### ISSUE TITLE
help command seems broken

### ISSUE THREAD

**Issue by jkoorts** [jhipster/generator-jhipster#10006]
C:\dev\java\bikebuddy\oem-hex-gateway>jhipster --help
INFO! Using JHipster version installed globally

  Spring Boot + Angular/React in one handy generator

C:\dev\java\bikebuddy\oem-hex-gateway>jhipster -help
INFO! Using JHipster version installed globally
Usage: jhipster [command] [options]

Options:
  -d, --debug                    enable debugger
  -V, --version                  output the version number
  -h, --help                     output usage information

Commands:
  app                            Create a new JHipster application based on the selected options
  aws                            Deploy the current application to Amazon Web Services
  aws-containers                 Deploy the current application to Amazon Web Services using ECS
  ci-cd                          Create pipeline scripts for popular Continuous Integration/Continuous Deployment tools
  cloudfoundry                   Generate a `deploy/cloudfoundry` folder with a specific manifest.yml to deploy to Cloud Foundry
  docker-compose                 Create all required Docker deployment configuration for the selected applications
  entity [name]                  Create a new JHipster entity: JPA entity, Spring server-side components and Angular client-side components
  export-jdl [jdlFile]           Create a JDL file from the existing entities
  gae                            Deploy the current application to Google App Engine
  heroku                         Deploy the current application to Heroku
  import-jdl [jdlFiles...]       Create entities from the JDL file passed in argument.
    By default everything is run in parallel. If you like to interact with the console use '--interactive' flag.
  info                           Display information about your current project and system
  kubernetes                     Deploy the current application to Kubernetes
  kubernetes-helm|k8s-helm       Deploy the current application to Kubernetes using Helm package manager
  languages [languages...]       Select languages from a list of available languages. The i18n files will be copied to the /webapp/i18n folder
  openshift                      Deploy the current application to OpenShift
  spring-service|service [name]  Create a new Spring service bean
  spring-controller [name]       Create a new Spring controller
  upgrade                        Upgrade the JHipster version, and upgrade the generated application
  completion                     Print command completion script
INFO!   For more info visit https://www.jhipster.tech
INFO!

**Comment by deepu105** [comment]
I confirm this. Seems like `jhipster -h` works fine but `jhipster --help` seems broken

**Comment by pascalgrimaud** [comment]
The problem comes from this PR https://github.com/jhipster/generator-jhipster/pull/9913
@dziemich : can you have a look plz ?
Otherwise, a quick solution would be to revert the commit.

**Comment by deepu105** [comment]
Lets revert that commit in the meantime since the improvement is not that
noticeable

**Comment by pascalgrimaud** [comment]
Ok, I'm doing this @deepu105
