### ISSUE TITLE
Type safe translation keys 

### ISSUE THREAD

**Issue by bonsmik** [jhipster/generator-jhipster#10002]
##### **Overview of the feature request**

Typescript could be used for "type safe localization". Currently translation keys are strings but with typescript config "resolveJsonModule" json files could be read and translate function could use type safe keys.

I suppose that typings would be read from the preferred language. Of course it leaves possible caveat that another used languages doesn't have same keys but that could be solved by comparing the translation files. 

I don't know would it be possible to achieve this without having all the translations in one file. Not sure though if there is reasons to have them in different files as they are now. 

I'm using React in client and not sure how this would with in Angular app.

Something like this

```
import translations from '../i18n/en/all_translations.json'; 
type Translations = typeof translations;

translate(key: Translations)
```

##### **Motivation for or Use Case**

I have used this style of typing in the past and it has helped me a lot and spared time to find why translations are not found.

##### **Related issues or PR**

Didn't find anything like this

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by bonsmik** [comment]
After a good night sleep I think that this could be implemented with separate translation files:

```
import activate from '../i18n/en/activate.json';
import audits from '../i18n/en/audits.json';
import configuration from '../i18n/en/configuration.json';
/* import all translation files */

export default { activate, audits, configuration /* a lot more exports */ };
```
And usage:
![i18n](https://user-images.githubusercontent.com/12121472/60322669-b141eb00-9988-11e9-836e-175e0b21e9a4.png)

**Comment by deepu105** [comment]
Honestly, I'm not sure if this is worth the effort(both in terms of maintaining this way and implementing it for all supported front ends)
It's nice to have type safety but IMO this is taking it too far.

**Comment by pascalgrimaud** [comment]
Agree with @deepu105 
It would be a lot of work for no real benefits.
