### ISSUE TITLE
Scope based authorization not working new Jwt Token Converter

### ISSUE THREAD

**Issue by anujgpatel** [jhipster/generator-jhipster#10018]
##### **Overview of the issue**

JHipster 6.1.0 added code for custom jwt token converter which generated GrantedAuthorities based on roles/groups claim value.  This implementation generated granted authorities purely based on that and dis-regards scp claim.

##### **Motivation for or Use Case**

Our controller uses authorization based on scope e.g. @org.springframework.security.access.prepost.PreAuthorize("hasAnyAuthority('SCOPE_jun10test:vendor','SCOPE_jun10test:thirdparty')")

##### **Reproduce the error**

Generate microservice with JHipster 6.1.0 or higher, select OAuth2 as authenticationType and add PreAuthorize annotation to one of the resources.
@org.springframework.security.access.prepost.PreAuthorize("hasAnyAuthority('SCOPE_jun10test:vendor','SCOPE_jun10test:thirdparty')")

##### **Related issues**

#9735 added this code for Jwt Token converter

##### **Suggest a Fix**

Here's the converter that should fix the problem.
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationConverter;

import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

public class CustomJwtAuthConverter extends JwtAuthenticationConverter {

    private static final String GROUP_CLAIM = "groups";
    private static final String GROUP_AUTHORITY_PREFIX = "ROLE_";

    @Override
    public Collection<GrantedAuthority> extractAuthorities(Jwt jwt) {
        Collection<GrantedAuthority> grantedAuthorities = super.extractAuthorities(jwt);
        List<String> groups = jwt.getClaimAsStringList(GROUP_CLAIM);
        if (groups != null) {
            List<GrantedAuthority> groupAuthorities = groups.stream()
                .map(group -> GROUP_AUTHORITY_PREFIX + group)
                .map(SimpleGrantedAuthority::new)
                .collect(Collectors.toList());
            grantedAuthorities.addAll(groupAuthorities);
        }
        return grantedAuthorities;
    }
}

The above converter extracts authorities from JwtAuthenticationConverter and adds additional authorities by reading groups claim (Can/should be updated to read the roles claim as well).
This will also require update to HttpSecurity in SecurityConfiguration.java as follows;
http
.....
.and()
            .oauth2ResourceServer().jwt().jwtAuthenticationConverter(new CustomJwtAuthConverter());

##### **JHipster Version(s)**

JHipster 6.1.2.  Could've been a regression from 6.1.0, but given the state it was in before that was even worse I wouldn't really call it regression.  

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "jhipsterVersion": "6.1.2",
    "applicationType": "microservice",
    "baseName": "july01test",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "@devex/generator-jhipster-nova-microservice",
        "version": "0.2.12"
      }
    ],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprint": "@devex/generator-jhipster-nova-microservice",
    "blueprintVersion": "0.2.12",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Policy {
  name String required,
  age Integer min(5)
}
microservice Policy with july01test
clientRootFolder Policy with july01test

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.21.0

node: v12.2.0

npm: 6.9.0

yeoman: 2.0.5

yarn: 1.13.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!```
Message Input

##### **Browsers and Operating System**

N/A

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
@anujgpatel, your change looks good. would you be able to raise PR? Please do note that #9874 also refactor this code.

**Comment by anujgpatel** [comment]
Yes, we will raise a PR for the above change

**Comment by vishal423** [comment]
As we don't use this flow in Jhipster generated apps, I would like to close it as lack of interest.

**Comment by pascalgrimaud** [comment]
Ok @vishal423, so let's close this
