### ISSUE TITLE
bower is broken on the "master" branch

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1002]
I don't how this happened, but the "master" branch is broken :-(
Creating a new project works, but no Bower dependency is installed, which of course makes the whole project unsuable. I checked with the v2.0.0 and it works, so it's something that has happened since the beginning of this week.
@andidev as you did several grunt-related commits, can you check if it's your fault?

I'm sorry, this week I had a lot of work and I didn't spend enough time validating the PRs

**Comment by andidev** [comment]
I'll have a look at it right away but I don't have any grunt related PR's that have been merged yet after version 2.0

**Comment by andidev** [comment]
Can't reproduce, what configuration did you use?

**Comment by jdubois** [comment]
OK, my fault... No idea what I did, I just deleted/recreated my app and it works...

**Comment by andidev** [comment]
Git is a bit of a mystery from time to time =)
