### ISSUE TITLE
Cannot disable or override SwaggerAutoConfiguration settings

### ISSUE THREAD

**Issue by micobarac** [jhipster/generator-jhipster#10034]
##### **Overview of the issue**

Cannot disable or override SwaggerAutoConfiguration settings. I want to add `securitySchemes`, `directModelSubstitute`, `securityContexts` and `apis` properties to the default Swagger docket, which is auto configured by jHipster.

##### **Motivation for or Use Case**

I want to be able to override default Swagger docket, without creating a new one, which forces me to create a new docket with new `groupName`, which I do not want.

##### **Reproduce the error**

```
package com.hellokoding.springboot.restful;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@SpringBootApplication
@EnableSwagger2
public class Application {
    @Bean
    public Docket swagger() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```

The error:

```
java.lang.IllegalStateException: Multiple Dockets with the same group name are not supported. The following duplicate groups were discovered. default
```

##### **Suggest a Fix**

Enable the option to disable or override `SwaggerAutoConfiguration`.

##### **JHipster Version(s)**

`6.1.2`

##### **JHipster Version(s)**

```
openprovider@0.0.0 /Users/milan/Sites/jhipster
└── generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.logate.openprovider"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "openprovider",
    "packageName": "com.logate.openprovider",
    "packageFolder": "com/logate/openprovider",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "yarn",
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 3.0.0

yarn: 1.16.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

macOS Mojave
Version 10.14.5 (18F132)

**Comment by cbornet** [comment]
Does it work if you annotate your bean with `@Primary` ?
Otherwise the autoconf accepts customizers so you should be able to override everything that's set by default.

**Comment by micobarac** [comment]
Yes, it worked with annotating my custom `@Bean` with `@Primary`.

**Comment by PierreBesson** [comment]
@micobarac You should rename your bean `swagger` -> `swaggerSpringfoxApiDocket` so that it will replace the autoconfiguration (see [SwaggerAutoConfiguration.java#L103](https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/config/apidoc/SwaggerAutoConfiguration.java#L103)). You can also stop enabling the `swagger` spring profile to disable our autoconfiguration and provide your own.

>Btw, I don't see a way to define securitySchemes, directModelSubstitute, securityContexts and apis properties via Swagger customizers.

Sorry I think StackOverflow is a more appropriate channel to get answer to this kind of questions about Springfox

As this is qualified to not be a bug. I'm closing the issue. Please add comments if you think otherwise.
