### ISSUE TITLE
Translation not found for validation messages when using DTO

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#10049]
When using DTOs the translation is not found for the fieldName` in validation messages,
this is because the objectName return by the server end with `DTO`, and the translation file doesn't end with it.

##### **Reproduce the error**
Generate a project with length validation (ex: minLength) disable client side validation, send the request.

##### **Suggest a Fix**
On the server, remove the DTO part if the culprit ends with DTO. 

##### **JHipster Version(s)**
6.1.2

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by clement26695** [comment]
Sorry, I didn't saw you already made a PR @yelhouti

**Comment by yelhouti** [comment]
@clement26695 no worries :)

**Comment by yelhouti** [comment]
@ruddell @pascalgrimaud any one wants to split the bounty? :)

**Comment by pascalgrimaud** [comment]
Thanks for proposing, but not for me :)
Take the bounty @yelhouti and if @ruddell wants one, he can claim one too
