### ISSUE TITLE
Existing Liquibase changelog files duplicated upon reimporting JDL file

### ISSUE THREAD

**Issue by maznag** [jhipster/generator-jhipster#10042]
##### **Overview of the issue**

When we make changes to a jdl file, and re-importe the model using 'jhipster import-jdl' command, the existing Liquibase changelog files are duplicated and the master is updated

##### **Motivation for or Use Case**

Existing changelog files shouldn't be duplicated.

##### **Reproduce the error**

1. Generate a new application
2. Create a JDL with an entity
3. Import jdl file
4. Modify a field in the JDL
4. Re-import it
5. See master.xml file and liquibase/changelog directory

##### **Related issues**
#9178 #8880

##### **JHipster Version(s)**

6.1.2

**Comment by clement26695** [comment]
I think it should be fixed with next version of jhipster-core (see: jhipster/jhipster-core#340)

**Comment by murdos** [comment]
Yes, I think it the same issue as https://github.com/jhipster/generator-jhipster/issues/9996 so closing this one as a duplicate.
