### ISSUE TITLE
Storing files outside of the database

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#10046]
##### **Overview of the feature request**

I know this might might be a sensitive issue for some, and this is clearly to start the discussion and weight the pros and cons, but wouldn't it be better to be able to store files outside of the database (using blobs...) 
##### **Motivation for or Use Case**

I feel that JHipster is teaching a lot of new comers the Spring/Angular (or React or Vue) stack, and that many people learn best practices here, so may be we should implement this (or perhaps have both options, and later encourage people to switch since this is HUGE breaking change...).
##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by amatosg** [comment]
I think this is a good idea, I had to find a way to upload all attachments to S3 to avoid having a very fat db.

**Comment by atomfrede** [comment]
I really like the idea as having e.g. images as base64 encoded strings in the API responses is quite suboptimal. Maybe we an support https://min.io/ which has an s3 compatible api and can be self hosted (but never tried it).

**Comment by yelhouti** [comment]
I personally would go with a simple write to disk to something like: `entityName.fieldName.id.extention` or `entityName.id.fieldName.extention`, and let kubernetes or anything else provision the persistence volume with S3, baremetal or whatever... I would also suggest adding an option filed with filename, and maybe drop saving the mime type in that database.

**Comment by avdev4j** [comment]
Hi,
I understand the issue but I think it's not a bad idea to use db,  by default, for storing files. We don't need a third party service and can be use even if you are behind a proxy or on local network.

So for best practices we should store files outside the db and use something like S3 but for some reasons use a db storage his still a solution for me.

Maybe we can let users choose and add a question or an option for db storage and minIO ?
We could add minIO docker image like we do for databases and manage generated entities depending on the option choosen.

**Comment by jdubois** [comment]
Storing files in the database isn't all bad, at least for a "small" usage. I totally agree you need something better if you're really having a lot of files, but then there's a lot of specific stuff to do depending on your business needs and the scale you want to achieve - I'm afraid this goes too far to be included in the main generator, and that it's going to be very hard to have something generic.

**Comment by vishal423** [comment]
We also took a similar approach in one of our projects to manage the binary data outside the database. While doing this, we also separated the life cycle of binary resources following Twitter APIs https://developer.twitter.com/en/docs/media/upload-media/overview

**Comment by pmverma** [comment]
This is really good to have if the project needs file uploading. But small or large files, public or private files, storing locally or to some cloud storage, frequency and volume of uploads. As @jdubois said, this goes too far and will be hard.

It would be better if Jhipster website has a page where we can add good&qualified links on **common** how-to on the generated projects.
JHipster cannot generate everything for its users but at least users will find information which they need in a single place and that is recommended by the team.

**Comment by deepu105** [comment]
We already have a tips and tricks section for this

**Comment by pascalgrimaud** [comment]
With all these comments, I think we agree to have this as a new tips.
Don't hesitate to create a new one @yelhouti 

I'm closing this as we won't implement a specific / dedicated solution for this in a main generator-jhipster.
