### ISSUE TITLE
spring.security.oauth2.client.registration.oidc.client-secret not validated 

### ISSUE THREAD

**Issue by anujgpatel** [jhipster/generator-jhipster#10045]
##### **Overview of the issue**

I have a jhipster 6 generated microservice with oauth2/oidc validation enabled(Spring Boot 2.1.4, Spring Security 5.1.5).  Corresponding application is registered with Okta and the application.yml has been updated with correct issuer-uri and client-id.  Though, I have configured it with wrong value for spring.security.oauth2.client.registration.oidc.client-secret. I would've expected the service to reject the token as it might not be able to validate it with the client secret it has, though it ends up serving the requested resource if presented with valid bearer token.

##### **Motivation for or Use Case**

If the app has wrong client secret, it should be surfaced.

##### **Reproduce the error**

Generate microservice using jhipster 6+
Enable OAuth2/oidc security
Register service_service application in okta 
Update service with right issuer-uri and client-id properties
Update service with wrong client-secret property
Run the microservice and invoke a protected resource by presenting valid bearer token

##### **Related issues**

No related issue

##### **Suggest a Fix**

Not sure how to fix

##### **JHipster Version(s)**

Jhipster 6.1.2

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
july-5-testfinal@0.0.0 /Users/apatel/workspace/july5testfinal
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "jhipsterVersion": "6.1.2",
    "applicationType": "microservice",
    "baseName": "july5testfinal",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "@devex/generator-jhipster-nova-microservice",
        "version": "0.3.0"
      }
    ],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprint": "@devex/generator-jhipster-nova-microservice",
    "blueprintVersion": "0.3.0",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

git version 2.19.0

node: v11.11.0

npm: 6.7.0

yeoman: 2.0.5

yarn: 1.13.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Do you have a `.yo-rc.json` file for your gateway app as well? I need to generate both a microservice and a gateway to verify this behavior.

**Comment by anujgpatel** [comment]
I have not generated gateway, I intend to use it as a standalone
microservice. Easiest way to verify this would be to follow the steps I
mentioned earlier and then using postman as follows;
Specify OAuth2 as auth type
Specify correct client-id, client-secret, appropriate scope and get the
token
Use token and perform GET on /services/<service name>/api/users

**Comment by mraible** [comment]
@anujgpatel This is not supported by our current OAuth 2.0 implementation. We expect you to have a gateway with your microservices.

**Comment by vishal423** [comment]
@mraible, Shouldn't behavior be the same for access via a gateway or directly via postman? As per my understanding, in both flows, micro-services API would be accessed by passing Bearer token in `Authorization` header. I think the concern raised in this issue is about incoming token validation against OIDC provider. Do we support that?

**Comment by anujgpatel** [comment]
@vishal423 That is one of the concerns, the other being, is the service secure enough? Because in its current state, it does not validate the signature of authorization server.

**Comment by mraible** [comment]
I asked a co-worker (@bdemers) about this issue. Here's what he said:

> Spring Security doesn’t use the client-id or client-secret when validating an access token (via a Bearer auth header).
> 
> The next version of Spring Security will support opaque tokens (i.e. remote validate per OAuth spec). Something like http.oauth2ResourceServer().opaqueToken() ... ( Instead of `.jwt()` )

**Comment by anujgpatel** [comment]
Jhipster is using WebSecurityConfigurerAdapter that does not allow to do online token validation. After we changed it manually to ResourceServerConfigurerAdapter and override configure method as follows, it does end up performing online token validation;
@Override
    public void configure(ResourceServerSecurityConfigurer resources) {
        RemoteTokenServices remoteTokenServices = new RemoteTokenServices();
        remoteTokenServices.setAccessTokenConverter(new OktaAccessTokenConverter());
        remoteTokenServices.setClientId(clientId);
        remoteTokenServices.setClientSecret(clientSecret);
//        remoteTokenServices.setClientSecret("lkaasdfasdfsdaf"); If you gave bogus value here, it will reject token
        remoteTokenServices.setCheckTokenEndpointUrl(serviceIntrospectUrl); // e.g. your-okta-auth-server/v1/introspect
        resources.tokenServices(remoteTokenServices);
        resources.resourceId(resourceId);
    }
