### ISSUE TITLE
JHipster K8s Operator

### ISSUE THREAD

**Issue by salaboy** [jhipster/generator-jhipster#10053]
##### **Overview of the feature request**

Integrating with Kubernetes requires more than just the Kubernetes Manifest to get our containers running inside the platform. The JHipster Kubernetes Operator will enable JHipster MicroService Applications (projects) to be managed and understood by the platform in a native way. 
Related to my presentation in JHipster Conf 2: https://salaboy.com/2019/07/03/jhipster-conf-rocks/
Source code(first stab at it): https://github.com/salaboy/jhipster-operator
Video: https://youtu.be/9iqTtwptTT8
##### **Motivation for or Use Case**

This Operator will have the following responsibilities:
1) Provide custom resource definitions for JHipster Applications(Project), Microservices, Gateways and Registries (at least in the first iteration)
2) Understand how Applications are wired together (the relationships between different 'application's inside an app.jdl file. 
3) Manage the lifecycle of an entire Application (set of Microservices and their dependencies) and check their state
4) Route traffic only for healthy applications (all the services are healthy)
5) Provide an extension point for domain specific requirements and integrations with other Kubernetes Components, such as Istio, Knative, etc.  

You can find the PR for the [RFC here](https://github.com/jhipster/generator-jhipster/issues/10053)

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/9348

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by salaboy** [comment]
PR for the RFC done: https://github.com/jhipster/generator-jhipster/pull/10054

**Comment by DanielFran** [comment]
@PierreBesson  Should we delete this PR now that the RFC has been merged?
