### ISSUE TITLE
Feature Request: Add 'skip-liquibase' flag to 'import-jdl'

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#10059]
##### **Overview of the feature request**

When re-importing a JDL file, jhipster updates the xml files with the updated entities, but after the project has been already deployed those files should not be updated but new changelogs should be generated with `liquibase:diff`.

##### **Motivation for or Use Case**

It would be really helpful for projects that have been already deployed to production to avoid liquibase, specially if using the `--interactive` flag.

##### **Related issues or PR**

No similar feature available

-   [x] Checking this box is mandatory (this is just to show you read everything)

https://opencollective.com/generator-jhipster/donate

**Comment by DanielFran** [comment]
Probably related with https://github.com/jhipster/jhipster-core/issues/341 and https://github.com/jhipster/generator-jhipster/issues/9996

Should be fixed with https://github.com/jhipster/jhipster-core/pull/340.

Can you confirm?

**Comment by amatosg** [comment]
Hi @DanielFran , this is actually not an issue but a feature request. the flag `skip-liquibase` doesn't exists and I think this would help projects that are already deployed and original liquibase files shouldn't be edited by the JDL import command.

What do you think?

**Comment by amatosg** [comment]
@DanielFran I think you should change the tags as it's not a bug report, rather is a feature request :)

**Comment by pascalgrimaud** [comment]
Can't you just use git to revert the specific folder, related to liquibase ?

**Comment by PierreBesson** [comment]
I think rather than this being a `--skip-liquibase` flag, it could be a `--update` flag. This way it could be used during generation as a heuristic that this is not a first generation.

**Comment by amatosg** [comment]
but what would it mean to use `--update`? it wouldn't be clear about what is not being regenerated, while using `--skip-liquibase` you know exactly what will happen
