### ISSUE TITLE
Compilation error gateway without cacheProvider

### ISSUE THREAD

**Issue by nonomoho** [jhipster/generator-jhipster#10055]
##### **Overview of the issue**

javax.cache.* is still used in RateLimitingFilter.java when there is **no** cacheProvider.

##### **Motivation for or Use Case**

Compilation failed

##### **Reproduce the error**

I use this jdl to generate my app:

```jdl
 
application {
    config {
        applicationType gateway,
        baseName demogateway,
        serverPort 18081,
        packageName com.jhipster.demogateway,
        serviceDiscoveryType consul,
        authenticationType oauth2,
        databaseType no,
        cacheProvider no,
        buildTool maven,
        messageBroker kafka,
        clientFramework angularX,
        useSass true,
        enableTranslation true,
        nativeLanguage en,
        languages [en, al, ar-ly, hy, zh-cn, fr, de, in, it, pt-pt, ru, sr, es, tr, th, ua, uz-Latn-uz, vi],
        testFrameworks [gatling, protractor],
    }
    entities *
}
```

##### **JHipster Version(s)**

JHipster v6.1.2

##### **JHipster Version(s)**

```
customer-gateway@0.0.0 /Users/arnaudfreismuth/Documents/***
└── generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "no",
    "devDatabaseType": "no",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "al",
      "ar-ly",
      "hy",
      "zh-cn",
      "fr",
      "de",
      "in",
      "it",
      "pt-pt",
      "ru",
      "sr",
      "es",
      "tr",
      "th",
      "ua",
      "uz-Latn-uz",
      "vi"
    ],
    "messageBroker": "kafka",
    "nativeLanguage": "en",
    "packageName": "com.***",
    "packageFolder": "com/***",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "serviceDiscoveryType": "consul",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": ["gatling", "protractor"],
    "websocket": false,
    "applicationType": "gateway",
    "baseName": "customer_gateway",
    "serverPort": "18081",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "buildTool": "maven",
    "clientFramework": "angularX",
    "useSass": true,
    "jhipsterVersion": "6.1.2",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "entities": []
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment Zulu11.31+11-CA (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)

git version 2.20.1 (Apple Git-117)

node: v10.15.3

npm: 6.4.1

yeoman: 2.0.6

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
seems related to #9867

**Comment by nonomoho** [comment]
Yes, sorry I didn't see that!
