### ISSUE TITLE
Heroku sub-generator runs the entire build on Heroku server

### ISSUE THREAD

**Issue by anshumanpurohit** [jhipster/generator-jhipster#1006]
yo jhipster:heroku not only creates/pushes the Heroku app, it runs the entire build, including CSS preprocessing etc., on the Heroku server. To me Heroku is a run-time servers, and build time concerns/dependency should not bleed to that environment.

**Comment by jdubois** [comment]
No, that's how you are supposed to work with Heroku, you push your source code and it builds the app.
Have a look at https://devcenter.heroku.com/articles/getting-started-with-java#deploy-the-app -> the Maven build is done on the Heroku side.
In our case, the production build is done locally, and commited to Heroku, so we are half-way between what you want (which isn't what we should do) and how Heroku works.

**Comment by anshumanpurohit** [comment]
What is actually compiled and committed to Heroku? I think middle ground is ok, but the JavaScript and CSS preprocessing should be done on CI servers off Heroku servers.

**Comment by jdubois** [comment]
What is sent to Heroku is in your deploy/heroku folder
JS and CSS preprocessing are done and commited locally

**Comment by anshumanpurohit** [comment]
Thanks @jdubois !
It seems JS and CSS preprocessing is done committed locally using the `prod` maven profile and the `dev
