### ISSUE TITLE
LogstashTcpSocketAppender seems broken

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#10065]
##### **Overview of the issue**
LogstashTcpSocketAppender seems broken.

logs:
````txt
09:40:38,682 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Log destination localhost/127.0.0.1:5000: connection failed. java.net.ConnectException: Connection refused (Connection refused)
	at java.net.ConnectException: Connection refused (Connection refused)
	at 	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at 	at java.net.Socket.connect(Socket.java:589)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.openSocket(AbstractLogstashTcpSocketAppender.java:586)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onStart(AbstractLogstashTcpSocketAppender.java:508)
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onStart(AsyncDisruptorAppender.java:351)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.notifyStart(BatchEventProcessor.java:224)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:120)
	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at 	at java.lang.Thread.run(Thread.java:748)
09:40:38,696 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Log destination localhost/127.0.0.1:5000: Waiting 29983ms before attempting reconnection.
09:40:38,694 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - 'FileNamePattern' option has the same value "/tmp/spring.log.%d{yyyy-MM-dd}.%i.gz" as that given for appender [FILE] defined earlier.
09:40:38,697 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Collisions detected with FileAppender/RollingAppender instances defined earlier. Aborting.
09:40:38,697 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - For more information, please visit http://logback.qos.ch/codes.html#earlier_fa_collision
````

##### **JHipster Version(s)**

See current master

**Comment by DanielFran** [comment]
@PierreBesson looking at LogstashTcpSocketAppender [documentation](https://github.com/logstash/logstash-logback-encoder#tcp-appenders) and issue https://github.com/logstash/logstash-logback-encoder/issues/252, it seems that we don't need to wrap the LogstashTcpSocketAppender with an AsyncAppender, since the LogstashTcpSocketAppender itself is asynchronous (it'll never block the logging thread).
````txt
Internally, the TCP appenders are asynchronous (using the LMAX Disruptor RingBuffer).
All the encoding and TCP communication is delegated to a single writer thread.
There is no need to wrap the TCP appenders with another asynchronous appender (such as AsyncAppender or LoggingEventAsyncDisruptorAppender).
````
So looking at our [code](https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/config/logging/LoggingUtils.java#L67-L88):
````java
    public static void addLogstashTcpSocketAppender(LoggerContext context, String customFields,
                                                    JHipsterProperties.Logging.Logstash logstashProperties) {
        log.info("Initializing Logstash loggingProperties");


        // More documentation is available at: https://github.com/logstash/logstash-logback-encoder
        LogstashTcpSocketAppender logstashAppender = new LogstashTcpSocketAppender();
        logstashAppender.addDestinations(new InetSocketAddress(logstashProperties.getHost(), logstashProperties.getPort()));
        logstashAppender.setContext(context);
        logstashAppender.setEncoder(logstashEncoder(customFields));
        logstashAppender.setName(LOGSTASH_APPENDER_NAME);
        logstashAppender.start();


        // Wrap the appender in an Async appender for performance
        AsyncAppender asyncLogstashAppender = new AsyncAppender();
        asyncLogstashAppender.setContext(context);
        asyncLogstashAppender.setName(ASYNC_LOGSTASH_APPENDER_NAME);
        asyncLogstashAppender.setQueueSize(logstashProperties.getQueueSize());
        asyncLogstashAppender.addAppender(logstashAppender);
        asyncLogstashAppender.start();


        context.getLogger(ch.qos.logback.classic.Logger.ROOT_LOGGER_NAME).addAppender(asyncLogstashAppender);
    }
```` 

We can transform it to:
````java
    public static void addLogstashTcpSocketAppender(LoggerContext context, String customFields,
                                                    JHipsterProperties.Logging.Logstash logstashProperties) {
        log.info("Initializing Logstash loggingProperties");


        // More documentation is available at: https://github.com/logstash/logstash-logback-encoder
        LogstashTcpSocketAppender logstashAppender = new LogstashTcpSocketAppender();
        logstashAppender.addDestinations(new InetSocketAddress(logstashProperties.getHost(), logstashProperties.getPort()));
        logstashAppender.setContext(context);
        logstashAppender.setEncoder(logstashEncoder(customFields));
        logstashAppender.setName(LOGSTASH_APPENDER_NAME);
        logstashAppender.setQueueSize(logstashProperties.getQueueSize());
        logstashAppender.start();

context.getLogger(ch.qos.logback.classic.Logger.ROOT_LOGGER_NAME).addAppender(logstashAppender);
    }
````

**Comment by PierreBesson** [comment]
It might have been broken because of an upgrade of logstash-encoder. Please go forward with any fix necessary. 

As for why we have wrapped the tcpappender in the asyncappender, it's just that we were using the udpAppender before so it was kept during the migration from udp to tcp.

**Comment by micobarac** [comment]
[https://github.com/jhipster/generator-jhipster/issues/10052](https://github.com/jhipster/generator-jhipster/issues/10052)

**Comment by gmarziou** [comment]
> it seems that we don't need to wrap the LogstashTcpSocketAppender with an AsyncAppender, since the LogstashTcpSocketAppender itself is asynchronous 

Interesting.
Also, the  AsyncAppender  by default drops all events with level higher then WARN (DEBUG and INFO) when queue is 80% full. This behavior is something I wanted for applications logs but not for metrics which are logged as INFO. I had to set a threshold of 0 and a larger event queue to avoid droppping metrics under havey load.

Do we have similar behavior with LogstashTcpSocketAppender ?

**Comment by DanielFran** [comment]
Probably yes since logstash documentation describe that it works like a AsyncAppender.

**Comment by gmarziou** [comment]
I had a look and could not see such behavior implemented so I guess it a difference with previous implementation. Now events can be dropped whatever their level is when ring is full, previously the AsyncAppender would try to keep ERROR and WARN as much as possible which seems a good strategy to me. 

In my app, I also preferred to have 2 logstash appenders: one for application logs and one for metrics, it enabled to have a larger queue size for metrics which is fine because metrics events are smaller and I prefer to still get metrics under heavy load. JHipster's approach is to use one single logback appender with a metrics Marker, I don't know what are the benefits.

**Comment by sw-enthusiast** [comment]
> @PierreBesson looking at LogstashTcpSocketAppender [documentation](https://github.com/logstash/logstash-logback-encoder#tcp-appenders) and issue [logstash/logstash-logback-encoder#252](https://github.com/logstash/logstash-logback-encoder/issues/252), it seems that we don't need to wrap the LogstashTcpSocketAppender with an AsyncAppender, since the LogstashTcpSocketAppender itself is asynchronous (it'll never block the logging thread).
> 
> ```
> Internally, the TCP appenders are asynchronous (using the LMAX Disruptor RingBuffer).
> All the encoding and TCP communication is delegated to a single writer thread.
> There is no need to wrap the TCP appenders with another asynchronous appender (such as AsyncAppender or LoggingEventAsyncDisruptorAppender).
> ```
> 
> So looking at our [code](https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/config/logging/LoggingUtils.java#L67-L88):
> 
> ```java
>     public static void addLogstashTcpSocketAppender(LoggerContext context, String customFields,
>                                                     JHipsterProperties.Logging.Logstash logstashProperties) {
>         log.info("Initializing Logstash loggingProperties");
> 
> 
>         // More documentation is available at: https://github.com/logstash/logstash-logback-encoder
>         LogstashTcpSocketAppender logstashAppender = new LogstashTcpSocketAppender();
>         logstashAppender.addDestinations(new InetSocketAddress(logstashProperties.getHost(), logstashProperties.getPort()));
>         logstashAppender.setContext(context);
>         logstashAppender.setEncoder(logstashEncoder(customFields));
>         logstashAppender.setName(LOGSTASH_APPENDER_NAME);
>         logstashAppender.start();
> 
> 
>         // Wrap the appender in an Async appender for performance
>         AsyncAppender asyncLogstashAppender = new AsyncAppender();
>         asyncLogstashAppender.setContext(context);
>         asyncLogstashAppender.setName(ASYNC_LOGSTASH_APPENDER_NAME);
>         asyncLogstashAppender.setQueueSize(logstashProperties.getQueueSize());
>         asyncLogstashAppender.addAppender(logstashAppender);
>         asyncLogstashAppender.start();
> 
> 
>         context.getLogger(ch.qos.logback.classic.Logger.ROOT_LOGGER_NAME).addAppender(asyncLogstashAppender);
>     }
> ```
> 
> We can transform it to:
> 
> ```java
>     public static void addLogstashTcpSocketAppender(LoggerContext context, String customFields,
>                                                     JHipsterProperties.Logging.Logstash logstashProperties) {
>         log.info("Initializing Logstash loggingProperties");
> 
> 
>         // More documentation is available at: https://github.com/logstash/logstash-logback-encoder
>         LogstashTcpSocketAppender logstashAppender = new LogstashTcpSocketAppender();
>         logstashAppender.addDestinations(new InetSocketAddress(logstashProperties.getHost(), logstashProperties.getPort()));
>         logstashAppender.setContext(context);
>         logstashAppender.setEncoder(logstashEncoder(customFields));
>         logstashAppender.setName(LOGSTASH_APPENDER_NAME);
>         logstashAppender.setQueueSize(logstashProperties.getQueueSize());
>         logstashAppender.start();
> 
> context.getLogger(ch.qos.logback.classic.Logger.ROOT_LOGGER_NAME).addAppender(logstashAppender);
>     }
> ```

This change did not fix the problem for me running mvn clean install and it fails for the "default" profile.

**Comment by DanielFran** [comment]
This is not the fix for this issue but just an enhancement.

**Comment by PierreBesson** [comment]
@gmarziou is making a good points on the dropping strategy and how we could configure smart defaults for this. Personally, I have not used the logback appender to report logs for a long-time as recent projects that I have worked on exported logs from the docker driver (
(Kubernetes) or AWS cloudwatch. But personally I like the solution that we offer in JHipster. However it seems that it's not the current trend as it is not "cloud native" and also java specific.

**Comment by DanielFran** [comment]
+1 Never used it.

**Comment by PierreBesson** [comment]
It's a bit sad that it's the two of us maintaining this even though we don't use it and we get little feedback on it. But anyway I would like to continue pushing this solution for a while because I think it is really simple to use and useful for small projects / startups to get quickly started on monitoring.

So I will investigate the bug as soon as I have time

**Comment by micobarac** [comment]
Is there an option to disable logstash entirely, until this issue gets resolved?

**Comment by gmarziou** [comment]
How does it fail? 

If you have upgraded jhipster-framework to master, then it should be `isInstanceOf(LogstashTcpSocketAppender.class)`.

**Comment by micobarac** [comment]
It fails if I turn logstash to false for test application.yaml.

**Comment by gmarziou** [comment]
Could you paste the error?

**Comment by micobarac** [comment]
I commented out the `testLogstashAppender()` method, as it fails to assert, because it asserts to null value:

`assertThat(context.getLogger("ROOT").getAppender("ASYNC_LOGSTASH")).isInstanceOf(AsyncAppender.class);`

**Comment by gmarziou** [comment]
@micobarac where does this `testLogstashAppender()` comes from? I can't find it in current code base,was it generated from an older version? If so, I suspect it's obsolete and should be removed from your project.

**Comment by micobarac** [comment]
It comes from LogsResourceIT.java, which was probably generated by an older version of JHipster. I will remove this IT.

**Comment by gmarziou** [comment]
@DanielFran I could not reproduce, I generated a monolith with 6.2.0, enabled logstash in application-dev.yml, started the jhipster-console with docker-compose and started the app with mvnw I got no error. Please clarify your setup.

**Comment by DanielFran** [comment]
@gmarziou you can check on the majority of the CIs the error is present...

**Comment by PierreBesson** [comment]
I also don't understand this issue. What are the steps to reproduce ?

**Comment by gmarziou** [comment]
But in CI, is jhipster-console ready to ingest logs?

**Comment by DanielFran** [comment]
There is no failed build, only warnings/errors that appears during the tests that were not present some months ago...

https://travis-ci.org/jhipster/generator-jhipster/jobs/569755854#L5131

**Comment by gmarziou** [comment]
OK but 20-docker-compose.sh does not start the jhipster-console so why using logstash in CI if there's no logstash server to listen?

**Comment by nonomoho** [comment]
We had the problem in our current project with @pascalgrimaud. To fix it, we disabled logstash appender.

**Comment by pascalgrimaud** [comment]
Thanks @nonomoho !
Good catch
