### ISSUE TITLE
False positive error when using cassandra as DB on a microservice JDL

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#10066]
##### **Overview of the issue**

When a JDL file has an application with Cassandra, there is an error during import-jdl which seems wrong as the JDL is valid(At least it looks valid)

##### **Reproduce the error**

Run `jhipster import-jdl` with given JDL and it gives below
```
❯ jhipster import-jdl app.jdl 
INFO! Using JHipster version installed globally
INFO! Executing import-jdl app.jdl
INFO! Options: from-cli: true
INFO! The JDL is being parsed.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
Error: Cassandra entities don't have relationships.
Error while parsing applications and entities from the JDL Error: Cassandra entities don't have relationships.
Error: Cassandra entities don't have relationships.
    at checkNoSQLModeling (/home/deepu/.nvm/versions/node/v10.13.0/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/parser/entity_parser.js:82:11)
    at Object.parse (/home/deepu/.nvm/versions/node/v10.13.0/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/parser/entity_parser.js:63:5)
    at getJSONEntities (/home/deepu/.nvm/versions/node/v10.13.0/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:155:23)
    at jdlObject.forEachApplication.application (/home/deepu/.nvm/versions/node/v10.13.0/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:137:28)
    at Object.keys.forEach.applicationName (/home/deepu/.nvm/versions/node/v10.13.0/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_object.js:90:7)
    at Array.forEach (<anonymous>)
    at JDLObject.forEachApplication (/home/deepu/.nvm/versions/node/v10.13.0/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_object.js:88:36)
    at importApplicationsAndEntities (/home/deepu/.nvm/versions/node/v10.13.0/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:136:15)
    at JDLImporter.import (/home/deepu/.nvm/versions/node/v10.13.0/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:72:26)
    at JDLProcessor.importJDL (/home/deepu/.nvm/versions/node/v10.13.0/lib/node_modules/generator-jhipster/cli/import-jdl.js:76:41)

```

##### **Suggest a Fix**

Validate individual application with their entities

##### **JHipster Version(s)**

6.1.2

##### **JHipster configuration**

<details>
<summary>JDL definition</summary>

<pre>
/*
 * This is a microservice e-commerce store sample with Gateway and three microservice applications
 * This uses JHipster registry for service discovery and JWT authentication
 */
 
application {
  config {
    baseName store,
    applicationType gateway,
    packageName com.jhipster.demo.store,
    serviceDiscoveryType eureka,
    authenticationType jwt,
    prodDatabaseType mysql,
    cacheProvider hazelcast,
    buildTool gradle,
    clientFramework react,
    useSass true,
    testFrameworks [protractor]
  }
  entities *
}

application {
  config {
    baseName product,
    applicationType microservice,
    packageName com.jhipster.demo.product,
    serviceDiscoveryType eureka,
    authenticationType jwt,
    prodDatabaseType postgresql,
    cacheProvider hazelcast,
    buildTool gradle,
    serverPort 8081,
    skipUserManagement true
  }
  entities Product, ProductCategory, ProductOrder, OrderItem
}

application {
  config {
    baseName invoice,
    applicationType microservice,
    packageName com.jhipster.demo.invoice,
    serviceDiscoveryType eureka,
    authenticationType jwt,
    prodDatabaseType mariadb,
    cacheProvider no,
    enableHibernateCache false,
    buildTool gradle,
    serverPort 8082,
    skipUserManagement true
  }
  entities Invoice, Shipment
}

application {
  config {
    baseName notification,
    applicationType microservice,
    packageName com.jhipster.demo.notification,
    serviceDiscoveryType eureka,
    authenticationType jwt,
    databaseType mongodb,
    cacheProvider no,
    enableHibernateCache false,
    buildTool gradle,
    serverPort 8083,
    skipUserManagement true
  }
  entities Notification
}

application {
  config {
    baseName payments,
    applicationType microservice,
    packageName com.jhipster.demo.payments,
    serviceDiscoveryType eureka,
    authenticationType jwt,
    databaseType cassandra,
    cacheProvider no,
    enableHibernateCache false,
    buildTool gradle,
    serverPort 8084,
    skipUserManagement true
  }
}

/* Entities for Store Gateway */

entity Customer {
    firstName String required
    lastName String required
    gender Gender required
    email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)
    phone String required
    addressLine1 String required
    addressLine2 String
    city String required
    country String required
}

enum Gender {
    MALE, FEMALE, OTHER
}

relationship OneToOne {
    Customer{user(login) required} to User
}

service Customer with serviceClass
paginate Customer with pagination

/** Product sold by the Online store */
entity Product {
    name String required
    description String
    price BigDecimal required min(0)
    size Size required
    image ImageBlob
}

enum Size {
    S, M, L, XL, XXL
}

entity ProductCategory {
    name String required
    description String
}

entity ProductOrder {
    placedDate Instant required
    status OrderStatus required
    code String required
    invoiceId Long
    customer String required
}

enum OrderStatus {
    COMPLETED, PENDING, CANCELLED
}

entity OrderItem {
    quantity Integer required min(0)
    totalPrice BigDecimal required min(0)
    status OrderItemStatus required
}

enum OrderItemStatus {
    AVAILABLE, OUT_OF_STOCK, BACK_ORDER
}

relationship ManyToOne {
	OrderItem{product(name) required} to Product
}

relationship OneToMany {
   ProductOrder{orderItem} to OrderItem{order(code) required} ,
   ProductCategory{product} to Product{productCategory(name)}
}

service Product, ProductCategory, ProductOrder, OrderItem with serviceClass
paginate Product, ProductOrder, OrderItem with pagination
microservice Product, ProductOrder, ProductCategory, OrderItem with product

/* Entities for Invoice microservice */
entity Invoice {
    code String required
    date Instant required
    details String
    status InvoiceStatus required
    paymentMethod PaymentMethod required
    paymentDate Instant required
    paymentAmount BigDecimal required
}

enum InvoiceStatus {
    PAID, ISSUED, CANCELLED
}

entity Shipment {
    trackingCode String
    date Instant required
    details String
}

enum PaymentMethod {
    CREDIT_CARD, CASH_ON_DELIVERY, PAYPAL
}

relationship OneToMany {
    Invoice{shipment} to Shipment{invoice(code) required}
}

service Invoice, Shipment with serviceClass
paginate Invoice, Shipment with pagination
microservice Invoice, Shipment with invoice

/* Entities for notification microservice */

entity Notification {
    date Instant required
    details String
    sentDate Instant required
    format NotificationType required
    userId Long required
    productId Long required
}

enum NotificationType {
    EMAIL, SMS, PARCEL
}

microservice Notification with notification

/**
 * Deployments
 */

deployment {
  deploymentType kubernetes
  appsFolders [store, invoice, notification, product, payments]
  dockerRepositoryName "deepu105"
  serviceDiscoveryType eureka
  kubernetesServiceType LoadBalancer
  kubernetesNamespace xl-demo
}
</pre>
</details>

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by clement26695** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/9710
