### ISSUE TITLE
listen EADDRINUSE: address already in use 127.0.0.1:9060

### ISSUE THREAD

**Issue by shougao** [jhipster/generator-jhipster#10079]
##### **Overview of the issue**

when separate run microservice - gateway service, using npm start and IDEA ruan server side.
after run 'npm start' i got the message 

Error: listen EADDRINUSE: address already in use 127.0.0.1:9060

below is the detail message. 

Webpack: Starting ...
Starting type checking service...
Webpack: Starting ...

  ✔ Compile modules
  ❯ Build modules (1%)
    → 3 of 3 modules :: 
[HPM] Proxy created: [ '/api',
  '/services',
  '/management',
  '/swagger-resources',
  '/v2/api-docs',
  '/h2-console',
  '/auth' ]  ->  http://localhost:8080
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:9060
    at Server.setupListenHandle [as _listen2] (net.js:1290:14)
    at listenInCluster (net.js:1338:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1471:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1317:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gateway@0.0.0 webpack-dev-server: `node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "webpack/webpack.dev.js" "--inline" "--hot" "--port=9060" "--watch-content-base" "--env.stats=minimal"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gateway@0.0.0 webpack-dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eric/.npm/_logs/2019-07-12T06_58_38_240Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gateway@0.0.0 webpack:dev: `npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --hot --port=9060 --watch-content-base --env.stats=minimal`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gateway@0.0.0 webpack:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eric/.npm/_logs/2019-07-12T06_58_38_280Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gateway@0.0.0 start: `npm run webpack:dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gateway@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eric/.npm/_logs/2019-07-12T06_58_38_319Z-debug.log

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
That's because you have two gateways or monoliths running at the same time. Basically you ran twice `npm start` and both commands open up the same port.
