### ISSUE TITLE
jib / openshift / chmod +x entrypoint.sh workaround

### ISSUE THREAD

**Issue by jsm174** [jhipster/generator-jhipster#10071]
##### **Overview of the issue**

As stated in the openshift docs at https://www.jhipster.tech/openshift:

```
If you face any issue in running the image built by jib plugin (like chmod +x entrypoint.sh not permitted), then you might have to update scc. Do the following change, oc edit scc restricted and update runAsUser.Type strategy to RunAsAny
```

Unfortunately, we are working in an Openshift environment managed by a team that is unwilling to allow us to do this.

We updated the `docker.gradle` and modified jib to use the `extraDirectories.permissions` feature:

``` 
jib {
    from {
        image = "adoptopenjdk:11-jre-hotspot"
    }
    to {
        image = "gateway:latest"
    }
    container {
        entrypoint = ["sh", "-c", "./entrypoint.sh"]
        ports = ["8080"]
        environment = [
            SPRING_OUTPUT_ANSI_ENABLED: "ALWAYS",
            JHIPSTER_SLEEP: "0"
        ]
        useCurrentTimestamp = true
    }
    extraDirectories {
       permissions = [
          '/entrypoint.sh': '755'
       ]
    }
}
```

This seems to be working for us. 

If this seems reasonable, I would be willing to submit a PR. 

If this is wrong, and I'm missing something obvious, then feedback would be appreciated. 
 

##### **Motivation for or Use Case**

Allow jibs to work in openshift without changes.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/8887

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/jmillard/git/jh610-cors-issue-demo/gateway
└── generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "no",
    "devDatabaseType": "no",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.example.gateway",
    "packageFolder": "com/example/gateway",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "gateway",
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "buildTool": "gradle",
    "jhipsterVersion": "6.1.2",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "ehcache",
    "serverPort": "8080",
    "clientFramework": "angularX",
    "useSass": true,
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "entities": [
    "Blog"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  title String required
}
paginate Blog with pagination
microservice Blog with blog

</pre>
</details>

##### **Environment and Tools**

openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.1+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.1+12, mixed mode, sharing)

git version 2.20.1 (Apple Git-117)

node: v10.15.3

npm: 6.4.1

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Hi @jsm174, sorry for the late reply.
I don't see a problem with this improvement. it's going to be useful for many people who mess up their permissions. Can you submit a PR ? Can you also do it for maven :pray: ?

**Comment by jsm174** [comment]
@PierreBesson no worries. I'll work on a PR!

**Comment by jsm174** [comment]
@PierreBesson 

So I have the PR ready to go. During testing, I can't get the maven xml to work. If I'm reading the documentation correctly, this is supposed to be the format:

```
                        <container>
                            <entrypoint>
                                <shell>sh</shell>
                                <option>-c</option>
                                <arg>/entrypoint.sh</arg>
                            </entrypoint>
                            <ports>
                                <port>8081</port>
                                <port>5701/udp</port>
                            </ports>
                            <environment>
                                <SPRING_OUTPUT_ANSI_ENABLED>ALWAYS</SPRING_OUTPUT_ANSI_ENABLED>
                                <JHIPSTER_SLEEP>0</JHIPSTER_SLEEP>
                            </environment>
                            <useCurrentTimestamp>true</useCurrentTimestamp>
                        </container>
                        <extraDirectories>
                            <permissions>
                                <permission>
                                    <file>/entrypoint.sh</file>
                                    <mode>755</mode>
                                </permission>
                            </permissions>
                        </extraDirectories>
                    </configuration>
```

If I run it from the command line:

```
./mvnw package -Pprod jib:dockerBuild -Djib.extraDirectories.permissions="/entrypoint.sh"="755"
```

It works perfectly. I'm not a maven expert, any ideas?

**Comment by DanielFran** [comment]
@jsm174 Di you forget to define the paths in extraDirectories?
See jib documentation https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#adding-arbitrary-files-to-the-image:
<paths>src/main/custom-extra-dir</paths>

**Comment by jsm174** [comment]
@DanielFran. Thx. You don't have define `paths` because `entrypoint.sh` exists in the root directory. 

The gradle version looks just like this:

```
    extraDirectories {
       permissions = [
          '/entrypoint.sh': '755'
       ]
    }
```

I did try though with a `<paths>/<paths>` and it threw an error.

**Comment by PierreBesson** [comment]
@jsm174 do you have the time to submit the PR ?
For the syntax, just guessing, but it might be :
```
<paths>
<path>/</path>
</paths>
```

**Comment by Fenglei-Pan** [comment]
This configuration works for maven build:
`<container>
    <entrypoint>
        <shell>sh</shell>
        <option>-c</option>
	    <arg>/entrypoint.sh</arg>
    </entrypoint>
    <ports>
        <port>8081</port>
        <port>5701/udp</port>
    </ports>
    <environment>                                
        <SPRING_OUTPUT_ANSI_ENABLED>ALWAYS</SPRING_OUTPUT_ANSI_ENABLED>
        <JHIPSTER_SLEEP>0</JHIPSTER_SLEEP>
    </environment>
    <useCurrentTimestamp>true</useCurrentTimestamp>
</container>
<extraDirectories>
    <paths>src/main/jib</paths>
    <permissions>
        <permission>
            <file>/entrypoint.sh</file>
             <mode>755</mode>
        </permission>
    </permissions>
</extraDirectories>`

**Comment by PierreBesson** [comment]
Thank you @fenglei-pan, would you like to try and submit a PR ?

**Comment by pascalgrimaud** [comment]
Opened since 3 months, and no PR to improve this. 
It looks like people don't use Openshift a lot or maybe don't care, so let's close this, because of lack of interest.

Anyway, the solution are mentionned in this ticket.

**Comment by DanielFran** [comment]
Reopened since I did found the same issue.
