### ISSUE TITLE
Implement project generator as web page, like Spring Initializr

### ISSUE THREAD

**Issue by peter-gergely-horvath** [jhipster/generator-jhipster#10076]
##### **Overview of the feature request**

The current solution where the project generator has to be installed to the user's machine is quite cumbersome: since Java developers do not necessarily have Node installed by default, first you have to install Node properly, then download the generator application, and then generate your project from a command line wizard.

It would be great if JHipster had a web-page based generator like [Spring Initializr ](https://start.spring.io/), where you have a simple wizard and can simply download the generated project as a ZIP

##### **Motivation for or Use Case**

User experience/simplicity improvement: Java developers do not necessarily have Node installed. Getting a Node runtime installed just for the generator is cumbersome.

Simpler usage would help further adoption. 

##### **Related issues or PR**

No, I haven't seen anything like that. 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
We already have that. Check out start.jhipster.tech
