### ISSUE TITLE
SwaggerUI not working with OAUTH

### ISSUE THREAD

**Issue by sjerman** [jhipster/generator-jhipster#1008]
Just created an application with OAUTH and discovered that the SwaggerUI wouldn't load.

Seems like a small bug:

replace:
            var authToken = JSON.parse(localStorage.getItem("token")).access_token;
with
            var authToken = JSON.parse(localStorage.getItem("ls.token")).access_token;

fixes it.....

**Comment by jdubois** [comment]
Yes this is a duplicate ticket, it's already fixed on master
