### ISSUE TITLE
Error running the sub-generator Kubernetes when using MSSQL

### ISSUE THREAD

**Issue by smouelhi** [jhipster/generator-jhipster#10089]
##### **Overview of the issue**

When running the Kubernetes sub-generator on a microservice gateway using mssql, the execution fails at the end throwing the following error:
`ls: no such file or directory: /Users/seif/Documents/Projects/zand/corporate/corporate-v2/corporate-ui/target/jib-cache
ERROR! Error: Copying template db/mssql.yml.ejs failed. [Error: ENOENT: no such file or directory, open '/Users/seif/Documents/Projects/zand/corporate/corporate-v2/corporate-ui/node_modules/generator-jhipster/generators/kubernetes/templates/db/mssql.yml.ejs']
`

##### **Motivation for or Use Case**

It should generate the configuration files for Kubernetes with mssql as DB, but cannot find mssql configuration.

##### **Reproduce the error**

1- Create a microservice gateway, with the following options with the DB type MSSQL.
2- Run `jhipster kubernetes`
3- After answering the last question, an error is thrown.

##### **Related issues**

N/A

##### **Suggest a Fix**

Create the mssql.yml.ejs file and fill the basic configuration required.

##### **JHipster Version(s)**

jhipster 6.1.2

##### **JHipster Version(s)**

```
corporate-ui@0.0.0 /Users/seif/Documents/Projects/zand/corporate/corporate-v2/corporate-ui
└── generator-jhipster@6.1.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.zand.banking.corporate",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "gateway",
    "baseName": "corporate_ui",
    "packageName": "com.zand.banking.corporate",
    "packageFolder": "com/zand/banking/corporate",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mssql",
    "prodDatabaseType": "mssql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.20.1 (Apple Git-117)

node: v12.6.0

npm: 6.10.1

yarn: 1.16.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

macOS 10.14.5

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
Closed via #10090
