### ISSUE TITLE
SkipUiGrouping not working properly

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#10083]
##### **Overview of the issue**
When generating code with `--skip-ui-grouing,` import `model` and `service` doesn't work well for relationships.
The path for the two imports is still prefixed with microservice name.

##### **Reproduce the error**
Generated a project with a microservice and a relationship with the flag `--skip-ui-grouing,`

##### **Suggest a Fix**

PR comming...

##### **JHipster Version(s)**
6.1.2

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
as asked here https://github.com/jhipster/generator-jhipster/pull/10084#issuecomment-587042752

Closing this, feel free to reopen if the bug is still there, with more information.
