### ISSUE TITLE
Issues when running mvn -Pprod package

### ISSUE THREAD

**Issue by micobarac** [jhipster/generator-jhipster#10080]
##### **Overview of the issue**

I have issues when **building for production**:

`mvn -Pprod package`

Instead of **WAR** file, default **JAR** file gets generated. I fixed this by altering **pom.xml**:

`<packaging>war</packaging>`

**maven-enforcer-plugin** reports many warnings:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-dependencyConvergence) @ openprovider ---
[WARNING] 
Dependency convergence error for org.ow2.asm:asm:5.0.4 paths to dependency are:
+-com.logate.openprovider:openprovider:2.2.0
  +-com.jayway.jsonpath:json-path:2.4.0
    +-net.minidev:json-smart:2.3
      +-net.minidev:accessors-smart:1.2
        +-org.ow2.asm:asm:5.0.4
and
+-com.logate.openprovider:openprovider:2.2.0
  +-io.github.swagger2markup:swagger2markup:1.3.3
    +-io.github.swagger2markup:markup-document-builder:1.1.2
      +-nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:1.0
        +-org.pegdown:pegdown:1.4.2
          +-org.parboiled:parboiled-java:1.1.6
            +-org.ow2.asm:asm:5.0.4
and
+-com.logate.openprovider:openprovider:2.2.0
  +-org.cassandraunit:cassandra-unit-spring:3.11.2.0
    +-org.cassandraunit:cassandra-unit:3.11.2.0
      +-org.apache.cassandra:cassandra-all:3.11.4
        +-org.ow2.asm:asm:5.0.4
and
+-com.logate.openprovider:openprovider:2.2.0
  +-com.datastax.cassandra:cassandra-driver-extras:3.6.0
    +-com.datastax.cassandra:cassandra-driver-core:3.6.0
      +-com.github.jnr:jnr-ffi:2.1.7
        +-org.ow2.asm:asm:5.0.3

[WARNING] 
Dependency convergence error for io.swagger:swagger-compat-spec-parser:1.0.13 paths to dependency are:
+-com.logate.openprovider:openprovider:2.2.0
  +-io.springfox:springfox-staticdocs:2.6.1
    +-io.github.robwin:swagger2markup:0.9.2
      +-io.swagger:swagger-compat-spec-parser:1.0.13
and
+-com.logate.openprovider:openprovider:2.2.0
  +-io.github.swagger2markup:swagger2markup:1.3.3
    +-io.swagger:swagger-compat-spec-parser:1.0.35

[WARNING] 
Dependency convergence error for commons-logging:commons-logging:1.2 paths to dependency are:
+-com.logate.openprovider:openprovider:2.2.0
  +-io.github.swagger2markup:swagger2markup:1.3.3
    +-org.apache.commons:commons-configuration2:2.1
      +-commons-logging:commons-logging:1.2
and
+-com.logate.openprovider:openprovider:2.2.0
  +-io.github.swagger2markup:swagger2markup:1.3.3
    +-commons-beanutils:commons-beanutils:1.9.2
      +-commons-logging:commons-logging:1.1.1

[WARNING] 
Dependency convergence error for org.ow2.asm:asm-util:4.1 paths to dependency are:
+-com.logate.openprovider:openprovider:2.2.0
  +-io.github.swagger2markup:swagger2markup:1.3.3
    +-io.github.swagger2markup:markup-document-builder:1.1.2
      +-nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:1.0
        +-org.pegdown:pegdown:1.4.2
          +-org.parboiled:parboiled-java:1.1.6
            +-org.ow2.asm:asm-util:4.1
and
+-com.logate.openprovider:openprovider:2.2.0
  +-com.datastax.cassandra:cassandra-driver-extras:3.6.0
    +-com.datastax.cassandra:cassandra-driver-core:3.6.0
      +-com.github.jnr:jnr-ffi:2.1.7
        +-org.ow2.asm:asm-util:5.0.3

[WARNING] 
Dependency convergence error for io.vavr:vavr:0.9.1 paths to dependency are:
+-com.logate.openprovider:openprovider:2.2.0
  +-io.github.swagger2markup:swagger2markup:1.3.3
    +-io.vavr:vavr:0.9.1
and
+-com.logate.openprovider:openprovider:2.2.0
  +-io.github.swagger2markup:swagger2markup:1.3.3
    +-ch.netzwerg:paleo-core:0.11.0
      +-io.vavr:vavr:0.9.0

[WARNING] 
Dependency convergence error for org.ow2.asm:asm-tree:4.1 paths to dependency are:
+-com.logate.openprovider:openprovider:2.2.0
  +-io.github.swagger2markup:swagger2markup:1.3.3
    +-io.github.swagger2markup:markup-document-builder:1.1.2
      +-nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:1.0
        +-org.pegdown:pegdown:1.4.2
          +-org.parboiled:parboiled-java:1.1.6
            +-org.ow2.asm:asm-tree:4.1
and
+-com.logate.openprovider:openprovider:2.2.0
  +-com.datastax.cassandra:cassandra-driver-extras:3.6.0
    +-com.datastax.cassandra:cassandra-driver-core:3.6.0
      +-com.github.jnr:jnr-ffi:2.1.7
        +-org.ow2.asm:asm-commons:5.0.3
          +-org.ow2.asm:asm-tree:5.0.3
and
+-com.logate.openprovider:openprovider:2.2.0
  +-com.datastax.cassandra:cassandra-driver-extras:3.6.0
    +-com.datastax.cassandra:cassandra-driver-core:3.6.0
      +-com.github.jnr:jnr-ffi:2.1.7
        +-org.ow2.asm:asm-tree:5.0.3

[WARNING] 
Dependency convergence error for com.carrotsearch:hppc:0.7.1 paths to dependency are:
+-com.logate.openprovider:openprovider:2.2.0
  +-com.fasterxml.jackson.datatype:jackson-datatype-hppc:2.9.9
    +-com.carrotsearch:hppc:0.7.1
and
+-com.logate.openprovider:openprovider:2.2.0
  +-org.cassandraunit:cassandra-unit-spring:3.11.2.0
    +-org.cassandraunit:cassandra-unit:3.11.2.0
      +-org.apache.cassandra:cassandra-all:3.11.4
        +-org.apache.cassandra:cassandra-thrift:3.11.4
          +-com.carrotsearch:hppc:0.5.4

[WARNING] 
Dependency convergence error for org.ow2.asm:asm-analysis:4.1 paths to dependency are:
+-com.logate.openprovider:openprovider:2.2.0
  +-io.github.swagger2markup:swagger2markup:1.3.3
    +-io.github.swagger2markup:markup-document-builder:1.1.2
      +-nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:1.0
        +-org.pegdown:pegdown:1.4.2
          +-org.parboiled:parboiled-java:1.1.6
            +-org.ow2.asm:asm-analysis:4.1
and
+-com.logate.openprovider:openprovider:2.2.0
  +-com.datastax.cassandra:cassandra-driver-extras:3.6.0
    +-com.datastax.cassandra:cassandra-driver-core:3.6.0
      +-com.github.jnr:jnr-ffi:2.1.7
        +-org.ow2.asm:asm-analysis:5.0.3

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
```

Only `com.logate.openprovider.config.WebConfigurerTest` is ran. **All other tests are skipped**!!!

Building ends with error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war) on project openprovider: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode)
`

The strange thing here is that maven always resolves **maven-war-plugin** version **2.2**, instead of **3.2.3**, as stated inside **pom.xml** file. That's what's obviously causing the error. 

##### **Motivation for or Use Case**

Build war file for production, while running all tests.

##### **Reproduce the error**

Generate a new JHipster Cassandra project:

`jhipster --skip-client --yarn`

Run building war file for production:

`mvn -Pprod package`

##### **Suggest a Fix**

Run bulding **WAR** file for production successfully with **all tests included**.

##### **JHipster Version(s)**

`6.1.2`

##### **JHipster Version(s)**

```
openprovider@0.0.0 /Users/milan/Sites/jhipster
└── generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.logate.openprovider"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "openprovider",
    "packageName": "com.logate.openprovider",
    "packageFolder": "com/logate/openprovider",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "yarn",
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 3.0.0

yarn: 1.16.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

macOS Mojave
Version 10.14.5 (18F132)

**Comment by antarus** [comment]
Hello,
In Jhipster 6 the default packaging is `jar`. 
If you want a war, use the profile `war`

**Comment by micobarac** [comment]
Ok, but what about the errors?

**Comment by micobarac** [comment]
Oh, compared to the JHipster 4, pom.xml file structure has changed a lot. That's what's causing all the errors with  building WAR.

WAR was moved to a separate profile. So, instead of running:

`mvn -Pprod package`

one must run:

`mvn -Pprod,war package`

**Comment by DanielFran** [comment]
The maven-enforcer-plugin has been added to inform about possible conflicts with dependencies that cannot be managed in the project due to the overall options and combinations of pom versions.
The user can decide to resolve or not the conflicts.
Prior that, no information were available by default, but user were able to analyse conflicts using dependency graph...

**Comment by micobarac** [comment]
Can you resolve dependency issues automatically, or it must be done manually?

What about the problem with generating WAR (JAR) packages?

**Comment by DanielFran** [comment]
Dependency management is done manually...

**Comment by DanielFran** [comment]
You need to define war in the pom, and include profile war that will use maven-war-plugin to generate the war files

**Comment by micobarac** [comment]
But, there is already a profile war generated by jhipster, it's not a problem.

**Comment by PierreBesson** [comment]
>Instead of WAR file, default JAR file gets generated. I fixed this by altering pom.xml: 

```
  <packaging>war</packaging>
```

You should not do this, you should leave packaging as jar. The only way is to use the war profile, it should produce a valid war.
Also please understand that `war` is no longer a first class citizen of jhipster. Yes the war profile does also generate the jar that you don't need but it's better than the previous solution which would generate the war.original that most people didn't need.

**Comment by micobarac** [comment]
Noone?

**Comment by micobarac** [comment]
The only way to achieve what I need, two **WAR** files, without **JAR** files is by setting:

`<packaging>war</packaging>`

and running:

`./mvnw -Pprod,war verify`

**Comment by micobarac** [comment]
Btw, there is a difference between your online documentation and README.md file, regarding packaging for production.

**Online docs say:**

./mvnw -Pprod verify

./mvnw -Pprod,war verify

**README.md says:**

./mvnw -Pprod clean verify

./mvnw -Pprod,war clean verify

Is a **clean** command really necessary, because, as the way I see in **pom.xml**, **prod** profile automatically invokes cleaning process. So, which one of the docs is true and optimal?

**Comment by pascalgrimaud** [comment]
This ticket confused me, because there are several subject here:
- upgrade from v4 to v6 ? There are a lot of breaking changes so it's normal it won't work out of the box
- integration tests : same, it has been discussed
- war vs jar : we made a choice by default, you can look the old discussion about it

Please, understand it's really really hard for us to support all type of packaging. Some people want:
- to separate client / server
- jar file
- war file
- war original file
- war to be deployed into Tomcat
- war to be deployed into Wildfly
- Docker image
- etc.

Don't hesitate to contribute and fix our documentation if it's wrong.

**Comment by micobarac** [comment]
Thanks @pascalgrimaud and all the JHipster team for all the effort you put into JHipster.

But, I just want to emphasise the following summarised things which bother me (please, do not ignore my statements and please, do not redirect me to some old discussions):

- If you provide the option to output jar and war file, please do provide an easy way to output either one or another, not combined (current issue: wrong, ugly...). The more important, **war.original NEVER gets generated** with default pom.xml settings, which is an unacceptable problem for me. You may set jar as a default one, as your own choice of preference, but, bear in mind that there are people still using war format and will be using it in a long time. And you cannot omit war.original file from generation, please treat it the same way as you treat jar file output. So, either generate *.jar and *.jar.original, or *.war and *.war.original, like you used to before in earlier versions. Let's not make target folder a mess.

- Regarding integration tests, it is unacceptable to me to generate jar or war without integration tests successfully ran prior to package file. It is not safe, especially with commercial apps based on JHipster.

- Please, compare the docs and differences for package generation I mentioned above. Currently it is a bit confusing.

**Comment by pascalgrimaud** [comment]
@micobarac : why are you closing the ticket ? I'm pretty sure our doc is not up-to-dated, we need to work on this about this part war / jar

**Comment by micobarac** [comment]
@pascalgrimaud , I sound like a madman talking to myself here, that's why I closed a ticked :).

I opened a new issue for packaging for production problem #10096.

**Comment by pascalgrimaud** [comment]
The main problem with JHipster is: all the work is done during our personal time (night and week-end). It's not our main job, we are not paid for that... So plz, just be patient :)

**Comment by micobarac** [comment]
I know that and I appreciate your time and effort.

I am just putting and effort here also to solve these confusions too, that might be helpful to someone else. I have a very narrow time to migrate from JHipster 4 to JHipster 6 and it's hard to be patient in solving all these breaking changes that happened in-between the two versions.

I found a workaround for war problem, but still, you should investigate and try to make it work (consistently) when you have time.

**Comment by micobarac** [comment]
We can close this now, as I opened separate issues for things that remain unexplained.
