### ISSUE TITLE
Content Security Policy violation with BootSwatch themes

### ISSUE THREAD

**Issue by mabilalmirza** [jhipster/generator-jhipster#10091]
##### **Overview of the issue**
Content Security Policy violation is reported in browser when running application with Bootswatch theme. Firefox reports it as below.

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700 (“style-src”).
```

##### **Reproduce the error**
1. Create Monolithic App and select a bootswatch theme, e.g. yetti while generating application.
2. build and run the application.
3. Load the application in browser and see browser console for error. 

##### **Suggest a Fix**
This is occurring because bootswatch themes are using google fonts as below.
`@import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700");`

Instead of changing Content Security Policy in SecurityConfiguration.java, there should be a way to host the google fonts along with application. May be we can use [google-fonts-webpack-plugin](https://www.npmjs.com/package/google-fonts-webpack-plugin) but I am not sure yet.

##### **JHipster Version(s)**
6.1.2

##### **JHipster configuration**
Output of `jhipster info` command:

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

app@0.0.0 D:\projects\playground\app
-- generator-jhipster@6.1.2
 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "demo.app",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "app",
    "packageName": "demo.app",
    "packageFolder": "demo/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "yeti",
    "clientThemeVariant": "primary",
    "testFrameworks": ["cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

git version 2.19.0.windows.1

node: v10.15.0

npm: 6.6.0

yeoman: 3.0.0

yarn: 1.13.0

Docker version 18.09.3, build 774a1f4eee

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**
Experienced on Microsoft Windows 10 with Firefix, Chrome, Brave. But this seems to be a generic issue. 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
As the plugin seems to be not maintained I would go with adapting the content security policy (if possible)

**Comment by mabilalmirza** [comment]
Updating content security policy will not work in an environment where application is deployed and used in a intranet with no internet access. I think, at the moment, the easiest option is not to use bootswatch for such cases.

**Comment by atomfrede** [comment]
But in that case bootswatch/Google fonts won't work regardless of the csp, right? So  I see two issues here. The csp is to strict when using bootswatch themes and Google fonts are loaded from external sources. We can fix the csp such that bootswatch works as before adding the csp and have look at delivering fonts not via cdn.
