### ISSUE TITLE
Use `npm-shrinkwrap.json` instead of `package-lock.json` in generator

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#10099]
##### **Overview of the issue**
Use `npm-shrinkwrap.json` instead of `package-lock.json` in generator

Following npm shrinkwrap docs, `generator-jhipster` should publish lock file including transitive dependencies. It can avoid issues like #9952  

> The recommended use-case for npm-shrinkwrap.json is applications deployed through the publishing process on the registry: for example, daemons and command-line tools intended as global installs or devDependencies.

##### **Motivation for or Use Case**

Improve predictability of `generator-jhipster` cli.

##### **Related issues**
#9952 

##### **Suggest a Fix**
Switch to `npm-shrinkwrap.json`

##### **JHipster Version(s)**

refer master branch

##### **JHipster configuration**
N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
N/A

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Great initiative @vishal423 ! This was also my recommendation following the previous bug with yeoman-enviromnent. For the case of a CLI tool it is perfectly justified to use a shrinkwrap.json because we don't want `jhipster ` to suddenly stop working because of a bad transitive dependency.

**Comment by SudharakaP** [comment]
@jhipster/developers : Could someone please assign this to me as discussed in https://github.com/jhipster/generator-jhipster/pull/10139 ? Otherwise I might lose track of this. 😄 I am quite forgetful sometimes. 😄

**Comment by pascalgrimaud** [comment]
@SudharakaP : done. But it will require a lot of work to achieve this... as it will impact other repositories of the organization

**Comment by SudharakaP** [comment]
@pascalgrimaud : Not a problem. I like the work. 😄

**Comment by pascalgrimaud** [comment]
I think it's not the priority now, we have too much opened tickets to focus on.
So I suggest to close this, and we can rethink about it later when there are less ticket

**Comment by SudharakaP** [comment]
@pascalgrimaud : I have some spare time and if it's okay, I'd like to do this one in the next week or so. We can probably include this in the v7 roadmap? If that's in agreement let me know so that we can reopen the issue. :smile:

**Comment by pascalgrimaud** [comment]
yes if possible, let's do it for v7, but we have so much more interesting stuff to priorize, so not sure this one deserved you spend time to achieve

**Comment by SudharakaP** [comment]
@pascalgrimaud : I was looking into this and I also encountered the [same problem as vishal423](https://github.com/jhipster/generator-jhipster/pull/10139#discussion_r307307697) where the global npm install command `npm install -g "$JHI_HOME"` fails. I've [opened an issue](https://github.com/nodelib/nodelib/issues/50) in the nodelib side since I believe this is a problem there. If this is not a high priority I suggest that we keep `package-lock.json` for now and I'll revisit this if we could find a cleaner solution (or if they fix it on the nodelib side). :smile:

**Comment by pascalgrimaud** [comment]
ok let's keep `package-lock.json` for now
