### ISSUE TITLE
No ".war.original" generated from "mvn -Pprod,war clean verify"

### ISSUE THREAD

**Issue by micobarac** [jhipster/generator-jhipster#10096]
##### **Overview of the issue**

I have issues when **building for production**:

`mvn -Pprod,war clean verify`

***.war.original** file doesn't get generated. ***.jar** files are generated, although I explicitly asked for **war** file output format. I don't use **jars** at all.

![image](https://user-images.githubusercontent.com/16001837/61133042-ec7e0700-a4bc-11e9-8996-6f2e793ae0ee.png)

##### **Motivation for or Use Case**

Build ***.war.original** file for production.

With original settings:

`<packaging>jar</packaging>`

`mvn -Pprod clean verify` should generate:

```
project.jar
project.jar.original
```

`mvn -Pprod,war clean verify`should generate:

```
project.war
project.war.original --> should be here
 --> jar files shouldn't be here
```

##### **Reproduce the error**

Generate a new JHipster Cassandra project:

`jhipster --skip-client --yarn`

Run building war file for production:

`mvn -Pprod,war clean verify`

```
project.war
project.war.original --> missing one
 --> jar files are here too
```

##### **Suggest a Fix**

Create ***.war.original** file for production successfully. This is the desired behavior:

![image](https://user-images.githubusercontent.com/16001837/61275892-2dbd3200-a7af-11e9-94ef-3b10bcd5e957.png)

##### **JHipster Version(s)**

`6.1.2`

##### **JHipster Version(s)**

```
openprovider@0.0.0 /Users/milan/Sites/jhipster
└── generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.logate.openprovider"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "openprovider",
    "packageName": "com.logate.openprovider",
    "packageFolder": "com/logate/openprovider",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "yarn",
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 3.0.0

yarn: 1.16.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

macOS Mojave
Version 10.14.5 (18F132)

**Comment by micobarac** [comment]
The only way I was able to achieve what I need (two **WAR** files, without **JAR** files) is by setting:

`<packaging>war</packaging>`

and running:

`mvn -Pprod,war clean verify`

![image](https://user-images.githubusercontent.com/16001837/61275892-2dbd3200-a7af-11e9-94ef-3b10bcd5e957.png)

**Comment by atomfrede** [comment]
Why do you need the `.original` war file? As we decided for `.jar` as our primary packing I think we can prevent maven to generate them even when wanting war files in addition.

**Comment by micobarac** [comment]
I need it, as I deploy my app to test and prpd Tomcat, which can be different versions.

**Comment by DanielFran** [comment]
@micobarac I finished to migrate an old Prod application (from 5.8.0 to 6.1.2) that is deployed in Tomcat:
- previously migration, I had 'war' in pom + packaging using 'prod' profile creates a 'war.original' binary that was used to be deployed in Tomcat
- after migration, I have now 'jar' in pom + packaging using 'prod,war' profiles creates a 'war' binary that is used to be deployed in Tomcat

I did not have any issue and application is working fine in Tomcat Production environment.

**Comment by micobarac** [comment]
I have always used .war.original since the JHIpster 3. Regular war used to cause me problems. .war.original does not contain the Tomcat jars. Why is .jar.original generated with the default settings?

**Comment by atomfrede** [comment]
So are we going to do something about the inconsistency when generating war file when the generated war works fine in tomcat? Is it still executable?

**Comment by pascalgrimaud** [comment]
I think we just need to document that part. It should be enough, as it's hard to support all config between jar, war, jar.original and war.original
