### ISSUE TITLE
how to run multiple jhipster in one machine

### ISSUE THREAD

**Issue by saputrasaja** [jhipster/generator-jhipster#1009]
Can i run multiple jhipster app in one machine ?
Assuming each app run in ports and different databases too

**Comment by gmarziou** [comment]
Yes as it is based on spring-boot

**Comment by saputrasaja** [comment]
i try run a jhipster app on default config --8080 port
and create the new one with different port
- server.port : 8083
- metrics.spark.port: 9998
- metrics.graphite.port: 2002

but on second running shown an error like this

transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)

did i miss some thing ?

**Comment by jdubois** [comment]
Please use Stackoverflow for this kind of question.

**Comment by saputrasaja** [comment]
[SOLVED]

found it, i forgot to change jvmArguments address  in pom.xml

thx
