### ISSUE TITLE
Sonarqube external config not used with maven + jenkins

### ISSUE THREAD

**Issue by pdelaby** [jhipster/generator-jhipster#10101]
##### **Overview of the issue**

Sonar configuration is now in `sonar-project.properties` but does not seem to be used during the analysis with Maven and Jenkins. I fixed it by adding the goal `initialize` during the sonar step ( in the pom, the configuration for the properties is during the `initialize` phase). 

With the classic phase, `./mvnw sonar:sonar`, sonar did not show code coverage and other parameters, and the maven log shows
```
[INFO] Load project settings for component key: 'fr.mycompany.mypackage:project-name'
[INFO] Load project settings for component key: 'fr.mycompany.mypackage:project-name' (done) | time=34ms
[INFO] Load quality profiles
```

With  `./mvnw initialize sonar:sonar`, sonar set the correct name, show code coverage, exclude the correct files and the maven log shows
```
[INFO] Load project settings for component key: 'ProjectName'
[INFO] Load quality profiles
```
I don't know if this issue is also with gradle or other CI tools. 

##### **Motivation for or Use Case**

Sonar analysis shoud use the `sonar-project.properties`

##### **Reproduce the error**

* Generate jhipster project in 6.1.2, with maven
* Use the goal ci-cd with jenkins and sonar. 

##### **Suggest a Fix**

Change the step from  `sh "./mvnw sonar:sonar"`  to `sh "./mvnw initialize sonar:sonar"`

##### **JHipster Version(s)**

6.1.2

##### **JHipster Version(s)**

```
noda-demande-ms@0.0.0 C:\projets\noda\services\noda-demande-ms2
`-- generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "microservice",
    "serverPort": "8087",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

git version 2.22.0.windows.1

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@pdelaby I confirm the issue!

Can you please make a PR to fix it on all pipelines (Jenkins, gitlab,...)?

**Comment by pdelaby** [comment]
I added the goal on Jenkins pipeline, GitLab CI and Travis CI. I can confirm it works on Jenkins Pipeline.
The README file template already suggest to add this goal.
