### ISSUE TITLE
Move from TSLint to ESLint

### ISSUE THREAD

**Issue by TheJavaGuy** [jhipster/generator-jhipster#10105]
##### **Overview of the feature request**

TSLint will very soon move to maintenance mode and, starting from January 1st 2020 stop accepting anything except security fixes. This is a documented [issue](https://github.com/palantir/tslint/issues/4534), also explained in their [blog post](https://medium.com/palantir/tslint-in-2019-1a144c2317a9). I believe that JHipster should move from TSLint to ESLint in the similar timeframe.

##### **Motivation for or Use Case**

For sure TypeScript will continue to be developed, and hopefully JHipster and ESLint too. I think that staying stuck with the tool which will be abandoned soon is not an optimal way ahead.

Tasks:
- [x] Migrate angular code to use ESLint - #10187 
- [x] Migrate reactjs code to use ESLint - #10213 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
I think we need to wait until https://github.com/mgechev/codelyzer/issues/763 is closed.

**Comment by MathieuAA** [comment]
We needn't have to wait, as such a migration is kind of easy to do, and works (I've done this migration twice, this wasn't such a big deal).

**Comment by vishal423** [comment]
@jhipster/developers, anyone willing to take. Otherwise, I will spend time over weekend

**Comment by pascalgrimaud** [comment]
I think you can take it. Thanks a lot @vishal423 ! So happy to have you in the team :-)

**Comment by wmarques** [comment]
Is that really urgent ? TSLint looks pretty well used today and there are not a clean migration path documented about this.
Also, some `codelyzer` rules aren't yet implemented in ESLint so we would loose some great lint features on the Angular side.

**Comment by vishal423** [comment]
@wmarques, I believe we can use `eslint-plugin-tslint` to continue execute tslint specific rules. I have started work on this activity with an angular project and might be able to come up with something in next few days..

**Comment by DanielFran** [comment]
@vishal423 typescript-eslint v2 hás been released and have breacking changes. Maybe it is better to use the nee version now? See https://github.com/typescript-eslint/typescript-eslint/commit/05ba26879dd5a5a0e1159951c8b24dc5e0e5cc4a

**Comment by vishal423** [comment]
@DanielFran, thanks for update. Dependency update is a never ending task.

**Comment by DanielFran** [comment]
And do not forget to claim the bug-bounty and close this issue :stuck_out_tongue_winking_eye:

**Comment by vishal423** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/10350

**Comment by pascalgrimaud** [comment]
Just approuved.
Thanks @vishal423 !
