### ISSUE TITLE
Microservices - 401 Error on every page load for added entities and user is logged out

### ISSUE THREAD

**Issue by mikebski** [jhipster/generator-jhipster#10108]
##### **Overview of the issue**

![jhipster-bug](https://user-images.githubusercontent.com/4280588/61384978-a7245580-a87f-11e9-94b4-a1f0e6bff6c0.gif)

I created a microservice project with gradle and added 1 entity with 2 string fields.

I created a gw project  with gradle and added the entity to that project, overwriting files when prompted.

I started the registry via docker and it came up fine on http://localhost:8761/#/

I started the mircoservice project and it comes up and attaches to the registry

I started the gw project and it comes up and attaches to the registry

When I login and select the menu item for the added entity, I get a 401 error about the translation not found and it logs the user out

All other menu items seem to work OK

##### **Motivation for or Use Case**

This should work out of the box

##### **Reproduce the error**

See overview for steps

##### **Related issues**

This is similar but > 1 year old

https://github.com/jhipster/generator-jhipster/issues/7865

##### **Suggest a Fix**

No idea about a fix, I'm afraid

##### **JHipster configuration**

jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gw@0.0.0 /Users/mike/code/public/jh/gw
└── generator-jhipster@6.1.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en",
      "microservicePath": "../svc"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "gateway",
    "baseName": "gw",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_212"
OpenJDK Runtime Environment Corretto-8.212.04.1 (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM Corretto-8.212.04.1 (build 25.212-b04, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 3.1.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
     JDL content here
  </pre>
  </details>
-->

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Company.json:

{
    "fluentMethods": true,
    "clientRootFolder": "svc",
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20190717125641",
    "dto": "mapstruct",
    "searchEngine": false,
    "service": "serviceImpl",
    "entityTableName": "company",
    "databaseType": "sql",
    "jpaMetamodelFiltering": true,
    "pagination": "no",
    "microserviceName": "svc"
}

##### **Browsers and Operating System**

MAC issue with Chrome / FF / Safari

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mikebski** [comment]
This happens with Maven too, I'm getting the following error on the request:

Request URL: http://localhost:8080/services/svc/api/companies?page=0&size=20&sort=id,asc&cacheBuster=1563376382701

Request Method: GET

Status Code: 401 Unauthorized

Remote Address: [::1]:8080

Referrer Policy: strict-origin-when-cross-origin

Here is the response:

detail: "Full authentication is required to access this resource"
message: "error.http.401"
path: "/api/companies"
status: 401
title: "Unauthorized"
type: "https://www.jhipster.tech/problem/problem-with-message"

I'm logged in as `admin`

**Comment by clement26695** [comment]
Would it be possible to go inside your microservice folder and run `jhipster info` and paste the results here. It would help to debug.

Thanks!

**Comment by mikebski** [comment]
@clement26695 

jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
svc@0.0.0 /Users/mike/code/public/jh-maven/svc
└── generator-jhipster@6.1.2 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "microservice",
    "baseName": "svc",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Company {
  name String required
}
dto Company with mapstruct
paginate Company with pagination
service Company with serviceImpl
microservice Company with svc
filter Company
clientRootFolder Company with svc

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_212"
OpenJDK Runtime Environment Corretto-8.212.04.1 (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM Corretto-8.212.04.1 (build 25.212-b04, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 3.1.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

**Comment by vishal423** [comment]
@mikebski, I am not able to reproduce this issue. I believe you haven't updated `application-*.yml` on both `gateway` and `micro-service` to have identical jwt `base64-secret` value. Can you confirm?

```
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: YzIwYjU2MTRlYjUzMjAxNzYyY2E0NDZhODNiYWU0NjYwODlhODE3YzRiNWRlYjgyNzQyZTgyMjdmMmM5YmFkZGRlZTE0M2E5Y2NkZjRhOTFhZWRmMjhmMDUxYjlhMmMyNWVkMWI0ZDYzYjkxOTZmYjIyYTFiYjBhY2JlMDNiNGI=
```

**Comment by mikebski** [comment]
ah, I have not done that, I must have missed it in the docs.  I will give
it a shot.

**Comment by vishal423** [comment]
@mikebski, did you get chance to reproduce this issue following the above instructions?

**Comment by mikebski** [comment]
@vishal423 Yes - thanks, it works if I do it like the instructions tell me to...
