### ISSUE TITLE
Prometheus endpoint is not enabled by default

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#10112]
##### **Overview of the issue**

Prometheus is the default metrics backend but the endpoint is not enabled by default

##### **Motivation for or Use Case**

Metrics are not available in Prometheus

##### **Reproduce the error**

Create a new jhipster application with latest version, start application and validate that endpoint /management/prometheus is available

##### **Suggest a Fix**

Update application.yml with the configuration:
````txt
management:
  endpoint:
    prometheus:
      enabled: true
````

##### **JHipster Version(s)**

6.1.2 and master

##### **JHipster configuration**
>
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
myci-service-myapplication@0.0.0 /home/dev/workspace/jhipster/blog_full/myciServiceMyapplication
└── generator-jhipster@6.1.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr",
      "es",
      "it",
      "pt-pt",
      "ru"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "io.mycompany.myci.service.myapplication",
    "packageFolder": "io/mycompany/myci/service/myapplication",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "consul",
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "microservice",
    "baseName": "myciServiceMyapplication",
    "buildTool": "maven",
    "clientPackageManager": "npm",
    "serverPort": "8010",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "skipUserManagement": true,
    "jhipsterVersion": "6.1.2",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "entities": [
    "Category",
    "Product",
    "Customer",
    "Address"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Category entity
 */
entity Category {
  /**
   * Description
   */
  description String required,
  /**
   * Sort order
   */
  sortOrder Integer,
  /**
   * Creation date
   */
  dateAdded Instant,
  /**
   * Update date
   */
  dateModified Instant,
  /**
   * Status
   */
  currentStatus CategoryStatus
}
/**
 * Product entity
 */
entity Product {
  /**
   * Title
   */
  title String required,
  /**
   * Keywords
   */
  keywords String,
  /**
   * Description
   */
  description String,
  /**
   * Rating
   */
  rating Integer,
  /**
   * Creation date
   */
  dateAdded Instant,
  /**
   * Update date
   */
  dateModified Instant
}
/**
 * Customer entity
 */
entity Customer {
  /**
   * First name
   */
  firstName String,
  /**
   * Last name
   */
  lastName String,
  /**
   * Email
   */
  email String,
  /**
   * Telephone
   */
  telephone String
}
/**
 * Address entity
 */
entity Address {
  /**
   * Address line 1
   */
  address1 String,
  /**
   * Address line 2
   */
  address2 String,
  /**
   * City
   */
  city String,
  /**
   * Zip code
   */
  postcode String required maxlength(10),
  /**
   * Country
   */
  country String required maxlength(2)
}
enum CategoryStatus {
  AVAILABLE,
  RESTRICTED,
  DISABLED
}

relationship OneToMany {
  /**
   * Addresses
   */
  Customer{address} to
  /**
   * Customer
   */
  Address{customer}
}
relationship ManyToOne {
  /**
   * Parent category
   */
  Category{parent} to Category
}
relationship ManyToMany {
  /**
   * Titles
   */
  Category{product(title)} to
  /**
   * Categories
   */
  Product{category}
}

dto Category, Product, Customer, Address with mapstruct
paginate Category, Product, Customer, Address with pagination
service Category, Product, Customer, Address with serviceClass
microservice Category, Product, Customer, Address with myciServiceMyapplication
filter Category, Product, Customer, Address

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 1.8.3.1

node: v8.11.1

npm: 5.6.0

yeoman: 2.0.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by clement26695** [comment]
Isn't it already enabled by default with Spring boot Actuator ? 
(In https://github.com/jhipster/generator-jhipster/blob/b5cba3bcfe712c0545ad150dbc1a542704d3ed39/generators/server/templates/src/main/resources/config/application.yml.ejs#L115)

**Comment by PierreBesson** [comment]
This is on purpose https://github.com/jhipster/generator-jhipster/pull/9377 

See the discussions:
- https://github.com/jhipster/generator-jhipster/pull/9362
- https://github.com/jhipster/generator-jhipster/issues/8946

I'd rather we implement the solution from @cbornet.

**Comment by DanielFran** [comment]
OK, got it, thanks!

Maybe we should fix documentation in https://www.jhipster.tech/monitoring/

I see:
````txt
Forwarding metrics to a supported third party monitoring system (JMX, Prometheus)

JHipster also provides a Metrics exporters for JMX and Prometheus.

Forwarding metrics to alternative systems is also supported and can also simply be enabled in your YAML configuration files.

jhipster:
    metrics:
        prometheus:
            enabled: true

````

And should be
````txt
management:
  metrics:
    export:
      prometheus:
        enabled: true
````

**Comment by DanielFran** [comment]
Will close it now!
