### ISSUE TITLE
[Feature] yo jhipster:addProperty to add a new property to an existing entity

### ISSUE THREAD

**Issue by sbert** [jhipster/generator-jhipster#1012]
When I begin a project I can't define the final data model.
In this case I lost the great power of jhipster generator.

It will be very interesting to have a new generation feature to add property / relation to an entity.

An approach can be : 
generate Abstract<ENTITY_NAME>Base and CustomEntity instead of entity. 
The specific code will be in customEntity and when I add a new property the Abstract<ENTITY_NAME>Base will be replace by the new generation.
Idem for controller

**Comment by jdubois** [comment]
Yes it would be nice, but we would need to add a marker somewhere for us to add the code -> this is a bit complex and I'm not a big fan of it, but we do it elsewhere, see https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/resources/config/liquibase/master.xml#L8 )

**Comment by silhouette** [comment]
Yes, this would be a nice feature. I'd use the entity configuration file for this. So addProperty / addRelationship would add the new property (or relationship) to the config file and then use it to regenerate the code. As a workarround you can do it already just editing the config file with a text-editor. That's what I prefer for changing my data model.

**Comment by jdubois** [comment]
Oh @silhouette yes let's just regenerate everything -> I wanted to do a marker (see my previous comment), but it's much better to regenerate everything

- if the user didn't modify anything, he will just overwrite his files
- if he modified, he can do the merging, either with Yeoman or Git -> it's easier and more powerful than a marker, which can be deleted by mistake

**Comment by gmarziou** [comment]
What's the status on this?
I have a Contract entity that was generated with 1 field and 3 relations, I edited the file to remove 1 relation and add 2 fields then run `yo jhipster:entity Contract` that overwrote all files.
But in the end , only the deleted relation has been taken into account not the 2 additional fields.

**Comment by gmarziou** [comment]
Sorry, my fault, it does work, I don't know what I did.

**Comment by gmarziou** [comment]
By the way this feature is not documented.

**Comment by gmarziou** [comment]
In the doc, I think we should give some hints about ids:
- field ids and relationship ids are independent and could overlap
- do these ids have to be continuous or can there be a hole when I delete a field or a relationship

Also add a warning that there could be issues with existing data r constraints in database.

**Comment by jdubois** [comment]
As long as we regenerate everything, there's nothing to do here -> I know it's not the perfect solution, but it's the easiest (nothing to do), and the less error-prone.
Besides, I don't know if many people will want to use it.
@gmarziou you are correct, I don't think this is documented, I'll add something in the entity sub-generator documentation
@gmarziou the IDs are technical items. You can have holes in them, no problem. In fact it happens all the time if you use a sequence, like with Postgresql
