### ISSUE TITLE
Javadoc for the IT tests has typo in tag

### ISSUE THREAD

**Issue by rabiori** [jhipster/generator-jhipster#10124]
##### **Overview of the issue**

Javadoc on the class looks like this:
```
/**
 * Integration tests for the {@Link BookResource} REST controller.
 */
```
Instead, the correct tag is this `@link` (lowercase):
```
/**
 * Integration tests for the {@link BookResource} REST controller.
 */
```
##### **Motivation for or Use Case**

So intellij won't warn me :)

##### **Suggest a Fix**

https://github.com/jhipster/generator-jhipster/pull/10123

##### **JHipster Version(s)**

6.1.2

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Thanks @rabiori for reporting the doc issue.
I am closing this as your PR #10123 is already merged.
