### ISSUE TITLE
[Feature] add beanValidation in generation step

### ISSUE THREAD

**Issue by sbert** [jhipster/generator-jhipster#1013]
It will be very interesting to have a new step (y/N by default) to add beanValidation when I generate an entity (NotEmpty, size,....)

Theses rules will be implemented in entity, controller and Angular

**Comment by jdubois** [comment]
yes, indeed -> I would even ask this at the beginning of the entity, so it's just one more question for people who don't want it.
And we should also generate the correct SQL schema (column size is the same as the bean validation max size, for example)

**Comment by gzsombor** [comment]
Probably using http://netceteragroup.github.io/valdr/ for server + client side validation would be beneficial too

**Comment by leonardoavs** [comment]
Bean Validation is difficult, but we can ask for the lenght and ask if the attribute is required, moreover we can have a default length for the string types, I mean that we do not need to request the length for all the types, in the past I implemented this for a local jhipster project, and yes is a question more, but it saves a lot of time.

Like example it generate the liquid database file with right constraints and field length, this can generate the screens with basic validation, and it makes the entity more robust.

**Comment by leonardoavs** [comment]
@gzsombor currently I have an implementation of the validation for the string type. I want to contribute it but I do not know how I can do that, can you tell me?

**Comment by gzsombor** [comment]
It sounds difficult, but it's actually not that hard at all:
1. You should fork the generator-jhipster repository to your account
1. Create your patch, commit it, and push to your repository on github
1. Create a pull request from that branch (which contains only one changeset)

And you are done!

**Comment by leonardoavs** [comment]
gzsombor thanks.

**Comment by jdubois** [comment]
Done :-)
