### ISSUE TITLE
can we declare create Specification method as protected in <Entity>QueryService service to extends it easily

### ISSUE THREAD

**Issue by maznag** [jhipster/generator-jhipster#10144]
##### **Overview of the issue**

can we declare create Specification method as protected in <Entity>QueryService service to extends it easily

##### **Motivation for or Use Case**

Need to extend EntityQueryService

##### **Suggest a Fix**

protected instead of private.

##### **JHipster Version(s)**

6.1.2

**Comment by pmverma** [comment]
If someone is doing a side-by-side approach then this is good to have.
👍
