### ISSUE TITLE
dysfunctional war file generated

### ISSUE THREAD

**Issue by ccornchip** [jhipster/generator-jhipster#10141]
##### **Overview of the issue**

Creating a war using bootWar gives an almost-empty war skeleton.

I'm probably doing something wrong, but I've been following the instructions by the letter and I can't find what I did wrong

##### **Motivation for or Use Case**

Due to another issue 
https://stackoverflow.com/questions/57115303/setting-up-feign-in-jhipster-behind-a-ssl-socket
I cannot put my gateway in https, so as a workaround I'm trying to create a war and put it behind a tomcat. When I deploy I get the message saying I need to run npm install and npm start, however I have done so and am still getting this message

##### **Reproduce the error**

I created a new project (either by start.jhipster.tech, or simply by typing jhipster). Following the readme, I run:
<pre>
npm install
npm start
gradlew -Pprod -Pwar bootWar
</pre>

Unzipping the generated war file, I only find 3 directories (META-INF/, org/, WEB-INF/) and no other files.  When I deploy this, I get the message that I should run npm install and npm start.

##### **Related issues**

unsure

##### **Suggest a Fix**

I'm sorry, this is out of my field of competences.

##### **JHipster Version(s)**

Jhipster 6.1.2.  From memory, I had no trouble doing this in jhipster 4.

##### **JHipster configuration**

results from running jhipster info:

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster-sample-application@0.0.0 D:\jhipster\jhipsterSampleApplication
`-- generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "gateway",
    "gitCompany": "",
    "baseName": "jhipsterSampleApplication",
    "packageName": "io.github.jhipster.application",
    "packageFolder": "io/github/jhipster/application",
    "serverPort": 8080,
    "serviceDiscoveryType": "eureka",
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "enableSwaggerCodegen": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "enableTranslation": false,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientFramework": "angularX",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "6.1.2",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

git version 2.22.0.windows.1

node: v10.16.0

npm: 6.9.0

yarn: 1.17.3

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

none.

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Will have a look. It worked for monolithic applications for sure. Will check for gateways too.

**Comment by ccornchip** [comment]
I tried without running `npm start`, and once again after running `npm run webpack:build`.  I still get the page "An error has occured :-("

**Comment by atomfrede** [comment]
When building with gradle there is normally no need to run any `npm` tasks manually. But I'll try find some time to check it this evening.

**Comment by atomfrede** [comment]
@ccornchip Can you check the content of your war file? It looks ok to me (need to download a tomcat). `WEB-INF/classes/static` contains the correct files. Are you deploying under a context path? In that case you need to adapt the `baseHref` in `webpack.prod.js` accordingly. 
You can try to rename the `.war` to `ROOT.war` and deploy it to replace the root application?

**Comment by atomfrede** [comment]
@ccornchip I think you missed the configuration for `baseHref`. I have created a `.war` file, named it `ROOT.war` and deployed it in tomcat 9 and it works fine. If you want to deploy under a context path you have to set `baseHref` accordingly (e.g. `mycontext`) such that webpack generates correct urls/links for assets etc. Can you confirm it works for you too?

**Comment by atomfrede** [comment]
@ccornchip I will close it. If you think it is a jhipster bug we can open it again.

**Comment by ccornchip** [comment]
I am currently on vacations, I'll try this when I get back
