### ISSUE TITLE
WebConfigurer exists for API Gateway

### ISSUE THREAD

**Issue by jkoorts** [jhipster/generator-jhipster#10148]
##### **Overview of the issue**

When you build a API Gateway as per documentation (https://www.jhipster.tech/separating-front-end-and-api/), the class WebConfigurer still exists.

##### **Motivation for or Use Case**

For a RESTful Gateway this config does not make sense.

##### **Reproduce the error**

jhipster --skip-client

##### **Suggest a Fix**

File should not exist.

##### **JHipster Version(s)**

Latest

**Comment by PierreBesson** [comment]
Please fill out the template seriously. 
- "latest" is not a jhipster version.
- You have not included the yo-rc.json which tells us about the options you chose when generating your app.

Do you mean that when running `jhipster --skip-client` some backend files are still generated ?

**Comment by jkoorts** [comment]
Apologies, 

JHipster Version(s):

6.1.2

.yo-rc.json 
`{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.hex"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "gateway",
    "baseName": "appgateway",
    "packageName": "com.hex",
    "packageFolder": "com/hex",
    "serverPort": "8099",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "skipClient": true
  }
}`

Yes, skip-client did package my gateway without the Angular app which was what I wanted, but with the RESTful only gateway now I still see this single class file which is not used in a RESTful gateway. I would expect that file used with the Angular bits (with the /src/main/webapp stuff)

Jhipster generated my gateway "web-less", but I still see this "Web" class.

**Comment by PierreBesson** [comment]
I don't understand what you mean by "RESTful only gateway" or "web-less".

**Comment by jkoorts** [comment]
The generated gateway was stripped off all its web related stuff, which is awesome. I now have a gateway application that my REST client speaks to (The OAUTH2 clientid sits on the gateway). My REST client only speaks json and expects json back. So no html and website related stuff.

Looking at WebConfigurer you see implementations of html which is never used by the gateway and will never be used by my REST calls.

Here a some bits from that class:

`private void setMimeMappings(WebServerFactory server) {
        if (server instanceof ConfigurableServletWebServerFactory) {
            MimeMappings mappings = new MimeMappings(MimeMappings.DEFAULT);
            // IE issue, see https://github.com/jhipster/generator-jhipster/pull/711
            mappings.add("html", MediaType.TEXT_HTML_VALUE + ";charset=" + StandardCharsets.UTF_8.name().toLowerCase());
            // CloudFoundry issue, see https://github.com/cloudfoundry/gorouter/issues/64
            mappings.add("json", MediaType.TEXT_HTML_VALUE + ";charset=" + StandardCharsets.UTF_8.name().toLowerCase());
            ConfigurableServletWebServerFactory servletWebServer = (ConfigurableServletWebServerFactory) server;
            servletWebServer.setMimeMappings(mappings);
        }
    }`

Notice the comment "IE" ?

**Comment by PierreBesson** [comment]
I see, the gateway was developed to be an edge service for the frontend (by reusing most of the codebase from the original jhipster monolith app + a zuul proxy). I can see how you would use it only for exposing APIs for other java services but that is not the primary use case.

If you really don't want the class, you are free to remove it but I think it's going to be useful for some people. However you are right that all the code about `initCachingHttpHeadersFilter()` and `customize(WebServerFactory server) ` could be removed for the --skip-client option.
