### ISSUE TITLE
let grunt-cdnify rewrite static resource to image and font URLs for production build

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1014]
It seems that the official yeoman angular generator is doing this. Should JHipster do so as well?

Not sure how mutch we can benifit from this and if there are any drawbacks
* `<img src="____">` in html
* `background-image: url(____);` in your CSS (including inside `<style>` tags in your HTML)

grunt-cdnify at [GitHub](https://github.com/callumlocke/grunt-cdnify)

**Comment by jdubois** [comment]
I need to check -> my concern with CDN is that it's only for public website, and many people build business applications with JHipster (which is probably not the case with the official Angular generator, which is too simple)

**Comment by jdubois** [comment]
OK, so indeed you need a CDN to make this work -> it's out of scope, a currently most people use JHipster for internal web apps.
