### ISSUE TITLE
Is there a way to switch frontend from Angular to React?

### ISSUE THREAD

**Issue by mrassili** [jhipster/generator-jhipster#10143]
##### **Overview of the feature request**

Change the frontend of a JHipster generated webapp from Angular to React

##### **Motivation for or Use Case**

I am working on a existing project which was generated with Angular and has entities set up and some work done already on the backend, and need to migrate it to React without losing any work done
The app is monolithic but open to changing that if it was a way to keep entities

##### **Related issues or PR**

Can't find any related issue.

**Comment by ecostanzi** [comment]
You can do this, but if you have already customized your angular files you'll have to code these changes again in the react app.

Here's what you can do:
-  remove the following directories: `src/main/webapp`,  `src/test/javascript`, `webpack`
- change your .yo-rc.json file and change `"clientFramework": "angularX"` to `"clientFramework": "react"`
- run `jhipster --with-entities`

Jhipster will generate the react app, you will have to handle conflicts and overrides on the files that are common to both angular and react (e.g. package.json)

**Comment by mrassili** [comment]
Thank you!
Worked like a charm.

**Comment by pascalgrimaud** [comment]
so you got the answer, then we can close this :-)
