### ISSUE TITLE
Auto commit in manual upgrade should be avoided

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#10158]
##### **Overview of the issue**

Since #8645 JHipster auto commits changes if manually upgrading project.

Auto commit can be avoided if using flag `--skip-git`, but I always forget this flag and then must do `git reset` to commit before upgrade, which is annoying.

In some comments of #8880 other people also don't like this auto commit behaviour on manual upgrade.

##### **Reproduce the error**

Generate project with JHipster (run command `jhipster`). Initial code is committed to Git with message "**Initial application generated by JHipster-6.1.2**".  
Make some changes and commit these to git with message "**My changes**".  
Regenerate project (run command `jhipster` again). Regenerated code is automatically committed to Git as new commit with message "**Initial application generated by JHipster-6.1.2**".

Now Git contains 3 commits with messages:
* Initial application generated by JHipster-6.1.2
* My changes
* Initial application generated by JHipster-6.1.2

and all changes made in commit with message "My changes" are lost.

##### **Suggest a Fix**

Possible fix is to change line https://github.com/jhipster/generator-jhipster/blob/master/generators/app/index.js#L517 from
```
                        if (code === 0 && this.gitInitialized) {
```
to
```
                        if (code === 0 && this.gitInitialized && !this.existingProject) {
```

##### **JHipster Version(s)**

```
jhipster@0.0.0 C:\projects\teest\jhipster-git
`-- generator-jhipster@6.1.2  -> C:\projects\kaido-github\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": [
      "et"
    ],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01
##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
+1, I also don't like auto commit behavior on manual upgrade.

**Comment by kaidohallik** [comment]
I made PR #10159 to fix this issue.

**Comment by avdev4j** [comment]
I often face off this problem when I upgrade or re-generate my project. TBH I planned to do a PR for fix that. So for me it's 100% legit.

I will do a review of the PR if you want.

**Comment by kaidohallik** [comment]
It would be great if you could review the PR.
