### ISSUE TITLE
[Angular] user-management.component: eventManager subscription is not destroyed

### ISSUE THREAD

**Issue by QuentinLeGoff** [jhipster/generator-jhipster#10153]
##### **JHipster Version(s)**

```
jal-bo@0.0.0 ****
`-- generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "****",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "****",
    "packageName": "****",
    "packageFolder": "***",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b04, mixed mode)

git version 2.20.1.windows.1

node: v10.15.0

npm: 6.8.0

yeoman: 2.0.5

yarn: 1.13.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Overview of the issue**

When you are on the user-component list, as the eventManager subscription is not destroyed when the component is, the user-service request (loadAll -> this.userService.query) is made N time (N is the number of the user-management.component is created.

##### **Motivation for or Use Case**

It's important to unsubscribe subcriptions, other than http and routing that Angular handles, because it leads to memory leak and lower performances

##### **Reproduce the error**

1. Go to the user-management page (user-management.component)
2. Create a user
3. Click on "Edit" for this user and cancel to go back to the list
4. Open your developer tools -> got to network tab
5. Remove the created user
6. See the number of requests made by the subscription
##### **Suggest a Fix**

What is done in the component
```javascript
registerChangeInUsers() {
    this.eventManager.subscribe('userListModification', response => this.loadAll());
  }
```
It could be destroyed in the ngOnDestroy method of the component:

```javascript
private _destroyed$ = new Subject();
....
registerChangeInUsers() {
    this.eventManager
         .pipe(
              takeUntil(this._destroyed$)
         )
         .subscribe('userListModification', response => this.loadAll());
  }
....
public ngOnDestroy (): void {
    this._destroyed$.next();
    this._destroyed$.complete();
}
```
##### **JHipster Version(s)**

6.1.2, don't know.

##### **Browsers and Operating System**

Windows 10, all browsers
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by QuentinLeGoff** [comment]
There is a similar issue in the home.component with the 'authenticationSuccess' event.
```javascript
    this.eventManager.subscribe('authenticationSuccess', message => {
      this.accountService.identity().then(account => {
        this.account = account;
      });
    });
```

It's not unsubscribe and so every time (N times)  you go on the home component, it will subscribe to this event with the callback. And when you logout and login again, it will call N times the callback.

In generated entities, theses subscriptions are well destroyed, example below.
```javascript
  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IQuestions) {
    return item.id;
  }

  registerChangeInQuestions() {
    this.eventSubscriber = this.eventManager.subscribe('questionsListModification', response => this.loadAll());
  }
```

**Comment by vishal423** [comment]
@QuentinLeGoff, good catch. Would you be able to raise PR with suggested changes?

**Comment by QuentinLeGoff** [comment]
I could try this week (my first time 😄).

If I do that, could I remove the unsubscription of routeData that is already handle by Angular and set pagingParams without parenthesis in the user-management.component ? 
My modifications would be 

_user-management.component.ts_
```javascript
<%_ if (databaseType !== 'cassandra') { _%>
  eventSubscriber: Subscription; // To add
  
constructor(
        private userService: UserService,
        private alertService: JhiAlertService,
        private accountService: AccountService,
        <%_ if (prodDatabaseType !== 'cassandra') { _%>
        private parseLinks: JhiParseLinks,
        private activatedRoute: ActivatedRoute,
        private router: Router,
        <%_ } _%>
        private eventManager: JhiEventManager,
        private modalService: NgbModal,
    ) {
        <%_ if (databaseType !== 'cassandra') { _%>
        this.itemsPerPage = ITEMS_PER_PAGE;
        this.routeData = this.activatedRoute.data.subscribe((data) => {
        this.page = data.pagingParams.page; // To modify (align with pagination-template template)
        this.previousPage = data.pagingParams.page; // To modify (align with pagination-template template)
        this.reverse = data.pagingParams.ascending; // To modify (align with pagination-template template)
        this.predicate = data.pagingParams.predicate; // To modify (align with pagination-template template)
        });
        <%_ } _%>
    }

...
<%_ if (databaseType !== 'cassandra') { _%>
  ngOnDestroy() {
    this.routeData.unsubscribe(); // To remove
    this.eventManager.destroy(this.eventSubscriber); // To add
  }
<%_ } _%>
```

_home.component.ts_

```javascript

    <%_ if (authenticationType !== 'oauth2') { _%>
    eventSubscriber: Subscription;
    modalRef: NgbModalRef;
    <%_ } _%>
    ...
    registerAuthenticationSuccess() {
        this.eventSubscriber = this.eventManager.subscribe('authenticationSuccess', (message) => {
            this.accountService.identity().then((account) => {
                this.account = account;
            });
        });
        <%_ } _%>
    }
    ...
    <%_ if (authenticationType !== 'oauth2') { _%>
    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }
    <%_ }_%>
```

**Comment by vishal423** [comment]
I will prefer to not remove any un-subscription related code including router events as I still see some open subscription related issues on angular router and having clean code causes no harm.

**Comment by QuentinLeGoff** [comment]
PR claimed with https://opencollective.com/generator-jhipster/expenses/9456

**Comment by pascalgrimaud** [comment]
Just approuved, thanks @QuentinLeGoff !

**Comment by QuentinLeGoff** [comment]
It was a pleasure and I didn't expect it to be a bug bounty 👍 Thanks !
