### ISSUE TITLE
[Bug] on manyToMany relation generation

### ISSUE THREAD

**Issue by sbert** [jhipster/generator-jhipster#1015]
I've got an error when I try to save an entity with manyToMany relation : 
`Hibernate: insert into T_PROJECT (code, name) values (?, ?)
Hibernate: insert into T_PROJECT_T_COMPONENT (T_PROJECT_id, components_id) values (?, ?)
[WARN] org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 1054, SQLState: 42S22
[ERROR] org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Unknown column 'T_PROJECT_id' in 'field list'`

The use case : 
* JHipster 2.0
* Create a component entity without relation
* Create a project entity with manyToMany relation on component (project is the owner)

=> Result
* A relation table T_PROJECT_T_COMPONENT with columnNames="projects_id, components_id"
* 2 tables T_PROJECT, T_COMPONENT

**Comment by jdubois** [comment]
Your relationships should be declared on both parts -> "component" should also have a many-to-many relationship to "project" (and it is not the owner)

**Comment by sbert** [comment]
Another solution will be to add JoinTable mapping.
Something like : 
@JoinTable(joinColumns = {
            @JoinColumn(name = "projects_id", nullable = false, updatable = false) },
            inverseJoinColumns = { @JoinColumn(name = "components_id",
                nullable = false, updatable = false) })
