### ISSUE TITLE
React builds : e2e failed

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#10157]
##### **Overview of the issue**

Since 1 day, the builds for React failed during e2e tests. 
It works well for Angular. 

##### **Suggest a Fix**

I think it comes from the dependencies in package.json, maybe update them ? 

##### **JHipster Version(s)**

Current master

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
I think it's related to new version of chrome driver support
