### ISSUE TITLE
Fixes for entity customization into a blueprint

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#10160]
##### **Overview of the feature request**

Allow blueprints to customize the entity.

##### **Motivation for or Use Case**

I am developing a multi tenancy blueprint that creates an entity into admin module.
https://github.com/mshima/generator-jhipster-multitenancy2

##### **Related issues or PR**

-   [x] JHipster not honoring entityServiceFileName:
https://github.com/jhipster/generator-jhipster/pull/10154

-   [x] routerLink create by JHipster doesn't allow '/' in the entityUrl
https://github.com/jhipster/generator-jhipster/pull/10156

-   [x] Allow to create a menu where routerLink != jhiTranslate:
Ex: addElementToAdminMenu('admin/company-management', 'glyphiconName', this.enableTranslation, this.clientFramework, 'companyManagement')
https://github.com/jhipster/generator-jhipster/pull/10155

-   [ ] Tests are generated with incorrect path:
https://github.com/jhipster/generator-jhipster/pull/10161

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
`Allow blueprints to customize the entity.`

The whole point of a blueprint is to allow customization.
What problems are you having?

**Comment by mshima** [comment]
> `Allow blueprints to customize the entity.`
> 
> The whole point of a blueprint is to allow customization.
> What problems are you having?

I am creating PR to fix those issues, each one is an issue.
Is necessary to create 1 issue per PR?
