### ISSUE TITLE
update Gruntfile.js

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1016]
Gruntfile.js dependencies should be updated. 
The Gruntfile configuration should aslo be reviewed and compared with more maintained yeoman generators like [Generator Angular](https://github.com/yeoman/generator-angular). I think it could be a good idea to try keeping it in sync as mutch as possible with a official generator so that JHipster could benifit from it's bugsfixes.

@jdubois Which generator is the that was forked when this project started? Which one should it follow?

**Comment by jdubois** [comment]
It think it came originally from generator angular fullstack, but that was more than 1 year ago... Indeed, dependencies should be updated, do you want to have a look?

**Comment by andidev** [comment]
Yes I could do that. Is it okey to do that in PR #1007 which fixes #970 ?

Seems that #970 was not that easy as I thought (as always when you develop something =) )

**Comment by jdubois** [comment]
Yes, if that's easier for you!
