### ISSUE TITLE
Improve Implementation of Angular Reactive Forms

### ISSUE THREAD

**Issue by RDsideNow** [jhipster/generator-jhipster#10178]
##### **Make use of formArray in reactive forms with non one to one relationships**

Am pretty new to the software development world, and not sure if what i am requesting is clear, or plausible.  I really like the generator, and wanted to contribute, hopefully in a positive way to further improve this for others who use this tool. 

 I think using formArray when specifying non one to one relationships in a form will make it easier to have a parent to child form relationship.

I also think using a form model could also aid in decoupling the form in a component, allowing it to be used in multiple components?

I also think decoupling validation from the HTML and putting more in the component itself could reduce the HTML generated potentially, just based on other sample projects if have seen.  

##### **Motivation for or Use Case**

I have been trying to implement a similar parent child form from the example in the link below in my project, but find i am heavily modifying the generated code.

https://github.com/Josh-Hicks/NBA-team-app?source=post_page---------------------------

##### **Related issues or PR**

-   [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
You are welcome to make a PR to contribute this.

**Comment by RDsideNow** [comment]
@pascalgrimaud

For my i am trying to nest or inject another component form into a parent form (invoice line to an invoice). 

Current jhipster implementation joins these through the track by id on the template. 

What was referenced may not be the solution, but essentially i wanted to be able to nest full components in other components. 

I hope that explains it better?

On a side note, has ngrx integration ever been considered fo the jhipster project?

**Comment by wmarques** [comment]
@RDsideNow Hi, we never discussed about ngrx actually.
For me it adds a lot of boilerplate code for a basic app so I'm not in favour of implementing it, but we can discuss this with other contributors of course, that's only my opinion.

When you say "decoupling form in the component" do you mean using Reactive Forms ? Because that's already the case if I'm correct.

I agree that we lack of a formArray when we have a one to many relationship though.

**Comment by yelhouti** [comment]
For the Form Array part, I think it could be added by a new annotation, if the many part is managed through the one pat, we could have a formArray, else we keep the code as is.
I am also against ngrx, for simple state management, it is often much cleaner to use a service than a store, but ngrx has definitely many advantages in some cases. (just my opinion)

**Comment by wmarques** [comment]
@yelhouti What do you mean by new annotation ?

**Comment by yelhouti** [comment]
I meen we could have something like:
```
@managed
relationship OneToMany {
....
}
```
and if managed handle the Many Pat on the One Part

**Comment by pascalgrimaud** [comment]
@RDsideNow : thanks for proposing this.

Anyway, I don't really understand the request.
What I can suggest is:
- create a sample project, code your feature inside your project, share it on GitHub and ask opinion on Twitter, so you can have some feedback
- then, if you're motivated enough, try to code your own module or blueprint

If your module or blueprint is really popular, then we can reconsider to include it to the main generator 

So for now, let's close this. 
Don't hesitate to comment and share your code or module once you start the work
