### ISSUE TITLE
the version6.1.2 can not access in tomcat after build it as war

### ISSUE THREAD

**Issue by HuangAo** [jhipster/generator-jhipster#10179]
##### **Overview of the issue**

use "mvn clean install -Pprod" to build as war file and deploy to tomcat, in the screenshot the path "http://localhost:8080/content/css/loading.css" not exit in tomcat folder, the right path seems to be "http://localhost:8080//jhipster-sample-application-0.0.1-SNAPSHOT/content/css/loading.css" in my case

![issue](https://user-images.githubusercontent.com/22422179/62353422-364a9200-b53d-11e9-836b-e607664a47e7.png)

**Comment by atomfrede** [comment]
I think you have forgotten to change the `baseHref` in `webpack.common.js`.

`When deploying a JHipster app to an Application Server or customizing your context-path, it is required to set the baseHref value in webpack.common.jsor webpack.prod.js equal to the expected context-path.` See https://www.jhipster.tech/production/.

You can try to rename you `.war` file to `ROOT.war` and deploy that such that the app is deployed under the root path. If it is something else feel free to open this issue again.

**Comment by DanielFran** [comment]
@HuangAo Do not forget that since v6 now it is needed also to add the profile war (https://www.jhipster.tech/production/#build)
````sh
mvn clean install -Pprod,war
````

**Comment by HuangAo** [comment]
> @HuangAo Do not forget that since v6 now it is needed also to add the profile war (https://www.jhipster.tech/production/#build)
> 
> ```shell
> mvn clean install -Pprod,war
> ```

Thanks DanielFran, i changed the <packaging> vaule from jar to war before run the command
