### ISSUE TITLE
When running on kubernetes and pod is terminated, ContextClosedEvent is not published

### ISSUE THREAD

**Issue by rabiori** [jhipster/generator-jhipster#10186]
##### **Overview of the issue**

After upgrading to 6.1.2 (from 5.8.2), when running on k8s and pod is terminated, `ContextClosedEvent` is not published, despite being published in the past.

##### **Motivation for or Use Case**

We listen to it and perform some cleanup operations during the grace period, and it is no longer published.

##### **Reproduce the error**

Not sure if it will work the same, but 
* write code that listens to the event (aka. `@EventListener(ContextClosedEvent.class)`)
* deploy to k8s
* terminate the pod
* see that your code is not called

##### **JHipster Version(s)**

6.1.2 (after upgrade from 5.8.2)

##### **JHipster configuration**

Can't provide that right now, sorry...
If there is any specific field it is relevant, let me know.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by rabiori** [comment]
Appears to be connected to the change of the base image to `adoptopenjdk`, I think

**Comment by atomfrede** [comment]
Can you verify it works with e.g. `openjdk`?

**Comment by rabiori** [comment]
for me it did

**Comment by atomfrede** [comment]
Just asking because I can see any reason what the concrete jvm/jdk why spring should not publish this event (except some performance reason such that the pod is terminated before spring publishes the event).
