### ISSUE TITLE
openapi - generated pom.xml bug

### ISSUE THREAD

**Issue by GitAntinus** [jhipster/generator-jhipster#10180]
##### **Overview of the issue**

with open-api option selected,
in the generated pom.xml,
at openapi-generator-maven-plugin section,
execution.configuration
there is an element named "validateSpec",
which is not defined.
(promoted by intellij then manually check by me)

##### **Motivation for or Use Case**

programming error.

##### **Reproduce the error**

just generate a project.

##### **Suggest a Fix**

I think it should be
```xml
<skipValidateSpec>false</skipValidateSpec>
```
##### **JHipster Version(s)**
6.2.0

##### **JHipster configuration**
```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "ai.techfin",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "tradeSystem",
    "packageName": "ai.techfin",
    "packageFolder": "ai/techfin",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "rememberMeKey": "6784f92a8fac4fa29d9b9b32e41d9c8afd4c7f2267cb03b28eaf7c111b30c677537df84a06b10df98c4362ee546c2c5b8d3f",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ],
    "blueprints": [],
    "skipClient": true
  }
}
```

**Comment by atomfrede** [comment]
Thanks for reporting that @GitAntinus. You proposal seems correct, would you mind submitting a pull request?

**Comment by GitAntinus** [comment]
> Thanks for reporting that @GitAntinus. You proposal seems correct, would you mind submitting a pull request?

I would if i knew where to modify the code...

**Comment by atomfrede** [comment]
It is basically in this file. https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/pom.xml.ejs

Have a look at our contribution guidelines, it should be quite straight forward.

**Comment by pascalgrimaud** [comment]
@GitAntinus : don't hesitate to ask us if you need help on how to contribute

**Comment by amatosg** [comment]
@GitAntinus you have to edit this line: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/pom.xml.ejs#L1269 :+1:

**Comment by GitAntinus** [comment]
> @GitAntinus you have to edit this line: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/pom.xml.ejs#L1269 👍

thanks very much for your help

**Comment by GitAntinus** [comment]
> @GitAntinus : don't hesitate to ask us if you need help on how to contribute

thanks I just dont get time to do that
