### ISSUE TITLE
[Feature] subj-generator entity properties for custom type

### ISSUE THREAD

**Issue by jgribonvald** [jhipster/generator-jhipster#1019]
Is there some planning of integrating custom type as properties ? like 
- Enum
- Embedded objects
- ElementCollection for properties as Set<?> where ? could be basic or custom type

It would be great at least that we can generate these things from the .jhipster.entity.json
Also it would be great to be able to add custom annotation on entities.

**Comment by jdubois** [comment]
This is not planned yet, but if you are interested a PR is welcome.
It's a good idea, it's mostly me lacking time to do everything

**Comment by jdubois** [comment]
This is out of scope for the moment, too complex to implement
