### ISSUE TITLE
spring-boot-annotation-processor is unable to process package io.github.jhipster

### ISSUE THREAD

**Issue by GitAntinus** [jhipster/generator-jhipster#10195]
##### **Overview of the issue**
spring-boot-annotation-processor is unable to process package io.github.jhipster,
where a lot of config is done.
This is because compiler wont compile so wont process the downloaded package,
but to generate metadata, it need to be processed. 

##### **Motivation for or Use Case**
to generate better metadata for programming use.

##### **Reproduce the error**
generate a project with maven option, then compile. no metadata is avilable.

##### **Related issues**
#10194

##### **Suggest a Fix**
I suggest moving the io.github.jhispter package to generator so that the code inside would be generated into source folder.
I think this is a better solution than put the config code into a jar.
since I may need to modify or process the code there.
The code is related to the application anyway, it should be in the src folder. not a dependency.

a second way to fix this issue is to process io.github.jhipster to get the metadata file, then add this file
to generator. This is a easier one, but not so convenient since any modify in io.github.jhipster
would require a new process.

##### **JHipster Version(s)**
6.2.0

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
So basically your fix is to remove the jhipster lib :rofl:. Don't you think it would be better to add the annotation-processor to the `jhipster-framework` pom. If I understand things correctly this is how spring boot does it for their own libraries.

**Comment by DanielFran** [comment]
I checked quickly and we already have the processor dependency

**Comment by GitAntinus** [comment]
> So basically your fix is to remove the jhipster lib 🤣. Don't you think it would be better to add the annotation-processor to the `jhipster-framework` pom. If I understand things correctly this is how spring boot does it for their own libraries.

I've already processed the package and generated a metadata file. check it out

**Comment by GitAntinus** [comment]
> I checked quickly and we already have the processor dependency

it's not only about having the dependency dude. You need to invoke the processor to process the right package to get what you want.

**Comment by PierreBesson** [comment]
I think the processor will be invoked by the maven build when the jhipster framework will be released. It's not a the best to add this in the generated source as the JhipsterProperties might change in the future.

**Comment by PierreBesson** [comment]
@GitAntinus it works !

**Comment by GitAntinus** [comment]
> @GitAntinus it works !

Great success!
