### ISSUE TITLE
[Feature Request] - Frontend: Move FormGroup to service

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#10198]
##### **Overview of the feature request**
When having entities with many fields, having them in the `entity-update.component.ts` file could be tedious. Also, when coding side-by-side it will force me to duplicate my code for creating the form, updating the form and for creating the entity from form (those can be big methods).

##### **Motivation for or Use Case**
This change would allow anyone to work _side-by-side_ without repeating code, by just calling the service. For instance, I have moved the code to the service and I have a method like this:

``` 
createFromForm(editForm: FormGroup): IInvoice {
    return {
        ...new Invoice(),
        id: editForm.get(['id']).value,
        (...many other variables....)
        };
    }
``` 

and I would just call

`let invoice = this.invoiceService.createFromForm(this.editForm);`

I think this will improve readability, would make the code even cleaner, and again, it would stop repeated code in the front end.

##### **Related issues or PR**
None that I know of.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by yelhouti** [comment]
I would also add the following, the current version uses the constructor of an entity to initialize the asome fields (ex: boolean to false...) IMO, this should be done in the form initial values.
Also the route entity resolver (that retrieves the entity if the id is defined), should return `of(undefined)` when there is no Id. why do you think?

**Comment by yelhouti** [comment]
Also and more importantly IMO, createFromForm should use this.editForm.value .
Why? so that disabled fields are not send, ...

**Comment by vishal423** [comment]
@yelhouti, are you working on this? If not, I can try to wrap this up before vacations.

**Comment by yelhouti** [comment]
@vishal423 I didn't start yet, wanted to define the spec first, you can have an example on how you think the result should look like and I would gladly discuss it

**Comment by vishal423** [comment]
@yelhouti, I will assign this to you. I have started on different prototype, so, may not get much time. On my project (not JHipster based), I followed this approach:
- Create separate form model
- Create separate mapper service that allows conversion from/to domain/dto to form model.
- Define form element validations (required, length etc) in service.

**Comment by yelhouti** [comment]
@vishal423 I feel like the form and it's validation should be on the same file, if I move the form, to another component (so it can be imported and reused in another module), I understand the approach.
Also, form and model should have the exact structur, and we should use editForm.setValue, not init the form and editForm.value to retrieve it, instead of the code we have today. don't you agree?

**Comment by yelhouti** [comment]
> I will choose form.value or property by property mapping on a case by case basis. From the JHipster perspective, we should be flexible on this front and allow users to take a call that best suits their requirements.

I totally agree, but in the simple forms we generate we should use forms the way they were intended to be used, to show developers the best way to do the work. As you said, they can always change what they submit if they feel the need to.

What I meant is that, if we define `this.fb.group(...)` in some ts file we should have the the form fields `<form><input ...></form>` in the corresponding html file.

**Comment by yelhouti** [comment]
I have a version ready of what I want to do in this blueprint, please what the final code would look like:
https://github.com/elhoutico/jhipster-primeng-blueprint/blob/master/test/samples/primeng-blueprint-test/src/main/webapp/app/entities/task/task-update.component.ts

**Comment by wmarques** [comment]
@yelhouti LGTM
About using form.value vs explicit mapping, I would go for `form.value` if that's possible. It's easier to read and less code to write. If our users want specific mapping I think they can do it themselves :)

**Comment by yelhouti** [comment]
@wmarques great that we agree on this, I will make a PR asap.

**Comment by vishal423** [comment]
@yelhouti, I initially suggested the use of `form.value` in one of the review comments in reactive forms integration, however, there seem to be some cases that were not working. Check this link for an existing discussion on this https://github.com/jhipster/generator-jhipster/pull/9153#discussion_r252651385 

If that's not an issue anymore, then, we can do this change as well. However, I believe this is a different improvement than requested in this ticket and should be done separately.

**Comment by yelhouti** [comment]
@vishal423 thanks for pointing me to that thread. I asked few questions to understand why I didn't work for him. for me (my blueprint) it' works like a charm, but I might have missed something.

**Comment by pascalgrimaud** [comment]
Thanks for the request, but as no work has been done since months, I'm closing this for lack of interest

**Comment by amatosg** [comment]
@pascalgrimaud would it be ok if I work on this although is closed? I think having those methods in the service file would ease a side-by-side approach and reduce code duplication.

The idea is to have those methods as static so it can be reused.

**Comment by pascalgrimaud** [comment]
I'm not a front guy so my point of view is not the best one.
I'm not against to improve our code, but keep in mind the final release v7 is close so we should not introduce some breaking changes. It means if the change here is simple and it will be easy to upgrade from v7.0.0 to v7.0.1 for example, I'm fine.

**Comment by amatosg** [comment]
I'm going to wait until next release if that's ok

**Comment by yelhouti** [comment]
I think we should wait for the next release of angular where forms will be typed :)
