### ISSUE TITLE
Update dependency on ng-bootstrap to 5.1 for Angular

### ISSUE THREAD

**Issue by krusche** [jhipster/generator-jhipster#10209]
##### **Overview of the feature request**

Update the dependency on ng-bootstrap to 5.1 for Angular. ng-bootstrap 5.x is compatible with Angular 8.x so this should be possible.

##### **Motivation for or Use Case**

Allow jhipster user to get the newest features and bugfixes in ng-bootstrap and stay up-to-date with this dependency.

At the moment, this is not possible out of the box, because https://github.com/jhipster/ng-jhipster includes code that depends on ng-bootstrap 4, and there were some small breaking changes in ng-bootstrap 5. However, I don't think this would be much effort and it would be highly appreciated.

##### **Related issues or PR**

I was not able to find related issues

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
bootstrap `v5.x` is compatible with angular `v8.x` and this upgrade will remove warnings during installation. I think we also need to upgrade other dependencies.

@krusche would you be able to contribute to upgrade angular dependencies? Otherwise, I will do this over coming week.

**Comment by pascalgrimaud** [comment]
@vishal423 : you mentionned that `ng-jhipster` can't currently be released as it contains partial change related to translation optimization. Is it fixed today ?

**Comment by krusche** [comment]
@vishal423 sorry, I am not really familiar with ng-jhipster

**Comment by vishal423** [comment]
@pascalgrimaud, that's still an issue. I think we can revert that change to release `ng-jhipster` to fix other important issues like #9982

**Comment by pascalgrimaud** [comment]
@vishal423 : are you talking about reverting this PR https://github.com/jhipster/ng-jhipster/pull/99 ?

**Comment by vishal423** [comment]
@pascalgrimaud, yes, I was referring to that PR. Otherwise, if we can resolve #10069 early, then, that would be great.

**Comment by pascalgrimaud** [comment]
Sorry @vishal423, I didn't saw you self assign this ticket
I did the PR, it should be OK, just need to wait the CI

**Comment by vishal423** [comment]
no issues
