### ISSUE TITLE
add tree view e.g. with jstree or other similiar material library

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#10203]
#####

tree view on Frontend to display the relationships between entities for a simple user of the app

##### **Motivation for or Use Case**

Because of different relationship (1:n, n:n, 1:1) between entities, sometimes the crud-views on frontend doesn't convey a simple overview of entities.

##### **Related issues or PR**

I don't know if there is a similar request already :) 

-   [x] Checking this box is mandatory (this is just to show you read everything)

Cheers
Yuqiu

**Comment by PierreBesson** [comment]
@geyuqiu Could you be more precise on your idea, maybe with a diagram/mockup of what this would look like.

**Comment by gmarziou** [comment]
For which frontend framework? 

For Angular/Bootstrap, there's https://leovo2708.github.io/ngx-treeview/#/components

**Comment by pascalgrimaud** [comment]
I don't think it should go directly to generator-jhipster, as this one won't bring too much value.

@geyuqiu : if you think it's an important feature request, I invite you to create a module for that. Have a look at https://www.jhipster.tech/modules/creating-a-module/#-creating-a-module
Don't hesitate to ping us (here or twitter) as soon as you code / release a 1st version.

Then, if it's a big success, we can reconsider this feature.
For now, let's close this and focus on other tickets / bugs
