### ISSUE TITLE
Wrong regexp for CacheBuster

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1020]
I came across the init of CacheBuster in app.js and it seems to me that it still using the old /rest URI rather than new /api which could explain some strange behavior around authentication that were reported recently. 

https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/webapp/scripts/app/_app.js#L63

~~~javascript
        //Cache everything except rest api requests
        httpRequestInterceptorCacheBusterProvider.setMatchlist([/.*rest.*/, /.*protected.*/], true);
~~~

I did not make a PR as I haven't tested anything.

**Comment by jdubois** [comment]
You are correct, as I forgot about it....

**Comment by jdubois** [comment]
Done
