### ISSUE TITLE
[Feature Request] Create IDs as unsigned

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#10200]
##### **Overview of the feature request**
When using a SQL db, it doesn't make sense to have negative IDs (AFAIK it would never happen).

##### **Motivation for or Use Case**
Creating unsigned columns would double the range of IDs. I know, it's a very rare scenario, but is still an improvement.

The change would be to simple add `UNSIGNED` in [this](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs#L51) line.
##### **Related issues or PR**
None that I know of.

-   [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by SudharakaP** [comment]
@PierreBesson : I'll create a pull request this week for this one. I think we need to do a simple check to see if it's not a string type (such as ```VARCHAR``` type) in order to apply ```UNSIGNED``` .

**Comment by gmarziou** [comment]
@amatosg your proposed change applies only to column type, what about the field type in java entity? Are you sure that a java long will be bale to take advanatge of an unisgned id column? 

Have you made some test when column value is  between 2^63 and  2^64-1 does it convert to negative number in java entity?

**Comment by amatosg** [comment]
> Have you made some test when column value is between 2^63 and 2^64-1 to see if it converts to negative number in java entity?

Oh, I see what you mean, after 9,223,372,036,854,775,808 the number goes around and starts at negative, right? And using `BigInteger` wouldn't make much sense either.

So even if `UNSIGNED` is added, it would work when going beyond 9,223,372,036,854,775,807 as it would go around to nevative.
