### ISSUE TITLE
jhiHasAnyAuthority doesn't work in freshly opened page

### ISSUE THREAD

**Issue by arslan2012** [jhipster/generator-jhipster#10211]
##### **Overview of the issue**

jhiHasAnyAuthority doesn't work in freshly opened page, it only works if user had opened other pages before.

##### **Motivation for or Use Case**

I have a page /item/1 that does not use accountService.
in it, there is an element that uses *jhiHasAnyAuthority.
the element will not show up if I directly opened the page.

##### **Suggest a Fix**

further investigation suggests that accountService.getAuthenticationState() will not return if accountService.identity() hasn't been called before. so I changed my HasAnyAuthorityDirective
```
@@ -25,6 +25,7 @@
     this.authorities = typeof value === 'string' ? [value] : value;
     this.updateView();
     // Get notified each time authentication state changes.
+    this.accountService.identity();
     this.accountService.getAuthenticationState().subscribe(identity => this.updateView());
   }
 


```

this solved my problem.

##### **JHipster Version(s)**
6.2.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "admin",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "lux",
    "clientThemeVariant": "primary",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": [],
    "skipServer": true
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Gentoo icedtea-3.12.0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

git version 2.22.0

node: v11.14.0

npm: 6.7.0

yeoman: 2.0.6

yarn: 1.16.0

##### **Browsers and Operating System**

Firefox on Gentoo

**Comment by pmverma** [comment]
Thanks @arslan2012 for reporting the issue.
Can you please update it with steps to reproduce?

**Comment by pascalgrimaud** [comment]
I'm closing this, as we don't have steps to reproduce.
Feel free to give more details to help us reproducing your issue
