### ISSUE TITLE
Add bootswatch theme in JDL application.config

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#10212]
##### **Overview of the feature request**

I would want to define the Bootswatch theme of my application directly in my `.jdl` file to have the same feature as what I can obtain using the CLI while creating a new application.

##### **Motivation for or Use Case**

Have the same feature using the `jhipster-generator` CLI or using a JDL file.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
There was this ticket: https://github.com/jhipster/jhipster-core/issues/332
The work was done by @MathieuAA here: https://github.com/jhipster/jhipster-core/commit/b96b92ceac97bc859db81da6124d2db0650d6eb1

I think we simply forget to update the documentation.
