### ISSUE TITLE
./gradlew liquibaseDiffChangelog throws Errors:   Unknown parameter: 'excludeObjects'

### ISSUE THREAD

**Issue by gojesandeep** [jhipster/generator-jhipster#1021]
Environment : 
 DB: Postgres 9.3
 Build : Maven
Java Version 8
OS : Mac OSX 10.10
./gradlew liquibaseDiffChangelog command throws 

:compileJava UP-TO-DATE
:nodeSetup SKIPPED
:npmSetup SKIPPED
:npmInstall UP-TO-DATE
:bower
:processResources UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:liquibaseDiffChangelog
Errors:
  Unknown parameter: 'excludeObjects'
Last few lines of output : 
Unexpected error running Liquibase: Unknown parameter: 'excludeObjects'

[ERROR] liquibase - Unknown parameter: 'excludeObjects'
liquibase.exception.CommandLineParsingException: Unknown parameter: 'excludeObjects'
	at liquibase.integration.commandline.Main.parseOptions(Main.java:702) [liquibase-core-3.3.2.jar:na]
	at liquibase.integration.commandline.Main.run(Main.java:124) [liquibase-core-3.3.2.jar:na]
	at liquibase.integration.commandline.Main.main(Main.java:94) [liquibase-core-3.3.2.jar:na]

For more information, use the --logLevel flag
:liquibaseDiffChangelog FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':liquibaseDiffChangelog'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java'' finished with non-zero exit value 255

Found this issue https://liquibase.jira.com/browse/CORE-875 and found it to be fixed in 3.3.2 .

**Comment by gojesandeep** [comment]
task liquibaseDiffChangelog(dependsOn: compileJava, type: JavaExec) {
  group = "liquibase"

  classpath sourceSets.main.runtimeClasspath
  classpath configurations.liquibase
  main = "liquibase.integration.commandline.Main"

  args "--changeLogFile=src/main/resources/config/liquibase/changelog/" + buildTimestamp() +"_changelog.xml"
  args "--referenceUrl=hibernate:spring:com.golive.platform.domain?dialect=org.hibernate.dialect.PostgreSQL9Dialect"
  args "--username=sandeepgoje"
  args "--password="
  args "--url=jdbc:postgresql://localhost/live"
  args "--driver=org.postgresql.Driver"
  args "--excludeObjects=oauth_access_token, oauth_approvals, oauth_client_details, oauth_client_token, oauth_code, oauth_refresh_token"
  args "diffChangeLog"
}

**Comment by jdubois** [comment]
You said that your build is with Maven, but you use the Gradlew command... It's either you selected Maven, or Gradle.

**Comment by gojesandeep** [comment]
Sorry for the mistake. I am using Gradle

**Comment by atomfrede** [comment]
Very strange as the same worked for me with mysql. According to the [latest release notes](http://blog.liquibase.org/2015/01/liquibase-3-3-2-released.html) ``excludeObjects`` is the expected argument. Will check it out during the weekend.

**Comment by gojesandeep** [comment]
I have checked if there was any bug and found the feature request URL I pasted. I went through the liquibase code base to check where the exception was being thrown but could not go further.

**Comment by atomfrede** [comment]
Are you using oauth or session based authentication?

**Comment by gojesandeep** [comment]
I have setup with OAuth

The most profound statements are often said in silence.
-Lynn Johnston

**Comment by gojesandeep** [comment]
I tried commenting out that line and checked but it was throwing a bunch of migrations which should not be triggered so I reverted back.

**Comment by atomfrede** [comment]
Solution: just put the line with ``excludeObjects`` after the line with ``diffChangelog``:

```
args "diffChangeLog"
args "--excludeObjects=oauth_access_token, oauth_approvals,   oauth_client_details,oauth_client_token, oauth_code, oauth_refresh_token"
```

**Comment by gojesandeep** [comment]
Thanks for the help. It worked for me.
