### ISSUE TITLE
import-jdl does not install the blueprint before the first import

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#10217]
##### **Overview of the issue**
When trying to create a project using a jdl with application block and blueprints, ex:
```
jhipster --blueprints primeng-blueprint@latest import-jdl jhipster.jh
```
jhipster doesn't find the blueprint in the empty folder resulting on:
```
WARNING! Could not retrieve version of blueprint 'generator-jhipster-primeng-blueprint'
```
npm install (locally) or npm link fixes the problem, but I feel like jhipster should install the dependency locally before starting the import or at least look for it globally, what do you guys think?

##### **Motivation for or Use Case**
being able to generate the app in one click without prior knowledge of jhipster internals

**Comment by pascalgrimaud** [comment]
I already encountered the problem.

For the solution: I prefer a global installation like generator-jhipster, than a local installation before the 1st run. Because the user will have to wait before answering questions.

But currently, a global installation seems not enough too, so we need to fix it. 

@yelhouti : do you have an idea ? do you want to have a look ?

**Comment by yelhouti** [comment]
@pascalgrimaud on how to use the global installation? sure, the same way yoman does it? do you want me to try to write a fix? I ll gladly do

**Comment by pascalgrimaud** [comment]
Yes exactly, I think the workflow should be:

```
npm install -g generator-jhipster
npm install -g generator-jhipster-vuejs
mkdir toto
cd toto
jhipster --blueprint vuejs
```

Thanks a lot !

**Comment by deepu105** [comment]
Thats starnge. My original implementation made sure it can fetch from
global if local is not available

Thanks & Regards,
Deepu

**Comment by yelhouti** [comment]
Great, now I can't reproduce it, closing until I can...

**Comment by yelhouti** [comment]
I can confirm that the problem is still there, but it doesn't always manifest, I will investigate once I have more time
