### ISSUE TITLE
Document how to use other yeoman angular generators

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1022]
JHipster 2

I have tried to use other yeoman generators to generate an angular service or other components and found it hard to do,.

I think some documentation would help and maybe some thinking about whether this is the way to go or whether jhipster should provide its own sub generators.

I'm a yo newbie so maybe there's a way to configure things in `.yo-rc.json` file so that it is compatible with several generators

To give an example, I wanted to create a service named invoice, so I tried several generators and below I noted the issues.

## Angular generator

~~~
yo angular:service invoice
   create src\main\webapp\scripts\services\invoice.js
   create src\test\javascript\spec\services\invoice.js
~~~

Project structure does not exactly map, in jhipster I think the expected structure should be:

~~~
src\main\webapp\scripts\app\invoice\invoice.service.js
src\test\javascript\spec\app\invoice\invoice.service.spec.js
~~~

Please note that currently the specs are named using camel case: invoiceServiceSpec.js

## MeanJS generator

Not really usable, different naming convention, notion of module missing in jhipster.

## Angular-fullstack generator

By running it a the root level, we need to specify the path.

~~~
yo angular-fullstack:service invoice
? Where would you like to create this service? (client/app/) src/main/webapp/scripts/app
   create src\main\webapp\scripts\app\invoice\invoice.service.js
   create src\main\webapp\scripts\app\invoice\invoice.service.spec.js
~~~

The test spec is saved in same folder as the service which does not map well to jhipster project structure.

By running it in app sub folder, it's easier to use.

~~~
cd src\main\webapp\scripts\app
yo angular-fullstack:service facture
? Where would you like to create this service? (client/app/) .
   create src\main\webapp\scripts\app\invoice\invoice.service.js
   create src\main\webapp\scripts\app\invoice\invoice.service.spec.js
~~~

**Comment by gmarziou** [comment]
I tried generator-ng-component and its configuration can be better tuned than the other ones, the default path where the files arez generated and it even seems possible to provide a template.

The only problem is that it generates the test in same folder than component.

-----
npm install -g generator-ng-component
yo ng-component:service invoice
Where would you like to create this service? src/main/webapp/scripts/app/
   create src\main\webapp\scripts\app\invoice\invoice.service.js
   create src\main\webapp\scripts\app\invoice\invoice.service.spec.js
-----

~~~javascript
  "generator-ng-component": {
    "routeDirectory": "src/main/webapp/scripts/app/",
    "directiveDirectory": "src/main/webapp/scripts/app/",
    "filterDirectory": "src/main/webapp/scripts/app/",
    "serviceDirectory": "src/main/webapp/scripts/app/",
    "basePath": "",
    "moduleName": "",
    "filters": [
      "uirouter"
    ],
    "extensions": [
      "js",
      "html",
      "scss"
    ],
    "directiveSimpleTemplates": "",
    "directiveComplexTemplates": "",
    "filterTemplates": "",
    "serviceTemplates": "",
    "factoryTemplates": "",
    "controllerTemplates": "",
    "decoratorTemplates": "",
    "providerTemplates": "",
    "routeTemplates": ""
  }
~~~

**Comment by gmarziou** [comment]
I think the final answer (and maybe to document) is that jhipster users should not expect other angularjs generators to be compatible with jhipster.

**Comment by jdubois** [comment]
Yes, Yeoman generators are not compatible with each other, so it just doesn't work.
Just @jmirc did a job to make the "angular" generator work with JHipster, but that was specific to this generator, which is very simple, and we haven't pushed tests very far, so I don't know how useful it is.

**Comment by kringon** [comment]
i think this functionality would be very usefull!

**Comment by verrol** [comment]
If all the Angualr generator were using the same project structure, then it would be useful to be able to switch. Generators come with different sub-generators too. Wouldn't it be a huge undertaking to provide CRUD forms for several generators?

One of the themes I see mentioned here several times is that, jHipster should make it easy to get you going and not try to do everything. Wouldn't some of the other generators have different learning curves? The harder jHipster is to use, we will have fewer new users picking it up. One of the things I really liked, was how I can get a full stack app in about 13 question.
