### ISSUE TITLE
Blob fields generate invalid angular services/components

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#10229]
##### **Overview of the issue**

Generating an entity with a blob fields of type image results in a frontend which can't compile, because of wrong imports.

##### **Motivation for or Use Case**

Although blob support is still in beta it should not fail like that. 

##### **Reproduce the error**

Create a fresh application, create an entity with a blob field (of type image).

##### **Related issues**

--

##### **Suggest a Fix**

Somehow the imports are wrong:

* `import { createRequestOption } from 'app/shared';`
* `import { UserRouteAccessService } from 'app/core';`
* `import { JhiLanguageHelper } from 'app/core';`
* `import { CspfiledownloadSharedModule } from 'app/shared';`
* `import { AccountService } from 'app/core';`

##### **JHipster Version(s)**

Current master at least

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "cspfiledownload",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "blueprints": []
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
entity Downloadable {
  myimage ImageBlob
}
```

##### **Browsers and Operating System**

Not relevant for this issue.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
@atomfrede, I think you are not using latest check-ins on master as imports should be absolute. Can you please check again on latest master code?

**Comment by vishal423** [comment]
Further, I believe we do test `ImageBlob` fields in our builds like @ 
https://github.com/jhipster/generator-jhipster/blob/29592ab0bd158ecd0829c406d594537a4f91b7d8/test-integration/samples/jdl-default/app.jdl#L52

**Comment by atomfrede** [comment]
Too early as it seems. Will check but I think I forgot to link my fork
again before creating the entity.
