### ISSUE TITLE
Polish file and class names in Angular part

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#10220]
##### **Overview of the issue**

Issues I discovered when refactoring imports in Angular part (barrel remove in #10185):

* inconsistent component and service class prefixes: components and services are mainly without prefix, but some of them have prefix `<%=jhiPrefixCapitalized%>`: `AlertErrorComponent`, `AlertComponent`, `ConfigurationComponent`, `ConfigurationService`, `DocsComponent`, `GatewayComponent`, `HealthModalComponent`, `HealthCheckComponent`, `HealthService`, `LoginModalComponent`, `MainComponent`, `MetricsMonitoringComponent`, `MetricsService`, `TrackerComponent`, `TrackerService`  
Why such difference? I think it would be good practice to use one style, so 2 possible solutions:
    * either remove prefix `<%=jhiPrefixCapitalized%>` from all components and services
    * or add prefix `<%=jhiPrefixCapitalized%>` to all components and services

* modules are prefixed differently, with prefix `<%=angularXAppName%>`, why this prefix is different, maybe use the same prefix `<%=jhiPrefixCapitalized%>` as used in components and services? If prefix will be removed from all components and services then this inconsistency will disappear, then only prefix `<%=angularXAppName%>` remains in use and this is not the case any more.

* as standard, service files have suffix `.service.ts`, but one file is different: `user-route-access-service.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/core/auth/user-route-access-service.ts.ejs - dash instead of point before service), suggestion: rename this file to `user-route-access.service.ts`

* some class or file names doesn't follow general name convention:
    * register service class name is `Register` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/account/register/register.service.ts.ejs#L26), suggestion: rename this class to `RegisterService` (other service classes are ending with suffix Service)
    * in `health.component.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.ts.ejs#L29) class name is `HealthCheckComponent`, suggestion: rename this to `HealthComponent`
    * in `metrics.component.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.ts.ejs#L28) class name is `MetricsMonitoringComponent`, suggestion: rename this to `MetricsComponent`
    * better name for file `errorhandler.interceptor.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts.ejs#L26) is `error-handler.interceptor.ts` (class name inside this is `ErrorHandlerInterceptor`)
    * in file `auth-jwt.service.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs#L31) class name is `AuthServerProvider`, suggestion: rename class to `AuthJwtService`
    * in `langauge.helper.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/core/language/language.helper.ts.ejs#L31) class name is `JhiLanguageHelper`, suggestion: rename class to `LanguageHelper`
    * in `login.component.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.ts.ejs#L32) class name is `LoginModalComponent`, suggestion:
        * change `login.component.ts` to `login-modal.component.ts`
        * change `login.component.html` to `login-modal.component.html`

##### **Motivation for or Use Case**

Using unified style makes code better readable and avoids confusions why some files or classes are named not logically.

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@kaidohallik : thanks for taking time to write this ticket with full details !

**Comment by deepu105** [comment]
Since these will be breaking lets do it for next major version

Thanks & Regards,
Deepu

**Comment by kaidohallik** [comment]
One more suggestion for refactoring, rename:
* class `EntityModule` to `EntityRoutingModule`
* file `entity.module.ts` to `entity-routing.module.ts`

Reason: before implementing entity lazy loading this module was collection of entity modules, but after that this is a routing module. Code is better readable if file and class names reflect their content as accurately as possible.

**Comment by kaidohallik** [comment]
If cleaning `app.module` and `core.module` some changes in #10340 left out from simplified version #10360.

So additional refactor suggestions:
* move modules to better suitable location:
    * `shared/util/datepicker-adapter.ts` to `core/date/datepicker-adapter.ts`
    * `blocks/config/prod.config.ts` to `core/config/prod.config.ts`
    * `blocks/config/uib-pagination.config.ts` to `core/config/uib-pagination.config.ts`
    * `blocks/interceptor/auth.interceptor.ts` to `core/interceptor/auth.interceptor.ts`
    * `blocks/interceptor/auth-expired.interceptor.ts` to `core/interceptor/auth-expired.interceptor.ts`
    * `blocks/interceptor/errorhandler.interceptor.ts` to `core/interceptor/error-handler.interceptor.ts`
    * `blocks/interceptor/notification.interceptor.ts` to `core/interceptor/notification.interceptor.ts`
* after that whole `blocks` folder can be deleted
* PR #10340 also includes one possible solution how to inform user if file is moved into new location and old and new version differ, read #10340 for other ideas
* `providers` section should be deleted from `app.module` and existing providers moved to `core.module`

**Comment by kaidohallik** [comment]
In #10443 new modules added without prefix `<%=angularXAppName%>`, so current direction is to remove this prefix from all modules in the new major version.

**Comment by kaidohallik** [comment]
I saw that @deepu105 added label `Hactoberfest` here.

I think that for file renaming tasks precondition is merging PR #10521 - then people who upgrade:
* will see notifications in the console if old and new content of the renamed file differ
* in Git commit preview can see what files are renamed and can see changes between old and new version

**Comment by kaidohallik** [comment]
This comment is preparation to resolve this issue (after #10521 is merged which partially resolves this and adds core functionality for other changes).

As in #10443 was already started removing prefix so I think we should resolve this issue by removing prefixes `<%=jhiPrefixCapitalized%>` and `<%=angularXAppName%>` from all components, services and modules.

@deepu105 said in one previous comment that this is a breaking change. I tried to analyze changes and I grouped changes into 3 groups.

1. Changes that can be considered as breaking. These are common modules-components what existing apps can import and existing modules can import in added content. If this is the case then user gets compilation errors and must fix import clauses.
* module name in `entity-management.module` - this can include microservice name as prefix, so this is a special case and must be treated separately, one solution: if `locals.microserviceName` is specified then use this prefix also in the future version
* `SharedModule` renaming
* `JhiLanguageHelper` renaming
* rename `user-route-access-service.ts` to `user-route-access.service.ts`

2. Changes that at first sight seem to be breaking but actually are not.
* `AlertErrorComponent` and `AlertComponent` renaming - these are shared components, but imported only in `SharedModule` and used by selector, so changing component name is safe internal change
* `LoginModalComponent` renaming and rename file `login.component` to `login-modal.component` - imported internally only in `SharedModule` and `LoginModalService` and no need to import this in custom modules and this in fact is not suitable to `SharedModule`, I would like to move this under `core/login` (where login services are) and move declaration from `SharedModule` to `AppModule`
* `MainComponent` - used only internally in `app.module`
* `entity.module` component name renaming and file name renaming to `entity-routing.module` - new routes for entity lazy loading are added using needle API (which is adjusted to new location) and moving file doesn't break anything, this is internal change, I would also like to move newly named `EntityRoutingModule` import from `app.module` to `app-routing.module`

3. Other changes have clearly local impact in my opinion and are not breaking.

So currently it seems to me that correct road map to resolve this issue is:
* wait while #10521 is merged
* PR for changes in group 2 and 3
* wait while group 2 and 3 PR is merged
* PR for changes in group 1 and label this PR for v7 (if all agree that these are breaking changes and can't be merged now)

Note: if it is decided that group 1 changes are not breaking then road map is:
* wait while #10521 is merged
* PR for changes in group 1, 2 and 3

**Comment by deepu105** [comment]
Lets keep major restructure stuff for v7, these are not pressing concerns
anyway

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
@kaidohallik : what is the state of this ticket plz ?

**Comment by kaidohallik** [comment]
Still some todo because didn't dare to change in v6:
* some modules have still prefix `<%=angularXAppName%>`
* `user-route-access-service.ts` is not renamed to `user-route-access.service.ts`
* `errorhandler.interceptor.ts` is not renamed to `error-handler.interceptor.ts`
* login functionality should be in one single place (currently split into 2 different folders `shared/login` and `core/login`):
    - `shared/login/login.component.ts` is not moved to `core/login/login-modal.component.ts`
    - `shared/login/login.component.html` is not moved to `core/login/login-modal.component.html`
* `shared/util/datepicker-adapter.ts` is not moved to `core/date/datepicker-adapter.ts`
* entity module is not renamed:
    - class `EntityModule` to `EntityRoutingModule`
    - file `entity.module.ts` to `entity-routing.module.ts`

Moving `blocks` under `core` is not must have. @vishal423 proposed to rethink Angular app structure in v7: https://github.com/jhipster/generator-jhipster/pull/10521#issuecomment-538985740

Other changes are done.

**Comment by pascalgrimaud** [comment]
thanks a lot for clarification @kaidohallik
so I'm adding v7 label

**Comment by pascalgrimaud** [comment]
@kaidohallik : did you get a bounty for all other tickets related to this one, like strict mode and other stuff ?

**Comment by kaidohallik** [comment]
Yes, all those changes were part of strict mode PR-s, so I got bounty from #10631

**Comment by qmonmert** [comment]
@pascalgrimaud I'm working on this : 

Still some 

> todo because didn't dare to change in v6:

> some modules have still prefix <%=angularXAppName%>
> user-route-access-service.ts is not renamed to user-route-access.service.ts
> errorhandler.interceptor.ts is not renamed to error-handler.interceptor.ts
> login functionality should be in one single place (currently split into 2 different folders shared/login and core/login):
> shared/login/login.component.ts is not moved to core/login/login-modal.component.ts
> shared/login/login.component.html is not moved to core/login/login-modal.component.html
> shared/util/datepicker-adapter.ts is not moved to core/date/datepicker-adapter.ts
> entity module is not renamed:
> class EntityModule to EntityRoutingModule
> file entity.module.ts to entity-routing.module.ts

**Comment by qmonmert** [comment]
> Still some todo because didn't dare to change in v6:
> 
> * some modules have still prefix `<%=angularXAppName%>`
> * `user-route-access-service.ts` is not renamed to `user-route-access.service.ts`
> * `errorhandler.interceptor.ts` is not renamed to `error-handler.interceptor.ts`
> * login functionality should be in one single place (currently split into 2 different folders `shared/login` and `core/login`):
>   
>   * `shared/login/login.component.ts` is not moved to `core/login/login-modal.component.ts`
>   * `shared/login/login.component.html` is not moved to `core/login/login-modal.component.html`
> * `shared/util/datepicker-adapter.ts` is not moved to `core/date/datepicker-adapter.ts`
> * entity module is not renamed:
>   
>   * class `EntityModule` to `EntityRoutingModule`
>   * file `entity.module.ts` to `entity-routing.module.ts`
> 
> Moving `blocks` under `core` is not must have. @vishal423 proposed to rethink Angular app structure in v7: [#10521 (comment)](https://github.com/jhipster/generator-jhipster/pull/10521#issuecomment-538985740)
> 
> Other changes are done.

@pascalgrimaud I'm working on this

**Comment by qmonmert** [comment]
@kaidohallik when you say "**some modules have still prefix <%=angularXAppName%>**", do you mean that we replace

```
import { <%= angularXAppName %>SharedModule } from 'app/shared/shared.module';
import { <%= angularXAppName %>CoreModule } from 'app/core/core.module';
import { <%= angularXAppName %>AppRoutingModule } from './app-routing.module';
import { <%= angularXAppName %>HomeModule } from './home/home.module';
import { <%= angularXAppName %>EntityRoutingModule } from './entities/entity-routing.module';
```
by
```
import { SharedModule } from 'app/shared/shared.module';
import { CoreModule } from 'app/core/core.module';
import { AppRoutingModule } from './app-routing.module';
import { HomeModule } from './home/home.module';
import { EntityRoutingModule } from './entities/entity-routing.module';
```
for example ? 

cc @pascalgrimaud

**Comment by qmonmert** [comment]
PR #12182

**Comment by qmonmert** [comment]
@jdubois & @pascalgrimaud I claim my money 😄  https://opencollective.com/generator-jhipster/expenses/23283
