### ISSUE TITLE
blueprints not found in Windows

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#10223]
##### **Overview of the issue**

Since #10004 it's not possible to use blueprints in `Windows`.  
Error occurs in all tested shells: `Command Prompt`, `Git Bash` and `PowerShell`.
Not tested in Mac and Linux but as no problems have reported then I guess blueprints are working in these operating systems.

##### **Motivation for or Use Case**

Want to use blueprints also in Windows.

##### **Reproduce the error**

Install blueprint: `npm install -g generator-jhipster-vuejs`  
Run JHipster with blueprint: `jhipster --blueprint vuejs`  
This causes the following behavior:
* command line window is deactivated, some other window is activated
* if coming back to command line window then the following error is displayed:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: The generator-jhipster-vuejs blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-vuejs.
    at Environment.error (C:\projects\kaido-github\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:176:40)
    at module.exports.error (C:\projects\kaido-github\generator-jhipster\generators\generator-base.js:1448:18)
    at shelljs.exec (C:\projects\kaido-github\generator-jhipster\generators\generator-base-private.js:845:22)
    at C:\projects\kaido-github\generator-jhipster\node_modules\shelljs\src\exec.js:121:9
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Emitted 'error' event at:
    at Environment.error (C:\projects\kaido-github\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:178:15)
    at module.exports.error (C:\projects\kaido-github\generator-jhipster\generators\generator-base.js:1448:18)
    [... lines matching original stack trace ...]
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

##### **Related issues**

#10004

##### **Suggest a Fix**

In Windows I could fix this by changing line https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base-private.js#L837 (added `node` at the beginning of the command) from
```
shelljs.exec(`${yoInternalCliPath} --generators`, { silent: true }, (err, stdout, stderr) => {
```
to
```
shelljs.exec(`node ${yoInternalCliPath} --generators`, { silent: true }, (err, stdout, stderr) => {
```
If this works also in Mac and Linux then this is universal fix. If not then probably need to check which operating system is used and if Windows then add `node` at the beginning of the command.

FYI: globally installed `yo` command files in my Windows are with these contents:

<details>
<summary>yo</summary>
<pre>
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/yo/lib/cli.js" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/yo/lib/cli.js" "$@"
  ret=$?
fi
exit $ret
</pre>
</details>

<details>
<summary>yo.cmd</summary>
<pre>
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\yo\lib\cli.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\yo\lib\cli.js" %*
)
</pre>
</details>

Additional note about #10004 - in line https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base-private.js#L835 it's cleaner to use `path.join` as used in other places in JHipster source code, change from
```
const yoInternalCliPath = `${__dirname}/../node_modules/yo/lib/cli.js`;
```
to
```
const yoInternalCliPath = path.join(__dirname, '../node_modules/yo/lib/cli.js');
```

##### **JHipster Version(s)**

```
C:\projects\teest\jhipster-vuejs
`-- generator-jhipster@6.2.0  -> C:\projects\kaido-github\generator-jhipster

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.15.2

Docker version 19.03.1, build 74b1e89

docker-compose version 1.24.1, build 4667896b
##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@kaidohallik : it is an important issue. Can you propose a PR plz ? I'm using Linux so I can test it

**Comment by clement26695** [comment]
I did not read completely your issue, so it can be totally off topic, but I found that there are issues when the main generator is installed locally and the blueprint globally (or vice-versa, I can't remember).

**Comment by kaidohallik** [comment]
@pascalgrimaud I opened PR #10225 for fix

**Comment by kaidohallik** [comment]
@clement26695 main generator locally and blueprint globally can maybe cause strange behavior I encountered in generating Vue app as described in #10224

**Comment by pascalgrimaud** [comment]
thanks @kaidohallik
I'll test your PR soon

**Comment by arabbani** [comment]
This is still not working on windows. Can you reopen the issue.

**Comment by pascalgrimaud** [comment]
@arabbani : can you provide more information plz ? Which version of JHipster ? Which blueprint, etc...
You can have a look at all tickets and PR related to this one. There are other fix too

**Comment by arabbani** [comment]
JHipster 6.3.0.
Blueprint - kotlin.
OS - Windows 10.

**Comment by arabbani** [comment]
Any update?
