### ISSUE TITLE
Generating an entity should not create json file at project root

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1023]
In Jhipster 2, when creating an entity named invoice with `yo jhipster:entity invoice`, generator creates a `.jhipster.invoice.json` file at the root of the project. 
I don't know whether this file must be kept or not: it does not seem to be used by the application so maybe it's used by the generator, in such case it would be nicer to keep it under a sub directory like `.jhipster.entities` as otherwise the project root will have too many of them

**Comment by leonardoavs** [comment]
I totally agree with this, if we put the entity json file that is generated by jhipster in a subfolder, this can be a very good feature.

**Comment by jdubois** [comment]
It's a hidden field (with a dot), but I understand it can be annoying for Windows users.
We could do a ".jhipster" instead.
It would also be easier to move around.
Note that I expect great things from this file, see #925 for example, but at the moment the usage is:

- helps you re-generate the entity easily -> so if you migrate it's easier
- easy to copy, so you can generate the same entity in other projects
- it's not too difficult to change, so some people are already using this to generate several entities which are close to each other

**Comment by jdubois** [comment]
Sorry I closed it by mistake

**Comment by gmarziou** [comment]
+1 for the ".jhipster" folder and great ideas

**Comment by jimbobwyatt** [comment]
Not seeing this today after generating an entity. Resolved?

**Comment by jdubois** [comment]
@jimbobwyatt it's a hidden file, there's a dot in front of it

**Comment by jimbobwyatt** [comment]
Got that part, still not seeing it. Windows only thing? Problem that I am not seeing it. My entity works just fine...

**Comment by jdubois** [comment]
If you run the entity sub-generator again for the same entity, does it asks you the questions again? It should not, as it's normally reading the file

**Comment by jimbobwyatt** [comment]
Yes, it does. Just getting up to speed on the project or I would run that down for you. 

My command: yo jhipster:entity key

Output: Generating field #1
? Do you want to add a field to your entity? (Y/n)

'npm install -g yo' ran before I started playing today, but I was already on the 2.x release. Also a complete node idiot by choice if that has anything to do with it, so there is that.

**Comment by jimbobwyatt** [comment]
Not completely sure I updated to 2.1.1 so I did and same behavior. Mixing releases there...god I hate node, really only willing to learn for this project.

**Comment by jdubois** [comment]
Anyway, you should have the "dot" file -> it's been there for a long time, and we still haven't moved it to a separate folder.

**Comment by jimbobwyatt** [comment]
```
**********@********:~/**********$ ls -al
total 120
drwxrwxr-x.  6 ********** **********  4096 Feb 10 14:14 .
drwxrwxr-x.  3 ********** **********  4096 Jan 24 11:20 ..
-rw-r--r--.  1 ********** **********   712 Jan 24 11:14 bower.json
-rw-r--r--.  1 ********** **********    56 Jan 24 11:14 .bowerrc
-rw-r--r--.  1 ********** **********   475 Dec  4 00:43 .editorconfig
-rw-r--r--.  1 ********** **********   344 Dec  4 01:09 .gitattributes
-rw-r--r--.  1 ********** **********   142 Dec  4 00:43 .gitignore
-rw-r--r--.  1 ********** ********** 13966 Jan 24 11:14 Gruntfile.js
drwxrwxr-x.  5 ********** **********  4096 Jan 24 11:22 .idea
-rw-r--r--.  1 ********** **********   389 Dec 11 13:46 .jshintrc
drwxrwxr-x. 43 ********** **********  4096 Jan 24 11:15 node_modules
-rw-rw-r--.  1 ********** ********** 16334 Jan 24 11:22 ockms.iml
-rw-r--r--.  1 ********** **********  1428 Jan 24 11:14 package.json
-rwxr-xr-x.  1 ********** ********** 25221 Jan 24 11:14 pom.xml
-rw-r--r--.  1 ********** **********    44 Jan 24 11:14 README.md
drwxrwxr-x.  4 ********** **********  4096 Jan 24 11:14 src
drwxrwxr-x. 10 ********** **********  4096 Feb 10 15:22 target
-rw-rw-r--.  1 ********** **********   482 Jan 24 11:14 .yo-rc.json
**********@***********:~/Projects/************$ 


I've seen the file and other related generator files in question in the past, but not now. Am I the only one?

**Comment by gmarziou** [comment]
I'm on Windows too and I can see the entity json files.

**Comment by jimbobwyatt** [comment]
Ignore me...started a brand new project and I see this now. Another project I have is about six months old so I must have had some stale hipster code in there someplace.

**Comment by damogallagher** [comment]
@jdubois - is it possible to specifiy where these json files get generated?
We have a project where half the developers have a version of jhipster that is old and a few new members downloaded it today.

I know we could just tell everyone to upgrade but being able to specify this would be useful

Cheers

**Comment by jdubois** [comment]
No you can't specify it, we need to know where to find it.
Updating JHipster is very easy, and I would recommend everyone uses the same version, or you can get any random error.

**Comment by damogallagher** [comment]
ok thats fine, thanks for getting back to me. I will request everyone performs an upgrade so
