### ISSUE TITLE
Broken build for Angular apps

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#10242]
##### **Overview of the issue**

The Angular application webpack build seems broken in master

```
> store@0.0.1-SNAPSHOT webpack /home/deepu/Documents/jhipster-book/v2/Chapters/3/code/online-store
> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"

Webpack: Starting ...
Starting type checking service...
Webpack: Starting ...

   ✔ Compile modules
   ✔ Build modules
   ✔ Optimize modules
   ✔ Emit files

Webpack: Finished after 7.169 seconds.
> :webpackBuildDev
 ERROR  Failed to compile with 1 errors3:47:04 PM

 error  in ./src/main/webapp/app/app-routing.module.ts

Module parse failed: Unexpected token (16:40)
File was processed with these loaders:
 * ./node_modules/angular2-template-loader/index.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/thread-loader/dist/cjs.js
 * ./node_modules/ts-loader/index.js
 * ./node_modules/angular-router-loader/src/index.js
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
|                 {
|                     path: 'admin',
>                     loadChildren: () => import('./admin/admin.module').then(m => m.StoreAdminModule)
|                 },
|                 ...LAYOUT_ROUTES

 @ ./src/main/webapp/app/app.module.ts 16:0-61 52:12-33
 @ ./src/main/webapp/app/app.main.ts

   605 modules

ERROR in ./src/main/webapp/app/app-routing.module.ts 16:40
Module parse failed: Unexpected token (16:40)
File was processed with these loaders:
 * ./node_modules/angular2-template-loader/index.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/thread-loader/dist/cjs.js
 * ./node_modules/ts-loader/index.js
 * ./node_modules/angular-router-loader/src/index.js
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
|                 {
|                     path: 'admin',
>                     loadChildren: () => import('./admin/admin.module').then(m => m.StoreAdminModule)
|                 },
|                 ...LAYOUT_ROUTES
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! store@0.0.1-SNAPSHOT webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the store@0.0.1-SNAPSHOT webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deepu/.npm/_logs/2019-08-18T13_47_04_545Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! store@0.0.1-SNAPSHOT webpack:build:main: `npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the store@0.0.1-SNAPSHOT webpack:build:main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deepu/.npm/_logs/2019-08-18T13_47_04_555Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! store@0.0.1-SNAPSHOT webpack:build: `npm run cleanup && npm run webpack:build:main`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the store@0.0.1-SNAPSHOT webpack:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deepu/.npm/_logs/2019-08-18T13_47_04_566Z-debug.log

> Task :webpackBuildDev FAILED

FAILURE: Build failed with an exception.

```

##### **Reproduce the error**

Run `./gradlew` on the generated app

##### **JHipster Version(s)**

```
store@0.0.1-SNAPSHOT /home/deepu/Documents/jhipster-book/v2/Chapters/3/code/online-store
└── generator-jhipster@6.2.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.store",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "store",
    "packageName": "com.mycompany.store",
    "packageFolder": "com/mycompany/store",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn"
    ],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-linux64) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-linux64) (build 25.212-b04, mixed mode)

git version 2.21.0

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.0

yarn: 1.17.3

Docker version 19.03.1, build 74b1e89

docker-compose version 1.22.0, build f46880f

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@wmarques @vishal423 guys any idea what broke this? the Travis builds seem fine though, which is strange

**Comment by deepu105** [comment]
Seems related to https://github.com/angular/angular-cli/issues/14566

**Comment by deepu105** [comment]
Following this fixed the issue, since the project had an old package-lock
```
rm package-lock.json
rm -rf node_modules
npm i
```

**Comment by amirdt22** [comment]
Alternative is to use `"webpack": "4.35.3"` in package.json
