### ISSUE TITLE
How to use 'dist' files in production

### ISSUE THREAD

**Issue by sjerman** [jhipster/generator-jhipster#1024]
OK, this may be obvious...

I run a build mvn -Pprod package.

A directory 'dist' is created with the compiled/minified assets. All good.

The question is how do those assets get used at runtime? run the app in 'prod' mode doesn't do it..

Do I have to manually copy stuff around (or work on Maven :)) or am I just missing something?

Steve
PS: apologies if I should be using a different mechanism than this.

**Comment by andidev** [comment]
Run the app in `prod` mode should use the dist folder as far as I know. How do you mean that it does'nt. Give an example of a resource that does not load from the assets folder.

**Comment by sjerman** [comment]
Apologies. I think caching must be getting in way.
