### ISSUE TITLE
Improvements to Documentation in generator-jhipster and jhipster.github.io

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10249]
I have seen some outdated documentation and documentation that could be improved on both generator-jhipster and jhipster.github.io. I just want to know if it's okay to create direct pull requests as and when I see those instead of creating issues and then creating pull requests? I know this is the standard approach in jhipster.github.io but wasn't sure if this is supposed to be done in generator-jhipster project. 

Creating issues for small things and single line changes might just be a waste; or so I thought? 😄 

And sorry to create this question as an issue; didn't know where else I should ask this.

**Comment by vishal423** [comment]
I believe it should be fine

**Comment by jdubois** [comment]
Thanks @SudharakaP : yes, the standard process is to create a ticket, but if it's something simple like wording you can bypass the process, no problem! Feel free to open all the PR you want!

**Comment by SudharakaP** [comment]
@vishal423 , @jdubois : Thanks much for confirming. 😄
