### ISSUE TITLE
getting error while pulling the container image on windows server 2016(1607)

### ISSUE THREAD

**Issue by rashmigowda-doc** [jhipster/generator-jhipster#10251]
docker : failed to register layer: re-exec error: exit status 1: output: 
time="2019-08-21T05:04:39-07:00" level=error msg="hcsshim::ImportLayer - failed 
failed in Win32: There is not enough space on the disk. (0x70)" 
error="hcsshim::ImportLayer - failed failed in Win32: There is not enough space on 
the disk. (0x70)" importFolderPath="C:\\ProgramData\\docker\\tmp\\hcs148061235" path="
\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\f26d97a71f3bc94b4e35241f67da807d9ab3af1
592f1f5d0d88d0d21d7878975"
At line:1 char:1
+ docker pull mcr.microsoft.com/windows/servercore:10.0.14393.693
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (failed to regis...8d0d21d7878975":String 
   ) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
cloning the parent utility VM image failed: BackupWrite \\?\C:\ProgramData\docker\wind
owsfilter\f26d97a71f3bc94b4e35241f67da807d9ab3af1592f1f5d0d88d0d21d7878975\UtilityVM\F
iles\EFI\Microsoft\Boot\es-ES: There is not enough space on the disk.

**Comment by SudharakaP** [comment]
@rashmigowda-doc : This seems to be a disk space related issue. Note that the error says ```There is not enough spare on the disk```. 

Have you checked whether the drive has enough space?

**Comment by rashmigowda-doc** [comment]
Yes , I have 150GB free space on my local hard disk

**Comment by ruddell** [comment]
Are you sure this is related to the JHipster generator project?  If so, please fill out the template and provide steps to reproduce (especially what Docker image you are trying to pull).

I don't recognize that Microsoft Docker image from JHipster.  I've seen similar error messages on Mac though, try to remove and re-create the container

**Comment by rashmigowda-doc** [comment]
> docker : failed to register layer: re-exec error: exit status 1: output:
> time="2019-08-21T05:04:39-07:00" level=error msg="hcsshim::ImportLayer - failed
> failed in Win32: There is not enough space on the disk. (0x70)"
> error="hcsshim::ImportLayer - failed failed in Win32: There is not enough space on
> the disk. (0x70)" importFolderPath="C:\ProgramData\docker\tmp\hcs148061235" path="
> \\?\C:\ProgramData\docker\windowsfilter\f26d97a71f3bc94b4e35241f67da807d9ab3af1
> 592f1f5d0d88d0d21d7878975"
> At line:1 char:1
> 
> * docker pull mcr.microsoft.com/windows/servercore:10.0.14393.693
> * ```
>     + CategoryInfo          : NotSpecified: (failed to regis...8d0d21d7878975":String 
>    ) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>   ```
> 
> cloning the parent utility VM image failed: BackupWrite \?\C:\ProgramData\docker\wind
> owsfilter\f26d97a71f3bc94b4e35241f67da807d9ab3af1592f1f5d0d88d0d21d7878975\UtilityVM\F
> iles\EFI\Microsoft\Boot\es-ES: There is not enough space on the disk.

**Comment by rashmigowda-doc** [comment]
thank you everyone, issue got solved . its bcz  of  quota management which got enabled automatically for my local drive
