### ISSUE TITLE
Update Sonar Analysis Rules According to New Rules

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10258]
##### **Overview of the issue**

Recently SonarQube added some new rules. This effects most projects and right now there's a huge number of new bugs and [vulnerabilities detected](https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application). We probably need to do minor changes to so that we pass the quality gate analysis. 

https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
I can create a pull request for this in the next week or the following; if someone wants to do this sooner feel free to take it. 😄

**Comment by atomfrede** [comment]
I will take care of a few issues now.

**Comment by SudharakaP** [comment]
@atomfrede : Wonderful. Thanks a bunch 😄

**Comment by amatosg** [comment]
regarding Sonar, would it be ok if I fix the bugs shown there?

**Comment by SudharakaP** [comment]
> regarding Sonar, would it be ok if I fix the bugs shown there?

@amaillere : I have no problems; feel free to by all means; I didn't know everyone likes fixing Sonar bugs.... 🤣 🤣 😃  😄

**Comment by amatosg** [comment]
I do, it improves code quality ;)

**Comment by SudharakaP** [comment]
@atomfrede : I suppose after merging #10263 we should get A rating and this could be closed; correct? Just confirming to make sure whether I have to work further on this one. :smile:

**Comment by atomfrede** [comment]
@SudharakaP Yes, I think there are no other issues left.

**Comment by SudharakaP** [comment]
Wonderful. Thanks for the confirmation. :smile:

**Comment by atomfrede** [comment]
I think we can close this as we have only seven issues (which are false positives) left.
