### ISSUE TITLE
Add a schedule to delete audit logs after 30 days

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#10253]
The current implementation of audit log for authentication could result in DB becoming too large, so we should implement a simple @scheduled job to delete the content which are older than 30 days

**Comment by SudharakaP** [comment]
@deepu105 : I am willing to tackle this one. 😄 . I was thinking, should we give the user to choose the schedule duration (30 days or whatever they want) or is it sufficient to keep the 30 days hard-coded for now?

**Comment by pmverma** [comment]
Adding the duration in the property file is better IMO.
The same case is also should be for removing not active users, currently, it is hard-coded to 3 days.

IMO, best is to have an admin screen where admin has the option to change property values at runtime.

**Comment by SudharakaP** [comment]
@deepu105, @pmverma : Wonderful, I'll start working on this with configurable values for removing non-active users and audit log deletion. 😄

**Comment by deepu105** [comment]
No need to choose anything lets just set it to 30days by default. It's trivial to change if needed in code. Maybe we can make it property in the spring boot application.yaml files

**Comment by gmarziou** [comment]
A property would be in the case of microservices and centralized configuration

**Comment by patrickjp93** [comment]
Configurable is best. Many enterprise users have to keep logs for years, and not everyone has off-site duplication or Splunk despite being "enterprise."

**Comment by SudharakaP** [comment]
I've created the pull request. Please feel free to let me know if you see any issues or anything else needs to be added. 😄

**Comment by gmarziou** [comment]
@SudharakaP maybe you should consider squashing your commits into one single for a simpler history when merged.

**Comment by SudharakaP** [comment]
@gmarziou : Thanks, but maybe I am understanding this wrong but isn't it more appropriate to [squash merge](https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits) after the pull request is reviewed?

**Comment by gmarziou** [comment]
Well maybe, I always do it this way and this is how it is recommend in https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-git-commit-guidelines

**Comment by SudharakaP** [comment]
@gmarziou : Okay, I'll do this starting now. But what's the best place to have a discussion about this with everyone? Do you guys have a public channel where all members/devs participate?

**Comment by gmarziou** [comment]
Here is [an example](https://github.com/jhipster/generator-jhipster/pull/10187) where Vishal did it and you can see with several force pushes, github manages it nicely even though some review comments are no longer attached to their initial commit

**Comment by SudharakaP** [comment]
> Here is [an example](https://github.com/jhipster/generator-jhipster/pull/10187) where Vishal did it and you can see it several from several forced pushes, github manages it nicely even though some review comments are no longer attached to their initial commit

Thanks for the example; got it now 😄

**Comment by gmarziou** [comment]
> Do you guys have a public channel where all JH members/devs participate?

Not fully public: https://groups.google.com/forum/#!forum/jhipster-dev and https://gitter.im/jhipster/jhipster-dev-team

Fully public but with very few dev team members: https://gitter.im/jhipster/generator-jhipster

**Comment by SudharakaP** [comment]
Thanks much; the problem with the first one is I cannot post (I think it's only for members); the second one, I can post because there's a bug in gitter; but it's supposedly private; so I don't think it's appropriate. But that's fine I'll post in the public gitter I guess. 😄

**Comment by SudharakaP** [comment]
@gmarziou : I've squashed it as you suggested. Please let me know if you see any further issues. 😄

**Comment by gmarziou** [comment]
You squashed by you kept the commit messages unedited, so it contains a lot of duplicates. I would suggest you amend the commit message.

**Comment by SudharakaP** [comment]
@gmarziou : Sorry about that, I've done another squash with the comment properly updated. Let me know if you see any issues. 👍

**Comment by SudharakaP** [comment]
@gmarziou : Did you delete your review about retention-period? I've added that as well 😄 Let me know if there's any other issues; even if they are nit-picky. 😄

**Comment by gmarziou** [comment]
Looks good to me.  👍

**Comment by SudharakaP** [comment]
@gmarziou : Thanks :+1: 

@DanielFran : If you see any other issue please feel free to let me know; I cannot get the travis or any azure tests pass since the [jhispter-framework pull request](https://github.com/jhipster/jhipster/pull/379) needs to be build first. 

And on that note, I've found time and time again there's some Azure test or Travis tests that fails for invalid reasons. Maybe this is too much to ask, but would it be possible for me to get access to restarting the tests when that happens again so that I don't have to wait until someone restarts ? :stuck_out_tongue_winking_eye:

**Comment by gmarziou** [comment]
You don't have to wait for someone, just close and re-open your PR, it'll restart CI.

**Comment by SudharakaP** [comment]
@gmarziou : Thanks. :+1: Didn't think about that :smile:
