### ISSUE TITLE
Sonar Analysis; Add support for PRs 

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10269]
##### **Overview of the issue**

Currently when one generates a project with JH and chooses to add Sonar analysis, the generated Travis pipeline does not account for the fact that Sonar analysis could be triggered by PRs. In fact investigating this further Sonar analysis on PRs are only limited to their developer edition and above (refer: https://docs.sonarqube.org/latest/analysis/pull-request/). 

So if a user sets up Sonar community edition and does a Travis build using the generated project, a PR (from an external fork) has the potential to fail the whole build, since the Sonar analysis fails.  

##### **Motivation for or Use Case**

The potential for the Travis build to fail on failing the Sonar analysis seems problematic.

##### **Reproduce the error**

1) Generate a project with Sonar

2) Add a PR (from an external fork) to the project and see if it runs the build correctly.

##### **Related issues**

None that I know of; but I've encounter this issue on a project generated by JH; https://github.com/python-sinhala-education-society/OpenLearnr/issues/75 

##### **Suggest a Fix**

I think there's two ways to fix this. 

1) Add an if condition to the ```.travis.yml``` file so that PRs do not try to run Sonar analysis. 

2) Add support for the PR to trigger the analysis locally and add comments to the PR based on the analysis (this is implemented in the referenced issue above). 

I vote for the first option since all user's might not want to add comments for PRs based on Sonar.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
I don't know if this is an issue that's too nitpicky to begin with, if you guys agree and think it's useful, I can work on a solution to this.

**Comment by atomfrede** [comment]
It really depends on the project setup imho, when to trigger a sonar analysis (e.g. develop vs master branch). The analysis of any branch may update the sonar analysis. So I totally agree a PR from an external fork triggers sonar should be prevented.

**Comment by SudharakaP** [comment]
@atomfrede : Wonderful; thanks. 

If there's no other objections to this; I'll do a pr for this soon.

**Comment by SudharakaP** [comment]
Please disregard this pull request; I've made a mistake.

**Comment by SudharakaP** [comment]
@atomfrede : This is done; let me know if you see any issues or anything :smile:

**Comment by cbornet** [comment]
FYI I don't know if something has changed but I do have PR analysis working with the free sonarcloud.
