### ISSUE TITLE
remove code duplication

### ISSUE THREAD

**Issue by ratijas** [jhipster/generator-jhipster#10273]
##### **Overview of the issue**

https://github.com/jhipster/generator-jhipster/blob/d2fe25d60161e6d752f2e482033d265b2cb88a5e/generators/server/files.js#L69-L78

Two identical blocks of code configuring mongodb generator. No impact on generation. Just redundant.

##### **Reproduce the error**

No errors.

##### **Suggest a Fix**

Remove second block.

##### **JHipster Version(s)**

commit d2fe25d60161e6d752f2e482033d265b2cb88a5e

**Comment by SudharakaP** [comment]
@ratijas : Thanks for reporting this. :smile:
