### ISSUE TITLE
Choose between properties and plugin configuration for maven-compiler-plugin

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#10279]
##### **Overview of the feature request**
According to https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html we could configure maven-compiler-plugin by 2 ways:

* By setting properties:
 ```
<properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
```

* By setting the configuration plugin itself:
```
     <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
```

In JHipster we have both solutions implemented. We could remove one of them.

IMHO I would remove the configuration in plugin declaration and only keep properties since they are easy to read and close to our `java.version` property.

/discuss
##### **Motivation for or Use Case**
Simplify the pom.xml.

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by fdelbrayelle** [comment]
I would like to take this one for my first PR on the project just to check all the regular steps to resolve an issue properly. @SudharakaP are you ok to let me this one?

**Comment by SudharakaP** [comment]
Sure thing. :smile: Go ahead by all means.

**Comment by fdelbrayelle** [comment]
Still failing in Azure with the same error even after taking [this commit](https://github.com/jhipster/generator-jhipster/commit/31f592418343ad26ca560de6c2912fb3bcc78d8f) from @DanielFran.

Here is the error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:javadoc (default-cli) on project jhipster-sample-application: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses packages in the unnamed module, but the packages defined in https://docs.oracle.com/en/java/javase/11/docs/api/ are in named modules.
```

It seems it's a bad idea to remove version from maven-compile-plugin, so @avdev4j should we close this issue?

**Comment by avdev4j** [comment]
Closed after a bug was found in javadoc plugin. We need to try with a Java version > 11 according to @DanielFran
