### ISSUE TITLE
Some Videos Missing from JHipster Conf 2

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10270]
I was looking at the [JHipster Conf 2 videos](https://www.youtube.com/playlist?list=PL6IFaLdAcgE3aSgmRyhi6eULdlrwjA5sm) and I found two videos are missing in the YouTube channel;

1) The Reactive Revolution by Josh Long

2) Extending JHipster with Spring Cloud Kubernetes by Mauricio Salatino

Does anyone here have these videos and if so would you be able to share them? 

Thanks much 😄

**Comment by jdubois** [comment]
I think some of the videos failed, but I don't which ones - @pascalgrimaud can you have a look at Ippon?

**Comment by SudharakaP** [comment]
@jdubois : Thanks Julien; hope it isn't much trouble asking for these, if you guys cannot find them, no worries as well 👍

**Comment by avdev4j** [comment]
I've just sent a mail to know what happen with those vids. Maybe one forgets or technical problems during the capture. I keep you informed.

**Comment by avdev4j** [comment]
Unfortunately, these videos are not available because of screen capture failed. 
I'm sorry.

**Comment by SudharakaP** [comment]
@ardev4j :  No worries. Thanks much for looking into this.
