### ISSUE TITLE
Pluralization for entities via configuration file

### ISSUE THREAD

**Issue by silhouette** [jhipster/generator-jhipster#1029]
Currently the pluralization for entities is just <entityName> + "s", which does not work well for words ending in y or s, even in English.

Therefore I suggest to add a setting "pluralEntityName" in the .jhipster.<entityName>.json configuration file, preset with the current logic. This way it can easily be changed after the first generation and the entity can be regenerated. And it stays correct when upgrading jhipster and regenerating the code.

For backward compatibility I'd preset it in the same way if it's null in the configuration file.

**Comment by gmarziou** [comment]
Yes it's probably better to do it this way and maybe even better to ask the user when generating a new entity while proposing the default.

Anyway, I have never been a big fan of using plural for entities, it was first popularized by Ruby on Rails with its Inflector but after all these years it still has problems (even in English) and is confusing for users speaking a language where these basic plural rules do not work. If there was a vote for JHispter about improving it or removing it, I would vote for removing it.

**Comment by silhouette** [comment]
I'd definitely vote against removing it. Something like

    List<Category> category = ...

makes my eyes hurt even more than categorys... ;-)

**Comment by gmarziou** [comment]
Well it could be easily fixed :)

     List<Category> categoryList = ...

And after all that's only code, your users do not see it but they can see wrong plural in URLs.

So, get rid of plural or ask user for confirmation when generating a new entity.

**Comment by Altaflux** [comment]
If there is interest I have a branch that contains a change that allows correct pluralization of entities during Entity generation, it works great just that it is a bit behind current master. If this approach sounds correct I can update this change and send a pull request.

https://github.com/Altaflux/generator-jhipster/commit/a58a53490a350d15956aa25b68d5f7f424fc56e2

**Comment by jdubois** [comment]
Yes, the @Altaflux code is the best way to do it. I've already read it before, and I thought there was some issues between the Java & JavaScript pluralization code?
@Altaflux if you are sure there is no issue, your solution is my favorite, as it's all automatic

**Comment by Altaflux** [comment]
Hi Julien,

Sorry for taking so long to answer back. I have tested quite well the code and there should be no issue as every bit that needs to be pluralized will be pluralized with the same word. 
The pluralizer works with a very well known algorithm that is used in lots of code.

The only way that the pluralizer could fail would be if an entity contains an unpluralizable word which would throw us back the same word back for single and plural. If this ends happening the entity generator would simply check it an append "List" to the plural version of the word.

Example:

pluralizerdEntity = pluralize(entity);

if(pluralizedEntity === entity){
      pluralizedEntity  = entity + "List";

}

I can re factor that piece of code and submit a pull request.

**Comment by jdubois** [comment]
OK @Altaflux it's just me, I thought I remember there was an issue here.

This looks good to me, if you can do a PR it's most welcome!

**Comment by jdubois** [comment]
Hi all, any PR under way for this?

**Comment by Altaflux** [comment]
Hi Jdubois,

Sorry for taking so long, it has been very busy weeks for me at this moment but rest assured there will definitely be a PR upcoming very soon. If it is affecting the metrics you can close the issue and I will reopen it when I send the PR.

**Comment by tagliola** [comment]
Maybe https://github.com/atteo/evo-inflector is an option? I think it's already part of the spring dependencies.

**Comment by Altaflux** [comment]
Spring Data Rest uses Evo-Inflector inside to do the pluralization. The issue here is that pluralization needs to occur during entity generation which is done on Javascript. The code has already been written and it is working, actually the js library I used uses the same algorithm as Evo , I just need to separate it from other changes I have and send the pull request.

**Comment by jdubois** [comment]
I'm closing this as it is inactive -> @Altaflux I'm still very interested by a PR, if you have time
