### ISSUE TITLE
Ability to query unpaged data

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#10290]
##### **Overview of the issue**
we can not query unpaged data even when using param: `?unpaged=true` or `?paged=false`. As per my quick searched on the internet, this should normally work but since we have a custom `PageableParameterBuilderPlugin` that didn't re-implement that it doesn't.

##### **Motivation for or Use Case**
being able to preload a class that is reused through the app and needs to be cached client side.

##### **Reproduce the error**
Try to query the server with: `?unpaged=true` or `?paged=false` the logger says that the pageable is the default one: `page: Page request [number: 0, size 20, sort: UNSORTED]`

##### **Suggest a Fix**
Change the PageableParameterBuilderPlugin to check for these params before starting to convert, also careful `PaginationUtil.generatePaginationHttpHeaders` should maybe not be called when `page == Pageable.unpaged()` to avoid confusing the guys consuming the API.
I can right a PR if needed.

##### **JHipster Version(s)**
6.2.0

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
@yelhouti Good catch. If you could do a PR that would be awesome

**Comment by yelhouti** [comment]
After reading the code https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/web/PageableHandlerMethodArgumentResolver.java it seems that this param is not standard, I could override the Resolver to check first for `unpaged` and if not true (false or null) return unpaged else call parent method. Of course this should be added if everyone thinks is useful.
One important uses case could be our html selects that are broken because of pagination and we could use this to workaround the problem.

**Comment by cbornet** [comment]
PageableParameterBuilderPlugin is only for the OpenAPI spec so it doesn't have any effect on the handling of the query. The pagination is handled by spring and I don't think we should change the behavior. IMO it's dangerous to give the possibility for the client to query unpaged data with large collections.

**Comment by cbornet** [comment]
I don't see any reference in the doc to paged=false or unpaged=true. Could you give links to where it's mentioned ?

**Comment by yelhouti** [comment]
@cbornet you are right, please read my comment before...

**Comment by Blackdread** [comment]
Never heard of paged=false or unpaged=true as well, you have a link for that?
As mentioned by @cbornet you should not have unpaged api when have lot of data.
In your case you can set default Pageable in the resolver, set max as high as you wish then it should solve your problem but no need to change `PaginationUtil.generatePaginationHttpHeaders` or other things

**Comment by yelhouti** [comment]
@Blackdread please also read my comment above, also your solution is not what I'm looking for, I want to have pagination everywhere, except in one case, and in that one data will be cached using a service worker.

**Comment by yelhouti** [comment]
For those interested here is my code:
```
public class CustomPageableHandlerMethodArgumentResolver extends PageableHandlerMethodArgumentResolver {

    private static final String DEFAULT_UNPAGED_PARAMETER = "unpaged";

    private String unpagedParameterName = DEFAULT_UNPAGED_PARAMETER;
....
    @Override
    public Pageable resolveArgument(MethodParameter methodParameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
        String unpagedString = webRequest.getParameter(getParameterNameToUse(unpagedParameterName, methodParameter));
        if ("true".equals(unpagedString)) {
            return Pageable.unpaged();
        }
        return super.resolveArgument(methodParameter, mavContainer, webRequest, binderFactory);
    }
}

```

**Comment by Blackdread** [comment]
you get UnsupportedOperationException if your Pageable instance is wrongly used.
If you really do not want pageable then just remove it from your Controller method :)

**Comment by cbornet** [comment]
I think pagination works as expected.
@yelhouti you can reopen if you think something can be done better.
