### ISSUE TITLE
Keycloak realm name to be same as project name

### ISSUE THREAD

**Issue by caffeinecoders** [jhipster/generator-jhipster#10292]
##### **Overview of the feature request**

Currently when we generate project with Keycloak support, the realm name generate for Keycloak cloak is "jhipster", can it be instead the project/application name

##### **Motivation for or Use Case**

This is something which I have to do it manually everytime, but if this comes as part of code generated from Jhipster, I believe this will be addon for me.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
Hi @caffeinecoders 
I think "jhipster" is used as realm name to match with default keycloak docker config -> https://github.com/jhipster/generator-jhipster/tree/master/generators/server/templates/src/main/docker/config

But I suppose we could change it with the project with the matching pattern. Maybe @mraible could help us to learn more about that.

regards,

**Comment by mraible** [comment]
No one has complained in the past. How many apps are you creating and why is this an issue for you?

**Comment by caffeinecoders** [comment]
I am creating multiple apps, and using single Keycloak instance with multiple realms setup on the same. But main reason is still not this, but to use realm name as project name, makes URL better looking. 

I don't want to hide that I am using jhipster framework, infact, I do give credits to Jhipster framework always in our framework used sections.

**Comment by pmverma** [comment]
Here is the issue I created for the same. https://github.com/jhipster/generator-jhipster/issues/9502 cc: @mraible @avdev4j

**Comment by pmverma** [comment]
But again, this totally depends on the organization/company and use cases.
For eg, you can refer to RedHat website.

For developers,
https://developers.redhat.com/auth/realms/rhd/login-actions/registration?client_id=web&tab_id=CAKv_u-OHec

For customers,
https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/auth?client_id=customer-portal&redirect_uri=https%3A%2F%2Faccess.redhat.com%2Fwebassets%2Favalon%2Fj%2Fincludes%2Fsession%2Fscribe%2F%3FredirectTo%3Dhttps%253A%252F%252Faccess.redhat.com%252F%253FextIdCarryOver%253Dtrue%2526sc_cid%253D701f2000000txokAAA&state=a4f7463e-7e54-4e4b-861a-9da2aa0b5ba4&nonce=52141b18-c7ec-41d7-8da7-f9aab65cd356&response_mode=fragment&response_type=code&scope=openid

I have seen some deployed applications without even changing the realm name.
For eg, https://mcqs.thinkscholar.com/#/

**Comment by pascalgrimaud** [comment]
I don't think it's a good idea, because:
- you generate a gateway, called "gateway" with Keycloak realm "gateway" in config
- you generate a microservice, called "microservice" with Keycloak realm "microservice" in config
- you won't be able to start the microservice because the realm will not match to the one in gateway
- if you have multiple gateway, you'll have the same problem

The simplest way is to keep "jhipster" and if you want to change it the realm, it's pretty easy
So for now, I don't think we should do this change, that's why I'm closing this.
But we can still discuss if you have other idea
