### ISSUE TITLE
Document how to install new javascript, css, sass dependencies with new wiredep configuration 

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1030]
Changes committed in PR #1007 and #969 offers a new work flow for adding new javascript, css and sass dependencies via Bower. This new feature should be documented as some already as mentioned. 
@gmarziu offered to help with this task. Are you still up to it? Otherwise I could take a look at it or maybe work something out together in this issue? How should we work with this?

**Comment by gmarziou** [comment]
I like bower and wiredep a lot, I just used it on my project to add font-awesome. I'd be happy to help on this but I think it'll be asier after my PR get merged into doc.

**Comment by andidev** [comment]
Thanks that would be nice, maybe I'll start doing it if I will get time for it. I'll keep this issue updated with the docs.

**Comment by gmarziou** [comment]
Feel free to do it, I'd be happy to review too.

**Comment by jdubois** [comment]
Yes, please update the doc, you know better than me how it's working!
Do you need help to update the website? It's a Jekyll website, and you can do PR on it, like the generator website.

**Comment by andidev** [comment]
Okey, I'll will give it a try.
