### ISSUE TITLE
Incorrect eslintrc configuration with default react app and no e2e tests

### ISSUE THREAD

**Issue by clement26695** [jhipster/generator-jhipster#10304]
##### **Overview of the issue**

The eslintrc.json file contains these lines, even if no tsconfig.e2e.json is generated. It causes `npm run webpack:build` to fail.

##### **Related issues**

This line https://github.com/vishal423/generator-jhipster/blob/ebebc5da928ce2205a92359d9eef10332739495b/generators/client/templates/react/.eslintrc.json.ejs#L20 was modified in #10232

Ping @vishal423 as he was at the author of PR 10232.

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT /home/cdessoude/Documents/workplace/samples/bugs/test-react
└── generator-jhipster@6.2.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

git version 2.17.1

node: v10.16.1

npm: 6.10.3

yeoman: 3.1.0

yarn: 1.10.1

Docker version 19.03.1, build 74b1e89

docker-compose version 1.23.1, build b02f1306

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
@clement26695. Thanks for reporting. I will check this later today.
