### ISSUE TITLE
Using Keycloak docker image with External Mysql Server

### ISSUE THREAD

**Issue by caffeinecoders** [jhipster/generator-jhipster#10300]
##### **Overview of the feature request**

Using Keycloak running inside docker container, with Google cloud sql instead of mysql running in separate container. 

##### **Motivation for or Use Case**

Migrating my application to cloud, and like to use google cloud sql for storing keycloak data.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Have you tried connecting your keycloak to external database?
For eg, https://github.com/jboss-dockerfiles/keycloak/blob/master/server/README.md#environment-variables

This is not a feature request for JHipster but related to keycloak deployment which you have to do manually if you don't want to use generated db for you.

**Comment by caffeinecoders** [comment]
Actually, I check the configuration and tried providing google cloud sql parameters directly as per documentation but for some reason that didn't work.

**Comment by CodyMTX** [comment]
> Alright, please close this. I am able to fix the issue now. Thanks for your help here.

How were you able to fix this?  I'm having the same issue.
