### ISSUE TITLE
Add feature that allows admin user to switch to any normal user

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1031]
Don't know if this is possible with all three Authentication types supported by JHipster but I could look into it if this feature is wanted.

This could be possible to implement with the [SwitchUserFilter](http://docs.spring.io/spring-security/site/docs/current/apidocs/index.html?org/springframework/security/web/authentication/switchuser/SwitchUserFilter.html)

This change would add a new menu item "Switch User" to the "Account" menu and a new "Swithc User" page looking a lot like the login page but without the password input.

**Comment by jdubois** [comment]
Indeed, this would be hard to test with the three authentication types.
Besides, we would need rules between the authorization roles -> the "ROLE_ADMIN" users should be able to switch to all users, but not the other roles.
For me this goes a bit too far.

**Comment by andidev** [comment]
It is possible to create list of which user roles should't be possible to switch to and then do a check before the `attemptSwitchUser(request)` call in the `SwitchUserFilter` if the switch to user has any of these roles.
This can probably be done by overriding the `attemptSwitchUser(request)`. If the role exists on the user then throw a `AuthenticationException` , if not then call `super.attemptSwitchUser(request)` and let the swichting logic contiune it´s magic.

Should I look into this? or maybe this feature is not that wanted?

**Comment by andidev** [comment]
I'm closing this since the lack of intresst. I will probably dont have time to develop this right now anyway.

**Comment by mtrycz** [comment]
I have succesfully implemented this functionality in our jhipster generated project, both with Spring Sessions (which is easier) and OAuth2 authentication (which is what we'll be using). Didn't have time to check JWT authentication. We have applications with some thousands of accounts sourced from LDAP, and it'll really help us debug any (user-facing) issues.

If there is still any interest in this functionality, I could probably contribute.

**Comment by givemesumthing** [comment]
i realize i am way too late to the party. But have a similar requirement. Is there a possibility that this feature has been implemented int the new jhipster version ?

**Comment by givemesumthing** [comment]
> I have succesfully implemented this functionality in our jhipster generated project, both with Spring Sessions (which is easier) and OAuth2 authentication (which is what we'll be using). Didn't have time to check JWT authentication. We have applications with some thousands of accounts sourced from LDAP, and it'll really help us debug any (user-facing) issues.
> 
> If there is still any interest in this functionality, I could probably contribute.

@mtrycz  Please do contribute.. will it be possible for you to share the implementation that you have done ?

**Comment by amontenegro** [comment]
Am also looking for something like this, if we have admins and users, it is handy to be able to switch from an admin to a regular user account to check errors reported by the user.

Thanks
