### ISSUE TITLE
Parallel Test Execution - Maven Surefire Plugin

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10311]
##### **Overview of the feature request**
Maybe this has been tried before, and I hope this is not a duplicate; if so I apologize in advance. 😄 

I've noticed the checks (for JH generator) take quite a bit of time; especially our Travis Build.  For a typical successful build it usually takes around [45 mins or so](https://travis-ci.org/jhipster/generator-jhipster/builds/578576132). 

Now I do see that in the Travis build we are using parallelized across multiple VMs but I was wondering whether there's any attempt made to [parallelize the Maven Surefire Plugin](https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html) or more generally  maximize parallelization across a single vm as well ? 

If not I can take a look at this and try to do it. 😄 

##### **Motivation for or Use Case**
Obviously, ```faster builds == 😄 😄 😄```

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Travis builds are slow anyway and there has been some discussion to remove in future.
So lets focus on Azure builds as it is much faster.
Certainly, there are some rooms for improvements such as using [Azure Pipeline caching (preview)](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops) to reduce the download time of both ` java dependencies` and `node_modules`.

Last time I tested the sample app on my machine with [JUnit 5 Parallel Execution](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution), unit tests was reduced about `<10 sec` and integration tests about `<40 seconds`.
But the output logs were not sequential I think - need to confirm.

But yes if the build time is reduced much then definitely it is better.

**Comment by SudharakaP** [comment]
@pmverma : Wonderful; thanks much; Even not specifically for Travis, making Surefire parallel might be a worthwhile improvement if the build times are greatly reduced, but the amounts you quote aren't that much of an improvement isn't? I mean making it faster by some seconds doesn't make a difference I was thinking. When you were referring 10 secs and 40 secs were you referring to individual tests or the whole test suites?

About the Travis build removal; if it's not too much trouble, would you be able to point me to where that was discussed? Didn't see that in the issues; maybe in some email thread?

**Comment by pmverma** [comment]
Here are some references:
https://groups.google.com/forum/#!topic/jhipster-dev/-15ABEvSVHc
https://github.com/jhipster/jhipster-vuejs/issues/435#issuecomment-516831626

For the tests I was referring the whole test suites.
BTW, Surefire only runs unit test as per current configuration.
Failsafe plugin runs the integration tests which takes longer time than unit tests.

You can analyze more at https://dev.azure.com/jhipster/generator-jhipster/_build?definitionId=2

**Comment by SudharakaP** [comment]
Wonderful thanks a bunch for all the links and info. 😃

Let me go through the links and stuff you sent and do some more research
into making this faster.

**Comment by PierreBesson** [comment]
Any optimisation in speeding up tests is welcome. However our CI is slow mostly because of e2e tests.

**Comment by SudharakaP** [comment]
I am currently working on this issue and so please keep this open for a while; I was testing the azure cache previews on my fork and I couldn't get significant speed-ups in build times yet; but will revisit it and post my results here. :smile:

**Comment by vishal423** [comment]
I have personally observed parallel execution gain in a multi module complex codebase. Since generated code is pretty simple, I am not sure if it would provide lot of value add. Further, we have moved few builds from `travis ci` to` github ci` and build execution on travis has come down to ~25 mins. Should we close this ticket?

**Comment by SudharakaP** [comment]
@vishval423 : I agree. I was thinking yesterday what to do about this issue too. I think at this point my original intention is met; which is to reduce the build time mainly a result of the slow Travis build. I was experimenting with azure caches too but I think that is not the main point of this issue, and they don't seem to gain a significant reduction. And I also think at this point we don't probably want to complicate matters with parallel builds.

Therefore I think this issue is no longer relavant and should be closed. Feel free to let me know otherwise. :smile:

On another note, I want to thank @deepu105 for adding a bounty on this one. Hope you could reassign the bounty to a more deserving issue. :smile:
