### ISSUE TITLE
Generated gateway UserService.getUserFromAuthentication() error

### ISSUE THREAD

**Issue by JesusTheHun** [jhipster/generator-jhipster#10320]
##### **Overview of the issue**

The generated method `UserService.getUserFromAuthentication()` produce this code : 

```java
        User user = getUser(attributes);
        user.setAuthorities(authToken.getAuthorities().stream()
            .map(GrantedAuthority::getAuthority)
            .map(authority -> {
                Authority auth = new Authority();
                auth.setName(authority);
                return auth;
            })
            .collect(Collectors.toSet()));
```

Unfortunately `User.setAutorities()`expect a `Set<String>`and is given a `Set<Authority>`. Hence compilation fails.

##### **Reproduce the error**

Generate a gateway with jhispter generator with OAuth2, it won't compile.
##### **Suggest a Fix**

The fix is pretty simple, remove the map to Authority domain object : 

```java
        User user = getUser(attributes);
        user.setAuthorities(authToken.getAuthorities().stream()
            .map(GrantedAuthority::getAuthority)
            .collect(Collectors.toSet()));
```

##### **JHipster Version(s)**

Version 6.2.0, I don't know if it is a regression but I assume it is.

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "couchbase",
    "devDatabaseType": "couchbase",
    "prodDatabaseType": "couchbase",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "flatly",
    "clientThemeVariant": "primary",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "blueprints": []
  }
}

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
git version 2.20.1
node: v12.9.1
npm: 6.10.2
yeoman: 3.1.0
Docker version 18.09.3, build 774a1f4
docker-compose version 1.23.2, build unknown
```

**Comment by SudharakaP** [comment]
I've recreated this issue on my end and it seems that this was introduced in https://github.com/jhipster/generator-jhipster/commit/f26c0cf83fa07286d94c263bb1db801779642d9f. 

@cbornet : Seems like the following part is redundant since we take the authority through ```.map(GrantedAuthority::getAuthority)```. Do you agree removing it? 

```        
<%_ if (databaseType !== 'no') { _%>
.map(authority -> {
    Authority auth = new Authority();
    auth.setName(authority);
    return auth;
})
 <%_ } _%>
```

**Comment by SudharakaP** [comment]
I've made a fix to this; please let me know if you see any issues.

**Comment by SudharakaP** [comment]
@pascalgrimaud : I see that you've merged this; but I just wanted to point out that the fix eventually I made is not the fix suggested by the OP in case if you've not noticed it. That piece of code is needed for the correct functionality as some db types expect a set of Authorities. 😄
