### ISSUE TITLE
swagger api doc not sending authorization header under JWT

### ISSUE THREAD

**Issue by amirdt22** [jhipster/generator-jhipster#10330]
##### **Overview of the issue**

In a fresh mvn, jwt, api-first development app, the swagger /admin/docs interface is not sending the authorization header resulting in 401 for all new endpoints.

##### **Motivation for or Use Case**

Confusing for new users who want to use the interface to test out endpoints.

##### **Reproduce the error**

1) Generate an app selecting all defaults (mvn, jwt) and select API-First development
2) Add a path to `api.yml`
3) run the app, log in and visit /admin/docs
4) test your endpoint

Expected:
501 (not implemented)

Actual:
401 unauthorized

Broken/Working `api.yml`: https://stackoverflow.com/questions/57748298/jhipster-swagger-api-doc-not-sending-jwt-authorization-header-resulting-in-401

##### **Related issues**

Possibly: https://github.com/jhipster/generator-jhipster/issues/5501

##### **Suggest a Fix**

[api.yml](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/swagger/api.yml.ejs) is generated with a security key of `jwt` while [swagger-ui/index.hml](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs) is using `bearer`

I think `api.yml` should use the `bearer` key (can submit a PR if you agree).  
At a minimum some documentation (also happy to help if that's the path forward).

##### **JHipster Version(s)**

6.2.0, never tried a previous version

##### **JHipster configuration**

```
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
##### **JHipster Version(s)**

```
temp-2@0.0.0 /Users/amir/bug-jhipster-api-doc
└── generator-jhipster@6.2.0 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "temp2",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "xx",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

git version 2.20.1

node: v10.16.3

npm: 6.9.0

yeoman: 3.1.0

yarn: 1.13.0

Docker version 19.03.1, build 74b1e89

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!
```

##### **Browsers and Operating System**

MacOS, Chrome

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by amirdt22** [comment]
Changing api.yml might not be the right approach as it looks like "jwt" has a special meaning for the swagger-editor and it correctly sends the bearer header for "jwt" but not for "bearer" so perhaps the best options is to update `swagger-ui/index.html.ejs`?

**Comment by cbornet** [comment]
What is the path of the endpoint you added to your api.yml ? I think the header is only added for /api/** endpoints.

**Comment by amirdt22** [comment]
The path is `/api/pet/findByStatus`.  (I might also suggest that the `servers.url` parameter includes `/api` otherwise they won't show up in swagger due to `swagger:default-include-pattern: /api/.*`)

Full api.yml here:
```
# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.1'
info:
  title: 'temp2'
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Development server
  - url: https://localhost:8080/api
    description: Development server with TLS Profile
paths:
  /pet/findByStatus:
    get:
      tags:
        - pet
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        400:
          description: Invalid status value
          content: {}

components:
  schemas:
    Pet:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
```

Changing `securitySchemes.jwt` and `security.jwt` to `securitySchemes.bearer` and `security.bearer` makes it work in `/admin/docs` however the docker-compose swagger-editor then doesn't offer to authorize.

**Comment by amirdt22** [comment]
I think this is the right fix:
```
diff --git a/src/main/webapp/swagger-ui/index.html b/src/main/webapp/swagger-ui/index.html
index 416eace..ee91001 100644
--- a/src/main/webapp/swagger-ui/index.html
+++ b/src/main/webapp/swagger-ui/index.html
@@ -84,7 +84,7 @@
                 function addApiKeyAuthorization() {
                     var authToken = JSON.parse(localStorage.getItem("jhi-authenticationtoken") || sessionStorage.getItem("jhi-authenticationtoken"));
                     var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("Authorization", "Bearer " + authToken, "header");
-                    window.swaggerUi.api.clientAuthorizations.add("bearer", apiKeyAuth);
+                    window.swaggerUi.api.clientAuthorizations.add("jwt", apiKeyAuth);
                 }
```

This works with both the `admin/docs` view as well as the swagger-editor.

**Comment by amirdt22** [comment]
Or in the generator:
```
diff --git a/generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs b/generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs
index 7d81231b6..02c61f8e7 100644
--- a/generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs
+++ b/generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs
@@ -106,7 +106,7 @@
                 <%_ } else if (authenticationType === 'jwt') { _%>
                     var authToken = JSON.parse(localStorage.getItem("<%=jhiPrefixDashed %>-authenticationtoken") || sessionStorage.getItem("<%=jhiPrefixDashed %>-authenticationtoken"));
                     var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("Authorization", "Bearer " + authToken, "header");
-                    window.swaggerUi.api.clientAuthorizations.add("bearer", apiKeyAuth);
+                    window.swaggerUi.api.clientAuthorizations.add("jwt", apiKeyAuth);
                 <%_ } _%>
                 }

diff --git a/generators/client/templates/react/src/main/webapp/swagger-ui/index.html.ejs b/generators/client/templates/react/src/main/webapp/swagger-ui/index.html.ejs
index 5d3ed6f6d..36d160784 100644
--- a/generators/client/templates/react/src/main/webapp/swagger-ui/index.html.ejs
+++ b/generators/client/templates/react/src/main/webapp/swagger-ui/index.html.ejs
@@ -111,7 +111,7 @@
                 <%_ } else if (authenticationType === 'jwt') { _%>
                     var authToken = JSON.parse(localStorage.getItem("jhi-authenticationToken") || sessionStorage.getItem("jhi-authenticationToken"));
                     var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("Authorization", "Bearer " + authToken, "header");
-                    window.swaggerUi.api.clientAuthorizations.add("bearer", apiKeyAuth);
+                    window.swaggerUi.api.clientAuthorizations.add("jwt", apiKeyAuth);
                 <%_ } _%>
                 }
```

**Comment by cbornet** [comment]
The "bearer" clientAuthorizations is used for the OAS generated by Springfox (management and entities endpoint) so I don't think it can be removed.

**Comment by cbornet** [comment]
Ignore my previous comment. Your change does indeed work. Do you want to do the PR ?

**Comment by amirdt22** [comment]
@cbornet sorry just saw this - I can do the PR but not sure how to add tests for this, if you can advise here or once I open it, would appreciate that.

**Comment by cbornet** [comment]
Don't worry. I don't think we have tests for swagger-ui yet so this shall be done in a separate PR.

**Comment by sanjitvimal** [comment]
Jhipster - 7.0.0 Beta,   weblux 
Issue:- Swagger Doc is not loading
Console Error:- 
Refused to apply style from 'http://localhost:8080/swagger-ui/swagger-ui.css' because its MIME type ('application/problem+json') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.html:14 GET http://localhost:8080/swagger-ui/swagger-ui-bundle.js net::ERR_ABORTED 401 (Unauthorized)
index.html:15 GET http://localhost:8080/swagger-ui/swagger-ui-standalone-preset.js net::ERR_ABORTED 401 (Unauthorized)
index.html:16 GET http://localhost:8080/swagger-ui/axios.min.js net::ERR_ABORTED 401 (Unauthorized)
index.html:36 Uncaught ReferenceError: axios is not defined
    at window.onload (index.html:36)
