### ISSUE TITLE
Error message not correct when registering the user with the same email

### ISSUE THREAD

**Issue by davykiala** [jhipster/generator-jhipster#1034]
Hello,
I am testing Jhipster sample 2.0.. The issue can also be  reproduce inany project generated with jhipster 2 generator. 
This is the use case : 
1. I create an user :  http://localhost:8080/#/register
login :  test
email : test@test.fr
password : test2015
passwordConfirm : test2015

2. I create an user :  http://localhost:8080/#/register
login :  test1
email : test@test.fr
password : test2015
passwordConfirm : test2015

I've just changed the login i keep the same email. 
The error message in the register page is "Registration failed! Please try again later" instead of "e-mail address already in use".

DETAILS : 
I've tried to debug, the Spring controller respond with BAD REQUEST status and the text "" . The problem is in the angularJS function : 
            createAccount: function (account, callback) {
                var cb = callback || angular.noop;

                return Register.save(account,
                    function () {
                        return cb(account);
                    },
                    function (err) {
                        this.logout();
                        return cb(err);
                    }.bind(this)).$promise;
            }

In the callback function, the error is "unexpected-token". I don't understand. Why ? I don't know if you could correct. If possible explain me what's happening and i could correct and submit the correction. Thanks

**Comment by jdubois** [comment]
OK, I don't know who modified this page, but it's broken:

- password validation is wrong (test with a 5 character password)
- I got a "SyntaxError: Unexpected token e" after registration

**Comment by jdubois** [comment]
OK, this is because the message that is sent back is not parsed properly - this has something to do with our new v2 code, I remember we already had that issue but @jmirc corrected it and I didn't pay enough attention... This shouldn't be too complex to correct.
