### ISSUE TITLE
Support for GAE Flexible

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10344]
##### **Overview of the feature request**

Currently we support [GAE Standard](https://cloud.google.com/appengine/docs/standard/java11/) and my belief is it's getting fairly stable after we fix #10336. 

I would like to discuss about supporting [GAE Flexible](https://cloud.google.com/appengine/docs/flexible/java/). The problem is Flexible environment by default only runs on Java 8. Although what I would like to try is to define a [custom run-time to support Java 11](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/about-custom-runtimes). This way we could make our GAE generators consistent; both supporting Java 11. 

Do you guys think this is a worthwhile effort? I am not sure how much demand we get for our GAE generator or if it's widely used by our users. Anyhow feel free to let me know your thoughts on this. 😄 

If this is useful; I can work on this one next 😄 

##### **Motivation for or Use Case**

Make the GAE generator support all App Engine environments so that users have a wider choice.

##### **Related issues or PR**

#10196

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by saturnism** [comment]
i don't personally feel this is necessary at this time. App Engine Standard Java 11 can do just about everything now. I would prioritize microservices first :)

**Comment by SudharakaP** [comment]
@saturnism : Agreed. 😄 I wonder whether we should do this at all since doing too many things might make the generators unmanageable. We should probably focus on one stable monolith deployment method (i.e: GAE Standard Environment which we already have) and one stable micro-service deployment (which is underway). How about we close this issue ?

**Comment by saturnism** [comment]
Agreed :) Let's focus on the 2 most important use cases first. Thanks for the help!

**Comment by SudharakaP** [comment]
@saturnism : You are welcome 😄
