### ISSUE TITLE
Generated StringFilter classes can support "excludes" or "does not contain" mechanism

### ISSUE THREAD

**Issue by vraravam** [jhipster/generator-jhipster#10355]
##### **Overview of the feature request**

Currently, the `StringFilter` class has the ability to do a `contains` check. I am proposing an inversion/negation of the same.

##### **Motivation for or Use Case**

In my filters UI, I would like to be able to give the user the option of filtering not only by inclusion rule but also the exclusion rule for strings.

##### **Related issues or PR**

No - searched both open and closed PRs

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
@vraravam, Can you provide more context on the requested change? I assume you are referring to UI improvements, but, I am not clear on the framework implementation under discussion and the class being referenced.

**Comment by vraravam** [comment]
@vishal423 : If you see in the `jhipster-framework.jar`, I see this class: 
```
public class StringFilter extends Filter<String> {

    private static final long serialVersionUID = 1L;

    private String contains;
....
}
```
In the UI/API, I am able to specify filters where I can do a `contains` search for string-based fields. I would like to have the complimentary/negation of the same. Does that give a clearer picture?

**Comment by vraravam** [comment]
Basically, `contains` translates to a `like` query in SQL terms. I am proposing a `doesNotContain` which should inverse the sql condition.

**Comment by vraravam** [comment]
on further thought, maybe we should make it *not* limited to `StringFilter`. I can imagine a scenario where a `LongFilter` can do a `notEqualsTo` or similarly in `RangeFilter` (as an example).

**Comment by vraravam** [comment]
@pascalgrimaud - sure, i can give it a shot - but, which codebase is this in? I couldn't find `StringFilter.java` in the current codebase.

**Comment by murdos** [comment]
@vraravam You'll find it here, in the jhipster server side library: https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/service/filter/StringFilter.java

**Comment by DanielFran** [comment]
@gzsombor Do not forget to claim bug-bounty.

**Comment by gzsombor** [comment]
Thanks, I submitted this: https://opencollective.com/generator-jhipster/expenses/10505
