### ISSUE TITLE
The default version of jhipster-dependencies could not be found in maven central

### ISSUE THREAD

**Issue by niudai** [jhipster/generator-jhipster#10357]
```
        <!-- Dependency versions -->
        <jhipster-dependencies.version>3.0.5-SNAPSHOT</jhipster-dependencies.version>
        <!-- The spring-boot version should match the one managed by
```
The default version generated by jhipster of jhipster-dependencies is 3.0.5-SNAPSHOT, and until now, the newest version is 3.0.4 in maven central:
![image](https://user-images.githubusercontent.com/44165182/64306131-42a28e80-cfc4-11e9-9e5b-4dbf1d9fb818.png)
I don't know why you use an unreleased version, and even in snapshot mode?

**Comment by vishal423** [comment]
I believe you are trying master branch code and at the moment you need to build the jhipster dependencies manually. There is an open [discussion](https://groups.google.com/forum/#!topic/jhipster-dev/nWcocnBJTyo) thread on dev group to improve this experience.
