### ISSUE TITLE
Kubernetes/Istio Enhancements

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#10352]
##### **Overview of the feature request**

- [x] Ability to choose Ingress type / class
- [x] Ability to allow empty domain name for Ingress
- [x] Default Istio to use Istio Ingress w/ reasonable defaults

##### **Motivation for or Use Case**

To allow easy out-of-the-box deployment experience for different types of clusters.

###### Ability to choose Ingress type / class
Kubernetes Ingress comes in different forms, each w/ different restrictions. For example, NGINX allows path matching w/ regex, but GCP ingress does not.

For GCP ingress, services needs to be on `NodePort`.

Add a prompt for the type of ingress user is trying to create.

###### Ability to allow empty domain name for Ingress

It's hard to figure out the domain name on a cloud cluster where the IP address of the Ingress is unknown - because it hasn't been created yet.

###### Default Istio to use Istio Ingress w/ reasonable defaults

When deploying to Istio, there is little to no reason to continue to use standard Kubernetes load balancer or Ingress. Default it to use Istio Ingress. We can also automatically determine the Istio Ingress IP address.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I think everything was done
So I'm closing this
