### ISSUE TITLE
The popup signin react cannot be closed

### ISSUE THREAD

**Issue by manisi** [jhipster/generator-jhipster#10368]
##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by manisi** [comment]
##### **JHipster Version(s)**

```
sport-app-server@0.0.0 /Users/developer/Desktop/sportAppServer
└── generator-jhipster@6.2.0 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "sport.mobile.app",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "sportAppServer",
    "packageName": "sport.mobile.app",
    "packageFolder": "sport/mobile/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mssql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fa"
    ],
    "blueprints": []
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Foo {
  name String
}
dto Foo with mapstruct
paginate Foo with pagination
service Foo with serviceClass
filter Foo

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

git version 2.20.1

node: v10.16.0

npm: 6.9.0

yeoman: 3.1.0

yarn: 1.16.0

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.25.0-rc2, build 661ac20e

**Comment by atomfrede** [comment]
I just reproduced it. The following happens:

- You click on login
- The route changes to `/login`
- The login modal opens
- Close the modal (e.g. via cancel)
- the modal closes and opens again

It was introduced when adding hooks. But I think the behavior before was also not great as the user would stay on `/login` which is basically an empty page.

**Comment by pascalgrimaud** [comment]
cc @qmonmert : maybe you can help ?

**Comment by qmonmert** [comment]
I did a PR to fix that #10382

**Comment by pascalgrimaud** [comment]
thanks @qmonmert !

**Comment by qmonmert** [comment]
@pascalgrimaud tests ok on the PR #10382 ;)

**Comment by pascalgrimaud** [comment]
Thanks @qmonmert 
Closing this as the PR has been merged

**Comment by qmonmert** [comment]
@pascalgrimaud top
