### ISSUE TITLE
RTL lang in react home page is incorrect

### ISSUE THREAD

**Issue by manisi** [jhipster/generator-jhipster#10369]
##### **Overview of the issue**
If you select right-to-left in the desired language settings form, the home screen and menus do not change right to left correctly.

##### **JHipster Version(s)**

```
sport-app-server@0.0.0 /Users/developer/Desktop/sportAppServer
└── generator-jhipster@6.2.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "sport.mobile.app",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "sportAppServer",
    "packageName": "sport.mobile.app",
    "packageFolder": "sport/mobile/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mssql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fa"
    ],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Foo {
  name String
}
dto Foo with mapstruct
paginate Foo with pagination
service Foo with serviceClass
filter Foo

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

git version 2.20.1

node: v10.16.0

npm: 6.9.0

yeoman: 3.1.0

yarn: 1.16.0

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.25.0-rc2, build 661ac20e

**Comment by chrisdns** [comment]
Hi

I tried to reproduce it with your .yo-rc but it seems to work fine, what do you mean by "do not change right to left correctly"

**Comment by manisi** [comment]
> Hi
> 
> I tried to reproduce it with your .yo-rc but it seems to work fine, what do you mean by "do not change right to left correctly"

Hi @chrisdns 
please see this picture
<img width="1429" alt="Screen Shot 2019-09-10 at 17 27 23" src="https://user-images.githubusercontent.com/3120328/64615997-d6bf8c00-d3f0-11e9-808a-da5c1f124fce.png">
page align not set to RTL

**Comment by vishal423** [comment]
@manisi, it seems you have understanding about changes to be done. Can you contribute?

**Comment by manisi** [comment]
Yes 
but how can i start?
Thanks

**Comment by SudharakaP** [comment]
@manisi : We have a pretty detailed guide about how to contribute; https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

Let us know if you have any specific queries. :smile:

**Comment by pascalgrimaud** [comment]
I confirm the issue, when changing the language in account > settings
@manisi : feel free to propose a PR for that, if you know how to fix it

**Comment by Hawkurane** [comment]
Hello, I've found the culprit:
In Angular, when submitting the form, this is the code that is executed:

https://github.com/jhipster/generator-jhipster/blob/7c44af17f2b488b07f1b3b69ae4637b93057308b/generators/client/templates/angular/src/main/webapp/app/account/settings/settings.component.ts.ejs#L67-L86

While in React, when using the form to change settings, this is what happens:
We have an API call:

https://github.com/jhipster/generator-jhipster/blob/7c44af17f2b488b07f1b3b69ae4637b93057308b/generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.reducer.ts.ejs#L75-L89

The Back End part:

```Java
    /**
     * {@code POST  /account} : update the current user information.
     *
     * @param userDTO the current user information.
     * @throws EmailAlreadyUsedException {@code 400 (Bad Request)} if the email is already used.
     * @throws RuntimeException {@code 500 (Internal Server Error)} if the user login wasn't found.
     */
    @PostMapping("/account")
    public void saveAccount(@Valid @RequestBody UserDTO userDTO) {
        String userLogin = SecurityUtils.getCurrentUserLogin().orElseThrow(() -> new AccountResourceException("Current user login not found"));
        Optional<User> existingUser = userRepository.findOneByEmailIgnoreCase(userDTO.getEmail());
        if (existingUser.isPresent() && (!existingUser.get().getLogin().equalsIgnoreCase(userLogin))) {
            throw new EmailAlreadyUsedException();
        }
        Optional<User> user = userRepository.findOneByLogin(userLogin);
        if (!user.isPresent()) {
            throw new AccountResourceException("User could not be found");
        }
        userService.updateUser(userDTO.getFirstName(), userDTO.getLastName(), userDTO.getEmail(),
            userDTO.getLangKey(), userDTO.getImageUrl());
    }
```

By the way, for information, in React's side, this is what is happening when changing the language without going through Account's settings

https://github.com/jhipster/generator-jhipster/blob/7c44af17f2b488b07f1b3b69ae4637b93057308b/generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs#L61-L70

I think these informations can help in making a PR (if there isn't any yet) :)

**Comment by pascalgrimaud** [comment]
@Hawkurane : it looks like you know how to fix this.
Do you have the bandwidth to do it plz ?

**Comment by Hawkurane** [comment]
Sure I can take a look at this tomorrow

**Comment by Hawkurane** [comment]
The Pull Request fixes your specific issue but after changing account settings, opening a private navigtation page and relogging again, the language is still in the wrong order (LTR instead of RTL)
