### ISSUE TITLE
Update Github description and tags to include Vue

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10377]
##### **Overview of the issue**

Minor thing I've noticed; we need to update the Github Repo description and tags to include Vue.
cc: @PierreBesson @pascalgrimaud @jdubois  

![image](https://user-images.githubusercontent.com/12435965/64555646-9d085b80-d2f2-11e9-8ef0-46950b7a63f5.png)

##### **Motivation for or Use Case**

Update Description and tags

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
We do not yet merge the Vue blueprint in main generator repo.

**Comment by SudharakaP** [comment]
@DanielFran : Thanks for the information. I was just wondering given the website is updated with Vue. 😄

**Comment by pascalgrimaud** [comment]
Vue.js is still in blueprint.
We should discuss about including it in main generator...

So for now, we can keep the current description.

**Comment by SudharakaP** [comment]
@pascalgrimaud : Thanks for the info Pascal 😄
