### ISSUE TITLE
XAuth Authentication is broken

### ISSUE THREAD

**Issue by julienboulay** [jhipster/generator-jhipster#1037]
The xauth authentication mechanism is broken, because CSRF protection should be disabled for this authentication type.

It seems to be a merge issue coming from this commit 9b6d784254254719e406e654d32d1cc37bc6f610

After the x-auth-token branch has been merged, we missed the following lines in _SecurityConfiguration.java template.

`<% if (authenticationType == 'xauth') { %>
            .csrf()
            .disable()<% } %>`

CSRF protection may not be required for token based authentication, as soon as CORS is disabled.

**Comment by jdubois** [comment]
Hi, CSRF should not be configured for token based authentication (that would means 2 tokens!).
Yes, it's probably a merge issue, can you have a look?

**Comment by julienboulay** [comment]
Yes, I will make a PR as soon as possible
