### ISSUE TITLE
Add support for Foundation for Apps 

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1039]
I know it's a lot to ask, but it'd be cool to see support for Foundation for Apps: http://foundation.zurb.com/apps/.

I like Bootstrap, but the project I'm working on recently chose FA instead. We're using AngularJS on the front-end and might use Spring Boot for the API. If JHipster had a FA option, it'd be a slam dunk. How hard would it be to add? If given some direction, I'd be happy to look into adding it.

**Comment by jdubois** [comment]
It's certainly do-able, but you would need to update all the front-end files:

- We use the Bootstrap components everywhere, for example the menu, the validation, etc...
- We also use its grid system and its CSS classes everywhere

The good news is that our front-end is well separated from the back-end, so you will not have a lot of conflicts with the other generators.

Still, it looks like a lot of work.

**Comment by gmarziou** [comment]
I would not do in the HTML templates of the generator, they would get unreadable
Maybe it could be done by defining jhipster semantic classes that would act as adapters on top of both frameworks classes, it would be probably doable in SASS but then what about non SASS setups and would make harder to follow framework updates.

**Comment by jdubois** [comment]
No we just can't do our own "semantic CSS classes", we would build a framework on top of other frameworks, that's just too complex.
I'm also very happy to have the classic Bootstrap classes, as anybody who knows Bootstrap can understand them instantly.
That probably means we can't support other frameworks, unless someone re-code the whole HTML layer: that would be a lot of work, and it would be impossible to maintain.

@mraible I'm sorry but at the moment I don't think there's a solution for this
