### ISSUE TITLE
Register and login flow not working

### ISSUE THREAD

**Issue by svennela** [jhipster/generator-jhipster#1040]
Hi,
I am using jhipster 2.0 with OAUTH. Once i click register then again authenticate it is not letting me login.

Below are steps to reproduce
1) http://localhost:8080/#/ (click on new register new account link)
2) http://localhost:8080/#/register (click on new register new authenticate link)
3) http://localhost:8080/#/login (try to login , it will redirect to register again)

Please let me know.

**Comment by jdubois** [comment]
This can be linked to #1034 -> it seems the registration screen is broken, I need to check what happened there

**Comment by jdubois** [comment]
OK, this is just because you did not activate your account -> look at the logs, you have an activation key (that should be sent to you by email in production).
