### ISSUE TITLE
Gradle heroku deploy

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#1041]
Heroku offers a [gradle buildpack](https://github.com/heroku/heroku-buildpack-gradle). It would be great to be able to deploy also gradle projects to heroku. This requires copying the gradle wrapper files to the deploy directory and a little update in the gradle buildfile.

@jdubois feel free to assign it directly to me, as I'm currently experimenting with heroku and gradle

**Comment by jdubois** [comment]
@atomfrede are you working on this? Otherwise let's just close it

**Comment by atomfrede** [comment]
At the moment it's on hold a little bit (I'm working on #508 rigth now as I need it). We can reopen this issue when the PR is finished.
