### ISSUE TITLE
The version of jhipster used by a blueprint should be checked against the version of jhispter used by user

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#10415]
##### **Overview of the issue**

Since a blueprint extends code/class of jhipster subgen(s), it has a dependency on a specific version of JHipster. E.g. let's the blueprint lightly overrides the server subgen (overriding Dockerfile) and depends on jhpster 6.0.0
However if the user has version 6.3.0 installed and launch the generator with the former blueprint, it will end with e.g. client code in v6.3.0 but server code in v6.0.0.

##### **Motivation for or Use Case**

The generated code could be inconsistent since some new feature or fix involve multiple subgen.
Also only one version of jhipster is saved/stored in .yo-rc.json for later use by e.g. the upgrade command. Since this version is wrong the upgrade will only be partial.

##### **Reproduce the error**

See above.

##### **Suggest a Fix**

When we check that blueprint exists, we should probably check the jhipster version compatibility and stop if it doesn't match (if user still want to generates the app, it should launch the generation with the skipCheck option)

##### **JHipster Version(s)**

6.3.0

##### **JHipster configuration**

N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**
N/A

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@murdos : I merged your other PR in generator-jhipster-blueprint. Is there still something to do in the main generator-jhipster ? Or can it be closed ?

**Comment by murdos** [comment]
Yes, there's still the check to implement in the main generator-jhipster. I link the issue in generator-jhipster-blueprint here to illustrate how bad practice it is to use a non fixed version (generated blueprints previously used something like `">=6.1.0"`
