### ISSUE TITLE
Do not use Instant.now for better testability

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#10418]
##### **Overview of the feature request**

As we would like to follow best practices I would suggest not to use `Instant.now()` (e.g. https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/service/UserService.java.ejs#L206).

Instead inject a clock, which can be mocked in tests, such that it is possible to have assertions like

```java
assertThat(maybeUser.orElse(null).getResetDate()).isEqualTo("2019-01-01T00:00:00.00Z");
```
##### **Motivation for or Use Case**

I recently find it quite annoying to test such things and best one could to is to check if it is not null. Also find [this blog post](https://phauer.com/2019/modern-best-practices-testing-java/#don-t-use-instant-now-or-new-date) very inspiring.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Blackdread** [comment]
I usually have a public static method that returns Instant.now() in a util final class.
In tests I provide as well a public static method to force the date returned by the previous method.
But can also inject a service that gives Instant.
Only difference is you do not need to inject when using the static way.

**Comment by atomfrede** [comment]
When using a static method you can't easily mock it (e.g. you need powermock which I would consider bad practice). Therefore using a clock which can properly mocked in tests.

**Comment by Blackdread** [comment]
I know, you have trade-off.
Setter of static method could accept an "interface" so can be easily mocked (which provides the instant).
Many solutions, just depends on your needs, there is not one perfect solution.
DI is not always the best when you cannot have DI in some parts of your code

**Comment by murdos** [comment]
> I usually have a public static method that returns Instant.now() in a util final class.
In tests I provide as well a public static method to force the date returned by the previous method.
But can also inject a service that gives Instant.
>

> Setter of static method could accept an "interface" so can be easily mocked (which provides the instant).

Interesting. Do you have a concrete example or a link to an article illustrating that?

For JHipster I think that injecting a clock would be a good solution.

**Comment by antonioortizpola** [comment]
I do not know if this can help, but I like a lot the testability of the C# library NodaTime.

https://nodatime.org/2.4.x/userguide/testing

> The most obvious dependency is a clock - an implementation of NodaTime.IClock, which simply provides "the current date and time" (as an Instant, given that the concept of "now" isn't inherently bound to any time zone or calendar). The FakeClock can be set to any given instant, advanced manually, or set to advance a given amount each time it's accessed. The production environment should normally inject the singleton SystemClock instance which simply uses DateTime.UtcNow behind the scenes.

**Comment by pdelaby** [comment]
Instead of a static method, we simply use an object implementing java `Supplier` interface : 
```java
@Service
public class InstantNowSupplier implements Supplier<Instant> {

    @Override
    public Instant get() {
        return Instant.now();
    }
}
```

So it can be easely mocked. 

The better version (that you can mock as a lambda,  `new MyClassToTest(()-> Instant.ofEpochMilli(33l));` ) use an Interface and an implementation. More practical, but adds 2 classes.

```java
public interface InstantNowSupplier extends Supplier<Instant> {
}

@Service
public class InstantNowSupplierImpl implements InstantNowSupplier {
    @Override
    public Instant get() {
        return Instant.now();
    }
}

```

**Comment by Vaelyr** [comment]
Only proper solution is to inject Clock and construct date instances passing that in. Any other solution suggested here does not make any sense.

**Comment by vishal423** [comment]
I generally use relative assertions in such scenario:

`assertThat(obs.getStartDate()).isNotNull().isBeforeOrEqualTo(LocalDateTime.now());`

**Comment by atomfrede** [comment]
@jhipster/developers Do we have a decision here? The minimal solution would be to use relative assertations maybe, but I still believe injecting a clock is the "best" solution from a testability perspective.

**Comment by vishal423** [comment]
To understand better, what are we trying to test by injecting a mock `Clock` object? As an example, in my service, I want to ensure that the creation date should always be a current timestamp, then, how injecting a mock will help to verify this assumption/business requirement?

**Comment by antonioortizpola** [comment]
It depends a lot of what are you tring to achieve, for example, we work with different timezones, so, some conversions are needed, it is easy to test known dates, because of summer/winter times, or adjustments.

Other case is processing failures and retries, maybe you need to force a process to fail, and then have the mock to go forward in time so you do not need to wait.

There are many more scenarios where this is helpful, what I am not sure of, is how general this is to be included in the JHipster basecode (I support the integration, but maybe it is just because I have had the same necessity in the past). Also I do not know how could be implemented, I guess the interface looks good to me.

**Comment by atomfrede** [comment]
As we didn't agreed on what to do I would suggest we keep it as is for now, as it works for us.

**Comment by mshima** [comment]
PRs have been done for reproducible builds.
We could use it and inject a date.
https://github.com/jhipster/generator-jhipster/blob/d3cc5f6b8e021422bbab6d8151172ececb0eaf2d/generators/entity-server/files.js#L42
