### ISSUE TITLE
JIB Gradle Configuration error

### ISSUE THREAD

**Issue by vwiencek** [jhipster/generator-jhipster#10422]
##### **Overview of the issue**

It seems that JIB Gradle options have evolved.

We should replace 
`useCurrentTimestamp = true`

with 
 `creationTime = "USE_CURRENT_TIMESTAMP"`

I’ll propose a PR today 

See https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/README.md#extended-usage

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
thanks @vwiencek, I have assigned the issue to you.

**Comment by atomfrede** [comment]
:+1: @vwiencek for reporting that. Can you check if we need to adapt the maven configuration as well?

**Comment by vwiencek** [comment]
I’ve hoped for years that I won’t have to use maven at all but let’s face it .... I need to look at it :-)

**Comment by atomfrede** [comment]
I can look into it if you like. So go ahead with the pr for Gradle and we can discuss all other changes there

**Comment by atomfrede** [comment]
It looks like the same naming in the maven plugin https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage

**Comment by atomfrede** [comment]
Closed via #10426
