### ISSUE TITLE
Use the Oracle drivers from Maven Central

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#10423]
After years waiting, Oracle finally released their drivers on Maven Central:

https://medium.com/@kuassimensah/oracle-jdbc-drivers-on-maven-central-64fcf724d8b

So we need to update our Maven & Gradle builds, our documentation, and also the generator output (where we explain to people they need to use the Oracle proprietary drivers).

This should help a lot people using Oracle!

**Comment by PierreBesson** [comment]
It is still unclear to me what is the license of those drivers and if we would be in legal trouble or not adding them to generated apps or testing them in our CI. It is Oracle after all.

**Comment by DanielFran** [comment]
@jdubois I have implemented the changes but I cannot test it.
Do you have any contact that could validate it is OK?

**Comment by jdubois** [comment]
@DanielFran you mean to get an Oracle license? Unfortunately not... I'm not sure if there are official Docker images for that, but Oracle XE is supposed to be free for dev usage, so you can totally use it for testing.
Then that's a lot of work of you, if it's just getting the same driver, but from another repo, for me it's good.

**Comment by jdubois** [comment]
Oh, and if people who have all the $$$ to buy Oracle databases could help on this, this would be great!

**Comment by DanielFran** [comment]
@jdubois I validated other projects and the impacts is pratically what I implemented... So I will commit it.
Thanks

**Comment by DanielFran** [comment]
@pascalgrimaud Do not forget to merge https://github.com/jhipster/jhipster.github.io/pull/808 for next version.
Thanks
