### ISSUE TITLE
Fast profile should not disable liquibase when using H2 in memory

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1042]
Currently DatabaseConfiguration.liquibase() method does not run database migrations if 'fast' profile is set, it should be smarter and run it if database is H2 in memory.

**Comment by jdubois** [comment]
That was on purpose: if you want to go fast, don't use an embedded database, and don't use Liquibase. Otherwise you won't gain much from the "fast" profile (Swagger and Tomcat/Jetty are the 2 other culprits).

**Comment by gmarziou** [comment]
I agree with you on the purpose however the way it fails is annoying, the appplication starts well and will fail as soon as the database is accessed.
If you don't want to support H2 in memory with fast profile, maybe the application should just fail at init with a clear message.

**Comment by jdubois** [comment]
OK, I need to check what we can do about this

**Comment by gmarziou** [comment]
I can propose a PR if you want.

**Comment by jdubois** [comment]
Yes, please do: I'm changing my mind, it's better to have this working than to have nothing!

**Comment by gmarziou** [comment]
OK, maybe we can make it work and log a WARN saying that this is not optimal?

**Comment by jdubois** [comment]
Yes, good idea!
