### ISSUE TITLE
Add docker plugin to pom so that CI can push images

### ISSUE THREAD

**Issue by jkoorts** [jhipster/generator-jhipster#10438]
##### **Overview of the feature request**

Like with jhipster-registry add a maven plugin eg. dockerfile-maven-plugin so that CI can push images to a registry

##### **Motivation for or Use Case**

For CI

##### **Related issues or PR**

I
dont
know

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
If I am not mistaken we use [jib](https://cloud.google.com/blog/products/gcp/introducing-jib-build-java-docker-images-better) for building the application's docker image. So there is no `DOCKERFILE` anymore generated, therefore the maven docker file plugin has become useless and was removed.

**Comment by jkoorts** [comment]
awesome thanks. Will check that out.
