### ISSUE TITLE
Keycloak user management

### ISSUE THREAD

**Issue by vwiencek** [jhipster/generator-jhipster#10439]
##### **Overview of the feature request**
Hello

I was wondering if we could have a user management page (to edit preferred language or other options) even if we have a keycloak / okta server for authentication ?

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
do you mean by app level preferences?

**Comment by pascalgrimaud** [comment]
Do you mean directly in a JHipster application ? It is duoable, but I don't see any value for that.
You can already do it, using directly Keycloak administration page.

**Comment by vishal423** [comment]
I think the point here is to allow user to update his language or other preferences that are local to the app. Generally in enterprise apps, end users don't have direct access to OIDC administrative pages.

**Comment by vwiencek** [comment]
Ok, just to clarify:

- application based preferences should be stored on the application side -> OK
- what about user related information like the password ? if I login with admin/admin ou user/user I don't see where I can change my password ? What is the best place to update it ?

In keycloak documentation they talk about a "user management console" but I can't find it.

**Comment by pascalgrimaud** [comment]
@vwiencek : go to your keycloak administration console at http://localhost:9080

**Comment by pascalgrimaud** [comment]
I think this ticket can be closed, as the user management is on Keycloak side

**Comment by vwiencek** [comment]
Hello, 

sorry to reopen that ... but in JHipster microservice with keycloak authentication, if I log in with user/user, I don't find any link to change my password ..... maybe it's a keycloak issue ?

thx

**Comment by ruddell** [comment]
Using the default generated Keycloak Docker config, a user can log in to the account management page at http://localhost:9080/auth/realms/jhipster/account/  That page is also where the user can enable two-factor authentication for their account.  You could add that as a link to the navbar

I'm not sure how it works when using Okta

**Comment by vwiencek** [comment]
EXCELLENT
I guess it was missing in the documentation ?
Besides, I think that a link from the application to this page could be great .... I'll try a PR
