### ISSUE TITLE
Gulp + Production mode packages the non minified css and js

### ISSUE THREAD

**Issue by ctranxuan** [jhipster/generator-jhipster#1043]
Hello,
Packaging  with the « prod » profile a project generated with JHipster 2.0.0 with Gulp and Maven, gives a war that embeds both the « dist » folder with minified css and js, and folders with non-minified css and js.

Here are the steps to reproduce:

* create a project with jhipster-generator 2.0.0 (choose the default options except for the js build manager: choose Gulp): yo jhipster
* run: mvn -Pprod package
* unpack the war: see screenshot in attachment.

![screenshot from 2015-01-27 16 14 28](https://cloud.githubusercontent.com/assets/816144/5920893/573979a6-a640-11e4-9a47-eb73d1fc270b.png)

I'm not sure it is the right behavior. What I expected was to get a war that embeds only the « dist ».
Can you confirm it is an issue?

Thanks in advance,

Cédric.

**Comment by jdubois** [comment]
No it's not an issue: the "prod" packaging has both the "prod" files (minified, etc, in the "dist" folder) as well as the normal "dev" files.

2 reasons for this:

- Some people are required to have a unique WAR for all environments
- In case you want to debug your WAR, you can run it in "dev" mode (otherwise it's impossible to debug)

**Comment by skjolber** [comment]
You should reconsider this dev+prod approach, as it is going to add a lot of confusion. Rather go with map files, or introduce more profiles, i.e. 'stage' and so.

**Comment by gmarziou** [comment]
More profiles would be confusing as well I think.
Source maps would be good to have for both JS and SASS files.

**Comment by gmarziou** [comment]
Source maps are tracked in #2282

**Comment by skjolber** [comment]
More profiles will not be confusing; if anything, creating a distribution archive with both prod and dev files is contrary to common sense and confusing; what is the use case for using both in the same deployment? This is borderline a security issue, as dev files can make their way into 3rd party hands unintentionally.

**Comment by deepu105** [comment]
For use case, there is one that I know at least, my client has a policy
that anything we develop needs to be deployed to staging env and get tested
and signed off and same package needs to be moved to prod without any
modification, so in that case this packaging serves me well.

**Comment by gzsombor** [comment]
After we were bitten by problems, which only brakes the minified build, we decided to use the minified build for every environments. And that what I would suggest for everyone else.

**Comment by skjolber** [comment]
@deepu105 seems your use-case means working around your client's policy? I mean, if you are testing on dev files and putting minified into production?

**Comment by gmarziou** [comment]
I agree with @gzsombor's approach combined with source maps

**Comment by skjolber** [comment]
Sounds good @gmarziou

**Comment by deepu105** [comment]
yes, its kind of a workaround i agree. I would like to use same files as
well, not sure if source maps with minified files will let us edit the
js/html and see it rightaway. i can even edit directly in chrome, thats
really great for dev.
i guess we can achieve it with browsersync but uglify is not that fast
either. so i would rather use current setup

On Fri, Dec 11, 2015 at 4:33 AM, Thomas Skjølberg <notifications@github.com>
wrote:

> Sounds good @gmarziou <https://github.com/gmarziou>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1043#issuecomment-163780908>
> .
>



-- 
thank you,
Deepu.k.s
