### ISSUE TITLE
After jHipster enable csrf protection sometimes meet error 403(forbidden)

### ISSUE THREAD

**Issue by wenbin9** [jhipster/generator-jhipster#10432]
Hi jHipster,

     I  enable csrf protection in jhipster-sample-app(v6.12), when operate on page send put, post request often meet error code: 403. **The cause is X-XSRF-TOKEN in  header and cookie is different.**  Refer to attactment. Can you help with it?

![image](https://user-images.githubusercontent.com/43366674/65010504-a58c1200-d942-11e9-8efd-f25ed3bd02ee.png)

X-XSRF-TOKEN in  header and cookie is different:
![image](https://user-images.githubusercontent.com/43366674/65010557-d4a28380-d942-11e9-9f17-081e37e06154.png)

**Comment by wenbin9** [comment]
This is my SecurityConfiguration enable csrf:
![image](https://user-images.githubusercontent.com/43366674/65010644-18958880-d943-11e9-9ea7-24593f496133.png)

**Comment by pascalgrimaud** [comment]
Can you provide all information, required in template, as your configuration, tools etc ?

**Comment by wenbin9** [comment]
@pascalgrimaud    

### 1.Configuration:
Update SecurityConfiguration.java  enable csrf, others use jhipster default Configuration.

private static final String[] CSRF_IGNORE = {"/manifest.webapp", "/api/authenticate", "/api/account"};
    @Override
    public void configure(HttpSecurity http) throws Exception {
        // @formatter:off
        http
            .csrf()
            //.disable()
            .ignoringAntMatchers(CSRF_IGNORE)
            .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
            .and()
            .addFilterBefore(corsFilter, CsrfFilter.class)
            .addFilterBefore(corsFilter, UsernamePasswordAuthenticationFilter.class)
            .exceptionHandling()
            .authenticationEntryPoint(problemSupport)
            .accessDeniedHandler(problemSupport)
        .and()
            .headers()
            .contentSecurityPolicy("default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:")
        .and()
            .referrerPolicy(ReferrerPolicyHeaderWriter.ReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN)
        .and()
            .featurePolicy("geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'self'; payment 'none'")
        .and()
            .frameOptions()
            .deny()
        .and()
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        .and()
            .authorizeRequests()
            .antMatchers("/api/authenticate").permitAll()
            .antMatchers("/api/register").permitAll()
            .antMatchers("/api/activate").permitAll()
            .antMatchers("/api/account/reset-password/init").permitAll()
            .antMatchers("/api/account/reset-password/finish").permitAll()
            .antMatchers("/api/**").authenticated()
            .antMatchers("/management/health").permitAll()
            .antMatchers("/management/info").permitAll()
            .antMatchers("/management/prometheus").permitAll()
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN)
        .and()
            .httpBasic()
        .and()
            .apply(securityConfigurerAdapter());
        // @formatter:on
    }

### 2.Operation
Update  jhipster sample(v6.12) entities eg: update entity 'Bank Account' (may need update many times)

![image](https://user-images.githubusercontent.com/43366674/65016560-2f45da80-d957-11e9-960c-fc7e8cbdd465.png)

### 3.Start Tools
both use cmd start

npm start
mvn

![image](https://user-images.githubusercontent.com/43366674/65016791-ae3b1300-d957-11e9-8b01-44db421ac04d.png)

Seek for your help.Thanks

**Comment by vishal423** [comment]
@wenbin9, this behavior is due to the use of `SessionCreationPolicy.STATELESS`. When you enable CSRF protection, spring creates a temporary transient session and to avoid session fixation generates a new CSRF token. In 5.2.x spring security, you may be allowed to override this behavior.  On the client side, if your client library has read the old CSRF cookie and populated that value in header, then, there are high chances that the header value may not match with actual cookie sent by the browser and this could result into 403. 

I will advise to not mix CSRF with stateless and if you really care about CSRF, then, switch to other authentication strategies like Session/OIDC.

**Comment by wenbin9** [comment]
@vishal423 After removed SessionCreationPolicy.STATELESS. It works, thank you
