### ISSUE TITLE
frontend-tests fail because of missing TESTS-results-jest.xml

### ISSUE THREAD

**Issue by shanon84** [jhipster/generator-jhipster#10445]
##### **Overview of the issue**

TESTS-results-jest.xml is no longer created while running frontend tests.

##### **Motivation for or Use Case**

A new generated application with frontend fails in generated jenkins build pipeline.

##### **Reproduce the error**

generate a new application with frontend. Generate jenkinsfile. Build -> frontend test fails cause of missing TESTS-results-jest.xml file.

##### **Suggest a Fix**

in jest.conf.js:
replace reporters block with this:
`    reporters: [
        'default',
        [ 'jest-junit', { outputDirectory: './target/test-results/', outputName: 'TESTS-results-jest.xml' } ]
    ],`
see also jest-junit page about changed api:
https://www.npmjs.com/package/jest-junit

##### **JHipster Version(s)**

6.3.0

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Thanks @shanon84 for reporting this. We clearly missed that in https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs#L21

**Comment by pascalgrimaud** [comment]
maybe the API for Jest has changed, because I tested it few months ago and it works well

**Comment by guiferrpereira** [comment]
The issue was that jest-junit bumped from 6.4.0 to 8.0.0 and the template wasn't updated accordingly:

https://github.com/jhipster/generator-jhipster/blob/c95c3c7f855a06fff3e3d8edba3e688e8b370e55/generators/client/templates/react/src/test/javascript/jest.conf.js.ejs#L21

https://github.com/jhipster/generator-jhipster/blob/c95c3c7f855a06fff3e3d8edba3e688e8b370e55/generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs#L21

To fix it:

`[ 'jest-junit', { outputDirectory: './target/test-results/', outputName: 'TESTS-results-jest.xml' } ]`

**Comment by vishal423** [comment]
we haven't yet migrated to the jest-junit v8.x. see this:
https://github.com/jhipster/generator-jhipster/blob/c95c3c7f855a06fff3e3d8edba3e688e8b370e55/generators/client/templates/angular/package.json.ejs#L108

**Comment by vishal423** [comment]
even in react, we haven't migrated:
https://github.com/jhipster/generator-jhipster/blob/c95c3c7f855a06fff3e3d8edba3e688e8b370e55/generators/client/templates/react/package.json.ejs#L120

**Comment by shanon84** [comment]
@vishal423 
You are right with the react template.
In my generated aplication with angular:
node_modules\generator-jhipster\generators\client\templates\angular\package.json.ejs
Line 109:     "jest-junit": "8.0.0",

see also version 6.3.0 in github:
https://github.com/jhipster/generator-jhipster/blob/v6.3.0/generators/client/templates/angular/package.json.ejs

**Comment by vishal423** [comment]
My bad. I was looking into diverged branch.

**Comment by vishal423** [comment]
@shanon84, would you be able to raise PR?
