### ISSUE TITLE
Invalid audience problem with Okta Authentication Server

### ISSUE THREAD

**Issue by nebnhoj** [jhipster/generator-jhipster#10449]
##### **Overview of the issue**

Encountered an Issue in Microservice application with a custom Okta Authorization Server.
I started a new Microservice Project with Okta Authorization Server.
I managed to authenticate the /users resource using the default Authorization Server configuration in Okta, but when I add new auth server with same policy and scope in default server I always encountered a problem with Invalid audience : Invalid audience: [http://localhost:8081], even though I already add http://localhost:8081 as audience in authorization server.

Please see the stack trace below: 

**2019-09-19 21:06:53.184  WARN 55988 --- [  XNIO-1 task-1] s.p.p.security.oauth2.AudienceValidator  : Invalid audience: [http://localhost:8081]
2019-09-19 21:06:53.938  WARN 55988 --- [  XNIO-1 task-2] s.p.p.security.oauth2.AudienceValidator  : Invalid audience: [http://localhost:8081]
2019-09-19 21:06:54.334  WARN 55988 --- [  XNIO-1 task-3] s.p.p.security.oauth2.AudienceValidator  : Invalid audience: [http://localhost:8081]**

##### **Motivation for or Use Case**

This is bug for me because the default authorisation server works but the new authorisation always returns Invalid Audience even I add it in Okta

##### **Reproduce the error**

1. Create a Microservice application
2. Create new Okta Authorisation server
3. Create new Native Application in Okta
4. Configure .yaml file for the OIDC configuration with the issuer given in Okta Authorisation server and the client id of the application
5. Try using password grant_type
6. After getting the access token.
7. Try to use it to authenticate the Microservice application that you created before try /api/users

##### **JHipster Version(s)**
**6.3.0**

##### **JHipster configuration**
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": ""
    },
    "jhipsterVersion": "6.3.0",
    "applicationType": "microservice",
    "baseName": "",
    "packageName": "",
    "packageFolder": "",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "cacheProvider": "memcached",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "",
    "embeddableLaunchScript": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  }
}

##### **Browsers and Operating System**
Google Chrome and Mac OS Mojave

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
The possible audience values are hard-coded in `AudienceValidator.java`. You should be able to change it in your code to match what you set in your Okta AS.

https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/security/oauth2/AudienceValidator.java.ejs#L37

**Comment by nebnhoj** [comment]
Thank you very much @mraible.

**Comment by vishal423** [comment]
I am keen to have it open and externalize to a property file.

**Comment by nebnhoj** [comment]
Thank you @vishal423
