### ISSUE TITLE
Add spring no-http (checkstyle) plugin

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#10464]
##### **Overview of the feature request**

We should add the spring no-http plugin to make sure we (and our users) do not use http repositories by accident in maven or gradle builds. If it works well we can extend the use to e.g. production code.

I will take care of it. It worked pretty well for gradle but there were some problems with the maven checkstyle integration.

##### **Motivation for or Use Case**

https://github.com/jhipster/generator-jhipster/security/advisories/GHSA-mc84-xr9p-938r

##### **Related issues or PR**

none.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by duderoot** [comment]
@atomfrede in which step will the _nohttp plugin_ be run? From what I see one needs to execute explicitly the checkstyle plugin manually  .e.g.  mvn checkstyle::check. Do we want to put this step as a prestep before compile in the ci-cd files?

**Comment by atomfrede** [comment]
Not really sure. I would put it into the verify phase maybe.

**Comment by duderoot** [comment]
Isn't the `verify` phase a little too late? I mean at that point the libs are already downloaded. IMHO this should be done at the beginning of the lifecycle e.g. `validate` or `compile`. If we add a dedicated task to the pipeline this should be also at the begin of the pipeline.

**Comment by atomfrede** [comment]
True enough.

**Comment by atomfrede** [comment]
I have added no http checks in the generated ci fles as first step or step after clean
