### ISSUE TITLE
Jhipster version 6.x.x OAuth2MethodSecurityExpressionHandler never register automatic

### ISSUE THREAD

**Issue by ThienPhuc92** [jhipster/generator-jhipster#10469]
##### **Overview of the issue**

Bug appear when generate microservice application
When I use jhipster version 6.x.x OAuth2MethodSecurityExpressionHandler never register automatic. So when i call to a controller with @PreAuthorize("#oauth2.hasScope('web-app')") annotation it always throw Exception "Attempted to call method hasScope(java.lang.String) on null context object".
**But it not has any problem with jhipster version 5.x.x with the same config**

Here is my config with error:

`
@Configuration
@EnableResourceServer
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)
public class SecurityConfiguration extends ResourceServerConfigurerAdapter {
    private final OAuth2Properties oAuth2Properties;

    public SecurityConfiguration(OAuth2Properties oAuth2Properties) {
        this.oAuth2Properties = oAuth2Properties;
    }

    @Override
    public void configure(HttpSecurity http) throws Exception {
        http
            .csrf()
            .disable()
            .headers()
            .frameOptions()
            .disable()
        .and()
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        .and()
            .authorizeRequests()
            .antMatchers("/api/**").authenticated()
            .antMatchers("/management/health").permitAll()
            .antMatchers("/management/info").permitAll()
            .antMatchers("/management/prometheus").permitAll()
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN);
    }

    @Bean
    public TokenStore tokenStore(JwtAccessTokenConverter jwtAccessTokenConverter) {
        return new JwtTokenStore(jwtAccessTokenConverter);
    }

    @Bean
    public JwtAccessTokenConverter jwtAccessTokenConverter(OAuth2SignatureVerifierClient signatureVerifierClient) {
        return new OAuth2JwtAccessTokenConverter(oAuth2Properties, signatureVerifierClient);
    }

    @Bean
	@Qualifier("loadBalancedRestTemplate")
    public RestTemplate loadBalancedRestTemplate(RestTemplateCustomizer customizer) {
        RestTemplate restTemplate = new RestTemplate();
        customizer.customize(restTemplate);
        return restTemplate;
    }

    @Bean
    @Qualifier("vanillaRestTemplate")
    public RestTemplate vanillaRestTemplate() {
        return new RestTemplate();
    }
}
`

This is image when i debug, it load DefaultMethodSecurityExpressionHandler
![image](https://user-images.githubusercontent.com/15994841/65401598-7cacc680-ddf3-11e9-8e61-5f37b87885f9.png)

##### **Reproduce the error**
java.lang.IllegalArgumentException: Failed to evaluate expression '#oauth2.hasScope('web-app')'
	at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:30)
	at org.springframework.security.access.expression.method.ExpressionBasedPreInvocationAdvice.before(ExpressionBasedPreInvocationAdvice.java:59)
	at org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter.vote(PreInvocationAuthorizationAdviceVoter.java:72)
	at org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter.vote(PreInvocationAuthorizationAdviceVoter.java:40)
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:63)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)

Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1011E: Method call: Attempted to call method hasScope(java.lang.String) on null context object
	at org.springframework.expression.spel.ast.MethodReference.throwIfNotNullSafe(MethodReference.java:153)
	at org.springframework.expression.spel.ast.MethodReference.getValueRef(MethodReference.java:82)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:68)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:89)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:114)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:300)
	at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:26)
	... 119 common frames omitted

##### **Suggest a Fix**

I fix it by two step:
1. Add a class 

`
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)
public class MethodSecurityConfig extends GlobalMethodSecurityConfiguration {

    @Override
    protected MethodSecurityExpressionHandler createExpressionHandler() {
        return methodSecurityExpressionHandler();
    }

    @Bean
    public MethodSecurityExpressionHandler methodSecurityExpressionHandler() {
        return new OAuth2MethodSecurityExpressionHandler();
    }
}
`

2. Remove @EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true) on 
SecurityConfiguration class

This is image after i change config, it load OAuth2MethodSecurityExpressionHandler so #oauth2.hasScope will execute without any error
![image](https://user-images.githubusercontent.com/15994841/65401707-02307680-ddf4-11e9-87df-0bf859d940b3.png)

##### **JHipster Version(s)**

Version 6.x.x

**Comment by vishal423** [comment]
@ThienPhuc92, are you using `UAA`?

**Comment by ThienPhuc92** [comment]
Yes, I have an UAA. But this bug happen on microservice application, not on UAA. My token has scope and when i use PreAuthorize with #oauth.hasScope exception appear

**Comment by xetys** [comment]
hey, I found the cause of the issue on my own today. 

This issue is appearing for both, UAA and OIDC...

You can solve this by creating a new configuration class like this:

```java
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)
public class MethodSecurityConfiguration extends GlobalMethodSecurityConfiguration {
    @Override
    protected MethodSecurityExpressionHandler createExpressionHandler() {
        return new OAuth2MethodSecurityExpressionHandler();
    }
}
```

AND remove the `@EnableGlobalMethodSecurity` annotation from the usual `SecurityConfiguration`

I will PR a fix ASAP

**Comment by xetys** [comment]
update: tested with an OAUTH2 based application and confirmed there

**Comment by ThienPhuc92** [comment]
Thank you very much but this happen both UAA and Microservice Application. I think you should test on both of it!

**Comment by pascalgrimaud** [comment]
@xetys : I'm adding the 'bugs' label, as you confirmed the issue and removed the 'need reproduction' label

**Comment by vishal423** [comment]
Latest spring security recommends using Granted authority naming conventions like `SCOPE_<actual-scope>`. Check [docs](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#oauth2resourceserver-jwt-authorization).

**Comment by xetys** [comment]
are you sure about deprecation? I just checked some docs like https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide and https://docs.spring.io/spring-security-oauth2-boot/docs/current-SNAPSHOT/api/deprecated-list.html and can't deprecation warnings...

**Comment by vishal423** [comment]
check this https://github.com/spring-projects/spring-security-oauth/issues/1805

**Comment by xetys** [comment]
I see...so they assume I copy the scope as SCOPE_XXX into authorities? I don't like this, but if that's the only way...

**Comment by vishal423** [comment]
there was an attempt in #10075, however, the developer closed that request.

**Comment by Tcharl** [comment]
Can we close this one after and rolling back the #10845 PR? According to the doc, and at least for Oauth2 (don't know for JWT), there's nothing more to achieve than the original code in order to handle scope but using the right spEl (`hasAuthority("SCOPE_scope")`), so should even work without #10075.

I'm not that confortable to add two deprecated spring-oauth2 library as well as seing deprecated DSLs in jhipster generated code .
