### ISSUE TITLE
add application version number

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1046]
It would be nice to display the version number (from pom.xml) of the running app.
Not sure if it should be visible from all views or maybe just from a single view. And maybe just for admin users.
Any suggestions?

Here is a mock that show the verison number next to the logo
DEV:
![screen shot 2015-01-28 at 01 15 14](https://cloud.githubusercontent.com/assets/571389/5930183/a1b3963c-a68c-11e4-8729-23fda4137bba.png)

PROD:
![screen shot 2015-01-28 at 01 17 49](https://cloud.githubusercontent.com/assets/571389/5930184/a57d00be-a68c-11e4-922b-ec3c5aae01ea.png)

**Comment by gmarziou** [comment]
+1
I also would like to see this version number in the server logs at application start..

**Comment by andidev** [comment]
That would also be nice

**Comment by andidev** [comment]
Changes are made if the feature is wanted.
The changes are dependent on the release of #975. So I'll provide the PR as soon as #975 is merged.
