### ISSUE TITLE
add version number in the server logs at application start

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1048]
@gmarziou mentioned this in #1046. Creating a separate issue for this.

The best way to do this according to [StackOverflow](http://stackoverflow.com/questions/3697449/retrieve-version-from-maven-pom-xml-in-code) is to inject the version number in a property file via resource filtering. And then load this property file and print the version number from `Application.java`.

**Comment by andidev** [comment]
Sorry I incorrectly referenced the wrong issue in the #1050 PR. PR should have been closed #1046 (which is correctly closed). Could you reopen this?

**Comment by jdubois** [comment]
It's open again!

**Comment by andidev** [comment]
Is there a reason why the  logs are not `static` in the java classes?

I have to access the log in a static method and I'm not sure if I should call `LoggerFactory.getLogger(Application.class)` in the static method or make the logger in the class `static` and use that insead.

Anyone with some knowledge on this?

**Comment by andidev** [comment]
This is now implemented on Maven builds, though I am having trouble getting the filtering of the appliation.yml to work with gradle.

Who is responsible/expert on gradle that maybe could help me out?

**Comment by gmarziou** [comment]
Personally, I almost never use static loggers in my classes because otherwise you'll get different logger names (by default based on class name) for parent and child classes for statements logged by a single instance. So for me, the logger should have been intialized like this `protected final Logger log = LoggerFactory.getLogger(getClass());` so that classes extending Application could log the same way.

**Comment by jdubois** [comment]
- The logger should not be static without a good reason: so usually they are not static, but for your specific use-case (in a Main class), it could be static.
- For Gradle issues, we have our own Gradle expert, and official maintener, @atomfrede

**Comment by andidev** [comment]
@gmarziou and @dubois, Aha thanks for the explanation, now it makes sense. So since Application.java will most likely ever be extended I can make the loggger static. Done!

I'm getting closer. One last piece of the puzzle left to solve. It would be good if @atomfrede could code review the gradle part when I'm done or help me with this last part if I fail to solve it.

**Comment by andidev** [comment]
So I give up, can't seem to solve it. Could you take a look at it @atomfrede ?

The derives from that I have configured gradle to filter the `application.yml` file so that 
```
application:
    name: @rootProject.name@
    version: @version@
```

becomes

```
application:
    name: jhipster
    version: 0.1-SNAPSHOT
```

when the resource is copied to  in the processResources task.

This works perfectly when packaging with `gradle build` and then running the app with `java -jar build/libs/jhipster-0.1-SNAPSHOT.war`.

However it does not work if running the app with `gradle bootRun` since then the resources are loaded from the original location and not the ones that where filtered in the processResources task.

This is the exception thrown:
```
Exception in thread "main" while scanning for the next token
found character @ '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 17, column 11:
        name: @rootProject.name@
              ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:132)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:84)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:104)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:502)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:152)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:137)
	at org.springframework.boot.env.YamlPropertySourceLoader$Processor.process(YamlPropertySourceLoader.java:78)
	at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
	at com.mycompany.myapp.Application.loadApplicationYml(Application.java:94)
	at com.mycompany.myapp.Application.main(Application.java:51)
:bootRun FAILED
```

which confirms the problem.

The problem is [explained in Spring Boot Maven Plugin](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/maven-plugin/usage.html#Running_the_application).

So the solution is to disable that spring boot adds the resources from it's original location by setting some configuration `addResources` to false. However I find documentation on how to do this for the Spring Boot Gradle Plugin. The maven plugin seems to be reading the system property `run.addResources` but I cant seem to trigger it with the Gradle Plugin. I have tried running `gradle bootRun -Drun.addResource=false` but it does not work.

Any ideas on how to solve this mystery?

**Comment by atomfrede** [comment]
Not right away, but I can have a look at it. Can you setup a sample project with your current state I can work with?

**Comment by andidev** [comment]
@atomfrede, Thanks, but it looks like it's probably not needed. 
According to @philweb's answer in issue [#749](https://github.com/spring-projects/spring-boot/issues/749) this is not supported by the Spring Boot Gradle Plugin.
A feature request issue spring-projects/spring-boot#2431 is created and is a direct blocker for this case. I'll finish this case once this issue is solved in Spring Boot Gradle Plugin.

**Comment by atomfrede** [comment]
@andidev Yes, I found that issue too, and was jsut about to open an issue at spring boot ;) Nevertheless I think I have a little workaround in mind using the gretty plugin, but an official solution would be nice.

**Comment by andidev** [comment]
Agree, official solution would be best. Since the case is as non critical as it can be it is probably best to wait for the Spring Boot team to release a fix for this issue.

**Comment by dubois** [comment]
Hey, you guys are tagging @dubois and you have the wrong guy!

p☎

**Comment by andidev** [comment]
Hehe sorry my bad

**Comment by jdubois** [comment]
OK, we'll wait until we have an official solution, doesn't seem like a big deal to me!

**Comment by andidev** [comment]
Spring Boot 1.2.2 is released with the fix needed to release this. I'll try to rebase to current master and do a PR.
