### ISSUE TITLE
Jhipster Integration with Google Firebase for Authentication

### ISSUE THREAD

**Issue by caffeinecoders** [jhipster/generator-jhipster#10480]
##### **Overview of the feature request**

Do we have any plan for Jhipster integraiton with Google Firebase? I understand that Jhipster support OIDC and hence provide integration with all Auth servers which support OIDC. But at the same time, I do believe that Firebase is one auth server, which is getting very famous and provide so many features at such a low price. 
Hence this request, to consider this integration.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
No, we do not have any plans to integrate Google Firebase. However, you're welcome to develop it and contribute it to the project. It might be easiest to do this as a module or blueprint. I recommend starting the process by developing a prototype, then incorporating the necessary changes into a module or blueprint. If it becomes popular (and is well-maintained), we can roll it into the main generator.
