### ISSUE TITLE
H2 Console on microservice not working

### ISSUE THREAD

**Issue by vwiencek** [jhipster/generator-jhipster#10481]
Dear all,

When I create a microservice with the following model.jdl

```
application {
   config {
     baseName certification,
     applicationType microservice,
     packageName com.mla.reglab.certification,
     serviceDiscoveryType eureka,
     authenticationType oauth2,
     clientPackageManager npm,
     jhiPrefix certification,
     devDatabaseType h2Disk,
     prodDatabaseType postgresql,
     enableSwaggerCodegen true,
     enableHibernateCache true,
     cacheProvider hazelcast,
     nativeLanguage en,
     languages [en, fr, es],
     buildTool gradle,
     serverPort 8084,
     skipUserManagement true
   }
   entities EntityA
}

entity EntityA {
  name String required
}


dto all with mapstruct
service all with serviceClass
paginate all with pagination
```

And when I try to access http://localhost:8084/h2-console I get the H2 connection screen but when I try to connect, et get this error `No suitable driver found for 08001/0`
##### **JHipster Version(s)**

Version 6.3.1

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Could you paste which values you set in H2 connection screen?

**Comment by vwiencek** [comment]
<img width="453" alt="Screenshot 2019-09-24 at 12 26 58" src="https://user-images.githubusercontent.com/1091392/65504114-9c60ef00-dec6-11e9-8099-a41510677222.png">

**Comment by vwiencek** [comment]
<img width="611" alt="Screenshot 2019-09-24 at 12 27 21" src="https://user-images.githubusercontent.com/1091392/65504143-aaaf0b00-dec6-11e9-89e9-ddf4e9f9413e.png">

**Comment by vwiencek** [comment]
I kept default values
"Test Connection" works

**Comment by SudharakaP** [comment]
This is due to our security policy recently being changed to deny all `X-Frame-Options` headers. I've relaxed this to allow same origin requests; which I think is okay. Correct me if I am wrong. :smile:

**Comment by vwiencek** [comment]
Could you please tell me what to change ? Thx

**Comment by clement26695** [comment]
You can check the changes made in @SudharakaP PR (https://github.com/jhipster/generator-jhipster/pull/10498/files#diff-5896bcb3f7efe22444d57880b0069cf3R240). 

Basically, you would only have to replace `.frameOptions().deny()` by `.frameOptions().sameOrigin()` in your SecurityConfiguration.java file

**Comment by SudharakaP** [comment]
@clement26695 : Thanks 👍 

@vwiencek : Just for the record, when creating future issues please include some more information such as filling up the 'JHipster configuration' section with your `.yo-rc.json` configuration at the very least. This way it would be easier for us to recreate your scenario. 😄

**Comment by ahd3r** [comment]
I faced the same exception but on the H2 database and it appeared because of my initial request object manipulation in `doFilter`. I did it cuz I needed to read the Body of the request multiple times, but for some reason, it broke the connection to the H2 console. So this is what I did, that fixed this issue for me:

```
@Override
public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
    if (((HttpServletRequest) request).getRequestURI().startsWith("/h2-console/")) {
        chain.doFilter(request, response);
        return;
    }
    RepeatableHttpServletRequestWrapper wrappedRequest = new RepeatableHttpServletRequestWrapper((HttpServletRequest) request);
    chain.doFilter(wrappedRequest, response);
}
```

**Comment by TiagoBohnenberger** [comment]
> I faced the same exception but on the H2 database and it appeared because of my initial request object manipulation in `doFilter`. I did it cuz I needed to read the Body of the request multiple times, but for some reason, it broke the connection to the H2 console. So this is what I did, that fixed this issue for me:
> 
> ```
> @Override
> public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
>     if (((HttpServletRequest) request).getRequestURI().startsWith("/h2-console/")) {
>         chain.doFilter(request, response);
>         return;
>     }
>     RepeatableHttpServletRequestWrapper wrappedRequest = new RepeatableHttpServletRequestWrapper((HttpServletRequest) request);
>     chain.doFilter(wrappedRequest, response);
> }
> ```

That worked for me. Thanks!
