### ISSUE TITLE
Add all options to skip some prompts of app generator questions

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster#10482]
**Overview of the feature request**
Hi all wonderful community,
I suggest to support option to skip the questions that we can't override.
For some questions jhipster already provides it (skip-server, skip-client and so on),
but for the **i18n** there is the parameter without cli settings [this.skipI18n](https://github.com/jhipster/generator-jhipster/search?q=this.skipI18n&unscoped_q=this.skipI18n).

So we have to provide skipping for:
* i18n
* additional [test framework](https://github.com/jhipster/generator-jhipster/blob/b1925bbe9283d4502d749d829fa1793afb1605e8/generators/app/prompts.js#L123) 
* Additional [modules to install](https://github.com/jhipster/generator-jhipster/blob/b1925bbe9283d4502d749d829fa1793afb1605e8/generators/app/prompts.js#L153)

After in every blueprint the developer can add for default that options.

**Motivation for or Use Case**
Refers to [this comment](https://github.com/jhipster/generator-jhipster/issues/10467#issuecomment-534034014) and #9692 issue.
As is difficult to override or extend the app generator class, is useful to not display the app generator questions that we don't want into the blueprint. Then it's easy to custom the other rest of prompts in every subgenerator to have the full control of blueprint.

**Related issues or PR**
The [nodejs blueprint issue](https://github.com/jhipster/generator-jhipster-nodejs/issues/44) requires it for the question about _additional test framework_ .

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Kerruba** [comment]
I think also supporting skipping questions by providing a default answer would be fantastic for the #9692 issue. As a blueprint developer for example I would like to make the assumption in the blueprint that the app is always a microservice

**Comment by amanganiello90** [comment]
> 
> 
> I think also supporting skipping questions by providing a default answer would be fantastic for the #9692 issue. As a blueprint developer for example I would like to make the assumption in the blueprint that the app is always a microservice

Hi @Kerruba,
you already set a your value in the blueprint generator..
You can change any response from the server generator initialization phase (in your case for the application type). For example see this:  https://github.com/jhipster/generator-jhipster-nodejs/blob/9787a64234303f95b18385cc4f7c3a61e8ef6ca1/generators/server/index.js#L99

**Comment by amanganiello90** [comment]
Hi @Kerruba,
For your happiness in my PR I have also add a **--skip-app-type** option. 
The default value, set by jhipster, is **monolith*, but you can change it in your server initialization phase.
Thanks

**Comment by pascalgrimaud** [comment]
I'm closing this as https://github.com/jhipster/generator-jhipster/pull/10752 has been merged and it should help
