### ISSUE TITLE
No matching version found for @typescript-eslint/typescript-estree@2.0.0

### ISSUE THREAD

**Issue by deltatree** [jhipster/generator-jhipster#10490]
##### **Overview of the issue**

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @typescript-eslint/typescript-estree@2.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@typescript-eslint/experimental-utils'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/linux/.npm/_logs/2019-09-25T06_22_35_848Z-debug.log
Application commit to Git failed from /home/linux/user42-ui. Try to commit manually.

##### **Motivation for or Use Case**

BUG

##### **Reproduce the error**

Create new project

##### **Related issues**

Nothing found

##### **JHipster Version(s)**

6.3.1

##### **JHipster configuration**

INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
user-42@0.0.1-SNAPSHOT /home/linux/user42-ui
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.egonXXX.bigbaing.user42",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "monolith",
    "baseName": "user42",
    "packageName": "de.egonXXX.bigbaing.user42",
    "packageFolder": "de/egonXXX/bigbaing/user42",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "flatly",
    "clientThemeVariant": "primary",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de"
    ],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

git version 2.17.1

node: v12.10.0

npm: 6.10.3

yeoman: 3.1.0

yarn: 1.17.3

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

**Comment by vishal423** [comment]
I am not sure if this is an issue on JHipster side. You can check this package @ https://www.npmjs.com/package/@typescript-eslint/typescript-estree/v/2.0.0

**Comment by pascalgrimaud** [comment]
Can you try with Node LTS 10.16.3 instead of latest plz ?

**Comment by pascalgrimaud** [comment]
No news, so I'm closing this
