### ISSUE TITLE
Improve developer experience in VSC if open src/main/webapp/app

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#10502]
##### **Motivation for or Use Case**

I have seen front end developer complaining about bad experience in Visual Studio Code:
* front end developer wants to see as few files as possible in the IDE
* front end developer opens only folder `src/main/webapp/app`
* Visual Studio Code is unable to resolve path `app` in Typescript imports, because `tsconfig.json` with this information is not found (this file is in the root folder of the generated app) and these imports are red and developer can't see these imported classes content and can't jump with one click into these imported classes

### Possible solution 1

Add file `src/main/webapp/app/tsconfig.json` with the following content:
```
{
    "extends": "../../../../tsconfig.json"
}
```
And for tests add file `src/test/javascript/spec/tsconfig.json` with the same content:
```
{
    "extends": "../../../../tsconfig.json"
}
```
After that Visual Studio Code resolves path `app` if opening only folder `src/main/webapp/app` or `src/test/javascript/spec`.

### Possible solution 2

Add tip to documentation which includes:

1. description of the solution 1

2. additional solution: scripts for removing import alias if someone prefers that; removing import alias is basically bad practice (the code becomes less readable) and JHipster can't generate such code by default:

* add node script `remove-import-alias.js` to app root folder which replaces import aliases with relative paths:
```
const fs = require('fs');

removeImportAlias = function(dir, level, additionalPath) {
  fs.readdirSync(dir).forEach(function(file) {
    if (fs.statSync(dir + file).isDirectory()) {
      removeImportAlias(dir + file + '/', level + 1, additionalPath);
    } else if (file.endsWith('.ts')) {
      fs.readFile(dir + file, 'utf8', function (err, content) {
        if (err) {
          console.log(err);
        } else {
          let path = '../'.repeat(level);
          if (additionalPath) {
            path += additionalPath;
          }
          if (!path) {
            path = './';
          }
          const newContent = content.replace(/import \{ (.*) \} from 'app\/(.*)';/g, `import { $1 } from '${path}$2';`);
          fs.writeFile(dir + file, newContent, 'utf8', function (err) {
            if (err) {
              console.log(err);
            }
          });
        }
      });
    }
  });
};

removeImportAlias(`./src/main/webapp/app/`, 0);
removeImportAlias(`./src/test/javascript/spec/`, 0, '../../../main/webapp/app/');
```
* add `remove-import-alias.js` to `.eslintignore`
* run added script: `node remove-import-alias.js`
* delete `app/*` from file `tsconfig.json` from section `compilerOptions.paths`

##### **JHipster Version(s)**

```
app@0.0.1-SNAPSHOT C:\projects\teest\jhipster-lang-service5
`-- generator-jhipster@6.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "monolith",
    "baseName": "app",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "de"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.11.3

yeoman: 2.0.6

yarn: 1.17.3

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.24.1, build 4667896b

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
I think this is not just limited to absolute paths like add packages, run npm/yarn scripts from within IDE

**Comment by pascalgrimaud** [comment]
As I think it is something specific, it should go to a tips.

Anyway, I find it strange, that the front developer prefered to go a `src/main/webapp/app` for opening their app, then, they need to go to the root folder to launch `npm start`, as `src/main/webapp/app` doesn't contain `package.json`
