### ISSUE TITLE
Add Documentation of openapi-client Sub-generator 

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10507]
##### **Overview of the issue**

I couldn't find any documentation about the `openapi-client` sub-generator within [https://www.jhipster.tech/](https://www.jhipster.tech/). Is documentation about this sub-generator available anywhere? If not, let me know I can add some? 😄 

cc: @ecostanzi 

##### **Motivation for or Use Case**

Complete documentation makes life easier 😄  

##### **Related issues**

Reference Issue: https://github.com/jhipster/generator-jhipster/issues/9548

**Comment by ecostanzi** [comment]
Sure this is definitely something that needs to be done. I just opened issue https://github.com/jhipster/generator-jhipster/issues/10510 to discuss about some improvements. They will affect how the sub-module works and therefore the documentation related to it.

**Comment by SudharakaP** [comment]
@ecostanzi : Would you like to take this? Since you build this generator, maybe it's more appropriate for you to add the documentation. :smile:

**Comment by SudharakaP** [comment]
@ecostanzi : I've went ahead and created a pull request to add a small blob about the openapi client sub-generator. If you have any suggestions or alterations, feel free to let me know. :smile:
