### ISSUE TITLE
[Feature Request] read-only/maintenance mode

### ISSUE THREAD

**Issue by amrnablus** [jhipster/generator-jhipster#10506]
##### **Overview of the feature request**

Basically, the methods on the web.rest that do not write any data get annotate (jhipster already does that with @Transational(readonly=true).
when the readonly flag is activated, any method not annotated as read-only will throw an Exception

##### **Motivation for or Use Case**

1. In case there is some maintenance going on and the user would like to keep the API running in a read-only mode they can do so easily, beats taking the whole thing down.
2. it can be expanded to users, where particular users can be flagged as read-only and the same logic can be used to prevent unwanted writes from particular users.

I had to sort of code a read only version of a generated app and felt the logic can be integrated into the genrator itself. The idea seems useful
##### **Related issues or PR**

I would love to work on the feature myself if it gets approved.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Vaelyr** [comment]
@Transational(readonly=true) has very different purpose and is not meant for such use case. Also this cannot be changed at runtime. What you are proposing is completely different and special use case which does not seem to fit here at all and should be developed separately.

**Comment by amrnablus** [comment]
True, my point was that @Transational(readonly=true) gets generated by jhipster, thus, jhipster "knows" when it's generating a readonly method and can annotate it on the controller level, beyond that @Transational(readonly=true) has no relation to this.

**Comment by amrnablus** [comment]
The implementation i have in mind roughly looks like this:
```
Class XyzController {
    @PostMapping("/xyz")
    .....

    @GetMapping("/xyz")
    @ReadOnly(true)
    public ... 
}


```
And there would be an aspect similar to the logging aspect that checks weather or not the system is in a readonly mode and returns an exception accordingly.

Another option we could do it block any request that's not GET, in which case the login needs to be hanlded separately.

**Comment by gmarziou** [comment]
I think that most users don't expose their entities in REST layer, so I'm not sure this annotation would be often used.
Why not simply using `@Immutable`on the entity?

**Comment by amrnablus** [comment]
@gmarziou the point of this feature request is to render the _API_ readonly not a particular entity.
think of it this way, your master database is down and you want to perform some maintenance, normally you'd need to take the whole API down (or leave it up have tons of exception and more and more write requests to the master), it would be beneficial if we can mark the API as read-only mode, in which case any request that causes a database write will be rejected while the rest of the system functions normally in a read-only state.
As for `@Immutable` I feel it conveys that this marked entity is perpetually immutable which isn't the case here, but I'm down to use it otherwise.

**Comment by pascalgrimaud** [comment]
Not sure I understand well your solution, but just to let you know it has been already asked with a good solution.

You can have a look at:
- https://github.com/jhipster/generator-jhipster/issues/8800
- https://github.com/jhipster/generator-jhipster/issues/9562
- https://github.com/jhipster/jhipster-core/issues/318
- https://github.com/jhipster/jhipster-core/pull/370

Some work has been done but not completed.
Cc @murdos as he took the lead on this

**Comment by pascalgrimaud** [comment]
@amrnablus : can you read these tickets and tell us if it's what you have in mind ?

**Comment by murdos** [comment]
From what I understood, @amrnablus want to be able to switch all REST API of an application in read-only/maintenance mode for a period of time, either at runtime or with a configuration key.

IMO this feature is too specific to be included in JHipster.

**Comment by amrnablus** [comment]
Yep, that's exactly what I mean. Although I don't think it's very specific, that's just good design

**Comment by pascalgrimaud** [comment]
So it confirms what @murdos said.
It's really too specific. For doing that, you can have an Apache Httpd server, or NGinx. It's far easier.

From an architecture point of view, if your application is down, you can't call API, so readonly mode is useless. 
If your database is down, you have a big problem. Resolving this by putting API in read only mode, is only possible by using the cache system. Then, it's too specific to be included in JHipster

**Comment by amrnablus** [comment]
There are quite a few caess where your database is not just down (i mean in this case yes you're pretty much screwed and there is nothing jhipster can do). 
You could be recieving too many writes and it's slowing everything down, you cloud put your API in a readonly mode until you spin a different server.

As for http caching, i'm guessing you mean something like varnish? That works but the state of the cache is not perdictable and it highly depends on the flow of requests, the API itself is the source of truth.

I don't see any particular drawbacks for implementing this, especially if we make it optional.

**Comment by mraible** [comment]
I would recommend using your hosting provider to give you this functionality. For example, Heroku has a "maintenance mode" feature. https://devcenter.heroku.com/articles/maintenance-mode

**Comment by gmarziou** [comment]
> You could be receiving too many writes and it's slowing everything down, you cloud put your API in a readonly mode until you spin a different server.

As Pascal said, it's easy and more effective to do it from a reverse proxy like nginx configured to limit all HTTP methods except GET.

**Comment by pascalgrimaud** [comment]
I think we can close this, as it is something we won't do
