### ISSUE TITLE
Move back to angular cli

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#10539]
##### **Overview of the feature request**

I would like to use angular cli in conjunction with jhipster,

##### **Motivation for or Use Case**

Angular CLI has well matured since it's start, and allows to easily enable features like Ivy...,
I suggest we switch back to using it.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/9817 discussion started here, but as suggest by @wmarques I created a new Issue.

@deepu105  can this be addd to Hacktoberfest please ? Thanks

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by yelhouti** [comment]
@pascalgrimaud does it mean you guys agree on switching back to angular cli and removing most (all?) of the custom webpack config?

**Comment by pascalgrimaud** [comment]
We tried several years ago and it didn't manage to make angular cli working.
If I'm not wrong, @wmarques proposed on Twitter to switch to Angular CLI.

For me, if we manage to make angular cli compatible with JHipster, it's fine.
But, I'm not a front guy, so @wmarques @vishal423 @kaidohallik are the best here to answer !

**Comment by yelhouti** [comment]
I'm waiting for the go from any of you guys: @wmarques @vishal423  @kaidohallik

**Comment by vishal423** [comment]
@yelhouti, yes I would also like to migrate to `angular cli`. I proposed that for v7 in this [thread](https://groups.google.com/forum/#!topic/jhipster-dev/QI1b5frW13A) as it would be a breaking change. As per my understanding, @wmarques might have already started on it.

**Comment by yelhouti** [comment]
thanks @vishal423 for your comment, @wmarques do you want any help for this?

**Comment by deepu105** [comment]
When we tried last time it was difficult to get some of the custom stuff we
were doing and also the bundle size was not as good as what we had. If it's
possible to get similar results with CLI without breaking changes then I'm
ok with that. If there are breaking changes then may be better to postpone
for next major version

**Comment by wmarques** [comment]
I'm working on it and I will continue this work during JHipster day at Ippon offices next Tuesday.
I will be able to provide a PR.

@deepu105 we can now extend their config so we should be able to keep our improvements.

**Comment by yelhouti** [comment]
@wmarques great thanks for letting me know (it avoids double work), can I join the session remotely?

**Comment by wmarques** [comment]
@yelhouti Sorry the Jhipster Day will be on tuesday 15th and not next tuesday. Of course you can join this remotely. 

If you want to progress further on it I can provide a starting point on my repo and give you the rights to contribute on it :)

**Comment by yelhouti** [comment]
Sure, please don't hesitate

**Comment by yelhouti** [comment]
@wmarques is there some calendar I can subscribe to?

**Comment by wmarques** [comment]
@yelhouti here is the branch https://github.com/wmarques/generator-jhipster/tree/add-angular-cli

**Comment by mraible** [comment]
Increasing the bounty since I'd love to see this happen!

**Comment by gmarziou** [comment]
This is fantastic, thanks @wmarques

**Comment by igor-h** [comment]
@wmarques Hi William. What can we do if I have project started with jHipster in 2019-2020, when the frontend was still build with webpack. 
How can I upgrade now? 
Do we have some steps for that?
Thank you!

**Comment by wmarques** [comment]
Hello,
Unfortunately I don't have a documentation ready for you. I think the best way is to generate a new app and see the differences on the frontend side. It's not huge I think, mostly moving some folders, it's mostly configuration.
But if you never upgraded since 2 years you will have other issues than the Angular cli I'm afraid...
