### ISSUE TITLE
Treating cookie theft exception correctly

### ISSUE THREAD

**Issue by thiagonuic** [jhipster/generator-jhipster#1053]
Hi,

I am having some problem when spring security detects cookie theft, which redirects to a generic error page showing something like:

Status: Internal Server Error (Internal Server Error)
??message_en_US?? Invalid remember-me token (Series/token) mismatch. Implies previous cookie theft attack.

This is obviously terrible for user experience. I found this link (below) on how to solve it with spring xml.

http://blog.triptiny.com/2012/09/20/how-to-handle-cookietheftexception-in-spring-remember-me-authentication-elegantly/

How would we solve it with spring boot and the jhipster architecture? The best solution would be to redirect the user to the login page.

Thanks.

**Comment by jdubois** [comment]
If your users are having a cookie theft attack, the best solution would be to alert them ASAP. This should not happen under normal operations, of course.
We could redirect them to a specific page, but at the moment they should just be redirected to the login page: isn't this the case on your app?

**Comment by thiagonuic** [comment]
Not right now, they are getting this error and even pressing F5 it does not solve it. Sometimes I get cookie theft attack during development, but F5 solves the problem. I just don't know how to apply a solution to redirect to the login page. The current error page comes from spring.

**Comment by thiagonuic** [comment]
They are not getting true cookie theft attack since it is only intranet for a couple of users right now.

**Comment by jdubois** [comment]
OK, so it's more an error from JHipster.

- which version are you using? we might have had a bug in a previous version
- can you try with a simple app? maybe it's because you broke something without noticing

**Comment by gkhighelf** [comment]
Good day.
I have the same issue with clean install.

generator params
{
  "generator-jhipster": {
    "baseName": "appname",
    "packageName": "com.appname",
    "packageFolder": "com/appname",
    "authenticationType": "cookie",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8"
  }
}

node_modules/generator-jhipster/package.json

  "name": "generator-jhipster",
  "version": "2.0.0",

**Comment by jdubois** [comment]
It might be linked to Hazelcast -> are you using Hazelcast in production mode? This is something I didn't try

**Comment by thiagonuic** [comment]
In my case I am no using hazelcast.

**Comment by gkhighelf** [comment]
yes, i'm using HazelCast in production mode

**Comment by jdubois** [comment]
We upgraded Hazelcast in the latest version, and it corrected some other login/logout issues, can you test if you still have the problem?

**Comment by jdubois** [comment]
No news - I guess this was due to HazelCast, so I'm closing this

**Comment by marcus-rp** [comment]
Hi

I don't have HazelCast set on the project, anyway that problem also occurs to me.

**Comment by mydevalias** [comment]
I noticed this happens a lot for me if one time I start the server normal and after I start it in debug. For now I did a quick fix and I threw RememberMeAuthenticationException instead of CookieTheftException in CustomPersistentRememberMeServices.getPersistentToken. This will redirect to main page and users can re-login
