### ISSUE TITLE
jhipster gae seems to be broken

### ISSUE THREAD

**Issue by Simsal** [jhipster/generator-jhipster#10533]
##### **Overview of the issue**

I had a running application on google gae, deployed via jhipster gae. This was with jhipster 5.x. Deployment of this old version still succeeds.

Deployment of newer jhipster versions doesn't work.

GAE Error reporting doesn't show any errors.

##### **Motivation for or Use Case**

I can't update my application 

##### **Reproduce the error**

It is reproducable by generating a new jhipster monolithic application and running the gae generator. The generator says that everything worked as expected, but the server returns a 500 error.

> Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds.

##### **Suggest a Fix**

In earlier versions there were much more files uploaded to Google Cloud Storage. With jhipster 6.3.1 there is just 1 file.

```
[INFO] GCLOUD: Services to deploy:
[INFO] GCLOUD:
[INFO] GCLOUD: descriptor:      [/Users/d0253800/Workspace/testJhipster/target/appengine-staging/app.yaml]
[INFO] GCLOUD: source:          [/Users/d0253800/Workspace/testJhipster/target/appengine-staging]
[INFO] GCLOUD: target project:  [xyz]
[INFO] GCLOUD: target service:  [default]
[INFO] GCLOUD: target version:  [1]
[INFO] GCLOUD: target url:      [https://xyz.appspot.com]
[INFO] GCLOUD:
[INFO] GCLOUD:
[INFO] GCLOUD: Beginning deployment of service [default]...
[INFO] GCLOUD: #============================================================#
[INFO] GCLOUD: #= Uploading 1 file to Google Cloud Storage                 =#
[INFO] GCLOUD: #============================================================#
[INFO] GCLOUD: File upload done.
[INFO] GCLOUD: Updating service [default]...
[INFO] GCLOUD: ......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done.
[INFO] GCLOUD: Setting traffic split for service [default]...
[INFO] GCLOUD: ....................................done.
[INFO] GCLOUD: Deployed service [default] to [https://xyz.appspot.com]
[INFO] GCLOUD:
[INFO] GCLOUD: You can stream logs from the command line by running:
[INFO] GCLOUD:   $ gcloud app logs tail -s default
[INFO] GCLOUD:
[INFO] GCLOUD: To view your application in the web browser run:
[INFO] GCLOUD:   $ gcloud app browse
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:55 min
[INFO] Finished at: 2019-10-01T16:58:30+02:00
```

##### **JHipster Version(s)**

6.3.1

##### **JHipster configuration**

> Welcome to the JHipster Information Sub-Generator
> 
> ##### **JHipster Version(s)**
> 
> ```
> test-jhipster@0.0.1-SNAPSHOT /Users/d0253800/Workspace/testJhipster
> └── generator-jhipster@6.3.1
> 
> ```
> 
> 
> ##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
> 
> 
> <details>
> <summary>.yo-rc.json file</summary>
> <pre>
> {
>   "generator-jhipster": {
>     "promptValues": {
>       "packageName": "com.mycompany.myapp",
>       "nativeLanguage": "de"
>     },
>     "jhipsterVersion": "6.3.1",
>     "applicationType": "monolith",
>     "baseName": "testJhipster",
>     "packageName": "com.mycompany.myapp",
>     "packageFolder": "com/mycompany/myapp",
>     "serverPort": "8080",
>     "authenticationType": "jwt",
>     "cacheProvider": "ehcache",
>     "enableHibernateCache": true,
>     "websocket": false,
>     "databaseType": "sql",
>     "devDatabaseType": "h2Disk",
>     "prodDatabaseType": "mysql",
>     "searchEngine": false,
>     "messageBroker": false,
>     "serviceDiscoveryType": false,
>     "buildTool": "maven",
>     "enableSwaggerCodegen": false,
>     "jwtSecretKey": "xyz",
>     "embeddableLaunchScript": false,
>     "useSass": true,
>     "clientPackageManager": "npm",
>     "clientFramework": "angularX",
>     "clientTheme": "none",
>     "clientThemeVariant": "",
>     "testFrameworks": [],
>     "jhiPrefix": "jhi",
>     "entitySuffix": "",
>     "dtoSuffix": "DTO",
>     "otherModules": [],
>     "enableTranslation": true,
>     "nativeLanguage": "de",
>     "languages": [
>       "de",
>       "en"
>     ],
>     "blueprints": [],
>     "gcpProjectId": "xyz",
>     "gcpCloudSqlInstanceName": "xyz:europe-west3:xyz",
>     "gcpCloudSqlUserName": "root",
>     "gcpCloudSqlDatabaseName": "test",
>     "gaeServiceName": "default",
>     "gaeLocation": "europe-west3",
>     "gaeInstanceClass": "F1",
>     "gaeScalingType": "automatic",
>     "gaeMinInstances": "1",
>     "gaeMaxInstances": "1",
>     "gaeCloudSQLInstanceNeeded": "Y"
>   }
> }
> </pre>
> </details>
> 
> 
> ##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
> 
> <details>
> <summary>JDL entity definitions</summary>
> 
> <pre>
> 
> </pre>
> </details>
> 
> 
> ##### **Environment and Tools**
> 
> java version "1.8.0_151"
> Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
> 
> git version 2.14.3
> 
> node: v8.11.3
> 
> npm: 6.10.1
> 
> yeoman: 3.1.0
> 
> yarn: 1.13.0
> 
> INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

none

##### **Browsers and Operating System**
MacOS

-   [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@Simsal : Hi again Simsal. Seems you are doing deployments in all platforms. :smile: 

I think I know what is going on here. Firstly we have migrated to Jar packaging; which is why you see one file probably. Since we now support [AppEngine standard with Java 11](https://cloud.google.com/appengine/docs/standard/java11/); I suggest you build the application in Java 11. You can easily change this by changing the pom files "java.version" property to 11. Also make sure you use F2 instance or higher as it seems [Google App engine doesn't support spring boot on F1 instances](https://github.com/jhipster/generator-jhipster/issues/10331#issuecomment-528563349). 

Please let me know if you have any additional questions. :smile: 

Some additional information, we were doing lots of improvements to GAE. There's one pull request that is yet to be merged and this will improve it even further; https://github.com/jhipster/generator-jhipster/pull/10420

**Comment by Simsal** [comment]
Hey, be prepared for some problems in azure ;)

Thank you for your input, I really appreciate it.

Ah, I missed the part with the F1 instance within the other issue. I already tried it with the java 11 compiling.

So with the change to F2 I get atleast errors within gae.
There is a 

> java.lang.OutOfMemoryError: Java heap space

error. 
Do you think that this is somehow related to the generator?

Errormessage:
`org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditEventsEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/audit/AuditEventsEndpointAutoConfiguration.class]: Unsatisfied dependency expressed through method 'auditEventsEndpoint' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'customAuditEventRepository' defined in URL [jar:file:/srv/xyz-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/com/fs/xyz/repository/CustomAuditEventRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistenceAuditEventRepository': Cannot create inner bean '(inner bean)#41aaedaa' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#41aaedaa': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: Java heap space`

**Comment by SudharakaP** [comment]
@Simsal :

> Hey, be prepared for some problems in azure ;)

As far as I know, there's no sub-generator for Azure but rather documented instructions on how to deploy using Docker or Kubernetes (https://www.jhipster.tech/azure/). It would be interesting and yes, I might be able to take a look there too if you run into problems. 😄 

> Thank you for your input, I really appreciate it.

You are welcome. 😄 

> Ah, I missed the part with the F1 instance within the other issue. I already tried it with the java 11 compiling.
> 
> So with the change to F2 I get atleast errors within gae.
> There is a
> 
> > java.lang.OutOfMemoryError: Java heap space
> 
> error.
> Do you think that this is somehow related to the generator?
> 
> Errormessage:
> `org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditEventsEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/audit/AuditEventsEndpointAutoConfiguration.class]: Unsatisfied dependency expressed through method 'auditEventsEndpoint' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'customAuditEventRepository' defined in URL [jar:file:/srv/xyz-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/com/fs/xyz/repository/CustomAuditEventRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistenceAuditEventRepository': Cannot create inner bean '(inner bean)#41aaedaa' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#41aaedaa': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: Java heap space`

I have encountered this error. I don't remember with absolute clarity on how I get over this; but I have a hunch this is related to cloud sql. I've wrote down some stuff which needs to be improved in this sub-generator and will do some testing today evening and get back to you. 

On another note, I noticed that our documentation; https://www.jhipster.tech/gcp/ mentions the deployment command as, ./mvnw appengine:deploy -DskipTests -Pgae,prod-gae,war. This should be corrected to ./mvnw appengine:deploy -DskipTests -Pgae,prod-gae since we no longer are using the war profile. I'll correct this in the documentation in the evening as well. 😄

**Comment by SudharakaP** [comment]
@Simsal : Sorry, the command should be `./mvnw package appengine:deploy -DskipTests -Pgae,prod-gae`.

**Comment by SudharakaP** [comment]
@Simsal : Sorry, I've made a mistake in my above comment. Firstly the command to deploy should be, `./mvnw package appengine:deploy -DskipTests -Pgae,prod-gae`. Secondly this works after the the pull request https://github.com/jhipster/generator-jhipster/pull/10420 is merged.

**Comment by SudharakaP** [comment]
@Simsal : I couldn't recreate the same error you got but I did manage to get a similar error even when using F2 instance and your exact same configuration. It seems that the memory exceeded after serving some requests. Could you please try a class larger than F2 instance or keep F2 as it is and increase the max instance count to 2 or more. I believe this should fix the issue.

**Comment by ruddell** [comment]
Do we set `_JAVA_OPTIONS=-Xmx512m -Xms256m` or similar config anywhere for AppEngine?  For example, Docker [does it here](https://github.com/jhipster/generator-jhipster/blob/ad4131887c1161ea77ad0ab4fff6fef57a5eacd0/generators/server/templates/src/main/docker/app.yml.ejs#L24) and Heroku [does it here](https://github.com/jhipster/generator-jhipster/blob/ad4131887c1161ea77ad0ab4fff6fef57a5eacd0/generators/heroku/templates/Procfile.ejs#L19)

**Comment by SudharakaP** [comment]
> Do we set `_JAVA_OPTIONS=-Xmx512m -Xms256m` or similar config anywhere for AppEngine? For example, Docker [does it here](https://github.com/jhipster/generator-jhipster/blob/ad4131887c1161ea77ad0ab4fff6fef57a5eacd0/generators/server/templates/src/main/docker/app.yml.ejs#L24) and Heroku [does it here](https://github.com/jhipster/generator-jhipster/blob/ad4131887c1161ea77ad0ab4fff6fef57a5eacd0/generators/heroku/templates/Procfile.ejs#L19)

@ruddell : Actually this is a very good point, which I totally missed; yes app engine can set it; https://cloud.google.com/appengine/docs/standard/java11/runtime#application_startup. I think we should add this as well to our `app.yaml` file. Since this is a minor change, I'll add this to our [existing pull request](#10420).

@Simsal : You can try this too; all you got to do is set `entrypoint: java -Xmx512m -jar your-artifact.jar` in `app.yaml` file.

**Comment by SudharakaP** [comment]
@Simsal : Did you figure this out; or do you need any further assistance from our side? :smile:

**Comment by Simsal** [comment]
Hey @SudharakaP ,
Sorry I have been ill the past week. I just looked into your hints.
-> Increasing the app engine instance class to F2 or even F4 hasn't changed the outcome, neither has 2 running instances
-> Yes I used the `./mvnw package appengine:deploy -DskipTests -Pprod,prod-gae`
-> How can I set the entrypoint? If I change the file directly at `target/appengine-staging/app.yaml` and use `./mvnw package appengine:deploy -DskipTests -Pprod,prod-gae` for deploying, than the entrypoint gets overwritten. If I leave out `package` it doesn't upload the altered app.yaml

> Beginning deployment of service [default]...
> [INFO] GCLOUD: #============================================================#
> [INFO] GCLOUD: #= Uploading 0 files to Google Cloud Storage                =#
> [INFO] GCLOUD: #============================================================#
> [INFO] GCLOUD: File upload done.

**Comment by SudharakaP** [comment]
> Hey @SudharakaP ,
> Sorry I have been ill the past week. I just looked into your hints.
> -> Increasing the app engine instance class to F2 or even F4 hasn't changed the outcome, neither has 2 running instances
> -> Yes I used the `./mvnw package appengine:deploy -DskipTests -Pprod,prod-gae`
> -> How can I set the entrypoint? If I change the file directly at `target/appengine-staging/app.yaml` and use `./mvnw package appengine:deploy -DskipTests -Pprod,prod-gae` for deploying, than the entrypoint gets overwritten. If I leave out `package` it doesn't upload the altered app.yaml
> 
> > Beginning deployment of service [default]...
> > [INFO] GCLOUD: #============================================================#
> > [INFO] GCLOUD: #= Uploading 0 files to Google Cloud Storage                =#
> > [INFO] GCLOUD: #============================================================#
> > [INFO] GCLOUD: File upload done.

@Simsal : Thanks for testing this out. Changing anything in the `target` directory will not work since rebuilding the project will overwrite it. The `app.yaml` file can be found at, `src/main/appengine` folder. Change that instead. :smile: 

Hope you get well soon :smile:

**Comment by pascalgrimaud** [comment]
I think everything was fixed recently.
Don't hesitate to tell me if I'm wrong, so I can reopen this ticket if needed

For now, let's close this
