### ISSUE TITLE
Hibernate 5.3.11 critical issue

### ISSUE THREAD

**Issue by laurentsorin** [jhipster/generator-jhipster#10544]
Hi, 
##### **Overview of the issue**

After upgrading my app to this jhipster version, I encountered this critical issue : https://hibernate.atlassian.net/browse/HHH-13590

After few searches, I noticed that Jhipster 6.3.1 use hibernate 5.3.11 from jhipster-dependencies 3.0.5 (see https://github.com/jhipster/jhipster/blob/3.0.5/jhipster-dependencies/pom.xml) but a critical bug has been solved by hibernate team for this version

##### **Motivation for or Use Case**

This is a blocking issue for my app (I was previously on 5.2)

##### **Reproduce the error**

It's a bit difficult to reproduce the bug from a jhipster vanilla or generated entities, but I think that jhipster must integrate updated libraries (especially if critical bugs are fixed).

See the jira hibernate ticket to a hibernate use case : https://hibernate.atlassian.net/browse/HHH-13590

##### **Related issues**

N/A

##### **Suggest a Fix**

Migrate hibernate in jhipster-dependencies to 5.3.12
A workaround is to exclude hibernate 5.3.11 from maven dependencies and add 5.3.12

##### **JHipster Version(s)**

6.3.1, it's a regression (I was previously on jhipster 5.2)

##### **JHipster configuration**

> INFO! Using JHipster version installed globally
> INFO! Executing jhipster:info
> INFO! Options: from-cli: true
> Welcome to the JHipster Information Sub-Generator
> 
> ##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
> 
> <details>
> <summary>.yo-rc.json file</summary>
> <pre>
> {
>   "generator-jhipster": {
>     "promptValues": {
>       "packageName": "com.app.base",
>       "nativeLanguage": "en"
>     },
>     "jhipsterVersion": "6.3.1",
>     "baseName": "app-base",
>     "reactive": false,
>     "packageName": "com.app.base",
>     "packageFolder": "com/app/base",
>     "serverPort": "8080",
>     "authenticationType": "session",
>     "cacheProvider": "ehcache",
>     "enableHibernateCache": true,
>     "websocket": "spring-websocket",
>     "databaseType": "sql",
>     "devDatabaseType": "h2Disk",
>     "prodDatabaseType": "oracle",
>     "searchEngine": false,
>     "messageBroker": false,
>     "serviceDiscoveryType": false,
>     "buildTool": "maven",
>     "enableSwaggerCodegen": false,
>     "rememberMeKey": "",
>     "clientFramework": "react",
>     "useSass": true,
>     "clientPackageManager": "yarn",
>     "applicationType": "monolith",
>     "testFrameworks": [
>       "gatling",
>       "cucumber"
>     ],
>     "jhiPrefix": "jhi",
>     "enableTranslation": true,
>     "nativeLanguage": "en",
>     "languages": [
>       "en",
>       "fr"It's a bit difficult t
>     ],
>     "embeddableLaunchScript": false,
>     "clientTheme": "none",
>     "entitySuffix": "",
>     "dtoSuffix": "DTO",
>     "otherModules": [],
>     "blueprints": []
>   }
> }
> </pre>
> </details>
> 
>
> 
> ##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
> 
> <details>
> <summary>JDL entity definitions</summary>
> 
> <pre>
> 
> </pre>
> </details>
> 
> 
> ##### **Environment and Tools**
> 
> openjdk version "1.8.0_212"
> OpenJDK Runtime Environment (build 1.8.0_212-b04)
> OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
> 
> git version 2.20.1
> 
> node: v10.16.0
> 
> npm: 6.9.0
> 
> yeoman: 3.1.0
> 
> yarn: 1.17.3
> 
> Docker version 19.03.2, build 6a30dfca03

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

Fedora 29
Chrome

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@laurentsorin Thanks for the report!
Working actually to upgrade an actual project and figure out the same issue.

Actually spring-boot 2.1.9 is expected to be out today that includes the update of Hibernate version: https://github.com/spring-projects/spring-boot/issues?page=1&q=is%3Aclosed+milestone%3A2.1.9

So I am more in favor to upgrade to latest spring-boot version!

@jhipster/developers We should consider a new version this week to fix the issue?

**Comment by pascalgrimaud** [comment]
I should be able to do a release if needed

**Comment by jdubois** [comment]
Thanks a lot @laurentsorin !!!
I'll be travelling this weekend (to SpringOne!!) so thanks @pascalgrimaud for taking care of the release

**Comment by DanielFran** [comment]
@jdubois @pascalgrimaud Working on the update...

**Comment by pascalgrimaud** [comment]
I'm adding a bounty on this, as it looks important.
Thanks @laurentsorin for reporting this.
Thanks @DanielFran for working on the fix

**Comment by DanielFran** [comment]
@pascalgrimaud Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/10568

**Comment by DanielFran** [comment]
@pascalgrimaud Are you planning soon a new version due to that issue?

**Comment by pascalgrimaud** [comment]
@DanielFran : yes, I'd like and I'll try to do my best.
