### ISSUE TITLE
duplicate key-value in webpack.prod.js.ejs

### ISSUE THREAD

**Issue by speermahi** [jhipster/generator-jhipster#10557]
`
compress: {
                        dead_code: true,
                        warnings: false,
                        properties: true,
                        drop_debugger: true,
                        conditionals: true,
                        booleans: true,
                        loops: true,
                        unused: true,
                        toplevel: true,
                        if_return: true,
                        inline: true,
                        join_vars: true,
                        ecma: 6,
                        module: true,
                        toplevel: true
                    },
`

it has toplevel key twice within compress object

**Comment by vishal423** [comment]
@speermahi, would you like to contribute fix?
