### ISSUE TITLE
Update spring-boot to 2.2 and spring-cloud to Hoxton

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#10565]
From spring calender: http://spring-calendar.cfapps.io/

- Spring-boot 2.2 is expected on [October 16th](https://github.com/spring-projects/spring-boot/milestones): https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes

- Spring-cloud Hoxton is expected on [November 7th](https://github.com/spring-cloud/spring-cloud-release/milestones) : https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Hoxton-Release-Notes

Created branch https://github.com/jhipster/generator-jhipster/tree/spring-boot_2.x and https://github.com/jhipster/jhipster/tree/spring-boot_2.x for migration.

For reference:
- https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#upgrading-to-version-52
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2.0-Draft-Release-Notes

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
@jhipster/developers Spring boot 2.2 has been released !
See the [announcement](https://spring.io/blog/2019/10/16/spring-boot-2-2-0) and [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes).

**Comment by pmverma** [comment]
Note: To update Postgres dialect from current 95 to `org.hibernate.dialect.PostgreSQL10Dialect` as 2.2.0 uses hibernate 5.4 which has added it.

**Comment by DanielFran** [comment]
@pmverma Changed generator to use new dialect for PostgreSQL 10

**Comment by oliverkuldmae** [comment]
Is there an ETA for this update? This would resolve a pretty significant dependency conflict for a project I'm working on that uses PostgreSQL 11, PostGIS 3 and Flyway.

**Comment by pascalgrimaud** [comment]
@oliverkuldmae : as all the work is done during our personal time, there is no ETA. It will be done when someone takes the lead on the subject. So today, it is still in progress

**Comment by jdubois** [comment]
As this is important I'm adding a bug bounty... Please tell me if there is a significant amount of work (it doesn't seem to be at first sight), and I'll add more if needed.

**Comment by alexis-puska** [comment]
Hi all,
Can you migrate whit this dependencies, the version of hibernate 5.4.7.Final ?
I use hibernate search with elastic search, and i try to migrate with the last hibernate search backend elastic search require the Hibernate Search ORM Integration 6.0.0 and require hibernate core 5.4.7.Final minimum with spring boot 2.2
https://mvnrepository.com/artifact/org.hibernate.search/hibernate-search-mapper-orm/6.0.0.Beta2
it's so sade to migrate and create a jhipster server side dependencies and can't used the orm integration for hibernate search elastic search.
Currently wee only have the hibernate search elastic search to index information at each jpa operation but we only have the low rest api elastic search to request and aggregate information.
With this dependencies update we can use the orm mapper of hibernate search 6 to automaticatly index, and used the high rest level api of elastic search to request it (no longuer create json from scratch to make request, but a powerfull java api, and no longer elasticserach server dependencies with lucene conflict -> see here : https://github.com/elastic/elasticsearch/issues/29184)

**Comment by PierreBesson** [comment]
@alexis-puska I'm sorry but we can't upgrade to spring 2.2 as long as there is no spring cloud release that supports it. See the release train section on this part : https://spring.io/projects/spring-cloud#overview

**Comment by alexis-puska** [comment]
@PierreBesson Thank for the information, I watch this you wait for spring cloud Hoxton release and currently is only the release candidate... i hope the release came in the next day...

**Comment by alexis-puska** [comment]
The update of spring cloud is planified to 21 novembre : https://github.com/spring-cloud/spring-cloud-release/milestones !

**Comment by murdos** [comment]
@DanielFran : are you working on the upgrade, or may I try to work on it?

**Comment by DanielFran** [comment]
@murdos I put it on hold due to too many conflicts between the specific branch and the master, and it was not possible to rebase.
I am expecting to work on it during the weekend.

**Comment by ksilz** [comment]
Spring Cloud Hoxton [was released](https://spring.io/blog/2019/11/28/spring-cloud-hoxton-released).

**Comment by alexis-puska** [comment]
@DanielFran may the force be with you 👍

**Comment by PierreBesson** [comment]
Is someone working on the spring boot 2.2 migration ? I don't see any blocker to do it. Can I go forward with it ?
Also spring boot 2.2.2 is already out https://spring.io/blog/2019/12/06/spring-boot-2-2-2-is-now-available

**Comment by DanielFran** [comment]
@PierreBesson I have something working, just missing Elastic upgrade.
This is available in specific branchs...

**Comment by PierreBesson** [comment]
You are the best @DanielFran !

**Comment by DanielFran** [comment]
@PierreBesson Focused on SB 2.1.11 update last 2 days, now will continue to work on SB 2.2.
@pascalgrimaud Do you plan a new version soon? Might need a new one due to https://github.com/jhipster/generator-jhipster/issues/10887 and https://github.com/jhipster/generator-jhipster/issues/10885 bugs

**Comment by deepu105** [comment]
Awesome guys

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
@DanielFran : it could be cool a new release before the end of the year :-)

**Comment by juliensadaoui** [comment]
Spring Cloud Hoxton SR1 is available.

https://spring.io/blog/2019/12/21/spring-cloud-hoxton-service-release-1-sr1-is-available

**Comment by murdos** [comment]
Thanks @juliensadaoui ! I've updated jhipster-dependencies to use SR1

**Comment by pascalgrimaud** [comment]
I'm increasing the bounty as there is much more work than expected

**Comment by DanielFran** [comment]
@murdos @mraible Thanks for your help. You both deserv a part of the bounty!
How do you want to share?

**Comment by mraible** [comment]
@DanielFran No need to include me, I only added and if statement! 🙂

**Comment by murdos** [comment]
@mraible but you're the one that detected the spring boot version conflict! 😀

How about $200 for @DanielFran and me, and $100 for @mraible ?

**Comment by alexis-puska** [comment]
when is planed a version with spring boot 2.2 and server side dependencies up to date ?

**Comment by pascalgrimaud** [comment]
@alexis-puska : as JHipster is an Open Source project and all of us work on our personal time, there is no ETA. Sorry, just wait and be patient

**Comment by DanielFran** [comment]
@murdos Since @mraible did not wan't a part of the bounty, we can divide, $250 for each one.

**Comment by murdos** [comment]
> 
> 
> @murdos Since @mraible did not wan't a part of the bounty, we can divide, $250 for each one.

👍

**Comment by DanielFran** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/13194
