### ISSUE TITLE
Change page title when changing state in Angular

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1056]
Today the page title is static: it's the application name.
With angular-ui, a common approach is to use the state configuration data to store the title as jhipster already does for security roles and then to update the title in $rootScope when state changes.
As title must be translated, the state data should rather contain the key of the title.

If there's any interest, I'd like to work on it and propose a PR.

**Comment by andidev** [comment]
+1 this is a must have according to me

**Comment by atomfrede** [comment]
I like the idea :+1:

**Comment by jdubois** [comment]
Yes, that's a neat idea!

**Comment by rasheedamir** [comment]
Indeed nice idea!

**Comment by gmarziou** [comment]
I got it working for static titles, now I need to beable to make it work with state params and also build a service to enable developers to call it from a controller incase you want something specific (e.g. 'first_name last_name' as a title for a User view).

**Comment by jdubois** [comment]
@gmarziou can you already do a PR with the static titles? Let's first start with something easy, we'll make it more complex later

**Comment by gmarziou** [comment]
OK, I have to do some cleanup first.

**Comment by johnlamey** [comment]
@gmarziou : maybe this is very old ticket, but can I know did we enable the dynamic feature for title as you was intended before 'enable developers to call it from a controller in case you want something specific and dynamic (e.g. 'first_name last_name' as a title for a User view).'

**Comment by gmarziou** [comment]
Angular 1, we let developers setting a dynamic title from controller, see `state.handler.js`

Angular 2, it can be done from component using `this.titleService.setTitle(title);`

**Comment by johnlamey** [comment]
did as `state.handler.js` and it works fine, thanks @gmarziou for your help and contributions.
