### ISSUE TITLE
Improve the App Generation on the web portal

### ISSUE THREAD

**Issue by cmoine** [jhipster/generator-jhipster#10568]
##### **Overview of the feature request**

I don't know if this is the right place to submit the ticket since it is related to the web portal (https://start.jhipster.tech/#/generate-application). The actual implementation is pretty basic, and does not allow to use it in a productive manner.

##### **Motivation for or Use Case**

I found this web page very convenient because I did not have to install/configure/update jHipster every time, unfortunately, I cannot use this web page anymore if I want to generate VueJS app, since it is a blueprint. For me it is a show stopper for using it now. It would be cool:
- Either integrate blueprints usage into this web page
- Change VueJS blueprint into "bundled" generated, just like Angular & React. Since VueJS is really gaining popularity, I think that it would really make sense to do it anyway.

It would be also very nice to remember every choice made in this page, so we are able to generate an app generated with a newer version of JHipster.

##### **Related issues or PR**

None, but I would be glad to contribute for this feature in a PR.

**Comment by atomfrede** [comment]
We have plans to integrate vue.js into the mainline generator targeted for jhipster 7. Until then you have to install jhipster locally unfortunately.

**Comment by cmoine** [comment]
A vague idea when JHipster 7 is planned to be out? I cannot find any roadmap.

**Comment by pascalgrimaud** [comment]
@cmoine : thanks for proposing this. Anyway, I'll try to give you some answers:

- About Roadmap. There is no roadmap: it depends on the opened ticket and the features which are asked by the community
- About JHipster 7. There is no date. As all the team works on our free and personal time, it's not our main job, we are not paid for that. That's why we can't give a release date
- About Vue.js. It's not decided yet to include it to the main generator. It needs to be discussed. If you want to help, in fact, the current Vue.js is broken in our CI. Help are really welcome here

As everything is open sourced here, you can easily:
- fork the project jhipster-online
- work on it, to include the Vue.js blueprint
- build / package / deploy on your own infra/cloud

**Comment by cmoine** [comment]
Argl, indeed I realize it is the wrong place for this ticket, it should be on JHipster Online project.

**Comment by avdev4j** [comment]
But adding official blueprints as option on start.jhipster.tech is a good option imo.

**Comment by cmoine** [comment]
>  If you want to help, in fact, the current Vue.js is broken in our CI. 
Are you talking about the VueJS blueprint @pascalgrimaud ?

**Comment by cmoine** [comment]
I created the issue in the right place: https://github.com/jhipster/jhipster-online/issues/135

Is there a ticket for integrating VueJS generator into the mainline generator, or should I create one for the discussion?

**Comment by pascalgrimaud** [comment]
@cmoine : yes, plz, create a ticket here for Vue.js, so we can see if it's popular or not

**Comment by pascalgrimaud** [comment]
Yes, the CI for Vue.js is broken: https://github.com/jhipster/jhipster-vuejs
Again, failing protractor tests...

**Comment by avdev4j** [comment]
As I already worked on a JHipster online fork I probably help you to add blueprints on it. I don't have many free times but it's a great idea which I want to contribute for.

**Comment by cmoine** [comment]
> yes, plz, create a ticket here for Vue.js, so we can see if it's popular or not

https://github.com/jhipster/generator-jhipster/issues/10575

**Comment by pascalgrimaud** [comment]
I think we can close this as:
- a new discussion for integrating Vue.js to the core has been opened
- another ticket for using blueprint in jhipster-online
