### ISSUE TITLE
ManyToMany relation with required generates wrong faker config

### ISSUE THREAD

**Issue by duderoot** [jhipster/generator-jhipster#10577]
##### **Overview of the issue**
When creating a model with a `ManyToMany` relation and also specify the second entity as required in the owner entity, 
![grafik](https://user-images.githubusercontent.com/4954023/66424441-efca5580-ea0d-11e9-9239-451fc93ac206.png)

the liquibase script which is loading faker data is having a wrong column in it. 
<img width="1351" alt="grafik" src="https://user-images.githubusercontent.com/4954023/66424528-19837c80-ea0e-11e9-84bb-1ea1e388f61c.png">

The tests are passing because the faker csv file is not having data for this column i.e. `course_id`
<img width="321" alt="grafik" src="https://user-images.githubusercontent.com/4954023/66424682-5e0f1800-ea0e-11e9-8556-9c40a3591e78.png">

##### **Reproduce the error**
I attached the model that I am using.

##### **JHipster Version(s)**

```
sample-app@0.0.1-SNAPSHOT /Users/duderoot/git/jhipster/sample_app
└── generator-jhipster@6.3.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.xlabiq.app",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "monolith",
    "baseName": "sample_app",
    "packageName": "de.xlabiq.app",
    "packageFolder": "de/xlabiq/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Student {
  lastName String required,
  firstName String required
}
entity Course {
  name String required,
  description String
}
relationship ManyToMany {
  Student{course(name) required} to Course{student(lastName)}
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190717_289 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)

git version 2.21.0

node: v8.16.1

npm: 6.4.1

yeoman: 3.1.0

yarn: 1.17.3

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by murdos** [comment]
I think that https://github.com/jhipster/generator-jhipster/pull/10535/files might fixes this issue

**Comment by duderoot** [comment]
@murdos It looks like it will fix this. I will make a pull from your repo and try it.

**Comment by duderoot** [comment]
When @murdos will fix his PR #10535 with patch similar to [this](https://github.com/duderoot/generator-jhipster/commit/09140cb210c866358852dd27e892a2db9c40d8c8) it should work.

**Comment by duderoot** [comment]
@murdos Is there one particular reason why you reopen this PR or is it because you just add a new label to it?

**Comment by murdos** [comment]
I've reopen the **issue** because it still exists until my PR is merged. 
I've however closed your PR (assuming that was your intention, and that you closed by error the issue instead of the PR)

**Comment by duderoot** [comment]
Ok is fine by me. I thought it will be considered as duplicated and since the team wants _to have as few as possible and as much as need it_  🤓 open issues I was in the favor of closing this issue. IMHO  a reference on this issue or maybe an update of the description of your issue and will do.
