### ISSUE TITLE
add feature 'what's new in version XXX?'

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1057]
Would be nice to easaly communicate the changes in new releases to the users of the app.
This could be done in a JIRA style with a popup every new release presenting the user with the latest changes.

If not a popup at least present it for the user when mouse clicking the verrsion number located right next to the application name in the navbar.

I vote for both them.

Any thoughts on this? Please comment.

**Comment by gmarziou** [comment]
it's not required for the kind of apps I build so as long as it is easy to disable it it's OK for me

For instance, if it could be disabled  by a property in application.yml, it would be fine for me, I could even choose to enable it in integration testing to communicate with testers and disable it in application-prod.yml when running in production profile

**Comment by jdubois** [comment]
It's not required for me either... We usually just have a static page somewhere in the documentation, or even nothing at all

**Comment by andidev** [comment]
I'm closing this since the lack of intresst. I will probably dont have time to develop this right now anyway.
