### ISSUE TITLE
GitHub CI Default Timeout Problems

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10589]
##### **Overview of the issue**

It seems to me that the recent change to Github CI timeout reduction (https://github.com/jhipster/generator-jhipster/pull/10584) seems to have some effects. When I was trying to get https://github.com/jhipster/generator-jhipster/pull/10498 pass the tests, I observed two tests were failing. I've restarted the tests again several times but seems they keep failing. Notice that one failure says that a "shutdown signal was received" while the other says that "the timeout of 40 is exceeded" although this happens way before 40 mins. I wonder if this is a bug in the GitHub Actions given that they are still in Beta? 

##### **Motivation for or Use Case**

Getting our CI working. 

##### **Reproduce the error**

Try closing and reopening that PR for example. 

##### **Related issues**

https://github.com/jhipster/generator-jhipster/pull/10498

##### **Suggest a Fix**

I haven't dived deep into this; but for now maybe increase or remove the timeouts? 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I think there is a real problem with a build.
What is the config which failed ?
I guess it's couchbase, as it's failed with JDK8 in the daily builds project

**Comment by vishal423** [comment]
@SudharakaP, can you point me to the build job executions that you think got aborted before 40 mins? Please note that 40 mins duration is for the entire job to complete (not for individual steps inside job). There is an issue in our `ngx-couchbase` test suite that intermittently hangs the backend tests build. Default job timeout was 6 hours which unnecessarily hogs the build infrastructure resources and I believe 40 mins is enough time for a build job to be completed.

**Comment by vishal423** [comment]
@pascalgrimaud, on Github CI, `ngx-couchbase` build intermittently hangs on JDK 11. I suspect it's related to test containers.

**Comment by pascalgrimaud** [comment]
Oh it's Jdk11, so indeed, it's strange !
We need to investigate. 
And I agree, 40min is enough for a build

**Comment by SudharakaP** [comment]
@pascalgrimaud, @vishal423 : Here are the build jobs that failed. 

https://github.com/jhipster/generator-jhipster/pull/10498/checks?check_run_id=253798027

https://github.com/jhipster/generator-jhipster/pull/10498/checks?check_run_id=253798027

https://github.com/jhipster/generator-jhipster/pull/10498/checks?check_run_id=254018117

https://github.com/jhipster/generator-jhipster/pull/10498/checks?check_run_id=254018117

You can also find the complete list at the bottom of this page; https://github.com/jhipster/generator-jhipster/pull/10498/files

**Comment by vishal423** [comment]
https://github.com/jhipster/generator-jhipster/pull/10498/checks?check_run_id=253798027  -- failed after 6 hours timeout
https://github.com/jhipster/generator-jhipster/pull/10498/checks?check_run_id=254018117 -- failed after 40 mins (after reduction in wait timeout)

These failed on `couchbase` and that was one of reason to reduce wait timeout.

I don't see an issue with Github CI, unless you can provide more details on why you think so. As far as couchbase build problems are concerned (in multiple repositories), they need to be addressed (independent of this ci) and should be tracked in separate issue.

**Comment by SudharakaP** [comment]
@vishal423 : Thanks for the information. I didn't know there were already known problems with couchbase which is why u assumed it has something to do with GitHub ci. On that note I am closing this issue. Would you like me to open a new issue to track the couchbase issue? :smile:

**Comment by vishal423** [comment]
yes, that will help to have more visibility on that issue. Fyi, similar failure on `jhipster` pipeline https://github.com/jhipster/jhipster/runs/252032661
