### ISSUE TITLE
SecurityConfiguration.java: Eclipse Code Formatter Turned Off

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10580]
##### **Overview of the issue**

This question was raised by @amirensit on Gitter. 

On #9416 we have turned the Eclipse formatter off and on for a [certain piece of code in SecurityConfiguration.java](https://github.com/jhipster/generator-jhipster/pull/9416/files#diff-5896bcb3f7efe22444d57880b0069cf3) by adding `\\@formatter:off` and `\\@formatter:on`. I was wondering why this was added? Is there some kind of formatting issues with Eclipse? 😄 

cc: @mraible 

##### **Related issues**

#9416

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
That allows to preserve the manual formatting of security DSL. Also, that syntax is not specific to eclipse, and also works well with `intellij`.

**Comment by SudharakaP** [comment]
@vishal423 : Thanks for the explanation. Ah, didn't know that this is also common to Intellij. :smile:
