### ISSUE TITLE
Github Actions in CI sub generator

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#10599]
It would be cool to have Github Actions in the CI sub-generator, as it will be easy to integrate it for generated project in GitHub.

@vishal423 : do you want to took this ticket, as you already do an amazing work in our CI ?

**Comment by vishal423** [comment]
sure.

**Comment by jdubois** [comment]
I just did one for my Azure Spring Cloud sub-generator... And we have already something similar with Heroku.
We'll need to be smart and document cleanly what each sub-generator does.

**Comment by pascalgrimaud** [comment]
Nice @jdubois 
The new Azure Spring Cloud sub gen is only for deploying ? or does it include all .github workflow file to be used as a new CI too ?

**Comment by jdubois** [comment]
It runs test, packages and deploys... My goal is to do only a "git push" and be done 😁
Like Heroku in fact!

**Comment by vishal423** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/11001

**Comment by pascalgrimaud** [comment]
thanks @vishal423 ! just approuved :)
