### ISSUE TITLE
please support nacos configuration center

### ISSUE THREAD

**Issue by yudar1024** [jhipster/generator-jhipster#10597]
##### **Motivation for or Use Case**

git configuration center is hard to in product env. most real case are use nacos or appollo as configuration center. they support more feature than git configuration.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Hello @yudar1024, and thanks for your proposal.

I'd suggest you to create a JHipster sample application, and include `nacos` support. Please, share your code publicly on GitHub. 

Then, you can create a module and maintain the support:
https://www.jhipster.tech/modules/creating-a-module/

For now, I don't think it can be support in JHipster, as we have too many option to maintain. But, if your module becomes really popular, we can reconsider it.

Are you ready to start the work ?
