### ISSUE TITLE
In Sql scenario, To be able to choose Cascade and Fetch type in JDL would be fantastic

### ISSUE THREAD

**Issue by apescione** [jhipster/generator-jhipster#10593]
**JDL designing a relationship between two entities with Cascade and Fetch type**

Using JDL to generate my entities, you can choose CascadeType and FetchType if different from default values.

This feature is very useful because I can avoid to modify  Generated Entity Manually and lose these changes when I regenerate the entity from JDL.

I looked for similar issues, but it seems there aren't any requests about setting of cascade and/or fetching

**Comment by pascalgrimaud** [comment]
Thanks for proposing this.
Anyway, it would be against our Policy 2: only add options when there is sufficient added-value in the generated code

Adding this option would imply:
- code and maintain it
- add new builds to test this
- add option in jdl core
- etc

The solutions for you, are:
- do the change manually, after regenerating
- use git to compare and revert
- code your own module, which will be launch after you regenerate entity
- etc

@apescione : are you ready to code and maintain your own JHipster module for that ?
If it becomes really popular, we can reconsider this.

**Comment by MathieuAA** [comment]
> This feature is very useful because I can avoid to modify Generated Entity Manually and lose these changes when I regenerate the entity from JDL.

The issue is about how you deal with what's generated vs what you implement yourself.
There are solutions for that, mainly the "side-by-side" approach.
Having "Cascading" or "Fetching type" support seems like an implementation choice, which should be decided depending on your model, or even architecture.
