### ISSUE TITLE
Fix webpack errors during war packaging

### ISSUE THREAD

**Issue by jsebrien** [jhipster/generator-jhipster#10603]
Hello,

This issue comes after this one : https://github.com/jhipster/generator-jhipster/issues/10583

As a reminder, i'm using Jhipster to build a webapp, and I need to create a war file to deliver it in production. I'm running the following command: mvn package (or mvn -Pprod,war clean verify)

I get a lot of errors from npm/webpack:
[mvn-package.log](https://github.com/jhipster/generator-jhipster/files/3717705/mvn-package.log)

jhipster info command output:
[jhipster-info.log](https://github.com/jhipster/generator-jhipster/files/3717707/jhipster-info.log)

What are the errors I need to fix here?

Regards,

Julien

**Comment by clement26695** [comment]
Hi @jsebrien,

Would it be possible to fill out the template provided when creating an issue? We need you to provide the result of `jhipster info` command, the version of JHipster used and a few others to help you. Otherwise, there are too many configurations available to know how to reproduce your issue and find a way to solve it.

You can also provide a link to a github repository of your application so we can work on that

**Comment by jsebrien** [comment]
Hello,
jhipster-info.log in my ticket contains the output of the jhipster info command.
The original repo is on bitbucket, I'll try to create a github repo with the code.
Regards,
Julien

**Comment by clement26695** [comment]
I would say it comes from the fact that you want to use elasticsearch in your entities (see `search Chart, DocMetas with elasticsearch` in the jhipster-info.log) but that you didn't enable ElasticSearch in your app generation (see `"serviceDiscoveryType": false,` in the jhipster-info.log)

Removing the `search Chart, DocMetas with elasticsearch`  in the jdl makes the compile phase pass in my case

**Comment by jsebrien** [comment]
Hello,

You mean, removing "searchEngine": "elasticsearch" in .jhipster/DocMetas.json and Chart.json 
or running again jhipster import-jdl <my_jdl>
and then run again command : mvn -Pprod,war clean verify 
?
Regards,
Julien

**Comment by clement26695** [comment]
Either of these options should work:
- remove the last line of your jdl file ant run `jhipster import-jdl <my_jdl>` again
- remove manually `"searchEngine": "elasticsearch"`in .jhipster/DocMetas.json and Chart.json and run `jhipster entity DocMetas` and `jhipster entity Chart` to regenerate the 2 entities

Finally, as you are using JHipster version 5.8.1, I don't think the war profile exists, and you should just use `./mvnw -Pprod package` to package the app

**Comment by clement26695** [comment]
FYI, you can access older version of the documentation here: https://www.jhipster.tech/documentation-archive/
For the 5.8.1 version, it is accessible here: https://www.jhipster.tech/documentation-archive/v5.8.1

**Comment by jsebrien** [comment]
Hello,

I tried, but it does not solve the issue.
Can you explain me how service discovery and the npm errors I get are related?
Regards,
Julien Sebrien

**Comment by gmarziou** [comment]
About your webpack build errors, they occur in `node_modules/react-dropzone-uploader/dist/Dropzone.tsx` which seems strange for me because if you look at your project's tsconfig.json it excludes `node_modules`, so it should not try to build Dropzone.tsx unless you made some changes.

```json
  "include": ["src/main/webapp/app", "src/test/javascript/spec"],
  "exclude": ["node_modules"]
```

**Comment by gmarziou** [comment]
Your errors come from typescript compilation of react-dropzone-uploader, try updating typescript.
Anyway, this is not a JHipster issue.
