### ISSUE TITLE
Keycloak Daily Build Broken

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10605]
##### **Overview of the issue**

It seems that the Keycloak daily build has some problems with it's end-to-end tests phase. 

https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=34&_a=summary

In every build the e2e phase seems to be broken. 

##### **Motivation for or Use Case**

Getting the CI tests in working condition gives us more visibility on problematic code and reduces bugs at runtime. 

##### **Reproduce the error**

Running the daily builds.

##### **Related issues**

None that I know of.

##### **Suggest a Fix**

Not known yet.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I think we should keep all of this in one ticket. Because, we can open at least 10 new tickets for all these failed builds ahaha

**Comment by pascalgrimaud** [comment]
closing in favor of https://github.com/jhipster/generator-jhipster/issues/10604
