### ISSUE TITLE
Cannot change spring profile to prod

### ISSUE THREAD

**Issue by aunlu** [jhipster/generator-jhipster#10601]
##### **Overview of the issue**

I created a sample Jhipster project  by following online jhipster-guides. It works fine in dev mode with "./mvnw ". But, when I try to test with prod mode (./mvnw -Pprod), it still uses dev profiles:

```	Application 'BugTrackerJHipster' is running! Access URLs:
	Local: 		http://localhost:8080/
	External: 	http://127.0.1.1:8080/
	Profile(s): 	[swagger, dev]
```
Also, "./mvnw -Pprod clean verify" does not produce executable jar.

##### **JHipster configuration**
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
bug-tracker-j-hipster@0.0.1-SNAPSHOT /media/aunlu/Data/aunlu/Documents/SourceCode/jhipster/BugTrackerJHipster
└── generator-jhipster@6.3.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.bugtracker",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "monolith",
    "baseName": "BugTrackerJHipster",
    "packageName": "com.mycompany.bugtracker",
    "packageFolder": "com/mycompany/bugtracker",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "false",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "tr"
    ],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Project {
  name String
}
entity Label {
  label String minlength(3)
}
entity Ticket {
  title String required,
  description String,
  dueDate LocalDate,
  done Boolean
}
relationship ManyToOne {
  Ticket{project(name)} to Project,
  Ticket{assignedTo(login)} to User
}
relationship ManyToMany {
  Ticket{label(label)} to Label{ticket}
}

paginate Ticket with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment Zulu11.33+15-CA (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.33+15-CA (build 11.0.4+11-LTS, mixed mode)

git version 2.20.1

node: v10.16.3

npm: 6.9.0

Docker version 19.03.2, build 6a30dfca03

##### **Browsers and Operating System**
Ubuntu 19.04

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@aunlu : Did you manually change the `.yo-rc.json` file by any chance? The line `"serviceDiscoveryType": "false"` seems problematic. It should be `"serviceDiscoveryType": false` without the quotes around `false`.

**Comment by pascalgrimaud** [comment]
You need to provide more steps to reproduce, as everything works fine with prod profile

**Comment by pascalgrimaud** [comment]
@aunlu : I couldn't reproduce. Feel free to provide steps in details and more information, then I can try again and reopen this ticket if needed
