### ISSUE TITLE
Auto Delete Merged Head Branches of Pull Requests

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10616]
##### **Overview of the feature request**

I was wondering if it's possible to enable auto delete merged branches of pull requests; https://github.blog/changelog/2019-07-31-automatically-delete-head-branches-of-pull-requests/ and https://help.github.com/en/articles/managing-the-automatic-deletion-of-branches

cc: @jhipster/builders 

##### **Motivation for or Use Case**

This would save unnecessary hassle of manual deletion of branches after merging the pull requests. :smile: 

##### **Related issues or PR**

None that I know of. 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I could change this, if all @jhipster/developers agree

**Comment by sendilkumarn** [comment]
Sure let us do it

**Comment by pascalgrimaud** [comment]
just done, so I'm closing this

**Comment by SudharakaP** [comment]
@pascalgrimaud : Thank you :)

**Comment by SudharakaP** [comment]
@pascalgrimaud : Are you certain this is done? Because, I still have to manually delete branches it seems. :thinking:  For example; 

![image](https://user-images.githubusercontent.com/12435965/66892131-aa72ce80-ef9f-11e9-8a53-83a97e6f4f8c.png)

**Comment by PierreBesson** [comment]
@SudharakaP Those are on your own fork. They belong to you, we cannot delete them for you.

**Comment by pascalgrimaud** [comment]
Yes I'm sure. But as Pierre said, I think it concerns only the branch of the project, not the branch of the fork, as we don't have right on this

**Comment by SudharakaP** [comment]
@pascalgrimaud @PierreBesson : Ops, you guys are right. On another project which we are working on, I have write access this is why I was confused. Sorry for the trouble. :smile:
