### ISSUE TITLE
support for other UI

### ISSUE THREAD

**Issue by hqzh** [jhipster/generator-jhipster#10617]
##### **Overview of the feature request**

Bootstrap4, not the only option, I want to use [antd](https://ant.design/docs/react/introduce-cn)

##### **Motivation for or Use Case**

Chinese users demand

**Comment by pascalgrimaud** [comment]
@hqzh : thanks for your proposal, but we can't support in main generator-jhipster as it will be too much work for the core team. 

What I can suggest is:
- create a public repo on GitHub and share your code
- then, you can create a module ; see https://www.jhipster.tech/modules/creating-a-module/
- or you can create a blueprint ; see https://www.jhipster.tech/modules/creating-a-blueprint/

If it becomes popular, we can reconsider to integrate it to main generator-jhipster. 

@hqzh : are you ready and motivated to work and maintain your own module/blueprint ?

**Comment by hqzh** [comment]
thanks, I am not available in the near future, I will continue to pay attention

**Comment by pascalgrimaud** [comment]
As you don't have yourself the bandwidth to work on this, let's close this ticket
