### ISSUE TITLE
Incorrect location of app.js

### ISSUE THREAD

**Issue by atul-bhosale** [jhipster/generator-jhipster#1061]
JHipster Version : 2.1.0

As per documentation (http://jhipster.github.io/using_angularjs.html) "app.js" is under "scripts" directory. But when I setup the application the location of app.js is "scripts/app/app.js".
and in sample app (https://github.com/jhipster/jhipster-sample-app) "app.js" is under "scripts/app"

Also when I tried to add route using (https://github.com/yeoman/generator-angular#route) "yo angular:route myroute" shows following error

$ yo angular:route myroute

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'c:\xampp\htdocs\jhipster\src\main\weba
pp\scripts\app.js'

as location of app.js is incorrect.

OR I missed any configuration.

**Comment by gmarziou** [comment]
2 issues:
- error in documentation, I'll fix it.
- error using another yeoman angular generator

I have tested few other yeoman generators and most of them are not compatible with jhipster project structure. The closest one would probably angular-fullstack.

Also using angular:route may not be very helpful with JHipster 2.x as it is now using angular-ui states for routing.

**Comment by rainerschuster** [comment]
According to https://docs.google.com/document/d/16oIpeEyb-qkPjM_bVQ4zX-dlibyH5_21fTrdQllGiwM/edit?usp=sharing JHipster supports "yo angular" since release 2.0.0. Maybe this document should also be fixed.

**Comment by gmarziou** [comment]
I know there have been some work done for this particular generator but for this particular sub generator about routes I'm sure it's going to be difficult to standard routes and angular-ui states as described [here](https://github.com/angular-ui/ui-router/wiki/Backwards-Compatibility). Also the states are more powerful and I don't know how the role-based authorization system of JHipster would work with routes as allowed roles are specified in state's data.

**Comment by gmarziou** [comment]
I updated the doc in this PR https://github.com/jhipster/jhipster.github.io/pull/27

Regarding the angular generator, I'll wait comments from @jmirc who did some work on it.

**Comment by jdubois** [comment]
Thanks @gmarziou I merged your PR.

Yes @jmirc did some work to integrate with the "angular" generator, but normally Yeoman generator aren't compatibles with each other (this might change in future versions), so don't expect those to work!
