### ISSUE TITLE
Support creation of SCIM 2.0 endpoints

### ISSUE THREAD

**Issue by thawkins** [jhipster/generator-jhipster#10620]
##### **Overview of the feature request**

SCIM 2.0 is a standard for exposing APIs that allow provision of user/group resources inside an application. 

see: https://github.com/BetterCloud/scim2  for an implementation. 

However we would need to ensure than the user/group management model was consistent with the SCIM model to even be able to graft this implementation onto the app. 

A blueprint to embed the better cloud implementation and hook up any required configs/code would be cool. 

It would be a step towards supporting federated authentication systems like WS02 Identity server directly. 

##### **Motivation for or Use Case**

When creating enterprise applications, organizations often have their own enterprise wide user/group directories (for example Okta), having an SCIM implementation would allow the user records inside the JHipster APP to be synchronized with the external directory. Note in this use case authentication would still remain  with the external service, but enumeration (listing people based on their properties would come from the local database, example: people who can approve this request)

##### **Related issues or PR**

No previous request has been made as far as I am aware. 

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Thanks for your proposal @thawkins

As suggested, are you ready to work on a blueprint or module ?
In this case, don't hesitate to tweet once you have a 1st version, so you can have feedback from community. 

Then, if your blueprint or module becomes really popular, we can reconsider to include it to the core generator-jhipster.

**Comment by pascalgrimaud** [comment]
I'm closing this as it should go to module, as suggested
