### ISSUE TITLE
Entities sorting is not working properly

### ISSUE THREAD

**Issue by ashishjmeshram** [jhipster/generator-jhipster#10629]
##### **Overview of the issue**

Created a new jhipster project from scratch. When you go to users management screen and try to sort the users based on id or login columns. Sorting is done in ascending order but icon is showing descending direction and vice versa.  

##### **Motivation for or Use Case**

Icons should properly reflect the direction of the sorting correctly.

##### **Reproduce the error**

Created a new jhipster project from scratch. When you go to users management screen and try to sort the users based on id or login columns. Sorting is done in ascending order but icon is showing descending direction and vice versa.  

This happens with new entities generated as well.

##### **Related issues**

None

##### **Suggest a Fix**

Currently not known.

##### **JHipster Version(s)**

6.4.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "in.gov.hssc.dvscentral",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "monolith",
    "baseName": "dvsCentral",
    "packageName": "in.gov.hssc.dvscentral",
    "packageFolder": "in/gov/hssc/dvscentral",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "cosmo",
    "clientThemeVariant": "dark",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "hi"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v8.10.0

npm: 3.5.2

yeoman: 2.0.4

yarn: 1.7.0

Docker version 18.09.7, build 2d0083d

##### **Browsers and Operating System**

Linux (Ubuntu 18.04) and Chrome

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
I confirm this issue. Thanks for reporting @ashishjmeshram!

I made PR for the fix in the `ng-jhipster` repo: jhipster/ng-jhipster#111
To fix this in the `generator-jhipster` the following steps are needed:
1. merge jhipster/ng-jhipster#111
2. release the new version of the `ng-jhipster`
3. create PR for the `generator-jhipster` repo to use this new version of the `ng-jhipster`
4. merge PR created for `generator-jhipster`

**Comment by pascalgrimaud** [comment]
@kaidohallik : I just did a new release of ng-jhipster v0.11.3

**Comment by kaidohallik** [comment]
@pascalgrimaud thanks, I'm working on PR for generator-jhipster.

**Comment by mansourofski** [comment]
I found the solition,
it is related to the method
  protected fillComponentAttributesFromResponseBody(data: IReferences[] | null): IReferences[] 

change the content of that method to be like this::
  protected fillComponentAttributesFromResponseBody(data: IReferences[] | null): IReferences[] {
    const referencesNew = [];
    if (data) {
      for (const d of data) {
        if (referencesNew.map(op => op.id).indexOf(d.id) === -1) {
          referencesNew.push(d);
        }
      }
    }
    return referencesNew;
  }

and it will work.
enjoy
