### ISSUE TITLE
Add sequence name to PersistentAuditEvent

### ISSUE THREAD

**Issue by alexis-puska** [jhipster/generator-jhipster#10638]
##### **Overview of the feature request**

Add a sequence name to PersistentAuditEvent

##### **Motivation for or Use Case**

When use hibernate envers with jhipster we have conflict between the sequence generated whit default step [50] by PersistentAuditEvent because they have no sequence name. I resolve that with a sequence name on this table, hibernate envers can create a default sequence with step 1 named hibernate_sequence. I think that can resolve some conflict. In best practice, each table have a differente sequence.

##### **Related issues or PR**

-   [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@alexis-puska : thanks for reporting this. It means the sequence name is missing. It looks like to know how to fix it.

Would you like to do a PR for that ?

**Comment by pascalgrimaud** [comment]
As there is no more comment on this, I'm closing this ticket.
Feel free to provide directly a PR to improve this, if you know how to do it.
