### ISSUE TITLE
clientRootfolder option needs a value

### ISSUE THREAD

**Issue by Redouane-Elalami** [jhipster/generator-jhipster#10632]
```
Error: The 'clientRootFolder' option needs a value.
Error while parsing applications and entities from the JDL Error: The 'clientRootFolder' option needs a value.
```
**I want to generate entities by importing a jdl file using : jhipster import-jdl ~/Downloads/jhipster-jdl.jh
It works properly on the gateway , however in the backend side i receive the error described above**

##### **JHipster Version(s)**

v6.4.1 

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
armmory@0.0.0 /Users/red1/IdeaProjects/armmory
└── generator-jhipster@6.4.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.backend.armory",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "microservice",
    "baseName": "",
    "packageName": "com.backend.armory",
    "packageFolder": "com/backend/armory",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly",
      "fr",
      "it",
      "pt-br",
      "es"
    ],
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

git version 2.21.0

node: v10.16.3

npm: 6.9.0

yeoman: 3.1.0

yarn: 1.17.3

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.24.1, build 4667896b

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

entity Discipline {
	disciplineName String required,
    disciplineDescription String,
    disciplinePrice Long
}

entity Program {
	programName String required,
	programDescription String,
    programPrice Long
}

entity Course {
	courseTitle String required,
    courseDescription String,
    coursePrice Long,
    courseLevel Level
}

entity Lesson {
	lessonTitle String required,
	lessonDescription String,
    language Language
}

entity Resource {
	resourceName String,
    resourceDescription String,
    resourceURL String,
    resourcePreviewImage String,
    resourceType ResourceType,
    weight Integer
}

enum Level {
	NOVICE, BEGINNER, INTERMEDIATE, ADVANCED, PROFESSIONAL
}

enum ResourceType {
	VIDEO, IMAGE, TUTORIAL, PAGE, PARTIAL, TOOL 
}

enum Language {
    ENGLISH, SPANISH, HUNGARIAN, GERMAN
}

relationship OneToMany {
	Discipline{resources} to Resource,
	Program{resources} to Resource,
    Course{resources} to Resource,
    Lesson{resources} to Resource
}

relationship ManyToMany {
	Discipline{programs} to Program{disciplines},
    Program{courses} to Course{programs},
	Course{lessons} to Lesson{courses}
}

// Set pagination options
paginate Lesson with infinite-scroll
paginate Program, Course with pagination

dto * with mapstruct

// Set service options to all except few
service all with serviceImpl /*except Program, Course*/

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
That's weird, I don't see any `clientRootFolder` option in your JDL. I'll try to reproduce though.

**Comment by MathieuAA** [comment]
By the way, there's an error in your JDL, the last line is invalid.
It should be `service all with serviceImpl except Program, Course`

**Comment by MathieuAA** [comment]
Okay, check your .yo-rc.json file, the `baseName` option isn't set, which cause this issue because when parsing the JDL, if your app is a microservice, the `clientRootFolder` option is the MS name (see https://github.com/jhipster/jhipster-core/issues/252)
