### ISSUE TITLE
current swagger-springmvc v0.8.8 adds unnecessary scala (extra 7MB size) dependency to war/jar 

### ISSUE THREAD

**Issue by aldas** [jhipster/generator-jhipster#1064]
gradle.properties has swagger_springmvc_version=0.8.8 this version of swagger has eventually dependcy to "org.scala-lang:scala-library:2.10.0" which is ~7MB. This is unnecessary according to https://github.com/json4s/json4s/issues/108 

```
+--- com.mangofactory:swagger-springmvc:0.8.8
|    +--- com.wordnik:swagger-core_2.10:1.3.5
|    |    +--- commons-lang:commons-lang:2.4 -> 2.6
|    |    +--- org.slf4j:slf4j-api:1.6.3 -> 1.7.7
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.1.5 -> 2.4.0
|    |    +--- com.fasterxml.jackson.module:jackson-module-jsonSchema:2.1.0
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.1.0 -> 2.4.4 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.1.0 -> 2.4.4
|    |    |    \--- com.fasterxml.jackson.core:jackson-annotations:2.1.0 -> 2.4.0
|    |    +--- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.0.0
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.0.0 -> 2.4.4
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.0.0 -> 2.4.4 (*)
|    |    |    +--- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.0.0
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.0.0 -> 2.4.4
|    |    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.0.0 -> 2.4.4 (*)
|    |    |    \--- javax.ws.rs:jsr311-api:1.1.1
|    |    +--- com.wordnik:swagger-annotations:1.3.5
|    |    +--- org.json4s:json4s-ext_2.10:3.2.5
|    |    |    +--- org.scala-lang:scala-library:2.10.0
```

maybe swagger springmvc version should/could be pumped to 0.9.x series?

**Comment by aldas** [comment]
this way war size drops from 42MB to 35MB

**Comment by atomfrede** [comment]
@aldas Have you excluded ``scala-library`` from ``swagger-springmvc`` dependency? I tried it and get ``com/wordnik/swagger/model/ApiInfo.class): warning: Cannot find annotation method 'bytes()' in type 'ScalaSignature': class file for scala.reflect.ScalaSignature not found``

Nevertheless compilation succeeds, but there are test failures (a lot of ``ClassNotFoundException``). Using the latest 0.9.x doesn't work either for me here as ``ApiInfo`` is not available anymore. So it looks like ``scala-library`` is required right now.

@jdubois The maven build should add ``scala-library`` too (as it not excluded), is that correct?

**Comment by aldas** [comment]
I think "ApiInfo" has been moved to different package in 0.9.x.  I tried excluding various scala things in gradle but eventually changed swagger version as someday I need to upgrade it anyway. 

As I recall all I needed to get things working was to use ```
import com.mangofactory.swagger.models.dto.ApiInfo;``` import.

**Comment by aldas** [comment]
I think that from swagger 0.9.5 (commit https://github.com/martypitt/swagger-springmvc/commit/e426cd18cfc1a4181ae1fdf17d5810ae6121b022#diff-763c874365a7bc898858eaa1aeee307a )  ```com.wordnik.swagger.model.ApiInfo;``` was removed and replaced with ```com.mangofactory.swagger.models.dto.ApiInfo;``` class

**Comment by atomfrede** [comment]
Ah thanks, IDEA didn't pick up the change in my gradle file correctly, so I couldn't quick-fix the changed package. I'll provide a pull request during the weekend for both maven and gradle as it reduces the size of war file ~ 10MB (59mb before, now 49mb).

**Comment by kumaresanperumal5666** [comment]
thanks
