### ISSUE TITLE
User email inconsistencies.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#10646]
##### **Overview of the issue**

When creating new user, the email field is causing some problems.

1. When email is not set an 'Internal server error.' is shown.
https://github.com/jhipster/generator-jhipster/blob/7e8eb98a14d97a3a2e608eb6e4c2e93cd3358f96/generators/server/templates/src/main/java/package/service/UserService.java.ejs#L356

2. When email is set then deleted, a 'does not meet min/max size requirements!' is shown.
https://github.com/jhipster/generator-jhipster/blob/7e8eb98a14d97a3a2e608eb6e4c2e93cd3358f96/generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.ts.ejs#L47

On initial_schema.xml.ejs email is unique and nullable.
https://github.com/jhipster/generator-jhipster/blob/7e8eb98a14d97a3a2e608eb6e4c2e93cd3358f96/generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs#L60-L62

Is email is unique, why don't make it not null?

##### **Suggest a Fix**

Make email nullable=false or fix validation and service.

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
I can provide a patch, but need to know if I should make email nullable == false or fix ui validation and service.

**Comment by ruddell** [comment]
I believe the original reason for allowing null emails was for social login. Twitter did not provide the email upon login (https://github.com/jhipster/generator-jhipster/pull/3538).  Social login was removed before v5 so think we can revert those changes.  

One thing to verify is whether or not Keycloak/Okta users always have an email address, as we sync those users to the JHipster app's database.

**Comment by mshima** [comment]
> One thing to verify is whether or not Keycloak/Okta users always have an email address, as we sync those users to the JHipster app's database.

Didn't found this information, but looks like email is not required, so I've done some validations for null emails.

Let me know if we should make email required.

**Comment by MathieuAA** [comment]
Perhaps @mraible can help shed some light here.
> One thing to verify is whether or not Keycloak/Okta users always have an email address, as we sync those users to the JHipster app's database.

**Comment by mraible** [comment]
Okta users will always have an email address. I'm not sure about Keycloak since we pre-populate that with `admin` and `user` users, which aren't really tied to a person.
