### ISSUE TITLE
Wrong translation for not found entities in spanish

### ISSUE THREAD

**Issue by EnmanuelReyes** [jhipster/generator-jhipster#10652]
##### **Overview of the issue**

Wrong translation in spanish for not found entities.

##### **Motivation for or Use Case**

For a entity called **Person**:

It should say: Ningún `Person` encontrado
Instead of 'No `Person` found'

##### **Reproduce the error**

Generate a monolithic application, select a database, select a client framework (I used Angular), then generate an entity using the command `jhipster entity Person` without any fields or relationships.

##### **Related issues**

I think this doesn't apply.

##### **Suggest a Fix**

The line that should be modified is:
https://github.com/jhipster/generator-jhipster/blob/ec309349781af15fe0c13105c864c3567eff25a8/generators/entity-i18n/templates/i18n/entity_es.json.ejs#L28

I can do it myself, but I need some kind of approval.

##### **JHipster Version(s)**

```
my-app@0.0.1-SNAPSHOT /Users/enmanuelreyes/Documents/Software/hacktoberfest/myApp
└── generator-jhipster@6.4.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "monolith",
    "baseName": "myApp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es"
    ],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Person

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.10.1

node: v10.15.3

npm: 6.4.1

yeoman: 3.1.0

yarn: 1.12.3

Docker version 19.03.1, build 74b1e89

docker-compose version 1.24.1, build 4667896b

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Person.json

{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [],
    "fields": [],
    "changelogDate": "20191020161629",
    "dto": "no",
    "searchEngine": false,
    "service": "no",
    "entityTableName": "person",
    "databaseType": "sql",
    "jpaMetamodelFiltering": false,
    "pagination": "no"
}
##### **Browsers and Operating System**

Mac OS Mojave (10.14.6)

-   [ ✔️] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Thanks for reporting @EnmanuelReyes. Can you please do a PR?

**Comment by EnmanuelReyes** [comment]
Of course!
Already on it.
