### ISSUE TITLE
Update Mysql dialect to 8.0

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#10653]
##### **Overview of the feature request**

This is not a feature request but rather a question regarding mysql dialect should be updated or not.
While working on #10650 with mysql database, I got a MAJOR warning message as following.

```
MAJOR - DialectVersionEvent - Your application is using the 
[org.hibernate.dialect.MySQL5InnoDBDialect] Hibernate-specific Dialect. Consider using the 
[org.hibernate.dialect.MySQL57Dialect] instead as it's closer to your current database server version 
[MySQL 8.0]. For more info about this event, check out this User Guide link - 
https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/#DialectVersionEvent
```
While I can update to `MySQL57Dialect `, it seems there is a new dialect available `org.hibernate.dialect.MySQL8Dialect` for our current hibernate version 5.3.x.

But before updating to either, I was wondering how many people are still on mysql db server 5.x.x.
I was not thinking to upgrade to `org.hibernate.dialect.MySQL8Dialect` but since we already have mysql docker image version 8.0.17, what do you think @jhipster/developers ?

Mysql 8.0 was out in Apr, 2018. https://www.mysql.com/news-and-events/
##### **Motivation for or Use Case**

Have the latest dialect version.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
yes, let's upgrade and document the change for user who uses old version of MySQL
