### ISSUE TITLE
Update All Daily Build OS to Ubuntu 18.04

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10662]
##### **Overview of the issue**

This was inspired from the following thread; https://github.com/hipster-labs/jhipster-daily-builds/pull/25. I think we should consider upgrading all daily builds to Ubuntu 18.04 (i.e: ubuntu-latest) image. 

If this is in agreement I can do a pull request. :smile: 

##### **Motivation for or Use Case**

We had some success with https://github.com/hipster-labs/jhipster-daily-builds/pull/25 after upgrading to Ubuntu 18.04 and I also think we should make all the builds consistent. Given that we user `ubuntu-latest` on our Github CI, I think it makes sense to upgrade. 

##### **Suggest a Fix**

Upgrade all `vmImage` tags to `ubuntu-latest`

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
agree, we should use Ubuntu LTS

**Comment by pmverma** [comment]
@pascalgrimaud I also would like to have a schedule for Windows which is already available in daily-build. I know the build was not stable but it would be better to enable and watch.

**Comment by SudharakaP** [comment]
@pmverma : Agreed. 

I can do this as part of this as well if you guys are okay with it. What specific configuration shall we use. How about a basic monolith with all the defaults? Or do you have a different specification in mind? 😄

**Comment by pmverma** [comment]
Sorry for confusing you. I meant to have a schedule under daily-build, not the main generator build.
We already have a Windows pipeline at https://github.com/hipster-labs/jhipster-daily-builds/blob/master/azure-template-windows.yml
I think @pascalgrimaud has the permission to configure the azure pipeline.

Notes:
Unfortunately writing PowerShell or batch script using yml was a hell and I finally decided to use the git bash to run the script in the pipeline.
So you will see minimal to no difference between the Linux and windows pipeline.

**Comment by SudharakaP** [comment]
@pmverma : Ah, no problem. Got it; thanks for the info 😄

**Comment by SudharakaP** [comment]
I've created the pull request to upgrade all pipelines; let me know if you see any issues. I'll monitor this for sometime to see if everything works as expected. :smile:

**Comment by SudharakaP** [comment]
I've missed one step in my previous PR. We have to upgrade the ChromeDriver as well since the default ChromeDriver seems not compatible with Chrome 78 which we install in the build scripts. I've created a new PR for this one. :smile:

@pascalgrimaud : Could we restart all builds to check if everything works as expected after we merge https://github.com/hipster-labs/jhipster-daily-builds/pull/29 and https://github.com/jhipster/generator-jhipster/pull/10673 ?
