### ISSUE TITLE
ci-cd support circleci

### ISSUE THREAD

**Issue by amirdt22** [jhipster/generator-jhipster#10671]
##### **Overview of the feature request**

Support generation of circle-ci config in the ci-cd generator

##### **Motivation for or Use Case**

Travis has been giving us a lot of trouble and we've migrated to CircleCi in our other projects.

##### **Related issues or PR**

#7192
It seems this was once supported on the older 1.0 format.  That issue references a [generator](https://github.com/jeantsai/generator-jhipster-circleci-2) but I'm not sure it's still supported, last commit was 2 years ago and it [doesn't seem to be working](https://github.com/jeantsai/generator-jhipster-circleci-2/issues/1)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
@amirdt22 You are right we removed circle ci as no one wanted to migrate to 2.0 format of circle ci. https://github.com/jhipster/generator-jhipster/issues/9957#issuecomment-504333759

If you are willing to create and maintain circle ci your are welcome to add it again supporting the 2.0 as you seem to have experience with it.

**Comment by pascalgrimaud** [comment]
Yes, I removed it because no one wanted to do the migration to 2.0 format, and CircleCI deprecated the format 1.0.

So you're welcome to do a PR to add back the support ;)

**Comment by amirdt22** [comment]
Perfect, will get it started on my project and find some time to back it in to the generator!

**Comment by SudharakaP** [comment]
@amirdt22 : Are you still on this? I can add this one back if you'd like :smile:

**Comment by oseferi** [comment]
@amirdt22 hi, did have you had any progress on the generator? I am trying to setup circle ci with my app, so i stumbled upon this issue.

**Comment by pascalgrimaud** [comment]
No work has been done since 4 months, so I suppose no one want to contribute to this ? Then, I'm closing this for lack of interest.
Feel free to contribute and maintain Circle CI if you like it.
If I remember well, I saw a module for that too...

**Comment by SudharakaP** [comment]
@pascalgrimaud : I was waiting for @amirdt22's reply above since he was assigned to the issue. :smile:  But I can take this issue and support circle ci if there's enough demand for it. WDYT?

**Comment by pascalgrimaud** [comment]
@SudharakaP : yes if you think it deserves, go ahead

**Comment by amirdt22** [comment]
Apologies @SudharakaP - I wasn't able to get to this.  We are using CircleCI but don't think our solution for our project is portable currently.

**Comment by SudharakaP** [comment]
@amirdt22 : Hey, no problem. I started working on this tody. Hopefully we can support circle-ci 2.0 quite soon. 😄

**Comment by pascalgrimaud** [comment]
no worry, @amirdt22 I can understand you didn't have time. But maybe you can review once it's done by @SudharakaP ?
