### ISSUE TITLE
Keys containing dots are not translated in a react application

### ISSUE THREAD

**Issue by SoniaLahi** [jhipster/generator-jhipster#10678]
##### **Overview of the issue**

The react application can't translate a key if it contains several `.`, such as : `url.not.found`.
Keys with a single `.` are found only if their value is a string.

Example, in global.json : 
```javascript
"global" : {
  "form": {
    "username.label": "Username", // is found
     "any.nested" : {
        "label" : "Anything" // is not found
      }
  },
  "error" : {
    "url.not.found": "Not found",  // is not found
    "url.not.found": { 
      "label": "Not found",  // is not found
    }
  },
}
```

##### **Motivation for or Use Case**

the error message is not translated. 
![translation-not-found](https://user-images.githubusercontent.com/5923781/67489018-1d9bd500-f671-11e9-910f-86f06e121914.png)

##### **Reproduce the error**

1. log in
2. get an entity that does not exist (e.g : http://localhost:9000/entity/subtitle/30)
3. a toaster with the translation-not-found pops in

##### **Suggest a Fix**

Should it be fixed by changing the react-jhipster library or should it be considered not using dots in json keys ?
##### **JHipster configuration**

INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT /home/tinubu.local/slahcene.ext/dev/contrib-jhipster/translation-not-found-dot
└── generator-jhipster@6.4.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Subtitle {
  name String,
  language Language
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

git version 2.20.1

node: v13.0.1

npm: 6.12.0

yeoman: 3.1.0

yarn: 1.15.2

Docker version 19.03.2, build 6a30dfca03

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I remember seeing something similar in Blueprint Vue.js

See this line https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/templates/vue/src/main/webapp/app/account/login-form/login-form.vue.ejs#L11

Something like that:
`$t('global.form[\'username.label\']')`

Not sure, maybe it's not related but we can give a try

**Comment by atomfrede** [comment]
It really depends, I wonder if it works in angular, as the translations will become a json object having a key with dots inside could be interepreted as accessing `key.value`
```json
{
 key {
  value: "TEST"
 }
}
```

or `{ key.value }`. For example mongo db (without using spring data special key mapper) does not allow dots in keys for the very same reason.

**Comment by pascalgrimaud** [comment]
Just give a quick try, and I can confirm the issue

**Comment by pascalgrimaud** [comment]
Adding a bounty on this, as it's a bug

**Comment by qmonmert** [comment]
@pascalgrimaud I'm working on this bug, I'll do a PR on the https://github.com/jhipster/react-jhipster lib

**Comment by qmonmert** [comment]
@pascalgrimaud PR on the lib https://github.com/jhipster/react-jhipster/pull/38

**Comment by qmonmert** [comment]
I claim my money :) https://opencollective.com/generator-jhipster/expenses/12457

**Comment by pascalgrimaud** [comment]
we can close it, it will be in the next release of react-jhipster
Thanks @qmonmert

**Comment by qmonmert** [comment]
Thanks @pascalgrimaud happy to help :)
