### ISSUE TITLE
autoIncrement variable in initial_schema.xml is not defined for Postgres

### ISSUE THREAD

**Issue by ersinciftci** [jhipster/generator-jhipster#10684]
##### **Overview of the issue**

I created a microservice and selected Postgres as database type. It created `00000000000000_initial_schema.xml` file and it refers to a `${autoIncrement}` in the xml twice, but that variable is not defined anywhere. I looked at the `initial_schema.xml.ejs` file in JHipster source code and it seems like it creates the `autoIncrement` property only for MySQL and MariaDB:

```
<%_ if (prodDatabaseType === 'mysql' || prodDatabaseType === 'mariadb') { _%>
    <property name="autoIncrement" value="true"/>
<%_ } _%>
```

But it still refers to `${autoIncrement}` for microservices using Postgres. It doesn't cause an error but it's confusing. Am I missing something? 
##### **Reproduce the error**

Create a microservice and select Postgres as the database type.

##### **JHipster Version(s)**

6.3.1

##### **JHipster configuration**

<details><summary>jhipster info</summary>
<p>
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
oct-25-eclx-3@0.0.0 /Users/eciftci/workspace/oct25eclx3
└── generator-jhipster@6.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "microservice",
    "baseName": "oct25eclx3",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "embeddableLaunchScript": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.21.0

node: v12.1.0

npm: 6.9.0

yeoman: 3.1.0

yarn: 1.15.2

Docker version 19.03.4, build 9013bf5

docker-compose version 1.24.1, build 4667896b
</p>
</details>

##### **Browsers and Operating System**
MacOS Catalina

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
It looks like you know how to fix it.
@ersinciftci : would you like to contribute and do a PR for that ?

**Comment by ersinciftci** [comment]
@pascalgrimaud Sure, just to make sure, in both `initial_schema.xml.ejs` and `added_entity.xml.ejs`, I'll add `|| prodDatabaseType === 'postgresql'` to the existing `prodDatabaseType === 'mysql' || prodDatabaseType === 'mariadb'` condition to add `autoIncrement` property for Postgres?

**Comment by pascalgrimaud** [comment]
@ersinciftci : I didn't look in details, but yes, I think it's the correct fix. Then I still don't understand why it doesn't cause an error because of this missing property

**Comment by ctamisier** [comment]
I think for postgres a sequence is used. So I'm not sure we should use autoIncrement=true for postgres. Maybe setting it to false will be less confusing indeed.
Probably if the variable is not defined it is considered as false by liquibase ?

**Comment by ersinciftci** [comment]
Hmm, so maybe I need to do the opposite in my PR, instead of creating the property for Postgres, we shouldn't use `${autoIncrement} ` property for Postgres.

**Comment by ctamisier** [comment]
Exactly, `${autoIncrement}` shouldn't appear in the liquibase file for postgres and the result should be the same.

**Comment by 40rn05lyv** [comment]
The same issue with H2 database (file-based). Liquibase references 

    <column name="id" type="bigint" autoIncrement="${autoIncrement}">

But `autoIncrement` is not defined anywhere. New entities also have this `autoIncrement` property, but they actually use `sequenceGenerator`.

**Comment by pmverma** [comment]
As per liquibase doc, autoincrement will be ignored on DBs which don't support it.
https://www.liquibase.org/documentation/column.html

But I think to have a false value rather than true for DBs other than mysql/mariadb.

**Comment by ersinciftci** [comment]
If it's ignored on databases that do not support auto increment, maybe the `<column/>` tag shouldn't have `autoIncrement="${autoIncrement}"` attribute at all for Postgres, instead of having it set to `false`? It seems like it's not a mandatory attribute.

**Comment by pmverma** [comment]
That would be best if removed as it also removes the developer confusion when sequence-based DB is used.
Would you be able to do this in the current PR?
