### ISSUE TITLE
Generate Full Auth Config For Back End

### ISSUE THREAD

**Issue by patrickjp93** [jhipster/generator-jhipster#10689]
##### **Overview of the feature request**
When creating a new application, the authentication handler for the back end can be generated completely given any relevant URIs or filters.

Ex: The LDAP integration example on the main site can be generated at the time of creation. Much of the Auth Handler boilerplate is already generated when selecting OAuth2, so it should be possible for other cases.

https://www.jhipster.tech/tips/016_tip_ldap_authentication.html

So in the generator, we can add Auth handler options for LDAP and others, and the relevant code in the Security Configuration and overrided AuthenticationManager--as well as the fields in the yml/properties files--will be generated with the project.

##### **Motivation for or Use Case**
Security is hard, particularly for under-resourced teams in corporate IT, and can sometimes be a key hurdle in getting projects over the line. To improve JHipster adoption rates, quick turnaround time from Project Generation to Integration with existing software stacks at a company goes a long way in convincing managers and senior engineers to use the technology, especially if the "best practices" are already baked into the base implementation.

Generating auth implementations aligned to examples already provided on the main site shouldn't be stepping on any toes when it's already done for OAuth2. 

##### **Related issues or PR**
I didn't find a previous request for this sort of feature.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@patrickjp93 : thanks for the proposal. I think this tips https://www.jhipster.tech/tips/016_tip_ldap_authentication.html can go into a module. Are you motivated enough to start your own module and maintain it ?

You can have a look at our page about module: https://www.jhipster.tech/modules/creating-a-module/

Then if your modul  is really popular, then we can reconsider to include it to the main generator

**Comment by patrickjp93** [comment]
Hi Pascal, I do have a little bit of spare time these days. Do you guys have a "Getting started writing JH Modules" page or documentation I can reference, or else a good repo history to use as a guide? Code generators are not my forte'.

**Comment by pascalgrimaud** [comment]
@patrickjp93 : sorry for the late answer, I was busy the last days.

Before creating a module or blueprint, I suggest you to:
- create a sample JHipster project
- apply the change you want, ideally in 1 commit

Then, study the diff with git, and try to transform it into a module:
- read https://www.jhipster.tech/modules/creating-a-module/#-creating-a-module
- use https://github.com/jhipster/generator-jhipster-module to generate your own module
- you'll need to change some function or use master branch, or wait a new release of the module, as last release contain some old functions which doesn't work with JHipster 6
- code the change in your module
- try and test your module in an existing jhipster project
- try another config like Gradle, React, Microservives etc
- once everything is ok, you can launch npm publish, for releasing your module
- don't hesitate to tweet it

You can have a look at our Marketplace, you'll find other module and you can do similar change. It will help you a lot.

**Comment by pascalgrimaud** [comment]
I think we can close this, as it can / should go to module.
Don't hesitate to comment this ticket if needed
