### ISSUE TITLE
SpringDataWebProperties is not used for swagger auto configuration

### ISSUE THREAD

**Issue by Blackdread** [jhipster/generator-jhipster#10694]
##### **Overview of the issue**
Hard-coded values in [PageableParameterBuilderPlugin](https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/config/apidoc/PageableParameterBuilderPlugin.java)
Hard-coded: size-parameter, page-parameter, one indexed or not, default-page-size, etc

##### **Motivation for or Use Case**
Add better doc in swagger ui by specifying default page size, actual param name to use, etc

So users who generate jhipster app do not need to customize this part if they want this functionality.

##### **Suggest a Fix**
Add org.springframework.boot.autoconfigure.data.web.SpringDataWebProperties in auto configuration.

```
@Bean
@ConditionalOnMissingBean
public PageableParameterBuilderPlugin pageableParameterBuilderPlugin(TypeNameExtractor typeNameExtractor,
                                                                             TypeResolver typeResolver,
                                                                             SpringDataWebProperties springDataWebProperties) {
       return new PageableParameterBuilderPlugin(typeNameExtractor, typeResolver, springDataWebProperties);
}
```

then in  [PageableParameterBuilderPlugin](https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/config/apidoc/PageableParameterBuilderPlugin.java) use properties to set values.

Use in `ParameterBuilder` the `defaultValue` to set actual default value for page, size.

Can also support to display default values for page,size and sort via use of PageableDefault, SortDefault, SortDefault.SortDefaults but this requires more customization of the plugin.

_Documentation can also say which sort param name are supported but this is a custom annotation I have and plugin resolves the annotation in controllers at runtime so swagger can also display allowed sort params._ => not part of this issue since it is really custom annotation I have created.

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@Blackdread Any chance you can contribute a pull request to fix this? I've added a bug bounty for motivation. :)

**Comment by DanielFran** [comment]
Those classes do not exist anymore so that we can close this issue
