### ISSUE TITLE
K8s Knative generator (k8s-knative)

### ISSUE THREAD

**Issue by srinivasa-vasu** [jhipster/generator-jhipster#10695]
##### **Overview of the feature request**
Knative integration

##### **Motivation for or Use Case**
Provide `k8s-knative` as a separate generator to integrate Knative constructs with the deployment manifest. This can leverage the existing `k8s`/ `helm` generator for other common & cross-cutting services. In the future, we can also explore options like cloud-native buildpacks (kpack), kf and other options for direct source to oci compliant image conversion.

@saturnism and I had a chat during SpringOne and thought of adding this new feature.

##### **Related issues or PR**
None

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/10773 as it has been merged manually
