### ISSUE TITLE
Oracle : Docker-compose issue in version 6.3.1

### ISSUE THREAD

**Issue by e-from** [jhipster/generator-jhipster#10708]
##### **Overview of the issue**

I used JHipster to create a microservices gateway with Oracle as the database.  I then made sure the gateway was accessible by running the jhipster registry and running  "npm install" and then "mvn" and "npm start" in the gateway app directory and verified gateway accessibility in browser.  I then shut down the registry and gateway and create a docker-compose directory in application base directory.   I then run jhipster docker-compose and after answering the questions (and selecting the gateway application to include in the docker compose configuration) I get error below:

ERROR! Error: *****/src/main/docker/oracle.yml doesn't exist

Older versions of the JHipster generator used to create oracle.yml but newer ones no longer do, yet the docker-compose sub generators still looks for the file.

##### **Motivation for or Use Case**

Docker compose is important

##### **Reproduce the error**

-run jhipster and create a microservices gateway with Oracle as the database.  
-make sure the gateway was accessible by running the jhipster registry and running  "npm install" and then "mvn" and "npm start" and verify gateway accessibility in browser.  
-shut down the registry and gateway 
-create a docker-compose directory in application base directory.  
-run jhipster docker-compose and answer the questions (select the gateway application to include in the docker compose configuration)
- get error below:

ERROR! Error: *****/src/main/docker/oracle.yml doesn't exist

##### **JHipster Version(s)**

6.3.1 

##### **JHipster Version(s)**

```
gateway@0.0.1-SNAPSHOT C:\Users\***\Projects\TestProject\gateway
`-- generator-jhipster@6.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.org.test"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.org.test",
    "packageFolder": "com/org/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "<<<removed>>>",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

git version 2.22.0.windows.1

node: v10.16.0

npm: 6.9.0

yarn: 1.16.0

Docker version 19.03.4, build 9013bf5

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!
If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
     JDL content here
  </pre>
  </details>
-->

##### **Browsers and Operating System**

Windows 10, all browsers

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
The problem comes from Oracle docker-compose files, which was removed few months ago:
https://github.com/jhipster/generator-jhipster/commit/93f41f66cbc17d7c0400009430ea3e3a4434528f

As we don't have this file anymore, it's normal the docker-compose sub generator doesn't work with Oracle.

Not sure we can do something on our side as the error you have is probably enough

**Comment by e-from** [comment]
Can Docker-compose have a command-line parameter to skip database configuration?
