### ISSUE TITLE
Relationships with User in OAuth2 app broken on master

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#10700]
##### **Overview of the issue**

Ionic for JHipster tests against the master branch for CI. It stopped passing recently because of an error in the entity generator.

https://travis-ci.org/oktadeveloper/generator-jhipster-ionic/jobs/604144898#L2440

```
[ERROR] /home/travis/backend/src/test/java/io/github/jhipster/travis/domain/BlogTest.java:[14,47] incompatible types: java.lang.String cannot be converted to java.lang.Long
[ERROR] /home/travis/backend/src/test/java/io/github/jhipster/travis/domain/BlogTest.java:[18,47] incompatible types: java.lang.String cannot be converted to java.lang.Long
```

##### **Motivation for or Use Case**

This was working fine a couple days ago. I'm guessing it's related to [this commit](https://github.com/jhipster/generator-jhipster/commit/03abdc12ec7ce340d788454f1d18ebaff1bf06a1) since failures started happening [today](https://travis-ci.org/oktadeveloper/generator-jhipster-ionic/builds).

##### **Reproduce the error**

Create a new JHipster app with the following `.yo-rc.json`:

```json
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.okta.developer",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "6.3.1",
        "baseName": "backend",
        "reactive": false,
        "packageName": "com.okta.developer",
        "packageFolder": "com/okta/developer",
        "serverPort": "8080",
        "authenticationType": "oauth2",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "clientFramework": "angular",
        "useSass": false,
        "clientPackageManager": "yarn",
        "applicationType": "monolith",
        "testFrameworks": [
            "protractor"
        ],
        "jhiPrefix": "jhi",
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": [
            "en"
        ]
    }
}
```

Then create entities using the following JDL:

```
entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll
```

##### **JHipster Version(s)**

master branch

**Comment by pascalgrimaud** [comment]
Indeed, I could reproduce it.
Then I don't understand why the CI didn't detect it.

@stonedMoose : can you have a look on this issue you introduced plz ?

**Comment by pascalgrimaud** [comment]
It only affects relationships with User in OAuth2 app.
I got the fix, currently testing it and will submit a PR soon

**Comment by stonedMoose** [comment]
Sorry I just saw your message.

It strange indeed that the pipeline did not detect it but fails afterwards... Are the pipelines on master and on branches the same ?

**Comment by pascalgrimaud** [comment]
@stonedMoose : no worry, don't be sorry :)
It is fixed now. 

The CI didn't detect it because we don't have tests for relationships with User in OAuth2 app
