### ISSUE TITLE
JDL with Regex Patterns and E2E Tests

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10704]
##### **Overview of the issue**

Currently we don't take into account regex patterns when it comes to our auto generation of e2e tests. This causes auto generated e2e tests to fail if a user has a JDL with regex patterns. For example this is one of the causes for the failure in our [daily keycloak builds](https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=34&_a=summary). 

Is this something we should cover in our e2e tests? :thinking: 

##### **Motivation for or Use Case**

Getting the default E2E tests pass. 

##### **Reproduce the error**

Create a simple project with a JDL field including a regex pattern (example JDL given below)

##### **Related issues**

#10604

##### **Suggest a Fix**

We can probably create automated e2e test generation for regex with the help of http://fent.github.io/randexp.js/#r=sun%7Cmon

##### **JHipster Version(s)**

6.4.1

##### **JHipster configuration**
  <details>
  <summary>JDL definitions</summary>
  <pre>
entity Customer {
    firstName String required
    lastName String required
    email String required pattern(/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/)
    phone String required
    addressLine1 String required
    addressLine2 String
    city String required
    country String required
}
  </pre>
  </details>

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@pascalgrimaud : Yes for some reason we do run protractor tests on Keycloak builds and with a JDL ([microservice-demo.jdl](https://github.com/hipster-labs/jhipster-daily-builds/blob/master/test-integration/jdl-samples/templates/microservice-demo.jdl.ejs)) that has this kind of regex. Do you think we should remove running e2e on Key-cloak as well? :thinking: 

On another note, I am not sure if we can guarantee that the e2e tests will work for all sorts of user generated JDLs since there might be other corner cases as well; which I think is a bigger topic :smile:

**Comment by pascalgrimaud** [comment]
mhhh the regex works well for other configs, but it failed only for Keycloak. Do you know why ?

**Comment by SudharakaP** [comment]
@pascalgrimaud : Are you sure? Maybe I am seeing this wrong, but I don't see that JDL file being executed for any other daily build. Can you refer me to an example that works with that JDL?

**Comment by pascalgrimaud** [comment]
@SudharakaP :
- JDLMs.Redis.MariaDB : https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=6907
- in `jhipster info`, I can see:

```
entity Customer {
  firstName String required,
  lastName String required,
  gender Gender required,
  email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
  phone String required,
  addressLine1 String required,
  addressLine2 String,
  city String required,
  country String required
}
```

**Comment by SudharakaP** [comment]
Just to give a heads up, I am working on this issue; although in my previous attempt, I couldn't get `randexp` working correctly; I'll try again 😄
