### ISSUE TITLE
jhipster-ldap-integration

### ISSUE THREAD

**Issue by issovic** [jhipster/generator-jhipster#10716]
Hey JHipsters  i want to link my Jhipster application to LDAP server and trying to use also the user authorities which is not available in the ldap server . t tried to follow https://www.jhipster.tech/tips/016_tip_ldap_authentication.html#ldap-authentication but it didnt work. always showing error **bad credentials** even the same username/password working on any other LDAP client . i can't share the CN here public because it's private but i can email you if you wanted to check it with me . is LDAP working fine with you ?

**Comment by pascalgrimaud** [comment]
The tips are proposed by our users, the core team didn't maintain it and didn't check if it works well.

So once you resolve your issue, @issovic, don't hesitate to update the tips if needed.

**Comment by issovic** [comment]
@pascalgrimaud thanks for awnsering me, well i just resolved the issue by adding a new function that try to authenticate a user to the active directory with simple method, 
i conserved the default project authentifcate manager and i just used jhipster user detail to load profils, it's a tricky was that i did, i just test ldap connection withth user/password if it works and before i generate JWT token, i search for the user with his login into my JHI_USER, if i found it, i change his password to ldap one and generate token, else if the user was not found but still ldap isauthorized, i create new user with the password in parameter and last one if the user was not authorized in ldap i just return empty JWT .
it's a tricky was but i hope we can improve it but creating and transforming it into customAuthentifcateManager .
 i added new file LdapService containing this function

	public boolean authorize(String userName,String password) {
		try {
			
			log.info("Authorizing active directory ldap ....");

			userName="dc\\"+userName;
			Hashtable<String, String> ldapEnv = new Hashtable<String, String>(11);
			ldapEnv.put(Context.INITIAL_CONTEXT_FACTORY, initialContextFactury);
			// ldapEnv.put(Context.PROVIDER_URL, "ldap://societe.fr:389");
			ldapEnv.put(Context.PROVIDER_URL, providerUrl);
			ldapEnv.put(Context.SECURITY_AUTHENTICATION, securityAuthentification);
			// ldapEnv.put(Context.SECURITY_PRINCIPAL,
			// "cn=administrateur,cn=users,dc=societe,dc=fr");
			ldapEnv.put(Context.SECURITY_PRINCIPAL, userName);
			ldapEnv.put(Context.SECURITY_CREDENTIALS, password);
			// ldapEnv.put(Context.SECURITY_PROTOCOL, "ssl");
			// ldapEnv.put(Context.SECURITY_PROTOCOL, "simple");
			ldapContext = new InitialDirContext(ldapEnv);
			log.info("connected");
		      ldapContext.close();
			return true;
		} catch (Exception e) {
			log.error(e.getMessage());
		}
		return false;
	}

**Comment by patrickjp93** [comment]
See this goes down the vein of what I suggested in [Generate Full Auth Config For Back End](https://github.com/jhipster/generator-jhipster/issues/10689)

That said, this code would be cleaned up a bit with anonymous initialization and some structured programming. For our own deployment using Spring LDAP, we had some more complex security logging and other exception handling that integrated with Splunk and other central monitoring tools, so having multiple returns was a headache to read.

Also, your code can have an exception cancel authentication even after it has succeeded in Active Directory. The below is a bit more resilient against secondary exceptions

> public boolean authenticate(String userName,String password) {
        log.info("Authorizing active directory ldap ....");
        boolean result = false;

        userName=userDomain+"\\"+userName; //better for multi-environment deployments
	Hashtable<String, String> ldapEnv = new Hashtable<>(6) {
            { put(Context.INITIAL_CONTEXT_FACTORY, initialContextFactory); }
            { put(Context.PROVIDER_URL, providerUrl); }
            { put(Context.SECURITY_AUTHENTICATION, securityAuthentication); }
            { put(Context.SECURITY_PRINCIPAL, userName); }
            { put(Context.SECURITY_CREDENTIALS, password); }
            { put(Context.SECURITY_PROTOCOL, "ssl"); } //ssl should be default for security
        };

	try {
		ldapContext = new InitialDirContext(ldapEnv);
                result = true;
                log.info("connected");
                //setUserAuthoritiesByADGroups(ldapContext);
		//setUserAuthoritiesByPermissions();
	        ldapContext.close();
	} catch (Exception e) { 
            log.error(e.getMessage()); 
        }
	return result;
    }

**Comment by pascalgrimaud** [comment]
@issovic @patrickjp93 : can one of you update this page plz https://www.jhipster.tech/tips/016_tip_ldap_authentication.html ?

If you don't want or don't have time, no problem. I'll simply delete this tips.

**Comment by patrickjp93** [comment]
@pascalgrimaud I'm actually brand new to the community and don't have access to much of anything. Happy to do the grunt work if someone can point me in the right direction to get set up.

**Comment by pascalgrimaud** [comment]
@patrickjp93 : to contribute to the documentation, just follow these steps
- fork this project in GitHub: https://github.com/jhipster/jhipster.github.io
- clone your fork locally: `git clone https://github.com/patrickjp93/jhipster.github.io`
- go into your fork: `cd jhipster.github.io`
- create a new branch, for example: `git checkout -b update-ldap-tips`
- edit this file: `016_tip_ldap_authentication.md`
- if you have docker-compose in your computer, you can start Jekyll and test if it's fine: `docker-compose up` and go to `http://0.0.0.0:4000` -> not mandatory, we will review your PR
- once everything looks ok, commit your changes locally: `git add . && git commit -m 'your message'`
- then, push to your fork: `git push origin update-ldap-tips`
- go to https://github.com/jhipster/jhipster.github.io and open a new pull request

**Comment by patrickjp93** [comment]
Okay, I'll hop on this today.

**Comment by pascalgrimaud** [comment]
@patrickjp93 : it's fine, nothing urgent. Take the time you need. Don't hesitate to ask help, but if we don't answer immediatly, just be patient ;)
We are happy to help new user to contribute, so thanks so much for wanting to help the community

**Comment by patrickjp93** [comment]
@issovic  Just to clarify, you only have problems with the JHipster tip because your LDAP deployment does not provide AD Groups, correct? Or is it something else entirely?

I can provide some cleaner reference materials and code from Baeldung and others if it's everything that's broken...

**Comment by patrickjp93** [comment]
@pascalgrimaud [PR](https://github.com/jhipster/jhipster.github.io/pull/847)

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/jhipster.github.io/pull/847

**Comment by micobarac** [comment]
Guys, the LDAP Authentication tips article's proposed code doesn't work. It would be nice to have an updated and fully working article on how to authenticate on AD and get groups.

**Comment by pascalgrimaud** [comment]
The tips are proposed by our users, the core team didn't maintain it and didn't check if it works well.
So once you resolve your issue, @micobarac, don't hesitate to update the tips if needed and propose a pull request.

If the tips doesn't work anymore and if no one wants to update it, just tell me and I'll remove it.

**Comment by omurthy** [comment]
LDAP integration still doesnt work. It returns Bad Credentials .
