### ISSUE TITLE
Kubernetes Support 6.4.1 fails to find database and more

### ISSUE THREAD

**Issue by mishkaechoes** [jhipster/generator-jhipster#10725]
##### **Overview of the issue**
Attempted to generate monolith with multiple different configurations. After running jhipster kubernetes a consistent error would result from not being able to identify the prod database:

ERROR! Error: Copying template db/undefined.yml.ejs failed. [Error: ENOENT: no such file or directory, open '/..../node_modules/generator-jhipster/generators/kubernetes/templates/db/undefined.yml.ejs']

I've attempted both postgres and mongodb.
After modifying files.ejs and hardcoding the appropriate database other problems would follow:
- Ports were not configured correctly on the service or the application container
- Fixing those ports still did not have the application start appropriately. It would hang shortly after displaying the JHipster banner. (I did not debug further).

##### **Motivation for or Use Case**
I am evaluating JHipster as a solution for building out a Microservice project. After having other difficulties it made sense to scale back to a monolith and get a better feel for the workflow for deploying to Kubernetes.

##### **JHipster Version(s)**

6.4.1

##### **JHipster configuration**
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
pulse@0.0.1-SNAPSHOT /Users/mishka/workspace/jhipster/demo/pulse-demo-3
├── generator-jhipster@6.4.1
└─┬ generator-jhipster-kotlin@1.1.0
  └── generator-jhipster@6.2.0

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster-kotlin": {
    "promptValues": {
      "packageName": "com.company.product"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "pulse",
    "packageName": "com.company.product",
    "packageFolder": "com/company/product",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "secret"
  },
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "monolith",
    "baseName": "pulse",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "flatly",
    "clientThemeVariant": "dark",
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.1.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "al",
      "ar-ly",
      "hy",
      "by",
      "bn",
      "ca",
      "zh-cn",
      "zh-tw",
      "cs",
      "da",
      "nl",
      "et",
      "fa",
      "fi",
      "fr",
      "gl",
      "de",
      "el",
      "hi",
      "hu",
      "in",
      "it",
      "ja",
      "ko",
      "mr",
      "my",
      "pl",
      "pt-br",
      "pt-pt",
      "ro",
      "ru",
      "sk",
      "sr",
      "es",
      "sv",
      "tr",
      "ta",
      "te",
      "th",
      "ua",
      "uz-Cyrl-uz",
      "uz-Latn-uz",
      "vi"
    ],
    "blueprints": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.1.0"
      }
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.23.0

node: v12.8.1

npm: 6.10.3

yeoman: 3.1.0

yarn: 1.17.3

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

MACOS

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
The issue is in the main generator. Let me fix it.
