### ISSUE TITLE
Unable to Create QueryService for User entity (Compilation error while creating criteria based searching for User entity).

### ISSUE THREAD

**Issue by dronavallisaikrishna** [jhipster/generator-jhipster#10720]
##### **Overview of the issue**
As part of my application, I am showing paginated users. But I  want to enable criteria-based searching for user entity.  I created the following files from the help of other entities.

1. created `UserCriteria.java` class 
2. Enabled `JPAspecificationExecutor<User>` on UserRepository.
3. Created a `UserQueryService`. 

But when I run the code the JPA static meta-model is not generating. So the application is failing to compile.

##### **Reproduce the error**
auth/src/main/java/com/star/auth/service/UserQueryService.java:[100,100] cannot find symbol
[ERROR]   symbol:   variable User_
[ERROR]   location: class com.star.auth.service.UserQueryService

##### **JHipster Version(s)**
6.2.0

##### **JHipster configuration**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.star.auth",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "uaa",
    "baseName": "StarAuthentication",
    "packageName": "comstar.auth",
    "packageFolder": "com/star/auth",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi",
      "ta",
      "te"
    ],
    "blueprints": [],
    "skipClient": true
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
There is no .JSON file for the user entity.

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
This is not a JHipster, the problem is in custom code. 

Please use [gitter](https://gitter.im/jhipster/generator-jhipster) or [stackoverflow](https://stackoverflow.com/questions/tagged/jhipster) for questions
