### ISSUE TITLE
Some filters made with the "QueryService" service do not work.

### ISSUE THREAD

**Issue by nico783** [jhipster/generator-jhipster#10721]
##### **Overview of the issue**

I have created an entity that has an id as an attribute. 
When I make the following call: http://localhost:8080/api/example?id.lessThan=2
all "example" objects are returned and not only objects with id less than 2.

##### **Motivation for or Use Case**

I expect to get only the filtered objects.

##### **Suggest a Fix**

It seems that the code called in QueryService does not allow to manage "RangeFilter" but only "Filter" them. This explains why the filters 
greaterThan, lessThan, moreOrEqualThan, lessOrEqualThan are not managed.

In debug, I note that the called method is:
"QueryService" (line 83):
```
protected <X> Specification<ENTITY> buildSpecification(Filter<X> filter, 
Function<Root<ENTITY>, Expression<X>> metaclassFunction) {
        if (filter.getEquals() != null) {
            return equalsSpecification(metaclassFunction, filter.getEquals());
        } else if (filter.getIn() != null) {
            return valueIn(metaclassFunction, filter.getIn());
        } else if (filter.getNotEquals() != null) {
            return notEqualsSpecification(metaclassFunction, filter.getNotEquals());
        } else if (filter.getSpecified() != null) {
            return byFieldSpecified(metaclassFunction, filter.getSpecified());
        }
        return null;
    }
```
The returned result is null and filter is not apply. 

The addition of the following method in the QueryService class, in order to manage RangeFilter, seems to fix the problem:
```
protected <X extends Comparable<? super X>> Specification<ENTITY> buildSpecification(RangeFilter<X> filter, SingularAttribute<? super ENTITY, X> field) {
        return this.buildSpecification(filter, (root) -> root.get(field));
}
```

##### **JHipster Version(s)**

6.0.1

##### **JHipster Version(s)**

```
qsf-2@0.0.0 /Users/nicolasbenizri/Lab/qsf-v2/qsf-v2
└── generator-jhipster@6.0.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.adeo.qsf"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "monolith",
    "baseName": "qsf2",
    "packageName": "com.adeo.qsf",
    "packageFolder": "com/adeo/qsf",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity CommandExample {
  description String
}
entity ReceiptExample {
  state String
}
relationship OneToOne {
  CommandExample{receiptExample} to ReceiptExample
}

dto CommandExample, ReceiptExample with mapstruct
paginate CommandExample, ReceiptExample with pagination
service CommandExample, ReceiptExample with serviceClass
filter CommandExample, ReceiptExample

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.20.1 (Apple Git-117)

node: v10.15.3

npm: 6.12.1

Docker version 18.09.0, build 4d60db4

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Blackdread** [comment]
You should provide implementation of your `public Specification<XXX> createSpecification(XXXCriteria criteria)`.
It won't compile if you try to call `buildSpecification(RangeFilter ...)` without knowing at compile time the type of the filter

**Comment by nico783** [comment]
> You should provide implementation of your `public Specification<XXX> createSpecification(XXXCriteria criteria)`.
> It won't compile if you try to call `buildSpecification(RangeFilter ...)` without knowing at compile time the type of the filter

For the moment I use the following implementation that fixes the problem:

```
public abstract class CorrectedQueryService<ENTITY> extends QueryService<ENTITY> {
     protected <X extends Comparable<? super X>> Specification<ENTITY> buildSpecification(RangeFilter<X> filter, SingularAttribute<? super ENTITY, X> field) {
        return this.buildSpecification(filter, (root) -> root.get(field));
    }
}
```

However, I think there is an anomaly in the QueryService class

**Comment by gzsombor** [comment]
Yes, the id is treated differently, I will submit a fix for this today.
