### ISSUE TITLE
Better UI for not logged in and authentication expired users in Angular

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#10733]
##### **Overview of the feature request**

This is follow up to PR-s #10672 (corresponding issue is #10630) and #10675 (corresponding issue is #10551).  
PR for resolving this issue can be done after #10672 and #10675 are merged.

After above referenced 2 PR-s the logic for "not logged in" / "authentication expired" users in session and JWT authentication is:
* remember "requested" / "last seen" page
* route to home page
* open login modal
* on successful login route to "requested" / "last seen" page

In issues and PR-s referred above was proposed / discussed some enhancements. This issue is for discussion of these enhancements.

Description of possible enhancement:

* instead of routing to home page, route to https://github.com/jhipster/generator-jhipster/tree/master/generators/client/templates/angular/src/main/webapp/app/layouts/error where new special error sections with the following content will be added:
    * new error messages (translation keys are going to `error.json`)
        * `error.notLoggedIn`: **You are not logged in.**
        * `error.authenticationExpired`: **Authentication expired.**
    * information where user is routed after logging in in the form (translation can go to the `error.json` with the key `error.redirectUrl`): **After logging in you are routed to {{ redirectUrl }}**
    * button "Log in"

* don't open login modal by default, user can open login modal by clicking "Log in"

* if user navigates away from this error page without logging in then clear remembered "requested" / "last seen" page, because navigating away without logging in can be considered as cancellation of routing to "requested" / "last seen" page after logging in

##### **Motivation for or Use Case**

Improve UI for not logged in and authentication expired users.

##### **Related issues or PR**

#10672 #10630 #10675 #10551 #9800

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
There's a couple of PRs that've been merged related to this issue. Can we close it, or is there still work that needs to be done?

**Comment by kaidohallik** [comment]
In the current main branch this is not resolved. But I think current open PR #11926 will resolve this issue. So this issue can be closed after #11926 is merged.

**Comment by DanielFran** [comment]
Closed with #11926
