### ISSUE TITLE
Optimistic locking

### ISSUE THREAD

**Issue by rockbird** [jhipster/generator-jhipster#1074]
Hi,

I started to play with jhipster and it is a great project.

I'm building an app with Posgresql and I saw that the entities / tables don't have a version property / column. Do you intend to add support for optimistic locking in the future ?

Thanks,
Marius

**Comment by jdubois** [comment]
I don't think this is required for what we do: pessimistic locking should work fine for our use case.

Then, adding a Version field is trivial, so as long as this is easy there is no need for us to generate it: just add it by writing it.

One thing I didn't check, is if Liquibase "diff" works with the version field, if you have any feedback on this I would be very interested.
