### ISSUE TITLE
Add JDL generator support for Google Cloud Datastore

### ISSUE THREAD

**Issue by ludoch** [jhipster/generator-jhipster#10746]
##### **Overview of the feature request**
Add JDL generator support for Google Cloud Datastore

##### **Motivation for or Use Case**
We want to promote more jHipster app integration with Google Cloud Platform (App Engine, GKE, Cloud Run,...) and in this ecosystem, the Google Datastore is critical for customers.
Datastore is not SQL but Object database. 
We have Java client libraries at: 
https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-datastore

Guide at https://cloud.google.com/java/getting-started/using-cloud-datastore

We also have a third party Object Mapper that provides better abstraction: Objectify:
https://github.com/objectify/objectify/wiki/DesignOfObjectify6
See it only version 6 or above, not previous releases.
Code is at https://github.com/objectify/objectify

This would enable major usage of jHipster on Google Cloud, adding the ease of use of JDL and the power of Cloud Datastore.
All JDL features might not be able to be implemented, and portability to other SQL base solutions is not a goal.

##### **Related issues or PR**

No.
-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ludoch** [comment]
cc @saturnism

**Comment by ludoch** [comment]
Forgot to add that we already have a Spring GCP Datastore integration, hosted on the Spring repo:

https://spring.io/projects/spring-cloud-gcp

There, you can see 2 potential targets: Spanner, and Datastore.
In terms of initial impact for many customers, Datastore would be more important imo.

**Comment by ludoch** [comment]
Thanks Mathieu. Please chat with Ray and me for brainstorming, questions, and help. If you need GCP credits, Ray is the man.

**Comment by MathieuAA** [comment]
Roger that, thanks :)

**Comment by ludoch** [comment]
More samples when it comes to Spanner. https://github.com/saturnism/cloud-spanner-java-by-example

**Comment by MathieuAA** [comment]
Thanks @ludoch, I'll try to find time to look into it this week-end and I might ping you guys next week

**Comment by mraible** [comment]
Closing due to no action from @ludoch or @saturnism. I love you guys!
