### ISSUE TITLE
Avoid skipping tests when deploying to the Cloud

### ISSUE THREAD

**Issue by Falydoor** [jhipster/generator-jhipster#10741]
##### **Overview of the feature request**

The AWS/Heroku/CloudFoundry sub-generators use the function `buildApplication` in `generators/generator-base.js` with the `prod` profile to package the application. The function always skips the tests which is not really recommended, especially when using the `prod` profile.

##### **Motivation for or Use Case**

The tests should not be skipped when deploying the app to any Cloud providers.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
There is no specific reason for not launching tests
So I'm in favor of removing skipTests

**Comment by pascalgrimaud** [comment]
@Falydoor : would you like to provide a PR to fix this plz ?

**Comment by pascalgrimaud** [comment]
Maybe it can be a minor improvement but it looks like no one want to work on this, so let's close this ticket.
