### ISSUE TITLE
npm test failed for upgrade.spec.js

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#10758]
##### **Overview of the issue**

Current `npm test` failed for tests related to upgrade.

##### **Motivation for or Use Case**

Need to be fixed quickly, so I'm putting a bounty on this.

##### **Reproduce the error**

```
npm run test:unit test/upgrade.spec.js
```

##### **JHipster Version(s)**

v6.5.0 and current master

**Comment by pascalgrimaud** [comment]
cc @murdos as you're the boss on this part.
If you can help...

**Comment by murdos** [comment]
Sure, I'll see if I can reproduce and fix it!

**Comment by pascalgrimaud** [comment]
Thanks a lot @murdos 
I'm focus on my talk at Microsoft Ignite, I don't have time to have a look.
Don't hesitate to comment or give feedbacks here if you're stuck
