### ISSUE TITLE
not able to properly generate project in 2.1.1 on linux

### ISSUE THREAD

**Issue by alexandrustefan** [jhipster/generator-jhipster#1075]
Hi,

I am on Elementary OS (Ubuntu based) and I am not able to generate a new project using the generator.
After running "yo jhipster" at the end of execution I get 
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```
Also, as soon as I run mvn spring-boot:run , the index is displaying a plain string "This is your footer", and looking into the "Console" tab in Chrome, I can see that the angular.js is not present, as I get "Uncaught ReferenceError: angular is not defined".

I have tried running npm install and bower install manually, but without luck.

**Comment by jdubois** [comment]
We need the full stack trace -> this looks like a npm or bower installation problem, that's why you don't have everything working in the end.

Please check both installations (I can't know which is failing because the stack trace is not complete)

**Comment by gmarziou** [comment]
Yes very likely a broken node instalation.
Ubuntu comes with a rather old version of node. I fixed mine by uninstalling node, deleting manually the directories where it was installed and then re-installing a 0.10.36 version.

**Comment by stombergas** [comment]
Hi,

I have the same problem on Xubunutu 14.10. Version of Node is 0.10.36. and npm is 2.5.
I have also used the Docker installation but get the same error.
Tried it with different node installations, but no luck. The same stacktrace nothing more, after 
running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


Everything looks all right!

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by alexandrustefan** [comment]
I've managed to solve this by installing grunt cli via npm, and then to run grunt in the root of the generated project.

**Comment by stombergas** [comment]
Alexandrustefan, thank you very much , it works finally.

**Comment by davykiala** [comment]
I have the same error as alexandrustefan on mac yosemite. This error arrived just after i've update the jhipster generator.

**Comment by alexandrustefan** [comment]
It should work the same way as I mentioned above...

**Comment by greha** [comment]
Hi,
i had the same issue on windows, and @alexandrustefan solution worked for me -> Thanks!

**Comment by davykiala** [comment]
Thanks i resolve the error. I am new into mac osx. I have Yosemite. I've uninstalled node using this stackoverflow thread http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x . Then i've installed the node 0.12.00 version. When i re-install yeoman, generator-jhipster and grunt-cli.
Thanks a lot. You save me headache.

**Comment by gmarziou** [comment]
Be careful, 0.12.0 is only few days old, if you encounter problems you may want to switch to 0.10, not 0.11

**Comment by alexandrustefan** [comment]
You are all welcome ! Based on this situations I would like to suggest to mention this step also in the documentation (installing grunt cli). That's because the error is not very intuitive and also even though I have worked with spring and angular before, I am not vey familiar with npm grunt and bower. I am sure that there are plenty of other people who will love to give a try to jhipster but they will fail due to lack of knowledge when it comes to the mentiones tools.  Thanks :)

**Comment by davykiala** [comment]
alexandrustefan i am new in collaboration in an open source project on Github. Could you give me which step to suggest an improvment of the documentation ?

**Comment by alexandrustefan** [comment]
@davykiala the suggestion was addressed to @jdubois or @gmarziou which added this already :). Thanks !

**Comment by juancarloscavero** [comment]
Try to install the latest version of gradle, it's worked well for me

**Comment by danielemaddaluno** [comment]
For me executing `sudo npm install -g grunt-cli` worked fine!
