### ISSUE TITLE
jhipster export-jdl results in ERROR

### ISSUE THREAD

**Issue by Kelvijn** [jhipster/generator-jhipster#10768]
jhipster info                          
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
xg-edfu-admin-website@0.0.1-SNAPSHOT /Users/calvinswinnen/Documents/projects/Qarad/xg-edfu-admin-website
└── generator-jhipster@6.5.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.qarad",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.5.0",
    "applicationType": "monolith",
    "baseName": "xg_edfu_admin_website",
    "packageName": "com.qarad",
    "packageFolder": "com/qarad",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Testt

</pre>
</details>

##### **Overview of the issue**

jhipster export-jdl results in 
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:export-jdl application.jdl
INFO! Options: from-cli: true
ERROR! TypeError: Cannot read property 'error' of undefined
##### **Reproduce the error**

1. create new application with jhipster 

2. 
jhipster export-jdl application.jdl
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:export-jdl application.jdl
INFO! Options: from-cli: true
ERROR! TypeError: Cannot read property 'error' of undefined

##### **JHipster Version(s)**

6.5

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
cc @MathieuAA : can you help on this plz ?

**Comment by Shaolans** [comment]
Looks like this is failing because embeddableLaunchScript and blueprints because when checking options values, they are not defined here (https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/application_options.js).

**Comment by pascalgrimaud** [comment]
It will be fixed in the next release, so I'm closing this.
Same here -> @MathieuAA plz claim the bounty as you did the fix

**Comment by MathieuAA** [comment]
Thanks, bounty claim: https://opencollective.com/generator-jhipster/expenses/11777
