### ISSUE TITLE
[Feature Request] jhi-item-count should have the entity name

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#10778]
##### **Overview of the feature request**
If JHipster already pluralizes the entity's name, then why wouldn't it be added to that module? I cloned the component and added `@Input() pluralEntityName: string;` and the html would become `... of {{ total }} {{ pluralEntityName }}`

The `jhi-item-count` would have the extra parameter like this: `[pluralEntityName]="'users'"` (although I don't know how would this work with translations 😕)

##### **Motivation for or Use Case**
This request would add readability to the pagination.

##### **Related issues or PR**
No PR that I know of.

-   [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by pascalgrimaud** [comment]
Opened for too long, and no comment on this.
Thanks for the request, feel free to provide a pull request if you think it's interesting to have. Don't forget the 3 fronts: Angular, React and Vue.js

For now, I'm closing this for lack of interest
