### ISSUE TITLE
Update Jhipster Entity without overriding existing files and custom code

### ISSUE THREAD

**Issue by hammad-tariq** [jhipster/generator-jhipster#10787]
##### **Overview of the feature request**

When I try to update existing entity in my JHipster project I get following message:

? Do you want to update the entity? This will replace the existing files for this 
entity, all your custom code will be overwritten 
  Yes, re generate the entity 
❯ Yes, add more fields and relationships 
  Yes, remove fields and relationships 
  No, exit 

##### **Motivation for or Use Case**

As it states all your custom code will be overwritten. I have some custom code now in my application which I want to keep and add more fields at the same time.

Do I need to make some manual changes ? What will be the process for this use case.

**Comment by gmarziou** [comment]
You could update your entity on a git branch and then merge to your master to keep your custom code.
You could also follow the side-by-side approach https://www.youtube.com/watch?v=Gg5CYoBdpVo

As this is a question and not an issue, I'm closing this.

Please use [gitter](https://gitter.im/jhipster/generator-jhipster) or [stackoverflow](https://stackoverflow.com/questions/tagged/jhipster) for questions
