### ISSUE TITLE
minor issues with Gitlab CI-CD

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#10795]
##### **Overview of the issue**

The out commented code block in the `.gitlab-ci.yml` for docker-push has two little issues I noticed:

1. when running `jib` without `-Pprod`, the build tool generates a dev frontend, which is not intended in production
2. we set `IMAGE_TAG` to `$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA`, what creates an invalid container image tag

##### **Motivation for or Use Case**

Using `docker-push` in Gitlab CICD

##### **Reproduce the error**

Use `jhipster ci-cd` to generate a `.gitlab-ci.yml` and uncomment the docker-push task.
-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by defrummel** [comment]
This would have saved me some hours of debugging! good job fixing it :)
