### ISSUE TITLE
Allow using kubernetes PVCs for stateful resources

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#10804]
##### **Overview of the feature request**

As already discussed in #5173 or #9622, our kubernetes sub-generator generates all "stateful resources" (such as MySQL, PostgreSQL, etc.) with `emptyDir` as volume definition. 

I propose the following add-on:

When `jhipster kubernetes` asks its prompts, it should ask

```
Do you want to use a storage class for dynamic storage provisioning?
- No
- Yes, the default storage class
- Yes, with a specified storage class
```

If the user chooses the last option, an additional question asks the `storageClassName`. 

##### **Motivation for or Use Case**

I think the motivation is clear: we want to define non-empheral storage as we want to keep our data. In the past discussions, we were concerning about the cloud-specific storage configurations. AFAIK, kubernetes developed the concept of storage classes and persistent volume claim with the aim of decouple persistence with the persistent provider.

In usual clusters, with a recent kubernetes version, you just can create a PVC without specifying `storageClassName` or annotations. If the cluster has a default storage class, kubernetes assumes such an empty definition as a PVC for the default storage class implicitly. 

In scenarios, where cluster administrators enable several storage classes, we can ask the user for the storage class name. In earlier versions of k8s, there was no clear standard about how to set the storage class name, as you could either use the property, or `alpha`/`beta` annotations. However, as of today, it is well established.

I see the following tasks here:

- [ ] add the new prompts to sub-generator with corresponding cofigurations
- [ ] when using PVCs is enabled, propagate the correct PVC to all persistent resources, including app databases, JHipster console, etc
- [ ] add PVC related options to JDL in deployment->kubernetes

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
@xetys if you know how to implement this feature in a cloud-agnostic way and keep things working out of the box in most cases. I'm all for this. Do you have time right now to develop this feature?

**Comment by xetys** [comment]
@PierreBesson sure, already started ;)
