### ISSUE TITLE
please support multiple datasource

### ISSUE THREAD

**Issue by Yerikshu** [jhipster/generator-jhipster#10814]
##### **Overview of the feature request**
support multiple datasource such as es\marridb\mongodb at the same time, for example, in the databaseconfiguration, will config the db1, db2, .... dbn

##### **Motivation for or Use Case**
as the guide for https://www.baeldung.com/spring-data-jpa-multiple-databases, 

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@Yerikshu : sorry but it is something we can't do as it is too specific to your business case. If you need this, you can simply code it in your application. I don't think it should be support directly in JHipster.

Anyway, if you think it's a must have, I can suggest you to create a blueprint for that.
Have a look at https://www.jhipster.tech/modules/creating-a-blueprint/#-creating-a-blueprint

For now, I'm closing this.
