### ISSUE TITLE
CI: migration to GitHub Actions

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#10817]
The work was already started by @vishal423 here https://github.com/jhipster/generator-jhipster/pull/10505

I'd like to migrate our current Travis builds to GitHub Actions, with these advantages:
- free for Open Source
- up to 20 parallel builds
- no Minutes limitation per month
- see the documentation:
    - https://github.com/features/actions
    - https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions

The plan:
- [x] propose a new matrix builds, testing Angular / React / Maven / Gradle / Monolith / Microservices without privileging one of these configuration
- [x] keep 1 build for `npm test`
- [x] use 19 builds for other configs
- [x] add badges to README
- [x] we can still keep Azure Pipelines as it works well, but we need to test another config
- [x] copy all config from the current Travis builds to GitHub Actions
- [x] reduce the number of builds in Travis
- [x] don't forget Sonar Analyze which is in Travis
- [x] remove Travis

**Comment by pascalgrimaud** [comment]
cc @jhipster/developers as it will impact all other repositories.
Then, if it's a success, we need to do the same for:
- jhipster lib
- jhipster-registry
- ng-jhipster
- react-jhipster
- blueprints
- etc.

**Comment by pascalgrimaud** [comment]
I'm starting to work on this

**Comment by pascalgrimaud** [comment]
I'm proposing:

For GitHub Actions (19 builds):

```
ngx-maven-mysql
ngx-maven-psql-es-noi18n
ngx-maven-mariadb-oauth2-infinispan
ngx-maven-mongodb-kafka-cucumber
ngx-maven-h2disk-ws-nocache
ngx-gradle-mysql-fr
ngx-gradle-psql-es-noi18n
ngx-gradle-mariadb-oauth2-infinispan
ngx-gradle-mongodb-kafka-cucumber
ngx-gradle-yarn-h2disk-ws-nocache
react-maven-mysql
react-maven-psql-es-noi18n
react-maven-h2mem-memcached
react-maven-cassandra-session-redis
react-maven-couchbase-caffeine
react-gradle-psql-es-noi18n
react-gradle-h2mem-memcached
react-gradle-cassandra-session-redis
react-gradle-couchbase-caffeine
```

For Azure Pipelines:

```
ms-ngx-gateway-eureka-jwt
ms-ngx-gateway-eureka-oauth2
ms-ngx-gateway-eureka-uaa
ms-micro-eureka-jwt
ms-react-gateway-consul-jwt
ms-react-gateway-consul-oauth2
ms-micro-consul-oauth2
```

**Comment by vishal423** [comment]
@pascalgrimaud, let me know if you need any help here

**Comment by pascalgrimaud** [comment]
@vishal423 : thanks :) I need to work on this to learn GitHub Actions. You already did the hard part so I used your work here !

**Comment by pascalgrimaud** [comment]
Thanks to @jdubois for adding me as admin to SonarCloud organization

Here the link of the Organization: https://sonarcloud.io/organizations/jhipster/projects
Then, I need to:
- update the link of Sonar at jhipster.tech
- remove completelely Travis

**Comment by pascalgrimaud** [comment]
All work is done, so I'm closing this.
I'll open a new ticket for each repo, to migrate to GitHub Actions too
