### ISSUE TITLE
liquibase diff finding some changes that don't exist

### ISSUE THREAD

**Issue by tomy29** [jhipster/generator-jhipster#1082]
Hi,

I am trying to run liquibase diff with jhipster V2.
But liquibase finds some new fields that are already the tables. It shouldnt find those changes.
For example liquibase created this file (at entity creation via jhipster generator) : 

    <?xml version="1.0" encoding="utf-8"?>
    <databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
    
        <property name="now" value="now()" dbms="mysql,h2"/>
        <property name="now" value="current_timestamp" dbms="postgresql"/>
    
        
        <changeSet id="20150202175035" author="jhipster">
            <createTable tableName="T_CATALOGUE">
                <column name="id" type="bigint" autoIncrement="true">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="date_derniere_modif" type="date">
                    <constraints nullable="false" />
                </column>
                <column name="actif" type="bit"/>
                <column name="fournisseur_code" type="varchar(255)"/>
                <column name="fournisseur_id" type="bigint"/>
                <column name="pays_id" type="bigint"/>
                <column name="marque_id" type="bigint"/>
                <column name="produit_id" type="bigint"/>
                <column name="emballage_id" type="bigint"/>
                <column name="client_id" type="bigint"/>
            </createTable>
            
            <addForeignKeyConstraint baseColumnNames="fournisseur_id"
                                     baseTableName="T_CATALOGUE"
                                     constraintName="fk_catalogue_fournisseur_id"
                                     referencedColumnNames="id"
                                     referencedTableName="T_FOURNISSEUR"/>
    
            <addForeignKeyConstraint baseColumnNames="pays_id"
                                     baseTableName="T_CATALOGUE"
                                     constraintName="fk_catalogue_pays_id"
                                     referencedColumnNames="id"
                                     referencedTableName="T_PAYS"/>
    
            <addForeignKeyConstraint baseColumnNames="marque_id"
                                     baseTableName="T_CATALOGUE"
                                     constraintName="fk_catalogue_marque_id"
                                     referencedColumnNames="id"
                                     referencedTableName="T_MARQUE"/>
    
            <addForeignKeyConstraint baseColumnNames="produit_id"
                                     baseTableName="T_CATALOGUE"
                                     constraintName="fk_catalogue_produit_id"
                                     referencedColumnNames="id"
                                     referencedTableName="T_PRODUIT"/>
    
            <addForeignKeyConstraint baseColumnNames="emballage_id"
                                     baseTableName="T_CATALOGUE"
                                     constraintName="fk_catalogue_emballage_id"
                                     referencedColumnNames="id"
                                     referencedTableName="T_EMBALLAGE"/>
    
            <addForeignKeyConstraint baseColumnNames="client_id"
                                     baseTableName="T_CATALOGUE"
                                     constraintName="fk_catalogue_client_id"
                                     referencedColumnNames="id"
                                     referencedTableName="T_CLIENT"/>
    
        </changeSet>
    </databaseChangeLog>

and when I run liquibase diff (with maven on eclipse), a new change file is created with : 

    <changeSet author="techvalley (generated)" id="1422955244728-17">
        <addForeignKeyConstraint baseColumnNames="marque_id" baseTableName="T_CATALOGUE" constraintName="FK_8himrp79am8xdrxwwd4mqr17i" deferrable="false" initiallyDeferred="false" referencedColumnNames="id" referencedTableName="T_MARQUE"/>
    </changeSet>

Thanks for your help

**Comment by jdubois** [comment]
- did you apply the first changeset?
- did you compile your project before doing the "liquibase:diff"?
- do you have only one "addForeignKeyConstraint" changeset? I wonder why this one would be different than the others

**Comment by tomy29** [comment]
I did so many things that I can't be sure of the chronology of my actions.
I think this is what I did : 
1- I ran mvn spring-boot:run after I initially created my application.
2- Then I added entities (by 3-4 each time) and ran mvn spring-boot:run after. 
3- Once I had created all my entities I updated some object and ran liquibase diff. 
I just sent an example with one foreign key, but liquibase diff added many existing foreign keys and some existing fields too.
If nobody else has this problem, this must come from me. I must not have done things properly at the beginning. 
You can close this ticket if no one else has this problem.

**Comment by jdubois** [comment]
Well, it looks like you're the only one, so I'm closing this, but I'm keeping an eye on this -> I don't know how many people are using "liquibase:diff", and I don't have any other feedback. So it's either there's no bug, or nobody uses it! That would be disappointing!
