### ISSUE TITLE
Gateway UAA HTTP 403 "error": "access_denied"

### ISSUE THREAD

**Issue by jmai220489** [jhipster/generator-jhipster#10839]
At the time of consuming the post type service from Swagger gateway, error http 403 is presented, please support it seems something is missing.
 
![image](https://user-images.githubusercontent.com/43712645/69763713-18341d80-113c-11ea-8d21-11a3c30e4022.png)

![image](https://user-images.githubusercontent.com/43712645/69763732-2c781a80-113c-11ea-82df-f1748c1706e6.png)
![image](https://user-images.githubusercontent.com/43712645/69763748-3a2da000-113c-11ea-8589-a700ba61b4cc.png)

![image](https://user-images.githubusercontent.com/43712645/69763769-4a457f80-113c-11ea-9400-b4bb16c4e552.png)

![image](https://user-images.githubusercontent.com/43712645/69763963-d2c42000-113c-11ea-91c9-27f6dfea9aca.png)

your support please

UAA
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.fianancie.uaa",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "com.fianancie.uaa",
    "packageFolder": "com/fianancie/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "MDk2M2UyYzdmNDQ3MWFhZjFmMWE4OGM1MmMwM2E5ZjU3ZDhiNzQxZGRlYzNkMDkyNjhkMjYzMDQ5MTkxMDY1YjJmOWU2NWM0ZjE4YmRmOTQ5OTZlNGE5N2JiNGJlMzA4N2M3ZTVjOTI4OTgxNTFhMzZmOWYzZGJlYzg5OTRhMjM=",
    "embeddableLaunchScript": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "blueprints": [],
    "skipClient": true
  }
}

GATEWAY
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.financie.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.financie.gateway",
    "packageFolder": "com/financie/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "es"],
    "blueprints": []
  }
}

**Comment by pascalgrimaud** [comment]
It should be fixed by https://github.com/jhipster/generator-jhipster/pull/11033 and the last release of JHipster Registry v6.0.2
Feel free to comment if it's not the case
