### ISSUE TITLE
Add "createDatabaseIfNotExist=true" to the MySQL connection String

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#10831]
When using MySQL, our connection String uses an existing schema.

On some platforms (like Docker) this isn't an issue as we can correctly create the schema when creating the database, but on some other platforms (like Azure, of course...) this causes an issue: the developer needs to manually create the schema first, which is more work for him (on Azure: you need to allow your IP in the firewall, then configure a database client, to be able to create that schema).

Reading https://stackoverflow.com/questions/34283630/create-databases-with-liquibase-on-empty-mysql-instance it looks like there is a `createDatabaseIfNotExist=true` option in the connection String, to automate this. I would like to set this be default.

**Comment by qmonmert** [comment]
Hey @jdubois I do a PR for that https://github.com/jhipster/generator-jhipster/pull/10953

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/10953
