### ISSUE TITLE
jhiTranslate + [translateValues] escape HTML problem

### ISSUE THREAD

**Issue by codecholeric** [jhipster/generator-jhipster#10832]
##### jhiTranslate + [translateValues] behaves inconsistent to ngx-translate pipe

When I use

```
<span>{{ template | translate:{param: userInput} }}</span>
```

the variable `userInput` gets escaped. I.e. strings like `<p>foo</p>` will be presented verbatim.

If I use

```
<span jhiTranslate="template" [translateValues]="{param: userInput}"></span>
```

then the HTML will be interpreted. I think this has to do with `JhiTranslateDirective` setting `this.el.nativeElement.innerHTML = value;` instead of sanitizing the result like `{{ ... | translate }}` does.

Is this difference in behavior on purpose? Or is `JhiTranslateDirective` missing some kind of sanitization?

##### **Motivation for or Use Case**

We only use `jhiTranslate` throughout the app, however it was surprising to us, that `jhiTranslate` would behave differently than `{{ ... | translate }}` as we would actually have needed the behavior of the pipe (i.e. escaping the html). There does not seem to be any convenient way to programmatically escape HTML code besides doing low-level string operations (i.e. `string.replace('<', '&lt;')` and similar) in a JHipster Angular app?

##### **Reproduce the error**

Add a tag with the directive `jhiTranslate`, a localization template with a variable and provide that variable including HTML via `[translateValues]`.

##### **Suggest a Fix**

If this deviation from `ngx-translate` is by accident, then sanitizing the value within `JhiTranslateDirective` should be sufficient.

##### **JHipster Version(s)**

JHipster `6.4.1`

##### **JHipster configuration**

<details>
    <summary>jhipster info</summary>

```
$ jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
myapp@0.0.1-SNAPSHOT $WORKSPACE
├── generator-jhipster@6.4.0
└─┬ generator-jhipster-kotlin@1.3.0
  └── generator-jhipster@6.4.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster-kotlin": {
    "promptValues": {
      "packageName": "com.myapp"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "monolith",
    "baseName": "myapp",
    "packageName": "com.myapp",
    "packageFolder": "com/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "$SECRET_KEY",
    "embeddableLaunchScript": false
  },
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.4.0",
    "applicationType": "monolith",
    "baseName": "myapp",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "dark",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.3.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "de"],
    "blueprint": "generator-jhipster-kotlin",
    "blueprintVersion": "0.8.1",
    "blueprints": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.3.0"
      }
    ]
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

git version 2.17.1

node: v10.15.0

npm: 6.11.3

yeoman: 3.1.0

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.16.1, build 6d1ac21

INFO! Congratulations, JHipster execution is complete!
```
</details>

**Comment by kaidohallik** [comment]
I looked at `ng-jhipster` and at `ngx-translate` and here is my conclusion.

According to `ngx-translate` documentation:

* if you want to escape HTML, then use some method from here: https://github.com/ngx-translate/core#4-use-the-service-the-pipe-or-the-directive

* if you want HTML to be interpreted then use this: https://github.com/ngx-translate/core#5-use-html-tags

And what I see in `ng-jhipster` is: this is the a synonym of HTML interpretation of `ngx-translate` (https://github.com/ngx-translate/core#5-use-html-tags).

So conclusion: in `ng-jhipster` is implemented only HTML interpretation. If you want to escape HTML, then use https://github.com/ngx-translate/core#4-use-the-service-the-pipe-or-the-directive
