### ISSUE TITLE
Upgrade with pt_BR localization is broken

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#10840]
##### **Overview of the issue**

Upgrading from jhipster 5.8.1 to 6.5.1 results in error with pt_BR localization.

PR https://github.com/jhipster/generator-jhipster/commit/492707876f4a6961b5ab2797818a5f7e5192c661 changed localization file name from 'xx_yyyy_zz to xx_yyyy_ZZ to match java locales'.

The following error is shown at git merge step:

```
error: The following untracked working tree files would be overwritten by checkout:
	src/main/resources/i18n/messages_pt_BR.properties
Please move or remove them before you switch branches.
```

##### **Reproduce the error**

- Create a project with server files and pt-br localization with jhipster < 6.1.0
- Upgrade it to last jhipster version

##### **Suggest a Fix**

Rename files on upgrade.

##### **Browsers and Operating System**

macOS

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by murdos** [comment]
Seems to be very similar to #9908

**Comment by pascalgrimaud** [comment]
yes it's similar to #9908 but I don't know if we can do something

**Comment by PierreBesson** [comment]
Well for me it's not a bug. Yes it's kind of a breaking change  but this was the tradeoff to be able to support all locales. Especially Uzbek which can be written with 2 different alphabets. Actually it's fascinating that Uzbek has been using 3 different scripts for its language in the 20th century (arabic, cyrillic and latin). The cyrillic to latin migration is still in progress today: https://en.wikipedia.org/wiki/Uzbek_alphabet
