### ISSUE TITLE
Generated classes are not automatically set as sources

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#10859]
##### **Overview of the issue**
When using generated classes, like when choosing open-api option, they are not automatically added as project sources. 

By default  maven exclude the entire target folder.

##### **Motivation for or Use Case**
Improve the developer experience by automatically adding generated classes as project sources.

##### **Reproduce the error**
Generate a JHipster application with maven and open-api option.
Launch `./mvnw generate-sources`
create a new service like that (`fu` is a resource of my api).
```java
@Service
public class FuService implements FuApiDelegate {
}
```

--> FuApiDelegate is not recognized.

##### **Suggest a Fix**
We can add documentation to face with all IDE (e.g. `./mvnw idea:idea` for intellij) but I'm looking for a more agnostic solution.

I suggest to add a maven plugin:
`build-helper-maven-plugin`
```xml
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>test</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${basedir}/target/generated-sources</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

It seems gradle don't need this kind of configuration, but I'm not sure and I need to do more tests, otherwise we could do something like :
```groovy
sourceSets {
    main.java.srcDirs = ['src/main/java', 'build/openapi/src/main/java']
}
```

##### **JHipster Version(s)**

```
offers-open-api@0.0.1-SNAPSHOT /Users/aviard/projects/perso/offersOpenApi
└── generator-jhipster@6.5.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.avdev4j.fr.offersopenapi",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "offersOpenApi",
    "packageName": "com.avdev4j.fr.offersopenapi",
    "packageFolder": "com/avdev4j/fr/offersopenapi",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)

git version 2.19.0

node: v10.13.0

npm: 6.5.0

yeoman: 2.0.5

yarn: 1.13.0

Docker version 19.03.4, build 9013bf5

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**
MacOs

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
Currently, I'm struggling with this feature. It seems adding the plugin has no value at all and does not fix the problem.
The things I succeed is to add the generated classes in my classpath like that:
`./mvnw idea:idea`
or after generating sources click on `re-import project` in maven menu

For eclipse case, doing
`./mvnw eclipse:clean eclipse:eclipse` (the clean seems to be important while you already have a .project file.

It's not easy to know how to improve that, maybe we can't. In this case I suggest to add a documentation part about that. It's always difficult to see our classes generated and can't use them...

**Comment by pascalgrimaud** [comment]
So in this case, as you said, the best way is to add documentation on our website.
Can you provide a PR to fix this, @avdev4j ?

**Comment by pascalgrimaud** [comment]
any update on this @avdev4j or should I close this for lack of interest ?

**Comment by pascalgrimaud** [comment]
partially fixed by https://github.com/jhipster/jhipster.github.io/pull/898 : the doc can still be improved but it's better than nothing

**Comment by avdev4j** [comment]
@atomfrede as I remember you know gradle a bit, isn't it ? I did some tests but generated files are still excluded from the source folder. Have you any idea how to, via a command, update the project setting ?

We should add a gradle section to the doc ;)

**Comment by atomfrede** [comment]
I didn't follow this issue well, but at least for the mapstruct files I usually have to do nothing (in idea). You talk about openapi generator files right? Can have a look. I know for maven it really depends where they are generated otherwise idea will forget it every time.
