### ISSUE TITLE
Ngx-translate not working with ng-jhipster version 11

### ISSUE THREAD

**Issue by Pranavism** [jhipster/generator-jhipster#10850]
* **Overview of the request**

Upgraded jhipster gateway to angular 8 ,
with  "ng-jhipster": "^0.11.5", translations are not getting picked up.

Just after upgrade first issue encountered :

compiler.js?ad3e:2420 Uncaught Error: Template parse errors:
The pipe 'translate' could not be found 

Then imported TranslateModule in shared modules.
The error is gone but translations are not getting picked up.

all fields are shown as for example.
global.form.confirmpassword

* **Motivation for or Use Case** 
Upgrade to angular 8 hence the dependencies required ng-jhipster 11.

We are at an advanced stage and now stuck cannot go back to older versions

* **Browsers and Operating System** 

All browsers

Package.json 

-----------
{
    "name": "gateway",
    "version": "0.0.0",
    "description": "Description for gateway",
    "private": true,
    "license": "UNLICENSED",
    "cacheDirectories": [
        "node_modules"
    ],
    "dependencies": {
        "@angular/animations": "^8.2.12",
        "@angular/cdk": "^7.2.0",
        "@angular/common": "8.2.12",
        "@angular/compiler": "8.2.12",
        "@angular/core": "8.2.12",
        "@angular/flex-layout": "^7.0.0-beta.22",
        "@angular/forms": "8.2.12",
        "@angular/material": "^7.2.0",
        "@angular/platform-browser": "8.2.12",
        "@angular/platform-browser-dynamic": "8.2.12",
        "@angular/router": "8.2.12",
        "@coreui/angular": "^2.6.3",
        "@coreui/coreui": "^2.1.16",
        "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.3.1",
        "@coreui/icons": "^0.4.1",
        "@fortawesome/angular-fontawesome": "0.5.0",
        "@fortawesome/fontawesome-svg-core": "1.2.25",
        "@fortawesome/free-solid-svg-icons": "5.11.2",
        "@ng-bootstrap/ng-bootstrap": "5.1.2",
        "@ngx-formly/bootstrap": "^5.5.1",
        "@ngx-formly/core": "^5.5.1",
        "@ngx-translate/core": "^11.0.1",
        "@ngx-translate/http-loader": "^4.0.0",
        "@rxweb/reactive-form-validators": "^1.9.7",
        "ajv": "^6.10.2",
        "angular-webstorage-service": "^1.0.2",
        "bootstrap": "4.3.1",
        "chart.js": "^2.9.1",
        "core-js": "2.5.7",
        "flag-icon-css": "^3.4.5",
        "font-awesome": "^4.7.0",
        "jquery": "^1.9.1",
        "moment": "2.22.2",
        "ng-jhipster": "^0.11.5",
        "ng2-charts": "^2.3.0",
        "ngx-bootstrap": "^5.2.0",
        "ngx-cookie": "2.0.1",
        "ngx-infinite-scroll": "6.0.1",
        "ngx-toastr": "11.1.2",
        "ngx-webstorage": "^4.0.1",
        "popper.js": "^1.16.0",
        "primeflex": "^1.0.0-rc.1",
        "primeicons": "^2.0.0",
        "primeng": "^8.0.4",
        "rxjs": "6.5.3",
        "simple-line-icons": "^2.4.1",
        "swagger-ui": "2.2.10",
        "tslib": "1.9.3",
        "zone.js": "0.9.1"
    },
    "devDependencies": {
        "@angular/cli": "8.3.14",
        "@angular/compiler-cli": "8.2.12",
        "@ngtools/webpack": "8.3.14",
        "@types/jest": "23.3.9",
        "@types/node": "10.12.10",
        "angular-router-loader": "0.8.5",
        "angular2-template-loader": "0.6.2",
        "autoprefixer": "9.3.1",
        "browser-sync": "2.26.3",
        "browser-sync-webpack-plugin": "2.2.2",
        "cache-loader": "1.2.5",
        "codelyzer": "5.2.0",
        "copy-webpack-plugin": "4.6.0",
        "css-loader": "1.0.1",
        "file-loader": "2.0.0",
        "fork-ts-checker-webpack-plugin": "0.5.0",
        "friendly-errors-webpack-plugin": "1.7.0",
        "generator-jhipster": "5.7.2",
        "html-loader": "0.5.5",
        "html-webpack-plugin": "3.2.0",
        "husky": "1.2.0",
        "jest": "23.6.0",
        "jest-junit": "5.2.0",
        "jest-preset-angular": "6.0.1",
        "jest-sonar-reporter": "2.0.0",
        "lint-staged": "8.1.0",
        "merge-jsons-webpack-plugin": "1.0.18",
        "mini-css-extract-plugin": "0.4.5",
        "moment-locales-webpack-plugin": "1.0.7",
        "optimize-css-assets-webpack-plugin": "5.0.1",
        "prettier": "1.15.2",
        "reflect-metadata": "0.1.12",
        "rimraf": "2.6.2",
        "simple-progress-webpack-plugin": "1.1.2",
        "style-loader": "0.23.1",
        "terser-webpack-plugin": "1.1.0",
        "thread-loader": "1.2.0",
        "to-string-loader": "1.1.5",
        "ts-loader": "5.3.0",
        "tslint": "5.11.0",
        "tslint-config-prettier": "1.16.0",
        "tslint-loader": "3.6.0",
        "typescript": "3.5.3",
        "sass": "1.15.1",
        "sass-loader": "7.1.0",
        "postcss-loader": "3.0.0",
        "xml2js": "0.4.19",
        "webpack": "4.26.0",
        "webpack-cli": "3.1.2",
        "webpack-dev-server": "3.1.10",
        "webpack-merge": "4.1.4",
        "webpack-notifier": "1.7.0",
        "webpack-visualizer-plugin": "0.1.11",
        "workbox-webpack-plugin": "3.6.3",
        "write-file-webpack-plugin": "4.5.0"
    },
    "engines": {
        "node": ">=8.9.0"
    },
    "lint-staged": {
        "{,src/**/}*.{md,json,ts,css,scss}": [
            "prettier --write",
            "git add"
        ]
    },
    "scripts": {
        "prettier:format": "prettier --write \"{,src/**/}*.{md,json,ts,css,scss}\"",
        "lint": "tslint --project tsconfig.json -e 'node_modules/**'",
        "lint:fix": "npm run lint -- --fix",
        "ngc": "ngc -p tsconfig-aot.json",
        "cleanup": "rimraf target/{aot,www}",
        "clean-www": "rimraf target//www/app/{src,target/}",
        "start": "npm run webpack:dev",
        "start-tls": "npm run webpack:dev -- --env.tls",
        "serve": "npm run start",
        "build": "npm run webpack:prod",
        "test": "npm run lint && jest --coverage --logHeapUsage -w=2 --config src/test/javascript/jest.conf.js",
        "test:watch": "npm run test -- --watch",
        "webpack:dev": "npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --hot --port=9060 --watch-content-base --env.stats=minimal",
        "webpack:dev-verbose": "npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --hot --port=9060 --watch-content-base --profile --progress --env.stats=normal",
        "webpack:build:main": "npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal",
        "webpack:build": "npm run cleanup && npm run webpack:build:main",
        "webpack:prod:main": "npm run webpack -- --config webpack/webpack.prod.js --profile",
        "webpack:prod": "npm run cleanup && npm run webpack:prod:main && npm run clean-www",
        "webpack:test": "npm run test",
        "webpack-dev-server": "node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
        "webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js"
    },
    "jestSonar": {
        "reportPath": "target/test-results/jest",
        "reportFile": "TESTS-results-sonar.xml"
    }
}

* **Related issues** 

* **Suggest a Fix**

**Comment by kaidohallik** [comment]
I see that in `package.json` you have reference to `generator-jhipster` version `5.7.2`.

Current version of the generator is `6.5.1` and this is using `ng-jhipster` version `0.11.4`, latest version `0.11.5` also works fine with the code generated by `generator-jhipster` version `6.5.1`

We are testing latest `generator-jhipster` and `ng-jhipster` together and when releasing a new version of the `generator-jhipster` then this is tested with specific `ng-jhipster` version.

If you generate code with some version of the `generator-jhipster` and manually update `ng-jhipster` version then this may and may not work.

If you want to use the latest version of the `ng-jhipster` then you should regenerate you app with the latest `generator-jhipster`.

I'll do PR for `ng-jhipster` readme to add this information there.

**Comment by kaidohallik** [comment]
PR done: jhipster/ng-jhipster#117
