### ISSUE TITLE
Unididectional OneToOne misses entity-is-null in back end

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#10858]
##### **Overview of the issue**

If not using entity filtering (`jpaMetamodelFiltering=false`) then into `EntityResource.java` is for `OneToOne ownerSide=false` generated filter parameter with value `entity-is-null` and this filter is used in the front end if `clientFramework=angularX`.

Problem is that if it's unidirectional `OneToOne` then this relationship information is completely missing in the `ownerSide=false` entity configuration. And this causes that this `filter` parameter with related implementation is not generated into `EntityResource.java` and in runtime front end doesn't get correct response from the server what leads to errors:
* if some row is already used in some relation then this row is shown again in the different owner object update form
* if the same row is selected again in the different owner object and clicked Save then:
    * in the back end is thrown error `org.hibernate.exception.ConstraintViolationException` (`Unique index or primary key violation`)
    * message "**Internal server error**" is shown to the user

This problem was caught by CI after I made strict type checks in the front end for entities with this PR: #10857 - now already code in the front end in compile time detected that this filter doesn't exist in the back end, corresponding error in CI: https://dev.azure.com/jhipster/generator-jhipster/_build/results?buildId=7495&view=logs&jobId=b82dda55-0fb5-5cba-f633-5f7ed4bfc689&taskId=0bfc65f1-7dd6-56a9-b8fa-7d3851ae2e56&lineStart=89&lineEnd=98&colStart=1&colEnd=1

Code in the back-end for `entity-is-null`: https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/java/package/common/get_all_stream_template.ejs#L23

Code in the front-end for `entity-is-null`: https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base-private.js#L1020

##### **Motivation for or Use Case**

1. Internal server error should be avoided.
2. I would like to pass CI for #10857 

##### **Reproduce the error**

In the CI in the default JDL config is Department to Location unidirectional OneToOne.

Steps:
1. Choose Location id=1 into one Department and save.
2. Go to second Department update form, choose again Location id=1 (this option is available there) and click Save.
3. Internal server error is shown in the front end and `org.hibernate.exception.ConstraintViolationException` (`Unique index or primary key violation`)
in the back end

##### **Related issues**

Couldn't find.

##### **Suggest a Fix**

Maybe add relation information into entity configuration for `unidirectional ownerSide=false OneToOne` and add new keyword `unidirectional` to entity relation configuration and implement that in templates?

##### **JHipster Version(s)**

```
jhipster-sample-application@0.0.1-SNAPSHOT C:\projects\teest\jhipster-one-to-one-unidirectional
`-- generator-jhipster@6.5.1  -> C:\projects\kaido-github\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "websocket": false,
    "applicationType": "monolith",
    "baseName": "jhipsterSampleApplication",
    "authenticationType": "jwt",
    "buildTool": "maven",
    "clientFramework": "angularX",
    "jhipsterVersion": "6.5.1",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "cacheProvider": "ehcache",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "serverPort": "8080",
    "useSass": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1575270992635,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount {
  name String required,
  bankNumber Integer,
  agencyNumber Long,
  lastOperationDuration Float,
  meanOperationDuration Double,
  balance BigDecimal required,
  openingDay LocalDate,
  lastOperationDate Instant,
  active Boolean,
  accountType BankAccountType,
  attachment AnyBlob,
  description TextBlob
}
entity TheLabel {
  labelName String required minlength(3)
}
entity Operation {
  date Instant required,
  description String,
  amount BigDecimal required
}
entity Department {
  name String required,
  description TextBlob,
  advertisement AnyBlob,
  logo ImageBlob
}
/**
 * JobHistory comment.
 */
entity JobHistory {
  startDate ZonedDateTime,
  endDate ZonedDateTime,
  language Language
}
entity Job {
  title String minlength(5) maxlength(25),
  type JobType,
  minSalary Long,
  maxSalary Long
}
/**
 * The Employee entity.\nSecond line in javadoc.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate ZonedDateTime,
  salary Long,
  commissionPct Long
}
entity Location {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Task {
  title String,
  description String
}
entity GoldenBadge {
  name String
}
entity SilverBadge {
  name String
}
entity Identifier {
  name String required unique
}
entity Country {
  name String
}
entity Region {
  name String
}
enum BankAccountType {
  CHECKING,
  SAVINGS,
  LOAN
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}
enum JobType {
  BOSS,
  SLAVE
}

relationship OneToOne {
  Department{location} to Location,
  Employee{user(login)} to User with jpaDerivedIdentifier
}
relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)},
  Employee{job} to Job{emp(lastName)},
  /**
   * A relationship
   */
  Department{employee} to
  /**
   * Another side of the same relationship,
   */
  Employee{department},
  Location{country} to Country{location},
  Country{area} to Region{country}
}
relationship ManyToOne {
  BankAccount{user(login)} to User,
  Employee{manager(lastName)} to Employee,
  Employee{sibag(name) required} to SilverBadge,
  Employee{gobag(name) required} to GoldenBadge,
  GoldenBadge{iden(name) required} to Identifier,
  SilverBadge{iden(name) required} to Identifier
}
relationship ManyToMany {
  Operation{theLabel(labelName)} to TheLabel{operation},
  JobHistory{department} to Department{history},
  JobHistory{job} to Job{history},
  JobHistory{emp(firstName)} to Employee{history},
  Job{chore(title)} to Task{linkedJob(title)}
}

dto BankAccount, Department, Employee, Location, GoldenBadge, SilverBadge, Identifier, Country, Region with mapstruct
service BankAccount, Location, Country with serviceImpl
service TheLabel, Department, Employee, GoldenBadge, SilverBadge, Identifier, Region with serviceClass
angularSuffix BankAccount with mySuffix
filter BankAccount, Employee
clientRootFolder BankAccount, TheLabel, Operation with test-root
paginate TheLabel, Job with pagination
paginate Operation, JobHistory, Employee with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

git version 2.24.0.windows.2

node: v12.13.0

npm: 6.11.3

yeoman: 2.0.6

yarn: 1.17.3

Docker version 19.03.5, build 633a0ea

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's a bug

**Comment by mshima** [comment]
@pascalgrimaud I think @kaidohallik fixed this some time after creating this.

**Comment by pascalgrimaud** [comment]
@kaidohallik : do you confirm ? Can we close this ?

**Comment by kaidohallik** [comment]
This is not fixed. But as this is a minor bug which is not easy to fix then I think this can stay closed unless someone wants to fix this.
