### ISSUE TITLE
node_modules exclusion impacts DX on IntelliJ

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#10860]
##### **Overview of the issue**

With PR #9036 we added these lines to our build.gradle

```
idea {
    module {
        excludeDirs += files("node_modules")
    }
}
```

While this makes sense for non-client applications, this impacts developer experience for working with frontend frameworks.

If you are using Angular, IntelliJ offers similar features as in Java when it comes to auto-import, interpret templates, auto-complete etc. IntelliJ does this by indexing `node_modules`, where all the `@angular` and `RxJS` files are. So if `node_modules` are excluded, you should better know the imports on your own :joy: 

##### **Motivation for or Use Case**

I am using IntelliJ for developing the Angular frontends generated by JHipster, and spend some time by `node_modules > Cancel Exclusion` over and over again, until I recently found out what is causing the issues.

I don't see any other options as including `node_modules` in indexing to get the full support from IntelliJ while working on Angular projects.

##### **Reproduce the error**

- Generate a new JHipster application with a client (preferably Angular, but I'm sure it will also occur on React or Vue)
- open project in IntelliJ
- wait for indexing completion and start the application both with backend and frontend
- check all the angular templates. You will find a lack of auto-complete all over. IntelliJ will mark `*ngFor` and `*ngIf` as missing. IntelliJ won't resolve any components
- when in a typescript file, try to work with `Observable` or other classes, which are not currently imported in this files. No auto-complete or auto-import
- examine one of our `xx.module.ts` files, you will find IntelliJ marking `RouterModule` as error with the message, that `RouterModule` is not an Angular module
- right-click on `node_modules`, `Mark Directory as > Cancel Exclusion`
- after indexing, all the issues mentioned above seem resolved now
- do a gradle re-import. The quoted lines of code from build gradle will exclude `node_modules` once again, with the issues coming back

I didn't check this with react, but I'm sure there should be happening something similar.

##### **Suggest a Fix**

If the current application contains client code, do *not* exclude `node_modules`
and

remove the following statement from documentation, as it is not true IMHO:

```
As the node_modules/ directory is only used internally by JHipster, it can be safely excluded.
```

##### **JHipster Version(s)**

current

##### **JHipster configuration**

all applications containing client code
+ gradle
+ IntelliJ as IDE

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
To have better visibility, plz add a 'area' label. I'm adding enhancement here

**Comment by pascalgrimaud** [comment]
We need to discuss about it.
See my comments at https://github.com/jhipster/jhipster.github.io/pull/859

I'm not sure it's good for demo or our end-users who don't have Ultimate license with Intellij.

**Comment by xetys** [comment]
For the documentation, I would just add these infos to the doc page.

About the PR...well, we use the idea plugin, so this is already limiting the issue for idea users only.

I don't know, how big the difference in index time is as of today. I have some good and some poor devices. But with current versions of IDEA it is acceptable for me...

**Comment by pascalgrimaud** [comment]
Unless I'm wrong, I think :

- users who will be happy by this change:
    - users who use Idea Ultimate + code the front in Idea

- users who won't be happy by this change:
    - users who don't have Idea Ultimate but Idea Community, so can't code the front here
    - users who will open project with Idea Ultimate only for demo -> speaker
    - users who got Idea Ultimate but don't code the front, only backend
    - users who got Idea Ultimate but prefer to use VSCode to code the front because it's far better with VSCode

It's just my opinion. Let's wait what others think

**Comment by atomfrede** [comment]
After thinking about it again I think we should leave it as is. Personally I do not use Idea for frontend development (most of the time) and we would give everyone not having the ultimate edition a worse experience. Maybe we can do a twitter poll to have at least some data how our users are doing development?

**Comment by SudharakaP** [comment]
Just for the purpose of statistics/poll, I am using Intellij IDEA Ultimate both for front and back end. :smile:

**Comment by pascalgrimaud** [comment]
So as Frederik suggested (like me), let's leave it as is
We can still discuss if needed or add some documentation for that
