### ISSUE TITLE
Create new page in documtentation for "Installing frontend dependencies"

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1086]
The section "Using Bower to install and update JavaScript, CSS and Sass dependencies" in the Documentation page  "Using in development" should be more detailed and moved into an own page called "Installing frontend dependencies".
I could try to document this if wanted.

**Comment by jdubois** [comment]
Yes, we could have front-end and back-end development separated. And at least a page on installing Bower dependencies and using "grunt serve" correctly.

**Comment by rasheedamir** [comment]
@andidev I would can assist you in this documentation; how about using a shared Google doc?

**Comment by andidev** [comment]
@rasheedamir Not mutch time for this right now, but maybe in a few days.
If you want to start right away please feel free to do this. I created a document on google docs which is open for editing, heres the [link](https://docs.google.com/document/d/1nP2rcTgJkyV633z62wQbSQqhAgS1OCgl5DqLYIPpPr8/edit?usp=sharing)

**Comment by rasheedamir** [comment]
I have started add stuff; please take a look and provide feedback as comments in the doc.

**Comment by jdubois** [comment]
I'm closing this for 2 reasons:

- I've had a look at your documentation, and this looks "normal" Grunt/Bower documentation to me -> we can have some of this documentation, but it's out of scope of the project to document other projects like Grunt or Bower
- It looks like work has stopped on this issue
