### ISSUE TITLE
Update Keycloak to 8.0.1

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#10862]
Highlights:
* LDAP Issue

This release fixes a critical vulnerability in LDAP introduced in Keycloak 7. If you are using Keycloak 7.0.0, 7.0.1 or 8.0.0 in production we strongly suggest that you upgrade immediately.
* WildFly 18.0.1.Final

Upgrade to WildFly 18.0.1.Final which includes updates to a number of CVEs in third-party libraries.

**Comment by pascalgrimaud** [comment]
Maybe it's easy to do, maybe not, but it will require some testing.
That's why I'm adding a bounty on this, as it's important to upgrade to Keycloak 8.0.1

**Comment by vishal423** [comment]
I will take this

**Comment by vishal423** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/12558

**Comment by pascalgrimaud** [comment]
just approuved, thanks a lot @vishal423
so happy to have you in the team
