### ISSUE TITLE
JhiAlertComponent can't handle Arabic param

### ISSUE THREAD

**Issue by mohamedzaki90** [jhipster/generator-jhipster#10877]
##### **Overview of the issue**
When using a localized Alert message for entity create/update with Arabic param the displayed alert param is not handled correctly.

##### **Motivation for or Use Case**
The business may require hiding persistence ids from the presentation in favor of some business field which could be in Arabic.

##### **Reproduce the error**
Generate sample application with localization (Arabic)
Generate an entity with a String field
create a record with an Arabic value.
in the EntityResource.java modify the update alert param to use the entity String field instead of id
try to update that entity and notice the message with the param

![image](https://user-images.githubusercontent.com/12154618/70183960-83a75d80-16ef-11ea-96bf-718dfb37703b.png)

##### **Related issues**
NA

##### **JHipster Version(s)**

6.5.1
##### **JHipster configuration**
H2 desk database in dev profile

##### **Browsers and Operating System**
chrome. Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
Problem is described (limitation of HTTP headers) and solution (URLEncode HTTP parameter) is provided in this SO question: https://stackoverflow.com/questions/11213160/sending-utf-8-values-in-http-headers-results-in-mojibake

I made quick test.

In JHipster server side library changed this line https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/web/util/HeaderUtil.java#L28 from
```
headers.add("X-" + applicationName + "-params", param);
```
to
```
headers.add("X-" + applicationName + "-params", URLEncoder.encode(param, "UTF-8"));
```

And in generator-jhipster in Angular code changed this line https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/notification.interceptor.ts.ejs#L42 from
```
alertParams = event.headers.get(entry);
```
to
```
alertParams = new HttpUrlEncodingCodec().decodeValue(event.headers.get(entry));
```

After this change Arabic showed up correctly in the following workflow:

* in the code generated by JHipster I changed in the line generated by https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs#L190 `getId()` to `getName()` (name is some string property in entity)

* in entity update form put some Arabic text to field `name`

* clicked Save and alert was shown with correct Arabic text

Should we do this change in JHipster server side library and in Angular side to support any kind of alert parameters?

**Comment by kaidohallik** [comment]
I made some more tests and found out that + sign needs special treatment in Angular side after switching JHipster server side library to generate urlencoded HTTP header, so in my testing then both these 2 solution are working in Angular side:

* `alertParams = new HttpUrlEncodingCodec().decodeValue(event.headers.get(entry).replace(/\+/g, ' '));`

* `alertParams = decodeURIComponent(event.headers.get(entry).replace(/\+/g, ' '));`
