### ISSUE TITLE
Incorrect mssql-jdbc driver dependency

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#10875]
##### **Overview of the issue**
`mssql-jdbc` driver dependency version `8.1.0.jre8` specified in the `jhipster-dependencies` bom is not available in the maven central repository. It will cause build failure.

##### **Motivation for or Use Case**

Refer discussion https://github.com/jhipster/jhipster/commit/ac03c6e7040bcda5c8155bdab043ba31b9d4add3#r36264116
##### **Reproduce the error**
Select MS SQL server as development / production database

##### **Suggest a Fix**
Change to `8.1.0.jre8-preview` or downgrade to `v7.4.1.jre8`

##### **JHipster Version(s)**
v6.5.1

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
@DanielFran, I have raised an issue to track this.

**Comment by Code7Bit** [comment]
just generated a microservice and its still an issu cant find dependecy mssql

**Comment by vishal423** [comment]
@Code7Bit, this should be fixed in the next release. In the meantime, you can manually downgrade dependency to lower version as suggested in fix.

**Comment by gmarziou** [comment]
@Code7Bit have you generated using the master branch of the generator? Because the fix from Daniel has not been released yet, so version 6.5.1 does not include it.
