### ISSUE TITLE
Config Server service name is not translated in Health Checks

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#10870]
##### **Overview of the issue**

If you create a microservices architecture with i18n and JHipster Registry, the "Cloud Config" service is not translated properly in the health checks screen.

<img width="1271" alt="Screen Shot 2019-12-03 at 3 27 39 PM" src="https://user-images.githubusercontent.com/17892/70087167-c9760000-15e1-11ea-8924-5c27f9e1ec57.png">

##### **Motivation for or Use Case**

All the other keys are translated.

##### **Reproduce the error**

Create a microservices architecture with the following JDL. Start all services and navigate to http://localhost:8080/admin/health in the gateway.

```
application {
  config {
    baseName gateway,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serviceDiscoveryType eureka,
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

// will be created under 'docker-compose' folder
deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "jmicro"
  consoleOptions [zipkin]
}
```

##### **Suggest a Fix**

The client is looking for `health.indicator.clientConfigServer` while the i18n key is `health.indicator.configServer`.

##### **JHipster Version(s)**

```
gateway@0.0.1-SNAPSHOT /Users/mraible/dev/ultimate-jhipster-workshop/lab-microservices/gateway
└── generator-jhipster@6.5.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.okta.developer.gateway",
    "packageFolder": "com/okta/developer/gateway",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "baseName": "gateway",
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "jhipsterVersion": "6.5.1",
    "buildTool": "maven",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "ehcache",
    "serverPort": "8080",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["Blog", "Post", "Tag", "Product"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}
entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}
relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

microservice Blog, Post, Tag with blog
microservice Product with store
paginate Post, Tag with infinite-scroll
paginate Product with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

git version 2.21.0 (Apple Git-122.2)

node: v12.13.0

npm: 6.13.1

yeoman: 3.1.1

yarn: 1.19.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!

**Comment by kaidohallik** [comment]
This can be caused by this change in `spring-cloud-config` project: https://github.com/spring-cloud/spring-cloud-config/commit/513353b8e7580df1ca6f24eccdd2cf4c126855a1#diff-ec84b704fc84b98ce1e406eaf1130212L68-R68

**Comment by kaidohallik** [comment]
I debugged and found out that indeed health keys are coming from bean names and suffix `HealthIndicator` is removed from final key, call stack:

1. `org.springframework.boot.actuate.autoconfigure.health.HealthIndicatorAutoConfiguration.healthIndicatorRegistry`

2. `org.springframework.boot.actuate.autoconfigure.health.HealthIndicatorRegistryBeans.get`:

* gets all beans by type `HealthIndicator.class` with this method: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/ListableBeanFactory.html#getBeansOfType-java.lang.Class- which states "Returns: a Map with the matching beans, containing the bean names as keys and the corresponding bean instances as values"

3. `org.springframework.boot.actuate.health.HealthIndicatorRegistryFactory.createHealthIndicatorRegistry`

4. `org.springframework.boot.actuate.health.HealthIndicatorRegistryFactory.initialize` registers health indicators, names are coming from:

* in our current master is used this code to remove `HealthIndicator` suffix: https://github.com/spring-projects/spring-boot/commit/3c535e0de340a718d6cf0d863a6529b314a38f42#diff-506b4201ff26976a856f0bf134ea6542L32-L36
```
		int index = name.toLowerCase(Locale.ENGLISH).indexOf("healthindicator");
		if (index > 0) {
			return name.substring(0, index);
		}
		return name;
```

* if Spring Boot 2.2 will be used then this code will do the same: https://github.com/spring-projects/spring-boot/commit/3c535e0de340a718d6cf0d863a6529b314a38f42#diff-f9849ba01a53085b166edd4c37bc7064R40-R45
```
		for (String suffix : SUFFIXES) {
			if (name != null && name.toLowerCase(Locale.ENGLISH).endsWith(suffix)) {
				return name.substring(0, name.length() - suffix.length());
			}
		}
		return name;
```
where `SUFFIXES` is:
```
	private static final String[] SUFFIXES = { "healthindicator", "healthcontributor" };
```

So conclusion: key change from `configServer` to `clientConfigServer` is coming from spring boot version 2.1.0 and we should change this translation key in `health.json` files.
