### ISSUE TITLE
Align equals implementation of DTOs and entities

### ISSUE THREAD

**Issue by sniffertine** [jhipster/generator-jhipster#10888]
##### **Overview of the feature request**
In this change, equals implementation of entities has changed:
https://github.com/jhipster/generator-jhipster/pull/9022/files

The semantics of equals in DTO classes is identical (except instanceof check vs class check), but implemented very differently. 

--> Change generated code for DTOs to use same semantics
--> Maybe consider to use instanceof for DTOs as well. This would for example allow anonymous instances to be considered equal.

##### **Motivation for or Use Case**

Understanding equals implementation is important. I spent some time trying to understand why the entities had different logic than DTOs, until I found the changes in 9022. 

It would be more clear if the logic was exactly the same, or at least only the instanceof vs class check was different.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/pull/9022/files

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Thanks for reporting this @sniffertine : would you like to contribute and provide a PR ?

**Comment by sniffertine** [comment]
Hello all
I am not sure that implementing hashcode as 31 for DTOs ist necessary, since the id of DTOs normally does not change during usage. I would probably leave it as Objects.hashCode(getId());
