### ISSUE TITLE
Release 6.5.1 clean setup will generate liquibase change log

### ISSUE THREAD

**Issue by RobertMolenda** [jhipster/generator-jhipster#10885]
##### Release 6.5.1 clean setup will generate liquibase change log

A clean setup of JHipster will cause the first 'mvn liquibase:diff' to generate a change log

##### **Motivation for or Use Case**

After a clean stand up of JHipster - and prior to importing a jdl no database changes should be expected for the core application

##### **Reproduce the error**

(windows commands)
mkdir newapplication
cd newapplication
jhipster
(take defaults)
mvnw
cntl-C after application starts
mvn liquibase:diff

You will observe that a change set is generated for liquibase
[INFO] SELECT SEQUENCE_NAME FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_SCHEMA = 'PUBLIC' AND IS_GENERATED=FALSE
[INFO] select CONSTRAINT_NAME, COLUMN_LIST as COLUMN_NAME from information_schema.constraints where constraint_type='UNIQUE' and constraint_catalog='NEWPROJECT' and constraint_schema='PUBLIC' and table_name='JHI_USER' and constraint_name='UX_USER_LOGIN'
[INFO] select CONSTRAINT_NAME, COLUMN_LIST as COLUMN_NAME from information_schema.constraints where constraint_type='UNIQUE' and constraint_catalog='NEWPROJECT' and constraint_schema='PUBLIC' and table_name='JHI_USER' and constraint_name='UX_USER_EMAIL'
[INFO] C:\Blazent\Source\newproject\src\main\resources\config\liquibase\changelog\20191205131604_changelog.xml does not exist, creating
[INFO] Differences written to Change Log File, C:\Blazent\Source\newproject/src/main/resources/config/liquibase/changelog/20191205131604_changelog.xml
[INFO] ------------------------------------------------------------------------
[

##### **Related issues**

I saw a previous issue but it was closed - now I can't find it

##### **Suggest a Fix**

unsure of the core issue

##### **JHipster Version(s)**

6.5.1

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
newproject@0.0.1-SNAPSHOT C:\Blazent\Source\newproject
`-- generator-jhipster@6.5.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.blazent.newproject",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "newproject",
    "packageName": "com.blazent.newproject",
    "packageFolder": "com/blazent/newproject",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "spacelab",
    "clientThemeVariant": "primary",
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}

</pre>
</details><summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

git version 2.24.0.windows.2

node: v12.13.1

npm: 6.13.1

yeoman: 3.1.0

INFO! Congratulations, JHipster execution is complete!

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**

WIndows server 2016, Chrome

-   [X] Checking this box is mandatory (this is just to show you read everything)

The <date>_changelog.xml generated is:

    <changeSet author="Administrator (generated)" id="1575551790121-1">
        <dropUniqueConstraint constraintName="UC_JHI_USEREMAIL_COL" tableName="jhi_user"/>
        <addUniqueConstraint columnNames="email" constraintName="UC_JHI_USEREMAIL_COL" tableName="jhi_user"/>
    </changeSet>
    <changeSet author="Administrator (generated)" id="1575551790121-2">
        <dropUniqueConstraint constraintName="UC_JHI_USERLOGIN_COL" tableName="jhi_user"/>
        <addUniqueConstraint columnNames="login" constraintName="UC_JHI_USERLOGIN_COL" tableName="jhi_user"/>
    </changeSet>

**Comment by pascalgrimaud** [comment]
Closing this in favor of https://github.com/jhipster/generator-jhipster/issues/10887, as there are more comments thereu
If I'm wrong, don't hesitate to tell me
