### ISSUE TITLE
How is the language currently selected in ngx-translate available in API calls on the server side?

### ISSUE THREAD

**Issue by abenneke** [jhipster/generator-jhipster#10889]
##### **Overview of the issue**

When the user selects language X via `ngx-translate` `TranslateService` in the Angular UI and the application invokes a REST API call, how is X transported to the server side and available in/for Springs `MessageSource` (for example) during the REST API call processing?

##### **Motivation for or Use Case**

The REST API implementation wants to prepare the data returned and/or generate (error) messages in a language consistent with the UI.

We consider this being a standard problem and think it has already been solved – but we could not find a/the solution!? What did we miss? Any help and/or pointer would be appreciated. Thank you!

##### **Current implementation fragments**

What we found is the `LocaleConfiguration`, which looks like it should use a `NG_TRANSLATE_LANG_KEY` cookie – however such a cookie does not seem to exist? Do we have to enable it somewhere? Or is this for future use? Or a leftover from previous versions?

As an alternative the `LocaleConfiguration` is using a `language` parameter – but adding such a parameter to each and every REST API call does not appear to be a good solution to us?

Using the `Accept-Language` header could be another alternative, however this header is filled with the settings configured in the browser (and not the language selected in `ngx-translate`)?

##### **Related issues or PR**

We were not able to find any.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
I think it also would make sense to save the language the user selected in the frontend, such that they must not set it explicitly in the profile settings (https://github.com/jhipster/generator-jhipster/issues/10566).

**Comment by atomfrede** [comment]
@jhipster/developers From what I can tell, the current `AngularCookieLocaleResolver` is obsolete (as we don't set any cookie at all), so we can replace it with the default `CookieLocaleResolver` (which checks the accept langugage header if no cookie is present). We can decide to create cookie or send the correct accept language header in our api calls, which seems to be the current browser language (at least for angular). WDYT?

**Comment by pascalgrimaud** [comment]
it looks like an enhancement or feature request ?
anyway, it looks similar to https://github.com/jhipster/generator-jhipster/issues/10566 so I'm proposing to close this and discuss in the other ticket

**Comment by abenneke** [comment]
Thank you for looking into this.

However, I don't see this as a duplicate: What we were asking for here is having the selected language from the client side available on the server side during a REST call, which is not the case by default at the moment, AFAIK. 

#10566 is about persisting the selected language somewhere (local store, profile, ...). If the implementation of #10566 stores on the server side, this _might_ solve this as well - but if it stores in the browser, nothing is changed for this issue.
