### ISSUE TITLE
No default value one-to-many selectbox

### ISSUE THREAD

**Issue by Kelvijn** [jhipster/generator-jhipster#10884]
##### **Overview of the issue**

When you create an entity with a one-to-many relationship and then creating an entity, it looks like there is a value selected for the required relation, but when submitting you get an exception.
You have to select a value yourself.
##### **Motivation for or Use Case**

It should be clear to the user that you have to select a value instead of showing the first one in the list but not setting is as default value.
##### **Reproduce the error**
Create entity with one-to-many relation
Create an entity on the owning side
It will look like the first value is selected in the selectbox, but value is nog actually set.

##### **Suggest a Fix**
Show an empty selectbox instead of first element.

##### **JHipster Version(s)**

jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
xg-edfu-admin-website@0.0.1-SNAPSHOT /Users/calvinswinnen/Documents/projects/Qarad/xg_edfu_admin_website
└── generator-jhipster@6.4.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.qarad.edfu",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "monolith",
    "baseName": "xg_edfu_admin_website",
    "packageName": "com.qarad.edfu",
    "packageFolder": "com/qarad/edfu",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity AccessRight {
  name String required unique minlength(1) maxlength(30),
  displayName String required maxlength(50)
}
entity BusinessUnit {
  displayName String required minlength(1) maxlength(50),
  slug String required unique minlength(1) maxlength(20) pattern(/[A-Za-z0-9]+/)
}
entity Manufacturer {
  analyticsProperty String maxlength(255),
  creationDate Instant,
  deleted String maxlength(1),
  lastUpdate Instant,
  name String required unique minlength(1) maxlength(50),
  baseUrl String required maxlength(255),
  opsVersion String required maxlength(8),
  customUrl String maxlength(255)
}
entity Continent {
  isoCode String required unique minlength(2) maxlength(2),
  name String required unique minlength(1) maxlength(30)
}
entity Country {
  isoCode String required unique minlength(2) maxlength(2),
  name String required unique minlength(1) maxlength(50),
  fullName String required unique minlength(1) maxlength(50),
  iso3 String required unique minlength(3) maxlength(3),
  number String required unique minlength(3) maxlength(3),
  displayOrder Integer
}
entity InterfaceRegion {
  name String required unique minlength(1) maxlength(50)
}
entity InterfaceLanguage {
  name String required unique minlength(1) maxlength(20),
  isoCode String required unique minlength(2) maxlength(2)
}
entity UserGroup {
  name String required unique minlength(1) maxlength(30)
}
entity DocumentRegion {
  name String required unique minlength(1) maxlength(50)
}
entity DocumentLanguage {
  name String required unique minlength(1) maxlength(20),
  isoCode String required unique minlength(2) maxlength(2)
}
entity ProductType {
  name String required unique minlength(1) maxlength(30),
  slug String required unique minlength(1) maxlength(20) pattern(/[A-Za-z0-9]+/),
  active Boolean required
}
entity Product {
  keyCode String required unique minlength(1) maxlength(50)
}
entity ProductGroup {
  name String required unique minlength(1) maxlength(30)
}
entity Role {
  name String required unique minlength(1) maxlength(30),
  description String maxlength(255),
  predefined Boolean required
}
entity DocumentType {
  name String required minlength(1) maxlength(30),
  active Boolean required
}
entity Audience {
  name String required unique minlength(1) maxlength(30)
}
entity Document {
  name String required minlength(1) maxlength(100),
  number String maxlength(30)
}
entity File {
  name String required minlength(1) maxlength(255),
  s3objectKey String required minlength(1) maxlength(1024),
  version String required minlength(1) maxlength(20),
  date LocalDate required,
  validUntil LocalDate required,
  remarksActive Boolean required,
  remarks String maxlength(4000)
}
relationship OneToMany {
  Continent{countries} to Country{continent(name) required},
  BusinessUnit{interfaceRegions} to InterfaceRegion{businessUnit(displayName) required},
  Role{userGroups} to UserGroup{role(description)},
  BusinessUnit{documentRegions} to DocumentRegion{businessUnit(displayName) required},
  BusinessUnit{productTypes} to ProductType{businessUnit(displayName) required},
  ProductType{products} to Product{productType(name)},
  DocumentType{documents} to Document{documentType(name)}
}
relationship ManyToMany {
  BusinessUnit{interfaceLanguages(name)} to InterfaceLanguage{businessUnits(displayName)},
  BusinessUnit{documentLanguages(name)} to DocumentLanguage{businessUnits(displayName)},
  InterfaceRegion{interfaceCountries(name) required} to Country{interfaceRegions},
  UserGroup{businessUnits(displayName)} to BusinessUnit{userGroup(name)},
  UserGroup{users(email)} to User,
  DocumentRegion{documentCountries(name) required} to Country{documentRegions},
  Product{productGroups(name)} to ProductGroup{products},
  Role{accessRights(displayName)} to AccessRight{roles(name)},
  DocumentType{audience(name)} to Audience{documentType(name)},
  Document{productGroups(name)} to ProductGroup{documents(name)},
  Document{files(name)} to File{documents(name)},
  File{countries(name)} to Country{files(name)},
  File{documentLanguages(name)} to DocumentLanguage{files(name)}
}

dto AccessRight, BusinessUnit, Manufacturer, Continent, Country, InterfaceRegion, InterfaceLanguage, UserGroup, DocumentRegion, DocumentLanguage, ProductType, Product, ProductGroup, Role, DocumentType, Audience, Document, File with mapstruct
service AccessRight, BusinessUnit, Manufacturer, Continent, Country, InterfaceRegion, InterfaceLanguage, UserGroup, DocumentRegion, DocumentLanguage, ProductType, Product, ProductGroup, Role, DocumentType, Audience, Document, File with serviceImpl
readOnly AccessRight, Manufacturer, Continent, Country, InterfaceLanguage, DocumentLanguage

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20191017_369 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)

git version 2.21.0 (Apple Git-122)

node: v12.1.0

npm: 6.13.0

yeoman: 3.1.1

yarn: 1.16.0

Docker version 19.03.4, build 9013bf5

docker-compose version 1.24.1, build 4667896b

**Comment by qmonmert** [comment]
@Kelvijn I tried to reproduce but it seems to work, the selectbox are empty by default and it means that there is no value 
![image](https://user-images.githubusercontent.com/9989211/70378033-ff85ed80-191b-11ea-9383-ea734fd445a5.png)

**Comment by Kelvijn** [comment]
Hmm I see, did you make customer a required field?

**Comment by qmonmert** [comment]
@Kelvijn you updated the front (react) after that you generate the entity ?

**Comment by qmonmert** [comment]
@Kelvijn if you add "required" like this : 
`AvInput id="car-owner" type="select" required`
no default value is selected

![image](https://user-images.githubusercontent.com/9989211/70866036-d0e3c480-1f64-11ea-8758-b7d1b6a7be6f.png)

cc @pascalgrimaud

**Comment by pascalgrimaud** [comment]
Let's close this as I don't see any issue here, until we have more feedback or steps to reproduce
