### ISSUE TITLE
Reword Compass Question

### ISSUE THREAD

**Issue by fredcooke** [jhipster/generator-jhipster#1088]
Rather than:

"Would you like to use the Compass CSS Authoring Framework?"

Which gives me the impression of CSS-free HTML, reword as a selection like many of the other technology questions:

"Would you like to use Compass, Sass, or Less for CSS processing/production?" or similar, as appropriate.

I've not dug through, however I'm still wondering exactly what was generated, and how. I'm guessing plain SASS?

Big thumbs up for jhipster, it's very very nice indeed! :-)

**Comment by jdubois** [comment]
The official generator asks:

'Would you like to use Sass (with Compass)?'

See https://github.com/yeoman/generator-angular/blob/master/app/index.js#L145

I find it better to write it's a CSS authoring framework (as it's how they describe it at http://compass-style.org/ ) as I find it clearer. Personally I had no idea what Compass was the first time I saw this question, and the name is too vague.

**Comment by fredcooke** [comment]
My point is: If you say no, what DO you get? No CSS? How can someone with only superficial knowledge make a good choice (even with searching) if there is nothing to get the search to define for you? For example, I'd never heard of Hazelcast, but was quickly able to make a good informed choice after searching for it. I have heard of LessCSS, SASS, Compass, and CSS raw, but did not understand what actions would be taken based on my choice. Same applies to the "official" one (I assume you mean official angularJS one), which is vague too. As with all feedback, you may do what you like with it, including nothing. But I wanted to share it as I felt a useful improvement could be made at low dev cost.

**Comment by fredcooke** [comment]
And I definitely wanted a CSS processor (probably SASS, but...), not straight CSS, so this was an important branch point for me.
