### ISSUE TITLE
jhipster ci-cd generates jenkins.yml with a deprecated jenkins image

### ISSUE THREAD

**Issue by mohamedzaki90** [jhipster/generator-jhipster#10898]
##### **Overview of the issue**
When using jhipster ci-cd it generates a docker compose jenkins.yml file with jenkins:latest
this image is now deprecated in favor of the jenkins/jenkins:lts

The current jenkins image does not install the suggested plugins and fail with errors

##### **Motivation for or Use Case**
The jenkins.yml is very useful for local dev and testing

##### **Reproduce the error**
use jhipster ci-cd in a generated project and see the image field in the generated jenkins.yml

##### **Suggest a Fix**
modify the image to be jenkins/jenkins:lts

##### **JHipster Version(s)**
6.5.1

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@mohamedzaki90 : would you like to submit a PR with your proposal plz ?

**Comment by mohamedzaki90** [comment]
@pascalgrimaud I  tried to push a new branch with the fix to make a pr but I got denied.
Push failed
Remote: Permission to jhipster/generator-jhipster.git denied to mohamedzaki90.

**Comment by pascalgrimaud** [comment]
@mohamedzaki90 : thanks for trying to contribute !!

In fact, you can't push directly to jhipster/generator-jhipster ; you need to fork first the generator, then you'll be able to push to your fork: mohamedzaki90/generator-jhipster

Then, you'll be able to submit a PR here :)

Don't hesitate to ask if you need help or didn't understand my instructions

**Comment by mohamedzaki90** [comment]
https://github.com/jhipster/generator-jhipster/pull/10990

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/generator-jhipster/pull/10990
