### ISSUE TITLE
JDL enum creation cannot have CustomValues

### ISSUE THREAD

**Issue by RobertMolenda** [jhipster/generator-jhipster#10903]
##### **Overview of the issue**

A clean project install and import of an enum with custom values will fail

##### **Motivation for or Use Case**

Documentation indicates it is a valid syntax to have

##### **Reproduce the error**

(windows commands)
mkdir newapplication
cd newapplication
jhipster
(take defaults)
mvnw
cntl-C after application starts

Add the JDL file (mentioned below) via:
jhipster -import-jdl <the jdl file>

You will receive the following error:
SyntaxError: ',' expected. (2:6)
  1 | export const enum EntryStatus {
> 2 |   NEW(New) = 'NEW(New)',
    |      ^
  3 |   PENDING(Pending) = 'PENDING(Pending)',
  4 |   MAPPED(Mapped) = 'MAPPED(Mapped)'
  5 | }
    at e (C:\Blazent\Source\jhipsterdemo\node_modules\generator-jhipster\node_modules\prettier\parser-typescript.js:1:267)
    at Object.parse (C:\Blazent\Source\jhipsterdemo\node_modules\generator-jhipster\node_modules\prettier\parser-typescript.js:1:2172547)
    at Object.parse$2 [as parse] (C:\Blazent\Source\jhipsterdemo\node_modules\generator-jhipster\node_modules\prettier\index.js:10639:19)
    at coreFormat (C:\Blazent\Source\jhipsterdemo\node_modules\generator-jhipster\node_modules\prettier\index.js:13856:23)
    at format (C:\Blazent\Source\jhipsterdemo\node_modules\generator-jhipster\node_modules\prettier\index.js:14115:73)
    at formatWithCursor (C:\Blazent\Source\jhipsterdemo\node_modules\generator-jhipster\node_modules\prettier\index.js:14131:12)
    at C:\Blazent\Source\jhipsterdemo\node_modules\generator-jhipster\node_modules\prettier\index.js:42399:15
    at Object.format (C:\Blazent\Source\jhipsterdemo\node_modules\generator-jhipster\node_modules\prettier\index.js:42418:12)
    at C:\Blazent\Source\jhipsterdemo\node_modules\generator-jhipster\generators\generator-transforms.js:44:39

##### **Related issues**

Search didn't find any current issues

##### **Suggest a Fix**

Unsure of proper fix or if feature was not released along with the documentation

##### **JHipster Version(s)**

6.5.1

##### **JHipster configuration**
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

JHipster Version(s)
newproject@0.0.1-SNAPSHOT C:\Blazent\Source\newproject
`-- generator-jhipster@6.5.1

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

entity Sample {
  name String
  theEnum SampleEnum
}

enum {
  TEST (Test),
  DEV (Dev),
  PROD (Prod)
}

##### **Browsers and Operating System**

Windows data center 2016 / Chrome

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
The enum must have a name, you forgot to add one in your sample.
By the way, the error doesn't reflect what's in your sample...

**Comment by MathieuAA** [comment]
Check this example for instance:

```jdl
enum EnvironmentType {
  ARCHIVE (archive),
  DEV (development),
  INTEGRATION (integration),
  PROD (production),
  TEST (test),
  UAT (uat),
  NON_PROD (nonProd)
}

entity Environment {
  type EnvironmentType required
}
```

**Comment by RobertMolenda** [comment]
Pasted the above directly into my jdl file and received:

    force src\main\webapp\app\entities\entity.module.ts
SyntaxError: ',' expected. (2:10)
  1 | export const enum EnvironmentType {
> 2 |   ARCHIVE(archive) = 'ARCHIVE(archive)',
    |          ^
  3 |   DEV(development) = 'DEV(development)',
  4 |   INTEGRATION(integration) = 'INTEGRATION(integration)',
  5 |   PROD(production) = 'PROD(production)',
    at e (C:\Blazent\Source\jhipsterdemo\node_modules\generator-jhipster\node_modules\prettier\parser-typescript.js:1:267)

**Comment by RobertMolenda** [comment]
FYI:
npm --version prettier
6.13.1

**Comment by MathieuAA** [comment]
Seems like the generation isn't working. Let me check.

**Comment by MathieuAA** [comment]
Confirmed, working on it

**Comment by MathieuAA** [comment]
This was a pain in the ass, but I think I've fixed this bug (https://github.com/MathieuAA/generator-jhipster/tree/fix/10903).
I'll polish and finish it tomorrow.

Thanks again for reporting it.

**Comment by MathieuAA** [comment]
Thank you @wmarques
