### ISSUE TITLE
Prettier tabWitdh and files under .github/workflows

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#10905]
##### **Overview of the issue**

If upgrading Prettier to 1.18.2 then to fix lint errors I was forced to execute `npm run lint-fix` and then I noticed that files under https://github.com/jhipster/generator-jhipster/tree/master/.github/workflows are indented with `tabWidth=2` (some sub elements are accidentally with 4 spaces) but `.prettierrc` states that `tabWidth=4`, should we reformat files under `.github/workflows` with `tabWidth=4` or switch `.prettierrc` to `tabWidth=2` and reformat all generator files with `tabWidth=2`?

##### **Motivation for or Use Case**

`npm run lint-fix` should not show differences in generator-jhipster.

##### **Reproduce the error**

`npm run lint-fix`

##### **Suggest a Fix**

Possible solutions are described in the overview part.

##### **JHipster Version(s)**

Current master.

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
I would vote to switch the github workflow to match with the prettier config.

**Comment by kaidohallik** [comment]
I somehow missed this last comment, created PR #11007 now.
