### ISSUE TITLE
If generator and generated app are using different Prettier version then regeneration can show differences

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#10902]
##### **Overview of the issue**

If generator and generated app Prettier version differ, which is the case ATM:

* generator-jhipster: 1.16.4
* Angular: 1.18.2
* React: 1.18.2

then on regeneration can occur differences if not skipping Git commit hooks, because:

* on initial generation is app committed to Git which runs Prettier in generated app
* on regeneration Git commit is not done and sources are formatted only with generator Prettier

This is the case ATM, in Angular part `.yo-rc.json` and `page-ribbon.component.ts` are formatted differently in Prettier 1.16.4 and 1.18.2

##### **Motivation for or Use Case**

If files are not changed then no differences should be shown.

##### **Reproduce the error**

1. Generate app with the configuration pasted to this issue: `jhipster`
2. Regenerate app: `jhipster --force`

##### **Related issues**

Didn't fine.

##### **Suggest a Fix**

2 solutions:

* Solution 1. Keep generator and generated app Prettier in sync.
* Solution 2. Add the following command to `end()` function in client generator (and maybe make this optional, for example run only if new switch `--prettier` is specified?):
```
this.spawnCommandSync(this.clientPackageManager, ['run', 'prettier:format']);
```

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT C:\projects\teest\strict-shared
`-- generator-jhipster@6.5.1  -> c:\projects\kaido-github\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1575892239104,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": ["et", "en", "ru"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount {
  name String required,
  bankNumber Integer,
  agencyNumber Long,
  lastOperationDuration Float,
  meanOperationDuration Double,
  balance BigDecimal required,
  openingDay LocalDate,
  lastOperationDate Instant,
  active Boolean,
  accountType BankAccountType,
  attachment AnyBlob,
  description TextBlob
}
entity TheLabel {
  labelName String required minlength(3)
}
entity Operation {
  date Instant required,
  description String,
  amount BigDecimal required
}
entity Department {
  name String required,
  description TextBlob,
  advertisement AnyBlob,
  logo ImageBlob
}
/**
 * JobHistory comment.
 */
entity JobHistory {
  startDate ZonedDateTime,
  endDate ZonedDateTime,
  language Language
}
entity Job {
  title String minlength(5) maxlength(25),
  type JobType,
  minSalary Long,
  maxSalary Long
}
/**
 * The Employee entity.\nSecond line in javadoc.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate ZonedDateTime,
  salary Long,
  commissionPct Long
}
entity Location {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Task {
  title String,
  description String
}
entity GoldenBadge {
  name String
}
entity SilverBadge {
  name String
}
entity Identifier {
  name String required unique
}
entity Country {
  name String
}
entity Region {
  name String
}
enum BankAccountType {
  CHECKING,
  SAVINGS,
  LOAN
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}
enum JobType {
  BOSS,
  SLAVE
}

relationship OneToOne {
  Department{location} to Location,
  Employee{user(login)} to User with jpaDerivedIdentifier
}
relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)},
  Employee{job} to Job{emp(lastName)},
  /**
   * A relationship
   */
  Department{employee} to
  /**
   * Another side of the same relationship,
   */
  Employee{department},
  Location{country} to Country{location},
  Country{area} to Region{country}
}
relationship ManyToOne {
  BankAccount{user(login)} to User,
  Employee{manager(lastName)} to Employee,
  Employee{sibag(name) required} to SilverBadge,
  Employee{gobag(name) required} to GoldenBadge,
  GoldenBadge{iden(name) required} to Identifier,
  SilverBadge{iden(name) required} to Identifier
}
relationship ManyToMany {
  Operation{theLabel(labelName)} to TheLabel{operation},
  JobHistory{department} to Department{history},
  JobHistory{job} to Job{history},
  JobHistory{emp(firstName)} to Employee{history},
  Job{chore(title)} to Task{linkedJob(title)}
}

dto BankAccount, Department, Employee, Location, GoldenBadge, SilverBadge, Identifier, Country, Region with mapstruct
service BankAccount, Location, Country with serviceImpl
service TheLabel, Department, Employee, GoldenBadge, SilverBadge, Identifier, Region with serviceClass
angularSuffix BankAccount with mySuffix
filter BankAccount, Employee
clientRootFolder BankAccount, TheLabel, Operation with test-root
paginate TheLabel, Job with pagination
paginate Operation, JobHistory, Employee with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

git version 2.24.0.windows.2

node: v12.13.0

npm: 6.11.3

yeoman: 2.0.6

yarn: 1.17.3

Docker version 19.03.5, build 633a0ea

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I have reproduced this by generating a default app without `--skip-install`, then `.yo-rc.json` and `page-ribbon.component.ts` show staged changes.  

Was not sure where this was coming from until now.  I usually generate my apps with `--skip-install`, which prevents this issue from happening.

Solution 1 is simple but could regress in the future if we don't upgrade `prettier` at the same time.  Would solution 2 work with apps that don't call `npm install` during generation?

**Comment by kaidohallik** [comment]
@ruddell, I guess that we can't run Prettier if install is not done (install is skipped), because then Prettier may not be installed yet.

After thinking more about that problem I believe that we should try to keep Prettier versions in generator and in generated projects in sync because:
* generation is faster without that additional step
* if user has some own custom files (not generated by JHipster) in application folder then user may not want that these files are automatically formatted by JHipster

I investigated this further and seems that here is 2 nuances:
* `.yo-rc.json`: seems that from some version of Yeoman/Prettier arrays in json are formatted differently by these tools and as `.yo-rc.json` is not formatted by the generator then `.yo-rc.json` is shown as changed after regeneration
* `page-ribbon.component.ts` - Prettier 1.16.4 and 1.18.2 are formatting differently

So solution to achieve consistent generation is:
* add additional step at the end of generation process where `.yo-rc.json` is formatted by Prettier
* upgrade generator-jhipster to Prettier 1.18.2

I made PR #10904 with that fix.
