### ISSUE TITLE
Can't deploy jwt secured monolith because of unbound base64Secret

### ISSUE THREAD

**Issue by mohamedzaki90** [jhipster/generator-jhipster#10906]
##### **Overview of the issue**
When generating a sample app with jwt security option. the artifact of `mvnw -Pprod -DskipTests package` is not deployable and the following error appears in the console

~~~
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenProvider' : Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Decode argument cannot be null.
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1255)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
vb-be162fa3 => 2019-12-10 12:55:17.279  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
vb-be162fa3 => 2019-12-10 12:55:17.279  ... 25 common frames omitted
vb-be162fa3 => 2019-12-10 12:55:17.279 Caused by: java.lang.IllegalArgumentException: Decode argument cannot be null.
vb-be162fa3 => 2019-12-10 12:55:17.279  at io.jsonwebtoken.lang.Assert.notNull(Assert.java:82)
vb-be162fa3 => 2019-12-10 12:55:17.279  at io.jsonwebtoken.io.ExceptionPropagatingDecoder.decode(ExceptionPropagatingDecoder.java:19)
vb-be162fa3 => 2019-12-10 12:55:17.279  at com.jdldemos.security.jwt.TokenProvider.afterPropertiesSet(TokenProvider.java:53)
~~~

##### **Motivation for or Use Case**
Can't use mvnw -Pprod -DskipTests package to package a deployable war for boxfuse

##### **Reproduce the error**
generate a sample monolith with jwt security option and execute mvnw -Pprod -DskipTests package and try to deploy it with boxfuse

##### **Suggest a Fix**
the issue occures because of null param in TokenProvider.afterPropertiesSet() line: 53

##### **JHipster Version(s)**
6.5.1

##### **Browsers and Operating System**
Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Have you defined `base64-secret` property in your `application-prod.yml` ?

**Comment by mohamedzaki90** [comment]
@gmarziou it's already defined but I just noticed that boxfuse use active profile: boxfuse
I then added a new application-boxfuse.yml with the jhipster properties section and this specific issue seems to be eliminated

**Comment by gmarziou** [comment]
Did you follow this guide? https://www.jhipster.tech/boxfuse/#deploying-to-aws-with-boxfuse

**Comment by mohamedzaki90** [comment]
Yes, which took so long to discover the exception after creating the required instances.
Currently, I'm trying to run locally by following https://boxfuse.com/getstarted/jhipster.
Although I managed to resolve that specific issue by creating boxfuse profile, I'm not sure if this is the solution.
Running `boxfuse run -env=Prod` runs on aws.

I'm just wondering that nothing mentioned about that in the guide

**Comment by gmarziou** [comment]
I guess it's something to ask BoxFuse, their guide does not mention any publication date so maybe they need to update it, have you contacted them?

**Comment by pascalgrimaud** [comment]
I'm closing this as it's related to BoxFuse.
Don't hesitate to give feedback if you think there is an issue in our generator
