### ISSUE TITLE
Add [skip ci] and [ci skip] for GitHub CI

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10923]
##### **Overview of the issue**

An idea I got after reading the following conversation by @pascalgrimaud and @deepu105; https://github.com/jhipster/generator-jhipster/pull/10920#issuecomment-565118390

Currently it seems that when a commit is made, keywords such as [skip ci] and [ci skip] is not honored by the Github CI builds. Now the Azure builds [do follow them](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#skipping-ci-for-individual-commits). 

So we need to add a custom command for GitHub builds to skip when encountering [skip ci] and [ci skip]

##### **Motivation for or Use Case**

Stop unnecessary builds being triggered. 

##### **Reproduce the error**

Create a test branch in your fork and do a commit with [skip ci] or [ci skip].

##### **Related issues**

https://github.com/jhipster/generator-jhipster/pull/10920

##### **Suggest a Fix**

Please see associated PR. 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
If this is all in agreement; I can go ahead and add this to our other repositories as well. Let me know. :smile:

**Comment by pascalgrimaud** [comment]
FYI, I didn't migrate the other repo to GitHub Actions yet, but yes, this change should be included by default to all our CI

**Comment by SudharakaP** [comment]
@pascalgrimaud : Okay when we do migrate we'll add it. I was also wondering, shall we add this to our README file as well? :thinking:

**Comment by deepu105** [comment]
Yes we can
