### ISSUE TITLE
YARN process crashes after adding a new angular module to the project

### ISSUE THREAD

**Issue by andreasfranz** [jhipster/generator-jhipster#10929]
##### **Overview of the issue**

The yarn process sometimes stops working when adding a new angular module.

##### **Motivation for or Use Case**

During development it is annoying to restart the yarn process after it crashed.

##### **Reproduce the error**

Unfortunately it is a bug that just happens from time to time. Maybe it' a race conditions or unhandled in the `@typescript-eslint/eslint-plugin`. 
I tried an upgrade to @typescript-eslint/eslint-plugin to version 2.6.1 and that helped with the issue

##### **Related issues**

https://github.com/jhipster/generator-jhipster/pull/10232

##### **JHipster Version(s)**

6.5.1

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "de",
      "microservicePath": "../backend/"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "gateway",
    "baseName": "toolbox",
    "packageName": "com.example",
    "packageFolder": "com/example/",
    "serverPort": "8082",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "yarn",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "de"],
    "blueprints": []
  }
}

##### **Browsers and Operating System**

macOS Catalina 10.15.1
Google Chrome 78.0.3904.108

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
This should be fixed by https://github.com/jhipster/generator-jhipster/pull/10798, which is part of v6.5.1.  

Can you confirm?  Or do you have a specific error message?

**Comment by pascalgrimaud** [comment]
I'm closing this as I think it's solved.
Don't hesitate to reopen and provide more information if it's not the case

**Comment by andreasfranz** [comment]
@pascalgrimaud thanks for the quick reply that was the exact issue.
