### ISSUE TITLE
Handling of SASS files

### ISSUE THREAD

**Issue by andreasfranz** [jhipster/generator-jhipster#10928]
##### **Overview of the feature request**

I would like to suggest some small improvements. When using JHipster with SASS support enabled (`"useSass": true` in .yo.rc file) .scss files are generated to `src/main/wepapp/content.` 

The .scss files are bundled to the production artifact and are also accessible in a production environment. (e.g. http://localhost/content/scss/global.scss)

Maybe it would also be a good idea to move the scss files to another directory since they are actually source files that are compiles to css and then should be in the `src/main/wepapp/content ` folder.

##### **Motivation for or Use Case**

First of all the production build will be smaller by not including .scss files and moving the .scss files away from the content directory may also give a clearer project structure.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/2869

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
I agree that we should not include those files in the prod build.
However, it's not a big issue as they're not used in the index.html so they are never downloaded by the client, so this doesn't affect client-side performances.

**Comment by pascalgrimaud** [comment]
@andreasfranz : so if I understand well, the only optimization would be to decrease the size of the Jar file. In this case, do you want to contribute and improve the packaging part ? You need to have a look at Angular, React and Vue.js too plz ?

**Comment by pascalgrimaud** [comment]
no more comment, so I'm closing this for lack of interest
Feel free to provide a PR if you want
