### ISSUE TITLE
Update ng-bootstrap

### ISSUE THREAD

**Issue by andreasfranz** [jhipster/generator-jhipster#10930]
##### **Overview of the feature request**

The latest bugfix releases introduced various bugfixes (see https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md)

##### **Motivation for or Use Case**

There are various bug fixes including a lot of improvements regarding modal popups that affect our project.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@andreasfranz : can you propose a PR with this upgrade this plz ?
