### ISSUE TITLE
Do We have any plan for Quarkus?

### ISSUE THREAD

**Issue by unikzforce** [jhipster/generator-jhipster#10943]
##### **Overview of the feature request**

Can you please have a look at the RedHats' Quarkus project?
[Quarkus.io](http://www.quarkus.io) seems to be very promising.

AOT, high speed , and native stuff is promised when using quarkus+graalvm

##### **Motivation for or Use Case**

It meens that lighter and faster java. So java is no more Cold Start monster anymore.

##### **Related issues or PR**

-   [+ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
We are already in contact with the quarkus team as far as I know. Currently we are waiting for a reference application we can use to create a blueprint and the templates.

**Comment by unikzforce** [comment]
Awesome, So, I'll just close this one
