### ISSUE TITLE
[HazelCast] Unable to login after logout

### ISSUE THREAD

**Issue by scarlson-synegen** [jhipster/generator-jhipster#1094]
* Overview
After logging out of unmodified JHipster installation, I am unable to login again until I refresh the login page 1 or 2 times. Before the page refreshes, it always produces the error "Authentication failed! Please check your credentials and try again.".

 From the UI, logout appears to work correctly, but an exception is thrown in the backend: "java.lang.IllegalStateException: invalidate: Session already invalidated".

* JHipster Version
2.1.1

* OS and Browser
Mac OS X Yosemite - Firefox - Chrome

* Steps to Reproduce
0.a generate system using .yo-jc.json below
0.b build: mvn -Pprod clean package install
0.c run: mvn -Pprod spring-boot:run
1 login as admin/admin or user/user
2 click Logout in Account menu to logout
3 Click the "authenticate" link to return to login page
4 enter valid credentials to login (e.g. admin/admin or user/user) -> this will fail until the page is refreshed once or twice

* .yo-rc.json
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "useCompass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8"
  }
}

**Comment by jdubois** [comment]
Maybe this is linked to HazelCast, this is the only "uncommon" option you have -> could you try without HazelCast, to see if it's the culprit?

**Comment by scarlson-synegen** [comment]
Yes, with all the generator settings the same except clusteredHttpSession set to "no" instead of "hazelcast", the problem does not occur.

Note that the initial description is incorrect in that the problem is not about login, but is rather about logout. Turns out that logout is not working at all, and if the page is immediately refreshed after logout, you can see that the user is still logged in to the system.

**Comment by jimbobwyatt** [comment]
Could be an underlying system issue with token generation/expiration/invalidation. I'm on Fedora with all the latest bits and don't have this issue.

**Comment by scarlson-synegen** [comment]
Issue seems to be due to this bug in hazelcast when using Tomcat 8:
https://github.com/hazelcast/hazelcast/issues/3742

I deployed to Tomcat 7 and the issue is not present.
The fix for this issue is in hazelcast v3.4 (JHipster currently uses hazelcast 3.3.3). I built using hazelcast 3.4 and deployed to Tomcat 8, and the issue is also not present.

**Comment by jdubois** [comment]
OK, I'm adding "hazelcast" to the bug title -> @scarlson-synegen do you confirm that updating to Hazelcast 3.4 solves the issue? In that case we will need to upgrade the template

**Comment by scarlson-synegen** [comment]
Yes, updating to HazelCast 3.4 solves the problem.

Note that a code change is necessary when going to 3.4 - in file _CacheConfiguration.java:

1) need to add [wrapped in -> if (hibernateCache == 'hazelcast')]
import com.hazelcast.config.EvictionPolicy;

and 2) change:
mapConfig.setEvictionPolicy(MapConfig.EvictionPolicy.LRU);

to:
mapConfig.setEvictionPolicy(EvictionPolicy.LRU);

Note that I have not fully tested with multiple nodes where sessions are actually being clustered, but I have confirmed that the initial problem is resolved when using a single node system. I will not have time to do more thorough testing for a week or more.

**Comment by jdubois** [comment]
I upgraded to HazelCast 3.4 and

- I didn't have to do the changes you mention (and anyway I don't understand why I would need to do them)
- I have some "fatal" error warning, and a new stacktrace telling me my session is already invalided, but this all seem to work correctly

As such, I'm commiting this and closing this ticket at the same time, but we need to watch out those errors -> if you can test and give us some feedback, it's welcome!!

**Comment by jdubois** [comment]
Sorry I did a mistake... Give me some time to sort this out, sorry!!!!

**Comment by scarlson-synegen** [comment]
Make sure that you have the hibernateCache set to hazelcast also. That is when the additional changes are necessary. Hazelcast seems to have moved the EvictionPolicy enum to a separate class (as opposed to being in MapConfig).
