### ISSUE TITLE
Missing spring-boot plugin 2.1.10.RELEASE

### ISSUE THREAD

**Issue by skmaingi** [jhipster/generator-jhipster#10969]
##### **Overview of the issue**

[INFO] Scanning for projects...
[WARNING] The POM for org.springframework.boot:spring-boot-maven-plugin:jar:2.1.10.RELEASE is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.springframework.boot:spring-boot-maven-plugin:2.1.10.RELEASE: Plugin org.springframework.boot:spring-boot-maven-plugin:2.1.10.RELEASE or one of its dependencies could not be resolved: Failure to find org.springframework.boot:spring-boot-maven-plugin:jar:2.1.10.RELEASE in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[WARNING] The POM for org.springframework.boot:spring-boot-maven-plugin:jar:2.1.10.RELEASE is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.springframework.boot:spring-boot-maven-plugin:2.1.10.RELEASE: Plugin org.springframework.boot:spring-boot-maven-plugin:2.1.10.RELEASE or one of its dependencies could not be resolved: Failure to find org.springframework.boot:spring-boot-maven-plugin:jar:2.1.10.RELEASE in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 6.0 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 kB at 9.0 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.302 s
[INFO] Finished at: 2019-12-14T01:30:25+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/developer2/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

##### **Motivation for or Use Case**

The bug is generated when running a new JHipster application

##### **Reproduce the error**
Steps:

1. Install generator-jhipster on Ubuntu OS using _npm install -g generator-jhipster_
2. Create JHipster application by running _jhipster_ command in project's directory
3. Run _./mvnw_ 

##### **Suggest a Fix**

Use Spring Boot 2.1.9.RELEASE

##### **JHipster Version(s)**

6.5.1

##### **JHipster configuration**

        <maven.version>3.3.9</maven.version>
        <java.version>1.8</java.version>
        <node.version>v12.13.0</node.version>
        <npm.version>6.13.0</npm.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <project.testresult.directory>${project.build.directory}/test-results</project.testresult.directory>
        <maven.build.timestamp.format>yyyyMMddHHmmss</maven.build.timestamp.format>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <argLine>-Djava.security.egd=file:/dev/./urandom -Xmx256m</argLine>
        <m2e.apt.activation>jdt_apt</m2e.apt.activation>
        <run.addResources>false</run.addResources>
        
        <profile.no-liquibase />
        <profile.swagger />
        <profile.tls />

        
        <jhipster-dependencies.version>3.0.7</jhipster-dependencies.version>
        
        <spring-boot.version>2.1.10.RELEASE</spring-boot.version>
        
        <spring.version>5.1.11.RELEASE</spring.version>

##### **Browsers and Operating System**

Ubuntu Xenial OS

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
It's most likely an issue with corrupt download. You can remove directory `~/.m2/repository/org/springframework/boot/spring-boot-maven-plugin/` from local maven repository and try again.

**Comment by skmaingi** [comment]
Thank you @vishal423

> It's most likely an issue with corrupt download. You can remove directory `~/.m2/repository/org/springframework/boot/spring-boot-maven-plugin/` from local maven repository and try again.

Thank you @vishal423
