### ISSUE TITLE
App with session authentication can infinite loop if server responses inadequately

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#10964]
##### **Overview of the issue**

If using session authentication and in some reason server responses in logout endpoint with HTTP error 401 then `auth-expired.interceptor` runs to infinite loop which causes browser crash.

##### **Motivation for or Use Case**

Client application should survive server inadequate responses. Just in case...

##### **Reproduce the error**

I was able to reproduce this in the following manner:
* create client with session authentication
* create server with jwt authentication

##### **Related issues**

Similar problem was reported for UAA in #6882 and this was fixed by #6890

##### **Suggest a Fix**

In #6890 was this for UAA solved by not doing logout in server any more if `auth-expired.interceptor` is catching 401 error.

I believe that better solution is to do both for UAA and session auth:
* try logout from server just in case
* in logout function catch error and continue silently

##### **JHipster Version(s)**

Current master.

##### **Browsers and Operating System**

Windows 10, Chrome 79

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
adding a bounty as it's a bug and it needed to be solved before the next release if possible

**Comment by kaidohallik** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/12570
