### ISSUE TITLE
Remove process.exit uses.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#10963]
##### **Overview of the feature request**

Remove process.exit uses and handle process shutdown cleanly.

##### **Motivation for or Use Case**

Node.js process.exit is not recommended because it has side effects https://nodejs.org/api/process.html#process_process_exit_code.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/10934
https://github.com/jhipster/generator-jhipster/pull/10956
https://github.com/jhipster/generator-jhipster/pull/10944
https://github.com/jhipster/generator-jhipster/pull/10961

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@pascalgrimaud I think we should go ahead and merge both PRs.

**Comment by pascalgrimaud** [comment]
OK @mshima : I'm waiting the rebase for the green CI :heavy_check_mark:

**Comment by pascalgrimaud** [comment]
Closing this as both PRs have been merged
