### ISSUE TITLE
Feature: automatically add new script to index.html

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1098]
When I create a new controller or any other js file, I'd like grunt serve to update the index.html to import the new file and the browser to reload.

**Comment by andidev** [comment]
That would be a great feature. Unfortunately wiredep does not handle that since it only deals with injecting files mentioned in the bower.json file. 
The reason why is probably because it doesn't know in which order to inject the files if they are dependent on each other. 
Would be nice to have to be able do define the dependencies in a comment at the top of the file and let wiredep read those. Maybe a feature to suggest in the wiredep project. 

An alternative for achieving this would be to use requirejs. But then we would have dynamically loading of resource files with a lot of http request. But this also comes with some other obligations.

**Comment by gmarziou** [comment]
Don't you think that the the order should be quite simple: first app.js then your other files?
If we wanted to go further we could benefit from our conventions by including components first (to include services, filters, etc...), then controllers, then states.

I will have a look at [grunt-include-source](https://github.com/jwvdiermen/grunt-include-source)

**Comment by andidev** [comment]
You are right, grunt-include-source looks really promising for this task! Did not know about such a plugin. Setting the ordering option from top-down will solve that app.js is ordered first. 

I say let's go for this!

**Comment by gmarziou** [comment]
I got it working on freshly generated app: https://github.com/gmarziou/jhipster-inc-source

It works on `grunt build` and `grunt serve` for added and deleted scripts.
It's a joy to use.

I'll do more tests and integrate this into the generator, the steps are:

    - add grunt-include-source as dev dependency to package.json
    - add special comments in index.html
    - add task and configuration in Gruntfile.js

You can see changes in [this commit](https://github.com/gmarziou/jhipster-inc-source/commit/5c48e78ad9f935f7842040b74788c52f209d67ea)

**Comment by andidev** [comment]
Nice! Is it possible to do the same thing in gulp? 

Maybe the same configuration should be used for the app css files as well? Today there is no folder structure for page specific css styles. Everything is put in a main.css file. Is this really the best practice?

**Comment by gmarziou** [comment]
There is [gulp-include](https://github.com/wiledal/gulp-include) and [gulp-include-source](https://github.com/gil/gulp-include-source), ideally it would have been great to find a tool using same comments in the HTML but I doubt it exists. I'll build a prototype.

Regarding CSS organisation, I have mixed feelings about it I am used to Rails practice wherre you have a main css for the app and a css per controller/model, in my experience the per model css files are often empty otherwise it could be a code smell that you are relying more on id selectors rather than on classes.
You could still split in files but the question is whether to put all your files under `assets` or close to the view under app. The fact is that there is no logical link between your CSS and your view as the css are all included by the index.html, it would be only a convention.
So finally, I'd be in favor to let the CSS or SASS files in the assets folder and let the developer decide whether to split up for easier maintenance but I'd be inetersted to hear whet others say.

**Comment by jdubois** [comment]
I don't understand what you mean, because this all works for me... It has always worked, in fact!

Maybe I don't understand what you mean, so here is what I do:

1- run the app with "mvn spring-boot:run"
2- do a "grunt serve"
3- do a "yo jhispter:entity Foo"

-> the browser automatically refreshes, and I have the "foo" entity in my menu, and if I click on it I can see the page, etc.. Of course I need to reload the Maven server if I want the server to handle the requests, but the front end works

**Comment by gmarziou** [comment]
This works because you use the generator which automatically inserts newly created js files into teh index.html.
Now just create a filter or a directive, this can be done only by creating a new file from your editor, with the change I propose grunt will insert into the index.html the new file and trigger a browser reload.

**Comment by gmarziou** [comment]
if we had this working for grunt and gulp, we could simplify the sub generators as they won't have to insert the generated scripts into index.html

**Comment by andidev** [comment]
@gmarziou have you checked that it wont break the angular generator compability?
E.g. `yo angular:decorator mydecorator` adds `app/scripts/decorators/mydecoratordecorator.js` inside index.html's ` <!-- build:js({.tmp,src/main/webapp}) scripts/app.js -->` comment. Will the grunt-include-source task overrwrite this include? I think it should be okey but it should be tested.

**Comment by gmarziou** [comment]
@andidev Good point, yes it works but it's purely accidental ;) because it inserts new script as this:

        <script src="scripts/app/main/main.js"></script>
        
        <script src="scripts/decorators/authdecorator.js"></script>
        

Even if it did not work, it would have been easy to manage by excluding `decorators` directory.

But let me say that JHipster project structure is not fully compatible with angular generator because they are organized by type (service, decorator, ...) while JHipster 2.x is organized by feature ala angular-fullstack.

JHipster sets `"appPath": "src/main/webapp"` in bower.json and angular interprets this as app.js being under `src/main/webapp/scripts` while it is under `src/main/webapp/scripts/app`. This is unfortunate because all angular sub generators that must write into app.js just fail (e.g. `yo angular:route`) so the compatibility with angular generator is partial and I think that having anounced it as a a feature of 2.x will only create frustration with some users.

Anyway, it reminded my attempt to run angular-fullstack sub generators for the client part, so I did have a look again at it and found 2 things:
- it uses their own plugin [grunt-asset-injector](https://github.com/DaftMonk/grunt-asset-injector) which has been deprecated in favor [grunt-injector](https://github.com/klei/grunt-injector) it is very similar to grunt-include-source but can be better tuned and more its author has also done a gulp plugin [gulp-inject](https://github.com/klei/gulp-inject). So I'm confident that we could have same index.html comment tags for both grunt and gulp.
- it is possible to use angular-fullstack client side generators by adding some configuration into `.yo-rc.json`, I'm wondering whether this could be officially supported by JHipster or at least documented, the alternative could be that JHipster provides its own client side generators

**Comment by andidev** [comment]
Looks like the Angular Fullstack generator is doing it the right way to me, created a new issue about css injection for further discussion over there. I dont see why not it should be added if the javascript injection is configured.

**Comment by jdubois** [comment]
OK, so this is for when you don't use the sub-generator:

if you add new files by hand, or with another generator (which is the same thing, basically, as Yeoman generators are not meant to work together), then you need to add that one line to import the CSS in your index.html

Looks like normal development to me, and we can't have any idea of what the user is doing -> maybe he doesn't want that CSS to be included at that moment, maybe he wants it in another order...

I still don't really understand the use for this feature: if it's just for saving one line of code to write, I feel it's too complex for a very simple benefit

**Comment by gmarziou** [comment]
This happens a lot of when you develop Ui that goes beyond basic CRUD views but anyway it's not such a big deal.
It could be more interesting to add client-only sub generators to JHipster.

**Comment by gmarziou** [comment]
In particular, I think that `yo jhipster:client-state` would be interesting it would basically would generate same files as  `yo jhipster:entity` on client side except for the service

**Comment by gmarziou** [comment]
Closing it due to lack of interest

**Comment by piedrahitac** [comment]
> In particular, I think that yo jhipster:client-state would be interesting it would basically would generate same files as yo jhipster:entity on client side except for the service

Don't know if it's worth re-opening this issue or creating a new one, but I think a client state sub generator would be a great idea. For example, if I create a custom REST endpoint, having a client sub-generator that scaffolds Angular and HTML could save a lot of time and, seems to me, it is a fairly common use case.
