### ISSUE TITLE
Fix openapi-client subgenerator model generation and package

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#11001]
##### **Overview of the feature request**
Because I have opened some PRs to improve the openapi-client subgenerator, and I want to open some new ones, I think it's better to centralize this work in a specific issue. There is the list below...

##### **Motivation for or Use Case**
Make the openapi-client great again !

##### **Related issues or PR**
-   [ ] When using openapi-client with date field the java.time.LocalDate is not imported https://github.com/jhipster/generator-jhipster/pull/10989
-   [ ] use lower case package instead of snake case one https://github.com/jhipster/generator-jhipster/pull/10987
- [ ] openapitools is imported but the dependance is not present
- [ ] Clean unused import in the model files

####

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
why do you open a new ticket for that ? There is an already one: https://github.com/jhipster/generator-jhipster/issues/10510

**Comment by avdev4j** [comment]
Well, titles are a little bit confusing. The @ecostanzi  one is about the way we call the openapi-generator from OpenApiTools.

Mine is about the generated result and the way we configure (or not) how JHipster call this tools.

I don't think we sould merge both but have a more explicit title. What do you think about ?

**Comment by PierreBesson** [comment]
IMO we don't need an issue to fix small bugs like this. And we have too many issues already. Please close it @avdev4j.
