### ISSUE TITLE
After logging into system redirect to registration page

### ISSUE THREAD

**Issue by svennela** [jhipster/generator-jhipster#1100]
Hi ,

It happens in 2.0 and 2.1, I am using Outh based option.
To reproduce.
1) click on registration button
2) click on authentation button from registration page
3) after successful login, it lets you login but show registration page instead of home page.

**Comment by jdubois** [comment]
You are correct.

The issue is because we redirect you to the page you tried to see before being logged in. It's a good feature, except when that page was the registration page!

**Comment by svennela** [comment]
how to ignore or add condition after successful login, take it to main page if it is registration page. it doesn't make sense if user is already logged in and showing registration page.

**Comment by gmarziou** [comment]
Have a look at login.controller.js on success it calls $rootScope.back() which is defined in app.js, I think this is where there should be a test on $rootScope.previousStateName === 'register'

**Comment by svennela** [comment]
cool thanks

**Comment by gmarziou** [comment]
If you have fixed the problem maybe you could send a PR?

**Comment by jdubois** [comment]
I'm re-opening this because we need to solve it anyway
