### ISSUE TITLE
JDL exported by export-jdl is invalid.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#11012]
##### **Overview of the issue**

JDL exported from a new generated all default application is invalid.
```
SyntaxError: Error: MismatchedTokenException: Expecting --> '}' <-- but found --> 'packageFolder' <--
	at line: 13, column: 5
    at callApiMethod (.../generator-jhipster/node_modules/jhipster-core/lib/readers/jdl_reader.js:99:11)
```

##### **Reproduce the error**

`jhipster` with all default.
`jhipster export-jdl`
`jhipster import-jdl folderName.jdl`

##### **Suggest a Fix**

JDL is been exported with invalid fields and values.
`packageFolder` field seems invalid.
`jhipsterVersion 6.5.1` 6.5.1 value seems invalid.

##### **JHipster Version(s)**

master

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
     application {
  config {
    databaseType sql
    devDatabaseType h2Disk
    enableHibernateCache true
    enableSwaggerCodegen false
    enableTranslation true
    jhiPrefix jhi
    languages [en]
    messageBroker false
    nativeLanguage en
    packageName com.mycompany.myapp
    packageFolder com/mycompany/myapp
    prodDatabaseType mysql
    searchEngine false
    serviceDiscoveryType false
    skipClient false
    skipServer false
    testFrameworks []
    websocket false
    jhipsterVersion 6.5.1
    applicationType monolith
    baseName jdl
    serverPort 8080
    authenticationType jwt
    cacheProvider ehcache
    buildTool maven
    jwtSecretKey ODE3ZjQ2MDZhYmVkYmU5MjA2MTUxY2M0OGIzZjk0YWI0YmViNmI4YWVhODk0MmQxNWY1Zjg2MTU3ZDcwZjQ0YjY1YmYyMjY2YTY2Yjk1YzQ4M2JkMmU2YzQwMGI0M2Y2NzczYmM0NDYwYmQ2N2QwYmFkNjg2NmEyZjViOTE5NTE=
    embeddableLaunchScript false
    useSass true
    clientPackageManager npm
    clientFramework angularX
    clientTheme none
    clientThemeVariant
    creationTimestamp 1576855458053
    entitySuffix
    dtoSuffix DTO
    otherModules []
    blueprints
    skipUserManagement false
  }
}
  </pre>
  </details>

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "jdl",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1576855458053,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.21.0 (Apple Git-122.2)

node: v10.16.2

npm: 6.9.0

yeoman: 3.1.0

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Seems this is been fixed at https://github.com/jhipster/jhipster-core/issues/411.
This should be fixed at a new jhipster-core release.

I will keep this open until then.

**Comment by pascalgrimaud** [comment]
Does it mean we need a new release of jhipster-core ?

**Comment by mshima** [comment]
> Does it mean we need a new release of jhipster-core ?

I think so.
@MathieuAA is that right?

**Comment by MathieuAA** [comment]
Yes, sorry I was unavailable for a few days. I'm doing one today.
