### ISSUE TITLE
PersistenceAuditEvent ID type error 

### ISSUE THREAD

**Issue by danielshiplett** [jhipster/generator-jhipster#1101]
It appears that when a project is generated with MongoDB as the database, the document @Id type is wrong.  The repository has the @Id field set to String but the type has a long.  This causes problems when inserting new audit events.  No errors or exceptions are thrown.  All new audit events end up as id == 0.  Therefore only a single event will be stored.  This was observed with JHipster 2.1.1.

**Comment by jdubois** [comment]
I've tested it and you are correct.
If we use a long as document Id, how do you generate your Id? Is there some kind of "auto increment" option on MongoDB?
Otherwise, I'm quite happy with having a String as Id -> in that case, it looks more like an issue in the EnableMongoAuditing annotation, that does not understand Strings.

**Comment by danielshiplett** [comment]
I just changed the @Id type to String and modified the repository type to match.  It seemed to work.  I didn't notice any issues with EnableMongoAuditing.

**Comment by jdubois** [comment]
then I don't understand your issue @danielshiplett - is it resolved for you?

**Comment by danielshiplett** [comment]
Yes.  Just changing the @ID to String was enough.  It just needs an update to the generator so that when MongoDB is selected the domain object and repository get set to String rather than long in the future.

**Comment by jdubois** [comment]
The ID is already a String... So I still don't understand your issue

**Comment by danielshiplett** [comment]
I just pulled the latest generator and generated a new default MongoDB
backed application.  The PersistentAuditEvent id field is a long.
The PersistenceAuditEventRepository is:

public interface PersistenceAuditEventRepository extends
MongoRepository<PersistentAuditEvent, String>

That is a type mismatch for Spring Data MongoDB repositories.  It fails
silently.  Only one entry will ever be stored in that collection.

To prove this, log into the new app and out multiple times.  Then log in as
'admin' and go to the Audit Events page.  It will show only one event.  The
latest.

A log entry placed in CustomAuditEventRepository just after:

persistenceAuditEventRepository.save(persistentAuditEvent);

Will show that the persistentAuditEvent id field is always a zero value.

**Comment by jdubois** [comment]
Oh, you talked about the PersistentAuditEvent ! Understood!

That's corrected -> commit is under way!
