### ISSUE TITLE
Can jit-grunt speed up grunt build?

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1102]
I tested [jit-grunt](https://github.com/shootaroo/jit-grunt) to speed up grunt build and it does not seem to make a drastic difference at least for a small app freshly generated.

Task                       | load-grunt-tasks | jit-grunt |
---------------------------|------------------|-----------|
grunt clean build          | 11.4             | 9.7       |
grunt clean test           |  1.9             | 2.5       |
grunt clean buildHeroku    | 14.4             | 13.7      |
grunt clean buildOpenshift | 14.4             | 13.3      |
grunt clean default        | 12.9             | 12.1      |

I may test on a real app next week.

In case someone wants to try:

    npm install jit-grunt --save-dev

Then edit Gruntfile.js and replace 

    require('load-grunt-tasks')(grunt);
    require('time-grunt')(grunt);

by

    require('time-grunt')(grunt);
    require('jit-grunt')(grunt, {
        ngconstant: 'grunt-ng-constant',
        useminPrepare: 'grunt-usemin',
        ngtemplates: 'grunt-angular-templates',
        configureProxies: 'grunt-connect-proxy'
    });

**Comment by jdubois** [comment]
Doesn't seem to help a lot... and I'm afraid to do such a heavy change on the build system

**Comment by gmarziou** [comment]
Yes consider it as an experience that can be found by users by seraching the issues.
For now, I'm closing it, I may add some results on larger app if I have time.
