### ISSUE TITLE
Feature request: start script to start all docker-compose units contained in src/main/docker

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#11044]
##### **Overview of the feature request**

I really like that elasticsearch, jhipster-registry, postgresql etc. get some docker-compose unit files auto-generated.
To save time, I want a bash scripts to be auto-generated which contains some likes like
```
docker-compose -f elasticsearch.yml up -d
docker-compose -f jhipster-registry.yml up -d
```
For all services which have a docker-compose unit file

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Could you clarify whether you want a bash script per component or a bash to start all components at once? If it's the 2nd option, docker-compose would be a better option than bash.

**Comment by CodingSpiderFox** [comment]
I would like the second option but I'm not sure how docker-compose could
help with that. Putting all contents of all the existing docker-compose
files into a single docker-compose file would not be my preferred option.
I'd rather have something that I can execute directly without having to
pass additional command line options like -f or -d

**Comment by gmarziou** [comment]
Then it's just like what we already in app.yml to start both the app and the database. Once you have only one command to type, your shell completion could be enough.

**Comment by pascalgrimaud** [comment]
@CodingSpiderFox : thanks for your proposal, but we won't implement this for different reasons:
- there is already the generated `app.yml` which is similar to what you want but you need to edit and remove the application part and you need to use `docker-compose`
- we won't implement a bash script as it will only contain a `docker-compose` command, so there is no real value here

If you really want to do this, you can implement and maintain your own module (see https://www.jhipster.tech/modules/creating-a-module/#-creating-a-module).
If it becomes really popular, we can think about integrating this feature in the main generator-jhipster.

Don't hesitate to comment this ticket as soon as you start to code your module.
Hope to see your code on GitHub soon
