### ISSUE TITLE
Multi tenancy

### ISSUE THREAD

**Issue by Fazerty** [jhipster/generator-jhipster#1105]
I would like to convert my app (created with jhipster) to a saas app. I would like to have one database per tenant without having multiple instances of the application and with the possibility to create databases on the fly.
Do you have any plan to add a multi tenancy architechture to the jhipster generator (http://docs.jboss.org/hibernate/orm/4.2/devguide/en-US/html/ch16.html#d5e4780
https://github.com/vtajzich/spring-hibernate4-multitenant)?
Do you have any advice to do it?

Many Thanks

**Comment by jdubois** [comment]
Not a lot of advice from me at least...
I'm afraid that having one database per client is going to cost you a lot of money, and that your connection pool will probably be an issue. In fact, I mostly see issues in this pattern, and not a lot of benefits.
I'd rather put all clients in one database (with a FK to determine each client), that looks a more classical approach to multi tenancy with a database

**Comment by rasheedamir** [comment]
I agree with @jdubois that initially the best approach will be to have "single database" that is have "all tenants in one database". This approach is also much easy to implement and deploy.

If down the road your app grow's a lot with large number of tenants and user's then can move to other approach.

**Comment by etteru** [comment]
From my point of view, multi tenancy would be indeed a very useful feature in jhipster. At the moment, jhipster only supports function roles, but no data roles. I.e., you can restrict access to certain functionalities, but not to certain data. What about if my books/authors should only be visible by me?

Bottom line: An example of how to implement data roles would be great as it is such a common use case to have user private data!
