### ISSUE TITLE
Feature: automatically add new css to index.html

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1106]
[Angular Fullstack Generator](https://github.com/DaftMonk/generator-angular-fullstack/) uses [grunt-injector](https://github.com/klei/grunt-injector) to inject app css files into `<link>` tags in index.html.
Should JHipster do this as well?

This would be useful for example 
 - if the developer wants to separate page sepcific css styles into separate files ...
 - if the developer wants to separate component (dirvective) specific css styles into separate files ...

... instead of keeping all css classes in one gig main.css file.

Since this structure is not enforced the current way of working with one big main.css files is still supported.

This should also be configured for .scss files if sass/compass is configured.

This issue is associated with #1098

**Comment by dancancro** [comment]
Alternatively, how about modularizing css in such a way that it can be lazy-loaded or somehow name-spaced if such a thing exists?

[AngularCSS](http://door3.com/insights/introducing-angularcss-css-demand-angularjs#.VNddTFPF-RY) is one project that appears to do that.

**Comment by jdubois** [comment]
This could be an interesting option, but let me first say the things I have against it:

- It's a small project (37 stars), and we've already had too many issues with small projects: they don't have enough users, so  they are not as well tested as we need
- *In general*, it's much better to have 1 big gigantic CSS file: it's gzipped and then cached on the client side, so it's more performant to get it once and for all, than do several http requests, each time you show up a new view. That was my original idea with JHipster, in fact.

But I agree this could be a good option -> maybe if we do a specific directory, we could have "extra" CSS files that are lazy-loaded.

This should all change with HTTP 2, so this is something we will need to re-think completely.

**Comment by gmarziou** [comment]
I like the proposed feature to enable the developper splitting up stylesheets if he wants to, as long as it is optional.

I'm not a big fan of angular-fullstack's way of putting the css in same directory as code and view, I prefer to have them in assets so that I can deploy several instances of same application using different "skins".

I don't like AngularCSS because loading a CSS when you change state there can be a visual issue as the CSS is loaded asynchroneously, I would hate to see my view badly rendered while waiting for the CSS to be loaded. This is the reason why stylesheets are inserted first in the head part. SPA are made to provide seamless UI, this goes against it I think.

Also, I think it would be difficult to make it work with CSS pre-processors.

**Comment by gmarziou** [comment]
Also this may all change with web components.

**Comment by andidev** [comment]
@jdubois 
please note that grunt-injector plugin does include all the css styles in the main.css file. It works in the same way as wiredep works but for app resources instead of vendor. So they are not lazy loaded. The only benifit is that you don't have to add new js, css files to indext.html in `<link>` and `<script>` tags.

Also note that the lazy loading solution [AngularCSS](https://github.com/door3/angular-css) mentioned by @dancancro has 92 stars if that makes a differense.

Not sure which one you where refering to in your comment.

@gmarziou
The splitting up would be optional as long as we dont refactor the current main.css files I guess.
I agree thats it is a bit strange to find css files in the script folder but still as it is today the html files are placed there as well so it would be more logical to also place the css in the same folder as the js and html. The benefits are that it's easier to releize that it is an isolated component and once you get used to it will be an convienent habbit to have them close to each other.

**Comment by jdubois** [comment]
Once again, I don't see the added value here, compared to the complexity and risk

**Comment by jdubois** [comment]
I'm closing this because I'm not convinced, and this hasn't been updated for 3 weeks.
