### ISSUE TITLE
Health check page not working in Spring Boot 2.2

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#11060]
##### **Overview of the issue**

As explained in #10909, Actuator health endpoint API has breaking changes in Spring Boot 2.2

So at least in Angular health page is empty with current master.

##### **Motivation for or Use Case**

Health page should work.

##### **Reproduce the error**

Generate app with current master, run it, and navigate to Administration --> Health

Error in browser console and page is empty.

##### **Suggest a Fix**

Switching to Actuator API v2 as described in #10909 fixes this problem.

But there is also a new health indicator `ping` which has no translation ATM. This translation must be added.

But better fix is to migrate health page to Actuator API v3.

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT C:\projects\teest\jhipster-spring-boot-2-2
`-- generator-jhipster@6.6.0  -> C:\projects\kaido-github\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1577774332310,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": ["et", "en", "ru"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

git version 2.24.0.windows.2

node: v12.14.0

npm: 6.11.3

yeoman: 2.0.6

yarn: 1.17.3

Docker version 19.03.5, build 633a0ea

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

Windows 10, Chrome

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
About ping health indicator: https://github.com/spring-projects/spring-boot/issues/17926

**Comment by pascalgrimaud** [comment]
@kaidohallik : if I understand well, there are som impact on our JHipster Registry right ?
- JHipster Registry uses SB2.1
- our applications will use SB2.2
- will our Registry be compatible with old and new applications ? I'm not sure, so it could be a breaking change here

**Comment by kaidohallik** [comment]
Actuator in SB2.2 supports both API v2 and v3. So it's client choice which API version to use. Changing client code in generated app doesn't affect JHipster Registry in any way.
