### ISSUE TITLE
Create page in documentation that explains how to deploy frontend & backend separately

### ISSUE THREAD

**Issue by rasheedamir** [jhipster/generator-jhipster#1107]
I was thinking it will be very helpful to have a page in documentation which explains how someone can deploy frontend & backend (REST API) separately as two apps instead of just one app.

Any thoughts or suggestions?

**Comment by gmarziou** [comment]
Yes it'd be very useful as it has a lot of implications:
- how to build
- how to switch from relative to absolute in client
- how to overcome same origin policy

**Comment by sdoxsee** [comment]
+1 This would be useful for me at the moment...although there could be quite a number of variations that would could make it difficult to document.

**Comment by rasheedamir** [comment]
@sdoxsee can you please list down the variations that you can think off? at this moment we need to gather all thoughts and then decide and finalize how to do it.

**Comment by gmarziou** [comment]
I think one variation would be whether you want to have different (sub)domains for both client and server (i.e client.example.com and server.example.com), this is the most complex case because it has impact on cookie domain, same origin policy.

If you want to serve both client and server from same domain but running on different servers then it would be easy to do most work in the reverse proxy.

**Comment by sdoxsee** [comment]
My particular case involves having the OAuth2 Authentication Server along
on the same domain as the AngularJS client but using a different domain for
the part of jhipster that acts as a Resource Server for validating JWT
tokens and handling RESTful APIs. In fact, eventually I'd be replacing the
entire OAuth2 Authentication Server part with a C# (
https://github.com/IdentityServer/Thinktecture.IdentityServer3) one do all
my authenticating against it while keeping the AngularJS client (though
served on the C# server) and Resource Server from jhipster. I can imagine
many permutations of this.

**Comment by rasheedamir** [comment]
regarding:

* "how to overcome same origin policy" 

we can add "CORS filter" [Sample](https://spring.io/guides/gs/rest-service-cors/); It will allow the clients to communicate servers from different origin. For example, when xyz.com requests some resources from abc.com, same-origin policy usually block the request. But by supporting CORS, the server can include a special header in the response to allows clients to access data.

**Comment by jimbobwyatt** [comment]
Is this within project scope? Getting host headers to match between the front-end and back-end or using CORS headers seems outside to me...sdoxsee, don't do that, you will never see the end to the pain. I am speaking from experience. Very difficult to recover from a setup like that.

**Comment by jdubois** [comment]
Yes, it's interesting but I agree with @jimbobwyatt it's outside project scope, as you break up our "normal" build. And personally I don't understand why anybody would do that -> it can only lead to security issues (CORS) or performance issues (remember we set the headers, etc, so you will need to do that again)

Anyway, it should work out of the box, excepted the  CORS filter, of course, but that's normal if you separate the front and back, so I don't think that's really interesting to document, at least not in our official documentation

**Comment by sdoxsee** [comment]
@jimbobwyatt agreed. Out of scope. @jdubois good work at staying focused on the main things for jhipster. Thanks

**Comment by rasheedamir** [comment]
agreed guys!
