### ISSUE TITLE
--target-version option for blueprint in upgrade sub-generator

### ISSUE THREAD

**Issue by ersinciftci** [jhipster/generator-jhipster#11078]
##### **Overview of the feature request**

There is a way to specify a target version for the JHipster itself in the upgrade sub-generator using `--target-version`, but there is no way to specify a target version for the blueprint, it always gets the latest version from the npm registry. So I propose a `--target-blueprint-version` option.

##### **Motivation for or Use Case**

We want to publish a new version of our blueprint as a beta version, and we want that version to be optional when people upgrade their microservice. Currently JHipster gets the latest version of the blueprint so it's not optional.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by murdos** [comment]
This feature is already available with `--target-blueprint-versions foo@0.0.1,bar@1.0.2`. 
`--target-blueprint-version` was previously available, but has been removed when we added support for using multiple blueprints.

**Comment by murdos** [comment]
Reopening because documentation needs to be updated
