### ISSUE TITLE
Error when upgrading jhipster 6.4 to Latest

### ISSUE THREAD

**Issue by obxjames** [jhipster/generator-jhipster#11080]
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
apollo@0.0.1-SNAPSHOT /root/apollo/apollo/gateway
└── generator-jhipster@6.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr", "pl", "ro", "tr", "de", "es"],
    "blueprints": [],
    "appsFolders": ["gateway", "mercury", "moon"],
    "directoryPath": "../",
    "gatewayType": "zuul",
    "monitoring": "elk",
    "consoleOptions": [],
    "creationTimestamp": 1578173467058
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>

##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.1)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.1, mixed mode, sharing)

git version 2.20.1

node: v10.18.0

npm: 6.13.4

yeoman: 3.1.1

Docker version 19.03.2, build 6a30dfca03

docker-compose version 1.25.0, build 0a186604
</details>

##### **Overview of the issue**

When running the jhipster upgrade command I have found it adds 
```
<<<<<<< HEAD
========
>>>>>>> jhipster_upgrade
```

To most if not all the files causing a major issue with the application.

##### **Motivation for or Use Case**

Breaks everything when keeping up to date currently within the current enviroment

##### **Reproduce the error**

1. Have a version of JHipster not latest (6.4.0 works just fine)
2. Run npm install -g generator-jhipster in root folder
3. Run jhipster upgrade

Find error when running maven or gradle with npm

##### **Related issues**

None

##### **Suggest a Fix**

Unknown at this stage

##### **JHipster Version(s)**

 
6.4.0

-   [x] Checking this box is mandatory (this is just to show you read everything). But acknowledging that I have removed information irreverent to issue

**Comment by mshima** [comment]
Don’t seems a bug to me. Upgrade does the following:
- creates a jhipster_upgrade branch:
- do a clean generation with the old version
- regenerate with the new version.
- then tries to merge the upgrade commit into the main branch.

If the original file has been changed, then it will conflict.
Conflicts must be resolved manually.
