### ISSUE TITLE
ConstraintViolation on valid e-mail addresses

### ISSUE THREAD

**Issue by jepp-igus** [jhipster/generator-jhipster#11088]
##### **Overview of the issue**
A ConstraintViolation can be thrown if a given email address like example+alias@gmail.com get validated with the given validation regex pattern.

But keycloak doesn't have a problem with the given e-mail addresses. 
Because the plus char doesn't make the mail invalid.
So it might be the best solution to use the same regex pattern like keycloak does.

See: https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/services/validation/Validation.java#L45

https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/Constants.java.ejs#L28

INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
generator-jhipster@6.6.0 /home/xxx/generator-jhipster
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

git version 2.17.1

node: v12.13.1

npm: 6.12.1

Docker version 19.03.5, build 633a0ea838

docker-compose version 1.17.1, build unknown

**Comment by PierreBesson** [comment]
+1 It's no good not to support email addresses containing a "+".

**Comment by qmonmert** [comment]
@pascalgrimaud I'm working on it

**Comment by pascalgrimaud** [comment]
@qmonmert : have a look at https://github.com/jhipster/generator-jhipster/pull/11089 too as there are some interesting comment. Then, maybe this PR is out of date and we need to think more to solve this

**Comment by qmonmert** [comment]
@pascalgrimaud ok

**Comment by qmonmert** [comment]
@jepp-igus & @pascalgrimaud my PR is done #11450 ✅
I use the same regex that Keycloak except that I remove two characters % and /
because it's not possible with the code : 
`@GetMapping("/users/{login:" + Constants.LOGIN_REGEX + "}")`

@pascalgrimaud I updated a translation key but only in french and english because I don't know the translations for the others languages ...

**Comment by pascalgrimaud** [comment]
@qmonmert : in this case, you can use english by default when you don't know the translation

**Comment by qmonmert** [comment]
@pascalgrimaud ok :)

**Comment by qmonmert** [comment]
@jepp-igus & @pascalgrimaud my PR is finished

**Comment by qmonmert** [comment]
@pascalgrimaud & @jdubois I claim my money 😄https://opencollective.com/generator-jhipster/expenses/14828
