### ISSUE TITLE
Usign Materia bootswatch theme, the navbar links are not visible

### ISSUE THREAD

**Issue by hfsoares** [jhipster/generator-jhipster#11083]
##### **Overview of the issue**
After creating the application, using angular and  Materia bootswatch theme, the navbar links are not visible

##### **Motivation for or Use Case**
The navbar links should be visible

##### **Reproduce the error**
Just create the application, using Angular and Materia bootswatch theme

##### **Related issues**
I have not founded a Issue, but there is a stackoverflow question:
https://stackoverflow.com/questions/58733508/the-angular-navbar-generated-with-jhipster-is-not-working-properly

##### **Suggest a Fix**
this was the first line from _app/layouts/navbar/navbar.component.html:_
`<nav class="navbar navbar-primary navbar-expand-md bg-primary">`

Comparing with the code in bootswatch website, i added navbar-dark class, and this is how I fixed in my project
`<nav class="navbar navbar-primary navbar-expand-md navbar-dark bg-primary">`

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
informa@0.0.1-SNAPSHOT /Users/humberto/Desenvolvimento/objective-informa
└── generator-jhipster@6.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.objective.informa",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "monolith",
    "baseName": "informa",
    "packageName": "com.objective.informa",
    "packageFolder": "com/objective/informa",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "materia",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1578073309908,
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": ["pt-br"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

git version 2.21.0 (Apple Git-122.2)

node: v12.14.0

npm: 6.13.4

yeoman: 3.1.1

Docker version 19.03.1, build 74b1e89

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!
##### **Browsers and Operating System**
MAC OSX Catalina
Chrome

**Comment by atomfrede** [comment]
I think we only can document that somehow. I guess using `navbar-dark` for other themes may break them.

**Comment by kaidohallik** [comment]
@hfsoares thanks for opening this issue and pointing out the solution.

In Bootswatch:
* primary and dark variants are using `navbar-dark`
* light is using `navbar-light`

But JHipster generates for primary variant `navbar-primary` which is incorrect.

PR for fix coming shortly.

**Comment by kaidohallik** [comment]
I opened PR #11102 to fix this.
