### ISSUE TITLE
Too many fake Liquibase data for entity linked to User (MapsId + Oauth2)

### ISSUE THREAD

**Issue by hdurix** [jhipster/generator-jhipster#11099]
##### **Overview of the issue**

When choosing Oauth2 with a SQL database (so Liquibase) then generating an entity with a relation with User and MapIds option (JPA derived identifier), too many records are generated for the given entity: 4 but only 2 users are created.

##### **Motivation for or Use Case**

The application is starting but Liquibase is failing. Then it's not possible to use this entity...

##### **Reproduce the error**

* Generate an app with Oauth2 + a SQL database
* Create an entity and a relation to User with MapsId

##### **Related issues**

https://github.com/jhipster/jhipster-vuejs/issues/532

In Vue.js blueprint, e2e tests are [failing](https://dev.azure.com/jhipster/jhipster-vuejs/_build/results?buildId=8488) in this configuration, this should also be the case in Angular because the list of entities can not be retrieved (so there might be a fix to do here as well).

##### **Suggest a Fix**

This [line](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs#L51) has to check if oauth2 is used.

And possibly fix the e2e tests as they should be failing in this case.

##### **JHipster Version(s)**

```
sample-oauth-2-infinispan@0.0.1-SNAPSHOT /home/hippolyte/workspace/jhipster/tmps/tmp5
└── generator-jhipster@6.6.0  -> /home/hippolyte/workspace/jhipster/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "baseName": "sampleOauth2Infinispan",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "infinispan",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "applicationType": "monolith",
    "testFrameworks": ["gatling", "protractor"],
    "jhiPrefix": "myPrefix",
    "serviceDiscoveryType": false,
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": [],
    "jhipsterVersion": "6.6.0",
    "creationTimestamp": 1578405178289
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity MapsIdUserProfileWithDTO (maps_id_user_profile_withdto) {
  dateOfBirth Instant
}
relationship OneToOne {
  MapsIdUserProfileWithDTO{user(login)} to User with jpaDerivedIdentifier
}

dto MapsIdUserProfileWithDTO with mapstruct
service MapsIdUserProfileWithDTO with serviceImpl

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment 18.9 (build 11.0.5+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.5+10, mixed mode)

git version 2.20.1

node: v12.13.1

npm: 6.12.1

yeoman: 3.1.1

Docker version 19.03.2, build 6a30dfca03

docker-compose version 1.25.0, build 0a186604

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Hi @hdurix , this issue is mentioned in https://github.com/jhipster/generator-jhipster/issues/9579 , as problem 3.
Glad you are doing a PR.

**Comment by hdurix** [comment]
Great, thanks @pmverma, I didn't know that this issue was known.

I have got the fix ready but I want to be sure that e2e tests are failing when liquibase does not run successfully, because in this case, the app is not totally usable. That's my goal for today :)

**Comment by hdurix** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/13215
