### ISSUE TITLE
JHipster registry and cloud foundry (Pivotal)

### ISSUE THREAD

**Issue by rmt21** [jhipster/generator-jhipster#11113]
##### **Overview of the issue**

I;m trying to deploy jhipster registry to cloud foundry, however its profiles are being overridden by spring cloud configs 'cloud' profile. I'm unable to get the service running on its normal port of 8761, its constantly defaulting to port 8080. Do you know how to override these properties and get it set up successfully?

##### **Motivation for or Use Case**

Unable to use jhipster registry on cloud foundry.

##### **Reproduce the error**

Deploy jhipster registry to cloud foundry.

##### **Suggest a Fix**

Override of cloud porfiles values?

##### **JHipster Version(s)**

6.5.1

##### **JHipster Version(s)**

```
jhipster-registry@6.0.2 /home/vitalinstinct/Development/apollo/jhipster-registry
└── generator-jhipster@6.5.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "jhipsterVersion": "6.5.1",
    "baseName": "JHipsterRegistry",
    "packageName": "io.github.jhipster.registry",
    "packageFolder": "io/github/jhipster/registry",
    "serverPort": "8761",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "enableTranslation": false,
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": false,
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "embeddableLaunchScript": false,
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": [],
    "creationTimestamp": 1576848019661
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.1)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.1, mixed mode, sharing)

git version 2.20.1

node: v12.13.1

npm: 6.12.1

yeoman: 3.1.0

yarn: 1.19.2

Docker version 19.03.3, build a872fc2f86

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

Ubuntu

-   [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Can't you fix the port using the "server.port" property? Otherwise, you could reconfigure your services to point to port 8080, that would also work.

This isn't really bug, could you open a ticket on StackOverflow instead? I'm closing this because of this.

And please link your Stackoverflow question here, so people can find it.

**Comment by rmt21** [comment]
Thanks.

https://stackoverflow.com/questions/59718806/jhipster-registry-and-cloud-foundry-pivotal
