### ISSUE TITLE
Mobile responsive menu-bar not working in jhipster 6.0.1

### ISSUE THREAD

**Issue by kalumet** [jhipster/generator-jhipster#11114]
##### **Overview of the issue**

The dropdown menu is not triggering the router event when watched on a mobile device.

##### **Motivation for or Use Case**

Mobile users are not able to navigate as intendet.

##### **Reproduce the error**

jhipster generator 6.0.1
generate a vanilla monolith application

##### **Related issues**

I haven't found anything so far that would explain the issue. I tried to open a console on the mobile chrome (Iphone), but do not get any information or error-message.

##### **Suggest a Fix**

sorry ... I'm not experienced enough to understand how to identify the issue.

##### **JHipster Version(s)**

6.0.1

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhtest@0.0.0 D:\dev\jhtest
`-- generator-jhipster@6.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "monolith",
    "baseName": "jhtest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": ["de", "en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

git version 1.8.4.msysgit.0

node: v8.11.3

npm: 5.6.0

yarn: 1.10.1

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Win 10 (Google Chrome is up to date
Version 79.0.3945.117 (Official Build) (64-bit))

Iphone 7s with latest IOS and APP Versions of Safari and Chrome.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I've seen this issue and was going to report it, but it seems to be fixed in master.  I couldn't find the change that fixed it though.

Fixed in master: https://pagination-master.herokuapp.com/
Broken with last release: https://pagination-issue-v-6-5-1.herokuapp.com/

Here is one [possible workaround](https://github.com/ruddell/jhipster-examples/commit/b8393c957b033c960187b8bfc3d7bda74d1cb42d) (you would have to apply it to all dropdown elements)

**Comment by qmonmert** [comment]
@kalumet indeed it works with the latest version of JHipster 6.6.0 (I just checked) cc @ruddell

**Comment by kalumet** [comment]
Thanks for the verification and the workaround.

**Comment by ruddell** [comment]
As it's fixed in the latest release v6.6.0 and a workaround is provided for those who can't upgrade yet, I'm closing the issue.

If someone wants to find the exact fix, it's somewhere between [v6.5.1 and v6.6.0](https://github.com/jhipster/generator-jhipster/issues?q=milestone%3A6.6.0+is%3Aclosed) but there are 150+ PRs from that period so it's hard to tell from a quick look.

**Comment by kaidohallik** [comment]
FYI: I tried https://pagination-issue-v-6-5-1.herokuapp.com/ with Chrome and Opera in Android and working fine, so it can be iOS specific.

**Comment by kaidohallik** [comment]
When looking at Git history then some candidates for fixer are:

1. removing bold from navbar hover in Angular default theme (bold caused dropdown width changes on hover on menu items with longest texts which caused e2e failures in some configs): #10820

2. updating dependencies: #10942
