### ISSUE TITLE
Implement Asyncapi for Event-driven architecture

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#11112]
##### **Overview of the feature request**
We already use OpenApi for Rest implementation, would be awesome to implement AsyncApi for event-driven architecture (Kafka,...).

https://www.asyncapi.com
https://github.com/asyncapi/asyncapi

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@cbornet Do you know this project?

**Comment by cbornet** [comment]
I know it by name and it looks like a nice initiative. But afaik the tooling is very limited right now, especially for Java. That's why I've never used it on a project and I don't see what we could provide in JHipster.

**Comment by DanielFran** [comment]
I was thinking about a sub-generator like the one for OpenApi... but yes, it seems we do not have more than documentation html/md available for java.

**Comment by DanielFran** [comment]
@cbornet Looking at https://www.asyncapi.com/docs/tooling/ it seems the generator create already java-spring implementation (https://github.com/asyncapi/generator/tree/master/templates/java-spring)

**Comment by cbornet** [comment]
That's code for spring-integration so you'd have to choose to use spring-integration first. If you're interested, maybe you could do it as a module ?

**Comment by pascalgrimaud** [comment]
I think it should go to module first, instead of main generator

**Comment by pascalgrimaud** [comment]
Closing this as we have too much opened tickets and I think it should go to module first
