### ISSUE TITLE
Dependency Status link is dead

### ISSUE THREAD

**Issue by fdelbrayelle** [jhipster/generator-jhipster#11118]
"Dependency Status" link in home README.md is a dead link leading here : https://david-dm.org/jhipster/generator-jhipster-module

**Comment by pascalgrimaud** [comment]
Then, let's wait a little bit so

**Comment by SudharakaP** [comment]
@pascalgrimaud : Okay david-dm is back up again. So I am closing this one; we will probably see this from time to time for sure, but from what I've seen its not too often. Feel free to reopen if you guys decide to remove david-dm completely. 😄

**Comment by pascalgrimaud** [comment]
I'm reopening this as it's down again.
Time to remove it... not very usefull to have it as badge
