### ISSUE TITLE
Add 'yo jhipster:doctor'

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1112]
In order to help beginners, I think that the app generator should test presence of required tools according to user's answers. Kind of `yo doctor`

- Do you want to use Java 8? `javac -version`
- Which *development* database would you like to use? Too many possibilities between local, Remote, VM...
- Would you like to use Maven or Gradle?  `mvn -v` or `gradle -v`
- Would you like to use Grunt or Gulp.js for building the frontend?  `grunt --version` or `gulp -v`
- Would you like to use the Compass CSS Authoring Framework? `compass -v`

**Comment by jdubois** [comment]
We could have a "yo jhipster:doctor" task...
For database you can't really test this, as we are in JavaScript. Maybe something with Maven?

**Comment by atomfrede** [comment]
Great idea. But at least for gradle this is not required, as we are using the gradle wrapper, so gradle must not be in the path.

**Comment by jdubois** [comment]
Oops you are correct, and our new installation page is wrong!!!!

**Comment by atomfrede** [comment]
:) You're right! I can provide a PR during the day if you like.

**Comment by jdubois** [comment]
Of course I'd like it!

**Comment by alexandrustefan** [comment]
@gmarziou : That would be a great idea. +1 this !

**Comment by gmarziou** [comment]
+1 for a "yo jhipster:doctor" task, thsi way we could launch it any time and ask users who report an issue to do it. As the configuration is in .yo-rc.json file, it should not be too difficult.

**Comment by rasheedamir** [comment]
+1  for a "yo jhipster:doctor" task!

**Comment by gmarziou** [comment]
Looking at [rff-doctor](https://github.com/rakuten-frontend/rff-doctor), it could be a good base to start with

**Comment by jdubois** [comment]
We already use shelljs to test files and directories, it could be a good fit for testing if stuff is already installed: https://github.com/arturadib/shelljs

**Comment by gmarziou** [comment]
Looks cool,  I mentioned rff-doctor mainly for its check list not really for its implementation.
In particular it tests git and access to github.com which is required for some npm/bower dependencies.

**Comment by gmarziou** [comment]
I investigated how these tools were built and it seems to me that this feature should not be implemented as a sub generator, it does not fit and also a generator is a rather complex environment for simple tasks that will only display a diagnostic on screen. Also we want to run this tool before jhipster or when jhipster does not work so it is better to have it as a standalone tool with simpler dependencies like yo doctor and rff-doctor.
So we would have a jhipster-doctor globally installed npm tool.

**Comment by jdubois** [comment]
You are correct @gmarziou 
So we still need this tool, but this should be a separate project.

I can add a "jhipster-doctor" project on Github, would that be OK with you?

**Comment by gmarziou** [comment]
Perfect

**Comment by gmarziou** [comment]
I have started adding new checkings on a [fork of rff-doctor](https://github.com/gmarziou/rff-doctor)

**Comment by jdubois** [comment]
@gmarziou any news on this?
I can create a project for you under the JHipster organization, if you want to

**Comment by gmarziou** [comment]
It's on my todo list but I may be unable to work on it before end of March.

**Comment by jdubois** [comment]
No news on this great idea -> I'm closing this as this is not moving forward
Sad!
