### ISSUE TITLE
Update Cucumber versionfrom 4.8.x to 6.6.x

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#11136]
##### **Overview of the feature request**

See: 
- https://cucumber.io/blog/open-source/announcing-cucumber-jvm-v5-0-0-rc1/
- https://github.com/cucumber/cucumber-jvm/blob/master/release-notes/v5.0.0.md
- https://github.com/cucumber/cucumber-jvm/blob/master/release-notes/v5.1.0-v5.7.0.md
- https://github.com/cucumber/cucumber-jvm/blob/master/release-notes/v6.0.0.md

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
any interest on this ?
should we keep this opened, as we know we have many lib to upgrade for every new Spring Boot version

**Comment by juliensadaoui** [comment]
I will do it.

**Comment by DanielFran** [comment]
@juliensadaoui Are you working on it?

**Comment by pascalgrimaud** [comment]
@juliensadaoui : do you still plan to do this ? Or should we close this ticket

**Comment by DanielFran** [comment]
@jhipster/developers Should we delete the use of cucumber?

**Comment by pascalgrimaud** [comment]
+1 from me

**Comment by avdev4j** [comment]
I'm sorry, but what's wrong with cucumber?

**Comment by pascalgrimaud** [comment]
@avdev4j : no one seems to have interest in Cucumber, as this ticket is opened since 9 months and nothing has been done... So just let's remove this option for v7

**Comment by murdos** [comment]
May I try to do the update? Cucumber option was one of nice and cool things when I discovered JHipster, and I think it would be a shame to have it removed.

**Comment by pascalgrimaud** [comment]
You're welcome @murdos ! thanks a lot
