### ISSUE TITLE
Wierd issue with grunt/mvn

### ISSUE THREAD

**Issue by nezuvian** [jhipster/generator-jhipster#1114]
I created a new jhipster application, then configured the password for the db. After this I start the application with ```grunt serve```, the browser opens, the welcome page loads. The wierd thing comes next, when I try to log in with any of the predefined users the authentication fails. I tried to take a look at /health but I got the following:
```
An error has occurred:{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect”}
```

Then I shut down grunt and run the app with ```mvn spring-boot:run``` with this I was able to log in and the /health page was working. 

About the config:
* Windows
* MySQL for dev as well as prod
* jdk8

**Comment by gmarziou** [comment]
When you use grunt serve you start a ststic web server that serves the client part of your app on port 9000 and proxies the api calls to your spring-boot application running on port 8080 but it does not start it, you have to start it by running mvn spring-boot:run.

So there's no issue.

**Comment by nezuvian** [comment]
Okay, I misinterpreted the instructions a bit. Thanks for the help!
