### ISSUE TITLE
New needle for adding new entries in log configuration

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#11146]
##### **Overview of the feature request**

Have a new needle in the server subgenerator for adding new log level configuration.

##### **Motivation for or Use Case**

https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/62 is a good example for the need.

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by seraphinandrieux** [comment]
Hello @murdos , I'm working on it :)
