### ISSUE TITLE
Document some guidelines about how to design REST api in jhipster apps

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1115]
I like Restangular principles, the way it handles relations, Angular 2 support commitment though I haven't used it yet on a real project.
I have already read interesting discussions in issues, in particular #668 so I will not ask for JHipster to support Restangular, instead I would like to ask for some guidelines in documentation about:
- how to define nested resources and related services in client part
- how are managed related objects in responses, it seems to me that the entity generator includes them rather than linking them
- how to handle pagination
- differences with "usual" RESTful implementation like $resource using POST to update rather than PUT
- ....

**Comment by MartinLichtblau** [comment]
Push

**Comment by jimbobwyatt** [comment]
Would the hipster way of doing this be including client libraries as part of project generation and entity/service creation? Could be mitigation for the coming Angularpocalypse to abstract away the UI and have RESTful client libraries to test against. It would also provide for more testability/usability for folks who are really just building microservices with this project but love what the UI stuff brings manageability wise. Love this project by the way, but my facial hair predates the hipster movement so I can't completely endorse :)

**Comment by jimbobwyatt** [comment]
Damn, that means I'm old. Sonofa...

**Comment by jdubois** [comment]
I'm closing this as some of those have been clearly improved recently: REST requests are better, more HATEOAS like, with pagination.

For other things, like relations, I haven't worked on it yet, so I don't have anything to share at the moment. This is up to the developer, at the moment!
