### ISSUE TITLE
Rewrite in Go

### ISSUE THREAD

**Issue by jimbobwyatt** [jhipster/generator-jhipster#1116]
Just being a hipster and disruptive and non-constructive, but I love this project! I'll be contributing soon!

**Comment by jdubois** [comment]
Please don't hesitate to contribute!

But I'm closing this as we won't rewrite it in go -> btw did you see last year's April's fool? http://jhipster.github.io/2014/04/01/jhipster-release-2.0.0.html

That makes me think I need to prepare another one!

**Comment by jimbobwyatt** [comment]
Late to the party, but even more encouragement for me that this team has a sense of humor! Sorry for spamming the issue list, but drives up the number. Gaming metrics is a pastime of mine.
