### ISSUE TITLE
Jhipster React Typescript project not supported by Internet Explorer 11.

### ISSUE THREAD

**Issue by prumenov97** [jhipster/generator-jhipster#11172]
##### **Overview of the issue**

I'd like to report an issue I've ran into the last couple of days. I've tried to add Internet Explorer support for my Jhipster React Typescript application using the following Jhipster guide:

https://www.jhipster.tech/tips/028_tip_ie_support.html#provide-internet-explorer-support

Unfortunately, I cannot find the following code block: 
{
                test: /manifest.webapp$/,
                loader: 'file-loader',
                options: {
                    name: 'manifest.webapp'
                }
            },
in order to complete it. Perhaps the guide is a bit outdated and needs some extra steps, in order for it to be functional. I'm using IE version 11.973 .17763.0, "react": "16.8.5", "react-jhipster": "0.9.0", and "generator-jhipster": "6.5.0". 

##### **Motivation for or Use Case**

Need to make the project compatible with IE 11.

##### **Reproduce the error**

Generate a new jhipster react project and follow the Jhipster IE support guide:

https://www.jhipster.tech/tips/028_tip_ie_support.html#provide-internet-explorer-support

Start and open the project on IE 11 and receive an error message.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/10184

##### **JHipster Version(s)**

-"react-jhipster": "0.9.0"
-"generator-jhipster": "6.5.0". 

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: from-cli: true

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.5.0
Application files will be generated in folder: C:\Portal\Bitbucket\Portal\portal
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

WARNING! Java is not found on your computer.
 ______________________________________________________________________________

  JHipster update available: 6.6.0 (current: 6.5.0)

  Run npm install -g generator-jhipster to update.

 ______________________________________________________________________________

##### **Browsers and Operating System**

-Windows 10
-Internet Explorer 11

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
The tip is assuming you use angular and not react and provided by our users, so we can't guarantee it works for every option we have. We do not officially support any internet explorer version, so I will close this issue. You can try stackoverflow to get some advice how to make that work.

**Comment by ruddell** [comment]
Another user was able to get IE working with React by adding a polyfill: https://github.com/jhipster/react-jhipster/issues/41#issuecomment-577555216
