### ISSUE TITLE
More random thoughts.

### ISSUE THREAD

**Issue by jimbobwyatt** [jhipster/generator-jhipster#1117]
Any support for contributing to an online learning course with this project as its base? I'd be looking for key contributors to submit short lessons as screencasts but would handle all course related effort.

**Comment by jdubois** [comment]
I have coworkers from Ippon USA (cc @rlheritier ) who have already done some training videos -> I still didn't watch them, I just don't have the time...

But we could have a Youtube channel with those videos. I'm currently using my own Youtube account, I will check if I can make a "JHipster" account.

**Comment by jimbobwyatt** [comment]
Let me see what you have and we can go from there. Youtube is great for contained subjects, but you have quite a bit more here. More structure is required in the content production than something like Khan's Academy. I work for a company who used to have an interest in a company that everyone knows. They did a pretty good job at instructional video series like this. I can't divulge that association without lots of red tape and I wouldn't be working on this on their behalf, but you can see where I am going.

Anybody care to see Africa?

**Comment by jdubois** [comment]
OK, I see the interest in this, of course, so I can only agree with you!!

A few questions, thus:

- Will those be free for everyone? I understand those platform require money to run, but everything in JHipster is free, and I'd like it to stay that way
- As you seem to know this very well, will you be OK to be in charge of this "officially" ? There isn't anything "official", of course, it's more that people stand up to be the leader of some part of the project, and in that case I can assign Github tickets to you when it's related to your part

**Comment by jimbobwyatt** [comment]
Yes, gratis. Do you have a preferred license? I'm thinking something out of the creative commons suite, but I'm not an expert on all of the options. And yes, I'll lead as best I can. I'll get something put together for the group to give feedback on in the next couple of weeks.

**Comment by jdubois** [comment]
I would use http://creativecommons.org/licenses/by-nc-sa/4.0/

-> it's a bit restrictive, but I don't want commercial companies to sell those videos, I would like those to be always free for everybody

**Comment by jimbobwyatt** [comment]
Perfect, my thoughts exactly.

**Comment by jdubois** [comment]
OK -> I'm closing this ticket, can you start another one when you start your project? If you look for people to help you, I can tweet this
