### ISSUE TITLE
Angular LanguageHelper service not created anymore

### ISSUE THREAD

**Issue by niklasastrom** [jhipster/generator-jhipster#11189]
##### **Overview of the issue**
In the generated Angular application, the service `webapp.app.core.language.LanguageHelper` service is not instantiated and working as intended in the application because there is no usage of it.

In earlier versions of jHipster, this service contained more logic that was used from other files (from e.g. the `main.component.ts`), but this logic is extracted. Because of this, there is no usage of this service from other files and hence the service is never created by Angular, and the subscription on languageChange that is defined in there is never registered. For a newly generated Angular application, this causes the `lang` property in the `<html>` tag in the built page to not update when the language is changed in the application.

##### **Motivation for or Use Case**

Additionally to the `<html lang="" >` problem describe above, we had more logic in this service regarding language changes that worked with the previous version of jhipster, but not after updating to version 6.6.0.

##### **Reproduce the error**

Generate a new project with Angular.
I created a monolithic application, no database and at least two languages. Start the generated application. Change language in the `language` drop down on the page, inspect the html elements and verify that the `<html lang="">` is not changed. By checking the sources of the built application, it is also possible to verify that the `language.helper.ts` file is not part of the built application.

##### **Suggest a Fix**

Possible fix: Reference the languageHelper from another class. Perhaps move the init logic currently executed in the constructor to a public method that is called to avoid "service not used error" from the class where the languageHelper is added.

Or there is a way in angular to create unused services?

##### **JHipster Version(s)**

Version 6.6.0

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "monolith",
    "baseName": "jhipster2test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "...",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1580212156955,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "de"],
    "blueprints": []
  }
}

</pre>
</details>

##### **Browsers and Operating System**

This issue is not browser related.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
I confirm this issue, this is regression from #10893. Thanks a lot for reporting this issue @niklasastrom!

Page title management was in 2 different places:
* for i18n enabled in `LanguageHelper`
* for i18n disabled in `MainComponent`

After refactor page title logic is in one single place, in `MainComponent`, for both i18n disabled and enabled.

After that `LanguageHelper` became very short and I felt that I want to transfer all remaining code also to `MainComponent` and delete `LanguageHelper`. But a little while ago was discussion that deleting a file is a breaking change and to avoid being rejected #10893 I didn't delete `LanguageHelper`.

As now this is causing problems then I'll do a PR to remove `LanguageHelper` completely and migrate those remaining couple of lines from `LanguageHelper` to `MainComponent`.

**Comment by kaidohallik** [comment]
FYI: this problem seems to be caused by tree shaking. There is an open Angular ticket for that: https://github.com/angular/angular/issues/25633

From one side this can be considered as Angular bug (tree shaking didn't detect that `LanguageHelper` contains code that is actually used), but from other side this lead us to improve our code (remove pointless `LanguageHelper` class).

**Comment by pascalgrimaud** [comment]
adding a bounty as it's a bug

**Comment by kaidohallik** [comment]
bounty claimed: https://opencollective.com/generator-jhipster/expenses/13788
