### ISSUE TITLE
Despite having last version of "yo", I receive "Your yo version is outdated"

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#11181]
##### **Overview of the issue**

I tried to create an UAA application and I receive the following error:
```
Yeoman Doctor
Running sanity checks on your system

✔ No .bowerrc file in home directory
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .yo-rc.json file in home directory
✔ Node.js version
✔ npm version
✖ yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest


Found potential issues on your machine :(
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for global-agent@2.1.7: wanted: {"node":">=10.0"} (current: {"node":"8.11.4","npm":"6.13.6"})
npm WARN notsup Not compatible with your version of node/npm: global-agent@2.1.7

added 806 packages from 482 contributors and audited 5877 packages in 174.157s

10 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

Despite have already the last `yo` version installed:
```
alex@alex-Inspiron-5559:~$ yo --version 
3.1.1
alex@alex-Inspiron-5559:~$ npm -version
6.13.6
alex@alex-Inspiron-5559:~$ node -v
v8.11.4
alex@alex-Inspiron-5559:~$ nodejs -v
v8.10.0
```

##### **Motivation for or Use Case**

I can't create a new JHipster application with `jhipster-generator` version 660.

##### **Reproduce the error**

No idea how reproduce it.
Most likely I have a wrong configuration locally, but I can't figure out how to fix it.

##### **Related issues**

I don't think so.

##### **Suggest a Fix**
No idea

##### **JHipster Version(s)**

version 6.6.0

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.test",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "uaa",
    "baseName": "TestUaa660",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "...xxx...",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1580065168671,
    "testFrameworks": ["gatling"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": ["en", "fr", "de", "it"],
    "blueprints": [],
    "skipClient": true
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities are created.

##### **Browsers and Operating System**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
```

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
What command are you executing?

**Comment by pascalgrimaud** [comment]
Strange, it is a warning, not an error.
I already saw the same on my machine, but no issue for generating a project.

So yes, waiting your command

**Comment by alexsintoni** [comment]
Hi @mshima ,

I simply run `jhipster` in an empty folder and I follow the usual questions from the generator

**Comment by pascalgrimaud** [comment]
@alexsintoni : thanks. What happened at the end of generation, after the warning message about yo ? Empty folder ? No additional logs ?

**Comment by mshima** [comment]
Yo cli is loaded internally by jhipster, yo command is never executed.
As @pascalgrimaud said, it’s a warning that’s is shown by npm install (when it installs yo) which is executed at jhipster install step.

One scenario I can think is that you installed yo locally and npm removed yo from jhipster node_modules directory.
You should try to remove yo from your local directory.

**Comment by alexsintoni** [comment]
Hi guys,

apologize for my late reply.
I just run the UAA that I have created and despite that error, it seems to work. 
I did not create any other application nor gateway. So, I can't tell you 100% that it is working. But sure it is running and it is registered in the JHipster Registry.

**Comment by mshima** [comment]
This isn’t a bug.
Closing.
Reopen it if you find any problem.
