### ISSUE TITLE
UserXAuthTokenController is generated with wrong package declaration

### ISSUE THREAD

**Issue by javajack** [jhipster/generator-jhipster#1118]
UserXAuthTokenController is generated in the com.webiyo.rikrut.web.rest package.

But the source code of UserXAuthTokenController has the package definition as package com.webiyo.rikrut.security.xauth

There seem to be a bug in yeoman generator template.

I am on windows machine.

![jhispter](https://cloud.githubusercontent.com/assets/1037726/6143519/2460abd8-b1f0-11e4-8eca-820ba401e58d.png)

**Comment by rasheedamir** [comment]
yeah you are correct this is bug.

Here is the template [UserXAuthTokenController](https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/java/package/web/rest/_UserXAuthTokenController.java)

And it's pointing to: `package <%=packageName%>.security.xauth;` whereas it should be: `package <%=packageName%>.web.rest`

I will try to generate a PR for it today.

**Comment by jdubois** [comment]
Yes, this is a bug!!

@rasheedamir I'll merge your PR when it's done, and I'll need to do a release soon, indeed
