### ISSUE TITLE
Option to generate master detail relationship in front end

### ISSUE THREAD

**Issue by mohamedzaki90** [jhipster/generator-jhipster#11183]
##### **Overview of the feature request**

It's common customization to add some related entities in the edit/view page of the main entity for example:
order and order lines
product and product options

##### **Motivation for or Use Case**
1. Define what is the best practice to do implement this pattern since nearly all examples explain the normal single entity pages.
2. Save customization time to focus on styling instead of building from scratch
3. help to minimize conflicts while upgrades
4. very useful while designing DDD aggregates

##### **Related issues or PR**
https://github.com/jhipster/generator-jhipster/issues/11173
https://github.com/jhipster/generator-jhipster/issues/11122
https://github.com/jhipster/generator-jhipster/issues/10958

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
It's interesting to have but sadly, no comment on this ticket. 

Anyway, I think it will be really complex to achieve this, as it can be done only in major version.

@mohamedzaki90 : if you think it's a must have, you need to take the lead on this.
The steps would be:
- provide an example of code in GitHub
- then, start to contribute in the 3 fronts, Angular, React, Vue.js
- don't forget the other database like MongoDB

What do you think @mohamedzaki90 ?

**Comment by mshima** [comment]
I really don't know why I set as 7.x

**Comment by pascalgrimaud** [comment]
@mshima : because it required a lot of work ? :p

**Comment by mshima** [comment]
@pascalgrimaud @mohamedzaki90

**Comment by mshima** [comment]
Didn’t mean to closed 🤦‍♂ .
@pascalgrimaud I have remembered.
@mohamedzaki90 set related to https://github.com/jhipster/generator-jhipster/issues/10958

**Comment by pascalgrimaud** [comment]
Still very few comments... and it will require a lot of work to achieve this.
So unless someone wants to take this and start the work, I'll reopen.

For now, let's close this.
