### ISSUE TITLE
Compilation errors with OAuth and ManyToMany with User on a microservice app

### ISSUE THREAD

**Issue by Falydoor** [jhipster/generator-jhipster#11191]
##### **Overview of the issue**

Compilation errors below:

```
[ERROR] /Users/theo/Documents/perso/jhipster-many/mono/src/main/java/com/mycompany/myapp/web/rest/CountryResource.java:[57,20] cannot find symbol
  symbol:   method getUser()
  location: variable country of type com.mycompany.myapp.domain.Country
[ERROR] /Users/theo/Documents/perso/jhipster-many/mono/src/main/java/com/mycompany/myapp/web/rest/CountryResource.java:[59,40] cannot find symbol
  symbol:   method getUser()
  location: variable country of type com.mycompany.myapp.domain.Country
[ERROR] /Users/theo/Documents/perso/jhipster-many/mono/src/main/java/com/mycompany/myapp/web/rest/CountryResource.java:[82,20] cannot find symbol
  symbol:   method getUser()
  location: variable country of type com.mycompany.myapp.domain.Country
[ERROR] /Users/theo/Documents/perso/jhipster-many/mono/src/main/java/com/mycompany/myapp/web/rest/CountryResource.java:[84,40] cannot find symbol
  symbol:   method getUser()
  location: variable country of type com.mycompany.myapp.domain.Country
```

##### **Motivation for or Use Case**

Project should compile.

##### **Reproduce the error**

Generate the app using the JDL below:

<details>
<summary>JDL file</summary>
<pre>
application {
  config {
    authenticationType oauth2
    applicationType microservice
  }
  entities *
}
entity Country {
  name String
}
relationship ManyToMany {
  Country{User(login)} to User{Country(name)}
}
</pre>
</details>

##### **Related issues**

#11160

##### **JHipster Version(s)**

```
jhipster@0.0.0 /Users/theo/Documents/perso/jhipster-many/mono
└── generator-jhipster@6.6.0  -> /Users/theo/Documents/perso/generator-jhipster-fork

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "authenticationType": "oauth2",
    "applicationType": "microservice",
    "jhipsterVersion": "6.6.0",
    "creationTimestamp": 1580226060770,
    "baseName": "jhipster",
    "buildTool": "maven",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "hazelcast",
    "serverPort": "8081",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["Country"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Country {
  name String
}
relationship ManyToMany {
  Country{user(login)} to User
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 12 Mac OS X amd64-64-Bit Compressed References 20190915_201 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - 9984ea0dd9 based on jdk-12.0.2+10)

git version 2.25.0

node: v10.18.1

npm: 6.13.4

yarn: 1.21.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.24.1, build 4667896b

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Isn't related to #11025?

**Comment by Falydoor** [comment]
Not really, this is because a microservice app must save the User in case of a relationship.

**Comment by MathieuAA** [comment]
Ah! true.
