### ISSUE TITLE
mvn compile liquibase:diff error

### ISSUE THREAD

**Issue by Fazerty** [jhipster/generator-jhipster#1119]
I had an error and the generated file was empty.
I changed in the pom.xml this line (added table: )
\<diffExcludeObjects\>table:oauth_access_token, table:oauth_approvals, table:oauth_client_details, table:oauth_client_token, table:oauth_code, table:oauth_refresh_token\</diffExcludeObjects\>
and it seems to work now.

**Comment by Fazerty** [comment]
It seems that column:created_date is also useful (column:t_user.created_date doesn't work)

**Comment by jdubois** [comment]
Which error did you have? I need more explanation than just "I had an error"

The diffExcludeObjects can use the table: prefix -> we don't use it as it shouldn't be needed, but if that makes a difference I could change this

I'm closing this as, for the moment, I don't have a clear bug here.
