### ISSUE TITLE
Update Mongo to 4.2.x

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#11199]
##### **Overview of the feature request**

See:
- https://docs.mongodb.com/manual/release-notes/4.2/
- https://docs.mongodb.com/manual/tutorial/upgrade-revision/

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by seraphinandrieux** [comment]
Hello @DanielFran , I'm working on it :)
