### ISSUE TITLE
jHipster mongolab connection

### ISSUE THREAD

**Issue by javajack** [jhipster/generator-jhipster#1120]
How do I connect to Mongolab ? Does it require additional configuration points ?

Mongo lab provides user and password except host and port. How to set those user and password ?

Following is the URI scheme for mongo driver. Could jHipster generate appropriate additional configuration ?

If not , how to solve it ? 
mongodb://<dbuser>:<dbpassword>@host:port/dbname

**Comment by jdubois** [comment]
You can add more options in the application.yml file, it's a Spring Boot + MongoDB configuration.

As this is all done by Spring Boot, and not JHipster, I'm forwarding you to the Spring Boot documentation, a good starting point is : https://spring.io/guides/gs/accessing-data-mongodb/
