### ISSUE TITLE
Redundant query parameter in many-to-many relationships in entity

### ISSUE THREAD

**Issue by lululu0620** [jhipster/generator-jhipster#11216]
##### **Overview of the issue**

When we generate an entity which contains many-to-many relationship with another entity, JHipster creates a query parameter for getAll endpoints called `eagerload`, but it's not used anywhere in EntityResource.java. 

There is already a logic to use either `findAllWithEagerRelationships` or `findAll` in the ejs template based on if the entity has a many-to-many relationship or not, so not sure why there is also an unused `eagerload` query parameter in the endpoints. 

If we want to give the option to load it eager or not during the runtime, shouldn't the generated Java code have:
```
if (eagerload) {
    return entityRepository.findAllWithEagerRelationships();
} else {
    return entityRepository.findAll();
}
```
?

##### **Motivation for or Use Case**

To make it configurable to eager or lazy load many-to-many relationships during runtime

##### **Reproduce the error**

1- Generate a microservice
2- Add an entity that has many-to-many relationship with another entity
3- Check the generated EntityResource.java file, getAll method have `eagerload` parameter but it isn't used.

##### **Suggest a Fix**

We should either remove `eagerload` parameter or use it in the getAll method.

##### **JHipster Version(s)**

6.5.1

##### **JHipster configuration**

We used this sample JDL https://github.com/jhipster/jdl-samples/blob/master/simple-online-shop.jh

##### **Browsers and Operating System**

MacOS Catalina

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by seraphinandrieux** [comment]
@lululu0620 I'm working on it
