### ISSUE TITLE
Enum Not Usable in ReactUI Conditions

### ISSUE THREAD

**Issue by RizziCR** [jhipster/generator-jhipster#11215]
##### **Overview of the issue**

I have some ENUM in my Monolith Project. I make some changes to the REACT frontendcode, but ENUM not working in production build.
In develop-mode I can compare the ENUM value from the Entity with a String, but not with the ENUM-Entity itself. But for the production build, the validation engine put out an error, that an comparison of ENUM and String isn't valid.

ENUM Definition from JDL File:
`enum MatchStatus {
  NONE, CREATED, SCHEDULED, READY, RUNNING, FINISHED, APPROVED
}`

1) Comparison that works in react:
`if (entity.matchStatus == 'RUNNING') {...}`

2) Comparison Works NOT in frontend:
`if (entity.matchStatus == MatchStatus.RUNNING) {...}`

Point 1 works in develop, but can't package it for production.
Point 2 can package for production, but not working.

commandline command that I use
`mvn -Pprod,swagger clean verify`

##### **Reproduce the error**

JDL:

```
application {
  config {
    applicationType monolith
    baseName example
    packageName com.example.my
    buildTool maven
    authenticationType jwt
    clientFramework react
    cacheProvider ehcache
    prodDatabaseType mariadb
    devDatabaseType h2Disk
    nativeLanguage en
    languages [en,de]
    useSass true
  }
  entities *
}

enum MatchStatus {
  NONE, CREATED, SCHEDULED, READY, RUNNING, FINISHED, APPROVED
}

entity Match {
    name String
    status MatchStatus
}
```

Then in the match list I change the code of the status column to show different colored icons for each status.

```
{ (() => {
                    switch (tournamentMatch.status) {
                      case 'READY':
                        return <span className="match-status-ready"/>;
                      case 'RUNNING':
                        return <span className="match-status-running"/>;
                      case 'FINISHED':
                        return <span className="match-status-finished"/>;
                      default:
                        return '-';
                    }
                  })() }
```
With string cases it works fine, but can't build for production

```
[INFO] Webpack: Starting ...
[INFO] Starting type checking service...
Webpack: Starting ...
[INFO] 
[INFO]    ✔ Compile modules
[INFO]    ✔ Build modules
[INFO]    ✔ Optimize modules
[INFO]    ✔ Emit files
[INFO] 
[INFO] Webpack: Finished after 49.419 seconds.
[INFO] 
[INFO]  ERROR  Failed to compile with 3 errors8:16:54 PM
[INFO] 
[INFO] ERROR in /..../matches.tsx
[INFO] TS2678: Type '"READY"' is not comparable to type 'MatchStatus'.
[INFO] 
[INFO] ERROR in /..../matches.tsx
[INFO] TS2678: Type '"RUNNING"' is not comparable to type 'MatchStatus'.
[INFO] 
[INFO] ERROR in /..../matches.tsx
[INFO] TS2678: Type '"FINISHED"' is not comparable to type 'MatchStatus'.
```

The entity enum is compared as a string, but the enum itself is compare as a number

##### **Environment and Tools**

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode)

git version 2.25.0

node: v13.7.0

npm: 6.13.6

yeoman: 3.1.0

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.2, build 698e2846

##### **Browsers and Operating System**

Operating System ist latest macOS Catalina.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by foxable** [comment]
I stumbled across the same problem. If the enum is defined without [explicit values](https://www.jhipster.tech/jdl/enums), JHipster generates a numeric enum in TypeScript:

JDL
```jdl
enum MyEnum {
  VALUE1
  VALUE2
}
```
my-enum.model.ts
```ts
export const enum MyEnum {
  VALUE1,
  VALUE2
}
```

So at runtime, the actual enum values are `0` and `1` instead of `'VALUE1'` and `'VALUE2'`. This does not match the values provided by the backend, which are the keys as strings.

If you explicitly define enum values in JDL, a TypeScript string enum with the expected values is defined.

JDL
```
enum MyEnum {
  VALUE1 (VALUE1)
  VALUE2 (VALUE2)
}
```

my-enum.model.ts
```ts
export const enum MyEnum {
  VALUE1 =  'VALUE1',
  VALUE2 = 'VALUE2'
}
```

However, instead of the keys, the keys plus their values appear as actual values in all other generated files, e.g. as translation keys (`VALUE1(VALUE1)` instead of just `VALUE1`). This does not seem desirable to me.

In my opinion, the TypeScript template should be fixed to always define a string enum, either using the explicit values, if defined, or the keys otherwise.

**Comment by foxable** [comment]
I just created  PR #11218 which fixes the enum template for React clients.

**Comment by pascalgrimaud** [comment]
fixed by https://github.com/jhipster/generator-jhipster/pull/11218

**Comment by tibistibi** [comment]
Do I understand that I need to put all enums like this:
```
enum MyEnum {
  VALUE1 (VALUE1)
  VALUE2 (VALUE2)
}
```

in my model to get this:
```
export const enum MyEnum {
  VALUE1 =  'VALUE1',
  VALUE2 = 'VALUE2'
}
```

And this will aslo work for Angular?
