### ISSUE TITLE
Relationship with UUID + DTO

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#11217]
##### **Overview of the issue**

When generating a relationship with UUID + DTO (mapstruct), the generated project didn't compile.

##### **Motivation for or Use Case**

Here the stacktrace:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/pgrimaud/tmp/04-bug-uuid-dto/src/main/java/io/github/pascalgrimaud/toto/service/mapper/AlphaMapper.java:[16,14] Can't map property "java.util.UUID alpha.beta.uuidCode" to "java.lang.String betaUuidCode". Consider to declare/implement a mapping method: "java.lang.String map(java.util.UUID value)".
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.666 s
[INFO] Finished at: 2020-01-31T10:17:49+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jhipster: Compilation failure
[ERROR] /home/pgrimaud/tmp/04-bug-uuid-dto/src/main/java/io/github/pascalgrimaud/toto/service/mapper/AlphaMapper.java:[16,14] Can't map property "java.util.UUID alpha.beta.uuidCode" to "java.lang.String betaUuidCode". Consider to declare/implement a mapping method: "java.lang.String map(java.util.UUID value)".
[ERROR] 

```

##### **Reproduce the error**

- generate a project with all default options
- use this JDL:

```
/**
 * The Alpha entity.
 * @author A true hipster
 */
entity Alpha {
  /** fieldName */
  name String
}

/**
 * The Beta entity.
 * @author A true hipster
 */
entity Beta {
  /** fieldName */
  name String
  uuidCode UUID
}

/**
 * Many to one relationship.
 */
relationship ManyToOne {
  Alpha{beta(uuidCode)} to Beta
}

dto * with mapstruct

```

##### **Suggest a Fix**

Probably something to do in this line:
https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs#L142

But other checks need to be done (tests / integration tests etc)

##### **JHipster Version(s)**

v6.6.0 and current master

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT /home/pgrimaud/tmp/04-bug-uuid-dto
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud.toto",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "io.github.pascalgrimaud.toto",
    "packageFolder": "io/github/pascalgrimaud/toto",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1580459341222,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * The Alpha entity.\n@author A true hipster
 */
entity Alpha {
  /**
   * fieldName
   */
  name String
}
/**
 * The Beta entity.\n@author A true hipster
 */
entity Beta {
  /**
   * fieldName
   */
  name String,
  uuidCode UUID
}
relationship ManyToOne {
  Alpha{beta(uuidCode)} to Beta
}

dto Alpha, Beta with mapstruct
service Alpha, Beta with serviceClass

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

git version 2.25.0

node: v12.14.0

npm: 6.13.4

yeoman: 3.1.1

yarn: 1.21.1

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.21.2, build a133471

**Comment by Falydoor** [comment]
The issue is also there with `Blob`, `AnyBlob ` and `ImageBlob `.

**Comment by maznag** [comment]
@Falydoor Yes, actually it works only for String type !
