### ISSUE TITLE
React webpack build broken for login.tsx typescript error in jwt choise

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster#11229]
##### **Overview of the issue**

When I perform ```npm run webpack:build``` or ```npm run webpack:prod``` with jwt security, the build fails with error:

```
ERROR in C:/Users/amanganiello/Desktop/jhipster-projects/gen-node/src/main/webapp/app/modules/login/login.tsx(26,11):
TS2339: Property 'from' does not exist on type '{} | { from: { pathname: string; search: string; }; }'.

```
##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT C:\Users\amanganiello\Desktop\jhipster-projects\gen-off
`-- generator-jhipster@6.6.0  -> C:\Users\amanganiello\Desktop\jhipster-projects\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1580818057827,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
Picked up _JAVA_OPTIONS: -Xmx512M

git version 2.24.1.windows.2

node: v12.13.1

npm: 6.12.1

yeoman: 2.0.6

yarn: 1.1.0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
I believe this is the same as https://github.com/jhipster/generator-jhipster/issues/11139. You can use the solution that was committed to master; https://github.com/jhipster/generator-jhipster/issues/11139#issuecomment-575938542

**Comment by amanganiello90** [comment]
okkk, thanks!

**Comment by SudharakaP** [comment]
@amanganiello90 : You are welcome 😄
