### ISSUE TITLE
[windows, protractor] change postinstall script in package.json

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11240]
##### **Overview of the issue**

postinstall breaks ui test locally on windows ( after update to jhipster 6.6)
following work around solves this issue currently:

` "postinstall": "node node_modules/protractor/bin/webdriver-manager update --gecko false --versions.chrome=72.0.3626.7",`

similiar to this issue: https://github.com/angular/webdriver-manager/issues/351, 80 instead of 74

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@geyuqiu : Can you give some more information about this issue and how to reproduce it. It would be nice if you could complete all the sections of the issue templates so that other members can reproduce it easily. 😄

**Comment by vishal423** [comment]
It's not an issue with JHipster, rather your environment. I would suggest updating your google chrome (to latest version `80.0.3987.87`).

However, the workaround you suggested can be added as a tip @ https://www.jhipster.tech/tips/ to help someone who wants to stick to an old version .

**Comment by geyuqiu** [comment]
> It's not an issue with JHipster, rather your environment. I would suggest updating your google chrome (to latest version `80.0.3987.87`).
> 
> However, the workaround you suggested can be added as a tip @ https://www.jhipster.tech/tips/ to help someone who wants to stick to an old version .

actually the error logs were missleading, the update to 80.x is done

but e2e on windows with it failed: 

![image](https://user-images.githubusercontent.com/4540661/73987435-adc00a80-4940-11ea-860c-68b7ce5bee11.png)


![image](https://user-images.githubusercontent.com/4540661/73987419-a39e0c00-4940-11ea-8314-11d74d39a6ee.png)

**Comment by kaidohallik** [comment]
@geyuqiu there are 2 different things:
* chromedriver downloaded by application
* chrome.exe installed in your system

If versions of those 2 doesn't match then you see this error.

Solution is as @vishal423 mentioned: update chrome.exe in your system to the latest version 80.
