### ISSUE TITLE
Update Hazelcast management-center to 4.0.x

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#11244]
##### **Overview of the feature request**

See:
- https://docs.hazelcast.org/docs/management-center/4.0/manual/html/index.html
- https://docs.hazelcast.org/docs/management-center/rn/index.html#4-0
- https://hazelcast.com/blog/hazelcast-imdg-4-0-is-released
- https://docs.hazelcast.org/docs/latest/manual/html-single/#migration-guides
- https://github.com/hazelcast/hazelcast/releases/tag/v4.0
- https://github.com/hazelcast/hazelcast/wiki/4.0
- https://github.com/hazelcast/hazelcast-hibernate5/releases/tag/v2.0.0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Similar to https://github.com/jhipster/generator-jhipster/pull/11179, the context-path changed again to be at `/` instead of `/hazelcast-mancenter` ([Docker image docs](https://hub.docker.com/r/hazelcast/management-center/))

**Comment by pascalgrimaud** [comment]
@DanielFran @ruddell : do you know how to fix this ?
- simply upgrade to the image to 4.0
- and modify the context-path ?

**Comment by ruddell** [comment]
It does not work out-of-the-box with just those changes, I'm guessing it also needs an update of Hazelcast to v4.x?
```
2020-03-05 10:55:34.684  INFO 60731 --- [  restartedMain] c.h.i.m.ManagementCenterService          : [127.0.0.1]:5702 [dev] [3.12.6] Hazelcast will connect to Hazelcast Management Center on address: 
http://localhost:8180
2020-03-05 10:55:34.699  INFO 60731 --- [  restartedMain] com.hazelcast.core.LifecycleService      : [127.0.0.1]:5702 [dev] [3.12.6] [127.0.0.1]:5702 is STARTED
2020-03-05 10:55:34.738  INFO 60731 --- [.MC.Task.Poller] c.h.i.m.ManagementCenterService          : [127.0.0.1]:5702 [dev] [3.12.6] Failed to pull tasks from Management Center
```

**Comment by jdubois** [comment]
I just tried to do it, and it's not as simple as the Hazelcast API has changed.
I'm putting a bug bounty here as this is our main caching option for scalable apps.

**Comment by jdubois** [comment]
I have some contacts with the Hazelcast team, and in fact Spring Boot doesn't support Hazelcast 4 at the moment, see https://github.com/spring-projects/spring-boot/issues/20856

As we define Hazelcast as a Spring Bean ourselves, we might be able to go around that issue.

**Comment by vishal423** [comment]
I have a working prototype with Hazelcast `v4.x`, however, that requires spring-boot `v2.3` (specifically on the actuator side). Tomorrow, I will make PR on the spring boot 2.3 migration branch.

**Comment by vishal423** [comment]
I think we can close the issue as the spring boot v2.3 branch changes (including hazelcast upgrade) have merged into master.

**Comment by pascalgrimaud** [comment]
thanks @vishal423
