### ISSUE TITLE
Update jboss/keycloak version to 9.0

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#11245]
##### **Overview of the feature request**

See:
- https://www.keycloak.org/docs/latest/release_notes/index.html

https://www.keycloak.org/2020/02/keycloak-900-released.html

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@vishal423 Have you time to make the update?

**Comment by vishal423** [comment]
@DanielFran, I can handle this over weekend.

**Comment by vishal423** [comment]
I did a quick check and there seem to be some issues importing realm/users with CLI scripts. I can do the same operation via the Admin console without issues. Further the script profile is deprecated in favor of a dedicated jar and in the near future, we also need to migrate. For this specific issue, I will see if I can spend some more time debugging the issue and get a quick solution.

**Comment by vishal423** [comment]
I did some debugging and noticed an open issue on the [Keycloak](https://issues.redhat.com/projects/KEYCLOAK/issues/KEYCLOAK-12921) side. We may have to wait for the next release.

**Comment by vishal423** [comment]
Now that [Keycloak](https://www.keycloak.org/2020/02/keycloak-900-released.html) `v9` is released, I will try again over weekend.

**Comment by vishal423** [comment]
I did a quick check and the issue observed with the `v8.0.2` is fixed in the `v9.0`. I will soon raise a PR.
