### ISSUE TITLE
Maintainer Reply Templates as Saved Replies

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#11242]
##### **Overview of the feature request**

Currently we have maintainer templates in the [`.github/MAINTAINERS_REPLY_TEMPLATES`](https://github.com/jhipster/generator-jhipster/tree/master/.github/MAINTAINERS_REPLY_TEMPLATES) folder. I suggest adding these as [Saved Reply Templates](https://help.github.com/en/github/writing-on-github/working-with-saved-replies). 

Method to do so is highlighted here; https://help.github.com/en/github/writing-on-github/creating-a-saved-reply

Usage is highlighted here; https://help.github.com/en/github/writing-on-github/using-saved-replies

##### **Motivation for or Use Case**

This way we don't have to copy paste but rather could select from the saved reply list when composing a response to a pull request or issue. 😄

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
Actually I realized I can do this myself. Sorry about that. 👍

**Comment by jdubois** [comment]
Yes, all this GitHub tools that facilitate our work are always welcome.
Just please send your template (probably through the mailing list?) so we can all agree on the wording.
Thanks a lot!

**Comment by SudharakaP** [comment]
@jdubois : We already have them publicly available at;https://github.com/jhipster/generator-jhipster/tree/master/.github/MAINTAINERS_REPLY_TEMPLATES. If I create any new ones though; I'll sure to share them with you guys. 😄

**Comment by mshima** [comment]
I wasn't aware of this.
Thanks @SudharakaP.

**Comment by SudharakaP** [comment]
@mshima : You are welcome 👍

**Comment by deepu105** [comment]
I thought we already did that as I get them in drop-down already

**Comment by SudharakaP** [comment]
@deepu105 : My guess is that it's not an organizational setting but rather user's need to add it on their own account. For example I had to go to my account settings and add it under `Saved Replies`. The instructions point in that direction too; https://help.github.com/en/github/writing-on-github/creating-a-saved-reply.

**Comment by deepu105** [comment]
Then may be I would have done that
