### ISSUE TITLE
Cannot generate Jhipster project with token authentication

### ISSUE THREAD

**Issue by davykiala** [jhipster/generator-jhipster#1125]
I use yeoman 1.4.5 and jhipster 2.1.1, i generate the project with the following option : 
Welcome to the JHipster Generator

? (1/13) What is the base name of your application? jhipster
? (2/13) What is your default Java package name? com.mycompany.myapp
? (3/13) Do you want to use Java 8? Yes (use Java 8)
? (4/13) Which *type* of authentication would you like to use? Token-based authentication (stateless, with a token)
? (5/13) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL)
? (6/13) Which *production* database would you like to use? MySQL
? (7/13) Which *development* database would you like to use? MySQL
? (8/13) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
? (9/13) Do you want to use clustered HTTP sessions? No
? (10/13) Do you want to use WebSockets? No
? (11/13) Would you like to use Maven or Gradle for building the backend? Maven (recommended)
? (12/13) Would you like to use Grunt or Gulp.js for building the frontend? Grunt (recommended)
? (13/13) Would you like to use the Compass CSS Authoring Framework? (y/N) n

THE FIRST ERROR: 

bower bootstrap#3.3.2                                 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/twbs/bootstrap.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Operation timed out
npm WARN package.json jhipster@0.0.0 No repository field.
npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.0","npm":"2.5.1"})

THEN THIS 

generator-jhipster@2.1.1 node_modules/generator-jhipster
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── shelljs@0.3.0
├── underscore.string@2.3.3
├── cheerio@0.17.0 (dom-serializer@0.0.1, entities@1.1.1, htmlparser2@3.7.3, CSSselect@0.4.1)
├── insight@0.4.3 (object-assign@1.0.0, async@0.9.0, lodash.debounce@2.4.1, os-name@1.0.3, tough-cookie@0.12.1, request@2.53.0, configstore@0.3.2, inquirer@0.6.0)
└── yeoman-generator@0.17.7 (dargs@2.1.0, diff@1.2.2, class-extend@0.1.1, rimraf@2.2.8, text-table@0.2.0, mime@1.3.4, async@0.9.0, isbinaryfile@2.0.3, debug@1.0.4, cross-spawn@0.2.6, nopt@3.0.1, run-async@0.1.0, mkdirp@0.5.0, iconv-lite@0.4.7, grouped-queue@0.3.0, findup-sync@0.1.3, file-utils@0.2.2, glob@4.3.5, github-username@1.1.1, download@1.0.7, gruntfile-editor@0.2.0, request@2.53.0, inquirer@0.7.3)
Running "ngconstant:dev" (ngconstant) task
Creating module tokApp at src/main/webapp/scripts/app/app.constants.js...OK

Running "wiredep:app" (wiredep) task
Warning: Error: Cannot find where you keep your Bower packages. Use --force to continue.

Aborted due to warnings.

Execution Time (2015-02-11 19:03:43 UTC)
loading tasks    80ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 29%
ngconstant:dev   15ms  ▇▇▇▇▇▇▇ 5%
wiredep:app     177ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 65%

If i use the option --force , this will not produces others problem on my app ?

**Comment by jdubois** [comment]
The error is that you can't connect to Github -> I suppose you are behind a corporate firewall

Bower needs to connect to Github in order to download dependencies.

I'd like to help you more, because I know there's a trick for using Bower behind a firewall, but I can't remember it...

It's not a JHipster issue, so I'm closing this.

**Comment by saaspeter** [comment]
I also got this: Warning: Error: Cannot find where you keep your Bower packages, but I can connect github very well.

**Comment by gmarziou** [comment]
Try running rff-doctor to get a diagnostic: https://github.com/rakuten-frontend/rff-doctor
