### ISSUE TITLE
gae generator: can't find the WEB-INF content for static resources (index.html, etc)

### ISSUE THREAD

**Issue by ludoch** [jhipster/generator-jhipster#11253]
##### **Overview of the issue**

With the GAE java11 generator, the appengine-staging directory used for deployment using thin root does not seem to contain the web app resources (WEB-INF/*) so the app does not work when deployed (404 errors).

##### **Reproduce the error**

jhipster
(use monolit) and all defaults
jhispter gae
(use all default, or F2)
deploy using documented way
See error on the page activation.

##### **JHipster Version(s)**

Trying with the latest one released this week

Not sure where static content (WEB-INF/*) is supposed to appear either in the main jar or the repository/ areas for deps, but I do not see it so far for GAE...

**Comment by SudharakaP** [comment]
Hmm... This is strange. I thought I did a full test on this. :thinking: Let me try to do a full deployment and get back to you. :smile:

**Comment by SudharakaP** [comment]
Found it. :smile: This is related to; https://github.com/jhipster/generator-jhipster/pull/11207. The default activation of the webpack profile means that we have to update the documentation for maven to include the webpack profile. Let me do a PR for that. :smile:

**Comment by SudharakaP** [comment]
Done. When deploying try the `./mvnw package appengine:deploy -DskipTests -Pgae,webpack,prod-gae`. That should do the trick. :smile:

**Comment by vishal423** [comment]
@SudharakaP, The `webpack` profile executes the development build and is not recommended to be used in production.

**Comment by pascalgrimaud** [comment]
I don't care if there are duplicated part in the pom.xml : so if needed, we should add the missing part about webpack in gae.

**Comment by SudharakaP** [comment]
@vishal423 : Thanks for pointing it out. Agreed. Think what we could do is use the `prod` profile in addition to the `gae` profile (which creates the thin jar) when deploying to GAE. Let me make that change. Feel free to let me know if you disagree or has a better solution. :smile:

**Comment by pascalgrimaud** [comment]
adding the prod profile with gae is a good idea !

**Comment by SudharakaP** [comment]
I've modified both PRs submitted above to use `Prod` profile instead. :smile:

**Comment by ludoch** [comment]
Verified!
Thanks so much for the quick turnaround...
Ideally for next improvement will be to separate the static resources from the main jar, but what we have now is great! Thanks!

**Comment by SudharakaP** [comment]
No problem. You are welcome. And yes separating the static resources is something to look forward to. :smile:
