### ISSUE TITLE
angular: Upgrade to v9.0

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#11255]
##### **Overview of the feature request**

Angular v9 is finally out with Ivy support and breaking changes. Check
https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3
##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
I have something working on my laptop, will provide a PR tomorrow

**Comment by ksilz** [comment]
@wmarques Not sure if you're aware: `ng-bootstrap` also needs an [upgrade for Angular 9](https://github.com/ng-bootstrap/ng-bootstrap/issues/3537).

**Comment by wmarques** [comment]
@ksilz Thanks, however I didn't have any issue with ng-bootstrap while upgrading.. Strange, I'll follow this!

**Comment by pascalgrimaud** [comment]
I'm adding a bounty on this as it's important to have in the next release and it's more work than expected
