### ISSUE TITLE
flaky cpu/memory overflow issues when building jar for production in gitlab

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11251]
build jar fails sometimes on a gitlab server with 1.78G RAM

![image](https://user-images.githubusercontent.com/4540661/73983321-6fbde900-4936-11ea-8ca8-fa198ebb5d22.png)

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by geyuqiu** [comment]
![image](https://user-images.githubusercontent.com/4540661/73983763-7a2cb280-4937-11ea-9ac1-3b5f8c42f41c.png)
during 
`node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.prod.js" "--profile"
`

**Comment by SudharakaP** [comment]
@geyuqiu : Could you please fill in the issue template fully so that people can reproduce your issue easily. 😄

**Comment by pascalgrimaud** [comment]
Simply increase the memory on your GitLab server ?

**Comment by geyuqiu** [comment]
trying with 1024 instead of 4096 (4GB) https://medium.com/@vuongtran/how-to-solve-process-out-of-memory-in-node-js-5f0de8f8464c, https://stackoverflow.com/questions/48387040/nodejs-recommended-max-old-space-size/48392705

**Comment by geyuqiu** [comment]
> Simply increase the memory on your GitLab server ?

if it is so easy :)

**Comment by PierreBesson** [comment]
I would recommend at least 4Gb of ram for the webpack build. For Gitlab, I recommend setting up an external Gitlab runner : https://docs.gitlab.com/runner/install/

**Comment by geyuqiu** [comment]
@PierreBesson I will have this in mind for next cloud project :)
