### ISSUE TITLE
Render Login Directly on Home

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11257]
##### **Overview of the feature request**

move login inside of home component instead of modal dialog

- less popups
- simpler design
- less bugs?
- in angular

1.  get rid of `login-modal.service.ts`
2.  less dependencies of `loginModalService `in `auth-expired.interceptor`, `homeComponent`, `userRouteAcessService`
3. no more `this.activeModal.dismiss('cancel');`

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@geyuqiu : Thanks for taking the time to write the suggestions; it would be helpful if you could follow the issue templates for bugs or new features and add more details on what exactly you mean by "less popups", "simple design" and "less bugs" and the reasoning behind each of the improvements you mentioned. And maybe some reproducible examples on the bugs you see. :smile:

**Comment by vishal423** [comment]
I also like to move away from the login dialog. If we all agree, then, we should do this across all UI implementations; `angular`, `react`, `vue`.

**Comment by mohamedsogoba** [comment]
please man how to install jhipster i am newcomer.
i need to documentation

**Comment by SudharakaP** [comment]
@mohamedsogoba : Hi, we have loads of documentation on our website, https://www.jhipster.tech/ and if you have any specific questions feel free to ask them on [StackOverflow](https://stackoverflow.com/tags/jhipster) with the jhipster tag or at our [Gitter channel](https://gitter.im/jhipster/generator-jhipster?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge).

**Comment by pascalgrimaud** [comment]
we could do it, but only for v7
I'm not against this

**Comment by mraible** [comment]
Is there a PR related to this issue? If not, I'd prefer to close it until there's some action on it.

**Comment by maznag** [comment]
https://github.com/jhipster/generator-jhipster/pull/11926
