### ISSUE TITLE
[jdl] more options for entity generation, e.g. read only access is only possible

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11259]
##### **Overview of the feature request**

generate read only operations for an entity, instead of generating all 4 crud operations 

`crud A ONLY_CREATE`
`crud B CRUD`

##### **Motivation for or Use Case**

currently for many entities, we import-jdl first, and then manually remove all create, update and delete operations (*.java, *IT.java, *.ts, *.html, *.ts, *.spec.ts and protractor tests ), because e.g. read only access is permitted for certain entities

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by murdos** [comment]
Use the `readOnly` option for an entity. See https://www.jhipster.tech/jdl/options#available-options and https://github.com/jhipster/jhipster-core/pull/370
