### ISSUE TITLE
Jhipster UAA is Unable to load the keys from config/tls/keystore.p12. from ec2.

### ISSUE THREAD

**Issue by dronavallisaikrishna** [jhipster/generator-jhipster#11270]
##### **Overview of the issue**
I have created a jhipster application with microservice architecture. I have a registry, UAA and a gateway.
Now to move them to production i have created a new keystore.p12 for UAA and modified the alias and password and name of the UAA server as shown below.
```
uaa:
  #be sure to to change to a different keystore in production!
  #create one using: keytool -genkey -alias aliasName -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
  key-store:
    name: config/tls/keystore.p12
    password: mypassword
    alias: aliasName
```

i created the keystore file using the jhipster recommended command from application-prod.yml
`keytool -genkey -alias aliasName -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
`

The issue is after updating these parameters in my local, i tried running with the command `./mvnw -Pprod`. This works absolutely fine. 
But after moving the respective jar to ec2 instance I am getting the error as shown below.

```2020-02-10 06:32:50.779  WARN 3736 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration': Unsatisfied dependency expressed through field 'tokenStore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenStore' defined in class path resource [com/star/auth/config/UaaConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtTokenStore]: Factory method 'tokenStore' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtAccessTokenConverter' defined in class path resource [com/star/auth/config/UaaConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtAccessTokenConverter' threw exception; nested exception is java.lang.IllegalStateException: Cannot load keys from store: class path resource [classpath:config/tls/keystore.p12]```

The thing that i dont understand is, i have modified the gateway and registry server keystore properties as well. But they work fine. Only UAA server is creating this exception.

Even UAA server with dev environment is also throwing the same error.

`

##### **JHipster Version(s)**
6.5.1

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.star.auth",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "uaa",
    "baseName": "StarAuthentication",
    "packageName": "com.star.auth",
    "packageFolder": "com/star/auth",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "Y2JmNmY0NDZlYzNlZjJiYzZkMGI3ZWVjYzIxODA0NzcyOWVjODkwMDA2MTA0MjYyYjE2OTZlZDY0ODBiZDEyNmJiZmY5NTBkMGUzYzhiMDQ5Nzg2OTNhZDkwYjNjZmIwYWY0Y2JiNTRiNzNkYzYzYTQ5MDY1YTI5YTMyMmNmMGQ=",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi",
      "ta",
      "te"
    ],
    "blueprints": [],
    "skipClient": true
  }
}
```

##### **Browsers and Operating System**
My local systme is using Mac Os catelina 10.15, ec2 is using ubuntu 18.04

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
As you said, it works fine locally, but fails when you deploy to ec2.

So that's why I don't think it's a JHipster bug as it would fail locally too. It's something related to your environnement in EC2. You should ask help to StackOverFlow instead.

I'm closing this as it will be impossible for us to reproduce your issue, unless, you have full steps to do it locally.
