### ISSUE TITLE
Can't find needle code for 'jhipster-needle-add-admin-route'

### ISSUE THREAD

**Issue by WiteCastle** [jhipster/generator-jhipster#11285]
##### **Overview of the issue**

I'm attempting to update the [elasticsearch-reindexer module](https://github.com/WiteCastle/generator-jhipster-elasticsearch-reindexer) to the latest Jhipster version but I can't find the function that'll update the `jhipster-needle-add-admin-route` section. Has this functionality been removed? I don't see any code to edit that needle in the Angular client api:

https://github.com/jhipster/generator-jhipster/blob/00e3a657810cc7d0ee81572763f6ea5909b7ca0d/generators/client/needle-api/needle-client-angular.js#L56-L59

##### **Motivation for or Use Case**

A route should be added to the admin-routing.module.ts file.

##### **Reproduce the error**

1. Create a new jhipster module
2. Attempt to add a new admin menu item
3. You'll notice that a new menu item is added to the admin menu but when clicked the page does not exist.

##### **Related issues**

Possibly #10443

##### **Suggest a Fix**

Add code to the angular needle client that adds back the ability to edit the admin-route needle.

##### **JHipster Version(s)**

```
generator-jhipster-elasticsearch-reindexer@1.2.1 D:\Ebsan\workspace\generator-jhipster-elasticsearch-reindexer
`-- generator-jhipster@6.7.0
```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

git version 2.24.1.windows.2

node: v12.13.0

npm: 6.13.7

yeoman: 3.1.1

##### **Browsers and Operating System**

Windows 10, all browsers

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
What was the original jhipster version?

**Comment by WiteCastle** [comment]
The original module was using Jhipster version 6.3.1. 

The original module is here: https://github.com/geraldhumphries/generator-jhipster-elasticsearch-reindexer

**Comment by mshima** [comment]
Just looked at jhipster 6.3.1 code, jhipster-needle-add-admin-route was never used.

I proposed https://github.com/jhipster/generator-jhipster/pull/10286 that used it.
But I closed it as I didn't had the time to work on it.

**Comment by kaidohallik** [comment]
I opened #11289 to add this missing function.
