### ISSUE TITLE
Create New Workflow for Label Cleanup

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#11283]
##### **Overview of the feature request**

As per the following discussion, I thought it would be nice to have a workflow that cleans up labels in our issues. So for example once a issue is closed labels like `triage`, `undefined`, `needs-reproduction` and `waiting for information` needs to be automatically removed. 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/jhipster-dev/xfrODe_g14U

##### **Motivation for or Use Case**

Cleanup old labels of closed issues. 😄 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
I think we can add more labels for the cleanup (for example status labels maybe?). But given we don't adhere to a strict labeling policy I wanted to keep it simple. Please feel free to let me know if you want to include more labels or have any other suggestions. 😄

**Comment by pascalgrimaud** [comment]
it's good idea ! I just need time to think more about it and propose something here too !

**Comment by SudharakaP** [comment]
@pascalgrimaud : Thanks; [@mshima  suggested](https://github.com/jhipster/generator-jhipster/pull/11284#issuecomment-584813557) to keep the `area: triage` and `theme: undefined` and remove the `status: work in progress`.

Please feel free to let me know your thoughts as well; once everyone comes to an agreement I'll make some modifications. 😄

**Comment by DanielFran** [comment]
I believe we should change, if possible, the workflow that add the 2 labels to add them only if no label of the same type is not present.

**Comment by mshima** [comment]
> @pascalgrimaud : Thanks; [@mshima suggested](https://github.com/jhipster/generator-jhipster/pull/11284#issuecomment-584813557) to keep the `area: triage` and `theme: undefined` and remove the `status: work in progress`.

Close/reopen off the issue will remove those labels, it should be kept for reopen.

I think we should remove every `status: *`, and rename those that should be kept.
`status: bounty-requested` => `bounty: requested`
`status: bounty-approved` => `bounty: approved`
`status: should go to modules` => `resolution: should go to modules`
`status: wont-fix` => `resolution: wont-fix`

**Comment by mshima** [comment]
> I believe we should change, if possible, the workflow that add the 2 labels to add them only if no label of the same type is not present.

I agree with you, but this will make the workflow much more complicated.
Instead of just writing, it will be read then write.

**Comment by SudharakaP** [comment]
> > @pascalgrimaud : Thanks; [@mshima suggested](https://github.com/jhipster/generator-jhipster/pull/11284#issuecomment-584813557) to keep the `area: triage` and `theme: undefined` and remove the `status: work in progress`.
> 
> Close/reopen off the issue will remove those labels, it should be kept for reopen.
> 
> I think we should remove every `status: *`, and rename those that should be kept.
> `status: bounty-requested` => `bounty: requested`
> `status: bounty-approved` => `bounty: approved`
> `status: should go to modules` => `resolution: should go to modules`
> `status: wont-fix` => `resolution: wont-fix`

@mshima : I agree with keeping the `area: triage` and `theme: undefined` and removing/renaming the `status: *` labels; but maybe given our label creation isn't governed by any rules, I am thinking if we need to discuss this a bit more. 

Currently in the entire repo (even including closed issues and pull requests) I see; 0 bounty-requested labels, 5 bounty-approved labels, 0 should go to modules labels and 42 wont-fix labels. So I am not sure if we are improving things by adding automated rules to these labels which are rarely used. :smile: 

Rather I would suggest if we do have this kind of more sophisticated label renaming maybe we should first identify and agree upon the labels we do use and make rules for them instead. :smile: 

cc: @jhipster/developers

**Comment by SudharakaP** [comment]
I've modified the code to keep the `area: triage` and `theme: undefined` labels and only remove `area: needs-reproduction`, `area: waiting for information` and all `status: *` labels for now. The implementation of renaming the status labels should be doable as as well as long as you guys think its worthwhile; just feel free to let me know. :smile:
