### ISSUE TITLE
Delete Non Used getToken Method in AuthServerProvider

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11296]
##### **Overview of the feature request**
this method is never called in source code
```
getToken(): string {
    return this.$localStorage.retrieve('authenticationToken') || this.$sessionStorage.retrieve('authenticationToken') || '';
}

```
##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@geyuqiu : Can you give some more information; I think you are referring to; 

https://github.com/jhipster/generator-jhipster/blob/a0b0d6643558223db053f9f6a156075d298c70f1/generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs#L60-L62

But that method is used at,

https://github.com/jhipster/generator-jhipster/blob/a0b0d6643558223db053f9f6a156075d298c70f1/generators/client/templates/angular/src/main/webapp/app/core/tracker/tracker.service.ts.ejs#L64

**Comment by geyuqiu** [comment]
@SudharakaP which flag do I have to set to get tracker.service enabled? because I am not having a directory with the name `tracker` under  .../app/core

**Comment by pascalgrimaud** [comment]
@geyuqiu : you can try to generate a project with websockets option

**Comment by geyuqiu** [comment]
great, closing this for now :)
