### ISSUE TITLE
Elastic Search on Kubernetes OOMKilled

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#11301]
##### **Overview of the issue**

If service uses ES, and generates the Kubernetes manifiest, ES deployment fails to start and is OOMKilled.

##### **Motivation for or Use Case**

ES should work.

##### **Reproduce the error**

https://github.com/jhipster/jdl-samples/blob/master/microservices-blog-store.jh

##### **Suggest a Fix**

Determine & increase resource limit.

##### **JHipster Version(s)**

6.7.0

##### **JHipster configuration**

https://github.com/jhipster/jdl-samples/blob/master/microservices-blog-store.jh

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

https://github.com/jhipster/jdl-samples/blob/master/microservices-blog-store.jh

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
fixed by https://github.com/jhipster/generator-jhipster/pull/11303
