### ISSUE TITLE
[jhipster cli, option select, windows] 

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11306]
##### **Overview of the issue**
use arrow keys or push space to select not working in jhipster cli on windows

not sure if this is a problem with [git windows](https://git-scm.com/download/win) or jhipster cli

![image](https://user-images.githubusercontent.com/4540661/74422223-90ae9e80-4e4e-11ea-9ee1-cc26b31fe906.png)

##### **JHipster Version(s)**
6.6.

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
This issue is related to windows terminal. You should use another terminal like powershell, git bash or something like Cmdr.
