### ISSUE TITLE
[sonar, windows, not on mac!] Line 3 of report refers to a file with an unknown language:... account.service.spec.ts 

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11307]
##### **Overview of the issue**

`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) `

##### **Reproduce the error**

local windows machine
```
npm test
mvnw -Pprod -Dcheckstyle.skip verify sonar:sonar -Dsonar.host.url=http://[remote-sonar-url]
# skip checkstyle disable nohttp errors 

```

.gitlab-ci.yml

```
./mvnw -q compile -Dmaven.repo.local=$MAVEN_USER_HOME
./mvnw -q org.jacoco:jacoco-maven-plugin:prepare-agent initialize sonar:sonar -Dsonar.host.url=http://[remote-url] -Dsonar.login=$SONAR_TOKEN -Dmaven.repo.local=$MAVEN_USER_HOME
```

##### **Suggest a Fix**

similiar error message on windows and linux-ci-server: 

`Error during parsing of generic test execution report '...target\tes\jest\TESTS-results-sonar.xml'. Look at the SonarQube documentation to know the expected XML format.: Line 3 of report refers to a file with an unknown language ... account.service.spec.ts`

this worked on Mac with local-docker-sonar-setup (currently no docker allowed at client on ci-linux-server and windows: which are bad news, I know right xD)

TESTS-results-sonar.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
  <file path="...\src\test\javascript\spec\app\core\user\account.service.spec.ts">
    <testCase name="Service Tests Account Service authenticate authenticationState should emit null if input is null" duration="65"/>
    <testCase name="Service Tests Account Service authenticate authenticationState should emit the same account as was in input parameter" duration="15"/>
```

##### **JHipster Version(s)**

6.6

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by geyuqiu** [comment]
comment out 

`#sonar.testExecutionReportPaths=target/test-results/jest/TESTS-results-sonar.xml`

in `sonar-project.properties` the commands succeed and statistics are visible on remote sonar dashboard

**Comment by geyuqiu** [comment]
works on mac this way:

```
docker-compose -f src/main/docker/sonar.yml up -d
npm test
mvnw -Pprod verify sonar:sonar
```

**Comment by pascalgrimaud** [comment]
@geyuqiu : I already saw this but I don't remember well where and why. Plz, maybe check the Sonar version ?

**Comment by pascalgrimaud** [comment]
I'm closing this as I think it comes from the Sonar version.
Feel free to provide more information to reproduce the problem locally
