### ISSUE TITLE
Managing fine grain rights on entities/resources

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1131]
The entity generator exposes the whole entity through a resource, this works fine in simple cases but it's not enough as soon as you want to filter data based on user's roles or when a field update is conditioned by business logic. This is why in JHipster there is a UserDto and User entity.

Documentation could help by giving some guidelines like using DTOs, adding business logic to services or controllers, using JsonView, ... I can only think of solutions involving hand coding but may there are also some declarative approaches that I don't know.

Anyway if this requires hand coding, do you think that the generator could help here to promote some practices by generating extra code?

**Comment by jdubois** [comment]
Yes this has to be hand coded, at some point we can't generate everything, people need to write their business rules.

**Comment by gmarziou** [comment]
OK so what about sharing some practices in documentation?
if we extended the example of Book and Author by adding different authorizations, it could be a separate guide.

**Comment by jdubois** [comment]
That's "normal" Spring architecture to me. Of course it's good to write that down (I've done that kind of thing for the service sub-generator, so I can't say it's bad!), but maybe this should be in a separate "end user" guide

**Comment by gmarziou** [comment]
I'll go through this process in following weeks in my current project so I'll try to clarify my thoughts on this and share.

**Comment by jdubois** [comment]
OK -> feel free to share, you can also do some kind of "guide" or "how to", we miss that kind of thing in the documentation
