### ISSUE TITLE
there is no MySql, PostgreSql... database option when trying to generate Reactive application

### ISSUE THREAD

**Issue by mahaouchi9** [jhipster/generator-jhipster#11326]
Hello 
this is my first time using Jhipster and I have an issue with the database options offered by jhipster.

actually, i want to use an SQL DB but i cant find it in the [options:] 

![Capture](https://user-images.githubusercontent.com/29981856/74609709-eb652600-50ec-11ea-93a7-89c77d686a87.PNG)

Maybe it because of something related to machine, but since I'm new to jhipster I can't figure it out.

thinks in advance for your reply.

**Comment by mshima** [comment]
They are disabled for reactive:
https://github.com/jhipster/generator-jhipster/blob/cdb9ef09d7fb821402504ebc1c578c82a9026a93/generators/server/prompts.js#L164-L169

**Comment by pascalgrimaud** [comment]
As mentionned by @mshima, Reactive option is only for NoSQL database, so it's normal.
I'm closing this as it's not a bug

**Comment by mahaouchi9** [comment]
Ok thank you for the response!

**Comment by cbornet** [comment]
I've started working on r2dbc. You can see the progress here : https://github.com/cbornet/jhipster-r2dbc
