### ISSUE TITLE
Kubernetes: Ingress extensions/v1beta1 -> networking.k8s.io/v1beta1

### ISSUE THREAD

**Issue by huytmb** [jhipster/generator-jhipster#11324]
##### **Overview of the issue**

Resource Ingress is deprecated in Kubernetes API `extensions/v1beta1`

> **apiVersion: extensions/v1beta1**
> kind: Ingress

Referencing PR: https://github.com/kubernetes/kubernetes/pull/74057

In `generator-constants.js` of generator: 
https://github.com/jhipster/generator-jhipster/blob/448d48ec9df570ee4c68f46050e23c0c936b49b7/generators/generator-constants.js#L80

##### **Suggest a Fix**

> **apiVersion: networking.k8s.io/v1beta1**
> kind: Ingress

##### **JHipster Version(s)**
6.7.1

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/generator-jhipster/pull/11325
