### ISSUE TITLE
app.constants.js is missing from the source tree in jhipster v 2.2

### ISSUE THREAD

**Issue by StasPereverziev** [jhipster/generator-jhipster#1132]
I've generated a project with jhipster v 2.2 and there are no app.constants.js file in a source tree

**Comment by jdubois** [comment]
No enough information to reproduce this issue

**Comment by StasPereverziev** [comment]
I did next steps:

Welcome to the JHipster Generator

 (1/13) What is the base name of your application? jhipster
 (2/13) What is your default Java package name? com.jhepster
 (3/13) Do you want to use Java 8? Yes (use Java 8)
 (4/13) Which *type* of authentication would you like to use? HTTP Session Authentication (stateful, default Spring Security mechanism)
 (5/13) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL)
 (6/13) Which *production* database would you like to use? MySQL
 (7/13) Which *development* database would you like to use? MySQL
 (8/13) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
 (9/13) Do you want to use clustered HTTP sessions? No
 (10/13) Do you want to use WebSockets? No
 (11/13) Would you like to use Maven or Gradle for building the backend? Maven (recommended)
 (12/13) Would you like to use Grunt or Gulp.js for building the frontend? Grunt (recommended)
 (13/13) Would you like to use the Compass CSS Authoring Framework? (y/N) N

In the end I've got an error 

generator-jhipster@2.2.0 node_modules/generator-jhipster
├── shelljs@0.3.0
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── underscore.string@2.3.3
├── cheerio@0.17.0 (dom-serializer@0.0.1, entities@1.1.1, CSSselect@0.4.1, htmlparser2@3.7.3)
├── yeoman-generator@0.17.7 (dargs@2.1.0, diff@1.2.2, class-extend@0.1.1, text-table@0.2.0, mime@1.3.4, debug@1.0.4, grouped-queue@0.3.0, isbinaryfile@2.0.3, cross-spawn@0.2.6, nopt@3.0.1, run-async@0.1.0, async@0.9.0, mkdirp@0.5.0, rimraf@2.2.8, iconv-lite@0.4.7, findup-sync@0.1.3, github-username@1.1.1, glob@4.3.5, file-utils@0.2.2, gruntfile-editor@0.2.0, request@2.53.0, download@1.0.7, inquirer@0.7.3)
└── insight@0.4.3 (object-assign@1.0.0, async@0.9.0, os-name@1.0.3, lodash.debounce@2.4.1, tough-cookie@0.12.1, request@2.53.0, configstore@0.3.2, inquirer@0.6.0)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

After that project was generated without an app.constants.js file in a source tree

**Comment by jdubois** [comment]
OK, the real issue is the error you got: can you give the full stack trace? Its probably that you don't have npm correctly installed

**Comment by MardariG** [comment]
Have the same problem.

**Comment by andrelugomes** [comment]
Have the same problem here.

The server running but just show me "This is your footer" ob browser.
![error1](https://cloud.githubusercontent.com/assets/1247724/6755356/4abb192a-cf01-11e4-9747-313896e8b59b.png)
![error2](https://cloud.githubusercontent.com/assets/1247724/6755357/4abd4f6a-cf01-11e4-92b3-e14666a27acf.png)

**Comment by jdubois** [comment]
Same issue: you had an error when installing npm and/or bower
Do a "npm install" and "bower install" manually. Maybe also a "grunt wiredep" afterwards.

**Comment by andrelugomes** [comment]
$ npm install
npm WARN prefer global yo@1.4.6 should be installed with -g

> yo@1.4.6 postinstall c:\Users\s2it_agomes\workspace\jhipster\node_modules\yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory

Everything looks all right!

----------------------------------------
$ bower install
bower bootstrap#3.3.2       not-cached git://github.com/twbs/bootstrap.git#3.3.2
bower bootstrap#3.3.2          resolve git://github.com/twbs/bootstrap.git#3.3.2
bower modernizr#2.8.3       not-cached git://github.com/Modernizr/Modernizr.git#2.8.3
bower modernizr#2.8.3          resolve git://github.com/Modernizr/Modernizr.git#2.8.3
bower jquery#2.1.3          not-cached git://github.com/jquery/jquery.git#2.1.3
bower jquery#2.1.3             resolve git://github.com/jquery/jquery.git#2.1.3
bower json3#3.3.2           not-cached git://github.com/bestiejs/json3.git#3.3.2
bower json3#3.3.2              resolve git://github.com/bestiejs/json3.git#3.3.2
bower angular-resource#1.3.11       not-cached git://github.com/angular/bower-angular-resource.git#1.3.11
bower angular-resource#1.3.11          resolve git://github.com/angular/bower-angular-resource.git#1.3.11
bower angular-ui-router#0.2.13      not-cached git://github.com/angular-ui/ui-router.git#0.2.13
bower angular-ui-router#0.2.13         resolve git://github.com/angular-ui/ui-router.git#0.2.13
bower angular-i18n#1.3.11           not-cached git://github.com/angular/bower-angular-i18n.git#1.3.11
bower angular-i18n#1.3.11              resolve git://github.com/angular/bower-angular-i18n.git#1.3.11
bower angular-translate#2.6.0       not-cached git://github.com/PascalPrecht/bower-angular-translate.git#2.6.0
bower angular-translate#2.6.0          resolve git://github.com/PascalPrecht/bower-angular-translate.git#2.6.0
bower angular#1.3.11                not-cached git://github.com/angular/bower-angular.git#1.3.11
bower angular#1.3.11                   resolve git://github.com/angular/bower-angular.git#1.3.11
bower angular-cookies#1.3.11        not-cached git://github.com/angular/bower-angular-cookies.git#1.3.11
bower angular-cookies#1.3.11           resolve git://github.com/angular/bower-angular-cookies.git#1.3.11
bower angular-sanitize#1.3.11       not-cached git://github.com/angular/bower-angular-sanitize.git#1.3.11
bower angular-sanitize#1.3.11          resolve git://github.com/angular/bower-angular-sanitize.git#1.3.11
bower angular-translate-storage-cookie#2.6.0       not-cached git://github.com/PascalPrecht/bower-angular-translate-storage-cookie.git#2.6.0
bower angular-translate-storage-cookie#2.6.0          resolve git://github.com/PascalPrecht/bower-angular-translate-storage-cookie.git#2.6.0
bower angular-translate-loader-partial#2.6.0       not-cached git://github.com/PascalPrecht/bower-angular-translate-loader-partial.git#2.6.0
bower angular-translate-loader-partial#2.6.0          resolve git://github.com/PascalPrecht/bower-angular-translate-loader-partial.git#2.6.0
bower angular-dynamic-locale#0.1.24                not-cached git://github.com/lgalfaso/angular-dynamic-locale.git#0.1.24
bower angular-dynamic-locale#0.1.24                   resolve git://github.com/lgalfaso/angular-dynamic-locale.git#0.1.24
bower angular-local-storage#0.1.5                  not-cached git://github.com/grevory/angular-local-storage.git#0.1.5
bower angular-local-storage#0.1.5                     resolve git://github.com/grevory/angular-local-storage.git#0.1.5
bower swagger-ui#2.0.24                            not-cached git://github.com/wordnik/swagger-ui.git#2.0.24
bower swagger-ui#2.0.24                               resolve git://github.com/wordnik/swagger-ui.git#2.0.24
bower angular-cache-buster#0.4.3                   not-cached git://github.com/saintmac/angular-cache-buster.git#0.4.3
bower angular-cache-buster#0.4.3                      resolve git://github.com/saintmac/angular-cache-buster.git#0.4.3
bower angular-scenario#1.3.11                      not-cached git://github.com/angular/bower-angular-scenario.git#1.3.11
bower angular-scenario#1.3.11                         resolve git://github.com/angular/bower-angular-scenario.git#1.3.11
bower ngInfiniteScroll#1.2.0                       not-cached git://github.com/sroze/ngInfiniteScroll.git#1.2.0
bower ngInfiniteScroll#1.2.0                          resolve git://github.com/sroze/ngInfiniteScroll.git#1.2.0
bower angular-mocks#1.3.11                         not-cached git://github.com/angular/bower-angular-mocks.git#1.3.11
bower angular-mocks#1.3.11                            resolve git://github.com/angular/bower-angular-mocks.git#1.3.11
bower bootstrap#3.3.2                                 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/twbs/bootstrap.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=No error

**Comment by andrelugomes** [comment]
I had to re-install Grunt and worked... but grunt wiredep give me this:
$ grunt wiredep
Running "wiredep:app" (wiredep) task
Warning: Error: Cannot find where you keep your Bower packages. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-03-20 16:46:34 UTC)
loading tasks  70ms  ███████████ 6%
wiredep:app    1.1s  ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 93%
Total 1.1s

**Comment by jdubois** [comment]
It is normal, you have a fatal error at the end of "bower install".

I guess you are behind a corporate firewall, you need to have access to Github -> you need to do a 
```
git config --global url."https://".insteadOf git://

**Comment by andrelugomes** [comment]
I got it! I hav some probles with Bower instalations... it can't access github.com because some rules on my net work. 

The solution: git config --global url."https://".insteadOf git://

https://github.com/Laverna/laverna/issues/60

**Comment by jdubois** [comment]
wow, we replied the same solution at the same time :-)

**Comment by andrelugomes** [comment]
hahah in the same time... thanks

**Comment by rilopez** [comment]
I had the similar npm install problems while generating my app, tried without luck a `npm install & bower install && grunt wiredep`  but after digging into the code ,  I found that the app.constants.js file is generated by the `ngconstant` grunt task. so I just ran 

    grunt ngconstant

and  the http 404 for app.constants.js went away
