### ISSUE TITLE
Bad readability for swagger-ui with dark themes

### ISSUE THREAD

**Issue by Joniator** [jhipster/generator-jhipster#11330]
##### **Overview of the issue**

If using a dark theme, the readability of swagger is almost zero. The dark font color blends with the background color.

##### **Motivation for or Use Case**

This breaks swagger-ui for any dark theme, the text blends with the background.

##### **Reproduce the error**

- Create new project
- Use a dark theme (e.g. darky)
- Log in as admin
- Navigate to the api docs

##### **Suggest a Fix**

Add a scss to the docs component that sets the iframe background to white
- or -
If a dark theme was selected, add a theme to swagger-ui that is suited for dark backgrounds.

##### **JHipster Version(s)**
```
bug-tracker-j-hipster@0.0.1-SNAPSHOT /home/jonathanboeckel1996/cloudshell_open/BugTrackerJHipster
└── generator-jhipster@6.7.1
```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "monolith",
    "baseName": "Example",
    "packageName": "com.example.example",
    "packageFolder": "com/example/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "darkly",
    "clientThemeVariant": "dark",
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}
</pre>
</details>
##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
<details>
<summary>JDL entity definitions</summary>
<pre>
</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
git version 2.11.0
node: v10.14.2
npm: 6.13.7
yarn: 1.22.0
Docker version 19.03.5, build 633a0ea838
docker-compose version 1.24.0, build 0aa59064

**Comment by pascalgrimaud** [comment]
would you like to propose a solution with a PR @Joniator plz ?

**Comment by Joniator** [comment]
I did, but I am confused as to why the pipeline is still failing.

First was clear, there were 2 tests that failed (I didn't notice since on my machine 200+ tests fail ootb), but I managed to fix them.

Now it fails at `React / react-maven-psql-es-noi18n-mapsid` and I have no idea as to why or how I can even reproduce this locally.

**Comment by mshima** [comment]
> Now it fails at `React / react-maven-psql-es-noi18n-mapsid` and I have no idea as to why or how I can even reproduce this locally.

This is normal.
React e2e fails sometimes.
I’ve triggered a rebuild.

**Comment by mshima** [comment]
Looks like github messed up. 🤦‍♂ 
Second time I see every react test fail like this.
@Joniator can you recreate last commit and force push?
I think this is the only way to clear github error. 😒

**Comment by Joniator** [comment]
I recreated the commit, lets hope for the best
