### ISSUE TITLE
Default spring service name

### ISSUE THREAD

**Issue by xvitcoder** [jhipster/generator-jhipster#1133]
At the moment if you run **"yo jhipster:service book"** and select to generate also the interface for this service, it will generate the class like this

````java
@Service
@Transactional
public class BookServiceImpl implements BookService {
    private final Logger log = LoggerFactory.getLogger(BookServiceImpl.class);
}
```

It is nice, but the bean name of this service in the spring context will be **"bookServiceImpl"**, which is not very common, it should be **"bookService"** after the interface name.

It would be nice that the *jhipster:service* sub-generator would name the services with interfaces by interface name like this:

````java
@Service("bookService")
@Transactional
public class BookServiceImpl implements BookService {
    private final Logger log = LoggerFactory.getLogger(BookServiceImpl.class);
}
```

**Comment by jdubois** [comment]
I know what you mean, and you are correct about this name, but we will stick the way we are now:

- We always keep the default names and configuration, unless we have an issue. It's easier to understand for new users if we don't change the default configuration
- In practice, nobody cares about the Spring bean names anyway, as you are going to use an @inject annotation, which will work on the class name
