### ISSUE TITLE
[spring security] prevent brute force auth

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11333]
##### **Overview of the feature request**
Has there been a discussion about blocking failed password attempts in general ?
Simply put – we'll keep a record of the number of failed attempts (originating from a single IP address). If that particular IP goes over a set number of requests – it will be blocked for ever (24 hours).
more information:
[prevent brute force auth with spring security](https://www.baeldung.com/spring-security-block-brute-force-authentication-attempts)

##### **Motivation for or Use Case**

enhance security for option jwt e.g.

##### **Related issues or PR**

don't know

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
it's an interesting feature to have in real project, but not for JHipster as it goes too far. It would be complex to implement as you need to take care about:
- security option
- cache option

Maybe if you think it's must have, you can start to implement it inside a JHipster module. Then, if it becomes really popular, we can reconsider to include it directly in generator-jhipster.
