### ISSUE TITLE
MS SQL dependency not found on maven central

### ISSUE THREAD

**Issue by nbaiocco** [jhipster/generator-jhipster#11356]
##### **Overview of the issue**

Jhipster 6.7.0 and 6.7.1 includes a dependency for Microsoft SQL Server apparently not existent on maven central:
`
<dependency>
	<groupId>com.microsoft.sqlserver</groupId>
	<artifactId>mssql-jdbc</artifactId>
</dependency>
`
(version <mssql-jdbc.version>8.1.1.jre8</mssql-jdbc.version> from jhipster-dependencies)

Produces this compile error:
**Could not find artifact com.microsoft.sqlserver:mssql-jdbc:pom:8.1.1.jre8 in maven.intesys.it (http://maven.intesys.it/content/groups/public/)**

##### **Reproduce the error**

Generate a jHipster project with ms-sql database type.

##### **Suggest a Fix**

Update dependency version to: <version>8.2.0.jre8</version>

##### **JHipster Version(s)**

6.7.0, 6.7.1

##### **JHipster Version(s)**

```
quote-calculator@0.0.1-SNAPSHOT C:\Develop\Workspaces\IdeaProjects\scb_quotecalculator
`-- generator-jhipster@6.7.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "it.intesys",
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "monolith",
    "baseName": "quoteCalculator",
    "packageName": "it.intesys",
    "packageFolder": "it/intesys",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "infinispan",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mssql",
    "prodDatabaseType": "mssql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1577806306162,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": ["it", "en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.25.0.windows.1

node: v12.14.1

npm: 6.13.7

yeoman: 3.1.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Thanks for reporting this.
Indead, the jhipster dependencies 3.0.4 uses:

But since few days, we already upgrade it:
- https://github.com/jhipster/jhipster/commit/382ff7d7211d00351de62fb28ca298c514d5fffe
- https://github.com/jhipster/jhipster/commit/1853f51dc10cdb6d43a4496d1ca3903842a0058b

So it's already fixed and will be in the next release

**Comment by pascalgrimaud** [comment]
@nbaiocco : for your information, I just did a new release of jhipster lib: 3.5.0. It will be available in few hours, so you can upgrade this lib in your project
