### ISSUE TITLE
Avoid Code Duplication in @RequestMapping in [entityName]Resource.java

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11353]
##### **Overview of the feature request**
entity name should be in `@RequestMapping `in `[entityName]Resource.java`, in order to avoid code duplication of entity name in @GetMapping, @PostMapping, @PutMapping, @DeleteMapping etc.
```
@RestController
@RequestMapping("/api/[entityName]")
// ...
@GetMapping("/{id}")
// ...
@DeleteMapping("/{id}")
```
instead of 

```
@RestController
@RequestMapping("/api")
// ...
@GetMapping("/[entityName]/{id}")
// ...
@DeleteMapping("/[entityName]/{id}")
```

##### **Motivation for or Use Case**

cleaner ?

##### **Related issues or PR**

don't know

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@geyuqiu : LGTM, would you like to contribute and provide a pull request for this plz ?

**Comment by geyuqiu** [comment]
@pascalgrimaud 
do you have a link for best practice guide / acceptance criteria for pull requests regarding *.ejs ?

**Comment by pmverma** [comment]
@geyuqiu Quick links for you!
https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md
https://github.com/jhipster/generator-jhipster/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by pascalgrimaud** [comment]
@geyuqiu : did you start this ?

**Comment by pascalgrimaud** [comment]
Closing this as it can be an improvement
But no anwser means no one want to work on this, so closing this ticket
