### ISSUE TITLE
[*ResourceIT.java, liquibase, refactoring, enhancement, clean] reuse master.xml and fakedata in integration tests

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11357]
##### **Overview of the feature request**

reuse master.xml and fakedata in test

##### **Motivation for or Use Case**
**current situation:** 

\- fakedata in xml format are not reused in test environment
\- instead fake data for integration tests are created in *ResourceIT.java. via methods `createUpdatedEntity `and `createEntity `
\- code duplication and not a best practice
\- currently getting following error if trying `@DataJpaTest` :( 
`cannot find liquibase classpath:/db/changelog/db.changelog-master.yaml`

**changes needed and may look better after the feature is finished:** 

\+ src/TEST/resources/config/application.yml
- add `faker` so that `spring.liquibase.contexts = test, faker`
- `spring.liquibase.change-log = classpath:config/liquibase/master.xml `(even better use default path/name of master changeLog of `LiquibaseProperties`): 
```
public class LiquibaseProperties {
    private String changeLog = "classpath:/db/changelog/db.changelog-master.yaml";
    // ...
}
```
might be interesting, because thus, no changes needed, but may break if default implementation in `LiquibaseProperties ` from Spring Boot changes

\+ copy everything under src/main/resources/config/liquibase to `test `folder during generation
\+ `@DataJpaTest` "unit" tests are possible for `[entityName]Repository.java`, instead of clumsy integration tests including whole Spring context via `@SpringBootTest(classes = [AppName].class)`
\+ optional ? possible ? other changes: set liquibase properties in application-*.yml not via `LiquibaseConfiguration.java`:
`liquibase.setChangeLog("classpath:config/liquibase/master.xml");`

##### **Potential changes overall**

A lot, A lot, A lot

##### **Related issues or PR**

no idea

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
fake data is used only for dev, in local, not in other profile, because some users don't like this and don't want fake data

If you want to keep these data, you can use a specific profile + context, it should work well, or use the same way we did for inserting data for user.

**Comment by pascalgrimaud** [comment]
Forget my last comment, I though you want to use fake data in other environment like integration, pre-production etc...

**Comment by pascalgrimaud** [comment]
I didn't try this solution, but could you try this to add `faker` to liquibase context in application.yml file from test plz ?

**Comment by pascalgrimaud** [comment]
Just tried it and I confirm it work.
You can apply this diff:

```diff
diff --git a/src/test/resources/config/application.yml b/src/test/resources/config/application.yml
index 177c4413..8492a487 100644
--- a/src/test/resources/config/application.yml
+++ b/src/test/resources/config/application.yml
@@ -45,7 +45,7 @@ spring:
       hibernate.hbm2ddl.auto: validate
       hibernate.jdbc.time_zone: UTC
   liquibase:
-    contexts: test
+    contexts: test, faker
   mail:
     host: localhost
   main:
```

**Comment by geyuqiu** [comment]
> Just tried it and I confirm it work.
> You can apply this diff:
> 
> ```diff
> diff --git a/src/test/resources/config/application.yml b/src/test/resources/config/application.yml
> index 177c4413..8492a487 100644
> --- a/src/test/resources/config/application.yml
> +++ b/src/test/resources/config/application.yml
> @@ -45,7 +45,7 @@ spring:
>        hibernate.hbm2ddl.auto: validate
>        hibernate.jdbc.time_zone: UTC
>    liquibase:
> -    contexts: test
> +    contexts: test, faker
>    mail:
>      host: localhost
>    main:
> ```

yeah, this is working for me already, that is why I wrote /src/TEST

**Comment by geyuqiu** [comment]
@pascalgrimaud Just a general suggestion from me to use faker data in tests, because tests against a empty db is somehow not production like, because a prod db will mostly likely have data.
