### ISSUE TITLE
Reorder Entity Crud Components Folder Structure

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11366]
##### **Overview of the feature request**

suggested generated Project structure

```
entities/  
|- update/                  
|  |- [entityName]-update.component.html                
|  |- [entityName]-update.component.ts
|- detail/                  
|  |- [entityName]-detail.component.html                 
|  |- [entityName]-detail.component.ts
|- delete-dialog/                  
|  |- [entityName]-delete-dialog.component.html                
|  |- [entityName]-delete-dialog.component.ts
|- [entityName].route.ts     
|- [entityName].service.ts
|- [entityName].module.ts   
|- [entityName].component.html                
|- [entityName].component.ts   
```

current generated Project structure

```
entities/                
|- [entityName]-update.component.html                
|- [entityName]-update.component.ts          
|- [entityName]-detail.component.html                 
|- [entityName]-detail.component.ts               
|- [entityName]-delete-dialog.component.html                
|- [entityName]-delete-dialog.component.ts
|- [entityName].route.ts     
|- [entityName].service.ts
|- [entityName].module.ts   
|- [entityName].component.html                
|- [entityName].component.ts   
```

##### **Motivation for or Use Case**

too much files in 1 directory ?

##### **Related issues or PR**
no idea
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I'd rather have all the files in one directory. If you're manually navigating from the command line or in an IDE, it's easier to go into one directory. Personally, I like to use Command + Shift + N in IntelliJ to find files by name.

**Comment by SudharakaP** [comment]
@geyuqiu : Hi geyuqiu 😄 Just to note that I've renamed the title of your issue. You probably don't need to use tags such as `[folder structure, angular, enhancement]` in the title as we use [GitHub labels](https://help.github.com/en/github/managing-your-work-on-github/about-labels) anyways.

**Comment by pascalgrimaud** [comment]
It needs to be discussed before doing something

**Comment by mshima** [comment]
> too much files in 1 directory ?

Is not a good argument to keep it open.
There is 2 rejection at least, mine included.
Closing for now.

**Comment by geyuqiu** [comment]
Although being rejected, I just want to point out that the folders can be blown up easily and become harder to have a overview by adding additional components for that entity.
