### ISSUE TITLE
WARs are not executed on Tomcat while jars are working

### ISSUE THREAD

**Issue by aydincaner** [jhipster/generator-jhipster#11365]
##### **Overview of the issue**

I export as war and when i try to remote machine tomcat, it gives error.

##### **Motivation for or Use Case**

I cant deploy to tomcat.

##### **Reproduce the error**

1- Use jhipster to generate spring + angular project with gradle
2- Export as war with that command:

` ./gradlew -Pwar clean bootWar`

because

`./gradlew -Pprod -Pwar clean bootWar`

gives error:

FAILURE: Build failed with an exception.

* What went wrong:
Task 'bootWar??' not found in root project 'halil'. Some candidates are: 'bootJar', 'bootWar'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s`

so , i use this:

``./gradlew -Pwar clean bootWar`
then it gives war.
3- Put to tomcat. Then get error
4- Export as jar with that:

`./gradlew -Pprod -Pjar clean bootJar`
5- Use **java -jar xx.jar** to run and there is no error

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/9829#issuecomment-589649434
https://github.com/jhipster/generator-jhipster/issues/5996
##### **Suggest a Fix**
I also tried to change **new BaseHrefWebpackPlugin({ baseHref:** to war file name but did not work

maybe tomcat versions
##### **JHipster configuration**
jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
halil@0.0.1-SNAPSHOT C:\Projects\WORK\halil
`-- generator-jhipster@6.7.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.bpn.legolas",
      "nativeLanguage": "tr"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "monolith",
    "baseName": "halil",
    "packageName": "com.bpn.legolas",
    "packageFolder": "com/bpn/legolas",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1582210924944,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "tr",
    "languages": ["tr", "al", "ar-ly"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

git version 2.21.0.windows.1

node: v12.14.1

npm: 6.13.4

yeoman: 3.1.1

yarn: 1.22.0

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
none

##### **Browsers and Operating System**

windows 10. chrome my machine
client machine is same too
**tomcat version:** 8.5
**java:**8
-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
What are these 2 characters at the end of your gradle command? It seems to be the reason why your build fails:

> $ ./gradlew -Pprod -Pwar clean bootWar��
> What went wrong:
> Task 'bootWar??' 

Looks like character encoding issue or copy/pasting error.
Have you tried typing manually the command?

**Comment by aydincaner** [comment]
@gmarziou  i edited question. And answers to your questions.

For **` ./gradlew **:

`$ ./gradlew

> Task :bootRun

        ??? ???   ??? ????????? ????????   ??????? ????????? ????????? ????????
        ??? ???   ??? ????????? ????????? ???????? ????????? ????????? ?????????
        ??? ?????????    ???    ????????? ???????     ???    ???????   ?????????
  ???   ??? ?????????    ???    ????????   ???????    ???    ???????   ????????
  ????????? ???   ??? ????????? ???       ????????    ???    ????????? ???  ????
   ???????  ???   ??? ????????? ???       ???????     ???    ????????? ???   ???

:: JHipster ?  :: Running Spring Boot 2.2.4.RELEASE ::
:: https://www.jhipster.tech ::

2020-02-21 17:53:11.681  INFO 3180 --- [  restartedMain] com.bpn.legolas.HalilApp                 : Starting HalilApp on caydin-nb with PID 3180 (C:\Projects\WORK\halil\build\classes\java\main started by caydin in C:\Projects\WORK\halil)
2020-02-21 17:53:11.683 DEBUG 3180 --- [  restartedMain] com.bpn.legolas.HalilApp                 : Running with Spring Boot v2.2.4.RELEASE, Spring v5.2.3.RELEASE
2020-02-21 17:53:11.683  INFO 3180 --- [  restartedMain] com.bpn.legolas.HalilApp                 : The following profiles are active: dev,swagger
2020-02-21 17:53:13.799 DEBUG 3180 --- [  restartedMain] i.m.c.u.i.logging.InternalLoggerFactory  : Using SLF4J as the default logging framework
2020-02-21 17:53:13.976 DEBUG 3180 --- [  restartedMain] com.bpn.legolas.config.WebConfigurer     : Registering CORS filter
2020-02-21 17:53:13.998  INFO 3180 --- [  restartedMain] com.bpn.legolas.config.WebConfigurer     : Web application configuration, using profiles: dev
2020-02-21 17:53:13.999  INFO 3180 --- [  restartedMain] com.bpn.legolas.config.WebConfigurer     : Web application fully configured
2020-02-21 17:53:14.123 DEBUG 3180 --- [  restartedMain] c.b.legolas.security.jwt.TokenProvider   : Using a Base64-encoded JWT secret key
2020-02-21 17:53:15.234 DEBUG 3180 --- [  restartedMain] c.bpn.legolas.config.AsyncConfiguration  : Creating Async Task Executor
2020-02-21 17:53:15.703 DEBUG 3180 --- [  restartedMain] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Starting Swagger
2020-02-21 17:53:15.711 DEBUG 3180 --- [  restartedMain] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Started Swagger in 7 ms
2020-02-21 17:53:16.214 ERROR 3180 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8080 was already in use.

Action:

Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 10s
7 actionable tasks: 2 executed, 5 up-to-date`

from cmd.

On powershell,  

`/gradlew -Pprod -Pwar clean bootWar `

works and gives war and again it does not work at tomcat.

**Comment by gmarziou** [comment]
https://stackoverflow.com/questions/60338181/jhipster-spring-angular-jar-working-but-not-war-working

**Comment by aydincaner** [comment]
@gmarziou it is my question. And same errors :(

**Comment by gmarziou** [comment]
Yes and cross-posting is a bad practice, it just makes it more difficult to help you.

**Comment by pascalgrimaud** [comment]
Here what I know, from my recent tests:
- Maven + War (using java -jar *.warr) -> KO
- Maven + War + Tomcat -> KO
- Gradle + War -> OK
- Gradle + War + Tomcat -> KO
That's why it's disabled in our CI currently (except for Gradle)

Then, I already discussed with @PierreBesson about it, and I think it's time for removing War packaging.
It requires too much effort to maintain it, for nothing.
It's broken since months, but no one wants to fix it.

So, @aydincaner : you are really welcome to provide a PR and propose a fix, as you're using War file.

**Comment by geyuqiu** [comment]
Maven + war (jhipster version 6.5.1) + tomcat
 worked for me once, but then I switched to jar

**Comment by caneraydinbey** [comment]
@geyuqiu jar with gradle worked also in tomcat?

**Comment by caneraydinbey** [comment]
@geyuqiu jar with gradle worked also in tomcat?

@pascalgrimaud  i dont think i can do that PR. I need too much time

Ajd i am putting two screenshots. They seem maybe helpful. The error in the console and in the network tab.


![Annotation 2020-02-24 121554](https://user-images.githubusercontent.com/17731063/75140671-6a1b1e00-5700-11ea-94d2-6adae067b053.png)

![Annotation 2020-02-24 121821](https://user-images.githubusercontent.com/17731063/75140668-67b8c400-5700-11ea-94c1-7ac76e9e05d6.png)

**Comment by caneraydinbey** [comment]
I created angular + spring with maven this time. Changed jar to war in pomxml and put to webapp in tomcat. but similar errors again

![image](https://user-images.githubusercontent.com/17731063/75153609-df94e780-571c-11ea-9f2c-5c5debb93cd2.png)

**Comment by geyuqiu** [comment]
> @geyuqiu jar with gradle worked also in tomcat?
> 
> @pascalgrimaud i dont think i can do that PR. I need too much time
> 
> Ajd i am putting two screenshots. They seem maybe helpful. The error in the console and in the network tab.
> 
> ![Annotation 2020-02-24 121554](https://user-images.githubusercontent.com/17731063/75140671-6a1b1e00-5700-11ea-94d2-6adae067b053.png)
> 
> ![Annotation 2020-02-24 121821](https://user-images.githubusercontent.com/17731063/75140668-67b8c400-5700-11ea-94c1-7ac76e9e05d6.png)

've never had a great relationship with gradle, maybe it was because of the error message of missing dependencies I don't remember, consequently... I tried to avoid that, except for Android, where there are no alternatives xD

**Comment by ruddell** [comment]
@caneraydinbey Based on the screenshots, you are deploying under a context path, but did not configure the baseHref.  In your case it should be `/halil-2-0.0.1-SNAPSHOT/` ([configure it here](https://github.com/jhipster/generator-jhipster/blob/ec26d48bf7683ba768d4ff07dcfcf73e8f141fb1/generators/client/templates/angular/webpack/webpack.common.js.ejs#L120))

**Comment by caneraydinbey** [comment]
@ruddell for **halil2\webpack\webpack.common.js** I changed this line:

`new BaseHrefWebpackPlugin({ baseHref: '/halil-2-0.0.1-SNAPSHOT' })`

and then repackaged with **maven**.

Then i put again under webapps undet tomcat and started:

![image](https://user-images.githubusercontent.com/17731063/75243863-b9824c80-57db-11ea-9d9f-a03d005e46d4.png)



When i go to 

http://localhost:8080/halil-2-0.0.1-SNAPSHOT/

it gives errors again:

![image](https://user-images.githubusercontent.com/17731063/75243872-c1da8780-57db-11ea-831f-7b81995121fa.png)


Network tab:

![image](https://user-images.githubusercontent.com/17731063/75243884-c737d200-57db-11ea-860b-c60b52fcadeb.png)

I use intellij idea **package** option from maven menu:

![image](https://user-images.githubusercontent.com/17731063/75243933-dfa7ec80-57db-11ea-80b4-cce77442cedb.png)

I also ran from powershell:

`mvn -Pdev package`

![image](https://user-images.githubusercontent.com/17731063/75244217-796f9980-57dc-11ea-9a2e-17d2746ce3be.png)


this time it did not bring it:

![image](https://user-images.githubusercontent.com/17731063/75244340-b50a6380-57dc-11ea-926b-8b264929936f.png)

tomcatlogs:

![image](https://user-images.githubusercontent.com/17731063/75244348-bb98db00-57dc-11ea-806d-e23e5556ab32.png)

**Comment by ruddell** [comment]
@caneraydinbey Your baseHref needs to match the baseHref in my last message, you forgot the trailing slash.  It will apply to both dev and prod, so you may want to copy the BaseHrefWebpackPlugin config to webpack.prod.js and only apply it there.

**Comment by vishal423** [comment]
I spent some time on this and don't see any issues at least with maven. Here is what I tried and worked for me:
1. Generate session authentication based monolithic project with name as `sessionapp`
2. Change the `baseHref` in the `webpack.common.js` to `/sessionapp/`
3. Create a war using `./mvnw -Pprod,war clean verify -DskipTests`
4. Rename the generated war from `sessionapp-0.0.1-SNAPSHOT.war` to `sessionapp.war` so that it matches the `baseHref`
5. Copy the `sessionapp.war` to the tomcat's `webapps` directory and post deployment, access the application with URL: `http://localhost:8080/sessionapp/`

Post step #3, if you want to deploy the generated `sessionapp-0.0.1-SNAPSHOT.jar` using `java -jar`:

4. Rename the generated jar from `sessionapp-0.0.1-SNAPSHOT.jar` to `sessionapp.jar` so that it matches the `baseHref`
5. Specify context path as environment variable or as a command line parameter and run the jar. I tried with command line parameter using command `java -jar sessionapp.jar --server.servlet.context-path=/sessionapp` and post deployment, access the application with URL `http://localhost:8080/sessionapp/`

@pascalgrimaud , @aydincaner - Can you try following above steps to see if that also works for you?

**Comment by pascalgrimaud** [comment]
@vishal423 : thanks for having a look, I'll try your steps.
On your side, did you try to launch war file directly, as it should be executable file ?

**Comment by pascalgrimaud** [comment]
@vishal423 :
- I have no problems, following your steps, it works well
- now, I only have problem when starting war from command line:

```
➜ java -jar target/jhburger.war            
aucun attribut manifest principal dans target/jhburger.war
```

**Comment by vishal423** [comment]
@pascalgrimaud, I also see the same issue with executable war. Most likely, it's an issue with `maven-war-plugin` configurations. If no one else is looking into it, I can try to spend some time over the next few days.

**Comment by pascalgrimaud** [comment]
@vishal423 : yes please, if you can

**Comment by vishal423** [comment]
@pascalgrimaud, per my analysis, the war generated with inclusion of `war` maven profile is not executable. I actually don't see much usefulness of this war as it can contain conflicting dependencies that should be provided by container and would personally prefer to remove it.

IMO, the correct steps to generate a war ( + executable) should be:
1. Generate Jhipster application (e.g. session authentication based monolithic project) with name as `sessionapp`
2. Change the `baseHref` in the `webpack.common.js` to `/sessionapp/`
3. In `pom.xml`, change packaging to `war`
4. In `pom.xml`, change scope of `spring-boot-starter-undertow` to `provided`
3. Create a war (executable and original) using `./mvnw -Pprod clean verify -DskipTests`
4. Rename the generated war from `sessionapp-0.0.1-SNAPSHOT.war` to `sessionapp.war` so that it matches the `baseHref`
5. Copy the `sessionapp.war` (either executable or original)  to the tomcat's `webapps` directory and post deployment, access the application with URL: `http://localhost:8080/sessionapp/`
6. You can also run the executable war as `java -jar sessionapp.war --server.servlet.context-path=/sessionapp` and post deployment, access the application with URL `http://localhost:8080/sessionapp/`

There was an issue with executable war generated in step 3, that I have fixed in a PR.

**Comment by pascalgrimaud** [comment]
Agree with you @vishal423 
So for me, we just need to:
- merge your other PR
- add documentation at https://www.jhipster.tech/production/#building-an-executable-jar--war-file with the steps you provided

@vishal423 : can you do the documentation part plz ? Then I think we can close this ticket, with the bounty for you

**Comment by pascalgrimaud** [comment]
Closing this as both PR have been merged
Thanks a lot @vishal423 :)

**Comment by rennydonny** [comment]
What about gateway jhipster project? @vishal423 , I changed yours indications, However I got the above same error:

webpack.common.js
`template: './src/main/webapp/index.html',
            chunks: ['polyfills', 'main', 'global'],
            chunksSortMode: 'manual',
            inject: 'body',
            base: '/',
            base: '/gateway',
        }),`
.../swagger-ui/index.html
`axios.get("/swagger-resources").then(function (response) {
            response.data.forEach(function (resource) {
                urls.push({"name": resource.name, "url": resource.location});
                urls.push({"name": resource.name, "url": "/gateway"+resource.location});
            });`
pom.xml
`....
<packaging>war</packaging>
....
               <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-undertow</artifactId>
                    <scope>provided</scope>
                </dependency>
`

![image](https://user-images.githubusercontent.com/4966706/94352114-a90eaa80-0026-11eb-8b89-b9220a3ce36b.png)

**Comment by gmarziou** [comment]
@rennydonny please open a new issue with all required details rather than commenting a 7 months old issue

**Comment by vishal423** [comment]
@rennydonny, I just tried with a gateway project and don't see any issue. In your shared configurations, you have missed the trailing slash and `base: '/gateway'` should be `base: '/gateway/'`
