### ISSUE TITLE
Introduce GIVEN, WHEN, THEN in tests

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11363]
##### **Overview of the feature request**

there are couple of comments in integration tests in java.
But there is no general structure, how they are ordered.
However, a comment sometimes "lies" because code is changed easily and comments often live longer,. Code does not lie. `Given, when, then` pattern normally does not lie.
get rid of some trivial comments like
```
// Create the [entityName]
[EntityName]DTO [entityName]DTO = [EntityName]Mapper.toDto([entityName]);
// ...
// Initialize the database
[EntityName]Repository.saveAndFlush([entityName]);
// ...
// Update the [entityName]
```

keep intelligent comments: 
```
// Disconnect from session so that the updates on [entityName] are not directly saved in db
em.detach([entityName]);
```

##### **Motivation for or Use Case**

establish good practice regarding comments in tests

##### **Related issues or PR**

no idea

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
It could be also an opportunity to promote the use of JUnit 5's `@DisplayName`

**Comment by pascalgrimaud** [comment]
Yes, feel free to contribute and improve this part

**Comment by pascalgrimaud** [comment]
@geyuqiu : did you start this ?

**Comment by pascalgrimaud** [comment]
Then, it can be an improvement, but if no one wants to contribute, it won't be done
Closing this as no answer, we have other ticket to focus on
