### ISSUE TITLE
Monolithic application generation with eureka does not present an option to chose authentication type; always defaults to JWT

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#11373]
##### **Overview of the issue**
Monolithic application generation with eureka does not present an option to chose authentication type; always defaults to JWT

```
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)                       
? [Alpha] Do you want to make it reactive with Spring WebFlux? No                                                                      
? What is the base name of your application? jhipster                                                                                  
? What is your default Java package name? com.mycompany.myapp                                                                          
? Do you want to use the JHipster Registry to configure, monitor and scale your application? Yes                                       
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)                                  
? Which *production* database would you like to use? MySQL                                                                             
? Which *development* database would you like to use? H2 with disk-based persistence                                                   
? Do you want to use the Spring cache abstraction? Yes, with the Ehcache implementation (local cache, for a single node)               
? Do you want to use Hibernate 2nd level cache? Yes                                                                                    
? Would you like to use Maven or Gradle for building the backend? Maven                                                                
? Which other technologies would you like to use? (Press <space> to select, <a> to toggle all, <i> to invert selection)                
? Which *Framework* would you like to use for the client? Angular                                                                      
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster                                                 
? Would you like to enable internationalization support? Yes                                                                           
? Please choose the native language of the application English                                                                         
? Please choose additional languages to install (Press <space> to select, <a> to toggle all, <i> to invert selection)                  
? Besides JUnit and Jest, which testing frameworks would you like to use? (Press <space> to select, <a> to toggle all, <i> to invert se
lection)                                                                                                                               
? Would you like to install other generators from the JHipster Marketplace? (y/N)
```

##### **JHipster Version(s)**
master

##### **JHipster configuration**
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT /home/vishal/ang/session-eureka
└── generator-jhipster@6.7.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "yarn",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1582390988626,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0, JRE 13 Linux amd64-64-Bit Compressed References 20200117_151 (JIT enabled, AOT enabled)
OpenJ9   - 6968c18d7
OMR      - 7a1b0239a
JCL      - 9c5a41bd5f based on jdk-13.0.2+8)

git version 2.25.0

node: v12.13.1

npm: 6.12.1

yarn: 1.21.1

Docker version 19.03.6, build 369ce74a3c

docker-compose version 1.25.0, build 0a186604

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
There is a specific conditional.
https://github.com/jhipster/generator-jhipster/blob/80de24a7df4000a29b0a88653df176c06612431b/generators/server/prompts.js#L108

**Comment by vishal423** [comment]
I think it used to work before, but not quite sure. If this combination is not supported/valid, then, we can close the issue.

**Comment by mshima** [comment]
It’s old.
Maybe it works now.
I have no clue.

**Comment by vishal423** [comment]
Today, I tried against a few old releases back till `4.14` and indeed, it was never supported. I am closing the issue as not implemented.
