### ISSUE TITLE
Disable Hot Reload for Spring Boot

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11388]
##### **Overview of the feature request**
```
mvnw
# on git windows
# server is available on 8080
# change some code in Spring Boot Backend
# some weird errors are visible on git windows console and server is down on 8080


***************************
APPLICATION FAILED TO START
***************************

Description:
...

# restart with 
mvnw
# port 8080/18080 is already in use
```

server is then stuck on git windows and can be stopped on 8080 with a work around via

```
netstat -ano | findstr :8080
# outputting a [PORTID]
taskkill /F /PID [PORTID]
```

by the way, ctrl + C does not work on git windows to stop the server `mvnw`

##### **Related issues or PR**

- does not happen on Mac

- may have to do with https://github.com/jhipster/generator-jhipster/issues/1423

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
I don't think this is related to Spring Boot but rather the port being used by another process. From my experience this does happen from time to time on Windows and less so often on Linux. What you did by using `taskkill /F /PID <portid>` is to forcefully kill the task running on that port. 

I believe this has nothing to do with JHipster and the error message `port 8080/18080 is already in use` clearly identifies and points to the problem. Therefore I am closing this issue. 😄

**Comment by geyuqiu** [comment]
@SudharakaP actually mvnw is running on 8080 (error message shows some weird ports: 18080)

**Comment by SudharakaP** [comment]
I think it says either 8080 or 18080 is blocked. Here's a reference of all the ports that needs to be available (depending on your project configuration) for JHipster; https://www.jhipster.tech/common-ports/
