### ISSUE TITLE
Generate jHipster apps from inside Eclipe, IntelliJ IDEA, etc

### ISSUE THREAD

**Issue by distributev** [jhipster/generator-jhipster#11387]
##### **Overview of the feature request**

Generate jHipster apps from inside Eclipe, IntelliJ IDEA, etc

##### **Motivation for or Use Case**

People are using Eclipe, IntelliJ IDEA for writing their Java code. It would be nice to give the option to generate jHipster apps from inside Eclipe, IntelliJ IDEA, etc.

Spring Initializr Documentation shows how this can be achieved.

https://docs.spring.io/initializr/docs/current/reference/html/

Netflix Built a Spring Application Generator to Boost Dev Productivity. Here's How You Can, Too.

https://spring.io/blog/2020/02/24/netflix-built-a-spring-application-generator-to-boost-dev-productivity-here-s-how-you-can-too

##### **Related issues or PR**

I did not find a similar issue.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
As a java library, Spring Initializr can be more easily integrated into java IDEs than JHipster which is written in NodejS. Still, it requires 31 classes for the IntelliJ plugin.

**Comment by MathieuAA** [comment]
@colameo I'm wondering if you know of a way to do it

**Comment by mraible** [comment]
I've added a large bounty on this one because I don't think it's easy but it would be nice to have. If JHipster Online offered an API like start.spring.io does, it'd be a lot easier. For example, here's how you can create a Spring Boot app with Kotlin and Gradle, among other features.

```
http https://start.spring.io/starter.zip javaVersion==11 language==kotlin \ 
 artifactId==notes-api groupId==com.okta.developer packageName==com.okta.developer.notes \ 
type==gradle-project dependencies==h2,data-jpa,data-rest,okta,web -d
```

**Comment by gmarziou** [comment]
Generating an app in start.spring.io is a one shot action.
In JHipster you still have to add entities, it's the start of a process.

How often do normal users (not JHipster team) generate an app versus how often do they enrich it?

**Comment by pascalgrimaud** [comment]
it's indeed a lot of work but I'm not sure it is worth...
The end user can still use 'cli', or jhipster online. And it is probably same time than using directly IDE.
So for me, it's better to focus on bug or other feature.

**Comment by pascalgrimaud** [comment]
So I'm closing this as there are many ways to generate a project:
- installing everything and using CLI: `jhipster`
- installing Docker image and using CLI inside Docker container
- using our DevBox
- using JDL
- using jhipster-online

So I don't think implementing this inside IDE would be a gain... maybe few seconds for days of work
That's why I'm closing this.
