### ISSUE TITLE
Migrate Daily Builds to GitHub Actions

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#11391]
This project is important for the quality of generator-jhipster
https://github.com/hipster-labs/jhipster-daily-builds

It is not in the main organization to not share the builds.

To be consistent with the main organization, it's time for migrate to GitHub Actions.
There are a lot of work to achieve this, I think.

As I don't have time, I open a ticket here with a bounty.

Here all the tasks:

- [x] migrate JDL Microservices
- [x] add badge for JDL Microservices in README
- [x] migrate apps (Angular, React, Maven, Gradle, etc)
- [x] add badge for apps in README
- [x] work on schedulers as each run can contain 20 builds
- [x] remove all Travis names / packages / build
- [x] wait 1 week and if it works fine, remove Azure yaml file
- [x] then, remove Azure configuration
- [x] copy the badges from jhipster-daily-builds to README of main generator-jhipster

**Comment by pascalgrimaud** [comment]
Maybe you can help @Hawkurane, as you helped me a lot for the Azure Pipelines in the past ?

**Comment by Hawkurane** [comment]
Hello, sure !
I will start by doing the JDL Microservices part so we can have a first version of the yamls

**Comment by pascalgrimaud** [comment]
I'm updating the original ticket to put all required tasks

**Comment by pascalgrimaud** [comment]
It starts to work well.
See the README at https://github.com/hipster-labs/jhipster-daily-builds

**Comment by pascalgrimaud** [comment]
About scheduler:
- all default apps builds are launched between 0am UTC and 5am UTC
- Neo4j builds are in a specific file (see [Neo4j.yaml](https://github.com/hipster-labs/jhipster-daily-builds/blob/master/.github/workflows/neo4j.yaml)) as integration tests failed (cc @atomfrede)
- all JDL Microservices builds are launched between 5am UTC and 9am UTC

**Comment by Hawkurane** [comment]
By the way, we should change the badges on the readme on the main project's github

**Comment by pascalgrimaud** [comment]
@Hawkurane : yes it's mentionned in the list of items:
`copy the badges from jhipster-daily-builds to README of main generator-jhipster`

**Comment by pascalgrimaud** [comment]
closing this as we finished everything

**Comment by pascalgrimaud** [comment]
Half of the bounty claimed: https://opencollective.com/generator-jhipster/expenses/15305

**Comment by Hawkurane** [comment]
Half of the bounty claimed: https://opencollective.com/generator-jhipster/expenses/15313
as well

**Comment by pascalgrimaud** [comment]
@Hawkurane : approved
