### ISSUE TITLE
Unable to parse command line options: Unrecognized option: -npt

### ISSUE THREAD

**Issue by ajoysinhactc** [jhipster/generator-jhipster#11399]
I am trying to build jhipster spring-boot microservice using jenkins .. but maven clean failed with following error . jenkins file generated using jhipster ci cd command

Code failed 

> stage('clean') {
>             sh "./mvnw -ntp clean"
>  }

Error Displayed 

> Unable to parse command line options: Unrecognized option: -npt

Following is the environment details :

Java version : 11
Maven version : 3.6.0
OS : Ubuntu

**Comment by atomfrede** [comment]
There seems to be something wrong. You snipped says `ntp`, which is correct. But the error `npt` which is wrong. Did you paste the complete generad ci config?

**Comment by pmverma** [comment]
@ajoysinhactc `-ntp` option is available with maven version `3.6.1` and was added in #10291 
Not sure why are you getting this error.

Please follow the issue template to provide more information which are necessary.

**Comment by ajoysinhactc** [comment]
Thanks .. I was getting the error due to old maven wrapper .. after updating the maven wrapper it is executing fine ..

**Comment by Pratiknavalgi** [comment]
Unable to parse command line options: Unrecognized option: --debug--errors

usage: mvn [options] [<goal(s)>] [<phase(s)>]

**Comment by Pratiknavalgi** [comment]
i got this error
anyone ehose know why this error.
Unable to parse command line options: Unrecognized option: --debug--errors

usage: mvn [options] [<goal(s)>] [<phase(s)>]
