### ISSUE TITLE
Make dev and prod equal on spring.jpa.properties

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#11396]
These settings have been added to application-prod.yml:

      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true

I would like these to be in application-dev.yml as well to make sure errors appear in my dev already and not in production.

Could be there is a specific reason why this was only done in prod if so I would like to know.

As a side note: fail_on_pagination_over_collection_fetch: true will not work together with @EntityGraph. Can I just remove these?

**Comment by pmverma** [comment]
@tibistibi Basically these optimizations (#10667 ) was added to `-prod.yml` because dev and prod databases might not be the same.
And I did focus mainly for production.

However, I just realize that if both the dev and prod databases are same then better it should be in `application.yml`, WDYT?

As these optimizations are just suggestions of https://github.com/vladmihalcea/hypersistence-optimizer, it is up to users to do some necessary work.

**Comment by tibistibi** [comment]
@pmverma yes i think moving it to applicatoin.yml is better. Than we know both are equal. I made a PR can you check if I did it correctly?

**Comment by tibistibi** [comment]
#11414

**Comment by tibistibi** [comment]
@pmverma somehow a test failed not sure if it is because of the change I made. Can you look at it?

**Comment by pmverma** [comment]
@tibistibi,

> However, I just realize that if both the dev and prod databases are same then better it should be in application.yml, WDYT?

Since you have moved all those options to application.yml file without a filter for H2, I hope no-complain message from hypersistence as it has not been tested again.

Anyway, it is fine as we do not use H2 in production.

**Comment by tibistibi** [comment]
ah and you say in prod file there was no H2 check because there is none but for dev there could be an H2 check.
If that gives a problem we should move it to prod and dev and add the checks there

**Comment by pmverma** [comment]
Lets keep it as it is because IMO user should not be using H2 either for dev apart from some testing.
