### ISSUE TITLE
Elasticsearch doesn't integrate with faker.js

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#11400]
##### **Overview of the issue**

If you create an app with Elasticsearch, you'll be surprised when none of the records shown on a list screen are searchable.

##### **Motivation for or Use Case**

As a user, I expect to be able to search the data that I see.

##### **Reproduce the error**

Create a new app with the following JDL:

```
application {
 config {
   baseName notes
   authenticationType oauth2
   buildTool gradle
   searchEngine elasticsearch
   testFrameworks [protractor]
 }
 entities *
}
entity Note {
 title String required
 text TextBlob
}
relationship ManyToOne {
 Note{user(login)} to User
}
paginate Note with pagination
```

Start the app, login, navigate to the list screen and you'll see you aren't able to search/find any of the existing records.

```
docker-compose -f src/main/docker/keycloak.yml up -d
docker-compose -f src/main/docker/elasticsearch.yml up -d
./gradlew
```

However, if you add a new record, it is searchable.

##### **Suggest a Fix**

When faker is enabled, populate Elasticsearch's index on startup.

##### **JHipster Version(s)**

```
notes@0.0.1-SNAPSHOT /Users/mraible/easy-notes
├── generator-jhipster@6.6.0
└─┬ generator-jhipster-kotlin@1.4.0
  └── generator-jhipster@6.6.0  deduped

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "baseName": "notes",
    "authenticationType": "oauth2",
    "buildTool": "gradle",
    "jhipsterVersion": "6.6.0",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "serverPort": "8080",
    "useSass": true,
    "creationTimestamp": 1582817580460,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.4.0"
      }
    ],
    "blueprints": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.4.0"
      }
    ]
  },
  "entities": ["Note"],
  "generator-jhipster-kotlin": {
    "jhipsterVersion": "6.6.0",
    "applicationType": "monolith",
    "baseName": "notes",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "embeddableLaunchScript": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Note {
  title String required,
  text TextBlob
}
relationship ManyToOne {
  Note{user(login)} to User
}

paginate Note with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

git version 2.21.1 (Apple Git-122.3)

node: v12.13.0

npm: 6.13.7

yeoman: 3.1.1

yarn: 1.22.0

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

**Comment by SudharakaP** [comment]
I think this has already been reported at #11321; except that issue is specific to React, but seems the issue exists on Angular side as well. I am currently working on that. 😄

**Comment by pascalgrimaud** [comment]
I'm changing this to "feature" as for me, it's not a bug.

We have this, since long time, because inserting Data using liquibase, don't change anything for Elasticsearch : the data is not indexed. Same for MongoDB. So this is not related to Faker.js directly.

That's why the best would be to use something similar to the module : https://github.com/geraldhumphries/generator-jhipster-elasticsearch-reindexer

But I don't know how it can be achieved...

**Comment by mraible** [comment]
I'll close this issue. It's not a big deal.

**Comment by hepaestus** [comment]
I am having issues with JH and Elasticsearch as well. Opened another ticket #16136 https://github.com/jhipster/generator-jhipster/issues/16136
