### ISSUE TITLE
Responsive UI

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11407]
##### **Overview of the feature request**

not only for logs https://github.com/jhipster/generator-jhipster/issues/3276
Was this fix merged / working btw.?

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
Yes, this is fixed and merged at #3282 and if you carefully follow that issue thread you'll see the pull request is linked below [this comment](https://github.com/jhipster/generator-jhipster/issues/3276#issuecomment-202772697).
