### ISSUE TITLE
@PreAuthorize @PostAuthorize @Secured not working

### ISSUE THREAD

**Issue by zackfei** [jhipster/generator-jhipster#11401]
##### **Overview of the issue**
1. perform `jhipster upgrade` from 6.6.0 to `6.7.1` for jhipster UAA
2. `@PreAuthorize`, `@PostAuthorize`, `@Secured` is not work anymore, espcially `UserResource.java`

This file `MethodSecurityConfiguration.java` was deleted during upgrade.
This happen when upgrade other microservice application also.

##### **JHipster Version(s)**

$ jhipster info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
uaa@0.0.0 /home/kent/workspaces/jhipster/microservice/uaa
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.uaa",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "io.uaa",
    "packageFolder": "io/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "testFrameworks": ["gatling"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": ["en", "zh-cn", "zh-tw"],
    "blueprints": [],
    "skipClient": true,
    "creationTimestamp": 1577936444933
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 1.8.3.1

node: v10.18.1

npm: 6.13.4

yeoman: 2.0.6

yarn: 1.21.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.16.1, build 6d1ac21

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
@zackfei please respect guidelines and paste output of `jhipster info` so that we know your full project configuration.

**Comment by mraible** [comment]
Does this happen if you create a brand new app with 6.7.1?

**Comment by zackfei** [comment]
> 
> 
> Does this happen if you create a brand new app with 6.7.1?

I try to create a brand new jhipster UAA, but `MethodSecurityConfiguration` didn't generated out. 
The key annotation `@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)` is missing.
Anyway, create a brand new app is not the approach I want because by doing so I will lost those changes that I add on top in the app

**Comment by pascalgrimaud** [comment]
FYI.

This file was added by @xetys here https://github.com/jhipster/generator-jhipster/pull/10845/files

But it has been removed by @mraible at https://github.com/jhipster/generator-jhipster/commit/2e448adb31bbc063d1f5ee98e110892c73695e8b#diff-d702dc7debe242a567b1c79be70e1621

**Comment by xetys** [comment]
I see...is there any reason for this @mraible ?

**Comment by mshima** [comment]
> But it has been removed by @mraible at [2e448ad#diff-d702dc7debe242a567b1c79be70e1621](https://github.com/jhipster/generator-jhipster/commit/2e448adb31bbc063d1f5ee98e110892c73695e8b#diff-d702dc7debe242a567b1c79be70e1621)

I missed the removed file cleanup in this PR.
The annotation probably should be added here:
https://github.com/jhipster/generator-jhipster/blob/2e448adb31bbc063d1f5ee98e110892c73695e8b/generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs#L389

**Comment by mraible** [comment]
I removed it because it didn't seem to be needed for OAuth since you can use Spring EL in Spring Security's latest OAuth support. I forgot UAA is still using Spring Security's legacy OAuth support.

**Comment by xetys** [comment]
I was adding this to enable 

``` java
@PreAuthorize('#oauth.hasScope(...)')
```

Hint: I know it is deprecated, but currently this is the way how spring-security-oauth offers it, and I am still waiting what the Spring team is deciding about maintaining authorization server: https://github.com/spring-projects/spring-security/issues/6320

**Comment by pascalgrimaud** [comment]
So I think we can add it back, only for UAA options ?

**Comment by xetys** [comment]
yep... I'll open a PR for this
