### ISSUE TITLE
Add entity unit and e2e tests in Ionic for JHipster

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#11406]
##### **Overview of the feature request**

The Ionic for JHipster module (aka, Ionic4J) does not currently generate unit or e2e tests with its entity generator. Since Ionic4J's entity generator extends from JHipster, it shouldn't be too hard to create templates for unit and e2e tests. 

See https://github.com/oktadeveloper/generator-jhipster-ionic/issues/170 for the issue in the Ionic4J project.

##### **Motivation for or Use Case**

I'm opening this as an issue on the JHipster project so I can assign a bug bounty to it and hopefully accelerate its development.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by amanganiello90** [comment]
@mraible , if it is not a problem, I can work on this.

**Comment by mraible** [comment]
Please do! 👍

**Comment by amanganiello90** [comment]
ok. I will start on [feature/entity-tests branch](https://github.com/amanganiello90/generator-jhipster-ionic/tree/feature/entity-tests)

**Comment by mraible** [comment]
Fixed thanks to @amanganiello90! 👊

**Comment by amanganiello90** [comment]
$200 bug bounty claim for https://opencollective.com/generator-jhipster/expenses/15270

**Comment by pascalgrimaud** [comment]
@amanganiello90 : just approuved

**Comment by amanganiello90** [comment]
> 
> 
> @amanganiello90 : just approuved

Thanks!
