### ISSUE TITLE
Update entity generator to support reactive applications

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#11404]
##### **Overview of the feature request**

One of the last remaining items to move our Reactive/WebFlux support (https://github.com/jhipster/generator-jhipster/issues/7608) to beta is to update the entity generator and its tests.

- [ ] Entities with service
- [ ] Entities without service
- [ ] Entities tests with `WebTestClient`

##### **Motivation for or Use Case**

I'm opening these tasks as a new issue so we can assign a bug bounty to it and hopefully accelerate its development. Selfishly, I'd like to demo our WebFlux support with microservices in March.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@pascalgrimaud I created a "reactive" label, but then realized maybe it should be named "theme: reactive"?

**Comment by pascalgrimaud** [comment]
yes, `theme: reactive` is better to keep consistency. I'm surprised that it didn't exist yet

**Comment by murdos** [comment]
FYI, unless someone else is already working on it, I'll try to handle this task.

**Comment by cbornet** [comment]
I'm not sure you can assign the work to yourself if there's a bounty on it :smiley: . Anyway please go ahead. I at least won't try to compete on this.

**Comment by murdos** [comment]
@cbornet : I'm just trying to avoid duplicated effort, and thus announcing that I'm currently working on it (https://github.com/murdos/generator-jhipster/tree/reactive-entity-server). I'll open a draft when I got a full use case complete (e.g. entity without service)

**Comment by cbornet** [comment]
BTW I've started working on SQL/R2DBC support. For the entity gen you can maybe ignore SQL for now.

**Comment by mraible** [comment]
@murdos Are you still planning to add support for Elasticsearch? Also, did you get the bounty for this?

**Comment by murdos** [comment]
> Are you still planning to add support for Elasticsearch? 

Yes. I got something working at last. I need to report the changes to the templates, you should have a PR during the week to come.

> Also, did you get the bounty for this?

Not yet.

Regarding r2dbc entity support, I'm inclined to wait the availability of https://github.com/spring-projects/spring-data-r2dbc/issues/282 in a milestone before really starting, it should really ease the work (and also simplify the existing User and PersistenceAuditEvent r2dbc repositories). 

Also I noted that R2DBC support has been added in Spring Boot 2.3 M3, so the experimental spring boot starter is now deprecated (or at least not updated it seems) and there are some breaking changes that we'll need to handle.
