### ISSUE TITLE
Upgrade the KHipster CLI to support JHipster v6.7.1

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#11412]
Refer https://github.com/jhipster/jhipster-kotlin/pull/217

**Comment by mraible** [comment]
This is a lot of work! Thanks for doing it @sendilkumarn. I assigned a $200 bounty to it.

**Comment by pascalgrimaud** [comment]
The description is not enough to someone who would like to start to work on this ticket.
Can you explain more @sendilkumarn plz ?

**Comment by sendilkumarn** [comment]
Actually the work is done. This is just a bounty PR. :) I will close this :)
