### ISSUE TITLE
extend nohttp checkstyle

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11422]
##### **Overview of the feature request**

either [sun](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/sun_checks.xml) or [google](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)

##### **Motivation for or Use Case**

static analysis

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
We use sonar for static analysis so I don't think we will support multiple tools for static code analysis.

**Comment by SudharakaP** [comment]
I think we can close this issue as we already support Sonar. Feel free to reopen if anyone thinks otherwise. :smile:
