### ISSUE TITLE
Automatize Release detail

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#11427]
##### **Overview of the feature request**

Detail the release content automatically based on the milestone list.

New GitHub action has been created for this purpose: https://github.com/radcortez/milestone-release-action

CC @pascalgrimaud 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
The project is very recent.
Do you have a look at https://github.com/jhipster/jhipster-vuejs/issues/507 opened by @atomfrede ?
I'd prefer this project, which has more stars:
- https://github.com/apps/release-drafter
- https://github.com/release-drafter/release-drafter

I'm closing this, I'd prefer to give a try on Vue.js blueprint and if it's a success, we can try in the main generator
Hope you're ok @DanielFran
