### ISSUE TITLE
ExceptionTranslatorIT Failed Test on Clean Generation

### ISSUE THREAD

**Issue by cah-rob-snider** [jhipster/generator-jhipster#11431]
##### **Overview of the issue**

I performed a clean generation and, when running `gradlew clean test integrationTest`, these two tests fail:

```
ExceptionTranslatorIT > testMethodNotSupported() FAILED
    java.lang.AssertionError at ExceptionTranslatorIT.java:87

ExceptionTranslatorIT > testMethodArgumentNotValid() FAILED
    java.lang.AssertionError at ExceptionTranslatorIT.java:41
```

##### **Motivation for or Use Case**

I am unable to start a new project with test cases failing out of the box.

##### **Reproduce the error**

1. run `npm install -g generator-jhipster@6.7.1`
2. run `jhipster` with the below .`yo-rc.json`
3. run `gradlew clean test integrationTest`

##### **Suggest a Fix**

I believe this commit is what is causing the issues:
fd4e8427d0495ba640abea70632b1f50ff5d3621

`generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs`
Reverting lines 69-85 fixes it

##### **JHipster Version(s)**

6.7.1

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT C:\Users\rob.snider\Documents\GitHub\jhipster-test
`-- generator-jhipster@6.7.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1583268398191,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.21.0.windows.1

node: v10.16.3

npm: 6.12.0

yeoman: 2.0.5

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

##### **Browsers and Operating System**

Windows 7 and 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Do you use the exact version of generator-jhipster@6.7.1 or do you use master branch ?
I tested your config with exact 6.7.1, and didn't manage to reproduce:

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 12s
11 actionable tasks: 10 executed, 1 up-to-date
```

**Comment by cah-rob-snider** [comment]
I am not using master.

I pushed the generated code to https://github.com/cah-rob-snider/jhipster-test

**Comment by pascalgrimaud** [comment]
@cah-rob-snider : can you tell me how did you generate your project ? With JHipster Online ? With JDL ? With Command Line ?

- I cloned your project and I confirm the issue
- But I regenerated the project and found some difference:

```diff
diff --git a/src/test/java/com/mycompany/myapp/web/rest/UserResourceIT.java b/src/test/java/com/mycompany/myapp/web/rest/UserResourceIT.java
index 191c96a..75072e3 100644
--- a/src/test/java/com/mycompany/myapp/web/rest/UserResourceIT.java
+++ b/src/test/java/com/mycompany/myapp/web/rest/UserResourceIT.java
@@ -27,6 +27,7 @@ import java.util.function.Consumer;
 import static org.assertj.core.api.Assertions.assertThat;
 import static org.hamcrest.Matchers.hasItems;
 import static org.hamcrest.Matchers.hasItem;
+import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
 import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
 import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
 
diff --git a/src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorIT.java b/src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorIT.java
index afff6b8..d9ab2c8 100644
--- a/src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorIT.java
+++ b/src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorIT.java
@@ -10,6 +10,7 @@ import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMock
 import org.springframework.http.MediaType;
 import org.springframework.test.web.servlet.MockMvc;
 
+import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
 import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
 import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
 import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
@@ -29,7 +30,7 @@ public class ExceptionTranslatorIT {
 
     @Test
     public void testConcurrencyFailure() throws Exception {
-        mockMvc.perform(get("/api/exception-translator-test/concurrency-failure"))
+        mockMvc.perform(get("/api/exception-translator-test/concurrency-failure").with(csrf()))
             .andExpect(status().isConflict())
             .andExpect(content().contentType(MediaType.APPLICATION_PROBLEM_JSON))
             .andExpect(jsonPath("$.message").value(ErrorConstants.ERR_CONCURRENCY_FAILURE));
@@ -37,7 +38,7 @@ public class ExceptionTranslatorIT {
 
     @Test
     public void testMethodArgumentNotValid() throws Exception {
-         mockMvc.perform(post("/api/exception-translator-test/method-argument").content("{}").contentType(MediaType.APPLICATION_JSON))
+         mockMvc.perform(post("/api/exception-translator-test/method-argument").content("{}").contentType(MediaType.APPLICATION_JSON).with(csrf()))
              .andExpect(status().isBadRequest())
              .andExpect(content().contentType(MediaType.APPLICATION_PROBLEM_JSON))
              .andExpect(jsonPath("$.message").value(ErrorConstants.ERR_VALIDATION))
@@ -48,7 +49,7 @@ public class ExceptionTranslatorIT {
 
     @Test
     public void testMissingServletRequestPartException() throws Exception {
-        mockMvc.perform(get("/api/exception-translator-test/missing-servlet-request-part"))
+        mockMvc.perform(get("/api/exception-translator-test/missing-servlet-request-part").with(csrf()))
             .andExpect(status().isBadRequest())
             .andExpect(content().contentType(MediaType.APPLICATION_PROBLEM_JSON))
             .andExpect(jsonPath("$.message").value("error.http.400"));
@@ -56,7 +57,7 @@ public class ExceptionTranslatorIT {
 
     @Test
     public void testMissingServletRequestParameterException() throws Exception {
-        mockMvc.perform(get("/api/exception-translator-test/missing-servlet-request-parameter"))
+        mockMvc.perform(get("/api/exception-translator-test/missing-servlet-request-parameter").with(csrf()))
             .andExpect(status().isBadRequest())
             .andExpect(content().contentType(MediaType.APPLICATION_PROBLEM_JSON))
             .andExpect(jsonPath("$.message").value("error.http.400"));
@@ -64,7 +65,7 @@ public class ExceptionTranslatorIT {
 
     @Test
     public void testAccessDenied() throws Exception {
-        mockMvc.perform(get("/api/exception-translator-test/access-denied"))
+        mockMvc.perform(get("/api/exception-translator-test/access-denied").with(csrf()))
             .andExpect(status().isForbidden())
             .andExpect(content().contentType(MediaType.APPLICATION_PROBLEM_JSON))
             .andExpect(jsonPath("$.message").value("error.http.403"))
@@ -73,7 +74,7 @@ public class ExceptionTranslatorIT {
 
     @Test
     public void testUnauthorized() throws Exception {
-        mockMvc.perform(get("/api/exception-translator-test/unauthorized"))
+        mockMvc.perform(get("/api/exception-translator-test/unauthorized").with(csrf()))
             .andExpect(status().isUnauthorized())
             .andExpect(content().contentType(MediaType.APPLICATION_PROBLEM_JSON))
             .andExpect(jsonPath("$.message").value("error.http.401"))
@@ -83,7 +84,7 @@ public class ExceptionTranslatorIT {
 
     @Test
     public void testMethodNotSupported() throws Exception {
-        mockMvc.perform(post("/api/exception-translator-test/access-denied"))
+        mockMvc.perform(post("/api/exception-translator-test/access-denied").with(csrf()))
             .andExpect(status().isMethodNotAllowed())
             .andExpect(content().contentType(MediaType.APPLICATION_PROBLEM_JSON))
             .andExpect(jsonPath("$.message").value("error.http.405"))
@@ -92,7 +93,7 @@ public class ExceptionTranslatorIT {
 
     @Test
     public void testExceptionWithResponseStatus() throws Exception {
-        mockMvc.perform(get("/api/exception-translator-test/response-status"))
+        mockMvc.perform(get("/api/exception-translator-test/response-status").with(csrf()))
             .andExpect(status().isBadRequest())
             .andExpect(content().contentType(MediaType.APPLICATION_PROBLEM_JSON))
             .andExpect(jsonPath("$.message").value("error.http.400"))
@@ -101,7 +102,7 @@ public class ExceptionTranslatorIT {
 
     @Test
     public void testInternalServerError() throws Exception {
-        mockMvc.perform(get("/api/exception-translator-test/internal-server-error"))
+        mockMvc.perform(get("/api/exception-translator-test/internal-server-error").with(csrf()))
             .andExpect(status().isInternalServerError())
             .andExpect(content().contentType(MediaType.APPLICATION_PROBLEM_JSON))
             .andExpect(jsonPath("$.message").value("error.http.500"))
```

So when I compare the ExceptionTranslatorIT file from your project with the one from JHipster v6.7.1, it's not the same:
- https://github.com/cah-rob-snider/jhipster-test/blob/master/src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorIT.java
- https://github.com/jhipster/generator-jhipster/blob/v6.7.1/generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs#L78

**Comment by cah-rob-snider** [comment]
I generated it with the command line. My teammate generated a new project with e CLI as well and had the same issue. I'll try doing it online and see what that does.

**Comment by mshima** [comment]
I think this is a synchronization problem.
Related to https://github.com/jhipster/generator-jhipster/issues/10528
Running `jhipster --with-entities` fix the problem?

**Comment by pascalgrimaud** [comment]
Ok, I manage to reproduce with CLI.
To resume:
- when prompting, there is the issue
- when using an existing `.yo-rc.json`, it's ok

So probably something related to this line: https://github.com/jhipster/generator-jhipster/blob/0a1d8a3afc6947dcbf490fb5d35897c174e616e4/generators/server/index.js#L212

**Comment by mshima** [comment]
> Ok, I manage to reproduce with CLI.

If you reproduced with cli, then its confirmed it's related to https://github.com/jhipster/generator-jhipster/issues/10528.
And should be fixed with https://github.com/jhipster/generator-jhipster/pull/10554.

**Comment by pascalgrimaud** [comment]
I found a fix, but not sure it's the correct one.
Can you have a look @mshima plz ?

**Comment by mshima** [comment]
@pascalgrimaud I was a little faster =P.
https://github.com/jhipster/generator-jhipster/pull/11432

**Comment by pascalgrimaud** [comment]
you're too fast, I was going to close my PR, but you already closed yours (again you're faster) !

**Comment by cah-rob-snider** [comment]
Thanks for the speedy fix guys!!
