### ISSUE TITLE
migrate to cypress from protractor

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11440]
##### **Overview of the feature request**

current disadvantages with protractor:

\- async/await for all protractor methods / tests (async await hell, 1 method async/await &rarr; every method async/await)
\- no video capturing out of the box during ui-tests
\- debugging ui-tests on ci only via work arounds: adding source code for taking screen shot (failing tests not reproducible locally on dev)

Advantanges with [cypress](https://www.cypress.io/)
\+ less flaky ui-tests
\+ video capturring out of the box
\+ more comfortable with [test-runner](https://docs.cypress.io/guides/core-concepts/test-runner.html#Overview) etc.

To be cleared
? [open/Beta feature request for supporting Firefox](https://github.com/cypress-io/cypress/issues/1096)
? return-on-invest
? make sense first for jhipster-module

##### **Motivation for or Use Case**

hipster: new frameworks ?

##### **Related issues or PR**

no

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
We already started the discussion for Vue.js
- here the ticket: https://github.com/jhipster/jhipster-vuejs/issues/401
- here a 1st draft of pull request: https://github.com/jhipster/jhipster-vuejs/pull/399

But to achieve it completely, it's a lot of work, so not sure we'll be done in the next months.

@geyuqiu : maybe you don't know, but we all work on JHipster during our free and personal time, the evening or the week-end. We are not paid for what we do. It's not our main Job.
So it's hard to code all feature requests or enhancement without help. So if you suggest something, be ready to take the lead and start to contribute to the project.

**Comment by wmarques** [comment]
@geyuqiu I don't understand the "async/await" hell. For me it's not a big issue.
But as @pascalgrimaud said, let's keep one ticket for this in Vue.js, everything is in there.
