### ISSUE TITLE
Ajax Failure and Success Handlers not firing 

### ISSUE THREAD

**Issue by gthiet** [jhipster/generator-jhipster#1144]
The AjaxSuccessHandler and AjaxFailureHandler's under the OAuth and token authentication strategies never trigger. They fire under the session authentication strategy.

**Comment by jdubois** [comment]
Yes they are only configured in the "session" strategy, so this is perfectly normal.
Is your issue just that you have those 2 files for nothing? I'm going to remove them and close this PR with the commit.
