### ISSUE TITLE
Pagination not working on history back/forward

### ISSUE THREAD

**Issue by HJK181** [jhipster/generator-jhipster#11455]
##### **Overview of the issue**

Pagination of entity in React frontend does not work when using history back/forward, e.g. mouse back button.

##### **Reproduce the error**

Create a simple entity with pagination. Go to page > 1 by using the pagination component and try to navigate back and forth by using the mouse buttons.

##### **JHipster configuration**
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway-react@0.0.1-SNAPSHOT C:\gatewayReact
`-- generator-jhipster@6.7.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.foo",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "6.7.0",
    "applicationType": "gateway",
    "baseName": "gatewayReact",
    "packageName": "de.foo",
    "packageFolder": "de/foo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "secret",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "materia",
    "clientThemeVariant": "light",
    "creationTimestamp": 1581489638260,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": ["de", "en"],
    "blueprints": []
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)

git version 2.15.0.windows.1

node: v12.4.0

npm: 6.9.0

yeoman: 3.1.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

##### **Browsers and Operating System**

Windows/Chrome, should be Browser independent.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@HJK181 : can you use `jhipster info` too plz ? so we have your node, npm version etc... just to be sure it doesn't come from it

**Comment by HJK181** [comment]
@pascalgrimaud Updated the description, sry for the missing part.

**Comment by ruddell** [comment]
This also affects the Angular client. Going forward or back in history does not update the entity table data, even though the query params are updated.

**Comment by HJK181** [comment]
I've tried/noticed multiple thing:
1. Use `props.history.listen` to get notified about location changes. This does not seam to work as the listener get's triggered several times for a single history back/forward. I'm new to React but I think this might be related to nesting multiple `switch` in nested components?! 
2. Use `useLocation` from `react-router-dom`, here the `effect` runs only once for a history back/forward, but I have the problem that my components get's mounted/unmounted on every history change. As far as I read, this should not happen when using `switch` of `react-router-dom` but again, I'm to inexperienced yet to tell more.
3. What I also noticed is that as soon as I use history back, were the URL changes correctly (the components just doesn't update it's state), the Browser does not offer the possibility to user history forward. Don't know whats happening here.

**Comment by qmonmert** [comment]
@HJK181 @ruddell @pascalgrimaud I fixed all the issues in my PR #11518 

@chrisdns can you look my PR ? 🙂

**Comment by HJK181** [comment]
Hi @qmonmert thank you very much, hope the PR get's reviewed and merged soon :) 
if it’s not too much to ask if you can have a look at my stackoverflow question https://stackoverflow.com/questions/60826454/jhipster-react-router-render-called-multiple-times
I would be very grateful. i'n not sure if this is also a bug in the generator. And please excuse me I'm pretty new to react and jhispter.

**Comment by qmonmert** [comment]
@HJK181 I looked your stackoverflow question, it's difficult to see where is the problem but I think the problem is in your react code (maybe hooks or reducer) and not in the generator JH

**Comment by HJK181** [comment]
@qmonmert thanks for having a look. Basically I just described the code Jhipster is generating for those not familiar with Jhipster. It should be reproducible for every React based app with an entity. Just  visit the detail page of an entity and see it's render method called several times.

**Comment by qmonmert** [comment]
@HJK181 it's not a bug, it's just like React works

**Comment by HJK181** [comment]
From what I've read this shouldn't be the case. As I pointed out in the question, the render method should not be called, maybe someone else can also check the question, @chrisdns ?

**Comment by qmonmert** [comment]
@pascalgrimaud I claim my money 😄 https://opencollective.com/generator-jhipster/expenses/15564

**Comment by pascalgrimaud** [comment]
@qmonmert : approuved !
