### ISSUE TITLE
Any gains by incorporating principles from nx.dev within JHipster?

### ISSUE THREAD

**Issue by distributev** [jhipster/generator-jhipster#11451]
##### **Motivation for or Use Case**

https://nx.dev/angular CLI adds good value for Angular developers to split a big product into individual sub-projects 

There are also

https://nx.dev/react and 
https://nx.dev/web (for Web Components)

I believe https://nx.dev should be evaluated if it fits well with the jhipster architecture.

Monorepo != Monolith which means Monorepo should  not be confused with Monolith

Further reading 
 
Tactical Domain-Driven Design with Angular and Monorepos?

https://www.softwarearchitekt.at/aktuelles/tactical-domain-driven-design-with-monorepos/

Sustainable Angular Architectures

https://www.softwarearchitekt.at/aktuelles/sustainable-angular-architectures-2/

##### **Related issues or PR**

I did not find a similar request.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
Thanks for suggesting this.

We are already moving to Angular CLI and for me, it's ok for our needs.
For now a basic JHipster app is one front and one or more backends, it depends if you do microservices or not.
So right now I don't really see the point of integrating a monorepo solution into JHipster. Moving to Angular CLI looks enough for me.

**Comment by pascalgrimaud** [comment]
Thanks for your proposition.
But, as said by @wmarques, Angular CLI looks enough for our needs and as we already have too much options, we can't support everything.
Don't hesitate to discuss if you think it's a must have, show code on GitHub, start a module etc.

That's why I'm closing this.

**Comment by gmarziou** [comment]
@distributev I have used Nx to start a new project 2 months ago because I liked their ideas but 3 weeks later I gave up and went back to angular  CLI. because when something does not work and you are not enough experienced in this tool it's hard to find what's wrong.

Also, I did not foresee a need for Nx monorepo for my project, with Angular CLI I can still have several applications and shared libs easily with an angular [workspace](https://angular.io/guide/glossary#workspace) in same repo. As I don't plan to mix Angular and React, I don't see a clear benefit to Nx.

**Comment by khalilou88** [comment]
Hi guys, since you are working on a "New sub generators for modularity", maybe you could write it on top of nx?

**Comment by mraible** [comment]
How would you compare this with microfrontends? Can it be added as a module or blueprint instead?

**Comment by khalilou88** [comment]
unfortunately I think you need to rewrite jhipster and drop yeoman to use nx generators.
I am only suggesting, its a lot of work to do.
I recently created a nx plugin to add support of gradle multi project build and spring boot to a nx worspace.
I think what I did is like what you want to do with yeoman.
You can have an idea about my plugin here (I am still working on it) :
https://dev.to/gridou/how-to-add-spring-boot-and-gradle-multi-project-builds-capabilities-to-your-nx-workspace-53cd
here a video, how to create a nx plugin :
https://www.youtube.com/watch?v=fC1-4fAZDP4&t=5s

**Comment by khalilou88** [comment]
I think the author of this issue was speaking about nx for both frontend and backend so my comment was not referring to microfrontends or frontends framework but for a polyglot workspace. I think I will be  good for hipster since you have support for many techno.
