### ISSUE TITLE
Documentation via arc42 especially for building block view

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11469]
##### **Overview of the feature request**
Have we had a discussion regarding documenting jHipster via arc42 templates, e.g. : 
[arc24 building block view](https://docs.arc42.org/section-5/)  for Users, Authorities etc. 

Graphics can be vcs-ed in plantuml :) 

##### **Motivation for or Use Case**

This view can reveal how generated Angular / Spring Boot, Monolith / Microservices app would look like

##### Has a similar feature request been asked for before? Please search both closed & open issues 
no?
Should it go to the jhipster.tech website?

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
@geyuqiu Do you have a sample application with this set up ? So that we can evaluate if this is valuable perhaps as an option or external module.

**Comment by atomfrede** [comment]
You can find some examples here https://arc42.org/examples

I liked this one https://biking.michael-simons.eu/docs/index.html. I would put that into a module/blueprint imho.

**Comment by pascalgrimaud** [comment]
no answer for the original author
so lack of interest for this, that's why I'm closing this
