### ISSUE TITLE
generating an application with reactive spring webflux and cassandra error

### ISSUE THREAD

**Issue by nimotli** [jhipster/generator-jhipster#11460]
##### **Overview of the issue**
After i generated a Jhipster application with the option reactive and cassandra I get an error in web.rest.UserJWTController because it tries to import a service that doesn't exist (AuditEventService). 
i tried with other options and it gets created, the only combo where it doesnt work is Cassandra-Reactive

##### **Motivation for or Use Case**
Trying to start a new webflux/cassandra project

##### **Reproduce the error**
generate a jhipster app with reactive spring webflux and cassandra, you'll notice a compilation error and some missing classes

##### **JHipster Version(s)**
v6.8.0

##### **JHipster configuration**
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
yorcspace@0.0.1-SNAPSHOT C:\Users\pc\projects\yorc.space
`-- generator-jhipster@6.8.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "yorc.space",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "yorcspace",
    "packageName": "yorc.space",
    "packageFolder": "yorc/space",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1583851345791,
    "testFrameworks": ["gatling"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "ar-ly", "nl", "fr", "de", "it", "ja", "ru"],
    "blueprints": [],
    "reactive": true
  }
}

</pre>
</details>
##### **Browsers and Operating System**

Google chrome
Windows 10
-   [check ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
If you remove the import, does it compile? If you have time, a pull request to fix this would be great!

**Comment by nimotli** [comment]
> If you remove the import, does it compile? If you have time, a pull request to fix this would be great!

No it doesn't, its needed for other stuff.
I will try to fix it, if I'm successful I'll send a pull request.

**Comment by geyuqiu** [comment]
@mraible correct me if I am wrong, current Audit functionality is used to

- register/log authentication_success / authentication_failuree
- enable further integration of [entity-audit](https://github.com/hipster-labs/generator-jhipster-entity-audit)
