### ISSUE TITLE
Jhipster upgrade delete home directory data

### ISSUE THREAD

**Issue by fresnault** [jhipster/generator-jhipster#11465]
Hello everyone,

First of all, thank you for your participation in this beautiful project that I have been following for several years.

##### **Overview of the issue**

Jhipster upgrade generator try to cleanup current repository. If there is a symbolic link ~ inside the jhipster application, uprade generator will delete home directory without warning.

##### **Motivation for or Use Case**

It would be better to add a check to prevent this from happening. It happened to me earlier and i lost a lot of documents...

##### **Reproduce the error**

**/!\ I advise you not to reproduce the bug**

Add a symbolic link in your jhipster folder, like "~ -> ../some-data/". In my case, the link was created when I add an appender in logstash configuration to try to log in my home directory.

```MacBook:backend fesnault$ jhipster upgrade
INFO! Using JHipster version installed globally
INFO! Executing jhipster:upgrade
INFO! Options: from-cli: true
Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
No blueprints detected, skipping check of last blueprint version
Looking for latest generator-jhipster version...
Looking for latest generator-jhipster version...
6.8.0
✔ New generator-jhipster version found: 6.8.0
     info git rev-parse -q --is-inside-work-tree
true
✔ Git repository detected
     info git status --porcelain
     info git rev-parse -q --abbrev-ref HEAD
master
     info git rev-parse -q --verify jhipster_upgrade
     info git checkout --orphan jhipster_upgrade
Switched to a new branch 'jhipster_upgrade'
✔ Created branch jhipster_upgrade
     info Removing .editorconfig
     info Removing .gitattributes
     info Removing .gitignore
     info Removing .prettierignore
     info Removing .prettierrc
     info Removing README.md
     info Removing checkstyle.xml
     info Removing jhipster-jdl.jh
     info Removing jhipster-jdl.png
     info Removing mvnw
     info Removing mvnw.cmd
     info Removing package-lock.json
     info Removing package.json
     info Removing pom.xml
     info Removing sonar-project.properties
     info Removing src
     info Removing ~
rm: could not remove directory (code EACCES): /Users/fesnault/Desktop
rm: could not remove directory (code EACCES): /Users/fesnault/Documents
rm: could not remove directory (code EACCES): /Users/fesnault/Downloads
...
```

##### **Suggest a Fix**

I think It would be better to add a check in the cleanup method.
https://github.com/jhipster/generator-jhipster/blob/20d2756317e1f991fc25d37f6f18f4a9ec52d078/generators/upgrade/index.js#L142-L150

##### **Related issues**

old issue : https://github.com/jhipster/generator-jhipster/issues/8117

##### **JHipster Version(s)**

```
MacBook:limmo-backend fesnault$ jhipster --version
INFO! Using JHipster version installed globally
6.7.1
```

##### **JHipster configuration**

INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
limmo@0.0.0 /Users/fesnault/git/limmo-backend
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.fresnault.limmo",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "monolith",
    "baseName": "limmo",
    "packageName": "com.fresnault.limmo",
    "packageFolder": "com/fresnault/limmo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "creationTimestamp": 1583260236823,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "fr",
    "languages": ["fr", "en"],
    "blueprints": [],
    "skipClient": true,
    "aws": {
      "applicationName": "limmo",
      "environmentName": "prod",
      "bucketName": "limmo",
      "instanceType": "t2.micro",
      "awsRegion": "eu-west-3",
      "dbName": "limmo",
      "dbInstanceClass": "db.t2.micro"
    }
  }
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.17.2 (Apple Git-113)

node: v11.5.0

npm: 6.14.1

yeoman: 3.1.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.2, build 698e2846

##### **Browsers and Operating System**

MacOS Sierra 10.13.6 (17G7024)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Do you have a file called ~?

**Comment by fresnault** [comment]
> Do you have a file called ~?

Yes, it's a folder generated by logback in my case. I think the behaviour is the same with symlink.

```
MacBook:limmo-backend fesnault$ ls -al
total 864
drwxr-xr-x  24 fesnault  staff     768 11 mar 20:03 .
drwxr-xr-x   3 fesnault  staff      96 11 mar 20:01 ..
-rw-r--r--   1 fesnault  staff     469 11 mar 20:02 .editorconfig
drwxr-xr-x  12 fesnault  staff     384 11 mar 20:02 .git
-rw-r--r--   1 fesnault  staff    3413 11 mar 20:02 .gitattributes
-rw-r--r--   1 fesnault  staff    1923 11 mar 20:02 .gitignore
drwxr-xr-x   6 fesnault  staff     192 11 mar 20:02 .jhipster
drwxr-xr-x   3 fesnault  staff      96 11 mar 20:02 .mvn
-rw-r--r--   1 fesnault  staff      43 11 mar 20:02 .prettierignore
-rw-r--r--   1 fesnault  staff     174 11 mar 20:02 .prettierrc
-rw-r--r--   1 fesnault  staff    1513 11 mar 20:02 .yo-rc.json
-rw-r--r--   1 fesnault  staff    3732 11 mar 20:02 README.md
-rw-r--r--   1 fesnault  staff     980 11 mar 20:02 checkstyle.xml
-rw-r--r--   1 fesnault  staff     882 11 mar 20:02 jhipster-jdl.jh
-rw-r--r--   1 fesnault  staff   61830 11 mar 20:02 jhipster-jdl.png
-rwxr-xr-x   1 fesnault  staff   10069 11 mar 20:02 mvnw
-rw-r--r--   1 fesnault  staff    6789 11 mar 20:02 mvnw.cmd
-rw-r--r--   1 fesnault  staff  260812 11 mar 20:02 package-lock.json
-rw-r--r--   1 fesnault  staff     343 11 mar 20:02 package.json
-rw-r--r--   1 fesnault  staff   47199 11 mar 20:02 pom.xml
-rw-r--r--   1 fesnault  staff    1756 11 mar 20:02 sonar-project.properties
drwxr-xr-x   4 fesnault  staff     128 11 mar 20:02 src
drwxr-xr-x   7 fesnault  staff     224 11 mar 20:03 target
drwxr-xr-x   3 fesnault  staff      96 11 mar 20:06 ~
```

**Comment by mshima** [comment]
> Yes, it's a folder generated by logback in my case. I think the behaviour is the same with symlink.

Symlink is safe, `rm -rf ~` is problematic.
Or files named `$HOME`, `$PWD`, etc.
