### ISSUE TITLE
Add Regular/Core Contributor Guidelines to CONTRIBUTING.md

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#11471]
##### **Overview of the issue**

As discussed in the following email thread, this is to include some information to the documentation for regular contributors and core team members of the JHipster project. This adds a section called `Regular Contributor Guidelines` to the contribution guide. If you have any further suggestions or things to include please feel free to let me know. :smile: 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/xfrODe_g14U/YSoDESxUAAAJ

cc: @jhipster/developers 

##### **Suggest a Fix**

Please see below PR.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Great
