### ISSUE TITLE
Redis Replication setup (master-slave mode)

### ISSUE THREAD

**Issue by zhx828** [jhipster/generator-jhipster#11474]
##### **Overview of the feature request**
Often time, in the production, the single server setup is not recommended, so we added the Redis Cluster support(https://github.com/jhipster/generator-jhipster/issues/11129). But for small projects, the cluster may not be necessary.

##### **Motivation for or Use Case**
We want to guarantee the cache is still available if one of the nodes is crashed. I modified my project based on v6.6.0 to use single node in dev, and master-slave in production. It's relatively light weight changes, but not sure whether it should be included in the jHipster.

##### **Related issues or PR**
https://github.com/jhipster/generator-jhipster/issues/11129
https://github.com/jhipster/generator-jhipster/issues/9280

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@zhx828 : thanks for opening the discussion, but I don't understand well your suggestion. If I'm correct, you suggest to have another config 'master-slave' in production. We would have 3 configs:
- single node
- master-slave for small project -> new yaml file ?
- cluster

Currently, the single node is applied for dev and prod profile.
The cluster mode is commented in the configuration: the user needs to update the config for that.

**Comment by zhx828** [comment]
@pascalgrimaud Thanks for the quick reply. I haven't tried out the 6.8.0 yet. So probably I should do that before giving more details. But here is what I have so far.

I modified the application yaml to specify which type of the redis the instance should use. There are more work can be done to provide a more generic configuration.

## dev
```
  redis:
    type: 'single'
    password: 'redis-password'
    single-cache:
      address: 'redis://localhost:6379
```

## production
```
  redis:
    type: 'master-slave'
    password: 'redis-password'
    master-slave-cache:
      master-address: 'redis://redis-master:6379'
      slave-address: 'redis://redis-slave:6379
```

Then in the CacheConfiguration, I have
```
@Bean
    public javax.cache.configuration.Configuration<Object, Object> jcacheConfiguration(JHipsterProperties jHipsterProperties, ApplicationProperties applicationProperties) throws Exception {
        ...
        Config config = new Config();
        if (applicationProperties.getRedis().getType().equals(RedisType.SINGLE.getType())) {
            config.useSingleServer()
                .setAddress(applicationProperties.getRedis().getSingleCache().getAddress())
                .setPassword(applicationProperties.getRedis().getPassword());
        } else if (applicationProperties.getRedis().getType().equals(RedisType.MASTER_SLAVE.getType())) {
            config.useMasterSlaveServers()
                .setMasterAddress(applicationProperties.getRedis().getMasterSlaveCache().getMasterAddress())
                .addSlaveAddress(applicationProperties.getRedis().getMasterSlaveCache().getSlaveAddress())
                .setPassword(applicationProperties.getRedis().getPassword());
        } else {
            throw new Exception("The redis type " + applicationProperties.getRedis().getType() + " is not supported. Only single and master-slave are supported.");
        }
        ...
    }
```

**Comment by pascalgrimaud** [comment]
For now, we use:
- useClusterServers -> for "real" prod
- useSingleServer -> for dev

You suggest to add another config:
- useMasterSlaveServers -> for "real" prod, which doesn't need a real cluster ?

It can be interesting to document it, as putting it in main generator, there will be 1 more option for our end user which will not be used a lot...
What about putting a tips at https://www.jhipster.tech/tips/
Do you agree ? Would you like to submit a PR for this tip ?

**Comment by zhx828** [comment]
@pascalgrimaud I agree that it would be one more option to maintain. We can re-evaluate if more people asking the same thing. I drafted a tip (https://github.com/jhipster/jhipster.github.io/pull/920), please help to review. Thanks!
