### ISSUE TITLE
Do not generate Javadoc for methods of service implementations

### ISSUE THREAD

**Issue by sniffertine** [jhipster/generator-jhipster#11482]
##### **Overview of the issue**

For generated services, the same Javadoc is generated for interface and impl classes. 

##### **Motivation for or Use Case**

If you later document your service interface, you must not forget to either update the documentation of the impl class as well or delete it (to inherit the Javadoc of the interface)

##### **Suggest a Fix**

Do not generate a Javadoc for service impl classes. In most cases, you want to inherit the Javadoc of the interface anyway. 

##### **JHipster Version(s)**

6.3.1

##### **Browsers and Operating System**

-   not browser-related

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by geyuqiu** [comment]
@pascalgrimaud  may want to group [them](https://github.com/jhipster/generator-jhipster/issues/11363) ?
