### ISSUE TITLE
Add support to auto installation of blueprints/modules.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#11480]
##### **Overview of the feature request**

There is already a prompt to show blueprints and modules.
JHipster could install them automatically.

##### **Motivation for or Use Case**

Out of box support for blueprints and modules.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@mshima : I don't understand well what you have in mind, specially by installing automatically module and blueprint.
Do you mean: `npm install -g generator-jhipster` : we should install all existing blueprints and modules too ?

**Comment by mshima** [comment]
@pascalgrimaud 
Case 1:
- Running `jhipster —blueprints foo` will install the blueprint foo if it isn’t installed.
Case 2:
- Running `jhipster` already prompt if you want to use a blueprint/module. Install it instead of showing a message to install manually.

The module/blueprint will be installed and used without restarting jhipster.

**Comment by pascalgrimaud** [comment]
For the case1, I'm in favor, but I wonder if it's possible. You're an expert in Yeoman part so you know it well.

For the case 2, I'm not sure at all, as the existing modules are not sync with generator-jhipster. A lot of them are broken and would not work with our current version of JHipster.

**Comment by mshima** [comment]
Can be done.

For case 2, maybe we should change tags for jhipster 7.

**Comment by pascalgrimaud** [comment]
For case 1, there are some works:
- check if the blueprint is installed or not
- multi install if there is more than 1 blueprint
- check compatibility: today, not all blueprints are sync with v6.8.0 (I should update Vue.js soon)

For case 2, for v7, yes we should filter the existing modules like we did for v5 but not for v6.
For automatically installing them, I don't think it's a good idea. 
For example, I don't want to have in my package.json a module related to Kafka if I didn't choose it in my config. 
Or multitenancy if I have a NoSQL database.
If it was the case, I have to clean this file after each new generation and I don't want to. We should keep the package.json clean enough and let the end user to choose what needed

**Comment by mshima** [comment]
> For case 1, there are some works:
> 
> * check if the blueprint is installed or not

It’s already done today

> * multi install if there is more than 1 blueprint

Sure

> * check compatibility: today, not all blueprints are sync with v6.8.0 (I should update Vue.js soon)

It’s already done today.
But can’t be done before installing.
Once is installed it will be checked.

> For case 2, for v7, yes we should filter the existing modules like we did for v5 but not for v6.
> For automatically installing them, I don't think it's a good idea.
> For example, I don't want to have in my package.json a module related to Kafka if I didn't choose it in my config.

Current prompt adds it to otherModules:

https://github.com/jhipster/generator-jhipster/blob/7786df240e1d8e2e0e93ba1cc6b8b08e5179209f/generators/app/prompts.js#L189

Then saves to config.
https://github.com/jhipster/generator-jhipster/blob/7786df240e1d8e2e0e93ba1cc6b8b08e5179209f/generators/app/index.js#L493

So it will be written to package.json.

https://github.com/jhipster/generator-jhipster/blob/7786df240e1d8e2e0e93ba1cc6b8b08e5179209f/generators/client/templates/angular/package.json.ejs#L150

This feature will not change current behavior.
I really don’t like jhipster and blueprint/modules to be written to package.json at all. I think we should remove it. But that’s another discussion.

> Or multitenancy if I have a NoSQL database.
> If it was the case, I have to clean this file after each new generation and I don't want to. We should keep the package.json clean enough and let the end user to choose what needed

Auto install will to install only blueprints/modules selected by the user.
The approach I am thinking uses an separated node_modules repository.
It will not write to package.json at first.
It will write at the project generation because every module is written.

**Comment by pascalgrimaud** [comment]
We didn't manage to understand well each other :D
But in the end, I think we agree !

**Comment by pascalgrimaud** [comment]
@mshima : I'm adding a bounty on this as it is a very nice feature
