### ISSUE TITLE
gradlew build in container problem

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#11499]
##### **Overview of the issue**

I am running ./gradlew clean build -Pprod -PnodeInstall --no-daemon inside a container to build the app, and it tale too much time (and fails sometimes) due to memory constraints I think.

I check the code and found in gradlew:
https://github.com/jhipster/generator-jhipster/blob/e322dbb8a0fc83c632dd72b0d7308fd8da931862/generators/server/templates/gradlew#L47

Can anyone tell me why? @atomfrede maybe

Can we switch to java 9+ syntax that scales depending on container memory...
We could also just remove this and let the use choose what to use, specially since gradle.properties I think could be used for such things.

Thanks in advance.

##### **Motivation for or Use Case**

Building in containers

##### **Reproduce the error**

run ./gradlew build in a container with a big enough app

##### **Suggest a Fix**

remove JVM ARGS from gradlew

##### **JHipster Version(s)**

6.6.0

**Comment by atomfrede** [comment]
The gradlew(wrapper) is not created by us. It's the default file created by gradlew it itself and we should not change it. You can define the memory for the gradle Java process via parameters, but I need to look them up.

**Comment by yelhouti** [comment]
@atomfrede no worries, I tough you modified it manually since I saw one line change, or did you just update gradle then call `gradle wrapper`?

**Comment by atomfrede** [comment]
Yes. Just calling the wrapper command with the version we want to have.

**Comment by yelhouti** [comment]
thanks for confirming :)
