### ISSUE TITLE
Generate springboot microservices which supports multiple Couchbase bucket configuration

### ISSUE THREAD

**Issue by amalkurup89** [jhipster/generator-jhipster#11494]
##### **Overview of the feature request**

Currently the springboot microservices generated by Jhipster supports only single bucket configuration with Couchbase. Can we have Jhipster support multi-bucket Couchbase configuration

##### **Motivation for or Use Case**
Suggestion to improve Jhipster

##### **Related issues or PR** --> No

No

-   [ ✓] Checking this box is mandatory (this is just to show you read everything)

**Comment by amalkurup89** [comment]
@DanielFran Is this being looked upon or in your recent feature list

**Comment by pascalgrimaud** [comment]
@amalkurup89 : you can contribute to the project and propose a pull request, as it seems you know who to do it.

**Comment by pascalgrimaud** [comment]
No more comment since weeks.
If you want to do this @amalkurup89, just tell me and I'll reopen the ticket.
Otherwise, I'm closing this for lack of interest.
