### ISSUE TITLE
Spring Session Support

### ISSUE THREAD

**Issue by hantsy** [jhipster/generator-jhipster#1149]
Spring Session is a new project which use Redis based Session instead of Http Session, and it provides Cookie based and Header based session id. I think it can work well with jhipster existed token based security solution.

**Comment by jdubois** [comment]
No we can't ask all of our users to install Redis 
Current options are Hazelcast or being stateless, and we will focus on those

**Comment by thekalinga** [comment]
Spring session can work with hazelcast too

https://github.com/spring-projects/spring-session/tree/1.0.1.RELEASE//samples/hazelcast

Any plans around using the spring session with jhipster?
