### ISSUE TITLE
Upgrade couchbase to 6.5.0

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#11491]
See https://docs.couchbase.com/server/6.5/release-notes/relnotes.html

ping @tchlyah 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by tchlyah** [comment]
It's version 6.5.0 😉 

I already upgraded the version here https://github.com/jhipster/generator-jhipster/pull/11421, which is blocked for now by https://github.com/testcontainers/testcontainers-java/pull/2350!

If you prefer I can do an other PR just for the upgrade

**Comment by DanielFran** [comment]
@tchlyah Thanks for the feedback.

Will you make a PR to update the changes in jhipster bom? See https://github.com/jhipster/jhipster/blob/master/jhipster-dependencies/pom.xml#L48-L50

Anyway, I will close this one.
Thanks
