### ISSUE TITLE
Extending the JDLImporter is no longer working after JHipster 6.7.0

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#11501]
##### **Overview of the issue**

The Ionic for JHipster project has an [`import-jdl`](https://github.com/oktadeveloper/generator-jhipster-ionic/blob/master/generators/import-jdl/index.js) command that uses JHipster Core's JDLImporter:

```
const jdlImporter = jhiCore.jdl.import.JDLImporter.createImporterFromFiles(this.jdlFiles, {
  databaseType: this.prodDatabaseType,
  applicationType: this.applicationType,
  applicationName: this.baseName
});
```

This works great when using JHipster 6.7.0, but as soon as I upgrade to generator-jhipster 6.7.1, I get the following error when trying to import JDL:

```
➜  ionic4j git:(master) ✗ yo jhipster-ionic:import-jdl app.jdl
INFO! The JDL is being parsed...
INFO! File .jhipster-ionic.json not found. Please run this command in an Ionic project.
TypeError: Cannot read property 'import' of undefined
events.js:187
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'exportedEntities' of undefined
    at ImportJDLGenerator.generateEntities (/Users/mraible/ionic4j/node_modules/generator-jhipster-ionic/generators/import-jdl/index.js:125:30)
    at Object.<anonymous> (/Users/mraible/ionic4j/node_modules/yeoman-generator/lib/index.js:647:25)
    at /Users/mraible/ionic4j/node_modules/run-async/index.js:47:25
    at new Promise (<anonymous>)
    at /Users/mraible/ionic4j/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.once.once (/Users/mraible/ionic4j/node_modules/yeoman-generator/lib/index.js:648:11)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:131:23)
Emitted 'error' event on ImportJDLGenerator instance at:
    at Immediate.<anonymous> (/Users/mraible/ionic4j/node_modules/yeoman-generator/lib/index.js:668:20)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:131:23)
```

##### **Motivation for or Use Case**

If I revert to JHipster 6.7.0, everything works fine.

##### **Reproduce the error**

Create a `bug/backend` folder and copy the following `app.jdl` into it.

```
application {
  config {
    baseName mono
    applicationType monolith
    authenticationType jwt
    packageName org.jhipster.demo.blog
    prodDatabaseType mysql
    buildTool maven
    clientFramework angular
    testFrameworks [protractor]
  }
  entities *
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll
```

Run `jhipster import-jdl app.jdl`

Using the latest release of Ionic4J, cd into `bug` and run `yo jhipster-ionic default` to create a new app. Then run the following:

```
cd ionic4j
yo jhipster-ionic:import-jdl ../backend/app.jdl
```

You'll see the error I mentioned. If you change `ionic4j/package.json` to use `generator-jhipster` v6.7.0 and run `npm install`, running the above command will succeed.

##### **JHipster Version(s)**

```
mono@0.0.1-SNAPSHOT /Users/mraible/backend
└── generator-jhipster@6.8.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "baseName": "mono",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "applicationType": "monolith",
    "packageName": "org.jhipster.demo.blog",
    "packageFolder": "org/jhipster/demo/blog",
    "jhipsterVersion": "6.8.0",
    "creationTimestamp": 1585027080643,
    "skipServer": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["Blog", "Post", "Tag"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}
entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

git version 2.21.1 (Apple Git-122.3)

node: v12.13.0

npm: 6.14.2

yeoman: 3.1.1

yarn: 1.22.0

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.4, build 8d51620a

**Comment by MathieuAA** [comment]
`.jhipster-ionic.json not found`

That's not part of the regular JDL import flow, @mraible I'm new to this but why is it needed to import a JDL file?

**Comment by mshima** [comment]
@mraible instead of pinning generator-jhipster.
You should add a explicit dependency on jhipster-core@6.0.7.

Is there any plan to add blueprint support?

**Comment by mshima** [comment]
This is the relevant api change:
https://github.com/jhipster/generator-jhipster/commit/e41b0327b643f96c48d4c00fe708a0c42174c63e#diff-0898b22730d57afcd394d8e4889ece4a

**Comment by mraible** [comment]
@MathieuAA You are correct. We create this file for the entity generator since we extend from JHipsters in https://github.com/oktadeveloper/generator-jhipster-ionic/blob/master/generators/entity/index.js.

@mshima Thanks for the relevant API change. I'll try changing our JDL importer to use that. As far as pinning jhipster-core, we also extend the entity generator from generator-jhipster so I prefer to retain the dependency on that higher-level component.

See https://github.com/oktadeveloper/generator-jhipster-ionic/pull/274 for the PR to fix.

**Comment by mraible** [comment]
Hmmmm, changing from:

```js
const jdlImporter = jhiCore.jdl.import.JDLImporter.createImporterFromFiles(this.jdlFiles, {
```

To:

```js
const jdlImporter = jhiCore.JDLImporter.createImporterFromFiles(this.jdlFiles, {
```

Doesn't seem to solve the problem. https://travis-ci.org/github/oktadeveloper/generator-jhipster-ionic/jobs/666438709#L2362

**Comment by mraible** [comment]
Damn, I did a new release of Ionic4J yesterday and it seems this is [still an issue](https://github.com/oktadeveloper/generator-jhipster-ionic/issues/279). There's no error output now. It seems the writing of files just fails silently. Is there anything in our [`import-jdl/index.js`](https://github.com/oktadeveloper/generator-jhipster-ionic/blob/master/generators/import-jdl/index.js) that looks funny?

**Comment by mshima** [comment]
I will take a look in ~ 1 hour.

**Comment by MathieuAA** [comment]
A way to know that would be to look at what's returned by the importer @mraible.
This should be the exact list of what's written to the disk

**Comment by mshima** [comment]
> Damn, I did a new release of Ionic4J yesterday and it seems this is [still an issue](https://github.com/oktadeveloper/generator-jhipster-ionic/issues/279). There's no error output now. It seems the writing of files just fails silently. Is there anything in our [`import-jdl/index.js`](https://github.com/oktadeveloper/generator-jhipster-ionic/blob/master/generators/import-jdl/index.js) that looks funny?

You reverted the version but not the jhipster-core api change.
That's why I think the jhipster-core must be pinned.

**Comment by mraible** [comment]
This is fixed thanks to @mshima! https://github.com/oktadeveloper/generator-jhipster-ionic/releases/tag/v5.1.1

I'm not sure how to set up the bounty payout. Can you help me do that @pascalgrimaud?

**Comment by pascalgrimaud** [comment]
> I'm not sure how to set up the bounty payout.

Just follow this: https://www.jhipster.tech/bug-bounties/
