### ISSUE TITLE
Migrate Ionic for JHipster to use GitHub Actions

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#11506]
Proxy ticket for https://github.com/oktadeveloper/generator-jhipster-ionic/issues/278. @pascalgrimaud volunteered. :)

**Comment by Hawkurane** [comment]
Hello, I would like to work on this, would that be ok ? @mraible @pascalgrimaud

**Comment by pascalgrimaud** [comment]
sure, I can help to review if needed @Hawkurane 
gogogo !

**Comment by mraible** [comment]
@Hawkurane Have you started on this yet? I'm thinking about doing it now since Travis is down. I can hold off if you've already started it.

**Comment by mraible** [comment]
@Hawkurane Nevermind. Travis started working again. 🙂

**Comment by Hawkurane** [comment]
@mraible Yes, I have already started on it: I just need to change environment variables from travis to github's.
if you want to check the progress on my branch: [https://github.com/Hawkurane/generator-jhipster-ionic/tree/migrate-github-ci](https://github.com/Hawkurane/generator-jhipster-ionic/tree/migrate-github-ci)

**Comment by amanganiello90** [comment]
> @mraible Yes, I have already started on it: I just need to change environment variables from travis to github's.
> if you want to check the progress on my branch: https://github.com/Hawkurane/generator-jhipster-ionic/tree/migrate-github-ci

If it is not a problem, I could help you rewiewing this ticket, because I have the CI integration for this task that I am working: https://github.com/oktadeveloper/generator-jhipster-ionic/issues/170.
Don't hesitate for every think, fell free 😊

**Comment by mraible** [comment]
@Hawkurane Anything I can do to help?

**Comment by Hawkurane** [comment]
Hello, I have been working with @Shaolans and I think we are quite near the end,
currently we are meeting a problem with selenium for e2e tests, which I think comes from permission rights:
[https://github.com/Hawkurane/generator-jhipster-ionic/runs/552203161?check_suite_focus=true](https://github.com/Hawkurane/generator-jhipster-ionic/runs/552203161?check_suite_focus=true)

**Comment by mraible** [comment]
Fixed! Thanks y'all. 🙏

**Comment by pascalgrimaud** [comment]
I'm increasing the bounty as @Hawkurane said me it was more work than expected and he needs help from @Shaolans : so it will be easier for them to share the bounty
Good job guys

**Comment by Hawkurane** [comment]
Half of the bounty claimed as well 
https://opencollective.com/generator-jhipster/expenses/15294

**Comment by pascalgrimaud** [comment]
@Hawkurane : approuved
