### ISSUE TITLE
Bug with frontend and docker?

### ISSUE THREAD

**Issue by CentroricercheRPS** [jhipster/generator-jhipster#11503]
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
powerfront@0.0.1-SNAPSHOT /home/michele/gitlab/jhipster/PowerNETGuard/powerfront
└── generator-jhipster@6.8.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": false,
    "baseName": "powerfront",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "it", "fr", "de", "es"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "gateway",
    "packageName": "com.rps.png",
    "packageFolder": "com/rps/png",
    "jhipsterVersion": "6.8.0",
    "creationTimestamp": 1585044660725,
    "skipServer": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["Device"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Device {
  address String required
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)

git version 2.20.1

node: v10.16.0

npm: 6.9.0

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.25.4, build 8d51620a

INFO! Congratulations, JHipster execution is complete!
##### **Overview of the issue**

If I run 
'./mvnw package -Pprod verify jib:dockerBuild`

then I get

[INFO] Oops! Something went wrong! :(
[INFO] 
[INFO] ESLint: 6.7.2.
[INFO] 
[INFO] ESLint couldn't find the config "jhipster" to extend from. Please check that the name of the config is correct.
[INFO] 
[INFO] The config "jhipster" was referenced from the config file in "/home/michele/gitlab/jhipster/.eslintrc.json".
[INFO] 
[INFO] If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.
[INFO] 
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 2
[INFO] npm ERR! powerfront@0.0.1-SNAPSHOT lint: `eslint . --ext .js,.ts`
[INFO] npm ERR! Exit status 2
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the powerfront@0.0.1-SNAPSHOT lint script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /root/.npm/_logs/2020-03-24T11_39_15_038Z-debug.log
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 2
[INFO] npm ERR! powerfront@0.0.1-SNAPSHOT test: `npm run lint && jest --coverage --logHeapUsage -w=2 --config src/test/javascript/jest.conf.js`
[INFO] npm ERR! Exit status 2
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the powerfront@0.0.1-SNAPSHOT test script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /root/.npm/_logs/2020-03-24T11_39_15_069Z-debug.log
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 2
[INFO] npm ERR! powerfront@0.0.1-SNAPSHOT webpack:test: `npm run test`
[INFO] npm ERR! Exit status 2
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the powerfront@0.0.1-SNAPSHOT webpack:test script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /root/.npm/_logs/2020-03-24T11_39_15_107Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:52 min
[INFO] Finished at: 2020-03-24T12:39:15+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:npm (webpack build test) on project powerfront: Failed to run task: 'npm run webpack:test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

##### **Motivation for or Use Case**

Standard command should work

##### **Reproduce the error**

Created a frontend project, then run the jib docker build command gave me the error above

##### **JHipster Version(s)**

First time I user JHipster

##### **JHipster configuration**

see above
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": false,
    "baseName": "powerfront",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "it", "fr", "de", "es"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "gateway",
    "packageName": "com.rps.png",
    "packageFolder": "com/rps/png",
    "jhipsterVersion": "6.8.0",
    "creationTimestamp": 1585044660725,
    "skipServer": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "jwtSecretKey": "NzcwN2ZjMGYwZGY2ZmIxN2QxNWFmNzFmZDgwM2QwZWIwZGY2NWU4YWU0YWMwZTQyNDgzYjY1NjY0MDI4YjVlOTcwYjYwYzIxOTJiNDBlYjY3ODgzOGE1MTEwYmFkMjA1MDNiM2Y5MDMzYjc0MjgyMDY2YWQwNDY0NGRiYjY2NjQ=",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["Device"]
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
    "name": "Device",
    "fields": [
        {
            "fieldName": "address",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "relationships": [],
    "changelogDate": "20200324101200",
    "entityTableName": "device",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "readOnly": false,
    "embedded": false,
    "clientRootFolder": "",
    "applications": [
        "powerfront",
        "powerback"
    ]
}
##### **Browsers and Operating System**

Debian 10.3

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I could not reproduce this issue, you should have `"eslint-config-jhipster": "0.0.1",` in your package.json which contains the jhipster eslint configuration.

If I remove that line from the package.json, I get the same error message.

**Comment by CentroricercheRPS** [comment]
Yes, I have that line. However, I run the command ('./mvnw package -Pprod verify jib:dockerBuild`) as root (because of Docker permissions).

Can this be an issue?

**Comment by ruddell** [comment]
Does `./mvnw package -Pprod verify` work? You should be able to run that without root, which would let us know if that's causing the issue.

**Comment by CentroricercheRPS** [comment]
Nope, I got the same error.

**Comment by vishal423** [comment]
@CentroricercheRPS, can you try upgrading your `node.js` version from `10.16.x` to the one used by app `12.16.x`?

**Comment by CentroricercheRPS** [comment]
Installed 12.16.1 (with nvm), still got the same issue

**Comment by vishal423** [comment]
did you cleaned the `node_modules` directory and installed packages again?

**Comment by CentroricercheRPS** [comment]
rm -rf node_modules/

and

./mvnw package -Pprod verify

Still got the same error

**Comment by CentroricercheRPS** [comment]
I realized that this project was nested inside another jhipster project! After deleting the parent folder project files, the verify worked!
