### ISSUE TITLE
Duplicate Success Message Printing: Entity Generation

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#11502]
##### **Overview of the issue**

When generating entities using a JDL file, upon success we print the message; `INFO! Congratulations, JHipster execution is complete!`. However this message seems to be printed for each entity generated. So for example if I have three entities in my JDL file that message is printed three times. 

##### **Motivation for or Use Case**

It's not the most visually pleasing when say we have a JDL file with 10 entities and the success message being printed 10 times. 

##### **Reproduce the error**

Create a simple project. You can use the below configuration. 

##### **Related issues**

None.

##### **Suggest a Fix**

Don't have one right now. If someone is willing to take this please feel free to do so; otherwise I'll fix this in the future. :smile: 

##### **JHipster configuration**

<pre>&lt;details&gt;
&lt;summary&gt;.yo-rc.json file&lt;/summary&gt;
&lt;pre&gt;
{
  &quot;generator-jhipster&quot;: {
    &quot;promptValues&quot;: {
      &quot;packageName&quot;: &quot;com.mycompany.myapp&quot;
    },
    &quot;jhipsterVersion&quot;: &quot;6.8.0&quot;,
    &quot;applicationType&quot;: &quot;monolith&quot;,
    &quot;baseName&quot;: &quot;jhipster&quot;,
    &quot;packageName&quot;: &quot;com.mycompany.myapp&quot;,
    &quot;packageFolder&quot;: &quot;com/mycompany/myapp&quot;,
    &quot;serverPort&quot;: &quot;8080&quot;,
    &quot;authenticationType&quot;: &quot;jwt&quot;,
    &quot;cacheProvider&quot;: &quot;ehcache&quot;,
    &quot;enableHibernateCache&quot;: false,
    &quot;websocket&quot;: false,
    &quot;databaseType&quot;: &quot;sql&quot;,
    &quot;devDatabaseType&quot;: &quot;h2Disk&quot;,
    &quot;prodDatabaseType&quot;: &quot;mysql&quot;,
    &quot;searchEngine&quot;: false,
    &quot;messageBroker&quot;: false,
    &quot;serviceDiscoveryType&quot;: false,
    &quot;buildTool&quot;: &quot;maven&quot;,
    &quot;enableSwaggerCodegen&quot;: false,
    &quot;jwtSecretKey&quot;: &quot;bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl&quot;,
    &quot;embeddableLaunchScript&quot;: false,
    &quot;useSass&quot;: true,
    &quot;clientPackageManager&quot;: &quot;npm&quot;,
    &quot;clientFramework&quot;: &quot;angularX&quot;,
    &quot;clientTheme&quot;: &quot;none&quot;,
    &quot;clientThemeVariant&quot;: &quot;&quot;,
    &quot;creationTimestamp&quot;: 1585028296449,
    &quot;testFrameworks&quot;: [],
    &quot;jhiPrefix&quot;: &quot;jhi&quot;,
    &quot;entitySuffix&quot;: &quot;&quot;,
    &quot;dtoSuffix&quot;: &quot;DTO&quot;,
    &quot;otherModules&quot;: [],
    &quot;enableTranslation&quot;: false,
    &quot;blueprints&quot;: []
  }
}

&lt;/pre&gt;
&lt;/details&gt;

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

&lt;details&gt;
&lt;summary&gt;JDL entity definitions&lt;/summary&gt;

&lt;pre&gt;
entity Region {
  regionName String
}
entity Country {
  countryName String
}
entity Location {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}

&lt;/pre&gt;
&lt;/details&gt;

##### **Environment and Tools**

openjdk version &quot;11.0.6&quot; 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.17.1

node: v12.13.0

npm: 6.12.0

yarn: 1.21.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.24.1, build 4667896b
</pre>

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nassimerrahoui** [comment]
Hello, I'm working on it.

**Comment by SudharakaP** [comment]
@nassimerrahoui : Wonderful; thanks. Let me know if you have any questions or further information. :smile:

**Comment by qmonmert** [comment]
@nassimerrahoui I didn't know that you worked on it, I made a PR #11507 I contact you
