### ISSUE TITLE
Provides multi project options

### ISSUE THREAD

**Issue by hantsy** [jhipster/generator-jhipster#1150]
Provides an option to generate client(AngularJS SPA) and server(REST API) projects respectively.

**Comment by dejewi** [comment]
+1

**Comment by svennela** [comment]
+1
I would say..

Provides an option to generate AS(AuthServer), client(AngularJS SPA) and server(REST API) projects respectively.
Just like below
https://github.com/dsyer/spring-security-angular/tree/master/oauth2-vanilla

**Comment by dejewi** [comment]
@svennela +2 ;)

**Comment by jdubois** [comment]
As mentioned, it's already been discussed and it's out of scope.
You can delete the front or the back end code easily, so it's trivial to get what you want, but you can't really use one without the other.

**Comment by gzsombor** [comment]
... and there are lot's of different way to modularize the application, which are totally different. For example, I've separated as an 'api' module (for DTO's and internal interfaces), an 'impl' module (for handling the database, and the service implementations), and a 'web' module (for the REST resources, and the web assets).
