### ISSUE TITLE
Wrong tutorial or error in documentation

### ISSUE THREAD

**Issue by CentroricercheRPS** [jhipster/generator-jhipster#11514]
##### **JHipster Version(s)**

```
/home/michele
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "appsFolders": ["invoice", "notification", "store"],
    "directoryPath": "../",
    "gatewayType": "zuul",
    "clusteredDbApps": [],
    "monitoring": "no",
    "consoleOptions": [],
    "serviceDiscoveryType": "eureka",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)

git version 2.20.1

node: v10.16.0

npm: 6.9.0

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.25.4, build 8d51620a

##### **Overview of the issue**

Copied the example:
`https://raw.githubusercontent.com/jhipster/jdl-samples/master/microservice-ecommerce-store.jdl`

Ran

```
jhipster import-jdl microservice-ecommerce-store.jdl
cd invoice/
./gradlew bootJar -Pprod jibDockerBuild
cd ..
cd notification/
./gradlew bootJar -Pprod jibDockerBuild
cd ..
cd store/
./gradlew bootJar -Pprod jibDockerBuild
mkdir docker-compose
cd docker-compose/
jhipster docker-compose
docker-compose up -d
```

##### **Motivation for or Use Case**

Two issues:
1) Instead of having one database instance, I get two databases linked to invoice and store respectively, and when opening the web page the data isn't pre-populated.
2) Is not possible to add a new Customer, because you always get the error "Field user cannot be empty!"

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

https://raw.githubusercontent.com/jhipster/jdl-samples/master/microservice-ecommerce-store.jdl

##### **Browsers and Operating System**

Debian 10

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
Can you share the JDL file(s) you have and also the `.yo-rc.json` file(s). To me it seems like you have some microservice application but without the `.yo-rc.json` files and the entity files we cannot accurately recreate the problem. :smile:

**Comment by CentroricercheRPS** [comment]
I just used the tutorial https://raw.githubusercontent.com/jhipster/jdl-samples/master/microservice-ecommerce-store.jdl

I didn't touch anything, please check the 'Overview of the issue' section of this bug report for information on how to reproduce, and 'Motivation for or Use Case' for the outcome.

If you try this and are unable to reproduce the issue, you can close it

**Comment by SudharakaP** [comment]
@CentroricercheRPS : Thanks much for that information. :smile: 

I've started these micro-services as you did just to test it out. 

1) You should get three databases; notice that the jdl has three applications; the store; invoice and the notification. Among these the store is the [gateway](https://www.jhipster.tech/api-gateway/#-the-jhipster-api-gateway) the other two are microservices. The invoice microservice should have a mysql database the notification microservice should have a mongodb database and the store gateway should have another mysql database. These databases are created correctly and I could access the gateway and see the microservices running. 

2) When trying to add a customer I get the same error. I think this is a bug on our end. When looking at the logs I see the following error. :thinking: 

```
Bad Request: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<com.jhipster.demo.store.domain.Customer> com.jhipster.demo.store.web.rest.CustomerResource.createCustomer(com.jhipster.demo.store.domain.Customer) throws java.net.URISyntaxException: [Field error in object 'customer' on field 'user': rejected value [null]; codes [NotNull.customer.user,NotNull.user,NotNull.com.jhipster.demo.store.domain.User,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [customer.user,user]; arguments []; default message [user]]; default message [must not be null]] 
```

**Comment by SudharakaP** [comment]
@MathieuAA : Hey Mathieu, do you see an obvious problem with this JDL file? I was just wondering since it's updated 17 months ago. :smiley:

**Comment by MathieuAA** [comment]
I don't see any obvious error. However, this reminds me of an old issue with the same sample. I think it's related to the `required` keyword for relationships. I'm not sure at all.

**Comment by MathieuAA** [comment]
Maybe related to #10858, but again I'm not so sure... I'm sure I've seen something like that somewhere

**Comment by SudharakaP** [comment]
@MathieuAA : Thanks a lot for your input. :handshake:  Let me do some more investigation. :thinking:

**Comment by MathieuAA** [comment]
BTW, what's the generator's version?

**Comment by SudharakaP** [comment]
> BTW, what's the generator's version?

I am using v6.8.0. :smile:

**Comment by MathieuAA** [comment]
@SudharakaP when you add a new customer, is there a select element to actually select an existing user?

**Comment by MathieuAA** [comment]
Ah. That's an interesting one. Two possibilities:
  - either the JDL generates an invalid JSON content, which the generator uses to generate "corrupt" code
  - or the generator doesn't generate a valid code

I could swear that I've already seen this issue but I can't seem to find it

**Comment by SudharakaP** [comment]
The `customer.json` file looks like follows. It seems correct to me; then it generator problem I guess. :thinking: 

```json
{
  "name": "Customer",
  "fields": [
    {
      "fieldName": "firstName",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "lastName",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "gender",
      "fieldType": "Gender",
      "fieldValues": "MALE,FEMALE,OTHER",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "email",
      "fieldType": "String",
      "fieldValidateRules": ["required", "pattern"],
      "fieldValidateRulesPattern": "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"
    },
    {
      "fieldName": "phone",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "addressLine1",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "addressLine2",
      "fieldType": "String"
    },
    {
      "fieldName": "city",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "country",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    }
  ],
  "relationships": [
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "user",
      "otherEntityRelationshipName": "customer",
      "relationshipValidateRules": "required",
      "relationshipName": "user",
      "otherEntityField": "login",
      "ownerSide": true
    },
    {
      "relationshipType": "one-to-many",
      "otherEntityName": "productOrder",
      "otherEntityRelationshipName": "customer",
      "relationshipName": "order"
    }
  ],
  "changelogDate": "20200416175904",
  "entityTableName": "customer",
  "dto": "no",
  "pagination": "pagination",
  "service": "serviceClass",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "clientRootFolder": "",
  "applications": ["store"]
}
```

**Comment by SudharakaP** [comment]
I've made a fix for this issue. I believe this error is introduced by revision 448d48ec9 whereby instead of the correct user object the react client passes a null object. :smile: 

@CentroricercheRPS : Please refer to the above PR and all you have to do is replace the line `entity.user = users[values.user]` by `entity.user = values.user` within the `customer-update.tsx` class (in `store` app).
