### ISSUE TITLE
Unable to start a MongoDB cluster with Docker

### ISSUE THREAD

**Issue by Falydoor** [jhipster/generator-jhipster#11519]
##### **Overview of the issue**

Unable to start a MongoDB cluster using the docker-compose file:

![image](https://user-images.githubusercontent.com/2212267/77790253-e2943800-703a-11ea-927a-993cebf20b6a.png)

##### **Motivation for or Use Case**

The docker-compose file should start a MongoDB cluster.

##### **Reproduce the error**

Generate a monolith that uses MongoDB and then run `docker-compose -f src/main/docker/mongodb-cluster.yml up`.

##### **Suggest a Fix**

Some options are removed from the CLI -> https://docs.mongodb.com/manual/release-notes/4.2-compatibility/#mmapv1-specific-configuration-options.

##### **JHipster Version(s)**

6.8.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "mongo",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1585334753063,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 12 Mac OS X amd64-64-Bit Compressed References 20190915_201 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - 9984ea0dd9 based on jdk-12.0.2+10)

git version 2.26.0

node: v10.19.0

npm: 6.13.7

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.4, build 8d51620a

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by monxxi** [comment]
Hello, i'll try to fix this bug.

**Comment by pascalgrimaud** [comment]
Thanks and congrats for your 1st contribution @monxxi !
