### ISSUE TITLE
[Feature Request] Add custom NgbInputDatepicker implementation

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#11525]
##### **Overview of the feature request**

Currently, date picker only allows YYYY-MM-DD format. By adding a custom implementation, users will be able to choose the format she/he desires.

##### **Motivation for or Use Case**

Being able to choose the format I want to show in a date picker.

##### **Related issues or PR**

No issues/PR found

##### **Proposal**
 I created a files called `shared/component/ngb-custom-date-parser-formatter.ts` with following content:
```
import { NgbDateParserFormatter, NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
import { Injectable } from '@angular/core';
import * as moment from 'moment';

@Injectable()
export class NgbCustomDateParserFormatter extends NgbDateParserFormatter {

  constructor(private momentFormat: string) {
    super();
  };

  format(date: NgbDateStruct): string {
    if (date === null) {
      return '';
    }
    const d = moment({ year: date.year,
      month: date.month - 1,
      date: date.day });
    return d.isValid() ? d.format(this.momentFormat) : '';
  }

  parse(value: string): NgbDateStruct {
    if (!value) {
      return null;
    }
    const d = moment(value, this.momentFormat);
    return d.isValid() ? { year: d.year(),
      month: d.month() + 1,
      day: d.date() } : null;
  }
}
```
In my `app.module.ts` file I added this line: (maybe the format could be saved in a config file?)
```
providers: [
    {
      provide: NgbDateParserFormatter,
      useValue: new NgbCustomDateParserFormatter("DD/MM/YYYY")
    }
  ],
```

After that, I was able to show my dates as wished:

![Nueva_Factura](https://user-images.githubusercontent.com/42916953/77840223-90423c80-714a-11ea-84de-2e3859b3fb31.png)

-   [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by aleksandar-budisa** [comment]
I need complete code from ngb-custom-date-parser-formatter.ts to html.

**Comment by amatosg** [comment]
> I need complete code from ngb-custom-date-parser-formatter.ts to html.

There is no html change needed for this to work. The generated code will show dates in the desired format.

**Comment by aleksandar-budisa** [comment]
This code in my case don't work, visual studio code show error for format metod.

**Comment by aleksandar-budisa** [comment]
I use angular 9.

**Comment by aleksandar-budisa** [comment]
![screen](https://user-images.githubusercontent.com/32466224/77887860-9845cd80-726b-11ea-888e-e02616cb40e8.jpg)
This is error in command promt.

**Comment by aleksandar-budisa** [comment]
Works, thanks very much.

**Comment by amatosg** [comment]
@aleksandar-budisa then please delete the comments to keep the issye clean. Thanks

**Comment by aleksandar-budisa** [comment]
Deleted. Thanks.

**Comment by mraible** [comment]
Closing because of @amatosg's comment:

> There is no html change needed for this to work. The generated code will show dates in the desired format.

**Comment by aleksandar-budisa** [comment]
Where and how and I will do it ?
I don't remember when and where I write this.

уто, 31. мар 2020. у 01:31 Alejandro Matos <notifications@github.com> је
написао/ла:

**Comment by amatosg** [comment]
@mraible sorry, I don't see the relation between my comment and the closure of this issue. What I meant is that the changes needed were only the new ParserFormatter file and add the record in app.model.ts but nothing have to be changed in the HTML file

**Comment by mraible** [comment]
OK, reopening.

**Comment by amatosg** [comment]
I'm going to wait until next release if that's ok

**Comment by DanielFran** [comment]
@amatosg Are you willing to give it a shot again?

**Comment by amatosg** [comment]
@DanielFran I don't know how to create new files, do I just create the ejs file? :/

**Comment by Tcharl** [comment]
@amatosg 
You should create a new ejs file and also reference it in the according section of the relative 'file.js'
