### ISSUE TITLE
In a blueprint, `--prettier-java` can't find the java plugin

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#11533]
##### **Overview of the issue**
Use the `--prettier-java` in a JHipster blueprint.
https://github.com/jhipster/jhipster-quarkus/pull/37#issuecomment-606827625

##### **Reproduce the error**

Quite tricky to reproduce since it's very specific to blueprints planning to use the `--prettier-java` option, so I think Jhipster quarkus may be the only one?

##### **Suggest a Fix**

According to https://prettier.io/docs/en/plugins.html Prettier looks for plugin in the same `node_modules` but in a blueprint Prettier and the java plugin are not in the same directory

Within a blueprint, the dependencies are a bit transformed (i'm not a node_module so don't ask me why).
Anyway, in the blueprint node_modules  I can found the `generator-jhipster` dependency which has also couple of dependencies
![Screenshot 2020-03-31 at 10 57 58 PM](https://user-images.githubusercontent.com/593564/78074583-486a2200-73a3-11ea-8ae4-c4b7924d7f0f.png)
You may notice prettier is present as dependency but not the java plugin. 

I can find the java plugin in the blueprint dependencies (I remove the declaration or prettier and java plugin in the blueprint `package.json`).
![Screenshot 2020-03-31 at 10 58 15 PM](https://user-images.githubusercontent.com/593564/78074711-7bacb100-73a3-11ea-8898-06d2ae308481.png)

So  we end up with this structure in a blueprint:
```
node_modules/
  + generator-jhipster/
  |-+node_modules/
     |--+prettier/ <-- the one invoke by `--prettier-java`
  +prettier/
  +prettier-plugin-java
```

I had a deeper look to:
https://github.com/jhipster/generator-jhipster/blob/d3cc5f6b8e021422bbab6d8151172ececb0eaf2d/generators/generator-transforms.js#L44
I tested by updating `generator-transform.js
```
onst prettierTransform = function(defaultOptions) {
    const transform = (file, encoding, callback) => {
        /* resolve from the projects config */
        prettier.resolveConfig(file.relative).then(options => {
            if (file.state !== 'deleted') {
                const str = file.contents.toString('utf8');
                if (!options || Object.keys(options).length === 0) {
                    options = defaultOptions;
                }
                // for better errors
                options.filepath = file.relative;
                this.
                options.plugins = ["/Users/daniel/workspace/jhipster-quarkus/node_modules/prettier-plugin-java"]
                const data = prettier.format(str, options);
                file.contents = Buffer.from(data);
            }
            callback(null, file);
        });
    };
    return through.obj(transform);
};
```
Since I specify the plugins path it works like a charm.

Now that I had the root cause, I tried to have a more "generic" way to fix the issue.
I don't remember a way to get a blueprint basedir to compute a "${basedir}/node_modules" path which would do the trick? Are you aware of this kind of util method? 
Otherwise, you can use `options.pluginSearchDirs = [".", ".."];` which works too but I'm sure there is plenty of side-effects (not sure it work with the main jhipster generator.

##### **JHipster Version(s)**

`6.8.0`
##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I'm adding the label blueprint too

**Comment by pascalgrimaud** [comment]
cc @mshima and @clementdessoude : maybe you know how to solve this issue ?

**Comment by mshima** [comment]
I didn’t test, but I think the fix is:
```
    options.plugins = [require('prettier-java')];
```
An alternative is.
```
if (generator.fromBlueprint) {
    options.pluginSearchDirs = [".", ".."];
}
```

Probably if prettier-java is removed from dependency of the blueprint, it will be moved to the correct place.
```
node_modules/
  + generator-jhipster/
  |-+node_modules/
     |--+prettier/
     |--+prettier-plugin-java
  +prettier/
```

**Comment by danielpetisme** [comment]
Hello,
I tried to remove the prettier-plugin-java from the blueprint dependencies and it does not solve the issue.
Actually, I don't understand how npm organize `node_modules` I guess it optimize the dependency graph to prevent and that's why it's reorganizing it.

It's not the first time we deltas between the generator itself and its usage within a blueprint...

**Comment by danielpetisme** [comment]
I've tested
```
options.plugins = [require('prettier-plugin-java')];
```

 🎉 it works (at least with the blueprint)... it would requires further testing with the main generator

**Comment by mshima** [comment]
> I've tested
> 
> ```
> options.plugins = [require('prettier-plugin-java')];
> ```
> 
> 🎉 it works (at least with the blueprint)... it would requires further testing with the main generator

I pretty sure it will work.
I looked at prettier source an it uses a custom loader strategy, just like yeoman-environment.
By default it looks for plugins at same level hierarchy.
We have to register it to fix this issue.

**Comment by clementdessoude** [comment]
Thank you for having taken a look at this, @mshima !

**Comment by mshima** [comment]
@danielpetisme can you test if https://github.com/jhipster/generator-jhipster/pull/11567 fixes this problem?

**Comment by danielpetisme** [comment]
Ok will do.

Le jeu. 9 avr. 2020 à 18:30, Marcelo Shima <notifications@github.com> a
écrit :
