### ISSUE TITLE
Add `prettier-plugin-java` by default in the generated project

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#11534]
##### **Overview of the feature request**

The idea is to add the `prettier-plugin-java` dependency on the server side.
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/package.json.ejs

##### **Motivation for or Use Case**

I see the java plugin used during the generation, I can see [`.prettierrc`](https://github.com/jhipster/generator-jhipster/blob/master/generators/common/templates/.prettierrc.ejs#L15) udpated to take the java plugin in consideration but I don't see the generated application actually using it... Feel strange...

Is there a reason to not include it now?

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@danielpetisme If You agree I will then close this ticket, there is already #10641 to activate it by default in v7.

**Comment by pascalgrimaud** [comment]
@danielpetisme : FYI, that's what I already did in my generator-jhipster fork for my customer, as the team decide to not include prettier-java in main generator-jhipster by default and as we don't want to start the v7 yet.

What it could be done without impact:
- add the `prettier-plugin-java` dependency on the server side
- no hook with auto prettier format for java file. Only for the other: md,json,ts,tsx,scss,css,yml
- add a new script in `package.json`:

```
    "prettier:java": "prettier --write \"{,src/**/}*.java\" --plugin=./node_modules/prettier-plugin-java",
    "prettier:java:watch": "onchange '**/*.java' -- prettier --write {{changed}} --plugin=./node_modules/prettier-plugin-java",
    "prettier:java:check": "prettier --check \"{,src/**/}*.java\" --plugin=./node_modules/prettier-plugin-java"
```
