### ISSUE TITLE
[Feature] Add inheritance mapping to the entity sub-generator

### ISSUE THREAD

**Issue by nezuvian** [jhipster/generator-jhipster#1153]
I use inheritance mapping extensively for a project, it would definitely come in handy if I could generate the mappings. I guess this wouldn't be a small feature, so I would happily volunteer to help.

**Comment by jdubois** [comment]
We have a PR waiting for this, can you have a look at it?
I will probably break it when I merge our Cassandra branch
I would love to have it but it's going to be difficult
