### ISSUE TITLE
What is the liquibase-maven-plugin used for ?

### ISSUE THREAD

**Issue by kbjp** [jhipster/generator-jhipster#1154]
Hi,
Would it be possible that someone explains what the liquibase-maven-plugin is used for ?
If I correctly remember, in JHipster version 1.X, the database schema was just built/updated at application start.
I have a hard-time figuring out why we now need that plugin (Tests ?).
Thank you very much in advance for your feedback.
Regards
kb

**Comment by gmarziou** [comment]
Please read the documentation: http://jhipster.github.io/development.html
Database updates with the Maven liquibase:diff goal

**Comment by kbjp** [comment]
I handle Jhipster the same way as my new TV: push all the buttons, ask around, and if everything else fails, read the manual ! :-)
Thank Gael...maybe I should read the doco ! :-)
Kb

**Comment by gmarziou** [comment]
Then maybe you should close your issue :)
