### ISSUE TITLE
Intellij and protractor tsconfig

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#11556]
##### **Overview of the issue**

When you try running tests using protractor from intellij it fails saying:
```
error TS5058: The specified path does not exist: '<MY_PROJECT_PATH>/src/test/javascript/tsconfig.e2e.json'.
```

intellij tries find the ts config specified in protractor:
```
    beforeLaunch: function() {
        require('ts-node').register({
            project: 'tsconfig.e2e.json'
        });
    },
```
near the protractor.conf.js path (since it reads a relative path).

this used work in previous versions before moving tsconfig.e2e.json/tsconfig-aot.json to the root od the project.

now if you use the relative path `npm run e2e` works (since run for the root of the project).
and if you change to `../../../tsconfig.e2e.json` intellij work (since it run form the protractor.conf.js) location but npm stops working.
Any idea on hos to fix this please?
Moving the aot config is not an option anymore as it's used in dev with angular9.

Note: maybe this can be fixes in the generated code, and intellij could be tweacked to make it work, and this should be added to the tips and tricks Intellij, so I'm still posting it here as I suspect others will be facing the same problem and will look here the same way i did.

##### **Motivation for or Use Case**

Run and Debug protractor tests with idea.

##### **Reproduce the error**

just tryt to run the tests with intellij

##### **JHipster Version(s)**

6.8.0

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
I've added this to the tips section in our documentation. I hope this will help people who use IntelliJ IDEA. Let me know if you guys see any issues or if any alteration is needed. :smile:

**Comment by yelhouti** [comment]
I think we could call a function that looks for the tsconfig, but hey, my work around works too XD, the only problem I have with it is that people tend to forget and commit these changes...

**Comment by SudharakaP** [comment]
@yelhouti : Do you mean altering the `jhipster-generator` so that each generated project will have a function which looks for tsconfig?
