### ISSUE TITLE
Metrics page broken for react Monolith

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11561]
##### **Overview of the issue**
/admin/metrics page shows error:
![Bildschirmfoto 2020-04-08 um 16 18 34](https://user-images.githubusercontent.com/4540661/78794930-a48d0180-79b4-11ea-9d0f-b2b9285a98e4.png)

in console:
![Bildschirmfoto 2020-04-08 um 16 19 22](https://user-images.githubusercontent.com/4540661/78794993-ba9ac200-79b4-11ea-8bd1-d228a25389ca.png)

##### **JHipster Version(s)**
6.8

##### **JHipster configuration**
no jdl imported yet

.yo-rc.json
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "..."
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "veri",
    "packageName": "...",
    "packageFolder": "...",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "...",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1586208446028,
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": ["en", "de"],
    "blueprints": [],
    "searchEngine": false
  }
}

```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I confirm the issue.
Adding a bounty as it's a bug and needed to be fixed for the next release

**Comment by SudharakaP** [comment]
I'll take a look at this one. :thinking:

**Comment by qmonmert** [comment]
@SudharakaP I think there is a link with this commit https://github.com/jhipster/react-jhipster/commit/aaacc2633473e101b73506e758d20edb1e3701b2

**Comment by SudharakaP** [comment]
I've submitted the PR. This comes form `react-jhipster` which uses the [NumeralJS](https://github.com/adamwdraper/Numeral-js) library. As of 2.0.0, NumeralJS needs that the user [loads the locales separately](https://github.com/adamwdraper/Numeral-js#200) one by one. 

I couldn't' find an elegant method to dynamically load the locales using typescript. The easier fix is to import all locales. 

References: https://github.com/adamwdraper/Numeral-js/issues/548 and https://github.com/adamwdraper/Numeral-js/issues/555.
