### ISSUE TITLE
Cache-Control from CachingHttpHeadersFilter overwritten by WebMvcAutoConfiguration

### ISSUE THREAD

**Issue by DRoppelt** [jhipster/generator-jhipster#11575]
It seems that Cache-Control Headers added by `io.github.jhipster.web.filter.CachingHttpHeadersFilter` are just overwritten/discarded due to SpringMvcAutoConfig.

Not sure if I am not seeing something, but 6.8.0, 6.7.1 and 6.6.0 show this behaviour.

##### **Overview of the issue**

Any config/added "Cache-Control" by following block in `WebConfigurer` 

```
 @Override
    public void onStartup(ServletContext servletContext) throws ServletException {
        ...
        if (env.acceptsProfiles(Profiles.of(JHipsterConstants.SPRING_PROFILE_PRODUCTION))) {
            initCachingHttpHeadersFilter(servletContext, disps);
        }
       ...
    }
```

Following this method call:

```

    private void initCachingHttpHeadersFilter(ServletContext servletContext,
                                              EnumSet<DispatcherType> disps) {
        log.debug("Registering Caching HTTP Headers Filter");
        FilterRegistration.Dynamic cachingHttpHeadersFilter =
            servletContext.addFilter("cachingHttpHeadersFilter",
                new CachingHttpHeadersFilter(jHipsterProperties));

        cachingHttpHeadersFilter.addMappingForUrlPatterns(disps, true, "/i18n/*");
        cachingHttpHeadersFilter.addMappingForUrlPatterns(disps, true, "/content/*");
        cachingHttpHeadersFilter.addMappingForUrlPatterns(disps, true, "/app/*");
        cachingHttpHeadersFilter.setAsyncSupported(true);
    }
```

**Is not affecting cached resources in "prod" at all.**

Assets will still have `Cache-Control: no-store`.

It seems that the filter itself works, but `WebMvcAutoConfiguration` will set its own cache-strategy here:

```
@Override
public void addResourceHandlers(ResourceHandlerRegistry registry) {
...
customizeResourceHandlerRegistration(registry.addResourceHandler(staticPathPattern)
		.addResourceLocations(getResourceLocations(this.resourceProperties.getStaticLocations()))
		.setCachePeriod(getSeconds(cachePeriod)).setCacheControl(cacheControl));
```

And then override any cache headers when serving static content.

##### **Motivation for or Use Case**

`CachingHttpHeadersFilter` cannot be used, any sign of "if in PRD, following assets are cached" is wrong.

##### **Reproduce the error**

* Use a blank JHipster project configured as monolith.

* add code "if(true||" to the if around "com.mycompany.myapp.config.WebConfigurer#initCachingHttpHeadersFilter(..)">

* add 
```
jhipster:
  http:
    cache: # Used by the CachingHttpHeadersFilter
      timeToLiveInDays: 1461
``` 
to `application.yml` to enable this setting on all env.

* start mvnw
```
$ ./mvnw
....
----------------------------------------------------------
        Application 'testFreshJhipster' is running! Access URLs:
        Local:          http://localhost:8080/
        External:       http://192.168.178.40:8080/
        Profile(s):     [dev, swagger]
----------------------------------------------------------
```

* Open website on `localhost:8080`

* Inspect response-headers of js/css `/app/*`

* see that it still says `Cache-Control: no-store`

```

http://localhost:8080/app/main.bundle.js

HTTP/1.1 200 OK
Expires: 
Cache-Control: no-store
Pragma: 
Accept-Ranges: bytes
Date: Sat, 11 Apr 2020 18:31:59 GMT
Connection: keep-alive
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Last-Modified: Sat, 11 Apr 2020 18:01:09 GMT
Content-Length: 10454712
Content-Type: application/javascript
```

I am not sure whenthis was introcued. I can reproduce this with 6.8.0, 6.7.1, 6.6.0

##### **Suggest a Fix**

I have been debugging this for a while and not come up with a solution yet.

So far I found out that:

* `spring.resources.chain.period: -1s` will disable the caching, so that the headers are not overwritten
  * but then **no** resources at all receive any cache-headers.
* `spring.resources.chain.period: 1s` will change it from "no-store" to "1". But still override it.

The code to set headers will probably either have to follow this pattern:

```
@Configuration
public class HttpCacheControlConfiguration implements WebMvcConfigurer {

    @Autowired
    private ResourceProperties resourceProperties;


    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {

        registry.addResourceHandler("/app/**")
            .addResourceLocations(resourceProperties.getStaticLocations())
            .setCachePeriod(12222);

    }
}

```
(altough I have not got it to work yet, assets in /app hit a 404)

Or the `CachingHttpHeadersFilter` has to filter **after** whatever Spring MVC is doing with the headers.

##### **JHipster Version(s)**

```
test-fresh-jhipster@0.0.1-SNAPSHOT C:\projects\xxx\testFreshJhipster
`-- generator-jhipster@6.8.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "testFreshJhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1586613662092,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

git version 2.25.0.windows.1

node: v12.15.0

npm: 6.14.4

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.4, build 8d51620a

##### **Browsers and Operating System**

Firefox 75 & Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DRoppelt** [comment]
So I tried to investigate this approach:

> Or the CachingHttpHeadersFilter has to filter after whatever Spring MVC is doing with the headers.

But it seems that Spring MVC sets their cache Headers after all filteres have been passed. And adding/changing headers after the controller processed the request (post-filter over pre-filter), does not work. See here https://mtyurt.net/post/spring-modify-response-headers-after-processing.html

Based on this article, I have come up with following approach, but it feels too hacky.

```
        //... add cache filters
        HttpServletResponseWrapper wrapper = new HttpServletResponseWrapper(httpResponse) {
            @Override
            public void setHeader(String name, String value) {
                if(Arrays.asList("Cache-Control", "Pragma", "Expires").contains(name)) {
                    log.trace("Overrule reset of cache control setting [{}]->[{}] on [{}]. Skipping",
                        name, value, httpRequest.getRequestURI());
                    return;
                }
                super.setHeader(name, value);
            }
        };
        chain.doFilter(req, wrapper);
```

This wrapper will simply skip any changes to the headers that were set previously.

**Comment by cbornet** [comment]
I remember having the same kind of problem with Webflux. Maybe the way it's done with WebFlux can also be used for MVC.

**Comment by pascalgrimaud** [comment]
Just changed the label to `bug` as it has been confirmed
Added a bounty too, as it's a bug and needed to be fixed before the next release

**Comment by pascalgrimaud** [comment]
Increasing the bounty as it requires more work than expected and needs some change in vue.js blueprint too. Otherwise, the Vue.js part won't work well with the next release of generator-jhipster

**Comment by monxxi** [comment]
here the related issue on the blueprint vuejs 
jhipster/jhipster-vuejs#599

I've created the PR (https://github.com/jhipster/jhipster-vuejs/pull/603), but if someone can review it and give me some feedback, they will be welcome

**Comment by pascalgrimaud** [comment]
@monxxi : thanks, I'll review the PR on Vue.js blueprint soon
