### ISSUE TITLE
Neo4J with OAuth option not working, UserService incompatible.

### ISSUE THREAD

**Issue by jhighman** [jhipster/generator-jhipster#11574]
I can generate the application with JWT and verify it.  When I choose the OAuth2 option, it generates compile time errors in the user service.

##### **JHipster Version(s)**

6.8.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.test"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "test",
    "packageName": "io.test",
    "packageFolder": "io/test",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "neo4j",
    "devDatabaseType": "neo4j",
    "prodDatabaseType": "neo4j",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "journal",
    "clientThemeVariant": "light",
    "creationTimestamp": 1586628278284,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities.

**Comment by pascalgrimaud** [comment]
It's strange that Neo4j + JWT works for you, it shouldn't as I already saw an issue with this, about Integration Tests.
Anyway, you're probably right for OAuth2.

Don't forget Neo4j is still in beta, if you know how to fix it, your help is really welcome.

cc @atomfrede

**Comment by atomfrede** [comment]
Will check. Jwt works fine. We also tried oauth. Currently working on a performance issue for certain jdl models.

**Comment by pascalgrimaud** [comment]
@atomfrede : not sure about Jwt+Neo4j, the last time I tried, `mvn verify` failed

**Comment by atomfrede** [comment]
Ah one of the tests. I thought we fixed it already. Will have look over the weekend

**Comment by jhighman** [comment]
There are two issues, here are the fixes:
Change the line:
`        user.setAuthorities(authToken.getAuthorities().stream()
            .map(GrantedAuthority::getAuthority)
            .collect(Collectors.toSet()));
`
to this:

`        user.setAuthorities(authToken.getAuthorities().stream()
                .map(GrantedAuthority::getAuthority)
                .map(authority -> {
                    Authority auth = new Authority();
                    auth.setName(authority);
                    return auth;
                })
                .collect(Collectors.toSet()));`

The other issue is to add a fifth parameter to the update user method to include the imageUrl:
`dateUser(String firstName, String lastName, String email, String langKey, String imageUrl) `
also add a set statement:
`user.setImageUrl(imageUrl);`

I tested this and it works.

**Comment by mraible** [comment]
@jhighman I made these changes in this PR: https://github.com/jhipster/generator-jhipster/pull/11571

**Comment by atomfrede** [comment]
So the oauth probhlem is fixed with your PR @mraible (and not related to neo)?

**Comment by mraible** [comment]
Yes, but not all tests are passing with my PR. When they do, I think we can move WebFlux to beta.

**Comment by mraible** [comment]
I'm closing this because I believe it's fixed.
