### ISSUE TITLE
add "enum with payload" feature

### ISSUE THREAD

**Issue by 62mkv** [jhipster/generator-jhipster#11586]
##### **Overview of the feature request**

I want to be able to define (via JDL) and generate Java/JS models for enums *with payload*. 

The suggested syntax is: 
```
enum [<enum name>] [ payload <type>] {
  <ENUM KEY> ([<enum value>])
}
```
where `payload` is a binary option for an enum, with any valid JDL type name as a value

With enum defined as 
```
enum ProcessingStatus payload String {
    IN_PROGRESS("In progress"),
    SUCCESS("Success"),
    FAIL("Fail"),
    UNDEFINED("Undefined");
}
```

I would expect to achieve
```
public enum ProcessingStatus {
    IN_PROGRESS("In progress"),
    SUCCESS("Success"),
    FAIL("Fail"),
    UNDEFINED("Undefined");

    private String value;

    ProcessingStatus(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
```

##### **Motivation for or Use Case**

Nearly all of enums in my recent projects have some kind of "payload" (mostly String), so support for this case in JHipster would be really helpful

##### **Related issues or PR**

this issue: https://github.com/jhipster/jhipster-core/issues/357
was supposed to give *exactly* discussed functionality but was completely differently understood and somehow implemented. 

Here https://github.com/jhipster/jhipster-core/issues/459 I was asked to create an issue, which is what I am doing here

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
What is a payload? Not sure I get it as I should

**Comment by 62mkv** [comment]
By "payload" I mean that an element of an enum will have some value ("payload") attached to it, as opposed to "regular" enum which will have not any additional value attached

**Comment by 62mkv** [comment]
Feel free to modify the proposed syntax, of course!

**Comment by MathieuAA** [comment]
Inferring the type is possible without keyword. We can leverage the syntax:
  - anything between double quotes is considered a string (speaking in JCore v8 terms)
  - an int is an int, and shouldn't be between quotes

**Comment by MathieuAA** [comment]
Sorry if I'm confusing, I still have the ideas for JCore v8 in my head

**Comment by 62mkv** [comment]
I'm fine with that. What with currently existing support for unquoted value? How that will be interpreted as a "payload"?

**Comment by MathieuAA** [comment]
An idea I proposed in https://github.com/jhipster/jhipster-core/issues/459 is to deprecate them.

**Comment by MathieuAA** [comment]
I'm closing this one, as I believe the core topic here was specifying the type of a custom enum value. If anyone wants to add support for integers, or booleans (or other types) then this can be discussed in a new issue.
