### ISSUE TITLE
Java code with enums with custom values don't compile

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#11587]
##### **Overview of the issue** & **reproduction**

When importing such a JDL content:
```
entity MyEntity {
  myField MyEnum
}

enum MyEnum {
  AAA(aaa),
  BBB(bbb)
}
```

The Java code won't accept the custom values because they are generated (didn't seem so before, but anyway...).

##### **Motivation for or Use Case**

Generated code should compile.

##### **Reproduce the error**

Generate an app with
```
application
  config {
    baseName testWithEnums
  }}

entity MyEntity {
  myField MyEnum
}

enum MyEnum {
  AAA(aaa),
  BBB(bbb)
}
```

Check the generated enum, you should see it doesn't compile.

##### **Related issues**

Don't think so. Related to https://github.com/jhipster/jhipster-core/issues/459.

##### **Suggest a Fix**

#11588

##### **JHipster Version(s)**

master

##### **JHipster configuration**

```
application
  config {
    baseName testWithEnums
  }}

entity MyEntity {
  myField MyEnum
}

enum MyEnum {
  AAA(aaa),
  BBB(bbb)
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Just generate an app with the provided JDL, it should do the trick.

##### **Browsers and Operating System**

Irrelevant.

**Comment by aLeXcBa1990** [comment]
Do you think that multiple values can be supported?
https://www.baeldung.com/java-enum-values#multiple-values

**Comment by MathieuAA** [comment]
For now, it's just a fix to properly support strings. Java allows a lot more things and we shouldn't keep up with everything it does, so I don't know.

**Comment by aLeXcBa1990** [comment]
Ok I understand I hope I can help with that sometime

**Comment by pascalgrimaud** [comment]
Incrementing the bounty as it's more work than expected
