### ISSUE TITLE
Refactor JDL Sections in Documentation

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#11596]
##### **Overview of the issue**

Our documentation has 5 sections with the same title; `JHipster Domain Language (JDL)`. I find this confusing. When we type JDL in the search bar we get all of these 5 results; 

![image](https://user-images.githubusercontent.com/12435965/79680022-dfb2e000-81bf-11ea-8ad6-915a2eb7c8c0.png)

I suggest refactor the documentation such that these sections become subsections within the JDL section which can be navigated through the left hand side-bar. 

![image](https://user-images.githubusercontent.com/12435965/79680039-18eb5000-81c0-11ea-9057-3f58ca0d0d98.png)

Let me know what you guys thing. I can make the changes if things are in agreement. :smile: 

##### **Motivation for or Use Case**

Making the JDL sections more easily found within the documentation and make them accessible via a central point.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
@SudharakaP Please do!

**Comment by SudharakaP** [comment]
I've done some minor refactoring to the headings so that when they appear on the search it's easier to know which section. Also I've removed the Atom IDE (https://atom.io/packages/ide-jhipster) from the JDL page since it's deprecated and I don't think it could be installed anymore (GitHub repo missing). :smile:

**Comment by MathieuAA** [comment]
Thanks again @SudharakaP!

**Comment by SudharakaP** [comment]
You are welcome. 😄
