### ISSUE TITLE
v7 - remove serviceClass generation

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#11590]
##### **Overview of the feature request**

As of today, we have serviceClass and serviceImpl generation available.
serviceImpl looks to be the best option, which is compliant with modulith, bounded context, side by side and friends.
Also, it's not a big overhead for the end user and can even be simplified
```

@MyEntity
public interface MyEntityService extends CrudService<MyEntity> {}

```
##### **Motivation for or Use Case**

Simplifying the generator.
generators more easy to maintain

##### **Related issues or PR**

#10958

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
We don't have any issue since years about this. No issue, no maintenance to do on this part.
Both (serviceClass and serviceImpl) works very well, I'd prefer to keep both options, so the end user will have the choice.

**Comment by Tcharl** [comment]
It's always better to have the choice written :-).

Thank you @pascalgrimaud @murdos
