### ISSUE TITLE
Re-enable BlockHound once blocking calls are fixed

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#11599]
##### **Overview of the feature request**

BlockHound has been added in https://github.com/jhipster/generator-jhipster/pull/11009 but it has unveiled some blocking calls in frameworks that we're using and thus our CI tests have become very unstable since.
I plan to temporarily disable BlockHound in order to have trustable integration tests again, but we should re-enable it once the blocking calls are resolved.

**Comment by mraible** [comment]
We should create a PR that re-enables BlockHound. That way, we can run CI on it periodically to see if the issues are fixed.

**Comment by mraible** [comment]
@murdos Have you had a chance to re-examine this?

**Comment by cbornet** [comment]
See https://github.com/jhipster/generator-jhipster/pull/11791 . There's an issue open on reactor but it seems nobody is working on it. So we should probably do the workaround.

**Comment by mraible** [comment]
+1 for the workaround. It sucks, but it's often the best way. ☺️

**Comment by murdos** [comment]
I've a branch for re-enabling BlockHound with some white-listing: https://github.com/murdos/generator-jhipster/tree/enable-blockhound

I'll wait for webflux builds to be fixed (probably with https://github.com/jhipster/generator-jhipster/pull/12688) to be able to do more tests and create the PR.

**Comment by murdos** [comment]
PR exists and is waiting for approval

**Comment by Tcharl** [comment]
It is, isn't it?

**Comment by mraible** [comment]
@Tcharl Yes, I see a `JHipsterBlockHoundIntegration` class in a JHipster 7.6 project.

**Comment by Tcharl** [comment]
Closing so
