### ISSUE TITLE
JHipster 6 hangs on import-jdl then continues after 3-5 Minutes

### ISSUE THREAD

**Issue by tillias** [jhipster/generator-jhipster#11617]
##### **Overview of the issue**

When starting jdl import there is big delay / hang

##### **Motivation for or Use Case**
It just shows "Using JHipster version installed globally" and hangs, not clear if this is because of proxy stuff, or connectivity or performance etc
>jhipster import-jdl my.jdl
INFO! Using JHipster version installed globally
-> Here it hangs 3-5 Minutes
INFO! Executing import-jdl my.jdl
INFO! Options: from-cli: true, inline: 
INFO! Found .yo-rc.json on path. This is an existing app
INFO! The JDL is being parsed.
INFO! Found entities: MyEntity.
INFO! The JDL has been successfully parsed
INFO! Generating 1 entity.

##### **Reproduce the error**

Follow official tutorial for any new jhipster app

##### **Suggest a Fix**

Is it possible to enable tracing? Perhaps there are some additional steps between those two:
Step1: INFO! Using JHipster version installed globally

Step2: INFO! Executing import-jdl my.jdl

OS: Win10 64bit node: 12.16.2 npm: 6.14.4

**Comment by tillias** [comment]
I have also checked and it seems this behaviour is same for all jhipster commands: https://stackoverflow.com/questions/61361341/jhipster-hangs-for-every-command

**Comment by mshima** [comment]
I am working on it.

**Comment by mshima** [comment]
What version of jhipster are you running?

**Comment by tillias** [comment]
I have installed it yesterday, it says "generator-jhipster": "6.8.0"

**Comment by mshima** [comment]
Run and post the output.
```
DEBUG=yeoman:* jhipster import-jdl my.jdl
```

**Comment by MathieuAA** [comment]
@tillias please provide a complete issue template (OS, etc.)

**Comment by tillias** [comment]
There are following entries:
```
  yeoman:environment found C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/openshift/index.js, trying to register +2ms
  yeoman:environment Registered jhipster:openshift (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster\generators\openshift\index.js) on package jhipster (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster) +5ms
  yeoman:environment Resolve namespaces for C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/server/index.js: jhipster:server +1ms
  yeoman:environment found C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/server/index.js, trying to register +6ms
  yeoman:environment Registered jhipster:server (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster\generators\server\index.js) on package jhipster (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster) +1ms
  yeoman:environment Resolve namespaces for C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/spring-controller/index.js: jhipster:spring-controller +1ms
  yeoman:environment found C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/spring-controller/index.js, trying to register +2ms
  yeoman:environment Registered jhipster:spring-controller (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster\generators\spring-controller\index.js) on package jhipster (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster) +2ms
  yeoman:environment Resolve namespaces for C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/spring-service/index.js: jhipster:spring-service +0ms
  yeoman:environment found C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/spring-service/index.js, trying to register +2ms
  yeoman:environment Registered jhipster:spring-service (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster\generators\spring-service\index.js) on package jhipster (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster) +2ms
  yeoman:environment Resolve namespaces for C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/upgrade/index.js: jhipster:upgrade +0ms
  yeoman:environment found C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/upgrade/index.js, trying to register +2ms
  yeoman:environment Registered jhipster:upgrade (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster\generators\upgrade\index.js) on package jhipster (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster) +2ms
  yeoman:environment Resolve namespaces for C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/upgrade-config/index.js: jhipster:upgrade-config +6ms
  yeoman:environment found C:/Users/ilternov/AppData/Roaming/npm/node_modules/generator-jhipster/generators/upgrade-config/index.js, trying to register +8ms
  yeoman:environment Registered jhipster:upgrade-config (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster\generators\upgrade-config\index.js) on package jhipster (C:\Users\ilternov\AppData\Roaming\npm\node_modules\generator-jhipster) +1ms
```

After the last one it is hanging. Possibly few more entries will appear, will post in separate comment

**Comment by tillias** [comment]
After few minutes there is following appended:
```
 yeoman:environment Running lookup with options { filterPaths: true, packagePatterns: [], filePatterns: [ '*\\index.js', 'generators\\*\\index.js', 'lib\\g
enerators\\*\\index.js' ], npmPaths: [ 'C:\\Users\\myuser\\AppData\\Roaming\\npm\\node_modules\\generator-jhipster\\node_modules', 'C:\\Users\\myuser\\A
ppData\\Roaming\\npm\\node_modules', 'C:\\node_modules', 'C:\\tmp\\node_modules' ], packagePaths: [] } +3m
version is not a known command. See 'jhipster --help'.
```

I have issues jhipster version command

**Comment by tillias** [comment]
> @tillias please provide a complete issue template (OS, etc.)
I can't post full details, I'm in work / enterprise environment with sensitive data... I have already posted OS, version etc. Please let me know if you need something concrete so I can obfuscate sensitive data

**Comment by mshima** [comment]
This is a problem with yeoman-environment's lookup with network mounted paths.
But shouldn’t happen without blueprint.
I will provide a fix to master.
You can try generator-jhipster@6.7.1, I think it’s not affected by this problem.

**Comment by tillias** [comment]
Thank you very much, testing right now. Is it enough to issue
`npm install -g generator-jhipster@6.7.1`
or additional work is needed?

**Comment by mshima** [comment]
Should be.
Maybe you need to remove generator-jhipster from local repository.
`rm -rf node_modules/generator-jhipster`

**Comment by tillias** [comment]
@mshima checked on private PC in the meantime, 6.7.1 works fast, no delay as 6.8.0

**Comment by mshima** [comment]
On the private pc 6.8.0 should work fast too. Unless there are mounted network file systems.

**Comment by mshima** [comment]
> It seems npm now ignores my .npmrc (with corporate proxy) for some reason and installation of 6.7.1 is not working -> related to [yeoman/yo#589](https://github.com/yeoman/yo/issues/589)
> 
> ```
>     at Object.onceWrapper (events.js:417:26)
>     at ClientRequest.emit (events.js:310:20)
>     at ClientRequest.EventEmitter.emit (domain.js:482:12)
>     at TLSSocket.socketErrorListener (_http_client.js:426:9)
>     at TLSSocket.emit (events.js:310:20)
>     at TLSSocket.EventEmitter.emit (domain.js:482:12)
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   code: 'ETIMEDOUT',
>   message: 'connect ETIMEDOUT 104.16.27.35:443',
>   host: 'registry.npmjs.org',
>   hostname: 'registry.npmjs.org',
>   method: 'GET',
>   path: '/yo'
> ```
> 
> Update: 6.8.0 installation works fine with .npmrc
> 
> ```
> + generator-jhipster@6.8.0
> added 586 packages from 458 contributors in 91.913s
> ```
> 
> I will have to use private laptop after work to test the whole ticket from the very beginning

jhipster 6.7.1 used yo for some operations.
jhipster 6.8.0 we removed yo dependency completely.
