### ISSUE TITLE
Make joda time optional

### ISSUE THREAD

**Issue by xvitcoder** [jhipster/generator-jhipster#1161]
It would be nice to have the usage of joda-time optional, cause not everybody use it.

**Comment by rasheedamir** [comment]
For Java 8 it can be made optional but what alternatives do we have for joda time before Java 8?

**Comment by gzsombor** [comment]
This is a duplicate of https://github.com/jhipster/generator-jhipster/issues/1161

**Comment by jdubois** [comment]
Yes this is a duplicate

**Comment by xvitcoder** [comment]
Yes, it could be done alternatives just for Java 8, as most of us use Java 8. If Java 7 s selected then the option for using joda-time can be skipped.
