### ISSUE TITLE
Add 'text' type in the entity subgenerator

### ISSUE THREAD

**Issue by xvitcoder** [jhipster/generator-jhipster#1162]
It would be nice to have more entity field types in the entity subgenerator like 'text', 'blob'.

**Comment by jdubois** [comment]
There is already String.
And yes it's always good to have more.

**Comment by gmarziou** [comment]
I think that there should be some difference in generator between backend type (e.g. string) and frontend type (text, textarea, url, e-mail, ...) which implies different presentation and validation.

**Comment by jdubois** [comment]
Yes, but at the moment we use the Java types, because we have differences between database types, front end types, etc. So we need one way to "standardize" them
