### ISSUE TITLE
java.net.UnknownHostException: fastdl.mongodb.org when running integration tests behind proxy

### ISSUE THREAD

**Issue by tillias** [jhipster/generator-jhipster#11628]
##### **Overview of the issue**

This happens on every build behind proxy. Please see attached log

##### **Motivation for or Use Case**

Because our Corporate Jenkins works behind proxy as in many other organizations

##### **Reproduce the error**

Start build of any (also sample) jhipster generated project in Jenkins behind proxy. 

##### **Suggest a Fix**

For some reason dependencies other than this particular mognodb one are resolved correctly by using proxy specified in maven settings.xml on target build server. Some people mention this fix https://stackoverflow.com/questions/30388917/junit-test-cases-using-embed-mongodb-de-flapdoodle-embed-mongo but I can't find this code inside sample project

##### **JHipster Version(s)**

6.7.1

##### **JHipster configuration**

Since this happens with any project, there is no specific information here

##### **Browsers and Operating System**

Window 10 64bit

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Plz provide all information asked in template, with your config.

Then, I'm not sure we can do something as it seems related to your proxy.
Maybe a solution would be to use testcontainers.

**Comment by tillias** [comment]
This is related to _fastdl.mongodb.org_ dependency itself. It doesn't take into account proxy settings, thus they ask to use following configuration:

```
Command command = Command.MongoD;

IRuntimeConfig runtimeConfig = new RuntimeConfigBuilder()
        .defaults(command)
        .artifactStore(new ArtifactStoreBuilder()
                .defaults(command)
                .download(new DownloadConfigBuilder()
                        .defaultsForCommand(command)
                        .proxyFactory(new HttpProxyFactory("proxy_host", 8080))))
        .build();

 MongodStarter starter = MongodStarter.getInstance(runtimeConfig);
```

Unfortunately I can't find any hint how to make this adjustment in JHipster generated project. So solution may be:

1. Adjust generator so there is additional service available in new project
2. User can edit "proxy_host" 

At the moment I can't find any code block which is responsible for such a configuration

**Comment by pascalgrimaud** [comment]
Not sure we can do something in generator-jhipster, you should have a look directly at fastdl.mongodb.org dependency directly, as you mentioned yourself

And as it's related to a proxy, the problem comes from there.
As it's not a JHipster bug and as it's impossible for us to reproduce, I'm closing this

**Comment by tillias** [comment]
Well, you can at least provide documentation how to extend stuff generated by jhipster as I mentioned before. But if you think doing nothing is a good idea, sure close it
