### ISSUE TITLE
Use linked generator

### ISSUE THREAD

**Issue by darklyjohn** [jhipster/generator-jhipster#11630]
##### **Overview of the issue**
I'm trying to run jhipster-generator by using the dev setup. I linked a cloned jhipster-generator. 
But when I try to run "jhipster" command no way it's not working. But when I use "yo" and select the jhipster generator it is working.

##### **Motivation for or Use Case**
>jhipster
INFO! Using JHipster version installed globally
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: from-cli: true
Error: You don't seem to have a generator with the name “jhipster:app” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-jhipster:app.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
    at Environment.create (C:\GitProjects\jhipster-generator\node_modules\yeoman-environment\lib\environment.js:622:9)
    at Environment.run (C:\GitProjects\jhipster-generator\node_modules\yeoman-environment\lib\environment.js:725:28)
    at runYoCommand (C:\GitProjects\jhipster-generator\cli\cli.js:69:13)
    at Object.<anonymous> (C:\GitProjects\jhipster-generator\cli\cli.js:127:5)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)

-----------------------------------------------------------------
With yo : 

yo
? 'Allo jnn-tri! What would you like to do? Jhipster

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo jhipster

WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.8.0
Application files will be generated in folder: C:

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Follows the guide at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup to do your dev setup.
If you still have the issue after trying, tell us more about how to reproduce it.

**Comment by darklyjohn** [comment]
@pmverma I followed this guide. So I cloned the current jhipster-generator  from github. Then I use 

`C:\GitProjects\jhipster-generator>npm link
audited 11291 packages in 4.559s

10 packages are looking for funding
  run `npm fund` for details

found 190 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
C:\npm\jhipster -> C:\npm\node_modules\generator-jhipster\cli\jhipster.js
C:\npm\node_modules\generator-jhipster -> C:\GitProjects\jhipster-generator`

then 

`C:\GitProjects\jhipster-generator>cd ..

C:\GitProjects>cd generateAppWithLinkedGenerator

C:\GitProjects\generateAppWithLinkedGenerator>jhipster
INFO! Using JHipster version installed globally
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: from-cli: true
Error: You don't seem to have a generator with the name “jhipster:app” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-jhipster:app.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
    at Environment.create (C:\GitProjects\jhipster-generator\node_modules\yeoman-environment\lib\environment.js:622:9)
    at Environment.run (C:\GitProjects\jhipster-generator\node_modules\yeoman-environment\lib\environment.js:725:28)
    at runYoCommand (C:\GitProjects\jhipster-generator\cli\cli.js:69:13)
    at Object.<anonymous> (C:\GitProjects\jhipster-generator\cli\cli.js:127:5)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)

C:\GitProjects\generateAppWithLinkedGenerator>`

And finally If I run 

`C:\GitProjects\generateAppWithLinkedGenerator>yo
? 'Allo jnn-tri! What would you like to do? Jhipster

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo jhipster

WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.8.0
Application files will be generated in folder: C:\GitProjects\generateAppWithLinkedGenerator
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

? Which *type* of application would you like to create? (Use arrow keys)
> Monolithic application (recommended for simple projects) TEST jnn
  Microservice application
  Microservice gateway
  JHipster UAA server`

and you can see I made a 'little' change by add "TEST jnn" in the code to check if the generator run is well the cloned generator.

Maybe I missed something ?

**Comment by mshima** [comment]
Run
```
DEBUG=yeoman:* jhipster
```

Post the log.

**Comment by darklyjohn** [comment]
C:\GitProjects\generateAppWithLinkedGenerator>jhipster
INFO! Using JHipster version installed globally
  yeoman:environment:repository Running npm with args [ 'root', '-g', '--prefix', 'C:\\GitProjects\\generateAppWithLinkedGenerator\\.yo-repository', '--loglevel', 'error' ] +0ms
  yeoman:environment Running lookup with options: { packagePaths: [ 'C:\\GitProjects\\jhipster-generator' ], filePatterns: [ '*\\index.ts', '*\\index.js', 'generators\\*\\index.ts', 'generators\\*\\index.js', 'lib\\generators\\*\\index.ts', 'lib\\generators\\*\\index.js' ], filterPaths: false, packagePatterns: 'generator-*', globbyDeep: 1, reverse: true } +0ms
  yeoman:environment Lookup calculated options: { packagePaths: [ 'C:\\GitProjects\\jhipster-generator' ], filePatterns: [ '*\\index.ts', '*\\index.js', 'generators\\*\\index.ts', 'generators\\*\\index.js', 'lib\\generators\\*\\index.ts', 'lib\\generators\\*\\index.js' ], filterPaths: false, packagePatterns: 'generator-*', globbyDeep: 1, reverse: true } +13ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/app/index.js: C::GitProjects:jhipster-generator:app +0ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/app/index.js, trying to register +190ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:app (C:\GitProjects\jhipster-generator\generators\app\index.js) on package C (C:\GitProjects\jhipster-generator) +3ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/aws/index.js: C::GitProjects:jhipster-generator:aws +1ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/aws/index.js, trying to register +3ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:aws (C:\GitProjects\jhipster-generator\generators\aws\index.js) on package C (C:\GitProjects\jhipster-generator) +1ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/aws-containers/index.js: C::GitProjects:jhipster-generator:aws-containers +1ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/aws-containers/index.js, trying to register +2ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:aws-containers (C:\GitProjects\jhipster-generator\generators\aws-containers\index.js) on package C (C:\GitProjects\jhipster-generator) +2ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/azure-app-service/index.js: C::GitProjects:jhipster-generator:azure-app-service +2ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/azure-app-service/index.js, trying to register +4ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:azure-app-service (C:\GitProjects\jhipster-generator\generators\azure-app-service\index.js) on package C (C:\GitProjects\jhipster-generator) +1ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/azure-spring-cloud/index.js: C::GitProjects:jhipster-generator:azure-spring-cloud +1ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/azure-spring-cloud/index.js, trying to register +2ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:azure-spring-cloud (C:\GitProjects\jhipster-generator\generators\azure-spring-cloud\index.js) on package C (C:\GitProjects\jhipster-generator) +1ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/ci-cd/index.js: C::GitProjects:jhipster-generator:ci-cd +1ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/ci-cd/index.js, trying to register +2ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:ci-cd (C:\GitProjects\jhipster-generator\generators\ci-cd\index.js) on package C (C:\GitProjects\jhipster-generator) +2ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/client/index.js: C::GitProjects:jhipster-generator:client +0ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/client/index.js, trying to register +2ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:client (C:\GitProjects\jhipster-generator\generators\client\index.js) on package C (C:\GitProjects\jhipster-generator) +2ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/cloudfoundry/index.js: C::GitProjects:jhipster-generator:cloudfoundry +0ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/cloudfoundry/index.js, trying to register +2ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:cloudfoundry (C:\GitProjects\jhipster-generator\generators\cloudfoundry\index.js) on package C (C:\GitProjects\jhipster-generator) +2ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/common/index.js: C::GitProjects:jhipster-generator:common +0ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/common/index.js, trying to register +2ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:common (C:\GitProjects\jhipster-generator\generators\common\index.js) on package C (C:\GitProjects\jhipster-generator) +2ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/docker-compose/index.js: C::GitProjects:jhipster-generator:docker-compose +1ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/docker-compose/index.js, trying to register +4ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:docker-compose (C:\GitProjects\jhipster-generator\generators\docker-compose\index.js) on package C (C:\GitProjects\jhipster-generator) +3ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/entity/index.js: C::GitProjects:jhipster-generator:entity +1ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/entity/index.js, trying to register +3ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:entity (C:\GitProjects\jhipster-generator\generators\entity\index.js) on package C (C:\GitProjects\jhipster-generator) +2ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/entity-client/index.js: C::GitProjects:jhipster-generator:entity-client +0ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/entity-client/index.js, trying to register +2ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:entity-client (C:\GitProjects\jhipster-generator\generators\entity-client\index.js) on package C (C:\GitProjects\jhipster-generator) +2ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/entity-i18n/index.js: C::GitProjects:jhipster-generator:entity-i18n +3ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/entity-i18n/index.js, trying to register +7ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:entity-i18n (C:\GitProjects\jhipster-generator\generators\entity-i18n\index.js) on package C (C:\GitProjects\jhipster-generator) +6ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/entity-server/index.js: C::GitProjects:jhipster-generator:entity-server +2ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/entity-server/index.js, trying to register +8ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:entity-server (C:\GitProjects\jhipster-generator\generators\entity-server\index.js) on package C (C:\GitProjects\jhipster-generator) +5ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/export-jdl/index.js: C::GitProjects:jhipster-generator:export-jdl +2ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/export-jdl/index.js, trying to register +6ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:export-jdl (C:\GitProjects\jhipster-generator\generators\export-jdl\index.js) on package C (C:\GitProjects\jhipster-generator) +4ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/gae/index.js: C::GitProjects:jhipster-generator:gae +3ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/gae/index.js, trying to register +7ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:gae (C:\GitProjects\jhipster-generator\generators\gae\index.js) on package C (C:\GitProjects\jhipster-generator) +6ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/heroku/index.js: C::GitProjects:jhipster-generator:heroku +3ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/heroku/index.js, trying to register +11ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:heroku (C:\GitProjects\jhipster-generator\generators\heroku\index.js) on package C (C:\GitProjects\jhipster-generator) +6ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/info/index.js: C::GitProjects:jhipster-generator:info +2ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/info/index.js, trying to register +6ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:info (C:\GitProjects\jhipster-generator\generators\info\index.js) on package C (C:\GitProjects\jhipster-generator) +6ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/kubernetes/index.js: C::GitProjects:jhipster-generator:kubernetes +2ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/kubernetes/index.js, trying to register +8ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:kubernetes (C:\GitProjects\jhipster-generator\generators\kubernetes\index.js) on package C (C:\GitProjects\jhipster-generator) +4ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/kubernetes-helm/index.js: C::GitProjects:jhipster-generator:kubernetes-helm +2ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/kubernetes-helm/index.js, trying to register +7ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:kubernetes-helm (C:\GitProjects\jhipster-generator\generators\kubernetes-helm\index.js) on package C (C:\GitProjects\jhipster-generator) +6ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/kubernetes-knative/index.js: C::GitProjects:jhipster-generator:kubernetes-knative +3ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/kubernetes-knative/index.js, trying to register +8ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:kubernetes-knative (C:\GitProjects\jhipster-generator\generators\kubernetes-knative\index.js) on package C (C:\GitProjects\jhipster-generator) +5ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/languages/index.js: C::GitProjects:jhipster-generator:languages +3ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/languages/index.js, trying to register +11ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:languages (C:\GitProjects\jhipster-generator\generators\languages\index.js) on package C (C:\GitProjects\jhipster-generator) +7ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/openapi-client/index.js: C::GitProjects:jhipster-generator:openapi-client +4ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/openapi-client/index.js, trying to register +8ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:openapi-client (C:\GitProjects\jhipster-generator\generators\openapi-client\index.js) on package C (C:\GitProjects\jhipster-generator) +4ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/openshift/index.js: C::GitProjects:jhipster-generator:openshift +4ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/openshift/index.js, trying to register +9ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:openshift (C:\GitProjects\jhipster-generator\generators\openshift\index.js) on package C (C:\GitProjects\jhipster-generator) +5ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/server/index.js: C::GitProjects:jhipster-generator:server +2ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/server/index.js, trying to register +6ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:server (C:\GitProjects\jhipster-generator\generators\server\index.js) on package C (C:\GitProjects\jhipster-generator) +4ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/spring-controller/index.js: C::GitProjects:jhipster-generator:spring-controller +2ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/spring-controller/index.js, trying to register +7ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:spring-controller (C:\GitProjects\jhipster-generator\generators\spring-controller\index.js) on package C (C:\GitProjects\jhipster-generator) +5ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/spring-service/index.js: C::GitProjects:jhipster-generator:spring-service +2ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/spring-service/index.js, trying to register +6ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:spring-service (C:\GitProjects\jhipster-generator\generators\spring-service\index.js) on package C (C:\GitProjects\jhipster-generator) +4ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/upgrade/index.js: C::GitProjects:jhipster-generator:upgrade +4ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/upgrade/index.js, trying to register +8ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:upgrade (C:\GitProjects\jhipster-generator\generators\upgrade\index.js) on package C (C:\GitProjects\jhipster-generator) +4ms
  yeoman:environment Resolve namespaces for C:/GitProjects/jhipster-generator/generators/upgrade-config/index.js: C::GitProjects:jhipster-generator:upgrade-config +3ms
  yeoman:environment found C:/GitProjects/jhipster-generator/generators/upgrade-config/index.js, trying to register +7ms
  yeoman:environment Registered C::GitProjects:jhipster-generator:upgrade-config (C:\GitProjects\jhipster-generator\generators\upgrade-config\index.js) on package C (C:\GitProjects\jhipster-generator) +4ms
  yeoman:environment Running lookup with options: { filterPaths: true, packagePatterns: [], filePatterns: [ '*\\index.ts', '*\\index.js', 'generators\\*\\index.ts', 'generators\\*\\index.js', 'lib\\generators\\*\\index.ts', 'lib\\generators\\*\\index.js' ], globbyDeep: 1, reverse: true } +4ms
  yeoman:environment Lookup calculated options: { filterPaths: true, packagePatterns: [], filePatterns: [ '*\\index.ts', '*\\index.js', 'generators\\*\\index.ts', 'generators\\*\\index.js', 'lib\\generators\\*\\index.ts', 'lib\\generators\\*\\index.js' ], globbyDeep: 1, reverse: true, npmPaths: [ 'C:\\Users\\vande\\AppData\\Roaming\\npm\\node_modules', 'C:\\GitProjects\\jhipster-generator\\node_modules', 'C:\\Users\\vande\\AppData\\Local\\Yarn\\Data\\global\\node_modules', 'C:\\Users\\vande\\AppData\\Local\\Yarn\\Data\\link', 'C:\\npm\\node_modules', 'C:\\node_modules', 'C:\\GitProjects\\node_modules', 'C:\\GitProjects\\generateAppWithLinkedGenerator\\node_modules' ], packagePaths: [] } +1s
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: from-cli: true
Error: You don't seem to have a generator with the name “jhipster:app” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-jhipster:app.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
    at Environment.create (C:\GitProjects\jhipster-generator\node_modules\yeoman-environment\lib\environment.js:622:9)
    at Environment.run (C:\GitProjects\jhipster-generator\node_modules\yeoman-environment\lib\environment.js:725:28)
    at runYoCommand (C:\GitProjects\jhipster-generator\cli\cli.js:69:13)
    at Object.<anonymous> (C:\GitProjects\jhipster-generator\cli\cli.js:127:5)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)

C:\GitProjects\generateAppWithLinkedGenerator>

**Comment by murdos** [comment]
@darklyjohn Have you ran the `npm link generator-jhipster` in your `generateAppWithLinkedGenerator` directory, before launching the `jhipster` command?

**Comment by darklyjohn** [comment]
@murdos  yes and the same error :(

**Comment by mshima** [comment]
Move `C:\GitProjects\jhipster-generator` to `C:\GitProjects\node_modules\jhipster-generator`.
Run `npm link` again.
It should fix.

I will think about how to proper fix this.

**Comment by darklyjohn** [comment]
@mshima not working , I reinstall node.  But still the same problem. I made a debug of the code and see that in the environment file of node_module/yeoman-environment , the variable toNameSpace is undefined. Do you know where this value is set ? and how ? 

`create(namespaceOrPath, options) {
    options = options || {};
    const namespace = this.toNamespace ? this.toNamespace(namespaceOrPath) : undefined;

    let Generator;
    if (namespace && this.getByNamespace) {
      options.namespaceId = namespace;
      Generator = this.getByNamespace(namespace);
    }

    Generator = Generator || this.get(namespaceOrPath);
    if (namespace && Generator && Generator.namespace && Generator.namespace !== Environment.UNKNOWN_NAMESPACE) {
      // Update namespace object in case of aliased namespace.
      namespace.namespace = Generator.namespace;
    }

    if (typeof Generator !== 'function') {
      if (namespace && namespace.optional) {
        return undefined;
      }
      const generatorHint = namespace ? namespace.generatorHint : getGeneratorHint(namespaceOrPath);

      return this.error(
        new Error(
          chalk.red('You don\'t seem to have a generator with the name “' + namespaceOrPath + '” installed.') + '\n' +
          'But help is on the way:\n\n' +
          'You can see available generators via ' +
          chalk.yellow('npm search yeoman-generator') + ' or via ' + chalk.yellow('http://yeoman.io/generators/') + '. \n' +
          'Install them with ' + chalk.yellow(`npm install ${generatorHint}`) + '.\n\n' +
          'To see all your installed generators run ' + chalk.yellow('yo') + ' without any arguments. ' +
          'Adding the ' + chalk.yellow('--help') + ' option will also show subgenerators. \n\n' +
          'If ' + chalk.yellow('yo') + ' cannot find the generator, run ' + chalk.yellow('yo doctor') + ' to troubleshoot your system.'
        ),
        options.verifyListener
      );
    }`

**Comment by mshima** [comment]
Try this branch: https://github.com/mshima/generator-jhipster/tree/yeoman

**Comment by mshima** [comment]
You can update yeoman-environment to 2.9.6 on generator-jhipster#master too.

The bug is that the namespace is been registered wrong:
Log:
`yeoman:environment Registered C::GitProjects:jhipster-generator:app (C:\GitProjects\jhipster-generator\generators\app\index.js) on package C (C:\GitProjects\jhipster-generator)`

`C::GitProjects:jhipster-generator:app` instead of `jhipster:app`.

Probably this is only happening with Windows SO, as I am been not affected.

**Comment by mshima** [comment]
Sorry.
There is another problem the folder should be named `generator-jhipster` instead of `hipster-generator`.

**Comment by darklyjohn** [comment]
@mshima I try your fork , and it's working fine !  thank you , I will also try with my generator. 
Strange things with Windows SO ..
