### ISSUE TITLE
ecommerce istio error

### ISSUE THREAD

**Issue by ajsatix** [jhipster/generator-jhipster#11635]
store pod keeps crashing continously. when i looked at the logs for the pod i get below
![image](https://user-images.githubusercontent.com/60906911/80251414-31ada700-8693-11ea-8914-b55451af5abd.png)
@deepu105 can you help

**Comment by SudharakaP** [comment]
This is a duplicate of https://github.com/jhipster/generator-jhipster/issues/11551. We have already fixed it. Therefore I am closing this issue. :smiley:

**Comment by ajsatix** [comment]
thank @SudharakaP

**Comment by SudharakaP** [comment]
You are welcome :smile:
