### ISSUE TITLE
Filtering on Entities Gives Wrong Results

### ISSUE THREAD

**Issue by letanloc1998** [jhipster/generator-jhipster#11649]
##### **Overview of the issue**

https://www.jhipster.tech/entities-filtering/

When I filter equals and in, it give wrong result

##### **Motivation for or Use Case**

?id.equals=5&id.in=1&id.in=2&id.in=3

=> result entity/object id = 5
expected result: null (no id =5 and in = [1, 2, 3])

##### **Suggest a Fix**

Check criteria with multiple condition

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@letanloc1998 : Could you please complete the issue template with and example configuration. You can get the configuration for JHipster project where you saw this issue with `jhipster info` command. :smile:

**Comment by Blackdread** [comment]
it is not an issue.
If equals is given then it ignores others like: in, gt, lt, etc.

**Comment by letanloc1998** [comment]
> it is not an issue.
> If equals is given then it ignores others like: in, gt, lt, etc.

Hmm, this will give big bug logic code.

**Comment by letanloc1998** [comment]
> @letanloc1998 : Could you please complete the issue template with an example configuration (particularly the `.yo-rc.json` file and any entities). You can get the configuration for JHipster project where you saw this issue with `jhipster info` command.

This is logic code. It will response wrong result ~~

**Comment by SudharakaP** [comment]
@letanloc1998 : Hi, actually, @Blackdread is correct; it doesn't make sense to write `?id.equals=5&id.in=1&id.in=2&id.in=3` since id in this case is already equal to 5. If what you mean is some other bug that you notice, feel free to reopen with more detailed configuration so that we can reproduce the issue. :smiley:
