### ISSUE TITLE
Update react dependencies with major version changes

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#11651]
Update the following dependencies in React implementation. It could be bit of work since we haven't updated these in a while

```
 react-toastify          4.5.2  →  5.5.0 
 react-transition-group  2.7.0  →  4.3.0 
 reactstrap              7.1.0  →  8.4.1 
 uuid                    3.3.3  →  7.0.3 
 html-webpack-plugin     3.2.0  →  4.2.0 
```

**Comment by MathieuAA** [comment]
@deepu105 if you're not already doing it I'm willing to give it a go, I have the same use case in one of my apps :)

**Comment by mraible** [comment]
I created [a similar issue for Angular](https://github.com/jhipster/generator-jhipster/issues/11652).

**Comment by deepu105** [comment]
@MathieuAA plz go ahead, I just did #11653 but the dependencies here needs bit more work

**Comment by MathieuAA** [comment]
@deepu105 alright then

**Comment by MathieuAA** [comment]
First issue I've encountered, with the `html-webpack-plugin` dependency.
```
TypeError: Cannot read property 'tapAsync' of undefined
    at /home/mathieu/projects/munchy/node_modules/base-href-webpack-plugin/build/index.js:28:65
    ...
```

Found this issue in the repo that seems to correspond: https://github.com/jantimon/html-webpack-plugin/issues/1377#issuecomment-605678041
The `base-href-webpack-plugin` dependency didn't receive updates since early 2019. I'm gonna focus on the others 4 that seem to be easier to deal with.
I'll go back to this dependency after the others.

**Comment by deepu105** [comment]
I think this one is not very important anyway

**Comment by MathieuAA** [comment]
So far, except the last dependency, everything's okay. There's just reactstrap, but it's very minor: https://github.com/reactstrap/reactstrap/blob/master/CHANGELOG.md#breaking-changes. I'm doing some more tests in real apps but I think you can include them in your PR

**Comment by MathieuAA** [comment]
BTW, I didn't see any use of the `uuid` package in the front-end code (except in the `package.json` file). Unless I'm missing something...

**Comment by deepu105** [comment]
Probably its from some legacy stuff or used only in some specific option
combination

**Comment by MathieuAA** [comment]
Claimed my half: https://opencollective.com/generator-jhipster/expenses/17196. Thanks again Deepu!
