### ISSUE TITLE
Add Documentation about Embedded Entities for Document Databases

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#11658]
##### **Overview of the issue**

This is inspired from; https://github.com/jhipster/generator-jhipster/pull/11239#issuecomment-619372587

I think as per #11239 we need to add to our documentation about embedded entities. I am not exactly sure how this functionality works myself; if someone could give me a brief example I am more than happy to add this to the documentation. :smile: 

##### **Motivation for or Use Case**

Making the documentation up-to date. 

##### **Related issues**

#11239

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
remove 'stale', as self-assigned by @SudharakaP

**Comment by SudharakaP** [comment]
@github-actions : This is in my list to-do; so please don't close it. 🙏🏽 🥺

**Comment by pascalgrimaud** [comment]
still to do

**Comment by SudharakaP** [comment]
Sorry, I couldn't find the time yet but I will soon. So please keep it
open.

**Comment by SudharakaP** [comment]
Keep it open please. 😄

**Comment by SudharakaP** [comment]
This is done, let me know if there's anything more needs to be added. 😄 

cc: @tchlyah

**Comment by SudharakaP** [comment]
This is done and merged for v7.0.0 release; https://github.com/jhipster/jhipster.github.io/pull/1098. Therefore I am closing this. 😄
