### ISSUE TITLE
Add New Server Side options to jhipster.tech

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#11668]
##### **Overview of the feature request**

We have a number of backend options that aren't listed on jhipster.tech:

* Kotlin
* Node.js
* .NET
* Micronaut
* Quarkus

##### **Motivation for or Use Case**

We should highlight the work that developers have done on these blueprints. If they're not ready for use, we probably shouldn't include them.

##### **Related issues or PR**

https://github.com/jhipster/jhipster.github.io/pull/952

**Comment by pascalgrimaud** [comment]
done by https://github.com/jhipster/jhipster.github.io/pull/952 I think, so I'm closing this
