### ISSUE TITLE
Is my security a problem ? 

### ISSUE THREAD

**Issue by antoinecharlet** [jhipster/generator-jhipster#11675]
I post this on on stackoverflow: 
https://stackoverflow.com/questions/61482966/navigator-mediadevices-getusermedia-permission-denied
I com here juste to know if u saw somrthing weird in my security setting ! i'm using Let's encrypt
thx in advance

**Comment by atomfrede** [comment]
We are using a [feature policy ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy) security header in `SecurityConfiguration` which is [very restrictive](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs#L251) and should be adapted according to your needs. By default **no** access to camera or microphone is allowed.
