### ISSUE TITLE
Update Redis to 6.0.x

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#11678]
##### **Overview of the feature request**

See:
- http://antirez.com/news/132
- https://raw.githubusercontent.com/antirez/redis/6.0/00-RELEASENOTES

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@Shaolans : as you coded the original Redis part, can you have a look at this plz ?

**Comment by Shaolans** [comment]
@pascalgrimaud I will check it !

**Comment by Shaolans** [comment]
It seems redis 6.0 does not have big breaking changes, as they say it mostly a superset of 5.0.
So I don't think there is much to do, I also tested a generated app and works well.

I don't think we need a bug bounty for this =).
