### ISSUE TITLE
Update Keycloak to 10.0

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#11677]
##### **Overview of the feature request**

See:
- https://www.keycloak.org/2020/04/keycloak-1000-released
- https://www.keycloak.org/docs/latest/release_notes/index.html

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@vishal423 Have you time to make the update?

**Comment by vishal423** [comment]
@DanielFran, I will try to do it over next few days
