### ISSUE TITLE
Testcontainers for SQL databases: R2DBC support

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#11689]
##### **Overview of the feature request**

https://github.com/jhipster/generator-jhipster/pull/11584 has added Testcontainers for SQL databases, but it's missing support for reactive apps.

##### **Motivation for or Use Case**

Feature parity for reactive/non reactive applications

**Comment by ecostanzi** [comment]
Hi, last week I  created a [branch](https://github.com/ecostanzi/generator-jhipster/tree/r2dbc-sql-testcontainers) and started working on this.
```
spring:
 r2dbc:
  url: r2dbc:tc:postgresql://localhost:5432/myapp?TC_IMAGE_TAG=12.1
  username: myapp
  password:
```

The integration with testcontainers seems to be fine, but the main problem is that liquibase doesn't provide reactive support (see https://github.com/spring-projects/spring-data-r2dbc/issues/324). I'm not sure this can be done only using properties file: liquibase needs a datasource and to build it it's necessary to obtain jdbcURL from the java container instance.

Right now I'm trying to understand if the spring @DynamicPropertySource can be used to set the `spring.liquibase.*` and the `spring.r2dbc.*` properties globally for all tests.

**Comment by murdos** [comment]
@ecostanzi : have you tried to override the liquibase datasource with testcontainers from https://github.com/jhipster/generator-jhipster/blob/ccb3ea6340204eb1e3ba9aa01d49fc2d4f23518e/generators/server/templates/src/test/resources/config/application.yml.ejs#L135 in `application-testcontainers.yml`?

**Comment by ecostanzi** [comment]
I think that `spring.liquibase.url` has to be set dynamically before all testst start. By default testcontainers spins up the container on a random port so I cannot hardcode the url in the application-testcontainers.yml.

The code below works, but only for a single test and it doesn't use the `application-testcontainers.yml`. I'm wondering if I can set the dynamic properties once for all tests.

```java
@AutoConfigureWebTestClient
@WithMockUser(authorities = AuthoritiesConstants.ADMIN)
@SpringBootTest(classes = {ReacttestcntApp.class, TestcontainersConfiguration.class})
@Testcontainers
public class UserResourceIT {

    @Container
    static PostgreSQLContainer container = new PostgreSQLContainer("postgres:12.1")
        .withDatabaseName("reacttestcnt");

    @DynamicPropertySource
    static void propertySourceDyn(DynamicPropertyRegistry registry) {

        String jdbcUrl = container.getJdbcUrl();
        registry.add("spring.liquibase.url", ()->jdbcUrl);
        registry.add("spring.liquibase.user", container::getUsername);
        registry.add("spring.liquibase.password", container::getPassword);
      
        registry.add("spring.r2dbc.url", () -> jdbcUrl.replace("jdbc", "r2dbc"));
        registry.add("spring.r2dbc.username", () -> container::getUsername);
        registry.add("spring.r2dbc.password", () ->container::getPassword);
    }

//all the tests
```

**Comment by ecostanzi** [comment]
@murdos I saw your last PR: https://github.com/jhipster/generator-jhipster/pull/11803

I'm trying to do a similar thing with postgres containers here: https://github.com/ecostanzi/jhipster-testcontainers-r2jdb/blob/master/src/test/java/com/mycompany/myapp/config/DatabaseTestcontainersExtension.java/. I added the @ExtendsWith to the UserResourceIT test, but the method annotated with @DynamicProperty is never called by spring. Am I missing something? Thanks

**Comment by murdos** [comment]
@ecostanzi : no, sorry... I played a bit with your branch, but indeed I can't get it working and I don't see anything missing.

**Comment by topikachu** [comment]
@murdos  As far as I understand, @DynamicProperty can only be recognized within the test class.  I don't understand how  #11803 working. Is there anything I missing?

**Comment by murdos** [comment]
@topikachu Sorry, I don't understand too why it was working.

**Comment by atomfrede** [comment]
It would at least explain why it didn't work with neo4j using the same approach as with redis

**Comment by atomfrede** [comment]
I have a working solution (similar to what we do with neo/redis) as we need to customize the liquibase URL. Will provide a PR later today.
