### ISSUE TITLE
Replace or remove Spring Cloud Connectors

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#11685]
##### **Overview of the issue**

Spring Cloud Connectors is in maintenance mode: https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services

And the Spring Cloud Connectors starter has been removed from Spring Boot since [version 2.3.0 M1](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3.0-M1-Release-Notes)

##### **Motivation for or Use Case**

Don't rely on outdated libraries.

**Comment by atomfrede** [comment]
Do we still have free credits to evaluate and test the feature? If yes, who has access to that account?

**Comment by jdubois** [comment]
I didn’t know about that! What are they doing???

I probably still have free credits, and otherwise I can get some easily.

Is one of you interested to test? I should be able to give you access to the JHipster org on the public CF instance.

**Comment by jdubois** [comment]
Looking at our stats, we had 322 deployments to CloudFoundry last year, so we need to decide if we keep maintaining it or not. As far as I know, I'm the only one who was working on this sub-generator, and I just don't have the time anymore (not to mention I'd rather work on the Azure sub-generator, for the very basic reason that I can do it as part of my job, which is the easiest way for me to have time to do it)

**Comment by jdubois** [comment]
Those connectors have been replaced by https://github.com/pivotal-cf/java-cfenv but that project has very little activity, so I'm really wondering if we should spend time supporting this

**Comment by mraible** [comment]
@joshlong Is there anyone at VMWare that'd be interested in helping maintain JHipster's Cloud Foundry support? We can assign bug bounties to issues so there's $$ associated with contributions.

**Comment by jdubois** [comment]
Hey, I'm on an Azure bug right now which has a $100 bug bounty, so to be fair I'm adding a $200 bug bounty here (it's more complex)

**Comment by mraible** [comment]
Since Pivotal Web Services is shutting down in Jan 2021, do we still need to be concerned about this?

**Comment by jdubois** [comment]
Indeed, I believe we should remove them now... I'm lowering the bug bounty because that's easier than updating!

**Comment by pascalgrimaud** [comment]
little comment to keep this ticket opened, as the label 'stale' was removed by @murdos

**Comment by murdos** [comment]
> 
> 
> little comment to keep this ticket opened, as the label 'stale' was removed by @murdos

Sorry... I'm a bit confused on how this stale thing feature works 😅
Thanks @pascalgrimaud !

**Comment by pascalgrimaud** [comment]
@murdos : it's really simple
- if there is no comment in the ticket, the bot will add label  ̀stale`, with the previous comment
- if there is no comment in 7 days, the ticket will be closed, because it's inactive or no one want to work on this
- that's why I added a comment. I don't think removing the label will work

**Comment by jdubois** [comment]
Removing the "stale" label, we need to clean this up for JHipster 7
