### ISSUE TITLE
Does BrowserSync support client-only (i.e. without the backend)?

### ISSUE THREAD

**Issue by sdoxsee** [jhipster/generator-jhipster#1169]
I've been unable to get a generated app to work with "grunt serve" without starting the backend. I really liked doing fast client-only development previously and mocking out my backend API endpoints. How would one run the client without having to start the backend with browsersync? I'm going to have to roll back to 2.2.0 for now.

Thanks again for all the great work

**Comment by sdoxsee** [comment]
Nevermind. I was able to get it to work! Closing

**Comment by gmarziou** [comment]
@sdoxsee I also like to develop backend less and I use stubs with an $httpBackend interceptor, is it how you do it also? Just curious.

**Comment by sdoxsee** [comment]
@gmarziou yes,  that's how I do it as well--with ngMockE2E. Unfortunately I had to roll back the browsersync changes since I was only able to run it completely statically (no proxying) or completely proxied (i.e. Not just api calls but everything...making you dependent on starting the backend for anything at all). I prefer a hybrid when api calls are proxied to the server if I don't intercept and mock them first. The rest of the assets are served up without needing the backend and are livereloaded.  If you know how to get browsersync to do this,  please let me know...i have to diverge from jhipster at this point until I figure it out.

**Comment by gmarziou** [comment]
As we do the same, it will be also an issue for me, so I'll have a look at it.

@jdubois I think the issue should be re-opened and its title changed to something like: "BrowserSync incompatible with backend-less development"

Benefits of [Backend-less development with AngularJS](https://ruhul.wordpress.com/2014/11/03/backendless-development-with-angularjs/) are:
- faster development cycle
- easier communication with customers as you can zip the webapp folder and send it to them for review
- easier collaboration with designers

I don't know if there is something we can do to have both working in `serve` task but at least it should be easy to provide a new task without browersync:

    grunt.registerTask('noBackend', [
        'clean:server',
        'wiredep',
        'ngconstant:dev',
        'concurrent:server',
        'watch'
    ]);

 This task could also automate the wiring of the stubs script into the index.html which currently I do by commenting/uncommenting.

**Comment by gmarziou** [comment]
Here is [an example](https://github.com/gmarziou/jhipster-backend-less) where I added back the liverreload feature and a new grunt task serve-client. The details are in the [second commit](https://github.com/gmarziou/jhipster-backend-less/commit/79c00ff6831d5879da8155205b0a43a20bef806f).
It simulates an admin user, I did not add the proxies configuration to the api as I just wanted to be in pure backend-less confiiguration.

**Comment by gmarziou** [comment]
I'm still investigating why but so far it seems that:
  * It could be a [problem for Windows users](http://www.browsersync.io/docs/#windows-users) which would require them to have visual studio 2013 installed, that may be a lot for java developers
  * The way Gruntfile.js is configured in jhipster would proxy any request to the jhipster application running on port 8080, I think that this is what is preventing backend-less development from working as previously the proxification was more fine grain configured

**Comment by gmarziou** [comment]
I opened a BrowserSync issue https://github.com/BrowserSync/browser-sync/issues/471

**Comment by gmarziou** [comment]
WIth help from BrowserSync team, I got both static server for frorntend and proxy for backend API.
I could not make it work with connect-proxy but I found an example using http-proxy and got it working:

~~~~ javascript
var httpProxy = require('http-proxy');
 
var proxy = httpProxy.createProxyServer({
   target: 'http://localhost:8080/'
 });
 
var proxyMiddleware = function(req, res, next) {
   if (req.url.indexOf('api') != -1) {
     proxy.web(req, res);
   } else {
     next();
   }
};

....
        browserSync: {
            dev: {
                bsFiles: {
                    src : [
                        'src/main/webapp/**/*.html',
                        'src/main/webapp/**/*.json',
                        'src/main/webapp/bower_components/**/*.{js,css}',
                        '{.tmp/,}src/main/webapp/assets/styles/**/*.css',
                        '{.tmp/,}src/main/webapp/scripts/**/*.js',
                        'src/main/webapp/assets/images/**/*.{png,jpg,jpeg,gif,webp,svg}'
                    ]
                }
            },
            options: {
                watchTask: true,
                server: {
                   baseDir: [".tmp", "src/main/webapp"],
                   middleware: proxyMiddleware
                }
            }
        },

~~~~

**Comment by gmarziou** [comment]
I changed for a simpler version where I have 2 BrowserSync configurations: 
- dev: the original one that uses a proxy for all requests
- backendLess: the new one that uses static server and works only with simulated backend

This is what is below, it could be improved by avoiding duplicating the list of files to watch.

~~~~ javascript
        browserSync: {
            dev: {
                bsFiles: {
                    src : [
                        'src/main/webapp/**/*.html',
                        'src/main/webapp/**/*.json',
                        'src/main/webapp/bower_components/**/*.{js,css}',
                        '{.tmp/,}src/main/webapp/assets/styles/**/*.css',
                        '{.tmp/,}src/main/webapp/scripts/**/*.js',
                        'src/main/webapp/assets/images/**/*.{png,jpg,jpeg,gif,webp,svg}'
                    ]
                },
                options: {
                    watchTask: true,
                    server: {
                       baseDir: [".tmp", "src/main/webapp"]
                    }
                }
            },
            backendLess: {
                bsFiles: {
                    src : [
                        'src/main/webapp/**/*.html',
                        'src/main/webapp/**/*.json',
                        'src/main/webapp/bower_components/**/*.{js,css}',
                        '{.tmp/,}src/main/webapp/assets/styles/**/*.css',
                        '{.tmp/,}src/main/webapp/scripts/**/*.js',
                        'src/main/webapp/assets/images/**/*.{png,jpg,jpeg,gif,webp,svg}'
                    ]
                },
                options: {
                    watchTask: true,
                    proxy: "localhost:8080"
                }
            },
        },
~~~~

These 2 configurations are used by 2 tasks:
- `serve`: the original one that uses BrowserSync:dev
- `serve-client`: the new one that uses BrowserSync:backendLess

~~~~ javascript
    grunt.registerTask('serve', [
        'clean:server',
        'wiredep',
        'ngconstant:dev',
        'concurrent:server',
        'browserSync:dev',
        'watch'
    ]);

    grunt.registerTask('serve-client', [
        'clean:server',
        'wiredep',
        'ngconstant:dev',
        'concurrent:server',
        'browserSync:backendLess',
        'watch'
    ]);
~~~~

**Comment by sdoxsee** [comment]
Thanks @gmarziou Doesn't browserSync:backendLess need the server running though? Isn't it the same as what is currently in jhipster? Do you have them backwards? Correct me if I'm wrong but the static doesn't need a backend but it also means that you have to mock every backend endpoint or it will fail. Does this work for a hybrid approach where you're proxying to your real backend if a stubbed out response hasn't been defined to intercept the call?

**Comment by gmarziou** [comment]
browserSync:backendLess does not need the server unless you call an endpoint that has not been stubbed. For instance I did not stub all the swagger-ui or other admin stuff because I need them when I run in backend less mode, I only need to stub authentication and my own services.

So for hybrid approach, you have 2 solutions:
- use my first approach of back-porting the pre-2.3.0 task, this is what I have done in at this [point of my repo history](https://github.com/gmarziou/jhipster-backend-less/tree/530bc825d4aeb2d0246fde8fe20cd23b6a4d286a)
- use the http-proxy middleware described above but you'll have to define precise mappings in your proxy which could be cumbersome to use, you can see it this [point of my repo history](https://github.com/gmarziou/jhipster-backend-less/tree/1678c44115341fdd7e221d7a1f6f3c7d4b0777cd)

**Comment by sdoxsee** [comment]
If i start in backendLess mode then my app doesn't come up in the browser without starting the backend...mind you I'm not mocking out anything yet. I don't want to mock out everything right off the bat (at least that's how jhipster used to work). Also, perhaps my computer setup is wrong (using Yosemite). I'm going to go status quo with the old implementation for now.

Thanks for your help.
