### ISSUE TITLE
Support redis in heroku subgen

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#11695]
##### **Overview of the feature request**

Heroku as a redis service. If I am not mistaken we don't support that addon in the heroku subgen. I think we should

* https://elements.heroku.com/addons/heroku-redis

##### **Related issues or PR**

* https://github.com/jhipster/generator-jhipster/issues/11693

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
To use the redis addon we must

* decrease the pool sizes for redis (as the free plan only allows 20 connection)
* parse the `REDIS_URL` as it has the form `redis://[:PASSWORD@]HOST[:PORT]` and just setting this as adress seem not to work. Getting `nauthorized: javax.cache.CacheException: org.redisson.client.RedisAuthRequiredException: NOAUTH Authentication required`

**Comment by pascalgrimaud** [comment]
It's ok, but the properties should be in application.yml, so probably some changes to do in jhipster lib, if I'm correct

It means:
- add new properties in jhipster lib
- do the change for useSingleServer and maybe cluster too
- let the default value in application.yml for dev/prod locally
- override the value in application-heroku.yml with the ones you suggest

What do you think ?

**Comment by atomfrede** [comment]
Exactly my plan. The main part is adding the properties to the jhipster lib.
