### ISSUE TITLE
Support Okta with Heroku sub-gen

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#11698]
##### **Overview of the feature request**

Okta has a Heroku add-on. If OIDC authentication is used, we should prompt to add Okta.

##### **Motivation for or Use Case**

This will allow OIDC to be more widely used and make apps more portable.

@dogeared Wrote our Okta add-on so he's a good resource if help is needed.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Seems we miss a lot stuff from heroku. Would like to work on them. Finally a good opportunity to try out octa!
