### ISSUE TITLE
Neo4J: Cyclic OneToMany adds an incorrect ManyToOne

### ISSUE THREAD

**Issue by jkransen** [jhipster/generator-jhipster#11691]
##### **Overview of the issue**

Neo4J generation
Cyclic Relationship to entity itself results in second, incorrect property.

##### **Motivation for or Use Case**

I want a Person to have friends as a collection of type Person.

##### **Reproduce the error**

    entity Person {
       name: String
    }

    relationship OneToMany {
       Person{friends} to Person
    }

Generate application based on this. Generated domain class:

    @Node
    public class Person implements Serializable {

        // correct: 

        @Relationship
        private Set<Person> friends = new HashSet<>();

        // incorrect:

        @Relationship("person")
        @JsonIgnoreProperties("friends")
         private Person person;

    }

Also, some additional code is generated based on this, including CRUD in the front end.

##### **Related issues**

This similar issue was related to React, and Neo4J was not used back then:
https://github.com/jhipster/generator-jhipster/issues/11549

##### **Suggest a Fix**

Do not generate the reverse relationship in a OneToMany to type itself for Neo4J.

##### **JHipster Version(s)**

6.8.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.blabla",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "blabla",
    "packageName": "com.blabla",
    "packageFolder": "com/blabla",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "neo4j",
    "devDatabaseType": "neo4j",
    "prodDatabaseType": "neo4j",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "minty",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1588343391509,
    "testFrameworks": ["cucumber"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": [],
    "herokuAppName": "blabla",
    "herokuDeployType": "jar"
  }
}
---
If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
     JDL content here
  </pre>
  </details>
-->

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Here, Person is called Trainer. I think I already see the problem. There is a ManyToOne after the OneToMany that should probably go. I checked, and it is not in the jhipster-jdl.jh

{
    "name": "Trainer",
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "code",
            "fieldType": "Long"
        },
        {
            "fieldName": "level",
            "fieldType": "Integer"
        },
        {
            "fieldName": "xp",
            "fieldType": "Integer"
        },
        {
            "fieldName": "team",
            "fieldType": "Team",
            "fieldValues": "VALOR,MYSTIC,INSTINCT"
        }
    ],
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "trainer",
            "otherEntityRelationshipName": "trainer",
            "relationshipName": "friends"
        },
        {
            "relationshipType": "many-to-one",
            "otherEntityName": "trainer",
            "otherEntityRelationshipName": "friends",
            "relationshipName": "trainer",
            "otherEntityField": "id"
        }
    ],
    "changelogDate": "20200502070200",
    "entityTableName": "trainer",
    "dto": "no",
    "pagination": "no",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "readOnly": false,
    "embedded": false,
    "clientRootFolder": "",
    "applications": "*"
}

##### **Browsers and Operating System**

Linux Mint 19

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Thanks @jkransen for reporting this and being brave using the neo4j support. Just to make sure, the generated entity contains both the `Set<Person>` and the backreference to `Person`? Indeed that looks like a bug as it should not be needed with neo. I will try to have look.

**Comment by jkransen** [comment]
Hi Frederik, indeed I want to give Neo4J a try. At least I can learn something about it along the way. I will be glad to give more feedback knowing that it will be picked up. Maybe a few small steps on the road to get rid of that beta tag :-)

**Comment by MathieuAA** [comment]
I'll fix it.

**Comment by MathieuAA** [comment]
Unless @pascalgrimaud wants it for JCode?

**Comment by pascalgrimaud** [comment]
@MathieuAA : as you want :)

**Comment by MathieuAA** [comment]
Two things here:
  - The JDL sample doesn't work, there's no `:` char between a field's name and a type,
  - This is what is actually displayed when trying to import the JDL content:
```
warn: In the One-to-Many relationship from Person to Person, only bidirectionality is supported for a One-to-Many association. The other side will be automatically added.
```

If it's not necessary to generate the corresponding many-to-one relationship for neo4j-related cases then:
  - This case should be documented,
  - The generator should take this into account (I'm making the change)

**Comment by MathieuAA** [comment]
@atomfrede should we disable the automatic conversion to a bidirectional one-to-many relationship only if the DB type is Neo4j? Or also if the source & destination entities are the same?

**Comment by atomfrede** [comment]
Does it cause any problems except for neo4j? If not let's just do it for neo
