### ISSUE TITLE
why always cannot find git-commit-id-plugin?

### ISSUE THREAD

**Issue by fuzheng1998** [jhipster/generator-jhipster#11702]
when generating new project, I found git-commit-plugin is always ignored, in IDEA saying `cannot find declaration to go`.
<img width="625" alt="Screen Shot 2020-05-05 at 08 23 53" src="https://user-images.githubusercontent.com/24203166/81025617-c2615f80-8ea9-11ea-864e-efa0148fbfdd.png">

- maven version 3.6
- open-jdk 11
- maven repo Aliyun mirror
NOTE: if changing to maven repo, saying cannot transfer...

**Comment by pascalgrimaud** [comment]
Sorry but it's related to your maven configuration, not a JHipster issue.
We can't help you to configure your environment here
