### ISSUE TITLE
Frontend is not available (behind a reverse proxy, e.g. via heroku)

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#11714]
##### **Overview of the issue**

The newly introduced caching configuration makes the frontend not delivered when deployed on heroku (but I guess it a more general problem).

##### **Motivation for or Use Case**

It should just work.

##### **Reproduce the error**

Generate an application (from latest master) and deploy it to heroku. You will see the failure pacman. If you disable or remove the new `StaticResourcesWebConfiguration` it just works fine. 
The error I see in the heroku logs is a 404 when requesting the static resources.

##### **Suggest a Fix**

Not sure, disabling the `StaticResourcesWebConfiguration` is not good as caching will be affected.

##### **JHipster Version(s)**

Latest master

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
need to investigate, as it works with default packaging in local
but it's broken behind a reverse proxy ?

cc @monxxi

**Comment by atomfrede** [comment]
@pascalgrimaud I guess it is something like this. Good to know it works locally (didn't test, but I thought would have been noticed). We should fix that before the release :pray:

**Comment by atomfrede** [comment]
First I thought it might be related to the cache key PR, but the e2e tests can't find the frontend too, might that be related to this one?

![image](https://user-images.githubusercontent.com/203401/81155635-7257cb00-8f85-11ea-9dce-e2c59c832f0f.png)

**Comment by pascalgrimaud** [comment]
thanks @atomfrede 
as JDLMS failed, it means it should be easy to reproduce the problem locally

**Comment by pascalgrimaud** [comment]
I'm working on this with @monxxi this morning
we should have a fix for that very soon

**Comment by atomfrede** [comment]
@pascalgrimaud Awesome, thanks!

**Comment by atomfrede** [comment]
Just checked it with heroku and it works fine, thanks @pascalgrimaud & @monxxi
