### ISSUE TITLE
Enhancement suggestions for nodejs blueprint

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster#11723]
This is a proxy issue for jhipster/generator-jhipster-nodejs#136 so @mraible can assign a bug bounty to it.

**Comment by mraible** [comment]
@amanganiello90 I was able to add a bug bounty to the original issue, so I'm not sure this is needed. Can you help @pascalgrimaud?

**Comment by amanganiello90** [comment]
Ok no problem, Ed can start the issue. Thanks

**Comment by pascalgrimaud** [comment]
@mraible : as said in the mailing list, it's because each blueprint has a separate team. As it seems resolved, I'm closing this.
