### ISSUE TITLE
Login RegEx is a breaking change 

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#11726]
##### **Overview of the issue**

[One recent PR](https://github.com/jhipster/generator-jhipster/pull/11450) changed the validation patterns logins. This regex has a problem.

* There is a potential breaking change. E.g. with the old regex `foo@bar@com` was a valid login. With the regex in master not. So data which is currently in the database and a valid login will be invalid now

##### **Motivation for or Use Case**

It should not happen.

##### **Related issues**

None.

##### **Suggest a Fix**

Update the regex such that

* It behaves more like the old regex, such that breaking changes do not happen

##### **JHipster Version(s)**

Current master only. The was **NO** release with the breaking change, so no user is in danger.
 
##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
In my opinion, we should revert the change on login regex and not allow email address as a valid username at least in `v6.x` release. The issue/enhancement raised in original ticket doesn't seems a must priority to be handled in `v6.x` for JWT/Session based authentication types.
