### ISSUE TITLE
add the documentation for entity options to jhipster.tech website

### ISSUE THREAD

**Issue by 62mkv** [jhipster/generator-jhipster#11732]
##### **Overview of the feature request**

Turns out (looking at https://github.com/jhipster/jhipster-core/pull/370/) entities actually have quite some options, including in the JDL, but no where could I find any of those on the https://jhipster.tech pages

##### **Motivation for or Use Case**

I would expect to be able to find this information at: 
- https://www.jhipster.tech/jdl/entities-fields
- https://www.jhipster.tech/creating-an-entity/

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by 62mkv** [comment]
update: some of those options are actually mentioned at https://www.jhipster.tech/jdl/options, which clearly is not enough, they should at least be mentioned with a link for further details on the pages, describing entity definition itself

**Comment by MathieuAA** [comment]
Can you do a PR to improve that?

**Comment by 62mkv** [comment]
Will give it a try, probably
