### ISSUE TITLE
Add Neo4j to Kubernetes/Helm deployment sub generators

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#11731]
##### **Overview of the feature request**

We did not yet add neo support to kubernetes/helm generator.

##### **Motivation for or Use Case**

To be consistent and moving foward with getting neo4j out of beta we should support deployments for neo based apps out of box.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Any updates @atomfrede?

**Comment by atomfrede** [comment]
Sorry, totally forgot about this.

**Comment by atomfrede** [comment]
Will try to work on this.

**Comment by pascalgrimaud** [comment]
Closing this in favor of https://github.com/jhipster/generator-jhipster/issues/13477
