### ISSUE TITLE
MySQL - Entity with LocalDate: one-day bug

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#11740]
##### **Overview of the issue**

Following this ticket: https://github.com/jhipster/generator-jhipster/issues/11734

In a MySQL application, when you save an entity with LocalDate, the result is not correct:
- save with 2020/05/08
- result: 2020/05/07

##### **Motivation for or Use Case**

The result should be correct.

##### **Reproduce the error**

I pushed this project to reproduce easily: https://github.com/pascalgrimaud/jhipster-burger-11740

```
git clone https://github.com/pascalgrimaud/jhipster-burger-11740
cd jhipster-burger-11740
npm ci
docker-compose -f src/main/docker/mysql.yml up -d
./mvnw
```

Then, go to Beer entity
Create a new entity
Check the drinkDate

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/11734

##### **Suggest a Fix**

Not sure at all about this solution :

```diff
diff --git a/src/main/java/io/github/pascalgrimaud/BurgerApp.java b/src/main/java/io/github/pascalgrimaud/BurgerApp.java
index 6236c6d..3a0b37c 100644
--- a/src/main/java/io/github/pascalgrimaud/BurgerApp.java
+++ b/src/main/java/io/github/pascalgrimaud/BurgerApp.java
@@ -5,6 +5,7 @@ import io.github.pascalgrimaud.config.ApplicationProperties;
 import io.github.jhipster.config.DefaultProfileUtil;
 import io.github.jhipster.config.JHipsterConstants;
 
+import java.util.TimeZone;
 import org.apache.commons.lang3.StringUtils;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
@@ -41,6 +42,8 @@ public class BurgerApp {
      */
     @PostConstruct
     public void initApplication() {
+        TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
+
         Collection<String> activeProfiles = Arrays.asList(env.getActiveProfiles());
         if (activeProfiles.contains(JHipsterConstants.SPRING_PROFILE_DEVELOPMENT) && activeProfiles.contains(JHipsterConstants.SPRING_PROFILE_PRODUCTION)) {
             log.error("You have misconfigured your application! It should not run " +
```

##### **JHipster Version(s)**

6.8.0 and maybe less

##### **JHipster Version(s)**

```
burger@0.0.1-SNAPSHOT /home/pgrimaud/tmp/11-burger
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "burger",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1588964185564,
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": [],
    "prettierJava": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Beer {
  name String,
  drinkDate LocalDate
}
dto Beer with mapstruct
service Beer with serviceClass

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

git version 2.26.2

node: v12.16.1

npm: 6.14.2

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.2, build a133471

identical .jhipster/Beer.json
INFO! Congratulations, JHipster execution is complete!

**Comment by pascalgrimaud** [comment]
Related link:

- https://stackoverflow.com/a/61678763
- https://bugs.mysql.com/bug.php?id=99487

The upgrade of mysql-connector to 8.0.20 is not a solution for now as it introduced another bug.

**Comment by ecostanzi** [comment]
From the [documentation](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html):

> serverTimezone
Override detection/mapping of time zone. Used when time zone from server doesn't map to Java time zone

We are saying to mysql that our server is in UTC when in many case it's not. On my laptop for example the JVM timezone is Europe/Rome.

So, @pascalgrimaud I think that your solution works. We are aligning the JVM timezone to the jdcb connection string. 

Solution 2: align the jdbc connection string to the JVM timezone. This can be done by changing the jdbc connecton string like we did with testcontainers properties file: `serverTimezone=${user.timezone}`. 

I personally prefer your solution, but I'm wondering what is the impact for users who will upgrade to this new version.

These are the tests I did:

With UTC timezone : `jdbc:mysql://localhost:3306/burger?...useLegacyDatetimeCode=false&**serverTimezone=UTC**...`

```
curl -X POST http://localhost:8080/api/beers -s -d '{"drinkDate": "2020-05-08"}' -H "Content-Type: application/json"
{
  "id" : 19,
  "name" : null,
  "drinkDate" : "2020-05-08"
}

curl -s http://localhost:8080/api/beers/19
{
  "id" : 19,
  "name" : null,
  "drinkDate" : "2020-05-07" --> wrong
}
```
With my timezone: `jdbc:mysql://localhost:3306/burger?...useLegacyDatetimeCode=false&**serverTimezone=Europe/Rome**...`
```
curl -X POST http://localhost:8080/api/beers -s -d '{"drinkDate": "2020-05-08"}' -H "Content-Type: application/json"
{
  "id" : 20,
  "name" : null,
  "drinkDate" : "2020-05-08"
}

curl -s http://localhost:8080/api/beers/20
{
  "id" : 20,
  "name" : null,
  "drinkDate" : "2020-05-08" --> correct!
}
```

With ${user.timezone}:
`jdbc:mysql://localhost:3306/burger?...useLegacyDatetimeCode=false&**serverTimezone=${user.timezone}**...`
```
curl -X POST http://localhost:8080/api/beers -s -d '{"drinkDate": "2020-05-08"}' -H "Content-Type: application/json"
{
  "id" : 21,
  "name" : null,
  "drinkDate" : "2020-05-08"
}

curl -s http://localhost:8080/api/beers/21
{
  "id" : 21,
  "name" : null,
  "drinkDate" : "2020-05-08" --> correct!
}

```

**Comment by pascalgrimaud** [comment]
Thanks for helping here @ecostanzi 
I think it's because the default timezone of the JVM is user.timezone
And as you said, maybe the best solution is to align JVM + jdbc url :

- use UTC
    - JVM to UTC timezone (in PostConstruct)
    - all jdbc url with UTC (needs change for testcontainers only, as dev and prod already use UTC)
-  use user timezone
    - let JVM like this (by default user timezone)
    - change all jdbc url to use user.timezone (needs change for dev, prod)

The only problem is exactly like you said: `I'm wondering what is the impact for users who will upgrade to this new version.`

**Comment by ctamisier** [comment]
I think there will be a problem if there are several instances of the application around the world. One in Europe and one in Australia. Depending where the entity is saved or re-saved, the date might be affected.

About 8.0.20 version the bug seems fix in ServerPreparedQueryBindValue line 287 by getting a calendar in the current server timezone which won't wrongly affect the date in the next code lines.

With this version it seems that cacheDefaultTimezone is null even if we provide it in the url as &cacheDefaultTimezone=false.

**Comment by pascalgrimaud** [comment]
> I think there will be a problem if there are several instances of the application around the world. One in Europe and one in Australia. Depending where the entity is saved or re-saved, the date might be affected.

@ctamisier : in this case, all the config should be set to UTC, right ?

**Comment by ctamisier** [comment]
Yes exact. It is also what I've understand about the initial motivation to set to UTC in the connector configuration which seems correct to me and a good way to have unified dates (specially if we use Mysql DATETIME). (cc @avdev4j)

The problem might be here (about 8.0.20): https://github.com/mysql/mysql-connector-j/commit/c1e9c7d1f3ff5b31ca6a2744707ae4dd7840cf3c#r39054941

**Comment by ecostanzi** [comment]
Let's consider this. If we change the jvm timezone in the `postconstruct` users that upgrade might not even notice the change and deploy a new version of the app. Besides, if someone has set `-Duser.timezone=not-utc`in the Java opts, we would override that setting. I'm afraid that in this case many will be affected by the change.

On the other hand, if we change the properties files we would give them the chance to fix the production properties. Hopefully most of the users have externalized the production configuration.

**Comment by ctamisier** [comment]
Indeed we shouldn't do this: 
`TimeZone.setDefault(TimeZone.getTimeZone("UTC"));`

For now we can imagine to use &serverTimezone=${user.timezone} but it is a bit against all the analysis here: https://github.com/jhipster/generator-jhipster/issues/8284 ? (saying UTC everywhere)

For me the solution is a fix on the connector post 8.0.20 (as I think the &cacheDefaultTimezone=false is the solution) but I don't know much how it will go..

**Comment by pascalgrimaud** [comment]
Yes I believe we just need to wait a new version of mysql connector

**Comment by skmaingi** [comment]
@pascalgrimaud I removed `&serverTimezone=UTC` from jdbc url and inserted dates for different Timezone and all were correct on reading them

**Comment by skmaingi** [comment]
@pascalgrimaud removing `&serverTimezone=UTC` and setting JVM Timezone will not work for existing MySQL databases that saved LocalDate entries in UTC. 
Date conversion maybe required for those who were using previous version

**Comment by ctamisier** [comment]
A ticket on MySQL Connector/J is opened here: https://bugs.mysql.com/bug.php?id=99713.(about the exception on storing date with the connector 8.0.20)
It is "verfied". 
So I think if we have a version 8.0.21 it should work as 8.0.20 should fix the "one day bug" in a proper way.

**Comment by DanielFran** [comment]
@pascalgrimaud @ctamisier version 8.0.21 is now available: https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-21.html

I will create a PR today to update the version in BOM project, so we can close this PR.

**Comment by pascalgrimaud** [comment]
Thanks a lot.
So the best fix was to wait the new version :)

**Comment by ctamisier** [comment]
Can you see a fix about this issue ?
eventually here: https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-21.html#connector-j-8-0-21-bug

**Comment by DanielFran** [comment]
@ctamisier I just checked that mysql/mysql-connector-j@c1e9c7d#r39054941 was on 8.0.21
![image](https://user-images.githubusercontent.com/3706415/87667210-df47c800-c761-11ea-8dd5-6f0e42f166ec.png)

**Comment by DanielFran** [comment]
@ctamisier I review again the commits for that version and in fact there is no commit to fix the current issue in 8.0.20, I mislead with the commit you put bellow...

**Comment by mraible** [comment]
@ctamisier Can you create a PR to use the next release once it happens?

**Comment by ctamisier** [comment]
Sure ! but @DanielFran might go faster than me :)

**Comment by pascalgrimaud** [comment]
it looks like the 8.0.22 is available : https://search.maven.org/artifact/mysql/mysql-connector-java/8.0.22/jar

**Comment by DanielFran** [comment]
Sorry, but I had a cirurgy yesterday so I will be out few weeks...

**Comment by mshima** [comment]
@DanielFran best wishes.

**Comment by pascalgrimaud** [comment]
@DanielFran : no worry about JHipster, take care of yourself, it's more important my friend !

**Comment by pascalgrimaud** [comment]
@ctamisier : I just tested with 8.0.22 and it is finally fixed !!!
As you are the one who did the most of work here (analyzed the bug, opened ticket, followed release, etc), can you propose a pull request at https://github.com/jhipster/jhipster to upgrade this plz ? Then, the bounty will be for you !

```xml
<mysql-jdbc.version>8.0.19</mysql-jdbc.version>
```

**Comment by ctamisier** [comment]
take care @DanielFran !
Yes I'll submit a PR. Thx.

**Comment by pascalgrimaud** [comment]
@ctamisier : approved your bounty https://opencollective.com/generator-jhipster/expenses/26862

**Comment by henry2man** [comment]
Hi folks. I'been facing issues like this one with a newly created JH microservice. In my case I obtained wrong `LocalDates` representing one day minus the real ones. 

I have been trying many versions from 8.0.22 onwards without success. Finally I have only been able to fix the problems with `LocalDate` only when I have downgraded to the latest valid version of `mysql-connector-java` (`8.0.19`), reverting the changes made in https://github.com/jhipster/jhipster/pull/888

@ecostanzi @pascalgrimaud Have any of you ever had a problem with this again? If yes, shouldn't we lock 8.0.19 until this is resolved in MySQL?

PS: I've double checked that
- I'm using `+8.0.22` versions, cleaning and executing commands like `./mvnw dependency:tree`, 
- My JDBC connection url includes `...&useLegacyDatetimeCode=false&serverTimezone=UTC...`
- My MySQL server is running in a Docker container with `UTC` timezone
- My `application.yml` includes `hibernate.jdbc.time_zone: UTC`
- My Java code contains timezone adjust code: `TimeZone.setDefault(TimeZone.getTimeZone("Etc/UTC"));`

**Comment by pascalgrimaud** [comment]
I thought it was fixed... But yes, if there is still the issue, we should downgrade.

I can't say, as I'm using PostgreSQL for my customers, I don't use MySQL any more.

**Comment by henry2man** [comment]
> I thought it was fixed... But yes, if there is still the issue, we should downgrade.
> 
> I can't say, as I'm using PostgreSQL for my customers, I don't use MySQL any more.

Maybe @ctamisier @mraible @skmaingi @mshima can say anything else about this?

**Comment by ctamisier** [comment]
From what I remember, we had the "one-day" bug when using 8.0.19.
8.0.20 fixed this issue but introduced another issue which has been fixed on 8.0.22.

I just retried with the current `main` branch with a monolith+mysql with an entity having a LocalDate and I don't have the issue.
If I manually downgrade to 8.0.19 I have the issue.

Do you have the issue even without adding any additional UTC parameters (such as `TimeZone.setDefault()`) ? (because if I add this one, I have the one-day gap).

**Comment by ctamisier** [comment]
Could you confirm by debugging that you have `defaultTimeZone=UTC` ?  (as you set mysql server to UTC)

(this is from mysql connector)
![image](https://user-images.githubusercontent.com/766263/144568783-a51d5bc0-ac0e-44d5-ac16-4a2189d8477e.png)

**Comment by henry2man** [comment]
@ctamisier Thanks for the directions. Now there are holidays coming, so I won't be able to verify it for a few days. Then I will try to generate a minimal test case to see the impact of the change in dependency, at least in relation to the problem I have now.
