### ISSUE TITLE
Simplify authoring modules: support for `npm link`

### ISSUE THREAD

**Issue by aanno** [jhipster/generator-jhipster#11747]
##### **Overview of the feature request**

I'm trying to develop a jhipster module and found that unnecessary difficult. As it is a module with post entity hook, I would like to test it on an (other) jhipster project. However

```bash
# in (other) jhipster project
$ npm link ~/scm/aanno/generator-jhipster-module-aanno
...
$ jhipster --with-entities
...
Could not compose module generator-jhipster-module-aanno. 
Make sure you have installed the module with 'npm install -g generator-jhipster-module-aanno'
...
``` 
makes development unnecessary difficult, even with

```bash
$ cat .yo-rc.json
...
    "otherModules": [
      {
        "name": "generator-jhipster-module-aanno",
        "version": "0.0.0"
      },
...
``` 

and

```bash
$ cat package.json
...
  "devDependencies": {
    "generator-jhipster-module-aanno": "0.0.0",
...
``` 

##### **Motivation for or Use Case**

I would expect that `jhipster` recognizes the use of `npm link` and will simply use that, even for modules and blueprints.

**Comment by kaidohallik** [comment]
I confirm this issue. Linked modules were supported in hooks in JHipster v6.7.0 but removed in v6.8.0. I made PR #11749 for restoring hooks support for linked modules.

**Comment by mshima** [comment]
@murdos I think we should make unify blueprint and module support for jhipster 7.
* Rename the module entity and app generator to ex: jhipster-post-app and jhipster-post-entity.
* Set cli to something like `jhipster --add-ons blueprint,module`.
* And at try to load every jhipster-post-* for every add-on (current blueprint or modules).

What do you think?

**Comment by aanno** [comment]
Just for the records: Linking (i.e. `npm link` or `yarn link`) now works again, but I have to use `jhipster --with-entities --prefer-local --skip-install`.

**Comment by mshima** [comment]
prefer-local is enabled by default, not needed.
skip-install is to skip `npm/yarn install` at jhipster end, otherwise it will override current linked module with the version specified at packages.json.

**Comment by kaidohallik** [comment]
I also confirm that #11756 fixed this issue, thanks @mshima for providing correct fix and thanks @aanno for opening this issue.
