### ISSUE TITLE
field 'FROM' allowed in JDL

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#11741]
##### **Overview of the issue**
I have a project using Angular and Postgres. Following entity won't rise an error:

```
entity ProductMove {
    from String
    to String
    date ZonedDateTime
    documentSerie String
    documentNumber String
    quantity Double
}
```

This will make some tests fail as the generated query contains `PRODUCTMOV28_.FROM[*] AS FROM5_43_28_` for that particular field:

```
expected \"identifier\"; SQL statement:\nselect manufactur0_.id as id1_36_0_, 
```

##### **Motivation for or Use Case**

Field `FROM` should not be allowed as it will make tests fail.

##### **Reproduce the error**
Import a JDL file containing shuch entity.

##### **Suggest a Fix**
Add `FROM` as a reserved word for fields.

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
factur-app@1.2.5 /IdeaProjects/FacturApp
├── generator-jhipster@6.8.0
└─┬ generator-jhipster-primeng@3.0.0
  └── generator-jhipster@6.8.0  deduped

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "packageName"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "Facturapp",
    "packageName": "packageName",
    "packageFolder": "packageFolder",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "caffeine",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "secret",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "spacelab",
    "clientThemeVariant": "primary",
    "testFrameworks": [],
    "jhiPrefix": "fa",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": [],
    "creationTimestamp": 1580194041932
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20191016_371 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)

git version 2.20.1 (Apple Git-117)

node: v11.15.0

npm: 6.14.4

yeoman: 3.1.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
<details>
<summary>ProductMove .json</summary>
<pre>
{
    "name": "ProductMove",
    "fields": [
        {
            "fieldName": "from",
            "fieldType": "String"
        },
        {
            "fieldName": "to",
            "fieldType": "String"
        },
        {
            "fieldName": "date",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "documentSerie",
            "fieldType": "String"
        },
        {
            "fieldName": "documentNumber",
            "fieldType": "String"
        },
        {
            "fieldName": "quantity",
            "fieldType": "Double"
        }
    ],
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "product",
            "otherEntityRelationshipName": "productMove",
            "relationshipValidateRules": "required",
            "relationshipName": "product"
        }
    ],
    "changelogDate": "20200421002019",
    "entityTableName": "product_move",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": true,
    "fluentMethods": true,
    "readOnly": false,
    "clientRootFolder": "",
    "applications": "*"
}
</pre>
</details>

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by ruddell** [comment]
`From` is already a reserved word for PostgreSQL ([code](https://github.com/jhipster/jhipster-core/blob/0504758b8677626c5eeb4f6b587836666d1fa2ef/lib/core/jhipster/reserved_keywords/postgresql.js#L62)), which means it should update the field name in the table with a prefix of `jhiPrefix`.  You should see:
- `fa_from` in the liquibase XML changelog for ProductMove
- `@Column(name = "fa_from")` above the `from` field in `ProductMove.java`

Ran `./mvnw test` with your config and the generated tests pass. Do you have any more steps to help reproduce?

**Comment by amatosg** [comment]
being the dumb a** that I'm, I changed the generated code myself just because _I didn't like it_

Closing the issue.
