### ISSUE TITLE
Monetary Amount

### ISSUE THREAD

**Issue by mmuruev** [jhipster/generator-jhipster#11750]
Current Jhipster (6.8) does support for currencty, but lack of monetary amount type, for example https://www.postgresql.org/docs/current/datatype-money.html and ![Java Money](https://www.baeldung.com/wp-content/uploads/2017/03/javax-monetary3-1.png)
Will be nice to have such feature

**Comment by pascalgrimaud** [comment]
plz, provide your JDL at https://github.com/jhipster/jdl-samples

**Comment by mmuruev** [comment]
I'm asking about MonetaryAmount type field how JDL will help here?

**Comment by pascalgrimaud** [comment]
Oh ok, sorry. I read too quickly. 
So it's a feature request. 

Then, did you already test it in a real JHipster project ? Did you check liquibase, compatibility with H2 in dev, etc ? Inject data with fake data ? 

If everything works fine, would you like to contribute and provide this feature ?

**Comment by yelhouti** [comment]
@mmuruev this how I do this, I always store the value in smalles possible units (cents for dollars...) this prevents dealing with rounding problems two in javascript (which famous for this) if we use multiple currencies, I just add the currency field and that's it.
Only front end needs to know about how many decimals are per currency and I store the value there.

**Comment by MathieuAA** [comment]
@mmuruev are you talking about JSR 354?

**Comment by mmuruev** [comment]
Yes exactly about this

**Comment by MathieuAA** [comment]
As Pascal said, would you like to contribute and add this? We have quite a big number of issues on our hand here, and if you're motivated to contribute, that'd be great.

**Comment by pascalgrimaud** [comment]
As no answer from you, I suppose you don't want to contribute to provide this feature @mmuruev ?

Just for your information, it's a lot of work:
- add the new type for PostgreSQL, in sub generator entity
- check if liquibase works fine, specially for config with h2disk + PostgreSQL, h2mem + PostgreSQL
- check liquibase diff
- add unit tests
- add integration tests
- add gatling tests
- check with service, serviceImpl, DTO, pagination etc
- work on all main fronts: Angular, React - don't forget Vue.js too (in blueprint)
- add front tests
- add e2e tests
- work on JDL (jhipster-core)
- it would be nice to add this in Kotlin, and other blueprints too

Then, once it's achieve, plz add this new type in our main CI
Check in jhipster-daily-builds too.

If you want to contribute to this feature, just tell me, and I'll reopen this ticket.

For now, I'm closing this ticket and it's a lot of work to achieve and I don't think in our core team, we have the bandwidth to do this.
