### ISSUE TITLE
Country and Currency info

### ISSUE THREAD

**Issue by mmuruev** [jhipster/generator-jhipster#11752]
It will be nice to have such 'constant' entities as Country and Currency by Jhipster, of course, on-demand! Or there is something already existed?

**Comment by atomfrede** [comment]
Hi @mmuruev I guess you have something mind, that JHipster provides e.g. a jdl to store countries and currencies in database? We have not something like this. It sound like a perfect use case for a module which can be applied to a jhipster application and not something which will made it into the core generator. 
If you like to work on a module we are happy to help as much as possible.

**Comment by pascalgrimaud** [comment]
That's what we had already discussed:
- default JDL, which can be applied to every project : list of countries is the perfect example

**Comment by pascalgrimaud** [comment]
should go to https://github.com/jhipster/jdl-samples

**Comment by pascalgrimaud** [comment]
Feel free to open a PR there -> https://github.com/jhipster/jdl-samples
For now, let's close this.
