### ISSUE TITLE
csrf should not be enabled with OAuth2 authType

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#11759]
##### **Overview of the issue**

@mraible I can see in a newly generated project with OAuth2 that csrf is enabled, this not the case when the JWT type is enabled. I totally agree with the JWT case since the auth token prevents csrf attacks but why do we keep it in the oauth2 auth type.
Am I missing something?
@mraible maybe you could help :)

[X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
OAuth 2.0 is similar to session-based authentication in that the access token is stored in the session. The client and server still communicate via cookies. And if you're going to use cookies, you should do CSRF. 

We could do SameSite=Strict as an alternative to CSRF, but I don't think it's supported in all browsers.

https://web.dev/samesite-cookies-explained/

**Comment by yelhouti** [comment]
@mraible always forget that detail, we are using OAuth2 but not with tokens, but using the back channel... which in my opinion defies the purpose but hey we already discussed that. Sorry for bothering again.
could we rename it to OIdC by the way, since it is what we are using know (audience validation...)
