### ISSUE TITLE
Creating an application - 401 Unauthorized

### ISSUE THREAD

**Issue by Rigobert** [jhipster/generator-jhipster#1175]
Hi,
After the creating an application, the first it to the localhost:8080 gave me an 401 unauthorized status code on the following request : 

angular.js:9818 GET http://localhost:8080/api/account?cacheBuster=1424435935121 401 (Unauthorized)

![401](https://cloud.githubusercontent.com/assets/890431/6286395/52f5c38e-b907-11e4-82d7-538e1163861a.png)

**Comment by jdubois** [comment]
First request gives you a 401, as you are not logged in, this is the standard REST response code when you are not authorized.

**Comment by Rigobert** [comment]
For sure.
But why doing this request if it isn't necessary ?

**Comment by jdubois** [comment]
It's necessary, in order to know if you are logged in or not.
There is automatic login with a cookie, for example, so when you arrive we have no idea if you are logged in or not
