### ISSUE TITLE
Sorting icon is not changing any more in Angular

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#11762]
##### **Overview of the issue**

In Angular app audits, user-management and entities with pagination sorting icon is not changing any more.

Regression from PR #11262 from this changed line: https://github.com/jhipster/generator-jhipster/pull/11262/files#diff-e4d800620d73178a8f853c368c1d5011R38

In https://github.com/FortAwesome/angular-fontawesome/blob/master/CHANGELOG.md is note for version 0.6.0:  
`FaIconComponent.iconProp` was removed. Use `FaIconComponent.icon` instead.

So in `ng-jhipster` should change icon via property `icon` instead of property `iconProp`. Will do PR for fix in `ng-jhipster`.

##### **Motivation for or Use Case**

Sorting icon should reflect which column is sorted and in which order.

##### **Reproduce the error**

Generate Angular app and try to click sorting icons in audits, user management or entities with pagination.

##### **Related issues**

Regression from #11262

##### **Suggest a Fix**

In `ng-jhipster` use `FaIconComponent.icon` instead of `FaIconComponent.iconProp`.

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT c:\projects\teest\jhipster-sorting-icon
`-- generator-jhipster@6.8.0  -> c:\projects\kaido-github\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1589105597581,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": ["et"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity MyEntity {
  myField1 String,
  myField2 String
}
paginate MyEntity with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

git version 2.26.2.windows.1

node: v12.16.2

npm: 6.11.3

yeoman: 3.1.1

yarn: 1.17.3

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.4, build 8d51620a

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
I made jhipster/ng-jhipster#128 for fix. To close this issue the roadmap is:
* merge jhipster/ng-jhipster#128
* make a new release of the ng-jhipster
* make a PR in the generator-jhipster to use a new version of the ng-jhipster
* merge PR in the generator-jhipster

**Comment by pascalgrimaud** [comment]
@kaidohallik : thanks, I'll try to do the release of ng-jhipster in few hours, after my day work
