### ISSUE TITLE
Allow code generation without database

### ISSUE THREAD

**Issue by jkransen** [jhipster/generator-jhipster#11775]
##### **Overview of the feature request**

Allow code generation without database, so a developer can implement mapping to an unsupported database. 

##### **Motivation for or Use Case**

When I choose "no database" during initial generation, I am not able to do a JDL import, getting an error that there is no database. This was a deliberate choice, and I still want to be able to use the generation functionality up to the services layer and domain classes. 

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
You should be able to use Angular CLI to generate Angular components. Most everything in JDL depends on entities being created. Entities expect a database to exist.

**Comment by jkransen** [comment]
I see your point, but there is still some java code generated that is still reusable without JPA. REST endpoint, service, domain class. Now I generated an application based on PostgreSQL, and all I had to change was replace the Repository with something custom made. But I can also see that you would want to have a running application at the end of generation, without stubs.

**Comment by MathieuAA** [comment]
> When I choose "no database" during initial generation, I am not able to do a JDL import, getting an error that there is no database. This was a deliberate choice, and I still want to be able to use the generation functionality up to the services layer and domain classes.

What kind of error? can you copy/paste it here please?

**Comment by jkransen** [comment]
```
jeroen@xps:/tmp/dummy  (master) $ jhipster import-jdl jhipster-jdl.jh
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing import-jdl jhipster-jdl.jh
INFO! Options: from-cli: true, inline: 
INFO! Found .yo-rc.json on path. This is an existing app
INFO! The JDL is being parsed.
INFO! Found entities: CalendarBlockade, CalendarPrice, Station.
INFO! The JDL has been successfully parsed
INFO! Generating 3 entities.

Found the .jhipster/CalendarBlockade.json configuration file, entity can be automatically generated!

ERROR! Error: The entity cannot be generated as the application does not have a database configured!

```

**Comment by MathieuAA** [comment]
@jhipster/developers should we support this use-case?

**Comment by mshima** [comment]
This can be interesting to create new kinds of blueprints, but not sure we should.

**Comment by deepu105** [comment]
I think its already possible to choose no database when doing microservices

**Comment by murdos** [comment]
I think we should support it indeed. 
It's already possible to generate client side only for a monolith, using `--skip-server` flag. 
However in that case you must provide the target database using `--db` (I think it's only for the H2 console). IMO we should make this parameter optional, and assume that no H2 console will be available.

**Comment by pascalgrimaud** [comment]
After reading this, I think it's too specific, and I'm not sure we should put effort to support this, unless the team think it's absolutely a must have feature.
JDL + entities are here for application with database. If you don't have a database, you can't use it.
The main reason is : we can't generate something which will work out of the box

We already provide sub generators like : spring-controler, spring-service for that.

What you can do is, to achieve your need is to:
- generate project 1 without database
- generate project 2, same option but with database
- generate the entities in project 2
- copy/paste the files you want from project 2 to project 1 (maybe exclude liquibase, repository, integration test, etc) -> it will be hard to know what to keep / what to remove here, as it's specific to your need
- update your services, customize your code etc

For these reasons, I'm closing this.
Feel free to comment, to argue if you think it's a must have feature.
