### ISSUE TITLE
Allow choice of language without i14n

### ISSUE THREAD

**Issue by jkransen** [jhipster/generator-jhipster#11776]
##### **Overview of the feature request**

When i14n is not chosen, allow generation of non-English default language.

##### **Motivation for or Use Case**

When i14n is selected, a default language can be set, together with additional lanugages. When i14n is disabled, there is no prompt for what the language should be and it is set to English as default. This makes it impossible to generate an application with just one language other than English. 

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
You can use i18n, select e.g. german as default language and don't select another language, which should give you the desired result (except having a i18n framework added and in place).

**Comment by pascalgrimaud** [comment]
The answer from @atomfrede is correct, that's the way how to do it today.
As there is no issue, I'm closing this.
