### ISSUE TITLE
Set VM timezone to default UTC

### ISSUE THREAD

**Issue by Blackdread** [jhipster/generator-jhipster#11780]
This might be a breaking change for some.

See PR: https://github.com/jhipster/generator-jhipster/pull/11779

##### **Overview of the issue**

I have recently used some libraries (ORM, others) that use ```ZoneId.systemDefault()``` to format (Instant, LocalDate, etc) and save to DB which result in incorrect date stored.

The ```serverTimezone=UTC``` or other options for DB connection string does not solve the issue.

##### **Motivation for or Use Case**

Software should use UTC everywhere, and ignore the fact that server might be miss-configured (not set on UTC).

Also it may solves issues for some database library that use ```ZoneId.systemDefault()``` which can return something else that UTC if not configured for server/PC.

##### **Reproduce the error**

Just do not set the VM default, have a server/PC configured outside of UTC.

##### **Suggest a Fix**

See PR: https://github.com/jhipster/generator-jhipster/pull/11779

##### **JHipster Version(s)**

All

##### **JHipster configuration**

Any

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Any

##### **Browsers and Operating System**

Any

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@Blackdread : is it related to https://github.com/jhipster/generator-jhipster/issues/11740 ? Maybe the same issue ?

**Comment by Blackdread** [comment]
Yes saw it after created this issue and PR.

My use case is I use "Exposed" from Jetbrains; it uses ```ZoneId.systemDefault()``` to format ```Instant```, etc to save into the DB which result in wrong data saved.

But I think there might be many other libraries that depends on the system default zone which should always be in UTC.
I know many people won't agree but UTC is the easiest approach and most accurate one in almost all cases.
I can understand that in #11740 , some may want to let user to define it in the application.yml or follow server/PC configuration but you will 99% of the time have people install the software on any machine and never touch the configuration of the machine, so I think the responsibility is back to the software to make it automatic and ignore the server config for the dates (at least).

**Comment by gmarziou** [comment]
One thing that could be surprising for some users is that one of the first thing they'll notice is that their logs will be off dated unless they specify a timezone in logback.xml

**Comment by Blackdread** [comment]
you mean the opposite?
If I set the VM to UTC then logback.xml dates are in UTC.
If I do not set the VM then logback.xml dates are from my system timezone.

My logback.xml does not specify any timezone.

**Comment by gmarziou** [comment]
Yes, that's what I mean: if users wants log timestamps in local timezone with a JVM in UTC they must configure their message pattern as `%date{HH:mm:ss.SSS, Europe/Paris}` for example.

**Comment by avdev4j** [comment]
TBH, I'm not very confortable with this kind of solution.
Storing date fields as UTC seems to be legit since we can't know which timezone has been used to generate them. 
But it's a bit different for the JVM. Users could want to manage dates on they own timezone and then store them in UTC, couldn't them?

**Comment by mraible** [comment]
Closing because @avdev4j is not comfortable with it.

**Comment by yelhouti** [comment]
If by user you mean developer, if they want to they would want the same for the DB I guess.
If you mean end users, this what ZoneDateTime... is used for, and everything sent from the frontend with that different timezone keeps it both in java and in the database, no matter how the JVM is configured.
Or am I missing something?

**Comment by Blackdread** [comment]
Back-end only.
You usually send time using instant to front-end, then they use Moment.js (or other) to show the date in timezone of user's browser or business logic.
