### ISSUE TITLE
JHipster 6.8.0 - 404 after logging (Traefik, OAuth2)

### ISSUE THREAD

**Issue by Ajrarn24** [jhipster/generator-jhipster#11782]
##### **Overview of the issue**

Hello JHipster team,

When dealing with docker-compose using Traefik and OAuth2, I get a 404 error after logging in Keycloak.

##### **Motivation for or Use Case**

After connection to Keycloak, user should be redirected to the application and not get 404.

##### **Reproduce the error**

Please consider following jdl describing 2 microservices (one gateway type, one microservice type), using Consul and OAuth2/OIDC.

<details>
  <summary>JDL definitions</summary>
  <pre>
     application {
  config {
    baseName gateway
    applicationType gateway
    packageName fr.test.gateway
    serviceDiscoveryType consul
    authenticationType oauth2
    prodDatabaseType postgresql
	searchEngine elasticsearch
    cacheProvider hazelcast
    enableHibernateCache true
    enableSwaggerCodegen true
    buildTool maven
    clientFramework angularX
	clientTheme sketchy
    clientThemeVariant primary
    useSass true
    nativeLanguage en
	languages [en]
    websocket spring-websocket
    testFrameworks [protractor,cucumber,gatling]
  }
  entities *
}
application {
  config {
    baseName appli
    applicationType microservice
    packageName fr.test.appli
    serviceDiscoveryType consul
    authenticationType oauth2
    prodDatabaseType postgresql
	searchEngine elasticsearch
	cacheProvider hazelcast
    buildTool maven
    serverPort 8081
    websocket spring-websocket
    enableSwaggerCodegen true
    nativeLanguage en
	languages [en]
  }
  entities *
}
  </pre>
  </details>

After creating these 2 microservices using jhipster import-jdl, I have updated two files following documentation [here](https://www.jhipster.tech/traefik/)

- webpack.common.js

`...
new BaseHrefWebpackPlugin({ baseHref: '/services/gateway/' }),
 ...`

- SecurityConfiguration.java

`.and().oauth2Login().defaultSuccessUrl("/services/gateway/").and()`

After starting everything with docker-compose up -d command, choosing Traefik to work with Consul:

- Open application using [http://localhost/services/gateway/](http://localhost/services/gateway/) 
- Click on **Account/Sign** in in the interface
- Provide login information (admin/admin) in Keycloak screen and validate
- 404 error on URL starting like this: [http://localhost/login/oauth2/code/oidc?state=](http://localhost/login/oauth2/code/oidc?state=)

If I change URL manually like this: [http://localhost/services/gateway/login/oauth2/code/oidc?state=](http://localhost/services/gateway/login/oauth2/code/oidc?state=), I am authenticated as **admin** and application is working fine.

##### **Related issues**

Seems to be very similar with [#9769](https://github.com/jhipster/generator-jhipster/issues/9769)
But, if I'm not wrong, following documentation [here](https://www.jhipster.tech/traefik/) was supposed to solve the issue.

##### **Suggest a Fix**

Not sure about what could be done but modification in SecurityConfiguration.java doesn't seem to redirect as expected.

##### **JHipster Version(s)**

JHipster 6.8.0
Not tested the same on previous versions.

##### **JHipster configuration**

Please consider following jdl describing 2 microservices (one gateway type, one microservice type), using Consul and OAuth2/OIDC.

<details>
  <summary>JDL definitions</summary>
  <pre>
     application {
  config {
    baseName gateway
    applicationType gateway
    packageName fr.test.gateway
    serviceDiscoveryType consul
    authenticationType oauth2
    prodDatabaseType postgresql
	searchEngine elasticsearch
    cacheProvider hazelcast
    enableHibernateCache true
    enableSwaggerCodegen true
    buildTool maven
    clientFramework angularX
	clientTheme sketchy
    clientThemeVariant primary
    useSass true
    nativeLanguage en
	languages [en]
    websocket spring-websocket
    testFrameworks [protractor,cucumber,gatling]
  }
  entities *
}
application {
  config {
    baseName appli
    applicationType microservice
    packageName fr.test.appli
    serviceDiscoveryType consul
    authenticationType oauth2
    prodDatabaseType postgresql
	searchEngine elasticsearch
	cacheProvider hazelcast
    buildTool maven
    serverPort 8081
    websocket spring-websocket
    enableSwaggerCodegen true
    nativeLanguage en
	languages [en]
  }
  entities *
}
  </pre>
  </details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Issue doesn't seem to be linked to entity issue.

##### **Browsers and Operating System**

Windows 10 Professional (1903)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by chelfe** [comment]
I would like to take this ticket.

**Comment by mraible** [comment]
Go for it!

**Comment by chelfe** [comment]
I claim my money :) https://opencollective.com/generator-jhipster/expenses/25558

**Comment by pascalgrimaud** [comment]
@chelfe : approved
