### ISSUE TITLE
Can I contribute my JHipster tutorial to the web site?

### ISSUE THREAD

**Issue by ksilz** [jhipster/generator-jhipster#11783]
##### **Overview of the feature request**

Last year, I published a three-part tutorial on JHipster on my blog:
- [Part 1](https://betterprojectsfaster.com/learn/tutorial-jhipster-docker-01/) explained how it saved my project. It's a motivation for why you should use JHipster.
- [Part 2](https://betterprojectsfaster.com/learn/tutorial-jhipster-docker-02/) explains how you install JHipster and generate your first application with it. The JDL for the application (a simple online shop) is included. Then it takes you through all the screens of the JHipster application.
- [Part 3](https://betterprojectsfaster.com/learn/tutorial-jhipster-docker-03/) first explains how to set up IntelliJ or Eclipse and then import the project into these two IDEs. 

So is there a way that some of that content could become part of the JHipster web site?
##### **Motivation for or Use Case**

Here's the value that I think my tutorials add:
- [Part 1](https://betterprojectsfaster.com/learn/tutorial-jhipster-docker-01/) gives motivation for using JHipster from a different perspective than the official web page. First of all, I wrap it int the story of my first JHipster project. I also point out three problems that I believe are common for Java developers (see below) and then show how JHipster solves them. I also list reasons why JHipster may not be right for you and how you can use JHipster "piecemeal".
  - Are you or your team struggling with Angular, React, NoSQL, or microservices?
  - Uncertainty about how DevOps, containers, and the cloud impact Java?
  - Can't find the results-oriented online training for these new technologies?
- [Part 2](https://betterprojectsfaster.com/learn/tutorial-jhipster-docker-02/) has a bit more detail on installing JHipster and includes a walkthrough of all the admin screens. I think these aren't well documented on the JHipster web site.
- [Part 3](https://betterprojectsfaster.com/learn/tutorial-jhipster-docker-03/) provides detailed instructions on how to set up IntelliJ or Eclipse and which settings to tweak to import it. It then walks through the build files and the source. It has more than 100 screenshots.

**Comment by atomfrede** [comment]
Wow @ksilz thats a lot of content, very nice from a quick look at it and very detailed! We could at least link it on our website and tweet about it I would say.

**Comment by atomfrede** [comment]
@ksilz FYI this is my first proposal how we could put your tutorial on our homepage https://github.com/jhipster/jhipster.github.io/pull/962

**Comment by deepu105** [comment]
closed vai jhipster/jhipster.github.io#962

**Comment by ksilz** [comment]
@atomfrede Thank you for getting my tutorial on the home page!

There are a couple more points I'd like to discuss with you. In general, I spent a lot of time creating content that I think could be useful in other places of the JHipster web site.

**IDE Set-up**
The [JHipster web site section on IntelliJ](https://www.jhipster.tech/configuring-ide-idea/) is pretty bare-bones. Compares this [to my section](https://betterprojectsfaster.com/learn/tutorial-jhipster-docker-03#intellij-existing-installation): It leads you step-by-step through plug-in selections, compiler & build settings, and project import all the way until you actually run the project. 
Eclipse is in better shape: There's more content on the JHipster site. But [my section](https://betterprojectsfaster.com/learn/tutorial-jhipster-docker-03#eclipse-existing-installation) 
tells you what plug-ins you need and has additional Eclipse settings you need.

Now documenting IDE configuration is a thankless job. IDEs get major new releases 3-4 times a year, the plug-ins change all the time, and JHipster changes, too. I'm happy to **update both the Eclipse & IntelliJ section with content from my tutorial**. I'm also happy to **keep the IntelliJ section updated at least for the next year**, because I'm developing with JHipster & IntelliJ daily. I don't feel comfortable maintaining the Eclipse section because I don't use Eclipse.

**Feature Overview**
Two of the benefits of JHipster are entity code generation and built-in admin screens. I don't think the JHipster web site actually shows any of these. [My tutorial does](https://betterprojectsfaster.com/learn/tutorial-jhipster-docker-02#exploring-the-application-layout). I'm happy to **contribute that content to the JHipster web site**.

**Source Code Exploration**
I don't think the JHipster web site details the generated build files or the generated code. [My tutorial does](https://betterprojectsfaster.com/learn/tutorial-jhipster-docker-03#sources-build-system--configuration). I'm happy to **contribute that content to the JHipster web site**.

**Comment by deepu105** [comment]
Hi Karsten, I suggest you contribute such improvements as PRs to the
documents site and we will review and action accordingly

**Comment by ksilz** [comment]
@deepu105 What’s the policy on pictures for the web site? My blog hosts them at [Cloudinary](https://cloudinary.com/). So they are automatically optimised to the device, the browser and the width of the web view.

**Comment by deepu105** [comment]
We put pictures in the same repo as the code. Please look at the existing
source of the docs. You can follow the same
