### ISSUE TITLE
Javadoc for existing entities spoils liquibase migrations

### ISSUE THREAD

**Issue by 62mkv** [jhipster/generator-jhipster#11785]
##### **Overview of the issue**

If an application has been generated from JDL, which upon initial generated looked like that

```
@paginate(pagination)
entity BusinessUnitConfig {
   unitName String required unique minlength(10) maxlength(32)
   defaultLabelQueue String required minlength(1) maxlength(16)
}
```

and then, on subsequent changes, Javadoc has been added to an entity: 

```
/**
* Some documentation here
*
* @author 62mkv
*/
entity BusinessUnitConfig {
...
```

then that javadoc will be included in the Liquibase migrations for those entities on subsequent generation from that same JDL file via `jhipster import-jdl..` command as a "remarks" value on a "table" element, which will lead to those changesets being considered "broken" (as their checksum has changed since previous execution) and whole migration failed

##### **Motivation for or Use Case**

Let's not include new or changed entity javadoc to the liquibase migration (or, if that's not easily possible, let's not include it at all into Liquibase changeset - it feels that added value is less than possible damage)

##### **Reproduce the error**

see above

##### **JHipster Version(s)**

6.8.0

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@62mkv : I agree with you, we should not change the liquibase changelog for this simple "comment" / "remarks". Do you agree @MathieuAA ?

**Comment by pascalgrimaud** [comment]
cc @DanielFran : just found you were the original author of this -> https://github.com/jhipster/generator-jhipster/pull/7454
Do you agree to revert your PR ?

**Comment by DanielFran** [comment]
@pascalgrimaud The descriptions are added in liquibase script from comments in JDL.
This is to document table fields, a good practice in SQL development.
Why should we remove it?

**Comment by pascalgrimaud** [comment]
For the use case above described by @62mkv :
- you use a JDL to generate the entities and the changelog
- you deploy it
- you want to improve the JDL: add some comments in the JDL, add other table
- you could have a typo and change the comment
- once you regenerate the entities, it will add these "remarks", so the changelog has changed -> that's the main issue, described in this ticket

My main question would be: are these remarks important enough to modify the changelog ?

**Comment by DanielFran** [comment]
OK, got it.
It never happen before, maybe this is due now to the recent changes done in liquibase part in generator.

Well, I will do a PR to remove it.

**Comment by murdos** [comment]
Sorry, but I disagree with reverting #7454. Having documentation for table and columns in database is a best practice that we should continue to enforce.

Regarding the specific use case described above, well, in that case you should just review the changes and revert them manually if you've already deployed your application. As far as I know there are lot of case where this is what we recommend.

**Comment by pascalgrimaud** [comment]
Ok then, so my best advice here would be to not add comment on existing entities which has been deployed in production, or at least take care of every changelog
So as it is something we won't fix, I'm closing this
