### ISSUE TITLE
Swagger documentation Authentication Failure

### ISSUE THREAD

**Issue by gojesandeep** [jhipster/generator-jhipster#1178]
I was trying to look at the API inside the Admin login. The Swagger API documentation was not being shown and when I looked at console logs, the object getting returned from localStorage.getItem("token") is null in swagger-ui/index.html. When I looked at the auth.oauth2.service.js and check the line with localStorageService.set('token', response) the token is properly getting set. Checked it by placing console.log(localStorageService.get('token')) below it. Is there some kind of difference where angular is writing to local storage using localStorageService and where browser is reading when calling localStorage.

**Comment by dejewi** [comment]
What version of jhipster do you use?

**Comment by gojesandeep** [comment]
How to check the version.

**Comment by dejewi** [comment]
open Gruntfile.js
and on the begining you will have something similar: 
// Generated on 2015-02-23 using generator-jhipster 2.3.0

**Comment by gojesandeep** [comment]
// Generated on 2015-01-21 using generator-jhipster 2.0.0

**Comment by gojesandeep** [comment]
Are there any instructions on updating the version as I am seeing that jhipster has been upgraded.

**Comment by dejewi** [comment]
this bug was fixed in newer version.
in src/main/webapp/swagger-ui/index.html you should have something like:
            var authToken = JSON.parse(localStorage.getItem("ls.token")).access_token;

**Comment by dejewi** [comment]
How to upgrade:
Update your version of JHipster with:
npm update -g generator-jhipster
And then you can update your project when you run again
yo jhipster

**Comment by gojesandeep** [comment]
Thanks It worked.

**Comment by dejewi** [comment]
You welcome
