### ISSUE TITLE
add "password" option for entity field

### ISSUE THREAD

**Issue by 62mkv** [jhipster/generator-jhipster#11786]
##### **Overview of the feature request**

enable relatively safe approach by default for managing "password" fields in generated entities, for example:
- when created, persist such values in a rather safe, Spring Security-friendly format, for example, BCrypt-ed
- do not allow for editing saved values directly (as it's just a bcrypted value), instead, show blank field when editing, with a warning that previously save value will be lost)

##### **Motivation for or Use Case**

JHipster is used for quickly creating modern CRUD applications. One of possible areas is building configuration UIs for managing setup of other applications. One of configuration aspects is user credentials management. However, JHipster does not allow for anything, that specifically address many concerns, related to user credentials management, in particular, safe password management.

Storing passwords bcrypt-ed will resolve most of security concerns related to this. 

see also https://docs.spring.io/spring-security/site/docs/5.2.4.RELEASE/reference/htmlsingle/#pe-dpe-format

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@62mkv : I don't understand well this ticket.

Is it an enhancement you want to propose ? Change the way we store the password ? 

Is it a feature request ? New field types ?

**Comment by 62mkv** [comment]
Hi Pascal
Yes I want to introduce a special sub-type of entity field (of type String). I want to be able to mark an entity field as storing a "password" value which will result in: 
- immediately upon editing, the value entered will be processed by adaptive one way function, such as bcrypt; and saved in a DB in a way that's compatible with Spring Security (i.e. prefixed with "{bcrypt}", for example)
- editing this value is never possible, as the original value can not be retrieved from the DB, so any editing will just show a blank field
--
Sent from Mail.ru app for Android Saturday, 16 May 2020, 01:59PM +03:00 from Pascal Grimaud  notifications@github.com :

**Comment by atomfrede** [comment]
Should it be possible to overwrite the saved value when entering a new value into the password field (or providing it via api)?

**Comment by 62mkv** [comment]
Not sure if I understand the question, but in my view it should be totally possible to *replace* the value. Just not via editing in traditional sense, as the persisted value is just a one-directional hash
--
Sent from Mail.ru app for Android Wednesday, 20 May 2020, 09:38AM +03:00 from Frederik Hahne  notifications@github.com :

**Comment by vishal423** [comment]
Instead of limiting to a password field (which is a special type), how about supporting the storage of encrypted data in a database column (only backend change). IMO, this is a more common use case.

**Comment by 62mkv** [comment]
what I want to achieve is not _encryption_ at all. it's about applying one-way adaptive function that would create a _hash_ of a password. so that the other application (not JH-based one!) could use this table as it's credentials source with Spring Security

**Comment by 62mkv** [comment]
hi @pascalgrimaud  is it still "waiting for information" ? Let me put forward a more detailed rationale, based on real-world use case:
- we currently build a REST API backend service 
- this service has not any UI, or configurability endpoints - to achieve maximum performance characteristics
- but this service still needs some configuration bits ("masterdata")
- in order to achieve that, we're building a second app, which is JHipster-based (as JHipster allows to quickly define a simple CRUD application, which is exactly what we want here)
- that JHipster-based app (the "config app") has it's own users, defined by default JHipster mechanism as jhi_user table
- now we have a requirement to add authentication also to the "service" itself. but the service users are entirely different audience, compared to "config app users" (the "service users" are essentially our other enterprise applications, while "config app users" are actual humans, with e-mail and such), so we can't just use "jhi_user" table to authenticate service users against service
- there's also a limitation that the "service users" can only authenticate via HTTP Basic, so we can't use "application tokens" or something like that.
- now, we've totally built what we want with JHipster, by just using a String value for password, but I don't much like the fact that any config user now can see all "service users password" plain-text. 
- I could of course implement this "password-hashing" and editing limitations myself, but thought that this might be a generic enough use case so decided to raise this request. 

hopefully now it's enough information! thanks!
- there's also

**Comment by 62mkv** [comment]
huh, it does not display that label anymore.. probably "label removal events" are not reflected in the history.. ok then

**Comment by pascalgrimaud** [comment]
@62mkv : no, it is not labeled as "waiting information", it is as "feature request" now.
We're waiting more comments, specially from core team members to accept or not this feature.

If it's accepted, are you ready to contribute and provide this feature ? It will be a lot of work to achieve this...
- check all database, mysql, psql, mariadb, mongodb, cassandra, etc...
- implement the backend
- try to help other blueprints (Kotlin ...)
- implement the frontend for Angular and React
- don't forget the blueprint Vue.js too
- jhipster-core, to have the option in JDL

But I still think the best solution would be to make a module for that.
You won't depend on us, you can already start all the work and publish your module. Then, if your module is really popular and used a lot, it will be easy to include it directly in the main generator-jhipster.

Let's discuss.

**Comment by 62mkv** [comment]
well, I certainly have not imagined that to be _that_ much work, but then again, I only use JHipster occasionally and certainly am not an expert in this. I can't commit at the moment to anything here, but maybe somebody else will pick it up, I definitely would not mind :)

**Comment by pascalgrimaud** [comment]
I could be nice to have, and the best would be in a module / blueprint.
For now, I'm closing this as we have too much opened tickets
Unless someone plans to start to code this, I can reopen.
