### ISSUE TITLE
Fix frequently failing react builds (e2e)

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#11805]
I think we're all getting tired to see failing react builds.
This is the issue to fix'em.

Even though I'm assigning myself to this issue, anyone is free to contribute and fix them! The goal here is to improve our QoL as contributors.

---

Found issues:
  - StaleElementReferenceError: stale element reference: element is not attached to the page document:  https://github.com/jhipster/generator-jhipster/runs/682093799?check_suite_focus=true
  - `should delete last item` expected 0 got 1 or (10 got 11)
  - Account tests: https://github.com/hipster-labs/jhipster-daily-builds/runs/659933931?check_suite_focus=true#step:18:364

**Comment by pascalgrimaud** [comment]
adding a bounty for this
React builds are flaky since at least 6 months...

**Comment by MathieuAA** [comment]
I'm gonna try the recent changes made by @skmaingi against my private fork with duplicated builds to see if it works

**Comment by pascalgrimaud** [comment]
I'm reopening this, because I need to test if it totally fixed, with the related PRs.

**Comment by skmaingi** [comment]
@MathieuAA @pascalgrimaud Confirm if pull request #11916 has fixed this.

**Comment by mshima** [comment]
If this issue is fixed I think the bounty should be increased an shared between @MathieuAA @skmaingi and @sendilkumarn

**Comment by MathieuAA** [comment]
I wish to give my part to the issue for cypress.

**Comment by sendilkumarn** [comment]
👍 of course for Cypress :)

**Comment by jdubois** [comment]
I'm going to increase the bounty to $300 so it can be shared evenly.
-> Mathieu, I will have a look at how to give $100 to Cypress

And @MathieuAA  what is blocking from closing this issue?

**Comment by MathieuAA** [comment]
Nothing :) I guess I'm so used to have the classic "fixes #XXX" that I've completely forgot about this issue!

**Comment by jdubois** [comment]
Ok then don’t forget to claim your bounties!
@MathieuAA for the $100 you want to give to Cypress I know there’s a way to transfer money directly between 2 collectives and not pay any fee, I need to have a look

**Comment by pascalgrimaud** [comment]
@jdubois : I think @MathieuAA means the issue in JHipster related to support Cypress and replace Protractor :)

**Comment by jdubois** [comment]
Oh then that would be much easier! @MathieuAA can you clarify?

**Comment by MathieuAA** [comment]
I meant that I wished, and still wish, to "add" my part of this bounty to the bounty related to adding cypress for JHipster

**Comment by jdubois** [comment]
@MathieuAA so I'm removing $100 here and adding them to https://github.com/jhipster/generator-jhipster/issues/11961 instead
