### ISSUE TITLE
Registry is not working in FireFox

### ISSUE THREAD

**Issue by vinaykahar** [jhipster/generator-jhipster#11802]
**Steps to reproduce the error:**

- Download the jhipster registry from git.
- Start the registry with command mvn in terminal (This is for linux)
- Go to chrome and hit the url http://localhost:8761 - Everything will work fine.
- Go to FireFox (Version 76) and hit the url http://localhost:8761 - Nothing works fine
- In console of firefox i get the error as **TypeError: clazz.decorators is undefined**
- I was facing the same issue while generating UI for monolithic app and microservice app gateway.

**Comment by atomfrede** [comment]
This is related to https://github.com/jhipster/generator-jhipster/issues/11566

It is already fixed in master and Firefox will fix it with upcoming version 77 think. Feel free to reopen this if you think it's a different error.
