### ISSUE TITLE
ERROR! Error: The table name is too long for Oracle, try a shorter name

### ISSUE THREAD

**Issue by JoaoCharnetTR** [jhipster/generator-jhipster#11801]
##### **Overview of the issue**
When creating entities from a .jh file that has table name with more than 26 characters in length, I'm getting the following error:
**

> Error: The table name is too long for Oracle, try a shorter name.

**
Oracle's limit for table name is 30 characters, so I'm not sure why hipster is giving this error.

##### **Reproduce the error**
create a jh file with the following content:

> entity AlteracoesFaturaImportacao (ALTERACOES_FATURA_IMPORTACAO) {
	IdInvoice BigDecimal,
	DataAlteracao LocalDate,
	CodInformante BigDecimal,
	MotivoAlteracao String,
	IdAlteracao BigDecimal,
	SMaquina String
}

And try to import it with jhipster import-idl YourFile.jh

##### **JHipster Version(s)**

6.8.0

##### **JHipster configuration**

[jhipster_info.txt](https://github.com/jhipster/generator-jhipster/files/4637421/jhipster_info.txt)

[__yo-rc.json.zip](https://github.com/jhipster/generator-jhipster/files/4637425/__yo-rc.json.zip)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

> {
    "name": "AlteracoesFaturaImportacao",
    "fields": [
        {
            "fieldName": "idInvoice",
            "fieldType": "BigDecimal"
        },
        {
            "fieldName": "dataAlteracao",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "codInformante",
            "fieldType": "BigDecimal"
        },
        {
            "fieldName": "motivoAlteracao",
            "fieldType": "String"
        },
        {
            "fieldName": "idAlteracao",
            "fieldType": "BigDecimal"
        },
        {
            "fieldName": "sMaquina",
            "fieldType": "String"
        }
    ],
    "relationships": [],
    "changelogDate": "20200515205000",
    "entityTableName": "alteracoes_fatura_importacao",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "readOnly": false,
    "embedded": false,
    "clientRootFolder": "",
    "applications": "*"
}

##### **Browsers and Operating System**

Mac OS 10.15.4

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/blob/573508eab2024a518e2f94eda8e6f4908bbfe38c/generators/entity/index.js#L336-L337
It was added when oracle support was added 5 years ago.
Probably every table was prefixed with `jhi_`.
Anyway this is not recommended, because when adding relationship it will be cropped.

**Comment by JoaoCharnetTR** [comment]
I understand. The "problem" is that I'm doing a reverse engineer from an Oracle database to see how it would look on the web. This is a legacy desktop application.
I would not like to change the existing database tables/columns/constraints. I'm just creating the application.
Any idea what I can do (besides trimming the table name)?

**Comment by mshima** [comment]
You can try:
```
@skipCheckLengthOfIdentifier
entity AlteracoesFaturaImportacao (ALTERACOES_FATURA_IMPORTACAO) {
...
```

or
`jhipster --skip-check-length-of-identifier`

**Comment by JoaoCharnetTR** [comment]
I'll give it shot.

Thanks

**Comment by atomfrede** [comment]
Skipping the length check should do it. As @mshima said we did prefix our tables with `jhi_` once by default.

**Comment by JoaoCharnetTR** [comment]
I have tried the option in the command line argument, but got the same error.

>  jhipster import-jdl ../../gcrt-architecture_generate-jdl/gen2.jh --skip-check-length-of-identifier
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing import-jdl ../../gcrt-architecture_generate-jdl/gen2.jh
INFO! Options: **skipCheckLengthOfIdentifier**: true, from-cli: true, skip-check-length-of-identifier: true, inline:
INFO! Found .yo-rc.json on path. This is an existing app
INFO! The JDL is being parsed.
The entity AlteracaoProcessoImportacao is being updated.
ERROR! Error: The table name is too long for Oracle, try a shorter name.
You can specify a different table name in your JDL file or change it in .jhipster/AlteracaoProcessoImportacao.json file and then run again 'jhipster entity AlteracaoProcessoImportacao.'
