### ISSUE TITLE
Document new requirements for Windows user due to BrowserSync support

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1180]
According to BrowserSync doc, there is an issue when  npm installing for [Windows users](http://www.browsersync.io/docs/#windows-users) who may have to install Visual Studio 2013 due to use of gyp.
I tested on my PC and it works but I have VS installed, it would help if someone on Windows without VS could try.

**Comment by jdubois** [comment]
I can't test it, but we don't have any other reports about this. The BrowserSync doc talks about "compiling", I'm not sure we compile anything...
Can anybody validate this issue?
Otherwise we could have another grunt task with the old "livereload", for Windows users who have that issue.

**Comment by atomfrede** [comment]
I've created a new application successfully on a windows machine to check PR #1198. I've not tested if browser sync worked but I'll give it a try tomorrow.

**Comment by gmarziou** [comment]
I also have found a Win machine without visual studio to test, I'll try tomorrow.

**Comment by atomfrede** [comment]
On my machine (windows 8.1 *without* Visual Studio) creating an application and running with ```mvn spring-boot:run`` and ``grunt serve`` works quite well.

**Comment by gmarziou** [comment]
I confirm it's also working on my machine

**Comment by mraible** [comment]
Oops, wrong ticket number in my commit message. Should've been for #1880.
