### ISSUE TITLE
JDLs with blueprints not working.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#11815]
##### **Overview of the issue**

When importing jdls with blueprints the execution fails.

##### **Motivation for or Use Case**

JDL with blueprints should work.

##### **Reproduce the error**

`jhipster import-jdl foo.jdl` when foo.jdl have blueprints.

##### **Suggest a Fix**

Run blueprint lookup after the jdl has been imported.
Currently blueprints lookup is done before importing jdl due to custom commands and shared options.

##### **JHipster Version(s)**

6.9.0

##### **JHipster configuration**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tonterias** [comment]
I took the blog example https://github.com/jhipster/jdl-samples/blob/master/blog.jh and Apply JDL Model to a project using Jhipster Online and failed. It failed also in local when I tried to start the backend with gradlew:

> Task :compileJava FAILED
Note: Hibernate JPA 2 Static-Metamodel Generator 5.4.15.Final
D:\JHipster\miturno3\src\main\java\es\miturno\web\config\CloudDatabaseConfiguration.java:24: error: Duplicate `@ConfigurationProperties` definition for prefix 'spring.datasource.hikari'
    public DataSource dataSource() {
                      ^
1 error

![image](https://user-images.githubusercontent.com/11610877/82378382-4cbacf00-9a25-11ea-9c0b-3b472ae1d675.png)

**Comment by mshima** [comment]
@Tonterias your error is not related with this issue.

**Comment by pascalgrimaud** [comment]
@mshima : is it the same ticket than https://github.com/jhipster/generator-jhipster/issues/9870 ?

**Comment by mshima** [comment]
@pascalgrimaud no.
Jdls:
`blueprints [foo, bar]`
Is not finding the blueprints at the first run.

The other Issue is to allow blueprints to add custom configs:
`myByBlueprintConfig foo`
@MathieuAA didn't like my solution for that one.

I have a work to fix this bug but is a follow-up to https://github.com/jhipster/generator-jhipster/pull/11770
I am waiting it to get approved.
