### ISSUE TITLE
[FR] add initial liquibase files inside a folder

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#11818]
##### **Overview of the feature request**
Create entities and relationships inside `config/liquibase/changelog/init` (this is only a proposal)

##### **Motivation for or Use Case**
When an application is generated, all the entities and relationship files are generated inside `config/liquibase/changelog/`. If we're constantly making changes (maybe adding fields to support new features, which is my case), new changelogs will be also added to the sale folder. After a few months that folder will contain many files! I managed to reduce the amount of file when I migrated from MySQL to PostgreSQL (using `identity`, btw :wink:).

Is my opinion that having all the files generated by entities and its relationship in a separate folder would make liquibase migration more organized.

##### **Related issues or PR**

None that I know of.

-   [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by vishal423** [comment]
>  If we're constantly making changes (maybe adding fields to support new features, which is my case), new changelogs will be also added to the sale folder.

How about grouping changelogs per release version? That would give a consolidated view of database modifications per product release.

**Comment by amatosg** [comment]
I think that would complicate things as you would have to know when a version is being released. My idea is just to put the initial files that get generated by creating an entity (basically the 2 files for each entity) in a special folder (like `init` or something similar).

**Comment by ecostanzi** [comment]
Hello @amatosg. Why not putting your changelogs in a different folder? Jhipster changelogs stay in `config/liquibase/changelog/`, your custom changelogs in `config/liquibase/changelog/custom`. Changing the folder to the liquibase changelogs might cause problems when upgrading to a newer jhipster version.

**Comment by gmarziou** [comment]
This would be a breaking change for existing projects upgrading because Liquibase stores migration file path in DATABASECHANGELOG table and so an upgraded application would just fail at start.

**Comment by amatosg** [comment]
What @gmarziou says is true. A change on where the files are would break existing projects which is a no-no. I forgot about existing projects (mine being one of them, duh!).

@ecostanzi this could make more sense, but I think having a clean view would be more beneficial. You would still have to see all the generated changelogs.

Anyways. Moving changelogs out of its original location isn't possible :(
