### ISSUE TITLE
jhipster dependencies: upgrade from v6.8.0 to v6.9.0

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#11812]
This ticket is just for a bounty, for all the work done in https://github.com/jhipster/jhipster by @DanielFran for this release v6.9.0 and the previous
So the bounty is for you

**Comment by DanielFran** [comment]
Manu thanks @pascalgrimaud , really apreciate

**Comment by DanielFran** [comment]
@pascalgrimaud Bounty claimed: https://opencollective.com/generator-jhipster/expenses/18468

**Comment by pascalgrimaud** [comment]
approuved, so can be closed
