### ISSUE TITLE
Proposal: Code parsing and switching to schematics AKA call me crazy

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#11810]
##### **Overview of the feature request**
Hi everybody,

I am writing this knowing that there is little to no chance it would be implemented in JHipster, but hey lets discuss it for the sake of argument.

the way Jhipster templating is done today is by using ejs... it requires all the logic for a specific destination file to go in the same file (if we want the template to still be readable) and for people who wants to add a very small feature (example just an annotation to some field) it either needs to:
- Option 1: have it's own blueprint that overrides the specific files, and keep it update with the default generator to have the latest features
- Option 2: have a blueprint write some complex function with parsing... 

Pros and Cons:
Option1:
pros:
- is the easiest to get up and running (ie on the short term)

cons:
- maintaining it is a PITA unless your code is merged in the main generator.
- not composable

Option2:
pros:
- composable

cons:
- hard to implement (parsing...)
- slow (since writing is done to disc we will need read parse write for each change)

The ability to have composable generation is very powerful and opens a lot of possibilities while allowing for a main code base much easier to maintain...

So how we could we fix Option 2: (ie the crazy part)
1- Have a parser for each language we want to implement, I think this already being done in some form with prettier if I am not mistaken.
2- have the ability to modify the file tree and convert back to a string/file.
3- have everything done in memory instead of disk, and here we could take advantage of how schematics does things.

Happy to hear any comments/remarks !!!

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
> So how we could we fix Option 2: (ie the crazy part)
> 1- Have a parser for each language we want to implement, I think this already being done in some form with prettier if I am not mistaken.
> 2- have the ability to modify the file tree and convert back to a string/file.

This probably can be done with https://www.npmjs.com/package/java-parser
Or just use regexp.
I have done this for js files with espree.

> 3- have everything done in memory instead of disk, and here we could take advantage of how schematics does things.

JHipster writes everything to memory and the blueprint should use memory too.
this.fs is a instance of mem-fs-editor.

**Comment by yelhouti** [comment]
@mshima 
I was talking about the whole process using this strategy not only on blueprints.
So when a feature is appreciated it is added to the main blueprint.
Having two strategies is not very wise as it makes integration of improvement blueprints very hard.
Also, I want to be able to disable stuff done today, in the blueprint without suppressing it.
Add steps in the middle... (like handling Ids differently).

Also maybe I was wrong, I tough each blueprint rewrites the final file to disk, but I might be wring.

**Comment by pascalgrimaud** [comment]
I don't understand this:
> maintaining it is a PITA unless your code is merged in the main generator.

It's like saying:
- I don't want to do a module / blueprint and maintain it, because I don't have time / motivation
- I'd prefer to merge it in the main core generator so the core team will maintain it for me

**Comment by yelhouti** [comment]
@pascalgrimaud not really, once my code is working and it doesn't need changes I shouldn't have to re merge it with master at each release. if it was in the main generator, no one would need to touch it.
If blueprints where composable that wouldn't be a problem too.

**Comment by mshima** [comment]
@yelhouti changing jhipster to a more modular generation (splitting into micro generators) was discussed before.
There is a recent discussion on jhipster-dev mail list, you can look at the archive.
For this to happen, probably jhipster should move away from yeoman to another generator platform, which means reimplementing everything and every blueprint too.

You should try to implement using regex patching to make easier to forward porting.
You can try implement you blueprint on top of generator-jhipster-customizer.

Closing this for now.

**Comment by yelhouti** [comment]
@mshima couldn't find it in the mailing list can you point me to the right one please? thanks

**Comment by mshima** [comment]
@yelhouti https://groups.google.com/forum/#!topic/jhipster-dev/7ghhQxp_Tvg

**Comment by yelhouti** [comment]
@mshima thank you :)
And big thank you to @Tcharl for suggesting something this radical, I'm not that crazy after all :). I also think that arguments from both sides are valid, and the discussion wasn't finished since you had to switch back to talking about 6.9. Maybe this is a better place to continue that discussion since blueprint authors and the community in general is not all subscribed to the dev mailing list.
What do you guys think?
