### ISSUE TITLE
Add Ionic AngularJS Mobile

### ISSUE THREAD

**Issue by verrol** [jhipster/generator-jhipster#1182]
Hi guys,

I just found JHipster and trying to learn it. 

One thought I had as I started playing with it.

Since JHipster uses AngularJS for the front-end. Would it be possibly to tie in Ionic Framework for "mobile front-end"? That way, as a developer, I get both web-desktop and mobile HTML5 front-end at the same time, talking to the same back-end. It seems like adding ionic would fit very well with JHipster.

Thanks.

.v

**Comment by jdubois** [comment]
I don't know what Ionic is, but looks like it's a set of components created by a company on top of AngularJS?
I want to stick to standard, normal AngularJS. This is what we have always done, and it's the goal from the start.
If you want to use something on top of AngularJS, you can of course do it, and we will help you (for example, with Bower) to achieve this, but we will not migrate to something "more complete" than Angular, as this would restrict what our users can do.

**Comment by gmarziou** [comment]
Agree with @jdubois, Ionic is not built on Bootstrap so our current views could not be re-used, it uses Apache Cordova which means a complete different build so it would mean probably creating a distinct module. Add to this that navigation for a mobile app has to be completely different than for a desktop web app and you'll end up by re-using only the entities services and maybe the authentication.

That said, it would be interesting to try building a prototype that would use jhipster backend from a client generated by [generator-ionic](https://github.com/diegonetto/generator-ionic)
