### ISSUE TITLE
vanillaRestTemplate bean  code isn't added to the config file

### ISSUE THREAD

**Issue by mesuttekin** [jhipster/generator-jhipster#11826]
* **Overview of the issue**
When I create a gateway with importing jdl, the generator doesn't add vanillaRestTemplate bean code in the file(SecurityConfiguration.java). 

  When I run ./gradlew, it throws blow error. 

  APPLICATION FAILED TO START
  Description:
Parameter 0 of constructor in com.mycompany.myapp.web.filter.RouteDetectorFilter required a bean of type 'org.springframework.web.client.RestTemplate' that could not be found.
The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Qualifier(value=vanillaRestTemplate)
Action:
Consider defining a bean of type 'org.springframework.web.client.RestTemplate' in your configuration.

* **Motivation for or Use Case** 
  While generating code for gateway with importing jdl.

  it is a bug because spring boot doesn't start and throws above expectations.

* **JHipster Version(s)** 
6.8.0

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "baseName": "gateway",
    "buildTool": "gradle",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["cucumber"],
    "websocket": false,
    "applicationType": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "useSass": true,
    "jhipsterVersion": "6.8.0",
    "creationTimestamp": 1589966220246,
    "skipServer": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": []
}

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
No entity

* **Browsers and Operating System** 
Mac

* **Reproduce the error** 
  Save below configuration to a file (bug1.jdl) and run below command. 

  jhipster import-jdl bug1.jdl

  application {
  config {
    baseName gateway
    applicationType gateway
    packageName com.mycompany.myapp
    serviceDiscoveryType no
    authenticationType jwt
    databaseType mongodb
    buildTool gradle
    clientFramework react
    testFrameworks [cucumber]
    enableSwaggerCodegen true
    useSass true
  }
  entities *
}

* **Related issues** 
  I couldn't find any related issue.
* **Suggest a Fix** 
  Add bean method in the SecurityConfiguration.java file 

  import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.web.client.RestTemplate;
@Bean
@Qualifier("vanillaRestTemplate")
public RestTemplate vanillaRestTemplate() {
    return new RestTemplate();
}

**Comment by vishal423** [comment]
@mesuttekin  can you try against latest version `v6.9.0`?

**Comment by ruddell** [comment]
Fixed in https://github.com/jhipster/generator-jhipster/pull/11552 (part of v6.9.0).  You can workaround it in v6.8.0 by applying the same changes from the PR in your project.
 - Add [`RestTemplateConfiguration.java`](https://github.com/jhipster/generator-jhipster/pull/11552/files#diff-089152f7e6ccf0bd1ecced2cd312696b) to your project
 - Replace references to `vanillaRestTemplate` with `restTemplate`
