### ISSUE TITLE
Missing neo4j.yml.ejs file while generating kubernetes files

### ISSUE THREAD

**Issue by sujithsj** [jhipster/generator-jhipster#11837]
##### **Overview of the issue**

I have a microservice with neo4j database while i am deploying it into prod azure trying to generate kubernetes files but giving the error like bellow
Copying template db/neo4j.yml.ejs failed no such file or director.
I went into templates/db folder but i don't find neo4j.yml.ejs file there.

##### **Motivation for or Use Case**

To support neo4j microservice production deployment 

##### **JHipster Version(s)**

Jhipster 6.9.0

##### **Browsers and Operating System**

Linux 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
This is something we still need to do. See https://github.com/jhipster/generator-jhipster/issues/11731

I will close this as a duplicate.
