### ISSUE TITLE
now() cannot be used in liquidbase with MariaDB

### ISSUE THREAD

**Issue by sbouchex** [jhipster/generator-jhipster#11840]
##### **Overview of the issue**

I'm performing the following schema change with MariaDB :
```
<addColumn tableName="incident">
            <column name="dateheure_maj" type="datetime" defaultValueDate="${now}">
                <constraints nullable="true" />
            </column>
        </addColumn>
```

MariaDB is receiving the following query : 

`ALTER TABLE lignedurgence.incident ADD dateheure_maj datetime DEFAULT ${now} NULL]
`

But the query fails because ${now} is not replaced by "now()"

##### **Suggest a Fix**

master.xml should contain :

`<property name="now" value="now()" dbms="mysql, mariadb"/>`

##### **JHipster Version(s)**

I'm using jhipster 6.8.0

**Comment by MathieuAA** [comment]
I've just noticed your PR @sbouchex, thank you for taking care of this issue!
