### ISSUE TITLE
Gateway with gradle doesn't work with Gitlab CI

### ISSUE THREAD

**Issue by CentroricercheRPS** [jhipster/generator-jhipster#11854]
##### **Overview of the issue**

Created a gateway application with gradle, works fine when compiled from the command line, but fails with Gitlab CI (jhipster ci-cd)

[Please see the stackoverflow question](https://stackoverflow.com/questions/61959951/gitlab-ci-failure-with-jhipster)

##### **Reproduce the error**

Create a 6.9 gateway application with JDL and gradle, run jhipster ci-cd and then send it to a Gitlab runner.

##### **JHipster Version(s)**

6.9

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gatewayu@0.0.1-SNAPSHOT /home/michele/gitlab/upowernetguard/gatewayu
└── generator-jhipster@6.9.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "uaa",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": false,
    "baseName": "gatewayu",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "it", "fr", "de", "es"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "gateway",
    "packageName": "com.rps.png",
    "packageFolder": "com/rps/png",
    "uaaBaseName": "uaa",
    "jhipsterVersion": "6.9.0",
    "creationTimestamp": 1590083280536,
    "skipServer": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["Device"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Device {
  address String unique required,
  protocol Protocol required,
  port Integer,
  name String,
  icon Integer,
  tags String,
  status Status,
  uptime Duration,
  lastchecked Instant
}
enum Protocol {
  SNMPV1,
  SNMPV2C,
  SNMPV3,
  JSON
}
enum Status {
  OK,
  INFO,
  MINOR,
  MAJOR,
  CRITICAL,
  COMMLOST
}

service Device with serviceClass
microservice Device with powerbacku
filter Device

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)

git version 2.20.1

node: v12.16.1

npm: 6.14.5

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.25.4, build 8d51620a

identical .jhipster/Device.json
INFO! Congratulations, JHipster execution is complete!

---
If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
deployment {
  deploymentType docker-compose
  appsFolders [uaa, powerbacku, gatewayu, realgraphu, snmpju]
  dockerRepositoryName "10.1.10.58:5000"
}

application {
  config {
    baseName uaa
    applicationType uaa,
    serviceDiscoveryType eureka,
    packageName com.rps.png,
    buildTool gradle
  }
}

application {
  config {
    baseName gatewayu
    applicationType gateway,
    packageName com.rps.png,
    authenticationType uaa,
    uaaBaseName "uaa",
//    clientTheme Solar,
//    clientThemeVariant Dark,
    nativeLanguage en,
    languages [en, it, fr, de, es]
    buildTool gradle
  }
  entities *
}

application {
  config {
    baseName powerbacku
    applicationType microservice,
    packageName com.rps.png,
    authenticationType uaa,
    uaaBaseName "uaa",
    prodDatabaseType mysql,
    devDatabaseType mysql,
//    clientTheme Solar,
    nativeLanguage en,
    languages [en, it, fr, de, es]
    buildTool gradle,
    serverPort 8081
  }
  entities *
}

application {
  config {
    baseName realgraphu
    applicationType microservice,
    packageName com.rps.png,
    authenticationType uaa,
    uaaBaseName "uaa",
    databaseType no,
//    clientTheme Solar,
    nativeLanguage en,
    languages [en, it, fr, de, es]
    buildTool gradle,
    serverPort 8081
  }
  entities *
}

application {
  config {
    baseName snmpju
    applicationType microservice,
    packageName com.rps.png,
    authenticationType uaa,
    uaaBaseName "uaa",
    databaseType no,
//    clientTheme Solar,
    nativeLanguage en,
    languages [en, it, fr, de, es]
    buildTool gradle,
    serverPort 8081
  }
  entities *
}

enum Protocol {
   SNMPV1, SNMPV2C, SNMPV3, JSON
}

enum Status {
   OK, INFO, MINOR, MAJOR, CRITICAL, COMMLOST
}

entity Device {
  address String unique required
  protocol Protocol required
  port Integer
  name String
  icon Integer
  tags String
  status Status
  uptime Duration
  lastchecked Instant
}

filter Device

microservice Device with powerbacku
  </pre>
  </details>

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Thanks for reporting this. It looks indeed like a bug on our side.

**Comment by atomfrede** [comment]
@CentroricercheRPS Are you running your builds inside docker (e.g. on gitlab.com)?

**Comment by CentroricercheRPS** [comment]
I have gitlab runner on a VM. What should I check?

**Comment by atomfrede** [comment]
Basically which executor your runner is using. See https://docs.gitlab.com/runner/executors/README.html for details.

**Comment by CentroricercheRPS** [comment]
config.toml says 

`executor = "docker"`

...so I guess it's running in docker

**Comment by atomfrede** [comment]
And you selected run in docker when generating the ci config? Can you share the whole generated ci config file?

**Comment by atomfrede** [comment]
It works in [gitlab.com](https://gitlab.com/jhipster-talks/tngbtd/pipelines/144034135) using docker (so having an `image` [config at the top](https://gitlab.com/jhipster-talks/tngbtd/-/blob/master/.gitlab-ci.yml)).

nevertheless we should add the nodeInstall here to make sure the ci builds do not rely on any environment available

**Comment by CentroricercheRPS** [comment]
Please check the JDL definitions above, I'm quoting the relevant part:
```
deployment {
  deploymentType docker-compose
  appsFolders [uaa, powerbacku, gatewayu, realgraphu, snmpju]
  dockerRepositoryName "10.1.10.58:5000"
}
```
I this everything should be set.

**Comment by CentroricercheRPS** [comment]
Also the .gitlab-ci.yml is already posted on stackoverflow

**Comment by CentroricercheRPS** [comment]
And indeed, the image: is missing! Maybe JDL generated docker-compose is different?

**Comment by atomfrede** [comment]
Docker compose and deployment option is unrelated to the ci/cd configuration (at least I think so). How did you create the ci/cd configuration?

**Comment by CentroricercheRPS** [comment]
You're right, I was mixing things.

After importing the JDL, I ran `jhipster ci-cd` and selected gitlab

**Comment by CentroricercheRPS** [comment]
I left the default option:

```
In GitLab CI, perform the build in a docker container (hint: GitLab.com uses Docker container) ? No
```

However, please note that microservices and UAA works with Gitlab CI with the above setting.
Also on maven (on 6.8) the gateway works with Gitlab CI with the above setting.

**Comment by atomfrede** [comment]
Yes as I said most likely a bug on our side. UAA and microservices have no ui, so everything is fine for that.

**Comment by pascalgrimaud** [comment]
looks like there is no bug here, as we found the problem
that's why I'm closing this

**Comment by atomfrede** [comment]
I will add the `-PnodeInstall` to the package phase, such that we are consistent with other tasks.
