### ISSUE TITLE
jhipster OAuth2 Authentication

### ISSUE THREAD

**Issue by moonflower123** [jhipster/generator-jhipster#1186]
Im creating a new jhipster application with mysql database , the database is created with the tables but while loading http://localhost:8080/login.jsp it gives Your request cannot be processed in the browser.
this is the logs

[DEBUG] com.ita.om.config.DatabaseConfiguration - Configuring Datasource
[DEBUG] com.ita.om.config.DatabaseConfiguration - Configuring Liquibase
[DEBUG] com.ita.om.config.MailConfiguration - Configuring mail server
[INFO] com.ita.om.config.WebConfigurer - Web application configuration, using profiles: [dev]
[DEBUG] com.ita.om.config.WebConfigurer - Initializing Metrics registries
[DEBUG] com.ita.om.config.WebConfigurer - Registering Metrics Filter
[DEBUG] com.ita.om.config.WebConfigurer - Registering Metrics Servlet
[INFO] com.ita.om.config.WebConfigurer - Web application fully configured
[INFO] com.ita.om.Application - Running with Spring profile(s) : [dev]
[INFO] com.ita.om.config.ThymeleafConfiguration - loading non-reloadable mail messages resources
[DEBUG] com.ita.om.config.apidoc.SwaggerConfiguration - Starting Swagger
[DEBUG] com.ita.om.config.apidoc.SwaggerConfiguration - Started Swagger in 29 ms
[DEBUG] com.ita.om.config.CacheConfiguration - No cache
[DEBUG] com.ita.om.aop.logging.LoggingAspect - Enter: com.ita.om.repository.CustomAuditEventRepository.auditEventRepository() with argument[s] = []
[DEBUG] com.ita.om.aop.logging.LoggingAspect - Exit: com.ita.om.repository.CustomAuditEventRepository.auditEventRepository() with result = com.ita.om.repository.Cust
omAuditEventRepository$1@77896335
[INFO] com.ita.om.Application - Started Application in 30.541 seconds (JVM running for 31.214)
[DEBUG] com.ita.om.aop.logging.LoggingAspect - Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Thu
 Feb 26 13:34:27 GST 2015, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access
is denied}]]
Hibernate: insert into T_PERSISTENT_AUDIT_EVENT (event_date, event_type, principal) values (?, ?, ?)
[DEBUG] com.ita.om.aop.logging.LoggingAspect - Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
Hibernate: insert into T_PERSISTENT_AUDIT_EVENT_DATA (event_id, name, value) values (?, ?, ?)
Hibernate: insert into T_PERSISTENT_AUDIT_EVENT_DATA (event_id, name, value) values (?, ?, ?)

**Comment by Kahfimaulana** [comment]
do you have accessed the correct url ? http://localhost:8080/ without /login.jsp ?

**Comment by jdubois** [comment]
Yes we don't have JSPs in JHipster, so this is a "normal" response!
