### ISSUE TITLE
import-jdl fails for uaa build

### ISSUE THREAD

**Issue by kodisj** [jhipster/generator-jhipster#11868]
##### **Overview of the issue**

importing jdl fails for uaa.  Here is the jdl
application {
  config {
    baseName uaa
    applicationType uaa
    packageName com.latchiya
    serviceDiscoveryType no
    authenticationType jwt
    databaseType no
    devDatabaseType no
    prodDatabaseType no
    cacheProvider hazelcast
    buildTool maven
    useSass true
    serverPort 9999
    languages [en]
  }
  entities *
}

Here is the error:

   create src\main\resources\config\application.yml
   create src\main\resources\config\application-dev.yml
   create src\main\resources\config\application-tls.yml
SyntaxError: Map keys must be unique; "authentication" is repeated (96:9)
   94 |                 url:
   95 |     security:
>  96 |         authentication:
      |         ^^^^^^^^^^^^^^^
>  97 |             jwt:
      | ^^^^^^^^^^^^^^^^
>  98 |                 # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      | ^^^^^^^^^^^^^^^^
>  99 |                 # As this is the PRODUCTION configuration, you MUST change the default key, and store it securely:
      | ^^^^^^^^^^^^^^^^
> 100 |                 # - In the JHipster Registry (which includes a Spring Cloud Config server)
      | ^^^^^^^^^^^^^^^^
> 101 |                 # - In a separate `application-prod.yml` file, in the same folder as your executable JAR file
      | ^^^^^^^^^^^^^^^^
> 102 |                 # - In the `JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET` environment variable
      | ^^^^^^^^^^^^^^^^
> 103 |                 base64-secret: M2Y1YTBhMjE0OTFiNTc2OWUwZDhjN2NmYjNhMzBlNzk3M2QwZmUzMWZiMjc0ZjY0YjQ5ZThlODBkN2E0ZDkxOGY2YWI4YjQzNjdkYTJlNTM0Yzk2YjAwYTYwY2E1NDdkMzIxNDNlMTBkOGZlMmNiNmI0MjU0MWVmNzY2MWNhYmM=
      | ^^^^^^^^^^^^^^^^
> 104 |                 # Token is valid 24 hours
      | ^^^^^^^^^^^^^^^^
> 105 |                 token-validity-in-seconds: 86400
      | ^^^^^^^^^^^^^^^^
> 106 |                 token-validity-in-seconds-for-remember-me: 2592000
      | ^^^^^^^^^^^^^^^^
> 107 |         authentication:
      | ^^^^^^^^^^^^^^^^
> 108 |             jwt:
      | ^^^^^^^^^^^^^^^^
> 109 |                 # Access Token is valid for 5 mins
      | ^^^^^^^^^^^^^^^^
> 110 |                 token-validity-in-seconds: 300
      | ^^^^^^^^^^^^^^^^
> 111 |                 # Refresh Token is valid for 7 days
      | ^^^^^^^^^^^^^^^^
> 112 |                 token-validity-in-seconds-for-remember-me: 252000
      | ^^^^^^^^^^^^^^^^
> 113 |     mail: # specific JHipster mail property, for standard properties see MailProperties
      | ^
  114 |         base-url: http://my-server-url-to-change # Modify according to your server's URL
  115 |     metrics:
  116 |         logs: # Reports metrics in the logs
    at t (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\parser-yaml.js:1:281)
    at Object.parse (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\parser-yaml.js:16:152603)
    at Object.parse (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:11370:19)
    at coreFormat (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:14784:25)
    at format (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:15019:75)
    at formatWithCursor (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:15035:12)
    at C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:51620:12
    at Object.format (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:51640:12)
    at C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-transforms.js:44:39
INFO! App: child process exited with code 1
ERROR! JHipster finished with code 1

##### **Motivation for or Use Case**

importing jdl shoud work for uaa

##### **Reproduce the error**

jhipster import-jdl xxx.jdl  (put the above jdl)

##### **JHipster Version(s)**

6.9.0, I am not doing regression

##### **JHipster configuration**
   create src\main\resources\config\application-dev.yml
   create src\main\resources\config\application-tls.yml
SyntaxError: Map keys must be unique; "authentication" is repeated (96:9)
   94 |                 url:
   95 |     security:
>  96 |         authentication:
      |         ^^^^^^^^^^^^^^^
>  97 |             jwt:
      | ^^^^^^^^^^^^^^^^
>  98 |                 # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      | ^^^^^^^^^^^^^^^^
>  99 |                 # As this is the PRODUCTION configuration, you MUST change the default key, and store it securely:
      | ^^^^^^^^^^^^^^^^
> 100 |                 # - In the JHipster Registry (which includes a Spring Cloud Config server)
      | ^^^^^^^^^^^^^^^^
> 101 |                 # - In a separate `application-prod.yml` file, in the same folder as your executable JAR file
      | ^^^^^^^^^^^^^^^^
> 102 |                 # - In the `JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET` environment variable
      | ^^^^^^^^^^^^^^^^
> 103 |                 base64-secret: M2Y1YTBhMjE0OTFiNTc2OWUwZDhjN2NmYjNhMzBlNzk3M2QwZmUzMWZiMjc0ZjY0YjQ5ZThlODBkN2E0ZDkxOGY2YWI4YjQzNjdkYTJlNTM0Yzk2YjAwYTYwY2E1NDdkMzIxNDNlMTBkOGZlMmNiNmI0MjU0MWVmNzY2MWNhYmM=
      | ^^^^^^^^^^^^^^^^
> 104 |                 # Token is valid 24 hours
      | ^^^^^^^^^^^^^^^^
> 105 |                 token-validity-in-seconds: 86400
      | ^^^^^^^^^^^^^^^^
> 106 |                 token-validity-in-seconds-for-remember-me: 2592000
      | ^^^^^^^^^^^^^^^^
> 107 |         authentication:
      | ^^^^^^^^^^^^^^^^
> 108 |             jwt:
      | ^^^^^^^^^^^^^^^^
> 109 |                 # Access Token is valid for 5 mins
      | ^^^^^^^^^^^^^^^^
> 110 |                 token-validity-in-seconds: 300
      | ^^^^^^^^^^^^^^^^
> 111 |                 # Refresh Token is valid for 7 days
      | ^^^^^^^^^^^^^^^^
> 112 |                 token-validity-in-seconds-for-remember-me: 252000
      | ^^^^^^^^^^^^^^^^
> 113 |     mail: # specific JHipster mail property, for standard properties see MailProperties
      | ^
  114 |         base-url: http://my-server-url-to-change # Modify according to your server's URL
  115 |     metrics:
  116 |         logs: # Reports metrics in the logs
    at t (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\parser-yaml.js:1:281)
    at Object.parse (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\parser-yaml.js:16:152603)
    at Object.parse (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:11370:19)
    at coreFormat (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:14784:25)
    at format (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:15019:75)
    at formatWithCursor (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:15035:12)
    at C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:51620:12
    at Object.format (C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\prettier\index.js:51640:12)
    at C:\Users\kodisj\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-transforms.js:44:39
INFO! App: child process exited with code 1
ERROR! JHipster finished with code 1

##### **Browsers and Operating System**
WIndows 10 home edition

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
This occurs if `authenticationType` is `jwt` and if the `applicationType` is `uaa` (see the `application-prod.yml.ejs` file)

**Comment by MathieuAA** [comment]
`authenticationType` must be `uaa` too. You can omit the application configuration option though, JHipster will set it for you.

**Comment by MathieuAA** [comment]
I'm gonna make the authenticationType always be `uaa` when the appType is `uaa` when parsing a JDL file.
