### ISSUE TITLE
Duration type field is printed as PT10H10M10.1S

### ISSUE THREAD

**Issue by CentroricercheRPS** [jhipster/generator-jhipster#11862]
##### **Overview of the feature request**

When I add a Duration type field to a Entity, the Angular front end print the field as PT10H10M10.1S. It is correct but a bit raw. It should be printed in a user friendly way by default, while still offering options for customization.
For example "about 10 hours" (minutes, seconds and milliseconds are less relevant)
Possibly internationalized.

##### **Motivation for or Use Case**

User friendlyness

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Is angular doing any formatting or just printing the raw value from the server response? As we have use moment.js you could try to use `moment.duration('P1Y2M3DT4H5M6S')`. See https://momentjs.com/docs/#/durations/

**Comment by DanielFran** [comment]
@jhipster/developers Maybe we should think about creating some methods to help on dates and duration format?
The already have also this issue https://github.com/jhipster/generator-jhipster/issues/11525 for dates.

**Comment by pascalgrimaud** [comment]
Not only related to Angular, as I saw this with Vue.js too.
Need to check for React.

So +1 here

**Comment by MathieuAA** [comment]
Same for react last I've checked

**Comment by pascalgrimaud** [comment]
important to have, so I'm adding a bounty

**Comment by atomfrede** [comment]
I can work on this.
