### ISSUE TITLE
Bootstrap servers key format for Kafka

### ISSUE THREAD

**Issue by fdelbrayelle** [jhipster/generator-jhipster#11863]
##### **Overview of the issue**

According to the [official Apache Kafka documentation](https://kafka.apache.org/documentation/#bootstrap.servers) the key for bootstrap.servers should be with a `.` and not a `-` like it's done in `application.yml` files:

```
bootstrap-servers: localhost:9092
```

##### **Motivation for or Use Case**

Fit the official key format.

##### **Suggest a Fix**

Replace `bootstrap-servers` by `bootstrap.servers` in both `application.yml` (src/java/main and src/test/main) and remove this block of code in `KafkaProperties.java.ejs`:

```
        if (!properties.containsKey("bootstrap.servers")) {
            properties.put("bootstrap.servers", this.bootStrapServers);
        }
```

Finally, replace this block in `app.yml.ejs`:

```
- KAFKA_BOOTSTRAPSERVERS=kafka:9092
```

by

```
- KAFKA_BOOTSTRAP_SERVERS=kafka:9092
```

##### **JHipster Version(s)**

6.9.0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
cc @cbornet as you coded this original part. Do you have an opinion on this plz ?

**Comment by cbornet** [comment]
I think this wouldn't work with YAML mapping. The current way mimics what is done by Spring Boot.

**Comment by ctamisier** [comment]
Yes there is no way to map 'bootstrap.servers' to a variable in the property class (AFAIK).

I would say to do like it is done here:
https://github.com/fdelbrayelle/sample-with-kafka/blob/master/src/main/resources/config/application.yml#L163
and 
https://github.com/fdelbrayelle/sample-with-kafka/blob/master/src/main/java/tech/ippon/generated/config/KafkaProperties.java#L17

The java mapping is not the nicest but it keeps the original kafka property key that need to be used. And avoid eventual confusion between 'bootstrap.servers' and 'bootstrap-servers'.

(the same way that we have 'key.deserializer, 'key.serializer', 'value.deserializer', ...)

**Comment by cbornet** [comment]
IMO it's better to keep coherence with spring-boot. And `'[key.deserializer]': org.apache.kafka.common.serialization.StringDeserializer` is really ugly...

**Comment by ctamisier** [comment]
Yes I see.

**If we want to keep coherence with Spring Boot:**
We will have to define property keys like bootstrapServers, keyDeserializer, valueDeserializer, etc... in the yml configuration file.

Having this, means we need somehow to have a mapping to "transform":
bootstrapServers to bootstrap.servers, 
keyDeserializer to key.deserializer and 
valueDeserializer to value.deserializer, etc...

(similar than this : https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java)

But every new version of kafka-clients that add a new key, this key will have to be defined in this mapping as well (and remove the eventual deprecated ones).

**If we want to keep kafka property style:**
No mapping is needed, we can just define a property (ex: ['fetch.max.bytes']=???) in application.yml.

(By the way I don't see "fetch.max.bytes" in KafkaProperties class of Spring Boot... :( )

**Comment by cbornet** [comment]
Spring Boot has a [properties](https://github.com/spring-projects/spring-boot/blob/1defd673476e2c4a143cb5db7f295bc4d8a23670/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java#L75) field for additional properties which are not mapped to a known field.

**Comment by fdelbrayelle** [comment]
The `'[my.property]` is quite ugly but mandatory if you want to keep the whole `my.property` into a single field when mapping consumers and producers configuration into maps. If not using `'[...]` the property will be split in a object. That's why we chose this notation with @ctamisier for the module.

Maybe there is a good alternative?

**Comment by pascalgrimaud** [comment]
So how can we advance on this ticket ? @cbornet @fdelbrayelle @ctamisier : what do you suggest ?
- stay like this ?
- apply a change ?
As it will impact the generator-jhipster-kafka module, it's important to be consistent between the main generator-jhipster and the module for our end-users

**Comment by fdelbrayelle** [comment]
As the [Kafka module](https://github.com/fdelbrayelle/generator-jhipster-kafka/) can be use alongside the main generator I would say we can stay like this and close.

**Comment by pascalgrimaud** [comment]
Ok then, don't hesitate to comment and discuss further if needed
Thanks @fdelbrayelle
