### ISSUE TITLE
Application on firefox issue

### ISSUE THREAD

**Issue by smurugan86** [jhipster/generator-jhipster#11864]
##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@smurugan86 : We would need more information about the issue you are experiencing. Could you please provide more information by filling out the issue template?

**Comment by atomfrede** [comment]
I guess it is related to https://github.com/jhipster/generator-jhipster/issues/11566 so most likely we can close this if no more information are provided.

**Comment by SudharakaP** [comment]
> I guess it is related to #11566 so most likely we can close this if no more information are provided.

I think so too. :smile: 

@smurugan86 : Feel free to reopen if this is not related to #11566 and if you have additional information.
