### ISSUE TITLE
Replace datetime-local input in generated pages

### ISSUE THREAD

**Issue by sbouchex** [jhipster/generator-jhipster#11861]
When an entity field is typed "Instant", the generated html for this field is an **datetime-local** input but this input is deprecated and no supported by Firefox (and Safari)
see https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/datetime-local

Solution : Add a thirtparty date & time selector (Materiel ? other ?)

**Comment by SudharakaP** [comment]
Thanks for raising the issue. This has been already discussed at https://github.com/jhipster/generator-jhipster/issues/11124. It was decided to let the user choose the date picker. As far as I remember the last time I checked I couldn't find a decent picker that respects the bootstrap theme. If you have any suggestions feel free to reopen the issue and raise a PR. :smile:
