### ISSUE TITLE
Is jhipster able to create Dapp

### ISSUE THREAD

**Issue by Aghorb** [jhipster/generator-jhipster#11878]
I am developing a Dapp based on the quorum blockchain (forked from ethereum) and I wonder if jhipster allows the creation of Dapps based on a smart contract (solidity language) as a backend.

**Comment by pascalgrimaud** [comment]
It depends on what you want to do.
You can use JHipster to generate only the front (Angular, React or Vue.js) and code your backend yourself.
You can provide a blueprint https://www.jhipster.tech/modules/creating-a-blueprint/ if you want to share your code.

The generated code from JHipster is yours. You can do what you want with that.

I'm closing this, as there is no issue here.
