### ISSUE TITLE
Cli changes for jhipster 7

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#11896]
##### **Overview of the feature request**

I propose the following changes to cli for jhipster7
- [x] ~~Remove import-jdl command~~ import-jdl: do not force `--skip-sample-repository`
  `import-jdl` is now an alias for jdl command forcing `--skip-sample-repository`.
  We should promote `jdl --skip-sample-repository`. https://github.com/jhipster/generator-jhipster/pull/11770#discussion_r434523752, https://github.com/jhipster/generator-jhipster/pull/11770#issuecomment-634892631, https://github.com/jhipster/generator-jhipster/pull/11770#issuecomment-634880598
- [x] Remove kebab case options.
  Having to deal with `this.options['skip-install']` and `this.options.skipInstall` should be removed.
- [ ] Disable allowUnknownOption
  Makes easier to deal with cli options. https://github.com/jhipster/generator-jhipster/pull/11770#discussion_r430536146
  We must make sure every options is registered and load options from blueprints before disabling allowUnknownOption.
  

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Lets not remove the alias for 7, it doesn't cost anything to have the alias. We can consider removing it for v8

**Comment by mraible** [comment]
@mshima It seems you re-opened this issue yesterday. Is there something else you need to fix?

**Comment by mshima** [comment]
@mraible the I reverted the PR for jhipster code due to a bug and to it don’t interfere at the work there.
The issue is https://github.com/tj/commander.js/issues/1343.
I have a branch ready based on commander 7, so I am waiting it to be released.

**Comment by mshima** [comment]
@pascalgrimaud commander 7 is planned for January, so we have 2 options for jhipster 7:
- bundle a commander 7 snapshot with jhipster (just 1 file).
- postpone `allowUnknownOption` to jhipster 8.

**Comment by pascalgrimaud** [comment]
Honestly, I don't know. Maybe we can give a try to snapshot.
What's your advice on this ?

Le lun. 12 oct. 2020 à 22:57, Marcelo Shima <notifications@github.com> a
écrit :

**Comment by mshima** [comment]
> Honestly, I don't know. Maybe we can give a try to snapshot.

I think we should do it.

**Comment by pascalgrimaud** [comment]
I'm trusting you, so let's follow your advice

**Comment by mraible** [comment]
Added bug bounty for your help @mshima.

**Comment by pascalgrimaud** [comment]
I think the last item is done.
Can you confirm it @mshima plz ?

**Comment by mshima** [comment]
@pascalgrimaud I have a cli refactoring PR to make tests easier.
It's quite complex to implement tests right now.
