### ISSUE TITLE
Cannot find module './../../page-objects/jhi-page-objects'

### ISSUE THREAD

**Issue by lucasangelo1989** [jhipster/generator-jhipster#11893]
##### **Overview of the issue**

 
I'm having a problem when I'm going to create a new entity through the command line "jhipster entity MuniEstado". After doing the step by step and the jhipster make the calls I have the message ERROR

##### **Reproduce the error**
jhipster entity MuniEstado
created a single field called value of type double. I made all possible combinations to replace the configuration files.
I have the following message at the end
ERROR in /home/dell/SINAJUVE/visao-master/src/test/javascript/e2e/entities/muni-estado/muni-estado.spec.ts
(2,28): Cannot find module './../../page-objects/jhi-page-objects'.

##### **JHipster configuration**

My configurations 
INFO! Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
visao@0.0.0 /home/dell/SINAJUVE/visao-master
└── generator-jhipster@5.1.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "br.com.ibict.visao",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "monolith",
    "baseName": "visao",
    "packageName": "br.com.ibict.visao",
    "packageFolder": "br/com/ibict/visao",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity MuniEstado (muni_estado) {
  value Double
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.7.4

node: v10.20.1

npm: 6.14.5

yarn: 1.22.4

##### **Browsers and Operating System**

 ubuntu operating system
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Your JHipster version is old: 5.1.0
Can you try with the last version of JHipster 6.9.1 plz ?

**Comment by pascalgrimaud** [comment]
don't hesitate to comment if you manage to reproduce the issue in the last version of jhipster
for now, I'm closing this ticket

**Comment by lucasangelo1989** [comment]
Your tip is very good, I upgraded to version 6 and the application worked, thank you very much.
