### ISSUE TITLE
@BeforeEach methods not executed in IT tests with Gradle

### ISSUE THREAD

**Issue by stancalau** [jhipster/generator-jhipster#11906]
##### **Overview of the issue**

`@BeforeEach` methods are not executed in intergration tests.

##### **Motivation for or Use Case**

Db cleanup code is not run before tests, possibly leaving junk, setup logic is not performed.

##### **Reproduce the error**

Tried Idea debug run for integration tests, the breakpoint within `@BeforeEach` is never reached.
Tried console > gradle clean build, my custom tests fail because setup logic is not performed
Tried to update version of archunit_junit5_version to 0.14.1 . Same result.

##### **JHipster Version(s)**

```
proj@0.0.1-SNAPSHOT H:\PersonalProjects\proj\proj
`-- generator-jhipster@6.8.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.proj",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "proj",
    "packageName": "com.proj",
    "packageFolder": "com/proj",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "flatly",
    "clientThemeVariant": "light",
    "creationTimestamp": 1588669169240,
    "testFrameworks": ["cucumber"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "ro"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Tenant {
  alias String required unique minlength(3) maxlength(25),
  issuer String required,
  confirmationDate Instant,
  creationDate Instant required,
  databaseName String required,
  clientId String required minlength(1),
  clientSecret String required minlength(1)
}
entity TenantRegistrationRequest {
  email String required,
  tenantName String required minlength(3),
  requestDate Instant required,
  confirmationEmailSentDate Instant,
  requestValidated Boolean required
}
entity UserInvitation {
  email String required minlength(5) maxlength(254),
  invitationSentDate Instant,
  invitationAccepted Boolean,
  acceptDate Instant,
  revoked Boolean,
  tenantName String required minlength(3) maxlength(25),
  expired Boolean
}
dto Tenant, TenantRegistrationRequest, UserInvitation with mapstruct
paginate Tenant, TenantRegistrationRequest with pagination
paginate UserInvitation with infinite-scroll
service Tenant, UserInvitation with serviceImpl
service TenantRegistrationRequest with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)

git version 2.25.1.windows.1

node: v12.16.2

npm: 6.14.4

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6

INFO! Congratulations, JHipster execution is complete!

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Thanks @stancalau for reporting this and the perfectly filled issue template :+1:
I will try to reproduce it. You mention your custom tests are failing, can you say if our generated test fail too? As I am pretty sure we have a `beforeEach` in certain tests.

**Comment by stancalau** [comment]
@atomfrede The generated tests do not fail. I assume the entries left in the db (mongo in my case) do not collide in tests.

**Comment by atomfrede** [comment]
Thanks, will have a look. We have `@BeforeEach` for non sql databases in our generated tests to delete data from mongo db (see https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs#L272).

**Comment by stancalau** [comment]
I think we can close the issue. I found some broken code executing before the test setup in spring boot. That's why the breakpoint was never reached.

Tested the UserResourceIT and it stops in `@BeforeEach` on breakpoint.

Sorry about that :(

**Comment by atomfrede** [comment]
No problem, great it works!
