### ISSUE TITLE
Gateway with gradle doesn't work with Gitlab CI

### ISSUE THREAD

**Issue by CentroricercheRPS** [jhipster/generator-jhipster#11918]
Please see

https://github.com/jhipster/generator-jhipster/issues/11854

recently closed with 6.9.1

##### **Overview of the issue**

On 6.9.1, the issue is not completely solved. The "package" phase now succeeds, but then the "docker-push" phase fails with an error that looks suspiciously similar to the previous one.

```
./gradlew bootJar -Pprod -x check --no-daemon
 To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.4.1/userguide/gradle_daemon.html.
 Daemon will be stopped at the end of the build stopping after processing
 > Task :bootBuildInfo
 > Task :nodeSetup SKIPPED
 > Task :npmSetup SKIPPED
 > Task :npmInstall UP-TO-DATE
 > Task :webpack FAILED
 FAILURE: Build failed with an exception.
 * What went wrong:
 Execution failed for task ':webpack'.
 > A problem occurred starting process 'command 'npm''
```

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Can you do a PR as we can't test your configuration that well. All works fine on gitlab.com for example

**Comment by CentroricercheRPS** [comment]
Solved! I added -PnodeInstall to the gradle command. The command now is:

`
/gradlew jib -Pprod -PnodeInstall -Djib.allowInsecureRegistries=true -Djib.to.tags=latest -Djib.to.image=$IMAGE_TAG -Djib.to.auth.username="gitlab-ci-token"  -Djib.to.auth.password=$CI_BUILD_TOKEN
`

Please update the script

**Comment by CentroricercheRPS** [comment]
Added the PR https://github.com/atomfrede/generator-jhipster/pull/2

**Comment by pascalgrimaud** [comment]
@CentroricercheRPS : you should do a PR in generator-jhipster project, not in @atomfrede's fork :)

**Comment by atomfrede** [comment]
Oh I didn't even notice.

**Comment by CentroricercheRPS** [comment]
Done!

https://github.com/jhipster/generator-jhipster/pull/11974

**Comment by atomfrede** [comment]
Closed with https://github.com/jhipster/generator-jhipster/pull/11974
