### ISSUE TITLE
Improve React management in generators

### ISSUE THREAD

**Issue by alombardo83** [jhipster/generator-jhipster#11936]
##### **Overview of the feature request**

React is not integrated as well as Angular in generators. I'd like to improve its integration.

##### **Motivation for or Use Case**

I prefer React rather than Angular but tierce generators can't provide a "React-friendly" client side because of a leak in JHipster generator core.

##### **Related issues or PR**

-   [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Can you please provide more information about specifically what you'd like to see improved? It's hard to add a bug bounty to an issue like this when there are no specifics.

_An interesting A/B test would be to make React the default for 6 months. It might break existing tutorials and videos, but we'd get a clear sense of whether people choose the default (Angular) or specifically choose it._

**Comment by alombardo83** [comment]
@mraible hi Matt, thanks to consider my issue. My main goal is to complete the implementation of BaseGenerator and ClientReact classes where there are "TODO" entries.
I think it's not a too big issue and could be a good beginning for me to contribute JHipster.
If you prefer keep this kind of issues in the core dev team, I understand and I let you work quietly ;)

**Comment by mraible** [comment]
Sounds good! Please proceed.

**Comment by pascalgrimaud** [comment]
Thanks for proposing your help to improve React part. It's really important for us.

What I can suggest:
- if the change is minor, just do a new pull request directly to generator-jhipster
- if the change is not minor, or you need advice, point of view etc, open a new ticket first to discuss about the enhancement. Once we agree, you can start the work

For now, I'm closing this ticket as it's too generic and it doesn't provide any details on our React can be improved.
But don't hesitate to follow my advices above, and open new ticket if you need to discuss
