### ISSUE TITLE
Rename the default branch from `master` to `main`

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#11935]
Hey let's rename the `master` branch in JHipster repos and beat GitHub to it

@jhipster/developers 

Context: https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/#:~:text=GitHub%20is%20working%20on%20replacing,its%20CEO%20said%20on%20Friday.

**Comment by pascalgrimaud** [comment]
@deepu105 : I didn't follow closely the debate on social network, but is there a final official decision about this ?
For me, there is nothing urgent here. If "main" is not the new official name, we must rename to another one again

**Comment by deepu105** [comment]
ok then let's wait to see what GitHub comes up with

**Comment by jdubois** [comment]
Yes, let's use the new default, that's perfect!
I hope it won't be too much work on the currently opened pull requests.

**Comment by atomfrede** [comment]
Mark from the Spring Data Team has already build a script which renames the primary branch to main for all repositories under one org. https://twitter.com/mp911de/status/1271785736547729408 https://github.com/mp911de/rename-to-main 

I think I have read somewhere when doing it via gh api existing PRs are updated automatically, but I can't find the reference anymore.

**Comment by jdubois** [comment]
Could we test this on the hipster-labs org first? Or on one of our own personal repos? If the PRs are updated automatically, then there's no need to think a lot about this, let's just do it.

**Comment by atomfrede** [comment]
Dave Syer got covered the retargeting of open PRs: https://github.com/dsyer/main-branch-switch

**Comment by sendilkumarn** [comment]
You can test this on jhipster-kotlin 👍

**Comment by jdubois** [comment]
Reading https://twitter.com/lukaseder/status/1273187350911291393 I believe we will have the same issue. I know I'm doing this quite often, and I'm probably not the only one.
So at the very least we should check if we have some "master" references in our own documentation.

**Comment by atomfrede** [comment]
At least `CONTRIBUTING.md` must be changed (although it is not a link to the master branch)

**Comment by deepu105** [comment]
IMO its worth all the trouble if it helps to improve diversity and helps to
fight systematic racism

**Comment by atomfrede** [comment]
Definitely. We should do it. And if we miss some parts first it's easy to change it afterwards.

**Comment by SudharakaP** [comment]
Just for reference, I believe by end of this year GitHub will support this natively and probably it's easier to wait until then; 

https://github.com/github/renaming/ 

And currently they have done parts of it; https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/

**Comment by mraible** [comment]
I'm ready to do this now. It's soooooo easy. PRs will suffer, but maybe that's the motivation for us to merge stuff?!

https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by vishal423** [comment]
I think we should wait for https://github.com/github/renaming/ to have a good developer experience

**Comment by pascalgrimaud** [comment]
We should wait for patch release v6.10.4 before doing this too
Then, we can start with small repositories before doing the main repository

**Comment by SudharakaP** [comment]
I'll do this in jhipster-online after v6.10.4 is released (and end of year) and maybe we can use that as a test run to see if everything works correctly. 😄 

Refer:  https://github.com/jhipster/jhipster-online/issues/246

**Comment by pascalgrimaud** [comment]
Done for jhipster-devbox:
- https://github.com/jhipster/jhipster-devbox/issues/123
- create branch main from master
- protect main
- edit existing pull requests

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/react-jhipster
- create branch main from master
- protect main
- edit existing pull requests

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/ng-jhipster
- create branch main from master
- protect main
- edit existing pull requests

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster-registry
- create branch main from master
- protect main
- edit existing pull requests

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster-control-center
- create branch main from master
- protect main
- edit existing pull requests

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/generator-jhipster-module
- create branch main from master
- protect main
- edit existing pull requests
- some updates : https://github.com/jhipster/generator-jhipster-module/pull/138

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/generator-jhipster-blueprint
- create branch main from master
- protect main
- edit existing pull requests
- some updates: https://github.com/jhipster/generator-jhipster-blueprint/pull/156

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster-registry-sample-config
- create branch main from master
- protect main
- edit existing pull requests

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/consul-config-loader
- create branch main from master
- protect main
- edit existing pull requests
- some updates: https://github.com/jhipster/consul-config-loader/pull/28

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster-artwork
- create branch main from master
- protect main
- edit existing pull requests
- some updates: https://github.com/jhipster/jhipster-artwork/pull/10

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster-fisher-plugin
- create branch main from master
- protect main
- edit existing pull requests

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster-oh-my-zsh-plugin
- create branch main from master
- protect main
- edit existing pull requests

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jdl-samples
- create branch main from master
- protect main
- edit existing pull requests

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster-base
- create branch main from master
- protect main
- edit existing pull requests
- some updates: https://github.com/jhipster/jhipster-base/pull/18

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster-guides
- create branch main from master
- protect main
- edit existing pull requests
- some updates: https://github.com/jhipster/jhipster-guides/pull/31

**Comment by deepu105** [comment]
I thought we were gonna wait for GitHub to support this

**Comment by pascalgrimaud** [comment]
I had some time this afternoon, looking the Roland Garros final :tennis: :-)

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/eslint-config-jhipster
- create branch main from master
- protect main
- edit existing pull requests
- some updates: https://github.com/jhipster/eslint-config-jhipster/pull/7

**Comment by mraible** [comment]
Does the rename for JDL-samples require code changes since the `JDL` command reads from it?

**Comment by pascalgrimaud** [comment]
yes probably @mraible but I didn't delete master branch so it should still work for now
I didn't start the work yet for generator-jhipster, it will be the 'final boss'

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster-automated-samples
- create branch main from master
- protect main

Done for all the samples too:
https://github.com/jhipster/jhipster-sample-app
https://github.com/jhipster/jhipster-sample-app-react
https://github.com/jhipster/jhipster-sample-app-gradle
https://github.com/jhipster/jhipster-sample-app-mongodb
https://github.com/jhipster/jhipster-sample-app-couchbase
https://github.com/jhipster/jhipster-sample-app-cassandra
https://github.com/jhipster/jhipster-sample-app-dto
https://github.com/jhipster/jhipster-sample-app-elasticsearch
https://github.com/jhipster/jhipster-sample-app-hazelcast
https://github.com/jhipster/jhipster-sample-app-nocache
https://github.com/jhipster/jhipster-sample-app-noi18n
https://github.com/jhipster/jhipster-sample-app-websocket
https://github.com/jhipster/jhipster-sample-app-oauth2
https://github.com/jhipster/jhipster-sample-app-gateway
https://github.com/jhipster/jhipster-sample-app-microservice

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster.github.io
- create branch main from master
- protect main
- edit existing pull requests
- some updates: https://github.com/jhipster/jhipster.github.io/pull/1021

**Comment by pascalgrimaud** [comment]
Done for https://github.com/jhipster/jhipster (cc @DanielFran)
- create branch main from master
- protect main
- edit existing pull requests
- some updates: https://github.com/jhipster/jhipster/pull/879

**Comment by pascalgrimaud** [comment]
In progress for https://github.com/jhipster/generator-jhipster
- [x] create branch main from master
- [x] protect main
- [ ] edit existing pull requests
- [ ] som updates: https://github.com/jhipster/generator-jhipster/pull/12718
- [ ] change main as default branch

**Comment by pascalgrimaud** [comment]
These repos needs to be changed too:

## prettier-java
cc @clementdessoude 
- https://github.com/jhipster/prettier-java

## svelte
cc @vishal423 
- https://github.com/jhipster/generator-jhipster-svelte

## dotnet
cc @nicolas63 @danielpetisme 
- https://github.com/jhipster/jhipster-dotnetcore 
- https://github.com/jhipster/jhipster-net
- https://github.com/jhipster/jhipster-sample-app-dotnetcore
- https://github.com/jhipster/jhipster-net-sample-app-template

## IDE
cc @colameo 
- https://github.com/jhipster/jhipster-ide

## JHipster Online
cc @SudharakaP 
- https://github.com/jhipster/jhipster-online

## Quarkus
cc @danielpetisme @avdev4j @joewhite101 
- https://github.com/jhipster/generator-jhipster-quarkus
- https://github.com/jhipster/jhipster-sample-app-quarkus

## Kotlin
cc @sendilkumarn 
- https://github.com/jhipster/jhipster-kotlin
- https://github.com/jhipster/jhipster-sample-app-kotlin

## Node.js
cc @amanganiello90 
- https://github.com/jhipster/generator-jhipster-nodejs 
- https://github.com/jhipster/jhipster-sample-app-nodejs
- https://github.com/jhipster/jhipster-sample-app-nodejs-oauth2

## Micronaut
cc @JasonTypesCodes @atomfrede
- https://github.com/jhipster/generator-jhipster-micronaut
- https://github.com/jhipster/jhipster-sample-app-micronaut

## Go
cc @deepu105 
- https://github.com/jhipster/jhipster-go
- https://github.com/jhipster/jhipster-sample-app-golang

## JDL Studio
cc @deepu105 (strange `src` branch)
- https://github.com/jhipster/jdl-studio

## JOOQ
cc @mshima
- https://github.com/jhipster/generator-jhipster-jooq

## CN
cc @PierreBesson 
- https://github.com/jhipster/cn

## Archived / Deprecated repos

These repos don't need to change, as there will be archived for v7:
- https://github.com/jhipster/jhipster-console
- https://github.com/jhipster/jhipster-core
- https://github.com/jhipster/jhipster-docker-hub

Same for old repos or deprecated repos

**Comment by jdubois** [comment]
Thank you so much for your hard work @pascalgrimaud

**Comment by avdev4j** [comment]
I take those from Quarkus.

**Comment by amanganiello90** [comment]
Yes, I done for :

- https://github.com/jhipster/jhipster-sample-app-nodejs
-  https://github.com/jhipster/jhipster-sample-app-nodejs-oauth2
-  https://github.com/jhipster/generator-jhipster-nodejs

But I haven't settings permissions for the last in order to change the default.

@deepu105 Could you help me?

**Comment by pascalgrimaud** [comment]
@amanganiello90 : I added you as admin for the repo https://github.com/jhipster/generator-jhipster-nodejs

**Comment by deepu105** [comment]
I'll update the Go repos. JDL studio doesn't need to change as it doesn't have a master branch and src contains source and gh-pages contain the build

**Comment by mraible** [comment]
I updated generator-jhipster-ionic to use main as the default branch.

https://github.com/oktadeveloper/generator-jhipster-ionic <https://github.com/oktadeveloper/generator-jhipster-ionic>

**Comment by nicolas63** [comment]
done for : 
    https://github.com/jhipster/jhipster-dotnetcore
    https://github.com/jhipster/jhipster-net
    https://github.com/jhipster/jhipster-sample-app-dotnetcore

this repository is deprecated 
    https://github.com/jhipster/jhipster-net-sample-app-template

**Comment by pascalgrimaud** [comment]
I forgot Azure Pipelines, so I just configure it to point to main branch instead of master, for these projects:
- generator-jhipster
- jhipster
It means all recent PRs don't have Azure Pipelines -> cc @mshima 

All other projects should use GitHub Actions instead of Azure Pipelines.
If someone needs to configure Azure Pipelines for one of these projects, don't hesitate to ping me.

**Comment by mshima** [comment]
Same for me for https://github.com/jhipster/generator-jhipster-jooq

**Comment by pascalgrimaud** [comment]
@JasonTypesCodes : just added you to admin team for Micronaut projects

**Comment by pascalgrimaud** [comment]
@mshima : I created a new team jOOQ admins and added you

**Comment by mshima** [comment]
> @mshima : I created a new team jOOQ admins and added you

Done.

**Comment by DanielFran** [comment]
@pascalgrimaud Everything has been migrated.
Can this be closed?

**Comment by pascalgrimaud** [comment]
no, unfortunately, it's not finished yet...

Still to do on my side:
- check all Sonar analysis
- check all configuration at Azure DevOps (there are a lot of projects...), unless we decide to migrate to GitHub Actions

**Comment by avdev4j** [comment]
@SudharakaP @pascalgrimaud FYI the jhipser-bot used in the JHipster online is still creating master branch we creating a new project.

I don't think we noticed that ;)

**Comment by pascalgrimaud** [comment]
@avdev4j : I think it's because this PR https://github.com/jhipster/jhipster-online/pull/255 is not deployed to GCP yet

**Comment by avdev4j** [comment]
great !

**Comment by pascalgrimaud** [comment]
What was done:
- Azure DevOps should be configured correctly for active project (JHipster Kotlin)
- All SonarCloud projects should use main branch
- at Docker Hub:
    - jhipster
    - jhipster-online
    - jhipster-registry
    - consul-config-loader
    - jhipster-control-center

I think all work is done so the ticket can be closed !

**Comment by pascalgrimaud** [comment]
The last thing to do will be to delete the master branch
But I prefer to do it next year (in january 2021) so all our users can update their module / blueprint

**Comment by pascalgrimaud** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/28148
