### ISSUE TITLE
Broken Links in Showcase of Apps

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#11945]
##### **Overview of the issue**

As [mentioned in my email](https://groups.google.com/forum/#!topic/jhipster-dev/ZcoTQagXF0s); most of the webpages in our app showcase seems to have broken links or pointing to GitHub pages.

**1) Devoxx** 

Gives a security warning (SSL certificate problems). 

@deepu105 : Since you have added this, do you know a different link perhaps? :smile_cat: 

**2) Dan Cancro's Great Big Example Application** 

This one is a sample application and the link points to the GitHub repo. I vote for removing this since the showcase should probably include real world applications that are made using jhipster? :smile: 

<strike>**3) SoundXtream Audio Platform** 

This one takes us to the GitHub account. And there's a link to application there; but it doesn't seem to work (http://soundxtream.com/). 

@xavierpandis: Do you have this app running somewhere? If so update us with the link so we can update it. :smile: 

**4) The Rock Bible**

Link points to the GitHub repo.

@jotabono: Is this app deployed? If so please update us with the link. :smile: 

**5) Real State Camp**

Link points to the GitHub repo.

@arnaugarcia: Is this app deployed? If so please update us with the link. :smile: </strike>

**6) Coincoindrone** 

404 error.

@Z3nk: Is this app deployed and running? If so could you please provide us with the link? :smile:  

**7) Guc Voile** 

Points to a YouTube video.   

@GregTres: Do you have the actual url of the application. Maybe we can include that instead? :smile: 

##### **Motivation for or Use Case**

Cleanup the showcase section. 

cc: @jhipster/developers 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Btw showcase doesn't have to be a live app. It can also be a GitHub repo
like the soundextreme one

**Comment by SudharakaP** [comment]
> Btw showcase doesn't have to be a live app. It can also be a GitHub repo like the soundextreme one

@deepu105 : In that case we can keep, 3), 4) and 5) as it is. I've updated the issue. :+1:
