### ISSUE TITLE
[Discussion] [Documentaiton request] Which jhipster blueprints are 1st, 2nd, 3rd tiers?

### ISSUE THREAD

**Issue by agilob** [jhipster/generator-jhipster#11944]
In the last days I've tried quarkus and micronaut, which resulted in a few MR opened with fixes to the generators. At first I generated spring-boot project and converted it to micronaut, then I was confused about compilation error, broken syntax (like missing `,`) etc. Nothing major, but it wasn't stated anywhere what features are supported, what's planned, what works, but I wasted a lot of time trying to figure out what was broken and how to use it (thus the MR fixing some issues).

If possible, could you please compile a table/matrix of features => feature / jhipster what is proven to work, fully supported, WIP, not-supported?

Something in a form:

\    | DTO generation | Pagination | Ehcache |
------------ | ------------- | ------------- | ------------- |
JHipster | 10 | 10 | 10 |
MHipster | 5 | 5 | 0 |
KHipster | x | y | z |

\* consider the numbers random for purpose of demonstration

This would serve users as a documentation/reference on maturity of all(some?) jhispter generators as well as a roadmap.

**Comment by pascalgrimaud** [comment]
@agilob : I agree it will be nice to have to give more visibility to our users. Anyway, it's the entire responsability of each blueprint. So the best would be to open a new ticket in each of blueprint.
