### ISSUE TITLE
Blaze-Persistence support

### ISSUE THREAD

**Issue by Mobe91** [jhipster/generator-jhipster#11947]
##### **Overview of the feature request**

The goal of this feature request is to add support for blaze-persistence to jhipster. Specifically, the user should be able to 

* select blaze-persistence Entity Views as DTO option for an entity and 
* enable keyset pagination for an entity

##### **Motivation for or Use Case**

DTOs using Blaze-Persistence Entity Views directly map to database queries and allow to only fetch the data that is required for the respective DTO, thereby increasing the efficiency of database access.

Also, Blaze-Persistence offers integrations with Spring WebMVC and Spring Data JPA that allow for effortless keyset pagination.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Mobe91** [comment]
I am prepared to create a PR for this but I would appreciate some guidance (already posted to your gitter chat). As far as I understand this would mostly become a second path along MapStruct so it would not go into a separate jhipster module, right?

**Comment by atomfrede** [comment]
I don't know how blaze works, but I would say a blueprint would be a good fit (we have not the capacity to maintain it in the main generator). Do you have an example application maybe that shows what needs to be changed?

**Comment by Mobe91** [comment]
@atomfrede 
Examples:
[Cat WebMVC Controller](https://github.com/Blazebit/blaze-persistence/blob/27622d7ccbcf0f23392bb4b9345694836779ee2f/examples/spring-data-webmvc/src/main/java/com/blazebit/persistence/examples/spring/data/webmvc/controller/CatRestController.java#L108)
[Cat entity](https://github.com/Blazebit/blaze-persistence/blob/27622d7ccbcf0f23392bb4b9345694836779ee2f/examples/spring-data-webmvc/src/main/java/com/blazebit/persistence/examples/spring/data/webmvc/model/Cat.java#L35)
[Cat Entity View/DTO](https://github.com/Blazebit/blaze-persistence/blob/27622d7ccbcf0f23392bb4b9345694836779ee2f/examples/spring-hateoas/src/main/java/com/blazebit/persistence/examples/spring/hateoas/view/CatWithOwnerView.java#L27)
[Cat repository](https://github.com/Blazebit/blaze-persistence/blob/master/examples/spring-data-webmvc/src/main/java/com/blazebit/persistence/examples/spring/data/webmvc/repository/CatViewRepository.java)
Apart from the changes to the above artifacts I would also need to make some changes to the `DatabaseConfiguration` that is currently generated by jhipster + additional dependencies and a new `BlazePersistenceConfiguration` that defines some beans.

**Comment by Mobe91** [comment]
Can you by chance point me to an example of how to create such a blueprint and of how it would be used once created?

**Comment by mshima** [comment]
> Can you by chance point me to an example of how to create such a blueprint

Normally a blueprint is created by copying the generator-jhipster sources, and changing it, but if the changes are simple, you can patch the generated code.

I recommend you to create a sample application, with the required changes in 1 commit and post the link here, so we can take a look.

You can use one of the samples at https://github.com/jhipster/jdl-samples.

> how it would be used once created?

Once the blueprint is ready just add `blueprints [yourBlueprint]` to config section (requires current master), or call `jhipster --blueprints yourBlueprint`

**Comment by pascalgrimaud** [comment]
As already mentionned:
> we have not the capacity to maintain it in the main generator

So to give a try, you should follow these steps:
- create a sample JHipster project, with all default options
- apply the change to use Blaze in 1 single commit -> so you will be able to see all the required changes
- don't hesitate to share code here, link with your GitHub project etc

Depending on a lot of changes or not, depending on your motivation, you can start to code a module / blueprint.
You have a lot of example for that.

Then, you can publish your module and ask feedback from community.
If your module is a great success, we can reconsider this.

For now, I'm closing this ticket and it should go to module/blueprint.
