### ISSUE TITLE
Package name with cassandra database 

### ISSUE THREAD

**Issue by warleyc** [jhipster/generator-jhipster#1194]
hi,

When the database type is cassandra, one package name is hardcoded with   com.mycompany.myapp inside the class  generator-jhipster/app/templates/src/main/java/package/service/_UserService.java :

import <%=packageName%>.repository.UserRepository;<% if (databaseType == 'cassandra') { %>
import com.mycompany.myapp.security.AuthoritiesConstants;<% } %>

a+
Nicolas

**Comment by jdubois** [comment]
Thanks! This is stupid of me, I'm correcting this right away and doing a new release ASAP
