### ISSUE TITLE
[Experimental] Add Support for Spring Fu

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#11967]
##### **Overview of the feature request**

The functional way of running a spring boot application. I know, it is very early and experimental but everyone is pretty excited about this and we should start supporting them. 

##### **Motivation for or Use Case**

Traditionally, we generate a lot of boiler plate code is the major pain point for anyone who is getting started. While this is both our pro and con. We should definitely provide a lite version to generate. Spring-fu will be an ideal way to start generating light weight applications. 

I would like to start adding this feature both here and jhipster/jhipster-kotlin. 

P.S. Spring-fu is definitely not production ready and it is still in experimental stage. But it will be a great sub generator :) 

##### **Related issues or PR**

NA

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@sendilkumarn It's been a few months since you added this. Are you still passionate about it and willing to write the code in the next 30 days? If not, I think we should close this and create a PR when it's more actionable.

**Comment by sendilkumarn** [comment]
I totally forgot it! I have something but it needs few patches, but sadly don't have time to complete it. 

Let us close this one. I will re-open it when the code is ready.
