### ISSUE TITLE
[Integration Testing] Add cypress to the main generator

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#11961]
##### **Overview of the feature request**

[Cypress](https://www.cypress.io) is awesome, it is debuggable and it is easy and framework agnostic. 

##### **Motivation for or Use Case**

Protractor is flaky for react, while there were multiple attempts to fix them. I think it is a high time to move away from the protractor and start using `Cypress`. 

##### **Related issues or PR**

#11923 #11916 #11814 and others

There are a lot of discussions happened before especially this one :: https://github.com/jhipster/jhipster-vuejs/pull/399 

I have also started the migration in this [branch](https://github.com/sendilkumarn/generator-jhipster/tree/feat/add-cypress), let us merge both into the main generator and start using Cypress.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
cc @nassimerrahoui and @adilabed as they already did it for JHipster Control Center, and nearly finished the work from @clementdessoude in Vue.js blueprint

Then, @sendilkumarn, I would suggest to add Cypress for v6 if possible AND remove Protractor in v7

**Comment by sendilkumarn** [comment]
> Then, @sendilkumarn, I would suggest to add Cypress for v6 if possible AND remove Protractor in v7

@pascalgrimaud I like this idea.

>  @nassimerrahoui, @adilabed & @clementdessoude 

Can we start working on this in a branch (likely this [one](https://github.com/sendilkumarn/generator-jhipster/tree/feat/add-cypress)) or any other?  WDYT?

**Comment by adilabed** [comment]
>> Can we start working on this in a branch (likely this [one](https://github.com/sendilkumarn/generator-jhipster/tree/feat/add-cypress)) or any other (instead of duplicating work)? WDYT?

I am in favor of concentrating our efforts in this branch https://github.com/sendilkumarn/generator-jhipster/tree/feat/add-cypress, instead of duplicating work.

**Comment by nassimerrahoui** [comment]
> > Then, @sendilkumarn, I would suggest to add Cypress for v6 if possible AND remove Protractor in v7
> 
> @pascalgrimaud I like this idea.
> 
> > @nassimerrahoui, @adilabed & @clementdessoude
> 
> Can we start working on this in a branch (likely this [one](https://github.com/sendilkumarn/generator-jhipster/tree/feat/add-cypress)) or any other (instead of duplicating work) ? WDYT?

Yes, it's sounds good to me ! :+1:

**Comment by nassimerrahoui** [comment]
As discussed with other members, there is 3 solutions :

- Write e2e Cypress tests for each framework like Protactor,

- Instead of writing e2e tests for each framework, maybe we can use specific attributes to select elements and write common e2e tests for all frameworks including Vuejs blueprint (cf. [Cypress documentation for selecting elements](https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements)).

- Create a sub generator for e2e tests

**Comment by clementdessoude** [comment]
I like the idea of targetting specific attributes for selecting elements. In the end game, it will:
- guarantee an uniformisation between each framework used (frontend+backend)
- ease the burden of maintaining the e2e tests

**Comment by sendilkumarn** [comment]
I am all in for targeting specific attributes for selecting elements. But it will be a pain to maintain it across blueprints and an unwanted dependency to carry forward. I am all in if we can find a way around it. 

But yeah the main generator should have only one cypress test suite. Let us refactor it. I will create a project in that repo, feel free to pick whatever you like and we will ship it 👍 Looking forward to it already.

**Comment by jdubois** [comment]
Adding a $100 bug bounty as proposed by @MathieuAA on https://github.com/jhipster/generator-jhipster/issues/11805

**Comment by avdev4j** [comment]
hi @sendilkumarn 
it seems the Cypress feature has moved forward and we have some test cases available. I would like to help you and @nassimerrahoui @adilabed to complete the feature and to having it in our first v7 release.

WDYT? Have you any idea of what is in to do?

I have checked this branch https://github.com/sendilkumarn/generator-jhipster/tree/feat/add-cypress and this project https://github.com/sendilkumarn/generator-jhipster/projects/1

regards,

**Comment by avdev4j** [comment]
Finally we move the cypress current work to my JHipster fork because we were not able to rebase from last master version. A draft PR has been open here. We need to:
- Check 2e2 sub-generator since core mechanism has been deeply rework 
- Add Vue Cypress tests
- Add generator unit tests
- Deprecate protractor and remove ** in development** label for Cypress

**Comment by pascalgrimaud** [comment]
increasing the bounty as it's a lot of work to achieve it

**Comment by pascalgrimaud** [comment]
It's a lot lot lot of work to achieve this, and it was a team work.
So I increase the bounty to 600, and propose this split:
- @nassimerrahoui : 250 as main lead
- @adilabed : 150 as co main lead
- @mshima : 100 for fix and review
- @qmonmert : 100 for test and review

@avdev4j : it was during your full time contribution to JHipster

Hope you're ok with this.
Ping me when you claim the bounty, so I can check and approve. 

As the work is achieved, let's close this. 
Again, congrats all contributors !

**Comment by avdev4j** [comment]
Let's do that! Congrats everyone

**Comment by nassimerrahoui** [comment]
@pascalgrimaud : Bounty claimed [](https://opencollective.com/generator-jhipster/expenses/24786)

**Comment by adilabed** [comment]
@pascalgrimaud : Bounty claimed https://opencollective.com/generator-jhipster/expenses/24787

**Comment by pascalgrimaud** [comment]
@nassimerrahoui @adilabed : approved

**Comment by qmonmert** [comment]
@pascalgrimaud : Bounty claimed https://opencollective.com/generator-jhipster/expenses/24793

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by tillias** [comment]
Is there any example of how to use cypress with JWT Token?

I can't pass through jhi related stuff because something really cheesy is customized there:

```
let jwt_token

before(function fetchUser() {
    cy.request('POST', '/api/authenticate', {
        username: 'user',
        password: 'user',
    })
        .its('body')
        .then((res) => {
            jwt_token = res.id_token
        })
})

beforeEach(function setUser() {
    cy.visit('/', {
        onBeforeLoad(win) {
            win.sessionStorage.setItem('jhi-authenticationtoken', jwt_token)
        }
    })
})

describe('test', () => {
    it('check login works programmatically', () => {
        cy.visit('/');
        cy.get('.lead').should('have.text', 'Here is microservices catalog');
        cy.get('#home-logged-message').should('have.text', 'You are logged in as user "user".')
    })
})
```
