### ISSUE TITLE
jhipster with spreadjs not working while generated  project though online UI  monolithic project .

### ISSUE THREAD

**Issue by shivroy121** [jhipster/generator-jhipster#11976]
Hi Team ,

I have created the project though jhipster online ui application and trying to use spreadjs . I am getting the error 

ERROR in node_modules/@grapecity/spread-sheets-angular/dist/gc.spread.sheets.angular.ts:247:17 - error TS7029: Fallthrough case in switch.

247    case 'autoGenerateColumns':

The same application i created though cli  - jhipster --skip-server --db=sql --auth=jwt it is working .

npm install @grapecity/spread-sheets@12
npm install @grapecity/spread-sheets-angular@12

import { SpreadSheetsModule } from '@grapecity/spread-sheets-angular';

added in app module

<div class="opbox" id="viewFileData" style="height:460px;"></div>
----------------------------
In Component .

import * as GC from '@grapecity/spread-sheets';
spread:any;
sheet:any;

ngOnInit(): void {
const ele = document.getElementById('viewFileData');
this.spread = new GC.Spread.Sheets.Workbook(ele);
this.sheet = this.spread.getSheet(0); 
const activeSheet = this.spread.getActiveSheet(); 
activeSheet.setValue(10, 9, "Hashu"); 
}

I Added the code reference to produce  the issue . Kindly check once .

**Comment by SudharakaP** [comment]
The error that you are describing is coming from the spread js library. Do you a complete stack trace you could post? Any other logs that precedes this error?

`ERROR in node_modules/@grapecity/spread-sheets-angular/dist/gc.spread.sheets.angular.ts:247:17 - error TS7029: Fallthrough case in switch`

And seems spreadjs is close source and therefore I couldn't find a GitHub issue tracker or something which points to their bugs. My guess is you'll have better luck posting this on StackOverflow with the spreadjs label. But maybe some other members can chip in. :thinking:

**Comment by shivroy121** [comment]
Hi SudharakaP ,

Thanks for your response  . Yes spreadjs is not open source . but you can use it for testing with licence key . They error log is only coming this much . It is working in cli generate project . So might question got what difference there with ui generated &  cli generated project  .

Regards
Shiv

**Comment by pascalgrimaud** [comment]
Sorry @shivroy121 but for this kind of question, it's better to use StackOverFlow.
This section is only for bugs in generator-jhipster : as you modified the generated code, there is no bug on our side.
That's why I'm closing this.
