### ISSUE TITLE
Upgrade to support angular v10.0

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#11990]
##### **Overview of the feature request**
Angular v10.0 has been released. Checkout the details at https://blog.angular.io/version-10-of-angular-now-available-78960babd41

##### **Motivation for or Use Case**

It would be good to support latest angular version before next JHipster release.
- [ ] Upgrade angular version and associated dependencies in `JHipster`
- [ ] Upgrade angular version and associated dependencies in `ng-jhipster`

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
I will be starting on it..

**Comment by pascalgrimaud** [comment]
you're awesome @vishal423 !
