### ISSUE TITLE
Generator from DB to entities

### ISSUE THREAD

**Issue by Kahfimaulana** [jhipster/generator-jhipster#1200]
Hey I am new in using Jhipster. I have tried some features and it's really nice to have a spring-boot and angularJS combined. I just have some feature request to generate from db to entity. :) is that possible things ? 
Nice work. Amazing :+1:

**Comment by jdubois** [comment]
No, we can't do it -> we work the other way around
If you want this kind of feature, you can have a look at http://www.springfuse.com/
