### ISSUE TITLE
Please include some minimal security settings for the included elasticsearch.yml

### ISSUE THREAD

**Issue by nomuna** [jhipster/generator-jhipster#12015]
The default elasticsearch.yml included with the jhipster is

1. not secured (not even a user and a password). 
2. it is also listening on all the external ip addresses of the server/host it is running on 

which is a security issue IMHO.

Or at least document it in the README.md or something. I tried http.host=127.0.0.1 in the environment section of the elasticsearch,yml, The container starts but I can't access it from localhost as well.

**Comment by pascalgrimaud** [comment]
For me, it is not a security issue as the provided `elasticsearch.yml` file is for development only: it works out of the box.
It's similar to what we do for all database configuration, with no password or default one.

I don't understand your other problem, plz provide more information
> Or at least document it in the README.md or something. I tried http.host=127.0.0.1 in the environment section of the elasticsearch,yml, The container starts but I can't access it from localhost as well.

**Comment by nomuna** [comment]
If you download the elasticsearch as an archive from the elasticsearch site and let it run, then with the default configuration it is reachable only over localhost. 

With the container, even if it is on my local machine I don't want it exposing a port on my machine. An open installation of elasticsearch without any password or user, and the rest endpoints are open to public. You can do POST requests. 
I don't like this. I stopped using the container and installed it as a service on my machine using the zipped version.

But others may not be so lucky to notice it and may deploy it on a production server. $hit happens...

https://www.zdnet.com/article/a-hacker-has-wiped-defaced-more-than-15000-elasticsearch-servers/
https://www.zdnet.com/article/elasticsearch-server-exposed-the-personal-data-of-over-57-million-us-citizens/

**Comment by nomuna** [comment]
how about just change the included compose files port section to

    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300

seems to do the trick. The postgresql.yml needs to be changed as well since it has the same problem.

**Comment by Tcharl** [comment]
We could even go further and configure opendistro when the chosen option is oauth2 and docker-compose or k8s for prod configuration.

However, I've the same opinion the @pascalgrimaud : the actual configuration is for dev and it works well for local machine, letting the user to have an insecure prod configuration would encourage the risk (using 127.0.0.1 means letting elastic being deployed on another machine than the developper one). I don't think jhipster's goal is to produce production-ready docker-compose or k8s yml that do not need any modification, but it could be something to think about :-).

**Comment by gmarziou** [comment]
Thanks @nomuna for pointing this out, I never thought of it. I tested the "127.0.0.1:xxxx:yyyy" configuration with Postgresql and `netstat` confirmed that the port is bound to `127.0.0.1` instead of `0.0.0.0`.

I agree with @pascalgrimaud and @Tcharl who said that the generated configuration si for dev and you must harden it before going to production. However, even in dev, it's safer to lock your containers on your own PC by default because you might be using it in an unsafe environment (e.g. in a conference) or your enterprise network might have been compromised.

For me, this proposition sounds like a good improvement. I would be in favor of using it for all containers with a small comment like:

```
# If you want to expose these ports outside your dev PC, remove the "127.0.0.1:" prefix
ports:
  - 127.0.0.1:9200:9200
  - 127.0.0.1:9300:9300
```

I'd also be in favor of adding a warning comment at the top of your dockeere-compose files saying something "This configuration is intended for development purpose, it's your responsibility to harden it for production".

**Comment by nomuna** [comment]
> 
> 
> Thanks @nomuna for pointing this out, I never thought of it. I tested the "127.0.0.1:xxxx:yyyy" configuration with Postgresql and `netstat` confirmed that the port is bound to `127.0.0.1` instead of `0.0.0.0`.
> 
> I agree with @pascalgrimaud and @Tcharl who said that the generated configuration is for dev and that you must harden it before going to production.
> 
> However, even in dev, it's safer to lock your containers on your own PC by default because you might be using it in an unsafe environment (e.g. a conference) or your enterprise network might have been compromised.
> 
> For me, this proposition sounds like a good improvement. I would be in favor of using it for all containers with a small comment like:
> 
> ```yaml
> # If you want to expose these ports outside your dev PC, 
> # remove the "127.0.0.1:" prefix
> ports:
>   - 127.0.0.1:9200:9200
>   - 127.0.0.1:9300:9300
> ```
> 
> I'd also be in favor of adding a warning comment at the top of your docker-compose files saying something like:
> 
> > This configuration is intended for development purpose, it's your responsibility to harden it for production

All of this sounds good to me. In a normal linux distro a server software you install comes with a set of sane security defaults to prevent you from getting into trouble. I think containers should follow the same path. Thanks for paying attention to this issue.
