### ISSUE TITLE
Can multi tenancy feature for microservices and gateway be introduced in jhipster which means multi-tenant user support in the same DB schema? I would like to contribute in coding the part.

### ISSUE THREAD

**Issue by shalphaaslam** [jhipster/generator-jhipster#12013]
##### **Overview of the feature request**

The feature of handling different users from multiple tenants in the same DB through the same microservices and gateway would help in usecases such as multi-tenancy support for any particular domain.

##### **Motivation for or Use Case**

Since I am currently working in the Jhipster framework to support multi-tenancy in microservice architecture which is All tenant in one DB schema multi-tenancy mode for easier and simpler scalable services.

##### **Related issues or PR**

Existing multi-tenancy support in jhipster marketplace hold only for monolithic application and I would like to contribute on the microservices and gateway coding part of the feature if possible.

-   [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
As you already mentionned, there is indeed an existing blueprint for that:
https://github.com/sonalake/generator-jhipster-multitenancy

The best would be to go there, and help this project to add microservices/gateways support.
cc @CharlotteFawsitt @jduggan83

**Comment by pascalgrimaud** [comment]
Closing this in favor of the existing blueprint
