### ISSUE TITLE
Swagger doesn't work

### ISSUE THREAD

**Issue by jperezdelafuente** [jhipster/generator-jhipster#12025]
Since jHipster 6.10.0 the swagger api doesn't work in:
- new generate project
- update project from jHipsrer 6.9.1

Swagger API references to: https://petstore.swagger.io/v2/swagger.json
![swagger](https://user-images.githubusercontent.com/9991172/86360552-d55a9b00-bc72-11ea-83ab-a1556caa3bce.PNG)

**Comment by pascalgrimaud** [comment]
@jperezdelafuente : you need to fill the template, otherwise we can't reproduce your issue as we don't have any information

**Comment by jperezdelafuente** [comment]
##### **Overview of the issue**

Since jHipster 6.10.0 the swagger api doesn't work in:
- new generate project
- update project from jHipsrer 6.9.1

##### **Motivation for or Use Case**

Swagger api

##### **Reproduce the error**

 Swagger api doesn't work

##### **JHipster Version(s)**

jHipster 6.10.0 

##### **JHipster configuration**



##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT D:\minah\demo-swagger
`-- generator-jhipster@6.10.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.10.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1593692622903,
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

git version 2.21.0.windows.1

node: v12.16.3

npm: 6.14.5

yeoman: 3.1.1

yarn: 1.16.0

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Withour entities

##### **Browsers and Operating System**

Google Chrome  Versión 83.0.4103.116 (Build oficial) (64 bits)
Windows 10

**Comment by niklasLensing** [comment]
I have the same issue: When I navigate to /admin/docs Swagger opens with the Swagger Petstore just like the screenshot above.
It seems like some Swagger resources cannot be loaded. See the screenshot from my Browser console below.

![grafik](https://user-images.githubusercontent.com/46967813/86472367-58e1be00-bd3f-11ea-8063-6d7d58cb6c4f.png)

**Comment by ruddell** [comment]
Confirmed this is an issue with a new v6.10.x app. To reproduce, generate an app and navigate to the Swagger page.

As a workaround until this is fixed, you can replace the petstore URL https://petstore.swagger.io/v2/swagger.json with http://localhost:8080/v2/api-docs

**Comment by pascalgrimaud** [comment]
Ok, I think it's the same issue than: https://github.com/jhipster/jhipster-vuejs/issues/618
It should be the same fix: https://github.com/jhipster/jhipster-vuejs/pull/619/files

**Comment by pascalgrimaud** [comment]
If the fix is confirmed, then, I'll do a patch release 6.10.1 when possible.

**Comment by vishal423** [comment]
yeah, I did update the copy plugin and seems same issue over here. Just wondering, why none of our automated tests caught this

**Comment by niklasLensing** [comment]
I can confirm that the change from https://github.com/jhipster/jhipster-vuejs/pull/619/files fixes this issue for me.
