### ISSUE TITLE
methode findAll() not exist in UserRepository.class with cassandra choice

### ISSUE THREAD

**Issue by warleyc** [jhipster/generator-jhipster#1202]
hi,
I have a compilation error when I choose the default setting but with cassandra database,
 the method findAll() doesn't  exist in the UserRepository interface.

a+
nicolas

logs :

INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/xxxxx/jh.c/src/main/java/com/mycompany/myapp/web/rest/UserResource.java:[42,30] cannot find symbol
  symbol:   method findAll()
  location: variable userRepository of type com.mycompany.myapp.repository.UserRepository
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.191 s
[INFO] Finished at: 2015-03-03T12:01:14+09:00
[INFO] Final Memory: 32M/284M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jhipster: Compilation failure
[ERROR] /Users/xxxxx/jh.c/src/main/java/com/mycompany/myapp/web/rest/UserResource.java:[42,30] cannot find symbol
[ERROR] symbol:   method findAll()
[ERROR] location: variable userRepository of type com.mycompany.myapp.repository.UserRepository
[ERROR] -> [Help 1]

**Comment by jdubois** [comment]
You are correct, sorry about this!
I'm correcting this ASAP, it should be out in the next release, we should be ready today
