### ISSUE TITLE
Sonar docker exposes same port as kafka - 9092

### ISSUE THREAD

**Issue by vivekmore** [jhipster/generator-jhipster#12037]
##### **Overview of the issue**

Can we have a different default port exposed for sonar docker container in generated code so it doesn't collide with kafka's 9092 port?
e.g. 19092

##### **Motivation for or Use Case**

To allow running sonar and kafka containers parallelly.

##### **Reproduce the error**

Generate app using attached .yo-rc.json

##### **Suggest a Fix**

I can submit a PR if the team agrees on this improvement/suggestion.

##### **JHipster Version(s)**

6.10.0

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.monkey.swing",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.0",
    "applicationType": "monolith",
    "baseName": "jh610",
    "packageName": "org.monkey.swing",
    "packageFolder": "org/monkey/swing",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "asIxYTQ4MzAyODZkZDMyNzg1NzhmNmVlYmZiNjQ2YzRjODE5NTcxYTllZWMyNWE0OTE0YmY2OTg2YzJmNzc4MzJlMTA1YWRlOGM3NmM2NmMxaac1YWIzNGRjNDYwZTZhN2NmNWExNTJiMGVjYTZmZmJjMzJiODQ0MWRmNjE3OGI=",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "minty",
    "clientThemeVariant": "dark",
    "creationTimestamp": 1593568365866,
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "mr"],
    "blueprints": []
  }
}


```

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@vivekmore : I agree. But I think we don't need to expose the port 9092, we can simply remove it. What do you think ?

**Comment by vivekmore** [comment]
Yes I was also was researching about the need to expose 9092.

If you know when sonarqube stopped needing 9092 that be helpful to document here. Otherwise I'll do some more research to find out. I'll remove the port after that.

**Comment by vivekmore** [comment]
Ok it appears 9092 was originally exposed to expose the internally used in-memory H2 database.
