### ISSUE TITLE
Api First should serve provided api.json from /api-docs

### ISSUE THREAD

**Issue by rainoko** [jhipster/generator-jhipster#12033]
##### **Overview of the feature request**

If using predefined api.json or api.yml. It should be logical to serve from api-docs this file content instead of springfox generated json.

##### **Motivation for or Use Case**

Spring fox has limited functionality and not support all what can be described in openapi json on yml. So generating from yml and then generating again api-docs from code will lose some swagger functionality. Also spring fox still generates only swagger 2 doc but api generation is supported also from openapi 3 version so it would be nice to have same version in api-docs.

**Comment by cbornet** [comment]
Yes. We could have 2 paths. One for API first and one for springfox. Ideally the spec of API first would be enhanced with the entity endpoints and Spring Boot actuators defs. That's something I've been wanting to work on from some time.

**Comment by mraible** [comment]
@cbornet Are you working on this? If not, maybe we should close it and you can re-open when you have the bandwidth to work on it.

**Comment by cbornet** [comment]
Yes we can close for now.
Just for info, there's currently a dedicated Springfox Docket for the API-first OAS : https://github.com/jhipster/generator-jhipster/blob/bfe31a7e96c84b05c923fa7ece6af9cc1fcbad50/generators/server/templates/src/main/java/package/config/OpenApiConfiguration.java.ejs#L53
