### ISSUE TITLE
Java compilation version upgrade

### ISSUE THREAD

**Issue by Strat1987** [jhipster/generator-jhipster#12058]
##### **Overview of the feature request**

JHipster still seems to java.version 1.8 in pom.xml used by the maven-compiler-plugin.
Are there plans to upgrade to using a newer version of java to compile?

##### **Motivation for or Use Case**

Since the bundled jib container is already bumped to version 11, what's stopping the team from also updating the java.version used for compilation?

##### **Related issues or PR**

None that I could find.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
We plan to upgrade to java 11 with v7, but still keep source compatibility to java 8 for  a certain amount of time. https://github.com/jhipster/generator-jhipster/pull/12021/files

**Comment by Strat1987** [comment]
@atomfrede That's great to hear! looking forward to the release
