### ISSUE TITLE
databaseless

### ISSUE THREAD

**Issue by obazoud** [jhipster/generator-jhipster#1205]
Hi,

Please provide an option to generate application without database.

Thanks.

**Comment by jdubois** [comment]
You mean with something like RxJava to access the backend? That was my original idea, in fact

**Comment by obazoud** [comment]
My use case is to use generate an 'jhipster' application with OAuth2 authentication and use a remote REST API (with OAuth token).
No need a database.

**Comment by jdubois** [comment]
OK, so that's the same use case as me -> have you had a look at RxJava? This was my favorite choice for doing REST requests to the backend, but I haven't had time to work on it yet

**Comment by jdubois** [comment]
Oh sorry: for OAuth2, you will need a database.... that's how it works

**Comment by jdubois** [comment]
Just to summarize:

- For OAuth2 you need a database: either SQL or MongoDB
- To be databaseless: I agree we should do it sometime, but it's out of scope for the moment. And if we do it, my idea is to use RxJava to do the REST requests, unless someone has some other feedback to send
