### ISSUE TITLE
Reduce code: Add AbstractServiceImpl and extends services of it

### ISSUE THREAD

**Issue by javachavez** [jhipster/generator-jhipster#12059]
Useful to reduce code: Add AbstractServiceImpl and extends services of it:

**ABSTRACT SERVICE**
`public abstract class AbstractServiceImpl<D, E, M extends EntityMapper<E, D>, R extends JpaRepository> {

  protected final Logger log;

  protected final R repository;

  protected final M mapper;

  protected AbstractServiceImpl(final Logger log, final R repository, final M mapper) {
    this.log = log;
    this.repository = repository;
    this.mapper = mapper;
  }

  public D save(final D dto) {
    this.log.debug("Request to save ");
    E entityDomain = this.mapper.inEntityDomain(dto);
    entityDomain = (E) this.repository.save(entityDomain);
    return this.mapper.inDataTransferObject(entityDomain);
  }

  @Transactional(readOnly = true)
  public Page<D> findAll(final Pageable pageable) {
    this.log.debug("Request to get all");
    return this.repository.findAll(pageable).map(entityDomain -> this.mapper.inDataTransferObject((E) entityDomain));
  }

  @Transactional(readOnly = true)
  public Optional<D> findOne(final Long id) {
    this.log.debug("Request to get : {}", id);
    final Optional<E> entityOptional = this.repository.findById(id);
    E entity = entityOptional.orElseThrow(() -> new ElementNotFoundException("not found entity with id= " + id + ""));
    return Optional.of(this.mapper.inDataTransferObject(entity));
  }

  public void delete(final Long id) {
    this.log.debug("Request to delete {}", id);
    this.repository.deleteById(id);
  }
`

**EXAMPLE SERVICE**
public class ExServiceImpl extends AbstractServiceImpl<Entity, EntityDomain, EntityMapper, Repository>{

  protected ExServiceImpl(final Repository repository, final EntityMapper mapper) {
    super(log, repository, mapper);
  }
}

**And the same is applicable for RestControllers in a next step**

**Comment by mraible** [comment]
I'm not against the idea, but I'm closing this issue. Please create a PR and re-open this issue once you have an implementation.
