### ISSUE TITLE
Failing Generated Code Compilation 

### ISSUE THREAD

**Issue by haigopi** [jhipster/generator-jhipster#12060]
##### **Overview of the issue**

./gradlew fails to compile the generated code base.

> Task :openApiGenerate
Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
Successfully generated code to ../build/openapi

> Task :compileJava FAILED
/src/main/java/com/app/publisher/config/OpenApiConfiguration.java:12: error: package springfox.documentation.builders does not exist
import springfox.documentation.builders.RequestHandlerSelectors;
                                       ^
../src/main/java/com/app/publisher/config/OpenApiConfiguration.java:13: error: package springfox.documentation.service does not exist
import springfox.documentation.service.ApiInfo;
                                      ^
../src/main/java/com/app/publisher/config/OpenApiConfiguration.java:14: error: package springfox.documentation.service does not exist
import springfox.documentation.service.Contact;
                                      ^
../src/main/java/com/app/publisher/config/OpenApiConfiguration.java:15: error: package springfox.documentation.spi does not exist
import springfox.documentation.spi.DocumentationType;
                                  ^
../src/main/java/com/app/publisher/config/OpenApiConfiguration.java:16: error: package springfox.documentation.spring.web.plugins does not exist
import springfox.documentation.spring.web.plugins.Docket;

../src/main/java/com/app/publisher/config/OpenApiConfiguration.java:36: error: cannot find symbol
public Docket apiFirstDocket(JHipsterProperties jHipsterProperties) {
           ^
  symbol:   class Docket
  location: class OpenApiConfiguration
8 errors

##### **Motivation for or Use Case**

Compilation Fails.

##### **Reproduce the error**

? Which *type* of application would you like to create? Microservice application
? [Beta] Do you want to make it reactive with Spring WebFlux? Yes
? What is the base name of your application? chefs
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8081
? What is your default Java package name? com.app.publisher
? Which service discovery server do you want to use? JHipster Registry (uses Eureka, provides Spring Cloud Config support and monitor
ing dashboards)
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? MongoDB
? Would you like to use Maven or Gradle for building the backend? Gradle
? Which other technologies would you like to use? Search engine using Elasticsearch, API first development using OpenAPI-generator
? Would you like to enable internationalization support? No
? Besides JUnit and Jest, which testing frameworks would you like to use?
? Would you like to install other generators from the JHipster Marketplace? No

##### **Suggest a Fix**

Seems, missing Springfox dependencies causing the issue when Spring WebFlux had been chosen.
**Since this feature is in BETA and if the corresponding team is already aware of this issue, please close this.** 

##### **JHipster Version(s)**

6.10.1
6.10.0

##### **JHipster configuration**
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
chefs@0.0.0 ..
└── generator-jhipster@6.10.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.app.publisher"
    },
    "jhipsterVersion": "6.10.0",
    "applicationType": "microservice",
    "baseName": "chefs",
    "packageName": "com.app.publisher",
    "packageFolder": "com/app/publisher",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1594434917786,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "reactive": true,
    "skipClient": true,
    "skipUserManagement": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v13.12.0

npm: 6.14.4

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6

##### **Browsers and Operating System**

MAC OS, BRAVE Browser.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Thanks for reporting this issue.

**Comment by qmonmert** [comment]
@haigopi I think that the issue was fixed by this commit https://github.com/jhipster/generator-jhipster/commit/f4f6d511006b6535ecd6b935c093e5ac05e1e7e0#diff-2c3f53e6e847061a8ab6ba212e021632
I don't reproduce

**Comment by qmonmert** [comment]
@pascalgrimaud no response, so I think you can close
