### ISSUE TITLE
jhipster stucks on " The following profiles are active: prod"

### ISSUE THREAD

**Issue by daniboy82** [jhipster/generator-jhipster#12068]
##### **Overview of the issue**

jhipster stucks on " The following profiles are active: prod" when starting with command "mvn -Pprod"

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfiguration' defined in file [/home/dgl/repo-news/target/classes/br/com/dgl/reponews/config/SecurityConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'persistentTokenRememberMeServices' defined in file [/home/dgl/repo-news/target/classes/br/com/dgl/reponews/security/PersistentTokenRememberMeServices.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsService' defined in file [/home/dgl/repo-news/target/classes/br/com/dgl/reponews/security/DomainUserDetailsService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Cannot create inner bean '(inner bean)#2c60ce47' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#2c60ce47': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [br/com/dgl/reponews/config/LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by DESKTOP-660B2KF (10.8.0.2) since 7/13/20, 3:51 AM
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)

##### **Motivation for or Use Case**

no information on spring.log or anywhere else.

##### **Reproduce the error**

command "mvn -Pprod"

##### **JHipster Version(s)**

        <jhipster-dependencies.version>3.6.0</jhipster-dependencies.version>

##### **Browsers and Operating System**

ubuntu 18
openjdk version "11.0.7" 2020-04-14

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Error you posted: `nested exception is liquibase.exception.LockException: Could not acquire change log lock. Currently locked by DESKTOP-660B2KF (10.8.0.2) since 7/13/20, 3:51 AM`

It looks like the liquibase lock may have gotten stuck somehow.  You can unlock it with `./mvnw liquibase:releaseLocks` or do it manually with an SQL query on the database `update databasechangeloglock set locked=false;`

**Comment by daniboy82** [comment]
thanks for your response! the behavior changed :-)

I don't understand why jhipster is trying to recriate my db.

This db is the same I am using for development (-Pdev) and it is already created.

now I get the error:

nException: Error creating bean with name 'liquibase' defined in class path resource [br/com/dgl/reponews/config/LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20200319162100_added_entity_constraints_Clipping.xml::20200319162100-2::jhipster:
     Reason: liquibase.exception.DatabaseException: Duplicate foreign key constraint name 'fk_clipping_fonte_id' [Failed SQL: (1826) ALTER TABLE reponewsdb.clipping ADD CONSTRAINT fk_clipping_fonte_id FOREIGN KEY (fonte_id) REFERENCES reponewsdb.fonte (id)]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)



I tried "./mvnw -Pprod compile liquibase:diff"

is there a way to say to jhipster to bypass it?

**Comment by daniboy82** [comment]
problem solved, i added:

    profiles:
        include: no-liquibase

thanks so much!

**Comment by ruddell** [comment]
Sounds like you solved your issue, closing
