### ISSUE TITLE
.jhipsterignore file

### ISSUE THREAD

**Issue by ecostanzi** [jhipster/generator-jhipster#12080]
##### **Overview of the feature request**
To prevent Jhipster from overriding files, we could add a `.jhipsterignore` file to the workspace. It would have .gitignore-like syntax and could be used to "freeze" files after generation.

##### **Motivation for or Use Case**

These are some of the examples that come to my mind after having used jhipster for a while:

- Services and Controllers are almost never changed by jhipster after the layers (Controller, DTO, Service/QueryService, Repository) have been defined. By .jhipsterignoring the service and the controller after they have been created allow to customize them without going side-by-side.
- in a "DDD" like scenario (pointed out here: https://github.com/jhipster/generator-jhipster/issues/11122#issuecomment-653464042), or simply when I write custom logic into the entities. it could be useful to freeze the entity and handle the upgrade manually. 
- sometimes I don't need to generate a controller for an entity, I just use the entity and the repository in my business layer. (though a `@skipCrud` in the jdl is probably more appropriate) 
- liquibase changeset should never change (see also: https://github.com/jhipster/generator-jhipster/issues/11398
- Other "fragile" files: `SecurityConfiguration`, `UserService`, email templates

There are other scenario where this feature can be useful, these are some of them. 

I drafted the change here: https://github.com/ecostanzi/generator-jhipster/commit/f58e95ac51adf5debc9ae6fa1375e3d9b69ea23d. If you like the idea I can move on. 

##### **Related issues or PR**

I took the idea after reading this issue: https://github.com/jhipster/generator-jhipster/issues/9171

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Not fully convinced yet.
But, this approach won't work for:
- needles
- copy: https://github.com/jhipster/generator-jhipster/blob/dc03fd49b71fe2e8560b24e93cf002431ae4bcb7/generators/generator-base-private.js#L795
- modules and blueprints that don't use jhipster`s apis.

It should be implemented at yeoman-generator.
IMO the right approach is just like https://github.com/jhipster/generator-jhipster/commit/750236bf533dbc20cf545fea52200d7a230f6479 but use `skip` instead of `force`.

I prefer `.yo_overrides` that would allow for set 'force' or 'skip' based on the glob result, something like.
```
src/webapp/** = skip
src/** = force
```

**Comment by ecostanzi** [comment]
Thank you for pointing out. Would yeoman transformstream approach solve all the three issues you raised?

BTW i'd still suggest a dedicated ignore file. As a developer, I cannot think at a scenario where I want to choose a file and force the override for it, but I could miss some point in this case.

**Comment by mshima** [comment]
> Thank you for pointing out. Would yeoman transformstream approach solve all the three issues you raised?

To solve point 3 it needs to be implemented upstream.
You can implement here and once it’s is ready I can help moving it upstream.

> BTW i'd still suggest a dedicated ignore file. As a developer, I cannot think at a scenario where I want to choose a file and force the override for it, but I could miss some point in this case.

Not just force, you could add support to:
- skip: don’t commit the file others transforms and log applies.
- ignore: remove the modified state from nem-fs and remove the file from transform queue.
- diff: skips the file but print the diff.
- whitespace: forces when only whitespaces has changed.
- bail: throws an error if the file changed.

They are conflicter features.
Probably we should call `.yo-resolver`.

Adding support only to ignore don’t seems right to me.

**Comment by mshima** [comment]
Another request for a similar feature https://github.com/jhipster/generator-jhipster/issues/12054

**Comment by mshima** [comment]
@ecostanzi I feel you should close this issue and open at yeoman-environment so we could discuss there:
- Any motivation for this as a jhipster feature is just hacky.
If we want DDD, we should implement DDD, not ignoring non-DDD file.
If we want immutable liquibase, we should implement incremental liquibase changelog.
This is a feature jhipster should support at all.
- As a generic yeoman feature is doable, but just ignoring the file is half backed feature to me.

**Comment by ecostanzi** [comment]
@mshima ok I understand your point, ignoring files is more a yeoman task than a jhipster task. I'll see if I can address it on yeoman environment. 

However, preventing jhipster from overriding files during entity re-generation or upgrades is something that occasionally comes out. If on one hand I agree with you that a .jhipsterignore is hacky, on the other hand I think it should be addressed at a higher level by Jhipster. I'm not a big fan of the side-by-side approach, it applies to services and repositories but not to entities. And all the extensions are something you wouldn't do as developer when working on a spring boot project without jhipster. 

That said I don't have an answer to all these doubts, just thinking out loud. Thank you for the valuable discussion.

**Comment by pascalgrimaud** [comment]
@ecostanzi : you can easily use your own shell script to do the revert of folders/files you want

**Comment by mshima** [comment]
@ecostanzi I recommend you to implement inside your jhipster branch for now.
I am doing a major cleanup at yeoman's generator/environment/test, in the end it will be pretty much a transformer like https://github.com/jhipster/generator-jhipster/commit/750236bf533dbc20cf545fea52200d7a230f6479, that just read the config and sets conflicter field.

**Comment by ecostanzi** [comment]
@pascalgrimaud I was looking for a solution that can be versioned and shared with the team. I'll definitely consider a script for simpler cases though :)

@mshima sure thanks I'll give it a try.

**Comment by mraible** [comment]
Any updates on this feature? I'm not confident it's needed, but I'll leave that decision up to y'all!
