### ISSUE TITLE
Problem in pagination

### ISSUE THREAD

**Issue by AksuX** [jhipster/generator-jhipster#1208]
Pagination brokes down if do following:
- you have 2 pages of item
- click last ">>"
- click first "<<"
- where should now read "2", it reads "11"

Problem is that page is string when reading it from the header. Quick and dirty fix is to change line in parse-links.service.js ->
```javascript
                var page = queryString['page']; 
                // this is new code (starts from line 26)
                if( angular.isString(page) ) {
                  page = parseInt(page);
                }
```

Also it's not good that we lose the url when clicking the pagination links so I would remove all 'href="#"' from the nav/pagination element EG. ->
 ``` html
<nav>
      <ul class="pagination">
        <li ng-show="links['first']" ng-click="loadPage(links['first'])"><a>&lt;&lt;</a></li>
        <li ng-show="links['prev']" ng-click="loadPage(links['prev'])"><a>&lt;</a></li>
        <li ng-show="page > 2" ng-click="loadPage(page - 2)"><a>{{page - 2}}</a></li>
        <li ng-show="page > 1" ng-click="loadPage(page - 1)"><a>{{page - 1}}</a></li>
        <li class="active"><a>{{page}}</a></li>
        <li ng-show="page < links['last']" ng-click="loadPage(page + 1)"><a>{{page + 1}}</a></li>
        <li ng-show="page < links['last'] - 1" ng-click="loadPage(page + 2)"><a>{{page + 2}}</a></li>
        <li ng-show="links['next']" ng-click="loadPage(links['next'])"><a>&gt;</a></li>
        <li ng-show="links['last']" ng-click="loadPage(links['last'])"><a>&gt;&gt;</a></li>
      </ul>
    </nav>
```

Also i think that it would be lot nicer if the pagination would be own directive...

**Comment by jdubois** [comment]
You are correct about the 2 changes you mention (in fact I already did the first one, but I messed up when doing the templates!).
You are also correct, this should be a directive -> I'm opening another issue for this
