### ISSUE TITLE
JHipster Control Center

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#12090]
##### **Overview of the feature request**
A few weeks ago, @PierreBesson has written an RFC to provide companion sidecar to manage JHipster apps (https://github.com/jhipster/generator-jhipster/issues/10913). This RFC is available here : https://github.com/jhipster/generator-jhipster/blob/master/rfcs/2-jhipster-rfc-jhipster-control-center.md

We decide to focus this feature on the V7. This is a different way to imagine how we can manage and control JHipster applications, monoliths or microservices.

This is how JHipster Control Center (aka JHCC) is born.

##### **Who are you JHCC?**
[JHipster Control Center](https://github.com/jhipster/jhipster-control-center) is a JHipster separated application that will allow you to manage and control your microservice or monolith applications from a single place.

Spring Cloud is used to reach your applications, 4 modes are supported:
- Eureka server
- Consul Server
- Kubernetes
- A static range URI

You can log to JHCC through:
- JWT
- Oauth2

You can test your API through a unified Swagger-UI.

The management UI is developed with Vue front-end framework.

##### **How to use JHCC**
We plan to provide JHCC through a Docker image or a jar file. JHipster applications will contains all the necessary Docker-compose configuration file to start JHCC out of the box.
JHCC is made to help developers during both development and production phases, that's why we want JHCC to be easy as possible to be ran.

##### **What are the consequences to generated JHipster applications?**
JHipster would no longer generate these features since they will be dedicated to JHCC:
- Open-api documentation
- Logs, Metrics, Configuration, properties and Health admin pages

These mean less generated code, to simplify the maintenance and avoid duplicate UI through 3 different frameworks.
Also, we want to, by this way, reduce the front-end compilation time. 

JHipster Registry will be deprecated for V7+.

##### **Conclusion**

The application is still under development and @nassimerrahoui and @adilabed are the main contributors since this is their traineeship subject. We are glad to know they are outperforming our expectations for this feature.
But, as usual, there is a lot of work to remain and we really need the community help to fully integrate this application into the V7.

Feel free to contribute and give us feedbacks.

PS: A list of what we will have to do on main generator
- [x] Don't always generate admin ui (Angular/React/Vue) https://github.com/jhipster/generator-jhipster/pull/12738
- [x] Add JHCC Docker-Compose files https://github.com/jhipster/generator-jhipster/pull/12126
- [ ] Add JHCC Docker-Compose in Docker-Compose subgen (cc @PierreBesson)
- [ ] Add JHCC Kubernetes in Kubernetes subgen (cc @PierreBesson)
- [x] Review the following question:
> Do you want to use the JHipster Registry to configure, monitor and scale your application?

cc @jhipster/developers

**Comment by atomfrede** [comment]
Really great work from what I have seen already! :+1: One thing I am not sure how we plan to handle this following: In e.g. micronaut blueprint we have modified the metrics page because the response format is a little different. Is there a solution for that already or any idea how to handle such things within the JHCC?

**Comment by avdev4j** [comment]
I don't think so @atomfrede but indeed why not to include this in the current JHCC? Or better, find a way to personalize JHCC without forking the project. I know this is what @PierreBesson target for future releases.

**Comment by PierreBesson** [comment]
@atomfrede I would say it's OK if not all actuator endpoints are available in all backends (some people might disable specific endpoints on purpose [as described in the docs](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-enabling-endpoints)). I was thinking that the JHCC should use the /management listing endpoint to know which endpoint is available. The idea has never been to be spring boot specific. JHCC was conceived to be the common interface between jhipster applications using all kinds of front-end and backend technologies.

**Comment by atomfrede** [comment]
Sounds good. Looking forward for whats coming here!

**Comment by pascalgrimaud** [comment]
We need to review this question too: `? Do you want to use the JHipster Registry to configure, monitor and scale your application?`

As by default, we'll have a new `jhipster-control-center.yml` file, in `src/main/docker/` folder

**Comment by PierreBesson** [comment]
JHCC docker-compose and Kubernetes sub-gen support remain to be done. I guess "Don't always generate admin ui (Angular/React/Vue)" is developed and merge. Ping @avdev4j

**Comment by avdev4j** [comment]
Exactly :) I check the box.

**Comment by pascalgrimaud** [comment]
Work done here: https://github.com/jhipster/jhipster-control-center
Now we can open the tickets in this repo instead of the main generator-jhipster.
