### ISSUE TITLE
"jhipster info" outputs "identical .jhipster/EntityName.json" for all entities

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#12092]
##### **Overview of the issue**
`jhipster info` prints `identical .jhipster/EntityName.json` for all entities after it runs.

##### **Motivation for or Use Case**
This information is unnecessary and shouldn't be printed during `jhipster info`. It logs once per entity, so apps with many entities have many extra logs.

Also files should not be modified during `jhipster info`

##### **Reproduce the error**
- Generate an app with entities
```
    jhipster jdl --inline \
        "application { entities * }
         entity Foo { name String }
         entity Bar { name String }
         entity Baz { name String }
        "
```
- Run `jhipster info`
- See the extra logs at the end of the output:
```
docker-compose version 1.25.5, build 8a1c60f6

identical .jhipster/Bar.json
identical .jhipster/Baz.json
identical .jhipster/Foo.json
INFO! Congratulations, JHipster execution is complete!
```

##### **Related issues**
`git bisect` shows the first failing commit as 990550f84a1600aedc854cf97d5c6e13b5b2eb33, part of https://github.com/jhipster/generator-jhipster/pull/11447:
```
990550f84a1600aedc854cf97d5c6e13b5b2eb33 is the first bad commit
commit 990550f84a1600aedc854cf97d5c6e13b5b2eb33
Author: Marcelo Boveto Shima <marceloshima@gmail.com>
Date:   Sat Mar 7 17:19:56 2020 -0300

    Enable prettier for .jhipster/* and use this.fs for read and verify.

:040000 040000 a339a1c024c9ebaaf81f06ad03429b44e00e1bdb 0e94949fd6c3b56cd31378442014e40011020cb7 M	generators
```
##### **Suggest a Fix**

Not sure where this is coming from, @mshima may be more familiar as they made the change.

##### **JHipster Version(s)**
Not present in v6.8.0
Present in v6.9.0+

##### **JHipster configuration**
  <details>
  <summary>JDL definitions</summary>
  <pre>
         application { entities * }
         entity Foo { name String }
         entity Bar { name String }
         entity Baz { name String }
  </pre>
  </details>

##### **Environment and Tools**
  <details>
  <summary>Environment and Tools</summary>
  <pre>
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.20.1

node: v12.16.1

npm: 6.14.5

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6
  </pre>
  </details>

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
The source is:
https://github.com/jhipster/generator-jhipster/blob/990550f84a1600aedc854cf97d5c6e13b5b2eb33/generators/generator-base.js#L1324-L1325

I did this change because import-jdl generates `.jhipster/*.json` but not prettified.

We can workaround with a property like `this.skipEntitiesRewrite` but in my opinion the fix is jhipster-core to return the files structures and let the generator write them, so the files will be prettified. Rewriting `.jhipster/*.json` can be removed.

**Comment by kaffelmedhoussem67** [comment]
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.1-SNAPSHOT C:\Users\Kaffel med houssem\Documents\CRMSAAS\gateway
`-- generator-jhipster@6.10.5

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": false,
    "baseName": "gateway",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["cucumber"],
    "websocket": false,
    "packageName": "com.crm.developer.gateway",
    "packageFolder": "com/crm/developer/gateway",
    "applicationType": "gateway",
    "useSass": true,
    "jhipsterVersion": "6.10.5",
    "creationTimestamp": 1617536400605,
    "skipServer": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["Leads", "Claim", "Software", "Sales", "Activities"]
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Leads {
  firstname String required minlength(3),
  lastname String required minlength(2),
  email String required unique pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
  score Float,
  inscridate Instant required,
  phonenumber String unique,
  statut Status required
}
entity Claim {
  title String required,
  content TextBlob required,
  dateclaim Instant required,
  secreenshot ImageBlob
}
entity Software {
  softwareName String required,
  price BigDecimal required min(0),
  softwareType Softwaretype
}
entity Sales {
  salesdate Instant,
  typeContract TypeContract
}
entity Activities {
  activityname String required,
  content TextBlob,
  dateActivity Instant required,
  activityType Activetype
}
enum Status {
  NEW,
  POTENTIAL,
  CUSTOMER
}
enum Softwaretype {
  VOIP,
  ACCOUNTING_SOFTWARE,
  EMAIL_CLIENT_SOFTWARE
}
enum TypeContract {
  TRIMESTER,
  SEMESTER,
  ANNUAL
}
enum Activetype {
  EMAIL,
  CALL,
  MEETING
}

relationship OneToMany {
  Software{sales} to Sales{software}
}

paginate Leads, Claim, Software, Sales, Activities with infinite-scroll
search Leads, Claim, Software, Sales, Activities with elasticsearch

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

git version 2.28.0.windows.1

node: v14.16.0

npm: 6.14.11

yeoman: 3.1.1

yarn: 1.22.10

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build c4eb3a1f

identical .jhipster\Activities.json
identical .jhipster\Claim.json
identical .jhipster\Leads.json
identical .jhipster\Sales.json
identical .jhipster\Software.json
INFO! Congratulations, JHipster execution is complete!

**Comment by kaffelmedhoussem67** [comment]
this is my jhipster s info : 
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.1-SNAPSHOT C:\Users\Kaffel med houssem\Documents\CRMSAAS\gateway
`-- generator-jhipster@6.10.5

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": false,
    "baseName": "gateway",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["cucumber"],
    "websocket": false,
    "packageName": "com.crm.developer.gateway",
    "packageFolder": "com/crm/developer/gateway",
    "applicationType": "gateway",
    "useSass": true,
    "jhipsterVersion": "6.10.5",
    "creationTimestamp": 1617536400605,
    "skipServer": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["Leads", "Claim", "Software", "Sales", "Activities"]
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Leads {
  firstname String required minlength(3),
  lastname String required minlength(2),
  email String required unique pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
  score Float,
  inscridate Instant required,
  phonenumber String unique,
  statut Status required
}
entity Claim {
  title String required,
  content TextBlob required,
  dateclaim Instant required,
  secreenshot ImageBlob
}
entity Software {
  softwareName String required,
  price BigDecimal required min(0),
  softwareType Softwaretype
}
entity Sales {
  salesdate Instant,
  typeContract TypeContract
}
entity Activities {
  activityname String required,
  content TextBlob,
  dateActivity Instant required,
  activityType Activetype
}
enum Status {
  NEW,
  POTENTIAL,
  CUSTOMER
}
enum Softwaretype {
  VOIP,
  ACCOUNTING_SOFTWARE,
  EMAIL_CLIENT_SOFTWARE
}
enum TypeContract {
  TRIMESTER,
  SEMESTER,
  ANNUAL
}
enum Activetype {
  EMAIL,
  CALL,
  MEETING
}

relationship OneToMany {
  Software{sales} to Sales{software}
}

paginate Leads, Claim, Software, Sales, Activities with infinite-scroll
search Leads, Claim, Software, Sales, Activities with elasticsearch

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

git version 2.28.0.windows.1

node: v14.16.0

npm: 6.14.11

yeoman: 3.1.1

yarn: 1.22.10

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build c4eb3a1f

identical .jhipster\Activities.json
identical .jhipster\Claim.json
identical .jhipster\Leads.json
identical .jhipster\Sales.json
identical .jhipster\Software.json
INFO! Congratulations, JHipster execution is complete!
