### ISSUE TITLE
One To Many Relationship (postgres) Fails Integration Tests 

### ISSUE THREAD

**Issue by RDsideNow** [jhipster/generator-jhipster#12091]
##### **Overview of the issue**

Integration Test Fails when there is no required tag on the many entity

##### **Motivation for or Use Case**

gitlab ci-cd fails when the integration tests fail

##### **Reproduce the error**

Import JDL
Run the integration tests

##### **Related issues**

#12076 

##### **Suggest a Fix**

I believe it has something to do with filtering.  If i add the require tag to the many side of the relationship and import the jdl, the integration tests resolve

##### **JHipster Version(s)**

v6.10.1

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
vendor@0.0.0 /Users/Repos/GitLab/jhipster bugs/vendor
└── generator-jhipster@6.10.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "serverPort": "8083",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "baseName": "vendor",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["fr", "es", "en"],
    "messageBroker": "kafka",
    "nativeLanguage": "en",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": true,
    "testFrameworks": ["gatling", "cucumber"],
    "websocket": false,
    "applicationType": "microservice",
    "packageName": "com.jhipster.demo.vendor",
    "packageFolder": "com/jhipster/demo/vendor",
    "uaaBaseName": "uaa",
    "clientPackageManager": "yarn",
    "dtoSuffix": "DTO",
    "jhipsterVersion": "6.10.1",
    "creationTimestamp": 1594958880223,
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "otherModules": [],
    "blueprints": []
  },
  "entities": [
    "VendorAccountManager",
    "VendorTerritory",
    "VendorTerritoryState",
    "Vendor",
    "VendorStatusHistory",
    "VendorInsurance",
    "InsuranceCertificate",
    "InsuranceCoverage",
    "VendorContact",
    "VendorContactInformation",
    "VendorServiceArea",
    "ServiceAreaStatusHistory",
    "RegionalTaxRate",
    "VendorTaxRate",
    "VendorProduct",
    "VendorProductRate",
    "VendorFee",
    "VendorFeeRate",
    "VendorTaxInformation",
    "TimeZone",
    "VendorAddress",
    "AvailabilityStatusHistory"
  ]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity VendorProductRate {
  rateAmount Integer required,
  unitOptionId String required,
  effectiveDate Instant,
  isCanceled Boolean,
  cancelationDate Instant,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorFeeRate {
  rateAmount Integer required,
  includedUnits Integer required,
  unitOptionId String required,
  effectiveDate Instant,
  isCanceled Boolean,
  cancelationDate Instant,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorProduct {
  isActive Boolean,
  priority VendorPriorityType,
  product VendorProductType,
  productGroup VendorProductGroupType,
  vehicle VendorVehicleType,
  grossVehicleWeight VendorGrossVehicleWeight,
  serviceOptionId String required,
  basicProductId String required,
  maxPassengerCount Integer,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorFee {
  isActive Boolean,
  feeOptionId String required,
  basicProductId String required,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorServiceArea {
  status VendorServiceAreaStatus required,
  zipcode String required,
  crowFlyMiles Integer,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity ServiceAreaStatusHistory {
  sequenceNumber Integer required,
  dateTime Instant required,
  status VendorServiceAreaStatus required,
  createdBy String
}
entity RegionalTaxRate {
  sequenceNumber Integer required,
  taxRateType VendorTaxRateType required,
  isActive Boolean,
  taxRate Integer max(100),
  city String,
  stateProvidence String,
  zipcode String,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorTaxInformation {
  isActive Boolean,
  taxIdentityNumber String unique required pattern(/^(\d{2})-(\d{7})$/),
  taxClass VendorTaxClassType required,
  purchaseDate LocalDate required,
  legalBusinessName String required,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorTaxRate {
  sequenceNumber Integer required,
  isActive Boolean,
  taxRateType VendorTaxRateType required,
  taxRate Integer max(100),
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorAccountManager {
  isActive Boolean,
  userId String required,
  emailAddress String required,
  firstName String required,
  lastName String,
  officePhoneNumber String,
  mobilePhoneNumber String,
  extension String,
  faxNumber String,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity AvailabilityStatusHistory {
  status VendorDriverAvailability,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorContact {
  sequenceNumber Integer required,
  isActive Boolean,
  contactType VendorContactType required,
  availabilityStatus VendorDriverAvailability,
  firstName String required,
  lastName String,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorAddress {
  streetAddress String required,
  suiteNumber String,
  city String required,
  stateProvidence String required,
  zipcode String required,
  latitude String,
  longitude String,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorContactInformation {
  contactMethod VendorContactMethodType required,
  preferred Boolean,
  emailAddress String,
  businessPhoneNumber String,
  extension String,
  mobilePhoneNumber String,
  homePhoneNumber String,
  faxNumber String,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorStatusHistory {
  sequenceNumber Integer required,
  dateTime Instant required,
  status VendorStatus required,
  createdBy String
}
entity VendorTerritory {
  isActive Boolean,
  name String required unique,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorTerritoryState {
  stateProvidence String required,
  abbreviation String required,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity TimeZone {
  name String required unique,
  abbreviation String required,
  timeZoneOffset Integer required,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity Vendor {
  name String required,
  vendorNumber String unique,
  phoneNumber String,
  websiteURL String maxlength(100),
  logo ImageBlob,
  vendorBankAccountId String,
  hasNegotiatedPricing Boolean,
  chargeSaleTax Boolean,
  paymentMethod VendorPaymentType required,
  substanceAbusePolicy Boolean,
  backgroundChecks Boolean,
  status VendorStatus required,
  autoSubmitBills Boolean,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity VendorInsurance {
  agencyName String required,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity InsuranceCertificate {
  certificateImage ImageBlob,
  policyNumber String required,
  effectiveDate LocalDate required,
  expirationDate LocalDate required,
  cancelationDate LocalDate,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
entity InsuranceCoverage {
  coverageType VendorInsCoverageType required,
  coverageAmount Integer required,
  createdBy String,
  createdOn Instant,
  updatedBy String,
  updatedOn Instant
}
enum VendorPriorityType {
  EMERGENCY,
  NON_EMERGENCY
}
enum VendorProductType {
  TRANSPORT,
  NON_TRANSPORT
}
enum VendorProductGroupType {
  NON_SALVAGE,
  SALVAGE
}
enum VendorVehicleType {
  AUTOMOBILE,
  RECREATIONAL_VEHICLE,
  TRAILER,
  MOTORCYCLE,
  ALL_TERRAIN_VEHICLE,
  WATERCRAFT,
  AIRCRAFT
}
enum VendorGrossVehicleWeight {
  LESS_THAN_10000_LBS,
  BETWEEN_10001_AND_20000_LBS,
  BETWEEN_20001_AND_30000_LBS,
  MORE_THAN_30001_LBS
}
enum VendorServiceAreaStatus {
  DRAFT,
  SUBMITTED,
  PENDING,
  APPROVED,
  DENIED,
  ACTIVE,
  INACTIVE,
  SUSPENDED,
  VOIDED
}
enum VendorTaxRateType {
  CITY,
  COUNTY,
  STATE
}
enum VendorTaxClassType {
  INDIVIDUAL_SOLE_PROPRIETER,
  CORPORATION,
  PARTNERSHIP,
  LIMITED_LIABILITY_COMPANY
}
enum VendorDriverAvailability {
  AVAILABLE,
  UNAVAILABLE
}
enum VendorContactType {
  JOB_POSTING,
  BILLING,
  OWNER,
  MANAGER,
  DRIVER,
  INSURANCE_AGENT
}
enum VendorContactMethodType {
  EMAIL,
  MOBILE_PHONE,
  BUSINESS_PHONE,
  HOME_PHONE,
  FAX
}
enum VendorStatus {
  ACTIVE,
  INACTIVE,
  DEACTIVATED,
  SUSPENDED,
  DELETED,
  VOID
}
enum VendorPaymentType {
  EFT,
  CHECK,
  CREDIT_CARD
}
enum VendorInsCoverageType {
  GARAGE,
  ON_HOOK,
  WORKMAN_COMPENSATION,
  LIABILITY
}

relationship OneToOne {
  VendorTaxInformation{vendorAddress required} to VendorAddress,
  VendorTaxInformation{vendorContact} to VendorContact{vendorTaxInformation},
  VendorAccountManager{vendorTerritory(name)} to VendorTerritory,
  VendorAddress{vendorContact} to VendorContact,
  VendorInsurance{vendorContact required} to VendorContact,
  VendorInsurance{vendorAddress required} to VendorAddress
}
relationship OneToMany {
  Vendor{vendorProductRate} to VendorProductRate{vendor},
  VendorProduct{vendorProductRate} to VendorProductRate{vendorProduct required},
  Vendor{vendorFeeRate} to VendorFeeRate{vendor},
  VendorFee{vendorFeeRate} to VendorFeeRate{vendorFee required},
  Vendor{vendorProduct} to VendorProduct{vendor required},
  Vendor{vendorFee} to VendorFee{vendor required},
  Vendor{vendorServiceArea} to VendorServiceArea{vendor required},
  Vendor{serviceAreaStatusHistory} to ServiceAreaStatusHistory{vendor},
  VendorServiceArea{serviceAreaStatusHistory} to ServiceAreaStatusHistory{vendorServiceArea required},
  Vendor{vendorTaxInformation} to VendorTaxInformation{vendor required},
  Vendor{vendorTaxRate} to VendorTaxRate{vendor required},
  VendorContact{availabilityStatusHistory} to AvailabilityStatusHistory{vendorContact},
  Vendor{vendorContact} to VendorContact{vendor required},
  Vendor{vendorAddress} to VendorAddress{vendor required},
  Vendor{vendorContactInformation} to VendorContactInformation{vendor},
  VendorContact{vendorContactInformation} to VendorContactInformation{vendorContact required},
  Vendor{vendorStatusHistory} to VendorStatusHistory{vendor required},
  VendorAccountManager{vendorTerritoryState} to VendorTerritoryState{vendorAccountManager},
  VendorTerritory{vendorTerritoryState} to VendorTerritoryState{vendorTerritory(name) required},
  Vendor{vendorInsurance} to VendorInsurance{vendor required},
  VendorInsurance{insuranceCertificate} to InsuranceCertificate{insuranceAgency required},
  Vendor{insuraceCertificate} to InsuranceCertificate{vendor},
  InsuranceCertificate{insuranceCoverage} to InsuranceCoverage{insuranceCertificate required},
  Vendor{insuranceCoverage} to InsuranceCoverage{vendor}
}
relationship ManyToOne {
  VendorAddress{vendorTerritoryState(stateProvidence)} to VendorTerritoryState,
  Vendor{timeZone(name) required} to TimeZone,
  Vendor{vendorAccountManager} to VendorAccountManager
}

dto VendorProductRate, VendorFeeRate, VendorProduct, VendorFee, VendorServiceArea, ServiceAreaStatusHistory, RegionalTaxRate, VendorTaxInformation, VendorTaxRate, VendorAccountManager, AvailabilityStatusHistory, VendorContact, VendorAddress, VendorContactInformation, VendorStatusHistory, VendorTerritory, VendorTerritoryState, TimeZone, Vendor, VendorInsurance, InsuranceCertificate, InsuranceCoverage with mapstruct
paginate VendorProductRate, VendorFeeRate, VendorProduct, VendorFee, VendorServiceArea, ServiceAreaStatusHistory, RegionalTaxRate, VendorTaxInformation, VendorTaxRate, VendorAccountManager, AvailabilityStatusHistory, VendorContact, VendorAddress, VendorContactInformation, VendorStatusHistory, VendorTerritory, VendorTerritoryState, TimeZone, Vendor, VendorInsurance, InsuranceCertificate, InsuranceCoverage with pagination
service VendorProductRate, VendorFeeRate, VendorProduct, VendorFee, VendorServiceArea, ServiceAreaStatusHistory, RegionalTaxRate, VendorTaxInformation, VendorTaxRate, VendorAccountManager, AvailabilityStatusHistory, VendorContact, VendorAddress, VendorContactInformation, VendorStatusHistory, VendorTerritory, VendorTerritoryState, TimeZone, Vendor, VendorInsurance, InsuranceCertificate, InsuranceCoverage with serviceClass
microservice VendorProductRate, VendorFeeRate, VendorProduct, VendorFee, VendorServiceArea, ServiceAreaStatusHistory, RegionalTaxRate, VendorTaxInformation, VendorTaxRate, VendorAccountManager, AvailabilityStatusHistory, VendorContact, VendorAddress, VendorContactInformation, VendorStatusHistory, VendorTerritory, VendorTerritoryState, TimeZone, Vendor, VendorInsurance, InsuranceCertificate, InsuranceCoverage with vendor
filter VendorProductRate, VendorFeeRate, VendorProduct, VendorFee, VendorServiceArea, ServiceAreaStatusHistory, RegionalTaxRate, VendorTaxInformation, VendorTaxRate, VendorAccountManager, AvailabilityStatusHistory, VendorContact, VendorAddress, VendorContactInformation, VendorStatusHistory, VendorTerritory, VendorTerritoryState, TimeZone, Vendor, VendorInsurance, InsuranceCertificate, InsuranceCoverage

</pre>
</details>

##### **Environment and Tools**

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode)

git version 2.23.0

node: v14.5.0

npm: 6.14.6

yarn: 1.22.4

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6

identical .jhipster/AvailabilityStatusHistory.json
identical .jhipster/InsuranceCertificate.json
identical .jhipster/InsuranceCoverage.json
identical .jhipster/RegionalTaxRate.json
identical .jhipster/ServiceAreaStatusHistory.json
identical .jhipster/TimeZone.json
identical .jhipster/Vendor.json
identical .jhipster/VendorAccountManager.json
identical .jhipster/VendorAddress.json
identical .jhipster/VendorContact.json
identical .jhipster/VendorContactInformation.json
identical .jhipster/VendorFee.json
identical .jhipster/VendorFeeRate.json
identical .jhipster/VendorInsurance.json
identical .jhipster/VendorProduct.json
identical .jhipster/VendorProductRate.json
identical .jhipster/VendorServiceArea.json
identical .jhipster/VendorStatusHistory.json
identical .jhipster/VendorTaxInformation.json
identical .jhipster/VendorTaxRate.json
identical .jhipster/VendorTerritory.json
identical .jhipster/VendorTerritoryState.json
INFO! Congratulations, JHipster execution is complete!

  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
             applicationType uaa,
             baseName uaa,
             packageName com.jhipster.demo.uaa,
             serverPort 9999,
             serviceDiscoveryType eureka,
             authenticationType uaa,
             uaaBaseName "uaa",
             cacheProvider hazelcast,
             enableHibernateCache true,
             jwtSecretKey 
             websocket false,
             databaseType sql,
             messageBroker kafka,
            devDatabaseType postgresql,
            prodDatabaseType postgresql,
             enableSwaggerCodegen true,
             buildTool gradle,
             useSass true,
             clientPackageManager yarn,
             testFrameworks [
               gatling,
               cucumber
             ],
             enableTranslation true,
             nativeLanguage en,
             languages [
               fr,
               es,
               en
             ],
             jhiPrefix jhi,
             dtoSuffix DTO,
             skipClient true,
             skipUserManagement false
         }
}

application {
  config {
        applicationType gateway,
        baseName apigateway,
        packageName com.jhipster.demo.apigateway,
        serverPort 8080,
        serviceDiscoveryType eureka,
        authenticationType uaa,
        uaaBaseName "uaa",
        cacheProvider ehcache,
        enableHibernateCache true,
        websocket spring-websocket,
        databaseType sql,
        devDatabaseType postgresql,
        prodDatabaseType postgresql,
        enableSwaggerCodegen true,
        buildTool gradle,
        useSass true,
        messageBroker kafka,
        clientPackageManager yarn,
        testFrameworks [
          gatling,
          cucumber,
          protractor
        ],
        enableTranslation true,
        nativeLanguage en,
        languages [
          fr,
          es,
          en
        ],
        clientFramework angularX,
        jhiPrefix jhi,
        dtoSuffix DTO
        }
      entities *
}

application {
  config {
             applicationType microservice,
             baseName vendor,
             packageName com.jhipster.demo.vendor,
             serverPort 8083,
             serviceDiscoveryType eureka,
             authenticationType uaa,
             uaaBaseName "uaa",
             cacheProvider hazelcast,
             enableHibernateCache true,
             websocket false,
             databaseType sql,
             messageBroker kafka,
             devDatabaseType postgresql,
             prodDatabaseType postgresql,
             enableSwaggerCodegen true,
             buildTool gradle,
             useSass true,
             clientPackageManager yarn,
             testFrameworks [
               gatling,
               cucumber
             ],
             enableTranslation true,
             nativeLanguage en,
             languages [
               fr,
               es,
               en
             ],
             jhiPrefix jhi,
             dtoSuffix DTO,
             skipClient true,
             skipUserManagement true
         }
  entities VendorAccountManager, VendorTerritory, VendorTerritoryState, Vendor,
           VendorStatusHistory, VendorInsurance, InsuranceCertificate, InsuranceCoverage,
           VendorContact, VendorContactInformation, VendorServiceArea, ServiceAreaStatusHistory,
           RegionalTaxRate, VendorTaxRate, VendorProduct, VendorProductRate, VendorFee,
           VendorFeeRate, VendorTaxInformation, TimeZone, VendorAddress, AvailabilityStatusHistory
}

relationship OneToOne {
	VendorInsurance{vendorContact required} to VendorContact,
    VendorInsurance{vendorAddress required} to VendorAddress,
    VendorAddress{vendorContact} to VendorContact,
    VendorTaxInformation{vendorAddress required} to VendorAddress,
	VendorAccountManager{vendorTerritory (name)} to VendorTerritory,
    VendorTaxInformation{vendorContact} to VendorContact{vendorTaxInformation}
}

relationship OneToMany {
	Vendor{vendorContactInformation} to VendorContactInformation{vendor},
    Vendor{vendorFeeRate} to VendorFeeRate{vendor},
    Vendor{serviceAreaStatusHistory} to ServiceAreaStatusHistory{vendor},
	VendorAccountManager{vendorTerritoryState} to VendorTerritoryState{vendorAccountManager},
	Vendor{vendorProductRate} to VendorProductRate{vendor},
	Vendor{vendorAddress} to VendorAddress{vendor required},
	VendorProduct{vendorProductRate} to VendorProductRate{vendorProduct required},
    VendorFee{vendorFeeRate} to VendorFeeRate{vendorFee required},
    Vendor{vendorTaxRate} to VendorTaxRate{vendor required},
    Vendor{vendorTaxInformation} to VendorTaxInformation{vendor required},
	VendorTerritory{vendorTerritoryState} to VendorTerritoryState{vendorTerritory(name) required},
	Vendor{vendorInsurance} to VendorInsurance{vendor required},
	VendorInsurance{insuranceCertificate} to InsuranceCertificate{insuranceAgency required},
	InsuranceCertificate{insuranceCoverage} to InsuranceCoverage{insuranceCertificate required},
    Vendor{insuraceCertificate} to InsuranceCertificate{vendor},
    Vendor{VendorStatusHistory} to VendorStatusHistory{vendor required},
    Vendor{vendorServiceArea} to VendorServiceArea{vendor required},
	VendorContact{vendorContactInformation} to VendorContactInformation{vendorContact required},
    Vendor{vendorContact} to VendorContact{vendor required}
    VendorServiceArea{serviceAreaStatusHistory} to ServiceAreaStatusHistory{vendorServiceArea required}
	Vendor{vendorProduct} to VendorProduct{vendor required},
    Vendor{vendorFee} to VendorFee{vendor required},
	VendorContact{availabilityStatusHistory} to AvailabilityStatusHistory{vendorContact},
    Vendor{insuranceCoverage} to InsuranceCoverage{vendor}
}

relationship ManyToOne {
	VendorAddress{vendorTerritoryState(stateProvidence)} to VendorTerritoryState,
	Vendor{timeZone(name) required} to TimeZone,
    Vendor{vendorAccountManager} to VendorAccountManager
}

entity VendorProductRate {
    rateAmount Integer required,
    unitOptionId String required,
    effectiveDate Instant,
    isCanceled Boolean,
    cancelationDate Instant,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity VendorFeeRate {
    rateAmount Integer required,
    includedUnits Integer required,
    unitOptionId String required,
    effectiveDate Instant,
    isCanceled Boolean,
    cancelationDate Instant,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity VendorProduct {
	isActive Boolean,
    priority VendorPriorityType,
    product VendorProductType,
    productGroup VendorProductGroupType,
    vehicle VendorVehicleType,
    grossVehicleWeight VendorGrossVehicleWeight,
    serviceOptionId String required,
    basicProductId String required,
    maxPassengerCount Integer,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

enum VendorVehicleType {
	AUTOMOBILE,
    RECREATIONAL_VEHICLE,
    TRAILER,
    MOTORCYCLE,
    ALL_TERRAIN_VEHICLE,
    WATERCRAFT,
    AIRCRAFT
}

enum VendorGrossVehicleWeight {
	LESS_THAN_10000_LBS,
    BETWEEN_10001_AND_20000_LBS,
    BETWEEN_20001_AND_30000_LBS,
    MORE_THAN_30001_LBS
}

enum VendorProductType {
	TRANSPORT,
    NON_TRANSPORT
}

enum VendorProductGroupType {
	NON_SALVAGE,
    SALVAGE
}

enum VendorPriorityType {
	EMERGENCY,
    NON_EMERGENCY
}

entity VendorFee {
	isActive Boolean,
    feeOptionId String required,
    basicProductId String required,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity VendorServiceArea {
    status VendorServiceAreaStatus required,
    zipcode String required,
    crowFlyMiles Integer,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity ServiceAreaStatusHistory {
	sequenceNumber Integer required,
    dateTime Instant required,
    status VendorServiceAreaStatus required,
    createdBy String
}

enum VendorServiceAreaStatus {
	DRAFT,
    SUBMITTED,
    PENDING,
    APPROVED,
    DENIED,
	ACTIVE,
    INACTIVE,
    SUSPENDED,
    VOIDED
}

enum VendorTaxRateType {
	CITY,
    COUNTY,
    STATE
}

enum VendorTaxClassType {
	INDIVIDUAL_SOLE_PROPRIETER,
	CORPORATION,
    PARTNERSHIP,
    LIMITED_LIABILITY_COMPANY
}

entity RegionalTaxRate {
	sequenceNumber Integer required,
    taxRateType VendorTaxRateType required,
    isActive Boolean,
    taxRate Integer max (100),
    city String,
    stateProvidence String,
    zipcode String,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity VendorTaxInformation {
    isActive Boolean,
    taxIdentityNumber String unique required pattern(/^(\d{2})-(\d{7})$/),
    taxClass VendorTaxClassType required,
    purchaseDate LocalDate required,
    legalBusinessName String required,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity VendorTaxRate {
	sequenceNumber Integer required,
    isActive Boolean,
    taxRateType VendorTaxRateType required,
    taxRate Integer max(100),
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity VendorAccountManager {
	isActive Boolean,
    userId String required,
	emailAddress String required,
	firstName String required,
	lastName String,
    officePhoneNumber String,
    mobilePhoneNumber String,
    extension String,
    faxNumber String,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity AvailabilityStatusHistory {
    status VendorDriverAvailability
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

enum VendorDriverAvailability {
	AVAILABLE,
    UNAVAILABLE
}

entity VendorContact {
	sequenceNumber Integer required,
    isActive Boolean,
    contactType VendorContactType required,
	availabilityStatus VendorDriverAvailability,
	firstName String required,
	lastName String,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity VendorAddress {
    streetAddress String required,
    suiteNumber String,
    city String required,
    stateProvidence String required,
    zipcode String required,
    latitude String,
    longitude String,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity VendorContactInformation {
    contactMethod VendorContactMethodType required,
    preferred Boolean,
    emailAddress String,
    businessPhoneNumber String,
    extension String,
    mobilePhoneNumber String,
    homePhoneNumber String,
    faxNumber String,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

enum VendorContactMethodType {
	EMAIL,
    MOBILE_PHONE,
    BUSINESS_PHONE,
    HOME_PHONE,
    FAX
}

enum VendorContactType {
	JOB_POSTING,
    BILLING,
    OWNER,
    MANAGER,
    DRIVER,
    INSURANCE_AGENT
}

entity VendorStatusHistory {
	sequenceNumber Integer required,
    dateTime Instant required,
    status VendorStatus required,
    createdBy String
}

enum VendorStatus {
	ACTIVE,
    INACTIVE,
    DEACTIVATED,
    SUSPENDED,
    DELETED,
    VOID
}

enum VendorInsCoverageType {
	GARAGE,
    ON_HOOK,
    WORKMAN_COMPENSATION,
    LIABILITY
}

entity VendorTerritory {
	isActive Boolean,
	name String required unique,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity VendorTerritoryState {
	stateProvidence String required,
    abbreviation String required,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

enum VendorPaymentType {
	EFT,
    CHECK,
    CREDIT_CARD
}

entity TimeZone {
    name String required unique,
    abbreviation String required,
    timeZoneOffset Integer required,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity Vendor {
    name String required,
    vendorNumber String unique,
    phoneNumber String,
    websiteURL String maxlength(100),
    logo ImageBlob,
    vendorBankAccountId String,
    hasNegotiatedPricing Boolean,
    chargeSaleTax Boolean,
    paymentMethod VendorPaymentType required,
    substanceAbusePolicy Boolean,
    backgroundChecks Boolean,
    status VendorStatus required,
    autoSubmitBills Boolean,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity VendorInsurance {
    agencyName String required,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity InsuranceCertificate {
	certificateImage ImageBlob,
    policyNumber String required,
    effectiveDate LocalDate required,
    expirationDate LocalDate required,
    cancelationDate LocalDate,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

entity InsuranceCoverage {
    coverageType VendorInsCoverageType required,
    coverageAmount Integer required,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

paginate VendorAccountManager, VendorTerritory, VendorTerritoryState, Vendor,
VendorStatusHistory, VendorInsurance, InsuranceCertificate, InsuranceCoverage,
VendorContact, VendorContactInformation, VendorServiceArea, ServiceAreaStatusHistory,
RegionalTaxRate, VendorTaxRate, VendorProduct, VendorProductRate, VendorFee,
VendorFeeRate, VendorTaxInformation, TimeZone, VendorAddress, AvailabilityStatusHistory with pagination
service VendorAccountManager, VendorTerritory, VendorTerritoryState, Vendor,
VendorStatusHistory, VendorInsurance, InsuranceCertificate, InsuranceCoverage,
VendorContact, VendorContactInformation, VendorServiceArea, ServiceAreaStatusHistory,
RegionalTaxRate, VendorTaxRate, VendorProduct, VendorProductRate, VendorFee,
VendorFeeRate, VendorTaxInformation, TimeZone, VendorAddress, AvailabilityStatusHistory with serviceClass
dto VendorAccountManager, VendorTerritory, VendorTerritoryState, Vendor,
VendorStatusHistory, VendorInsurance, InsuranceCertificate, InsuranceCoverage,
VendorContact, VendorContactInformation, VendorServiceArea, ServiceAreaStatusHistory,
RegionalTaxRate, VendorTaxRate, VendorProduct, VendorProductRate, VendorFee,
VendorFeeRate, VendorTaxInformation, TimeZone, VendorAddress, AvailabilityStatusHistory with mapstruct
filter VendorAccountManager, VendorTerritory, VendorTerritoryState, Vendor,
VendorStatusHistory, VendorInsurance, InsuranceCertificate, InsuranceCoverage,
VendorContact, VendorContactInformation, VendorServiceArea, ServiceAreaStatusHistory,
RegionalTaxRate, VendorTaxRate, VendorProduct, VendorProductRate, VendorFee,
VendorFeeRate, VendorTaxInformation, TimeZone, VendorAddress, AvailabilityStatusHistory
microservice VendorAccountManager, VendorTerritory, VendorTerritoryState, Vendor,
VendorStatusHistory, VendorInsurance, InsuranceCertificate, InsuranceCoverage,
VendorContact, VendorContactInformation, VendorServiceArea, ServiceAreaStatusHistory,
RegionalTaxRate, VendorTaxRate, VendorProduct, VendorProductRate, VendorFee,
VendorFeeRate, VendorTaxInformation, TimeZone, VendorAddress, AvailabilityStatusHistory with vendor

  </pre>
  </details>

##### **Browsers and Operating System**

MacOS Catalina 10.15.5

-   [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Closing because v6.10.1. Please reopen if you experience this issue with v7.6.0.
