### ISSUE TITLE
Prettier Java by default

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12109]
##### **Overview of the feature request**

In v6.10.1, we have the flag `--prettier-java`
For v7, we should put `prettier-java` by default, in all generated projects.

We should discuss about the flag `--no-prettier-java` but I'm not in favor for keeping this, as we don't have it for our frontend.

cc @clementdessoude @Shaolans @murdos 

##### **Motivation for or Use Case**

I use prettier-java for my customers, since months, and it works so well.
It should absolutely be by default in all generated projects.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues?q=prettier

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@mshima : as it's related to `prettier`, I can mention it here. But I'm not sure it's related to prettier-java, maybe related to yeoman phase. I'm a little lost for this minor issue.
When I generate a Vue application, at the end of generation, there are some files which are not commited by git:

```
Application successfully committed to Git from /home/pgrimaud/tmp/12-vue.

If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Server application generated successfully.

Run your Spring Boot application:
./mvnw

Client application generated successfully.

Start your Webpack development server with:
 npm start


> jhipster@0.0.0 cleanup /home/pgrimaud/tmp/12-vue
> rimraf target/classes/static/

INFO! Congratulations, JHipster execution is complete!

17:46:28 in ~/tmp/12-vue on  master [!+] took 1m 30s 
➜ git status   
Sur la branche master
Modifications qui seront validées :
  (utilisez "git restore --staged <fichier>..." pour désindexer)
	modifié :         .lintstagedrc.js
	modifié :         .postcssrc.js
	modifié :         src/test/javascript/jest.conf.js
	modifié :         webpack/loader.conf.js
	modifié :         webpack/utils.js
	modifié :         webpack/vue.utils.js
	modifié :         webpack/webpack.common.js
	modifié :         webpack/webpack.dev.js
	modifié :         webpack/webpack.prod.js

Modifications qui ne seront pas validées :
  (utilisez "git add <fichier>..." pour mettre à jour ce qui sera validé)
  (utilisez "git restore <fichier>..." pour annuler les modifications dans le répertoire de travail)
	modifié :         .lintstagedrc.js
	modifié :         .postcssrc.js
	modifié :         src/test/javascript/jest.conf.js
	modifié :         webpack/loader.conf.js
	modifié :         webpack/utils.js
	modifié :         webpack/vue.utils.js
	modifié :         webpack/webpack.common.js
	modifié :         webpack/webpack.dev.js
	modifié :         webpack/webpack.prod.js


17:46:32 in ~/tmp/12-vue on  master [!+]
```

Here an extract of git diff, which is related to prettier:

```diff
diff --git a/.lintstagedrc.js b/.lintstagedrc.js
index c689969..34f98cf 100644
--- a/.lintstagedrc.js
+++ b/.lintstagedrc.js
@@ -1,3 +1,3 @@
 module.exports = {
-  '{,src/**/}*.{json,md,yml,java,ts,css,scss}': ['prettier --write', 'git add']
+  '{,src/**/}*.{json,md,yml,java,ts,css,scss}': ['prettier --write', 'git add'],
 };
diff --git a/.postcssrc.js b/.postcssrc.js
index c3a587f..39ebf31 100644
--- a/.postcssrc.js
+++ b/.postcssrc.js
@@ -5,6 +5,6 @@ module.exports = {
     'postcss-import': {},
     'postcss-url': {},
     // to edit target browsers: use "browserslist" field in package.json
-    autoprefixer: {}
-  }
+    autoprefixer: {},
+  },
 };
```

But when I `git add`, everything disappears :
```
17:47:25 in ~/tmp/12-vue on  master [!+] 
➜ git add .            

17:47:28 in ~/tmp/12-vue on  master 
➜ git status
Sur la branche master
rien à valider, la copie de travail est propre
```

**Comment by mshima** [comment]
> @mshima : as it's related to `prettier`, I can mention it here. But I'm not sure it's related to prettier-java, maybe related to yeoman phase. I'm a little lost for this minor issue.
> When I generate a Vue application, at the end of generation, there are some files which are not commited by git:

@pascalgrimaud looks like a prettier conflict of the generated prettier config/version with main generator one.
I will try to reproduce this error.

**Comment by murdos** [comment]
@pascalgrimaud I agree with you, I would remove the flag to disable prettier-java too

**Comment by clementdessoude** [comment]
Thanks @mshima !
