### ISSUE TITLE
Debugging REST Controllers

### ISSUE THREAD

**Issue by nezuvian** [jhipster/generator-jhipster#1210]
Hi!

Currently debugging the REST Controllers is quite a challenge, first for a "debug mode" the CSRF protection should be disabled, authentication should be somehow managed (e.g you want to debug the permissions directly). So it's not a trivial thing to do right now. As @jdubois [mentioned](https://twitter.com/java_hipster/status/573114930813136896) maybe a profile can be used for debugging purposes, as I do not have much experience with Spring profiles maybe someone can lend a hand fixing this issue. Any help would be appreciated.

**Comment by pschmitz** [comment]
I found that an issue too.  No way to easily use CURL.
However, you can log in as admin/admin and run api commands direct from your browsers URL prompt....
maybe could use something like curl and wget together, that might be a stretch though.

**Comment by jdubois** [comment]
Yes, the best option is to use the Chrome dev tools, so you can run the requests from there.
Using CURL, security will always be an issue -> or you just remove security, but this will of course lead to other problems.
@nezuvian I didn't understand you wanted to use something like CURL: we can disable CSRF, but still the authentification will be an issue (you will have a smaller problem, but still it's going to be annoying).
You can have a look at what I did in the Gatling tests, as I'm doing exactly the same thing as you: as you will see, this can be automated, but it's a bit complex, and I don't think you can really do this with CURL

**Comment by nezuvian** [comment]
I think you misunderstood me. What I actually want to use is IntelliJ Idea's Rest Client tool with debugging, breakpoints, stack trace, etc. , but that's not the main issue here. The main issue is as you mentioned the authentication and csrf protection should be disabled to be able to access anything. So the main question is this possible somehow? I know you can disable both by hand but that's quite tedious to and not very safe. Would something like this be possible with a profile (-Pdebug) or is there some different way to do this easily?

**Comment by jdubois** [comment]
Yes I misunderstood you.
I've been playing with the Chrome Dev Tool: you can do "copy as cCurl" and it works perfectly well, I'm able to replay all requests in my console. I'll try with Intellij, I've never used this feature.
