### ISSUE TITLE
Neo4j: roles are lost when activating/deactivating user

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12139]
##### **Overview of the issue**

In http://localhost:8080/admin/user-management
When activating or deactivating an user, all roles are lost.

When updating an User -> same

##### **Motivation for or Use Case**

Detected by Vue daily builds, which have more e2e tests.

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/22-vue-neo4j
└── generator-jhipster@6.10.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "clientPackageManager": "npm",
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["gatling", "protractor"],
    "pages": [],
    "creationTimestamp": 1595060535913,
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "io.github.jhipster.sample",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "databaseType": "neo4j",
    "devDatabaseType": "neo4j",
    "prodDatabaseType": "neo4j",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "io/github/jhipster/sample",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": ["en"],
    "jhipsterVersion": "6.10.0"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Artist {
  name String required
}
entity Genre {
  name String required
}
entity Track {
  name String required
}
entity Album {
  name String required
}
relationship OneToOne {
  Album{artist(name)} to Artist,
  Album{genre(name)} to Genre
}
relationship OneToMany {
  Album{track} to Track{album(name)}
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

git version 2.27.0

node: v12.17.0

npm: 6.14.4

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.2, build a133471

identical .jhipster/Album.json
identical .jhipster/Artist.json
identical .jhipster/Genre.json
identical .jhipster/Track.json

**Comment by pascalgrimaud** [comment]
I'll need your help here @atomfrede :)

**Comment by atomfrede** [comment]
Let me check. I think it's a known issue with sdn/rx.

**Comment by pascalgrimaud** [comment]
Thanks @atomfrede 
I think it's related to these lines: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/service/UserService.java.ejs#L514-L515

**Comment by pascalgrimaud** [comment]
Maybe missing `neo4j` here: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/service/UserService.java.ejs#L520

I'm testing it

**Comment by pascalgrimaud** [comment]
sorry for disturbing you @atomfrede : it should be fixed. No need to know neo4j here to fix it =)

**Comment by atomfrede** [comment]
Awesome!
