### ISSUE TITLE
"DockerFile to Jib migration" force us to abandon non root user practice 

### ISSUE THREAD

**Issue by trixprod** [jhipster/generator-jhipster#12136]
Hello,

I'm little bit surprised when i have migrated some of my projects from DockerFile to the standard Jib docker image build process.

The DockerFile was supposed to create an "jhipster" user to prevent us to use root user ( A critical issue was discovered in 2019 and was related to usage of root user ).

I was not able to reproduce the old good behaviour with Jib by creating an user and i haven't found any recommendation or code about creating an user before entering entrypoint.sh.

So, i may miss the point. Is it a good practice to keep root user ? If not, what is the good way to handle this with jib ?

Thank you.
Regard

**Comment by atomfrede** [comment]
A good point. There is an option to set a container user (see https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#configuration). We should use that if possible.

**Comment by atomfrede** [comment]
This configuration works pretty well and set the user the first non root user:

```xml
  <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>${jib-maven-plugin.version}</version>
                    <configuration>
                        <from>
                            <image>adoptopenjdk:11-jre-hotspot</image>
                        </from>
                        <to>
                            <image>mhipsterredis:latest</image>
                        </to>
                        <container>
                            <entrypoint>
                                <shell>sh</shell>
                                <option>-c</option>
                                <arg>/entrypoint.sh</arg>
                            </entrypoint>
                            <ports>
                                <port>8080</port>
                            </ports>
                            <environment>
                                <SPRING_OUTPUT_ANSI_ENABLED>ALWAYS</SPRING_OUTPUT_ANSI_ENABLED>
                                <JHIPSTER_SLEEP>0</JHIPSTER_SLEEP>
                            </environment>
                            <creationTime>USE_CURRENT_TIMESTAMP</creationTime>
                            <user>1000</user>
                        </container>
                        <extraDirectories>
                            <paths>src/main/jib</paths>
                            <permissions>
                                <permission>
                                    <file>/entrypoint.sh</file>
                                    <mode>755</mode>
                                </permission>
                            </permissions>
                        </extraDirectories>
                    </configuration>
                </plugin>

**Comment by PierreBesson** [comment]
Having a non-root user is a desirable change. Possibly, at the time we migrated to jib, it did not support setting a non-root user which would explain why it is not currently in setup. @trixprod, would you consider submitting the above code as a PR for maven and gradle configurations?

**Comment by PierreBesson** [comment]
@trixprod, next time please follow our issue template. Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md).

**Comment by trixprod** [comment]
> ```
> 1000
> ```

Hello @atomfrede , i already tried this but the user 1000 has to exist to run correctly the container.
That's why the DockerFile create the user jhipster before.

If we add the adduser command before the entrypoint we have a permission denied error. ( i guess it try to adduser with user 1000 ).

**Comment by atomfrede** [comment]
At least for our openjdk image user 1000 exists as it based on Ubuntu. For other distributions that might not work, that's true.
