### ISSUE TITLE
Locale switching only if chosen from menu

### ISSUE THREAD

**Issue by danaki** [jhipster/generator-jhipster#1213]
I have Russian as the only language of my app. I don't have any language switching menu there. First inconvenience is that I have to edit language settings across several files like app.js and language.service.js. It would be great to have a config for that. Other thing is that because I don't have language switch, tmhDynamicLocale is not initialized and angulars' locale files not loaded. It would be more reliable to watch for $translate's current language and set locale accordingly:
```
    ...
    .run(...) {
        ...
        $rootScope.$watch(function() {
            return $translate.use();
        }, function(language) {
            tmhDynamicLocale.set(language);
        });
    }
```

However I'm not angular guru, this snippet just worked for me.
Jhipster 1.10.0

**Comment by jdubois** [comment]
If you have just one language, you could even remove all translations and write directly the text in your pages.
Yes you can "force" the language like you did, it's like emulating what the menu does, so it works the same in the end.

**Comment by danaki** [comment]
I don't want to break compatibility and I can decide to add a language in the future. So it's just correct to set default language to anything else than English. The setting of locale leads to correct time and currency helpers so my guess it must listen for the current locale setting, or contrary translate-provider must listen to the current locale (I'm not sure there is getter for this), or both of them must listen to the current global locale setting. Imagine for example there're no language menu and application can detect language from user agent preferences. Anyway that was just a proposal.
