### ISSUE TITLE
BUG: Undertow SSL can not work with Reactive app.

### ISSUE THREAD

**Issue by PC-Chiu** [jhipster/generator-jhipster#12138]
When I boot gateway(Reactive) with append profile `tls`, Undertow SSL can not work.

##### **Reproduce the error**

```
Description:

Parameter 0 of constructor in io.github.jhipster.security.ssl.UndertowSSLConfiguration required a bean of type 'org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory' in your configuration.
```

##### **Suggest a Fix**

Change 

```
@ConditionalOnClass({UndertowServletWebServerFactory.class, UndertowOptions.class})
io.github.jhipster.security.ssl.UndertowSSLConfiguration
```

to @ConditionalOnBean({UndertowServletWebServerFactory.class})

and add `UndertowSSLReactiveConfiguration`

```
@ConditionalOnBean({UndertowReactiveWebServerFactory.class})
io.github.jhipster.security.ssl.UndertowSSLReactiveConfiguration
```

##### **JHipster Version(s)**

6.10.1

##### **Browsers and Operating System**

Mac OS

**Comment by mraible** [comment]
Can you please create a PR to fix this issue? Thanks in advance!

If you need help, please let me know. I'd be happy to help. 🙂

**Comment by atomfrede** [comment]
I looked at it some time ago. It needs some extensions in the jhipster lib.

**Comment by mraible** [comment]
@atomfrede Added a bug bounty for motivation. 😊

**Comment by atomfrede** [comment]
:+1: I think I have the code in jhipster lib somewhere at home, but didn't test it yet with a generated application.

**Comment by atomfrede** [comment]
Indeed, I have found the code. Will try to test it today.

**Comment by atomfrede** [comment]
@mraible Now I remember my problem I discovered. Do we use undertow for reactive option at all? Aren't we using netty?

**Comment by mraible** [comment]
From https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web-reactive.html#webflux-server-choice:

> Spring WebFlux is supported on Tomcat, Jetty, Servlet 3.1+ containers, as well as on non-Servlet runtimes such as Netty and Undertow.

**Comment by atomfrede** [comment]
We are using netty with webflux instead of undertow as far as I can tell.
