### ISSUE TITLE
Local HTTP server requests hang after 'gulp serve'  

### ISSUE THREAD

**Issue by sometxdude** [jhipster/generator-jhipster#1214]
'gulp serve' executes succesfully, but if you attempt to access http://localhost:9000, the request just hangs.  I tested this on Mac, Windows, and Linux and it occurs on all 3.   JHipster version tested is 2.5.1

To reproduce:
(1/13) What is the base name of your application? jhipster
(2/13) What is your default Java package name? com.mycompany.myapp
(3/13) Do you want to use Java 8? Yes (use Java 8)
(4/13) Which *type* of authentication would you like to use? HTTP Session Authentication (stateful, default Spring Security mechanism)
(5/13) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL)
(6/13) Which *production* database would you like to use? PostgreSQL
(7/13) Which *development* database would you like to use? PostgreSQL
(8/13) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
(9/13) Do you want to use clustered HTTP sessions? No
(10/13) Do you want to use WebSockets? No
(11/13) Would you like to use Maven or Gradle for building the backend? Gradle
(12/13) Would you like to use Grunt or Gulp.js for building the frontend? Gulp.js
(13/13) Would you like to use the Compass CSS Authoring Framework(y/N) N

**Comment by jdubois** [comment]
Did you look at the URL in the log? For me it's port 3000, not 9000

**Comment by sometxdude** [comment]
For me, the console says '
Server started http://localhost:9000'.  It looks like the latest template
for gulpfile.js has it configured for 9000.  I can see it in
app/templates/gulpfile.js
<https://github.com/jhipster/generator-jhipster/blob/2cb225a410f04a2d5ec99756de292a6194f5098c/app/templates/gulpfile.js>

**Comment by sometxdude** [comment]
I managed to track down the proximate cause of this error.  If you don't select H2 as your dev database, then '/console/' is excluded from the proxyRoutes.  When this path is excluded, the local gulp server just hangs on any request.  I manually added '/console/' to the proxyRoutes and the problem goes away.

var proxyRoutes = [
            '/api',
            '/health',
            '/configprops',
            '/api-docs',
            '/metrics',
            '/dump',
            '/console/'   <-- this is missing if you don't use H2
        ];

**Comment by jdubois** [comment]
Oh sorry I didn't see you were using gulp.js! So yes you are correct! We had the same issue with grunt!

**Comment by jdubois** [comment]
In fact it's another issue, because of the trailing slash.
I'm pushing a quick fix.

**Comment by fclaeys** [comment]
Hello Julien,

In fact the trailing slash wasn't the cause of the issue.
In the gulpfile.js line 147, the 
```
var route in requireTrailingSlash 
```
set the index of the array (0,1,...) in route and not the value as excepted line 148.

I can push a PR with a correction.
