### ISSUE TITLE
Login regex needs refactoring

### ISSUE THREAD

**Issue by yuniel-acosta** [jhipster/generator-jhipster#12148]
##### **Overview of the issue**

Testing the login of the users note that according to the regex **^(?>[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*)|(?>[_.@A-Za-z0-9-]+)$** this would be a correct login "......." or "/ .......". It is even possible to insert in the database which could be a security vulnerability in addition to the fact that it is not correct that there is a user login '.......'

##### **Reproduce the error**
Create a new app and try to register a new user with the following login '......'
The test was done using the blueprint vuejs, but that does not affect the backend which also has this problem...

##### **Suggest a Fix**

The solution would be to create a new regular expression that allows you to enter a correct user. For this you can use the following web page that allows you to test the regular expressions.[regex test web site]( https://regex101.com/)

##### **JHipster Version(s)**
v6.10.1

**Comment by atomfrede** [comment]
Just to make sure, why to you think `......` should not be a valid login (besides it looks strange)?

**Comment by yuniel-acosta** [comment]
This is a correct login for a user (my criteria)

Only contains alphanumeric characters, underscore and dot.

Underscore and dot can't be at the end or start of a username (e.g **_username** / **username_** / **.username** / **username.**).

Underscore and dot can't be next to each other (e.g user_.name).

Underscore or dot can't be used multiple times in a row (e.g user__name / user..name).

Regex for this rules:
`^[a-zA-Z0-9]([._](?![._])|[a-zA-Z0-9]){4,18}[a-zA-Z0-9]$`
Note: here the minimum is 4 character and maximum 18, this restriction could be remove or change.

I know that JHIPSTER uses the same regular expression for both login (username) and email. I think that in the user registration, these regex should be different one for login and another for email. In the authentication view if it can be used a same regex that you check if it is email or username.

**Comment by atomfrede** [comment]
In fact we plan to use emails as login with v7 if I am not mistaken. Your regex won't match e.g. `admin` when testing it, are you sure thats what you would like to have?

**Comment by yuniel-acosta** [comment]
@atomfrede You're right, fix the regular expression [regex](https://www.regextester.com/index.php?fam=117639) . Do you tell me that in version 7 of jhipster it is only allowed to authenticate using email ?. I would like both authentication options to be considered.
![username](https://user-images.githubusercontent.com/33158051/88561004-d88c4100-cffc-11ea-9653-ef750bd9df0d.png)

**Comment by atomfrede** [comment]
At least that one option that has been discussed. Eventually you can change it by adapting the regex in the generated code to your needs.

**Comment by mraible** [comment]
@atomfrede Can we close this issue?

**Comment by yuniel-acosta** [comment]
Yes
