### ISSUE TITLE
Gradle Grunt build issue in windows

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1215]
The Grunt build task generated in the gradle build file should have the  ``` 'cmd', '/c' ```  param in the commandline for windows. without this it is failing in windows

```
task gruntBuild(type: Exec) {
    commandLine 'cmd', '/c', 'grunt', '--force', 'build'

}
task gruntTest(type: Exec) {
    commandLine 'cmd', '/c','grunt', 'test'
}
```

**Comment by atomfrede** [comment]
Already fixed by #1206
