### ISSUE TITLE
npm install failed if using authenticationType: session

### ISSUE THREAD

**Issue by oopsaleem** [jhipster/generator-jhipster#12151]
##### **Overview of the issue**
`npm install` failed for a new monolithic project created with default configs but changing `authenticationType: session`

##### **Reproduce the error**
`jhipster import-jdl sampleApp.jdl`
[sampleApp.jdl.txt](https://github.com/jhipster/generator-jhipster/files/4977581/sampleApp.jdl.txt)

![Annotation 2020-07-26 152812](https://user-images.githubusercontent.com/3925543/88478936-b4752500-cf54-11ea-9932-930f78c8f77b.png)

**Comment by atomfrede** [comment]
Can you delete your `package-lock.json`? This is most likely an issue with npm and not jhipster.

**Comment by oopsaleem** [comment]
> Can you delete your `package-lock.json`? This is most likely an issue with npm and not jhipster. And it would be great if you fill our issue template so we know the concrete version(s) you are using,

Hi @atomfrede  `package-lock.json` doesn't exist yet. 

##### **JHipster Version(s)**
 JHipster v6.10.1

##### **JHipster configuration**
>jhipster info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
sample-app@0.0.1-SNAPSHOT C:\temp\sampleApp
`-- (empty)

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "baseName": "sampleApp",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "blueprints": [],
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "creationTimestamp": 1595767800633,
    "dtoSuffix": "DTO",
    "embeddableLaunchScript": false,
    "jhipsterVersion": "6.10.1",
    "otherModules": [],
    "packageName": "com.samplecompany",
    "packageFolder": "com/samplecompany",
    "skipServer": false,
    "useSass": true,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "entitySuffix": ""
  },
  "entities": []
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

git version 2.23.0.windows.1

node: v12.18.2

npm: 6.14.6

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
N/A
##### **Browsers and Operating System**
Microsoft Windows [Version 10.0.17763.1294]
64 bit.

**Comment by oopsaleem** [comment]
npm clean

**Comment by oopsaleem** [comment]
Issue resolved by:

npm uninstall -g generator-jhipster
npm cache clean
npm install -g generator-jhipster
