### ISSUE TITLE
Add JHipster Control Center Docker Compose documentation in JHipster website

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#12163]
##### **Overview of the feature request**
JHipster Control Center Docker Compose file is generated according to the options chosen by the user. For some reasons we could personalize the yaml. We need to add a dedicated page to JHipster website.

##### **Motivation for or Use Case**
Move documentation from yaml Docker Compose to a dedicated JHipster website.

##### **Related issues or PR**
https://github.com/jhipster/generator-jhipster/pull/12126

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Any updates @avdev4j?

**Comment by avdev4j** [comment]
Need to be done :D

**Comment by pascalgrimaud** [comment]
@avdev4j @PierreBesson @nassimerrahoui @adilabed :
we need to find a stream lead for JHipster Control Center too, otherwise, it will become an unused / dead project...
