### ISSUE TITLE
Implement incremental liquibase.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12178]
##### **Overview of the feature request**

Implement linear liquibase changelog.
- Every time some entity is added or removed, create a new changelog.
- Don't touch old changelogs.
- Don't recreate master.xml.
- Append new entries to master.xml.
- New master.xml's entries must be linear.
- Constraints depends on the table existence.

Tasks:
- [x] 1. stop passing fork function to import-jdl. (https://github.com/jhipster/generator-jhipster/pull/12137)
- [x] 2. add a option to jdl to stop saving config files. (https://github.com/jhipster/jhipster-core/pull/442, https://github.com/jhipster/jhipster-core/pull/450)
- [x] 3. change jdl to return a complete application structure. (https://github.com/jhipster/generator-jhipster/pull/12191)
- [x] 4. change import-jdl to save the config to keep fork compatibility. (https://github.com/jhipster/generator-jhipster/pull/12193)
- [ ] 5. stop calling environment using fork for 1 application and pass the application structure as option instead of saving.
- [x] 6. make entities generator more friendly to composing. (https://github.com/jhipster/generator-jhipster/pull/12176)
- [ ] 7. implement incremental-changelog and inclemental-changelog-liquibase.
- [x] 8. Allow app/entities configs to passed at options instead of saving. (https://github.com/jhipster/generator-jhipster/pull/12197)
- [x] 9. Don't touch master.xml and initial.xml.

Support for multiples applications (not planned):
- [ ] ~stop calling environment using fork for multiples applications.~ (Postponed due to fork/cwd requirement).

##### **Motivation for or Use Case**

Make easier to developers to deal with liquibase.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/11398
https://github.com/mshima/generator-jhipster-liquibase/

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/36634

**Comment by pascalgrimaud** [comment]
@mshima : approved
