### ISSUE TITLE
aws-containers sub-generator wrong regEx

### ISSUE THREAD

**Issue by deekovski** [jhipster/generator-jhipster#12196]
If i use the aws-containers sub-generator on an microservice architecture, there is this error:
` An error occurred (InvalidParameterException) when calling the CreateRepository operation: Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''`

It seems to be a bug in the regEx (the \ is not escaped if i run a regEx-Tester).
I'm not sure if its an actual bug in the generator or the aws / eksctl-cli.

jhipster version: v6.10.1
AWS-cli version: 2.0.36
eksctl version: 0.25.0

**Comment by SudharakaP** [comment]
@deekovski : Could you share your `.yo-rc.json` file or let us know what the `baseName` of the application is? This seems to be coming when the application name contains capitalized letters (as evidenced here; https://github.com/jenkins-x/jx/issues/1344). The regex error is coming from the aws library; so there's not much we could do; but I think we should lowercase before passing the value there. 😄

**Comment by pascalgrimaud** [comment]
closing this as no additional information
