### ISSUE TITLE
Pagination should be a directive

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1219]
As discussed in #1208 the pagination code should be in a directive

**Comment by deepu105** [comment]
+1
have considered angular-ui bootstrap?

**Comment by 8cells** [comment]
:+1:  angular-ui bootstrap

**Comment by gzsombor** [comment]
:+1: for adding angular-ui-bootstrap as a default - with that even modal dialogs are much nicer.

**Comment by dejewi** [comment]
:+1: angular-ui bootstrap

**Comment by jdubois** [comment]
No I will not add angular-ui, because that would brings lots of extra libraries, and the idea is that we keep minimal on the amount of things on top of Angular.
You can still add angular-ui easily using Bower, the idea is that:

- you can easily use angular-ui if you want to
- but we don't force people to use it, if they don't want to

This might change in the future, but as we should some time have a look at Angular JS 2.0, that also means that the less 3rd party libs we have, the better.
