### ISSUE TITLE
Add Support for EclipseLink as JPA provider

### ISSUE THREAD

**Issue by xurror** [jhipster/generator-jhipster#12200]
##### **Overview of the feature request**

JHipster uses hibernate as default JPA provider which has proven to be very effective, but eclipselink has made huge improvements over the years with few tradeoffs between the the 2. Also EclipseLink happens to be the reference implementation for JPA 2.0

##### **Motivation for or Use Case**

EclipseLink is the reference JPA implementation.
It is also a very suitable alternative to hibernate.

##### **Related issues or PR**

No

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
I don't think we can handle/support a second JPA provider. This might be a good thing to put into a blueprint/module imho.

**Comment by mraible** [comment]
I believe Apache Roller supports EclipseLink and Hibernate and it's not too difficult to switch between them. It's possible you only need to change a few files to do this.

**Comment by xurror** [comment]
> I believe Apache Roller supports EclipseLink and Hibernate and it's not too difficult to switch between them. It's possible you only need to change a few files to do this.
> […](#)
> On Aug 5, 2020, at 07:35, Frederik Hahne ***@***.***> wrote: ﻿ I don't think we can handle/support a second JPA provider. This might be a good thing to put into a blueprint/module imho. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I thought ASF has a license conflict with hibernate. We faced a similar problem with Apache Fineract where we had to switch the provider.

**Comment by xurror** [comment]
> I don't think we can handle/support a second JPA provider. This might be a good thing to put into a blueprint/module imho.

This sounds reasonable. I will try to propose a PR for this. Thanks.

**Comment by mraible** [comment]
> I thought ASF has a license conflict with hibernate. 

Yes, it does. That's why we ship Roller with Eclipse and tell people how to change to Hibernate.

**Comment by atomfrede** [comment]
> > I don't think we can handle/support a second JPA provider. This might be a good thing to put into a blueprint/module imho.
> 
> This sounds reasonable. I will try to propose a PR for this. Thanks.

Awesome! We try to support where possible, don't hesitate to reach put. I will close this issue here.
