### ISSUE TITLE
Unit tests fail with ClassNotFoundException when Postgres selected as dev database

### ISSUE THREAD

**Issue by sometxdude** [jhipster/generator-jhipster#1220]
If you select Postgres as the development database, the generated unit tests appear to be dependent on H2.  However, the H2 jar dependency is missing from the gradle build file, which results in a ClassNotFoundException.  This was tested using the most current master branch on 3/5/2015.

To reproduce:

1) Create a new project by selecting Postgres as the dev database, and Gradle for the build
2)  Run 'gradle build'.   Build fails with unit test errors.

**Comment by atomfrede** [comment]
When selecting Postgres as dev database H2 is not supposed to be on the classpath. Can you check if there is the same problem when using maven?

**Comment by jdubois** [comment]
It's working with Maven -> @atomfrede can you test on your side?
