### ISSUE TITLE
Failing cassandra-related builds

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#12216]
##### **Overview of the issue**

Some cassandra-related builds fail :(

##### **Motivation for or Use Case**

I want the CI not to throw anything I haven't done at me.

##### **Reproduce the error**

See: #12214 
Error:
```

The dependencies of some of the beans in the application context form a cycle:

   cassTestServiceClassEntityService defined in URL [jar:file:/home/runner/app/app.jar!/BOOT-INF/classes!/io/github/jhipster/sample/service/CassTestServiceClassEntityService.class]
      ↓
   cassTestServiceClassEntityRepository
      ↓
   org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration
┌─────┐
|  cassandraCluster defined in class path resource [org/springframework/boot/autoconfigure/cassandra/CassandraAutoConfiguration.class]
↑     ↓
|  cassandraConfiguration (field private com.datastax.driver.core.Cluster io.github.jhipster.sample.config.cassandra.CassandraConfiguration.cluster)
└─────┘
```

##### **Related issues**

None found

##### **JHipster Version(s)**

main branch

##### **JHipster configuration**

See [the failing build](https://github.com/jhipster/generator-jhipster/runs/957038305)
[here](https://github.com/jhipster/generator-jhipster/blob/master/test-integration/samples/react-maven-cassandra-session-redis/.yo-rc.json)

##### **Browsers and Operating System**

CI

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
It started failing sometime after https://github.com/jhipster/generator-jhipster/commit/571c66a6a6974e5380e91fd45af8e0527e3c9fa6.
It succeed when was merged, but I triggered a rebuild and failed.

Seem some dependency was updated.

**Comment by avdev4j** [comment]
Any update about this bug?

**Comment by mshima** [comment]
I looked at at generator-jhipster and jhipster-lib and I couldn’t find a commit that caused this bug.

**Comment by DanielFran** [comment]
Same, I try to identify in both projects which commit trigger those errors and did not found anything...

**Comment by MathieuAA** [comment]
I find it weird (but interesting) that we didn't cause this. Has any spring-boot-related dependency been updated lately?
