### ISSUE TITLE
mongo generate required unique fields with @Indexed(unique = true) instead of just @NotNull

### ISSUE THREAD

**Issue by gaetan224** [jhipster/generator-jhipster#12232]
##### **generate required unique fields with @Indexed(unique = true) **

as for version  6.5.1 the required unique fields are generated with only the @NotNull annotation meanwhile the mongodb use in this version (4.0.13) support @Indexed(unique = true) annotation which i think is more appropriate to match the required unique constraint

##### **the fiels are not unique**

the fields are not unique

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Please create a pull request to fix, and then re-open this issue.
