### ISSUE TITLE
Creating many-to-many relationship

### ISSUE THREAD

**Issue by Kahfimaulana** [jhipster/generator-jhipster#1223]
Hey,
I have some trouble when creating many-to-many relationship. 
I have created the following entity : 
1. student : id, studentName one-to-many studentCourse
2. course : id , courseName one-to-many studentCourses
3. studentCourse : studentId, courseId

When I create entity studentCourse and have relation many-to-one with both of table student and course, I got the following error : 

D:\WorkspaceJava\itm>yo jhipster:entity studentCourse
The entity studentCourse is being created.
Generating field #1
? Do you want to add a field to your entity? No

Generating relationships with other entities
? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? student
? What is the name of the relationship? studentId
? What is the type of the relationship? many-to-one
? When you display this relationship with AngularJS, which field from 'student' do you want to use? id

studentId - student (many-to-one)
Generating relationships with other entities
? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? course
? What is the name of the relationship? courseId
? What is the type of the relationship? many-to-one
? When you display this relationship with AngularJS, which field from 'course' do you want to use? id

studentId - student (many-to-one)
courseId - course (many-to-one)
Generating relationships with other entities
? Do you want to add a relationship to another entity? No

studentId - student (many-to-one)
courseId - course (many-to-one)
Everything is configured, generating the entity...
undefined:77
((__t = ( fields[fieldId].fieldName )) == null ? '' : __t) +
                         ^
TypeError: Cannot read property 'fieldName' of undefined
    at eval (eval at template (C:\Users\DSI\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\lodash\dist\lodash.js:6305:22), <anonymous>
:77:26)
    at EntityGenerator.underscore [as _engine] (C:\Users\DSI\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\util\engines.js:31:45)
    at EntityGenerator.engine (C:\Users\DSI\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\actions\actions.js:314:10)
    at EntityGenerator.template (C:\Users\DSI\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\actions\actions.js:289:15)
    at EntityGenerator.files (C:\Users\DSI\AppData\Roaming\npm\node_modules\generator-jhipster\entity\index.js:436:10)
    at C:\Users\DSI\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)

Could anyone to help me to solve this problem? Or could you help me to explain how to create many-to-many relationship in entity-generator?

Thanks, 
Kahfi

**Comment by jdubois** [comment]
You shouldn't have an error, so I will look at this, but this is outside of your question.

If you want a many-to-many relationship, you need to select a "many-to-many" relationship. If you select another kind of relationship, of course it will not work!

Here you are doing two many-to-one relationships, and you don't write the opposite side of the relationship (the one-to-many), which probably explain why you have an error.

**Comment by Kahfimaulana** [comment]
Hey, I have created one-to-many relationship before created many-to-one as opposite. But this I got an error. first I create : 
1. student : id, studentName     => student one-to-many with studentCourse entity

2. course : id , courseName one-to-many studentCourses  => course one-to-many with studentCourse

So you have to look at this problem. 

Thanks,

**Comment by jdubois** [comment]
Ok I'm reopening this - can you share your json config files, in your .jhipster folder?

**Comment by Kahfimaulana** [comment]
student.json :
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "studentCourse_student",
            "relationshipNameCapitalized": "StudentCourse_student",
            "relationshipFieldName": "studentCourse_student",
            "otherEntityName": "studentCourse",
            "relationshipType": "one-to-many",
            "otherEntityNameCapitalized": "StudentCourse"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String",
            "fieldNameCapitalized": "Name",
            "fieldNameUnderscored": "name"
        }
    ],
    "fieldsContainOwnerManyToMany": false,
    "fieldsContainOneToMany": true,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": false,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": false,
    "fieldsContainDate": false,
    "changelogDate": "20150306160014"
}


course.json : 
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "studentCourse_course",
            "relationshipNameCapitalized": "StudentCourse_course",
            "relationshipFieldName": "studentCourse_course",
            "otherEntityName": "studentCourse",
            "relationshipType": "one-to-many",
            "otherEntityNameCapitalized": "StudentCourse"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String",
            "fieldNameCapitalized": "Name",
            "fieldNameUnderscored": "name"
        }
    ],
    "fieldsContainOwnerManyToMany": false,
    "fieldsContainOneToMany": true,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": false,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": false,
    "fieldsContainDate": false,
    "changelogDate": "20150306160101"
}

**Comment by jdubois** [comment]
I'm sorry but you still have 2 one-to-many unidirectonal relationships here, this just can't work. Can you send me your complete config ?

**Comment by Kahfimaulana** [comment]
Yes, it was the opposite from many-to-one relationship as you said before. 
First I created student entity and course entity with one-to-many like in config above. Afterwards I created studentCourse entity with many-to-one relationship that will relate student and course as many-to-many relationship. Is that true ? 
The student and course entity have been successfully to create, but when I create the studentCouse entity it was fail.

**Comment by jdubois** [comment]
OK, so this your original configuration, and then you modified it, correct?
This original configuration cannot work: you need to do bi-directional relationships between entities. But as you want many-to-many relationships, don't do two one-to-many relationships, but one many-to-many relationship.
Student has a many-to-many relationship to Course
Course has a many-to-many relationship to Student
And one of those two must be the owner of the relationship.

**Comment by Kahfimaulana** [comment]
It's work !! 
Before, I thought that we have must create a new entity said 'studentCourse' as a generated table from many-to-many relationship between student and course. All We have to do is just create student entity has many-to-many relationship to course and it is an owner. Vice versa for course entity but it is not an owner. Then everything it's gonna be work, it will generated xml config to create a new table as generated table from many-to-many relationship. 

Thanks so much for your help.. 
I close this problem.

Regards,
Kahfi
