### ISSUE TITLE
swagger-ui  generate issue when `DeleteMapping` with regex.

### ISSUE THREAD

**Issue by Michael2008S** [jhipster/generator-jhipster#12250]
##### **Overview of the issue**

` "jhipsterVersion": "6.10.1"`

```java 
    /**
     * {@code DELETE /users/:login} : delete the "login" User.
     *
     * @param login the login of the user to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/users/{login:" + Constants.LOGIN_REGEX + "}")
    @PreAuthorize("hasAuthority(\"" + AuthoritiesConstants.ADMIN + "\")")
    public ResponseEntity<Void> deleteUser(@PathVariable String login) {
        log.debug("REST request to delete User: {}", login);
        userService.deleteUser(login);
        return ResponseEntity.noContent().headers(HeaderUtil.createAlert(applicationName,  "userManagement.deleted", login)).build();
    }
```

![image](https://user-images.githubusercontent.com/1240769/90314239-d9056100-df44-11ea-82ae-b8e7b365feca.png)

**Comment by qmonmert** [comment]
@Michael2008S 

The bug comes from Constants.java 
```
public static final String LOGIN_REGEX = "^(?>[a-zA-Z0-9!$&*+=?^_`**{|}**~.-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*)|(?>[_.@A-Za-z0-9-]+)$";
```

Curly braces generate a bug in
``` 
@GetMapping("/users/{login:" + Constants.LOGIN_REGEX + "}")
```
```
@DeleteMapping("/users/{login:" + Constants.LOGIN_REGEX + "}")
```
because curly braces are specials characters in mapping definition. Even if I escape curly braces, it doesn't work.

A solution will be to remove curly braces in LOGIN_REGEX and in the front. 

What do you think @pascalgrimaud & @mshima ?

**Comment by gmarziou** [comment]
What's the point of using a regex in a path variable? As far as I know Spring does not support it.

If you want to validate `login` path variable, it should be:

    @DeleteMapping("/users/{login}")
    public ResponseEntity<Void> deleteUser(@PathVariable("login") @Pattern(Constants.LOGIN_REGEX) String login) {

**Comment by mshima** [comment]
If @gmarziou solution works, it seems to be the right approach.
I think old generated validation is broken `...in:^(?>...` (line start).

**Comment by gmarziou** [comment]
This issue in Springfox is probably related: https://github.com/springfox/springfox/issues/2185

**Comment by pascalgrimaud** [comment]
Ok then, it looks like @gmarziou's solution is the good one. We should apply this change in our templates

**Comment by qmonmert** [comment]
PR done https://github.com/jhipster/generator-jhipster/pull/12276 with @gmarziou's solution
