### ISSUE TITLE
Update gradle dependencies

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#1227]
Some dependencies have explicit versions (from ``gradle.properties``) which are less than the ones defined by spring boot. Therefore a maven project uses ``jackson 2.4.5`` while gradle uses ``2.3.3`` for example. 
I think they sould use the same to remove potential errors induced by mixed dependencies.

**Comment by jdubois** [comment]
Yes, we should have the same versions everywhere! I don't know how you can do this with Gradle, but with Maven we just inherit from the parent pom, that's really easy.

**Comment by atomfrede** [comment]
[Gradle Spring Boot Plugin](http://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html#build-tool-plugins-gradle-dependencies-without-versions) offers a custom ``ResolutionStrategy`` for "blessed" artifacts. So I think I´ll give it a try with that.

**Comment by jdubois** [comment]
@atomfrede shouldn't this be closed now you have commited your update?

**Comment by atomfrede** [comment]
Yes, I would consider it as closed.
