### ISSUE TITLE
Cannot deploy application to CloudFoundry or Heroku

### ISSUE THREAD

**Issue by davykiala** [jhipster/generator-jhipster#1228]
Hello,
I've built an application with Jhipster. But when i deploy to CloudFoundry i have the following error : 
npm WARN unmet dependency which is version 1.0.2
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c mvn package -Pprod -DskipTests' }

Pushing the application to Cloud Foundry
En utilisant le fichier manifeste ./deploy/cloudfoundry/manifest.yml

Mise à jour de l'application xxxxxxxx dans l'org xxxxxxx / espace development comme xxxxxxxx@gmail.com...

OK

L'ajout xxxxxxxx ...

RATÉ
Erreur lors du téléchargement de l'application.
lstat /Users/xxxxxxxx/Working/workspace/xxxxx/target/*.war: no such file or directory

✖ { [Error: Command failed: /bin/sh -c cf push -f ./deploy/cloudfoundry/manifest.yml -p target/*.war
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c cf push -f ./deploy/cloudfoundry/manifest.yml -p target/*.war' }

Could you check this issue please ?

I've tried to deploy to Heroku i have an other error : 
 yo jhipster:heroku
Heroku configuration is starting
? Name to deploy as: xxxxxxx
? On which region do you want to deploy ? eu

Initializing deployment repository
Reinitialized existing Git repository in /Users/xxxxxxx/Working/workspace/talents/deploy/heroku/.git/

Creating Heroku application and setting up node environment
heroku apps:create hubtalents --region eu && heroku config:set NODE_ENV=production
✖ { [Error: Command failed: /bin/sh -c heroku apps:create xxxxxxx --region eu && heroku config:set NODE_ENV=production
Your version of git is 1.9.3. Which has serious security vulnerabilities.
More information here: https://blog.heroku.com/archives/2014/12/23/update_your_git_clients_on_windows_and_os_x
 !    Name is already taken
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c heroku apps:create xxxxxxxxx --region eu && heroku config:set NODE_ENV=production' }

Could you check please ?

**Comment by jdubois** [comment]
- for CloudFoundry it looks like you don't have a WAR in your target/ directory, which shouldn't be the case if you executed "yo jhipster:cloudfoundry" -> is this the command you launched?
- for Heroku the message is "name already taken", so the application name you have is already taken by someone else, and you need to change it

**Comment by davykiala** [comment]
For CloudFoundry Yes i execute the command : yo jhipster:cloudfoundry.
For Heroku :  I am sorry i did not paste the correct stacktrace. Here it is : 
remote: Building source:

remote: 

remote: -----> Deleting 0 files matching .slugignore patterns.

remote: 
remote:  !     Push rejected, no Cedar-supported app detected
remote: 

remote: Verifying deploy...

remote: 
remote: !	Push rejected to hubtalents.
remote: 

To https://git.heroku.com/hubtalents.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/hubtalents.git'


Error: Command failed: /bin/sh -c git push -f heroku master
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Deleting 0 files matching .slugignore patterns.
remote: 
remote:  !     Push rejected, no Cedar-supported app detected
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to xxxxxxxxx.
remote: 
To https://git.heroku.com/xxxxxxxx.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/xxxxxxx.git'

**Comment by davykiala** [comment]
For CloudFoundry it seem to be a problem with a goal : 
ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.2:build (run-grunt) on project xxxxx: Error during : grunt test --no-color: Process exited with an error: 3 (Exit value: 3) -> [Help 1]

**Comment by jdubois** [comment]
In that case it's your grunt tests which are failing: we run all tests before deploying. Run "grunt test" manually and you will see what the failed tests are.

**Comment by davykiala** [comment]
I've just run the test : 
grunt test
Running "clean:server" (clean) task

Running "concurrent:test" (concurrent) task
Fatal error: Cannot find module 'duplexer'


Execution Time (2015-03-07 07:41:37 UTC)
loading tasks     5ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 17%
clean:server      5ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 17%
concurrent:test  18ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 62%
Total 29ms

////Here is the npm version i used
npm -version
2.5.1

Do you have an idea ?

**Comment by jdubois** [comment]
No, I have no idea what the 'duplexer' module is! Maybe try a 'npm install' to install it?

**Comment by davykiala** [comment]
I 've just try to reinstall npm and i am getting suspicious warnings...

MacBook-Air-de-xxxx:xxxxxxxx myname$ sudo npm  install
npm WARN package.json xxxxxxxx@0.0.0 No repository field.
npm WARN prefer global yo@1.3.3 should be installed with -g

> yo@1.3.3 postinstall /Users/myname/Working/workspace/xxxxxxxx/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory

Everything looks all right!
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/request/node_modules/mime-types,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/mime-types,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/request/node_modules/mime-types,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/form-data requires async@'~0.9.0' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/async,
npm WARN unmet dependency which is version 0.7.0
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/mime-types,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/request/node_modules/mime-types,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/mime-types,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/request/node_modules/mime-types,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/form-data requires async@'~0.9.0' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/async,
npm WARN unmet dependency which is version 0.7.0
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency /Users/myname/Working/workspace/xxxxxxxx/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/mime-types,
npm WARN unmet dependency which is version 1.0.2

**Comment by davykiala** [comment]
Concerning the deployment issue on CloudFoundry, i notice my problem arrived when executing test with grunt. I know this is not the good solution to resolve my problem. In Gruntfile.js, i comment the following part : 
            generateOpenshiftDirectory: {
                    expand: true,
                    dest: 'deploy/openshift',
                    src: [
                        'pom.xml',
                        'src/main/**'
                ]
            }
        },
      /*  concurrent: {
            server: [<% if (useCompass) { %>
                'compass:server'<% } %>
            ],
            test: [<% if (useCompass) { %>
                'compass'<% } %>
            ],
            dist: [<% if (useCompass) { %>
                'compass:dist',<% } %>
                'imagemin',
                'svgmin'
            ]
        },*/
        karma: {
            unit: {
                configFile: 'src/test/javascript/karma.conf.js',
                singleRun: true
            }
        },

I don't know really why but now i can deploy my application to Cloudfoundry.

**Comment by jdubois** [comment]
- you have an issue in your tests
- you can see that issue if you run "grunt test" manually
- by default, we don't deploy if there is an issue in your test, that's a good safeguard
- of course, if you don't care about your tests, just comment the testing part, and deploy
