### ISSUE TITLE
Fix Couchbase option with Spring Boot 2.3

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#12300]
##### **Overview of the issue**

The Couchbase option is currently broken with Spring Boot 2.3.
See https://groups.google.com/g/jhipster-dev/c/P_4c1bCMVtI/m/ZE--g7qYBwAJ

##### **Suggest a Fix**

Some progress was made in this draft PR: https://github.com/jhipster/generator-jhipster/pull/11845
It can be a starting point. Pending upstream fixes from Spring Data Couchbase are also required.

##### **JHipster Version(s)**

master / 7

**Comment by pascalgrimaud** [comment]
@tchlyah : your help will be welcome here

**Comment by tchlyah** [comment]
Hello! Sorry it was very complicated for me lately. I've on the subject, I almost fixed all the issues, but I'm still blocked by [DATACOUCH-589](https://jira.spring.io/projects/DATACOUCH/issues/DATACOUCH-589). Spring Data Couchbase ignores the annotation [@ScanConsistency](https://github.com/spring-projects/spring-data-couchbase/blob/master/src/main/java/org/springframework/data/couchbase/repository/ScanConsistency.java) for generated queries.
I didn't find any work arround possible for this. So I'm waiting for https://github.com/spring-projects/spring-data-couchbase/pull/261, which fixes the problem, to be merged!

**Comment by mraible** [comment]
Hello @tchlyah - it looks like https://github.com/spring-projects/spring-data-couchbase/pull/261 needs a rebase. Can you please ping the owners of that PR and see if they can update things?

**Comment by pascalgrimaud** [comment]
So the discussion would be:
- should we remove Couchbase support or not ?
- looking the statistics: https://start.jhipster.tech/statistics -> I don't think Couchbase is used a lot (none/other -> 0.01% the last year)

**Comment by Tcharl** [comment]
I guess this is fixed in the current release: I see the couchbase test running
