### ISSUE TITLE
Languages don't appear with Vue and Internationalization Support

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#12322]
##### **Overview of the issue**

When I generate a simple app with the client framework **Vue** and I **enable the internationalization support** (with some langues), the menu to change languages doesn't appear. 

##### **Motivation for or Use Case**

This is a bug.

##### **Reproduce the error**

Generate an app with Vue and internationalization support.

##### **Suggest a Fix**

In the file src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts there is not the notion of languages.

##### **JHipster Version(s)**

6.10.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "6.10.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1598542454378,
    "promptValues": {
      "packageName": "com.app.publisher",
      "nativeLanguage": "fr"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "com.app.publisher",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "packageFolder": "com/app/publisher",
    "jwtSecretKey": "NDk0OWUyMTYyY2ZhZmU5YjI3MmE4YTUyZTc2OGJmN2NmNjA1MjkwOTdjNDBhM2VhYzU2MTZlMjBlOWEyNzQxZTdiZWJmZDIzYWM2ODExZWJmN2NkYzgyZWFlOTljZjMxM2ViNTgzZjgwYWRiYjVlMDZlN2QwOTk3NGFkMzIyMTM=",
    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": ["fr", "de", "es"]
  }
}

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
I'm working on it

**Comment by pascalgrimaud** [comment]
@qmonmert : did you try in private navigation ? I think I already saw this issue but it was related to cache

**Comment by qmonmert** [comment]
> @qmonmert : did you try in private navigation ? I think I already saw this issue but it was related to cache

@pascalgrimaud I will try tomorrow, but the variable `languages` is not defined in `generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs` but used in `generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.vue.ejs`

```
<%_ if (enableTranslation) { _%>
        <b-nav-item-dropdown id="languagesnavBarDropdown" right v-if="languages && Object.keys(languages).length > 1">
          <span slot="button-content">
            <font-awesome-icon icon="flag" />
            <span v-text="$t('global.menu.language')">Language</span>
          </span>
          <b-dropdown-item v-for="(value, key) in languages" :key="`lang-${key}`" v-on:click="changeLanguage(key);"
              :class="{ active: isActiveLanguage(key)}">
            {{value.name}}
          </b-dropdown-item>
        </b-nav-item-dropdown>
        <%_ } _%>
```

**Comment by qmonmert** [comment]
@pascalgrimaud I confirm the bug

**Comment by pascalgrimaud** [comment]
Thanks @qmonmert :-D
Have a look at https://github.com/jhipster/generator-jhipster/commit/e2b1906124e4b6d0e8e3cc79fa3a793130c0c27e#diff-28594319a2d7d5b4400fff18e5a1b8c7

**Comment by qmonmert** [comment]
@pascalgrimaud oops
