### ISSUE TITLE
Improve Blueprint Documentation

### ISSUE THREAD

**Issue by Kerruba** [jhipster/generator-jhipster#12330]
##### Improve the blueprint documentation

The idea is a to have a dedicated section of the site that would allow developer to better understand how to use 
the blueprint functionalities without having to search around in the code-base and different project documentation
(yeoman, ejs, etc)

##### **Motivation for or Use Case**

I'm a blueprint developer, and when I started building the blueprint I faced many difficulties because I didn't know
where to look for details about how to do things the correct way or where to change stuff to hook into Jhipster

##### **Related issues or PR**

I've created a small gist that explains some of the details of the `file` templates and is available here
https://gist.github.com/Kerruba/f0976ccd000d0454b10e52fe412d09ba

Wondering if it would make sense to start a dedicated section on the JHipster website to support other blueprint developers and get help

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
Hi @Kerruba 
I've been a "blueprint developper" too and I must admit that I'm impressed by your gist. It's clear that this is what we need on the official website.

During the first JHipster virtual meetup I have dealt with blueprints and module, for this occasion I wrote a medium article (https://medium.com/@anth.viard/build-your-own-jhipster-with-modules-and-blueprints-dd7a2833a388). My goal is to make blueprints and modules more accessible.

That the reason why I can bring you some help. WDYT?

**Comment by Kerruba** [comment]
Hi @avdev4j,

that would be great thanks. I've already followed some of your articles during my blueprint development experience and I found those very useful to grasp some of the details of JHipster, so thanks for those too :-).

What do you think could be a good next step into the direction of making blueprints and modules more accessible?

**Comment by avdev4j** [comment]
I'm glad to hear that :D. That was exactly the goal for. 

the first step could be to move your gist to the main website by adding a new page here https://github.com/jhipster/jhipster.github.io

Then maybe improve it too (if needed) and adding more content to explain step by step what we suppose to do (and how) with a blueprint. I would like to do some screencast too, we are laking that kind of content but it requires a lot of time and some skills :D.

I think we need to do a list of what we want to have as official documentation and ask the community to contribute too. @jhipster/developers maybe you already have any ideas...

The only drawbacks (as always with documentations) is that we weed to pay attention to always have a documentation up to date.

**Comment by mshima** [comment]
That specific documentation fits in our jsdoc.
Keeping updating the api documentation at a different repository is painful.
My opinion is to improve our jsdoc (add @private to every method outside generator-base.js) and publish.

**Comment by Kerruba** [comment]
> Keeping updating the api documentation at a different repository is painful.
@mshima that's true, but the problem is that sometimes features and information are hidden away deep into the code and in the class hierarchy, and checking for a function that is deep down 2 layers to understand how should I format an object is not that convenient. 
What about exposing the JHipster API on the website by automatically generate html from the jsdoc?

**Comment by mshima** [comment]
@Kerruba that's exactly what I am talking about. 👍 

This workflow creates a PR with jsdoc for each release.
https://github.com/mshima/yeoman-test/blob/master/.github/workflows/gh_pages.yml

**Comment by avdev4j** [comment]
I think what @mshima suggest could be a really good improvement. I'm sure that we will find some methods or code to improve too. However, I still think that will be a first step and  that we could go further, especially on a "how to" documentation. Maybe a starter guide or tutorials.

**Comment by Kerruba** [comment]
I thinking about this too.

Speaking about my gist specifically, that's more an "how to" guide rather than a proper documentation of the API. Also I'm thinking here about people that never used the blueprint and possibly just discovered JHipster and would like to try the blueprint functionality it out. 
Having a getting started guide/tutorial to guide him during the first steps would be awesome, with a dedicated section about the API reference documentation built from the jsdoc to check for those parts that need more details.

For example, I had a great experience with[ vue.js documentation](https://vuejs.org/v2/guide/): it's clear, well formatted, and very user friendly. 
The Vue JS API reference has a [dedicated section in the documentation](https://vuejs.org/v2/api/), and you go there when you need more details about some method/functionality.

@avdev4j if I was going to create the page as you suggested, where should I create it? Should we add an entirely new section? 
If so, I think we should also include the tutorials you created about debugging the generator-jhipster and the blueprint to that section.

**Comment by pascalgrimaud** [comment]
@Kerruba : I think it's important to have a new section, at same level than JDL.
Blueprint system becomes really popular the last months, so it's well deserved and will help people to start their blueprint.

**Comment by mshima** [comment]
@Kerruba any type of documentation are welcome, I just prefer api documentation at jsdoc.

For non api documentation I think it's worth to add the JHipster workflow:
https://github.com/jhipster/generator-jhipster/pull/12038#issuecomment-654405452 not sure if I made it wrong or I changed later, but the composing is at default priority.
https://github.com/jhipster/generator-jhipster/issues/12338 changes the workflow again but it should make the workflow much more consistent and predictable.

**Comment by avdev4j** [comment]
@pascalgrimaud The only thing I struggled with is that we already have a "Blueprint and module" section.  So adding a new one can be confusing for our users. 

Maybe we should adding new sub sections just like this one : https://www.jhipster.tech/modules/creating-a-blueprint/

examples:
https://www.jhipster.tech/modules/getting-started/
https://www.jhipster.tech/modules/debugging-a-blueprint/
https://www.jhipster.tech/modules/blueprint-api-documentation/
...

Or maybe we should split modules and blueprints...

**Comment by DanielFran** [comment]
> @Kerruba that's exactly what I am talking about. 👍
> 
> This workflow creates a PR with jsdoc for each release. https://github.com/mshima/yeoman-test/blob/master/.github/workflows/gh_pages.yml

@mshima Are you planning to implement blueprint documentation, or can we close this issue?

**Comment by mshima** [comment]
@DanielFran there is another open issue https://github.com/jhipster/generator-jhipster/issues/16988.
PR is waiting for v9.2.0.
The required implementation is merged but I don’t think it’s released.
