### ISSUE TITLE
Add support for UUID as entity field type with SQL databases 

### ISSUE THREAD

**Issue by nadouani** [jhipster/generator-jhipster#1235]
Hi, 

I usually use a UUID field in addition to the ID in every entity. To reproduce that using jhipster, it would be nice to add the UUID field type to the list of choices when the user selects a SQL database as persistence method.

UUID fields in Java could be stored as String in the database.

Thanks

**Comment by 8cells** [comment]
:+1:

**Comment by jdubois** [comment]
You have an ID and a UUID at the same time? Why?

Currently we have: an ID for SQL database, and a UUID for NoSQL databases.

**Comment by nadouani** [comment]
I prefer using UUIDs when I need to expose the entities' identifiers (I don't use the IDs as part of the URLs or REST APIs).

This is just for a security purpose, because I want prevent people from trying to guess an ID.

With that said, internally, I use the IDs when I need to fetch the data in the non exposed business services.

**Comment by jdubois** [comment]
OK, that's a neat idea, indeed.
But I don't know what we could add in JHipster: if you store those are String, we already support String, of course. Then if you have a specific key, for me that 's business code, and you need to code it yourself.

**Comment by artjomg** [comment]
I think this option is not business code by default since JPA supports UUID generation out of the box. It would be indeed  very nice if  UUID could be selected by the generator optionally.

**Comment by artjomg** [comment]
Looks like a duplicate of https://github.com/jhipster/generator-jhipster/issues/1244
