### ISSUE TITLE
Documentation issue: use bootRepackage to produce runnable war

### ISSUE THREAD

**Issue by danaki** [jhipster/generator-jhipster#1236]
Discussion is here http://stackoverflow.com/questions/28879370/gradle-war-tomcat-and-manifest/28883483

**Comment by atomfrede** [comment]
Maybe a cheat-sheet, containing all hipsters yeoman commands and all commands for maven/gradle can help to prevent such issues

**Comment by jdubois** [comment]
Aren't you supposed to do "bootRun"?
In that case we could argue that the Spring Boot documentation is not good enough, but we are just focusing on JHipster here -> we should not do another documentation on top of Spring Boot

**Comment by danaki** [comment]
I'm newbie, I just follow documentation provided here http://jhipster.github.io/production.html (hence not updated for gradle) and it doesn't work.

**Comment by atomfrede** [comment]
Yes, gradle section is missign there. @jdubois If you like I can add it.

**Comment by jdubois** [comment]
Yes of course -> sorry @danaki I didn't think it was totally lacking. We should of course have minimal documentation, and then redirect people to the Spring Boot doc.
