### ISSUE TITLE
Neo4j : broken builds

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12376]
##### **Overview of the issue**

Neo4j daily builds are broken since more than 10 days. 
see https://github.com/hipster-labs/jhipster-daily-builds/actions?query=workflow%3A%22Vue+Maven+NoSQL%22

cc @atomfrede 

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
It looks like maven somehow resolves to `io.github.classgraph:classgraph:jar:4.8.83` (from springfox) while the neo4 migrations require `4.8.87`. Pinning it resolves the tests. Swagger UI works fine too.
