### ISSUE TITLE
Protect user api and create a filtered user api for relationships.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12374]
##### **Overview of the feature request**

I propose to:
- Move current '/api/users' to '/api/admin/users' and protect it with admin role.
- Create a compatible '/api/users' with filtered data (id, first and last name).
And enable by default only if there is some relationship with User.

##### **Motivation for or Use Case**

Create a safer default to prevent privacy issues.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Big +1

About 
> Create a compatible '/api/users' with filtered data (id, first and last name).
And enable by default only if there is some relationship with User

do you have an idea how to do this part ?

**Comment by pascalgrimaud** [comment]
unless you want to take this ticket @mshima, I'd like to keep this for our JHipster Code in 1 week.
It's not difficult to achieve it. 
Are you ok ?

**Comment by mshima** [comment]
@pascalgrimaud I will not take this ticket.
Most of the job I am doing is related to the workflow.
My own todo is almost finished, then I will create some tickets with cleanup suggestions.
I would suggest to add a bounty to it, but you can keep it to JHipster Code.

**Comment by pascalgrimaud** [comment]
important to have

**Comment by pascalgrimaud** [comment]
adding a bounty, if it can motivated someone

**Comment by pascalgrimaud** [comment]
PR in progress: https://github.com/jhipster/generator-jhipster/pull/13048

**Comment by pascalgrimaud** [comment]
I'm increasing the bounty as it was much work than expected
Don't forget it @gzsombor

**Comment by gzsombor** [comment]
Thanks @pascalgrimaud ! I claimed the bug bounty here: https://opencollective.com/generator-jhipster/expenses/30439

**Comment by pascalgrimaud** [comment]
@gzsombor : approved
