### ISSUE TITLE
import-jdl : webpack:build launched several times

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12378]
##### **Overview of the issue**

When using import-jdl, the  `webpack:build` is launched several times, instead of 1.

##### **Motivation for or Use Case**

See the logs :

```
Running `webpack:build` to update client app

Entity Project generated successfully.

> jhipster@0.0.1-SNAPSHOT webpack:build /home/pgrimaud/tmp/02-burger
> npm run cleanup && npm run webpack:build:main


> jhipster@0.0.1-SNAPSHOT cleanup /home/pgrimaud/tmp/02-burger
> rimraf target/classes/static/


> jhipster@0.0.1-SNAPSHOT webpack:build:main /home/pgrimaud/tmp/02-burger
> npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal


> jhipster@0.0.1-SNAPSHOT webpack /home/pgrimaud/tmp/02-burger
> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"

Webpack: Starting ...
Compiling @angular/core : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @ngx-translate/core : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling ngx-infinite-scroll : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling ngx-cookie-service : es2015 as esm2015
Compiling @fortawesome/angular-fontawesome : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling ngx-webstorage : es2015 as esm2015
Compiling @fortawesome/angular-fontawesome/testing : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @ngx-translate/http-loader : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @ng-bootstrap/ng-bootstrap : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Webpack: Starting ...

  ✔ Compile modules
  ✔ Build modules
  ✔ Optimize modules
  ✔ Emit files

Webpack: Finished after 18.937 seconds.



 DONE  Compiled successfully in 18943ms                                                                                     13:38:38

   466 modules

Running `webpack:build` to update client app

Entity Label generated successfully.

> jhipster@0.0.1-SNAPSHOT webpack:build /home/pgrimaud/tmp/02-burger
> npm run cleanup && npm run webpack:build:main


> jhipster@0.0.1-SNAPSHOT cleanup /home/pgrimaud/tmp/02-burger
> rimraf target/classes/static/


> jhipster@0.0.1-SNAPSHOT webpack:build:main /home/pgrimaud/tmp/02-burger
> npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal


> jhipster@0.0.1-SNAPSHOT webpack /home/pgrimaud/tmp/02-burger
> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"

Webpack: Starting ...

  ✔ Compile modules
  ✔ Build modules
  ✔ Optimize modules
  ✔ Emit files

Webpack: Finished after 17.032 seconds.



 DONE  Compiled successfully in 17036ms                                                                                                                                          13:38:57

   466 modules

Running `webpack:build` to update client app

Entity Ticket generated successfully.

> jhipster@0.0.1-SNAPSHOT webpack:build /home/pgrimaud/tmp/02-burger
> npm run cleanup && npm run webpack:build:main


> jhipster@0.0.1-SNAPSHOT cleanup /home/pgrimaud/tmp/02-burger
> rimraf target/classes/static/


> jhipster@0.0.1-SNAPSHOT webpack:build:main /home/pgrimaud/tmp/02-burger
> npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal


> jhipster@0.0.1-SNAPSHOT webpack /home/pgrimaud/tmp/02-burger
> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"

Webpack: Starting ...

  ✔ Compile modules
  ✔ Build modules
  ✔ Optimize modules
  ✔ Emit files

Webpack: Finished after 16.716 seconds.



 DONE  Compiled successfully in 16725ms                                                                                                                                          13:39:17

   466 modules

Running `webpack:build` to update client app

Entity Attachment generated successfully.

> jhipster@0.0.1-SNAPSHOT webpack:build /home/pgrimaud/tmp/02-burger
> npm run cleanup && npm run webpack:build:main


> jhipster@0.0.1-SNAPSHOT cleanup /home/pgrimaud/tmp/02-burger
> rimraf target/classes/static/


> jhipster@0.0.1-SNAPSHOT webpack:build:main /home/pgrimaud/tmp/02-burger
> npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal


> jhipster@0.0.1-SNAPSHOT webpack /home/pgrimaud/tmp/02-burger
> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"

Webpack: Starting ...

  ✔ Compile modules
  ✔ Build modules
  ✔ Optimize modules
  ✔ Emit files

Webpack: Finished after 16.500 seconds.



 DONE  Compiled successfully in 16507ms                                                                                                                                          13:39:36

   466 modules

Running `webpack:build` to update client app

Entity Comment generated successfully.

> jhipster@0.0.1-SNAPSHOT webpack:build /home/pgrimaud/tmp/02-burger
> npm run cleanup && npm run webpack:build:main


> jhipster@0.0.1-SNAPSHOT cleanup /home/pgrimaud/tmp/02-burger
> rimraf target/classes/static/


> jhipster@0.0.1-SNAPSHOT webpack:build:main /home/pgrimaud/tmp/02-burger
> npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal


> jhipster@0.0.1-SNAPSHOT webpack /home/pgrimaud/tmp/02-burger
> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"

Webpack: Starting ...

  ✔ Compile modules
  ✔ Build modules
  ✔ Optimize modules
  ✔ Emit files

Webpack: Finished after 16.517 seconds.



 DONE  Compiled successfully in 16526ms                                                                                                                                          13:39:55

   466 modules
INFO! Generator jhipster:entity Project succeed
INFO! Generator jhipster:entity Label succeed
INFO! Generator jhipster:entity Ticket succeed
INFO! Generator jhipster:entity Attachment succeed
INFO! Generator jhipster:entity Comment succeed
INFO! Congratulations, JHipster execution is complete!
```

##### **Reproduce the error**

- generate a JHipster project
- then, add a JDL with several entities
- launch the import-jdl : `jhipster import-jdl bug-tracker.jdl`

##### **Related issues**

Not sure if it's related to all your last changes, @mshima ?

##### **JHipster Version(s)**

master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1598875218493,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Project {
  name String
}
entity Label {
  label String required minlength(3)
}
entity Ticket {
  title String required
  description String
  dueDate LocalDate
  date ZonedDateTime
  status Status
  type Type
  priority Priority
}
entity Attachment {
  name String required minlength(3)
  file AnyBlob
}
entity Comment {
  date ZonedDateTime
  text String
}
enum Status {
  OPEN (Open),
  WAITING_FOR_RESPONSE (Waiting for Customer Response),
  CLOSED (Closed),
  DUPLICATE (Duplicate),
  IN_PROGRESS (In Progress),
  REOPENED (Reopened),
  CANNOT_REPRODUCE (Cannot Reproduce),
  SOLVED (Solved),
  WONT_IMPLEMENT (Won't Implement),
  VERIFIED (Verified)
}
enum Type {
  BUG (Bug),
  FEATURE (Feature)
}
enum Priority {
  HIGHEST (Highest),
  HIGHER (Higher),
  HIGH (High),
  NORMAL (Normal),
  LOW (Low),
  LOWER (Lower),
  LOWERST (Lowest)
}

relationship OneToMany {
  Ticket{attachment} to Attachment{ticket}
  Comment{parent} to Comment{child}
}
relationship ManyToOne {
  Ticket{project(name)} to Project
  Ticket{assignedTo(login)} to User
  Ticket{reportedBy(login)} to User
  Comment{login} to User
}
relationship ManyToMany {
  Ticket{label(label)} to Label{ticket}
}

paginate Ticket with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

git version 2.28.0

node: v12.18.3

npm: 6.14.6

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.2, build a133471

**Comment by mshima** [comment]
@pascalgrimaud it’s related to a prior refactoring.
This commit should fix it https://github.com/jhipster/generator-jhipster/pull/12379/commits/005e18d5354792659a84615061386fdb4fad8d7d

**Comment by mshima** [comment]
@pascalgrimaud I cannot reproduce.
```
mkdir bug-tracker
cd bug-tracker
npm install jhipster/generator-jhipster#master
jhipster jdl bug-tracker.jh
```

Looks like you removed the application part, it was broken at samples repository, just fixed it.
Without application it will execute one `jhipster entity` for each entity.
AFAIK without `--skip-install` this is the expected behaviour.
```
Git repository initialized.
Application successfully committed to Git from /Users/mshima/aplicacoes/bug-tracker.

If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Server application generated successfully.

Run your Spring Boot application:
./mvnw

Client application generated successfully.

Start your Webpack development server with:
 npm start


> jhipster@0.0.1-SNAPSHOT cleanup /Users/mshima/aplicacoes/bug-tracker
> rimraf target/classes/static/

Entity Project generated successfully.
Entity Label generated successfully.
Entity Ticket generated successfully.
Entity Attachment generated successfully.
Entity Comment generated successfully.
INFO! Generator jhipster:app succeed
INFO! Congratulations, JHipster execution is complete!
```

**Comment by pascalgrimaud** [comment]
I just took a simple example of JDL, because when working for my customer, we don't have the application part in JDL files, we only have entities. And if I'm not wrong, it has never been mandatory to have the application part in JDL.

So the behavior of import-jdl has changed between v6.10.1 and current master.

I'm fine with this, because I can change my alias to something like that: `jhipster import-jdl bug-tracker.jdl --skip-install && npm run webpack:build`

But I afraid it will annoy our users.
What do you think?

**Comment by mshima** [comment]
> So the behavior of import-jdl has changed between v6.10.1 and current master.

It's a bug then. I will fix it.
