### ISSUE TITLE
improve Right Align in RTL Languages same as Angular or React

### ISSUE THREAD

**Issue by manisi** [jhipster/generator-jhipster#12384]
VueJs:(not correct)
<img width="1379" alt="Screen Shot 2020-02-11 at 16 37 11" src="https://user-images.githubusercontent.com/3120328/74240141-968d6e00-4cee-11ea-8926-28afbe7b9bf7.png">

React :(correct)
<img width="1409" alt="Screen Shot 2020-02-11 at 16 59 25" src="https://user-images.githubusercontent.com/3120328/74240878-123bea80-4cf0-11ea-96b4-727cf642f506.png">

**Comment by yehudab** [comment]
Can I take this issue?
Looks like the only thing that's missing is the automatic `dir` change when the language changes.
I also see slight RTL fixes that might be needed in the CSS. I can take this opportunity to fix these as well.

**Comment by pascalgrimaud** [comment]
sure, go ahead plz @yehudab !

**Comment by yehudab** [comment]
I ended up only fixing the vue issue in my PR,
I see that the other issues I saw (e.g. the ribon not being flipped) are common to all 3 frameworks, not just to vue, 
so I think that it will be better to create a new issue for them.

**Comment by pascalgrimaud** [comment]
> I see that the CSS issues I saw (e.g. the ribon not being flipped) are common to all 3 frameworks, not just to vue,
so I think that it will be better to create a new issue just for the CSS fixes.

Indeed, it's better to open a new issue about this improvement
