### ISSUE TITLE
Vue: global enum

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12407]
##### **Overview of the issue**

Similar to what was done for Angular, the enum should be global for Vue applications too, instead of beeing duplicated in each entities

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/9920
https://github.com/jhipster/generator-jhipster/pull/10015

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@pascalgrimaud PR done https://github.com/jhipster/generator-jhipster/pull/12409

**Comment by pascalgrimaud** [comment]
already, you're so fast @qmonmert !
