### ISSUE TITLE
Server-side password length check

### ISSUE THREAD

**Issue by aklauza** [jhipster/generator-jhipster#1240]
The JPA annotation for the minLength in the User's password is not effective as when that validation is run, the password is already hashed. And therefore, is always longer than the minimum.

Because of this, I can do a simple POST to /account/change_password with a password that only has 1 char and that is saved with no problems. (Tested with jhipster v2.5.2)

I recommend a fix like the following. May look dirty, but It is preferable to get the minLength from the Entity itselft than hardcoding it in the RestController:

```java
@RequestMapping(value = "/account/change_password", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
	@Timed
	public ResponseEntity<?> changePassword(@RequestBody String password) {
		int minLength;
		try {
			minLength= User.class.getDeclaredField("password").getAnnotation(Size.class).min();
		} catch (NoSuchFieldException e) {
			return new ResponseEntity<>(HttpStatus.FORBIDDEN);
		}
		if (StringUtils.isEmpty(password) || password.length() < minLength)
			return new ResponseEntity<>(HttpStatus.FORBIDDEN);
		userService.changePassword(password);
		return new ResponseEntity<>(HttpStatus.OK);
	}

**Comment by jdubois** [comment]
You are correct -> we should do the validation when we receive the password. And that would be consistent with our new entity validation (from yesterday!)

**Comment by jdubois** [comment]
As this is just a String, we can't use Bean Validation on it, so I'm just doing a simple check.
