### ISSUE TITLE
Merge or overwrite entity-client sub0generator

### ISSUE THREAD

**Issue by shorstki** [jhipster/generator-jhipster#12408]
Maybe it's not the right place to ask, but I run out of ideas. Asked already question on stackoverflow
https://stackoverflow.com/questions/63723484/customizing-entity-client-sub-generator-in-jhipster-blueprint

But nobody answers as maybe there is too little users with better knowledge about yeoman and jhipster. The thing is I am unable to do merge or overwrite `entity-client` sub-generator. Just placing files in `/generators` is not enough. I tried adding simple console log in parent `entity` generator 
```javascript
const BaseEntityGenerator = require('generator-jhipster/generators/entity');

class EntityGenerator extends BaseEntityGenerator {
    get initializing() {
        this.log('\n This is blueprint entity generator');
        return super._initializing();
    }

   // other get methods() just running return super._method();
}
```

I'm trying to modify `entity` generator as I saw it's calling `entity-client` from path `..\entity-client` and I thought it would solve the issue. Unfortunatelly any changes I make are not taken into action when I create entity and there is no tutorial for entity and client generators. Even if I don't call there `super._prompting()` I got the same questions from `entity` generator running `jhipster entity sample` from terminal. So

1. What is missing to make my changes work in a project generated from that blueprint? Blueprint is `npm link`ed locally
2. Do I have to regenerate app/project if I change the blueprint generator or it's used just from linked local blueprint? I run `npm link generator-jhipster-mycustomgenerator`

**Comment by mshima** [comment]
You can take a look at https://github.com/jhipster/generator-jhipster-jooq/blob/master/generators/entity-server/index.js.

**Comment by mshima** [comment]
Closing, should be discussed at https://github.com/jhipster/generator-jhipster/issues/12330.
