### ISSUE TITLE
Make generated package.json updatable by dependabot.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12413]
##### **Overview of the feature request**

Updating generated package.json currently is done manually.

Idea:
- Extract dependencies and version to a real package.json.
- Add placeholders in package.json.ejs.
- Replace placeholder with the version from the real package.json once package.json.ejs was consumed.

##### **Motivation for or Use Case**

Keep our generated package.json updated.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@mshima : I was thinking about this sometime back when we added support for dependabot in the generator. But do you think this is possible since the generated `package.json` file contains `.ejs` templates strings. I was sure how to automate this. 🤔

**Comment by mshima** [comment]
@SudharakaP see https://github.com/jhipster/generator-jhipster/pull/12415.
The implementation isn't normal but it works.
