### ISSUE TITLE
JHC - DevXP - do not mix allowed list and denied list when defining option

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#12418]
##### **Overview of the feature request**

Current jhipster options are not totally consistent.
* Some are acting as a denied list: skipclient, skipserver.
* Some are acting as an allowedlist: elasticsearch, dto.

We may use the same way to define options and provide reasonable defaults.

##### **Motivation for or Use Case**

Developer experience is always a key to success.
It will be always possible to achieve the needed combination using a combination of 'except' and wildcard keywords.

example: `client A, B except * // only generates A and B client `

---

### Main goal

Having a list of options to "reverse" (skipClient, skipServer, etc.) and propose a better name for them.
Have a JDL-first approach: the JDL as a DSL is easier to update/change than the whole generator.
Create new JDL options, that will be exported to JHipster-readable JSON files, but with their previous counterpart so as not to introduce any breaking change.

### Short-term goal

Remove the deprecated options from the JDL, keep the previous behaviour

### Long-term goal

Remove the deprecated options from the generator

**Comment by nonomoho** [comment]
I think we should keep `skipclient` or `skipserver`. If we pass them in positive (`generateclient`, `generateserver`), the user will feel forced to use it even the default value is `true`.

**Comment by mraible** [comment]
We should not use whitelist or blacklist in our code or documentation. Please use allowed list or denied list to be nice to others.

**Comment by Tcharl** [comment]
@nonomoho 
For the denied list transformed to allowed list I was thinking about:
* if nothing is specified, it would behave like `generateclient *`
* if something is specified it would only generate what is listed

**Comment by Tcharl** [comment]
Closing as it is nice to have and the community has no clear decision on the solution
