### ISSUE TITLE
Swagger UI - management API - GET requests with body

### ISSUE THREAD

**Issue by ndywicki** [jhipster/generator-jhipster#12412]
##### **Overview of the issue**

Hello Team,

When I try to fetch the Spring Boot Actuator APIs (/management) with Swagger UI, there is an issue about the GET request have a body.

Stacktrace:

```
swagger-ui-bundle.js:6 TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
    at swagger-ui-bundle.js:6
    at c (swagger-ui-bundle.js:79)
    at Generator._invoke (swagger-ui-bundle.js:79)
    at Generator.e.<computed> [as next] (swagger-ui-bundle.js:79)
    at o (swagger-ui-bundle.js:51)
    at s (swagger-ui-bundle.js:51)
```

I'm not sure where come from the Open API specifications : http://localhost:8080/v2/api-docs?group=management but the GET request have a parameter in "Body" like "additionalProp1, ..."

Example:
![Swagger-UI-get-issue](https://user-images.githubusercontent.com/1721344/92487076-1c25bd80-f1ed-11ea-90f5-4c8b0728aa44.png)

##### **Reproduce the error**

Generate new Jhipster application with all default values.
After admin login go to API menu and try management API with GET requests.

##### **Related issues**

No found in Jhipster but maybe this https://stackoverflow.com/questions/48749252/swagger-typeerror-failed-to-execute-fetch-on-window-request-with-get-head ?

##### **JHipster Version(s)**

v6.9.0
v6.10.1

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
sampleapp@0.0.1-SNAPSHOT C:\Workspaces\jhipster\v6.10.1\sampleapp
`-- generator-jhipster@6.10.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.1",
    "applicationType": "monolith",
    "baseName": "sampleapp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "caffeine",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1599569444230,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200728_776 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)

git version 2.28.0.windows.1

node: v14.8.0

npm: 6.14.7

Docker version 19.03.12, build 48a66213fe

docker-compose version 1.26.2, build eefe0d31

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Win10 & Edge Version 85.0.564.44 (Version officielle) (64 bits)

**Comment by pascalgrimaud** [comment]
thanks for reporting this @ndywicki 
I already saw this issue too, but not sure we can do something, as the API comes from Spring Boot

**Comment by PierreBesson** [comment]
I confirm this issue which is quite annoying. This is 100% caused by Swagger UI itself which fills out the request body with this sample text: `{"additionalProp1":"string","additionalProp2":"string","additionalProp3":"string"}`. I think I can find a workaround as this is quite annoying.

**Comment by ndywicki** [comment]
Hello,

Just for information is the same on the Jhipster-lite (v0.0.12-SNAPSHOT) Swagger UI ;-) 
But strangely no fetch error, only the badly interpreted the ProjectDTO schema:

![Capture](https://user-images.githubusercontent.com/1721344/156603052-70e161c5-4066-49a6-833e-7f5848c23532.PNG)

Could be a clue
