### ISSUE TITLE
Update all the Docker Compose files to Compose v3

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#12428]
All our Docker Compose files use the Compose v2 specification.

Current Compose version is v3.8 and we should update all of them -> https://docs.docker.com/compose/compose-file/

**Comment by pascalgrimaud** [comment]
It's complex, I'm adding a bounty on this

**Comment by pascalgrimaud** [comment]
Increasing the bounty as it was a lot of work to achieve this

**Comment by qmonmert** [comment]
@pascalgrimaud I claim my money  https://opencollective.com/generator-jhipster/expenses/25293

**Comment by jdubois** [comment]
Well done! Payment is approved, thank you so much!

**Comment by pascalgrimaud** [comment]
seriously, @jdubois, you're so fast !

**Comment by qmonmert** [comment]
thanks "Fast Man" @jdubois :) 
thanks @pascalgrimaud

**Comment by jdubois** [comment]
Not as fast as you on a running track, unfortunately....
