### ISSUE TITLE
Should gradle zip/tar distribution contain the web frontend ?

### ISSUE THREAD

**Issue by ddewaele** [jhipster/generator-jhipster#1243]
I'm not sure if this the correct way of doing things, but I'm trying to create a distribution (zip / tar file) containing my jHipster application

I'm executing the following command 
```
./gradlew installDist  (or bootRepackage)
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:bower
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:findMainClass
:startScripts UP-TO-DATE
:installDist
 
BUILD SUCCESSFUL
 
Total time: 5.884 secs
```

A tar file is generated in the ```build/distributions``` folder.

This tar file contains a ```lib``` and a ```bin``` folder.

Running the executable from the bin folder does not work. Although I'm not seeing any errors in the logs :
```
Davys-MacBook-Pro:bin ddewaele$ ./Test
[INFO] com.mycompany.myapp.Application - Starting Application on Davys-MacBook-Pro.local with PID 55041 (/Users/ddewaele/Projects/Test/build/distributions/Test-0.1-SNAPSHOT/lib/Test-0.1-SNAPSHOT.jar started by ddewaele in /Users/ddewaele/Projects/Test/build/distributions/Test-0.1-SNAPSHOT/bin)
[DEBUG] com.mycompany.myapp.Application - Running with Spring Boot v1.2.2.RELEASE, Spring v4.1.5.RELEASE
[DEBUG] org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
[DEBUG] com.mycompany.myapp.config.AsyncConfiguration - Creating Async Task Executor
[DEBUG] com.mycompany.myapp.config.MetricsConfiguration - Registering JVM gauges
[INFO] com.mycompany.myapp.config.MetricsConfiguration - Initializing Metrics JMX reporting
[DEBUG] com.mycompany.myapp.config.DatabaseConfiguration - Configuring Datasource
[DEBUG] com.mycompany.myapp.config.DatabaseConfiguration - Configuring Liquibase
objc[55041]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
[DEBUG] com.mycompany.myapp.config.MailConfiguration - Configuring mail server
[INFO] com.mycompany.myapp.Application - Running with Spring profile(s) : [dev]
[INFO] com.mycompany.myapp.config.WebConfigurer - Web application configuration, using profiles: [dev]
[DEBUG] com.mycompany.myapp.config.WebConfigurer - Initializing Metrics registries
[DEBUG] com.mycompany.myapp.config.WebConfigurer - Registering Metrics Filter
[DEBUG] com.mycompany.myapp.config.WebConfigurer - Registering Metrics Servlet
[DEBUG] com.mycompany.myapp.config.WebConfigurer - Initialize H2 console
[INFO] com.mycompany.myapp.config.WebConfigurer - Web application fully configured
[INFO] com.mycompany.myapp.config.ThymeleafConfiguration - loading non-reloadable mail messages resources
[DEBUG] com.mycompany.myapp.config.CacheConfiguration - Starting Ehcache
[DEBUG] com.mycompany.myapp.config.CacheConfiguration - Registering Ehcache Metrics gauges
[DEBUG] com.mycompany.myapp.config.apidoc.SwaggerConfiguration - Starting Swagger
[DEBUG] com.mycompany.myapp.config.apidoc.SwaggerConfiguration - Started Swagger in 13 ms
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Enter: com.mycompany.myapp.repository.CustomAuditEventRepository.auditEventRepository() with argument[s] = []
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Exit: com.mycompany.myapp.repository.CustomAuditEventRepository.auditEventRepository() with result = com.mycompany.myapp.repository.CustomAuditEventRepository$1@28e0e464
[INFO] com.mycompany.myapp.Application - Started Application in 8.538 seconds (JVM running for 8.928)
[INFO] com.mycompany.myapp.Application - Access URLs:
----------------------------------------------------------
	Local: 		http://127.0.0.1:8080
	External: 	http://192.168.1.131:8080
----------------------------------------------------------

```

and the app does seem to start, I'm getting this on every request:

![](https://dl.dropboxusercontent.com/u/13246619/Ixor/IxorTalkDocs/jhipster_error.png)

I'm guessing the distribution does not contain the angular part.  (Not even sure if it should be included or not.)

**Comment by jdubois** [comment]
I have no idea how the Gradle build is working for that part, but in order to have a distribution you need to use the "prod" profile, and that doesn't seem to be the case here.

**Comment by atomfrede** [comment]
Not sure how it should work, but I got the same error when I executed the jar by accident. So I guess the executable just wraps the jar file and not the war generated bootRepackage. Can you check if the generated war file works correctly?

**Comment by ddewaele** [comment]
The generated WAR (result of ```gradlew bootRepackage``) works fine and can be executed with the jar command.

Our goal is to have the code checked out by jenkins, built using gradle, uploaded to a repo, and then have a deploy process that downloads an artifact (executable war or tar file) and depoy it to our dev servers. 

I noticed that the war file that gets uploaded to our maven repo is not the executable one, and that the distribution file (tar) can be executed, but doesn't contain the web frontend.

I'll check with our Spring Boot / Gradle gurus today to see what is wrong and what needs to be added. 

I'll update my findings here

**Comment by atomfrede** [comment]
@ddewaele Great! I think the easiest solution would be to configure jenkins to pick up the correct war file and upload to your repository instead of trying to change the generated jars/wars. Nevertheless it should be possible with a little effort, as you just need to add the webapp directory to the generated artifact.

**Comment by ddewaele** [comment]
I don't want to change any of the generated jars (unless there is a bug in jHipster and we should see how we can fix it on that level). 

I do think some updates will be needed in the jHipster build.gradle template file as currently it doesn't support installing or installing / deploying artifacts to maven.

We just need to clarify 

- what artifacts will get uploaded to the repository (ex: the original and the auto-executable) when using jHipster with maven and gradle builds
- what the content of that distribution tar/zip file should be (should it also include the webapp).

Again, the goal is to have an end-to-end CI process where we can

- checkout code from git
- build the sources (using either gradle or maven)
- upload artifacts to a maven repository (lots of gradle projects upload artifacts to maven repos)
- have a deploy process download these artifacts (either auto-exec war or tar file) and deploy them somewhere on the dev environment

But I'll start with some Spring Boot / Gradle reading first :)

**Comment by jdubois** [comment]
OK, keep us updated, of course that should be interesting for a lot of people (including those using Maven!).
Should we close this ticket, and then add smaller tickets, depending on what you find out?

**Comment by ddewaele** [comment]
@jdubois  This topic here is more of a question / discussion than it is an issue. So it shouldn't be kept open too long.

We should first have a common understanding of what we want to achieve, and then define more fine-grained issues / pull requests

For me it involves around how we want to see jHipster distributing your app (packaging it , uploading it to a repository , and having people / processes use that distribution) without too much hassle.

My view on this :  

- jHipster should provide out of the box reasonable defaults for building / packaging an distributing your application (when both using maven and Gradle)
- This involves the ability to install / upload the necessary artifacts to a repository (most likely maven) to do so.
- The auto-executable WAR file is one such way of distributing the app.
- The tar/zip distribution archive is another.
- Both ways of distribution should allow for straightforward executing the app (either by launching the WAR file with the jar command, or launching the shell script in the tar/zip distribution).
- 
Is that more or less how you see it ?

**Comment by jdubois** [comment]
Yes we agree!

Concerning your points:

- Yes we should have out of the box reasonable defaults
- I didn't do anything about uploading to a repository, and didn't think this was an issue. I guess that would just be configuring a plugin? If it's small & easy, let's do it.
- Yes the executable WAR file was my favorite
- A WAR file to be deployed on an app server is the other option

**Comment by atomfrede** [comment]
From my point of view having an executable .war file and a .war file deployable on an application server is enough.

**Comment by ddewaele** [comment]
OK. 

- I'll issue a pull request for some gradle changes making it easier to get started with maven out of the box.
- The distribution (tar/zip) that's generated using ```./gradlew bootRepackage``` is handled by the [Sprint Boot Gradle plugin](http://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html) and the [Gradle distribution plugin](https://gradle.org/docs/current/userguide/distribution_plugin.html). Could also be an issue on that level. 
- The distribution (tar/zip) is only available when using Gradle build. (An equivalent could be done using the Maven Assembly Plugin)

This issue can be closed I think.
