### ISSUE TITLE
Double warning logging when creating an entity from the CLI

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#12433]
##### **Overview of the issue**

When trying to fix #11691, I tried to generate an entity with a reflexive one-to-many relationship using neo4j as DB type.
However, this appeared in the console:
```
WARNING! Could not find the other side of the relationship {
    "relationshipName": "friends",
    "otherEntityName": "person",
    "relationshipType": "one-to-many",
    "otherEntityRelationshipName": "person",
    "otherEntityPrimaryKeyType": "String"
}
     info Creating changelog for entities Person
WARNING! Could not find the other side of the relationship {
    "relationshipName": "friends",
    "otherEntityName": "person",
    "relationshipType": "one-to-many",
    "otherEntityRelationshipName": "person",
    "otherEntityPrimaryKeyType": "String"
}
```

##### **Motivation for or Use Case**

It's not very user-friendly to have the same warning appear twice.

##### **Reproduce the error**

- jhipster entity Person
- you can skip the field generation
- create one relationship like so
```
? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? Person
? What is the name of the relationship? friends
? What is the type of the relationship? one-to-many
? What is the name of this relationship in the other entity? person
```
- you can skip the options

##### **Related issues**

#11691 

##### **Suggest a Fix**

I didn't have time to look into this.

##### **JHipster Version(s)**

master

##### **JHipster configuration**

My JDL file:
```
application {
  config {
    baseName testyy
    databaseType neo4j
    devDatabaseType neo4j
    prodDatabaseType neo4j
    enableHibernateCache false
  }
}

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

The Person entity
```json
{
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    }
  ],
  "relationships": [
    {
      "relationshipName": "friends",
      "otherEntityName": "person",
      "relationshipType": "one-to-many",
      "otherEntityRelationshipName": "person"
    }
  ],
  "service": "no",
  "readOnly": false,
  "pagination": "no",
  "name": "Person",
  "changelogDate": "20200910210812"
}
```

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
It’s in my todo.

**Comment by MathieuAA** [comment]
Thanks Marcelo!
