### ISSUE TITLE
Improve test speed by using mocha's parallel flag

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#12444]
When doing some tests this morning, I decided to try the `-p` flag of Mocha to run tests in parallel.
The results:
  - Tests were over in **4 minutes**
  - Only **40/5000+** tests failed (all CLI-related)

The error:
```
 Error: ENOENT: no such file or directory, uv_cwd
      at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:128:26)
      at process.cwd (node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:10:19)
      at process.cwd (node_modules/graceful-fs/polyfills.js:10:19)
      at _prepareTempEnv (test/utils/utils.js:60:25)
      at testInTempDir (test/utils/utils.js:84:25)
      at Context.<anonymous> (test/cli/cli.spec.js:386:21)
```

Without the flag: Over **13 minutes**

@jhipster/developers I think it's worth investigating.

If the investigation is inconclusive, we can still split our tests so as to have a majority of tests running in parallel, and a few others sequentially.

**Comment by MathieuAA** [comment]
BTW, solving this issue before JCode would be good, so that we don't wait too long for our test to be over. 
Or maybe we could do this during JCode :)

**Comment by atomfrede** [comment]
That is a huge improvement :+1:

**Comment by mshima** [comment]
https://github.com/mshima/generator-jhipster/commits/mocha_parallel
Fell free to test, but I am against merging it.
- won’t benefit github CI (dual core)
- will leave too many temp files. Proper cleanup after step should be added to tests. Same folder is used currently, cleanup happens on before step.

A easy workaround is to run only desired tests:
`mocha test/...`

**Comment by deepu105** [comment]
I tried to run tests in parallel when I was developing the CLI but it was
very buggy and flaky so gave up but probably we can split the tests into
multiple groups and run some of them in parallel. For folder cleanup may be
we can switch to generating folder with random names and clean after each
test

**Comment by MathieuAA** [comment]
Splitting them by domain like JDL, client, server, etc., or even by subgen may be a good idea

**Comment by mraible** [comment]
> From 13mins down to 4/5 minutes

Wow - great work @MathieuAA!!

**Comment by MathieuAA** [comment]
Thanks Matt!

**Comment by mshima** [comment]
@MathieuAA I would prefer create PRs instead of committing directly to master.
There is ~37 uses of the parallel unsafe function, only ~8 of them will need independent fixes.

**Comment by MathieuAA** [comment]
Great, then it may be the next steps

**Comment by deepu105** [comment]
Yes everyone since JDL is now in the main generator lets do PRs so that we
can keep track of changes.
