### ISSUE TITLE
Option to choose uuid and not long as id

### ISSUE THREAD

**Issue by seghers** [jhipster/generator-jhipster#1244]
I'm developing an application which uses jhipster with the postgresql db. I recently discovered it and I realy love it.

Almost all my table id's are UUID(eg. users), some are INTEGERS(static data: eg. levels) none are LONG.
Would it be possible to add an option in the entity generator to choose the id type. 
I do know uuid's are supported in postgresql but not in mysql which might complicate the implementation.

I'm asking this because every time I regenerate the project after a jhipster update, I have to replace all the Long dependant code with UUID, Integer.

**Comment by jdubois** [comment]
Of course the only way to make it work currently, is the way you do: you need to refactor.

I'd like to propose other option for IDs, indeed, and having other types is the most important one. Note that we also support MongoDB and Cassandra, and that they use UUIDs! So that shouldn't be hard to code. How do you generate your UUIDs? Can you look at the Cassandra code to see if that could suit your needs?

**Comment by seghers** [comment]
Currently the entities that need a UUID extend a baseClass:

```
    @Id
    @NotNull
//    @Type(type = "pg-uuid") //TODO necessary for prod:postgres, not for dev:h2.
    @GeneratedValue(generator = "myUUIDGenerator")
    @GenericGenerator(name = "myUUIDGenerator", strategy = "uuid2")
    @Column(name = "id", columnDefinition = "uuid")
    protected UUID id;

    @CreatedDate
    @NotNull
    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    @Column(name = "created_date", nullable = false)
    protected DateTime createdDate = DateTime.now();
```

I'll look at Cassandra in a moment

**Comment by seghers** [comment]
> Can you look at the Cassandra code to see if that could suit your needs?

The cassandra implementation uses alot of extra code that is not needed for running postgres with uuid as id. 
It only needs replacing Long > Uuid. 
- The baseClass contains also the hashCode(), get,set. 
- Some liquibase changes: ```
<column name="id" type="uuid">```

The biggest problem as I see it is that mysql is not supporting uuid. This could be solved by splitting 'databaseType = sql' in 'sub-groups' as the jhipster generator already does.

- ...

**Comment by jdubois** [comment]
OK so @seghers your last comment is the only correct solution currently.

We will refactor types in a few weeks, so we can add more types, and so we can use those types in our new https://github.com/jhipster/jhipster-uml project -> we need to share the types between both projects!

**Comment by cselti** [comment]
The jhipster-uml project sounds very interesting :+1:
