### ISSUE TITLE
Vue: bad enum definition

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12448]
##### **Overview of the issue**

The enum is not correctly defined in Vue.js application.

##### **Motivation for or Use Case**

Because of bad definition, we can't init a specific value, otherwise, the `npm test` failed

```
  ● Component Tests › Ticket Management Update Component › Previous state › Should go previous state

    TypeError: Cannot read property 'previousState' of undefined

      117 |     describe('Previous state', () => {
      118 |       it('Should go previous state', async () => {
    > 119 |         comp.previousState();
          |              ^
      120 |         await comp.$nextTick();
      121 | 
      122 |         expect(comp.$router.currentRoute.fullPath).toContain('/');

      at src/test/javascript/spec/app/entities/ticket/ticket-update.component.spec.ts:119:14
      at step (node_modules/tslib/tslib.js:140:27)
      at Object.next (node_modules/tslib/tslib.js:121:57)
      at node_modules/tslib/tslib.js:114:75
      at Object.__awaiter (node_modules/tslib/tslib.js:110:16)
      at Object.<anonymous> (src/test/javascript/spec/app/entities/ticket/ticket-update.component.spec.ts:118:38)


Test Suites: 1 failed, 28 passed, 29 total
Tests:       6 failed, 134 passed, 140 total

```

##### **Reproduce the error**

- generate a Vue.js application
- create an entity with enum
- launch npm test : it works
- then, in entity-update.component.ts, init the field with a value of enum
- launch npm test: it failed

You can play with this project: https://github.com/pascalgrimaud/jh-200820-vue-enum
There is a specific branch: `bug-enum`

You can see the diff here:
https://github.com/pascalgrimaud/jh-200820-vue-enum/commit/3a75d6dd77f1490d9ec8eff0c32509ef6303f089

##### **Suggest a Fix**

The reason is explained here https://www.typescriptlang.org/docs/handbook/enums.html

> Const enums can only use constant enum expressions and unlike regular enums they are completely removed during compilation. Const enum members are inlined at use sites. This is possible since const enums cannot have computed members.

Currently we have:

```typescript
export const enum Status {
  OPEN = 'Open',
  WAITING_FOR_RESPONSE = 'Waiting for Customer Response',
  CLOSED = 'Closed',
  DUPLICATE = 'Duplicate',
  IN_PROGRESS = 'In Progress',
  REOPENED = 'Reopened',
  CANNOT_REPRODUCE = 'Cannot Reproduce',
  SOLVED = 'Solved',
  WONT_IMPLEMENT = 'Won&#39;t Implement',
  VERIFIED = 'Verified',
}
```

We should have instead:

```typescript
export enum Status {
  OPEN = 'Open',
  WAITING_FOR_RESPONSE = 'Waiting for Customer Response',
  CLOSED = 'Closed',
  DUPLICATE = 'Duplicate',
  IN_PROGRESS = 'In Progress',
  REOPENED = 'Reopened',
  CANNOT_REPRODUCE = 'Cannot Reproduce',
  SOLVED = 'Solved',
  WONT_IMPLEMENT = 'Won&#39;t Implement',
  VERIFIED = 'Verified',
}
```

##### **JHipster Version(s)**

Current master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "burger",
    "jhipsterVersion": "6.10.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1597848200224,
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "io.github.pascalgrimaud",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "io/github/pascalgrimaud",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Ticket {
  title String required
  description String
  dueDate LocalDate
  date ZonedDateTime
  status Status
  type Type
  priority Priority
}
enum Status {
  OPEN (Open),
  WAITING_FOR_RESPONSE (Waiting for Customer Response),
  CLOSED (Closed),
  DUPLICATE (Duplicate),
  IN_PROGRESS (In Progress),
  REOPENED (Reopened),
  CANNOT_REPRODUCE (Cannot Reproduce),
  SOLVED (Solved),
  WONT_IMPLEMENT (Won't Implement),
  VERIFIED (Verified)
}
enum Type {
  BUG (Bug),
  FEATURE (Feature)
}
enum Priority {
  HIGHEST (Highest),
  HIGHER (Higher),
  HIGH (High),
  NORMAL (Normal),
  LOW (Low),
  LOWER (Lower),
  LOWERST (Lowest)
}

relationship ManyToOne {
  Ticket{assignedTo(login)} to User
  Ticket{reportedBy(login)} to User
}

paginate Ticket with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

git version 2.28.0

node: v12.18.3

npm: 6.14.6

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.2, build a133471

**Comment by fdaudies** [comment]
Hi @pascalgrimaud  Could i work on this ?

**Comment by pascalgrimaud** [comment]
yes @fdaudies

**Comment by deftdawg** [comment]
Spent a couple of hours trying to look up Enum values by the keys only to discover the addition of "const" eliminates the keys at compile time... dough!

The patch in #12615 fixes that, and it can be applied directly to your generator-jhipster folder, run `npm install` and then dirty up your enums by adding a dummy value and running jdl-import, removing the dummy value and re-running jdl-import.  (there's probably a quicker way to dirty the files via .jhipster properties, but I'm super tired atm)
