### ISSUE TITLE
When the "cacheProvider" is set to "no", the "enableHibernateCache" is automatically set to "true"

### ISSUE THREAD

**Issue by MarlonLuan** [jhipster/generator-jhipster#12445]
##### **Overview of the issue**

When the "cacheProvider" is set to "no", the "enableHibernateCache" is automatically set to "true"

When the "cacheProvider" is set to "no", the option to select the  "enableHibernateCache" does not appear,
then the default value("true") is set.

##### **Reproduce the error**

- jhipster

? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? PostgreSQL
? Do you want to use the Spring cache abstraction? No - Warning, when using an SQL database, this will disable the Hibernate 2nd level cache!

##### **Suggest a Fix**

- Set default value of "enableHibernateCache" to "false"

or

- Set value of "enableHibernateCache" to "false" when  "cacheProvider" is set to "no"
 

##### **JHipster Version(s)**

master
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "master",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1599995426806,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "clientThemeVariant": "primary",
    "useSass": true,
    "enableHibernateCache": true,
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Debian-1, mixed mode, sharing)

git version 2.28.0

node: v12.18.3

npm: 6.14.8

Docker version 19.03.12, build 48a6621

docker-compose version 1.25.0, build unknown

**Comment by MathieuAA** [comment]
Does this happen when using the JDL? I admit I haven't tried

**Comment by MarlonLuan** [comment]
It doesn't happen when i use jdl

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>app.jdl</summary>
<pre>
application {
  config {
    cacheProvider no
  }
}

</pre>
</details>




<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "baseName": "jhipster",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "creationTimestamp": 1601036160240,
    "skipServer": false,
    "packageFolder": "com/mycompany/myapp",
    "packageName": "com.mycompany.myapp",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "applicationType": "monolith",
    "entities": [],
    "blueprints": [],
    "otherModules": [],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "reactive": false,
    "pages": [],
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons"
  }
}

</pre>
</details>

----


Using CLI automatically:
```
enableHibernateCache = true
```



Using JDL automatically:
```
enableHibernateCache = false
```

**Comment by mshima** [comment]
Condition is missing at:
https://github.com/jhipster/generator-jhipster/blob/b1b6f78c0f7de30dce6dbadd191cd6ad50cd1fac/generators/server/prompts.js#L311-L312
@MarlonLuan can you create a PR?
