### ISSUE TITLE
Vue: prettier for Vue files

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12455]
##### **Overview of the issue**

It would be nice to have prettier formatting for Vue file.

##### **Motivation for or Use Case**

Consistency in Vue file

##### **Reproduce the error**

- generate a Vue.js application
- look at the code:
    - change-password.vue is with 4 spaces for indent
    - user-management.vue is with 2 spaces for indent

##### **Suggest a Fix**

- add Vue to list of file for prettier
- check configuration and put it to 2 spaces if not

##### **JHipster Version(s)**

Current master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "6.10.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": ["cypress"],
    "pages": [],
    "creationTimestamp": 1599409665813,
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "io.github.pascalgrimaud",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "clientTheme": "cerulean",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "io/github/pascalgrimaud",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "useSass": true,
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

git version 2.28.0

node: v12.18.3

npm: 6.14.6

yeoman: 3.1.1

yarn: 1.22.5

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.2, build a133471

**Comment by swarajsaaj** [comment]
@pascalgrimaud Can I work on this?
I think adding .vue extension to https://github.com/jhipster/generator-jhipster/blob/1ea10ad6595ade2c98293556acd901af8f365113/generators/generator-base.js#L233 should do it.
I can try changing and test.

**Comment by pascalgrimaud** [comment]
sure @swarajsaaj : go ahead plz ! :)

**Comment by swarajsaaj** [comment]
@pascalgrimaud  I raised a PR for this #12639 , but it seems the checks are failing due to some other reasons (connection timeout in one case). Is this expected with Github actions and the MR can be reviewed?
