### ISSUE TITLE
Front: icon in menu

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12457]
##### **Overview of the issue**

The icon in menu could be more appropriate, for Angular, React and Vue
I suggest:
- change the icon of administration to https://fontawesome.com/icons/users-cog?style=solid
- change the icon of administration>configuration to https://fontawesome.com/icons/cogs?style=solid
- change the icon of administration>user-management to https://fontawesome.com/icons/users?style=solid
- change the icon of administration>database to https://fontawesome.com/icons/database?style=solid

##### **Motivation for or Use Case**

Better UI 

##### **Reproduce the error**

- generate an application
- start the app
- log in
- navigate in menu

##### **Suggest a Fix**

- import new icons
- use these icons in page

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ascelineboullen** [comment]
I'm looking this one ! :)

**Comment by pascalgrimaud** [comment]
thanks @ascelineboullen : I assign the ticket
