### ISSUE TITLE
Front: refresh button

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12456]
##### **Overview of the issue**

When viewing an entity or the user-management page, it would be nice to have a `refresh` button.

##### **Motivation for or Use Case**

No need to press F5 :-)

##### **Reproduce the error**

- generate an application (Angular, React or Vue)
- generate entities (not mandatory)
- start the app
- go to user-management
- or go to an entity

##### **Suggest a Fix**

- add refresh button in front page
- link the action to retrieve users or entities
- do it for all front: Angular, React, Vue

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by FabienEssid** [comment]
I'm looking this one

**Comment by pascalgrimaud** [comment]
Thanks @FabienEssid

**Comment by FabienEssid** [comment]
Some news about my work.  
I have to make modifications on these parts :  
* [x] React - User Management screen
* [x] React - Entity screen with pagination
* [x] React - Entity screen with infinite scroll
* [x] React - Entity screen without pagination
* [x] Angular - User Management screen
* [ ] Angular - Entity screen with pagination
* [ ] Angular - Entity screen with infinite scroll
* [ ] Angular - Entity screen without pagination
* [ ] Vue - User Management screen
* [ ] Vue - Entity screen with pagination
* [ ] Vue - Entity screen with infinite scroll
* [ ] Vue - Entity screen without pagination

**Comment by pascalgrimaud** [comment]
Thanks @FabienEssid : don't hesitate to push your work, although it's not finished

**Comment by FabienEssid** [comment]
I worked on this issue tonight. I completed the Angular part.
I have to make modifications on Vue templates now. Work in progress :muscle:

**Comment by pascalgrimaud** [comment]
@FabienEssid : no worry, nothing urgent here, so take your time. And you should rest because of all us should be tired after the JHipster code :)

**Comment by FabienEssid** [comment]
I claimed my bug bounty https://opencollective.com/generator-jhipster/expenses/25361  
Thanks for it !

**Comment by pascalgrimaud** [comment]
@FabienEssid : approved ! thanks for helping the project ;)
