### ISSUE TITLE
Vue: toast instead of alert custom

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12450]
##### **Overview of the issue**

In a Vue.js application, the alert is managed by alert service and is custom.
We should use Toast instead, like it's done in JHipster Control Center

##### **Motivation for or Use Case**

Simpler and better UI

##### **Reproduce the error**

- generate a Vue.js application
- start the app
- login in
- go to user management
- edit an user

##### **Suggest a Fix**

- remove the alert.service.ts and alert.service.spec.ts
- replace by the toast (see an example at https://github.com/jhipster/jhipster-control-center/blob/master/src/main/webapp/app/applications/instance/instance.component.ts#L96-L101)
- the place where to change is:
    - user-management
    - entity

##### **JHipster Version(s)**

Current master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "6.10.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": ["cypress"],
    "pages": [],
    "creationTimestamp": 1599409665813,
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "io.github.pascalgrimaud",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "clientTheme": "cerulean",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "io/github/pascalgrimaud",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "useSass": true,
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

git version 2.28.0

node: v12.18.3

npm: 6.14.6

yeoman: 3.1.1

yarn: 1.22.5

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.2, build a133471

**Comment by fdaudies** [comment]
Hello @pascalgrimaud, I'm available to work on this

**Comment by pascalgrimaud** [comment]
Thanks so much @fdaudies : I will be so happy to have it
I assign the ticket to you !

**Comment by pascalgrimaud** [comment]
More work than expected for a 1st contribution
I'm adding a bounty, as it's well deserved

**Comment by fdaudies** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/25978

**Comment by pascalgrimaud** [comment]
thanks @fdaudies : approved
