### ISSUE TITLE
Annotation to detect generated files

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12459]
##### **Overview of the issue**

There is no way to know if a java class has been generated by JHipster or not. It will help real applications for development

##### **Motivation for or Use Case**

Add an annotation like `@Generated` to all generated classes from JHipster

##### **Suggest a Fix**

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.METHOD, ElementType.TYPE, ElementType.CONSTRUCTOR })
public @interface Generated {}
```

##### **JHipster Version(s)**

Current master

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jsone-studios** [comment]
I am going to work on this issue.

**Comment by pascalgrimaud** [comment]
thanks @jsone-studios

**Comment by vishal423** [comment]
@pascalgrimaud, do you have any specific reason to restrict to Java and not include the frontend code? Can't we differentiate via git log?

**Comment by pascalgrimaud** [comment]
@vishal423 :
- we can include the frontend too, but can be done in another ticket. But what do you propose for the frontend code ? A comment ?
- we could with `git log`, but the benefits of using this annotation:
    - it's faster to see it : you think twice before modifying it
    - you can exclude the generated code from Sonar, to analyze your business code only
    - etc
