### ISSUE TITLE
Vue: webpack logs

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12451]
##### **Overview of the issue**

When start a Vue.js application in dev, the webpack log is too verbose

##### **Motivation for or Use Case**

see the full logs:

```
[INFO] > jhipster@0.0.0 webpack /home/pgrimaud/tmp/06-vue
[INFO] > node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--progress" "--profile"
[INFO] 
[INFO] <s> [webpack.Progress] 0% compiling
[INFO] <s> [webpack.Progress] 10% building 0/0 modules 0 active 
[INFO] <s> [webpack.Progress] 10% building 0/0 modules 0 active 
[INFO] <s> [webpack.Progress] 10% building 0/0 modules 0 active 
[INFO] <s> [webpack.Progress] 10% building 0/1 modules 1 active /home/pgrimaud/tmp/06-vue/node_modules/ts-loader/index.js??ref--1-0!/home/pgrimaud/tmp/06-vue/src/main/webapp/app/main.ts
[INFO] <s> [webpack.Progress] 10% building 0/2 modules 2 active /home/pgrimaud/tmp/06-vue/node_modules/vue-style-loader/index.js!/home/pgrimaud/tmp/06-vue/node_modules/css-loader/dist/cjs.js??ref--9-1!/home/pgrimaud/tmp/06-vue/node_modules/postcss-loader/src/index.js??ref--9-2!/home/pgrimaud/tmp/06-vue/node_modules/sass-loader/dist/cjs.js??ref--9-3!/home/pgrimaud/tmp/06-vue/src/main/webapp/content/scss/global.scss
[INFO] <s> [webpack.Progress] 10% building 1/2 modules 1 active /home/pgrimaud/tmp/06-vue/node_modules/ts-loader/index.js??ref--1-0!/home/pgrimaud/tmp/06-vue/src/main/webapp/app/main.ts
[INFO] <s> [webpack.Progress] 10% building 1/3 modules 2 active /home/pgrimaud/tmp/06-vue/node_modules/css-loader/dist/cjs.js??ref--9-1!/home/pgrimaud/tmp/06-vue/node_modules/postcss-loader/src/index.js??ref--9-2!/home/pgrimaud/tmp/06-vue/node_modules/sass-loader/dist/cjs.js??ref--9-3!/home/pgrimaud/tmp/06-vue/src/main/webapp/content/scss/global.scss
[INFO] <s> [webpack.Progress] 10% building 2/3 modules 1 active /home/pgrimaud/tmp/06-vue/node_modules/css-loader/dist/cjs.js??ref--9-1!/home/pgrimaud/tmp/06-vue/node_modules/postcss-loader/src/index.js??ref--9-2!/home/pgrimaud/tmp/06-vue/node_modules/sass-loader/dist/cjs.js??ref--9-3!/home/pgrimaud/tmp/06-vue/src/main/webapp/content/scss/global.scss
[INFO] <s> [webpack.Progress] 30% building 2/3 modules 1 active /home/pgrimaud/tmp/06-vue/node_modules/css-loader/dist/cjs.js??ref--9-1!/home/pgrimaud/tmp/06-vue/node_modules/postcss-loader/src/index.js??ref--9-2!/home/pgrimaud/tmp/06-vue/node_modules/sass-loader/dist/cjs.js??ref--9-3!/home/pgrimaud/tmp/06-vue/src/main/webapp/content/scss/global.scss
[INFO] <s> [webpack.Progress] 30% building 2/4 modules 2 active /home/pgrimaud/tmp/06-vue/node_modules/vue-style-loader/lib/addStylesClient.js
[INFO] <s> [webpack.Progress] 30% building 2/5 modules 3 active /home/pgrimaud/tmp/06-vue/node_modules/vue-style-loader/index.js!/home/pgrimaud/tmp/06-vue/node_modules/css-loader/dist/cjs.js??ref--9-1!/home/pgrimaud/tmp/06-vue/node_modules/postcss-loader/src/index.js??ref--9-2!/home/pgrimaud/tmp/06-vue/node_modules/sass-loader/dist/cjs.js??ref--9-3!/home/pgrimaud/tmp/06-vue/src/main/webapp/content/scss/vendor.scss
[INFO] <s> [webpack.Progress] 30% building 3/5 modules 2 active /home/pgrimaud/tmp/06-vue/node_modules/vue-style-loader/lib/addStylesClient.js
[INFO] <s> [webpack.Progress] 30% building 3/6 modules 3 active /home/pgrimaud/tmp/06-vue/node_modules/css-loader/dist/cjs.js??ref--9-1!/home/pgrimaud/tmp/06-vue/node_modules/postcss-loader/src/index.js??ref--9-2!/home/pgrimaud/tmp/06-vue/node_modules/sass-loader/dist/cjs.js??ref--9-3!/home/pgrimaud/tmp/06-vue/src/main/webapp/content/scss/vendor.scss
(...)
[INFO] 
[INFO] Hash: 4cb4e4e49929c0630f1b
[INFO] Version: webpack 4.43.0
[INFO] Time: 8796ms
[INFO] Built at: 2020-09-06 18:37:05
```

##### **Reproduce the error**

- generate a Vue.js application
- start it in dev: ./mvnw

##### **Suggest a Fix**

Change configuration for webpack in package.json

##### **JHipster Version(s)**

Current master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "6.10.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": ["cypress"],
    "pages": [],
    "creationTimestamp": 1599409665813,
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "io.github.pascalgrimaud",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "clientTheme": "cerulean",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "io/github/pascalgrimaud",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "useSass": true,
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

git version 2.28.0

node: v12.18.3

npm: 6.14.6

yeoman: 3.1.1

yarn: 1.22.5

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.2, build a133471

**Comment by chelfe** [comment]
i take this ticket

**Comment by pascalgrimaud** [comment]
I assign the ticket to you @chelfe

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/generator-jhipster/pull/12505
