### ISSUE TITLE
Faker data: not correct for duration

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12465]
##### **Overview of the issue**

When generating project with entities having duration, the faker data is not correct : so nothing is displayed

##### **Motivation for or Use Case**

The faker data should be correct for duration

##### **Reproduce the error**

- generate project
- generate entity with duration
- start the app
- go to the entity
- nothing is displayed for duration column

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ThomasCarca** [comment]
@pascalgrimaud I will take this one

**Comment by mraible** [comment]
@ThomasCarca Any progress to report?

**Comment by DanielFran** [comment]
Can someone confirm this has been fixed with #12427 and #12516 can be closed too?
