### ISSUE TITLE
Annotation for Integration Test

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12460]
##### **Overview of the issue**

The list of current annotations used in Integration Test are long and repetitive.
It could be replaced by 1 annotation defined somewhere.

##### **Motivation for or Use Case**

Easy for maintenance in our templates.
Easy to use for real development

##### **Reproduce the error**

- generate a JHipster application, which needs a specific Spring context with testcontainers for Integration tests
    - Cassandra
    - Kafka
    - Redis
    - Neo4j
    - Oauth2
- look at integration tests

##### **Suggest a Fix**

Define IntegrationTest, something like that (depending on configuration):

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@SpringBootTest(classes = { Jhneo4JApp.class, TestSecurityConfiguration.class })
@ExtendWith(RedisTestContainerExtension.class)
@ExtendWith(AbstractNeo4jIT.class)
public @interface IntegrationTest {}
```

Then, replace this complex block and import:

```java
@SpringBootTest(classes = { Jhneo4JApp.class, TestSecurityConfiguration.class })
@ExtendWith(RedisTestContainerExtension.class)
@ExtendWith(AbstractNeo4jIT.class)
```

by:

```java
@IntegrationTest
```

or

```java
@ApplicationNameIntTest
```

##### **JHipster Version(s)**

Current master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhneo4j",
    "jhipsterVersion": "6.10.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": ["cypress"],
    "pages": [],
    "creationTimestamp": 1599431596008,
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "oauth2",
    "packageName": "io.github.pascalgrimaud",
    "serverPort": "8080",
    "cacheProvider": "redis",
    "databaseType": "neo4j",
    "buildTool": "maven",
    "serverSideOptions": ["messageBroker:kafka"],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": "kafka",
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "io/github/pascalgrimaud",
    "devDatabaseType": "neo4j",
    "prodDatabaseType": "neo4j",
    "enableHibernateCache": false,
    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

git version 2.28.0

node: v12.18.3

npm: 6.14.6

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.2, build a133471

**Comment by swarajsaaj** [comment]
@pascalgrimaud  Can I pick this up?

I can try this one as below:-
1. Create a New AppIntegrationTest.java annotation in ***/generators/server/templates/src/test/java/package***
2. Decorate this annotation class with all conditional templates in other ITs.
3. Use this annotation in other ITs.

Please let me know if I am missing something, as its my first contribution in Jhupster.

**Comment by pascalgrimaud** [comment]
@swarajsaaj : yes you're welcome for your 1st contribution, and we'll try to help you :)
Just one important thing:
- there will be logic inside this AppIntegrationTest, specially when it's OAuth2, Kafka, Redis, etc...

**Comment by souleymatoo** [comment]
@pascalgrimaud and @swarajsaaj 
i already create an pull request for this issue.
Sorry for not asking before start.

@pascalgrimaud  should i dropped it ?

**Comment by pascalgrimaud** [comment]
@souleymatoo : no, we should not drop your work. But it would be nice if @swarajsaaj can review and test your PR, so it will be  "team work" :)

**Comment by swarajsaaj** [comment]
@pascalgrimaud Definitely :) I can follow along the PR. @souleymatoo Please proceed with the PR.

**Comment by pascalgrimaud** [comment]
PR is in progress

**Comment by pascalgrimaud** [comment]
As there is no progress since, I'm adding a bounty on this, if it can motivate people.
@souleymatoo : any progress on your pull request ?
@swarajsaaj : if no answer, do you want to go on the work plz ?

If someone else wants to take the lead here, don't hesitate

**Comment by swarajsaaj** [comment]
@pascalgrimaud yes I can take it up if there is no progress on existing PR

**Comment by pascalgrimaud** [comment]
Thanks @swarajsaaj : I think the PR here is already in a good progress https://github.com/jhipster/generator-jhipster/pull/12637 but there are still some issue.
Feel free to start your work from here, or start another one.

I could increase the bounty later if @souleymatoo will be back and if you used his work, no worry about that ;)

**Comment by swarajsaaj** [comment]
Hi @pascalgrimaud , I took some motivation from existing PR and raised #13249 with the fix. I have not included `@ExtendWith(AbstractNeo4jIT.class)` (and other database related extensions) in the common annotation as I think it may slow down the tests that do not require a database interaction, should I create a separate annotation (maybe separate PR) like `@PersistenceIntegrationTest` to include the conditional logic of Neo4J, Cassandra and SQL extensions? What do you suggest?

**Comment by pascalgrimaud** [comment]
@swarajsaaj : thanks for your work

Then, I don't understand well why you didn't include AbstractNeo4jIT with a condition like you did for Redis for example. In a Neo4j project, all integration tests needs AbstractNeo4jIT as it will start a Spring Context for tests with the database. I don't think it will change something as it will be the same as today.

About Cassandra, it's different, as it doesn't implement BeforeAllCallback. We should do the change one day, but as we have very few uses of Cassandra, it's not so important today.

**Comment by swarajsaaj** [comment]
@pascalgrimaud : Thanks for quick response.
My confusion arose from `ExceptionTranslatorIT ` class, currently there is no inclusion of `AbstractNeo4jIT` in this integration test, but now I think it should be added, else its failing.

**Comment by swarajsaaj** [comment]
@pascalgrimaud added `AbstractNeo4jIT` and `ReactiveSqlTestContainerExtension` to the base annotation. Requesting review.
