### ISSUE TITLE
Sonar: Replace this "String" wrapper object with primitive type "string"

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#12467]
##### **Overview of the issue**

Sonar issue in duration.pipe.ts.ejs

##### **Motivation for or Use Case**

Minor Sonar issue
 
##### **Reproduce the error**

- Generate a project with Angular like framework.
- Start Sonar `docker-compose -f src/main/docker/sonar.yml up -d`
- Launch analysis `./mvnw -Pprod clean verify sonar:sonar`

![image](https://user-images.githubusercontent.com/9989211/92623664-d9381880-f2c6-11ea-9524-c85bd0c5547b.png)

##### **Suggest a Fix**

Replace String by string in duration.pipe.ts.ejs

##### **JHipster Version(s)**

Current version

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ThomasCarca** [comment]
@pascalgrimaud I'll handle this one :)
