### ISSUE TITLE
Warning in dependencies

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12461]
##### **Overview of the issue**

When starting an application, there are some warnings about dependencies

##### **Motivation for or Use Case**

Try to reduce / fix these warnings

##### **Reproduce the error**

- generate an application
- start it

```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-dependencyConvergence) @ burger ---
[WARNING] 
Dependency convergence error for org.apache.commons:commons-compress:1.20 paths to dependency are:
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.testcontainers:mysql:1.14.3
    +-org.testcontainers:jdbc:1.14.3
      +-org.testcontainers:database-commons:1.14.3
        +-org.testcontainers:testcontainers:1.14.3
          +-org.apache.commons:commons-compress:1.20
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-loader-tools:2.3.3.RELEASE
    +-org.apache.commons:commons-compress:1.19

[WARNING] 
Dependency convergence error for org.wildfly.common:wildfly-common:1.5.2.Final paths to dependency are:
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-undertow:2.3.3.RELEASE
    +-io.undertow:undertow-core:2.1.3.Final
      +-org.jboss.xnio:xnio-api:3.8.0.Final
        +-org.wildfly.common:wildfly-common:1.5.2.Final
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-undertow:2.3.3.RELEASE
    +-io.undertow:undertow-core:2.1.3.Final
      +-org.jboss.xnio:xnio-api:3.8.0.Final
        +-org.wildfly.client:wildfly-client-config:1.0.1.Final
          +-org.wildfly.common:wildfly-common:1.2.0.Final

[WARNING] 
Dependency convergence error for org.apiguardian:apiguardian-api:1.1.0 paths to dependency are:
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-test:2.3.3.RELEASE
    +-org.junit.jupiter:junit-jupiter:5.6.2
      +-org.junit.jupiter:junit-jupiter-api:5.6.2
        +-org.apiguardian:apiguardian-api:1.1.0
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-test:2.3.3.RELEASE
    +-org.junit.jupiter:junit-jupiter:5.6.2
      +-org.junit.jupiter:junit-jupiter-api:5.6.2
        +-org.junit.platform:junit-platform-commons:1.6.2
          +-org.apiguardian:apiguardian-api:1.1.0
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-test:2.3.3.RELEASE
    +-org.junit.jupiter:junit-jupiter:5.6.2
      +-org.junit.jupiter:junit-jupiter-params:5.6.2
        +-org.apiguardian:apiguardian-api:1.1.0
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-test:2.3.3.RELEASE
    +-org.junit.jupiter:junit-jupiter:5.6.2
      +-org.junit.jupiter:junit-jupiter-engine:5.6.2
        +-org.apiguardian:apiguardian-api:1.1.0
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-com.tngtech.archunit:archunit-junit5-engine:0.14.1
    +-com.tngtech.archunit:archunit-junit5-engine-api:0.14.1
      +-org.junit.platform:junit-platform-engine:1.6.2
        +-org.apiguardian:apiguardian-api:1.1.0
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.2
    +-org.zalando:problem-violations:0.25.2
      +-org.apiguardian:apiguardian-api:1.1.0
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.2
    +-org.zalando:problem-spring-common:0.25.2
      +-org.apiguardian:apiguardian-api:1.1.0
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.2
    +-org.apiguardian:apiguardian-api:1.1.0
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.2
    +-org.zalando:problem:0.23.0
      +-org.apiguardian:apiguardian-api:1.0.0
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.2
    +-org.zalando:jackson-datatype-problem:0.23.0
      +-org.apiguardian:apiguardian-api:1.0.0
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.2
    +-org.zalando:faux-pas:0.8.0
      +-org.apiguardian:apiguardian-api:1.0.0

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
```

##### **JHipster Version(s)**

Current master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "burger",
    "jhipsterVersion": "6.10.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1599432243998,
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "io.github.pascalgrimaud",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "io/github/pascalgrimaud",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

git version 2.28.0

node: v12.18.3

npm: 6.14.6

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.2, build a133471

**Comment by mikrethor** [comment]
I looked a bit into it and I would advise not to try to manage version in jhipster.

For me the projects that bring those version should be modified.

problem-spring-web brings : 
 - +-org.apiguardian:apiguardian-api:1.1.0
 - +-org.apiguardian:apiguardian-api:1.0.0

spring-boot-starter-undertow brings : 
- +-org.wildfly.common:wildfly-common:1.5.2.Final
- +-org.wildfly.common:wildfly-common:1.2.0.Final

For commons-compress the latest version is brought by testcontainer (scope test) and the other by spring-boot-loader-tools so we could manage the version in jhipster put it could bring problem when migrating to another version of spring boot.

I am gonna look in zalando problem in order to be able to use org.apiguardian:apiguardian-api:1.1.0 all the way.

**Comment by mikrethor** [comment]
Actually I could correct it a bit by bumping problem-spring-web to 0.26.2

**Comment by mikrethor** [comment]
> Actually I could correct it a bit by bumping problem-spring-web to 0.26.2

It seems to be already done

**Comment by mikrethor** [comment]
about faux-pas 0.8.0 containing org.apiguardian:apiguardian-api:1.0.0 [see](https://github.com/zalando/faux-pas/issues/167)

**Comment by pascalgrimaud** [comment]
@Falydoor @DanielFran : can you have a look @atmikrethor 's comment plz ?
I'm reopening this ticket to not forget

**Comment by Falydoor** [comment]
Yes I agree with you @mikrethor, it would be definitely best to have the warnings fixed in the original dependencies but it might take longer depending on their release cycle. 

For 
```
[WARNING] 
Dependency convergence error for org.wildfly.common:wildfly-common:1.5.2.Final paths to dependency are:
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-undertow:2.3.3.RELEASE
    +-io.undertow:undertow-core:2.1.3.Final
      +-org.jboss.xnio:xnio-api:3.8.0.Final
        +-org.wildfly.common:wildfly-common:1.5.2.Final
and
+-io.github.pascalgrimaud:burger:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-undertow:2.3.3.RELEASE
    +-io.undertow:undertow-core:2.1.3.Final
      +-org.jboss.xnio:xnio-api:3.8.0.Final
        +-org.wildfly.client:wildfly-client-config:1.0.1.Final
          +-org.wildfly.common:wildfly-common:1.2.0.Final
```
 we can't even open an issue on `xnio-api` at https://github.com/xnio/xnio 😬.

**Comment by mikrethor** [comment]
Ok but it's just warning and handling the dependencies in Jhipster regardless of spring boot dependencies or calando management could cause bigger problems

**Comment by pascalgrimaud** [comment]
So what would be the best ?
Do you think we should revert https://github.com/jhipster/jhipster/pull/861/ @mikrethor ?

**Comment by DanielFran** [comment]
I introduced the warning of dependency in both jhipster bom and generator projects, in the past, this was not visible.
I added it just to inform users that they might need to manage the dependencies in the project, because is too difficult to manage them on both jhipster bom and generator (too much combination).

I would prefer that this is managed directly on the source, otherwise, when updating dependencies It is needed to review it again.

**Comment by mikrethor** [comment]
For me it should be reverted

**Comment by DanielFran** [comment]
@pascalgrimaud If you agree then we should revert it.
Thanks

**Comment by pascalgrimaud** [comment]
Yes, agree @DanielFran 
as these warnings doesn't come from our side, it's better to let like this, as suggested by @mikrethor
