### ISSUE TITLE
Swagger: disable or remove try it button

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12464]
##### **Overview of the issue**

When using Swagger, the `try it` button is annoying.
It would be nice if we can remove it and use directly the API, instead of clicking `try it` before

##### **Motivation for or Use Case**

Better UX for dev, no need to click try it, then execute...

##### **Reproduce the error**

- generate a JHipster project
- start it
- go to swagger
- play with API

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by thri33** [comment]
@deepu105 I take this ticket

**Comment by pascalgrimaud** [comment]
I assign the ticket to you @thri33

**Comment by nonomoho** [comment]
I found something, I create a PR.

**Comment by cbornet** [comment]
Another solution I've used in a project is to set tryItOutEnabled to true by default in swagger-ui but that requires to build swagger-ui:

https://github.com/swagger-api/swagger-ui/blob/12ccab79d2df670d7157d23c38eb938f868d3f6f/src/core/containers/OperationContainer.jsx#L11

**Comment by nonomoho** [comment]
Yes, I don't know what's the best.

**Comment by deepu105** [comment]
Since this hack is on the swagger html files and similar to other hacks we already do, IMO its good enough.
