### ISSUE TITLE
Sonar: Remove this unused import of 'Validators'

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#12468]
##### **Overview of the issue**

Sonar issue in the file `generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs`
Import `Validators` should not be in the file for some configurations

##### **Motivation for or Use Case**

Minor Sonar issue

##### **Reproduce the error**

- Generate a project with Angular like framework.
- Start Sonar `docker-compose -f src/main/docker/sonar.yml up -d`
- Launch analysis `./mvnw -Pprod clean verify sonar:sonar`

![image](https://user-images.githubusercontent.com/9989211/92628689-7d24c280-f2cd-11ea-9561-9ed138d55893.png)

##### **Suggest a Fix**

Add conditions on `Validators` to display or not this import.

##### **JHipster Version(s)**

Current version

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ThomasCarca** [comment]
@deepu105 I'll take this one

**Comment by pascalgrimaud** [comment]
Thanks @ThomasCarca : I assign the ticket to you
