### ISSUE TITLE
Documentation: typo

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#12469]
##### **Overview of the issue**

There is a typo in the file `CONTRIBUTING.md`. Indeed there is an **extra space**.

##### **Motivation for or Use Case**

Better documentation

##### **Reproduce the error**

- Go on this page: https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md
- Look the line `correct with the following command :`

##### **Suggest a Fix**

Replace `correct with the following command :` by `correct with the following command:`

##### **JHipster Version(s)**

Current version

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Virginiw** [comment]
hello, available to work on this !

**Comment by pascalgrimaud** [comment]
Thanks a lot @Virginiw : I assign the ticket to you
