### ISSUE TITLE
Angular: improve UI for checkbox

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12463]
##### **Overview of the issue**

When using Angular, the checkbox for entities is not nice

##### **Motivation for or Use Case**

Improve UI

##### **Reproduce the error**

- generate a project with Angular
- generate an entity with boolean
- start the app
- log in
- go to entity
- edit one of them
- see the checkbox

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by bengaid** [comment]
@deepu105

**Comment by pascalgrimaud** [comment]
Thanks @bengaid !
