### ISSUE TITLE
Angular: improve view entities

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12462]
##### **Overview of the issue**

Improve "view entities" / "view user management"

##### **Reproduce the error**

- generate a project with Angular
- go to user-management
- go to view user
- it's not similar to Vue, as the alignment is not nice
- same for entities

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@pascalgrimaud I take this one :)
