### ISSUE TITLE
Cypress: headless only in CI, not in local

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12466]
##### **Overview of the issue**

When using cypress locally, it should be nice to not start it in headless mode
The headless mode should only be for the CI

##### **Motivation for or Use Case**

Better demo

##### **Reproduce the error**

- generate jhipster project with Cypress
- start the app
- start cypress

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Hawkurane** [comment]
Hello, can I take this?

Also what command should we use for the non-headless mode?

- Change npm run e2e to a non-headless mode and run a npm run e2e:headless in the CI?
- Keep npm run e2e as headless, create a non-headless mode (e.g. npm run e2e:local)

**Comment by Hawkurane** [comment]
hi @pascalgrimaud I've claimed the bounty: https://opencollective.com/generator-jhipster/expenses/25299

**Comment by pascalgrimaud** [comment]
@Hawkurane : approved
