### ISSUE TITLE
Sonar: Remove this unused import of 'Vue'

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#12470]
##### **Overview of the issue**

Sonar issue in the files: 
`generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs`

`Vue` from `vue-property-decorator` should not be imported.

##### **Motivation for or Use Case**

Minor Sonar issue

##### **Reproduce the error**

- Generate a project with Vue like framework.
- Start Sonar `docker-compose -f src/main/docker/sonar.yml up -d`
- Launch analysis `./mvnw -Pprod clean verify sonar:sonar`

![image](https://user-images.githubusercontent.com/9989211/92699039-645bf180-f34d-11ea-811a-351b20cbe382.png)

##### **Suggest a Fix**

Remove `Vue` from this line `import { Component, Vue, Inject } from 'vue-property-decorator';`.

##### **JHipster Version(s)**

Current version

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
fixed by https://github.com/jhipster/generator-jhipster/pull/12508
