### ISSUE TITLE
Sonar: Remove this unused import

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#12471]
##### **Overview of the issue**

Sonar issue in the file:
`generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs`

`numeric` `required` `minLength` `maxLength` `minValue` `maxValue` are imported by default, but we need to be smart and check first if there are useful. In this case, we can import them.
 
##### **Motivation for or Use Case**

Minor Sonar issue

##### **Reproduce the error**

- Generate a project with **Vue** like framework.
- Start **Sonar** `docker-compose -f src/main/docker/sonar.yml up -d`
- Launch analysis `./mvnw -Pprod clean verify sonar:sonar`

![image](https://user-images.githubusercontent.com/9989211/92701084-dd5c4880-f34f-11ea-8ef3-369e9291e523.png)

##### **Suggest a Fix**

Add some `if` to import `numeric` `required` `minLength` `maxLength` `minValue` `maxValue` only when there are useful.

##### **JHipster Version(s)**

Current version

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by thri33** [comment]
I take this ticket

**Comment by pascalgrimaud** [comment]
Thanks @thri33 : I assign the ticket to you !
