### ISSUE TITLE
Sonar: Remove this useless assignment to variable "locale"

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#12472]
##### **Overview of the issue**

Sonar issue in the file:
`generators/client/templates/react/src/main/webapp/app/shared/DurationFormat.tsx.ejs`

The line `locale = TranslatorContext.context.locale;` seems to be useless.

##### **Motivation for or Use Case**

Minor Sonar issue

##### **Reproduce the error**

- Generate a project with **React** like framework.
- Start **Sonar** `docker-compose -f src/main/docker/sonar.yml up -d`
- Launch analysis `./mvnw -Pprod clean verify sonar:sonar`

![image](https://user-images.githubusercontent.com/9989211/92707157-5b6f1e00-f355-11ea-8589-ae381dc43359.png)

##### **Suggest a Fix**

Delete the line `locale = TranslatorContext.context.locale;`

##### **JHipster Version(s)**

Current version

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SoniaLahi** [comment]
i take this ticket

**Comment by pascalgrimaud** [comment]
thanks @SoniaLahi : I assign the ticket to you

**Comment by SoniaLahi** [comment]
This sonar error highlights a bug. The real problem is here is that the locale is not used when calling the moment method. 

The condition actually makes sense ans should be kept as it is.
