### ISSUE TITLE
Sonar: Remove this unused import of 'FontAwesomeIcon'

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#12473]
##### **Overview of the issue**

Sonar issue in the file:
`generators/client/templates/react/src/main/webapp/app/shared/layout/menus/account.tsx.ejs`

`FontAwesomeIcon` is imported by default, but we need to be smart and check first if there is useful. In this case, we can import it.

##### **Motivation for or Use Case**

Minor Sonar issue

##### **Reproduce the error**

- Generate a project with **React** like framework.
- Start **Sonar** docker-compose -f src/main/docker/sonar.yml up -d
- Launch analysis ./mvnw -Pprod clean verify sonar:sonar

![image](https://user-images.githubusercontent.com/9989211/92708319-51015400-f356-11ea-9bbc-eaa2da55cf9a.png)

##### **Suggest a Fix**

Add condition on the import `import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';`

##### **JHipster Version(s)**

Current version

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ThomasCarca** [comment]
@deepu105 I'll be taking this one
