### ISSUE TITLE
Java: WebConfigurerTest.java import unused

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#12477]
##### **Overview of the issue**

In the file `generators/server/templates/src/test/java/package/config/WebConfigurerTest.java.ejs`:
the import `import io.github.jhipster.web.filter.CachingHttpHeadersFilter;` is useless.

##### **Motivation for or Use Case**

Import useless

##### **Reproduce the error**

- Generate an application
- Look the file `WebConfigurerTest.java`

##### **Suggest a Fix**

Remove this lines:
```
<%_ if (!skipClient) { _%>
import io.github.jhipster.web.filter.CachingHttpHeadersFilter;
<%_ } _%>
``` 

##### **JHipster Version(s)**

Current version

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ThomasCarca** [comment]
@pascalgrimaud I'll handle this one
