### ISSUE TITLE
Multiple columns in an entity with foreign key references to same remote entity

### ISSUE THREAD

**Issue by gvsrini** [jhipster/generator-jhipster#1248]
A table can contain two (or more) columns (like FROM_USER and TO_USER), both of them being foreign keys to the same remote (USER) entity.

This seems to be not possible in the current version of entity generator.

**Comment by gzsombor** [comment]
No, it's supported. You can create multiple relations between the same entities, you just have to specify different names for them.

**Comment by jdubois** [comment]
@gzsombor is correct (and should be, he's the one who coded this!)
