### ISSUE TITLE
DevBox: upgrade to Ubuntu 20.04

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12488]
##### **Overview of the issue**

Our currrent [devbox](https://github.com/jhipster/jhipster-devbox) uses Ubuntu 18.04
It would be cool to upgrade to Ubuntu 20.04

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SoniaLahi** [comment]
I would like to work on this one :)

**Comment by SudharakaP** [comment]
@SoniaLahi : Thanks. I've assigned you the issue. 👍🏼

**Comment by DanielFran** [comment]
@jdubois @pascalgrimaud Does [devbox](https://github.com/jhipster/jhipster-devbox) still used nowadays?

Latest [vagrant](https://app.vagrantup.com/jhipster/boxes/jhipster-devbox) image available is from version 5.8.2?

Should we keep this project @jhipster/developers ?

**Comment by pascalgrimaud** [comment]
let's close this ticket

**Comment by jdubois** [comment]
Indeed I wanted to deprecate the DevBox as today you have better options, but someone volunteered to maintain it…. If he doesn’t, we should deprecate it.

**Comment by DanielFran** [comment]
> @DanielFran : I don't know at all if it's used today
> 
> But there is 2 things:
> 
>     * the publish to vagrant: it's not done today and I don't know how to do it, but who cares?
> 
>     * the release + tag in the project, so if the user wants to build the vagrant image, he/she can -> we can still continue to maintain this part, as it's easy to change the version, tag et push

@pascalgrimaud Yes, I know you always update the generator version, but it needs to be updated, like ubuntu, pgadmin,...


> Indeed I wanted to deprecate the DevBox as today you have better options, but someone volunteered to maintain it…. If he doesn’t, we should deprecate it.

@jdubois who is maintaining it?

**Comment by jdubois** [comment]
Nobody is maintaining it anymore, and I don’t want to push anyone into doing this.
This is a dead technology now that we have DevContainers.

**Comment by pascalgrimaud** [comment]
So let's archive this project
