### ISSUE TITLE
Java: UserJWTControllerIT.java import unused

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#12482]
##### **Overview of the issue**

In the file `generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs`:
the import `import org.springframework.test.web.servlet.setup.MockMvcBuilders;` is useless.

##### **Motivation for or Use Case**

Import useless

##### **Reproduce the error**

- Generate an application
- Look the file `UserJWTControllerIT.java`

##### **Suggest a Fix**

Remove this line:
``` 
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
``` 

##### **JHipster Version(s)**

Current version

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Virginiw** [comment]
May I take this issue ?

**Comment by pascalgrimaud** [comment]
Ok @Virginiw : I assign the ticket to you
