### ISSUE TITLE
JHCC: add missing badges in README

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12483]
##### **Overview of the issue**

Add missing badges in README:
- GitHub builds
- Sonar analyze
- Docker Hub with Docker images (similar to jhipster-registry)

##### **Motivation for or Use Case**

So we can know the state of build, Sonar, etc

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by chelfe** [comment]
i take this ticket

**Comment by pascalgrimaud** [comment]
thanks @chelfe ! I assign the ticket to you
