### ISSUE TITLE
Move jib folder

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12486]
##### **Overview of the issue**

In `src/main` folder, we have:
- docker
- java
- jib
- resources
- webapp

I think we can move jib to docker folder, as jib contains just 1 file, and is probably not used in all projects

##### **Motivation for or Use Case**

Reduce the number of folders in `src/main`

##### **Reproduce the error**

Generate a project, look in `src/main`

##### **Suggest a Fix**

Don't forget to test with maven and gradle

##### **JHipster Version(s)**

master

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SoniaLahi** [comment]
I would like to take this ticket please :smiley:

**Comment by pascalgrimaud** [comment]
ok @SoniaLahi : I assign this ticket to you
