### ISSUE TITLE
Add new artwork

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12487]
##### **Overview of the issue**

It would be so cool to have new artwork
Don't hesitate to add at https://github.com/jhipster/jhipster-artwork

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ascelineboullen** [comment]
@pascalgrimaud , I'm on it ! :)

**Comment by pascalgrimaud** [comment]
thanks @ascelineboullen !

**Comment by mraible** [comment]
@ascelineboullen Any updates?

**Comment by ascelineboullen** [comment]
@mraible , yes, I'm still on it, I will be able to send you proposals this weekend :)

**Comment by ascelineboullen** [comment]
I just openned a PR, 
https://github.com/jhipster/jhipster-artwork/pull/9
If everything it's ok for you, about process, about format, about resolution, etc, I will open other PR, because I working on differents members family proposals :D @mraible @pascalgrimaud

**Comment by jdubois** [comment]
It looks really cool!

**Comment by pascalgrimaud** [comment]
love it ! <3

**Comment by deepu105** [comment]
Pr merged. @ascelineboullen plz claim the bounty

**Comment by pascalgrimaud** [comment]
@deepu105 : I think there are some new artworks soon too ;)

**Comment by pascalgrimaud** [comment]
Thanks @ascelineboullen for the new artwork ! +1 from me
I'll let another team member to check too and validate :)

**Comment by ascelineboullen** [comment]
Thank you everybody! _I claimed the bounty (https://opencollective.com/generator-jhipster/expenses/26282) for this issue (cc @pascalgrimaud @deepu105 @jdubois), with this PR https://github.com/jhipster/jhipster-artwork/pull/14 https://github.com/jhipster/jhipster-artwork/pull/13 https://github.com/jhipster/jhipster-artwork/pull/12 https://github.com/jhipster/jhipster-artwork/pull/11 https://github.com/jhipster/jhipster-artwork/pull/9 _
But as soon as I have some time and inspiration, I would be happy to create more illustrations members! 😄 . 
If you have any ideas, don't hesitate! 🙏

**Comment by pascalgrimaud** [comment]
@ascelineboullen : approved ! thanks a lot, really nice work !

**Comment by nicolas63** [comment]
> 
> 
> **Thank you everybody!**
> _I claimed the bounty (https://opencollective.com/generator-jhipster/expenses/26282) for this issue #12487 (cc @pascalgrimaud @deepu105 @jdubois),_
> 
> _with this PRs [jhipster/jhipster-artwork#14](https://github.com/jhipster/jhipster-artwork/pull/14), [jhipster/jhipster-artwork#13](https://github.com/jhipster/jhipster-artwork/pull/13), [jhipster/jhipster-artwork#12](https://github.com/jhipster/jhipster-artwork/pull/12), [jhipster/jhipster-artwork#11](https://github.com/jhipster/jhipster-artwork/pull/11), [jhipster/jhipster-artwork#9](https://github.com/jhipster/jhipster-artwork/pull/9)_
> 
> But as soon as I have some time and inspiration, I would be happy to create more illustrations members! 😄 .
> If you have any ideas for news members, **don't hesitate to tell me**! 🙏

@ascelineboullen your work is very awesome! I'm interesting if you have any ideas for the dotnetcore blueprint (https://github.com/jhipster/jhipster-dotnetcore)

**Comment by ascelineboullen** [comment]
Thank you @nicolas63 ! 😄 
I will think about it for the next Illustation

**Comment by pascalgrimaud** [comment]
Most of work has been done, and the bounty claimed too.
I'm closing this, but if you want to work on new artworks, plz open a new ticket :)

**Comment by ascelineboullen** [comment]
Yes, thank you @pascalgrimaud ;)
