### ISSUE TITLE
JDL: Provide JDL keywords as an API

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#12495]
Provide an API to replace the keyword and stuff in https://github.com/jhipster/jdl-studio/blob/v2/src/codemirror/CodemirrorJDLMode.ts

**Comment by mraible** [comment]
Sometimes simple is better. Do we really need this? I'd rather update a file than have to modify a service and figure out how to redeploy it!

**Comment by deepu105** [comment]
Well its not really needed but good to have. But with JDL parser I believe its easier to generate this and I believe @MathieuAA wanted to do it but ya current way of updating file is also good enough.

**Comment by DanielFran** [comment]
@mshima with the latest improvements, do we have a jdl keywords API available?

**Comment by mshima** [comment]
Need to be exported, may require some changes.
jhipster-base?

**Comment by DanielFran** [comment]
@mshima @deepu105 with latest changes on main generator jdl is now exported.
Can this be closed?

**Comment by deepu105** [comment]
Not really @DanielFran I'm working on using the current package in JDL studio so this can be closed when that's done as part of #22841
