### ISSUE TITLE
Number of values in a drop-down (foreign key) reference are limited to page size

### ISSUE THREAD

**Issue by gvsrini** [jhipster/generator-jhipster#1249]
I'm not sure if this is a bug or a configuration issue at my end. MY_TABLE contains a foreign key which has more than 20 records in the MASTER_TABLE. When I go to create a row in MY_TABLE, the drop down showing values of MASTER_TABLE is limited to PAGE_SIZE.

Is there any way, I can make it show ALL rows of the MASTER_TABLE?

**Comment by gzsombor** [comment]
I think, this is caused by the newly introduced paging mechanism.

**Comment by jdubois** [comment]
If you selected pagination, then there's indeed a page size limitation. On the client side, you can ask for more than the default page size, but still there will be upper limitation.
If you don't want that limitation:

- Don't use pagination at all
- Use pagination to get the next page (and do 2 requests)
- Use pagination and change the page size value to accept bigger requests
