### ISSUE TITLE
JDL: Improve parsed JSON

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#12494]
When using `jhipster-core/lib/dsl/api` to parse a JDL to JSON, provide the resolved entities in the application structure instead of included/excluded

Current:
```
{
  "applications": [
    {
      "config": {
        "baseName": "myApp",
        "applicationType": "gateway",
        "packageName": "com.myapp",
        "packageFolder": "com/myapp",
        "authenticationType": "jwt",
        "prodDatabaseType": "mysql",
        "clientFramework": "react"
      },
      "entities": { "entityList": ["*"], "excluded": [] },
      "options": {}
    }
  ]
}
```

Expected 
```
{
  "applications": [
    {
      "config": {
        "baseName": "myApp",
        "applicationType": "gateway",
        "packageName": "com.myapp",
        "packageFolder": "com/myapp",
        "authenticationType": "jwt",
        "prodDatabaseType": "mysql",
        "clientFramework": "react"
      },
      "entities": { 
          "entityList": ["A", "B", "C"]
      },
      "options": {}
    }
  ]
}
```

**Comment by mraible** [comment]
Added bug bounty to motivate @deepu105 to fix. :)

**Comment by deepu105** [comment]
Ha ha, Matt, you should know that I have claimed the least bounties (thats my way of saying bounties doesn't motivate me) 😂😂 I believe @MathieuAA was already working on this 😉

**Comment by MathieuAA** [comment]
I can't promise anything, based on my current unavailability to do stuff for JHipster... This issue is kinda easy to do.
The code already exists and there's no test to write, only to update.
I'll try to get it done this WE along with the user management stuff.

**Comment by MathieuAA** [comment]
The user management stuff has a PR, I'm working on this one.

**Comment by MathieuAA** [comment]
@deepu105 I'm gonna implement like this:
```json
{
  "applications": [
    {
      "config": {
        "baseName": "myApp",
        "applicationType": "gateway",
        "packageName": "com.myapp",
        "packageFolder": "com/myapp",
        "authenticationType": "jwt",
        "prodDatabaseType": "mysql",
        "clientFramework": "react"
      },
      "entities": ["A", "B", "C"],
      "options": {}
    }
  ]
}
```
The difference here is that `entities` isn't an object containing the entity list, but an array of entity names.
Is it okay for you?

**Comment by deepu105** [comment]
Yup. Works for me. I guess this will be a major version then

**Comment by MathieuAA** [comment]
Yup. I'll apply the changes to JCore tomorrow and release a major version
