### ISSUE TITLE
Name Convention Getter for "Boolean" and "boolean" is incorrect

### ISSUE THREAD

**Issue by MarlonLuan** [jhipster/generator-jhipster#12498]
##### **Overview of the issue**

In "User.java",

https://github.com/jhipster/generator-jhipster/blob/a91c744a3d093cb738825b369ab912325104c7f9/generators/server/templates/src/main/java/package/domain/User.java.ejs#L438

 following conventions the correct one should be 

```java
public boolean isActivated() {
```

In "LoginVM.java",
https://github.com/jhipster/generator-jhipster/blob/86a0ecdeca071ba4098d3a115f548841a821ab9e/generators/server/templates/src/main/java/package/web/rest/vm/LoginVM.java.ejs#L55

 following conventions the correct one should be 

```java
public Boolean getRememberMe() {
```
or change "Boolean" to primitive "boolean"

```java
public boolean isRememberMe() {
```

##### **Suggest a Fix**

- Change "Boolean" to "boolean"
or
- Follow convenction in method name

##### **JHipster Version(s)**

master

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
hi @MarlonLuan 
on which documentation do you based this information? (Boolean = getXXX and boolean = isXXX)?

**Comment by MarlonLuan** [comment]
- When select option "Generate Getter and Setter" in IDE (I tested the eclipse and Intellij) follows this pattern

- Lombok docs
https://projectlombok.org/features/GetterSetter

- Oracle javabeans spec
https://download.oracle.com/otn-pub/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/beans.101.pdf

8.3  Design Patterns for Properties
8.3.2 Boolean properties

**Comment by avdev4j** [comment]
So let's go, would you like to contribute to this ticket? We need to check if entity generator follow this pattern too.

**Comment by MarlonLuan** [comment]
Yes, you can assign it to me
