### ISSUE TITLE
Introduce gen.ignore behavior

### ISSUE THREAD

**Issue by fcauchois** [jhipster/generator-jhipster#12496]
##### **Overview of the feature request**

We want to be able to force generator to use pre-existant class. This will enable developers to use custom classes.

Why not using a ".gitignore way" of manage this behavior : .genignore
File content is just full classe name or package name (like import syntaxe)  to be ignore at generator runtime

.genignore :
*.ElasticSearchConfiguration
*.domain.EntityCustom*
*.service.MyCustomService

So before créating a file, the generator will check if package name don't match a .genignore entry. If so, generation is ignored.

##### **Motivation for or Use Case**

Generator don't allow custom code in generated code : no hook (other feature to follow :D), no inheritance (as side by side strategy, other feature to follow :D). So no custom code possibility at all. We just want a simple way to keep our custom code SAFE :D.

##### **Related issues or PR**

-   [ ]

**Comment by mshima** [comment]
@fcauchois this is not suitable for jhipster.
It should be implemented upstream (conflicter currently implemented at yeoman-generator, will be moved to yeoman-environment).
See https://github.com/jhipster/generator-jhipster/issues/12080

**Comment by MathieuAA** [comment]
@mshima hello! From what @fcauchois said, is there any other solution that you see that could solve the problem?

**Comment by Tcharl** [comment]
Can this option be reconsidered: gitignore has no merge, diff, bail, ... and it just works.
I think that overengineering the solution would be too complicated for our end users.
In the end, they just want to say: "please generator don't touch this"

**Comment by mshima** [comment]
Why not just skip?
`dry-run` will skip, but print diffs to console.
So you would have access to the diff, and analyze if you didn’t lost anything.
`force` would prevent to run `jhipster —force` every time.

**Comment by Tcharl** [comment]
What if we hack  `generator-base.js#writeFilesToDisk` ?

**Comment by mshima** [comment]
> What if we hack `generator-base.js#writeFilesToDisk` ?

@Tcharl why? Conflicter approach is easier and is the only approach that will work.
`writeFilesToDisk` is just a wrapper for others functions and they be used alone.

**Comment by mshima** [comment]
Looks like @jdubois announced this already 😆. https://twitter.com/jhipster/status/1305532865497780227?s=21 at 2:30.
So this is going to happen now.

**Comment by mshima** [comment]
Closing this in favor of https://github.com/jhipster/generator-jhipster/issues/12080.
The discussion there is deeper and better described.
