### ISSUE TITLE
Injecting custom code in generation process

### ISSUE THREAD

**Issue by fcauchois** [jhipster/generator-jhipster#12502]
##### **Overview of the feature request**

From the studio, or more precisely in jdl configuration file, we want to add hook syntaxe to allow custom code to be directly printed in generated code.

JDL hook syntaxe proposal :
```
@custom service
import `import xx.yy.MyAnnotationToBePlacedOnRegionServiceClassDecalration;`
class `@MyAnnotationToBePlacedOnRegionServiceClassDecalration(...)`
@custom entity
import `java.util.Math`
body `public double getRandom() {
  return Math.random();
}`
entity Region {
   regionName String
}

entity Country {
    @custom property
    import `import xx.zz.MyPropertyAnnotation`
  `@MyPropertyAnnotation`
  countryName String
}
```

@custom <type>
import ....
`` 

type : type of generated content. Can be java class, or Typescript class (as EntityComponent, etc) ? Every "type" must match a dedicated script. so everybody will be able to crate new one to fit their needs.
Every type of custom will specifc where the custom code can be printed
import : allow import need by custom code
`` custom code is a string backquoted, used "as it" (we just don't and don't want know its purpose)

Syntaxe variant proposal :

```
entity Region {
   regionName String
}
custom Region service {
  import `import xx.yy.MyAnnotationToBePlacedOnRegionServiceClassDecalration;`
  class Region `@MyAnnotationToBePlacedOnRegionServiceClassDecalration(...)`
}
custom Region entity {
  import `java.util.Math`
  append `public double getRandom() {
    return Math.random();
  }`
} 

entity Country {
  countryName String
}
custom Country service {
  import `import xx.zz.MyPropertyAnnotation`
  property countryName before `@MyPropertyAnnotation`
}
```

Do people need that (i do, hardly) ?
Can we do that in a JDL extension (as a blueprint) ?
With 2nd option, it allow to add those definition in a separated file so JDL sutdio stays clean...
What is the best syntaxe for you ? 

Next step : jdl studio extension coloration and graphical representation of custom hooks

##### **Motivation for or Use Case**

yeoman generator allow custom tasks thanks to hook : this is the way to allow everything, everywhere. We need it in JDL generation process to allow eveybody to add some custom code at the right place in generated code.

##### **Related issues or PR**

-   [ ] https://github.com/jhipster/generator-jhipster/issues/12496
-   [ ] https://github.com/jhipster/generator-jhipster/issues/12497

**Comment by deepu105** [comment]
What is the usecase for this? and how does this help? Isn't adding the custom code directly to generated code easier and more error proof? since anything added here can't be properly validated for syntax errors and such and parsing the JDL with this would be much more painful for us. I don't see the value for maintenance here. The only advantage I can see is when you upgrade an entity you can retain custom code, but that issue is already being explored in DDD design and such.

WDYT @MathieuAA

**Comment by MathieuAA** [comment]
Agreed. I understand the need but the solution isn't satisfactory for me. I'm still thinking about a proper solution for this issue, but I don't think there's an easy one.
