### ISSUE TITLE
Regenerating modified entity breaks liquibase change set

### ISSUE THREAD

**Issue by cmeyer1869** [jhipster/generator-jhipster#1250]
Regenerating an entity after changing its json config will also recreate the liquibase change set. However, deploying this change set in an existing system fails with a validation error, because it was already delpoyed with different content/hash.

The entity/liquibase subgenerator should create separate change sets on top of each other, to allow updating and deploying changed entities.

**Comment by jdubois** [comment]
I understand, but I don't think we can do anything here.

The normal workflow, if you want to change your entity, is to change it directly, and then use "mvn liquibase:diff" to have the changelog.

You could of course do that changelog by hand, that's how we used to do, and I still do it that way from time to time.
