### ISSUE TITLE
JavaBean methods are not correct when the first letter is lower case and the second letter is uppercase

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1251]
The data is not saved and there is no error message on the UI, seems like bean validation failure
Here is the *testEntity*, strangely if i use *tcap* instead of *tCap* in attribute name it works!
```
{
    "relationships": [],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "tCap",
            "fieldType": "String",
            "fieldNameCapitalized": "TCap",
            "fieldNameUnderscored": "t_cap",
            "fieldValidate": true,
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "fieldsContainOwnerManyToMany": false,
    "fieldsContainOneToMany": false,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": false,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": false,
    "fieldsContainDate": false,
    "changelogDate": "20150313034831",
    "pagination": "no",
    "validation": true
}
```
All files seems to generated properly

Here is the request payload in the PUT request from chrome console( Isnt the create request suppose to be POST? )
```
{tCap: "test", id: null}
```

Here is the error from console

```
error: "Bad Request"
exception: "org.springframework.web.bind.MethodArgumentNotValidException"
message: "Validation failed for argument at index 0 in method: public org.springframework.http.ResponseEntity<java.lang.Void> com.tcs.testapp.web.rest.TestEntityResource.update(com.tcs.testapp.domain.TestEntity) throws java.net.URISyntaxException, with 1 error(s): [Field error in object 'testEntity' on field 'tCap': rejected value [null]; codes [NotNull.testEntity.tCap,NotNull.tCap,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [testEntity.tCap,tCap]; arguments []; default message [tCap]]; default message [may not be null]] "
path: "/api/testEntitys"
status: 400
timestamp: 1426220537642
```

I'll try to debug and see whats happening when i find time from work

**Comment by jdubois** [comment]
- I can't reproduce
- Yes the HTTP PUT is correct for creating an entity
- We don't generate NotNull constraints on the ID, so you should not have this validation error
- We generate the "required" validation on the AngularJS field, so you shouldn't be able to do that request anyway

Did you change anything in the generated code?

**Comment by deepu105** [comment]
No, I didnt touch the code at all, yes required validation was on the angular JS side, the problem is even after filling data and submitting(you can see that data was in the PUT request for the field tCap) it gives this error in the console and data is not saved. So there is no way to save data from this form.

I tried again in a fresh project the same thing and same error appears.
I tried debugging but its not even reaching the REST resource error seems to be thrown even before that
BTW Im working on windows, does that make any change?

**Comment by jdubois** [comment]
OK, let me check again

**Comment by deepu105** [comment]
K this is weird, the issue arises only if my attribute name starts with smallcase immediately followed by uppercase
eg: fCap fails, but firstCap is alright

**Comment by deepu105** [comment]
can you plz try generating the entity with the json I pasted above?
I tried multiple times and i am able to reproduce the error

**Comment by deepu105** [comment]
This one wroks
```
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Column(name = "first_cap", nullable = false)
    private String firstCap;
```

This one fails

```
@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Column(name = "f_cap", nullable = false)
    private String fCap;
```

**Comment by jdubois** [comment]
OK you are correct, sorry!
No idea what's wrong, I'm checking this up

**Comment by deepu105** [comment]
Yup Thank you :) I was demonstrating and defending my decision to use JHipster to collegues and this happened?
I'm trying to debug, will post back if I find anything

**Comment by jdubois** [comment]
The entity getter and setter are wrong!!!

**Comment by jdubois** [comment]
Here is why: http://stackoverflow.com/questions/2948083/naming-convention-for-getters-setters-in-java

**Comment by deepu105** [comment]
who would have guessed :+1:

**Comment by jdubois** [comment]
Yes, most stupid thing I've read since a long time.
I'll do a specific check in the generator.

**Comment by deepu105** [comment]
:+1:

**Comment by AdrienHorgnies** [comment]
It seems the issue isn't totally solved.

I have the same issue with a slightly more messed up name : `mAXCapacity`.

This results in the following getter : `getmAXCapacity`. And we have `@Column(name = "m_ax_capacity")` for the column annotation.

All this results in an application impossible to build : 
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/altissiadev/JHipster/otherTest/src/main/java/com/mycompany/myapp/domain/Mug.java:[72,33] cannot find symbol
  symbol:   method getMAXCapacity()
  location: class com.mycompany.myapp.domain.Mug
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.421 s
[INFO] Finished at: 2017-06-21T17:13:56+02:00
[INFO] Final Memory: 41M/399M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project other-test: Compilation failure
[ERROR] /home/altissiadev/JHipster/otherTest/src/main/java/com/mycompany/myapp/domain/Mug.java:[72,33] cannot find symbol
[ERROR] symbol:   method getMAXCapacity()
[ERROR] location: class com.mycompany.myapp.domain.Mug
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

I produced this error with v4.5.5. I just pressed enter at each prompt and generating the application with `yo jhipster`.

**Comment by pascalgrimaud** [comment]
@AdrienHorgnies : can you open a new ticket ?

**Comment by AdrienHorgnies** [comment]
I will do that.
