### ISSUE TITLE
Add support for simple JDL deployments

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#12511]
##### **Overview of the feature request**

Since the JDL supports the deployment keyword, it would be nice to have it support simple use cases. Currently, JHipster crashes when attempting to generate deployment for a single app using JDL.

##### **Motivation for or Use Case**

I want the following JDL file :

```
application {
  config {
    baseName testApplication
    prodDatabaseType postgresql
  }
}

deployment {
  deploymentType kubernetes
  dockerRepositoryName "pbesson"
}
```
To generate a valid JHipster application and its Kubernetes deployment files in `deploy/kubernetes`.

It should work similarly for other deployment sub-generators. And for the docker-compose option, we should deprecate the `src/main/docker/app.yml` file which is a duplicate of this feature.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Do you mean it crashes for monoliths? The deployment spec works for Microservices (at least used to work when I coded it)

**Comment by pascalgrimaud** [comment]
We need to check if the 'app.yml' is used or not by the docker compose sub generator.

If not, we should just remove it... it was created long time ago, before the sub gen docker compose, I'm not sure it is really used by our users today

**Comment by mraible** [comment]
Last time I tried, Docker Compose worked for `app.yml`. If we remove it, how can we start everything via Docker?

**Comment by pascalgrimaud** [comment]
@mraible : IMO, the best is to use docker-compose sub generator. It's here for that.
