### ISSUE TITLE
myBatis or spring JDBC option instead of JPA+Hibernate

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1252]
Hi guys, is it feasible to use myBatis instead of JPA+Hibernate, I know you can do the integration manually and make it work but any possibility of getting liquibase working on it?

Sorry if this is too much out of the way. I wanted to add that I discovered jHipster recently and its really amazing work you guys have done. I love the project. I'm using it for a new Large critical enterprise project (unfortunately I wont be able to share details of the project due to signed NDA). I really find jHipster stack ideal for the project, it had most of the things I had originally planned as the stack, I'c just switched the UX design with Less integration and gonna switch DAO from JPA+Hibernate to MyBatis.

Would love to contribute back if anyone is interested in the above option or the Less integration

**Comment by jdubois** [comment]
No we won't support other options than Hibernate/JPA.

**Comment by deepu105** [comment]
OK understood, but any suggestion or advice as I'm trying to replace JPA/Hibernate with myBatis for Oracle DB
(The project Im using JHipster for needs to be on Mybatis, as the team doesnt have any skillset in JPA/Hibernate)

**Comment by jdubois** [comment]
You should just change the DAO layer -> have a look at what we generate with Cassandra, it might be the closest to what you are doing
But this is going to be a lot of work, really. And you will need to make your Liquibase diff by hand. And the entity generator won't work.
And why MyBatis, I thought this was dead for years now?

**Comment by deepu105** [comment]
Thanks for the direction, ill try that out.
Our encounter with JPA/Hibernate was not quite good in earlier project mostly because the teams are not very concrete in those, so rather than screwing things up Mybatis seemed a better alternative than doing spring JDBC. But after looking at what you guys have done I'm more tempted to use JPA/Hibernate, But my project use case anyway requires very complex data model and views so I wont be using entity generator, ill be doing those manually
