### ISSUE TITLE
JDL: Remove webpack and the bundling stuff as its not needed anymore for JDL Studio

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#12520]
We currently have a webpack bundling step in JDL that's creates some web-friendly static files, we don't need it anymore

**Comment by MathieuAA** [comment]
To remove: webpack, the terser plugin, the NPM scripts, the bundling file, the folders and files inside the generator.
I can do it tomorrow on the train back to Paris unless someone beats me to it
