### ISSUE TITLE
Translations for falsy values : 0 and false

### ISSUE THREAD

**Issue by SoniaLahi** [jhipster/generator-jhipster#12529]
##### **Overview of the feature request**

In order to have a similar behaviour between frontend frameworks (cf. PR on [react falsy translations](https://github.com/jhipster/react-jhipster/pull/48)), when translation key values are 0 or false, it should return the value (0, false) instead of the key, in a Vue app.

##### **Motivation for or Use Case**
Standardization of translation behaviours in frontend apps. 
This ticket is about **Vue**.

##### **Related issues or PR**
Improvement requested here : https://github.com/jhipster/react-jhipster/pull/48#issuecomment-610908160

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SoniaLahi** [comment]
I would like to work on it :)

**Comment by mraible** [comment]
@SoniaLahi Any updates? Can we help?

**Comment by pascalgrimaud** [comment]
The PR is done, we just need to do a release of react-jhipster
It's hard for me to find time to check every part, as react-jhipster should be maintain and release by the stream lead

**Comment by SoniaLahi** [comment]
We should close this issue. I opened it to change the way the translation was done in vue, but it's currently working well.

**Comment by pascalgrimaud** [comment]
Agree we can close this.
It will really work only when react-jhipster is released
