### ISSUE TITLE
Add Less compilation task to grunt/gulp file

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1253]
I know most people would prefer Sass, but it brings in the Ruby/Compass dependency along with it, Less is simpler hence why not add it as an option?

**Comment by jdubois** [comment]
No, we can't support all options, we already have a lot of them, and then it's impossible to maintain.
Compass seems to be the one people prefer, that's why we have chosen it.

**Comment by deepu105** [comment]
fair enough
