### ISSUE TITLE
Package.json cleanup.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12541]
##### **Overview of the feature request**

- Drop test, not used.
- Drop mkdirp, every use seems unnecessary.
- Drop tabtab, seems broken. Anybody is using?
- Replace js-object-pretty-print with JSON.stringfy.
- Remove resolutions

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
about tabtab, it was for having auto completion when running jhipster cmd
I personally don't use it, as I'm really happy with zsh autosuggestion

+1 for cleaning
