### ISSUE TITLE
Option for setting pluralized form of entity names

### ISSUE THREAD

**Issue by msegmx** [jhipster/generator-jhipster#12554]
##### **Overview of the feature request**

Please provide a way to set the pluralized form of entity names:

* Ask the user about the plural form
* Add an option to provide the pluralized form of an entity name in JDL

##### **Motivation for or Use Case**

I'm not native in English but I always make a point of using English as my primary language when writing code. So I normally use English words for variable names, table names, entities, etc. and use a dictionary if necessary.

But there are times when translating a word, an entity name to English simply doesn't work; for example, when you talk to a customer you use specific words and you want to / have to use these words as entity names in your project. So, if there are, say, 10 entities, translating only a few or even most of them into English still affects how you think, like thinking half in English and half in my native language makes things way more difficult then it should be. So, in cases like these, not translating entity names into English at all is the preferred way to go. Problems arise during the pluralization phase of non-English words.

At this point, for people who, for whatever reason, have to use non-English words for entity names, providing pluralized forms of names becomes more of a necessity rather than a convenience.

(Please note, this request is not about adding support for different non-Latin alphabets; I would never use non-English characters like ç, ü, ö, etc inside code)

##### **Related issues or PR**

There are posts where pluralization was discussed from 4-5 years ago, but those posts were mostly about pluralization using the English language.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@msegmx are you thinking about field name or just translations is enough?

**Comment by msegmx** [comment]
@mshima only pluralized form of entity names. No translation needed.

**Comment by Yoshio123** [comment]
> ##### **Overview of the feature request**
> 
> 
> 
> Please provide a way to set the pluralized form of entity names:
> 
> 
> 
> * Ask the user about the plural form
> 
> * Add an option to provide the pluralized form of an entity name in JDL
> 
> 
> 
> ##### **Motivation for or Use Case**
> 
> 
> 
> I'm not native in English but I always make a point of using English as my primary language when writing code. So I normally use English words for variable names, table names, entities, etc. and use a dictionary if necessary.
> 
> 
> 
> But there are times when translating a word, an entity name to English simply doesn't work; for example, when you talk to a customer you use specific words and you want to / have to use these words as entity names in your project. So, if there are, say, 10 entities, translating only a few or even most of them into English still affects how you think, like thinking half in English and half in my native language makes things way more difficult then it should be. So, in cases like these, not translating entity names into English at all is the preferred way to go. Problems arise during the pluralization phase of non-English words.
> 
> 
> 
> At this point, for people who, for whatever reason, have to use non-English words for entity names, providing pluralized forms of names becomes more of a necessity rather than a convenience.
> 
> 
> 
> (Please note, this request is not about adding support for different non-Latin alphabets; I would never use non-English characters like ç, ü, ö, etc inside code)
> 
> 
> 
> ##### **Related issues or PR**
> 
> 
> 
> There are posts where pluralization was discussed from 4-5 years ago, but those posts were mostly about pluralization using the English language.
> 
> 
> 
> -   [x] Checking this box is mandatory (this is just to show you read everything)
> 
> 
> 
> 
> 
> 
I bought first Mac keyboard was French option physically. 
This Mac was setup trouble with key fittings.
Because,Number typing needs shit key.
Right upper icon looked didn't down case was very confused head.
This trap is very many time looking for me.
Boot progress is very dangerous.
Firmware key is need should be.

**Comment by mshima** [comment]
Once https://github.com/jhipster/generator-jhipster/pull/12570 is merged just add `entityNamePlural` annotation:
```
@entityNamePlural(everyBugs)
entity Bug {}
```
