### ISSUE TITLE
Add a command to modify entities and create tests

### ISSUE THREAD

**Issue by houcine8** [jhipster/generator-jhipster#1255]
I propose to add a command which incorporate necessary changes in master.xml when modifying existing entities.
Also for the creation of tests when adding entities manually.

**Comment by jgribonvald** [comment]
You can create/make change manually in your entity file description, ie .jhipster/EntityName.json and run again yo jhipster:entity EntityName

But a list of options to avoid overriding (to process without confirm on these files) entity.java, entity.js, etc... file generation would be great, like that we can add/do custom entities without problem and continuing other files generation based on the entity

**Comment by jdubois** [comment]
- those commands wouldn't be in master.xml, as this could have already been applied: you would need to do a diff
- as far as I'm concerned, a "liquibase:diff" perfectly does the trick, and is our recommended workflow
- so you can submit a PR, but if it's something really complicated to maintain I won't merge it, as I'm happy with the current workflow, and I don't want to have to maintain too many different workflows that basically do the same thing
