### ISSUE TITLE
Make serverFiles a parameter of writeFiles function

### ISSUE THREAD

**Issue by kevin-madhu** [jhipster/generator-jhipster#12556]
##### **Overview of the feature request**

Currently all the writeFiles functions in files.js use serverFiles from within the module. It helps in writing blueprints (and within blueprints, when a blueprint depends on another blueprint) to just pass in serverFiles without having to rewrite writeFiles functions inside the blueprints.

##### **Motivation for or Use Case**

I'm writing a blueprint that generates kotlin/java code depending upon the project's context and in order for me to do this, I just have to copy the template files override serverFiles and pass in serverFiles to writeFiles functions from the corresponding projects. 

Right now, instead of doing what's mentioned above, I'll have to copy over the writeFiles functions also, which increases the effort required for maintenance of the  blueprint/keeping up with those projects.

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
I'm not sure to understand. Can you, please, send an example of what are doing now, and what you want to do in the future if we change the way we handle serverFiles and write function. (I just want to be sure that I will not answer you without fully understand the issue).

Thank you !

**Comment by kevin-madhu** [comment]
@avdev4j It's so that I can write code like below instead of having to copy those functions from the corresponding projects.

**generators/entity-server/index.js**
`
const chalk = require('chalk');
const EntityServerGenerator = require('generator-jhipster/generators/entity-server');
const javaWriteFiles = require('generator-jhipster/generators/entity-server/files').writeFiles;
const kotlinWriteFiles = require('generator-jhipster-kotlin/generators/entity-server/files').writeFiles;
const javaServerFiles = require('./files').javaServerFiles;
const kotlinServerFiles = require('./files').kotlinServerFiles;

module.exports = class extends EntityServerGenerator {
    constructor(args, opts) {
        super(args, { fromBlueprint: true, ...opts }); // fromBlueprint variable is important

        if (!this.jhipsterContext) {
            this.error(`This is a JHipster blueprint and should be used only like ${chalk.yellow('jhipster --blueprint axon')}`);
        }
    }

    get initializing() {
        /**
         * Any method beginning with _ can be reused from the superclass `EntityServerGenerator`
         *
         * There are multiple ways to customize a phase from JHipster.
         *
         * 1. Let JHipster handle a phase, blueprint doesnt override anything.
         * ```
         *      return super._initializing();
         * ```
         *
         * 2. Override the entire phase, this is when the blueprint takes control of a phase
         * ```
         *      return {
         *          myCustomInitPhaseStep() {
         *              // Do all your stuff here
         *          },
         *          myAnotherCustomInitPhaseStep(){
         *              // Do all your stuff here
         *          }
         *      };
         * ```
         *
         * 3. Partially override a phase, this is when the blueprint gets the phase from JHipster and customizes it.
         * ```
         *      const phaseFromJHipster = super._initializing();
         *      const myCustomPhaseSteps = {
         *          displayLogo() {
         *              // override the displayLogo method from the _initializing phase of JHipster
         *          },
         *          myCustomInitPhaseStep() {
         *              // Do all your stuff here
         *          },
         *      }
         *      return Object.assign(phaseFromJHipster, myCustomPhaseSteps);
         * ```
         */
        // Here we are not overriding this phase and hence its being handled by JHipster
        return super._initializing();
    }

    get prompting() {
        // Here we are not overriding this phase and hence its being handled by JHipster
        return super._prompting();
    }

    get configuring() {
        // Here we are not overriding this phase and hence its being handled by JHipster
        return super._configuring();
    }

    get default() {
        // Here we are not overriding this phase and hence its being handled by JHipster
        return super._default();
    }

    get writing() {
        // Here we are not overriding this phase and hence its being handled by JHipster
        // return super._writing();
        const phaseFromJHipster = super.writing();

        const myCustomPhaseSteps = {
            saveBlueprintConfig() {
                const applicationLanguage = this.blueprintConfig.get('applicationLanguage');
                switch (applicationLanguage) {
                    case 'kotlin':
                        kotlinWriteFiles(kotlinServerFiles);
                        break;

                    default:
                        javaWriteFiles(javaServerFiles);
                        break;
                }
            }
        }

        return Object.assign(phaseFromJHipster, myCustomPhaseSteps);
    }

    get install() {
        // Here we are not overriding this phase and hence its being handled by JHipster
        return super._install();
    }

    get end() {
        // Here we are not overriding this phase and hence its being handled by JHipster
        return super._end();
    }
};
`

**generators/entity-server/files.js**
`
const constants = require('generator-jhipster/generators/generator-constants');

/* Use customized randexp */
// const randexp = utils.RandexpWithFaker;

/* Constants use throughout */
const INTERPOLATE_REGEX = constants.INTERPOLATE_REGEX;
const SERVER_MAIN_SRC_DIR = constants.SERVER_MAIN_SRC_DIR;
const SERVER_MAIN_RES_DIR = constants.SERVER_MAIN_RES_DIR;
const TEST_DIR = constants.TEST_DIR;
const SERVER_TEST_SRC_DIR = constants.SERVER_TEST_SRC_DIR;
const INTERPOLATE_REGEX = constants.INTERPOLATE_REGEX;
const TEST_DIR = constants.TEST_DIR;
const SERVER_MAIN_SRC_KOTLIN_DIR = `${constants.MAIN_DIR}kotlin/`;
const SERVER_TEST_SRC_KOTLIN_DIR = `${constants.TEST_DIR}kotlin/`;

/**
 * The default is to use a file path string. It implies use of the template method.
 * For any other config an object { file:.., method:.., template:.. } can be used
 */
const javaServerFiles = {
    // ...baseServerFiles,
    dbChangelog: [],
    fakeData: [],
    server: [
        {
            condition: generator =>
                (!generator.reactive || !['mongodb', 'cassandra', 'couchbase', 'neo4j'].includes(generator.databaseType)) &&
                !generator.embedded,
            path: SERVER_MAIN_SRC_DIR,
            templates: [
                {
                    file: 'package/repository/EntityViewRepository.java',
                    renameTo: generator => `${generator.packageFolder}/repository/${generator.entityClass}ViewRepository.java`,
                },
            ],
        },
        {
            condition: generator =>
                generator.reactive &&
                ['mongodb', 'cassandra', 'couchbase', 'neo4j'].includes(generator.databaseType) &&
                !generator.embedded,
            path: SERVER_MAIN_SRC_DIR,
            templates: [
                {
                    file: 'package/repository/EntityReactiveViewRepository.java',
                    renameTo: generator => `${generator.packageFolder}/repository/${generator.entityClass}ViewRepository.java`,
                },
            ],
        },
    ],
    test: [],
};

const kotlinServerFiles = {
    // ...baseServerFiles,
    server: [
        {
            condition: generator =>
                (!generator.reactive || !['mongodb', 'cassandra', 'couchbase', 'neo4j'].includes(generator.databaseType)) &&
                !generator.embedded,
            path: SERVER_MAIN_SRC_KOTLIN_DIR,
            templates: [
                {
                    file: 'package/repository/EntityViewRepository.kt',
                    renameTo: generator => `${generator.packageFolder}/repository/${generator.entityClass}ViewRepository.kt`,
                    useBluePrint: true,
                },
            ],
        },
        {
            condition: generator =>
                generator.reactive &&
                ['mongodb', 'cassandra', 'couchbase', 'neo4j'].includes(generator.databaseType) &&
                !generator.embedded,
            path: SERVER_MAIN_SRC_KOTLIN_DIR,
            templates: [
                {
                    file: 'package/repository/EntityReactiveViewRepository.kt',
                    renameTo: generator => `${generator.packageFolder}/repository/${generator.entityClass}ViewReactiveRepository.kt`,
                    useBluePrint: true,
                },
            ],
        },
    ],
    test: [],
};

module.exports = {
    javaServerFiles,
    kotlinServerFiles,
};
//
// function writeFiles() {
//     return {
//         saveRemoteEntityPath() {
//             if (_.isUndefined(this.microservicePath)) {
//                 return;
//             }
//             this.copy(
//                 `${this.microservicePath}/${this.jhipsterConfigDirectory}/${this.entityNameCapitalized}.json`,
//                 this.destinationPath(`${this.jhipsterConfigDirectory}/${this.entityNameCapitalized}.json`)
//             );
//         },
//
//         setupReproducibility() {
//             if (this.skipServer) return;
//
//             // In order to have consistent results with Faker, restart seed with current entity name hash.
//             faker.seed(utils.stringHashCode(this.name.toLowerCase()));
//         },
//
//         writeServerFiles() {
//             if (this.skipServer) return;
//
//             // write server side files
//             writeFilesToDisk(serverFiles, this, false, this.fetchFromInstalledJHipster('entity-server/templates'));
//
//             if (this.databaseType === 'sql') {
//                 if (!this.skipDbChangelog) {
//                     if (this.fieldsContainOwnerManyToMany || this.fieldsContainOwnerOneToOne || this.fieldsContainManyToOne) {
//                         this.addConstraintsChangelogToLiquibase(`${this.changelogDate}_added_entity_constraints_${this.entityClass}`);
//                     }
//                     this.addChangelogToLiquibase(`${this.changelogDate}_added_entity_${this.entityClass}`);
//                 }
//
//                 const serverCacheKt = new NeedleServerChacheKt(this);
//
//                 if (['ehcache', 'caffeine', 'infinispan', 'redis'].includes(this.cacheProvider) && this.enableHibernateCache) {
//                     serverCacheKt.addEntityToCache(
//                         this.asEntity(this.entityClass),
//                         this.relationships,
//                         this.packageName,
//                         this.packageFolder,
//                         this.cacheProvider
//                     );
//                 }
//             }
//         },
//
//         writeEnumFiles() {
//             // TODO replace this with proper function.
//             const fetchFromInstalledKHipster = subpath => path.join(__dirname, subpath);
//             this.fields.forEach(field => {
//                 if (!field.fieldIsEnum) {
//                     return;
//                 }
//
//                 const fieldType = field.fieldType;
//                 const enumInfo = {
//                     ...utils.getEnumInfo(field, this.clientRootFolder),
//                     angularAppName: this.angularAppName,
//                     packageName: this.packageName,
//                 };
//                 // eslint-disable-next-line no-console
//                 if (!this.skipServer) {
//                     const pathToTemplateFile = `${fetchFromInstalledKHipster(
//                         'templates'
//                     )}/${SERVER_MAIN_SRC_KOTLIN_DIR}package/domain/enumeration/Enum.kt.ejs`;
//                     this.template(
//                         pathToTemplateFile,
//                         `${SERVER_MAIN_SRC_KOTLIN_DIR}${this.packageFolder}/domain/enumeration/${fieldType}.kt`,
//                         this,
//                         {},
//                         enumInfo
//                     );
//                 }
//             });
//         },
//     };
// }
//
`

**Comment by DanielFran** [comment]
@kevin-madhu Do you still have this issue?
Maybe there is a better approach @mashima?

**Comment by emilpaw** [comment]
@DanielFran I highly suspect you meant to ping @mshima

**Comment by kevin-madhu** [comment]
@DanielFran Basically, I wanted to write a blueprint that added some files on top of the ones generated by jhipster, but at the same time offer the user with a choice to choose between java and kotlin.  I've given up the attempt to write such a blueprint, atleast at the moment. So, it doesn't matter to me now. So, maybe I'll close the issue and maybe re-open if I decide to work on the same later and I'm not able to at that point?

**Comment by mshima** [comment]
The writeFiles is a task group.
And the tasks are really simple.
https://github.com/jhipster/generator-jhipster/blob/ba71168e1b9a6747af9cfe31e9f7d62e304750e1/generators/server/files.js#L1950-L1975

I don't see the reason for it to be in a separated file, IMO we should move it to the generator itself for v8.

We are exporting the serverFiles
https://github.com/jhipster/generator-jhipster/blob/ba71168e1b9a6747af9cfe31e9f7d62e304750e1/generators/server/files.js#L1978

So it's just import it and write it.
```
await this.writeFiles({
  sections: serverFiles,
  context: this,
});
```

And there are a lot of improvements to blueprints support.
Micronaut reuses the main generator files for entities for example.
We need an updated use case.
