### ISSUE TITLE
In Vue app, can't see entities submenus

### ISSUE THREAD

**Issue by SoniaLahi** [jhipster/generator-jhipster#12553]
##### **Overview of the issue**

After importing the jdl example on [jdl-studio](https://start.jhipster.tech/jdl-studio/) the Vue app does not display the list of entities in the menu 'Entities'.

Expected (from react app) : 
![image](https://user-images.githubusercontent.com/5923781/93655206-75c68d00-fa22-11ea-91cd-7de90acac687.png)

Got (vue) :
![image](https://user-images.githubusercontent.com/5923781/93655163-44e65800-fa22-11ea-8c6f-eec0cdbe19bd.png)

##### **Reproduce the error**

1/ clone generator-jhipster + `npm link` in this project
2/ generate vue app : create new folder + `npm link generator-jhipster` + `jhipster`
3/ `jhipster import-jdl jhi-1.jh`
4/ build and start front/back
5/ login

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/sonia/dev/jhipster-code/tmp-confirm-issue/vue-test
└── generator-jhipster@6.10.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "6.10.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1600477117063,
    "promptValues": {
      "packageName": "fr.sla.vue",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "fr.sla.vue",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "fr/sla/vue",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Region {
  regionName String
}
entity Country {
  countryName String
}
/**
 * not an ignored comment
 */
entity Location {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Department {
  departmentName String required
}
/**
 * Task entity.\n@author The JHipster team.
 */
entity Task {
  title String,
  description String
}
/**
 * The Employee entity.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate Instant,
  salary Long,
  commissionPct Long
}
entity Job {
  jobTitle String,
  minSalary Long,
  maxSalary Long
}
entity JobHistory {
  startDate Instant,
  endDate Instant,
  language Language
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region} to Region,
  Location{country} to Country,
  Department{location} to Location,
  JobHistory{job} to Job,
  JobHistory{department} to Department,
  JobHistory{employee} to Employee
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to
  /**
   * Another side of the same relationship
   */
  Employee{department},
  Employee{job} to Job{employee}
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

service Region, Country, Location, Department, Task, JobHistory with serviceImpl
paginate Employee, JobHistory with infinite-scroll
paginate Job with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

git version 2.17.1

node: v12.13.0

npm: 6.13.0

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.6, build 369ce74a3c

docker-compose version 1.26.0, build d4451659

identical .jhipster/Country.json
identical .jhipster/Department.json
identical .jhipster/Employee.json
identical .jhipster/Job.json
identical .jhipster/JobHistory.json
identical .jhipster/Location.json
identical .jhipster/Region.json
identical .jhipster/Task.json
INFO! Congratulations, JHipster execution is complete!

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

git version 2.17.1

node: v12.13.0

npm: 6.13.0

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.6, build 369ce74a3c

docker-compose version 1.26.0, build d4451659

identical .jhipster/Country.json
identical .jhipster/Department.json
identical .jhipster/Employee.json
identical .jhipster/Job.json
identical .jhipster/JobHistory.json
identical .jhipster/Location.json
identical .jhipster/Region.json
identical .jhipster/Task.json
INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@SoniaLahi : between step2 and 3, can you launch again `npm link generator-jhipster ` before importing jdl ?
Otherwise, I afraid it will use local generator-jhipster v6.10.1 which doesn't have Vue.js

**Comment by SoniaLahi** [comment]
Thank you @pascalgrimaud, it works now. 
Have I missed the step in the documentation or should it be added somewhere ?

**Comment by pascalgrimaud** [comment]
it's the normal behavior, and it should be in my slide for jhipster code
but we can check if in contribution.md file it's there or not. 
Feel free to check and close this ticket if it's ok :)

**Comment by SoniaLahi** [comment]
Actually, it was written in the slides :clap:  but not in the contribution.md

**Comment by mraible** [comment]
@SoniaLahi Did you create a PR for this change?

**Comment by pascalgrimaud** [comment]
it's already in progress, @mraible
