### ISSUE TITLE
Disabling Oauth2 refresh token 

### ISSUE THREAD

**Issue by aklauza** [jhipster/generator-jhipster#1256]
As I can infer from these two closed issues (https://github.com/jhipster/generator-jhipster/issues/441 and https://github.com/jhipster/generator-jhipster/issues/1170) and the code, jHipster is not implementing the refresh token flow in the Oauth2 protocol.

This is completely fine and optional, and some big providers are not implementing it either (github for example). However, if you guys decided not to implement it for now (which I completely agree as will show later in the post), you should disable it completely in Spring. As it is now, the AuthorizationServer keeps sending the refresh_token and its endpoint is still open. To change this, in OAuth2ServerConfiguration.configure() method you should change this line:
```java
.authorizedGrantTypes("password")
```
and add the following:
```java
.refreshTokenValiditySeconds(0)
```
Now the refresh_token will not be provided by the server and therefore, the oauthTokens are really short lived and the user has to login again when they expire, which is more secure. Security is the reason why some providers are deciding not to implement the refresh_token flow in the protocol.

If you keep open the refresh_token endpoint on the server, anyone with access to the user's browser localStorage could be requesting valid tokens from the server for months, and therefore use the client's credentials without even knowing the username or password. The refresh_token is really a weakness in the Oauth2 protocol. I strongly recommend you to disable it. On the other side, in the your docs, you should clearly state that Oauth2 protocol MUST be implemented in conjunction with HTTPS. Without a secure connection it is highly vulnerable.

**Comment by seghers** [comment]
jHipster might not use it in the angular part but I'm sure people are using the refreshtokens in other clients.
Just removing this functionality for everyone seems hasty.

Maybe an extra config entry: 4) auth type? > 4.2) oauth2? > 4.2.1) without refreshtokens?

**Comment by aklauza** [comment]
Yes, the configuration option seems totally reasonable. But then, if there is an option with refresh tokens, it should be implemented in the angular app when the developer chooses it as well.

**Comment by jdubois** [comment]
For me this is the same discussion as #1257 so I'm closing this, and let's discuss this in the other ticket
