### ISSUE TITLE
Relationships handling improvements.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12562]
##### **Overview of the feature request**

Improve relationship handling:
- [ ] JDL should export every reference. (https://github.com/jhipster/generator-jhipster/pull/12551, https://github.com/jhipster/generator-jhipster/pull/12552)
- [ ] Replace `@JsonIgnore` with `@JsonIgnoreProperty`
`@JsonIgnore` ignores the other side (prevents from showing in the UI)
`@JsonIgnoreProperty` just prevents cyclic serialization (we should consider using `@JsonViews` in the future).
- [ ] Improve eager loading.
Currently we eager load `ownerSide && 'many-to-many'` relationships.
We should load every relationship by default or make easier to load others relationships.
- Make easier to code relationship at client frameworks:
  - angular:
    - [ ] allow the entity module to load relationship components to embed or pop-up (https://github.com/jhipster/generator-jhipster/pull/12549).

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Yoshio123** [comment]
> ##### **Overview of the feature request**
> 
> 
> 
> Improve relationship handling:
> 
> - [ ] JDL should export every reference. (https://github.com/jhipster/generator-jhipster/pull/12551, https://github.com/jhipster/generator-jhipster/pull/12552)
> 
> - [ ] Replace `@JsonIgnore` with `@JsonIgnoreProperty`
> 
> `@JsonIgnore` ignores the other side (prevents from showing in the UI)
> 
> `@JsonIgnoreProperty` just prevents cyclic serialization (we should consider using `@JsonViews` in the future).
> 
> - [ ] Improve eager loading.
> 
> Currently we eager load `ownerSide && 'many-to-many'` relationships.
> 
> We should load every relationship by default or make easier to load others relationships.
> 
> - Make easier to code relationship at client frameworks:
> 
>   - angular:
> 
>     - [ ] allow the entity module to load relationship components to embed or pop-up (https://github.com/jhipster/generator-jhipster/pull/12549).
> 
> 
> 
> 
> 
> ##### **Motivation for or Use Case**
> 
> 
> 
> 
> 
> 
> 
> ##### **Related issues or PR**
> 
> 
> 
> 
> 
> 
> 
> -   [ ] Checking this box is mandatory (this is just to show you read everything)
> 
> 
> 
> 
> 
>

**Comment by Yoshio123** [comment]
> > ##### **Overview of the feature request**
> > 
> > 
> > 
> > Improve relationship handling:
> > 
> > - [x] JDL should export every reference. (https://github.com/jhipster/generator-jhipster/pull/12551, https://github.com/jhipster/generator-jhipster/pull/12552)
> > 
> > - [x] Replace `@JsonIgnore` with `@JsonIgnoreProperty`
> > 
> > `@JsonIgnore` ignores the other side (prevents from showing in the UI)
> > 
> > `@JsonIgnoreProperty` just prevents cyclic serialization (we should consider using `@JsonViews` in the future).
> > 
> > - [x] Improve eager loading.
> > 
> > Currently we eager load `ownerSide && 'many-to-many'` relationships.
> > 
> > We should load every relationship by default or make easier to load others relationships.
> > 
> > - Make easier to code relationship at client frameworks:
> > 
> >   - angular:
> > 
> >     - [x] allow the entity module to load relationship components to embed or pop-up (https://github.com/jhipster/generator-jhipster/pull/12549).
> > 
> > 
> > 
> > 
> > 
> > ##### **Motivation for or Use Case**
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > ##### **Related issues or PR**
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > -   [ ] Checking this box is mandatory (this is just to show you read everything)
> > 
> > 
> > 
> > 
> > 
> > 
> 
>
