### ISSUE TITLE
JhiHttpInterceptor should tweak types to allow strict typescript ('use strict') on classes that inherit from it

### ISSUE THREAD

**Issue by AdamJWise** [jhipster/generator-jhipster#12578]
##### **Overview of the issue**

When using the class 'JhiHttpInterceptor' the intended use is to 'intercept' calls and pass the argument as a return value.  However, the method signatures do not allow the method to simply return the incoming parameter. if typescript's 'use strict' option is set to true.

See https://github.com/jhipster/jhipster-sample-app-token/blob/master/src/main/webapp/app/blocks/interceptor/notification.interceptor.ts#L16

![image](https://user-images.githubusercontent.com/8713765/94034695-4ef4b780-fd90-11ea-8bc0-81af764809df.png)

Note that the 'options' parameter is typed so that it actually means 'RequestOptionsArgs | undefined' but the return type is just 'RequestOptionsArgs'.

So, if a class inherits from JhiHttpInterceptor and attempts to build via 'use strict', this will produce an error like the following:

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/8713765/94035354-f5d95380-fd90-11ea-9ff0-e9bbdb33aa1f.png">

```
Error at src/main/webapp/app/blocks/interceptor/notification.interceptor.ts:18:9: Type 'RequestOptionsArgs | undefined' is not assignable to type 'RequestOptionsArgs'.
  Type 'undefined' is not assignable to type 'RequestOptionsArgs'.
```

Specifically, 

##### **Motivation for or Use Case**

The official JHipster policy is to 'use strict' versions for third-party libraries. Also in order to use JHipster in certain secure environments we need to pass a security review with very strict linting requirements.

##### **Reproduce the error**

1. Add 'use strict' to tsconfig.
2. Code a class to inherit from JhiHttpInterceptor
3. run the linter

##### **Related issues**

n/a

##### **Suggest a Fix**

Tweaking the parameter type and/or the return type of methods to JhiHttpInterceptor to match. One way would be to tweak the return types to include '| undefined'.

##### **JHipster Version(s)**

I'm seeing this in the current version of JHipster, in the sample app as of 2020-09-23. See https://github.com/jhipster/jhipster-sample-app-token.

##### **JHipster configuration**

n/a

##### **Browsers and Operating System**

All versions of Jhipster with JhiHttpInterceptor.ts

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
https://github.com/jhipster/jhipster-sample-app-token is deprecated and hasn't been updated since 2017 (@jdubois we should probably archive that repository). 

That sample uses JHipster v4 and we are now on JHipster v6 (soon v7). We no longer use `JhiHttpInterceptor` anywhere in the code.  

Does this issue still apply to the latest release?  For reference, here's the [current version of NotificationInterceptor](https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/webapp/app/blocks/interceptor/notification.interceptor.ts) from the default sample app https://github.com/jhipster/jhipster-sample-app

**Comment by jdubois** [comment]
Thanks @ruddell - the project is clearly written DEPRECATED in big letters in the description

**Comment by mraible** [comment]
Maybe we should archive it? That’s that I did with AppFuse.

https://github.com/appfuse/appfuse <https://github.com/appfuse/appfuse>

**Comment by jdubois** [comment]
OK, let me archive it

**Comment by AdamJWise** [comment]
Thanks for the great feedback. I checked and the equivalent classes in the latest version of JHipster do not have this problem. (For example: https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/webapp/app/blocks/interceptor/notification.interceptor.ts)

**Comment by ruddell** [comment]
Since this was fixed in v4, closing the issue.

As a workaround for old projects, you can copy [JhiHttpInterceptor](https://github.com/jhipster/ng-jhipster/blob/v0.3.4/src/interceptor/http.interceptor.ts) into your own project, fix the types, and extend it instead of the one from ng-jhipster.
