### ISSUE TITLE
Hibernate sequence generator should start with a higher value

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#12572]
##### **Overview of the feature request**

Hibernate sequence generator should start with a higher value.

##### **Motivation for or Use Case**

Current value start with 1050 and if it is needed to load more initial data, it won't be sufficient sometimes.
Starting with a value with , for eg, 100k will give enough space for the records to be added.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
@pmverma, Can you elaborate on the issue over here? How small initial value impact performance?

**Comment by pmverma** [comment]
Thanks Vishal, there is no performance impact here.
It is just that if it start with 100k then we can load up to 100k of data (custom initial data via CSV in my case) without `id`s conflicts.

**Comment by pascalgrimaud** [comment]
I already encountered this issue, when putting 1500 datas in fake data cvs files.
The main problem is: liquibase load data ignores the sequence. 

I think 100k is really too much. 
Of course, we can increase the value but it won't fix the problem. 
The best would be to document it:
- add little comment in load data part, in liquibase changelog
- add document at jhipster.tech

What do you think ?

**Comment by pmverma** [comment]
Ok, 2 things here.

I want to maintain the relationship too, so having liquibase generate the id won't help in my case.
It is fine for me even sequence start with at least 10k.

Although I have not tried it but if you want liquibase to generate ids, then there is an attribute `valueComputed` on the tag `column` where we can call the sequence.

**Comment by gmarziou** [comment]
Usually in my projects I update the sequence in the change log after the loadData.

 This is easy when you have one sequence per entity rather than global hibernate sequence 

Why can’t we do the same?

**Comment by murdos** [comment]
+1 for having one sequence per entity rather than a global hibernate sequence

**Comment by gmarziou** [comment]
Having a sequence per entity is the default in postgresql when using SERIAL pseudo type and also it helps when extracting micro services from a monolith.

In fact, I can’t find any benefit why Hibernate global sequence.

**Comment by pmverma** [comment]
Ok, 2 things here.

1. I will increase the default starting value of the hibernate default sequence to 10k. I hope this will not cause any problem.

1. Having a sequence per entity. @jhipster/developers If there is no objection I will do a separate PR.

**Comment by jdubois** [comment]
The idea behind having just one sequence is that you have a unique ID for all objects. It could be handy sometimes.
Please have a look at Vlad’s posts on this, in case we are missing something.
Also this will be a breaking change, so be careful as this should go in a major release.

**Comment by murdos** [comment]
Re-opening since I'm experimenting the use of a dedicated sequence per entity.

**Comment by mraible** [comment]
> Re-opening since I'm experimenting the use of a dedicated sequence per entity.

@mshima Should we keep this issue open or close it?

**Comment by mshima** [comment]
@mraible not me 😄.

Anyway, I like one sequence per entity, I had it implemented inside a customization blueprint.
But only one sequence is simpler.

Changing the initial sequence number is pretty easy.
Change the value and add the file to .yo-resolve.

**Comment by Tcharl** [comment]
Closing, as there's a simple fix for the end user that needs it (and because we have a lot of other issue to fix :-p)
