### ISSUE TITLE
Wrong implementation in handleMethodArgumentNotValid

### ISSUE THREAD

**Issue by dmushkov** [jhipster/generator-jhipster#12574]
##### **Overview of the issue**
Wrong code for method handleMethodArgumentNotValid in ExceptionTranslator.java in server app 

##### **Reproduce the error**

In server generator 
we have following piece of code in ExceptionTranslator class 

 ```
@Override
    public ResponseEntity<Problem> handleMethodArgumentNotValid(MethodArgumentNotValidException ex, @Nonnull NativeWebRequest request) {
        BindingResult result = ex.getBindingResult();
        List<FieldErrorVM> fieldErrors = result.getFieldErrors().stream()
            .map(f -> new FieldErrorVM(f.getObjectName().replaceFirst("DTO$", ""), f.getField(), f.getCode()))
            .collect(Collectors.toList());

        Problem problem = Problem.builder()
            .withType(ErrorConstants.CONSTRAINT_VIOLATION_TYPE)
            .withTitle("Method argument not valid")
            .withStatus(defaultConstraintViolationStatus())
            .with(MESSAGE_KEY, ErrorConstants.ERR_VALIDATION)
            .with(FIELD_ERRORS_KEY, fieldErrors)
            .build();
        return create(ex, problem, request);
    }


```
UserDTO 

```
 @NotBlank
    @Pattern(regexp = Constants.LOGIN_REGEX)
    @Size(min = 1, max = 50)
    private String login;
```

then when we test creation of user with not following regex for login name we can get 

Body = {"type":"https://www.jhipster.tech/problem/constraint-violation","title":"Method argument not valid","status":400,"path":"/api/users","message":"error.validation","fieldErrors":[{"objectName":"user","field":"login","message":"**Pattern**"}]}
    Forwarded URL = null
   Redirected URL = null
          Cookies = []

Even if we put translationKey Pattern in message.properties file in res folder message will be always **Pattern**. 

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Thanks for the bug report @dmushkov! Any chance you can create a pull request to fix it? If you need help contributing, please let me know.
