### ISSUE TITLE
Jenkins docker version based on Java 8 while Java version in application is 11

### ISSUE THREAD

**Issue by bmvermeer** [jhipster/generator-jhipster#12595]
##### **Overview of the issue**

When generating a jenkins.yml with `jhipster ci-cd` the image is based on Java 8
The Jhipster app that is generated has java.version 11 in the pom file.

##### **Motivation for or Use Case**

Failure if building within Jenkins container

##### **Suggest a Fix**

updating Jenkins docker version to lts-jdk11

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/12596
