### ISSUE TITLE
Deployed .war gateway project doesn't work on tomcat server

### ISSUE THREAD

**Issue by rennydonny** [jhipster/generator-jhipster#12599]
##### **Overview of the issue**

I got an error after following the instructions  https://www.jhipster.tech/production/
Initial configuration:

![gatewayInitConf](https://user-images.githubusercontent.com/4966706/94372123-d5770500-00c0-11eb-89b7-37e1191abdb7.png)

Changes to deploy on tomcat server:

![warToTomcatDeployConfig](https://user-images.githubusercontent.com/4966706/94372126-dad44f80-00c0-11eb-8dfc-c4fa8877cfc2.png)

##### **Reproduce the error**

1. Create a jhipster Microservice Gateway project
2. Make changes from jhipster guide https://www.jhipster.tech/production/
3. Packed as war `./mvnw -Pprod,war clean package -DskipTests `
4. Renamed `target/gateway-0.0.1-SNAPSHOT.war.original` to `gateway.war`
5. Copy to `<tomcat_path>/webapps/gateway.war`
6. Start tomcat server
7. Go to browser `http://localhost:8080/gateway/`

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/11365

##### **JHipster Version(s)**

v6.10.3

##### **JHipster configuration**

> `INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.1-SNAPSHOT /home/renny/workspace/demos/gateway
└── generator-jhipster@6.10.3 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.home.demo.gateway"
    },
    "jhipsterVersion": "6.10.3",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.home.demo.gateway",
    "packageFolder": "com/home/demo/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1601226472271,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10)
OpenJDK 64-Bit Server VM (build 11.0.8+10, mixed mode)

git version 2.28.0

node: v12.18.4

npm: 6.14.7

Docker version 19.03.13-ce, build 4484c46d9d

docker-compose version 1.27.4, build unknown
`

##### **Browsers and Operating System**

> OS: Arch Linux x86_64
> Kernel: 5.4.67-1-lts
> Google Chrome and Mozilla Firefox

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
It's an issue with configuration. Refer comment https://github.com/jhipster/generator-jhipster/issues/11365#issuecomment-699645477
