### ISSUE TITLE
Websocket connection failure- application context is missing

### ISSUE THREAD

**Issue by pnreddysvu** [jhipster/generator-jhipster#1259]
I created a websocket application and deployed the original war in Tomcat.
I noticed the websocket connection request is sending with root context instead of application context.

Actual Request:
http://localhost:8080/websocket/activity/info

But correct request should be 

http://localhost:8080/MyAPP/websocket/activity/info

same for http://localhost:8080/websocket/tracker/info

**Comment by mrzepinski** [comment]
+1

**Comment by jdubois** [comment]
Yes, the first "/" on the Websocket URL should be removed, like we do for the API requests.

However, when I remove it, I have the following error:
```
Uncaught SyntaxError: Failed to construct 'WebSocket': The URL 'wsocket/tracker/705/2wfhpyqj/websocket' is invalid.
```

**Comment by jdubois** [comment]
I'm closing this as "won't fix", as this causes this Syntax Error.

Anyway we only provide the tracker as an example: if you create your own websocket connection, you should use it with the correct URL anyway.
