### ISSUE TITLE
user serverPort variable in EntityGatlingTest.scala

### ISSUE THREAD

**Issue by nicolas63** [jhipster/generator-jhipster#12606]
##### **Overview of the feature request**

replace hard coded port by serverPort variable 
`val baseURL = Option(System.getProperty("baseURL")) getOrElse """http://localhost:8080"""`

`val baseURL = Option(System.getProperty("baseURL")) getOrElse """http://localhost:<%= serverPort %>"""`

##### **Motivation for or Use Case**

Allow blueprint to override with custom port without additonal argument for run gatling 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

if it's ok for you i can provide a PR

**Comment by atomfrede** [comment]
Looks like a reasonable change. Can you do a PR for this?

**Comment by nicolas63** [comment]
Yes, i do it soon
