### ISSUE TITLE
Unable to see icons with prod profile

### ISSUE THREAD

**Issue by pnreddysvu** [jhipster/generator-jhipster#1260]
I created a oAuth2-mongodb-websocket application. Deployed the original war in tomcat.
I set the prod as active profile. Able to access the application but icons/images are not showing.

attached the screenshots.

I could see the request without application context.

Request URL:http://localhost:8080/assets/images/1d45bca0.hipster.png
Request Method:GET
Status Code:404 Not Found

Request URL:http://localhost:8080/bower_components/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2
Request Method:GET
Status Code:404 Not Found

![dev-profile-working](https://cloud.githubusercontent.com/assets/10413413/6654851/43c4e32a-cb06-11e4-9774-f02c8ac8503e.png)
![prod-profile-not-working](https://cloud.githubusercontent.com/assets/10413413/6654852/47cef438-cb06-11e4-82c5-25136a244ce7.png)

**Comment by atomfrede** [comment]
Why don't you use the executable .war file? But yes, both icons and image doesn't work when deploying in a tomcat (looks like a problem with paths in css).

**Comment by pnreddysvu** [comment]
We need JSR 289 container. executable war does not contain JSR 289 platform. So i had to deploy my application is custom tomcat.

**Comment by atomfrede** [comment]
Is it possible to deploy jhipster in the root context of your tomcat instance?

**Comment by pnreddysvu** [comment]
I have two Jhipster apps. Both cannot be run in the root context. If you are not planning to solve this, I will try  to change the path locally in my application.

**Comment by atomfrede** [comment]
Why not use seperate tomcats for each application? From my experience running multiple applications in one container (at least in production) doesn't work that well.

**Comment by martyspringer** [comment]
Someone else created a workaround for this problem:
http://ignaciosuay.com/how-to-avoid-grunt-build-not-loading-bootstrap-glyphicons-using-jhipster/
I tried it and his changes fix the problem.

**Comment by jdubois** [comment]
You are correct, this only works if you deploy JHipster as the root of the application server.

If you don't deploy it to the root, then the Grunt tasks (like CSSMin) can't know your application context, so their URL will not be correct -> then you have to configure them to give them the correct URL.

I don't think we can solve this inside JHipster, as you can deploy to any context, and this is done after the grunt tasks has minified the files: so it's too late to regenerate them.

In that case, you must either reconfigure your grunt tasks, or have an URL rewriter in front of your app server.
