### ISSUE TITLE
CORS properties in application-*.yml not working

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#12601]
##### **Overview of the issue**

This maybe due to my lack of understanding of how CORS seems to behave in JHipster applications. But I am trying to include a video in a sample jhipster application which is hosted on a external storage. Here's the sample application. 

https://github.com/SudharakaP/JHipsterCORSSampleApplication

Now when I run `npm start` with Browsersync and access front-end on `localhost:9000` everything seems to work fine. But when I run `./mvnw -Pdev` it seems that the video is not accessible and I get the CORS error; 

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4 (“default-src”).
```

Since in the `application-dev.yml` we have,

```
cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
```
I thought that in `dev` profile these requests should be allowed. Am I missing something here? 🤔 

##### **Motivation for or Use Case**

Making Browsersync and dev profile experience consistent.

##### **Reproduce the error**

Please clone the above repo and follow the above instructions given in the overview.

##### **JHipster Version(s)**

6.10.3

##### **JHipster configuration**
<pre>&lt;details&gt;
&lt;summary&gt;.yo-rc.json file&lt;/summary&gt;
&lt;pre&gt;
{
  &quot;generator-jhipster&quot;: {
    &quot;applicationType&quot;: &quot;monolith&quot;,
    &quot;gitCompany&quot;: &quot;&quot;,
    &quot;baseName&quot;: &quot;JHipsterCORSSampleApplication&quot;,
    &quot;packageName&quot;: &quot;com.mycompany.myapp&quot;,
    &quot;packageFolder&quot;: &quot;com/mycompany/myapp&quot;,
    &quot;serverPort&quot;: 8080,
    &quot;serviceDiscoveryType&quot;: false,
    &quot;authenticationType&quot;: &quot;jwt&quot;,
    &quot;uaaBaseName&quot;: &quot;../uaa&quot;,
    &quot;cacheProvider&quot;: &quot;ehcache&quot;,
    &quot;enableHibernateCache&quot;: true,
    &quot;websocket&quot;: false,
    &quot;databaseType&quot;: &quot;sql&quot;,
    &quot;devDatabaseType&quot;: &quot;h2Disk&quot;,
    &quot;prodDatabaseType&quot;: &quot;mysql&quot;,
    &quot;searchEngine&quot;: false,
    &quot;enableSwaggerCodegen&quot;: false,
    &quot;messageBroker&quot;: false,
    &quot;buildTool&quot;: &quot;maven&quot;,
    &quot;useSass&quot;: true,
    &quot;clientPackageManager&quot;: &quot;npm&quot;,
    &quot;testFrameworks&quot;: [],
    &quot;enableTranslation&quot;: false,
    &quot;nativeLanguage&quot;: &quot;en&quot;,
    &quot;languages&quot;: [&quot;en&quot;],
    &quot;clientFramework&quot;: &quot;react&quot;,
    &quot;jhiPrefix&quot;: &quot;jhi&quot;,
    &quot;jhipsterVersion&quot;: &quot;6.10.3&quot;,
    &quot;jwtSecretKey&quot;: &quot;YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons&quot;,
    &quot;embeddableLaunchScript&quot;: false,
    &quot;clientTheme&quot;: &quot;none&quot;,
    &quot;creationTimestamp&quot;: 1601263618104,
    &quot;entitySuffix&quot;: &quot;&quot;,
    &quot;dtoSuffix&quot;: &quot;DTO&quot;,
    &quot;otherModules&quot;: [],
    &quot;blueprints&quot;: [],
    &quot;prettierJava&quot;: true
  },
  &quot;git-provider&quot;: &quot;GitHub&quot;,
  &quot;git-company&quot;: &quot;SudharakaP&quot;,
  &quot;repository-name&quot;: &quot;JHipsterCORSSampleApplication&quot;
}

&lt;/pre&gt;
&lt;/details&gt;</pre>

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
It is not the cors policy, its the co[ntent security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). By default (e.g. for images, videos) only `self` is allowed. You need to adapt the [policy accordingly](https://github.com/jhipster/generator-jhipster/blob/81c3b248dd3e734e2594e0519a2839d808b7b422/generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs#L244). We do that already in case bootswatch themes are selected as they include parts from google fonts for example.

**Comment by SudharakaP** [comment]
@atomfrede : Ah, nice; yes I was confusing the two; thanks for the explanation. 😄
