### ISSUE TITLE
One-to-One relationship with shared primary key issue

### ISSUE THREAD

**Issue by Kahfimaulana** [jhipster/generator-jhipster#1262]
Hey, 
I have an issue with one-to-one relationship with shared primary key. 
I have scheme below:
1.Table module: varchar() moduleName (PK)
2.Table module_detail:
varchar() module_name (PK and FK reference module(module_name) )
String description

So I try to generate module entity first, have one-to-one relationship to moduleDetail entity, and attempted as an owner of relationship. 
Secondly, I generated moduleDetail entity, have one-to-one relationship to module entity.

The generated html file for moduleDetail entity (moduleDetail.html) does not implement a select options that contains a module options. Whereas, it was an one-to-one relationship.
I have tried to manipulated file are generated domain and html file but the result is "attempted to assign id from null one-to-one property".

So, How could I generate jhipster to meet a result with my scheme?

**Comment by jdubois** [comment]
We do support one-to-one relationship, but we don't generate the UI yet.

This is a duplicate from #905
