### ISSUE TITLE
Getting started with jhipster , application wont run by default 

### ISSUE THREAD

**Issue by ArjunDandagi** [jhipster/generator-jhipster#12629]
##### **Overview of the issue**

I was excited to see if the project becomes up and running without having to code anything 

i have also recorded the session here https://asciinema.org/a/tzoJpDkAtmjrzQiCSc2JysMN7

##### **Motivation for or Use Case**
I haven't written a single line of code yet. but if i am not wrong , i should be able to run the application without editing for the 
first time

the setup won't work with the options i chose when starting 

##### **Reproduce the error**

https://asciinema.org/a/tzoJpDkAtmjrzQiCSc2JysMN7

##### **JHipster Version(s)**
jhipster 6.10.3
npm 6.14.8
Apache Maven 3.6.3
java : 
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

node: v12.14.0

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
The generator won't run the app by default.
You can do so by `./mvnw` as described in last lines of project generation.

**Comment by ArjunDandagi** [comment]
i used ./mvnw itself , can you please reproduce this and see if it works?

this is the recording i have done while running jhipster for the first time 
https://asciinema.org/a/tzoJpDkAtmjrzQiCSc2JysMN7

jhipster 6.10.3
npm 6.14.8
Apache Maven 3.6.3
java : openjdk version "11.0.8" 2020-07-14
node: v12.14.0

**Comment by pmverma** [comment]
> i used ./mvnw itself , can you please reproduce this and see if it works?

What issue are you having?

Check more at https://www.jhipster.tech/development/
You can ask at https://stackoverflow.com/questions/tagged/jhipster
