### ISSUE TITLE
Deploying JHipster with a context path breaks SwaggerUI

### ISSUE THREAD

**Issue by clocken** [jhipster/generator-jhipster#12649]
##### **Overview of the issue**

When deploying JHipster with a context path set, one has to change the Webpack configuration and SwaggerUI according to https://www.jhipster.tech/production/#build, otherwise the client app fails to load.
First off, the doc is incomplete as one also has to prepend the `axios.get` call with the context path, like so: `axios.get("/jhipster/swagger-resources")`. Otherwise the SwaggerUI will not load the Resource definitions.
But even if one follows the doc and the above, the SwaggerUI is still broken.

##### **Motivation for or Use Case**

It should be possible to use a context path when deploying JHipster and use the SwaggerUI without further configuration.

##### **Reproduce the error**

* Generate a new JHipster project
* Set `server.servlet.context-path` to desired context
* Make configuration changes according to the doc and the `axios.get` call
* Run `mvn spring-boot:run` on the project

##### **Related issues**

#5620

##### **Suggest a Fix**

Using relative paths would make it possible to set `server.servlet.context-path` and keep the client app runnable without further configuration. I have already made a commit in my fork for that - see: https://github.com/jhipster/generator-jhipster/compare/main...clocken:running-jhipster-on-a-specified-context

There is still an issue with the SwaggerUI though. If a context path is set, the [Docket](https://github.com/jhipster/jhipster/blob/40fe6c2bdf21de95ce99834652585668f603e347/jhipster-framework/src/main/java/io/github/jhipster/config/apidoc/SpringfoxAutoConfiguration.java#L104) will not generate the correct *OAS*.
To fix that for the `default` group one also has to prepend the context path to `jhipster.api-docs.default-include-pattern`.
But for the `management` group the *OAS* will still not be generated as it matches the api resources by `management.endpoints.web.base-path`.
If I am not mistaken, there is currently no way to specify the correct regex matcher for the Management-[Docket](https://github.com/jhipster/jhipster/blob/40fe6c2bdf21de95ce99834652585668f603e347/jhipster-framework/src/main/java/io/github/jhipster/config/apidoc/SpringfoxAutoConfiguration.java#L146).

This leads me to the following suggestions:
* Use the relative paths in the client app as per my commit above
* First option for fixing the SwaggerUI:
  * Figure out the context path inside the Docket's and prepend them transparently to the `jhipster.api-docs.default-include-pattern` and `management.endpoints.web.base-path`.

This would make it possible to create JHipster deployments with a context path without further configuration.

There's also another solution for the SwaggerUI which I include just for completeness as I don't like it very much.
* Second option for fixing the SwaggerUI:
  * set `jhipster.api-docs.default-include-pattern` to `${spring.servlet.context-path:}/api/.*` and
  * introduce a new variable `jhipster.api-docs.management-include-pattern` to specify the regex for the Management-Docket and set it to `${spring.servlet.context-path:}/management/.*`

I don't like it, because it relies on the correct ordering of the properties so Spring will replace them correctly (an extension to the doc with yet another place to add the context path would do, but defeat the purpose of my request :wink:). Also, this would not work when deploying as a WAR to an Appserver with context path configuration outside of JHipster.

If you are willing to discuss this let me know and I will do the necessary implementations and/or doc updates.

##### **JHipster Version(s)**

Used current main.

```
jhipster-app@0.0.1-SNAPSHOT /home/clocken/jhipster-app
└── generator-jhipster@6.10.4 

```
This maybe a regression - see #5620 and PR #5871. I don't know if the change back to absolute paths was on purpose.

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipsterApp",
    "jhipsterVersion": "6.10.4",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1603388507906,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": ["en"]
  }
}

</pre>
</details>

##### **Environment and Tools**

```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

git version 2.17.1

node: v12.18.4

npm: 6.14.6

Docker version 19.03.13, build 4484c46d9d
```
##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

Unrelated, but I am using Linux and Firefox.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Thanks for reporting this bug. If I understand correctly, you are setting the context-path property and the swagger-ui gets broken in this case. I believe this is something that we could support for advanced use cases. However, let's be careful with this as we have to support other use cases such as microservices and access from the JHipster Control Center... Give me a couple of days to try to reproduce your issue and understand the bug.

Also, please always add your JHipster configuration in your ticket (yo-rc.json, version, etc...). Even though you might think it's not relevant please always add it, we need those details to help us investigate the issue. Thanks.

**Comment by mraible** [comment]
Who uses context paths in 2020? :trollface:

**Comment by niutouJust** [comment]
> Who uses context paths in 2020? 
🤣

**Comment by clocken** [comment]
> Thanks for reporting this bug. If I understand correctly, you are setting the context-path property and the swagger-ui gets broken in this case. I believe this is something that we could support for advanced use cases. However, let's be careful with this as we have to support other use cases such as microservices and access from the JHipster Control Center... Give me a couple of days to try to reproduce your issue and understand the bug.

Thanks for addressing this @PierreBesson. That's correct. However, this obviously also applies when generating a WAR file for an application server, say WildFly, and defining the context path in the `jboss-web.xml` for instance.
Regarding microservices, I don't think it would be an issue using relative paths in the client app considering that relative paths have already been used in the past - see PR #5871. But I haven't analyzed this, yet.

> Also, please always add your JHipster configuration in your ticket (yo-rc.json, version, etc...).

I've updated the description of this issue with the relevant info. Sorry for being ignorant about this.

@mraible and @niutouJust: Yeah, I know... But there are still projects out there, that have to embrace the good ol' times :smile:

**Comment by PierreBesson** [comment]
@clocken, I took the liberty to cherry-pick your commit from your branch and implemented your solution 2.

I think this is the less intrusive and the most flexible solution as you can always tweak `jhipster.api-docs.default-include-pattern` and `jhipster.api-docs.management-include-pattern` to make swagger ui works with app server deployment on a context path defined outside of spring. Please review on your side to check the implementation. However you will need the new unrelease jhipster library from https://github.com/jhipster/jhipster-bom/pull/42 that introduce the management include pattern property.

PS: please submit a PR for the h2 issue.

**Comment by clocken** [comment]
@PierreBesson Thanks for the implementation. You're right, especially regarding the intrusiveness of the solution.
But there are some minor adjustments to be made, I think. I implemented them in a separate copy of your branches and commented in the PR's. Feel free to cherry pick again.
By the way: What's the preferred procedure in this situation? Cherry picking or should I have commited to your branch directly?

There is no issue with `h2`. It was just an example of a relative path already being used.

**Comment by pascalgrimaud** [comment]
@clocken @PierreBesson: does the proposed solution works ?
The use case to test, after changing the property:
- start via intellij
- start via mvn
- npm start
- with jar

**Comment by clocken** [comment]
@pascalgrimaud Yes, the proposed solution works.
Though after some more testing I found two more places where relative paths needed to be set in the React and Vue clients. Implemented changes also ready for cherry-picking, if you are satisfied @PierreBesson. PR for the docs also updated.

**Comment by clocken** [comment]
Oh, I thought adding commits would be enough to keep this open. As the work is [nearly finished](https://github.com/jhipster/generator-jhipster/pull/12923#issuecomment-748077732) it would be nice if someone could reopen this. Thanks

**Comment by DanielFran** [comment]
Reopened

**Comment by PierreBesson** [comment]
@pascalgrimaud Could you add a bounty on this, to give to @clocken who did really great work on this over the length of 3 months!

**Comment by pascalgrimaud** [comment]
bounty added

**Comment by clocken** [comment]
Thanks for seeing this through and for the bounty :smiley: I will collect it when this has been merged.
Merry Christmas, despite these weird times!

**Comment by pascalgrimaud** [comment]
Keep it

**Comment by pascalgrimaud** [comment]
Keep it

**Comment by pascalgrimaud** [comment]
Increasing the bounty, so @PierreBesson and @clocken you can share it
Closing this one, as I think it's resolved

**Comment by clocken** [comment]
Bounty claimed => https://opencollective.com/generator-jhipster/expenses/37070

**Comment by pascalgrimaud** [comment]
@clocken : approved
