### ISSUE TITLE
Error: Only 'h2Memory', 'h2Disk', 'mysql' are allowed as devDatabaseType

### ISSUE THREAD

**Issue by MarlonLuan** [jhipster/generator-jhipster#12643]
With the change to set postgres as default, the following error is generated:

```bash
Error: Only 'h2Memory', 'h2Disk', 'mysql' are allowed as devDatabaseType values for databaseType 'sql'.
Error while parsing applications and entities from the JDL Error: Only 'h2Memory', 'h2Disk', 'mysql' are allowed as devDatabaseType values for databaseType 'sql'.
Error: Only 'h2Memory', 'h2Disk', 'mysql' are allowed as devDatabaseType values for databaseType 'sql'.
```

##### **Reproduce the error**

```js
jhipster import-jdl app.jdl 
```

##### **JHipster Version(s)**

master

##### **JHipster configuration**

<details>
<summary>app.jdl file</summary>
<pre>
application {
  config {
    devDatabaseType postgresql
  }
}
</pre>
</details>

**Comment by pascalgrimaud** [comment]
Thanks @MarlonLuan for reporting this, I'm having a look

**Comment by mshima** [comment]
@pascalgrimaud https://github.com/jhipster/generator-jhipster/blob/efd391d5c067227a2e7d5e16de7532d09e35cb5f/jdl/jhipster/default-application-options.js#L198

**Comment by pascalgrimaud** [comment]
Strange, I could reproduce this with 6.10.3, so it doesn't come from my previous PR about PostgreSQL as default database

**Comment by pascalgrimaud** [comment]
OK understood, thanks for pointing this @mshima : do you want to do the PR or I can do it now?

**Comment by mshima** [comment]
Please do it. I am taking a look at microservice/angular bug
