### ISSUE TITLE
chore : use `--no-install-recommends` flag to `apt-get` in dockerfile to save space

### ISSUE THREAD

**Issue by Rajpratik71** [jhipster/generator-jhipster#12648]
##### **Overview of the feature request**

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

##### **Motivation for or Use Case**

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

##### **Related issues or PR**

#12647 

-   [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
The PR #12647 did fix this issue or is there anything left I can't see right now?

**Comment by pascalgrimaud** [comment]
no auto close, so let's close this :)
