### ISSUE TITLE
Bump @ng-bootstrap/ng-bootstrap to 7.0.0

### ISSUE THREAD

**Issue by tillias** [jhipster/generator-jhipster#12656]
##### **Overview of the feature request**

Hello folks,

@ng-bootstrap/ng-bootstrap currently used is targeting angular 9 while jhipster generates with "@angular/core": "10.0.0"

If I update ng-bootstrap to 7.0.0 then I have following warning:
```
npm WARN ng-jhipster@0.15.0 requires a peer of @ng-bootstrap/ng-bootstrap@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-jhipster@0.15.0 requires a peer of @fortawesome/angular-fontawesome@^0.6.1 but none is installed. You must install peer dependencies yourself.
```

##### **Motivation for or Use Case**

To be consistent across libraries

##### **Related issues or PR**

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Can you please create a PR with this change?

**Comment by DanielFran** [comment]
The update has been done in main branch, so closing this issue.
