### ISSUE TITLE
Make Integration Tests more robust

### ISSUE THREAD

**Issue by red0point** [jhipster/generator-jhipster#1265]
The Integration Tests for testing a POST on an entity are carried out like the following (pseudocode);

- assert that the database is empty
- insert an object
- assert that there is exactly one object in the database
- get that object and verify it's the one that has been inserted.

But when loading test-data into that project, the integration tests fail.
I'd suggest following testing pattern:

- get the size of the table
- insert an arbitrary object - store the returned id
- verify that the size has increased by one
- get the object by id and verify it's the one you inserted.

What do you mean?

**Comment by jdubois** [comment]
This is a temporary, in-memory database, how come you have data inside your table?
But I agree, it would be better that way.

**Comment by red0point** [comment]
We just added some test data to be loaded by Liquibase so we can have an in memory DB and at the same time we don't need to add the data manually everytime.
Am 16.03.2015 16:54 schrieb Julien Dubois <notifications@github.com>:This is a temporary, in-memory database, how come you have data inside your table?
But I agree, it would be better that way.

**Comment by jdubois** [comment]
Oh, yes that's a good idea
