### ISSUE TITLE
Bump @fortawesome/angular-fontawesome to 0.7.0

### ISSUE THREAD

**Issue by tillias** [jhipster/generator-jhipster#12657]
##### **Overview of the feature request**

Same as https://github.com/jhipster/generator-jhipster/issues/12656

0.6.0 is targeting angular 9, while jhipster generates with 10: https://www.npmjs.com/package/@fortawesome/angular-fontawesome -> compatibility table

##### **Motivation for or Use Case**

To be consistent across libraries

##### **Related issues or PR**

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Please create a PR to fix this issue. I can add a bug bounty if you need motivation. :)

**Comment by tillias** [comment]
Hi @mraible not needed, I really like jhipster as a very nice product and will check it this week

**Comment by DanielFran** [comment]
The update has been done in main branch, so closing this issue.
