### ISSUE TITLE
Add csp header to allow Google analytics 

### ISSUE THREAD

**Issue by khocef** [jhipster/generator-jhipster#12666]
The SecurityConfiguration is blocking Google Analytics script and requests 
![image](https://user-images.githubusercontent.com/3718899/95264903-72a80b00-0830-11eb-86d7-c2651421b4f8.png)
![image](https://user-images.githubusercontent.com/3718899/95264923-7dfb3680-0830-11eb-809b-273f3eec18b2.png)

**Comment by atomfrede** [comment]
I think this is not a jhipster issue. Did you e.g. looked at https://content-security-policy.com/faq/ and changed the csp accordingly?

**Comment by khocef** [comment]
@atomfrede But since jhipster is providing a Google Analytics configuration in index.html I think it should not be blocked by the csp conf. What do you think ?

**Comment by atomfrede** [comment]
Good point, I would still say we should not change the default generated CSP, instead document what must be changed as google analytics is totally optional to me (apart from the privacy questions regarding google analytics).

**Comment by khocef** [comment]
I dont have a working analytics at the moment but something like this should work

```
 contentSecurityPolicy("default-src 'none';script-src 'self' www.google-analytics.com;img-src www.google-analytics.com;
")
```

**Comment by atomfrede** [comment]
I will have a look at this, while also looking if we have a problem with https://github.com/jhipster/generator-jhipster/issues/12677

**Comment by khocef** [comment]
@mraible  this worked for me 

**index.html**    
```
 <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-XXXXXX-1', 'auto');
    </script>

```

**SecurityConfiguration.java** 

``` 
contentSecurityPolicy("default-src 'self' www.google-analytics.com; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' www.google-analytics.com data:; font-src 'self' data:")
```

**Comment by atomfrede** [comment]
Awesome, thats what I have to. PR will be there in next couple of minutes.
