### ISSUE TITLE
jhipster fails to generate for openshift

### ISSUE THREAD

**Issue by Rajpratik71** [jhipster/generator-jhipster#12675]
##### **Overview of the issue**
PS D:\sterlite\eo-openshift-deployment> jhipster openshift
INFO! Using JHipster version installed globally
INFO! Executing jhipster:openshift
⭕ [*BETA*] Welcome to the JHipster OpenShift Generator ⭕
Files will be generated in folder: D:\sterlite\eo-openshift-deployment or in the root directory path that you select in the subsequent step
√ Docker is installed
WARNING! oc 1.3 or later is not installed on your computer.
Make sure you have OpenShift Origin / OpenShift Container Platform and CLI installed. Read https://github.com/openshift/origin/

? Which *type* of application would you like to deploy? Microservice application
? Enter the root directory where your gateway(s) and microservices are located ../
5 applications found at D:\sterlite\

? Which applications do you want to include in your configuration? applicationlcm, edgeorchestrator, eo-ui-gateway, uaa
? Do you want to setup monitoring for your applications ? Yes, for metrics only with Prometheus
JHipster registry detected as the service discovery and configuration provider used by your apps
? Enter the admin password used to secure the JHipster Registry sterlite
? What should we use for the OpenShift namespace? eo
? Which *type* of database storage would you like to use? Persistent Storage
? What should we use for the base Docker repository name? 172.30.162.84:5000/sterlite
? What command should we use for push Docker image to repository? docker push

Checking Docker images in applications directories...
ls: no such file or directory: D:/sterlite/applicationlcm/target/jib-cache
ls: no such file or directory: D:/sterlite/edgeorchestrator/target/jib-cache
ls: no such file or directory: D:/sterlite/eo-ui-gateway/target/jib-cache
ls: no such file or directory: D:/sterlite/uaa/target/jib-cache
ERROR! Copying template deployment.yml.ejs failed. [ReferenceError: C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\generators\openshift\templates\deployment.yml.ejs:221
    219|               value: jhipster-kafka:9092
    220|             - name: KAFKA_CONSUMER_GROUP_ID
 >> 221|               value: '<%= dasherizedBaseName %>'
    222|             - name: KAFKA_CONSUMER_AUTO_OFFSET_RESET
    223|               value: 'earliest'
    224|             - name: KAFKA_PRODUCER_BOOTSTRAP_SERVERS

dasherizedBaseName is not defined]
Error: Copying template deployment.yml.ejs failed. [ReferenceError: C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\generators\openshift\templates\deployment.yml.ejs:221
    219|               value: jhipster-kafka:9092
    220|             - name: KAFKA_CONSUMER_GROUP_ID
 >> 221|               value: '<%= dasherizedBaseName %>'
    222|             - name: KAFKA_CONSUMER_AUTO_OFFSET_RESET
    223|               value: 'earliest'
    224|             - name: KAFKA_PRODUCER_BOOTSTRAP_SERVERS

dasherizedBaseName is not defined]
    at module.exports.error (C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base.js:1590:15)
    at C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\generators\utils.js:256:23
    at tryHandleCache (C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\ejs\lib\ejs.js:275:14)
    at Object.exports.renderFile (C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\ejs\lib\ejs.js:489:10)
    at Object.renderContent (C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\generators\utils.js:252:9)
    at module.exports.template (C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base-private.js:769:23)
    at module.exports.writeDeployments (C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\generators\openshift\files.js:29:22)
    at Object.<anonymous> (C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:976:25)
    at C:\Users\pratik.raj\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)

##### **JHipster configuration**

PS D:\sterlite\eo-openshift-deployment> jhipster info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
D:\sterlite\eo-openshift-deployment
`--  JHipster v6.10.1

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment 18.9 (build 11.0.8+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10, mixed mode)

git version 2.27.0.windows.1

node: v12.18.2

npm: 6.14.5

Docker version 19.03.3, build 2355349d-

docker-compose version 1.26.0, build d4451659

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not applicable

##### **Browsers and Operating System**

Windows 10

-   [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@Rajpratik71 : 
Sorry about that. But to be honest, we have very few feedback about OpenShift sub generator, and it's not well maintained... I wonder if we should keep this sub generator.
If you know how to fix it, feel free to help

I use OpenShift for my customer but we don't use this sub generator because:
- it doesn't fit to our needs
- it's broken

**Comment by mraible** [comment]
This seems like a good opportunity to start removing stuff that’s not supported well by its providers.

**Comment by Rajpratik71** [comment]
> @Rajpratik71 :
> Sorry about that. But to be honest, we have very few feedback about OpenShift sub generator, and it's not well maintained... I wonder if we should keep this sub generator.
> If you know how to fix it, feel free to help
> 
> I use OpenShift for my customer but we don't use this sub generator because:
> 
> * it doesn't fit to our needs
> * it's broken

Ok , Sure I will try to debug the issue , find the cause and will update here.

**Comment by mraible** [comment]
I'm going to assume this is fixed in v7. If it's not, please reopen this issue.
