### ISSUE TITLE
Support for File Upload

### ISSUE THREAD

**Issue by red0point** [jhipster/generator-jhipster#1267]
I'm currently struggling to implement a File Upload functionality with Oauth with JHipster and authenticated users using oauth. Does anybody have any tested methodologies for accomplishing just that?

I'm struggling with supplying the correct headers for the upload request when using Oauth. Is there any documentation? I didn't find anything on the JHipster Website.

Any plans for integrating file upload directly into JHipster? Maybe as a separate Entity with a relation to own entities? Or as an attribute?

**Comment by jdubois** [comment]
No, nothing planned at the moment.
I've already implemented this for https://github.com/ippontech/tatami -> we just used https://github.com/blueimp/jQuery-File-Upload and connected it to a Spring MVC controller. I don't know what OAuth adds to that (excepted a specific header with the token), but that shouldn't be too difficult.

For me this goes too far for JHipster, at least for the moment, so we will not do it. But indeed, if you have some documentation, or a blog post, we could document it here in this ticket.
