### ISSUE TITLE
RTL: CSS Fine tuning is needed for all frameworks

### ISSUE THREAD

**Issue by yehudab** [jhipster/generator-jhipster#12682]
##### **Overview of the issue**

Some elements on the app are still not mirrored correctly. E.g., The `Development` ribbon stays on the left, while it should move to the right, etc.

##### **Motivation for or Use Case**

Better support for RTL languages

##### **Reproduce the error**

Create a jhipster app for angular/react/vue with support for an RTL language such as Arabic

##### **Related issues**

This is a followup to #12384. 

##### **Suggest a Fix**

1. Add more `[dir=rtl]` rules to `rtl.scss` as needed
2. There are now 3 exact copies of the same file `rtl.scss`. For better maintenance, it is desired to move this file to a common folder and reuse it for all 3 frameworks

##### **JHipster Version(s)**

6.10.3

##### **Browsers and Operating System**

Windows 10, Chrome, Firefox

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@yehudab : approved
