### ISSUE TITLE
Unauthorized Access Denied

### ISSUE THREAD

**Issue by houcine8** [jhipster/generator-jhipster#1268]
I generate my data model which contains team entity.
I want to access this entity without authentication so I try to test it before by putting url service for getting all teams. ("172.0.0.1:8080/api/teams")
but I have this problem: Unauthorized access denied!
Any help?

**Comment by jdubois** [comment]
- This is not a bug
- Your security configuration is in the SecurityConfiguration class, and by default you need to be authenticated. By default we are secured, but of course you can (should?) reconfigure this for your specific use case.

**Comment by houcine8** [comment]
Thank you,
I have two project jhipster type one with httpAuth configuration and other with OAuth2 configuration.
So this solution is possible with httpAuth configuration by adding antMatchers("/api/**").permitAll();
but with OAuth2 configuration I haven't find where I can add this instruction.

**Comment by houcine8** [comment]
I find it in the OAuth2ServerConfiguration you can manage all your authentication entrypoint.
Thank you
