### ISSUE TITLE
Provide extensibility to use other frontend module bundler

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#12697]
##### **Overview of the feature request**

Currently, in all frontend framework implementations (`react`, `vue`, `angular`), `webpack` is used as a module bundler and the bundler name (webpack) is hard-coded in all scripts (including server side, CI). It leaves little option as blueprint authors to try other module bundlers like `rollup` and `parcel`.

I suggest to externalize the module bundler name as an option (like used for `yarn` before) and keep `webpack` as default option value (like used for `npm` before). 

##### **Motivation for or Use Case**

As a blueprint author, I would like to use `rollup` or `parcel` instead of `webpack` without overriding server-side code and scripts.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
feel free to refactorize this part @vishal423 if it can help for your blueprint

**Comment by vishal423** [comment]
I was thinking a little more about this. How about using generic names in shared generators? Like change scripts in client generator to ensure following in the `pom.xml`:
profile id `webpack` to `webapp`
run `webpack:build` to `webapp:build:dev`
run `webpack:test` to `webapp:test`
run `webpack:prod` to `webapp:build`

**Comment by mshima** [comment]
@vishal423 do you want to provide the PR?
This npm commands should be stable during jhipster 7 cycle.

**Comment by vishal423** [comment]
@mshima, I will try to create PR over the weekend. I don't see any complexity on this change and will keep it backward compatible (not removing old scripts)

**Comment by vishal423** [comment]
Closing as the issue has been addressed.
