### ISSUE TITLE
Missing License on jhipster / jhipster-sample-app

### ISSUE THREAD

**Issue by MK-2001** [jhipster/generator-jhipster#12695]
##### **Overview of the issue**

To use the code in my projects, I need the information to the underling license.
Please add a LICENSE.md into the REPO jhipster/jhipster-sample-app.

##### **Motivation for or Use Case**

No usage allowed without license information

##### **Suggest a Fix**

Please add a LICENSE.md into the REPO jhipster/jhipster-sample-app.

##### **JHipster Version(s)**

jhipster/jhipster-sample-app.

**Comment by pascalgrimaud** [comment]
Agree with you.
This project is automatically generated when doing a release, and currently, we don't have option to add default license. That's the reason why it's missing

**Comment by pascalgrimaud** [comment]
Closing this as license was added to all sample projects
