### ISSUE TITLE
JHipster with Keycloak with HTTPS

### ISSUE THREAD

**Issue by neokeld** [jhipster/generator-jhipster#12699]
##### **Overview of the issue**

Trying to use JHipster with Angular/Spring Boot, with Keycloak with https activated, i have this stack trace:
_Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 107 common frames omitted_

It seems that JHipster try to send a client certificate.
I have tried to provide a truststore (through my JVM) with a certificate and i have the same error.
I have tried to disable X509 in Keycloak and i have the same error.
Do you know this issue ?

##### **Motivation for or Use Case**

I can't use Keycloak with https.

##### **Reproduce the error**

Install Keycloak. Generate a Spring Boot / Keycloak.

##### **JHipster Version(s)**

6.8.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules 
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
@0.0.1-SNAPSHOT C:\Users\\IdeaProjects\-projects\-
`-- generator-jhipster@6.8.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": "consul",
    "skipUserManagement": true,
    "baseName": "",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "skipClient": false,
    "testFrameworks": ["protractor", "cucumber", "gatling"],
    "websocket": "spring-websocket",
    "applicationType": "gateway",
    "packageName": "com...",
    "packageFolder": "com///",
    "clientTheme": "sketchy",
    "clientThemeVariant": "primary",
    "useSass": true,
    "jhipsterVersion": "6.8.0",
    "creationTimestamp": 1588169160014,
    "skipServer": false,
    "clientPackageManager": "npm",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": [],
    "skipFakeData": true
  },
  "entities": ["User", "Application", "Application", "Workspace", "Analysis"]
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

git version 2.27.0.windows.1

node: v12.18.0

npm: 6.14.4

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.27.4, build 40524192

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Windows / CentOS / Firefox

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Duplicate of #12700
