### ISSUE TITLE
Constants from Spring configuration

### ISSUE THREAD

**Issue by danaki** [jhipster/generator-jhipster#1269]
It is convenient to have some Spring constants from application-*.yml files be available for Angular app. For example, facebook app can be configured in spring.social.facebook.app_id with facebook's 'secret' in application.yml for social login, and the same app_id can be auto exported to app.constants.js. This is feature request, I guess there can be better approach.

**Comment by jdubois** [comment]
You are correct, that would be convenient, however the AngularJS app does not have access to that file... We have our internal configuration here, like the database password, so of course we don't want this accessible from the AngularJS app.
Let me think if we can fin a better solution.

**Comment by danaki** [comment]
I did this for my project:
```
        ngconstant: {
            options: {
...
                constants: {
                    FACEBOOK_APP_ID: grunt.file.readYAML('src/main/resources/config/application.yml', "utf8")['spring']['social']['facebook']['clientId']
                }
            },
...
        }
```

Hence, I prefer convention over configuration, so such custom code could require additional excess configuration. What if Grunt read a separate .yml or .properties or a section inside application.yml (if exists, let's call it "export") and put everything it finds to ngconstant replacing characters by convention (so in my case const would become SPRING_SOCIAL_FACEBOOK_CLIENTID)

**Comment by jdubois** [comment]
That's a nice tip!!
Still, I'm worried that people might expose server side information by error.

**Comment by jdubois** [comment]
OK, so it's really a nice idea, but I'm too worried that people think it's a "normal" way to expose configuration to the client side, and end up exporting sensitive information (like security information), so we will not provide this by default.

**Comment by ppawel** [comment]
Why did you close this? It's one of the obvious things that you need for any production application...

**Comment by deepu105** [comment]
@ppawel we already expose all the configuration via an authenticated url which is displayed in the configuration screen under admin. So you can call the `JhiConfigurationService` on angularJS and use the `getEnv` method to get all the properties on the `*.yml` files and environment. You just need to filter what you want and ofcourse all the passwords would be hidden as asterisks.
