### ISSUE TITLE
Implement cache at github actions.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12693]
##### **Overview of the feature request**

Add npm, maven, gradle, cypress caching to worflows.

##### **Motivation for or Use Case**

May prevent network random failures.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I started study it, but I don't find enough information about matrix caches.

**Comment by murdos** [comment]
It was on my radar too 😄

**Comment by pascalgrimaud** [comment]
we have a lot of parallel builds, and we have 5gb to store cache.
I think it can be a problem

**Comment by mshima** [comment]
> we have a lot of parallel builds, and we have 5gb to store cache.
> I think it can be a problem

Cache doesn't count. Only upload-artifact action like cypress screenshots.
I will create a PR.
