### ISSUE TITLE
Hexagonal architecture friendly.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12702]
##### **Overview of the feature request**

This issue is to track hexagonal architecture related issues and keep references.
If any core contributor thinks this should not happen, please manifest.

Update the issue description instead of adding new comment for new references.

Discussion on this issue will be locked.

##### **Motivation for or Use Case**

Following some principles of hexagonal architecture would make easier for the developer to keep they code separated from jhipster generated source. Improving maintainability.

We should focus on allowing jhipster to generate source with hexagonal architecture.
We should try to not discuss structure specifics.

##### **References**

https://github.com/peholmst/learning-content/blob/author/petter-holmstrom/ddd-part-4/learn/tutorials/ddd/03__ddd_and_hexagonal/content.adoc

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@mshima : any specific reason to lock the thread to collaborators ?

**Comment by mshima** [comment]
> @mshima : any specific reason to lock the thread to collaborators ?

I want to create a separated issue for each subject and discuss there.

**Comment by pascalgrimaud** [comment]
In the ream, only @hdurix, you and I have interest on this. That's why I'd prefer to open the discussion to all users :)

**Comment by mshima** [comment]
@pascalgrimaud not sure this is true, most of the members aren’t interested in DDD. Hexagonal is a different discussion.
But feel free to open, I just think this is too big for one issue.
