### ISSUE TITLE
Change current DTO implementation

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12707]
##### **Overview of the feature request**

Current DTO implementation flattens id and label from a child to its parent when relationship is `one-to-one`.
IMO we should keep hierarchical implementation for consistency.

##### **Motivation for or Use Case**

Flattening relationships makes templates more complicated.
I don't see benefits to flattened relationship.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by tillias** [comment]
@mshima may I ask if what you want in this ticket is exactly the same I desperately need in my project?

Let's say I have following dto:

```
public class HouseDTO {
    private Long id;
    private String name;
    private String description;
    private String url;
    private Long ownerId;
}

private class OwnerDTO {
    private Long id;
    private String name;
}

```
If I need full entity in front-end (and I'm using Angular) then I can do the following:

```
public class HouseFullDTO {
    private Long id;
    private String name;
    private String description;
    private String url;
    private OwnerDTO owner;
}
```
In the Back-End it work just fine (you can even introduce **HouseBaseDTO** and move all except Owner to it). But Front-End is painful like a hell! 

**Waaaaay more cleaner solution** will be delivering one DTO for all cases, but by default **OwnerDTO** in the example below should contain only ID filled: 
```
public class HouseFullDTO {
    private Long id;
    private String name;
    private String description;
    private String url;
    private OwnerDTO owner;
}
```

**Comment by mshima** [comment]
@tillias something like this but with reference dto:
```
public class HouseDTO {
    private Long id;
    private String name;
    private String description;
    private String url;
    private OwnerRefDTO owner;
}

private class OwnerRefDTO {
    private Long id;
    private String name;
}

private class OwnerDTO extends OwnerRefDTO {
    private String birthday;
}

```

Related to https://github.com/jhipster/generator-jhipster/issues/12374

**Comment by tillias** [comment]
Will this also include front-end entities? What is **name** in RefDTO? Which field to take if there is no **name** field in the entity?

**Comment by mshima** [comment]
@tillias updated the example.
name is the value field (label) that jhipster allows to add to each relationship, it can be missing.

**Comment by mshima** [comment]
> Will this also include front-end entities?

It must include, otherwise it won't work.

**Comment by tillias** [comment]
Ok, then I don't get it how it will make life easier and we're talking about two completely different issues.

Let's say I have following component: https://github.com/tillias/microservice-catalog/blob/master/src/main/webapp/app/entities/microservice/microservice-dashboard/microservice-card/microservice-card.component.html

It receives IMicroservice entity which contains (Team, Status) custom attributes. With your approach it will be replaced with Ref object which delivers nothing but ID, so it will be exactly the same problem with templates.

With my suggestion you simply need to write custom mapper in BE and additional method in FE. That was it.

**Comment by mshima** [comment]
> Ok, then I don't get it how it will make life easier and we're talking about two completely different issues.

If you need the complete object, just change owner to use OwnerDTO instead of HouseOwnerReferenceDTO
This approach:
- Can be used with maptstruct, otherwise we should create our own mapper for each relationship.
- Safeguard for data leak.
- Api compatibility, just less data.
- Cyclic relationship safe.

JHipster should provide the full object reference for Value Objects like embedded, cascade all relationships.

**Comment by tillias** [comment]
Ok I see, so this means either support use-case when partial object is needed or use-case when full object is needed. But not both use-case simultaneously. That is indeed interesting approach, but this will still require manual adaption of all entities (both BE and FE). After this adaption you will still have to adapt UI templates as well.

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/issues/12779 seems @valueObject(cascade) I have in an internal implementation.
- Parent needs to have reference to full Child implementation.
- Guarantee Childs are eager loaded.
- Add Cascade.ALL to the parent -> child relationship.

**Comment by tillias** [comment]
Just to be on a safe side, no offence meant, I do understand and value what you're doing here guys, very much appreciated! My use-case was more related to overwriting custom logic (especially in "domain entities"). I wish there was https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods in Java :(

**Comment by gzsombor** [comment]
@tillias : I don't understand, why the proposed approach works on the backend, but it's painful on the frontend? What makes the frontend so special?
 In my experience, using inheritence in the DTO objects works neatly. I have : 
* IdDTO(Long id)
* NamedDTO(String name) + extends IdDTO
* HouseListDTO(couple of fields for listing) + extends NamedDTO
* HouseDetailDTO(everything with references to other entities) + extends HouseListDTO
* HouseUpdateDTO(fields which can be updated) 
* HouseCreationDTO( fields required for creation)

Yes, there are lot of different types, but the compiler is there, and there is no confusion, what fields are filled, and what not. And yes, there is no custom logic in the DTO, they are just for defining the protocol, the available fields.

**Comment by tillias** [comment]
@gzsombor proposed approach doesn't work neither in BE nor in FE. Sorry for misunderstanding, I'll blogpost about it next week
