### ISSUE TITLE
Server-side sorting using Spring Data

### ISSUE THREAD

**Issue by ddewaele** [jhipster/generator-jhipster#1270]
I appreciate the fact that jHipster aims to bootstrap users using a plain vanilla AngularJS app, but I was wondering if server-side sorting could be offered.

Server-side pagination (using Spring Data) is already included so I guess adding server-side sorting wouldn't be that more intrusive.

I do realise that include a lot of additional libs and third party stuff i not desirable:

- https://github.com/jhipster/generator-jhipster/issues/668
- https://github.com/jhipster/generator-jhipster/issues/797

But wouldn't it be "simply" a matter of :

- Extend the REST layer to accept an optional sortOrder / sortDirection combo.
- Extend the PaginationUtil to create a Pageable that includes the sorting info
- Adding a ng-click on the column headers
- Add some glue in the controller to link everything together

I don't know what other REST layers / databases are currently support, but if we currently stick with Spring Data this shouldn't be that intrusive.

I can send you a pull request that adds server-side sorting if you want, or upload a sample app that demonstrates the technique.

**Comment by jdubois** [comment]
Yes that would be a good idea -> as this add another layer of code, maybe that should be an option in the entity sub-generator? Like with ask for pagination, we could also ask for sorting?

And yes, if it only works with JPA that's fine -> I don't know MongoDB well enough to code this properly, and with Cassandra it is just not possible to have this working.

If you can do a PR that would be great!

**Comment by rblazquez** [comment]
Hope this succeeds. I've been reading discussions on #668 #797

Even for a simple CRUD application paging, sorting, and searching are a must.

Im concerned about the choice of sortOrder sortDirection combo. If you want to allow a future multiple sorting feature the choice of this would be important. If you choose two different parameters it would be difficult to implement since you will have to match pairs and many corner cases has to be considered. Instead what i've seen in other REST APIs and i've finally used is a single parameter with order and direction info like "sort=+name", "sort=-name" ... note also that order(name, year) is different result than order(year,name) so it would be worthy to have multiple values instead of allowing multiple sort parameter entries so "sort=name,-year" is one option. 

Just a suggestion.

**Comment by tagliola** [comment]
+1 rblazquez

**Comment by ddewaele** [comment]
Why isn't rblazquez comment showing up as a comment here ?

Can we use this for inspiration ? 

From : http://docs.spring.io/spring-data/rest/docs/current/reference/html/#paging-and-sorting.sorting

```
curl -v "http://localhost:8080/people/search/nameStartsWith?name=K&sort=name,desc"
```

*To sort the results by more than one property, keep adding as many sort=PROPERTY parameters as you need. They will be added to the Pageable in the order they appear in the query string.*

So a single field is encapsulated in a single sort query param.
Convention = [sortProperty],[sortOrder]

I can deliver a PR for this by the end of day. Already completed most of it. Just need to add the multiple column sorting.

**Comment by rasheedamir** [comment]
+1 @ddewaele

**Comment by rblazquez** [comment]
@ddewaele i've removed my comment since i realized that Spring has another formar to organize the multiple sort + direction parameters. Ive used the sort=[+/-]attribute1, [+/-]atributte2, ... notation that i've seen in other APIs but maybe it would be wiser to keep close to the std. spring format.

The usual standar spring, at least in spring-data-rest, is:

sort=field&field.dir=[asc/desc]

**Comment by ddewaele** [comment]
@rblazquez : 

According to http://docs.spring.io/spring-data/rest/docs/current/reference/html/#paging-and-sorting.sorting , the syntax for multiple column sorting would be 

```
?sort=field1,asc&sort=field2,desc&sort=field3,asc
```
So multiple sort query params, containing a comma seperated string (fieldname,direction).

This is the format I'm currently working with ....  Where did you see that ```field.dir``` reference ?

**Comment by ddewaele** [comment]
Sorry for the delay on this ... I've got a fork setup with a [basic implementation](https://github.com/ddewaele/generator-jhipster/tree/server-side-sorting)

What it currently does

## HTML template
On the html table, made the columns clickable. Upon clicking a ```loadPageSorted``` is executed on the controller, setting the correct sort property (propertyname + toggling direction)

## Angular Controller
In the controller, a loadPageSorted is added and a sorts array is maintained.
sorts array contains ```"property,direction"``` combos.
In the jHipster generated app, there will always be just 1-column sorting.
```
$scope.sorts = ["id,asc"];
```

## Spring REST layer

Using a registerCustomEditor, to avoid Spring interpreting ```"id,asc"``` as an array. We want to have an array of sort strings 

- ```["id,asc"]```
- ```["id,asc","name,desc"]```

as described by the Spring API.

REST layer converts this to a proper Spring Sort object using the SortQueryParamConverter

## TODOs

- CSS to show a pointer when clicking on a column
- Add questions during the scaffolding to either make the sorting optional (similar to pagination) or club sorting / pagination together.

All comments are welcome.

**Comment by jdubois** [comment]
Yes that looks like a cool feature, but isn't it a bit complex to set up?
Can you point me to your code change, so I can have a look?

**Comment by ddewaele** [comment]
@jdubois : I don't think it's that complex. I've got a fork over here where you can see the code changes to the jHipster generator : https://github.com/jhipster/generator-jhipster/compare/master...ddewaele:server-side-sorting

**Comment by jdubois** [comment]
@ddewaele indeed, it doesn't look very complex.

As nobody as commented on this, and as I didn't see anybody else with this request, I don't think a lot of people have this requirement.
And as it adds more code, I don't think we should do it unless we have enough people asking for it, this is why I'm closing it.

But I agree it's nice, and not very complex to do, so I'm very open to do this later

**Comment by rblazquez** [comment]
Sorry guys, i think this was "on track" with the work made by @ddewaele

Sorting is essential feature to me and all my working environment (clients, workmates)

If it can be planned for any release would be a very nice feature IMHO.

**Comment by ddewaele** [comment]
Back from holiday tomorrow. I can update this pull request with the latest
jhipster developments if enough people like this feature and there is a
chance it gets merged :)

**Comment by deepu105** [comment]
I like the idea, and i guess there is still interest in this. But like how
@jdubois pointed out it would be nice if you can simplify your
implementation. Take a look at this PR for improving pagination abstraction
as well
https://github.com/jhipster/generator-jhipster/pull/1920#issuecomment-135320187
Back from holiday tomorrow. I can update this pull request with the latest
jhipster developments if enough people like this feature and there is a
chance it gets merged :)

On Thursday, August 27, 2015, rblazquez <notifications@github.com> wrote:

> Sorry guys, i think this was "on track" with the work made by @ddewaele
> <https://github.com/ddewaele>
>
> Sorting is essential feature to me and all my working environment
> (clients, workmates)
>
> If it can be planned for any release would be a very nice feature IMHO.
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/jhipster/generator-jhipster/issues/1270#issuecomment-135525645
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/1270#issuecomment-135530694>
.

**Comment by rblazquez** [comment]
Nice! ... the Page and Pageable interfaces has support for Sort params ... but some work will be required to adapt @ddewaele original code. Still most of the work is already done and is not very complex stuff.

Thanks!

**Comment by 0loky0** [comment]
Hey !

Hope one day jhipster will integrate a native clean, best practice way for " real world " remote sorting/searching form auto genenated CRUD.

Few issues about it : 
https://github.com/jhipster/generator-jhipster/issues/797
https://github.com/jhipster/generator-jhipster/issues/993 (mine)

Don't understand why it's not on the map.

**Comment by devedipoint** [comment]
:+1:

**Comment by blacar** [comment]
Could this issue get reopened?

**Comment by deepu105** [comment]
Ok but are you gonna work on this? 
@jdubois ill reopen this for now, if no development we can close it later

**Comment by jdubois** [comment]
Yes and as long as the result is very simple -> from my understanding most of it should already be available from Spring Data

**Comment by rblazquez** [comment]
Since  "Support for pagination abstraction instead of request parameters #1920 " is already merged to master it should be easy to create a simplified version of the work done by @ddewaele.

PageableHandlerMethodArgumentResolver has a default SortHandlerMethodArgumentResolver so if we keep in standard request params then backend side work is fully provided by spring.

... so it would be a matter of adapting the frontend side

am i right?

**Comment by rblazquez** [comment]
Im doing some work but not skilled in advanced JS tasks ... once changes made to html, css, and JS stuff ... how can i test it?

**Comment by erkieh** [comment]
@rblazquez Are you working on this?

**Comment by AVE-cesar** [comment]
:+1:

**Comment by pkcool** [comment]
+1

**Comment by deepu105** [comment]
@rblazquez are you working on this? This is open for quite some time if no one is interested we will close this

**Comment by deepu105** [comment]
@ddewaele do you wanna PR this?

**Comment by jdubois** [comment]
@deepu105 let's close this if nobody works on it

I'm sorry to everyone interested in this, but we all work on our free time for this, and there are just too many opened bugs at the moment, we can't do everything.

**Comment by geraldhumphries** [comment]
I have a very simple implementation of server side sorting. It only works if pagination/infinite scrolling is enabled and can only sort on one column. It uses the same vernacular as other parts of the application, but I'm not sure if I like calling the direction variable "reverse" or even using a boolean with a ternary.

https://gist.github.com/geraldhumphries/e0ed743dc4162ac02f3d

**Comment by deepu105** [comment]
Its ok if it works only with pagination, but its doesnt add much value if it is only for one column.
So im closing this. feelfree to open a new issue and reference this if anyone is interested in implementing this with all columns sort

**Comment by deepu105** [comment]
@geraldhumphries I looked at your gist, your predicate can be bound to multiple columns easily right? if you can make it work for all columns then we can merge that, I guess its ok to have sort enabled only when pagination is enabled as well. plzlet me know if you can work on it then ill re open this issue

**Comment by geraldhumphries** [comment]
@deepu105 It is capable of sorting on all columns, but can only do one column at a time. When you click to sort the second column it gets rid of the sort on the first one. Sorry I wasn't clear. Sorting on multiple columns at once is more complex.

**Comment by deepu105** [comment]
ya that's fine and normal behavior for most table sort plugins, can you
cleanup and PR that? @jdubois, what do you think about making pagination
and sort a single option? since sort will work only when pagination is
enabled we can ask something like "do you want to enable server side
pagination and sort?"

On Tue, Nov 10, 2015 at 12:24 PM, Gerald Humphries <notifications@github.com
> wrote:

> @deepu105 <https://github.com/deepu105> It is capable of sorting on all
> columns, but can only do one column at a time. When you click to sort the
> second column it gets rid of the sort on the first one. Sorry I wasn't
> clear. Sorting on multiple columns at once is more complex.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1270#issuecomment-155282465>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by pkcool** [comment]
sorting one column at a time is good for me, don't need sorting on multiple columns.

**Comment by geraldhumphries** [comment]
I might be able to make sorting work without pagination, but it would have to be client-side. I am working on the PR right now.

**Comment by geraldhumphries** [comment]
In case anyone missed it, server-side entity sorting went into release 2.25.0.
