### ISSUE TITLE
Upgrade to webpack 5

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#12712]
##### **Overview of the feature request**

Released today! https://twitter.com/thelarkinn/status/1315062117221851136?s=21

##### **Motivation for or Use Case**

It will make micro frontends easier to implement.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I don't think this will be easy, so I'm assigning a bug bounty to this. I can increase the amount if requested.

**Comment by mshima** [comment]
I will be working on this.

**Comment by mshima** [comment]
@mraible `@angular/cli@10` will not provide support for webpack@5 https://github.com/angular/angular-cli/issues/17555#issuecomment-701359679.
`@angular/cli@10` has a peer dependency on webpack@4, so it will conflict with https://github.com/jhipster/generator-jhipster/issues/12747.

At angular front, webpack@5 will happen by default with angular@11 only.
Don't have time to look at others frameworks now.

**Comment by gmarziou** [comment]
Once #10624 is complete, this would come "for free"

**Comment by mshima** [comment]
@artemis-bot there is nothing we can do for angular in our side right now.
We need to wait webpack 5 support from dependencies like https://www.npmjs.com/package/@angular-builders/custom-webpack.

**Comment by pascalgrimaud** [comment]
still in todo list

**Comment by krusche** [comment]
any news here?

**Comment by Tcharl** [comment]
`@angular-builders/custom-webpack` 11 has been published 18 days ago and it seems to have [fixed the webpack-5 issue](https://github.com/just-jeb/angular-builders/issues/841)

**Comment by mshima** [comment]
At angular part, we should wait for angular-cli to support webpack@5.
Currently the only way is to use yarn resolution and force it.
IFAIK our angular implementation is ready.
Dependencies without webpack@5 is angular-cli and ng-bootstrap.

**Comment by mshima** [comment]
Angular how to added at https://github.com/jhipster/generator-jhipster/issues/13642#issuecomment-763798399
