### ISSUE TITLE
Health Check UI displays nothing when the GET 'management/health' returns 503 server error

### ISSUE THREAD

**Issue by jgdvarun60** [jhipster/generator-jhipster#12713]
**Expected**: To mark the status representing application DOWN in Red colour others in green colour 
**Actual**: No data is seen under Health Table, as axios.get('...') throws error on 503 and payload is set as undefined

**Solution**: Maybe to use .catch(error => error.response) as shown below to catch error and set the payload that can be displayed in UI.
in the file [administration.reducer.ts] 

```
// Actions
export const systemHealth = () => ({
  type: ACTION_TYPES.FETCH_HEALTH,
  payload: axios.get('management/health').catch(error => error.response)
});
```

**Comment by mraible** [comment]
Closing because no response from bug reporter. Please reopen if you're experiencing this with JHipster 7.
