### ISSUE TITLE
Add Pluralization

### ISSUE THREAD

**Issue by ratonlarvor** [jhipster/generator-jhipster#1273]
That could be interesting to think about plurialization in the generator.

Angular-translate does already manage that: http://angular-translate.github.io/docs/#/guide/14_pluralization

That could be interesting for the backend as well

**Comment by jdubois** [comment]
This is a duplicate from #1029

Yes it would be better, but:

- There is clearly a lack of interest: last time nobody worked on this subject
- It would break a lot of existing things
- We need to make sure we have the same mecanism for the front end and the back end

I'm letting this opened for a couple of days, and if nobody picks it up, I will close it.

**Comment by leonardoavs** [comment]
+1 to pluralization

**Comment by ratonlarvor** [comment]
OK, I can work on it ASAP and will let you know by a pull request ;)

**Comment by jdubois** [comment]
Closed as not active
