### ISSUE TITLE
Implement dependabot automerge.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12746]
##### **Overview of the feature request**

Implement a dependabot auto merge workflow for package.json.
Dependabot 2 does not support auto merge and there is no plans to do so.
The reason for no auto merge is to force the user to validate the release before updating to it.
With that in mind I want to discuss if we should create auto merge workflow..

The workflow would be based on the idea of https://github.com/dependabot/dependabot-core/issues/2268#issuecomment-654608325.

##### **Motivation for or Use Case**

Dependency updates can be tedious:
- We have 4 package.json files instead of 1 like normal projects.
- We don't have manpower to manually test every dependency up.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
dependabot already helps us a lot, by upgrading some dependencies
It doesn't consume too much time to check quickly what's changed before merging it. 

Then, I prefer to manually check if there is a major version

So to resume my idea:
- auto merge: patch, minor
- manual merge: major

But not sure it's worth to do this. I suggest to spend time on other stuff :)

**Comment by mshima** [comment]
For future reference https://github.com/dependabot/fetch-metadata#enabling-auto-merge.

**Comment by pascalgrimaud** [comment]
Thanks for pointing it, @mshima 
I think it's a good idea to auto merge patch and minor version

**Comment by mshima** [comment]
@pascalgrimaud can you enable auto-merge at generator-jhipster repository?

**Comment by pascalgrimaud** [comment]
it's already the case:

![image](https://user-images.githubusercontent.com/9156882/158602503-4b46c7a0-aada-4b58-bd8e-654cf40b8134.png)

Is it ok ?

**Comment by mshima** [comment]
@pascalgrimaud yes, thanks.

**Comment by mshima** [comment]
Closed in https://github.com/jhipster/generator-jhipster/pull/18134

**Comment by mshima** [comment]
Not working as expected.
Probably we will need to protect the branch and add auto approve workflow

**Comment by pascalgrimaud** [comment]
We implement it in JHipster Lite and it seems to work as expected.
What is the problem here?

**Comment by mshima** [comment]
PRs are merged without waiting for tests to finish.
Just triggered a Dependabot update to test.
3 pr were created and merged.

**Comment by pascalgrimaud** [comment]
Yes same happened yesterday, I think it's because of incidents with all github, but not sure
See https://www.githubstatus.com/

**Comment by mshima** [comment]
Unfortunately this is a known issue.
@pascalgrimaud can you enable Branches -> add branch protection rules -> main  with `Require status checks to pass before merging`

**Comment by pascalgrimaud** [comment]
@mshima : just done for main branch :

![Screenshot_20220318-063158](https://user-images.githubusercontent.com/9156882/158943511-1672815e-b485-4f26-a3ea-6e4db0508af0.png)

**Comment by pascalgrimaud** [comment]
I think you're right @mshima 
It seems to not work as intended

**Comment by mshima** [comment]
PR needs to be at a blocked state, otherwise it's merged by auto merge.

**Comment by pascalgrimaud** [comment]
> PR needs to be at a blocked state, otherwise it's merged by auto merge.

@mshima : I don't understand. Do you need me to configure something else ?

**Comment by mshima** [comment]
> Do you need me to configure something else ?

Once https://github.com/jhipster/generator-jhipster/pull/18147 is merged.
It’s needed to add status checks required to pass before merging.
- check-angular
- check-react
- check-vue
- check-generators
- check-npm-test

**Comment by mshima** [comment]
@pascalgrimaud can you add the required status checks?

**Comment by pascalgrimaud** [comment]
@mshima : done

![image](https://user-images.githubusercontent.com/9156882/159263631-04c15897-6bb4-474f-868f-6999a2adbc65.png)

**Comment by mshima** [comment]
@pascalgrimaud thanks.
I hope this is done now.

**Comment by mshima** [comment]
@pascalgrimaud I've forgot the `check-dev-server` status. Can you it too, please?

**Comment by pascalgrimaud** [comment]
@mshima : updated. Don't hesitate to ping me if it needs ;-)

![image](https://user-images.githubusercontent.com/9156882/159279174-3e1f5492-1726-4bd0-99a5-34d4256d171a.png)
