### ISSUE TITLE
Can we update already generated entity

### ISSUE THREAD

**Issue by BhawaniSingh** [jhipster/generator-jhipster#1274]
Is there any option/sub-generator to edit the already generated entities

**Comment by seghers** [comment]
You could edit the <entityname>.json file in the .jhipster folder.
run "yo jhipster:entity <entityname>"

**Comment by jdubois** [comment]
Yes @seghers is correct

If the documentation is not enough http://jhipster.github.io/creating_an_entity.html please tell us what's missing.

**Comment by BhawaniSingh** [comment]
Oops sorry, I missed the documentation

Regards
Bhawani Singh
