### ISSUE TITLE
Log4j2 Support

### ISSUE THREAD

**Issue by BhawaniSingh** [jhipster/generator-jhipster#1275]
Can we have the log4j2 support. Loj4j2 is way faster than logback.
We can have support for both the loggers.

Thanks for making jhipster such a awesome project. It helps a lot in kickstarting the new project.

**Comment by jdubois** [comment]
I'd rather support only one logger, what makes you say Log4J2 is faster or better?

I only selected Logback because Dropwizard does, and I guessed they did a good job to select the logger.

**Comment by thekalinga** [comment]
Julien,

Here is a huge reason.

http://blogs.mulesoft.org/disrupting-asynchronous-loggers/

Its uses lmax disruptor's ring buffers which are much more efficient. Besides, when dropwizard was created log4j2 dint exist to begin with.

Can u please allow the users to chose atleast log4j2

**Comment by thekalinga** [comment]
I am creating a new ticket to track this..
