### ISSUE TITLE
Make Eureka and Ribbon optional when deploying to Kubernetes

### ISSUE THREAD

**Issue by ErikLundJensen** [jhipster/generator-jhipster#12758]
##### **Overview of the feature request**

The Netflix OSS stack (Eureka, Ribbon and Registry) are obsolete and replaced by technologies as Kubernetes and service mesh.
Change JHipster to allow deployment without Eureka client and Eureka Server.

##### **Motivation for or Use Case**

Running Eureka server at Kubernetes is an extra layer of indirection as Kubernetes already supports load balancing of services. Further more service mesh like Istio replaces the need for Eureka Client and Ribbon as those features are handled by the service mesh.

Current implementation of JHipster does not allow disabling Eureka client due to several issue.

First the dependencies in JHipster must be updated to get the latest Spring Cloud Netflix related jar files because of this issue:
https://github.com/spring-cloud/spring-cloud-netflix/issues/3814

Secondly, even though I remove Eureka related jars the JHipster UAA setup still does not find the right service.
It looks like UAA setup does not support overriding hostname using Ribbon's listOfServers property.
uaa.ribbon.listOfServers

I'm not sure it is a simple change to JHipster, however, to keep JHipster relevant I find it important to be able to execute in a Kubernetes environment without running a Eureka server.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Hello @ErikLundJensen : I don't understand well your need. We have the option "no service discovery". Is it not enough ?

![no_service_discovery](https://user-images.githubusercontent.com/9156882/96125898-422d3480-0ef4-11eb-8d7f-1ba915e870d9.png)

**Comment by ErikLundJensen** [comment]
OK, I was migrating an existing JHipster application.
I'll try to regenerate with "no service discovery" and see how it goes.

**Comment by PierreBesson** [comment]
@ErikLundJensen  Please add the proper information in your bug report, as such our **guidelines are not followed**.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md),
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by ErikLundJensen** [comment]
I suggest that we close this feature request as re-generating classes with "no service discovery" can solve the problem.
