### ISSUE TITLE
JhiEventManager multiple subscriptions

### ISSUE THREAD

**Issue by tillias** [jhipster/generator-jhipster#12778]
##### **Overview of the feature request**

Hello folks, not sure how to propose small feature for https://github.com/jhipster/ng-jhipster, cause I don't see "Issues" tab there. 

##### **Motivation for or Use Case**

It happens quite often, that you need to refresh some list of entities based on multiple events. 

Based on my question and answer in https://stackoverflow.com/questions/64371612/jhieventmanager-multiple-subscriptions it is possible to use add() for child subscriptions in JhiEventManager.

This way syntax can be like this:

```
export class SomeComponent implements OnInit, OnDestroy {
  eventSubscriber?: Subscription;
 
  constructor(protected eventManager: JhiEventManager) {
  }

  ngOnInit(): void {
    this.registerChanges();
  }

  registerChanges(): void {
    this.eventSubscriber = this.eventManager.subscribe('firstEvent', 'secondEvent', 'thirdEvent' () => this.loadAll());
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }
```

##### **Related issues or PR**

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
you are at the right place @tillias
