### ISSUE TITLE
How to configure server side to not expire token ?

### ISSUE THREAD

**Issue by lucasmartinez** [jhipster/generator-jhipster#1277]
I have 2 applications. One online and one offline.
What I need is do not prompt credentials for offline application once user is loged in. This application will run in apache cordova in android. So I have to login just once, work offline (I stores all data in html5 dbs on client side ) and synchronize phone data to spring server. Is this possible with your project ? What I see is you use token expiration time ( 1800 by default ) What I need is do not expires the token for offline application. 
Also I don't want to promt credentials every 30 minutes. If the user is in the middle of long form and token expires in the middle, the user will loss data. So I think is interesting using idle time ( like http://hackedbychinese.github.io/ng-idle/ ) instead loging off the cliente every 30 minutes.

**Comment by flythebluesky** [comment]
Also, hopefully there is a way to retain two tokens for a user - one for mobile/api access that never expires, and one for web that expires after a short timeout (e.g. 30 mins).

**Comment by andrezimmermann** [comment]
Isn't possible to just create a custom java.servlet.Filter, where, after the login, you check if the client is mobile or from the mobile application, then the the session to never expire, if not, set to the default time?

**Comment by jdubois** [comment]
- you can use one of the stateless authentications
- if you want the stateful authentication, you can increase the session time, it's the standard Spring Boot configuration
- you can also use our remember me mechanism, which will log the user automatically

You should ask this question on SO : this is not a bug and as I don't know Cordova I'm not the best person to answer.
