### ISSUE TITLE
Change current DTO implementation alternative version

### ISSUE THREAD

**Issue by tillias** [jhipster/generator-jhipster#12779]
##### **Overview of the feature request**

It would be cool having different DTO implementation. Instead if flattening just deliver ID field filled, all other fields ignored. This will greatly simplify regeneration of entities and increase overall JDL usability

##### **Motivation for or Use Case**

Let us say we have classical parent-child component structure in FE(I will use here Angular as example). 

Here are BE entities:

```
Parent {
  id: long;
  child: Child <------ here only ID is filled
}

Child: {
  id: long;
  text: String
}
```

Here are FE entities (TS):

```
IParent {
  id: number;
  child: Child <------ here only ID is filled
}

IChild: {
  id: number;
  text: string
}
```

For those use-cases when IParent needs full IChild you don't need to generate separate data-types hierarchy and introduce any additional logic, except providing custom method in FE Service and custom method in Resource / Service

FE: 

```
ParentService {
  query(req?: any): Observable<EntityArrayResponseType> {
    const options = createRequestOption(req);
    return this.http.get<IParent[]>(this.resourceUrl, { params: options, observe: 'response' });
  }
 queryWithChild() <<<<---- custom method / manual. 
{
  call custom resource URL here
}
```

BE (in case of services custom method in service can be introduced):

```
    @GetMapping("/parents")
    public List<Parent> getAllParent() {
        return parentRepository.findAll(); 
    }

    @GetMapping("/parents-with-child")   <<<<-------- This is custom method, written by those who needs this behavior. Easy to merge after generation
    public List<Parent> getAllParentsWithChild() {
        get parents together join children here
    }
```

This way template will stay the same, no changes needed. That is very close to the idea behind domain model (Parent, Child) and its  independence on the underlying technical details. 

This is similar to https://github.com/jhipster/generator-jhipster/issues/12707 but much more closer to the roots of Domain Driven Design and Ubiquitous Language.

Whenever import-jdl is executed there is no need to change front-end templates, cause domain model is not changed and custom methods inside services / resources are easier to merge with generated stuff

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/12707

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@tillias there is no need for an alternative issue for the same discussion.
Feel free to propose a PR with your approach to close the other issue.

**Comment by tillias** [comment]
I disagree, this is different issue. But cause you have more right, do whatever you like

**Comment by mshima** [comment]
> Unfortunately I'm not JHipster developer

Feel free to apply for it https://www.jhipster.tech/team/.

> I don't have time for PR

Every jhipster developer has this problem too.

> Cause you have more rights here, do whatever you like -> my best intention is to suggest, your is to accept or reject. What I wanted to ask, is to discuss it with others, but not simply closing it because you don't like it.

I am not saying I like or dislike, it's just duplicated, the discussion is open in the other issue.

**Comment by tillias** [comment]
Sure, no offence meant, as I mentioned before, we all have best intentions. I will probably give up with DTOs anyways and go with data layer entities.

**Comment by tillias** [comment]
I think use-cases are different. Perhaps I'll take more time next week to make a blog-post, with more examples and explanation

**Comment by mshima** [comment]
> Sure, no offence meant, as I mentioned before, we all have best intentions. I will probably give up with DTOs anyways and go with data layer entities.

That's what I am using right now.

**Comment by tillias** [comment]
I wish there were partial classes in Java like in C# https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods. 

This way every time you import jdl it won't overwrite custom logic.
