### ISSUE TITLE
Spring-Boot problems with Hibernate-validator

### ISSUE THREAD

**Issue by andrelugomes** [jhipster/generator-jhipster#1279]
Anyone have problems following the documentation (https://jhipster.github.io/installation.html).
After run mvn spring-boot:run, shows some compile errors:

[WARNING] The POM for org.hibernate:hibernate-validator:jar:5.1.3.Final is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/domain/PersistentToken.java:[13,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/domain/PersistentToken.java:[14,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/domain/User.java:[9,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/domain/User.java:[10,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/domain/User.java:[11,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/domain/AbstractAuditingEntity.java:[15,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/domain/Authority.java:[9,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/domain/Authority.java:[10,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/domain/PersistentAuditEvent.java:[6,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/web/rest/dto/UserDTO.java:[5,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/web/rest/dto/UserDTO.java:[7,36] package javax.validation.constraints does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/web/rest/AccountResource.java:[23,24] package javax.validation does not exist
[ERROR] /c:/Users/s2it_agomes/workspace/testes-jhipster/src/main/java/com/mycompany/myapp/domain/PersistentToken.java:[35,6] cannot find symbol

**Comment by jdubois** [comment]
How is it possible that your pom for org.hibernate:hibernate-validator:jar:5.1.3.Final is invalid?
Can you delete your Maven repository and recreate it? Looks like it's corrupted

**Comment by andrelugomes** [comment]
it realy was corrupted. Worked!!! thanks

**Comment by tencho12** [comment]
> How is it possible that your pom for org.hibernate:hibernate-validator:jar:5.1.3.Final is invalid?
> Can you delete your Maven repository and recreate it? Looks like it's corrupted
how to Delete and recreate it?

**Comment by gmarziou** [comment]
@tencho12 See https://maven.apache.org/plugins/maven-dependency-plugin/examples/purging-local-repository.html

**Comment by ibrahimkarayel** [comment]
you need to add that dependency. 

`<dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-validation</artifactId>
</dependency>`

**Comment by CSAMU4** [comment]
> you need to add that dependency.
> 
> > 
> 
> ```
>  <groupId>org.springframework.boot</groupId>
>  <artifactId>spring-boot-starter-validation</artifactId>
> ```

Thanks! This worked!
