### ISSUE TITLE
[JDL] Stop setting languages as ['en', 'fr'].

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12809]
##### **Overview of the feature request**

Export empty languages by default.

##### **Motivation for or Use Case**

I want jdl samples to be localized in my language.
`jhipster jdl bug-tracker.jh`.

Next step is to use os-locale to set the language or fallback to ['en'] when locale is not valid or environment `CI===true`.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/blob/653e893014cf9768d38f7069db113395b98ac501/jdl/jhipster/application-options.js#L147

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
CC @MathieuAA

**Comment by MathieuAA** [comment]
How will the languages be set? If it's handled by the generator then I guess it's okay

**Comment by MathieuAA** [comment]
PR approved, just one conflict to resolve.

**Comment by mshima** [comment]
Thanks @MathieuAA
