### ISSUE TITLE
Images referenced by css are not shown any more in Angular

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#12803]
##### **Overview of the issue**

Images referenced in css are not shown any more. For example JHipster family member in home page and JHipster tie in navbar.

##### **Motivation for or Use Case**

Images referenced in css should be shown.

##### **Reproduce the error**

Generate Angular app with current master and start app and see that images in homepage and navbar are missing.

##### **Related issues**

This is regression from `css-loader` version upgrade (from version 3 to version 5) PR #12755 - before that change images in css are working.

##### **Suggest a Fix**

Look at `css-loader` release notes https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md v4 and v5 breaking changes sections and try to understand what needs to be changed in JHipster.

##### **JHipster Version(s)**

```
jhipster-7@0.0.1-SNAPSHOT c:\projects\teest\jhipster7
`-- generator-jhipster@6.10.4

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster7",
    "jhipsterVersion": "6.10.4",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": ["cypress"],
    "pages": [],
    "creationTimestamp": 1603213069799,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "et",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": ["et", "en", "ru"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

git version 2.29.0.windows.1

node: v12.18.4

npm: 6.11.3

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.27.4, build 40524192

##### **Browsers and Operating System**

Windows

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
We should downgrade if we need this fixed, otherwise we should wait for https://github.com/jhipster/generator-jhipster/pull/10624.
