### ISSUE TITLE
Settings form not back to pristine after making changes and browsing away

### ISSUE THREAD

**Issue by gomesp** [jhipster/generator-jhipster#1281]
I've noticed that the user settings form does not refresh its details if a user make any changes but does not submit/click save.

So, I could change, for example, the name then go to the homepage, and return to the settings page and the "new" name would have been "persisted". However, if the user returns in a different session the "old" name would show up.

Is this a design choice? Should the default behaviour to tell the user that the information is not saved (or refresh to the persisted state)?

**Comment by aklauza** [comment]
I don't think that is a desired design choice. Seem to me like a bug. Every time the view is opened it should be presented with a state consistent with the server. There is an easy fix for this. All you have to do is force refreshing the user data each time you open that view. To do so, in `settings.controller.js` you have to replace:
```javascript
Principal.identity().then(function(account) {
      $scope.settingsAccount = account;
});
```
with
```javascript
Principal.identity(true).then(function(account) {
      $scope.settingsAccount = account;
});
```
The true flag forces refreshing the user data each time that view is loaded.

**Comment by gomesp** [comment]
Thanks @aklauza :+1:. I hope @jdubois incorporates this change.

**Comment by jdubois** [comment]
Oh yes I didn't see this. It's indeed a bug, thanks!
