### ISSUE TITLE
ExtendWith annotation class not imported in AccountResourceIT when using Redis cache

### ISSUE THREAD

**Issue by sinaghazi** [jhipster/generator-jhipster#12817]
##### **Overview of the issue**

On a fresh project creation with Redis cache and Okta identity provider configuration, I faced a problem in initial generation of test class of AccountResourceIT under test web rest folder. 

##### **Reproduce the error**

Generate a fresh new project without any jdl. use Okta for identity and Redis as the cache. Then run ./mvnw in the project root folder. 

##### **Suggest a Fix**

import org.junit.jupiter.api.extension.ExtendWith;

##### **JHipster Version(s)**

```
firmork@0.0.1-SNAPSHOT /Users/sinaghazi/Projects/Firmork/Platform
└── generator-jhipster@6.10.4 

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.firmork.platform",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.4",
    "applicationType": "monolith",
    "baseName": "Firmork",
    "packageName": "com.firmork.platform",
    "packageFolder": "com/firmork/platform",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "redis",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "lux",
    "clientThemeVariant": "dark",
    "creationTimestamp": 1603355310991,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fi"],
    "blueprints": []
  }
}

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**

macOS Catalina 10.15.7

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
I don't reproduce ...

**Comment by pascalgrimaud** [comment]
@qmonmert : did you try with 6.10.4 instead of main ?

**Comment by qmonmert** [comment]
@pascalgrimaud indeed there is a bug on 6.10.4
```
<%_ if (databaseType === 'neo4j' || cacheProvider === 'redis' || (reactive && ['mysql', 'postgresql', 'mssql'].includes(prodDatabaseType))) { _%>
import org.junit.jupiter.api.extension.ExtendWith;
<%_ } _%>
```
ok on main brach

```
<%_ if (databaseType === 'neo4j') { _%>
import org.junit.jupiter.api.extension.ExtendWith;
<%_ } _%>
```
ko on 6.10.4

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/12974
