### ISSUE TITLE
Remove deprecated functionality from Angular code

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#12813]
##### **Overview of the feature request**

I would like to remove deprecated functionality from Angular code. As replacing `TestBed.get` with `TestBed.inject` was bigger task (without using type casting `as unknown` workaround) then I create this ticket to track different PR-s:

- [x] replace `TestBed.get` with `TestBed.inject`

 - [ ] replace other deprecated functionality

 - [ ] apply ESLint rule https://github.com/gund/eslint-plugin-deprecation to avoid further deprecated functionality

##### **Motivation for or Use Case**

As we are hipsters then we should avoid using deprecated functionality.

##### **Related issues or PR**

Starting with PR-s shortly.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/28313

**Comment by pascalgrimaud** [comment]
@kaidohallik : approved
