### ISSUE TITLE
Apache mod_security latest CRS thinks NG_TRANSLATE_LANG_KEY cookie is trying to do a SQL injection?

### ISSUE THREAD

**Issue by peterboni** [jhipster/generator-jhipster#1282]
[Sat Mar 21 20:15:56.551430 2015] [:error] [pid 18232] [client 106.68.121.174] ModSecurity: Access denied with code 403 (phase 2). Pattern match "(^[\\"'`\\xc2\\xb4\\xe2\\x80\\x99\\xe2\\x80\\x98;]+|[\\"'`\\xc2\\xb4\\xe2\\x80\\x99\\xe2\\x80\\x98;]+$)" at REQUEST_COOKIES:NG_TRANSLATE_LANG_KEY. [file "/etc/httpd/crs/owasp-modsecurity-crs/base_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "64"] [id "981318"] [rev "2"] [msg "SQL Injection Attack: Common Injection Testing Detected"] [data "Matched Data: \\x22 found within REQUEST_COOKIES:NG_TRANSLATE_LANG_KEY: \\x22en\\x22"] [severity "CRITICAL"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "8"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"] [hostname "www.removed.com"] [uri "/"] [unique_id "VQ02zOvY4KdL@x2LjPyXsAAAAAQ"]

**Comment by jdubois** [comment]
It's always good to know, so thanks for reporting this.

Then, if there is a bug in Apache mod_security, you should report this to them.
