### ISSUE TITLE
JVM Debugger and RMI

### ISSUE THREAD

**Issue by pvlastaridis** [jhipster/generator-jhipster#1284]
I found following statement on the internet and since we are passing the below jvm variables in spring-boot-maven-plugin I thought we could use the new format. Also I would like to know why we attach a debugger to our jvm is it because of metrics?

**In Java SE 5 or newer, one can use a new standard JVM option to attach a remote debugger. For example,**

    -agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y

**In Sun JDK 1.4 or earlier, one still uses this old options:**

    -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=9009

Also please enligthen me and tell me which module needs the below jvm param (metrics again?)

    -Djava.rmi.server.hostname=localhost

**Comment by jdubois** [comment]
This comes from a PR, and I didn't check it well enough:

- yes we should use the new format
- no I don't think RMI is used for anything

I'll keep this opened until we fix this line, and of course this time I need to check it better

**Comment by jdubois** [comment]
You are correct. I'm copying the default configuration provided by Intellij IDEA.
