### ISSUE TITLE
Moment.js should be removed from react-jhipster as well

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#12858]
Moment.js dependency should be removed from https://github.com/jhipster/react-jhipster/blob/main/package.json#L43 right ? (+ from the components that use it: TextFormat)
Otherwise it is still bundled in the final javascript file ?

(cc @qlereboursBS,@atomfrede, @pascalgrimaud)

**Comment by pascalgrimaud** [comment]
yes I think

**Comment by qmonmert** [comment]
👍
