### ISSUE TITLE
What happened to /tracker page under admin?

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1285]
I tried to dig through changelogs, but couldnt find any, sorry if I missed it along the way. It was a nice feature, I had an old build from which I ported it to the new code generated. But any specific security issue or something for its removal?

**Comment by jdubois** [comment]
No it's still there!
But only available if you selected the websocket option.

BTW I will rework it soon, I have done quite a lot of websocket coding lately, and my skills have improved :-)

**Comment by deepu105** [comment]
Thats Strange, I updated a project with websocket configured originally using latest jHipster and when comparing the code I didn't find the tracker part, I'll check config and generate again, will let you know if there is an issue. Might be a mistake on my part too in that case I wont bother you :)

**Comment by deepu105** [comment]
:+1:  for reworking the websocket part :) may be you can implement a notification system or in app chat as sample :smile_cat: coz I diddnt realize what websocket was doing untill i digged through the tracker code. Anyway just an idea I know its a far reach at this point
