### ISSUE TITLE
Invalid json in eslintrc

### ISSUE THREAD

**Issue by nicolas63** [jhipster/generator-jhipster#12859]
##### **Overview of the issue**

the json in eslintrc.json is not valid 
https://github.com/jhipster/generator-jhipster/blob/main/generators/client/templates/angular/.eslintrc.json.ejs

##### **Suggest a Fix**

I can correct the json if you are ok 

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@nicolas63 go ahead.
