### ISSUE TITLE
Rename package io.github.jhipster -> tech.jhipster

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#12854]
As part of V7 Roadmap, It has been required to rename package io.github.jhispter -> tech.jhipster

To do so, it has been decided to create a new project [jhipster-bom](https://github.com/jhipster/jhipster-bom) to start with a new maven dependency starting on version 1.0.0.

Old project [jhipster](https://github.com/jhipster/jhipster) will be then discontinued

**Comment by pascalgrimaud** [comment]
Adding a bounty as it was a lot of work.
Thanks for your hard work @DanielFran ! plz claim it

**Comment by pascalgrimaud** [comment]
A new release of jhipster-bom has been done:
https://repo.maven.apache.org/maven2/tech/jhipster/

cc @gmarziou : if you can test in your projects and give feedbacks ;)

**Comment by DanielFran** [comment]
@pascalgrimaud Bug bounty claimed.

**Comment by pascalgrimaud** [comment]
@DanielFran : approved
