### ISSUE TITLE
Add a Milestone/Roadmap page to documentation

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1286]
It would be nice to have a roadmap page, or atleast an updated milestone section in github so users can plan for changes and prepare beforehand

**Comment by jdubois** [comment]
Yes, you are right.

Currently our roadmap is basically this ticketing system. I also try to give some information during each release, about what's coming next, but I don't always know what we are going to do.

-> for the moment I'll focus on giving more information during each release, about what we are preparing for the future, and when I have something good enough, I will put it into a separate page.
