### ISSUE TITLE
Stop exporting metrics through logback/logstash and remove DropWizard metrics dependency

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#12878]
As part of v7 roadmap, we should stop exporting metrics through logback/logstash, this is no longer relevant with Prometheus and deprecated JHipster Console.
This way we can also drop DropWizard metrics dependency.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
cc @PierreBesson

**Comment by DanielFran** [comment]
> Could we remove dependency on DropWizard ?
> _Originally posted by @gmarziou in https://github.com/jhipster/generator-jhipster/issues/10958#issuecomment-591366222_
> 

> I think the dependency on dropwizard is only to output the metrics in the logs so yes it can be removed.
> _Originally posted by @PierreBesson in https://github.com/jhipster/generator-jhipster/issues/10958#issuecomment-591384656_
> 

> I would like to deprecate the JHipster Console for JHipster 7. It can be replaced by documentation on how to integrate with ELK and Prometheus.
> _Originally posted by @PierreBesson in https://github.com/jhipster/generator-jhipster/issues/10958#issuecomment-593988884_
> 

> @PierreBesson yes exporting metrics through logback/logstash is no longer relevant with Prometheus Let's drop JHipster Console. This way we can also drop DropWizard metrics dependency.
> 
> I think documentation could be light because most likely users looking for a production ready centralized logging and metrics may opt for dedicated cloud solutions or for solutions integrated in their cloud provider offer.
> 
> For those who may want to manage their own infrastructure (for instance for regulation compliance like PCI-DSS) they  will probably not use jhipster-console;
> _Originally posted by @gmarziou in https://github.com/jhipster/generator-jhipster/issues/10958#issuecomment-596448093_
>

**Comment by PierreBesson** [comment]
I confirm that this can and should be done for v7.
Moreover, the [JHipsterLoggingMetricsExportConfiguration.java](https://github.com/jhipster/jhipster/blob/main/jhipster-framework/src/main/java/io/github/jhipster/config/metric/JHipsterLoggingMetricsExportConfiguration.java) class and associated config prop (`jhipster.metrics.logs.enabled`) need to be remove from the JHipster lib as we no longer need this functionality.

**Comment by DanielFran** [comment]
Thanks @PierreBesson for the confirmation, both PR are ready in generator and jhipster-bom projects
