### ISSUE TITLE
Remove hard coded path in updateLanguagesInWebpackAngular 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/generator-jhipster#12870]
##### **Overview of the issue**

To allow blueprint customization we need to use `${this.CLIENT_MAIN_SRC_DIR}` here 
https://github.com/jhipster/generator-jhipster/blob/main/generators/generator-base-private.js#L343

##### **Related issues**

https://github.com/jhipster/generator-jhipster/pull/12410

##### **Suggest a Fix**

I can provide a PR to fix this if you are ok 

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@nicolas63 Can you provide a PR, please?

**Comment by mshima** [comment]
@nicolas63 if you are willing to create the PR, always go for it 😄 .

To prevent others bugs like this, add 
```
path.join(__dirname, '..', 'generators', 'generator-base-private.js')
path.join(__dirname, '..', 'generators', 'generator-base.js')
```
to
https://github.com/jhipster/generator-jhipster/blob/2302720eb7ed54cf114130559f715904c823af4f/test/enforcements.spec.js#L41-L49

**Comment by nicolas63** [comment]
Thanks for your advice @mshima. I will add this test

**Comment by mshima** [comment]
@nicolas63 please add `...readDir(path.join(__dirname, '..', 'generators', 'entities-client')),` too.
