### ISSUE TITLE
DevOps CI/CD pipeline for JHipster

### ISSUE THREAD

**Issue by wilsonmar** [jhipster/generator-jhipster#12888]
##### **Overview of the feature request**

Automate builds of JHipster so a change in code would build and run tests, creating environments for QA, Test, Prod.

##### **Motivation for or Use Case**

Join the fun and have a fully functional starter like JHipster.

Being in CircleCI would provide metric insights for DevOps not available with JHipster alone.

##### **Related issues or PR**

You have it?

**Comment by atomfrede** [comment]
I am not sure what the exact issue/question/problem you try to address, but we have CI/CD subgenerator which supports already a wide range of ci solutions for your generated application. https://www.jhipster.tech/setting-up-ci/
