### ISSUE TITLE
Add --app option heroku deployment

### ISSUE THREAD

**Issue by zohebsait** [jhipster/generator-jhipster#1288]
When I try yo jhipster:heroku it fails deploy with below error:

    ✖ { [Error: Command failed: /bin/sh -c heroku apps:create test-4 && heroku config:set     NODE_ENV=production
     !    Multiple apps in folder and no app specified.
     !    Specify app with --app APP.
    ]

Can we fix this to pass the application name with --app parameter with all heroku commands, so that it is always applied to the right heroku application.

Thanks,
Zoheb

**Comment by jdubois** [comment]
Is this a new option?
If you can make it work I'd appreciate a PR, as I can't test this myself

**Comment by zohebsait** [comment]
It's an old option, but it affects accounts with multiple apps.

I have tested the fix and submited a pull request, https://github.com/jhipster/generator-jhipster/pull/1311

**Comment by jdubois** [comment]
Closed as PR is merged, thanks!
