### ISSUE TITLE
Update dayjs locale when changing app language

### ISSUE THREAD

**Issue by medamineziraoui** [jhipster/generator-jhipster#12887]
##### **Overview of the feature request**

Currently when changing the language from application, the locale is not updated. it will keep the default locale of days. that need to change.

##### **Motivation for or Use Case**

Locale dayjs need to be updated according to the use language selection.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/12575

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by medamineziraoui** [comment]
@FabienEssid

**Comment by atomfrede** [comment]
A confirm the issue for angular. It works for vue.

**Comment by medamineziraoui** [comment]
Hello @atomfrede yes i would love to, this would be my first contribution if done successfully so definitely would not hesitate to ask if I need help.

**Comment by atomfrede** [comment]
@medamineziraoui Awesome! I think for angular you need to look [here](https://github.com/jhipster/generator-jhipster/blob/2da017ca2b6ca46d7651a29a1cfb5f2e5c82c6ee/generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.ts.ejs#L70) and for react it could be done in the [locale reducer/store](https://github.com/jhipster/generator-jhipster/blob/2da017ca2b6ca46d7651a29a1cfb5f2e5c82c6ee/generators/client/templates/react/src/main/webapp/app/shared/reducers/locale.ts.ejs#L49)

**Comment by medamineziraoui** [comment]
@atomfrede Thank you

**Comment by FabienEssid** [comment]
@medamineziraoui is currently on holidays. We should work on this issue when he'll be back next week :slightly_smiling_face:

**Comment by medamineziraoui** [comment]
Hello im starting working on this issue today, i will keep you updated with my progress :slightly_smiling_face:

**Comment by medamineziraoui** [comment]
- [ ]  Vuejs: we tried the fixed offered by @atomfrede, we confirmed that it change update the dayjs with the current app locale.
- [ ] React:  I located this reducer that update locale in the hipster `TranslatorContext`
```
export type LocaleState = Readonly<typeof initialState>;

export default (state: LocaleState = initialState, action): LocaleState => {
  switch (action.type) {
    case ACTION_TYPES.SET_LOCALE: {
      const currentLocale = action.locale;
      if (state.currentLocale !== currentLocale) {
        dayjs.locale(currentLocale); // <====== updated this dayjs locale before setting state in the TranslatorContext
        TranslatorContext.setLocale(currentLocale);
```
What do think about updating React this way to fixe the dayjs locale?
- [ ] Angular: i tried starting the project but i got an error 
![image](https://user-images.githubusercontent.com/57661415/100020684-80b1eb00-2de0-11eb-8cfb-8c7a2fed44c9.png)
I will look it up tomorrow

**Comment by medamineziraoui** [comment]
- When we tried starting spring section of a generated jhipster project 3 weeks ago, we got this error 
![image](https://user-images.githubusercontent.com/57661415/100021560-f5395980-2de1-11eb-8a6c-3b03efb8761c.png)
On multiple machines. 
Today we tried starting again the same process ( ofc after pulling changes from jhipster main project , we got the changes ), and we still got the exactly the same error.
Did you experience the same issue before ?
We only could work with the generator when we changed 
```
<jhipster-dependencies.version>7.0.0-SNAPSHOT</jhipster-dependencies.version> 
```
jhipster-dependencies.version to 0.1,0
This ofc broke multiple parts in the project but it was enough for us to test what we need for Vuejs and Reactjs.

**Comment by DanielFran** [comment]
@medamineziraoui You need to checkout jhipster-bom project and build it locally.

**Comment by medamineziraoui** [comment]
Thank you for your answer @DanielFran, you are talking about this repo ? https://github.com/jhipster/jhipster-bom
Is there anything else I need to do ( any change in configuration for generated project ?)

**Comment by DanielFran** [comment]
Yes, it is this repo. No changes required on generator side...

**Comment by medamineziraoui** [comment]
Ok thank you, i will test this tomorrow :slightly_smiling_face:

**Comment by kaidohallik** [comment]
> * Angular: i tried starting the project but i got an error

Try to delete `node_modules` folder and `package-lock.json` file and run `npm install` again, this can solve this error.

**Comment by medamineziraoui** [comment]
Thank you @kaidohallik i will try this later this day and i will keep you updated :slightly_smiling_face:

**Comment by medamineziraoui** [comment]
I tried both solution for jhipster-bom and node_modules and works fine ( needed to upgrade node version too for angular ), i got another issue when trying to link the generator-jhipster 
![image](https://user-images.githubusercontent.com/57661415/100153495-7f49f680-2ea4-11eb-8250-bb94b5e28c72.png)
i will check it out and continue tomorrow

**Comment by medamineziraoui** [comment]
Never mind i upgraded the node and it works now 
![image](https://user-images.githubusercontent.com/57661415/100153716-ccc66380-2ea4-11eb-9052-f8dd9366f320.png)

**Comment by DanielFran** [comment]
@medamineziraoui Do you still have issues with your setup?

**Comment by medamineziraoui** [comment]
Hello no i don't have setups issues thx to your advice guys so thank you, i wasn't able to work fixe the issue those pass days but i will this weekend.

**Comment by atomfrede** [comment]
Keep it open

**Comment by atomfrede** [comment]
@medamineziraoui Whats your status on this? If you like I can pick up where you left and finish it.

**Comment by medamineziraoui** [comment]
Hello @atomfrede sorry for being disconnected for this long :sweat_smile: , but if you let me I would like to continue work on this issue this weekend, i did test the fixes on monday and it s worked for 
- Vue.js
- ReactJs
- angularJs

I will send a Fix this weekend.

**Comment by atomfrede** [comment]
Sure, go ahead, looking forward to the PR!

**Comment by medamineziraoui** [comment]
Thank you :smile:

**Comment by medamineziraoui** [comment]
I added Pull Request @atomfrede , i tried to add test for react but couldn't make it work,
```
 it('should current locale state be coherent with dayjs locale', () => {
    const localeState = locale({ currentLocale: 'en' }, { type: ACTION_TYPES.SET_LOCALE, locale: 'es' });
    expect(dayjs.locale()).toEqual(localeState?.currentLocale);
  });
```
Maybe locale method is async
This is the first time I try to write test with jest so could be if i did something wrong.

I ran test with vuejs but i got 2 failed tests, i don t believe they are related to my changes.

**Comment by medamineziraoui** [comment]
Thank you for letting me finish the PR, and i apologize for taking long to finish a simple fixe

**Comment by atomfrede** [comment]
No need to apologize! We are all doing this in our freetime. Thanks for contributing.
