### ISSUE TITLE
some scripts not loaded in index.html

### ISSUE THREAD

**Issue by Qinwroks** [jhipster/generator-jhipster#1289]
![wrong](https://cloud.githubusercontent.com/assets/728884/6799376/46305c42-d250-11e4-9220-14fab44d7db7.png)

i follow the video tutorial. still have problems with the starter project.

**Comment by Qinwroks** [comment]
it was done by this:
yo jhipsteer -> import project in IDEA -> run Application.main()

**Comment by jdubois** [comment]
If you have scripts missing at the beginning of the project, you had an error either during "bower install" or "grunt install".
Please re-run those install manually, and maybe even do a "grunt wiredep" afterwards.
If you still have the error, please re-open the ticket with more information
