### ISSUE TITLE
Improve localization user experience.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12900]
##### **Overview of the feature request**

Guess user native language based on environment locale and set `en` as second language.

##### **Motivation for or Use Case**

IMO this improves user experience.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
It is a nice touch but I think it might surprise some people. If we implement this, at least print an explicit log to tell the user that we detected his or her locale and as such pre-selected their language.

**Comment by pascalgrimaud** [comment]
Following my https://github.com/jhipster/generator-jhipster/pull/12810#issuecomment-723549597, I think the command `jhipster jdl bug-tracker.jh` should be exactly the same, no matter the machine, the CI or the localization.
It's better for reproduce the config.

So what I can propose:
- `jhipster jdl bug-tracker.jh` : generate with `en` by default, so the user can add more language if he/she wants
- if the JDL file contains the language properties, use it instead
- add a new flag: `jhipster jdl bug-tracker.jh --native-language` : try to calculate the locale and use it. It should work with Windows, MacOS and Linux

What do you think ?

**Comment by mshima** [comment]
@pascalgrimaud it's a solution.
Current with PR just execute `jhipster -n`.
