### ISSUE TITLE
Split test framework prompt.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12902]
##### **Overview of the feature request**

Our test framework prompts is currently implemented in app generator.
We should split into a 2 prompts:
- a prompt in client generator for client test frameworks
- a prompt in server generator for server test frameworks

##### **Motivation for or Use Case**

- Allows client/server only blueprints to don't override app generator to customize test framework prompt.
- Remove unrelated prompt from app generator.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Are you still interested in this feature @mshima?

**Comment by mshima** [comment]
@mraible I may implement that for v8 while modularizing.
