### ISSUE TITLE
Polyfilling node core modules when upgrade to Jhipster 6.10

### ISSUE THREAD

**Issue by sabeurios** [jhipster/generator-jhipster#12908]
I have an existing project generated with jhipster 5.7 so I upgraded it to 6.10 and I transferred the existing files to the new directory and suddenly I had this polyfilling problem.

<img width="743" alt="Screenshot 2020-10-29 at 09 19 28" src="https://user-images.githubusercontent.com/57177536/97698217-7aae4000-1aa8-11eb-9b57-0e6653a24c3d.png">

I opened a subject in the webpack form but they directed me here.

**Comment by mshima** [comment]
We are still using webpack 4.
You should correct your dependencies.

**Comment by sabeurios** [comment]
@mshima  I'm using webpack 5.2.0 generated automatically with jhipster 6.10
![Uploading Screenshot 2020-10-30 at 12.24.02.png…]()

**Comment by DanielFran** [comment]
Looking at v6 branch, webpack defined is version 4: https://github.com/jhipster/generator-jhipster/blob/v6.x_maintenance/generators/client/templates/react/package.json.ejs#L175

![image](https://user-images.githubusercontent.com/3706415/97700121-340a1700-1aa3-11eb-9993-59ce69f37ad6.png)

**Comment by mshima** [comment]
@sabeurios you can see the open issue at https://github.com/jhipster/generator-jhipster/issues/12712.
