### ISSUE TITLE
Customization of the webpack path 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/generator-jhipster#12925]
##### **Overview of the issue**

For the dotnet blueprint i need to customize this line how can i do it ? 
https://github.com/jhipster/generator-jhipster/blob/main/generators/generator-base-private.js#L343

Maybe @mshima can help me ? 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@nicolas63 changing to
```
const fullPath = this.destionationPath('webpack/webpack.custom.js');
```
should do the trick.

**Comment by nicolas63** [comment]
thanks ! 
I'm going to do PR

**Comment by nicolas63** [comment]
@mshima the destinationPath method create an absolute path and just after the method replace content do the same and cause some troubles. Have you any idea to create absolute path only once ?

**Comment by mshima** [comment]
@nicolas63 you are right, there is a unsafe conversion at:
https://github.com/jhipster/generator-jhipster/blob/1643527b2cc3b64d47d76111f692692e12a01952/generators/utils.js#L89-L90

Replace that with:
```
const fullPath = generator.destinationPath(args.file);
```

You can revert the other changes.

Thanks.

**Comment by nicolas63** [comment]
Thanks to you for your help.
I will make the change
