### ISSUE TITLE
RBAC/ACL information shouldn't be exposed in the client

### ISSUE THREAD

**Issue by jhulick** [jhipster/generator-jhipster#1293]
Great project! Our team is considering JHipster for some of our projects. One application feature that is concerning is how the client security is implemented. Currently user role data is exposed in the client. Removal of user role information from the client  (Principle, Router and View) would be ideal, and instead put all security checks to the server-side. One angular module/project that I've noticed addresses the client portion, and is called angular-rbac: https://github.com/plandem/angular-rbac. This module has a service and directive for making back-end security checks, plus some caching to reduce chatty http calls. In the case of JHipster, the service could protect the router changes and data services, and the directive view data access.

**Comment by jdubois** [comment]
- You seem to imply that our security roles are not checked on the server side: this is not true, we do check everything on the server side, using Spring Security
- We do expose the roles on the client side (and we have a new directive coming in the next version, that you probably will like better), but this is just to show the right screen to users

**Comment by jhulick** [comment]
Sorry, I should have been more explicit. User details and security roles are retrieved from the server side (UserDetailsService.loadUserByUsername), and a user's details (along with their granted authorities) are exposed to the client. The client then determines whether a user is in a role or not (Principal.isInRole function, within the jhipsterApp module). I am saying that instead, the server should determine if the user is in a role and return a boolean response to the client, rather than leaking personal details to the insecure browser environment.

**Comment by gzsombor** [comment]
You mentioned that angular-rbac module, but that would require a webservice to retrieve a list of allowed 'roles', so that wouldn't be any more secure than the current solution. The only difference, is that angular-rbac would emit multiple requests - instead of asking once, and using that informations. So it is still decided on the client side, which parts are visible.

**Comment by jhulick** [comment]
@gzsombor, have you actually looked at the angular-rbac code? The $rbac service returns true/false results, given a role set against a resource. User RBAC/ACL information is not leaked to the client by the angular-rbac $rbac service.

**Comment by gzsombor** [comment]
Yes, I've looked into. And what do you think, where this $rbac service will run ? On the client side. It's functionally equivalent with the current implementation, as the server still have to sends which 'roles' are granted, and which are not. Basicly, you still have to provide a rest service, which based on a list of role names sends back true/false values. Yes, it's a bit different than sending all the granted roles, but if you know the role names - and you can easily get most of them from the source of the client code, then it wouldn't change anything
 To protection of the real sensitive data should happen on the server side, not by some client side service or directive.

**Comment by jdubois** [comment]
- I just had a quick look at angular-rbac -> it has only 12 stars, and we do not use projects which are not well-established. This is just too much risk for us and our users.
- I don't see why exposing the roles is such a big issue. The user knows if he is a "user" or an "admin", I don't think hiding this makes anything more secure. And anyway, if you have just a boolean telling you the same information, it wouldn't be hard to guess your roles - angular-rbac isn't really more secure.

**Comment by jhulick** [comment]
The core issue I'm bringing up isn't the control decision, but exposing of detailed system security information. It would be ideal to configure resource/role/permission mapping on the server-side. This way, no internal system security information would be exposed to the client. Then remove the 'data.roles' object from the $stateProvider, and inject a server-side check via service on route change, dataservice call, or directive, etc.

**Comment by jdubois** [comment]
OK, but I still don't understand why this would be "detailed security information", or why this would be a security issue.
I've had a look at https://github.com/angular-app/angular-app which is quite an established project, and they do send if the user is an admin or not, which is basically the same thing as what we do.
You need to know that, anyway, otherwise you just can't generate a correct UI.

**Comment by andrezimmermann** [comment]
My two cents here is that you still expose the details of your system security if you ask the permission for the server. Either way you can inspect the code to know the roles and permission and change using the browser developer tools to change my permission on the client side. The real security is within the server. Hiding the information is just security by obfuscation.

**Comment by jhulick** [comment]
@andrezimmermann, just posted an edit of my comment above. If resource roles/permission and user roles/permissions are kept to the server-side, that would address this issue. We are saying the same thing.

**Comment by deepu105** [comment]
I'm going through a dilemma on the role mapping part in Jhipster, the current application I use Jhipster have dynamic role mapping, i.e, end users can define new roles in a GUI and grant granular CRUD access to various other modules, since the Roles generated are dynamic, Jhipster way of checking ROLE_ADMIN or ROLE_USER at the client side will not work, I'm exploring other ways to best implement this so that dynamic roles can be handled. I have done similar implementations in JSP  but quite new to angular hence its been a little tough to decide on best approach. Any ideas ? anyone?

My current thought is to have the role validations at server side and have a AOP interceptor to intercept data transferred by rest calls and decide to update/delete or sent GET request back based on role of the user. But worried that this will have overhead on all calls

**Comment by jhulick** [comment]
@deepu105 I've the same dilemma for an upcoming jhipster application. Resource owners may dynamically grant access permission to others at runtime and so security checks will need to be in the API layer rather than in the client. I'll be working on these things: 1) on initial application load, check the user role and shard the client based accordingly on their role. In other words, only load the application view/features their role would allow them to have. The admin section on the client will not go to one with a 'user' role. This may require changes to how the client modules are constructed. 2) an API for dynamic resource permission updates, and 3) back-end access checks in the middleware for every resource action. It's still something rather new for me too, and my current thinking is to go token based with OAuth2 flows for now. Stateful session would of course work too. I'd be interested to hear your feedback, and from others too about this approach.

**Comment by deepu105** [comment]
@jhulick : I guess for your architecture the approach seems to be fine, My current thoughts are also very much similar, only difference being ill be using stateful session.
I'm planning to have the user data in session with the role id, and on my AOP layer will check the role mapping to modules for the role ID and will remove/nullify any unauthorized content (I guess a better way would be to check before making the DB call and stop any unauthorized data query)
In my client side code ill have a directive on every widget/data section which will remove the section if the data object is empty and show/hide edit/view/delete actions based on the object properties

**Comment by lubo08** [comment]
I think that problem is that also admin parts of html are exposed to the client even client is log in as user not admin still there is admin code. This can happened in secure application. Just use thymeleaf with spring security to do not expose this part of code to the client. 

`<li ng-class="{active: $state.includes('admin')}" ng-switch-when="true" has-authority="ROLE_ADMIN" class="dropdown pointer ng-scope hidden">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="" id="admin-menu">
                        <span>
                            <span class="glyphicon glyphicon-tower"></span>
                            <span class="hidden-sm ng-scope" translate="global.menu.admin.main">Administration</span>
                            <b class="caret"></b>
                        </span>
                    </a>
                    <ul class="dropdown-menu">
                        <li ui-sref-active="active"><a ui-sref="user-management" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/user-management"><span class="glyphicon glyphicon-user"></span>
                            &nbsp;<span translate="global.menu.admin.user-management" class="ng-scope">User management</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="tracker" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/tracker"><span class="glyphicon glyphicon-eye-open"></span>
                                &nbsp;<span translate="global.menu.admin.tracker" class="ng-scope">User tracker</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="metrics" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/metrics"><span class="glyphicon glyphicon-dashboard"></span>
                            &nbsp;<span translate="global.menu.admin.metrics" class="ng-scope">Metrics</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="health" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/health"><span class="glyphicon glyphicon-heart"></span>
                            &nbsp;<span translate="global.menu.admin.health" class="ng-scope">Health</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="configuration" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/configuration"><span class="glyphicon glyphicon-list-alt"></span>
                            &nbsp;<span translate="global.menu.admin.configuration" class="ng-scope">Configuration</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="audits" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/audits"><span class="glyphicon glyphicon-bell"></span>
                            &nbsp;<span translate="global.menu.admin.audits" class="ng-scope">Audits</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="logs" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/logs"><span class="glyphicon glyphicon-tasks"></span>
                            &nbsp;<span translate="global.menu.admin.logs" class="ng-scope">Logs</span></a></li>
                        <li ng-hide="inProduction" ui-sref-active="active" aria-hidden="false"><a ui-sref="docs" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/docs"><span class="glyphicon glyphicon-book"></span>
                            &nbsp;<span translate="global.menu.admin.apidocs" class="ng-scope">API</span></a></li>
                        
                        <li ng-hide="inProduction" aria-hidden="false"><a href="/h2-console" target="_tab" data-toggle="collapse" data-target=".navbar-collapse.in"><span class="glyphicon glyphicon-hdd"></span>
                            &nbsp;<span translate="global.menu.admin.database" class="ng-scope">Database</span></a></li>
                    </ul>
                </li>`

**Comment by jhulick** [comment]
@lubo08 After about a year mulling over these SPA security ideas, I've done exactly what you are recommending on a Spring Boot project by using of Thymeleaf to shard a SPA into domains for security (ex. user, admin, etc). While this might seem simple, it creates lots of duplication and one-offs in the client code - a bad smell for coding/maintenance. I've yet to find a really good approach, dynamically loading modules is also PITA and error prone, but when security demands zero leaks to the client at this point in time I would fall back to what you recommend with a Thymeleaf approach. But, all things considered, what other JHipster core devs have said in this ticket is correct: make sure that the server-side security is rock solid, and don't worry so much about the client because secured data and functionality shouldn't leak if server-side is secure (even though markup might).
