### ISSUE TITLE
no exported Method react-jhipster

### ISSUE THREAD

**Issue by sabeurios** [jhipster/generator-jhipster#12942]
I encountered this issue while trying to migrate my solution to a newer version of jhipster.
**Code:**
```
import {
  Translate,
  translate,
  ICrudSearchAction,
  ICrudGetAllAction,
  getSortState,
  IPaginationBaseState,
  getPaginationItemsNumber,
  JhiPagination
} from 'react-jhipster';
```
**Error:**
`......./node_modules/react-jhipster/lib"' has no exported member 'getPaginationItemsNumber'.`
it seems that the method 'getPaginationItemsNumber' is no longer predefined.

**Comment by qmonmert** [comment]
@sabeurios `getPaginationItemsNumber` is not used since a long time in JHipster

**Comment by venkatnaveen7** [comment]
Team
Im upgrading my version of react-jhipster from 0.7.0 to 0.21.0    but getPaginationItemsNumber is missing in the 0.21.0 version
Is this replaced by any other function, May I know where can I find some help
