### ISSUE TITLE
Customize database validation in JDL 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/generator-jhipster#12959]
##### **Overview of the issue**

Since database type is checked in import-jdl the dotnet blueprint can't import jdl for sqllite database (in-memory) 
-> https://github.com/jhipster/generator-jhipster/blob/main/jdl/jhipster/field-types.js#L144

##### **Suggest a Fix**

Maybe we can give the possibility to customize the supported database types and blueprints can enrich them

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
@mshima do you have an idea how to implement this?

**Comment by mshima** [comment]
JDL does not have any support to allow blueprints to extend it.
You should ping @MathieuAA for this one 😄 .

**Comment by MathieuAA** [comment]
The easiest is to disable validations. It's a good idea because there'd be no need to maintain a list of custom options
