### ISSUE TITLE
Auto Rebase Action

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#12950]
##### **Overview of the feature request**

I recently came across this GitHub Action; https://github.com/cirrus-actions/rebase which auto rebases PRs. I was wondering if this might be useful for us so that the merger doesn't have to wait for original submitter of the PR to rebase it. Shall we integrate this? 

cc: @jhipster/developers 

##### **Motivation for or Use Case**

So that rebases could be done seamlessly without having to wait for the original poster. 

##### **Related issues or PR**

N/A

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Not sure about that, because some people will prefer using git merge upstream/main, other will prefer git rebase upstream/main
Then, in case of rebase, it will force people to use git push -f
So I'd prefer letting the full control to the contributor

But it's just my opinion :)

**Comment by mshima** [comment]
When we push or close/reopen a PR, all tests are done with a merge between `main` and the PR branch.
And we almost always use merge instead of rebasing, I think this is more useful when the repository chooses linear history.

**Comment by SudharakaP** [comment]
@pascalgrimaud @mshima: Good points. I think I love rebases more than merges which is the reason I suggested this. Anyways I understand the different workflows people  use so we'll not do this for now. 😄
