### ISSUE TITLE
Use MapStruct instead of UserMapper and PasswordChangeDT. MapStruct 1.4.0.Final is out

### ISSUE THREAD

**Issue by tillias** [jhipster/generator-jhipster#12967]
##### **Overview of the feature request**

No more need for hand-made UserMapper and also bump version

##### **Motivation for or Use Case**

```
/**
 * Mapper for the entity {@link User} and its DTO called {@link UserDTO}.
 *
 * Normal mappers are generated using MapStruct, this one is hand-coded as MapStruct
 * support is still in beta, and requires a manual step with an IDE.
 */
@Service
public class UserMapper {
```

##### **Related issues or PR**

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@tillias : I think it's because mapstruct is optional, when using entities. Unless we change this and put mapstruct by default with DTO

**Comment by mshima** [comment]
@pascalgrimaud now that dto is not flatten anymore, I would agree to drop non dto option.
Dropping non-dto and non-service would reduce a lot our test cases.
IMO we could reopen https://github.com/jhipster/generator-jhipster/issues/11589.
Force entities to dto as `mapstruct` and service as `serviceClass` or `serviceImpl`.
And drop implementations during jhipster 7 cycle.

**Comment by pascalgrimaud** [comment]
100% agree.
For my real projects, I always use dto+service by default, as it can't work without mapstruct

**Comment by tillias** [comment]
Hi folks, with new IntelliJ 2020.3 this is a critical issue (of course if Java 11 is used) see https://youtrack.jetbrains.com/issue/IDEA-200481

I can confirm that tests can't be run out of intelliJ 2020.3 anymore.

Any chance you can at least bump version to 1.4.1 in upcoming release?

For all other using JHipster 6x workaround is

```
<mapstruct.version>1.4.1.Final</mapstruct.version>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>${mapstruct.version}</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by pascalgrimaud** [comment]
thanks a lot for your suggestion @tillias 
I'm keeping it in mind, in case of a new patch release for v6

**Comment by 8debug** [comment]
#pascal

> thanks a lot for your suggestion @tillias
> I'm keeping it in mind, in case of a new patch release for v6



> thanks a lot for your suggestion @tillias
> I'm keeping it in mind, in case of a new patch release for v6

I try, but it is not work
