### ISSUE TITLE
Logback.loglevel for Gradle missing

### ISSUE THREAD

**Issue by danaki** [jhipster/generator-jhipster#1301]
I've found this commit https://github.com/LeovR/generator-jhipster/commit/8b24fae7f6475e207f432d96303fe39c8ccd185f but nothing similar for Gradle. Tried to setup it with
```
        System.setProperty('logback.loglevel', 'OFF')
```
without success.

Btw, LOGBack supports conditionals <if><then> with Janino library so it's possible to depend only on spring.profiles.active no external "logback.loglevel" needed.

P.S. can't get any logs for jhipster app on tomcat in production, just nothing except deploy messages/exceptions, where can be the problem?

**Comment by jdubois** [comment]
Concerning your production issue, shouldn't this be another ticket?
Anyway you should have logs, you need to check your configuration, maybe your app server is hiding them?

**Comment by atomfrede** [comment]
Will have a look over the weekend. At least when using ``bootRun`` and the executable ``.war`` file I have logs as excpected.

**Comment by danaki** [comment]
Won't polute this issue with tomcat things, I'm newbie so there'd be probably problem with my tomcat8 configuration.
