### ISSUE TITLE
Login redirect doesn't work in OAuth2 and React

### ISSUE THREAD

**Issue by ja1979** [jhipster/generator-jhipster#13010]
##### **Overview of the issue**

Opening a non-public URL (which requires a authenticated user) doesn't work as expected and the following error is thrown:

```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    in Lifecycle (created by Context.Consumer)
    in Redirect (created by Context.Consumer)
    in Route (created by PrivateRouteComponent)
    in PrivateRouteComponent (created by Connect(PrivateRouteComponent))
    in Connect(PrivateRouteComponent) (created by Routes)
    in Switch (created by Routes)
    in div (created by Routes)
    in Routes (created by App)
    in ErrorBoundary (created by App)
    in div (created by Card)
    in Card (created by App)
    in div (created by App)
    in div (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp (created by ConnectFunction)
    in ConnectFunction
    in div
    in Provider
    in ErrorBoundary
```

This problem is not present when choosing Angular with OAuth, or using React with JWT. The combination of React with OAuth has this issue.

##### **Motivation for or Use Case**

Users want to be redirected to the requested page after they logged in Keycloak. In our case, we send emails to users to review some information what requires authentication and then redirect to that specific page.

##### **Reproduce the error**

1. Create a new **Monolithic** application and choose **OAuth 2.0** and **React**
2. Start container for Keycloak
3. Run the application
4. Without signing in, open a non-public URL like [http://localhost:9000/admin/audits](http://localhost:9000/admin/audits)
5. Error message appears. Keycloak page to login is expected.

##### **Related issues**

n/a

##### **Suggest a Fix**

n/a

##### **JHipster Version(s)**

6.10.5

##### **JHipster configuration**

`jhipster info`

```
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

tms@0.0.1-SNAPSHOT /mnt/myfiles/Projects/tmp/redirect-oidc-test
└── generator-jhipster@6.10.5 



##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.andespetro.tms"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "tms",
    "packageName": "com.andespetro.tms",
    "packageFolder": "com/andespetro/tms",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1604848055606,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment 18.9 (build 11.0.9+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9+11, mixed mode, sharing)

git version 2.26.2

node: v12.19.0

npm: 6.14.8

yeoman: 3.1.1

yarn: 1.21.1

INFO! Congratulations, JHipster execution is complete!
```

`.yo-rc.json`

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.andespetro.tms"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "tms",
    "packageName": "com.andespetro.tms",
    "packageFolder": "com/andespetro/tms",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1604848055606,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Error is not related to entity creation.

##### **Browsers and Operating System**

OS: Fedora 32
Browsers: Firefox 82.0.2 and Chrome 86.0.4240.183

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
I confirm the bug

**Comment by pascalgrimaud** [comment]
@qmonmert : do you confirm the bug with 6.10.5 or with main branch ?

**Comment by qmonmert** [comment]
@pascalgrimaud main branch

**Comment by pascalgrimaud** [comment]
thanks, but I don't understand why the CI works so
adding a bounty on this for the investigation + the fix

**Comment by mraible** [comment]
I just tried it with the latest main branch and it works. There is an error in the console though.

<img width="1524" alt="Screen Shot 2020-11-10 at 12 00 54 PM" src="https://user-images.githubusercontent.com/17892/98719037-70affb00-234c-11eb-8be8-5e24ecda8ca6.png">

**Comment by sendilkumarn** [comment]
@mraible I noticed this error, and it is because the entities menu is empty. If you create an entity this will go away 😃

**Comment by qmonmert** [comment]
@mraible you are redirected on the keycloak page ? not me

I tried the last main branch with Angular and I am not redirected on the keycloak page when I access to http://localhost:9000/admin/audits (and not logged)

**Comment by mraible** [comment]
@qmonmert I'm redirected when I click on "sign in". Which, BTW, seems like it's missing a space before it.

<img width="516" alt="Screen Shot 2020-11-10 at 12 25 20 PM" src="https://user-images.githubusercontent.com/17892/98723827-203a9c80-2350-11eb-9fd5-8742a97e478f.png">

If I try navigating directly to a protected URL (e.g., `http://localhost:8080/admin/health`), I get redirected to `/login` (instead of `http://localhost:8080/oauth2/authorization/oidc`) and an error is rendered.

<img width="1394" alt="Screen Shot 2020-11-10 at 12 26 31 PM" src="https://user-images.githubusercontent.com/17892/98724027-5ed05700-2350-11eb-9555-7f613fffaffd.png">

If I change `private-route.tsx` to use `/oauth2/authorization/oidc` instead of `/login`, I get the same error.

```diff
diff --git a/react-oauth2/src/main/webapp/app/shared/auth/private-route.tsx b/react-oauth2/src/main/webapp/app/shared/auth/private-route.tsx
index 85c2096..a111f8e 100644
--- a/react-oauth2/src/main/webapp/app/shared/auth/private-route.tsx
+++ b/react-oauth2/src/main/webapp/app/shared/auth/private-route.tsx
@@ -39,7 +39,7 @@ export const PrivateRouteComponent = ({
       ) : (
         <Redirect
           to={{
-            pathname: '/login',
+            pathname: '/oauth2/authorization/oidc',
             search: props.location.search,
             state: { from: props.location },
           }}
```

**Comment by qmonmert** [comment]
@mraible ok like me :)

**Comment by yacine17** [comment]
@mraible after to be redirected to `http://localhost:8080/oauth2/authorization/oidc` the page should be reloaded to be directed to Keycloak which react doesn't do with `<RedirectTo />`. I think a component with route `/login` or `/oauth2/authorization/oidc` should be added to perform the reload with `window.location.reload()` (I tested it and it works for me).

Concerning the error, it caused by the PrivateRoute component from the ` <PrivateRoute path="/" component={Entities} hasAnyAuthorities={[AUTHORITIES.USER]} />` in `routes.tsx` since it will be called again and again after the first redirection to `/login` since there is no `exact` attribut which will cause Maximum update depth exceeded error.

**Comment by mraible** [comment]
@qmonmert I tried your branch and it does work. However, it doesn't redirect me back to my original URL (e.g., `http://localhost:8080/admin/health`). Not sure if it's possible to fix that.

**Comment by qmonmert** [comment]
@mraible yes I will try to see if we can do that :)

**Comment by qmonmert** [comment]
@mraible PR done (without redirect back to the original URL, I don't know if it possible)

**Comment by qmonmert** [comment]
@mraible redirection is ok now 🙂

**Comment by qmonmert** [comment]
@jdubois & @pascalgrimaud I claim my money 🙂 https://opencollective.com/generator-jhipster/expenses/28034

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
