### ISSUE TITLE
Maven runs w/ wrong profile on Heroku

### ISSUE THREAD

**Issue by atwoodjw** [jhipster/generator-jhipster#1302]
When Heroku's Java buildpack runs, it doesn't set the prod Maven profile. 

It runs...
`mvn -B -DskipTests=true clean install`
... instead of ...
`mvn -Pprod package`.

So Heroku is building the application for development, but running it with the production Spring profile. This is confusing, since the documentation stresses parity between Maven and Spring profiles.

However, I'm not sure this can easily be fixed without creating a custom buildback.

**Comment by jdubois** [comment]
It shouldn't run with the dev profile, as we add "--spring.profiles.active=prod" in the procfile -> it's the procfile that runs the app, not Maven.

Are you sure you are using the "yo jhipster:heroku" subgenerator?

**Comment by atwoodjw** [comment]
Hi @jdubois ,

I think you misread. I agree the app does run with the prod Spring profile (`--spring.profiles.active=prod`). But the Maven clean install task runs without a specified profile (`mvn -Pprod package`), and since the dev profile is activeByDefault, that's the profile used when app builds on Heroku.

**Comment by jdubois** [comment]
Oh yes, I think we run in dev mode because there was an issue on Heroku which was prevented us to run in prod mode, and that was the main reason this sub-generator is in "beta".

I'm going to check if prod mode works.

**Comment by atwoodjw** [comment]
It looks like you can have a [custom Maven settings.xml file](https://devcenter.heroku.com/articles/using-a-custom-maven-settings-xml) now.

So maybe the sub-generator could generate something like this?

```
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <activeProfiles>
        <activeProfile>prod</activeProfile>
    </activeProfiles>
</settings>
```

**Comment by jdubois** [comment]
The whole Heroku sub-generator is being re-worked by someone from Heroku, so this is outdated now.

See #1482
