### ISSUE TITLE
Avoid N+1 Selects on '*-to-many' relationships

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#13038]
In `src/main/resources/config/application.yml`,
there is `hibernate.query.fail_on_pagination_over_collection_fetch: true`.
But this option is not in `src/test/resources/config/application.yml`.

Which means we could write a request that will work in a test but will fail in production.
A request of this kind is actually generated (ex: Foo many-to-many Bar):
![image](https://user-images.githubusercontent.com/766263/99065324-82410f00-25a7-11eb-87f8-f3686554e8ae.png)
(Pageable + fetch)

In this case, `@BatchSize` on bars field in Foo (like in User/Authority relation) should be used ? (+ remove the left join)

**Comment by mshima** [comment]
I think that just removing left join for collections should be enough.
A should be fixed by https://github.com/jhipster/generator-jhipster/pull/13021/ and commit https://github.com/jhipster/generator-jhipster/pull/12971/commits/017be84ced6d406190f6c777392591e4a06f3065 from another PR.

**Comment by ctamisier** [comment]
After the DTO improvement merge, we now have N+1 selects (with a Foo many-to-many Bar)
![image](https://user-images.githubusercontent.com/766263/99562230-1f48e100-29c8-11eb-9d20-711149ee3c38.png)

I don't know why but additional requests didn't show the 1st time I ran my app. But I can see them now... (screenshot)
It seems that `show-sql: true` is not the best way to debug SQL requests.. I will investigate.

So for the N+1 selects problem, what about @BatchSize(size = 20) ? (like User <-> Authority)

**Comment by mshima** [comment]
> I don't know why but additional requests didn't show the 1st time I ran my app. But I can see them now... (screenshot)
> It seems that `show-sql: true` is not the best way to debug SQL requests.. I will investigate.

Probably due to caching.

We probably should implement a mix of https://vladmihalcea.com/fix-hibernate-hhh000104-entity-fetch-pagination-warning-message/ and https://vladmihalcea.com/hibernate-multiplebagfetchexception/

Something like
Fetch the entity:
```
List< Post > post = entityManager.createQuery("""
    select distinct p
    from Post p
    order by p.createdOn
    """, Post.class)
.setParameter(...)
.setMaxResults(5)
.setHint(QueryHints.PASS_DISTINCT_THROUGH, false)
.getResultList();
```

And then fetch every bag separated:
```
posts = entityManager.createQuery("""
    select distinct p
    from Post p
    left join fetch p.tags t
    where p in :posts""", Post.class)
.setParameter("posts", posts)
.setHint(QueryHints.PASS_DISTINCT_THROUGH, false)
.getResultList();
```

**Comment by ctamisier** [comment]
If I am not wrong, these 2 requests are exactly what `@BatchSize` performs.

From your proposition the plus I see is that you can dynamically set the `.setMaxResults(...)` with the current page size (instead of having it harcoded in the `@BatchSize(size = 20)` for example).

But... If we have several many-to-many relations from one Entity (ex: Foo many-to-many Bar and Foo many-to-many Baz, or more...), it will be quite verbose in the generated code I guess..
It might be a bad habit I have to use `@BatchSize` when I encounter this use case, but it is the best tradeoff I found.
The drawback is that the size of the "Bag" is hardcoded, but I'd say that if we change the page size from the client call, we can just set the size to the "maximum allowed" in `@BatchSize(size = MAX)`

**Comment by mshima** [comment]
One problem is that `entity.getMany()` must be called in the `@Transactional` context, and I read somewhere that even calling it does not guarantee the entities are loaded.
- The safe scenarios I know are `dto` with `serviceClass` or `serviceImpl`.
- I think `non-dto` or `service=no` are not safe.

Maybe @vladmihalcea could help us deciding if `@BatchSize` is a good solution for this issue.

**Comment by vladmihalcea** [comment]
@mshima @ctamisier I don't advise people to use `@BatchSize` as, in my opinion, it's a hack. That's because it can reduce the number of additional queries, but it does not necessarily do it in a single query.

The solution I provided in the article you mentioned is based on the fact that in the context of a running `EntityManager`, Hibernate can replace the collection proxies when we fetch the explicitly using secondary queries.

You can do the same with entity graphs if you want a more dynamic approach to fetching collections.

**Comment by vladmihalcea** [comment]
> But we are guaranteed that the maximum number of requests will be pageSize % batchSize, right ?

That's per association, so if you have 5 such associations and an average of 3 batch queries per association, you'll still run 15 queries instead of 5.

> As we use pagination, I'm not sure we can limit (and offset) the size of the result set by using entity graphs only (and I start thinking that we actually can't use entity graph if we have pagination...). We will still somehow need to programmatically build the SQL request with setMaxResults(). I will keep investigating.

I think that easy to do. You just apply the LIMIT and OFFSET on the parent + ToOne associations, and at most one collection, and afterward you just use JOIN FETCH for the remaining collections.

**Comment by mshima** [comment]
@vladmihalcea thanks, that's been helpful.
I agree `@BatchSize` feels like a hack.
@ctamisier we should keep the PR open, if no one steps in to implement the alternative, we should merge as workaround for jhipster 7 final.

**Comment by ctamisier** [comment]
@mshima Ok let's do this what you said.

Indeed, there are some unpredictive behaviors in the `@BatchSize` (but not the behavior explained above).

If I have the following relationship:
**Foo** many-to-many `@BatchSize(size = 11)` **Bar** 

If I get all my Foos (which is 11 Foos exactly in my DB for example), it performs only 1 SQL request to get all its Bars:
![image](https://user-images.githubusercontent.com/766263/100848625-ab0b4480-3481-11eb-8ad4-078e67d67340.png) (11 '?', so this is very fine for me)

But.... If I have this:
**Foo** many-to-many `@BatchSize(size = 12)` **Bar** (a bigger batch size)
![image](https://user-images.githubusercontent.com/766263/100848809-eefe4980-3481-11eb-9744-4a8379887b30.png)
It splits the batch and performs 2 SQL requests (10 '?' + 1 '?').
Which seems a bug for me (even if I put `@BatchSize(size = 1000)`, I have this same behavior)

I stop here and I'll continue on SO eventually.
Thanks @mshima & @vladmihalcea for your help.

**Comment by gmarziou** [comment]
Maybe we should integrate [QuickPerf](https://github.com/ttddyy/datasource-assert) or [datasource-assert](https://github.com/ttddyy/datasource-assert) in the generated tests.
