### ISSUE TITLE
Separate default and composing in entity.js 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/generator-jhipster#13036]
##### **Overview of the issue**

During default phase some treatment like `prepareRelationshipsForTemplates` is done just before composing 

to allow the blueprints to take advantage of this phase maybe we can split composing and default ? 
Or maybe move `prepareRelationshipsForTemplates` to another phase ? 

what is your feeling @mshima ? 

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@nicolas63 done at https://github.com/jhipster/generator-jhipster/pull/13021 😄.
Keep this open to give visibility.

**Comment by mshima** [comment]
> During default phase some treatment like `prepareRelationshipsForTemplates` is done just before composing

Composing or writing?

**Comment by nicolas63** [comment]
I just want to have access to _preparingRelationships to prepare relationship with dotnet specificities so yes your PR fix that ! 🥇
