### ISSUE TITLE
deploying on Heroku fails when the OAuth2 option is selected

### ISSUE THREAD

**Issue by redoc123** [jhipster/generator-jhipster#1304]
I created a new jhipster (V 2.6.0) app with the following settings. 

{
  "generator-jhipster": {
    "baseName": "her",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "authenticationType": "oauth2", //UPDATE: this issue seem to happening for oauth2 apps.
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "useCompass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "rememberMeKey": "e9119609914af5da68213e6e4f1a0b547c357a9f"
  }
}

I have nt made any changes to the app. I ran heroku sub genrator right after the creation without any modifications. trying to push my developer heroku edition. 

I am getting the following exception. 

remote: 
remote: -----> Deleting 0 files matching .slugignore patterns.        

remote: 
remote:  !     Push rejected, no Cedar-supported app detected        
remote: HINT: This occurs when Heroku cannot detect the buildpack        
remote:       to use for this application automatically.        
remote: See https://devcenter.heroku.com/articles/buildpacks        
remote: 

remote: Verifying deploy...
        

remote: 
remote: !	Push rejected to her.        
remote: 

To https://git.heroku.com/her.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/her.git'
<----------------------------------------------------------------------------------------------------->
Error: Command failed: remote: Compressing source files... done.        
remote: Building source:        
remote: 
remote: -----> Deleting 0 files matching .slugignore patterns.        
remote: 
remote:  !     Push rejected, no Cedar-supported app detected        
remote: HINT: This occurs when Heroku cannot detect the buildpack        
remote:       to use for this application automatically.        
remote: See https://devcenter.heroku.com/articles/buildpacks        
remote: 
remote: Verifying deploy...        
remote: 
remote: !	Push rejected to her.        
remote: 
To https://git.heroku.com/her.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/her.git'

<----------------------------------------------------------------------------------------------------->

I know that similar issues were created in the past but this is still an issue for me. Please advise.

**Comment by jdubois** [comment]
As you added a comment saying it's only for OAuth2 apps I'm updating the title.
I find it very strange that the stack couldn't be found because of OAuth2 - I didn't try it yet, but I can't find a link between those two. Can you try to deploy the same app without OAuth2?

**Comment by jdubois** [comment]
I just deployed an OAuth2 app without any issue on Heroku...

I'm using our development branch, and I just upgraded to Spring Security 4, so if your issue is really with OAuth2, this might be the solution.

Otherwise I have no idea how I could reproduce your issue -> can you check again when we release the next version (2.7.0, normally), which should be at the end of the week?
