### ISSUE TITLE
Login redirect doesn't work in OAuth2 and Vue

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13042]
##### **Overview of the issue**

If you're using Vue + OAuth 2.0 and try to navigate directly to a URL (e.g., `http://localhost:8080/admin/health`), you get an error page rather than redirected to log in.

<img width="1178" alt="Screen Shot 2020-11-14 at 2 04 34 PM" src="https://user-images.githubusercontent.com/17892/99156934-855cfd80-2682-11eb-8f51-20ddf2270da8.png">

Inspired by https://github.com/jhipster/generator-jhipster/issues/13010. 

NOTE: I tested Angular and it works as expected.

##### **Motivation for or Use Case**

The best user experience is you're prompted to log in, then returned to where you started.

##### **Reproduce the error**

Create an app with the following `.yo-rc.json`:

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.andespetro.tms"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "tms",
    "packageName": "com.andespetro.tms",
    "packageFolder": "com/andespetro/tms",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1604848055606,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": [],
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "reactive": false,
    "pages": [],
    "withAdminUi": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"]
  }
}
```

Start the app, then try to navigate directly to http://localhost:8080/admin/health. You'll get an error rather than being redirected to log in.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/13010

##### **JHipster Version(s)**

`main` branch on Nov 14, 2020.

**Comment by qmonmert** [comment]
@mraible I will try to fix that

**Comment by qmonmert** [comment]
@mraible PR done

**Comment by qmonmert** [comment]
@pascalgrimaud & @jdubois I claim my money 😄  https://opencollective.com/generator-jhipster/expenses/28085

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
