### ISSUE TITLE
Problems with --skip-server

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#13055]
##### **Overview of the issue**

If using `--skip-server` option then also one server side related question is asked, server side options are written into `.yo-rc.json` and in regeneration server side is generated.

##### **Motivation for or Use Case**

If skipping server then should not ask server side related questions and should not generate server side related content and files.

##### **Reproduce the error**

Run JHipster: `jhipster --skip-server`
Question "**[Beta] Do you want to make it reactive with Spring WebFlux? (y/N)**" is asked though this option is for server side and should not be asked.
Note: after generation `.yo-rc.json` contains also server side options with default values (for example `"packageName": "com.mycompany.myapp"`) which is confusing.

Regenerate with JHipster: `jhipster --force`
Server side is generated though `.yo-rc.json` contains `"skipServer": true`

##### **JHipster Version(s)**

Latest `main` branch.

```
jhipster@0.0.1-SNAPSHOT C:\projects\teest\jhipster-skip-server-2
`-- generator-jhipster@6.10.5  -> c:\projects\kaido-github\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "skipServer": true,
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "6.10.5",
    "skipClient": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1605530147390,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "promptValues": {
      "nativeLanguage": "en"
    },
    "clientThemeVariant": "",
    "packageName": "com.mycompany.myapp",
    "cacheProvider": "ehcache",
    "websocket": false,
    "databaseType": "sql",
    "prodDatabaseType": "postgresql",
    "devDatabaseType": "h2Disk",
    "searchEngine": false,
    "buildTool": "maven",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "serviceDiscoveryType": false,
    "enableHibernateCache": true,
    "languages": ["en", "fr"],
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "messageBroker": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

git version 2.29.2.windows.2

node: v12.18.4

npm: 6.11.3

yeoman: 3.1.1

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.27.4, build 40524192

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Do we still have the issue in main branch ?

**Comment by kaidohallik** [comment]
Left open because unrelated config generation issue: https://github.com/jhipster/generator-jhipster/pull/13058#issuecomment-728309913

**Comment by mshima** [comment]
Closing. The unrelated config generation issue will be tracked by https://github.com/jhipster/generator-jhipster/issues/13412.
