### ISSUE TITLE
React frontend after session timeout: Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. 

### ISSUE THREAD

**Issue by cifilaci** [jhipster/generator-jhipster#13059]
##### **Overview of the issue**

After session timeout on React fronted redirected to /login page what shows maximum depth exception:

_An unexpected error has occurred.
Details
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    in Lifecycle (created by Context.Consumer)
    in Redirect (created by Context.Consumer)
    in Route (created by PrivateRouteComponent)
    in PrivateRouteComponent (created by Connect(PrivateRouteComponent))
    in Connect(PrivateRouteComponent) (created by Routes)
    in Switch (created by Routes)
    in div (created by Routes)
    in Routes (created by App)
    in ErrorBoundary (created by App)
    in div (created by Card)
    in Card (created by App)
    in div (created by App)
    in div (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp (created by ConnectFunction)
    in ConnectFunction
    in div
    in Provider
    in ErrorBoundary_

##### **Motivation for or Use Case**

Can not reauthenticate, since if I try to authenticate again, t gives the same error.

##### **Reproduce the error**

Login form UI. Leave the UI idle, then try to navigate on site.

##### **JHipster Version(s)**

```
ultra-balaton-planner@0.0.1-SNAPSHOT /home/lczifranics/websites/ubwithmoni/backend
└── generator-jhipster@6.8.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "baseName": "UltraBalatonPlanner",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "hu"],
    "messageBroker": false,
    "nativeLanguage": "hu",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "applicationType": "monolith",
    "packageName": "org.tuning.startup",
    "packageFolder": "org/tuning/startup",
    "useSass": true,
    "jhipsterVersion": "6.8.0",
    "creationTimestamp": 1592338380305,
    "skipServer": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["Leg", "Plan", "Preference", "Race", "Team"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Race {
  name String maxlength(140) required,
  gpx AnyBlob required
}
entity Team {
  name String required,
  profileUrl String
}
entity Plan
entity Leg {
  length Float,
  sponsorName String maxlength(140) required,
  start String maxlength(140) required,
  end String maxlength(140) required,
  lat Float,
  lon Float
}
entity Preference {
  averageSpeed Double required,
  profileUrl String,
  phoneNumber String,
  nickname String,
  averagePaceMin Integer,
  averagePaceSec Integer
}
relationship OneToOne {
  Preference{user(login)} to User
}
relationship ManyToOne {
  Plan{teams(name)} to Team,
  Plan{race(name)} to Race,
  Leg{users(login)} to User
}
relationship ManyToMany {
  Race{teams(name)} to Team{race},
  Race{legs(sponsorName)} to Leg{race},
  Team{users(login)} to User,
  Plan{legs(sponsorName)} to Leg{plan}
}

dto Race, Team, Plan, Leg, Preference with mapstruct
service Race, Team, Plan, Leg, Preference with serviceImpl

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

git version 2.25.1

node: v12.16.2

npm: 6.14.8

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.12, build 48a66213fe

docker-compose version 1.21.2, build a133471

**Comment by mraible** [comment]
This sounds similar to #13010, which was fixed by https://github.com/jhipster/generator-jhipster/pull/13028. Are you able to try with the `main` branch to see if it's fixed?

**Comment by pascalgrimaud** [comment]
closing this as it looks like duplicate ticket
