### ISSUE TITLE
Switch modules to use jhipster command instead of yo.

### ISSUE THREAD

**Issue by fdelbrayelle** [jhipster/generator-jhipster#13068]
##### **Overview of the issue**

When using JHipster Kafka module by launching `yo jhipster-kafka`, this new step is called in `JHipsterBaseGenerator`: registerCommitPriorityFilesTask and leads to a crashing error : 

```
events.js:180
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.rootGenerator is not a function
    at module.exports.method (/home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/generator-jhipster/generators/generator-base-private.js:1376:30)
    at Object.<anonymous> (/home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:991:25)
    at /home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:992:11)
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event at:
    at Immediate.<anonymous> (/home/francois/dev/jhipster/generator-jhipster-kafka/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1022:20)
    at processImmediate (internal/timers.js:439:21)
```

Cause by a api introduced in some minor version of yeoman-environment: https://github.com/jhipster/generator-jhipster/blob/c1279fa9747c3b824408401e5d45ca3be39d61ee/generators/generator-base-private.js#L1376

##### **Motivation for or Use Case**

It's blocking to generate new files and use existing modules using the last version of the main generator.

##### **Reproduce the error**

Only reproducible with a yo with old yeoman-environment version.
1. `mkdir test-app && cd test-app`
2. `jhipster` after linking current folder/app to main generator on updated main branch
3. In another folder: `git clone https://github.com/fdelbrayelle/generator-jhipster-kafka.git`, `git checkout chore_v7_compatibility` and then `npm link`
4. In the app folder: `npm link generator-jhipster-kafka`
5. `yo jhipster-kafka` and choose all default answers (you can type `Toto` as prefix object)
6. :boom:

##### **Suggest a Fix**

~Maybe replace `if (this.env.rootGenerator() !== this) return;`: by `if (this.env.rootGenerator !== this) return;` in `generator-base-private.js:`. What do you think about it @mshima?~ More breaking changes will be introduced.

Switch to use jhipster cli, so we can control installed yeoman-environment version.
`jhipster module kafka` instead of `yo jhipster-kafka`.

##### **JHipster Version(s)**

Main branch

##### **JHipster configuration**

```
$ jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT /home/francois/dev/jhipster/tests/test-jhipster-main
└── generator-jhipster@6.10.5 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "6.10.5",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1605608383185,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": ["messageBroker:kafka"],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": "kafka",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "fr",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "reactive": false,
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1605608479000
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Linux amd64-64-Bit Compressed References 20191016_358 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)

git version 2.25.1

node: v12.13.0

npm: 6.12.0

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entity generated

##### **Browsers and Operating System**

Ubuntu 20.04

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
> Maybe replace `if (this.env.rootGenerator() !== this) return;`: by `if (this.env.rootGenerator !== this) return;` in `generator-base-private.js:`. What do you think about it @mshima?

For now I recommend to reinstall yo to update yeoman-environment and ignore this error.

This would be a temporary workaround.
I am planning to have a hard dependency on yeoman-environment 3.0.0 and probably yo will not be updated in time for jhipster 7.

Maybe we should switch modules to use jhipster cli instead of yo. What do you think @murdos ?

**Comment by fdelbrayelle** [comment]
Thank you for your answer!

It worked with `npm install -g yo@latest` after removing it from nvm :+1:

**Comment by murdos** [comment]
> Maybe we should switch modules to use jhipster cli instead of yo. What do you think @murdos ?

Yeah, sounds good 👍
