### ISSUE TITLE
java.lang.IllegalStateException: No current ServletRequestAttributes

### ISSUE THREAD

**Issue by khalidnouh** [jhipster/generator-jhipster#13064]
in a microservice spring boot app ,when I invoke a rest like this

```java
   @GetMapping("/data")
    public ResponseEntity<List<ApplicantDTO>> getAllApplicants(ApplicantCriteria criteria, Pageable pageable) {
        log.debug("REST request to get Applicants by criteria: {}", criteria);
        Page<ApplicantDTO> page = applicantQueryService.findByCriteria(criteria, pageable);
        HttpHeaders headers =  PaginationUtil.generatePaginationHttpHeaders(ServletUriComponentsBuilder.fromCurrentRequest(), page);
        return ResponseEntity.ok().headers(headers).body(page.getContent());
    }
```
the error occurred in generatePaginationHttpHeaders ,although it works fine in another microservice with the same configurations

**Comment by pascalgrimaud** [comment]
plz, provide all information in template, as we don't have any information to reproduce your issue

**Comment by khalidnouh** [comment]
![2020-11-18 17_16_30-Greenshot](https://user-images.githubusercontent.com/10672746/99549083-fa516f80-29c1-11eb-98b3-2ae78fa8934a.png)
in this attached image you can see a dropdownlist of ids ,it shows only 21 item (in the database i have 31 items), 
i don't want  to increase the size , so i need a way to get the other items in this list

**Comment by khalidnouh** [comment]
@pascalgrimaud

**Comment by pascalgrimaud** [comment]
You need to use `jhipster info` and copy paste all information on your config.

Without this, we can't guess your config ?
Is it with Angular ? React ?
Is it with Cassandra ? Neo4j ?
Is it Reactive or Mvc ?
etc...

**Comment by khalidnouh** [comment]
@pascalgrimaud 
i using angular 
##### **JHipster Version(s)**

```
applicant-user-management@0.0.0 D:\Aman Repos\applicant-mgmt-ms
`-- (empty)

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "gitCompany": "",
    "baseName": "ApplicantUserManagement",
    "packageName": "com.isoft.applicant.um",
    "packageFolder": "com/isoft/applicant/um",
    "serverPort": 8082,
    "serviceDiscoveryType": "eureka",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "enableSwaggerCodegen": false,
    "messageBroker": false,
    "buildTool": "maven",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["ar-ly", "en"],
    "clientFramework": "angularX",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "6.7.1",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1583139421728,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  },
  "git-provider": "GitHub",
  "git-company": "mamdouh87",
  "repository-name": "applicant-usermgmt-ms"
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Applicant {
  userId Integer,
  type Integer,
  status Integer,
  category Integer,
  code String,
  centerId Integer
}
entity PersonalDetails {
  fullName String,
  mobileNo String,
  nationalId String,
  passportKey String,
  firstName String,
  middleName String,
  lastName String,
  familyName String,
  birthDate LocalDate,
  passportIssueCountry String,
  email String,
  position String
}
relationship OneToOne {
  Applicant{personalDetails} to PersonalDetails
}

dto Applicant, PersonalDetails with mapstruct
paginate Applicant, PersonalDetails with pagination
service Applicant, PersonalDetails with serviceImpl
microservice Applicant, PersonalDetails with ApplicantUserManagement
filter Applicant, PersonalDetails
clientRootFolder Applicant, PersonalDetails with applicant-mgmt-ms

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

git version 2.23.0.windows.1

node: v12.5.0

npm: 6.9.0

yeoman: 3.1.1

identical .jhipster\Applicant.json
identical .jhipster\PersonalDetails.json
INFO! Congratulations, JHipster execution is complete!

**Comment by khalidnouh** [comment]
@pascalgrimaud  if there is any shortcut to swap between elements in the drop down list?

**Comment by khalidnouh** [comment]
@pascalgrimaud  i need your help sir

**Comment by pascalgrimaud** [comment]
As you choose pagination, the findAll method return a Page.
If you want to get all elements, remove the pagination, or modify your code to return a full list.
But don't forget that if your table have a lot of entries (more than 1000), the selection will be painful for the end user.

I'm closing this, as there is no bug in JHipster : it's the normal behavior of generated projects with JHipster.
