### ISSUE TITLE
Mock axios with sinon

### ISSUE THREAD

**Issue by nonomoho** [jhipster/generator-jhipster#13066]
##### **Overview of the feature request**

Use sinon to mock axios instead of jest

##### **Motivation for or Use Case**

In my project it was useful to mock axios with sinon to have more possibilities to check what was called.
There is not much impact for the services but it makes it easier to add new code for more complicated calls

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
Why use sinon while jest can also mock node_modules dependency ? What are the advantages of using `sinon` over jest mocks ?

**Comment by nonomoho** [comment]
Sinon stubs have some advantages: 
- It's less verbose
- More importantly sinon API is very easy and more natural comparing to Jest's implementation
- You can use `withArgs('...')`methods. Instead of `mockedAxios.get = jest.fn(apiName => (apiName === 'yourUrl' ? Promise.reject() : Promise.resolve({})));` you can use `axiosStub.get.withArgs('api/account').rejects();`
