### ISSUE TITLE
Enable prettier for html files.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#13090]
##### **Overview of the feature request**

We should consider enabling prettier for html files at the generator.

##### **Motivation for or Use Case**

Standardise html formatting.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
+ 1

**Comment by kaidohallik** [comment]
Maybe it's good idea to put into v7 release notes something like: "We have enabled Prettier for HTML. You can run Prettier with html enabled before upgrading and commit changes to Git to see real changes in HTML files after upgrade.".

**Comment by gmarziou** [comment]
I have a question: does Prettier for HTML run only at generation time or also using git commit hooks?

**Comment by kaidohallik** [comment]
`getPrettierExtensions()` is used in all places:
* in generation
* in `package.json` in script `prettier:format`
* in `.lintstagedrc.js`

So if user doesn't skip commit hook generation then HTML is prettified also on commit.

**Comment by gmarziou** [comment]
Are there any instructions about how to disable it?

**Comment by kaidohallik** [comment]
About `skip-commit-hook` option.

No info in:
* https://www.jhipster.tech/creating-an-app/
* jhipster --help

Only place I found is:
* https://www.jhipster.tech/2018/06/20/jhipster-release-5.0.0.html#front-end

**Comment by gmarziou** [comment]
Thanks @kaidohallik

**Comment by mshima** [comment]
`jhipster app --help` prints every option.
