### ISSUE TITLE
Replace JpaRepository with @RepositoryDefinition

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#13112]
##### **Overview of the issue**

We are currently using `EntityRepository extends JpaRepository<Entity, Id>`.
It works great but `JpaRepository` provides much more apis than we use. Eg:
- Batch api
- Query by example

We should replace it with `@RepositoryDefinition(domainClass = Entity.class, idClass = Id.class)` annotation and implement only the required methods.

##### **Motivation for or Use Case**

Our repository should provide only the operations we use.

##### **JHipster Version(s)**

master

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
> It works great but JpaRepository provides much more apis than we use

I think it was the initial goal. Maybe our generated code don't use all apis, but our users will.
