### ISSUE TITLE
Localization key "metrics.jvm.http.table.max" created only in english language file

### ISSUE THREAD

**Issue by funder7** [jhipster/generator-jhipster#13129]
##### **Overview of the issue**

The key `metrics.jvm.http.table.max` is present only in the english localization file, while in the others is missing.

##### **Motivation for or Use Case**

Multi language project.

##### **Reproduce the error**

Generate a project from JDL having: `languages [en, it, fr, es, de]`

##### **Related issues**

/

##### **Suggest a Fix**

I can provide the italian localization: "Massima". 

##### **JHipster Version(s)**

`6.10.5`

##### **JHipster configuration**

Tried to launch `jhipster info`, it returned this error: `Error: EROFS: read-only file system, open '/home/-username-/.config/insight-nodejs/insight-generator-jhipster.json.2091904192'`

Node version: 12.19.1 (LTS)
Npm version: 6.14.8

##### **Browsers and Operating System**

Chrome - Elementary OS 5 (ubuntu based)

**Comment by qmonmert** [comment]
I confirm the bug
