### ISSUE TITLE
Add globalFilter field in criteria that would much on many fields

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#13132]
##### **Overview of the feature request**

Often, when using filterable entities, (specially in a dropdown with search box) it is very useful to have have some field in criteria that would much against multiple fields:
(ex: employee.visa, employee.firstName, employee.lastName) elasticsearch can be used but is often over kill for such narrow use cases. I would suggest adding a new field in criteria: `String globalFilter`, that would (by default) match against the id, and otherEntityField when the current entity i used in relationships.
the generated code would look like this:
```
    protected Specification<Customer> createSpecification(CustomerCriteria criteria) {
        Specification<Customer> specification = Specification.where(null);
        if (criteria != null) {
            ...
            if (criteria.getFirstName() != null) {
                specification = specification.and(buildStringSpecification(criteria.getFirstName(), Customer_.firstName));
            }
            if (criteria.getLastName() != null) {
                specification = specification.and(buildStringSpecification(criteria.getLastName(), Customer_.lastName));
            }
            ...
            // once all AND are done we add a last AND with all ORs
            if(criteria.getGlobalFilter() != null) {
                Specification<Customer> orSpecification = Specification.where(null);
                if (NumberUtils.isParsable(criteria.getGlobalFilter())) {
                    LongFilter globalLongFilter = new LongFilter();
                    globalLongFilter.setEquals(NumberUtils.createLong(criteria.getGlobalFilter()));
                    orSpecification = orSpecification.or(buildSpecification(globalLongFilter, Customer_.id));
                }
                StringFilter globalStringFilter = new StringFilter();
                globalStringFilter.setContains(criteria.getGlobalFilter());
                orSpecification = orSpecification.or(buildStringSpecification(globalStringFilter, Customer_.firstName));
                orSpecification = orSpecification.or(buildStringSpecification(globalStringFilter, Customer_.lastName));
                orSpecification = orSpecification.or(buildStringSpecification(globalStringFilter, Customer_.avsNumber));
                orSpecification = orSpecification.or(buildStringSpecification(globalStringFilter, Customer_.other));
                specification = specification.and(orSpecification);
            }
        }
        return specification;
    }
}
```
 
We use the primeng blueprint, which expects something like this for there awesome filterable lazy dropdown.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by gzsombor** [comment]
As you showed, it's trivial to add to the generated code, however this requirement looks very specific to your case. Yes, searching in 2-3 string fields could common, but searching in all - would be definitely surprising behavior.

**Comment by yelhouti** [comment]
@gzsombor I clearly don't want to implement searching in all fields, but just in the ones used in relationships.
We introducing composite keys, which means that we would need to start searching in two or more entities for the dropdown, this will become a must have if we want searchable dropdowns without elastic search.

**Comment by gzsombor** [comment]
Sorry, I don't understand. You've showed a code, where you would like to search in customer "first name", "last name" "avs number" and "other" - and also in the customer id - which is a number, not a string. How does this relates to compound keys? Do you want to search by compound keys? But in that case, you could do it by the individual parts of the keys, just "and"-ing together.

**Comment by yelhouti** [comment]
No worries, let me give you some example:
here is a JDL:
```
entity Employee{
        @id username String required
        fullname String required
}

entity EmployeeSkill{
        // compositeId employeeSkill.name, employee.id
        @id name String required
        level Integer required
}

relationship OneToMany {
        @id Employee{skill(name)} to EmployeeSkill{employee(fullname) required}
}

entity CertificateType{
        name String required
}

entity EmployeeSkillCertificate{
    // compositeId EmployeeSkill.employee.id, EmployeeSkill.name, CertficiateType.id
        grade Integer required
    date LocalDate required
}

relationship OneToMany{
        @id CertificateType to EmployeeSkillCertificate{type(name) required}
}

relationship OneToMany{
        @id EmployeeSkill to EmployeeSkillCertificate{skill required}
}
```

lets say I want to create an EmployeeSkillCertificate for a specific EmployeeSkill, I would need to use a dropdown.
To find the correct EmployeeSkill I would need to filter either by:
1- EmployeeSkill.employee.username
2- EmployeeSkill.name (the name of the skill)
since there is more than one entity, I would need to search using both fields (with an OR) and list all matching EmployeeSkill for the end user to choose.

We could even envisage a more advances scenario, where the globalFilter is split using " " (space), and loop over all values apply the same filter on all entities with an OR.

I have been using composite keys in my blueprint for while, and this is a much common use case than what you would think.

**Comment by gzsombor** [comment]
Thanks for the explanation, I mostly understand now. One question is that, do you want to have a dropdown, or an autocomplete text field? For a dropdown you don't need filtering, just ask the backend for 20 entities, and done (this is what JHipster currently does for every entities) So I assume, that you want autocomplete, aren't you?
 It's a bit funny, because 3 years ago, I wanted to do it for plain String fields - and I even implemented it for Angular in #6618, but it wasn't merged, because it seemed that no-one was interested enough, in the end, nor do I.
 
For the composite id filter scenario, I would suggest to generate a custom Id criteria class inside the EntityCriteria class - just like we currently do for enums. So for your example:

```
class EmployeeSkillCriteria {

 class IdCriteria {
    // filtering on the individual parts of the composite key:
    StringFilter employeeSkillName;
    LongFilter employeeId;

    String contains;
  }

  IdCriteria id;
}
```

And in the service, you can have a function which handles this IdCriteria, and delegate it to the separate StringFilter / LongFilter handling code _and_ deal with these bit specific 'or' functionalities. Probably, this won't be too complicated, and would be consistent with the rest of the REST API. I mean, you can put these into the URL: _?id.employeeSkillName=ABC-123&id.employeeId.equals=456_ or _?id.contains=XYZ_

**Comment by yelhouti** [comment]
@gzsombor I am using some king of a mix between dropdown and autocomplete, but I don't want to talk about the details of that here, as it's not relevant to the discussion., but feel free to ask me on gitter or otherwise and I will explain the constraints that lead to the solution we are using now.

I would strongly discourage against the use of the id field in the frontend, since it is an implementation detail + I might want to filter using other fields that are not included in the idCriteria.
And much more importantly, you are not solving my main problem, using ONE vaue to filter against multiple fields, the same way you would if you had something like elasticsearch.

**Comment by yelhouti** [comment]
I would really like to start working on this, as soon as I know that is desired, and when ready will get merged.

**Comment by gzsombor** [comment]
Sorry, maybe I don't follow you, what and how do you want to achieve. 
If you just want to filter for entities with 'or' expression, in multiple fields, you can write something like this:

```
private Specification<XYZ> byEntityNameContains(String name) {
    return (root, query, builder) -> {
        builder.or(
            builder.like(builder.upper(root.get(XYZ_.name)), name),
            builder.like(builder.upper(root.get(XYZ_.description)), name),
            builder.like(builder.upper(root.get(XYZ_.customer).get(Customer_.name)), name)
            )
        }
}

``` 
 
Have this string field inside the criteria. 
But I don't get, from where do you want to get, which fields should be queried, and which not. Do you want to add a new questions when the user creates a string field, if that field should take part in this 'global name' search? And of course do the same for every relations?

**Comment by yelhouti** [comment]
@gzsombor code would look close to this, but we would not ask questions, we would use the otherEntityFields (fields is plural in case of composite ids)

The question is, why not add these manually? And my answer would be, because when I write a blueprint for the frontend, that uses filters (in dropdowns for pageable entities) I need to be able to filter by something, and globalFilter is the right thing to have.

**Comment by yelhouti** [comment]
Should I start working on this? @gzsombor @pascalgrimaud  I am ready to make a PR.
