### ISSUE TITLE
Generator freezes after #13124

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#13138]
##### **Overview of the issue**

After #13124 in my Windows 10 `jhipster` command is freezing after welcome message:
```
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________
```
If reverting #13124 then generator starts to work again.

##### **Motivation for or Use Case**

Generator should not freeze. Generator should work.

##### **Reproduce the error**

Link `generator-jhipster` latest main branch and try to generate with command `jhipster`

##### **Related issues**

Started after #13124

##### **Suggest a Fix**

If I look at changes then `prettier-plugin-java` uses Prettier version 2.2.0 but `generator-jhipster` uses version 2.1.2 - maybe this version difference causes this problem and solution is to upgrade Prettier to 2.2.0 also in generator.

##### **JHipster Version(s)**

Latest main branch.

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
FYI: Prettier update to 2.2.0 by dependabot in #13120 is also failing.

**Comment by kaidohallik** [comment]
FYI: I reverted #13120 and updated Prettier to 2.2.0 and this issue still exists. So seems to be Prettier 2.2.0 issue.

**Comment by kaidohallik** [comment]
I tested in Windows with different shells and Prettier 2.2.0 in JHipster:
* **is not working** with Command Prompt and PowerShell
* **is working** with Git Bash

**Comment by kaidohallik** [comment]
I updated some existing project to Prettier 2.2.0 and formatting with this was successful in Command Prompt - so problem exists only when using JHipster + Prettier 2.2.0 in Command Prompt or PowerShell.

**Comment by DanielFran** [comment]
cc @clementdessoude

**Comment by kaidohallik** [comment]
Sharing some debug information.

Process hangs in `node.js` internal function
```
stream_base_commons.handleWriteReq
```
in line
```
return handle.writeUtf8String(req, data);
```
where data is "Generator is starting!" and generator is `jhipster:common` (the same function with `jhipster:app` succeeded and text was printed out in the console)

This "Generator is starting!" comes from `yeoman-generator/lib/index.js`

Last point in JHipster code is function `composeWithJHipster` where generator is `jhipster:common`

If commenting out "Generator is starting!" in yeoman then crashes in the next console write command from server `index.js`:
"This is an existing project, using the configuration from your .yo-rc.json file"

So seems that something happens with console after `jhipster:app` and before other generators.

**Comment by mshima** [comment]
Reverting fixes the problem?

**Comment by kaidohallik** [comment]
Yes.

**Comment by mshima** [comment]
What node version are you using? Can you try with 14 lts?

**Comment by kaidohallik** [comment]
My node version was `v12.18.4`, after upgrading node to `v14.15.1` `jhipster` started to work again with the latest `main` branch.
Thanks @mshima for suggestion.
Closing this as this is working with the latest Node LTS version.

**Comment by mshima** [comment]
For reference, the node.js bug seems to be https://github.com/nodejs/node/issues/30701
