### ISSUE TITLE
JDL: an application is not generated if it doesn't contain entities

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#13141]
As @pmverma reported in our mailing list (thanks again).

##### **Overview of the issue and  Motivation for or Use Case**

An application should be generated whether it contains entities or not, it's not the case.

##### **Reproduce the error**

Importing this JDL sample only generates the first app.
```jdl
application {
  config {
    baseName app1
  }
  entities A
}

application {
  config {
    baseName app2
  }
}
```

##### **Related issues**

I don't think there is one.

##### **Suggest a Fix**

[This](https://github.com/jhipster/generator-jhipster/blob/main/cli/import-jdl.js#L389) seems to be the issue.
A test should be made for this case.

##### **JHipster Version(s)**

Tested on main branch.

-   [X] Checking this box is mandatory (this is just to show you read everything)
-   [X] Yes I do love JHipster.

**Comment by swarajsaaj** [comment]
I did some analysis and issue seems to be at:-
https://github.com/jhipster/generator-jhipster/blob/0aec2eb0dd90d7289fde02c03546b5bf64a9b541/jdl/converters/jdl-to-json/jdl-with-applications-to-json-converter.js#L49
where this condition returns either a map of applications without entities directly, but this method does not add applications without entities in map anywhere below
