### ISSUE TITLE
User management and User Group Management

### ISSUE THREAD

**Issue by pnreddysvu** [jhipster/generator-jhipster#1314]
User management and User Group Management is very common requirement for enterprise applications.

Jhipster provides user subscription but that will be useful for only one type of applications may be social apps. Most of the enterprise applications will not allow self subscription. Only admin will be able to manage users and user groups.

Another common requirement is bulk provisioning of users which could be list of entries in csv and upload which will trigger provisioning/deletion.

Another common requirement is searching/sorting existing users and modify/delete them. I think this can be easily implemented once #1270 is fixed.

I did not find any doc on how to modify existing user object i.e adding new attributes/deleting existing attributes. That is very much needed.

There is a specification for user/user group management. You may be already knowing this.
http://www.simplecloud.info/

The above specification provides REST APIs.

and one implementation which uses Spring + Java is 
https://github.com/cloudfoundry/uaa

Please have a look if some of these can be reused in JHipster.

All things may not be possible to implement in Jhipster. But it will be good if most common requirements for enterprise apps will be in place and supported out-of the box.

**Comment by jdubois** [comment]
I had no idea there was a spec for this, thank you for pointing this out.

Some notes:

- This has already been discussed: it's a lot of work, and I'm not sure we have the ressources to do it. Besides, it might go a little too far. But I agree, I'd like to have this, at least as an option.
- I've seen there are already multiple implementations, including one in CloudFoundry: https://github.com/cloudfoundry/uaa -> does this really makes sense to create our own implementation? Shouldn't we better integrate an existing implementation? This is new too me, but this opens new possibilities: if we could integrate such a solution, that would be my favorite choice.

**Comment by pnreddysvu** [comment]
Yes I agree with you. It does not make sense to implement again. We can integrate with UAA. Because they have already taken care of many aspects. Cloud UAA supports user authentication from multiple data sources including social, in-house, LDAP etc.

It will be a great solution if we can integrate with Cloud UAA so that user management/authentication will be handled out-of the box. I heard from Dave Syer in one of his webinars saying that they are going to migrate cloud CAA to Spring bootstrap.

**Comment by jdubois** [comment]
OK, so I'm closing this as we will not implement this JHipster anyway.

Concerning Cloud UAA, we will see how this project evolves, and how easy it is to connect to it.

**Comment by pnreddysvu** [comment]
Are you Ok to have separate authorization server?
why I am asking is cloudfoundry UAA provides war file which can be run as an independent Oauth2 authorization server. The advantage with independent authorization server is multiple applications can use single authorization server. 

currently JHipster provides embedded authorization server. If we want to develop multiple applications then each will have its own authorization server which will be difficult to maintain. So it is better to have independent authorization server. If you are OK to integrate Jhipster with independent   
oauth2 authorization server(cloud foundry uaa), I can tryout sample apps integration with UAA. 

Note: I dont know anything about front end development. So  I will sample apps  with curl/java client.

Let me know your thoughts.

I have a suggestion. Currently Jhipster provides 3 types of authentication. So it will be good if you can add one more option like Outh2 support with cloudfoundry UAA so that if any one wants separate auth server they can use UAA. otherwise they can go with one of other 3 options.

**Comment by jdubois** [comment]
Yes that would be a 4th option, hopefully not too different from the existing OAuth2 option.

**Comment by svennela** [comment]
+1 cloudfoundry UAA. It is production ready authserver.

**Comment by pnreddysvu** [comment]
@jdubois yes it is same as existing OAuth2. I feel instead of maintaining separate OAuth2 implementation it is better to reuse UAA which is a dedicated project for OAuth2. SO that JHipster can concentrate on different useful things. I saw few other issues/feature requests related to social integration(facebook,google etc). UAA already supports this. Just think of reusing UAA OAUth2 implementation instead of maintaining it.

**Comment by eallais** [comment]
+1

**Comment by vikas-a** [comment]
+1
