### ISSUE TITLE
Generates e2e-test fails since expected date format is of unknown format

### ISSUE THREAD

**Issue by carestra** [jhipster/generator-jhipster#13147]
##### **Overview of the issue**
Importing entity generates e2e-test which fails since expected date format is of unknown format.
Exception:
AssertionError: expected '10120-01-26T02:30' to include '2001-01-01T02:30'

##### **Motivation for or Use Case**
I expect the generated e2e-test are correct after importing an entity.

##### **Reproduce the error**
Steps to reproduce:
1 - Install JHipster using "Local installation with NPM", https://www.jhipster.tech/installation/
2 - Create the project folder and move into it.
3 - Run "jhipster'  (see yo-rc.json) and create app.
4 - Import entity (see activity.jdl), jhipster import-jdl activity.jdl
5 - Start keycloak, docker-compose -f src/main/docker/keycloak.yml up -d
6 - Start app, ./mvnw
7 - Start new terminal session and move to project folder
8 - Run e2e-test, npm run e2e
9 - The test in src/test/javascript/e2e/entities/activityactivity-update.page-object.ts fails and outputs
AssertionError: expected '10120-01-26T02:30' to include '2001-01-01T02:30'

##### **Related issues**
No related issues found

##### **Suggest a Fix**
Manually I can create a new 'activity' and I can see that the date is correct (in h2disk).
The date-utils.ts use: 
export const APP_LOCAL_DATETIME_FORMAT = 'YYYY-MM-DDTHH:mm';
so why it return 10120-01-26T02:30'? 

##### **JHipster Version(s)**
"jhipsterVersion": "6.10.5"

##### **JHipster configuration**
carestra:activity $ jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
activity@0.0.1-SNAPSHOT /**/**/activity
└── generator-jhipster@6.10.5

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "se.carestra.learn.jhipster"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "activity",
    "packageName": "se.carestra.learn.jhipster",
    "packageFolder": "se/carestra/learn/jhipster",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "darkly",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1606418633256,
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Activity {
  title String required,
  startHour Integer required min(0) max(23),
  endHour Integer required min(0) max(23),
  activationDate Instant required,
  deactivationDate Instant,
  createDate Instant required,
  lastChangedDate Instant
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20201023_788 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)

git version 2.23.0

node: v14.15.0

npm: 6.14.8

yeoman: 3.1.1

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.27.4, build 40524192

identical .jhipster/Activity.json
INFO! Congratulations, JHipster execution is complete!
carestra:activity $

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Activity.json
```json
{
  "name": "Activity",
  "fields": [
    {
      "fieldName": "title",
      "fieldType": "String",
      "fieldValidateRules": [
        "required"
      ]
    },
    {
      "fieldName": "startHour",
      "fieldType": "Integer",
      "fieldValidateRules": [
        "required",
        "min",
        "max"
      ],
      "fieldValidateRulesMin": "0",
      "fieldValidateRulesMax": "23"
    },
    {
      "fieldName": "endHour",
      "fieldType": "Integer",
      "fieldValidateRules": [
        "required",
        "min",
        "max"
      ],
      "fieldValidateRulesMin": "0",
      "fieldValidateRulesMax": "23"
    },
    {
      "fieldName": "activationDate",
      "fieldType": "Instant",
      "fieldValidateRules": [
        "required"
      ]
    },
    {
      "fieldName": "deactivationDate",
      "fieldType": "Instant"
    },
    {
      "fieldName": "createDate",
      "fieldType": "Instant",
      "fieldValidateRules": [
        "required"
      ]
    },
    {
      "fieldName": "lastChangedDate",
      "fieldType": "Instant"
    }
  ],
  "relationships": [],
  "changelogDate": "20201126193150",
  "entityTableName": "activity",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "clientRootFolder": "",
  "applications": "*"
}
```

##### **Browsers and Operating System**
Occurs on MacOs Catalina, version 10.15.7, Mac mini (2018).

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@carestra which test fails ?

**Comment by carestra** [comment]
@qmonmert the test in src/test/javascript/e2e/entities/activityactivity-update.page-object.ts

Updating the info with the failing test name.

**Comment by qmonmert** [comment]
I don't reproduce on the main branch

**Comment by carestra** [comment]
I still have the problem and I can reproduce it al lover again with the .yo-rc.json and entity.jdl files.
I get:
Activity e2e test
    ✓ should load Activities
    1) should create and delete Activities


  8 passing (10s)
  1 failing

  1) Activity e2e test
       should create and delete Activities:
     AssertionError: expected '10120-01-29T02:30' to include '2001-01-01T02:30'
      at ActivityUpdatePage.<anonymous> (src/test/javascript/e2e/entities/activity/activity-update.page-object.ts:119:60)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/tslib/tslib.js:110:62)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)



[11:07:02] I/launcher - 0 instance(s) of WebDriver still running
[11:07:02] I/launcher - chrome #01 failed 1 test(s)
[11:07:02] I/launcher - overall: 1 failed spec(s)
[11:07:02] E/launcher - Process exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! activity@0.0.1-SNAPSHOT e2e: `protractor src/test/javascript/protractor.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the activity@0.0.1-SNAPSHOT e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /[*******]/.npm/_logs/2020-11-29T10_07_02_319Z-debug.log


and the file "2020-11-29T10_07_02_319Z-debug.log"

0 info it worked if it ends with ok
  1 verbose cli [
  1 verbose cli   '/[******]/.nvm/versions/node/v14.15.0/bin/node',
  1 verbose cli   '/[******]/.nvm/versions/node/v14.15.0/bin/npm',
  1 verbose cli   'run',
  1 verbose cli   'e2e'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.0
4 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
5 info lifecycle activity@0.0.1-SNAPSHOT~pree2e: activity@0.0.1-SNAPSHOT
6 info lifecycle activity@0.0.1-SNAPSHOT~e2e: activity@0.0.1-SNAPSHOT
7 verbose lifecycle activity@0.0.1-SNAPSHOT~e2e: unsafe-perm in lifecycle true
8 verbose lifecycle activity@0.0.1-SNAPSHOT~e2e: PATH: /[******]/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/[******]/[******]/otherapp/node_modules/.bin:/[******]/Applications/sdkman/candidates/scala/current/bin:/[******]/Applications/sdkman/candidates/sbt/current/bin:/[******]/Applications/sdkman/candidates/maven/current/bin:/[******]/Applications/sdkman/candidates/java/current/bin:/[******]/Applications/sdkman/candidates/dotty/current/bin:/usr/local/sbin:/[******]/.nvm/versions/node/v14.15.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/[******]/Applications/mongodb/client
9 verbose lifecycle activity@0.0.1-SNAPSHOT~e2e: CWD: /[******]/[******]/otherapp
10 silly lifecycle activity@0.0.1-SNAPSHOT~e2e: Args: [ '-c', 'protractor src/test/javascript/protractor.conf.js' ]
11 silly lifecycle activity@0.0.1-SNAPSHOT~e2e: Returned: code: 1  signal: null
12 info lifecycle activity@0.0.1-SNAPSHOT~e2e: Failed to exec e2e script
13 verbose stack Error: activity@0.0.1-SNAPSHOT e2e: `protractor src/test/javascript/protractor.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/[******]/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
  13 verbose stack     at EventEmitter.emit (events.js:315:20)
  13 verbose stack     at ChildProcess.<anonymous> (/[******]/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    13 verbose stack     at ChildProcess.emit (events.js:315:20)
    13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    14 verbose pkgid activity@0.0.1-SNAPSHOT
    15 verbose cwd /[******]/[******]/otherapp
    16 verbose Darwin 19.6.0
    17 verbose argv "/[******]/.nvm/versions/node/v14.15.0/bin/node" "/[******]/.nvm/versions/node/v14.15.0/bin/npm" "run" "e2e"
    18 verbose node v14.15.0
    19 verbose npm  v6.14.8
    20 error code ELIFECYCLE
    21 error errno 1
    22 error activity@0.0.1-SNAPSHOT e2e: `protractor src/test/javascript/protractor.conf.js`
    22 error Exit status 1
    23 error Failed at the activity@0.0.1-SNAPSHOT e2e script.
    23 error This is probably not a problem with npm. There is likely additional logging output above.
    24 verbose exit [ 1, true ]

**Comment by mraible** [comment]
Does it happen with v7 beta 0?

**Comment by avdev4j** [comment]
Hi @carestra 
I tried to reproduce this error but with no success. I tested on both v7 (main branch) and the 6.10.5 version. 

Here is an extract of my JHipster info output. Please let me know if you still encounter the problem but since we can't reproduce it I'm obliged to close this ticket for the moment.

If you have more information please let us know. You could also try on the V7 beta version right now.

Anyway, we suggest moving to the Cypress option when the final v7 will be available.

If we have more information or was can reproduce it we will consider reopening it.

All the tests have been made during a stream session, you can find it here http://twitch.tv/avdev4j

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
activity@0.0.1-SNAPSHOT /private/tmp/13147
└── generator-jhipster@6.10.5

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "se.carestra.learn.jhipster"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "activity",
    "packageName": "se.carestra.learn.jhipster",
    "packageFolder": "se/carestra/learn/jhipster",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "darkly",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1606418633256,
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Activity {
  title String required,
  startHour Integer required min(0) max(23),
  endHour Integer required min(0) max(23),
  activationDate Instant required,
  deactivationDate Instant,
  createDate Instant required,
  lastChangedDate Instant
}

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

git version 2.28.0

node: v14.15.0

npm: 6.14.8

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192
