### ISSUE TITLE
Java code won't compile due to variable name conflict

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#13142]
##### **Overview of the issue**

```
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ jhcantcompile ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 76 source files to D:\01-pmohan\github\pmverma\jhcantcompile\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/01-pmohan/github/pmverma/jhcantcompile/src/main/java/com/mycompany/myapp/domain/MyFile.java:[80,37] variable myFileData is already defined in method setMyFileData(java.util.Set<com.mycompany.myapp.domain.MyFileData>)
[ERROR] /D:/01-pmohan/github/pmverma/jhcantcompile/src/main/java/com/mycompany/myapp/domain/MyFile.java:[83,32] variable myFileData is already defined in method setMyFileData(java.util.Set<com.mycompany.myapp.domain.MyFileData>)
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.998 s
[INFO] Finished at: 2020-11-25T16:12:39+06:30
[INFO] ------------------------------------------------------------------------
```
##### **Motivation for or Use Case**

JHipster should generate compilation-error free code.

##### **Reproduce the error**

Using main branch, on a fresh monolith app, generate following jdl file.
```
entity MyFile {
  name String
}
entity MyFileData {
  detail1 String
}
relationship OneToMany {
  MyFile{myFileData} to MyFileData{myFile required}
}

```

##### **Suggest a Fix**

I have extracted generated entity code.

```
@Entity
@Table(name = "my_file")
public class MyFile implements Serializable {
    @OneToMany(mappedBy = "myFile")
    @JsonIgnoreProperties(value = { "myFile" }, allowSetters = true)
    private Set<MyFileData> myFileData = new HashSet<>();

    public MyFile myFileData(Set<MyFileData> myFileData) {
        this.setMyFileData(myFileData);
        return this;
    }

    public void setMyFileData(Set<MyFileData> myFileData) { // ----1----
        if (this.myFileData != null) {
            this.myFileData.forEach(myFileData -> myFileData.setMyFile(null)); // ----2----
        }
        if (myFileData != null) {
            myFileData.forEach(myFileData -> myFileData.setMyFile(this)); // ----2----
        }
        this.myFileData = myFileData;
    }
}
```

- `----2----`  variable name `myFileData`  inside forEach conflicts with `----1----`
Having a single character variable seems simpler to me.
`myFileData.forEach(m -> m.setMyFile(this));`

https://github.com/jhipster/generator-jhipster/blob/main/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs#L624-L631

-  this code is only useful when using cascade value otherwise values will not be persisted in DB. Are we adding cascade property     in v7?

##### **JHipster Version(s)**

```
jhcantcompile@0.0.0 D:\01-pmohan\github\pmverma\jhcantcompile
`-- generator-jhipster@mainbranch

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": true,
    "baseName": "jhcantcompile",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "dtoSuffix": "DTO",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "reactive": false,
    "skipServer": false,
    "jhipsterVersion": "6.10.5",
    "entitySuffix": "",
    "entities": ["MyFile", "MyFileData"],
    "clientThemeVariant": "",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1606297306595,
    "lastLiquibaseTimestamp": 1606297426000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity MyFile {
  name String
}
entity MyFileData {
  detail1 String
}
relationship OneToMany {
  MyFile{myFileData} to MyFileData{myFile required}
}

dto MyFile, MyFileData with mapstruct
service MyFile, MyFileData with serviceImpl

</pre>
</details>

##### **Environment and Tools**

java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

git version 2.28.0.windows.1

node: v14.15.1

npm: 6.14.8

yeoman: 3.1.1
-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
> * this code is only useful when using cascade value otherwise values will not be persisted in DB.

We have back reference update at `add*` and `remove*` for a long time, at least jhipster 5.
IMO makes sense to add to setters too.

> Are we adding cascade property     in v7?

I have plans to add. Blocked by https://github.com/jhipster/generator-jhipster/pull/13044
