### ISSUE TITLE
PATCH method support for partial update

### ISSUE THREAD

**Issue by pnreddysvu** [jhipster/generator-jhipster#1315]
Will it be good to have partial update support of a resource through PATCH?

**Comment by jdubois** [comment]
I had this in a previous project, and clearly we should not use it.
Lots of proxy servers don't support it, which breaks the app for many clients. That was our biggest cause of bugs.

**Comment by pnreddysvu** [comment]
Ok. But is there any other alternative for partial resource update ?

**Comment by jdubois** [comment]
No, in that case you just use the PUT verb

If you want to use the PATCH verb, just do it : I'm just saying I had trouble with it, so we will not generate it by default, but that doesn't prevent you from using it, of course

**Comment by tagliola** [comment]
Wouldn't the X-HTTP-Method-Override header solve any proxy issues with
these methods? If that is supported by the stack, which I don't know.

**Comment by jdubois** [comment]
I have no idea what this header does...
The issue comes from proxy servers, we probably can't do anything about them.

**Comment by tagliola** [comment]
It overrides the HTTP method to whatever the header is set. If you have a
proxy which only allowed GET and POST and blocks the rest, you can perform
a POST with this header set to the action you actually want to have
performed, such as DELETE or PATCH. See
http://docs.spring.io/spring/docs/3.0.x/api/org/springframework/web/filter/HiddenHttpMethodFilter.html
for some Spring IO which could be used to get this working.

**Comment by cm325** [comment]
Patch support has increased, and with the above workaround, it would seem this could be supported everywhere. This seems like a big missing feature of a rest api-

**Comment by mukesh-mohan** [comment]
The Problem I faced with the PUT method instead of PATCH is, its expected to pass all the values for the model. If I pass only few changed fields, it was making the other non-passed fields as blank. So if we need to make a partial update I stringly recomment a PATCH method support. And if I made my custom changes, next time if I make any schema changes It overrides my existing changes.

**Comment by pnujwala** [comment]
Can this be re-opened?

**Comment by PierreBesson** [comment]
Hi @pnujwala,
Can you open a new issue with details. I think it's worth having this discussion again but our process is to create a new issue rather than reopening old ones.
