### ISSUE TITLE
Live reload refreshes, but not with new client code

### ISSUE THREAD

**Issue by verrol** [jhipster/generator-jhipster#1316]
Client live reload not updating content.
I have my app backend running, used 'mvn spring-boot:run'. Then i stared live reload with 'grunt serve'. A new tab is opened but any changes to the code only case a refresh of the same old content.

If it helps:

package.json:    "generator-jhipster": "2.6.0",
package.json:    "grunt": "0.4.5",
NPM: 2.0.0
Node: v0.11.14

**Comment by verrol** [comment]
I am on Mac OX 10.10.2 by the way.

**Comment by jdubois** [comment]
I'm using it all the time and it works... And I have basically the same setup as you!
Can you try with the sample app https://github.com/jhipster/jhipster-sample-app

**Comment by verrol** [comment]
Still the same issue using the sample app. I recorded a 1min video showing the problem here. So must my something with my setup. I am using nvm, but I don't think that is the problem. I can see the change notification on the console and the browser reloads, but just doesn't show the updated content. I have tried both Chrome and Firefox.

MKV file (smaller than mp4): http://gofile.me/2puq1/CtodsPpu

**Comment by jdubois** [comment]
OK, that's an easy one :-)
This is just because you are updating a translated text (see the translate directive?). So you see the translated text, which indeed did not change.
Try to the whole tag, or update the i18n json file, or modify the CSS...

I'm closing this because I know this is your issue. And I agree it's misleading!!!

**Comment by verrol** [comment]
Ah, that makes sense now. Translated text. :) duh
Thanks.
