### ISSUE TITLE
Tests next to the files they are testing in Vue

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#13179]
I open this issue according to https://github.com/jhipster/generator-jhipster/issues/13125#issuecomment-736645438.

In Angular part were tests moved next to the files they are testing after https://github.com/jhipster/generator-jhipster/issues/13125#issuecomment-735789694 and https://github.com/jhipster/generator-jhipster/issues/13125#issuecomment-735793814

In https://groups.google.com/g/jhipster-dev/c/wq6pe4VLPlE general opinion was that 3 front end frameworks should be in sync in tests location.

So should we move tests next to the files they are testing also in Vue part?

**Comment by pascalgrimaud** [comment]
I just tried `vue-cli` and the tests are in a specific folder:

```
* src
* tests
  * e2e (cypress)
  * unit (jest)
```

So with Vue, the tests are in specific folders, so I'd prefer to keep like this today.

**Comment by pascalgrimaud** [comment]
cc @sahbi-ktifa @hdurix @atomfrede @nonomoho @Falydoor : what do you think ? Your opinions are important here

**Comment by atomfrede** [comment]
Without your comment I would have said put it next to the file/component because that's what we do usually or inside a _test folder next to the components. In case vue cli is keeping them in dedicated folders I think we should stick to that so users coming from vue cli know the structure well.

**Comment by atomfrede** [comment]
Keep it open please.

**Comment by pascalgrimaud** [comment]
Are you sure @atomfrede ? :)
I think it can be closed, unless someone wants to discuss about this change

**Comment by pascalgrimaud** [comment]
Let's close this, as for now, we'll keep test in separate folders for Vue.js (following official vue-cli)
