### ISSUE TITLE
Tests next to the files they are testing in React

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#13178]
I open this issue according to https://github.com/jhipster/generator-jhipster/issues/13125#issuecomment-736645438.

In Angular part were tests moved next to the files they are testing after https://github.com/jhipster/generator-jhipster/issues/13125#issuecomment-735789694 and https://github.com/jhipster/generator-jhipster/issues/13125#issuecomment-735793814

In https://groups.google.com/g/jhipster-dev/c/wq6pe4VLPlE general opinion was that 3 front end frameworks should be in sync in tests location.

So should we move tests next to the files they are testing also in React part?

**Comment by pascalgrimaud** [comment]
@sendilkumarn @deepu105 : your opinions are important here, as you are the main leads on React part. What do you think ?

**Comment by sendilkumarn** [comment]
I am fine with that, Let us move the tests along with the components / files.

**Comment by deepu105** [comment]
As I expressed earlier if its moved for one, it must be moved for all 3 frameworks
