### ISSUE TITLE
Testing blueprints with skipClient as false is not possible

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#13180]
##### **Overview of the issue**
Testing a blueprint that extends app generator and test it with a scenario where skipClient is passed as false is not possible.

##### **Motivation for or Use Case**
If we want to skip some files when the skipClient is false (so when we don't want to generate the client) e.g `StaticResourcesWebConfiguration.java`. we can't test it through a Yeoman test, even if the behavior is correct when we launch the generator in a concret environment.

According to the files.js definition, the following should be generate if we have the client (when the skipClient is false) but my test failed.

```
        {
            condition: generator => !generator.skipClient && !generator.reactive,
            path: SERVER_MAIN_SRC_DIR,
            templates: [
                {
                    file: 'package/config/StaticResourcesWebConfiguration.java',
                    renameTo: generator => `${generator.javaDir}config/StaticResourcesWebConfiguration.java`,
                },
            ],
        },
```

##### **Reproduce the error**
Run this test file, https://github.com/avdev4j/generator-jhipster/blob/bug-test-bp/test/blueprint/app-blueprint-bug.spec.js
both tests should be green.

Note I test this file in particular but I can reproduce it with each file with the same condition.

##### **Related issues**
https://github.com/jhipster/generator-jhipster-quarkus/pull/87

##### **Suggest a Fix**
I would love ;).

##### **JHipster Version(s)**
From 6.10.1 to the main branch.

I think it exists for a long time before because I already met that.

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
I know @mshima you know well this part. I wonder if this can from a condition that is not well handles when we are running tests. But I'm not sure. 

Also I think, this part has been recently rework but I'm sure the bug was present before. I met it nearly 2 years ago.

**Comment by mshima** [comment]
Can you rebase against main and fix lint to let npm test to run?

It’s missing `packageFolder` at the assertion.
https://github.com/avdev4j/generator-jhipster/blob/d621b7c14f8e4668c9d0c29fcf2c2705c094e9ce/test/blueprint/app-blueprint-bug.spec.js#L135

`${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/config/StaticResourcesWebConfiguration.java`

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster-quarkus/pull/87#issuecomment-736643423 is a different issue.
Related to https://github.com/jhipster/generator-jhipster/blob/5c7de79dc7c386459ae4b96ccbf4085466708f9b/generators/generator-base.js#L2308 only testing positive value instead of not undefined.

**Comment by avdev4j** [comment]
> com/mycompany/myapp/config

You're right, I thought I found the way to reproduce the bug but not...

> only testing positive value instead of not undefined.

So the solution could be to test plainly the option 
`if(options.skipClient !== undefined)`

**Comment by mshima** [comment]
I think this error doesn't apply for jhipster 7, so I will tag as jhipster 6.
You should take a look at the severity of the bug, but IMO it's not worth to track it. jhipster 6 workflow is really confusing.
Config/Options handling was rewritten for jhipster 7.

**Comment by avdev4j** [comment]
because I can't reproduce it on main branch, I think you're right. Let's close this one since it's not really bloquant and I don't want to spend time for something like that. 

Let's wait to the v7 release and retest ;)

thanks @mshima
