### ISSUE TITLE
Bugs report for Openshift sub-generator - 'nc' command not found in crc container/pod

### ISSUE THREAD

**Issue by jh64** [jhipster/generator-jhipster#13183]
I have been trying to run the JHipster (6.10.4) generated apps to run on Openshift CodeReady/crc (4.6.1). I managed to workaround and fix a few issues/bugs in the yaml files generated by running the command "jhipster openshift". Now I can run the apps on crc successfully now, for both simple monolithic app, and microservices app using jhipster-registry.

My research result: the 'nc' command used in the yaml file is not supported by crc container/pod (RedHat Linux minimal OS package/container for openshift/crc), being deprecated, and replaced by 'ss'. I worked around the issue by removing the "pre:" section where the 'nc' command is used.

Suggestion: review and fix for the template/code in https://github.com/jhipster/generator-jhipster/tree/main/generators/openshift/templates/deployment.yml.ejs, or ask RedHat to put the 'nc' command back in the OS of openshift/crc container. I guess this is a regression caused by RedHat new OS package/container. It may be a bit tricky as jhipster sub-generator may have to check if 'nc' is supported, if not then use 'ss' which will need different command and parameter as bash script.

**Comment by jh64** [comment]
Looking further, the 'nc' command can be found on the master node, but not found on the running container/pod.

**Comment by jh64** [comment]
Looking further, the busybox docker image supports the 'nc' command. By using the busybox in initContainers to check the database service can fix the issue.
e.g.
          initContainers:
            - name: init-ds
              image: busybox:latest
              command:
                - '/bin/sh'
                - '-c'
                - |
                  while true
                  do
                    rt=$(nc -z -w 1 ${APPLICATION_NAME}-postgresqldb 80)
                    if [ $? -eq 0 ]; then
                      echo "DB is UP"
                      break
                    fi
                    echo "DB is not yet reachable;sleep for 10s before retry"
                    sleep 10
                  done

**Comment by jh64** [comment]
My code fix has been checked in to the branch I forked for issue #13184: https://github.com/jh64/generator-jhipster.git

**Comment by jh64** [comment]
I have published the pre-release v.10.6: https://github.com/jh64/generator-jhipster/releases

**Comment by pascalgrimaud** [comment]
As mentioned here https://github.com/jhipster/generator-jhipster/issues/12675#issuecomment-705350314
The OpenShift sub generator is not well maintained.

Feel free to open a pull request, to fix the main generator-jhipster, instead of doing the fix on your fork only :-)
Your contributions are really welcome!

**Comment by jh64** [comment]
I have done the pull/merge request: https://github.com/jhipster/generator-jhipster/pull/13223. Thanks!

**Comment by pascalgrimaud** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/13223
