### ISSUE TITLE
Bugs report for Openshift sub-generator - jhipster-registry.yml has 2 syntax issues

### ISSUE THREAD

**Issue by jh64** [jhipster/generator-jhipster#13184]
2 error messages:

1. Error from server (BadRequest): StatefulSet in version "v1" cannot be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.Replicas: readUint32: unexpected character:

This means: '.StatefulSetSpec.Replicas' is using string, should be integer.

2. spec.selector: Required value

This means: 'spec.selector' is missing.

Suggestion: review and fix for the code in https://github.com/jhipster/generator-jhipster/tree/main/generators/openshift/templates/registry/jhipster-registry.yml.ejs

I forked a branch onto my repository containing the code fix: https://github.com/jh64/generator-jhipster.git

See if the code fix can be reviewed, merged and built.

**Comment by pascalgrimaud** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/13223
