### ISSUE TITLE
Can't save 2 entities consecutively (React + manytomany)

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#13182]
##### **Overview of the issue**

Can't save 2 entities consecutively
Fails in the browser with 
```
Uncaught (in promise) TypeError: Cannot read property 'filter' of undefined
    at mapIdList (entity-utils.ts:23)
    at Object.saveEntity [as onSubmit] (foo-update.tsx:63)
    at AvForm._callee$ (AvForm.js:152)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.<computed> [as next] (runtime.js:114)
    at step (asyncToGenerator.js:17)
    at asyncToGenerator.js:28
```

##### **Reproduce the error**

Create a Foo, and immediately after, create a new one.
On 2nd save, it fails

##### **JHipster Version(s)**

```
clement-2@0.0.1-SNAPSHOT /Users/ctamisier/projects/clement2
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "clement2",
    "jhipsterVersion": "6.10.5",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1606926921414,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": [
      "en"
    ],
    "reactive": false,
    "entities": [
      "Foo",
      "Bar"
    ],
    "lastLiquibaseTimestamp": 1606927729000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Foo {
  code String
}
entity Bar {
  code String
}
relationship ManyToMany {
  Foo{bar} to Bar{foo}
}

paginate Foo, Bar with pagination
service Foo, Bar with serviceImpl

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

git version 2.29.2

node: v12.16.2

npm: 6.14.8

yeoman: 3.1.1

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.27.4, build 40524192

**Comment by qmonmert** [comment]
@ctamisier it seems to work on the main branch

**Comment by ctamisier** [comment]
Really, that's strange, I tried again from scratch from `main` branch, with given `.yo-rc.json` and `jdl`, and it still fails..

**Comment by ruddell** [comment]
I was able to reproduce it on the `main` branch with today's code.  I recorded a video showing that the many-to-many `bars` array is `undefined` after one or more saves (took me three attempts at first) https://www.loom.com/share/680530f58c4346e9913e10e40f766e0c

Changing the `foo.model.ts` default value helps but not sure that's the correct fix.

```diff
-export const defaultValue: Readonly<IFoo> = {};
+export const defaultValue: Readonly<IFoo> = { bars: [] };
```

**Comment by qmonmert** [comment]
@ctamisier I reproduce, you have to go fast to reproduce :)

**Comment by ctamisier** [comment]
I haven't check (I will), but if it's a matter of how fast we click on save, does the entity is persisted with all the filled fields.
now the undefined array is mapped to [], were the other fields undefined too ?

**Comment by ctamisier** [comment]
Actually the issue is that on the 2nd click on "new Foo", the state is not reset to default.
the `fooEntity` is still the "previous" one (if you console.log). I'd say there is something wrong in the state management.
You can see that the selected `bar` is also the one you just saved on `Foo`.
