### ISSUE TITLE
Comment générer les entities directement de la  base donnée  vers  mon projet jhipster

### ISSUE THREAD

**Issue by Hafyane** [jhipster/generator-jhipster#1319]
Bonjour ,
 je suis nouveaux en  JHipster ,j'ai  une base de donnée qui contient 19 tables sous Mysql ,j'ai cherché sur le Net sur comment générer les entities directement de la  base donnée  vers  mon projet jhipster j'ai pas trouvé de solution.

donc j’étais obligé de répété "yo jhipster:entity  namentity"  19 fois mais le probléme c'est que j'ai pas trouvé le type longblob   pour mon champ image

**Comment by jdubois** [comment]
Please go to [StackOverflow](http://stackoverflow.com/tags/jhipster) for this kind of question, which is not a bug (did you read our [guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) )?
And please write them in English: OK, that's not in the guidelines, but it's important that everybody can understand you.

Anyway, to answer your question: we don't generate entities from the database, JHipster works the other way around. If you want to generate your app from the database, I recommend you use [SpringFuse](http://www.springfuse.com/) cc @framiere @nromanetti
