### ISSUE TITLE
Spring boot 2.4 support

### ISSUE THREAD

**Issue by rburgst** [jhipster/generator-jhipster#13237]
##### **Overview of the feature request**

I know 2.3 support is coming with 7.0.0, but spring-boot 2.4 is already available.

##### **Motivation for or Use Case**

it would be good to support the latest technologies and spring features.

https://spring.io/blog/2020/11/12/spring-boot-2-4-0-available-now
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/11681

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
For your information, there is already a branch for that: https://github.com/jhipster/jhipster-bom/tree/spring-boot-2.4
But, it's a lot of work, because of different options: Microservices, Couchbase, UAA, Webflux, etc.
So it's not ready yet

**Comment by mraible** [comment]
I'd love to see this!

**Comment by mraible** [comment]
This work is being done in https://github.com/jhipster/generator-jhipster/pull/13551.
