### ISSUE TITLE
Add Apache Ignite as an option for cache management

### ISSUE THREAD

**Issue by SammyVimes** [jhipster/generator-jhipster#13234]
##### **Overview of the feature request**

I'd like to propose the addition of Apache Ignite as a Cache Manager. According to @jdubois, there is very little work to do it, as Ignite supports JCache. As an Apache Ignite contributor, I'll gladly implement this.

##### **Motivation for or Use Case**

Apache Ignite is a distributed in-memory computing platform. It works great as a cache for web application
Potentially it can also be added as an option for the database, as Ignite is indeed a database (it supports distributed SQL queries, snapshots, map-reduce, ACID transactions, and so on). Ignite has a lot of [proven use-cases](https://ignite.apache.org/use-cases/provenusecases.html) and is within one of the top-10 most active Apache Communities. 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
hi @SammyVimes 
thanks for this suggestion. My only concerne here is that we have a plenty of caching solution right now. Maybe we should thinking of removing the less used ones. But, it's probably another subject ;).

However, as @jdubois said It should be easy to add a new cache implementation with JCache. Basically add the dependency and update the CacheConfiguration Java class. A little reminder, we have to do that for both existing entities (User and Authority) and also each time we create a new entity through the entity generator.

I will be happy to do the review ;).

regards,

Anthony

**Comment by pascalgrimaud** [comment]
We can update the current CacheConfiguration, but we can create a new one:
- IgniteCacheConfiguration (in template) -> CacheConfiguration (in project)

So we won't have more additional conditions in this big big big file : https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs

**Comment by SammyVimes** [comment]
Yes, this seems reasonable!

**Comment by DanielFran** [comment]
@SammyVimes Are you still available to contribute with a PR?

**Comment by DanielFran** [comment]
Closing since no action for a while
