### ISSUE TITLE
Sonar Analysis for Angular: bad results

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#13232]
##### **Overview of the issue**

The current Sonar Analysis for Angular application is bad:
- 13 bugs
- 1 vulnerability
- 15 security hotspots
- coverage at 63.5%

##### **Motivation for or Use Case**

- you can have a look at https://sonarcloud.io/dashboard?id=jhipster-sample-application
- the spec files should not be analyzed by Sonar https://sonarcloud.io/component_measures?id=jhipster-sample-application&metric=coverage&selected=jhipster-sample-application%3Asrc%2Fmain%2Fwebapp%2Fapp%2Fentities%2Ftest-root%2Flabel%2Flist%2Flabel.component.spec.ts
- the coverage dropped from 82% to 63% : https://sonarcloud.io/project/activity?custom_metrics=coverage&graph=custom&id=jhipster-sample-application

##### **Related issues**

Probably related to https://github.com/jhipster/generator-jhipster/pull/13171

##### **JHipster Version(s)**

current main branch

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
I made #13233 which says to SonarCloud that `*.spec.ts` files are test files in Angular app and this should take them away from analyze and coverage.
This should fix coverage and most security hotspots.
Bugs, vulnerability and some security hotspots come from Java code

**Comment by pascalgrimaud** [comment]
thanks a lot @kaidohallik for fixing this so fast ! let's merge it once the CI passed

**Comment by avdev4j** [comment]
I supposed this is fixed through @kaidohallik PRs. I close the issue ;)

**Comment by pascalgrimaud** [comment]
Not finished yet, @avdev4j as we still have :
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&resolved=false&types=BUG
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&resolved=false&types=VULNERABILITY

I'm removing the theme Angular, as the todo list is on Java part now

**Comment by pascalgrimaud** [comment]
Closing this in favor of https://github.com/jhipster/generator-jhipster/issues/13291
