### ISSUE TITLE
Can not using primitive type in entity json.

### ISSUE THREAD

**Issue by Mavlarn** [jhipster/generator-jhipster#1324]
I am using entity json in .jhipster to auto generate the entity files. I found that if I use primitive type like int, long, the entity xml file can not be created properly. I found the template code:
```
CREATE TABLE IF NOT EXISTS <%= entityInstance %> (
    id uuid,<% for (fieldId in fields) { %><% if (fields[fieldId].fieldType == 'UUID') { %>
    <%= fields[fieldId].fieldName %> uuid,<% } else if (fields[fieldId].fieldType == 'TimeUUID') { %>
    <%= fields[fieldId].fieldName %> timeuuid,<% } else if (fields[fieldId].fieldType == 'String') { %>
    <%= fields[fieldId].fieldName %> text,<% } else if (fields[fieldId].fieldType == 'Integer') { %>
    <%= fields[fieldId].fieldName %> int,<% } else if (fields[fieldId].fieldType == 'Long') { %>
    <%= fields[fieldId].fieldName %> bigint,<% } else if (fields[fieldId].fieldType == 'BigDecimal') { %>
    <%= fields[fieldId].fieldName %> decimal,<% } else if (fields[fieldId].fieldType == 'Date') { %>
    <%= fields[fieldId].fieldName %> timestamp,<% } else if (fields[fieldId].fieldType == 'Boolean') { %>
    <%= fields[fieldId].fieldName %> boolean,<% } } %>
    PRIMARY KEY(id)
);
```

So it can only use Integer, Long type for filed.

I know sometime it will be better to use Object type instead of primitive type. But sometime, I really want to use primitive type for some performance and less memory for large amount of data.

So I am asking, is it possible to provide the support for primitive type for entity? Thanks.

**Comment by jdubois** [comment]
I see you are using Cassandra: the driver is normally converting those to primitive types. I agree it's probably better to have primitives for performance reasons, but this is such a small difference that it's probably not worth it. Besides, having objects give us some other advantages, so I'd stick with objects for the moment.

If you really want primitives, and as I see you are modifying the JSON files:

- Don't modify the JSON files to give them a configuration that does not exist: it's not going to work
- Just modify the resulting Java files: change the Integer to int directly in your domain object, it will work

**Comment by Mavlarn** [comment]
OK, very reasonable. Thanks for your great job!
