### ISSUE TITLE
ConstraintViolation when fieldValidateRulesMin > 0

### ISSUE THREAD

**Issue by jenslofgren** [jhipster/generator-jhipster#1326]
If I generate the following entity:
```
yo  jhipster:entity longcontrainttest
The entity longcontrainttest is being created.
Generating field #1
? Do you want to add a field to your entity? Yes
? What is the name of your field? longTest
? What is the type of your field? Long
? Do you want to add validation rules to your field? Yes
? Which validation rules do you want to add? Minimum size
? What is the minimum size of your field? 3
=================Longcontrainttest=================
longTest (Long) min='3' 
Generating field #2
? Do you want to add a field to your entity? No
=================Longcontrainttest=================
longTest (Long) min='3' 
? Do you want pagination on your entity? No
```

Summary: Long field with validation rule->min=3

The test will fail with:
javax.validation.ConstraintViolationException

Reason seems to be that the following fields in the Test is not adjusted to min=3:

```
private static final Long DEFAULT_LONG_TEST = 0L;
private static final Long UPDATED_LONG_TEST = 1L;
```

**Comment by jdubois** [comment]
Yes this is a limitation of the generator, as we don't generate tests related to your validation rules (I think I wrote it in the documentation, but I agree it's not very clear).

It's part me being lazy, as we can probably generate some of them, but also part of this being impossible to generate: if you validate with a regexp pattern, for example, we can't automatically generate something that follows that pattern.

I'll check this tomorrow, but of course I can only generate the simple validation rules.

**Comment by jdubois** [comment]
I've made it much, much better -> I will close this ticket with my commit

Of course this isn't perfect, because I don't think this can be perfectly generated, but yet this will solve most of the issues.
