### ISSUE TITLE
Allow customization of the ID field type for User entity

### ISSUE THREAD

**Issue by MarlonLuan** [jhipster/generator-jhipster#13278]
##### **Overview of the feature request**

Adds support to custom ids:

```
entity User {
  id UUID
}
```

##### **Motivation for or Use Case**

Now with  PR #13258 it is possible to customize the entities ID, it would be interesting to be able to also change the user entity, to maintain consistency and standardization

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
As said in other pull request, `Relationships are not complete yet`
I think it should be done first, before this ticket

**Comment by pascalgrimaud** [comment]
after thinking about it, it will require a lot of work to achieve it, as there are impacts on all part of generator

**Comment by mshima** [comment]
I don't think it will require too many changes.
- relationship should be done.
- frontends should be id type independent.

I am finishing a PR adding support to `--pk-type` option that will allow to use UUID by default.

**Comment by mshima** [comment]
Missing:
- jdl support
- add ci test
- test with react and vue

For jdl support I'm will try to implement as pkType option.
Customizing User entity is more complicated.

**Comment by MathieuAA** [comment]
Too bad I'm only seeing this now but having an option is a semantically bad idea: it would mean that every PK should be of type <INSERT_VALUE_HERE>. What can easily be done is:
  - not filter out `id` fields (like `id`, `thingId`, or `idThing`),
  - accept the passed type as the PK type,
  - have an attribute in the dumped JSON such as `primaryKey`: "<FIELD_NAME>"

Of course, that would mean all the above and make the JDL export accept this change.

**Comment by mshima** [comment]
@MathieuAA thats exactly what have been done.
The missing part is the User:
- First option:
```
entity User {
  id UUID
}
```
  - Requires to don’t filter User entity for non skipUserManagement.
  - Requires the user to override the default id  for every entity
 
 - Second option:
 ```
application { config  {
  pkType UUID
} }
```
  - Ugglier
  - The id have a implicit customized type.

We should decide the approach to take for it.

**Comment by MathieuAA** [comment]
> Requires to don’t filter User entity for non skipUserManagement.

This can be convention instead of a verbose configuration BTW: if such an entity exists, the option is automatically set (with a log informing the user).

> Requires the user to override the default id for every entity

Not necessarily: if a field looking like `id` is found, not just for the `User` entity, then this can be set locally to an entity. The default being what JHipster advocates and uses.

> Requires the user to override the default id for every entity

same

**Comment by mshima** [comment]
I mean if the application wants to use a custom type for the entire application.

**Comment by MathieuAA** [comment]
> I mean if the application wants to use a custom type for the entire application.

Oh okay. It makes sense

**Comment by mshima** [comment]
@MathieuAA I will let you do the jdl part the generator part is at https://github.com/jhipster/generator-jhipster/pull/13990.

User definition must be exported when present in the jdl.
Should not be exported when added for relationships:
https://github.com/jhipster/generator-jhipster/blob/0c513bf224bb516180ef2086dd3ce9855a77b772/jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.js#L173-L181

Preferably It should be exported only with name, fields, relationships and annotations.
Fields, relationships and annotations could be useful for blueprints.

A full example of custom ids supported syntax is at https://github.com/jhipster/generator-jhipster/blob/main/test-integration/samples/jdl-entities/custom-id.jdl.

**Comment by MathieuAA** [comment]
@mshima roger that, I'll look into it later today.

**Comment by MathieuAA** [comment]
> Preferably It should be exported only with name, fields, relationships and annotations.

So... name, fields, relationships and options (annotation = options). Which means pretty much everything right? :)

**Comment by mshima** [comment]
> Which means pretty much everything right? :)

DTO, filter, entityTableName, everything else in the root of the definition should be omitted.
Right now it would be ignored, but we could just use it as start point of the User entity.

Eg:
- entityTableName should be prefixed with `jhi_`.
- DTO is somewhat always true.
- There is no difference for filter value.
The safe implementation is to omit.

**Comment by MathieuAA** [comment]
I'm gonna try something.

**Comment by MathieuAA** [comment]
@mshima I'm gonna only export the User.json file if there's a custom ID, and not use the sample from the repo.

The User entity should look like this:
```json
{
          applications: '*',
          changelogDate: 'WHATEVER',
          dto: 'mapstruct',
          embedded: false,
          entityTableName: 'jhi_user',
          fields: [
            {
              fieldName: 'id',
              fieldType: 'UUID',
              fieldValidateRules: ['required', 'unique'],
            }
          ],
          fluentMethods: true,
          javadoc: undefined,
          jpaMetamodelFiltering: false,
          name: 'User',
          pagination: 'no',
          readOnly: false,
          relationships: [],
          service: 'no',
        }
```

I don't see the need for anything more here (like more fields, relationships and options) => that would be the `skipUserManagement` option's role.

If such needs arise, we will update the code if need be, but for the meantime: YAGNI.

**Comment by mshima** [comment]
> edit: a better solution would be to have "overriding JSON entities" for such needs. Such JSON files would contain properties (like fields, etc.) that could be merged with the default props before the code generation. WDYT? That would cover this issue, and make other changes like that be much cheaper to make.

Not sure what do you mean by "overriding JSON entities".

If I understand correctly, it's a feature that don't export default configurations. It contains only configurations defined in the jdl so it's is safe to be merged.
If I am correct, I like the idea.

**Comment by MathieuAA** [comment]
That's the idea. Sorry, I had this idea at 4/5 in the morning, I understand I can be quite vague early in the morning ;)

The point is not to export something complete, but only overriding props. And we could do it for, well, pretty much anything we want

**Comment by mshima** [comment]
That's great.
The generator is already using jdl defaults for applications, so it's applying twice.

**Comment by mshima** [comment]
Let's keep this one open.
We should fix this, at least for v8.
