### ISSUE TITLE
Bugs report for Openshift sub-generator - No route to host (Host unreachable)

### ISSUE THREAD

**Issue by jh64** [jhipster/generator-jhipster#13281]
I have been trying to run the JHipster (6.10.5) generated apps (**excluding the JHipster Registry**) to run on Openshift CodeReady/crc (4.6.1). I managed to fix a few bugs in the yaml files generated by running the command "jhipster openshift".

Error from the **gateway** app:
I/O error on GET request for "http://myapp:80/management/health": No route to host (Host unreachable); nested exception is java.net.NoRouteToHostException: No route to host (Host unreachable)

I will be fixing: https://github.com/jhipster/generator-jhipster/tree/main/generators/openshift/templates/deployment.yml.ejs

I changed the yml file - fixed the port for the service spec - making them the same as the k8s one.
Note: RouteDetectorFilter.java is generated only in the case that the Jhipster Registry is excluded . And it has port 80 hard coded for searching/detecting the microservice apps' service.

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/generator-jhipster/pull/13283
