### ISSUE TITLE
Bugs report for Openshift sub-generator - Invalid JWT token

### ISSUE THREAD

**Issue by jh64** [jhipster/generator-jhipster#13282]
After fixing the issue #13281, my investigation progressed to this issue:
Error from the microservice app (routed through the gateway app): "Invalid JWT token."

I fixed it by adding the missing JWT. I used the same one (JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET) from the file https://github.com/jhipster/generator-jhipster/blob/main/generators/openshift/templates/registry/jhipster-registry.yml.ejs.

I will be fixing: https://github.com/jhipster/generator-jhipster/tree/main/generators/openshift/templates/deployment.yml.ejs

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/generator-jhipster/pull/13283
