### ISSUE TITLE
Post generation handler

### ISSUE THREAD

**Issue by towith** [jhipster/generator-jhipster#13309]
# Feature request: Post generation handler
I wonder if there are some post code generation handlers to modify generated code , that would be useful and increase flexibility, sometimes , for example I want to modify entity generated code to extends a common super class (Not managed by code generation) , and some time I want to add an annotation to  the generated code class field, these are enhanced `decoration` approach. 

> Of cause , this can be do by manual,  or change the `.ejs` template code , in `node_modules` folder, but if there are handlers , i think would be more convenient , and more `manageable` (by version control)

**Comment by pascalgrimaud** [comment]
You should have a look at:
- module: https://www.jhipster.tech/modules/creating-a-module/
- blueprint: https://www.jhipster.tech/modules/official-blueprints/

**Comment by towith** [comment]
@pascalgrimaud yes, `module` and `blueprint` is similar to what I mean, I make this issue closed , thanks for your reply.
