### ISSUE TITLE
Duplicate class found in the file 

### ISSUE THREAD

**Issue by 8debug** [jhipster/generator-jhipster#13304]
Microsoft Windows [版本 10.0.17134.1246]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\DELL\Desktop\myapp>jhipster info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
myapp@0.0.1-SNAPSHOT C:\Users\DELL\Desktop\myapp
`-- generator-jhipster@6.10.5

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "myapp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "yarn",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1608098851915,
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}
entity Entry {
  title String required,
  content TextBlob required,
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User,
  Entry{blog(name)} to Blog
}
relationship ManyToMany {
  Entry{tag(name)} to Tag{entry}
}

paginate Entry, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.20.1.windows.1

node: v14.15.1

npm: 6.14.8

yarn: 1.22.10

Docker version 20.10.0, build 7287ab3

docker-compose version 1.27.4, build 40524192

identical .jhipster\Blog.json
identical .jhipster\Entry.json
identical .jhipster\Tag.json
INFO! Congratulations, JHipster execution is complete!

##### **Overview of the issue**

Follow the video tutorial to create a project using the command line (use gradle). Can successfully run this project under the command line, but run project failed in IntelliJ IDEA .

![image](https://user-images.githubusercontent.com/3394927/102334449-a4c0b080-3fc9-11eb-9078-af12216a38b1.png)

##### **Motivation for or Use Case**

Successfully start the project through the button in the IntelliJ IDEA

**Comment by 8debug** [comment]
Has anyone encountered this problem?

**Comment by 8debug** [comment]
Windows10

I found a solution：

step1 Open the command line
step2 Enter the project root directory and `gradlew clean`
step3 `npm install -g rimraf`
step4 `rimraf node_modules`
step5 `npm install`
step6 `gradlew build`
step7 `gradlew`

**Comment by 8debug** [comment]
The problem is still using IntelliJ IDEA

**Comment by 8debug** [comment]
The problem is still using IntelliJ IDEA

**Comment by pascalgrimaud** [comment]
I don't know what is exactly your problem, but it seems related to IntelliJ
Can you have a look at this comment ? It's related to mapstruct
- https://github.com/jhipster/generator-jhipster/issues/12967#issuecomment-737405698
- see https://youtrack.jetbrains.com/issue/IDEA-200481 too

So try to upgrade mapstruct to 1.4.1

**Comment by 8debug** [comment]
> I don't know what is exactly your problem, but it seems related to IntelliJ
> Can you have a look at this comment ? It's related to mapstruct
> 
> * [#12967 (comment)](https://github.com/jhipster/generator-jhipster/issues/12967#issuecomment-737405698)
> * see https://youtrack.jetbrains.com/issue/IDEA-200481 too
> 
> So try to upgrade mapstruct to 1.4.1

I try, but it is not work

**Comment by Tcharl** [comment]
I don't have the issue when using Gradle and IJ.
I also don't have the 'generated' folder.

I would check if the 'annotation processors' is well configured in your IJ preference.
Should be enabled, but the 'obtain processors from the classpath' radio should be selected
