### ISSUE TITLE
If using import-jdl for importing entities only then Prettier is not launched

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#13308]
##### **Overview of the issue**

If running `jhipster import-jdl entities.jdl` where `entities.jdl` contains only entities then generated result is not prettified.

For example `entities.jdl` with this content:
```
entity MyEntity {
    name String
}
```

Tested with the current main branch.

##### **Motivation for or Use Case**

Generation result should be formatted by Prettier also if importing only entities with `import-jdl`.

##### **Reproduce the error**

Run `jhipster import-jdl entities.jdl` where `entities.jdl` contains only entities.

##### **JHipster Version(s)**

Current main branch.

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "6.10.5",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "withGeneratedFlag": false,
    "jhiPrefix": "doublePrefix",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [
      "protractor"
    ],
    "pages": [],
    "creationTimestamp": 1604860694412,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": [
      "en",
      "et",
      "ru"
    ],
    "lastLiquibaseTimestamp": 1608128870000,
    "withAdminUi": true,
    "embeddableLaunchScript": false
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

git version 2.29.2.windows.3

node: v14.15.1

npm: 6.14.9

yeoman: 3.1.1

Docker version 20.10.0, build 7287ab3

docker-compose version 1.27.4, build 40524192

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Should be fixed by https://github.com/jhipster/generator-jhipster/pull/12711.
