### ISSUE TITLE
ng-jhipster: alert-error should pick up error detail

### ISSUE THREAD

**Issue by sunyuyangg555** [jhipster/generator-jhipster#13316]
##### **Overview of the issue**

alert-error should pick up error detail

##### **Motivation for or Use Case**

When I throw RuntimeException from server with detail message, the``` <jhi-alert-error/>``` should pick up the message.

##### **Reproduce the error**
in server
```
@Transactional
    public void importAssets(List<Asset> assets) {
        if (assets.size() == 0) {
            throw new RuntimeException("this is the detail error message!");
        }
}
```
and the http error message is 
```
{
  "type" : "https://www.jhipster.tech/problem/problem-with-message",
  "title" : "Internal Server Error",
  "status" : 500,
  "detail" : "this is the detail error message!",
  "path" : "/api/assets/import",
  "message" : "error.http.500"
}
```
in clien, only show Internal server error message!

##### **Suggest a Fix**

in alert-error.component.ts shoud pick up detail message:
```
        default:
            if (httpErrorResponse.error !== '' && httpErrorResponse.error.message) {
              this.addErrorAlert(httpErrorResponse.error.detail ?? httpErrorResponse.error.message);
            } else {
              this.addErrorAlert(httpErrorResponse.error);
            }
```
##### **JHipster Version(s)**

JHipster 6.10.3
ng-jhipster 0.15.0

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by swarajsaaj** [comment]
I checked this on latest build 
jhipster version7.0.0-beta.0

See the screenshot below, instead of showing "Test error message", UI shows "error.http.500". From controller an `IllegalArgumentException` was thrown with the message.

![image](https://user-images.githubusercontent.com/6285049/103030369-ab2ec980-4581-11eb-8ea6-c96e4955d916.png)

I agree, this should be fixed to show meaningful messages.

**Comment by swarajsaaj** [comment]
I can provide PR for fixing both 4xx and non-4xx statuses.
