### ISSUE TITLE
[Cypress] Replace all cy.server() and cy.route() by cy.intercept()

### ISSUE THREAD

**Issue by nassimerrahoui** [jhipster/generator-jhipster#13345]
##### **Overview of the feature request**

Replace all cy.server() and cy.route() by cy.intercept().
(see: https://docs.cypress.io/api/commands/intercept.html#Comparison-to-cy-route)

##### **Motivation for or Use Case**

In a future release, cypress support for cy.server() and cy.route() will be moved to a plugin.
They encourage to use cy.intercept() instead.
(see: https://docs.cypress.io/guides/references/changelog.html#6-0-0)

##### **Related issues or PR**

N/A

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@jdubois @pascalgrimaud I claim my money :) https://opencollective.com/generator-jhipster/expenses/31375

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by qmonmert** [comment]
thanks @pascalgrimaud
