### ISSUE TITLE
may project lombok fit here?

### ISSUE THREAD

**Issue by rblazquez** [jhipster/generator-jhipster#1334]
Have you consider include project lombok to reduce the amount of boilerplate code?

I know jHipster claims to use a small set of dependencies and i personally agree with this idea, but in my experience the reduction of boilerplate code achieves a much more clean code, and less maintenance effort.

Also project lombok is small set of annotations that are also optional, is a stable project and integrates very well with IDEs.

**Comment by jdubois** [comment]
Duplicate of #398
