### ISSUE TITLE
When using `jhipster entity NewEntity` all the entities are re-generated

### ISSUE THREAD

**Issue by ecostanzi** [jhipster/generator-jhipster#13365]
##### **Overview of the issue**

When creating a **single** entity using command `jhipster entity MyEntity`, at the end of the prompt phase i can see that the generator re-generates **all** the entities that are already configured in the `.jhipster` directory.

I admit I'm not aware of all the changes that have been discussed for the new release but I'm not sure this is the expected behavior.

##### **Motivation for or Use Case**

`jhipster entity` should affect only the files related to the single entity. As a developer, when generating or re-generating a single entity, I don't want to worry about changes that may occur to other entities.

This impacts also a blueprint I'm porting to the new version. It seems that the entity generator of the blueprint is invoked for all the entities.

##### **Reproduce the error**

Create the first entity `jhipster entity Blog`.
Create the second entity `jhipster entity Comment`

See that both Blog and Comment entity are generated.
```bash
...
? Do you want pagination and sorting on your entity? No
info Creating changelog for entities Blog,Comment
Everything is configured, generating the entity...
Found the /home/admin/jhtest/.jhipster/Blog.json configuration file, entity can be automatically generated!
```

##### **Suggest a Fix**

No suggestions so far.

##### **JHipster Version(s)**

7.0.0-beta.0

##### **JHipster configuration**

admin@vps743604:~/jhtest$ jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhtest@0.0.1-SNAPSHOT /home/admin/jhtest
└── generator-jhipster@7.0.0-beta.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "jhtest",
    "jhipsterVersion": "7.0.0-beta.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1608713230421,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": ["enableSwaggerCodegen:true"],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1608713664000,
    "entities": ["Blog", "Comment"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  name String
}
entity Comment {
  name String
}

</pre>
</details>

##### **Environment and Tools**

git version 2.17.1

node: v12.18.4

npm: 6.14.6

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```json
{
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    }
  ],
  "relationships": [],
  "service": "no",
  "readOnly": false,
  "pagination": "no",
  "name": "Blog",
  "changelogDate": "20201223085159"
}
```
```json
{
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    }
  ],
  "relationships": [],
  "service": "no",
  "readOnly": false,
  "pagination": "no",
  "name": "Comment",
  "changelogDate": "20201223085424"
}
```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
At jhipster 7 when generating one entity, data from related entities are required.
Example: 
```jdl
entity Foo {}
entity Bar {
   name String
}
relationship OneToOne {
   Foo{bar (name)} Bar
}
```
Foo has relationship with Bar and defines `name` as select labels. Bar finds the `name` reference generates a custom dto mapping for `name`.

So
- JHipster 7 requires to process related entities.
- It's possible to skip writing entities other than the target one, but they may be outdated.

**Comment by ecostanzi** [comment]
> JHipster 7 requires to process related entities.

I understand, but in this case the two entities are not related to each other.

> It's possible to skip writing entities other than the target one, but they may be outdated.

How can it be done?

**Comment by pascalgrimaud** [comment]
For me, the current `jhipster entity <entity name>` is broken.

To reproduce the issue:
- `git clone https://github.com/jhipster/jhipster-sample-app-microservice`
- `cd jhipster-sample-app-microservice`
- `npm ci`
- `jhipster entity Beer`

```
➜ jhipster entity Beer  
INFO! Using JHipster version installed locally in current project's node_modules

Found the /home/pgrimaud/tmp/jhipster-sample-app-microservice/.jhipster/Beer.json configuration file, entity can be automatically generated!

? Do you want to update the entity? This will replace the existing files for this entity, all your custom code will be overwritten (Use arrow keys)
❯ Yes, re generate the entity 
  Yes, add more fields and relationships 
  Yes, remove fields and relationships 
  No, exit
```

**Comment by ecostanzi** [comment]
@pascalgrimaud are you sure? The first time I execute `jhipster entiy Beer` it works (there's no `.jhipster/Beer.json` in the workspace). The second time it regenerates both `BankAccount` and `Beer` even if they are not related.

**Comment by pascalgrimaud** [comment]
@ecostanzi : not for microservices
