### ISSUE TITLE
Error when access to an entity with undefined localdate

### ISSUE THREAD

**Issue by luc-clement** [jhipster/generator-jhipster#1336]
Hi, 

I'm currently working on a project using Jhipster 2.6.0 and i had an error after trying to access to the edit or details page of an entity that was saved with an undefined date field. 

I fixed this in the file entity.service.js by remplacing the lines (transformResponse of the method GET) : 
<pre>
var myDateFrom = data.myDate.split("-");
data.myDate = new Date(new Date(myDateFrom[0], myDateFrom[1] - 1, myDateFrom[2]));
</pre>

With the lines : 
<pre>
if (data.myDate != null) {
    var myDateFrom = data.myDate.split("-");
    data.myDate = new Date(new Date(myDateFrom[0], myDateFrom[1] - 1, myDateFrom[2]));
}
</pre>

**Comment by jdubois** [comment]
Duplicate from #1245
(But with better explanation!)
