### ISSUE TITLE
A microservices architecture with Vue doesn't have translations in alerts

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13384]
##### **Overview of the issue**

If you create a JHipster microservices architecture with Vue, the alerts in the UI aren't translated.

<img width="1025" alt="Screen Shot 2020-12-29 at 11 47 49 AM" src="https://user-images.githubusercontent.com/17892/103306874-dffcaf80-49cb-11eb-8986-69986bfd6724.png">

It looks like there's a missing translation for `health.indicator.r2dbc` in Administration > Health too.

<img width="1182" alt="Screen Shot 2020-12-29 at 11 50 06 AM" src="https://user-images.githubusercontent.com/17892/103306952-15a19880-49cc-11eb-8bf1-2e9262bff1e8.png">

##### **Motivation for or Use Case**

I'd like to show how JHipster works with microservices and Vue. It looks bad when keys aren't translated. 

##### **Reproduce the error**

Create a microservices architecture with JHipster 7 beta 0 using the following JDL:

```
application {
  config {
    baseName gateway
    reactive true
    clientFramework vue
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    databaseType neo4j
    devDatabaseType neo4j
    prodDatabaseType neo4j
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store
    reactive true
    packageName com.okta.developer.store
    applicationType microservice
    authenticationType oauth2
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    searchEngine elasticsearch
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog
```

Start all the services using Docker Compose and Maven:

```
cd gateway
docker-compose -f src/main/docker/keycloak.yml up -d #jhkeycloakup
# wait 20 seconds for Keycloak to start up
docker-compose -f src/main/docker/jhipster-registry.yml up -d #jhregistryup
docker-compose -f src/main/docker/postgresql.yml up -d #jhpostgresqlup
./mvnw -Pprod
```

Open a new terminal to start the blog app:
```
cd ../blog
docker-compose -f src/main/docker/neo4j.yml up -d #jhneo4jup
./mvnw 
```

Open a new terminal to start the store app:
```
cd ../store
docker-compose -f src/main/docker/mongodb.yml up -d #jhmongoup
docker-compose -f src/main/docker/elasticsearch.yml up -d #jhesup
./mvnw
```

Open `http://localhost:8080`, log in, and add entities. 

##### **JHipster Version(s)**

7.0.0-beta.0

**Comment by mraible** [comment]
When running Cypress tests, I also noticed that there's a flash of untranslated content before the translation happens. I don't recall seeing this with Angular or React.

**Comment by swarajsaaj** [comment]
The toast message here is not being translated because of incorrect key here, instead of `gatewayApp.storeProduct.created`, it should be `storeApp.storeProduct.created`. with prefix as `microserviceAppName` instead of `frontendAppName` in case of microservices

**Comment by pascalgrimaud** [comment]
Would you to provide a pull request to fix it plz @swarajsaaj ?

**Comment by swarajsaaj** [comment]
Yes @pascalgrimaud , I would provide a PR soon.

**Comment by swarajsaaj** [comment]
@atomfrede #13394 also needs to be merged for adding one missing translation.

**Comment by atomfrede** [comment]
Done.

**Comment by swarajsaaj** [comment]
Sure @atomfrede , but that PR still seems open :)
