### ISSUE TITLE
bidirectional ManyToOne relations causing error

### ISSUE THREAD

**Issue by Guzzi** [jhipster/generator-jhipster#13396]
##### **Overview of the issue**

As per documentytion, bidirectional ManyToOne relations should be possible - end they worked in older JH version.
See documentation here ->https://www.jhipster.tech/managing-relationships/#a-bidirectional-many-to-one-relationship
The mentioned example causes an error when generating code with jhipster import-jdl xxx.jdl and recommends to use OneToMany relation instead.

##### **Motivation for or Use Case**

ManyToOne entity relations should work as documented (and I can't generate older jdls with current jHipster anymore)

##### **Reproduce the error**

Use example jdl from ManyToOne documentation with jhipster import-jdl xxx.jdl from here: https://www.jhipster.tech/managing-relationships/#a-bidirectional-many-to-one-relationship

##### **Related issues**

didn't find one.

##### **JHipster Version(s)**

6.10.5

##### **Browsers and Operating System**

win10/cmd line

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ecostanzi** [comment]
The documentation seems to be wrong. Probably it worked with the old versions of the jdl.

The error is: Error during import-jdl: In the Many-to-One relationship from Car to Owner, only unidirectionality is supported, you should either create a bidirectional One-to-Many relationship or remove the injected field in the destination entity instead.

As suggested, you can remove the "injected field in the destination entity":
```
entity Owner
entity Car

relationship ManyToOne {
  Car{owner} to Owner
}
```

**Comment by ecostanzi** [comment]
I was about to remove it but I noticed that it has been added in [this commit](https://github.com/jhipster/jhipster.github.io/commit/58853b18406013b0e4a63ff33c278edbb45e08ca) few weeks ago. Maybe @yelhouti can clarify this.

**Comment by yelhouti** [comment]
I think this will be released with 7.X, I guess it was merged too early.

**Comment by yelhouti** [comment]
Indeed, released in 7.0.0.beta https://github.com/jhipster/generator-jhipster/pull/13131

**Comment by ecostanzi** [comment]
@yelhouti  thanks, I missed it. 

@Guzzi as long as you stick with version 6.10.5, remove the injected field `{car}` from the destination entity. Will that be enough to solve your problem?

**Comment by yelhouti** [comment]
@ecostanzi no worries, good luck

**Comment by Guzzi** [comment]
@ecostanzi unfortunately removing the injected field does not help - yes, the generator works and runs without error, but the generated code is missing the methods for B to A direction, that we already use and is missing now - so I would have to manually add all this code.
As far as I understand, it is only a generator issue, so wouldn't it be the easiest to backport to removal of this check to 6.x? I assume 7.x beta is still too much in progress to use it now... 
Or could/should I use 7.x generated code (that includes bidirectional generation) and merge it into 6.10 code?
I tried using OneToMany instead of ManyToOne (reversing the jdl relation) - this allows bidirectional relation, but I fear that this might change persistence layer, which would be fatal (huge existing databases...)
Any help or hints are appreciated :-)

**Comment by ecostanzi** [comment]
I'm not sure about the backporting, but I strongly suggest not to mix the files generated by two different versions of jhipster.

> I tried using OneToMany instead of ManyToOne (reversing the jdl relation) - this allows bidirectional relation, but I fear that this might change persistence layer, which would be fatal (huge existing databases...)

What are you worried about? You seem to need is a `car` table with a foreign key `car.person_id` --> `person.id`. Using OneToMany in the jdl should be enough.

```
relationship OneToMany {
  Person{car} to Car{owner}
}
```

**Comment by ecostanzi** [comment]
@Guzzi any feedback? If `OneToMany` worked for you I think we should close this issue.

**Comment by Guzzi** [comment]
@ecostanzi, @pascalgrimaud - I think this one can be closed, as with 7.x bidirectional ManyToOne are possible again and there won't be a backport to 6.x anyway.

**Comment by pascalgrimaud** [comment]
Thanks @Guzzi :)
