### ISSUE TITLE
Release 6.10.5 not working with R2DBC since it's not experimental anymore and the pom moved

### ISSUE THREAD

**Issue by digital-thinking** [jhipster/generator-jhipster#13391]
In latest version Release 6.10.5 JHipster still used the experimental artifact of spring boot (spring_boot_starter_data_r2dbc_version), which is not experimental anymore and therefore moved to the official spring boot groupid in the maven repository. From 
`"org.springframework.boot.experimental:spring-boot-starter-data-r2dbc}"`
to 
`"org.springframework.boot:spring-boot-starter-data-r2dbc" `

Unfortunately updaring the groupid is not enough, as jhipster is using spring boot 2.2.7 and spring-boot-starter-data-r2dbc is only available since 2.3. 

The solution for me is to use the beta release of jhipster 7 (Spring boot 2.3).
I guess if someone has the old pom (spring-boot-starter-data-r2dbc:0.1.0.M3) available it would be great for others to make it available here, so they can simply add it to their local repository.

**Comment by pascalgrimaud** [comment]
Yes, you should use beta release of JHipster 7, as for 6.10.5 the support was not good enough

**Comment by mraible** [comment]
Can this be closed now?
