### ISSUE TITLE
Generating using React with Jhipster v6.10.5 fails on axios 0.18.0 transient dependency

### ISSUE THREAD

**Issue by Strat1987** [jhipster/generator-jhipster#13407]
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "Downloads",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1609755407496,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "nl"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

git version 2.30.0

node: v15.5.0

npm: 7.3.0

yeoman: 2.0.2

yarn: 1.22.10

Docker version 20.10.0, build 7287ab3

docker-compose version 1.27.4, build 40524192

##### **Overview of the issue**

running jhipster generation using v6.10.5 fails when choosing react as frontend framework

##### **Motivation for or Use Case**

attempt to upgrade from v6.8.0 to v6.10.5

##### **Reproduce the error**
run
jhipster

choose all defaults and react as frontend framework

##### **Suggest a Fix**

https://github.com/jhipster/react-jhipster/blob/main/package.json seems to need some updates on transient dependency versions

##### **JHipster Version(s)**

Jhipster 6.10.5

##### **JHipster configuration**

<!--
To provide all information we need, you should run `jhipster info` in the project root folder, and
copy/paste the result here.

The `.yo-rc.json` file generated in the root folder is mandatory for bug reports. This will help us to replicate the scenario.
You should remove any sensitive information like the rememberMe key or the jwtSecretKey key.
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "Downloads",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YjI1OTM5NTk3NWY4ZjA5NDQ0MzJmMmY3NTAzN2IzNmRhMDg5NjY2ZmI3NGQyODVkNmU3YWM5MWRmNjM3MGEzZWVlOGY5NDlkNzcxODg3MWEyNjc2MTBiMTUwYmFhYWRmNzU5YjQ5MjY5YWUyOWYzNjEwNGNmYmRhNTJmMjcxMTA=",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1609755407496,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "nl"],
    "blueprints": []
  }
}

##### **Browsers and Operating System**
OS X 10.14.6 - not browser related

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Support for npm v7 is tracked in https://github.com/jhipster/generator-jhipster/issues/12747

Please use an LTS version of Node and NPM.
> Latest LTS Version: 14.15.3 (includes npm 6.14.9)
https://nodejs.org/en/download/
https://nodejs.org/en/about/releases/
