### ISSUE TITLE
Not used config stored in .yo-rc.json

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#13412]
##### **Overview of the issue**

When generating a **microservice** application, there are some properties in `.yo-rc.json` which are incorrect:

```
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": true
```

##### **Motivation for or Use Case**

As there is no front part, these properties should not be here.

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/18-micro
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "microservice",
    "baseName": "jhipster",
    "jhipsterVersion": "7.0.0-beta.0",
    "skipClient": true,
    "skipUserManagement": true,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1609832735305,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "serviceDiscoveryType": "eureka",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8081",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["fr"],
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

git version 2.30.0

node: v14.15.3

npm: 6.14.9

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.27.3, build 4092ae5d

INFO! Congratulations, JHipster execution is complete!

**Comment by mshima** [comment]
Reopening to track same problem with skipServer/skipClient related to https://github.com/jhipster/generator-jhipster/pull/13058#issuecomment-728234151.

**Comment by mshima** [comment]
I've tried to fix this by using jdl defaults methods, but jdl has the same problem:
```
$ jhipster jdl --inline 'application { config { skipClient true } }' --json-only
$ cat .yo-rc.json | grep client
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
```

Same for skipServer for configurations like cacheProvider:
```
$ jhipster jdl --inline 'application { config { skipServer true } }' --json-only
$ cat .yo-rc.json
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": true,
    "baseName": "jhipster",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
```

I will wait for jdl defaults to be fixed first.

**Comment by pascalgrimaud** [comment]
Still todo

**Comment by pascalgrimaud** [comment]
I think it's solved, for unknown reason :-D
So it can be closed
