### ISSUE TITLE
Provide a generic reference data microservice that can be called from UI and server-side code

### ISSUE THREAD

**Issue by vbhatt** [jhipster/generator-jhipster#1341]
Reference data is any kind of data that is used to categorize other data or for relating data to information beyond the boundaries of the enterprise. Sometimes called lookup data, it is organized by domain such as ‘states’ or ‘countries’ and is defined by entities made up of codes and values such as 2 letter state abbreviations and the state name:

domain = “States”
code = ‘NH'
value = ‘New Hampshire'

This reference data microservice can be very useful create and find metadata.

**Comment by jdubois** [comment]
I have no idea what we are supposed to do here... If you want to create a "country" entity just use the entity sub generator.
