### ISSUE TITLE
Remove mLabs and Graphene Add On from Heroku Deployments

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#13424]
##### **Overview of the issue**

Sadly both [mLab](https://docs.mlab.com/shutdown-of-heroku-add-on/) and [Graphene](https://docs.graphenedb.com/docs/shutdown-of-heroku-add-on) have discontinued their Heroku Addons.

To be consistent we should remove both options from the heroku deployment as no replacements with a free tier are available.

I can take care of this.

##### **Motivation for or Use Case**

Do not try to setup something which can't work.

##### **Reproduce the error**

Try to provision an application with mongo db on heroku.

##### **Related issues**

* https://github.com/jhipster/jhipster.github.io/pull/1057

##### **Suggest a Fix**

Remove both options from the heroku subgenerator.

##### **JHipster Version(s)**

6.x, 7.x

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
@pascalgrimaud Do you consider this worth a new 6.x release (I do)? We could also update mapstruct (https://github.com/jhipster/generator-jhipster/issues/12967).

**Comment by pascalgrimaud** [comment]
I could a release, the main question is: is it worth? We should ask it in the mailing list.

In my opinion, we should promote v7 beta. I think we are really closed for final v7 release

**Comment by atomfrede** [comment]
Sounds good to me. I trust you with that, so I will do it only on main.
