### ISSUE TITLE
User "email_verified" value is not mapped correctly from IdP (project w. OAuth) 

### ISSUE THREAD

**Issue by funder7** [jhipster/generator-jhipster#13441]
##### **Overview of the issue**

While doing some updates to the UserService class, I noticed that in the getUser method, where the map of details coming from the identity provider is mapped to the User object, there's something that I can't understand well:

1) A conditions checks if "email_verified" is set, if that is the case, it will be the value of "activated: 
```java
		if (details.get("email_verified") != null) {
			user.setActivated((Boolean) details.get("email_verified"));
		}
```
2) At the end of the function we have:
```java
		user.setActivated(true);
		return user;
```

It's always executed independently of the value returned from the IdP, leading to an "always verified" user. 

3) UserDTO: the constructor (with User as input) is not mapping  `activated` property, which is set to false by default 

I checked git history in case that it was something added by me, but it's all present since initial commit. 

##### **Motivation for or Use Case**

I think that the user must be set as active, ONLY  if "email_verified" property cannot be synced, for example when email activation is disabled in the IdP. 

If the value is always mapped to true, ignoring if the email and/or other values are verified, an user is allowed to access resources reserved to active users only, if some logic is based upon the "activated" status of an user. 

##### **Reproduce the error**

1) Import the JDL 
2) Open keycloak and configure the SMTP server
4) Create a new user from keycloak registration form - (activation mail is sent)
5) Click the activation link, or set email as activated from user settings in keycloak admin panel
6) Fetch the account details through UserService -> getUserFromAuthentication 
7) User is "active"
8) Set user's email activated as false, from keycloak
9) Repeat the operation, user will be active again
10) Comment the line UserService where user.setActive(true)
11) Restart and fetch again the user account details, it will always be false now

This is due to missing mapping in UserDTO constructor, and active property harcoded to false. 

##### **Related issues**

Apparently none.

##### **Suggest a Fix**

Maybe I'm missing something, but I would map UserDTO's active to User in the constructor, and remove the line in UserService, leaving it read the "email_verified" property value. 

If that property is null, then I would consider the User active by default. 

##### **JHipster Version(s)**

6.10.5

##### **JHipster configuration**

The `.yo-rc.json` 

```
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": true,
    "baseName": "testApp",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "jhiPrefix": "tst",
    "languages": ["en", "it", "fr", "es", "de"],
    "messageBroker": false,
    "nativeLanguage": "it",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["protractor"],
    "websocket": "spring-websocket",
    "applicationType": "monolith",
    "clientPackageManager": "npm",
    "clientTheme": "materia",
    "clientThemeVariant": "primary",
    "dtoSuffix": "DTO",
    "packageName": "it.test.app",
    "packageFolder": "it/test/app",
    "skipServer": false,
    "useSass": true,
    "jhipsterVersion": "6.10.5",
    "creationTimestamp": 1610141340787,
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "otherModules": [],
    "blueprints": []
  },
  "entities": []
}
```

---
  <details>
  <summary>JDL definitions</summary>
  <pre>
     application {
  config {
    applicationType monolith
    authenticationType oauth2
    baseName testApp
    buildTool maven
    cacheProvider ehcache
    clientFramework angularX
    clientPackageManager npm
    clientTheme materia
    clientThemeVariant primary
    databaseType sql
    devDatabaseType postgresql
    dtoSuffix DTO
    enableHibernateCache true
    enableSwaggerCodegen true
    enableTranslation true
    jhiPrefix tst
    languages [en, it, fr, es, de]
    messageBroker false
    nativeLanguage it
    packageName it.test.app
    prodDatabaseType postgresql
    searchEngine false
    serverPort 8080
    serviceDiscoveryType false
    skipClient false
    skipServer false
    skipUserManagement true
    testFrameworks [protractor]
    useSass true
    websocket spring-websocket
  }
}

  </pre>
  </details>

##### **Browsers and Operating System**

 macOs Catalina 10.15.7 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
hi @funder7 
firstly the bug about the DTO mapping is no still relevant since we moved to two separate objects for admin and non-admin fields. The field has been added since.

Then, the second part is about the "email_verified" field. I think you are right and we should consider this value to set the activated flag. I asked @mraible's review to be sure we are doing well.

Unfortunately, we don't plan to do some 6.X fixing version and move directly to the 7 one, please consider using JHipster 7 in the future to have this fix.

WDYT?

We made the fix during a streaming session here: http://twitch.tv./avdev4j

**Comment by funder7** [comment]
Hi @avdev4j thanks for the info, I looked on your twitch page but I couldn't find the exact video where the topic is discussed. 
Btw it's nice to see that jh 7.0 is coming, I will check it out in the next weeks. 

I noticed a problem with synchronization between the IdP and local User representation, it's done once the "updated_at" value is present in the token, but if you update the user's details on the IdP, then the auth token will not contain updated information (especially the "updated_at" value will not represent the correct value).  

So if you use something like keycloak-admin, to update the user profile on IdP, without invalidating the access token, the local user representation (I mean what's saved in the "jhi_user" table), will not be refreshed. 

To overcome this, I updated manually the local user info. Then user data is synced from IdP only when the auth token is newer than local user data. Otherwise, the previous data present in the token would override the new changes. 

Maybe invalidating the access token, once user data is updated on IdP, would make the actual code work without any change: once the access token is invalid, the client gets a new one with updated user data. 

I've [asked on StackOverflow](https://stackoverflow.com/questions/65684388/jhipster-keycloak-how-to-update-user-data-on-keycloak-correctly) some days ago, but I've received no answers (oAuth2 is scary. uh?! :-D) 

It's not very easy to explain without code though, but I think that this an important topic that must be addressed, in order to take full advantage of OpenId functionalities. 

If you need more info, or somebody else would be interested into analyzing this, please let me know, I would be happy to give more details and some code examples. 

Cheers.
