### ISSUE TITLE
Protractor tests fail to run in a microservices architecture

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13443]
##### **Overview of the issue**

If I use <https://github.com/jhipster/jdl-samples/blob/main/microservices-blog-store.jh> to generate a new microservices architecture, the Protractor tests fail to run when I run `npm run e2e` in the gateway app.

```
➜  gateway git:(master) npm run e2e

> gateway@0.0.1-SNAPSHOT e2e /Users/mraible/blog-store/gateway
> npm run e2e:protractor


> gateway@0.0.1-SNAPSHOT e2e:protractor /Users/mraible/blog-store/gateway
> protractor src/test/javascript/protractor.conf.js

[19:18:13] I/launcher - Running 1 instances of WebDriver
[19:18:13] I/direct - Using ChromeDriver directly...
[19:18:13] E/runner - Unable to start a WebDriver session.
[19:18:13] E/launcher - Error: Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at Object.spawn (child_process.js:553:9)
    at exec (/Users/mraible/blog-store/gateway/node_modules/selenium-webdriver/io/exec.js:116:27)
    at /Users/mraible/blog-store/gateway/node_modules/selenium-webdriver/remote/index.js:219:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[19:18:13] E/launcher - Process exited with error code 100
npm ERR! code ELIFECYCLE
npm ERR! errno 100
npm ERR! gateway@0.0.1-SNAPSHOT e2e:protractor: `protractor src/test/javascript/protractor.conf.js`
npm ERR! Exit status 100
npm ERR!
npm ERR! Failed at the gateway@0.0.1-SNAPSHOT e2e:protractor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2021-01-09T02_18_13_254Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 100
npm ERR! gateway@0.0.1-SNAPSHOT e2e: `npm run e2e:protractor`
npm ERR! Exit status 100
npm ERR!
npm ERR! Failed at the gateway@0.0.1-SNAPSHOT e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2021-01-09T02_18_13_292Z-debug.log
```

##### **Motivation for or Use Case**

Protractor tests should run if you choose it as a testing tool.

##### **Reproduce the error**

With JHipster 7 beta 0, download the aforementioned JDL and run `jhipster import microservices-blog-store.jdl`. Start Docker containers, apps, and run `npm run e2e` in the gateway app's directory.

##### **JHipster Version(s)**

INFO! Using JHipster version installed locally in current project's node_modules
##### **JHipster Version(s)**

```
gateway@0.0.1-SNAPSHOT /Users/mraible/blog-store/gateway
└── generator-jhipster@7.0.0-beta.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "withAdminUi": true,
    "baseName": "gateway",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "skipClient": false,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "packageName": "com.okta.developer.gateway",
    "packageFolder": "com/okta/developer/gateway",
    "applicationType": "gateway",
    "jhipsterVersion": "7.0.0-beta.0",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1610156903214,
    "lastLiquibaseTimestamp": 1610157143000,
    "entities": ["Tag", "Product", "Blog", "Post"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Tag {
  name String required minlength(2)
}
entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Tag, Post with infinite-scroll
paginate Product with pagination
microservice Tag, Blog, Post with blog
microservice Product with store
clientRootFolder Tag, Blog, Post with blog
clientRootFolder Product with store

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v14.15.0

npm: 6.14.11

yeoman: 3.1.1

Docker version 20.10.0, build 7287ab3

docker-compose version 1.27.4, build 40524192

INFO! Congratulations, JHipster execution is complete!

**Comment by pascalgrimaud** [comment]
it looks strange, something like protractor was not download correctly
did you retry npm install ?

**Comment by mraible** [comment]
I did. I removed node_modules and ran npm install again. Same issue.

**Comment by kaidohallik** [comment]
I tested this with the current main branch and was working for me.

**Comment by kaidohallik** [comment]
I made #13449 to update Protractor related dependencies. Maybe this is Chrome version issue and maybe driver update helps.

**Comment by mraible** [comment]
@kaidohallik I updated to webdriver-manager 12.1.8 and indeed it fixed the problem. Found the answer [here](https://stackoverflow.com/questions/65618558/osx-fix-selenium-chromedriver-launch-error-spawn-unknown-system-error-86-bad-cp).
