### ISSUE TITLE
Broken Swagger with Microservices

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#13444]
##### **Overview of the issue**

With current v7 beta, you can't use swagger to call your other microservices

##### **Reproduce the error**

- create a Gateway application
- create a Microservice with 1 entity
- start registry or consul
- start gateway
- start microservice
- try to access to entity with Swagger

##### **Related issues**

Not sure, but I think it's related to upgrade to openapi3

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
cc @nassimerrahoui @qmonmert as I know you already started to investigate
but help is welcome here !

**Comment by nassimerrahoui** [comment]
To add more information : the problem is related to this change https://swagger.io/docs/specification/api-host-and-base-path/
In OpenAPI 3.0, servers array specify one or more base URLs for API. servers replaces the host, basePath and schemes keywords used in OpenAPI 2.0.

**Comment by qmonmert** [comment]
@pascalgrimaud I claim my money :) https://opencollective.com/generator-jhipster/expenses/31623

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by qmonmert** [comment]
Thanks @pascalgrimaud
