### ISSUE TITLE
Create a Vue PWA with JHipster 7 beta 0 doesn't work

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13468]
##### **Overview of the issue**

Creating a PWA with JHipster should be simple. You just need to comment out the Service Worker code in `src/main/webapp/index.html`.

```html
<script>
    if ('serviceWorker' in navigator) {
         navigator.serviceWorker
            .register('./service-worker.js')
            .then(function() { console.log('Service Worker Registered'); });
    }
</script>
```

I tried this with a Vue app and it results in an error in my browser's console.

```
A bad HTTP response code (404) was received when fetching the script.
(index):1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('http://localhost:8080/') 
with script ('http://localhost:8080/service-worker.js'): A bad HTTP response code (404) was received when fetching 
the script.
Promise.then (async)
(anonymous) @ (index):18
```

##### **Motivation for or Use Case**

It should be possible to create a PWA with Vue.

##### **Reproduce the error**

Create a new Vue app with JHipster 7, try to make it into a PWA.

##### **Suggest a Fix**

Add `service-worker.js` to a Vue project.

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/mraible/dev/choose-jhipster/gateway
└── generator-jhipster@7.0.0-beta.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "clientFramework": "vue",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "withAdminUi": true,
    "baseName": "gateway",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en"
    ],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [
      "cypress"
    ],
    "websocket": false,
    "applicationType": "gateway",
    "reactive": true,
    "packageName": "com.okta.developer.gateway",
    "packageFolder": "com/okta/developer/gateway",
    "jhipsterVersion": "7.0.0-beta.0",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1610406750939,
    "lastLiquibaseTimestamp": 1610406990000,
    "entities": [
      "Tag",
      "Product",
      "Blog",
      "Post"
    ],
    "appFolder": "gateway"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Tag {
  name String required minlength(2)
}
entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Tag, Post with infinite-scroll
paginate Product with pagination
microservice Tag, Blog, Post with blog
microservice Product with store
clientRootFolder Tag, Blog, Post with blog
clientRootFolder Product with store

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v14.15.0

npm: 6.14.11

yeoman: 3.1.1

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192

**Comment by swarajsaaj** [comment]
It seems workbox configuration is missing in Vue's webpack configuration, hence it is not generating the service-worker.js dynamically
