### ISSUE TITLE
A reactive monolith is not AAA in Sonar

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13471]
##### **Overview of the issue**

If I generate a reactive monolith, the Sonar scores aren't great. Instead of A for Bugs, it's a C. And there's a new Hotspots Reviewed metric that seems to error.

![image](https://user-images.githubusercontent.com/17892/104277016-4ae5c600-5463-11eb-922e-407a0c90af3a.png)

##### **Motivation for or Use Case**

It's fun to show Sonar in demos when it scores AAA!

##### **Reproduce the error**

Create an app with the JDL and fixes from #13467. Then, start Sonar and run:

```
./mvnw -Pprod clean verify sonar:sonar -Dsonar.host.url=http://localhost:9001
```

Log in to http://localhost:9001 and view the report.

##### **Related issues**

#13467

##### **Suggest a Fix**

Not sure.

##### **JHipster Version(s)**

7.0 beta 0

**Comment by mraible** [comment]
If I change to use MongoDB instead of MySQL, the results are better.

<img width="1220" alt="Screen Shot 2021-01-11 at 11 42 16 PM" src="https://user-images.githubusercontent.com/17892/104278956-afeeeb00-5466-11eb-8260-837753365ae4.png">

Here's the JDL I used:

```
application {
  config {
    baseName blog
    applicationType monolith
    authenticationType oauth2
    packageName com.jhipster.demo.blog
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    buildTool maven
    clientFramework vue
    reactive true
    testFrameworks [cypress]
  }
  entities *
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll
```

**Comment by qmonmert** [comment]
@mraible I tried with MongoDB and the result seems good:

![image](https://user-images.githubusercontent.com/9989211/104561504-cc964900-5647-11eb-91d4-0f51bec7a4ed.png)

**Comment by mraible** [comment]
You are correct. It seems to be a problem when using MySQL (R2DBC).

**Comment by murdos** [comment]
Keep open, I'll take a look
