### ISSUE TITLE
Remove (and replace) @Transactional in tests

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#13475]
##### **Overview of the issue**

We should not use Transactional in tests and replace it without something different.

##### **Motivation for or Use Case**

I faced a similar issue to the one descried here, in my case it wasn't a false negative thankfully, the rollback just didn't happen because I was using `@Transactional(Transactional.TxType.REQUIRES_NEW)`  in the method I called from my test, and I would just have removed transactional and moved on but thankfully another test fails (idempotence was broken), the thread below explain how to fix it.

https://dev.to/henrykeys/don-t-use-transactional-in-tests-40eb

##### **Reproduce the error**

Follow what was explained in the post, or anotate something in your repo with `@Transactional(Transactional.TxType.REQUIRES_NEW)` making it not rollback.

##### **Suggest a Fix**

```
@BeforeEach
    public void initTest() {
    TestUtil.deleteAll(em, Entity.class);
    TestUtil.deleteAll(em, EntityDependendency1.class);
...
    entity = = createEntity(em);
}
```
with the code of deleteAll similar to findAll

##### **JHipster Version(s)**

6.8.0

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Related: there's a Sonar warning for having `@Transactional` on a package-protected method in `UserService`.
 
<img width="1054" alt="Screen Shot 2021-01-13 at 11 36 29 AM" src="https://user-images.githubusercontent.com/17892/104494382-9eefc800-5593-11eb-94e8-bf50dacb92af.png">

**Comment by pascalgrimaud** [comment]
For me, the deleteAll can't work for all use cases, specially if you use some fake data to init your database in testcontainers for example, and before launching deleteAll for entityC, you need first deleteAll for entityB, but it needs to deleteAll entityA etc...
It's hard to find the correct logic in our template here

In my opinion, we have Transactional for years here and it works pretty well.
So unless a string argument, I'd prefer to keep like it today

Let's discuss, I'm waiting opinion from other people.

**Comment by yelhouti** [comment]
@pascalgrimaud about the logic in the template, createEntity tells us all we need to know, we could have a delete that work in the exact same way: each resourceIT has a deleteAll, that calls its relationsResourceIT.deleteAll. We could even call it resetAll so that it can be used to initData in testContainers....

I also would rather we keep `@Transactional` it is much easier to think about, but creates a lot problems when you have multiple instances... because of false negatives.

**Comment by Tcharl** [comment]
I'm not a fan having tests using `@transactional` because it can skip some use cases (example, adding the same value twice on an `@Unique` field won't throw an exception).
But if we keep it, we can add `TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();` in our teardown, so that we would keep idempotence between tests
