### ISSUE TITLE
Tracker websockets are open many times and never closed

### ISSUE THREAD

**Issue by luc-clement** [jhipster/generator-jhipster#1347]
Hello,

I'm working on a project using JHipster 2.6.0. 

I figured out some strange behavior in the application (not a bug properly speaking) concerning the tracker socket. It seems that the TrackerController is loaded each time you go to state 'tracker'. But each time you do this, it will create a new socket that will subscribe to '/topic/activity' and will never unsubscribe.
That means that if you keep a session open as an administrator for a long time, and go to the tracker view several times (let's say X times), for each user going to a new state, you will receive X times the same message. 
And you'll also continue receiving those messages X times even if you're not on the tracker page anymore since you didn't close the sockets.

Here is what I can see in the javascript console, logged in as an admin user, after going 4 times on the Users Tracker page and when another windows logged in as a user : 
> "<<< MESSAGE
> destination:/topic/activity
> content-type:application/json;charset=UTF-8
> subscription:sub-0
> message-id:6q5iynxd-57
> content-length:117

> {"sessionId":"tx9ouo5c","userLogin":"user","ipAddress":"/127.0.0.1:49656","page":"home","time":"2015-04-06 20:16:46"}

> "<<< MESSAGE
> destination:/topic/activity
> content-type:application/json;charset=UTF-8
> subscription:sub-0
> message-id:f0fxrfnc-88
> content-length:117

> {"sessionId":"tx9ouo5c","userLogin":"user","ipAddress":"/127.0.0.1:49656","page":"home","time":"2015-04-06 20:16:46"}

> "<<< MESSAGE
> destination:/topic/activity
> content-type:application/json;charset=UTF-8
> subscription:sub-0
> message-id:gnmnrx4j-86
> content-length:117

> {"sessionId":"tx9ouo5c","userLogin":"user","ipAddress":"/127.0.0.1:49656","page":"home","time":"2015-04-06 20:16:46"}

> "<<< MESSAGE
> destination:/topic/activity
> content-type:application/json;charset=UTF-8
> subscription:sub-0
> message-id:opdl57z0-87
> content-length:117

> {"sessionId":"tx9ouo5c","userLogin":"user","ipAddress":"/127.0.0.1:49656","page":"home","time":"2015-04-06 20:16:46"}

You will notice that only the message-id is changing, but the message content is always the same.

Does that mean that we have as many instances of an angular controller running as we went to a state using this controller ? And does that also mean that the controllers are still running after we go to a state that isn't associate with this controller anymore (since we still receive the messages when we aren't on the tracker page anymore) ?

I can't find a proper way to fix it because I'm not sure I understand well the behavior of the controllers here...

**Comment by jdubois** [comment]
Can you have a look at the 2.7.0 code base? Prior to this version, I agree that was buggy.

**Comment by luc-clement** [comment]
I just launched a new app with the 2.7.0 version, it looks like we have the same behavior.

The problem probably comes from the tracker.controller.js file where we create a socket and subscribe to '/topic/activity' :
```javascript
angular.module('jhipsterApp')
    .controller('TrackerController', function ($scope) {
        // This controller uses a Websocket connection to receive user activities in real-time.

        $scope.activities = [];
        var stompClient = null;
        var socket = new SockJS('/websocket/tracker');
        stompClient = Stomp.over(socket);
        stompClient.connect({}, function(frame) {
            stompClient.subscribe('/topic/activity', function(activity){
                showActivity(JSON.parse(activity.body));
            });
        });

        function showActivity(activity) {
            var existingActivity = false;
            for (var index = 0; index < $scope.activities.length; index++) {
                if($scope.activities[index].sessionId == activity.sessionId) {
                    existingActivity = true;
                    if (activity.page == 'logout') {
                        $scope.activities.splice(index, 1);
                    } else {
                        $scope.activities[index] = activity;
                    }
                }
            }
            if (!existingActivity && (activity.page != 'logout')) {
                $scope.activities.push(activity);
            }
            $scope.$apply();
        };
    });

```
As I said in my first post, it looks like we have a new instance of this tracker controller running each time we visit the 'tracker' state in the same session as an administrator.

**Comment by jdubois** [comment]
I confirm the issue. I shouldn't have created the Websocket connection in the controller, this needs to be refactored.
