### ISSUE TITLE
JHipster 7.0.0.beta.0 - reactive database password not configured for Kubernetes

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#13481]
##### **Overview of the issue**

Kubernetes generator configures the `SPRING_DATASOURCE_PASSWORD` env var. But reactive apps currently configures database password w/ `spring.r2dbc.password`. Which translates to `SPRING_R2DBC_PASSWORD`.

##### **Motivation for or Use Case**

Preparing for a demo.

##### **Reproduce the error**

1. Generate app from https://github.com/mraible/choose-jhipster/blob/main/apps.jdl
2. Notice that the gateway uses reactive
3. Deploy to Kubernetes
4. Observe Gateway failure. Log shows that the password is incorrect.

##### **Suggest a Fix**

For reactive apps, configure `SPRING_R2DBC_PASSWORD` env var.

##### **JHipster Version(s)**

7.0.0.beta.0

##### **JHipster configuration**

```
application {
  config {
    applicationType gateway
    baseName gateway
    clientFramework vue
    reactive true
    packageName com.okta.developer.gateway
    authenticationType oauth2
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    applicationType microservice
    baseName blog
    reactive false
    packageName com.okta.developer.blog
    authenticationType oauth2
    prodDatabaseType mysql
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    applicationType microservice
    baseName store
    reactive true
    packageName com.okta.developer.store
    authenticationType oauth2
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}

```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by saturnism** [comment]
fyi @mraible

**Comment by saturnism** [comment]
it looks like the `deployment.yml` template already has a conditional on `reactive`. for some reason, that didn't seem effective.

https://github.com/jhipster/generator-jhipster/blob/v7.0.0-beta.0/generators/kubernetes/templates/deployment.yml.ejs

**Comment by mraible** [comment]
@saturnism I believe that conditional might need to be changed to `app.reactive` (I'm guessing from looking at the other conditionals).

```
<%_ if (app.reactive) { _%>
```

**Comment by saturnism** [comment]
ah it looks like the conditional did work, but it only has `SPRING_R2DBC_URL`, but not `SPRING_R2DBC_PASSWORD`

**Comment by saturnism** [comment]
oops, it does need to be changed to `app.reactive`. was testing w/ different code base.
