### ISSUE TITLE
JHipster v7 beta 0 - mvn verify fails when using neo4j

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13484]
##### **Overview of the issue**

If you create a microservice app with Neo4j and try to create a Docker image from it, tests fail:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.018 s <<< FAILURE! - in com.okta.developer.blog.web.rest.UserResourceIT
[ERROR] com.okta.developer.blog.web.rest.UserResourceIT  Time elapsed: 0.018 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=neo4j:4.2.1, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.NotFoundException:
Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}
```

##### **Motivation for or Use Case**

Tests should pass when generating an app.

##### **Reproduce the error**

Create an app with the following JDL, cd into `blog` and run `./mvnw -ntp -Pprod verify jib:dockerBuild`.

```
application {
  config {
    applicationType gateway
    baseName gateway
    clientFramework vue
    reactive true
    packageName com.okta.developer.gateway
    authenticationType oauth2
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    applicationType microservice
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    authenticationType oauth2
    databaseType neo4j
    devDatabaseType neo4j
    prodDatabaseType neo4j
    enableHibernateCache false
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    applicationType microservice
    baseName store
    reactive true
    packageName com.okta.developer.store
    authenticationType oauth2
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}
```

##### **Suggest a Fix**

Not sure, maybe replace with another Docker container?

##### **JHipster Version(s)**

```
blog@0.0.0 /Users/mraible/dev/choose-jhipster/blog
└── generator-jhipster@7.0.0-beta.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "serverPort": "8081",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "baseName": "blog",
    "buildTool": "maven",
    "databaseType": "neo4j",
    "devDatabaseType": "neo4j",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en"
    ],
    "messageBroker": false,
    "prodDatabaseType": "neo4j",
    "searchEngine": false,
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "microservice",
    "reactive": true,
    "packageName": "com.okta.developer.blog",
    "packageFolder": "com/okta/developer/blog",
    "jhipsterVersion": "7.0.0-beta.0",
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": true,
    "nativeLanguage": "en",
    "creationTimestamp": 1610509250414,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "lastLiquibaseTimestamp": 1610509430000,
    "entities": [
      "Tag",
      "Blog",
      "Post"
    ],
    "appFolder": "blog"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Tag {
  name String required minlength(2)
}
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Tag, Post with infinite-scroll
microservice Tag, Blog, Post with blog
clientRootFolder Tag, Blog, Post with blog

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v14.15.0

npm: 6.14.11

yeoman: 3.1.1

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192

**Comment by atomfrede** [comment]
I think somehow all testcontainers tests should be affected as ryuk is used by tc to coordinate and kill containers even when jvm dies. And (as far as I recall) we don't define a custom the ryuk image. Which testcontainers version is in use? Maybe somehow an older version is used somehow

**Comment by bsideup** [comment]
Due to the recent changes in Docker, it is highly recommended to use Testcontainers 1.15.1. 

@mraible does it pass if you manually change the version to 1.15.1?

**Comment by mraible** [comment]
It looks like the `main` branch is using 1.15.1. I tried to reproduce this issue with the main branch and it works so I'll close this issue.
