### ISSUE TITLE
Use a Builder class for domain classes

### ISSUE THREAD

**Issue by drissamri** [jhipster/generator-jhipster#1350]
First off, great project, I've been putting off to play around with JHipster way too long. It's great to see a feature filled generator with lots of best practises incorporated. 

One minor improvement could be to use the Builder as explained in Effective Java to simplify creating new entities?

<pre>
 User newUser = new User();
        newUser.setLogin(login);
        newUser.setPassword(encryptedPassword);
        newUser.setFirstName(firstName);
        newUser.setLastName(lastName);
        newUser.setEmail(email);
        newUser.setLangKey(langKey);
        newUser.setActivated(false);
        newUser.setActivationKey(RandomUtil.generateActivationKey());
</pre>

Would change to something along the lines of

<pre>
 User newUser = new User().Builder()
        .login(login)
        .password(encryptedPassword)
        .firstName(firstName)
        .lastName(lastName)
        .email(email)
        .langKey(langKey)
        .activated(false)
        .activationKey(RandomUtil.generateActivationKey())
        .build();
</pre>

It's a small change but I do think it's a simplifies it for the user and is a good pattern to follow when construction new entities, especially when there's quite a few properties.

I didn't want add it before being sure you see the benefit of having this in the code as another good practise for people to use?

**Comment by jdubois** [comment]
I'm not using this myself, but I understand why people would like to have it... So in the end it depends if that helps people or not:

- if it helps them, let's do it!
- if not, let's add code that isn't used

Of course, another option is to make it optional in the generator, but I feel we already have too many questions.

We need feedback on this, so everybody feel free to add your comments!!

**Comment by atomfrede** [comment]
Personally I like the fluent style, either with builder or instead of classical setters, but others don't like the fluent style, so it is a design decision. But I totally agree with @jdubois there should no additional question in the generator, as this would make maintaining entities very complex.

**Comment by verrol** [comment]
What about a compromise? 

By default, it works the way it does, setter and getter. But if the user wants, they can edit the .jhipster/<entity>.java and set some property 'useBuilder' to true, which is false by default. Then they just re-run entity sub-generator for the entity they want. That way, they don't have to answer an additional question for every entity. And they can choose which entity will use builders. There could also be a global or per project .jhipsterrc file, like git config. The user can set options they want on all projects or for a specific project.

**Comment by drissamri** [comment]
I think that makes it a hidden feature that wouldn't be used often enough to justify putting it in the code.

It should be either included for User entity and Entity generator or not included at all I think. I would not make it an additional question either.

**Comment by jdubois** [comment]
OK, I think we all agree we shouldn't make an additional question, and that the builder code wouldn't be used by everyone (including me!), so in the end that would mean we add some code that wouldn't be used by most people -> this of course isn't a good solution

So we will not add this feature at the moment.

**Comment by cselti** [comment]
@drissamri : most IDEs (I saw in IntelliJ, Netbeans and Eclipse also) have a [builtin](https://www.jetbrains.com/idea/help/replace-constructor-with-builder.html)  or [plugin provided](https://plugins.jetbrains.com/plugin/7354) refactoring case, that can generate a builder class from POJO and/or a constructor.
