### ISSUE TITLE
Angular many-to-one and many-to-many relationships shows empty value.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#13510]
##### **Overview of the issue**

Angular many-to-one and many-to-many relationships may show empty value even if there is a value.
This problem happens when pagination at related Entity is enabled:
- With pagination only 20 items are returned from the server.
- If the saved value is not returned from server, select shows an empty value even when the value exists.

##### **Motivation for or Use Case**

Selects should not show empty value if there is a value.

##### **Reproduce the error**

- Download https://github.com/jhipster/jdl-samples/blob/main/bug-tracker.jh
- Add `Project` to pagination.
- Import `jhipster jdl bug-tracker.jh`
- Run the application
- Create 11 more Projects
- Go to `administration -> database`
- Select `Ticket`
- Set any Ticket's Project to the last project eg: 1011
- Go to the Ticket edit page.
- Project's select is empty.

##### **Suggest a Fix**

Add Project registry to the select if not returned from the server.

##### **JHipster Version(s)**

master

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "baseName": "jhipster",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "jhipsterVersion": "7.0.0-beta.0",
    "skipServer": false,
    "packageFolder": "com/mycompany/myapp",
    "packageName": "com.mycompany.myapp",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "applicationType": "monolith",
    "entities": ["Project", "Label", "Ticket", "Attachment", "Comment"],
    "skipJhipsterDependencies": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "reactive": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1604089251719,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "lastLiquibaseTimestamp": 1604089551000,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Project {
  name String
}
entity Label {
  label String required minlength(3)
}
entity Ticket {
  title String required
  description String
  dueDate LocalDate
  date ZonedDateTime
  status Status
  type Type
  priority Priority
}
entity Attachment {
  name String required minlength(3)
  file AnyBlob
}
entity Comment {
  date ZonedDateTime
  text String
}
enum Status {
  OPEN (Open),
  WAITING_FOR_RESPONSE (Waiting for Customer Response),
  CLOSED (Closed),
  DUPLICATE (Duplicate),
  IN_PROGRESS (In Progress),
  REOPENED (Reopened),
  CANNOT_REPRODUCE (Cannot Reproduce),
  SOLVED (Solved),
  WONT_IMPLEMENT (Won't Implement),
  VERIFIED (Verified)
}
enum Type {
  BUG (Bug),
  FEATURE (Feature)
}
enum Priority {
  HIGHEST (Highest),
  HIGHER (Higher),
  HIGH (High),
  NORMAL (Normal),
  LOW (Low),
  LOWER (Lower),
  LOWERST (Lowest)
}

relationship OneToMany {
  Ticket{attachment} to Attachment{ticket}
  Comment{parent} to Comment{child}
}
relationship ManyToOne {
  Ticket{project(name)} to Project
  Ticket{assignedTo(login)} to User
  Ticket{reportedBy(login)} to User
  Comment{login} to User
}
relationship ManyToMany {
  Ticket{label(label)} to Label{ticket}
}

paginate Project, Ticket with pagination

</pre>
</details>

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
it looks like a bug which needs to be fixed for beta.1
Adding a bounty on this

**Comment by qmonmert** [comment]
@mshima maybe I don't understand, but when I set `PROJECT_ID` with value `1001` (not `1011` like you say) on a ticket, the edit page shows the project

![image](https://user-images.githubusercontent.com/9989211/104817380-39187000-5821-11eb-9d58-681c090c059a.png)

![image](https://user-images.githubusercontent.com/9989211/104817388-43d30500-5821-11eb-9f15-afa32592dc2d.png)

![image](https://user-images.githubusercontent.com/9989211/104817394-50eff400-5821-11eb-85ec-f95eade32090.png)

**Comment by mshima** [comment]
@qmonmert you need to create 11 more Projects.
So it will have 21 projects.
Pagination will only return the 20 first projects.

I am working on a fix based on https://github.com/jhipster/generator-jhipster/pull/13496.
Found while improving update component for embedded forms.

**Comment by qmonmert** [comment]
@mshima ok
