### ISSUE TITLE
Angular dependencies need updating

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13526]
##### **Overview of the issue**

Create an Angular project with the `main` branch and run `ncu` (from npm-check-updates):

```
 @ng-bootstrap/ng-bootstrap                  8.0.1  →     9.0.0
 swagger-ui-dist                            3.39.0  →    3.40.0
 zone.js                                    0.10.3  →    0.11.3
 @angular/cli                               11.0.6  →    11.0.7
 @openapitools/openapi-generator-cli  1.0.13-4.3.1  →    2.1.16
 @types/node                              14.14.20  →  14.14.21
 copy-webpack-plugin                         6.4.1  →     7.0.0
 typescript                                  4.0.5  →     4.1.3
```

##### **Motivation for or Use Case**

I like to show how JHipster is up-to-date and doesn't have vulnerabilities.

##### **Reproduce the error**

```
wget https://raw.githubusercontent.com/jhipster/jdl-samples/main/blog-oauth2.jdl
jhipster jdl blog-oauth2.jdl
```

##### **Suggest a Fix**

Update dependencies.

##### **JHipster Version(s)**

```
blog@0.0.1-SNAPSHOT /Users/mraible/dev/angular-protractor
└── generator-jhipster@7.0.0-beta.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": true,
    "withAdminUi": true,
    "baseName": "blog",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "applicationType": "monolith",
    "packageName": "com.jhipster.demo.blog",
    "packageFolder": "com/jhipster/demo/blog",
    "jhipsterVersion": "7.0.0-beta.0",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "entities": ["Blog", "Post", "Tag"],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1610661181529,
    "lastLiquibaseTimestamp": 1610661361000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v14.15.0

npm: 6.14.11

yeoman: 3.1.1

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192

**Comment by mshima** [comment]
>  @ng-bootstrap/ng-bootstrap                  8.0.1  →     9.0.0

Released today

>  swagger-ui-dist                            3.39.0  →    3.40.0

Released today

>  zone.js                                    0.10.3  →    0.11.3

Angular 11.0.x is fixed at 0.10.3

>  @angular/cli                               11.0.6  →    11.0.7

Released today

>  @openapitools/openapi-generator-cli  1.0.13-4.3.1  →    2.1.16

We don’t have test for it and it’s used only for `jhipster openapi`.
I took a look today and I think we should drop the dependency by default and install it at opencli generator.

>  @types/node                              14.14.20  →  14.14.21

We may add to dependabot.
But since we are supporting node 12+,   `@types/node` shouldn’t be 12.x?

>  copy-webpack-plugin                         6.4.1  →     7.0.0

Requires webpack 5

>  typescript                                  4.0.5  →     4.1.3

Angular 11.0.x is fixed at 4.0.x

**Comment by mshima** [comment]
<img width="691" alt="image" src="https://user-images.githubusercontent.com/1417183/104919019-5e69c300-5974-11eb-9212-3138b8a45210.png">
None of them are updatable due to angular dependencies.

**Comment by mraible** [comment]
@mshima Is there some tool that you used to determine this? It looks useful.

**Comment by mshima** [comment]
@mraible plain `npm outdated`.
I used npm 7, but should be available to npm 6 too.
