### ISSUE TITLE
track changes in generated app

### ISSUE THREAD

**Issue by psakar** [jhipster/generator-jhipster#1352]
Hello,
I would like to store in version control result(s) of running generator. It will enable following:

    example of generated files
    easy way to see what was changed in generated files between versions

**Comment by jdubois** [comment]
I don't understand your idea, you can already store your generated files in version control? Can you explain what you want to do?
I'm sorry but there are so many changes in your PR that I don't know what it's supposed to do (but I'm sure it's something useful!)

**Comment by psakar** [comment]
I want to store generated files for some example configuration **inside** your project. The test than verifies not only presence of generated files (this is currently is doing test/test-creation.js), but it also **verifies the content of generated files**. 

Hence I've added test test-generate-app-hibernate-ehcache.js which generates application with default options with hibernate and ehcache. The test compares generated files to files stored in added folder test/archetypes/app-hibernate-ehcache

Other test is for generating entity (test-generate-entity.js -> folder  test/archetypes/entity).

This would mean, that change in generator would require (in most cases) also the change in files used for comparison, thus users (and author) can see what is the actual change in generated files.

Other part of the change is that every test generates the files into its own temporary folder in test/temp, and the folder is deleted after the test.

The deleting of folder with generated files can be suppressed by setting _DEBUG=true in the test.

**Comment by jdubois** [comment]
OK, personally I don't need this feature (I'm working directly with a diff in Git), and I'm afraid this is going to add a lot of new files.
Any feedback from other users?

**Comment by wuethrich44** [comment]
In my opinion is this feature part of a version control system so jhipster don't need it.

**Comment by PeterEltgroth** [comment]
I agree with @wuethrich44, version control systems exist for this reason, and I prefer GIT above all others.

**Comment by psakar** [comment]
the intent is to track in version control changes in **generated** code as well.

**Comment by PeterEltgroth** [comment]
I must not be understanding what you are doing.

After generating a project I initialize a new GIT repository for it and check in the generated code. Then when a new jhipster generator is released I run the generator again and the regenerated files (classes, js, css, yml, etc.) appear as 'Uncommitted changes' in my projects GIT repository. Then I can review the changes, pick what I want to commit, merge what needs to be merged, and discard changes I do not want.

**Comment by derLukers** [comment]
If I understand this correctly, it is an idea I've played with in my head a bit and could be very useful.

At the moment we cannot (afaik) regenerate or edit entities, that have been changed in any way, for example an entity with a method added or something like that.
With this functionality we'd basically just "rebase" the changes that have been done to one version of a generated file and put them onto the new generated file. This way changes in the entities would be preserved when regenerating or adding attributes

**Comment by jdubois** [comment]
@psakar is this because you want to make a diff between the original generated file, your own file, and a newly generated file? I agree with @wuethrich44 and @PeterEltgroth that you could do this with Git.

**Comment by psakar** [comment]
@PeterEltgroth  I did not know I can do it this way / it was not possible for entities and OTOH this approach will not work once you start to customize (at least not in such straightforward way  - soon or later you will run into conflicts)

@derLukers If I understand Peters approach, it should work for you ...

@jdubois right, that works (AFAIK at least for app and entities ATM, I do not know if it works for other types). OTOH, how do you know, that changes in generator are correct without testing ? This was meant to be the test, because it does not test only presence of generated files, but it compares generated files with 'template' (or as I call it archetype (maven like))

**Comment by jdubois** [comment]
@psakar I do my own test by hand. I test (most) combinations for errors before each release. This can take quite some time! But I couldn't find a way to automate this.
I'm closing this as we won't merge your PR, as I think we all agree we can do this with Git.
