### ISSUE TITLE
Gradle doesn't run tests like Maven does when building Docker image

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13531]
##### **Overview of the issue**

The Docker Compose sub-generator spits out the following command to generate Docker containers:

```
./gradlew bootJar -Pprod jibDockerBuild
```

This doesn't appear to run tests as the Maven build command does.

```
./mvnw -Pprod package verify jib:dockerBuild 
```

##### **Motivation for or Use Case**

We should be consistent. As a person who demos a lot, I like that tests aren't run because it's faster. However, I'm not sure that's the best practice.

##### **JHipster Version(s)**

v7 main branch

**Comment by atomfrede** [comment]
The equivalent command would be `bootJar check`. I also would not run the test when building the image as I mostly do it before.

**Comment by mraible** [comment]
If that's the case, we should remove `verify` from the Maven command.

**Comment by ruddell** [comment]
`verify` was added for a specific reason in https://github.com/jhipster/generator-jhipster/pull/8864, I'm not sure if it is still needed.

**Comment by mraible** [comment]
I tested building with `package` instead of `verify` using the following JDL:

```
application {
  config {
    baseName gateway
    reactive true
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    clientFramework vue
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    databaseType neo4j
    devDatabaseType neo4j
    prodDatabaseType neo4j
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store
    reactive true
    packageName com.okta.developer.store
    applicationType microservice
    authenticationType oauth2
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}
```

Then, I built Docker images using `./mvnw -ntp -Pprod package jib:dockerBuild`. I ran everything using Docker compose and then ran `npm run e2e` in the `gateway` directory.

Tests didn't pass the first time, but they did the 2nd time I tried!

```
  27 passing (20s)

[11:36:30] I/launcher - 0 instance(s) of WebDriver still running
[11:36:30] I/launcher - chrome #01 passed
```

**Comment by vishal423** [comment]
I believe the `Jib` docker build should also work with `compile` phase.

**Comment by mraible** [comment]
What Maven command would you recommend we use for Jib, @saturnism?

**Comment by atomfrede** [comment]
The [documentation](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#build-your-image) just uses compile like this `mvn compile jib:dockerBuild` so `package` without verify should work

**Comment by mraible** [comment]
@atomfrede I like how the referenced documentation allows you to bind to a build phase, like `package`. Maybe we should use that so the command can be `./mvnw -Pprod jib:dockerBuild`.

**Comment by atomfrede** [comment]
Keep it open please.

**Comment by mraible** [comment]
☘️

**Comment by atomfrede** [comment]
Keep it open there is a pending PR

**Comment by Tcharl** [comment]
Package looks to be the right maven lifecycle phase for docker build: after all, it's like getting your jar. If you want to skip unit tests which are executed before, use -DskipTests. 
I don't know for gradle, but the maven lifecycle is pretty straighforward:

- Clean => Clean
- Generate source => processors
- process source => Processors, but for source modification
- Generate/Process resources => same for configuration
- Compile => .class
- Process classes => Bytecode
- Test => Unit test
- Package => get the binary
- Integration tests => start the runtime, execute tests on binary, stop the runtime
- Verify => quality of the binary (signature?)
- Install => local installtion
- Deploy => to the package repo or PaaS
- Site => process doc, aggregate reports
- Deploy site => same as deploy, but for site

**Comment by atomfrede** [comment]
Can we close this?

**Comment by mraible** [comment]
Yep.
