### ISSUE TITLE
[Feature Request] Custom Table Prefix

### ISSUE THREAD

**Issue by hdost** [jhipster/generator-jhipster#1356]
Rather than force all tables to be generated with T_ it would be nice to have no prefix or even a custom one.

This might require some sort of property file. Could potentially be added to the .yo-rc.json file during setup.

**Comment by PeterEltgroth** [comment]
Does #1278 address this request?

**Comment by hdost** [comment]
It looks as if the discussion has been had, I think the ticket can be closed

**Comment by hirro** [comment]
Maybe the contents of the .jhipster folder can be moved into an entities
folder (.jhipster/entities).
This would make room for database meta-data, ./jhipster/Database.json for
example, where the prefix is stored.

Maybe there are more meta-data that could be added if the meta-data files
are reorganized, custom types such as enums might be an example.

2015-04-08 15:37 GMT+02:00 Peter Eltgroth <notifications@github.com>:
