### ISSUE TITLE
Provide browser support in documentation

### ISSUE THREAD

**Issue by gmetais** [jhipster/generator-jhipster#1357]
The documentation doesn't provide any browser support information.

By reading the code, the supported IE version is not very clear:
- the used jQuery version (2.1.3) only supports IE >= 9.
- in the HTML template, there are a few `<!--[if lt IE X]>` conditions that add CSS classes for old browsers down to IE7.
- there's also in the HTML template a warning message "You are using an outdated browser" if IE < 10.
- ~~the JS library json3.js is loaded, which is only needed by IE <= 7~~

It would be great to decide what's the supported version of IE and make a few changes in the code to stick to it. Than add a chapter to the documentation.

**Comment by gmetais** [comment]
> the JS library json3.js is loaded, which is only needed by IE <= 7

Json3 is not a simple polyfill for IE <= 7, is was json2. It actually also contains a better serialization for "primitive wrapper objects" and dates and some other changes.

Sorry for the mistake!

**Comment by jdubois** [comment]
Hi @gmetais - shouldn't this be closed now?

**Comment by gmetais** [comment]
Oh yes sure!
