### ISSUE TITLE
Upgrade to Spring Boot 2.4

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13582]
##### Overview of the feature 

We should upgrade to use Spring Boot 2.4.

##### Motivation for or Use Case

Spring Boot has releases every six months now. We should try to support its major releases as much as possible.

##### Related issues or PR

https://github.com/jhipster/generator-jhipster/pull/13551 for main generator and https://github.com/jhipster/jhipster-bom/pull/133 for JHipster BOM.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@mraible : there is already a ticket here https://github.com/jhipster/generator-jhipster/issues/13237 so I think we should close one

**Comment by mraible** [comment]
You're right. Sorry about that. I'll close this one.
