### ISSUE TITLE
JMS support

### ISSUE THREAD

**Issue by duartejc** [jhipster/generator-jhipster#1358]
Would it be interesting to have support for messaging with JMS? I have built a Spring Boot application with a few functionalities which I think would be great to add in JHipster.
Let me know if you'd like to have such integration so that I could implement it.

**Comment by drissamri** [comment]
For what communication would the JMS support be though? What would be the use case for a basic JHipster generated application to use JMS?

**Comment by duartejc** [comment]
I've already implemented JMS (for the customer ) for real-time notifications. An event sends a message to specific queues which are listened by users' queues . Once an user connects to the system, all the messages sent to queue are send to user through WebSockets. Another use case should be chat. 
Considering that many SPAs have such requirements, I think it would be nice to implement JMS.

**Comment by wzomer** [comment]
+1 @duartejc

**Comment by pnreddysvu** [comment]
+1 for chat

**Comment by jdubois** [comment]
I didn't look at what Spring Boot provides for JMS, did you use it?
(and I'm supposed to be on the JMS expert group, shame on me!!)
Because I'm not sure we can add much value on top of it.

**Comment by duartejc** [comment]
As I know, Spring Boot provides support for JMS through the @EnableJms annotation. It seems a simple implementation. I've never used such implementation, but I've implemented messaging the same way with RabbitMQ and spring-rabbit module which fit well.

**Comment by jdubois** [comment]
OK, in that case we only add something if it adds something interesting on top of Spring Boot. Otherwise, the way it works is you add the normal Spring Boot annotation, as you quoted.
So at the moment we won't do anything more in JHipster, until we find something specific to do of course!
