### ISSUE TITLE
Project broken after upgrade to 2.7.0

### ISSUE THREAD

**Issue by balbler** [jhipster/generator-jhipster#1359]
Working project on 2.6.0
upgraded jhipster via NPM
ran yo jhipster in project root
Now if i regenerate a entity, all setters and getters except for collections and ID are just get() and set() as method name:
    public String get() {
        return meetingKey;
    }

    public void set(String meetingKey) {
        this.meetingKey = meetingKey;
    }

    public String get() {
        return confName;
    }

    public void set(String confName) {
        this.confName = confName;
    }

    public DateTime get() {
        return meetingStartTime;
    }

**Comment by balbler** [comment]
Just did a check, seems the JSON for entity generation was updated, now including the field fieldInJavaBeanMethod
is there some way to migrate correctly?

**Comment by jdubois** [comment]
You are correct, this is the cause of your issue, but I now I wonder why I added that field -> I might remove it in the next version, and I'm keeping your ticket open to remember this.
The easiest way for you to upgrade is to add that field manually -> normally I generate missing attributes, when possible, during the upgrades, and here I forgot this one. Once again, I'll need a closer look.

**Comment by balbler** [comment]
no problem, i confirmed by adding the field and now all is working again.
thanks for the swift response!

**Comment by jdubois** [comment]
Oh yes, it's in the comments, it's because of this incredibly stupid JavaBean spec (see http://stackoverflow.com/questions/2948083/naming-convention-for-getters-setters-in-java ).
Now I remember banging my head on this for a couple of hours!!
