### ISSUE TITLE
Add Support to Auto Update the Copyright Headers each Year

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#13617]
##### **Overview of the feature request**

Inspired from https://github.com/jhipster/jhipster-online/issues/276. I've seen us updating copyright headers each year manually which is time consuming. Maybe we can automate it in every repository. 

I would suggest creating a [GitHub actions template](https://docs.github.com/en/enterprise-server@2.22/actions/learn-github-actions/sharing-workflows-with-your-organization) for this so that it can be easily shared across the JHipster organization. If this is agreed, I can submit a pull request. 😄 

##### **Motivation for or Use Case**

Automate the copyright header update. 

##### **Related issues or PR**

https://github.com/jhipster/jhipster-online/issues/276 and https://github.com/jhipster/jhipster-online/pull/275

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@pascalgrimaud : For this one, I don't think I have permission to create repositories under the JHipster organization. Would you be able to give that to me or you could create the `.github` repo so that I could create the template there. 😄

**Comment by pascalgrimaud** [comment]
@SudharakaP : I can create the repo. Which is the name ?

**Comment by SudharakaP** [comment]
> @SudharakaP : I can create the repo. Which is the name ?

@pascalgrimaud : The repo should be named `.github`

**Comment by pascalgrimaud** [comment]
@SudharakaP : the repo already exists -> https://github.com/jhipster/.github :-D

**Comment by mshima** [comment]
Would be nice to check if there are files missing copyright.

**Comment by SudharakaP** [comment]
> Would be nice to check if there are files missing copyright.

Yeah, there's quite a few in `jhipster-online` which is missing copyright which I am gonna do another PR later, but I am not sure if we can do some kinda global temple solution for that as in certain repos there might be some files which need not have copyright. 🤔

**Comment by mshima** [comment]
Fail on missing and add a badge.
Adding the copyright is more difficult.

**Comment by SudharakaP** [comment]
> Fail on missing and add a badge.
> Adding the copyright is more difficult.

@mshima : Could you explain a little bit more on what you mean by adding a badge? I am not sure how to do that exactly. 🤔

**Comment by mshima** [comment]
Badge for the workflow:
![Copyright Status](https://github.com/jhipster/jhipster-online/workflows/Copyright%20Update/badge.svg)
