### ISSUE TITLE
Using 2 Space Indentation as Default in Prettier for yml Files

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#13612]
##### **Motivation for or Use Case**

This is motivated from the discussion at https://github.com/jhipster/jhipster-online/pull/275. We currently use [4 spaces as prettier default](https://github.com/jhipster/generator-jhipster/blob/ff54054055990360b0c94eee2cf873b77ab22e72/.prettierrc#L5). So all our `yml` files in the generator has 4 space indentation. However in the generated projects we use [2 spaces](https://github.com/jhipster/generator-jhipster/blob/ff54054055990360b0c94eee2cf873b77ab22e72/generators/common/templates/.prettierrc.ejs#L5).

##### **Suggest a Fix**

Suggest using a 2 space width for all `yml` files in the generator. Let me know your thoughts? 

@jhipster/developers 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
+1 for 2 spaces everywhere except maybe for java... Could we also agree to rename `.yml` extensions to `.yaml` or are there some tools that don't support it ?

**Comment by SudharakaP** [comment]
> +1 for 2 spaces everywhere except maybe for java... Could we also agree to rename `.yml` extensions to `.yaml` or are there some tools that don't support it ?

I think the only `.yaml` files we have are `app.yaml` and `dispatch.yaml` within the GAE sub-generator. I don't know if GAE supports `yml` extension as well; the documentation doesn't seem to mention it. Let me run a test sometime. 🤔

**Comment by SudharakaP** [comment]
@PierreBesson : Ops, I read your comment wrongly; you are asking for the conversion other way around (`.yml` to `.yaml`). Sorry. 😄

**Comment by mraible** [comment]
I've seen `.yaml` a few times recently and I have to say I prefer `.yml` instead. This is probably in large part because of Spring Boot and how they've used this convention.

**Comment by PierreBesson** [comment]
In my experience, `.yaml` is preferred by most projects (ansible, kubernetes,...). `.yaml` is also recommended in their official docs (https://yaml.org/faq.html). Also the spring boot docs, now mention both `.yml` and .yaml` in their examples.
