### ISSUE TITLE
Upgrade R2DBC implementation for Spring Boot 2.4

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13613]
##### **Overview of the issue**

From the [Spring Boot 2.4 release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes):

> The core infrastructure of R2DBC has moved to Spring Framework with a new `spring-r2dbc` module. If you are using this infrastructure, make sure to migrate deprecated access to the new core support.

I'm creating this as a separate issue than the [main Spring Boot 2.4 issue](https://github.com/jhipster/generator-jhipster/issues/13237) because it requires more work than expected and I want to add a bug bounty to it.

##### **Motivation for or Use Case**

Our current implementation of R2DBC does not work with Spring Boot 2.4. [This PR](https://github.com/jhipster/generator-jhipster/pull/13551) is tracking Spring Boot 2.4 support and apps with R2DBC do not start successfully because the expected `DatabaseClient` is not available.

##### **Reproduce the error**

`npm link` in the `spring-boot-2.4` branch, then create an app with the following `.yo-rc.json` and try to start it.

```json
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "reactive": true,
    "baseName": "sampleWebfluxPsql",
    "packageName": "tech.jhipster.sample",
    "packageFolder": "tech/jhipster/sample",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "buildTool": "maven",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "testFrameworks": ["gatling", "cypress"],
    "serverPort": "8080",
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "creationTimestamp": 1596513172471,
    "jwtSecretKey": "ZjY4MTM4YjI5YzMwZjhjYjI2OTNkNTRjMWQ5Y2Q0Y2YwOWNmZTE2NzRmYzU3NTMwM2NjOTE3MTllOTM3MWRkMzcyYTljMjVmNmQ0Y2MxOTUzODc0MDhhMTlkMDIxMzI2YzQzZDM2ZDE3MmQ3NjVkODk3OTVmYzljYTQyZDNmMTQ=",
    "blueprints": [],
    "otherModules": [],
    "jhipsterVersion": "7.0.0-beta.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "pages": [],
    "serviceDiscoveryType": false,
    "messageBroker": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": true
  }
}
```

##### **Suggest a Fix**

Upgrade to non-deprecated classes.

##### **JHipster Version(s)**

`spring-boot-2.4` branch

**Comment by mraible** [comment]
@pascalgrimaud I think we should remove the enhancement label. This is a major blocker for Spring Boot 2.4 support.

**Comment by pascalgrimaud** [comment]
Yes we can change of course. Is it a feature or a bug ?

**Comment by mraible** [comment]
It's a bug since our R2DBC implementation works fine with Spring Boot 2.3.

**Comment by ecostanzi** [comment]
Hello! I can give this a try. I started fixing the generated project here https://github.com/ecostanzi/jhipster-r2dbc-spring-boot-24 and at least it starts now. 2 questions:
- should I create the branch starting from `spring-boot-2.4`?
- which jdl do you suggest to use for a full set of entities?

**Comment by mraible** [comment]
Yes, starting from the `spring-boot-2.4` branch would be best. You don't need any entities to start since the errors happen without any. I've been testing with the `webflux-psql` sample.

**Comment by mraible** [comment]
@ecostanzi I read your comment wrong and didn't realize you had startup working. The `webflux-psql` job uses the `sql` entities. From `test-integration/scripts/11-generate-entities.sh`, that is:

```
    moveEntity BankAccount
    moveEntity Label
    moveEntity Operation

    moveEntity FieldTestEntity
    moveEntity FieldTestMapstructAndServiceClassEntity
    moveEntity FieldTestServiceClassAndJpaFilteringEntity
    moveEntity FieldTestServiceImplEntity
    moveEntity FieldTestInfiniteScrollEntity
    moveEntity FieldTestPaginationEntity
    moveEntity FieldTestEnumWithValue

    moveEntity EntityWithDTO
    moveEntity EntityWithPaginationAndDTO
    moveEntity EntityWithServiceClassAndPagination
    moveEntity EntityWithServiceClassPaginationAndDTO
    moveEntity EntityWithServiceImplAndDTO
    moveEntity EntityWithServiceImplAndPagination
    moveEntity EntityWithServiceImplPaginationAndDTO

    moveEntity MapsIdUserProfileWithDTO
```

**Comment by mraible** [comment]
@ecostanzi Can you please create a PR against the `spring-boot-2.4` branch with your enhancements?

**Comment by ecostanzi** [comment]
@mraible I've just created a draft PR. Fixing the entity repository is taking me longer than expected. I'm trying to find a way to update the whole entity without [iterating on all its fields](https://github.com/ecostanzi/jhipster-r2dbc-spring-boot-24/blob/master/src/main/java/tech/jhipster/sample/repository/BlogRepositoryInternalImpl.java#L140).

**Comment by DanielFran** [comment]
Closed by #13739

@ecostanzi Do not forget to claim the bug-bounty

**Comment by ecostanzi** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/32800

**Comment by pascalgrimaud** [comment]
@ecostanzi : approved
