### ISSUE TITLE
React cypress e2e test is flaky.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#13639]
##### **Overview of the issue**

React cypress tests are failing randomly.
https://github.com/jhipster/generator-jhipster/actions?query=workflow%3AReact+is%3Afailure

##### **Motivation for or Use Case**

Have CI builds to don’t fail so often.

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
So e2e are still flaky, using Protractor or Cypress, it is still the same...lol

**Comment by avdev4j** [comment]
I have suggested adding Cypress Dashboard to find flaky test https://docs.cypress.io/guides/dashboard/flaky-test-management.html#Flake-Detection

As an OSS project, we can have unlimited test records.

I have already asked for an account for JHipster. I'm waiting for an answer and then I would like to add this to some workflows.

**Comment by mshima** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/13825
