### ISSUE TITLE
[Daily-builds] Sometimes Cypress failed to make a connection to the Chrome DevTools Protocol

### ISSUE THREAD

**Issue by nassimerrahoui** [jhipster/generator-jhipster#13635]
##### **Overview of the issue**

Some daily builds with Cypress have this error `Cypress failed to make a connection to the Chrome DevTools Protocol: ECONNREFUSED at TCPConnectWrap.afterConnect` like here : https://github.com/hipster-labs/jhipster-daily-builds/runs/1733523794?check_suite_focus=true

##### **Motivation for or Use Case**

N/A

##### **Reproduce the error**

https://github.com/hipster-labs/jhipster-daily-builds/runs/1733523794?check_suite_focus=true

##### **Related issues**

N/A

##### **Suggest a Fix**

This bug seems to be fixed here https://github.com/cypress-io/cypress/pull/14348 and added to Cypress 6.3
We can upgrade Cypress version to 6.3

##### **JHipster Version(s)**

v7.0.0-beta.1

##### **JHipster configuration**

https://github.com/hipster-labs/jhipster-daily-builds/runs/1733523794?check_suite_focus=true

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Just closed the dependabot PR https://github.com/jhipster/generator-jhipster/pull/13621 because it failed every test.
Looks like a regression.

**Comment by pascalgrimaud** [comment]
Specially the JDLMS builds are not enough stable

**Comment by mshima** [comment]
@nassimerrahoui was updated to 6.4.0. Should we close this?

**Comment by nassimerrahoui** [comment]
Closing this issue because cypress was updated to 6.4.0.

**Comment by pascalgrimaud** [comment]
As the original issue is resolved, we can closed it.
But all daily builds are still broken, for another reason... maybe communication between microservices
