### ISSUE TITLE
Upgrade to webpack 5 for Angular

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13642]
##### **Overview of the feature request**

We need webpack 5 support for Angular in order to support microfrontends (#10189) with [module federation](https://webpack.js.org/concepts/module-federation/). Support for Vue and React was added in https://github.com/jhipster/generator-jhipster/pull/13615. 

From @mshima:

> At angular part, we should wait for angular-cli to support webpack@5.
> Currently the only way is to use yarn resolution and force it.
> IFAIK our angular implementation is ready.
> Dependencies without webpack@5 is angular-cli and ng-bootstrap.

##### **Motivation for or Use Case**

Webpack 5 will allow us to move away from a monolithic UI to a microfrontends one, where each microservice has its UI packaged with it.

##### **Related issues or PR**

#10189, #13615

**Comment by mshima** [comment]
I will create a howto to use webpack 5 with angular.

**Comment by mshima** [comment]
Update jhipster with PR https://github.com/jhipster/generator-jhipster/pull/13649.
Run:
```
npm install -g yarn@latest
jhipster jdl bug-tracker.jh --client-package-manager yarn --skip-jhipster-dependencies
yarn add webpack@latest
yarn add copy-webpack-plugin@latest
```
Add to package.json:
```
  "resolutions": {
    "webpack": "^5.16.0"
  },
```
Run:
```
yarn install
yarn start
```

To make sure only 1 webpack is installed and is version 5:
```
find node_modules | grep node_modules/webpack/package.json
cat node_modules/webpack/package.json | grep version
```

**Comment by mshima** [comment]
Remove the bounty since this is the a followup to https://github.com/jhipster/generator-jhipster/pull/13615

**Comment by mraible** [comment]
@mshima Thanks for documenting it! I'd like to leave this open until it can be done with npm.

**Comment by mraible** [comment]
FWIW, Angular CLI 11.1 seems to have a few updates related to Webpack 5.

**Comment by mraible** [comment]
I checked and Angular CLI 11.1 still uses webpack 4.

```
➜  foo git:(master) ✗ find node_modules | grep node_modules/webpack/package.json
cat node_modules/webpack/package.json | grep version
node_modules/webpack/package.json
    "type": "version",
  "version": "4.44.2",
```

**Comment by Tcharl** [comment]
I know that it could looks like a hack, but what about [overriding dependency with yarn](https://github.com/module-federation/module-federation-examples/tree/master/angular11-microfrontends) as they recommend in the [webpack 5 angular issue](https://github.com/angular/angular-cli/issues/17555)?
Also npm seems to [recommend](https://github.com/npm/rfcs/blob/latest/accepted/0009-package-overrides.md) the use of a [third party library](https://www.npmjs.com/package/replace-deep-dep) to achieve the same.

It would ensure that Jhipster is supporting webpack 5 to ease the merge once they'll be ready

**Comment by wmarques** [comment]
As we switched onto Angular CLI, I think we should wait to have Webpack 5 fully supported by the CLI. Users can already opt-in as @Tcharl mentioned, but I'm not in favor of adding this in generated apps.

**Comment by pascalgrimaud** [comment]
keep it

**Comment by mraible** [comment]
Keep it open. Angular 12 and Module federation is on the horizon!

**Comment by mshima** [comment]
Waiting for angular12 support at ng-bootstrap.
