### ISSUE TITLE
Document generator breaking changes that a blueprint should address to support v7.x

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#13650]
##### **Overview of the feature request**
Generator API has changed a lot between `v6.10x` and `v7.x` release. It would be good to document the breaking changes and provide an upgrade path so that blueprint owners can do appropriate changes before the final `v7.x` release.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Not only documentation, I think these repo needs to be updated too:
- https://github.com/jhipster/generator-jhipster-blueprint
- https://github.com/jhipster/generator-jhipster-module

**Comment by pascalgrimaud** [comment]
keep it opened, as the documentation is important

**Comment by pascalgrimaud** [comment]
keep it

**Comment by atomfrede** [comment]
Keep it open

**Comment by vishal423** [comment]
Closing as I don't see anyone working on it and don't require for `svelte` blueprint
