### ISSUE TITLE
JHipster base alongside spring batch, Spring JMS and spring webservices

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1365]
I'm using Jhipster in a large project that would have batch file processing, soap webservices and JMS queue,  I would like to reuse the core Java part generated by jHipster for batch and webservice.What would be the best approach to do this

Have a EAR with separate modules for web, webservice, batch etc
or 
Integrate everything into the Jhipster generated base and have a single WAR(will this have any implications?)

Any guidance guys?

**Comment by jdubois** [comment]
- First time I hear of EAR files for years, do they still exist? I just wouldn't recommend using an app server for JHipster, it's useless and support costs a lot of $$$
- The most important part of "modules" is to have a clean and modular codebase -> in the end, putting everything in the same WAR is the same as putting everything in an EAR
- I've done several apps with more than 1,000,000 LOC of custom code, no issue at all
- You could also have a "micro service" approach and be all hype, but of course those require remote REST calls, so it costs ressources (EJB 1 anyone?)
- You could also ask this on StackOverflow to have a broader audience

**Comment by deepu105** [comment]
Hi @jdubois , Thanks, Yes unfortunately in some of the enterprise world (Some traditional ones in that) there are still EARs, mostly becoz of Axis WS, spring batch etc :smile: 
And since they have Jboss application server licence it would be gigantic task for me to convince not to have App servers, but then we need clusters and all those things which are more stable in these kind of setup. I know those can be done without an App server, but difficult to convince clients IT as they have more traditional view of things :P
Anyway I have almost decided our approach as below.
Have a single WAR with all integrated in it (Spring WS, Spring JMS and Spring scheduler for batch jobs)

**Comment by lokkju** [comment]
Bringing a basic level of Spring Batch support based on spring-batch-starter-web would be one way to get spring batch support cheaply.  Essentially just auto-discover jobs and allow the launching of them via a web service/admin page.
