### ISSUE TITLE
Warn user when generating in a non-empty directory

### ISSUE THREAD

**Issue by jeffsheets** [jhipster/generator-jhipster#1368]
It would be nice to provide the user with a message when ```yo jhipster``` is run in a non-empty directory. I've done this a couple of times now and it is easily fixed by removing the files by timestamp, but it would be nice if JHipster warned me at the start of the process.

This is more of an enhancement request than a bug, but I'm not sure of the best way to address it. I'm happy to code the pull request if we agree this is needed and how to fix it.

- The simplest code change would be a warning console.log early in the process, instructing the user they are in an empty directory and to ctrl-c if they'd like to cancel.
- Or add as the first or 2nd prompt when an empty directory is detected. Something like ```The current directory is not empty. We recommend running JHipster from an empty directory. Do you want continue or cancel?```
- Or a prompt after the application name is given, saying something like ```The current directory is not empty. Would you like JHipster to create and run in a new directory named {appName}?``` This would be a bit more complex to get it perfect.

Thoughts? I suppose a 4th option would be to just update the "Creating an application" documentation to show a ```mkdir sampleApp``` and ```cd sampleApp``` as the first two lines.
http://jhipster.github.io/creating_an_app.html

**Comment by cselti** [comment]
The JHipster based on the http://yeoman.io/ generator, which is a developer tool, and the most yeoman generator also will not ask like this. Usually the most most developer tool will not ask, that "really want to rebuild your project?" or anything like this. Using a version controlling system in a proper way can help the developers to revert an unwanted modification.

**Comment by jdubois** [comment]
Other generators don't do it, and I want to stick with the "classical" usage of Yeoman (I agree with @cselti on this)

**Comment by jeffsheets** [comment]
Ok. I can understand that. I would still recommend a documentation note to first create a new directory before running ```yo jhipster```. Especially since this can be the first introduction to yeoman for many java developers.

**Comment by dancancro** [comment]
@jeffsheets.  I do that too.  Another line in the docs would be appreciated by the uninitiated.  +1.

**Comment by jdubois** [comment]
You are correct, I'm adding this in the documentation!
