### ISSUE TITLE
Vue client doesn't change JHipster mascot when generating new apps

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13689]
##### **Overview of the feature request**

React and Angular pick a random JHipster mascot when generating new apps. The Vue client seems to always generate the same one. 

![image](https://user-images.githubusercontent.com/17892/105530145-9f2f4800-5ca4-11eb-9119-986c470a794b.png)

##### **Motivation for or Use Case**

The Vue client generation process should be similar to Angular and React.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@mraible I generated a Vue app and I had this JH mascot

![image](https://user-images.githubusercontent.com/9989211/105630027-caea3380-5e46-11eb-8f82-70b9b84c8a0f.png)

**Comment by mshima** [comment]
It isn’t random, it’s basename on application basename hash.

**Comment by pascalgrimaud** [comment]
We could add new mascots, recently added by @ascelineboullen in jhipster-artwork project

**Comment by mraible** [comment]
OK, I didn't realize that using the same app name would result in the same
image. This issue can be closed.

**Comment by pascalgrimaud** [comment]
Ok then, we could create another ticket for adding new mascots so :)
