### ISSUE TITLE
DB Page "Not Found" Error For Reactive Microservices

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#13699]
##### **Overview of the issue**

Signing into the gateway app of a reactive microservices as the admin. Navigating to the database menu, one will get the followings

```
Error page!
The page does not exist.
```
The error is observed with Matt Rabbie's sample codes of his article https://developer.okta.com/blog/2021/01/20/reactive-java-microservices

##### **JHipster Version(s)**

Release 7.0.0-beta.1

##### **JHipster configuration**
```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36-1562)
OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

git version 2.28.0

node: v15.5.0

npm: 7.3.0

yeoman: 2.0.0

Docker version 19.03.12, build 48a66213fe

docker-compose version 1.8.0, build unknown
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Please see the entity configuration in Matt's article https://developer.okta.com/blog/2021/01/20/reactive-java-microservices

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
This is similar to a problem we discovered with the micronaut blueprint. For non reactive applications the servlet for h2 is registered (via our library). This does not work for reactive applications. We could it like in the [micronaut case and start the h2 console ](    private static void startH2WebConsole() {)webserver (would need another port, but that can be changed in the frontend).
