### ISSUE TITLE
Implicit HTTPStatus 201 Location Handling

### ISSUE THREAD

**Issue by roded** [jhipster/generator-jhipster#1369]
Hi,
Is there a reason that the 201 HTTP status + URI returned by the entity resources' create() methods is not handled implicitly?

Currently (unless I'm missing something), in order to get the object of a newly created entity, one would have to read the location response header and manually issue another request.

    var thiz = this;
    EntityResource.update(newEntity, function (response, headers) {
        var uri = headers('Location');
        $http.get(uri).then(function (response) {
            thiz.entity = response.data;
        });
    });

Is there a better way of accomplishing this out-of-the-box?

**Comment by cselti** [comment]
The source of the problem will be on the server side - check the logs of your backend.

**Comment by gzsombor** [comment]
Unfortunately a recent change in the server side introduced this functionality, which I think a very inconvenient. You can easily change back to the original, modifying the *Resource.java from
 *ResponseEntity.created(...).build()* to  *ResponseEntity.created(...).body(result)*
And of course, modifying the return type from ResponseEntity<Void> to ResponseEntity<<%= entityClass %>> . As I've done it in this change: https://github.com/jhipster/generator-jhipster/commit/1b00293e17b93ab5d9f887c87faa9df475a604cf#diff-6df43229eebc57022a615642394d1c50R49

**Comment by roded** [comment]
What are the implications of such a change on the migration process of existing projects to newer JHipster versions? 
(somewhat off topic, this issue has been bugging me for a while: are there best practices for changing JHipster generated resources to allow for easier migration late on? is a manual merge the best way to handle migrations?)

**Comment by gzsombor** [comment]
You can easily fork jhipster, and maintain your own changes on top of the official one. I've already doing it, my fork contains ~20 changeset. I've regularly rebase my fork - it's really trivial, if you know git, which I've assume - and time-to-time I regenerate my applications with the new templates. That could be tricky, if you've already heavily customized your app. Which is, I think, unavoidable when you need more than the basic CRUD functionality. So manual merge is our only hope. Or you can stop following the changes, which is perfectly fine, if you accumulated enough knowledge, how to fix the occasional bugs in the infrastructure code

**Comment by roded** [comment]
That's an interesting way to go about it, though the overhead is quite high I think. 
I wonder if there isn't a decent way of facilitating easier migrations by jhipster itself though; perhaps a defined directory structure in which there's a tree for generated resources and another for proprietary code. This way migrating would mean fixing compilation issues instead of manually merging code (javascript would still be difficult short of a very good IDE with a working angular plugin).

Anyway, back to the main issue, if anyone could comment on whether the new ResponseEntity format  is here to stay, or whether there's a possibility to handle the returned object URI via jhipster $http interceptor or whatnot, that would be great.

**Comment by jdubois** [comment]
Sorry guys, I didn't make this change on purpose, and I didn't know I was breaking anything -> normally I take care of not breaking stuff, and otherwise I document it, of course. So this was not intentional, and not a normal change.
For me the correct way to handle the creation of an entity is what we do -> send a 201 header with the location of the new entity, and not send the new entity. So this looks good to me, unless proven wrong of course!
