### ISSUE TITLE
Generated Query Services and Integration Tests do not use custom IDs given to Entites

### ISSUE THREAD

**Issue by mdromazos-drive** [jhipster/generator-jhipster#13695]
##### **Overview of the issue**

When a importing an entity with the jhipster import-jdl command and with filtering turned on, the generated EntityQueryService does not use the correct id name.  The same thing is happening in entities that have relationships to entities with custom Ids.

For Example:
* I Created an entity with the following code given at the bottom of this ticket using the `jhipster import-jdl` command
* Then the following snippet is generated in the WorkoutSessionQueryService
`
            if (criteria.getRowidWorkoutSession() != null) {
                specification = specification.and(buildRangeSpecification(criteria.getRowidWorkoutSession(), WorkoutSession_.id));
            }
`

There is also an issue where the custom id is not being used when generating the rest Integration Tests. 

It is an easy workaround to manually change the code.  Though it gets tedious to do with many entities and if you extend an entity later and have to overwrite the files.

##### **Motivation for or Use Case**

I am currently integrating Jhipster with my API.  My data model is already created and I have a different name for my ids of my tables.  I need to use the custom Id feature in order to integrate Jhipster

##### **Reproduce the error**

* Create a jhipster appliation using the jdl file using the code I provided above

##### **Suggest a Fix**

Update the code that generates the EntityQueryService classes to use the custom Id if one is provided

##### **JHipster Version(s)**

Jhipster 7 Beta-1

##### **JHipster configuration**

`

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)

git version 2.22.0

node: v15.5.0

npm: 6.14.10

yeoman: 3.1.1

Docker version 19.03.12, build 48a66213fe

docker-compose version 1.26.2, build eefe0d31

`
To provide all information we need, you should run `jhipster info` in the project root folder, and
copy/paste the result here.
The `.yo-rc.json` file generated in the root folder is mandatory for bug reports. This will help us to replicate the scenario.
You should remove any sensitive information like the rememberMe key or the jwtSecretKey key.
{
  "generator-jhipster": {
    "blueprints": [],
    "applicationType": "monolith",
    "baseName": "drive",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling", "cucumber"],
    "pages": [],
    "creationTimestamp": 1611354228721,
    "promptValues": {
      "packageName": "com.drive.fitness",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.drive.fitness",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": ["searchEngine:elasticsearch", "websocket:spring-websocket"],
    "websocket": "spring-websocket",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/drive/fitness",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1611359273000,
    "entities": [
       WorkoutSession
    ],
    "embeddableLaunchScript": false,
    "otherModules": []
  }
}

---
If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    applicationType monolith
    authenticationType oauth2
    baseName drive
    blueprints []
    buildTool maven
    cacheProvider ehcache
    clientFramework angularX
    clientPackageManager npm
    clientTheme none
    creationTimestamp 1611354228721
    databaseType sql
    devDatabaseType h2Memory
    dtoSuffix DTO
    embeddableLaunchScript false
    enableHibernateCache false
    enableSwaggerCodegen false
    enableTranslation false
    jhiPrefix jhi
    jhipsterVersion "7.0.0-beta.1"
    languages [en, fr]
    messageBroker false
    nativeLanguage en
    otherModules []
    packageName com.drive.fitness
    prodDatabaseType postgresql
    reactive false
    searchEngine elasticsearch
    serverPort 8080
    serviceDiscoveryType false
    skipClient false
    skipServer false
    skipUserManagement true
    testFrameworks [cypress, gatling, cucumber]
    websocket spring-websocket
    withAdminUi true
  }
  entities WorkoutSession
}

entity WorkoutSession {
  @Id rowidWorkoutSession Long
  workoutSessionStartTime LocalDate
  workoutSessionEndTime LocalDate
}
dto WorkoutSession
paginate WorkoutSession
service WorkoutSession with serviceClass
filter WorkoutSession  </pre>
  </details>

##### **Browsers and Operating System**

MacOS 11.1

- [x] Checking this box is mandatory (this is just to show you read everything)

P.S. I love this product, your team has done a great job, thanks!

**Comment by pascalgrimaud** [comment]
Thanks for opening this ticket @mdromazos-drive
But can you generate a sample project + sample JDL + provide all information of this sample, with your configuration too plz ?
No need your real project, just a sample, so it will help us to reproduce

As without your JDL, we can't guess your entities
Thanks in advance :)
