### ISSUE TITLE
Feature Request: Allow some VS Code files in .gitignore

### ISSUE THREAD

**Issue by egvimo** [jhipster/generator-jhipster#13715]
##### **Overview of the feature request**

Currently the `.gitignore` file is excluding the whole `.vscode` folder. However some files in this folder are worth to be shared. Like you do in this repository with the `launch.json` file.

##### **Motivation for or Use Case**

I suggest to change the `.gitignore` template to allow the common files:

```text
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
```

##### **Related issues or PR**

If you agree, I can create a PR for this feature request.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Thanks for proposing this, but I'd like more details on these files, as for me, there are specifics to each developers
Each dev use their own extensions etc

**Comment by atomfrede** [comment]
This is what [gitignore.io](https://www.toptal.com/developers/gitignore/api/visualstudiocode) generates for vs code

```
.vscode/*
!.vscode/tasks.json
!.vscode/launch.json
*.code-workspace
```

Not sure if sharing launch configs makes sense/works well. But for extensions and settings these seem personal things to me.

**Comment by egvimo** [comment]
For me [it generates the following](https://www.toptal.com/developers/gitignore/api/vscode):

```text
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace
```

Also [GitHubs templates](https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore) suggests the same.

The `extensions.json` contains [recommendations](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) for the extensions, but every developer is free to apply or deny the installation.

The `settings.json` is very good to share settings for linters and code formatting tools to enforce the language rules used for the repositoy. Also the [JHipster Docs recommends](https://www.jhipster.tech/configuring-ide-visual-studio-code/) adding some settings to the `settings.json` which should be shared among the developers.

You could even go a step further and generate the `settings.json` with the generator to provide these recommendations. ;)

**Comment by atomfrede** [comment]
Seems like gitignore makes a difference between vscode and visual studio code 😁 

So we could recommend to have e.g. Java extension and jdl extension for example? Sounds like a good thing to have.

**Comment by egvimo** [comment]
Yes, you can recommend general extensions like Prettier or JDL for all apps and specific ones like Angular for Angular apps.

**Comment by mshima** [comment]
IMO this should go into a blueprint, so customizations can be done.
I have plans to create one for eclipse.

**Comment by egvimo** [comment]
How about to change the `.gitignore` file directly here? So that the VS Code files can be used without a blueprint.

I can create a PR for that.

And the rest of the additional files would be in the blueprint.

**Comment by atomfrede** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/13836
