### ISSUE TITLE
Couchbase Builds are broken in jhipster-daily-builds

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13737]
##### **Overview of the issue**

All JDLMS builds are [failing in jhipster-daily-builds](https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/511555517).

It seems to be related to [YAML parsing](https://github.com/hipster-labs/jhipster-daily-builds/runs/1767751644?check_suite_focus=true#step:11:1073):

<img width="969" alt="Screen Shot 2021-01-26 at 2 05 55 PM" src="https://user-images.githubusercontent.com/17892/105905401-9d84bd80-5fdf-11eb-9aa7-9fac1a19f218.png">

##### **Motivation for or Use Case**

All builds should pass in jhipster-daily-builds as we get closer to a release.

**Comment by kaidohallik** [comment]
This build was ran 13 hours ago, fix for this error, #13725, was applied 12 hours ago. So this is hopefully fixed.

**Comment by mraible** [comment]
@kaidohallik Cool! I just triggered a new build. https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/511555517

**Comment by mraible** [comment]
@kaidohallik All JDLMS actions are passing now! 

We still have Couchbase failures that seem to be related to EJS.

https://github.com/hipster-labs/jhipster-daily-builds/runs/1766840804?check_suite_focus=true

<img width="1189" alt="Screen Shot 2021-01-26 at 3 43 24 PM" src="https://user-images.githubusercontent.com/17892/105915797-5d2c3c00-5fed-11eb-96e2-0ed80c17df4d.png">

**Comment by mshima** [comment]
Dúplice of https://github.com/jhipster/generator-jhipster/issues/12300 and https://github.com/jhipster/generator-jhipster/issues/13544.
