### ISSUE TITLE
Why entity generator don't use pagination directive?

### ISSUE THREAD

**Issue by wzomer** [jhipster/generator-jhipster#1374]
(Google translate help)

1. Why entity generator don't use pagination directive?
2. Why pagination directive use the "angularAppName" in your name? Others directives don't use...

Thanks!

**Comment by jdubois** [comment]
1. yes it should use it
2. it uses the name of your app, because this is a directive specific for your project

I tried to use another pagination directive, but they are all quite complex to use, and we only needed something very simple

**Comment by geraldhumphries** [comment]
@jdubois I was about to open a similar issue. Pagination directives were added in [this commit](https://github.com/jhipster/generator-jhipster/commit/b9c696df53dbd48977a8fc599b41fa84372f8d91) but were never used. When generating an entity the following code is used for the pagination controls:

```
<nav>
    <ul class="pagination">
        <li ng-show="links['first'] >= 0" ng-click="loadPage(links['first'])"><a>&lt;&lt;</a></li>
        <li ng-show="page > 0" ng-click="loadPage(links['prev'] || 0)"><a>&lt;</a></li>
        <li ng-show="page > 1" ng-click="loadPage(page - 2)"><a>{{page - 1}}</a></li>
        <li ng-show="page > 0" ng-click="loadPage(page - 1)"><a>{{page}}</a></li>
        <li class="active"><a>{{page + 1}}</a></li>
        <li ng-show="page < links['last']" ng-click="loadPage(page + 1)"><a>{{page + 2}}</a></li>
        <li ng-show="page < links['last'] - 1" ng-click="loadPage(page + 2)"><a>{{page + 3}}</a></li>
        <li ng-show="links['next']" ng-click="loadPage(links['next'])"><a>&gt;</a></li>
        <li ng-show="links['last'] > 0" ng-click="loadPage(links['last'])"><a>&gt;&gt;</a></li>
    </ul>
</nav>
```

With a small update (replacing `class="<%=angularAppName%>-pagination"` with `class="pagination"` in `scripts/components/form/_pagination.html`), that code block can be replaced with `<<%=slugifiedBaseName%>-app-pagination />`. I have not tested it through the generator (just in my app), and I assume the simple pager can be replaced with `<<%=slugifiedBaseName%>-app-pager />` after a similar update.

I think his second question about the directive names is also something to reconsider. There are many other directives in JHIpster and none of them use the app name in the title. Maybe replace it with "jhipster" or "jh".

**Comment by deepu105** [comment]
Actually since we include ui bootstrap already we should see if we can use
the pagination directive from them

**Comment by geraldhumphries** [comment]
Bootstrap's pagination directive looks like this:

`<uib-pagination total-items="totalItems" ng-model="currentPage" max-size="maxSize" class="pagination-sm" boundary-links="true" rotate="false" num-pages="numPages"></uib-pagination>`

We will need to refactor PaginationUtil to add number of pages, but we can remove the LINK header and the ParseLinks service which simplifies things a lot. This also solves the PaginationUtil issue mentioned in #2387 and lets us refactor the search query out of the URI.

**Comment by geraldhumphries** [comment]
It looks like using the Link header is best practice for APIs, so it should remain even if we stop using it.

**Comment by deepu105** [comment]
Did you try the uib directive in Jh app does it work? If so you  can do a
PR?

**Comment by geraldhumphries** [comment]
It does work. I am working on a PR right now.

**Comment by geraldhumphries** [comment]
It does work. I am working on a PR right now. A few questions:

1. For the simple pager, uib provides a pager directive with "Previous" and "Next", but with no "First" and "Last". The current functionality can be copied by simply using the regular pagination directive with `max-size="0"`, but I do not see a point in ever choosing this over full pagination. Bootstrap's pager is different enough that there is a point to it being in the generator. If you want the pager buttons to say "Previous" and "Next" then I will also need to figure out i18n support.

1. Here is a paginator that looks and works almost exactly like the current one:
    ```
<pagination class="pagination" total-items="totalItems" ng-model="page" ng-change="loadAll()"
    previous-text="&lsaquo;" next-text="&rsaquo;" first-text="&laquo;" last-text="&raquo;"
    items-per-page="itemsPerPage" max-size="5" boundary-links="true"></pagination>
    ```
    if I configure these setting globally in `paginationConfig` I think I can shorten it to:
    ```
<pagination class="pagination" total-items="totalItems" ng-model="page" ng-change="loadAll()"></pagination>
    ```
    Should I configure the paginator globally or leave it in the html?

1. I think the paging links should be moved out of the `table-responsive` div if we are using Bootstrap's pager. This will increase usability because the pager won't be hidden if the user has to scroll the table horizontally. For the full paginator, this can cause it to wrap on extra small screens unless the template is overridden with one that will hide certain buttons using Bootstrap classes.

**Comment by deepu105** [comment]
1. I havent used the simple pager myself so im not sure @jhipster/developers any comment on this? though I have always thought why someone would select the simple pager!
2. For config,I think it will nice to have it globally as one can override locally when required
3. I guess its better to have it outside as you suggest, for small devices personally im ok if it wraps neatly as it is the normal bootstrap behaviour

**Comment by jdubois** [comment]
@deepu105 simple pager if useful with Cassandra -> as you can't have the "size" of the data (unless you do a full scan), it's the only solution to use
Yes I'm fine with using the pagination from UI Bootstrap, @geraldhumphries your PR is welcome!

**Comment by geraldhumphries** [comment]
Here is an example of the pagination wrapping:
![pagination-wrapping](https://cloud.githubusercontent.com/assets/5278953/11401935/34ae873a-9363-11e5-86d3-e15302e33699.png)

Happens on my phone too. This can mostly be solved by using `.pagination-sm`, but that makes the buttons very small and kind of hard to hit on mobile. If this is unacceptable I will leave it inside `.table-responsive`. We do lose the niceties of having the pagination centered, outside of the scrolling div (screenshot is `.pagination-sm` inside a `.text-center` div) :

![pagination-sm-centered](https://cloud.githubusercontent.com/assets/5278953/11402053/ed560f38-9363-11e5-8d69-9c93c3deefdd.png)

For now, I will open a pull request with the pagination configured like the second screenshot.

**Comment by deepu105** [comment]
+1 from me and you can use the simple pager from bootstrap to replace our
simple pager as well
