### ISSUE TITLE
Okta password rules have changed. JHipster + Heroku needs updating.

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13768]
##### **Overview of the issue**

We have the following question in our Heroku integration, but if I enter `Password1`, it’s accepted, and I can’t log in afterward. So it's not working.

```
? Initial password for the JHipster Admin user. Password requirements: at least 8 characters, 
a lowercase letter, an uppercase letter, a number, no parts of your username.
```

I'm trying to find out what our new rules are.

##### **Motivation for or Use Case**

Password rules should reflect a password that will work with Okta.

##### **Reproduce the error**

```
jhipster jdl blog-oauth2
jhipster heroku
```

Then use `Password1` for the password.

##### **JHipster Version(s)**

v7 beta 1

**Comment by mraible** [comment]
If I reset my password and try to use `Password`, I get the following error:

```
This password was found in a list of commonly used passwords. Please try another password.
```

**Comment by mraible** [comment]
@dogeared Do you have any ideas for how the password logic for JHipster + Heroku + Okta could be improved? For example, maybe we should implement the one-time token feature like the Okta CLI has?

**Comment by atomfrede** [comment]
@mraible Maybe we could generate a random password and display it during generation, such that you have to copy it for first login?

**Comment by mraible** [comment]
@atomfrede That works for me!
