### ISSUE TITLE
Support for Neo4j / Spring Data Neo4j

### ISSUE THREAD

**Issue by vince-bickers** [jhipster/generator-jhipster#1378]
Hi guys

I'm the primary author of [Spring Data Neo4j 4.0](https://github.com/spring-projects/spring-data-neo4j/tree/4.0), and I'd really like to get involved with JHipster and add support for server-based Neo4j to go alongside the other NoSQL offerings like Mongo. I have already built a sample Spring-Boot app using JHipster and Neo4j, but it involved a lot of manual kludges to get it to work, as you can imagine :) It would be really cool to have this work "out of the box". 

I see there's already a jhipster-neo4j project available. Is the intention to migrate that into the main jhipster-generator code base?

**Comment by jdubois** [comment]
Hi!

- We've already had a sample project on using Neo4J https://github.com/jhipster/jhipster-neo4j-app but it didn't go as far as being ready to be merged.
- Neo4J has a very specific licensing model. I'd rather focus on "true" Open Source databases, and that's already a lot of work to maintain for me. If you can implement it, and if your code is easy to maintain, we can give it a try, but once again I will not spend a lot of time on it.

**Comment by vince-bickers** [comment]
Hi Julien, thanks for the quick response.

Understand about the licensing model of Neo4j. The interface I'm proposing would be agnostic with regard to commercial/enterprise Neo4j, as it would leverage the work we're currently doing on SDN 4.0, which doesn't care which flavour you're using and works equally well with either. This is more about generating the JPA-style annotations for the entity classes and the supporting infrastructure required for Neo4j.

Anyway, I will fork the generator-jhipster code base and take a look at how easy it would be to add support for server-based Neo4j based on SDN 4.0 annotations. If and when I have something working, you can have a look and decide whether you think its worthwhile integrating.

**Comment by jdubois** [comment]
OK, good luck to you, I know it's quite a lot of work to do! I'll do my best to merge it afterwards.

**Comment by conker84** [comment]
I guys what is the status of this?
@jdubois if i want get this, what is the best way to proceed?

**Comment by jdubois** [comment]
@conker84 as you can see, no answer for more than 2 years, so nobody works on this.
Since that time we have added the ability to do [modules](http://www.jhipster.tech/modules/marketplace) and that would probably be the best solution for you to implement this, as you won't depend on us.

**Comment by conker84** [comment]
I checked the [docs](http://www.jhipster.tech/modules/creating-a-module/) and for what I had understand a module is not a solution because there is only the "Post Entity creation hook" and a Neo4j java bean has it own annotations.
What do you think?

**Comment by jdubois** [comment]
Maybe you would need some new needles for this - depends on what the integration requires

**Comment by conker84** [comment]
A direct integration in the generator-jhipster could be a solution?

**Comment by pascalgrimaud** [comment]
> A direct integration in the generator-jhipster could be a solution?

I don't think so. It would be a lot of work for us, and few people asked Neo4j for the last 2 years.

If you need this, you can do a module, as suggested. With module, you can do what you want:
- use post entity hook and needles
- parsing entity file + replace
- replace the entire file

You are totally free. And if the module is a success, we can think about integrating directly to the generator-jhipster.

**Comment by flefevre** [comment]
Hello there,
we are a small research team in an academic laboratory and we are wondering if you succeed. We are looking for a jhipster generator compatible with Neo4j database. we have seen the example https://github.com/jhipster/jhipster-neo4j-app but it is old and jhispter has evolved !
Any idea on how to have jhispter and neo4j, a native graph database...
Thanks for your ideas

**Comment by jdubois** [comment]
Spring Data Neo4J has also evolved... I would just use it directly, there's not much other option anyway today.
