### ISSUE TITLE
Updating an entity with a relationship deletes all the fields in the other entity (React + Neo4j)

### ISSUE THREAD

**Issue by utnaf** [jhipster/generator-jhipster#13797]
Hey everyone! Thanks for the great job on JHipster!

##### Trying to update an entity with a relationship cause the other entity to be empty

When using Neo4j and React (at least happened to me with this combo) and with two entities with a OneToMany relationship (Foo - HAS_MANY -> Bar), the update of Bar with a Foo selected in the select box causes all Foo fields (except for the ID) to disappear.

##### **Motivation for or Use Case**

Updating an entity should not empty the related entity. Same setup but with Angular instead of React works fine.

##### **Reproduce the error**

So I created an app with React and Neo4j. Then I created two entities, let's say:

```
entity Exam {
	title String
}

entity Question {
	content String
}
```

and I related them

```
relationship OneToMany {
  Exam{questions} to Question{exam}
}
```

Then I create an Exam named "Foo", I create a Question and connect it with Foo using the select input, and I save.
Everything goes smoothly apparently.

<img width="943" alt="Screenshot 2021-02-01 at 21 35 36" src="https://user-images.githubusercontent.com/1318539/106515108-747b9580-64d5-11eb-8adf-7480f15ba336.png">

But when I got back to the exam

<img width="489" alt="Screenshot 2021-02-01 at 21 36 09" src="https://user-images.githubusercontent.com/1318539/106516507-6e86b400-64d7-11eb-88e7-edf0d344aee8.png">

The content of the entity is empty.

##### **Related issues**

Couldn't find any

##### **Suggest a Fix**

I think the bit that causes issues is `question-update.tsx:93-102`

```
<AvInput id="question-exam" type="select" className="form-control" name="exam.id">
  <option value="" key="0" />
  {exams
    ? exams.map(otherEntity => (
        <option value={otherEntity.id} key={otherEntity.id}>
          {otherEntity.id}
        </option>
      ))
    : null}
</AvInput>
```

Having the option value `{otherEntity.id}` leads to have a PUT request body like

```
{
  "id": "123",
  "text": "My first question",
  "exam": {
    "id": "456",
  }
}
```

The backend doesn't "refresh" the Exam entity so when it saves the question it just overwrite this json with the existing node on the db. This is my guess.

##### **JHipster Version(s)**

6.10.5

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    applicationType monolith
    authenticationType jwt
    baseName EntityMistery
    blueprints []
    buildTool maven
    cacheProvider no
    clientFramework react
    clientPackageManager npm
    clientTheme lumen
    clientThemeVariant primary
    creationTimestamp 1612207623633
    databaseType neo4j
    devDatabaseType neo4j
    dtoSuffix DTO
    embeddableLaunchScript false
    enableHibernateCache false
    enableSwaggerCodegen false
    enableTranslation true
    jhiPrefix jhi
    jhipsterVersion "6.10.5"
    jwtSecretKey "NTc2ZWFlMmY4Nzk3NjQ0NjFlMzMwYzJmNWQzNWI2MGVhMTgxNWVhNDU3MDNlNDJlMjM4Yjc5MzJhMjFkNTYyNzQ1OThmYmM5M2NjMDlhZmU1NmY5ZmRmZTE4MjZhOTliZDg4ZGZmZDc2NjMyYjIxYWVhMjNjOGVhNzA5ZmY3ZGU="
    languages [en, it]
    messageBroker false
    nativeLanguage en
    otherModules []
    packageName org.example
    prodDatabaseType neo4j
    searchEngine false
    serverPort 8080
    serviceDiscoveryType false
    skipClient false
    skipServer false
    skipUserManagement false
    testFrameworks []
    useSass true
    websocket false
  }

  entities Exam, Question
}

entity Exam {
  title String
}
entity Question {
  content String
}
relationship OneToMany {
  Exam{questions} to Question{exam}
}
  </pre>
  </details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Everything is in the JDL

##### **Browsers and Operating System**

MaxOS 11.1 - Chrome 88 and Opera 73

- [x] Checking this box is mandatory (this is just to show you read everything)

##### **JHipster Version(s)**

```
entity-mistery@0.0.1-SNAPSHOT ~/Test
└── generator-jhipster@6.10.5

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "clientFramework": "react",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "baseName": "EntityMistery",
    "buildTool": "maven",
    "databaseType": "neo4j",
    "devDatabaseType": "neo4j",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["it", "en"],
    "messageBroker": false,
    "nativeLanguage": "it",
    "prodDatabaseType": "neo4j",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "blueprints": [],
    "clientPackageManager": "npm",
    "clientTheme": "lumen",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1612211460960,
    "dtoSuffix": "DTO",
    "embeddableLaunchScript": false,
    "jhipsterVersion": "6.10.5",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "otherModules": [],
    "packageName": "org.example",
    "packageFolder": "org/example",
    "skipServer": false,
    "useSass": true,
    "entitySuffix": ""
  },
  "entities": ["Exam", "Question"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Exam {
  title String
}
entity Question {
  content String
}
relationship OneToMany {
  Exam{questions} to Question{exam}
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+21-CA (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+21-CA (build 11.0.9+11-LTS, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v14.15.1

npm: 6.14.10

yeoman: 3.1.1

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192

identical .jhipster/Exam.json
identical .jhipster/Question.json

**Comment by atomfrede** [comment]
So with angular and neo4j it works fine you say? Can you check the latest beta which contains some improvements regarding handling relations with neo4j?

**Comment by utnaf** [comment]
Hi @atomfrede, just tried `7.0.0-beta.1` and problem still there. 

Let me know if I can do any other tests!

**Comment by atomfrede** [comment]
Thanks. And with angular everything is okay?

**Comment by utnaf** [comment]
Yes, with angular this doesn't happen

**Comment by atomfrede** [comment]
Okay, so it seems like a react frontend issue.

**Comment by utnaf** [comment]
This is the main difference between React and Vue.

Recap: we have entity Exam and entity Question, related like: Exam - HAS_MANY - Question

When inserting/updating a Question we select an Exam to attach.

Request payload made by Angular

```
PUT /questions

{
  "id": "123",
  "text": "Answer me please",
  "exam": { 
    "id": "345",
    "name": "The First Exam",
    "date": "2020-02-03 14:38:03"
  }
}
```

Request payload made by React

```
PUT /questions

{
  "id": "123",
  "text": "Answer me please",
  "exam": { 
    "id": "345"
  }
}
```

Now, I don't know which one should be considered correct. The backend is basically overwriting all the Exam fields that come from the frontend. With angular it works because we are sending everything every time, but I think the correct solution should be just to send the exam ID and the backend should take care of the rest.

**Comment by atomfrede** [comment]
I agree. For neo4 I am not sure if thats possible (I remember some similar problem when we implemented that). Will try to have a look and double check with the neo4j/spring data team

**Comment by utnaf** [comment]
Sure, no hurry btw, I just came across this one while playing around with JHipster. Thank you!

**Comment by mshima** [comment]
> Request payload made by Angular
> 
> ```
> PUT /questions
> 
> {
>   "id": "123",
>   "text": "Answer me please",
>   "exam": { 
>     "id": "345",
>     "name": "The First Exam",
>     "date": "2020-02-03 14:38:03"
>   }
> }
> ```

That's only true from non-dto entities, dto only returns id (+ label) from the server. At least for imperative implementation.

So an alternative is to use PATCH.
Current implementation doesn't supports field removals since there is no undefined on java.
This PATCH problem could be fixed by https://github.com/jhipster/generator-jhipster/pull/12507#issuecomment-699032634.

**Comment by utnaf** [comment]
> > Request payload made by Angular
> > ```
> > PUT /questions
> > 
> > {
> >   "id": "123",
> >   "text": "Answer me please",
> >   "exam": { 
> >     "id": "345",
> >     "name": "The First Exam",
> >     "date": "2020-02-03 14:38:03"
> >   }
> > }
> > ```
> 
> That's only true from non-dto entities, dto only returns id (+ label) from the server. At least for imperative implementation.
> 
> So an alternative is to use PATCH.
> Current implementation doesn't supports field removals since there is no undefined on java.
> This PATCH problem could be fixed by [#12507 (comment)](https://github.com/jhipster/generator-jhipster/pull/12507#issuecomment-699032634).

That's good news! Thank for the info @mshima

**Comment by atomfrede** [comment]
Keep it open, I am in contact with neo4j for details. Spring data neo4j can't handle this for us we still might switch to patch if that helps (I don't know how our current patch implementation works exactly).

**Comment by atomfrede** [comment]
WIth the latest main branch I have a different behaviour. The payload looks like this (so no title for the exam). But the relation is not saved at all. 

![image](https://user-images.githubusercontent.com/203401/110426166-e8492900-80a5-11eb-96b1-b1ff82e85d11.png)

**Comment by atomfrede** [comment]
What I found when using this [sample](https://github.com/atomfrede/neo4j-jhipster-sample-13797) mapstruct warns about unmapped target properties: `warning: Unmapped target properties: "questions, removeQuestions".` When doing a debug and filling the `questions` property manually the relation is created and everything looks fine so far. Just have no good idea how to make sure the questions property is filled during mapping (would require some database query).

**Comment by atomfrede** [comment]
Has a chat with @meistermeier and we will change how relations work for neo4j. In short we try not create bidirectional relations similar to what we have in mongo when using embedded docs and furthermore it will increase performance :zap:

**Comment by michael-simons** [comment]
This should be fixable with our new projections support.

**Comment by meistermeier** [comment]
Have been thinking about this for a while now. Projections might not solve this.
IIRC the problem already starts with the correct creation of entities and relationships
```
relationship OneToMany {
  Exam{questions} to Question{exam}
}
```
The current logic within the code generator will create a bidirectional mapping between `Exam` and `Question`. There used to be a rule that says, no bidirectional relationships for store type _neo4j_ but there were some other changes that render this code useless.
`<motivational voice>` Let's reactive and solve this once for all `</motivational voice>` ;)

**Comment by atomfrede** [comment]
Let's do it 🤘

**Comment by mshima** [comment]
> relationship OneToMany {
>   Exam{questions} to Question{exam}
> }

```
relationship OneToMany {
  Exam{questions} to Question
}
```
Will not generate bi-directional.
We may easily forbid bi-directional for neo4j.

**Comment by meistermeier** [comment]
I think that this was also creating bidirectional relationships. It was basically taking the JPA path. But this was all 7-beta-something when I tried it.

**Comment by atomfrede** [comment]
I will have look what is generated and create a small sample application. @meistermeier If you are okay I will come back to you once I have something to show and talk about?

**Comment by meistermeier** [comment]
Yes, let's do this. I am currently trying to find the place where I have seen the wrong entity creation.

**Comment by atomfrede** [comment]
:+1: Thanks for your support

**Comment by deepu105** [comment]
@mshima I see you mentioned this in a merged PR, do you think we can close this?

**Comment by mshima** [comment]
Still applies.
The PR allows unidirectional one-to-many relationships by default related to https://github.com/jhipster/generator-jhipster/issues/13797#issuecomment-921190898
