### ISSUE TITLE
fucking jhipster doesn't work

### ISSUE THREAD

**Issue by angryhipster** [jhipster/generator-jhipster#1380]
hello, I have this crappy jhipster installed but when i try to generate staff it prints only "npm WARN engine generator-jhipster@2.7.0: wanted: {"node":">=0.10.0","npm":">=1.4.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})"
and more the same shit

**Comment by matdere** [comment]
Maybe wanted npm is not updated...  So maybe npm should be updated...  So
maybe the crap is not where you think it is...  Maybe only...

A convinced jhipster user

**Comment by jdubois** [comment]
I'm not even reading further than the ticket name -> please be polite first!!

**Comment by cagreek** [comment]
The hater (angryhipster) with the profanity must be a new to developer.  Don't even listen to them.  I can honestly say this is the best framework for spinning up an app quickly.   I've been using it for a year now and love it!!!

**Comment by pnreddysvu** [comment]
@angryhipster  many contributors put lot of effort to develop JHipster which is one of the best in its kind and thousands of happy users using it. I am one among them. If you don't know how to use it then try getting help from community.

Be polite when you are talking about an open source software. You did not pay single penny to any one to use the software.

If you don't like don't use it. I assume no one forced you to use JHipster.

**Comment by jdubois** [comment]
Thanks @cagreek @pnreddysvu !
