### ISSUE TITLE
Reactive microservices: No bean named 'reactiveTransactionManager' available

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13810]
##### **Overview of the issue**

I discovered a bug that I thought was a Protractor issue but appears to be a real problem.

```
2021-02-02 12:01:54.456 DEBUG 80301 --- [ctor-http-nio-2] c.o.d.blog.web.rest.BlogResource         : 
REST request to save Blog : Blog{id=null, name='name', handle='handle'}
2021-02-02 12:01:54.456 ERROR 80301 --- [ctor-http-nio-2] c.o.d.blog.web.rest.BlogResource         : 
Exception in createBlog() with cause = 'NULL' and exception = 'No bean named 'reactiveTransactionManager' 
available: No matching TransactionManager bean found for qualifier 'reactiveTransactionManager' - 
neither qualifier match nor bean name match!'

org.springframework.beans.factory.NoSuchBeanDefinitionException: 
No bean named 'reactiveTransactionManager' available: No matching TransactionManager bean found for 
qualifier 'reactiveTransactionManager' - neither qualifier match nor bean name match!
```

##### **Motivation for or Use Case**

Everything should work without errors when you generate a reactive microservices architecture and run e2e tests on them.

##### **Reproduce the error**

Clone the main branch:

```
git clone git@github.com:jhipster/generator-jhipster.git
cd generator-jhipster
npm install
npm link
```

Create a reactive microservices stack:

```
take reactive-stack
cd reactive-stack
jhipster jdl reactive-ms
```

Start everything:

```
cd gateway
jhkeycloakup
jhregistryup
./gradlew

# open a new terminal
cd ../blog
jhneo4jup
./gradlew

# open a new terminal
cd ../store
jhmongoup
./gradlew
```

Open the `gateway` project in a new terminal and run `npm run e2e`. It'll stop at the following point:

```
  Blog e2e test
    ✓ should load Blogs
    Create flow
      ✓ should load create Blog page
```

If you look at your blog app's logs, you'll see the error above.

##### **Suggest a Fix**

Not sure.

##### **JHipster Version(s)**

`main` branch as of 12:00 MST on Feb 2, 2021.

**Comment by atomfrede** [comment]
Seems like we missed to [read the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4.0-M2-Release-Notes#neo4j-1) :D Will take care of it:
