### ISSUE TITLE
Only footer is displayed

### ISSUE THREAD

**Issue by aditiranush** [jhipster/generator-jhipster#1381]
Hi I'm new to JHipster I created the application as mentioned in your tutorial.The application got generetaed and i run the same .But only footer is getting displayed :( Can you  please suggest me what could be the issue.

I have choose Maven ,Gulp and Mysql option

**Comment by wuethrich44** [comment]
It looks like you don't run `bower install` successfully. Can you check if you have a folder `bower_components` in your `webapp` folder?

**Comment by jdubois** [comment]
Yes it's a ```bower install``` or ```npm install``` that probably failed, please try again those commands manually.

**Comment by aditiranush** [comment]
i have bower component in the web app folder shall i reintall the bower ?

**Comment by jdubois** [comment]
No, ```bower install``` will install the dependencies in the bower folder (in src/main/webapp) -> I'm guessing some of those didn't download, maybe a proxy or network issue, have a look at your logs when you run bower.
