### ISSUE TITLE
Update database

### ISSUE THREAD

**Issue by NilsBRLT** [jhipster/generator-jhipster#1382]
Hi,

I'm using Jhipster on MacOS and I follow the 20mn tutorial of @jdubois.
When I create author and book, entities are correctly available on the application but the database is not updated. I use a local mysql base.

Now I have some errors in my database that I don't understand. If someone has a solution... Thanks !
![capture d ecran 2015-04-15 a 10 34 03](https://cloud.githubusercontent.com/assets/9608688/7154941/01ed79b8-e35b-11e4-9ea3-46ce7043343b.png)

**Comment by jdubois** [comment]
- what a strange error, in a PHP file???
- did you restart your Java server? It's the one that should update the database

I don't think this is a real ticket, maybe you should ask this on StackOverflow?

**Comment by NilsBRLT** [comment]
I have not precise that there isn't new liquifies changelog. I try that you tell to me !

**Comment by NilsBRLT** [comment]
Yeaah, I always have this error I posted, but after restart Mamp tables are created in my base.
Thank's a lot for the quick answer @jdubois !
