### ISSUE TITLE
entity generation fails when when using --single-entity option

### ISSUE THREAD

**Issue by ecostanzi** [jhipster/generator-jhipster#13833]
To generate a single entity without regenerating all the project entities the `--single-entity` option has been added in the entity generator (https://github.com/jhipster/generator-jhipster/issues/13365). I was trying this feature today but I realized it doesn't work.

##### **Overview of the issue**

When trying to generate a single entity I got the following error.

```
jhipster entity Tag --single-entity
INFO! Using JHipster version installed globally

Found the .jhipster\Tag.json configuration file, entity can be automatically generated!

? Do you want to update the entity? This will replace the existing files for this entity, all your custom code will be o
verwritten Yes, re generate the entity
ERROR! Error looking for otherEntity Post
Error: Error looking for otherEntity Post
    at C:\Users\ecostanzi\dev\github\generator-jhipster\generators\entity\index.js:565:19
    at Array.forEach (<anonymous>)
    at EntityGenerator.loadRelationships (C:\Users\ecostanzi\dev\github\generator-jhipster\generators\entity\index.js:561:36)
    at Object.<anonymous> (C:\Users\ecostanzi\dev\github\generator-jhipster\node_modules\yeoman-generator\lib\index.js:991:25)
    at C:\Users\ecostanzi\dev\github\generator-jhipster\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Users\ecostanzi\dev\github\generator-jhipster\node_modules\run-async\index.js:26:19
    at runLoop.add.once.once (C:\Users\ecostanzi\dev\github\generator-jhipster\node_modules\yeoman-generator\lib\index.js:992:11)
    at processImmediate (internal/timers.js:456:21)
```

##### **Motivation for or Use Case**

It's important to allow the generation a single entity without triggering the generation of all the entities of the project.  

##### **Reproduce the error**

```
# clone the project from the main branch and link it
$ git clone git@github.com:jhipster/generator-jhipster.git
$ cd generator-jhipster
$ npm link

# create a new project and use the cloned version of jhipster
$ mkdir -p /path/to/myproject && cd /path/to/myproject 
$ npm link generator-jhipster

# generate the project
$ jhipster import-jdl https://gist.githubusercontent.com/ecostanzi/d46084caa95d2d2416aed89d6e9facd6/raw/7ea0302a24347fb3df457eba227c60a388348c8b/blog.jdl --skip install

# try to generate the entity Tag
$ jhipster entity Tag --single-entity
```

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/13365

##### **Suggest a Fix**

None. I'll look into it later.

##### **JHipster Version(s)**
7.0.0-beta.1 (main branch)

##### **JHipster Version(s)**

```
blog@0.0.0 C:\Users\ecostanzi\dev\tmp\jh7blog
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "clientFramework": "react",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": true,
    "baseName": "blog",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "skipClient": true,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "applicationType": "monolith",
    "packageName": "com.jhipster.demo.blog",
    "packageFolder": "com/jhipster/demo/blog",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "entities": ["Blog", "Post", "Tag"],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1612379550780,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "lastLiquibaseTimestamp": 1612379730000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.25.0.windows.1

node: v12.18.4

npm: 6.14.6

yeoman: 3.1.1

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192

INFO! Congratulations, JHipster execution is complete!

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Adding a bounty on this, as it's a bug and we need the fix for the next release

**Comment by mshima** [comment]
Entity generator prepares its own entity for templates.
When having relationships, all the entities must be prepared for templates.
The only solution I can think of is to skip writing and postWriting, to the entities are prepared, but files aren't touched.
The PR also allows `jhipster entities Foo Bar`, so all passed entities files will be regenerated.
