### ISSUE TITLE
Updating authorities.csv does not trigger liquibase

### ISSUE THREAD

**Issue by dirkharrington** [jhipster/generator-jhipster#1384]
I'm new to this ecosystem, so this is a question out of ignorance....

I've updated authorities.csv to have new roles. What is the correct way to have liquibase apply those changes? I thought the right approach (for my situation) was to change the loadData for the file to loadUpdateData in the initial schema, so that it would handle detecting the differences in the csv file. However, that doesn't seem to work properly.

Any help is greatly appreciated.

**Comment by jdubois** [comment]
I would say you need to put this in a new changelog, but I have never done this myself.
This is not a bug or a feature request, and we are not developping Liquibase, so this is not the right place -> can you post this on stackoverflow, with the Liquibase and JHipster tags?
