### ISSUE TITLE
Speeding up "Docker build and deploy" flow pipelines

### ISSUE THREAD

**Issue by AlexisTonneau** [jhipster/generator-jhipster#13854]
##### **Overview of the feature request**

Speed up CI/CD pipeline with the flow "Build and publish a Docker image". IMHO we don't need to compile at the release-job, as far as "build" and "package" jobs were previously done.  
It isn't the case for similar CI/CD services, so I think this is a small mistake here.
Concerned job : 
`
docker-push:
  stage: release
  variables:
    REGISTRY_URL: $CI_REGISTRY
  dependencies:
    - maven-package
  script:
    - export IMAGE_TAG=$CI_REGISTRY_IMAGE:$TAG
    - ./mvnw -ntp compile jib:build -Pprod -Djib.to.image=$IMAGE_TAG -Djib.to.auth.username=gitlab-ci-token  -Djib.to.auth.password=$CI_BUILD_TOKEN -Dmaven.repo.local=$MAVEN_USER_HOME
  only:
    - master
    - staging
`

##### **Motivation for or Use Case**

In our internal GitLab instance, pipelines are taking forever and execute redondant tasks. It also occurs useless storage increase in our runners. We were loosing 5 minutes for each pipeline, and hopefully it doesn't happen to other teams

##### **Related issues or PR**

- [x]  Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
@AlexisTonneau you're right. Can you do a PR and also have a look at the gradle part in gitlab ci?

**Comment by atomfrede** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/13859
