### ISSUE TITLE
REST semantics for POST / PUT

### ISSUE THREAD

**Issue by ddewaele** [jhipster/generator-jhipster#1386]
Although create/update methods (POST / PUT) are generated on the RestController, the generated Angular controllers only seems to use the ```PUT```, even for creating new records.

Internally the ```update``` method then delegates back to the create ```method``` depending on the existence of an id.

```
    @RequestMapping(value = "/groups",
        method = RequestMethod.PUT,
        produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    public ResponseEntity<Void> update(@Valid @RequestBody Group group) throws URISyntaxException {
        log.debug("REST request to update Group : {}", group);
        if (group.getId() == null) {
            return create(group);
        }
        groupRepository.save(group);
        return ResponseEntity.ok().build();
    }
```

IMHO it would be cleaner if Angular would issue a ```POST``` when creating new entities, and only use the ```PUT``` to update them.

**Comment by ctytgat** [comment]
Agreed. I modified the standard generated code by adding this little module (based on http://kirkbushell.me/angular-js-using-ng-resource-in-a-more-restful-manner/)

```
angular.module( 'rest.resource', [ 'ngResource' ] )
    .factory('restResource', function($resource) {

        return function( url, params, methods ) {
            var defaults = {
                'create': { method: 'POST', isArray: false },
                'query': { method: 'GET', isArray: true},
                'get': {
                    method: 'GET',
                    transformResponse: function (data) {
                        data = angular.fromJson(data);
                        return data;
                    }
                },
                'update': { method:'PUT', params: {id: '@id'}, isArray: false }
            };

            methods = angular.extend(defaults, methods);

            var resource = $resource(url, params, methods);

            resource.save = function(data, callback) {
                if (!data.id ) {
                    return resource.create(data, callback);
                } else {
                    return resource.update(data, callback);
                }
            };

            return resource;
        };
    });
```

then a xyz.service.js becomes 

```
angular.module('proxyv2App')
    .factory('City', [ 'restResource', function( $resource ) {
        return $resource('api/cities/:id');
    }]);
```

**Comment by jdubois** [comment]
Let me explain first why it's done this way:

- On the server side we generate all REST methods, as they can be useful for everyone. We all agree on this, normally.
- On the client side: using PUT to create an entity is perfectly correct, so I don't see why this would an issue. Of course we could also use POST: there are 2 ways to do this, and I'm using one of them.

**Comment by ctytgat** [comment]
IMHO they way the REST resources are currently generated/used by the client is not entirely correct.
The client is now creating an object using 
PUT /api/<resource>
However, when you do a GET on the same url, you get the list of resources (which is expected, but not consistent). PUT should be used when updating a resource through its known location. If the location is not know, use POST.
See also http://restcookbook.com/HTTP%20Methods/put-vs-post/

So the usual way of doing things is
create: POST /api/<resource>
create: PUT /api/<resource>/<id>

**Comment by jdubois** [comment]
I don't know this book, but if you read the end of the article, you will see that we do is perfectly normal.

**Comment by ddewaele** [comment]
I think there is consensus that both POST and PUT can be used for creating objects, providing that the PUT call is idempotent.

I don't think this is currently the case with jHipster.

See this for some more reading:

http://stackoverflow.com/questions/630453/put-vs-post-in-rest

**Comment by ctytgat** [comment]
Yes you can use PUT to create, but my point is that you currently don't use the correct uri for that. (see both articles)

**Comment by jdubois** [comment]
OK, is this because we use PUT without an ID? If you follow your book, it's perfectly correct, and if you follow the stackoverflow answer, you should better do a POST.
For me this is correct, but as always with REST, there is not clear source of what's good or not. What is good with POST, is that we are sure everybody will agree with that, so that's the best solution in the end.
I'll have a look to see if this is easy to change, and use POST instead.

**Comment by ddewaele** [comment]
In the book it is mentioned 

*Use PUT when you can update a resource completely through a specific resource. For instance, if you know that an article resides at http://example.org/article/1234, you can PUT a new resource representation of this article directly through a PUT on this URL.*

As the ID is generated server-side (and not on the client), we don't have a specific resource yet, as such PUT cannot be used.

I think it will indeed avoid a lot of discussions like "does jHipster do proper REST or not"  by just switching to POST :)

**Comment by gzsombor** [comment]
I prefer to have less code, and because 99% of the code is the same for both for updating and creating entities - they are covering the same functionality: to save an object. So I prefer to have one REST call - which was the original JHipster functionality, until a couple of weeks ago.

**Comment by jdubois** [comment]
@gzsombor that's why I did it in the first place.
I'll have a look to see if it's easy to do or not.

**Comment by jdubois** [comment]
I've had a look at the code, and it's indeed more complex to implement...

**Comment by pnreddysvu** [comment]
Usually PUT is used to create entity when client knows/generates ID. If server generates ID then POST should be used.

**Comment by wuethrich44** [comment]
I agree with @gzsombor. I won't have much code duplication because it is not RESTful the other way. The interface provide the correct functionality (POST and PUT) so you can adapt your client if you like.

**Comment by gzsombor** [comment]
Probably there were some misunderstanding about my opinion: I prefer to have only _one_ backend method, not this confusing create/update split, where the update can be used for creation as well. I don't mind if it's PUT or POST. And prefer to have a proper, non-void result, so no duplicate server round trip is needed, just to get the new/updated entity - which can be very different from what the client sent

**Comment by jdubois** [comment]
Closed by https://github.com/jhipster/generator-jhipster/commit/69c6f5baab78ceb33a843ab22d9b4ce4b681096f

**Comment by kevinwheeler** [comment]
Out of curiosity, what's the rationale for using POST instead of PUT to update the current user information in `POST  /account` in AccountResource.java?

**Comment by kevinwheeler** [comment]
Would also be interested to know why `/api` routes that don't exist return 403 instead of 404.

**Comment by mraible** [comment]
@kevinwheeler This is because Spring Security 6 blocks everything by default. With Spring Security 5, this would have returned a 404. If you allow `/api/**` in your security configuration, it will result in a 404 when nothing is found.
