### ISSUE TITLE
Unit test fail when change generated entity to extend AbstractAuditingEntity

### ISSUE THREAD

**Issue by windhood** [jhipster/generator-jhipster#1387]
I generate an entity, say Store. but I manually change store class to extend AbstractAuditingEntity, I also changed the generated liquibase xml file to add the corresponding columns. However when I run the StoreResourceTest, both create and update will got the 400 error. Details as following:
MockHttpServletRequest:
         HTTP Method = POST
         Request URI = /api/stores
          Parameters = {}
             Headers = {Content-Type=[application/json;charset=UTF-8]}

             Handler:
                Type = com.bigpot.web.rest.StoreResource
              Method = public org.springframework.http.ResponseEntity<java.lang.Void> com.bigpot.web.rest.StoreResource.create(com.bigpot.domain.Store) throws java.net.URISyntaxException

               Async:
       Async started = false
        Async result = null

  Resolved Exception:
                Type = org.springframework.web.bind.MethodArgumentNotValidException

        ModelAndView:
           View name = null
                View = null
               Model = null

            FlashMap:

MockHttpServletResponse:
              Status = 400
       Error message = null
             Headers = {}
        Content type = null
                Body = 
       Forwarded URL = null
      Redirected URL = null
             Cookies = []

java.lang.AssertionError: Status 
Expected :201
Actual   :400

It seems the object marshall of AbstractAuditingEntity has problem?

Thanks

**Comment by gzsombor** [comment]
It's hard to guess, but I think, you have to modify the test too, to configure the user for spring security, something like:

        SecurityContext securityContext = SecurityContextHolder.getContext();
        securityContext.setAuthentication(new UsernamePasswordAuthenticationToken(new UserDetails(user.getLogin(), authorities, null), null));

**Comment by windhood** [comment]
Thanks! I have tried your suggestion, but it is the same result, still not working.

SecurityContext securityContext = SecurityContextHolder.createEmptyContext();
        securityContext.setAuthentication(new UsernamePasswordAuthenticationToken("admin", "admin"));
        SecurityContextHolder.setContext(securityContext);

**Comment by windhood** [comment]
Found the reason, the json deserializatin error (when deserialize createDate and lastModifiedDate).

[DEBUG] com.xxxx.web.rest.TestUtil - Json string is [{"createdBy":"SYSTEM","createdDate":{"weekOfWeekyear":16,"weekyear":2015,"monthOfYear":4,"yearOfEra":2015,"yearOfCentury":15,"centuryOfEra":20,"millisOfSecond":696,"millisOfDay":4743696,"secondOfMinute":3,"secondOfDay":4743,"minuteOfHour":19,"minuteOfDay":79,"hourOfDay":1,"year":2015,"dayOfMonth":19,"dayOfWeek":7,"era":1,"dayOfYear":109,"chronology":{"zone":{"fixed":false,"uncachedZone":{"cachable":true,"fixed":false,"id":"America/Los_Angeles"},"id":"America/Los_Angeles"}},"zone":{"fixed":false,"uncachedZone":{"cachable":true,"fixed":false,"id":"America/Los_Angeles"},"id":"America/Los_Angeles"},"millis":1429431543696,"afterNow":false,"beforeNow":true,"equalNow":false},"name":"SAMPLE_TEXT","picture":"SAMPLE_TEXT","price":0,"notes":"SAMPLE_TEXT"}]
[WARN] com.xxxx.web.rest.ProductResource - Returning HTTP 400 Bad Request
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Can not deserialize instance of org.joda.time.DateTime out of START_OBJECT token

so the generatedTestUtil.convertObjectToJsonBytes did not serialize the org.joda.time.DateTime correctly. 
How should we fix it?

**Comment by windhood** [comment]
OK, I added two annotations to the createDate and lastModifyDate,such as:

@CreatedDate
    @NotNull
    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    @Column(name = "created_date", nullable = false)
    @JsonSerialize(using = CustomDateTimeSerializer.class)
    @JsonDeserialize(using = CustomDateTimeDeserializer.class)
    private DateTime createdDate = DateTime.now();

I also gave createdBy a default value.
Maybe it is not a very idea to use the AbstractAuditEntity as a request parameter? Use a DTO (as UserDTO) instead?

Thanks

**Comment by cselti** [comment]
The TestUtil helper class doesn't use the same Jackson configuration (JodaTimeModule, ..) as the main project's one. I made a pull request to fix this (#1397)

**Comment by bonhamcm** [comment]
I had an issue because the validation interceptor runs before the auditing code so I had to remove the ```@NotNull``` annotation to make it work.

**Comment by jdubois** [comment]
Fix as #1397 is merged

**Comment by wuethrich44** [comment]
@cselti I had a `HttpMessageNotReadableException` when I want to convert a user entity to json. This PR fix this Problem. Thank you!
