### ISSUE TITLE
Enable entity generation when no DB is selected

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#13901]
##### **Overview of the feature request**
Hi my fellow Hipsters,
I would like to push a new feature to the generator and would like to gather your suggestions.
At Entando we have enabled entity generation even when we don't have any database selected in our blueprint:
https://github.com/entando/entando-blueprint/tree/master/generators/entity-server/templates/src/main/java/package/domain

For the moment, JHipster doesn't allow us to generate any entity when you have a project with 'no database' is chosen.
Instead of keeping this behavior in the Entando blueprint, I would like to put it to the main project.

##### **Motivation for or Use Case**
We are using this feature for some use cases:
- Backend fo frontend
- A Microservice with a domain but without persistence needed but with caching solution instead
- APIs aggregation
- Any middleware that can have a business domain to handle with and no need for persistence

I know that entities are mostly linked to a JPA design and rely on a database representation.

Enable entities, in this case, will allow our users to benefit from the power of domain generation in more cases than currently.

What do you think?

cc @jhipster/developers @joewhite101

##### **Related issues or PR**
N/A

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
For me, our sub generator entities is already really complex...
I'm not sure it will be useful for real projects, for real customers, so adding more complexity is not good for this sub gen.

But maybe I'm wrong.

**Comment by deepu105** [comment]
The only reason I could think of for doing this is if you have a
microservice with no DB and call some other service to persist data but as
Pascal mentioned the added complexity doesn't justify the value IMO as well

**Comment by deepu105** [comment]
What if only the restriction is removed and no templates are modified to
remove DB related annotations and stuff?

**Comment by gmarziou** [comment]
Do you mean generating only REST controllers and DTOs unchanged and then modify services so that they call repositories? It looks almost like openapi generator to me.

**Comment by avdev4j** [comment]
> Do you mean generating only REST controllers and DTOs unchanged and then modify services so that they don't call repositories? It looks almost like openapi generator to me.

It's only about that, we actually building all the layers for a given entity. It could be used with openapi generator but it will not replace it. OpenApi is cool if you have the OpenApi definition file.
In this case we would use the OpenApi and the entities to aggregate multiple calls into one business object and so one exposed API (BFF).
Example:
Api A 
Api B
JHipster app calls A
JHipster app call B
Return C

C is the generated entity that can have a business layer with a service and an exposed layer with a rest service.

Another option could be to use the same entity generation if we want to use a specific repository that is not related to a traditional database. E.g a redis client / server implementation.
In this case, I can generate all the stuff I need and then push the result through a non-jpa repository.

This is why it's most open the current sub-generator to more possibilities.

I'm not sure @pascalgrimaud and @deepu105 the complexity will be an issue since we are already filtering the generated content according to the database type e.g 'sql'.

Maybe the best thing should be to try to generate the entity if 'no' database is selected and see what's happening. For sure, the final result will be more a POJO than a real entity in the JPA area.

**Comment by pascalgrimaud** [comment]
IMO, the complexity will be (about the entities without database) to manage:
- MapStruct: it is mandatory, right ? (as there will be DTO and no Entities)
- service / serviceImpl : mandatory ?
- what about filtering option ?
- what about the Pagination, which required Page from Spring Data: no pagination?
- JDL, there will be a lot of new rules to forbid some configuration (see list above)
- don't forget JHipster IDE
- all tests in CI
- relationship between these entities
- protractor tests
- cypress tests
- gatling tests
- etc

For all of that, you'll need to update our templates to add the check `if (nodatabase)`
So, in the end, a lot of templates to modify.

What you would like is a Domain Object (in Hexagonal Architecture), built with JDL.
Then, around this Domain Object:
- you can call another sub gen to build the secondary (which is the repository) if needed, so here, we don't care about the database
- then, you can call another sub gen to build the primary (which can be API rest, Kafka Consumer, etc) if needed

But, we are not ready yet for this kind of architecture, until v8

**Comment by pascalgrimaud** [comment]
A last thing, you can have a look at the statistics: https://start.jhipster.tech/statistics
For database with "none/other", the result is 0.03% the last year, 0.09% the last month.

**Comment by avdev4j** [comment]
@pascalgrimaud 
I agree, all the complexity will come more from all the things around the templates than the templates themselves (the entity part is well structured IMO).

I trust you about the Domain object in a Hexagonal POV and I'm pretty sure we are talking the same thing for the final usage. 
My first idea was that we do not benefit from all the power of the JDL generation at the moment.
So, we should wait a bit and invest in the v8 refactoring and see if something can be done here.

> For database with "none/other", the result is 0.03% the last year, 0.09% the last month.
**Bad faith On** Because people can't generate domain objects with **Bad faith Off**

**Comment by avdev4j** [comment]
I'm closing this one since this should not be worth and can be done during the next main JHipster version.

Thanks mates
