### ISSUE TITLE
Error during generator-hipster

### ISSUE THREAD

**Issue by alexhutnik** [jhipster/generator-jhipster#1392]
I picked the following options:

    (1/13) What is the base name of your application? banking
    (2/13) What is your default Java package name? com.banking
    (3/13) Do you want to use Java 8? Yes (use Java 8)
    (4/13) Which *type* of authentication would you like to use? HTTP Session Authentication (stateful, default Spring Security mechanism)
    (5/13) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL)
    (6/13) Which *production* database would you like to use? MySQL
    (7/13) Which *development* database would you like to use? H2 in-memory with Web console
    (8/13) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
    (9/13) Do you want to use clustered HTTP sessions? No
    (10/13) Do you want to use WebSockets? No
    (11/13) Would you like to use Maven or Gradle for building the backend? Maven (recommended)
    (12/13) Would you like to use Grunt or Gulp.js for building the frontend? Grunt (recommended)
    (13/13) Would you like to use the Compass CSS Authoring Framework? No

And at the end, I get the following error:

    generator-jhipster@2.7.0 node_modules/generator-jhipster
    ├── shelljs@0.3.0
    ├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
    ├── underscore.string@2.3.3
    ├── cheerio@0.17.0 (dom-serializer@0.0.1, entities@1.1.1, htmlparser2@3.7.3, CSSselect@0.4.1, lodash@2.4.1)
    ├── insight@0.4.3 (object-assign@1.0.0, async@0.9.0, os-name@1.0.3, lodash.debounce@2.4.1, tough-cookie@0.12.1, request@2.55.0, configstore@0.3.2, inquirer@0.6.0)
    └── yeoman-generator@0.17.7 (dargs@2.1.0, rimraf@2.3.2, diff@1.3.2, class-extend@0.1.1, text-table@0.2.0, mime@1.3.4, async@0.9.0, isbinaryfile@2.0.3, cross-spawn@0.2.9, debug@1.0.4, grouped-queue@0.3.0, nopt@3.0.1, mkdirp@0.5.0, run-async@0.1.0, iconv-lite@0.4.8, file-utils@0.2.2, glob@4.5.3, findup-sync@0.1.3, github-username@1.1.1, lodash@2.4.1, download@1.0.7, request@2.55.0, gruntfile-editor@0.2.0, inquirer@0.7.3)
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: spawn grunt ENOENT
        at exports._errnoException (util.js:746:11)
        at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
        at child_process.js:1144:20
        at process._tickCallback (node.js:355:11)

I tried changing my git config as prescribed here without any success: https://github.com/jhipster/generator-jhipster/issues/1132

**Comment by jdubois** [comment]
You had an error when installing npm and/or bower
Do a "npm install" and "bower install" manually.

**Comment by Shiva-Shinde** [comment]
I am having exactly the same problem. I did npm install and bower install manually with out any success. 
I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn grunt ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

Please let me know If I am going wrong some where

**Comment by gmarziou** [comment]
This is unlikely a jhipster problem but rather a nodeJS problem, what's your node version? How did you install it? Try running 'yo doctor'.

**Comment by Shiva-Shinde** [comment]
Yeah I understand, I had some problems with nodejs installation. I found the problem and resolved it. JHipster is working absolutely fine. Thanks for helping!!


I saw JHipster has some inbuilt MySQL, PostgreSQL open source database applications. Since they use SQL,  a relational database. Can I replace different databases like OracleDB or NuoDB since they use the same SQL. Thanks in advance.

**Comment by gmarziou** [comment]
Yes you can, just add the jar of your db driver to your pom dependencies and configure according your application.yml. My hipster application works fine with both Oracle and Postgres.

**Comment by Shiva-Shinde** [comment]
Thanks. You mean I can migrate to any SQL (a relational database) based database applications right!!

**Comment by jdubois** [comment]
Yes. We should hopefully have soon a guide on using Oracle -> there is no technical issue, only a legal one: as it's a proprietary database, we can't provide its driver, and it's hard for me to test (as I'm not going to buy it)

**Comment by Shiva-Shinde** [comment]
I understand. I am trying to do that replacing some other databases (proprietary) other than mysql on JHipster. If I make it, I will definitely let you know guys. Thanks for support!!

**Comment by Shiva-Shinde** [comment]
I have selected production:MySQL, development: MySQL and language as SQL while loading 
*yo jhipster* and I have successfully connected to MySQL after creating mysqlapp (application) on JHipster.
However, I am trying to connect to other databases. Oracle in this case.

I have added both jdbc and Hibernate driver and installed maven. I have added these dependencies in pom.xml file of my JHipster application in Spring Tool Suite.

As you guys suggested, my next step is to configure the application.yml file. I never did this before, could you guys provide me any reference or resource on how to configure this application.yml. I am completely new to this application.yml thing, having trouble, no idea on where to start from. Hopefully, If I configure, I am all set for loading JHipster aap with new database oracle?

Thanks JHipster Team

**Comment by gmarziou** [comment]
This is like a usual data source configuration with JDBC URL except that it is stored in application.yml
For Oracle, mine looks like this:
~~~
spring:
    profiles: dev
    datasource:
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@host.example.com:1521:SID
        username: USER
        password: user

    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
~~~

**Comment by Shiva-Shinde** [comment]
Shall I create a new app-dev.ml file. Since I already have MySQL config in my app-dev.yml file. Shall I remove the MySQL confg stuff and add oracle config?


I was adding Oracle with MySQL in it but I guess it might create a conflict with the port number. Thanks!!

**Comment by gmarziou** [comment]
Please learn about [github markdown](https://guides.github.com/features/mastering-markdown/) when posting here.
