### ISSUE TITLE
Loading "grunt-karma.js" tasks...ERROR

### ISSUE THREAD

**Issue by fontanellif** [jhipster/generator-jhipster#1393]
i'm trying to package a simple jhipster project but i get this error: 

mvn package -Pprod

[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ awhy ---
[INFO] 
[INFO] --- yeoman-maven-plugin:0.4:build (run-frontend-build) @ awhy ---
[INFO] node version :
v0.10.38
[INFO] npm version :
2.7.4
[INFO] --------------------------------------
[INFO]          NPM INSTALL
[INFO] --------------------------------------
npm WARN unmet dependency /var/www/app/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-parser requires debug@'0.7.4' but will load
npm WARN unmet dependency /var/www/app/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/debug,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /var/www/app/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-parser requires json3@'3.2.6' but will load
........
[INFO] bower version :
1.4.0
[INFO] --------------------------------------
[INFO]          BOWER INSTALL --NO-COLOR
[INFO] --------------------------------------
[INFO] grunt version :
grunt-cli v0.1.13
grunt v0.4.5
[INFO] --------------------------------------
[INFO]          GRUNT TEST --NO-COLOR
[INFO] --------------------------------------
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'iconv-lite'
Warning: Task "karma" not found. Use --force to continue.

Aborted due to warnings.

Execution Time (2015-04-18 15:05:23 UTC)
loading tasks  105ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
Total 107ms

All dependencies should be installed with npm install.

**Comment by jdubois** [comment]
You had an error when installing npm.
Do a "npm install" manually.
