### ISSUE TITLE
Dev environment H2 tables aren't generated

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#13948]
##### **Overview of the issue**

Running Deepu's sample https://dev.to/adyen/building-an-e-commerce-application-using-java-react-2iln with two replacements: postgresql instead of mysel and Vue instead of React.

Two tables are missing in the H2: shopping cart and product order.

##### **JHipster Version(s)**

 7.0.0-beta.1

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vw98075** [comment]
This error doesn't occur when I run it in docker. So, that is a problem in the dev environment only.

**Comment by Tcharl** [comment]
Is it still not working?
