### ISSUE TITLE
Eliminate render-blocking JavaScript and CSS in above-the-fold content

### ISSUE THREAD

**Issue by jackygrahamez** [jhipster/generator-jhipster#1394]
Is it possible to build a site in such a way to eliminate the render blocking javascripts and css. Instead using async attribute? I am looking at ways to optimize my site further. Google has a great tool for analyzing called Page Speed Insight. I see jhipster.github.io has the same issue as mine

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fjhipster.github.io%2F&tab=mobile

**Comment by jdubois** [comment]
I don't understand what you mean by "render blocking JavaScript", do you have some example?
For jhipster.github.io it's just a basic, static website, not a real JHipster application

**Comment by jackygrahamez** [comment]
Google's "PageSpeed Insights" tool provides suggests on how to optimize load time. It recommends removing "render blocking Javascript" you can see for yourself by running a jHipster project using this tool. I checked both my own and https://jhipster.github.io/
https://developers.google.com

When you run the tool, Google provides a link that explains what render blocking code is.
https://developers.google.com/speed/docs/insights/BlockingJS

Render blocking code requires that all the bytes be retrieved before the browser starts rendering the page. One way to avoid that is to use the async parameter in the script tag for example <script async src="my.js">

I was looking at the grunt tasks and trying to figure out if there is a way to put the async attribute into the build template for both app.js and vendor.js.

**Comment by jdubois** [comment]
OK, I had a look and that's really a neat tool!
I understand your issue, but I'm not sure if we can do anything about it: the whole application is in the JS files... Then the REST requests are asynchronous, of course.
Let's keep it open until we have the time to have a closer look.

**Comment by gmarziou** [comment]
The question is what will you show to your users until all your blocking JS get loaded?
You can show only static HTML so the best you can do is probably to display an animated gif, not that useful IMHO.

**Comment by jdubois** [comment]
OK, I can't find a solution to make it work "full async", and as @gmarziou says it wouldn't have much use anyway.

Maybe there's something for AngularJS, as it's also provided by Google, but I couldn't find anything

**Comment by tnr2394** [comment]
Render blocking javascript means such a javascript or ajax call that is generated from your page which gets the content from over the network delaying the rendering and hence loading of the page. So all we need to do is avoiding more of ajax calls to server while rendering the page.

**Comment by gmarziou** [comment]
Please avoid commenting an old closed issue, open a new one if you have propositions or submit a PR.

**Comment by cmitsolutions** [comment]
i fix this problem using this https://stackoverflow.com/questions/41000088/grunt-remove-async-and-defer-from-my-scripts-and-css, edit the Gruntfile.js (assuming you are using grunt) and add this into usemin:

 // Performs rewrites based on filerev and the useminPrepare configuration
    usemin: {
      html: ['<%= yeoman.dist %>/{,*/}*.html'],
      css: ['<%= yeoman.dist %>/styles/{,*/}*.css'],
      js: ['<%= yeoman.dist %>/scripts/{,*/}*.js'],
      options: {
        assetsDirs: [
          '<%= yeoman.dist %>',
          '<%= yeoman.dist %>/images',
          '<%= yeoman.dist %>/styles'
        ],
        patterns: {
          js: [[/(images\/[^''""]*\.(png|jpg|jpeg|gif|webp|svg))/g, 'Replacing references to images']]
        },
        blockReplacements: {
		  
		  js: function(block) {
			return '<script defer src="' + block.dest + '"></script>';
		  }
		}
      }
    },
