### ISSUE TITLE
Add ImgBot to jhipster.github.io

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13941]
##### **Overview of the feature request**

I just got a PR (because I have ImgBot enabled on my repos) and it reduces the image sizes by 50%!

https://github.com/mraible/jhipster.github.io/pull/2

##### **Motivation for or Use Case**

Faster is better.

**Comment by mraible** [comment]
Please?

**Comment by CGarces** [comment]
Hi @mraible another option is add image compression on PRs instead of activate a boot at repository level.

You can made your own yaml workflow and send a PR to jhipster.github.io

See: 
https://github.com/calibreapp/image-actions
https://github.com/marketplace/actions/image-actions

**Comment by mraible** [comment]
@CGarces Any chance you could create a PR for this?

**Comment by CGarces** [comment]
I'll try on the weekend.

**Comment by DanielFran** [comment]
@CGarces, Are you still available to contribute with a PR?

**Comment by CGarces** [comment]
Sorry, I'm working on another projects right now.

**Comment by DanielFran** [comment]
Thanks, @CGarces for the confirmation.
I will close it for now. You can request to re-open it if needed.
