### ISSUE TITLE
Downgrade husky dependency to v4.x

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#13940]
##### **Overview of the issue**
I noticed that we upgraded to husky `v5.x` which's not free to use in commercial projects. Since we don't enforce any licensing terms on JHipster generated applications, I suggest downgrading the dependency to `v4.x`. I did put a comment on the merged PR, however, that may have been lost in the dependabot alerts.

##### **JHipster Version(s)**
Main branch

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
From their v5 announcement:
> For a limited time, husky 5 will be released under License Zero's Parity License. It will be MIT again later.

Don't know when the licence will change, again... This kind of move (and lack of details) makes me want to check for alternatives to husky.

**Comment by PierreBesson** [comment]
Their new license doesn't make any sense to me (https://github.com/typicode/husky/blob/main/LICENSE-PARITY) with very vague language. Open source software licensing is a complex topic. It is definitely not acceptable to ship this with JHipster, I think we might have to create a project policy to only depend on permissive licenses dependencies.
Also it looks like they might have relicensed contributors code without having them sign a CLA :shrug:.

But you will be glad to know that the Parity license is part of a [family of licenses](https://github.com/licensezero/parity-public-license#family) which includes Parity, Charity and Prosperity. I'm not making this up...

**Comment by atomfrede** [comment]
This is fixed by #14008, so let's close this.

**Comment by atomfrede** [comment]
Husky 6 has been released (under MIT), should we consider updating to that version again? https://github.com/typicode/husky/releases/tag/v6.0.0

**Comment by PierreBesson** [comment]
Yes, it looks very good. I like their technical solution to the git hooks problem https://blog.typicode.com/husky-git-hooks-javascript-config/.
