### ISSUE TITLE
Use main as initial branch name for generated application

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#13954]
##### **Overview of the feature request**

Should we use `main` for the branch name of the generated application or stick with `master` (or more precise the global setting of the user)?

##### **Motivation for or Use Case**

Would be good to have this change for 7.x as at least I would consider it "breaking".

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
It's already done for JHipster Online I think.
Anyway, for local project, it depends on the git configuration of our users. Not sure we should force it, as the `git init` is not related to JHipster.

The user needs to do this: `git config --global init.defaultBranch main` 

Unless what you propose is:
- `git init`
- if the branch is master, we'll use: `git branch -m main`

**Comment by atomfrede** [comment]
I think we are on the same track. If the default branch is not `main` but something else than `master` (e.g. `develop` whatever) we should not overwrite/overrule the user's setting here. If it's master we could just use `main` instead either by providing the parameter to `git init` or creating the branch as you proposed. 
Not sure if it is worth the effort.

**Comment by SudharakaP** [comment]
>It's already done for JHipster Online I think.

Yes, jhipster-online already do that, and when I was adding that I had this exact thought. 

https://github.com/jhipster/jhipster-online/blob/10fadd33cc4a6597502480ed16ae1fb0db7d5041/src/main/java/io/github/jhipster/online/service/GitService.java#L74-L76

Also in the future Git will change their default branch to something other than main as stated here; https://sfconservancy.org/news/2020/jun/23/gitbranchname/.

**Comment by atomfrede** [comment]
If there will be something coming to git core let's close this.
