### ISSUE TITLE
Not able to use TextBlob with MS SQL Server

### ISSUE THREAD

**Issue by RishabhTayal** [jhipster/generator-jhipster#13977]
##### **Overview of the issue**

I am using MS SQL Server as a database with my Jhipster generated project. There seems to be an issue with using Blob of type CLOB (Text Field) when generating the field for the entity. Adding the code from my json file and the exception I am getting when the liquibase migration is being run. Please note: When I change the field type from CLOB to String, everything works fine. That eliminates possibility of some other cause of the issue. I have generated another test project with mysql database with same JDL and it works fine so seems like the issue is related to MS SQL Server support.

##### **Motivation for or Use Case**

Not able to use CLOB (Blob) with MS Sql server.

##### **Reproduce the error**

Create a new jhipster project using MS Sql server. Create a new entity with CLOB as field type. Run the liquibase migration to see the exception in the console logs.

##### **Related issues**

N/A

##### **Suggest a Fix**

--

##### **JHipster Version(s)**

6.10.5

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.et",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "MyApp",
    "packageName": "com.et",
    "packageFolder": "com/et",
    "serverPort": "8086",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mssql",
    "prodDatabaseType": "mssql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "xxxxxxxxx",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity NotificationSetting {
  myField TextBlob
}
service NotificationSetting with serviceImpl

</pre>
</details>

##### **Browsers and Operating System**

macOS 10.15.7

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Can you give more information on what database you are using?  JHipster works out-of-the-box when using the `src/main/docker/mssql.yml` container for MSSQL.  Tested both v6 and v7-beta which uses the following versions:

- V6: `mcr.microsoft.com/mssql/server:2017-latest-ubuntu`.
- V7: `mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04`.

**Comment by RishabhTayal** [comment]
@ruddell How can I find the version of database?

**Comment by ruddell** [comment]
I'm not sure off the top of my head, I would recommend looking on StackOverflow. 
 Maybe https://stackoverflow.com/q/20351674/3737815

**Comment by RishabhTayal** [comment]
Microsoft SQL Azure (RTM) - 12.0.2000.8 
	Oct  1 2020 18:48:35 
	Copyright (C) 2019 Microsoft Corporation

Here is the current DB version.

**Comment by ruddell** [comment]
I tested a database hosted on Azure that matches your instance.

If I removed the below line in `master.xml`, I get the error.  Please add it to your `master.xml` to match the generated code:
```
    <property name="clobType" value="clob" dbms="mysql, oracle, mssql, mariadb, postgresql"/>
```

After adding that line, liquibase started successfully.

**Comment by RishabhTayal** [comment]
@ruddell This works!!! Thanks a lot for your support. 👍
