### ISSUE TITLE
Feature Request: Stubbed api response(s) for grunt/gulp serve

### ISSUE THREAD

**Issue by marksmall** [jhipster/generator-jhipster#1398]
I've not found an existing request for this.

It would be nice if jhipster provided the ability to stub api responses during development.  I see this as a test directory containing files with stubbed responses.  These files could be used when running grunt/gulp serve.  This would provide a clean separation between server/client side coding.  The stubbed data may even be able to be used in unit/integration tests, but that may be a step too far.

**Comment by jdubois** [comment]
Currently you need to run your Java server, and you have live data -> I don't see why this would be useful, how do you intend to use it?

**Comment by marksmall** [comment]
Splitting up server/client development by agreeing the api between each is the point of the serve task.  This forces you to agree the api and give it due consideration.  Too often I've seen developers opt to add more parameters to the api for the sake of easiness and not consider the implications thoroughly.  By stubbing api for development you ensure any changes are discussed (hopefully).  After all, this is the point of the serve task, otherwise what is the point of it.

**Comment by jdubois** [comment]
Usually it's the same person who does everything. Otherwise we have Swagger, or people can just look at the Spring MVC endpoints, they're easy to read.
If you mock the REST endpoints, you lose the ability to have live data, and you are not on the "real" API, so you might have more bugs.

**Comment by marksmall** [comment]
Sorry, but I disagree with your point that is is usually the same person doing both, in small apps maybe.  Swagger while good doesn't force developers to discuss the API, it just reports what it is as the server-side views it.  I don't know what you mean by the "real" API, it seems your suggesting the server-side is the definitive arbiter of the API, if true, then I disagree, it is a shared contract between server and client, neither should take precedence.  While mocking has the potential not to reflect the server-side API, this is human error i.e. changing API without discussion, this is human error, not a problem with the process.

Anyway, it looks like a feature your not interested in so I'll not labour the point further, thanks for your time..

**Comment by sdoxsee** [comment]
You're not alone in wanting to mock out the backend for development. Here's an earlier discussion https://github.com/jhipster/generator-jhipster/issues/1169

**Comment by jdubois** [comment]
@marksmall I'm just trying to understand what you want to do with it

- In my opinion, it's much better to have one person do a whole "user story", and not split teams by technologies
- I also prefer to have the "live" version than a "mocked" version, as long as it's easy to set up (which is what we try to do)

But, I understand people want to use JHipster in other ways, and do not want to work the same way as I do: whenever this is possible, I try to have those working too.

I see better what you want to do, and as you said in the first place, that might help for our karma.js tests -> those are currently too basic, and there are already a couple of people who have proposed to work on improving them. So I'll try to have everyone in sync here.

**Comment by marksmall** [comment]
Hi Julien,

I agree it is better for one person to do a whole user story.  Sometime we don't have the option e.g. we are mocking the UI to show to the client.  I notice that there has also already been a feature request for this sort of thing:

https://github.com/jhipster/generator-jhipster/issues/1169

I'm happy to work on something when I get the chance and present it here for discussion, thanks for all the good work.

**Comment by gmarziou** [comment]
Well, as I explained it in #1169 it's so easy to do it with angular (see my sample project) that it's not worth doing it in jhipster

**Comment by jdubois** [comment]
I've just looked at the code from @gmarziou and it's indeed so easy to do, it's not worth it.
But I don't understand how authentication is supposed to work? Anyway, without a back end, I don't know how you can make all this work.

**Comment by jdubois** [comment]
Closing this as:

- In my opinion it's far better to have the backend working, and it shouldn't be hard to have
- Otherwise, the code from @gmarziou is really easy to change

Anyway, I still don't understand how you could have authentication working without the backend, so I don't understand how you could work

**Comment by gmarziou** [comment]
@jdubois the authentication works fine as long as you use simple login/pwd which is easy to stub.
