### ISSUE TITLE
ReactUI : Unnecessary Entities Request Generated towards BE

### ISSUE THREAD

**Issue by olgunkaya** [jhipster/generator-jhipster#14009]
##### **Overview of the issue**

createEntity method generated via entity.reducer template includes another dispatch to fetch all entities aka getEntities. But considering the nature of the create entity and the flow of app the dispatch to getEntities should be avoided or be enhanced. 

##### **Reproduce the error**

1. Generate an app including React UI.
2. Go to an entity page. 
3. Create an entity. 
4. On the inspection window of the browser one can see that there is an extra getEntities method.

##### **Suggest a Fix**

1. Include a boolean parameter to indicate if a redirect will be performed back to the list of entities page. Since entity list page will reload the entities in useEffect(...) the dispatch from createEntity becomes unnecessary. Using this boolean (with value of true) can give ability to the users to cache entities if they have such use case.  
2. Remove the dispatch in createEntity.

##### **JHipster Version(s)**

 "jhipsterVersion": "6.10.5",

**Comment by pascalgrimaud** [comment]
@olgunkaya : can you try the 7.0.0-beta.1 version or better, use the main branch ?
There are so much improvements since 6.10.5, so I think it's already fixed, but I'm not sure as I don't use React for my own projects

**Comment by olgunkaya** [comment]
Hi @pascalgrimaud,

I think my version is the latest stable version (with all my respect I prefer not to go with beta)
https://github.com/jhipster/generator-jhipster/tags

Plus I checked on the main branch and see below section for the generation template. 

https://github.com/jhipster/generator-jhipster/blob/main/generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs

`...
<%_ if (!readOnly) { _%>
export const createEntity: ICrudPutAction<I<%= entityReactName %>> = entity => async dispatch => {
  const result = await dispatch({
    type: ACTION_TYPES.CREATE_<%= entityActionName %>,
    payload: axios.post(apiUrl, cleanEntity(entity))
  });
  <%_ if (pagination !== 'infinite-scroll') { _%>
  **dispatch(getEntities());**
  <%_ } _%>
  return result;
};
...`

It's still the same on main branch too.

**Comment by olgunkaya** [comment]
Fixed in https://github.com/jhipster/generator-jhipster/commit/54659d9349f00066edf621e269b46652214f3c7b

**Comment by pascalgrimaud** [comment]
No worry, it belongs to you to choose Beta version or stable version :-) I respect that.
Just for your information, all applications for my customer use beta.1 and it's in prod 😎

Thanks for finding the commit

**Comment by olgunkaya** [comment]
Well, I am not fully compatible with it, can I update/upgrade my current application with 7 beta 1 without losing modifications done? Although I prefer stable but would like to give it a chance on a separate branch to see the output :)
