### ISSUE TITLE
Web page is being reload instead of only changing content, when hot reload is enabled

### ISSUE THREAD

**Issue by sameerthekhans** [jhipster/generator-jhipster#14028]
##### **Overview of the issue**

Web page is being reload instead of only changing content, when hot reload is enabled

##### **Motivation for or Use Case**

Hot reload should only change content without page reload

##### **Reproduce the error**

Simply start application, change the content and observe the page

##### **Suggest a Fix**
By default webpack `liveReload` is enabled, and it should be turned off when using `hot` reload

##### **JHipster Version(s)**
6.10.5

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.sample.first"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "gateway",
    "baseName": "jhipster",
    "packageName": "com.sample.first",
    "packageFolder": "com/sample/first",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": "spring-websocket",
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1613911180573,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

node: v14.15.4

npm: 6.14.10

##### **Browsers and Operating System**
Windows and chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
In the latest JHipster beta version `7.0.0-beta.1` you can run `npm run start-hmr` instead of `npm start` (if using Angular), which uses Angular 11 HMR support by running `ng serve --hmr`.
HMR support is not fully configured in the JHipster version 6.

**Comment by wmarques** [comment]
@kaidohallik btw why don't we enable hmr by default in `npm start` script ?

**Comment by kaidohallik** [comment]
@wmarques I think we can enable HMR by default, some comments about this topic: https://github.com/jhipster/generator-jhipster/pull/13118#issuecomment-732024690 and https://github.com/jhipster/generator-jhipster/pull/13118#issuecomment-732037077
If removing `start-hmr` script from `package.json` then also `README.md` should be updated, need to remove https://github.com/jhipster/generator-jhipster/blob/a4e8fe5ad5195cfdc0931c9c1b350d4390e61841/generators/common/templates/README.md.ejs#L97-L104

**Comment by wmarques** [comment]
@kaidohallik Well let's keep it that way then :) 
Let's close this as it will be supported in v7
