### ISSUE TITLE
Proposal: unify Cassandra date-time JDL types with common-databases JDL types

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#14026]
##### **Overview of the feature request**

Rework JDL types for Cassandra: https://www.jhipster.tech/jdl/entities-fields#field-types-and-validations
- [breaking-change] remove `Date` type: it currently seems to be a synonym of `Instant`, since it also generates a field with java type `Instant` and a `timestamp` column type
- add support for `LocalDate` JDL Type, [already supported by Spring Data Cassandra](https://docs.spring.io/spring-data/cassandra/docs/current/reference/html/#mapping-conversion)
- add support for `Duration` JDL Type

##### **Motivation for or Use Case**

Feature parity between Cassandra and other databases. Adding support for missing types is quite easy.
Reduce complexity by proposing the same JDL types for all databases.

Next step: try to use for Cassandra the same Blob types used for other databases 

##### Open question

- Should we keep `Date` type for retro-compatibility in V7, and wait V8 for removing it?

**Comment by murdos** [comment]
FYI I'll submit a PR, probably tomorrow

**Comment by pascalgrimaud** [comment]
Not sure to keep retro compatibility, I think you can remove it directly now as we are still in v7 beta
