### ISSUE TITLE
Replace Spring Cloud Hystrix

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#14031]
##### **Overview of the feature request**

Spring Cloud Hystrix is in maintenance mode, we should probably replace it by Spring Cloud Circuit Breaker

##### **Motivation for or Use Case**

https://spring.io/blog/2018/12/12/spring-cloud-greenwich-rc1-available-now#spring-cloud-netflix-projects-entering-maintenance-mode

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@atomfrede @murdos : is it needed for the next release ? Or can we go without it ?

**Comment by murdos** [comment]
@pascalgrimaud : We can go without it IMO, it's no blocking. 
This is even something that we can do after V7 final release, e.g. with next Spring Boot upgrade.

**Comment by pascalgrimaud** [comment]
Thanks for the information @murdos 
So there is still this PR https://github.com/jhipster/generator-jhipster/pull/14029 before being able to do a new release

**Comment by murdos** [comment]
@pascalgrimaud : for the release, I've some trouble with a vuejs e2e not passing with https://github.com/jhipster/generator-jhipster/pull/14027 that I've not yet reproduced locally.
I can split the PR, to just have one small PR with the breaking change (removal of `Data` type) if you want to include it in the next release.

**Comment by murdos** [comment]
Keep it open

**Comment by atomfrede** [comment]
Keep it open

**Comment by atomfrede** [comment]
Keep it open

**Comment by atomfrede** [comment]
Keep it open

**Comment by atomfrede** [comment]
Keep it open
