### ISSUE TITLE
import script with bower.json has a bug

### ISSUE THREAD

**Issue by Qinwroks** [jhipster/generator-jhipster#1403]
import iscroll and angular-iscroll by bower.json
  "dependencies": {
    .......
    "iscroll": "~5.1.3",
    "angular-iscroll": "~1.2.4"
  }

then i run 'bower install' and 'grunt wiredep', but the 'src/main/webapp/index.html' file not updated!

there is no iscroll and angular-iscroll script tag 

between 
```java
 <!-- bower:js -->
  <!-- endbower -->

WHAT WRONG?

**Comment by Qinwroks** [comment]
i add these scripts myself like this

.....
<script src="bower_components/iscroll/build/iscroll.js"></script>
<script src="bower_components/angular-iscroll/dist/lib/angular-iscroll.js"></script>
 

but when i run 'grunt serve' , the two lines i add was removed aromatically.

**Comment by andidev** [comment]
There is no Bower package called angular-iscroll, see http://bower.io/search/?q=angular-iscroll
File a bug report in angular-iscroll project

**Comment by andidev** [comment]
Place manually imported scripts after the endbower comment tag

**Comment by Qinwroks** [comment]
@andidev Thank you!
