### ISSUE TITLE
optimize PATCH request in v7

### ISSUE THREAD

**Issue by PiperDing** [jhipster/generator-jhipster#14033]
##### **Overview of the feature request**
make patch request better
1. move partialUpdate function to mapstruct,just like this:
```java
public interface EntityMapper<D, E> {
    E toEntity(D dto);

    D toDto(E entity);

    List<E> toEntity(List<D> dtoList);

    List<D> toDto(List<E> entityList);
    
    @Named("partialUpdate")
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void partialUpdate(@MappingTarget E entity, D dto);
}
```
2.generaoter the missing code for client in *.service.ts

##### **Motivation for or Use Case**
For first one, I want to exclude some field in PATCH request sometimes.or it's not the same for different user.it's eary to make different config in mapstruct

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
mapstruct is used when we choose DTO, so in this case, it can be an improvement

**Comment by DanielFran** [comment]
@PiperDing will you provide a PR soon?

**Comment by PiperDing** [comment]
@DanielFran I'd like to contribute to this feature, but I don't know what to do next.This is the first time I submitted an issue.I've seen the generator code and know how to modify it.Do I just modify the code and submit the merge request?

**Comment by DanielFran** [comment]
@PiperDing yes please go ahead.

**Comment by mshima** [comment]
IMO, we should try to implement something like https://github.com/jhipster/generator-jhipster/pull/12507#issuecomment-699032634.
Don't allow to remove a value is preventive to use PATCH IMO.

**Comment by PiperDing** [comment]
I just submitted the pull request #14292
