### ISSUE TITLE
Feature Request: Obfuscation support to protect code

### ISSUE THREAD

**Issue by pnreddysvu** [jhipster/generator-jhipster#1405]
Javascript code is minified. Same way should java code to be protected by obfuscation?

**Comment by jdubois** [comment]
- JavaScrip tis minified, not obfuscated -> it's surprisingly easy to read it, in fact
- Java obfuscation is a whole different concept, and it is also on the server side, so it's not working at the same level

I also don't believe there is a good OSS Java obfuscation lib.
