### ISSUE TITLE
Feature request: reading active profile from OS environment variable

### ISSUE THREAD

**Issue by Arturozz** [jhipster/generator-jhipster#1408]
Hi,

It would be nice to be able to read current application profile from OS environment variable using spring default value "SPRING_PROFILES_ACTIVE" besides argument "spring.profiles.active"

Its really useful for use it with Docker so you can have a unique container with the same CMD command and select your profile when launching it.
ex: 
docker run --env SPRING_PROFILES_ACTIVE=dev myrepo/myapp

Thanks!

**Comment by Arturozz** [comment]
It currently works passing a environment variable, its a spring boot feature, but then the Application. addDefaultProfile method also adds "dev" profile because it only checks "spring.profiles.active"

**Comment by jdubois** [comment]
I'm reopening this because the previously merged solution does not work
