### ISSUE TITLE
Any authenticated user can access to any user details (/api/users/**)

### ISSUE THREAD

**Issue by alexfdz** [jhipster/generator-jhipster#1409]
As per [SecurityConfiguration definition](../blob/master/app/templates/src/main/java/package/config/_SecurityConfiguration.java#L133) any authenticated connection can access to the _/api/**_ endpoints (/api/users for example).

Looks risky to have this kind of configuration by default.

**Comment by jdubois** [comment]
Yes, this is intended this way.

There are some websites (Github for instance) where you have all user info even without being logged in. Then, this is a business decision, it depends on what you want to do.

Here we don't give important info on users, and once again you should secure your REST endpoint if your business requirements are different, and we can't know what your requirements are.

**Comment by alexfdz** [comment]
Good point!
