### ISSUE TITLE
Ability to extend the ci-cd sub-generator in blueprints

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster#14097]
##### **Overview of the feature request**

Hi all wonderful community, I would like to replace the ci-cd  index subgenerator with a [generator-base-blueprint](https://github.com/jhipster/generator-jhipster/blob/ae893d0f6e53d648641d96ced0ab0f6058fbe29e/generators/generator-base-blueprint.js) extension, because in this moment it inherits from the [generator-base class](https://github.com/jhipster/generator-jhipster/blob/ae893d0f6e53d648641d96ced0ab0f6058fbe29e/generators/ci-cd/index.js#L29). So it is not possible to rewrite it in a blueprint.

##### **Motivation for or Use Case**

In [generator-jhipster-nodejs](https://github.com/jhipster/generator-jhipster-nodejs/issues/104) we have that concern.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Yes plz go ahead @amanganiello90
