### ISSUE TITLE
Add property or remove reference to "${start-class}" in pom.xml spring-boot-maven-plugin configuration?

### ISSUE THREAD

**Issue by nickshoe** [jhipster/generator-jhipster#14099]
IntelliJ gives the following error upon pom.xml inspection: `Cannot resolve symbol 'start-class' `

Removing the following tag altogether seems to have no negative effect on the build:

https://github.com/jhipster/generator-jhipster/blob/af5d2a8d18480452573d6ab2f280e5186a337bb9/generators/server/templates/pom.xml.ejs#L1478

Spring Boot seems to automatically search for the main class at compile time, so this tag may be pointless or it may be valued with the generated main class name.

If this edit makes sens to you, I can do the PR.

**Comment by pascalgrimaud** [comment]
If it works without it, yes, let's remove it
But we need to check:
- start with IntelliJ Community + Ultimate
- start with command line: mvn / gradle
- start with jar (will be tested by the CI)

**Comment by gmarziou** [comment]
@nickshoe could you check that manifest of built jar is the same because I think this is where start-class used?

The alternative would be to define this property to its correct value.

**Comment by nickshoe** [comment]
@pascalgrimaud ok, I will perform those checks!
@gmarziou sure, thanks. I'll check that too.

In any case, I think it's better to specify the main class explicitly because it would make the code speak for himself.

**Comment by nickshoe** [comment]
Removing the `${start-class}` reference doesn't affect the generated jar manifest (please see the image below).
Actually, the "start-class" property doesn't exist in the pom's build properties declaration and I haven't found any reference online about this property being magically valued somewhere else.
I'll go ahead with the other checks.

![pom-without-start-class-jar-manifest](https://user-images.githubusercontent.com/32668766/109421158-7ce0c680-79d6-11eb-9029-67706540564e.jpeg)
![image](https://user-images.githubusercontent.com/32668766/109421194-9e41b280-79d6-11eb-9fdb-04abf9771d97.png)

**Comment by vishal423** [comment]
If we don't specify an explicit start class, then, spring boot maven plugin will search for one in the classpath and use that. In most scenarios, it shall work without any issue. However, if the plugin finds more than one class with a `main` method, then in absence of an explicit `start-class`, a conflict would appear. Since that's the standard spring boot behavior, I think it's fine to remove it.

**Comment by nickshoe** [comment]
Removing `${start-class}`, checks results:
- IntelliJ Community + Ultimate: both ok
- mvn: ok
- gradle: the generator already explicitely specify the main class name -> no changes required
  https://github.com/jhipster/generator-jhipster/blob/6aa419c4d4e8a19310df743aebe5b15979a63708/generators/server/templates/build.gradle.ejs#L114-L116
- `mvn clean` -> `mvn package` -> `java -jar target/jhipster-0.0.1-SNAPSHOT.jar`: ok

I'll go ahead and specify an explicit value for `start-class` property in pom.xml only, since Gradle is already ok.

**Comment by nickshoe** [comment]
I made the PR but tests are failing due to some errors.
Actually, I don't think they're related to the changes in the PR.

https://dev.azure.com/jhipster/generator-jhipster/_build/results?buildId=18290&view=logs&j=b82dda55-0fb5-5cba-f633-5f7ed4bfc689&t=8cb150ad-72b5-5f82-9010-b4c6dcf290af&l=891

**Comment by pascalgrimaud** [comment]
I'm restarting the builds

**Comment by nickshoe** [comment]
@pascalgrimaud now that error doesn't happen anymore, but there is another one:
https://github.com/jhipster/generator-jhipster/pull/14104/checks?check_run_id=2005824364#step:26:1024

**Comment by nickshoe** [comment]
I've rebased the PR branch against the upstream main branch. Tests are running again.

**Comment by nickshoe** [comment]
@pascalgrimaud I've rebased again and now all tests are passing.
