### ISSUE TITLE
Using h2 with reactive-ms fails to compile

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#14107]
##### **Overview of the issue**

Running `jhipster jdl reactive-ms` results in a compile error in the gateway project:

```
> Task :compileJava
Note: Hibernate JPA 2 Static-Metamodel Generator 5.4.27.Final
/Users/mraible/reactive-stack/gateway/src/main/java/com/okta/developer/gateway/config/WebConfigurer.java:43: error: method initH2Console in class H2ConfigurationHelper cannot be applied to given types;
            H2ConfigurationHelper.initH2Console();
                                 ^
  required: ServletContext
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: /Users/mraible/reactive-stack/gateway/src/main/java/com/okta/developer/gateway/service/ColumnConverter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.
```

##### **Motivation for or Use Case**

It should be possible to run `jhipster jdl reactive-ms` and all e2e tests pass, as you could with previous beta releases.

##### **Reproduce the error**

Run `jhipster jdl reactive-ms` and then build the gateway's Docker container.

##### **JHipster Version(s)**

`main` branch.

**Comment by atomfrede** [comment]
Do have a local build jhipster-bom project? You need a version with this pr https://github.com/jhipster/jhipster-bom/pull/165

**Comment by mraible** [comment]
If I update and install my `jhipster-bom` project locally, it works. I guess I expected it to be published as a snapshot. I'm guessing it isn't since the published SNAPSHOT is for all beta releases?

**Comment by murdos** [comment]
> 
> I expected it to be published as a snapshot. I'm guessing it isn't since the published SNAPSHOT is for all beta releases?

It used to work until we switch from [jhipster](https://github.com/jhipster/jhipster) to jhipster-bom, because @jdubois had a private repository that was publishing snaphots, but I don't think he has setup the same thing for jhipster-bom.

**Comment by jdubois** [comment]
Oh yes, let me do the same.
I’ll update the ticket when it’s done.

**Comment by jdubois** [comment]
Done. It should be published at midnight, let's wait until tomorrow to check!

**Comment by jdubois** [comment]
It's looking good, so I'm closing this. Please ping me if you encounter any issue here, as it's done from one of my private repos (because of access rights).

**Comment by murdos** [comment]
Thanks @jdubois !!!
