### ISSUE TITLE
[Angular] ConfigService should be renamed

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#14109]
##### **Overview of the issue**
The only function of config.service.ts is either to set the endpoint prefix or get the endpoint. I propose renaming the class to `EndpointService` or `EndpointConfigService` to make more sense of its functions.

##### **Motivation for or Use Case**
Users having already an (or creating a new) entity called `Config` will get the following error:
`Import declaration conflicts with local declaration of 'ConfigService'`

Which means the class name is the same as a class we're importing. Keeping the current name will result in errors when upgrading to users having said entity.

Another motivation would be to have a class with a name that tells what does the class do as "ConfigService" is too generic.

##### **Reproduce the error**

While using the main branch
* create a new project with Angular as frontend 
* add an entity called Config
* Open entity's ConfigService.

##### **Related issues**

None that I know of.

##### **Suggest a Fix**

Rename ConfigService class to either `EndpointService` or `EndpointConfigService` (or any other name that makes sense) so users that already have an entity called Config will have no issue migrating.

##### **JHipster Version(s)**
7.0.0-beta.1

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.amatosg"
    },
    "jhipsterVersion": "7.0.0-beta.1",
    "applicationType": "monolith",
    "baseName": "ConfTestProject",
    "packageName": "com.amatosg",
    "packageFolder": "com/amatosg",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "caffeine",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "spacelab",
    "clientThemeVariant": "primary",
    "testFrameworks": [],
    "jhiPrefix": "fa",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": [],
    "creationTimestamp": 1580194041932,
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "pages": [],
    "withAdminUi": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "reactive": false,
    "lastLiquibaseTimestamp": 1614565273000,
    "entities": ["Config"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Config {
  description String required
}
dto Config with mapstruct
paginate Config with pagination
service Config with serviceImpl
filter Config

</pre>
</details>

##### **Browsers and Operating System**
Not related.

- [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by mshima** [comment]
ConfigService is supposed to carry all constants from https://github.com/jhipster/generator-jhipster/tree/main/generators/client/templates/angular/src/main/webapp/app/config for improved microfrontend support.
But since:
- that’s not the case yet
- webpack 5 support will only come with angular 12

It currently contains 1 constant that was outside config folder, so it was not shared between microfrontends.

This can be done for jhipster 7 and reevaluated later.

**Comment by amatosg** [comment]
if not renaming to the proposed names, please consider renaming it anything as it will impact in users having already a _Config_ entity

**Comment by mraible** [comment]
How about `ApiConfigService`?

**Comment by pascalgrimaud** [comment]
In the past, we used Jhi prefix, to prevent this kind of problem, because the prefix can be customized too.
Maybe we could use the same logic

**Comment by mshima** [comment]
Could be ApplicationConfig, or use shell microfrontend term, AplicationShellConfig.

**Comment by amatosg** [comment]
> In the past, we used Jhi prefix, to prevent this kind of problem, because the prefix can be customized too.
> Maybe we could use the same logic

I like this approach, is parameterized and in the hand of the user, and also with a default value in mind avoiding conflicts
