### ISSUE TITLE
Spring ElasticSearch not imported in Gradle

### ISSUE THREAD

**Issue by alexcibotari** [jhipster/generator-jhipster#1410]
if you select ElasticSearch, gradle not import dependency for spring-data-elasticsearch:
 compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-elasticsearch'

**Comment by atomfrede** [comment]
You're right. Will take care of it today.

**Comment by alexcibotari** [comment]
How I can fix this bug in your repository? I want to help your team, If I will find some additional bug in future

**Comment by atomfrede** [comment]
All information are available in the [contributing file](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md)

**Comment by atomfrede** [comment]
@alexcibotari Why did you close your PR? Looked quite good (maybe don't use ``my-fix-branch`` for your branch). Will you reopen the pull request?

**Comment by alexcibotari** [comment]
I done all how it was describe in contribution file :(, 
I will try again :) I want to contribute for this project, I like it :+1:

**Comment by alexcibotari** [comment]
Done again, I can delete my branch just after you merge sources ?

**Comment by atomfrede** [comment]
yes, after your changes are merged you can delete your branch.

**Comment by atomfrede** [comment]
@jdubois I think you can close this issue

**Comment by jdubois** [comment]
Cool, thanks!
