### ISSUE TITLE
I don't have a remember-me check-box on Login page with token auth

### ISSUE THREAD

**Issue by davykiala** [jhipster/generator-jhipster#1411]
I've generated an app with token authentication choice. When i go to the login page, i don't have remember-me check box. Perhaps it normal but there is any information about it on page http://jhipster.github.io/security.html.

**Comment by jdubois** [comment]
Yes, remember me should be specific to session-based authentication (and that's the only part of the doc where we describe it).
I will check it, but this looks normal to me, and at the right part in the doc.
