### ISSUE TITLE
Move the blueprint generator to the JHipster 7 architecture

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#14135]
The JHipster 7 release is about to come. We need to upgrade this generator to match the breaking changes introduced in this new major version.

I have created a v7 branch: https://github.com/jhipster/generator-jhipster-blueprint/tree/jhipster-7

here is what I'm thinking about:
- [x] remove setupXXXOptions calling
- [x] Add the new lifecycle getters (loading, preparing, etc...)
- [x] Generate GitHub action file instead of Travis
- [x] Check generated tests
- [x] CI is green
- [x] Update the documentation https://github.com/jhipster/jhipster.github.io/pull/1088
- [x] according to @ruddell support the followings sub-gen heroku, cypress, page, entities, and ci-cd
- [x] Use async/wait @mshima 

Feel free to add anything you think it's mandatory for the v7 release.

**Comment by pascalgrimaud** [comment]
Can you add a new item to your list plz @avdev4j ?
- update the documentation

**Comment by avdev4j** [comment]
Done!

I have also opened a PR for fixing some parts of the documentation. We can merge it now while we need to wait for the other one (related to the v7).

please find this PR here: 
https://github.com/jhipster/jhipster.github.io/pull/1087

**Comment by mshima** [comment]
Why don't we integrate integrate generator-jhipster-blueprint into generator-jhipster?
- No need to install `yo` which is somewhat unmaintained.
- Easy as jhipster create-blueprint.
- It's a quite small generator.
- Will generate a blueprint for current installed blueprint.

**Comment by avdev4j** [comment]
@mshima I'm 100% in favor of that. Btw, this generator is not maintained enough, maybe it could help.

If we do that, we need to do it for modules also.

**Comment by murdos** [comment]
> 
> Why don't we integrate generator-jhipster-blueprint into generator-jhipster?
> 
>     * No need to install `yo` which is somewhat unmaintained.
> 
>     * Easy as jhipster create-blueprint.
> 

The only downside I see is that the `jhipster` cli is mainly used to work inside a project generated with jhipster.
Whereas here the use case is a bit different: you want to customize the jhipster generator by generating a blueprint.
So different context, and also different target user (generator developer vs generator user).

**Comment by avdev4j** [comment]
after all, I'm not sure it could be a good idea because of what you said @murdos
not sure it will help to maintain it better...

**Comment by mshima** [comment]
I really don't see benefits on having to install `yo` if `jhipster` will be installed for both blueprint developer and generator user.
It will improve integration:
- `generator-jhipster-blueprint` uses `generator-hipster` resources for tests https://github.com/jhipster/generator-jhipster-blueprint/blob/68e5dd1905726cbb260e340fabea97b5c427a154/.github/workflows/github-ci.yml#L64-L66.
- `jhipster create-blueprint` will create a blueprint for that exact jhipster version.

IMO it's @murdos call as maintainer and stream leader here.

**Comment by avdev4j** [comment]
Let's open a new ticket for the proposal, maybe more ideas can help to make a decision.

I see pro and cons in both possibilities.

Btw the PR is ready for review so if anybody from @jhipster/developers wants to review it, feel free; so can merge it after that and move to modules ;).

**Comment by deepu105** [comment]
Lets first upgrade the `generator-jhipster-blueprint` to work with v7 and we can discuss separately in another ticket about merging it into main generator

**Comment by murdos** [comment]
> Lets first upgrade the `generator-jhipster-blueprint` to work with v7 and we can discuss separately in another ticket about merging it into main generator

👍

**Comment by pascalgrimaud** [comment]
@mshima : following https://github.com/jhipster/generator-jhipster/pull/14193 do you think we need to upgrade the blueprint generator ?

**Comment by mshima** [comment]
@pascalgrimaud no.
- would require yo@4 which I just released a beta, which should be stable enough, but I will not tag as latest so soon due to backward compatibility check, I will call for testing and wait.
- there isn't many advantages to upgrade, it's mainly cleanup and move features from generator to the environment.

**Comment by avdev4j** [comment]
So there is something else to do here?

**Comment by avdev4j** [comment]
I'm closing this one since the job has been done ;)

**Comment by avdev4j** [comment]
bounty claimed here https://opencollective.com/generator-jhipster/expenses/36160

**Comment by pascalgrimaud** [comment]
@avdev4j : approved
