### ISSUE TITLE
Hazelcast configs are not compatible with its management center

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#14133]
##### **Overview of the issue**

Current Hazelcast map names seem not being loadable by its management center and so the cache information.
![image](https://user-images.githubusercontent.com/5289123/109606904-b2f88480-7b55-11eb-9e78-bbb8db22ed66.png)

##### **Motivation for or Use Case**

Jhipster configs should be able to work with hazelcast management center.

##### **Reproduce the error**

1. Create a monolith app with hazelcast
2. Start the app
3. Run the standalone hazelcast management center by downloading it.(Generated docker file should also work but I have not tried it)
4. Login and see that cache information from members are not displayed.

##### **Suggest a Fix**

In the `CacheConfiguration.java`, change following to use `addMapConfig` method and set the map name inside each method.

```
// config.getMapConfigs().put("default", initializeDefaultMapConfig(jHipsterProperties));
// config.getMapConfigs().put("mm.com.dat.jlpt.domain.*", initializeDomainMapConfig(jHipsterProperties));

config.addMapConfig(initializeDefaultMapConfig(jHipsterProperties));
config.addMapConfig(initializeDomainMapConfig(jHipsterProperties));
```

```
private MapConfig initializeDefaultMapConfig(JHipsterProperties jHipsterProperties) {
//         MapConfig mapConfig = new MapConfig();
        MapConfig mapConfig = new MapConfig("default");
................................
```
```
private MapConfig initializeDomainMapConfig(JHipsterProperties jHipsterProperties) {
//        MapConfig mapConfig = new MapConfig();
        MapConfig mapConfig = new MapConfig("mm.com.dat.jlpt.domain.*");
.................................
```

Followings are the resulting config xml snippet without&with name attribute.
You can see the difference from management center before and after fixing.

Before
```
<hazelcast xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-4.1.xsd">
.......
<map>  <-- this should be for default
</map>
<map>  <-- this should be for mm.com.dat.jlpt.domain.*
</map>

.......
</hazelcast>
```

After
```
<hazelcast xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-4.1.xsd">
.......
<map name="default">
</map>
<map name="mm.com.dat.jlpt.domain.*">
</map>

.......
</hazelcast>
```
##### **JHipster Version(s)**
Current `main` branch

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Can you take the ticket and do the fix plz @pmverma ?
