### ISSUE TITLE
Current PUT method doesn't follows HTTP specification.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#14139]
##### **Overview of the feature request**

Our current PUT api is identical to our POST api, with the difference of id validation.
According to HTTP specification, PUT should contain id in the URL `api/my-entity/<id>` instead of just `api/my-entity`.

So when executing PUT `api/my-entity/<id>`, a subsequent GET `api/my-entity/<id>` will return the same object.

Some references:
https://stackoverflow.com/questions/630453/put-vs-post-in-rest
https://tools.ietf.org/html/rfc7231#section-4.3.4

##### **Motivation for or Use Case**

While working with composite ids with manually generated ids, I came across this question and seems a valid issue.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Well, not really. The IETF page doesn't specify anything about IDs. Theoretically, one can omit ID as a request param but still pass a payload containing just enough information to update a resource (and still guarantee idempotency).

While I do agree seeing `PUT /resources/:id` is really common in CRUD use-cases, it's only a convention.

**Comment by mshima** [comment]
> Well, not really. The IETF page about the PUT verb use doesn't make IDs absolutely mandatory. 

Agreed with that.

```
   A successful PUT of a given
   representation would suggest that a subsequent GET on that same
   target resource will result in an equivalent representation being
   sent in a 200 (OK) response.
```

If I understand right, `PUT /resources/` with a payload, a subsequent `GET /resources/` should return the same payload.

Not guaranteed, since it could be overridden:
```
   However, there is no guarantee that
   such a state change will be observable, since the target resource
   might be acted upon by other user agents in parallel, or might be
   subject to dynamic processing by the origin server, before any
   subsequent GET is received.
```

In our case, when we use `PUT /resources/` with a payload, `GET /resources/` never returns the payload, but a list of entities.

> While I do agree seeing `PUT /resources/:id` is really common in CRUD use-cases, it's only a convention.

Anyway, as you said, this is just a convention, but this convention seems to be the right approach according to specifications.

**Comment by MathieuAA** [comment]
>  Not guaranteed, since it could be overridden

@mshima exactly. POST may create a resource (or at the very least is expected to return something different each time). When one does a PUT, one should then expect a GET to return the current state, or the response of the previous PUT... only if the PUT comes RIGHT BEFORE the GET (no other system calls to update the resource). We got that right.

> Anyway, as you said, this is just a convention, but this convention seems to be the right approach according to specifications.

It's _a_ good enough approach, but it's like Agile and Scrum. The spec is broader that what the CRUD conventions tell (very much like the confusion between Agile & Scrum, here Agile is the spec, Scrum is CRUD). If we choose to follow the CRUD conventions, like almost every company does in the world (speaking for REST of level 1 at least), our way isn't too bad an implementation.

WDYT @cbornet? I know you love REST-related things when you're not in the swimming pool ;)

**Comment by cbornet** [comment]
I'm with @mshima on this :smiley: . I think it's better to do the PUT on the target URI.
Since it's a breaking change, it's probably the good time to do it for v7.
