### ISSUE TITLE
SB version 2.4.2/3 are mixed

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#14131]
##### **Overview of the issue**

Current jhipster bom is using SB 2.4.3 as parent however maven SB version property has not been updated to 2.4.3.
And hence, only 2.4.2 is being used.

##### **Motivation for or Use Case**

Version should be consistent

##### **Related issues**

https://github.com/jhipster/jhipster-bom/pull/183
##### **Suggest a Fix**

Update maven property 
##### **JHipster Version(s)**

`main` branch
##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
it is still in progress here: https://github.com/jhipster/generator-jhipster/pull/14043

**Comment by pmverma** [comment]
Oh thanks @pascalgrimaud, I missed that PR.

**Comment by DanielFran** [comment]
Closed via https://github.com/jhipster/generator-jhipster/pull/14043
