### ISSUE TITLE
Entity names with Detail 

### ISSUE THREAD

**Issue by christophe-f** [jhipster/generator-jhipster#1414]
Hi,

After generating entities, the UI stopped working. It seems that if you are using 'Detail' in the entity name, such as Order and OrderDetail, the second one will cause issues in the angular route names /orderDetail and /orderDetailDetail

**Comment by jdubois** [comment]
Strange, are you sure this is because of the "Detail" suffix? Can you try with another suffix, just to check?

**Comment by christophe-f** [comment]
Here are more info:

When creating the 'Order' entity, it generates a /scripts/app/entities/order/order.js file containing 2 states ('order' and 'orderDetail')

Then when creating the 'OrderDetail' entity, it generates a /scripts/app/entities/orderDetail/orderDetail.js file containing 2 states ('orderDetail' and 'orderDetailDetail')

AngularJS is complaining about the 2 'orderDetail' routes as it's not unique.

Same about the controllers names. AngularJS doesn't complain about it, but some weird behaviour may happen.

I have switched to 'OrderItem' instead of 'OrderDetail'. Maybe a note can be added into the documentation to say that the 'Detail' suffix is a system reserved keyword.

**Comment by jdubois** [comment]
OK, I understand the routes issue :-(

**Comment by jdubois** [comment]
There is no easy solution here: I'm going to forbid using the "detail" suffix for an entity
