### ISSUE TITLE
All JDL Options are missing

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#14146]
##### **Overview of the issue**

I recall going to [this page](https://www.jhipster.tech/jdl/options#available-options) to see all the options you can use in JDL. For example, database types, authentication types, etc. Now they're gone. Did they get moved or deleted somehow?

##### **Motivation for or Use Case**

It's nice to see all options in JDL when modifying EJS templates.

**Comment by MathieuAA** [comment]
Hi Matt! Are you looking for [this](https://www.jhipster.tech/jdl/applications#available-application-configuration-options)?

**Comment by MathieuAA** [comment]
What I did to find them:
  - in the left-side pane, click JDL
  - for the type of thing you're playing with (fields, apps, etc.) click on the link and go to the bottom of the page

I guess theses pages are pretty important (even for me). Maybe we should find a way to make them more visible?

**Comment by mraible** [comment]
@MathieuAA Yes, that's the guide I'm looking for! I searched for "jhipster jdl" and landed on https://www.jhipster.tech/jdl/options. Maybe a link to application options on that page would help?

**Comment by MathieuAA** [comment]
Tell me what you think.
The user searches for the JDL app options, and lands of the regular options page. The user then sees this isn't what she/he's looking for and notices a "See also" section on the page which redirects to the app options.

Would that be enough?

I'm thinking:
  - regular options => app options
  - app options => regular options

**Comment by mraible** [comment]
Works for me!
