### ISSUE TITLE
Switching language doesn't change locale 

### ISSUE THREAD

**Issue by omrzljak** [jhipster/generator-jhipster#1415]
When user switch language also locale in tmhDynamicLocale should be changed. At least , that is what I understood from angular code generated by jhipster. 

There is small fault in app.js : 
```javascript
tmhDynamicLocaleProvider.useCookieStorage('NG_TRANSLATE_LANG_KEY');
```
tmhDynamicLocaleProvider.useCookieStorage is paramterles function. To set used key you have to put 
```javascript
tmhDynamicLocaleProvider.useCookieStorage();
tmhDynamicLocaleProvider.storageKey('NG_TRANSLATE_LANG_KEY');
```

This will trigger that appropriate locale is loaded on every time app is started. But to do this dynamicly on language change we need to alter language.controller.js. 
Add this call into changeLanguage() function
```javascript
            tmhDynamicLocale.set(languageKey);
```
And add tmhDynamicLocale. in dependencies.

with this addition switching language will switch locale also. But this is not yet full solution. Because for one language we have more locales.

**Comment by jdubois** [comment]
I'm not sure I understood everything you said -> I've made some changes, they look good, and I'll close this ticket when my code is pushed, but please have a look at what I did, and don't hesitate to comment!!!

**Comment by omrzljak** [comment]
Now it is good !
