### ISSUE TITLE
Fake data fails when there is a required oneToOne relationship with user entity

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#14158]
##### **Overview of the issue**

Fake data generated is wrong when there is a oneToOne relationship with user entity. This results in error during startup

```
Liquibase could not start correctly, your database is NOT ready: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20210304131457_added_entity_CustomerDetails.xml::20210304131457-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.UX_CUSTOMER_DETAILS__USER_ID_INDEX_E ON PUBLIC.CUSTOMER_DETAILS(USER_ID) VALUES 1"; SQL statement:
INSERT INTO PUBLIC.customer_details(id, gender, phone, address_line_1, address_line_2, city, country, user_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?) [23505-200]

liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20210304131457_added_entity_CustomerDetails.xml::20210304131457-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.UX_CUSTOMER_DETAILS__USER_ID_INDEX_E ON PUBLIC.CUSTOMER_DETAILS(USER_ID) VALUES 1"; SQL statement:
INSERT INTO PUBLIC.customer_details(id, gender, phone, address_line_1, address_line_2, city, country, user_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?) [23505-200]
```

##### **JHipster Version(s)**

```
store@0.0.1-SNAPSHOT /home/deepu/workspace/temp/jhiIng
└── generator-jhipster@7.0.0-beta.1 

```

##### **JDL for the app**

<details>
<summary>JDL entity definitions</summary>

<pre>
application {
  config {
    baseName store
    packageName com.jhipster.demo.store
    authenticationType jwt
    prodDatabaseType mysql
    buildTool gradle
    clientFramework react
    enableTranslation true
    nativeLanguage en
    languages [en, nl]
  }
  entities *
}

/**
 * Product sold by the Online store
 */
entity Product {
  name String required
  description String
  price BigDecimal required min(0)
  size Size required
  image ImageBlob
}
entity ProductCategory {
  name String required
  description String
}
entity CustomerDetails {
  gender Gender required
  phone String required
  addressLine1 String required
  addressLine2 String
  city String required
  country String required
}
entity ShoppingCart {
  placedDate Instant required
  status OrderStatus required
  totalPrice BigDecimal required min(0)
  paymentMethod PaymentMethod required
  paymentReference String
}
entity ProductOrder {
  quantity Integer required min(0)
  totalPrice BigDecimal required min(0)
}
enum Size {
  S,
  M,
  L,
  XL,
  XXL
}
enum Gender {
  MALE,
  FEMALE,
  OTHER
}
enum OrderStatus {
  COMPLETED,
  PAID,
  PENDING,
  CANCELLED,
  REFUNDED
}
enum PaymentMethod {
  CREDIT_CARD (card),
  IDEAL (ideal)
}

relationship OneToOne {
  CustomerDetails{user(login) required} to User
}
relationship OneToMany {
  ProductCategory{product} to Product{productCategory(name) required}
  CustomerDetails{cart} to ShoppingCart{customerDetails required}
  ShoppingCart{order} to ProductOrder{cart required}
}
relationship ManyToOne {
  ProductOrder{product(name) required} to Product
}

paginate Product, ProductCategory, CustomerDetails with pagination
service Product, ProductCategory, CustomerDetails, ShoppingCart, ProductOrder with serviceClass

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Linux amd64-64-Bit Compressed References 20201022_810 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)

git version 2.26.2

node: v12.16.2

npm: 6.14.4

yeoman: 2.0.0

Docker version 20.10.3, build 48d30b5

docker-compose version 1.27.1, build 509cfb99
  

##### **Browsers and Operating System**

NA

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Handling user relationship is a little tricky.

https://github.com/jhipster/generator-jhipster/issues/9579#issuecomment-519842714
