### ISSUE TITLE
 Specifying a display field "firstName" in a relationship with user using jdl make generator fail

### ISSUE THREAD

**Issue by VergilSkye** [jhipster/generator-jhipster#14164]
##### **Overview of the issue**

jhipster generator v7 beta.1 doesn't allow specifying the display field "firstName" in a relationship with user using a jdl.
I made some test and the only display fields allowed are: id and login

I tried to import this jdl in version 7 beta 1 and didn't work, in the older version 6.10.5 work just fine.

entity Ball {
    fieldName String
}
relationship ManyToOne {
    Ball{user(firstName)} to User
}

this is the stack error

info Creating changelog for entities Ball
Error running generator entities: Error: Error looking for field firstName at User
Error: Error looking for field firstName at User
    at prepareRelationshipForTemplates (/home/qualitytecnologia/4Q/jh7-arqueo/node_modules/generator-jhipster/utils/relationship.js:130:19)
    at /home/qualitytecnologia/4Q/jh7-arqueo/node_modules/generator-jhipster/generators/entity/index.js:532:21
    at Array.forEach (<anonymous>)
    at EntityGenerator.prepareRelationshipsForTemplates (/home/qualitytecnologia/4Q/jh7-arqueo/node_modules/generator-jhipster/generators/entity/index.js:531:44)
    at Object.<anonymous> (/home/qualitytecnologia/4Q/jh7-arqueo/node_modules/yeoman-generator/lib/index.js:991:25)
    at /home/qualitytecnologia/4Q/jh7-arqueo/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /home/qualitytecnologia/4Q/jh7-arqueo/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/home/qualitytecnologia/4Q/jh7-arqueo/node_modules/yeoman-generator/lib/index.js:992:11)
    at processImmediate (internal/timers.js:456:21)
ERROR! Error looking for field firstName at User
Error: Error looking for field firstName at User
    at prepareRelationshipForTemplates (/home/qualitytecnologia/4Q/jh7-arqueo/node_modules/generator-jhipster/utils/relationship.js:130:19)
    at /home/qualitytecnologia/4Q/jh7-arqueo/node_modules/generator-jhipster/generators/entity/index.js:532:21
    at Array.forEach (<anonymous>)
    at EntityGenerator.prepareRelationshipsForTemplates (/home/qualitytecnologia/4Q/jh7-arqueo/node_modules/generator-jhipster/generators/entity/index.js:531:44)
    at Object.<anonymous> (/home/qualitytecnologia/4Q/jh7-arqueo/node_modules/yeoman-generator/lib/index.js:991:25)
    at /home/qualitytecnologia/4Q/jh7-arqueo/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /home/qualitytecnologia/4Q/jh7-arqueo/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/home/qualitytecnologia/4Q/jh7-arqueo/node_modules/yeoman-generator/lib/index.js:992:11)

##### **Motivation for or Use Case**

the end user should be allow, at least, to select firstName and lastName as display field relationship between user and another entity

##### **Reproduce the error**
generetar a jhipster project with version 7 beta 1
import the jdl with jhipster jdl app.jdl
Error appears: Error running generator entities: Error: Error looking for field firstName at User

##### **Suggest a Fix**

entity user, in the generator, has to have firstName in fieldName

##### **JHipster Version(s)**

```
arqueo-7@0.0.1-SNAPSHOT /home/qualitytecnologia/4Q/jh7-arqueo
└── generator-jhipster@7.0.0-beta.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "arqueo7",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1614899209891,
    "promptValues": {
      "packageName": "br.com.qualitytecnologia",
      "nativeLanguage": "pt-br"
    },
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "br.com.qualitytecnologia",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "packageFolder": "br/com/qualitytecnologia",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["pt-br"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Ball {
      fieldName String
   }
   relationship ManyToOne {
     Ball{user(firstName)} to User
   }
</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

git version 2.25.1

node: v12.18.2

npm: 6.14.5

yeoman: 3.1.1

Docker version 20.10.5, build 55c4c88

docker-compose version 1.25.0, build unknown

##### **Browsers and Operating System**

Ubuntu 20.04
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
First name and last name seems incomplete to me.
IMO the best approach would be to create a full name dto mapping, but not sure it makes sense to create in jhipster by default.
Anyway, you can create a PR adding the fields you are missing here: https://github.com/jhipster/generator-jhipster/blob/b0fed8a48a58b1de98c79acef90268f75b56ad31/generators/generator-base-private.js#L1634-L1639

**Comment by VergilSkye** [comment]
I made a fork and made this changes but but it didn't fix. Frontend errors appeared like: _**_Property 'firstName' does not exist on type 'IUser_**_
So I noticed that there is a **UserDTO** and  a new **AdminUserDTO** in v7. 
@mshima can you help me with a piece of code? 
In the _**_PublicUserResource_**_ has the endpoint  _getAllPublicUsers_:
```java
@GetMapping("/users")
    public ResponseEntity<List<UserDTO>> getAllPublicUsers(Pageable pageable) {
        log.debug("REST request to get all public User names");
       // Omit for succinctness
       } 
```

this is the only endpoint that return a UserDTO and in the log message say:  "_gell all public User names_" but this dto doesn't have any name, only **id** and **login**.

So UserDTO shoud have a fullName or at least firstName and lastName?

Can you let me know where is UserDTO and IUser file in the generator, i'm still bit lost

**Comment by VergilSkye** [comment]
ok, i didn't notice that:
In my project there's 2 interfaces **IUser**. One it’s inside _app/admin/user-management.model.ts_ and it's created when I **generated** the project. The other interface it's inside _app/entities/user/user.model.ts_ and it's created when **importing** the jdl with the relationship.

should have two interface IUser with different properties?

**Comment by mshima** [comment]
Your are right, this was done for privacy reasons, to get the entire user needs admin rights.

So the fix is to add the missing field at:
https://github.com/jhipster/generator-jhipster/blob/b0fed8a48a58b1de98c79acef90268f75b56ad31/generators/generator-base-private.js#L1634-L1639

Loop over the used fields for relationships
```
for (field of user.otherRelationships.map(relationship => relationship.otherEntityField)) {
  implement field api.
}
```

- add them to the server:
https://github.com/jhipster/generator-jhipster/blob/d7dd98fe235e086351aa86e7eb8db1fa1d171745/generators/server/templates/src/main/java/package/service/dto/UserDTO.java.ejs#L58-L73

- add them to the client:
https://github.com/jhipster/generator-jhipster/blob/d7dd98fe235e086351aa86e7eb8db1fa1d171745/generators/client/templates/angular/src/main/webapp/app/entities/user/user.model.ts.ejs#L22-L31

Not sure if it is complete.
