### ISSUE TITLE
Feature Request: Can Angular Translate be an option while generating an app?

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1416]
Instead of making Angular translate and everything related to translate default, can it be an option while generation? I know I can just remove the default french translation and work but still for just using English the entire translation services riding on top of everything is unnessery right? that too with the occasional fliker of foo.some.title

**Comment by deepu105** [comment]
Sorry if its too Ambitious, I have anyways removed the translate part manually, But i thought could be useful to others if its an option as well helps when upgrading jhipster versions on translation removed projects

**Comment by jdubois** [comment]
I'd love to, but this is such a huge change, it just can't be done and maintained.
Our initial choice is to have i18n by default, as a "good practice", but I fully agree that when it's not needed, it's really a pain.
Making it optional would require to have switches everywhere in the code: this looks a really lot, lot of work, and I personally don't have enough time for this.
Of course, if anybody wants to do a PR, this should be merged.

**Comment by deepu105** [comment]
Still learning Yo and stuff, so once I'm confident enough I will attempt a PR on this. Ya agree that it is spread over so many placed and I had a tough time removing it from everywhere :smile:

**Comment by deepu105** [comment]
@jdubois : Have started working on this, will try to provide a PR by this week.
Need few suggestions from you, below is the approach Im doing.

1. Add one more question in the main generator as below
```
{
            type: 'confirm',
            name: 'enableTranslation',
            message: '(15/15) Would you like to enable translation support with Angular Translate?',
            default: true
        }
```
default is true so that existing users will not have a conflict when upgrading, do below when option is set as `false`
2. skip installing the language files and js while generating
3. skip dependencies in bower
```
<% if (enableTranslation) { %>
    "angular-i18n": "1.3.15",
    "angular-translate": "2.7.0",
    "angular-translate-storage-cookie": "2.7.0",
    "angular-translate-loader-partial": "2.7.0",
    "angular-dynamic-locale": "0.1.27",<% } %>
```
Now is angular-i18n required? I have removed it in my projects and had no issues. I didnt see any other explicit usage anywhere. what about date and currency filters, should we leave this in even if translation is disabled
4. server side changes:
     * ```AngularCookieLocaleResolver``` is related to translation but this could be left intact for non translation as well i guess, any suggestion?
     * `LocaleConfiguration` skip the language part
     * make changes to skip reading mail messages in i18n 
     * make changes to handle lang key for user
Anything I missed?
5. make changes in the Java and JS tests to skip translation stuff
6. skip translate filter usage in all html and reference in JS files, skip `translatePartialLoader` in route configs
7. do the same for entity generator
8. Display friendly error message in language stub generator when user tries to install language in a translation disable app

so did I miss anything? any suggestions?

**Comment by deepu105** [comment]
currently the thymeleaf templates are just copied,but in order to make translation optional we would need to process it first so I change lines 536-537 in `app/index.js` to below
```
// Create mail templates
    this.template(resourceDir + '/mails/activationEmail.html', resourceDir + 'mails/activationEmail.html', this, {});
    this.template(resourceDir + '/mails/passwordResetEmail.html', resourceDir + 'mails/passwordResetEmail.html', this, {});
```

But there seems to be a problem

yeoman tries to process the baseUrl in `th:href="@{|${baseUrl}/#/reset/finish?key=${user.resetKey}|}"` and throws below error, any idea on how to ignore this?

```
undefined:31
((__t = (baseUrl)) == null ? '' : __t) +
         ^
ReferenceError: baseUrl is not defined
    at eval (eval at template (D:\Projects\GIT\generator-jhipster\node_modules\yeoman-generator\node_modules\lodash\dist
\lodash.js:6306:22), <anonymous>:31:10)
    at JhipsterGenerator.underscore [as _engine] (D:\Projects\GIT\generator-jhipster\node_modules\yeoman-generator\lib\u
til\engines.js:31:45)
    at JhipsterGenerator.engine (D:\Projects\GIT\generator-jhipster\node_modules\yeoman-generator\lib\actions\actions.js
:314:10)
    at JhipsterGenerator.template (D:\Projects\GIT\generator-jhipster\node_modules\yeoman-generator\lib\actions\actions.
js:289:15)
    at JhipsterGenerator.app (D:\Projects\GIT\generator-jhipster\app\index.js:537:10)
    at D:\Projects\GIT\generator-jhipster\node_modules\yeoman-generator\lib\base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by deepu105** [comment]
OK I ended up using this `'interpolate': /<%=([\s\S]+?)%>/g ` to fix the above issue in the template

**Comment by jdubois** [comment]
Sorry @deepu105 I forgot to re-open this issue.

This must be a huge work? Do you have an idea of the size of your PR? I'm a bit frightened by it, as it will touch a lot of files, as it might be complex to merge.

**Comment by deepu105** [comment]
Hmm so far the changes to core JH generator files are minimal, and Java part I havent changed much, may be just few lines, But on the angular part I have touched all the html and the route js files

so overall the number of files in the commit is gonna be lot due to all the htmls, but I guess if changing those many took a JH newbie like me approx 2 days, reviewing those shouldn't take long for you I hope. Most of the html file changes are just the switches to have translate directive only when translation is enabled

**Comment by deepu105** [comment]
Found a better way to remove translate directive rather than having switch all over the html, will try it out and see, if it works out it should reduce number of files I touch :)

**Comment by jdubois** [comment]
Oh yes, if you can find a way to automatically remove all tags, that would be much, much better!!!!!!!!!

**Comment by deepu105** [comment]
Now I have to revert all the HTML changes I have already made, :sob: 

Btw, Im doing this to remove tags
```
Generator.prototype.stripTranslateDirective = function (_this, webappDir, entry) {
    var directiveRegex = '(translate\="([a-zA-Z0-9](\.)?)+") | (translate-values\="\{([a-zA-Z]|\d|\:|\{|\}|\[|\]|\-|\'|\s|\.)*?\}")'; //looks for something like translate="foo.bar.message" and translate-values="{foo: '{{ foo.bar }}'}"
    var fullPath = webappDir + entry;
    var body = _this.read(fullPath);
    
    var re = new RegExp(directiveRegex, 'g');

    body = body.replace(re, '');

    _this.write(fullPath, body);
}

```

Need to test this out fully

**Comment by jdubois** [comment]
Yes, but this is way cooler than coding everything manually :-)
Looks really great!

**Comment by deepu105** [comment]
yup, but I guess still need to touch HTML files that have placeholder value set from translate. that too can be automated I guess by reading the translate key and getting it from the appropriate json and replacing it but that would be too much of code i guess.

Also I noticed that the text content inside translate placeholders in many of the HTML are not in syc with the corresponding json files, so guess need to update that as well

**Comment by deepu105** [comment]
Have tested out both translation enabled and disabled apps generated. Everything seems to work as expected.

**Comment by deepu105** [comment]
here is the issue which i was talking about earlier

As you can see the json files are loaded and there is no console errors but translation hasn't been applied, this is during a refresh with default English, it works if i refresh again, and sometimes not. This is very annoying as there is no way to debug or reproduce this :cry: 

![image](https://cloud.githubusercontent.com/assets/1107223/7804761/f100ff12-0399-11e5-847a-0cd5e4d7d3b7.png)
