### ISSUE TITLE
Password is stored in local storage

### ISSUE THREAD

**Issue by zzcoder** [jhipster/generator-jhipster#1417]
In auth.session.service.js, it stores user password in token,
```javascript
                   localStorageService.set('token', $window.btoa(credentials.username + ':' + credentials.password));
```
The password can be retrieved from localStorage easily. This is a big security hole. 

We removed the token and it has no ill effect so this might be old code.

**Comment by jdubois** [comment]
I didn't code this, doing a "git blame" shows this code from @amr -> Amir, do you know what this is for?
I agree this shouldn't be stored here, if possible.

Then, it's not such a big security hole: if someone has access to your browser's local storage, you have a much bigger security hole than JHipster!!

**Comment by jdubois** [comment]
I can't find what this is used for, so I'm removing it!
