### ISSUE TITLE
Entities broken with pagination + criteria filter

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#14199]
##### **Overview of the issue**

Can't list entity with using pagination + criteria filter

![beer_entity](https://user-images.githubusercontent.com/9156882/110216649-870c3480-7eb0-11eb-9053-c3a4ff3da8c0.png)

```
2021-03-06 19:15:16.370  WARN 18032 --- [  XNIO-1 task-2] o.z.problem.spring.common.AdviceTraits   : Bad Request: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'productCriteria' on field 'size': rejected value [20]; codes [typeMismatch.productCriteria.size,typeMismatch.size,typeMismatch.io.github.pascalgrimaud.beer.service.criteria.ProductCriteria$SizeFilter,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [productCriteria.size,size]; arguments []; default message [size]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'io.github.pascalgrimaud.beer.service.criteria.ProductCriteria$SizeFilter' for property 'size'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'io.github.pascalgrimaud.beer.service.criteria.ProductCriteria$SizeFilter' for property 'size': no matching editors or conversion strategy found]
```

##### **Suggest a Fix**

It's probably related to ENUM, but not sure

##### **JHipster Version(s)**

```
beer@0.0.0 /home/pgrimaud/tmp/12-beer
└── generator-jhipster@7.0.0-beta.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "vue",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": true,
    "baseName": "beer",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["cypress"],
    "websocket": false,
    "applicationType": "monolith",
    "packageName": "io.github.pascalgrimaud.beer",
    "packageFolder": "io/github/pascalgrimaud/beer",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "entities": ["Product"],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1615053884446,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "lastLiquibaseTimestamp": 1615053944000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Product {
  name String required
  description String
  price BigDecimal required min(0)
  size Size required
  image ImageBlob
}
enum Size {
  S,
  M,
  L,
  XL,
  XXL
}

dto Product with mapstruct
paginate Product with pagination
service Product with serviceClass
filter Product

</pre>
</details>

My JDL

```
application {
  config {
    baseName beer
    applicationType monolith
    packageName io.github.pascalgrimaud.beer
    authenticationType jwt
    devDatabaseType postgresql
    prodDatabaseType postgresql
    buildTool maven
    clientFramework vue
    testFrameworks [cypress]
  }
  entities *
}

entity Product {
  name String required
  description String
  price BigDecimal required min(0)
  size Size required
  image ImageBlob
}
enum Size {
  S, M, L, XL, XXL
}

dto Product with mapstruct
service Product with serviceClass
paginate Product with pagination
filter Product
```

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

git version 2.30.1

node: v14.15.4

npm: 6.14.10

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.27.3, build 4092ae5d

INFO! Congratulations, JHipster execution is complete!

**Comment by pascalgrimaud** [comment]
cc @gzsombor as I start to test criteria filter and it looks like broken for me...
Maybe you have an idea ?

**Comment by pascalgrimaud** [comment]
Ok, I think there is a conflict with `size` field.
If I'm correct, to avoid this, we need to exclude `size`, `page`, etc from Pageable, to avoid conflict with the generated criteria

**Comment by gzsombor** [comment]
Interesting, that's surely the problem with the 'size' parameter. If I modify the integration test for products to call:
`        defaultProductShouldBeFound("size=20");` I get similar http 400 error code:
` {"type":"https://zalando.github.io/problem/constraint-violation","title":"Constraint Violation","status":400,"path":"/api/products","violations":[{"field":"size","message":"Failed to convert property value of type 'java.lang.String' to required type 'tech.jhipster.criteria.service.criteria.ProductCriteria$SizeFilter' for property 'size'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'tech.jhipster.criteria.service.criteria.ProductCriteria$SizeFilter' for property 'size': no matching editors or conversion strategy found"}],"message":"error.validation"} `

Which is kind of make sense, as a 'proper' criteria would be `size.equals=S`, so here it tries to convert '20' to a SizeFilter object.

**Comment by pascalgrimaud** [comment]
Yes, I think there is probably the same problem with sort, page etc.

**Comment by gzsombor** [comment]
Yes, I can confirm that. It shouldn't be too difficult to add these words to the reserved word list, maybe, we could limit it, when JPA + filtering is enabled.

**Comment by pascalgrimaud** [comment]
Should we exclude the use of entity with size, page name ?
Or should we exclude the criteria ?

**Comment by gzsombor** [comment]
The name of the entity in this case is not problematic, only for the field names. In my patch, I've just added check for relational db + non-reactive.
