### ISSUE TITLE
build jhipster with custom parameters

### ISSUE THREAD

**Issue by ivanursul** [jhipster/generator-jhipster#1422]
Hi guys. I am unable to build jhipster with custom parameters
I am doing mvn spring-boot:run -Dspring.datasource.databaseName=[somedatabasename]
and the name of database is not changing.

Could someone tell me how should I override this properties ?

**Comment by gzsombor** [comment]
I think, for maven, you need to specify the parameters slightly differently: -Drun.arguments="--spring.datasource.databaseName=[somedatabasename]"

**Comment by jdubois** [comment]
Yes, because you need to pass the arguments to your JHipster instance, not to Maven.
I think @gzsombor is correct, so I'm closing this -> can you re-open the issue if you still have the problem?
