### ISSUE TITLE
When updating Entities belonging to a Relationship, the entity on the other side is not updated.

### ISSUE THREAD

**Issue by me-kell** [jhipster/generator-jhipster#14228]
##### **JHipster Version(s)**

```
jhipster-sample-application@0.0.1-SNAPSHOT /home/map/jhipster-sample-app
└── generator-jhipster@7.0.0-beta.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "baseName": "jhipsterSampleApplication",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "maven",
    "searchEngine": false,
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": ["gatling", "protractor"],
    "languages": ["en"],
    "serverPort": 8080,
    "jhipsterVersion": "7.0.0-beta.1",
    "enableSocialSignIn": false,
    "useSass": true,
    "jhiPrefix": "jhi",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "reactive": false,
    "otherModules": [],
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientTheme": "none",
    "blueprints": [],
    "embeddableLaunchScript": false,
    "creationTimestamp": 1577000812973,
    "skipUserManagement": false,
    "withAdminUi": true,
    "clientThemeVariant": "",
    "skipClient": false,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "pages": [],
    "nativeLanguage": "en",
    "entities": ["BankAccount", "Label", "Operation"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount {
  name String required
  balance BigDecimal required
}
entity Label {
  label String required minlength(3)
}
entity Operation {
  date Instant required
  description String
  amount BigDecimal required
}
relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)}
}
relationship ManyToOne {
  BankAccount{user(login)} to User
}
relationship ManyToMany {
  Operation{label(label)} to Label{operation}
}

paginate Operation with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)

git version 2.20.1

node: v14.16.0

npm: 6.14.11

Docker version 20.10.5, build 55c4c88

**Reproduced with JHipster versions 6.10.5 and 7.0.0-beta.1 and different jds. And with `https://github.com/jhipster/jhipster-sample-app` versions 6.10.5 and 7.0.0-beta.1 under Debian 10**

##### **Overview of the issue**

When updating Entities belonging to a Relationship, the entity on the other side is not updated.

##### **Motivation for or Use Case**

Since I'm new to JHipster I don't know whether it is intended not to generate the necessary code or it is a bug.

I would expect, that (e.g. in the jhipster-sample-app) adding/assigning a `label` and a `bankAccount` to an `operation`. The corresponding `label` and `bankAccount` get the `operation` added too. This is not working though.

##### **Reproduce the error**

```
npm install -g generator-jhipster@7.0.0-beta.1
cd ~
git clone https://github.com/jhipster/jhipster-sample-app --branch v7.0.0-beta.1
cd ~/jhipster-sample-app
./mvnw
```

In a separate terminal. Request the REST-API and get the `operation`, the `label` and the `bank-account` with `id=1`:

```
apt-get install -y jq  # <- if not yet installed
curl -X GET "http://localhost:8080/api/operations/1" -H  "accept: */*" -H  "Authorization: Bearer $ID" && \
curl -X GET "http://localhost:8080/api/labels/1" -H  "accept: */*" -H  "Authorization: Bearer $ID" && \
curl -X GET "http://localhost:8080/api/bank-accounts/1" -H  "accept: */*" -H  "Authorization: Bearer $ID"
```
you get the following from the automatically generated data.
```
{
  "id" : 1,
  "date" : "2015-08-05T08:48:38Z",
  "description" : "Mississippi Account Associate",
  "amount" : 13968.00,
  "bankAccount" : null,
  "labels" : [ ]
}
{
  "id" : 1,
  "label" : "deposit",
  "operations" : null
}
{
  "id" : 1,
  "name" : "monitor",
  "balance" : 17676.00,
  "user" : null,
  "operations" : null
}
```
Then update an `operation` and get the `operation`
```
curl -X PUT "http://localhost:8080/api/operations" \
    -H  "accept: */*" \
    -H  "Content-Type: application/json" \
    -H  "Authorization: Bearer $ID" \
    -d "{\"id\":1,"\
"\"description\":\"updated operation description\","\
"\"message\":\"updated operation message\","\
"\"amount\":\"123\","\
"\"date\":\"2021-03-08T11:08:00Z\","\
"\""bankAccount"\":{\"id\":1},"\
"\"labels\":[{\"id\":1}]}"

curl -X GET "http://localhost:8080/api/operations/1" -H  "accept: */*" -H  "Authorization: Bearer $ID"
```
The `operation` has been updated and it points to a `bankAccount` and a `label` as expected.
```
{
  "id" : 1,
  "date" : "2021-03-08T11:08:00Z",
  "description" : "updated operation description",
  "amount" : 123,
  "bankAccount" : {
    "id" : 1,
    "name" : "monitor",
    "balance" : 17676.00
  },
  "labels" : [ {
    "id" : 1,
    "label" : "deposit"
  } ]
}
```
But the corresponding `bankAccount` and `label` are not updated.

Get the `bankAccount` and the `label` 
```
curl -X GET "http://localhost:8080/api/labels/1" -H  "accept: */*" -H  "Authorization: Bearer $ID" && \
curl -X GET "http://localhost:8080/api/bank-accounts/1" -H  "accept: */*" -H  "Authorization: Bearer $ID"
```
The `operations` fields in both are  `null`
```
{
  "id" : 1,
  "label" : "deposit",
  "operations" : null
}
{
  "id" : 1,
  "name" : "monitor",
  "balance" : 17676.00,
  "user" : null,
  "operations" : null
}
```
Is this behaviour intended? Or is it a bug?

**Comment by mshima** [comment]
Expected behavior.
We currently don’t support cascading entities out of the box.

**Comment by me-kell** [comment]
It is also expected behaviour, that updating the `operations` of a `label` it returns an updated `label` with the updated `operations`, but querying it returns the non updated `label` with the `operations` being `null`?

```
 curl -X GET "http://localhost:8080/api/labels/1" -H  "accept: */*" -H  "Authorization: Bearer $ID"

{
  "id" : 1,
  "label" : "deposit",
  "operations" : null
}
```
updating the `label` returns a label with `operations`
```
curl -X PUT "http://localhost:8080/api/labels" \
    -H  "accept: */*" \
    -H  "Content-Type: application/json" \
    -H  "Authorization: Bearer $ID" \
    -d "{\"id\":1,"\
"\"label\":\"updated operation label\","\
"\"operations\":[{\"id\":1}]}"

{
  "id" : 1,
  "label" : "updated operation label",
  "operations" : [ {
    "id" : 1,
    "date" : "2015-08-05T08:48:38Z",
    "description" : "Mississippi Account Associate",
    "amount" : 13968.00
  } ]
}
```
But the `operations` on the `label` actually remains unchanged:
```
curl -X GET "http://localhost:8080/api/labels/1" -H  "accept: */*" -H  "Authorization: Bearer $ID"                                                                                                                                         
{
  "id" : 1,
  "label" : "updated operation label",
  "operations" : null
}
```
What do I get wrong with bidirectionality?

**Comment by mshima** [comment]
> It is also expected behaviour, that updating the `operations` of a `label` it returns an updated `label` with the updated `operations`, but querying it returns the non updated `label` with the `operations` being `null`?

Yes expected.

> What do I get wrong with bidirectionality?

Bidirectionality is for classes references, not api calls.
Operation contains the join column.
