### ISSUE TITLE
Use Gradle Enterprise

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#14226]
##### **Overview of the feature request**

:heart: to gradle we have now an own gradle enterprise instance, so let's see what it can do. 
We talked about different possibilities how it can help with our quite complex and special builds.

In the short term we can use the build scans to analyze generated applications and optimize the generated code (should be quite "easy"). Moreover using the build cache for maven (and maybe migrate to gradle) can speed up the jhipster-bom builds (although they are not that complex as e.g. junit or spring builds).
The most complex part would be how to leverage e.g. build cache for our own ci builds as we are using a setup which is very special (generate code on demand etc.). But maybe we find a way to benefit from it or optimize our builds. 
For example maybe it is possible to benefit from gradle's up-2-date checks so we can rely on that to decided which builds to execute. But thats long term and will need more planning, I guess @pascalgrimaud  thoughts would be great to have.

CC @jdubois here is the ticket :) 

##### **Motivation for or Use Case**

* Better/Faster Builds for our users/generated applications
* Better/Faster Builds for jhipster-bom
* Better/Faster CI Builds

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
It can be a good idea if it can speed up the builds.
But we need to check that first:
- compare a default build with GitHub Actions without cache with a new build, using our Gradle Enterprise

**Comment by atomfrede** [comment]
Exactly. Careful moving forward here. Let's start small and see how far we want or can go.

**Comment by jdubois** [comment]
I've added a $300 bug bounty, we'll adjust this depending on the difficulty of the ticket.

**Comment by atomfrede** [comment]
After the first meeting with gradle, we will create a (or multiple) sample project(s) which is connected to our gradle enterprise so we can capture build scans and optimize for our users. We might also add an option to the generator to add gradle enterprise configuration so we can have it in out auto generated samples too.

**Comment by atomfrede** [comment]
:tada: we have our first build scans, but I don't know why the build is failing (freshly generated from main). But the cool thing is I can point everyone to to the failing build and output: https://ge.jhipster.tech/s/7eoife7fnhqok/tests which is pretty cool imho.

**Comment by atomfrede** [comment]
Hi everyone, 

here is a little status update what we have done and achieved already.

* With the created sample project we have identified some things to improve, which is done and can easily be added to the generator
* The migration to gradle 7 seems to be fine, this will enable file system watching which might improve incremental builds

Next steps I would like to do:

* Add a command line flag to the main generator to provide a gradle enterprise server and generate required configuration
* Have this for at least our auto generated sample project to have regular build scan
* Integrate the mentioned improvements in the generator to have the improvements visible
* Use the gradle enterprise maven support for the jhipster-bom project for [build caching and incremental build](https://docs.gradle.com/enterprise/maven-build-cache/)

what do you think? Of course if you would like to try gradle enterprise and publish build scans have a look at https://github.com/atomfrede/jhipster-ge-monolith-angular (I think I will write also some documentation) how to do it and give me a ping so I can create a user with write access on our instance.
As all our build scans are public you can explore them via the web interface: https://ge.jhipster.tech

As a side effect we have been able to create two issues for the liquibase and noHttp plugin to improve their implementation:

**Comment by atomfrede** [comment]
I will update to gradle 7 after we have integrated gradle enterprise, so do not wonder it takes a little longer than usual.

**Comment by jdubois** [comment]
@atomfrede it's awesome that you were able to help those other projects! We should definitely publicize this and thank the Gradle team for this! (if you can do a Tweet, I'll RT it with the official account)
Also, who that make sense to tell publicly about our build scans? Maybe that could help other people?

**Comment by atomfrede** [comment]
@jdubois I will do a tweet as its pretty cool to have such collaborations. I would say let's announce our build scans when we have some automation on our side. I will also write a small blog post how we optimized our build already, such that up-2-date checks are working for everything, but we are quite good already.

**Comment by atomfrede** [comment]
I need an opinion. Right now I would like to add a flag (`--gradle-enterprise`) which will automatically add configuration for our own gradle enterprise instance, so we can use it in ci easier. 
Another option would be to have a regular options (right now experimental) to ask for gradle enterprise (yes/no) and instance url and use that one. 

What do you think would be better? I didn't manage to add the additional flag, although I thought it was easy, does anyone have a hint what to consider when adding a new flag (like `--skip-client`)?

**Comment by jdubois** [comment]
I believe a flag is a better option: it's more hidden for normal users, who should not worry about this

**Comment by atomfrede** [comment]
I have created a prompt for now, but will hide it behind the `--experimental` flag for normal users (for now).

**Comment by pascalgrimaud** [comment]
I think flag is indeed better, otherwise, we'll have too much prompts
Just don't forget to document it, as currently we have a lot of flags which are hidden

**Comment by atomfrede** [comment]
Maybe it was a bit unclear :D I think it would be nice to have it for our users eventually, so they can create an application and use their gradle enterprise server out of box. The flag might help us in ci or testing to generate an app which is connected to our gradle enterprise instance. In terms of JDL it looks like this

```
application {
  config {
    buildTool gradle
    enableGradleEnterprise true
    gradleEnterpriseHost "ge.jhipster.tech"
  }
}
```

**Comment by atomfrede** [comment]
@jhipster/developers During analysis of our buildscans we noticed, that the output of the frontend build is not cacheable. The reason is, that the webpack build sets the build timestamp which is used as cachebuster for the translation files. So even when nothing has changed the created index.html is changed. Did we think already of an alternative approach, e.g. doing a hash for all translation files?

**Comment by atomfrede** [comment]
[As it seems ](https://github.com/jhipster/generator-jhipster/search?q=BUILD_TIMESTAMP) the `BUILD_TIMESTAMP` is really just used as cache buster for i18n files. So doing a hash over all i18n files and provide that via maven/gradle like we do for `APP_VERSION` would work.

**Comment by atomfrede** [comment]
Keep it open.

**Comment by atomfrede** [comment]
Keep it open

**Comment by atomfrede** [comment]
Closing this as the main part is done. Follow ups are tracked separately. https://github.com/jhipster/generator-jhipster/issues/16272
