### ISSUE TITLE
Remove traefik support

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#14233]
##### **Overview of the feature request**

Following https://github.com/jhipster/generator-jhipster/issues/11198, let's remove traefik support.

##### **Motivation for or Use Case**

No support for v2 migration

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@pascalgrimaud bog-bounty claimed: https://opencollective.com/generator-jhipster/expenses/35628

**Comment by pascalgrimaud** [comment]
@DanielFran : approved
