### ISSUE TITLE
Prefer project scoped node/npm binaries over global binaries

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#14249]
##### **Overview of the feature request**

The current version of JHipster uses global `node`/`npm` binaries to install project-specific dependencies for new projects, and while executing node scripts like `npm start`. However, during java build, we use the project local `node` and `npm` binaries. The current setup forces the globally installed version to be compliant with project requirements and a mismatch could lead to either build failures or hard to debug issues. Since we already ship a local node and npm binary (as part of `frontend-maven-plugin` plugin dependency), we can move away from use of global binaries.

A brief set of changes are well documented at https://github.com/dsyer/spring-boot-angular#install-angular-cli

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
💕 Anything to speed up the build process is most welcome! 

The most annoying thing for me is `npm install` takes a lot of time when creating the app, and when I run `./mvnw` or `./gradlew` happens again. WTF? :shakesfist:

**Comment by pascalgrimaud** [comment]
Yes I aware of this behavior, @mraible 
See my comment https://github.com/jhipster/generator-jhipster/issues/13796#issuecomment-771131452

**Comment by mshima** [comment]
Recent failures in installing npm in CI made me think that this is indeed required.
On it, unless @vishal423 is already on it.

**Comment by vishal423** [comment]
@mshima, If you have the bandwidth, then, feel free to take it up.

**Comment by atomfrede** [comment]
There is a pending PR.

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/41133

**Comment by pascalgrimaud** [comment]
@mshima : approved
