### ISSUE TITLE
CachingHttpHeadersFilter cache period should be configurable

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1424]
Currently, [CachingHttpHeadersFilter](https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/java/package/web/filter/_CachingHttpHeadersFilter.java) uses a constant CACHE_PERIOD of 31 days expressed in milli seconds for "Expires" header and same value for "Cache-Control" header but hard-coded that does not use the constant.

I propose that same value gets used in both cases and that 31 days constant is used as default value that could be easily overwritten in application.yml to a much longer period.

**Comment by atomfrede** [comment]
Yes, I agree with you it should be configurable.

**Comment by jdubois** [comment]
Yes, agreed. Could you do a PR? Otherwise I'll do this in a few days, that should be easy.

**Comment by atomfrede** [comment]
I can prepare a PR
