### ISSUE TITLE
Remove AWS Containers Subgenerator

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#14264]
##### **Overview of the issue**

I think this was discussed in the mailing list, but I was wondering if we have consensus on this one. I think we should remove the AWS subgenerator (at least the AWS Containers) as it's getting too difficult to test it without having any AWS credits. If in agreement I could go ahead and remove this.  

@jhipster/developers 

##### **Motivation for or Use Case**

Reduce technical debt and make things easy to maintain.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
What are its statistics compared with other cloud sub generators?

**Comment by SudharakaP** [comment]
> What are its statistics compared with other cloud sub generators?

It's around 9.88% for the past year I believe; 

![image](https://user-images.githubusercontent.com/12435965/110866307-cd2f1280-8279-11eb-9204-e151223f8f47.png)

Now I would assume that the `aws-containers` sub-generator is used even less. We didn't do a lot of maintenance on it and testing it we need to have some sort of credits as otherwise the cost is significant; since it uses the [EKS service](
![Uploading image.png…]()
).

**Comment by SudharakaP** [comment]
So, if there's no other objections to this I'll remove this sub-generator soon. 😄

**Comment by deepu105** [comment]
Lets do it
