### ISSUE TITLE
Create entity without table persistance

### ISSUE THREAD

**Issue by FrancescoMez79** [jhipster/generator-jhipster#14271]
Dear Support,
is possible in JHipster create an entity (my business class) without a table persistance, with JDL language?
All my entities added must have a relationship with the database?

Thanks,
Francesco

**Comment by gmarziou** [comment]
By definition, an entity is persisted. So,  could you clarify what you expect to generate on client and server sides?

Have you looked at [API-first development](https://www.jhipster.tech/doing-api-first-development/)?

**Comment by avdev4j** [comment]
hi @FrancescoMez79 
I guess you are talking about that: https://github.com/jhipster/generator-jhipster/issues/13901

Unfortunately, this is not supported now, we have some plans for the next major version of JHipster (after the v7) but not now.

You can take a look at the Entando blueprint if you want, we did it in some way. https://github.com/entando/entando-blueprint/blob/master/generators/entity-server/templates/src/main/java/package/domain/NoDbEntity.java.ejs

**Comment by pascalgrimaud** [comment]
For me, an entity without a database can't be called as entity.

**Comment by murdos** [comment]
> For me, an entity without a database can't be called as entity.

I think that in an hexagonal architecture, you may have entity that are

**Comment by Tcharl** [comment]
Can't we just generate a `List<DTO>` at the service level in this situation? I guess there's also no need for mapper and repository in this case
