### ISSUE TITLE
Add support for microservices workspaces support.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#14272]
##### **Overview of the feature request**

Generate microservices into a mono-repository (optional) with npm scripts.

##### **Motivation for or Use Case**

- Simplify testing.
- Same npm api of monolith applications, CI can be the same or with few adjusts.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
I would rather consider it as an anti-pattern and also not compliant with the 12-factor app [recommendation](https://12factor.net/codebase). We should improve the existing orchestrator like docker-compose sub-gen if required.

**Comment by mshima** [comment]
I will try to elaborate better later, but this is about the scripts to make tests and reproduction easier.
Not about making a unique git repository for every microservice.

**Comment by pascalgrimaud** [comment]
@mshima : at first, I was against this idea like @vishal423 but after looking at your PR, it seems a very good idea. And as it's optional, I'm fine with this
