### ISSUE TITLE
Update Open-api generator version to 5.x

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#14287]
##### **Overview of the feature request**

Migrate from 4.3.1 to 5.0.1 (or even 5.1.0 expected in April)

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
ping @ecostanzi @cbornet

**Comment by ecostanzi** [comment]
Keep it open

**Comment by atomfrede** [comment]
Keep it open.

**Comment by atomfrede** [comment]
Keep it open

**Comment by pascalgrimaud** [comment]
Adding a bounty to motivate someone

**Comment by DanielFran** [comment]
@ecostanzi any progress on the generator?
