### ISSUE TITLE
Fix Ionic for JHipster with npm 7

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#14285]
See https://github.com/oktadeveloper/generator-jhipster-ionic/issues/434.

**Comment by mshima** [comment]
@mraible add .npmrc with `legacy-peer-deeps`

**Comment by mraible** [comment]
Sure, but what's the real fix?! 😜

**Comment by mshima** [comment]
First problem: ng-jhipster.
An unmaintained lib will always have problems.
In this case ng-jhipster wants you to use angular 10 instead of 11.
Is ng-jhipster required? If so it’s time to split ng-jhipster into another generator.

I will take a deeper look.

**Comment by mshima** [comment]
By the way I’ve just recently removed .npmrc from angular, react and vue have it.
Downgrade some libs may be required too.

**Comment by mraible** [comment]
Fixed. Please collect your bug bounty since I used your suggestion. :)

**Comment by mshima** [comment]
@mraible keep open. I will take a look if peer dependencies are resolvable if we drop ng-jhipster dependency.
I know it’s not with it.

Have been busy to look at this.

**Comment by mraible** [comment]
I dropped the ng-jhipster dependency but found I needed it for Ionic's starters to work. My main issue now is I can't get Ionic's CI to pass for a gateway. I had it working with a reactive gateway and JHipster 7, but now I'm trying it with JHipster 6 and Zuul and it doesn't work either. 

Oh, wait...

It looks like switching from MongoDB to PostgreSQL might've fixed it. https://github.com/oktadeveloper/generator-jhipster-ionic/pull/465

**Comment by mshima** [comment]
I have reproduced the problem and there were version conflicts at generated dependencies.
I had it tracked to angular dependencies conflicting with `@ionic/angular-toolkit` but it was already fixed upstream by https://github.com/ionic-team/starters/commit/da07ea3d47ba6d0190f1446ccb39788d760d63e4#diff-a39f899adb17e2b43435d9759f925d89b0226cfbe1b5b231336ef716e6f99d23.

With those changes npm install without legacy-peer-deps succeeds.

To use this commit is change https://github.com/oktadeveloper/ionic-jhipster-starter/blob/41b65f972abab652ca047e596c419cfff936e3c2/ionic.starter.json#L3 baseref to da07ea3d47ba6d0190f1446ccb39788d760d63e4?
Not easy to understand 😆

**Comment by mraible** [comment]
I created a PR with the updated baseref at https://github.com/oktadeveloper/ionic-jhipster-starter/pull/51. If this build passes, I can push to ionic-team/starters.

**Comment by mshima** [comment]
Current failure seem related to an outdated npm version, where it fails to resolve peer dependencies to the same package with different ranges.
I've created https://github.com/oktadeveloper/ionic-jhipster-starter/pull/52 with webpack resolved instead of letting npm resolve it.

**Comment by mraible** [comment]
Still needs to be done. I'll try to look into it soon.

**Comment by mraible** [comment]
I created a branch to upgrade the minimum version of JHipster to v7 for Ionic. Not sure what else I need to do to make tests pass.

https://github.com/oktadeveloper/generator-jhipster-ionic/pull/482

**Comment by mraible** [comment]
@mshima The original task for this issue has been completed. Please collect your bounty and close this issue when you're finished.

**Comment by mraible** [comment]
This has been completed but I don't think @mshima claimed his bounty.

**Comment by mshima** [comment]
Will do. Thanks.

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/41742.

**Comment by pascalgrimaud** [comment]
@mshima : approved :-)
