### ISSUE TITLE
Login doesn't work on IE 11 if form action is specified

### ISSUE THREAD

**Issue by zzcoder** [jhipster/generator-jhipster#1431]
The generated login form works as is. However, it's a security risk not specifying action in form. To pass the certification, we have to add action.

It turns out IE 11 will abort any ajax calls in progress if the form is submitting.  Solution is to change the button type from submit to button.

                <button type="button" class="btn btn-primary" ng-click="login()" translate="login.form.button">Authenticate</button>

It would be nice if you can make the same change in jHipster.

**Comment by zzcoder** [comment]
We found a problem with this approach. The ENTER key doesn't work anymore without a submit button. The new fix is to keep the submit button but change the event handler. 

1. Passing the $event to the handler,

     <form class="form" role="form" action="{{actionUrl}}" ng-submit="login($event)">

2. Prevent submit in the handler,
```javascript
       $scope.login = function (event) {
            // Keep IE from applying form action
            event.preventDefault();

            // Do the login
            Auth.login({
                username: $scope.username,
                password: $scope.password,
                rememberMe: $scope.rememberMe
            }).then(function () {
                $scope.authenticationError = false;
                $rootScope.back();
            }).catch(function () {
                $scope.authenticationError = true;
            });
        };
```

**Comment by jdubois** [comment]
Argh, and I just did the 2.11.0 release with this fix :-(
