### ISSUE TITLE
Sponsored by @oktadev no longer printed

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#14329]
##### **Overview of the issue**

When running `jhipster jdl default`, I expect to see "Sponsored by Okta" at the end. However, now it just says:

```
INFO! Generator app succeed
Congratulations, JHipster execution is complete!
Congratulations, JHipster execution is complete!
```

##### **Motivation for or Use Case**

It was working when I added it a couple of weeks ago.

**Comment by atomfrede** [comment]
It works when using just `jhipster` and answering the prompts.
