### ISSUE TITLE
Modularize/separate templates based on (major) feature support

### ISSUE THREAD

**Issue by lokkju** [jhipster/generator-jhipster#1432]
Some of the templates, such as the Entity template, are getting highly complex in terms of the if statements contained with them.  Would it make more sense to split the template into multiple, say one per backend type supported, and then the main template just contains include statements?

This would allow for easier maintenance of the template based on each backend technology, by the people best with that backend technology; and doesn't seem to result in much code duplication.  It also just make the template plain easier to read.

**Comment by jdubois** [comment]
Yes, at least this is worth trying - I fully agree with you

**Comment by lokkju** [comment]
I'll see if I can find a workable way to do this.

**Comment by drissamri** [comment]
This would be awesome. It's currently really hard to contribute larger features. :)

**Comment by gzsombor** [comment]
A couple of recurring idioms should be refactored to independent function calls as well, for example, generating all the class-imports could be improved, with a function which collects all the classes, and would print in a sorted, nicely separated order.
So every template would start with something like :

    if (dateIsUsed) { 
         import("java.util.Date");
    }
    ...
    ...
    <%= getImports() %>

What do you think?

**Comment by jdubois** [comment]
Maybe we should wait a little bit for this: Java 7 being end of life, I'm waiting until we have less Java 7 users (currently 25%, down from 30% last month) to remove it.
This should simplify a lot of code, and we could refactor the templates at the same time.

Are you OK with waiting a few months for this?

**Comment by jdubois** [comment]
@gzsombor I'm not sure I understand what you do with the imports, but if it works yes that would be a great help.

I agree the templates are starting to be messy, but it will also be very hard to refactor them.

As commented earlier, I'd like to wait until Java 7 is removed (now we are at 20%, it's going down!!), as this should help a lot of the refactoring.

But yes, this refactoring will be necessary.
