### ISSUE TITLE
Move the module generator to the JHipster 7

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#14327]
##### **Overview of the feature request**
The JHipster 7 release is about to come. We need to upgrade this generator to match the breaking changes introduced in this new major version.

##### **Motivation for or Use Case**
Generate JHi7 module.

##### **Related issues or PR**
https://github.com/jhipster/generator-jhipster/issues/14135

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Adding a bounty, as it's important to have for v7

**Comment by avdev4j** [comment]
Done here : https://github.com/jhipster/generator-jhipster-module/pull/183

**Comment by mraible** [comment]
If you want to test it on a module, you can experiment with the [Ionic module](https://github.com/oktadeveloper/generator-jhipster-ionic/issues/466). 😉

**Comment by avdev4j** [comment]
Keep it open. I need to fix the last comments

**Comment by avdev4j** [comment]
bounty claimed https://opencollective.com/generator-jhipster/expenses/41155
