### ISSUE TITLE
Reactive: Integration tests with validated endpoints fail because of blocking call

### ISSUE THREAD

**Issue by MarcelRosenberger** [jhipster/generator-jhipster#14326]
##### **Overview of the issue**

Integration tests of Ressource-Endpoints with `@Valid`-annotated method arguments fail, because BlockHound detects a blocking call. The call is made by `SpringValidatorAdapter`.

The error message is:
`reactor.blockhound.BlockingOperationError: Blocking call! java.io.RandomAccessFile#readBytes
	at java.base/java.io.RandomAccessFile.readBytes(RandomAccessFile.java)`

##### **Related issues**
#7608, [#24247](https://github.com/spring-projects/spring-framework/issues/24247)

##### **How to reproduce**
Run `ExceptionTranslatorIT.testMethodArgumentNotValid`

##### **Suggest a Fix**

A workaround is to disable BlockHound in the class `JHipsterBlockHoundIntegration` by adding
`builder.allowBlockingCallsInside("org.springframework.validation.beanvalidation.SpringValidatorAdapter", "validate");`

The linked issues suggest that the problem is already fixed (via --parameters). I am using the spring-boot gradle-plugin which should set this automatically and still get the error.

Is it only me having this?

##### **JHipster Version(s)**
7.0.0-beta.1

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Can you please run `jhipster info` on your project or provide a JDL so we can try and reproduce the issue?

**Comment by MarcelRosenberger** [comment]
Thanks for looking at this!

-- generator-jhipster@7.0.0-beta.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "microservice",
    "baseName": "myapp",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipClient": true,
    "skipUserManagement": true,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1615587694341,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "reactive": true,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8081",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": ["searchEngine:elasticsearch"],
    "websocket": false,
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "de"],
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": true,
    "lastLiquibaseTimestamp": 1615588018000,
    "entities": ["Car", "Owner"]
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Car {
  name String required
  milage Integer
}
entity Owner {
  age Integer
}
relationship ManyToOne {
  Car{owner required} to Owner
}

microservice Car, Owner with myapp
clientRootFolder Car, Owner with myapp

</pre>
</details>


##### **Environment and Tools**

git version 2.19.1.windows.1

node: v12.15.0

npm: 7.6.3

yeoman: 3.1.0

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192

INFO! Congratulations, JHipster execution is complete!

**Comment by mraible** [comment]
I created an app with the current `main` branch and your `.yo-rc.json`. Then, I ran:

```
./gradlew test integrationTest
```

I can confirm this is indeed an issue.

```
> Task :compileJava
Note: Hibernate JPA 2 Static-Metamodel Generator 5.4.29.Final
Note: /Users/mraible/dev/jh-14326/src/main/java/com/mycompany/myapp/security/jwt/JWTFilter.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/mraible/dev/jh-14326/src/main/java/com/mycompany/myapp/security/jwt/TokenProvider.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :integrationTest

ExceptionTranslatorIT > testMethodArgumentNotValid() FAILED
    java.lang.AssertionError at ExceptionTranslatorIT.java:51

9 tests completed, 1 failed

> Task :integrationTest FAILED

FAILURE: Build failed with an exception.
```

I tried adding this:

```
builder.allowBlockingCallsInside("org.springframework.validation.beanvalidation.SpringValidatorAdapter", "validate");
```

And it fixes it! 

```
BUILD SUCCESSFUL in 30s
```

Can you please create a PR with this fix?
