### ISSUE TITLE
No embedded Elasticsearch error 

### ISSUE THREAD

**Issue by fontanellif** [jhipster/generator-jhipster#1435]
Hi, i'm testing the new feature based on ES search. Everything works well with the embedded ES instance, but when i try to use a real ES instance i get this error:

`"error" : "ElasticsearchIllegalArgumentException[No feature for name [nodes]]",`

I try to change the port 9200 (http client) -> 9300 (transport client), change the ES version (1.4.1) -> (1.3.2 the same version of the elasticsearch dependencies) but i get the same error.
I think that the hipster documentation must contain more information about how use a real ES instance and an example of query.

Thank you in advance

**Comment by jdubois** [comment]
Hi,

We don't do anything ourselves, in fact this all comes form Spring Data Elasticsearch, so it's supposed to work out-of-the-box at our level -> if you have a working implementation, can you improve the documentation on http://jhipster.github.io/using_elasticsearch.html ? You can propose a PR [here](https://github.com/jhipster/jhipster.github.io).

**Comment by jdubois** [comment]
Hi,
I just tested with an out-of-the-box version of ES (latest version, 1.5.2) and it worked straight away.
You just need to configure in your YAML configuration:
```
cluster-nodes: 127.0.0.1:9300
```
As this is a [standard Spring Boot configuration](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) and that it works normally, I don't think we have anything specific to document.

**Comment by mukeshkdangi** [comment]
didn't help cluster-nodes: 127.0.0.1:9300
