### ISSUE TITLE
Generated DTO classes are missing relationship representations

### ISSUE THREAD

**Issue by krmahadevan** [jhipster/generator-jhipster#14352]
##### **Overview of the issue**
When generating the DTO classes from a JDL using `jhipster import-jdl` the generated DTOs are missing the relation object collections.

For e.g., Here's a JDL

```
entity Father

entity Child

relationship OneToMany {
    Father to Child
}

dto * with mapstruct
```

The generated Entity class looks like below:

```java
import javax.persistence.*;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * A Father.
 */
@Entity
@Table(name = "father")
public class Father implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToMany(mappedBy = "father")
    private Set<Child> children = new HashSet<>();

    // jhipster-needle-entity-add-field - JHipster will add fields here
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Set<Child> getChildren() {
        return children;
    }

    public Father children(Set<Child> children) {
        this.children = children;
        return this;
    }

    public Father addChild(Child child) {
        this.children.add(child);
        child.setFather(this);
        return this;
    }

    public Father removeChild(Child child) {
        this.children.remove(child);
        child.setFather(null);
        return this;
    }

    public void setChildren(Set<Child> children) {
        this.children = children;
    }
    // jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Father)) {
            return false;
        }
        return id != null && id.equals(((Father) o).id);
    }

    @Override
    public int hashCode() {
        return 31;
    }

    // prettier-ignore
    @Override
    public String toString() {
        return "Father{" +
            "id=" + getId() +
            "}";
    }
}
```

Here's the generated DTO class which is missing the `private Set<ChildDTO> children = new HashSet<>();` entry in it.

```java
import java.io.Serializable;

/**
 * A DTO for the {@link com.rationaleemotions.domain.Father} entity.
 */
public class FatherDTO implements Serializable {
    
    private Long id;

    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof FatherDTO)) {
            return false;
        }

        return id != null && id.equals(((FatherDTO) o).id);
    }

    @Override
    public int hashCode() {
        return 31;
    }

    // prettier-ignore
    @Override
    public String toString() {
        return "FatherDTO{" +
            "id=" + getId() +
            "}";
    }
}

```

##### **Motivation for or Use Case**

Because the relationships are missing in the generated DTOs, we need to manually go through the DTOs and add these missing relationships. If there are a lot of entities that are being generated then this becomes more of a manual task.

##### **Reproduce the error**

Create a JDL file with its contents as below:

```
entity Father

entity Child

relationship OneToMany {
    Father to Child
}

dto * with mapstruct
```

and then run the command `jhipster import-jdl example.jdl`

##### **JHipster Version(s)**
v6.10.5

##### **JHipster configuration**
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
experiments@0.0.0 /Users/703240805mac/githome/playground/experiments
└── generator-jhipster@6.10.5

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.rationaleemotions"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "microservice",
    "baseName": "experiments",
    "packageName": "com.rationaleemotions",
    "packageFolder": "com/rationaleemotions",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1615914214966,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Father
entity Child
relationship OneToMany {
  Father{child} to Child{father}
}

dto Father, Child with mapstruct
service Father, Child with serviceClass
microservice Father, Child with experiments
clientRootFolder Father, Child with experiments

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.30.2

node: v14.15.5

npm: 6.14.11

yeoman: 3.1.1

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build c4eb3a1f

identical .jhipster/Child.json
identical .jhipster/Father.json
INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

**Father.json**

```json
{
  "name": "Father",
  "fields": [],
  "relationships": [
    {
      "relationshipType": "one-to-many",
      "otherEntityName": "child",
      "otherEntityRelationshipName": "father",
      "relationshipName": "child"
    }
  ],
  "changelogDate": "20210316170950",
  "entityTableName": "father",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "serviceClass",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "clientRootFolder": "experiments",
  "applications": "*",
  "microserviceName": "experiments"
}

```

**Child.json**
```json
{
  "name": "Child",
  "fields": [],
  "relationships": [
    {
      "relationshipType": "many-to-one",
      "otherEntityName": "father",
      "otherEntityRelationshipName": "child",
      "relationshipName": "father",
      "otherEntityField": "id"
    }
  ],
  "changelogDate": "20210316171050",
  "entityTableName": "child",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "serviceClass",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "clientRootFolder": "experiments",
  "applications": "*",
  "microserviceName": "experiments"
}
```

##### **Browsers and Operating System**

This issue is NOT related to any browser. 

OS : macOS Catalina 10.15.7

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Don't you have a FatherId in the Child Dto and a `uses` reference in its mapper?
DTO reference was not something that we wanted on the XToMany X side

**Comment by krmahadevan** [comment]
@Tcharl - My apologies for the really delayed response to your question.

I am a bit new to both mapstruct as well as JHipster as well. So please bear with me if the question sounds a bit naive.

Are you suggesting that I should always try to build the `List<ChildDTO>` for a particular `FatherDTO` by iterating through all the `ChildDTO` and then keeping this map somewhere outside ?

Just for the sake of clarity, here's how the `ChildDTO` looks like

<details>
```java
public class ChildDTO implements Serializable {

  private Long id;

  private FatherDTO father;

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public FatherDTO getFather() {
    return father;
  }

  public void setFather(FatherDTO father) {
    this.father = father;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ChildDTO)) {
      return false;
    }

    ChildDTO childDTO = (ChildDTO) o;
    if (this.id == null) {
      return false;
    }
    return Objects.equals(this.id, childDTO.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.id);
  }

  // prettier-ignore
    @Override
    public String toString() {
        return "ChildDTO{" +
            "id=" + getId() +
            ", father=" + getFather() +
            "}";
    }
}
```
</details>

And here's how the ChildMapper looks like

<details>
```java
@Mapper(componentModel = "spring", uses = { FatherMapper.class })
public interface ChildMapper extends EntityMapper<ChildDTO, Child> {
  @Mapping(target = "father", source = "father", qualifiedByName = "id")
  ChildDTO toDto(Child s);
}
```
</details>

**Comment by krmahadevan** [comment]
@pascalgrimaud - I noticed that you have added the label "needs-reproduction". Can you please let me know if i need to add any additional context to clarify my ask. I will add them accordingly.

**Comment by pascalgrimaud** [comment]
@krmahadevan : I put this label, waiting someone else to have a look and reproduce the issue :-)

**Comment by krmahadevan** [comment]
Ah ok. @pascalgrimaud - Incase anything additional is needed from my side, please let me know.

**Comment by mshima** [comment]
This bug happens with JHipster v6.
No additional v6 release is planned.

**Comment by krmahadevan** [comment]
@mshima - So if I use [JHipster 7.0.0](https://www.jhipster.tech/2021/03/21/jhipster-release-7.0.0.html) I should be able to circumvent past this problem ?
