### ISSUE TITLE
Frictionless custom code contribution in jhipster relying on git hooks

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#14363]
##### **Overview of the feature request**

This solution would use git hook to let our end user being able to mix jhipster and custom code in a frictionless manneer relying on the yo-resolve file, a git hook and a slightly hardened git process. Let me try to sum up what could be a solution.

1. Add a new configuration file in the .jhipster folder.
This file will contains the list of files managed by the jhipster generator as well as a `jdl-commit` configuration bit (I'll describe this bit a little bit later).

2. Generation phase
When using the `import-jdl`or `jhipster-upgrade` command, we would first check if git does not contains uncommited files, we can commit these files before generating or refuse the generation.
These commands will set the `jdl-commit`bit to `true`, meaning that the hook won't do anything before the next commit.
We could also commit the modified file after generation, so that we ensure that this commit only contains stuff that has been generated

3. Custom code
Then, our end user will typicallly override/adapt the generated code (also add some more sources) in a dedicated commit.
Here, when he will commit, and if the `jdl-commit` bit is set to false, we can add all the modified files that are managed by the generator (contained in the file list previously mentionned) as skipped in the .yo-resolve file using a git hook, so that these files won't be overridden during the next regeneration.

Note that if we force commit at the generation phase, we won't need the `jdl-commit` bit.

##### **Motivation for or Use Case**

Propose an enhanced developer experience, allowing to mix generation and custom code management mostly transparent.

##### **Related issues or PR**

[.yo-resolve JH code stories](https://github.com/jhipster/generator-jhipster/issues/12497)
[another one on the same topic](https://github.com/jhipster/generator-jhipster/issues/12417)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Not sure it is needed, with jhipster v8
I have some other ideas I'll share to the team soon :)

**Comment by Tcharl** [comment]
I don't know what you plan, so it's difficult to confirm/infirm ^^.
However, it's a very good news that you plan to improve the developper experience (particularly the custom code one)

This story can represent a quick win for V7 at least: it doesn't modify nothing: it only improves the developer xp. Also, I don't know how to implement it but it seems to be very simple to achieve

**Comment by pascalgrimaud** [comment]
Sure, v7 will live, and v8 is not for tomorrow :-)
If it can help for v7, let's do it

**Comment by Tcharl** [comment]
Please keep opened, I'm on another one, but plan to implement this one!

**Comment by Tcharl** [comment]
Please keep open,  plan to go back on it this week

**Comment by Tcharl** [comment]
keep open
