### ISSUE TITLE
For an Entity, Many to One with User, findAllForCurrentUser doesn't work.

### ISSUE THREAD

**Issue by amangale** [jhipster/generator-jhipster#1438]
Hi,

I am using Token-based authentication with Mysql.

I have an entity which belongs to the User. I tried the findAllforCurrentUser method, but it is not working. 

If I try the same flow with Session-based authentication, it works. What am I missing?

The repository code for both looks like:

@Query("select contact from Contact contact where contact.user.login = ?#{principal.username}")
List< Contact > findAllForCurrentUser();

Thanks,
Ashwin

**Comment by jdubois** [comment]
So your method was correctly generated, but that may be because there's something different in the Toekn-based authent -> can you elaborate on "it is not working"? Like a stacktrace, or an error message

**Comment by amangale** [comment]
Hi,

Actually, it was something I was trying on the angular side which was not displaying the fetched records (hence the 'it is not working').

Also, I had enabled pagination, so the repository method goes something like:

@Query("select contact from Contact contact where contact.user.login = ?#{principal.username}")
Page<Contact> findAllForCurrentUser(Pageable p);

Thanks for your quick reply,
Ashwin
