### ISSUE TITLE
Parametrise SecurityConfiguration CSP  policies

### ISSUE THREAD

**Issue by ko5tik** [jhipster/generator-jhipster#14381]
##### **Overview of the feature request**

I am developing application, and need to display map data - say from OpenStreetMap.   To do this,  CSH heaer must be produced like this:

`img-src 'self' data: https://*.tile.openstreetmap.org; `

Current template is hardwired to:

`img-src 'self' data:;`

Being able to parametrize  image source would be nice. 

##### **Motivation for or Use Case**

I  need to display cartographic data - say with leaflet.   This means downloading image tiles from external server. Everything works while developing with webpack, but once application is deployed properly  maps stop working

##### **Related issues or PR**

Searched fo issues,   but did not found request for parametrisation.   Only corrections / inclusion  of google fonts

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
You mean e.g. during generation or just a property in `application.properties` which is used in generated `SecurityConfiguration`?

**Comment by ko5tik** [comment]
I would say  in generated `SecurityConfiguration` -  do not see how it is going to be picked up from` application.properties` - `ContentSecurityPolicyHeaderWriter`  does not look there

**Comment by atomfrede** [comment]
Yes, I mean generate it hard coded and e.g. let the user enter a custom header during generation which will complicate the generator even more or just change the configuration to read a to be defined property so you can change it later via a property (with all the benefits, e.g. environment overwrite).

**Comment by ko5tik** [comment]
Something like:
```
@Autowired
Environment environment;

environment.getProperty("cspPolicy", "default valie like it is today")
```

)

**Comment by mraible** [comment]
@ko5tik Can you create a PR with this proposed change?

**Comment by ko5tik** [comment]
Hi Matt, already on it.
