### ISSUE TITLE
Not Able to generate application with following settings

### ISSUE THREAD

**Issue by amitkurud** [jhipster/generator-jhipster#14402]
##### **Overview of the issue**
When I try to generate application with follwing settings I get error 
Unhandled promise rejection at:
TypeError: Cannot read property 'push' of undefined                                                
##### **Reproduce the error**
`? Which *type* of application would you like to create? Gateway application
? What is the base name of your application? jhi
? As you are running in a microservice architecture, on which port would like your server to run? It shoul
d be unique to avoid port conflicts. 8080
? What is your default Java package name? com.mycompany.myapp
? Which service discovery server do you want to use? JHipster Registry (uses Eureka, provides Spring Cloud
 Config support and monitoring dashboards)
? Which *type* of authentication would you like to use? OAuth 2.0 / OIDC Authentication (stateful, works w
ith Keycloak and Okta)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Which cache do you want to use? (Spring cache abstraction) Hazelcast (distributed cache, for multiple no
des, supports rate-limiting for gateway applications)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? Elasticsearch as search engine, Apache Kafka as asynchro
nous messages broker, API first development using OpenAPI-generator
? Which *Framework* would you like to use for the client? React
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Cosmo
? Choose a Bootswatch variant navbar theme (https://bootswatch.com/)? Dark
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install Hindi
     info Disabling hibernate cache for cache provider no
? Besides JUnit and Jest, which testing frameworks would you like to use? Cypress, Gatling, Cucumber
? Would you like to install other generators from the JHipster Marketplace? Yes
? Which other modules would you like to use? (generator-jhipster-kafka-1.0.1) A JHipster module that gener
ates Apache Kafka consumers and producers and more!`

##### **JHipster Version(s)**
7.0.0
##### **Browsers and Operating System**
Linux

**Comment by ilyasziyaoglu** [comment]
I am getting the same error.
