### ISSUE TITLE
[react] Entity listing table has an extra column for id

### ISSUE THREAD

**Issue by swarajsaaj** [jhipster/generator-jhipster#14404]
##### **Overview of the issue**

Entities generated using client as react have an extra duplicate column `<td>` for ID 
For reference, ID is being rendered twice and title column is distorted
![image](https://user-images.githubusercontent.com/6285049/111916937-54af2980-8aa3-11eb-8566-516ec88e586b.png)

##### **Motivation for or Use Case**

The layout looks distorted/skewed

##### **Reproduce the error**

Generate any entity in react client app

##### **Related issues**

Seems the filter for ID field was removed in PR https://github.com/jhipster/generator-jhipster/pull/13824

##### **Suggest a Fix**

Add a filter for ID column as its already added as first `td` at https://github.com/jhipster/generator-jhipster/blob/main/generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs#L329

##### **JHipster Version(s)**

main

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1616350178844,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1616351928000,
    "entities": ["Post"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Post {
  title String
}
dto Post with mapstruct
service Post with serviceImpl

</pre>
</details>

##### **Environment and Tools**

openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

git version 2.21.0.windows.1

node: v14.15.4

npm: 6.14.10

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build c4eb3a1f

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@swarajsaaj can you create the PR with the fix?

**Comment by swarajsaaj** [comment]
Yes @mshima I 'll provide a PR soon
