### ISSUE TITLE
additional modules list missing when installing a new jh7 project

### ISSUE THREAD

**Issue by jaanusnurmoja** [jhipster/generator-jhipster#14433]
##### **Overview of the issue**

Other modules list shows only Kafka module when installing a new jh 7 project. 
![image](https://user-images.githubusercontent.com/1138055/112190774-fc486b00-8c0d-11eb-80f7-ee02c0c37b85.png)

##### **JHipster Version(s)**

7.0.0  There was no such issue with earlier version(s)

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
What modules are you expecting to be listed? It's possible they haven't been updated to support v7.

**Comment by pascalgrimaud** [comment]
It's simply because the modules need to be upgraded for supporting JHipster v7, and be tagged with `jhipster-7`

See the module, maintained by @fdelbrayelle : https://github.com/fdelbrayelle/generator-jhipster-kafka/blob/master/package.json#L10

**Comment by fdelbrayelle** [comment]
Yep I've already test the Kafka module with the `7.0.0` and everything works fine! :rocket:
