### ISSUE TITLE
Improvements to cypress implementation.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#14441]
##### **Overview of the issue**

While doing some work related to https://github.com/jhipster/generator-jhipster/issues/14103.
I've found some problems and improvements that we could make in our cypress implementation.

- Our tests could reduce roundtrips eg:
  - First test executes go to main page -> open menu -> go to entity page -> do some checks.
  - Every other test executes the first test + some other test. 
- Remove unnecessary page visits.
- Our tests executes with prod profile, which doesn't includes fake data.
Many tests are actually not executed at all without a registry in database, but reported as succeeded instead of skipped.

##### **Motivation for or Use Case**

- Reduce cypress execution times.
- Be more effective in our tests.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/14103

##### **Suggest a Fix**

- Start every other test from the entity page.
- Mock backend api when there is no registry in database so tests will be executed instead of skipped.

##### **JHipster Version(s)**

main

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I'm changing the label, as it's more an improvement than a bug :)

**Comment by pascalgrimaud** [comment]
Reading your ticket, one thing which is important, is to be able to execute the test alone. That explains why there are some repetitive steps
