### ISSUE TITLE
Eclipse config: Have JHipster exclude validation on node and bower out of the box

### ISSUE THREAD

**Issue by michaelisvy** [jhipster/generator-jhipster#1446]
Importing a project in JHipster currently requires lots of manual steps. 

I've just generated a project. Here is what I can see after importing it:

![image](https://cloud.githubusercontent.com/assets/1440137/7505621/4fd28ef6-f487-11e4-9636-7233b1f91638.png)

At this stage, I need to do lots of manual operations. All the below should be automated.
The fixes provided below are just here as a guideline for manual configuration (until JHipster provides a proper automated fix for that).

# Exclude the ‘node_modules’ folder in Ecliipse (based on Eclipse 3.6.2)

right click on Project -> Resource -> Resource Filters
You should then select: Exclude all, Applies to folders, Name matches node_modules
Press ok.

Project properties:
![image](https://cloud.githubusercontent.com/assets/1440137/7505655/c2f329fe-f487-11e4-93e1-5e2b55dd82d2.png)

![image](https://cloud.githubusercontent.com/assets/1440137/7505656/ccf19de6-f487-11e4-9657-d7bbd52c022e.png)

# Exclude 'scripts' and 'bower_components" from src/main/java

To do so:

right click on Project -> Javascript -> Include path
You can then click on the “source” tab and select your_project/src/main/webapp
You can then select “Excluded: (None) -> Edit -> Add multiple
You can select “bower_components” and “scripts” and click “ok”.

![image](https://cloud.githubusercontent.com/assets/1440137/7505666/e3d8f2e8-f487-11e4-905b-4bd30609c146.png)

![image](https://cloud.githubusercontent.com/assets/1440137/7505673/f30269fc-f487-11e4-8db5-56fde11e7ef1.png)

Edit -> Add multiple

![image](https://cloud.githubusercontent.com/assets/1440137/7505677/fea4cdcc-f487-11e4-9377-03d34b8ac730.png)

# Proposed fix:

for node_modules folder, JHipster should generate a .project file that contains the below:

```xml
<filteredResources>
<filter>
<id>1430533357431</id>
<name></name>
<type>10</type>
<matcher>
<id>org.eclipse.ui.ide.multiFilter</id>
<arguments>1.0-name-matches-false-false-node_modules</arguments>
</matcher>
</filter>
</filteredResources>
```

For folders 'scripts' and 'bower_components' configuration is done inside .settings/.jsdtscope

```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry excluding="bower_components/|scripts/" kind="src" path="src/main/webapp"/>
	...
</classpath>
```

**Comment by gmarziou** [comment]
An alternative would be that the IDE excludes directories and files that are listed in the .gitignore file, I know that some editors like Sublime Text do it with some plugins. Maybe there's something similar for Eclipse.

**Comment by jdubois** [comment]
Yes the best solution would be to generate the .project file.
I'll have a look at this.

**Comment by jdubois** [comment]
OK, so Eclipse is still incredible hard to configure!!!

@michaelisvy I followed your steps, and indeed this solves all configuration issues, so that's really good

-> do you think you could make a PR with the correct configuration? I'm afraid we will need to add lots of stuff from the .settings directory, and that would be hard to do.

**Comment by cselti** [comment]
My personal point of view, that everybody will use their own IDE and their responsibility is to configure it :) 
But in this case - maybe the m2e or IDEA maven plug-ins could help in it? 
(i haven't got any experience in them, so it's just a question)

**Comment by michaelisvy** [comment]
@jdubois let me discuss it with our Eclipse people. Generating the files is easy but we just need to make sure it works in all situation (with m2e, without m2e etc).

**Comment by jdubois** [comment]
Yes I agree with you @cselti and this is the original idea with JHipster.
Then, I am not an Eclipse user, but I have to admit this is what most people use.
@michaelisvy you could just contribute to the documentation: it would be easier to do, and that would follow the same idea.

**Comment by michaelisvy** [comment]
Hi, I think it all depends to how many JHipster users are Eclipse users. If you think there are 10% of them, we don't need to care about it. But if 70% of JHipster users use Eclipse, then it's a problem. There are quite a lot of manual steps to do the configuration as you've seen. 
Besides, we're just talking about adding 2 hidden files at the root of the generated project. It's not that intrusive.

**Comment by michaelisvy** [comment]
Hi Julien,
I thought one more option would be to ask people if they are using Eclipse as part of the generator command prompt questions. If they are using Eclipse, we can generate the 2 hidden files. I guess it's also useful because you can know which percentage of your users are using Eclipse.

I can also just as well do a pull request to add some documentation. Just let me know what's best for you.

**Comment by nicoglp** [comment]
Maybe we can try configure this with the eclipse maven's plugin help. I'm going to test it.
https://maven.apache.org/plugins/maven-eclipse-plugin/eclipse-mojo.html

**Comment by jdubois** [comment]
I think most of our users are developing with Eclipse, or at least work in a team where some people use Eclipse.
So it makes sense to have a good Eclipse configuration out-of-the-box, without asking any additional question (I don't want to end up having 20 questions). Besides, it's only hidden files, so it shouldn't be an issue (only thing that worries me is that hidden files are shown in Intellij - but if they annoy you too much, it's super-easy to delete).
So @michaelisvy I think the best solution is to generate those files: could you do a PR?

**Comment by nicoglp** [comment]
@jdubois those hidden files would be deleted if someone executes the 'clean' goal of Maven Eclipse Plugin, and replaced y executes the 'eclipse' goal. This is why I suggest try do this with the plugin.

**Comment by michaelisvy** [comment]
@nicoglp the Maven Eclipse plugin does not play well with m2eclipse (which is what people use the most as far as I can see). I tried to have some files generated by mvn eclipse:eclipse and then have them imported in Eclipse using m2eclipse, it just doesn't work. 

@jdubois sure, I'll see how to do a PR. the ,project file needs to contain the name of the current project so I need to see how to generate that. Will look into it.

Cheers,
Michael.

**Comment by michaelisvy** [comment]
Hi Julien,
I've had a quick look. I guess inside the .project file I need to use "<%= _.slugify(baseName) %>" so I can get the project basename. 
How can I test the project generation locally? I see that there is a file called test-creation.js but I'm not sure how to run it.

**Comment by jdubois** [comment]
Hi @michaelisvy yes it's how you use Yeoman templates

If you want to test the project generation, have a look at our [CONTRIBUTING.md](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup). It's quite easy to do, in fact!

**Comment by jdubois** [comment]
@michaelisvy I'm also going to have a look at how to generate config files for Intellij.

If this is too complex, we can just have a page on the website with the guide you wrote at the beginning of this ticket.

**Comment by jdubois** [comment]
OK, I've tried it with Intellij, and this is quite complex.
I'll add a page in the documentation, it will be much simpler.

**Comment by moifort** [comment]
For my case I also excluded `dist` folder. I work with eclipse Luna and JHipster 2.

**Comment by jdubois** [comment]
Oh yes this is a good idea

**Comment by jdubois** [comment]
Documentation is added here: http://jhipster.github.io/configuring_ide.html

@moifort I didn't exclude the dist folder, I know, I'll do this later
