### ISSUE TITLE
JDL parsing error on rememberMeKey while importing

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#14462]
##### **Overview of the issue**

With JHipster 7, I generated a monolith with session auth then exported the JDL, created a new directory and imported the JDL: it fails at parsing `rememberMeKey`

Import the JDL, parsing fails on `rememberMeKey`

```
jhipster jdl .\test.jdl
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing import-jdl .\test.jdl
error: Syntax error message:
        MismatchedTokenException: Found an invalid token 'rememberMeKey', at line: 28 and column: 5.
        Please make sure your JDL content does not use invalid characters, keywords or options.
Error during import-jdl: Error: MismatchedTokenException: Found an invalid token 'rememberMeKey', at line: 28 and column: 5.
        Please make sure your JDL content does not use invalid characters, keywords or options.
Error: MismatchedTokenException: Found an invalid token 'rememberMeKey', at line: 28 and column: 5.
        Please make sure your JDL content does not use invalid characters, keywords or options.
    at throwErrorAboutInvalidToken (C:\Actoll\test\node_modules\generator-jhipster\jdl\parsing\api.js:85:9)
```

##### **Motivation for or Use Case**

It should work.

##### **Reproduce the error**

```
jhipster --skip-client
jhipster export-jdl test.jdl
```

  <details>
  <summary>Here is the JDL</summary>
  <pre>
application {
  config {
    applicationType monolith
    authenticationType session
    baseName test
    blueprints []
    buildTool maven
    cacheProvider ehcache
    clientFramework angularX
    clientPackageManager npm
    clientTheme none
    creationTimestamp 1616706630640
    databaseType sql
    devDatabaseType h2Disk
    dtoSuffix DTO
    enableHibernateCache true
    enableSwaggerCodegen false
    enableTranslation true
    jhiPrefix jhi
    jhipsterVersion "7.0.0"
    languages [fr]
    messageBroker false
    nativeLanguage fr
    otherModules []
    packageName com.mycompany.myapp
    prodDatabaseType postgresql
    reactive false
    rememberMeKey "091289ae37d3e497b9a48ccb2a0b6c3d27937f935fb426a1270eae3ac1b21e6c89c0daac55c8ba5054866691aed9aa48092f"
    searchEngine false
    serverPort 8080
    serviceDiscoveryType false
    skipClient true
    skipServer false
    skipUserManagement false
    testFrameworks []
    websocket false
    withAdminUi true
  }
}
  </pre>
  </details>

Import the JDL, parsing fails on `rememberMeKey`

```
jhipster jdl .\test.jdl
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing import-jdl .\test.jdl
error: Syntax error message:
        MismatchedTokenException: Found an invalid token 'rememberMeKey', at line: 28 and column: 5.
        Please make sure your JDL content does not use invalid characters, keywords or options.
Error during import-jdl: Error: MismatchedTokenException: Found an invalid token 'rememberMeKey', at line: 28 and column: 5.
```

##### **JHipster Version(s)**

```
C:\Actoll\test
`-- generator-jhipster@7.0.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.19.0, JRE 14 Windows 10 amd64-64-Bit Compressed References 20200318_5 (JIT enabled, AOT enabled)
OpenJ9   - 0133ba037
OMR      - 1c04e0ef9
JCL      - a73be60649 based on jdk-14+36)

git version 2.30.0.windows.2

node: v12.16.1

npm: 6.14.8

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build c4eb3a1f

##### **Browsers and Operating System**

Windows 10

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Looking into it

**Comment by gmarziou** [comment]
Thanks cause I have no idea how the parser works :)

**Comment by MathieuAA** [comment]
I think I know why... it's funny because jwtSecretKey can be read, but not this option.
There's a list of accepted tokens the parsed knows about and uses to consume what's inside a JDL file.
Here, the rememberMeKey option isn't allowed. That must be why.

I'm writing a test for it and fixing it.
