### ISSUE TITLE
Reactive: strange swagger

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#14476]
##### **Overview of the issue**

When using a Reactive application, the generated swagger is really strange

![reactive_swagger_1](https://user-images.githubusercontent.com/9156882/112718558-20e56100-8ef4-11eb-9662-b2c023e5dff5.png)

![reactive_swagger_2](https://user-images.githubusercontent.com/9156882/112718560-22af2480-8ef4-11eb-9a33-85e571c40878.png)

##### **Motivation for or Use Case**

The behaviour should be the same than MVC

##### **Reproduce the error**

- generate a Reactive application
- start it
- go to swagger and check the user API

##### **JHipster Version(s)**

7.0.0 and current main branch

##### **JHipster Version(s)**

```
appreactive@0.0.1-SNAPSHOT /home/pgrimaud/tmp/17-app-reactive
└── generator-jhipster@7.0.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "appreactive",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1616841818493,
    "serviceDiscoveryType": false,
    "reactive": true,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

git version 2.31.0

node: v14.16.0

npm: 7.7.5

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.27.3, build 4092ae5d

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

**Comment by cbornet** [comment]
I think it's because the reactive version has a `ServerHttpRequest` param in the method (from which we get info for the pagination).
It should be fixed by adding `.ignoredParameterTypes(ServerHttpRequest.class)` to the [docket configuration](https://github.com/jhipster/jhipster-bom/blob/4a3d667ecfcbd64e1105d5986a95a9bf00d8c2c1/jhipster-framework/src/main/java/tech/jhipster/config/apidoc/SpringfoxAutoConfiguration.java#L172)

**Comment by smaestri** [comment]
@cbornet you're right, this was the way to solve the problem (although the link is not correct, as we should modify API and not management docket). Done here https://github.com/jhipster/jhipster-bom/pull/243

**Comment by cbornet** [comment]
Actually it should be done in the customizer here : https://github.com/jhipster/jhipster-bom/blob/7bb09dd675fe2750ff83acb1656861441be67cdc/jhipster-framework/src/main/java/tech/jhipster/config/apidoc/customizer/JHipsterSpringfoxCustomizer.java#L94

**Comment by smaestri** [comment]
Thank for the review, I did not see this `customizer` at first. PR updated.

**Comment by smaestri** [comment]
Hi @pascalgrimaud  bug solved. As it is my first contribution to Jhispter, tell me if I miss something. https://opencollective.com/generator-jhipster/expenses/37557

**Comment by pascalgrimaud** [comment]
@smaestri : approved ! thanks for your contribution

@cbornet : you can claim the same bounty too, if you want, no need to split here, just ping me :-)

**Comment by cbornet** [comment]
@smaestri thanks for the contribution 👍.
@pascalgrimaud thanks a lot 🙂
