### ISSUE TITLE
Reactive: user and authorities

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#14475]
##### **Overview of the issue**

When using a Reactive application, the API doesn't get the authorities

![appreactive_authorities](https://user-images.githubusercontent.com/9156882/112718452-5fc6e700-8ef3-11eb-9975-908ed68a4850.png)

```json
[ {
  "id" : 1,
  "login" : "admin",
  "firstName" : "Administrator",
  "lastName" : "Administrator",
  "email" : "admin@localhost",
  "imageUrl" : "",
  "activated" : true,
  "langKey" : "en",
  "createdBy" : "system",
  "createdDate" : "2021-03-27T10:52:27.235540Z",
  "lastModifiedBy" : "system",
  "lastModifiedDate" : "2021-03-27T10:52:27.235541Z",
  "authorities" : [ ]
}, {
  "id" : 2,
  "login" : "user",
  "firstName" : "User",
  "lastName" : "User",
  "email" : "user@localhost",
  "imageUrl" : "",
  "activated" : true,
  "langKey" : "en",
  "createdBy" : "system",
  "createdDate" : "2021-03-27T10:52:27.236030Z",
  "lastModifiedBy" : "system",
  "lastModifiedDate" : "2021-03-27T10:52:27.236031Z",
  "authorities" : [ ]
} ]
```

##### **Motivation for or Use Case**

The behaviour should be the same between MVC and Reactive

##### **Reproduce the error**

- generate a Reactive application
- start it
- display user management page

##### **JHipster Version(s)**

7.0.0 and current main branch

##### **JHipster Version(s)**

```
appreactive@0.0.1-SNAPSHOT /home/pgrimaud/tmp/17-app-reactive
└── generator-jhipster@7.0.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "appreactive",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1616841818493,
    "serviceDiscoveryType": false,
    "reactive": true,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

git version 2.31.0

node: v14.16.0

npm: 7.7.5

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.27.3, build 4092ae5d

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

**Comment by chrisdns** [comment]
I will check this :+1:

**Comment by pascalgrimaud** [comment]
Thanks @chrisdns
