### ISSUE TITLE
Microservices with Istio on Kubernetes is broken

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#14479]
##### **Overview of the issue**

Seems like microsevices with Istio on Kubernetes is broken after v7. It was working until v7.0.0-beta.1. Seems like the new Reactive only gateway is the culprit as v7 beta 1 still had Zuul gateway. I haven't tested non Istio microservices yet.

Ping @PierreBesson @srinivasa-vasu 

##### **Reproduce the error**

Try this app for example https://gist.github.com/deepu105/1f0663af2acdb67dd5472c4896b595cf

##### **Suggest a Fix**

Not sure as i'm not that experienced in Reactive Spring 

##### **JHipster Version(s)**

v7

##### **JHipster configuration**

https://gist.github.com/deepu105/1f0663af2acdb67dd5472c4896b595cf

**Comment by mraible** [comment]
I tried deploying the reactive-ms JDL from samples to GCP with Kubernetes right before the release and it worked fine. I did not use Istio though.

**Comment by PierreBesson** [comment]
I will probably not have the time to look into this soon as I'm about to go on vacation.

**Comment by deepu105** [comment]
I'll try to spend some time on this, but I don't have much experience with
reactive gateways. lets see

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Keep open

Thanks & Regards,
Deepu

**Comment by sendilkumarn** [comment]
@deepu105 Can you explain a bit more about the issue here? I tried it just now and it works. But I am not seeing entities in the application, is that the problem?

**Comment by sendilkumarn** [comment]
Closing this. @deepu105 feel free to reopen if you still have any issues.

**Comment by deepu105** [comment]
You mean it works with reactive gateways out of the box? I was using Istio 1.8 I think. I can try 1.9 later

**Comment by deepu105** [comment]
@sendilkumarn I'm still running into this, the routing doesn't seem to work? were you able to create entities in other microservices when you tested them? I have tested with multiple versions of Istio from 1.8 to 1.11 and the routing to microservices doesn't work

**Comment by sendilkumarn** [comment]
last time I checked it was working with Spring Cloud Gateway and Zuul. I have used it on one of my presentation too. But it was 6 months before. 

Are you sure you have setup Istio, creds, and Roles correctly?

**Comment by deepu105** [comment]
Zuul was removed in 7.0.0 so unless you checked before that I'm not sure how it worked. I did some bisect and the last version this worked was in 7.0 alpha before migrating to spring gateway. My Istio setup is based on the default demo profile, what creds and roles did you setup?
