### ISSUE TITLE
Vue: npm start doesn't refresh correctly

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#14474]
##### **Overview of the issue**

When using `npm start` with Vue application, the page is not correctly refreshed when changing the code

##### **Motivation for or Use Case**

`npm start` should work fine

##### **Reproduce the error**

- generate a Vue application
- start the app
- start with `npm start`
- change home.vue for example -> it doesn't refresh automatically, you need to manually refresh the page

It works well with Angular
Not tried with React

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/15-app-vue
└── generator-jhipster@7.0.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1616840005429,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

git version 2.31.0

node: v14.16.0

npm: 7.7.5

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.27.3, build 4092ae5d

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/37020 :)

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
