### ISSUE TITLE
Strings starting with upper and lowercase letters are not correctly sorted in entities pages

### ISSUE THREAD

**Issue by vitoraasouza** [jhipster/generator-jhipster#14489]
##### **Overview of the issue**

When we try to sort the entries of an entity by a String field, the Strings starting with uppercase letters come before the ones starting with lowercase letters.

![Screenshot from 2021-03-27 23-33-16](https://user-images.githubusercontent.com/18122521/112740707-a6e5c400-8f55-11eb-9483-852393262eec.png)

##### **Motivation for or Use Case**

The sorting should respect the alphabet order.

##### **Reproduce the error**

- Create a simple application (I think that different configurations do not influence the final result)
- Add an entity with a String field
- Create some entity's entries with Strings starting with upper and lowercase letters
- Sort the entries by the String field and check the result

##### **JHipster Version(s)**

```
projectone@0.0.1-SNAPSHOT /home/shiryu/Desktop/test_jhi7/new-project2
└── generator-jhipster@7.0.0

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "projectone",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1616898152383,
    "serviceDiscoveryType": "eureka",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "one.project",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "one/project",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1616898359000,
    "entities": ["TestTable"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity TestTable {
  name String
  age Integer
}
paginate TestTable with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11-ea" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11-ea+4-Ubuntu-0ubuntu3.16.04.1)
OpenJDK 64-Bit Server VM (build 11.0.11-ea+4-Ubuntu-0ubuntu3.16.04.1, mixed mode, sharing)

git version 2.31.1

node: v14.16.0

npm: 7.7.5

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.6, build 5db8d86f

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

**Comment by ruddell** [comment]
This is related to `postgresql` sorting rather than the frontend, and does not reproduce when using the Docker container for postgresql in `src/main/postgresql.yml`.

It's probably related to your local system: https://wiki.postgresql.org/wiki/FAQ#Why_do_my_strings_sort_incorrectly.3F

I'm not sure there is anything actionable we can do on our end.
