### ISSUE TITLE
Swagger authtentication is broken

### ISSUE THREAD

**Issue by VergilSkye** [jhipster/generator-jhipster#14488]
##### **Overview of the issue**

In the v7 version the swagger-ui doesn't have autentication and make unauthorized request.
When open by the _Adminstration_ tab and select **API** will open the API documentation (the user is already login in the app and have the ROLE_ADMIN)

when i try to use any endpoint i have the following response 
```
"type": "https://www.jhipster.tech/problem/problem-with-message",
  "title": "Unauthorized",
  "status": 401,
  "detail": "Full authentication is required to access this resource",
  "path": "/api/account",
  "message": "error.http.401"
```

##### **Motivation for or Use Case**

swagger must work by default with the user autentication

##### **JHipster configuration**
<pre>&lt;details&gt;
&lt;summary&gt;.yo-rc.json file&lt;/summary&gt;
&lt;pre&gt;
{
  &quot;generator-jhipster&quot;: {
    &quot;blueprints&quot;: [],
    &quot;otherModules&quot;: [],
    &quot;applicationType&quot;: &quot;monolith&quot;,
    &quot;baseName&quot;: &quot;pessoa&quot;,
    &quot;jhipsterVersion&quot;: &quot;7.0.0&quot;,
    &quot;skipClient&quot;: false,
    &quot;skipServer&quot;: false,
    &quot;skipUserManagement&quot;: false,
    &quot;skipCheckLengthOfIdentifier&quot;: false,
    &quot;skipFakeData&quot;: false,
    &quot;jhiPrefix&quot;: &quot;jhi&quot;,
    &quot;entitySuffix&quot;: &quot;&quot;,
    &quot;dtoSuffix&quot;: &quot;DTO&quot;,
    &quot;testFrameworks&quot;: [],
    &quot;pages&quot;: [],
    &quot;creationTimestamp&quot;: 1616757108518,
    &quot;serviceDiscoveryType&quot;: false,
    &quot;reactive&quot;: false,
    &quot;authenticationType&quot;: &quot;jwt&quot;,
    &quot;packageName&quot;: &quot;dev.vergil&quot;,
    &quot;serverPort&quot;: &quot;8080&quot;,
    &quot;cacheProvider&quot;: &quot;ehcache&quot;,
    &quot;enableHibernateCache&quot;: true,
    &quot;databaseType&quot;: &quot;sql&quot;,
    &quot;devDatabaseType&quot;: &quot;h2Memory&quot;,
    &quot;prodDatabaseType&quot;: &quot;postgresql&quot;,
    &quot;buildTool&quot;: &quot;maven&quot;,
    &quot;serverSideOptions&quot;: [&quot;websocket:spring-websocket&quot;],
    &quot;websocket&quot;: &quot;spring-websocket&quot;,
    &quot;searchEngine&quot;: false,
    &quot;messageBroker&quot;: false,
    &quot;enableSwaggerCodegen&quot;: false,
    &quot;clientFramework&quot;: &quot;angularX&quot;,
    &quot;withAdminUi&quot;: true,
    &quot;clientTheme&quot;: &quot;none&quot;,
    &quot;enableTranslation&quot;: true,
    &quot;nativeLanguage&quot;: &quot;pt-br&quot;,
    &quot;packageFolder&quot;: &quot;dev/vergil&quot;,
    &quot;jwtSecretKey&quot;: &quot;YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons&quot;,
    &quot;clientPackageManager&quot;: &quot;npm&quot;,
    &quot;clientThemeVariant&quot;: &quot;&quot;,
    &quot;languages&quot;: [&quot;pt-br&quot;, &quot;en&quot;],
    &quot;entities&quot;: [&quot;Pessoa&quot;],
    &quot;lastLiquibaseTimestamp&quot;: 1616759375000
  }
}

&lt;/pre&gt;
&lt;/details&gt;
</pre>
##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * The Pessoa entity.\n@author Virgílio Stefanin
 */
entity Pessoa {
  /**
   * Nome obrigatorio
   */
  nome String required
  /**
   * Sexo enum com tres opcoes, Masculino, Feminino, Outros
   */
  sexo TipoSexo
  /**
   * Email nao obrigatorio
   */
  email String
  /**
   * Data de nascimento obrigatoria
   */
  dataNascimento LocalDate required
  /**
   * Naturalidade não obrigatória
   */
  naturalidade String
  /**
   * Nacionalidade não obrigatória
   */
  nacionalidade String
  cpf String required unique
}
enum TipoSexo {
  MASCULINO,
  FEMININO,
  OUTROS
}

dto Pessoa with mapstruct
paginate Pessoa with pagination
service Pessoa with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

git version 2.25.1

node: v12.18.2

npm: 6.14.5

Docker version 20.10.5, build 55c4c88

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Should be fixed by https://github.com/jhipster/generator-jhipster/pull/14443.

**Comment by VergilSkye** [comment]
thanks, with this change my swagger is functional. 
@mshima someone report when you run the ```npm start``` command it's opening port **9000** on browser and it should be port **4200**?

**Comment by mshima** [comment]
@VergilSkye 9000 is browser sync while 4200 is ng serve.
I know a problem that `ng build` wrongly runs browser sync.

**Comment by VergilSkye** [comment]
Thanks for the info, so my browser sync it's broken, only 4200 it's working on the moment,i will investigate tomorrow and make a separate issue, For this one it's already close :)

**Comment by pascalgrimaud** [comment]
@VergilSkye : we did this fix yesterday for Vue https://github.com/jhipster/generator-jhipster/pull/14478
Maybe there is the same issue for Angular?

**Comment by pascalgrimaud** [comment]
Reopening this ticket as the PR is not merged yet

**Comment by VergilSkye** [comment]
> @VergilSkye : we did this fix yesterday for Vue #14478
> Maybe there is the same issue for Angular?

no, it's not the same issue i think. 

in my generated project, I changed the _auth-jwt.service.ts_ file line 24 and 25 

```
const tokenInLocalStorage: string | null = this.$localStorage.retrieve('authenticationToken');
const tokenInSessionStorage: string | null = this.$sessionStorage.retrieve('authenticationToken');
```   
to 
```
const tokenInLocalStorage: string | null = this.$localStorage.retrieve('jhi-authenticationToken');
const tokenInSessionStorage: string | null = this.$sessionStorage.retrieve('jhi-authenticationToken');
```
and in the file _app.module.ts_ line 44 i changed 
```
NgxWebstorageModule.forRoot({ prefix: 'jhi', separator: '-' }),
```

to 

```
NgxWebstorageModule.forRoot({ prefix: 'jhi', separator: '-', caseSensitive: true }),
```

these changes were copied from commit #14443

so i think the  #14443 should fix this problem,

**Comment by VergilSkye** [comment]
So i'm make a dummy project for a interview process with swagger and websocktes,
I verified that the websockets are not working either because of the jwt token. I modified the file _auth.interceptor.ts_ line **22** and several lines _auth-jwt.service.ts_ adding the prefix **jhi** .  So it' not only swagger broken, websockets too. 

I wish to make a pr request or download #14443 to see if fixes my problem, but i have little time today :(

**Comment by pascalgrimaud** [comment]
@VergilSkye : my comment was for browser sync, not for broken swagger, which is in PR :-)
