### ISSUE TITLE
🚀 Create constraints on multiple columns

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#14529]
##### **Overview of the feature request**
Allow to create unique constraints on multiple columns when importing from a JDL file.

##### **Motivation for or Use Case**
It might be useful to other users (I actually found it useful). It could be something like 

``` javascript
@Unique(column1, column2, column3)
entity Example
```

and that would generate

```java
@Table(name = "example",
    uniqueConstraints = {
        @UniqueConstraint(columnNames = {"column1", "column2", "column3"})
    })
```

##### **Related issues or PR**
None that I know of.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
First problem, jdl doesn't support arrays https://github.com/jhipster/generator-jhipster/pull/12632.

**Comment by MathieuAA** [comment]
I'm against it. A constraint should be linked to the field (JDL-wise) instead of the entity. 
That, and this syntax would require you to update the name at least twice when changing a field's name.

**Comment by amatosg** [comment]
Wel, that would be the case then dealing with constraints that involve only one field. Besides, when dealing with Unique constraints, I don't think I would see changes that often to the field names.

**Comment by laariche-khalid** [comment]
Hi any Update in this feature , it's very useful
