### ISSUE TITLE
turn off/customize table name prefix

### ISSUE THREAD

**Issue by Qinwroks** [jhipster/generator-jhipster#1452]
i think it will be great i can turn off table name prefix or use a more meaningful prefix.

**Comment by jdubois** [comment]
We don't have prefixes anymore for normal tables. Are you referring to the JHI_ prefix ?

**Comment by Qinwroks** [comment]
yes. the pre-generated entities have JHI prefiex

**Comment by jdubois** [comment]
This is only for the JHipster tables, not for your own tables.
We can't remove this prefix: there was a lot of talk about it, the biggest issue being that "User" is a reserved keyword in Postgresql, so we can't map the "User" entity on a "User" table. Pretty bad, but that's Postgresql's fault, not ours...
So we can't remove this, but if you don't like it, and of course if you don't use Postgesql, it's very easy to change (just change the mapping and the Liquibase changelog)

**Comment by tporadowski** [comment]
@jdubois just for clarification - you're right that using reserved keywords is problematic, but you *could* use them even as table and column names (they just need to be passed in backticks, i.e. `` `User` ``, which can also be configured for Hibernate/JPA)

**Comment by jdubois** [comment]
@tporadowski I didn't know about this "backtick" usage... Are you sure it works for all databases, and for JPA? In that case we could indeed remove all "JHI_" prefix...
The prefix can still be useful to know which tables are from JHipster, and maybe for people (like me) who don't know about the "backtick", but if we can get rid of it, it would be better.
In that case we could remove all reserved keyword checks... Do you know if this works with MongoDB and Cassandra also?

**Comment by tporadowski** [comment]
@jdubois [this StackOverflow reply](http://stackoverflow.com/questions/3608420/hibernate-saving-user-model-to-postgres/3611916#3611916) covers Postgresql with Hibernate or JPA, I think MySQL can safely use the same approach (using backticks is much more common there anyway). Yet, I don't know if this is supported in MongoDB or Cassandra.
