### ISSUE TITLE
Add the JHipster technical board page on the website

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#14539]
##### **Overview of the feature request**
Following the last JHipster developer association meeting, I'm creating a new PR to add the JHipster technical board page on the official website.

The technical board is a committee to help the project to ensures the platform continues to reflect and serve its diverse and growing user community.

For more details, please check the PR content.

The name still needs to be defined, here are the propositions:
- Technology Advisory Board
- JHipster Tech Board
- JHipster Board
- JHipster Steering Committee
- JHipster Engineering Task Force (JETF)

Please check the PR too

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
I vote for "Technology Advisory Board" which makes things simply and clear in my opinion. 😄

**Comment by DanielFran** [comment]
I would vote for "Technology Advisory Board" too

**Comment by MathieuAA** [comment]
So do I

**Comment by atomfrede** [comment]
Keep it open

**Comment by avdev4j** [comment]
Keep it open please. Work in progress

**Comment by avdev4j** [comment]
Keep it open
