### ISSUE TITLE
Grunt build fails due to autoprefixer:generated having no source files

### ISSUE THREAD

**Issue by kaliatech** [jhipster/generator-jhipster#1453]
Running "grunt build" on clean project setup eventually results in:

```
Running "ngAnnotate:dist" (ngAnnotate) task
>> 2 files successfully generated.

Running "cssmin:generated" (cssmin) task
>> Destination not written because minified CSS was empty.

Running "autoprefixer:generated" (autoprefixer) task
Warning: No source files were found. Use --force to continue.

Aborted due to warnings.
```

The Gruntfile.js has comment in autoprefixer configuration stating "not used since Uglify task does autoprefixer".  So, I commented out the autoprefixer from the build task, and things seemed to work.

Using jhipster 2.10.1 on windows, grunt 0.4.5.  Compass selected during init options.

**Comment by jdubois** [comment]
This is probably linked to Compass, can you try without it?

**Comment by kaliatech** [comment]
Confirmed. This is only an issue if Compass is being used.

**Comment by jdubois** [comment]
OK, just so you are not blocked: I understand why I didn't see it, it's because I don't use that task!
I just do a "grunt serve" and it works.

But of course "grunt build" should also work, I'm going to have a look at it.

**Comment by jdubois** [comment]
This was due to the vendor.css which doesn't exist in the Compass build (as the Bootstrap css code is imported in the main.css file). It's this file which was causing the "minified CSS was empty" error, as it didn't exist.

**Comment by andidev** [comment]
This commit removes the injection of css files when installing new Bower packages with css dependencies. Don't think this is the correct solution.

**Comment by jdubois** [comment]
@andidev it removes them only for Compass (there's a "if"), and in that case the files are imported directly into the main.scss file (that was how it worked before, I don't know if that's a good idea or not)

**Comment by andidev** [comment]
Not sure about that. I think sass files are injected in the main.scss files but css files are not. Css files are injected in index.html vendor.

**Comment by andidev** [comment]
I just confirmed this introduces a new bug. see comment on commit
https://github.com/jhipster/generator-jhipster/commit/c831a7bbc48e2940b9880703864d6b40ea85f37a

**Comment by jdubois** [comment]
Oh yes, indeed, that will cause this error, sorry I didn't understand what you meant!
I'm not sure how to solve this, thus.

**Comment by andidev** [comment]
I'll figure something out

**Comment by andidev** [comment]
Please merge the "Autoprefixer fails fix" pull request to revert your changes @jdubois and apply the correct fix
