### ISSUE TITLE
Unable to login : CSRF Validation failed on OAuth2 authentification with gulp serve

### ISSUE THREAD

**Issue by dstackowiak** [jhipster/generator-jhipster#1454]
**Overview**
When i try to login, on port 9000 (gulp serve), i've this response on token call : 
> {"timestamp":1431102471126,"status":403,"error":"Forbidden","message":"Expected CSRF token not found. Has your session expired?","path":"/oauth/token/"}

No problem on 8080

**JHipster version** : 2.10.1

**Comment by lunias** [comment]
Getting the same issue w/ generator-jhipster@2.16.0.

Clean install. Here is my yo-rc.json.

{
  "generator-jhipster": {
    "baseName": "rc",
    "packageName": "com.ethanaa.rc",
    "packageFolder": "com/ethanaa/rc",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useCompass": true,
    "buildTool": "gradle",
    "frontendBuilder": "gulp",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "32ea117046a2e6f8bc454b9211cb9833ec912272"
  }
}

**Comment by gmarziou** [comment]
It still exists in 2.19.0.

**Comment by gmarziou** [comment]
@dstackowiak @lunias 

Could try to change version of proxy-middleware as below in package.json?

    "proxy-middleware": "0.13.1"

For me, it fixes the CSRF issue
