### ISSUE TITLE
Values generated by Faker are changing on regeneration

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#14549]
##### **Overview of the issue**

In Angular entity update test https://github.com/jhipster/generator-jhipster/blob/943fd873d29a3d8ed4fab31d8d2fa91fc71fd1d8/generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.spec.ts.ejs#L84 there are related entity objects with primary keys generated by Faker.

If for the related entity is not yet called `resetFakerSeed()` https://github.com/jhipster/generator-jhipster/blob/943fd873d29a3d8ed4fab31d8d2fa91fc71fd1d8/generators/entity-client/files.js#L442 then in every regeneration different fake values are generated.

The same values are generated in those cases:
* if server generation is not skipped then in server sub generator `resetFakerSeed()` is already called for every entity and always the same value is generated
* if you are lucky and entities generation order is suitable (referenced entities are generated before) then the same value is generated

But if neither of the above conditions is met then every regeneration generates the different values.

Entities generation order is calculated based on entity `changelogDate`:
https://github.com/jhipster/generator-jhipster/blob/943fd873d29a3d8ed4fab31d8d2fa91fc71fd1d8/generators/generator-base.js#L1559-L1561

The same problem may occur elsewhere where in entities is used Faker data for related entities.

##### **Motivation for or Use Case**

Regeneration should generate the same content as initial generation.

##### **Reproduce the error**

Generate application with: `jhipster --skip-server`

Create `entities.jdl` with content:
```
entity Entity1 {
    field1 String
}
```

Generate first entity with: `jhipster import-jdl entities.jdl`

Change `entities.jdl` to:
```
entity Entity1 {
    field1 String
}
entity Entity2 {
    field2 String
}
relationship OneToMany {
    Entity2{entity1} to Entity1{entity2}
}
```

Run again: `jhipster import-jdl entities.jdl`

If now regenerating entities for example with:
```
jhipster entities
```
then every time new random `Entity2` id-s are generated because `Entity1` is generated before `Entity2` and `resetFakerSeed()` for `Entity2` is not called yet.

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT C:\projects\teest\jhipster-faker3
`-- generator-jhipster@7.0.0 -> C:\projects\contro\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "skipServer": true,
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1617277519460,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "et"],
    "packageName": "com.mycompany.myapp",
    "cacheProvider": "ehcache",
    "websocket": false,
    "databaseType": "sql",
    "prodDatabaseType": "postgresql",
    "devDatabaseType": "h2Disk",
    "searchEngine": false,
    "buildTool": "maven",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "serviceDiscoveryType": false,
    "enableHibernateCache": true,
    "reactive": false,
    "entities": ["Entity1", "Entity2"],
    "lastLiquibaseTimestamp": 1617278155000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Entity1 {
  field1 String
}
entity Entity2 {
  field2 String
}
relationship OneToMany {
  Entity2{entity1} to Entity1{entity2}
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

git version 2.31.1.windows.1

node: v14.16.0

npm: 7.7.6

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build c4eb3a1f

##### **Browsers and Operating System**

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@kaidohallik can you try calling resetFakerSeed after it was created?
https://github.com/jhipster/generator-jhipster/blob/3142b03e85d65af8fe4851f0984d9284c4cfc6bf/utils/entity.js#L86

**Comment by kaidohallik** [comment]
@mshima If calling `resetFakerSeed` after it was created then this fixes this issue.
Should we remove all other `resetFakerSeed()` calls and leave only this new one?

**Comment by mshima** [comment]
> Should we remove all other `resetFakerSeed()` calls and leave only this new one?

Thinking about this, we can replace the others call, with
```
const templatePath = generator.templatePath(source);
if (generator.resetFakerSeed) {
  generator.resetFakerSeed(templatePath);
}
```
before https://github.com/jhipster/generator-jhipster/blob/f35cf8becc58c3ea52038a09138ed1cae2895a24/generators/utils.js#L286

With this change, files will be reproducible independently. An additional call to the faker at any file will not change others files.

**Comment by kaidohallik** [comment]
Adding `generator.resetFakerSeed` to function `renderContent` in file `utils.js` doesn't improve reproducibility in the current generator version.

Calling `entityWithConfig.resetFakerSeed()` after it was created is still needed to achieve reproducible build because faker is used in entity context:
https://github.com/jhipster/generator-jhipster/blob/d2a00cd343346c4550c4ceff18605bf1d6c60964/utils/field.js#L276
So for related entity this is in related entity context.

I'll do PR which adds call to `resetFakerSeed` after this is created and removes other unnecessary `resetFakerSeed` calls.

**Comment by kaidohallik** [comment]
I created #14595 for fix. If I tried to remove `resetFakerSeed` from other places then:
* in the existing project first regeneration in some places different fake values were generated (next regenerations generated the same values)
* generator tests didn't pass

So I added only one line for fix.

**Comment by mshima** [comment]
I will take a look at https://github.com/jhipster/generator-jhipster/issues/14549#issuecomment-813366054 later.
I think it will improve long term reproducibility.
