### ISSUE TITLE
Command mvnw -P-webapp don't works

### ISSUE THREAD

**Issue by FrancescoMez79** [jhipster/generator-jhipster#14548]
Dear Support,
we have created a Monolithic application in Jhipster 6.10.5.

REading the Jhipster documentation :
https://www.jhipster.tech/development/

is written that we can use the command : ./mvnw -P-webapp 
https://i.imgur.com/6p4zg0f.png
to run only the server side application.

This don't works. It run even the client side application (Angular) :

this is the log attached:
[logJHipster.txt](https://github.com/jhipster/generator-jhipster/files/6241754/logJHipster.txt)

Looking the pom.xml, instead we see only the profile "webpack" and not "webapp", and using this profile with the command mvnw it works.

<profile>
            <id>webpack</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.h2database</groupId>
                    <artifactId>h2</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.eirslett</groupId>
                        <artifactId>frontend-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>install node and npm</id>
                                <goals>
                                    <goal>install-node-and-npm</goal>
                                </goals>
                                <configuration>
                                    <nodeVersion>${node.version}</nodeVersion>
                                    <npmVersion>${npm.version}</npmVersion>
                                </configuration>
                            </execution>
                            <execution>
                                <id>npm install</id>
                                <goals>
                                    <goal>npm</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>webpack build dev</id>
                                <goals>
                                    <goal>npm</goal>
                                </goals>
..

So, is this a problem of the Documentation?

Thanks,
Francesco

**Comment by pascalgrimaud** [comment]
With 6.10.5, it was webpack
With 7.0.0, it is webapp

So the documentation was updated to the last version. You should have a look at the archive: https://www.jhipster.tech/documentation-archive/

**Comment by pascalgrimaud** [comment]
As there is no bug here, I'm closing the ticket
