### ISSUE TITLE
Microservice swagger access not authorized from Gateway

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#14556]
##### **Overview of the issue**

I have just created a new microservice architecture with one gateway and one microservice with last version of JHipster v7.0.0.
When I try to access the swagger documentation of the microservice via the Gateway portal, I receive the following error:

![image](https://user-images.githubusercontent.com/1822749/113404580-b0818880-93a8-11eb-99b2-19093eb09abc.png)

##### **Motivation for or Use Case**

As described in the JHipster documentation at [Automatic documentation](https://www.jhipster.tech/api-gateway/#documentation), I would like to access the swagger documentation of the microservice via the gateway portal for tests

##### **Reproduce the error**

1. Create a new microservice and a new gateway with the last JHipster version 7.0.0.
2. Change the JHipster JWT secret in the microservice with the one from the gateway as described here [JWT (JSON Web Token)](https://www.jhipster.tech/api-gateway/#security)
3. Using the JDL command, create the new entities in the microservice and in the gateway (I used the default file from the online  [JDL Studio](https://start.jhipster.tech/jdl-studio/) )
4. Launch all the services including the JHpster Registry
5. Login to the Gteway portal using the admin credential and from the navigation menu go to "admin > API"

##### **JHipster Version(s)**

Version 7.0.0

##### **JHipster configuration**

Microservice .yo-rc.json

```
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "microservice",
    "baseName": "microservice700",
    "jhipsterVersion": "7.0.0",
    "skipClient": true,
    "skipUserManagement": true,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1617354155906,
    "serviceDiscoveryType": "eureka",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8081",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "....",
    "languages": ["en", "al", "ar-ly", "hy", "bn", "fi"],
    "entities": ["Region", "Country", "Location", "Department", "Task", "Employee", "Job", "JobHistory"],
    "lastLiquibaseTimestamp": 1617354341000
  }
}
```

Gateway .yo-rc.json

```
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "gateway",
    "baseName": "gateway700",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1617354389345,
    "serviceDiscoveryType": "eureka",
    "reactive": true,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "....",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "al", "ar-ly", "hy", "by", "bn", "bg", "zh-cn", "hr", "cs", "nl"],
    "entities": ["Region", "Country", "Location", "Department", "Task", "Employee", "Job", "JobHistory"],
    "lastLiquibaseTimestamp": 1617354988000
  }
}
```

##### **Browsers and Operating System**

Browser: Chrome
Operating System: Ubuntu 20.04

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@alexsintoni : how did you start your application plz ?

**Comment by mshima** [comment]
May be related to https://github.com/jhipster/generator-jhipster/pull/14443

**Comment by pascalgrimaud** [comment]
Oh yes, good catch @mshima : the release is in progress :)
