### ISSUE TITLE
Authority as relationship name not work!

### ISSUE THREAD

**Issue by ohforest** [jhipster/generator-jhipster#14596]
`$cat authority_entity_to_relationship.jdl`
entity A
entity B

relationship ManyToOne {
  A{authority} to Authority
}

relationship OneToOne {
  B{authority} to Authority
}
`$jhipster import-jdl ../authority_entity_to_relationship.jdl`
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing import-jdl ../authority_entity_to_relationship.jdl
INFO! The JDL is being parsed.
INFO! Found entities: A, B.
INFO! The JDL has been successfully parsed
INFO! Generating 0 applications.
INFO! Generating 2 entities.
INFO! Generating entities for application undefined in a new parallel process

Found the .jhipster/A.json configuration file, entity can be automatically generated!

Found the .jhipster/B.json configuration file, entity can be automatically generated!

info Creating changelog for entities A,B
Error running generator entities: Error: Error looking for otherEntity Authority
Error: Error looking for otherEntity Authority
    at /Users/jiang/workspace/java-workspace/localhost/security/node_modules/generator-jhipster/generators/entity/index.js:530:19
    at Array.forEach (<anonymous>)
    at EntityGenerator.loadRelationships (/Users/jiang/workspace/java-workspace/localhost/security/node_modules/generator-jhipster/generators/entity/index.js:526:36)
    at Object.<anonymous> (/Users/jiang/workspace/java-workspace/localhost/security/node_modules/yeoman-generator/lib/index.js:1009:25)
    at /Users/jiang/workspace/java-workspace/localhost/security/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/jiang/workspace/java-workspace/localhost/security/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/jiang/workspace/java-workspace/localhost/security/node_modules/yeoman-generator/lib/index.js:1010:11)
    at Immediate.<anonymous> (/Users/jiang/workspace/java-workspace/localhost/security/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at processImmediate (internal/timers.js:461:21)
ERROR! Error looking for otherEntity Authority
Error: Error looking for otherEntity Authority
    at /Users/jiang/workspace/java-workspace/localhost/security/node_modules/generator-jhipster/generators/entity/index.js:530:19
    at Array.forEach (<anonymous>)
    at EntityGenerator.loadRelationships (/Users/jiang/workspace/java-workspace/localhost/security/node_modules/generator-jhipster/generators/entity/index.js:526:36)
    at Object.<anonymous> (/Users/jiang/workspace/java-workspace/localhost/security/node_modules/yeoman-generator/lib/index.js:1009:25)
    at /Users/jiang/workspace/java-workspace/localhost/security/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/jiang/workspace/java-workspace/localhost/security/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/jiang/workspace/java-workspace/localhost/security/node_modules/yeoman-generator/lib/index.js:1010:11)
    at Immediate.<anonymous> (/Users/jiang/workspace/java-workspace/localhost/security/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at processImmediate (internal/timers.js:461:21)

`$jhipster --version`
INFO! Using JHipster version installed locally in current project's node_modules
7.0.1

**Comment by ecostanzi** [comment]
Is it a monolith or a microservice? Can you paste the entire output of `jhipster info` command?

**Comment by ohforest** [comment]
> Is it a monolith or a microservice? Can you paste the entire output of `jhipster info` command?

$jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
security@0.0.0 /Users/jiang/workspace/java-workspace/localhost/security
└── generator-jhipster@7.0.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "security",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1617727239830,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.localhost.security",
    "serverPort": "8080",
    "cacheProvider": "redis",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": ["enableSwaggerCodegen:true"],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "yeti",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "packageFolder": "com/localhost/security",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "languages": ["zh-cn", "en"]
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v14.16.0

npm: 6.14.11

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build c4eb3a1f


No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
