### ISSUE TITLE
Can not find index.html when starting with Application.main()

### ISSUE THREAD

**Issue by Mavlarn** [jhipster/generator-jhipster#1459]
I just created a new project with latest version, 2.10.1, and added several entities, and no other modification, and started the app with Application.main(). Then I got 404 error when I access http://localhost:8080 or access with ip. And it is same when I start "grunt serve" and access.

But when I start with "mvn spring-boot: run", there is no problem.

Is it my environment related problem? or I need to configure something?

**Comment by jdubois** [comment]
Yes it's supposed to working "out of the box" when you run the Application class file.

Maybe refresh your browser? Or do a "npm install" and "bower install" again? Did it work before adding the entities?

So yes it should be related to environment, at least I can't reproduce it (I just did it on the [sample app](https://github.com/jhipster/jhipster-sample-app), and it worked).

**Comment by gmarziou** [comment]
Try changing artifc

**Comment by jdubois** [comment]
@gmarziou it's not the first time I read this -> do you have more information on this? I don't understand this at all, do we need to change something in what is being generated?

**Comment by gmarziou** [comment]
I'm not sure what is wrong here, my application had to be packaged as war file when using prod profile but it was generated 3 months ago with jhipster version at that time before the introduction of BrowserSync.
The content of the jar file is missing lot of files under webapp folder, so I package it as a war even though I execute it as an executable jar. 
I'm not at work this week so I can't investigate but I will when I come back.

**Comment by jdubois** [comment]
What I don't understand is that there is no JAR file normally, just a WAR file. Did you follow http://jhipster.github.io/production.html ?

**Comment by gmarziou** [comment]
Yes that's what I did, next week I'll run diff on my pom.xml versus the one generated with current generator.

**Comment by gmarziou** [comment]
I diffed the pom and could not find a clear evidence: I use older spring-boot 1.2.2 and I don't exclude starter-tomcat from starter-web as below. I don't have time right now to investigate this.

~~~~
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
~~~~
