### ISSUE TITLE
Bad request with websocket on Amazon Cloud

### ISSUE THREAD

**Issue by wuethrich44** [jhipster/generator-jhipster#1460]
I try to use websocket on a Amazon Elastic Beanstalk. But when the client try to connect to the server, I got a `400 Bad Request`.

Has somebody any experience with deploy jhipster to AWS?

**Comment by jdubois** [comment]
Yes, Websocket do not work from being Amazon Elastic Beanstalk, you need to use a separate port for this.
This is typically what CloudFoundry does.

This is not a JHipster issue, it's a limitation with the AWS load balancer.

**Comment by wuethrich44** [comment]
fyi: You must set all load balancers (outgoing port 8080) and all security groups to tcp. Then you must add `<scope>provided</scope>` to the embedded tomcat dependency in you `pom.xml`. After that changes websockets should work on aws.

**Comment by jdubois** [comment]
Oh thanks @wuethrich44 !
People at Pivotal should hire you, as their CloudFoundry instance can't operate on the normal ports :-)
