### ISSUE TITLE
Use of gradle daemon makes bower fail during build

### ISSUE THREAD

**Issue by vwiencek** [jhipster/generator-jhipster#1461]
Maybe it's not the right place for this bug/issue.

When using gradle daemon (`org.gradle.daemon=true` in `.gradle/gradle.properties`) then bower fails during build.

`gradle bootRun --stacktrace` 

gives the following stacktrace http://pastebin.com/Mf1vGdir

when I run `gradle bootRun --stacktrace --no-daemon` it works fine

**Comment by atomfrede** [comment]
Using the gradle wrapper here works fine. Which gradle version are you using? Can you try using the wrapper:

``gradlew bootRun --daemon``

**Comment by jdubois** [comment]
If you don't use the wrapper, and don't provide the version number you use instead, we just can't help you, so I'm closing this.
