### ISSUE TITLE
JPA Entity Filtering option does not work when using reactive option

### ISSUE THREAD

**Issue by aricooperman** [jhipster/generator-jhipster#14616]
##### **Overview of the issue**

If you select reactive = true and also try to enable filtering on any entities, those entities will not have any filtering code generated for them, or at least the API does not support it

##### **Motivation for or Use Case**

If you want to have entity filtering and reactive at same time

##### **Reproduce the error**

Enable filtering on any entity and turn reactive on

##### **Related issues**

None seen

##### **Suggest a Fix**

Unsure

##### **JHipster Version(s)**

7.0.1

##### **JHipster configuration**

JDL to quickly reproduce, Just toggle reactive on and off and check resulting generation

<details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    applicationType monolith
    authenticationType jwt
    baseName reactivefilterbug
    buildTool gradle
    packageName com.foo.bar
    reactive true
  }

  entities *
}

entity A {
  a Boolean required
  b Integer required
  c String required
}

filter *
  </pre>
  </details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Generated from JDL above

##### **Browsers and Operating System**

Should not be browser or platform related but testing on Fedora 33

**Comment by smaestri** [comment]
After some investigations, _Jhipster_ use Spring Data Specifications and [JpaSpecificationExecutor](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaSpecificationExecutor.html) in non-reactive mode, not yet supported in reactive mode, as indicated [here](https://github.com/spring-projects/spring-data-r2dbc/issues/246). I suppose it would be possible to do it with existing _r2dbc_ APIs, but not sure if it's relevant.

**Comment by smaestri** [comment]
After some deeper investigations, I seems possible to do filtering by using [Query By Example r2dbc feature.](https://docs.spring.io/spring-data/r2dbc/docs/1.3.0/reference/html/#r2dbc.repositories.queries.query-by-example) An example can be seen [here](https://github.com/spring-projects/spring-data-examples/tree/main/r2dbc/query-by-example). However, this feature requires _Spring Boot 2.5.0-RC1._, not yet released, and so not part of _Jhipster_ for now.
But I think it is possible to start working on this feature, and release it when _Spring Boot 2.5.0-RC1_ will be integrated into _JHipster_. Any remark or suggestion are welcome!

**Comment by Tcharl** [comment]
Please go for it @smaestri !

**Comment by DanielFran** [comment]
@smaestri Can you confirm you are still available to contribute with a PR?

**Comment by smaestri** [comment]
Hi, yes I have some free time to work on it in the next weeks. I Keep you posted

**Comment by dwarakaprasad** [comment]
_Full disclosure - I am new to this Reactive & Criteria part_

Just out of curiosity, why not use the existing org.springframework.data.relational.core.sql.* or org.springframework.data.relational.core.query.* to implement this feature. 

Based on this [issue - referenced by @smaestri](https://github.com/spring-projects/spring-data-r2dbc/issues/246) spring R2DBC does not support relationship, so why bring in Query By Example. 

I feel that the existing EntityCriteria implementation can be reused and the org.springframework.data.relational.core.sql.Condition part could be built based on the search-criteria enabling the filtering option (I am hoping that the Condition/Criteria would support all the existing non-reactive filtering options - I can do some investigation if you guys think its an acceptable approach)

**Comment by dwarakaprasad** [comment]
Based on my previous comment, [here](https://github.com/dwarakaprasad/filterreactive) is a sample gateway application with two entities (Customer & Address) implementing entity filtering, everything is supported except,

1. Distinct
2. Filtering by relationship on the non-owning side (this can be implemented but a bit involved)

All the tests (unit & e2e) have passed.

[Here](https://github.com/dwarakaprasad/filterreactive/commit/61e6864c671223f7d49d04b9ae1920226f70b550) are the list of files changed for this feature.

If you guys like this approach, i can build this feature into the generator.

**Comment by dwarakaprasad** [comment]
@smaestri @mraible @DanielFran, what do you guys think about this implementation, is it good enough for the generator.  I can make the ConditionBuilder more generic. Things that need you comments,

1. EntityCriteria moved into domain package (from seervice) - Currently the query is being built in EntityManager, which takes Condition as an input param. Conversion of entityCriteria to Condition needs access to Table (built inside repository), Column (built inside repository) & ColumnConverter (component available inside repository)
2. No filtering support on the non owning side -  This can be done but will need changes to the API
3. No '/count' rest service endpoint - There is no count method available in the R2dbc repository interface (similar to JpaSpecificationExecutor). I can create a facade method to return just the count, but I am not sure if that will have any performance impact.

**Comment by dwarakaprasad** [comment]
bug bounty claim [https://opencollective.com/generator-jhipster/expenses/160398](https://opencollective.com/generator-jhipster/expenses/160398)
