### ISSUE TITLE
Add Lighthouse to Cypress tests to identify performance regressions

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#14615]
##### **Overview of the feature request**

This looks really cool. I think we should investigate adding it to JHipster.

[Using Cypress and Google Lighthouse for Performance Testing](https://applitools.com/blog/using-cypress-google-lighthouse-performance-testing)

##### **Motivation for or Use Case**

It'd be nice to know if we've done things that cause worse performance, especially for PWAs.

##### **Related issues or PR**

None.

**Comment by atomfrede** [comment]
Looks really cool didn't know about the audit package.

**Comment by atomfrede** [comment]
@mraible I created an [example](https://github.com/atomfrede/jhipster-cypress-audit) and did some [test with ng and vue](https://atomfrede.gitlab.io/2021/04/automated-frontend-perfomance-test-with-lighthouse-for-jhipster/). I think adding it will be a good thing. I can go on and add it to the generator if we all agree.

**Comment by mraible** [comment]
@atomfrede Fantastic work! I'm +1 for adding it so we know when we hurt front-end performance.

**Comment by atomfrede** [comment]
Can you check what cpu slowdown factor you are using? The default lighthouse ci uses  4x slowdown resulting in "mid tier mobile" cpu power. As a consequence the angular performance rating is ~75 (vue has >90 with same slowdown)

**Comment by mraible** [comment]
Are you asking me this question @atomfrede? I'm not sure why you're asking as this issue has no test results.

**Comment by atomfrede** [comment]
Yes because I remember you showed usually >90 performance rating for angular.

**Comment by mraible** [comment]
I just created a new app with v7.0.1 and `jhipster jdl default`. Then, I made it a PWA using the instructions in the README and ran it with `./mvnw -Pprod`. Results:

<img width="767" alt="Screen Shot 2021-04-12 at 3 39 26 PM" src="https://user-images.githubusercontent.com/17892/114466160-51402700-9ba5-11eb-9263-7e7d529abdf8.png">

NOTE: I tried with `./mvnw -Pprod,tls`, but Chrome refuses to load `https://localhost:8080` when I do that.

Here's my runtime settings:

<img width="740" alt="Screen Shot 2021-04-12 at 3 39 42 PM" src="https://user-images.githubusercontent.com/17892/114466181-58ffcb80-9ba5-11eb-9175-bb3a47f28504.png">

I'll try with React and Vue and comment on this issue when I have results.

**Comment by atomfrede** [comment]
Thanks. Will try my sample with pwa. The 4x slowdown at least is the same but I have score of 75 using angular.

**Comment by mraible** [comment]
To create React and Vue apps, I ran `rm -rf *`, changed `clientFramework` to `react` (or `vue`) and ran JHipster again. Then I uncommented the service-worker code in `src/main/webapp/index.html` and ran it with `./mvnw -Pprod`. I made sure to test each app in a brand new incognito window.

React:

<img width="764" alt="React" src="https://user-images.githubusercontent.com/17892/114467148-b7797980-9ba6-11eb-9a75-665f0b106ebd.png">

Vue:

<img width="739" alt="Vue" src="https://user-images.githubusercontent.com/17892/114467716-91080e00-9ba7-11eb-827d-742bc1a7b890.png">

**Comment by mshima** [comment]
@mraible `jhipster jdl default --client-framework vue/react` =)

**Comment by atomfrede** [comment]
Keep it open
