### ISSUE TITLE
Unable to access API from CURL using Keycloack and Authorization Header

### ISSUE THREAD

**Issue by gabsone** [jhipster/generator-jhipster#14625]
##### **Overview of the issue**
Unable to access API from CURL using Keycloack and Authorization Header in microservices generated app:

Step 1: obtain token from keycloak with:

`curl -X POST 'http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token' \
 --header 'Content-Type: application/x-www-form-urlencoded' \
 --data-urlencode 'grant_type=password' \
 --data-urlencode 'client_id=web_app' \
 --data-urlencode 'client_secret=web_app' \
 --data-urlencode 'username=admin' \
 --data-urlencode 'password=admin'`

Step 2: invoke service on gateway using token through Authorization header:

`curl -i -X 'GET' \
  'http://localhost:8080/api/gateway/routes' \
  -H 'accept: */*' \
  -H 'Authentication: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI.....'
  `
 
The gateway return always:
`HTTP/1.1 401 Unauthorized
{
  "type" : "https://www.jhipster.tech/problem/problem-with-message",
  "title" : "Unauthorized",
  "status" : 401,
  "detail" : "Not Authenticated",
  "path" : "/api/gateway/routes",
  "message" : "error.http.401"
}`

##### **Motivation for or Use Case**
Accessing the API from a mobile or desktop app for a microservices generated using JHipster v7 and using Keycloack for Security

##### **Reproduce the error**
Generate a gateway App using JHipster Generator v7 and Select OAuth using Keycloak for security
Import in keycloak jhipster realm
Configure web_app client in keycloak with option "Direct Access Grants Enabled" enabled.
Generate a Token from curl (step1)
Access any protected API

##### **Related issues**
#9221

##### **JHipster Version(s)**
7.0.1

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/jhipster/app
`-- generator-jhipster@7.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "gateway",
    "baseName": "gateway",
    "jhipsterVersion": "7.0.1",
    "skipClient": true,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1617954955819,
    "serviceDiscoveryType": "eureka",
    "reactive": true,
    "authenticationType": "oauth2",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "mongodb",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "no",
    "enableTranslation": false,
    "nativeLanguage": "it",
    "packageFolder": "com/mycompany/myapp",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": true,
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

git version 2.25.1

node: v14.16.0

npm: 7.8.0

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Have you compared your options with the curl command line options that swagger-ui generates on gateway?

**Comment by gabsone** [comment]
Yes.
the "swagger-ui" suggests this command:
` curl -X 'GET' \
http://localhost:8080/api/gateway/routes' \
-H 'accept: */*' \
 -H 'X-XSRF-TOKEN: f525966b-d9bf-4b02-82a0-1166e35a9b90'
`
running it however does not work:
`{
  "type" : "https://www.jhipster.tech/problem/problem-with-message",
  "title" : "Unauthorized",
  "status" : 401,
  "detail" : "Not Authenticated",
  "path" : "/api/gateway/routes",
  "message" : "error.http.401"
}`

but in any case, how to obtain the X-XSRF-TOKEN token?

in my opinion the problem is due to the fact that the gateway only accepts cookies as authentication mode and does not read the Authorization or X-XSRF-TOKEN headers.

**Comment by gmarziou** [comment]
If it's the case, do you see something about it in gateway logs?

**Comment by gmarziou** [comment]
I'm surprised by what swagger-ui generated.

CSRF is disabled in SecurityConfiguration.
Anyway, what do you see in gateway logs? Have you tried increasing log level of "org.springframework.security" or using `@EnableWebSecurity(debug = true)`?

**Comment by gabsone** [comment]
> I'm surprised by what swagger-ui generated.
> 
> CSRF is disabled in SecurityConfiguration.
> 
> Anyway, what do you see in gateway logs? Have you tried increasing log level of "org.springframework.security" or using `@EnableWebSecurity(debug = true)`?

the v7 use @EnableWebFluxSecurity() and CSRF is enabled:
<pre>
  http
            .securityMatcher(new NegatedServerWebExchangeMatcher(new OrServerWebExchangeMatcher(
                pathMatchers("/app/**", "/i18n/**", "/content/**", "/swagger-ui/**", "/swagger-resources/**", "/v2/api-docs", "/v3/api-docs", "/test/**"),
                pathMatchers(HttpMethod.OPTIONS, "/**")
            )))
        .csrf()
                .csrfTokenRepository(CookieServerCsrfTokenRepository.withHttpOnlyFalse())
        .and()
            // See https://github.com/spring-projects/spring-security/issues/5766
            .addFilterAt(new CookieCsrfFilter(), SecurityWebFiltersOrder.REACTOR_CONTEXT)
            .addFilterAt(new SpaWebFilter(), SecurityWebFiltersOrder.AUTHENTICATION)
            .exceptionHandling()
                .accessDeniedHandler(problemSupport)
                .authenticationEntryPoint(problemSupport)
        .and()
            .headers()
                .contentSecurityPolicy("default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; font-src 'self' data:")
            .and()
                .referrerPolicy(ReferrerPolicyServerHttpHeadersWriter.ReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN)
            .and()
                .featurePolicy("geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'self'; payment 'none'")
            .and()
                .frameOptions().disable()
        .and()
            .authorizeExchange()
            .pathMatchers("/").permitAll()
            .pathMatchers("/*.*").permitAll()
            .pathMatchers("/api/auth-info").permitAll()
            .pathMatchers("/api/admin/**").hasAuthority(AuthoritiesConstants.ADMIN)
            .pathMatchers("/api/**").authenticated()
            .pathMatchers("/services/**").authenticated()
            .pathMatchers("/management/health").permitAll()
            .pathMatchers("/management/health/**").permitAll()
            .pathMatchers("/management/info").permitAll()
            .pathMatchers("/management/prometheus").permitAll()
            .pathMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN);

        http.oauth2Login()
            .and()
            .oauth2ResourceServer()
                .jwt()
                .jwtAuthenticationConverter(jwtAuthenticationConverter());
       http.oauth2Client();
        // @formatter:on
        return http.build();

</pre>


the logs says only this:
<pre>
2021-04-12 09:29:08.138  WARN 314 --- [oundedElastic-1] o.z.problem.spring.common.AdviceTraits   : Unauthorized: Not Authenticated
</pre>

**Comment by gmarziou** [comment]
OK, but have you tried to disable csrf to see if it has an impact and enabled more security logging?

**Comment by gabsone** [comment]
with CSRF disable ..... same result 
the logging config is:
<pre>
logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.mycompany.myapp: DEBUG
    org.springframework: DEBUG

</pre>

**Comment by gmarziou** [comment]
OK, so now you know that it's not related to CSRF

**Comment by mraible** [comment]
Make sure you're passing `openid`, `email`, and `profile` as scopes to get your token. I was able to make things work in https://github.com/jhipster/generator-jhipster/issues/14680, so I don't think this is a problem.
