### ISSUE TITLE
“From address must not be null” exception while registering

### ISSUE THREAD

**Issue by rroukens** [jhipster/generator-jhipster#1462]
The 'From' address used to send mails from is always null because the getProperty points to a non-existing Spring property in MailService.java.

After some debugging I found the solution. In the service MailService.java the 'From' address is retrieved by this code:

@PostConstruct
public void init() {
    this.from = env.getProperty("spring.mail.from");
}
However, the property "spring.mail.from" doesn't exist in application.yml. It should be "mail.from". So without the "spring" prefix.

Changing this to this code solved the problem for me:

@PostConstruct
public void init() {
    this.from = env.getProperty("mail.from");
}

**Comment by jdubois** [comment]
OK, this is my fault, and this is linked to #1216

@rroukens will you do a PR?
