### ISSUE TITLE
Document how to remove a language

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1467]
It's documented how to add a language but not how to remove a language. There are most probably many users that won't use the french language in their applications. Instead they use their native language and english.

**Comment by diego-torres** [comment]
Just did backwards to adding the language:
1. Remove the language folder from /src/main/webapp/i18/[remove-lang]
2. Remove the entry from src/main/webapp/components/language/language.service.js

**Comment by andidev** [comment]
Thanks, thats true. Though it should still be documented I think.

**Comment by jdubois** [comment]
Fixed by https://github.com/jhipster/jhipster.github.io/commit/25ef53d723022acb1313f92722c81d13ca6d070f
