### ISSUE TITLE
JWT Authentication broke with upgrade to 7.0.1

### ISSUE THREAD

**Issue by Simsal** [jhipster/generator-jhipster#14680]
##### **Overview of the issue**

Authorization with Authorization Header broke after upgrade to 7.0.1.
Before, I could access some parts of my api by sending the jwt token obtained from okta as authorization header against my backend.

##### **Motivation for or Use Case**

Sending a valid jwt token in authorization header prdouces following error in postman desktop:
Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: null", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"

##### **Reproduce the error**

I was able to reproduce the error by creating a new project with 7.0.1 and trying to access any entity via jwt token. Backend isn't able to decode the jwt

##### **Related issues**

Maybe related?
 #14625 

##### **JHipster Version(s)**

7.0.1

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.octolearn.octolearn",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "7.0.1",
    "applicationType": "monolith",
    "baseName": "octolearn",
    "packageName": "de.octolearn.octolearn",
    "packageFolder": "de/octolearn/octolearn",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1601751214138,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": ["de", "en"],
    "blueprints": [],
    "lastLiquibaseTimestamp": 1617454205000,
    "skipUserManagement": true,
    "withAdminUi": true,
    "skipClient": false,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "pages": [],
    "reactive": false,
    "entities": [
      "Impressum",
      "About"
    ]
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

git version 2.29.2.windows.2

node: v14.15.0

npm: 6.14.8

##### **Browsers and Operating System**

Win 10
Chrome 89.0.4389.128 
- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
What version were you using previously that worked? Can you please provide the contents of your `yo-rc.json` file so we can try to reproduce? Also, how are are you generating you access token?

**Comment by Simsal** [comment]
The currently working version is "jhipsterVersion": "6.10.3". my yo.rc.json is linked in the issue.
It is reproducible by generating a new jhipster monolith with one entity.

I am generating the token via following link generated via https://oidcdebugger.com/
http://*my-okta-domain*/oauth2/default/v1/authorize?client_id=*clientID*&redirect_uri=https%3A%2F%2Foidcdebugger.com%2Fdebug&scope=openid&response_type=token&response_mode=form_post&state=octolearn&nonce=zdt7tpbxdz

**Comment by mraible** [comment]
I used your `.yo-rc.json` to generate a new app, then configured it to use Okta using the Okta CLI:

```
okta apps create jhipster
source .okta.env
./mvnw
```

I confirmed I can log in and view admin screens.

To generate an access token, I modified my Okta app to use implicit flow, add `https://oidcdebugger.com/debug`, and then created one using oidcdebugger.com.

I set it in my terminal:

```
TOKEN=eyJraWQiOiJxMm5rZmtwUDRhMlJLV2REU2JfQ...
```

Then, tried to access the JHipster API with HTTPie.

```
http :8080/api/account "Authorization: Bearer $TOKEN"
```

It fails:

```
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Content-Length: 0
Content-Security-Policy: default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:
Date: Thu, 15 Apr 2021 00:25:53 GMT
Expires: 0
Feature-Policy: geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'self'; payment 'none'
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
Set-Cookie: XSRF-TOKEN=e3b6f87d-03ab-4ca4-b31c-e3cd1945438e; path=/
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
WWW-Authenticate: Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: null", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

Investigating now.

**Comment by mraible** [comment]
I just started my app in debug mode using the environment values from the generated `.okta.env` in IntelliJ. Now it works with the same access token.

```
$ http :8080/api/account "Authorization: Bearer $TOKEN"
{
    "activated": true,
    "authorities": [
        "ROLE_USER",
        "ROLE_ADMIN"
    ],
    "createdBy": null,
    "createdDate": "2021-04-15T00:35:10.767078Z",
    "email": "matt.raible+1@okta.com",
    "firstName": "Matt",
    "id": "00uaauofbP99lUlOe5d6",
    "imageUrl": null,
    "langKey": "de",
    "lastModifiedBy": null,
    "lastModifiedDate": "2021-04-15T00:35:10.767078Z",
    "lastName": "Raible",
    "login": "matt.raible+1@okta.com"
}
```

**Comment by mraible** [comment]
I can no longer reproduce this issue, so I'm going to close it. Please reopen if the steps I outlined above don't work for you.

**Comment by mraible** [comment]
Here are the settings I'm using in OIDC Debugger:

<img width="701" alt="Screen Shot 2021-04-14 at 6 44 54 PM" src="https://user-images.githubusercontent.com/17892/114798008-9f922900-9d51-11eb-9995-956671d14e8f.png">

**Comment by Simsal** [comment]
Thank you for your investigation!
I found that with 7.0.1 there is the scope parameter within the application.yml
and it seems like the scopes must match between the token generation and the expected oidc parameter.

With the older version openid as solo scope was enough.

```
security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://---/oauth2/default
        registration:
          oidc:
            client-id:---
            client-secret: ----
            scope: openid,profile,email
```

**Comment by mraible** [comment]
Yeah, this was a change in Spring Security brought about by Spring Boot 2.4. It used to default to these same scopes. Now you have to explicitly state them.
