### ISSUE TITLE
Using node-sass instead of the ruby sass

### ISSUE THREAD

**Issue by cjvaz** [jhipster/generator-jhipster#1469]
Using Docker I noticed that is missing ruby in the Dockerfile, I put line of the configuration in Dockerfile but I think interesting to use the node-sass, am I wrong?

**Comment by jdubois** [comment]
No we don't include it in the DockerFile: it's not a default option, and it adds a lot of stuff in the image.

So we won't add it by default -> there could be another DockerFile for this, but I will not do it at the moment, as less than 5% of users are actually using Compass according to our stats.

**Comment by gmarziou** [comment]
Docker or not, migrating to node-sass rather than current ruby-sass would remove dependency on ruby and also would drastically improve performance. I'll give it a try.

**Comment by jdubois** [comment]
Oh, OK, my main pain point is performance -> if you can use node-sass and that it's faster, please try it!!

**Comment by cjvaz** [comment]
This is what I think, remove the dependence of the ruby. But it would be nice to put in the installation documentation that the jhipster-docker does not support sass-compass.

**Comment by deepu105** [comment]
http://benfrain.com/lightning-fast-sass-compiling-with-libsass-node-sass-and-grunt-sass/

**Comment by gmarziou** [comment]
I did not play enough yet but I was pleased to see that node-sass installed cleanly on Windows.

**Comment by deepu105** [comment]
@gmarziou are you on this? else I can try this out, I have some time this week

**Comment by gmarziou** [comment]
I won't be bale to work until end of next week, so please go ahead.

**Comment by deepu105** [comment]
Ok, im on it

**Comment by deepu105** [comment]
Tried node-sass with gulp-sass plugin and it is much much faster than ruby-compass option, see below both configured on a JH project and ran on the same main.scss file

![image](https://cloud.githubusercontent.com/assets/1107223/7787178/3d02ba24-0230-11e5-8c17-5398cde105e5.png)

@jdubois what do you think?
can we have it as an option during generator, So instead of asking `do you want to use compass for css` can we ask `do you want to use sass for css` and present `No`, `yes, with compass`, `yes, with node-sass` as options

Ill try with grunt as well

**Comment by deepu105** [comment]
here is the output for grunt with grunt-sass plugin

![image](https://cloud.githubusercontent.com/assets/1107223/7787322/68d5d318-0238-11e5-9746-bf1ade4bbc8a.png)

Overall the performance gain is huge if we are talking only in seconds

**Comment by jdubois** [comment]
@deepu105 I don't use Compass, so I'm not sure -> does it work exactly the same way?
If so, and as it's clear that performance is better, I'd rather have just node-sass -> let's not have too many options, just the best ones. Otherwise we can't maintain everything, and it confuses users.
If does the same thing, can you create a new issue? As this one was originally on Docker, even if the title is misleading

**Comment by deepu105** [comment]
Ok, ill create a new issue. But my thought behind having option was to support existing users who use compass.
the behavior is exactly same for the scss file JH has, I compared generated output file fromcompass and node sass, its exactly same except for some alignments and formatting. But node-sass doesn't yet support some of the proprietary compass mixins & features like sprite generation etc. Though the scss file that JH shipps with has not used any of compass specific features, there might be some users who have customized it to use those. So are you sure that we can drop compass in that case?

**Comment by jdubois** [comment]
@deepu105 OK so it's not exactly the same, so that means we should support both.... I'm not using it, and my stats show that less than 5% of users are using Compass, is that really worth the effort and the maintenance cost? Is your code big & hard to maintain?

**Comment by deepu105** [comment]
@jdubois 
if we can tell that in a release note then we can remove compass and ask compass users to refer a  tip file to continue using compass (Here we can give instruction to setup compass)

Changes for this will be in Gruntfile.js, gulp.js (around 10 lines in each), then dependency include in package.json, and the changes required in app.js to change the question (and around 11 reference to useCompass variable)

**Comment by deepu105** [comment]
@jdubois  So let me know if I should go ahead and do the PR or drop it!

**Comment by gmarziou** [comment]
I use SASS with jhipster and dropping Compass in favor of node-sass is just simplifying and improving dev environment. The only reason to keep Compass would be due to some syntax not supported yet by libsass but Bootstrap-sass usually fixes any compatibility issue.

**Comment by deepu105** [comment]
Ya i agree on the simplicity part

**Comment by deepu105** [comment]
Also im glad that JH scss files are just plain scss and not using any compass specific mixins, why would anyone want to lock in with a specific vendor syntax, when i compiled the bootstrap scss files with both compass and node sass the output where same except for some formatting changes

**Comment by gmarziou** [comment]
@deepu105 do you have a repo where i could have a look? I'm starting doing it on my project.

**Comment by deepu105** [comment]
haven't commited anything to JH code yet,as I tried it out on a generated project. was waiting for go ahead from @jdubois to add it in JH.  If its ok with you I can check in those changed files and share it to you, let me know what you need, grunt or gulp

**Comment by gmarziou** [comment]
a generated project with grunt would be fine for me

**Comment by deepu105** [comment]
ok will share, gimme a while

**Comment by deepu105** [comment]
I guess i'll put it here. did a diff, changes are just few, I did a simple config

1. src/scss/main.scss (correct the bower import path as below)
----------------------
```
// bower:scss
@import "bootstrap-sass/assets/stylesheets/_bootstrap.scss";
// endbower
```
2. add the below task to gruntfile.js instead of compass task
--------------------
```
sass: {
            options: {
                sourceMap: false
            },
            dist: {
                files: {
                    'src/main/webapp/assets/styles/main.css': 'src/main/scss/main.scss'
                }
            }
        },
```
add sass task to watch instead of compass

```
sass: {
                files: ['src/main/scss/**/*.{scss,sass}'],
                tasks: ['sass']
            },
```
swap compass tasks in concurrent
```
concurrent: {
            server: [
                'sass'
            ],
            test: [
                'sass'
            ],
            dist: [
                'sass',
                'imagemin',
                'svgmin'
            ]
        },
```
2. `"grunt-sass": "^1.0.0"` to package.json instead of `grunt-contrib-compass`
---------------------

Changes for gulp is also very similar, guess I'll do a PR if there is interest in merging, as i dont wanna waste time on this. I dont use sass anyways, happy with less :smile:

**Comment by gmarziou** [comment]
Thanks, I am currently struggling with incompatible version of lodash between the one used by yo and the one used by grunt-sass

**Comment by gmarziou** [comment]
OK, it's working now

I have slightly different options than yours but I'm not sure which one is totally required.
I think sourceMap should be true for debugging.

~~~~
            options: {
                includePaths: [
                    'src/main/webapp/bower_components'
                ]
            },
            dist: {
                files: [{
                    expand: true,
                    cwd: 'src/main/scss',
                    src: ['*.scss'],
                    dest: 'src/main/webapp/assets/styles',
                    ext: '.css'
                }]
            },
            server: {
                files: [{
                    expand: true,
                    cwd: 'src/main/scss',
                    src: ['*.scss'],
                    dest: 'src/main/webapp/assets/styles',
                    ext: '.css'
                }]
            }
        },
~~~~

**Comment by deepu105** [comment]
@gmarziou ya this looks better. but both dist and server is the same in your config rite?is that useful? also did includepath work for you? without altering the imports path in scss?

**Comment by gmarziou** [comment]
Yes the imports path has to be altered but it was the same with compass as I documented it here:

http://jhipster.github.io/customizing_bootstrap.html

**Comment by Emeegeemee** [comment]
I'm trying to completely remove my dependency on bootstrap and instead use bootstrap-sass. How did you guys go about getting the fonts from the sass version instead of the bootstrap? Or did you keep both dependencies?

**Comment by gmarziou** [comment]
When you generate your app with SASS option, first line of main*;scss is:

~~~
$icon-font-path: "../../bower_components/bootstrap-sass/assets/fonts/bootstrap/";
~~~

it works for me

**Comment by Emeegeemee** [comment]
Thank you very much I was trying to add node-sass to a project that was generated without compass so I didn't think to look at what was in the templates main.scss

**Comment by gmarziou** [comment]
Just wanted to mention that I got this running on 2 Windows machines and one RedHat without problem.
I may try to run it on OSX too.
