### ISSUE TITLE
BrowserSync with templates of the angular

### ISSUE THREAD

**Issue by cjvaz** [jhipster/generator-jhipster#1470]
Using BrowserSync when updating a template nothing happens, insert the setting 
browserSync: { ...
                        'src/main/webapp/scripts/**/*.html',
... the display is synchronized.

**Comment by jdubois** [comment]
I can't reproduce your issue.

We already have ```'src/main/webapp/**/*.html'``` so no need to add /scripts/.

**Comment by FaustVs** [comment]
Apologies - not sure of the etiquette on commenting on a closed issue. 

I can confirm that I also have this issue,  and the fix proposed by cjvaz resolves it. I'm a Windows user, and would be interested to know if cjvaz is also?

**Comment by jdubois** [comment]
@FaustVs no etiquette here :-)
But I don't look at closed issue a lot, so you have more chances to have your comment lost!

I can't understand why you have this issue -> if it's related to Windows, so could be a good point (I'm on MacOS)

**Comment by cjvaz** [comment]
I'm a Linux user and issue persist.

**Comment by bbbenja** [comment]
+1 on Windows, html templates are not watched. It works well with index.html file, and controller files.

**Comment by jdubois** [comment]
I'm just having it working with my main.html file -> can you test this one also? I don't understand how this happens.
Or maybe send me a screencast of what you do?

**Comment by FaustVs** [comment]
Hi @jdubois - I've emailed you a quick screencast of this issue to the email address mentioned on your personal website. Please let me know if you have any queries, or would like further information.

Many thanks

**Comment by jdubois** [comment]
Thanks @FaustVs : I see your error, and I agree everything should be working.
I just upgraded to the latest BrowserSync version, and I still don't have the issue (doing exactly the same thing as you) -> can try it again when the next version is released? Or can you test from the "master" branch?

**Comment by FaustVs** [comment]
No worries @jdubois - I'll certainly try again when the next version is released, and will have a look at testing from master branch in the meantime.

To make you aware - I've been doing a bit more testing on this issue to try and isolate the problem. I don't thinks its necessarily a 'JHipster' problem, and may potentially be a BrowserSync one.

I took one of the sample BrowserSync projects from Github, and copied a generated JHipster webapp into it. Under that setup, live re-loading doesn't work either.

However, if you either remove the browserSync configuration to watch the `'src/main/webapp/scripts/**/*.js'` folder or if you 'widen' it to watch `'src/main/webapp/**/*.js'` (remove the scripts folder), live reloading starts working again.

As such, it seems adding a watch on `'[...]/scripts/**/*.js'` overrides or blocks the watching of the .html files in the scripts folder specified on the wildcard search of `'src/main/webapp/**/*.html'`.

I'd be interested in thoughts on the above. I'm happy to create a PR that would probably fix the issue for us poor Windows (and Linux? in @cjvaz case) users. Or is this potentially something to raise as a bug for BrowserSync or its Grunt plugin?

**Comment by jdubois** [comment]
@FaustVs if it fixes the issue for Windows users, and if it doesn't have any effect on performance (this is why I tried to have only a subdirectory), then yes, can you send a PR?
