### ISSUE TITLE
Sonarqube Security Hotspot for mixed content on generated home page

### ISSUE THREAD

**Issue by josephshannon** [jhipster/generator-jhipster#14735]
##### **Overview of the issue**

The generated home page using the React generator uses http:// over https:// for the link to the JHipster stackoverflow tag

##### **Motivation for or Use Case**

Mixed content (i.e. both http:// and https://) is being reported as a security hotspot in my customer's SonarQube analysis

##### **Reproduce the error**

Running an app generated with the current JHipster React generator against the latest Sonarqube Docker image, rather than using the JHipster-configured Sonarqube, will produce the below security hotspot in its analysis
<img width="1298" alt="jhipster-sonarqube" src="https://user-images.githubusercontent.com/23630152/115490982-1edd9c00-a22d-11eb-9ef2-b56585b853b3.png">

##### **Related issues**

None

##### **Suggest a Fix**

I will submit a PR with all references to the Stackoverflow tag changed from http to https

##### **JHipster Version(s)**

6.10.5

##### **JHipster Version(s)**

```
test@0.0.1-SNAPSHOT /Users/josephshannon/test
└── generator-jhipster@6.10.5 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1618974787841,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.23.0

node: v14.15.5

npm: 6.14.11

yeoman: 3.1.1

yarn: 1.22.4

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build c4eb3a1f

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

Browser: NA; Mac OSX 11.2.3 (20D91)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by josephshannon** [comment]
Do I need to be added as a contributor to submit a PR? I get this when trying to push my branch:

```
$ git push origin sonarqube-homepage-security-finding
ERROR: Permission to jhipster/generator-jhipster.git denied to josephshannon.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by mraible** [comment]
You should be able to fork the repo and push to your fork to create a PR.

**Comment by josephshannon** [comment]
> You should be able to fork the repo and push to your fork to create a PR.

Done. Thank you, sir.
