### ISSUE TITLE
Jhipster 7.0.1 and couchbase 7

### ISSUE THREAD

**Issue by blackxMan** [jhipster/generator-jhipster#14745]
Hello,
is there any chance to support couchbase 7 with scopes & collections feature.
thank you

**Comment by mraible** [comment]
If you're willing to do the work, we'd love to have Couchbase support! We dropped it from JHipster 7 because we found Spring Data's support wasn't that great with Spring Boot 2.3 and 2.4.

https://github.com/jhipster/generator-jhipster/pull/14184

**Comment by blackxMan** [comment]
hey @mraible,
Thanks for answer, i think they fix all problem in the new version Spring Data Couchbase 4.0  based on couchbase sdk 3

**Comment by mraible** [comment]
@blackxMan If you'd like to see Couchbase support re-added, you're more than welcome to fork my repo and contribute to the `fix-couchbase` branch. I've spent too many hours on it that I'm no longer interested in working on it.

**Comment by murdos** [comment]
> i think they fix all problem in the new version Spring Data Couchbase 4.0 based on couchbase sdk 3

On the contrary, things go broken since Spring Data Couchbase 4.0 release.
I also spent too many hours trying to fix it.

**Comment by coderguy-tech** [comment]
Hey,
I'm working on this right now: 
1. Updating JHipster codebase to use the new version of Spring Data Couchbase 4 based on Couchbase SDK 3
2. Re-wiring some of the older code (wherever CB related database code is) to ensure that it works with Spring Data and Couchbase SDK API calls. 
3. Running through the test suites of JHipster to ensure that they pass — as we hit failures in the tests, we are resolving these issues as we go along

If I need help or get stuck along the way, will reach out.
Thanks

**Comment by DanielFran** [comment]
@coderguy-tech dear not forget #14184, you can continue based on that...

**Comment by coderguy-tech** [comment]
Thanks, I'll take a look at that

**Comment by gkysaad** [comment]
As I was working on the fix I came across an issue with the Couchmove implementation. Couchbase's SearchIndex class' `toJson()` function does not output all of the custom data used to create a SearchIndex object, resulting in FTS indices not being created properly with all the required data in the database. So, I've created a custom SearchIndex class and created a PR in the couchmove repo to fix this bug there: https://github.com/differentway/couchmove/pull/13.

**Comment by DanielFran** [comment]
@gkysaad I merged on BOM the update to couchmove 3.1.1

@gkysaad @coderguy-tech Fille free to continue the work started on couchbase migration for spring-boot 2+ in #14184

**Comment by gkysaad** [comment]
Thanks @DanielFran! I've been working based on the branch in https://github.com/jhipster/generator-jhipster/pull/14184 but I'm working off a new branch that's rebased with jhipster:main as the changes on that branch were way behind the latest code and thus led to too many merge conflicts when I tried to rebase.

**Comment by gkysaad** [comment]
I've created a PR with my fixes and implementation for Spring Data Couchbase 4.
