### ISSUE TITLE
Openshift generator pre_build hook Maven broken URL

### ISSUE THREAD

**Issue by dhaalves** [jhipster/generator-jhipster#1475]
Broken url is: http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.2.3/binaries/apache-maven-3.2.3-bin.tar.gz

**Comment by jdubois** [comment]
Thanks @dhaalves ! This is indeed quite outdated, I'm upgrading everything.

**Comment by jdubois** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/commit/2009e4b73b5e2f7c2d5ede6fc499e400c904db94
