### ISSUE TITLE
Keycloak.X distribution (Quarkus) - less memory consumption

### ISSUE THREAD

**Issue by JeroenAdam** [jhipster/generator-jhipster#14765]
#### **Overview of the feature request**

Keycloak is basically a Java application and has been released now as well using the Quarkus framework.
I tested it and the latest version 12.0.4 is working fine with less memory consumption.
See the official [release announcement](https://www.keycloak.org/2020/12/first-keycloak-x-release.adoc).

#### **Motivation**

Less memory consumption and faster startup time.

#### **How I did it:**

docker run -d --restart=always --name keycloak-test -p 9080:8080 \
    -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin \
    quay.io/keycloak/keycloak-x:12.0.4 \
    --db-username=keycloak --db-password=change_me --proxy=edge
    
(the proxy parameter because I'm behind Apache)

Some manual config:
 * attention: the issuer-uri (Jhipster application.yml) may not have the /auth in its path: https://www.example.com/realms/jhipster 
(/auth has been dropped). Quote from [documentation](https://github.com/keycloak/keycloak-community/blob/master/design/keycloak.x/configuration.md): "Keycloak.X should use / as the context root path. There is no need to keep the /auth context path currently used by the Wildfly distribution."
 * import jhipster-realm.json and jhipster-users-0.json manually using UI (Jhipster generated realm-config folder)
 * import realm-export.json using UI which I generated from another v12.0.4 instance (Java distribution) launched from Jhipster generated keycloak.yml
 * manually added Client scope 'jhipster' and its 3 Token mappers langKey, login and roles
 * manually selected both Realm Roles offline_acces and uma_authorization as Realm Default Roles

#### **It works!**

It works fine with my generated v7.0.1 monolith application but many annoying warnings appear in the logs eg. when hitting endpoints:

2021-04-24 10:55:44.916  WARN 1 --- [  XNIO-1 task-1] o.z.problem.spring.common.AdviceTraits   : Unauthorized: Full authentication is required to access this resource
2021-04-24 11:04:55.973  WARN 1 --- [  XNIO-1 task-1] o.z.problem.spring.common.AdviceTraits   : Unauthorized: Full authentication is required to access this resource
2021-04-24 11:04:55.984  WARN 1 --- [  XNIO-1 task-4] o.z.problem.spring.common.AdviceTraits   : Unauthorized: Full authentication is required to access this resource

![image](https://user-images.githubusercontent.com/16437621/115957413-9bf56380-a502-11eb-80fd-6d9aa502c455.png)

**Comment by vishal423** [comment]
As `Keycloak.X` is a preview distribution, I would rather wait for a stable release to integrate with `JHipster` as default.

**Comment by DanielFran** [comment]
Closed in favour of https://github.com/jhipster/generator-jhipster/issues/17850
