### ISSUE TITLE
Facing issue to dockerize jhipster client and server separate image, as Docker folder is missing in Jhipster Angular project 

### ISSUE THREAD

**Issue by RtzS** [jhipster/generator-jhipster#14762]
HI All,

Jhipster version7.0.1

I am trying to create separate image for client and server application. Created separate client and server layer using 'Jhipster --skip-client/ --skip-server'. 
But observed that docker folder is not generated in client application. So I am not able to create separate docker image of client.

Can any one please help me here.
Thankyou in anvance.

**Comment by gmarziou** [comment]
Please don't crosspost with Stackoverflow: https://stackoverflow.com/questions/67224788/how-to-dockerize-jhipster-monolothic-angular-application-as-docker-folder-is-mis

Have you read the docs? It uses jib from maven or gradle. https://www.jhipster.tech/docker-compose/#-building-and-running-a-docker-image-of-your-application
