### ISSUE TITLE
401 Unautherized when doing password reset

### ISSUE THREAD

**Issue by rroukens** [jhipster/generator-jhipster#1478]
When starting the password reset procedure I got a 401 Unauthorized error in API: http://localhost:8080//api/account/reset_password/init

After some debugging I solved it by adding these two lines in method configure of class SecurityConfiguration to web.ignoring().
            .antMatchers("/api/account/reset_password/init")
            .antMatchers("/api/account/reset_password/finish"):

The full method is now:

    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
            .antMatchers("/scripts/**/*.{js,html}")
            .antMatchers("/bower_components/**")
            .antMatchers("/i18n/**")
            .antMatchers("/assets/**")
            .antMatchers("/swagger-ui/**")
            .antMatchers("/api/register")
            .antMatchers("/api/activate")
            .antMatchers("/api/account/reset_password/init")
            .antMatchers("/api/account/reset_password/finish")
            .antMatchers("/test/**");
    }

Is this the correct way to fix it?

**Comment by atomfrede** [comment]
Which kind of authentication qre you using? oauth?

**Comment by rroukens** [comment]
Yes, I'm using oauth.
