### ISSUE TITLE
Align yeoman generator lifecycle

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#14798]
##### **Overview of the feature request**

Hi Ladies and gents :-),

I'm currently thinking on aligning the different generators steps in a 'one size fits all' way: most of them are already on that pattern, but wanted to be sure of the lines I'm moving.

What do you think about this description?

1. Initializing (can be split into the steps below)
- Loading constants
- Reading the essential properties from .yo-rc or current entity (microservice or gateway)
- Loading default configuration (for example microservice server)
- Saying hello

2. Loading configuration
- Reading yo.rc & entity data depending on the generator context

3. Prompting
- End user prompt

4. Configuring
- Save configuration
- Setting up some capabilities (e.g. create some cloud resources)

5. Composing
- Composing generators

6. Loading
- Querying platforms (e.g. azure) to retrieve some more conf

7. Preparing
- Derived properties for platform and servers and entities

8. Preparing fields
- Derived properties for fields

9. Preparing relationships
- Derived properties for relationships

10. Default
- I don't know what to do here, but can help

11. Writing
- Write the template

12. Post writing
- Hooks for templates

13. Install
- Post actions (ex: setup git repo)
- Push app to platform

14. End
- Thanks Messages, reports (warning)

Are you OK with this? Does it covers every cases?

##### **Motivation for or Use Case**

Aligning the lifecycle among generator will avoid race condition and help generator maintenance.

Not really OK with that lifecycle? Copy paste it and propose your alternative!

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
You can see my initial proposal here https://github.com/jhipster/generator-jhipster/issues/12338.

- 1
  - 1. May be postponed to 6, not sure.
  - 2. See bellow at priority 2.
  - 3. Loading default configuration needs clarification like priority 2.
- 2 should not exist.
  - Reading yo.rc depending on the generator context:
    - Should be done in step 1 when the configuration needs to be already final (entity*, deployments).
    - Should be done in step 6 when the configuration needs to be synchronized (common, server, client, languages).
Eg: server prompt config won't be ready at priority 2 for common/client/languages, so it must be loaded after saving in configuring step.
  - Entity data depending on the generator context:
    - Like above but for the entities json, very important for blueprints.
Blueprint may save the config at configuring step.
- 4
  - 2. I don't know what you mean about `Setting up some capabilities (e.g. create some cloud resources)` but seems to be best placed at install priority

Priority 6 must consider it's own data as inexistent and load everything.
