### ISSUE TITLE
Upgrade Ionic for JHipster to JHipster 7

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#14800]
##### **Overview of the feature request**

This is a proxy issue to get https://github.com/oktadeveloper/generator-jhipster-ionic/pull/482 across the finish line. I'm unsure of how to proceed. 

##### **Motivation for or Use Case**

It'd be nice if Ionic for JHipster could be used with JHipster 7.

**Comment by mshima** [comment]
On it.

**Comment by mraible** [comment]
Thanks for all your help with this upgrade @mshima! Please claim your well-deserved bounty. 🙏

**Comment by DanielFran** [comment]
@mshima Can request the bounty to close this issue?

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/41787.

**Comment by pascalgrimaud** [comment]
@mshima : approved

**Comment by mshima** [comment]
Thanks.
