### ISSUE TITLE
Strange blueprint generator-jhipster-yob in market place

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#14813]
##### **Overview of the issue**

Looking at a [stackoverflow question](https://stackoverflow.com/questions/67278791/gererating-the-entity-from-existing-microservice-application-using-jhipster) I noticed generator-jhipster-yob blueprint which I did not know.

On npm, https://www.npmjs.com/package/generator-jhipster-yob shows a default generated blueprint with wrong github repo: https://github.com/mygitname/generator-jhipster-yob

```json
  "author": {
    "name": "mygitfirstname mygitlastname",
    "email": "mygitemail",
    "url": "mygiturl"
  },
  "bugs": {
    "url": "https://github.com/mygitname/generator-jhipster-yob/issues"
  },
```

However, the page mentions a github user @alankarapte as the author.

I don't necessarily think it's malicious intent, it could be someone who made an experimental blueprint and forgot to cleanup on npm.

BUT I think the JHipster market place should not present blueprints where the git repo is not visible.

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
We can add it to the blocked list in website

**Comment by gmarziou** [comment]
Thanks @deepu105 I did not know this mechanism

**Comment by alankarapte** [comment]
This is experimental blueprint which I created. please give me a way by
which I can use it personally without publishing on npm registry.

**Comment by gmarziou** [comment]
You can still use it from npm registry, it's just no longer visible on market place. 
If it's experimental, why not saying so in your README so that it's visible in npm registry?

Also you don't need npm registry to use it personally, just use `npm link`.

**Comment by deepu105** [comment]
You can use `npm link` command to install it locally to use and don't have to publish it. Also what we did doesn't affect you using it only hides it in our marketplace. If you end up finishing it and want to be listed in marketplace just let us know and we will revert this
