### ISSUE TITLE
Deployment JDL doesn't offer all Kubernetes options

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#14817]
##### **Overview of the issue**

If I run `jhipster k8s` and answer the questions as follows:

```
$ jhipster k8s
microservices
../
select all
No to prometheus
clustered? Yes
Admin password? admin
namespace? default
repo name? gcr.io/wise-name-333
docker push
Enable Istio? No 
service type?
LoadBalancer
dynamic storage? Yes
a specific storage? empty
```

... it'll generate a `.yo-rc.json` that looks like this:

```json
{
  "generator-jhipster": {
    "appsFolders": ["blog", "gateway", "store"],
    "directoryPath": "../",
    "clusteredDbApps": ["store"],
    "serviceDiscoveryType": "eureka",
    "jwtSecretKey": "ODAwNjk0MTViNTllYzAxNjZjNjE5MmE2NjZjMjMwYzdmZTZjNjkyMGQzN2Q3YWEwZWQzZTg2OTdhNzQ3N2QxNmM2ZDJiODFhZmM5N2Y4NmFjODBmOTUzOWRkNjBiMDAwMmFmZQ==",
    "dockerRepositoryName": "gcr.io/jhipster7",
    "dockerPushCommand": "docker push",
    "kubernetesNamespace": "default",
    "kubernetesServiceType": "LoadBalancer",
    "kubernetesUseDynamicStorage": true,
    "kubernetesStorageClassName": "",
    "ingressDomain": "",
    "monitoring": "no",
    "istio": false
  }
}
```

However, it doesn't seem that [our deployment JDL](https://www.jhipster.tech/jdl/deployments) supports the dynamic storage or storage class name options for k8s. The following seems to get close, but doesn't produce the same `.yo-rc.json`.

```
deployment {
  deploymentType kubernetes
  appsFolders [gateway, blog, store]
  clusteredDbApps [store]
  dockerRepositoryName "gcr.io/jhipster7"
}
```

Related: does there need to be a `jwtSecretKey` for OAuth apps?

##### **Motivation for or Use Case**

It'd be nice to create the same configuration with JDL that you can with `jhipster k8s`.

##### **JHipster Version(s)**

7.0.1

**Comment by MathieuAA** [comment]
Seems like the deployment part is not up to date with the recent changes...
We should really think about creating a DoD (definition of done).

I have one hour this morning, I'm gonna investigate

**Comment by MathieuAA** [comment]
I can confirm the deployment part is really out of date.
Fixing this issue requires a refactoring (splitting by deployment type like k8s, openshift, etc.) and the actual fix.
