### ISSUE TITLE
Firefox URL mangled when using browser sync

### ISSUE THREAD

**Issue by verrol** [jhipster/generator-jhipster#1483]
This doesn't happen if you use Firefox or Chrome alone. But if both Firefox and Chrome are oped at the same time. The Firefox URL will get manged after creating a record.

How to reproduce:
1. Created a new jHipster app
2. Added an entity
3. Use Firefox to add a record
4. Open Chrome, log in using the same account.
5. Firefox URL now looks like GET request with all the entity fields as request params.

**Comment by jdubois** [comment]
OK, but this is a BrowserSync issue, we can't do anything about this.
Can you open up a ticket at BrowerSync, and link it here?
