### ISSUE TITLE
useJPADerivedIdentifier deprecated, jdl 

### ISSUE THREAD

**Issue by Tenshock** [jhipster/generator-jhipster#14841]
##### **Overview of the issue**

I tried to generate some entities and relationships with jdl. Apparently, the option `with jpaDerivedIdentifier` for the OneToOne relationship is deprecated and make the generation to crash.

##### **Motivation for or Use Case**

I want to optimise the OneToOne relationships.

##### **Reproduce the error**

1. Generate an empty project
2. apply the jdl

##### **Related issues**

Not found

##### **Suggest a Fix**

The only thing I can add is the crash logs:

  <details>
  <summary>Crash logs</summary>
  <pre>
ERROR! /Users/user1/repo/enterprise/my-app/node_modules/generator-jhipster/generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs:1398
    1396|     void putNonExisting<%= entityClass %>() throws Exception {
    1397|         int databaseSizeBeforeUpdate = <%= entityInstance %>Repository.findAll()<%= callListBlock %>.size();
 >> 1398|         <%= persistInstance %>.set<%= primaryKey.nameCapitalized %>(<%= getJavaValueGeneratorForType(primaryKey.type) %>);
    1399|
    1400| <%_ if (dto === 'mapstruct') { _%>
    1401|         // Create the <%= entityClass %>

Java type OpeningHoursId does not have a random generator implemented
  </pre>
  </details>

##### **JHipster Version(s)**

7.0.1

##### **JHipster Version(s)**

```
myproject@0.0.1-SNAPSHOT /Users/user1/repo/enterprise/my-app
└── generator-jhipster@7.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "myapp",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1618579945229,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.myapp.sub",
    "serverPort": "8080",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "cosmo",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "packageFolder": "com/myapp/sub",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "languages": ["fr", "en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v14.16.1

npm: 6.14.12

Docker version 20.10.5, build 55c4c88

docker-compose version 1.29.0, build 07737305

No change to package.json was detected. No package manager install will be executed.

<details>
<summary>JDL definitions</summary>
<pre>
entity OpeningHours {
    day String
}

entity DayTime {
    hour Integer min(0) max(23)
    minute Integer min(0) max(59)
}

relationship OneToOne {
    OpeningHours{startPeriod} to DayTime with jpaDerivedIdentifier
    OpeningHours{endPeriod} to DayTime with jpaDerivedIdentifier
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

The entities files are not generated because of the error

##### **Browsers and Operating System**

macOS Big Sur 11.2

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Commenting, this is weird

**Comment by pmverma** [comment]
@Tenshock ,
I believe the new way to provide the option in JDL is as following.
```
@ChangelogDate(20200804040000)
entity UserMapsId {
}

relationship OneToOne {
  UserMapsId to @Id User
}
```

I have picked it from https://github.com/jhipster/generator-jhipster/blob/main/test-integration/samples/jdl-entities/user-relationships/entities.jdl

I think docs has not been updated.

**Comment by pmverma** [comment]
@mshima, Can you please confirm this? I can update the doc to be in sync.

**Comment by mshima** [comment]
@pmverma yes, but jpaDerivedIdentifier should work too. It should convert internally.

**Comment by mshima** [comment]
Anyway the jdl doesn’t look correct to me.
We don’t support multiple ids, so 2 id relationships at the same relationship isn’t supported.

**Comment by pmverma** [comment]
@Tenshock Can you please correct your jdl and retry it?

**Comment by Walk-Code** [comment]
how to fix Java type Integer does not have a random generator implemented?

**Comment by muhannadalhariri** [comment]
> how to fix Java type Integer does not have a random generator implemented?

I have tried the field type with Long and it worked like a charm
