### ISSUE TITLE
StackOverflowError with multiple entity relations when elastic is enabled 

### ISSUE THREAD

**Issue by Guzzi** [jhipster/generator-jhipster#14840]
##### **Overview of the issue**
PUT requests on certain entities fail if multiple relations are defined in JDL file and elastic is enabled. Same request is successful when elastic is disabled. 

##### **Motivation for or Use Case**
Using elastic for search indices while having multiple entity relations and being able to use the rest calls for storing entity changes without stackoverflow errors.

##### **Reproduce the error**
- create jHipster project with "jhipster import-jdl test.jh" with below attached JDL file (see "JDL definitions")
- start project with "mvnw"
- open gui and login
- select entity - "area"
- edit any of the fake data entries
- click on "save"
- error is thrown (stackoverflow error in log)

When setting "searchengine false" is chosen in the JDL (rebuilding and testing as above), the entity can be saved without error.

##### **Related issues**
haven't found any.

##### **Suggest a Fix**
no idea - but we found, that when we separate the calls to save entity in db and save elastic via two separated transactions, it seems to work. However, this then breaks the transaction concept if the elastic save fails.

##### **JHipster Version(s)**
current -> 7.0.1 (but 6.10.5 had the same issue) 

##### **JHipster configuration**

jhipster info:

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "clientFramework": "angularX",
    "serverPort": "8081",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": true,
    "baseName": "location",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "de", "fr"],
    "messageBroker": false,
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "nativeLanguage": "en",
    "jhipsterVersion": "7.0.1",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "entities": ["Customer", "Area", "AreaType"],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1619540342657,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "lastLiquibaseTimestamp": 1619540522000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Customer {
  name String required unique
}
entity Area {
  name String required
  description String
}
entity AreaType {
  name String required unique
}
relationship OneToMany {
  AreaType{customerDefaultAreaType(name)} to Customer{defaultAreaType(name) required}
  AreaType{area(name)} to Area{areaType(name) required}
}
relationship ManyToMany {
  Customer{allAreaTypes(name)} to AreaType{customerAllAreaType(name)}
}

dto Customer, Area, AreaType with mapstruct
paginate Customer, Area, AreaType with infinite-scroll
service Customer, Area, AreaType with serviceClass
filter Customer, Area, AreaType

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

git version 2.23.0.windows.1

node: v14.16.0

npm: 6.14.11

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.27.4, build 40524192

If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
     application {
  config {
    baseName location
    serverPort 8081
    applicationType monolith
    packageName com.test
    authenticationType jwt
    prodDatabaseType mariadb
    devDatabaseType h2Memory
    buildTool maven
    searchEngine elasticsearch
    //searchEngine false
    enableHibernateCache true
    cacheProvider hazelcast
    enableTranslation true
    nativeLanguage          en
    languages      [en, de, fr]
    serviceDiscoveryType false
  }
  entities *
}

entity Customer{
    name String required unique
}

entity Area{
    name String required
    description String
}

entity AreaType{
    name String required unique
}

relationship ManyToOne{
                Area{areaType(name) required} to AreaType{area(name)}
}
relationship ManyToMany{
                Customer{allAreaTypes(name)} to AreaType{customerAllAreaType(name)}
}
relationship ManyToOne{
                Customer{defaultAreaType(name) required} to AreaType{customerDefaultAreaType(name)}
}

paginate * with infinite-scroll
filter * 
service * with serviceClass
dto * with mapstruct

  </pre>
  </details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Entity that is having issues with PUT request is "Area":
<details>
<summary>Area.json file</summary>
<pre>
{
  "name": "Area",
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "description",
      "fieldType": "String"
    }
  ],
  "relationships": [
    {
      "relationshipType": "many-to-one",
      "otherEntityName": "areaType",
      "otherEntityRelationshipName": "area",
      "relationshipValidateRules": "required",
      "relationshipName": "areaType",
      "otherEntityField": "name"
    }
  ],
  "entityTableName": "area",
  "dto": "mapstruct",
  "pagination": "infinite-scroll",
  "service": "serviceClass",
  "jpaMetamodelFiltering": true,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "applications": ["location"],
  "changelogDate": "20210427162102"
}
  </pre>
  </details>

##### **Browsers and Operating System**
Win10 with latest Patches, latest Chrome Browser

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by vitoraasouza** [comment]
I have noticed that this happens only when ElasticSearch repository class tries to save the result of the entity repository. For instance, this is an automatic generated method by JHipster:
```java
public MyEntity save(MyEntity myEntity) {
    log.debug("Request to save MyEntity : {}", myEntity);
    MyEntity result = myEntityRepository.save(myEntity);
    myEntitySearchRepository.save(result);
    return result;
}
```
The StackOverflowError occurs on line `myEntitySearchRepository.save(result);`.

But if we do the following, the error does not happen anymore:
```java
public MyEntity save(MyEntity myEntity) {
    log.debug("Request to save MyEntity : {}", myEntity);
    MyEntity result = myEntityRepository.save(myEntity);
    myEntity.setId(result.getId());
    // myEntity is used, instead result, because ElasticSearch throws a StackOverflowError with result
    myEntitySearchRepository.save(myEntity);
    return result;
}
```

I don't know why this happens, but this workaround could help someone else to figure out the root of this problem.

**Comment by thelearner214** [comment]
I think it's similar to the [issue](https://stackoverflow.com/questions/67558754/indexing-problem-with-spring-data-elastic-migration-from-3-x-to-4-x). 
in the above examples, the second one is saving only the base entity as document whereas the first one refreshed all the relationships and tries to add them as subdocuments that might be cross referencing leading to the Stack-overflow error.

**Comment by Guzzi** [comment]
I think - unless there is a better and mor intelligent solution - jhipster should at least generate the save method in a way that it does not crash, e.g. with the above "two step" save method - otherwise the only practical way would be to disable elastic completely and manuelly implement it or manually fix all generated code, which imho doesn't make sense at all.

**Comment by naomeencontro** [comment]
Keep it open.

**Comment by thelearner214** [comment]
We are using this approach until a permanent solution: https://stackoverflow.com/a/68259478/15942962

**Comment by Tcharl** [comment]
Someone to identify a potential solution?

**Comment by Lina-Basuni** [comment]
This is still an issue

**Comment by pascalgrimaud** [comment]
Following the comments, it looks like a bug
Adding a bounty to motivate people to find a fix

**Comment by mheidt** [comment]
I think, it's rather an architectural issue. 
I wouldn't put the entities into elastic but a mix of the DTOs (if you enabled that) and the entity classes. 
Beans, that are cascading into other entites (not like the DTOs) but without the jpa annotations.
The jpl generator should generate those and we (the user) should be able to disable fields (f.e. if you don't like to have byte[] in your repo..kind of PITA right now).

**Comment by mheidt** [comment]
yes, the stackoverflow solution is the same @vitoraasouza suggested.

**Comment by RobertBurrellDonkin** [comment]
Anyway fancy taking this one on...? If so, please jump in :-)

If not, then I might have a little look today...

**Comment by RobertBurrellDonkin** [comment]
Thanks @mheidt :-)

Took a little bit of playing around to replicate the original with the latest (below) but yes, death loop still happens

`  
public AreaDTO save(AreaDTO areaDTO) {
        log.debug("Request to save Area : {}", areaDTO);
        Area area = areaMapper.toEntity(areaDTO);
        area = areaRepository.save(area);
        AreaDTO result = areaMapper.toDto(area);
        areaSearchRepository.save(area);
        return result;
    }
`

And yes, it's caused by using the live entity. And yes, I would lean towards using the DTO but that's a bigger architectural change.

But I think the correct narrow fix would be to map the result DTO to an entity then save that. (It's possible that the data store might change some values)

Unless anyone jumps in, I'm thinking about giving a fix a go tomorrow... Wish me luck!

**Comment by ko5tik** [comment]
Primary cause is  circular loop in object model - which was prevendet by @JsonIgnoreProperties before,    but new version of elasticsearch does not look for it at all.   I created a pull request for related issue ( https://github.com/jhipster/generator-jhipster/pull/17561 ) but there is no automatic handling of  object loops.   One solution would be to place @Transient on fields of entities which are indexed  - this will at least handle some of those loops

**Comment by OmarHawk** [comment]
I prepared a PR request that hopefully fixes this issue for most of the cases. #18866
