### ISSUE TITLE
Generating a separate CRUD interface for the administrators

### ISSUE THREAD

**Issue by preslavrachev** [jhipster/generator-jhipster#1486]
This is not so much an issue, as it is a request for an advice. I am sorry for wasting space on the issues page, but I really did not know where else to ask (the SO community will probably mark it off)

So, I followed the video tutorial, and built the skeleton of my app. Then, I reached the following problem: 
Per requirements, I'd have to provide administrators with an extremely simple, but functional management interface over all entities. Typical CRUD stuff. By default, the JHipster generators build a sort of a CRUD management UI, but the idea is that the programmer is then supposed to manually keep editing everything, until the final user UI is finished. In my case, I'd have to create the simple intuitive end-user UI for the user, but keep a fully functional CRUD UI for the administrators under "/admin"

The basic assumption is that I will mark specific controller actions as accessible only by user with administrator rights. Then, I have no idea so far, but to copy all the generated Angular components and moved them under a subdirectory called admin, so that they don't get affected by frontend changes. I will also need a bit of routing magic, and a copy of the HTML file to reference all of the admin comps. 

My biggest fear is not get some mess-ups while re-generating some of the components. Do you see a better way? 

Thanks in advance!

**Comment by preslavrachev** [comment]
This looks very interesting: http://lightadmin.org/ It is a pluggable CRUD admin dashboard for SpringBoot applications. If it does what it says, might save me the time to build the CRUD dashboard myself.

**Comment by jdubois** [comment]
My main concern is that you are going to duplicate everything, which isn't very good for maintenance.

The "normal" way of doing this is to have security checks, and not show the same screens depending on the user's rights. This is done with Spring Security & AngularJS, and is a standard use case.

If you "just" need a CRUD interface, then you can even have some SQL tool on top of your database for your administrators: as those interface won't have any business logic, this can lead to any kind of bugs, of course.

If this is really what you need, you can have look at [phpMyAdmin](http://www.phpmyadmin.net/home_page/index.php), I use it very often when I need a Web interface on top of a database.
