### ISSUE TITLE
Jhipster Generate fields without specific type and broke code 

### ISSUE THREAD

**Issue by yacosta738** [jhipster/generator-jhipster#14872]
##### **Overview of the issue**

When I generate a new project some class fields are missing types. Example the Class **UserNotActivatedException**   was generate with this field error
 
```
package com.mycompany.myapp.security;

import org.springframework.security.core.AuthenticationException;

/**
 * This exception is thrown in case of a not activated user trying to authenticate.
 */
public class UserNotActivatedException extends AuthenticationException {
    private static final serialVersionUID = 1L;

    public UserNotActivatedException(String message) {
        super(message);
    }

    public UserNotActivatedException(String message, Throwable t) {
        super(message, t);
    }
}
```

##### **Motivation for or Use Case**

This is an error and the project is incomplete.

##### **Reproduce the error**

Generate a new Project with Jhipster (The project could be in monolithic or microservice architecture)

##### **JHipster Version(s)**

```
testas@0.0.0 /home/acosta/Projects/Desoft/SMRO/test
└── generator-jhipster@7.0.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "testas",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1620181380554,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode)

git version 2.31.1

node: v14.16.1

npm: 6.14.12

Docker version 20.10.6, build 370c28948e

docker-compose version 1.26.2, build eefe0d31

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**
Brave Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) unknown (64-bit)

Operating System: Manjaro Linux
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
Kernel Version: 5.10.32-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-6500U CPU @ 2.50GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 520 

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by yacosta738** [comment]
The problem exists when you install Jhipster globally with yarn, with npm it works fine.

**Comment by atomfrede** [comment]
Which yarn version are you using? Sounds like a yarn issue to me.

**Comment by yacosta738** [comment]
this is my yarn version 
```
yarn -v
1.22.10
```
