### ISSUE TITLE
fix: Sub generators should allow using blueprint custom-options

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#14870]
##### **Overview of the issue**

Blueprints cannot have its own `options`. For example `KHipster` has `--skip-ktlint-format` option. But running `khipster docker-compose --skip-ktlint-format`  errors out with the following message 

```
error: unknown option '--skip-ktlint-format'
```

Refer https://github.com/jhipster/jhipster-kotlin/issues/281 for more details

cc: @mraible @mshima 

##### **Motivation for or Use Case**

Blueprints should be able to define their own `option` and all the sub-generators should be capable of handling them.

##### **Reproduce the error**

- Install KHipster
- Run `khipster docker-compose --skip-install`

##### **Related issues**

https://github.com/jhipster/jhipster-kotlin/issues/281

##### **Suggest a Fix**

load application config / options in all the sub-generators.

##### **JHipster Version(s)**

v7+

##### **JHipster configuration**

N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

All of the above

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
There are 2 actions to be taken in the generator-jhipster
- Migrate from fork to worker thread
- Migrate import-jdl command to a blueprintable generator.

**Comment by sendilkumarn** [comment]
How about adding a `--skip-format` option in the main generator as a temporary handler until we fix those two options? 

Blueprints can reuse them, right?

**Comment by mshima** [comment]
> How about adding a `--skip-format` option in the main generator as a temporary handler until we fix those two options?
> 
> Blueprints can reuse them, right?

Removing the default value doesn't fix the problem?
https://github.com/jhipster/jhipster-kotlin/issues/281#issuecomment-832268984

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/44490.

**Comment by pascalgrimaud** [comment]
@mshima : approved
