### ISSUE TITLE
multiple fetch of same resource in Karma test

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1488]
In ```passwordDirectiveSpec.js``` and ```authServiceSpec.js``` the ```$httpBackend.expectGET``` call seems to be repeated for `i18n/en/global.json` and `i18n/en/language.json` 
Is this intentional or a mistake?

**Comment by jdubois** [comment]
Indeed, but it looks like those calls are made twice by the application -> this is done by Angular Translate, so I'm not sure we can optimize this.
For me this isn't an issue in the tests, it's the application that shouldn't issue those calls.
