### ISSUE TITLE
Error: Failed to load plugin '@typescript-eslint' declared in '../.eslintrc.json': Cannot find module '@typescript-eslint/eslint-plugin'

### ISSUE THREAD

**Issue by hhipster** [jhipster/generator-jhipster#14885]
##### **Overview of the issue**

I have created a gateway application and I have tried to started it up on local.

when I am trying to build it with maven I am getting the following exception:
`Error: Failed to load plugin '@typescript-eslint' declared in '../.eslintrc.json': Cannot find module '@typescript-eslint/eslint-plugin'`

The same apply to 4 other team members.

Seems like this is related to the failing npm build.

I have tried to update my npm, install eslint again but I couldn't sort this out.
Sorry if it is a misconfiguration and not a bug, but I couldn't sort this out so I thought that maybe it is a bug

**Comment by hhipster** [comment]
Hi,
I am afraid this is something related to the dependency with the npm version in the pom.xml.
Is this happening to other users, or only my team and I are facing this issue?

**Comment by gmarziou** [comment]
https://stackoverflow.com/questions/67408568/jhipster-failed-to-load-plugin-typescript-eslint-declared-in-eslintrc-js

**Comment by hhipster** [comment]
Thank you very much for your help.
I have checked this question and your suggestion on it, I would like to share the logs when the mvnw is doing the npm install as suggested:

`--- frontend-maven-plugin:1.11.3:install-node-and-npm (install node and npm) @ aaa ---
[INFO] Node v14.16.0 is already installed.
[INFO] NPM 7.8.0 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.11.3:npm (npm install) @ aaa ---
[INFO] Running 'npm install' in /Users/user/Workspace/aaa
[INFO] 
[INFO] up to date, audited 2463 packages in 3s
[INFO] 
[INFO] 172 packages are looking for funding
[INFO]   run `npm fund` for details
[INFO] 
[INFO] found 0 vulnerabilities
[INFO] 
[INFO] --- frontend-maven-plugin:1.11.3:npm (webapp build dev) @ aaa ---
[INFO] npm not inheriting proxy config from Maven
[INFO] Running 'npm run webapp:build' in /Users/user/Workspace/aaa
[INFO] 
[INFO] > aaa@0.0.1-SNAPSHOT webapp:build
[INFO] > npm run clean-www && npm run webapp:build:dev
[INFO] 
[INFO] 
[INFO] > aaa@0.0.1-SNAPSHOT clean-www
[INFO] > rimraf target/classes/static/app/{src,target/}
[INFO] 
[INFO] 
[INFO] > aaa@0.0.1-SNAPSHOT webapp:build:dev
[INFO] > ng build
[INFO] 
[INFO] Webpack: Starting ...
Webpack: Starting ...
[INFO] 
[INFO]    ✔ Compile modules
[INFO]    ✔ Build modules
[INFO]    ❯ Optimize modules (102%)
[INFO]      → After seal ...
[INFO]      → After asset optimization ...✔ Browser application bundle generation complete.
[INFO]  ERROR  Failed to compile with 1 errors12:35:48 PM
[INFO] 
[INFO]  error  
Webpack: Starting ...
[INFO] 
[INFO]    ✔ Compile modules
[INFO]    ✔ Build modules
[INFO]    ✔ Optimize modules
[INFO]    ✔ Emit files
[INFO] 
[INFO] Webpack: Finished after 10.554 seconds.
[INFO] 
[INFO] 
[INFO] Error: Failed to load plugin '@typescript-eslint' declared in '../.eslintrc.json': Cannot find module '@typescript-eslint/eslint-plugin'
[INFO] Require stack:
[INFO] - /Users/user/Workspace/__placeholder__.js
[INFO] Referenced from: /Users/user/Workspace/.eslintrc.json
[INFO] 
`
As all this is automated via maven, what action should I take?

**Comment by gmarziou** [comment]
Please don't crosspost, it's hard to follow. Please post here or on stackoverflow not a bit of both.

```
[INFO] --- frontend-maven-plugin:1.11.3:npm (npm install) @ aaa ---
[INFO] Running 'npm install' in /Users/user/Workspace/aaa
[INFO]
[INFO] up to date, audited 2463 packages in 3s
```
As you can see, npm install did nothing because nothing has changed and modules are already installed.

So you could try a cleanup of `node` sub folder with `rm -rf /Users/user/Workspace/aaa/node` and then re-run build, maybe something did go wrong first time.

If this still fails, you could inspect the contents of `node/node_modules` to check whether `@typescript-eslint` is really missing.

Maybe this could be a compatibility problem between your local node environment and the one in pom.xml. Please show output of `node --version` and `npm --version`. Some users have experienced issues between npm 6 and 7, it could be due to your package-lock.json being in npm 6 and maven using 7.

**Comment by hhipster** [comment]
Hi,
Thank you again for the support you are giving! :)

node -v
v14.16.1

npm -v
7.11.2

deleted and recreated node_modules and removed the package-lock.json.
typescript folder is inside the node modules folder
still having this issue.
I have reinstalled npm and node.
I am using a MacBook pro intel processor.

**Comment by gmarziou** [comment]
I have tried same thing with [jhipster-sample-app](https://github.com/jhipster/jhipster-sample-app) on Windows and it fails but differently probably due angular cli running JHipster's custom webpack configuration.

```
[INFO] > jhipster-sample-application@0.0.1-SNAPSHOT webapp:build:dev
[INFO] > ng build
[INFO]
[INFO] An unhandled exception occurred: Cannot read property 'Match' of undefined

[error] TypeError: Cannot read property 'Match' of undefined
    at Object.<anonymous> (D:\projets\jhipster-projects\jhipster-sample-app\node_modules\@angular-builders\custom-webpack\dist\webpack-config-merger.js:9:49)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\projets\jhipster-projects\jhipster-sample-app\node_modules\@angular-builders\custom-webpack\dist\custom-webpack-builder.js:14:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\projets\jhipster-projects\jhipster-sample-app\node_modules\@angular-builders\custom-webpack\dist\transform-factories.js:14:34)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
````

I'll try to investigate further, maybe @kaidohallik could have some idea.

For your case, as a workaround, you could disable eslint, I could not try due to error I got but I suppose it should be done in `webpack/webpack.custom.js`

**Comment by gmarziou** [comment]
@hhipster does it fail the same when run outside maven with `npm run webapp:build` ?

**Comment by gmarziou** [comment]
I reproduced same error on Windows and fixed it by updating to latest versions of all eslint dev dependencies.
Could try? Below is the diff output to help.

```diff
diff --git a/package.json b/package.json
index fb0f5ed8..dc562429 100644
--- a/package.json
+++ b/package.json
@@ -101,7 +101,7 @@
   "devDependencies": {
     "@angular-builders/custom-webpack": "11.1.1",
     "@angular-builders/jest": "11.1.1",
-    "@angular-eslint/eslint-plugin": "2.0.2",
+    "@angular-eslint/eslint-plugin": "4.2.0",
     "@angular/cli": "11.2.6",
     "@angular/compiler-cli": "11.2.7",
     "@angular/service-worker": "11.2.7",
@@ -111,8 +111,8 @@
     "@types/mocha": "8.2.0",
     "@types/node": "14.14.37",
     "@types/selenium-webdriver": "4.0.11",
-    "@typescript-eslint/eslint-plugin": "4.20.0",
-    "@typescript-eslint/parser": "4.20.0",
+    "@typescript-eslint/eslint-plugin": "4.22.1",
+    "@typescript-eslint/parser": "4.22.1",
     "browser-sync": "2.26.14",
     "browser-sync-webpack-plugin": "2.3.0",
     "chai": "4.2.0",
@@ -122,7 +122,7 @@
     "copy-webpack-plugin": "6.4.1",
     "eslint": "7.23.0",
     "eslint-config-prettier": "8.1.0",
-    "eslint-webpack-plugin": "2.5.3",
+    "eslint-webpack-plugin": "2.5.4",
     "friendly-errors-webpack-plugin": "1.7.0",
     "generator-jhipster": "7.0.1",
     "husky": "4.3.8",
```

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's a bug

**Comment by gmarziou** [comment]
@pascalgrimaud it seems Dependabot is taking care of updating all these dependencies so let's wait for him to claim the bounty 😄, angular 12 is out and could help too and also I'm waiting for feedback from @hhipster

**Comment by pascalgrimaud** [comment]
Lol @gmarziou indeed!

**Comment by hhipster** [comment]
> @hhipster does it fail the same when run outside maven with `npm run webapp:build` ?

Hi,

Yes it is failing when it tries to do that command

thank you for your help

**Comment by gmarziou** [comment]
OK but did you try what I suggested: upgrading deps in package.json?

**Comment by mrafsyam** [comment]
Thanks @gmarziou. That solved my issue as well.

**Comment by akashgp09** [comment]
Hi @pascalgrimaud @gmarziou I would like to fix this issue :)

**Comment by gmarziou** [comment]
It's already fixed as far as I know

**Comment by pascalgrimaud** [comment]
Yes, by the bot I think
