### ISSUE TITLE
Cassandra cluster name is set as "Test Cluster"

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1489]
The `CassandraProperties.java` has `clusterName = "Test Cluster"`
Shouldnt this be set as a valid name relative to the generated app like `"<%=baseName%> Cluster"` or something?

I dont know s*** about Cassandra and I do not use it, I was just going through the generator code and saw this, so if it was intentional for a purpose plz forgive me :smile_cat:

**Comment by jdubois** [comment]
Good catch, but it's on purpose :-)
It's the default Cassandra cluster name (in conf/cassandra.yml), so it makes sense that our default is the same as their default.

**Comment by deepu105** [comment]
:-)
