### ISSUE TITLE
Thoughts on some useful features for JHipster 

### ISSUE THREAD

**Issue by raccarva** [jhipster/generator-jhipster#14907]
Hello folks.

I am taking my first experiences with JHipster and I am interested in it because it is not just a tool for programmers but a real software design tool. 
As so, it sits on top of Spring, Angular, and a bunch of other tools which compose an environment for it to deliver true time-saving capabilities such as delivering full-featured operational applications based only on the object-relational model defined by the user.
On the other hand, despite my humble experience with the tool, I already can see aspects that leave space for improvements, as explained below:

- The tool assumes that by generating a complete CRUD functionality for every entity, it will fulfill the developer's necessities, which I think is not the case. In almost all domain model you take from the real world, you will find some entities for what the developer does not want to implement all CRUD operations. For example, there are entities whose data is imported to the application and, so, the "create" operation does not make sense in the context of that application. So, there should exist clauses in the JDL (and/or questions in the tool) to allow the developer to limit the operations which are to be implemented for each entity;

- It generates programs to make CRUD operations for single entities, which is helpful but does not cover all common necessities. A common situation is when we need to implement CRUD´s for an entity in the context of a relationship, i. e. when you have the situation of an "entity" -> "entity-item" relationship, you want the instance of "entity" to appear in the form when creating "entity-item" elements for that instance (See an example in  https://docs.oracle.com/cd/E38376_01/English/User_Guides/uDesignerHelp/uDesigner/Content/uDesigner/18Designing%20a%20Form/Adding_a_Line_Item_List_to_a_Form.htm). I think this can be implemented in JH by adding the concept of SQL views (https://www.c-sharpcorner.com/UploadFile/f0b2ed/views-in-sql-server/) to JDL and allowing the generation of the CRUD programs for the defined views, and not only for single entities. I can develop these ideas and post them later if they are of interest. 

- The concept of "views" I mentioned earlier, could be useful also to implement restrictions such as in the case of the "blog application" example, where the developer has to change the repository query created by JH to limit the user to access only his/her posts. By using a view in JDL, this could be made intrinsic because the "recover" repository query would be generated from the view query and would not be a "findall" method over the entity.

I think more insights can show up while I familiarize myself with the tool and I intend to share them in the future.

If you think the ideas here are too broad to make a ticket, I can work them as separate and more specific tickets to be more in accordance with this channel.

Regards,

Ramiro.

**Comment by gmarziou** [comment]
In my own opinion, JHipster does not have the objective to create a well polished application, a developer is always required to modify generated code. Adding JDL keywords or more questions to give more control on what is generated could be a never ending task with the risk of making JH a difficult tool to learn.

The example you took from Primavera uDesigner's doc are not particularly exciting with these old screenshots in Internet Explorer, they just illustrate a vision from the past century where business people were told they could create an app without programming. Maybe it's coming back with no-code or low-code in a different form.

**Comment by raccarva** [comment]
> In my own opinion, JHipster does not have the objective to create a well polished application, a developer is always required to modify generated code. Adding JDL keywords or more questions to give more control on what is generated could be a never ending task with the risk of making JH a difficult tool to learn.
> 
> The example you took from Primavera uDesigner's doc are not particularly exciting with these old screenshots in Internet Explorer, they just illustrate a vision from the past century where business people were told they could create an app without programming. Maybe it's coming back with no-code or low-code in a different form.

Thanks for the comments, gmarziou.  You said that JH does not have the objective of creating a well polished application but it already does so in many aspects, to the point of generating such luxuries as monitoring and health functionality.
The core of my thinking is: should we use JH just as an application jump starter and then proceed to program in java/javascript (e.g. revert to "no tool" mode) or is it a good idea to see JH as an environment that will help me during the customization phase of the application as well?
If the second option is a good way to go (and I think it is), then having more features to control what will be generated is welcome.
