### ISSUE TITLE
Jest not picking up @types correctly

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#14900]
Disclaimer: I am new to Jest

##### **Overview of the issue**

I have been trying to to fix some tests that use Jest (angular).

Something I found is that @Types are not picked up leading to some errors in my tests, so I started looking for jest typescript support, I found two main libraries:
1- ts-jest (seems to need extra config to handle html templates correctly)
2-  jest-preset-angular (built on top of ts-jest it seems)
I couldn't make either of them work.

Documentation says that jest should pick @types automatically, but this doesn't seem to work for me:
I have :
```
    "@types/w3c-web-usb": "^1.0.4",
```

But my tests fail on complication with error:
```
Property 'usb' does not exist on type 'Navigator'.
``` 

I know Jest is using jsdom, I I am mocking these calls anyway, but the tests refuse to compile, until I manually copy past what is in the `@types/w3c-web-usb` inside the `setup-jest.ts` (see below). The only jest/typescript related library I found in the project is `@angular-builders/jest` but I don't know if I should report this there or somewhere else so I am posting here hopping to get help from the people who made the file @kaidohallik maybe you could help :) .

##### **Related issue**

Also, and this could be argued as unrelated, but I am trying to to customize the config, and I couldn't easily find how to do it:
It is actually pretty straight forward:
Edit the jest.conf.js to add some custom file `setup-jest.js` like this:

```
module.exports = {
  setupFiles: ['jest-date-mock', '<rootDir>/setup-jest.ts'],
  ...
}
```
Since are already mocking the angular router in a lot of the generated tests we could maybe move the 
```
jest.mock('@angular/router');
```
To that file, I think it would help a lot of users to know where to put there global configs, and it's the name I found used in most of the docs out there.

Also I can update the jest section of the generated project README to include this.
In my case I had to add:
```
jest.mock('@ngx-translate/core');
```

In a lot files because I use the `translateService` if few cases.

Maybe I am missing some performance issue with this, or this just not best practice. Please someone who knows better let me know.

##### **Motivation for or Use Case**

Improve the testing experience for developers

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by yelhouti** [comment]
Ok, After I tried everything in my project, I decide to create a minimal reproduction project using ng-cli for the `@angular-builder/jest`. After adding the USB dependency the project didn't compile (contrary to JHipster).
After some googling I found that adding 
```
/// <reference types="w3c-web-usb" />
```
Fixes the problem. And After running Jest it works. Same in my JHipster project.

My question now becomes: Why JHipster compiles without the Tri-Slash Directive ? (probably something in ts-config). And should jest (`@angular-builder/jest` ?) pick this up ? or should we change JHipster to be consistent between tests and normal code ?

**Comment by mshima** [comment]
You should take a look at https://github.com/jhipster/generator-jhipster/pull/14741.

And add `w3c-web-usb` to types at tsconfig.js.

**Comment by mshima** [comment]
I suppose this can be closed now.

**Comment by yelhouti** [comment]
@mshima well yes, if we remove the types from tsconfig.spec.ts (unless I'm missing something again)

**Comment by mshima** [comment]
Ok now you are asking to remove 
https://github.com/jhipster/generator-jhipster/blob/f92bb15f65e90c50fe8d15abb3fd6946aa7b7e8d/generators/client/templates/angular/tsconfig.spec.json.ejs#L24

But "types" is required when having conflicting typings like jest and mocha (cypress), maybe protractor too.

IMO is better to add typings to root than having to add typings to jest only,
With https://github.com/jhipster/generator-jhipster/blob/f92bb15f65e90c50fe8d15abb3fd6946aa7b7e8d/generators/client/templates/angular/tsconfig.spec.json.ejs#L20

jest inherits the root typings.

I will reopen to discuss if there is need for any action.

**Comment by yelhouti** [comment]
I didn't know about the conflict thing, thanks for the info.
well in that case, IMO, we should have no types in tsconfig and tsconfig.spec (to use `@types`). and add it only to e2e. What do you think?

**Comment by deepu105** [comment]
@mshima @yelhouti what should be done here?

**Comment by yelhouti** [comment]
@deepu105 
I don't remember how I fixed this so I am willing to close this for now.
