### ISSUE TITLE
Deploy on Heroku is missing one step in the documentation

### ISSUE THREAD

**Issue by christophe-f** [jhipster/generator-jhipster#1490]
Hi,

I have just followed the steps from the new documentation page:
http://jhipster.github.io/heroku.html

After installing the Heroku Belt, the 'heroku deploy:jar --jar target/*.war' command does not exist.
You have to install the 'heroku-deploy' plugin to make this work.

Here is the command to install the plugin:
heroku plugins:install https://github.com/heroku/heroku-deploy

Then you can push an app.

Another issue, is that it's been weeks I'm trying to use Heroku and either it's failing to start (due to their slow server with a timeout of 60 seconds), or random issue to connect to their Postgresql db.
So I'm using CloudFoundry and it's working 100% of the time. That was my last try on that platform.

Christophe

**Comment by jdubois** [comment]
Hi, I didn't install this plugin and it worked for me -> @jkutner do you know about this plugin?

**Comment by jkutner** [comment]
@christophe-f did you receive and error message in the logs that might suggest why the plugin was not installed? There is a step in the generator for it, but I can't see why I wouldn't have run. What platform are you running on (Linux, Mac, etc)?

Sorry Heroku didn't work out for you. Feel free to contact support about the boot timeout limit. If it's hanging after the step `Using Heroku, parsing their $DATABASE_URL to use it with JDBC`, then it's probably the app's auto config (the next step after that message) that takes so long. If it's hanging on something like "Configuring Liquibase", then it may be that the database is locked.

**Comment by christophe-f** [comment]
Thanks. 

As it's not a new app, I didn't run 'yo jhipster:heroku' but followed the section 'Updating your deployed application'. Now it's all good.

Thanks again.
