### ISSUE TITLE
Docker Compose sub-generator generates YAML that doesn't work with `docker compose`

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#14910]
##### **Overview of the issue**

The YAML generated by JHipster's Docker Compose sub-generator doesn't work with Docker CLI's new `compose` support.

* https://twitter.com/mraible/status/1390671872992464900
* https://github.com/oktadev/java-microservices-examples/pull/23

##### **Motivation for or Use Case**

It'd be cool if `docker compose` worked with JHipster.

##### **JHipster Version(s)**

7.0.1

**Comment by swarajsaaj** [comment]
bounty claim at https://opencollective.com/generator-jhipster/expenses/40709
