### ISSUE TITLE
Getting Unauthorized (401) when running from production

### ISSUE THREAD

**Issue by pmdusso** [jhipster/generator-jhipster#1493]
Hello there! I'm getting the following errors when trying to access my application running from AWS (in production mode):

```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
http://app.mydomain.com/views/main.html Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

When I clean the cookies, things work. Maybe the cookies from one app are interfering with the another? How can I debug this? If relevant, I can provide my security configurations, etc.

**Comment by jdubois** [comment]
Normally HTML pages are not secured with JHipster (they don't need to, as they have no data), so you should never have this problem.
Did you change the default security config?

If you want to debug what happens, change the log level of Spring Security to "debug", and you will see why it gives you the 401 response.
