### ISSUE TITLE
Bad sonar security rating 

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#14949]
##### **Overview of the issue**

Because of a change in the sonar rulesets we have now just a B in terms of security in our sample application.
The issue is imho not severe (maybe we can also exclude/ignore it), but we should do something about the red quality gate.

![image](https://user-images.githubusercontent.com/203401/117795573-9b710280-b24e-11eb-8905-97967f4be842.png)

![image](https://user-images.githubusercontent.com/203401/117796035-002c5d00-b24f-11eb-9f51-f780f4f6e850.png)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
I tried to forge some logs and succeeded. Running locally you can easily see the entry has been forged as it is not colored, but inside a log file or some other tool that would not be possible. So I tried OWASP easpi to encode it, but didn't have something working here.

**Comment by atomfrede** [comment]
I have managed to configured  https://github.com/javabeanz/owasp-security-logging with the owasp filter documented here https://github.com/javabeanz/owasp-security-logging/wiki/Log-Forging

It looks like this. Maybe we should only enabled it in production as the nice "table like" log gets broken of course. You can see how the line break is replaced by the owasp clrf filter:

![image](https://user-images.githubusercontent.com/203401/121079204-2572a380-c7da-11eb-841c-c4c17f436aec.png)

Basically this requires defining the clrf filter in `logback-spring.xml` and setting `logging.pattern.console` via regular properties using the clrf filter. With this I would say we are doing fine against log forging and could even ignore the sonar warnings regarding log forging.

**Comment by atomfrede** [comment]
Keep it open

**Comment by atomfrede** [comment]
Keep it open

**Comment by nomuna** [comment]
Just cloned the source code for the project and ran a sonar analysis with sonarqube-9.0.1.46107 for windows x64 with the defaults/ sonar quality gates. I don't see any security issues... Am I missing something? Is the project on sonar cloud? If it is could you provide the url?

**Comment by atomfrede** [comment]
It's the generated sample app not the generator code itself. It is on sonar cloud here https://sonarcloud.io/dashboard?id=jhipster-sample-application

**Comment by nomuna** [comment]
> 
> 
> It's the generated sample app not the generator code itself. It is on sonar cloud here https://sonarcloud.io/dashboard?id=jhipster-sample-application


So it has nothing to do with the code under  https://github.com/jhipster/jhipster-sample-app ?

**Comment by atomfrede** [comment]
It is exactly that project, you are right.

**Comment by atomfrede** [comment]
But in fact the rating has changed from `F` to `B` compared to the screenshots. The log forging is now minor as it seems

**Comment by nomuna** [comment]
> 
> 
> But in fact the rating has changed from `F` to `B` compared to the screenshots. The log forging is now minor as it seems

It is seriously weird... The scan I performed is a couple of hrs old and the code was checked out may be at the same time.
I don't see those log forging vulnerabilities.

**Comment by nomuna** [comment]
BankAccountQueryService class is neither in master nor in main branch. I think the code comes from a different repository.

**Comment by atomfrede** [comment]
Keep it open

**Comment by nomuna** [comment]
> 
> 
> I think that https://sonarcloud.io/dashboard?id=jhipster-sample-application is failing now just on code coverage.
> 
> What am I missing...?

As I have pointed out in my last message the project has moved on some classes were deleted and refactored so that the screenshot used as an info for the issue is no longer relevant. The devs refuse to accept it apparently... :D

**Comment by pascalgrimaud** [comment]
Probably it's because the Sonar analysis is broken since June:

![image](https://user-images.githubusercontent.com/9156882/143836452-17e85862-8661-4dfc-adaa-23fb262884df.png)

**Comment by atomfrede** [comment]
Coming back to this. The issue still exists, but the vulnerabilities are now minor (B). Nevertheless log forging is still possible, while I suppose a lot of people are using json based/structured logging instead of plain pattern layouts, not sure we must do something about it. We could document it more clearly in "going to production" and ignore the sonar issues. 
In addition we may also provide json log configuration (by default) for production?
