### ISSUE TITLE
Fix JWT token initialization in TokenProvider

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#14952]
##### **Overview of the issue**

I think there is a logical issue in the way the secret to generate the JWT token is initialized in the constructor of `TokenProvider` class.

The current implementation for JHipster version 7.0.1 is the following:

```
    public TokenProvider(JHipsterProperties jHipsterProperties) {
        byte[] keyBytes;
        String secret = jHipsterProperties.getSecurity().getAuthentication().getJwt().getSecret();
        if (!ObjectUtils.isEmpty(secret)) {
            log.warn(
                "Warning: the JWT key used is not Base64-encoded. " +
                "We recommend using the `jhipster.security.authentication.jwt.base64-secret` key for optimum security."
            );
            keyBytes = secret.getBytes(StandardCharsets.UTF_8);
        } else {
            log.debug("Using a Base64-encoded JWT secret key");
            keyBytes = Decoders.BASE64.decode(jHipsterProperties.getSecurity().getAuthentication().getJwt().getBase64Secret());
        }
        key = Keys.hmacShaKeyFor(keyBytes);
        jwtParser = Jwts.parserBuilder().setSigningKey(key).build();
        this.tokenValidityInMilliseconds = 1000 * jHipsterProperties.getSecurity().getAuthentication().getJwt().getTokenValidityInSeconds();
        this.tokenValidityInMillisecondsForRememberMe =
            1000 * jHipsterProperties.getSecurity().getAuthentication().getJwt().getTokenValidityInSecondsForRememberMe();
    }
```

The problem with this implementation is that in case in the `YAML` configuration files there are both `secret` and `base 64 secret` set, the less secure secret is chosen instead of the suggested base 64 one.

Moreover, JHipster generator already configures the normal plain text secret with a default value which is not visible to users, and it is hard to replace it properly with the base 64 one.

##### **Motivation for or Use Case**

As suggested by JHipster documentation and warning message in the code (`"Warning: the JWT key used is not Base64-encoded. " +
                "We recommend using the jhipster.security.authentication.jwt.base64-secret key for optimum security."`), developers should use to configure the secrete to generate the JWT token using the base 64 setting instead of the normal plain text.
But in case both are configured, I would imagine that the code would automatically get the base 64 one instead of the plain text.
This is not reflected in the code

##### **Suggest a Fix**

I would suggest the following change to reflect the suggestion also in the code:

```
    public TokenProvider(JHipsterProperties jHipsterProperties) {
        byte[] keyBytes;
        String secret = jHipsterProperties.getSecurity().getAuthentication().getJwt().getBase64Secret();
        if (!ObjectUtils.isEmpty(secret)) {
            log.debug("Using a Base64-encoded JWT secret key");
            keyBytes = Decoders.BASE64.decode(secret);
        } else {
            log.warn(
                "Warning: the JWT key used is not Base64-encoded. " +
                "We recommend using the `jhipster.security.authentication.jwt.base64-secret` key for optimum security."
            );
            secret = jHipsterProperties.getSecurity().getAuthentication().getJwt().getSecret();
            keyBytes = secret.getBytes(StandardCharsets.UTF_8);
        }
        key = Keys.hmacShaKeyFor(keyBytes);
        jwtParser = Jwts.parserBuilder().setSigningKey(key).build();
        this.tokenValidityInMilliseconds = 1000 * jHipsterProperties.getSecurity().getAuthentication().getJwt().getTokenValidityInSeconds();
        this.tokenValidityInMillisecondsForRememberMe =
            1000 * jHipsterProperties.getSecurity().getAuthentication().getJwt().getTokenValidityInSecondsForRememberMe();
    }
```
I this way, the priority is on the `getBase64Secret` instead of `getSecret` also in the code.

##### **JHipster Version(s)**

7.0.1

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
@alexsintoni Thanks for reporting the issue. I tend to agree to use the base64 if it is configured. Would you like to do a PR?
