### ISSUE TITLE
Add WebFlux choice to the Gateway generation as it is for Microservices and Monolithic applications

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#14950]
##### **Overview of the feature request**

In the last JHipster Generator version 7.0.1, it is possible to choose between WebFlux or regular JPA framework for both Microservices and Monolithic applications but not for Gateway.

In particular, during the step-by-step guide to generate a new project, it appears the following question
```
Do you want to make it reactive with Spring WebFlux? (y/N)
```
to choose if use `WebFlux` (if answered YES) or JPA (if answered NO).
Such question does not appear when users wants to generate Gateway.

I would like to have the same choice for Gateways as well.

##### **Motivation for or Use Case**

I read very little about `WebFlux`, therefore I am a total beginner about it.
The little documentation I saw said that `WebFlux` is useful to subscribe to streaming events like Twitter.
For all my use cases, I do not need to subscribe to any stream but run simple CRUD operations to a database.
For this purpose, JPA is a perfect framework that I also know well.
Unfortunately, I can choose to use JPA when I create both Microservices or Monolithic applications, but not when I create Gateways.
For this reason, I had difficulties to customize the gateways for my use cases and I have to learn how to use properly `WebFlux` which I don't even see useful for me as I don't need to subscribe to any stream event.

I hope, you understand my request and add that choice to generate Gateways as well as to generate Microservices or Monolithic applications.

Thanks a million for your understanding and help.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@alexsintoni : you can read this ticket too https://github.com/jhipster/generator-jhipster/issues/13855

I tried a lot of thing but the conclusion is to migrate to Reactive as we have no choice.

You can still checkout v7.0.0-beta.1 to use a Gateway without Reactive, but you won't be able to upgrade Spring Boot anymore
