### ISSUE TITLE
Tutorial AWS elastic beanstalk

### ISSUE THREAD

**Issue by seghers** [jhipster/generator-jhipster#1498]
Does anyone have a tutorial for 'deploying', 'hosting' a jhipster application on aws using:

- postgresql: > Amazon RDS for PostgreSQL
- ssl endpoint on the loadbalancer

I'm trying aws because Heroku charges $20/month for the ssl.
Would love to use ovh but they don't offer these things yet. (using runabove storage(s3) which is great)
And I don't have the know-how, time to setup everything in a secure, permanent way

ps: never used aws before.

Thank you

**Comment by jdubois** [comment]
Hi, I've heard about people using JHipster on AWS Beanstalk, but I don't have any tutorial about this.

I just can't test this, as this costs money, so I won't write any tutorial (unless someone is ready to spend is own $$$ to give some AWS credit, in that case I'll happily have fun with that money!)

**Comment by wuethrich44** [comment]
I deploy jhipster to aws successfully. I create a tomcat with elastic beanstalk and set the database credentials and the spring profile via environment variables. Then you can deploy the war file to the tomcat. If you have more question I suggest you to ask your questions in stackoverflow.

**Comment by jdubois** [comment]
@wuethrich44 if you could write a documentation, for the official website, that would be great!
But yes, I don't think there is anything specific to do to deploy to Beanstalk

**Comment by wuethrich44** [comment]
I think about to contribute a subgenerator for aws if there is any demand.

@jdubois Should I open e separate issue for this feature?

**Comment by jdubois** [comment]
@wuethrich44 no, no need to create an issue for that, the PR will be enough:

Fork https://github.com/jhipster/jhipster.github.io and copy/paste https://github.com/jhipster/jhipster.github.io/blob/master/cloudfoundry.html to create a new "Deploying on AWS" page and send a PR. I'll add it to the menu and reformat it if needed, the most important part is of course your content!

**Comment by deepu105** [comment]
@wuethrich44 how did I miss this thread :joy: I'm thinking of AWS sub generator as well, I primarily use AWS for hosting prototypes and stuff and was thinking of adding that as a sub.

I was looking into the AWS node-sdk (looks neat) and the AWS CLI

Let me know if you need any help

**Comment by wuethrich44** [comment]
That sounds great I think there is a real demand on a AWS sub generator. My first approach was to use the [EB cli](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3.html). I get jhipster running but I can figure out how to retrieve the RDS database name. But I will take a look in the node sdk...

**Comment by deepu105** [comment]
EB cli cant get RDS details, you have to either use AWS CLI or AWS SDK

The node SDK supports RDS and EBS along with other stuff
Btw what is your approach on this? if you have something on a repo let me know ill take a look as well

**Comment by wuethrich44** [comment]
I think the node sdk suits best for jhipster because we use node anyway. I will have a look on the sdk this week and provide any progress in this issue.

**Comment by wuethrich44** [comment]
I publish a first version of the aws generator in my repo (https://github.com/wuethrich44/generator-jhipster/tree/aws-generator)

The generator deploy the application in development profile and us a the H2 database. In a next step I try to get a RDSdatabase up and running.

@deepu105 Could you review my code and give me a feedback? (I'm a javascript newbie...)

**Comment by deepu105** [comment]
@jdubois btw you can use one app server and one db server instance for free for a year in aws in using that and as long as you have only 1 pair active you can create multiple apps and keep playing around for free

**Comment by deepu105** [comment]
@wuethrich44 sure ill take a look

**Comment by deepu105** [comment]
@wuethrich44 nice work man. overall it looks good, i have added some inline notes to your commit can you take a look. I guess this can be a good start for AWS and then slowly we can add on RDS instance creation etc.

**Comment by jdubois** [comment]
I think it really looks good, and I'd love to have this in JHipster.
Still, I can't test it -> @deepu105 I've used that one-year credit long ago... And I'm not going to pay for AWS... The good news is that I'm friend with AWS's head of developer marketing, I'm going to ask him for help!

**Comment by deepu105** [comment]
Btw i have an active account so i can help to test

**Comment by wuethrich44** [comment]
This week I try to setup jhipster with rds. But this is a little bit tricky with security groups etc. I will publish my progress in this issue.

**Comment by wuethrich44** [comment]
@deepu105 I add RDS database support currently for mysql (https://github.com/wuethrich44/generator-jhipster/commit/9c6e6fc68cb56f806afca7f6eb34d335ed2a024c). I would be very thankful if you could take a look at it...

**Comment by deepu105** [comment]
Sure ill take look during the weekend

**Comment by deepu105** [comment]
@wuethrich44 looks good man :+1: ill try to test your branch this weekend

**Comment by wuethrich44** [comment]
@jdubois The script is ready for a first PR. 

But the subgenerator will introduce three new dependencies in the `package.json` that only people need who use the aws subgenerator. Do you have a idea to install these dependencies dynamically or does this new dependencies doesn't matter?

I had a little discussion about this problem with @deepu105 in this commit https://github.com/wuethrich44/generator-jhipster/commit/8767ccecd21e93bae6187f8a3542eae149b61c7c.
