### ISSUE TITLE
Compilation error in Gateway application not using Reactive

### ISSUE THREAD

**Issue by jidma** [jhipster/generator-jhipster#14988]
##### **Overview of the issue**

After generating a new Gateway application with reactive = false
There's a compilation error on `GatewayResource.java` 

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project xrp-gateway: Compilation failure
    [ERROR] /C:/Users/xxxxxxxxxxx/xxxx/appgateway/web/rest/GatewayResource.java:[52,49] cannot find symbol
    [ERROR]   symbol:   variable appName
    [ERROR]   location: class com.xrp.appgateway.web.rest.GatewayResource

##### **Suggest a Fix**

Check this commit: 6126a05, 

In the file,  `generators/server/templates/src/main/java/package/web/rest/GatewayResource.java.ejs` the variable `appName` is not declared when reactive is false:

    <%_ if (reactive) { _%>
        @Value("${spring.application.name}")
        private String appName;
    <%_ } _%>

But it's still used later in the code regardless of the value of `reactive`:

    if (!serviceId.equalsIgnoreCase(appName)) {
         routeVM.setServiceInstances(discoveryClient.getInstances(serviceId));
         routeVMs.add(routeVM);
     }

##### **JHipster Version(s)**

Regression since 7.0.0 - Works @ 6.10.5

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "gateway",
    "baseName": "XrpGateway",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "xrp",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "pages": [],
    "creationTimestamp": 1620857463720,
    "serviceDiscoveryType": "consul",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.xrp.appgateway",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": ["messageBroker:kafka"],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": "kafka",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/xrp/appgateway",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"],
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons"
  }
}

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities yet

##### **Browsers and Operating System**

Not relevent

**Comment by mraible** [comment]
There is no option for a non-reactive gateway in JHipster 7. See https://twitter.com/mraible/status/1392127843233112069 for more information.

**Comment by jidma** [comment]
> There is no option for a non-reactive gateway in JHipster 7. See https://twitter.com/mraible/status/1392127843233112069 for more information.

Thank you for the reply.
There's still this misleading condition in `GatewayResource.java.ejs` :

    <%_ if (reactive) { _%>
        @Value("${spring.application.name}")
        private String appName;
    <%_ } _%>

**Comment by mraible** [comment]
Does this misleading condition cause issues? Or is it just not used?

**Comment by jidma** [comment]
Well if I understood correctly and that we can't have non-reactive gateways, then the condition on the 'reactive' variable shouldn't be used (always true).

Also the .yo-rc.json still references the variables 'reactive' for the gateway.

I manually set it to true and regenerated which lead to the compilation error.

**Comment by mraible** [comment]
@pascalgrimaud I believe you added the logic to force a reactive gateway. Does JDL allow you to override that?

**Comment by jidma** [comment]
I don't think it does. It generates the `.yo-rc.json` with reactive set to false.

**Comment by jidma** [comment]
@mraible  Should I close this issue, or create a PR to remove the condition ?

change:

    <%_ if (reactive) { _%>
        @Value("${spring.application.name}")
        private String appName;
    <%_ } _%>

to

    @Value("${spring.application.name}")
    private String appName;

(because reactive should always be true)

**Comment by mraible** [comment]
A PR would be great. Thank you!

**Comment by jidma** [comment]
> A PR would be great. Thank you!

Thank you for your time

**Comment by pascalgrimaud** [comment]
How can I reproduce ?
Using prompt ? JDL ?

**Comment by jidma** [comment]
> How can I reproduce ?
> Using prompt ? JDL ?

- modify .yo-rc.json (see description)
- run `jhipster`

**Comment by pascalgrimaud** [comment]
Yes, but this yo-rc.json is invalid, it should not be possible to generate it, with prompt or JDL, unless it's manually edited

**Comment by jidma** [comment]
> Yes, but this yo-rc.json is invalid, it should not be possible to generate it, with prompt or JDL, unless it's manually edited

Indeed

**Comment by pascalgrimaud** [comment]
Ok in this case, I don't think we can do something as it's out of scope of the generation, if the user edited manually the yo rc json, and relaunch the generation

**Comment by jidma** [comment]
> Ok in this case, I don't think we can do something as it's out of scope of the generation, if the user edited manually the yo rc json, and relaunch the generation

Indeed, and in this case my PR just removes the "if condition", because its an unused code now that reactive is always true.

**Comment by atomfrede** [comment]
Seems like everything is clear now.
