### ISSUE TITLE
After adding Heroku support, tests fail

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1501]
After the `HerokuDatabaseConfiguration.java` file is added, tests fail:

> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.context.ApplicationContextException: Heroku database URL is not configured, you must set --spring.datasource.heroku-url=$DATABASE_URL

My workaround:

Added the following to `HerokuDatabaseConfiguration`:

    @Profile("heroku")

Modify Procfile to have:

    --spring.profiles.active=prod,heroku

**Comment by jdubois** [comment]
Yes that seems logical to me, in fact I thought we had this Spring profile (I did a "git blame" and I didn't find anything, so I might just be crazy...)

I'm having a look at this cc @jkutner

**Comment by jdubois** [comment]
And of course what you did @mraible works... And this is what I believed we already had :-)

I'm going to modify our code accordingly, @jkutner I hope it's OK for you?

**Comment by jkutner** [comment]
@jdubois looks good. thanks for fixing that!
