### ISSUE TITLE
JHipster keeps crashing on Heroku

### ISSUE THREAD

**Issue by nikrich** [jhipster/generator-jhipster#1503]
Every couple of hours my JHipster default application crashes on Heroku.
I'm using the Hobby Dyno and here is the gist of my Heroku log:

https://gist.github.com/nikrich/56cde6b9be6fe53ecc24

Is this a JHipster bug or rather Heroku? I'm at a loss

**Comment by jdubois** [comment]
If you are using the "free" version of Heroku, I think it's normal that they shut down your instance everyday.
Then if it doesn't start up, did you check if your database is locked? See http://jhipster.github.io/heroku.html

It mostly looks like JHipster is waiting for something -> I'm guessing it's the database lock

**Comment by nikrich** [comment]
Thanks for the speedy response!

Will look into it. I'm not using the Free account instead I'm using the $7 hobby account.

Regards

**Comment by jdubois** [comment]
I'm not sure what the hobby account provide, isn't this just for the database? And they can still put your app server to sleep?

**Comment by nikrich** [comment]
Here is the details for hobby :) : 

![image](https://cloud.githubusercontent.com/assets/8254123/7722934/d77013da-fee4-11e4-82fd-402a530dfb13.png)

**Comment by jdubois** [comment]
OK, so it 'never sleeps', which was my main question! So your app shouldn't be crashing all the time, did you check the database?

**Comment by nikrich** [comment]
Not yet! Will do so in the afternoon when I'm at my linux desktop!

**Comment by jdubois** [comment]
Hi, I've read your log again, and I saw it was waiting for Liquibase before going into time out -> this is the database lock problem, see http://jhipster.github.io/heroku.html and you will get the solution!

You might want to remove Liquibase for this reason, but at the same time it's really useful for database upgrades with Heroku...

**Comment by ramjamram** [comment]
Were you able to deploy Jhipser to Heroku? I have been reading that typical slug file of Jhipster exceeds the maximum slug size allow in Heroku. Do you mind telling me how big was the Jhipster slug file deployed to Heroku?
