### ISSUE TITLE
Redux code is following very outdated practices - would you consider switching to Redux Toolkit?

### ISSUE THREAD

**Issue by phryneas** [jhipster/generator-jhipster#15033]
##### **Overview of the feature request**

The Redux code currently in this Project follows very outdated Redux patterns. I would suggest following current best practices from the [Redux Style Guide](https://redux.js.org/style-guide/style-guide/) and switching over to the official Redux Toolkit.

##### **Motivation for or Use Case**

Hi,
I'm a Redux maintainer :wave: 

From time to time we get JHipster users in our help chat (#redux on [Reactiflux](https://www.reactiflux.com/)) and their applications come with very outdated patterns that we do not actively encourage for new applications any more and that require a lot more code to be written by the user. 
It is quite disheartening to tell them that, despite having created a "new" application, they are actually very far away from what we would not consider "best practice" and they essentially have to refactor their application.

Would you be willing to consider switching over to the official [Redux Toolkit](https://redux-toolkit.js.org/) and, while at it, also from `connect` calls to the more modern [Redux Hooks](https://react-redux.js.org/api/hooks) `useState` and `useDispatch`?

A good overview on what actually changes with Redux Toolkit is available in the official [Redux Fundamentals Tutorial, Part 8: Modern Redux with Redux Toolki](https://redux.js.org/tutorials/fundamentals/part-8-modern-redux)

##### **Related issues or PR**

None similar in this Project. A similar switch has for example been done by React Boilerplate at the end of 2019: https://github.com/react-boilerplate/react-boilerplate/pull/2808

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Thanks for the suggestion @phryneas. I've added a bug bounty to this issue in hopes of increasing motivation.

**Comment by deepu105** [comment]
I'll give it a go over the weekend

**Comment by phryneas** [comment]
It's tempting, but I already have too much on my "maintainer plate" with the upcoming release of RTK Query - so go for it. If you have any questions about best practices that go beyond the links above, feel free to contact me in chat. But really, especially with the [CRA template](https://github.com/reduxjs/cra-template-redux-typescript) there is probable a lot of prior art on how to approach this best :)

**Comment by deepu105** [comment]
Ok I'm on it then

**Comment by deepu105** [comment]
@phryneas while I agree about moving to redux toolkit and stuff I'm not sure about using hookes instead of connect. I find connect with mapStateToProps and mapDispatch cleaner with added advantage of TS inference etc. Is thete any actual advantage of using hooks for this?

**Comment by phryneas** [comment]
Yes. TS inference is a *lot* cleaner for the hooks, as you don't need do declare any types at all and need to do stuff like merging around prop types.

If you have declared a `useAppSelector` hook like described in [TypeScript QuickStart](https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks), you just do

```ts
const value = useAppSelector(state => state.foo.bar.baz)
```
and it is perfectly typed from start to end.

**Comment by deepu105** [comment]
Ok I'll try it out and see

**Comment by deepu105** [comment]
@phryneas I'm trying to rewrite current reducers using the createSlice method and it seems like this will create way more code than what we currently have, since there are many cases which just falls through in current scenario due to them being thunks with Reques/Success/failure states. The toolkit docs uses very simple examples. Is there way to write the below reducer cleanly using createSlice/createReducer without adding a `builder.addCase()` for each case? Else IMO this change will overall make the code base less DRY IMO is harder to justify the value of using createSlice


```
export default (state: UserManagementState = initialState, action): UserManagementState => {
  switch (action.type) {
    case REQUEST(ACTION_TYPES.FETCH_ROLES):
      return {
        ...state,
      };
    case REQUEST(ACTION_TYPES.FETCH_USERS):
    case REQUEST(ACTION_TYPES.FETCH_USERS_AS_ADMIN):
    case REQUEST(ACTION_TYPES.FETCH_USER):
      return {
        ...state,
        errorMessage: null,
        updateSuccess: false,
        loading: true,
      };
    case REQUEST(ACTION_TYPES.CREATE_USER):
    case REQUEST(ACTION_TYPES.UPDATE_USER):
    case REQUEST(ACTION_TYPES.DELETE_USER):
      return {
        ...state,
        errorMessage: null,
        updateSuccess: false,
        updating: true,
      };
    case FAILURE(ACTION_TYPES.FETCH_USERS):
    case FAILURE(ACTION_TYPES.FETCH_USERS_AS_ADMIN):
    case FAILURE(ACTION_TYPES.FETCH_USER):
    case FAILURE(ACTION_TYPES.FETCH_ROLES):
    case FAILURE(ACTION_TYPES.CREATE_USER):
    case FAILURE(ACTION_TYPES.UPDATE_USER):
    case FAILURE(ACTION_TYPES.DELETE_USER):
      return {
        ...state,
        loading: false,
        updating: false,
        updateSuccess: false,
        errorMessage: action.payload,
      };
    case SUCCESS(ACTION_TYPES.FETCH_ROLES):
      return {
        ...state,
        authorities: action.payload.data,
      };
    case SUCCESS(ACTION_TYPES.FETCH_USERS):
    case SUCCESS(ACTION_TYPES.FETCH_USERS_AS_ADMIN):
      return {
        ...state,
        loading: false,
        users: action.payload.data,
        totalItems: parseInt(action.payload.headers['x-total-count'], 10),
      };
    case SUCCESS(ACTION_TYPES.FETCH_USER):
      return {
        ...state,
        loading: false,
        user: action.payload.data,
      };
    case SUCCESS(ACTION_TYPES.CREATE_USER):
    case SUCCESS(ACTION_TYPES.UPDATE_USER):
      return {
        ...state,
        updating: false,
        updateSuccess: true,
        user: action.payload.data,
      };
    case SUCCESS(ACTION_TYPES.DELETE_USER):
      return {
        ...state,
        updating: false,
        updateSuccess: true,
        user: defaultValue,
      };
    case ACTION_TYPES.RESET:
      return {
        ...initialState,
      };
    default:
      return state;
  }
};
```

**Comment by phryneas** [comment]
Honestly, that above snippet means that your current logic there is highly suspectible to race conditions if two different request were ever to run at the same time, as their lifecycle would override the loading status of each other.  
Those should use separate loading states.

Generally, going in on Redux Toolkit would also mean getting rid of `redux-promise-middleware` and following the recommendations on asynchronity there.

There you could go two routes:
* follow the **current** approach and use `createAsyncThunk`, but this has the same problem as your code above: it will need multiple status properties for multiple requests, which will make code reuse difficult
* go all-in on the upcoming features of RTK. We released the beta of RTK 1.6 which will come with [RTK Query](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/tutorials/rtk-query) just a few hours ago (from this point on we are primarily writing more docs, there are no more API changes to be expected). 
For RTK-Query you would just write a central api description with all your endpoints on it and it will create the complete redux logic and hooks to use in your components automatically.

As an example:

```ts
export const pokemonApi = createApi({
  reducerPath: 'pokemonApi',
  baseQuery: fetchBaseQuery({ baseUrl: 'https://pokeapi.co/api/v2/' }),
  endpoints: (builder) => ({
    getPokemonByName: builder.query<Pokemon, string>({
      query: (name) => `pokemon/${name}`,
    }),
  }),
})

// Export hooks for usage in functional components, which are
// auto-generated based on the defined endpoints
export const { useGetPokemonByNameQuery } = pokemonApi
```

and in a component:

```ts
  const { data, error, isLoading } = useGetPokemonByNameQuery('bulbasaur')
```

**Comment by phryneas** [comment]
PS: I'm not sure if JHipster emits an OpenAPI specification, but if it does you can even use our [Code Generation](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/usage/rtk-query/code-generation) approach for those endpoint definitions and all their types.

**Comment by deepu105** [comment]
1. Yes i'm aware of that, the loading status is common for an entity and its ok if its overridden. the chances of two calls for the same entity on a page is very low and even if it happens its perfectly ok for the loading to be overridden as its only used for trivial things.
2. Unfortunately this is where I would disagree. I find the `createAsyncThunk` based stuff too boilerplatey and less readable than current simple action/reducer combo. I'm fine with functional programming style as long as it doesnt become too convoluted. 
3. The RTKQuery option seems reasonable but I dont want to use a beta version here

You know overall I'm actually even less sure now that moving to redux toolkit is actually providing any tangible value at all. If anything it seems to be making the code less readable and more boilerplatey. But i'll do my best to resemble the RTK pattern for the sake of users even though I'm not fully convinced. Don't get me wrong I have used RTK on other projects and it was fine, since I started with it there I just wrote everything according to that style, but doing a migration and forcing it on anyone who tries to upgrade to a new JHipster version seems like a waste of effort given the current code works fine and I dont see any issue with it except for following a different code style

**Comment by deepu105** [comment]
I'm gonna try something like this for now https://stackoverflow.com/questions/61582886/how-to-use-redux-promise-middleware-with-slices-in-redux-toolkit

**Comment by phryneas** [comment]
As for RTK Query being a beta release right now: this has been in alpha for half a year and we're at the point where we're incorporated just about every suggestion and fixed that handfull of minor bugs that have been reported.
At the current point, unless someone would come around the corner with a world-shattering bug, we won't take much longer. Any new features would probably not make it into RTK 1.6 any more, but would be postponed for 1.7.
The main point right now is integrating it with the RTK package itself and especially getting everything documented. We're pretty far with that by now, so I'm confident that that final release will be within the next few weeks.

If you want to make additional state changes on response, you can always add extraReducers to that other slice that should change for the `api.endpoints.myEndpoint.matchFulfilled` [action matcher](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/api/rtk-query/created-api/endpoints#matchers)

Other side effects could be triggered from the [`onQueryStarted`](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/api/rtk-query/createApi#onquerystarted) lifecycle event.

The point about getting RTK in here is not necessarily getting all current users to migrate over, but to not provide non-standard patterns in "newly generated" applications any more. 
I don't know how much control you have there over who gets what, but people who use a code generator like this often learn from it (maybe coming in from another part of the stack) - and someone learning all the patterns that are reflected here is doing themselves a big disservice as the Redux ecosystem is finally going into a common direction after having been a mess of libraries & patterns that nobody could possibly find any orientation in for years before.

**Comment by phryneas** [comment]
Also, just thinking about it: did you take the [matching utility `isAnyOf`](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/api/matching-utilities#isanyof) into account?

```js
builder.addMatcher(isAnyOf(
  FAILURE(ACTION_TYPES.FETCH_USERS),
  FAILURE(ACTION_TYPES.FETCH_USERS_AS_ADMIN),
  FAILURE(ACTION_TYPES.FETCH_USER),
  FAILURE(ACTION_TYPES.FETCH_ROLES),
  FAILURE(ACTION_TYPES.CREATE_USER),
  FAILURE(ACTION_TYPES.UPDATE_USER),
  FAILURE(ACTION_TYPES.DELETE_USER)
), (state, action) => {
  state.loading = false;
  state.updating = false;
  state.updateSuccess = false;
  state.errorMessage = action.payload,
})
```

**Comment by markerikson** [comment]
> overall I'm actually even less sure now that moving to redux toolkit is actually providing any tangible value at all. If anything it seems to be making the code less readable and more boilerplatey. 

@deepu105 A few thoughts here:

- RTK has been specifically designed to simplify standard Redux usage patterns and eliminate common mistakes.  Using it will be a net improvement for all people working on these codebases.
- It's also now the standard approach for writing Redux apps. That means that as RTK adoption continues to grow, it will be beneficial for people to see the same consistent patterns across multiple codebases.
- The "check for any failure in this slice" case could probably even be simplified further by doing a check for the slice prefix rather than checking all those different action types individually

**Comment by deepu105** [comment]
Wasn't aware of the isAny of utility. I think that will do the job. Also I think RTK query may not work for us since we currently use axios especially so that we can make jwt/oauth and session based auth work seamlessly. We have an axios interceptor that handles that. If RTK can have such a mechanism then may be could work. I'll try out few different combinations and see which looks better. I'll do a draft PR so that I can get some reviews from you guys may be

**Comment by phryneas** [comment]
You can switch out the "fetching logic" of RTK query completely by specifying a different baseQuery, we just already ship with a basic fetch implementation. See the "customizing queries" docs page, especially [the basic axios example](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/usage/rtk-query/customizing-queries#axios-base-query)

**Comment by markerikson** [comment]
You can use RTK Query with whatever fetching mechanism you want - we just supply `baseFetchQuery` out of the box so that users don't have to write a bunch of hand-written `fetch()` logic themselves.

We have an example of Axios usage in the preview docs:

https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/usage/rtk-query/customizing-queries#axios-base-query

**Comment by deepu105** [comment]
@phryneas @markerikson 

> If you want to make additional state changes on response, you can always add extraReducers to that other slice that should change for the api.endpoints.myEndpoint.matchFulfilled action matcher

> Other side effects could be triggered from the onQueryStarted lifecycle event.

I need to trigger the GET request from the same API when an update happens, I was looking for something like `onQueryCompleted` but I think that doesnt exist, probably due to the async nature of stuff. So for this API there is no custom reducer where I can add an api.endpoints.myEndpoint.matchFulfilled action matcher so what would be RTK way to trigger `getUsers` from below when `createUser` is completed? 

```
const userApi = createApi({
  baseQuery: axiosBaseQuery(),
  endpoints(build) {
    return {
      getUsers: build.query({
        query: ({ page, size, sort }: ISearch) => ({
          url: `${apiUrl}${sort ? `?page=${page}&size=${size}&sort=${sort}` : ''}`,
          method: 'GET',
        }),
      }),
      getUsersAsAdmin: build.query({
        query: ({ page, size, sort }: ISearch) => ({
          url: `${adminUrl}${sort ? `?page=${page}&size=${size}&sort=${sort}` : ''}`,
          method: 'GET',
        }),
      }),
      getRoles: build.query({
        query: () => ({ url: 'api/authorities', method: 'GET' }),
      }),
      getUser: build.query({
        query: (id: string | number) => ({ url: `${adminUrl}/${id}`, method: 'GET' }),
      }),
      createUser: build.mutation({
        query: (user: IUser) => ({ url: adminUrl, method: 'POST', data: user }),
      }),
    };
  },
});
```

**Comment by deepu105** [comment]
On a side note I noticed this from webpack

```
WARNING in ./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/deepu/workspace/jhipster/temp/jhtest/node_modules/@reduxjs/toolkit/dist/module.js.map' file: Error: ENOENT: no such file or directory, open '/home/deepu/workspace/jhipster/temp/jhtest/node_modules/@reduxjs/toolkit/dist/module.js.map'

```

**Comment by deepu105** [comment]
So finally after trying both RTK Query and `createSlice` with `createAsyncThunk` actions, I decided to proceed with `createSlice` with `createAsyncThunk` as it was the path with least drastic changes overall. For RTK query I would have to literally rewrite almost all of the app from scratch to fit its opinionated style and more importanstly most of the features offered by RTK query like catching, polling etc is not required for JHipster apps, so we will be paying for the abstractions unnecessarily without much benefit.

[Here](https://github.com/deepu105/jhipster-sample-app/commit/5c42198da7d2158211de872454935fbac7c21d26) is the commit with impl for one entity, can you guys take a look and see if anything can be improved? if it looks OK then I'll proceed to do the same for all the entities in the app and then update the JHipster templates to use the same. I think I'll also create a [wrapped method](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/usage/usage-with-typescript#wrapping-createslice) for createSlice to further cutdown boilerplate as all our entities pretty much use the same template

**Comment by markerikson** [comment]
Observations:

- Setting up `defaultMiddleware` as an array that way is going to lose the types, _and_ it's going to throw away the development mode safety check middleware.  Also, `configureStore` already adds the thunk middleware anyway.  It should be changed to:

```ts
const store = configureStore({
  reducer,
  middleware: getDefaultMiddleware => {
    return getDefaultMiddleware.concat(
      errorMiddleware,
	  notificationMiddleware,
	  promiseMiddleware, // todo remove
	  loadingBarMiddleware(),
	  websocketMiddleware,
	  loggerMiddleware,
    );
  }
})
```

- What's the issue with `useAppDispatch`?
- Just as an FYI, destructuring results from `useSelector` is legal, but it will cause this component to re-render even if _other_ fields in that object that aren't used are updated, so you have to be sure that this component really is using all the fields in that slice.  In other words:
  - if a particular slice has `{a, b,c, d}`
  - and I do `const {a, b, c} = useSelector(state => state.someSlice)`
  - and `state.someSlice.d` gets updated
  - then the component will still re-render because the returned `state.someSlice` value got updated, even though this component doesn't care about it.
- The new async thunks appear to be mostly doing `return axios.get()`, which means the response object itself is going to end up as `action.payload`.  Typically you'd want just `response.data` to be the payload, which means you'd need to `await` the response promise and then `return response.data`
- I don't think the `return Promise.resolve(result)` bits are needed - you can just `return result` since the payload creators are `async` already.
- I think you could probably also drop the `try/catch` in most of those and just let the rejected promise aspect throw errors as normal.
-

**Comment by phryneas** [comment]
Sorry, I was away for most of the day.

> I need to trigger the GET request from the same API when an update happens, I was looking for something like `onQueryCompleted` but I think that doesnt exist, probably due to the async nature of stuff. So for this API there is no custom reducer where I can add an api.endpoints.myEndpoint.matchFulfilled action matcher so what would be RTK way to trigger `getUsers` from below when `createUser` is completed?


You would use the invalidation features - see [Cached Data](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/rtk-query/usage/cached-data)

```diff
const userApi = createApi({
  baseQuery: axiosBaseQuery(),
+  tagTypes: ["User"],
  endpoints(build) {
    return {
      getUsers: build.query({
        query: ({ page, size, sort }: ISearch) => ({
          url: `${apiUrl}${sort ? `?page=${page}&size=${size}&sort=${sort}` : ''}`,
          method: 'GET',
        }),
// will be reloaded when either "User:LIST" invalidates or one of the "User:id" pairs on this page invalidates
+       providesTags: (result) =>
+        result
+          ? [
+              ...result.map(({ id }) => ({ type: 'User' as const, id })),
+              { type: 'User', id: 'LIST' },
+            ]
+          : [{ type: 'User', id: 'LIST' }],
      }),
      getUsersAsAdmin: build.query({
        query: ({ page, size, sort }: ISearch) => ({
          url: `${adminUrl}${sort ? `?page=${page}&size=${size}&sort=${sort}` : ''}`,
          method: 'GET',
        }),
      }),
      getRoles: build.query({
        query: () => ({ url: 'api/authorities', method: 'GET' }),
      }),
      getUser: build.query({
        query: (id: string | number) => ({ url: `${adminUrl}/${id}`, method: 'GET' }),
// will reload if this "User:id" pair invalidates
+       providesTags: (result, error, arg) => [{{ type: 'User', id: arg }]
      }),
      createUser: build.mutation({
        query: (user: IUser) => ({ url: adminUrl, method: 'POST', data: user }),
// invalidates "User:LIST"
+       invalidatesTags: (result) => [{{ type: 'User', id: 'LIST' }]
      }),

      updateUser: build.mutation({
// ...
// invalidates "User:id"
+       invalidatesTags: (result, error, arg) => [{{ type: 'User', id: arg }]
      }),
    };
  },
});
```

This is especially interesting when you have one API for all entity types (as we recommend, you can still split it over multiple files) and one endpoint mutation also causes query results from other entities to refetch (maybe because they somehow return combined results)

**Comment by deepu105** [comment]
> Observations:
> 
> * Setting up `defaultMiddleware` as an array that way is going to lose the types, _and_ it's going to throw away the development mode safety check middleware.  Also, `configureStore` already adds the thunk middleware anyway.  It should be changed to:
> 
> ```ts
> const store = configureStore({
>   reducer,
>   middleware: getDefaultMiddleware => {
>     return getDefaultMiddleware.concat(
>       errorMiddleware,
> 	  notificationMiddleware,
> 	  promiseMiddleware, // todo remove
> 	  loadingBarMiddleware(),
> 	  websocketMiddleware,
> 	  loggerMiddleware,
>     );
>   }
> })
> ```

Didn't know about thunk being pre-included, will update. I dont get the typing magic, seems a bit weird :thinking: Regardless I updated to what you suggested

> * What's the issue with `useAppDispatch`?

There was some TS errors when passing `AppDispatch` as generic, but now it seems to be gone after changing to above code

> * Just as an FYI, destructuring results from `useSelector` is legal, but it will cause this component to re-render even if _other_ fields in that object that aren't used are updated, so you have to be sure that this component really is using all the fields in that slice.  In other words:
>   
>   * if a particular slice has `{a, b,c, d}`
>   * and I do `const {a, b, c} = useSelector(state => state.someSlice)`
>   * and `state.someSlice.d` gets updated
>   * then the component will still re-render because the returned `state.someSlice` value got updated, even though this component doesn't care about it.

Totally overlooked that. Been away from React/Redux for a while :joy: This means I'll have to assign each field in a new line with a `useSelector` right. that seems ugly though :sob: 

> * The new async thunks appear to be mostly doing `return axios.get()`, which means the response object itself is going to end up as `action.payload`.  Typically you'd want just `response.data` to be the payload, which means you'd need to `await` the response promise and then `return response.data`
> * I don't think the `return Promise.resolve(result)` bits are needed - you can just `return result` since the payload creators are `async` already.
> * I think you could probably also drop the `try/catch` in most of those and just let the rejected promise aspect throw errors as normal.

All this was my attempt to fix the issue I mentioned in the commit as below. Seems like the error object from axios is swallowed by RTK at some point and instead it returns a simple error object with just message and stack. We have some middlewares which really need all the info from the axios error, so was trying different things to see if it will work, I guess finally `return thunkAPI.rejectWithValue(error);` sees to work but then I didnt try removing other stuff as I really didnt understand(or look into) the RTK magic going on

> Is there a better way to do this? Ideally we would need the error object from Axios for our notification middleware but actions created by createAsyncThunk seem to swallow the error and produce just the simple error message. If there is way to catch teh actual object in a middleware then this part can be even more simple

**Comment by deepu105** [comment]
Thanks to both @phryneas and @markerikson for spending time on this. really appreciate that

**Comment by deepu105** [comment]
> Sorry, I was away for most of the day. It's late by now, so I'll just answer this question - I think you already have the review from Mark :)
> 
> > I need to trigger the GET request from the same API when an update happens, I was looking for something like `onQueryCompleted` but I think that doesnt exist, probably due to the async nature of stuff. So for this API there is no custom reducer where I can add an api.endpoints.myEndpoint.matchFulfilled action matcher so what would be RTK way to trigger `getUsers` from below when `createUser` is completed?
> 
> You would use the invalidation features - see [Cached Data](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/rtk-query/usage/cached-data)
> 
> ```diff
> const userApi = createApi({
>   baseQuery: axiosBaseQuery(),
> +  tagTypes: ["User"],
>   endpoints(build) {
>     return {
>       getUsers: build.query({
>         query: ({ page, size, sort }: ISearch) => ({
>           url: `${apiUrl}${sort ? `?page=${page}&size=${size}&sort=${sort}` : ''}`,
>           method: 'GET',
>         }),
> // will be reloaded when either "User:LIST" invalidates or one of the "User:id" pairs on this page invalidates
> +       providesTags: (result) =>
> +        result
> +          ? [
> +              ...result.map(({ id }) => ({ type: 'User' as const, id })),
> +              { type: 'User', id: 'LIST' },
> +            ]
> +          : [{ type: 'User', id: 'LIST' }],
>       }),
>       getUsersAsAdmin: build.query({
>         query: ({ page, size, sort }: ISearch) => ({
>           url: `${adminUrl}${sort ? `?page=${page}&size=${size}&sort=${sort}` : ''}`,
>           method: 'GET',
>         }),
>       }),
>       getRoles: build.query({
>         query: () => ({ url: 'api/authorities', method: 'GET' }),
>       }),
>       getUser: build.query({
>         query: (id: string | number) => ({ url: `${adminUrl}/${id}`, method: 'GET' }),
> // will reload if this "User:id" pair invalidates
> +       providesTags: (result, error, arg) => [{{ type: 'User', id: arg }]
>       }),
>       createUser: build.mutation({
>         query: (user: IUser) => ({ url: adminUrl, method: 'POST', data: user }),
> // invalidates "User:LIST"
> +       invalidatesTags: (result) => [{{ type: 'User', id: 'LIST' }]
>       }),
> 
>       updateUser: build.mutation({
> // ...
> // invalidates "User:id"
> +       invalidatesTags: (result, error, arg) => [{{ type: 'User', id: arg }]
>       }),
>     };
>   },
> });
> ```
> 
> This is especially interesting when you have one API for all entity types (as we recommend, you can still split it over multiple files) and one endpoint mutation also causes query results from other entities to refetch (maybe because they somehow return combined results)

Thanks for this. Unfortunately I decided not to use RTK query. 

Another question out of curiosity, for an app with a server side DB, I would avoid client side catching like a plague so using the caching part is not a route I wanna go so what is the rationale behind catching in RTK query, when do you use it and how do you ensure you are seeing accurate data even if it has changed on the server? Btw does the catching always happen automatically? if so its a huge red flag IMO. it should be opt in as I wouldn't want my users to see catched data in a critiacl app when actual source has changed in the backend by someone else. Sorry if my understanding is just plain wrong, TBH, I havent spend time reading the docs in its entirety

**Comment by phryneas** [comment]
I think you overthink the term "caching" here. RTK Query does nothing different from what you are doing here: storing data in an in-memory variable. If you press F5, it is gone. It is not persisted for longer, it's - as Redux is, just an in-memory-cache.

What RTK-Query does essentially:
* if two components on screen use the same `useSomeQuery` with the same argument, the second one won't trigger a second request to the server, but uses data from the first
* once both unmount, after 60 seconds (configurable globally and per endpoint) that data is removed and when you later do such a query, it will be fetched again
* you can also do `const {data, isLoading} = useSomeQuery(5, { refetchOnMountOrArgChange: true })` to trigger a fetch every time this component mounts or `const {data, isLoading} = useSomeQuery(5, { refetchOnMountOrArgChange: 20 })` to trigger a refetch if this component mounts and the last request is more than 20 seconds in the past.
* you can also configure an automatic refetch of all queries on window re-focus and reconnect after disconnect
* per the mechanism I gave an example above you can declare which mutation makes which queries refetch their data
* at any point you can do a `result.refetch` or `dispatch(api.endpoints.some.initiate(5, { subscribe: false, forceRefetch: true })`

**Comment by deepu105** [comment]
ah ok, thanks for the explanation, makes more sense now. I read [this](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/usage/rtk-query/cached-data) in docs and it gave me an impression that even if I trigger a server request, this will give me catched data for same arguments, which would be bad of course as data might have changed for same argument at server side. It may be worthwhile to make this section of docs clear on what exactly the catching does

**Comment by phryneas** [comment]
> All this was my attempt to fix the issue I mentioned in the commit as below. Seems like the error object from axios is swallowed by RTK at some point and instead it returns a simple error object with just message and stack. We have some middlewares which really need all the info from the axios error, so was trying different things to see if it will work, I guess finally return thunkAPI.rejectWithValue(error); sees to work, which means I need the try catch as well, but then I didnt try removing other stuff as I really didnt understand(or look into) the RTK magic going on

Yeah, we recommend to only put serializable stuff into actions, so `cAT` cleans that up. Non-serializable values can cause problems with the devtools and certain middleware, even on actions.
Of course you could write your own `serializeError` function and pass that in as an option to preserve interesting data and strip away the rest.
Or you write a wrapper around your payload creators that abstracts that work, which is perfectly viable as well.

**Comment by deepu105** [comment]
I didn't know I could customize that, I was following [this](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/api/createAsyncThunk#handling-thunk-errors) docs to do the try catch. is there any docs on how to customize serializeError or payloadCreator? I cound't find anything on the website

**Comment by phryneas** [comment]
`serializeError` is just a function that is passed in whatever is thrown and whatever that returns is put in `action.error` of the rejected action.

"payloadCreator" is just the function you pass into `createAsycnThunk`, so I mean you could so something like

```js
const wrap = fn => (arg, api) => {
try {
  return (await fn(arg)).response
} catch (e) {
  return api.rejectWithValue(e)
}
```
(with some more handling of course)
and then

`const thunk = createAsyncThunk('foo', wrap(arg => axios.get(somethinWithArg)))`

**Comment by markerikson** [comment]
> Totally overlooked that. Been away from React/Redux for a while 😂 This means I'll have to assign each field in a new line with a `useSelector` right. that seems ugly though 😭

Another option is to import and pass the `shallowEqual` comparison function as the second arg to `useSelector`, and pick+return the actual fields that you care about, or use a memoized selector:

- https://redux.js.org/tutorials/fundamentals/part-5-ui-react#using-multiple-selectors-in-a-component
- https://redux.js.org/tutorials/fundamentals/part-7-standard-patterns#memoizing-selectors-with-createselector

**Comment by deepu105** [comment]
This was lot more work then I anticipated. I updated almost the entire react client code :wink: 

Thank you so much for answering all my questions patiently @phryneas & @markerikson 
Do let me know if you see any issues in the PR (Might be bit harder to readthrough due to all the EJS templates

**Comment by phryneas** [comment]
I left you a bit of a review, but this is already going a very nice direction :+1:

**Comment by deepu105** [comment]
@phryneas thanks for the review, I addresses all, except two of your comments, those I had some follow up questions. Let me know your thoughts on that an if required i'll fix them with new PRs

Oveall thanks for your help @markerikson & @phryneas

**Comment by phryneas** [comment]
@deepu105 looked good for me :) 
Generally, that was a review and not a requirements list - if you decide to do something differently there, that's totally okay ;)

**Comment by deepu105** [comment]
bounty claimed https://opencollective.com/generator-jhipster/expenses/42481
