### ISSUE TITLE
💥 Incorrect Object Type is being passed as parameter

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#15042]
##### **Overview of the issue**
When creating a reactive monolithic project, setting the entity as `UUID` and importing through a JDL file, the method in the `EntityRepository` interface has the incorrect object type as parameter:

```
@Override
Mono<Bank> findById(Long id);
```

instead of
```
@Override
Mono<Bank> findById(UUID id);
```

##### **Motivation for or Use Case**
This creates the wrong method signature.

##### **Reproduce the error**
1. Create an entity like 

```
entity Bank {
  id UUID,
  surrogateId Long,
	name String required minlength(3),
  phone String,
  address String,
  bic String,
  swift String,
  active Boolean
}
```
2. Import project with `jhipster import-jdl bank.jh`
3. Open `BankRepository` interface

##### **Related issues**
None that I know of.

##### **Suggest a Fix**

Change the signature using the proper object type

##### **JHipster Version(s)**
v7.0.1

##### **JHipster configuration**
  <details>
  <summary>JDL definitions</summary>
  <pre>
     {
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "myapp",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cucumber"],
    "pages": [],
    "creationTimestamp": 1621302585599,
    "serviceDiscoveryType": false,
    "reactive": true,
    "authenticationType": "oauth2",
    "packageName": "com.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "spacelab",
    "clientThemeVariant": "primary",
    "enableTranslation": false,
    "nativeLanguage": "es",
    "packageFolder": "com/facturapp",
    "clientPackageManager": "npm",
    "languages": ["en", "fr"],
    "entities": [
      "Bank"
    ],
    "lastLiquibaseTimestamp": 1621472187000
  }
}

  </pre>
  </details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
  <details>
  <summary>Entity Configuration</summary>
  <pre>
{
  "name": "Bank",
  "fields": [
    {
      "fieldName": "id",
      "fieldType": "UUID"
    },
    {
      "fieldName": "surrogateId",
      "fieldType": "Long"
    },
    {
      "fieldName": "name",
      "fieldType": "String",
      "fieldValidateRules": ["required", "minlength"],
      "fieldValidateRulesMinlength": "3"
    },
    {
      "fieldName": "phone",
      "fieldType": "String"
    },
    {
      "fieldName": "address",
      "fieldType": "String"
    },
    {
      "fieldName": "bic",
      "fieldType": "String"
    },
    {
      "fieldName": "swift",
      "fieldType": "String"
    },
    {
      "fieldName": "active",
      "fieldType": "Boolean"
    }
  ],
  "relationships": [
  ],
  "entityTableName": "bank",
  "dto": "mapstruct",
  "pagination": "pagination",
  "service": "serviceImpl",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "applications": "*",
  "changelogDate": "20210520005604"
}
  </pre>
  </details>

##### **Browsers and Operating System**

Using Windows 10 and Brave Browser

- [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by amatosg** [comment]
Also, class `EntityManager` is missing 2 methods:
```public Mono<Integer> updateLinkTable(LinkTable table, UUID entityId, Stream<UUID> referencedIds)``` and 
```public Mono<Void> deleteFromLinkTable(LinkTable table, UUID entityId)```

**Comment by atomfrede** [comment]
Looks like a bug. Here https://github.com/jhipster/generator-jhipster/blob/d6bf35800deb726ce6d231d5a475514942b5e795/generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs#L144 should be `<%= primaryKey.type %>` used instead of `Long`.

**Comment by DanielFran** [comment]
And also here:
https://github.com/jhipster/generator-jhipster/blob/d6bf35800deb726ce6d231d5a475514942b5e795/generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs#L110

**Comment by amatosg** [comment]
sure, let me take a look at it tonight

**Comment by amatosg** [comment]
https://github.com/jhipster/generator-jhipster/blob/d6bf35800deb726ce6d231d5a475514942b5e795/generators/server/templates/src/main/java/package/service/EntityManager.java.ejs#L195

https://github.com/jhipster/generator-jhipster/blob/d6bf35800deb726ce6d231d5a475514942b5e795/generators/server/templates/src/main/java/package/service/EntityManager.java.ejs#L217

So I guess those also need to be changed?

**Comment by amatosg** [comment]
@atomfrede @DanielFran I'm having trouble accessing `primaryKey` in `EntityManager.java.ejs`. Any lights on how to import that value?

**Comment by mshima** [comment]
It’s not available only default `jhipsterConfig.pkType`.
If possible you should use generics or just Object.

**Comment by amatosg** [comment]
I'm lacking the time to help with this, but I just remember about it. This bug is still present in the code :(
