### ISSUE TITLE
create custom controller

### ISSUE THREAD

**Issue by cata86** [jhipster/generator-jhipster#1504]
If I create e new controller and put it into package
BASE_PATH_PACKAGE.web.rest
It isn't accessible (404 not found), but if I put it in the root package ( BASE_PATH_PACKAGE where there is Application.java) everything works properly.

**Comment by cata86** [comment]
This is my controller:


@RequestMapping("/api")
@Controller
public class UploadController implements HandlerExceptionResolver {
	
	
		
    @RequestMapping(value = "/upload",method = RequestMethod.POST)
    public @ResponseBody String upload(@RequestParam("file") MultipartFile file,
    		 HttpServletRequest request ) throws IOException {
        .....
        ......
        .....
        return "OK";

    }
}

**Comment by gmarziou** [comment]
Shave you tried with @RestController?

**Comment by cata86** [comment]
yes, it has the same behavior.

**Comment by jdubois** [comment]
I just tried it and it works, of course...

Here's my controller:

```
@RestController
@RequestMapping("/api")
public class YoloResource {

    /**
     * GET  /yolo -> prints 'yolo'
     */
    @RequestMapping(value = "/yolo",
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    public String yolo() {
        return "yolo";
    }
}
```

I suggest you post your question on StackOverflow, this is not a JHipster issue.
