### ISSUE TITLE
Remove yarn from documentation

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#15058]
##### **Overview of the issue**

We have dropped yarn  support with JH 7. Nevertheless the documentation mentions yarn quite prominent.

##### **Motivation for or Use Case**

 Recently some issues and SO question haven related to yarn.  We should remove all things related to yarn from our documentation. Example: https://www.jhipster.tech/installation/

**Comment by avdev4j** [comment]
Unless this sentence 
> Tip: If you prefer using Yarn, you can use jhipster --yarn, to use Yarn instead of NPM.

If the rest of the documentation is still correct, no? (Yarn will use the package.json to retrieve the dependencies)

**Comment by atomfrede** [comment]
I am referring to this more or less: https://github.com/jhipster/generator-jhipster/pull/12134 We don't support yarn anymore (e.g. maven does always use npm). And yes, you are right installation is still valid. But we often mention `yarn start` etc. which is not supported anymore for the generated application.

**Comment by avdev4j** [comment]
Keep it

**Comment by avdev4j** [comment]
Keep it open

**Comment by DanielFran** [comment]
@deepu105 @pascalgrimaud bounty claimed: https://opencollective.com/generator-jhipster/expenses/157952

**Comment by pascalgrimaud** [comment]
@DanielFran : approved
