### ISSUE TITLE
Automated refactoring/migration with OpenRewrite

### ISSUE THREAD

**Issue by jkschneider** [jhipster/generator-jhipster#15068]
##### **Overview of the feature request**

[OpenRewrite](https://github.com/openrewrite/rewrite) is a style-preserving, type-aware automated source code refactoring library and set of build plugins. It allows you to define recipes that perform migrations, adopt code best practices, and repair security defects.

An initial home for JHipster-related recipes while we think about where it might live more permanently: https://github.com/openrewrite/rewrite-jhipster

##### **Motivation for**

A fundamental concern of any project generation tool is how to deal with upgrades after the initial generation, especially when users are expected to customize the generated code. To some extent, OpenRewrite will permit upgrades in previously generated code.

These updates don't have to encompass the full range of upgrades in order to generate value. For example, code that was generated with a security defect could be repaired independently of the rest of the upgrade path.

##### **Related issues or PR**

Suggest that we form a backlog of desired transformations here: https://github.com/openrewrite/rewrite-jhipster/issues. We can get started writing the first several recipes. I expect that the best practices and Spring Boot 1->2 migration recipes in [rewrite-spring](https://github.com/openrewrite/rewrite-spring) are already applicable. Best practices and JUnit 4->5 migration in [rewrite-testing-frameworks](https://github.com/openrewrite/rewrite-testing-frameworks) is also probably applicable.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Keep it

**Comment by timtebeek** [comment]
For now we had archived [openrewrite/rewrite-jhipster](https://github.com/openrewrite/rewrite-jhipster/issues), but we're certainly open to revive that if you all want to get involved there.
