### ISSUE TITLE
Support LiquiBase context functionnality

### ISSUE THREAD

**Issue by moifort** [jhipster/generator-jhipster#1507]
Hello Jhipster Team,

First, thank you for this awesome project!

Recently I encountered a (little) problem with the management of my DB with LiquiBase. I don't want to load my native data before running my tests with JUnit, for that I use the `context` functionality of LiquidBase (http://www.liquibase.org/documentation/contexts.html). 

This is an example of my changelog:

```
<changeSet id="20150521110306" author="Thibaut" context="!test">
       
     <loadData encoding="UTF-8"
                      file="config/liquibase/food.csv"
                      separator=";"
                      tableName="T_FOOD" />
           	                
</changeSet>
```

With the actual configuration it doesn't work because the LiquiBase context configuration is set by default at `development, production` in the `config/DatabaseConfiguration.java` file.

I would like to make a little pull request to support the LiquiBase context functionality. My change will be simple:
- Add a new property `context` in configuration files:
  * `src/main/resources/config/application-dev.yml`
  * `src/main/resources/config/application-prod.yml`
  * `src/test/resources/config/application.yml`
- Manage the new property and set LiquidBase context in the  `config/DatabaseConfiguration.java` file

Thibaut.

**Comment by jdubois** [comment]
Yes, this "context" property is there from the beginning, and in fact it is just wrong: I wanted to use it, and never did...
That's a very good idea, please do the PR

For the property, can you do:
```
liquibase:
    context: test
```

**Comment by moifort** [comment]
Yes, I will try this week-end :)!

**Comment by jdubois** [comment]
@moifort you could have closed it with your PR
Can you link to this ticket in your commit? So we keep track of everything

**Comment by moifort** [comment]
Sorry, and yes il will add to my commit comment!
