### ISSUE TITLE
DefinePlugin NODE_ENV conflicting values

### ISSUE THREAD

**Issue by rvong** [jhipster/generator-jhipster#15074]
##### **Overview of the issue**
On fresh generation of JHipster 7 generated by JHipster online, upon `./mvnw`
I get 
```
[INFO] WARNING in DefinePlugin
[INFO] Conflicting values for 'process.env.NODE_ENV'
```
Why is this happening and what's the fix if it's needed?

##### **Reproduce the error**

Create JHipster7 package and run `./mvnw`

##### **Browsers and Operating System**

Manjaro 20.2

sdkman jdk 11
nvm nodejs 14

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by manoj-mass** [comment]
Found this.
https://stackoverflow.com/questions/55185601/webpack-process-env-undefined-using-defineplugin-and-dotenv

**Comment by rvong** [comment]
Not sure what above bot comment means.

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/50248.

**Comment by pascalgrimaud** [comment]
@mshima : approved
