### ISSUE TITLE
Switch to Vert.x

### ISSUE THREAD

**Issue by guedressel** [jhipster/generator-jhipster#151]
Why is jhipster not running on [Vert.x](http://vertx.io/)?
Vert.x is the hippest platform out there...

**Comment by allahbaksh** [comment]
Should we try Vert.x-Web now? Given the fact that we can generate microservice we can have option to select Vert.x for creating microservice.
In my present work we trying to leverage Vert.X for file upload. The rest of the project is generated using jHipster (Zuul + App).

**Comment by mraible** [comment]
Feel free to create a module that replaces Spring Boot with Vert.x.

https://jhipster.github.io/modules/creating-a-module/

**Comment by jdubois** [comment]
I had the same discussion a few months ago about supporting Play!
Those could be some simple, no-configured database, microservices. You just need to configure Eureka and JWT.
Of course, you will lose metrics, documentation, configuration, logging.... But still I can understand the interest here, in supporting non-Spring technologies.
