### ISSUE TITLE
Missing @Override

### ISSUE THREAD

**Issue by moifort** [jhipster/generator-jhipster#1510]
I use Eclipse and I set the `@Override` annotation rule in Error when is missing. It's a very minor error, but for the user (like me), we need to put all the missing `@Override` before the project compiles. 

I propose to make a PR with the missing `@Override` on files:
- `repository/UserRepository.java`
- `security/Http401UnauthorizedEntryPoint.java`
- `security/SpringSecurityAuditorAware.java`
- `web/propertyeditors/LocaleDateTimeEditor.java`

Thibaut.

**Comment by jdubois** [comment]
I'm not using Eclipse so I didn't see that -> if that's just adding an annotation on 4 classes, yes please do a PR
