### ISSUE TITLE
If you create a new react jhipster project it and add entities it uses availity-reactstrap-validation which is deprecated

### ISSUE THREAD

**Issue by cordial** [jhipster/generator-jhipster#15127]
##### **Overview of the issue**

If you create a new react jhipster project it uses availity-reactstrap-validation which is deprecated. If we create new projects, is the only workaround to migrate all the react code manually from availity-reactstrap-validation to availity-react?

##### **Motivation for or Use Case**

Doesn't feel like a great start that I am using deprecated libraries if I create entities in a new react Jhipster app. 
##### **Reproduce the error**

1. Create JHipster app with react
2. Add entitiy
3. See availity-reactstrap-validation usage. 

##### **Suggest a Fix**

Upgrade jhipster to use availity-react or other. 

##### **JHipster Version(s)**

7.0.1

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
fengshui-manager@0.0.1-SNAPSHOT /Users/davidcarter/work/fengshuiManager
└── generator-jhipster@7.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "fengshuiManager",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1620227346794,
    "serviceDiscoveryType": "eureka",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.lime.fsm",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "mongodb",
    "buildTool": "gradle",
    "serverSideOptions": ["searchEngine:elasticsearch"],
    "websocket": false,
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/lime/fsm",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1620753169000,
    "entities": ["Partialresult", "CalcsheetResults", "Quiz"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Partialresult {
  emailAddress String required unique
  responseData Instant
  floorPlansUploaded Boolean
  houseImagesUploaded Boolean
  folderName String
}
entity CalcsheetResults {
  averageCompass String
  adjustedCompass String
  sittingAndFacing String
  outsideWaterVolume String
  fsConstructionCycle String
  totalSquareFootage String
  metalPounds String
  metalKg String
  heavyMetalKg String
}
entity Quiz {
  name String required
  emailAddress String required unique minlength(5) maxlength(50)
  houseLock String
  mountainEnergy String
  houseRemedies String
  metalRemedies String
  twoStoreyHouse String
  twoStoryHouse Boolean
  movingMetal String
  fireOrRedArea String
  redEarthArea String
}
paginate Partialresult, CalcsheetResults, Quiz with pagination
service Partialresult, CalcsheetResults, Quiz with serviceImpl

</pre>
</details>

##### **Environment and Tools**

openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36-1562)
OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

git version 2.30.1 (Apple Git-130)

node: v15.1.0

npm: 7.0.8

Docker version 20.10.6, build 370c289

docker-compose version 1.29.1, build c34c88b2

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

n/a but on a mac

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
We had a similar issue, but not much interest in fixing it. Recently we updated the [redux integration](https://github.com/jhipster/generator-jhipster/pull/15106). You're welcome to contribute the required changes, we are happy to help.

**Comment by cordial** [comment]
I wish i had the time. Doesn't this kinda mean that jhipster with react is currently pretty much unusable? The repo says don't start new projects with it, but the entity creation in JHipster uses it extensively. Is it because Angular is much more prevalent in this project as the front end of choice?

**Comment by atomfrede** [comment]
Angular is for sure the main UI and has a lot of contributors, while react has not. Maybe @deepu105 can suggest how to proceed here as you did tremendous work on the redux migration recently. I don't know much about react so hard to tell how much effort this would be.

**Comment by deepu105** [comment]
I'll look into this next

**Comment by atomfrede** [comment]
Thanks @deepu105

**Comment by deepu105** [comment]
bounty claimed https://opencollective.com/generator-jhipster/expenses/42481

**Comment by cordial** [comment]
cheers. when is this likely to get a release?

**Comment by deepu105** [comment]
When @pascalgrimaud has time :)

**Comment by pascalgrimaud** [comment]
Yes, the release should be for tomorrow, unless there are a lot of failures, detected by Daily builds, but I'm confident :)

**Comment by cordial** [comment]
cheers guys.
