### ISSUE TITLE
Create GitHub Actions to improve CI maintainability.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#15129]
##### **Overview of the feature request**

Implement custom actions to be shared between jhipster repositories.
- Implement actions locally in generator-jhispter.
- Migrate jhipster-bom to use generator-jhipster actions.
- Evaluate daily-build to use generator-jhipster actions.

##### **Motivation for or Use Case**

JHipster CI consists in:
 - 3 main repositories (generator-jhipster, jhipster-bom, daily-builds).
 - Each repository contains lots of workflows.
 - Each repository contains different scripts.
 - Many derived repositories.

Currently, to change some build process, each workflow must be updated manually to reflect the changes.

JHipster-BOM repository CI is failing, but should be identical to the generator-jhipster CI.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
cc @pascalgrimaud @DanielFran

**Comment by pascalgrimaud** [comment]
Agree with you @mshima 

When I coded this part, in the past, I tried to put everything inside shell scripts:
- to not depend on specific CI
- to be able to use the same shell scripts in different repo

Today, we have a lot of logic directly inside yml files. I think we should move logic into shell scripts. The yml files should only contain configuration (ngx, react, vue, database etc)

**Comment by mshima** [comment]
I don't think we will have many benefits from up-2-date checks.
We already have our own up-2-date using diff.

When pushing to main branch is important to run the tests due to transitive dependencies.
Would be great to have it in others branchs and personal branch if possible.

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/44491.

**Comment by pascalgrimaud** [comment]
@mshima : approved
