### ISSUE TITLE
Cypress e2e CI packaging error on copy

### ISSUE THREAD

**Issue by egvimo** [jhipster/generator-jhipster#15146]
##### **Overview of the issue**

The script for packaging and preparing for e2e is the following (`package.json`):

```json
"postci:e2e:package": "cp build/libs/*SNAPSHOT.$npm_package_config_packaging e2e.$npm_package_config_packaging"
```

If the version is something other than `*SNAPSHOT` this step is failing with `cp: cannot stat 'build/libs/*SNAPSHOT.jar': No such file or directory`.

##### **Motivation for or Use Case**

Be able to run e2e in CI for other versions than `*SNAPSHOT`.

##### **Reproduce the error**

Change the version and run e2e in CI.

##### **Suggest a Fix**

If the `SNAPSHOT` part is not necessary, I could change it to

```
cp build/libs/*.$npm_package_config_packaging e2e.$npm_package_config_packaging
```

and create a PR.

##### **JHipster Version(s)**

7.0.1

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Looks good to me. Can you provide the PR?
