### ISSUE TITLE
Joda and Java8 dates swagger model substitution

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1515]
Currently, the Joda Datetime type is correctly represented in swagger as "date-time" but a lot of useless objects are present in the model (Datetime, Chronology, DateTimeZone, ...). This is ugly and tools like swagger-codegen will generate these useless class.
As for the Joda LocalDate, it has no type mapping at all which is even worse.

This can be fixed easily by adding :
            .directModelSubstitute(org.joda.time.LocalDate.class, String.class)
            .directModelSubstitute(org.joda.time.DateTime.class, Date.class)
in SwaggerSpringMvcPlugin bean initialization.

And for Java 8 users when #1158 is implemented:
            .directModelSubstitute(java.util.LocalDate.class, String.class)
            .directModelSubstitute(java.util.LocalDateTime.class, Date.class)
            .directModelSubstitute(java.util.ZonedDatetime, Date.class)
            .directModelSubstitute(java.util.OffsetDatetime, Date.class)

So far, I have not found a way to map LocalDate to swagger "date". If someone has an idea...
Maybe when this gets fixed : https://github.com/springfox/springfox/issues/536

**Comment by jdubois** [comment]
Same issue with SpringFox, unfortunately!
