### ISSUE TITLE
MappedBy not correct when relationshipname differs from other entity name

### ISSUE THREAD

**Issue by fbab** [jhipster/generator-jhipster#1516]
I suppose the situation is a bug that is quite frustrating when starting using Jhipster (maybe we should give no choice about the name of the relationship).

I have 2 classes : Person 1 --- * Bankaccount
More info on diagram available at this URL :
http://www.plantuml.com:80/plantuml/png/Iyv9B2vM24WjAixFKwZcKb08BYdAp4jNo4lCJLMmvghbuae6gt1ApCjEJ4xEByqhGLQMd9y2KGOrGSbG8JadCpMlH4b1LrTNGSb0JqzB0QfF2SKGAuMyV90b0000

Excerpt from Bankaccount.json
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "client",
            "relationshipNameCapitalized": "Client",
            "relationshipFieldName": "client",
            "otherEntityName": "person",
            "relationshipType": "many-to-one",
            "otherEntityNameCapitalized": "Person",
            "otherEntityField": "name"

Excerpt from Person.json
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "account",
            "relationshipNameCapitalized": "Account",
            "relationshipFieldName": "account",
            "otherEntityName": "bankaccount",
            "relationshipType": "one-to-many",
            "otherEntityNameCapitalized": "Bankaccount"

When compiling the code generated (mvn test), an error is raised when running test.
The most significant is 
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.mycompany.myapp.domain.Bankaccount.person in com.mycompany.myapp.domain.Person.accounts

While waiting for an integrated solution in Jhipster, it can be solved by editing 
Observed :     @OneToMany(mappedBy = "person")
Expected : @OneToMany(mappedBy = "client")

**Comment by jdubois** [comment]
Which version are you using ?

**Comment by fbab** [comment]
Configuration :
Jhipster :  v2.11.1,
Yo :1.4.6
Npm : 2.9.1
NodeJs : v0.12.3

**Comment by jdubois** [comment]
Version 2.12.0, released yesterday, should solve jour issue, can you have a look?
:-)

**Comment by fbab** [comment]
Thx for your reply. I can't upgrade right now. I'll give it a try within next days.

**Comment by jdubois** [comment]
OK I'm closing this because I'm pretty sure this is your issue -> don't hesitate to re-open it if needed!!
