### ISSUE TITLE
Migrate react-jhipster to Jest

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#15171]
Migrate react-jhipster lib to use Jest for testing

While at it:
Migrate from enzyme to react-testing-lib
remove Karma, mocha, Chai
Update dependencies

**Comment by DanielFran** [comment]
@deepu105 @jhipster/developers  Would it be better to migrate react-jhipster library directly to generator like it was done for ng-jhipster?

**Comment by pascalgrimaud** [comment]
If I remember well, @deepu105 was against this.
I don't have any opinion on merging this or not, as I don't use React.
Merging this to generator-jhipster will make the release process easier, as I don't need to check react-jhipster for each new release.

But we can keep this project like this today, but someone must take care of releasing react-jhipster + sync with main generator-jhipster :)

**Comment by deepu105** [comment]
@DanielFran, No, this boilerplate is unnecessary for users. The angular migration was not something I ever agreed to or liked and I still think our future should be less boilerplate and not vice versa

**Comment by deepu105** [comment]
@pascalgrimaud IMO release of this lib should be seperate, whenever new features are added or bug fixes are done this lib should be releases. Its as easy as running `npm run release:patch` and a PR should be done to update version in JHipster. So that when you release JHipster you dont have to do anything

**Comment by deepu105** [comment]
bounty claimed https://opencollective.com/generator-jhipster/expenses/42481
