### ISSUE TITLE
yo jhipster:entity should have reserved keywords for existing routes

### ISSUE THREAD

**Issue by fbab** [jhipster/generator-jhipster#1517]
When running 
> yo jhipster:entity Admin
everything seems OK on the server side

But when opening the application on the browser side, the screen does not display  (only "This is your footer" with no menu).

**Comment by gmarziou** [comment]
What do you see in the browser console?

**Comment by fbab** [comment]
Thx for your reply : I only see 
This is your footer
no image, no menu, no developement label (in red, on upper left).

I renamed the entity from Admin to Administrator and run OK after that
(but took long to find the cause of the error).

**Comment by jdubois** [comment]
I guess this is because the "admin" route already exists -> we should have some "JHipster reserved keywords", like we have for Java reserved keywords.

**Comment by phouverneyuff** [comment]
@jdubois , the word "Test" should be reserved to.

**Comment by jdubois** [comment]
@phouverneyuff thanks, done at https://github.com/jhipster/generator-jhipster/commit/bd624f95ad8886e676f5e8a2ae7f65586eca7738
