### ISSUE TITLE
Option 'Clustered HTTP sessions using Hazelcast' deprecated?

### ISSUE THREAD

**Issue by Simsal** [jhipster/generator-jhipster#15184]
##### **Overview of the issue**

The documentation https://www.jhipster.tech/creating-an-app/#2 mentions the option for clustered http sessions. While generating a new app this option is not chooseable

##### **Motivation for or Use Case**

I would like to use clustered http sessions.

##### **Reproduce the error**

Create a new jhipster. The mentioned option doesn't show up.

##### **Related issues**

I created a stackoverflow question and someone mentioned that the option was last mentioned 2017.
https://stackoverflow.com/questions/67765405/clustered-http-sessions-using-hazelcast-in-jhipster-generator?noredirect=1#comment119807995_67765405

##### **Suggest a Fix**

Mark the option as deprecated/delete it from documentation or show a way to enable it

##### **JHipster Version(s)**

7.0.1

##### **Browsers and Operating System**

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
In case it helps, [this tutorial](https://developer.okta.com/blog/2020/12/14/spring-session-redis) shows how to configure a Spring Boot application to store sessions in Redis with Spring Session, so the session can be shared among multiple gateway nodes and is preserved when a node failure happens.

**Comment by deepu105** [comment]
I think we removed the option, so docs need to be updated
