### ISSUE TITLE
Unable to use word class as column name

### ISSUE THREAD

**Issue by juzerali** [jhipster/generator-jhipster#15190]
##### **Overview of the issue**

When trying to create a table with a column named `class`, jhipster fails with following error
```
>> Your field name cannot contain a Java or React reserved keyword
```

##### **Motivation for or Use Case**

[Spring Security ACL](https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/appendix-schema.html#hypersql) requires the `acl_class` table to be created with a column named `class` for the in-built `JdbcMutableAclService` to work as expected. Not being able to generate this column name will result in the user providing a custom implementation of `MutableAclService`.

##### **Suggest a Fix**

Whitelist the word `class` to be used as a column name.

##### **JHipster Version(s)**
`7.0.1`

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
The error is clear, its a reserved word, please use another word or refactor after generation
