### ISSUE TITLE
Auto cancel redundant/stale GitHub action builds

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#15205]
I noticed that the Github action builds on our repos don't auto cancel on newer commits, like it used to do on Travis and this is really clogging up our pipelines and makes the GitHub builds really slow and more over this is wasting unnecessary resources and energy overall

So we need to try one of the solution mentioned [here](https://github.community/t/is-it-possible-to-cancel-previous-jobs-automatically-when-the-pull-request-is-updated/16779/2)

- [x] Update for generator-jhipster
- [ ] Update for hipster/labs daily builds
- [x] Update for BOM project
- [ ] Update for JHipster online

**Comment by deepu105** [comment]
@pascalgrimaud do you think 300 is good bounty for this or should we make it 500?

**Comment by deepu105** [comment]
can be done along side https://github.com/jhipster/generator-jhipster/issues/15129 as well

**Comment by SudharakaP** [comment]
I'll do this over the weekend; shouldn't be difficult; but if anyone wanna take it before that feel free to. 😄

**Comment by mshima** [comment]
Last time I checked, wasn't possible, in the link you provided there are some alternatives.
I will take a look, it's holiday here today.

**Comment by pascalgrimaud** [comment]
hehe, same as @mshima 
The last time I wanted this, it was not possible. Maybe it has been improved...?

**Comment by mshima** [comment]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency should do the trick.
I in beta, but is upstream.

**Comment by deepu105** [comment]
@mshima @SudharakaP seems to have assigned this to him as well so just make sure to coordinate so that both of you dont end up doing it :)

**Comment by SudharakaP** [comment]
@mshima : I've assigned it to you. If you feel you need help or something feel free to ping me I can take a look.

**Comment by mshima** [comment]
I don't think it's worth to add this to daily builds or to jhipster online.
The number of PRs and workflows is too low.
At generator-jhipster and jhipster-bom a PR can trigger almost 40 builds.

**Comment by deepu105** [comment]
Ya those are just placeholders. Feel free to update to what you think is more applicable

**Comment by DanielFran** [comment]
> 
> 
> I don't think it's worth to add this to daily builds or to jhipster online.
> The number of PRs and workflows is too low.
> At generator-jhipster and jhipster-bom a PR can trigger almost 40 builds.

@deepu105 Following last @mshima comment can this issue be closed?

**Comment by deepu105** [comment]
Ya sure feel free to close it if you think its done

**Comment by mshima** [comment]
I will add to daily builds. Can be used for manual builds.

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/44492.

**Comment by pascalgrimaud** [comment]
@mshima : approved
