### ISSUE TITLE
"This is your footer" shows before the site is displayed properly

### ISSUE THREAD

**Issue by dereklin** [jhipster/generator-jhipster#1523]
I am new to jhipster and trying it out.  When I run java -jar jhipster-0.0.1-SNAPSHOT.war --spring.profiles.active=prod, and then go to http://127.0.0.1:8080/#/, I see "This is your footer" shows up first for a about 1 second, and then the rest of the site shows up properly.  Is this a time lag due to the angular binding?

**Comment by moifort** [comment]
Yes, normally it's the time it takes to angular to be completely loaded (js, css, ect.). Don't worry, when the navigator has already cached your webapp it's less than 1 second. If it still takes to much time, you can use the network console to analyze it (in Firefox with Firebug for example).

![capture d ecran 2015-05-24 a 22 37 04](https://cloud.githubusercontent.com/assets/4958079/7789546/733d6e24-0265-11e5-9080-5060ceabc5e8.png)

**Comment by jdubois** [comment]
It shouldn't take 1 second, or maybe you have a very very slow computer.
But this doesn't look like an issue, so I'm closing it.
