### ISSUE TITLE
Feature Request: Bootswatch themes

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1526]
Will any one be interested in having a default theme switcher on the generated app using bootswatch.

If so I can submit a PR, I have done a small directive to mimic the below function, I can integrate the same into the footer section of the generated app, so that there is a select element to choose from the list of available bootswatch themes, with the original bootstrap theme as fall back

Might not be much value once you get started fixing a theme, but will be nice to play for those who wanna try out some themes before fixing one right out of box in the generated app

http://jsbin.com/rabij/1/edit?html,js,output

**Comment by jdubois** [comment]
Yes that was my original idea at the very beginning of the project -> it's just lack of time if I didn't do it.
So yes if you have something working that would be great.

**Comment by deepu105** [comment]
:+1: will cleanup and do a PR

**Comment by deepu105** [comment]
Hi Guys, Added bootswatch support how does it look, theme can be switched directly from the menu

cyborg
----------
![image](https://cloud.githubusercontent.com/assets/1107223/7805499/192d671c-03a6-11e5-97d3-4a678d78cdb7.png)

Flatly
--------
![image](https://cloud.githubusercontent.com/assets/1107223/7805504/2d773608-03a6-11e5-9b63-07cbe8f11450.png)

**Comment by deepu105** [comment]
more screenshots
---------------

![image](https://cloud.githubusercontent.com/assets/1107223/7805539/ae7305f2-03a6-11e5-88e9-c60294790a6c.png)

![image](https://cloud.githubusercontent.com/assets/1107223/7805512/580e0784-03a6-11e5-9668-a61778cce871.png)


![image](https://cloud.githubusercontent.com/assets/1107223/7805522/79317e78-03a6-11e5-98cd-39d360f68550.png)


![image](https://cloud.githubusercontent.com/assets/1107223/7805528/850731b6-03a6-11e5-87b5-569bb945c776.png)


![image](https://cloud.githubusercontent.com/assets/1107223/7805530/8f3138e4-03a6-11e5-853a-e1081f7dd41b.png)

**Comment by gzsombor** [comment]
:+1:

**Comment by PeterEltgroth** [comment]
:+1:

**Comment by atomfrede** [comment]
Great work!

**Comment by piedrahitac** [comment]
Looking good!

I have a question, though... Should this be optional or not?

**Comment by deepu105** [comment]
not sure if its worth adding as an option all together, we were discussing about having it as a dev profile only option here https://github.com/jhipster/generator-jhipster/pull/1529

Im trying to see how to fix token auth issue and also a better way to have the theme menu, may be as a footer menu or a floating side menu

**Comment by deepu105** [comment]
changed to fix x-auth issue and moved theme switcher to footer

![image](https://cloud.githubusercontent.com/assets/1107223/7855742/991527ba-0556-11e5-8704-c44910901068.png)

**Comment by moifort** [comment]
:+1:

**Comment by jksoftpro** [comment]
:+1:

**Comment by RagnarFrunck** [comment]
:thumbsup:

**Comment by deepu105** [comment]
need to write this as a tip, but this is low priority for now

**Comment by deepu105** [comment]
This is kind of unmaintained as JHipster by default allows theme selection
during code generation. You can port the theme switcher code from this
easily as well

Thanks & Regards,
Deepu
