### ISSUE TITLE
Different templatePathFrom and templatePathTo in writeFilesToDisk() in generator-base.js

### ISSUE THREAD

**Issue by aksth** [jhipster/generator-jhipster#15273]
##### **Overview of the feature request**

Right now in `writeFilesToDisk()` of `generator-base.js`, both `templatePathFrom` and `templatePathTo` is being created using the `templatePath/blockPath` variable. This means in both the source and destination this `'templatePath'` will exist.

But what if we do not want the same directory structure as that of the template in our generated code? Are there any options right now to handle this case?

If not, can't we add a new parameter in `blockTemplate`, maybe something like `sourcePath`, and use that to manage source and destination path instead of using only `path` parameter like now?

##### **Motivation for or Use Case**

We should be able to change the directory structure of the templates in our generated code, different from the original directory structure of templates in the sub-generator.

For example, in the server sub-generator,

Let's say we want to change the directory of the `'docker'` template from `'src/main/docker'` to just `'/docker'` in the root folder when the code is generated. How to achieve this?

I tried to implement this using a blueprint, but I couldn't figure it out.
For the server sub-generator, I tried following in the files.js

```javascript
const serverFilesFromJHipster = {
  jib: [
    {
      path: 'docker/jib/',
      templates: ['entrypoint.sh']
    },
  ]
}
.........
.........
this.writeFilesToDisk(serverFilesFromJHipster, this, false, this.fetchFromInstalledJHipster('server/templates'))
```
This obviously fails because the `writeFilesToDisk()` function will calculate `templatePathFrom =  'server/templates/docker/jib/entrypoint.sh'` and `templatePathTo = '/docker/jib/entrypoint.sh'`

Here, it will not be able to find `'server/templates/docker/jib/entrypoint.sh'` because it exists in `'server/templates/src/main/docker/jib/entrypoint.sh'`

##### **Related issues or PR**

Didn't find any.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by aksth** [comment]
Closing this, as it looks like it is possible to do this:

We can omit `path` param.

```javascript
const serverFilesFromJHipster = {
  jib: [
    { 
        file: 'src/main/docker/jib/entrypoint.sh', 
        renameTo: () => 'docker/jib/entrypoint.sh'
    },
  ]
}
......
......
this.log(this.writeFilesToDisk(serverFilesFromJHipster, this, false, this.fetchFromInstalledJHipster('server/templates')));
```

**Comment by aksth** [comment]
@pascalgrimaud is this already resolved in milestone 7.1.0?

**Comment by pascalgrimaud** [comment]
No, I added this milestone automatically because the ticket was closed

**Comment by mshima** [comment]
Implemented at `writeFiles` https://github.com/jhipster/generator-jhipster/blob/0a88bb215aaf6329229fbf277ed284b4460e2b62/generators/generator-base.js#L2354.
