### ISSUE TITLE
Use Node-sass instead of compass

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1527]
Use Node-sass instead of compass as node-sass has better performance then compass and this will remove the ruby dependency for JH

Detailed discussion in below issue
https://github.com/jhipster/generator-jhipster/issues/1469#issuecomment-105192134

**Comment by deepu105** [comment]
@jdubois do you want this PR?

**Comment by piedrahitac** [comment]
@deepu105 I think this is totally worth the PR, but that's just me...

**Comment by jdubois** [comment]
@deepu105 yes that's clearly worth a PR. I'm not using this personally, but I see a lot of issues with Ruby and Compass, so if it can solve them that would be really good.
If you don't have the time to work on it, please close the issue, it has been opened for too long.

**Comment by deepu105** [comment]
I was waiting for a go ahead from you, ill work on this next week
