### ISSUE TITLE
JWT TokenProvider doesn't check if user exists or still has permissions

### ISSUE THREAD

**Issue by Evertude** [jhipster/generator-jhipster#15270]
##### **Overview of the issue**

Users with a valid JWT Token can still access the API even after the user was deleted or permissions where removed

##### **Motivation for or Use Case**

Security

##### **Reproduce the error**

Create a User
Call /api/authenticate to get a token
Delete the user or remove roles/claims
Call any api with the token from before and see that it still works

##### **Suggest a Fix**

Compare the claims with the user repository

##### **JHipster Version(s)**

7.0.1

##### **JHipster configuration**

"generator-jhipster": {
    "authenticationType": "jwt"
}

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
This is how tokens work and the usual mitigation is to configure short token duration combined with refreshing tokens. 

Comparing the  claims with the user repository is another way to do it but what would you do if roles have changed , return a 401 error so that client re-authenticates?

**Comment by atomfrede** [comment]
The default token validity is 30 minutes as it seem so maybe we can create short live token by default?

**Comment by gmarziou** [comment]
I don't remember our client's behavior on token expiration.

**Comment by pascalgrimaud** [comment]
> This is how tokens work and the usual mitigation is to configure short token duration combined with refreshing tokens.

Agree with this answer, I don't think we should change the current behavior

**Comment by deepu105** [comment]
@mraible wdyt? should we change anything here?

**Comment by mraible** [comment]
This is one of the downsides of token-based authentication. I often see a 5-minute TTL defined for tokens because of this.
