### ISSUE TITLE
MappedBy reference an unknown target entity property (bidirecional)

### ISSUE THREAD

**Issue by carlosribeiro** [jhipster/generator-jhipster#1528]
Example my json:

```
 "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "Email",
            "relationshipNameCapitalized": "Email",
            "relationshipFieldName": "email",
            "otherEntityName": "email",
            "relationshipType": "one-to-many",
            "otherEntityNameCapitalized": "Email",
            "ownerSide": false
        },
        {
            "relationshipId": 2,
            "relationshipName": "Telefone",
            "relationshipNameCapitalized": "Telefone",
            "relationshipFieldName": "telefone",
            "otherEntityName": "telefone",
            "relationshipType": "one-to-many",
            "otherEntityNameCapitalized": "Telefone",
            "ownerSide": false
        },
        {
            "relationshipId": 3,
            "relationshipName": "Morada",
            "relationshipNameCapitalized": "Morada",
            "relationshipFieldName": "morada",
            "otherEntityName": "morada",
            "relationshipType": "one-to-many",
            "otherEntityNameCapitalized": "Morada",
            "ownerSide": false
        }
    ]
...

```
Java generate based json:

```
....
   @OneToMany(mappedBy = "contacto")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<Email> emails = new HashSet<>();

    @OneToMany(mappedBy = "contacto")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<Telefone> telefones = new HashSet<>();

    @OneToMany(mappedBy = "contacto")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<Morada> moradas = new HashSet<>();
....

```

Image of diagram:
![image](https://cloud.githubusercontent.com/assets/816894/7802833/690b507a-0336-11e5-8803-bfd2ecc60540.png)

On debug generate error: 
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: pt.zzzzz.domain.Email.contacto in pt.zzzzz.domain.Contacto.emails

How to your resolve this problem?

**Comment by jdubois** [comment]
It depends on your version number.

**Comment by jdubois** [comment]
It is corrected in 2.12.0

**Comment by jdubois** [comment]
There's a new question for this when you generate

**Comment by carlosribeiro** [comment]
My version is 2.12.0

**Comment by jdubois** [comment]
Oh sorry so I'm reopening this, I'll have a closer look

**Comment by jdubois** [comment]
I've re-created your 4 entities, and it worked on the "master" branch -> I will release version 2.13.0 very soon, and the issue is not present, or at least I could not reproduce it.
There has been quite a lot of work on this part in the last weeks, so this might be the reason why I could not reproduce the issue.

If you still have the issue when 2.13.0 is released:

- Do not hesitate to re-open the issue
- If you can send your whole 4 .json files, that would be great -> if you can't send them publicly, we will find a solution

**Comment by dancancro** [comment]
I'm not sure if mine is the same problem, but I'm getting a similar error message. In my case, I have a one-to-many self-referential relationship. In particular, products can have one or more children products. The relationship file looks like this:
```
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "benefit",
            "relationshipNameCapitalized": "Benefit",
            "relationshipFieldName": "benefit",
            "otherEntityName": "benefit",
            "relationshipType": "many-to-many",
            "otherEntityNameCapitalized": "Benefit",
            "otherEntityField": "name",
            "ownerSide": true
        },
        {
            "relationshipId": 2,
            "relationshipName": "product",
            "relationshipNameCapitalized": "Product",
            "relationshipFieldName": "product",
            "otherEntityName": "product",
            "relationshipType": "one-to-many",
            "otherEntityNameCapitalized": "Product"
        },
        {
            "relationshipId": 3,
            "relationshipName": "combo",
            "relationshipNameCapitalized": "Combo",
            "relationshipFieldName": "combo",
            "otherEntityName": "product",
            "relationshipType": "many-to-many",
            "otherEntityNameCapitalized": "Product",
            "otherEntityField": "name",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String",
            "fieldNameCapitalized": "Name",
            "fieldNameUnderscored": "name",
            "fieldInJavaBeanMethod": "Name",
            "fieldValidate": true,
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "50"
        },
        {
            "fieldId": 2,
            "fieldName": "link",
            "fieldType": "String",
            "fieldNameCapitalized": "Link",
            "fieldNameUnderscored": "link",
            "fieldInJavaBeanMethod": "Link",
            "fieldValidate": false
        },
        {
            "fieldId": 3,
            "fieldName": "notes",
            "fieldType": "String",
            "fieldNameCapitalized": "Notes",
            "fieldNameUnderscored": "notes",
            "fieldInJavaBeanMethod": "Notes",
            "fieldValidate": false
        }
    ],
    "fieldsContainOwnerManyToMany": true,
    "fieldsContainOneToMany": true,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": false,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": false,
    "fieldsContainDate": false,
    "changelogDate": "20150518110853",
    "pagination": "pager",
    "validation": true
}
```

Is it possible to have one-to-many, self-referential relationships?

**Comment by jdubois** [comment]
Normally yes, and I have people next to me who do it -> I'll have a look at your code

**Comment by dancancro** [comment]
Thanks.  [Here's](https://gist.githubusercontent.com/dancancro/3c26582a7e48b2aeebad/raw/7ea80085b02eb56041a570c9109d4729af2e21f5/gistfile1.txt) the whole output, and [here's](https://gist.github.com/dancancro/1c7d1eb14f63ed05a59a) the source code.

**Comment by jdubois** [comment]
OK, I just tried it on the "master" branch and I have it working -> I will release 2.13.0 today, so you might want to try it out

One issue I see in your code is that you need a one-to-many from Product to Product, but also the other side of the relationship, so a many-to-one from Product to Product

This doesn't work perfectly, as there is one warning message and the UI is not working at 100% (there's a cyclic relationship in JSON). So this would need to be worked on, but the basic stuff is OK.

**Comment by carlosribeiro** [comment]
The problem is maintained with version 2.13.0.
Link to download compressed file with json https://www.dropbox.com/s/17hv4cua1lwzjts/files.zip?dl=0

**Comment by deepu105** [comment]
I faced this issue as well but i manually fixed it by removing the mapped by reference, not sure if its the same issue you are facing I had one-to-many self relationship. Havent yet tested if it works as expected, but it atleast cleared compilation and is building properly

**Comment by dancancro** [comment]
This is too hard. I give up.

**Comment by jdubois** [comment]
I will add a new documentation page for entity relationships. I agree this is hard.
For those who like UML, the jhipster-uml project will be another solution.

**Comment by deepu105** [comment]
Yes plz add that, it took me really a lot of trial and errors to figure out entity things, i guess lot of us would be having same problem so a detailed page on entity relationship and how to generate each relationship type would be great

**Comment by rosedo** [comment]
From what I understand, when you generate a OneToMany relationship between a Driver and his Cars, JHipster expects that the 'driver' field exists in the Car.
Removing  `mappedBy = "driver"` in the OneToMany annotation in the Driver model might fix it. This or fixing it on the other side by creating the property or relationship.
