### ISSUE TITLE
Current development version lacks semver and globby

### ISSUE THREAD

**Issue by ko5tik** [jhipster/generator-jhipster#15298]
##### **Overview of the issue**

Current development version is missing semver and globby dependencies. 

##### **Motivation for or Use Case**

Would  like to run current dfevelopment version

##### **Reproduce the error**

ko5tik@firefly ~/customer/voicecollect/jhsandbox/admin $ jhipster
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'semver'
Require stack:
- /home/ko5tik/sources/generator-jhipster/cli/jhipster.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ko5tik/sources/generator-jhipster/cli/jhipster.js:20:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/ko5tik/sources/generator-jhipster/cli/jhipster.js' ]
}

ko5tik@firefly ~/customer/voicecollect/jhsandbox/admin $ jhipster entities
INFO! Using JHipster version installed globally
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'globby'

##### **Related issues**

None found

##### **Suggest a Fix**

Following commands fix the issue:

ko5tik@firefly ~/sources/generator-jhipster $ npm install semver

added 616 packages, and audited 1039 packages in 5s

found 0 vulnerabilities
ko5tik@firefly ~/sources/generator-jhipster $ npm install globby

added 16 packages, and audited 1039 packages in 6s

found 0 vulnerabilities

##### **JHipster Version(s)**

current master

##### **JHipster configuration**
NFO! Using JHipster version installed globally
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
admin@0.0.1-SNAPSHOT /home/ko5tik/customer/voicecollect/jhsandbox/admin
└── generator-jhipster@7.0.1 -> /home/ko5tik/sources/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "clientFramework": "react",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "withAdminUi": true,
    "baseName": "admin",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "de", "fr"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["protractor", "cucumber"],
    "websocket": false,
    "packageName": "de.vc.admin",
    "packageFolder": "de/vc/admin",
    "applicationType": "gateway",
    "jhipsterVersion": "7.0.1",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": true,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1618903229192,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "entities": ["Channel", "RecordLabel", "Record", "CategoryLabel", "Node", "UserProfile", "SearchLabel", "MachineLabel", "UserGroup"],
    "lastLiquibaseTimestamp": 1618903529000,
    "openApiClients": {
      "recorder": {
        "spec": "../recorder/src/main/resources/swagger/api.yml",
        "generatorName": "spring"
      }
    }
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Channel {
  mediaType Media required
  name String unique required
  throwAwayAllowed Boolean
  threatAllowed Boolean
}
entity RecordLabel {
  name String unique required
}
entity Record {
  date Instant required
  length Long required
  throwAway Boolean
  threat Boolean
}
entity CategoryLabel {
  name String required unique
  description String required
  authorityAttach String required
}
entity Node {
  name String required
  description String
  timeToLive Long
}
entity UserProfile {
  principal String unique required
  template Boolean
  derivedFrom String
}
entity SearchLabel {
  name String required
  description String
}
entity MachineLabel {
  name String required
  value String
}
entity UserGroup {
  name String unique required
  description String
}
enum Media {
  AUDIO,
  VIDEO
}

relationship OneToMany {
  UserProfile{searchLabels(name)} to SearchLabel{userProfile}
}
relationship ManyToOne {
  RecordLabel{record} to Record
  Record{channel(name) required} to Channel
  Node{parent(name)} to Node
  UserProfile{actualNode(name)} to Node
}
relationship ManyToMany {
  Channel{nodes(name)} to Node{channels}
  CategoryLabel{record} to Record{categoryLabel}
  UserProfile{assignedNodes(name)} to Node{userProfiles}
  UserProfile{assignedCategories(name)} to CategoryLabel{userProfiles}
  UserProfile{machineLabel(name)} to MachineLabel{userProfiles}
  SearchLabel{records} to Record{searchLabels}
  MachineLabel{records} to Record{machineLabels}
  UserGroup{userProfile(principal)} to UserProfile{userGroups(name)}
  UserGroup{machineLabel(name)} to MachineLabel{userGroups}
}

microservice Channel, RecordLabel, Record, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, UserGroup with recorder
clientRootFolder Channel, RecordLabel, Record, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, UserGroup with recorder

</pre>
</details>

##### **Environment and Tools**

java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

git version 2.25.1

node: v14.16.0

npm: 7.13.0

Docker version 20.10.7, build f0df350

docker-compose version 1.29.0, build 07737305

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Browsers and Operating System**

Linux mint 20.x

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Have you tried `npm ci` at generator-jhipster folder?
Operations like link and updating the tree may need to run npm ci.

**Comment by ko5tik** [comment]
Reverted all changes, zapped package-lock.json,   run npm /  install npm ci    everything works.  
closing issue
