### ISSUE TITLE
Related entity objects are not fetched by reactive microservice

### ISSUE THREAD

**Issue by ko5tik** [jhipster/generator-jhipster#15295]
##### **Overview of the issue**

Reactive microservice  fails eager fetch of related entities objects. Thus those objects are not  displayed in detail list and also not on the edit page.  

##### **Motivation for or Use Case**

I would like to have the same functionality as non-reactive implementation

##### **Reproduce the error**

.jo-rc and entities are attached 

##### **Suggest a Fix**

In reactive  service repository implementation  does just lazy query:

    @Override
    public Mono<UserProfile> findById(Long id) {
        return createQuery(null, where("id").is(id)).one();
    }

While non-reactive implementation issued query with joined  dependencies:
    @Query(
        "select userProfile from UserProfile userProfile left join fetch userProfile.assignedNodes left join fetch userProfile.assignedCategories left join fetch userProfile.machineLabels left join fetch userProfile.userGroups where userProfile.id =:id"
    )
    Optional<UserProfile> findOneWithEagerRelationships(@Param("id") Long id);

I am not sure what is the best way to rework 

##### **JHipster Version(s)**

7.0.1

##### **JHipster Version(s)**

```
recorder@0.0.0 /home/ko5tik/customer/voicecollect/jhsandbox/recorder
└── generator-jhipster@7.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "serverPort": "8081",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "baseName": "recorder",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "packageName": "de.vc.recorder",
    "packageFolder": "de/vc/recorder",
    "applicationType": "microservice",
    "jhipsterVersion": "7.0.1",
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": true,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": false,
    "nativeLanguage": "en",
    "creationTimestamp": 1618903229235,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "entities": ["Channel", "RecordLabel", "Record", "CategoryLabel", "Node", "UserProfile", "SearchLabel", "MachineLabel", "UserGroup"],
    "lastLiquibaseTimestamp": 1618903529000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Channel {
  mediaType Media required
  name String unique required
  throwAwayAllowed Boolean
  threatAllowed Boolean
}
entity RecordLabel {
  name String unique required
}
entity Record {
  date Instant required
  length Long required
  throwAway Boolean
  threat Boolean
}
entity CategoryLabel {
  name String required unique
  description String required
  authorityAttach String required
}
entity Node {
  name String required
  description String
  timeToLive Long
}
entity UserProfile {
  principal String unique required
  template Boolean
  derivedFrom String
}
entity SearchLabel {
  name String required
  description String
}
entity MachineLabel {
  name String required
  value String
}
entity UserGroup {
  name String unique required
  description String
}
enum Media {
  AUDIO,
  VIDEO
}

relationship OneToMany {
  UserProfile{searchLabels(name)} to SearchLabel{userProfile}
}
relationship ManyToOne {
  RecordLabel{record} to Record
  Record{channel(name) required} to Channel
  Node{parent(name)} to Node
  UserProfile{actualNode(name)} to Node
}
relationship ManyToMany {
  Channel{nodes(name)} to Node{channels}
  CategoryLabel{record} to Record{categoryLabel}
  UserProfile{assignedNodes(name)} to Node{userProfiles}
  UserProfile{assignedCategories(name)} to CategoryLabel{userProfiles}
  UserProfile{machineLabel(name)} to MachineLabel{userProfiles}
  SearchLabel{records} to Record{searchLabels}
  MachineLabel{records} to Record{machineLabels}
  UserGroup{userProfile(principal)} to UserProfile{userGroups(name)}
  UserGroup{machineLabel(name)} to MachineLabel{userGroups}
}

microservice Channel, RecordLabel, Record, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, UserGroup with recorder
clientRootFolder Channel, RecordLabel, Record, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, UserGroup with recorder

</pre>
</details>

##### **Environment and Tools**

java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

git version 2.25.1

node: v14.16.0

npm: 7.13.0

Docker version 20.10.7, build f0df350

docker-compose version 1.29.0, build 07737305

##### **Browsers and Operating System**

linux mind 20.x

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Can you give a try @ko5tik ?

**Comment by ko5tik** [comment]
@Tcharl Tried it out.   Seems that dependent objects are delivered now.  Anyway, this issue is very stale  and ought to be closed
( please look into fresh pull requests instead :) )
