### ISSUE TITLE
jdl : specify sql column name for any field

### ISSUE THREAD

**Issue by veevee2** [jhipster/generator-jhipster#15297]
##### **Overview of the feature request**

Hi,
In jdl only @Id field can specify a dedicated sql column name, isn't it unfair for other fields who maybe could feel forsaken ;-).
I propose to add the same capacity so for any field, by a **_(SQL_COLUMN_NAME)_** possibility in jdl-field declaration (optional of course)

I see the fieldNameAsDatabaseColumn variable in Entity.java.ejs is ready for that, this information is not settable from the jdl.

It's possible to compensate this need after generation by manually adding necessary code in the java sources generated, but source of git-marge-erase conflict then, and work to do in each java generated class.

An example of jdl syntax : 

> entity Entity{
>   ....
>   registeringDate(REGISTERING_DATE_NAMED_RESPECTING_DBA_RULES) LocalDate
>   rate(RATE_NAMED_RESPECTING_DBA_RULES) Long
> }

Then the table will get REGISTERING_DATE_NAMED_RESPECTING_DBA_RULES and RATE_NAMED_RESPECTING_DBA_RULES columns. (in java generated sources, then in sql generated)

##### **Motivation for or Use Case**

1. You have to 'connect' the new application to an existing database, you cannot align sql column name with java entities field names (usualy sql naming conventions give eyespain).

2. You have to respect a java naming convention + a corportate/DBAs SQL naming convention.

##### **Related issues or PR**
I don't know any related issue.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
`@fieldNameAsDatabaseColumn(colum_name)` should work.
But it’s internal and we don’t have tests for it.
It’s subject to change.

**Comment by veevee2** [comment]
> `@fieldNameAsDatabaseColumn(colum_name)` works well : thank you 👍 
But not for the @Id fields.

I've anyway implemented the field(SQL_NAME) method here https://github.com/veevee2/generator-jhipster/commit/07ba76f783638b662cf995d49c70c5189051335c , this one also handle the @Id name tuning

**Comment by gothic-explorer** [comment]
Hi, not sure if this was deployed or no but I have great interest for this feature as is provides great flexibility in order to comply to client's database object naming conventions (tables & fields names). Currently i have to manually modify generated entity files and diverge a bit from JDL, with the risk of loosing manual changes after JDL import operation.

I would suggest also JDL to support case sensitivity, as field names seems to be generated in lower case.

**Comment by jperezdelafuente** [comment]
@fieldNameAsDatabaseColumn(colum_name) works well with Jhipster 8.1
But I don't know if this is still an internal feature or could be used
It is not documented in: https://www.jhipster.tech/jdl/entities-fields
I think this feature of allowing custom column names is very interesting and should be documented
