### ISSUE TITLE
Gulp build does not generate compressed index.html and hence fails in prod mode

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1530]
When Gulp is used in windows platform with Gradle as build it does not generate compressed index.html in `src/main/webapp/dist`
This causes application to fail in prod profile
Not sure if the issue exists in ios/linux and with maven (@zyst will you be able to confirm)

Config used
```
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "gulp",
    "javaVersion": "8",
    "rememberMeKey": ""
  }
}
```

**Comment by jdubois** [comment]
Gradle + Gulp + Windows you're asking for trouble :-)

**Comment by deepu105** [comment]
I guess the issue is
in `gulp.task('usemin'` there is the below line of code
 `return gulp.src([yeoman.app + '**/*.html', '!' + yeoman.app + 'bower_components/**/*.html'])`

So with `yeoman.app` set as `'src/main/webapp/` this becomes 
`'src/main/webapp/**/*.html` so index file which is in 'src/main/webapp/index.html` is skipped i guess

**Comment by deepu105** [comment]
Im no gulp expert, but if im rite about the above then it shouldnt work in any platform :confused:

**Comment by deepu105** [comment]
let me run with `return gulp.src([yeoman.app + '/*.html', '!' + yeoman.app + 'bower_components/**/*.html'])` and see

**Comment by deepu105** [comment]
@jdubois  windows+gradle+gulp I should be awarded hipster of the year then :stuck_out_tongue_winking_eye:

**Comment by Zyst** [comment]
Can confirm it's failing on Windows 7, trying with Maven as requested  by @deepu105 in chat.

**Comment by deepu105** [comment]
I guess I was wrong about the path thingy, changing to absolute path of index.html also does not generate it

**Comment by Zyst** [comment]
Confirmed it does work on Maven! 

![maven build](https://puu.sh/i0WxJ/112ff4285b.png)

Seriously mate you have to be masochistic to keep running these gradle builds.

**Comment by Zyst** [comment]
Comment: note that `/dist` still has no `index.html` 

Are you sure that's the intended functionality from a normal gulp -Pprod serve?

**Comment by Zyst** [comment]
![image](https://cloud.githubusercontent.com/assets/3832380/7808446/eb383c30-0358-11e5-8168-cb5e7773ad83.png)


Ran gulp serve after normally running server, I think gulp isn't doing the fancy stuff grunt does with the proxy injects, and just minifies content and the like. Not 100% sure.

**Comment by Zyst** [comment]
Rather, it does seem to be starting something (in 9876) but closes the task after that.

**Comment by deepu105** [comment]
If you are running in dev profile then it will work as content will be served from normal webapp folder, if gulp works with maven then it shoul work with `mvn -Pprod spring-boot:run`

**Comment by atomfrede** [comment]
OK I think I'll need a windows vm again to check what this strange operating system is doing...

**Comment by deepu105** [comment]
@atomfrede Are you sure its a platform issue? does it work in OSX? I guess it has nothing to do with gradle atleast

**Comment by atomfrede** [comment]
Not sure. I have never used the gulp build. Will try it with Linux first.

**Comment by deepu105** [comment]
@atomfrede Hi did you find anything on this? let me know if you want me to try out something in wndows

**Comment by atomfrede** [comment]
Sorry been quite busy yesterday and the day before need to watch Google I/O after work 😊 I hope I find some time on Sunday.

**Comment by atomfrede** [comment]
So I just tried ``mvn -Pprod spring-boot:run`` on my linux machine both with ``grunt`` and ``gulp``. While ``grunt`` works fine ``gulp`` just results in the attached screenshot. Both work fine in ``dev`` profile. So I guess it has nothing to do with ``gradle`` or ``windows``.

![bildschirmfoto von 2015-06-01 21-24-34](https://cloud.githubusercontent.com/assets/203401/7921267/a19ed826-08a4-11e5-94d2-0af486ee3798.png)

**Comment by deepu105** [comment]
I thought so. So gulp is skipping index.html while copying resources to the dist folder irrespective of platform.

**Comment by atomfrede** [comment]
I've found that removing
```gulp
html: [
  minifyHtml({empty: true, conditionals:true})    
],
```
Generates all html files in a minimied version. But it doesn't keep the folder structure, so they can't be found. Furthermore (after copying the files to the correct location) the glyphicons fonts could not be found. So it seems the gulp build is seriously broken at the moment.

![unbenannt](https://cloud.githubusercontent.com/assets/203401/8024086/86943f4e-0d27-11e5-82fd-01de8b2a0533.png)

**Comment by deepu105** [comment]
great timing, I was going through this issue as well

I noticed that the gulp build isnt as complete as the grunt build, lot of things seems to be missing

**Comment by deepu105** [comment]
the minifyhtml task seems to be processing the html files 

cwd:   D:\Projects\jh5
base:  D:\Projects\jh5\src\main\webapp\
path:  D:\Projects\jh5\src\main\webapp\index.html
stat:
       dev: -389331269,
       mode: 33206,
       nlink: 1,
       uid: 0,
       gid: 0,
       rdev: 0,
       blksize: undefined,
       ino: 562949954573346,
       size: 8358,
       blocks: undefined,
       atime: new Date('2015-06-07T12:32:13.833Z'),
       mtime: new Date('2015-06-07T13:20:51.490Z'),
       ctime: new Date('2015-06-07T13:20:51.490Z'),
       birthtime: new Date('2015-06-07T12:32:13.833Z')

**Comment by deepu105** [comment]
when I try removing minifyhtml alone it seems to generate correct structure, but html files arent minified

![image](https://cloud.githubusercontent.com/assets/1107223/8024176/ae824f98-0d5c-11e5-8193-d2f39638f087.png)

**Comment by deepu105** [comment]
@atomfrede I got working with another plugin, https://github.com/jonschlinkert/gulp-htmlmin

Let me know if it looks good to you, Ill test further and do a PR

```
gulp.task('usemin', function() {
    runSequence('images', 'styles', function () {
        return gulp.src([yeoman.app + '**/*.html', '!' + yeoman.app + 'bower_components/**/*.html']).
            pipe(usemin({
                css: [
                    prefix.apply(),
                    minifyCss({root: 'src/main/webapp'}),  // Replace relative paths for static resources with absolute path with root
                    'concat', // Needs to be present for minifyCss root option to work
                    rev()
                ],
                html: [
                    htmlmin({collapseWhitespace: true})//minifyHtml()
                ],
                js: [
                    ngAnnotate(),
                    uglify(),
                    'concat',
                    rev()
                ]
            })).
            pipe(gulp.dest(yeoman.dist));
    });
});
```

**Comment by deepu105** [comment]
OK tested and it works with `gulp-htmlmin`, so I guess the problem was with `gulp-minify-html`

**Comment by atomfrede** [comment]
:+1: looks good to me and works fine.

**Comment by deepu105** [comment]
Ok ill push now
