### ISSUE TITLE
yo jhipster-entity-audit command Not working 

### ISSUE THREAD

**Issue by hanenbal** [jhipster/generator-jhipster#15300]
##### **Overview of the issue**

hello . i'm having a issue in using  jhipster-entity-audit generator 

##### **Motivation for or Use Case** 
After creating my jhipster microservice 
 I installed  the  generatoe-jhipster-entity-audit  by using this command 
"npm install -g generator-jhipster-entity-audit"
and then  I installed  "yo" by using this command "npm install -g yo" .
but this command  "yo jhipster-entity-audit"  generates this error 
##### Error jhipster-entity-audit this.registerPrettierTransform is not a function . 
My jhipster version is  7.0.1, the yoman version is  4.2.0  and the generator-jhipster-entity-audit  is 3.3.0
 what shall I do ?
thanks in advance!

##### **JHipster Version(s)**
[7.0.1](url)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
The blueprint/module has not been ported jhipster 7. So unfortunately it seems not to work until this https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/166 is fixed.
