### ISSUE TITLE
Angular: Outdated templates in sort. and sort-by.directive.spec.ts.ejs?

### ISSUE THREAD

**Issue by QualiaCommunications** [jhipster/generator-jhipster#15309]
##### **Preface**
I am new to JHipster, Angular and GitHub. Please apologize and ignore the following submission if it is not a bug. 

##### **Overview of the issue**

I noticed that the following "spec" files (located in the "generators/client/templates/angular/src/test/javascript/spec/app/shared/sort/" folder) feature templates that assign the "transition" function as callback routine, although that function has been removed during the **"Fix entity pagination in Angular"** (#10959):

- sort-by.directive.spec.ts.ejs (https://github.com/jhipster/generator-jhipster/pull/13022/files, file number 170)
- sort.directive.spec.ts.ejs (https://github.com/jhipster/generator-jhipster/pull/13022/files, file number 102).

The references look like this:
`<tr <%= jhiPrefix %>Sort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="**transition**.bind(this)">`

With the "transition" function being removed, the "callback" should refer to "loadPage" instead.
E.g. like in: `<tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">`.

##### **Motivation for or Use Case**

As far as I understand, the "spec"-files are for testing. With an outdated template they may lead to tests being unsuccessful.

##### **Reproduce the error**

I do not know yet, how to run these tests or how to check, whether there are tests that might be impacted.

##### **Related issues**

The transition function seemed to be removed by "https://github.com/jhipster/generator-jhipster/pull/10959".
The "spec"-files seemed to be created during "https://github.com/jhipster/generator-jhipster/pull/13022".

##### **Suggest a Fix**

For my understanding, all references to the transition function need to be replaced by "loadPage".

##### **JHipster Version(s)**

Each version since JHipster 7.0.0.-beta.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
##### **JHipster Version(s)**

```
store-7@0.0.1-SNAPSHOT D:\Coding\Book\JHipster\e-com-app7
`-- generator-jhipster@7.0.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "store7",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["protractor"],
    "pages": [],
    "creationTimestamp": 1623100644451,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.store7",
    "serverPort": "8080",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "gradle",
    "serverSideOptions": ["websocket:spring-websocket"],
    "websocket": "spring-websocket",
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/store7",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "zh-cn", "de"],
    "entities": ["Product", "ProductCategory", "Customer", "ProductOrder", "OrderItem", "Invoice", "Shipment"],
    "lastLiquibaseTimestamp": 1623173272000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Product {
  name String required
  description String
  price BigDecimal required min(0)
  productSize Size required
  image ImageBlob
}
entity ProductCategory {
  name String required
  description String
}
entity Customer {
  firstName String required
  lastName String required
  gender Gender required
  email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)
  phone String required
  addressline1 String required
  addressline2 String required
  city String required
  country String required
}
entity ProductOrder {
  placedDate Instant required
  status OrderStatus required
  code String required
}
entity OrderItem {
  quantity Integer required min(0)
  totalPrice BigDecimal required min(0)
  status OrderItemStatus required
}
entity Invoice {
  date Instant required
  details String
  status InvoiceStatus required
  paymentMethod PaymentMethod required
  paymentDate Instant required
  paymentAccount BigDecimal required
  code String required
}
entity Shipment {
  trackingCode String
  date Instant required
  details String
}
enum Size {
  S,
  M,
  L,
  XL,
  XXL
}
enum Gender {
  MALE,
  FEMALE,
  OTHER
}
enum OrderStatus {
  COMPLETED,
  PENDING,
  CANCELLED
}
enum OrderItemStatus {
  AVAILABLE,
  OUT_OF_STOCK,
  BACK_ORDER
}
enum InvoiceStatus {
  PAID,
  ISSUED,
  CANCELLED
}
enum PaymentMethod {
  CREDIT_CARD,
  CASH_ON_DELIVERY,
  PAYPAL
}

relationship OneToOne {
  Customer{user(login) required} to User
}
relationship OneToMany {
  ProductCategory{product} to Product{productCategory(name)}
  Customer{order} to ProductOrder{customer(email) required}
  ProductOrder{orderItem} to OrderItem{order(code) required}
  ProductOrder{invoice} to Invoice{order(code) required}
  Invoice{shipment} to Shipment{invoice(code) required}
}
relationship ManyToOne {
  OrderItem{product(name) required} to Product
}

paginate Product, Customer, ProductOrder, OrderItem, Invoice, Shipment with pagination
service Product, ProductCategory, Customer, ProductOrder, OrderItem, Invoice, Shipment with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) Client VM (build 25.291-b10, mixed mode)

git version 2.24.1.windows.2

node: v14.17.0

npm: 6.14.13

Docker version 20.10.6, build 370c289

docker-compose version 1.29.1, build c34c88b2

Congratulations, JHipster execution is complete!
---
If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
    It has nothing to do with the JDL definitions.
  </pre>
  </details>
-->

##### **Browsers and Operating System**

Windows 10 Pro. The problem is not browser-related.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Do you confirm this @wmarques @kaidohallik ?

**Comment by QualiaCommunications** [comment]
@wmarques and @kaidohallik do not seem to be active at the moment. Anyone else, who can look into this?

**Comment by DanielFran** [comment]
transition is still present in https://github.com/jhipster/generator-jhipster/blob/main/generators/client/templates/angular/src/main/webapp/app/admin/user-management/list/user-management.component.ts.ejs#L108 and manage correctly the callback
