### ISSUE TITLE
Fix webflux-mariadb-gradle CI job

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#15308]
##### **Overview of the issue**

See https://github.com/jhipster/generator-jhipster/runs/2811036840?check_suite_focus=true

##### **Motivation for or Use Case**

I like WebFlux. I want its tests to pass.

**Comment by atomfrede** [comment]
I can reproduce it (but only with jdk > 13, which is not exactly what we have on ci). Let me check my fix.

**Comment by DanielFran** [comment]
@atomfrede this started after upgrading spring-boot to 2.4.7...

**Comment by atomfrede** [comment]
The issue I got was related to block hound maybe a dependency update? But to be honest can't see exactly how it is related.

**Comment by atomfrede** [comment]
Okay, need to check more, why it worked with java 11 locally.

**Comment by atomfrede** [comment]
Still working totally fine on my machine. Tests are all green.

**Comment by DanielFran** [comment]
Yes, I try to simulate the issue locally too but was not able...

**Comment by atomfrede** [comment]
it gets even more strange. This is the sample: https://github.com/atomfrede/jh-webflux-mariadb-gradle-sample. Running `npm run backend:info && npm run backend:doc:test && npm run backend:nohttp:test && npm run backend:unit:test` locally works totally fine. Doesn't run on ci https://github.com/atomfrede/jh-webflux-mariadb-gradle-sample/runs/2823735789?check_suite_focus=true

**Comment by atomfrede** [comment]
I see only the difference in jdk vendor and linux kerner:

```
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Oracle Corporation 11.0.11+9)
OS:           Linux 5.12.10-arch1-1 amd64
```

VS 

```

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Linux 5.8.0-1033-azure amd64
```

**Comment by mshima** [comment]
@atomfrede try enabling testcontainers.
https://github.com/jhipster/generator-jhipster/blob/93b9caf9a452987242efcbf24c3a957fee5cdd99/.github/workflows/webflux.yml#L136

May be a port conflict.

**Comment by atomfrede** [comment]
Will try, but wouldn't fail all tests in that case?

**Comment by mshima** [comment]
Indeed

**Comment by mshima** [comment]
The log is archived:
```
Internal Server Error

reactor.blockhound.BlockingOperationError: Blocking call! java.io.FileInputStream#readBytes
	at java.base/java.io.FileInputStream.readBytes(FileInputStream.java)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoContextWrite] :
	reactor.core.publisher.Mono.contextWrite(Mono.java:2060)
	org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.invokeWithinTransaction(TransactionAspectSupport.java:934)
Error has been observed at the following site(s):
	|_ Mono.contextWrite ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.invokeWithinTransaction(TransactionAspectSupport.java:934)
	|_ Mono.contextWrite ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.invokeWithinTransaction(TransactionAspectSupport.java:935)
	|_      Mono.flatMap ⇢ at org.springframework.web.reactive.result.method.annotation.ResponseEntityResultHandler.handleResult(ResponseEntityResultHandler.java:128)
	|_        checkpoint ⇢ Handler tech.jhipster.sample.web.rest.OperationResource#updateOperation(Long, Operation) [DispatcherHandler]
Stack trace:
		at java.base/java.io.FileInputStream.readBytes(FileInputStream.java)
		at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
		at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
		at java.base/sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424)
		at java.base/sun.security.provider.NativePRNG$RandomIO.ensureBufferValid(NativePRNG.java:526)
		at java.base/sun.security.provider.NativePRNG$RandomIO.implNextBytes(NativePRNG.java:545)
		at java.base/sun.security.provider.NativePRNG.engineNextBytes(NativePRNG.java:220)
		at java.base/java.security.SecureRandom.nextBytes(SecureRandom.java:751)
		at java.base/java.util.UUID.randomUUID(UUID.java:150)
		at org.springframework.transaction.reactive.TransactionContext.<init>(TransactionContext.java:43)
		at org.springframework.transaction.reactive.TransactionContext.<init>(TransactionContext.java:60)
```

Looks related to https://github.com/reactor/reactor-netty/issues/1550

**Comment by atomfrede** [comment]
Where did you get the logs? Still confused why it doesn't happen locally.

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/runs/2827638180
Artifacts button right up.

gradle seems to be missing https://github.com/jhipster/generator-jhipster/blob/88c0fccbc3d90402b5969ac16ddc17e780b4ec96/generators/server/templates/pom.xml.ejs#L79

**Comment by atomfrede** [comment]
Let me try.

**Comment by atomfrede** [comment]
Seems to work. https://github.com/atomfrede/jh-webflux-mariadb-gradle-sample/runs/2828443033?check_suite_focus=true Updated the PR.

**Comment by mshima** [comment]
This should fix gradle+gateway build errors in daily builds too.
@atomfrede can you switch 2 more webflux builds to gradle in main tests? There is only 1.
Don’t forget your bounty.

**Comment by atomfrede** [comment]
Will do. Thanks for the hint with the arg line.
