### ISSUE TITLE
Password reset leads to activation of user

### ISSUE THREAD

**Issue by wuethrich44** [jhipster/generator-jhipster#1532]
After a password reset of a deactivated user is the user activated.

Is this the desired behavior?

**Comment by atomfrede** [comment]
At least it is the same effect: a verified email address. That's why I coded it that way in the first place. But of course it can be changed if desired.

**Comment by wuethrich44** [comment]
Ok but I think the expected behavior of a password reset is to set a new password and not to verify an email address. In our application we activate user manually and stumble over this by accident. If we haven't test that we had a big security leak.

**Comment by atomfrede** [comment]
Yes in that case you're absolutly right (which becomes more important when jhipster has a user admin ui) . Let's wait what others are saying. If no one opposes your point I'll change it such that only activated users can reset their passwords or at least they are not activated after changing it.

**Comment by seghers** [comment]
We implemented it ourselves, allowing a reset to see the email as 'real' => activated.

It should be noted that there is a difference between a user and an email.
- user: activated, blocked, banned, ...
- email: new, verified

**Comment by jdubois** [comment]
@atomfrede yes only activated users should be able to reset their password

**Comment by atomfrede** [comment]
@jdubois Will provide a fix as soon as possible.

**Comment by wuethrich44** [comment]
:+1: Thanks
