### ISSUE TITLE
Replace puppeteer dependency/use with Okta authentication APIs in Cypress e2e tests

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#15337]
##### **Overview of the feature request**

Cypress e2e tests use puppeteer APIs and custom tasks to interactively log in. Since `Okta` authentication APIs can be leveraged for programmatic login and is a recommended Cypress approach, we shall replace `puppeteer` dependency and custom task with respective Okta APIs.

##### **Motivation for or Use Case**

One less dependency to manage, improve tests reliability with the use of APIs.

I have done a similar change in `svelte` blueprint and the same code can be leveraged here. https://github.com/jhipster/generator-jhipster-svelte/pull/495

##### **Related issues or PR**
https://github.com/jhipster/generator-jhipster/issues/12686

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Nice approach, didn't manage to leverage the api in that way before.

**Comment by vishal423** [comment]
It wasn't as easy as it's now. Had to dig deep to identify all missing parts and to hook them together 😄

**Comment by atomfrede** [comment]
:+1: Good to know, I spend some time to figured it out but failed

**Comment by mraible** [comment]
It'd be super cool to get this in the next release so Cypress with Okta is as fast as Keycloak. I'm adding a bug bounty in hopes of making it happen.

**Comment by vishal423** [comment]
I already started working on it. Most likely will create a PR tonight
