### ISSUE TITLE
Feature request to disable AuthenticationType for MicroService

### ISSUE THREAD

**Issue by ajay443** [jhipster/generator-jhipster#15342]
##### **Overview of the feature request**

Right now, you must secure the microservice by one of the protocol(like session, jwt, openid), I would like to create an generator, where I want to have `authenticationType false` type(disable the autheitcationType Generator .  This request is similar to `no database` type in generator,. 

> JDL content 

```
application {
  config {
    baseName AweseomApp,
    applicationType microservice,
    packageName com.example,
    authenticationType jwt,  // instead of jwt, let's add it as false
    prodDatabaseType postgresql
  }
  entities *
  service * with serviceClass
}

entity Cars {
   name String 
}
````
##### **Motivation for or Use Case**

We have custom Security flow, where we want to add custom security protocol on top of Jhipster generated microservice, since it generates with security, we are facing lots of code to delete it. It will be helpful, if we have just `authenticationType `  as `false`. 

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I'm not sure there will be a lot of interest from the core team to implement this. The best way to make it happen is likely to submit your own PR.

**Comment by pascalgrimaud** [comment]
You can choose JWT by default, and delete all the security part, in your generated code.

**Comment by pascalgrimaud** [comment]
Closing this as it is something we won't do right now
But I think with v8, you'll have this possibility :-)
