### ISSUE TITLE
LiquiBase files structure

### ISSUE THREAD

**Issue by moifort** [jhipster/generator-jhipster#1534]
JHipster introduced me an awesome functionality: LiquiBase. The JHipster Team and community make a really good integration of it.

But with time my LiquiBase package becames messy, like below:
![capture d ecran 2015-05-26 a 19 36 34](https://cloud.githubusercontent.com/assets/4958079/7819562/e15c5770-03e2-11e5-8948-0334411838b3.png)

## My solution
![capture d ecran 2015-05-26 a 19 54 08](https://cloud.githubusercontent.com/assets/4958079/7819306/02eea886-03e1-11e5-87ff-d0676cee45b8.png)

My file structure is based on the version of my application:
- I can find easily the modification of my DB for a specific release
- We can use `tag` functionality to rollback if something bad happen
- It's more clear and less messy

I created a new package `config.liquibase.data` with the same structure as `config.liquibase.changelog`. It contains all the data files (csv).

`master.xml`contains only references files based on the release version:
```xml
<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
    
    <include file="classpath:config/liquibase/master-0.0.1.xml" />
    <include file="classpath:config/liquibase/master-1.0.0.xml" />
    <include file="classpath:config/liquibase/master-2.0.0.xml" />
    
</databaseChangeLog>
```
`master-X.X.X` contains all the changeset of the release version:
```xml
<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">

    <include file="classpath:config/liquibase/changelog/0.0.1/00000000000000_initial_schema.xml" relativeToChangelogFile="false"/>
</databaseChangeLog>
```

ChangeSet and Data are stored in the X.X.X folder.

## Conclusion
I would like to know if you have encountered the same problem as me? what was your solution? What do you think about my solution?  

If we find a proper way we can improve JHipster generator to apply a best practice of LiquiBase files structure?

**Comment by deepu105** [comment]
I had similar issue and I was managing it manually, Liquibase is great for Dev but once the app is in production, Im bit worried about having liquibase enabled, so still thinking about disabling liquibase once application is stable and in production. I havent played with liquibase much yet, but i assume that liquibase will not overwrite existing tables and hence you would have to do manual update or drop table first, so for production I would still prefer to do it manually the classic way by having rollforward and rollback scripts. coz i dont want to end up messing up customers data

**Comment by moifort** [comment]
Thanks for your feedback @deepu105

**Comment by jdubois** [comment]
Yes that looks like a nice way of keeping the Liquibase files clean.

At the moment I don't know how we can integrate it into the generator, as we don't have the concepts of "tags", etc, even if our users use them, of course.

As I'd like people to know about it (and then maybe that will help to find a better solution, when more people use this), could you provide a "tip", like those:
https://github.com/jhipster/jhipster.github.io/pulls

I will soon make a new "user submitted tips" on the Website, with all those pages.
