### ISSUE TITLE
Failure: Monolith OAuth 2.0 (daily builds)

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#15359]
##### **Overview of the issue**

See https://github.com/hipster-labs/jhipster-daily-builds/actions/workflows/monolith-oauth2.yaml

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@atomfrede is this related to gradle 7.1.0?

**Comment by atomfrede** [comment]
I have some time later. Let me check

**Comment by atomfrede** [comment]
Looking at the issue on mobile its during Java compile while packaging which looks strange as it was compile for tests before.

**Comment by pascalgrimaud** [comment]
Thanks, I opened the ticket on mobile, so I can't give more information or give it a try

**Comment by atomfrede** [comment]
Looking into it, but I can't reproduce it wit a plain jhipster + oauth + gradle from main branch right now (no entities, will add them now).

**Comment by atomfrede** [comment]
I found something, but not sure what the reason is. I have the regular gradle enterprise meeting tomorrow, will check with Nelson. Anyways, I could reproduce it, when one task was compile with `-Pprod` while the task before was not. Not sure we should add it to main generator, would like to set `-- -Pprod` just for testing on ci. Is that easily possible?

**Comment by atomfrede** [comment]
So downgrading gradle seems to fix the issue. I will talk to Nelson what the problem could be with 7.1 and why seems to only effect the oauth build, wdyt?

**Comment by pascalgrimaud** [comment]
I'll try to have a look tomorrow morning too. So strange it's only related to OAuth2

**Comment by atomfrede** [comment]
> I'll try to have a look tomorrow morning too. So strange it's only related to OAuth2

Yes, that is totally strange as it is basically the same application

**Comment by pascalgrimaud** [comment]
In the meantime, your temp fix solved the issue, so I can achieve the release :)
Thanks a lot @atomfrede

**Comment by atomfrede** [comment]
Go ahead with the release :rocket:

**Comment by atomfrede** [comment]
Small update, during my last call with Gradle Nelson had some customers in mind which had strange problem with annotation processors, but couldn't provide a reproducer. I will look into their issue tracker if there is already something related.

**Comment by mraible** [comment]
Anything I can do to help with this?

**Comment by atomfrede** [comment]
Maybe you can reproduce it. Try upgrading to gradle 7.1 and run e.g. integrationTest and afterwarda integrationTest -Pprod. It should fail because Java compile is supposed to run again and tries to create classes via annotation processing which are already there.

**Comment by mraible** [comment]
I created a new project with [`blog-oauth2.jdl`](https://github.com/jhipster/jdl-samples/blob/main/blog-oauth2.jdl) and used Gradle instead of Maven. 

Then, I installed Gradle 7.1 using SDKMAN: `sdk install gradle 7.1`

Next, I ran `gradle integrationTest`, followed by `gradle integrationTest -Pprod`. 

I experienced no issues.

```
BUILD SUCCESSFUL in 1m 27s
11 actionable tasks: 7 executed, 4 up-to-date
Execution time: 1 min. 28 s.
```

**Comment by pascalgrimaud** [comment]
@atomfrede : plz claim the bounty for the time to reproduce this issue and investigate

**Comment by atomfrede** [comment]
Let's first see if the issue is fixed 🙂

**Comment by atomfrede** [comment]
Need to check why it seemed to work locally. Let's downgrade for now again :(
