### ISSUE TITLE
Adder and remover methods for OneToMany relationships

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1535]
It would be useful to have methods autogenerated for OneToMany relationships of the like :
public class Company implements Serializable {
...
    @OneToMany(mappedBy = "company")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<Employee> employees = new HashSet<>();
...

public void addEmployee(Employee employee) {
    employees.add(employee);
    employee.setCompany(this);
}

public void removeEmployee(Employee employee) {
    if (employees.contains(employee)) {
         employees.remove(employee);
         employee.setCompany(null);
    }
}
}
Note : this assumes that the relationship is bidirectional which is already the case since "mappedBy" is used in the relationship def.

**Comment by cbornet** [comment]
Better since we use sets : 

public boolean addEmployee(Employee employee) {
employee.setCompany(this);
return employees.add(employee);
}

public boolean removeEmployee(Employee employee) {
employee.setCompany(null);
return employees.remove(employee);
}

**Comment by jdubois** [comment]
My only issue is that I don't want to add methods that are not useful for everyone (or that should be an option).
But yes, I'm usually doing those methods, so I agree we should add them.

**Comment by jdubois** [comment]
As nobody commented on this, and I haven't seen anyone requesting this, I'm closing this issue

-> I agree this is good, as I'm using it too usually using it too, but I don't want to add too many lines of code if people don't request it

Of course, this can change in the future, it's just a matter of not enough people asking for this.
