### ISSUE TITLE
Upgrade Keycload to 14.0.x

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#15379]
##### **Overview of the feature request**

See https://www.keycloak.org/2021/06/keycloak-1400-released.html

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
Cc @vishal423

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's a pain to upgrade this

**Comment by vishal423** [comment]
Looking into it.
