### ISSUE TITLE
Upgrade to Spring Boot 2.5.1

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#15387]
##### **Overview of the feature request**

- https://spring.io/blog/2021/05/20/spring-boot-2-5-is-now-ga
- https://spring.io/blog/2021/06/10/spring-boot-2-5-1-is-now-available

This will allow us to try [Spring Native 0.10.0](https://spring.io/blog/2021/06/14/spring-native-0-10-0-available-now) for https://github.com/jhipster/generator-jhipster/issues/13733 and see if things are closer to working.

##### **Motivation for or Use Case**

I'd like to be able to compile a JHipster app to a native image.

##### **Related issues or PR**

- https://github.com/jhipster/generator-jhipster/issues/13733
- https://github.com/jhipster/jhipster-bom/pull/343

**Comment by DanielFran** [comment]
Working on it...

**Comment by jdubois** [comment]
@DanielFran I'm having a solution for Elasticsearch, but that's really complicated

**Comment by jdubois** [comment]
I started implementing is in https://github.com/jdubois/generator-jhipster/commit/25f1acb441bdd931269f773eabd06c81e1b84140 

My main blocker at the moment is that this returns a Stream of objects, so this won't work with pagination. Maybe we need to remove pagination for Elasticsearch, as it's a stream?

**Comment by DanielFran** [comment]
Closed by #15633

@jdubois do not forget to request the bounty

**Comment by jdubois** [comment]
@DanielFran you also did a big part of the work here! It's such a huge PR, it should have been $500 anyway, let me update it. -> how about you get $200 and I get $300?

**Comment by DanielFran** [comment]
Ok for me, many thanks! 👌

**Comment by jdubois** [comment]
That's normal! And I might not claim the money, but expense some stuff I need for streaming - I feel bad taking money here

**Comment by jdubois** [comment]
$300 is about 250 Euros, I'll expense the latest computer stuff I bought for that amount (cc @pascalgrimaud @deepu105 ) as at least I'll use them for JHipster

**Comment by jdubois** [comment]
Here is the expense: https://opencollective.com/generator-jhipster/expenses/46096

**Comment by pascalgrimaud** [comment]
you're too fast, not enough time to approved :)

**Comment by DanielFran** [comment]
@pascalgrimaud Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/48282
