### ISSUE TITLE
Add "application/json"  mediaType supports to patch method 

### ISSUE THREAD

**Issue by PiperDing** [jhipster/generator-jhipster#15383]
##### **Overview of the issue**

Add "application/json"  mediaType support to patch method . There is only "application/merge-patch+json" mediaType support in patch method, but client framework still use "application/json" mediaType. It case something wrong.
![image](https://user-images.githubusercontent.com/16641519/122576350-2df19680-d084-11eb-82a6-3ead4f58b915.png)
![image](https://user-images.githubusercontent.com/16641519/122578084-1b785c80-d086-11eb-9bc1-72a4274c8276.png)

##### **Motivation for or Use Case**

Many frameworks and tools still use patch method with "application/json"  even Angular

##### **Suggest a Fix**

Add  "application/json" support ,like this:
![image](https://user-images.githubusercontent.com/16641519/122578549-8e81d300-d086-11eb-9933-7a5679879c9f.png)

##### **JHipster Version(s)**
v7.0.0, v7.0.1

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by agriboss** [comment]
I also was getting a 415 error for this... Adding "application/json" as suggested to the mapping annotation worked.  I don't know if the preferred way would be to manually override the content type in angular or to do as suggested above.

**Comment by DanielFran** [comment]
@PiperDing @agriboss Would you mind contributing with a PR?

**Comment by PiperDing** [comment]
yes ，I will do it right now
