### ISSUE TITLE
Microfront End Fails To Generate Gateway

### ISSUE THREAD

**Issue by RDsideNow** [jhipster/generator-jhipster#15390]
##### **Overview of the issue**

running `jhipster jdl filename.jdl --microfrontend` generates the micro services but does not generate the gateway.  

I receive the following error

~~~
Error running generator app: TypeError: /usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular/webpack/webpack.microfrontend.js.ejs:38
    36| <%_ if (applicationTypeGateway) { _%>
    37|         remotes: {
 >> 38| <%_ for (microserviceName of Object.keys(jhipsterConfig.applications)) { _%>
    39|           '<%= microserviceName %>': `<%= microserviceName %>@${targetOptions.target !== 'serve' ? '/services/<%= microserviceName %>' : 'http://localhost:<%= jhipsterConfig.applications[microserviceName].applicationIndex + devServerBasePort %>'}/remoteEntry.js`,
    40| <%_ } _%>
    41|         },

Cannot convert undefined or null to object
TypeError: /usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular/webpack/webpack.microfrontend.js.ejs:38
    36| <%_ if (applicationTypeGateway) { _%>
    37|         remotes: {
 >> 38| <%_ for (microserviceName of Object.keys(jhipsterConfig.applications)) { _%>
    39|           '<%= microserviceName %>': `<%= microserviceName %>@${targetOptions.target !== 'serve' ? '/services/<%= microserviceName %>' : 'http://localhost:<%= jhipsterConfig.applications[microserviceName].applicationIndex + devServerBasePort %>'}/remoteEntry.js`,
    40| <%_ } _%>
    41|         },

Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at JHipsterClientGenerator.eval (eval at compile (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:37:40)
    at webpack.microfrontend.js (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:692:17)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:258:40
    at new Promise (<anonymous>)
    at tryHandleCache (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:256:14)
    at Object.exports.renderFile (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:489:10)
    at Object.renderContent (/usr/local/lib/node_modules/generator-jhipster/generators/utils.js:296:23)
    at JHipsterClientGenerator.template (/usr/local/lib/node_modules/generator-jhipster/generators/generator-base-private.js:822:26)
    at /usr/local/lib/node_modules/generator-jhipster/generators/generator-base.js:2223:47 {
  path: '/usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular/webpack/webpack.microfrontend.js.ejs'
}
ERROR! /usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular/webpack/webpack.microfrontend.js.ejs:38
    36| <%_ if (applicationTypeGateway) { _%>
    37|         remotes: {
 >> 38| <%_ for (microserviceName of Object.keys(jhipsterConfig.applications)) { _%>
    39|           '<%= microserviceName %>': `<%= microserviceName %>@${targetOptions.target !== 'serve' ? '/services/<%= microserviceName %>' : 'http://localhost:<%= jhipsterConfig.applications[microserviceName].applicationIndex + devServerBasePort %>'}/remoteEntry.js`,
    40| <%_ } _%>
    41|         },

Cannot convert undefined or null to object
TypeError: /usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular/webpack/webpack.microfrontend.js.ejs:38
    36| <%_ if (applicationTypeGateway) { _%>
    37|         remotes: {
 >> 38| <%_ for (microserviceName of Object.keys(jhipsterConfig.applications)) { _%>
    39|           '<%= microserviceName %>': `<%= microserviceName %>@${targetOptions.target !== 'serve' ? '/services/<%= microserviceName %>' : 'http://localhost:<%= jhipsterConfig.applications[microserviceName].applicationIndex + devServerBasePort %>'}/remoteEntry.js`,
    40| <%_ } _%>
    41|         },

Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at JHipsterClientGenerator.eval (eval at compile (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:37:40)
    at webpack.microfrontend.js (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:692:17)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:258:40
    at new Promise (<anonymous>)
    at tryHandleCache (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:256:14)
    at Object.exports.renderFile (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:489:10)
    at Object.renderContent (/usr/local/lib/node_modules/generator-jhipster/generators/utils.js:296:23)
    at JHipsterClientGenerator.template (/usr/local/lib/node_modules/generator-jhipster/generators/generator-base-private.js:822:26)
    at /usr/local/lib/node_modules/generator-jhipster/generators/generator-base.js:2223:47 {
~~~

##### **Motivation for or Use Case**

trying to use the new microfrontend feature

##### **Reproduce the error**

run jhipster jdl samplemicrofrontend.jh --microfrontend 

##### **Suggest a Fix**

unknown

##### **JHipster Version(s)**

7.1.0

##### **Browsers and Operating System**

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by RDsideNow** [comment]
I tried to include my jdl.  


deployment {
  deploymentType docker-compose,
  appsFolders [
  frontend,
  item,
  estimating,
  profitability
  ],
  directoryPath "../"
  dockerRepositoryName "rdsidenow",
  gatewayType zuul,
  monitoring prometheus
}

application {
  config {
        applicationType gateway,
        baseName frontend,
        packageName com.rdsidenow.frontend,
        serverPort 8080,
        serviceDiscoveryType eureka,
        authenticationType oauth2,
        cacheProvider hazelcast,
        enableHibernateCache false,
        databaseType sql,
        devDatabaseType postgresql,
        prodDatabaseType postgresql,
        enableSwaggerCodegen true,
        buildTool gradle,
        messageBroker kafka,
        clientPackageManager npm,
        testFrameworks [
          gatling,
          cucumber,
          cypress
        ],
        enableTranslation true,
        nativeLanguage en,
        languages [
          fr,
          es,
          en
        ],
        clientFramework angularX,
        jhiPrefix jhi,
        dtoSuffix DTO
        }
      entities *
}

application {
  config {
             applicationType microservice,
             baseName profitability,
             packageName com.rdsidenow.profitability,
             serverPort 8081,
             serviceDiscoveryType eureka,
             authenticationType oauth2,
             cacheProvider hazelcast,
             enableHibernateCache false,
             websocket false,
             messageBroker kafka,
             databaseType sql,
             devDatabaseType postgresql,
             prodDatabaseType postgresql,
             enableSwaggerCodegen true,
             buildTool gradle,
             clientPackageManager npm,
             testFrameworks [
               gatling,
               cucumber,
               cypress
             ],
             enableTranslation true,
             nativeLanguage en,
             languages [
               fr,
               es,
               en
             ],
             jhiPrefix jhi,
             dtoSuffix DTO,
             skipClient true,
             skipUserManagement true
         }
  entities Profitability, Transaction
}

application {
  config {
             applicationType microservice,
             baseName estimating,
             packageName com.rdsidenow.estimating,
             serverPort 8082,
             serviceDiscoveryType eureka,
             authenticationType oauth2,
             cacheProvider hazelcast,
             enableHibernateCache false,
             websocket false,
             messageBroker kafka,
             databaseType sql,
             devDatabaseType postgresql,
             prodDatabaseType postgresql,
             enableSwaggerCodegen true,
             buildTool gradle,
             clientPackageManager npm,
             testFrameworks [
               gatling,
               cucumber,
               cypress
             ],
             enableTranslation true,
             nativeLanguage en,
             languages [
               fr,
               es,
               en
             ],
             jhiPrefix jhi,
             dtoSuffix DTO,
             skipClient true,
             skipUserManagement true
         }
  entities Estimate, EstimateLineItem, EstimateItem
}

application {
  config {
             applicationType microservice,
             baseName item,
             packageName com.rdsidenow.item,
             serverPort 8083,
             serviceDiscoveryType eureka,
             authenticationType oauth2,
             cacheProvider hazelcast,
             enableHibernateCache false,
             websocket false,
             messageBroker kafka,
             databaseType sql,
             devDatabaseType postgresql,
             prodDatabaseType postgresql,
             enableSwaggerCodegen true,
             buildTool gradle,
             clientPackageManager npm,
             testFrameworks [
               gatling,
               cucumber,
               cypress
             ],
             enableTranslation true,
             nativeLanguage en,
             languages [
               fr,
               es,
               en
             ],
             jhiPrefix jhi,
             dtoSuffix DTO,
             skipClient true,
             skipUserManagement true
         }
  entities ServiceOption, FeeOption
}

entity Profitability {
	orderId String unique required,
    estBillTotal Long,
    estInvoiceTotal Long,
    billPaymentTotal Long,
    invoicePaymentTotal Long,
    estNetAmount Long,
    actNetAmount Long,
    profitable Boolean
}

entity Transaction {
	orderId String required,
    invoiceId String ,
    billId String ,
	transactionType TransactionType,
    amount Long
}

enum TransactionType {
	BILL_ESTIMATE,
    INVOICE_ESTIMATE,
    BILL_PAYMENT,
    INVOICE_PAYMENT
}

entity Estimate {
    orderId String required,
    type EstimateType required,
    status EstimateStatus required,
    addTax Boolean,
    taxRate Integer min (0) max(100),
    subTotal Integer required,
    taxAmount Integer required,
    total Integer required
}

enum EstimateStatus {
	OPEN,
    CLOSED,
    VOID
}

enum EstimateType {
	INVOICE,
    BILL
}

entity EstimateLineItem {
    unitPrice Long required,
    unit EstimateUnitType required,
    quantity Long required,
    discountQuantity Long required,
    addTax Boolean,
	limitType EstimateLimitType required,
    limitValue Long required,
    taxRate Long min (0) max(100),
    subTotal Long required,
    taxAmount Long required,
    total Long required
}

enum EstimateLimitType {
	MILES,
    DOLLARS
}

entity EstimateItem {
	name String unique required,
    rate Long required,
    discountQuantity Long,
    minQuantity Long,
    serviceOptionId String,
    feeOptionId String,
    unit EstimateUnitType required,
    isActive Boolean,
    deactivationDate Instant,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

enum EstimateUnitType {
	FLAT,
	PER_GALLON,
	PER_HOUR,
    PER_MILE,
    PER_DAY
}

entity ServiceOption {
	name String unique required,
    groupType ServiceGroupType required,
    serviceType BasicServiceType required,
    unit ServiceUnitType required,
    vehicleClass ServiceVehicleClass required,
    rate Long required,
    minQuantity Long,
    deactivationDate Instant,
    isActive Boolean,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

enum ServiceGroupType {
	NON_SALVAGE,
    SALVAGE
}

enum BasicServiceType {
	TOW,
    BATTERY,
    FLUID_DELIVERY,
    RIDE_SHARE,
    LOCKOUT,
    LOCKSMITH,
    WINCH_OUT,
    TIRE_CHANGE
}

enum ServiceVehicleClass {
	LIGHT,
    MEDIUM,
    HEAVY,
    CYCLE
}

enum ServiceUnitType {
	FLAT,
	PER_HOUR
}

entity FeeOption {
	name String unique required,
    feeType BasicFeeType required,
    unit FeeUnitType required,
    rate Long required,
    discountQuantity Long,
    minQuantity Long,
    isActive Boolean,
    deactivationDate Instant,
    createdBy String,
    createdOn Instant,
    updatedBy String,
    updatedOn Instant
}

enum FeeUnitType {
	FLAT,
	PER_GALLON,
	PER_HOUR,
    PER_MILE,
    PER_DAY
}

enum BasicFeeType {
    FUEL,
    PREMIUM,
    CANCELLATION,
    CREDIT_CARD_PROCESSING,
    CLEAN_UP,
    FUEL_SURCHARGE,
    IDLE_TIME,
    MILES_TO_DESTINATION,
    MILES_TO_ORIGIN,
    RETURN_MILES,
    WINCHING,
    LABOR,
    STORAGE
}

relationship OneToMany {
	Estimate to EstimateLineItem{estimate required}
}

relationship ManyToOne {
    EstimateLineItem{estimateItem(name)} to EstimateItem
}
paginate * with pagination
dto * with mapstruct
filter *

**Comment by mshima** [comment]
Your jdl is missing microservice definition:
https://github.com/jhipster/generator-jhipster/blob/18423dea1f344599bdd2924a49f31df9ee0236fa/test-integration/jdl-samples/blog-store-microfrontend/blog-store.jdl#L90

This is used to point the entity to a microservice, otherwise the entity should have backend and frontend in the gateway.

**Comment by RDsideNow** [comment]
@mshima thanks that worked.  I got the gateway started, but am now running into this error when selecting an entity link from the list of entities.

Thoughts what i am doing wrong here?

core.js:6456 ERROR Error: Uncaught (in promise): ScriptExternalLoadError: Loading script failed.
(error: http://localhost:4203/remoteEntry.js)
while loading "./fee-option" from 6793
ScriptExternalLoadError: Loading script failed.
(error: http://localhost:4203/remoteEntry.js)
    at Object.6793 (remoteEntry.js":1)
    at __webpack_require__ (bootstrap:19)
    at initExternal (sharing:27)
    at Function.__webpack_require__.I (sharing:57)
    at consumes:76
    at Object.5910 (consumes:122)
    at consumes:197
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.f.consumes (consumes:180)
    at ensure chunk:6
    at resolvePromise (zone.js:1255)
    at resolvePromise (zone.js:1209)
    at zone.js:1321
    at ZoneDelegate.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:28661)
    at ZoneDelegate.invokeTask (zone.js:433)
    at Zone.runTask (zone.js:205)
    at drainMicroTaskQueue (zone.js:620)
    at ZoneTask.invokeTask [as invoke] (zone.js:520)
    at invokeTask (zone.js:1656)

**Comment by mshima** [comment]
You should try to load an entity with simple names without '-', if works, may be a bug with those.
The ci test use case uses very simple names.

**Comment by RDsideNow** [comment]
@mshima i tried with simple names without the '-', but getting the same error.  I am using NPM start to start the gateway.  Does it matter if i use NPM start vs ng serve?  

(error: http://localhost:4201/remoteEntry.js) this seems odd to me but i am not super skilled but my proxy is localhost:4200.  Shouldnt the redirect be to http://localhost:4200/remoteEntry.js ?

core.js:6456 ERROR Error: Uncaught (in promise): ScriptExternalLoadError: Loading script failed.
(error: http://localhost:4201/remoteEntry.js)
while loading "./transaction" from 9121
ScriptExternalLoadError: Loading script failed.
(error: http://localhost:4201/remoteEntry.js)
    at Object.9121 (remoteEntry.js":1)
    at __webpack_require__ (bootstrap:19)
    at initExternal (sharing:27)
    at Function.__webpack_require__.I (sharing:56)
    at consumes:76
    at Object.5910 (consumes:122)
    at consumes:197
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.f.consumes (consumes:180)
    at ensure chunk:6
    at resolvePromise (zone.js:1255)
    at resolvePromise (zone.js:1209)
    at zone.js:1321
    at ZoneDelegate.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:28661)
    at ZoneDelegate.invokeTask (zone.js:433)
    at Zone.runTask (zone.js:205)
    at drainMicroTaskQueue (zone.js:620)
    at ZoneTask.invokeTask (zone.js:520)
    at ZoneTask.invoke (zone.js:505)

**Comment by mshima** [comment]
Have you started the dev server on the microservice side?

**Comment by RDsideNow** [comment]
I think so. I'm using docker-compose and the container shows the services are running.

**Comment by RDsideNow** [comment]
@mshima looks like non simple entity names (entity names broken up by a '-') still produce the error.

**Comment by mshima** [comment]
You must run npm start in every project.

**Comment by RDsideNow** [comment]
@mshima should the links work for non simple names (where there is a '-' entity name)

**Comment by mshima** [comment]
I've changed one CI entity to composite name (Camelcase) and CI succeeded.
jest and cypress worked. It's not reproducible on CI.

**Comment by RDsideNow** [comment]
Thanks again for all the help @mshima.  

One final question.  For the entities in camel case, should all of the text be prefixed like this?

<img width="1680" alt="Screen Shot 2021-06-22 at 12 00 37 AM" src="https://user-images.githubusercontent.com/42190464/122861152-f2a5d080-d2ec-11eb-9b5e-d3781072a409.png">

**Comment by mshima** [comment]
It’s failing to load translation.
Translation support needs improvement.
