### ISSUE TITLE
Generation of a new angular monolithic project with 7.1.0 is almost 2x slower than 7.0.1

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#15399]
##### **Overview of the issue**

I have consistently observed the generation of a new project (specific to npm dependencies installation of `angular`) to be around 2x slower than the previous released version.

##### **Motivation for or Use Case**

I am not sure if this is an intended behavior. Feel free to close the issue in that case.

##### **Reproduce the error**

Logs with `7.0.1` version:
```

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN bootstrap@4.6.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.6.0 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-eslint/eslint-plugin@2.0.2 requires a peer of eslint-plugin-import@* but none is installed. You must install peer dependencies yourself.
npm WARN @angular-eslint/eslint-plugin@2.0.2 requires a peer of eslint-plugin-jsdoc@* but none is installed. You must install peer dependencies yourself.
npm WARN @angular-eslint/eslint-plugin@2.0.2 requires a peer of eslint-plugin-prefer-arrow@* but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

added 1807 packages from 844 contributors, updated 2 packages and audited 2456 packages in 148.688s
```

Logs with `7.1.0` version

```sh
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.                                                                                 
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.                                                                                                                                                                                         
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.                                                                                                                                                                                         
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.                                                                                                                                                                                         
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.                                                                                                                                                                                         
npm WARN deprecated intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser                               
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.                                                                                                                                                                                         
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 2198 packages, and audited 3244 packages in 5m

```

##### **JHipster configuration**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1624128892049,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"],
    "cypressCoverage": false
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment Corretto-11.0.11.9.1 (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.11.9.1 (build 11.0.11+9-LTS, mixed mode)

git version 2.25.1

node: v14.15.4

npm: 6.14.10

Docker version 20.10.7, build f0df350

docker-compose version 1.29.2, build 5becea4c

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Version 7.0.1 uses globally installed npm. Version 6.14.10?
Version 7.1.0 uses a local version of npm 7.18.1.

Is related?

**Comment by vishal423** [comment]
I haven't specifically updated the `npm` on my machine, so, whatever version comes as default with `node` binary is the default. If you imply that the bump in the global npm version should resolve this issue, then, I haven't tried that. Do you have some references for that?

**Comment by mshima** [comment]
> If you imply that the bump in the global npm version should resolve this issue, then, I haven't tried that.

No, it can take longer, npm 7 may be slower.
But install time can change with cache hit, network calls, maybe audit man make slower.

But in ci, npm install is taking the same 1m with [7.1.0 with npm 7.18.1](https://github.com/jhipster/generator-jhipster/runs/2858576104) and [7.0.1 with npm 7.8.0](https://github.com/jhipster/generator-jhipster/runs/2254468648).

**Comment by vishal423** [comment]
Yeah, I noticed the CI behavior. I suspect the issue is somewhat related to npm cache. Before we go in that direction, I want to make sure that the issue is not scoped to my setup. Can you share timings for your local setup?

**Comment by mshima** [comment]
Executed several times:
`cd ..; rm -rf test_npm; mkdir test_npm; cd test_npm; npx generator-jhipster@7.1.0 jdl default`

npm takes 48-53s with cold cache and 21-25s with warm cache.
cache seems to become cold in a few minutes.

With npm@^6 installed globally
`cd ..; rm -rf test_npm; mkdir test_npm; cd test_npm; npx generator-jhipster@7.0.1 jdl default`
npm ranges from 35s to 40s.

**Comment by vishal423** [comment]
Yesterday, I tried [`7.1.0`](https://github.com/jhipster/generator-jhipster-svelte/runs/2879040933?check_suite_focus=true) integration in the `svelte` blueprint (with default `node` and `npm` versions), and can see overall 15-30s+ slowness in the application generation step. I am still looking at 10s+ slowness during the npm package installation step. It's not as bad as on my local system, and that's probably due to h/w and n/w connectivity differences.

Do we have any flag to revert to the old behavior?

**Comment by vishal423** [comment]
For the moment, I override the wrapper in `svelte` and things are back to their old state. Feel free to close the issue if nothing can be done/improved on the generator side.

**Comment by mraible** [comment]
Is this something that could use a bug bounty to fix?

**Comment by mshima** [comment]
@vishal423 I don’t see any benefits in doing that.
While the generation can be faster, first time .mvnw is called it will recreate the lock file using npm7 and take a long time instead of 2-5s.

IMO the only fix is to check if the build tool is maven or undefined, instead of just different than gradle.
So blueprints that don’t use neither maven and gradle, won’t fail.
So no bounty is required for this bug.

**Comment by vishal423** [comment]
As I said before, I haven't debugged why do we observe this slowness. I have a constrained WSL2 setup and such things do affect a lot. 

 In CI, for the second `./mvnw` I don't see any obvious variations (before and after override). To me, the initial boost is enough to move away. If you compare time to generate a new application with `gradle` [~80s](https://github.com/jhipster/generator-jhipster-svelte/runs/2891667589?check_suite_focus=true) (without override) and `maven` [~38s](https://github.com/jhipster/generator-jhipster-svelte/runs/2891667558?check_suite_focus=true) (with override), then, it's ~ `1.5x - 2x` in CI

**Comment by vishal423** [comment]
I think we can close as node 16.x is now available with npm 8.x as default in CI and most of the packages are now migrated to the new lock version.
