### ISSUE TITLE
Add more field data types in entity generation

### ISSUE THREAD

**Issue by malikhan5049** [jhipster/generator-jhipster#1540]
Hi,

recently i faced an issue i was trying to created an entity to store images and and there isnt relevant data type (byte[]/blob) exists currently in generator.

**Comment by jdubois** [comment]
Yes, I agree.

I'm not keeping this issue opened, as this is a never-ending story -> we already have one ticket for "enum", we might indeed have a new one for "blob".

Then it will never end, we will always need to add new types, of course.
