### ISSUE TITLE
Cleanup vue webpack config.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#15403]
##### **Overview of the issue**

While doing some changes to vue webpack at https://github.com/jhipster/generator-jhipster/pull/15210 and failing, discovered that vue webpack config needs a cleanup.
- Angular config uses 2 files, react uses 5, while vue uses 9.
- Some configs are never used and are misleading, eg:
https://github.com/jhipster/generator-jhipster/blob/1e42b520cdc8328cc7c96c09c9ecae65824f049d/generators/client/templates/vue/webpack/env.js.ejs#L15-L16
- Some implementations are wrong.
process.env.NODE_ENV is never set at this point.
https://github.com/jhipster/generator-jhipster/blob/1e42b520cdc8328cc7c96c09c9ecae65824f049d/generators/client/templates/vue/webpack/loader.conf.js.ejs#L4
- Use of process.env should be avoided https://github.com/webpack/changelog-v5/blob/master/MIGRATION%20GUIDE.md#level-5-runtime-errors, but some lib still requires it, need to track.
https://github.com/jhipster/generator-jhipster/blob/1e42b520cdc8328cc7c96c09c9ecae65824f049d/generators/client/templates/vue/webpack/webpack.common.js.ejs#L123

I have a partial implementation splited from https://github.com/jhipster/generator-jhipster/pull/15210, but it needs more work.

##### **Motivation for or Use Case**

Current config files are complicated and changes doesn't applies.

##### **Related issues**

Related to https://github.com/jhipster/generator-jhipster/pull/15210 and https://github.com/jhipster/generator-jhipster/pull/15107

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
It's not a bug, as currently it works.
I changed to enhancement and added a bounty on this

**Comment by mshima** [comment]
Keep open
