### ISSUE TITLE
Investigate Ionic CI with OAuth Gateway

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#15423]
##### **Overview of the issue**

The CI process for Ionic for JHipster has been struggling with gateway builds for a couple of weeks. Investigate and fix so CI passes consistently.

For example: https://github.com/oktadev/generator-jhipster-ionic/runs/2877557260?check_suite_focus=true

##### **Motivation for or Use Case**

There might be an issue with using a gateway as a resource server that we're unaware of. 

##### **Reproduce the error**

This is what the CI job does:

1. Creates a gateway with [`gateway-oauth2.jdl`](https://github.com/oktadev/generator-jhipster-ionic/blob/main/test-integration/jdl/gateway-oauth2.jdl)
2. Generates an Ionic app with `yo jhipster-ionic`
3. Imports the JDL from the gateway using `yo jhipster-ionic:import-jdl ../gateway/gateway-oauth2.jdl`
4. Starts the gateway and runs `npm run e2e` in the Ionic project

**Comment by vishal423** [comment]
I tried the steps locally, and the protractor tests seem to work intermittently. I think the issue is with the protractor test suite.

**Comment by mraible** [comment]
Maybe it'd be better to [migrate to Cypress](https://docs.cypress.io/guides/migrating-to-cypress/protractor)?

**Comment by mraible** [comment]
Closing since CI for Ionic for JHipster has been stable lately. https://github.com/oktadev/generator-jhipster-ionic/actions
