### ISSUE TITLE
deploy and start jhipster (react) project on tomcat server

### ISSUE THREAD

**Issue by hadimoradi1994** [jhipster/generator-jhipster#15434]
##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by swarajsaaj** [comment]
From the title, it seems you want to run a jhipster app with react frontend on standalone tomcat, instructions for creating a WAR are available at https://www.jhipster.tech/production/
If that's not what is expected, please add some description to the issue.

**Comment by hadimoradi1994** [comment]
I have created war file of project successfully and deployed on tomcat server, but when I want to run this war file got this exception on tomcat server <"org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]">

**Comment by hadimoradi1994** [comment]
> 
> 
> From the title, it seems you want to run a jhipster app with react frontend on standalone tomcat, instructions for creating a WAR are available at https://www.jhipster.tech/production/
> If that's not what is expected, please add some description to the issue.

I have created war file of project successfully and deployed on tomcat server, but when I want to run this war file got this exception on tomcat server <"org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]">

**Comment by pascalgrimaud** [comment]
Plz, fill the template with all information, @hadimoradi1994

**Comment by mraible** [comment]
No response, closing.
