### ISSUE TITLE
Links value in pagination link header is incorrect.

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#15446]
##### **Overview of the issue**
As the title says.
![image](https://user-images.githubusercontent.com/5289123/123058361-c1351e00-d42e-11eb-9be8-5b130bd48e07.png)

##### **Motivation for or Use Case**

The links of `next,prev,last`  are incorrect and link value for `first` is empty

##### **Reproduce the error**

1. Create a monolithic app
2. Create an entity with pagination (sort & header) 
3. Add at least 200 records(you can replace the provided faker csv before starting the app)
4. Start the app, goto entity listing page
5. Open dev tools & check the request by clicking the various page number

<details>
<summary>an_entity.csv</summary>
<pre>
id;afield
1;AI Shoes Awesome
2;Maine
3;Avon Tactics
4;Web
5;Gloves
6;schemas solution Health
7;Assistant
8;Chief 24/365
9;Chair eco-centric
10;Movies Architect matrix
11;AI Shoes Awesome
12;Maine
13;Avon Tactics
14;Web
15;Gloves
16;schemas solution Health
17;Assistant
18;Chief 24/366
19;AI Shoes Awesome
20;Maine
21;Avon Tactics
22;Web
23;Gloves
24;schemas solution Health
25;Assistant
26;Chief 24/366
27;Chair eco-centric
28;AI Shoes Awesome
29;Maine
30;Avon Tactics
31;Web
32;Gloves
33;schemas solution Health
34;Assistant
35;Chief 24/366
36;Chair eco-centric
37;Movies Architect matrix
38;AI Shoes Awesome
39;Maine
40;Avon Tactics
41;Web
42;Gloves
43;schemas solution Health
44;Assistant
45;Chief 24/367
46;AI Shoes Awesome
47;Maine
48;Avon Tactics
49;Web
50;Gloves
51;schemas solution Health
52;Assistant
53;Chief 24/367
54;Chair eco-centric
55;AI Shoes Awesome
56;Maine
57;Avon Tactics
58;Web
59;Gloves
60;schemas solution Health
61;Assistant
62;Chief 24/367
63;Chair eco-centric
64;Movies Architect matrix
65;AI Shoes Awesome
66;Maine
67;Avon Tactics
68;Web
69;Gloves
70;schemas solution Health
71;Assistant
72;Chief 24/368
73;AI Shoes Awesome
74;Maine
75;Avon Tactics
76;Web
77;Gloves
78;schemas solution Health
79;Assistant
80;Chief 24/368
81;Chair eco-centric
82;AI Shoes Awesome
83;Maine
84;Avon Tactics
85;Web
86;Gloves
87;schemas solution Health
88;Assistant
89;Chief 24/368
90;Chair eco-centric
91;Movies Architect matrix
92;AI Shoes Awesome
93;Maine
94;Avon Tactics
95;Web
96;Gloves
97;schemas solution Health
98;Assistant
99;Chief 24/369
100;AI Shoes Awesome
101;Maine
102;Avon Tactics
103;Web
104;Gloves
105;schemas solution Health
106;Assistant
107;Chief 24/369
108;Chair eco-centric
109;AI Shoes Awesome
110;Maine
111;Avon Tactics
112;Web
113;Gloves
114;schemas solution Health
115;Assistant
116;Chief 24/369
117;Chair eco-centric
118;Movies Architect matrix
119;AI Shoes Awesome
120;Maine
121;Avon Tactics
122;Web
123;Gloves
124;schemas solution Health
125;Assistant
126;Chief 24/370
127;AI Shoes Awesome
128;Maine
129;Avon Tactics
130;Web
131;Gloves
132;schemas solution Health
133;Assistant
134;Chief 24/370
135;Chair eco-centric
136;AI Shoes Awesome
137;Maine
138;Avon Tactics
139;Web
140;Gloves
141;schemas solution Health
142;Assistant
143;Chief 24/370
144;Chair eco-centric
145;Movies Architect matrix
146;AI Shoes Awesome
147;Maine
148;Avon Tactics
149;Web
150;Gloves
151;schemas solution Health
152;Assistant
153;Chief 24/371
154;AI Shoes Awesome
155;Maine
156;Avon Tactics
157;Web
158;Gloves
159;schemas solution Health
160;Assistant
161;Chief 24/371
162;Chair eco-centric
163;AI Shoes Awesome
164;Maine
165;Avon Tactics
166;Web
167;Gloves
168;schemas solution Health
169;Assistant
170;Chief 24/371
171;Chair eco-centric
172;Movies Architect matrix
173;AI Shoes Awesome
174;Maine
175;Avon Tactics
176;Web
177;Gloves
178;schemas solution Health
179;Assistant
180;Chief 24/372
181;AI Shoes Awesome
182;Maine
183;Avon Tactics
184;Web
185;Gloves
186;schemas solution Health
187;Assistant
188;Chief 24/372
189;Chair eco-centric
190;AI Shoes Awesome
191;Maine
192;Avon Tactics
193;Web
194;Gloves
195;schemas solution Health
196;Assistant
197;Chief 24/372
198;Chair eco-centric
199;Movies Architect matrix
200;AI Shoes Awesome
201;Maine
202;Avon Tactics
203;Web
204;Gloves
205;schemas solution Health
206;Assistant
207;Chief 24/373
208;AI Shoes Awesome
209;Maine
210;Avon Tactics
211;Web
212;Gloves
213;schemas solution Health
214;Assistant
215;Chief 24/373
216;Chair eco-centric
217;AI Shoes Awesome
218;Maine
219;Avon Tactics
220;Web
221;Gloves
222;schemas solution Health
223;Assistant
224;Chief 24/373
225;Chair eco-centric
226;Movies Architect matrix
227;AI Shoes Awesome
228;Maine
229;Avon Tactics
230;Web
231;Gloves
232;schemas solution Health
233;Assistant
234;Chief 24/374
235;AI Shoes Awesome
236;Maine
237;Avon Tactics
238;Web
239;Gloves
240;schemas solution Health
241;Assistant
242;Chief 24/374
243;Chair eco-centric
244;AI Shoes Awesome
245;Maine
246;Avon Tactics
247;Web
248;Gloves
249;schemas solution Health
250;Assistant
251;Chief 24/374
252;Chair eco-centric
253;Movies Architect matrix
254;AI Shoes Awesome
255;Maine
256;Avon Tactics
257;Web
258;Gloves
259;schemas solution Health
260;Assistant
261;Chief 24/375
262;AI Shoes Awesome
263;Maine
264;Avon Tactics
265;Web
266;Gloves
267;schemas solution Health
268;Assistant
269;Chief 24/375
270;Chair eco-centric
271;AI Shoes Awesome
272;Maine
273;Avon Tactics
274;Web
275;Gloves
276;schemas solution Health
277;Assistant
278;Chief 24/375
279;Chair eco-centric
280;Movies Architect matrix
281;AI Shoes Awesome
282;Maine
283;Avon Tactics
284;Web
285;Gloves
286;schemas solution Health
287;Assistant
288;Chief 24/376
289;AI Shoes Awesome
290;Maine
291;Avon Tactics
292;Web
293;Gloves
294;schemas solution Health
295;Assistant
296;Chief 24/376
297;Chair eco-centric
298;AI Shoes Awesome
299;Maine
300;Avon Tactics
301;Web
302;Gloves
303;schemas solution Health
304;Assistant
305;Chief 24/376
306;Chair eco-centric
307;Movies Architect matrix
308;AI Shoes Awesome
309;Maine
310;Avon Tactics
311;Web
312;Gloves
313;schemas solution Health
314;Assistant
315;Chief 24/377
316;AI Shoes Awesome
317;Maine
318;Avon Tactics
319;Web
320;Gloves
321;schemas solution Health
322;Assistant
323;Chief 24/377
324;Chair eco-centric
325;AI Shoes Awesome
326;Maine
327;Avon Tactics
328;Web
329;Gloves
330;schemas solution Health
331;Assistant
332;Chief 24/377
333;Chair eco-centric
334;Movies Architect matrix
335;AI Shoes Awesome
336;Maine
337;Avon Tactics
338;Web
339;Gloves
340;schemas solution Health
341;Assistant
342;Chief 24/378
343;AI Shoes Awesome
344;Maine
345;Avon Tactics
346;Web
347;Gloves
348;schemas solution Health
349;Assistant
350;Chief 24/378
351;Chair eco-centric
352;AI Shoes Awesome
353;Maine
354;Avon Tactics
355;Web
356;Gloves
357;schemas solution Health
358;Assistant
359;Chief 24/378
360;Chair eco-centric
361;Movies Architect matrix
362;AI Shoes Awesome
363;Maine
364;Avon Tactics
365;Web
366;Gloves
367;schemas solution Health
368;Assistant
369;Chief 24/379
370;AI Shoes Awesome
371;Maine
372;Avon Tactics
373;Web
374;Gloves
375;schemas solution Health
376;Assistant
377;Chief 24/379
378;Chair eco-centric
379;AI Shoes Awesome
380;Maine
381;Avon Tactics
382;Web
383;Gloves
384;schemas solution Health
385;Assistant
386;Chief 24/379
387;Chair eco-centric
388;Movies Architect matrix
389;AI Shoes Awesome
390;Maine
391;Avon Tactics
392;Web
393;Gloves
394;schemas solution Health
395;Assistant
396;Chief 24/380
397;AI Shoes Awesome
398;Maine
399;Avon Tactics
400;Web
401;Gloves
402;schemas solution Health
403;Assistant
404;Chief 24/380
405;Chair eco-centric
406;AI Shoes Awesome
407;Maine
408;Avon Tactics
409;Web
410;Gloves
411;schemas solution Health
412;Assistant
413;Chief 24/380
414;Chair eco-centric
415;Movies Architect matrix
416;AI Shoes Awesome
417;Maine
418;Avon Tactics
419;Web
420;Gloves
421;schemas solution Health
422;Assistant
423;Chief 24/381
424;AI Shoes Awesome
425;Maine
426;Avon Tactics
427;Web
428;Gloves
429;schemas solution Health
430;Assistant
431;Chief 24/381
432;Chair eco-centric
433;AI Shoes Awesome
434;Maine
435;Avon Tactics
436;Web
437;Gloves
438;schemas solution Health
439;Assistant
440;Chief 24/381
441;Chair eco-centric
442;Movies Architect matrix
443;AI Shoes Awesome
444;Maine
445;Avon Tactics
446;Web
447;Gloves
448;schemas solution Health
449;Assistant
450;Chief 24/382
451;AI Shoes Awesome
452;Maine
453;Avon Tactics
454;Web
455;Gloves
456;schemas solution Health
457;Assistant
458;Chief 24/382
459;Chair eco-centric
460;AI Shoes Awesome
461;Maine
462;Avon Tactics
463;Web
464;Gloves
465;schemas solution Health
466;Assistant
467;Chief 24/382
468;Chair eco-centric
469;Movies Architect matrix
470;AI Shoes Awesome
471;Maine
472;Avon Tactics
473;Web
474;Gloves
475;schemas solution Health
476;Assistant
477;Chief 24/383
478;AI Shoes Awesome
479;Maine
480;Avon Tactics
481;Web
482;Gloves
483;schemas solution Health
484;Assistant
485;Chief 24/383
486;Chair eco-centric
487;AI Shoes Awesome
488;Maine
489;Avon Tactics
490;Web
491;Gloves
492;schemas solution Health
493;Assistant
494;Chief 24/383
495;Chair eco-centric
496;Movies Architect matrix
497;AI Shoes Awesome
498;Maine
499;Avon Tactics
500;AI Shoes Awesome
</pre>
</details>

##### **Suggest a Fix**

-
##### **JHipster Version(s)**

```
jhpagination@0.0.1-SNAPSHOT C:\dev\github\jhpagination
`-- generator-jhipster@7.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "jhpagination",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1624431546588,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": false,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1624431808000,
    "entities": ["AnEntity"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity AnEntity {
  afield String
}
paginate AnEntity with pagination
service AnEntity with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

git version 2.32.0.windows.1

node: v14.17.0

npm: 7.7.1

Docker version 20.10.6, build 370c289

docker-compose version 1.29.1, build c34c88b2
##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by swarajsaaj** [comment]
@pmverma Trying to understand the issue, how is link value for "first" empty, Isn't it the one preceding it with page=0 as shown below? Similarly for other pages as well.
![image](https://user-images.githubusercontent.com/6285049/123198528-e5463d00-d4ca-11eb-8852-1a4b322b86a7.png)

**Comment by pmverma** [comment]
@swarajsaaj Thanks for pointing. My bad for the pair sides.
but the `prev,next,last` page numbers are wrong.

**Comment by swarajsaaj** [comment]
@pmverma Yes there is a different index in APIs because `Pageable` in spring has first page as 0 (instead of 1 as seen on client side).

**Comment by pmverma** [comment]
Oh thank @swarajsaaj . I think I need more sleep! 💤
