### ISSUE TITLE
`spring-cloud-starter-zipkin` has no longer exist with `spring-cloud-starter-***` v3.0.x

### ISSUE THREAD

**Issue by PC-Chiu** [jhipster/generator-jhipster#15455]
When I use `generator-jhipster` v7.1.0 to generate a webflux gateway，I found the profile `zipkin` use dependency `spring-cloud-starter-zipkin`

but, `spring-cloud-starter-zipkin` has no longer exist with `spring-cloud-starter-***` v3.0.x

##### **Suggest a Fix**

Change dependency with `spring-cloud-starter-sleuth`

and add `spring-cloud-sleuth-zipkin`

##### **JHipster Version(s)**

v7.1.0

Otherwise, should we add profile `jaeger` to use `opentracing-spring-jaeger-cloud-starter`

**Comment by PC-Chiu** [comment]
It can be see: https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#up-till-300-m5

**Comment by DanielFran** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/17615
