### ISSUE TITLE
npm test doesn't pass

### ISSUE THREAD

**Issue by nicolasduminil** [jhipster/generator-jhipster#15493]
##### **Overview of the issue**

Running the npm test commands displays 20 thousands errors

##### **Motivation for or Use Case**

npm test should pass

##### **Reproduce the error**

jhipster --skip-install
npm test

##### **JHipster Version(s)**

7.1.0

##### **JHipster configuration**

`jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator
##### **JHipster Version(s)**

```
dsirc@0.0.1-SNAPSHOT /home/nicolas/test
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "dsirc",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1624887871957,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.dsirc.tests",
    "serverPort": "8080",
    "cacheProvider": "infinispan",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "packageFolder": "com/dsirc/tests",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

git version 2.25.1

node: v14.17.1

npm: 6.14.13

Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2

docker-compose version 1.28.5, build c4eb3a1f

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

`
##### **Browsers and Operating System**

Ubuntu 20.04 LTS, Firefox 89.0.1

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Why do you set `--skip-install`?

**Comment by pascalgrimaud** [comment]
@Tcharl : it would be better to clean label and remove stale when you closed it. So we know the ticket is done
