### ISSUE TITLE
Exception deploying to Google Cloud

### ISSUE THREAD

**Issue by AbelAlcaraz** [jhipster/generator-jhipster#15523]
##### **Overview of the issue**

Trying to deploy project to GCP with command **./gradlew appengineDeploy -Pgae -Pprod-gae** and I'm getting error:

 > Task :webapp

> stp@0.0.1-SNAPSHOT webapp:prod
> npm run clean-www && npm run webapp:build:prod

> stp@0.0.1-SNAPSHOT clean-www
> rimraf build/resources/main/static/app/{src,build/}

> stp@0.0.1-SNAPSHOT webapp:build:prod
> ng build --prod

- Generating browser application bundles...
✔ Browser application bundle generation complete.
Webpack Bundle Analyzer saved report to /Users/abel/PROYECTOS/integria/stp/build/resources/main/stats.html
- Copying assets...
✔ Copying assets complete.
- Generating index html...
✔ Index html generation complete.
- Generating service worker...
✔ Service worker generation complete.

Initial Chunk Files               | Names         |      Size
main.cfaf4e179e1aa05d4b75.js      | main          | 585.86 kB
styles.7681a575931432bdeae0.css   | styles        | 143.90 kB
polyfills.943d450929e251632903.js | polyfills     |  36.38 kB
runtime.ea444841b0513ff301c8.js   | runtime       |   2.64 kB

| Initial Total | 768.77 kB

Lazy Chunk Files                  | Names         |      Size
19.1495492a16bf0d057ace.js        | -             |  74.58 kB
6.159360000033e12d7d24.js         | -             |  63.52 kB
13.265257745716e4fe3ed8.js        | -             |  59.06 kB
17.7b5eddb024ded30c1c9a.js        | -             |  43.20 kB
7.003b9de2ddf450bdefdc.js         | -             |  38.94 kB
10.1ebed59c1f8c31253b2b.js        | -             |  38.91 kB
9.63156f14d5194655a682.js         | -             |  36.81 kB
18.20db22807d7687763d72.js        | -             |  35.61 kB
8.e755460609179ed815d5.js         | -             |  28.13 kB
2.7fc32ce6ec0e385e4777.js         | -             |  20.27 kB
common.51bcc245263d32abaf54.js    | common        |   9.30 kB
11.29b89ef5ecfef14b0e00.js        | -             |   8.07 kB
12.1414a0727bd0a6c6a8d8.js        | -             |   7.84 kB
16.20e42de2d3bd2a781c7b.js        | -             |   6.95 kB
20.0f15e2e94adea6e81027.js        | -             |   4.93 kB
14.07b23261ff924e5ca54f.js        | -             | 947 bytes
15.6a267142f8a5f4810836.js        | -             | 831 bytes

Build at: 2021-07-01T09:52:29.772Z - Hash: dd36c47d302a843f0048 - Time: 66650ms

> Task :compileJava
Note: Hibernate JPA 2 Static-Metamodel Generator 5.4.29.Final

> Task :thinResolve FAILED
no main manifest attribute, in stp-0.0.1-SNAPSHOT.jar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':thinResolve'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-11.0.5.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 29s
14 actionable tasks: 12 executed, 2 up-to-date

##### **Motivation for or Use Case**

I need to deploy te app to GCP

##### **Reproduce the error**

Execute command: **./gradlew appengineDeploy -Pgae -Pprod-gae**

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
stp@0.0.1-SNAPSHOT /*****/stp
└── generator-jhipster@7.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "stp",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1620024894337,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "eu.integria.stp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "packageFolder": "eu/integria/stp",
    "jwtSecretKey": "******",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["es"],
    "lastLiquibaseTimestamp": 1624633576000,
    "entities": ["Embarcacion", "TrabajadorEmbarcacion", "Tecnico", "Proyecto", "Empresa", "EmpresaProyecto"],
    "gcpProjectId": "*****",
    "gcpCloudSqlInstanceName": "*****",
    "gcpCloudSqlUserName": "*****",
    "gcpCloudSqlDatabaseName": "*****",
    "gaeServiceName": "*****",
    "gaeLocation": "*****",
    "gaeInstanceClass": "F1",
    "gaeScalingType": "automatic",
    "gaeMinInstances": "0",
    "gaeMaxInstances": "1",
    "gaeCloudSQLInstanceNeeded": "Y"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Embarcacion {
}
entity TrabajadorEmbarcacion {
}
entity Tecnico {
}
entity Proyecto {
}
entity Empresa {
}
entity EmpresaProyecto {
}
enum CargoTrabajadorEmbarcacion {
}
enum TipoProyecto {
}
enum ActividadEmpresa {
}

relationship OneToMany {
  Embarcacion{trabajadorEmbarcacion} to TrabajadorEmbarcacion{embarcacion(nombre) required}
  Tecnico{proyecto} to Proyecto{tecnico(nombre)}
  TrabajadorEmbarcacion{proyecto} to Proyecto{trabajadorEmbarcacion(nombre)}
  Proyecto{empresa} to EmpresaProyecto{proyecto(codigo) required}
  Empresa{empresaProyecto} to EmpresaProyecto{empresa(nombre) required}
}
relationship ManyToOne {
  Proyecto{embarcacion(nombre) required} to Embarcacion
  EmpresaProyecto{empresaContratante(nombre)} to Empresa
}

paginate Embarcacion, TrabajadorEmbarcacion, Tecnico, Proyecto, Empresa, EmpresaProyecto with pagination
service Embarcacion, TrabajadorEmbarcacion, Tecnico, Proyecto, Empresa, EmpresaProyecto with serviceClass
filter Embarcacion, TrabajadorEmbarcacion, Tecnico, Proyecto, Empresa, EmpresaProyecto

</pre>
</details>

##### **Environment and Tools**

java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)

git version 2.26.2

node: v14.16.1

npm: 7.13.0

Docker version 20.10.0, build 7287ab3

docker-compose version 1.27.4, build 40524192

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Browsers and Operating System**

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
Haven't got the time to test this, but will do so. Please keep this open. 😄

**Comment by SudharakaP** [comment]
Keep this open please. 😉

**Comment by SudharakaP** [comment]
Keep it open please.

**Comment by mraible** [comment]
@SudharakaP Do you have time to investigate and fix this issue? If not, do you know someone that might be able to help?

**Comment by DanielFran** [comment]
@SudharakaP any news?

**Comment by SudharakaP** [comment]
Sorry it has been a bit busy, but I'll get it done this week or next for sure. 👍🏽
