### ISSUE TITLE
Don't assume an empty database in tests

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1552]
To speed up the tests, I use Liquibase to globally feed some test data set before running them (my tests can work on huge data sets).
This works well except that the tests "checkXXXIsRequired" fail because they assume that the database is empty.
It would be more flexible to just check the database size before the test and verify that it hasn't changed at the end (as this is done for other tests).

Replace: 
assertThat(FooRepository.findAll()).hasSize(0);
by:
int databaseSizeBeforeTest = FooRepository.findAll().size();

And:
assertThat(Foos).hasSize(0);
By:
assertThat(Foos).hasSize(databaseSizeBeforeTest);

**Comment by wuethrich44** [comment]
I improve the tests in this PR #1276. But I can't find the test which fail in your case. Maybe you could provide a PR?

**Comment by cbornet** [comment]
It seems it was added on master branch after you forked.
The method is:
public void check<%= fields[fieldId].fieldInJavaBeanMethod %>IsRequired() throws Exception {
between create() and getAll().

**Comment by wuethrich44** [comment]
Oh yes they add this test later. Could you fork this project and fix this test?

**Comment by tagliola** [comment]
IMO best practice would be to always assume the database to be empty at the
start of a test and try to clean the database after you. If you would need
some large set of data and group the tests due to test runtime
optimization, I would assume this would be done in a separate set of tests
and possibly a separate build. (E.g. it's not a unit test any more).

**Comment by jdubois** [comment]
As we use the @Transactional annotation on tests, everything should rollback at the end of the tests -> so normally the database is always in a "clean" state
So you shouldn't have to clean up things manually, just validate that at the end the test everything looks like it should, and then let the rollback clean up for you.

I'm not sure there is still an issue here, as I don't understand all the comments -> please reopen this ticket if something is still broken for you

**Comment by cbornet** [comment]
This is the exact same reasons as #1265 which you said was a good idea !!
