### ISSUE TITLE
@embedded doesn't work with Mongodb

### ISSUE THREAD

**Issue by Ivanov-Alexander** [jhipster/generator-jhipster#15524]
##### **Overview of the issue**
Hi guys, tried to generate project via JDL but got next error:
```
Unhandled promise rejection at:
TypeError: D:\jhipster\node_modules\generator-jhipster\generators\entity-client\templates\react\src\main\webapp\app\entities\entity-update.tsx.ejs:164
    162| <%_ relFieldNames.forEach(rel => { _%>
    163| <%_ if (rel.relationshipManyToOne || (rel.ownerSide && rel.relationshipOneToOne))  { _%>
 >> 164|         <%= rel.relationshipFieldName %>: <%= rel.otherEntityNamePlural %>.find(it => it.<%= rel.otherEntity.primaryKey.name %>.toString() === values.<%= rel.relationshipFieldName %>Id.toString()),
    165| <%_ } _%>
    166| <%_ }) _%>
    167|     }

Cannot read property 'name' of undefined
```

##### **Reproduce the error**
jhipster jdl .\application.jdl

##### **JHipster Version(s)**
7.1.0

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
D:\jhipster
`-- (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
Not generated
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
     application {
  config {
        baseName missionMarketplace
        packageName com.ai
        applicationType monolith
        authenticationType session
        buildTool maven
        cacheProvider redis
        clientFramework react
        clientPackageManager npm
        clientTheme yeti
        clientThemeVariant dark
        databaseType mongodb
        devDatabaseType mongodb
        prodDatabaseType mongodb
        dtoSuffix Response
        languages []
        nativeLanguage en
        serverPort 8080
    }
    
    entities *
dto * with mapstruct
service * with serviceClass
paginate * with pagination
}
entity Country {
    id UUID
    name String
}
@embedded
entity Region {
    name String
}
relationship OneToOne {
    Country to Region
}
</pre>
</details>

##### **Environment and Tools**

java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

git version 2.32.0.windows.1

node: v14.15.1

npm: 7.18.1

Docker version 20.10.7, build f0df350

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Not generated

##### **Browsers and Operating System**

OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043

- [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by Ivanov-Alexander** [comment]
![image](https://user-images.githubusercontent.com/1621756/124163737-8c693c80-daa8-11eb-8191-73390c78ee80.png)

**Comment by mshima** [comment]
Need to change line:
```
<%_ if (rel.relationshipManyToOne || (rel.ownerSide && rel.relationshipOneToOne))  { _%>
```
to
```
<%_ if (rel.relationshipManyToOne || (rel.ownerSide && rel.relationshipOneToOne && !rel.otherEntity.embedded))  { _%>
```

We don’t have support to embedded entities in the frontend.

**Comment by mraible** [comment]
@Ivanov-Alexander Is this still an issue with 7.6.0?

**Comment by mshima** [comment]
This probably still happens to vue and react.
There are a few fixes to angular embedded support at https://github.com/jhipster/generator-jhipster/pull/17822
