### ISSUE TITLE
Is necessary to add a 'local' profile.

### ISSUE THREAD

**Issue by Mavlarn** [jhipster/generator-jhipster#1554]
In my dev, I use H2 for local dev environment, and mysql/postgresql for product.
But, every time I prepare to use prod profile to deploy, there will be always some kind of problems, because of the difference of h2 and mysql. So I need to modify the dev profile to use mysql, test and run for some days before I deploy to production.Or, create a local profile for h2, and dev profile for mysql. Then I can switch easily between local/dev/prod .

So, I think maybe it is useful to add another profile for local.

**Comment by wuethrich44** [comment]
I think a better approach is to use a staging environment that is similar to the production environment. Then you can test your changes in the staging environment and if all works well you can deploy your changes to the production environment.

**Comment by Mavlarn** [comment]
@wuethrich44 , my current solution is to use 'dev' profile like 'staging environment' as you said, and a 'local' for developing with h2 and other local environment.

**Comment by jdubois** [comment]
This is something I've done on purpose, in fact, here is the idea:
- We only create the minimum useful profiles
- If that's enough for you, it's perfect -> we don't want to give you too many useless options
- If you need more profiles, you should of course create them, it's quite simple to do with Spring

Then, maybe having only "dev" and "prod" is too simple, and we could have a "stage" profile. Personally I don't use H2, so I don't have those issues, but my stats show that 80% of people use H2...

I'm closing this at the moment as it "works as expected", but I understand your issue, and I will keep it mind. At least I would need to document that.
