### ISSUE TITLE
Generating Blueprints failing on M1(ARM) Processor

### ISSUE THREAD

**Issue by sang-w0o** [jhipster/generator-jhipster#15544]
##### **Overview of the issue**

- While trying to create a vue.js blueprint, I get the error below.
![image](https://user-images.githubusercontent.com/48438083/124402218-d5034d00-dd69-11eb-8714-d6b2a61ae080.png)

##### **JHipster Version(s)**

- v7.1.0

##### **JHipster configuration**

- No custom configurations done.

```
❯ jhipster info
INFO! Using JHipster version installed globally
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Homebrew (build 17+0)
OpenJDK 64-Bit Server VM Homebrew (build 17+0, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v14.17.2

npm: 6.14.13

Docker version 20.10.6, build 370c289

docker-compose version 1.29.1, build c34c88b2


No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
```

##### **Browsers and Operating System**

- OS: Mac OS Big Sur on M1 Processor.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
`jhipster info` should be run in your project's directory to collect useful information.

**Comment by atomfrede** [comment]
Vue is part of the main generator since version 7. You don't need to use the blueprint anymore. The blueprint is not compatible with jhipster 7.
