### ISSUE TITLE
Paths altered by usemin in prod build doesnt work with a context in app servers

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1555]
Was looking into this [issue](https://stackoverflow.com/questions/30404042/jhipster-running-application-inside-a-context-image-and-glyphicons-problems#) raised by JH user @iuricmp and found the below.

Not sure if this is a usemin plugin issue or a config issue on JH side

Issue:

The image paths and font paths in `*.vendor.css` and `*.main.css` works only if the application is run from the root context as these are currently something like ` /bower_components/*` and `/assets/*` which would be 404 when the app is deployed as a war in say for example tomcat `webapps/jhipster.war` or similar in Jboss etc.
If I manually update the generated css files like this replacing `/bower_components` with `../../bower_components` and `/assets` with `../../assets` it works

From console logs even websocket doesnt seem to work with context on path as the request URL is missing the app context on path

![image](https://cloud.githubusercontent.com/assets/1107223/7910599/c5fbe176-0888-11e5-97c5-860d2fcdacd8.png)

**Comment by deepu105** [comment]
will try to find if there is a solution that can be done on Jhipster side, but havent used usemin much so will be good if somebody who knows it better can take a look as well

**Comment by deepu105** [comment]
Thats strange!! websocket seems to work if i change `/websocket/tracker` to `websocket/tracker` in `tracker.service.js` but says its a syntax error 

```
Opening Web Socket...

69b40175.vendor.js:4 Uncaught SyntaxError: Failed to construct 'WebSocket': The URL 'wsocket/tracker/163/wy5ibbow/websocket' is invalid.y.websocket @ 

69b40175.vendor.js:4y._try_next_protocol @ 69b40175.vendor.js:4y._didClose @ 69b40175.vendor.js:4g._ir.onfinish @ 69b40175.vendor.js:4f.emit @ 69b40175.vendor.js:4P.doXhr.f.onfinish @ 69b40175.vendor.js:5f.emit @ 69b40175.vendor.js:4u._start.g.xhr.onreadystatechange @ 69b40175.vendor.js:4
69b40175.vendor.js:4 Web Socket Opened...
69b40175.vendor.js:4 >>> CONNECT
X-CSRF-TOKEN:f62061c7-9998-477e-827c-727c864934ff
accept-version:1.1,1.0
heart-beat:10000,10000

```

**Comment by deepu105** [comment]
might  not have time till weekend to debug this, so if anyone else can take a look plz do so!

**Comment by jdubois** [comment]
@deepu105 yes we've already had that kind of error, as I assume the application is running on the "root" context.
This is wrong from my side, as indeed people might want to run the app in another context, and we need to have relative paths everywhere (which shouldn't be too hard to do).

**Comment by phouverney** [comment]
Maybe one file config can help.
The API URL could be in this file.

**Comment by atomfrede** [comment]
@deepu105 Removing the ``root`` from ``cssmin`` tasks helps at least for images when deploying inside jetty under any path that is not the root context. Still issues with the glyphicons but should be possible to find a solution.

**Comment by deepu105** [comment]
@atomfrede thanks, I guess websockets needs to be fixed as well

**Comment by atomfrede** [comment]
@deepu105 Can you check if it works for you as expected?

**Comment by jdubois** [comment]
@atomfrede @deepu105 can you keep me updated, as it's now merged in master?

**Comment by deepu105** [comment]
Ok ill check and update

**Comment by deepu105** [comment]
Ok tested with tomcat context root seems to be working for images and fonts, websocket needs to be fixed but thats a seperate issue hence ill open a new issue for that and this can remain closed

**Comment by atomfrede** [comment]
Yes correct, I didn't looked at websockets.

**Comment by deepu105** [comment]
@jdubois I have pushed two PR to fix the remaining context based issues (websocket and login page loop)
