### ISSUE TITLE
🚀 Resources shouldn't consume Repository directly

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#15589]
##### **Overview of the feature request**
In order to maintain good code quality, `Resource` layer shouldn't be using the `Repository` directly, but through the `Service` layer instead.

##### **Motivation for or Use Case**
This file
https://github.com/jhipster/generator-jhipster/blob/bad53a5fdb7cee3b307fbfa8fec51b8f99035c68/generators/entity-server/templates/src/main/java/package/common/inject_template.ejs#L43
creates the Constructor with a `Repository` object, which, IMHO, is incorrect as it should be the `Service` the one interacting with the `Resource`.

Also, the `Resource` is calling the `Repository` directly here:
https://github.com/jhipster/generator-jhipster/blob/bad53a5fdb7cee3b307fbfa8fec51b8f99035c68/generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs#L237
(and also a couple of lines later)

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Hello @amatosg :) The service layer can be generated through the `service` option and if it is the case: the controller would need a service to be created, and the service would need the repository (DI).
Sometimes adding an additional layer makes sense but here for simple apps... the service layer can be omitted.

**Comment by amatosg** [comment]
Although I don't agree on such exceptions, I respect the decision 😃
