### ISSUE TITLE
Blueprint generator fails on upgrade command

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#15617]
##### **Overview of the issue**

When running upgrade command from a project generated with blueprint, the upgrade command fails with version undefined error.

##### **Motivation for or Use Case**

It should not be mandatory for blueprints to implement `upgrade` subgenerator

##### **Reproduce the error**
Install KHipster & run `khipster upgrade`
```
.yo-rc.json
{
"generator-jhipster": {
"blueprints": [
{
"name": "generator-jhipster-kotlin",
"version": "1.12.1"
}
],
"otherModules": [
{
"name": "generator-jhipster-kotlin",
"version": "1.12.1"
}
],
"applicationType": "monolith",
"baseName": "test",
"jhipsterVersion": "7.0.1",
"skipClient": false,
"skipServer": false,
"skipUserManagement": false,
"skipCheckLengthOfIdentifier": false,
"skipFakeData": false,
"jhiPrefix": "jhi",
"entitySuffix": "",
"dtoSuffix": "DTO",
"testFrameworks": [],
"pages": [],
"creationTimestamp": 1624602504902,
"serviceDiscoveryType": false,
"reactive": false,
"authenticationType": "jwt",
"packageName": "com.mycompany.myapp",
"serverPort": "8080",
"cacheProvider": "ehcache",
"enableHibernateCache": true,
"databaseType": "sql",
"devDatabaseType": "h2Disk",
"prodDatabaseType": "postgresql",
"buildTool": "gradle",
"serverSideOptions": [],
"websocket": false,
"searchEngine": false,
"messageBroker": false,
"enableSwaggerCodegen": false,
"clientFramework": "react",
"withAdminUi": true,
"clientTheme": "none",
"enableTranslation": true,
"nativeLanguage": "en",
"packageFolder": "com/mycompany/myapp",
"jwtSecretKey": "YTEwMzFlZGM3NDA0ZTNlOWM0OWI2ZmY3MmUwZjdhNDYyN2RkYmUyZWM2YWEzZTZkOGUyNWVmYTdkN2RhYTIxNDk4YmY0YzdiM2Y0MzU0MWRmYTM4NzJjYTA3NmY1ODkxYWJjMDE5ZTViZDVjMDZiODJlYTFjMGU3MzIwZWFjZTY=",
"clientPackageManager": "npm",
"clientThemeVariant": "",
"languages": ["en"]
}
}
```

##### **Related issues**

https://github.com/jhipster/jhipster-kotlin/issues/286

##### **Suggest a Fix**

[This check](https://github.com/jhipster/generator-jhipster/blob/ad341f560fe4130c9d3ba45cd4b5f15256f84530/generators/upgrade/index.js#L263) should return true when the `version` is undefined.

##### **JHipster Version(s)**

< 7.1.0

##### **JHipster configuration**

refer above

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

 N/A

##### **Browsers and Operating System**

N/A

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Currently the blueprint version is required: https://github.com/jhipster/generator-jhipster/blob/ad341f560fe4130c9d3ba45cd4b5f15256f84530/generators/upgrade/index.js#L454.

Just workaround that condition will not fix the problem.

**Comment by mshima** [comment]
I will try to reproduce soon.

**Comment by mraible** [comment]
@sendilkumarn This references the Kotlin blueprint. Do you have an opinion about this?

**Comment by mshima** [comment]
Maybe this was fixed by https://github.com/jhipster/generator-jhipster/pull/17742/commits/d61fd1e2a8c086bd27c427a0fcdab89263782eaf
