### ISSUE TITLE
Jhipster 7 does not generate admin-ui pages even when it was chosen during project creation

### ISSUE THREAD

**Issue by Prof-daniel-Fiap** [jhipster/generator-jhipster#15619]
Jhipster 7 does not generate admin-ui pages even when it was chosen during project creation

**Comment by atomfrede** [comment]
Can fill the issue template please?

**Comment by Prof-daniel-Fiap** [comment]
**Overview of the issue**

Jhipster 7 does not generate admin-ui pages even when it was chosen during project creation

Motivation for or Use Case

I want to use admin ui.

**Reproduce the error**

Create one project, answer yes for admin-ui

**Related issues**

Couldnt find similar issues

**Suggest a Fix**

compare with version 6

**JHipster Version(s)**
7.1.0

**Comment by vishal423** [comment]
@Prof-daniel-Fiap , can you provide output of `jhipster info`?

**Comment by Prof-daniel-Fiap** [comment]
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? teste_app
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? com.mycompany.myapp
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Which cache do you want to use? (Spring cache abstraction) Ehcache (local cache, for a single node)
? Do you want to use Hibernate 2nd level cache? No
? Would you like to use Maven or Gradle for building the backend? Maven
? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? Which other technologies would you like to use?
? Which *Framework* would you like to use for the client? Angular
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install
? Besides JUnit and Jest, which testing frameworks would you like to use?
? Would you like to install other generators from the JHipster Marketplace? No

**Comment by Prof-daniel-Fiap** [comment]
[INFO]
[INFO] -------------------< com.mycompany.myapp:teste-app >--------------------
[INFO] Building Teste App 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- frontend-maven-plugin:1.12.0:install-node-and-npm (install-node-and-npm) @ teste-app ---
[INFO] Installing node version v14.17.1
[INFO] Copying node binary from C:\Users\danie\.m2\repository\com\github\eirslett\node\14.17.1\node-14.17.1-win-x64.exe to E:\projetos-jh\teste-admin-ui\target\node\node.exe
[INFO] Installed node locally.
[INFO] Installing npm version 7.18.1
[INFO] Unpacking C:\Users\danie\.m2\repository\com\github\eirslett\npm\7.18.1\npm-7.18.1.tar.gz into E:\projetos-jh\teste-admin-ui\target\node\node_modules
[INFO] Installed npm locally.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.864 s
[INFO] Finished at: 2021-07-23T12:15:14-03:00
[INFO] ------------------------------------------------------------------------
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 2252 packages, and audited 2253 packages in 1m

155 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 7.18.1 -> 7.20.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.20.1
npm notice Run npm install -g npm@7.20.1 to update!
npm notice
Application successfully committed to Git from E:\projetos-jh\teste-admin-ui.

If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Server application generated successfully.

Run your Spring Boot application:
./mvnw (mvnw if using Windows Command Prompt)

Client application generated successfully.

Start your Webpack development server with:
 npm start

**Comment by Prof-daniel-Fiap** [comment]
this time I use jwt instead oauth2 and it admin-ui worked. when I had the problem I was using oauth2 with keycloak, it maybe related.

**Comment by Prof-daniel-Fiap** [comment]
it is working now! I don't know what happened.
