### ISSUE TITLE
Jackson parameters in test conf file are ignored

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1561]
It seems the MockMvc uses its own MappingJackson2HttpMessageConverter and not the one configured by the Spring app. So parameters in the test application.yaml like WRITE_DATES_AS_TIMESTAMP or DEFAULT_VIEW_INCLUSION are not used.

I worked around this by injecting MappingJackson2HttpMessageConverter and using it to configure the mock like this:
```java
@Inject
private MappingJackson2HttpMessageConverter jacksonMessageConverter;

this.restHistDataMockMvc = MockMvcBuilders.standaloneSetup(fooResource).setMessageConverters(jacksonMessageConverter).build()
```
But I am not sure this is the good way to go. Is there any Spring guru that has an opinion on this ?

**Comment by jdubois** [comment]
- By default we don't have this issue as we don't change the default parameters (at least not that I am aware of, and I don't have any issue like this). So I can't reproduce, but I see your point.
- I don't want to add more configuration to the default generated files, if people don't have the issue (as there hasn't been any comments here, I guess people are fine with our current config)
- Yes I see your workaround -> once again I can't reproduce, but it looks good
