### ISSUE TITLE
Password length on server side is not checked correct

### ISSUE THREAD

**Issue by wuethrich44** [jhipster/generator-jhipster#1565]
Today i wanna change the password length to 8 chars. Then I noticed while the password reset the password is not checked on the server side in this method: 
```java
public Optional<User> completePasswordReset(String newPassword, String key) {}
```
During the registration the password length is check in the UserDTO and while the password change there is a fix in this PR https://github.com/jhipster/generator-jhipster/commit/16fb9338e46554581ee3a709b2c2ca9388cb3abd.

Furthermore the `@Size(min=5, max=100)` in the user entity password is useless because the password hash has a fix length.

I suggest two options to unify the password length check:

- Make all password changes with the UserDTO and use the `@Size` in this DTO
- Read the password length from the settings and fix this problem like in this PR https://github.com/jhipster/generator-jhipster/commit/16fb9338e46554581ee3a709b2c2ca9388cb3abd

Then I recommend to set the `@Size` from the user entity password field to this `@Size(min=60, max=60)` because the bcrypt hash produce 60 char length strings and rename the field to something like `passwordHash`.

What do you think about this suggestions?

**Comment by atomfrede** [comment]
Damn, again my fault :( Yes while resetting the password it is not checked on server side. 

So I think all your suggestions are reasonable and should be done. I guess I'll find some time in the next days to provide a PR.

**Comment by jdubois** [comment]
Yes this all looks good. I'll keep the field name `password`, thus.

**Comment by wuethrich44** [comment]
:+1: @atomfrede Thanks! What do you think about to extract the password length in two constants and use this constants in your new function and the UserDTO?

**Comment by atomfrede** [comment]
Good idea😀

**Comment by wuethrich44** [comment]
Could you implement that in your existing PR?

**Comment by atomfrede** [comment]
:white_check_mark:

**Comment by wuethrich44** [comment]
nice thanks :+1:
