### ISSUE TITLE
activate user controller not getting called

### ISSUE THREAD

**Issue by tsukhu** [jhipster/generator-jhipster#1567]
I have tried out multiple versions of jHipster including the latest version (2.14.2) and the sample on github and get the same issue.

On creating a new user the main contains a link of this kind for the activation 
http://127.0.0.1:8080/#/activate?key=92798744378986630559
However this does seem to get called at all. It there an issue with the passing of parameters to AngularJS ..

**Comment by tsukhu** [comment]
Ok - here is what is not working , I have mailtrap.io  configured as the main server and when I click on the activation link from the inbox then it does not work , but when I copy the activation url and directly use the same on the browser then it works .. I am missing something as is this the expected behaviour

**Comment by jdubois** [comment]
The name of your server is not correct, it shouldn't be "127.0.0.1".

We get this using a `request.getServerName()` in the `AccountResource` controller -> I don't know why this is wrong.

You could either re-code this part (write the server name in the application.yml file and then use it there), or maybe have a look at your server configuration? I don't know how this methods gets the server name, I need to have a closer look.

**Comment by tsukhu** [comment]
Thanks a lot .. I'll have a look and re-try this.

**Comment by tsukhu** [comment]
The problem for me was when I was clicking the HTML activation email from mailtrap.io (Free version) .. some how this just does not work (The activate route is not called at all) . However if I save the email content as an HTML file and there it works fine. I am not sure what but it has something to do with the mailtrap.io .. may be it is just supposed to be used as a mail dump.. 
I am closing this issue as it is not related to jHipster

**Comment by tsukhu** [comment]
Here is the workaround to make it work in mailtrap.io .. Apparently the mail is shown in an iframe with multiple tabs and clicking from within the iframe is causing some sort of weird behaviour . I am using Firefox here where you can  rightclick on the iFrame displaying the email and choose "Open Frame in New Tab" .. and then it works ..
![openframe_innewtab](https://cloud.githubusercontent.com/assets/846306/8000053/e9d414e6-0b72-11e5-8bb3-867e0121bdb3.PNG)

**Comment by tsukhu** [comment]
One possible improvement to the activation would be to handle keys that are not found .. at present even if I give a non existent key I get a success .. with an OptionalEmpty key
![activate_worksforincorrectkey](https://cloud.githubusercontent.com/assets/846306/8000090/6b9edcc2-0b73-11e5-83e5-604800c79b9b.PNG)

**Comment by deepu105** [comment]
You mean you can activate a user by passing a non existing random ley?  If thats the case its a security bug @atomfrede you may want to look at this

**Comment by tsukhu** [comment]
There is no activation as the key is not found but the message to the user is wrong as the logic does not throw an exception

**Comment by atomfrede** [comment]
@tsukhu Yes that message is strange. But otherwise anyone might be able to just try out any keys to activate other users.

**Comment by tsukhu** [comment]
@atomfrede should the username also be provided to derisk the chance of random activation
