### ISSUE TITLE
Set time to end for log level settings

### ISSUE THREAD

**Issue by oliosien** [jhipster/generator-jhipster#15705]
##### **Overview of the feature request**

It'd be a nice feature when I change a log level for a logger, show a field where administrator can write a date time until the new level must work. After this time the log level will return as it was before the change.

##### **Motivation for or Use Case**

If I set a debug level for a specific logger and I forget it, log file will increase and cause a dangerous disk usage.

##### **Related issues or PR**

I haven't find similar issue.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I don't think this is supported by logback, so closing. Please re-open if you find a solution and submit a PR to add.
