### ISSUE TITLE
Embedded Elasticsearch

### ISSUE THREAD

**Issue by The-Crocop** [jhipster/generator-jhipster#15713]
##### **Overview of the issue**

Before Upgrade to 7.1.0 we used to run elasticsearch embedded for local development. That worked just fine. 
After the upgrade jhipster switched to Spring Elasticsearch and now embedded option does not work anymore
I wonder if that is on purpose or it is a bug? And is there a way to get back old behavior or is jhiptser now meant to run elasticsearch with docker only?

##### **Motivation for or Use Case**

It used to woork previously and the devs in team didnt need to know or bother running elasticsearch. It worked out  of the box
##### **Reproduce the error**

Start a jhipster microservice with elasticsearch in version 7.1.0. If you dont have elasticsearch running in docker it will fail
##### **Related issues**

Couldnt find similar issues
##### **Suggest a Fix**

Either bring back embedded elasticsearch or update documentation to reflect the change

##### **JHipster Version(s)**

7.1.0

**Comment by mraible** [comment]
I believe @jdubois might've written the code that changed this behavior. Not sure.

**Comment by jdubois** [comment]
It's not possible anymore, and I deeply regret it, but that's a design decision from Elastic (the company). They basically don't want us to run Elasticsearch in embedded mode.

I am sincerely sad about it, and believe it's a bad decision for developers.

I'm closing this, as we can't go against the company building the product.
