### ISSUE TITLE
Feature Request: add metrics and health monitoring for hazelcast

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1571]
currently there is metrics for ehcache it would be useful have the same for hazelcast as well.

This can be done using [Statistics API](http://docs.hazelcast.org/docs/3.4/manual/html/management.html)
If somebody has already done this it would be nice to have it in JH, else ill try to do a PR after trying it out in my application first.

**Comment by jdubois** [comment]
This is should improved in Spring Boot 1.3, so we don't have to do it -> I'd rather wait until this Spring Boot 1.3 is released (should be September)

@deepu105 I know you're a big Hazelcast user, can you wait until September?

**Comment by deepu105** [comment]
@jdubois I guess Jhipster can wait but 2 of my projects have to go live in September so i would like them to have this anyway and spring boot 1.3 doesn't seem to offer detailed stats, after going through their comments im not even sure if hazelcast health and metrics will be there. So what do you think

**Comment by jdubois** [comment]
If it's urgent for you, and if we are not sure it is implemented, then yes I'll merge your PR

**Comment by deepu105** [comment]
Since i may end up implementing it anyway, ill do a pull, guess you can remove it if spring boot implements it

**Comment by RobWin** [comment]
I would be interested as well :D

**Comment by deepu105** [comment]
I guess Ill close this issue for now, since i might not have time to implement this we can wait for spring boot 1.3
