### ISSUE TITLE
Fix the Gradle build in v2.15.0

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1572]
The Gradle build fails in the latest v2.15.0, see https://drone.io/github.com/jhipster/jhipster-sample-app-gradle

**Comment by jdubois** [comment]
@atomfrede it might my fault, I'll have a look at it during the week end

**Comment by atomfrede** [comment]
Somehow the sample app is not generated correct:

```gradle
sourceCompatibility=1.${javaVersion}
targetCompatibility=1.${javaVersion}
```

Just generated a fresh app on my machine, build file is generated correctly.

https://github.com/jhipster/jhipster-sample-app-gradle/blob/master/build.gradle

**Comment by deepu105** [comment]
I fixed this in my oracle support PR, anyway will push a separate PR, I guess due to changes to yeoman 0.20 ${} doesnt get parsed I guess, this should be generated as 1.7 or 1.8

**Comment by atomfrede** [comment]
I think that part coded someone else. But when looked at it yesterday the same question came into my mind.
