### ISSUE TITLE
Vue UI doesn't reflect application backend errors

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#15722]
##### **Overview of the issue**

Case 1: Due to a misconfigured email service, an email doesn't send out for the password reset. There is a message indicating an email is sent on the UI despite the backend email error, nor any error message in the browser console.   

Case 2: After editing entity data, a unique database constrains error doesn't show up on the UI. In fact, the UI has no indication of the backend error at all. On the browser console, a message "uncaught (in promise) error: request failed with status code 500." The followings are the message.:
```
{
  "type" : "https://www.jhipster.tech/problem/problem-with-message",
  "title" : "Internal Server Error",
  "status" : 500,
  "detail" : "could not execute batch; SQL [update … where id=?]; constraint [\"PUBLIC.MY_ENTITY__CREATOR_ID_INDEX_9 ON PUBLIC.MY_ENTITY(CREATOR_ID) VALUES 1\"; SQL statement:\nupdate my_entity set …, username=? where id=? [23505-200]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch",
  "path" : "/api/my-entity/2”,
  "message" : "error.http.500"
}
```
##### **Motivation for or Use Case**

A user shall be notified of any backend errors.

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "myapp",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1625095262715,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.abc.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "cosmo",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/abc/myapp",
    "jwtSecretKey": "NThkZDg5YjE3OTkxNGU2YjUzNjAwODMwZjY4ODRiYmIyOWVkN2Q0NmZhMjZhNDU4MmQyYTQ5NDcxOWZlODRjY2ZhYWE5NjNjZWJkZDUyYzljYTU0NmU0OGExZDY4N2EwZjljZWQwMTliYWU3NGZiZTQ3NDQ1MGIwOTNjZDU3NmE=",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "es"]
  }
}
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
@vw98075 have you verified the web response sent by backend in browser dev tools? It should help to determine whether the problem is in Vue only or not.

**Comment by vw98075** [comment]
> @vw98075 have you verified the web response sent by backend in browser dev tools? It should help to determine whether the problem is in Vue only or not.

I update my report with more details. For the email, there isn't any error reported on the front end. For the DB error, the 500 is shown on the browser console. So, the error isn't picked in the Vue front end.

**Comment by gmarziou** [comment]
Thanks but you did not say what the web response was?. You only said error 500, does it mean that it does not have JSON body like I thought ti would due to the contraint violation being handled by [ExceptionTranslator](https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/java/io/github/jhipster/sample/web/rest/errors/ExceptionTranslator.java)

**Comment by vw98075** [comment]
I thought that the error should indicate where the problem is. The back-end error didn't catch on the front-end code. A pop-up message was expected. I add the response message to my post.

**Comment by gmarziou** [comment]
OK, so the backend correctly caught the error and provided the information to the Vue app which did not use it for display purpose.

This is clearly a JHipster Vue issue, I know only Angular where it is done by an interceptor that broadcasts errors to components including the one that deals with alert popups. 

So, I suppose in Vue it should be done in axios-interceptor.ts but I don't see any handling of errors except http 401 and 403.

I've tagged this issue as Vue so that someone else could help.

**Comment by vw98075** [comment]
I hope that this problem can be fixed in the next release. I don't know when it will happen then.

**Comment by gmarziou** [comment]
You could also consider contributing a fix to the community.

**Comment by vw98075** [comment]
I would if I were not busy on my project.

**Comment by vw98075** [comment]
I get my project to the 7.2.0 release today. This problem still exists. Here are the details: the BadRequestAlertException is thrown from a method in a controller. On the UI, the "save" button turns grey, but not an error message.
