### ISSUE TITLE
Browser Language Preference Needs To Be Honored

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#15744]
##### **Overview of the issue**

When Spanish is on the top of the language setting in my browser, my app still shows the content in the default language, English although Spanish is a language in my app.

##### **Motivation for or Use Case**

The browser language setting needs to be honored.

##### **Reproduce the error**

Create an app with multiple languages such as English as the default language and Spanish. Set Spanish on the top of your browser language setting. Access the app and it will show in English.

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "myapp",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1625095262715,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.abc.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "cosmo",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/abc/myapp",
    "jwtSecretKey": "NThkZDg5YjE3OTkxNGU2YjUzNjAwODMwZjY4ODRiYmIyOWVkN2Q0NmZhMjZhNDU4MmQyYTQ5NDcxOWZlODRjY2ZhYWE5NjNjZWJkZDUyYzljYTU0NmU0OGExZDY4N2EwZjljZWQwMTliYWU3NGZiZTQ3NDQ1MGIwOTNjZDU3NmE=",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "es"]
  }
}
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
I think this is a specific choice for your app, I'm not sure it would make sense to make it the default behavior. You can still implement it yourself with Spring LocaleResolver

**Comment by vw98075** [comment]
What I described is the correct multi-language web application behaviour. For example, Gitea, a Github like application, demonstrates the multi-language behaviour. The language setting in the browser will dictate the language display in the application. Try https://try.gitea.io/

**Comment by gmarziou** [comment]
You have described one way of doing it, there are other ways. Personally, I prefer that each application use its own preferences rather than relying on a global browser setting.

But maybe your proposition could be a good default and you could contribute it.

**Comment by vw98075** [comment]
Currently, I have some free time on hand to look into this issue. I do some coding tracing on the language setting in the front end Vue. Here is what I understand about the language setting:

1) initially, it retrieves the language settings (native/default language,  available languages) based on the configuration/app language preference (in the jhipsterConfig). And sets the displaying language with $store.getters.currentLanguage (which is the native/default language)

2) Once a user signs in the app, the current language is set with the user's language key.

A change needed is to set the current language based on the first language in the browser preference list which is in the jhipsterConfig.languages.

I see a generated Javascript code pormpts.js with some related code:
`
const languageOptions = this.getAllSupportedLanguageOptions();
...
return languageOptions.filter(...);
` 
I, however, can't find the Typescript code which generates the Javascript code. Can someone from the JHipster team shed some light on the subject?

**Comment by vw98075** [comment]
I change the following line in the refreshTranslation method of TranslationService.ts file
```
currentLanguage = newLanguage ? newLanguage : 'en';
```
to 
```
currentLanguage = newLanguage ? newLanguage : navigator.language;
```
With the change, the browser language setting is considered in the app language selection.

**Comment by vw98075** [comment]
I have a fix on this issue for our app. I, however, don't know how to make the change for JHipster generator.

**Comment by mraible** [comment]
The easiest way I've found to contribute a fix this this:

- Create a brand new app with JHipster. Check it into GitHub and push it to a main branch.
- Create a branch with your desired changed to make everything work.
- Take the changes and incorporate them into a PR for JHipster. Before you open the PR, test your changes locally and verify a new app's code matches the code from the previous step. SmartSynchronize can help with this.

Keep in mind that you will need to make these changes for Angular, React, and Vue.

**Comment by vw98075** [comment]
The related changes are in the jhi-navbar.component.ts..ejs. The file should be universal for all three front-end Javascript frameworks. I made changes based on our application language selections. I am not a Javascript person. So, it will take me longer to have a generic solution.

**Comment by gmarziou** [comment]
> Keep in mind that you will need to make these changes for Angular, React, and Vue.

@mraible I think it's asking for too much. You can't expect contributors to know well 3 frameworks.

**Comment by vw98075** [comment]
I can't push my code change due to "remote: Permission to jhipster/generator-jhipster.git denied to ..."

**Comment by gmarziou** [comment]
It's normal, because this is not how it works. You should push to your clone and then create a pull request to main project.

See https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md#submitting-a-pull-request

**Comment by vw98075** [comment]
The change I make for this matter is only on Vue. I have a look at Angular and React, but can't find the related code. As a result, I don't make the same code change for those two sets of front-end code.
