### ISSUE TITLE
naming conventions on the Javascript side

### ISSUE THREAD

**Issue by michaelisvy** [jhipster/generator-jhipster#1576]
Hi,
I understand the existing naming conventions are inspired from angular-fullstack.

- The Main Controller's file is called `main.controller.js`
- The controller placed in the scope is called `MainController` (with capital M)
- The corresponding service is called `Principal` and stored inside `principal.service.js`

I could be wrong, but my guess is that JHipster users are mostly Java developers who are moving from JSP to AngularJS. 

Wouldn't it be easier to have naming conventions on JS side that are close to what we have on the Java side?
In that case we would have:
- `main.controller.js` becomes `MainController.js`
- `principal.service.js` becomes `PrincipalService.js`
- scope attributes would start with a lower case like is Java. So we would have `$scope.mainController` instead of `$scope.MainController`

**Comment by deepu105** [comment]
Dude that would  be hell lot of refactoring for something which is not so trivial. I mean conventions are opinionated and I would say its not so difficult to understand the current JH convention which is close to what most of angular world follows.
Also if someone is moving from JSP to angular they are expected to learn angular in the first place and trust me the naming convention wont be least of their concern while learning angular

**Comment by atomfrede** [comment]
I would like to keep the current conventions. JH helps java developers to understand and learn best practice JS and JS developers to get started with best practice java code.

**Comment by jdubois** [comment]
Yes the idea is to have the JS conventions on the JS side, and the Java conventions on the Java side.

BTW, I'm not totally sure of our JS conventions, as I didn't code this myself.

So we will keep it that way.

@michaelisvy @deepu105 do you know that you both live in Singapore? Do you already know each other?

**Comment by deepu105** [comment]
@jdubois ha ha we just knew yesterday, we are planning to meet up and evangelize JH to the spring community here :smile:

**Comment by jdubois** [comment]
@deepu105 @michaelisvy great!! And I should meet Michaël this summer in Paris :-)

**Comment by michaelisvy** [comment]
@jdubois @deepu105 yes we're talking about doing a User Group event on Angular JS and JHipster early July. Hopefully we can make it happen :).
Thanks for the clarification on the naming conventions.
