### ISSUE TITLE
Cannot find module 'ejs' when running jhipster 2.15.1 

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1578]
Fresh install of node 0.12.4 using nvm on Ubuntu 15.04 64 bits, I followed the installation instructions of the jhipster site.

jhipster: 2.15.1 
yo : 1.4.7

Got this error when running yo jhipster*;
I fixed it with 'npm install ejs'.

$ yo jhipster
module.js:338
    throw err;
          ^
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/gael/jhipster/sfox/node_modules/generator-jhipster/app/index.js:13:11)

**Comment by deepu105** [comment]
but its in the dependencies and should get installed in npm install rite
```
"devDependencies": {
    "grunt": "0.4.5",
    "mocha": "1.21.5",
    "ejs": "2.3.1"
  },
```

**Comment by seghers** [comment]
@gmarziou Had the same err, Did the same solution

**Comment by KuchiVanDerK** [comment]
I had the same Problem
OSX Yosemite 10.10.3
npm install -g ejs
did the trick

**Comment by gmarziou** [comment]
@deepu105 unless I'm wrong these are the dependencies of the generated project, here the project has not been generated yet.

**Comment by gmarziou** [comment]
@KuchiVanDerK using -g could be a source of problems too, rather install locally

**Comment by gmarziou** [comment]
OK, it's my fault I did not install generator-jhipster globally. So, I failed foliowing the instructions till the end :(

**Comment by gmarziou** [comment]
Spoken too quick, the problem is still here even after installing genertor-jhipster globally.

~~~~
ls ~/.nvm/versions/node/v0.12.4/lib/node_modules/generator-jhipster/node_modules
chalk  cheerio  html-wiring  insight  mkdirp  shelljs  underscore.string  yeoman-generator  yo
~~~~

ejs is missing so I guess something is wrong in package.json

Maybe ejs should be in dependencies rather than devDependencies

**Comment by jdubois** [comment]
Maybe I shouldn't have put it in the "devDependencies", but in the "dependencies"?
As this is installed on my laptop, I don't see the difference... That would mean it fails for everybody!!
And it's hard to test for me.

**Comment by jdubois** [comment]
Yes, looks like an issue, I'm correcting this ASAP.
I wonder why we didn't have more bug requests on this??? Anyone?

**Comment by deepu105** [comment]
@gmarziou sorry i got it mixed up too i guess, i also didn't have any issues may be coz i had ejs installed while working on generator code

**Comment by gmarziou** [comment]
Yes it was probably the same with all people working on jhipster, I could reproduce it only because I installed a new version of node using nvm.
