### ISSUE TITLE
Update Keycloak  version to v15

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#15783]
##### **Overview of the feature request**

See https://www.keycloak.org/2021/07/keycloak-1500-released.html

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
Ping @vishal423

**Comment by vishal423** [comment]
I will take a look in a day or two

**Comment by pascalgrimaud** [comment]
Keep it

**Comment by pascalgrimaud** [comment]
Increasing the bounty as it's more work than expected
