### ISSUE TITLE
Provide a custom prefix for generator tasks

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#15784]
##### **Overview of the feature request**

Add a custom prefix for tasks and allow public methods without `_` prefix.

##### **Motivation for or Use Case**

Yeoman’s conventions makes every Generator prototypes method/getter without `_` prefix a task.
As the generator becomes more complex and extensible, public methods are required and must be prefixed with `_` which is a private method convention.

This causes confusion and makes the source code dirty.

Example of a buggy public method implementation, where `printHello` will be queued as a task.
```
class extends Generator {
  get initializing() {
    return {
      // Generator task (initializing => sayHello).
      sayHello() {
        this.printHello();
      }
    }
  }

  // Generator task (default => printHello).
  printHello() {
    console.log(‘hello’);
  }
}
```

Example of a correct public method implementation.
```
class extends Generator {
  get initializing() {
    return {
      // Generator task (initializing => sayHello).
      sayHello() {
        this.printHello();
      }
    }
  }

  /**
   * @public
   * Print hello message
   */
  _printHello() {
    console.log(‘hello’);
  }
}
```

##### **Proposed solution**

Make generators more compliant with javascript conventions.
- Change yeoman’s task to use a prefix, api will not need ‘_’ prefix.
```
class extends Generator {
  get '>initializing'() {
    return {
      // Generator task (initializing => sayHello).
      sayHello() {
        this.printHello();
      }
    }
  }

  /**
   * Print hello message
   */
  printHello() {
    console.log(‘hello’);
  }
}
```

##### **Implementation**

- Migrate every sub-generator to new conventions.
- Allow blueprints to opt-in to new conventions.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Done through your RFP
