### ISSUE TITLE
Cleanup some option

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#15815]
##### **Overview of the feature request**

There are some options that are not relavant.

When selecting a NoSQL database, the dev and the prod configuration is using that exact same datasource.
As an opposite, dev and prod database can be different when the user want a SQL one.

So here, I guess that we can simplify our options:

`databaseType` can only be `sql, cassandra, mongodb, neo4j, couchbase, no`
`devDatabaseType` and `prodDatabaseType` can only be `mysql, mariadb, mssql, postgresql, oracle, h2Disk, h2Mem`

There's no point using devDatabaseType/prodDatabaseType for noSql database, neither any useful case to use `databaseType=mysql`

If you're ok, I can cleanup derived constants and templates that are not following these guidelines

##### **Motivation for or Use Case**

A cleanup can be achieved to simplify our template and make our dsl more comprehensive.

##### **Related issues or PR**

#14235 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Yes. I think they were added recently.
Those configs resides inside sql generator in my modular prototype.

**Comment by Tcharl** [comment]
Keep opened
