### ISSUE TITLE
Not auto import classes when using LocalDate

### ISSUE THREAD

**Issue by Qinwroks** [jhipster/generator-jhipster#1582]
see attache file
![51d5ee36-d500-442b-b97c-f16e994a0caa](https://cloud.githubusercontent.com/assets/728884/8029453/f3e019ec-0def-11e5-9ea0-dcb32c934b70.png)

**Comment by jdubois** [comment]
I'm sorry but I don't understand: do you mean it's not imported by default?

Without your app version number, and the generator options you used, it's impossible for me to test this. Can you provide more information? An error report? In the meantime I'm closing this as I can't answer you.

**Comment by warleyc** [comment]
FYI
That happen when you add mannualy the date in "entity.json" file and forget to change this line in the same JSON file :
 "fieldsContainDateTime": false,
 "fieldsContainDate": false,
