### ISSUE TITLE
manage translations?

### ISSUE THREAD

**Issue by Fazerty** [jhipster/generator-jhipster#1585]
I would like to know how you manage the translations.
There several languages, for each we have several files, and it becomes rapidly difficult to manage.
How do find new string to translate, or unused?
Do you have a tool or is it done manually?

**Comment by jdubois** [comment]
I have some tooling, for the Java part -> my IDE understands the Java resource files
For the JavaScript part I do it manually, I don't think some tooling exists for that, but I haven't looked for that. You could ask the Angular Translate team for that, they probably know better than me.
