### ISSUE TITLE
LocalDates are not correctly handled (at least not in Zurich). between frontend and Backend

### ISSUE THREAD

**Issue by smurve** [jhipster/generator-jhipster#1586]
### Generated code does not correctly reflect the semantics of AngularJS and Joda time APIs

When a user enters a date, she usually means "as of my current calendar", or "considering my timezone and my day light saving settings". Now, AngularJS considers the browsers time zone and converts the date into a date time like "midnight early that day, expressed as of ZULU time".

For example: AngularJS will take the String "02-09-2015" and (in my case: Zürich in the summer) correctly interprets it as "01-09-2015T22:00:00Z"

The auto-generated backend somehow misses the semantics here.

When using LocalDate on entities, the corresponding field is created as

    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentLocalDate")
    @JsonSerialize(using = CustomLocalDateSerializer.class)
    @JsonDeserialize(using = ISO8601LocalDateDeserializer.class)
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

which puts the ISO8601LocalDateDeserializer in charge, but this one fails:

On the back-end, the current ISO8601LocalDateDeserializer calculates
```java
            return ISODateTimeFormat.dateTimeParser().parseLocalDate(str);
```
which simply disregards the 22 hours and ends up on 01-09-2015.

What you really want is this **SOLUTION**

```java
            return ISODateTimeFormat.dateTimeParser().parseDateTime(str).toLocalDate();
```

which correctly considers the Zulu Time Zone referred to by AngularJS (or the browser), and then disregards the time zone, which makes, because disregarding the time zone is exactly what humans (apart from a special breed of engineers and scientists) do when they enter a date anywhere.

Quintessence: Frontend and backend (and database) need to think the same way. Then things work fine.

Thx for considering this.

**Comment by jdubois** [comment]
Yes this part of the code should be improved, I will definitely consider your solution.

**Comment by gzsombor** [comment]
Yes, that's a good solution, I've fixed it on my branch a couple of month ago : https://github.com/gzsombor/generator-jhipster/commit/45af84106e8cbffe7a40647817afd3800321ca74
