### ISSUE TITLE
Integrate generator-jhipster-blueprint into generator-jhipster

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#15869]
##### **Overview of the feature request**

Move https://github.com/jhipster/generator-jhipster-blueprint generator into this repository.

##### **Motivation for or Use Case**

- Last release of generator-jhipster-blueprint is based on JHipster 6, it will easy maintenance.

- With https://github.com/jhipster/generator-jhipster/issues/15490 proposal, we are splitting the generators into many others.
Modular generators will make blueprints more coupled with the main generator.

- Migrate the ~blueprint generator and~ generated blueprints to mjs. Node ecosystem already started the migration.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Keep open.

**Comment by deepu105** [comment]
Let's do this. We really need to make it easier to make blueprints

**Comment by pascalgrimaud** [comment]
Huge work here, so I'm adding a big bounty
plz claim it @mshima

**Comment by mshima** [comment]
Thanks @pascalgrimaud, bounty claimed https://opencollective.com/generator-jhipster/expenses/71473.

Documentation is in progress at https://github.com/jhipster/jhipster.github.io/pull/1198.
I plan to add migration progress to modules and deprecate generator-jhipster-module too.
I will open a bug report to document generator-jhipster-module deprecation.

**Comment by pascalgrimaud** [comment]
@mshima : approved

Tell me if I should archive generator-jhipster-module, as I already did this for generator-jhipster-blueprint
