### ISSUE TITLE
Language 'names' written in own language?

### ISSUE THREAD

**Issue by seghers** [jhipster/generator-jhipster#1588]
Wouldn't it be clearer for the end user if the languages were written in there native languages.

eg.
### now: x files (1 for every language)
en/language.json:
```
{
    "language": {
        "en": "English",
        "fr": "French",
        "de": "German",
        "it": "Italian",
        "ja": "Japanese",
        "ru": "Russian"
    }
}
```
fr/language.json:
```
{
    "language": {
        "en": "Anglais",
        "fr": "Français",
        "de": "Allemand",
        "it": "Italien",
        "ja": "Japonais",
        "ru": "Russe"
    }
}
```
...

### possible: 1 file
language.json:
```
{
    "language": {
        "en": "English",
        "fr": "Français",
        "de": "Deutsch",
        "it": "Italiano",
        "ja": "日本語",
        "ru": "Русский"
    }
}
```

**Industry examples:**
Wikipedia languages:
![Wikipedia languages](http://i58.tinypic.com/50gxvl.png)

Google languages:
![Google languages](http://i58.tinypic.com/kdswo1.png)

**Comment by jdubois** [comment]
From a UI point of view I don't know.

From a technical point of view, here is why I did this:

- I had trouble with some encodings, so some characters where not possible to display. I'm not sure this can be solved, at least I don't know how.
- It's the only way I found to order languages (or the order changes depending on the language, like for "German" which is "Allemand" in French)

**Comment by seghers** [comment]
@jdubois Thank you for your fast response.

I'm not following your technical points:
- All characters I copied for the example are from within the codebase.
- There would be no need for changing the order depending on the language because the language options would never translate.

**Comment by jdubois** [comment]
@seghers 

For the encoding: it caused problems in the rest of the application, I had lots of wrong characters encodings on my web app. The issue is with mixing characters.

**Comment by KuchiVanDerK** [comment]
From usability perspective I would highly appreciate @seghers suggestion.
For example if the language is on Polish:
"en": "Angielski",
"fr": "Francuski",
"de": "Niemiecki",
"pl": "Polski",

I wouldn't know which one is English, French or German ;)

**Comment by seghers** [comment]
or it could be English + native

eg.
English/English
Dutch/Nederlands
Simplified Chinese/简体中文

**Comment by tagliola** [comment]
I would suggest only using the native language. Why pick someone if you
can't read it? I think all major language pickers (iOS, Windows, Android)
use that system.

**Comment by jdubois** [comment]
From the UI point of view I agree with you.

So as far as I'm concerned it's just a technical issue: if you are sure it works, can you make a PR? You might do it differently from what I did.
I will check it, and we will try to find someone using a non-latin alphabet to check it too, and then I will merge it.

**Comment by seghers** [comment]
I'll try to get it working locally and than a first pr.

source: https://scotch.io/tutorials/internationalization-of-angularjs-applications
