### ISSUE TITLE
Not working in new Macbook M1

### ISSUE THREAD

**Issue by tsendee0409** [jhipster/generator-jhipster#15881]
I am used to [https://hub.docker.com/r/jhipster/jhipster](https://hub.docker.com/r/jhipster/jhipster) in docker. I'v recently bought a new Macbook pro M1. Unfortunately, jhipster container doesn't work in M1. Only linux/amd64 is available in the docker hub. 
Is linux/arm64/v8 going to be supported?

**Comment by tsendee0409** [comment]
Hi! Matt, this is not a Docker issue. It is really up to you. You can add multi-arch when you build a docker image. I think you can use docker buildx to build multi-arch.

Please, check this out!
[https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)
[https://www.docker.com/blog/multi-platform-docker-builds/](https://www.docker.com/blog/multi-platform-docker-builds/)

**Comment by tsendee0409** [comment]
@mraible Could you re-open this issue?

**Comment by jdubois** [comment]
Yes, this is also why we bought M1s to several team members at the end of last year.
I'll need to buy a M1 for myself so I can work on this :-)

**Comment by pascalgrimaud** [comment]
Yes @jdubois you should. Just do it with Open Collective!

**Comment by mshima** [comment]
A Apple m1 is far from be required to implement this.

Would be better to reimplement Dockerfile https://github.com/mshima/generator-jhipster/blob/main/Dockerfile to use layers.
And pull arm64 versions of the base files.

But IMO there was a blocker: there was no official arm64 version of Java 11.
I will take a look if that changed.

**Comment by jdubois** [comment]
There should be a build from Microsoft (using our build of OpenJDK), but I didn't try them as I don't have a M1. I still need it to test and run the build.

**Comment by mshima** [comment]
You can create an run a cross-platform image using (at least worked while building amd64 from a M1):
```
docker build . -t jhipster-arm64 --platform linux/arm64
```

The native is in the top and cross-platform is in the bottom.
<img width="341" alt="Captura de Tela 2021-09-07 às 08 50 59" src="https://user-images.githubusercontent.com/1417183/132339975-2d105c85-7ca7-499c-b9eb-a217857e150f.png">

**Comment by mshima** [comment]
I need guidance to test this image.

**Comment by pascalgrimaud** [comment]
@mshima : you can try these following commands at https://github.com/hipster-labs/jhipster-daily-builds/blob/main/test-integration/scripts/26-tests-docker.sh

If you can generate a JHipster project, it works :-)

**Comment by tsendee0409** [comment]
Hi, jhipster v7.2.0 was recently released. But the official docker image of v7.2.0 has not been pushed to https://hub.docker.com/r/jhipster/jhipster

**Comment by tsendee0409** [comment]
@pascalgrimaud can you push it?

**Comment by pascalgrimaud** [comment]
@tsendee0409 : done!

The new image v7.2.0 is available: https://hub.docker.com/r/jhipster/jhipster/tags?page=1&ordering=last_updated

**Comment by tsendee0409** [comment]
@pascalgrimaud thanks. But linux/arm64 is not available. This means Some developers who have A1 apple could not pull and run it.

**Comment by pascalgrimaud** [comment]
Yes, I know linux/arm64 is not available yet, and it's a subject we need to work.
We have several issues, related to Docker:
- build new images, working with amd64 + arm64
- add workflow to push image to Docker Hub, as it's not automated any more

But, in the meantimes, you can clone the project, use main branch or tag version, and build the image to use it locally.

**Comment by tsendee0409** [comment]
Image v7.2.0 for arm64 is available. I built and pushed it to https://hub.docker.com/r/novelsoft/jhipster/tags?page=1&ordering=last_updated

**Comment by mshima** [comment]
Snapshots for amd64 and arm64 are available at GitHub containers registry.
https://github.com/jhipster/generator-jhipster/pkgs/container/generator-jhipster

**Comment by tsendee0409** [comment]
@mshima, it hasn't a version tag to pull the image on https://github.com/jhipster/generator-jhipster/pkgs/container/generator-jhipster/versions
Can you add a tag to the repo?

**Comment by DanielFran** [comment]
@tsendee0409 I believe what you have actually is a docker image based on the main only
For next jhipster version you will have the tagged version

**Comment by mshima** [comment]
Would be better if @pascalgrimaud could publish arm64 by running the docker build command with `--platform linux/arm64` option.

**Comment by mshima** [comment]
I’ve created v7.2.0-0 branch.
But workflow dispatch needs the workflow to exist at the branch.
Will add later.

**Comment by mshima** [comment]
> I tried to build, but it doesn't work:
> 
> * `docker build . -t jhipster/jhipster:v7.2.0-arm64 --platform linux/arm64`
> * `docker push jhipster/jhipster:v7.2.0-arm64`
>   ![Docker_JHipster](https://user-images.githubusercontent.com/9156882/134186584-048c48d1-636d-4974-baad-bec33715c367.png)

Replace build with buildx then. I probably have it by default.

**Comment by mshima** [comment]
Published at https://github.com/jhipster/generator-jhipster/pkgs/container/generator-jhipsterat 7.2.0-0 tag.
