### ISSUE TITLE
PATCH request should update collections

### ISSUE THREAD

**Issue by agriboss** [jhipster/generator-jhipster#15887]
##### **Overview of the feature request**

PATCH will not currently update relationships.  For example, calling patch on a child while passing a new parent will return 200 OK response, but the relationship will not in fact be updated in the database.  

##### **Motivation for or Use Case**

PATCH seems preferable to PUT for a lot of use cases since you do not need to pass the entire object to save one or two properties.  It would make sense to allow relationships to be updated in the same manner.  

##### **Related issues or PR**

This was mentioned when PATCH support was added recently https://github.com/jhipster/generator-jhipster/pull/12507

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
This is currently out of scope as it would be quite complex to do with code generation for all type of relationships and DBs, if you have any simple solution, please suggest with PR
