### ISSUE TITLE
Cassandra OAuth2 store

### ISSUE THREAD

**Issue by afedulov** [jhipster/generator-jhipster#1591]
Are there any specific technical difficulties that prevent support for Cassanrda OAuth2 tokens store (analogous to custom MongoDB Spring Security Oauth2 store) or did no one just address this feature yet?

**Comment by jdubois** [comment]
No technical difficulties, it's just that the implementation needs to be coded.

At the moment no one has volunteered to do it, and I will not do it because I don't need it.
