### ISSUE TITLE
GatewayAutoConfiguration required a bean of type ServerCodecConfigurer that could not be found.

### ISSUE THREAD

**Issue by asgh-mh** [jhipster/generator-jhipster#15933]
##### **Overview of the issue**

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method modifyRequestBodyGatewayFilterFactory in org.springframework.cloud.gateway.config.GatewayAutoConfiguration required a bean of type 'org.springframework.http.codec.ServerCodecConfigurer' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.http.codec.ServerCodecConfigurer' in your configuration.


```
##### **Motivation for or Use Case**

JHipster gateway won't start

##### **Reproduce the error**

Use the attached .yo.json and generate the code, then start a registry and try to run.

(I personally removed all dependencies on hibernate, but I don't believe it's necessary.)

##### **Related issues**

Related to #15545 

##### **Suggest a Fix**

People suggested the following code:

```
    implementation( "org.springframework.cloud:spring-cloud-starter-gateway") {
        exclude module : 'spring-cloud-starter'
        exclude module : 'spring-boot-starter-webflux'
    }
```

But doing that just makes the following error:

```
Parameter 0 of constructor in com.magellanhealth.mrxassist.gateway.web.rest.GatewayResource required a bean of type 'org.springframework.cloud.gateway.route.RouteLocator' that could not be found.
```

##### **JHipster Version(s)**

Version 7.1.0

##### **JHipster configuration**

```
m-rx-assist-gateway@0.0.0 /Source/a/7.1.0gate
└── generator-jhipster@7.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.foo.gateway"
    },
    "jhipsterVersion": "7.1.0",
    "applicationType": "gateway",
    "baseName": "FooGateway",
    "packageName": "com.foo.gateway",
    "packageFolder": "com/foo/gateway",
    "serverPort": "7080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "enableSocialSignIn": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true,
    "embeddableLaunchScript": false,
    "creationTimestamp": 1626477542362,
    "blueprints": [],
    "clientFramework": "angularX",
    "withAdminUi": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "reactive": false,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": true,
    "pages": [],
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "entities": []
  }
}

</pre>
</details>

##### **Browsers and Operating System**

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
A non-reactive gateway is not supported in JHipster 7. This is because Spring Cloud removed support for Zuul in Spring Boot 2.4 and we were forced to make Spring Cloud Gateway the only option for gateways. 

If you change your `.yo-rc.json` to have `"reactive": true`, everything will work.

The original ticket is at https://github.com/jhipster/generator-jhipster/issues/13855. 

@pascalgrimaud If reactive == false and gateway == true, shouldn't it force reactive?

**Comment by henry2man** [comment]
Just for reference, I've found the same error using JHipster Online, caused by an invalid code generation: https://github.com/jhipster/jhipster-online/issues/330
