### ISSUE TITLE
issue after upgrading generator-jhipster to 2.15.2

### ISSUE THREAD

**Issue by malikhan5049** [jhipster/generator-jhipster#1594]
Hi,

After upgrading generator-jhipster to latest(2.15.2) when create an entity it puts its entry in global.json at top of the file rather than under global->menu->entities

**Comment by Qinwroks** [comment]
yes.got that issue too. like this:

![20150610173749](https://cloud.githubusercontent.com/assets/728884/8079525/a9f86024-0f97-11e5-9efd-908b77041e1f.png)

**Comment by malikhan5049** [comment]
yep exactly

**Comment by deepu105** [comment]
I dont see the issue with latest version 2.16.0. Can you try with latest version and if you still have issue can you post your `.yo-rc.json` so that others can try to reproduce.

```
"global": {
        "title": "jhipster",
        "browsehappy": "You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/?locale=en\">upgrade your browser</a> to improve your experience.",
        "menu": {
            "home": "Home",
            "entities": {
                "main": "Entities",
                "foo": "Foo",
                "bar": "Bar",
                "additionalEntity": "JHipster will add additional entities here (do not translate!)"
            },
```

**Comment by jdubois** [comment]
I guess this is because you remove the special line in this file:

`"additionalEntity": "JHipster will add additional entities here (do not translate!)"`

This is where JHipster adds the new entities, so if you remove the line, it won't understand where to write those new entries.

Can you check this?

**Comment by Qinwroks** [comment]
OK, Checked.
`"additionalEntity": "JHipster will add additional entities here (do not translate!)"` must leave it as is!
