### ISSUE TITLE
Separate admin UI

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1595]
Hello,

First, I don't want to re-open the discussion about multi modules projects.

JHipster's admin features keep on growing (e.g. user management), monitoring part is quite rich also and I'm wondering whether it would make sense to split JHipster in 2 parts: end user vs admin.

Sometimes admin UI requires a different authentication scheme and other security settings, different look and feel, longer sessions, ...

Also, it could be interesting to have one single admin webapp being able to manage/monitor several jhispter end-user applications like [spring-boot-admin](https://github.com/codecentric/spring-boot-admin) seems to do (I did not try it).

Maybe it's beyond JHipster's scope.

**Comment by deepu105** [comment]
It definitely is a practical usecase. But from what I have seen its just one usecase. I recently did an enterprise audit for almost 300 + webapps of different size and stack and among them except few apps everything else had users from same usergroup as admin who along with admin activities does end user activity as well. The monitoring part is a different scenario nearly all of this application has monitoring in one form or other (jmx, tivoli, classic logs with monitoring shell scrips etc) but this was never exposed to users but where managed by some ams vendor 

So if this is split then it will hood to have as an option instead of being the default

**Comment by deepu105** [comment]
Btw spring boot admin looks really awesome

**Comment by gmarziou** [comment]
You got good points. 

JHipster could keep all custom UI for user management, swagger api and related UI as mandatory included and for monitoring UI on top of standard protocols like JMX use an external webapp like [spring-boot-admin](https://github.com/codecentric/spring-boot-admin) or [hawtio](https://github.com/hawtio/hawtio).

External monitoring UI makes sense to me also when hosting your app in the cloud where you may use dashboard provided by the cloud platform.

It could be seen also as an opportunity for JHipster to focus on user-facing features.

**Comment by BhawaniSingh** [comment]
hawtio is better than spring-boot-admin


Regards
Bhawani Singh

**Comment by jdubois** [comment]
I agree.

Besides, I would like JHipster to work with [CloudFoundry UAA](https://github.com/cloudfoundry/uaa):
- this would be needed if we want to have a "micro service" architecture in JHipster 3 (which looks more and more like what people want)
- it shouldn't be difficult to do, as we already support OAuth2

The main issue, for me, is that it looks very complex to do: so my main question, is how do you intend to do it?
And how do you want to package your "admin UI"?

**Comment by gmarziou** [comment]
Well, I'm not sure but it seems that hawtio and spring-boot have 2 points of integration:
- embedding hawtio in a spring-boot application
- spring-boot plugin in hawtio to display spring-boot metrics

I may have misunderstood hawtio model but it seems to me that JHipster could provide an hawtio-jhipster-plugin as a jar to be loaded into hawtio whether hawtio is running as a separate webapp or is embedded into JHipster app.

**Comment by deepu105** [comment]
I think this is something worth considering for 3.0

**Comment by jdubois** [comment]
This has been opened for 6 months and we still have no plan on doing this -> should we keep this open? I don't want to have long-running issues

**Comment by atomfrede** [comment]
This looks like a great candidate for a new jhipster module :)

**Comment by jdubois** [comment]
OK I'm closing this as it has no progress in 6 months.... If we do a "micro services" approach, I have some ideas on how to implement that, but it would be in another user story
