### ISSUE TITLE
always get error when import jdl file

### ISSUE THREAD

**Issue by yudar1024** [jhipster/generator-jhipster#15960]
##### **Overview of the issue**

when use jhipster import-jdl . error always happened

##### **Motivation for or Use Case**

jhipster can't generator entity related java file

##### **Reproduce the error**

1 install jhipster
2 init a project from jhipster online or create one from jhipster
3 get the example jdl from jhipster online
4 run jhipster import-jdl example.jdl

```java
Error: Error parsing file src\main\java\com\mycompany\myapp\repository\CountryRepository.java: Error: Sad sad panda, parsing errors detected in line: 12, column: 44!
Expecting token of type --> Identifier <-- but found --> '<' <--!
        ->compilationUnit
        ->ordinaryCompilationUnit
        ->typeDeclaration
        ->interfaceDeclaration
        ->normalInterfaceDeclaration
        ->extendsInterfaces
        ->interfaceTypeList
        ->interfaceType
        ->classType
    at Object.parse (E:\github\dddmode\node_modules\java-parser\src\index.js:41:11)
    at Object.parse (E:\github\dddmode\node_modules\prettier-plugin-java\src\parser.js:6:26)
    at Object.parse$a [as parse] (E:\github\dddmode\node_modules\prettier\index.js:13652:19)
    at coreFormat (E:\github\dddmode\node_modules\prettier\index.js:15183:16)
    at formatWithCursor$1 (E:\github\dddmode\node_modules\prettier\index.js:15423:14)
    at E:\github\dddmode\node_modules\prettier\index.js:60171:12
    at Object.format (E:\github\dddmode\node_modules\prettier\index.js:60191:12)
    at E:\github\dddmode\node_modules\generator-jhipster\generators\generator-transforms.js:53:31
    at async run (E:\github\dddmode\node_modules\p-queue\dist\index.js:163:29)

At: package com.mycompany.myapp.repository;

import com.mycompany.myapp.domain.Country;

import org.springframework.stereotype.Repository;

/**
 * Spring Data  repository for the Country entity.
 */
@SuppressWarnings("unused")
@Repository
public interface CountryRepository extends <Country, Long> {
}

    at E:\github\dddmode\node_modules\generator-jhipster\generators\generator-transforms.js:65:20
    at async run (E:\github\dddmode\node_modules\p-queue\dist\index.js:163:29)
ERROR! Error parsing file src\main\java\com\mycompany\myapp\repository\CountryRepository.java: Error: Sad sad panda, parsing errors detected in line: 12, column: 44!
Expecting token of type --> Identifier <-- but found --> '<' <--!
        ->compilationUnit
        ->ordinaryCompilationUnit
        ->typeDeclaration
        ->interfaceDeclaration
        ->normalInterfaceDeclaration
        ->extendsInterfaces
        ->interfaceTypeList
        ->interfaceType
        ->classType
    at Object.parse (E:\github\dddmode\node_modules\java-parser\src\index.js:41:11)
    at Object.parse (E:\github\dddmode\node_modules\prettier-plugin-java\src\parser.js:6:26)
    at Object.parse$a [as parse] (E:\github\dddmode\node_modules\prettier\index.js:13652:19)
    at coreFormat (E:\github\dddmode\node_modules\prettier\index.js:15183:16)
    at formatWithCursor$1 (E:\github\dddmode\node_modules\prettier\index.js:15423:14)
    at E:\github\dddmode\node_modules\prettier\index.js:60171:12
    at Object.format (E:\github\dddmode\node_modules\prettier\index.js:60191:12)
    at E:\github\dddmode\node_modules\generator-jhipster\generators\generator-transforms.js:53:31
    at async run (E:\github\dddmode\node_modules\p-queue\dist\index.js:163:29)

At: package com.mycompany.myapp.repository;

import com.mycompany.myapp.domain.Country;

import org.springframework.stereotype.Repository;

/**
 * Spring Data  repository for the Country entity.
 */
@SuppressWarnings("unused")
@Repository
public interface CountryRepository extends <Country, Long> {
}

Error: Error parsing file src\main\java\com\mycompany\myapp\repository\CountryRepository.java: Error: Sad sad panda, parsing errors detected in line: 12, column: 44!
Expecting token of type --> Identifier <-- but found --> '<' <--!
        ->compilationUnit
        ->ordinaryCompilationUnit
        ->typeDeclaration
        ->interfaceDeclaration
        ->normalInterfaceDeclaration
        ->extendsInterfaces
        ->interfaceTypeList
        ->interfaceType
        ->classType
    at Object.parse (E:\github\dddmode\node_modules\java-parser\src\index.js:41:11)
    at Object.parse (E:\github\dddmode\node_modules\prettier-plugin-java\src\parser.js:6:26)
    at Object.parse$a [as parse] (E:\github\dddmode\node_modules\prettier\index.js:13652:19)
    at coreFormat (E:\github\dddmode\node_modules\prettier\index.js:15183:16)
    at formatWithCursor$1 (E:\github\dddmode\node_modules\prettier\index.js:15423:14)
    at E:\github\dddmode\node_modules\prettier\index.js:60171:12
    at Object.format (E:\github\dddmode\node_modules\prettier\index.js:60191:12)
    at E:\github\dddmode\node_modules\generator-jhipster\generators\generator-transforms.js:53:31
    at async run (E:\github\dddmode\node_modules\p-queue\dist\index.js:163:29)

At: package com.mycompany.myapp.repository;

import com.mycompany.myapp.domain.Country;

import org.springframework.stereotype.Repository;

/**
 * Spring Data  repository for the Country entity.
 */
@SuppressWarnings("unused")
@Repository
public interface CountryRepository extends <Country, Long> {
}

    at E:\github\dddmode\node_modules\generator-jhipster\generators\generator-transforms.js:65:20
    at async run (E:\github\dddmode\node_modules\p-queue\dist\index.js:163:29)
   create src\main\webapp\app\entities\region\region.component.ts
```

##### **JHipster Version(s)**
7.1

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
dddmode@0.0.0 E:\github\dddmode
`-- generator-jhipster@7.1.0   

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "dddmode",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1628837755120,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "databaseType": "no",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "cosmo",
    "clientThemeVariant": "primary",
    "enableTranslation": false,
    "nativeLanguage": "zh-cn",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "fr"],
    "entities": ["Region", "Country", "Location", "Department", "Task", "Employee", "Job", "JobHistory"],
    "lastLiquibaseTimestamp": 1628839887000
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

git version 2.31.1.windows.1

node: v14.17.5

npm: 6.14.14

If you have a JDL please wrap it in below structure
 <details>
<summary>JDL entity definitions</summary>

<pre>
entity Region {
  regionName String
}
entity Country {
  countryName String
}
/**
 * not an ignored comment
 */
entity Location {
  streetAddress String
  postalCode String
  city String
  stateProvince String
}
/**
 * not an ignored comment
 */
entity Department {
  departmentName String required
}
/**
 * Task entity.\n@author The JHipster team.
 */
entity Task {
  title String
  description String
}
/**
 * The Employee entity.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String
  lastName String
  email String
  phoneNumber String
  hireDate Instant
  salary Long
  commissionPct Long
}
entity Job {
  jobTitle String
  minSalary Long
  maxSalary Long
}
entity JobHistory {
  startDate Instant
  endDate Instant
  language Language
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region} to Region
  Location{country} to Country
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to
  /**
   * Another side of the same relationship
   */
  Employee{department}
  Employee{job} to Job{employee}
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

</pre>
</details>

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Strange that it generates repository if you've choosen `databaseType: no` I don't think we have tested a monolith without a database though: what's the goal of your app?

**Comment by gmarziou** [comment]
Looks similar #14271 for me, entities without database is a strange concept

**Comment by yudar1024** [comment]
> Strange that it generates repository if you've choosen `databaseType: no` I don't think we have tested a monolith without a database though: what's the goal of your app?

the  goal is just run  temp demo, show the benefits of  jhipster , and don't want prepare related DB .

**Comment by gmarziou** [comment]
What's wrong with using a memory H2 database for your demo?

**Comment by pascalgrimaud** [comment]
I'm closing this as there is no error here.
Adding entities to an application without database is strange :-)
