### ISSUE TITLE
Jhipster 7.1.0 import-jdl (or jdl) command regenerate all existing entity #1

### ISSUE THREAD

**Issue by duonglv1993** [jhipster/generator-jhipster#15967]
##### **Overview of the issue**

When you define new entities in `.jdl` (in my case I named it is app.jdl) file, then use `jhipster import-jdl (or jdl)` command to generate entity, all existing entities will be regenerated (expected only new entities will be generated). I try use `jhipster jdl --skip-regenerate app.jdl`, but jhipster still regenerate all entities.

##### **Motivation for or Use Case**

Jhipster (7.1.0) seems that default is to regenerate all entities, but when I use `--skip-regenerate` option, it cannot help. In my previous project, I use jhipster 6.8.0, it doesn't regenerate existing entities (only generate new entities or modifies entity).

##### **Reproduce the error**

1. Create new application with Jhipster 7.1.0.
2. Create new file `app.jdl` with one entity (eg: employee entity name), then use `jhipster jdl app.jdl` to generate entity.
3. Add more new entity to `app.jdl` (eg: department entity name), the use  `jhipster jdl app.jdl`, now both new entity (department) and existing entity (employee) are generated (expected only one department entity is generated).

##### **Related issues**

.

##### **Suggest a Fix**

.

##### **JHipster Version(s)**

Jhipster 7.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "issuejhipster",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1628835510026,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.issuejhipster",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/issuejhipster",
    "jwtSecretKey": "",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"],
    "entities": ["Employee"],
    "lastLiquibaseTimestamp": 1628836693000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Employee (employees) {
  name String maxlength(50) required
  email String required
  birthDate Instant required
}
dto * with mapstruct
paginate * with pagination
service * with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.22.0.windows.1

node: v12.18.4

npm: 6.14.6

Docker version 20.10.7, build f0df350

docker-compose version 1.29.2, build 5becea4c

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
<details>
<pre>
{
  "name": "Employee",
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String",
      "fieldValidateRules": ["maxlength", "required"],
      "fieldValidateRulesMaxlength": "50"
    },
    {
      "fieldName": "email",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "birthDate",
      "fieldType": "Instant",
      "fieldValidateRules": ["required"]
    }
  ],
  "relationships": [],
  "entityTableName": "employees",
  "dto": "mapstruct",
  "pagination": "pagination",
  "service": "serviceClass",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "applications": "*",
  "changelogDate": "20210813063813"
}
</pre>
</details>

##### **Browsers and Operating System**

OS: Windows 10 64-bit

**Comment by Tcharl** [comment]
Why is it an issue? it is the expected behaviour since it keeps everything consistent.
If you don't want some of your entities to be regenerate, say 'skip' when it asks to override you entities or add the relative path to a .yo-resolve file at the root of your project. e.g.
`src/main/java/corp/domain/MyEntity.java skip`

**Comment by duonglv1993** [comment]
> Why is it an issue? it is the expected behaviour since it keeps everything consistent.
> If you don't want some of your entities to be regenerate, say 'skip' when it asks to override you entities or add the relative path to a .yo-resolve file at the root of your project. e.g.
> `src/main/java/corp/domain/MyEntity.java skip`

resource files, service,... must be customized according to your own business. it's never really exactly the same as the generated file.
say `skip` override don't have `skip all` option, I have a lot of file generated in my project (more than 1000 files), I have to enter `n` 1000 times to say skip override files. I think it's really unreasonable.

**Comment by jasonmarco** [comment]
Your issue seems to be related to mine:  [https://github.com/jhipster/generator-jhipster/issues/15366](https://github.com/jhipster/generator-jhipster/issues/15366)

As a workaround, you can add either the skipClient, or skipServer properties to each of your entity files in the .jhipster folder. When Jhipster regenerates everything, it will respect these settings and not generate the client, or the server

```
{
  "name": "FooEntity",
  "skipClient": true,
  "skipServer": false,
  "changelogDate": "20210730201049"
}
```

**Comment by mshima** [comment]
`--skip-regenerate` is a jhipster 6 option that don't rewrites identical files, triggering a webpack rebuild, it's enabled by default at jhipster 7.
See `jhipster --help`.

You can use globs at .yo-resolve.
`src/main/java/corp/domain/** skip`
