### ISSUE TITLE
Jhipster build with Websocket and Vue, not authenticating or log in

### ISSUE THREAD

**Issue by wdzul78** [jhipster/generator-jhipster#15961]
##### **Overview of the issue**

I try to login into the JHipster webapp but the app couldn't authenticating when the build is using this setup;

application type > Monolithic application
base name application > jhipster
spring webflux > N
package name > com.mycompany.myapp
authentication type > HTTP Session Auth (stateful)
database type > SQL
production db > MySQL
development db > MySQL
cache > Ehcache
Hibernate 2nd Lvl cache > Y
lib mgmt > Gradle
JHipster registry > No
Websocket using spring websocket
frontend framework > vue
admin UI > Y
theme > default
int. support > Y
Junit & Jest > cypress, gatling, cucumber

##### **Motivation for or Use Case**

I want to build a monolithic app using Vue and WebSocket with user session management.

##### **Reproduce the error**

use this suggested build:
application type > Monolithic application
base name application > jhipster
spring webflux > N
package name > com.mycompany.myapp
authentication type > HTTP Session Auth (stateful)
database type > SQL
production db > MySQL
development db > MySQL
cache > Ehcache
Hibernate 2nd Lvl cache > Y
lib mgmt > Gradle
JHipster registry > No
Websocket using spring websocket
frontend framework > vue
admin UI > Y
theme > default
int. support > Y
Junit & Jest > cypress, gatling, cucumber

run the server with

gradlew -x webapp

and another open terminal to run the vue front end

npm start

The frontend page open at localhost:9000 and backend at 8080. 

##### **Related issues**

I already post through stackoverflow;
https://stackoverflow.com/questions/68360233/jhipster-build-with-websocket-and-vue-not-authenticating-or-log-in

##### **Suggest a Fix**

So far; I don't have problems logging in (authenticating) with Jhipster build with angular as the front end. 

##### **JHipster Version(s)**

NPM version 7+
JHipster version 7.1.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test-vue-web-socket@0.0.0 D:\WDzul78\Documents\GitHub\TestVueWebSocket
`-- generator-jhipster@7.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "TestVueWebSocket",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1628840548581,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "session",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "buildTool": "gradle",
    "serverSideOptions": ["websocket:spring-websocket"],
    "websocket": "spring-websocket",
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "in"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

git version 2.20.1.windows.1

node: v16.5.0

npm: 7.19.1

Docker version 20.10.7, build f0df350

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Windows 10
![Lq5bM](https://user-images.githubusercontent.com/8960575/129326660-1d623353-8aab-4699-bdc1-481869044e45.jpg)

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by swarajsaaj** [comment]
Issue is reproducible on main with `session` authentication, works fine with `jwt` though.

**Comment by pascalgrimaud** [comment]
Adding a bounty for this bug

**Comment by swarajsaaj** [comment]
I just figured out, this is due to $cookies reference not present and hence causing the login loop infinitely (due to another interpolation call, tricky one). I ll submit a PR soon.
