### ISSUE TITLE
jHipster taking too much time to start up

### ISSUE THREAD

**Issue by malikhan5049** [jhipster/generator-jhipster#1598]
Hi,

I ve created a application with jhipster-generator version 2.15.2 and the startup before i created my entities was pretty much fast but after creating almost 12 entities startup time increased to 1095 seconds (18.25 minutes) which is too much i am sure i am missing something not sure what right now anyway i ve changed logging level for spring classes to see what exactly going on meanwhile if anyone have faced this issue before please help

**Comment by jdubois** [comment]
Of course it depends on your hardware, but it shouldn't take much more than 10 seconds.

Did you have a look at Swagger? That's why I log the Swagger boot time in the console, I know it behaves badly when there are many entities (many = more than 100 normally)

**Comment by malikhan5049** [comment]
when i change log level of spring classes to debug i got below exception

org.springframework.beans.factory.support.DefaultListableBeanFactory -
Returning cached instance of singleton bean 'swaggerSpringMvcPlugin'
17:02:51 [DEBUG]
org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor
- Could not find default TaskScheduler bean
org.springframework.beans.factory.NoSuchBeanDefinitionException: No
qualifying bean of type [org.springframework.scheduling.TaskScheduler] is
defined
at
org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:371)
~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331)
~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.finishRegistration(ScheduledAnnotationBeanPostProcessor.java:183)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.onApplicationEvent(ScheduledAnnotationBeanPostProcessor.java:162)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.onApplicationEvent(ScheduledAnnotationBeanPostProcessor.java:85)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:773)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
[spring-boot-1.2.3.RELEASE.jar:1.2.3.RELEASE]
at
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
[spring-boot-1.2.3.RELEASE.jar:1.2.3.RELEASE]
at
org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
[spring-boot-1.2.3.RELEASE.jar:1.2.3.RELEASE]
at
org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
[spring-boot-1.2.3.RELEASE.jar:1.2.3.RELEASE]
at com.ews.parkswift.Application.main(Application.java:72) [classes/:na]
17:02:51 [DEBUG]
org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor
- Could not find default ScheduledExecutorService bean
org.springframework.beans.factory.NoSuchBeanDefinitionException: No
qualifying bean of type [org.springframework.scheduling.TaskScheduler] is
defined
at
org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:371)
~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331)
~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.finishRegistration(ScheduledAnnotationBeanPostProcessor.java:183)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.onApplicationEvent(ScheduledAnnotationBeanPostProcessor.java:162)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.onApplicationEvent(ScheduledAnnotationBeanPostProcessor.java:85)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:773)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
[spring-boot-1.2.3.RELEASE.jar:1.2.3.RELEASE]
at
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
at
org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
[spring-boot-1.2.3.RELEASE.jar:1.2.3.RELEASE]
at
org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
[spring-boot-1.2.3.RELEASE.jar:1.2.3.RELEASE]
at
org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
[spring-boot-1.2.3.RELEASE.jar:1.2.3.RELEASE]
at com.ews.parkswift.Application.main(Application.java:72) [classes/:na]

**Comment by malikhan5049** [comment]
guess has something to do with removeNotActivatedUsers in UserService which
is scheduled

**Comment by gmarziou** [comment]
@malikhan5049 This exception is harmless, that's why it's logged in DEBUG and Spring provides a fallback when you did not provide your own scheduler configuration.

Your log is not complete and as @jdubois said, if you set logging level to DEBUG on your code and you're not using `fast` profile you should see the init duration of swagger logged by SwaggerConfiguration:  "Started Swagger in {} ms"

If this time is too long then you may want to use fast profile at least in development.

**Comment by malikhan5049** [comment]
@Gael yes that exception wasnt the problem actually swagger was taking too
much time for two reason mainly first i used fields with type LocalDate
(joda) in some of my entities and when swagger tries to create json for an
entity which is having LocalDate fields it starts creating json for
LocalDate class which was huge and i got fields of type LocalDate at many
places in my project anyway how if fix that is i added
"directModelSubstitute(LocalDate.class, String.class)" line in
swaggerpluginconfiguration and now swagger not creating json for LocalDate
rather String and second problem was with relationships by default jhipster
jsonignore oneToMany relationship but does not ignore manyToOne,
oneToOne/manyTomany (owner side) so swagger creates json for the
relationships which jhipster dont ignore and say if A is manyToOne with B
and B is manyToOne with C and so on swagger currently will create json
until it will find an entity with no relationship that is not jsonignored
that is actually what taking most of the time i think what it should do for
the relationships type that are not jsonignored ; dont create complete json
just id is enough for example A is manyToOne with B then while creating
json for A no need to created complete json for B just Id is enough also
this will stop wud say recursive json creation for entities with
relationships

**Comment by gmarziou** [comment]
Interesting, in my project I figured I had some kind of cycles between my entities and swagger spring mvc never ended, so I just disabled it for a while. Recently I upgraded to swagger springfox (as part of #1508) and the problem has gone.
So once I get a PR for springfox, I think it would be interesting that you try again.

**Comment by gmarziou** [comment]
Another thing that helped me a lot with this issue has been to use DTOs rather than entities directly in REST controllers.

**Comment by malikhan5049** [comment]
right will try DTO approach

**Comment by jdubois** [comment]
OK, and concerning Swagger:

- We have upgraded it to SpringFox 2.0
- We have solved the dates issue

So that should work much better.

**Comment by egiovanni85** [comment]
For this problem use Dto * and add Swagger-ui dependenies  in the pom.xml file, after this you can find the documentation on http://localhost:8080/swagger-ui.html#/

I found this solution by myself but now all my team use it.

		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger-ui</artifactId>
		    <version>2.9.2</version>
		</dependency>
		<dependency>
  		  <groupId>com.github.caspar-chen</groupId>
  		  <artifactId>swagger-ui-layer</artifactId>
  		  <version>1.1.3</version>
		</dependency>

**Comment by gmarziou** [comment]
@egiovanni85 you're commenting a 4 years-old issue !

Anyway, the 2 dependencies you're referring to are only about presentation (html, css, ...) so I can't understand how this could boost up application startup time. More, JHipster uses its own version of swagger-ui/index.html because springfox-swagger-ui does not cover our needs in particular for authentication.
