### ISSUE TITLE
Why enabling LoggingAspect only in dev?

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1599]
Hello,

Does anybody know why LoggingAspect is enabled in dev only?

I was thinking of using it in prod and wanted to know whether there are any gotchas I should be aware.
Maybe @jmirc as you're the one who configured it this way.

Thanks

**Comment by jdubois** [comment]
It monitors each method call, so it adds some overhead. That's the only reason why.
Depending on how your logger is configured, it can also introduce a lock, which would be very bad for your application.
So by default we turn it off in production, but of course it's easy to turn it on.

**Comment by gmarziou** [comment]
Thanks
