### ISSUE TITLE
Entity models should still be generated when using --skip-client 7.1.0

### ISSUE THREAD

**Issue by jasonmarco** [jhipster/generator-jhipster#15997]
##### **Overview of the issue**

Entities generated with `--skip-client` do not have their `${generator.entityFileName}.model.ts`, file generated using Angular. Entities generated **without** `--skip-client` that reference these files will have failed references.

##### **Motivation for or Use Case**

Generated projects that have a mix of skipped an standard clients are not generated properly; the frontend is unusable. Jhipster generation will fail `npm test`. 

<pre>
Error: src/main/webapp/app/entities/foo/update/foo-update.component.ts:10:22 - error TS2307: Cannot find module 'app/entities/bar/bar.model' or its corresponding type declarations.
</pre>

##### **Reproduce the error**
Generate project using provided `.yo-rc.json`  and entity files. 
[yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/7001194/yo-rc.json.txt)
**Renamed to .txt as Github rejects *.json files. Removed leading `.`**

##### **Related issues**

#15967 #15366

##### **Suggest a Fix**

Seems to be an issue with the `entity-client` generator.

##### **JHipster Version(s)**

7.1.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT C:\Users\BPC\IdeaProjects\#192
`-- generator-jhipster@7.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling", "cucumber"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1629207659479,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "gl", "el", "hi", "hu", "in"],
    "cypressCoverage": false,
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "lastLiquibaseTimestamp": 1629209410000,
    "entities": ["Foo", "Bar", "Baz"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Foo {
  name String required
}
entity Bar {
  amount Integer
}
entity Baz {
  percent Double
}
relationship OneToMany {
  Bar{foos} to Foo{bar}
}
relationship ManyToMany {
  Foo{bazs} to Baz{foos}
}

dto Foo, Bar, Baz with mapstruct
service Foo, Bar with serviceImpl
service Baz with serviceClass
filter Foo
readOnly Bar, Baz
paginate Baz with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM (build 11.0.10+9-LTS, mixed mode)

git version 2.26.0.windows.1

node: v14.17.5

npm: 7.19.1

Docker version 20.10.7, build f0df350

docker-compose version 1.29.2, build 5becea4c

Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

[Bar.json.txt](https://github.com/jhipster/generator-jhipster/files/7001129/Bar.json.txt)
[Baz.json.txt](https://github.com/jhipster/generator-jhipster/files/7001131/Baz.json.txt)
[Foo.json.txt](https://github.com/jhipster/generator-jhipster/files/7001132/Foo.json.txt)
*Renamed to .txt as Github rejects *.json files

***Please note, I have added** `"skipClient": true,` **to both the** `Baz.json` **and** `Bar.json` **files as in issue** #15366
Without these additions, Jhipster will incorrectly generate the client for these entities.

##### **Browsers and Operating System**

Windows 10 19043.1165

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
No client code should be generated for skipClient entities.
You can remove back reference from the definition so that reference will not be generated by any model.

You can force jdl to don't add back references using --unilateral-relationships.

**Comment by jasonmarco** [comment]
Maybe another option such as `minimalClient` or `clientModelOnly` would be preferable? I'll close this Issue for now. This may be more of a FR, I'll gather some more information / use cases.
Thanks @mshima
