### ISSUE TITLE
JHipster 3.0

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1600]
@jdubois I know you are not a great fan of defining milestones, but wouldn't it be good to have a discussion thread for 3.0 to gather ideas as well as to give JH users like us an idea on wats coming and what we should be prepared for?

**Comment by jdubois** [comment]
@deepu105 I'll do a "roadmap" page on the website

but it's mostly driven by what people want, the time I have, etc.... Lots of external things in fact.

**Comment by gmarziou** [comment]
Drop java 7

**Comment by atomfrede** [comment]
Drop java 7 sounds great!

**Comment by deepu105** [comment]
Ya a page would be nice but can we also have this thread open for discussion, ideas and brain storming please :smile:

**Comment by deepu105** [comment]
+1 to drop java 7

**Comment by diwalak** [comment]
I think it should be based on Spring Boot 1.3 (in turn based on Spring 4.2)
They both should be out by September
http://spring.io/blog/2015/06/12/spring-boot-1-3-0-m1-available-now
https://spring.io/blog/2015/05/26/spring-framework-4-2-goes-rc1

**Comment by phouverneyuff** [comment]
We could improve the websocket. My suggestions:

1 - Move the package "dto" from "web.rest" to "web" and "web.websocket" to "web" too. DTO is just one thing and don't matter if it used by rest or websocket. What you think about it? The package mapper should be move to web too.

2 - By default create mappings to realize CRUD. The problem is that the view should be changed too. I know that will be one great change, but will be more hipster. lololol

3 - If we choose "Spring Websocket" in 'yo jhipster' and execute 'yo jhipster:entity ENTITY_NAME', then could generate the api for entity in websocket, instead of rest.

**Comment by jdubois** [comment]
OK, we'll keep this here as it's better for discussion.

- Dropping Java 7 depends on how many people still use it: currently it's 20% of users, but it's going down, so for September that might be OK
- Of course we will migrate to Spring Boot 1.3, this is not what I would call a 3.0 version :-)

Here is what I wish we could have:

- Generate an [Ansible](http://www.ansible.com/home) configuration for our whole application stack: app server, database, ElasticSearch, etc. So you could have the whole infrastructure ready, as well as the application. This would work on Vagrant at the minimum.
- Much better JHipster-UML tooling (this is a work in progress by my trainees)
- A "JHipster light" project, using [Spark](https://github.com/perwendel/spark) and [Dagger](https://github.com/square/dagger): this could have a very close programming model to what we already have, but be much more faster to develop on
- Improve the Cassandra code, so we could be the [Mean IO](https://github.com/linnovate/mean) for Java + Cassandra

And here the biggest thing I want to do, which would be the reason for the 3.0 tag: to become more "micro-service" oriented:

- This would be an option in the generator
- We would use a lot of the [Netflix stack](http://netflix.github.io/) as proposed by the Spring Cloud Neflix project. This is where Spring is going, and we would as usual follow their lead. There is a lot of work there, I let you have a look at [Spring Cloud Neflix](http://cloud.spring.io/spring-cloud-netflix/).
- We would be able to query a REST backend, using [Retrofit](https://github.com/square/retrofit), so a JHipster server could query another JHipster server.
- We would need to have an OAuth 2 server, and [CloudFoundry UAA](https://github.com/cloudfoundry/uaa) looks like the logical step

**Comment by phouverneyuff** [comment]
I like it

**Comment by gmarziou** [comment]
Interesting.

this one below is intruiguing:

> A "JHipster light" project, using Spark and Dagger: this could have a very close programming model to what we already have, but be much more faster to develop on.

Would it mean moving away from spring-boot or combining them?

**Comment by jdubois** [comment]
@gmarziou I'd just like to try a separate stack in another project, not move away at all from Spring. But if we can have a very close programming model, and that it starts up a lot faster (I'm talking less that 1 sec startup time), then that could be an interesting alternatives for some use cases.
For example, if we go "micro services", this could be useful for doing a front-end router.

**Comment by phouverneyuff** [comment]
We should take look in benchmark. Will be spark more fast, respond more request in one second, .. if we compare with spring rest?

**Comment by gmarziou** [comment]
Very interesting, I am starting looking at Dagger from Android standpoint, it'd be cool to leverage it also on server side.

**Comment by atomfrede** [comment]
@jdubois Are you planning any early access phase to get input from the "community"? Can't wait to try netflix stack and spark :)

**Comment by phouverneyuff** [comment]
I loved [retrofit](http://square.github.io/retrofit/) !

**Comment by deepu105** [comment]
Retrofit looks very hip

**Comment by seghers** [comment]
retrofit 2.0 will be great: auto retry etc...

**Comment by piedrahitac** [comment]
> We would need to have an OAuth 2 server, and CloudFoundry UAA looks like the logical step

@jdubois How do you think we should go about this? I'm about to start developing a UAA/SSO OAuth2 solution for two JHipster apps. I was looking at Dave Syer's tutorial on the Spring page, but if there's an already made solution that's more robust and the community can benefit from it, then I would be willing to give it a shot.

Another feature that I think would be useful and save a lot of time in development, is a front-end sub-generator that creates empty angular services, controllers, directives (if needed) and basic html. So if I create a custom REST endpoint, I could easily generate a boilerplate front-end code to consume it.

**Comment by deepu105** [comment]
for the regular folks :wink:  
more field types [Blob, clob etc] with file upload field
revamp UX to be more hip, sidebar menu etc (I have already done this it looks great on both mobile and desktop)
better mobile support (for eg: no popup on mobile for entities)

**Comment by phouverneyuff** [comment]
@deepu105 interesting! I agree

**Comment by gmarziou** [comment]
+1 for a menu that works better on mobile but I think it could be done any time.
I'm less concerned by entity views as in my projects I have never kept them as-is.

**Comment by gzsombor** [comment]
In my fork, there are enough changes alone for a 3.0 release :wink: 
 - separation of the edit dialog, from the listing page (with proper url handling)
 - generation of separate services for the entities for proper and clear transaction handling
 - the DTO stuff, without MapStruct
 - separate 'test' spring profile, instead of the @IntegrationTest annotation

etc :-)

**Comment by moifort** [comment]
+1 @deepu105  for more field types [Blob, clob etc] with file upload field

**Comment by jdubois** [comment]
@gzsombor yes you are correct. I'm sorry about this, I just don't have enough time to review everything, since I'm doing this on my free time. I will take some time off for JHipster 3, which will include reviewing your fork.

**Comment by pmverma** [comment]
I think JHipster is such a great project which makes ready-to-run in just minutes. And think too as the project is more than just entity generator and having CRUD on them.

Someone can also provides pure API backend so I wonder why the project should not have API versions like the one from GitHub?

**Comment by cbornet** [comment]
@piedrahitac For code generation of clients (angular, android, objc, ...) you can use https://github.com/swagger-api/swagger-codegen

**Comment by vionita** [comment]
If you are looking at different stacks in the context of microservices for JHIpster 3.0, then [QBIT](https://github.com/advantageous/qbit) looks to me like an interesting option. 
Although, for the moment, personally I prefer sticking to the current stack.

**Comment by vionita** [comment]
Ansible seems to me like not a very popular provisioning tool. I would vote Chef on first place because is more developer friendly, and Puppet on second place. And they both have very well established communities.

**Comment by deepu105** [comment]
I have done a soap/http webservice client generator extending jhipster it has below options

+ Choose between soap  or http client
+ xml or json for http
+ choose soap schema
+ provide in/out entities and in/out xml root
+ generate jaxb schema class jar
+ generate the client stub all wired up
+ optional mapstruct mapping layer to convert to and from domain entity and jaxb generated class

If there is interest we can do something like this as well

**Comment by gzsombor** [comment]
Sounds interesting ! :+1:

**Comment by deepu105** [comment]
These are the current questions I use, i guess this would be useful for enterprise users who will have to deal with lots of webservices
```
var prompts = [
        {
            type: 'list',
            name: 'protocol',
            message: '(1/' + questions + ') What protocol do you want to use?',
            choices: [
                {
                    value: 'soap',
                    name: 'SOAP with XML data format'
                },
                {
                    value: 'http',
                    name: 'HTTP'
                }
            ],
            default: 0
        },
        {
            when: function (response) {
                return (response.protocol == 'http');
            },
            type: 'list',
            name: 'dataFormat',
            message: '(2/' + questions + ') Which data format would you like to use?',
            choices: [
                {
                    value: 'xml',
                    name: 'XML'
                },
                {
                    value: 'json',
                    name: 'JSON'
                }
            ],
            default: 0
        },
        {
            when: function (response) {
                return (response.protocol == 'soap');
            },
            type: 'input',
            name: 'schemaUrl',
            validate: function (input) {
                if (/^(((https?|ftp):\/\/[^\s/$.?#].[^\s]*)|([A-Za-z]:\/\/[^<>:"\\|?*]*))$/.test(input)) return true;
                return 'The path you have provided is not a valid URL or Absolute local directory path.';
            },
            message: '(2/' + questions + ') What is your WSDL schema path/url? Provide complete URL or an Absolute local directory path',
            default: '/schema/' + this.name + '/' + this.name + '.wsdl'
        },
        {
            type: 'input',
            name: 'defaultUrl',
            validate: function (input) {
                if (/^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$/.test(input)) return true;
                return 'The URL you have provided is not valid.';
            },
            message: '(3/' + questions + ') What is the default service URL you want to connect?',
            default: ''
        },
        { 
            when: function (response) {
                return (response.protocol == 'soap');
            },
            type: 'input',
            name: 'actionUrl',
            validate: function (input) {
                if (/^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$/.test(input)) return true;
                return 'The service operation name is not valid, please provide a valid schema path.';
            },
            message: '(4/' + questions + ') What is the service operation name including schema path?',
            default: ''
        },
        {
            type: 'input',
            name: 'reqEntity',
            validate: function (input) {
                if (/^([a-zA-Z0-9_]*)$/.test(input)) return true;
                return 'The entity name cannot contain special characters.';
            },
            message: '(5/' + questions + ') What is the entity from which request has to be mapped?',
            default: ''
        },
        {
            type: 'input',
            name: 'resEntity',
            validate: function (input) {
                if (/^([a-zA-Z0-9_]*)$/.test(input)) return true;
                return 'The entity name cannot contain special characters.';
            },
            message: '(6/' + questions + ') What is the entity to which response has to be mapped?',
            default: ''
        },
        {
            when: function (response) {
                return (response.dataFormat == 'xml');
            },
            type: 'input',
            name: 'reqRoot',
            validate: function (input) {
                if (/^([a-zA-Z0-9_\$\-]*)$/.test(input)) return true;
                return 'The request root name cannot contain special characters.';
            },
            message: '(7/' + questions + ') What is the request xml root class name to which request entity has to be mapped?',
            default: _.capitalize(this.name) + 'Req'
        },
        {
            type: 'input',
            name: 'resRoot',
            validate: function (input) {
                if (/^([a-zA-Z0-9_\$\-]*)$/.test(input)) return true;
                return 'The response root name cannot contain special characters.';
            },
            message: '(8/' + questions + ') What is the response xml root class name from which response entity has to be mapped?',
            default: _.capitalize(this.name) + 'Res'
        },
    ];
```

**Comment by gmarziou** [comment]
@deepu105 for generating the client in HTTP what did you use? [swagger-codegen](https://github.com/swagger-api/swagger-codegen)  seems interesting.

**Comment by deepu105** [comment]
@gmarziou  i used spring restTemplate as I found it simpler actually. havent looked at swagger yet. is it better?

**Comment by gmarziou** [comment]
I can't tell as I just read the docs, I thought it would make a good fit with jhipster. I may give it a try within weeks.

**Comment by cbornet** [comment]
@gmarziou @deepu105 I would stick to swagger-codegen as it is capable to generate clients in a variety of languages. An integration into jhipster would be great.
@deepu105 You want to do a spring client ? For IS-to-IS com ? Right now, swagger-codegen doesn't generate a spring client, there is only a java client using jackson and jersey-client. If you want to generate a spring client, you can provide your own template which is actually quite easy (I will write mine soon since I have to connect to a server for which I have a swagger spec).

**Comment by deepu105** [comment]
Man but swagger looks more complex to me, but my forte is javascript so i might be biased

**Comment by mmaczka** [comment]
I would like to see some changes target on speed of development (I would be the one to decide this should be for me the top priority) 

- Package some bits of jhipster (client & server side) to libs - upgrading the version of hipster should not be more difficult then updating mvn or bower dependency (e.g. login/regsitration)

- Give up on Spring autowiring and other features which slow down the startup time - server startup time should be much, much faster (ideally no more then 1 sec). This will also speed up unit test.

--
- One of the areas where jhipster can improve is date handling for application that uses time zones. It will be nice to have some built-in machinery for that 
---
Support for detecting and preventing concurrent updates of entities (using last_modifes_at) field 
---

Other idea is to use BDD for writing shared tests for client/server side.

**Comment by alvarowolfx** [comment]
I think will be awesome to have a way to generate project using Scala language, I already used Spring Boot with Scala and they works well together. The Typesafe Activator have a template using Spring and Scala, but it's not a complete solution like JHispter. 

I can dream big like this ? :rocket: hahhaha

**Comment by gzsombor** [comment]
Probably some frontend javascript could be packaged - and improved a lot, specially in the validation/error handling parts, but I doubt that from the backend you could make a working library. One of the main selling point of JHipster for me was the ability to customize everything, and the lack  uncommon/unnecessary dependencies. If you are bothered with that jhipster use 'login names' in audit fields, or the way how it integrates with spring security, you can easily change it, because it's plain java. 
 About the startup times: most of the time goes into hibernate and swagger setup, and the proxy bean creations, the autowiring actually is strikingly fast.

**Comment by gmarziou** [comment]
I like the idea of starting monolithic and swithcing to micro services when you need it as in [Martin Fowler's article](http://martinfowler.com/articles/dont-start-monolith.html).
So as long as JHipster enables this pattern at a reasonable cost it's fine for me.

**Comment by LiuXiaoJie** [comment]
An option to generate pure backend without frontend maybe useful.

**Comment by piedrahitac** [comment]
> An option to generate pure backend without frontend maybe useful.

If I'm not mistaken, Julien has said before that it won't become an option since you can simply generate a project and delete the frontend related stuff without any trouble, so he doesn't think it's worth adding.

**Comment by jhoelter** [comment]
I definitely agree on the micro-services architecture step and the integration of spring-cloud Netflix stack. I already used and implemented their implementation of Zuul (reverse proxy) in combinaison of OAuth 2.0 and find it very relevant. I am happy to help on the micro-services architecture part.

**Comment by piedrahitac** [comment]
@jdubois What are your thoughts on Spring's upcoming project REST Docs? The Spring Team has been critical of Swagger and with this new project they are proposing a different approach to services documentation.

Is this point of view something JHipster should follow, or are you and the community perfectly fine with what Swagger brings to the table?

**Comment by jdubois** [comment]
@piedrahitac I didn't heard of anything against Swagger, so I'd rather keep it. Also, it's widely popular and seems to do the work well.
I have no idea what the Spring team did, or why, but anyway before using any new projects I will wait until it has a "critical mass" of users.

**Comment by piedrahitac** [comment]
> @piedrahitac I didn't heard of anything against Swagger, so I'd rather keep it. Also, it's widely popular and seems to do the work well. I have no idea what the Spring team did, or why, but anyway before using any new projects I will wait until it has a "critical mass" of users.

Great, no problem then...

**Comment by Qinwroks** [comment]
@jhoelter can you give me a hit on how to implement a micro-services architecture. thanks!

**Comment by jdubois** [comment]
We can now discuss this on the dev mailing list, and at the moment we have enough ideas!

**Comment by deepu105** [comment]
Im just adding this to 3.0 to keep track

**Comment by unikzforce** [comment]
It would be really lovely if each generated Entity had an Super Class, for example User & BaseUser.
this would help in This Scenario: 
for example if you need to modify User, then you can modify it in User.java and if after some time you needed to Re-Generate the model, the User.java will not be Regenerated, Only Base**** classes will be Regenerated and your modifications will be there & Still Untouched ---> Safety and Less Effort to Maintain changes

**Comment by gmarziou** [comment]
@unikzforce Please don't camp an old issue, if you have a suggestion to improve it, open a new issue.
