### ISSUE TITLE
Metrics page broken for react Monolith

### ISSUE THREAD

**Issue by Jackjun724** [jhipster/generator-jhipster#16011]
##### **Overview of the issue**

Metrics page broken for react Monolith, You can refer to related issues #11561

##### **Motivation for or Use Case**

I use locale `zh-cn`, but numeral.locales only contains `chs`, Actually the two are the same, but the names are different，But the locale that does not exist in `numeral.locales` will cause numerical to throw an error

##### **Reproduce the error**

When `numeral.locales` does not contain `TranslatorContext.context.locale` , the problem will reproduce 

##### **Related issues**

#11561

##### **Suggest a Fix**

I will create pr, when the locale specified by `TranslatorContext.context.locale` does not exist, the default is specified as `en`

##### **JHipster Version(s)**

latest

##### **JHipster configuration**

default

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Jackjun724** [comment]
My [PR](https://github.com/jhipster/react-jhipster/pull/71)

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's a bug

**Comment by Jackjun724** [comment]
> Adding a bounty as it's a bug

I'm very sorry, I forgot to follow up the commit. Please check my latest commit.

**Comment by Jackjun724** [comment]
@pascalgrimaud I am unemployed, I think I need this money :) [](https://opencollective.com/generator-jhipster/expenses/51623)

**Comment by pascalgrimaud** [comment]
Thanks for your contribution @Jackjun724 : approved
