### ISSUE TITLE
Try to generat jhipster

### ISSUE THREAD

**Issue by smitnayakar** [jhipster/generator-jhipster#1603]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\jhipster\npm-debug.log
Running "ngconstant:dev" (ngconstant) task
Creating module doApp at src/main/webapp/scripts/app/app.constants.js...OK

Running "wiredep:app" (wiredep) task
Warning: Error: Cannot find where you keep your Bower packages. Use --force to c
ontinue.

Aborted due to warnings.

**Comment by jdubois** [comment]
Can not reproduce, please have a look at [our contributing document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) if you want more help
