### ISSUE TITLE
Duplicated hazelcast instances

### ISSUE THREAD

**Issue by pnowy** [jhipster/generator-jhipster#1604]
Hello,

I'm using the JHipster configuration with Java 8 and Hazelcast configuration (hazelcast is used for second level cache and clustered http session). Maybe I'm wrong but it seems that with current source code the two instances of Hazelcast are created. The flow looks like:

* The first instance is created during static initialization of class CacheConfiguration:
```java
private static HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
```
The above code is using hazelcast-default.xml from hazelcast.jar which has enabled by default multicasting. This operation is required to correct initialization of 2nd level cache and region factory (the instance cannot be null).

* The second instance is being defined on **CacheConfiguration#hazelcastInstance()** with annotation post construct according with the defined environment application properties. Unfortunately the code responsible for creating this new instance does not take into account that the first instance has been created. The Config for hazelcast is created and the assignment of the new instance looks like:
```java
hazelcastInstance = HazelcastInstanceFactory.newHazelcastInstance(config);
```

With this scenario we have the two hazelcast instances defined for one application instance. The code:
```java
log.debug("Instances: {}", Hazelcast.getAllHazelcastInstances());
```

will print: *Hazelcast instances: [HazelcastInstance{name='jhipsterapp', node=Address[127.0.0.1]:5702}, HazelcastInstance{name='_hzInstance_1_dev', node=Address[192.168.1.125]:5701}]*

I've noticed this behavior when on dev profile in our company network my application had started exchange the messages with other developer machines (and according with configuration the joiners for dev profile should be disabled and instance should be standalone). The root cause of this behavior is the instance created during static initialization.

Is it intended behavior that this is a separated instances? Do we want to have separate instances for 2nd lvl cache and spring cache? Did I miss something?

**Comment by pnowy** [comment]
I think that the simplest solution to avoid duplicated instances is to add the CacheManager dependency  on the DatabaseConfiguration (@Inject private CacheManager cacheManager) and remove the static initialization

```
DatabaseConfiguration {
       ...
      @Inject private CacheManager cacheManager;
      ...
}

CacheConfiguration {
    ....
    private static HazelcastInstance hazelcastInstance;
    ....
}
``` 

With the above solution the parametrized hazelcast instance will be initialized before Hibernate and the correct instance will be used on the HazelcastRegionFactory provided with the JHipster.

I've tested this approach and works fine (I have single parametrized instance for application as I expected). What do you think about that?

**Comment by deepu105** [comment]
I noticed this too but didn't look further since there was no issues and for dev i had multicast: false in the application.yml under hazelcast

**Comment by phouverneyuff** [comment]
related with issue #1616

**Comment by jdubois** [comment]
I should have corrected it with https://github.com/jhipster/generator-jhipster/commit/c0ddffd8539ba2a659685fc85ef0e1a97c95f0da
@deepu105 as you are our biggest HazelCast user, can you have a look at my code? I can't test with a real use case like you have, and I hope I didn't break anything.

**Comment by deepu105** [comment]
@jdubois your code looks fine to me, but im a HazelCast newbie anyways, but Ill be deploying an app with 2000+ users in clusters towards end of July, It will be in a JBoss app server so ill be able to test out fully that time. For time being my developers are running with multicast set to false to avoid hazelcast scanning through local LAN
Ill post back if i found any issues with the new code
