### ISSUE TITLE
Bug bounty for @qmonmert 

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#16042]
We give bug bounties for people doing "big or annoying tasks", when there is a ticket associated.

But we miss people like @qmonmert who has been doing a lot of small bug fixes and improvements during the summer: https://github.com/jhipster/generator-jhipster/pulls?q=is%3Amerged+is%3Apr+author%3Aqmonmert

He has a total of 170 merged PRs, which totally qualifies for "big or annoying tasks"!

So my proposal is that we give @qmonmert a specific $500 bounty in this ticket, to show how much we appreciate all those little contributions that he has done.

I'm adding the bug bounty tags already, please vote or comment on this ticket, to tell what you think about this idea!

**Comment by qmonmert** [comment]
😇

**Comment by avdev4j** [comment]
+1

makes sense since we should support this kind of work too. great job @qmonmert

**Comment by jdubois** [comment]
Wow, a lot of people seem to agree on this, @qmonmert don't wait and do your Open Collective invoice! Congrats!

**Comment by qmonmert** [comment]
Thanks all :)

@jdubois https://opencollective.com/generator-jhipster/expenses/48382
