### ISSUE TITLE
add a new field to jhi_user jhipster

### ISSUE THREAD

**Issue by Hafyane** [jhipster/generator-jhipster#1607]
gave me the different steps to add a new field to table(jhi_user)

**Comment by jdubois** [comment]
This is not a bug or a feature request, so I'm closing this. Did you read our [help page](http://jhipster.github.io/help.html)?
If you want to learn about Java, Spring and Hibernate, you can start with [this spring.io guide](http://spring.io/guides/gs/accessing-data-jpa/)
