### ISSUE TITLE
Only generate syncUserWithIdP when relationship with User is detected.

### ISSUE THREAD

**Issue by ko5tik** [jhipster/generator-jhipster#16074]
##### **Overview of the feature request**

Sometimes it is desirable to suppress generation of certain files.   I would like it to be configurable via say .yo-rc.json 

##### **Motivation for or Use Case**

Current solution  works manually  but it is error prone and does not take into account deleted files.  Better solution would be  to specify list of files  that should not be excluded from generation.

Sometimes there is no need in some generated files ( like .gitattributes / .gitignore )  and sometimes individual generators heve bugs and generate too much, and it takes too long to fix the  primary issue   ( one example would be microservice backend with OAuth  which definitely does not need any user and authority entittes,   but which are generated nevertheless ).   Or gateway applications with OAuth which do not need any database or persistence  or liquibase of whatever - which is still generated )    

##### **Related issues or PR**

none found 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
I think adding `<relative-path>/yourfile skip` in a .yo-resolve file at the root of your repository can do the trick

**Comment by ko5tik** [comment]
OK,  some additional information.    I got latest version from git and ran against my sources,    No references to User and Authority entoities in JSON,   and  relevant application settings are:
    "applicationType": "microservice",
    "authenticationType": "oauth2",
    "skipUserManagement": true,

Yet it generates  User and Authority entitites,  and also code in Cache manager and all the related rest  services and value objects.  My understanding is,   that  when I specified  skipUserManagement  then nothing shall be done in this field ( and corresponging frontends will also use the same settings ).  For now I am just deleting those files ,manually  after regeneration
  but I would prefer possibility to disable generation on file by file basis to avoid this step. While this may or may not be considered as a bug,  and be fixed in the future, there are a lot of similar situations  while user would like to be able to prevent generation of files

**Comment by pascalgrimaud** [comment]
A simple suggestion, really easy to do:
- add the list of files inside your own file
- use your own shell script to use git and revert the changes on these files

**Comment by mshima** [comment]
> "authenticationType": "oauth2",
> "skipUserManagement": true,

`skipUserManagement: true` don't change anything `oauth2` is always `skipUserManagement`

> Yet it generates User and Authority entitites, and also code in Cache manager and all the related rest services and value objects. My understanding is, that when I specified skipUserManagement then nothing shall be done in this field ( and corresponging frontends will also use the same settings )

I think User/Authority are only used by `syncUserWithIdP` which is used to allow relationships with User.
This could be optional on User relationship existence.

As for .yo-resolve, globs are accepted:
``` .yo-resolve
src/main/java/package/domain/User skip
src/main/java/package/domain/Authority skip
src/main/java/package/domain/** skip
```
Then no path matching that will be written.

@ko5tik would be nice if you could contribute with optional syncUserWithIdP.

**Comment by DanielFran** [comment]
Closing since there is a newer issue...
