### ISSUE TITLE
Install JHipster on Windows 10 - npm ERR! code EINVALIDTAGNAME

### ISSUE THREAD

**Issue by bigalnz** [jhipster/generator-jhipster#16075]
Installing Jhipster on Windows 10.

Run the command listed on the jhipster website:

npm install -g generator-jhipster

The resulting error is :

C:\Users\AlGrant>npm install =g generator-jhipster
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "=g": Tags may not have any characters that encodeURIComponent encodes.

The enviroment is  :  

WIndows 10 x 64
java version "1.8.0_291"
Welcome to Node.js v14.17.5.

**Comment by ruddell** [comment]
You used an equal sign instead of a hyphen in your command.

Correct: `npm install -g generator-jhipster`
Incorrect: `npm install =g generator-jhipster`
