### ISSUE TITLE
Cannot determine embedded database driver class for database type NONE. If you want an embedded database please put a supported one on the classpath.

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1610]
I created a new project last night that uses Gradle and PostgreSQL for its dev database. I was able to deploy it to Heroku and get it working fairly easily. This morning, I tried to run the app locally using "./gradlew bootRun". However, I get the following error on startup:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate 
[javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is 
org.springframework.beans.factory.BeanCreationException: 
Cannot determine embedded database driver class for database type NONE. If you want 
an embedded database please put a supported one on the classpath.
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
```

I've configured my application-dev.yml to have the proper settings from my local database, but it looks like this error might be caused by liquibase.

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'liquibase' defined in class path resource 
[org/jhipster/health/config/DatabaseConfiguration.class]: Unsatisfied 
dependency expressed through constructor argument with index 0 of type 
[javax.sql.DataSource]: : Error creating bean with name 'dataSource' 
defined in class path resource [org/springframework/boot/autoconfigure/jdbc
/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean 
instantiation via factory method failed; nested exception is 
org.springframework.beans.BeanInstantiationException: Failed to instantiate 
[javax.sql.DataSource]: Factory method 'dataSource' threw exception; 
nested exception is org.springframework.beans.factory.BeanCreationException: 
Cannot determine embedded database driver class for database type NONE. 
If you want an embedded database please put a supported one on the 
classpath.; nested exception is org.springframework.beans.factory.
BeanCreationException: Error creating bean with name 'dataSource' 
defined in class path resource [org/springframework/boot/autoconfigure
/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: 
Bean instantiation via factory method failed; nested exception is 
org.springframework.beans.BeanInstantiationException: Failed to instantiate 
[javax.sql.DataSource]: Factory method 'dataSource' threw exception; 
nested exception is org.springframework.beans.factory.BeanCreationException: 
Cannot determine embedded database driver class for database type NONE. 
If you want an embedded database please put a supported one on the classpath.
```

My build.gradle seems to have the correct dependencies, though I'm not sure why it has h2:

```
compile group: 'org.postgresql', name: 'postgresql', version: postgresql_version
...
testCompile group: 'com.h2database', name: 'h2'
```

Here's the information I used to create the project:

```
JHipster Generator v2.16.0

? (3/15) Do you want to use Java 8? Yes (use Java 8)
? (4/15) Which *type* of authentication would you like to use? Token-based authentication (stateless, with a token)
? (5/15) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL, Oracle)
? (6/15) Which *production* database would you like to use? (Use arrow keys)
? (6/15) Which *production* database would you like to use?
? (6/15) Which *production* database would you like to use? PostgreSQL
? (7/15) Which *development* database would you like to use? PostgreSQL
? (8/15) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
? (9/15) Do you want to use a search engine in your application? Yes, with ElasticSearch
? (10/15) Do you want to use clustered HTTP sessions? No
? (11/15) Do you want to use WebSockets? Yes, with Spring Websocket
? (12/15) Would you like to use Maven or Gradle for building the backend? Gradle
? (13/15) Would you like to use Grunt or Gulp.js for building the frontend? Grunt (recommended)
? (14/15) Would you like to use the Compass CSS Authoring Framework? No
? (15/15) Would you like to enable translation support with Angular Translate? Yes
```

**Comment by mraible** [comment]
This appears to be caused by integrating Heroku. If I execute the following command and clean, everything works fine.

    rm src/main/java/org/jhipster/health/config/HerokuDatabaseConfiguration.java

Having this class in my classpath seems to work fine on another project that uses Maven. Maybe Gradle isn't honoring the @Profile("heroku") annotation?

**Comment by atomfrede** [comment]
How does maven honor the ``@Profile`` annotation? At least I can't find anything in the ``pom.xml``. Does it somehow exclude from the classpath? 

Regarding h2: It is also in scope test when using maven, so I put the same way to gradle.

**Comment by mraible** [comment]
I copied the pom.xml file from my other project and was able to confirm that it happens with Maven too, so I don't think it's a Maven vs. Gradle issue. Like Gradle, if I remove `HerokuDatabaseConfiguration`, it starts up fine. I'll keep investigating.

**Comment by mraible** [comment]
This appears to be caused by the lack of "url" specified in the datasource settings. Here's what JHipster generated by default (I specified PostgreSQL for dev):

```
url: 
databaseName: health
serverName: localhost
username: health
password:
```

Here's what works:

```
url: jdbc:postgresql://localhost/health
username: health
password:
```

It seems that Spring Boot uses the url to determine if it should use an embedded database or not.

http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html

**Comment by jdubois** [comment]
It's a bug in the generated code -> I'm pushing the correction and I'll do a minor release just afterwards

**Comment by jdubois** [comment]
OK, this is more complex than expected. I should have corrected everything within 10 minutes, but it's late, I don't have the time to do a new release now -> can you try it out in the "master" branch? Or wait a couple of days (I have lots of work at the moment)

**Comment by jdubois** [comment]
Sorry, I know what the issue is, but I can't find a correct solution now... and I don't have the time at the moment. I'll get back on this in a couple of days.

**Comment by jdubois** [comment]
OK, I found a solution... I need more time to test -> if you can try on the "master" branch, it would help me a lot

It can have some impact on the CloudFoundry deployment, so this must also be tested

I'll do a release when this is fully tested

**Comment by mhicauber** [comment]
I'm still having the issue with the latest release (I updated with `npm update -g generator-jhipster` and then ran again `yo jhipster`). 

I checked the generated code : it does not contains the modifications of fix #1610. What is the proper way to get the latest jhipster generator containing the fix ?

Thanks.

**Comment by gmarziou** [comment]
Clone teh repository and use npm link as described [here](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup)

**Comment by mhicauber** [comment]
Thanks a lot I'll try that.

-- 

*Mon ordinateur fonctionne à l'énergie 100% verte, renouvelable, fournie
par ENERCOOP*
http://www.enercoop.fr/

2015-06-24 11:13 GMT+02:00 Gaël Marziou <notifications@github.com>:

**Comment by elciopa** [comment]
I have the same issue with the version 2.20. With you fix it's working perfectly. Here's my datasource

datasource:
        driver-class-name: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://localhost/jhipster220test
        serverName: localhost
        username: jhipster
        password: qwerty

**Comment by newink** [comment]
I don't know, was this fixed or not, but i'm getting error, when i try to use jhipster with connection strings in environment variables.
My datasource configuration in .yml file:
```yml
datasource:
        type: com.zaxxer.hikari.HikariDataSource 
        driver-class-name: oracle.jdbc.driver.OracleDriver
```

Error, i'm getting:
```
Exception encountered during context initialization - cancelling refresh attempt: 

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 
'com.ryantenney.metrics.spring.config.annotation.DelegatingMetricsConfiguration': Unsatisfied 
dependency expressed through method 'setMetricsConfigurers' parameter 0; nested exception is 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 
'metricsConfiguration': Unsatisfied dependency expressed through method 'setHikariDataSource' 
parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error 
creating bean with name 'dataSource' defined in class path resource 
[org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation 
via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; 
nested exception is java.lang.NullPointerException
```

I would really appreciate any help! Thanks in advance
