### ISSUE TITLE
Warning when compiling with React

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16116]
##### **Overview of the issue**

When creating a monolith with React, there's a compile warning on the `main` branch. 

```
WARNING in ./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from
'/Users/mraible/dev/example/node_modules/@reduxjs/toolkit/dist/module.js.map' 
file: Error: ENOENT: no such file or directory, open
'/Users/mraible/dev/example/node_modules/@reduxjs/toolkit/dist/module.js.map'
```

##### **Motivation for or Use Case**

Since it pops an alert, it's not a great experience. Everything still compiles though.

##### **Reproduce the error**

Create an app with React.

##### **JHipster Version(s)**

```
gallery@0.0.1-SNAPSHOT /Users/mraible/dev/example
└── generator-jhipster@7.1.0 -> ./../generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "gallery",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1630470306439,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "org.jhipster.gallery",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "pt-br"],
    "entities": ["Album", "Photo", "Tag"],
    "lastLiquibaseTimestamp": 1630470748000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Album {
  title String required
  description TextBlob
  created Instant
}
entity Photo {
  title String required
  description TextBlob
  image ImageBlob required
  height Integer
  width Integer
  taken Instant
  uploaded Instant
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Album{user(login)} to User
  Photo{album(title)} to Album
}
relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

git version 2.32.0

node: v14.17.0

npm: 7.21.0

Docker version 20.10.8, build 3967b7d

**Comment by mraible** [comment]
Related: there's no JHipster logo displayed when I run this app.

<img width="912" alt="Screen Shot 2021-08-31 at 10 38 39 PM" src="https://user-images.githubusercontent.com/17892/131612900-e810fc0c-a5d2-4b9f-9250-46d87483acd7.png">

**Comment by qmonmert** [comment]
same error here https://github.com/jhipster/generator-jhipster/pull/16079

**Comment by deepu105** [comment]
I guess the warning was present then as well. Could be either a redux issue or our webpack config issue

**Comment by mshima** [comment]
Merged upstream to master branch https://github.com/reduxjs/redux-toolkit/pull/1459

**Comment by qmonmert** [comment]
Fix with this new release https://github.com/reduxjs/redux-toolkit/releases/tag/v1.6.2

**Comment by alishahwee** [comment]
This is still occurring in 1.6.2

**Comment by qmonmert** [comment]
@pascalgrimaud there's not a compile warning on the main branch, we can close this ticket

**Comment by Gayatri19670** [comment]
WARNING in ./node_modules/@auth0/auth0-react/dist/auth0-react.esm.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
