### ISSUE TITLE
Failed to decode downloaded font on Heroku

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1611]
I'm using some custom fonts from http://themeforest.net/item/angulr-bootstrap-admin-web-app-with-angularjs/8437259 in my JHipster application.

I'm seeing the following warning in Chrome Developer Tools when I access my JHipster application at http://www.jhipster-book.com. I don't see this error when running locally.

```
Failed to decode downloaded font: http://www.jhipster-book.com/assets/fonts/sourcesanspro/sourcesanspro.woff
```

I'm using these same fonts on a client's project (that runs on GAE) and it works fine.

I posted this issue to StackOverflow and help.heroku.com.

http://stackoverflow.com/questions/30837327/failed-to-decode-downloaded-font-on-heroku

According to Heroku, "Our router will never set the Content-Type header itself. It's your app's responsibility to do that."

Does JHipster include a filter that can be used to set this mime-type?

**Comment by gmarziou** [comment]
Maybe you could try to add it in the WebConfigurer

https://github.com/jhipster/generator-jhipster/blob/79a4abfc550ebd5cedd9c648d0f13b59816cefd5/app/templates/src/main/java/package/config/_WebConfigurer.java#L119

**Comment by mraible** [comment]
I tried adding the following to my WebConfigurer:

```
mappings.add("json", "text/html;charset=utf-8");
mappings.add("woff", "application/x-font-woff");
container.setMimeMappings(mappings);
```
And it looks like the response headers are now being set correctly. 

```
Cache-Control:max-age=2678400000, public
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Connection:keep-alive
Content-Length:27247
Content-Type:application/x-font-woff;charset=UTF-8
Date:Tue, 16 Jun 2015 01:53:01 GMT
Expires:0
Expires:Fri, 17 Jul 2015 01:53:02 GMT
Last-Modified:Tue, 16 Jun 2015 01:38:54 GMT
Pragma:no-cache
Pragma:cache
Server:Apache-Coyote/1.1
Via:1.1 vegur
X-Application-Context:application:prod,heroku:47787
X-Content-Type-Options:nosniff
X-Xss-Protection:1; mode=block
```

However, the warning still shows and the font is not used. Interestingly, the Bootstrap and FontAwesome fonts are fine.

https://jhipster-news.herokuapp.com/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2

Response headers:
```
Connection:keep-alive
Content-Length:18028
Date:Tue, 16 Jun 2015 01:56:47 GMT
Last-Modified:Tue, 16 Jun 2015 01:30:30 GMT
Server:Apache-Coyote/1.1
Via:1.1 vegur
X-Application-Context:application:prod,heroku:47787
```

Notice that Bootstrap's glyphicons works fine and there's no content-type set.

**Comment by mraible** [comment]
I was able to solve this, but I'm not sure how. In `WebConfigurer.java`, I commented out the three lines that configure caching headers, static resources and gzipping.

        if (env.acceptsProfiles(Constants.SPRING_PROFILE_PRODUCTION)) {
            //initCachingHttpHeadersFilter(servletContext, disps);
            //initStaticResourcesProductionFilter(servletContext, disps);
            //initGzipFilter(servletContext, disps);
        }

I redeployed and confirmed that the "Failed to decode" warning did not appear. I also saw my font loaded correctly. Then I enabled gzipFiltering, packaged, redeployed and verified everything was working. 

I narrowed it down to initCachingHttpHeadersFilter and the following line:

    cachingHttpHeadersFilter.addMappingForUrlPatterns(disps, true, "/assets/*");

I changed it to use /assets/** instead of /assets/* and it seemed to solve the problem. However, when I changed it back to /assets/* to see if it'd happen again, it didn't. Now I have the same configuration I did when I started this process, yet the warning does not happen.

**Comment by mraible** [comment]
After rebooting this morning, I was able to see this issue again and figured out the cause. As suspected, changing from `/assets/*` to `/assets/**` solved the problem.

    cachingHttpHeadersFilter.addMappingForUrlPatterns(disps, true, "/assets/**");

**Comment by gmarziou** [comment]
This is strange, I looked at Tomcat code org.apache.catalina.core.StandardContext#validateURLPattern and could not find any evidence that '**' is valid.

**Comment by mraible** [comment]
Yeah, the issue came back again this morning after doing a redeploy. It certainly is strange that it disappears and then reappears.

**Comment by mraible** [comment]
Today, I noticed that if I deploy my app with the following command, it works and the font is downloaded correctly.

    mvn install -Pprod -DskipTests && heroku deploy:jar --jar target/*.war

However, if I run the same commands via Jenkins, it produces this warning.

* Build / Goals and options: clean install -Pprod -DskipTests
* Post Steps / Execute Shell / command: heroku deploy:jar --jar target/*.war --app myapp

I'm running both on the same machine: OS X, Java 8.

**Comment by jdubois** [comment]
I agree with @gmarziou : as far as I remember, the Servlet spec does not understand "ant style" expressions. So `/assets/**` shouldn't work.

**Comment by mraible** [comment]
For some reason, when I deploy using Jenkins, I see this issue. If I deploy manually from the command line, it works fine. I have Jenkins installed on the same machine (a MacBook Pro) that I'm running the command from, so it's a strange issue.

**Comment by jdubois** [comment]
@mraible do you still have this issue? Maybe it's some caching issue of the Web resources, did you try to clean cache and force refresh your browser?

**Comment by mraible** [comment]
I've been able to identify that this issue happens when I deploy to Heroku using Jenkins, but not when I do it manually from the command line. Pretty strange since Jenkins is running the same command on the same machine. I mentioned this issue in the following blog post:

http://www.jhipster-book.com/#!/news/entry/building-and-deploying-a-jhipster-app-with-jenkins

**Comment by gmarziou** [comment]
Is Jenkins running under same user or same environment/path?

Have you considered using [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin)? It could help because it that downloads/installs Node and NPM locally.

**Comment by mraible** [comment]
Yes, I still see it if I deploy using Jenkins. I don't think it's JHipster
related.

**Comment by mraible** [comment]
Yes, same user and environment.

**Comment by marcelinobadin** [comment]
I have the same problem and I don't have a clue why this happens. Any one can help me?

**Comment by deepu105** [comment]
this doesnt seem like a JHipster issue, plz reopen if you think its a Jhipster issue

**Comment by mraible** [comment]
This actually might be a JHipster issue, caused by its `.gitattributes` file. I noticed this file has `* text eol=lf` and the font file I'm using uses CRLFs. If I re-copy the font file from the Angulr theme I'm using and deploy, everything works. However, if I do a clean checkout from Git, the font is corrupted.
