### ISSUE TITLE
Error when creating an entity with a relationship to User in a microservice project

### ISSUE THREAD

**Issue by stefanobertini** [jhipster/generator-jhipster#16128]
##### **Overview of the issue**

In a Microservice module, if you want to create an entity that has a ManyToOne relationship to User and want the relationship to have a different name, you get an error in the generated Resource class.

```
relationship ManyToOne {
  Company{owner(login)} to User
}
```

In the resource class, the create method will try to issue a getUser()  which is not defined.

```
if (company.getUser() != null) {
    // Save user in case it's new and only exists in gateway
    userRepository.save(company.getUser());
}
```

##### **Motivation for or Use Case**

I want the relationship to have a different name than "user"

##### **Reproduce the error**

You can use the attached JDL to reproduce the error in the "backend" module.

##### **JHipster Version(s)**
7.1.0

##### **Environment and Tools**

java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

git version 2.30.1 (Apple Git-130)

node: v14.17.0

npm: 6.14.13

Docker version 20.10.6, build 370c289

docker-compose version 1.29.1, build c34c88b2

  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    baseName gateway 
    packageName it.plansoft.test.gateway
    applicationType gateway
    authenticationType oauth2
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
    nativeLanguage it
    languages [it, en]
  }
  entities Company
}

application {
  config {
    baseName backend
    packageName it.plansoft.test.backend
    applicationType microservice
    serverPort 8081
    authenticationType oauth2
    databaseType sql
    devDatabaseType postgresql    
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    buildTool maven
    enableHibernateCache true
    reactive false
    nativeLanguage it
    languages [it, en]
  }
  entities Company
}

entity Company {
  name String required maxlength(200)
  website String maxlength(200)
}

relationship ManyToOne {
  Company{owner(login)} to User
}

paginate Company with pagination
microservice Company with backend

deployment {
  deploymentType docker-compose
  appsFolders [gateway, backend]
  dockerRepositoryName "TestApp"
}
  </pre>
  </details>

##### **Browsers and Operating System**

MacOs 11.5.2 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@stefanobertini please ask to reopen if its still an issue
