### ISSUE TITLE
Cassandra compression setting not taken into account

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1612]
```java
// Manage compression protocol
        if (ProtocolOptions.Compression.SNAPPY.equals(this.getCompression())) {
            builder.withCompression(ProtocolOptions.Compression.SNAPPY);
        } else if (ProtocolOptions.Compression.LZ4.equals(this.getCompression())) {
            builder.withCompression(ProtocolOptions.Compression.LZ4);
        } else {
            builder.withCompression(ProtocolOptions.Compression.NONE);
        }
```
is not correct. It should be:
```java
// Manage compression protocol
        if (ProtocolOptions.Compression.SNAPPY.name().equals(this.getCompression())) {
            builder.withCompression(ProtocolOptions.Compression.SNAPPY);
        } else if (ProtocolOptions.Compression.LZ4.name().equals(this.getCompression())) {
            builder.withCompression(ProtocolOptions.Compression.LZ4);
        } else {
            builder.withCompression(ProtocolOptions.Compression.NONE);
        }
```

**Comment by jdubois** [comment]
Sonar would be a little bit smarter, it would see that as we do not override the toString() method, this is useless... And as I don't like coding one method for nothing, I'd say it's better this way.

Does anyone has an opinion on this?

**Comment by phouverneyuff** [comment]
The correct way to compare enum is using equals directly. We don't need compare with your name.

http://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals

Certainly it's false-positive in Sonar.

**Comment by cbornet** [comment]
The enum equals() expects an object and we are giving it a string. The effect is even worse than just sonar complaining : the compression param is not taken into account (ProtocolOptions.Compression.NONE is always used)
I rename the issue accordingly.

**Comment by gzsombor** [comment]
It's funny, that the 'ProtocolVersion' is handled correctly, only the compression is not

**Comment by jdubois** [comment]
Strange, indeed!
It's not really important, let's not argue on this : @cbornet can you do a PR? I will merge it.

**Comment by cbornet** [comment]
@gzsombor 'ProtocolVersion' is handled correctly because the test is: 
if (ProtocolVersion.V1**.name().**equals(this.getProtocolVersion()))
which is correct.
@jdubois I will try to do the PR when I find some time...

**Comment by gzsombor** [comment]
Yes, that's what I've said too :)
