### ISSUE TITLE
Migration from Joda time to Java 8 time

### ISSUE THREAD

**Issue by ygrenzinger** [jhipster/generator-jhipster#1613]
@jdubois the fork seems stable and the patch is ready

I have not implemented the proposed fix from last comments in https://github.com/jhipster/generator-jhipster/issues/1158

**Comment by jdubois** [comment]
@ygrenzinger I'm closing this as it's in fact a duplicate from #1158

As a personal note, I hope we can talk together about this soon :-)

**Comment by ygrenzinger** [comment]
No problem. Hope it will be useful. It's a piece of work :)

**Comment by jdubois** [comment]
@ygrenzinger not sure you understood the "personal note" part -> you might soon have a great project manager if you work in Suresnes

**Comment by ygrenzinger** [comment]
Ok I now understand. Yes normally it's confirmed. We can talk about this in September :)

**Comment by jdubois** [comment]
Great news!!! Must be the first time I meet a JHipster contributor in real life!
