### ISSUE TITLE
Authorization may be bypassed using REST request

### ISSUE THREAD

**Issue by tuxxilla** [jhipster/generator-jhipster#1615]
I created a new jhipster application, logged in as "User" and tried to access the resource `/api/audits/all`. 

According to `AuditResource.java` this should only be allowed for admins `@RolesAllowed(AuthoritiesConstants.ADMIN)`.

However it is possible to access this resource, when setting the `Authorization` header with the value of a logged in "User" bearer token.

Some other Urls are restricted as expected, e.g. `/metrics/metrics` or `/configprops`

### How to reproduce

* Generate jhipster with following parameters (did not test others)

	(1/15) What is the base name of your application? jhipster
	(2/15) What is your default Java package name? com.mycompany.myapp
	(3/15) Do you want to use Java 8? Yes (use Java 8)
	(4/15) Which *type* of authentication would you like to use? OAuth2 Authentication
                  (stateless, with an OAuth2 server iplementation)
	(5/15) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL)
	(6/15) Which *production* database would you like to use? MySQL
	(7/15) Which *development* database would you like to use? H2 in-memory with Web console
	(8/15) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
	(9/15) Do you want to use a search engine in your application? No
	(10/15) Do you want to use clustered HTTP sessions? No
	(11/15) Do you want to use WebSockets? No
	(12/15) Would you like to use Maven or Gradle for building the backend? Maven (recommended)
	(13/15) Would you like to use Grunt or Gulp.js for building the frontend? Grunt (recommended)
	(14/15) Would you like to use the Compass CSS Authoring Framework? No
	(15/15) Would you like to enable translation support with Angular Translate? Yes

* Launch application `mvn spring-boot:run`

* Login as "User"

* Capture and copy the `Authorization` header

* Use REST-Client (e.g. Postman) to send GET-Request to

   http://127.0.0.1:8080/api/audits/all using `Authorization` header copied above

* All audits are returned

**Comment by tuxxilla** [comment]
Just investigated this issue and found the following solution: I updated `SecurityConfiguration.java` setting `jsr250Enabled` to true:

    ...
    @EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true, jsr250Enabled = true)
    public class SecurityConfiguration extends WebSecurityConfigurerAdapter {
    ...

I don't know if it is the right solution but it looks as if it works now. I used the following solution as reference: http://stackoverflow.com/questions/9539936/rolesallowed-doesnt-work

**Comment by seghers** [comment]
I use 
    @PreAuthorize("hasAuthority('ROLE_ADMIN')")
 and not 
    @RolesAllowed(AuthoritiesConstants.ADMIN)
