### ISSUE TITLE
Replace the Azure sub-generator by NubesGen

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#16178]
Please note I'm the author of both projects.

I would like to replace our Azure sub-generator documented at https://www.jhipster.tech/azure/ by Nubesgen, documented at https://nubesgen.com/

They are not doing exactly the same things, and aren't working the same way, but the main reason isn't technical: I don't have the time to maintain twice the same thing, and I would prefer to focus on NubesGen.

For the technical aspects: NubesGen focuses on Terraform (and soon Bicep), which I believe is a far better solution than using the CLI (which is what we do for the sub-generator). I've done NubesGen after the sub-generator, and so I've learned from my mistakes.

This change would remove the sub-generator, and update the documentation to point to NubesGen. Then it's up to the NubesGen project to be compatible with JHipster.

**Comment by atomfrede** [comment]
Keep it open

**Comment by jdubois** [comment]
That should good with NubesGen v0.6.0 https://github.com/microsoft/NubesGen/releases/tag/v0.6.0

- This supports both Azure App Service and Azure Spring Cloud like we do today with the sub-generator
- This adds support to many more services, better security (Azure Key Vault), better configuration
- It adds full GitOps support for "git push" automatic deployment to Azure
- It works with Terraform, so you can easily tweak or update your infrastructure, which is very hard to do using the command line

**Comment by jdubois** [comment]
Keep it open

**Comment by jdubois** [comment]
Keep it open
