### ISSUE TITLE
Error occurs when admin UI is Chinese Simplified 

### ISSUE THREAD

**Issue by stevenbajer** [jhipster/generator-jhipster#16191]
##### **Overview of the issue**
![1631004818(1)](https://user-images.githubusercontent.com/48904072/132316261-25c0e845-9ce0-4b73-b620-d11fdc3d3884.png)

![1631004840](https://user-images.githubusercontent.com/48904072/132316369-168ce593-bee3-4c4e-8cab-73113d3f127a.png)

When I switch UI to Chinese simplified and error message is show.

The jhipster version is 7.1.0 and applicaiton create configure is blow:

Welcome to JHipster v7.1.0
Application files will be generated in folder: D:\xxxxxxx
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? xxxxxxx
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? cn.xxxxxxx.xxxxx
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, Oracle, MSSQL)
? Which *production* database would you like to use? MySQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Which cache do you want to use? (Spring cache abstraction) Hazelcast (distributed cache, for multiple nodes, supports
rate-limiting for gateway applications)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? Which other technologies would you like to use? WebSockets using Spring Websocket, API first development using OpenAPI-generator
? Which *Framework* would you like to use for the client? React
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Flatly
? Choose a Bootswatch variant navbar theme (https://bootswatch.com/)? Light
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application Chinese (Simplified)
? Please choose additional languages to install English
? Besides JUnit and Jest, which testing frameworks would you like to use?
? Would you like to install other generators from the JHipster Marketplace? No

When source code is generated and typed mvnw command. Then the applicaiton start and login as admin/admin to admin ui. When cilick metrics menu and current language is Chinese simplified, the error occured.

**Comment by swarajsaaj** [comment]
This is reproducible on `main`, issue is due to numeral.js having locale as `chs` for chinese instead of `zh-cn`, this issue is seems being looked at in https://github.com/jhipster/generator-jhipster/issues/16011
