### ISSUE TITLE
Error 500 instead of 401 on XAuthTokenFilter.doFilter when an AuthenticationException is thrown

### ISSUE THREAD

**Issue by arturozv** [jhipster/generator-jhipster#1620]
I'm trying to implement a force password reset functionality using a new field on User table. When the field is set, all requests should throw a new exception and return a new http code (419) until the User changes it's password. 

Throwing an exception when executing XAuthTokenFilter.doFilter(...) causes a internal server error instead of calling AuthenticationEntryPoint.commence(...)

How to reproduce it:
1 - generate a token based jhipster project.
2 - Login with an activated user.
3 - Update activated field to false for this user in database so a UserNotActivatedException will throw.
4 - Make any petition with previous logged user and it will return a 500 error instead of a 401.

I found a way to solve it. I don't know if its the best.
1 - Pass Http401UnauthorizedEntryPoint instance to XAuthTokenFilter
2 - Add a catch for AuthenticationException in XAuthTokenFilter before catching any other Exception and make a call to Http401UnauthorizedEntryPoint.commence(...)
3 - Inside Http401UnauthorizedEntryPoint return a custom Message depending on the Exception thrown (UserNotActivatedException, BadCredentialsException, ...)

**Comment by jdubois** [comment]
I labelled this as a bug, but in fact I understand you are modifying JHipster and have a question on this.

I don't understand everything, I guess it would be easier with some code -> as this is more a question, and that this hasn't progressed for 1 month and a half, could you please post this on StackOverflow? It's the best place for such questions
