### ISSUE TITLE
modify existing User entity field 

### ISSUE THREAD

**Issue by liuxx532** [jhipster/generator-jhipster#1623]
Hello, I just start to work on Jhipster, and got a question "Can I modify the exiting User entity field (normally expand the field) ?"  
Like, sometimes I want to collect more information from users when users register. 
I tried to "yo jhipster:entity user" to expand the filed, however, I am failed. I record the original field and typed them in when I    "yo jhipster:entity user", but there are many methods related to the original field and I am unable to handle them very well. 

So, I hope you have a good way to expand the user field, and share with me. 
Thank you very much.

**Comment by liuxx532** [comment]
Hope I have demonstrated clearly, Thank you.

**Comment by atomfrede** [comment]
You could create a new entity with your additional data and just a relation between user and your new entity.

**Comment by gmarziou** [comment]
Maybe the default entities like User could have a JSON description in .jhipster directory as custom ones have and so could be extended using entity sub generator?

**Comment by atomfrede** [comment]
:+1: @gmarziou Sounds great (what when the developer removes required fields?)

**Comment by gmarziou** [comment]
Well if you use a knife, you can hurt yourself and git is your best friend ;)

**Comment by atomfrede** [comment]
Yes of course, but you never know what people try to do ;)

**Comment by liuxx532** [comment]
@atomfrede  your idea could be work. But how can I build the relation between the new entity and user? If With a foreign key I also need to expand the filed. The previous question comes back again

**Comment by deepu105** [comment]
@liuxx532as of now you have to manually edit the entity and changelog files by hand to achieve this. You can create a userProfile entity and have it as a one to one in user entity but u have to manually add that in the user entity and edit changelog to add the foreignkey of userProfile to usertable

**Comment by liuxx532** [comment]
@deepu105  I think Your suggestion is quit similar as @atomfrede, and actually I was trying to approach that. Firstly I tried to re-generate the user with a additional foreign key, but u know User is related with Anthority and PersistentToken, I tried my best to rebuild the relationships among them three, however there  are always some errors(too much import and dependencies make the rebuild get very hard.)

**Comment by liuxx532** [comment]
I think many people sometimes want to re-generate the User entity to meet different kinds of requirements. Then I am to state my way to approach that, definitely it is not totally correct(Lol) but I hope we can discuss.
Firstly,  yo jhipster:entity user. Fill the fileds in, set  authorities as Integer, set persistentTokens as Integer as well, build one2many relationship with Authority and PersistentToken respectively. Build many2one relationship with PersistentToken by "Id" 
Secondly, yo jhipster:entity Authority, fill fileds in, build many2one relationship with user by "id". 

Thirdly, yo jhipster:entity PersistentToken. Fill fields in, set "user" as integer, build many2one relationship with user by "id", and build one2many relationship with user by "user". 

Hopefully, you can understand the way that I described above. More than welcome to point out the Errors or Bad choice. (@deepu105, @atomfrede,@gmarziou)

**Comment by liuxx532** [comment]
@jdubois  Hope you can come to here, and give me some suggestion. Please have a look the process to rebuild the User entity is correct or not. Thank you very much.

**Comment by phouverneyuff** [comment]
@liuxx532 , extend the table JHI_USER. I made tree types of user using generalization.

http://infocenter.sybase.com/archive/index.jsp?topic=/com.sybase.stf.powerdesigner.docs_12.0.0/html/clug/clugp114.htm

![image](https://cloud.githubusercontent.com/assets/9394724/8297484/59b7eeee-1934-11e5-9bb4-0cd4a470026e.png)

**Comment by liuxx532** [comment]
@phouverneyuff Thanks a lot for your ERD, but it looks like I am unable to see the full diagram(cannot see the right part), and I cannot access the url: """ http://infocenter.sybase.com/archive/index.jsp?topic=/com.sybase.stf.powerdesigner.docs_12.0.0/html/clug/clugp114.htm """.

Thank you.

**Comment by phouverneyuff** [comment]
@liuxx532 , I cut my ERD to you see only this part. 

I made generalization. Gestor(manager), Cliente(client) and Funcionario(employee) are kind of User. The relationship between them are one-to-one(1:1).

Type in Google Images "Generalization" and you will see other examples.

https://www.google.com.br/search?q=generalization&safe=off&espv=2&biw=2133&bih=1100&source=lnms&tbm=isch&sa=X&ei=f8OIVbeKJ8n5-AGZwbG4AQ&ved=0CAYQ_AUoAQ&dpr=0.9#safe=off&tbm=isch&q=generalization+user

**Comment by MathieuAA** [comment]
@atomfrede As a JHipster-UML guy, I couldn't agree more. Composition is the best solution (and it should be preferred over inheritance in this case).
The only advantage inheritance has (here) is that we don't have to modify the User entity. However, inheritance still needs to be correctly implemented (which, to my knowledge, .is not)
On the other hand, composition requires the User entity to be altered...  if we **don't** use unidirectional associations.
We (the JHipster-UML team) encountered this case before, and dealt with it by removing associations going from User (but we kept the ones going to User), and converting bidirectional associations to unidirectional ones.

**Comment by jdubois** [comment]
- My original idea what that you just modified the entity code to fits your needs. This would obviously work well, and if you want to upgrade to a newer JHipster version, you would use Git to do the merging.
- As proposed here, we could have a specific JSON configuration file for the User -> this wouldn't work well without some modification, as the User is a rather special entity. As this is quite a lot of work, and I'm not sure this is better than the previous option -> if you do a "yo jhipster" again, you will get the updated User entity as well. The main good thing here, is that it should work better with JHipster UML.
- Doing a one-to-one relationship is another option: this is probably better for maintenance, but you will have worse performance, as there will be a join to be made each time you want to get a User. So it doesn't look like a good idea to me.

-> so I would use my first solution, which is really basic in fact

**Comment by fsopjani** [comment]
ERROR! The table name cannot contain a PostgreSQL reserved keyword

**Comment by guilhermefalcao** [comment]
I have the same error when trying to add a new relationship (1-1) User(newEntity_id) - NewEntity(id).

Any solution?

**Comment by gmarziou** [comment]
Please don't camp on old issues, open a new one and follow our guidelines
