### ISSUE TITLE
update to MapStruct 1.0.0.CR1

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1624]
@jdubois @atomfrede Any specific reason to use beta1 instead of CR1?

**Comment by atomfrede** [comment]
I think when it was integrated first CR1 was not yet available. For the gradle build I've used the same version as the maven build. So it could be updated I think.

**Comment by deepu105** [comment]
btw @atomfrede mapstruct doesnt support nested property on the target is it?

**Comment by atomfrede** [comment]
Not sure. I have not that much knowledge of mapstruct yet.

**Comment by deepu105** [comment]
@jdubois I have upgraded this in my project, do you want a PR? Im using it for JAXB :sunglasses:

**Comment by jdubois** [comment]
Oh yes! In your PR, don't forget the Gradle build (but that's easy)

**Comment by deepu105** [comment]
I did only for Gradle in my app, I need to update Maven :P

On Tue, Jun 23, 2015 at 7:47 PM, Julien Dubois <notifications@github.com>
wrote:

> Oh yes! In your PR, don't forget the Gradle build (but that's easy)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1624#issuecomment-114464506>
> .
>



-- 
thank you,
Deepu.k.s
