### ISSUE TITLE
warning: jadira (hibernate user type) apparently leaking 3 DB connections during initialization

### ISSUE THREAD

**Issue by kbjp** [jhipster/generator-jhipster#1626]
Hi,
After religiously following HikariCP pool-size guidelines:
connections = ((core_count * 2) + effective_spindle_count) = 5 connections in my case
...and mysteriously running out of connections each and any time I was trying to open more than 2 parallel connections, I did a bit of investigation. 
A) How to reproduce:
0) use MySQL as dev DB
1) in jhipster, add the following line in application-dev.yml file under spring.datasource:
maximumPoolSize: 3
2) add following line to dataSource Bean:
config.setMaximumPoolSize(dataSourcePropertyResolver.getProperty("maximumPoolSize",Integer.class));
Start the application as usual. The welcome page will come up after around 30secs and throw an exception: "timeout waiting for a connection".

B) how to investigate:
1) put a debugger breakpoint in the BaseHikariPool->getConnection() method
2) monitor number of opened/active connections in HikariCP through jmx by attaching jconsole to the web container (tomcat in my case)
3) during jhipster app start-up, notice that from the 4th call to BaseHikariPool->getConnection(), the number of opened/active connections starts to creep up...then use debugger-callstack to see what library is asking for a connection (Jadira->AbstractUserTypeHibernateIntegrator->use42Api)

C) how to remedy:
It looks like a fix for this problem is already available in the master branch of the Jadira project:
https://github.com/JadiraOrg/jadira/blob/master/usertype.spi/src/main/java/org/jadira/usertype/spi/shared/AbstractUserTypeHibernateIntegrator.java
...but hasn't been released yet...as you can see, in that version, the connection is properly closed after use.

Hope that this post is useful for someone.

Regards

kbjp

**Comment by jdubois** [comment]
- Your analysis looks indeed correct
- I do have 3 active connections after starting my project, so it confirms what you say

The only doubt I have, is that when I deploy to the cloud (to Heroku for example), I'm using a free database (like elephantsql), and they give me a database with maximum 3 connections, and this works very well!! So I don't have this issue in production!

I will need to debug this further.

I didn't look at @ygrenzinger PR for #1158 but if we use the Java 8 data and time API, I hope we move away from Jadira.

**Comment by kbjp** [comment]
Simple work-around:
In your spring config file (application.yml) put jpa: properties: jadira.usertype.useJdbc42Apis: true/false (depending on if your DB driver is jdbc4.2 compliant or not). That way, jadira doesn't have to query the DB driver to figure-out its functionality; hence jadira will no longer open a DB connection during initialization...et voila ! :-)
Thanks for your feedback and thanks for building this wonderful framework !
Regards
kbjp

**Comment by jdubois** [comment]
@kbjp that's great! But it's going to be really annoying to know (and test!) which driver is compatible! I couldn't find a good way to do it.

**Comment by jdubois** [comment]
I just tested with H2 and I confirm that it works!!! 0 connection now!

**Comment by chrisphe** [comment]
I've released Jadira 4.0.0.GA. Rgds
