### ISSUE TITLE
Custom metrics and logging for invalid JWT tokens

### ISSUE THREAD

**Issue by nickshoe** [jhipster/generator-jhipster#16269]
https://github.com/jhipster/generator-jhipster/blob/b3a50e9fea46f3e5dcdc496010f4b3ff415d1af8/generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs#L123

There's already a `TRACE` level log row (with error details) for the very same event, and I think this is the proper level for this kind of events. I think `INFO` is appropriate for general information about the application status (e.g. app bootstraping, during normal operation, recurring tasks progress).

So, I propose to get rid of the `INFO` log row, and to change the `TRACE` log row message to `"Invalid JWT token."` too.

**Comment by nickshoe** [comment]
If it makes sense, I can do the PR of course..

**Comment by gmarziou** [comment]
For me, it does make sense to keep it as INFO because invalid tokens could be an indication of a hacking attempt.
If we you make it under TRACE, you'll never get the information about security issue.

Alternatively, logs could be replaced by a metrics.

**Comment by atomfrede** [comment]
Good point. But having too logs seems strange. Should we keep trace and set the log level for the TokenProvider to trace such that a log based metric can be used to detect potential hacking attempt?

**Comment by gmarziou** [comment]
I guess the TRACE log is there to get the details with the exception stack so for debugging a specific issue, for security INFO is enough. 

I wonder whether this code should catch the exception (current implementation) or rather let it popup so that spring security logs it correctly for auditing purpose:  https://www.baeldung.com/spring-boot-authentication-audit but maybe it'll break something.

**Comment by nickshoe** [comment]
If the objective is to have indications of potential attacks, then the appropriate level should be WARN in my opinion.

**Comment by nickshoe** [comment]
> For me, it does make sense to keep it as INFO because invalid tokens could be an indication of a hacking attempt.
> If we you make it under TRACE, you'll never get the information about security issue.
> 
> Alternatively, logs could be replaced by a metrics.

+1 for a metric, I can work on this

**Comment by nickshoe** [comment]
Hey guys, any news on this? 
Actually, I'm experiencing several failing login attempts in my app. The idea of a custom metric sounds very good to me; any thought about why shouldn't it be implemented this way and keep using logs instead?
I can do the PR, but I'd like to know more about what do you think about the design, so as to avoid waiting time. ;)

**Comment by gmarziou** [comment]
+1 for this security metrics, @jhipster/developers do you agree?

**Comment by jdubois** [comment]
Yes +1

**Comment by deepu105** [comment]
+ 1

Thanks & Regards,
Deepu

**Comment by nickshoe** [comment]
This is the client code, in the `TokenProvider` class:

```java
    public boolean validateToken(String authToken) {
        try {
            jwtParser.parseClaimsJws(authToken);
            return true;
        } catch (JwtException | IllegalArgumentException e) {
            log.info("Invalid JWT token."); // TODO: remove this line
            // TODO: track custom metric
            log.trace("Invalid JWT token trace.", e);
        }
        return false;
    }
```

Here is the signature of the `JwtParser::parseClaimsJws` method, used in the `TokenProvider` class:

```java
	Jws<Claims> parseClaimsJws(String claimsJws) 
		throws	ExpiredJwtException,
				UnsupportedJwtException,
				MalformedJwtException,
				SignatureException,
				IllegalArgumentException
```

We're only cacthing `JwtException` (_"Base class for JWT-related runtime exceptions."_) and `IllegalArgumentException` (_"if the claimsJws string is null or empty or only whitespace"_). 
These are the `JwtException` sub-classes and their meaning:
- `UnsupportedJwtException` - Exception thrown when receiving a JWT in a particular format/configuration that does not match the format expected by the application.
- `MalformedJwtException` - Exception indicating that a JWT was not correctly constructed and should be rejected.
- `SignatureException` - Exception indicating that either calculating a signature or verifying an existing signature of a JWT failed.
- `ExpiredJwtException` - Exception indicating that a JWT was accepted after it expired and must be rejected.

My proposal for logging and metering:
- `IllegalArgumentException`: i think this should be logged with `ERROR` level, because it's a programming mistake passing a `null` or empty (or untrimmed) string argument without checking that in the client code.
- `JwtException`: i think this is too generic, at least for metering; so I would handle every sub-classes per se:
  -  `ExpiredJwtException`: this is not a big deal, a legit JWT token has expired, nothing bad can happen; I would log this as a `DEBUG` level log and no metric;
  - `UnsupportedJwtException`, `MalformedJwtException` and `SignatureException`: all these exceptions happen when the JWT is explicitely wrong, it could have been tampered with (`SignatureException`), or just edited adding random characters (`MalformedJwtException`?), or copied and pasted from another app (`MalformedJwtException`): I propose to handle these cases together, writing a `WARN` log line and tracking a custom metric, i.e. a counter which represents the number of "malicious JWT authentication attempts" (naming convention for custom metrics? I propose `security.authentication.malicious-attempts-jwt`).

**Comment by nickshoe** [comment]
> you cannot be 100% sure that the attempts are malicious, imagine the case where the JWT secret was changed and suddenly all tokens issued previously have an invalid signature
Good point, we may take into account the "persistance" of these custom metrics: should they be reset upon restart? If so, I guess a JWT secret change demands an application reboot, and consequently causes a reset of the `invalid-tokens` metric. If we want to take advantage of the data, then the semantics should be clear upfront and distinguish between malicious and non-malicious attempts.

**Comment by gmarziou** [comment]
In my understanding, the metrics are supposed to be persisted by Prometheus or similar external tool.

In theory, JWT secret could be changed without restarting the app (see https://www.baeldung.com/spring-reloading-properties)

I'm not sure we really need a catch-all metric, after all it's just a matter of computing a sum :)

**Comment by nickshoe** [comment]
Yeah, I'm confusing the measuring and the reporting aspects.

Shall we proceed with a single custom metric `security.authentication.invalid-tokens` and use dimensions to allow the drill down on single exception?

> As a general rule it should be possible to use the name as a pivot. Dimensions allow a particular named metric to be sliced to drill down and reason about the data. This means that if just the name is selected, then the user can drill down using other dimensions and be able to reason about the value being shown.
>
> &ndash; [Dimensions](https://docs.spring.io/spring-metrics/docs/current/public/prometheus#dimensions)

**Comment by gmarziou** [comment]
I didn't know about the tags, your proposal looks good to me: it looks similar to the `status` tag for the `http.server.requests` metric from Spring Boot Actuator that you can then query this way.

http://localhost:8080/actuator/metrics/http.server.requests?tag=status:200

**Comment by nickshoe** [comment]
I took a dive into the `JwtParser` code, this is the actual meaning of the `UnsupportedJwtException`:

```java
            JwtSignatureValidator validator;
            try {
                algorithm.assertValidVerificationKey(key); //since 0.10.0: https://github.com/jwtk/jjwt/issues/334
                validator = createSignatureValidator(algorithm, key);
            } catch (WeakKeyException e) {
                throw e;
            } catch (InvalidKeyException | IllegalArgumentException e) {
                String algName = algorithm.getValue();
                String msg = "The parsed JWT indicates it was signed with the " + algName + " signature " +
                    "algorithm, but the specified signing key of type " + key.getClass().getName() +
                    " may not be used to validate " + algName + " signatures.  Because the specified " +
                    "signing key reflects a specific and expected algorithm, and the JWT does not reflect " +
                    "this algorithm, it is likely that the JWT was not expected and therefore should not be " +
                    "trusted.  Another possibility is that the parser was configured with the incorrect " +
                    "signing key, but this cannot be assumed for security reasons.";
                throw new UnsupportedJwtException(msg, e);
            }
```
https://github.com/jwtk/jjwt/blob/9dc82f01f0bfb74914c824ac78a398cedda9ff2f/impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java#L398-L414

I've tried to make an API call on the generated project by using a token from another application (actually, an example from [this page](https://learn.akamai.com/en-us/webhelp/iot/jwt-access-control/GUID-054028C7-1BF8-41A5-BD2E-A3E00F6CA550.html) - "A complete JWT") and this resulted in an `UnsupportedJwtException`; so I confirm my hypothesis: "copied and pasted from another app?".

**Comment by nickshoe** [comment]
I've made the PR, didn't actually add any test. Need a piece of advice for testing, maybe we could use a spy to check whether the metrics tracking methods get called?

**Comment by gmarziou** [comment]
I wonder whether we could just add assertions on the `MeterRegistry` like in this test: https://github.com/spring-projects/spring-integration/blob/main/spring-integration-core/src/test/java/org/springframework/integration/support/management/micrometer/MicrometerCustomMetricsTests.java

**Comment by nickshoe** [comment]
Thanks for the hint! It makes sense, I'll go ahead and write some tests following thata example.

**Comment by nickshoe** [comment]
@gmarziou pushed some tests on the PR branch, in particular the two classes: `SecurityMetersServiceTests` and `TokenProviderSecurityMetersTests`.

**Comment by gmarziou** [comment]
Keep it open
