### ISSUE TITLE
Enable gradle enterprise in sample apps and ci

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#16272]
##### Use gradle enterprise in sample apps and ci

Following https://github.com/jhipster/generator-jhipster/pull/14802 we should use our ge instance in the sample apps an ci generated apps.

##### **Motivation for or Use Case**

Be aware of e.g. any regressions in our build process so we always deliver best for our users and maybe even can benefit our ci runtimes.

##### **Related issues or PR**

* https://github.com/jhipster/generator-jhipster/pull/14802
* https://github.com/jhipster/generator-jhipster/issues/14226

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
The sample app will have support after this PR is merged: https://github.com/jhipster/jhipster-sample-app-gradle/pull/3

**Comment by DanielFran** [comment]
Closed in https://github.com/jhipster/jhipster-sample-app-gradle/pull/3

**Comment by atomfrede** [comment]
@deepu105 @DanielFran Didn't realize you added a bounty this year. I think I didn't claim it. Is it still valid to do so? Seems a little strange to me.

**Comment by DanielFran** [comment]
@atomfrede Yes, go head. :)

**Comment by atomfrede** [comment]
@DanielFran Great. We also have maven support in our gradle enterprise instance, so we can use it for the bom and jhipster-lite (e.g. build cache). Will try it out this week maybe. I am in contact with gradle to optimize it eventually.

**Comment by atomfrede** [comment]
@DanielFran  bounty claimed https://opencollective.com/generator-jhipster/expenses/178648

**Comment by DanielFran** [comment]
@atomfrede approved
