### ISSUE TITLE
Add Micro Frontend support to Vue

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16276]
##### **Overview of the feature request**

We have Angular support for Micro Frontends with the `--microfrontend` flag. It'd be sweet to add support for Vue too. 

##### **Motivation for or Use Case**

We should offer similar features across frameworks. 

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/pull/16214#issuecomment-918495549

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
I will take a look if I have time in 2 weeks or so.

**Comment by mraible** [comment]
Pending in https://github.com/jhipster/generator-jhipster/pull/16880.

**Comment by mshima** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/83303
