### ISSUE TITLE
Add Micro Frontend support to React

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16275]
##### **Overview of the feature request**

We have Angular support for Micro Frontends with the `--microfrontend` flag. It'd be sweet to add support for React too. 

##### **Motivation for or Use Case**

We should offer similar features across frameworks. 

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/pull/16214#issuecomment-918495549

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
I will take a shot after vue is done.

**Comment by mraible** [comment]
Keep open please.

**Comment by mraible** [comment]
Still want.

**Comment by mshima** [comment]
PR is coming.

**Comment by mshima** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/85381.
