### ISSUE TITLE
POM error in Eclipse/m2e with maven-processor-plugin

### ISSUE THREAD

**Issue by michaelisvy** [jhipster/generator-jhipster#1628]
I have a Maven error in Eclipse with the latest version of JHispter.

We need to add the below as part of:
org.eclipse.m2e/lifecycle-mapping

```xml
<pluginExecution>
                    <pluginExecutionFilter>
                      <groupId>org.bsc.maven</groupId>
                      <artifactId>maven-processor-plugin</artifactId>
                      <versionRange>[2.2.4,)</versionRange>
                      <goals>
                        <goal>process</goal>
                      </goals>
                    </pluginExecutionFilter>
                    <action>
                      <ignore />
                    </action>
</pluginExecution>
```

**Comment by jdubois** [comment]
I just tried it with STS, and I didn't have any issue. It did prompt me to ask to download the plugin, but it all worked fine.
Do you have this issue with an older project? How did you import your project (I did a "import existing Maven project)?
You know that I don't use Eclipse normally, so I might be wrong.
BTW, I wouldn't put an unbounded version range, you could get any new version at any time.

**Comment by michaelisvy** [comment]
Hi Julien,
I'm using: 
- JHipster 2.16
- STS 3.6.2
- JDK 1.8.0_20

Right now, as soon as I remove that statement, my POM shows an error. I'll try with the latest version of everything. 
BTW, I had used an unbounded version because that's what I have in the JHipster POM for the other <pluginExecution> tags (that might be something you have improved in the latest version of JHipster.

The Maven configuration is getting really complicated. I'm wondering if it wouldn't be better to use Gradle by default.

**Comment by michaelisvy** [comment]
Just so you know, I've updated to the latest version of JHipster and STS. I still have the same error. 
There might be something wrong with my project, I'll try to generate a fresh one and will see how it goes.

**Comment by michaelisvy** [comment]
I think there is a way to configure m2eclipse so we don't need to configure all those pluginExecutionFilters. I've just removed them from my pom.xml file and it still works fine. 

When I've imported my project into Eclipse there was a prompt that proposed to me something such as "Do not configure annotation processing". I've said yes and everything seems to be solved. 

Project has no more issues (apart from the usual Javascript stuff that we need to exclude) and deployment on Tomcat runs fine.

Sorry I need to reproduce it. Will try again with a fresh Eclipse instance (feel free to try out in the meantime).

**Comment by michaelisvy** [comment]
So when I install a fresh version of Spring Tool Suite, things are pretty easy. When importing my JHipster project as a Maven project, it proposes to "setup the Maven plugin connector" for maven-processor-plugin (see below):

![image](https://cloud.githubusercontent.com/assets/1440137/8888558/7067828e-32e4-11e5-8c45-db530a14b08f.png)

After the import, everything goes fine.
 I don't need all the m2eclipse config in the Maven POM (I've removed it and it works just fine).

**Comment by jdubois** [comment]
@michaelisvy looks good! So nothing to do in the end? Can you have a look at https://jhipster.github.io/configuring_ide_eclipse.html and tell us if something needs to be updated?

**Comment by fbricon** [comment]
So I tested https://github.com/jhipster/jhipster-sample-app/ in JBoss Developer Studio (JBDS) 9 and stock Eclipse WTP (Mars).

As @michaelisvy mentioned, maven-processor-plugin requires a specific configurator, provided by m2e-apt (available by default in JBDS). The m2e-apt feature is automatically discovered by m2e and needs to be installed by the user (See previous screenshot). I don't know why m2e would fail to display that installation wizard on Maven project import. But even if/when that fails, you can still Quick Fix/`Ctrl+1` (`Cmd+1` on Mac) on the error marker and select "Discover new m2e connectors"

For the default profile, the pom.xml manages pluginExecutions for : 
* `maven-dependency-plugin`: seems unused. If it was though, a configurator exists in m2e's catalog, so could be omitted.  
* `maven-enforcer-plugin`: already ignored by m2e by default. I really don't think you should override that. Doesn't make sense to execute it during Eclipse builds IMO.
* `exec-maven-plugin`: seems unused, so unnecessary. 

No problems with the `dev` profile.

For the `prod` profile, you have the `yeoman-maven-plugin` that m2e doesn't know what to do with. If that plugin had incremental build support built-in, it would be safe to execute during builds. But I guess it doesn't, so you'd better make m2e ignore that plugin, for that profile 

Off-Topic: JBoss Tools has a new Bower plugin for Eclipse, if you want to give it a try. 
Off-Topic2: Eclipse shows many warnings about unused imports in your code, you might consider `Ctrl+Shift+o` on the project.

**Comment by michaelisvy** [comment]
@fbricon  Thanks Fred that's really helpful.
I've just tried both scenarios (install the plugin when prompted and install the plugin using a quick fix). They both work fine. Julien, we should update the Eclipse guide.

And I agree with Fred, there are lots of unused imports that should be cleaned up.

Fred: since you know the internals of Eclipse: would you know what is the best way to exclude some folders from Javascript validation? At this stage JHipster users are asked to do it manually but there might be a better way (see here: http://jhipster.github.io/configuring_ide_eclipse.html)

Cheers,
Michael.

**Comment by gmarziou** [comment]
> And I agree with Fred, there are lots of unused imports that should be cleaned up.

I don't think they should be cleaned up by generator (unless they prevent compilation)  because IDEs can fix them easily and this adds much complexity to the generator templates.

**Comment by jdubois** [comment]
I'm trying as hard as possible to have the correct imports all the time -> as @gmarziou wrote this is a lot of work, but still I try to generate the classes correctly.
If there is work to do to optimize them, I will create a specific ticket.

**Comment by fbricon** [comment]
I was specifically pointing at the sample app, not the scaffolding results in general (much harder to achieve). 
I dunno if you regenerate the sample app every time you change your scaffolding mechanism. If not, then just clean it once, else, good luck with #1783 :-)

**Comment by fbricon** [comment]
As for the Javascript exclusion thing, there's no easy way to do it. JSDT notoriously sucks, however I know that in the upcoming Mars SR1 release, users will be able to disable Javascript parsing (per project or globally, I don't know), so you won't get these pesky js errors all over the place.

**Comment by michaelisvy** [comment]
@fbricon Fred, one question based on this link:
https://github.com/jhipster/jhipster-sample-app/blob/master/pom.xml#L380
do you think that we can remove the whole plugin declaration? 
Or should we remove the <configuration> tag and still declare the m2eclipse plugin?

Removing the whole plugin works well on my machine. Just wanted to confirm with you :).

Thanks!

**Comment by fbricon** [comment]
Yes, looks like the whole lifecycle-mapping plugin definition can be
skipped altogether.

On Tue, Aug 4, 2015 at 10:03 PM, michaelisvy <notifications@github.com>
wrote:

> @fbricon <https://github.com/fbricon> Fred, one question based on this
> link:
> https://github.com/jhipster/jhipster-sample-app/blob/master/pom.xml#L380
> do you think that we can remove the whole plugin declaration?
> Or should we remove the tag and still declare the m2eclipse plugin?
>
> Removing the whole plugin works well on my machine. Just wanted to confirm
> with you :).
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1628#issuecomment-127819018>
> .
>



-- 
"Have you tried turning it off and on again" - The IT Crowd
And if that fails, then http://goo.gl/tnBgH5

**Comment by michaelisvy** [comment]
Perfect, thanks!

**Comment by michaelisvy** [comment]
@fbricon I have removed the m2eclipse config and it's all good except that we have this warning:
```
maven-enforcer-plugin (goal "enforce") is ignored by m2e.
```

I think the m2e connector is there but we still have this warning. Is there something we can do to remove it?
After that our config will be perfect.
Thanks!

**Comment by fbricon** [comment]
Ah, it can be safely ignored but I reckon it's annoying.

Currently m2e doesn't provide a way to mute these messages from m2e's
default lifecycle mappings.

You have 2 choices for now:
- document that it can be safely ignored and document how this can be muted
by adding the following pluginExecution in the workspace lifecycle mapping
in Preferences > Maven > Lifecycle Mappings  > Open workspace lifecycle
mappings metadata :

<pluginExecution> <pluginExecutionFilter>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-enforcer-plugin</artifactId> <goals> <goal>enforce</goal>
</goals> <versionRange>[1.0-alpha-1,)</versionRange>
</pluginExecutionFilter> <action> <ignore/> </action> </pluginExecution>

- Keep that pluginexecution in your pom


On Wed, Aug 5, 2015 at 11:43 PM, michaelisvy <notifications@github.com>
wrote:

> @fbricon <https://github.com/fbricon> I have removed the m2eclipse config
> and it's all good except that we have this warning:
>
> maven-enforcer-plugin (goal "enforce") is ignored by m2e.
>
> I think the m2e connector is there but we still have this warning. Is
> there something we can do to remove it?
> After that our config will be perfect.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1628#issuecomment-128226787>
> .
>



-- 
"Have you tried turning it off and on again" - The IT Crowd
And if that fails, then http://goo.gl/tnBgH5

**Comment by michaelisvy** [comment]
Hi Fred, thanks for that. I would say the best thing is to leave this warning for now.

In the meantime, do you think it would make sense to have m2e provide some configuration that would mute those messages? I'd be happy to open an issue if you'd like.

**Comment by jdubois** [comment]
Closed as discussed with @michaelisvy

**Comment by fbricon** [comment]
@michaelisvy there may be an existing bug open already. If not, you can open one

**Comment by tayfunyasar** [comment]
I'm having trouble with yeoman-maven-plugin. I've tried "discover new m2e connectors" nothing found.

**Comment by erikkemperman** [comment]
@tayfunyasar I just ran into the same issue, "discover connectors" did not find anything. Created a PR [here](https://github.com/jhipster/generator-jhipster/pull/2726) that would fix this in the pom. Ugly, I think, but there is precedence -- the `jacoco-maven-plugin` is handled the same way.
