### ISSUE TITLE
`jhipster heroku` still prompts for credentials when Answer is No to Okta

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16299]
##### **Overview of the issue**

You're prompted for credentials even when you say No to Okta when running `jhipster heroku`. 

<img width="1325" alt="Screen Shot 2021-09-14 at 7 58 58 PM" src="https://user-images.githubusercontent.com/17892/133358077-32d11fd6-2408-4d1d-b739-01bf8f2ba608.png">

##### **Motivation for or Use Case**

I don't think you should be prompted for the JHipster Admin email or password when you say No to Okta.

##### **Reproduce the error**

Run `jhipster heroku` and say No to Okta.

##### **JHipster Version(s)**

```
gallery@0.0.1-SNAPSHOT /Users/mraible/dev/auth0-jhipster-example
└── generator-jhipster@7.2.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "gallery",
    "jhipsterVersion": "7.2.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1630470306439,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "org.jhipster.gallery",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "pt-br"],
    "entities": ["Album", "Photo", "Tag"],
    "lastLiquibaseTimestamp": 1631670674000,
    "enableGradleEnterprise": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Album {
  title String required
  description TextBlob
  created Instant
}
entity Photo {
  title String required
  description TextBlob
  image ImageBlob required
  height Integer
  width Integer
  taken Instant
  uploaded Instant
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Album{user(login)} to User
  Photo{album(title)} to Album
}
relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

git version 2.32.0

node: v14.17.0

npm: 7.22.0

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

**Comment by mraible** [comment]
It seems that things might not work at all when you answer no. It just hangs at:

```
Using existing Git repository

Installing Heroku CLI deployment plugin

Creating Heroku application and setting up node environment
```

**Comment by atomfrede** [comment]
Fixed the invalid prompt, but there seems to be an issue with `heroku create` command. It seems to hang even when selecting okta at

**Comment by mraible** [comment]
@atomfrede When I choose no for Okta, I still end up with some artifacts in my `.yo-rc.json`:

```
    "useOkta": false,
    "oktaAdminPassword": "XXX"
```

**Comment by atomfrede** [comment]
Yes it's the default values.

**Comment by mraible** [comment]
Running `jhipster heroku` seems to fail after I try to redeploy an existing projects.

```
Configuring Heroku
✖ Error: Command failed: heroku buildpacks:add heroku/java --app protected-reaches-51362
 ›   Error: The buildpack heroku/java is already set on your app.

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:376:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'heroku buildpacks:add heroku/java --app protected-reaches-51362',
  stdout: '',
  stderr: ' ›   Error: The buildpack heroku/java is already set on your app.\n'
```

**Comment by atomfrede** [comment]
Let me check. It seems heroku has change a little on their side. I think before setting the (same) buildpack again didn't throw such an error.

**Comment by mraible** [comment]
I tried this again today and it still writes Okta values to `.yo-rc.json`, even though I said I didn't want to use Okta.

```json
    "herokuAppName": "flickr-2",
    "herokuDeployType": "git",
    "herokuJavaVersion": "11",
    "useOkta": false,
    "oktaAdminPassword": "d4f70a690cad148c4cac2018c9805adc60393e95"
```
