### ISSUE TITLE
Plan for Material Design

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#1629]
Hi,
Do this project has any future plan to add material design for the applications?

Thanks.

**Comment by gmarziou** [comment]
For me, it just means using a Bootstrap theme that implements material design, so it seems very similar to #1526 which @jdubois proposed to add as a tip to the documentation.
Personally, I think jhipster should stay neutral in terms of look and feel and let the developers and his/her customers implement their own which is quite easy with bootstrap and sass.

**Comment by jdubois** [comment]
Yes, I agree with @gmarziou 
Then, if somebody wants to volunteer to check whether our base application follows the Material UI/UX guidelines, he's welcome!
