### ISSUE TITLE
The development ribbon and API links are missing when run locally

### ISSUE THREAD

**Issue by naris** [jhipster/generator-jhipster#16309]
##### **Overview of the issue**

While developing is jhipster is started with ./mvnw (without parameters) activeProfiles is empty. The log says that it defaulrs to dev,api_docs but that is not the case, it is actually empty and that causes the ts code to disable the api-docs and the development ribbon :(

##### **Motivation for or Use Case**

It breaks some very handy features of jhipster, the api docs are disabled and the development ribbon no longer appears. Attempting to run with ./mvnw -Pdev,api-docs in windows powershell results in an error as it does not like the comma

##### **Reproduce the error**

run any jhipster application with ./mvnw without any parameters. The face that the activeProfiles are indeed empty will be confirmed by the log:

```
2021-09-15 22:00:34.566  INFO 14812 --- [  restartedMain] com.epsilon.metadater.MetadaterApp       : No active profile set, falling back to default profiles: dev,api-docs
2021-09-15 22:00:51.352  INFO 14812 --- [  restartedMain] com.epsilon.metadater.MetadaterApp       : 
----------------------------------------------------------
        Application 'metadater' is running! Access URLs:
        Local:          http://localhost:8080/
        External:       http://10.213.4.136:8080/
        Profile(s):     []
----------------------------------------------------------
```

##### **Related issues**

I have not been able to find a similar issue.

##### **Suggest a Fix**

I managed to work around the issue on the client side by changing profile.service.ts to return hard-coded values if activeProfiles is empty. However, a much better fix would be to change the java management/info endpoint (ActiveProfilesInfoContributor.java?) to return the value from getDefaultProfiles() if the value form getActiveProfiles() is empty

Here are the changes for the work-around that I made:
  constructor(private http: HttpClient, private applicationConfigService: ApplicationConfigService) {}

```
  getProfileInfo(): Observable<ProfileInfo> {
    if (this.profileInfo$) {
      return this.profileInfo$;
    }

    this.profileInfo$ = this.http.get<InfoResponse>(this.infoUrl).pipe(
      map((response: InfoResponse) => {
        // eslint-disable-next-line no-console
        console.log("response=", response)
        const profileInfo: ProfileInfo = {
          activeProfiles: response.activeProfiles,
          inProduction: response.activeProfiles?.includes('prod'),
          openAPIEnabled: response.activeProfiles?.includes('api-docs'),
        };
        if (response.activeProfiles?.length === 0) {
            profileInfo.activeProfiles = ["dev", "api-docs"];
            profileInfo.inProduction = false;
            profileInfo.openAPIEnabled = true;
            profileInfo.ribbonEnv = "dev";
        }
        else if (response.activeProfiles && response['display-ribbon-on-profiles']) {
          const displayRibbonOnProfiles = response['display-ribbon-on-profiles'].split(',');
          const ribbonProfiles = displayRibbonOnProfiles.filter(profile => response.activeProfiles?.includes(profile));
          if (ribbonProfiles.length > 0) {
            profileInfo.ribbonEnv = ribbonProfiles[0];
          }
        }
      return profileInfo;
      }),
      shareReplay()
    );
    return this.profileInfo$;
  }
}
```

##### **JHipster Version(s)**

7.0.1

##### **JHipster configuration**

`╰─ jhipster info                                                                                                                             ─╯ 
INFO! Using JHipster version installed locally in current project's node_modules
INFO! No custom sharedOptions found within blueprint: generator-jhipster-primeng-blueprint at C:/src/metadater/node_modules/generator-jhipster-primeng-blueprint
INFO! No custom commands found within blueprint: generator-jhipster-primeng-blueprint at C:/src/metadater/node_modules/generator-jhipster-primeng-blueprint
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
metadater@0.0.1-SNAPSHOT C:\src\metadater
├─┬ generator-jhipster-primeng-blueprint@7.0.2
│ └── generator-jhipster@7.0.1 deduped
└── generator-jhipster@7.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [
      {
        "name": "generator-jhipster-primeng-blueprint",
        "version": "7.0.2"
      }
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-primeng-blueprint",
        "version": "7.0.2"
      }
    ],
    "applicationType": "monolith",
    "baseName": "metadater",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["gatling"],
    "pages": [],
    "creationTimestamp": 1629925710152,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.epsilon.metadater",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "buildTool": "maven",
    "serverSideOptions": ["enableSwaggerCodegen:true"],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/epsilon/metadater",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

git version 2.31.1.windows.1

node: v14.16.1

npm: 7.21.0

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
`
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not related to JDL

##### **Browsers and Operating System**

Windows 10 Enterprise 1909

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
A blueprint overrides our workflow completely.
Please update this issue if manage to reproduce without using the blueprint.

**Comment by naris** [comment]
I tried this again without any blueprints and the same thing happened. I will open a new issue for it.
