### ISSUE TITLE
Using brew.sh on Mac for JHipster setup

### ISSUE THREAD

**Issue by moifort** [jhipster/generator-jhipster#1630]
@jdubois, you can maybe add on your documentation, in the setup section, for Mac user, an alternative to docker: http://brew.sh. It's a package manager for mac os platform, very easy to install (one command line). After installing brew.sh you can follow the `Local installation` section and it's work fine (work very well for me)

PS: I don't find how to add `Documentation` tag on the issue

**Comment by jdubois** [comment]
@moifort yes that's Homebrew, I use it all the time. I'm not sure what it would add to the documentation, what do you do with it that's so interesting?

**Comment by moifort** [comment]
@jdubois, it's just an alternative, because at the beginning, I try to use docker on my mac but I have problems with docker app or Kitematic (not your container). It's not very interesting, but the idea was to propose an alternative for the personne who have the same problems like me.

**Comment by jdubois** [comment]
Yes, but the recommended installation [here](http://jhipster.github.io/installation.html) is already to set up your dev environnement locally.
I don't use Docker myself, I find it too slow and complex (on a Mac, if I was on Linux it would be a different story).
