### ISSUE TITLE
Use non-blocking CompletableFuture instead of traditional blocking Servlet

### ISSUE THREAD

**Issue by ledinhtuyenbkdn** [jhipster/generator-jhipster#16313]
will be nice to use non-blocking CompletableFuture request.
I have a performance test between blocking and non-blocking in Spring MVC.
And non-blocking is a pretty good than traditional blocking Servlet

**Comment by mraible** [comment]
Choose WebFlux. It is the way. 

<img width="1330" alt="Screen Shot 2021-09-16 at 2 16 54 AM" src="https://user-images.githubusercontent.com/17892/133576533-e65ccdb0-f2e9-4acf-9d42-e56993f1fb85.png">

**Comment by ledinhtuyenbkdn** [comment]
I think it is easy, convenient to use non-blocking with Spring MVC than Webflux.
I tried to code with Webflux. Reactive programming is too different than imperative.
Spring Data R2DBC is not fully supported all features in Spring Data JPA. 
Migrating to non-blocking with CompletableFuture is quite easy.

**Comment by atomfrede** [comment]
It sound too complicated and special imho. We offer webflux and classical mvc, which is what most people will use.

**Comment by pascalgrimaud** [comment]
Agree with @atomfrede 
We already provide 2 good options, which is not easy to maintain both (specially Webflux). Adding 1 more option (which would be a mixt) would be overkilled, and impossible to maintain for us.

It can go into a module or a blueprint, so don't hesitate to start to code one @ledinhtuyenbkdn

**Comment by ledinhtuyenbkdn** [comment]
Thanks for your suggestions.
So I will close this issue.
