### ISSUE TITLE
Liquibase Error when using Oracle-DB

### ISSUE THREAD

**Issue by mdireskeneli** [jhipster/generator-jhipster#1631]
When using Oracle-DB, there are some lines in generated liquibase files which are not compatible with oracle-database (I think it is meant to be for postgre-sql). So the database cannot be initialized at all.

Here is a part of the initial changeset file. 
<code>
`<changeSet id="00000000000001" author="jhipster">
<createSequence sequenceName="SEQ_USER" startValue="1000" incrementBy="1" />
<createTable tableName="JHI_USER">
<column name="id" type="bigint" autoIncrement="${autoIncrement}" defaultValueComputed="SEQ_USER.NEXTVAL">
<constraints primaryKey="true" nullable="false" />
</column>
...
</changeSet>`
</code>
Possible solution:
The tag <code>defaultValueComputed="SEQ_USER.NEXTVAL")</code> must be removed and instead a trigger must be created so that this works on oracle.

example trigger:
`<changeSet id="trigger_1" dbms="oracle">
		<createProcedure>
			CREATE TRIGGER tg_SEQ_USER
			BEFORE INSERT ON JHI_USER
			FOR EACH ROW
			DECLARE
			BEGIN
			IF( :new.id IS NULL )
			THEN
			:new.id := SEQ_USER.nextval;
			END IF;
			END;
		</createProcedure>
</changeSet>`

**Comment by jdubois** [comment]
@deepu105 as you coded this, and that I can't test it, can you have a look?

**Comment by deepu105** [comment]
@jdubois yes ill look into this

**Comment by deepu105** [comment]
@mdireskeneli what version of Oracle are you using, these lines are meant specifically for Oracle 12c, this makes use of the pseudo value support introduced in 12c. So if you are running anything below 12c it wont work and since Oracle 11g is EOL we will not be supporting that

**Comment by mdireskeneli** [comment]
@deepu105 
Yes, I was using Oracle 11g XE, since the express edition for 12c (which would be good to have for development purposes) has not been released. So I close the ticket when oracle 11g will not be supported. Thanks for the info!

**Comment by deepu105** [comment]
@mdireskeneli what do you mean not released? Im using 12c enterprise edition as well as a personal express edition on my laptop. You might want to check the website
