### ISSUE TITLE
Every second entity deletion from React UI refreshes the list instead of deleting 

### ISSUE THREAD

**Issue by marcinksiazek** [jhipster/generator-jhipster#16314]
##### **Overview of the issue**

The Delete entity button on every list has a strange behavior. The first time I delete an entity it works and the entity is deleted, when I try to delete another one by pressing 'Delete' instead of showing the popup it just refreshes the list. The third press works and then every second press on a delete button refreshes the list only.

##### **Motivation for or Use Case**

While this is a minor thing it makes the user experience deteriorating and it feels like there are serious issues with the React frontend implementation.

##### **Reproduce the error**

Generate an empty Monolith application with React, Postgres, H2 with disk, No cache.
Generate a basic entity using JDL
Start the application and navigate to the list.
Start deleting rows using Delete button

##### **JHipster Version(s)**

I was using both 7.1.1 and 7.2 with the same results.

##### **JHipster Version(s)**

```
bug@0.0.1-SNAPSHOT /Users/sg0225289/private/bug
└── generator-jhipster@7.2.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "bug",
    "jhipsterVersion": "7.2.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1631779653459,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"],
    "enableGradleEnterprise": false,
    "entities": ["Club"],
    "lastLiquibaseTimestamp": 1631781832000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Club {
  clubName String required
  clubShortName String required
}
dto Club with mapstruct
service Club with serviceClass

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

git version 2.30.1 (Apple Git-130)

node: v16.9.0

npm: 7.21.1

Docker version 20.10.8, build 3967b7d

##### **Browsers and Operating System**

MacOS 11.4
Chrome 93.0.4577.82 (Official Build) (x86_64)
Safari 14.1.1 (16611.2.7.1.4)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by marcinksiazek** [comment]
After additional investigation, it looks like the second use of a Delete button causes additional GET call just to retrieve the entity. Take a look at the screenshot.

GET Request Url: http://localhost:8080/api/clubs/4 (additional not necessary call)
Referer: http://localhost:8080/club

GET Request Url: http://localhost:8080/api/clubs/4
Referer: http://localhost:8080/club/4/delete

<img width="1303" alt="Screenshot 2021-09-16 at 12 40 32 PM" src="https://user-images.githubusercontent.com/1113918/133598522-5b386bab-8935-4b17-abe6-b832d185ac40.png">

**Comment by qmonmert** [comment]
Indeed I reproduce

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's an annoying bug

**Comment by qmonmert** [comment]
@marcinksiazek you can try my branch https://github.com/qmonmert/generator-jhipster/tree/react/16314 to see if it fixes :)

**Comment by marcinksiazek** [comment]
@qmonmert I've already applied the changes to my code and I can confirm it fixes the weird behavior. Thanks for reacting so quickly!

**Comment by qmonmert** [comment]
good @pascalgrimaud maybe you can merge

**Comment by qmonmert** [comment]
@pascalgrimaud @jdubois I claim my bounty :) https://opencollective.com/generator-jhipster/expenses/50388
