### ISSUE TITLE
Spring authentication failure after deployment with a war-file

### ISSUE THREAD

**Issue by mdireskeneli** [jhipster/generator-jhipster#1632]
The spring-authentication does not seem to work after the deployment of the application as a separate war-file (not using executable war). The user cannot login at all with proper credentials and the browser makes constantly unsuccesful logout requests. 
I am not sure what the cause is. I enabled the websockets while creating the project and am now using tomcat8.

**Comment by jdubois** [comment]
I can't reproduce your issue... Can you give me your version, your configuration, maybe a stacktrace? Do you have the same issue with the sample application?

**Comment by mdireskeneli** [comment]
Hello Julien,

I have just made a new application with jhipster and tested it.
Version/Configuration:
<pre><code>
Welcome to the JHipster Generator v2.16.1
? (1/15) What is the base name of your application? jhipster
? (2/15) What is your default Java package name? com.mycompany.myapp
? (3/15) Do you want to use Java 8? Yes (use Java 8)
? (4/15) Which *type* of authentication would you like to use? HTTP Session Auth
entication (stateful, default Spring Security mechanism)
? (5/15) Which *type* of database would you like to use? MongoDB
? (10/15) Do you want to use clustered HTTP sessions? No
? (11/15) Do you want to use WebSockets? Yes, with Spring Websocket
? (12/15) Would you like to use Maven or Gradle for building the backend? Maven
(recommended)
? (13/15) Would you like to use Grunt or Gulp.js for building the frontend? (Use
? (13/15) Would you like to use Grunt or Gulp.js for building the frontend? Grun
t (recommended)
? (14/15) Would you like to use the Compass CSS Authoring Framework? No
? (15/15) Would you like to enable translation support with Angular Translate? No
</code></pre>

I have tested this on my local machine and also on a linux server. 
here I send you the logs and the screenshot.

<pre><code>
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Cancel
ling cookie
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Enter: org.springframewo
rk.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent
[timestamp=Tue Jun 23 00:37:52 CEST 2015, principal=anonymousUser, type=AUTHORIZ
ATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedExcept
ion, message=Zugriff verweigert}]]
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Exit: org.springframewor
k.boot.actuate.audit.AuditEventRepository.add() with result = null
[DEBUG] com.mycompany.myapp.security.Http401UnauthorizedEntryPoint - Pre-authent
icated entry point called. Rejecting access
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - No per
sistent token found, so no token could be deleted
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Logout
 of user Unknown
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Cancel
ling cookie
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Rememb
er-me cookie detected
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - No per
sistent token found for series id: cyxB++dLdCmDNnucWExlvg==
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Cancel
ling cookie
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Enter: org.springframewo
rk.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent
[timestamp=Tue Jun 23 00:37:52 CEST 2015, principal=anonymousUser, type=AUTHORIZ
ATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedExcept
ion, message=Zugriff verweigert}]]
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Exit: org.springframewor
k.boot.actuate.audit.AuditEventRepository.add() with result = null
[DEBUG] com.mycompany.myapp.security.Http401UnauthorizedEntryPoint - Pre-authent
icated entry point called. Rejecting access
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - No per
sistent token found, so no token could be deleted
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Logout
 of user Unknown
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Cancel
ling cookie
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Rememb
er-me cookie detected
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - No per
sistent token found for series id: cyxB++dLdCmDNnucWExlvg==
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Cancel
ling cookie
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Enter: org.springframewo
rk.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent
[timestamp=Tue Jun 23 00:37:52 CEST 2015, principal=anonymousUser, type=AUTHORIZ
ATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedExcept
ion, message=Zugriff verweigert}]]
</code></pre>

![image](https://cloud.githubusercontent.com/assets/598670/8295054/3bacc174-1941-11e5-8c1c-adc87b2f9fd8.png)

I have now used the sample application (https://github.com/jhipster/jhipster-sample-app)
I still cannot login when I use the file jhipster.war.original for tomcat. 
Here are the logs:

<pre><code>
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Enter: org.springframewo
rk.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent
[timestamp=Tue Jun 23 00:54:10 CEST 2015, principal=anonymousUser, type=AUTHORIZ
ATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedExcept
ion, message=Zugriff verweigert}]]
Hibernate: insert into JHI_PERSISTENT_AUDIT_EVENT (event_id, event_date, event_t
ype, principal) values (null, ?, ?, ?)
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Exit: org.springframewor
k.boot.actuate.audit.AuditEventRepository.add() with result = null
Hibernate: insert into JHI_PERSISTENT_AUDIT_EVT_DATA (event_id, name, value) val
ues (?, ?, ?)
Hibernate: insert into JHI_PERSISTENT_AUDIT_EVT_DATA (event_id, name, value) val
ues (?, ?, ?)
[DEBUG] com.mycompany.myapp.security.Http401UnauthorizedEntryPoint - Pre-authent
icated entry point called. Rejecting access
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Logout
 of user Unknown
[DEBUG] com.mycompany.myapp.security.CustomPersistentRememberMeServices - Cancel
ling cookie
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Enter: org.springframewo
rk.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent
[timestamp=Tue Jun 23 00:54:10 CEST 2015, principal=anonymousUser, type=AUTHORIZ
ATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedExcept
ion, message=Zugriff verweigert}]]
Hibernate: insert into JHI_PERSISTENT_AUDIT_EVENT (event_id, event_date, event_t
ype, principal) values (null, ?, ?, ?)
[DEBUG] com.mycompany.myapp.aop.logging.LoggingAspect - Exit: org.springframewor
k.boot.actuate.audit.AuditEventRepository.add() with result = null
Hibernate: insert into JHI_PERSISTENT_AUDIT_EVT_DATA (event_id, name, value) val
ues (?, ?, ?)
Hibernate: insert into JHI_PERSISTENT_AUDIT_EVT_DATA (event_id, name, value) val
ues (?, ?, ?)
[DEBUG] com.mycompany.myapp.security.Http401UnauthorizedEntryPoint - Pre-authent
icated entry point called. Rejecting access
</code></pre>

When I start the sample application with "mvn spring-boot:run" then everything runs fine.

I have also tried to run the application in tomcat under the root-context path, but it did not make any difference.

**Comment by phouverneyuff** [comment]
@mdireskeneli try add this line in application.yml

server:
    contextPath: /

You can change the contextPath to another value.

**Comment by mdireskeneli** [comment]
I added the line <code>contextPath: /</code>
<pre><code>Caused by: java.lang.IllegalArgumentException: Root ContextPath must be specified using an empty string</code></pre>
Now I use the following configuration and it runs without any problems. Thanks !
<pre><code>
server:
    contextPath: 
    port: 8080
</code></pre>
