### ISSUE TITLE
Login page should display the authentication error instead of the generic message

### ISSUE THREAD

**Issue by sbouchex** [jhipster/generator-jhipster#16338]
##### **Overview of the feature request**

Current implementation is displaying the following message in case of authentication error : Failed to sign in! Please check your credentials and try again.

However, in case of custom authentication (implementing AuthenticationProvider), some message returned by the authentication server may be usefull (like "locked account", "any custom mesage")

So it would be nice to display a different login.messages.error.authentication message based on the /api/authenticate call

##### **Motivation for or Use Case**

In my case, I need to display some custom message to explain the connection status

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

I can work on the PR if needed

**Comment by sbouchex** [comment]
I can work on the PR if needed

**Comment by pmverma** [comment]
Hi @sbouchex,
It is a security best practice to show a general message for login failure.
You could do such as `User 'john' is locked.`, `User 'admin' is not present in the system.`, `User 'mary' is not activated` and so on.
However, it actually reveals many aspects of user information and hence it is avoided in an internet-facing application.
If your application is an intranet application, then I believe it won't be a big deal.

However, as for JHipster, I am sure that it is not going to be changed to display some specific message.
You will require to modify your app the way you want.

**Comment by mraible** [comment]
I agree with @pmverma so I'm closing this issue.

**Comment by mraible** [comment]
﻿
Providing information about why authentication failed is not a good security practice.
