### ISSUE TITLE
The development ribbon and API links are missing when run locally (with no blueprints)

### ISSUE THREAD

**Issue by naris** [jhipster/generator-jhipster#16333]
##### **Overview of the issue**

While developing is jhipster is started with ./mvnw (without parameters) activeProfiles is empty. The log says that it defaulrs to dev,api_docs but that is not the case, it is actually empty and that causes the ts code to disable the api-docs and the development ribbon :(

##### **Motivation for or Use Case**

It breaks some very handy features of jhipster, the api docs are disabled and the development ribbon no longer appears. Attempting to run with ./mvnw -Pdev,api-docs in windows powershell results in an error as it does not like the comma

##### **Reproduce the error**

run any jhipster application with ./mvnw without any parameters. The fact that the activeProfiles are indeed empty will be confirmed by the log. For this example I created a new jhipster application with openapi enabled and without any blueprints and the only change I made was to enable skipValidateSpec due to proxy issues :

`2021-09-17 14:51:54.090  INFO 25336 --- [  restartedMain] com.mycompany.myapp.JtesterApp           : No active profile set, falling back to default profiles: dev,api-docs
2021-09-17 14:52:00.576  INFO 25336 --- [  restartedMain] com.mycompany.myapp.JtesterApp           :
----------------------------------------------------------
        Application 'jtester' is running! Access URLs:
        Local:          http://localhost:8080/
        External:       http://10.213.7.65:8080/
        Profile(s):     []
----------------------------------------------------------`

However, When I 1st ran .mvnw and the app started, the correct profiles showed. But then when I ran npm start in another terminal session the mvnw session recompiled and restarted the app and the profiles were then empty

This is the output from initial session (before the one above):
`2021-09-17 14:50:14.203  INFO 25336 --- [  restartedMain] com.mycompany.myapp.JtesterApp           : The following profiles are active: dev,api-docs
2021-09-17 14:50:25.184  INFO 25336 --- [  restartedMain] com.mycompany.myapp.JtesterApp           : Started JtesterApp in 11.929 seconds (JVM running for 12.945)
2021-09-17 14:50:25.197  INFO 25336 --- [  restartedMain] com.mycompany.myapp.JtesterApp           :
----------------------------------------------------------
        Application 'jtester' is running! Access URLs:
        Local:          http://localhost:8080/
        External:       http://10.213.7.65:8080/
        Profile(s):     [dev, api-docs]
----------------------------------------------------------`

##### **Related issues**

Yes, I reported this yesterday (issue #16309) using a blueprint

##### **Suggest a Fix**

I managed to work around the issue on the client side in my original code (with the blueprint) by changing profile.service.ts to return hard-coded values if activeProfiles is empty. However, a much better fix would be to change the java management/info endpoint (ActiveProfilesInfoContributor.java?) to return the value from getDefaultProfiles() if the value form getActiveProfiles() is empty

Here are the changes for the work-around that I made in the original code:
  constructor(private http: HttpClient, private applicationConfigService: ApplicationConfigService) {}

```
  getProfileInfo(): Observable<ProfileInfo> {
    if (this.profileInfo$) {
      return this.profileInfo$;
    }

    this.profileInfo$ = this.http.get<InfoResponse>(this.infoUrl).pipe(
      map((response: InfoResponse) => {
        // eslint-disable-next-line no-console
        console.log("response=", response)
        const profileInfo: ProfileInfo = {
          activeProfiles: response.activeProfiles,
          inProduction: response.activeProfiles?.includes('prod'),
          openAPIEnabled: response.activeProfiles?.includes('api-docs'),
        };
        if (response.activeProfiles?.length === 0) {
            profileInfo.activeProfiles = ["dev", "api-docs"];
            profileInfo.inProduction = false;
            profileInfo.openAPIEnabled = true;
            profileInfo.ribbonEnv = "dev";
        }
        else if (response.activeProfiles && response['display-ribbon-on-profiles']) {
          const displayRibbonOnProfiles = response['display-ribbon-on-profiles'].split(',');
          const ribbonProfiles = displayRibbonOnProfiles.filter(profile => response.activeProfiles?.includes(profile));
          if (ribbonProfiles.length > 0) {
            profileInfo.ribbonEnv = ribbonProfiles[0];
          }
        }
      return profileInfo;
      }),
      shareReplay()
    );
    return this.profileInfo$;
  }
}
```

##### **JHipster Version(s)**

7.0.1

##### **JHipster configuration**

`╰─ jhipster info                                                                                                                                ─╯ 
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jtester@0.0.1-SNAPSHOT C:\src\jtester
└── generator-jhipster@7.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "jtester",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["gatling"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1631903898634,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "oracle",
    "buildTool": "maven",
    "serverSideOptions": ["enableSwaggerCodegen:true"],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

git version 2.31.1.windows.1

node: v14.16.1

npm: 7.21.0

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
`
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not related to JDL

##### **Browsers and Operating System**

Windows 10 Enterprise 1909

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by swarajsaaj** [comment]
I was able to reproduce this when importing project in IDE (which in turn creates `.settings` folder and needs setting the "dev" profile manually, either through your IDE or by setting `activeProfiles` in `.settings/org.eclipse.m2e.core.prefs`).

If a project is never imported in IDE that is interfering with settings (due to m2e maybe), all works well without setting the profile.

**Comment by naris** [comment]
I am using vscode, not eclipse or some other IDE.

**Comment by naris** [comment]
Also, is shoudl ne be required to set the profile manually, the documentation and the code itself indicates that dev is the default. When the server starts, it claims that the profile is set to the default of dev,api-docs, which turns out to be a lie.

**Comment by atomfrede** [comment]
As far as I know vscode java extension reuses a lot of stuff from eclipse.

**Comment by swarajsaaj** [comment]
Yes, I tested it using VSCode in first place. Opening the project folder in it creates the '.settings' folder with m2e preferences. Agree with  @atomfrede, vscode java extension seems to do this.

But yes, its also misleading from logs because the development ribbon and Api menu are dependent on "activeProfiles" field from '/management/info' endpoint, which in this case returns empty array even if profile fallback is in place.

**Comment by atomfrede** [comment]
Yes that's seems wrong indeed.
