### ISSUE TITLE
7.2.0 produces uncompilable code

### ISSUE THREAD

**Issue by thomasbigger584** [jhipster/generator-jhipster#16331]
##### **Overview of the issue**
After running 7.2.0 upgrade on an older application, I am getting uncompilable code in WebConfigurer.java line 81. 
The method provided requires a string but the parameter is an enum:

`String fullExecutablePath = decode(this.getClass().getResource("").getPath(), StandardCharsets.UTF_8);`

##### **Motivation for or Use Case**
I know I can change this enum to string, but I would rather have the generator fix this issue so I can make my next upgrade easier.

##### **Reproduce the error**

Run jhipster --force --with-entities and see output in WebConfigurer line 81

##### **Suggest a Fix**
We can append the name function to make it return the string representation:  `StandardCharsets.UTF_8.name()`

##### **JHipster Version(s)**

7.2.0

**Comment by thomasbigger584** [comment]
Additional note: when providing `StandardCharsets.UTF_8.name()` then the `decode()` method throws a checked `UnsupportedEncodingException`. So may need to handle this as well...

**Comment by atomfrede** [comment]
Which jdk are using to compile it? It is related to https://github.com/jhipster/generator-jhipster/pull/16198 (which requires jdk >= 11 I think).

**Comment by thomasbigger584** [comment]
Yeah, false alarm.. sorry. I generated a fresh project and compiling with java 11 and do not see the error.

**Comment by mshima** [comment]
We need to update supported Java version and add to changelog.
