### ISSUE TITLE
husky implementation is not compatible with npm@6

### ISSUE THREAD

**Issue by Akuka** [jhipster/generator-jhipster#16336]
The `npm exec` command introduced at npm v7
By JHipster [installation docs](https://www.jhipster.tech/installation/): 
> please use an LTS 64-bit version, non-LTS versions are not supported

The latest node LTS version is: 14.17.6 (includes **npm 6.14.15**)
npm 6.14.15 does not support `exec`

Am I missing something?

_Originally posted by @Akuka in https://github.com/jhipster/generator-jhipster/pull/16055#discussion_r711320197_

##### **JHipster Version(s)**
7.2.0

<img width="598" alt="Screen Shot 2021-09-18 at 22 31 29" src="https://user-images.githubusercontent.com/3299903/133906566-8a14e055-3463-4e2c-8c4e-3e06386a317a.png">

**Comment by atomfrede** [comment]
We are more or less require npm 7 if I am not mistaken https://github.com/jhipster/generator-jhipster/blob/main/generators/common/templates/package.json

**Comment by mshima** [comment]
We can try replacing `npm exec --no` with `npx --no-install`.
But running any npm@6 operation that deals with package-lock.json is not supported.

maven/gradle uses npm@7 and will cause package-lock.json to be recreated every time and may have cause a broken node_modules.

**Comment by mshima** [comment]
Another option is to implement `npmw` for gradle an use it.

**Comment by mshima** [comment]
Adjusted the title since npm@lts resolves to npm@7.

**Comment by Akuka** [comment]
Are you sure?

<img width="944" alt="Screen Shot 2021-09-19 at 20 41 24" src="https://user-images.githubusercontent.com/3299903/133937365-b9c5a088-5537-4341-943a-c688ba53846e.png">

**Comment by mshima** [comment]
> Are you sure?

That screenshot is from node site.

See npm@lts tag here:
https://www.npmjs.com/package/npm?activeTab=versions

**Comment by Akuka** [comment]
OK
Bottom line, anyone who follows the installation instructions, which explicitly asks to install a node in the LTS version, which comes with npm v6 - will not be able to run `git commit` because he will get an error from husky

**Comment by atomfrede** [comment]
Maybe it is just about clearly documenting, that npm7/`npm@lts` is also required?

**Comment by pascalgrimaud** [comment]
If we can find something which works for npm6 and npm7, it would be nice, as NodeLTS use npm6...
