### ISSUE TITLE
Running JH App behind reverse proxy

### ISSUE THREAD

**Issue by thomasbigger584** [jhipster/generator-jhipster#16359]
##### **Overview of the issue**

I had an app that used JHipster v4.14.1, and packaging with docker and deployed to a server with Nginx installed and routing requests for a URL like: `my.app.com/api`.
This worked fine. I was able to view the angular app and use the API.

After upgrading to v7.2.0, the assets for the web app do not load and I am greeted with the error page. Instead, they try to be pulled from `my.app.com`

Command I use to build the image: `./mvnw -ntp verify -Pprod -DskipTests jib:dockerBuild --batch-mode -e`

I know the web app is being built because I can build on localhost and run and works fine, just the web app doesn't load on the server due to the assets not being fetched from the right path.

##### **Motivation for or Use Case**

This was working before in a previous version, but now I have to restructure my webserver to host this app on a subdomain instead of my existing path structure. 

##### **Reproduce the error**

Run the app behind a web proxy like Nginx, on a custom route like `my.app.com/api`

##### **Suggest a Fix**

JH v4.14.1 didn't have this issue, but it is now a problem for newer versions.

If someone could suggest a temporary fix or where to look to change this back to the way it was, that would be helpful.

##### **JHipster Version(s)**

Worked on 4.14.1, upgrading to v7.2.0

**Comment by atomfrede** [comment]
Not sure, but do you need to set base href (resp. base property for vue/react) to `/api`? See https://www.jhipster.tech/production/ 
![image](https://user-images.githubusercontent.com/203401/134019431-8ff70475-f157-4e89-bcf0-d0cb33d0b9e8.png)

**Comment by thomasbigger584** [comment]
This looks promising, will check this out. Thanks

**Comment by thomasbigger584** [comment]
Works great. Only thing I have noticed is the Swagger UI isn't loading:
![image](https://user-images.githubusercontent.com/8379423/134022090-aa8a03ef-0723-4457-a93c-d21aef417419.png)
Any ideas?

**Comment by atomfrede** [comment]
I think there is some similar property/setting for swagger ui, but I am not sure.

**Comment by atomfrede** [comment]
Do you see where the swagger ui iframe points to? Maybe just a matter of also prefixing it with the right path.

**Comment by thomasbigger584** [comment]
Yeah iframe is there, although the JS and CSS assets are returning a 404. But it is looking in the right path for it...

![image](https://user-images.githubusercontent.com/8379423/134026704-35949670-fe25-41d4-8b68-0af8c7b161c4.png)

There must be some configuration for it. I'll keep looking, thanks

**Comment by thomasbigger584** [comment]
I haven't been able to find the configuration for swagger to work in this case.
