### ISSUE TITLE
jhipster:openshift

### ISSUE THREAD

**Issue by savvaoff** [jhipster/generator-jhipster#1636]
please make this files executable also by default (chmod +x):
.openshift/action_hooks/build
.openshift/action_hooks/pre_build

**Comment by jdubois** [comment]
Does it change anything? I didn't see any issue at the moment with those files. What do you want to do?

**Comment by savvaoff** [comment]
they were not executed by Openshift (without +x).

**Comment by jdubois** [comment]
I tested it that way, so at least it used to work -> looks annoying that Redhat changes the way Openshift works without notifying!!!
Anyway, it shouldn't do any harm, so I'm doing the +x

**Comment by magick93** [comment]
Hello, is there any documentation on using the openshift deployer?

What version of Openshift does this support?

**Comment by pascalgrimaud** [comment]
@magick93 : you can look here https://github.com/jhipster/generator-jhipster/issues/1896
OpenShift support is removed
