### ISSUE TITLE
Integrate vertical menu for admin profile (jhipster)

### ISSUE THREAD

**Issue by Hafyane** [jhipster/generator-jhipster#1637]
I work on a project jhipster

I have had a blockage is part of angularjs, I would like to integrate a menu vrtical in the admin profile so I modified scripts/app/admin.js but nothing happens.

'use strict';

angular.module('pmappApp').config(function($stateProvider) {
    $stateProvider.state('admin', {
        'abstract' : true,
        parent : 'site',
        views : {
            'gmenu@' : {
                templateUrl : 'scripts/app/admin/gmenu/gmenu.html',
                controller : 'GmenuController'
            }
        }
    });
});
![gmenu](https://cloud.githubusercontent.com/assets/11542730/8335007/8c28b0a0-1a8a-11e5-9d75-6d8fb3957fef.png)

**Comment by jdubois** [comment]
Nothing happens when you edit a file?
Either you changed the wrong file, or your OS has a serious issue!
I don't think this is a JHipster bug, so I'm closing this.
