### ISSUE TITLE
No way to upgrade projects to 7.1.2 from 6.10.5

### ISSUE THREAD

**Issue by sanketrk** [jhipster/generator-jhipster#16382]
##### **Overview of the issue**

We have a couple of microservices generated with 6.10.5 along with a blueprint generator-jhipster-entity-audit.  Now, we are trying to upgrade them 7.2.0 but unable to do so.  This is a blocker for us. 

We tried the command `jhipster upgrade --blueprints generator-jhipster-entity-audit` and below trace is printed : 

```
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-entity-audit at /usr/local/lib/node_modules/generator-jhipster-entity-audit
INFO! No custom commands found within blueprint: generator-jhipster-entity-audit at /usr/local/lib/node_modules/generator-jhipster-entity-audit
Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
✔ Checking for new blueprint versions
Looking for latest generator-jhipster-entity-audit version...
3.3.0
ERROR! Invalid Version: undefined
TypeError: Invalid Version: undefined
    at new SemVer (/usr/local/lib/node_modules/generator-jhipster/node_modules/semver/classes/semver.js:19:13)
    at compare (/usr/local/lib/node_modules/generator-jhipster/node_modules/semver/functions/compare.js:3:3)
    at Object.lt (/usr/local/lib/node_modules/generator-jhipster/node_modules/semver/functions/lt.js:2:29)
    at /usr/local/lib/node_modules/generator-jhipster/generators/upgrade/index.js:263:28
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster/generators/upgrade/index.js:260:22
    at Array.map (<anonymous>)
    at module.exports.checkLatestBlueprintVersions (/usr/local/lib/node_modules/generator-jhipster/generators/upgrade/index.js:259:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1024:25)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:49:25
703240209mac@703240209MAC PVAI-DocumentMgmtApp % jhipster --with-entities
```

We then resorted to manual upgrade with command `jhipster --with-entities` and it prints the below error :

```
ERROR! Error at entity EmailDoc: relationship name is not synchronized {
    "relationshipType": "many-to-one",
    "otherEntityName": "emailDocset",
    "otherEntityRelationshipName": "emailDoc",
    "relationshipName": "rootEmailDocset",
    "otherEntityField": "id",
    "otherEntity": "[EmailDocset Entity]",
    "ownerSide": true,
    "collection": false,
    "otherSideReferenceExists": false,
    "otherEntityIsEmbedded": false
} with {
    "relationshipType": "one-to-many",
    "otherEntityName": "emailDoc",
    "otherEntityRelationshipName": "emailDocset",
    "relationshipValidateRules": "required",
    "javadoc": "This field contain the references of all emaildocs that belong to this docset",
    "relationshipName": "emailDoc",
    "otherEntity": "[EmailDoc Entity]"
}
Error: Error at entity EmailDoc: relationship name is not synchronized {
    "relationshipType": "many-to-one",
    "otherEntityName": "emailDocset",
    "otherEntityRelationshipName": "emailDoc",
    "relationshipName": "rootEmailDocset",
    "otherEntityField": "id",
    "otherEntity": "[EmailDocset Entity]",
    "ownerSide": true,
    "collection": false,
    "otherSideReferenceExists": false,
    "otherEntityIsEmbedded": false
} with {
    "relationshipType": "one-to-many",
    "otherEntityName": "emailDoc",
    "otherEntityRelationshipName": "emailDocset",
    "relationshipValidateRules": "required",
    "javadoc": "This field contain the references of all emaildocs that belong to this docset",
    "relationshipName": "emailDoc",
    "otherEntity": "[EmailDoc Entity]"
}
    at prepareRelationshipForTemplates (/usr/local/lib/node_modules/generator-jhipster/utils/relationship.js:79:15)
    at /usr/local/lib/node_modules/generator-jhipster/generators/entity/index.js:629:11
    at Array.forEach (<anonymous>)
    at EntityGenerator.prepareRelationshipsForTemplates (/usr/local/lib/node_modules/generator-jhipster/generators/entity/index.js:628:36)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1024:25)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1025:11)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/grouped-queue/lib/subqueue.js:48:34)
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by sanketrk** [comment]
yo-rc.json of the root project : 

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.xxx.yyy"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "microservice",
    "baseName": "docManagement",
    "packageName": "com.xxx.yyy",
    "packageFolder": "com/xxx/yyy",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "NjQ4ZWRjOGY2YzFmNDRhZmQwN2E0ODgyMGZhMmY0NmMwYzQ5MDBmNGNjZjk0ZWVjNzYwZTFjMjk4ZjI0NWExZjIwMjJjNWUwZmRkMmU2MWQwNjQ2YWIwMDI0ZGE3MWVhMTczNTY0OWE0MWFlZDQ3NjdkMThmZTU4MjMxMDFmMWU=",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1611077969383,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom",
    "auditPage": true,
    "lastLiquibaseTimestamp": 1613557120000
  }
}
```

**Comment by sanketrk** [comment]
Associated JDL : 
entity EmailDoc {
	/** Primary Key of the table, it is auto increment number */
	id Integer required
	/** This field contain the URL of the doc on S3 databse */
	emailDocUrl String required maxlength(1000)
	/** This field contain the PDF URL of the doc on S3 databse */
	emailPdfUrl String required maxlength(1000)
	/** This field contain the file doc name  */
	emailDocName String required maxlength(550)
	/** This field contain the xce status  for a doc */
	xceStatus Integer required
	/** This field contain the number of anticipated cases */
	potentialCases Integer required
	/** This field value 'N' if the quality of the doc is not checked. And the values referenced from lau_reference_details table */
	qcStatus String required maxlength(1)
	/** This field value contain 0 if the doc is not processed from XCE */
	doNotProcess Boolean required
	/** This field value contain 1 the data got truncated  */
	isDocTruncated Boolean required
	/** This field contain the number of pdf pages */
	totalPdfPages Integer required
	/** This Field contain the staus of doc (DRAFT,NEW,REJECTED,ACCEPTED,SENT,RESTORED,VIEWED) */
	emailDocStatus String required maxlength(30)
	/** company Received Date */
	companyReceiveDate Instant
	/** This field contain the priority of the doc (1(Highr),2(Normal),3(Low)) */
	priority Integer required
	/** This field contain the name of format  */
	docFormat String required maxlength(200)
	/** This field contains the latest activity performed corresponding to doc */
	lastActivity String maxlength(20)
	/** This field contains email type information */
	emailType EmailType required
	/** This field value will contain the doc conversion status for a document */
	isDocConverted DocConversionStatus required
	/** This field contain the name user  to which this doc assigned */
    assignedUser String required maxlength(300)
}

/** This table contain the file docset level information.  */
entity EmailDocset {
	/** Primary Key of the table, it is auto increment number */
	id Integer required
	/** This field contain the type of worklist type(ARCHIVE INBOX REJECTED SENT) */
	worklistType String required maxlength(8)
	/** This field contain the status of worklist ex-VIEWED,REJECTED,NEW,ACCEPTED,Sent,Pending,Failed,RESTORED */
	worklistStatus String required maxlength(8)
	/** This field value will contain 1 if the doc is converted to pdf */
	isDocConverted Boolean required
	/** This field contain the email id of the receiver */
	receivedFrom String required maxlength(300)
	/** This is field contain the group id of the user received in the docset */
	userGroupId String required maxlength(300)
	/** This field contain the name user group to which this doc assigned */
	assignedUserGroup String required maxlength(100)
	/** This field contains, receive date of the docset  */
	receivedDate Instant required
	/** This field contain the  INTERNAL , EXTERNAL value of doc (How this doc got recived from internal or from external ) */
	receiveType String required maxlength(10)
	/** Unique ID or Message ID , comes from tipco, Used to check core-app already processed or not. */
	messageId String required maxlength(400)
    /** This field contain the number of anticipated cases */
    potentialCases Integer required
	/** This field contain root level docset id corresponding to the docset id  */
	rootDocsetId Long
	/** This field contain parent docset id corresponding to the docset id  */
	parentDocsetId Long
}

**Comment by pascalgrimaud** [comment]
Not sure we can do something.

Upgrading from v6 to v7 is a major upgrade. You need to do it manually. A tool like upgrade can't do the job.

**Comment by mshima** [comment]
`generator-jhipster-entity-audit` is a module, not a blueprint.
We don't support upgrading modules.
