### ISSUE TITLE
Change database table's name

### ISSUE THREAD

**Issue by hamark** [jhipster/generator-jhipster#1638]
Hi, 
First, thank you for all you've done with this project! 
I haven't found a way to change the database table's name when automatically creating or updating an entity. It would be great to have this feature when you have to comply to enterprise naming conventions.

**Comment by jdubois** [comment]
You can't change the default generated name:

- we can't have options for everything, it would make JHipster more complex
- we don't do options for things that are too simple: our value added is then very low

If you want to change a table name:

- Change it in your Liquibase configuration
- Change it in your JPA table mapping

That's all!

**Comment by gmarziou** [comment]
What about having table name in the entity json file* so that it could be edited and re-run?

**Comment by jdubois** [comment]
I'd rather not have too many options here too: they are not really documented, and we use them for JHipster UML (and maybe other tools later!), so the more complex they are, the more trouble we will have later. Those files should be simplified first, but that will break JHipster UML, and that's not the moment to break it (it's near the end of the project, so my trainees should soon find a real job, hopefully at my company - so I'll need to find new trainees!).
