### ISSUE TITLE
When there is a backend error, no error message shows up in the front end. 

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#16393]
##### **Overview of the issue**

When there is a backend error, no error message shows up in the front end. The BadRequestAlertException is thrown in the backend. The following error messages show up on the browser console, 
```
createError.js:16 
Uncaught (in promise) Error: Request failed with status code 400
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.onloadend (xhr.js:54)

createError
@
createError.js:16

settle
@
settle.js:17

onloadend
@
xhr.js:54

Promise.then (async)



push../node_modules/ts-loader/index.js??clonedRuleSet-1[0].rules[0].use[0]!./src/main/webapp/app/entities/job-candidate-repo/job-candidate-repo-update.component.ts?vue&type=script&lang=ts&.JobCandidateRepoUpdate.save
@
job-candidate-repo-u…te.component.ts:106

submit
@
job-candidate-repo-update.vue?cd42:14

invokeWithErrorHandling
@
vue.esm.js:1872

invoker
@
vue.esm.js:2197

original._wrapper
```
But, there isn't an error message in the front end. 

I have reported the error before due to another error type 500. The fix likely doesn't address the root problem. I still observe the problem after upgrading to 7.2.0.

##### **Motivation for or Use Case**

User experience

##### **Related issues**

#17522

##### **Suggest a Fix**

The BadRequestAlertException perhap needs to be handled.

##### **JHipster Version(s)**

7.1.0, 7.2.0

##### **JHipster configuration**
```

{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "myapp",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1626276896721,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.mycompany.myteams.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "cosmo",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myteams/myapp",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "de"],
    "entities": ["JobCandidateRepo", "RepositoryTemplate"],
    "lastLiquibaseTimestamp": 1629745008000
  }
}
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by swarajsaaj** [comment]
This is because there seems no error handling in place for Vue entities.
I could replicate this on `main`:-
![image](https://user-images.githubusercontent.com/6285049/134805175-f70cc78d-8a11-46ba-bd06-16d29068966a.png)

Though for success callbacks, a toast is displayed in most cases, but none in case of errors.
One such reference in create entity:-
https://github.com/jhipster/generator-jhipster/blob/0302965155a0b2f5c3da1ecd1861601e554e5eeb/generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs#L205-L223

Also the axios interceptors don't seem to handle this.

I ll try to fix this with a PR soon.

**Comment by pascalgrimaud** [comment]
Thanks for the configuration @swarajsaaj 
I'm adding a bounty to motivate people to improve this part :)

**Comment by swarajsaaj** [comment]
Translations for 'message' keys in exception response already exist, I think that is the obvious candidate to be shown in toast message. I ll try to see how well it works.
