### ISSUE TITLE
Okta password is written to .yo-rc.json even when Okta is not used

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16394]
##### **Overview of the issue**

When you run `jhipster heroku` with an OAuth 2.0 app, it writes an `oktaAdminPassword` key pair to `.yo-rc.json`. For example:

```
"useOkta": false,
"oktaAdminPassword": "67943b78cd02ef38c41af4cf30fb3fc98dbf0a31"
```

##### **Motivation for or Use Case**

When `useOkta` is false, there should be no other Okta-related values written to `.yo-rc.json`. 

Adding a password when it's not used will give the false impression that sensitive information has been leaked into source control.

##### **Reproduce the error**

Use the latest `main` branch to create an app and select OIDC for authentication. Then, run `jhipster heroku` to deploy it. Even if you select no for Okta, there's a value written for the password to `.yo-rc.json`. 

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/16299

##### **Suggest a Fix**

I tried to fix it but was unable to. I'm not sure what needs to change so this value isn't written.

##### **JHipster Version(s)**

`main` branch.

**Comment by atomfrede** [comment]
Didn't test it out but maybe we don't need to store it at all as the user must remember it and once for the initial login. Maybe we can just skip the prompt for the password and print it in the end to the console.

**Comment by yuvarajsanjeevi** [comment]
@atomfrede after successfully configured Okta we are printing the credentials https://github.com/jhipster/generator-jhipster/blob/main/generators/heroku/index.js#L863.

if we are sure we do not need that log then we can ignore it from writing into .yo-rc.json. otherwise we need it.

**Comment by yuvarajsanjeevi** [comment]
I claim the bounty at  https://opencollective.com/generator-jhipster/expenses/51608

**Comment by pascalgrimaud** [comment]
@yuvarajsanjeevi : approved, thanks for your work

**Comment by mraible** [comment]
I just tried this today and when you do select Okta, the password is still written to `.yo-rc.json`. Even though it's a temporary password, it seems like it's a risk because the user could check in the code before they log in to their app.

**Comment by atomfrede** [comment]
Did you used the main branch?

**Comment by yuvarajsanjeevi** [comment]
Since we are setting in config password has been written to '.yo-rc.json'
https://github.com/jhipster/generator-jhipster/blob/main/generators/heroku/index.js#L298

@mraible Can you please test with the PR branch

**Comment by mraible** [comment]
Yes, I will test now.
