### ISSUE TITLE
Improve Marketplace

### ISSUE THREAD

**Issue by jgdvarun60** [jhipster/generator-jhipster#16406]
##### **Overview of the feature request**

All the market place must be segrigated or atleast labelled for [modules or blueprints]*[different back end technologies and different front end technologies] that way its easy to search the exact market place item.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jgdvarun60** [comment]
Also compatibility of the modules with different technologies, we need to segregate front end module with back end module that way both can be applied independently. Like for example if we have multi tenant module for back end java and than multi tenant module for front end react or multi-tenant module for front end angular etc... Organizing the modules will definitely help in reducing the duplicate modules.

**Comment by pascalgrimaud** [comment]
Everything depends on the community.
What can be done to do what you suggest?
