### ISSUE TITLE
jdl does not work. SC 404 on https://raw.githubusercontent.com/jhipster/jdl-samples/main/jhipster-jdl.jh

### ISSUE THREAD

**Issue by emilc77** [jhipster/generator-jhipster#16425]
##### **Overview of the issue**

The JDL generator fails on simple Cassandra and Postgres apps.
In the console looks like an issue on https://raw.githubusercontent.com site.

##### **Motivation for or Use Case**

This is the default JDL execution.

##### **Reproduce the error**

Step 1. create an empty cassandra project.

? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? jhipster
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? com.mycompany.myapp
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? Cassandra
? Which cache do you want to use? (Spring cache abstraction) No cache - Warning, when using an SQL database, this will disable the Hibernate 2nd level cache!
? Would you like to use Maven or Gradle for building the backend? Maven
? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? Which other technologies would you like to use?
? Which *Framework* would you like to use for the client? Angular
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to enable internationalization support? No
? Please choose the native language of the application English
? Besides JUnit and Jest, which testing frameworks would you like to use? Gatling, Cucumber
? Would you like to install other generators from the JHipster Marketplace? No

Step 2. add the following jhipster-jdl.jdl with this content:

entity Employee {
	firstName String,
	lastName String,
	email String,
	phoneNumber String,
	hireDate Instant,
	salary Long,
	commissionPct Long
} 

Step 3. Run entity generator

C:\Temp\jhipster-cassandra>jhipster jdl jhipster-jdl.jh
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Downloading file: https://raw.githubusercontent.com/jhipster/jdl-samples/v7.1.0/jhipster-jdl.jh
INFO! Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/v7.1.0/jhipster-jdl.jh: 404 - Not Found
INFO! Downloading file: https://raw.githubusercontent.com/jhipster/jdl-samples/main/jhipster-jdl.jh
ERROR! Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/main/jhipster-jdl.jh: 404 - Not Found
Error: Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/main/jhipster-jdl.jh: 404 - Not Found
    at ClientRequest.<anonymous> (C:\Temp\jhipster-cassandra\node_modules\generator-jhipster\cli\download.js:33:25)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:376:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)

##### **Related issues**
-

##### **Suggest a Fix**
no idea.

##### **JHipster Version(s)**
7.1.0
7.2.0
both on windows laptops.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["gatling", "cucumber"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1632472163474,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "cassandra",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
No files generated in the directory `.jhipster`

##### **Environment and Tools**
java version "11.0.11" 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)
git version 2.32.0.windows.2
node: v14.17.0
npm: 6.14.13
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.26.2, build eefe0d31
No change to package.json was detected. No package manager install will be executed.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Unfortunatelly the entities are not created.
The .jhipster directory is empty.

##### **Browsers and Operating System**
Windows.
Latest Chrome.

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by swarajsaaj** [comment]
@emilc77 if the JDL file name is ` jhipster-jdl.jdl `, then command should be `jhipster jdl jhipster-jdl.jdl` and not `jhipster jdl jhipster-jdl.jh` (or its just a typo in bug description?)
In case the file is missing then it looks for the file on jdl-example repository.

**Comment by emilc77** [comment]
Yes, this is cause. Thank you.

The saved file from
https://start.jhipster.tech/jdl-studio/
has this name: jhipster-jdl.jdl
And the command line from home page of jhipster is 
jhipster jdl jhipster-jdl.jh
The extensions differ.

For the persons involved, consider being consistent with the file name in the 2 places.

Thank you @swarajsaaj

**Comment by mshima** [comment]
> And the command line from home page of jhipster is
> jhipster jdl jhipster-jdl.jh

Where exactly, so we can fix?

**Comment by swarajsaaj** [comment]
@mshima I think @emilc77  is talking about the 5 steps on homepage https://www.jhipster.tech/
JDL-studio saves a .jdl file, but steps mention a .jh (though both extensions are commonly used, following steps as-is can cause this issue)

**Comment by emilc77** [comment]
I would go first on a check in the command line:
jhipster jdl jhipster-jdl.jh
with the error "File not found 'jhipster-jdl.jh'" in case the file name is not correct.

**Comment by swarajsaaj** [comment]
>Step 1
I would go first on a check in the command line:
jhipster jdl jhipster-jdl.jh
with the error "File not found 'jhipster-jdl.jh'" in case the file name is not correct.

The CLI attempts to download the file from jdl-samples repository(https://github.com/jhipster/jdl-samples) as a fallback (and a usable feature for quick generation of samples). An INFO log can be added letting user know that the file provided was incorrect and now tool would look into jdl-samples for that.

**Comment by mshima** [comment]
Thanks @swarajsaaj for the fix.
