### ISSUE TITLE
Getting "ERROR! Callback called multiple times" when trying to generate a Gateway application

### ISSUE THREAD

**Issue by ArthurMiller** [jhipster/generator-jhipster#16422]
##### **Overview of the issue**

When generating a Jhipster Gateway application through the command-line, things start to generate but it always reports back an error and stops without completing the process. 
Jhipster version:
7.2.0

Error:

   create src/main/webapp/i18n/tr/login.json
   create src/main/webapp/i18n/tr/user-management.json
ERROR! Callback called multiple times
Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
    at NodeError (node:internal/errors:371:5)
    at onFinish (node:internal/streams/writable:667:37)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7) {
  code: 'ERR_MULTIPLE_CALLBACK'
}

##### **Motivation for or Use Case**

Currently I cannot generate a completed Gateway application.

##### **Reproduce the error**

Generate a Jhipster application Gateway with No service discovery, OAuth 2.0, React, Cypress, Gatling, Cucumber Postgesql DB, Hazelcast, Kafka, API first, all languages, 

##### **Related issues**

N/A

##### **JHipster Version(s)**

7.2.0

##### **JHipster configuration**

INFO! Using JHipster version installed globally
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test@0.0.1-SNAPSHOT /Users/arthurmiller/Desktop/equipifibnplapps/equipifibnplgateway
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "gateway",
    "baseName": "test",
    "jhipsterVersion": "7.2.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling", "cucumber"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1632455523925,
    "serviceDiscoveryType": "no",
    "reactive": true,
    "authenticationType": "oauth2",
    "packageName": "com.test.app",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": ["searchEngine:elasticsearch", "messageBroker:kafka", "enableSwaggerCodegen:true"],
    "websocket": false,
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "enableSwaggerCodegen": true,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "cosmo",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "monorepository": true,
    "skipCommitHook": true,
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": [
      "en",
      "al",
      "ar-ly",
      "hy",
      "by",
      "bn",
      "bg",
      "ca",
      "zh-cn",
      "zh-tw",
      "hr",
      "cs",
      "da",
      "nl",
      "et",
      "fa",
      "fi",
      "fr",
      "gl",
      "de",
      "el",
      "hi",
      "hu",
      "in",
      "it",
      "ja",
      "ko",
      "mr",
      "my",
      "pl",
      "pt-br",
      "pt-pt",
      "pa",
      "ro",
      "ru",
      "sk",
      "sr",
      "si",
      "es",
      "sv",
      "tr",
      "ta",
      "te",
      "th",
      "ua",
      "uz-Cyrl-uz",
      "uz-Latn-uz",
      "vi"
    ],
    "enableGradleEnterprise": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Homebrew (build 16.0.2+0)
OpenJDK 64-Bit Server VM Homebrew (build 16.0.2+0, mixed mode, sharing)

git version 2.30.1 (Apple Git-130)

node: v16.10.0

npm: 7.24.0

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

OSX 11.5.2

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by swarajsaaj** [comment]
This could be due to usage of non-LTS version of nodejs (16.10.0). Can you try if it works fine with LTS version (14.17.6) ?

**Comment by ArthurMiller** [comment]
I'll try that right now and get a response back to you asap.

**Comment by ArthurMiller** [comment]
That did the trick, thank you!!!
I ran:
npm install -g n
n 14.17.6

**Comment by pascalgrimaud** [comment]
Thanks for the feedback
So the ticket can be closed
