### ISSUE TITLE
git commit somehow triggers npm after upgrade to 7.2.0

### ISSUE THREAD

**Issue by Simsal** [jhipster/generator-jhipster#16433]
##### **Overview of the issue**

Since Upgrade from 7.0.0 to 7.2.0 the git commit command doesn't work anymore on my repository. Other git commands work as expected, but git commit somehow triggers npm.

I honestly do not know, if it is a problem with jhipster, but it started to occur after the 7.2.0 upgrade. On another dev machine with the 7.0.0 version of my project, git still works as expected

```
git commit -m "wip"

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    C:\Users\frank\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.8 C:\Program Files\nodejs\node_modules\npm
```

husky - pre-commit hook exited with code 1 (error)

##### **JHipster Version(s)**

```
project@0.0.1-SNAPSHOT C:\Users\frank\Workspace\project
`-- generator-jhipster@7.2.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.project.project",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "7.2.0",
    "applicationType": "monolith",
    "baseName": "project",
    "packageName": "de.project.project",
    "packageFolder": "de/project/project",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1601751214138,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": ["de", "en"],
    "blueprints": [],
    "lastLiquibaseTimestamp": 1624704750000,
    "skipUserManagement": true,
    "withAdminUi": true,
    "skipClient": false,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "pages": [],
    "reactive": false,
    "entities": [
      "removed"
      "GameStatistic"
    ],
    "enableGradleEnterprise": false,
    "devServerPort": 4200
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

git version 2.29.2.windows.2

node: v14.15.0

npm: 6.14.8

Docker version 20.10.7, build f0df350

docker-compose version 1.29.2, build 5becea4c

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
It is related to npm 6.
You can find the fix here: https://github.com/jhipster/generator-jhipster/pull/16360/files

I'm closing this as it's already fixed and will be in the next release
