### ISSUE TITLE
Microfrontend Add Capability to Define an Entity of the Same name with Different Properties In Different Services

### ISSUE THREAD

**Issue by RDsideNow** [jhipster/generator-jhipster#16462]
##### **Overview of the feature request**

Since implementing microfrontends it is now possible to have an entity with the same name and different properties is two different services, but with the current capabilities the first defined entity is what gets used.  It would be nice to be able to define an entity for two different services with the same name and different properties and annotate the entity with which service it belongs to.

##### **Motivation for or Use Case**

Improve microfrontend capabilities

##### **Related issues or PR**

I dont think so.

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
+1, I had the same issue years ago I had an aggregate ms fed with events coming from other, thus being composed of many entities that were the same in multiple ms.
The only hack I had was to prefix (or suffix) the name of each entity by the ms trigram

**Comment by RDsideNow** [comment]
Keep open

**Comment by mshima** [comment]
> @mshima i think i follow. To make sure i do, the JDL will still require you to specify a specify name for each entity, but the @EntityName annotation will allow the service to use the name specified between the parenthesis so each service would have a foo entity. Is that right?

Yes, kind of.
The `entityName` is currently:
The `entityName` used at generated source.
https://github.com/jhipster/generator-jhipster/blob/1de9167f7960c12a6934f0f564337edf08a110c4/utils/entity.js#L110

And the entity jhipster model name, used to refer relationships at `.jhipster/*.json` models.
Entity itself:
https://github.com/jhipster/generator-jhipster/blob/1de9167f7960c12a6934f0f564337edf08a110c4/generators/entity/index.js#L523
Relationship references:
https://github.com/jhipster/generator-jhipster/blob/1de9167f7960c12a6934f0f564337edf08a110c4/generators/entity/index.js#L562-L565


My proposal is to keep the entity filename (.jhipster/*.json) and the name inside it as the entity jhipster model name.
But allow the `@EntityName` annotation to override the generated entity name by doing the following change:
https://github.com/jhipster/generator-jhipster/blob/1de9167f7960c12a6934f0f564337edf08a110c4/utils/entity.js#L110
to
```
const entityName = _.upperFirst(entityWithConfig.entityName || entityWithConfig.name);
```
This change alone may be enough to close this issue but I am not whiling to test it myself right now.

**Comment by RDsideNow** [comment]
Can this be reopened?
