### ISSUE TITLE
side by side approach - missing

### ISSUE THREAD

**Issue by joro88** [jhipster/generator-jhipster#16477]
##### **Overview of the issue**

Side-by-side approach is an enormous productive step for jHipster. It would allow stay with jHipster generator much longer. Currently jHipster is used only for first step of project and then abandoned.

##### **Motivation for or Use Case**

Side-by-side was planned for 7.0.0-beta.0, so it is delayed about 10 months till now according: https://github.com/jhipster/generator-jhipster/issues/12497

##### **Reproduce the error**

Side-by-side approach is just not implemented.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/12497

##### **JHipster Version(s)**

7.2.0

##### **JHipster configuration**

N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A

- [v ] Checking this box is mandatory (this is just to show you read everything)

**Comment by joro88** [comment]
Any info?

**Comment by joro88** [comment]
Issue is not solved. Reopen it, please.

**Comment by pascalgrimaud** [comment]
@joro88 : I'm reopening it, but what do you expect from this ticket ? What do you suggest to solve it ? Do you want to contribute to propose something ?

**Comment by joro88** [comment]
What is status of that feature?

**Comment by pascalgrimaud** [comment]
@joro88 : nothing has been done, unless you want to take the lead on this and propose something ?

**Comment by joro88** [comment]
@pascalgrimaud I thought bugreports are written when software does not meet specification.

If that's not the case for jhipster, you could close the issue for third time without doing anything.

We see jhipster project does not meet specs. Missing milestone with ~1 year is not an issue for project lead. 

And when we ask, we get question back: "you want to take the lead on this"?

**Comment by atomfrede** [comment]
JHipster is fully open source. We do it all in our free time. We never promised to deliver something. We usually change or postpone features too later releases. While I agree side by side would be cool too have it's mostly about how you organize custom code so for the first try a documented approach is a good starting point as proposed in the mentioned pull request.

**Comment by Tcharl** [comment]
And note that the doc is currently in review: https://github.com/jhipster/jhipster.github.io/pull/1171

**Comment by joro88** [comment]
What I want is just to keep this issue open, please.
A lot of work has done in 7.x. Obviously all of it is prioritized over SBS / side-by-side. 
Maybe I made wrong assumption that SBS would give more benefit to mostly anyone. The assumption was based on jhipster feedback I have seen outside. And on some comments that even your dev team do this work – but manually. 
P.S. Thanks for great product you make.

**Comment by DanielFran** [comment]
@joro88 Will close this issue in favour of https://github.com/jhipster/generator-jhipster/issues/12497.
