### ISSUE TITLE
Incompatibilities between some prod and dev databases

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#16485]
##### **Overview of the issue**

There are some incompatibility between some database:
Choosing H2 as dev database and mssql as Prod databse lead to an unability of liquibase to startup (sql error while executing create table).

##### **Motivation for or Use Case**

fixing bug!

##### **Reproduce the error**

Choose H2 as dev db and Mssql as prod DB

##### **Suggest a Fix**

It's due to a dependency to `liquibase-mssql` in the pom in the main dependency section, whereas moving it in their relative profile (dev or prod) fix the thing. Not worth to mention that it's also a best practice :-)

I'll fix it when I'll have a minute

##### **JHipster Version(s)**

7.2.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I'm removing the stale label, as it's solved
