### ISSUE TITLE
Languages with dayjsLocaleId different from locale value break in react app

### ISSUE THREAD

**Issue by swarajsaaj** [jhipster/generator-jhipster#16486]
##### **Overview of the issue**

Languages with dayjsLocaleId different from locale value break in react app on changing language (For e.g. Albanian, Portuguese, Punjabi etc.)
![image](https://user-images.githubusercontent.com/6285049/135340180-70839910-0671-4f1d-95fa-f74fdbd13e65.png)

##### **Motivation for or Use Case**
Languages with different dayjs locale should work.

##### **Reproduce the error**

Add any of language with a special dayjs locale value (For e.g. Albanian, Portuguese, Punjabi etc.) and switch language from navbar.

##### **Related issues**

Somewhat related (but with numeral.js) #16011

##### **Suggest a Fix**

Following import doesn't check dayjsLocaleId while importing. 

https://github.com/jhipster/react-jhipster/blob/6f8b5147ed182e3adb6e06ccf20d57d2e39f4a2a/src/language/translator-context.ts#L34

Though this is already imported correctly in `app/config/dayjs.ts`

https://github.com/jhipster/generator-jhipster/blob/dfda919b9faa2e6e0b99ee5cf22418883db8f20e/generators/client/templates/react/src/main/webapp/app/config/dayjs.ts.ejs#L6
added needle here:-
https://github.com/jhipster/generator-jhipster/blob/c46dbd7b56c844699918e2733e3c5560dcba1ddd/generators/generator-base-private.js#L361

##### **JHipster Version(s)**

main/7.2.0

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Not needed

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
yes it's a bug

**Comment by swarajsaaj** [comment]
The problematic import is the `require` here https://github.com/jhipster/react-jhipster/blob/6f8b5147ed182e3adb6e06ccf20d57d2e39f4a2a/src/language/translator-context.ts#L34 as its already being imported by following line to `dayjs.ts` in generated project :-
https://github.com/jhipster/generator-jhipster/blob/c46dbd7b56c844699918e2733e3c5560dcba1ddd/generators/generator-base-private.js#L361

Not sure why is it being done redundantly.

**Comment by qmonmert** [comment]
I think that React JHipster Lib needs a fix here https://github.com/jhipster/react-jhipster/blob/6f8b5147ed182e3adb6e06ccf20d57d2e39f4a2a/src/language/translator-context.ts#L34
We need an equivalence between locale and dayjs-locale like in the generator https://github.com/jhipster/generator-jhipster/blob/de416a262811d1b4a894a229b0e397b3fd258f16/generators/generator-constants.js#L275

DayJS locales: https://github.com/iamkun/dayjs/tree/dev/src/locale

**Comment by mshima** [comment]
Would be nice to do a refactoring at locale enum.
Currently `value` is Java locale, `locale` is angular locale.
Would be nice to have `value` as an iso locale.
Rename Java locale to `javaLocaleId` and angular locale to `angularLocaleId`.

**Comment by swarajsaaj** [comment]
Redundant `require` removed from https://github.com/jhipster/react-jhipster/blob/6f8b5147ed182e3adb6e06ccf20d57d2e39f4a2a/src/language/translator-context.ts#L34. Please hint if there can be other solutions or this impacts anything else.

PR in progress at https://github.com/jhipster/react-jhipster/pull/79
