### ISSUE TITLE
Allow manage users and authorities

### ISSUE THREAD

**Issue by phouverneyuff** [jhipster/generator-jhipster#1648]
@jdubois , I'd like to start one PR to create a feature to manage users and roles.

Besides to use liquibase to insert authorities(roles), users and to associate user with authorities, I think that would be interesting there is in the menu a function to manage users and roles.

What do you think?

**Comment by deepu105** [comment]
I guess somebody is working on that PR already plz check open issues

**Comment by deepu105** [comment]
its #1525

**Comment by phouverneyuff** [comment]
Thanks!

**Comment by Qinwroks** [comment]
yes. but not merged yet.(@moifort, not ready?)

**Comment by gzsombor** [comment]
And there was a separate issue about creating new authorities: https://github.com/jhipster/generator-jhipster/issues/780 and a pull request: https://github.com/jhipster/generator-jhipster/pull/851 which was rejected, now the change lives on my fork ( https://github.com/gzsombor/generator-jhipster/commit/a9a9780931d1e4f6b2a32c41843f9982b7e6faa8 )

**Comment by phouverneyuff** [comment]
@gzsombor @deepu105, let's concentrate the conversation in the 1525
