### ISSUE TITLE
tech.jhipster.service.filter public class Filter<FIELD_TYPE> implements Serializable should have "setIn" overload for Set<FIELD_TYPE> parameter

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#16521]
##### **Overview of the feature request**

Though the database will likely handle duplicate field values in an in Query efficiently, I see no reason to construct such a large query. 

##### **Motivation for or Use Case**
In my service classes I usually map List<Long> parameters for Queries on Primary Key IDs to a Set<> so that all subsequent service logic is more efficient and does not produce redundant queries / results in for loops etc.

I want to be able to conveniently put the parameter value in my Query Specifications and not map them back to List

##### **Related issues or PR**

I don't know

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by CodingSpiderFox** [comment]
ping

**Comment by CodingSpiderFox** [comment]
ping

**Comment by deepu105** [comment]
you are welcome to PR with suggestion as it seems like there is no interest here
