### ISSUE TITLE
Nested entities are not getting validated

### ISSUE THREAD

**Issue by malikhan5049** [jhipster/generator-jhipster#1652]
Hi,

I am using Entities in place of DTOs in my project and the problem i was having is my nested entities which are not jsonignored are not getting validated though these entities have properties with validation annotations, workaround for this is to add a @valid annotation to these nested entites and all works fine so i was thinking may be it would be good to add @valid annotation at the time of entities generation for nested entities which are not annotated with @jsonignore, for example;

@Entity
Class A{
    string property1;
    @valid 
    @OneToOne
    Class B
}

**Comment by gzsombor** [comment]
You can't generate nested entities with JHipster, so the problem caused by the user.

**Comment by jdubois** [comment]
You are correct

**Comment by malikhan5049** [comment]
by nested entities I meant one's with you have relationships anyway I
figured out how to do that just add @valid annotation to the nested entity
and spring will validated it
