### ISSUE TITLE
Oauth2 cypress tests too slow because of login logout

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#16545]
##### **Overview of the feature request**

Cypress are tests too slow because of login logout specially when using OAuth2 because of all the redirects...
Cypress introduced a feature callled Cypress.session https://www.cypress.io/blog/2021/08/04/authenticate-faster-in-tests-cy-session-command/

##### **Motivation for or Use Case**

Faster tests

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Agreed. Adding bounty.

**Comment by pascalgrimaud** [comment]
We need to think more about this, because by doing 1 single login and 1 single logout, we can't launch 1 single test. We need to launch all tests. I don't know if I'm clear enough

Let's discuss :)

**Comment by yelhouti** [comment]
It one login per spec file as mentionned in the linked.
> The new cy.session() command solves this problem by caching and restoring cookies, localStorage and sessionStorage after a successful login. The steps that your login code takes to create the session will only be performed once when it's called the first time in any given spec file. Subsequent calls will restore the session from cache.

The file also discribes how to implement it so you don't need to worry about that running tests one by one.

**Comment by pascalgrimaud** [comment]
nice to know, so it would be a big improvement ! thanks @yelhouti

**Comment by yelhouti** [comment]
my plaisir, I will start working on it right away

**Comment by yelhouti** [comment]
it took a little bit more time than expected, because if we really oauth2logout (by to talking to the Idp) session is invalidated, instead we just clear the session client side and reload it for the next test.

**Comment by yelhouti** [comment]
@vishal423 IDP session is indeed not closed between tests in this PR.

**Comment by vishal423** [comment]
@yelhouti , Would it be possible to share the `e2e` test time numbers before and after this change? If the gain is significant, then I will plan this change for the `svelte` blueprint.

**Comment by yelhouti** [comment]
27 sec per test file from 40 sec per test file (for keycloak, since redirect...)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/100754.

**Comment by DanielFran** [comment]
@mraible approved
