### ISSUE TITLE
Use sub-package in the "domain" package

### ISSUE THREAD

**Issue by MatthieuLebigre** [jhipster/generator-jhipster#1656]
In larger application, we often want to organize the domain in sub-package : "user", "food", "drink", ...
JHipster should by default use sub-package in the "domain" package for the default entities : User, Authority, ...
I know it's easy to change it "by hand" after, but when we upgrade JHipster and regenerate the application, it's easier if the entities are in the same package, to perform the diff.

My suggestion :
 - common : AbstractAuditingEntity 
 - user : Authority, PersistentToken
 - audit : PersistentAuditEvent

**Comment by wuethrich44** [comment]
Please take a closer look at this discussion #1345.

**Comment by jdubois** [comment]
Yes, I don't want to have something too complex from the beginning. Besides, if we have separate packages, it's going to be really difficult for us to do the imports, etc, as we won't know where the classes are.

If you want several packages:

- You can still refactor, of course, that's easy with an IDE
- You could have several applications, "micro services" style -> that's where I want to go with JHipster 3, but that's just a thought at the moment
