### ISSUE TITLE
generated AuthorizationHeaderUtilTest   fails  on windows

### ISSUE THREAD

**Issue by ko5tik** [jhipster/generator-jhipster#16570]
##### **AuthorizationHeaderUtilTest  prodices failures on Windows due to timing issues**

While generating exipired token for test this code:

`            new OAuth2AccessToken(
                OAuth2AccessToken.TokenType.BEARER,
                "tokenVal",
                Instant.now(),
                accessTokenExpired ? Instant.now() : Instant.now().plus(Duration.ofMinutes(3))
            ),
`
may  produce the same instant in windows ( not in linux though )   and then an runtime exception comes from
spring boot code:

`ava.lang.IllegalArgumentException: expiresAt must be after issuedAt at org.springframework.util.Assert.isTrue(Assert.java:121) at org.springframework.security.oauth2.core.AbstractOAuth2Token.<init>(AbstractOAuth2Token.java:61) at org.springframework.security.oauth2.core.OAuth2AccessToken.<init>(OAuth2AccessToken.java:71) at org.springframework.security.oauth2.core.OAuth2AccessToken.<init>(OAuth2AccessToken.java:57) at de.vc.recorder.security.oauth2.AuthorizationHeaderUtilTest.getTestOAuth2AuthorizedClient(AuthorizationHeaderUtilTest.java:197) at`

Possible fix would be to use instant + 1ms and  waiting for one ms -   thus instant will be created, and also expired ( alternatively,  catch this exception and wait just in this case )

Some discussion about timer resolution:
https://stackoverflow.com/questions/20689055/java-8-instant-now-with-nanosecond-resolution

##### **Motivation for or Use Case**

Having  failing unit tests  is generally bad and costs evaluation time. 

##### **Related issues or PR**

none found

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by crowne** [comment]
I've made a Draft PR for this , although this is my first PR so I'd appreciate some help with the process.
https://github.com/jhipster/generator-jhipster/pull/16902

This fix below resolves the issue for me on windows

```
    private OAuth2AuthorizedClient getTestOAuth2AuthorizedClient(boolean accessTokenExpired) {
        Instant issuedAt = Instant.now();
        Instant expiresAt;
        if (accessTokenExpired) {
            expiresAt = issuedAt.plus(Duration.ofNanos(1));
            try {
                Thread.sleep(1);
            } catch (Exception e) {
                fail("Error in Thread.sleep(1) : " + e.getMessage());
            }
        } else {
            expiresAt = issuedAt.plus(Duration.ofMinutes(3));
        }
        OAuth2AccessToken token = new OAuth2AccessToken(OAuth2AccessToken.TokenType.BEARER, "tokenVal", issuedAt, expiresAt);

        return new OAuth2AuthorizedClient(
            ClientRegistration
                .withRegistrationId(VALID_REGISTRATION_ID)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .clientId("web-app")
                .clientSecret("secret")
                .redirectUriTemplate("/login/oauth2/code/oidc")
                .authorizationUri("http://localhost:8080/auth/realms/master/protocol/openid-connect/auth")
                .tokenUri("https://localhost:8080/auth/realms/master/protocol/openid-connect/token")
                .build(),
            "sub",
            token,
            new OAuth2RefreshToken("refreshVal", Instant.now())
        );
    }

```
