### ISSUE TITLE
findOneWithEagerRelationships vs findById

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#16590]
##### **Overview of the issue**

In the getMapping method of a resource class, the method findOneWithEagerRelationships of Spring Data JPA is used. In the patchMapping method of the same resource class, however, the method findById of Spring Data JPA is used to retrieve the data. That would lead to the NullPointerException exception during the instance variable update if the entity has some sort of relationship with other entities.  

I am aware that the patchMapping method isn't used by default, but it would be nice to have a correct code sample for people doing some customization in the part. (BTW, the currently patchMapping method implementation isn't useful for real-world usage for its purpose.)

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@vw98075 Are you available to contribute with a PR?

**Comment by vw98075** [comment]
Let me take a look. It has been a while since I posted the problem.
