### ISSUE TITLE
Monolith OAuth 2.0 : compilation error

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#16607]
##### **Overview of the issue**

See https://github.com/hipster-labs/jhipster-daily-builds/actions/workflows/monolith-oauth2.yaml

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Ah sorry totally forgot about it to downgrade again to have it fixed for now.
