### ISSUE TITLE
Improve Elasticsearch Docs

### ISSUE THREAD

**Issue by myspivey** [jhipster/generator-jhipster#1660]
http://jhipster.github.io/using_elasticsearch.html does not detail much of the implementation of elasticsearch. Currently on deploy, always seeing "None of the configured nodes are available: []".

**Comment by jdubois** [comment]
There isn't much, because it's the standard Spring Boot + Spring Data Elasticsearch standard configuration. I will point to their documentation.

**Comment by myspivey** [comment]
Id be interested to know why when pushing to production, leaving cluster-nodes as default and cluster-name set to a value, any persistence action either delete or create, throws an error. If I remove cluster-nodes value to use local, it stops throwing the error however search seems to stop working. That or I just do not understand how the search field is supposed to function. Regardless, seems like there is a setup step for production that is missing.

**Comment by jdubois** [comment]
Added the link to Spring Data Elasticsearch support in Spring Boot in https://github.com/jhipster/jhipster.github.io/commit/fd8bc3fb689c2ff16663bb90b762dcf9a7f7249a
