### ISSUE TITLE
Oauth2 client_secret should not be visible in javascript

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1661]
According to http://alexbilbie.com/2014/11/oauth-and-javascript/ the oauth app credentials should not be visible in the javascript and a server-side proxy should be used
The arguments in the blog seem to make sense. Anyone has a different opinion ?

For the record, this is the angular code generated by jhipster:
```javascript
var data = "username=" + credentials.username + "&password="
                    + credentials.password + "&grant_type=password&scope=read%20write&" +
                    "client_secret=mySecretOAuthSecret&client_id=jhipsteroauthapp";
```

**Comment by jdubois** [comment]
Can you check if this isn't an know issue? I've already seen this before.

**Comment by cbornet** [comment]
Oh yes, you're right. I didn't check well enough. This is a duplicate of #586.
Also, after some more readings, it appears the client secret is essentially used to identify the app (for instance so that we have different rate limitings for different apps) so this might not be a problem for jhipster

**Comment by jdubois** [comment]
So this still looks OK... If anybody can review this, it would be most welcome, as I'm not an expert in that field.

**Comment by jhoelter** [comment]
Agreed to get ride of the client credentials, definitely wrong
