### ISSUE TITLE
entity generator - String field RegExp pattern not escaped in Java

### ISSUE THREAD

**Issue by CodyBrokeIt** [jhipster/generator-jhipster#1664]
Generated an entity with a string field validated with this regular expression pattern:
^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$
to validate IPv4 addresses.

Compiling the application fails with:
```java
MyEntity.java:32: error: illegal escape character
    @Pattern(regexp = "^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$")
```
(It doesn't like that `\.` in the middle there.

MyEntity.java, should be generated as:
```java
    @NotNull
    @Pattern(regexp = "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$")
    @Field("ip")
    private String ip;
```
(With the escaped `\\.`)

The javascript side functions fine. Its a minor issue that is easily corrected after entity generation but does cause compile time error.

JHipster v2.17.0

**Comment by jdubois** [comment]
Yes, that's because the Java and the JavaScript patterns are different.
We basically just copy the regexp you enter to both Java and JavaScript -> in your case, do you mean we should replace all ```\``` by ```\\``` in Java?

**Comment by CodyBrokeIt** [comment]
Correct.

**Comment by jdubois** [comment]
I'm reopening this as the PR was reverted
