### ISSUE TITLE
Administration Data Missing With OAuth Client Implementation

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#16704]
##### **Overview of the issue**

With OAuth client implementation, there is no data on the metrics, health, configuration, and logs pages while the Swagger page shows APIs as expected. Also, those management GET APIs yield blank responses.  

##### **Motivation for or Use Case**

It is a bug due to missing data.

##### **Suggest a Fix**

Show the data as what it is in a stand-alone web application.

##### **JHipster Version(s)**

7.2.0

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "myapp",
    "jhipsterVersion": "7.2.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1626276896721,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.mycompany.components.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "cosmo",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/components/myapp",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "de"],
    "entities": ["Foo", "Boo", "Goo", "Reoo"],
    "lastLiquibaseTimestamp": 1634049322000,
    "enableGradleEnterprise": false
  }
}

```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I haven't seen this issue so I need to try and reproduce.

**Comment by vw98075** [comment]
The OAuth2 client app still needs the administration section for admin users. It can be ported from a regular JHipster app with a few changes. For user management, we only make the Profiles/user role field editable due to lacking authorization support on the OAuth server.

**Comment by mraible** [comment]
I just created a screencast today [of this blog post](https://auth0.com/blog/full-stack-java-with-react-spring-boot-and-jhipster/) and the administration screen worked fine for me. I tested on Keycloak and Auth0. 

<img width="1468" alt="Screen Shot 2021-12-17 at 16 45 52" src="https://user-images.githubusercontent.com/17892/146620135-c819b114-0288-4ed4-82dc-4cf25538977e.png">
<img width="1468" alt="Screen Shot 2021-12-17 at 16 46 09" src="https://user-images.githubusercontent.com/17892/146620156-d40d8785-e972-4e6b-b023-2464fd08b8c0.png">
<img width="1468" alt="Screen Shot 2021-12-17 at 16 46 13" src="https://user-images.githubusercontent.com/17892/146620159-0ddb98ad-53c9-4b04-9dbe-32da61f26cf2.png">
<img width="1468" alt="Screen Shot 2021-12-17 at 16 46 22" src="https://user-images.githubusercontent.com/17892/146620162-67e75392-8460-47d2-b151-8df50ae701ff.png">

I did not try your JDL, but I can do that when I get back from vacation in January.

**Comment by vw98075** [comment]
Good to know your article. Did you have the administration section right out of the generator? If so, which version did you use? I used the 7.3.0 and didn't get the administration section (both front end and back end code) at all. And after porting the code from a non-OAuth app over, I don't have the health check data. The OAuth2 server isn't Keycloak. I don't know whether that is the cause of the problem or not,

**Comment by DanielFran** [comment]
@vw98075 To add in front-end the admin pages you need to launch hipster with `--with-admin-ui flag`

This has been introduced in v7 (see https://github.com/jhipster/generator-jhipster/pull/12738)

**Comment by vw98075** [comment]
@DanielFran I think you misunderstood the issue. It is not about whether the admin UI is generated or not, but some sections of the admin UI are missing.
