### ISSUE TITLE
Generated integration tests reporting error 400 instead of OK (201) on 7.3.0

### ISSUE THREAD

**Issue by sdebnath** [jhipster/generator-jhipster#16710]
##### **Overview of the issue**

Running into server side integration test failure on clean JHipster 7.3.0 project. The entities have OneToOne as well as ManyToMany relationships. Here are the errors from running `./mvnw clean verify`

```
[ERROR] Failures:
[ERROR]   IndividualResourceIT.createIndividual:96 Status expected:<201> but was:<400>
[ERROR]   OrganizationResourceIT.createOrganization:87 Status expected:<201> but was:<400>
[ERROR]   OrganizationUnitResourceIT.createOrganizationUnit:102 Status expected:<201> but was:<400>
[ERROR]   VehicleResourceIT.createVehicle:109 Status expected:<201> but was:<400>
[INFO]
[ERROR] Tests run: 151, Failures: 4, Errors: 0, Skipped: 0
```

##### **Motivation for or Use Case**

Building a app that requires service class to handle complex relationships amongst entities.

##### **Reproduce the error**

1. Generate application with the specified .yo-rc.json
2. Use the entities JDl provided to add entities after project is created: `jhipster  jdl  <entity.jdl>`
3.  Run ./mvnw clean verify

##### **Related issues**

Similar  issue on an older version:
- https://github.com/jhipster/generator-jhipster/issues/8099

##### **JHipster Version(s)**

```
→ jhipster --version
INFO! Using JHipster version installed locally in current project's node_modules
7.3.0

```
##### **JHipster configuration**

Here's the output of jhipster info which includes the .yo-rc.json and entity definitions

  <details>
  <summary>jhipster info output</summary>
  <pre>
→ jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT /Volumes/Workspace/FlightDynamics/services/test-app
└── generator-jhipster@7.3.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "7.3.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1634412995554,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "enableGradleEnterprise": false,
    "languages": ["en", "fr"],
    "cypressCoverage": false,
    "entities": ["Individual", "Organization", "Vehicle", "OrganizationUnit"],
    "lastLiquibaseTimestamp": 1634414296000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Individual {
  id UUID required unique
}
entity Organization {
  id UUID required unique
}
entity Vehicle {
  id UUID required unique
  registration String required unique maxlength(16)
}
entity OrganizationUnit {
  id UUID required unique
}
relationship OneToOne {
  Individual{user required} to User
  Vehicle{owners required} to OrganizationUnit
  Vehicle{drivers} to OrganizationUnit
  OrganizationUnit{individualOwner} to Individual
  OrganizationUnit{organizationOwner} to Organization
}
relationship ManyToMany {
  OrganizationUnit{individual} to Individual{orgUnit}
  OrganizationUnit{organization} to Organization{orgUnit}
}

dto Individual, Organization, Vehicle, OrganizationUnit with mapstruct
service Individual, Organization, Vehicle, OrganizationUnit with serviceClass
paginate Vehicle with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

git version 2.33.0

node: v14.18.1

npm: 7.24.2

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

  </pre>
  </details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>Individual.json</summary>
<pre>
{
  "name": "Individual",
  "fields": [
    {
      "fieldName": "id",
      "fieldType": "UUID",
      "fieldValidateRules": ["required", "unique"],
      "options": {
        "autoGenerate": "true",
        "id": true
      }
    }
  ],
  "relationships": [
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "user",
      "otherEntityRelationshipName": "individual",
      "relationshipValidateRules": "required",
      "relationshipName": "user",
      "ownerSide": true
    },
    {
      "relationshipType": "many-to-many",
      "otherEntityName": "organizationUnit",
      "otherEntityRelationshipName": "individual",
      "relationshipName": "orgUnit",
      "ownerSide": false
    }
  ],
  "entityTableName": "individual",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "serviceClass",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "applications": "*",
  "changelogDate": "20211016195813"
}
</pre>
</details>

<details>
<summary>Organization.json</summary>
<pre>
{
  "name": "Organization",
  "fields": [
    {
      "fieldName": "id",
      "fieldType": "UUID",
      "fieldValidateRules": ["required", "unique"],
      "options": {
        "autoGenerate": "true",
        "id": true
      }
    }
  ],
  "relationships": [
    {
      "relationshipType": "many-to-many",
      "otherEntityName": "organizationUnit",
      "otherEntityRelationshipName": "organization",
      "relationshipName": "orgUnit",
      "ownerSide": false
    }
  ],
  "entityTableName": "organization",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "serviceClass",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "applications": "*",
  "changelogDate": "20211016195814"
}
</pre>
</details>

<details>
<summary>OrganizationUnit.json</summary>
<pre>
{
  "name": "OrganizationUnit",
  "fields": [
    {
      "fieldName": "id",
      "fieldType": "UUID",
      "fieldValidateRules": ["required", "unique"],
      "options": {
        "autoGenerate": "true",
        "id": true
      }
    }
  ],
  "relationships": [
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "individual",
      "otherEntityRelationshipName": "organizationUnit",
      "relationshipName": "individualOwner",
      "ownerSide": true
    },
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "organization",
      "otherEntityRelationshipName": "organizationUnit",
      "relationshipName": "organizationOwner",
      "ownerSide": true
    },
    {
      "relationshipType": "many-to-many",
      "otherEntityName": "individual",
      "otherEntityRelationshipName": "orgUnit",
      "relationshipName": "individual",
      "ownerSide": true
    },
    {
      "relationshipType": "many-to-many",
      "otherEntityName": "organization",
      "otherEntityRelationshipName": "orgUnit",
      "relationshipName": "organization",
      "ownerSide": true
    }
  ],
  "entityTableName": "organization_unit",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "serviceClass",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "applications": "*",
  "changelogDate": "20211016195816"
}

</pre>
</details>

<details>
<summary>Vehicle.json</summary>
<pre>
{
  "name": "Vehicle",
  "fields": [
    {
      "fieldName": "id",
      "fieldType": "UUID",
      "fieldValidateRules": ["required", "unique"],
      "options": {
        "autoGenerate": "true",
        "id": true
      }
    },
    {
      "fieldName": "registration",
      "fieldType": "String",
      "fieldValidateRules": ["required", "unique", "maxlength"],
      "fieldValidateRulesMaxlength": "16"
    }
  ],
  "relationships": [
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "organizationUnit",
      "otherEntityRelationshipName": "vehicle",
      "relationshipValidateRules": "required",
      "relationshipName": "owners",
      "ownerSide": true
    },
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "organizationUnit",
      "otherEntityRelationshipName": "vehicle",
      "relationshipName": "drivers",
      "ownerSide": true
    }
  ],
  "entityTableName": "vehicle",
  "dto": "mapstruct",
  "pagination": "pagination",
  "service": "serviceClass",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "applications": "*",
  "changelogDate": "20211016195815"
}

</pre>
</details>
##### **Browsers and Operating System**

Host:
```
→ uname -a
Darwin compewpewter.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
```
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by sdebnath** [comment]
So basically all the entities where services were defined are running into issue with object creation:

```
     Content type = application/problem+json
             Body = {"type":"https://www.jhipster.tech/problem/constraint-violation","title":"Method argument not valid","status":400,"path":"/api/organization-units","message":"error.validation","fieldErrors":[{"objectName":"organizationUnit","field":"id","message":"must not be null"}]}
```

```
     Content type = application/problem+json
             Body = {"type":"https://www.jhipster.tech/problem/constraint-violation","title":"Method argument not valid","status":400,"path":"/api/vehicles","message":"error.validation","fieldErrors":[{"objectName":"vehicle","field":"id","message":"must not be null"}]}
```

These entities have `id` defined as 

```
 @AutoGenerate(true) @Id id UUID required unique,
```
Here's the JDL file that I used to create the entities (this was translated and is mostly the same but doesn't have the autogenerated information in the `jhipster info` output above:

  <details>
  <summary>entity.jdl</summary>
  <pre>
@dto(mapstruct)
entity Individual {
    @AutoGenerate(true) @Id id UUID required unique
}

@dto(mapstruct)
@service(serviceClass)
entity Organization {
    @AutoGenerate(true) @Id id UUID required unique
}

@paginate(pagination)
@dto(mapstruct)
@service(serviceClass)
entity Vehicle {
    @AutoGenerate(true) @Id id UUID required unique,
    registration String required unique maxlength(16),
}

@dto(mapstruct)
@service(serviceClass)
entity OrganizationUnit {
    @AutoGenerate(true) @Id id UUID required unique,
}

relationship OneToOne {
    Individual{user required} to User
}

relationship OneToOne {
    Vehicle {owners required} to OrganizationUnit,
    Vehicle {drivers} to OrganizationUnit,
}

relationship ManyToMany {
    OrganizationUnit {individual} to Individual {orgUnit}
    OrganizationUnit {organization} to Organization {orgUnit}
}

relationship OneToOne {
    OrganizationUnit {individualOwner} to Individual
    OrganizationUnit {organizationOwner} to Organization
}

  </pre>
  </details>

Full log for for one of the tests:

```
[INFO] Running com.mycompany.myapp.web.rest.VehicleResourceIT
2021-10-16 13:00:57.609  WARN 83109 --- [           main] o.z.problem.spring.common.AdviceTraits   : Bad Request: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<com.mycompany.myapp.service.dto.VehicleDTO> com.mycompany.myapp.web.rest.VehicleResource.createVehicle(com.mycompany.myapp.service.dto.VehicleDTO) throws java.net.URISyntaxException: [Field error in object 'vehicleDTO' on field 'id': rejected value [null]; codes [NotNull.vehicleDTO.id,NotNull.id,NotNull.java.util.UUID,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [vehicleDTO.id,id]; arguments []; default message [id]]; default message [must not be null]]

MockHttpServletRequest:
      HTTP Method = POST
      Request URI = /api/vehicles
       Parameters = {}
          Headers = [Content-Type:"application/json;charset=UTF-8", Content-Length:"84"]
             Body = {"registration":"AAAAAAAAAA","owners":{"id":"83b8fcad-f350-4f88-bd16-949bfd25910b"}}
    Session Attrs = {}

Handler:
             Type = com.mycompany.myapp.web.rest.VehicleResource
           Method = com.mycompany.myapp.web.rest.VehicleResource#createVehicle(VehicleDTO)

Async:
    Async started = false
     Async result = null

Resolved Exception:
             Type = org.springframework.web.bind.MethodArgumentNotValidException

ModelAndView:
        View name = null
             View = null
            Model = null

FlashMap:
       Attributes = null

MockHttpServletResponse:
           Status = 400
    Error message = null
          Headers = [Vary:"Origin", "Access-Control-Request-Method", "Access-Control-Request-Headers", Content-Type:"application/problem+json", X-Content-Type-Options:"nosniff", X-XSS-Protection:"1; mode=block", Cache-Control:"no-cache, no-store, max-age=0, must-revalidate", Pragma:"no-cache", Expires:"0", X-Frame-Options:"DENY", Content-Security-Policy:"default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:", Referrer-Policy:"strict-origin-when-cross-origin", Permissions-Policy:"camera=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), sync-xhr=()"]
     Content type = application/problem+json
             Body = {"type":"https://www.jhipster.tech/problem/constraint-violation","title":"Method argument not valid","status":400,"path":"/api/vehicles","message":"error.validation","fieldErrors":[{"objectName":"vehicle","field":"id","message":"must not be null"}]}
    Forwarded URL = null
   Redirected URL = null
          Cookies = []
2021-10-16 13:00:57.623 ERROR 83109 --- [           main] tech.jhipster.web.util.HeaderUtil        : Entity processing failed, Invalid ID
2021-10-16 13:00:57.623  WARN 83109 --- [           main] o.z.problem.spring.common.AdviceTraits   : Bad Request: Invalid ID
2021-10-16 13:00:57.682 ERROR 83109 --- [           main] tech.jhipster.web.util.HeaderUtil        : Entity processing failed, A new vehicle cannot already have an ID
2021-10-16 13:00:57.683  WARN 83109 --- [           main] o.z.problem.spring.common.AdviceTraits   : Bad Request: A new vehicle cannot already have an ID
2021-10-16 13:00:57.727 ERROR 83109 --- [           main] tech.jhipster.web.util.HeaderUtil        : Entity processing failed, Entity not found
2021-10-16 13:00:57.727  WARN 83109 --- [           main] o.z.problem.spring.common.AdviceTraits   : Bad Request: Entity not found
2021-10-16 13:00:57.739 ERROR 83109 --- [           main] tech.jhipster.web.util.HeaderUtil        : Entity processing failed, Invalid ID
2021-10-16 13:00:57.739  WARN 83109 --- [           main] o.z.problem.spring.common.AdviceTraits   : Bad Request: Invalid ID
2021-10-16 13:00:57.750  WARN 83109 --- [           main] o.z.problem.spring.common.AdviceTraits   : Method Not Allowed: Request method 'PUT' not supported
2021-10-16 13:00:57.763  WARN 83109 --- [           main] o.z.problem.spring.common.AdviceTraits   : Bad Request: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<com.mycompany.myapp.service.dto.VehicleDTO> com.mycompany.myapp.web.rest.VehicleResource.createVehicle(com.mycompany.myapp.service.dto.VehicleDTO) throws java.net.URISyntaxException with 2 errors: [Field error in object 'vehicleDTO' on field 'registration': rejected value [null]; codes [NotNull.vehicleDTO.registration,NotNull.registration,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [vehicleDTO.registration,registration]; arguments []; default message [registration]]; default message [must not be null]] [Field error in object 'vehicleDTO' on field 'id': rejected value [null]; codes [NotNull.vehicleDTO.id,NotNull.id,NotNull.java.util.UUID,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [vehicleDTO.id,id]; arguments []; default message [id]]; default message [must not be null]]
2021-10-16 13:00:57.775  WARN 83109 --- [           main] o.z.problem.spring.common.AdviceTraits   : Method Not Allowed: Request method 'PATCH' not supported
2021-10-16 13:00:57.818 ERROR 83109 --- [           main] tech.jhipster.web.util.HeaderUtil        : Entity processing failed, Entity not found
2021-10-16 13:00:57.818  WARN 83109 --- [           main] o.z.problem.spring.common.AdviceTraits   : Bad Request: Entity not found
2021-10-16 13:00:57.833  WARN 83109 --- [           main] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND
[ERROR] Tests run: 16, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.25 s <<< FAILURE! - in com.mycompany.myapp.web.rest.VehicleResourceIT
[ERROR] com.mycompany.myapp.web.rest.VehicleResourceIT.createVehicle  Time elapsed: 0.017 s  <<< FAILURE!
java.lang.AssertionError: Status expected:<201> but was:<400>
	at com.mycompany.myapp.web.rest.VehicleResourceIT.createVehicle(VehicleResourceIT.java:109)
```

**Comment by sdebnath** [comment]
Okay guessing this is very likely is due to:

https://github.com/mraible/21-points/pull/58

**Comment by mheidt** [comment]
The issue is  the "required" of the @id field in the .jh file.
In former projectes we didn't define the id, so that jhipster was generating them by itself.
But having the @id defined ourselves as required, the DTO object gets a @NotNull id, which mustn't be as this object is passed in the POST and is rejected by the @Valid.
Only the PUT has an id already.
The best would be, if jhipster is not setting a @NotNull in the DTO object but in the entity object only.

**Comment by DanielFran** [comment]
@mheidt Are you available to contribute with a PR?
