### ISSUE TITLE
Want one more datatype which can store file in database (like : Blob)

### ISSUE THREAD

**Issue by abhshekshah2885** [jhipster/generator-jhipster#1673]
Hello,

Is there any support of field datatype of schema which could be store any file (like : *.docx,etc.) into the database. If any support available for this functionality then please suggest me..!! One more suggestion is that, if file could be store in database by user, so at that place file upload button should be available (UI Side) like file upload..!!

**Comment by atomfrede** [comment]
@andidev is already working on that. See #1651

**Comment by jdubois** [comment]
Yes, this is a duplicate, please check before posting a new ticket (as asked in the guidelines)
