### ISSUE TITLE
Docker Sub generator

### ISSUE THREAD

**Issue by savoisn** [jhipster/generator-jhipster#1674]
Hi everyone,

As discussed in #1655, 
I've been working quite a bit with Jhipster and docker to deploy an application on a PAAS.

Firstly before any discussion of what we can do with docker, I'd like to have a clear idea of what the community want out of a sub generator for docker.

here are a list of ideas that could be useful: 
 - just a **Dockerfile**, that will be used to build an image
 - a **dockerfile** and the corresponding **image**
 - **dockerfile + image + a fig config** to run the jhipster app + the linked service (mongo and/or elasticsearch and/or hazzlecast and/or mail service) -> this is how i test my apps... so that's my goal, but it might be too much (or not enough) for the community

there's a lot of options here, so I'd like to here your thoughts about all that :)

**Comment by atomfrede** [comment]
I think a good solution would be a dockerfile + fig/docker-compose file to setup dependend infrastructure containers. The developer than can build the image on the local machine.

**Comment by truemath** [comment]
+1 for dockerfile + docker-compose

**Comment by jdubois** [comment]
Yes dockerfile + image + fig for me also -> what's interesting is to have all the services at once, not just JHipster. I'm thinking of someone who wants postgresql + elasticsearch, for example, which looks to be quite a common requirements (if needed, I can have a look at what is more common, so you know on what to focus on!)

**Comment by savoisn** [comment]
@jdubois : Yep exactly what I am working on.
@atomfrede : I will need to build the image in the sub-generator, cause in the fig / docker-compose we are referencing actually built images by their name. So we will need to "docker build" the Dockerfile.

**Comment by jdubois** [comment]
@savoisn any progress on your sub-generator? I'm trying to close tickets that are not being worked on.

**Comment by savoisn** [comment]
@jdubois yes it's still on going, i'll have a PR by end of week I think. took a bit of time due to vacation :)

**Comment by jdubois** [comment]
Looks like this is stuck! So I'm closing this. Anyway, I'm not sure of what we can add here.
