### ISSUE TITLE
Accessibility in JHipster

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1675]
Accessibility is an important matter and I think that JHipster could help promote good practices and tools in this area.

I recommend you have a look at Marcy Sutton's talk at JSConf US 2015 about [The Magic of Automated Accessibility Testing](https://www.youtube.com/watch?v=-XUmf_RPF8k). She is a primary contributor to [ngAria](https://docs.angularjs.org/api/ngAria), Angular's accessibility module.

Good news is that automated tools now exist, in her talk she mentions [A11y](https://github.com/addyosmani/a11y) and [Protractor accessibility plugin](https://github.com/angular/protractor/blob/master/docs/plugins.md#accessibility-plugin).

A11y has a [Grunt task](https://github.com/lucalanca/grunt-a11y) and Protractor is end to end testing for AngularJS.

So I think that JHipster could start by using ngAria: it should be straight forward, I already did it on a JHipster app without any issue.
Then we could add grunt-ally task and start fixing accessibility issues reported by it.
As I understand it, Protractor would be useful to detect accessibility regressions.

I'm volunteering to work on this topic if there's interest.

**Comment by deepu105** [comment]
It will be good but then again like i18n does everybody need this?  I guess it would depend on individual use case

**Comment by gmarziou** [comment]
I don't think you can fairly compare i18n and a11y.

i18n is highly intrusive in your client code, it has a direct impact on your productivity as a developer because you cannot write text directly in your views, it has also a slight impact on performance.
So, if you don't need it, you get good reasons for not using i18n feature in JHipster.

None of these drawbacks are true for a11y.

10% of the population has a disability of some kind, in some countries, it's mandatory.

NgAria does not require you to do any change to your code and it's included in angular so why you would you want to remove it?

Then for the grunt task, as long as it is optional, you can decide whether you run it to assess your compliance.

**Comment by deepu105** [comment]
I guess if its a grunt task its fine, as long as its not something you have to code into every view it should be OK. To be frank I havent done anything specific for accessibility so far coz it was never a requirement from my clients :wink: 
But for a public website I think its a must to have but for web apps targeting a specific user group it may not necessary if the user group doesnt want it.

Anyway my point originally was that this is good to have but should be optional

**Comment by jdubois** [comment]
Yes, that's something we should consider. I didn't code anything specific for a11y, so it depends if we have a lot of issues.

**Comment by gmarziou** [comment]
I'll run the a11y tool on a sample webapp and I'll let you know what the issues are.

**Comment by gmarziou** [comment]
Some status:
- ng-aria does not break anything in JHipster
- I haven't been able to get something useful for a11y tool
- I run full audit with Chrome accessibility tools on all pages

I'll put my notes below but globally the audit is good, I ignored few things related to the "dev" red image.
I think the biggest win would be to use labelFor in all forms.

**Comment by gmarziou** [comment]
# Accessibility audit

## Navbar

- Contrast for text is too low

## Entities

### List entities

- Meaningless link text for pagination buttons ('<<", ">>', '1', ...)

### View entity

- No label for read-only inputs (all fields)

### Edit entity

- No label for read-only input ID

## Account menu

### Edit settings

 - No label for inputs (all fields)

## Audits

- No label for form inputs

**Comment by gmarziou** [comment]
I propose to work on 3 related PR:
- add ng-aria
- add "label for" for all forms
- pagination links

**Comment by jdubois** [comment]
@gmarziou 
-> "label for" and pagination links are indeed good
-> for ng-aria I'm not sure of what this will lead us to, but yes it's good to have a look at this

Can you close this issue, and create 3 issues instead?

**Comment by gmarziou** [comment]
- add ng-aria: #1718 
- add "label for" for all forms: #1719 
- pagination links: #1720
