### ISSUE TITLE
Upgrade to Spring Boot 2.6.0

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16772]
##### **Overview of the feature request**

Since Spring Boot 2.6.0 is a major release, I figured we might want to get a head start on upgrading to it. [v2.6.0-RC1](https://github.com/spring-projects/spring-boot/releases/tag/v2.6.0-RC1) was released today.

##### **Motivation for or Use Case**

It's good for JHipster to keep up with the major releases of libraries it depends on.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by yangliuyu** [comment]
spring boot 2.6.0 is released.

**Comment by mraible** [comment]
@yangliuyu Thanks for the heads up. I've updated both of the above PRs.

**Comment by mraible** [comment]
I still believe.

**Comment by mraible** [comment]
I don't need any of the bounty. I already get paid to work on JHipster! ;)

**Comment by pascalgrimaud** [comment]
No @DanielFran, claim 500$ -> @Tcharl and @mshima same claim. No share.
It's well deserved as it's a huge amount of work

**Comment by DanielFran** [comment]
Thanks @pascalgrimaud Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/60928

**Comment by pascalgrimaud** [comment]
@DanielFran : approved

**Comment by Tcharl** [comment]
Thank @pascalgrimaud , same here: https://opencollective.com/generator-jhipster/expenses/60950

**Comment by pascalgrimaud** [comment]
@Tcharl : approved

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/68440.
