### ISSUE TITLE
When for dev h2 and for prod psql selected, h2 dependency in maven file is in test scope, so available drivers available drivers: [ postgresql, pool ] and connection error thrown when trying to start project with dev profile.

### ISSUE THREAD

**Issue by Coenni** [jhipster/generator-jhipster#16790]
When for dev h2 and for prod psql selected, h2 dependency in maven file is in test scope, so available drivers available drivers: [ postgresql, pool ] and connection error thrown when trying to start project with dev profile.

So as quick solution, it is needed to comment <scope>test</scope> for the dependencies like below:
```
<dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
<!--            <scope>test</scope>-->
        </dependency>
        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-h2</artifactId>
<!--            <scope>test</scope>-->
        </dependency>

```

**Comment by Coenni** [comment]
![image](https://user-images.githubusercontent.com/2304879/138535237-06acf87f-d8fe-409c-910a-c446fbf7d354.png)

**Comment by justingloeckl** [comment]
Seen this error on many stackoverflow questions.

**Comment by pascalgrimaud** [comment]
Very strange, as it's a code we didn't change since years: https://github.com/jhipster/generator-jhipster/blame/main/generators/server/templates/pom.xml.ejs#L249-L260

Need some investigation

**Comment by Coenni** [comment]
My God feeling says, it is because of my local mvn repo was totally new, and I tried to run the application without running tests so H2 lib scope was test, and it was not downloaded to local repo yet. But as I chose local env dB as H2, scope should not test but default.

**Comment by Tcharl** [comment]
Maybe that fix could help https://github.com/jhipster/generator-jhipster/pull/16612
