### ISSUE TITLE
React - ValidatedForm values are empty if ValidatedField is not a direct child

### ISSUE THREAD

**Issue by mohamedzaki90** [jhipster/generator-jhipster#16795]
##### **Overview of the issue**

Try adding the form fields in a nested element `div` or `Col` and then submit the form, the value associated with that field is not submitted or empty

```
<ValidatedForm>
<Col>
<ValidatedField name="somename" ...../>
</Col>
</ValidatedForm>
```

##### **Motivation for or Use Case**

This is important for styling the generated forms and also nesting components

##### **Reproduce the error**

Generate a monolith application with react client, add any entity and try to adjust the generated entity-update.tsx ValidatedForm with the suggested change above. i.e add a column above any form field and try submitting any value

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/15588

##### **JHipster Version(s)**

7.3.0
##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mohamedzaki90** [comment]
It's not possible to open an issue in the react-jhipster repo, possibly I don't have permissions?

**Comment by qmonmert** [comment]
strange cc @pascalgrimaud

**Comment by mshima** [comment]
> It's not possible to open an issue in the react-jhipster repo, possibly I don't have permissions?

Issues is not enable there. Should be posted here.

**Comment by pascalgrimaud** [comment]
Yes it's not strange, it's normal @qmonmert 
It's for centralizing all issues, so it's to have more visibility

**Comment by kristo-aun-cko** [comment]
The react-jhipster/validated-form.tsx says "The validated fields/inputs must be direct children of the form."

The children object needs recursive traversal like so:

`/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import * as React from 'react';
import { ReactElement, useEffect, useState } from 'react';
import {
  DefaultValues,
  FieldError,
  FieldValues,
  RegisterOptions,
  SubmitHandler,
  useForm,
  UseFormRegister,
  UseFormSetValue,
  ValidationMode,
} from 'react-hook-form';
import { Button, Col, CustomInput, Form, FormFeedback, FormGroup, Input, InputProps, Label, Row } from 'reactstrap';

import { byteSize, isEmpty, openFile, setFileData } from '../util';

export interface ValidatedFormProps {
  children: React.ReactNode;
  onSubmit: SubmitHandler<FieldValues>;
  defaultValues?: DefaultValues<FieldValues>;
  mode?: keyof ValidationMode;
  [key: string]: any;
}

/**
 * A wrapper for simple validated forms using Reactstrap Form and React-hook-form.
 * The validated fields/inputs must be direct children of the form.
 * This components injects methods and values from react-hook-form's `useForm` hook into the ValidatedField/ValidatedInput components
 * For complex use cases or for nested children, use Reactstrap form elements
 * or ValidatedField or ValidatedInput and pass methods and values from react-hook-form's `useForm` hook
 * directly as props
 *
 * @param ValidatedFormProps
 * @returns JSX.Element
 */
export function ValidatedForm({ defaultValues, children, onSubmit, mode, ...rest }: ValidatedFormProps): JSX.Element {
  const {
    handleSubmit,
    register,
    reset,
    setValue,
    formState: { errors, touchedFields, dirtyFields },
  } = useForm({ mode: mode || 'onTouched', defaultValues });

  useEffect(() => {
    reset(defaultValues);
  }, [reset, defaultValues]);

  const isValidatedChild = (child) => {
    const type = child?.type;
    return type
      && child?.props?.name
      && ['ValidatedField', 'ValidatedInput', 'ValidatedBlobField'].includes(type.displayName);
  };
  
  const isButton = (child) => {
    const type = child?.type?.name;
    return type && ['Button'].includes(type);
  };

  const conditionalCallback = (child, callback) => {
    if (isButton(child) || isValidatedChild(child)) {
      return callback(child)
    }
    return;
  };

  const mapRecursive = (currentChildren, callback) => (
    React.Children.map(
      currentChildren,
      child => (
        child?.props?.children
         ?
          [ conditionalCallback(child, callback), mapRecursive(child.props.children, callback)]
          : conditionalCallback(child, callback)
      ),
    )
  );

  return (
    <Form onSubmit={handleSubmit(onSubmit)} {...rest}>
      {mapRecursive(children, (child: ReactElement) => {
        const type = child?.type as any;

        if (isValidatedChild(child)) {
          const childName = child.props.name;
          const elem = {
            ...child.props,
            register: child.props.register || register,
            error: child.props.error || errors[childName],
            isTouched: typeof child.props.isTouched === 'undefined' ? touchedFields[childName] : child.props.isTouched,
            isDirty: typeof child.props.isDirty === 'undefined' ? dirtyFields[childName] : child.props.isDirty,
            key: childName,
          };
          if (type.displayName === 'ValidatedBlobField') {
            const defaultValue = defaultValues[childName];
            const defaultContentType = defaultValues[`${childName}ContentType`];
            elem.setValue = typeof child.props.setValue === 'undefined' ? setValue : child.props.setValue;
            elem.defaultValue = typeof child.props.defaultValue === 'undefined' ? defaultValue : child.props.defaultValue;
            elem.defaultContentType =
              typeof child.props.defaultContentType === 'undefined' ? defaultContentType : child.props.defaultContentType;
          }
          return React.createElement(type, { ...elem });
        }
        return child;
      })}
    </Form>
  );
}

ValidatedForm.displayName = 'ValidatedForm';

export interface ValidatedInputProps extends InputProps {
  // name of the component, also used for validation
  name: string;
  // register function from react-hook-form
  register?: UseFormRegister<FieldValues>;
  // error object from react-hook-form for the field, errors[fieldsName]
  error?: FieldError;
  // isTouched from react-hook-form for the field, touchedFields[fieldsName]
  isTouched?: boolean;
  // isDirty from react-hook-form for the field, dirtyFields[fieldsName]
  isDirty?: boolean;
  // validation rules for react-hook-form register function
  validate?: RegisterOptions;
  // value for the input element
  value?: any;
  // default value for the Input component, not needed if defaultValues for ValidatedForm is set
  defaultValue?: string | number | string[];
}

export interface ValidatedFieldProps extends ValidatedInputProps {
  // label for the field
  label?: string;
  // className for label
  labelClass?: string;
  // hide the label
  labelHidden?: boolean;
  // Field is a column inside a row
  row?: boolean;
  // objet holding attributes for the rendered column in row mode
  col?: any;
  // field is checkbox. The input will be rendered before the label
  check?: boolean;
  // css class for the input element
  inputClass?: string;
  // tag attribute for input
  inputTag?: React.ElementType;
}

/**
 * A utility wrapper over Reactstrap Input component thats uses react-hook-form data to
 * show error message and error/validated styles.
 * This component can be used with ValidatedForm
 *
 * @param ValidatedInputProps
 * @returns JSX.Element
 */
export function ValidatedInput({
  name,
  id = name,
  register,
  error,
  isTouched,
  isDirty,
  validate,
  children,
  className,
  onChange,
  onBlur,
  ...attributes
}: ValidatedInputProps): JSX.Element {
  if (!register) {
    return (
      <Input name={name} id={id} className={className} onChange={onChange} onBlur={onBlur} {...attributes}>
        {children}
      </Input>
    );
  }

  className = className || '';
  className = isTouched ? `${className} is-touched` : className;
  className = isDirty ? `${className} is-dirty` : className;

  const { name: registeredName, onBlur: onBlurValidate, onChange: onChangeValidate, ref } = register(name, validate);
  return (
    <>
      <Input
        name={registeredName}
        id={id}
        valid={isTouched && !error}
        invalid={!!error}
        innerRef={ref}
        className={className}
        onChange={e => {
          void onChangeValidate(e);
          onChange && onChange(e);
        }}
        onBlur={e => {
          void onBlurValidate(e);
          onBlur && onBlur(e);
        }}
        {...attributes}
      >
        {children}
      </Input>
      {error && <FormFeedback>{error.message}</FormFeedback>}
    </>
  );
}

ValidatedInput.displayName = 'ValidatedInput';

/**
 * A utility wrapper over Reactstrap FormGroup + Label + ValidatedInput
 * that uses react-hook-form data to show error message and error/validated styles.
 * This component can be used with ValidatedForm
 *
 * @param ValidatedFieldProps
 * @returns JSX.Element
 */
export function ValidatedField({
  children,
  name,
  id,
  disabled,
  className,
  check,
  row,
  col,
  tag,
  label,
  labelClass,
  labelHidden,
  inputClass,
  inputTag,
  hidden,
  ...attributes
}: ValidatedFieldProps): JSX.Element {
  const input = (
    <ValidatedInput name={name} id={id} disabled={disabled} className={inputClass} hidden={hidden} tag={inputTag} {...attributes}>
      {children}
    </ValidatedInput>
  );

  const inputRow = row ? <Col {...col}>{input}</Col> : input;
  return (
    <FormGroup check={check} disabled={disabled} row={row} className={className} hidden={hidden} tag={tag}>
      {check && inputRow}
      {label && (
        <Label id={`${name}Label`} check={check} for={id} className={labelClass} hidden={labelHidden || hidden}>
          {label}
        </Label>
      )}
      {!check && inputRow}
    </FormGroup>
  );
}

ValidatedField.displayName = 'ValidatedField';

interface ValidatedBlobFieldProps extends ValidatedFieldProps {
  // set value function from react-hook-forms
  setValue?: UseFormSetValue<{
    [x: string]: any;
  }>;
  // default value for the blob content type
  defaultContentType?: string;
  // blob is an image
  isImage?: boolean;
  // style for image element
  imageStyle?: Record<string, string>;
  // css class for image
  imageClassName?: string;
  // clear button override
  clearBtn?: (clearBlob: () => void) => React.ReactElement;
  // label for open action for non image blobs
  openActionLabel?: string;
}

/**
 * A utility wrapper over Reactstrap FormGroup + Label + CustomInput for blobs and images
 * that uses react-hook-form data to show error message and error/validated styles.
 * This component can be used with ValidatedForm
 *
 * @param ValidatedBlobFieldProps
 * @returns JSX.Element
 */
export function ValidatedBlobField({
  name,
  register,
  setValue,
  error,
  isTouched,
  isDirty,
  validate,
  children,
  className,
  onChange,
  onBlur,
  id = name,
  disabled,
  row,
  col,
  tag,
  label,
  labelClass,
  labelHidden,
  inputClass,
  inputTag,
  hidden,
  defaultValue,
  defaultContentType,
  isImage,
  imageStyle,
  imageClassName,
  clearBtn,
  openActionLabel,
  // will be ignored as type will always be `file`
  type,
  check,
  ...attributes
}: ValidatedBlobFieldProps): JSX.Element {
  const [blob, setBlobData] = useState<string>(defaultValue as string);
  const [blobContentType, setBlobContentType] = useState<string>(defaultContentType);

  const contentTypeName = `${name}ContentType`;

  const setBlobValue = (data, contentType) => {
    setBlobData(data);
    setBlobContentType(contentType);
    setValue(contentTypeName, contentType, {
      shouldValidate: true,
      shouldDirty: true,
    });
    setValue(name, data, {
      shouldValidate: true,
      shouldDirty: true,
    });
  };
  const clearBlob = () => {
    setBlobValue(null, null);
  };

  const renderFormGroup = inner => (
    <FormGroup disabled={disabled} row={row} className={className} hidden={hidden} tag={tag}>
      {label && (
        <Label id={`${name}Label`} for={id} className={labelClass} hidden={labelHidden || hidden}>
          {label}
        </Label>
      )}
      {inner}
    </FormGroup>
  );

  const inputRow = input => (row ? <Col {...col}>{input}</Col> : input);

  if (!register) {
    return renderFormGroup(
      inputRow(<CustomInput type="file" id={id} name={name} className={className} onChange={onChange} onBlur={onBlur} {...attributes} />)
    );
  }

  className = className || '';
  className = isTouched ? `${className} is-touched` : className;
  className = isDirty ? `${className} is-dirty` : className;

  useEffect(() => {
    register(name, validate);
    register(contentTypeName, validate);
  }, [register]);

  const input = (
    <>
      <input id={`file_${name}_content_type`} name={contentTypeName} type="hidden" />
      <CustomInput
        type="file"
        id={id}
        name={name}
        valid={isTouched && !error}
        invalid={!!error}
        className={className}
        onChange={e => {
          setFileData(
            e,
            (contentType, data) => {
              setBlobValue(data, contentType);
            },
            isImage
          );
          onChange && onChange(e);
        }}
        onBlur={e => {
          setFileData(
            e,
            (contentType, data) => {
              setBlobValue(data, contentType);
            },
            isImage
          );
          onBlur && onBlur(e);
        }}
        {...attributes}
      />
      {error && <FormFeedback>{error.message}</FormFeedback>}
    </>
  );

  const defaultClearBtn = (
    <Button color="danger" size="sm" onClick={clearBlob}>
      <strong>&nbsp;x&nbsp;</strong>
    </Button>
  );

  return renderFormGroup(
    <>
      <br />
      {blob ? (
        <div className="mb-3 mt-2 jhi-validated-blob-field-item-container">
          {blobContentType ? (
            <a onClick={openFile(blobContentType, blob)} className="jhi-validated-blob-field-item-anchor">
              {isImage ? (
                <img
                  src={`data:${blobContentType};base64,${blob}`}
                  style={imageStyle || { maxHeight: '100px' }}
                  className={imageClassName}
                />
              ) : (
                openActionLabel || 'Open'
              )}
            </a>
          ) : null}
          <br />
          <Row className="jhi-validated-blob-field-item-row">
            <Col md="11" className="jhi-validated-blob-field-item-row-col">
              <span>
                {blobContentType}, {byteSize(blob)}
              </span>
            </Col>
            <Col md="1" className="jhi-validated-blob-field-item-row-col jhi-validated-blob-field-item-clear-btn">
              {clearBtn ? clearBtn(clearBlob) : defaultClearBtn}
            </Col>
          </Row>
        </div>
      ) : null}
      {inputRow(input)}
    </>
  );
}

ValidatedBlobField.displayName = 'ValidatedBlobField';

const EMAIL_REGEXP = /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i;

export function isEmail(value) {
  if (isEmpty(value)) return true;

  return EMAIL_REGEXP.test(value);
}
`

**Comment by deepu105** [comment]
This is not supported and that's why the comment is there. What we provide is just convenient wrappers. If you want to nest children and stuff, I suggest you use the library directly. Supporting this in Jhipster directly is too much work and not worth the effort as you can easily do it using the library

**Comment by mokshinfotech** [comment]
> This is not supported and that's why the comment is there. What we provide is just convenient wrappers. If you want to nest children and stuff, I suggest you use the library directly. Supporting this in Jhipster directly is too much work and not worth the effort as you can easily do it using the library

Is it possible for someone to furnish an example of a compact entity and demonstrate its usage with JHipster? Alternatively, do we need to eliminate all the code generated by JHipster and create our own implementation using react-hook-form? It would be beneficial if we could utilize the code generated by JHipster to tackle the problem of nested child components. I have reviewed an example shared by emilpaw, but there are a couple of issues with it that need to be addressed.
