### ISSUE TITLE
Front: npm install too long with Vue applications

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#16810]
##### **Overview of the issue**

When generating Vue application, the npm install took too much time: 3min
Comparing to Angular which took 1min.
I didn't test with React

It would be cool to improve it

##### **Motivation for or Use Case**

Detected by @jdubois and I confirm this issue

##### **Reproduce the error**

- generate a Vue application
- see how long npm install can take...

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@pascalgrimaud is the npm taking too long yet?
We could stop providing some features like workbox by default.

**Comment by pascalgrimaud** [comment]
I didn't test it recently, so I'll test it tomorrow

**Comment by pascalgrimaud** [comment]
Before it took 3min on my machine.
Now, it's 2min, so it's better, thanks @mshima

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/59118.

**Comment by pascalgrimaud** [comment]
@mshima : approved
