### ISSUE TITLE
Dependency console log is shown before the generator options

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1682]
The npm install and bower install log in console should be at the end of the questions,not before it
![image](https://cloud.githubusercontent.com/assets/1107223/8507824/b7dfef20-2286-11e5-910d-58c877c08440.png)

@jdubois  do you see the same or is this a windows only issue?

**Comment by jdubois** [comment]
Yes same issue, since we migrated to Yeoman 0.20.1, which is asynchronous.
Not sure if there is an issue besides this message showing up at the wrong place.
Yes this should be audited.

**Comment by deepu105** [comment]
so far i diddn't notice any other glitch from the migration, I guess we can move this log to the location were we print oracle related thing when it is selected coz it seems to be printing at the end properly

**Comment by gzsombor** [comment]
I don't know if it's a bug, or a feature - or I've screwed up locally a bit, but since that migration, when I re-generate something, and yo asks for file overwrites, if I answer 'no' to any files, it asks it again in a second round. Is it intended ? :)

**Comment by deepu105** [comment]
I noticed that as well and thought it was some yeoman bug, for me during generation if i answer a question and if validation fails and re answer the question and answer gets printed multiple times and same happens sometimes for file overwrites as well. BUT ALL THESE DOESN'T CAUSE ANY ISSUES SO FAR

**Comment by jdubois** [comment]
@gzsombor @deepu105 this is another issue, and this is really annoying!!! I'm creating a new ticket for this, and this is my top priority -> we should have a 2.18.1 bug fixing release for this
However, I'm completely lost with this, so if anyone can help, he's more than welcome!
