### ISSUE TITLE
Create entity metrics doesn't appear with gatlin test 

### ISSUE THREAD

**Issue by warleyc** [jhipster/generator-jhipster#1684]
When I run the  gatlin test, the metrics for creating an entity doesn't appear in the metrics screen. but if I create an entity manually with the ui the metrics increment by one. 

I created a new jhipster app with the default  settings
I created a new Entity with one field :
yo jhipster:entity MyEntity

I launched the application

I Launch the gatlin test : 
mvn gatling:execute

Result with 200 entity created :

> Global                                                   (OK=1900   KO=0     )
> First unauthenticated request                            (OK=100    KO=0     )
> Authentication                                           (OK=100    KO=0     )
> Authenticated request                                    (OK=100    KO=0     )
> Get all myEntitys                                        (OK=200    KO=0     )
> Create new myEntity                                      (OK=200    KO=0     )
> Get created myEntity                                     (OK=1000   KO=0     )
> Delete created myEntity                                  (OK=200    KO=0     )

But when I checked the metrics on the web application, we have 0 creation! :
![screen shot 2015-07-05 at 6 47 45 am](https://cloud.githubusercontent.com/assets/616295/8509540/6eda0c2c-22e3-11e5-8eb5-8245ea2deb3f.png)

but when I created one entity with the UI, its fine:
![screen shot 2015-07-05 at 7 03 43 am](https://cloud.githubusercontent.com/assets/616295/8509550/0ca13570-22e4-11e5-8fb9-5584a8377aa0.png)

**Comment by jdubois** [comment]
You are correct, this is because we do a "put" and not a "post". This is something that changed in the UI recently, but I didn't change the Gatling test accordingly.
Anyway, I'm fixing this now.
