### ISSUE TITLE
Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by OAlQuaseer** [jhipster/generator-jhipster#1685]
Hey,
I am totally new to Jhipster and used it to generate my application but I am getting a problem in my pom file

 after getting everything generated by jhipster which is :- 

Plugin execution not covered by lifecycle configuration: com.github.trecloux:yeoman-maven-plugin:0.4:build (execution: run-grunt, phase: generate-resources)

<img width="1440" alt="screen shot 2015-07-05 at 2 02 54 pm" src="https://cloud.githubusercontent.com/assets/8602989/8512964/a177db92-231e-11e5-9e5d-2b281aec8ac0.png">

Then, after realizing that I have duplication in two plugins then I removed the first one and error was gone. However, I am not quite sure from what I did is right or wrong, was I right?.

The two duplicated plugins in my pom file are :-  
1-  
<img width="1440" alt="screen shot 2015-07-05 at 1 58 13 pm" src="https://cloud.githubusercontent.com/assets/8602989/8512949/fe3d60dc-231d-11e5-847e-792633942b90.png">

2- 
<img width="1440" alt="screen shot 2015-07-05 at 1 58 40 pm" src="https://cloud.githubusercontent.com/assets/8602989/8512952/123cef30-231e-11e5-96e9-37e2f86a316a.png">

Your help would be much appreciated if you give me some resolutions what to do.
Thanks

**Comment by jdubois** [comment]
Hi,
It's not really duplicated: it is configured twice, with two different profiles.
I'm not using Eclipse, but I didn't have reports of people having this type issue, maybe you use an old Eclipse version? Can you try with STS?
For me this is a tooling issue, not a JHipster issue -> that's why I'm closing this, but if other people have this issue, we will need to find some solution

**Comment by OAlQuaseer** [comment]
@jdubois Hi, 
I just used STS and the problem is still there. 
Thank you so much,

**Comment by jdubois** [comment]
@OAlQuaseer OK, I'm reopening it 
@michaelisvy do you have the same problem?

**Comment by OAlQuaseer** [comment]
@jdubois really appreciate your help regarding this problem.

**Comment by OAlQuaseer** [comment]
@Greenbudda FYI,
I think you have the same problem.

**Comment by michaelisvy** [comment]
Hi,
I've had that problem in the past. It was just Eclipse being inconsistent.
If I remember properly, here is what I've done:

- go on the command line and make sure that you use the same version of Maven as the one configured in Eclipse
- go inside your project's folder on the command like
- run 'mvn dependency:resolve'
- go back to Eclipse, right click on your project and do 'Maven -> update project'

Please let me know if that helps.

Cheers,
Michael.

**Comment by Greenbudda** [comment]
Yes, I have similar problem and I could not resolve the issue as you have suggested @michaelisvy.
I have removed 2 lines of code from yeoman-maven-plugin Version 0.4
<id>run-grunt</id>
<phase>generate-resources</phase> 
To make the app build and run. Will removing these lines cause an issue? Thanks a lot!

**Comment by OAlQuaseer** [comment]
@michaelisvy 
Hi Michael,

I ve done what you suggested to us but, unfortunately, I still have the problem. 

Really appreciate your efforts with us,
Omar.

**Comment by jdubois** [comment]
@michaelisvy is it the same issue as #1628 ? Or is it related?

**Comment by michaelisvy** [comment]
@jdubois yes this is definitely related. May be we should close this issue and redirect to #1628?

**Comment by oussamasic** [comment]
In my case of a similar problem, instead of using Andrew's suggestion for the fix, it worked simply after I introduced <pluginManagement> tag to the pom.xml in question. Looks like that error is due to a missing <pluginManagement> tag. So, in order to avoid the exceptions in Eclipse, one needs to simply enclose all the plugin tags inside a <pluginManagement> tag, like so:

```
<build>
    <pluginManagement>
        <plugins>
            <plugin> ... </plugin>
            <plugin> ... </plugin>
                  ....
        </plugins>
    </pluginManagement>
</build>
```

**Comment by oussamasic** [comment]
@OAlQuaseer
