### ISSUE TITLE
Adding spring-boot-starter-jersey causes NoSuchMethodError com.fasterxml.classmate.members.ResolvedField.getAnnotations()Lcom/fasterxml/classmate/Annotations;

### ISSUE THREAD

**Issue by kevinosullivan** [jhipster/generator-jhipster#1689]
I want to to start using Jersey for REST instead of Spring.  (First off - if using Jersey in jHipster is non-starter, let me know and I'll abandon attempts to integrate it in.)

I'm using JHipster v2.17.0.

I started by modifying my jhipster project to add this to the pom.xml

       <dependency>
           <groupId>org.springframework.boot</groupId>
           <artifactId>spring-boot-starter-jersey</artifactId>
       </dependency>

When I run 'mvn spring-boot:run' I get this exception:

```java.lang.NoSuchMethodError: com.fasterxml.classmate.members.ResolvedField.getAnnotations()Lcom/fasterxml/classmate/Annotations;```
	```at springfox.documentation.schema.property.OptimizedModelPropertiesProvider$2.apply(OptimizedModelPropertiesProvider.java:150) ~[springfox-schema-2.0.3.jar:2.0.3]```
	

This method appeared in v1.1.0 of fasterxml.classmate, and I can tell from running with mvn -X that the project is including v1.2.0 the classmate jar.   So I'm really confused.

**Comment by jdubois** [comment]
As we don't provide Jersey as part of our stack, we can't really help you here.
It looks like an issue with SpringFox, you could remove it -> then you won't have the SpringFox API available, but as you use Jersey I don't expect this to work at all anyway.
Migrating to Jersey will probably break up a lot of things, like this one.

You can ask this on StackOverflow, maybe?
