### ISSUE TITLE
OneToOne relationship DTO generation with String instead of id

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster#16892]
Hi all. I have a question.
When I generate an entity with oneToOne relationship using DTO, I note that the DTO does not contain the string key but the id of the entity.

Example:

```
OneToOne {
Tariff{name} to  LanguageSettings
}
```

The JPA entity maps correctly the name field, but the TariffDTO contains only the **Long nameId** (instead of String name).

Could I set an option to have that behaviour?

Thanks in advance.
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vicpermir** [comment]
Try this:
```
OneToOne {
   Tariff{langSettings(name)} to LanguageSettings
}
```
In my opinion, for this kind of questions, you should use [stackoverflow](https://stackoverflow.com/questions/tagged/jhipster).

**Comment by Tcharl** [comment]
Seems fixed by the recommendation of @vicpermir .
Feel free to reopen if needed
