### ISSUE TITLE
Guava version conflict between cassandra_unit and springfox

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1691]
The version of guava used by springfox makes cassandra_unit crash
Solution : exclude guava from springfox dependency or upgrade cassandra to v2.1

For exclusion :
```xml
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>${springfox.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>guava</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by jdubois** [comment]
Thanks @cbornet -> this means we should do a new release quickly (I didn't see this one!!)
We'll also need to exclude this in Gradle cc @atomfrede 
-> If you have time to do the PR I'll merge it, otherwise I'll work on this tonight

**Comment by atomfrede** [comment]
Will do it today, no big deal.

**Comment by atomfrede** [comment]
@jdubois Excluding guava still required?

**Comment by jdubois** [comment]
@atomfrede no I upgraded to Cassandra 2.1.7 it solves the issue!

**Comment by atomfrede** [comment]
:+1:
