### ISSUE TITLE
The Compose file './docker-compose.yml' is invalid

### ISSUE THREAD

**Issue by indiepopart** [jhipster/generator-jhipster#16920]
##### **Overview of the issue**

Generated docker-compose.yml does not have a version.
```
➜  docker-compose docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'gateway'
```

##### **Motivation for or Use Case**

Compose file documentation says:
```
Version 1. This is specified by omitting a version key at the root of the YAML.
```

##### **Reproduce the error**

```
jhipster jdl blog-reactive-ms.jdl
cd docker-compose
docker-compose up
```

##### **JHipster Version(s)**

```
➜  jhipster4 jhipster --version
INFO! Using JHipster version installed globally
7.3.1
```
```
➜  jhipster4 docker-compose version
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
```
➜  jhipster4 node --version
v14.18.1
```

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    baseName gateway
    reactive true
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    buildTool maven
    clientFramework vue
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag
}
application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    buildTool maven
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType eureka
    searchEngine elasticsearch
  }
  entities Blog, Post, Tag
  service * with serviceClass
  search * with elasticsearch
}
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}
paginate Post, Tag with infinite-scroll
microservice Blog, Post, Tag with blog
deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog]
  dockerRepositoryName "jgarbarino"
}
  </pre>
  </details>

##### **Browsers and Operating System**

OS: Ubuntu 16.04.7 LTS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I'm not able to reproduce this. It works for me! 

OK, it doesn't _really_ work, but I don't get the same error either:

```
$ docker-compose up
[+] Running 0/6
 ⠿ jhipster-registry Error                                                                                        15.2s
 ⠿ blog-elasticsearch Error                                                                                       15.2s
 ⠿ blog Error                                                                                                     15.2s
 ⠿ keycloak Error                                                                                                 15.2s
 ⠿ blog-mongodb Error                                                                                             15.2s
 ⠿ gateway-postgresql Error                                                                                       15.2s
Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded
```

What version of Docker are you using? My versions:

```
$ docker --version
Docker version 20.10.8, build 3967b7d
$ docker-compose --version
Docker Compose version v2.0.0
```

**Comment by indiepopart** [comment]
I was using Docker version 19.
I updated to the following versions and the error does not happen:

```
➜  docker-compose docker --version
Docker version 20.10.7, build f0df350
➜  docker-compose docker-compose --version
Docker Compose version v2.0.1
```

**Comment by DanielFran** [comment]
Thanks, @indiepopart, for the feedback.
I suppose the issue can be closed?

**Comment by indiepopart** [comment]
It seems Docker Compose V1 is being deprecated soon. So I assume it can be closed.
