### ISSUE TITLE
Feedback/Feature Request: Code removal based on environment? (removeIf, remove code)

### ISSUE THREAD

**Issue by silentHoo** [jhipster/generator-jhipster#1693]
jHipster is great. But I'm missing a somewhat convenient way to remove frontend code based on the current environment. My local projects have a custom task to build dev, test or prod output, where some code is removed before it is written to the disk (I've a `/dist` folder where I serve from). This code contains some actions I won't do when I'm on development like login actions.

I would like to hear some feedback from the community if this is a feature that's worth integrating it in jHipster?

There are some projects in the wild which integrate that task in gulp/grunt:

* https://www.npmjs.com/package/gulp-remove-code
* https://www.npmjs.com/package/gulp-strip-code
* https://www.npmjs.com/package/grunt-strip-code

**Comment by andidev** [comment]
You could use the Angular constant ENV with contains the environment
```html
<div ng-show="{{ENV === 'dev'}}">this is only displayed in den environment </div>
```

**Comment by jdubois** [comment]
Yes I agree with @andidev we already do this. Otherwise, this is a rather specific use case, and I don't think we would add much value, so I don't think we should do this.
