### ISSUE TITLE
Jhipster integration Angular Universal for prerender

### ISSUE THREAD

**Issue by tanjie123** [jhipster/generator-jhipster#16945]
##### **Overview of the feature request**

Compared with SSR, SPA application is not conducive to search engine crawlers. In order to improve the chances of the website being retrieved by search engines, we can implement pre-rendering features based on prerender.io .

##### **Motivation for or Use Case**

Most web applications hope to be retrieved by web crawlers。

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/7999

**Comment by deepu105** [comment]
We already have too many features and I don't think there is bandwidth for doing SSR as well
