### ISSUE TITLE
Sonar Analysis of JHipster + Auth0 example shows two bugs

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16943]
##### **Overview of the issue**

I ran Sonar on my [JHipster + Auth0 example](https://github.com/oktadev/auth0-full-stack-java-example) today and discovered that Sonar reports two bugs. 

Screenshots:

<img width="1299" alt="Screen Shot 2021-11-08 at 1 45 30 PM" src="https://user-images.githubusercontent.com/17892/140816166-b8e1a68a-989a-47de-a43b-f7ead301f42f.png">
<img width="1311" alt="Screen Shot 2021-11-08 at 1 46 10 PM" src="https://user-images.githubusercontent.com/17892/140816170-ffc8d583-1074-4fe7-902e-0a9905544f7a.png">
<img width="1304" alt="Screen Shot 2021-11-08 at 1 46 23 PM" src="https://user-images.githubusercontent.com/17892/140816179-2f0e560f-8a4f-45c6-82d9-18abf7c9cdd0.png">

##### **Motivation for or Use Case**

Ideally, there should be 0 bugs.

##### **Reproduce the error**

```
git clone https://github.com/oktadev/auth0-full-stack-java-example
cd auth0-full-stack-java-example
docker-compose -f src/main/docker/sonar.yml up -d
./mvnw -Pprod verify sonar:sonar -Dsonar.host.url=http://localhost:9001
```

##### **JHipster Version(s)**

```
flickr-2@0.0.1-SNAPSHOT /Users/mraible/dev/auth0-full-stack-java-example
└── generator-jhipster@7.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "flickr2",
    "jhipsterVersion": "7.3.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1634022348068,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.auth0.flickr2",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "united",
    "clientThemeVariant": "dark",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "pt-br"],
    "enableGradleEnterprise": false,
    "entities": ["Album", "Photo", "Tag"],
    "lastLiquibaseTimestamp": 1634025089000,
    "herokuAppName": "flickr-2",
    "herokuDeployType": "git",
    "herokuJavaVersion": "11",
    "useOkta": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Album {
  title String required
  description TextBlob
  created Instant
}
entity Photo {
  title String required
  description TextBlob
  image ImageBlob required
  height Integer
  width Integer
  taken Instant
  uploaded Instant
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Album{user(login)} to User
  Photo{album(title)} to Album
}
relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.30.1 (Apple Git-130)

node: v14.18.1

npm: 8.1.2

Docker version 20.10.8, build 3967b7d

Docker Compose version v2.0.0

Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

**Comment by qmonmert** [comment]
@pascalgrimaud or @mraible can you confirm me that this is ok with sonar ? :)

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/55137

**Comment by pascalgrimaud** [comment]
@qmonmert : approved :-)

**Comment by qmonmert** [comment]
@pascalgrimaud merci
