### ISSUE TITLE
Import JDL fails

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#16973]
##### **Overview of the issue**

When running import-jdl with a JDL containing more than 1 application, there are errors and the process doesn't generate everything, either apps or deployment is missing. The below is the error in the log

```
ERROR! Callback called multiple timesuct: sill idealTree buildDeps
Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple timesetch manifest supports-color@8.1.1
    at NodeError (node:internal/errors:371:5)
    at onFinish (node:internal/streams/writable:667:37)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7) {
  code: 'ERR_MULTIPLE_CALLBACK'
}
INFO! Generator app child process exited with code 1a: sill fetch manifest supports-color@8.1.1
ERROR! Error executing app --reproducible --no-force --with-entities --no-dry-run --no-whitespace --no-bail --no-install-path --no-skip-regenerate --no-skip-yo-resolve --from-jdl --no-skip-cache --no-skip-install --no-force-install --no-ask-answered --no-defaults --no-skip-git
Error: Error executing app --reproducible --no-force --with-entities --no-dry-run --no-whitespace --no-bail --no-install-path --no-skip-regenerate --no-skip-yo-resolve --from-jdl --no-skip-cache --no-skip-install --no-force-install --no-ask-answered --no-defaults --no-skip-git
    at ChildProcess.<anonymous> (/home/deepu/.npm-global/lib/node_modules/generator-jhipster/cli/import-jdl.js:194:16)

```

##### **Motivation for or Use Case**

import-jdl should work

##### **Reproduce the error**

run `jhipster jdl` for the JDL file here https://gist.github.com/deepu105/1f0663af2acdb67dd5472c4896b595cf

##### **JHipster Version(s)**

7.3.1 and main branch

##### **Browsers and Operating System**

Fedora 35
Node: v16.11.1
NPM: 8.0.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Should be fixed by https://github.com/jhipster/generator-jhipster/pull/16930.
Related to https://github.com/jhipster/generator-jhipster/issues/16744.

**Comment by deepu105** [comment]
Yup seems like I was stuck at a previous node version. works with 16.13.0
