### ISSUE TITLE
Update and fix the Istio configurations

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#16985]
Seems like the Istio setup is broken and outdated for the latest Istio version(1.11). Need to be updated with the latest specs and routing needs to be fixed

**Comment by deepu105** [comment]
It seems like I'm stuck again with the same problem I reported many months ago in https://github.com/jhipster/generator-jhipster/issues/14479 The problem seems to be a combination of Spring cloud gateway and Istio which both does the same thing. I'm gonna try and disable Spring Cloud gateway and see if that works

**Comment by deepu105** [comment]
@jhipster/developers did anyone try this combo?

**Comment by mraible** [comment]
I haven't used Istio in any of my examples recently.

**Comment by deepu105** [comment]
Ya I have been trying different things to see what goes wrong, It works if I switch to Zull instead of Spring Cloud Gateway. There is n't much on the web on this combination and I'm honestly stuck as I'm not familiar with Spring Cloud

**Comment by pascalgrimaud** [comment]
We have 0 feedback from our final users, so I'm not sure it's an option which is used in real production
Is it important to keep and maintain this option?

**Comment by deepu105** [comment]
Ya probably we should remove Istio support as it seems I'm the only one using it

**Comment by deepu105** [comment]
I can also just extract it into a blueprint, but it would still not work with the default gateway

**Comment by Tcharl** [comment]
Hi @deepu105 ,

I plan to try an jhipster istio microservice stack in the next few monthes for personnal project, I also bought the book (not read yet) and really want to try.
The blueprint won't be a problem, but removing something that is really hard to setup would be terrible (even if it has to be pimped a little bit to work).
Once I'll have my kube up and running, I'll be able to maintain that code too...

**Comment by deepu105** [comment]
In a way a blueprint might be better since Spring Cloud Gateway provides similar features as Istio so for an Istio setup we don't need Sping cloud gateway and Zuul might be enough (even better IMO) so maybe we should Just move the Istio files to a blueprint and create a Zuul based gateway instead. After spending a day on this I'm honestly leaning towards just using Zuul

**Comment by deepu105** [comment]
Today I'm gonna give this another shot, this time trying to make it work without SCG and purely with Istio

**Comment by deepu105** [comment]
Damn it took me forever but I think I fixed it, seems like we need to rewrite the URLs on istio side as well, and technically SCG can be removed and it would still work fine, but also works with it

**Comment by Tcharl** [comment]
Who said code was kubernetes agnostic?
