### ISSUE TITLE
Unhandled exception causes error in tests and ui. Drop unhandled exception from cypress and fix jest tests in node 16.

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16982]
##### **Overview of the issue**

I created a photo album example as part of [this blog post](https://auth0.com/blog/full-stack-java-with-react-spring-boot-and-jhipster/). Today, I noticed that if you add an album, then add a photo to that album, it fails. The error in the console is:

```
Uncaught (in promise) TypeError: e.album is undefined
```

If I delete all albums and then add a photo, it works.

##### **Motivation for or Use Case**

It should be possible to add a parent entity and its children.

##### **Reproduce the error**

Clone the repo, run it, add an album, then add a photo to it:

```
git clone https://github.com/oktadev/auth0-full-stack-java-example.git example
cd example
jhkeycloakup
./mvnw
```

##### **JHipster Version(s)**

```
flickr-2@0.0.1-SNAPSHOT /Users/mraible/dev/mobile-jhipster/backend
└── generator-jhipster@7.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "flickr2",
    "jhipsterVersion": "7.3.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1634022348068,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.auth0.flickr2",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "united",
    "clientThemeVariant": "dark",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "pt-br"],
    "enableGradleEnterprise": false,
    "entities": ["Album", "Photo", "Tag"],
    "lastLiquibaseTimestamp": 1634025089000,
    "herokuAppName": "flickr-2",
    "herokuDeployType": "git",
    "herokuJavaVersion": "11",
    "useOkta": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Album {
  title String required
  description TextBlob
  created Instant
}
entity Photo {
  title String required
  description TextBlob
  image ImageBlob required
  height Integer
  width Integer
  taken Instant
  uploaded Instant
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Album{user(login)} to User
  Photo{album(title)} to Album
}
relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.30.1 (Apple Git-130)

node: v14.18.1

npm: 8.1.2

Docker version 20.10.8, build 3967b7d

Docker Compose version v2.0.0

**Comment by mshima** [comment]
@mraible is this related to the merged bootstrap5?

**Comment by mraible** [comment]
No, I don't think so because this app was created with v7.3.1.

**Comment by qmonmert** [comment]
@mraible I created a React App with your JDL and I don't reproduce the bug 😕

**Comment by mshima** [comment]
@mraible can we convert this issue to fix unhandled exceptions instead?
Drop react from
https://github.com/jhipster/generator-jhipster/blob/cc5fcdd73fed569276dd17cba0db0bb40a57a991/generators/cypress/templates/src/test/javascript/cypress/support/index.ts.ejs#L49-L57
And make react tests to pass at node 16.
