### ISSUE TITLE
getUser() is undefined for type ...

### ISSUE THREAD

**Issue by crowne** [jhipster/generator-jhipster#17001]
##### **Overview of the issue**

This bug results in a compilation error.
If a ManyToOne relationship is defined in jdl as follows:

```
relationship ManyToOne {
    Roster{changedBy(login)} to User
}
```
The Roster domain class is generated as expected with a member variable : User changedBy

However the RestController RosterResource contains the following generated code which does not compile:
```
        if (roster.getUser() != null) {
            // Save user in case it's new and only exists in gateway
            userRepository.save(roster.getUser());
        }
```

##### **Motivation for or Use Case**

This is a bug because the generated app does not compile.

##### **Reproduce the error**

Sample jdl file below:

```
// To generate : jhipster import-jdl --skip-check-length-of-identifier model.jdl  

// application {
//   config {
//     baseName portal
//     applicationType gateway
//     packageName com.jhipster.demo.portal
//     authenticationType oauth2
//     databaseType no
//     devDatabaseType no
//     prodDatabaseType no
//     clientFramework vue
//   }
//   entities *
// }

application {
  config {
    baseName hr
    applicationType microservice
    packageName com.jhipster.demo.hr
    authenticationType oauth2
    databaseType sql
    devDatabaseType h2Disk
    prodDatabaseType oracle
  }
  entities Department, Employee, Roster
}

enum ShiftType {
    EARLY_SHIFT, LATE_SHIFT
}

entity Department {
    name String required
}

entity Employee {
    firstName String
    surname String
    startDate LocalDate
}

entity Roster {
    fromDate LocalDate
    thruDate LocalDate
    shiftType ShiftType
    changedAt Instant
}

relationship OneToOne {
    Employee{user(login)} to User
}

relationship ManyToOne {
    Employee{department(name) required} to Department
    Roster{department(name)} to Department
    Roster{changedBy(login)} to User
}

service * with serviceClass
paginate * with pagination

```

##### **Related issues**

None found

##### **Suggest a Fix**

The RestController generator should be changed to refer to the named relationship.
i.e. `getChangedBy` instead of `getUser`
```
        if (roster.getChangedBy() != null) {
            // Save user in case it's new and only exists in gateway
            userRepository.save(roster.getChangedBy());
        }
```

##### **JHipster Version(s)**

7.3.1

##### **JHipster configuration**

→ E:\mjh\jh\jh-user-rel [master]› jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
hr@0.0.0 E:\mjh\jh\jh-user-rel
└── generator-jhipster@7.3.1  

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "serverPort": "8081",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "baseName": "hr",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "enableGradleEnterprise": false,
    "gradleEnterpriseHost": "",
    "applicationType": "microservice",
    "packageName": "com.jhipster.demo.hr",
    "packageFolder": "com/jhipster/demo/hr",
    "jhipsterVersion": "7.3.1",
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "applicationIndex": 0,
    "entities": ["Department", "Employee", "Roster"],
    "skipCheckLengthOfIdentifier": true,
    "skipServer": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": false,
    "nativeLanguage": "en",
    "creationTimestamp": 1636733398586,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "lastLiquibaseTimestamp": 1636733578000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Department {
  name String required
}
entity Employee {
  firstName String
  surname String
  startDate LocalDate
}
entity Roster {
  fromDate LocalDate
  thruDate LocalDate
  shiftType ShiftType
  changedAt Instant
}
enum ShiftType {
  EARLY_SHIFT,
  LATE_SHIFT
}

relationship OneToOne {
  Employee{user(login)} to User
}
relationship ManyToOne {
  Employee{department(name) required} to Department
  Roster{department(name)} to Department
  Roster{changedBy(login)} to User
}

paginate Department, Employee, Roster with pagination
service Department, Employee, Roster with serviceClass
microservice Department, Employee, Roster with hr
clientRootFolder Department, Employee, Roster with hr

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

git version 2.31.1.windows.1

node: v14.18.0

npm: 8.0.0

Docker version 20.10.8, build 3967b7d

Docker Compose version v2.0.0

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Browsers and Operating System**

Windows 10 Pro + Chrome
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by crowne** [comment]
As a work-around to this problem, if I change the relationship to `Employee` instead of `User` 
then the code is generated differently (more simply), 
and the compilation error does not occur.

```
relationship OneToOne {
    Employee{user(login)} to User
}

relationship ManyToOne {
    Employee{department(name) required} to Department
    Roster{department(name)} to Department
    Roster{changedBy(login)} to Employee
    // Roster{changedBy(login)} to User
}
```

**Comment by vicpermir** [comment]
The problem seems to be in:

https://github.com/jhipster/generator-jhipster/blob/0115869878f7fe667853fdb2ad339738093fee45/generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs#L180-L189

Same problem in lines L249-L257 and lines L312-L320

The method names `getUser()` and `getUsers()` are both hardwired and don't contemplate a different relationship name. Is this by design?

I wouldn't mind doing a PR to fix this with a little help from a more experienced contributor. How do I get the relationship name?

**Comment by mshima** [comment]
@vicpermir would be great if you could create the PR.

Should be something like:
```
<% for (const userRelationship of relationships.filter(relationship => relationships.otherEntity.builtInUser) { %>
 <%_ if (userRelationship.collection) { _%> 
     if (<%= instanceName %>.get<%= userRelationship.relationshipNameUpperCase %>() != null) { 
         // Save users in case they are new and only exists in gateway 
         userRepository.saveAll(<%= instanceName %>.get<%= userRelationship.relationshipNameUpperCase %>()); 
     } 
 <%_ } else { _%> 
     if (<%= instanceName %>.get<%= userRelationship.relationshipName %>() != null) { 
         // Save user in case it's new and only exists in gateway 
         userRepository.save(<%= instanceName %>.get<%= userRelationship.relationshipName %>()); 
     } 
 <%_ } _%>
<% } %>
```

**Comment by vicpermir** [comment]
Had to make a few changes due to method capitalization and plurals, generated a few projects with these changes and all worked fine.

Let me know if I did anything wrong.
