### ISSUE TITLE
why isn't index.html cached by the browser ?

### ISSUE THREAD

**Issue by kbjp** [jhipster/generator-jhipster#1700]
Hi,
Could someone explain me why index.html isn't cached by client browsers when running the application under the production profile ? (I use stand-alone tomcat8 as web-server and IE11/Chrome43 for my browsers) Obviously the fact that index.html isn't cached by the client browsers is good (otherwise that would lead to browser-cache issues during an application upgrade) but I just don't understand why my browsers behave that way without any meta data in the header...Is no-caching the default for HTML5 ?
Regards
kbjp

**Comment by gmarziou** [comment]
Look at mappings in the WebConfigurer.initCachingHttpHeadersFilter()

**Comment by kbjp** [comment]
Yes, I'm already aware of the CachingHttpHeadersFilter but since there's no specific caching instructions for index.html itself, I was expecting that, without any meta-headers in the page itself, it would be, by default, indefinitely cached by the browser (at least I believe that this was the default behavior before HTML5), unless you put a few extra meta headers like like "expires = 0", "pragma = no-cache" and "cache-control=max-age=0" but it looks like those meta tags are now invalid under HTML5. Which leads me back to my initial question: is the default behavior of HTML5 to avoid caching an HTML page in the browser unless told otherwise or did I miss something in the Jhipster code itself preventing the caching ?
Thank you very much in advance for your feedback.
Regards
kbjp

**Comment by gmarziou** [comment]
Have you looked at the response headers in browser console? I don't think it's related to HTML5, I rather think it's an IE11 thing.

**Comment by kbjp** [comment]
yes, I've already looked in the response headers for Chrome43 and IE11 but I haven't found anything preventing the browser from caching the page...so I'm happy that the page is not cached (that's the behavior I want) but I don't understand why it behaves that way.

**Comment by jdubois** [comment]
We don't do anything to cache the page, so I guess that's normal it's not cached.
And as you have written, this is for a perfectly normal reason: this page shouldn't be cached, as it might change. It doesn't have a checksum in its URL, like the CSS or JS files, and it's logical: it's the entry point to everything.
Then, this page is very small and very fast to send, this is nothing compared to the rest of your application (the JS is much much bigger, any call to the database will eat a lot more resources, etc etc). And we just need to have an entry point, we can't do anything about it.
