### ISSUE TITLE
UncategorizedElasticsearchException Please use a keyword field instead. Alternatively, set fielddata=true 

### ISSUE THREAD

**Issue by indiepopart** [jhipster/generator-jhipster#17018]
##### **Overview of the issue**

Search for entities that had `paginate` in the JDL fail with the following exception:

```
docker-compose-blog-1                | 2021-11-15 23:26:03.237 ERROR 1 --- [or-http-epoll-2] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
docker-compose-blog-1                | 
docker-compose-blog-1                | org.springframework.data.elasticsearch.UncategorizedElasticsearchException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed], Elasticsearch exception [type=illegal_argument_exception, reason=Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.]; nested exception is ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed], Elasticsearch exception [type=illegal_argument_exception, reason=Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.]]; nested: ElasticsearchException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.]];
``` 

##### **Motivation for or Use Case**

Search queries sent to elasticsearch are not using the keyword field.
The issue seems related to fielddata not enabled in the text fieldslacsearch. Text fields are not available for sorting by default. The recommended way is to use multi-field mapping, and a have the keyword field for sorting. I see the multi-field mapping is present in the generated index mapping. But the query sent to elasticsearch is not using the keyword field and fielddata is not enabled.
Original query gives error:
http://localhost:8080/services/blog/api/_search/posts?query=animal&sort=id,asc&page=0&size=20
Keyword query that works:
http://localhost:8080/services/blog/api/_search/posts?query=animal&sort=id.keyword,asc&page=0&size=20

##### **Reproduce the error**

```shell
jhipster jdl blog-reactive-ms.jdl
cd gateway
./mvnw -ntp -Pprod verify jib:dockerBuild
cd ../blog
./mvnw -ntp -Pprod verify jib:dockerBuild
cd ../docker-compose
docker compose up
```
1. Go to localhost:8080, sign in
2. Go to entities -> tag
3. Create a tag
4. Search for a tag ->  Internal Server Error

##### **Related issues**

Seems related to #16210 

##### **JHipster Version(s)**

```
➜  docker-compose jhipster --version                       
INFO! Using JHipster version installed globally
7.3.1
 ```

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    baseName gateway
    reactive true
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    buildTool maven
    clientFramework vue
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag
}
application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    buildTool maven
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType eureka
    searchEngine elasticsearch
  }
  entities Blog, Post, Tag
  service * with serviceClass
  search * with elasticsearch
}
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}
paginate Post, Tag with infinite-scroll
microservice Blog, Post, Tag with blog
deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog]
  dockerRepositoryName "jgarbarino"
}

  </pre>
  </details>

##### **Browsers and Operating System**

OS: Ubuntu 18.04.6 LTS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Added bug bounty in hopes of getting this fixed soon.
