### ISSUE TITLE
Send ContentSecurityPolicy (CSP) header only if client is generated?

### ISSUE THREAD

**Issue by nickshoe** [jhipster/generator-jhipster#17035]
When using JHipster for backend-only development, or when splitting frontend and backend, the CSP header sent by Spring makes no sense. 
[Policy Delivery](https://www.w3.org/TR/CSP2/#policy-delivery) seems to make sense only for html apps running in the browser; in fact, another way to specify CSP is by setting an HTML `meta` element (as defined [here](https://www.w3.org/TR/CSP2/#delivery-html-meta-element)).

It should be the web tier serving the frontend application (web server, load balancer, reverse proxy, etc...) to deliver this header.

> ... the CSP is rather static and can be delivered from [web application tiers](https://en.wikipedia.org/wiki/Multitier_architecture) above the application, for example on [load balancer](https://en.wikipedia.org/wiki/Load_balancer) or [web server](https://en.wikipedia.org/wiki/Web_server).
> 
> &mdash; [Wikipedia](https://en.wikipedia.org/wiki/Content_Security_Policy)

The CSP header is set in the following line of code, during the App bootstrap:

https://github.com/jhipster/generator-jhipster/blob/b8c76e52cb8377158d9a0b32c44796b7a4555b8e/generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs#L232

The value is read from the `application.yml` file:

https://github.com/jhipster/generator-jhipster/blob/91b29f57589a5b060ebeacd429361dfd924127a4/generators/server/templates/src/main/resources/config/application.yml.ejs#L333-L337

N.B.: The fact that the CSP header content depends on the client option of using a theme could be an indication that this aspect is a frontend-only matter.

**Propose a fix**: I would get rid of the CSP header set + config property altogether in the case where the client is not generated.

**Comment by nickshoe** [comment]
We could add instructions for setting the CSP header when separating the front-end and the API server, since the front-end will be served by a different HTTP server (nginx, Apache, ...) that would normally not address CSP.

**Comment by atomfrede** [comment]
It sound promising to have it in the html meta part. But I guess we loose the configuration via properties, while the question is if that is really needed.

**Comment by nickshoe** [comment]
@atomfrede I propose to leave the CSP configuration as it is right now (properties + `SecurityConfiguration` class), but to only generate the related code when the user wants the client to be generated.

**Comment by DanielFran** [comment]
@nickshoe Are you available to contribute with a PR?

**Comment by nickshoe** [comment]
Hey @DanielFran, sure.
I'll do a PR as soon as I can.

**Comment by nickshoe** [comment]
@DanielFran PR opened.

Please note that I've also ruled out the "Referrer-Policy", "Permission-Policy" and "X-Frame-Options" headers along with the "Content-Security-Policy" header, because they're all related to the client being served by the embedded http server in the Spring-Boot backend.
