### ISSUE TITLE
Style sheet file not show

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#1704]
In the index.html file, a style sheet line is pointed to assets/styles/main.css. I can't find the main.css file under the directory. To verify this problem is not related with Gradle, I create another project with  Maven and the rest is the same.

**Comment by gmarziou** [comment]
Did you select Compass/SASS?

**Comment by gmarziou** [comment]
I just generated a new project with 2.18.0 and without Compass/SASS and main.css exists.

**Comment by vw98075** [comment]
I think I did

**Comment by gmarziou** [comment]
If you use SASS, try running grunt serve or gulp serve, it should build it

**Comment by gmarziou** [comment]
if you don't remember your options, just copy/paste here the content of .yo-rc.json at the root of your projet

**Comment by gmarziou** [comment]
Works also with Compass/SASS.

You should use Compass if it makes sense for you and if you have it and Ruby installedas explained in the doc.

**Comment by vw98075** [comment]
I know I selected Compass for the project. After running "grunt serve" at the root directory of my project, I still don't see the main.css file under assets/style/main.css.

**Comment by gmarziou** [comment]
What does 'compass -v' print?

**Comment by vw98075** [comment]
It says the compass isn't recognized. I guess that I shall not use it.

**Comment by gmarziou** [comment]
Or you read [the doc](http://jhipster.github.io/installation.html) and install it.

**Comment by gmarziou** [comment]
In any case, I think you can close this issue now.

**Comment by vw98075** [comment]
Sure. Thanks much for your helps.
