### ISSUE TITLE
How to deal with geometry types?

### ISSUE THREAD

**Issue by seainside75** [jhipster/generator-jhipster#1705]
Hello, 

I'm trying to use Jhipster(very nice tool)  with a PostGIS DB.
Do I need to extend the available types?
Is there any other possibility?

Thanks in advance

**Comment by thiagogcm** [comment]
I've done this before

with hibernate-spatial and a custom GeoJson unmarsheller like this one https://github.com/bedatadriven/jackson-datatype-jts

**Comment by seainside75** [comment]
Thanks a lot. I will take a look to your URL

**Comment by jdubois** [comment]
@seainside75 I think this belongs more to StackOverflow, as we are not going to support this.
However, I'm interested in your findings, as this is exactly what I'm doing in my current gig (but we use Python+Flask, not JHipster!)
