### ISSUE TITLE
Issue with Generating ADMIN UI

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#17066]
##### **Overview of the issue**

Tried creating the application with admin UI, it failed to create the whole project. 

```bash
 create src/main/webapp/app/admin/docs/docs.component.ts
   create src/main/webapp/app/admin/docs/docs.component.html
   create src/main/webapp/app/admin/docs/docs.component.scss
   create src/main/webapp/app/admin/configuration/configuration.route.ts
   create src/main/webapp/app/admin/configuration/configuration.module.ts
   create src/main/webapp/app/admin/configuration/configuration.component.ts
ERROR! Callback called multiple times
Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
    at NodeError (node:internal/errors:371:5)
    at onFinish (node:internal/streams/writable:667:37)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7) {
  code: 'ERR_MULTIPLE_CALLBACK'
}

```

##### **Reproduce the error**

Select the following while creating the project. 

```bash
Do you want to generate the admin UI? Yes
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "smp",
    "jhipsterVersion": "7.3.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1637336846678,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.smp.app",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "enableGradleEnterprise": false,
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

git version 2.30.1 (Apple Git-130)

node: v16.13.0

npm: 8.1.0

Docker version 20.10.8, build 3967b7d

##### **JHipster Version(s)**

```
jhipster --version
INFO! Using JHipster version installed locally in current project's node_modules
7.3.1
```

**Comment by mshima** [comment]
Fixed in 7.4.0.
