### ISSUE TITLE
Replace react-infinite-scroller.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#17064]
##### **Overview of the feature request**

react-infinite-scroller is more than 3 years without a new release, and don't have official react@17 support.
We should replace it with another module. Maybe react-infinite-scroll-component.
And finally drop legacy-peer-deps.

##### **Motivation for or Use Case**

Replace not supported module.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
I'm on it!

**Comment by qmonmert** [comment]
@pascalgrimaud I claim my bounty :) https://opencollective.com/generator-jhipster/expenses/56160

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
