### ISSUE TITLE
font path in minified css has wrong path (?) when app not deployed in web server root

### ISSUE THREAD

**Issue by kbjp** [jhipster/generator-jhipster#1706]
Dear Jhipster team,

My apologies in advance if this is a false alert but i think there may be a problem with the minified css when the application is not deployed in the web server root: I'm getting HTTP 404 errors with file paths like: 
http://localhost:8080/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff 
while the proper file path should be more like:
http://localhost:8080/MYAPPNAME/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
(of course the glyphicons are not properly displayed in the browser)
I'm using tomcat8 stand-alone (application context = http://MYAPPNAME) and IE11/Chrome43 for my browser. Application built with Jhipster 2.16.
Haven't found a solution to this issue yet (not a grunt expert). 
Regards
kbjp

**Comment by interstellerS** [comment]
It may be related to this https://github.com/jhipster/generator-jhipster/issues/1704#issuecomment-119753555 .

**Comment by atomfrede** [comment]
It was fixed in #1555 which was released in ``2.17``. So try the latest version.

**Comment by jdubois** [comment]
Yes I think @atomfrede is right
Thanks @kbjp for writing the version number! Most people forget to do it!

**Comment by kbjp** [comment]
awesome ! thanks a lot for the feedback...saving me many hours !
kbjp
