### ISSUE TITLE
vue "jhipster entity" 7.4.0 not showing

### ISSUE THREAD

**Issue by pkral3** [jhipster/generator-jhipster#17075]
##### **Overview of the issue**
jhipster 7.4.0 vue
jhipster entity book
the book is not showing in web

##### **JHipster Version(s)**
7.4.0

##### **JHipster configuration**
Run with Vue: jhipster ; jhipster entity book

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I confirm the issue.
The component, service, model are correctly generated, but nothing about router, navbar menu etc.

**Comment by pascalgrimaud** [comment]
additional information:
- it works well with JDL
- it is broken with CLI: jhipster entity
