### ISSUE TITLE
`jhipster upgrade` doesn't work from 7.3.1 to 7.4.0

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#17072]
##### **Overview of the issue**

```
✔ Committed with message "Generated with JHipster 7.4.0"
git checkout -q main -f
✔ Checked out branch "main"
Merging changes back to main...
git merge -q jhipster_upgrade
Auto-merging src/main/webapp/app/entities/photo/photo.tsx
CONFLICT (content): Merge conflict in src/main/webapp/app/entities/photo/photo.tsx
Auto-merging pom.xml
Auto-merging package.json
CONFLICT (content): Merge conflict in package.json
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.
✔ Merge done!
git diff --name-only --diff-filter=U package.json
package.json
WARNING! There are conflicts in package.json, please fix them and then run npm install
ERROR! Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at patternSpy.dot (/usr/local/lib/node_modules/generator-jhipster/generators/generator-transforms.js:64:12)
    at async PTransform.transform [as _transform] (/usr/local/lib/node_modules/generator-jhipster/node_modules/p-transform/index.js:127:7)
    at async PTransform.queuedTransform (/usr/local/lib/node_modules/generator-jhipster/node_modules/p-transform/index.js:88:26)
    at async run (/usr/local/lib/node_modules/generator-jhipster/node_modules/p-queue/dist/index.js:163:29)
Execution time: 1 min. 57 s.
```

##### **Motivation for or Use Case**

I was hoping to use this command to update a recent application I created. 

##### **Reproduce the error**

```
git clone https://github.com/oktadev/auth0-full-stack-java-example app
cd app
npm i
npm i -g generator-jhipster@7.4.0
jhipster upgrade
```

##### **Related issues**

No

##### **JHipster Version(s)**

7.4.0 &&

```
flickr-2@0.0.1-SNAPSHOT /Users/mraible/dev/auth0-full-stack-java-example
└── generator-jhipster@7.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "flickr2",
    "jhipsterVersion": "7.3.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1634022348068,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.auth0.flickr2",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "united",
    "clientThemeVariant": "dark",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "pt-br"],
    "enableGradleEnterprise": false,
    "entities": ["Album", "Photo", "Tag"],
    "lastLiquibaseTimestamp": 1634025089000,
    "herokuAppName": "flickr-2",
    "herokuDeployType": "git",
    "herokuJavaVersion": "11",
    "useOkta": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Album {
  title String required
  description TextBlob
  created Instant
}
entity Photo {
  title String required
  description TextBlob
  image ImageBlob required
  height Integer
  width Integer
  taken Instant
  uploaded Instant
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Album{user(login)} to User
  Photo{album(title)} to Album
}
relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.30.1 (Apple Git-130)

node: v14.18.1

npm: 8.1.2

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

**Comment by mshima** [comment]
Will take a look soon.

**Comment by pascalgrimaud** [comment]
@mraible : does this command work for you ? I tested it several times in real projects for several customers and it never works for me.

**Comment by mraible** [comment]
It hasn't worked in a while, but it sure is cool when it does!

**Comment by pascalgrimaud** [comment]
I'll try to give more details the next time I tried, but I need to be carefull to not copy/paste here some information, related to the code of my customer :)

**Comment by RDsideNow** [comment]
I am having a similar issue

ERROR! Error executing app --reproducible --no-force --with-entities --no-dry-run --no-whitespace --no-bail --no-install-path --no-skip-regenerate --no-skip-yo-resolve --from-jdl --no-skip-cache --no-skip-install --no-force-install --no-ask-answered --no-defaults --no-skip-git --microfrontend

**Comment by mshima** [comment]
This bug is fixed.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/102425.

**Comment by DanielFran** [comment]
@mshima approved
