### ISSUE TITLE
Vue: fix unhandled exceptions.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#17096]
##### **Overview of the issue**

Following https://github.com/jhipster/generator-jhipster/issues/16744#issuecomment-974722473.

Unhandled exception causes warning in tests using node 14 and fails using node 16.
And requires workaround at cypress:
https://github.com/jhipster/generator-jhipster/blob/cc5fcdd73fed569276dd17cba0db0bb40a57a991/generators/cypress/templates/src/test/javascript/cypress/support/index.ts.ejs#L49-L57

The errors must be fixed and workarounds dropped.

##### **Motivation for or Use Case**

We need to fix unhandled exceptions in order to support node 16, drop cypress workaround and apply best practices.

##### **Reproduce the error**

https://github.com/jhipster/generator-jhipster/pull/16883 vue tests failures.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/16744
https://github.com/jhipster/generator-jhipster/issues/16982

##### **JHipster Version(s)**

main

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Added bounty following https://github.com/jhipster/generator-jhipster/issues/16744#issuecomment-974724475.

**Comment by DanielFran** [comment]
@mshima This can be closed?

**Comment by mshima** [comment]
Websocket support needs a rewrite to completely drop unhandled from cypress.
But we probably should open a new issue for it.

**Comment by mshima** [comment]
Completely fixed with https://github.com/jhipster/generator-jhipster/pull/17435

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/100753.

**Comment by DanielFran** [comment]
@mshima approved
