### ISSUE TITLE
JHipster Configuration Hazelcast

### ISSUE THREAD

**Issue by Mixermachine** [jhipster/generator-jhipster#17103]
##### **Overview of the issue**

Hy JHipster-Team,

I'm currently migrating an application to JHipster 7.4 and I found some things that look odd to me.
The JHipster documentation still references `io.github.jhipster.config.JHipsterProperties` in [https://www.jhipster.tech/common-application-properties/](https://www.jhipster.tech/common-application-properties/).
Shouldn't that be `tech.jhipster.config.JHipsterProperties` ?

It also mentions jhipster.cache.hazelcast.management-center.
Is this still a valid variable?
I get errors when I try to set that variable.

```
Property: jhipster.cache.hazelcast.management-center.enabled
    Value: true
    Origin: class path resource [config/application.yml] - 197:26
    Reason: The elements [jhipster.cache.hazelcast.management-center.enabled,jhipster.cache.hazelcast.management-center.update-interval,jhipster.cache.hazelcast.management-center.url] were left unbound.
    Property: jhipster.cache.hazelcast.management-center.update-interval
    Value: 5
```

Has the management-center setting been migrated to some different point?

##### **Motivation for or Use Case**

Helping new developers.

##### **Reproduce the error**

[https://www.jhipster.tech/common-application-properties/#2](https://www.jhipster.tech/common-application-properties/#2)

##### **Related issues**

---

##### **Suggest a Fix**

1. Reference current version JHipsterProperties.class
2. Suggest an alternative location for the management-center configs.

##### **JHipster Version(s)**

JHipster 7.4

##### **JHipster configuration**

Documentation issue.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Documentation issue.

##### **Browsers and Operating System**

Chrome 96, Edge 96

- [X] Checking this box is mandatory (this is just to show you read everything)

Greetings from Munich

**Comment by pascalgrimaud** [comment]
The class comes from here: https://github.com/jhipster/jhipster-bom/blob/main/jhipster-framework/src/main/java/tech/jhipster/config/JHipsterProperties.java

So I think it is still valid.

About our documentation, it is not correct, the package has changed

**Comment by Mixermachine** [comment]
@pascalgrimaud 
Yes that is why I created the issue :)
I just wanted to notify you as this might hinder new developers.

Do you know where the setting for the hazelcast management-center has gone?
I need to migrate my application to the new jhipster version and have to configure the management-center properties.

**Comment by pascalgrimaud** [comment]
Looking at the history: https://github.com/jhipster/jhipster-bom/commits/main/jhipster-framework/src/main/java/tech/jhipster/config/JHipsterProperties.java

There is this PR and commit:
- https://github.com/jhipster/jhipster-bom/pull/40
- https://github.com/jhipster/jhipster-bom/commit/d3f8548213fe423cc8d59f25f527e246a8751bcf#diff-f975304bdee225c6a3dd937233e0fee06f930a6104e3e31e14590d569d31da5b

With this comment in code:

```
            /**
             * In the Hazelcast v4.x, the cluster node doesn't expose
             * configurations to connect to the management center. Setting up
             * of this class properties don't provide any behavior and has
             * been retained for the backward compatibility, and should be
             * removed in the next major release of the JHipster
             */
```

Hope it will help you.

**Comment by Mixermachine** [comment]
Oh ok
We still use Hazelcast 3.11.

Seems like I need to manually configure the Hazelcast node somehow
