### ISSUE TITLE
One-to-many relationship not bidirectional in angular

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster#17117]
Hi, I want to know if there is a way to generate (from the jdl model) the bidirectional one-to-many in Angular client.
I have an app generated with jhipster 6.10.5 .

Thanks in advance.

**Comment by mshima** [comment]
We don’t support that at the backend as well (for writing, we don’t cascade).
It doesn’t make sense to have it in angular.
Should not be difficult to implement as a blueprint.
