### ISSUE TITLE
Upgrade to 7.4.0: relationship type is not synchronized

### ISSUE THREAD

**Issue by Simsal** [jhipster/generator-jhipster#17147]
##### **Overview of the issue**

ERROR! Error at entity UserExtra: relationship type is not synchronized {
    "relationshipType": "one-to-many",
    "otherEntityName": "userExtra",
    "otherEntityRelationshipName": "userExtra",
    "relationshipName": "userExtra",
    "otherEntity": "[UserExtra Entity]",
    "otherEntityField": "id",
    "ownerSide": false,
    "collection": true,
    "otherSideReferenceExists": true,
    "otherEntityIsEmbedded": false
} with {
    "relationshipType": "one-to-many",
    "otherEntityName": "userExtra",
    "otherEntityRelationshipName": "userExtra",
    "relationshipName": "userExtra",
    "otherEntity": "[UserExtra Entity]",
    "otherEntityField": "id",
    "ownerSide": false,
    "collection": true,
    "otherSideReferenceExists": true,
    "otherEntityIsEmbedded": false
}

##### **Motivation for or Use Case**

Upon upgrading to 7.4.0 the error occurs with entitiy type not being synchronized.
I just regenerated my project with 7.2.0 and there the error does not occur. 

I added the entity relationships of UserExtra farther down. 

##### **Related issues**

I read in another issue that every relation must have a unique name. As far as I can see, this does not apply here.

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.simsal.simsal",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "7.2.0",
    "applicationType": "monolith",
    "baseName": "simsal",
    "packageName": "de.simsal.simsal",
    "packageFolder": "de/simsal/simsal",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1601751214138,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": ["de", "en"],
    "blueprints": [],
    "lastLiquibaseTimestamp": 1635723752000,
    "skipUserManagement": true,
    "withAdminUi": true,
    "skipClient": false,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "pages": [],
    "reactive": false,
    "entities": [
      "UserExtra",
      "StudyGroup",
      "Game",
      "RepetitionCycle",
      "GameRecords"
    ],
    "enableGradleEnterprise": false,
    "devServerPort": 4200
  }
}

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

userExtra.json
{
  "name": "UserExtra",
  "fields": [
    {
      "fieldName": "username",
      "fieldType": "String"
    },
    {
      "fieldName": "profileStatus",
      "fieldType": "String"
    }
  ],
  "relationships": [
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "user",
      "otherEntityRelationshipName": "userExtra",
      "relationshipName": "user",
      "ownerSide": true,
      "useJPADerivedIdentifier": true,
      "id": true
    },
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "repetitionCycle",
      "otherEntityRelationshipName": "userExtra",
      "relationshipName": "repetitionCycle",
      "ownerSide": true
    },
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "studyGroup",
      "otherEntityRelationshipName": "administrator",
      "relationshipName": "studyGroup",
      "ownerSide": true
    },
    {
      "relationshipType": "one-to-many",
      "otherEntityName": "userExtra",
      "otherEntityRelationshipName": "main",
      "relationshipName": "second"
    },
    {
      "relationshipType": "many-to-many",
      "otherEntityName": "studyGroup",
      "otherEntityRelationshipName": "user",
      "relationshipName": "group",
      "ownerSide": true
    },
    {
      "relationshipType": "many-to-one",
      "otherEntityName": "userExtra",
      "otherEntityRelationshipName": "second",
      "relationshipName": "main"
    },
    {
      "relationshipType": "one-to-many",
      "otherEntityName": "game",
      "otherEntityRelationshipName": "userExtra",
      "relationshipName": "game"
    },
    {
      "relationshipType": "one-to-many",
      "otherEntityName": "gameRecords",
      "otherEntityRelationshipName": "userExtra",
      "relationshipName": "gameRecords"
    }
  ],
  "changelogDate": "20201109131306",
  "entityTableName": "user_extra",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "serviceClass",
  "jpaMetamodelFiltering": false,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "clientRootFolder": "",
  "applications": "*",
  "incrementalChangelog": false
}

JDL:
entity UserExtra {
  username String
  profileStatus String
}

relationship OneToOne {
  UserExtra{user} to User
  UserExtra{repetitionCycle} to RepetitionCycle{userExtra}
  UserExtra{studyGroup} to StudyGroup{administrator}
}
relationship OneToMany {
  UserExtra{second} to UserExtra{main}
  UserExtra{game} to Game{userExtra}
  UserExtra{gameRecords} to GameRecords{userExtra}
}

relationship ManyToMany {
  UserExtra{group} to StudyGroup{user}
}

##### **Browsers and Operating System**

macOS Big Sur 11.6

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Hi,

Can you please use ticket formatting (sections) and post your entire JDL? e.g. containing the `RepetitionCycle`, `StudyGroup`, `Game` and `GameRecords` entities?

Thank you!

**Comment by Simsal** [comment]
7.5.0 Upgrade worked as expected
