### ISSUE TITLE
Elasticsearch is generated for all entities - not only for those  which are actually marked  with  it

### ISSUE THREAD

**Issue by ko5tik** [jhipster/generator-jhipster#17142]
##### **Overview of the issue**

Only one entity in my project is marked with   "searchEngine": "elasticsearch" -   yet repositories  and code are generated for all those entities.   While it is not a show stopper,   it affects performance  and  misleads other developers. 

##### **Motivation for or Use Case**

I would like to have search repositories only for those classes  that are marked for it

##### **Related issues**

none  found

##### **Suggest a Fix**

improve logic  in generators/entity-server/files.js  ( and other places )   to generate search related stuff only if entity is marked for it.
Can do it myself  but there has to be general consensus   that it is worth doing  before I sink time into PR

##### **JHipster Version(s)**

7.4.0

##### **JHipster configuration**

elcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
recorder@0.0.0 /home/ko5tik/customer/voicecollect/jhsandbox/recorder
└── generator-jhipster@7.3.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "serverPort": "8081",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "baseName": "recorder",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "packageName": "de.vc.recorder",
    "packageFolder": "de/vc/recorder",
    "applicationType": "microservice",
    "jhipsterVersion": "7.3.0",
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": false,
    "nativeLanguage": "en",
    "creationTimestamp": 1618903229235,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "entities": [
      "Channel",
      "Recording",
      "CategoryLabel",
      "Node",
      "UserProfile",
      "SearchLabel",
      "MachineLabel",
      "Comment",
      "Connection",
      "AutomaticLabel",
      "Tag",
      "TagAttachment"
    ],
    "lastLiquibaseTimestamp": 1630495101000,
    "applicationIndex": 2,
    "gatewayServerPort": "8080",
    "monorepository": true,
    "skipCommitHook": true,
    "enableGradleEnterprise": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Channel {
  mediaType Media required
  name String unique required
  throwAwayAllowed Boolean
  threatAllowed Boolean
}
entity Recording {
  date Instant required
  throwAway Boolean
  threat Boolean
  accessed Boolean
  uuid String
  startTime Instant required
  stopTime Instant
}
entity CategoryLabel {
  name String required unique
  description String required
  authorityAttach String required
}
entity Node {
  name String required
  description String
  timeToLive Long
}
entity UserProfile {
  principal String unique required
  template Boolean
  derivedFrom String
}
entity SearchLabel {
  name String required
  description String
}
entity MachineLabel {
  name String required
  value String
}
entity Comment {
  description String
  date Instant required
}
entity Connection {
  connectionId String
  wrapperApplicationId String
  startTime Instant
  stopTime Instant
  messageType String
  channelNumber Integer
  channelName String
  status ConnectionStatus
  userId String
  direction ConnectionDirection
  callType CallType
  callingNumber String
  calledNumber String
  connectTime Long
}
entity AutomaticLabel {
  label String
}
entity Tag {
  name String unique required
}
entity TagAttachment {
  date Instant required
}
enum Media {
  AUDIO,
  VIDEO,
  TEXT,
  BINARY,
  PICTURE
}
enum ConnectionStatus {
  IDLE,
  SETUP,
  RINGING,
  CONNECTED,
  ON_HOLD,
  TRANSFERRED
}
enum ConnectionDirection {
  OUTGOING,
  INCOMING,
  UNKNOWN
}
enum CallType {
  STANDARD,
  CONFERENCE,
  DIVERTED,
  TRANSFERRED
}

relationship OneToMany {
  UserProfile{searchLabels(name)} to SearchLabel{userProfile}
  Recording{machineLabels(name)} to MachineLabel{recording required}
  Recording{connection} to Connection{recording}
  Connection{automaticLabel} to AutomaticLabel{connection}
}
relationship ManyToOne {
  Recording{channel(name) required} to Channel
  Node{parent(name)} to Node
  UserProfile{actualNode(name)} to Node
  Comment{recording required} to Recording
  Comment{userProfile required} to UserProfile
  TagAttachment{recording required} to Recording
  TagAttachment{userProfile required} to UserProfile
  TagAttachment{tag required} to Tag
}
relationship ManyToMany {
  Channel{nodes(name)} to Node
  Recording{categoryLabels(name)} to CategoryLabel
  UserProfile{assignedNodes(name)} to Node
  UserProfile{assignedCategories(name)} to CategoryLabel
  SearchLabel{recordings} to Recording
}

dto Channel, Recording, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, Comment, Connection, AutomaticLabel, Tag, TagAttachment with mapstruct
paginate Channel, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, Comment, Connection, AutomaticLabel, Tag, TagAttachment with pagination
paginate Recording with infinite-scroll
service Channel, Recording, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, Comment, Connection, AutomaticLabel, Tag, TagAttachment with serviceClass
microservice Channel, Recording, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, Comment, Connection, AutomaticLabel, Tag, TagAttachment with recorder
clientRootFolder Channel, Recording, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, Comment, Connection, AutomaticLabel, Tag, TagAttachment with recorder
search Recording with elasticsearch

</pre>
</details>

##### **Environment and Tools**

openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

git version 2.25.1

node: v16.13.0

npm: 8.1.4

Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.

##### **Browsers and Operating System**

linux

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Hi,

It's fixed by https://github.com/jhipster/generator-jhipster/pull/16612.
Feel free to contribute

**Comment by ko5tik** [comment]
Hi Charlie,

Looked into  your PR and  I  did not see any commits for server side
service templates.   Maybe I missed something?

========[] Lines game back in Appstore - check it out! []===============
https://play.google.com/store/apps/details?id=de.pribluda.games.android.lines

Blog:  https://www.pribluda.de

**Comment by Tcharl** [comment]
sorry wrong pasted to ticket

**Comment by ko5tik** [comment]
OK,   looked into source code and discovered that
 if 

 `  seacrhEngine: "elasticsearch"`

  is specified in .yo-rc.json ,   config is generated  for elastic search bean,  and also for every entity unless :
   
   `"searchEngine": false`

is specified in the entity JSON file.  

Even worse,    when elastic search is activated for entity  but not  on the top level   search repositories etc.  are generated
for the entity,   but no central search configuration. I consider this kind of bug. 

However for the frontend generation ( in angular )   search related stuff is only generated when 

 `  seacrhEngine: "elasticsearch"`

is specified in entity json file

Thus frotnend and backedn configuration behaves differently which is not cool,  and counterintuitive. 


I propose to harmonise  this configuration  so that:

1.  It is necessary to activate search on the top level
2. It is necessary to activate search on  every entity explicitely

( this will be also consistent with  JDL import )

**Comment by ko5tik** [comment]
To verify insert following:  
`        it('shall not generate search specific artifacts because elastic search is false on top level', () => {
          assert.noFile([
            `${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/repository/search/FooSearchRepository.java`,
            `${SERVER_TEST_SRC_DIR}com/mycompany/myapp/repository/search/FooSearchRepositoryMockConfiguration.java`,
          ]);
        });`

into entyty.spec.ts @ 804

(  search disabled on the top level,   and enabled in the entity )

**Comment by mshima** [comment]
> OK, looked into source code and discovered that if

@ko5tik glad to see you looking for a solution.

> 
> ` seacrhEngine: "elasticsearch"`
> 
> ....
> Thus frotnend and backedn configuration behaves differently which is not cool, and counterintuitive.

That's actually the current design.
Why? microservices.
Take a gateway that imports entities from 2 microservices, one with search and another without.
The gateway (frontend) has selective search support to expose all features of each microservice.

> I propose to harmonise this configuration so that:
> 
> 1. It is necessary to activate search on the top level
> 2. It is necessary to activate search on  every entity explicitely
> 
> ( this will be also consistent with JDL import )

1. A gateway exposes search at the frontend, even without enabling it at the gateway itself. The suggestion can be done for Monoliths.
2. JHipster 7 should, by default, require the entity to opt-out. Could be changed for JHipster 8, but I prefer the opt-out solution for better out-of-the-box experience.

**Comment by mshima** [comment]
> To verify insert following: ` it('shall not generate search specific artifacts because elastic search is false on top level', () => { assert.noFile([`${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/repository/search/FooSearchRepository.java`, `${SERVER_TEST_SRC_DIR}com/mycompany/myapp/repository/search/FooSearchRepositoryMockConfiguration.java`, ]); });`
> 
> into entyty.spec.ts @ 804
> 
> ( search disabled on the top level, and enabled in the entity )

Sounds good for the backend.
Can you create the PR?

**Comment by ko5tik** [comment]
Gateway exposes search at the frontend only if  entity explicitly opted in.   Indexing is created  unless entity explicitely opts out. And JDL import does not create explicit opt out -  say when I say " search  that with elastic search" I surely do not mean "also search and index everything else".   This is kind of misleading and has to   be fixed and  / or clarified in the documentation

So here is my formal proposal:

microservice backend ( and monolith too  of course )  shall generate indexing  only for entities explicitely requesting it,   to be consistent with JDL / gateway.  I think this is not a breaking change anyway  as   frontend already behaves correctly,  and does not generate calls to the backend for searching  not enabled entities.  

When agreed, I will proceed with pull request.

**Comment by ko5tik** [comment]
Pull request fixing this problem:

https://github.com/jhipster/generator-jhipster/pull/17192

**Comment by Rapster** [comment]
Issue still present in 7.8.1 for monolith application

**Comment by ko5tik** [comment]
> Issue still present in 7.8.1 for monolith application

can you create new bug or even better failing unit test /  provide jdl  and .yo-rc.json ?
