### ISSUE TITLE
How to refresh token while using x-auth-token based authentication?

### ISSUE THREAD

**Issue by alchemistgo87** [jhipster/generator-jhipster#1716]
Do we have refresh token option in x-auth-token authentication. If not, do we have to save username and password of the user in client's local storage or do we have to set the expiration time of token to be infinity.

**Comment by wangshug** [comment]
I am encountering this kind of problem, any suggestion to resolve it.

**Comment by deepu105** [comment]
closing this as issue https://github.com/jhipster/generator-jhipster/issues/1999 is more detailed and is talking about the same thing

**Comment by deepu105** [comment]
oops talked too soon its different issue i guess

**Comment by deepu105** [comment]
@jdubois should this be closed as we are planning to migrate to JWT

**Comment by jdubois** [comment]
Yes XAuth will be replaced by JWT
