### ISSUE TITLE
Migrate from Springfox to Springdoc

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#17175]
##### **Overview of the issue**

Springfox doesn't work with Spring Boot 2.6.0, so we should [migrate to Springdoc](https://springdoc.org/#migrating-from-springfox). 

##### **Motivation for or Use Case**

We should be able to keep up with Spring Boot releases. 

##### **Related issues**

https://github.com/jhipster/generator-jhipster/pull/16787#issuecomment-982130426

##### **JHipster Version(s)**

7.4.0

**Comment by mraible** [comment]
If no one grabs this today, I might take it on.

**Comment by mshima** [comment]
Let me take a look.

**Comment by mshima** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/85378

**Comment by DanielFran** [comment]
@mshima approved
