### ISSUE TITLE
Embedded elastic search finds nothing from Angular

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster#17207]
##### **Overview of the issue**

After running jhipster monolitich app with Angular client, I try to perform a search from the related box (it calls the search api).

##### **Motivation for or Use Case**

I type the word of an entity column and it returns always empty

##### **JHipster Version(s)**

v6.10.5

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.seaviaggiare.app",
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "seaviaggiare",
    "packageName": "com.seaviaggiare.app",
    "packageFolder": "com/seaviaggiare/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "Y2EzNzExOTUxODA3MDAxNDdlOGI5YzVkZmViM2MzMmEyZjU3MmIyNDg2OGVkY2RhYWMwNGE4ZTk2NGUxOWRjMWQ1Nzk4NTEzZDI1M2QzZDdmYWI0MWRkYTI3MzRmMTNkZWFlODIzOTczMWRjNjc1ZjUyN2U4MjE0ZTc3NzUzOTM=",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1637599239537,
    "testFrameworks": ["cucumber"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": ["it", "en"],
    "blueprints": []
  }
}
```
##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
it's probably because the entity is not indexed, as it was inserted by fake data
Try to create the data, and then, search. You should find it.

**Comment by amanganiello90** [comment]
Thanks!!
I have another question: If I call another rest api, that is not the search api, the indexes are always used?

**Comment by pascalgrimaud** [comment]
if you wall another rest api which is _search, it will use service -> repository and do the SQL query, unless there is a cache

**Comment by amanganiello90** [comment]
Thanks a lot!!

**Comment by Tcharl** [comment]
To index you' database into elastic, you can use the elasticreindexer module (it's a little bit old so you'll need some small changes, but you'll have the overall idea).
