### ISSUE TITLE
Switch to starter module for problem-spring-web

### ISSUE THREAD

**Issue by amirensit** [jhipster/generator-jhipster#17212]
##### **Overview of the feature request**

Use [the starter module](https://github.com/zalando/problem-spring-web/tree/main/problem-spring-web) for problem-spring-web.

##### **Motivation for or Use Case**

According to docs, it is possible to use the starter module for spring mvc applications.

**Comment by pascalgrimaud** [comment]
If it can reduce some code and delete some beans, it's a good idea

**Comment by DanielFran** [comment]
@amirensit can you provide a PR?

**Comment by mshima** [comment]
Closing in favor of https://github.com/jhipster/generator-jhipster/issues/19991.
