### ISSUE TITLE
SQL Table names should be underscored

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1721]
SQL table names are currently not underscored, this needs to be fixed.

Ill work on this soon

**Comment by andidev** [comment]
I have started working on #1753, have you done anything yet? Don't think the conflicts will be that large.

**Comment by deepu105** [comment]
no i haven't started, ill follow whatever method that you will come up with for the underscored names. Anyway this is not urgent so ill wait for ur PR and follow

**Comment by Vaelyr** [comment]
Wouldn't custom implementation of Hibernate naming strategy be an option, that would make them underscored and also maybe pluralize, which isn't supported either. Spring has their own too: http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/orm/jpa/hibernate/SpringNamingStrategy.html

**Comment by jdubois** [comment]
Oh sorry, then this is an issue for me: we always use the underlying technologies with their default configuration (unless this causes some issue). So if we use a custom Hibernate strategy, this is not the default anymore.

**Comment by jdubois** [comment]
This has also been discussed in the PR as well as on the dev mailing list, and we need to decide what to do here.
From my understanding it would be better this way, but we would break some compatibility (with foreign keys), is that correct?

**Comment by deepu105** [comment]
@jdubois yes for existing Jhipster generated apps this might give error when old tables are linked to new, but personally I think thats a easy to fix issue for the user as the error thrown by liquibase is very straight forward, other than that I dont think this will cause any issues

**Comment by jdubois** [comment]
@deepu105 can you check that this works fine with the SpringNamingStrategy ? And if so, can you put this strategy by default for Hibernate?
Then I'm OK to merge this, as long as we a good documentation for upgrading (can you write it here, and I'll copy/paste it in the release notes)

**Comment by deepu105** [comment]
@jdubois  ill check and update you, may be we can plan a seperate release for this

**Comment by deepu105** [comment]
@jdubois I had a look, currently we are not defining any strategy as we have the `@Table` annotation, this will override any strategy right? Im not a hibernate expert!
But if im not wrong we would have to generate the table names in liquibase files manually anyway and isnt if wise to have the same in entity with `@Table` as well so that there is no mismatch?

my current PR is just an improvement on existing code which didnt had any strategy

@Vaelyr do you have any comment on this?

**Comment by deepu105** [comment]
Oops it is indeed configured in the yml jpa section, ill do a change and check

**Comment by deepu105** [comment]
done :+1:
