### ISSUE TITLE
React Monolith project logging user out on browser page refresh

### ISSUE THREAD

**Issue by cordial** [jhipster/generator-jhipster#17231]
##### **Overview of the issue**

Overview of the issue
If I login then reload a page that requires authorization the login dialog will show up even though you already logged in.

Motivation for or Use Case
the user already logged in no need to ask him for credentials.

##### **Motivation for or Use Case**
n/a

##### **Reproduce the error**

1. Generate a monolithic project with react frontend
2. Start the front/backends.
3. login using the admin user.
4. open a page that require authorization for example http://localhost:8080/#/user-management
5. In your browser refresh the page. the login dialog will show up and the user is no longer logged in. 
6. I can't see anything in the console and there is no communication to the backend on that page refresh. 

##### **Related issues**

i can only see this being an issue in angular previously. 

##### **Suggest a Fix**

--

##### **JHipster Version(s)**

5.7.2

##### **JHipster configuration**

jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
(node:7838) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7838) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:7838) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
fengshui-manager@0.0.0 /Users/davidcarter/work/fengshui-manager
└── generator-jhipster@5.7.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "jhipsterVersion": "5.8.2",
    "baseName": "formbuilder",
    "packageName": "com.lmc.frm",
    "packageFolder": "com/lmc/frm",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "serviceDiscoveryType": false,
    "languages": [
      "en",
      "fr"
    ],
    "herokuAppName": null,
    "herokuDeployType": "jar",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Client {
  name String
}
entity Form {
  name String required minlength(4) maxlength(20),
  description String,
  licenseeId Integer
}
entity Licensee {
  name String
}
entity PartialResult {
  emailAddress String,
  responseData String required
}
entity Participant {
  resultId String,
  firstName String,
  lastName String,
  emailAddress String required
}
entity Questionnaire {
  name String required,
  address String required,
  postcode String required,
  country String required,
  occupation String,
  namesAndBirthdays String,
  houseBuiltDate String,
  remodelling Boolean,
  footageAndYear String,
  totalSquareFootage String required,
  houseType String,
  lengthOfOwnership String,
  homeHistory String,
  homeHappenings String,
  lifeChanges String,
  homeFeelings String,
  roomChoices String,
  furtherComments String,
  houseIntentions String,
  review String
}
entity QuizResult {
  name String required,
  emailAddress String required,
  houseLock String,
  mountainEnergy String,
  houseRememdies String,
  metalRemedies String,
  twoStoreyHouseRemedies String,
  movingMetal String,
  fireOrRedArea String,
  redEarthArea String
}
entity Result
paginate Client, Licensee, Participant, Questionnaire, QuizResult with pagination
service Client, Form, Licensee, PartialResult, Participant, Questionnaire, QuizResult, Result with serviceImpl

</pre>
</details>

##### **Environment and Tools**

openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36-1562)
OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

git version 2.30.1 (Apple Git-130)

node: v15.1.0

npm: 8.1.4

yeoman: 4.1.0

yarn: 1.22.10

Docker version 20.10.6, build 370c289

docker-compose version 1.29.1, build c34c88b2

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

All browsers 
- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
I don't reproduce

**Comment by pascalgrimaud** [comment]
You're using an old version of JHipster: generator-jhipster@5.7.2
Plz try last version

**Comment by cordial** [comment]
Sorry, that was a typo. my version is actually...     "generator-jhipster": "7.1.0",
