### ISSUE TITLE
Some compilation errors 

### ISSUE THREAD

**Issue by sidaoui** [jhipster/generator-jhipster#17253]
##### **Overview of the issue**

I wanted to create a reactive microservice springboot project with Jhipster, so i found this nice tutorial [Reactive Java Microservices with Spring Boot and JHipster](https://developer.okta.com/blog/2021/01/20/reactive-java-microservices), i copied his jdl file but i make some changes (a just add "entitySuffix Entity" in every application config).
The code generated have some compilation errors

##### **Suggest a Fix**

The code generate the Autority entity without the suffix but in the repository import it use it with the suffix, the same thing with the user entity

##### **JHipster Version(s)**
jhipster --version 7.4.1

##### **JHipster configuration**

INFO! Using JHipster version installed globally
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
C:\Users\msidaoui\git\reactive-stack
`-- (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "serverPort": "8082",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "baseName": "store",
    "buildTool": "maven",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "testFrameworks": [],
    "websocket": false,
    "enableGradleEnterprise": false,
    "gradleEnterpriseHost": "",
    "reactive": true,
    "packageName": "com.okta.developer.store",
    "packageFolder": "com/okta/developer/store",
    "applicationType": "microservice",
    "entitySuffix": "Entity",
    "jhipsterVersion": "7.4.1",
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "skipClient": true,
    "applicationIndex": 2,
    "gatewayServerPort": "8080",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1638977752606,
    "withAdminUi": false,
    "monorepository": true,
    "skipCommitHook": true,
    "jwtSecretKey": "YTZlYTk1ODRjYmFiNjdhMzdkMDgwZjRjZDExNWM4MmI0ZmIzZWY4YmMxYjI1ZWEzOWY2ODY3YjJhOTU1NTRkNzZiYmEzOGViZmM5ZmY0NGJiNzFiMTc4MTNkNjM5YmJlNjEwNzJiYTMzM2VkMjkzMTdiNTAwZTIxYWViOGYzMjE=",
    "entities": ["Product"],
    "lastLiquibaseTimestamp": 1638977812000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
application {
  config {
    baseName gateway 
    reactive true 
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2 
	entitySuffix Entity
    buildTool maven 
    clientFramework vue 
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress] 
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice 
    authenticationType oauth2
	entitySuffix Entity
    buildTool maven
    databaseType neo4j
    devDatabaseType neo4j
    prodDatabaseType neo4j
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store
    reactive true
    packageName com.okta.developer.store
    applicationType microservice
    authenticationType oauth2
	entitySuffix Entity
    buildTool maven
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment { 
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)

git version 2.30.2.windows.1

node: v16.13.1

npm: 7.20.5

Docker version 20.10.10, build b485636

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@pascalgrimaud I confirm the bug, I will work on it!

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's a bug

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/58098 ;)

**Comment by pascalgrimaud** [comment]
Approved
