### ISSUE TITLE
why Liquibase ??

### ISSUE THREAD

**Issue by gitsupi** [jhipster/generator-jhipster#17274]
we are suffering from Liquibase in development time  we really want to be removed this from jhipster core 
spring boot never have and  offer liquibase itself

**Comment by gitsupi** [comment]
spring boot is here to map ORM and leave mind from SQL and xml...
and you are here to automate it more but you are eliminate

**Comment by pascalgrimaud** [comment]
You have several solution if you don't like Liquibase:
- don't use JHipster, use directly Spring Initializr, add the Driver of your database. Then, you'll need to run manually SQL query to upgrade your database: create table, alter table, etc. And if you have more than 3 or 4 environments, enjoy to do it manually without Liquibase :)
- you could use `no-liquibase`, in your configuration, it works well
- delete Liquibase manually is easy, it should take less than 10min to do that (dependency, config, some classes, etc). But you'll lose a lot of time to run SQL queries manually

As there is no bug in JHipster, I'm closing this.

**Comment by Tcharl** [comment]
Liquibase is really useful for projects that are living and already in production: ORM DDL capability does not handle data and schema migration when there's already and existing one set on target database.
