### ISSUE TITLE
Jhipster + React + HTTP Session Authentication throws a 500 error when you refresh the browser page while unauthenticated. 

### ISSUE THREAD

**Issue by cordial** [jhipster/generator-jhipster#17275]
##### **Overview of the issue**

Jhipster + React + HTTP Session Authentication throws a 500 error when you refresh the browser page while authenticated. This is propogated to the front end with a toast that says error 500 (see image below). 

<img width="757" alt="Screenshot 2021-12-12 at 14 51 31" src="https://user-images.githubusercontent.com/419893/145717220-7a24401a-3efa-4dff-a5ee-889c9754a7cc.png">

##### **Motivation for or Use Case**

Other security mechanisms with react/jhipster handle this gracefully (the user sees no error message). 

##### **Reproduce the error**

1. create react + jhipster + HTTP Session Authentication project
2. Refresh page while unauthenticated. 

##### **Related issues**

n/a

##### **Suggest a Fix**

Handle from a UI perspective as the other security mechanisms do. 

##### **JHipster Version(s)**

7.1.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
fm-2@0.0.1-SNAPSHOT /Users/davidcarter/work/newerTest
└── generator-jhipster@7.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "fm2",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1639319155574,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "session",
    "packageName": "com.lime.fm2",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "databaseType": "mongodb",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "lux",
    "clientThemeVariant": "primary",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/lime/fm2",
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36-1562)
OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

git version 2.30.1 (Apple Git-130)

node: v15.1.0

npm: 8.1.4

Docker version 20.10.6, build 370c289

docker-compose version 1.29.1, build c34c88b2

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Browsers and Operating System**

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by cordial** [comment]
the theme is react.

**Comment by qmonmert** [comment]
@pascalgrimaud I don't reproduce

**Comment by pascalgrimaud** [comment]
Closing this, as it can't be reproduced
Plz try to provide more information

**Comment by cordial** [comment]
what's the point, you arbitrarily closed it already.
