### ISSUE TITLE
Vue Router Role Based Authorization Not working

### ISSUE THREAD

**Issue by danielpaukowitsch** [jhipster/generator-jhipster#17293]
##### **Overview of the issue**

It is possible for users with role "USER" to access pages that are marked as "admin-only" in the Vue router file.
The following route is accessable if a "normal" user knows the  URL.

```export default [
  {
    path: '/admin/docs',
    name: 'JhiDocsComponent',
    component: JhiDocsComponent,
    meta: { authorities: [Authority.ADMIN] },
  },
```

##### **Motivation for or Use Case**

If a normal user has the URL he could access pages he should not see (if the backend is configured wrong, e.g. only frontend role based authorization)

##### **Reproduce the error**

1. Create a Vue keycloak monolith app with the generator. (No entities needed.)
2. Start the Docker container for Keycloak and the database (if selected). 
3. run mvnw

##### **Related issues**

Didn't find any.

##### **Suggest a Fix**

The `router.beforeEach` in the `main.ts ` file  calls  `acountService.hasAnyAuthorityAndCheckAuth`  in order to check if the user is allowed to access the requested route and has the needed authorities. 
My guess is that there is an error problem in the following code section of the `account.service.ts` -  `hasAnyAuthorityAndCheckAuth` method.

```
 if (!this.authenticated || !this.userAuthorities) {
      const token = this.cookie.get('JSESSIONID') || this.cookie.get('XSRF-TOKEN');
      if (!this.store.getters.account && !this.store.getters.logon && token) {
        return this.retrieveAccount();
      }
      return Promise.resolve(false);
    }
```

`retrieveAccount ` returns TRUE if an account was found, I would suggest the following changes to the `hasAnyAuthorityAndCheckAuth` method and declaring it as async:

```
   if (!this.authenticated || !this.userAuthorities) {
      const token = this.cookie.get('JSESSIONID') || this.cookie.get('XSRF-TOKEN');
      if (!this.store.getters.account && !this.store.getters.logon && token) {
        const userFound = await this.retrieveAccount();
        if (!userFound) {
          return Promise.resolve(false);
        }
        return this.hasAnyAuthorityAndCheckAuth(authorities);
      }
      return Promise.resolve(false);
    }
    }
```

Please excuse me if I am missing something or I am just missusing this methods.
 
##### **JHipster Version(s)**

Tested with 7.1 and 7.4.

##### **JHipster configuration**

.yo-rc.json:
```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "test",
    "jhipsterVersion": "7.4.0",
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1639393078871,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "flatly",
    "clientThemeVariant": "light",
    "enableTranslation": false,
    "nativeLanguage": "de",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "enableGradleEnterprise": false,
    "languages": ["en", "fr"]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
no entities needed.

##### **Browsers and Operating System**
Google Chrome Version 96.0.4664.93, Windows 10
(same error if using private mode)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/58856 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
