### ISSUE TITLE
Improvement to get current user id

### ISSUE THREAD

**Issue by gzsombor** [jhipster/generator-jhipster#1730]
From my experiences, it is a generic need to get the id of the current user, not only the login name. It would be more efficient, and it would eliminate lot's of unnecessary db calls, for the login name -> id conversions. If others have the same experience - I would like to propose to add a : 
* Create a new class which org.springframework.security.core.userdetails.UserDetails, which stores the user id too 
* Modify the UserDetailsService to return that new User object
* Add a new method into  SecurityUtils, named as  getCurrentLoginId() to get the user id from spring security context

What do you think?

**Comment by gmarziou** [comment]
Agree it's quite common.
In my project, I used the 3rd option.

**Comment by gzsombor** [comment]
Sorry, I thought it's as one proposal, with 3 steps :) Where do you store the login id, if you just added a method to the SecurityUtils? And when do you init / delete it ? Have you created a new thread context variable with a custom filter?

**Comment by gmarziou** [comment]
In my project, I had both public resources and personal resources (e.g. MY contract) that are related to the logged user.
I did something very simple: I just added a getCurrentLoginId() method in a BasePersonalResource abstract class that ContractResource extended.
I implemented getCurrentLoginId() as a simple call to my user repository using SecurityUtils#getCurrentLogin().
I call this method upon each request to my REST controller.
I did not see any performance issue in my context and if I did I would have added caching.

**Comment by Mavlarn** [comment]
In my system, I always use userId, so I got user with login from DB and get id from user, for almost request. Although I use some common code to do that, but I think it is useful to store user id in security context too.

**Comment by deepu105** [comment]
is anyone working on this? its been opne for more than 2 month

**Comment by gzsombor** [comment]
Sorry, I'm a bit overwhelmed in the last 2 months, I will try to squeze some time to contribute an implementation of it.

**Comment by andidev** [comment]
This would be really nice to have

**Comment by amit2103** [comment]
Hi, I can try to contribute code here. Can I work in this?

**Comment by andidev** [comment]
@amit2103 please do! I think this maybe needs to get documented as well.

@jdubois are you okay with this?

**Comment by amit2103** [comment]
@andidev I will get started on this then.

**Comment by amit2103** [comment]
Created a Pull Request for this. Can some one review?

**Comment by gzsombor** [comment]
Ups, I haven't noticed, that someone else also tried to do it - I've done this : https://github.com/jhipster/generator-jhipster/pull/2115, but of course, I'm open to other ideas

**Comment by deepu105** [comment]
@gzsombor is a new user class required? Couldn't we use the existing user
entity?

**Comment by gzsombor** [comment]
Yes, that entity class is managed by hibernate, and if you put that class into the http session, as spring will do it - bad things will happen.

**Comment by amit2103** [comment]
@deepu105  @gzsombor  The main problem with using the user class is imply it does not implement the UserDetail. A pojo managed by Hibernate can be put in HttPSession. It will create no problem since it will be in a managed state, whether it is a security flaw or not is another question. Detached entity is a reality with Hibernate. Once Entity goes outside the Persistence Context, it is no longer managed by Hibernate.

The custom UserDetails object allows Spring Security to use it, so if someone writes a Custom Success or ErrorHandler it wont create a problem. Secondly the User object exposes too many details, any new addition to it will be automatically be exposed. I don't think that is needed.

**Comment by gzsombor** [comment]
Probably this simple user entity wouldn't cause big problems in the http session - assuming, that all it's lazy relations are preemptively fetched - which is always look awkward - but the general pattern is bad. If you start using it, you end up with doing lot's of relation prefetch, and some crazy dance to re-attach an entity to the session, and additionally to this, there will be hidden bugs, which won't surface until the system will be used concurrently, because it won't be clear, that the entity lurking in the session, reflects the up-to-date data inside the database, or it's a 10 minutes old, stale data. Yeah, I'm probably a grumpy old dev, who saw - and had to live/fix - a lot's of bad applications :wink:  Fortunately, we agree, that we need a separate class :smile:

**Comment by amit2103** [comment]
@gzsombor  Yes a complex Entity with lazy relation ships are a problem However I was talking off this entity. The User entity won't cause much trouble. Yes since we agree on the basic thing to do , all is fine :)

**Comment by jdubois** [comment]
Yes I agree this should be a separate class.
BTW, I understand how this works with session-based authentication, but I have no idea how this will work with other 2 authentications: won't this force a session to be created? It wouldn't be good

**Comment by amit2103** [comment]
@jdubois You are correct. In case of OAuth2 it can get a Session to be created. There is one way to stop it and that is to configure the Spring Secuirty as "stateless", when using stateless authentication protocols like Basic, OAuth2 Digest etc. With "stateless" Spring security takes care not to use any session.

**Comment by jdubois** [comment]
I thought we were already using the "stateless" mode but I didn't check. That would be the idea with both "stateless" authentications, but then I guess this code will not work anymore?

**Comment by gzsombor** [comment]
I assume that in stateless mode, spring ask the UserDetailsService for every request, but this is not changed by this commit

**Comment by amit2103** [comment]
@jdubois  this code doesn't change that behaviour in any way.

**Comment by amit2103** [comment]
@gzsombor  Also with stateless, your concern of using a session is also hopefully answered :)

**Comment by gzsombor** [comment]
@amit2103 : yes, stateless webapps are an entirely different beasts :)

**Comment by gzsombor** [comment]
@jdubois : I've pushed a 2nd version of my patch ( https://github.com/jhipster/generator-jhipster/pull/2115 ), where I fixed your comments - except the final fields - if no one objects, can you merge it ? I don't want to merge my commits, without agreement :)

**Comment by amit2103** [comment]
@jdubois  I have already updated my pull request. However if you feel you should  use @gzsombor 's pull request , feel free to discard mine

**Comment by deepu105** [comment]
I used the user entity extending userDetails in my project, didnt have any
issues so far actually. Its not trivial anyway.

**Comment by amit2103** [comment]
@deepu105  If you have a true stateless app, the problem @gzsombor  is talking off will never happen. However I making hibernate entities implement UserDetails is not considered good practice. One all your domain model details are leaked to the Security mechanism. Second the amount of detail that you are exposing to the client is not necessary by any means.

**Comment by gzsombor** [comment]
This is merged with 533a40fec379f948f00e83378ca32a6dc325f583.

**Comment by SimonKlausLudwig** [comment]
I am missing the CustomUserDetails which was merged in 533a40f. Is there a reason for this ? Thank you
