### ISSUE TITLE
JHipster 2.18 - Swagger Docs V2 - Unauthorized with Oauth2

### ISSUE THREAD

**Issue by cah-JimShingler** [jhipster/generator-jhipster#1731]
I recently upgraded to Jhipster 2.18 and started an new effort.  

here is my yo file:

{
  "generator-jhipster": {
    "baseName": "myservices",
    "packageName": "com.myapp.my",
    "packageFolder": "com/myapp/my",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "blahblahblah"
  }
}

When I authenticate with admin/admin and then go to api / swagger docs, ... the resources show up as appropriate, but if I tryout the user resource : GET /api/users

I get Unauthorized.

Request URL
http://127.0.0.1:8080/api/users
Response Body
{
  "timestamp": 1436962673569,
  "status": 401,
  "error": "Unauthorized",
  "message": "Access Denied",
  "path": "/api/users"
}
Response Code
401
Response Headers
{
  "pragma": "no-cache",
  "date": "Wed, 15 Jul 2015 12:17:53 GMT",
  "x-content-type-options": "nosniff",
  "server": "Apache-Coyote/1.1",
  "transfer-encoding": "chunked",
  "content-type": "application/json;charset=UTF-8",
  "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
  "x-xss-protection": "1; mode=block",
  "expires": "0"
}

Even though I already logged in.

If I setup the app with session authentication the process works with no problems:

{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "blahblahblah"
  }
}

So it appears that there might be a oauth security issue with Swagger docs.

Or, is there a security setting I need to change?

I am guessing it might be a yo template issues, ... I noticed the the SecurityConfiguration.java are different, ... the method "protected void configure(HttpSecurity http) throws Exception {" is missing from the Oauth app.

**Comment by cbornet** [comment]
You mean that swagger + oauth was working before you upgraded.
Duplicate of #1697 ?

**Comment by cah-JimShingler** [comment]
Yes, on a different app that was created before 2.18 it worked.

This is a new app using 2.18

Not sure if the issue is part of Swagger Upgrade or something else?

**Comment by ahhk2015starsml** [comment]
This last worked with jhipster 2.16.1 since it used a custom swagger-ui/index.html file.
The problem is the swagger requests do not attach any authentication tokens to the rest requests anymore, so you get 401 authentication errors.

You can compare the missing code here
https://gist.github.com/ahhk2015starsml/e8c0676c96303c59ef4d

**Comment by deepu105** [comment]
I guess it was never working coz swagger part was always in an iFrame and the tokens are not added to http headers @gmarziou isnt that right?

**Comment by gmarziou** [comment]
Kind of,  @jdubois copied the swagger-ui.html and modified it to retrieve token from localstorage  but it seems that we no longer store the token in localstorage, so it has probably worked but failed to work  once the token was removed from localstorage (I haven't searched in history when and why it changed).

I explained more the potential solutions in #1697

**Comment by pnreddysvu** [comment]
Token was removed from localstorage as part of the fix #1417

**Comment by gmarziou** [comment]
Thanks, so it's probably when things stopped working.

I think there were several errors here:
- putting the password in a token in localstorage
- removing the token completely, it should have been kept but containing only the server token
- rather than localstorage  we could have used sessionstsorage

**Comment by gmarziou** [comment]
I have opened issue swagger-api/swagger-ui#1503 to get a way to set the auth token before fetching the swagger spec file.

**Comment by jdubois** [comment]
@gmarziou another solution, which would be simpler:

- In "dev" mode the Swagger page is publicly accessible (no Spring Security at all)
- In "prod" mode it is not available at all

Anyway, "seeing" the API isn't really a security issue, as you can already see it from the AngularJS services.

**Comment by gmarziou** [comment]
Great idea.
I'll implement it.

**Comment by deepu105** [comment]
:+1: i wouldnt turn on swagger in production as its consuming precious prod resources.
I would even disable liquibase in prod as for me a quality software should be tested well in a test environment and moved to prod and if there are DB updates in prod it should have clear manual process to avoid any issues in prod
