### ISSUE TITLE
Pagination is reset for gateway application

### ISSUE THREAD

**Issue by ko5tik** [jhipster/generator-jhipster#17322]
##### **Overview of the issue**

As gateway application does not hat own database,    it is set to "no::

`    "databaseType": "no",`

This leads to disabling   pagination option in  .jhipste/*.json ifles ,   and templates are not generated
WHile this would be proper behavour for monolitic application,   it is not  for gateay

##### **Motivation for or Use Case**

Would like to have pagination  for my entitites in a gateway application

##### **Reproduce the error**

Regenerate entities in a gateway application wthout database and see that json files are changed 
and pagination is not generated for the frontend

##### **Suggest a Fix**

Small change in index.js @386  fixes it:

`
        this.entityConfig.name = this.entityConfig.name || context.name;
        if (![SQL, MONGODB, COUCHBASE, NEO4J].includes(context.databaseType) && context.applicationType !== GATEWAY) {
          this.entityConfig.pagination = NO_PAGINATION;
        }
`
I can provide pull request & more unit tests  when active one is merged 
##### **JHipster Version(s)**

7.4.1  and current trunk  former versions also affected

##### **JHipster Version(s)**

```
admin@0.0.1-SNAPSHOT /home/ko5tikxxxxxxxx
└── generator-jhipster@7.4.1 -> ./../../../../sources/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "withAdminUi": true,
    "baseName": "admin",
    "buildTool": "gradle",
    "databaseType": "no",
    "devDatabaseType": "no",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "de", "fr", "ar-ly", "es", "sr", "pt-pt"],
    "messageBroker": false,
    "prodDatabaseType": "no",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["protractor", "cucumber"],
    "websocket": false,
    "packageName": "de.vc.admin",
    "packageFolder": "de/vc/admin",
    "applicationType": "gateway",
    "jhipsterVersion": "7.4.1",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": true,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1618903229192,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "entities": [
      "Channel",
      "Recording",
      "CategoryLabel",
      "Node",
      "UserProfile",
      "SearchLabel",
      "MachineLabel",
      "Comment",
      "Connection",
      "AutomaticLabel",
      "Tag",
      "TagAttachment"
    ],
    "lastLiquibaseTimestamp": 1630495062000,
    "openApiClients": {
      "recorder": {
        "spec": "../recorder/src/main/resources/swagger/api.yml",
        "generatorName": "spring"
      }
    },
    "applicationIndex": 1,
    "applications": {
      "recorder": {
        "serverPort": "8081",
        "applicationIndex": 2
      }
    },
    "devServerPort": 4201,
    "monorepository": true,
    "skipCommitHook": true,
    "enableGradleEnterprise": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Channel {
  mediaType Media required
  name String unique required
  throwAwayAllowed Boolean
  threatAllowed Boolean
}
entity Recording {
  date Instant required
  throwAway Boolean
  threat Boolean
  accessed Boolean
  uuid String unique required
  startTime Instant required
  stopTime Instant
}
entity CategoryLabel {
  name String required unique
  description String required
  authorityAttach String required
}
entity Node {
  name String required
  description String
  timeToLive Long
}
entity UserProfile {
  principal String unique required
  template Boolean
  derivedFrom String
}
entity SearchLabel {
  name String required
  description String
}
entity MachineLabel {
  name String required
  value String
}
entity Comment {
  description String
  date Instant required
}
entity Connection {
  connectionId String unique required
  wrapperApplicationId String
  startTime Instant
  stopTime Instant
  messageType String
  channelNumber Integer
  channelName String
  status ConnectionStatus
  userId String
  direction ConnectionDirection
  callType CallType
  callingNumber String
  calledNumber String
  connectTime Instant
}
entity AutomaticLabel {
  label String
}
entity Tag {
  name String unique required
}
entity TagAttachment {
  date Instant required
}
enum Media {
  AUDIO,
  VIDEO,
  TEXT,
  BINARY,
  PICTURE
}
enum ConnectionStatus {
  IDLE,
  SETUP,
  RINGING,
  CONNECTED,
  ON_HOLD,
  TRANSFERRED
}
enum ConnectionDirection {
  OUTGOING,
  INCOMING,
  UNKNOWN
}
enum CallType {
  STANDARD,
  CONFERENCE,
  DIVERTED,
  TRANSFERRED
}

relationship OneToMany {
  UserProfile{searchLabels(name)} to SearchLabel{userProfile}
  Recording{machineLabels(name)} to MachineLabel{recording required}
  Recording{connection} to Connection{recording}
  Connection{automaticLabel} to AutomaticLabel{connection}
}
relationship ManyToOne {
  Recording{channel(name) required} to Channel
  Node{parent(name)} to Node
  UserProfile{actualNode(name)} to Node
  Comment{recording required} to Recording
  Comment{userProfile required} to UserProfile
  TagAttachment{recording required} to Recording
  TagAttachment{userProfile required} to UserProfile
  TagAttachment{tag required} to Tag
}
relationship ManyToMany {
  Channel{nodes(name)} to Node
  Recording{categoryLabels(name)} to CategoryLabel
  UserProfile{assignedNodes(name)} to Node
  UserProfile{assignedCategories(name)} to CategoryLabel
  SearchLabel{recordings} to Recording
}

dto Channel, Recording, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, Comment, Connection, AutomaticLabel, Tag, TagAttachment with mapstruct
paginate Channel, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, Comment, Connection, AutomaticLabel, Tag, TagAttachment with pagination
paginate Recording with infinite-scroll
service Channel, Recording, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, Comment, Connection, AutomaticLabel, Tag, TagAttachment with serviceClass
microservice Channel, Recording, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, Comment, Connection, AutomaticLabel, Tag, TagAttachment with recorder
clientRootFolder Channel, Recording, CategoryLabel, Node, UserProfile, SearchLabel, MachineLabel, Comment, Connection, AutomaticLabel, Tag, TagAttachment with recorder
search Recording with elasticsearch

</pre>
</details>

##### **Environment and Tools**

openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

git version 2.25.1

node: v16.13.1

npm: 8.1.2

Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

docker-compose version 1.29.2, build 5becea4c

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ko5tik** [comment]
This change can be piggy-backed on this pull request:

https://github.com/jhipster/generator-jhipster/pull/17252

**Comment by mshima** [comment]
@ko5tik let's keep separated.
This issue affects the gateway only.

**Comment by mshima** [comment]
Should be fixed now
