### ISSUE TITLE
JHipster - support for Pagination abstraction instead of request parameters

### ISSUE THREAD

**Issue by pnowy** [jhipster/generator-jhipster#1733]
I was wondering why on JHister parameters responsible for pagination are provided to back-end by specified request parameters (by @RequestParam annotation) instead of Pageable abstraction provided by PageableHandlerMethodArgumentResolver from Spring.

I assumed that the problem was cooperation with default offset recognized from 0 by Spring and front-end implementation which uses the first page (offset) from 1.

To solve this issue and provide Pageable parameter support on the Resource classes we could prepare our own PageAndSortResolver which will recognize the pagination parameters. With this approach the users of JHipster could also easily use Spring sort abstraction out-of-the-box. Is it worth to consider?

The required changes you can see on the example [JHipster project](https://github.com/pnowy/jhipster-pagination) (commit: https://github.com/pnowy/jhipster-pagination/commit/5a8c748c225fc97a0e3a5a0c1787bd649dc2e550).

**Comment by jdubois** [comment]
In fact the real cause is me not knowing the Spring pagination abstraction good enough! And I wanted to model the pagination with the offset, indeed.
So if you have a solution that could make both model work together, that would be an improvement.
I've had a look at your code and that looks good, my only 2 points are:

- It adds quite a number of new lines to the code, but I don't think this can be simplified
- I would like someone else to review this, as once again I don't know this very well

**Comment by pnowy** [comment]
Ok - so Spring provides out of the box pagination abstraction which can be used as method parameter with Pageable interface. What needs to be done before that is registration of additional argument resolver - mentioned PageableHandlerMethodArgumentResolver.

As I remember this arg resolver is automatically registered with data web support (annotation @EnableSpringDataWebSupport from Spring) or when the web configuration is extended from HateoasAwareSpringDataWebConfiguration (from Spring data commons project). In our case we can register the resolver on additional configuration class (the WebMvcConfiguration on my commit). This abstraction support automatically limit, offset and sorting support.

As I know the often problem with Spring abstraction is the offset (page number) which starts from 0 and the front libraries often use the 1 as the first page. The parameters (page & size) could be parametrized. What I've done in our case I've added additional layer of abstraction and moved the logic from PaginationUtils to our own parameter resolver (and adjusted the back-end logic to the front-end offset which starts from 1) and added the support to Sort resolver from Spring. It simplified resources source code.

But I think the best option it would be use provided PageableHandlerMethodArgumentResolver - but it needs some modification on front-end layer (use $scope.page from 0 and adjustment of pagination directive). I'm not sure are we using on JHipster different libraries for pagination (I've seen the pagination, pager and infinite scroll ). It would be great if you can throw some light of that front-end part regarding existed solutions - especially the infinite scroll (if we base only in self-made solutions the migration to "0" paging shouldn't be a problem).

I hope that I will find on this week some time and prepare separate branch with the solution with modified front-end part and Spring pure abstraction so you and someone else could take a look at that. What I expect from you is you opinion about modification of this front-end part to 0 based offset. Do you see any obstacles to that?

PS. In our project we also using some nice sort directive with that sort abstraction which allows automatically sort by entity properties so if we introduce the pageable abstraction I could present how it works :)

**Comment by pnowy** [comment]
I've prepared the changes based on pure Spring pagination abstraction. (with pageable resolver provided with Spring) with required front-end changes (see https://github.com/pnowy/jhipster-pagination/commit/c0dcd7934d845fd64e93cd2a043d350f1764b3af). There is a less new code as before due the fact that we are using there class from Spring.

These changes are about the pagination. I will take a look also to pager and infinite scroll.

**Comment by jdubois** [comment]
OK this looks a good idea indeed.
Have you checked if this had any impact on the SQL requests? I don't know how this works behind-the-scenes.

**Comment by pnowy** [comment]
The change doesn't have any impact to SQL queries. We still provide the Pageable abstraction to JPA repository. The only change is the way how we handle the Pageable creation (with argument resolver instead of "manually" creation).

I will put the changes into template and give you the update when the pull request will be finished.

**Comment by pnowy** [comment]
The required changes have been prepared on generator.

**Comment by jdubois** [comment]
The PR is merged so I'm closing this, thanks!!!

**Comment by pnowy** [comment]
You are welcome.
