### ISSUE TITLE
Entity detail view should not use input text 

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1735]
Entity detail view should not use input text because there is no form in this view and the static values are presented in a table. 

This is wrong from HTML standpoint and annoying for accessibility reasons.

https://github.com/jhipster/generator-jhipster/blob/master/entity/templates/src/main/webapp/app/_entity-detail.html#L24

**Comment by deepu105** [comment]
:+1: yes this should be just plain text values

**Comment by Vaelyr** [comment]
Should be paragraph with form-control-static class.
