### ISSUE TITLE
Upgrade Keycloak version to 16

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#17362]
##### **Overview of the feature request**

See https://www.keycloak.org/docs/latest/release_notes/index.html#keycloak-16-1-0

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
cc @vishal423

**Comment by vishal423** [comment]
sure. I will take a look in a day or two
