### ISSUE TITLE
In DTO usage the request search method return entity

### ISSUE THREAD

**Issue by outis10** [jhipster/generator-jhipster#1736]
Hi, I think if we use DTO this method have to return  the corresponding EntityDTO too only have access to the attributes of the DTO entity

Because my Entity and My  DTO have different atrtibutes when i searching the service return me the entity with  less attibutes than i required.
I changed to this and work fine

    Spliterator<Municipio> municipioSpliterator=    municipioSearchRepository.search(queryString(query)).spliterator();

        return StreamSupport
            .stream(municipioSpliterator, false).map(municipioMapper::municipioToMunicipioDTO)
            .collect(Collectors.toList());

thanks in advance

**Comment by deepu105** [comment]
This is long open is anyone gonna work on this?

**Comment by jdubois** [comment]
This looks logical to me, I'm coding this, it's easy
