### ISSUE TITLE
Cassandra entities do not compile

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1737]
In FooResource::create() method:
```java
Foo result = fooRepository.save(foo);
```
But in fooRepository:
```java
public void save(Foo foo) {
        if (foo.getId() == null) {
            foo.setId(UUID.randomUUID());
        }
        mapper.save(foo);
    }
```
So the code doesn't compile

**Comment by jdubois** [comment]
Yes I confirm this issue!
We should release a fix for this, this is really bad!

**Comment by jdubois** [comment]
This is really strange as it used to work -> I'm going to push a correction, but I wonder what happened here!

**Comment by deepu105** [comment]
I guess this is coz of changes for the entity modal states, all create updates should return the entity now i guess
