### ISSUE TITLE
Test failure in completely new application without customization

### ISSUE THREAD

**Issue by OmarHawk** [jhipster/generator-jhipster#17373]
##### **Overview of the issue**
Hi,

I just ran into an issue, where one single of the 127 automatically generated frontend tests does fail, without any customizations made after the app has been generated - and also without any entities in there. According to the error it sounds like something with multi-language support. I did select German as the first language and English as the second and no other languages...

This is the error output, while running the following command (which is supposed to build a docker image in the end, but also executes tests):

`mvnw package -Pprod verify jib:build`

<pre>
[INFO] FAIL src/main/webapp/app/shared/reducers/authentication.spec.ts (547 MB heap size)
[INFO]   â?? Authentication reducer tests â?º Actions â?º dispatches GET_SESSION_PENDING and GET_SESSION_FULFILLED actions
[INFO]
[INFO]     expect(received).toMatchObject(expected)
[INFO]
[INFO]     - Expected  - 1
[INFO]     + Received  + 1
[INFO]
[INFO]       Object {
[INFO]     -   "payload": "en",
[INFO]     +   "payload": "de",
[INFO]         "type": "locale/updateLocale",
[INFO]       }
[INFO]
[INFO]       173 |       expect(store.getActions()[0]).toMatchObject(expectedActions[0]);
[INFO]       174 |       expect(store.getActions()[1]).toMatchObject(expectedActions[1]);
[INFO]     > 175 |       expect(store.getActions()[2]).toMatchObject(expectedActions[2]);
[INFO]           |                                     ^
[INFO]       176 |     });
[INFO]       177 |
[INFO]       178 |     it('dispatches LOGOUT actions', async () => {
[INFO]
[INFO]       at next (src/main/webapp/app/shared/reducers/authentication.spec.ts:175:37)
[INFO]       at fulfilled (node_modules/tslib/tslib.js:114:62)
[INFO]`
</pre>

##### **Motivation for or Use Case**

It doesn't build.

##### **Reproduce the error**

Generate application and try to build a docker container out of it.

##### **Related issues**

didn't find any

##### **JHipster Version(s)**

7.4.1

##### **JHipster configuration**

C:\Users\jwedding\git\markant\demo2>jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
demo-2@0.0.1-SNAPSHOT C:\Users\jwedding\git\markant\demo2
`-- generator-jhipster@7.4.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "demo2",
    "jhipsterVersion": "7.4.1",
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cucumber"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1640095868041,
    "serviceDiscoveryType": "no",
    "reactive": true,
    "authenticationType": "session",
    "packageName": "com.demo",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["de", "en"],
    "enableGradleEnterprise": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode)

git version 2.34.1.windows.1

node: v14.18.2

npm: 6.14.15

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

##### **Browsers and Operating System**

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
Indeed this bug exists since a long time

**Comment by mshima** [comment]
Should:
https://github.com/jhipster/generator-jhipster/blob/3af341a9c12707751eb96ea5e0188fd434ae01e5/generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.spec.ts.ejs#L221

Be replaced by `<%= nativeLanguage %>` ?

**Comment by qmonmert** [comment]
@mshima you're right, I do the PR
