### ISSUE TITLE
Default Vue application: strange user.oauth2.service.ts

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#17387]
##### **Overview of the issue**

See https://github.com/jhipster/jhipster-sample-app-vuejs/blob/main/src/main/webapp/app/entities/user/user.oauth2.service.ts

Strange file as it's JWT configuration, not OAuth2

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Just need a rename, the service looks legit.

**Comment by pascalgrimaud** [comment]
Ok, if it is used, we should rename it

**Comment by mshima** [comment]
No oauth condition:
https://github.com/jhipster/jhipster-sample-app-vuejs/blob/2a822d0825cd16b5eb89431c64c498ff74ffc80e/src/main/webapp/app/main.ts#L29

**Comment by mshima** [comment]
Probably is used for relationship with user.
https://github.com/jhipster/generator-jhipster/blob/1de9167f7960c12a6934f0f564337edf08a110c4/generators/client/templates/vue/src/main/webapp/app/main.ts.ejs#L40-L42

**Comment by pascalgrimaud** [comment]
It was added here: https://github.com/jhipster/generator-jhipster/pull/13476

Need some investigation before doing something:
- rename or remove for JWT

**Comment by mshima** [comment]
It's a bug.
Vue is using admin url to fetch user relationships, so it fails for non admin users.
Found while implementing cypress session.

**Comment by pascalgrimaud** [comment]
Thanks @mshima
