### ISSUE TITLE
Readonly entity fields in jdl

### ISSUE THREAD

**Issue by M4jor-Tom** [jhipster/generator-jhipster#17411]
##### **Overview of the feature request**

Something like that would be interesting:

entity Object {
&ensp;density Double required
&ensp;volume Double required
&ensp;mass Double readonly as density * volume //Creates a getter with readonly frontend/CRUD support
&ensp;eligibleFoo Foo readonly as null //Same as before, returning just null so we can set watever we want
}

*The entity Object is NOT readOnly

##### **Motivation for or Use Case**

At work, I use a lot of calculating and/or reference chaining getters because my client wants a summarisation/concatenisation/aggregation on its screens.

This can be useful for:
-Calculation;
-ObjectKind data in Object other than otherField.
-Post Service process data injection in domain objects.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/8800
https://github.com/jhipster/jhipster-core/issues/318

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
At angular you can use `@Readonly` annotation.
Not sure about react or vue.

**Comment by M4jor-Tom** [comment]
Is that annotation to set in the JDL ?

**Comment by mshima** [comment]
Yes.
```
entity Foo {
  @Readonly name String
}
```

**Comment by M4jor-Tom** [comment]
Thanks for help, I thought it didn't exist, sorry for the fake issue, it works for React, as well (didn't try full execution, but could see that Foo.json would specify "readonly": true)

**Comment by mshima** [comment]
We lack documentation for annotations and customizations.
Hopefully we can improve it soon.

**Comment by M4jor-Tom** [comment]
Yes, I've got another idea but not sure I should open an feature issue for that reason, what do you think if we could use a several-crossed-relationships otherfield ?

For example, we have those entities: User{login} <OneToOne> UserData{foo} <OneToMany> Post{content},
and we'd like to show User.login in Post through UserData's relations.
We'd have that:

relationship OneToMany {
ensp;UserData to Post{userData(user.login)}
}

Do you think it's worth issuing or does such a thing already exists ?

**Comment by M4jor-Tom** [comment]
> Yes.
> 
> ```
> entity Foo {
>   @Readonly name String
> }
> ```

Back to that, I tried it, but ommiting Foo.name is readonly: true in Foo.json, nothing seems to change otherwise.
Indeed, I was able to set a @Readonly field and its new value persisted.

Is there something I am still missing ?

**Comment by mshima** [comment]
> Do you think it's worth issuing or does such a thing already exist ?

This feature looks quite specific.
Not sure it’s appropriate to have it implemented.

> Back to that, I tried it, but ommiting Foo.name is readonly: true in Foo.json, nothing seems to change otherwise. Indeed, I was able to set a @readonly field and its new value persisted.
> 
> Is there something I am still missing ?

Readonly support is quite specific, supported by angular for id fields.
You may be better luck to use mapstruct:
https://github.com/jhipster/generator-jhipster/blob/c6f390468c156a602e7603bd976eadd93151bff1/test-integration/samples/jdl-entities/entities.jdl#L7

 Those features are related to the unmerged composite id support.

**Comment by M4jor-Tom** [comment]
What I anderstood about all that, as a mostly a React and Vue and non-expert programmer, after reading https://www.pluralsight.com/guides/rendering-read-only-data-with-angular to anderstand what @Readonly should make with angular, is that Angular should disable Update and Delete functionnalities from user interface, so we could still Create, and Read what's been generated whatever acts in backend.

In our case, (JHipster), it seems like an Angular @Readonly is like a WORM (Write Once Read Many) field, like JPA's id.

What I'd like to do is even to is to have an on-read-generated transient field, like calculus or string confluence.

[Your commit](https://github.com/jhipster/generator-jhipster/commit/c6f390468c156a602e7603bd976eadd93151bff1) seems to do the job, even if I'm not sure of what it's about, but my [implementation](https://github.com/M4jor-Tom/LappLi/commit/f13acad4e065992eb41cdf9b13b3bdc7b67f61bf) of what I'd need at work doesn't required a MapStruct or a DTO.

Am I wrong not doing so ?

**Comment by drissslim** [comment]
> 

Any idea on the described use case and how to reference user.login in subsequent entity related to a UserData entity?

**Comment by M4jor-Tom** [comment]
To me, chaining an additional entity in the relationship's other field's name as it follows (with defined entity, of course):

relationship OneToMany {
 UserData to Post{userData(user.login)}
}

Suffises, because it is possible to know from that, that:
-"Post" entity must own a "userData" field
-"UserData" entity must own a "user" field
-Of course, "User" entity natively owns a login field, but it will have to be specified in the same way for a developer-created entity such as others.

**Comment by DanielFran** [comment]
Closing, fixed in V8
