### ISSUE TITLE
New entity is saved many times if save button is clicked continuously

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#1741]
My network connection was really slow and when I clicked save button...nothing happened..clicked again(without being a patience user)...nothing happened...clicked again.
Then suddenly as expected three entity data were saved.

I think this behavior is not correct.

**Comment by gmarziou** [comment]
This was fixed by PR #1707 which should be part of next release.

**Comment by pmverma** [comment]
Thanks!
Closing issue as it has been fixed.
