### ISSUE TITLE
Prevent messing up the home directory

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#17419]
I wanted to create a new project and forgot to create a new directory (Linux system)

I realized that after I went through the initial generation of the project. 
Now I have a lot of files and folders in my homedirectory and I need to be careful not to delete the wrong ones during cleanup.

I want jhipster to ask a yes/no question whether to continue if it discovers to be run from the home/<user>/ directory and not within a subdirectory.

**Comment by pascalgrimaud** [comment]
Unless I'm wrong, there should be a big warning when the folder is home directory

In my opinion, it's enough.
Adding a new question is overkilled as in majority of case, the answer will be the same: the user won't generate the project in home directory

**Comment by CodingSpiderFox** [comment]
Obviously the warning is not enough

**Comment by vicpermir** [comment]
My opinion is the initial warning is enough, but in any case you should be able list all the files/folders in your home directory ordered by date (creation or last modified) and do a quick cleanup.

**Comment by pmverma** [comment]
For reference, it was discussed in https://github.com/jhipster/generator-jhipster/issues/7896 and https://github.com/jhipster/generator-jhipster/pull/7898

**Comment by deepu105** [comment]
@pascalgrimaud shall we close this? or do we want to update the generator exist with warning when running in home directory
