### ISSUE TITLE
Admin bar disappears when refreshing settings page

### ISSUE THREAD

**Issue by hegek87** [jhipster/generator-jhipster#1742]
Hey,

Using Jhipster 2.16.1 an error on the settings page was found using chrome and safari. To reproduce this, do the following: 

1. Log in as an admin
2. Go to account -> settings
3. Refresh the page

You will see that the administration bar has disappeared. 

I have a fix for this that I committed to a local project, but I'm interested in hearing thoughts about this fix. The issue is caused by forcing the identity to be fetched in settings.controller.js. The has-role directive used in settings.html is run before the promise is returned and after the identity is set to undefined, hence it doesn't see the user as an admin and the admin bar is hidden.

My first (this is a commit of the forked sample app https://github.com/hegek87/jhipster-sample-app/commit/5e8731dcdfe5edf4bda0276d219d38fd77981cd3 ), and preferred attempt, was to resolve the settingsAccount in the settings state. This fixes the issue when we refresh the page, however, when we go to home, then return to account -> settings we get the following error:

TypeError: Cannot read property 'roles' of undefined
    at Object.Principal.isInAnyRole (principal.service.js:23)
    at auth.service.js:40
    at processQueue (angular.js:14454)
    at angular.js:14470
    at Scope.$eval (angular.js:15719)
    at Scope.$digest (angular.js:15530)
    at Scope.$apply (angular.js:15824)
    at angular.js:17580
    at completeOutstandingRequest (angular.js:5370)
    at angular.js:5642

I believe this is caused by the root state resolve, which calls Auth.authorize before the child state 'settings' calls its resolve which assigns _identity in Principal. 

So while searching for a way to delay the directive until after the promise returns I found $timeout. In https://github.com/hegek87/jhipster-sample-app/commit/3f3fb9f6268389b4c04294080e46b7da85e33bbd, I was able to fix the issue by adding a zero second timeout to the hasRole directive.

Is the zero second timeout an acceptable fix? If so, I'd be happy to submit a pull request. I'm interested in hearing other solutions if you guys have any ideas.

**Comment by atomfrede** [comment]
It looks ok, but timout is should be the last option. But I have no other idea right know to be honest.

**Comment by gzsombor** [comment]
This should be rewritten to use promises

**Comment by atomfrede** [comment]
@gzsombor I've changed the ``principal.service.js`` like this (and admin bar never disappears). Is this the correct implementation of a promise?

```
isInRole: function (role) {
   var deferred = $q.defer();
   
  $q.when("_identity")
            .then(function() {
                  if (!_authenticated || !_identity || !_identity.roles) {
                       deferred.resolve(false);
                  } else {
                       deferred.resolve(_identity.roles.indexOf(role) !== -1);
                  }
           });

  return deferred.promise;
}
```

**Comment by gzsombor** [comment]
I think, something like this would work: 

            isInRole: function (role) {
                if (!_authenticated) {
                    return false;
                }

                return this.identity().then(function(_id) { 
                  return _id.roles && _id.roles.indexOf(role) !== -1;
                }, function(err){ 
                  return false; 
                });
            },

The idea is to call the 'identity' which returns a promise about the account, and transform it to true or false according if the user has the requested role.

**Comment by atomfrede** [comment]
Thanks looks better. Will try it out (have some time today).
