### ISSUE TITLE
In project with keycloak, authentication is lost after second request when restarting the backend server

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#17420]
##### **Overview of the issue**

I generated the project, starte the keycloak container and database server, ran the web UI and copied the cookie for authentication into my postman.
Then I ran the GET request on my entity which worked.
Then I stopped the server and started it again.
Then I ran the GET request in postman once more and it succeeded.
Then I ran it a third time and it gave me a 401 error. 

##### **Browsers and Operating System**

Elementary OS 6.1
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@CodingSpiderFox : I encounter a similar but not exactly the same issue. Can you try this fix plz ? https://github.com/jhipster/generator-jhipster/pull/17396

**Comment by CodingSpiderFox** [comment]
I think it is a different cause
