### ISSUE TITLE
Grunt test fails after adding a new language (version 2.18)

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#1743]
Error message is something like

PhantomJS 1.9.8 (Windows 7 0.0.0) Directive Tests  Password strength Should display the password strength bar FAILED
    Error: Unexpected request: GET i18n/zh-cn/global.json
    Expected GET i18n/en/global.json

For more details, please refer to a post on stackoverflow.

http://stackoverflow.com/questions/31465119/get-an-error-after-adding-a-new-language?noredirect=1#comment50907885_31465119

**Comment by atomfrede** [comment]
Have you changed anything else? Preferred language or removed an old language? I've added ``de``, ``zh-cn`` and ``zh-tw`` and ``grunt test`` works fine for me.

**Comment by vw98075** [comment]
I removed the French with the steps stated in the online document.

**Comment by atomfrede** [comment]
Okay, I'll try it out. Nevertheless the test could be change to expect not a concrete language.

**Comment by atomfrede** [comment]
@vw98075 Still no problem here. @deepu105 Can you check it on windows if its a platform problem? But I'll adapt the test to a "wildcard" language today.

**Comment by deepu105** [comment]
@atomfrede could it be because of the order of the request being made? any way ill check it in windows

**Comment by vw98075** [comment]
I try again on this matter today. I remove the French language first and add Chinese. The test is fine. Last time, I added Chinese first and removed French. The order of language change might be the cause.

**Comment by vw98075** [comment]
I get the same error after changing language='en' to language='zh-cn' in language.service.js. The error still persists after I revert the change.

angular.module('yellowflowApp')
    .factory('Language', function ($q, $http, $translate, LANGUAGES) {
        return {
            getCurrent: function () {
                var deferred = $q.defer();
                var language = $translate.storage().get('NG_TRANSLATE_LANG_KEY');

                if (angular.isUndefined(language)) {
                    language = 'en';
                }

                deferred.resolve(language);
                return deferred.promise;
            },
            getAll: function () {
                var deferred = $q.defer();
                deferred.resolve(LANGUAGES);
                return deferred.promise;
            }
        };
    })

**Comment by vw98075** [comment]
I notice at some point, the following lines of code is added into karma.conf.js file also in the index.html file. 

            'main/webapp/bower_components/modernizr/modernizr.js',
            'main/webapp/bower_components/jquery/dist/jquery.js',
            'main/webapp/bower_components/stomp-websocket/lib/stomp.min.js',
            'main/webapp/bower_components/sockjs-client/dist/sockjs.js',
            'main/webapp/bower_components/bootstrap/dist/js/bootstrap.js',
            'main/webapp/bower_components/json3/lib/json3.js',
            'main/webapp/bower_components/angular/angular.js',
            'main/webapp/bower_components/angular-bootstrap/ui-bootstrap-tpls.js',
            'main/webapp/bower_components/angular-ui-router/release/angular-ui-router.js',
            'main/webapp/bower_components/angular-resource/angular-resource.js',
            'main/webapp/bower_components/angular-cookies/angular-cookies.js',
            'main/webapp/bower_components/angular-sanitize/angular-sanitize.js',
            'main/webapp/bower_components/angular-translate/angular-translate.js',
            'main/webapp/bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.js',
            'main/webapp/bower_components/angular-translate-loader-partial/angular-translate-loader-partial.js',
            'main/webapp/bower_components/angular-dynamic-locale/src/tmhDynamicLocale.js',
            'main/webapp/bower_components/angular-local-storage/dist/angular-local-storage.js',
            'main/webapp/bower_components/angular-cache-buster/angular-cache-buster.js',
            'main/webapp/bower_components/ngInfiniteScroll/build/ng-infinite-scroll.js',
            'main/webapp/bower_components/angular-mocks/angular-mocks.js',

**Comment by deepu105** [comment]
I tried it and dont see any issue, could it be something specific that you do. Anyways @atomfrede i think the language check should be generic in all places where the actual test has nothing to do with i18n

**Comment by atomfrede** [comment]
@deepu105 Yes the check should be generic. I can provide a PR.

**Comment by TonyLuo** [comment]
this issue still exists in JHipster Generator v2.24.0

**Comment by jdubois** [comment]
@TonyLuo I just tested it on the current master branch and it's working... It looks like there's something else here, more than just generating the app and adding a new language

**Comment by TonyLuo** [comment]
@jdubois  I generated a brand new project running command yo jhipster , then I removed the French language first and added Chinese following this guide http://jhipster.github.io/installing_new_languages.html , and then changed preferred language  to be zh-cn .  I did nothing else but just these steps. after that run mvn -Pprod clean package, the test failed with Error: Unexpected request: GET i18n/zh-cn/global.json

Is it caused by removing the French language ? 
I found that when I generated a new entity running yo jhipster:entity UserInfo, jhipster still generated i18n/fr/userInfo.json. It seems the jhipster still can remember fr language somewhere, the removing language steps in the guideline cannot remove the fr language clearly .

**Comment by pascalgrimaud** [comment]
@TonyLuo : can you try this ? https://github.com/jhipster/generator-jhipster/issues/1927

**Comment by TonyLuo** [comment]
@pascalgrimaud  I tried , but it didn't work for me.

**Comment by pascalgrimaud** [comment]
@TonyLuo: what file did u put in your karma.conf.js ?

**Comment by TonyLuo** [comment]
I put  zh.js  in karma.conf.js after  // endbower. but it didn't work.

`
  // endbower
   'main/webapp/bower_components/messageformat/locale/zh.js',
`

**Comment by thangnc** [comment]
I'm using JHipster 2.23.0. Put vi.js below //end bower will be worked. But when we run `grunt build`. Its not include the default locale into index.html.

**Comment by TonyLuo** [comment]
@jdubois finally found the cause... need to change the RegExp in httpBackend.js, as the code for Chinese Simply is  "zh-cn".  #2435 

`
httpBackend.js
function mockI18nCalls() {
    inject(function($httpBackend) {
        $httpBackend.whenGET(/i18n\/.*\/.+\.json/).respond({});
    });
}
`
