### ISSUE TITLE
Entities with JpaRepository only

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#17436]
##### **Overview of the feature request**

It could be a 1st step of @jdubois's idea in the mailing list.
I wonder if we could use the JDL to generate only the entities and jpa part, and ignoring Service, DTO, Rest, front, etc

Maybe we could only keep the liquibase part, I don't know.

##### **Motivation for or Use Case**

If the JDL can work in all Spring Boot projects, without the requirement of the base of JHipster project, it will be a killer feature.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Cc @mshima as you're our expert on this part. What do you think?
I can try to implement it, if you find the idea not bad and if you think it's doable

**Comment by MathieuAA** [comment]
It's easy to do. Again, the generation part is done by the generator and there's no change to do in the "JDL part" of the code base: once the .JSON files are generated, it's up to a generator to read the JSON entity files and do its magic.

**Comment by mshima** [comment]
> Cc @mshima as you're our expert on this part. What do you think?

Can somewhat be accomplished by `jhipster jdl bug-tracker.jh --ignore-application --db sql --skip-client`

Missing the `--skip-rest` option.

I will try a entity only jdl.

**Comment by pascalgrimaud** [comment]
Interesting! Will try it soon.
Don't hesitate to ping me if you need me to do something

**Comment by mshima** [comment]
> I will try a entity only jdl.

Application is currently required to parse the jdl.

**Comment by MathieuAA** [comment]
@mshima Yes, it's kinda mandatory so as to validate the provided entities. Removing this check can easily be done though

**Comment by nomuna** [comment]
So I tried the following with the current version.

```sh
jhipster import-jdl --skip-client --ignore-application model\21-points_mvn.jh
```
_21-points_mvn.jh_ is a file 21-points.jh where the build tool was set to maven.

The convent of the directory after the command is run is as follows

![skip_client_ignore_app_21_points](https://user-images.githubusercontent.com/14033335/149039592-037a15e4-eb53-46ba-948d-0207905bd8be.png)

So the functionality is "there". I can not imagine anyone who would say no to generated rest controllers and repositories for their entities.

**Comment by pascalgrimaud** [comment]
@nomuna : it depends on your needs and on your project:
- sometimes, you have Entities you don't want to expose in API
- it's not specially a good practice to expose the entity as this, you should always map to another object
- Rest Controller is not the only one input of your application, you can have Listener, CLI, etc

**Comment by nomuna** [comment]
So basically if you add another option to disable the rest stuff and repository stuff it would be enough, yes?

At the moment whoever needs this functionality could remove the rest/repository code. Not saying that the ticket does not make sense or anything. Just pointing out what is there and see how far I can go using the already available means so that what can and should be done is clarified.

**Comment by pascalgrimaud** [comment]
@nomuna : here some use cases

1st use case:
- init your project with Spring Initializr https://start.spring.io/
- add appropriate dependencies
- use JHipster to generate Entities and Jpa Repositories

2nd use case:
- existing Spring Boot project
- use JHipster to generate Entities and Jpa Repositories

So as discussed in the mailing list, we think it could be a great option to use the JDL in existing Spring Boot projects, without the need of JHipster projects.

**Comment by Tcharl** [comment]
Hello,

If you implement it, please keep in mind the discussion we had here: https://github.com/jhipster/generator-jhipster/issues/14416

IMHO inclusive options will fix one pain point we'll face in regard to exclusive syntax

**Comment by pascalgrimaud** [comment]
I don't plan to implement it and not sure if we should do it.
I can play with git, by reverting some part I don't want, and it should do the trick

**Comment by pascalgrimaud** [comment]
Followed my last comment, no need to implement it
