### ISSUE TITLE
HTTP 401 error for api-docs with Token-based authentication

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#1744]
401 : {"timestamp":1437078467982,"status":401,"error":"Unauthorized","message":"Access Denied","path":"/v2/api-docs"}

I don't have this error when I use OAuth2 authentication configuration

**Comment by gmarziou** [comment]
It seems to be a duplicate of #1731

**Comment by gmarziou** [comment]
Yes it's a known issue, it was the same also before upgrading to spring-fox

**Comment by vw98075** [comment]
I had scanned over those existing bug reports and didn't see the pone. Sorry for posting a duplicated report.

**Comment by gmarziou** [comment]
No problem, it was mentioned in 2.18.0 release notes:

https://jhipster.github.io/2015/07/07/jhipster-release-2.18.0.html

**Comment by paivaric** [comment]
+1
