### ISSUE TITLE
Integration tests fail when org.liquibase.ext.liquibase-mssql in classpath

### ISSUE THREAD

**Issue by ALLAOUI-DSI** [jhipster/generator-jhipster#17449]
##### **Overview of the issue**

When a project is created using the cli, and the prod DB is set to SQLSERVER, the integration tests fail with the following error messages (no edits to the generated files):
```
2021-12-31 11:23:34.833  WARN 14040 --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [io/nikom/config/LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
     Reason: liquibase.exception.DatabaseException: Erreur de syntaxe dans l'instruction SQL "IF[*] EXISTS(SELECT TABLE_NAME
            FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME = 'jhi_user'
             AND TABLE_SCHEMA = 'PUBLIC'
             AND COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), COLUMN_NAME, 'IsIdentity') = 1)
	SET IDENTITY_INSERT PUBLIC.JHI_USER ON"
Syntax error in SQL statement "IF[*] EXISTS(SELECT TABLE_NAME
            FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME = 'jhi_user'
             AND TABLE_SCHEMA = 'PUBLIC'
             AND COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), COLUMN_NAME, 'IsIdentity') = 1)
	SET IDENTITY_INSERT PUBLIC.JHI_USER ON"; SQL statement:
IF EXISTS(select TABLE_NAME
            from INFORMATION_SCHEMA.COLUMNS
           where TABLE_NAME = 'jhi_user'
             and TABLE_SCHEMA = 'PUBLIC'
             and COLUMNPROPERTY(object_id(TABLE_SCHEMA + '.' + TABLE_NAME), COLUMN_NAME, 'IsIdentity') = 1)
	SET IDENTITY_INSERT PUBLIC.jhi_user ON [42000-200] [Failed SQL: (42000) IF EXISTS(select TABLE_NAME
            from INFORMATION_SCHEMA.COLUMNS
           where TABLE_NAME = 'jhi_user'
             and TABLE_SCHEMA = 'PUBLIC'
             and COLUMNPROPERTY(object_id(TABLE_SCHEMA + '.' + TABLE_NAME), COLUMN_NAME, 'IsIdentity') = 1)
	SET IDENTITY_INSERT PUBLIC.jhi_user ON]
```

##### **Motivation for or Use Case**

A newly created project should pass all the tests.

##### **Reproduce the error**

Generate a new project with no options, and pick SQLSERVER as the prod DB, run the command:
`mvnw -Pprod clean verify`
The integration tests wont pass. 
When the following dependency is removed from POM.xml, the tests pass.
```
        <dependency>
            <groupId>org.liquibase.ext</groupId>
            <artifactId>liquibase-mssql</artifactId>
            <version>${liquibase.version}</version>
        </dependency>
````
##### **Related issues**

N/A
##### **Suggest a Fix**
Investigate the effect of the mentioned dependency on the tests.

##### **JHipster Version(s)**

` generator-jhipster@7.4.1`

##### **JHipster configuration**

`jhipster info` output: 

INFO! Using JHipster version installed locally in current project's node_modules
##### **JHipster Version(s)**

```
omega@0.0.1-SNAPSHOT C:\Users\USERNAME\jhipster-sqlserver
└── generator-jhipster@7.4.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "omega",
    "jhipsterVersion": "7.4.1",
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1640939685391,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "io.nikom",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mssql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "enableGradleEnterprise": false,
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

git version 2.24.1.windows.2

node: v16.13.1

npm: 8.1.2

##### **Browsers and Operating System**
Not browser related.
Windows 10 Pro 19041.746.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by lucastaehli** [comment]
Same Problem on "jhipsterVersion": "7.8.1". All tests fail.

**Comment by DanielFran** [comment]
@lucastaehli @ALLAOUI-DSI Starting on liquibase 4.4+, mssql-liquibase extension fixed the loaddata (see https://github.com/liquibase/liquibase-mssql/commit/0c2b40cb9971d02d0d852bef1778fc1bacf4c612)

Changes has been applied also in jhipster v.7.2.0 to remove the same workaround: https://github.com/jhipster/generator-jhipster/pull/15492/files

Can you contribute with the fix?
Thanks

**Comment by lucastaehli** [comment]
@DanielFran The problem is that SET IDENTITY_INSERT from the "loadData" gets executed even when the webapplication gets started with h2 or integration tests are started with h2. SET IDENTITY_INSERT is not supported at h2 and therefore the following Exception is thrown:

Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "IF[*] EXISTS(SELECT TABLE_NAME
            FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME = 'jhi_user'
             AND TABLE_SCHEMA = 'PUBLIC'
             AND COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), COLUMN_NAME, 'IsIdentity') = 1)
        SET IDENTITY_INSERT PUBLIC.JHI_USER ON"; SQL statement:

**Comment by DanielFran** [comment]
@lucastaehli 
Looking at pom.xml, for both dev and prod profile liquibase-mssql extension is only available if the dev/prod database defined is mssql: https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/pom.xml.ejs#L1770-L1779

We do not have anymore "SET IDENTITY_INSERT" declared in liquibase scripts, so it might be an issue during the update process of a major version.

Can you add here your jhipster configuration?

**Comment by lucastaehli** [comment]
@DanielFran I use gradle and the liquibase mssql dependencies are generated in the build.gradle file. I moved them to the profile_prod.gradle and everything seems to work now. Thanks for your help

**Comment by DanielFran** [comment]
@lucastaehli Did not check yet, but do you want to contribute with a PR?

**Comment by DanielFran** [comment]
@atomfrede SInce the issue is on gradle configuration, can you review test and prod profiles?
