### ISSUE TITLE
Create a board of JHipster contributors

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1745]
This isn't really a ticket, but I'd like to open up a discussion on managing JHipster and this is the only place to do it.

In case you are wondering:
- I have never met 98% of the other JHipster contributors
- I have no way to contact them outside Github -> we don't exchange mails in private, etc... I don't have even have the email addresses of most of the top contributors

I find this really cool, as we are just a bunch of people who like to code together. We have no issue on age, religion, sex, etc... which I also find really good.

But this raises some issues:

- As mentioned [here](http://raibledesigns.com/rd/entry/grails_angular_vs_jhipster?utm_content=bufferfa330&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer) in @mraible blog, people have concern that I decide everything. I kind of agree with this, even if thanks to Yeoman there is one huge argument against this comment: when people want to use stuff I wouldn't use myself (like Gulp.js, Gradle, Openshift, etc etc), then I just add an option to the generator. We can't do all the options in the world, but still that should make most people happy.
- When I am on holidays, the merges stop. Last summer this was managed by my good friend @jmirc but this year he doesn't have the time (and as I said earlier we're just a bunch of guys who like to code together, so nobody is forced to work here during the holidays)

-> this last point is my biggest concern. I just went 4 days abroad, and we have now 49 issues and 12 PRs, and this is just getting too big for me to handle alone.

One personal note, also, as I often have people asking me for "urgent" requests, opening private chat requests or sending me private emails: when not on holidays, I'm working full time for a client, so in the day I'm just not working for somebody else. I'm only doing "the best I can", on my free time.

If that doesn't suit you, and you'd like to have this warm feeling of having "corporate support", please note that you can get some from [my company](http://jhipster.github.io/consulting.html).

Enough talk about the problems, now let's move to the solutions.

One solution would be to move to a fundation, like Groovy did recently. @glaforge is a good friend, I'll ask him about this the next time we meet, but this looks quite complex.

For the moment, I'm really happy with the way Github works, and with the way we all work together. It's fun, we have no company or fundation to tell us we shouldn't send that [stupid tweet](https://twitter.com/java_hipster/status/619141562551955456) (oh yes, that's 1,450 retweets, it brought us a lot of new followers/stars/users), so I don't want to touch this.

My current idea, which I would like to discuss here is to:

- create a board with our top contributors
- give them write access to the repo
- create a specific mailing list for them (other people would just have "read" access to it)

That means that those top contributors would need to give me their real names and e-mail address, but of course there still won't be any commitment from them: they can leave at any time.

And I'd like to nominate our top contributors at this moment, @atomfrede @andidev @gzsombor @gmarziou @deepu105 (am I missing someone?)

**Comment by deepu105** [comment]
:+1: @jdubois Im in, let me know what details you require

**Comment by gmarziou** [comment]
I'd be glad to participate and in fact the timing is perfect as I'd like to propose some refactoring of the yeoman templates to make them easier to maintain and evolve.

**Comment by atomfrede** [comment]
@jdubois I love the way of working together. As you said no matter what age, religion, sex or origin. Everyone is treated with respect, which is really great! An the concern that you decide everything is far away from being true (e.g. oracle db, optional translation, frontend refatoring). So the community driven approach works very well.

So thanks to @deepu105 @andidev @gzsombor @gmarziou for their commitment (and everyone else I've forgotten here).

In addition to a mailing list I would also like to have a closed jhipster gitter chat (if thats possible). 

And of course: Count me in, trying to do my very best.

**Comment by jdubois** [comment]
@atomfrede oh yes for Gitter that should be doable. The only issue with Gitter is that we lose the history, so that's really just for chatting, not for discussing important stuff.

BTW I'm going to be away for a few more days, so don't worry if I don't answer, again :-)

**Comment by atomfrede** [comment]
@jdubois Yes, gitter is just for chatting not for great "design or architecture" discussions. Have some nice holidays!

**Comment by deepu105** [comment]
@atomfrede, @jdubois  yup thats very true, I have seen many OSS projects and nothing really made me want to be a contributor, especially given my hectic schedules. but this was an exception, I fell in love with JH at first sight and this is my major OSS contribution so far. 
I really liked the current way things are and Github is the easiest way for managing the project i guess.

:+1: for closed group chat

@jdubois have a nice holiday

**Comment by gzsombor** [comment]
+1 I'm in!

**Comment by andidev** [comment]
I'm in as well!

**Comment by jdubois** [comment]
Hi all,

OK, so we all agree here -> I'm closing this issue as a result.

 @deepu105 @andidev @gzsombor @gmarziou can you all send me your real email address so I can join you is necessary? My email is firstname.lastname@gmail.com (with my firstname="julien" and lastname="dubois")

This will be first priority in the next weeks (yes I'm still on holidays, so things won't go as fast as everybody wants, but hopefully this will solve this issue in the long run)

**Comment by jdubois** [comment]
@gmarziou I'm only missing your email address!

**Comment by gmarziou** [comment]
I did send it yesterday at 23:22 but I just sent it again.
