### ISSUE TITLE
Improve Sonar analysis

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#17468]
Improve Sonar analysis https://sonarcloud.io/project/overview?id=jhipster-sample-application

##### **Overview of the issue**

Improve code quality

##### **Reproduce the error**

Start local Sonar
`./mvnw -Pprod clean verify sonar:sonar`

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
PRs:
- https://github.com/jhipster/generator-jhipster/pull/17465
- https://github.com/jhipster/generator-jhipster/pull/17466

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/59965

**Comment by pascalgrimaud** [comment]
Thanks for your huge work here @qmonmert 
Adding a bounty for all of these PRs as it's a pain for:
- reproduce
- fix
- relaunch Sonar Analysis...
