### ISSUE TITLE
Implement new interfaces for ElasticSearch Entity indexing

### ISSUE THREAD

**Issue by ko5tik** [jhipster/generator-jhipster#17488]
##### **Overview of the feature request**

Current logic for entity indexing:

```java
    public RecordingDTO save(RecordingDTO recordingDTO) {
        log.debug("Request to save Recording : {}", recordingDTO);
        Recording recording = recordingMapper.toEntity(recordingDTO);
        recording = recordingRepository.save(recording);
        RecordingDTO result = recordingMapper.toDto(recording);
        recordingSearchRepository.save(recording);
        return result;
    }
```
Has a major flaw - it does not index  that is actually contained in database.   DTO coming from  REST layer may mot contain all the relations (which are managed by other entity)  and thus indexing result will not reflect actual data stored in database.

To overcome this situation,   indexing shall be performed over entity loaded from database in separate  transaction with sufficient isolation level to get real data contained in database.   This may ( shall ) be done asynchronously,   because it involves external rest call to elasticsearch service running in a separate JVM anyway. 

I propose adding 2 methods:

```java
    @Transactional(propagation =  Propagation.REQUIRES_NEW, readOnly = true, isolation = Isolation.READ_COMMITTED)
    public Recording indexRecording(Recording recording) {
        recordingRepository.findOneWithEagerRelationships(recording.getId()).ifPresent(recordingSearchRepository::save);
        return recording;
    }

    /**
     * asynch wrapper
     * @param toBeIndexed
     */
    @Async
    @Transactional(propagation =  Propagation.REQUIRES_NEW, readOnly = true, isolation = Isolation.READ_COMMITTED)
    public void asyncIndexRecording(Recording toBeIndexed) {
        indexRecording(toBeIndexed);
    }
```

And invoke them instead of calling search repository directly

     
##### **Motivation for or Use Case**

I would like index data  to be in synch with actual  data contained in database so search would be accurate. 

##### **Related issues or PR**

did not found

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ko5tik** [comment]
Actually I moved it out into separate service, so it does not collide with generated code when I have to regenerate - I am aware that special considerations shall be made when calling async methods and new transactions  on the same beans

**Comment by ko5tik** [comment]
Additional improvement:  search repostory shall offer methods utilising  Query  ,  not only string query.

**Comment by Tcharl** [comment]
Why do you want the exact same content from a sql db and an elastic db?

Looks normal to have everything in a sql db (because it's relational so you can query any relation), but only the document (without relations) in a noSQL one.

If you really want it, be sure to have the exact same content as the DTO in the NoSql db, no more, no less, and to avoid cycling dependency.

Ex:
EntityA----*to1-relationshipto----EntityB----*to1relationshipto----EntityC----1to1relationshipto----EntityA

**Comment by ko5tik** [comment]
My object model can be changed from the frontend,   and also  from some backend process.  SO DTO coming from the frontend does not necessary has all the proper data and relations.  When this DTO  is mapped to domain class,   and then passed to  elastic for indexing it will be out of sync with real  data model. So my proposed solution is  to perform index in a separate thansaction (read only and with proper isolation ) and in a separate thread  ( as this happens asynchronously anyway) - this assures that index  becomes the same data as database.

**Comment by ko5tik** [comment]
> Why do you want the exact same content from a sql db and an elastic db?
> 
> Looks normal to have everything in a sql db (because it's relational so you can query any relation), but only the document (without relations) in a noSQL one.
> 
> If you really want it, be sure to have the exact same content as the DTO in the NoSql db, no more, no less, and to avoid cycling dependency.
> 
> Ex: EntityA----*to1-relationshipto----EntityB----*to1relationshipto----EntityC----1to1relationshipto----EntityA

Say, you  have kind of CRM.    There is conversation ( entity A )   which   has a lot  of phone calls ( entity B ) with own metadata.     And I definitely need to search for conversations   by phone numbers of those calls ( and other metadata ) -  so they ought to be in one document
