### ISSUE TITLE
Modularize yeoman templates for easier maintenance and evolution

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1749]
Hi contributors!

The entity sub generator has probably the most complex yeoman templates of JHipster because they have grown each time new features were added, lately enums and validation have added even more complexity to the point that I think it's quite hard to evolve them.

So, thinking that there must be a better way, I looked at the template engine used by yeoman: [EJS](http://ejs.co/) and found that we could benefit from using these features:

-  `include `       Sub templates
- `<%-`             Outputs the unescaped value into the template
- `<%#`            Comment tag, no execution, no output
- `-%>`             Trim-mode ('newline slurp') tag, trims following newline

I have applied this approach to field validation:
  - _Entity.java (annotations)
  - _entity-dialog.html (angular directives on form input fields)

The main change is to extract complex logic from the template and to externalize it to a sub template included by the first one and located in same folder.

- [_entity-dialog.html](https://github.com/gmarziou/generator-jhipster/blob/validators/entity/templates/src/main/webapp/app/_entity-dialog.html) includes [ng_validators.ejs](https://github.com/gmarziou/generator-jhipster/blob/validators/entity/templates/src/main/webapp/app/ng_validators.ejs)
- [_Entity.java](https://github.com/gmarziou/generator-jhipster/blob/validators/entity/templates/src/main/java/package/domain/_Entity.java) includes [field_validators.ejs](https://github.com/gmarziou/generator-jhipster/blob/validators/entity/templates/src/main/java/package/domain/field_validators.ejs)

I chose the ejs extension because it's the default one and it allows to have a very concise syntax:

    <%- include field_validators -%>

Hopefully, you'll find that this more readable than current templates embedding this logic without any good indentation and mixing 2 languages.

Another benefit is that the ejs sub templates can easily be unit tested.

Embedded templates can still be used and they are good for 1 to 3 lines of JS, but for bigger JS fragments I think we should refactor the template using this approach.

My fork is [here](https://github.com/gmarziou/generator-jhipster/blob/validators) but there's nothing more than these 4 files I linked above.

**Comment by atomfrede** [comment]
Looks good to me. Especially when you have a lot of options (like validation or databases) your proposal makes it much easier to maintain the templates.

**Comment by gmarziou** [comment]
The most difficult part is to remove the old lines once you have created the sub template because it's so easy to remove a needed closing tag and ejs is not very good at pointing you to the error.

**Comment by deepu105** [comment]
yes this should be good, we should continue this to other parts as well, for example move reusable code to be used across the sub generators, like building war for cloud deployments etc, reduce the overuse of `this` etc, but these can be tracked under separate issues. :+1:  for above change

**Comment by deepu105** [comment]
@gmarziou after the addition of template ng_validator.ejs im finding the below error when i run with translation false.

This is coz for removing translation i have used a regex to strip translation content from html

in script-base.js line 223, the engine function throws error as it is unable to find the include file. I guess file name can be passed but how do we solve when we use more than one template files. Im not very familiar with ejs to comment
```
Generator.prototype.stripContent = function (source, regex, data, _opt) {
    var re = new RegExp(regex, 'g');
    var that=this;

    var body = html.readFileAsString(path.join(that.sourceRoot(), source));
    this.engine = require('ejs').render;
    body = this.engine(body, data, _opt);
    body = body.replace(re, '');

    return body;
}
```

```
Found the .jhipster/Bar.json configuration file, automatically generating the entity
The entity bar is being created.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: `include` requires the 'filename' option.
    at includeSource (D:\Projects\GIT\generator-jhipster\node_modules\ejs\lib\ejs.js:191:11)
    at D:\Projects\GIT\generator-jhipster\node_modules\ejs\lib\ejs.js:512:24
    at Array.forEach (native)
    at Object.Template.generateSource (D:\Projects\GIT\generator-jhipster\node_modules\ejs\lib\ejs.js:493:15)
    at Object.Template.compile (D:\Projects\GIT\generator-jhipster\node_modules\ejs\lib\ejs.js:416:12)
    at Object.compile (D:\Projects\GIT\generator-jhipster\node_modules\ejs\lib\ejs.js:288:16)
    at handleCache (D:\Projects\GIT\generator-jhipster\node_modules\ejs\lib\ejs.js:147:16)
    at EntityGenerator.exports.render [as engine] (D:\Projects\GIT\generator-jhipster\node_modules\ejs\lib\ejs.js:315:8)

    at EntityGenerator.Generator.stripContent (D:\Projects\GIT\generator-jhipster\script-base.js:229:17)
    at EntityGenerator.Generator.copyHtml (D:\Projects\GIT\generator-jhipster\script-base.js:200:25)

```

**Comment by deepu105** [comment]
@gmarziou I guess we need to add some tests for entity sub as well so that we can identify any issues before releases

**Comment by deepu105** [comment]
@gmarziou for now I have added below line before calling the engine method and it works

```
_opt.filename = path.join(that.sourceRoot(), "src/main/webapp/app/ng_validators.ejs");
```

but I dont know how to tackle this when there are multiple .ejs files in future

**Comment by gmarziou** [comment]
The include path is resolved relatively to the template including it.
Why is stripContent running on the template rather than on the generated file?

**Comment by deepu105** [comment]
I guess i had trouble getting this approach working on the rendered template in memory, but if you're able to change it plz do so

**Comment by andidev** [comment]
This is really good! We need to make our templates more readable.

I proposed a [PR](mde/ejs#105) to the ejs team which means that after the next release of ejs we will be able to refactor e.g. 

```html
<thead>
    <tr>
        <th translate="global.field.id">ID</th><% for (fieldId in fields) { %>
        <th translate="<%=keyPrefix + fields[fieldId].fieldName %>"><%=fields[fieldId].fieldNameCapitalized%></th><% } %><% for (relationshipId in relationships) {
            if (relationships[relationshipId].relationshipType == 'many-to-one'
               || (relationships[relationshipId].relationshipType == 'one-to-one' && relationships[relationshipId].ownerSide == true)) { %>
        <th translate="<%= keyPrefix + relationships[relationshipId].relationshipName%>"><%=relationships[relationshipId].relationshipName%></th><% } } %>
        <th></th>
    </tr>
</thead>
```

to
```html
<thead>
    <tr>
        <th translate="global.field.id">ID</th>
        <%_ for (fieldId in fields) { _%>
        <th translate="<%=keyPrefix + fields[fieldId].fieldName %>"><%=fields[fieldId].fieldNameCapitalized%></th>
        <%_ } _%>
        <%_ for (relationshipId in relationships) { _%>
            <%_ if (relationships[relationshipId].relationshipType == 'many-to-one || (relationships[relationshipId].relationshipType == 'one-to-one' && relationships[relationshipId].ownerSide == true)) { _%>
        <th translate="<%= keyPrefix + relationships[relationshipId].relationshipName%>"><%=relationships[relationshipId].relationshipName%></th>
            <%_ } _%>
        <%_ } _%>
        <th></th>
    </tr>
</thead>
```

and the output will still be the same.

I think it could be a good idea to start using the space and tab slurping tags `<%_` and `_%>` as much as possible and avoid placing if-cases at end of lines.

**Comment by gmarziou** [comment]
Wow you're amazing and ejs project woners are very welcoming.

We may have to wait for ejs release and then yeoman release to integrate it.
Or maybe we could start using it earlier by using github url in package.json?

**Comment by jdubois** [comment]
Yes this is amazing!!!

**Comment by andidev** [comment]
I'm amazed as well how well open source works in the node network. It's really cool how one can contribute this easy.

@gmarziou
The only problem is that the ejs is included as a transitive dependency. But maybe it is possible to override those as well.
I'm not 100% sure but maybe we can start using the latest version of ejs without waiting for yeoman to release it. This is since they include their depedencies with the `^` notation which means 1.X.X realeases are automatically updated.

**Comment by deepu105** [comment]
awesome :+1:

**Comment by gmarziou** [comment]
I think we should close this issue by copy/pasting some of the explanations to the CONTRIBUTING.md file. I can do it.

**Comment by jdubois** [comment]
@gmarziou yes OK! I still need to get used to those, but it's really cool!

**Comment by jdubois** [comment]
@gmarziou can you add the documentation to the CONTRIBUTING.md ?

I'm closing this as indeed we have a great solution.

I think we might need to redo all the templates for JHipster 3.0, anyway if we remove Java 7 support there will be a huge simplification work to do.

**Comment by deepu105** [comment]
Yes agree lets redo for 3.0 currently we use too much inline coding in
templates which can be simplified to methods in the index.js and we should
really split index js into mutiple sub files.
Also we need to remove over usage of the this keyword.
Shall I open a 3.0 ticket for this task and add to future milestone?

**Comment by gmarziou** [comment]
OK, I'll add documentation
