### ISSUE TITLE
"type": "https://www.jhipster.tech/problem/problem-with-message",     "title": "Internal Server Error",     "status": 500,     "detail": "Cannot invoke \"de.almaphil.alpharepository.web.rest.UserSettingsResource.getMobilityConfigForUser(java.lang.Long)\" because \"this.userSettingsResource\" is null",     "path": "/api/user/%7BuserId%7D/mobility-config",     "message": "error.http.500"

### ISSUE THREAD

**Issue by 99Farhan** [jhipster/generator-jhipster#17518]
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by 99Farhan** [comment]
pls help me with this  
how to do i get data of two repository in a class

**Comment by atomfrede** [comment]
Can follow the issue template and provide the requested information? Otherwise no one will be able to provide any help.

**Comment by deepu105** [comment]
please reopen after following the issue guidelines
