### ISSUE TITLE
update generated entity with added options

### ISSUE THREAD

**Issue by seghers** [jhipster/generator-jhipster#1754]
When I look at my project I see 20+ entity.json files that are outdated since I added them months ago. Is there an easy way to update/add new options to an old generated entity.json (or in batch for all entities)
Only modifying the .json and not auto running the entity sub-generator.

eg. 

        {
            "fieldId": 5,
            "fieldName": "country",
            "fieldType": "String",
            "fieldNameCapitalized": "Country",
            "fieldNameUnderscored": "country"
        },

to

        {
            "fieldId": 5,
            "fieldName": "country",
            "fieldType": "String",
            "fieldNameCapitalized": "Country",
            "fieldNameUnderscored": "country",
            "fieldInJavaBeanMethod": "Country",
            "fieldValidate": false
        },

**Comment by gmarziou** [comment]
The only solution is to re-run 'yo jhipster:entity' with same entity name and do manual merges which can be tedious if you have modified a lot your entities manually since generation.

**Comment by MatthieuLebigre** [comment]
A nice to have would be a tool (generator option ?) to update entity.json files, but it would be also difficult to implement/maintain.
Maybe a documentation of the changes between each version would help.
I had also some trouble when upgrading jhipster on existing app : the app itself is not that difficult to upgrade (run yo jhipster, and with git it's easy to merge the changes), but for the entities, it can be really painful to regenerate them.
And I think JHipster should made things easier when upgrading existing app with newer versions of jhipster

**Comment by jdubois** [comment]
Yes, I agree this is an issue.

The current solution is to do like @gmarziou -> just re-run the generator, like explained in the documentation

And as @MatthieuLebigre says it's often not very difficult, I do it all the time.

Anyway, in the future I do hope that those files get refactored (like in #1753 like @andidev says) so they are easier to upgrade.
