### ISSUE TITLE
A default date format filter needed in AngularJS code

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#1755]
This is an enhancement request.

When a date or time data type is generated in the front end, it should come with a default format filter.  Otherwise, a date or time will show up in a format based on the browser interpretation and a same date field can appear differently on different browsers.

**Comment by renancunha** [comment]
@vw98075 @jdubois I used the default date filter of the angular to solve this. Currently the generator prints the plain text that was received by the server.

By default, for fields of LocalDate type I format using the "shortDate" pattern ("M/d/yy") and for fields of DateTime type I used the "short" pattern ("M/d/yy h:mm a").

Remembering that these standards (short, shortDate etc) are defined by the angular localization system (ie.: for "pt-br" language, shortDate is "dd/MM/yy") and that user can manually change this (in the generated entity files) patterns for whatever he wants.

If you agree with this I can make an PR.

Thanks,
Renan.

**Comment by vw98075** [comment]
Thanks for looking into this issue. Will the default format be fixed or vary based on locale?

**Comment by renancunha** [comment]
@vw98075 varies based on locale. The app loads an locale file with these definitions according with current language.

Here is the file when the current language is english:
https://github.com/angular/bower-angular-i18n/blob/master/angular-locale_en.js

All these files are already included in the project.

**Comment by deepu105** [comment]
Is anyone willing to work on this?

**Comment by atomfrede** [comment]
I can do it. I guess we should use the standard angular date filter and not something like moment.js

**Comment by deepu105** [comment]
@atomfrede can I suggest we do something like the below so that within an application the dateformat can be easily changed by each application requirement instead of changing at every entity page. this will give the developer more control rather than we dictating what date format to use

create a default date filter as below and inject angular dateFilter:
set any default format from standard angular format
```
.filter('appNameDate', function(dateFilter) {
        return function(theDate) {
           return dateFilter(theDate, 'dd-MMM-yyyy');
        }
    })
```

**Comment by atomfrede** [comment]
Sounds good. Need to check how to handle it with the datepicker. But I guess I'll open a new ticket for adding the date picker.

**Comment by gmarziou** [comment]
The date format could also be stored in global.json so that it can be configured per locale.

**Comment by deepu105** [comment]
Thats better I guess

**Comment by jdubois** [comment]
Sorry I didn't follow that: if you all agree, let's do it :-)

**Comment by deepu105** [comment]
@atomfrede how about we replace ui-bootstrap with http://mgcrea.github.io/angular-strap/ it has nice datepickers and a more polished set of widgets plz take a look

**Comment by mraible** [comment]
I recently noticed that I had to add date filters with timezones to get dates to look good and render properly with generated entities. Is this a known issue? For example:

    {{weight.timestamp | date: 'medium': 'UTC'}}

**Comment by deepu105** [comment]
I have used date filters a lot, that too custom date filters extending
angular, but I have used timezone property only when i had to show the date
in UTC, for local it works well without timezone. Im on angular 1.4.x btw
In my apps the behavior is as below

1. I use a custom directive on top of ui-bootstrap datepicker/timepicker to
select dates
2. In DB these are automatically being saved in UTC time by Jhipster
default config
3. when I display dates back its either in a disabled datepicker directive
or in a normal text span with custom date filter without a timezone, here
the dates are automatically converted back to the local time
4. in some places my client wants the time in UTC so i use a filter with
timezone set

so far havent had any issues, i might have used more than 300~ date fields

On Mon, Nov 9, 2015 at 2:49 AM, Matt Raible <notifications@github.com>
wrote:

> I recently noticed that I had to add date filters with timezones to get
> dates to look good and render properly with generated entities. Is this a
> known issue? For example:
>
> {{weight.timestamp | date: 'medium': 'UTC'}}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1755#issuecomment-154857166>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by jdubois** [comment]
OK we have had this long-running issue on dates, and it's mostly my fault as I didn't want to add too many external libraries.
As we now use UI Bootstrap for pagination, etc, let's also use it for dates:

- That will (hopefully) solve this issue
- This means we would have a date picker for people not using Chrome
- And @deepu105 I've looked at AngularStrap: looks good, but it's only half as popular as UI Bootstrap, and I don't want to have yet another library...

**Comment by mraible** [comment]
Here's how I've integrated bootstrap-datepicker: http://stackoverflow.com/a/28143209/65681

**Comment by jdubois** [comment]
Thanks @mraible in fact it just took me 5 minutes to have it working... I'm currently tweaking it and having a look at how to make this into a template, that's the most difficult part!
