### ISSUE TITLE
Vue client: Web resource cache invalidation is not working

### ISSUE THREAD

**Issue by roh0sun** [jhipster/generator-jhipster#17573]
##### **Overview of the issue**

After 7.4.1, Webpack output option doesn't includes contenthash filename.
So cache invalidation is not working.
Also missing in MiniCssExtractPlugin too.

##### **Motivation for or Use Case**

Cache invalidation is not working for Vue client apps.

##### **Reproduce the error**

Generate a new app with Vue client option.

##### **Suggest a Fix**

Need to declare contenthashed filename options like React client.

in generators/client/templates/vue/webpack/webpack.common.js.ejs
```
      output: {
        path: resolve('<%= DIST_DIR %>'),
->      filename: 'app/[name].[contenthash].bundle.js',
->      chunkFilename: 'app/[name].[chunkhash].chunk.js'
      },
```

in generators/client/templates/vue/webpack/webpack.prod.js.ejs
```
    new MiniCssExtractPlugin(
->{
->   filename: 'content/[name].[contenthash].css',
->   chunkFilename: 'content/[name].[chunkhash].css'
->}
    ),
```

These were there befoere 7.4.1.

##### **JHipster Version(s)**

7.4.1+

##### **JHipster configuration**

```
{
  "generator-jhipster": {
...
    "clientFramework": "vue",
...
  }
}
```

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@roh0sun looks like you know how to fix. Can you provide the PR?

**Comment by roh0sun** [comment]
> @roh0sun looks like you know how to fix. Can you provide the PR?

I think I don't know how the Webpack works sufficiently.
Actually, I don't know anything about webpack.
I just pointed recent changes and Vue/React differencies.
