### ISSUE TITLE
Browsersync not updating web after upgrading to 7.5.0 with Angular

### ISSUE THREAD

**Issue by CarlosVallsCiscar** [jhipster/generator-jhipster#17571]
##### **Overview of the issue**
After updating my monolith app to 7.5.0 the hot reload has stopped working.

This message appears in the console every few seconds and the web is never updated:
```
WebSocketClient.js:13 WebSocket connection to 'ws://localhost:9000/ws' failed: 
WebSocketClient @ WebSocketClient.js:13
```

##### **Motivation for or Use Case**
Main feature stops working.

##### **Reproduce the error**
I have created a new project and still have the same problem.

##### **Related issues**
Not found

##### **Suggest a Fix**
-

##### **JHipster Version(s)**
7.5.0

#### **JHipster Version(s)**

```
bse@0.0.1-SNAPSHOT /Users/{user}/Desktop/bse
└── generator-jhipster@7.5.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "bse",
    "jhipsterVersion": "7.5.0",
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1642334731246,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "es",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "enableGradleEnterprise": false,
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7-27)
OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

git version 2.29.2

node: v16.13.1

npm: 8.1.2

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
-

##### **Browsers and Operating System**
Mac OS 12.1
Google Chrome 96.0.4664.110

**Comment by qmonmert** [comment]
@pascalgrimaud I confirm bug

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's a bug

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/61430 ;)

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
