### ISSUE TITLE
Duplicate Oath2 Tokens Created

### ISSUE THREAD

**Issue by myspivey** [jhipster/generator-jhipster#1759]
Sporadically getting duplicate tokens with heavy use. Appears to be the following issue, https://github.com/spring-projects/spring-security-oauth/issues/276

**Comment by myspivey** [comment]
Also came across this, https://github.com/spring-projects/spring-security-oauth/issues/463.

Looks like step one of the fix is making sure that authentication_id in oauth_access_token is unique. The second being to retry the request on DuplicateKeyException.

**Comment by jdubois** [comment]
Fixed by #1782
