### ISSUE TITLE
Problem with DTO - MapStruct

### ISSUE THREAD

**Issue by vitornobrega** [jhipster/generator-jhipster#1760]
I generated a single entity without relations and select DTO with MapStruct. When i run the application, i get an error NoSuchBeanDefinition for the new mapper.

Here is a printscreen with the log.
http://prntscr.com/7vzak7

This feature is working??

**Comment by Vaelyr** [comment]
You have to run your application with mvn spring-boot:run or add processor:process goal to your launch script or just run it once.

**Comment by jdubois** [comment]
Yes @Vaelyr is correct you need to have the post-processing phase to run -> maybe we should document it better?

**Comment by vitornobrega** [comment]
yes, the document should explain that when you run program with Main class
