### ISSUE TITLE
Application hangs when hasAnyAuthority function is used multiple times on same page with different role :- VueJS

### ISSUE THREAD

**Issue by jonyhartron** [jhipster/generator-jhipster#17627]
**Describe the bug**
Using Vue as UI, the browser is getting hanged when using hasAnyAuthority function on multiple places on single vue page with different roles.

**To Reproduce**

1. Create jhipster monolith application using VueJS for frontend.
2. Go to jhi-navbar.vue file
3. Copy the line v-if="hasAnyAuthority('ROLE_ADMIN') && authenticated" and use this to somewhere else like Home nav-item. Just make sure to change the 'ROLE_ADMIN' to 'ROLE_USER' amd save it.
4. Refresh the browser. Login using default user (login - user, pwd - user) and thats it, The browser is hang.
5. Expected behavior

What i have observed is that the hasAnyAuthrity function recalls itself again and again upto infinite due to which the browser gets hangled.

- OS: Ubuntu
- Browser chrome

**Comment by tomaytotomato** [comment]
I this this might be related to my issue?

https://github.com/jhipster/generator-jhipster/issues/17640

**Comment by qmonmert** [comment]
@pascalgrimaud I confirm the bug

**Comment by qmonmert** [comment]
@jonyhartron in your case, you can use this code (not optimal at all... but it works):

```
  private hasAdminAuthorityValue = false;
  private hasUserAuthorityValue = false;
  ...
  public hasAnyAuthority(authorities: any): boolean {
    this.accountService()
      .hasAnyAuthorityAndCheckAuth(authorities)
      .then(value => {
        if (authorities === 'ROLE_ADMIN') {
          this.hasAdminAuthorityValue = value;
        } else if (authorities === 'ROLE_USER') {
          this.hasUserAuthorityValue = value;
        }
      });
    if (authorities === 'ROLE_ADMIN') {
      return this.hasAdminAuthorityValue;
    } else if (authorities === 'ROLE_USER') {
      return this.hasUserAuthorityValue;
    }
  }
```

**Comment by mraible** [comment]
Does anyone have a diff we can use to fix this issue?

**Comment by jonyhartron** [comment]
> @jonyhartron in your case, you can use this code (not optimal at all... but it works):
> 
> ```
>   private hasAdminAuthorityValue = false;
>   private hasUserAuthorityValue = false;
>   ...
>   public hasAnyAuthority(authorities: any): boolean {
>     this.accountService()
>       .hasAnyAuthorityAndCheckAuth(authorities)
>       .then(value => {
>         if (authorities === 'ROLE_ADMIN') {
>           this.hasAdminAuthorityValue = value;
>         } else if (authorities === 'ROLE_USER') {
>           this.hasUserAuthorityValue = value;
>         }
>       });
>     if (authorities === 'ROLE_ADMIN') {
>       return this.hasAdminAuthorityValue;
>     } else if (authorities === 'ROLE_USER') {
>       return this.hasUserAuthorityValue;
>     }
>   }
> ```

@qmonmert yes using different field for each role resolves the issue, but i was wondering there must be better way, as adding more roles will add more checks.

**Comment by emilpaw** [comment]
@jonyhartron Does this work for you?

**Comment by jonyhartron** [comment]
> 

yes it worked for me
