### ISSUE TITLE
Look at some Jhipster third party dependencies to sponsor

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#17641]
You all know that Jhipster is well sponsored by backers and that this project is a lucky one.

Community may look at Jhipster third party dependencies that are struggling to find funds and sponsor them back.

Do you have some ideas regarding dependencies that are in this situation?
Please raise your hand if you are in that situation.

**Comment by pascalgrimaud** [comment]
I think about Mongock project -> https://github.com/mongock/mongock

See https://github.com/jhipster/generator-jhipster/pull/16787#issuecomment-1002700136

Cc @dieppa

**Comment by dieppa** [comment]
First of all thanks for this, @pascalgrimaud and @Tcharl. We(@oliver, @dhivesh and myself) really appreciate you taking Mongock into account for this.

The timing for this is great as we are actually working in adding our sponsorship model. We expect to have it available next week...Our  backlog is growing at pace and we are committed  to keep up with the market needs, grow the community of contributors further, etc.

Let us know what you need and how we can help... and thanks again for taking us into account.

**Comment by pascalgrimaud** [comment]
Following this:
- https://twitter.com/MongockTeam/status/1492149518305054720
- https://github.com/mongock/mongock/releases/tag/mongock-5.0.36

How can we progress on this @jdubois @deepu105 @mraible ?
Maybe adding a bounty for this ? as the reactive part for MongoDB was done and we can use it in generator-jhipster

**Comment by dieppa** [comment]
@pascalgrimaud [this](https://docs.mongock.io/v5/driver/mongodb-reactive/index.html) may be helpful.

None one from Mongock team really knows how JHipster's generator works, but if we can help, let us know.

**Comment by mraible** [comment]
@pascalgrimaud Let's create a couple issues and add bug bounties to them. Maybe one for adding reactive support to Mongock and another for integrating it into JHipster?

**Comment by mshima** [comment]
Would be nice if someone could fix the mongodb bug with primary keys that is preventing us to migrate to >= v4.3.0.
https://github.com/jhipster/jhipster-bom/pulls?q=is%3Apr+mongodb+is%3Aclosed

**Comment by mraible** [comment]
@mshima Can you create an issue for ^^ so we can assign a bug bounty to it?
