### ISSUE TITLE
Remove fake data or find an alternative for faker.js

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#17649]
Since the faker.js library is no longer maintained we should either drop the feature or find alternative for v8

**Comment by vishal423** [comment]
I believe there is an official fork of same. We should instead migrate to that in next minor/patch release

**Comment by gmarziou** [comment]
You mean this one? https://github.com/faker-js/faker

I just discovered this story, I'm glad JHipster pins exact versions to protect its users.

**Comment by pascalgrimaud** [comment]
> I'm glad JHipster pins exact versions to protect its users

Agree, that's why it's so important to use exact versions

**Comment by DanielFran** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/17669
