### ISSUE TITLE
It's broken.

### ISSUE THREAD

**Issue by pulkitnandan** [jhipster/generator-jhipster#1766]
On a fresh windows 10 machine I have installed, node, npm, bower, yo, jhipster and yo jhipster closes cmd in which it was launched. Nothing fancy to do for this bug reproduction. It exits withouth exception error and nothing generated.

**Comment by pulkitnandan** [comment]
Tested same in original windows 7. Same effect.

**Comment by gmarziou** [comment]
Help us to help you by providing more information: 

   node -v
   yo doctor

Does it fail the same when you run another yeoman generator like

   npm install -g generator-angular
   yo angular

**Comment by jdubois** [comment]
@gmarziou is right -> we need more information than "it's broken", did you read our guidelines before sending this ticket? I'll reopen this if you send those informations.

Our stats do show that no ones uses JHipster with Windows 10, and I don't even know if node and all its dependencies are supported on Windows 10. Anyway, as it also doesn't work on Windows 7 you probably have some other error (FYI Windows 7 was our top OS last month, with 25% of users!)

**Comment by pulkitnandan** [comment]
Try this on any system with slow internet connection. It seems to be a issue of node on windows 10. Please check your stats back again as I've installed it like 20 times on windows 10 and it failed every time.

**Comment by gmarziou** [comment]
Then it should fail for any other yeoman generator as well as any other gradle build when it resolves dependencies the first time. Sorry but there's nothing we can do to help you.

**Comment by pulkitnandan** [comment]
On this "Linux ip-172-31-31-37 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
" machine it fails again.


ubuntu@ip:~$ npm cache clean && npm install yo

> spawn-sync@1.0.13 postinstall /home/ubuntu/node_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

-
> yo@1.4.7 postinstall /home/ubuntu/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✔ NODE_PATH matches the npm root

Everything looks all right!
yo@1.4.7 node_modules/yo
├── titleize@1.0.0
├── array-uniq@1.0.2
├── figures@1.3.5
├── user-home@1.1.1
├── async@1.4.2
├── opn@1.0.2
├── humanize-string@1.0.1 (decamelize@1.0.0)
├── sort-on@1.2.2 (arrify@1.0.0, dot-prop@2.2.0)
├── yeoman-character@1.0.1 (supports-color@1.3.1)
├── string-length@1.0.1 (strip-ansi@3.0.0)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── root-check@1.0.0 (downgrade-root@1.1.0, sudo-block@1.2.0)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── repeating@1.1.3 (is-finite@1.0.1)
├── meow@3.3.0 (object-assign@3.0.0, camelcase-keys@1.0.0, minimist@1.1.3, indent-string@1.2.2)
├── yosay@1.0.5 (ansi-regex@1.1.1, ansi-styles@2.1.0, word-wrap@1.1.0, pad-component@0.0.1, strip-ansi@2.0.1, taketalk@1.0.0, minimist@1.1.3, string-width@1.0.1)
├── configstore@1.2.1 (os-tmpdir@1.0.1, object-assign@3.0.0, graceful-fs@4.1.2, uuid@2.0.1, xdg-basedir@2.0.0, osenv@0.1.3, write-file-atomic@1.1.2, mkdirp@0.5.1)
├── package-json@1.2.0 (registry-url@3.0.3)
├── npm-keyword@1.2.0 (registry-url@3.0.3)
├── update-notifier@0.5.0 (is-npm@1.0.0, latest-version@1.0.1, semver-diff@2.0.0)
├── got@3.3.1 (lowercase-keys@1.0.0, is-stream@1.0.1, timed-out@2.0.0, is-redirect@1.0.0, prepend-http@1.0.2, object-assign@3.0.0, infinity-agent@2.0.3, nested-error-stacks@1.0.1, read-all-stream@3.0.1, duplexify@3.4.2)
├── fullname@1.1.0 (npmconf@2.1.2)
├── cross-spawn@0.4.1 (lru-cache@2.6.5, spawn-sync@1.0.13)
├── yeoman-environment@1.2.7 (escape-string-regexp@1.0.3, log-symbols@1.0.2, diff@1.4.0, text-table@0.2.0, untildify@2.1.0, debug@2.2.0, mem-fs@1.1.0, globby@2.1.0, grouped-queue@0.3.0)
├── insight@0.6.0 (object-assign@2.1.1, lodash.debounce@3.1.1, async@0.9.2, os-name@1.0.3, tough-cookie@1.2.0, request@2.60.0)
├── lodash@3.10.1
├── yeoman-doctor@1.4.0 (log-symbols@1.0.2, object-values@1.0.0, each-async@1.1.1, semver@4.3.6, bin-version-check@2.1.0, twig@0.8.2)
└── inquirer@0.8.5 (ansi-regex@1.1.1, cli-width@1.0.1, through@2.3.8, readline2@0.1.1, rx@2.5.3)
ubuntu@ip:~$ yo jhipster
module.js:338
    throw err;
          ^
Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/index.js:6:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by gmarziou** [comment]
npm cache clean && npm install yo
