### ISSUE TITLE
Release all sample projects

### ISSUE THREAD

**Issue by assimbly** [jhipster/generator-jhipster#17677]
Currently, some sample projects are releases and available as tags. For example:

https://github.com/jhipster/jhipster-sample-app/tags
https://github.com/jhipster/jhipster-sample-app-react/tags

Not all sample repositories are however released/taged. Would be nice to have all generated sample projects available as tags (for easily downloading old versions and scripting purposes).

**Comment by assimbly** [comment]
Note that this can part of the CI/CD pipeline, but also JReleales (https://jreleaser.org/) has options for this.

**Comment by mshima** [comment]
We would need to create workflows to do that.
