### ISSUE TITLE
Blob issue

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#1769]
4 tests fail when creating an entity with 3 (blob) fields.

The original [issue](https://github.com/jhipster/jhipster-uml/issues/32).

**Here is the JSON file**, generated with JHipster (not JHipster-UML, but the result is the same):
{
    "relationships": [],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "myField",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldIsEnum": false,
            "fieldNameCapitalized": "MyField",
            "fieldNameUnderscored": "my_field",
            "fieldInJavaBeanMethod": "MyField",
            "fieldValidate": true,
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": "42"
        },
        {
            "fieldId": 2,
            "fieldName": "mySecondField",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldIsEnum": false,
            "fieldNameCapitalized": "MySecondField",
            "fieldNameUnderscored": "my_second_field",
            "fieldInJavaBeanMethod": "MySecondField",
            "fieldValidate": false
        },
        {
            "fieldId": 3,
            "fieldName": "myThirdField",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldIsEnum": false,
            "fieldNameCapitalized": "MyThirdField",
            "fieldNameUnderscored": "my_third_field",
            "fieldInJavaBeanMethod": "MyThirdField",
            "fieldValidate": true,
            "fieldValidateRules": [
                "required",
                "minbytes",
                "maxbytes"
            ],
            "fieldValidateRulesMinbytes": 0,
            "fieldValidateRulesMaxbytes": 5000000
        }
    ],
    "fieldsContainOwnerManyToMany": false,
    "fieldsContainOwnerOneToOne": false,
    "fieldsContainOneToMany": false,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": false,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": false,
    "fieldsContainDate": false,
    "fieldsContainBlob": true,
    "changelogDate": "20150726154418",
    "dto": "no",
    "pagination": "no",
    "validation": true
}

**The tests that fail are:**
  - getAllMyEntitys (would be nice to correct that spelling mistake with an inflexion module, will try to do a PR for it)
  - updateMyEntity
  - getMyEntity
  - deleteMyEntity

**The exception:**
javax.validation.ConstraintViolationException: Validation failed for classes [com.mycompany.myapp.domain.MyEntity] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='la taille doit être entre 42 et 2147483647', propertyPath=myField, rootBeanClass=class com.mycompany.myapp.domain.MyEntity, messageTemplate='{javax.validation.constraints.Size.message}'}
]

I will try to see what caused this error and fix it myself in the meantime.

**Comment by andidev** [comment]
@MathieuAA
Okay I see the problem. The test data in the test is always 3 bytes which violates the validation rules.

**Comment by andidev** [comment]
Have you started working on it already or should I fix it?

**Comment by andidev** [comment]
I started working on this so you know.

**Comment by MathieuAA** [comment]
Ok, good! I can't work at the moment anyway. Thanks.

**Comment by andidev** [comment]
This can be closed now, fixed by #1771
