### ISSUE TITLE
Invalid CSRF Token

### ISSUE THREAD

**Issue by slucky31** [jhipster/generator-jhipster#1772]
Hi,

I'm testing swagger and all the generated post failed with error 403 and message : 
> "Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'."

I'm using generator-jhipster v2.18.0
Here is my config : 

```
{
  "generator-jhipster": {
    "baseName": "ComicsManAdmin",
    "packageName": "net.ndt.comicsman.admin",
    "packageFolder": "net/ndt/comicsman/admin",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "myKey"
  }
}
```

**Comment by gmarziou** [comment]
Did you login as admin before going to the swagger URLs?

**Comment by slucky31** [comment]
Yes login as admin.

I try to create an instance of an entity create with jhipster-uml

For the URL, see the following images
![capture1](https://cloud.githubusercontent.com/assets/2489283/8909058/c373bd98-347f-11e5-8a65-53fdfedb48d6.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2489283/8909064/c56b2668-347f-11e5-9fd6-38ebd03063b4.PNG)
![capture3](https://cloud.githubusercontent.com/assets/2489283/8909066/c723fad4-347f-11e5-9707-28249f1fbe69.PNG)

**Comment by jdubois** [comment]
Isn't this a duplicate of #1731 ?

**Comment by slucky31** [comment]
I don't think so. The user resource : GET /api/users is Ok for me in Swagger Docs.

**Comment by gmarziou** [comment]
I have a solution but I'd like to have a solution that works also for  #1731 before a PR.
