### ISSUE TITLE
Logged in user can access and register a new user

### ISSUE THREAD

**Issue by lluiscanals** [jhipster/generator-jhipster#1773]
When logged in you should not have access to the new user registration view.

**Comment by jdubois** [comment]
Yes -> that's not really a security issue, but it's not very logical, I agree

**Comment by atomfrede** [comment]
@Falydoor Can you create a PR for your fix?

**Comment by Falydoor** [comment]
Let me know if my fix is fine as I begin with angular.

I denied the access to the login page too.
