### ISSUE TITLE
AbstractAuditingEntity not working for update for entities with dto

### ISSUE THREAD

**Issue by krishnakumarp** [jhipster/generator-jhipster#1774]
I tried to use the generated AbstractAuditingEntity to add audit fields to one of the application's entity. The update use case did not work correctly. It was failing with a constraint violation error that createdBy cannot be null. This property is marked as @NotNull in the generated class. But this field will be null in the update mode. 

I'd to change this class to modify the definitions of createdBy and createdAt to fix this issue.

    @CreatedBy
    @Column(name = "created_by", nullable = false, length = 50, updatable = false)
    @JsonIgnore
    private String createdBy;
    
    @CreatedDate
    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    @Column(name = "created_date", nullable = false, updatable = false)
    @JsonIgnore
    private DateTime createdDate = DateTime.now();

If this is correct, please update the generator to work correctly.

**Comment by gzsombor** [comment]
What cleared out the 'createdBy' field? It should be there, when it's retrieved from the database.

**Comment by krishnakumarp** [comment]
I mask these fields out in dto layer. It is normal not to pass these audit fields to dto and back. You dont want to update created_* fields with updates. So these fields should be marked as updatable=false and should  not have @NotNull

**Comment by gzsombor** [comment]
Yes, sure, you dont want to put that fields into a DTO, and blindly update it. It's the drawback for using the same DTO for sending to the client, and receiving from the client.
 But, as we don't generate that auditing DTO for that entity, we can't put that ignore flags inside the mapstruct based mapper. 
 I don't think it would be a wise decision, to mark the entity's created_ field as it can be null. We don't want to accidentally remove that information from the database.

**Comment by krishnakumarp** [comment]
But we will not update it accidentally, once we mark it as , updatable = false. No? 
While creating entity it is populated by AuditingEntityListener, so no chance of that being null. 
Minimally, we could mark those fields as updatable = false.

**Comment by gzsombor** [comment]
yes, that would make sense

**Comment by jdubois** [comment]
So this is specific to using DTOs:

- can you update the title of the ticket to reflect this? (I can't do it with the mobile app)
- @gzsombor I'm not sure I understand the solution correctly, could you do a PR or write à small exemple?

**Comment by jdubois** [comment]
- If you use DTOs, I fully agree you probably don't want to expose those fields
- Then it's up to you, in your mapping, to update them correctly

I don't think we should change the existing behavior, then this has been opened for a long time and I don't find this issue very clear -> this is why I'm closing this

If you have something more detailed, with maybe a PR or some sample code that demonstrates your issue (including the mapping code), it would be most welcomed.
