### ISSUE TITLE
CRUD front-end not generated for embedded entity.

### ISSUE THREAD

**Issue by CGarces** [jhipster/generator-jhipster#17756]
##### **Overview of the issue**

I'm using the "one-to-many relationship" sample for embedded entities as documented at https://www.jhipster.tech/managing-relationships/#embedded-entities-for-couchbase-and-mongodb

JHipster not generates the CRUD code for the embedded entity.

Just generate the code for "country", and "Region" is included in the model, but not used.

##### **Motivation for or Use Case**

Just testing the mongoDB features.

##### **Reproduce the error**

generate a monolithic mongoDB project with Angular as front-end

##### **JHipster Version(s)**

7.5.0

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "testmongo",
    "jhipsterVersion": "7.5.0",
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1643794606492,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": false,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "es",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "enableGradleEnterprise": false,
    "languages": ["en", "fr"],
    "entities": ["Country", "Region"],
    "lastLiquibaseTimestamp": 1643797299000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Country {
  countryName String
}
entity Region {
  regionName String
}
relationship OneToMany {
  Country{region} to Region{country}
}

embedded Region

</pre>
</details>

##### **Environment and Tools**

java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

git version 2.30.1.windows.1

node: v14.16.0

npm: 6.14.11

Docker version 20.10.11, build dea9396

docker-compose version 1.29.2, build 5becea4c

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vrijmetse** [comment]
I guess I am not the only one, I faced the same error with `Reactive` and  `Microservices`

```
application {
  config {
    baseName gateway
    applicationType gateway
    packageName org.brix.ee
    authenticationType jwt
    clientFramework react
    prodDatabaseType mongodb
    devDatabaseType mongodb
    databaseType mongodb
    searchEngine elasticsearch
    serviceDiscoveryType no
    buildTool gradle
    cacheProvider hazelcast
    enableSwaggerCodegen true
    reactive true
  }
  entities *
  dto * with mapstruct
}


application {
  config {
    baseName core
    applicationType microservice
    packageName org.brix.ee
    authenticationType jwt
    prodDatabaseType mongodb
    devDatabaseType mongodb
    databaseType mongodb
    serviceDiscoveryType no
    skipUserManagement true
    buildTool gradle
    serverPort 8081
    cacheProvider redis
    enableSwaggerCodegen true
    reactive true
  }
  entities *
  dto * with mapstruct
}

entity Country {
  countryName String
}

@embedded
entity Region {
  regionName String
}


relationship OneToOne {
  Country{region} to Region{country}
}

```

**Comment by Frast83** [comment]
I have the same issue with jhipster 7.8.1 MongoDB and Angular in a monolith project.

**Comment by CSC-Sendance** [comment]
Facing the same issue for jhipster 7.8.1 MongoDB in a microservice-style application/architecture.

**Comment by DevGirondin** [comment]
I have the same issue with jhipster 7.9.3 MongoDB and Angular in a monolith project.

**Comment by AllenSML** [comment]
I have the same issue with jhipster 7.9.3 MongoDB and Angular in a monolith project

**Comment by CrackerJDK94** [comment]
looks like they don't care about mongodb it must be because this is an obvious bug.

**Comment by CrackerJDK94** [comment]
Looks like they don't care about mongodb then right. Because this is an obvious error.

**Comment by Murik** [comment]
Still the same issue on jhipster 8.2.1. mongoDB with both anfular and vui.
