### ISSUE TITLE
Add possibility, during the generation, to embed Keycloak into spring

### ISSUE THREAD

**Issue by brandonfl** [jhipster/generator-jhipster#17758]
##### **Overview of the feature request**

For the default OpenID Connect server that is Keycloak, I see that it was possible to embed a Keycloak server into Spring.
Here is the article related : [https://www.baeldung.com/keycloak-embedded-in-spring-boot-app](https://www.baeldung.com/keycloak-embedded-in-spring-boot-app)

I think it can be a good addition for people using, for example, monolithic application as it simplify the project

##### **Motivation for or Use Case**

- Simplify monolithic projects
- Faster setup / dev for monolithic projects
- Possibility to use the monolithic project + Keycloak without having to install docker

##### **Related issues or PR**

None

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I'm not sure this is a good idea. It would prevent an app from switching to another OIDC provider. If it's possible to configure it AND still allow switching to another provider, I'll consider it.
