### ISSUE TITLE
Architecture test failure with skip user management option

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#17757]
##### **Overview of the issue**
If you generate a new application with skip user management option, then, the generated application has Junit test failure related to Architecture tests.
Refer build # https://github.com/jhipster/generator-jhipster-svelte/runs/4917371747?check_suite_focus=true#step:13:577 for error details

Refer JDL at https://github.com/jhipster/generator-jhipster-svelte/blob/main/.github/workflows/scripts/monolithic-jwt-maven-skip-user.jdl

##### **Motivation for or Use Case**
Prevents migration of svelte blueprint to use `7.6.0` JHipster release.

##### **JHipster Version(s)**
7.6.0

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Removing the service layer from the ArchitectureTest can be problematic, since it's possible to add an entity with service on an existing project.
@codecholeric is there a way to ignore empty groups?

**Comment by codecholeric** [comment]
@mshima there is a method `optionalLayer(..)` (see https://www.javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/library/Architectures.LayeredArchitecture.html#optionalLayer(java.lang.String) ). If you define the layer this way it may be empty...

**Comment by atomfrede** [comment]
As the PR is merged, we can close this I think.
