### ISSUE TITLE
Fix deprecated property that allows circular references

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#17774]
##### **Overview of the issue**

When upgrading to Spring Boot 2.6, we had to set the following properties. I believe the former (`allow-bean-definition-overriding`) was already there and might be necessary. The second one that allows circular references seems like a bug.

```yaml
spring:
  ...
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
```

##### **Motivation for or Use Case**

When trying to upgrade Spring Native with the latest release, I received this error that prevented me from using Liquibase.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase':
 Circular depends-on relationship between 'liquibase' and 'entityManagerFactory'
```

See [my updated README](https://github.com/mraible/spring-native-examples/pull/4/files#diff-1194561cbea346acb1bea37d81fdf5c70def982dcbb0c64eca2a96bc51941124R223) for more information.

Liquibase worked when I [last tried to integrate Spring Native](https://www.linkedin.com/pulse/jhipster-works-spring-native-part-2-matt-raible/). 

##### **Reproduce the error**

Change `src/main/resources/config/application.yml` to remove the `allow-circular-references` property. Start the app and watch it fail. Or just use the following steps:

```
git clone -b jhipster-7.6 https://github.com/mraible/spring-native-examples.git
cd spring-native-examples/spring-native-mvc
# update src/main/resources/config/application.yml to remove allow-circular-references
./mvnw spring-boot:run
```

##### **JHipster Version(s)**

```
jhipster@0.0.0 /Users/mraible/dev/spring-native-examples/spring-native-mvc
└── generator-jhipster@7.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "jhipster",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "no",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1632844293562,
    "databaseType": "no",
    "devDatabaseType": "no",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.6.0",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "monorepository": true,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "no",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": true,
    "skipCommitHook": true,
    "skipFakeData": false,
    "skipServer": false,
    "skipUserManagement": true,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

git version 2.32.0 (Apple Git-132)

node: v16.13.2

npm: 8.1.2

Docker version 20.10.12, build e91ed57

Docker Compose version v2.2.3

**Comment by mraible** [comment]
Bumping from 200 to 500.

**Comment by mshima** [comment]
Will try to fix this.

**Comment by mshima** [comment]
@DanielFran  bounty claimed https://opencollective.com/generator-jhipster/expenses/100751.

**Comment by DanielFran** [comment]
@mshima approved
