### ISSUE TITLE
The filters / criteria are no longer supported in Swagger (Spring Docs)

### ISSUE THREAD

**Issue by Akuka** [jhipster/generator-jhipster#17776]
##### **Overview of the issue**

The filters / criteria are no longer supported in Swagger (Spring Docs)

This is how it was at JHipster v7.4.1 (and in the official docs https://www.jhipster.tech/entities-filtering/)
![image](https://user-images.githubusercontent.com/3299903/152358448-c9c6e996-10b7-4e80-bb93-2b007710e0c6.png)

This is how it looks like at JHipster v7.5.0 or v7.6.0:
![Screen Shot 2022-02-03 at 16 14 13](https://user-images.githubusercontent.com/3299903/152359680-f6491e8a-486b-493b-a374-f04e2233f727.png)

The Issue detected after upgrade from JHipster v7.4.1 to v7.5.0 (or higher) 

Maybe cause by the migration from springfox to springdoc: https://github.com/jhipster/generator-jhipster/pull/17194

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/17175

##### **Suggest a Fix**

I have tried to add `@org.springdoc.api.annotations.ParameterObject` before the criteria (the same as `Pageable`), its a bit better but still not good (swagger not detecting the type of the objects, he thinks everything is object):
![image](https://user-images.githubusercontent.com/3299903/152360469-0adc7cb5-de9b-416a-a32c-f0bdd99e56f9.png)

 

##### **JHipster Version(s)**

7.5.0 and higher

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
##### **JHipster Version(s)**

```
bookstore@0.0.1-SNAPSHOT /Users/akuka/dev/jhipster/demo
└── generator-jhipster@7.5.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "bookstore",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1632036929033,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": ["Author", "Book"],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.4.1",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.demo.bookstore",
    "pages": [],
    "prodDatabaseType": "mysql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipFakeData": false,
    "skipServer": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Author {
  name String required
}
entity Book {
  title String required
  price Float required min(0)
}
relationship ManyToOne {
  Book{author(name) required} to Author
}

paginate Author, Book with pagination
service Author, Book with serviceClass
filter Author, Book

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

git version 2.34.1

node: v16.13.2

npm: 8.1.2

Docker version 20.10.11, build dea9396

docker-compose version 1.29.2, build 5becea4c

Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
  "changelogDate": "20210916213554",
  "dto": "no",
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    }
  ],
  "jpaMetamodelFiltering": true,
  "name": "Author",
  "pagination": "pagination",
  "readOnly": false,
  "relationships": [],
  "service": "serviceClass"
}

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I can confirm the issue

**Comment by mshima** [comment]
Adding `@org.springdoc.api.annotations.ParameterObject` should be the fix and works, but springdoc is failing to determine the generic type.

**Comment by mshima** [comment]
The 2 linked PRs (https://github.com/springdoc/springdoc-openapi/pull/1491 and https://github.com/jhipster/generator-jhipster/pull/17791) should fix this bug.

**Comment by Akuka** [comment]
I will take a look
We have a fix as well, will post it soon

**Comment by mshima** [comment]
springdoc v1.6.6 was released with the fix.
It’s missing the annotation now.

**Comment by Akuka** [comment]
Looks great!

**Comment by mshima** [comment]
@Akuka do you want to do some more improvements to filter/criteria openapi support (like description) or this issue can be closed?

**Comment by Akuka** [comment]
Can be closed, thanks

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/100750.

**Comment by DanielFran** [comment]
@mshima approved
