### ISSUE TITLE
Remove the GZip filter code

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1778]
See https://github.com/jhipster/generator-jhipster/commit/88038652b395f3f78e415f4f442f30088ac5c08b#commitcomment-12397890 we might have some copyright issue here, so we need to recode this.

**Comment by gmarziou** [comment]
By the way, I always disbale it in prod because I always have a reverse proxy in front of my jhipster apps that does it.
Is it really useful?

**Comment by gzsombor** [comment]
At least 2, that I'm aware of :)

**Comment by gmarziou** [comment]
:) Is that internal apps?

**Comment by kutzi** [comment]
Even without a remote proxy, your application server can handle this already. At least Tomcat and Jetty can do it.
I've also removed the GzipFilter and just enabled it in Tomcat.

**Comment by gzsombor** [comment]
One of them is internal, one is external. 
Is is possible to switch on the gzip compression with spring-boot ? That would be awesome ...

**Comment by jdubois** [comment]
- If you have a frontend or an app server that can do the gzipping, then the filter isn't useful (obviously). It is here for "normal people" who are just running JHipster as a JAR file, and/or who don't want to configure such a feature
- We should propose to disable it as an option in our .yml file
- I thought that would be included in Spring Boot at some point, but it still isn't -> we have a stronger "production" focus than most people, this is also one of the big selling points of JHipster

**Comment by kutzi** [comment]
jdubois: but if you run JHipster from the JAR, it means that you're using an embedded Jetty (or Tomcat) and again can use their gzip support?

**Comment by jdubois** [comment]
@kutzi  yes but then you need to configure them:

- they can't be configured through Spring Boot (at least when I coded the filter)
- they have different implementations

Here the idea is that we have a common implementation, with a common configuration, that we can tune specifically for JHipster.

**Comment by kutzi** [comment]
For Tomcat we just do in application.yml:

server:
    tomcat.compression: 1024
    tomcat.compressableMimeTypes: "text/html,text/xml,text/plain,text/css,application/json,application/xml,application/javascript,image/svg+xml"

**Comment by jdubois** [comment]
@kutzi if that's configurable from the application.yml then it's really different, in that case we should use this (at the time I remember it wasn't possible).

My opinion is that we should:

- remove the GZIP filter
- use the configuration from @kutzi in the production application.yml file

**Comment by deepu105** [comment]
Seems to be possible with spring boot property so we can config in `.yml` file

[Spring Boot Properties](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)

```
server.tomcat.compression=off # is compression enabled (off, on, or an integer content length limit)
server.tomcat.compressable-mime-types=text/html,text/xml,text/plain # comma-separated list of mime types that Tomcat will compress
```

**Comment by gmarziou** [comment]
In fact [SB offers 2 possibilities](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#how-to-enable-http-response-compression)
- the server built-in one  showed by @kutzi 
- the one using a GZipFilter provided by the server which offers more control over URL mappings, ...

**Comment by deepu105** [comment]
But shouldn't we avoid adding a new dependency just for this so either
spring boot property or a custom gzip filter sounds better for me

**Comment by gmarziou** [comment]
i agree that we should be careful bringing in a new dependency so I looked at [jetty-servlets pom](https://github.com/eclipse/jetty.project/blob/master/jetty-servlets/pom.xml) and it has several deps on other jetty modules, so it could potentially cause problems.

So you're right, it's probably better to go for spring boot property, document it and in this doc section add few words on alternative using Jetty GZipFilter with a link to spring boot doc.

On the other hand, jetty-servlets pom implements several [useful filters](https://github.com/eclipse/jetty.project/tree/master/jetty-servlets/src/main/java/org/eclipse/jetty/servlets) like AsyncGZipFilter, CrossOriginFilter, DosFilter, ... that could be useful for JHipster production mode.

**Comment by deepu105** [comment]
can't we extract the needed stuff and make our own jar? its open source
right.

Even the current gzip filter what is the problem in using if its derived
from an open source ehcache implementation, the licence allows
copying,modifying and distributing. so i dont think we are violating
anything in the first place. and if we need to put in a notice on the class
that it is derived from ehcache what is the big deal?

On Thu, Aug 6, 2015 at 5:02 PM, Gaël Marziou <notifications@github.com>
wrote:

> i agree that we should be careful bringing in a new dependency so I looked
> at jetty-servlets pom
> <https://github.com/eclipse/jetty.project/blob/master/jetty-servlets/pom.xml>
> and it has several deps on other jetty modules, so it could potentially
> cause problems.
>
> So you're right, it's probably better to go for spring boot property,
> document it and in this doc section add few words on alternative using
> Jetty GZipFilter with a link to spring boot doc.
>
> On the other hand, jetty-servlets pom implements several useful filters
> <https://github.com/eclipse/jetty.project/tree/master/jetty-servlets/src/main/java/org/eclipse/jetty/servlets>
> like AsyncGZipFilter, CrossOriginFilter, DosFilter, ... that could be
> useful for JHipster production mode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1778#issuecomment-128298075>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by deepu105** [comment]
I would love to see Jhipster becoming a micro library as well, with useful utilities and less bloat, may be this should be part of our 3.0 discussion as well

**Comment by jdubois** [comment]
OK, so:

- let's remove our own GZip filter. I don't want to take any risk here: ehcache belongs now to Software AG, which is clearly not an Open Source friendly company.
- as we use Tomcat in our normal configuration, let's stick with the Tomcat conf. It's much easier, and doesn't provide any risk.
- yes in the future we might do our own library, but it would be in several months (probably)

**Comment by deepu105** [comment]
I dont know if its the gzip filter or the grunt prod optimizations but my client side resources served on load was 10+ MB in dev profile and it has reduced to 1.1 MB in prod profile. Thats just awesome

**Comment by jdubois** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/commit/595e89272cb5f28964eccba62026095c32f6a546
