### ISSUE TITLE
SpringDoc migration broke compatibility with OpenAPI Specification v2.0

### ISSUE THREAD

**Issue by bytejan** [jhipster/generator-jhipster#17790]
**Overview of the issue**

Since jhipster 7.5, the api first code generation does not work anymore since it uses swagger annotations that are not recognized by springdoc, for example ApiModelProperty

##### **Motivation for or Use Case**

Right now it is not possible to create an api first application.

##### **Reproduce the error**

1) Create a clean jhipster application (7.5 or 7.6), and select the option api first. 
2) Add paths tot he resources/swagger/api.yml file
3) Generate the application.

##### **Related issues**

No related issues

##### **Suggest a Fix**

No solution yet.

##### **JHipster Version(s)**

7.5 and 7.6

##### **JHipster Version(s)**

```
foxahead@0.0.1-SNAPSHOT /Users/jan-jaaparends/development/new-jhip-76
└── generator-jhipster@7.6.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "foxahead",
    "blueprints": [],
    "buildTool": "gradle",
    "cacheProvider": "no",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1643948708042,
    "cypressCoverage": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.6.0",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "nl"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.foxahead.gateway",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": ["websocket:spring-websocket", "enableSwaggerCodegen:true"],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": ["cypress", "gatling"],
    "websocket": "spring-websocket",
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)

git version 2.23.0

node: v14.16.1

npm: 6.14.12

Docker version 20.10.10, build b485636

docker-compose version 1.29.2, build 5becea4c

##### **Browsers and Operating System**

MacOs Monterey - Apple M1 chip

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
springdoc is OAS3 only.

**Comment by ShepelIgor** [comment]
I am facing the same issue, is there any update on it?

**Comment by pascalgrimaud** [comment]
you can still use the openapi-generator with JHipster, but after the generation, you need to update all annotations and imports, helped by https://springdoc.org/migrating-from-springfox.html

So it won't work out of the box but it's still usable

**Comment by naris** [comment]
> you can still use the openapi-generator with JHipster, but after the generation, you need to update all annotations and imports, helped by https://springdoc.org/migrating-from-springfox.html
> 
> So it won't work out of the box but it's still usable

So, what you have to manually edit all the generated code every build?
No, that is NOT usable!
