### ISSUE TITLE
Support to multiple html templates

### ISSUE THREAD

**Issue by renancunha** [jhipster/generator-jhipster#1780]
Hello everyone, what I'm proposing here is an enhancement.

Would be nice to the end-user of the generator have the possibility (during the project creation) to choose an html template (for the generated application) of his choice.

In the current state JHipster always will generate the UI based on fixed html templates. 
My idea is to give the choice of user create his own templates and the generator will use them if the user wants.

I know, its a very complicated point because some html templates files have a lot of logical inside them.

At the moment I don't have an implementable idea, but I'm working on it.

Sorry if I can't express myself properly, but I think that this is a good improvement in JHipster.

Thanks,
Renan.

**Comment by jdubois** [comment]
We have 2 kind of templates:

- The ones from AngularJS -> here we stick to the default AngularJS system, and I don't think we could/should change this. It would be very, very difficult to change this.
- The server-side templates, with Thymeleaf -> it looks only very few people use them, so I don't see the need to add more
