### ISSUE TITLE
Add Multiple Datasource Support

### ISSUE THREAD

**Issue by Qinwroks** [jhipster/generator-jhipster#1781]
My JH App currently using mysql, now i want use mongodb. is there a way to do that?

@jdubois will u consider to add multiple ds support?

**Comment by atomfrede** [comment]
You want to use mongodb in addition? A "simple" solution would be to create a second jhipster app with mongodb support (remove all ui related stuff maybe) and let your current app communicate via rest api with the mongodb enabled app.

**Comment by jdubois** [comment]
Yes we currently can't have 2 datasources at the same time.
The only option is to have a "micro service" approach with 2 apps.

**Comment by Qinwroks** [comment]
Got it!
