### ISSUE TITLE
Add an ApplicationProperties needle

### ISSUE THREAD

**Issue by Ebsan** [jhipster/generator-jhipster#17838]
##### **Overview of the feature request**

Could a needle be added to ApplicationProperties.java and the corresponding application.yml file?

##### **Motivation for or Use Case**

Some modules may require application specific settings to be enabled/disabled by the user. At the moment the best way to do it is to completely regenerate the ApplicationProperties.java file and notify them that they'll have to manually edit the application.yml file. Some needles in the java class and yaml file would really make this process easier.

##### **Related issues or PR**

None were found.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/100749.

**Comment by DanielFran** [comment]
@mshima approved
