### ISSUE TITLE
It should not be possible to have enum values starting by a number in the entity generator

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1784]
? What is the class name of your enumeration? myEnumType
? What are the values of your enumeration (separated by comma)? 1foo,bar

Produces:
```java
public enum MyEnumType {
    1foo, bar
}
```
which is illegal.
The entity generator should verify that the enum values don't start with a number.

**Comment by andidev** [comment]
This can easily be done with a regex test in a else if case here
https://github.com/jhipster/generator-jhipster/blob/master/entity/index.js#L259

**Comment by cbornet** [comment]
A more flexible solution could also be to authorize the "1foo" value and use an enum class like this:
```java
package com.mycompany.myapp.domain.enumeration;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The MyEnumType enumeration.
 */
public enum MyEnumType {
    _1FOO("1foo"),
    BAR("bar")
    ;
    
    private final String value;

    private MyEnumType(String value) {
		this.value = value;
	}
    
	@JsonValue
	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return value;
	}

}
```
Capitalizing the enum names would even be better regarding naming conventions.

**Comment by andidev** [comment]
So I implemented validation of the enum values.

Looks to me that having enums starting by a number i a special case. We should create a new issue for that if it is wanted.
