### ISSUE TITLE
Links from generated README to JHipster documentation are broken.

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#17874]
Latest projects README.md generated by 7.6.0 pointing to jhipster.tech archived doc are broken because v7.6.0 cannot be found on https://www.jhipster.tech/documentation-archive/v7.6.0/.

Here is the sample gateway :

https://github.com/jhipster/jhipster-sample-app-gateway/blob/main/README.md#jhipstersamplegateway

I suppose that something was not run as part of release process.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@gmarziou : I started the discussion in the ML. see https://groups.google.com/g/jhipster-dev/c/pX00gWQcDAQ/m/_jDrwzqwBAAJ

**Comment by mraible** [comment]
Added bug bounty to help get this fixed.
