### ISSUE TITLE
Update sonar plugin and add code coverage

### ISSUE THREAD

**Issue by bescott1** [jhipster/generator-jhipster#1788]
The sonar plugin is outdated, and no longer compatible with the latest sonar server, it should be updated to 2.5.

Sonar analysis is incomplete without code coverage reports. There should be code coverage for Java and Javascript.

I will add Jacoco and Karma-coverage to solve this issue. I'm only able to add it to the maven configuration.

**Comment by atomfrede** [comment]
If required I can have a look at the gradle integration via https://docs.gradle.org/current/userguide/sonar_runner_plugin.html

**Comment by jdubois** [comment]
Yes that would be really great !

**Comment by bescott1** [comment]
This has been done for maven, just needs the gradle version.

**Comment by atomfrede** [comment]
I will take care of it.

**Comment by atomfrede** [comment]
How is the js coverage supposed to be displayed on the sonar Web interface? Are there any additional plugins required? 

I will downgrade the jacoco plugin, because jacoco changed there coverage format which seems not to be compatible to sonar yet. 

Currently gradle generates the same output as the maven build, but I can't see js coverage in the Web interface.

**Comment by bescott1** [comment]
There's a bug I didn't catch:

Maven and karma have different base path. The base path of maven is the project root, the base path of karma is {projectDir}/src.

Karma creates the lcov report where all files are based on the karma base path, when passed to Sonar through maven, Sonar cannot resolve the paths in the lcov file.

The fix as I see it would be to synchronize the base path of both to the same directory by changing karma.conf.js:

basePath: '../../', to basePath: '../../../',

All paths will have to be updated in this file to reflect the change, but not sure if this will have an impact beyond this config file.

**Comment by atomfrede** [comment]
I'll have a look as the ``karma.conf`` must be changed to default gradle output paths (at the moment they always point to mavens target directory)

**Comment by jdubois** [comment]
I don't know how good Sonar is for auditing JavaScript code -> if you can make it work, of course that would be better, but let's not make this slow us down!
Can you send a PR that updates Sonar and just makes the Java part work (which is the important part for me)?

**Comment by atomfrede** [comment]
Java part is already working. I can leave the JS part as it is, than it works right now for maven only.

**Comment by jdubois** [comment]
Yes it's already a big improvement, I'd be really happy to have a Sonar audit on the app: this was one my original goals, but I didn't work on this for at least a year.
@atomfrede can we close this for the moment ?

**Comment by atomfrede** [comment]
@jdubois Yes. I'll provide a PR with gradle integration in the next couple of days.

**Comment by bescott1** [comment]
Actually most of the JS part is working. The analysis is working, the only part that is missing is the JS coverage in sonar. 

I can take over and work on the gradle integration and fixing the JS coverage bug. I haven't done gradle yet but this will be a good intro to it.

**Comment by atomfrede** [comment]
@bescott1 The gradle part is already working fine (PR follows). I also have successfully added the JS coverage to sonar, but there are some problems with it due to some strange wiredep behaviour, so I'll leave it out for now. Just need to add some minor improvements to the ``karma.conf`` before I create the PR.

**Comment by bescott1** [comment]
ok, if you give me some details on what is still broken I can attempt to fix it.

**Comment by atomfrede** [comment]
Need to have a look at home and try to commit the PR until the end of week. Tehn we can have a look how to get the coverage to sonar. Your hint with the ``basePath`` was absolutly tright by the way, but you have to change some more stuff which gets overwritten by wiredep afterwards again.
