### ISSUE TITLE
Integration tests fail with nested jpaDerivedIdentifier

### ISSUE THREAD

**Issue by crowne** [jhipster/generator-jhipster#17906]
##### **Overview of the issue**
Integration tests fail when I define nested entities using jpaDerivedIdentifier
the integration tests fail for entities at or lower than grandchild level

Given the following entities:  
  - Animal
    - Fish
    - Bird
    - Mammal
      - Marsupial
      - Rodent
      - Cat
        - DomesticatedCat

And the following relationships:
relationship OneToOne {
  Fish{animal required} to Animal with jpaDerivedIdentifier
  Bird{animal required} to Animal with jpaDerivedIdentifier
  Mammal{animal required} to Animal with jpaDerivedIdentifier
    Marsupial{mammal required} to Mammal with jpaDerivedIdentifier
    Rodent{mammal required} to Mammal with jpaDerivedIdentifier
    Cat{mammal required} to Mammal with jpaDerivedIdentifier
      DomesticatedCat{cat required} to Cat with jpaDerivedIdentifier
}

generate the app
> jhipster jdl tree.jdl

test the app 
> mvn verify

The following errors are reported:

> [ERROR] Errors:
> [ERROR]   CatResourceIT.updateCatMapsIdAssociationWithNewId:150 » EntityExists A differe...
> [ERROR]   DomesticatedCatResourceIT.updateDomesticatedCatMapsIdAssociationWithNewId:155 » EntityExists
> [ERROR]   MarsupialResourceIT.updateMarsupialMapsIdAssociationWithNewId:150 » EntityExists
> [ERROR]   RodentResourceIT.updateRodentMapsIdAssociationWithNewId:150 » EntityExists A d...
> 

The tests for AnimalResourceIT, FishResourceIT, BirdResourceIT and MammalResourceIT all work,  
but anything lower than one level has a problem

##### **Motivation for or Use Case**

This isn't a problem for the app  at runtime, it seems to be an integration test issue only.

##### **Reproduce the error**

See the Overview, jdl will be provided.

##### **JHipster Version(s)**

7.5.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
tree@0.0.1-SNAPSHOT C:\github\jhip-treebug
`-- generator-jhipster@7.5.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": true,
    "baseName": "tree",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "testFrameworks": [],
    "websocket": false,
    "enableGradleEnterprise": false,
    "gradleEnterpriseHost": "",
    "applicationType": "monolith",
    "packageName": "com.jhipster.demo.tree",
    "packageFolder": "com/jhipster/demo/tree",
    "jhipsterVersion": "7.5.0",
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "applicationIndex": 0,
    "entities": ["Animal", "Fish", "Bird", "Mammal", "Marsupial", "Rodent", "Cat", "DomesticatedCat"],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1645088543533,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",    "devServerPort": 4200,
    "lastLiquibaseTimestamp": 1645089023000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Animal {
  name String required minlength(3)
  description String
}
entity Fish {
  hasScales Boolean required
}
entity Bird {
  wakingBehaviour WakingBehaviour required
}
entity Mammal {
  numberOfLegs Integer required min(2)
  numberOfArms Integer required min(0)
}
entity Marsupial {
  isEndangered Boolean required
}
entity Rodent {
  hasTail Boolean required
}
entity Cat {
  livesLeft Integer required
}
entity DomesticatedCat {
  hairType HairType required
}
enum WakingBehaviour {
  DIURNAL,
  NOCTURNAL
}
enum HairType {
  HAIRLESS,
  LONG,
  SHORT
}

relationship OneToOne {
  Fish{animal required} to Animal
  Bird{animal required} to Animal
  Mammal{animal required} to Animal
  Marsupial{mammal required} to Mammal
  Rodent{mammal required} to Mammal
  Cat{mammal required} to Mammal
  DomesticatedCat{cat required} to Cat
}

paginate Animal, Fish, Bird, Mammal, Marsupial, Rodent with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

git version 2.34.1.windows.1

node: v16.13.2

npm: 8.1.2

Docker version 20.10.12, build e91ed57

Docker Compose version v2.2.3

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Windows 10 Pro
Chrome, but this issue is not browser related

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by emilpaw** [comment]
I am working on this.
