### ISSUE TITLE
Composite primary key (again)

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#17919]
##### **Overview of the feature request**

Now that we have better support for the generation of primary keys (jdl...), ans that blueprints have been using them for a little while, I think we should start using them in the server code (java + liquibase) then once the server is stable enough implement them in the frontend.

Again before starting to work on this, I am pinging the people that showed must interest/opposition last time to see what you think:
@mshima @DanielFran @jdubois @deepu105 @PierreBesson @gmarziou I apologize in advance in forgot anybody.

More info on what have been done and discussed until now can be found here: https://github.com/jhipster/generator-jhipster/issues/7112

**Comment by yelhouti** [comment]
@DanielFran thank you for tagging this v8, do I understand correctly that this is a go ahead ? or does anyone have any objection ? ( Looking at you @mshima  :stuck_out_tongue:  )

**Comment by DanielFran** [comment]
It is tagged to "V8" to be discussed internally if we should or not include it on the roadmap...

**Comment by yelhouti** [comment]
@DanielFran thank you for the info, can I take part in the discutions ? I contact https://groups.google.com/g/jhipster-dev few weeks ago but never received a reply.

**Comment by pascalgrimaud** [comment]
@yelhouti : how did you contact the group ? as it's in read only for external members ?

**Comment by yelhouti** [comment]
@pascalgrimaud there is a contact owners and managers that allows you to send an email.
![Screenshot from 2022-05-23 18-38-48](https://user-images.githubusercontent.com/5471639/169867373-b4bbdc7f-1bdf-402d-971c-e80e4c6fad38.png)

**Comment by mshima** [comment]
We already support composite id in the internals.
If the template change is simple enough it can be merged.
No need for v8 tag.

**Comment by yelhouti** [comment]
I would like to be able to generated the server code two, which as you might think impacts almost all the entity-server files.

**Comment by amarpatel-xx** [comment]
I have a Cassandra implementation for composite primary keys (including clustering keys).  It is working for my local blueprint with version JHipster version 7.6.0.  I would like to contribute it to the JHipster community.  I would need help in merging the code with the latest JHipster (version 7.9.3).

**Comment by yelhouti** [comment]
@amarpatel-xx same for me, I have a version here updated to 7.9.3 https://github.com/yelhouti/generator-jhipster/tree/composite-key but I need to rebase it again.

**Comment by yelhouti** [comment]
Just keeping this open if no one minds, until I have time to rebase on top of 8.0.0

**Comment by amarpatel-xx** [comment]
I have successfully made a composite primary key blueprint for JHipster 8.6.0 cassandra.  Please see reference here: https://github.com/amarpatel-xx/jhipster-cassandra-composite-primary-key-example
