### ISSUE TITLE
There seems to have some problem with cacheBuster, it always gives 400 Bad Request

### ISSUE THREAD

**Issue by maddy1512** [jhipster/generator-jhipster#1793]

**Comment by atomfrede** [comment]
Some details would be great (which configuration, which requests...).

**Comment by jdubois** [comment]
The issue isn't with cachebuster -> cachebuster is just so that resources are not cached by some browsers, see https://github.com/saintmac/angular-cache-buster

-> your 400 error is something else, you need to have a look at what's happening server side
