### ISSUE TITLE
UserStepsDef creates incorrect instance of WebTestClient

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#17944]
##### **Overview of the issue**

When generating a clean reactive project without importing any entity, the UserStepsDef class has a few issues:

1. the `MockMvcBuilders` import is missing
2. the `status` static import is missing
3. the `content` static import is missing
4. the `jsonPath` static import is missing
5. The class tries to instantiate the `WebTestClient` object with the following code:
`this.userResourceMock = MockMvcBuilders.standaloneSetup(userResource).build();`
which actually returns a `MockMvc` object.
6. Method `i_search_user` shows the following error:
```
Required type: ResultActions
Provided: capture of ?
```
on this line: 
`actions = userResourceMock.get().uri("/api/admin/users/" + userId).accept(MediaType.APPLICATION_JSON);`

##### **Motivation for or Use Case**

When creating a reactive project, there should no errors :)

##### **Reproduce the error**

run `jhipster` and choose reactive when asked.

##### **Related issues**
I've searched but haven't found any related issue

##### **Suggest a Fix**
Add missing static imports and instantiate the object with the correct constructor (I don't know which is the correct constructor)

##### **JHipster Version(s)**
v7.6.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
reactive@0.0.1-SNAPSHOT /home/alejandro/projects/reactive
└── generator-jhipster@7.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "reactive",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "sandstone",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1645371838709,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [
    ],
    "entitySuffix": "",
    "jhiPrefix": "fa",
    "jhipsterVersion": "7.6.0",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1645376104000,
    "messageBroker": "kafka",
    "nativeLanguage": "es",
    "otherModules": [],
    "packageName": "com.reactive",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": true,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": ["messageBroker:kafka"],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": ["cucumber"],
    "websocket": false,
    "withAdminUi": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)

git version 2.32.0

node: v12.22.5

npm: 7.5.2

Docker version 20.10.12, build e91ed57

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Browsers and Operating System**

Linux with IntelliJ
- [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by mraible** [comment]
I can confirm this is an issue. 

```
[ERROR] /Users/mraible/Downloads/user-steps-def/src/test/java/com/reactive/cucumber/stepdefs/UserStepDefs.java:[41,33] cannot find symbol
[ERROR]   symbol:   variable MockMvcBuilders
[ERROR]   location: class com.reactive.cucumber.stepdefs.UserStepDefs
[ERROR] /Users/mraible/Downloads/user-steps-def/src/test/java/com/reactive/cucumber/stepdefs/UserStepDefs.java:[46,82] incompatible types: capture#1 of ? cannot be converted to org.springframework.test.web.servlet.ResultActions
[ERROR] /Users/mraible/Downloads/user-steps-def/src/test/java/com/reactive/cucumber/stepdefs/UserStepDefs.java:[51,27] cannot find symbol
[ERROR]   symbol:   method status()
[ERROR]   location: class com.reactive.cucumber.stepdefs.UserStepDefs
[ERROR] /Users/mraible/Downloads/user-steps-def/src/test/java/com/reactive/cucumber/stepdefs/UserStepDefs.java:[51,54] cannot find symbol
[ERROR]   symbol:   method content()
[ERROR]   location: class com.reactive.cucumber.stepdefs.UserStepDefs
[ERROR] /Users/mraible/Downloads/user-steps-def/src/test/java/com/reactive/cucumber/stepdefs/UserStepDefs.java:[56,27] cannot find symbol
[ERROR]   symbol:   method jsonPath(java.lang.String)
[ERROR]   location: class com.reactive.cucumber.stepdefs.UserStepDefs
[ERROR] -> [Help 1]
```

Adding a bounty to get this fixed. Please submit a PR if you know how to fix.
