### ISSUE TITLE
Integration tests fail with French as native language of the application

### ISSUE THREAD

**Issue by hamaarouf** [jhipster/generator-jhipster#17946]
##### **Overview of the issue**
When generating a jhipster project with French as native language of the application, the intergration test fail with the following failure message :

> [INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   MailServiceIT.testSendEmailFromTemplate:143
expected: "test title"
 but was: "Activation de votre compte mailservice"
[INFO]
[ERROR] Tests run: 90, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.7:report-integration (post-integration-tests) @ mailservice ---
[INFO] Loading execution data file C:\Users\ASUS\Documents\formation\Jhipsterr\mailservice\target\jacoco-it.exec
[INFO] Analyzed bundle 'Mailservice' with 56 classes
[INFO]
[INFO] --- maven-checkstyle-plugin:3.1.2:check (default) @ mailservice ---
[INFO] You have 0 Checkstyle violations.
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (verify) @ mailservice ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:56 min
[INFO] Finished at: 2022-02-21T16:52:56+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M5:verify (verify) on project mailservice: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\ASUS\Documents\formation\Jhipsterr\mailservice\target\failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

##### **Motivation for or Use Case**
this is a bug for me because, integration tests fail.

##### **Reproduce the error**

run `jhipster` and choose French as native language of the application. then run `mvnw verify`

##### **Related issues**
I've searched on the internet but I haven't found any related issue.

##### **Suggest a Fix**
When generating jhipster project with English we have :
`<Project_name>\src\test\resources\i18n\messages_en.properties` containing : 

> email.test.title=test title
> #Value used for English locale unit test in MailServiceIT
> #as this file is loaded instead of real file
> email.activation.title=inheritance account activation

and in 
`<Project_name>\src\test\java\com\mycompany\myapp\service\MailServiceIT.java`

> ... 
> assertThat(message.getSubject()).isEqualTo("test title");
> ...
> 
otherwise the two file have the same message _**test title**_

But in in project using French we have the following:
`<Project_name>\src\test\resources\i18n\messages_fr.properties` containing : 

> email.test.title=Activation de votre compte gestionUtilisateurs

and in 
`<Project_name>\src\test\java\com\mycompany\myapp\service\MailServiceIT.java`

> ... 
> assertThat(message.getSubject()).isEqualTo("test title");
> ...
> 

So there is two diffrent messages

so to I just edited **email.test.title** in `<Project_name>\src\test\resources\i18n\messages_fr.properties` to be:

> email.test.title=test title

And I don't have anymore that failure in integration tests

##### **JHipster Version(s)**

JHipster 7.6.0

##### **JHipster configuration**
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
mailservice@0.0.1-SNAPSHOT C:\Users\ASUS\Documents\formation\Jhipsterr\mailservice
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "mailservice",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1645457831454,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.6.0",
    "languages": ["fr"],
    "messageBroker": false,
    "monorepository": true,
    "nativeLanguage": "fr",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "eureka",
    "skipCheckLengthOfIdentifier": false,
    "skipCommitHook": true,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **Environment and Tools**

java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

git version 2.29.2.windows.2

node: v14.15.1

npm: 6.14.15

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Browsers and Operating System**

Windows 10 famille langue unique
Chrome, but it's not related to the browser.

**Comment by mraible** [comment]
Adding bug bounty because it seems like our i18n should support this.

**Comment by hamaarouf** [comment]
I'm working on it!

**Comment by gmarziou** [comment]
Unfortunately, this fix addresses only French, same change should be done for all languages.

**Comment by gmarziou** [comment]
I suspect that this problem reported on SO about Italian is related.

https://stackoverflow.com/questions/72618701/plugin-and-dependency-not-found

**Comment by hamaarouf** [comment]
@gmarziou Thank you for pointing that out! I can do it during this week. Please I have one question is there any simple way to test it without creating for each language a project?

**Comment by gmarziou** [comment]
As the change is simple, I would not worry about testing all languages.

Integration tests of the generator should have caught the initial bug but maybe we don't have a sample project, I must admit that I don't know how JHipster's CI works. @pascalgrimaud could help for sure. 

Integration tests can be run locally: https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md#running-integration-tests-locally

**Comment by hamaarouf** [comment]
I made a PR here https://github.com/jhipster/generator-jhipster/pull/18951
