### ISSUE TITLE
TLS Live Server not working

### ISSUE THREAD

**Issue by Ebsan** [jhipster/generator-jhipster#17968]
##### **Overview of the issue**

Using Jhipster 7.6.0 I can no longer run a live server with tls enabled. As described in the docs we should be able to run `npm run start-tls` to bring up a live server proxying to https://localhost:4200. However, the live server proxies to http://localhost:4200 (missing the s in https).

Here is the output from running `npm run start-tls`:

```
** Angular Live Development Server is listening on localhost:4200, open your browser on https://localhost:4200/ **


√ Compiled successfully.
[Browsersync] Proxying: http://localhost:4200
[Browsersync] Access URLs:
 ------------------------------------
       Local: http://localhost:9000
    External: http://10.10.0.115:9000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ------------------------------------
```

##### **Motivation for or Use Case**

Need to run tls in production. http is no longer used. Jhipster should default to https instead of http. Similar to #15655

##### **Reproduce the error**

1. Download latest version of Jhipster (v7.6.0)
2. Create new Jhipster app
3. Enable tls profile in `application.yml`
4. Run server using `mvnw`
5. Run the live server in another terminal using `npm run start-tls`

##### **Related issues**

* #15655

##### **JHipster Version(s)**

v7.6.0
This was working in previous versions.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "jhipster",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1645128760896,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.6.0",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": "elasticsearch",
    "serverPort": "8080",
    "serverSideOptions": ["searchEngine:elasticsearch"],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

git version 2.34.1.windows.1

node: v16.13.2

npm: 8.3.0

Docker version 20.10.12, build e91ed57

Docker Compose version v2.2.3

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by nomuna** [comment]
Please do not change the title of the ticket... Please.
