### ISSUE TITLE
Potential Security Vulnerabilities

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#17970]
##### **Overview of the feature request**

We use Fortify Static Code Analyzer to scan our project built with JHipster. The report shows over 150 potential security vulnerabilities. Although the majority of them are javascript libraries, it is worth sharing the finding. 

Here is the JHipster setup for the app:
```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "myapp",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "vue",
    "clientPackageManager": "npm",
    "clientTheme": "lux",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1626276896721,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [...],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.6.0",
    "languages": ["en", "de"],
    "lastLiquibaseTimestamp": 1641510171000,
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageFolder": "com/abc/myapp",
    "packageName": "com.abc.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipFakeData": false,
    "skipServer": false,
    "skipUserManagement": true,
    "testFrameworks": ["cypress", "gatling"],
    "websocket": false,
    "withAdminUi": true
  }
}
```

##### **Motivation for or Use Case**

To make applications built with JHipster more secure.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vw98075** [comment]
[sast-issues.csv](https://github.com/jhipster/generator-jhipster/files/8137139/sast-issues.csv)
 The about is the output file

**Comment by mraible** [comment]
Please create a pull request to fix these issues and we will gladly reward you. :)

**Comment by vw98075** [comment]
Other than those in the node_modules directory, I don't know where some of those Javascript files come from. The followings are some of such samples:

target/classes/static/app.js
target/classes/swagger-ui/swagger-ui-bundle.js
target/classes/swagger-ui/swagger-ui-standalone-preset.js
target/classes/swagger-ui/swagger-ui.js

I can't find the above files inside the project space on Idea.

To see whether I can do something on those javascript files, I need to know the source files.

**Comment by atomfrede** [comment]
app.js is the transpiled output of the respective frontend application. Swagger-ui sources are not part of the project, they are a 3rd party dependency: https://www.npmjs.com/package/swagger-ui

**Comment by gmarziou** [comment]
@vw98075 this tool could probably be better configured so that it skips npm modules that are dev dependencies (tools) that are not bundled with your app, this leads to many false positives. So either a bad tool or a bad configuration.
