### ISSUE TITLE
Duplicated alert.service.js 

### ISSUE THREAD

**Issue by fontanellif** [jhipster/generator-jhipster#1797]
Hi, i notice that the file alert.service.js is duplicated :

- generator-jhipster/app/templates/src/main/webapp/scripts/components/util/_alert.service.js
- generator-jhipster/app/templates/src/main/webapp/scripts/components/alert/_alert.service.js

i think that the first, under util directory, could be deleted. Right?

**Comment by deepu105** [comment]
yes im making a PR with those changes currently

On Sat, Aug 1, 2015 at 6:51 PM, Filippo Fontanelli <notifications@github.com

**Comment by deepu105** [comment]
closing this as the PR has been done https://github.com/jhipster/generator-jhipster/pull/1798
