### ISSUE TITLE
Buttons have black text on colored background

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#18008]
##### **Overview of the issue**

In previous versions of JHipster, I'm pretty sure the buttons had white text on buttons with colored backgrounds. In v7.7.0, the text is black. 

<img width="1086" alt="Screen Shot 2022-02-28 at 20 53 13" src="https://user-images.githubusercontent.com/17892/156101841-c1a6c941-f840-4b16-97d1-1e9b3d9bad08.png">

##### **Motivation for or Use Case**

I believe the button text was white in previous releases. If you look at [my blog post with v7.4.1](https://auth0.com/blog/full-stack-java-with-react-spring-boot-and-jhipster/), it does use a custom theme, but the button text is also white. 

![photo gallery](https://images.ctfassets.net/23aumh6u8s0i/6RIASq72N4JN9b3ya5UVra/c0530addbbf28020d1a42f6b18ea0bae/08_photo-gallery.jpg)

##### **Reproduce the error**

Create a new project with entities.

##### **JHipster Version(s)**

```
postgres@0.0.1-SNAPSHOT /Users/mraible/dev/spring-native-examples/postgres-webflux
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "Postgres",
    "blueprints": [
      {
        "name": "generator-jhipster-native",
        "version": "0.0.0"
      }
    ],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1632872179205,
    "cypressCoverage": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": ["Blog", "Post", "Tag"],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.7.0",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1632872631000,
    "messageBroker": false,
    "monorepository": true,
    "nativeLanguage": "en",
    "otherModules": [
      {
        "name": "generator-jhipster-native",
        "version": "0.0.0"
      }
    ],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": true,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipCommitHook": true,
    "skipFakeData": false,
    "skipJhipsterDependencies": true,
    "skipServer": false,
    "skipUserManagement": true,
    "testFrameworks": ["cypress"],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

git version 2.32.0 (Apple Git-132)

node: v16.13.2

npm: 8.1.2

Docker version 20.10.12, build e91ed57

Docker Compose version v2.2.3

**Comment by mshima** [comment]
This is related to bootstrap 5.
The text color (black or white) is calculated based on the background color.

**Comment by mraible** [comment]
If that's the case, should we close this issue?

**Comment by mshima** [comment]
IMO white would look better for current colors, but I don’t know if it’s possible to do it for every component, without customization every component one by one.
Eg: *-info (btn, modal, …)

**Comment by hamaarouf** [comment]
@mraible I created a project with jhipster 7.7.0 and I didn't have this issue. Im using Windows.
![test](https://user-images.githubusercontent.com/75782444/156220226-9db4f5ff-881d-4b86-bb8f-eee746865908.png)

**Comment by mshima** [comment]
React is not customizing the colors like angular is.

**Comment by mraible** [comment]
If I look at Bootstrap's example buttons at https://getbootstrap.com/docs/5.3/components/buttons/, it seems like their colors are more appropriate. Maybe the Bootswatch theme is causing the issue?

<img width="833" alt="Screenshot 2023-02-23 at 4 18 37 PM" src="https://user-images.githubusercontent.com/17892/221053290-d38ba1f4-ba9f-4888-a557-1c4af996b32c.png">

**Comment by mraible** [comment]
It still seems weird that React uses white text and Angular uses black.
