### ISSUE TITLE
question on include JHipster the maven dependency way

### ISSUE THREAD

**Issue by Qinwroks** [jhipster/generator-jhipster#1804]
is there a way to simplify the use of jh just like spring-boot way.

spring-boot way: just include spring-boot dependencies, so it is very simple.

or jh can use the spring-boot-starter way.

**if jh could provide a way like spring-boot or spring-boot-starter, then each jh version update, i should just change the jhipster version in my pom.**

**Comment by deepu105** [comment]
I definitely do not understand your query can you be more specific or detailed

**Comment by gmarziou** [comment]
@Qinwroks JHipster is a code generator not a dependency, so you can't depend on it, the generated code is yours.

**Comment by jdubois** [comment]
I think this is kind of the idea I have for JHipster 3, with some code in a specific JAR file.
-> this is not possible at the moment, but I will definitely try to do this in the next major version

**Comment by Qinwroks** [comment]
@jdubois ,OK THANKS!
