### ISSUE TITLE
Dockerfile is missing when generating a new project

### ISSUE THREAD

**Issue by hamaarouf** [jhipster/generator-jhipster#18050]
##### **Overview of the issue**
It's mentioned in the documentation  https://www.jhipster.tech/docker-compose/ at the description section that when we generate a new Jhipster project, Dockerfile is generated by Jhipster, which is not the case for me.

##### **Motivation for or Use Case**

It would be easier if Dockerfile generated by Jhipster instead of creating it. 

##### **Reproduce the error**

run `jhipster` to generate the project and go check in <project_name>\src\main\docker for Dockerfile

##### **Related issues**

I didn't find any related issue

##### **JHipster Version(s)**

jhipster-7.7.0 (also I had the same issue in jhipster-7.6.0)

##### **JHipster configuration**
INFO! Switching to JHipster installed locally in current project's node repository (node_modules)

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v7.7.0

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
project-1@0.0.1-SNAPSHOT C:\Users\ASUS\Documents\formation\Jhipsterr\jhipster7.7.0\project1
`-- generator-jhipster@7.7.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "project1",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1646148969323,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": ["Blog", "Post", "Tag"],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.7.0",
    "languages": ["fr"],
    "lastLiquibaseTimestamp": 1646155975000,
    "messageBroker": false,
    "monorepository": true,
    "nativeLanguage": "fr",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipCommitHook": true,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

git version 2.29.2.windows.2

node: v16.14.0

npm: 8.5.2

Docker version 20.10.12, build e91ed57

Docker Compose version v2.2.3

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
##### **Browsers and Operating System**

Windows 10 famille langue unique
Chrome

**Comment by nomuna** [comment]
No _Dockerfile_ will be generated for you. Jhipster generates _*.yml_ files for all the docker images to be used with docker-compose in the folder _src/main/docker_. How to start them is also described in the _README.md_ file that is also generated for the project.

**Comment by hamaarouf** [comment]
@nomuna did you try to regenerate the error ? because Dockerfile is missing in my case and it's not only for me, you can see in the comments section of this tutorial others who have the same issue

https://www.youtube.com/watch?v=6f87fg_MsLw&t=200s

here is the files I have in src/main/Docker:

![dockerfile](https://user-images.githubusercontent.com/75782444/156920884-bbb8e48b-fa74-451f-8807-918cd2a4c104.png)

**Comment by nomuna** [comment]
ok the video is from 2019... I am guessing the jhipster version of that time created Dockerfile. The new one does not. Try it with the docker-compose files. Or hunt down the version used in that video and try that.

**Comment by mshima** [comment]
We don’t provide a dockerfile because we use default jib-plugin one.
If you want to customize it, go to jib documentation.
To build the docker image run `npm run java:docker` or follow https://www.jhipster.tech/docker-compose/#3
And start it with `docker-compose -f src/main/docker/app.yml up`.

The Dockerfile reference should be removed from the documentation.

**Comment by hamaarouf** [comment]
@mshima Thank you for your answer! please can I make a PR to remove the Dockerfile reference from the documentation ?

**Comment by mshima** [comment]
@hamaarouf yes, please.

**Comment by mraible** [comment]
@hamaarouf Please provide a link to your documentation PR when you get a chance.

**Comment by hamaarouf** [comment]
@mraible Yes of course,  Could you please give me the link of documentation's repo I coudn't find it!

**Comment by pascalgrimaud** [comment]
@hamaarouf : https://github.com/jhipster/jhipster.github.io

**Comment by hamaarouf** [comment]
here is my PR link https://github.com/jhipster/jhipster.github.io/pull/1201

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/jhipster.github.io/pull/1201
