### ISSUE TITLE
Bump liquibase-core from 4.6.1 to 4.12.0 (Security alert)

### ISSUE THREAD

**Issue by Akuka** [jhipster/generator-jhipster#18071]
Improper Restriction of XML External Entity Reference in Liquibase

The XMLChangeLogSAXParser() function in Liquibase prior to version 4.8.0 contains an issue that may lead to to Improper Restriction of XML External Entity Reference.

Package: org.liquibase:liquibase-core
Affected versions: < 4.8.0
Patched version: 4.8.0

![image](https://user-images.githubusercontent.com/3299903/157411191-20367f8a-55e4-4a25-b715-e2cd8e6971cd.png)

**Comment by mshima** [comment]
[Regressions](https://github.com/jhipster/generator-jhipster/pull/18072#issuecomment-1075319341) must be fixed before updating.
We will need to keep 4.6.1 for mysql/mariadb and keep [h2 v1](https://github.com/liquibase/liquibase/issues/2306) .

**Comment by mraible** [comment]
Link to https://github.com/liquibase/liquibase/issues/2923 for tracking purposes.
