### ISSUE TITLE
SQL server 2012 table is not getting created

### ISSUE THREAD

**Issue by maheshkaranjkar** [jhipster/generator-jhipster#1807]
Hi Guys,

 We are trying to use jhipster with SQL  server, we have done all necessary configuration mentioned in Tips section http://jhipster.github.io/tips/004_tip_using_ms_sql_server.html .

Also we are able to run application first time . but wehn we created entity its not giving any error but table is nit getting created in database.

Following are files I have changed 

POM.xml

<code>

<!-- added dependencies  -- >
<dependency>
            <groupId>com.github.sabomichal</groupId>
            <artifactId>liquibase-mssql</artifactId>
            <version>1.4</version>
</dependency>
<dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>sqljdbc4</artifactId>
            <version>4.2</version>
 </dependency>

<!-- added Configuration changes -- >
<configuration>
            <changeLogFile>src/main/resources/config/liquibase/master.xml</changeLogFile>
                    <diffChangeLogFile>src/main/resources/config/liquibase/changelog/${maven.build.timestamp}_changelog.xml</diffChangeLogFile>
                    <driver>com.microsoft.sqlserver.jdbc.SQLServerDriver</driver>
                    <url>jdbc:sqlserver://localhost:1433;databaseName=db_globe</url>
                    <defaultSchemaName>db_globe</defaultSchemaName>
                    <username>gppuser</username>
                    <password />
                    <referenceUrl>hibernate:spring:com.bp.com.domain?dialect=org.hibernate.dialect.SQLServer2012Dialect</referenceUrl>
                    <verbose>true</verbose>
                    <logging>debug</logging>
                </configuration>
</code>

00000000000000_initial_schema.xml

<code>

<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd
        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">

    <property name="now" value="now()" dbms="mysql,h2"/>
    <property name="now" value="current_timestamp" dbms="postgresql"/>
    <property name="now" value="sysdate" dbms="oracle"/>
    <property name="now" value="GETDATE()" dbms="mssql"/>
	
	<property name="autoIncrement" value="true" dbms="mssql"/>
    <property name="autoIncrement" value="true" dbms="mysql,h2,postgresql"/>
    <property name="autoIncrement" value="false" dbms="oracle"/>

    <changeSet id="00000000000000" author="jhipster" dbms="postgresql,oracle">
        <createSequence sequenceName="hibernate_sequence" startValue="1000" incrementBy="1"/>
    </changeSet>
</code>

I have changed datasource application-dev.yml file.

NOTE : One thing I observed 
20150803125005_added_entity_Academy.xml (Entity file which is crated is not having mssql details) 
like 
<code>
<property name="now" value="GETDATE()" dbms="mssql"/>
</code>

Please guide me what wrong I have done.

also pleas mention if i have missed any thing.

Regards
Mahesh

**Comment by deepu105** [comment]
Did you restart the server after ceeating the entity?

**Comment by deepu105** [comment]
Also sql server is not officially supported by Jhipster so the date value needs to be manually added if you are using date i guess. Anyway since we do not support ms sql and most of us dont have a way to test we may not be able to help, you can try to post this in gitter to get some help. The tutorial was from @Zyst so he might be able to help you

**Comment by maheshkaranjkar** [comment]
Thanks deepu for your reply,

yes you are right problem was date field. I removed date field and it work fine.

Cheers !!
Mahesh

**Comment by maheshkaranjkar** [comment]
Hi Guys.

After updating latest liquibase version even table with Datetime field its working fine.
Updated Pom.xml
<code>

<liquibae.version>3.4.1</liquibase.version>

</code>

Regards
Mahesh

**Comment by deepu105** [comment]
@maheshkaranjkar you can submit a PR to upgrade liquibase version in maven and gradle files if you like.

**Comment by Zyst** [comment]
Sorry read this quite a bit later, took a vacation which led me to have no internet for nearly a month.

Glad you fixed your issue @maheshkaranjkar 

It seems you figured out how to use dates, so I won't elaborate further.
