### ISSUE TITLE
DTO mapping fails on many to one relationships.

### ISSUE THREAD

**Issue by cah-andrewfitzgerald** [jhipster/generator-jhipster#1809]
There is a mismatch between angular and the DTO for many-to-one relationships.

Create an Author entity (using the DTO option), and a Book entity (Also using the DTO option) where Book has a many-to-one relationship (writtenBy) to Author.

Using the generated admin interface, create an Author, then create a Book written by that author.

Upon saving, the book will have a null author. This is because the JSON is sent as book.writtenBy.id, while the DTO mapper is expecting book.writtenById.

I'm not sure if this should be fixed on the angular side or the DTO mapping side (This is JSON -> DTO mapping, not DTO-> Domain mapping)

**Comment by renancunha** [comment]
I agree with you @cah-andrewfitzgerald, I think it should be resolved in angular side. Maybe this solution is a little bit ugly, but make more sense...

**Comment by andidev** [comment]
the same problem with one to one realtionships

**Comment by maheshkaranjkar** [comment]
Hi Guys,

One more update, I am also facing same issue, I tried to update table from back end to see if at front end its fetching proper details. 

Yes in default view its showing proper value. but when I open it in edit and view mode value came as blank.

Regards
Mahesh

**Comment by andidev** [comment]
Working on this, PR is soon ready.
I'm fixing it on the angular front end side
