### ISSUE TITLE
How do I change the favicon.ico from the spring leaf to my own figure?

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#1812]
My favicon.ico file is in the same level as the index.html. Is that right? If so, why I always get the spring leaf as my favicon?

**Comment by gmarziou** [comment]
That was supposed to work this way but it does not work anymore probably since we moved static resources under assets folder.

Your  file should be here: src/main/webapp/static/favicon.ico

**Comment by gmarziou** [comment]
In fact it could be at different places as you can see in [spring-boot ResourceProperties](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ResourceProperties.java)

~~~java
	private static final String[] CLASSPATH_RESOURCE_LOCATIONS = {
			"classpath:/META-INF/resources/", "classpath:/resources/",
			"classpath:/static/", "classpath:/public/" };
~~~

Anyway, it's a bug on our side, either we fix it by changing JHipster favicon.ico location and comments in index.html or we must add a FaviconController.

**Comment by marcelinobadin** [comment]
Thank you. I just added this ./static folder to assets, included it on the Gruntfile.js to copy this to the dist and in the index.html I added 

```
<link rel="icon"
              type="image/x-icon"
              href="assets/static/favicon.ico">
```

in the <head> section.

It worked very fine.

**Comment by gmarziou** [comment]
Great, I keep the issue open because I'd like to discuss with dev team about how we fix it.

**Comment by marcelinobadin** [comment]
Well, it works fine once I run in development mode (java -jar ....war) but once I send it to AWS it stops to work and the spring leaf is all I have. If I found some solution I will post here. Thanks.

**Comment by gmarziou** [comment]
It's probably related to StaticResourcesProductionFilter which is active in production profile

**Comment by gmarziou** [comment]
@marcelinobadin did you make any progress?

**Comment by marcelinobadin** [comment]
Actually I did. As you told me about the static resources, I created a folder inside the assets, assets/static and put my favicon.ico there.
But then, I don't know what I was doing wrong but my favicon was "kind of" demaged once it went to dist folder. I just changed the .ico for a .png file and in the index.html I inserted:

<link rel="icon" type="image/png" sizes="32x32" href="assets/static/favicon-32x32.png">

and other tags because I have a lot of icons for many systems like Android and iOS.

But also, I notice that the Gruntfile.js should be changed and then I inserted this in the copy: { dist: tag

 'assets/static/*'

and it looks like something like this:

dist: {
                files: [{
                    expand: true,
                    dot: true,
                    cwd: 'src/main/webapp',
                    dest: '<%= yeoman.dist %>',
                    src: [
                        '*.html',
                        'scripts/**/*.html',
                        'assets/images/**/*.{png,gif,webp,jpg,jpeg,svg}',
                        'assets/fonts/*',
                        'assets/static/*'
                    ]
                }

then it is working in production now.

**Comment by gmarziou** [comment]
Great, could you consider proposing a PR?

**Comment by marcelinobadin** [comment]
well, I never did it  before but I would love to try. I would work on this during this weekend.

**Comment by gmarziou** [comment]
Great, we have [a guide](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) that can be helpful.

**Comment by andidev** [comment]
Is there any reason why we don't place the `favicon.ico` in the `assets/images` folder instead of creating a new folder called `static`?

**Comment by mraible** [comment]
Is this all really necessary? I have two JHipster projects and all I've done is replace the favicon.ico with my own and it seems to work in Chrome, Firefox and Safari on Mac.

**Comment by marcelinobadin** [comment]
@andidev actually the static folder comes in the beginning of this discussion when @gmarziou spoke about spring-boot ResourceProperties. Are you sure it should work on the images folder even the ResourceProperties tries to find something like /static?

@mraible have you tested under production profile? I think you will not see the favicon correctly. Instead you will see the spring "leaf" as the favicon.

**Comment by mraible** [comment]
@marcelinobadin Yes, I have. You can see it at http://www.jhipster-book.com.

**Comment by marcelinobadin** [comment]
@mraible cool! it never worked for me. Even changing the icon. That's why we start to discuss about it and I had to make the change for my project to work. Only one thing, is your project running with the war file with tomcat embedded? Because mine is running in the AWS ElasticBeanstalk and there I should use the .original file which for me always sound that something different occurs but i don't know what and why.. but sometimes the application behavior is pretty different than in the war file with the embedded tomcat.

**Comment by gmarziou** [comment]
I have confirmed the bug in my projects when running with embedded tomcat in Windows. If you Google it, you'll find that this is a very common issue people have with spring boot.

**Comment by mraible** [comment]
Mine is running on Heroku and yes, it uses the embedded Tomcat. Have you tried requesting the favicon.ico directly? For example, http://www.jhipster-book.com/favicon.ico

**Comment by gmarziou** [comment]
Yes I saw it was working for you but for me it was the same as for Marcelino: when requesting /favicon.ico I could not get the jhipster favicon only the spring leaf.

**Comment by gmarziou** [comment]
I just looked at your mappings using http://www.jhipster-book.com/mappings and it shows : 

~~~~
/**/favicon.ico: {
bean: "faviconHandlerMapping"
}
~~~~

I'll try with my project tomorrow, @mraible could you share your .yo-rc.json file?

**Comment by jdubois** [comment]
I indeed think you shouldn't have to do anything: just put it on the root folder. In theory, what we currently have should work, and that's the most natural way of doing it (as seen in HTML5Boilerplate, look at the comment in the index.html).

You might have some cache issue, I've seen some browsers caching the favicon very aggressively.

-> I don't want to merge this until we have more information here. Besides, I would like to keep the favicon in the root directory like in HTML5Boilerplate

@gmarziou good catch to use the /mappings URL -> we should protect all those, and we already do for several URLs in the `SecurityConfiguration`, but Spring Boot keeps adding more. This is quite a security issue in Spring Boot, I think we do a good job in preventing those! I'll correct this ASAP.

**Comment by marcelinobadin** [comment]
Well, I had this problem with all my clients (tens of them) but I will try to go deeper in this problem and once I figure out I can let you know but anyway, the only way I have found to solve was that and now everybody sees the favicon

**Comment by mraible** [comment]
@gmarziou Here's my .yo-rc.json:

````
{
  "generator-jhipster": {
    "baseName": "blog",
    "packageName": "org.jhipster.book",
    "packageFolder": "org/jhipster/book",
    "authenticationType": "xauth",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "rememberMeKey": "abcdefg",
    "searchEngine": "elasticsearch",
    "enableTranslation": true
  }
}
````

**Comment by gmarziou** [comment]
I'm not sure it is related to caching otherwise it would have been jhipster face not spring leaf.

**Comment by jdubois** [comment]
Yes, good point, unless the user started a "normal" Spring Boot app before... This has happened to me!

**Comment by marcelinobadin** [comment]
Great! Simpler is better. Thank you.

**Comment by RI-VIPER** [comment]
Where do I find the root directory to put the favicon.ico. I replaced the default /src/main/webapp/favicon.ico with my own favicon.ico but I can't see the favicon.

**Comment by gmarziou** [comment]
Which version of jhipster?
