### ISSUE TITLE
Gradle on gateway microservice throwing error conflicting between ng-bootstrap and ng-jhipster

### ISSUE THREAD

**Issue by RiceRiceBaby** [jhipster/generator-jhipster#18121]
I have no idea how to resolve this error:

> Task :npmInstall FAILED
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: portfolio@0.0.1-SNAPSHOT
npm ERR! Found: @ng-bootstrap/ng-bootstrap@6.1.0
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"6.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @ng-bootstrap/ng-bootstrap@"^5.1.0" from ng-jhipster@0.13.0
npm ERR! node_modules/ng-jhipster
npm ERR!   ng-jhipster@"0.13.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2022-03-15T06_21_30_720Z-debug-0.log

**Comment by emilpaw** [comment]
Could you please provide the required information which is specified in the issue template? I recommend you directly use the issue template for future issues.

**Comment by mshima** [comment]
ng-jhipster is not supported anymore.
