### ISSUE TITLE
Unable to call services from Angular Factory

### ISSUE THREAD

**Issue by vitornobrega** [jhipster/generator-jhipster#1814]
I generate an app from hipster generator and create a new factory to call my services.

All the existing services are called with x-csrf token in the headers but when i try to make a Get or a Post with my factory, i get de error 401, Unauthorized

In my app config, i have this:

 //enable CSRF
    $httpProvider.defaults.xsrfCookieName = 'CSRF-TOKEN';
    $httpProvider.defaults.xsrfHeaderName = 'X-CSRF-TOKEN';
This is my factory:

angular.module('jhipsterApp')
    .factory('WalletsService', function ($http) {
        return {
            findAll: function () {
                return $http.get('api/walletslist/').then(function (response) {
                    return response.data;
                });
            }
        };
    });
When i execute findAll function, i get this error:

[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (walletslist, line 0)
The x-csrf is saved in cookies but how i pass it in the headers? It should not be automatic ?

**Comment by gmarziou** [comment]
Yes this is automatic and it works otherwise you could not login into the app.
This is very likely an issue in your code, it should be posted on stackoverflow and you may want to provide more information there:
- What makes you think it's a CSRF issue?
- Did you change the SecurityConfiguration?
- How is your REST controller written?
- Were you logged in?

**Comment by vitornobrega** [comment]
I'am not logged in. This is in the registration process. I need to call a service to get reference data.

The rest controller is like another services.
I need to change something in the security config?

**Comment by gmarziou** [comment]
For reference, the [question on stackoverflow](http://stackoverflow.com/questions/31819918/angular-jhipster-how-to-send-x-csrf-token-in-all-http-requests/31820608#31820608)

**Comment by vitornobrega** [comment]
I already had this configuration on my security config. 

I create a similar service file like the generated services for entities and try to call api/walletslist before log in and it works! But i need to have my factory. 

In the generated services file, all requests have $resource and i have $http to make requests in the factory. 
For this reason, i think i am missing something in the factory but i dont know what is...

**Comment by gmarziou** [comment]
On Stackoverflow please
