### ISSUE TITLE
Misc improvements to the JHipster POM

### ISSUE THREAD

**Issue by michaelisvy** [jhipster/generator-jhipster#1815]
* JHipster declares the Hibernate version explicitly:

```xml 
<hibernate.version>4.3.6.Final</hibernate.version>

```
Current version provided by Spring Boot is 4.3.10.Final. Can't we rely on the default?

Same goes for json-path (same version is declared in JHipster and Spring Boot. Can we just rely on Boot?

* json-path is declared as follows:
```xml
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>${json-path.version}</version>
            <scope>test</scope>
        </dependency>
```
There are some warnings in Eclipse because the version and scope are not necessary. Can we remove them?
Same question for HikariCP and liquibase-core. In both cases, the version is not necessary.

**Comment by gmarziou** [comment]
JHipster uses same property names as Spring Boot for dependencies, so this enable teh app developer to overwrite what SB offers which can be useful sometimes when we need  to upgrade for a fix in Hibernate that is not included in the version referenced by SB pom.

I just did it yesterday in my app.

**Comment by michaelisvy** [comment]
Thanks. I'm familiar with Spring Boot but was more asking why we redefine that property in particular (and not all the other libs). 
We usually consider that it's easier to let Spring Boot come with the default version of libs unless there is a specific issue.

In the case of Spring Security, I get it. The version coming with Boot is too old and JHipster wants to use the latest Spring Security. That's not the case for Hibernate.

**Comment by jdubois** [comment]
Yes, we need to have a look at each commit log for those versions -> they are normally here because we had an issue with the version provided by Spring Boot (by default we use the Spring Boot versions, and only override them if we have a good reason to do so)

**Comment by jdubois** [comment]
@michaelisvy I commited your PR

-> for Hibernate and Liquibase this is because I had some bugs some time ago, but now that both of them have newer versions they must be corrected. We should use Spring Boot's versions, but this is needs to be tested first.

**Comment by deepu105** [comment]
@atomfrede shouldnt the same be done for Gradle as well?

**Comment by atomfrede** [comment]
Yes gradle should use the same versions as mvn. Need to have a look at the "blessed" dependencies of the gradle spring boot plugin which versions they provide and compare them to the current versions in maven.

**Comment by deepu105** [comment]
ill commit a PR with some dependency updates first can you take a look and
remove the ones that are in spring boot

On Sat, Aug 8, 2015 at 2:01 PM, Frederik Hahne <notifications@github.com>
wrote:

> Yes gradle should use the same versions as mvn. Need to have a look at the
> "blessed" dependencies of the gradle spring boot plugin which versions they
> provide and compare them to the current versions in maven.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1815#issuecomment-128921569>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by atomfrede** [comment]
Here is the list of "blessed" dependencies. When they are provided without explicit version these versions are used: http://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html

**Comment by deepu105** [comment]
but most of it are bit outdated

On Sat, Aug 8, 2015 at 2:09 PM, Frederik Hahne <notifications@github.com>
wrote:

> Here is the list of "blessed" dependencies. When they are provided without
> explicit version these versions are used:
> http://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1815#issuecomment-128921804>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by jdubois** [comment]
Yes but there might be many issues with those dependencies, so we'd better go with what is already tested by the Spring team, and then only change (upgrade or downgrade!) what doesn't suit us. For exemple Liquibase (we do much more Liquibase testing than the Spring team!)

**Comment by deepu105** [comment]
Ok I took a look we have `dropwizard_metrics_version`, `javax_transaction_version` and `hibernate_entitymanager_version` which can be removed

**Comment by atomfrede** [comment]
Removing the explicit version in fact downgraded ``HikariCP`` don't if thats an issue, but maybe.

**Comment by michaelisvy** [comment]
Thanks for finishing the job. I realise I had missed plenty of libs by just focusing on the default settings in the generator. How did you guys test all of that? Did you just generate several projects by hand and deploy them? Or is there a more automated way?

**Comment by jdubois** [comment]
We have some automated tests available here:
http://jhipster.github.io/build_status.html

But a lot of issues are found manually, we have a lot of options, and many
parts which can be tested automatically... That's why I'm always careful
when we upgrade stuff!

On Mon, Aug 17, 2015 at 1:45 PM, michaelisvy <notifications@github.com>
wrote:

> Thanks for finishing the job. I realise I had missed plenty of libs by
> just focusing on the default settings in the generator. How did you guys
> test all of that? Did you just generate several projects by hand and deploy
> them? Or is there a more automated way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1815#issuecomment-131792202>
> .
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by jdubois** [comment]
Closing this since the PR is merged
