### ISSUE TITLE
Phantom installation failed error while trying to create new application

### ISSUE THREAD

**Issue by smart987** [jhipster/generator-jhipster#1817]
Hi, Please find the error stack while I am trying to create new application, I have entered all the options through command prompt to create the new application but while generating application I am getting the following error stack in my command prompt. Can any one help me in resolving this.  

-----------------------------------------------------------------------------------------------------

   create src\main\webapp\scripts\components\interceptor\auth.interceptor.js
   create src\main\webapp\scripts\components\interceptor\errorhandler.intercepto
r.js
   create src\main\webapp\scripts\components\interceptor\notification.intercepto
r.js
   create src\main\webapp\scripts\components\alert\alert.service.js
   create src\main\webapp\scripts\components\alert\alert.directive.js
   create src\test\javascript\karma.conf.js
   create src\test\javascript\spec\app\account\health\health.controller.spec.js
   create src\test\javascript\spec\app\account\login\login.controller.spec.js
   create src\test\javascript\spec\app\account\password\password.controller.spec
.js
   create src\test\javascript\spec\app\account\password\password.directive.spec.
js
   create src\test\javascript\spec\app\account\sessions\sessions.controller.spec
.js
   create src\test\javascript\spec\app\account\settings\settings.controller.spec
.js
   create src\test\javascript\spec\components\auth\auth.services.spec.js
   create src\main\webapp\assets\styles\documentation.css
   create src\main\webapp\assets\images\development_ribbon.png
   create src\main\webapp\assets\images\hipster.png
   create src\main\webapp\assets\images\hipster2x.png
   create src\main\webapp\index.html
   create .editorconfig
   create .jshintrc
|

> spawn-sync@1.0.13 postinstall D:\smartcuttings\node_modules\yo\node_modules\cr
oss-spawn\node_modules\spawn-sync
> node postinstall

npm WARN optional dep failed, continuing fsevents@0.3.7
npm WARN optional dep failed, continuing imagemin-jpegtran@4.3.0
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
|

> phantomjs@1.9.17 install D:\smartcuttings\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\madasuk\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.
zip
Receiving...
| [=======================================-] 96% 0.0s|
Received 7292K total.
Extracting zip contents
Removing D:\smartcuttings\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\madasuk\AppData\Local\Temp\phantomjs\phantomjs
-1.9.8-windows.zip-extract-1438772342055\phantomjs-1.9.8-windows -> D:\smartcutt
ings\node_modules\phantomjs\lib\phantom
Phantom installation failed { [Error: EPERM, operation not permitted 'D:\smartcu
ttings\node_modules\phantomjs\lib\phantom\phantomjs.exe']
  errno: -4048,
  code: 'EPERM',
  path: 'D:\\smartcuttings\\node_modules\\phantomjs\\lib\\phantom\\phantomjs.exe
',
  syscall: 'chmod' } Error: EPERM, operation not permitted 'D:\smartcuttings\nod
e_modules\phantomjs\lib\phantom\phantomjs.exe'
    at Error (native)
    at Object.fs.chmodSync (evalmachine.<anonymous>:948:18)
    at Object.chmodSync (D:\smartcuttings\node_modules\phantomjs\node_modules\fs
-extra\node_modules\graceful-fs\polyfills.js:141:17)
    at Promise._successFn (D:\smartcuttings\node_modules\phantomjs\install.js:14
4:10)
    at Promise._call (D:\smartcuttings\node_modules\phantomjs\node_modules\kew\k
ew.js:373:13)
    at Promise._withInput (D:\smartcuttings\node_modules\phantomjs\node_modules\
kew\kew.js:333:25)
    at Promise.resolve (D:\smartcuttings\node_modules\phantomjs\node_modules\kew
\kew.js:105:27)
    at resolver (D:\smartcuttings\node_modules\phantomjs\node_modules\kew\kew.js
:409:17)
    at next (D:\smartcuttings\node_modules\phantomjs\node_modules\fs-extra\node_
modules\rimraf\rimraf.js:72:7)
    at FSReqWrap.CB [as oncomplete] (D:\smartcuttings\node_modules\phantomjs\nod
e_modules\fs-extra\node_modules\rimraf\rimraf.js:108:9)
npm WARN optional dep failed, continuing fsevents@0.3.7
/

> utf-8-validate@1.1.0 install D:\smartcuttings\node_modules\grunt-browser-sync\
node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_mod
ules\ws\node_modules\utf-8-validate
> node-gyp rebuild

|
D:\smartcuttings\node_modules\grunt-browser-sync\node_modules\browser-sync\node_
modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-vali
date>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modu
les\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:114:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
 Windows_NT 6.3.9600
command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
cwd D:\smartcuttings\node_modules\grunt-browser-sync\node_modules\browser-sync\n
ode_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-
validate
 v0.12.7
 node-gyp -v v2.0.1
gyp ERR! not ok

> bufferutil@1.1.0 install D:\smartcuttings\node_modules\grunt-browser-sync\node
_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules
\ws\node_modules\bufferutil
> node-gyp rebuild

D:\smartcuttings\node_modules\grunt-browser-sync\node_modules\browser-sync\node_
modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\
npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  el
se (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:114:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
System Windows_NT 6.3.9600
command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\smartcuttings\node_modules\grunt-browser-sync\node_modules\brows
er-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modul
es\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> utf-8-validate@1.1.0 install D:\smartcuttings\node_modules\grunt-browser-sync\
node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\n
ode_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

|
D:\smartcuttings\node_modules\grunt-browser-sync\node_modules\browser-sync\node_
modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\no
de_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (no
de "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_module
s\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
 onfigure error|
stack Error: Can't find Python executable "python", you can set the PYTHON env v
ariable.
 stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_module
s\node-gyp\lib\configure.js:114:14)
stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\
configure.js:69:11
 stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
System Windows_NT 6.3.9600
 "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\b
in\\node-gyp.js" "rebuild"
cwd D:\smartcuttings\node_modules\grunt-browser-sync\node_modules\browser-sync\n
ode_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-clien
t\node_modules\ws\node_modules\utf-8-validate
node -v v0.12.7
 v2.0.1p -v|
not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0

> bufferutil@1.1.0 install D:\smartcuttings\node_modules\grunt-browser-sync\node
_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_
modules\engine.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

\
D:\smartcuttings\node_modules\grunt-browser-sync\node_modules\browser-sync\node_
modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\no
de_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "
C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\no
de-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
 onfigure error-
 Error: Can't find Python executable "python", you can set the PYTHON env variab
le.
     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:114:14)
stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\
configure.js:69:11
     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
System Windows_NT 6.3.9600
command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
 D:\smartcuttings\node_modules\grunt-browser-sync\node_modules\browser-sync\node
_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\n
ode_modules\ws\node_modules\bufferutil
node -v v0.12.7
 v2.0.1p -v|
not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> ws@0.4.32 install D:\smartcuttings\node_modules\karma\node_modules\socket.io\n
ode_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
D:\smartcuttings\node_modules\karma\node_modules\socket.io\node_modules\socket.i
o-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Fi
les\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\no
de-gyp.js" rebuild )  else (node  rebuild )
npm WARN optional dep failed, continuing bufferutil@1.1.0
|

> spawn-sync@1.0.13 postinstall D:\smartcuttings\node_modules\generator-jhipster
\node_modules\yeoman-generator\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

npm WARN prefer global yo@1.4.7 should be installed with -g
\

> yo@1.4.7 postinstall D:\smartcuttings\node_modules\yo
> yodoctor

|
Yeoman Doctor/
Running sanity checks on your system

 Global configuration file is valid
 NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version

Everything looks all right!
|
> yo@1.4.6 postinstall D:\smartcuttings\node_modules\generator-jhipster\node_mod
ules\yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version

Everything looks all right!
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.17 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\smartcuttings\npm-debug.log
? May bower anonymously report usage statistics to improve the tool over time? (
Y/n) Running "ngconstant:dev" (ngconstant) task
Creating module smartcuttingsApp at src/main/webapp/scripts/app/app.constants.js
...OK

Running "wiredep:app" (wiredep) task
Warning: Error: Cannot find where you keep your Bower packages. Use --force to c
ontinue.

Aborted due to warnings.

Execution Time (2015-08-05 11:01:30 UTC)
loading tasks    90ms  █████████ 19%
ngconstant:dev   20ms  ██ 4%
wiredep:app     360ms  ████████████████████████████████████ 77%
Total 470ms

**Comment by gmarziou** [comment]
This is not a jhipster issue, you should report it to phantomjs project.

Your node environment is not correct as you can see in the many errors you got.
-  'EPERM' : wrong file permissions on path: 'D:\smartcuttings\node_modules\phantomjs\lib\phantom\phantomjs.exe
- Error: Can't find Python executable "python", you can set the PYTHON env variable. you did not install Python or did not configure it ciorrectly

These are examples of the joy of working with NodeJS on Windows, you got this probably because phantomjs is a native module. Node native modules usually use gyp o build their binaries and this requires ptython and MSBuild.exe.

If you can't switch to Linux, you should try to unintsall node and install it through a manager like nodist and install it in a folder that does not require priveldges like "c:\Program FIles".

Other issue you may encounter: when your global node_modules directory is on one drive (e;g. C:) and your local project node_module is on another drive, some module may fail when trying to make link.

There are many others.

**Comment by deepu105** [comment]
Btw i used to get the same error but thatscoz of mcafee antivirus which
does a realtime check on .exe files causing phantom.js intall to go into
some kind of file lock.

So if you have mcafee turn it off and try npm install.  Not sure about
other antivirus

**Comment by gmarziou** [comment]
Right, so many potential issues with npm and Windows, I even got trouble once because I defined EDITOR environment variable :imp:

**Comment by egorlitvinenko** [comment]
I have this problem on Linux with npm from anaconda3, but without any environment errors in log, just error with phantomjs.
