### ISSUE TITLE
Pagination does not work with Elasticsearch

### ISSUE THREAD

**Issue by Ebsan** [jhipster/generator-jhipster#18191]
##### **Overview of the issue**

When using elasticsearch for entities the returned search results are not paginated. You're only given results up to the max amount in `pagination.constants.ts` and nothing more. 

##### **Motivation for or Use Case**

Pagination should work across the app on all returned results.

##### **Reproduce the error**

Create a new app with elasticsearch enabled and a sample entity. Then make sure the entities are indexed in elasticsearch and do a search. It may be easier to lower the `ITEMS_PER_PAGE` setting in `pagination.constants.ts` as well. Notice how returned results are not paginated.

##### **JHipster Version(s)**

7.7.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "jhipster",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1648052692663,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": ["Foo"],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.7.0",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en"],
    "lastLiquibaseTimestamp": 1648053173000,
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": "elasticsearch",
    "serverPort": "8080",
    "serverSideOptions": ["searchEngine:elasticsearch"],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Foo {
  bar String required
}
paginate Foo with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

git version 2.34.1.windows.1

node: v16.13.2

npm: 8.3.0

Docker version 20.10.13, build a224086

Docker Compose version v2.3.3

##### **Browsers and Operating System**

Windows and Linux. ALL Browsers.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@Ebsan Can you confirm if issue still persist in main?

**Comment by Ebsan** [comment]
Yes, the issue still persists in main.

**Comment by swilimo** [comment]
@DanielFran this bug really exists on jhipster, pagination  for elastic don't work otherwise if this fix is not implemented

**Comment by swilimo** [comment]
@DanielFran yes i work with this fix it works perfectly
