### ISSUE TITLE
ValidatedForm how to validate based on multiple fields?

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [jhipster/generator-jhipster#18236]
* **Overview of the request**

`ValidatedForm` is giving me a hard time, since it abstracts away react-hook-form so much that I do not know where to put validation for constrains that affect multiple fields. I know I can pass a validation function to each field individually, but how do I access the state of other fields from there?

* **Motivation for or Use Case** 

I have two fields. At least one of them needs to have a value.

* **Browsers and Operating System** 

n/a

* **Related issues** 
* 
n/a

* **Suggest a Fix** 

A pointer towards some docs or a hint as to how to validate a whole form and show an error would be great. Cheers

**Comment by deepu105** [comment]
ValidatedForm is just a handly utility for generated projects (to reduce size of generated code) for any customization just use react hook form directly instead of ValidatedForm
