### ISSUE TITLE
JHipster Statistics have had a significant drop

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#18238]
##### **Overview of the issue**

I just noticed that our statistics seems to have had a significant drop right after November 17, 2021. 

https://start.jhipster.tech/statistics

##### **Motivation for or Use Case**

Statistics can be useful to see the choices our users are making.

##### **Related issues**

@pascalgrimaud theorized that it could be from the v7.4.0 release.

![image](https://user-images.githubusercontent.com/17892/160653515-7ff36170-3380-4b09-b5b6-ffab81c74012.png)

**Comment by emilpaw** [comment]
I am looking into this issue.

**Comment by mraible** [comment]
This is still happening, so I'm increasing the bounty.

**Comment by atomfrede** [comment]
Just had a quick look, it seems even with force-insight it looks like the statistics are not send (or does linking the generator for local development somehow overrule the force parameter and I didn't see the condition?)

**Comment by emilpaw** [comment]
@atomfrede How do you check if it's sent or not? It seems to send with my local setup.

**Comment by atomfrede** [comment]
Works now or at least the method is called and axios has no error when posting the request.

**Comment by emilpaw** [comment]
I set up an HTTP interceptor and it shows that the generator in fact is sending out requests with correct looking statistics data. Later today I will take a look into the JHipster Online Server. Maybe it somehow does not accept the requests.

**Comment by atomfrede** [comment]
Awesome. So I don't do that with the interceptor.

**Comment by emilpaw** [comment]
The PR should fix the issue.

**Comment by atomfrede** [comment]
Nice work @emilpaw !

**Comment by emilpaw** [comment]
Hey, @DanielFran the fix was merged two months ago and there is no new release of JHipster Online yet. Almost four months of statistical data is missing at this point. 

What's the meaning behind adding it to the 7.9.0 milestone? I don't see a reason to wait for the next JHipster release.

**Comment by mraible** [comment]
I agree with @emilpaw. Can we release this soon?

**Comment by DanielFran** [comment]
@mraible I am back too from holidays, will try to sync with @pascalgrimaud to release it
