### ISSUE TITLE
Duplicate functions generated in Repository

### ISSUE THREAD

**Issue by thewhatsupguy** [jhipster/generator-jhipster#1824]
So I am trying to create an entity where two of the attributes have many to one relationships with the id of JHI_USER. This works fine except for generating findAllForCurrentUser twice in the Repository.java file. 

Removing the duplicate manually makes it work just fine. 

To reproduce this issue

.yo-rc.json

{
  "generator-jhipster": {
    "baseName": "xxx",
    "packageName": "com.yyy.xxx",
    "packageFolder": "com/yyy/xxx",
    "authenticationType": "xauth",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "d4b87cc15a83fabfa008a7b19ad521ab3e1cd85f"
  }
}

Entity.json

{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "reciever",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        },
        {
            "relationshipId": 2,
            "relationshipName": "sender",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "message",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": "1",
            "fieldValidateRulesMaxlength": "500"
        },
        {
            "fieldId": 2,
            "fieldName": "senttime",
            "fieldType": "DateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20150806163851",
    "dto": "no",
    "pagination": "pager"
}

**Comment by jdubois** [comment]
I haven't tested but I'm pretty sure this is indeed a bug!

**Comment by andidev** [comment]
I guess we should still create two methods but the find method names should also contain the field name.
E.g. in this case we should create

```
    @Query(...)
    List<Entity> findByRecieverIsCurrentUser();

    @Query(...)
    List<Entity> findBySendersIsCurrentUser();
```

Changes need to be done in [_EntityRepository.java](https://github.com/jhipster/generator-jhipster/blob/master/entity/templates/src/main/java/package/repository/_EntityRepository.java#L30)


I think this simple line of code should do it
```
    List<<%= entityClass %>> findBy<%= relationships[relationshipId].relationshipNameCapitalized %>IsCurrentUser();<% } } %>
```

**Comment by jdubois** [comment]
I didn't test this, but yes it sounds really logical. When I created that function we couldn't map an entity twice, this is why the code has this issue.
@andidev could you do a PR and close the ticket with it?
