### ISSUE TITLE
How to deploy changes to the frontend once the app is live under production.

### ISSUE THREAD

**Issue by alchemistgo87** [jhipster/generator-jhipster#1825]
I have a concern since the backend and frontend stays together, how one can deploy new changes to the frontend once the app is live and if we don't want to risk any downtime. How is it done? Can someone help please?

**Comment by jdubois** [comment]
If you use our default build system, with everything in one WAR file, you can't. You need to redeploy your application.

- Of course you could package your front-end code differently, but it's a lot more trouble
- This doesn't need to involve a downtime, you could do some blue/green deployment (in fact that's how it's supposed to be done normally)
- You're just going to have 10 seconds downtime anyway, so if blue/green deployment is too complex for you, you don't really need to worry

You should ask this on Stackoverflow, it is a far better place for such questions.
