### ISSUE TITLE
Lets generate, crud, service, repository UI & etc. from entities created by it self developer

### ISSUE THREAD

**Issue by shadyar** [jhipster/generator-jhipster#18263]
I have a feature request.
Sometimes it's easier to code entities for developers instead of using JDL; and JHipster will can do other tasks like creating UI, crud services, repository and etc. 
If JHipster has a command sets entities directory path as an argument then it would create mappers repositories etc from entities.

**Comment by atomfrede** [comment]
The JDL is central part of JHipster and should be the central part to define entities, application configurations etc. I don't think we will support a use case to generate jhipster specific parts from java source code (did I get your point correctly? If not feel free to reopen the issue.)
