### ISSUE TITLE
SQL Injection in Reactive project

### ISSUE THREAD

**Issue by appkr** [jhipster/generator-jhipster#18269]
I don't know whether this is the right place to ask this though...

In a reactive spring project with r2dbc, I found that SQL injection is actually possible. This may happen because of me, lacking knowledge on how to use r2dbc correctly. If it is case please let me know the correct usage.

#### Setup
- Jhipster 7.7.0
- reactive with Spring WebFlux? Yes
- type of database? SQL

#### JDL
```
entity Example {
	id String
  name String
}
```

#### Change I made
- Make /api/** be accessible without authorization header
- Make GET /api/examples accept query parameter of `name`, and bind the parameter to the `findAllBy(Pageable pageable, Criteria criteria)` repository method
- Make a request to `GET /api/examples?name=foobar';DROP TABLE example;--`

#### Result
- The sql rendered was `SELECT e.id AS e_id, e.name AS e_name FROM example e WHERE name = 'foobar';DROP TABLE example;--'`
- That actually dropped the table

<img width="1138" alt="스크린샷 2022-04-04 오전 7 53 32" src="https://user-images.githubusercontent.com/6471947/161452719-c6ac2e4b-d5ab-4f8e-868e-2de9a710f040.png">

**Comment by pascalgrimaud** [comment]
Cc @jhipster/developers

**Comment by atomfrede** [comment]
Didn't expect that. Is it the same for non reactive/hibernate?

**Comment by pascalgrimaud** [comment]
I think it's important to try and check

**Comment by jdubois** [comment]
On non-reactive, at least when I worked on it a few years ago, we were using Hibernate’s criteria API, which would prevent this.

**Comment by deepu105** [comment]
For non reactive i'll be extremely surprised if its the case since we don't do any direct SQL and everything goes via Spring Data and hibernate

**Comment by OmarHawk** [comment]
Probably came out of the following PR #13515

**Comment by deepu105** [comment]
@atomfrede are you working on this? else I can try to find a fix?

**Comment by atomfrede** [comment]
Wanted to start now.

**Comment by deepu105** [comment]
I have a CVE drafted for this ready to go once we have a fix in place. Let me know if you need any help

**Comment by atomfrede** [comment]
At least I can reproduce it too pretty easy :(

**Comment by atomfrede** [comment]
When mapping the criteria manually to a condition it is not vulnerable, but somehow this seems to me as not the intended way to use spring datas criteria. But using `.just(VALUE)` instead of `.just(WHOLE CRITERIA)` seems to do the trick. But creating the custom mapping will be a lot of code and most likely quite error prone.

```java
//Criteria.where("name").is("foobar';DROP TABLE example;--");
//name=foobar';DROP TABLE example;--
Comparison equal = Conditions.isEqual(
Column.create(criteria.getColumn(), Table.create("example")),
                    Conditions.just(criteria.getValue().toString()));

**Comment by atomfrede** [comment]
I have created a reproducer here https://github.com/atomfrede/reactive-sql-jhipster-reproducer which has a potential hand coded fix. Try it via `http://localhost:8080/api/examples?name=foobar';DROP TABLE example;--`. Without the changes it will indeed delete the table while with the hand coded condition it works correctly.

**Comment by deepu105** [comment]
@atomfrede how important is the where clause mapping? can we remove the feature for the time being if it only affects searching in Get queries? so that we can publish a fix and then look for a proper solution?

**Comment by atomfrede** [comment]
As far as I can tell the generated application does not need it by default I think. All crud operations should work without the custom criteria (need to check). So yes we might remove it for the time being.

**Comment by deepu105** [comment]
In that case I vote to remove it and publish a patch and CVE. Then we can create a new issue to add the feature in a secure and scalable way. @jdubois @pascalgrimaud @mraible @DanielFran @jhipster/developers WDYAT?

**Comment by pascalgrimaud** [comment]
Agree with this fix. We can see later if we can do better

**Comment by atomfrede** [comment]
So basically we will ignore the `Criteria` provided to `EntityManager.createSelect` right?

**Comment by deepu105** [comment]
yes, and maybe change signature in generated code, if possible, to not take the criteria and add a comment so that users don't end up adding the same manually

**Comment by DanielFran** [comment]
Yes, I agree too with this fix.

**Comment by deepu105** [comment]
Thanks to everyone involved @appkr @OmarHawk we have decided to award each of you a 300$ bounty so please claim it via open collective. @atomfrede for you, we (me, Julien, Pascal) think you deserve more than 500$ so I'll send a mail in the public group to discuss that.

**Comment by appkr** [comment]
@deepu105 Thanks, the claim was filed at https://opencollective.com/generator-jhipster/expenses/71638

**Comment by deepu105** [comment]
@appkr it's approved. Next time please do report security issues to project maintainers privately first so we can disclose it responsibly after fixing them.

**Comment by appkr** [comment]
@deepu105 My bad, sorry. Yes I will If I have any.

**Comment by OmarHawk** [comment]
> Thanks to everyone involved @appkr @OmarHawk we have decided to award each of you a 300$ bounty so please claim it via open collective. @atomfrede for you, we (me, Julien, Pascal) think you deserve more than 500$ so I'll send a mail in the public group to discuss that.

Thanks :-). Filed it at https://opencollective.com/generator-jhipster/expenses/71657

**Comment by mshima** [comment]
@deepu105 it's missing to tag the release at GitHub https://github.com/jhipster/generator-jhipster/releases.

**Comment by mraible** [comment]
I noticed there are two draft releases on the released page. We should fix that and remove all the dependabot updates. As a developer, I like to quickly skim release notes, not scroll through automated patch updates from dependabot.

**Comment by deepu105** [comment]
I'll clean those up once I have power back. Hopefully tonight or tomorrow
morning

**Comment by deepu105** [comment]
@mshima @mraible I dont think the release page is used at all, since I see a lot of drafts. @pascalgrimaud do you know who set up the release drafter? there are too many drafts and the date is wrong as well

**Comment by deepu105** [comment]
there are like pages and pages of them :P so that's gonna be some long task

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
I know, I spent a lot lot lot of time to delete it in jhipster-lite project, but didn't have motivation to do it for generator-jhipster...

**Comment by deepu105** [comment]
I created a ticket and assigned bounty lets see if someone is motivated

Thanks & Regards,
Deepu
