### ISSUE TITLE
Is it safe to deploy Jhipster app to AWS (Since it is mentioned to be in Beta version on Jhipster website)

### ISSUE THREAD

**Issue by alchemistgo87** [jhipster/generator-jhipster#1826]

**Comment by jdubois** [comment]
We can't test it, as it's a paying service. So as far as I'm concerned it's not safe, but people are using it and it seems OK.
Anyway, as always with OSS, we don't provide any guarantee.

**Comment by alchemistgo87** [comment]
But they provide free service for a year, so you can easily test it and stop the service after testing.

**Comment by jdubois** [comment]
@alchemistgo87 yes, I got a free year in 2010 :-)

**Comment by deepu105** [comment]
@alchemistgo87 it is indeed safe, i have been using it, manually it can be done and no issues, the sub gen just automates it so why dont you just try it out?
