### ISSUE TITLE
How can I implement Oauth2 and JWT for authentication (with mongodb as primary database)

### ISSUE THREAD

**Issue by alchemistgo87** [jhipster/generator-jhipster#1827]
I am using mongodb as my primary database. I need to implement Oauth2 authentication along with JWT Tokens so that every time the request does not hit the database for authentication. But I am not able to get a proper answer to this. Can anybody help?

**Comment by deepu105** [comment]
@alchemistgo87 this shouldbe askedon Stackoverflow with the Jhipster tag please.

**Comment by gmarziou** [comment]
i think he did it at same time: http://stackoverflow.com/questions/31864288/how-to-implement-oauth2-along-with-jwt-authentication-in-spring-boot
