### ISSUE TITLE
Not able to generate war files in target folder using gradle.

### ISSUE THREAD

**Issue by alchemistgo87** [jhipster/generator-jhipster#1828]
I am trying to create war files using the command: ./gradlew -Pprod bootRepackage in ubuntu. But no target folder or war files are being created, though it shows: "Build Successful" at the end. Where am I going wrong?

**Comment by atomfrede** [comment]
Gradle generates its artifacts in ``build\libs`` folder.

**Comment by alchemistgo87** [comment]
While running yo jhipster:cloudfoundry command it is trying to find it from target folder. Is there any workaround for this?

**Comment by atomfrede** [comment]
@jdubois It looks like cf is only compatible with maven (at least the cf ``index.js`` only contains mvn build commands)

**Comment by PeterEltgroth** [comment]
I'm currently using the [Cloud Foundry gradle plugin](http://docs.run.pivotal.io/buildpacks/java/build-tool-int.html#gradle-security). Follow the directions at the top of [the page](http://docs.run.pivotal.io/buildpacks/java/build-tool-int.html#gradle-security) to setup your Cloud Foundry credentials for the plugin, then in build.gradle add:

Note: 
* The application, target, etc names below are examples only
* You will need to setup the **services** section for those your application uses
* This assumes you have some familiarity with gradle and Cloud Foundry.
```
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${spring_boot_version}"
	classpath "org.cloudfoundry:cf-gradle-plugin:1.1.2"  // ADD THIS
    }
}

apply plugin: "cloudfoundry"

cloudfoundry {
	target = "https://api.run.pivotal.io"
	space = "development"
	application = "myApp"
	file = file("build/libs/my.war")
	uri = "myApp.cfapps.io"
	memory = 1024
	instances = 1

	services {
		// gradlew cfServicePlans show services available
		'myDB' {
			label = 'mongolab'
			plan = 'sandbox'
			bind = true
		}
		'myMail' {
			label = 'sendgrid'
			plan = 'free'
			bind = true
		}
	}
}
```

and to deploy:

````./gradlew -Pprofile=prod clean assemble cfPush```
