### ISSUE TITLE
Netlify preview links redirect to www.jhipster.tech

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#18302]
##### **Overview of the issue**

It should be possible to use Netlify to preview Jekyll builds of the www.jhipster.tech site. 

When PRs are submitted to the `jhipster.github.io` repo, the preview links are added correctly, but when you click on them, it redirects you to www.jhipster.tech.

##### **Motivation for or Use Case**

It'd be nice if it was possible to preview website changes before merging them.

##### **Reproduce the error**

Create a PR to modify the `jhipster.github.io` repo, wait for the preview link to show up in the comments, and then click on it.

##### **Related issues**

Discussion started in https://github.com/jhipster/jhipster.github.io/pull/1204#issuecomment-1088163188.

##### **Suggest a Fix**

 Not sure, but we don't need to do anything special for preview links to work on the Okta developer blog. It's a Jekyll site too.

**Comment by Falydoor** [comment]
Based on this post https://answers.netlify.com/t/jekyll-site-uses-absolute-urls-deploy-previews-navigate-to-main-site/8441/12, looks like that can be achieved using:

```yaml
[context.deploy-preview]
  command = "printf \"url: %s\" \"$DEPLOY_PRIME_URL\" > _config_netlify.yml; jekyll build --config _config.yml,_config_netlify.yml"
  ```

I don't think we have a `netlify.toml` in `jhipster.github.io`, who is in charge of the Netlify configuration?

**Comment by mraible** [comment]
I created the Netlify preview integration under my account. Can you please create a PR with this change so we can see if it works?

**Comment by Falydoor** [comment]
I tried on my fork and it works for most links!

https://deploy-preview-1--effortless-cocada-183a9f.netlify.app/

But some links are doing an infinite redirect:
- https://deploy-preview-1--effortless-cocada-183a9f.netlify.app/releases/

Not sure why and how it can be fixed ☹️

**Comment by mraible** [comment]
@Falydoor This is good enough for me! You can see it in action at https://github.com/jhipster/jhipster.github.io/pull/1210. Please claim the bug bounty.

**Comment by Falydoor** [comment]
@mraible Awesome!

Bounty claimed https://opencollective.com/generator-jhipster/expenses/76840
