### ISSUE TITLE
Circular Reference error with MongoDb

### ISSUE THREAD

**Issue by alchemistgo87** [jhipster/generator-jhipster#1830]
I am using Jhipster with mongodb as main database. Its running properly in localhost:8080. But when i deploy it to cloudfoundry, it crash with following exception: 
Nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'mongoDbFactory': Requested bean is currently in creation: Is there an unresolvable circular reference?

**Comment by atomfrede** [comment]
Maybe it has something to do with

> MongoDB cannot load its data with Mongeez because of #733.

**Comment by jdubois** [comment]
Yes this is not supported, as [written in the documentation](http://jhipster.github.io/cloudfoundry.html)

This is because of Mongeez, but you can easily do it manually, it's just a matter of running the scripts manually. We should remove Mongeez and find a better solution, eventually.

**Comment by alchemistgo87** [comment]
All right. Thank you for the help.

**Comment by alchemistgo87** [comment]
By the way what is Mongeez actually used for?
I have one more question:
If I remove the following lines from Jhipster code would it work:

@Bean
    @Profile("!" + Constants.SPRING_PROFILE_FAST)
    public Mongeez mongeez() {
        log.debug("Configuring Mongeez");
        Mongeez mongeez = new Mongeez();
        mongeez.setFile(new ClassPathResource("/config/mongeez/master.xml"));
        mongeez.setMongo(mongo);
        mongeez.setDbName(mongoProperties.getDatabase());
        mongeez.process();
        return mongeez;
    }

**Comment by atomfrede** [comment]
Mongeez is used for database migrations when using mongodb. Yes it might work, but you'll have no data in your mongodb.

**Comment by alchemistgo87** [comment]
ohh no data. Then how should I fix this issue. How should I deploy withoug mongeez as my main db is mongodb.

**Comment by gouravsood** [comment]
Hi Team, 
I have removed all the references of Mongeez but still getting this exception while deploying the application in Cloud.

**Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'mongoDbFactory': Requested bean is currently in creation: Is there an unresolvable circular reference?**

Can you please suggest what can be actual root cause?

Thanks, 
Gourav
