### ISSUE TITLE
Too many draft releases from release drafter

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#18319]
It seems like there are too many draft releases created by release drafter as if it's being created for every merge. We should change it so that its generated only when a new tag is pushed

Also the dates on the created draft seems to be wrong

https://github.com/jhipster/generator-jhipster/releases.

**Comment by atomfrede** [comment]
I can do the monkey work this evening, have some time.

**Comment by pascalgrimaud** [comment]
@atomfrede : only keep the most recent one :-)

**Comment by atomfrede** [comment]
I will now remove all drafts except the last one and try to exclude certain PRs from release drafter (especially dependabot, it's really too much)

**Comment by atomfrede** [comment]
I have also removed the latest draft, such that release drafter can create a new one with correct date too.

**Comment by atomfrede** [comment]
At first it looks good imho. Drafted release notes are empty by default, added the release-notes label to certain PRs.

**Comment by atomfrede** [comment]
Works fine, let's close this, if we need to/want to further adapt the config let's do that in another issue.

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/71751

**Comment by mshima** [comment]
@atomfrede the release-notes tag is required?
Should it be added to labeler https://github.com/jhipster/generator-jhipster/blob/main/.github/labeler.yml?

The 2 first v7.8.1 release note entries are not included at the release.

**Comment by atomfrede** [comment]
My idea was to mark entries explicit to make them eligible for the release note page

**Comment by mshima** [comment]
IMO we should add every PR to release note, just keep Dependabot out.

**Comment by pascalgrimaud** [comment]
I'm fine with what @mshima suggests
What do you think @atomfrede ?

**Comment by atomfrede** [comment]
Also fine for me, guess keeping them out will help already to have better release notes.

**Comment by atomfrede** [comment]
Updated the config with https://github.com/jhipster/generator-jhipster/pull/18327
