### ISSUE TITLE
FIx docs archive

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#18318]
Fix docs archive based on discussion -> https://groups.google.com/g/jhipster-dev/c/pX00gWQcDAQ/m/_jDrwzqwBAAJ?pli=1

1. Move all old archives (v0.x to v5.x) to a new repository for reference
2. Update links where applicable to point to this in the website
3. Update readme of generated projects to point to archives again

**Comment by anarsultanov** [comment]
Could someone create a new repository for the old archives and I would take care of this issue.

**Comment by deepu105** [comment]
@anarsultanov sure here it is https://github.com/jhipster/documentation-archive-v1-to-v5

**Comment by anarsultanov** [comment]
@deepu105 I've created a PR to this repository: https://github.com/jhipster/documentation-archive-v1-to-v5/pull/1
Now we need to merge it and set up the github pages, after which I will update the links to point to it.

**Comment by anarsultanov** [comment]
Here is another PR updating documentation-archive to reference the new website: https://github.com/jhipster/documentation-archive/pull/130

**Comment by anarsultanov** [comment]
PRs updating README of generated projects:
- https://github.com/jhipster/jhipster-sample-app-ng1/pull/1
- https://github.com/jhipster/devoxx-2016/pull/1
- https://github.com/jhipster/webflux-jhipster/pull/1

The following projects are archived and therefore not updated:
- https://github.com/jhipster/jhipster-php
- https://github.com/jhipster/jhipster-sample-app-token

**Comment by deepu105** [comment]
@anarsultanov no need to updated sample apps, what I meant was update the generator-jhipster project templates so a that a newly generated project refers to archive for the version rather than live docs

**Comment by anarsultanov** [comment]
@deepu105 sure, here it is https://github.com/jhipster/generator-jhipster/pull/18384
Should I close the other PRs or will you merge them as they have already been updated with the correct links?

**Comment by anarsultanov** [comment]
@deepu105 is there something still missing here?

**Comment by anarsultanov** [comment]
@pascalgrimaud @deepu105 anyone planning to merge PRs and close the issue?
