### ISSUE TITLE
Unique constraint added for one-to-one relationship (owner) 

### ISSUE THREAD

**Issue by Rapster** [jhipster/generator-jhipster#18329]
##### **Overview of the issue**

Follow up of https://github.com/jhipster/generator-jhipster/issues/5550

> I see that by default a unique constraint is added to the column for the owner side of the one-to-one relation, and I have tracked it down to the following commit:
https://github.com/jhipster/generator-jhipster/commit/528b0ecb0c453ce7dbad5961651943209afe02e9

##### **Motivation for or Use Case**

Taking that example: https://www.jhipster.tech/user-entity/#using-composition

I have a custom user having a one-to-one relationship to "Entite" for example, though I can't create two users on the same entite

##### **Reproduce the error**

```
relationship OneToOne {
    MyUser{jhiUser} to User
    MyUser{entite} to Entite
}
```

![image](https://user-images.githubusercontent.com/7521311/162569823-25774a92-2cb7-4f23-9d7c-5357424d36be.png)

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/5550

##### **Cause**

Commit: https://github.com/jhipster/generator-jhipster/commit/528b0ecb0c453ce7dbad5961651943209afe02e9

##### **Suggested Fix**

Give the possibility to configure unique to false

##### **JHipster Version(s)**

7.7.0

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
That’s how one-to-one works.
Se the reason the original issue was closed.

**Comment by Rapster** [comment]
I'm guessing you're referring to this:

> If it's not unique, then this isn't a one-to-one relationship at the database level.

Which I don't think is quite true, otherwise sample like this _(based on JHipster Studio)_ wouldn't work:

```
// defining multiple oneToOne relationships
relationship OneToOne {
	JobHistory{job} to Job,
	JobHistory{department} to Department,
	JobHistory{employee} to Employee
}
```

Or am I missing something?

**Comment by mshima** [comment]
The JobHistory example won’t work.
Seems you are trying to add an OneToOne from JobHistory to the Job, Department, employee tuple.
Each OneToOne relationship is independent and the result is that each Employee, Department and Job can have only one JobHistory.
