### ISSUE TITLE
OAuth Authentication won't allow some special characters in passwords

### ISSUE THREAD

**Issue by briancmills** [jhipster/generator-jhipster#1834]
Certain special characters, specifically '+', won't be allowed in passwords when you are using OAuth because the password is not URI encoded before being posted to the authentication service.

Steps to reproduce:

* Generate a new application with all default answers, except using OAuth tokens for authentication.  
*  Run the webapp and login as 'admin'
*  Change the password for admin to '12345+'
*  Logout, attempt to log back in with the new password.  It will fail because the + symbol is converted to a space instead of being URI encoded. 

I fixed this in my local project by wrapping the password in the function encodeURIComponent(credentials.password).  This results in "12345%2B" being sent to the backend and allows authentication to succeed.  

I did not research whether this bug applies to any of the other authentication schemes.

**Comment by jdubois** [comment]
Sounds like an issue, indeed! Could you provide a PR?

**Comment by gmarziou** [comment]
Looks similar to #620

**Comment by briancmills** [comment]
Sure, I will take a stab at a PR.
