### ISSUE TITLE
Display a link to a filtered view for the Many Side of a OneToMany / ManyToOne relationship on the One side

### ISSUE THREAD

**Issue by OmarHawk** [jhipster/generator-jhipster#18370]
##### **Overview of the feature request**
Hi,

In case of OneToMany / ManyToOne relationships, we do already have a link to the "One" Side within the "Many" part of the relationship within the detail view but also within the list view, so that we can access the one specific entity that is being referenced. In some cases, it would be helpful to also have the other way round available in both views (list & view), so a link from the "Many" Side to see all the "Ones".

##### **Motivation for or Use Case**
Example: 
We do have a MainEntity with referenced LogEntry. So, we have a relationship model like this (simplified model of the actual application):

```
entity MainEntity {
   @Id uuid UUID
   sdate Instant
   processname String
}

entity LogEntry {
   message String
}

relationship ManyToOne {
   LogEntry{mainEntity} to MainEntity{logEntry}
}
```

Then, we normally want to easily see all the referenced `LogEntry` lines for the `MainEntity`. At the moment, we would now need to implement some custom UI / filtering to allow this (at last haven't found any way to activate such a thing), even though I do see this as a not so uncommon use case, so that maybe other projects beside mine could benefit from this.

##### **Related issues or PR**
Nothing found. Maybe haven't looked far enough. ;-)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by OmarHawk** [comment]
If that is somewhat interesting for the general jhipster project, I'd try to contribute this feature with a Pull Request.

**Comment by OmarHawk** [comment]
Well, in my own project, I implemented a draft implementation (adjusting the generated code) and it works quite well, using the filter option to generate the API methods. So I think, it would be just a smaller step to pprovide such a thing within the generator. I solely implemented this now for Angular frontend...

**Comment by DanielFran** [comment]
@OmarHawk Can you contribute with a PR? Since you already implemented it, it would be easier to evaluate such changes

**Comment by vishal423** [comment]
@OmarHawk, Do you mean to display many side entities on one side entity view? Do we fetch those in API as default?

**Comment by OmarHawk** [comment]
No, I do show the filtered list view of the "many"-side with a small UI to indicate it is filtered on certain attributes + allowing to clear certain or all applied filters.

Also the PR just adds general filtering capabilities to all entities where filtering API is enabled - but I only do make use of it for now for that single Use Case (Show a button to show the mentioned filtered List). even though it can easily be extended for other use cases - or used by some custom frontend. That's also why the shown filters that are currently being applied there looks rather "rudimentary" ;-)

**Comment by vishal423** [comment]
I see. Can you share screenshots of how the UI looks after your change?

**Comment by OmarHawk** [comment]
> I see. Can you share screenshots of how the UI looks after your change?

With the following JDL:
```
entity MainEntity {
   @Id uuid UUID
   sdate Instant
   processname String
}

entity LogEntry {
   message String
}

relationship ManyToOne {
   LogEntry{mainEntity} to MainEntity{logEntry}
}

filter all
paginate all with pagination
```

Note the "filter all" - means it works only in configurations where the filter option works. 
Note additionally the "paginate all with pagination" - means it works only where there is some actual pagination on the other side of the relationship. I have saved myself from adding route handling to the "no / infinit-scrolle " option for now, as there is currently no route handling at all then - and I wanted to get it done t least for one configuration. _Something for the 2nd step, I think._

And when you then select angularX as frontend framework, we do get the following kind of frontend on the page (One side):
![2022-05-12_18h11_12](https://user-images.githubusercontent.com/2911492/168123825-f8860e0a-01c9-4111-a428-b4cbd547c694.png)

And when following the link to the many side (first button in the right column), it looks like this:
![2022-05-12_18h11_20](https://user-images.githubusercontent.com/2911492/168123845-ec3d859d-35e8-4c2c-a15b-a93b25e36de3.png)

You can the delete either one certain filter by pressing the x behind the specific one - or all in one go by pressing the overall x and if there is no more filter applied, it looks again "normal":
![2022-05-12_18h11_30](https://user-images.githubusercontent.com/2911492/168124117-733864e4-5665-46f7-ba78-4e6280849f83.png)

As mentioned, you could also just use other and multiple `filter[filterName]=filterValue` within the normal angular route to filter for more or different kind of things.

**Comment by OmarHawk** [comment]
The same thing also does work for ManyToMany relationships in the very same way.

**Comment by Tcharl** [comment]
So cool
