### ISSUE TITLE
Custom Validation Support

### ISSUE THREAD

**Issue by olgunkaya** [jhipster/generator-jhipster#18371]
##### **Overview of the feature request**

Custom validation messages for custom regexps on fields. 

##### **Motivation for or Use Case**

I needed to apply a special pattern for one of my field, generator did it's job and applied these on my field etc.. Spring boot also can manage it pretty good. But when error happened, field response includes the regexp itself, which in this case not so helpfull for the end user. 

##### **Related issues or PR**

N/A

- [ x] Checking this box is mandatory (this is just to show you read everything)

P.S : I am not so good with generators etc.. if someone can assist (mentoring) me a bit, I can try implementing this myself. On my own generated project I did this manually.

**Comment by Tcharl** [comment]
Hi,

You can modify the `webapp/i8n/<lang>/<entity>.json#YourError` to modify the displayed label.

Feel free to reopen if I didn't understand the question

**Comment by olgunkaya** [comment]
@Tcharl  thanks for the comment. 

Let me give an example about my question. 

**A backend only application, no webapp folder in project structure**
I have a special email format ( cuz @Email basically matches anything :) ), thus I decided to use OWASP email format. 

`public static final String EMAIL_REGEXP = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
`

```
@Pattern(regexp = Constants.EMAL_REGEXP)
private String email;
```

When an email does not match OWASP regexp format, the error response is like below (ConstraintViolationException resolved by the exception resolver, controller advice).

> ".... should match ^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$" 

I would like to modify this violation message something like more user friendly :)

**Comment by olgunkaya** [comment]
@Tcharl sorry for flooding;

I just tried the messages.properties also under resources/i18n/messages.properties
As you can see it's not recognized as a message key in above file.  

```
{
    "title": "Method argument not valid",
    "status": 400,
    "path": "/api/login",
    "message": "error.validation",
    "fieldErrors": [
        {
            "objectName": "login",
            "field": "password",
            "message": "{weird.response.message}"
        }
    ]
}
```

**Comment by Tcharl** [comment]
You do not flood whoever, don't worry.
The message key is not in the resource folder, but in your webapp.

Take a look at your forms html page or the component that is validating your message, you'll always have a `translate` thing with a key (i.e. `entity.validation.foo`)

First here, You can either modify this key if it's a common one among all the validation.
And you can find the message that will be displayed to the end user for that key in your `<project>/webapp/i18n/<lang>/*.json`.

I hope it will help

**Comment by olgunkaya** [comment]
Thanks @Tcharl ,

my app is backend-only app. So no webapp folder at all. Currently, I am on mobile, I’ll share the folder structure once I got my pc running.

**Comment by Tcharl** [comment]
In this case, look at how the exceptiontranslator class works, you'll always have an exception key, that will let you insert your custom message at the front-end level (I encourage to generate a jhipster sample with frontend to see how it works)

**Comment by olgunkaya** [comment]
Thanks again. 
I’ll check it than. 

Teşekkürler
Olgun Kaya
