### ISSUE TITLE
The Croatian translation for global.entity.action.view is wrong

### ISSUE THREAD

**Issue by AntonioJuresic** [jhipster/generator-jhipster#18386]
##### **Overview of the issue**

The Croatian translation for `global.entity.action.view` in `global.json` is wrong. The current translation is `Preged` which is probably a typo. The correct translation would be `Pregled`.

[https://glosbe.com/hr/en/pregled](https://glosbe.com/hr/en/pregled)

##### **Reproduce the error**

To reproduce the error, just simply create a project with the translation to Croatian language. Going into a list of the entity the wrong translation should be visible.

##### **Suggest a Fix**

Change the value from `Preged` to `Pregled`.

##### **JHipster Version(s)**

Jhipster - 7.7.0

**Comment by DanielFran** [comment]
Hello @AntonioJuresic can you do a PR with the changes?

**Comment by AntonioJuresic** [comment]
Will do @DanielFran.

**Comment by AntonioJuresic** [comment]
Hi @DanielFran I did a PR.
