### ISSUE TITLE
Getting status 401 on auth/login on gateway

### ISSUE THREAD

**Issue by dronavallisaikrishna** [jhipster/generator-jhipster#18406]
##### **Overview of the issue**
auth/login is giving 401 in my external react client but working on the postman.

I have a jhipster uaa and gateway(running on 8080) with react. I have been working on the same UI and want to make a separate UI application. But as soon as I hit the auth/login OPTIONS API is giving 200 but the Actual auth/login API is giving 401. Weirdly if I hit the API in postman its working fine.
##### **Motivation for or Use Case**
I am trying to retire the Gateway UI that comes with jhipster gateway app and trying to build my own react app.

##### **Reproduce the error**
Using axios client in a react app. Simply as shown below.
```
import axios from 'axios';

export default axios.create({
  baseURL: `http://localhost:8080/`, 
  headers: {
    'Content-Type': 'application/json',
  },
});

axios
          .post('auth/login', {
            username: email,
            password: password,
          })
          .then(({ data }) => {
            console.log("data is:-", data);
            if (data) {
              localStorage.setItem('token', data.access_token);
              axios.defaults.headers.common['Authorization'] = 'Bearer ' + data.access_token;
              dispatch(fetchSuccess());
              dispatch(JWTAuth.getAuthUser(true, data.access_token));
            } else {
              dispatch(fetchError(data.error));
            }
          })
          .catch(function (error) {
            dispatch(fetchError(error.message));
          });

```
SecurtyConfiguration in gateway(No additional changes made to this file besides what comes while generating the APP/)
```
@Override
    public void configure(HttpSecurity http) throws Exception {
        http
            .csrf()
            .disable();
//            .ignoringAntMatchers("/h2-console/**")
//            .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
        http
            .addFilterBefore(corsFilter, CsrfFilter.class)
            .headers()
            .frameOptions()
            .disable()
        .and()
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        .and()
            .authorizeRequests()
            .antMatchers("/api/**").authenticated()
            .antMatchers("/management/health").permitAll()
            .antMatchers("/management/info").permitAll()
            .antMatchers("/management/prometheus").permitAll()
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN);
    }
```

##### **JHipster Version(s)**
6.2.0

##### **Browsers and Operating System**

Mac Os Bigsur 11.1
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Hi,

Can you post a jdl that fails at login? We don't know if you're using oauth2 or jwt.
We don't know neither if our frontend generation fails, and jhipster is not meant to fix bugs that are not following the frontend generation.
If you succeed to get a full generated gateway and it's react front failing, I would be glad to help or review your PR.

Best regards,

**Comment by eapriansyah** [comment]
permit access / and /*.*

@Override
    public void configure(HttpSecurity http) throws Exception {
        http
            .csrf()
            .disable();
//            .ignoringAntMatchers("/h2-console/**")
//            .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
        http
            .addFilterBefore(corsFilter, CsrfFilter.class)
            .headers()
            .frameOptions()
            .disable()
        .and()
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        .and()
            .authorizeRequests()
            .antMatchers("/").permitAll()
            .antMatchers("/*.*").permitAll()
            .antMatchers("/api/**").authenticated()
            .antMatchers("/management/health").permitAll()
            .antMatchers("/management/info").permitAll()
            .antMatchers("/management/prometheus").permitAll()
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN);
    }

**Comment by DanielFran** [comment]
Those questions should be addressed directly in StackOverflow.
Closing
