### ISSUE TITLE
SwaggerUI via Manual Distribution

### ISSUE THREAD

**Issue by olgunkaya** [jhipster/generator-jhipster#18407]
Today, I spent considerable amount of time to figure out what's going on with swagger UI and realized that **jhipster** only includes mvc artifact with the swagger-ui web distro in webapps. 

Is there any specific reason to not to go with ([link](https://springdoc.org/#getting-started))
```
   <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-ui</artifactId>
      <version>x.y.z</version>
   </dependency>
```

but instead go with mvc configurer [ in this link ](https://springdoc.org/#spring-webmvc-support ?
  ```
 <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-webmvc-core</artifactId>
      <version>x.y.z</version>
   </dependency>
```

I added the above mentioned ui with proper version (in my case 1.6.6) and now it works, displayes the UI. But not sure if I do this correct/properly.

**Comment by mshima** [comment]
We provide swagger at the client side.
Our swagger config is microservice aware. Springdoc provided one is not.
The springdoc swagger ui makes sense to monolith with skipClient only.

There is a closed bug about this solution.
Don't know if we have documentation about this, we could add.

**Comment by olgunkaya** [comment]
I think, I hit the condition, skipClient and monolith :) 

Teşekkürler
Olgun Kaya
