### ISSUE TITLE
change liquibase xml changelog to json or YML

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1840]
currently liquibase changesets are the only xml stuff we have. Liquibase supports yml and json as well, so if we convert to any of that we can be truly xml free.

I would prefer Json as it is easier to read and process

**Comment by gmarziou** [comment]
What about pom.xml? :smile:  Unless you use gradle of course.

I'm wondering whether maven liquibase plugin could read datasource properties from our application.yml to avoid duplcation.

**Comment by deepu105** [comment]
ya that part is also annoying

**Comment by gmarziou** [comment]
I just read their docs, unfortunately it can read only properties file but maybe we could generate properties from yml as part of the build.

**Comment by jdubois** [comment]
The issue with yml and JSON is that you don't have validation or auto-completion.
And with JSON you can't even write comment.
So for this kind of thing XML looks a lot better to me.

**Comment by gmarziou** [comment]
Fully agree with you about lack of comments in json, such a pain for npm and bower.

Auto-completion is the same issue in yml and xml: you need a reference, if you don't have an xsd or dtd then xml is not better.

You can have auto-completion for yml in IDEA, I just found it recently, it"s like HTML when it does not know a tag you can ask it to learn it, JHipster could generate this file, it would make editing application.yml easier to edit.

Anyway regarding liquibase duplication of datasource in pom, I think we could try [yaml-properties-plugin](https://github.com/aadnk/yaml-properties-plugin) which is only few lines of code.

**Comment by deepu105** [comment]
The  comments argument makes sense.

**Comment by atomfrede** [comment]
I also have not that much of a problem with xml changesets, so let's keep them.

**Comment by deepu105** [comment]
ok agree lets close this then.
