### ISSUE TITLE
Update React version to 18

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#18416]
##### **Overview of the feature request**

Keep react updated to latest version

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
cc @qmonmert

**Comment by qmonmert** [comment]
we need to upgrade react-jhipster also

**Comment by qmonmert** [comment]
@pascalgrimaud @jdubois bug bounty claimed https://opencollective.com/generator-jhipster/expenses/80687 🙂
