### ISSUE TITLE
Switch testFrameworks in samples from protractor to cypress

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#18415]
##### **Overview of the feature request**

Protractor has been deprecated in favour of cypress

##### **Motivation for or Use Case**

Align samples with the default in generator

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
cc @pascalgrimaud

**Comment by pascalgrimaud** [comment]
It's doable.
For that, we need to update all .yo-rc.json in all samples and it will be updated during the next release

**Comment by DanielFran** [comment]
You mean just change this line: https://github.com/jhipster/jhipster-sample-app/blob/main/.yo-rc.json#L47

**Comment by pascalgrimaud** [comment]
@DanielFran : exactly

**Comment by DanielFran** [comment]
Thanks @pascalgrimaud, will assign it to me ;)

**Comment by DanielFran** [comment]
@pascalgrimaud All PRs have been created

**Comment by pascalgrimaud** [comment]
we can close this, as it will be updated during next release
