### ISSUE TITLE
Generating new entity. Pluralization.

### ISSUE THREAD

**Issue by lluiscanals** [jhipster/generator-jhipster#1841]
Hi, I have created new entinty (address) with this configuration:

"relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "login"
        }
    ] ......
   "changelogDate": "20150807161042",
    "dto": "mapstruct",
    "pagination": "infinite-scroll"

I have found two things. First that when pluralizing it appends one "s", it should be "es". For example the addresss.html generated file, or the rest controller --> POST  /addresss -> Create a new address. Notice the 3's.

The other thing is that when trying to save or update one address and assign to a user, the user was never saved, so I changed this in src/main/webapp/scripts/app/entities/address/address-dialog.html

ng-model="address.user.id" ng-options="user.id as user.login for user in users"

to

ng-model="address.userId" ng-options="user.id as user.login for user in users"

and begins to work. It seems that the generated json passed to the rest controller is not generated the way that DTO expects.

Hope it helps! Thanks for your excellent work.

**Comment by MathieuAA** [comment]
Hi!

The first "thing" is more of an enhancement, and i believe [this](https://www.npmjs.com/package/inflection) lib can do the trick (I suggest you create a separate "issue" for that).
The second "thing", however, is an issue. If you have time, can you do a PR for this?

**Comment by jdubois** [comment]
- pluralization has already been widely discussed. The current system isn't perfect from a "human" point of view but at least everybody can find the URLs easily, and if you want to get them from another language (which wouldn't have the same pluralization lib) then it's also easy to use.
If you want a better name it's also very simple to change, anyway.
- your other issue comes from Mapstruct. It's an already oppened issue, and that's also why DTOs are still in beta. Have a look in the other opened issues (sorry, I'm only using my phone at the moment).
