### ISSUE TITLE
Suppress the `jhipster upgrade` unify blueprints configuration question

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#18425]
##### **Overview of the issue**

I've upgraded a couple of apps from 7.7 to 7.8 using the `jhipster upgrade` command. It seems to prompt me for the unify blueprints configuration question every time. This seems like it should be a one-time thing that goes away when you select yes. 

##### **Motivation for or Use Case**

Developer experience.

<img width="1442" alt="Screen Shot 2022-04-20 at 21 04 57" src="https://user-images.githubusercontent.com/17892/164363777-cc224018-7508-4bfd-8ec1-885ae51f0d2e.png">

##### **Reproduce the error**

Upgrade an app multiple times between patch versions.

**Comment by mshima** [comment]
Fixed in https://github.com/jhipster/generator-jhipster/pull/19655.
