### ISSUE TITLE
Is there a way to switch frontend from no to Angular?

### ISSUE THREAD

**Issue by jchvidal** [jhipster/generator-jhipster#18421]
##### **Overview of the issue**

Change the frontend of a JHipster generated from no (no frontend) to Angular

##### **Motivation for or Use Case**

I've  created a projet with no frontend. But now i need an angular frontend (mostly for the admin interface). I tried to modify .yo-rc.json file setting "clientFramework" to "angularX" and rerun jhipster --with-entities. 
But nothing happens. 

##### **Related issues**

I found the topic to switch from Angular frontend to react, but it dont't work.

**Comment by mshima** [comment]
`jhipster --client-framework angularX --no-skip-client --with-entities`

**Comment by jchvidal** [comment]
OK. Thanks a lot !
