### ISSUE TITLE
Names are limited to 30 characters when using oracle

### ISSUE THREAD

**Issue by naris** [jhipster/generator-jhipster#18424]
When generating entities I constantly get "The table name for this entity is too long to form constraint names. Please use a shorter table name" unless the names are too short to be meaningful, this is not acceptable!

Oracle has supported 128 characters names for a **long** time. In fact, any version of the Oracle database (<=12.1) that supported only 30 character has gone end-of-life and is no longer supported so why does jhipster insist on only allowing 30 character names?

**Comment by mraible** [comment]
This is a reasonable request. Can you please create a pull request to fix it?

https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md

**Comment by naris** [comment]
I have submitted a pull request for this. However in making the change I noticed that askForTableName() in generators/entity/prompts.js imposes a 30 character for table names for all databases (and it used to impose a 14 character limit for Oracle) so I changed it tp impose a 112 character limit for oracle (128 - 16 character since it was 14 for 30) and 30 characters for everything else.

I doubt this is the correct thing too do but I am not aware of why a 30 character limit was imposed for all databases here?

This is the original code:
```
        if (prodDatabaseType === 'oracle' && input.length > 14 && !skipCheckLengthOfIdentifier) {
          return 'The table name is too long for Oracle, try a shorter name';
        }
        if (input.length > 30 && !skipCheckLengthOfIdentifier) {
          return 'The table name is too long, try a shorter name';
        }

```

**Comment by mraible** [comment]
@jdubois Do you know why we've limited the length of table names historically?

**Comment by naris** [comment]
The askForTableName() function mentioned above only gets called when prompting the user for a table name to replace an invalid one.

There are also other places that check for different limits for different databases.

generators/entity/index.js had 2 different checks for oracle:
```
    } else if (prodDatabaseType === ORACLE && entityTableName.length > 26 && !skipCheckLengthOfIdentifier) {
      return `The table name is too long for Oracle, try a shorter name.\n${instructions}`;
    } else if (prodDatabaseType === ORACLE && entityTableName.length > 14 && !skipCheckLengthOfIdentifier) {
      this.warning(
        `The table name is long for Oracle, long table names can cause issues when used to create constraint names and join table names.\n${instructions}`
      );
```

getJoinTableName() in generators/generator-base.js had these checks:
```
    if (prodDatabaseType === ORACLE && joinTableName.length > 30 && !this.skipCheckLengthOfIdentifier) {
      this.warning(
        `The generated join table "${joinTableName}" is too long for Oracle (which has a 30 character limit). It will be truncated!`
      );

      limit = 30;
    } else if (prodDatabaseType === MYSQL && joinTableName.length > 64 && !this.skipCheckLengthOfIdentifier) {
      this.warning(
        `The generated join table "${joinTableName}" is too long for MySQL (which has a 64 character limit). It will be truncated!`
      );

      limit = 64;
    } else if (prodDatabaseType === POSTGRESQL && joinTableName.length >= 63 && !this.skipCheckLengthOfIdentifier) {
      this.warning(
        `The generated join table "${joinTableName}" is too long for PostgreSQL (which has a 63 character limit). It will be truncated!`
      );

      limit = 63;
    } else if (prodDatabaseType === MARIADB && joinTableName.length > 64 && !this.skipCheckLengthOfIdentifier) {
      this.warning(
        `The generated join table "${joinTableName}" is too long for MariaDB (which has a 64 character limit). It will be truncated!`
      );

      limit = 64;
    }

```

and getConstraintNameWithLimit() in generators/generator-base.js had these checks:
```
    if (prodDatabaseType === ORACLE && constraintName.length >= 27 && !this.skipCheckLengthOfIdentifier) {
      this.warning(
        `The generated constraint name "${constraintName}" is too long for Oracle (which has a 30 character limit). It will be truncated!`
      );

      limit = 28;
    } else if (prodDatabaseType === MYSQL && constraintName.length >= 61 && !this.skipCheckLengthOfIdentifier) {
      this.warning(
        `The generated constraint name "${constraintName}" is too long for MySQL (which has a 64 character limit). It will be truncated!`
      );

      limit = 62;
    } else if (prodDatabaseType === POSTGRESQL && constraintName.length >= 60 && !this.skipCheckLengthOfIdentifier) {
      this.warning(
        `The generated constraint name "${constraintName}" is too long for PostgreSQL (which has a 63 character limit). It will be truncated!`
      );

      limit = 61;
    } else if (prodDatabaseType === MARIADB && constraintName.length >= 61 && !this.skipCheckLengthOfIdentifier) {
      this.warning(
        `The generated constraint name "${constraintName}" is too long for MariaDB (which has a 64 character limit). It will be truncated!`
      );

      limit = 62;
    }

```

**Comment by jdubois** [comment]
@mraible this was because there was a limit in the table names in Oracle, but I believe this was removed in newer versions of the database. This was coded by @deepu105

**Comment by mshima** [comment]
Tables names should be changed only for v8.
Otherwise we will have lots of database breaking changes.
We can open an exception for oracle because we have a bad experience with current limits.

I did some table names changes for v7 fixing some issues like adding a additional `_` splitting relationships because
TableOne - Table = table_one_table
Table - OneTable = table_one_table
But table_one__table != table__one_table
And adding some validation digits for truncated name conflicts.

But kept most of old behavior. We can do something more dynamic to calculate table name for v8.

**Comment by DanielFran** [comment]
@mshima

For Join tables, no changes applied, except the validation for PostgreSQL that was considering 63 characters has the minimum to truncate the name instead of considering 64 ([here](https://github.com/jhipster/generator-jhipster/pull/18556/files#diff-6b3a4e19c79c8b302650b8b7466ce6e01e78d0e2f3105d87e9e55b9d6f4cb32dR1772))

For constraints, the refactor is to simplify the logic, it should not have impacts.

**Comment by mshima** [comment]
I prefer avoiding limits changes for v7 cycle:

<img width="916" alt="Captura de Tela 2022-05-04 às 14 15 32" src="https://user-images.githubusercontent.com/1417183/166743442-dd50dda9-d99b-453f-9421-68591ab87fbb.png">

**Comment by DanielFran** [comment]
@mshima I reverted changes, it will use new method only for Oracle.

**Comment by deepu105** [comment]
for context when I originally put in the limits (long time ago), there were limits on Oracle and maybe other DBs, most of those limits are probably not valid anymore. But the main constraint was also generating join table names and constraint names from long table names. As @mshima mentioned probably we should change these only for v8 to avoid breaking stuff.

**Comment by DanielFran** [comment]
Changes for Oracle has been merged, for other DBs draft PR is done with label v8
