### ISSUE TITLE
Microfrontend option not available in v7.8.0 and v7.8.1

### ISSUE THREAD

**Issue by jaydeep-punjani** [jhipster/generator-jhipster#18422]
##### **Overview of the issue**
Unable to see the Microfrontend option on creation of a new microservice application.

##### **Motivation for or Use Case**
Microfrontend

##### **Reproduce the error**
Create a new application using "jhipster" command.

##### **JHipster Version(s)**
v7.8.0 and v7.8.1

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
If you specify `clientFramework` for each microservice in your JDL, it'll use microfrontends. See this sample JDL:

https://github.com/jhipster/jdl-samples/blob/main/reactive-mf.jdl

**Comment by jaydeep-punjani** [comment]
@mraible got it, thanks. Will there be a way to do this via the CLI like in earlier versions ?

**Comment by mshima** [comment]
There's a status update by version at https://github.com/jhipster/generator-jhipster/issues/17031.
