### ISSUE TITLE
Generated tests for entities fail if there is a constraint on the string length

### ISSUE THREAD

**Issue by bourdux** [jhipster/generator-jhipster#1843]
## Summary

When generating test classes for an entity, and if a string field is specified to have a specified length, the generated tests fail.

jhipster-version : 2.19.0

## Reproduction

Generate an entity with a String field with a length constraint:

Entity field:

```json
{
    "relationships": [],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "code",
            "fieldType": "String",
            "fieldIsEnum": false,
            "fieldNameCapitalized": "Code",
            "fieldNameUnderscored": "code",
            "fieldInJavaBeanMethod": "Code",
            "fieldValidate": true,
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "2"
        },
        {
            "fieldId": 2,
            "fieldName": "name",
            "fieldType": "String",
            "fieldIsEnum": false,
            "fieldNameCapitalized": "Name",
            "fieldNameUnderscored": "name",
            "fieldInJavaBeanMethod": "Name",
            "fieldValidate": false
        }
    ],
    "fieldsContainOwnerManyToMany": false,
    "fieldsContainOwnerOneToOne": false,
    "fieldsContainOneToMany": false,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": false,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": false,
    "fieldsContainDate": false,
    "changelogDate": "20150808141007",
    "dto": "no",
    "pagination": "infinite-scroll",
    "validation": true
}
```

Test failure:

```java
javax.validation.ConstraintViolationException: Validation failed for classes [com.plplus.invoice.domain.Country] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='size must be between 0 and 2', propertyPath=code, rootBeanClass=class com.plplus.invoice.domain.Country, messageTemplate='{javax.validation.constraints.Size.message}'}
]
...
```

## Error source

The source of the error lies in the generated default fields.

```java
    private static final String DEFAULT_CODE = "SAMPLE_TEXT";
    private static final String UPDATED_CODE = "UPDATED_TEXT";
```
Since `SAMPLE_TEXT` and `UPDATED_TEXT` have a length greater than 2, the following tests fail:

CountryResourceTest#createCountry
CountryResourceTest#getAllCountrys
CountryResourceTest#updateCountry
CountryResourceTest#deleteCountry
CountryResourceTest#getCountry

## Proposed fix

Generate a smaller text or take the length constraints into account when generating the test classes.

**Comment by jdubois** [comment]
Yes I know about it, I even think it's documented in the sub-generator.
The problem is that it's really hard to implement correctly. The biggest issue is of course for the regex pattern!!!!
So unless someone has a great new idea here, this unfortunately can't be solved.

**Comment by atomfrede** [comment]
>JHipster generates unit tests that work for generic entities, without knowing your validation rules: it is possible that the generated tests do not pass the validation rules. In that case, you will need to update the sample values used in your unit tests, so that they pass the validation rules.

**Comment by bourdux** [comment]
@jdubois Well, I agree. I think it is not really worth the effort to integrate a string generator from regexp to do this :) Even if such librairies do exist :

- https://code.google.com/p/xeger/
- https://github.com/mifmif/Generex

@atomfrede Alright, thanks, I found it in the validation section of the entity documentation.

At least, users will surely see this issue now when they are faced with the same problem ;)

**Comment by andidev** [comment]
We could generate a random string of the correct length so it works for all cases except regexp. Is this better than nothing? This would fix at least this issue.

I've done this for the blob field. I could take a quick look at it.

**Comment by bourdux** [comment]
@andidev if you take this approach, it might also be a good idea to generate a comment in the test class stating that `DEFAULT_FIELD` and `UPDATED_FIELD` were randomly generated due to the length constraint.

**Comment by andidev** [comment]
Yes you are right. Is this clear enough?

```java
    private static final String DEFAULT_CODE = TestUtil.createRandomString(<%= minlength %>); // minlength string
    private static final String UPDATED_CODE = TestUtil.createRandomString(<%= maxlength %>); // maxlength string
```

and for strings with regexp validation maybe we should add a TODO comment like this
```java
    // TODO: Update test data to match regexp
    private static final String DEFAULT_CODE = TestUtil.createRandomString(<%= minlength %>); // minlength string
    // TODO: Update test data to match regexp
    private static final String UPDATED_CODE = TestUtil.createRandomString(<%= maxlength %>); // maxlength string
```

**Comment by bourdux** [comment]
@andidev seems cleer enough to me. However I would use two more constants such as `MIN_LENGTH_FIELD` and `MAX_LENGTH_FIELD` so the test becomes clearer.

Maybe we could then add validation test as well to improve the code coverage.

Something like that could work I guess:

```java
    @Test<% if (databaseType == 'sql') { %>
    @Transactional<% } %>
    public void check<%= fields[fieldId].fieldInJavaBeanMethod %>ShouldNotExceedMaxLength() throws Exception {
        int databaseSizeBeforeTest = <%= entityInstance %>Repository.findAll().size();
        // set the field to max length + 1
        <%= entityInstance %>.set<%= fields[fieldId].fieldInJavaBeanMethod %>(<%='MAX_LENGTH_' + fields[fieldId].fieldNameUnderscored.toUpperCase()%> + "a");

        // Create the <%= entityClass %>, which fails.<% if (dto == 'mapstruct') { %>
        <%= entityClass %>DTO <%= entityInstance %>DTO = <%= entityInstance %>Mapper.<%= entityInstance %>To<%= entityClass %>DTO(<%= entityInstance %>);<% } %>

        rest<%= entityClass %>MockMvc.perform(post("/api/<%= entityInstance %>s")
                .contentType(TestUtil.APPLICATION_JSON_UTF8)
                .content(TestUtil.convertObjectToJsonBytes(<%= entityInstance %><% if (dto == 'mapstruct') { %>DTO<% } %>)))
                .andExpect(status().isBadRequest());

        List<<%= entityClass %>> <%= entityInstance %>s = <%= entityInstance %>Repository.findAll();
        assertThat(<%= entityInstance %>s).hasSize(databaseSizeBeforeTest);
    }
```

which would generate something like that in my example:

```java
    @Test
    @Transactional
    public void checkCodeShouldNotExceedMaxLength() throws Exception{
        // Validate the database is empty
        assertThat(countryRepository.findAll()).hasSize(0);
        // Set the field to max length + 1
        country.setCode(UPDATED_CODE + "a");

        // Create the Country, which fails.
        restCountryMockMvc.perform(post("/api/countrys")
            .contentType(TestUtil.APPLICATION_JSON_UTF8)
            .content(TestUtil.convertObjectToJsonBytes(country)))
            .andExpect(status().isBadRequest());

        // Validate the database is still empty
        List<Country> countrys = countryRepository.findAll();
        assertThat(countrys).hasSize(0);
    }
```
Then we can do the same thing for min length.

**Comment by andidev** [comment]
That would be best solution. The problem is the lack of time.

I have done the mentioned simple solution for field type blob and hence it would be a matter of a simple copy and paste to do if for filed type string. I have other stuff that I need to prioritize right now.

PR's are welcome though :wink:

**Comment by bourdux** [comment]
@andidev well, I guess I could make a PR. Just let me finish my first project based on JHipster :) Then perhaps I can take the time to install the generator development environment. Yes, I did read CONTRIBUTING.md :P

**Comment by andidev** [comment]
Should we maybe label this as enchasement instead of bug?

**Comment by eater2** [comment]
Hi,
I tested the new version of this fix on our project. But the code enters the undefined IF, assigning still 5 characters.
I propose to add a small workound as below , or to apply a new fix.

             if (sampleTextMinLength == undefined) {
                sampleTextMinLength = 1;
            }

**Comment by jdubois** [comment]
Can you open up a new ticket and send a PR?

**Comment by cm325** [comment]
This might be too crude for you, but I honestly would be fine with the generator asking for valid sample text if the user has selected added validation constraints. Then when your tests get regenerated, everything would still work, rather than having to back out changes in git-

**Comment by jdubois** [comment]
Yes that's a good idea, I like it!!
