### ISSUE TITLE
Entity Auditing: Whether fixing the existing module or integrating it in jhipster itself...

### ISSUE THREAD

**Issue by OmarHawk** [jhipster/generator-jhipster#18471]
##### **Overview of the feature request**

Hi,

I just wanted to integrate some auditing capabilities to my Entities and found this one by @deepu105 :
https://github.com/hipster-labs/generator-jhipster-entity-audit

As already reported in various tickets (#15300, #16642, https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/171), this one does not work together with any of the latest JHipster versions. So now, I do wonder, whether we should follow / contribute one of the following approaches:
- Fix the existing module and get it working with the latest JHipster version by preparing a Pull Request there and getting it merged by you guys (will hopefully be the easiest, though this may not get it working for the reactive stack, as it has not been part of the module so far and I meanwhile switched away from the reactive stack)
- Contribute a feature to enable this via JDL directly within JHipster
- Just implement this as local customization for my own application by manually extending AbstractAuditingEntity and adjusting the initial liquibase changeset 
- any other ideas?

Sorry for asking in this repo, but I though here would be the greatest audience for that. ;-) 

##### **Motivation for or Use Case**
Sometimes, you really do need to see who changed data when and how....

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Yes, its better as a blueprint

Thanks & Regards,
Deepu

**Comment by mraible** [comment]
I can add a bug bounty to help facilitate the development of this feature. Please let me know how much you think it deserves.

**Comment by Meriem-22** [comment]
hello i'm having an issue in using jhipster-entity-audit generator . I installed the generator-jhipster-entity-audit by using this command
"npm install -g generator-jhipster-entity-audit"
and then I installed "yo" by using this command "npm install -g yo" .
but this command "yo jhipster-entity-audit" generates this error : use of deprecated folder mapping "./generators/" in the "exports" field module resolution of the package at c:\users\mm\onedrive\bureau\awtarapp\node_modules\generator-jhipster\package.json. update this package.json to use a subpath pattern like "./generators/*". Can someone help me plzz or what's the correct steps to integrate this module ?

**Comment by mraible** [comment]
I added a bug bounty to convert this module into a blueprint.

**Comment by atomfrede** [comment]
Should we focus in e.g. [javers version ](https://javers.org/documentation/spring-boot-integration/) or maybe even create a javers blueprint and start from scratch?

**Comment by mshima** [comment]
There is javers support, I will start migration.

**Comment by atomfrede** [comment]
Yes, I think both implementation could do the same (I did the javers part back in the days). Just thinking to remove the custom part and rely on what javers does.

**Comment by mshima** [comment]
The custom implementation can support others databases and reactive.
I don't think javers has reactive support.

An interesting follow up is to let jhipster generate the `EntityAuditEvent`, repository and rest endpoint.
So it would be generated using the implementation (reactive/imperative/database) standard and allow to use others features like pagination and criteria. And add a basic react/vue support.

PR is ready https://github.com/hipster-labs/generator-jhipster-entity-audit/pull/177.
