### ISSUE TITLE
EhCache is not getting disabled fully on fast boot

### ISSUE THREAD

**Issue by gvsrini** [jhipster/generator-jhipster#1848]
In CacheConfiguration.java file we have this code:
```
@Profile("!" + Constants.SPRING_PROFILE_FAST)
public class CacheConfiguration {
```

But it appears the cache is still being created when running FAST profile.

More info here:
http://stackoverflow.com/questions/31756501/what-is-the-best-way-to-disable-ehcache-in-jhipster

**Comment by deepu105** [comment]
yup i noticed this too yesterday, not only ehcache same for hazelcast as well

**Comment by gmarziou** [comment]
I may not be able to work on it this week. 

[spring boot 1.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3.0-M1-Release-Notes#caching-auto-configuration)  has some enhancements about caching that could require us to rework this part. More generally it seems 1.3 is going to require some JHipster work.

**Comment by deepu105** [comment]
Ya thats correct,  may be we should mark this item as willdolater

**Comment by gmarziou** [comment]
@gvsrini would you consider submitting a PR?

**Comment by jdubois** [comment]
OK, this must be automatically configured by Spring Boot.

Anyway:
- The trick here is mostly to remove the metrics -> they are disabled in "fast" boot, and the goal of this class is to add those metrics on top of the cache. So this class still does its job.
- Given how we move on at the moment, I think that the "fast" profile will soon disappear, as the "dev" profile has nearly the same speed

So I agree this is a bit misleading, but it works OK for the moment and this will whole configuration will probably disappear when we move to Spring Boot 1.3, so I'm closing this.
