### ISSUE TITLE
Control-center keycloak error

### ISSUE THREAD

**Issue by kypdkz** [jhipster/generator-jhipster#18486]
I created new project with latest jhipster 7.8.1. I added 127.0.0.1 keycloak to /etc/hosts file. I started the container with keycloak.yml from docker. registry worked but somehow control-center did not start. what should I do. can you please help me

docker log: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryReactiveClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalArgumentException: Unable to resolve Configuration with the provided Issuer of "http://keycloak:9080/auth/realms/jhipster"

at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)

.yo-rc.json file : 

{
  "generator-jhipster": {
    "applicationType": "microservice",
    "authenticationType": "oauth2",
    "baseName": "yyy",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "redis",
    "creationTimestamp": 1651016793853,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "jwtSecretKey": "keykeykey",
    "languages": ["en", "tr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "xxx",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": "elasticsearch",
    "serverPort": "8081",
    "serverSideOptions": ["searchEngine:elasticsearch"],
    "serviceDiscoveryType": "eureka",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": true,
    "skipFakeData": false,
    "skipUserManagement": true,
    "testFrameworks": ["cypress", "gatling", "cucumber"],
    "websocket": false,
    "withAdminUi": false
  }
}

**Comment by joe-bookwood** [comment]
This issue is also in jhipster 7.9.0. I generated the app with the monolith jdl sample file from the jdl editor, and changed authenticationType to oauth2.
