### ISSUE TITLE
expectedGET missing for language.json

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1850]
After upgrading my app from JHipster 2.16.0 to 2.19.0, I found that `password.directive.spec.js` and `auth.services.spec.js` both needed the following added to their `beforeEach`:

````
var languageJson = new RegExp('i18n\/.*\/language.json');
$httpBackend.whenGET(languageJson).respond({});
````

Not sure it this was an oversight or something unique to my project.

**Comment by atomfrede** [comment]
Looks like a bug.

**Comment by andidev** [comment]
Not sure that this is a bug, language.json where removed in version 2.17.0, see [this commit](https://github.com/jhipster/generator-jhipster/commit/f51ea1c325fcdb86dcd44874170ca7dad8ef8ec2)

**Comment by andidev** [comment]
Are you sure that you upgraded correctly?

You probably missed that this line was removed from `app.js`
-                    $translatePartialLoader.addPart('language');

Closing this since it seems to be invalid.

**Comment by atomfrede** [comment]
You're right I was looking for the language json in my fork without luck.

**Comment by mraible** [comment]
Thanks @andidev - I removed the reference from app.js, deleted the language.json files in my project and was able to remove the expectation in my tests. I appreciate the quick turnaround on this.
