### ISSUE TITLE
Update spring-boot version to 2.7.0

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#18510]
##### **Overview of the feature request**

Spring-boot version 2.7.0 is expected on May 19th: https://github.com/spring-projects/spring-boot/milestone/239

Changes required: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes

##### **Motivation for or Use Case**

Keep framework up-to-date

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Adding bug bounty because staying up to date with Spring Boot releases is important.

**Comment by tonylook** [comment]
ETA for this release?

**Comment by DanielFran** [comment]
@pascalgrimaud Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/83126

**Comment by DanielFran** [comment]
@mshima Do not forget to claim also same amount, lot of work and well diserve

**Comment by pascalgrimaud** [comment]
@DanielFran : approved

**Comment by DanielFran** [comment]
@mshima: approved
