### ISSUE TITLE
Cypress prompts you to Continue Download or Quit every so often

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#18536]
##### **Overview of the issue**

When running Cypress tests with `npm run e2e`, every so often, I'm prompted to continue downloading or Quit. If I click Quit, the tests continue and pass as expected. 

##### **Motivation for or Use Case**

This seems to create a `cypress/downloads/downloads.html` that is huge! 43MB

##### **Reproduce the error**

Create an app with Cypress, run `npm run e2e` a few times.

##### **Suggest a Fix**

At the very least, we should ignore `cypress/downloads/downloads.html` (or maybe just `cypress/`) in the generated `.gitignore` when Cypress is chosen.

##### **JHipster Version(s)**

`main` branch as of May 1, 2022.

##### **JHipster Version(s)**

```
twenty-one-points@0.0.1-SNAPSHOT /Users/mraible/dev/21-points
└── generator-jhipster@7.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "TwentyOnePoints",
    "blueprints": [],
    "buildTool": "gradle",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1651460089159,
    "cypressCoverage": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "org.jhipster.health",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": "elasticsearch",
    "serverPort": "8080",
    "serverSideOptions": ["searchEngine:elasticsearch"],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": ["cypress"],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

git version 2.32.0 (Apple Git-132)

node: v16.15.0

npm: 8.6.0

Docker version 20.10.13, build a224086

docker-compose version 1.29.2, build 5becea4c

**Comment by mraible** [comment]
It happens while tests are running, usually at the end of a test.

**Comment by mshima** [comment]
It’s related to downloading contents inside tests.
I will try to reproduce.

**Comment by mshima** [comment]
@mraible in what application have you been hit by this problem?
Plain 21-points?

**Comment by mraible** [comment]
I've seen it in many apps this last couple of weeks. It doesn't seem to matter if it's a monolith or microservices. The web framework doesn't seem to matter either since I've seen it with Vue, Ionic, and even [Svelte](https://github.com/jhipster/generator-jhipster-svelte/pull/1121#issuecomment-1110142989).

**Comment by mraible** [comment]
@mshima it's 43MB of gibberish as far as I can tell.

<img width="1523" alt="Screen Shot 2022-05-09 at 13 43 19" src="https://user-images.githubusercontent.com/17892/167485536-37f71e30-cc80-41d5-9aca-acbf6c54d884.png">

**Comment by mshima** [comment]
@mraible I've tried to reproduce, but I couldn't.
I think this happens when using auth0/okta.
Can you confirm if that's the case?
The file `model-info.pbm` is identifiable at the image. I don't think it's open source.

**Comment by mraible** [comment]
We can close this issue and I can re-open it when I have more details. I think the most important thing for now is to ignore this directory so there's not git changes after running `npm run e2e`.

**Comment by DanielFran** [comment]
@mshima approved
