### ISSUE TITLE
elasticsearch data dir created when running "mvn clean install"

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1853]
create a default config with `"searchEngine": "elasticsearch"`

run `mvn clean install` (or actually mvn test)

this creates an elasticsearch `data` dir in the root which is not ignored by git.

- Either we add the `data` dir `.gitignore` (as in #1713)
- Or we configure the location of the data dir to `target/elasticsearch/data` in the **test** resources `_application.yml` file (as in #1738)

@jdubois 
Could you please review this issue since you closed both of the refereed PR's earlier. I think that there may have been some kind of misunderstanding here.

**Comment by jdubois** [comment]
Yes the directory has changed, can you check? It should be correct.

**Comment by andidev** [comment]
I can confirm that when running `mvn spring-boot:run` the data dir is created in the `target/elasticsearch` path since it is confugured in [application-dev.yml](https://github.com/jhipster/jhipster-sample-app-elasticsearch/blob/master/src/main/resources/config/application-dev.yml#L38-L39)

However when running `mvn clean install` the test will use the configuration in the test resources folder and the `application-dev.yml` [file is missing there](https://github.com/jhipster/jhipster-sample-app-elasticsearch/tree/master/src/test/resources/config) and therefore the data dir is saved in the project root.

**Comment by atomfrede** [comment]
I would say we should add it to ``application.yml`` in **test** resources.

**Comment by jdubois** [comment]
Yes there is a misunderstanding here -> I agree with @atomfrede it should be added to the application.yml in the test resources

**Comment by andidev** [comment]
I'm merging it then!

**Comment by jdubois** [comment]
Yes!

**Comment by bonhamcm** [comment]
Thank you!
