### ISSUE TITLE
serviceDiscoveryType seems not be prepared correctly for templates

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#18533]
##### **Overview of the issue**

While looking into #18531 I wondered why the spring profiles are not replaced in the build artifacts. I looks like `serviceDiscoveryType` is supposed to be mapped to true/false, but it is still `no` when the template is evaluated.

In particular this means the build jar file has no active profiles set by default, because this replacement never happens.

```
<%_ if (!serviceDiscoveryType) { _%>
        filter {
            it.replace("#spring.profiles.active#", profiles)
        }
<%_ } _%>
```

##### **Motivation for or Use Case**

Build jar file should have e.g. production profile baked in. Sidenote, maybe I am wrong, but at least thats how I remember it and it still fits our documentation. I didn't check for maven.

##### **Reproduce the error**

Use the defaults except build tool gradle.

##### **Related issues**

#18531 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I'm not sure if this is related, but we discovered a discovery issue last week. Basically, if you deployed my example from [this post](https://developer.okta.com/blog/2021/06/01/kubernetes-spring-boot-jhipster) to Azure, Eureka wouldn't recognize the "store" app as being started. We tracked it down to [this issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/3941) and then discovered a fix:

```
eureka.instance.initial-status=starting
```

Adding this to the "store" app solved the problem. https://github.com/oktadev/okta-azure-kubernetes-cosmosdb-example/commit/9b41c2d083a5c73662172843bad22c292543d6b3

**Comment by atomfrede** [comment]
Seems unrelated if the other eureka properties have been generated correctly

**Comment by mraible** [comment]
OK. Here's the workaround we implemented to fix it: https://github.com/oktadev/okta-blog/commit/d38e52888e3e4b9bef2edc043a5e28af14635184

**Comment by atomfrede** [comment]
@mraible Should we implement the workaround with the custom healthindicator or wait for the upstream fix? Regardless of the problem with the original issue here, that the profile is not replaced correctly.

**Comment by mraible** [comment]
@atomfrede I think we should implement the workaround and open a new issue linked to the upstream fix. That way, we can remove it and do a new release when it's fixed.
