### ISSUE TITLE
Filter cannot find symbol: variable filter

### ISSUE THREAD

**Issue by alfredorueda** [jhipster/generator-jhipster#1854]
We used JHipster to generate a project like the example in the documentation (Human Resources Oracle Example) 

![uml](https://cloud.githubusercontent.com/assets/8808034/9207998/3f5e4c96-4071-11e5-890c-10dab460bf24.png)

When we added the entities incrementally, so JHipster UML generator asked us Ynaxdh and we overwritten all our files. After that, errors appeared in our project (the project with error is uploaded in https://github.com/alfredorueda/HR/tree/Filter_Error):

https://github.com/alfredorueda/HR/blob/Filter_Error/modelio/hr.xmi

The project is working in this previous step: https://github.com/alfredorueda/HR/tree/master

Below is attached our logs and piece of code where the error is located,

JHipster is amazing!!!
Thank you very much for your support.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project hr: Compilation failure: Compilation failure:
[ERROR] /C:/Users/alfredo/Developer/JHipster/HR/src/main/java/com/hr/web/rest/LocationResource.java:[77,41] cannot find symbol
[ERROR] symbol:   variable filter

		/**
		 * GET  /countrys -> get all the countrys.
		 */
		@RequestMapping(value = "/countrys",
				method = RequestMethod.GET,
				produces = MediaType.APPLICATION_JSON_VALUE)
		@Timed
		public List<Country> getAll() {
			if ("location-is-null".equals(filter)) {
				log.debug("REST request to get all Countrys where location is null");
				return StreamSupport
					.stream(countryRepository.findAll().spliterator(), false)
					.filter(country -> country.getLocation() == null)
					.collect(Collectors.toList());
			}

			log.debug("REST request to get all Countrys");
			return countryRepository.findAll();
		}

**Comment by andidev** [comment]
This is a bug that will be fixed next release. It occurs when you have an Entity with two one to one relationships where one is owner and the another one is not.

You can fix this by modifying
```java
    public List<Country> getAll() {
```

to
```java
    public List<Country> getAll(@RequestParam(required = false) String filter){
```
