### ISSUE TITLE
language subgenerator not working

### ISSUE THREAD

**Issue by thiagogcm** [jhipster/generator-jhipster#1855]
I tried to install a language with  yo jhipster:languages  without success. Anybody else with this problem ? 
using latest version

**Comment by seghers** [comment]
Work on a new default project.

**Comment by deepu105** [comment]
@thiagogcm you have to give more info then that man. what is the configuration you use, do you see any new language added in the i18n folder, was there any error etc.

Its working for me.
So reopen with those details please. else provide steps to reproduce

**Comment by andreneutzling** [comment]
I'm facing an issue with the generator as well. Details:

**Overview of the issue** - I'm facing an issue with the language generator. It doesn't allow me to select any supported language (the cursor don't move and the space doesn't respond).
**Motivation for or Use Case** - I cannot install any other default language.
**JHipster Version(s)** - 2.23.0
**Entity configuration(s)** - no entities created so far, however, I created some entities in another project and there the select menu works (ie.: selecting the validation).
**Operating System** - I'm running on Win 10, not sure if it is a OS specific issue. I've tried with Win default cmd, powershell and git bash, as User and as Admin.
**Reproduce the error** - 
1) Run Powershell as admin
2) Run the "yo jhipster:languages" in the project folder
3) Now I cannot move the cursor to select the language. It also doesn't respond to the space to select. I can only press enter, which does nothing.

**Related issues** - This one?!
**Suggest a Fix** - maybe apply the same select logic used in the Entity generator.  
**JHipster configuration** - (sorry it doesn't allow me to attach):
{
  "generator-jhipster": {
    "baseName": "testApp",
    "packageName": "br.org.testApp",
    "packageFolder": "br/org/testApp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "23ebe78ace004e47994e260f20a784a944353596",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ]
  }
}

**Comment by deepu105** [comment]
This could be an issue with the shell you are using, what terminal program
do you use? I had issues while using git bash from windows, i guess
cmd/powershell works good in windows and terminal in mac/unix

**Comment by pascalgrimaud** [comment]
@andreneutzling : did you have a look at https://github.com/jhipster/generator-jhipster/issues/2153 ?

**Comment by andreneutzling** [comment]
Thanks for the feedback guys.

@deepu105, I've tried with Win default cmd, powershell and git bash, as User and as Admin. Non of them worked. 

@pascalgrimaud, I'll try with another version of Node.

**Comment by andreneutzling** [comment]
@pascalgrimaud, I upgraded to node v5.1.0 (latest stable) and it's working fine now. Thanks a lot for your support!
