### ISSUE TITLE
Elasticsearch doesn't work for relationship after insert, the same work after update

### ISSUE THREAD

**Issue by antsch01** [jhipster/generator-jhipster#18555]
##### **Overview of the issue**

The search doesn't work after inserting a new entity, the same search work after updating the entity.
it seems after the updating entity the indexing has been updated.
##### **Motivation for or Use Case**

The client is not able to find the entity after inserting
##### **Reproduce the error**

- Entity A
- Entity B
- Relationship oneToMany A to B

1. Log into backoffice
2. Create the entity B with reference to A with id 100
3. Save is ok
4. Try to search 100, no found result --> search doesn't work
5. Open entity B, update and save
6. Try to search 100 and found 1 result, --> search work

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.seaviaggiare.app",
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "seaviaggiare",
    "packageName": "com.seaviaggiare.app",
    "packageFolder": "com/seaviaggiare/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1633264908943,
    "testFrameworks": ["cucumber"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": ["it", "en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
It looks like you're using JHipster 6.10.5. Can you try re-generating your app with JHipster 7.8.1 and see if this problem still exists?

**Comment by antsch01** [comment]
> It looks like you're using JHipster 6.10.5. Can you try re-generating your app with JHipster 7.8.1 and see if this problem still exists?

Hi @mraible 

thank you for reply, I tried to update jhister and regenerate the project following the guide jhipster.tech/upgrading-an-application/#automatic_upgrade but got an error.
I executed the command: npx jhipster upgrade and got the error Cannot read property 'propertyName' of undefined

![image](https://user-images.githubusercontent.com/101180033/166457560-9748ad82-f8bf-4bf1-987d-194392f95952.png)

Could you help me?

Thanks,
Antonio

**Comment by Tcharl** [comment]
Hi Antonio,

Regarding your upgrade issue, it looks like a misconfiguration of your jdl or your entities `./jhipster/*.json` (missing the name of your opposite relationship?).
Can you please try to update or post them so that I would be able to help?

Thanks!
