### ISSUE TITLE
State change error when navigating to an entity page, when using enumerations and translation

### ISSUE THREAD

**Issue by tonyob** [jhipster/generator-jhipster#1856]
Commit 387e0311da2bd7881b7db43b54a0d08d524eb802 introduced an issue when using translation and enumerations on generated entity pages.

Lines 24 & 48 of entity/templates/src/main/webapp/app/_entity.js are referencing an attribute which does not exist on the field object.

I'm presuming we should be adding the enumInstance attribute from line 980 of entity/index.js to the field object so it can be accessed in the entity template later.

The result of this is that we get a state change error since the $translatePartialLoader.addPart() function throws an exception when a blank string is passed in. This causes any entitys' (with an enumeration) list view/detail pages to be inaccessible when generated under the latest release.

**Comment by andidev** [comment]
You presume right and it is already done in #1849. It will be fixed in next release.
