### ISSUE TITLE
Generate a required (non-nullable) value inside an Entity relationship

### ISSUE THREAD

**Issue by salvatorenovelli** [jhipster/generator-jhipster#1859]
Hello I'm generating some Entity with the jhipster generator.

When I generate an entity relationship, I'd like to make the value in that field mandatory but unfortunately, the generator doesn't provide that option.

Is it possible to implement this functionality?

Regards

**Comment by deepu105** [comment]
you mean to have a relationship to be a required item?

**Comment by marcelinobadin** [comment]
Would be very nice to have it. I always need to rewrite my Domains to include @NotNull on mandatory relationships.

**Comment by jdubois** [comment]
This is something I have never used myself, you mean to put an @NotNull on a relationship?

This would be against our Policy 2 at http://jhipster.github.io/policies.html as we wouldn't add much value: basically we replace one annotation by one question... It's easier for people to use the annotation directly.

**Comment by lukasbradley** [comment]
@jdubois I feel this should be revisited.  It's not as straightforward as adding a few @NotNull annotations.

First, since the schema is generated, all of those columns should also be NOT NULL in the database.  It doesn't appear as if those NotNull annotations are being picked up by Liquibase.  Therefore, programmers must go back and alter the database constraints by hand.

Second, the generated UI adds notes by required fields automatically, which is nice.  Without the ability to automatically declare the relationship as required, all those user interface changes need to also be modified.

In my experience, the vast majority of database relationships are required (declared NOT NULL), and I think this should follow the same functionality as required fields.

Thanks.

**Comment by jdubois** [comment]
You are correct.
Could you create a new ticket for that, with your explanation? Normally we don't discuss on old tickets, because things change so much in JHipster.

**Comment by lukasbradley** [comment]
@jdubois Absolutely.  I appreciate your open mindedness.  Will get one in this afternoon.

**Comment by WhyINeedToFillUsername** [comment]
Is there any update to this? :)

**Comment by deepu105** [comment]
This is already implemented and released

**Comment by WhyINeedToFillUsername** [comment]
Ok, so how do I declare that a relationship field is required, please? I cannot find it in the documentation.

**Comment by deepu105** [comment]
When you add a new entity there will be aquestion to enable validations.
Its not available in JDL yet only in entity sub generator

**Comment by WhyINeedToFillUsername** [comment]
Well I tried to create an entity via sub generator before asking and it did not ask me for any validations on a relationship:

```
C:\dev\projects\app>yo jhipster:entity test

The entity test is being created.

Generating field #1

? Do you want to add a field to your entity? No

Generating relationships to other entities

? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? nvm
? What is the name of the relationship? nvm
? What is the type of the relationship? many-to-one
? When you display this relationship with AngularJS, which field from 'nvm' do you want to use? id

================= Test =================
Relationships
nvm (Nvm) many-to-one


Generating relationships to other entities

? Do you want to add a relationship to another entity? No

================= Test =================
Relationships
nvm (Nvm) many-to-one

? Do you want to use a Data Transfer Object (DTO)? No, use the entity directly
? Do you want to use separate service class for your business logic? No, the REST controller should use the repository directly
? Do you want pagination on your entity? No

Everything is configured, generating the entity...
```
`("jhipsterVersion": "3.1.0")`

**Comment by lluiscanals** [comment]
I think it was added at least in 3.2.x, so try to update first.
