### ISSUE TITLE
Add Database Reverse Engineering - Postgresql

### ISSUE THREAD

**Issue by DavidMCook** [jhipster/generator-jhipster#186]
I am loving what you all have done with JHipster so far! But, I am still working with Roo for my original domain/rest generation, simply because they have it running nearly perfectly. For those of us in the community that are data-driven-developers, could you investigate adding this feature?

**Comment by cm325** [comment]
:+1:  for dbre like spring roo. I have really enjoyed working with spring roo, it would be wonderful to see it getting more support perhaps in conjunction with jhipster-

**Comment by hm0** [comment]
I'd like to know if this killer feature is in your pipeline guys in the short term..Hopefully yes...

**Comment by atomfrede** [comment]
@hm0 Sadly I'm not aware of any efforts for this feature

**Comment by mraible** [comment]
If we could generate entities from database tables, would that be enough to make this work? AppFuse supports this with a Maven plugin.

**Comment by deepu105** [comment]
This was something i asked @jdubois when i was new to Jhipster, but then he
pointed out and i understand that its very complex to do, but then there
was jhipster uml, so i guess if we put our brains to it it might be
possible and would be a very interesting side project like jhipster uml

**Comment by dancancro** [comment]
Hi. I'm just curious. Is this the same feature as [this one](https://docs.strongloop.com/display/public/LB/Discovering+models+from+relational+databases#Discoveringmodelsfromrelationaldatabases-Overview) in Strongloop?

If so, maybe there's some knowledge exchange that could happen here.

**Comment by deepu105** [comment]
That looks cool man @jdubois what do you think of loopback link above?do
you think its worth to explore as a side project or as a JH uml extension?

**Comment by jdubois** [comment]
Database reverse engineering is a very difficult tasks, besides we enforce in JHipster some database schemas, and so we couldn't reverse-engineer everything.
This would definitely be another project, and that's a lot of work.
