### ISSUE TITLE
Why is the support for Atmosphere removed from jhipster?

### ISSUE THREAD

**Issue by alchemistgo87** [jhipster/generator-jhipster#1861]
I want to implement atmosphere for websocket and fallback mechanisms. But in the latest version of jhipster the support of Atmosphere has been removed. There is only support for spring websockets now. What steps should I take to move from spring websockets back to atmosphere?

**Comment by jdubois** [comment]
Please don't cross-post:
http://stackoverflow.com/questions/31965368/why-is-the-support-for-atmosphere-removed-from-jhipster

Why is it removed? Because I don't have the time to do everything...

**Comment by alchemistgo87** [comment]
All right. By the way, whatever work you and your team have done is really commendable. Its really helpful and I wish you all the very best !!

**Comment by jdubois** [comment]
I'd love to have Atmosphere back, but I already spent several days on it and I didn't succeed. If you find out a solution, don't hesitate to share!

**Comment by alchemistgo87** [comment]
I will, for sure (Y)
