### ISSUE TITLE
Gulp serve is failing on Windows 7

### ISSUE THREAD

**Issue by tuncayxx** [jhipster/generator-jhipster#1862]
I have all tools installed om Windows but when typing Gulp serve it fails saying compass.bat couldn't be found even I installed compass via nodejs ?

**Comment by gmarziou** [comment]
How did you install compass via  nodejs?

As far as I know nodejs does provide only grunt or gulp plugins for compass.
What do you get when you run `compass -v`?

That said if you don't need compass and only sass compilation you can use node-sass as explained in issue #1527. Eventually, it will be merged in jhipster.

**Comment by tuncayxx** [comment]
it is actually "grunt serve" that is NOT working.

I installed grunt as described on JHIpster setup page like: npm install -g grunt-cli

I get this error:

C:\code\jhipster-demo>grunt serve
Running "clean:server" (clean) task
>> 0 paths cleaned.
Running "wiredep:app" (wiredep) task
Running "wiredep:test" (wiredep) task
Running "ngconstant:dev" (ngconstant) task
Creating module demoApp at src/main/webapp/scripts/app/app.constants.js...OK
Running "compass:server" (compass) task
Warning: Command failed: C:\Windows\system32\cmd.exe /s /c "compass.bat --version"
'compass.bat' blev ikke genkendt som en intern eller ekstern kommando,
et program eller en batchfil.
 Use --force to continue.

Aborted due to warnings.

**Comment by gmarziou** [comment]
Warning: Command failed: C:\Windows\system32\cmd.exe /s /c "compass.bat --version"
   'compass.bat' blev ikke genkendt som en intern eller ekstern kommando,

No it 's not grunt the problem, as I told you JHipster's build uses compass command for grunt or gulp.
Read my first answer with questions I asked and recommendations, it's still valid.

**Comment by tuncayxx** [comment]
Why is there difference between Mac and Windows when it just works when you type grunt serve in Mac but the command not working in the Windows ? I didn't run compass - v yet .

**Comment by gmarziou** [comment]
Because Windows sucks for NodeJS, I know it from first hand experience as I work on both Windows and Ubuntu.

**Comment by deepu105** [comment]
Have u installed ruby for windows?  In mac it comes preinstalled, in
windows you have to install it and then the compass gem, hope you did that
as its clearly mentioned in the docs,  sorry i didn't go through this
thread fully so if i missed something sorry.

Anyways we are moving to node sass which is faster and cleaner so i
wouldn't be worried about compass anymore

**Comment by tuncayxx** [comment]
What should I exactly do in order to make the 'grunt serve' to work on Windows 7 as on Mac?

The documentation on jhipster https://jhipster.github.io/installation.html does not saying anything about Ruby, gem and node-sass ?

**Comment by tuncayxx** [comment]
Thank you, guys, 

I installed Ruby and installed compass via Ruby and it is working now :)

**Comment by gmarziou** [comment]
Ironically, next release will use node-sass and so remove the requirements on Ruby and Compass.

**Comment by tuncayxx** [comment]
Nice :)

-tuncay
