### ISSUE TITLE
Date picker is not working on safari browser 8.0.6

### ISSUE THREAD

**Issue by thaihau** [jhipster/generator-jhipster#1864]
# Summary
Date picker is not working on safari browser. But working on chrome.
jhipster-version : 2.19.0

# Environment
Browsers and Operating System
Safari: Version 8.0.6 (10600.6.3),  OS: Yosemite 10.10.3

Left handed is chrome, right hand side is safari.
![screen shot 2015-08-14 at 5 47 42 pm](https://cloud.githubusercontent.com/assets/851803/9271480/c08aa0de-42ac-11e5-9c17-450e89ffe632.png)

**Comment by gmarziou** [comment]
In fact there is no datepicker code, we set the input type to "date" and the browser decides how to render it, currently only Chrome and mobile browsers support it.
