### ISSUE TITLE
Cleanup generator-base API.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#18652]
##### **Overview of the issue**

Generator base has too many methods.
It should provide only the base methods, technology specific methods like needles and processHtml/Tsx should be removed.

- Implement a new needle base support.
- Migrate needles to this implementation.
- Implement transforms at writeFiles to replace processHtml/processJsx methods.

##### **Motivation for or Use Case**

Improve maintainability.

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
For processing and technology specific methods, I encourage to move to a more object oriented approach with packages and classes located in `/utils/tech/jhipster/generator/<client|server|dcvs|...>/<entity|class>`.

**Comment by DanielFran** [comment]
@mshima Anything missing to close this issue?

**Comment by mshima** [comment]
We still have the todo generator.
https://github.com/jhipster/generator-jhipster/blob/main/generators/base/generator-base-todo.mts

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/187981

**Comment by DanielFran** [comment]
@mshima approved
