### ISSUE TITLE
Issue in generating Spring controller. Newly generated controller goes to undefined/web/rest folder instead generating in existing package.

### ISSUE THREAD

**Issue by ArihantKumarJain1** [jhipster/generator-jhipster#18656]
Rest controller generation issue
Welcome to JHipster v7.8.1

The spring-controller Foo is being created.
? Do you want to add an action to your controller? Yes
? What is the name of your action? getData
? What is the HTTP method of your action? GET
? Do you want to add an action to your controller? Yes
? What is the name of your action? insertData
? What is the HTTP method of your action? POST
? Do you want to add an action to your controller? Yes
? What is the name of your action? updateData
? What is the HTTP method of your action? PUT
? Do you want to add an action to your controller? Yes
? What is the name of your action? deleteData
? What is the HTTP method of your action? DELETE
? Do you want to add an action to your controller? Yes
? What is the name of your action? fetchAllData
? What is the HTTP method of your action? GET
? Do you want to add an action to your controller? No
adding Get action 'getData' for /api/foo/get-data
adding Post action 'insertData' for /api/foo/insert-data
adding Put action 'updateData' for /api/foo/update-data
adding Delete action 'deleteData' for /api/foo/delete-data
adding Get action 'fetchAllData' for /api/foo/fetch-all-data
    force .yo-rc-global.json
    force .yo-rc.json
   create src\main\java\undefined\web\rest\FooResource.java
   create src\test\java\undefined\web\rest\FooResourceIT.java

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

Jhipster Info details.
Welcome to JHipster v7.8.1

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
application-micro@0.0.0 C:\JHipsterTest\ApplicationMicro
`-- generator-jhipster@7.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "authenticationType": "jwt",
    "baseName": "ApplicationMicro",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "hazelcast",
    "creationTimestamp": 1652429665448,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": ["FirstEntity"],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1652532155000,
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.micro",
    "pages": [],
    "prodDatabaseType": "mysql",
    "reactive": false,
    "searchEngine": "elasticsearch",
    "serverPort": "8081",
    "serverSideOptions": ["searchEngine:elasticsearch"],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": true,
    "skipFakeData": false,
    "skipUserManagement": true,
    "testFrameworks": ["cucumber"],
    "websocket": false,
    "withAdminUi": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity FirstEntity
service FirstEntity with serviceImpl
search FirstEntity with true
microservice FirstEntity with ApplicationMicro
filter FirstEntity
clientRootFolder FirstEntity with ApplicationMicro

</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

git version 2.36.0.windows.1

node: v16.15.0

npm: 8.9.0

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

**Comment by Tcharl** [comment]
Not sure `search with true` is legit.
