### ISSUE TITLE
Webpack in infinity building loop after first change in React/Angular frontend app 

### ISSUE THREAD

**Issue by mljolje** [jhipster/generator-jhipster#18703]
##### **Overview of the issue**

Create simple JHipster monolith application (no extra entities) with React or Angular frontend, start-up backend and frontend (npm start) and everything is fine. 
However, after first change of frontend files Webpack enters infinity building loop besides no changes are made.

##### **Motivation for or Use Case**

Cannot further update and develop frontend application since webpack in infinity loop.

##### **Reproduce the error**

After initial startup of frontend application, change any frontend file (like footer.tsx) and webpack enters infinity building loop:

Logs: 
```
Webpack: Starting ...

  √ Compile modules
  √ Build modules
  √ Optimize modules
  √ Emit files

Finished after 3.948 seconds.

49 assets
641 modules
webpack 5.71.0 compiled successfully in 3941 ms
No errors found.
Webpack: Starting ...
Webpack: Starting ...

  √ Compile modules
  √ Build modules
  √ Optimize modules
  √ Emit files

Finished after 0.442 seconds.

47 assets
641 modules
webpack 5.71.0 compiled successfully in 438 ms
No errors found.
<i> [webpack-dev-middleware] wait until bundle finished: /main.08e2107781e734bb3ad8.hot-update.js
Webpack: Starting ...

  √ Compile modules
  √ Build modules
  √ Optimize modules
  √ Emit files

Finished after 0.351 seconds.

47 assets
641 modules
webpack 5.71.0 compiled successfully in 348 ms
No errors found.
Webpack: Starting ...

Webpack: Starting ...

  √ Compile modules
  √ Build modules
  √ Optimize modules
  √ Emit files

Finished after 0.317 seconds.

47 assets
641 modules
webpack 5.71.0 compiled successfully in 316 ms
No errors found.
Webpack: Starting ...

Webpack: Starting ...

  √ Compile modules
  √ Build modules
  √ Optimize modules
  √ Emit files

Finished after 0.351 seconds.

Verbose logs:

2022-05-20 06:29:39: webpack 5.72.1 compiled successfully in 125 ms (6ac2fb2ff8fc981f027d)
No errors found.
<s> [webpack.Progress] 0%

<s> [webpack.Progress] 1% cache end idle
Webpack: Starting ...

2022-05-20 06:29:42: webpack 5.72.1 compiled successfully in 207 ms (6ac2fb2ff8fc981f027d)
No errors found.
<s> [webpack.Progress] 0%

<s> [webpack.Progress] 1% cache end idle
Webpack: Starting ...

2022-05-20 06:29:42: webpack 5.72.1 compiled successfully in 252 ms (6ac2fb2ff8fc981f027d)
No errors found.
<s> [webpack.Progress] 0%

<s> [webpack.Progress] 1% cache end idle
Webpack: Starting ...

```

##### **Related issues**

No related issue.

##### **Suggest a Fix**

No suggested fix.

##### **JHipster Version(s)**

v7.8.1

##### **JHipster configuration**

Welcome to JHipster v7.8.1

Welcome to the JHipster Information Sub-Generator

```
znr@0.0.1-SNAPSHOT C:\Users\eljomar\git\znrbackup
`-- generator-jhipster@7.8.1

```

```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "znr",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1652975378104,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "languages": ["en", "hr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.ericsson.znr",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": "elasticsearch",
    "serverPort": "8080",
    "serverSideOptions": ["searchEngine:elasticsearch", "websocket:spring-websocket"],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": true,
    "testFrameworks": ["cucumber"],
    "websocket": "spring-websocket",
    "withAdminUi": true
  }
}
```

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.27.0.windows.1

node: v14.18.1

npm: 8.6.0

Docker version 20.10.7, build f0df350

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No extra entities are created. Just initial setup.

##### **Browsers and Operating System**

Windows 10 Enterprise
Google Chrome Version 101.0.4951.67

- [ *] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
I'm on node 16, and do not have this issue, may be related?

**Comment by mljolje** [comment]
Same behavior with node 16, constant recompile loop.

**Comment by Tcharl** [comment]
Sorry, but We'll need more information: I'm not able to reproduce on my side (Mac unfortunately).

What I did:
1. Add keycloack in my etc/hosts file: `127.0.0.1	localhost keycloak``
2. Took your .yo-rc file and executed `jhipster --force` on the same folder
3. `npm install`
4. Started elastic and keycloak `docker-compose -d -f src/main/docker/<container.yml`
5. Started the app: `npm run watch`
6. Modified the footer: updates and does not loop.

**Comment by mraible** [comment]
@samir-kamble It's likely because many of us that use JHipster haven't seen it. I'm sorry you're experiencing it. It's very difficult to fix if we can't reproduce it.

**Comment by samir-kamble** [comment]
> @samir-kamble It's likely because many of us that use JHipster haven't seen it. I'm sorry you're experiencing it. It's very difficult to fix if we can't reproduce it.

Hi, Many thanks for quick response. At max I can share screen recording of issue happening. Please let me know if that can help

Particularly, it is happening on changing any file (HTML in my case) in angular application for first time only.

**Comment by samir-kamble** [comment]
I tried on following Node JS versions, But issue remains same. It seems like windows issue only. 

node-v14.21.3-win-x64
node-v16.20.1-win-x64
node-v18.10.0-win-x64
node-v20.4.0-win-x64

**Comment by samir-kamble** [comment]
Finally Tried generating fresh new application with generator, Still same issue.

**Comment by samir-kamble** [comment]
Searched quite a lot over internet but no solution found, This is Showstopper for me for now.

Anyone knows any solution please share.

**Comment by mshima** [comment]
Try disabling webpack cache:
https://github.com/jhipster/generator-jhipster/blob/6f920c24cb4bb293e22407bb293637e700317627/generators/react/templates/webpack/webpack.common.js.ejs#L67

**Comment by samir-kamble** [comment]
Can we do this via Web pack config present in angular app of jhipster frontend?

**Comment by mshima** [comment]
Can be disabled at angular.json file:
https://github.com/jhipster/generator-jhipster/blob/320e5438b38d3f50b105f7a0acf2a51975905e12/generators/angular/templates/angular.json.ejs#L130

**Comment by samir-kamble** [comment]
> Can be disabled at angular.json file:
> 
> https://github.com/jhipster/generator-jhipster/blob/320e5438b38d3f50b105f7a0acf2a51975905e12/generators/angular/templates/angular.json.ejs#L130

Hi,

Many thanks for Solution. 

Tried doing this. it worked for 1st save but after 2nd save same story of endless loop.
