### ISSUE TITLE
Translate React and Vue to native language.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#18743]
##### **Overview of the feature request**

Following https://github.com/jhipster/generator-jhipster/issues/15964 we should translate React and Vue to the native language.

While doing some work related to https://github.com/jhipster/generator-jhipster/issues/18652.
I've noticed that there is already some translation replacement been done, we can improve it and translate React and Vue to native language.

##### **Motivation for or Use Case**

Have generate applications translated to the native language is a nice touch.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
Closed by #18867

**Comment by mshima** [comment]
Vue is not translated yet, I need to check how the translation must be injected.

**Comment by mshima** [comment]
vscode/eslint are really annoying on v-text/v-html content.

<img width="559" alt="Captura de Tela 2023-04-20 às 17 59 41" src="https://user-images.githubusercontent.com/1417183/233495315-d068fa70-972b-4e5a-8c22-ee875bb6af56.png">

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/pull/21960 fixes those errors. But doesn't translates yet.
