### ISSUE TITLE
Table referencing other table not yet created

### ISSUE THREAD

**Issue by Maury1329** [jhipster/generator-jhipster#1874]
I have been trying JHispter for a few weeks now.
I created a data UML diagram in Modelio, exported it to .XMI format and created the structure with jhipster-uml. Then I manually edited my .jhipster\*.json files to include my validations etc.
I regenerated my entities based on my manual changes, using the entity sub-generator.
All well, so far.
When I ran the project with "mvn spring-boot:run", MySQL could not create Table A because it 
references Table B in its .json file and Table B was yet to be created.
This part in the .json file of Table A, indicates that.
````
        <addForeignKeyConstraint baseColumnNames="entityb_id"
                                 baseTableName="ENTITYA"
                                 constraintName="fk_entitya_entityb_id"
                                 referencedColumnNames="id"
                                 referencedTableName="ENTITYB"/>
````
I figured out that the problem is fixed, by adding this (FOREIGN_KEY_CHECKS on and then off) to all my Liquibase xml files, excluding the master that does the creation of the JHI_* entities.
````
<changeSet id="20150815......" author="jhipster">
	<sql>SET FOREIGN_KEY_CHECKS=0;</sql>
	<createTable tableName="ENTITYA">
            		<column ...
			...
        </createTable>
        <addForeignKeyConstraint baseColumnNames="entityb_id"
                                 baseTableName="ENTITYA"
                                 constraintName="fk_entitya_entityb_id"
                                 referencedColumnNames="id"
                                 referencedTableName="ENTITYB"/>
	<sql>SET FOREIGN_KEY_CHECKS=1;</sql>
</changeSet>
````
I automated this by performing these commands (in Cygwin in my case) for each Liquibase .xml file:
````
sed  '/<changeSet id=\"20150815160658\" author=\"jhipster\">/a <sql>SET FOREIGN_KEY_CHECKS=0;<\/sql>' 20150815160658_added_entity_Entity.xml -i.bk1
sed  '/<\/changeSet>/i <sql>SET FOREIGN_KEY_CHECKS=1;<\/sql>' 20150815160658_added_entity_Entity.xml -i.bk2
````
I used -i option to backup the source file. Twice, in this case.
The first command inserts the "sql" tag after the "changeSet" opening tag..
The second command inserts the "sql" tag before the "changeSet" closing tag.

I am assumming that this is just an ommission, becuase maybe JHipster wasn't tested with complex data structures yet.
Otherwise, I hope this helps others.

Regards

**Comment by andidev** [comment]
When you manually edited your .jhipster*.json files did you also add new relationships?

When you mean `complex data structures` could you provide provide an example of the relationships between entities that you are trying to create?

**Comment by Maury1329** [comment]
@andidev , I will send the .json files in a few days (after I finish some other pending work).
Since I exported them as XMI, I only added a few fields and validations, but not the relationships.
In Modelio I did not add field validation (contraints!?!), because I did not know how. Modelio's documentaion is about screen shots and not explanations .
I will rename some things, run again and make sure the error shows up before sending them.
I will also include the exact error message this time.

**Comment by MathieuAA** [comment]
Hi,

At first glance, it looks like an inverted association problem (the dependency is not where it should have been).
If you could do two things, that would be great:
  - create an issue in the JHipster-UML page (JHipster issues may or may not be related, but since you used JHipster-UML...) and close this one;
  - send us your JSON files and the XMI so that I can run some tests to confirm an issue.

**Comment by jdubois** [comment]
Yes, for me this is a jhipster-uml issue... Maybe also we can't generate everything, if there is some kind of cyclic dependencies between entities, but I haven't seen it yet.

-> I'm closing this, please open it up in jhipster-uml instead

**Comment by Maury1329** [comment]
That was seemingly a Liquibase issue. I was to quick in posting it.
I still has to figure out what the underlying problem was.
Sorry for the inconvience and thanks anyway.
