### ISSUE TITLE
Issues with deploying app on AWS - No Solution Stack named '64bit Amazon Linux 2015.03 v1.4.1 running Tomcat 8 Java 8' found

### ISSUE THREAD

**Issue by ankitgoel1987** [jhipster/generator-jhipster#1875]
Hi,

I am trying to deploy my application built using JHipster on AWS by following the steps mentioned in this document - http://jhipster.github.io/aws.html

It fails. This is what I see printed on my command prompt.

Create S3 bucket
Bucket <bucketName> already exists

Upload WAR to S3
War uploaded successful

Create database
Database created successful

Waiting for database (This may take several minutes)
Database available at jdbc:mysql://<Url>:3306/<dbname>

Create/Update application
x No Solution Stack named '64bit Amazon Linux 2015.03 v1.4.1 running Tomcat 8 Java 8' found.

Can someone please help me with resolving the problem here.

Thanks in advance,
Ankit

P.S: Many thanks to the JHipster team for building such an awesome generator.

**Comment by deepu105** [comment]
this has been fixed in master, please wait for the next release

**Comment by ankitgoel1987** [comment]
@deepu105 : Thanks for the response. Is there a way I can apply the fix on my local installation? We have a pressing need to deploy our app on AWS and waiting for the next release of JHipster does not look like a viable solution.

**Comment by deepu105** [comment]
you can fork the master branch, do a pull to your local and then go into
the folder and do a `npm link` this will make the generator point to this
folder and now if you run `yo jhipster` or any sub gen it will be based on
wats in this folder.

If you cant fork/pull then just download the master zip and unzip to a
folder and do the same as above

On Mon, Aug 17, 2015 at 8:48 AM, Ankit Goel <notifications@github.com>
wrote:

> @deepu105 <https://github.com/deepu105> : Thanks for the response. Is
> there a way I can apply the fix on my local installation? We have a
> pressing need to deploy our app on AWS and waiting for the next release of
> JHipster does not look like a viable solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1875#issuecomment-131645929>
> .
>



-- 
thank you,
Deepu.k.s
