### ISSUE TITLE
Set default format ZonedDateTime in view page for all entities

### ISSUE THREAD

**Issue by antsch01** [jhipster/generator-jhipster#18769]
##### **Overview of the issue**

I see that for all entities with attribute ZonedDateTime in the view page the data is not formatted, while in list page yes.
If I see the generator file I can see for example in:

entity-component.html- > {{ orderEntry.departureDate | date:'medium' }}
entity-detail.html -> {{ orderEntry.departureDate }}

to fix it I updated all generator file adding "| date:'medium'" in *-detail.html files.

My question is: Is there a way to not update the generator files and do the same by configuration?

##### **Motivation for or Use Case**
I don't want to update generator file, because I regenerate the entity I have to handle a lot of conflicts.

##### **Reproduce the error**
Create an entity with an attribute of type ZonedDateTime

##### **JHipster configuration**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.seaviaggiare.app",
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "seaviaggiare",
    "packageName": "com.seaviaggiare.app",
    "packageFolder": "com/seaviaggiare/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1633264908943,
    "testFrameworks": ["cucumber"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": ["it", "en"],
    "blueprints": []
  }
}

</pre>
</details>

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@antsch01 There is no configuration available.
You might need to upgrade the application to fix it...
Closing for now
