### ISSUE TITLE
 Git Commit Guidelines are outdated

### ISSUE THREAD

**Issue by emilpaw** [jhipster/generator-jhipster#18768]
##### **Overview of the feature request**

In the contribution guidelines, there are some rules about how to format the commit messages. Most commits in the repository don't follow the rules. Especially the one about capitalizing the first letter: https://github.com/jhipster/generator-jhipster/blob/dbf76ed6209f2ba02fb30476893e9ff0588776fd/CONTRIBUTING.md?plain=1#L376 and about being required to add a Github keyword in the footer of the message: https://github.com/jhipster/generator-jhipster/blob/dbf76ed6209f2ba02fb30476893e9ff0588776fd/CONTRIBUTING.md?plain=1#L390-L391 

I think we should change the rules to required capitalization (as most commits already do). 

Regarding the rule to always use Github keywords in the footer, I don't think it's a requirement in all cases since sometimes a Commit is not directly related to the commit which is worked on. e.g. small refactorings or fixed typos. 

##### **Motivation for or Use Case**

Rules which are not followed are useless at best and confusing at worst. 
Commit messages which follow a convention are easier to read.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
At least for the footer I understand the *must* for automatic closing (otherwise it won't work). So no must for a footer in general as (you said correctly) not every commit relates to an issue.
