### ISSUE TITLE
Add frontend sort when no pagination

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#18778]
##### **Overview of the feature request**

Jhipster lack of essential features to get really usable forms.
One of them is that there's no sort on fields when pagination is not selected.
It would be really easy to implement while being cool for end users.

##### **Motivation for or Use Case**

Improving the waow effect of a jhipster generation at low cost

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
@deepu105 I get why the react-jhipster is complaining: some form React elements of the library are manipulating states and effects within the library itself, which is considered as a bad practice and unsupported in the last react versions.
It's very hard for me to adapt the lib as I didn't produce it by myself, so any help would be really appreciated.
Otherwise I'll continue to look at it, but it can take a bit of time...

**Comment by deepu105** [comment]
I'll check when I find some time

**Comment by Tcharl** [comment]
Created a branch with the current library achievement

https://github.com/Tcharl/react-jhipster/tree/sort_non_paginated
https://github.com/Tcharl/generator-jhipster/tree/sort_react

I made a bit of progress, but still some work to achieve
