### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by khachaturs** [jhipster/generator-jhipster#1877]
Project is set up and is working fine on local machine, but when I deploy to the server it stats redirecting to login page all the time.

During debugging i found this condition in app.js file

if (response.status == 401 && response.data.path!="/api/account") {
  // redirecting to login page
}

again, it works fine on local machine, but on the server when it calls "api/account", returned  "response.data.path" is null, it's again being redirected to the login page, and doing the same call. Here goes the infinite loop.

**Comment by deepu105** [comment]
are you deploying the app with a context or is it just straight boot run?

the above code infact was to avoid that kind of looping

**Comment by jdubois** [comment]
@deepu105 indeed, this is supposed to be solved (and I've never had the issue myself!)

So @khachaturs I'm closing this as:

- you did not provide your JHipster version number (we don't know if it's fixed or not)
- you did not provide your JHipster options (this is probably linked to your security configuration)
- and the title of your ticket is not explicit

Please, also have a look in the tickets history, this has already been discussed, as mentioned by @deepu105 

-> please follow our guidelines for submitting issues, and re-submit your issue correctly
