### ISSUE TITLE
Compilation error: duplicate class

### ISSUE THREAD

**Issue by afedulov** [jhipster/generator-jhipster#1878]
Mapstruct causes compilation error.

Steps to reproduce:
1) Generate entity: "yo jhipster:entity foo" having one String field and select DTO option
2) mvn install

Result:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/Development/project_name/target/generated-sources/org/projectname/web/rest/mapper/
FooMapperImpl.java:[14,8]duplicate class: org.projectname.web.rest.mapper.FooMapperImpl
```
Target folder contains duplicate classes:
generated-source/annotaions/org/projectname/web/rest/mapper/FooMapperImpl.java
generated-source/org/projectname/web/rest/mapper/FooMapperImpl.java

The difference between those classes is that the one in the "annotations" folder does not contain timestamp of generation, so it comes from someone who obviously ignores the "mapstruct.suppressGeneratorTimestamp" parameter configured in pom.xml

Any ideas what could cause sources generation being called twice?

**Comment by jdubois** [comment]
I guess you also have your IDE running, and that it created that other class. Can you confirm this?

-> in that case it would be an IDE configuration to do, and it is not explained in our documentation

**Comment by afedulov** [comment]
Running "mvn clean install" from a console with IntelliJ shut down produces the same error.

**Comment by afedulov** [comment]
I have found out what the problem was. I had an issue described in https://github.com/jhipster/generator-jhipster/issues/1558 and in order to solve it I have added this dependency, as advised as a workaround by one of the posters:
```
 <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>${mapstruct.version}</version>
            <scope>provided</scope>
        </dependency>
```
Removing the processor from main dependencies resolves the problem of erroneous classes generation, but causes IntelliJ to fail with the "java: Annotation processor 'org.mapstruct.ap.MappingProcessor' not found"  error. I had to remove this annotations processor from IntelliJ manually in order to be able to compile.

**Comment by jdubois** [comment]
@afedulov could you help us to improve the documentation on this?

**Comment by afedulov** [comment]
Sure, here it is:

https://docs.google.com/document/d/1UiK5ZUWSJ2bAwM4Cg25QjoERtudYrWWPi7qJF97qNUw/edit?usp=sharing

The whole thing actually turned out to be much more convoluted, than initially expected.

**Comment by shaivyamahajan** [comment]
Disabling annotation processing in maven-compiler-plugin seems to fixe the duplicate class error, might be a more universal solution.  This relies on the maven-processor-plugin, which jhipster includes by default, to perform the annotation processing.  Just have to add this to the pom:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.1</version>
    <configuration>
        <source>${maven.compiler.source}</source>
        <target>${maven.compiler.target}</target>
        <proc>none</proc> <!-- disable annotation processing to avoid duplicating maven-processor-plugin output -->
    </configuration>
</plugin>
```


This allows including mapstruct as a dependency for IntelliJ:
```
 <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>${mapstruct.version}</version>
            <scope>provided</scope>
 </dependency>
```

**Comment by akrima** [comment]
I had the same issue but when i inspect the pom.xml i found that i call the dependency 

<dependency>
	<groupId>org.mapstruct</groupId>
	<artifactId>mapstruct-processor</artifactId>
	<version>1.0.0.Final</version>
	<scope>compile</scope>
</dependency>

in the build tag too
So i kepp who in the build tag and i remove the other like this:

<build>
		<plugins>
			<plugin>
				<groupId>org.bsc.maven</groupId>
				<artifactId>maven-processor-plugin</artifactId>
				<version>2.2.4</version>
				<executions>
					<execution>
						<id>process</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>process</goal>
						</goals>
						<configuration>
							<defaultOutputDirectory>${basedir}\target/generated-sources/struct-mapper</defaultOutputDirectory>
							<processors>
								<processor>org.mapstruct.ap.MappingProcessor</processor>
							</processors>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.mapstruct</groupId>
						<artifactId>mapstruct-processor</artifactId>
						<version>1.0.0.Final</version>
						<scope>compile</scope>
					</dependency>
				</dependencies>
				<configuration>
					<defaultOutputDirectory>${basedir}\target/generated-sources</defaultOutputDirectory>
					<processors>
						<processor>org.mapstruct.ap.MappingProcessor</processor>
					</processors>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>add-source</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>${basedir}\target/generated-sources/struct-mapper</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

**Comment by gmarziou** [comment]
@akrima please open a new issue and follow our guidelines rather than posting on an issue that was closed one year ago.

**Comment by gmarziou** [comment]
@akrima could you clarify your point? Do you mean the doc is wrong and are you proposing a change?

**Comment by Bill-TT** [comment]
> <proc>none</proc>

> 在 maven-compiler-plugin 中禁用注释处理似乎可以修复重复的类错误，这可能是一个更通用的解决方案。这依赖于 jhipster 默认包含的 maven-processor-plugin 来执行注释处理。只需要将其添加到 pom 中：
> 
> ```
> <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-compiler-plugin</artifactId>
>     <version>3.1</version>
>     <configuration>
>         <source>${maven.compiler.source}</source>
>         <target>${maven.compiler.target}</target>
>         <proc>none</proc> 
>     </configuration>
> </plugin>
> ```
> 
> 这允许包含 mapstruct 作为 IntelliJ 的依赖项：
> 
> ```
>  <dependency>
>             <groupId>org.mapstruct</groupId>
>             <artifactId>mapstruct-processor</artifactId>
>             <version>${mapstruct.version}</version>
>             <scope>provided</scope>
>  </dependency>
> ```

It's work,Thanks

> Disabling annotation processing in maven-compiler-plugin seems to fix the duplicate class error, might be a more universal solution. This relies on the maven-processor-plugin, which jhipster includes by default, to perform the annotation processing. Just have to add this to the pom:
> 
> ```
> <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-compiler-plugin</artifactId>
>     <version>3.1</version>
>     <configuration>
>         <source>${maven.compiler.source}</source>
>         <target>${maven.compiler.target}</target>
>         <proc>none</proc> 
>     </configuration>
> </plugin>
> ```
> 
> This allows including mapstruct as a dependency for IntelliJ:
> 
> ```
>  <dependency>
>             <groupId>org.mapstruct</groupId>
>             <artifactId>mapstruct-processor</artifactId>
>             <version>${mapstruct.version}</version>
>             <scope>provided</scope>
>  </dependency>
> ```

It's work, Thanks
