### ISSUE TITLE
Heroku + Okta: user not added to ROLE_USER group if jq not installed

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#18793]
##### **Overview of the issue**

I experienced [an issue](https://github.com/jhipster/generator-jhipster/pull/18774#issuecomment-1144063728) today when testing Heroku + Elasticsearch. Since I didn't have `jq` installed, I had to manually run the `./provision-okta-addon.sh` script. The username I entered was never given a password, so I logged in to Okta with my Heroku settings (OKTA_ADMIN_EMAIL and OKTA_ADMIN_PASSWORD) and reset the password. 

After logging in to my JHipster app, I found I was unable to view entity screens. This was because my user wasn't added to the `ROLE_USER` group. Once I added them, I was able to see everything as expected. 

##### **Motivation for or Use Case**

This could be a one-time issue, but I wanted to enter it just in case it's reproducible. 

##### **Reproduce the error**

Uninstall `jq` and deploy a JHipster app with OAuth to Heroku. 

##### **JHipster Version(s)**

Today's code from the `atomfrede:18650-heroku-elasticsearch-configuration` branch.

**Comment by atomfrede** [comment]
I am not sure, but I think we generate the password and do not store it somewhere (we did once but changed it). Maybe we just need to update documentation and output of the script, such that the user knows to reset the password. 

Regarding the missing user role I will have a look, it should not be the case.

**Comment by mraible** [comment]
Adding bug bounty for investigation.

**Comment by dagboujhatem** [comment]
Hello, i can try to fix this issue.

**Comment by mshima** [comment]
@mraible this issue can be closed?
