### ISSUE TITLE
Generate project README.md with build instructions

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1880]
The project README.md file should contain basic instructions about how to setup environment and use build process according to the tools chosen during generation (maven/gradle and grunt/gulp).

**Comment by mraible** [comment]
I believe there's a typo in the header: "Developping" should be "Developing"

**Comment by jdubois** [comment]
Thanks @mraible it's corrected https://github.com/jhipster/generator-jhipster/commit/55c2aa632cfc519423c6408f99d6ebe8ef5d95f3
