### ISSUE TITLE
Upgrade to Angular 14

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#18817]
##### **Overview of the feature request**

Angular 14 has been released.

The most significant change is typed forms.
As part of this migration, we should migrate away from FormBuilder.

- [x] update build config
- [x] migrate to typed form

We are missing libs to support it, but we can start migration.

Dependencies:
- [x] jest@28
- [x] @angular-builders/* (https://github.com/just-jeb/angular-builders/issues/1219)
- [x] @angular-eslint/eslint-plugin (https://github.com/angular-eslint/angular-eslint/pull/1004)
- [x] @fortawesome/angular-fontawesome (v0.11.0)
- [x] @ngx-translate/* (peer >= 13)
- [ ] @ng-bootstrap/ng-bootstrap (https://github.com/ng-bootstrap/ng-bootstrap/issues/4340)
- [x] ngx-cookie-service (v14.0.0)
- [x] ngx-infinite-scroll (https://github.com/orizens/ngx-infinite-scroll/issues/404)
- [x] ngx-webstorage

##### **Motivation for or Use Case**

Keep updated

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/pull/18586

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Deserves a bounty, doesn't it?

**Comment by DanielFran** [comment]
Adding a bug bounty, it is a lot of work

**Comment by ari62** [comment]
apologies if this isn't the correct place to ask, but will we be able to upgrade our angular version easily via a jhipster or angular command line command? thank you

**Comment by Tcharl** [comment]
Hi @ari62 , it's in the doc here: https://www.jhipster.tech/upgrading-an-application/

**Comment by ksilz** [comment]
@Tcharl, that page doesn't mention Angular (or React or Vue, for that matter). Here's what step 8 in the "[Step-by-step explanation of the upgrade process](https://www.jhipster.tech/upgrading-an-application/#step-by-step-explanation-of-the-upgrade-process)" says: "Re-generate the application using the jhipster --force --with-entities command."

I think this means there's **no use of the Angular upgrade command** as the Angular application is re-created from scratch. The resulting **new** Angular application is then combined with the **existing** version of that Angular application through Git merge. Correct?

**Comment by ksilz** [comment]
@ari62 Please see my previous comment if you haven't done so. @Tcharl agrees with it.
