### ISSUE TITLE
Reorganizing the JHipster documentation

### ISSUE THREAD

**Issue by michaelisvy** [jhipster/generator-jhipster#1881]
Hi,
I think the JHipster documentation is getting big and it would be nice to reorganize it so users can find information faster. 

Main goals: 
- avoid to use words such as "introduction", "setup", "presentation" etc and try to be more specfic
- some pages should be broken into several pages  (such as "Using in development")
- Separate out "environment setup" from "core JHipster tasks" such as creating an entity

What would you think of the below structure?

1) JHipster in 5 minutes (currently called "introduction")
* Technical stack
* Official JHipster slides (currently called "presentation")
* JHipster in 5 screenshots
* Video tutorial

2) Setting up your environnement
* Install JHispter
* Configure JHipster in Eclipse
* Configure JHispter in IntelliJ IDEA
* Contributors: installing a development environment

3) Core JHipster tasks
* Creating a JHipster application
* Creating an entity
* Creating a service
* Creating DTOs
* Managing relationships
* Adding a new language

4) Understanding and customizing generated code
* AngularJS generation (currently called "Development/Using AngularJS")
* Customizing CSS (currently called "Customizing Bootstrap")
* Automated tests (currently inside "Test/running tests")

5) Running JHipster 
(currently inside "Using in development" page that should be split into several pages)

6) Third party integrations
* Elastic Search 
* Cassandra
* MongoDB
* Oracle

7) JHipster profiles: development, test, production
* Introduction to profiles (currently inside "Managing profiles" page)
improvement: we should add a matrix to explain differences between various profiles

8) JHipster in production
* Best practices when using JHipster in production (currently "Production/Using in production")
* Deploying to Cloud Foundry
* Deploying to Heroku
* Deploying to OpenShift
* Deploying to AWS

9) JHipster-UML

10) Continuous Integration
 (currently inside "Test/Continuous integration")

11) Tips and tricks from JHipster users
 
12) Help and Bugs

13) About

**Comment by atomfrede** [comment]
Looks good so far to me. I would like to have the Tips'n Tricks at the root menu level and ``Install a new Language`` belongs to ``Core JHipster tasks`` I think.

**Comment by jdubois** [comment]
I would also like to:

- rename all the pages with underscores to use a dash instead ("create_a_new_app" -> "create-a-new-app") as it's better for SEO. What's bad is that we will have tons of 404 errors (I tried to do a redirect rule with Jekyll but that failed!)
- migrate everything from HTML to MarkDown (only reason we have HTML is that I didn't know we could use MarkDown in the first place!)
- host everything to our own domain name (I still need to decide which one... BTW the jhipster.com domain is owned by our friend Matt Raible, and redirects to our github page). The main issue is that Github pages can't handle SSL on a custom domain, and that should be bad for SEO -> that means I should have a look at hosting this myself, but I'm so happy with the way Github pages work that this really annoys me.

**Comment by michaelisvy** [comment]
@atomfrede I have reflected both changes above. We'll have to see if we don't have too many first level sections.
@jdubois sure, those changes can be done in the end.

**Comment by jdubois** [comment]
@michaelisvy as I merged your PR I'm closing this.
