### ISSUE TITLE
Auditing AUTHORIZATION_FAILURE for anonymousUser

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1882]
I deployed a JHipster app to Heroku in mid-June. You can see it at http://www.jhipster-book.com/. I've made a few data entries, but haven't done much with it for the most part. The good news is it's been up and running with no issues for over two months. However, this evening I received the following email from Heroku:

> The database HEROKU_POSTGRESQL_GREEN_URL on Heroku app jhipster-news is approaching its allocated storage capacity.

> The database contains 8,059 rows. The Hobby-dev plan allows a maximum of 10,000 rows. If the databases exceeds 10,000 rows then INSERT privileges will be revoked, preventing more data from being written. INSERT privileges are automatically reinstated if rows are removed and the database once again complies with the plan limit.

> To avoid a disruption to your service, migrate the database to a Basic ($9/month) or higher plan:

> https://devcenter.heroku.com/articles/upgrade-heroku-postgres-with-pgbackups

> If you are unable to upgrade the database, you should limit or reduce the number of records in it.

Looking at my database, the `jhi_persistent_audit` tables have just over 8000 records in them. Most of the records are AUTHORIZATION_FAILURE for anonymousUser. I'm guessing this is because a request is made to http://www.jhipster-book.com/api/account?cacheBuster=1439867362419 when users hit the homepage. 

Two questions:

1. Is it possible to turn off this request to account on the default page?
2. Is it possible to turn off logging of AUTHORIZATION_FAILURE for anonymousUser?

**Comment by jdubois** [comment]
Yes it's a good feedback.
Besides, for performance reasons, I'm not sure it's good to have this enabled by default -> shouldn't we disable it by default, and make it optional with a change in the application.yml file? I'm not sure this is issued by most people, any feedback on this?

**Comment by deepu105** [comment]
I had similar issue with this table having too much rows that too i had an sso authenticating every request so i have a DB job that clears data that is older than a month.
I personally feel that the user activity audit in its current form is not very useful, if we are able to make it log one request per login with some more info this might be more useful.

**Comment by jdubois** [comment]
I'm not sure we can tune this easily, the auditing is done automatically... I would rather remove it completely. Besides, there's a performance overhead and I'm not sure most people would want this.

Then, we could add some options:

- to have the auditing on again
- to have some security rules that are not provided by default (as Spring Security doesn't have a backend). My idea (from years ago!!) initially was to do some kind of "fail2ban" on users who fail their login attempts too many times.

**Comment by afedulov** [comment]
Would this modification to the CustomAuditEventRepository seem too hacky?

```
            @Override
            @Transactional(propagation = Propagation.REQUIRES_NEW)
            public void add(AuditEvent event) {
                if(!AUTHENTICATION_FAILURE.equals(event.getType())){
                   ...
                    persistenceAuditEventRepository.save(persistentAuditEvent);    
                }
            }
```
This would have the benefit of filtering quite useless authentication failures (as Julien proposes, this should be handled on a different level) and at the same time keep potentially useful audit information logs.

**Comment by mraible** [comment]
I think this would work. It might be useful to know when real users fail to
login, but I guess everyone is anonymous before authenticating.

On Thu, Aug 20, 2015 at 4:16 PM, Alexander Fedulov <notifications@github.com

**Comment by deepu105** [comment]
Im also finding this very annoying as its writing too much logs especially with a single sign on setup

**Comment by jdubois** [comment]
OK let's do it this way!

**Comment by jdubois** [comment]
I'm going to push the code solving this, but I'm not entirely satisfied:

- Losing the authentication failures could be annoying if someone tries to guess someone's login -> anyway my goal in the long run is to have something that does works like fail2ban, blacklisting those user IPs for some time
- Then, but it's another issue, each success login gives 3 success events -> no idea what causes it, as far as I understand this is all done by Spring Boot's audit feature, so it seems this is not our fault

And maybe we should also have some kind of cleaning mechanism, like a scheduled job that deletes older events after a fixed period.

**Comment by jdubois** [comment]
I'm opening another issue for the 3 success events
