### ISSUE TITLE
Generate frontend and backend seperately

### ISSUE THREAD

**Issue by paris0120** [jhipster/generator-jhipster#18850]
##### **Overview of the feature request**

Add an option to generate frontend and backend seperately

##### **Motivation for or Use Case**

Currently, the generator has the option --skip-client and --skip-server yet if generated separately by default the frontend server will still connect to the backend server with the same port (SERVER_API_URL  = ''). I'm wondering if an option can be added so that the front and back ends can be generated separately (in the case of a monolith app it can be <app name>/backend and <app name>/frontend, in the case of microservice gateway it can be /gateway and /frontend. Currently, all the scripts are there so only a front-end port is needed for the jdl and set the SERVER_API_URL value in the environment.js to the backend server.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Do you want to run your apps on separate ports in production or just in development? The reason I ask is because all the authentication mechanisms (accept for JWT) rely on cookies to communicate between the frontend and backend. We do this because [JWTs aren't that great for session tokens](https://developer.okta.com/blog/2017/08/17/why-jwts-suck-as-session-tokens).

**Comment by mraible** [comment]
Our current OAuth 2.0 support uses Spring Security and stores the access and ID tokens in the session on the server. We do it this way because it's more secure than doing authentication on the client and it's easier to implement so we don't have to use a different OIDC library for each frontend framework.

If you want to use any of JHipster's existing frontend implementations, you'd need to refactor them to do authentication on the client and pass an access token to the server for data. Or, you could use [Ionic for JHipster](https://developer.okta.com/blog/2022/05/12/ionic-angular-jhipster) to create a separate frontend client that runs standalone and talks to a JHipster backend.

**Comment by paris0120** [comment]
> 



> Our current OAuth 2.0 support uses Spring Security and stores the access and ID tokens in the session on the server. We do it this way because it's more secure than doing authentication on the client and it's easier to implement so we don't have to use a different OIDC library for each frontend framework.
> 
> If you want to use any of JHipster's existing frontend implementations, you'd need to refactor them to do authentication on the client and pass an access token to the server for data. Or, you could use [Ionic for JHipster](https://developer.okta.com/blog/2022/05/12/ionic-angular-jhipster) to create a separate frontend client that runs standalone and talks to a JHipster backend.

Can I run a frontend server as a microservice and point the gateway to that server?

**Comment by ndywicki** [comment]
For the monolithic version this is possible, as described in the documentation:
[separating-front-end-and-api](https://www.jhipster.tech/separating-front-end-and-api/#-separating-the-front-end-and-the-api-server)

On the other hand it is not a good idea to specify a value for SERVER_API_URL, in addition to the CORS setting, from a client point of view, calls to the backend API must be open to the outside (open firewall routes). The ideal is to close the backend and go through a reverse proxy like Nginx.
In this case the API calls will be `http://yourdomain.com/api/**`

Remarks:

- The NGINX configuration [configuration](https://www.jhipster.tech/separating-front-end-and-api/#configuration-lambda) is no longer up to date. Here an up to date sample:

```
server {
    listen 80;
    index index.html;
    server_name localhost;
    error_log  /var/log/nginx/error.log;

    root /usr/share/nginx/html;
	

    location /api {
        proxy_pass http://api.jhipster.tech:8081/api;
    }
    location /services {
        proxy_pass http://api.jhipster.tech:8081/services;
    }
    location /management {
        proxy_pass http://api.jhipster.tech:8081/management;
    }        
    location /v3/api-docs {
       proxy_pass http://api.jhipster.tech:8081/v3/api-docs;
    }
    location /h2-console {
       proxy_pass http://api.jhipster.tech:8081/h2-console;
    }
    location /oauth2 {
       proxy_pass http://api.jhipster.tech:8081/oauth2;
    }
	location /login {
       proxy_pass http://api.jhipster.tech:8081/login;
    }
	location /auth {
       proxy_pass http://api.jhipster.tech:8081/auth;
    }
	location /health {
       proxy_pass http://api.jhipster.tech:8081/health;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
```


- If OAuth2 is used, the server must be configured to use HTTP headers, to correctly generate the `redirect-uri` for the frontend (and not the backend). So you need to add in NGINX config:

```
proxy_set_header	X-Forwarded-Host    $host;
proxy_set_header	X-Forwarded-Port    $server_port;
```

 Also add in the `application.yml` the server config `server.forward-headers-strategy=framework` to use it:

```
server:
  servlet:
    session:
      cookie:
        http-only: true
  forward-headers-strategy: framework
```
