### ISSUE TITLE
Having Issues with Dependencies and Plugins

### ISSUE THREAD

**Issue by CTaylorEason** [jhipster/generator-jhipster#18855]
Hi,

I'm having trouble with five unique dependencies and plugins that were imported at the start of my jhipster project. Here are the dependencies and plugins: 

***********************************

<plugin>
    <groupId>io.github.git-commit-id</groupId>
    <artifactId>git-commit-id-maven-plugin</artifactId>
</plugin>

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-war-plugin</artifactId>
</plugin>

<id>zipkin</id>
<dependencies>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-sleuth</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-sleuth-zipkin</artifactId>
    </dependency>
</dependencies>
</profile>

***********************************

Here is a screen shot of the errors and another one of the stack trace: 

![Screenshot 2022-06-07 165808](https://user-images.githubusercontent.com/74200516/172503743-c390d3bd-5e4f-44e9-bbc5-a05ac96c3b49.png)

![Screenshot 2022-06-07 170517](https://user-images.githubusercontent.com/74200516/172504066-5d90ea85-6cfc-4ee5-9e02-728bac230405.png)

I've had my friend run the exact same program on his version of IntelliJ, and it worked perfectly. If there is someone who can help me explain what is going on and how to fix it, I would be most grateful! 

Thank you,
Taylor

**Comment by paris0120** [comment]
Did you load all the dependencies?

**Comment by CTaylorEason** [comment]
Hi,

Yes, I did, and I got the dependencies registering now; however, I have this new error in the stack trace: 

2022-06-10 12:30:50.822  WARN [testwebsite,,] 26240 --- [  XNIO-1 task-2] o.z.problem.spring.common.AdviceTraits   : Unauthorized: Full authentication is required to access this resource
2022-06-10 12:30:50.857 ERROR [testwebsite,,] 26240 --- [  XNIO-1 task-1] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.io.IOError: java.io.FileNotFoundException: Invalid file path
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
...

I'm running this on a local host in postgresql, and trying to access it on google chrome, but I keep running into this error.http.500. The tables have be built in the database by jhipster, and all my code for that has been built by jhipster too. I just can't access it via npm start. I'm running both the backend via ./mvnw and then running the frontend on a new terminal with npm start. it pulls up on localhost 9000 like normal but looks like this: 

![Screenshot 2022-06-10 123547](https://user-images.githubusercontent.com/74200516/173137774-b40d2c0a-db03-4e31-baf1-680ad5343116.png)


 I have no idea what's happening.

**Comment by CTaylorEason** [comment]
the frontend stack trace says there is something to do with my browser sync: 

Error: Cannot find module 'browser-sync-client/dist/index.min.js'
Require stack:
- C:\codingprojects\testwebsite\node_modules\browser-sync\dist\snippet.js
- C:\codingprojects\testwebsite\node_modules\browser-sync\dist\hooks.js
- C:\codingprojects\testwebsite\node_modules\browser-sync\dist\browser-sync.js
- C:\codingprojects\testwebsite\node_modules\browser-sync\dist\index.js
- C:\codingprojects\testwebsite\node_modules\browser-sync-webpack-plugin\lib\BrowserSyncPlugin.js
- C:\codingprojects\testwebsite\node_modules\browser-sync-webpack-plugin\index.js
- C:\codingprojects\testwebsite\webpack\webpack.dev.js
- C:\codingprojects\testwebsite\node_modules\webpack-cli\lib\webpack-cli.js
- C:\codingprojects\testwebsite\node_modules\webpack-cli\lib\bootstrap.js
- C:\codingprojects\testwebsite\node_modules\webpack-cli\bin\cli.js
- C:\codingprojects\testwebsite\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at C:\codingprojects\testwebsite\node_modules\browser-sync\dist\snippet.js:87:52
    at C:\codingprojects\testwebsite\node_modules\browser-sync-client\index.js:59:39
    at Array.reduce (<anonymous>)
    at processItems (C:\codingprojects\testwebsite\node_modules\browser-sync-client\index.js:54:10)
    at C:\codingprojects\testwebsite\node_modules\browser-sync-client\index.js:89:22
    at call (C:\codingprojects\testwebsite\node_modules\connect\index.js:239:7)
    at next (C:\codingprojects\testwebsite\node_modules\connect\index.js:183:5)
    at next (C:\codingprojects\testwebsite\node_modules\connect\index.js:161:14)

**Comment by Tcharl** [comment]
Which version of node are you using? Can you try: deleting your `package.lock` and your `node_modules` then `npm install` `npm run watch`?

**Comment by CGarces** [comment]
I also have the issue with "browser-sync-client/dist/index.min.js" in the front end
<details><summary>stacktrace</summary>
Error: Cannot find module 'browser-sync-client/dist/index.min.js'
Require stack:
- C:\foo_bar\node_modules\browser-sync\dist\snippet.js
- C:\foo_bar\node_modules\browser-sync\dist\hooks.js
- C:\foo_bar\node_modules\browser-sync\dist\browser-sync.js
- C:\foo_bar\node_modules\browser-sync\dist\index.js
- C:\foo_bar\node_modules\browser-sync-webpack-plugin\lib\BrowserSyncPlugin.js
- C:\foo_bar\node_modules\browser-sync-webpack-plugin\index.js
- C:\foo_bar\webpack\webpack.custom.js
- C:\foo_bar\node_modules\@angular-builders\custom-webpack\dist\utils.js
- C:\foo_bar\node_modules\@angular-builders\custom-webpack\dist\custom-webpack-builder.js
- C:\foo_bar\node_modules\@angular-builders\custom-webpack\dist\transform-factories.js
- C:\foo_bar\node_modules\@angular-builders\custom-webpack\dist\generic-browser-builder.js
- C:\foo_bar\node_modules\@angular-builders\custom-webpack\dist\dev-server\index.js
- C:\foo_bar\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\foo_bar\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- C:\foo_bar\node_modules\@angular\cli\models\architect-command.js
- C:\foo_bar\node_modules\@angular\cli\commands\serve-impl.js
- C:\foo_bar\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\foo_bar\node_modules\@angular-devkit\schematics\tools\index.js
- C:\foo_bar\node_modules\@angular\cli\utilities\json-schema.js
- C:\foo_bar\node_modules\@angular\cli\models\command-runner.js
- C:\foo_bar\node_modules\@angular\cli\lib\cli\index.js
- C:\foo_bar\node_modules\@angular\cli\lib\init.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at C:\foo_bar\node_modules\browser-sync\dist\snippet.js:87:52
    at C:\foo_bar\node_modules\browser-sync-client\index.js:59:39
    at Array.reduce (<anonymous>)
    at processItems (C:\foo_bar\node_modules\browser-sync-client\index.js:54:10)
    at C:\foo_bar\node_modules\browser-sync-client\index.js:89:22
    at call (C:\foo_bar\node_modules\connect\index.js:239:7)
    at next (C:\foo_bar\node_modules\connect\index.js:183:5)
    at next (C:\foo_bar\node_modules\connect\index.js:161:14)
</details>

node --version 
v14.16.0

**Comment by Tcharl** [comment]
If I'm not wrong, the node version should be 16.
```
╰─ node -v
v16.15.1
```
On my side

**Comment by CGarces** [comment]
Thanks I have upgraded to v16.16.0, but still failing.
