### ISSUE TITLE
Caching of user information is not optimized for scale

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#18868]
##### **Overview of the issue**

When using OAuth 2.0, there is logic that will look up the user's information (from the OIDC `/userinfo` endpoint) to popular the user's first and last names. It caches the lookups by the `sub` claim so it only happens once per user. However, it's not optimized for scale.

```java
// Warning from Rob Winch: caching in a hashmap could be bad since there is no expiry.
// Changing attributes will never get updated, and it can grow indefinitely (run out of memory).
// Ideally, we could use @Cacheable(cacheNames="users", key="#token") on the `enrich()` method,
// but @Cacheable doesn't work on reactive types. See github.com/spring-projects/spring-framework/issues/17920
private final Map<String, Mono<Jwt>> users = new ConcurrentHashMap<>();
```

Both Spring MVC (in `CustomClaimConverter.java`) and WebFlux (in `SecurityConfiguration`) use such a map.

**NOTE**: This is not an issue for regular JHipster apps. It's only an issue when you're using JHipster as an OAuth 2.0 resource server and passing in a JWT access token to authenticate. Currently, this is only done by the Ionic and React Native blueprints. Keycloak will never do the lookup since `given_name` and `family_name` are included claims in the access token. For Auth0 and Okta, this auto-lookup makes things easier to configure.

##### **Motivation for or Use Case**

This issue is to track converting the existing implementation to use the same cache abstraction that the user chooses. 

##### **Reproduce the error**

There is no error, it's just a hack currently.

##### **Related issues**

- https://github.com/jhipster/generator-jhipster/issues/13461
- https://github.com/jhipster/generator-jhipster/issues/11767

##### **Suggest a Fix**

Use a more optimized caching solution.

Related to https://github.com/spring-projects/spring-framework/issues/17920.

**Comment by paris0120** [comment]
Sync the map for every new token or all instances get tokens from one instance so that instance can cache all the tokens and each instance has its local copy of tokens?

**Comment by mraible** [comment]
I think it's OK to have a local copy of tokens. This will only apply to monoliths and gateways.

**Comment by atomfrede** [comment]
@mraible Would you say we use one common implementation for both reactive and non-reactive e.g. by using caffeine for everything (instead of using the users selected cache implementation)?

**Comment by mraible** [comment]
@atomfrede That sounds like a reasonable solution.

**Comment by atomfrede** [comment]
I have some time during 🚅 travel, will try to create a first PR.
