### ISSUE TITLE
gradlew clean does not delete target/test-classes

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1886]
I discovered this after generated a bunch of entities, then reverting everything in Git, after I'd run the tests. When I ran `./gradlew test`, it didn't delete `target/test-classes`. I fixed this by adding the following to my `build.gradle` file.

````
clean {
    delete "target"
}
````

**Comment by atomfrede** [comment]
Thanks for the hint. Will integrate it.
