### ISSUE TITLE
JDL: DTO/Entity separate generation

### ISSUE THREAD

**Issue by b509** [jhipster/generator-jhipster#18878]
##### **Overview of the feature request**
Have the possibility to not only define the entity but also a separate DTO for it. For a DB entry you could then have an entity definition (persistence layer) as is written into the database as well as a DTO (presentation layer). Mapping is feasible with Mapstruct, either by trying to generate it or by having the user provide it according to a given format beside the JDL file.

##### **Motivation for or Use Case**
In most applications I am aware of the persistence layer is always slightly different than what is presented in the frontend/REST api. To account for that you currently have to adapt the generated code. But technically it seems pretty straight-forward to support and would make the generated functionality more powerful and cover - in my experience - a very common issue that presentation layer != persistence layer.

##### **Related issues or PR**
No related issues

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
You can generate dto for jhipster application, [see](https://www.jhipster.tech/jdl/options)

Advanced syntax is not supported yet: you can code your own DTO and your own mappers on top of jhipster-generated dtos or entities then ([see](https://www.jhipster.tech/tips/035_tip_combine_generation_and_custom_code.html))
