### ISSUE TITLE
Conflicts of dependency when add ng material

### ISSUE THREAD

**Issue by paris0120** [jhipster/generator-jhipster#18876]
##### **Overview of the issue**

This is not exactly a bug but I've been trying to add ng material with 'ng add @angular/material' but get the following errors. Is there any way I can overwrite the dependency version? I have tried --force, deleting package_lock.json, removing all the dependencies from package.json, and rebuild with npm commands but none works. Thank you so much for your time in advance. 

The package @angular/material@13.3.5 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gateway@0.0.1-SNAPSHOT
npm ERR! Found: @angular/core@13.3.1
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"13.3.1" from the root project
npm ERR!   peer @angular/core@"^13.0.0 || ^14.0.0-0" from @angular/material@13.3.5
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"13.3.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"14.0.1" from @angular/animations@14.0.1
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"^13.0.0 || ^14.0.0-0" from @angular/material@13.3.5
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"13.3.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Paris\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Paris\AppData\Local\npm-cache\_logs\2022-06-09T16_58_41_401Z-debug-0.log

##### **Motivation for or Use Case**

Frontend with Material

##### **Reproduce the error**

ng add @angular/material

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
You need to install a version of Angular Material that works with Angular 13. For example:

```
ng add @angular/material@12
```

Note that if you want to use Angular Material, you'll need to rewrite all the templates to use material components. An easier way is to use a Material theme with Bootstrap. https://stackoverflow.com/a/72481929/65681

**Comment by paris0120** [comment]
> ```
> ng add @angular/material@12
> ```

I tried with different versions but it looks like no one has the core and animation matching with the one used by jhipster.  I have developed a frontend with Material and I just want to move it to the gateway and let it call the services generated by jhipster. Also, it looks like I need a paid account to use the components from Material Design for Bootstrap.


The package @angular/material@12 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gateway@0.0.1-SNAPSHOT
npm ERR! Found: @angular/core@13.3.1
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"13.3.1" from the root project
npm ERR!   peer @angular/core@"^12.0.0 || ^13.0.0-0" from @angular/material@12.2.13
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"12" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"13.3.11" from @angular/animations@13.3.11
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"^12.0.0 || ^13.0.0-0" from @angular/material@12.2.13
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"12" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/paris/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paris/.npm/_logs/2022-06-09T18_44_30_906Z-debug-0.log

**Comment by mshima** [comment]
You will need to install every dependency `ng add @angular/material@13 @angular/animations@13`.

Closing this is not supported by jhipster.
