### ISSUE TITLE
Deploying fresh app to heroku - Only PostgreSQL is Supported for Heroku generator

### ISSUE THREAD

**Issue by levrun** [jhipster/generator-jhipster#1890]
Hi, guys.
I'm trying to use following doc http://jhipster.github.io/heroku.html in order to try heroku deployment:
* Install heroku toolbelt
* Logged to heroku in command line
* run: yo jhipster:heroku
But in result I've got following error:
```javascript
Only PostgreSQL is Supported for Heroku generator
```
How I could fix/solve this issue?

**Comment by deepu105** [comment]
What database did you choose for the application generated.
Please provide your .yo-rc.json

**Comment by jdubois** [comment]
It can only work with Postgresql, that's written in the documentation at http://jhipster.github.io/heroku.html

-> I'm closing this as this is not an issue, it's a limitation that is documented.

If you want to work with another database it probably isn't very difficult, have a look at the generated code. Of course, that depends of the database you want to have!

-> If you do it, for example with MySQL, can you send us an update? So we could improve the code and the documentation.
