### ISSUE TITLE
Mvn install build fails

### ISSUE THREAD

**Issue by NoxNox92** [jhipster/generator-jhipster#18919]
##### **Overview of the issue**

Hello,
i've created a project with Jhipster (Italian as native language), when i run mvn install (both IntelliJ and command prompt) a test fails:

https://i.stack.imgur.com/vWyME.png

##### **Motivation for or Use Case**

As suggested on SO other users faced the same problem.

##### **Reproduce the error**

I ran in order mvn clean, mvn package and mvn install from command prompt or IntelliJ.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/17946

##### **Suggest a Fix**

Creating message_it.properties by copying message_en.proprties in src/test/resources/i18n seems to work.

##### **JHipster Version(s)**

v7.8.1

##### **JHipster configuration**

Welcome to JHipster v7.8.1

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
prova@0.0.1-SNAPSHOT C:\Users\fnocentini\Documents\prova
`-- generator-jhipster@7.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "prova",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1654790671792,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "jwtSecretKey": "",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "it",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "11.0.15" 2022-04-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.15+8-LTS-149, mixed mode)

git version 2.36.1.windows.1

node: v16.15.1

npm: 8.11.0

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Browsers and Operating System**

Windows 10 Pro
Mozilla Firefox 101.0.1

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Do you know the translation in it?

Can you PR? it's easy: 
- The error looks to be [here](https://github.com/jhipster/generator-jhipster/blob/main/generators/languages/templates/src/test/resources/i18n/messages_it.properties.ejs)
- It is missing one property compare to other languages (i.e. [french](https://github.com/jhipster/generator-jhipster/blob/main/generators/languages/templates/src/test/resources/i18n/messages_fr.properties.ejs)
You just have to add the missing key translated: email.activation.title=italian translation of 'activate your account' <%= baseName %>

**Comment by gmarziou** [comment]
@hamaarouf great job, thanks.

**Comment by gmarziou** [comment]
@NoxNox92 the fix will be part of next release
