### ISSUE TITLE
Add micro frontend example in the JDL studio

### ISSUE THREAD

**Issue by paris0120** [jhipster/generator-jhipster#18922]
##### **Overview of the feature request**

microfrontend jdl example in the jdl studio

##### **Motivation for or Use Case**

show how to use microfrontend.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
There is one in the JDL samples project. However, it won't work unless you use the main branch or wait for the next release.

https://github.com/jhipster/jdl-samples/blob/main/reactive-mf.jdl
