### ISSUE TITLE
Error: Cannot find module 'yeoman-environment'

### ISSUE THREAD

**Issue by pulkitnandan** [jhipster/generator-jhipster#1892]
On this "Linux ip 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
" machine it fails again.

ubuntu@ip:~$ node -v
v0.12.7
ubuntu@ip:~$ npm -v
2.13.5

ubuntu@ip:~$ npm cache clean && npm install yo

spawn-sync@1.0.13 postinstall /home/ubuntu/node_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync
node postinstall
yo@1.4.7 postinstall /home/ubuntu/node_modules/yo
yodoctor
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✔ NODE_PATH matches the npm root

Everything looks all right!
yo@1.4.7 node_modules/yo
├── titleize@1.0.0
├── array-uniq@1.0.2
├── figures@1.3.5
├── user-home@1.1.1
├── async@1.4.2
├── opn@1.0.2
├── humanize-string@1.0.1 (decamelize@1.0.0)
├── sort-on@1.2.2 (arrify@1.0.0, dot-prop@2.2.0)
├── yeoman-character@1.0.1 (supports-color@1.3.1)
├── string-length@1.0.1 (strip-ansi@3.0.0)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── root-check@1.0.0 (downgrade-root@1.1.0, sudo-block@1.2.0)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── repeating@1.1.3 (is-finite@1.0.1)
├── meow@3.3.0 (object-assign@3.0.0, camelcase-keys@1.0.0, minimist@1.1.3, indent-string@1.2.2)
├── yosay@1.0.5 (ansi-regex@1.1.1, ansi-styles@2.1.0, word-wrap@1.1.0, pad-component@0.0.1, strip-ansi@2.0.1, taketalk@1.0.0, minimist@1.1.3, string-width@1.0.1)
├── configstore@1.2.1 (os-tmpdir@1.0.1, object-assign@3.0.0, graceful-fs@4.1.2, uuid@2.0.1, xdg-basedir@2.0.0, osenv@0.1.3, write-file-atomic@1.1.2, mkdirp@0.5.1)
├── package-json@1.2.0 (registry-url@3.0.3)
├── npm-keyword@1.2.0 (registry-url@3.0.3)
├── update-notifier@0.5.0 (is-npm@1.0.0, latest-version@1.0.1, semver-diff@2.0.0)
├── got@3.3.1 (lowercase-keys@1.0.0, is-stream@1.0.1, timed-out@2.0.0, is-redirect@1.0.0, prepend-http@1.0.2, object-assign@3.0.0, infinity-agent@2.0.3, nested-error-stacks@1.0.1, read-all-stream@3.0.1, duplexify@3.4.2)
├── fullname@1.1.0 (npmconf@2.1.2)
├── cross-spawn@0.4.1 (lru-cache@2.6.5, spawn-sync@1.0.13)
├── yeoman-environment@1.2.7 (escape-string-regexp@1.0.3, log-symbols@1.0.2, diff@1.4.0, text-table@0.2.0, untildify@2.1.0, debug@2.2.0, mem-fs@1.1.0, globby@2.1.0, grouped-queue@0.3.0)
├── insight@0.6.0 (object-assign@2.1.1, lodash.debounce@3.1.1, async@0.9.2, os-name@1.0.3, tough-cookie@1.2.0, request@2.60.0)
├── lodash@3.10.1
├── yeoman-doctor@1.4.0 (log-symbols@1.0.2, object-values@1.0.0, each-async@1.1.1, semver@4.3.6, bin-version-check@2.1.0, twig@0.8.2)
└── inquirer@0.8.5 (ansi-regex@1.1.1, cli-width@1.0.1, through@2.3.8, readline2@0.1.1, rx@2.5.3)
ubuntu@ip:~$ yo jhipster
module.js:338
throw err;
^
Error: Cannot find module 'yeoman-environment'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/index.js:6:19)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)

**Comment by deepu105** [comment]
This is definitely a environment or setup issue and doesnt have anything to do with jhipster, can you try installing the angular-generator and see if it works

**Comment by pulkitnandan** [comment]
Yes it was done without errors.

**Comment by pulkitnandan** [comment]
I have reached somewhere to the end of jhipster installation after re-installing node using 

echo 'export PATH=$HOME/local/bin:$PATH' >> ~/.bashrc
. ~/.bashrc
mkdir ~/local
mkdir ~/node-latest-install
cd ~/node-latest-install
curl http://nodejs.org/dist/node-latest.tar.gz | tar xz --strip-components=1
./configure --prefix=~/local
make install
curl -L https://npmjs.org/install.sh | sh
node -v

then changed permission's using chmod g+rwx /root /root/.npm/*
 whichever file gives error as I'm logged in as root. But now this gives this new error.

identical src/main/webapp/assets/images/hipster2x.png
identical src/main/webapp/index.html
identical .editorconfig
identical .jshintrc
npm ERR! Linux 3.19.0-21-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.5
npm ERR! path /root/.npm/generator-jhipster/2.19.0/package/package.json.ceef5f158fa8c8540f0ea42382d5897c
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, open '/root/.npm/generator-jhipster/2.19.0/package/package.json.ceef5f158fa8c8540f0ea42382d5897c'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, open '/root/.npm/generator-jhipster/2.19.0/package/package.json.ceef5f158fa8c8540f0ea42382d5897c']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/root/.npm/generator-jhipster/2.19.0/package/package.json.ceef5f158fa8c8540f0ea42382d5897c',
npm ERR!   parent: 'nogpo' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/spend-analytics-dashboard/npm-debug.log
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
bower angular-ui-router#0.2.15  EACCES EACCES, open '/root/.cache/bower/registry/bower.herokuapp.com/lookup/angular-ui-router_8d538'

Stack trace:
Error: EACCES, open '/root/.cache/bower/registry/bower.herokuapp.com/lookup/angular-ui-router_8d538'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.12.7
OS: Linux 3.19.0-21-generic x64


Now I'll try creating a new user and reinstall node.

**Comment by pulkitnandan** [comment]
After creating a user and adding it to sudo group reinstalled node, bower, grunt-cli, yo, jhipster and then yo jhipster stuck for 30 minutes in 1 MBPS connection @

   create src/main/webapp/scripts/app/account/settings/settings.controller.js
   create src/main/webapp/scripts/app/admin/admin.js
   create src/main/webapp/scripts/app/admin/audits/audits.html
   create src/main/webapp/scripts/app/admin/audits/audits.js
   create src/main/webapp/scripts/app/admin/audits/audits.controller.js
   create src/main/webapp/scripts/app/admin/configuration/configuration.html
   create src/main/webapp/scripts/app/admin/configuration/configuration.js
   create src/main/webapp/scripts/app/admin/configuration/configuration.controller.js
   create src/main/webapp/scripts/app/admin/docs/docs.html
   create src/main/webapp/scripts/app/admin/docs/docs.js
   create src/main/webapp/scripts/app/admin/health/health.html
   create src/main/webapp/scripts/app/admin/health/health.modal.html
   create src/main/webapp/scripts/app/admin/health/health.js
   create src/main/webapp/scripts/app/admin/health/health.controller.js
   create src/main/webapp/scripts/app/admin/health/health.modal.controller.js
   create src/main/webapp/scripts/app/admin/logs/logs.html
   create src/main/webapp/scripts/app/admin/logs/logs.js
   create src/main/webapp/scripts/app/admin/logs/logs.controller.js
   create src/main/webapp/scripts/app/admin/metrics/metrics.html
   create src/main/webapp/scripts/app/admin/metrics/metrics.modal.html
   create src/main/webapp/scripts/app/admin/metrics/metrics.js
   create src/main/webapp/scripts/app/admin/metrics/metrics.controller.js
   create src/main/webapp/scripts/app/admin/metrics/metrics.modal.controller.js
   create src/main/webapp/scripts/app/error/error.html
   create src/main/webapp/scripts/app/error/accessdenied.html
   create src/main/webapp/scripts/app/entities/entity.js
   create src/main/webapp/scripts/app/error/error.js
   create src/main/webapp/scripts/app/main/main.html
   create src/main/webapp/scripts/app/main/main.js
   create src/main/webapp/scripts/app/main/main.controller.js
   create src/main/webapp/scripts/components/interceptor/auth.interceptor.js
   create src/main/webapp/scripts/components/interceptor/errorhandler.interceptor.js
   create src/main/webapp/scripts/components/interceptor/notification.interceptor.js
   create src/main/webapp/scripts/components/alert/alert.service.js
   create src/main/webapp/scripts/components/alert/alert.directive.js
   create src/test/javascript/karma.conf.js
   create src/test/javascript/spec/app/account/health/health.controller.spec.js
   create src/test/javascript/spec/app/account/login/login.controller.spec.js
   create src/test/javascript/spec/app/account/password/password.controller.spec.js
   create src/test/javascript/spec/app/account/password/password.directive.spec.js
   create src/test/javascript/spec/app/account/settings/settings.controller.spec.js
   create src/test/javascript/spec/components/auth/auth.services.spec.js
   create src/main/webapp/assets/styles/documentation.css
   create src/main/webapp/assets/images/development_ribbon.png
   create src/main/webapp/assets/images/hipster.png
   create src/main/webapp/assets/images/hipster2x.png
   create src/main/webapp/index.html
   create .editorconfig
   create .jshintrc

> spawn-sync@1.0.13 postinstall /home/algoscale/jhipster/node_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

npm WARN optional dep failed, continuing fsevents@0.3.8

> gifsicle@3.0.1 postinstall /home/algoscale/jhipster/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js


/


Then after stopping yo jhipster I ran it again where it still showing error in

bower angular-cookies extra-resolution Unnecessary resolution: angular-cookies#1.4.3
Loading "browser-sync.js" tasks...ERROR
>> Error: ENOENT, no such file or directory '/home/algoscale/jhipster/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/browser-sync-ui/static/content/help.content.html'
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module './lib/parse-js'


Clean install of nodejs from nvm, source, or thorugh apt-get doesn't let jhipster installed and run right out of box , tested atleast on two different ubuntu machines hosting on amazon ec2.

**Comment by pulkitnandan** [comment]
After installing thorugh 

git clone https://github.com/joyent/node.git
cd node
git checkout v0.12.7 #Try checking nodejs.org for what the stable version is
./configure && make && sudo make install

It's the same as installing with nvm.

**Comment by gmarziou** [comment]
It's not a JHipster issue, it's a failure during `npm install`, the fact that angular generator works does not prove anything as it doesn't use same node packages.

You tried 2 ways to install node: apt-get which requires sudo and nvm which does not require sudo, I would recommend you stick with nvm.

Make sure you cleaned up everything related to node: ~/.nvm, /tmp, local node_modules and npm cache.
Make your user owns these directories.
