### ISSUE TITLE
Security risk: User's password is shown in the logs

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1893]
User's passwords are displayed when logging:

[DEBUG] org.jhipster.health.web.rest.UserResource - REST request to get all Users
Hibernate: select user0_.id as id1_4_, user0_.created_by as created_2_4_, user0_.created_date as created_3_4_, user0_.last_modified_by as last_mod4_4_, user0_.last_modified_date as last_mod5_4_, user0_.activated as activate6_4_, user0_.activation_key as activati7_4_, user0_.email as email8_4_, user0_.first_name as first_na9_4_, user0_.lang_key as lang_ke10_4_, user0_.last_name as last_na11_4_, user0_.login as login12_4_, user0_.password as passwor13_4_, user0_.preferences_id as prefere16_4_, user0_.reset_date as reset_d14_4_, user0_.reset_key as reset_k15_4_ from JHI_USER user0_
[DEBUG] org.jhipster.health.aop.logging.LoggingAspect - Exit: org.jhipster.health.web.rest.UserResource.getAll() with result = [User{login='system', password='$2a$10$mE.qmcV0mFU5NcKh73TZx.z4ueI/.bDWbj0T1BYyqP481kGGarKLG', firstName='System', lastName='System', email='system@localhost', activated='true', langKey='en', activationKey='null'}, User{login='anonymousUser', password='$2a$10$j8S5d7Sr7.8VTOYNviDPOeWX8KcYILUVJBsYV83Y5NtECayypx9lO', firstName='Anonymous', lastName='User', email='anonymous@localhost', activated='true', langKey='en', activationKey='null'}, User{login='admin', password='$2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC', firstName='Administrator', lastName='Administrator', email='admin@localhost', activated='true', langKey='en', activationKey='null'}, User{login='user', password='$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K', firstName='User', lastName='User', email='user@localhost', activated='true', langKey='en', activationKey='null'}]

It's generally recommended by Security folks that you don't print passwords in log files, even if they are encrypted.

**Comment by jdubois** [comment]
Correct!
I merged your PR.
