### ISSUE TITLE
Update Angular Core to 13.3.11

### ISSUE THREAD

**Issue by paris0120** [jhipster/generator-jhipster#18944]
##### **Overview of the feature request**
Update Angular Core to 13.3.11

I did it in the following way but now sure if there is any bugs.
Set g-bootstrap the latest version
"@ng-bootstrap/ng-bootstrap": "12.1.2",
delete package_lock.json
npm i
ng update @angular/core@"13.3.11" --allow-dirty --force

Got some errors and warnings during the process but the frontend runs fine after the update. Don't have a thorough test yet. 

Can someone confirm that this is a right way to update the core?

##### **Motivation for or Use Case**

13.3.11 is the last version of angular 13. Many angular 13 libraries have dependency version conflicts with the current core. Update to 13.3.11 enable the user to use many libraries for the development. 

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
The only 'supported' way to update libraries is to execute `jhipster upgrade` when a new version of the platform is released.
Updating packages and dependencies by yourself is at your own risk (the community has no test for it)
