### ISSUE TITLE
Page access security issue

### ISSUE THREAD

**Issue by kevintvh** [jhipster/generator-jhipster#1897]
Hi Everyone,

Anyone got any issues related to URL access permissions ? We could define roles in pageabc.js#".state" and these roles are only apply when we logged in but anonymous does not work and anonymous could also access to the URL.

For example: http://localhost:8080/#/top_secret need to be accessed by "ROLE_ADMIN" but this URL could be accessed by anonymous user at the moment (Spring security permission checking works fine in the back end, just the web access authority does not work).

How could we fix this issue? or role base access defined in "$stateProvider" does not work properly?

I had a workaround:
 * Add `<div has-any-role="ROLE_ADMIN">` to the page
 * And authority.directive.js
```javascript
               setHidden = function () {
                        element.addClass('hidden');
                        $state.go('login');  //redirect to login page
                    }
```

so that anonymous user will get blank page or redirect to login page, but it should have other better solutions.

Please give me your ideas. Thanks.

**Comment by jdubois** [comment]
Have a look at the "Authorizations" part at http://jhipster.github.io/using_angularjs.html that should answer your question!

**Comment by kevintvh** [comment]
@jdubois: Yes, I know this note but it does not work as expected. As describing above for anyone to reproduce this issue.

You can easily have a quick test:
1. src/main/webapp/scripts/app/admin/configuration/configuration.js
roles: ['ROLE_ADMIN'],
2. Access http://localhost:8080/#/configuration without logging in.
3. What do you see ?

I think it should redirect user to login page. Please give me your ideas :)

Thanks,
Kevin.

**Comment by jdubois** [comment]
@kevintvh I'm sorry but I just tested and I am correctly redirected to the login page... Have you tried it on the sampe app?

**Comment by kevintvh** [comment]
@jdubois: Thank you for your prompt response :)

I tested in latest versions of Opera, Chrome and Firefox. And the redirect to login page happens randomly and some cases don't redirect.

You can go to /configuration a few times or close and open browser and manually type /configuration context again if it does redirect in the first hit.

**Comment by gmarziou** [comment]
@kevintvh, in your answer you did not say about whether you reproduced with the sample app.

It could be a problem of asynchronism, you should try to reproduce with the browser console open, maybe you 'll see the order of requests it different between success and failure.

**Comment by kevintvh** [comment]
@gmarziou: I just run sample app (https://github.com/jhipster/jhipster-sample-app-oauth2) and it works fine in all browsers. I'm not sure if it is an issue in old jhipster version (2.17).

I always open console to debug but there was no error.
OAuth2 scheme is used and jhipster-generator version is 2.17

.yo-rc.json
```
{
  "generator-jhipster": {
    "baseName": "myApp",
    "packageName": "com.myapp",
    "packageFolder": "com/myapp",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useCompass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "2fab812a8b5e3279dcbf264d32bbe647a7caaa05"
  }
}
```

Thank you.
