### ISSUE TITLE
Making API more RESTful

### ISSUE THREAD

**Issue by afedulov** [jhipster/generator-jhipster#1899]
I have noticed that some endpoints in the project do not quite match widely accepted practices of building RESTful APIs. For instance, AuditResource contains two URL mappings:
``` /audits/all ``` and ```/audits/byDates``` . It seems to me, that both of them are redundant. GET request to /audits/ without parameters completely defines the semantics of /all. GET request to /audits/ with start and end date passed as parameters completely describes the semantics of /audits/byDates. Spring REST can handle dispatching to those methods based on the methods signatures, so that we could just move the audits mapping to the class level making it ```@RequestMapping("/api/audits")``` instead of ``` @RequestMapping("/api")``` and remove both ```@RequestMapping(value = "/audits/byDates")``` and ```@RequestMapping(value = "/audits/all")```. RequestMapping of the former "byDates" method has to contain an additional parameter: ```params =  {"fromDate","toDate"} ```

**Comment by gmarziou** [comment]
Feel free to propose a PR.

**Comment by andidev** [comment]
This sounds like a good idea. Would make a lot more sense to me.

**Comment by jdubois** [comment]
Yes this is an API that was coded very early in the project, it can definitely be challenged. Regarding #1882 are you using this API @afedulov ? Do you find it useful? I'm thinking of removing it, or at least disabling it by default

**Comment by afedulov** [comment]
@jdubois I definitely consider this part of JHipster useful, but probably not for an obvious reason. When I just started with the project it has provided a great way to see how a very typical task of presenting data based on date range filtering can be achieved using this technology stack. I think that it is another way to look at this module. The power of JHipster is it ability to show developers how to quickly bootstrap their own functionality based on the technology stack they are not 100% familiar with. Audits, in my opinion, contribute to this purpose very nicely.

I have created a pull request containing the changes discussed in the current ticket: https://github.com/jhipster/generator-jhipster/pull/1906

PS: on the unrelated matter - any feedback on https://github.com/jhipster/generator-jhipster/issues/1878 ? Should I change something in the description? Should we maybe ask people with IntelliJ 14 to check how the workaround works for them?

**Comment by andidev** [comment]
To be consistent, we should also make the same changes to the entity REST API.

**Comment by afedulov** [comment]
@andidev do you mean those being generated? They are actually quite OK in their current form, I think. We could move MediaType.APPLICATION_JSON_VALUE to the top of the class and also mapping to /api/foo instead of having /foo on every method. Or do you have something else in mind?

**Comment by andidev** [comment]
Sorry I thought we used foo/all for entities. My bad forget my comment.
