### ISSUE TITLE
add browser-sync plugin for css reload

### ISSUE THREAD

**Issue by Avricot** [jhipster/generator-jhipster#19]
Have you any feedback about brwoser-sync ? 
Looks very nice, it's supposed to inject style changes without page-reload.
https://github.com/shakyShane/grunt-browser-sync

I'll give it a try and let you know

**Comment by jdubois** [comment]
I just add a look at this and I'm reopening the ticket:

- Works like our current "grunt serve" task
- But it syncs scrolling, forms, etc.... Incredible tool!!! Looks much more advanced than what we currently have
