### ISSUE TITLE
One of the buildSpecification methods doesn't allow to build like queries

### ISSUE THREAD

**Issue by Ielay** [jhipster/generator-jhipster#19004]
## Overview

For some reason one of the overloaded version of **buildSpecification** doesn't allow you to build like queries:

```
protected <X> Specification<ENTITY> buildSpecification(Filter<X> filter, Function<Root<ENTITY>, Expression<X>> metaclassFunction)
```

as there are no `if (filter.getContains() != null)` check in method body as it is in some versions of the method:

```
    protected <X> Specification<ENTITY> buildSpecification(Filter<X> filter, Function<Root<ENTITY>, Expression<X>> metaclassFunction) {
        if (filter.getEquals() != null) {
            return equalsSpecification(metaclassFunction, filter.getEquals());
        } else if (filter.getIn() != null) {
            return valueIn(metaclassFunction, filter.getIn());
        } else if (filter.getNotIn() != null) {
            return valueNotIn(metaclassFunction, filter.getNotIn());
        } else if (filter.getNotEquals() != null) {
            return notEqualsSpecification(metaclassFunction, filter.getNotEquals());
        } else if (filter.getSpecified() != null) {
            return byFieldSpecified(metaclassFunction, filter.getSpecified());
        }
        return null;
    }
```

The method is called from 
```
protected <OTHER, X> Specification<ENTITY> buildReferringEntitySpecification(Filter<X> filter,
                                                                                 SingularAttribute<? super ENTITY, OTHER> reference,
                                                                                 SingularAttribute<? super OTHER, X> valueField)
``` 
                                                                                 
and we want to use it to build like query of a field that is taken from another table (relationship ManyToOne). As this one doesn't allow building like query, we forced to use our custom impl.

**Comment by gzsombor** [comment]
The reason for the difference, is that the Filter<X> doesn't have getContains() method - only StringFilter has that attribute, that's why it is missing from the buildSpecification(Filter<X>, Function<...>), you need to call the [buildSpecification(StringFilter, Function)](https://github.com/jhipster/jhipster-bom/blob/f926afbebd066ec7c989de1623f290eac67c9d9d/jhipster-framework/src/main/java/tech/jhipster/service/QueryService.java#L105)
