### ISSUE TITLE
AuditEventConverter marked as @Configuration

### ISSUE THREAD

**Issue by afedulov** [jhipster/generator-jhipster#1901]
Just want to clarify. Is there a reason for the AuditEventConverter to be marked as @Configuration? Would it not be better to just convert its methods to static instead of injecting it?

**Comment by gmarziou** [comment]
Not sure why it is  @Configuration, I would rather annotate it as @Service or @Component, static methods are evil for testing.

**Comment by afedulov** [comment]
Agreed. I did not see the last method which contains some custom details for mapping WebAuthenticationDetails. I might imagine a situation where it could be beneficial to override these details for testing. However if not for that last method, I would say that static methods would have been just fine here. They are not the source of absolute evil, just have to be used judiciously. Anyhow, the singleton it remains than.

**Comment by gmarziou** [comment]
Could you test if it works with @Service?

**Comment by afedulov** [comment]
I can test, and I am almost sure it will, the only problem with changing it is the location of the class. It is currently located in the config/audit/ package. Which emphasizes that it was considered as a kinda-sorta configuration detail by the author. If we change it to @Service than it should probably also be relocated into service package. My proposition is to mark it @Component and move it into service/util because IMHO it is really just a small utility class used in the service layer.

**Comment by gmarziou** [comment]
Yes I agree. @jdubois as the author of this class, what do you think?

**Comment by jdubois** [comment]
I think I coded this at the very beginning of the project, and I don't remember why this isn't a Spring Bean!

**Comment by afedulov** [comment]
Do we have a decision on this one? Should I go on with my proposition?  (~~@Configuration~~ -> @Component ;   ~~config/audit/~~ -> services/util)

**Comment by jdubois** [comment]
As this class is used in a Repository, it can't be located in the service package -> that would make a circular dependencies in the packages.
As it's more a configuration class, this is why it was put in the config package. Perhaps we can find a better package, but it shouldn't be in the service layer anyway.
