### ISSUE TITLE
Search repositories generated for all entities

### ISSUE THREAD

**Issue by Rapster** [jhipster/generator-jhipster#19023]
##### **Overview of the issue**

Following up https://github.com/jhipster/generator-jhipster/issues/17142 for a monolith application. 

##### **Motivation for or Use Case**

Generate search repositories only for entities that has been declared as searchable. So far, from the moment you declare one entity searchable, everything gets searchable

##### **Reproduce the error**

See JDL

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/17142

##### **JHipster Version(s)**

7.8.1

##### **JHipster configuration**

  <details>
  <summary>.yo-rc.json</summary>
  <pre>
    {
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "bug_jhipster_json_properties",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1655567508706,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": ["A", "B", "C", "D"],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "jwtSecretKey": "YjA2MDBmNzNlN2JjZmFkOTk5NmVlYzRjMGI3YmNlMzlmZTMwYTRhNTJhN2VjZjg1YTZhMmVlY2ExZDU1NjgwY2UzMDI4YzllOThjNThjZWY0YTc0YTZiYzczNzZiNWE2MGYzZWU4MGYwY2IyNjM4YzM2YzlmOGIxODg0ZTk0Zjg=",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1655568046000,
    "messageBroker": false,
    "nativeLanguage": "fr",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": "elasticsearch",
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": false
  }
}
  </pre>
  </details>

<details>
  <summary>JDL definitions</summary>
  <pre>
entity A {

}

entity B {

}

entity C {

}

entity D {

}

relationship ManyToOne {
    A{b} to B
    B{c} to C
}

search A with elasticsearch
</pre>
</details>

##### **Browsers and Operating System**

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Rapster** [comment]
Pinging @ko5tik if you're still interested in that issue

**Comment by mshima** [comment]
At monoliths and probably microfrontends, search is opt-out `@SearchEngine(false)`.
This behavior is more new comers friendly.

**Comment by ko5tik** [comment]
If it is desired I can port this to other parts.

**Comment by mshima** [comment]
IMO we should stay will current behavior.

**Comment by Rapster** [comment]
Any reason you have in mind?

**Comment by Rapster** [comment]
I don't mind that by default if search engine is set. Other options like dto, service etc. works the very same way I think

**Comment by mshima** [comment]
We should start v8 cycle soon, so it’s time to discuss.
What’s your proposal?

**Comment by Rapster** [comment]
Similar to https://github.com/jhipster/generator-jhipster/issues/17142?

**Comment by Rapster** [comment]
To clarify, proposal:
- If search set but no entities specified then generate for all entities
- If search set and entities specified, only generate for specified entities

**Comment by ko5tik** [comment]
Have no use case at the moment -  current  project does not
involve jhipster.   But everything is implemented and  in pull request -
which will of
 course need. rebasing.    My idea was. that entities shall be omitted if
indexing is specified to "no".  and be indexed bz default

========[] Lines game back in Appstore - check it out! []===============
https://play.google.com/store/apps/details?id=de.pribluda.games.android.lines

Blog:  https://www.pribluda.de
