### ISSUE TITLE
api access rejected

### ISSUE THREAD

**Issue by adkhaila** [jhipster/generator-jhipster#1904]
Hello Julien,

for token based authentication , user admin is directly rejected when clicked 
menu : Administration > API. It works fine for other menus. 

We are adopting jhipster in our company for a new project , it's for an admin console so it would be a good start

I have an issue with thsi webapp when imported into eclipse and run by spring boot : 
when i clic , i get :+1: 401 : {"timestamp":1440089488358,"status":401,"error":"Unauthorized","message":"Access Denied","path":"/v2/api-docs"} http://127.0.0.1:8080/v2/api-docs

and in the logs : 
[DEBUG] com.mycompany.myapp.security.Http401UnauthorizedEntryPoint - Pre-authenticated entry point called. Rejecting access

**Comment by gmarziou** [comment]
Wait for next release 2.20, it contains fixes for the swagger-ui part.
