### ISSUE TITLE
Unable to see home page of bookstore

### ISSUE THREAD

**Issue by i4irshad** [jhipster/generator-jhipster#1905]
Hi,

I tried running bookstore application by following the steps mentioned in your website
After running Application.java or mvn spring-boot:run I am unable to see the entire content of home page
It only shows "This is your footer"
Can you please suggest where I am going wrong

Thanks,
Irshad

**Comment by jdubois** [comment]
You probably didn't install NPM correctly, have a look at your log messages.

**Comment by i4irshad** [comment]
even after updating npm (2.14.0) there is no success

**Comment by honsali** [comment]
I encountered the same pb when I used the http://127.0.0.1 url
try with http://localhost:8080

**Comment by i4irshad** [comment]
tried both the ways but neither of them worked :(
where can I get to see the logs and debug it

**Comment by gmarziou** [comment]
Just run `npm install` in your jhipster project directory and copy/paste the errors here.
You could also collect more informations by running rff-doctor:

   npm install -g rff-doctor
   rff-doctor

**Comment by deepu105** [comment]
Also check if wiredep has injected all bower items in index.html else run
grunt/gulp build

**Comment by i4irshad** [comment]
@gmarziou 
Tried running the npm install -g rff-doctor from jhipster project directory. Below is the output

Irshads-MacBook-Pro:jhipster Irshad$ npm install -g rff-doctor
/usr/local/bin/rff-doctor -> /usr/local/lib/node_modules/rff-doctor/bin/rff-doctor
rff-doctor@0.2.3 /usr/local/lib/node_modules/rff-doctor
├── figures@1.3.5
├── q@1.4.1
├── semver@4.3.6
├── lodash@3.10.1
├── which@1.1.1 (is-absolute@0.1.7)
└── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)

@deepu105 
I tried running the grunt build from jhipster project directory. It says "Cannot find where you keep your Bower packages" then I used the --force and here is the output

Irshads-MacBook-Pro:jhipster Irshad$ grunt build --force
Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "wiredep:app" (wiredep) task
Warning: Error: Cannot find where you keep your Bower packages. Used --force, continuing.

Running "ngconstant:prod" (ngconstant) task
Creating module bookstoreApp at .tmp/scripts/app/app.constants.js...OK

Running "useminPrepare:html" (useminPrepare) task
Configuration changed for concat, uglify, cssmin, autoprefixer

Running "ngtemplates:dist" (ngtemplates) task
File .tmp/templates/templates.js created.
Added .tmp/templates/templates.js to 

Running "imagemin:dist" (imagemin) task
Minified 0 images (saved 0 B)

Running "svgmin:dist" (svgmin) task
Total saved: 0 B

Running "concat:generated" (concat) task
File .tmp/concat/scripts/vendor.js created.
File .tmp/concat/scripts/app.js created.

Running "copy:fonts" (copy) task


Running "copy:dist" (copy) task
Copied 26 files

Running "ngAnnotate:dist" (ngAnnotate) task
>> 2 files successfully generated.

Running "cssmin:generated" (cssmin) task
>> Destination not written because minified CSS was empty.

Running "autoprefixer:generated" (autoprefixer) task
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
File src/main/webapp/dist/assets/styles/main.css created.

Running "uglify:generated" (uglify) task
>> 2 files created.

Running "rev:dist" (rev) task
src/main/webapp/dist/scripts/app.js >> 6ae1d7c7.app.js
src/main/webapp/dist/scripts/vendor.js >> d41d8cd9.vendor.js
src/main/webapp/dist/assets/styles/main.css >> 89f168a9.main.css
src/main/webapp/dist/assets/images/development_ribbon.png >> 129d6be2.development_ribbon.png
src/main/webapp/dist/assets/images/hipster.png >> 1d45bca0.hipster.png
src/main/webapp/dist/assets/images/hipster2x.png >> dca92e17.hipster2x.png

Running "usemin:html" (usemin) task
Replaced 23 references to assets

Running "usemin:css" (usemin) task
Replaced 1 reference to assets

Running "usemin:js" (usemin) task
Replaced 2 references to assets

Running "htmlmin:dist" (htmlmin) task
Minified 1 files

Done, but with warnings.


Execution Time (2015-08-22 08:21:36 UTC)
loading tasks            56ms  ▇▇▇▇ 3%
wiredep:app             117ms  ▇▇▇▇▇▇▇ 7%
ngconstant:prod          19ms  ▇▇ 1%
useminPrepare:html      159ms  ▇▇▇▇▇▇▇▇▇▇ 10%
ngtemplates:dist         69ms  ▇▇▇▇ 4%
svgmin:dist              62ms  ▇▇▇▇ 4%
concat:generated         49ms  ▇▇▇ 3%
copy:dist                48ms  ▇▇▇ 3%
ngAnnotate:dist         162ms  ▇▇▇▇▇▇▇▇▇▇ 10%
cssmin:generated         53ms  ▇▇▇▇ 3%
autoprefixer:generated   64ms  ▇▇▇▇ 4%
uglify:generated        656ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 40%
usemin:html              64ms  ▇▇▇▇ 4%
Total 1.6s

**Comment by i4irshad** [comment]
bower install did the trick :)
Able to see the home page...
Thank you all :+1:
