### ISSUE TITLE
Enchancement: Add track by id to all ng-repeat directives

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1907]
@jdubois @gmarziou @andidev @gzsombor @atomfrede  Do you think it would be good to add a default track by `entity.id` on all `ng-repeat` It should improve performance of DOM as per angular docs

https://docs.angularjs.org/api/ng/directive/ngRepeat
http://www.codelord.net/2014/04/15/improving-ng-repeat-performance-with-track-by/

**Comment by jdubois** [comment]
Looks good to me!

On Fri, Aug 21, 2015 at 3:58 PM, Deepu k Sasidharan <
notifications@github.com> wrote:

> @jdubois <https://github.com/jdubois> @gmarziou
> <https://github.com/gmarziou> @andidev <https://github.com/andidev>
> @gzsombor <https://github.com/gzsombor> @atomfrede
> <https://github.com/atomfrede> Do you think it would be good to add a
> default track by entity.id on all ng-repeat It should improve performance
> of DOM as per angular docs
>
> https://docs.angularjs.org/api/ng/directive/ngRepeat
>
> http://www.codelord.net/2014/04/15/improving-ng-repeat-performance-with-track-by/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1907>.
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by deepu105** [comment]
Ok ill add this after next release

**Comment by gmarziou** [comment]
Yes it's a good idea.

**Comment by deepu105** [comment]
Need to work on this but after next week
