### ISSUE TITLE
Angular tooling documentation

### ISSUE THREAD

**Issue by syafiqit** [jhipster/generator-jhipster#19070]
Angular Augury already archived, so can you suggest other alternatives for it or update the document for future reference.

**Comment by dwarakaprasad** [comment]
Based on this [1507](https://github.com/rangle/augury/issues/1507), you could use [Angular Dev Tools](https://angular.io/guide/devtools).

**Comment by DanielFran** [comment]
Closed via https://github.com/jhipster/jhipster.github.io/pull/1216
