### ISSUE TITLE
jhipster.github.io - docker-compose up is failing

### ISSUE THREAD

**Issue by dwarakaprasad** [jhipster/generator-jhipster#19072]
Followed the docker & docker compose development work flow found in the [README.md](https://github.com/jhipster/jhipster.github.io/blob/main/README.md) file.

I am on Ubuntu 20.04.4 LTS running Docker version 19.03.13, build 4484c46d9d &  docker-compose version 1.27.4, build 40524192

running docker-compose up in the root folder of the cloned project throws the following exception. Looks like there is some permission issue in the latest jekyll/jekyll:latest image

jhipster.github.io git:(main) docker-compose up
Recreating jhipster.github.io ... done
Attaching to jhipster.github.io
jhipster.github.io | Bundler 2.3.15 is running, but your lockfile was generated with 2.1.4. Installing Bundler 2.1.4 and restarting using that version.
jhipster.github.io | `/home/jekyll` is not writable.
jhipster.github.io | Bundler will use `/tmp/bundler20220701-28-if8s0e28' as your home directory temporarily.
jhipster.github.io | Fetching gem metadata from https://rubygems.org/.
jhipster.github.io | Fetching bundler 2.1.4
jhipster.github.io | Installing bundler 2.1.4
jhipster.github.io | There was an error installing the locked bundler version (2.1.4), rerun with the `--verbose` flag for more details. Going on using bundler 2.3.15.
jhipster.github.io | Fetching gem metadata from https://rubygems.org/.........
jhipster.github.io | Using concurrent-ruby 1.1.10
jhipster.github.io | Fetching minitest 5.16.1
jhipster.github.io | Using thread_safe 0.3.6
jhipster.github.io | Fetching zeitwerk 2.6.0
jhipster.github.io | Installing zeitwerk 2.6.0
jhipster.github.io | Using public_suffix 4.0.7
jhipster.github.io | Using bundler 2.3.15
jhipster.github.io | Fetching coffee-script-source 1.11.1
jhipster.github.io | Installing minitest 5.16.1
jhipster.github.io | Using execjs 2.8.1
jhipster.github.io | Using colorator 1.1.0
jhipster.github.io | Using commonmarker 0.23.5
jhipster.github.io | Fetching unf_ext 0.0.8.2
jhipster.github.io | Installing coffee-script-source 1.11.1
jhipster.github.io | Using eventmachine 1.2.7
jhipster.github.io | Using http_parser.rb 0.8.0
jhipster.github.io | Using ffi 1.15.5
jhipster.github.io | Fetching faraday-net_http 2.0.3
jhipster.github.io | Installing faraday-net_http 2.0.3
jhipster.github.io | Using ruby2_keywords 0.0.5
jhipster.github.io | Using forwardable-extended 2.6.0
jhipster.github.io | Using gemoji 3.0.1
jhipster.github.io | Using rb-fsevent 0.11.1
jhipster.github.io | Using rexml 3.2.5
jhipster.github.io | Using liquid 4.0.3
jhipster.github.io | Using mercenary 0.3.6
jhipster.github.io | Fetching rouge 3.26.0
jhipster.github.io | Installing unf_ext 0.0.8.2 with native extensions
jhipster.github.io | Using safe_yaml 1.0.5
jhipster.github.io | Fetching mini_portile2 2.8.0
jhipster.github.io | Installing rouge 3.26.0
jhipster.github.io | Using racc 1.6.0
jhipster.github.io | Using jekyll-paginate 1.1.0
jhipster.github.io | Fetching rubyzip 2.3.2
jhipster.github.io | Installing mini_portile2 2.8.0
jhipster.github.io | Fetching jekyll-swiss 1.0.0
jhipster.github.io | Installing jekyll-swiss 1.0.0
jhipster.github.io | Using unicode-display_width 1.8.0
jhipster.github.io | Fetching webrick 1.7.0
jhipster.github.io | Installing rubyzip 2.3.2
jhipster.github.io | Using i18n 0.9.5
jhipster.github.io | Using tzinfo 1.2.9
jhipster.github.io | Installing webrick 1.7.0
jhipster.github.io | --- ERROR REPORT TEMPLATE -------------------------------------------------------
jhipster.github.io | 
jhipster.github.io | ```
jhipster.github.io | Gem::FilePermissionError: You don't have write permissions for the /usr/gem directory.
jhipster.github.io |   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/installer.rb:720:in `verify_gem_home'
jhipster.github.io |   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/installer.rb:910:in `pre_install_checks'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/rubygems_gem_installer.rb:64:in `pre_install_checks'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/rubygems_gem_installer.rb:12:in `install'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/source/rubygems.rb:204:in `install'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:54:in `install'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/worker.rb:62:in `apply_func'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/worker.rb:57:in `block in process_queue'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/worker.rb:54:in `loop'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/worker.rb:54:in `process_queue'
jhipster.github.io |   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
jhipster.github.io | 
jhipster.github.io | ```
jhipster.github.io | 
jhipster.github.io | ## Environment
jhipster.github.io | 
jhipster.github.io | ```
jhipster.github.io | Bundler       2.3.15
jhipster.github.io |   Platforms   ruby, x86_64-linux-musl
jhipster.github.io | Ruby          3.1.1p18 (2022-02-18 revision 53f5fc4236a754ddf94b20dbb70ab63bd5109b18) [x86_64-linux-musl]
jhipster.github.io |   Full Path   /usr/local/bin/ruby
jhipster.github.io |   Config Dir  /usr/local/etc
jhipster.github.io | RubyGems      3.3.15
jhipster.github.io |   Gem Home    /usr/gem
jhipster.github.io |   Gem Path    /home/jekyll/.local/share/gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/gem
jhipster.github.io |   User Home   /home/jekyll
jhipster.github.io |   User Path   /home/jekyll/.local/share/gem/ruby/3.1.0
jhipster.github.io |   Bin Dir     /usr/gem/bin
jhipster.github.io | OpenSSL       
jhipster.github.io |   Compiled    OpenSSL 1.1.1n  15 Mar 2022
jhipster.github.io |   Loaded      OpenSSL 1.1.1n  15 Mar 2022
jhipster.github.io |   Cert File   /etc/ssl1.1/cert.pem
jhipster.github.io |   Cert Dir    /etc/ssl1.1/certs
jhipster.github.io | Tools         
jhipster.github.io |   Git         not installed
jhipster.github.io |   RVM         not installed
jhipster.github.io |   rbenv       not installed
jhipster.github.io |   chruby      not installed
jhipster.github.io | ```
jhipster.github.io | 
jhipster.github.io | ## Bundler Build Metadata
jhipster.github.io | 
jhipster.github.io | ```
jhipster.github.io | Built At          2022-06-01
jhipster.github.io | Git SHA           e7e41afd92
jhipster.github.io | Released Version  true
jhipster.github.io | ```
jhipster.github.io | 
jhipster.github.io | ## Bundler settings
jhipster.github.io | 
jhipster.github.io | ```
jhipster.github.io | app_config
jhipster.github.io |   Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
jhipster.github.io | bin
jhipster.github.io |   Set via BUNDLE_BIN: "/usr/local/bundle/bin"
jhipster.github.io | build.nokogiri
jhipster.github.io |   Set for your local app (/usr/local/bundle/config): "--use-system-libraries"
jhipster.github.io | disable_platform_warnings
jhipster.github.io |   Set via BUNDLE_DISABLE_PLATFORM_WARNINGS: "true"
jhipster.github.io | disable_version_check
jhipster.github.io |   Set for your local app (/usr/local/bundle/config): true
jhipster.github.io | home
jhipster.github.io |   Set via BUNDLE_HOME: "/usr/local/bundle"
jhipster.github.io | ignore_messages
jhipster.github.io |   Set for your local app (/usr/local/bundle/config): true
jhipster.github.io | jobs
jhipster.github.io |   Set for your local app (/usr/local/bundle/config): 2
jhipster.github.io | silence_root_warning
jhipster.github.io |   Set via BUNDLE_SILENCE_ROOT_WARNING: true
jhipster.github.io | ```
jhipster.github.io | 
jhipster.github.io | ## Gemfile
jhipster.github.io | 
jhipster.github.io | ### Gemfile
jhipster.github.io | 
jhipster.github.io | ```ruby
jhipster.github.io | source 'https://rubygems.org'
jhipster.github.io | gem 'github-pages'
jhipster.github.io | gem 'jekyll-redirect-from'
jhipster.github.io | 
jhipster.github.io | gem "webrick", "~> 1.7"
jhipster.github.io | ```
jhipster.github.io | 
jhipster.github.io | ### Gemfile.lock
jhipster.github.io | 
jhipster.github.io | ```
jhipster.github.io | GEM
jhipster.github.io |   remote: https://rubygems.org/
jhipster.github.io |   specs:
jhipster.github.io |     activesupport (6.0.5)
jhipster.github.io |       concurrent-ruby (~> 1.0, >= 1.0.2)
jhipster.github.io |       i18n (>= 0.7, < 2)
jhipster.github.io |       minitest (~> 5.1)
jhipster.github.io |       tzinfo (~> 1.1)
jhipster.github.io |       zeitwerk (~> 2.2, >= 2.2.2)
jhipster.github.io |     addressable (2.8.0)
jhipster.github.io |       public_suffix (>= 2.0.2, < 5.0)
jhipster.github.io |     coffee-script (2.4.1)
jhipster.github.io |       coffee-script-source
jhipster.github.io |       execjs
jhipster.github.io |     coffee-script-source (1.11.1)
jhipster.github.io |     colorator (1.1.0)
jhipster.github.io |     commonmarker (0.23.5)
jhipster.github.io |     concurrent-ruby (1.1.10)
jhipster.github.io |     dnsruby (1.61.9)
jhipster.github.io |       simpleidn (~> 0.1)
jhipster.github.io |     em-websocket (0.5.3)
jhipster.github.io |       eventmachine (>= 0.12.9)
jhipster.github.io |       http_parser.rb (~> 0)
jhipster.github.io |     ethon (0.15.0)
jhipster.github.io |       ffi (>= 1.15.0)
jhipster.github.io |     eventmachine (1.2.7)
jhipster.github.io |     execjs (2.8.1)
jhipster.github.io |     faraday (2.3.0)
jhipster.github.io |       faraday-net_http (~> 2.0)
jhipster.github.io |       ruby2_keywords (>= 0.0.4)
jhipster.github.io |     faraday-net_http (2.0.3)
jhipster.github.io |     ffi (1.15.5)
jhipster.github.io |     forwardable-extended (2.6.0)
jhipster.github.io |     gemoji (3.0.1)
jhipster.github.io |     github-pages (226)
jhipster.github.io |       github-pages-health-check (= 1.17.9)
jhipster.github.io |       jekyll (= 3.9.2)
jhipster.github.io |       jekyll-avatar (= 0.7.0)
jhipster.github.io |       jekyll-coffeescript (= 1.1.1)
jhipster.github.io |       jekyll-commonmark-ghpages (= 0.2.0)
jhipster.github.io |       jekyll-default-layout (= 0.1.4)
jhipster.github.io |       jekyll-feed (= 0.15.1)
jhipster.github.io |       jekyll-gist (= 1.5.0)
jhipster.github.io |       jekyll-github-metadata (= 2.13.0)
jhipster.github.io |       jekyll-include-cache (= 0.2.1)
jhipster.github.io |       jekyll-mentions (= 1.6.0)
jhipster.github.io |       jekyll-optional-front-matter (= 0.3.2)
jhipster.github.io |       jekyll-paginate (= 1.1.0)
jhipster.github.io |       jekyll-readme-index (= 0.3.0)
jhipster.github.io |       jekyll-redirect-from (= 0.16.0)
jhipster.github.io |       jekyll-relative-links (= 0.6.1)
jhipster.github.io |       jekyll-remote-theme (= 0.4.3)
jhipster.github.io |       jekyll-sass-converter (= 1.5.2)
jhipster.github.io |       jekyll-seo-tag (= 2.8.0)
jhipster.github.io |       jekyll-sitemap (= 1.4.0)
jhipster.github.io |       jekyll-swiss (= 1.0.0)
jhipster.github.io |       jekyll-theme-architect (= 0.2.0)
jhipster.github.io |       jekyll-theme-cayman (= 0.2.0)
jhipster.github.io |       jekyll-theme-dinky (= 0.2.0)
jhipster.github.io |       jekyll-theme-hacker (= 0.2.0)
jhipster.github.io |       jekyll-theme-leap-day (= 0.2.0)
jhipster.github.io |       jekyll-theme-merlot (= 0.2.0)
jhipster.github.io |       jekyll-theme-midnight (= 0.2.0)
jhipster.github.io |       jekyll-theme-minimal (= 0.2.0)
jhipster.github.io |       jekyll-theme-modernist (= 0.2.0)
jhipster.github.io |       jekyll-theme-primer (= 0.6.0)
jhipster.github.io |       jekyll-theme-slate (= 0.2.0)
jhipster.github.io |       jekyll-theme-tactile (= 0.2.0)
jhipster.github.io |       jekyll-theme-time-machine (= 0.2.0)
jhipster.github.io |       jekyll-titles-from-headings (= 0.5.3)
jhipster.github.io |       jemoji (= 0.12.0)
jhipster.github.io |       kramdown (= 2.3.2)
jhipster.github.io |       kramdown-parser-gfm (= 1.1.0)
jhipster.github.io |       liquid (= 4.0.3)
jhipster.github.io |       mercenary (~> 0.3)
jhipster.github.io |       minima (= 2.5.1)
jhipster.github.io |       nokogiri (>= 1.13.4, < 2.0)
jhipster.github.io |       rouge (= 3.26.0)
jhipster.github.io |       terminal-table (~> 1.4)
jhipster.github.io |     github-pages-health-check (1.17.9)
jhipster.github.io |       addressable (~> 2.3)
jhipster.github.io |       dnsruby (~> 1.60)
jhipster.github.io |       octokit (~> 4.0)
jhipster.github.io |       public_suffix (>= 3.0, < 5.0)
jhipster.github.io |       typhoeus (~> 1.3)
jhipster.github.io |     html-pipeline (2.14.2)
jhipster.github.io |       activesupport (>= 2)
jhipster.github.io |       nokogiri (>= 1.4)
jhipster.github.io |     http_parser.rb (0.8.0)
jhipster.github.io |     i18n (0.9.5)
jhipster.github.io |       concurrent-ruby (~> 1.0)
jhipster.github.io |     jekyll (3.9.2)
jhipster.github.io |       addressable (~> 2.4)
jhipster.github.io |       colorator (~> 1.0)
jhipster.github.io |       em-websocket (~> 0.5)
jhipster.github.io |       i18n (~> 0.7)
jhipster.github.io |       jekyll-sass-converter (~> 1.0)
jhipster.github.io |       jekyll-watch (~> 2.0)
jhipster.github.io |       kramdown (>= 1.17, < 3)
jhipster.github.io |       liquid (~> 4.0)
jhipster.github.io |       mercenary (~> 0.3.3)
jhipster.github.io |       pathutil (~> 0.9)
jhipster.github.io |       rouge (>= 1.7, < 4)
jhipster.github.io |       safe_yaml (~> 1.0)
jhipster.github.io |     jekyll-avatar (0.7.0)
jhipster.github.io |       jekyll (>= 3.0, < 5.0)
jhipster.github.io |     jekyll-coffeescript (1.1.1)
jhipster.github.io |       coffee-script (~> 2.2)
jhipster.github.io |       coffee-script-source (~> 1.11.1)
jhipster.github.io |     jekyll-commonmark (1.4.0)
jhipster.github.io |       commonmarker (~> 0.22)
jhipster.github.io |     jekyll-commonmark-ghpages (0.2.0)
jhipster.github.io |       commonmarker (~> 0.23.4)
jhipster.github.io |       jekyll (~> 3.9.0)
jhipster.github.io |       jekyll-commonmark (~> 1.4.0)
jhipster.github.io |       rouge (>= 2.0, < 4.0)
jhipster.github.io |     jekyll-default-layout (0.1.4)
jhipster.github.io |       jekyll (~> 3.0)
jhipster.github.io |     jekyll-feed (0.15.1)
jhipster.github.io |       jekyll (>= 3.7, < 5.0)
jhipster.github.io |     jekyll-gist (1.5.0)
jhipster.github.io |       octokit (~> 4.2)
jhipster.github.io |     jekyll-github-metadata (2.13.0)
jhipster.github.io |       jekyll (>= 3.4, < 5.0)
jhipster.github.io |       octokit (~> 4.0, != 4.4.0)
jhipster.github.io |     jekyll-include-cache (0.2.1)
jhipster.github.io |       jekyll (>= 3.7, < 5.0)
jhipster.github.io |     jekyll-mentions (1.6.0)
jhipster.github.io |       html-pipeline (~> 2.3)
jhipster.github.io |       jekyll (>= 3.7, < 5.0)
jhipster.github.io |     jekyll-optional-front-matter (0.3.2)
jhipster.github.io |       jekyll (>= 3.0, < 5.0)
jhipster.github.io |     jekyll-paginate (1.1.0)
jhipster.github.io |     jekyll-readme-index (0.3.0)
jhipster.github.io |       jekyll (>= 3.0, < 5.0)
jhipster.github.io |     jekyll-redirect-from (0.16.0)
jhipster.github.io |       jekyll (>= 3.3, < 5.0)
jhipster.github.io |     jekyll-relative-links (0.6.1)
jhipster.github.io |       jekyll (>= 3.3, < 5.0)
jhipster.github.io |     jekyll-remote-theme (0.4.3)
jhipster.github.io |       addressable (~> 2.0)
jhipster.github.io |       jekyll (>= 3.5, < 5.0)
jhipster.github.io |       jekyll-sass-converter (>= 1.0, <= 3.0.0, != 2.0.0)
jhipster.github.io |       rubyzip (>= 1.3.0, < 3.0)
jhipster.github.io |     jekyll-sass-converter (1.5.2)
jhipster.github.io |       sass (~> 3.4)
jhipster.github.io |     jekyll-seo-tag (2.8.0)
jhipster.github.io |       jekyll (>= 3.8, < 5.0)
jhipster.github.io |     jekyll-sitemap (1.4.0)
jhipster.github.io |       jekyll (>= 3.7, < 5.0)
jhipster.github.io |     jekyll-swiss (1.0.0)
jhipster.github.io |     jekyll-theme-architect (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-cayman (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-dinky (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-hacker (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-leap-day (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-merlot (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-midnight (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-minimal (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-modernist (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-primer (0.6.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-github-metadata (~> 2.9)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-slate (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-tactile (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-theme-time-machine (0.2.0)
jhipster.github.io |       jekyll (> 3.5, < 5.0)
jhipster.github.io |       jekyll-seo-tag (~> 2.0)
jhipster.github.io |     jekyll-titles-from-headings (0.5.3)
jhipster.github.io |       jekyll (>= 3.3, < 5.0)
jhipster.github.io |     jekyll-watch (2.2.1)
jhipster.github.io |       listen (~> 3.0)
jhipster.github.io |     jemoji (0.12.0)
jhipster.github.io |       gemoji (~> 3.0)
jhipster.github.io |       html-pipeline (~> 2.2)
jhipster.github.io |       jekyll (>= 3.0, < 5.0)
jhipster.github.io |     kramdown (2.3.2)
jhipster.github.io |       rexml
jhipster.github.io |     kramdown-parser-gfm (1.1.0)
jhipster.github.io |       kramdown (~> 2.0)
jhipster.github.io |     liquid (4.0.3)
jhipster.github.io |     listen (3.7.1)
jhipster.github.io |       rb-fsevent (~> 0.10, >= 0.10.3)
jhipster.github.io |       rb-inotify (~> 0.9, >= 0.9.10)
jhipster.github.io |     mercenary (0.3.6)
jhipster.github.io |     mini_portile2 (2.8.0)
jhipster.github.io |     minima (2.5.1)
jhipster.github.io |       jekyll (>= 3.5, < 5.0)
jhipster.github.io |       jekyll-feed (~> 0.9)
jhipster.github.io |       jekyll-seo-tag (~> 2.1)
jhipster.github.io |     minitest (5.16.1)
jhipster.github.io |     nokogiri (1.13.6)
jhipster.github.io |       mini_portile2 (~> 2.8.0)
jhipster.github.io |       racc (~> 1.4)
jhipster.github.io |     octokit (4.25.0)
jhipster.github.io |       faraday (>= 1, < 3)
jhipster.github.io |       sawyer (~> 0.9)
jhipster.github.io |     pathutil (0.16.2)
jhipster.github.io |       forwardable-extended (~> 2.6)
jhipster.github.io |     public_suffix (4.0.7)
jhipster.github.io |     racc (1.6.0)
jhipster.github.io |     rb-fsevent (0.11.1)
jhipster.github.io |     rb-inotify (0.10.1)
jhipster.github.io |       ffi (~> 1.0)
jhipster.github.io |     rexml (3.2.5)
jhipster.github.io |     rouge (3.26.0)
jhipster.github.io |     ruby2_keywords (0.0.5)
jhipster.github.io |     rubyzip (2.3.2)
jhipster.github.io |     safe_yaml (1.0.5)
jhipster.github.io |     sass (3.7.4)
jhipster.github.io |       sass-listen (~> 4.0.0)
jhipster.github.io |     sass-listen (4.0.0)
jhipster.github.io |       rb-fsevent (~> 0.9, >= 0.9.4)
jhipster.github.io |       rb-inotify (~> 0.9, >= 0.9.7)
jhipster.github.io |     sawyer (0.9.2)
jhipster.github.io |       addressable (>= 2.3.5)
jhipster.github.io |       faraday (>= 0.17.3, < 3)
jhipster.github.io |     simpleidn (0.2.1)
jhipster.github.io |       unf (~> 0.1.4)
jhipster.github.io |     terminal-table (1.8.0)
jhipster.github.io |       unicode-display_width (~> 1.1, >= 1.1.1)
jhipster.github.io |     thread_safe (0.3.6)
jhipster.github.io |     typhoeus (1.4.0)
jhipster.github.io |       ethon (>= 0.9.0)
jhipster.github.io |     tzinfo (1.2.9)
jhipster.github.io |       thread_safe (~> 0.1)
jhipster.github.io |     unf (0.1.4)
jhipster.github.io |       unf_ext
jhipster.github.io |     unf_ext (0.0.8.2)
jhipster.github.io |     unicode-display_width (1.8.0)
jhipster.github.io |     webrick (1.7.0)
jhipster.github.io |     zeitwerk (2.6.0)
jhipster.github.io | 
jhipster.github.io | PLATFORMS
jhipster.github.io |   ruby
jhipster.github.io | 
jhipster.github.io | DEPENDENCIES
jhipster.github.io |   github-pages
jhipster.github.io |   jekyll-redirect-from
jhipster.github.io |   webrick (~> 1.7)
jhipster.github.io | 
jhipster.github.io | BUNDLED WITH
jhipster.github.io |    2.1.4
jhipster.github.io | ```
jhipster.github.io | 
jhipster.github.io | --- TEMPLATE END ----------------------------------------------------------------
jhipster.github.io | 
jhipster.github.io | Unfortunately, an unexpected error occurred, and Bundler cannot continue.
jhipster.github.io | 
jhipster.github.io | First, try this link to see if there are any existing issue reports for this error:
jhipster.github.io | https://github.com/rubygems/rubygems/search?q=You+don%27t+have+write+permissions+for+the+%2Fusr%2Fgem+directory.&type=Issues
jhipster.github.io | 
jhipster.github.io | If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
jhipster.github.io exited with code 1

**Comment by DanielFran** [comment]
Closed by https://github.com/jhipster/jhipster.github.io/pull/1217
