### ISSUE TITLE
Problem creating docker image of jhipster project

### ISSUE THREAD

**Issue by FrancescoMez79** [jhipster/generator-jhipster#19071]
Dear Support,
we are trying to create a local docker image of our application, looking the Jhipster documentation:
https://www.jhipster.tech/docker-compose/

In detail, we are sending this command :
./mvnw -Pprod package verify jib:dockerBuild --offline

and we are receiving the error :
 Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.5.1:dockerBuild (default-cli) on project simpletmt-multitenancy: Cannot run Jib in offline mode; adoptopenjdk:11-jre-hotspot not found in local Jib cache -> [Help 1]

We have already installed the version of adoptopenjdk:11-jre-hotspot with this command:
sudo apt-get install adoptopenjdk-11-hotspot-jre

"
eminds@eminds-VirtualBox:~/jhipster/simpletmtapp/simpletmtapp$ sudo apt-get install adoptopenjdk-11-hotspot-jre
[sudo] password di eminds: 
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
adoptopenjdk-11-hotspot-jre è già alla versione più recente (11.0.11+9-3).
Il seguente pacchetto è stato installato automaticamente e non è più richiesto:
  libllvm9
Usare "sudo apt autoremove" per rimuoverlo.
0 aggiornati, 0 installati, 0 da rimuovere e 47 non aggiornati.
"

sending the command : 
./mvnw -Pprod package verify jib:dockerBuild --offline

we receive the error:
"
..
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M3:verify (verify) @ simpletmt-multitenancy ---
[INFO] 
[INFO] --- jib-maven-plugin:1.5.1:dockerBuild (default-cli) @ simpletmt-multitenancy ---
[WARNING] Setting image creation time to current time; your image may not be reproducible.
[INFO] 
[INFO] Containerizing application to Docker daemon as simpletmtmultitenancy...
[INFO] Executing tasks:
[INFO] [                              ] 0,0% complete
[INFO] > building dependencies layer
[INFO] > building resources layer
[INFO] > building classes layer
[INFO] > building extra files layer
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:25 min
[INFO] Finished at: 2022-06-30T15:13:01+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.5.1:dockerBuild (default-cli) on project simpletmt-multitenancy: Cannot run Jib in offline mode; adoptopenjdk:11-jre-hotspot not found in local Jib cache -> [Help 1]
[ERROR] 
[jhipsterLog.txt](https://github.com/jhipster/generator-jhipster/files/9029836/jhipsterLog.txt)
"

We have attached the final end of log of this command.

Can you please help us to understand what means exactly : 
"Cannot run Jib in offline mode; adoptopenjdk:11-jre-hotspot not found in local Jib cache "

and how can we solve this problem?

Thanks,
Francesco

**Comment by dwarakaprasad** [comment]
Can you please provide the below information as expected in the issue template,

**Comment by mshima** [comment]
> Cannot run Jib in offline mode; adoptopenjdk:11-jre-hotspot not found in local Jib cache -> [Help 1]

The problem is explained here.

**Comment by mshima** [comment]
Remove `--offline` from the command

**Comment by FrancescoMez79** [comment]
Hello,
if we remove --offline from command, we have another problem:
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.5.1:dockerBuild (default-cli) on project simpletmt-multitenancy: 429 Too Many Requests
[ERROR] {
[ERROR]   "errors": [
[ERROR]     {
[ERROR]       "code": "TOOMANYREQUESTS",
[ERROR]       "message": "You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
[ERROR]     }
[ERROR]   ]

How can we solve this problem?

We have tried to login in docker by "docker login" command, but after this, re-sending the build command :
./mvnw package -Pprod verify jib:dockerBuild

We receive the same error of rate limit of docker.

for this cause, we have added --offline in the command.

**Comment by FrancescoMez79** [comment]
This is the result of jhipster info command : 
"eminds@eminds-VirtualBox:~/jhipster/simpletmtapp/simpletmtapp$ jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
simpletmt-multitenancy@0.0.1-SNAPSHOT /home/eminds/jhipster/simpletmtapp/simpletmtapp
├── generator-jhipster@6.3.1 
└─┬ generator-jhipster-multitenancy@2.1.2
  └── generator-jhipster@6.3.1  deduped

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster-multitenancy": {
    "promptValues": {
      "packageName": "it.eminds"
    },
    "tenantChangelogDate": "20220619044740",
    "jhipsterVersion": "6.3.1",
    "applicationType": "monolith",
    "baseName": "simpletmtMultitenancy",
    "packageName": "it.eminds",
    "packageFolder": "it/eminds",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "tenantName": "Company",
    "tenantAwareEntities": [
      "Region",
      "FamilyTag",
      "Tag",
      "Label",
      "Translation",
      "Itinerary",
      "Step",
      "Location"
    ]
  },
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "monolith",
    "baseName": "simpletmtMultitenancy",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-multitenancy",
        "version": "2.1.2"
      }
    ],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "it",
    "languages": [
      "it",
      "en"
    ],
    "blueprints": [
      {
        "name": "generator-jhipster-multitenancy",
        "version": "2.1.2"
      }
    ]
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Company
entity Region {
  regionName String
}
entity FamilyTag {
  textId String required,
  description String required,
  position Integer required,
  enabled Boolean required
}
entity Tag {
  textId String required,
  description String required,
  position Integer required,
  enabled Boolean required,
  image ImageBlob required
}
entity Label {
  textId String required
}
entity Translation {
  textId String required,
  language Language,
  translate String
}
entity Itinerary {
  textId String required,
  duration Integer required,
  minPrice BigDecimal required,
  imageBadge ImageBlob required,
  imageMain ImageBlob required,
  idTmt Integer required
}
entity Step {
  textId String required,
  duration Integer required,
  order Integer required
}
entity Location {
  textId String required,
  image ImageBlob,
  latitude Double required,
  longitude Double required
}
enum Language {
  IT,
  EN,
  FR,
  ES
}

relationship OneToOne {
  FamilyTag{label} to Label,
  Tag{label} to Label,
  Itinerary{label} to Label,
  Itinerary{destination} to Label,
  Itinerary{description} to Label,
  Step{description} to Label,
  Step{location} to Location,
  Location{label} to Label
}
relationship OneToMany {
  FamilyTag{tag} to Tag{familyTag},
  Label{tag} to Translation{label},
  Itinerary{itinerary} to Step{itinerary}
}
relationship ManyToMany {
  Itinerary{tag} to Tag{itinerary}
}

paginate Company with pagination
service Company with serviceClass
service FamilyTag with serviceImpl

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v12.20.0

npm: 6.14.8

yeoman: 3.1.0

yarn: 1.22.10

Docker version 20.10.10, build b485636

docker-compose version 1.22.0, build f46880fe

INFO! Congratulations, JHipster execution is complete!
eminds@eminds-VirtualBox:~/jhipster/simpletmtapp/simpletmtapp$ 
"
