### ISSUE TITLE
Entity links to the User entity do not work

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1909]
@andidev I'm assigning this to you because I know you coded this part.

For me we can't release version 2.20.0 until this is solved -> @andidev please tell me if you have the time to work on it, so I know if I have to correct this myself

Just do a many-to-one relationship to the User entity, you will have a JavaScript error when clicking on the user entity. This is because it hasn't been generated for the User entity, which is a specific entity.

On the sample app you can test it by creating a new BankAccount, linking it to a user, and then clicking on the user.

**Comment by andidev** [comment]
I'll have a look at it tonight

fre 21 aug 2015 16:38 Julien Dubois <notifications@github.com> skrev:

**Comment by andidev** [comment]
So I am working on this right now. One question, is many-to-many relationships supported to the User entity?

**Comment by jdubois** [comment]
It should be supported on the non-owning side, but I haven't checked this for a long time!

**Comment by andidev** [comment]
Okey so I'll fix the issue there as well

**Comment by andidev** [comment]
fix ready just need some testing, working on that

**Comment by andidev** [comment]
tested for dto mapstruct and dto no option with one-to-one, many-to-one and many-to-many relationship.

so you can merge this

**Comment by jdubois** [comment]
Great, you even do more tests than me!

**Comment by jhenaoz** [comment]
really nice fix guys, congrats!
