### ISSUE TITLE
Add Spring Data Rest

### ISSUE THREAD

**Issue by cthiebault** [jhipster/generator-jhipster#191]
JHipster should use [Spring Data Rest](http://projects.spring.io/spring-data-rest) instead of "manually" generate REST controller. 

It would also offer HATEOAS support brought by [spring-hateoas](http://projects.spring.io/spring-hateoas).

**Comment by sahaliatarek** [comment]
I don't know guys why you are talking about complicated CRUD operations like you can't perform it with spring Data Rest, you can just override any operation by adding a RestCotroller to whatever end point you need. The big advantage of Spring Data Rest is hateoas.
that should be perfect if JHispter can include Spring Data Rest

**Comment by deepu105** [comment]
Please don't comment on very old tickets, if you have a feature request open a new issue with details on why you think its a good idea and how it fits current architecture
