### ISSUE TITLE
Keycloak as Microservice

### ISSUE THREAD

**Issue by paris0120** [jhipster/generator-jhipster#19103]
##### **Overview of the feature request**

Integrate Keycloak as a microservice. Example: https://github.com/paris0120/keycloak-server

##### **Motivation for or Use Case**
The keycloak can be behind the gateway. It is easier to convert a website to https and users can log in from the gateway server without jumping between different servers. 

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I think this could be a good idea if someone contributes and maintains it. Otherwise, it's likely to become a maintenance burden and will hurt the project more than it will help.
