### ISSUE TITLE
No Solution Stack named '64bit Amazon Linux 2015.03 v1.4.1 running Tomcat 8 Java 8' found.

### ISSUE THREAD

**Issue by rblazquez** [jhipster/generator-jhipster#1910]
Im trying to deploy jHipster in AWS and have this output:

```
Create S3 bucket
Bucket preveges created successful

Upload WAR to S3
War uploaded successful

Create database
Database created successful

Waiting for database (This may take several minutes)
Database available at jdbc:mysql://preveges.co5e9kgwtldd.eu-central-1.rds.amazonaws.com:3306/preveges

Create/Update application
✖ No Solution Stack named '64bit Amazon Linux 2015.03 v1.4.1 running Tomcat 8 Java 8' found.
```

Im not sure why it tries to load this stack version since ive used Java 7 in the generator.

Can you give me some clues on how to fix this?

**Comment by deepu105** [comment]
Fixed already will be in next release please search existing issues before opening new

**Comment by rblazquez** [comment]
True, sorry.

Looking at
https://github.com/jhipster/generator-jhipster/issues/1875

**Comment by deepu105** [comment]
Fyi, this due to a recent change done in EBS by AWS

**Comment by rblazquez** [comment]
Ive tried the solution you posted at #1875 and was not able to make it works. However it is easy to complete the beanstalk configuration manually and it works.

Even when at the moment it does not does all the work, it saves time and effort.
