### ISSUE TITLE
Problem creating docker image of jhipster project (Issue 19071)

### ISSUE THREAD

**Issue by FrancescoMez79** [jhipster/generator-jhipster#19104]
Dear Support,
you have closed the old ticket 19071, but we have not solved our problem.

 We have added the log when we remove the --offline from command :
./mvnw -Pprod package verify jib:dockerBuild --offline

Can you please help us to solve this problem?

Thanks,
Francesco

**Comment by FrancescoMez79** [comment]
We re-write the last comments:

"Hello,
if we remove --offline from command, we have another problem:
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.5.1:dockerBuild (default-cli) on project simpletmt-multitenancy: 429 Too Many Requests
[ERROR] {
[ERROR] "errors": [
[ERROR] {
[ERROR] "code": "TOOMANYREQUESTS",
[ERROR] "message": "You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
[ERROR] }
[ERROR] ]

How can we solve this problem?

We have tried to login in docker by "docker login" command, but after this, re-sending the build command :
./mvnw package -Pprod verify jib:dockerBuild

We receive the same error of rate limit of docker.

for this cause, we have added --offline in the command."

**Comment by FrancescoMez79** [comment]
Last comment : 

"This is the result of jhipster info command :
"eminds@eminds-VirtualBox:~/jhipster/simpletmtapp/simpletmtapp$ jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

JHipster Version(s)
simpletmt-multitenancy@0.0.1-SNAPSHOT /home/eminds/jhipster/simpletmtapp/simpletmtapp
├── generator-jhipster@6.3.1 
└─┬ generator-jhipster-multitenancy@2.1.2
  └── generator-jhipster@6.3.1  deduped

JHipster configuration, a .yo-rc.json file generated in the root folder
.yo-rc.json file
JDL for the Entity configuration(s) entityName.json files generated in the .jhipster directory
JDL entity definitions
Environment and Tools
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v12.20.0

npm: 6.14.8

yeoman: 3.1.0

yarn: 1.22.10

Docker version 20.10.10, build b485636

docker-compose version 1.22.0, build f46880fe

INFO! Congratulations, JHipster execution is complete!
eminds@eminds-VirtualBox:~/jhipster/simpletmtapp/simpletmtapp$
"

**Comment by atomfrede** [comment]
Maybe you need to tell jib what authentication to use too? Did you have a look at https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#authentication-methods ?

**Comment by FrancescoMez79** [comment]
We have tried to setting authentication using Maven setting.

We have changed the settings.xml in .m2 dir of Ubuntu, setting this :
<server>
        <id>registry.hub.docker.com</id>
        <username>fmezzina</username>
        <password>xxxxx</password>
    </server>

but we have the same error removing --offline from command.

What I wrong? What do we set in "id" field? I have setted my credentials of Docker.

Thanks,
Francesco

**Comment by DanielFran** [comment]
@FrancescoMez79 since this is not a jhispter bug, it is better to open a ticket in stackoverflow
