### ISSUE TITLE
`CachingHttpHeadersFilter` uses milliseconds to set Cache Control header

### ISSUE THREAD

**Issue by ge65cer** [jhipster/generator-jhipster#19102]
##### **Overview of the issue**

The [CachingHttpHeadersFilter](https://github.com/jhipster/jhipster-bom/blob/main/jhipster-framework/src/main/java/tech/jhipster/web/filter/CachingHttpHeadersFilter.java) in [jhipster-bom](https://github.com/jhipster/jhipster-bom) erroneously uses milliseconds instead of seconds when calculating the `cacheTimeToLive` from the `timeToLiveInDays` configuration value and later setting the `Cache-Control: max-age=x, public` HTTP header.

##### **Motivation for or Use Case**

This is wrong, as per definition the `max-age=` header uses seconds, not milliseconds.
https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Cache-Control

##### **Reproduce the error**

Add the `tech.jhipster.web.filter.CachingHttpHeadersFilter` to your `WebConfigurer`, e.g., like so:
```
FilterRegistration.Dynamic cachingHttpHeadersFilter = server.addFilter("cachingHttpHeadersFilter", new CachingHttpHeadersFilter(jHipsterProperties));
EnumSet<DispatcherType> dispatcherTypes = EnumSet.of(DispatcherType.REQUEST, DispatcherType.FORWARD, DispatcherType.ASYNC);
cachingHttpHeadersFilter.addMappingForUrlPatterns(dispatcherTypes, true, "/*");
cachingHttpHeadersFilter.setAsyncSupported(true);
```
Set your configuration to `http.cache.timeToLiveInDays: 1461` (default) and observe that the cache control header is `cache-control: max-age=126230400000, public` (should be `126230400`).

##### **Suggest a Fix**

Replace all occurrences of `TimeUnit.DAYS.toMillis()` with `TimeUnit.DAYS.toSeconds()` in the file.
Be careful that the `Expires` header on the other hand uses milliseconds to calculate a date in the future.

##### **JHipster Version(s)**

7.8.1

##### **Browsers and Operating System**

All browsers, as it is a server-side issue.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
This indeed looks like a bug. We also use     

`public static final long DEFAULT_SECONDS_TO_LIVE = TimeUnit.DAYS.toMillis(DEFAULT_DAYS_TO_LIVE);`

which looks wrong from the naming.

**Comment by ge65cer** [comment]
@atomfrede You are correct. If you want to reach out, our contact details are over at https://artemis.ase.in.tum.de/about.
