### ISSUE TITLE
Drop deprecated or unmaintained generators.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#19112]
##### **Overview of the feature request**

To be dropped
- [x] add
- [ ] ~init~ used by generate-blueprint
- [x] upgrade-config https://github.com/jhipster/generator-jhipster/pull/19655/commits/ab46e40d7013e68a1d82d3578d62a7c29f5b466e

Consider to drop:
- [x] aws https://github.com/jhipster/generator-jhipster/pull/23422/commits/5c200749827e4bbbd2fe1bfdf5ed7cd9b66e5a89
- [x] azure-app-service https://github.com/jhipster/generator-jhipster/pull/23422/commits/de808c4009b77ac1d2d9b1b2b95c423c2e9d6f5a
- [x] azure-spring-cloud https://github.com/jhipster/generator-jhipster/pull/23422/commits/186e83e1bc8788ce58fc468eb887ccb15e1e3417
- [x] cloudfoundry https://github.com/jhipster/generator-jhipster/pull/23422/commits/a410d285a950961ceaf6c16b05afa0e5a4392adc
- [x] gae https://github.com/jhipster/generator-jhipster/pull/23422/commits/0ef016d1414837cdbcd274d12b74643f3ac0f0a8
- [x] openshift https://github.com/jhipster/generator-jhipster/pull/23422/commits/6003f9901add16a6d061d9a2399a4490e62b4ed2
- [x] openapi-client https://github.com/jhipster/generator-jhipster/pull/23632/commits/144846eb59e0eaf8b11b59807480471f271ec21a
- [ ] ~heroku~

Consider to implement as a command or option:
- [ ] ~info~
- [ ] ~export-jdl~
- [x] page https://github.com/jhipster/generator-jhipster/pull/23615/commits/96e783bc7147e2d9bfa43dfcd1ee0fb2e57cecdd
- [x] spring-controller https://github.com/jhipster/generator-jhipster/pull/23502/commits/ea3a08a408de33783be05bee52a7f73fbac0a3b7
- [x] spring-service https://github.com/jhipster/generator-jhipster/pull/23502/commits/ea3a08a408de33783be05bee52a7f73fbac0a3b7

##### **Motivation for or Use Case**

Improve maintainability and developer experience

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
+1 to drop all unmaintained generators, especially the cloud ones

**Comment by mshima** [comment]
@mraible should we keep heroku?

**Comment by mshima** [comment]
What about openapi-client?

**Comment by deepu105** [comment]
I have never used the open api client one so no comments. Do anyone think there is value un keeping it around?

**Comment by mraible** [comment]
I'm +1 for Heroku, but I'm also biased because I use it in jhipster-book.org.

**Comment by deepu105** [comment]
@mshima this issue is complete right?

**Comment by mshima** [comment]
Yes

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/173568

**Comment by DanielFran** [comment]
@mshima approved
