### ISSUE TITLE
Integrate entities generators into each feature specific generator.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#19111]
##### **Overview of the feature request**

Implement RFC https://github.com/jhipster/generator-jhipster/blob/main/rfcs/4-jhipster-rfc-entity-as-core.md.

- [x] entities
- [x] entities-client
- [x] entity
- [x] entity-client
- [x] entity-i18n
- [x] entity-server

##### **Motivation for or Use Case**

Improve developer experience.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Just a remark on the syntax: most of the methods are using the 'Each' keyword to tell that this method to specify that it will impact the whole entity pool. The only exception being 'writingEntities' which uses plural. Could it be possible to align (e.g. using 'Each' or plural everywhere)?

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/120305

**Comment by DanielFran** [comment]
@mshima approved

**Comment by mshima** [comment]
@DanielFran that was quick, thanks. 😄
