### ISSUE TITLE
Enhancement of the username/password implementation

### ISSUE THREAD

**Issue by giraone** [jhipster/generator-jhipster#19124]
##### **Overview of the feature request**

I am using JHipster with the "standard" username/password authentication in a project. This project lately had a security penetration test. There were two findings related to the JHipster implemetation:

1. Unverified password change
  - CVSS 3.1 score of [8.8](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H)
  - *When setting a new password for a user, the product does not require knowledge of the original password or use of any other form of authentication.*
2. Weak password policies
  - CVSS 3.1 score of [7.5](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N)
  - *The product does not require users to have strong passwords, making it easier for attackers to compromise user accounts.*

The CVSS assessment might be debatable, the findings itself not. They are easily changeable and more or less "state of art".

I fixed the issues in my project:
1. By adding a third password input ("old password") besides "new password" and "confirm password" on two frontend screens (change and reset of password) and by adapting the backend classes (mostly AccountResource, UserService) and some resources.
2. By integrating the [Passay Password Validation Library](https://www.passay.org/) into the UserService class.

I can extract the changes and try to provide a pull request. Especially finding 2 has little impact and is more or less configurable, because *passay* itself is configurable. Finding 1 is a bit different, because it affects all frontend technologies and the APIs. This is sth. you should discuss first.

##### **Motivation for or Use Case**

Make JHipster more secure :-). And for myself: reduce problems, when I upgrade the project.

##### **Related issues or PR**

I found no related issue.

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Thanks for the heads up. Are you sure to add the "old password" to password reset? I mean the idea is you don't know the old password and need to reset. For changing my own password (when logged in) I need to enter my old password (at least I am not aware we have changed that).

Regarding integrating the password library, I am a bit reluctant as I am pretty sure everyone would like to have a different policy.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/203401/178357082-4f4d211d-4b91-4d57-aae0-0cdd77fc7df2.png">

**Comment by giraone** [comment]
Sorry, of course no for the reset. The policy checker had to be added for both screens - at least the server response must be evaluated also in the reset screen.

Concerning the password lib: here is a peace of code, that I am using:

```
{
        final MessageResolver resolverDe = getResolver("i18n/passwordpolicies_de.properties");
        final MessageResolver resolverEn = getResolver("i18n/passwordpolicies_en.properties");

        this.passwordValidatorDe = new PasswordValidator(resolverDe,
            new LengthRule(8, 50),
            new UsernameRule(true, true), // match reverse also, match case-insensitive
            dictionaryRule(),
            new IllegalSequenceRule(GermanSequenceData.Alphabetical, 4, false),
            new IllegalSequenceRule(EnglishSequenceData.Numerical, 4, false),
            new IllegalSequenceRule(GermanSequenceData.GermanQwertz, 4, false),
            new RepeatCharacterRegexRule(3),
            new CharacterRule(GermanCharacterData.LowerCase, 1),
            new CharacterRule(GermanCharacterData.UpperCase, 1),
            new CharacterRule(EnglishCharacterData.Digit, 1),
            new CharacterRule(EnglishCharacterData.Special, 1)
        );

        this.passwordValidatorEn = new PasswordValidator(resolverEn,
            new LengthRule(8, 50),
            new UsernameRule(true, true), // match reverse also, match case-insensitive
            dictionaryRule(),
            new IllegalSequenceRule(EnglishSequenceData.Alphabetical, 4, false),
            new IllegalSequenceRule(EnglishSequenceData.Numerical, 4, false),
            new IllegalSequenceRule(EnglishSequenceData.USQwerty, 4, false),
            new RepeatCharacterRegexRule(3),
            new CharacterRule(EnglishCharacterData.LowerCase, 1),
            new CharacterRule(EnglishCharacterData.UpperCase, 1),
            new CharacterRule(EnglishCharacterData.Digit, 1),
            new CharacterRule(EnglishCharacterData.Special, 1)
        );
    }
```

I would suggest to provide only an interface for the setup and a simple and sane default implementation: e.g. only for english passwords, probably no dictionary or only a small one, no check of password re-use. Everything else can be adapted for each project, including the i18n resource bundle as in my example above.

The default [error messages](https://github.com/vt-middleware/passay/blob/master/src/main/resources/passay.properties) itself use the settings from the rules, so they are in good shape for adaption.

**Comment by atomfrede** [comment]
I would say we might have this as tips section or a small blueprint. Pretty sure a lot of users do want to force us a password policy on them. Maybe we can have such a configuration for the production profile only so during local development and testing one can use a simple password when creating users (as well as in units/integration tests).

**Comment by atomfrede** [comment]
From my point of view this feature is not complex to integrate so I am a bit reluctant to add this to the generator. For me this might go into tip and tricks section or a blogpost, wdyt @jhipster/developers ?

**Comment by gmarziou** [comment]
I like this passay lib, the rules seem easy to configure.

- I looked at the error messages, how to support i18n?
- dependencies, I'm concerned about guava (always a source of problems) and bouncy castle (any version conflicts?)
- When a password is rejected, what is the status code returned by the lib to the client?

**Comment by atomfrede** [comment]
For i18n there seems to be a SpringMessageResolver https://github.com/vt-middleware/passay/blob/master/src/main/java/org/passay/spring/SpringMessageResolver.java

**Comment by giraone** [comment]
Related to the question on the status code for the client: for my implementation, I had been using 200 with a simple response body consisting of
- a boolean "accepted" attribute (true,false)
- and a string "notAcceptedMessage" attribute containing the language specific message, why password was not accepted.
It is no (http) error - it is a semantic issue based on a policy.

**Comment by gmarziou** [comment]
Why not returning an HTTP 400 error status? 
This would sound more RESTful to me, I guess this is is what Keycloak does too.

**Comment by giraone** [comment]
It is a general decision, how this is handled in JHipster. I personally prefer the 200, because 400 can be also returned when the POST body is "technically" wrong. 200 with accepted=false would be "technically correct", but "semantically not accepted". But as I mentioned it is a general decision, that has to be consistent in the whole application.Am 27.07.2022 09:48 schrieb Gaël Marziou ***@***.***>:
Why not returning an HTTP 400 error status?
This would sound more RESTful to me, I guess this is is what Keycloak does too.

**Comment by francoiscorporate** [comment]
Hi,

Will this feature be in newer version of Jhipster ?

I also want to force users to put strong passwords.

Thanks

**Comment by atomfrede** [comment]
Keep it open
