### ISSUE TITLE
AWS deployment fails for us-east-1 location

### ISSUE THREAD

**Issue by rblazquez** [jhipster/generator-jhipster#1913]
It fails to create the bucket with the message: "The specified location-constraint is not valid"

**Comment by jdubois** [comment]
Can anyone else test this or propose a solution?
As we can't test it, I have no idea what we can do...

**Comment by deepu105** [comment]
@wuethrich44 will you be able to take a look at this please?  Im a bit held up with work

**Comment by wuethrich44** [comment]
I will come back from my holidays on 5th September. Then I will take a look a this bug. As a workaround you can create a bucket manually and pass the bucketname to the generator.
