### ISSUE TITLE
python 3.x breaks grunt serve

### ISSUE THREAD

**Issue by craigryan** [jhipster/generator-jhipster#1914]
Following the default jhipster setup, grunt serve fails with a python version error because of browser sync. I have python 3.x installed (Win 8.1). 

Since jhipster indirectly depends on the python version installed I think it would be useful to mention in the installation doc to have python 2.x on PATH

**Comment by deepu105** [comment]
Yes i noticed this too but i wasnt using browser sync so didnt know it was breaking stuff

**Comment by atomfrede** [comment]
I have python 3.4.3 on PATH (Linux) and grunt serve works just fine.

**Comment by jdubois** [comment]
I have Python 2.x installed (default install with Homebrew on Mac), and I don't have any issue. I'm not really aware on any issue, but if this is linked to Grunt or BrowserSync can you link to the issue on those projects? I would be very surprised that one of them as an issue with Python, but I haven't looked at them very deeply.

**Comment by craigryan** [comment]
This only happens with a fresh project for me (no node_modules), after the
first build I guess python isn't called so any version can be installed.
The error I get (below) is fairly clear, browser sync build requires < 3.x
python which they'd probably point out if I logged an issue against it.
Up to you if you want to mention the indirect python 2.x dep in your docs,
for the sake of a better JH newbie experience.

The error:

...grunt-browser-sync\node_modules\
browser-sync\node_modules\socket.io
\node_modules\socket.io-client\node_modules\e
ngine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined
npm_c
onfig_node_gyp
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not
support
ed by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >=
v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion
(D:\packages\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:119:14)
...
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1

**Comment by gmarziou** [comment]
Well known and [very old gyp issue](https://code.google.com/p/gyp/issues/detail?id=36) and as a consequence [node-gyp](https://github.com/nodejs/node-gyp) does not support Pyhton 3 also, even [NodeJS requires gyp to build](https://github.com/nodejs/node/issues/133).

So it's clear the only thing we can do is to document it clearly and wait for Node community to fix this issue.

**Comment by jdubois** [comment]
If it's a node.js requirement we don't have to do anything: it's quite explicit that we rely on Node.js, and that it should be correctly installed.
