### ISSUE TITLE
Defining endpoint security through JDL

### ISSUE THREAD

**Issue by SpiralUp** [jhipster/generator-jhipster#19201]
##### **Overview of the feature request**

When creating an application through JHipster, it is necessary to manually adjust the security on the generated endpoints. This could be avoided if security was defined through JDL and then generated.
An example of a possible definition in JDL:

```
  secure _Entity_ with roles {
       ROLE_ADMIN allows (GET, PUT, POST, DELETE)
       ROLE_USER allows (GET)
  }

```

This should be reflected in the generation of EntityResource and EntityResourceIT.

I already have an implementation for this, so I can share it ...

##### **Motivation for or Use Case**

Now, security has to be added manually on endpoints that are generated and unit tests have to be refined manually. It seems to me that this is the most common refinement over the generated code.

##### **Related issues or PR**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by SpiralUp** [comment]
I just added a comment to the source code:
`
  // Security is enabled on this entity
  // Security type = roles
  // GET:    "ROLE_ADMIN", "ROLE_USER"
  // PUT:    "ROLE_ADMIN"
  // POST:   "ROLE_ADMIN"
  // DELETE: "ROLE_ADMIN"
`
but it's a good suggestion to make it visible in the API documentation as well - it shouldn't be hard ...

**Comment by DanielFran** [comment]
@SpiralUp Are you available to contribute with a PR?

**Comment by SpiralUp** [comment]
I'm available to contribute with a PR...
