### ISSUE TITLE
PostreSQL database not updated after app restart

### ISSUE THREAD

**Issue by rikr2sanchez** [jhipster/generator-jhipster#19210]
##### **Overview of the issue**

I'm using docker for development, PostgreSQL as DB. I've followed the guidelines for the database update (Database updates with the entity sub-generator), first I removed a column, then I've created same column with different data type. Then I've stoped container, rebuilded the app image and create, start container again. 

Result: First the app does not start due to liquibase checksum validation error. Then I cleared the checksums with mvn goal, after that the app starts but  DB is not being updated and keeps the old column type

##### **Motivation for or Use Case**

For my this is a bug since it does not behave as documentation explains.

##### **Reproduce the error**

1. create simple monolith app (use PostgreSQL for local DB and Docker for both, DB and app service as documentation explains)
2. create base db schema
3. run ```jhispter entity <SAMPLE_ENTITY>``` and remove field, then create again with different data type
4. restart the app
5. you will see liquibase checksum error first

##### **JHipster Version(s)**

7.8.1

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
mblab@0.0.1-SNAPSHOT /home/risanchez/work/mblab
└── generator-jhipster@7.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "mblab",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1655963356186,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": ["Order", "Doctor", "Item", "ShopList", "OrderType", "Payment"],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1656030638000,
    "messageBroker": false,
    "nativeLanguage": "es",
    "otherModules": [],
    "packageName": "com.mbdentallab",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  },
  "generator-jhipster-ionic": {
    "appDir": null,
    "ionicDir": "../mblab-mobile"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Order (jhi_order) {
  name String
  entryDate ZonedDateTime
  deadline ZonedDateTime
  testDate ZonedDateTime
  patient String
  dentalPieces String
}
entity Doctor {
  firstName String
  lastName String
  email String
  primaryPhone String
  secondaryPhone String
  address String
}
entity Item {
  name String
  type InventoryItemType
  active Boolean
  color String
  availableAmount Double
  amountUnit String
  unitCost Double
  minAmountAlert Double
  lastPurchase ZonedDateTime
  image ImageBlob
}
entity ShopList {
  title String
  createdAt ZonedDateTime
}
entity OrderType {
  name String
  cost Double
  createdAt ZonedDateTime
}
entity Payment {
  date ZonedDateTime
  amount Double
}
enum InventoryItemType {
  MATERIAL,
  TOOL
}

relationship OneToMany {
  Doctor{order} to Order{doctor}
  OrderType{order} to Order{type}
  Order{payment} to Payment{order}
}
relationship ManyToMany {
  ShopList{items} to Item{shopLists}
  OrderType{items} to Item{orderTypes}
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

git version 2.25.1

node: v18.6.0

npm: 8.13.2

Docker version 20.10.17, build 100c701

Docker Compose version v2.6.1

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
  "applications": "*",
  "changelogDate": "20220624003038",
  "dto": "no",
  "embedded": false,
  "entityTableName": "payment",
  "fields": [
    {
      "fieldName": "date",
      "fieldType": "ZonedDateTime"
    },
    {
      "fieldName": "amount",
      "fieldType": "Double"
    }
  ],
  "fluentMethods": true,
  "jpaMetamodelFiltering": false,
  "name": "Payment",
  "pagination": "no",
  "readOnly": false,
  "relationships": [
    {
      "otherEntityName": "order",
      "otherEntityRelationshipName": "payment",
      "relationshipName": "order",
      "relationshipType": "many-to-one"
    }
  ],
  "service": "no"
}

##### **Browsers and Operating System**

Chrome, WSL

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
> Then I cleared the checksums with mvn goal, after that the app starts but DB is not being updated and keeps the old column type

For me, it works as documented by Liquibase: when you clear checksums, changesets that have already been applied don't get re-run.

https://docs.liquibase.com/commands/maintenance/clear-checksums.html

Changesets are expected to be immutable, this is why Liquibase use checksums and this is why the --incremental-changelog feature was added to JHipster.

https://www.jhipster.tech/creating-an-app/#would-you-like-to-use-incremental-liquibase-changelogs
