### ISSUE TITLE
Translation applies only after page refresh

### ISSUE THREAD

**Issue by pshareiko** [jhipster/generator-jhipster#19246]
##### **Overview of the issue**

The language of the site is not being changed after the language selection. Every translatable module gets replaced with translation.not.found[key].

![image](https://user-images.githubusercontent.com/81857881/181179412-e562e977-c5b5-47d6-ad63-cf232a115d6d.png)

##### **Motivation for or Use Case**

Changing languages on the site becomes unusable

##### **Reproduce the error**

Change the language of the site

##### **Related issues**

Hasn't find any

##### **Suggest a Fix**

I'm assuming the problem is in using React with i18n, because the bug just appears in a freshly generated app. On the other hand, when using Angular as a client framework the language change works fine.

##### **JHipster Version(s)**

v7.8.1

##### **JHipster Version(s)**

```
store@0.0.1-SNAPSHOT C:\Practice\jhipster-store
`-- generator-jhipster@7.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "store",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1658300281392,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "languages": ["ru", "en"],
    "messageBroker": false,
    "nativeLanguage": "ru",
    "otherModules": [],
    "packageName": "by.shareiko.store",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": ["enableSwaggerCodegen:true"],
    "serviceDiscoveryType": "eureka",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

git version 2.24.1.windows.2

node: v16.15.1

npm: 8.11.0

Docker version 20.10.16, build aa7e414

docker-compose version 1.29.2, build 5becea4c

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Doesn't matter

##### **Browsers and Operating System**

Operating system used: Windows 10
The problem occurs in all browsers

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by galilo7** [comment]
Please, how could I fix the issue in my app if it was generated by Jhipster 7.8.1.

**Comment by hungdev** [comment]
how do i fix?
@galilo7 have you fixed it?

**Comment by hungdev** [comment]
I found a way to fix it.
step 1: replace content in locale.ts file by this content:

```
import axios from 'axios';
import dayjs from 'dayjs';
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

import { TranslatorContext } from 'react-jhipster';

const initialState = {
  currentLocale: '',
  sourcePrefixes: [],
  lastChange: TranslatorContext.context.lastChange,
  loadedKeys: [],
  loadedLocales: [],
};

export type LocaleState = Readonly<typeof initialState>;

const loadLocaleAndRegisterLocaleFile = async (locale: string, prefix: string) => {
  if (prefix || !Object.keys(TranslatorContext.context.translations).includes(locale)) {
    const response = await axios.get(`${prefix}i18n/${locale}.json?_=${I18N_HASH}`, { baseURL: '' });
    TranslatorContext.registerTranslations(locale, response.data);
  }
};

export const setLocale = createAsyncThunk('locale/setLocale', async (locale: string, thunkAPI: any) => {
  const { sourcePrefixes, loadedKeys, loadedLocales } = thunkAPI.getState().locale;
  if (!loadedLocales.includes(locale)) {
    const keys = (
      await Promise.all(
        [''].concat(sourcePrefixes).map(async sourcePrefix => {
          const key = `${sourcePrefix}${locale}`;
          if (loadedKeys.includes(key)) return undefined;
          await loadLocaleAndRegisterLocaleFile(locale, sourcePrefix);
          return key;
        })
      )
    ).filter(Boolean);
    thunkAPI.dispatch(loaded({ keys, locale }));
  }
  thunkAPI.dispatch(updateLocale(locale));
  return locale;
});

export const addTranslationSourcePrefix = createAsyncThunk(
  'locale/addTranslationSourcePrefix',
  async (sourcePrefix: string, thunkAPI: any) => {
    const { currentLocale, loadedKeys, sourcePrefixes } = thunkAPI.getState().locale;
    const key = `${sourcePrefix}${currentLocale}`;
    if (!sourcePrefixes.includes(sourcePrefix)) {
      if (!loadedKeys.includes(key)) {
        await loadLocaleAndRegisterLocaleFile(currentLocale, sourcePrefix);
        thunkAPI.dispatch(loaded({ sourcePrefix, keys: [key] }));
      }
    }
    return key;
  }
);

export const LocaleSlice = createSlice({
  name: 'locale',
  initialState: initialState as LocaleState,
  reducers: {
    updateLocale(state, action) {
      const currentLocale = action.payload;
      if (state.currentLocale !== currentLocale) {
        dayjs.locale(currentLocale);
        TranslatorContext.setLocale(currentLocale);
      }
      state.currentLocale = currentLocale;
    },
    loaded(state, action) {
      const { keys, locale, sourcePrefix } = action.payload;
      if (sourcePrefix && !state.sourcePrefixes.includes(sourcePrefix)) {
        state.sourcePrefixes = state.sourcePrefixes.concat(sourcePrefix);
      }
      if (locale && !state.loadedLocales.includes(locale)) {
        state.loadedLocales = state.loadedLocales.concat(locale);
      }
      if (keys) {
        state.loadedKeys = state.loadedKeys.concat(keys);
      }
      state.lastChange = TranslatorContext.context.lastChange;
    },
  },
});

export const { updateLocale, loaded } = LocaleSlice.actions;

// Reducer
export default LocaleSlice.reducer;
```
step 2: delete file translation-middleware.ts in the path: /app/config/translation-middleware.ts

step 3: in store.ts file in the path app/config/store.ts

remove import : import translationMiddleware from './translation-middleware';
and translationMiddleware from 
```
concat(errorMiddleware, notificationMiddleware, loadingBarMiddleware(), loggerMiddleware),
```

you can look at the commit: https://github.com/jhipster/generator-jhipster/pull/19339/files
