### ISSUE TITLE
JHipster bidirectional relationship One-2-Many

### ISSUE THREAD

**Issue by FrancescoMez79** [jhipster/generator-jhipster#19241]
Dear all,
we are using JHipster 6.3.1 version.
After created a new project, we have created in JDL Studio two entities :
- entity FamilyTag {	
    textId String required,
    description String required,
    position Integer required,
    enabled Boolean required
}

- entity Tag {
   textId String required,
   description String required,
   position Integer required,
   enabled Boolean required,
   image ImageBlob required
}

Each FamilyTag can have more Tags. So, we have created a relation OneToMAny :
relationship OneToMany {
	FamilyTag{tag} to Tag{fammilyTag}
}

My question is :
Why the "getAll" method of FamilyTag don't retrieve the list of Tags?

Looking the entity generated we can see in FamilyTag:
...
    @OneToMany(mappedBy = "familyTag")
    private Set<Tag> tags = new HashSet<>();

but trying the getAll method we see that tags is always null :
https://i.imgur.com/jf1Zq4o.png

What can we do to retrieve even the list of tags in FamilyTag ?
Thanks,
Francesco

**Comment by mraible** [comment]
@MathieuAA Can you examine this JDL and determine the issue?

**Comment by MathieuAA** [comment]
I see the typo "fammilyTag", but I guess that's just a typo.
I'm looking into it right now

**Comment by mshima** [comment]
There is no issue, this is the current default behavior.
Need to pass eagerload=true parameter.

**Comment by MathieuAA** [comment]
Indeed, the JDL looks good

**Comment by Tcharl** [comment]
Yes, lazy loading is the default
