### ISSUE TITLE
Don't override Spring MVC defaults for @RequestMapping

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1924]
When JHipster generates API methods, it includes 'method' and 'produces':

    @RequestMapping(value = "/points",
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_VALUE)

I'd recommend changing this to simply be:

    @RequestMapping(value = "/points")

The method value JHipster generates is the same as the default, and produces overrides the default value of 'application/json;charset=UTF-8'. If you decide to make this change, generated tests will need to be updated to not match on exact contentType:

    .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))

You can find information on this at https://jira.spring.io/browse/SPR-10165.

**Comment by jdubois** [comment]
+1 for me, and I'm the original author of this code :-)

**Comment by Vaelyr** [comment]
Removing method parameter will mess with Swagger/Springfox API documentation and gonna list all the possible methods there.

**Comment by RobWin** [comment]
@Vaelyr correct.

**Comment by deepu105** [comment]
I guess keeping current way is better than messing up swagger. So shall we close this @jdubois

**Comment by deepu105** [comment]
May be we can remove the produces attribute

**Comment by jdubois** [comment]
OK, I agree with @deepu105 then... The only thing that could be removed is the "GET" method which is the default, but as we have the other verbs for the other methods I find it more readable to write the verb every time.
