### ISSUE TITLE
Add support to run a local blueprint

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#19269]
##### **Overview of the feature request**

Blueprints are powerful to customize applications.
But it's not easy to create a blueprint package, publish (or install using git) to use it.
We may allow our users to implement a local blueprint at `.blueprint` folder.
This may improve interest in our blueprint system.

##### **Motivation for or Use Case**

Improve developer experience.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Documentation implemented at https://github.com/jhipster/jhipster.github.io/pull/1223.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/112872.

**Comment by DanielFran** [comment]
@mshima approved
