### ISSUE TITLE
authorities are not updated into the database

### ISSUE THREAD

**Issue by sbouchex** [jhipster/generator-jhipster#19267]
##### **Overview of the issue**

I'm using jhipster with keycloak.

If the user does not exist in the local database, it is created (according to UserService.syncUserWithIdP code) and the user authorities are stored into the jhi_user_authority table.
If the user exists in the local database, user details (name, timestamp) are updated (according to UserService.syncUserWithIdP code) but the user authorities are not updated in the jhi_user_authority table.

So if the user has its authorities changed (due to keycloak user change), the user is not getting the new authorities at the next login.

##### **Motivation for or Use Case**

The behavior is different if the user is already existing in the local database or not.

##### **Suggest a Fix**

Replace: updateUser(user.getFirstName(), user.getLastName(), user.getEmail(), user.getLangKey(), user.getImageUrl());
by: 
userRepository.save(user);
this.clearUserCaches(user);

##### **JHipster Version(s)**

7.6.1

##### **JHipster configuration**

oauth2 configuration

##### **Browsers and Operating System**

Chrome

**Comment by sbouchex** [comment]
Related to this change ? #7351

**Comment by OmarHawk** [comment]
Bug Bounty Claim https://opencollective.com/generator-jhipster/expenses/117439

**Comment by DanielFran** [comment]
@OmarHawk approved
