### ISSUE TITLE
Inconsistency in DTO's for relationships

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1928]
There is an inconsistency in the DTO object for relationships.

many-to-many relationships are included in DTOs as DTO objects e.g.
```java
    private Set<ManyToManyEntityDTO> manyToManyEntitys = new HashSet<>();
```

while the one to one-and-one to one-to-many relationships are included as Long objects e.g.
```java
    private Long oneToOneEntityId;
    private Long oneToManyEntityId;
```

We should either include relationships with DTOs or by IDs. Not sure which one is the best approach.

I think this issue may somewhat be related to the [mail discussion (MapStruct is great)](https://mail.google.com/mail/u/0/#inbox/14f4d1e2eee01cf6) @gmarziou started

**Comment by jdubois** [comment]
I did this on purpose, so the UI works the same as what we have without DTOs. This follows what we have with the @JsonIgnore annotation.

-> for many-to-many, in fact only the "owning" side has access to the collection, so we can display it in the edit form. This side also doesn't have the @JsonIgnore, so it works the same without DTOs.
