### ISSUE TITLE
Replace node download workaround for gradle

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#19302]
We have following workaround in place to make node download work with gradle on m1 machines:
https://github.com/jhipster/generator-jhipster/blob/e0a5e6c7db38c6709c001f4b8bb61998b954c031/generators/server/templates/build.gradle.ejs#L577

I think it is not needed as we rely on node >=16 which has arm64 binaries, at least I didn't notice any issues with the plugin on another project.

##### **Motivation for or Use Case**

Generate simple and easy to understand code.

**Comment by mshima** [comment]
👍
