### ISSUE TITLE
Instruction for micro frontend

### ISSUE THREAD

**Issue by paris0120** [jhipster/generator-jhipster#19307]
##### **Overview of the feature request**
Can you provide some information on how to use the new micro frontend function, such as how to disable/enable in the jdl studio, which framework is used etc.  Thank you.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
You can see an example in https://github.com/jhipster/jdl-samples/blob/main/reactive-mf.jdl.

**Comment by paris0120** [comment]
> You can see an example in https://github.com/jhipster/jdl-samples/blob/main/reactive-mf.jdl.

Thank you so much. I'm also wondering if there is a way to keep my current version of jhipster and install the new one and I can decide which version to use when generate the code. I would like to continue my development with the current version but mitigate to the new versions when possible.

**Comment by mraible** [comment]
I would suggest creating a branch and trying the `npx jhipster upgrade` command on it. Or you can manually upgrade too. 

https://www.jhipster.tech/upgrading-an-application/

**Comment by paris0120** [comment]
> I would suggest creating a branch and trying the `npx jhipster upgrade` command on it. Or you can manually upgrade too.
> 
> https://www.jhipster.tech/upgrading-an-application/

Thank you so much.

**Comment by mshima** [comment]
Instructions available at https://github.com/jhipster/generator-jhipster/issues/17031.

**Comment by bluegaspode** [comment]
I also tried to follow/try out microfrontend generation and want to support @paris0120  request.

I'm working with JHipster monolithic applications for quite some time, but just with the documentation available in #17031  I've not been able to create a microfrontend application.

reactive-mj.jdl was a great hint, as it indirectly documents the necessary changes to the jdl files. Unfortunately it doesn't load yet in JDL studio.

**Comment by mshima** [comment]
Updated https://github.com/jhipster/generator-jhipster/issues/17031 description.
