### ISSUE TITLE
Invalid CSRF Token for h2-console when upgrading app from 7.8.1 to 7.9.0

### ISSUE THREAD

**Issue by jsm174** [jhipster/generator-jhipster#19310]
##### **Overview of the issue**

While trying to upgrade a project from JHipster 7.8.1 to 7.9.0, I now get an error while logging into the h2-console:

```
{
  "type" : "https://www.jhipster.tech/problem/problem-with-message",
  "title" : "Forbidden",
  "status" : 403,
  "detail" : "Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'.",
  "path" : "/h2-console/login.do",
  "message" : "error.http.403"
}
```

This may not be an issue (maybe I am missing a configuration update), but an out of the box app in 7.8.1 does not have this issue.

##### **Motivation for or Use Case**

Unable to examine database locally without disabling csrf.

##### **Reproduce the error**

- Start a local keycloak
- Using 7.9.0
```
jhipster jdl app.jdl
chmod +x ./gradlew
./gradlew
```
- Go to http://localhost:8080/h2-console and login
- Verify CSRF error

- Repeat with 7.8.1
- Verify successful login

##### **JHipster Version(s)**

```
test-app@0.0.0 /Users/jmillard/git/test-app
└── generator-jhipster@7.9.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationIndex": 0,
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "TestApp",
    "blueprints": [],
    "buildTool": "gradle",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1609459200000,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": ["LastSeq"],
    "entitySuffix": "",
    "gradleEnterpriseHost": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.0",
    "languages": ["en"],
    "lastLiquibaseTimestamp": 1609459260000,
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageFolder": "com/testapp",
    "packageName": "com.testapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipCheckLengthOfIdentifier": false,
    "skipClient": true,
    "skipFakeData": true,
    "skipUserManagement": true,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity LastSeq {
  id UUID
  startSeq Long required
  endSeq Long required
  createdAt Instant
  lastUpdate Instant
}
paginate LastSeq with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment Homebrew (build 18.0.1.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1.1+0, mixed mode, sharing)

git version 2.36.1

node: v16.16.0

npm: 8.11.0

Docker version 20.10.17, build 100c701

Docker Compose version v2.6.1

##### **Browsers and Operating System**

MacOS 12.4
Chome 103.0.5060.134

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
I can reproduce it. There is an xsrf token send, but it is named `XSRF-TOKEN` while h2 console seems to expect to find it in `X-XSRF-TOKEN`
