### ISSUE TITLE
Adapting ES6 for client side code

### ISSUE THREAD

**Issue by tapas4java** [jhipster/generator-jhipster#1933]
ES6 is already started making noise in the community and Angular 1 also supports it. We should add an option for users to make a decision which language(ES6/ES5) he wants to use for development.

Currently we have below options:

1. Only ES 6 (With Traceur/Babel)
2. TypeScript

Anyway when we migrate to Angular2, We will consider TypeScript. For now I am proposing 1st option.

Let's discuss this and I will be happy to help on this.

**Comment by atomfrede** [comment]
As we are doing the same move now for a new application (ES6 + Babel) I like the idea. But I think this will bring us directly into maintainance hell. Maybe this should be considered for the next major release (3.0).

**Comment by gmarziou** [comment]
I also think that we should generate only ES6 and rely on Babel transpiler for ES5.

**Comment by tapas4java** [comment]
@gmarziou, Supporting only ES6 6  sounds good.

**Comment by atomfrede** [comment]
@gmarziou Yes that would be very cool

**Comment by deepu105** [comment]
This should be a 3.0 item i guess

**Comment by thiagogcm** [comment]
Good news regarding Angular2 
http://angularjs.blogspot.com.br/2015/08/angular-1-and-angular-2-coexistence.html

**Comment by thiagonuic** [comment]
Why not use TypeScript so we could take advantage of the definition types provided by Angular Team? Another great project that uses TypeScript is AngularGrid. They also provide definition types. This would allow autocomplete of their APIs.

**Comment by jdubois** [comment]
Yes I'd like to give a try to TypeScript too, looks like many people are migrating to it -> we could have the whole UI in TypeScript.

This is of course an enormous job, and the technology is absolutely not ready yet.

I don't like to have tickets opened for months, so as we all agree (anyway we will need to move on, that's obvious), I'm closing this as the discussion is OK

**Comment by mraible** [comment]
One of my big takeaways from Angular Summit this week was that 1) you should start using ES6 now and 2) it'll be easier to migrate to Angular 2.x if you follow John Papa's Angular Style Guide. 

https://github.com/johnpapa/angular-styleguide

In the session I attended on Angular 2 with John Lindquist (founder of egghead.io), he showed that TypeScript did add a bit of syntactic sugar over plain ES6, but it was mostly related to constructors and making properties public. He also showed that if you assigned types, you could easily generate JavaScript functions using WebStorm. Pretty cool stuff IMO.

**Comment by thiagonuic** [comment]
My main idea of using TypeScript is to get autocomplete from angular and such. Plus it is easy to get your java code and generate TypeScript interfaces for DTOs.

**Comment by deepu105** [comment]
@jdubois i was tagging these as 3.0 items and had them in 3.0 milestone, so
wouldn't it make more sense to have them open if we are gonna do them for
3.0?

**Comment by jdubois** [comment]
@deepu105 I'm trying not to have too many long-running opened issue.
It's clear to me, we will move to ES6 or TypeScript in the long time.
