### ISSUE TITLE
Warning from webpack with React is a bad developer experience

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#19355]
##### **Overview of the issue**

If you create an app with React and start it with `npm start`, the webpack warning takes up the whole screen and it looks like something is broken. You can close the window so you don't see it and everything works.

In a terminal, there is a warning.

```
WARNING in shared module react-dom
No required version specified and unable to automatically determine one. Unable to find 
required version for "react-dom" in description file 
(/Users/mraible/Downloads/mfa/gateway/node_modules/react-dom/package.json). 
It need to be in dependencies, devDependencies or peerDependencies.
```

In the browser, there's a jarring experience for users. 

<img width="1108" alt="Screen Shot 2022-08-06 at 12 36 02" src="https://user-images.githubusercontent.com/17892/183262132-a3a9458a-ef8a-402d-adaf-753ca229af61.png">

##### **Motivation for or Use Case**

Everything should be smooth when using `npm start`. 

##### **Reproduce the error**

```
jhipster jdl reactive-mf --skip-install
```

Start Docker containers and the gateway. Run `npm start` and you'll see the error.

##### **Suggest a Fix**

Suppress the warning popup in the browser or fix it so there is no warning.

##### **JHipster Version(s)**

```
gateway@0.0.1-SNAPSHOT /Users/mraible/Downloads/mfa/gateway
└── generator-jhipster@7.9.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationIndex": 2,
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "baseName": "gateway",
    "blueprints": [],
    "buildTool": "gradle",
    "cacheProvider": "no",
    "clientFramework": "react",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1659805247556,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9062,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entitySuffix": "",
    "gradleEnterpriseHost": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.2",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en"],
    "messageBroker": false,
    "microfrontends": [
      {
        "baseName": "blog"
      },
      {
        "baseName": "store"
      }
    ],
    "nativeLanguage": "en",
    "otherModules": [],
    "packageFolder": "com/okta/developer/gateway",
    "packageName": "com.okta.developer.gateway",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": true,
    "searchEngine": false,
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": true,
    "testFrameworks": ["cypress"],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

git version 2.32.1 (Apple Git-133)

node: v16.14.0

npm: 8.15.0

Docker version 20.10.17, build 100c701

Docker Compose version v2.6.1

**Comment by mshima** [comment]
@mraible I am pretty sure I fixed this at https://github.com/jhipster/generator-jhipster/pull/19339.
Can you try using main?

**Comment by mraible** [comment]
@mshima I can confirm it is fixed on the `main` branch.
