### ISSUE TITLE
Font-awesome package fails during post-install on Windows

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#19350]
Related to https://github.com/jhipster/generator-jhipster/issues/19294

I was able to reproduce the rimraf issue in Windows. Seems like the actual cause is `npm install` failing
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 127
npm ERR! path C:\Users\d4udt\workspace\jhtest\node_modules\@fortawesome\fontawesome-svg-core
npm ERR! command failed
npm ERR! command bash -c node attribution.js
npm ERR! /bin/bash: node: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\d4udt\AppData\Local\npm-cache\_logs\2022-08-05T15_02_07_830Z-debug-0.log
Error executing './npmw install', execute it yourself. (Command failed with exit code 127: ./npmw install)
```

When I run `npm install` manually and inspect the error log, it seems like failure is caused by the post-install script from `@fortawesome/fontawesome-common-types@6.1.2` so either we need to downgrade this dependency or wait for a fix upstream (https://github.com/FortAwesome/Font-Awesome/issues/19243). I have submitted an issue upstream and will open on here to track. 

For now workaround would be to downgrade the fontawesome version in package.json

**Comment by mshima** [comment]
This is probably duplicated of https://github.com/jhipster/generator-jhipster/issues/19225

**Comment by OmarHawk** [comment]
yes, that's the same - removing or clearing the generated .npmrc works as a workaround
