### ISSUE TITLE
npm WARN While resolving: react-virtualized@9.22.3

### ISSUE THREAD

**Issue by jaydeep-punjani** [jhipster/generator-jhipster#19353]
##### **Overview of the issue**

Getting NPM issue while running npm install
##### **Reproduce the error**
unable to start the UI from webpack using npm start. Blocked development for UI.

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-virtualized@9.22.3
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"18.2.0" from the root project
npm WARN   20 more (@fortawesome/react-fontawesome, @reduxjs/toolkit, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm WARN node_modules/rsuite/node_modules/react-virtualized
npm WARN   react-virtualized@"^9.22.3" from rsuite@5.16.4
npm WARN   node_modules/rsuite
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm WARN   node_modules/rsuite/node_modules/react-virtualized
npm WARN     react-virtualized@"^9.22.3" from rsuite@5.16.4
npm WARN     node_modules/rsuite
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-virtualized@9.22.3
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"18.2.0" from the root project
npm WARN   12 more (@rsuite/icons, @testing-library/react, react-jhipster, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm WARN node_modules/rsuite/node_modules/react-virtualized
npm WARN   react-virtualized@"^9.22.3" from rsuite@5.16.4
npm WARN   node_modules/rsuite
npm WARN 
npm WARN Conflicting peer dependency: react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm WARN   node_modules/rsuite/node_modules/react-virtualized
npm WARN     react-virtualized@"^9.22.3" from rsuite@5.16.4
npm WARN     node_modules/rsuite

##### **JHipster Version(s)**

7.9.2
##### **Browsers and Operating System**

MAC
- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Please re-open and provide your JDL so we can reproduce it.
