### ISSUE TITLE
Create user always do update (error) instead of save

### ISSUE THREAD

**Issue by jankod** [jhipster/generator-jhipster#19369]
##### **Overview of the issue**

On _user-management-update.component.ts_  on _save()_ method
I see when use console.log(user) that user.id is empty string but in angular it is number | null.
When I create new user always do this.userService.update()  instead this.userService.create(user)
and i got "Internal server error." because on server user has no set up user.id for update on database.

` if (user.id !== null`  not work.

##### **Reproduce the error**
Create clasic angular monolithic app. It is not posible to create new user.

##### **JHipster Version(s)**
v7.9.2

#####  Sugested fix
ugly solution is:

```TypeScript
  let u = "update";
  if (user.id != null)
    u = user.id.toString();

 if (u !== '') {
      this.userService.update(user).subscribe({
        next: () => this.onSaveSuccess(),
        error: () => this.onSaveError(),
      });
    } else {
      this.userService.create(user).subscribe({
        next: () => this.onSaveSuccess(),
        error: () => this.onSaveError(),
      });
    }
```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "aquapro",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "spacelab",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1659607498679,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": ["UserProfile", "Project", "Sample", "Analysis"],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.2",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "hr"],
    "lastLiquibaseTimestamp": 1659707804000,
    "messageBroker": false,
    "microfrontend": false,
    "microfrontends": [],
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "hr.ja.aquapro",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity UserProfile {
  firstName String
  lastName String
}
entity Project {
  name String required maxlength(220) unique
  description String maxlength(4000)
}
entity Sample {
  multispectralZipFile AnyBlob required
  description String maxlength(4000)
}
entity Analysis {
  name String required maxlength(200)
  description String maxlength(4000)
}
relationship OneToOne {
  UserProfile{user} to User
}
relationship OneToMany {
  UserProfile{project} to Project{userProfile}
  Project{a} to Sample{fff}
  Sample{analysis} to Analysis{sample}
}

paginate UserProfile, Project, Sample, Analysis with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

git version 2.34.1

node: v16.16.0

npm: 8.11.0

Docker version 20.10.14, build a224086

docker-compose version 1.29.2, build 5becea4c

##### **Browsers and Operating System**
Chrome, Firefox
Linux OS

**Comment by mshima** [comment]
Looks like we don't have cypress tests for user-management.

**Comment by mshima** [comment]
Workaround should be remove the optional (?) from id field at IUser and User definitions.

**Comment by jankod** [comment]
> Workaround should be remove the optional (?) from id field at IUser and User definitions.

This not work, I got two compile errors.

```
Error: src/main/webapp/app/admin/user-management/user-management.route.ts:20:15 - error TS2554: Expected 1-12 arguments, but got 0.

20     return of(new User());
                 ~~~~~~~~~~

src/main/webapp/app/admin/user-management/user-management.model.ts:18:5
  18     public id: number | null,
         ~~~~~~~~~~~~~~~~~~~~~~~~
  An argument for 'id' was not provided.
```
