### ISSUE TITLE
'Command failed with exit code 4294963238: npm run clean-www'

### ISSUE THREAD

**Issue by AdhiyamanMuthu** [jhipster/generator-jhipster#19360]
Overview of the issue,

I have started with Jhipster, I gave the following configurations to my first app 
{
WARNING! Your Node version is not LTS (Long Term Support), use it at your own risk! JHipster does not support non-LTS releases, so if you encounter a bug, please use a LTS version first.
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? firstapp
? Do you want to make it reactive with Spring WebFlux? Yes
? What is your default Java package name? com.infy.firstapp
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, MSSQL)
? Which *production* database would you like to use? MySQL
? Which *development* database would you like to use? MySQL
? Would you like to use Maven or Gradle for building the backend? Maven
? Do you want to use the JHipster Registry to configure, monitor and scale your application? Yes
? Which other technologies would you like to use?
? Which *Framework* would you like to use for the client? React
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to enable internationalization support? No
? Please choose the native language of the application English
? Besides JUnit and Jest, which testing frameworks would you like to use?
? Would you like to install other generators from the JHipster Marketplace? Yes
? Which other modules would you like to use?
Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 99,999 days
        for: CN=Java Hipster, OU=Development, O=com.infy.firstapp, L=, ST=, C=

KeyStore 'D:\Jhipster\firstapp\src\main\resources\config\tls\/keystore.p12' generated successfully.
}
--------------------------------------------------------------------------------
and this error while generating the app

{
Changes to package.json were detected.

Error: JAVA_HOME not found in your environment.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path D:\Jhipster\firstapp\node_modules\@fortawesome\fontawesome-common-types
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adhiyaman.muthu\AppData\Local\npm-cache\_logs\2022-08-07T04_00_50_749Z-debug-0.log
Error executing './npmw install', execute it yourself. (Command failed with exit code 4294963238: ./npmw install)
Application successfully committed to Git from D:\Jhipster\firstapp.

If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Server application generated successfully.

Run your Spring Boot application:
./mvnw (mvnw if using Windows Command Prompt)

Client application generated successfully.

Start your Webpack development server with:
 npm start

> firstapp@0.0.1-SNAPSHOT clean-www
> rimraf target/classes/static/app/{src,target/}

npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path D:\Jhipster\firstapp
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adhiyaman.muthu\AppData\Local\npm-cache\_logs\2022-08-07T04_07_15_798Z-debug-0.log
× An error occured while running jhipster:client#end
ERROR! Command failed with exit code 4294963238: npm run clean-www
Error: Command failed with exit code 4294963238: npm run clean-www
    at makeError (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\execa\lib\error.js:60:11)
    at module.exports.sync (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\execa\index.js:194:17)
    at spawnCommand.spawnCommandSync (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\actions\spawn-command.js:35:16)
    at JHipsterClientGenerator.end (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\generators\client\index.js:428:16)
    at Object.<anonymous> (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1091:23)
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:26:19
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1092:9
    at new Promise (<anonymous>) {
  shortMessage: 'Command failed with exit code 4294963238: npm run clean-www',
  command: 'npm run clean-www',
  escapedCommand: 'npm run clean-www',
  exitCode: 4294963238,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
}

can anyone kindly help me to get this problem resolved? thanks in advance.

**Comment by mraible** [comment]
> WARNING! Your Node version is not LTS (Long Term Support), use it at your own risk! JHipster does not support non-LTS releases, so if you encounter a bug, please use a LTS version first.

What version of Node are you using?

**Comment by AdhiyamanMuthu** [comment]
Hello Matt Raible!
I am using node version - v18.4.0.

if i use node latest node version, will my errors get resolved?

**Comment by mraible** [comment]
Node 16 is the latest LTS version. https://nodejs.org/

Please try that.

**Comment by AdhiyamanMuthu** [comment]
I have installed node v16.14.0
but again got some other errors while generating the jhipster as follows,

Error: JAVA_HOME not found in your environment.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'secondapp@0.0.1-SNAPSHOT',
npm WARN EBADENGINE   required: { node: '>=16.16.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.16.0' }
npm WARN EBADENGINE }
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path D:\Jhipster\secondapp\node_modules\@fortawesome\fontawesome-common-types
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adhiyaman.muthu\AppData\Local\npm-cache\_logs\2022-08-08T10_42_56_966Z-debug-0.log
Error executing './npmw install', execute it yourself. (Command failed with exit code 4294963238: ./npmw install)
Application successfully committed to Git from D:\Jhipster\secondapp.

If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Server application generated successfully.

Run your Spring Boot application:
./mvnw (mvnw if using Windows Command Prompt)

Client application generated successfully.

Start your Webpack development server with:
 npm start


> secondapp@0.0.1-SNAPSHOT clean-www
> rimraf target/classes/static/app/{src,target/}

npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path D:\Jhipster\secondapp
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adhiyaman.muthu\AppData\Local\npm-cache\_logs\2022-08-08T10_50_36_473Z-debug-0.log
× An error occured while running jhipster:client#end
ERROR! Command failed with exit code 4294963238: npm run clean-www
Error: Command failed with exit code 4294963238: npm run clean-www
    at makeError (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\execa\lib\error.js:60:11)
    at Function.module.exports.sync (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\execa\index.js:194:17)
    at JHipsterClientGenerator.spawnCommand.spawnCommandSync (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\actions\spawn-command.js:35:16)
    at JHipsterClientGenerator.end (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\generators\client\index.js:428:16)
    at Object.<anonymous> (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1091:23)
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:26:19
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1092:9
    at new Promise (<anonymous>) {
  shortMessage: 'Command failed with exit code 4294963238: npm run clean-www',
  command: 'npm run clean-www',
  escapedCommand: 'npm run clean-www',
  exitCode: 4294963238,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**Comment by mraible** [comment]
Node.js 16.16.0 is the latest LTS version. Can you please try that?

**Comment by AdhiyamanMuthu** [comment]
No issue was found on the current node version. but still, I am facing the same issue while generating the app.

npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path D:\Jhipster\thirdapp
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adhiyaman.muthu\AppData\Local\npm-cache\_logs\2022-08-09T06_42_38_784Z-debug-0.log
× An error occured while running jhipster:client#end
ERROR! Command failed with exit code 4294963238: npm run clean-www
Error: Command failed with exit code 4294963238: npm run clean-www
    at makeError (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\execa\lib\error.js:60:11)
    at Function.module.exports.sync (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\execa\index.js:194:17)
    at JHipsterClientGenerator.spawnCommand.spawnCommandSync (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\actions\spawn-command.js:35:16)
    at JHipsterClientGenerator.end (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\generators\client\index.js:428:16)
    at Object.<anonymous> (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1091:23)
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:26:19
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1092:9
    at new Promise (<anonymous>) {
  shortMessage: 'Command failed with exit code 4294963238: npm run clean-www',
  command: 'npm run clean-www',
  escapedCommand: 'npm run clean-www',
  exitCode: 4294963238,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false

**Comment by khadijakaimous** [comment]
i have the same issue, i cannot run the client#end with jhipster. i have the LTS version of node and java 11 and npm 8.

**Comment by khadijakaimous** [comment]
npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path C:\Users\HP\Documents\projects\jhipster
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Local\npm-cache\_logs\2022-08-17T14_24_53_567Z-debug-0.log
× An error occured while running jhipster:client#end
ERROR! Command failed with exit code 4294963238: npm run clean-www
Error: Command failed with exit code 4294963238: npm run clean-www

**Comment by DanielFran** [comment]
@khadijakaimous Since you are on windows, can you delete .npmrc file and confirm it is working?

**Comment by AndyAndurkar** [comment]
It works! Thanks, Daniel

**Comment by khadijakaimous** [comment]
Thank you so much it worked successfully

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by khadijakaimous** [comment]
But I will have to delete it every time I run the command jhipster generate a project ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DanielFran** [comment]
@khadijakaimous this has been fixed in 7.9.3
