### ISSUE TITLE
Proposal: define most common tasks as defaults to improve developer experience

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1936]
The following seem to be the most common tasks:

mvn spring-boot:run
gradlew bootRun
grunt serve

Wouldn't it be nicer if you only had to run?

mvn
gradlew
grunt

I find that typing one word is easier than two. ;)

It's an easy change, I'll create a pull request to match.

**Comment by jdubois** [comment]
Currently we don't have a default Maven goal, for example, so yes at least it could be used for the most common task, I agree.

**Comment by atomfrede** [comment]
We should not forget the default gulp task :)

**Comment by jdubois** [comment]
Sorry I'm just changing my mind:

- By default with Grunt the "usual" default task is to build the project. And we always use the default used by the underlying technology, see [policy 1](http://jhipster.github.io/policies.html)
- If the default for Grunt is to build, then it would also be logical to have "mvn package" be the default Maven task

-> I agree those are not the tasks I run the most often, but it looks more logical to me to have the build tasks by default

**Comment by jdubois** [comment]
@atomfrede by the way our Gulp maintainer @amr doesn't look very active anymore, shouldn't we deprecate Gulp?

**Comment by atomfrede** [comment]
I've not used gulp for jhipster projects. What about the usage statistics?

**Comment by jdubois** [comment]
@atomfrede I'm opening a new ticket for this

**Comment by mraible** [comment]
I disagree that the "usual" task for Grunt or Gulp is the build the project. In fact, I never build the project - I let Jenkins do that for me. Same goes for packaging. 

As a developer, I like to run and I do it several times a day. 

Even if you don't approve this, it'd be good to specify the default task for each build system. Then developers can change it to suite their style. That's what I've done on my projects.

**Comment by jdubois** [comment]
Yes, I also use the run tasks much more often than the build tasks, agreed.

Has anybody have another opinion on this?

**Comment by deepu105** [comment]
+1 for having run tasks as default

**Comment by atomfrede** [comment]
:+1: most used are ``./gradlew bootRun`` and ``grunt serve``

**Comment by andidev** [comment]
+1

**Comment by jdubois** [comment]
OK let's do it then!
