### ISSUE TITLE
Add tag for updatable files

### ISSUE THREAD

**Issue by paris0120** [jhipster/generator-jhipster#19381]
##### **Overview of the feature request**

Add a tag for the generated file that will be upgated/rewrite by jdl such as '##jhipster' or add a tag for files to skip for upgrade such as '##skip' at the beginning of a file. 

##### **Motivation for or Use Case**
When users modify the generated files they can remove or add the tag so that when jdl upgrade/regenerate the program it can skip the files instead of asking whether to overwrite them. 

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Use .yo-resolve, this can be done by ignoring the file at prompt with `i` option or write the relative path to file.
