### ISSUE TITLE
JDL JSON Entity field

### ISSUE THREAD

**Issue by JusticeN** [jhipster/generator-jhipster#19383]
##### **Overview of the feature request**
In some RDBMS table, use case like product attribute need dynamic fields.

##### **Motivation for or Use Case**

It will be time saving to have a Json entity field type that get converted to Java maps. Now I need to create a the field manually and have to solve merge conflicts every time I regenerate the code. E.g.: https://baeldung-cn.com/hibernate-persist-json-object 

##### **Related issues or PR**
Didn't find any so far. I hope the request is not a bad idea

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
If you'd like to contribute and maintain this feature, we're interested!

**Comment by emilpaw** [comment]
Related to: https://github.com/jhipster/generator-jhipster/issues/14526

**Comment by DanielFran** [comment]
Closed in favour of https://github.com/jhipster/generator-jhipster/issues/14526
