### ISSUE TITLE
Relationships to User are saved in a microservice architecture, but not rendered

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#19399]
##### **Overview of the issue**

Today, I tried my original [reactive microservices example](https://github.com/oktadev/java-microservices-examples/tree/main/reactive-jhipster) from [this blog post](https://developer.okta.com/blog/2021/01/20/reactive-java-microservices) and everything works as expected. The example is created with v7.0.1 and you can save a `blog` entity with or without a `user` and it all works.

<img width="1123" alt="Screen Shot 2022-08-10 at 23 42 49" src="https://user-images.githubusercontent.com/17892/184071130-8ac841dc-444b-4e09-a545-895893a32a24.png">
<img width="1123" alt="Screen Shot 2022-08-10 at 23 42 53" src="https://user-images.githubusercontent.com/17892/184071140-9068b371-4418-4dde-9063-d07bedee1ff8.png">
<img width="1123" alt="Screen Shot 2022-08-10 at 23 43 04" src="https://user-images.githubusercontent.com/17892/184071147-c1f5f7c4-4ab5-48c6-a320-0373f11c2d86.png">

If you create this same example with 7.9.2, it saves the relationship to the user, but it does not render it on the list or view screens. Furthermore, Angular does not render the user's login on the list screen.

For more information, see https://github.com/jhipster/generator-jhipster/issues/19342#issuecomment-1208877640 and subsequent comments.

##### **Motivation for or Use Case**

This functionality existed in v7.0.1 and therefore should be supported in all 7.x releases.

##### **Reproduce the error**

```
jhipster jdl reactive-ms
```

Then, start all the Docker containers for the gateway and start it. Start Neo4j for the blog app and start it as well. Log in and navigate to adding a new blog. After you add a new one, you'll see it rendered on the list screen. However, if you navigate to the view or edit screens, the user's login is not displayed. 

##### **JHipster Version(s)**

7.9.2

##### **JHipster configuration**

https://github.com/jhipster/jdl-samples/blob/main/reactive-ms.jdl

**Comment by mshima** [comment]
That's odd, I will take a look.

**Comment by mshima** [comment]
@mraible this happens only with Neo4j?

**Comment by mraible** [comment]
It works with 7.0.1 and Neo4J. I tried using PostgreSQL for both gateway and blog, but [couldn't get it to work](https://github.com/jhipster/generator-jhipster/issues/19342#issuecomment-1210906276).

**Comment by mshima** [comment]
@mraible https://github.com/jhipster/generator-jhipster/pull/19402 fixes the problem for Neo4j, fill free to merge it.
Postgres will be more complex. I’ve already done some work on it, but in the process I will do some cleanup at the templates and split into another PR.

**Comment by mraible** [comment]
@mshima I can confirm this particular issue is fixed by your PR! I confirmed with Vue and Angular. Feel free to close it, or leave it open for PostgreSQL.

**Comment by mshima** [comment]
Closing since the bug is fixed. I'm planing a follow-up PR targeting v8.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/112863.
