### ISSUE TITLE
Deprecate Gulp.js support

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1939]
Our current Gulp.js support isn't good enough:

- Our maintainer @amr doesn't seem very active anymore
- Gulp.js is only 6% of our front end builder usage (and 94% for Grunt)

Of course this causes a lot of issues, and is complex for maintenance.

Besides:

- Yeoman still provides specific tasks for Grunt (so it's better for us to use Grunt)
- When I started the project 2 years ago, Gulp.js was all the hype, and it was supposed to supercede Grunt. This has clearly not happened, and if this hasn't been the case after 2 years, I don't believe it will ever succeed.
- Gulp.js was also supposed to be faster and easier to use, I haven't seen this at all in practice

**Comment by deepu105** [comment]
Gulp is faster than grunt atleast in windows :P

**Comment by deepu105** [comment]
Shouldn't we ask people if someone is ready to take up gulp maintenance i
would hate to see all that effort removed :(

**Comment by mraible** [comment]
I agree with @deepu105. Can you point out any issues logged against the Gulp support or show us how to find them? I'd be happy to try and fix them.

**Comment by thiagogcm** [comment]
" I don't believe it will ever succeed."
Well, huge projects like angular 2 use Gulp for a reason...

I think it's too early to drop support for gulp.. just my humble opinion

**Comment by jdubois** [comment]
I'm not speaking about how good Gulp.js is supposed to be, just that it has not succeeded as having a bigger user base than Grunt.

Let me repeat again:

-  We only have 6% of users with Gulp.js (from 6331 generated projects last month)
- I said I didn't believe it will ever succeed, as usually successful projects get successful early. If, after 2 years, it hasn't been successful, then there are high chances that it will never be successful.

So I understand this last point was misunderstood, because it's 6% but it's going to go up because of its modular design, and general coolness, etc.

So I've had a look at the same stat, from January 2015. It was 11%. So Gulp.js usage has a downside trend. It's going down so big, that in just 8 month it went from 11% to 6%.

I'm using my statistics for stating that Gulp.js is going down, from 6331 generated projects last month. I don't even understand how we could argue about how maths could be wrong!

I'm not saying I don't like Gulp.js or that it is not cool, just that this has a high maintenance cost, and each of our options that goes close to 5% of usage should be a good candidate from being removed. We can't support everything, we have to focus on what people use.

Now if someone wants to stand up and be the official Gulp.js maintainer, I would be very happy about it, of course.

**Comment by tapas4java** [comment]
May be stats are not in favour of gulp because we are recomending grunt during project creation and lack of emphasise on docs. 

I believe gulp is equally capable as grunt with speed and easy configuration as added advantages. Droping gulp support is not a good idea!

**Comment by jdubois** [comment]
@tapas4java good point. But we have the same message for Gradle (which I should remove as the Gradle support is now very good thanks to @atomfrede ), and it's at a steady 10% (same in January as now).

**Comment by PeterEltgroth** [comment]
@jdubois I'm not a gulp (or grunt) expert, but I am using gulp on a project, and as such have an interest in keeping it alive in jhipster. I am willing to help maintain it, but will have a lot to learn.

Are there more issues [than these](https://github.com/jhipster/generator-jhipster/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+gulp
), and setting a default task for gulp like done in #1936?

**Comment by jdubois** [comment]
Hi @PeterEltgroth ! Yes there are only those few issues at the moment.
OK try to correct them and add the default task, and if you feel confortable with it you can be our new Gulp maintainer. That would solve this issue for me!

**Comment by mraible** [comment]
I added the default task for Gulp as part of #1936.

https://github.com/mraible/generator-jhipster/commit/6c88fd6c380dec976b3472e83d95d60833c0b4c9

**Comment by deepu105** [comment]
Lets try to keep gulp alive. Its actually faster than grunt and simpler to
read so all of us should give it a chance and try it out. Im planning to
use it in my next JH project as default im annoyed by grunt build being
slower than the gradle task. Especially the uglify task. I tried gulp on
the same project and it was much faster build.

**Comment by dancancro** [comment]
A couple of trade-off reports for what they're worth. Corrections welcome...
http://dancancro.com/grunt_vs_gulp.html
http://dancancro.com/brunch_vs_grunt.html

**Comment by deepu105** [comment]
If you go by github stars then
Gulp: 15k+
Grunt:9k+
Brunch:4k+

So thats something

**Comment by PeterEltgroth** [comment]
Thanks @mraible 

@jdubois I'll start looking at #1639 this weekend.

**Comment by amr** [comment]
and I'm not totally gone too, and would very much hate to see gulp support fade away in jhipster, will try to help as much as I can!

**Comment by PeterEltgroth** [comment]
Great to know @amr

**Comment by jdubois** [comment]
@amr great to see you again! Could you both work on Gulp.js, so it has the same level of support as Grunt? We'll then remove the "recommended" tag on Grunt, like we did for Maven

**Comment by PeterEltgroth** [comment]
@jdubois and @amr sounds good to me! I still have much to learn regarding gulp.

**Comment by wimdeblauwe** [comment]
I have noticed that there is still a recommended tag on Grunt in 2.27.0. I found this issue because I was trying to figure out why it is recommended. It it still recommended to use Grunt (our front-end devs like Gulp more).

If Grunt and Gulp should be on par, then maybe the page http://jhipster.github.io/development/ should be updated to reflect how to use the live reloading with Gulp?

**Comment by deepu105** [comment]
Problem is we dont have anyone actively maintaining our gulp part and the
core team mostly uses grunt so we couldn't put more effort to keep gulp in
line with grunt.

Yes gulp seems more user friendly and stable now so if anyone comes forward
to update and contribute we would be happy to remove the recommended label
for grunt. We have done it for gradle earlier and removed label since our
gradle support become on par with maven

**Comment by atomfrede** [comment]
I'm using gulp a lot at work, its pretty cool and I think I like it more than grunt. But as @deepu105 said we don't have a maintainer for that part. Does anybody know the current state of the gulp support? Are all features of our grunt build supported?

**Comment by deepu105** [comment]
I would also like to add few points.

After trying both grunt and gulp i would definitely prefer gulp
- as it is much more faster than grunt due to its streaming of files
opposed to io in grunt
- gulp is less verbose and easier to configure than grunt.
- less lines of code than grunt for similar setup
- you can do everything in gulp which you could do in grunt
- angular, yeoman and many big projects have switched to gulp and
recommends the same

**Comment by deepu105** [comment]
@atomfrede lets try to get our gulp on par with grunt. Then we can remove
the recommended label

**Comment by atomfrede** [comment]
@deepu105 You are absolutly right. Same experience from my side. We used grunt first (using windows at work) and starting up a browsersync server is much faster with gulp even the project is larger than the one using grunt.

**Comment by ngasull** [comment]
Hello hipsters, @pascalgrimaud brought me here!

A lot people now - especially among frontend and fullstack devs - prefer gulp over grunt mostly because of its principle: code over configuration. Morover, gulp community grew huge (see that [grunt](https://www.npmjs.com/package/grunt) and [gulp](https://www.npmjs.com/package/gulp) npm downloads are comparable, gulp is even higher) Thus I highly encourage to fully support gulp, without not recommending it which could discourage many potential jHipster users.

I've used grunt and gulp. You guessed that I prefer gulp ;) I've made my company's build flow with gulp so I have some knowledge of it. I don't know what's needed right now to help with gulp (which features are missing?) but don't hesitate to open an issue about it and mention me in it. I'd be glad to provide some help and to have a look into it.

**Comment by deepu105** [comment]
Thats great, we need to compare the gulpfile with gruntfile to see if all
options are covered, next we should test and make sure everything wirks
fine, need to check browsersync part which was having issues all the time

**Comment by atomfrede** [comment]
I've created an app with gulp. Surprisingly browser sync seems to work quite well. The prod build is not working at all 😢

**Comment by jdubois** [comment]
It's like our support for Gradle and Maven, the problem is that:

- Supporting both tools makes everybody happy (otherwise we would lose a good share of our users)
- But it's too much work for us to support both of them!

The current state is that most people use Grunt, including me, and that's why it's the recommended option, as we know there are less bugs.

We could do a bold move and migrate to Gulp totally, so we don't have the headache of maintaining both options, but that would be a major change we can't do in a minor version.

So, if people are interested in Gulp.js : please do contribute, help the Gulp.js build to be as good as the Grunt one, and then we can remove the recommended tag, and for a major release in the future start thinking of migrating. At the moment we just don't have enough people working on this, and we can't do everything -> as far as I'm concerned, I'd rather work on new features than on something which is already working well

**Comment by deepu105** [comment]
Julien,  yes its true that we need not invest more time here, but I think
we need to give gulp a chance by fixing it and removing the label.  The
usage ratio is less coz Most of the people who use Jhipster would be
backend devs who are not very familiar with Gulp or Grunt so they just
choose our recommended tool. I can boldly say that anyone who have used
both on a real project will never go back to grunt. Gulp really is so much
faster and better thats why even yeoman is gonna deprecate the grunt api as
they have already moved to using Gulp.

Once we get gulp fixed, which shouldn't be too tough, we should consider
dropping Grunt as it clearly wouldn't have any advantage over Gulp. And we
could save a lot of code

And I dont understand why it has to be a major release as it wont break
anything people can actually replace their grunt file easily with gulp as
it does the same job

**Comment by mkh1973** [comment]
Hi there,

I’m not familiar with gulp right now - I’m a quick learner, but if there’s a need I would volontier maintaining the gulp build.
Please let me know what to do.

br Michael

> Am 25.01.2016 um 02:06 schrieb Deepu K Sasidharan <notifications@github.com>:
> 
> Julien, yes its true that we need not invest more time here, but I think
> we need to give gulp a chance by fixing it and removing the label. The
> usage ratio is less coz Most of the people who use Jhipster would be
> backend devs who are not very familiar with Gulp or Grunt so they just
> choose our recommended tool. I can boldly say that anyone who have used
> both on a real project will never go back to grunt. Gulp really is so much
> faster and better thats why even yeoman is gonna deprecate the grunt api as
> they have already moved to using Gulp.
> 
> Once we get gulp fixed, which shouldn't be too tough, we should consider
> dropping Grunt as it clearly wouldn't have any advantage over Gulp. And we
> could save a lot of code
> 
> And I dont understand why it has to be a major release as it wont break
> anything people can actually replace their grunt file easily with gulp as
> it does the same job

**Comment by atomfrede** [comment]
:+1: First think I noticed not working is the production build, so if you like you can try to fix it.

**Comment by cbornet** [comment]
:+1 I can confirm that front end devs prefer gulp.

**Comment by ngasull** [comment]
I've just finished my work on gulp build :) https://github.com/jhipster/generator-jhipster/pull/2686

Production build (`gulp build`) was broken indeed. Moreover, `url` links in css files were broken. I've made the appropriate fixes for both and added a test, please feel free to test these and report me any problem on them. Moreover, I've only tested with `sass` enabled for now.

**Comment by deepu105** [comment]
Sure will test and merge this asap

**Comment by deepu105** [comment]
@mkh1973 that would be great, the more people working on this the closer we are to make gulp standard :)

Gulp serve is just way faster than grunt serve to even have a second thought  :)
