### ISSUE TITLE
Could not add user in admin user management GUI for v7.9.0

### ISSUE THREAD

**Issue by scyllor** [jhipster/generator-jhipster#19400]
##### **Overview of the issue**
Could not add user in admin user management GUI

![image](https://user-images.githubusercontent.com/2325287/184073818-6129156d-55b8-409b-ab4d-2273b66149c3.png)
![image](https://user-images.githubusercontent.com/2325287/184073875-ba74919b-0d15-4182-9a80-b8639f42a726.png)
![image](https://user-images.githubusercontent.com/2325287/184073923-61f9b4e3-1b04-4158-b93c-e6000bbec894.png)
![image](https://user-images.githubusercontent.com/2325287/184074000-79866832-2876-45e8-b874-9399cfb47288.png)

##### **Motivation for or Use Case**

Could not add user in admin user management GUI
##### **Reproduce the error**

1. generate any project using jhipster v7.9.0
2. config database correctly and ./mvnw at project directory
3. login using admin account and password
4. open user management gui for admin
5. click create user
6. put anything and save then the page said server internal error and the user could not be created.
##### **Suggest a Fix**
like photo shown, give a null value for initalUser or change the judgement code for user.id with !!user.id or take care about undefined variable

##### **JHipster Version(s)**
jhipster v7.9.0

##### **Browsers and Operating System**
Edge 104.0.1293.47 x86_64(Macbook Air Intel CPU)

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Duplicated of https://github.com/jhipster/generator-jhipster/issues/19369. Fixed on main.
