### ISSUE TITLE
Remove recommended label for maven

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1942]
As @jdubois highlighted in another thread the recommended label on maven should be removed as our gradle support is as good as maven and latest gradle is on par with maven. This would give gradle and maven equal chance of selection during app generation

**Comment by jdubois** [comment]
Yes agreed, thanks to @atomfrede !!!

**Comment by atomfrede** [comment]
Thanks! It's a pleasure to work with you all.
