### ISSUE TITLE
JHipster lite version

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1943]
A lite version of Jhipster with minimal options and minimal footprint with a decoupled admin UI if required. This will be great for micro projects and micro services. 
If possible we can explore something like spark or dagger as well

Just an idea for 3.0

**Comment by BhawaniSingh** [comment]
Yeah sure, I have experience with dagger (but on android) not sure how it
works with web.
But I'll look into it


Regards
Bhawani Singh

**Comment by piedrahitac** [comment]
I think this could be useful as long as the guidelines for the minimal options are set early on, because I don't know if supporting another project with a different stack can become overwhelming in the long run...

**Comment by jdubois** [comment]
I've had quite a long time toying on this, and I'm not satisfied with the results.
OK, you can remove lots of stuff, which would make the app go quicker, but then you have the security missing, the transactions missing.... etc.

**Comment by mraible** [comment]
I created a light version of AppFuse and it never got much traction at all. It's a lot of work to maintain and no one uses it.

**Comment by allanws** [comment]
Sorry for distracting you guys with that, but do you know the highest memory consumption culprits?
