### ISSUE TITLE
Could not run commands "npm start" and "./mvnw" to run the application.

### ISSUE THREAD

**Issue by AdhiyamanMuthu** [jhipster/generator-jhipster#19450]
Changes to package.json were detected.
Jhipster\firstapp\\target\node\npm.cmd was unexpected at this time.
Error executing './npmw install', execute it yourself. (Command failed with exit code 255: ./npmw install)
Application successfully committed to Git from D:\5) Jhipster\firstapp.

If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Server application generated successfully.

Run your Spring Boot application:
./mvnw (mvnw if using Windows Command Prompt)

Client application generated successfully.

Start your Webpack development server with:
 npm start

> firstapp@0.0.1-SNAPSHOT clean-www
> rimraf target/classes/static/app/{src,target/}

npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path D:\5) Jhipster\firstapp
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adhiyaman.muthu\AppData\Local\npm-cache\_logs\2022-08-16T15_05_13_385Z-debug-0.log
× An error occured while running jhipster:client#end
ERROR! Command failed with exit code 4294963238: npm run clean-www
Error: Command failed with exit code 4294963238: npm run clean-www
    at makeError (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\execa\lib\error.js:60:11)
    at Function.module.exports.sync (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\node_modules\execa\index.js:194:17)
    at JHipsterClientGenerator.spawnCommand.spawnCommandSync (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\actions\spawn-command.js:35:16)
    at JHipsterClientGenerator.end (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\generators\client\index.js:428:16)
    at Object.<anonymous> (C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1091:23)
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:26:19
    at C:\Users\adhiyaman.muthu\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1092:9
    at new Promise (<anonymous>) {
  shortMessage: 'Command failed with exit code 4294963238: npm run clean-www',
  command: 'npm run clean-www',
  escapedCommand: 'npm run clean-www',
  exitCode: 4294963238,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

D:\5) Jhipster\firstapp>./mvnw
'.' is not recognized as an internal or external command,
operable program or batch file.

D:\5) Jhipster\firstapp>npm start

> firstapp@0.0.1-SNAPSHOT start
> npm run webapp:dev --

npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path D:\5) Jhipster\firstapp
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adhiyaman.muthu\AppData\Local\npm-cache\_logs\2022-08-16T15_06_04_528Z-debug-0.log

**Comment by mraible** [comment]
What version of JHipster are you using? It'd be a lot easier for us to help you if you filled out the template when creating an issue.

**Comment by lucarota** [comment]
Hi,
I am not OP, but I have the same problem using JHipster 7.9.2 and 7.9.0. 
Using JHipster 7.8.1 everything is fine.

**Comment by mraible** [comment]
Should be fixed in 7.9.2. Please re-open and include your JDL or `.yo-rc.json` to reproduce.
