### ISSUE TITLE
App regeneration from JDL conflicts on whole file in case of contect and and line ending (LF -> CRLF) change

### ISSUE THREAD

**Issue by bendeguz-szatmari** [jhipster/generator-jhipster#19461]
##### **Overview of the issue**

Below you can find an example for the issue for my typescript model file.

One line change was made in the model file (settlement property's type):

Marked for removing in diff mode:
```
import dayjs from 'dayjs/esm';
import { IProject } from 'app/entities/project/project.model';
import { IPlan } from 'app/entities/plan/plan.model';
import { ISettlement } from 'app/entities/settlement/settlement.model';
import { IUserExtra } from 'app/entities/user-extra/user-extra.model';

export interface ITender {
  id: number;
  createTimestamp?: dayjs.Dayjs | null;
  lastUpdateTimestamp?: dayjs.Dayjs | null;
  submissionTimestamp?: dayjs.Dayjs | null;
  submitted?: boolean | null;
  active?: boolean | null;
  project?: Pick<IProject, 'id'> | null;
  plan?: Pick<IPlan, 'id'> | null;
  settlement?: ISettlement | null; // <----------------------- changed line
  contactPerson?: Pick<IUserExtra, 'id'> | null;
}

export type NewTender = Omit<ITender, 'id'> & { id: null };
```

Marked for adding

```
import dayjs from 'dayjs/esm';
import { IProject } from 'app/entities/project/project.model';
import { IPlan } from 'app/entities/plan/plan.model';
import { ISettlement } from 'app/entities/settlement/settlement.model';
import { IUserExtra } from 'app/entities/user-extra/user-extra.model';

export interface ITender {
  id: number;
  createTimestamp?: dayjs.Dayjs | null;
  lastUpdateTimestamp?: dayjs.Dayjs | null;
  submissionTimestamp?: dayjs.Dayjs | null;
  submitted?: boolean | null;
  active?: boolean | null;
  project?: Pick<IProject, 'id'> | null;
  plan?: Pick<IPlan, 'id'> | null;
  settlement?: Pick<ISettlement, 'id'> | null; // <----------------------- should be the only line that is conflicting
  contactPerson?: Pick<IUserExtra, 'id'> | null;
}

export type NewTender = Omit<ITender, 'id'> & { id: null };
```

##### **Motivation for or Use Case**

It is hard to see the real difference between the old and the new file.

##### **Reproduce the error**

1. Generate app from JDL (files are generated with LF ending)
2. Change one line in a model file for example.
3. Change line ending type to CRLF
4. Rerun app generation
5. Choose show difference option in command line

##### **Suggest a Fix**

Handle line ending change in diff mode or leave line ending "as-is" upon regeneration.

##### **JHipster Version(s)**

v7.9.0

##### **JHipster configuration**

openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Microsoft-25199 (build 11.0.12+7, mixed mode)

git version 2.33.0.windows.2

node: v16.16.0

npm: 8.17.0

##### **Browsers and Operating System**

Windows 10 Pro 21H2

##### **IDE**

Visual Studio Code
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
What is your setting for git and line endings? In particular `core.autocrlf` setting?

**Comment by bendeguz-szatmari** [comment]
It is set to true:
```
[core]
	autocrlf = true
```

**Comment by WizMe-M** [comment]
I'm sorry, where does this setting appear?

> It is set to true:
> 
> ```
> [core]
> 	autocrlf = true
> ```
