### ISSUE TITLE
Add sonar report to PRs.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#19467]
##### **Overview of the feature request**

Add sonar reports to PRs to avoid regressions.
It's not possible to use sonar cloud due to token restrictions.
We need to implement our own solution using sonar at docker.

##### **Motivation for or Use Case**

Keep the generated code quality high.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Adding bug bounty to this as we seem to always find Sonar issues after the fact. 

Would adding [`eslint-plugin-sonar`](https://github.com/SonarSource/eslint-plugin-sonarjs) help us catch these issues sooner?

**Comment by gmarziou** [comment]
Which code do you want to analyze on PRs? Generated code or the generator code itself? 

Generated code means a lot of sonar invocations on each CI project.

**Comment by mshima** [comment]
> Which code do you want to analyze on PRs? Generated code or the generator code itself?

Generated code

> Generated code means a lot of sonar invocations on each CI project.

The idea is to keep limited to ngx-default for now.
It’s the only one we have sonarcloud.

We already generate the previous (main) code every time.
The idea is:
- cache junit/maven results at main.
- load junit/maven results at PRs.
- run sonar at loaded results.
- run sonar at new code results.
- should reports at console and fail when new issues is found.

**Comment by pascalgrimaud** [comment]
One suggestion would be to have a look at this folder: https://github.com/jhipster/jhipster-lite/tree/main/tests-ci and specially this script [sonar.sh](https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/sonar.sh)

**Comment by zhyd1997** [comment]
Import the repo into [Sonar Cloud](https://sonarcloud.io/) and it will works automatically:

1. Analyze default branch firstly (automatically).
<img width="1440" alt="Screenshot 2023-04-29 at 19 44 15" src="https://user-images.githubusercontent.com/31362988/235300751-418df511-58a6-41d6-80d9-d2a4893eb914.png">

2. Every linked PR will be analyzed automatically, and commented the report:
see https://github.com/zhyd1997/generator-jhipster/pull/4#issuecomment-1528768481

<img width="691" alt="Screenshot 2023-04-29 at 19 45 31" src="https://user-images.githubusercontent.com/31362988/235300775-d5c94c06-b278-42d6-bc67-855765ca2721.png">

**Comment by pascalgrimaud** [comment]
Thanks for your suggestion @zhyd1997 
But the last time I tried, it doesn't detect the code smells. See my try: https://github.com/jhipster/jhipster-lite/pull/374

So it will always show false positive, that's why in JHipster Lite project, I prefer using a stable sh script to do the job

**Comment by zhyd1997** [comment]
Hi @pascalgrimaud 

It works now!

https://github.com/zhyd1997/generator-jhipster/pull/4#issuecomment-1528773778

**Comment by pascalgrimaud** [comment]
Oh, I'll give it a try to JHLite repository
Thanks @zhyd1997 :-)))

**Comment by pascalgrimaud** [comment]
For your information, just tested it this morning, and it's still broken.
See my try here: https://github.com/jhipster/jhipster-lite/pull/6131

**Comment by zhyd1997** [comment]
Update:  https://github.com/jhipster/jhipster-lite/pull/6131#issuecomment-1530996564
