### ISSUE TITLE
 JDL import fails on "Class constructor GAstVisitor cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#19486]
##### **Overview of the issue**

It seems JDL parsing is broken.

Several users have reported it on stackoverflow:

https://stackoverflow.com/questions/73422380/cannot-import-jdl-file-using-jhipster

##### **Reproduce the error**

Generate a monolith then import a simple JDL:

```
entity Product {
	Name String
}
```

The JDL parsing fails:

```
jhipster jdl app.jdl
Welcome to JHipster v7.9.2

ERROR! Class constructor GAstVisitor cannot be invoked without 'new'
TypeError: Class constructor GAstVisitor cannot be invoked without 'new'
    at new DslMethodsCollectorVisitor (D:\projets\jhipster-projects\issues\note\node_modules\generator-jhipster\node_modules\chevrotain\lib\src\parse\parser\traits\looksahead.js:107:47)
    at Object.<anonymous> (D:\projets\jhipster-projects\issues\note\node_modules\generator-jhipster\node_modules\chevrotain\lib\src\parse\parser\traits\looksahead.js:148:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (D:\projets\jhipster-projects\issues\note\node_modules\generator-jhipster\node_modules\chevrotain\lib\src\parse\parser\parser.js:34:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

```

##### **JHipster configuration**
INFO! Switching to JHipster installed locally in current project's node repository (node_modules)

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v7.9.2

##### **JHipster Version(s)**

```
note@0.0.0 D:\projets\jhipster-projects\issues\note
`-- generator-jhipster@7.9.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "note",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1661003750696,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.2",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "microfrontend": false,
    "microfrontends": [],
    "monorepository": true,
    "nativeLanguage": "fr",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": true,
    "skipCommitHook": true,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.19.0, JRE 14 Windows 10 amd64-64-Bit Compressed References 20200318_5 (JIT enabled, AOT enabled)
OpenJ9   - 0133ba037
OMR      - 1c04e0ef9
JCL      - a73be60649 based on jdk-14+36)

git version 2.30.0.windows.2

node: v14.17.3

npm: 7.12.0

Docker version 20.10.17, build 100c701

docker-compose version 1.29.2, build 5becea4c

Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
I’ve posted at chevrotain repository https://github.com/Chevrotain/chevrotain/issues/1845

**Comment by mshima** [comment]
Should be resolved.
