### ISSUE TITLE
Missing i18n keys causing translation-not-found errors in the admin health UI

### ISSUE THREAD

**Issue by mplawley** [jhipster/generator-jhipster#19491]
##### **Overview of the issue**

Two missing i18n keys are causing `translation-not-found` errors in the admin health page:

![i18n-bug-screenshot](https://user-images.githubusercontent.com/6279541/185812991-19f48ef7-e59f-4b65-af15-aa56467d605f.jpg)

##### **Motivation for or Use Case**

The admin health page should not have translation-not-found errors.

##### **Reproduce the error**

- Generate a new application as per the `jhipster info` output below. Note especially the affirmative response on the generation of the admin UI and on internationalization.
- Navigate to the admin health page and notice the following `translation-not-found` errors as per the screenshot above.

##### **Related issues**

This is of the `theme:i18n` label category.

##### **Suggest a Fix**

See my PR: https://github.com/jhipster/generator-jhipster/pull/19489

`jhipster info` output:

Welcome to JHipster v7.9.2

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
i-18-n-bug-repro@0.0.1-SNAPSHOT /Users/marklawley/developer/i18n-bug-repro
└── generator-jhipster@7.9.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "i18nBugRepro",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1661119569506,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.2",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "ko", "es"],
    "messageBroker": false,
    "microfrontend": false,
    "microfrontends": [],
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment Homebrew (build 18.0.2+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.2+0, mixed mode, sharing)

git version 2.32.1 (Apple Git-133)

node: v16.16.0

npm: 8.11.0

Docker version 20.10.17, build 100c701

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**

Tested on macOS 12.4 on Chrome Version 104.0.5112.79 (Official Build) (arm64).

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I can confirm this is an issue. I've seen it recently. I believe it happens because the keys are tied to service discovery and they shouldn't be.

**Comment by mshima** [comment]
I've managed to reproduce, but the error is that spring-cloud(-started) is been included as dependency, when it should not.
