### ISSUE TITLE
Sponsor bug

### ISSUE THREAD

**Issue by Casinoburst** [jhipster/generator-jhipster#19515]
hi guys, 

Started bronze sponsor for uudetkasinot.com and spinsify.com/uk, it told me to get a link and logo on jhipster, its been a week and they are not added, can you pls do that? 

Thanks

**Comment by atomfrede** [comment]
We get the data from the opencollective api. I guess this is you? So I don't see any issue here.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/203401/186256625-d54fdb77-a0b7-40de-9db4-e9bbc5c40427.png">

**Comment by Casinoburst** [comment]
Its for the sites uudetkasinot.com and spinsify.com, also on opencollective but different account.
________________________________
Från: Frederik Hahne ***@***.***>
Skickat: den 23 augusti 2022 22:13
Till: jhipster/generator-jhipster ***@***.***>
Kopia: John Clark ***@***.***>; Author ***@***.***>
Ämne: Re: [jhipster/generator-jhipster] Sponsor bug (Issue #19515)


We get the data from the opencollective api. I guess this is you? So I don't see any issue here.
[image]<https://user-images.githubusercontent.com/203401/186256625-d54fdb77-a0b7-40de-9db4-e9bbc5c40427.png>

**Comment by atomfrede** [comment]
They are not returned by the open collective api yet. Not sure if there is something we can do. Will checkif the api allows paging or so and we have exceeded the default number, but at least the uri says "all"

**Comment by atomfrede** [comment]
Playing around with the raw api does not return the other sponsors. Seems like an open collective issue

**Comment by Casinoburst** [comment]
ok cool, do you have any contact to open? Any support mail etc?
________________________________
Från: Frederik Hahne ***@***.***>
Skickat: den 24 augusti 2022 11:13
Till: jhipster/generator-jhipster ***@***.***>
Kopia: John Clark ***@***.***>; Author ***@***.***>
Ämne: Re: [jhipster/generator-jhipster] Sponsor bug (Issue #19515)


Playing around with the raw api does not return the other sponsors. Seems like an open collective issue

**Comment by Casinoburst** [comment]
ok cool, happy to sponsor a "free" month but ofc I thought as it stood that we will get listed after the donation. So if you can check that would be good thanks!
________________________________
Från: Frederik Hahne ***@***.***>
Skickat: den 24 augusti 2022 11:03
Till: jhipster/generator-jhipster ***@***.***>
Kopia: John Clark ***@***.***>; Author ***@***.***>
Ämne: Re: [jhipster/generator-jhipster] Sponsor bug (Issue #19515)


They are not returned by the open collective api yet. Not sure if there is something we can do. Will checkif the api allows paging or so and we have exceeded the default number, but at least the uri says "all"
