### ISSUE TITLE
Error 404 in production with MySQL

### ISSUE THREAD

**Issue by alfredorueda** [jhipster/generator-jhipster#1954]
Hello,

We made a project using the following UML diagram.
![image](https://cloud.githubusercontent.com/assets/8808034/9568955/9750a3ac-4f5a-11e5-82d7-163310ce5f8b.png)

The project works perfectly well with the dev profile using H2 Database. Here is a link of our repository: https://github.com/alfredorueda/Blog

When we switched to "prod" profile with MySQL database a html 404 error is showed in the browser.
![image](https://cloud.githubusercontent.com/assets/6538899/9568937/3d7bdc52-4f5a-11e5-8858-b2a8c9c46208.png)

Here is the link of our repo with the error: https://github.com/alfredorueda/Blog/tree/error-prod

![image](https://cloud.githubusercontent.com/assets/8808034/9568987/f174d230-4f5b-11e5-825e-ea36ad3b941f.png)

It seems that our DB is created and it has initial data (for instance all demo users).

Thank you very much, I'm really impressed with this tool.

**Comment by moifort** [comment]
I try your project on a mysql BDD, in production profile, it's run for me. What did you have in the output logs of Jhipster?

If your problem persist give us more informations, everything is detail here:
https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue

**Comment by warrendeleon** [comment]
Hello,

I downloaded the project and I have the same issue. Here is my logs:

https://drive.google.com/file/d/0BxGBKydB0Lnpa0hhdHZiT0lJTHc/view?usp=sharing

![image](https://cloud.githubusercontent.com/assets/6538899/9569546/f357e066-4f6e-11e5-81f1-e0528aa00568.png)

I'm using Ubuntu 15.04 with:

	jhipster@jhipster-VM:~/Developer/IntelliJ_IDEA_workspace/Blog$ mysql --version
	mysql  Ver 14.14 Distrib 5.6.25, for debian-linux-gnu (x86_64) using  EditLine wrapper
	
	jhipster@jhipster-VM:~/Developer/IntelliJ_IDEA_workspace/Blog$ npm --version
	2.11.3
	
As @alfredorueda said the DB is created and It have data:
![image](https://cloud.githubusercontent.com/assets/6538899/9569602/2b3d9682-4f70-11e5-8b33-f58274a8b06e.png)

I don't know why I'm also getting the html 404 page.

Thank you for your support.

**Comment by moifort** [comment]
Sorry by logs I mean server side (java application).
@warrendeleon If I refer by yours network console, it's look like more a problem in the server side, maybe your application failed to start after initialize the DB.

**Comment by warrendeleon** [comment]
Hello @moifort,

I added a link with my logs: http://warrendeleon.com/docs/log.txt

![image](https://cloud.githubusercontent.com/assets/6538899/9569676/44ca88ec-4f72-11e5-9b75-2f0476ae23aa.png)

Thank you for your help.

**Comment by moifort** [comment]
my bad, I will take a look.

**Comment by warrendeleon** [comment]
Thank you @moifort, I'll apreciate that.

**Comment by moifort** [comment]
Just to be sure do you have a generated directory `src\main\webapp\dist` with files inside?

When you make a `mvn -Pprod package` do you have error during the generation of your app?

Try to update all your app, this is my version:
- node version : 0.12.2
- npm version : 2.14.1
- bower version : 1.5.2
- grunt-cli v0.1.13
- grunt v0.4.5

Otherwise I don't know why it's work for me but not for you :(.

**Comment by jdubois** [comment]
I cloned your repo and ran your app normally in production (`mvn -Pprod spring-boot:run`) and had no issue at all. It's working very well, on the first run!
You either didn't install your NPM modules correctly (check your logs), or put a Web server in front of JHipster (with an error in your load balancer), which are quite usual issues.
