### ISSUE TITLE
Future of heroku support

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#19551]
##### **Overview of the issue**

> we will be phasing out our free plan for Heroku Dynos, free plan for Heroku Postgres, and free plan for Heroku Data for Redis®, as well as deleting inactive accounts.

See https://blog.heroku.com/next-chapter

Personally I really love our heroku support and I guess @mraible use it a lot for demos and I think also in the jhipster minibook. But with free dynos and free postgres gone I am not sure we should (or even can) support the heroku subgen as we do right now.

##### **Motivation for or Use Case**

No accidental cost for our users.

##### **Related issues**

* https://github.com/jhipster/generator-jhipster/issues/18793

##### **Suggest a Fix**

Remove heroku support at least for V8 or even for V7 too.

**Comment by emilpaw** [comment]
Considering that according to JHipster Statistics Heroku is with 50% usage by far the most popular cloud deployment option I don't think the support should be dropped soon.

Dropping it could be considered again if Heroku's market share plummets after they stop offering free products.

In the docs for Google Cloud the user is also informed to make sure they are using a free tier. I think adding a warning about the costs with Heroku to the docs might be enough.

**Comment by emilpaw** [comment]
Aren't other cloud deployment options also not free, for example, AWS?

**Comment by atomfrede** [comment]
Thats true, but for heroku (more or less) we promise to only use free options/tiers. With heroku sunsetting free dynos I think there is no easy, free deployment option left (especially for demonstrations purposes etc).

**Comment by atomfrede** [comment]
In particular this also means we can't test and maintain it anymore. For AWS it was contributed externally from a user having AWS access, for glcoud we used our own free credits to test it out, but not everyone has access of course, so the circle of maintainers are pretty limited.

**Comment by mraible** [comment]
With an annual budget of 150,000 USD, I think we can afford to pay for testing on Heroku and other providers. 😉

https://opencollective.com/generator-jhipster

**Comment by atomfrede** [comment]
True, but I am just thinking of the organizational issues :D Right now I can startup my vs code at any time, deploy an app for testing to heroku and fix a bug or so.

**Comment by mraible** [comment]
Is there a free alternative that allows you to deploy Java apps? Maybe Digital Ocean, but I think they only offer a 30-day free trial.

**Comment by atomfrede** [comment]
Personally I use dokku, but of course the serve must be paid. The digital ocean app platform pricing I never really understood :) And I think the free tier is for static websites only. Databases cost always

**Comment by zhyd1997** [comment]
Hi 👋

Maybe [Azure ](https://azure.microsoft.com/en-us/free/) is a good choice 👀.

**Comment by mraible** [comment]
Azure seems to be only free for 30 days. From the website linked above:

> Start with $200 Azure credit
> You’ll have 30 days to use it—in addition to free services.

**Comment by mraible** [comment]
I think we should keep Heroku's support as I still think we'll be able to get free credits for testing and students will be able to get free credits too.

From the blog post linked in this issue's description:

> Today, we're announcing:
> * Student and nonprofit program: an upcoming program to support students and nonprofits in conjunction with our nonprofit team.
> * Open source support: we will continue to contribute to open source projects, notably [Cloud Native Buildpacks](https://buildpacks.io/). We will be offering Heroku credits to select open source projects through Salesforce’s Open Source Program Office.

It'd also be cool to talk to the folks at Heroku (ping @jkutner) to see if we can get credits to hand out at conferences after we do demos with Heroku.

**Comment by zhyd1997** [comment]
> Azure seems to be only free for 30 days. From the website linked above:
> 
> > Start with $200 Azure credit
> > You’ll have 30 days to use it—in addition to free services.

Maybe it means have 30 days to use the $200 credit? 👀

**Comment by atomfrede** [comment]
> I think we should keep Heroku's support as I still think we'll be able to get free credits for testing and students will be able to get free credits too.
> 
> From the blog post linked in this issue's description:
> 
> > Today, we're announcing:
> > 
> > * Student and nonprofit program: an upcoming program to support students and nonprofits in conjunction with our nonprofit team.
> > * Open source support: we will continue to contribute to open source projects, notably [Cloud Native Buildpacks](https://buildpacks.io/). We will be offering Heroku credits to select open source projects through Salesforce’s Open Source Program Office.
> 
> It'd also be cool to talk to the folks at Heroku (ping @jkutner) to see if we can get credits to hand out at conferences after we do demos with Heroku.

Okay, sounds good. I will prepare the documentation already to reflect the price changes.

**Comment by deepu105** [comment]
https://github.com/jhipster/generator-jhipster/issues/19112

**Comment by mshima** [comment]
Heroku generator has been updated and will be kept for now.
Seems heroku still a good alternative for now.
Closing since I think there is nothing left to discuss.
