### ISSUE TITLE
webapp:test target fails on minimal monolit application when generated after 20 August 2022

### ISSUE THREAD

**Issue by johan-westin-private** [jhipster/generator-jhipster#19552]
INFO! Switching to JHipster installed locally in current project's node repository (node_modules)

Welcome to JHipster v7.9.2

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jh-minimal@0.0.1-SNAPSHOT /projects/it/users/jmwpa/var/dev/git_repository/learn/jh_792
└── generator-jhipster@7.9.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "jh_minimal",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1661428449686,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.2",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "mariadb",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": ["websocket:spring-websocket"],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": "spring-websocket",
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment (build 17.0.4+8-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.4+8-Ubuntu-122.04, mixed mode, sharing)

git version 2.34.1

node: v16.14.0

npm: 8.18.0

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤  by @oktadev.

##### **Overview of the issue**

The webapp:test target fails on minimal monolit application.

This is one example:

$ ./npmw run webapp:test
...
...
FAIL  src/main/webapp/app/admin/logs/logs.service.spec.ts (832 MB heap size)
  ● Logs Service › Service methods › should change log level

    Expected one matching request for criteria "Match method: POST, URL: (any)", found none.

      25 |       service.changeLevel('main', 'ERROR').subscribe();
      26 |
    > 27 |       const req = httpMock.expectOne({ method: 'POST' });
         |                            ^
      28 |       expect(req.request.body).toEqual({ configuredLevel: 'ERROR' });
      29 |     });
      30 |   });

      at HttpClientTestingBackend.expectOne (node_modules/@angular/common/fesm2020/http/testing.mjs:288:19)
      at src/main/webapp/app/admin/logs/logs.service.spec.ts:27:28
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:409:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3830:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:408:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:169:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4331:34)

##### **JHipster Version(s)**

7.9.2

Have seen the same issue in 7.7.0 and 7.8.1 when generate app lately.
The same app generated 27 Feb 2022 using 7.7.0 works fine.

##### **JHipster configuration**

[jh-7.9.2-files.zip](https://github.com/jhipster/generator-jhipster/files/9432123/jh-7.9.2-files.zip)

##### **Browsers and Operating System**

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
There was a transitional dependency breaking change the fix is https://github.com/jhipster/generator-jhipster/commit/5a297792ac13e684e55bb367468e92124cca6389

**Comment by johan-westin-private** [comment]
Hi,

Thanks for the work around!
It works great with my own URL as well :-).

Best regards,
Johan Westin
