### ISSUE TITLE
Fix Security hot spots as identified by Sonar

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#19555]
Related to https://github.com/jhipster/generator-jhipster/pull/19531#issuecomment-1229021895:

##### **Overview of the issue**

There are some security hot spots that could use repair

<img width="1282" alt="Screen Shot 2022-08-26 at 16 48 04" src="https://user-images.githubusercontent.com/17892/187000214-1ab9e3dc-e83f-4e6f-8618-c1f2fb586af5.png">

<img width="1275" alt="Screen Shot 2022-08-26 at 16 48 28" src="https://user-images.githubusercontent.com/17892/187000222-62df2d4a-2b5e-46f5-b3df-08cfa37e5ba7.png">

##### **Motivation for or Use Case**

Better security is better for everyone.

##### **Reproduce the error**

Generate a JHipster app with Sonar, then run:

```
./gradlew -Pprod clean check jacocoTestReport sonarqube
```

##### **Related issues**

https://github.com/jhipster/generator-jhipster/pull/19531

##### **Suggest a Fix**

Not sure.

##### **JHipster Version(s)**

`main` branch

**Comment by emilpaw** [comment]
I think none of these two are an issue.

1. The data comes from the server and the regex itself is fine.
2. This is formatting for file sizes where the input is always a base64 encoded string so there is no way to inject malicious regex there.

**Comment by mraible** [comment]
In that case, can we tell Sonar to ignore these issues somehow?

**Comment by mraible** [comment]
Maybe we should add the [`eslint-plugin-sonar`](https://github.com/SonarSource/eslint-plugin-sonarjs) to catch these issues sooner?

**Comment by qmonmert** [comment]
@DanielFran https://opencollective.com/generator-jhipster/expenses/91996 :)

**Comment by DanielFran** [comment]
@qmonmert approved

**Comment by qmonmert** [comment]
@DanielFran thanks

**Comment by mraible** [comment]
This does fix the problem mentioned in this issue. However, there are still 16 code smells.

[JHipster code smells.pdf](https://github.com/jhipster/generator-jhipster/files/9440073/JHipster.code.smells.pdf)

**Comment by qmonmert** [comment]
@mraible good, maybe open an other issue

**Comment by qmonmert** [comment]
There are 184 code smells on the main branch

**Comment by mraible** [comment]
Looks great now @qmonmert, nice work!

<img width="1272" alt="Screen Shot 2022-08-28 at 13 02 16" src="https://user-images.githubusercontent.com/17892/187090411-0265fea0-ad00-4f56-960e-de89d7d10f01.png">

**Comment by qmonmert** [comment]
@mraible 👍
