### ISSUE TITLE
Unauthorized access 

### ISSUE THREAD

**Issue by ikajinic** [jhipster/generator-jhipster#1956]
There is an issue with partial access to pages that the user is not authorized to acces. For example, user with role ROLE_USER can access (partially) pages such as metrics, health etc. by going directly to their URL. Spring will reject data access which is good, but the page is still shown instead of sending the user to "accessdenied" state.

To reproduce the issue, log in as default "user" and try to go to: http://localhost:8080/#/metrics 

Issue is principal.service.js, function "isInAnyRole" which does this:

if (this.isInRole(roles[i])) {
     return true;
}

since this.isInRole() function returns promise, this "if" check will actually be checking if this.isInRole(roles[i]) !== null && this.isInRole(roles[i]) !== undefined which it is and it will return true.

To fix this, above check could be replaced with something like this:

if (_identity.roles.indexOf(roles[i]) !== -1) {
      return true;
}

**Comment by deepu105** [comment]
Can you propose a PR

**Comment by gzsombor** [comment]
You should configure these kind of access restrictions on the module configurations, with the $stateProvider - for example : 

            $stateProvider
                .state('health', {
                    parent: 'admin',
                    url: '/health',
                    data: {
                        roles: ['ROLE_ADMIN'],
                        pageTitle: 'health.title'
                    },

**Comment by ikajinic** [comment]
Issue was not with $stateProvider, rather with the check of user roles which was done in principal.service.js. I've submitted a pull request <a href="https://github.com/jhipster/generator-jhipster/pull/1957">#1957</a>
