### ISSUE TITLE
Jhipster / Hazelcast project fails to start when packaged as WAR 

### ISSUE THREAD

**Issue by NickGDev** [jhipster/generator-jhipster#1958]
Error on Tomcat startup:
 Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is java.lang.IllegalArgumentException: PortableFactory[-23] is already registered! com.hazelcast.mapreduce.impl.MapReducePortableHook$1@66d83be5 ->

This issue has been previously reported and determined to be a dependency version conflict, i have checked my the generated maven configuration and lib folder in my WAR and cannot see mixed versions of hazelcast / spring / hibernate jars. 

I have also tried troubleshooting this issue by placing an thread-safe check during the instantiation of  the Hazelcast instance in the CacheConfiguration class but this doesn't fix the error or just causes a null pointer. Ehcache is not experiencing the same issue and switching to hazelcast 3.2.5 does not resolve the issue.

I have created a project from the latest jhipster generator and uploaded my error log

steps to reproduce:
Mac OS X / JDK 8_51 (x64) / Maven 3.3.3

mvn clean package
java -jar target/jhipster-0.0.1-SNAPSHOT.war

source project:
https://github.com/NickGDev/jhipster-hazelcast-websockets

error:
http://pastebin.com/3J2x8dg4

previous reports:
http://stackoverflow.com/questions/28028637/upgrading-hazelcast-to-3-2-5-results-in-portablefactory-19-is-already-regis

**Comment by deepu105** [comment]
Nick, I have multiple huge JHipster applications with hazelcast running in
tomcat and jboss eap as war for months now and I never had this issue,
though i haven't used the hazelcast cluster option yet. But from ur case it
doesn't look that way either can you provide your yo-rc file?

**Comment by NickGDev** [comment]
Hi Deepu, thanks for the quick response! I'm actually seeing the problem when using a newly generated project from the latest Jhipster generator (updated 31-08-15). I have a feeling there is a dependency compatibility issue with some of the jars used in the latests generator (eg Hikari's version was updated from 2.3.7 -> 2.4.0). For some reason the issue only affects the project when it is packaged as a WAR (possible issue with maven lib plugin config?) 

Here's the yo-rc file for the git project referenced http://pastebin.com/qPN2QEfS

**Comment by deepu105** [comment]
I also have all the latest jar as per v 2.20 only difference is im using
gradle. Anyway ill take a look when i find some time

**Comment by desposi1** [comment]
I am also having this problem. I am working around it right now by just running `mvn spring-boot:run -Pprod` in my staging environment, but I need to deploy a .WAR file when we start pushing to production.

**Comment by deepu105** [comment]
@NickGDev can you try to reproduce this with a fresh app using latest JH version, as Im unable to reproduce on new app
