### ISSUE TITLE
It throws org.hibernate.HibernateException: identifier of an instance of c.q.i.City was altered from 1 to 2814 when using patch rest api

### ISSUE THREAD

**Issue by scyllor** [jhipster/generator-jhipster#19598]
##### **Overview of the issue**
it throws org.hibernate.HibernateException: identifier of an instance of c.q.i.City was altered from 1 to 2814 when using patch rest api to update a many to one relationship with dto * with mapstruct enabled

Here use same entity in hibernate session, but change the id if we want to partial update a relationship
![image](https://user-images.githubusercontent.com/2325287/187476982-f6d3092c-25ee-43c6-ad2a-beff2e8f0ce2.png)
![image](https://user-images.githubusercontent.com/2325287/187447905-57e2ada2-fc27-4ffd-8a8c-3622e6a090eb.png)
![image](https://user-images.githubusercontent.com/2325287/187448176-e438af41-1c45-453c-ad52-4ac8ebb8ea82.png)
![image](https://user-images.githubusercontent.com/2325287/187448433-523ed07a-1f6b-4934-8e88-57d4713d72bb.png)

##### **Motivation for or Use Case**

![image](https://user-images.githubusercontent.com/2325287/187448546-f3be9db3-a638-41c8-a689-afecf1ddc402.png)

##### **Reproduce the error**
![image](https://user-images.githubusercontent.com/2325287/187448565-59afe9bc-3621-4fe8-b0c6-cca06881e341.png)

##### **Suggest a Fix**
use mapper twice.
cloning a new from entity from hibernate and copy non null columns from incoming DTO to it.(even use deepclone for partialUpdate in mapper, the reference wont be changed)
![image](https://user-images.githubusercontent.com/2325287/187471329-24cf7653-95d6-42d5-8b36-846675effa5b.png)

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Priyan5huThakur** [comment]
i am getting this error in my bank and address entity where i am updating bank with its address

**Comment by Priyan5huThakur** [comment]
{
  "branchId":"0f588f50-4df2-4f8f-bd9e-b24aad25bcc8",
  "name": "jfhfj",
  "swiftCode": " SBINBBXXX",
  "branchFullName":"SBI Branch main bazar",
  "ifscCode": "SBI001",
  "addressId": "30b63eba-ebe4-4778-a061-b1261d6ad97d",
    "addressArr": {
    "id": "30b63eba-ebe4-4778-a061-b1261d6ad97d",
    "description": "Address of SBI bank main branch",
    "line1": "main market",
    "line2": "ground floor",
    "line3": "Building 8",
    "postalCode": "16001",
    "cityId": "13399076-5343-430e-a22a-9a60637c8906",
    "stateId": "62fdc367-8184-4675-be63-66dbaf970927",
    "countryId": "2c947c34-326b-4b89-bff3-a9cc637a40a3",
    "entityType": "BANK",
    "addressTypeId": "bc6bc6e9-1e22-4c83-8b02-b2843d3c447c",
    "isPrimary": true,
    "latitude": 40.7128,
    "longitude": -74.006
  }
}

**Comment by Priyan5huThakur** [comment]
@Override
    public BankDTO updateBank(UUID id, BankDTO bankDTO) {

        logger.info("Starting updateBank method for bank ID: {}", id);

        Optional<Bank> bankOptional = bankRepository.findById(id);
        if (bankOptional.isPresent()) {
            Bank bank = bankOptional.get();
            logger.info("Banks found: {}", bank.toString());

            AddressDTO addressDTO = bankDTO.getAddressArr();
            UUID getAddressId = bankDTO.getAddressId();

            logger.info("Looking for address with ID: {}", getAddressId);
            Optional<Address> addressOptional = addressRepository.findById(getAddressId);
            if (addressOptional.isPresent()) {
                Address existingAddress = addressOptional.get();
                logger.info("Address found: {}", existingAddress);

                logger.debug("Mapping addressDTO to existingAddress");
                modelMapper.map(addressDTO, existingAddress);

                logger.info("Saving updated address");
                Address savedAddress = addressRepository.save(existingAddress);
                modelMapper.map(savedAddress, addressDTO);
            } else {
                logger.warn("Address not found with ID: {}", getAddressId);
            }

            logger.debug("Mapping bankDTO to bank");
            modelMapper.map(bankDTO, bank);

            logger.info("Saving updated bank");
            Bank updatedBank = bankRepository.save(bank);

            BankDTO updatedBankDTO = modelMapper.map(updatedBank, BankDTO.class);
            logger.info("Successfully updated bank with ID: {}", id);
            return updatedBankDTO;
        } else {
            logger.warn("Banks not found with ID: {}", id);
        }

        logger.info("Returning input bankDTO as no update was performed");
        return bankDTO;
    }

**Comment by bjbmiguel** [comment]
Hi @Priyan5huThakur ,

is this issue has been solved ?

I have this same issue and i am still try to solve it.

Caused by: org.hibernate.HibernateException: identifier of an instance of ao.co.nmintegration.equation.api.sms.domain.model.District was altered from 1 to 9
