### ISSUE TITLE
Not Able to update Jhipster

### ISSUE THREAD

**Issue by maheshkaranjkar** [jhipster/generator-jhipster#1959]
Hi Guys,

 I am trying to update Jhipstre to latest version i. 2.20.0, but getiing following errors,

Request you to guide me in same so that I can use latest version.

following are the errors which I am getting.

<code>

C:\Users\355360>npm update -g generator-jhipster
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "generator-jhipster"
npm ERR! node v0.12.2
npm ERR! npm  v3.2.0
npm ERR! code ENOSELF

npm ERR! Refusing to install generator-jhipster as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\355360\npm-debug.log

</code>

Regards
Mahesh

**Comment by maheshkaranjkar** [comment]
Hi Guys,

I updated project using YO, 

Regards
Mahesh

**Comment by deepu105** [comment]
Assuming your issue is resolved?

**Comment by jdubois** [comment]
Yes @maheshkaranjkar said it's working now... I guess he had an error with his NPM installation.

**Comment by maheshkaranjkar** [comment]
Yes, Its working ... But faced so many issues . But I guess its not related to Jhipster as @jdubois said it might be issue with my NPM instalation.

Thanks for your help.
Regards
Mahesh Karanjkar
