### ISSUE TITLE
Newly created project won't compile (webapp)

### ISSUE THREAD

**Issue by marcuss** [jhipster/generator-jhipster#19604]
##### **Overview of the issue**
 With today's build, using a monolithic app, with no admin console, with mysql in memory, using Vue, no cache, session authentication, the generated project without changes does not build.

It fails with something identical to an old issue #4900

ERROR in ./src/main/webapp/content/scss/vendor.scss (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-7.use[1]!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-7.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-7.use[3]!./src/main/webapp/content/scss/vendor.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: shade-color(#f0f5fa, 50%) is not a color.

##### **Motivation for or Use Case**
I want to use JHipster for a simple project but I can not do it.

##### **Reproduce the error**
run mvn (in mac). and see the error.

run ./mvnw  (in windows) wait and see the error.

##### **Related issues**

The following issue seems very similar 
https://github.com/jhipster/generator-jhipster/issues/4900

##### **JHipster Version(s)**
7.9.2

##### **JHipster Version(s)**

```
beebank@0.0.0 /Users/marcuss/code/beebanck2
└── generator-jhipster@7.9.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "session",
    "baseName": "beebank",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "vue",
    "clientPackageManager": "npm",
    "clientTheme": "morph",
    "clientThemeVariant": "light",
    "creationTimestamp": 1661910952953,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.2",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "microfrontend": false,
    "microfrontends": [],
    "nativeLanguage": "es",
    "otherModules": [],
    "packageName": "co.beebank.app",
    "pages": [],
    "prodDatabaseType": "mysql",
    "reactive": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

```
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment (build 18.0.2.1+1-1)
OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

git version 2.33.0

node: v17.7.1

npm: 8.5.2

Docker version 20.10.17-rd, build c2e4e01

Docker Compose version v2.6.1


No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
```

##### **Browsers and Operating System**
Windows 10
Mac OS
 Both running latest Chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
I confirm the issue

**Comment by qmonmert** [comment]
error with theme `morph`, works with `darkly`

**Comment by mraible** [comment]
@qmonmert Is this something we should (and can) fix?

**Comment by qmonmert** [comment]
I opened an issue https://github.com/thomaspark/bootswatch/issues/1206 
I think it's not us

**Comment by mshima** [comment]
Maybe it’s not even an upstream bug.
We generate bootswatch@4 with bootstrap@5.
They should match.

**Comment by qmonmert** [comment]
`shade-color` is a Boostrap 5 function https://getbootstrap.com/docs/5.0/customize/sass/

<img width="826" alt="image" src="https://user-images.githubusercontent.com/9989211/187987240-c4d7900e-1dcf-4416-a1fe-70dec3782848.png">

but JHipster is still with Bootstrap 4

@marcuss you can switch your theme

**Comment by marcuss** [comment]
@qmonmert  sure, actually just read this I was off on weekend I'll let you know how it goes

**Comment by mshima** [comment]
I recommend downgrading to bootswatch@4

**Comment by marcuss** [comment]
@qmonmert @mshima  Everything works if I use another theme (try it Darkly), I did have an issue with my Node version tho (this one: https://github.com/jhipster/generator-jhipster-svelte/issues/1030) , but downgrading to 16 made it disappear.
