### ISSUE TITLE
Rest call successful without X-CSRF-TOKEN 

### ISSUE THREAD

**Issue by varunkumarm** [jhipster/generator-jhipster#1961]
I've created the application using default spring security option. 

I've just created the sample "author" entity. Below is the CURL command I got from the API section. 

curl -X GET --header "Accept: application/json" --header "X-CSRF-TOKEN: f2444850-ebb4-439c-ab28-3e4d59981087" "http://localhost:8080/api/authors/1"

However, I got a unauthorized message. 

{"timestamp":1441112477445,"status":401,"error":"Unauthorized","message":"Access Denied","path":"/api/authors/1"}

Now, I copied the JSESSIONID cookie value from request header in chrome dev tools and created a request as below, which successfully retrieves the corresponding author entity for me. 

curl -X GET --header "Accept: application/json" --cookie "JSESSIONID=DC42724928111B064C0E3B23B029F89D" "http://localhost:8080/api/authors/1" 

Is the curl statement provided in swagger api section wrong? Also, if the request is sent without the csrf token, why did it succeed? Shouldn't the server respond with unauthorized message when csrf token is not present?

**Comment by jdubois** [comment]
This is normal:

- On your first request, you don't have a sessionid, so you are not logged in -> this is why you are not authorized
- On the second request, you do a GET request, and Spring Security only do the check when you write something (REST-style, that normal, you are not writing so there is no need to check). Have a look at the Spring Security docs for more information on this. If you wish to test, do a POST request instead, without the CSRF token, you will be rejected!

**Comment by varunkumarm** [comment]
Thanks a lot for clearing my doubts.

The below example command given in the swagger ui is wrong then - not sure if that is a bug specific to jhipster though.

curl -X GET --header "Accept: application/json" --header "X-CSRF-TOKEN: f2444850-ebb4-439c-ab28-3e4d59981087" "http://localhost:8080/api/authors/1"

This example command piqued my interest as to how the server would authenticate/authorize the user with just a csrf token and without any sessionid. Thanks again for clarifying!!

**Comment by jdubois** [comment]
I didn't have a look at Swagger here, they probably have no idea about our authentication mechanism. Personally I do my CURL requests using the Chrome dev console (right click, copy as CURL)

Anyway thanks for pointing out this: it's really easy to have a security breach on this part, so all security audits, questions, doubts are warmly welcome!!!
