### ISSUE TITLE
New table naming strategy makes the tests fail on the sample application

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1962]
I just merged #1799 and I only tested the application with MySQL to see the new table names, and that was a huge mistake!!

So it makes the `mvn test` fail on the sample application https://github.com/jhipster/jhipster-sample-app

The error message is:

    Caused by: org.hibernate.HibernateException: Missing column: bankAccount_id in SAMPLEAPPLICATION.PUBLIC.OPERATION

@deepu105 I'm assigning this to you are you are the author of the PR, of course.

There is also one slight formatting issue: there are two lines after the "id" field.

**Comment by deepu105** [comment]
Ok ill take look I was doing a direct test may be i missed to add strategy
in test .yml

**Comment by deepu105** [comment]
as i doubted, it was missing in `application.yml` under test.
btw @jdubois i couldnt find the formatting issue you mentioned??
