### ISSUE TITLE
xxService.save(dto) claims to return "the persisted entity"; but it return a DTO.

### ISSUE THREAD

**Issue by jackpunt** [jhipster/generator-jhipster#19628]
##### **Overview of the issue**

xxService.save(dto) claims to return "the persisted entity"; but it return a DTO.

The generated source finishes with: 
`return xxMapper.toDto(xxInst);`
##### **Motivation for or Use Case**

Does not work as documented; I do not get a handle to the Entity.

##### **Reproduce the error**

Run any jhipster jdl --with-entity

##### **Suggest a Fix**

Either change the return to match the javadoc, or change the javadoc to match the code.

##### **JHipster Version(s)**

7.9.2

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jackpunt** [comment]
The generated 'Sevice' has a similar problem.
Is **says** it will return an Entity; but it is mapped to the DTO.

This makes it painful for those of us trying to learn/use JHipster, when the javadoc is wrong,
and we must continually refer to the source code to see what is really happening.

It would be **so** simple for y'all to align the javadoc with the actual interface.

```
   /**
     * Get one xx by id.
     *
     * @param id the id of the entity.
     * @return the entity.
     */
    @Transactional(readOnly = true)
    public Optional<XxtDTO> findOne(Long id) {
        log.debug("Request to get Xx : {}", id);
        return xxRepository.findById(id).map(xxMapper::toDto);
    }
```

**Comment by atomfrede** [comment]
Would you like to provide a PR?

**Comment by jackpunt** [comment]
Not clear to me what is the problem/solution...
Should the methods return an entity? or a DTO? 
Is it just a doc/synchronization problem?

If you confirm the cause/solution, then maybe I'd try...
[but then you would need to explain me where is all the code/tools/tests to make such a change...
  I did so much of my open source back in the last century (emacs-18/19 anyone?) ]

**Comment by atomfrede** [comment]
If you post your config I could tell you more. But I guess its really just documentation. The simplest configuration does not use service classes as such the entity is returned so most likely the javadoc does not reflect that.

**Comment by Tcharl** [comment]
I would say that returning the DTO is the right behavior, so the doc should be updated.

To mitigate what I said, It's sometimes useful to chain services and working on entity only while having the last service returning the DTO, so maybe a good pattern could be rely on package-protected method returning entities.
```
interface MyService {
MyDTO save(MyDTO myDTO);
}

class MyServiceImpl implements MyService {
public MyDTO save(MyDTO myDTO) {
return myMapper.toDTO(save(myMapper.toEntity(myDTO));
}

protected My save(My my) {
return myRepository.save(my);
}
}
```
