### ISSUE TITLE
Mapstruct Implementation assumes that all related entity has a DTO

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1963]
When we use mapstruct to generate DTO for an entity the generated code assumes that all child/parent relations also have DTO so if i use a mixed combination as below i get compile errors

1. Book - DTO
2. Author - no DTO

Ill post a sample config when i find time

**Comment by jdubois** [comment]
Yes, this is written [here](http://jhipster.github.io/using_dtos.html), but probably not clearly enough.

You need to have a graph or DTOs, you can't send a DTO linked to an entity to the front-end. So for me this is a logical limitation, but this needs to be explained better.

**Comment by deepu105** [comment]
Oops sorry didn't notice that. Shall i close this or should we add a
documentation label?

**Comment by jdubois** [comment]
Let me look again at the documentation and add something if necessary, then I will close it

**Comment by jdubois** [comment]
For me the documentation is enough, @deepu105 if you want something more detailed just ask me!

**Comment by deepu105** [comment]
As long as its documented its fine +1
