### ISSUE TITLE
Profile menus labels are not updated after login using react

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#19634]
##### **Overview of the issue**

On at least JWT (I'm using the react-default generator configuration), profile menus labels are not updated after login (they are always proposing to signin and so on.
Clicking on them provides the right behavior: using the button labelled with 'Register' let's the user updating his password...

##### **Motivation for or Use Case**

Describing the according call to action ^^

##### **Reproduce the error**

Generate the react-default jhipster sample
Login
Check the labels of the profile menu on top right

##### **JHipster Version(s)**
7.9.3

##### **Browsers and Operating System**

Firefox and Chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jelharou** [comment]
I noticed the same thing a while back (Windows 11/Opera).  It is the Account menu:
![image](https://user-images.githubusercontent.com/18337852/188449459-c876e46a-9521-4a5f-9377-7f3026420482.png)

**Comment by qmonmert** [comment]
Confirm bug
