### ISSUE TITLE
Add typings to generators tasks.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#19658]
##### **Overview of the feature request**

Typings is useful for development, it will improve blueprints and generator contributions.

<img width="305" alt="autocomplete" src="https://user-images.githubusercontent.com/1417183/188646496-790a57be-0f71-4f9e-98df-c192051c0456.png">

##### **Motivation for or Use Case**

Improve developer experience.

This won't help with ejs templates.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Not only for devs, but also for typescript migration!

**Comment by mshima** [comment]
Migrating generators to typescript is not a goal for v8. But can be done during v8 cycle.

**Comment by Tcharl** [comment]
Excellent, so many thanks for that

**Comment by mshima** [comment]
@DanielFran bug bounty claim https://opencollective.com/generator-jhipster/expenses/220549.

**Comment by DanielFran** [comment]
@mshima approved
