### ISSUE TITLE
Update JWT Authentication (without OAuth 2.0) by using Spring OAuth2 Resource Server instead of JJWT

### ISSUE THREAD

**Issue by SaiUpadhyayula** [jhipster/generator-jhipster#19689]
##### **Overview of the feature request**
As of Spring Security 5, JWT support is added out-of-the-box - https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html

So there is no need to add custom 3rd party libraries like jjwt and write custom filters like the JwtFilter.java class.

It would be great also to update the generator to reflect this change.

I am not sure if this is already discussed or not, I could not find any discussion in the issues, please close it if this is already discussed before :)

Sample apps with this implementation can be found here -
From Spring Repository itself - https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/jwt/login

https://github.com/danvega/jwt

A bit non-trivial example - https://github.com/SaiUpadhyayula/spring-reddit-clone

##### **Motivation for or Use Case**

It's important to make use of the framework support for JWT instead of writing our own custom logic. Spring Security team also suggests using the in-built support instead of writing custom logic.

##### **Related issues or PR**

Couldn't find any with my search, but I would love to contribute if this request is approved :)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I think you're confusing OAuth 2.0 with JWT. We do support OAuth 2.0 / OIDC authentication using Spring Security and no external libraries. We even provider resource server support, which is what your first link goes to.

However, for JWT authentication (which doesn't use OAuth 2.0), we need a mechanism to generate the JWT, which is what JJWT is used for.

**Comment by SaiUpadhyayula** [comment]
@mraible I am also referring to the scenario of JWT Authentication (without using OAuth 2.0). Even for this case, we can utilize the resource server library (even though we are not using any Auth Server like Okta or Keycloak) by using the JwtDecoder and JwtEncoder classes. 

We can generate the JWT and parse the JWT using the Resource Server support, so there is no need to rely on the JJWT library and the custom JWTFilter class.

Please have a look at the below sample app from the official Spring repository itself, which implements the JWT Authentication:

https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/jwt/login

**Comment by mraible** [comment]
If we switched to this, we'd just be depending on a new JWT library (the Nimbus SDK). I guess the good news is Spring Security uses it. 

From: https://github.com/spring-projects/spring-security-samples/blob/main/servlet/spring-boot/java/jwt/login/src/main/java/example/RestConfig.java#L22-L27

```java
import com.nimbusds.jose.jwk.JWK;
import com.nimbusds.jose.jwk.JWKSet;
import com.nimbusds.jose.jwk.RSAKey;
import com.nimbusds.jose.jwk.source.ImmutableJWKSet;
import com.nimbusds.jose.jwk.source.JWKSource;
import com.nimbusds.jose.proc.SecurityContext;
```

JJWT was created by friends of mine, and I trust them, so I'm not sure which is better.

If you'd like to create a PR, we can see if moving to a new library still passes all our CI tests.

**Comment by mshima** [comment]
From what I’ve seen, it’s doable and will reduce complexity due to shared dependencies between oauth2 and jwt.

**Comment by SaiUpadhyayula** [comment]
@mraible Yes, I will try to raise a PR soon.

**Comment by atomfrede** [comment]
@mshima @mraible Should we tag it for v8?

**Comment by mraible** [comment]
@atomfrede Yes, that's a good idea.

**Comment by mshima** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/20066

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/120306

**Comment by DanielFran** [comment]
@mshima approved
