### ISSUE TITLE
Angular 14 - Setting page titles natively with the Angular router

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#19693]
##### **Overview of the feature request**

Implements https://dev.to/brandontroberts/setting-page-titles-natively-with-the-angular-router-393j

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Adding a bounty as I know you spent a lot of night to achieve this :-)

**Comment by qmonmert** [comment]
thanks @pascalgrimaud 🙂 https://opencollective.com/generator-jhipster/expenses/96933

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
