### ISSUE TITLE
The sample DTO app doesn't work since upgrade to MapStruct 1.0.0.CR2

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1971]
Error message is:

    [ERROR] diagnostic: /Users/julien/workspace/jhipster-automation/samples/jhipster-sample-app-dto/src/main/java/com/mycompany/myapp/web/rest/mapper/BankAccountMapper.java:20: error: Can't map property "java.lang.Long userId" to "com.mycompany.myapp.domain.User user". Consider to declare/implement a mapping method: "com.mycompany.myapp.domain.User map(java.lang.Long value)".
    BankAccount bankAccountDTOToBankAccount(BankAccountDTO bankAccountDTO);
                ^
    [ERROR] diagnostic: /Users/julien/workspace/jhipster-automation/samples/jhipster-sample-app-dto/src/main/java/com/mycompany/myapp/web/rest/mapper/OperationMapper.java:19: error: Can't map property "java.lang.Long bankAccountId" to "com.mycompany.myapp.domain.BankAccount bankAccount". Consider to declare/implement a mapping method: "com.mycompany.myapp.domain.BankAccount map(java.lang.Long value)".
    Operation operationDTOToOperation(OperationDTO operationDTO);

Next I should test before upgrading!

**Comment by deepu105** [comment]
When did we upgrade?

**Comment by jdubois** [comment]
This is 100% my fault. MapStruct had this new CR version a few days ago and I thought it was safe to upgrade. I should have tested before, my bad!

**Comment by jdubois** [comment]
So this should be corrected in the next MapStruct version!
In the meantime I'm rolling back to MapStruct 1.0.0.CR1.

**Comment by jdubois** [comment]
Done by https://github.com/jhipster/generator-jhipster/commit/befad4a4a5899bedc2096dcf8563b81a24daa58c
