### ISSUE TITLE
Entity modification fails

### ISSUE THREAD

**Issue by natalia-pokrovskaya** [jhipster/generator-jhipster#1973]
Hello,

I've created an entity some days before and now I want to modify it by adding some new fields. So I modified my .json file and run yo jhipster:entity copy (copy is the name of my entity). Everything works pretty well, except liquibase changelog file generation. 
In fact, I'm asked to overwrite the existing changelog
> Overwrite src/main/resources/config/liquibase/changelog/20150902131228_added_entity_Copy.xml? (Ynaxdh)

If I reply yes, then my application fails to start because md5sum differs. If I say no, my entity change but the database not.... I supposed that the new changelog file should be some kind of "delta" file, shouldn't it?
How should I manage the database changes?

Thank you in advance for your help!

**Comment by jdubois** [comment]
Have a look at the "database updates" section of the [documentation](http://jhipster.github.io/development.html).

-> if you don't find this clear enough, we can improve it, I'm just closing this because it's supposed to be documented, not to end the discussion!

**Comment by natalia-pokrovskaya** [comment]
@jdubois Thank you for reply.

Yes, I read this section, but I'm still a little bit perplexed...
In this section it stands "If you add or modify a JPA entity, you will need to update your database schema.", should I modify it manually before I run the entity sub-generator?
In this section, I see 'A new "change log" is created', but in my case it tries to recreate the existent one and after that I cannot run my application anymore...
What I'm doing wrong?

Thank you!

**Comment by jdubois** [comment]
No, you can you Liquibase:diff or do the changelog manually.

Liquibase:diff looks easier to me, but that's up to you to decide.

If all this looks too complex for you, you can also remove Liquibase and do everything manually.

**Comment by natalia-pokrovskaya** [comment]
Ok, thanks!
