### ISSUE TITLE
Update microservices architecture diagram 

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#19739]
##### **Overview of the issue**

The current microservices architecture diagram needs to be updated.

https://www.jhipster.tech/microservices-architecture/

I think it'd also be good to include an architecture diagram of micro frontends.

##### **Motivation for or Use Case**

People should be able to use our diagrams in their blog posts and presentations. We don't want them to show information that's 5+ years old. Especially since the current diagram uses AngularJS and JHipster Console, both of which are no longer supported.

##### **Suggest a Fix**

I created a couple of ideas in OmniGraffle, but I think it might be better to use the same mechanism that was used before. You can find the artifacts I created and a link to how the current one was created [on our jhipster-dev mailing list](https://groups.google.com/g/jhipster-dev/c/PvHmoAgYFL8).

##### **JHipster Version(s)**

7.9.3

**Comment by A-5ingh** [comment]
@mraible Can I work on this? I have contributed to `jhipster-dotnetcore` in the past but would require support in achieving this task.

**Comment by mraible** [comment]
Yes! Please let me know if I can help.

**Comment by A-5ingh** [comment]
Thanks, @mraible. I'll go through the docs already available and if you can share the components to be added. I can work on it. Do we need to stick to the same design/look or it can also be changed?

**Comment by mraible** [comment]
This details how the diagram was originally created:

https://github.com/jhipster/generator-jhipster/issues/2785#issuecomment-192944329

I'm not sure we need to use the same system. For example, I created one with OmniGraffle, but it's difficult to tell what changed since it's not text-based.

https://speakerdeck.com/mraible/micro-frontends-for-java-developers-javaone-2022?slide=29

**Comment by A-5ingh** [comment]
I think using asciiflow will be beneficial as it will be easy to see what gets changed. I have converted your OmniGraffle one into ASCII. Please review if this helps. 
```
+-------------------------------------------------------------------+                   +---------------------------------------------------------------------+
|                                                                   |                   |                                                                     |
|                                                                   |                   |                                                                     |
|                                                                   |                   |   +--------------+      +-----------------+    +----------------+   |        +-----------------+
|                                                                   |                   |   |              |      |                 |    |                |   |        |                 |
|                                     +-----------------------+     |                   |   |   Angular    |      |  Spring Cloud   |    |     Access     +---|------->|    KeyCloak     |
|                                     |                       |     |                   |   |     App      |      |     Gateway     |    |     Control    |   |        |                 |
|                                     | JHipster Registry     |     |                   |   |              |      |                 |    |                |   |     +--|----+            |
|                                     |                       |     |                   |   +--------------+      +-----------------+    +----------------+   |     |  +----|------------+
|                                     |                       |     |                   |                                                                     |     |  {s}  |
|                                     |   +---------------+   |     |                   |                                                                     |     | Users |
|                                     |   | Eureka Server |   |     |                   +---+-----------------------------+-----------------------------------+     | Roles |
|     +---------------+               |   +---------------+   |     |                       |                             |                                         |       |
|     |               |               |   | Config Server |   |     |                       |                             |                                         +-------+
|     | HashiCorp     |               |   +---------------+   |     |                       |                             |
|     | Consul        |               |                       |     |                       |                             |
|     |               |               |                       |     |                       |                             |
|     +--------+------+               +----------+------------+     |                       |                      8081   v                 8082
|              |                                 |                  |                       |       +------------------+     +------------------+
|              |                                 |                  |                       |       |                  |     |                  |
|              +--------------+------------------+                  |                       |       |  Microservice 1  |     |  Microservice 2  |
|                             |                                     |                       |       |                  |     |                  |
|                             v                                     |                       |       +-----+------------+     +------------------+
|                         +-------+                                 |                       |             |
|                         |  {s}  |                                 |<----------------------+-------------+
|                         |       |                                 |                                     |        8083                      ...
|                         |  Git  |                                 | 8500 Consul                   +-----+------------+     +------------------+
|                         |  Repo |                                 | 8761 Eureka                   |                  |     |                  |
|                         +-------+                                 |                               |  Microservice 3  |     |  microservice n  |
|                                                                   |                               |                  |     |                  |
+-------------------------------------------------------------------+                               +------------------+     +------------------+
```

**Comment by A-5ingh** [comment]
@mraible any feedback on these two diagrams? I know they look too basic and definitely would add a jazz if we use images/icons of respective technologies.

**Comment by dpalic** [comment]
This created image can be provided as image, SVG or as text.
Original is a text based source file

Here in sketch status, during developing/creating:

![image](https://user-images.githubusercontent.com/1399203/199859782-59276c4c-61f9-4d21-8d5c-d4ca7330e945.png)

and here in finalized status for release:

![image](https://user-images.githubusercontent.com/1399203/199860015-457e8b98-309b-4828-acf8-ffaa57740372.png)

@mraible if you are interested ( ;-) and I have a good chance for bug bounty) will provide you more details and of course create more diagrams like required

**Comment by mraible** [comment]
@A-5ingh These look great! Is there anyway to make the text white when the background is red? On the Keycloak box, for instance.

**Comment by mraible** [comment]
@dpalic This looks awesome! I was going to mention that the wavy lines look funny in the first graphic, but you fixed that in the 2nd one. Is it possible to add more colors, like red or green? Also, we shouldn't use the coffee cup because Oracle will send us a message telling us not too. It's better to use [Duke](https://wiki.openjdk.org/display/duke/Gallery) to indicate Java.

**Comment by A-5ingh** [comment]
> Duke

I couldn't see any option in [ditaa](https://github.com/stathissideris/ditaa) to change the font color but it has different color codes available if you feel like using some other color instead of red.
![image](https://user-images.githubusercontent.com/32884734/200027673-f6af8dc3-73d2-4420-8253-cbbd7248c1c9.png)

**Comment by A-5ingh** [comment]
or @mraible we can use a darker shade of red which automatically uses the font color as white.
![jhip-microfrontend_6](https://user-images.githubusercontent.com/32884734/200048212-d89e5876-aa81-4134-8ebc-89570f3df991.png)

**Comment by A-5ingh** [comment]
So @mraible, we can add logs too but it will be a manual process. Do you want me to do it or do we want to keep it like that so that anyone can generate the `png` just by using `ditaa` on the ASCII diagram?

**Comment by mraible** [comment]
What do you mean by "add logs"? I don't understand what this means.On Nov 4, 2022, at 13:58, A. Singh ***@***.***> wrote:﻿
So @mraible, we can add logs too but it will be a manual process. Do you want me to do it or do we want to keep it like that so that anyone can generate the png just by using ditaa on the ASCII diagram?

**Comment by A-5ingh** [comment]
For instance, adding the git logo to the git repo, react logo to react app, etc.

**Comment by mraible** [comment]
Thanks for the clarifications. Logos would be cool, but if they can't be generated from source, it's probably not worth it. We need to have something that's easy to update.

**Comment by A-5ingh** [comment]
Right, that's why I didn't do much research. But I see we can give a background image using `ditaa`. I'll see what I can do. Please do let me know if there is any other feedback or improvement you feel we can do to it

**Comment by dpalic** [comment]
> @dpalic This looks awesome! I was going to mention that the wavy lines look funny in the first graphic, but you fixed that in the 2nd one. Is it possible to add more colors, like red or green? Also, we shouldn't use the coffee cup because Oracle will send us a message telling us not too. It's better to use [Duke](https://wiki.openjdk.org/display/duke/Gallery) to indicate Java.

regarding the both image types. It is intentionally. The first image is a sketch / work in progress view to visualize the diagram is not in finished status

regarding logo, sure can replace

regarding the colors, do you have a CI color set/book which we could use?.

**Comment by mraible** [comment]
@dpalic There are some colors for the website redesign in https://github.com/jhipster/generator-jhipster/issues/13595. Not sure if that's what you're looking for.

**Comment by dpalic** [comment]
@mraible you mean https://rebrand.ly/jhipster ?
the colors of the new website?

If so, I can try to use them

**Comment by mraible** [comment]
Yes. This might help too. https://github.com/jhipster/jhipster-artwork/issues/21

**Comment by A-5ingh** [comment]
@deepu105 / @mraible Please let me know if you are going to consider `asciiflow` and `dtaa` for it as showed in previous comments. Just in case @dpalic solution isn't complete.

**Comment by mraible** [comment]
Looks good! https://www.jhipster.tech/microservices-architecture/

![image](https://github.com/user-attachments/assets/7ba373de-78b6-48c4-99ad-8df35a80dd65)
