### ISSUE TITLE
Remove entity

### ISSUE THREAD

**Issue by buurd** [jhipster/generator-jhipster#19761]
##### **Overview of the feature request**

When learning of how an application is used some features might be cut, eg needs to be removed. Right now it seems liked JHipster doesn't seem to offer a controlled way of removing generated code for an entity when it is removed from the JDL. It's left as en excersise for the developer to understand what to remove and how. At least it should be documented how to do this operation in a acceptable way.

##### **Motivation for or Use Case**

JHipster generate more than the application, there are a number of files supporting the generation to. So it is not just a question of removing the entity-class and then track compilation-errors. A guide or a tools that helps with the cleanup would be of great help and safety. 

Tricks like having a single commit for each entity doesn't cover modified entities and in my option puts the responsibility in the wrong place. 

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by emilpaw** [comment]
This was discussed before in #8933

**Comment by buurd** [comment]
After reading #8933 I conclude the the only withdraw most of my request, but I still would like an update to the documentation about the subject, how to handle a delete-situation.

**Comment by atomfrede** [comment]
Yes documentation would be a nice thing.

**Comment by harshbsharma** [comment]
Hey I would like to contribute , can you assign?
