### ISSUE TITLE
Feature Request: Add quick inline help in setup process

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#19762]
##### **Overview of the feature request**

I want to know what certain options in the project setup wizard are meant to be used for.

##### **Motivation for or Use Case**

Updated to Jhipster 7.9.3 today and generated a new project. Recognized there is a new step "Use microfrontends (y/n)?" 
Though in this case it is quite obvious what this option is meant to be used for, a quick 2-3 sentence description with some keywords would give users a better idea of what to expect when enabling that option.

Currently, there are two available choices for most options in project generation: "yes (y)" or "no (n)". I would love to have add a third option "help (h)" added. When pressing h, the short description should appear. When then pressing ESC or q, the user should be returned to the selection (y/n)

##### **Related issues or PR**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by emilpaw** [comment]
I don't think having the documentation in two places is a good idea. Instead, we should direct the effort into improving the documentation on the website.

**Comment by gmarziou** [comment]
An alternative would be to print a link to online documentation at the end of the question, most terminals are able to make them clickable.

**Comment by CodingSpiderFox** [comment]
Yes, that might also work :)
