### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by thewhatsupguy** [jhipster/generator-jhipster#1979]
Hey @jdubois , I read this comment of yours on #1881 (Started a new thread because that issue is already closed. Hope that's the right way to go)

host everything to our own domain name (I still need to decide which one... BTW the jhipster.com domain is owned by our friend Matt Raible, and redirects to our github page). The main issue is that Github pages can't handle SSL on a custom domain, and that should be bad for SEO -> that means I should have a look at hosting this myself, but I'm so happy with the way Github pages work that this really annoys me.

A quick Google search seems to throw up tutorials on how to do this. Am I missing something here.

**Comment by jdubois** [comment]
Thanks @thewhatsupguy !
Yes for jhipster.com I know Matt got it, he told me about it.

The main issue with hosting this myself is that I need a way to run automatically jekyll after one merge -> there is probably a hook for this, but I haven't found out.

Basically that's quite a lot of work, it would cost some money (please remember I do all this for free), all this to have a custom domain... and most people find the website through Google anyway.

At the moment there is no urgent need for me, and I just don't have the time to do this.
