### ISSUE TITLE
mvn spring-boot:run produces error when i clone the project

### ISSUE THREAD

**Issue by feelcoder** [jhipster/generator-jhipster#1982]
I got this error

[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Authority.java:16: error: cannot find symbol
@Entity
 ^
  symbol: class Entity
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Authority.java:17: error: cannot find symbol
@Table(name = "JHI_AUTHORITY")
 ^
  symbol: class Table
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Testplanner.java:5: error: package org.springframework.data.elasticsearch.annotations does not exist
import org.springframework.data.elasticsearch.annotations.Document;
                                                         ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Testplanner.java:15: error: cannot find symbol
@Entity
 ^
  symbol: class Entity
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Testplanner.java:16: error: cannot find symbol
@Table(name = "TESTPLANNER")
 ^
  symbol: class Table
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Testplanner.java:18: error: cannot find symbol
@Document(indexName="testplanner")
 ^
  symbol: class Document
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/AbstractAuditingEntity.java:12: error: package org.springframework.data.jpa.domain.support does not exist
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
                                                  ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/AbstractAuditingEntity.java:13: error: cannot find symbol
import javax.persistence.Column;
                        ^
  symbol:   class Column
  location: package javax.persistence
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/AbstractAuditingEntity.java:14: error: cannot find symbol
import javax.persistence.EntityListeners;
                        ^
  symbol:   class EntityListeners
  location: package javax.persistence
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/AbstractAuditingEntity.java:15: error: cannot find symbol
import javax.persistence.MappedSuperclass;
                        ^
  symbol:   class MappedSuperclass
  location: package javax.persistence
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/AbstractAuditingEntity.java:16: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
                                   ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/AbstractAuditingEntity.java:22: error: cannot find symbol
@MappedSuperclass
 ^
  symbol: class MappedSuperclass
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/AbstractAuditingEntity.java:24: error: cannot find symbol
@EntityListeners(AuditingEntityListener.class)
 ^
  symbol: class EntityListeners
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/User.java:8: error: package org.springframework.data.elasticsearch.annotations does not exist
import org.springframework.data.elasticsearch.annotations.Document;
                                                         ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/User.java:11: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
                                   ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/User.java:12: error: package javax.validation.constraints does not exist
import javax.validation.constraints.Pattern;
                                   ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/User.java:13: error: package javax.validation.constraints does not exist
import javax.validation.constraints.Size;
                                   ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/User.java:23: error: cannot find symbol
@Entity
 ^
  symbol: class Entity
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/User.java:24: error: cannot find symbol
@Table(name = "JHI_USER")
 ^
  symbol: class Table
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/User.java:26: error: cannot find symbol
@Document(indexName="user")
 ^
  symbol: class Document
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:7: error: cannot find symbol
import javax.persistence.Column;
                        ^
  symbol:   class Column
  location: package javax.persistence
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:8: error: cannot find symbol
import javax.persistence.Entity;
                        ^
  symbol:   class Entity
  location: package javax.persistence
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:9: error: cannot find symbol
import javax.persistence.EnumType;
                        ^
  symbol:   class EnumType
  location: package javax.persistence
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:10: error: cannot find symbol
import javax.persistence.Enumerated;
                        ^
  symbol:   class Enumerated
  location: package javax.persistence
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:11: error: cannot find symbol
import javax.persistence.Id;
                        ^
  symbol:   class Id
  location: package javax.persistence
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:12: error: cannot find symbol
import javax.persistence.PrePersist;
                        ^
  symbol:   class PrePersist
  location: package javax.persistence
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:13: error: cannot find symbol
import javax.persistence.Table;
                        ^
  symbol:   class Table
  location: package javax.persistence
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:14: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
                                   ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:24: error: package org.springframework.data.elasticsearch.annotations does not exist
import org.springframework.data.elasticsearch.annotations.Document;
                                                         ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:32: error: cannot find symbol
@Entity
 ^
  symbol: class Entity
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:33: error: cannot find symbol
@Table(name = "PLANNING")
 ^
  symbol: class Table
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/domain/Planning.java:35: error: cannot find symbol
@Document(indexName="planning")
 ^
  symbol: class Document
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/app/CurriculumCourseApp.java:26: error: package org.optaplanner.core.api.solver does not exist
import org.optaplanner.core.api.solver.Solver;
                                      ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/app/CurriculumCourseApp.java:27: error: package org.optaplanner.core.api.solver does not exist
import org.optaplanner.core.api.solver.SolverFactory;
                                      ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/app/CurriculumCourseApp.java:36: error: cannot find symbol
    SolverFactory solverFactory = SolverFactory.createFromXmlResource(SOLVER_CONFIG);
    ^
  symbol:   class SolverFactory
  location: class org.adorsys.adplanner.curriculumcourse.app.CurriculumCourseApp
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/app/CurriculumCourseApp.java:39: error: cannot find symbol
    private Map<String, Solver> mapSolver = new HashMap<String, Solver>();
                        ^
  symbol:   class Solver
  location: class org.adorsys.adplanner.curriculumcourse.app.CurriculumCourseApp
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:24: error: package org.optaplanner.core.api.domain.solution does not exist
import org.optaplanner.core.api.domain.solution.PlanningEntityCollectionProperty;
                                               ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:25: error: package org.optaplanner.core.api.domain.solution does not exist
import org.optaplanner.core.api.domain.solution.PlanningSolution;
                                               ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:26: error: package org.optaplanner.core.api.domain.solution does not exist
import org.optaplanner.core.api.domain.solution.Solution;
                                               ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:27: error: package org.optaplanner.core.api.domain.valuerange does not exist
import org.optaplanner.core.api.domain.valuerange.ValueRangeProvider;
                                                 ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:28: error: package org.optaplanner.core.api.score.buildin.hardsoft does not exist
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore;
                                                      ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:29: error: package org.optaplanner.core.impl.score.buildin.hardsoft does not exist
import org.optaplanner.core.impl.score.buildin.hardsoft.HardSoftScoreDefinition;
                                                       ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:31: error: package com.thoughtworks.xstream.annotations does not exist
import com.thoughtworks.xstream.annotations.XStreamConverter;
                                           ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:32: error: package org.optaplanner.persistence.xstream.impl.score does not exist
import org.optaplanner.persistence.xstream.impl.score.XStreamScoreConverter;
                                                     ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:35: error: cannot find symbol
public class CourseSchedule implements Solution<HardSoftScore> {
                                       ^
  symbol: class Solution
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:35: error: cannot find symbol
public class CourseSchedule implements Solution<HardSoftScore> {
                                                ^
  symbol: class HardSoftScore
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:34: error: cannot find symbol
@PlanningSolution
 ^
  symbol: class PlanningSolution
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/Lecture.java:25: error: package org.optaplanner.core.api.domain.entity does not exist
import org.optaplanner.core.api.domain.entity.PlanningEntity;
                                             ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/Lecture.java:26: error: package org.optaplanner.core.api.domain.variable does not exist
import org.optaplanner.core.api.domain.variable.PlanningVariable;
                                               ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/Lecture.java:28: error: cannot find symbol
@PlanningEntity(difficultyWeightFactoryClass = LectureDifficultyWeightFactory.class,
 ^
  symbol: class PlanningEntity
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:53: error: cannot find symbol
    private HardSoftScore score;
            ^
  symbol:   class HardSoftScore
  location: class org.adorsys.adplanner.curriculumcourse.domain.CourseSchedule
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:138: error: cannot find symbol
    public HardSoftScore getScore() {
           ^
  symbol:   class HardSoftScore
  location: class org.adorsys.adplanner.curriculumcourse.domain.CourseSchedule
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/CourseSchedule.java:142: error: cannot find symbol
    public void setScore(HardSoftScore score) {
                         ^
  symbol:   class HardSoftScore
  location: class org.adorsys.adplanner.curriculumcourse.domain.CourseSchedule
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/solver/move/DifferentCourseSwapMoveFilter.java:20: error: package org.optaplanner.core.impl.heuristic.selector.common.decorator does not exist
import org.optaplanner.core.impl.heuristic.selector.common.decorator.SelectionFilter;
                                                                    ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/solver/move/DifferentCourseSwapMoveFilter.java:21: error: package org.optaplanner.core.impl.heuristic.selector.move.generic does not exist
import org.optaplanner.core.impl.heuristic.selector.move.generic.SwapMove;
                                                                ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/solver/move/DifferentCourseSwapMoveFilter.java:22: error: package org.optaplanner.core.impl.score.director does not exist
import org.optaplanner.core.impl.score.director.ScoreDirector;
                                               ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/solver/move/DifferentCourseSwapMoveFilter.java:24: error: cannot find symbol
public class DifferentCourseSwapMoveFilter implements SelectionFilter<SwapMove> {
                                                      ^
  symbol: class SelectionFilter
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/solver/move/DifferentCourseSwapMoveFilter.java:24: error: cannot find symbol
public class DifferentCourseSwapMoveFilter implements SelectionFilter<SwapMove> {
                                                                      ^
  symbol: class SwapMove
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/solver/move/DifferentCourseSwapMoveFilter.java:26: error: cannot find symbol
    public boolean accept(ScoreDirector scoreDirector, SwapMove move) {
                          ^
  symbol:   class ScoreDirector
  location: class org.adorsys.adplanner.curriculumcourse.solver.move.DifferentCourseSwapMoveFilter
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/solver/move/DifferentCourseSwapMoveFilter.java:26: error: cannot find symbol
    public boolean accept(ScoreDirector scoreDirector, SwapMove move) {
                                                       ^
  symbol:   class SwapMove
  location: class org.adorsys.adplanner.curriculumcourse.solver.move.DifferentCourseSwapMoveFilter
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/solver/PeriodStrengthWeightFactory.java:23: error: package org.optaplanner.core.impl.heuristic.selector.common.decorator does not exist
import org.optaplanner.core.impl.heuristic.selector.common.decorator.SelectionSorterWeightFactory;
                                                                    ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/solver/PeriodStrengthWeightFactory.java:25: error: cannot find symbol
public class PeriodStrengthWeightFactory implements SelectionSorterWeightFactory<CourseSchedule, Period> {
                                                    ^
  symbol: class SelectionSorterWeightFactory
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/solver/LectureDifficultyWeightFactory.java:24: error: package org.optaplanner.core.impl.heuristic.selector.common.decorator does not exist
import org.optaplanner.core.impl.heuristic.selector.common.decorator.SelectionSorterWeightFactory;
                                                                    ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/solver/LectureDifficultyWeightFactory.java:26: error: cannot find symbol
public class LectureDifficultyWeightFactory implements SelectionSorterWeightFactory<CourseSchedule, Lecture> {
                                                       ^
  symbol: class SelectionSorterWeightFactory
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/solver/RoomStrengthWeightFactory.java:22: error: package org.optaplanner.core.impl.heuristic.selector.common.decorator does not exist
import org.optaplanner.core.impl.heuristic.selector.common.decorator.SelectionSorterWeightFactory;
                                                                    ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/solver/RoomStrengthWeightFactory.java:24: error: cannot find symbol
public class RoomStrengthWeightFactory implements SelectionSorterWeightFactory<CourseSchedule, Room> {
                                                  ^
  symbol: class SelectionSorterWeightFactory
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/solver/MovableLectureSelectionFilter.java:20: error: package org.optaplanner.core.impl.heuristic.selector.common.decorator does not exist
import org.optaplanner.core.impl.heuristic.selector.common.decorator.SelectionFilter;
                                                                    ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/solver/MovableLectureSelectionFilter.java:21: error: package org.optaplanner.core.impl.score.director does not exist
import org.optaplanner.core.impl.score.director.ScoreDirector;
                                               ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/solver/MovableLectureSelectionFilter.java:23: error: cannot find symbol
public class MovableLectureSelectionFilter implements SelectionFilter<Lecture> {
                                                      ^
  symbol: class SelectionFilter
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/curriculumcourse/domain/solver/MovableLectureSelectionFilter.java:25: error: cannot find symbol
    public boolean accept(ScoreDirector scoreDirector, Lecture lecture) {
                          ^
  symbol:   class ScoreDirector
  location: class org.adorsys.adplanner.curriculumcourse.domain.solver.MovableLectureSelectionFilter
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/CustomAuditEventRepository.java:6: error: package org.springframework.boot.actuate.audit does not exist
import org.springframework.boot.actuate.audit.AuditEvent;
                                             ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/CustomAuditEventRepository.java:7: error: package org.springframework.boot.actuate.audit does not exist
import org.springframework.boot.actuate.audit.AuditEventRepository;
                                             ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/CustomAuditEventRepository.java:10: error: package org.springframework.transaction.annotation does not exist
import org.springframework.transaction.annotation.Propagation;
                                                 ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/CustomAuditEventRepository.java:11: error: package org.springframework.transaction.annotation does not exist
import org.springframework.transaction.annotation.Transactional;
                                                 ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/PersistenceAuditEventRepository.java:5: error: package org.springframework.data.jpa.repository does not exist
import org.springframework.data.jpa.repository.JpaRepository;
                                              ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/PersistenceAuditEventRepository.java:12: error: cannot find symbol
public interface PersistenceAuditEventRepository extends JpaRepository<PersistentAuditEvent, String> {
                                                         ^
  symbol: class JpaRepository
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/CustomAuditEventRepository.java:27: error: cannot find symbol
    public AuditEventRepository auditEventRepository() {
           ^
  symbol:   class AuditEventRepository
  location: class org.adorsys.adplanner.repository.CustomAuditEventRepository
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/AuthorityRepository.java:4: error: package org.springframework.data.jpa.repository does not exist
import org.springframework.data.jpa.repository.JpaRepository;
                                              ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/AuthorityRepository.java:9: error: cannot find symbol
public interface AuthorityRepository extends JpaRepository<Authority, String> {
                                             ^
  symbol: class JpaRepository
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/UserRepository.java:6: error: package org.springframework.data.jpa.repository does not exist
import org.springframework.data.jpa.repository.JpaRepository;
                                              ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/UserRepository.java:7: error: package org.springframework.data.jpa.repository does not exist
import org.springframework.data.jpa.repository.Query;
                                              ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/UserRepository.java:15: error: cannot find symbol
public interface UserRepository extends JpaRepository<User, Long> {
                                        ^
  symbol: class JpaRepository
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/PlanningRepository.java:4: error: package org.springframework.data.jpa.repository does not exist
import org.springframework.data.jpa.repository.*;
^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/PlanningRepository.java:11: error: cannot find symbol
public interface PlanningRepository extends JpaRepository<Planning,String> {
                                            ^
  symbol: class JpaRepository
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/search/TestplannerSearchRepository.java:4: error: package org.springframework.data.elasticsearch.repository does not exist
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;
                                                        ^
[ERROR] diagnostic: /home/feelcoder/dev2/planning/src/main/java/org/adorsys/adplanner/repository/search/TestplannerSearchRepository.java:9: error: cannot find symbol
public interface TestplannerSearchRepository extends ElasticsearchRepository<Testplanner, Long> {
                                                     ^
  symbol: class ElasticsearchRepository
[WARNING] diagnostic: warning: The following options were not recognized by any processor: '[mapstruct.defaultComponentModel, mapstruct.suppressGeneratorTimestamp]'
[ERROR] error on execute: error during compilation
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.421s
[INFO] Finished at: Sun Sep 06 20:46:41 UTC 2015
[INFO] Final Memory: 30M/73M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bsc.maven:maven-processor-plugin:2.2.4:process (process) on project adplanner: Error executing: error during compilation -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by gmarziou** [comment]
This is not a JHipster issue: your maven dependencies are not resolved.
Fix your maven environment.

Also when cloning a project, you must make sure that you run 'npm install' and 'bower install' in clone though it's not related to your issue.
