### ISSUE TITLE
Drop modules support

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#19829]
##### **Overview of the feature request**

Modules was deprecated in favor of blueprints.
We should remove support for it.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
I just looked at the market place, I roughly estimate that 40 % are modules, most of them are old (jhipster <= 6) but few of them are more recent and actively maintained.

As far as I know, modules deprecation was not announced in v7, so it sounds hard to drop support like this.

Maybe these authors could be contacted with some guidelines showing how to migrate a module to a blueprint.

**Comment by mshima** [comment]
Module migration is available here https://www.jhipster.tech/modules/creating-a-module/.

Just saw the layout is broken: https://github.com/jhipster/jhipster.github.io/pull/1236 should fix it

**Comment by gmarziou** [comment]
Excellent
