### ISSUE TITLE
MongoDB unit tests

### ISSUE THREAD

**Issue by franciscocpg** [jhipster/generator-jhipster#1986]
At https://jhipster.github.io/using_mongodb.html you stated the following:
**"As MongoDB is not a Java application, JHipster cannot run an in-memory version of the database for running unit tests: in order to have your tests working, you will need to start manually a MongoDB instance"**
My suggestion is to use https://github.com/joelittlejohn/embedmongo-maven-plugin to workaround this problem. What you guys think about it?

**Comment by atomfrede** [comment]
Have you tried it already? It looks like you need to add some specific code to your units test. I'm not sure it works well with spring-data (but I haven't tried it). In https://github.com/jhipster/generator-jhipster/issues/1477 there was another proposal using [https://github.com/fakemongo/fongo](fongo). If you like a PR will be appreciated.

**Comment by franciscocpg** [comment]
Hi @atomfrede.
Yes I have tried it already using with EclipseLinkNoSQL and HibernateOGM without any problems.
I am newbie to jhipster, so I am going to understand better the way you guys make things work with MongoDB and try to propose a PR.

**Comment by atomfrede** [comment]
@franciscocpg Sounds cool. If you have any questions don't hesitate to ask and don't forget to look at the [Contributing Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md).

**Comment by thiagogcm** [comment]
Guys from Vert.x use this tool for unit testing
    https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo

Never tried it directly though

**Comment by franciscocpg** [comment]
Hi @thiagogcm.
In fact, https://github.com/joelittlejohn/embedmongo-maven-plugin already uses https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo but it encapsulates (wrapper) all configuration using maven.
Another option to consider is https://github.com/lordofthejars/nosql-unit that provides both managed and *in-memory* instances.

**Comment by jdubois** [comment]
Yes, this kind of thing has already been proposed in the past.

The wrapper could be a good solution, but we have to be sure it behaves correctly on all OSes, which will be an issue (as we won't be able to test it on all OSes!)

**Comment by franciscocpg** [comment]
Hello @jdubois.
I have already tested this solution using Windows 7, MacOS and Ubuntu, so I think this will not be a problem.
To avoid permissions problems, by default the wrapper downloads and executes the mongodb instance at the user home folder.

**Comment by jdubois** [comment]
If you can try it with JHipster it would be really cool.

My main issue at the moment is that we use Mongeez, and that it can't work on cloud databases (see https://github.com/jhipster/generator-jhipster/issues/733 ), and so removing Mongeez has the highest priority for me.

**Comment by altus34** [comment]
It's available in the last version of spring boot

https://github.com/spring-projects/spring-boot/commits/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.java?author=wilkinsona

**Comment by altus34** [comment]
If you want to use it in current version of spring-boot you can add 
     
    <dependency>
         <groupId>cz.jirutka.spring</groupId>
         <artifactId>embedmongo-spring</artifactId>
         <version>1.3.1</version>
         <scope>test</scope>
     </dependency>

This dependency use de.flapdoodle.embed.mongo (a true mongo)
After that just a Configuration class 

    import com.mongodb.*;
    import cz.jirutka.spring.embedmongo.EmbeddedMongoBuilder;
    import org.springframework.context.annotation.*;
    import org.springframework.data.mongodb.config.AbstractMongoConfiguration;

    import java.io.IOException;

    @Configuration
    public class EmbeddedMongo extends AbstractMongoConfiguration {

        String MONGO_DB_HOST = "localhost";
        int MONGO_DB_PORT = 27017;
        String MONGO_DB_NAME = "express-domain-test";

        @Override
        protected String getDatabaseName() {
            return MONGO_DB_NAME;
        }

        @Bean(destroyMethod = "close")
        public Mongo mongo() throws IOException {
            try {
                // Try to find an existing local mongo
                MongoClientOptions options = MongoClientOptions.builder().connectTimeout(100).build();
                MongoClient mongoClient = new MongoClient(new ServerAddress(MONGO_DB_HOST,MONGO_DB_PORT), options);
                mongoClient.getConnectPoint();
                return mongoClient;
            } catch (Exception e) {
                // Else start an embedded mongo
                return new EmbeddedMongoBuilder()
                        .version("2.4.5")
                        .bindIp(MONGO_DB_HOST)
                        .port(MONGO_DB_PORT)
                        .build();
            }
        }
    }

**Comment by jdubois** [comment]
Fixed by #2148
