### ISSUE TITLE
I don t see image in jhipster when add img with src tag  [jhipster]

### ISSUE THREAD

**Issue by silvanonapoli1990** [jhipster/generator-jhipster#19887]
hi everyone i have problem to see image in jhipster? i put the image in the component and in src/main/webapp/content/images
but i don t see the image i see only the alt tag

**Comment by gmarziou** [comment]
Please don't use the project issue tracker for questions, questions are for stackoverflow and I answered you there.

https://stackoverflow.com/questions/73906299/how-add-image-jhipster-angular
