### ISSUE TITLE
API servlet mapping

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1997]
Currently the api is served on "/" and the rest controllers include a "/api" in there request mapping.
Wouldn't it be cleaner to have these controllers served on "/api" ?
It would also be better for the swagger doc as the "/api" could be set in the basePath field and the resource paths would not include it.

Concrete use case : I use a front proxy to version my api and I make mappings from http://myDomain.com/api/v1.0 to http://locaIP/api. I use swagger to document and publish my API and it would be easier to just change the basePath instead of changing every resource paths in the swagger.json

**Comment by jdubois** [comment]
I'm not sure this can be changed -> Spring Boot serves several URL on "/" (like "/dump"), and we use the same Spring MVC configuration.

**Comment by cbornet** [comment]
It seems possible to modify the default dispatch servlet http://www.leveluplunch.com/java/tutorials/011-add-servlet-mapping-to-dispatcherservlet-spring-boot/

**Comment by jdubois** [comment]
Yes I know how to do it in a normal Spring app, but with Spring Boot the dispatcher servlet is auto-configured, so that's different.
Besides, we might need several dispatcher servlets, and that's an issue: that means several Web application contexts, which is good for advanced users, but very confusing for normal people.

**Comment by cbornet** [comment]
If you have beans named "dispatcherServlet" and "dispatcherServletRegistration" they will override the ones auto-configured by DispatcherServletAutoConfiguration.
As for the multiple web contexts, I understand your concern...

**Comment by jdubois** [comment]
Yes but I don't know the impacts for the Spring Boot endpoints, are they served by this DispatcherServlet?
This solution looks more complex to me than what we are trying to solve: it's just 5 letters at the top of each class...

**Comment by jdubois** [comment]
Sorry, 6 letters :-)

**Comment by cbornet** [comment]
Yes, this is configuration flexibility at the cost of code complexity.
Remains my very personnal issue with swagger generated doc.

**Comment by jdubois** [comment]
Can't this be configured on the Swagger side?

**Comment by cbornet** [comment]
I haven't found a way. @dilipkrish, you have an idea ?

**Comment by dilipkrish** [comment]
@cbornet You should be able to use the [WebApplicationInitalizer](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/WebApplicationInitializer.html) to define dynamic servlet dispatchers with a mapping of `"/api"` . And then in springfox you need to add a [pathMapping](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) see **8**, to your docket. I think that should solve your problem.

**Comment by cbornet** [comment]
Would this avoid the "multiple webapp context" complexity that @jdubois wants to avoid

**Comment by dilipkrish** [comment]
@cbornet that technique will not create multiple contexts (see the javadoc :point_up:) ; if you don't want it to that is. However; with the caveat that Im not very familiar with the workings of how jhipster sets things up; I'm not sure how easy it is in jhipster to allow generating custom dynamic servlet registrations hooks based your needs.

**Comment by cbornet** [comment]
Well, I don't really feel confident with the jhipster web config either... Maybe someone who has better knowledge ?

**Comment by piedrahitac** [comment]
I don't know if this would solve your issue, but you can add additional `WebMvc` configuration to JHipster (or Spring Boot for that matter) by creating a new  `@Configuration` class that extends `WebMvcConfigurerAdapter`.

I'm currently using this approach to add some custom resource handlers and it works like a charm, the only consideration is to avoid the `@EnableWebMvc` annotation in your configuration classes, as it will conflict with JHipster.

**Comment by dilipkrish** [comment]
@piedrahitac that will work, but keep in mind that for springboot apps, you'll lose all auto configuration magic that spring boot gives you.

**Comment by jdubois** [comment]
OK, I definitely don't think this is a good idea. We are just trying to remove a few letters, and we can end up in a big mess.
This is why I'm closing this.
