### ISSUE TITLE
Implement base-workspaces.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#19980]
##### **Overview of the feature request**

It will be the base for generators that uses multiple applications like the workspace generator and deployments.
It should provide a few custom priorities:
```
  get [BaseWorkspaces.DEFAULT]() {} // for reference

  get [BaseWorkspaces.LOADING_WORKSPACES]({ workspaces }) {}

  get [BaseWorkspaces.PREPARING_WORKSPACES]({ workspaces, applications }) {
    workspaces.aConfig = applications.every(application => application.aConfig);
    workspaces.anotherConfig = application.some(application => application.anotherConfig);
  }

  get [BaseWorkspaces.WRITING]({ workspaces }) {}
```

##### **Motivation for or Use Case**

Simplify deployment generators.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/pull/19978#discussion_r991586546

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/170967

**Comment by DanielFran** [comment]
@mshima approved
