### ISSUE TITLE
Add internal support for generators to implement jdl incremental generation for config and entities.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#19989]
##### **Overview of the feature request**

Back in JHipster 6, jdl command advertised that it only generates changed entities.
That was somewhat true, but it generated inconsistent source code.
The feature was jdl specific and had not support at generators. This was implemented by passing only changed entities to the generator, but it ignored application dependent configurations and relationships. Since the generator had no knowledge about others entities, relationships primaryKey and label types, that fall back to the default type that are application database dependent, were generated wrongly.
Due to this inconsistent behavior, this option was disabled.

For a consistent result, a jhipster application should be fully prepared.
At jhipster v8 the prepared application and entities are shared between the generators and fully consistent.
Now it's possible to add internal support to configuration and entities changes.

Configuration changes proposal:
```
  get [BaseApplicationGenerator.WRITING]() {
    return {
      async writeIncrementalConfig({ application, configChanges, sharedOptions }) {
        if (sharedOptions.regenerate || configChanges.cacheProvider?.newValue === 'ehcache') {
          await this.writeFiles({ files: ehcacheFiles, context: application });
        } else if (configChanges.cacheProvider?.oldValue === 'ehcache') {
          await this.deleteFiles({ files: ehcacheFiles, context: application });
        }
      }
    }
  }
```

Entity and entity changelogs proposal:
```
  get [BaseApplicationGenerator.WRITING_ENTITIES]() {
    return {
      async writeIncrementalEntities({ application, sharedOptions, entities, changedEntities }) {
        for (const { entity, deleted, added, changes } of changedEntities) {
          if (sharedOptions.regenerate || added) {
            await this.writeFiles({ files: entityFiles, context: entity });
          } else if (deleted) {
            await this.deleteFiles({ files: entityFiles, context: entity });
          }

          for (const entityChange of changes) {
            await this.writeFiles({ files: changelogFiles, context: { ...entity, ...entityChange } });
          }
        }
      }
    }
  }
```

##### **Motivation for or Use Case**

Allow to generate new configuration and entities without overriding custom code.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/pull/19978#discussion_r991871870
https://github.com/jhipster/generator-jhipster/issues/19761
https://github.com/jhipster/generator-jhipster/issues/8933
https://github.com/jhipster/generator-jhipster/issues/19328
https://github.com/jhipster/generator-jhipster/issues/17006
https://github.com/jhipster/generator-jhipster/issues/14678
https://github.com/jhipster/generator-jhipster/issues/13365
https://github.com/jhipster/generator-jhipster/issues/13833

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/165732.

**Comment by DanielFran** [comment]
@mshima approved
