### ISSUE TITLE
Login required for token-based auth, even though rememberMe is set

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1999]
I've noticed that I have to re-login all the time on www.21-points.com. The "remember me for two weeks" functionality seems broken. The app uses release 2.19.0.

My .yo-rc.json:

````
{
  "generator-jhipster": {
    "baseName": "21points",
    "packageName": "org.jhipster.health",
    "packageFolder": "org/jhipster/health",
    "authenticationType": "xauth",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "happyfriday!"
  }
}
````

**Comment by jdubois** [comment]
As the token is a custom implementation, I don't think this is working with the remember-me filter from Spring Security.
Then, the token could be stored in the localsession (or a cookie, of course), so this can be implemented.

**Comment by jdubois** [comment]
Oh, and we shouldn't generate the remember-me box for the moment, of course.

**Comment by mraible** [comment]
In my app, there is no checkbox for remember-me. Instead, it's hardcoded to true in `login.controller.js`:

```
$scope.rememberMe = true;
$timeout(function (){angular.element('[ng-model="username"]').focus();});
$scope.login = function (event) {
    event.preventDefault();
    Auth.login({
        username: $scope.username,
        password: $scope.password,
        rememberMe: $scope.rememberMe
    }).then(function () {
        $scope.authenticationError = false;
        if ($rootScope.previousStateName === 'register') {
            $state.go('home');
        } else {
            $rootScope.back();
        }
    }).catch(function () {
        $scope.authenticationError = true;
    });
};
```

**Comment by jdubois** [comment]
This is also linked to #1716

I didn't code this authentication method, but I guess it's simpler than what people expect it to be.

**Comment by wibbo** [comment]
Do I understand the idea of this enhancement correctly, that the remember me functionality should work the same way when using a token-based authentication as it does for HTTP session authentication? And I think for OAuth2 authentication, this should be the case as well.

**Comment by deepu105** [comment]
We need to revalidate this in the wake of #2100

**Comment by jdubois** [comment]
Yes we need to check this now that #2100 is done.
Currently the user token is stored in the browser's localstorage, so it's a different mechanism that the normal session-based login.

**Comment by deepu105** [comment]
@jdubois can we close this with JWT i dont think we have the remember me box at all right?

**Comment by jdubois** [comment]
Yes.
There will be some specific work to have something similar with JWT, but it's another task.
