### ISSUE TITLE
Generating an entity called "load" will cause a 400 error when adding a new load through entity management

### ISSUE THREAD

**Issue by geraldhumphries** [jhipster/generator-jhipster#2000]
After clicking save the response is this error:

```
Required request body content is missing: org.springframework.web.method.HandlerMethod$HandlerMethodParameter@d03bdbc7
```

Caused here in load-detail.controller.js:
```
$scope.load = entity;
$scope.load = function(id) {
    Load.get({id : id}, function(result) {
        $scope.load = result;
    });
};
```

When the Load.save() is called, $resource will only add a request body if the object to be saved isn't a function. Since a function was assigned to $scope.load the request will be made without any body, causing the 400 response.

**Comment by deepu105** [comment]
I guess we need to rename the common functions to be more generic and less susceptible to entity name clashes

**Comment by jdubois** [comment]
Yes, this happens quite often and there are many names issues here... Maybe we could prefix everything with "jhi", but then again we didn't want to have JHipster written everywhere...
The only solution at the moment is to add "load" to our list of reserved keywords -> it's not that bad, that's how a lot of system work, like databases for example

**Comment by deepu105** [comment]
Ya may be we can rethink this for JH 3.0 and for now just can add to the
list
