### ISSUE TITLE
Migrate from Spring Cloud Sleuth to Micrometer Tracing

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#20004]
##### **Overview of the issue**

Migrate from [Spring Cloud Sleuth](https://spring.io/projects/spring-cloud-sleuth) to [Micrometer Tracing](https://micrometer.io/docs/tracing).

##### **Motivation for or Use Case**

This is the way with Spring Boot 3.0:

https://twitter.com/springcloud/status/1580315720717516800

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/19782

**Comment by mraible** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/20011.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/112897.

**Comment by DanielFran** [comment]
@mshima approved
