### ISSUE TITLE
CloudFoundy deployment does not detect up-to-date 'cf' executable

### ISSUE THREAD

**Issue by flo-f** [jhipster/generator-jhipster#2001]
Environment:
* generator-jhipster version 2.20.0
* cf for OS X and Linux version 6.12.3

Running Command:
`yo jhipster:cloudfoundry` 
fails with error:
`Creating Cloud Foundry deployment files`
`✖ cloudfoundry's cf command line interface is not available. You can install it via https://github.com/cloudfoundry/cli/releases`

**Issue:**
* the generator checks for `cf --version` which seems broken in the mentioned release of `cf` - it returns:
`--version' is not a registered command. See 'cf help'`
* Changing the command to `cf -v` fixes the issue:
`cf version 6.12.3-c0c9a03-2015-08-31T20:29:20+00:00`

**Comment by jdubois** [comment]
PR merged!
