### ISSUE TITLE
Remove duplicate imports

### ISSUE THREAD

**Issue by emilpaw** [jhipster/generator-jhipster#20015]
##### **Overview of the feature request**

Remove duplicate imports and activate the "import/no-duplicates" eslint rule.

##### **Motivation for or Use Case**

Improve the code quality.

##### **Related issues or PR**
#19182 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
Closed in https://github.com/jhipster/generator-jhipster/pull/22909
