### ISSUE TITLE
Remove usage of `any` type and improve jdl types

### ISSUE THREAD

**Issue by emilpaw** [jhipster/generator-jhipster#20037]
##### **Overview of the feature request**

As discussed here https://github.com/jhipster/generator-jhipster/pull/19856#discussion_r994928906 we have a lot of `any` types in the TypeScript modules. The goal is to remove most of them and make the types more accurate. This probably can't be done at once instead we should remove the `any`s bit by bit.

##### **Motivation for or Use Case**

To fully leverage TypeScripts benefits the amount of the `any` type needs to be reduced.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@mshima Is there anything to do here?

**Comment by mshima** [comment]
Yes, but nothing urgent.
