### ISSUE TITLE
Improve types related to jdl parsing

### ISSUE THREAD

**Issue by emilpaw** [jhipster/generator-jhipster#20035]
##### **Overview of the feature request**

As mentioned in https://github.com/jhipster/generator-jhipster/pull/19856#discussion_r994937881 the modules related to the jdl parsing are typed very loosely. There is a lot to be improved.

##### **Motivation for or Use Case**

Better type safety makes the code easier to maintain.

##### **Related issues or PR**

#19856 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Lets keep a single issue for jdl types.
Closing in favor of https://github.com/jhipster/generator-jhipster/issues/20037
