### ISSUE TITLE
Requests to gateway fail thanks to 401 from Keycloak when gateway silently calls operation realms/realmName/protocol/openid-connect/userinfo

### ISSUE THREAD

**Issue by Delirante** [jhipster/generator-jhipster#20063]
##### **Overview of the issue**

Keycloak endpoint "realms/realmName/protocol/openid-connect/userinfo" is called with every request made to gateway and not just once as is written in comment "// Retrieve user info from OAuth provider if not already loaded".
Problematic code was added in this commit (few minor changes were added in later commits) https://github.com/atomfrede/generator-jhipster/commit/a9db8bbb4e9cd21bfb0e9b2d236ba5d3e37a5550.
Concretely problem is with implementation of method enrich() in class SecurityConfiguration.

Because of this all requests to gateway fails for users which are already in Caffeine cache, their first JWT have expired and they are using another valid JWT for calls.
I believe this is because all calls to operation userInfo in Keycloak are using old expired JWT.

##### **Motivation for or Use Case**

Requests to gateway fail with http error 500 and with http error 401 as message.

##### **Reproduce the error**

    1. Generate JWT for user.
    2. Call some operation on gateway which needs authentication.
    3. Wait until JWT expires + 2 min.
    4. Generate new JWT for user.
    5. Call that endpoint again.
    
    You will receive 500 error with 401 as message.

##### **Related issues**

There is not any.

##### **Suggest a Fix**

You need to change implementation of method enrich() in class SecurityConfiguration. Look how implementation of method get() in Cache.class of Caffeine is described: Returns the value associated with the key in this cache, **obtaining that value from the mappingFunction if necessary**.

I believe that part of code which calls userInfo operation in Keycloak should not be called always but just once. So you need to implement it that way.

##### **JHipster Version(s)**

7.9.3

##### **JHipster configuration**

Jhipster info:
Welcome to JHipster v7.9.3

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```                                                       
gateway@0.0.0 C:\****
`-- generator-jhipster@7.9.3                              

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "baseName": "gateway",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "no",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1638778233951,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.3",
    "jwtSecretKey": "*****",
    "languages": ["en", "sk"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "******",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": true,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "eureka",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": true,
    "skipFakeData": false,
    "skipUserManagement": true,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

git version 2.28.0.windows.1

node: v16.18.0

npm: 8.19.2

Docker version 20.10.17, build 100c701

docker-compose version 1.29.2, build 5becea4c

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
We call the [get method of the caffeine cache](https://github.com/jhipster/generator-jhipster/blob/f04bce348443ab001247661294ad247e2fadf848/generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs#L436), so the cache decides when to call the mapping function and retrieve a new value for the key. 

So either there is a bug in caffeine (don't think so), we have done a mistake, but just calling get with a lambda does look okay. So maybe the cache key is not a good choice. Will need some debugging, but thanks for the detailed report with all information needed as it seems.

**Comment by Delirante** [comment]
Yes, one of solutions can be not using Mono<Jwt> as value in Caffeine cache.
Another can be call block() method after method bodyToMono(), so result will be actually extracted (not sure this will help on 100%).
Or another can be extract whole code which calls userinfo operation on keycloak out of lamba function.

**Comment by shrralis** [comment]
I also bumped into this issue recently.
My fix for this is in these lines: https://github.com/jhipster/generator-jhipster/blob/a5138a04b1a536f47b59bacd1dc84ede9ab8e0cd/generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs#L398-L432

What I did was something like ...
 ```java
return Optional.ofNullable(users.getIfPresent(jwt.getSubject()))
    .orElseGet(...
        WebClient.create()
            ...
            .doOnNext(newJwt -> users.put(jwt.getSubject(), Mono.just(newJwt)))
    );
```

**Comment by mraible** [comment]
Adding bug bounty.

**Comment by shrralis** [comment]
Bug bounty claimed https://opencollective.com/generator-jhipster/expenses/156324
