### ISSUE TITLE
Cloud Foundry deployment fails on Java 8

### ISSUE THREAD

**Issue by drissamri** [jhipster/generator-jhipster#2009]
Not all Cloud Foundry providers uses the [Java buildpack](https://github.com/cloudfoundry/java-buildpack) as default Java buildpack. 

As an example, IBM Bluemix uses their [IBM JDK buildpack](https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack) which is also able to run standalone jars/wars. The problem is that this by default runs JDK 7, so Java 8 applications will fail.

```
2015-09-14T12:41:57.95+0200 [App/0]      ERR Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=be/craftworkz/ucll/Application, offset=6
````
I think the best solution is to specify the buildpack in the Cloud Foundry manifest that is generated by JHipster so the behaviour will be consistent in every CF instance (anynines, PWS, Bluemix, Stackato, ...). This is easily done by adding the following line:
```
  buildpack: https://github.com/cloudfoundry/java-buildpack
```

If you agree, I'll send a pull request to change this.

**Comment by jdubois** [comment]
I didn't know about this, so I can only trust you!!

I'm currently really fed up to have to maintain JDK 7 in JHipster, so it will be be removed quite soon -> I will announce it is deprecated in the next release.

OK to merge this, does anyone else has an opinion on this?

**Comment by drissamri** [comment]
The problem is not really with Java 7 or 8 but different default settings on different Cloud Foundry providers. I'll pull request it later tonight and see if any other problems show up on Bluemix that might be prevented by setting more defaults in the manifest.

Nonetheless it will be nice when the generator code can ditch Java 7.. ;-)

**Comment by drissamri** [comment]
I have added pull request #2016 for this.

**Comment by jdubois** [comment]
Fixed as the PR is merged
