### ISSUE TITLE
Drop AngularCookieLocaleResolver or rename

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#20106]
##### **Overview of the feature request**

Leftover from angularjs (angular 1).
https://github.com/angular-translate/angular-translate/blob/d727abb0cae045c1f645bb7a92f06f8240875987/src/service/storage-key.js

##### **Motivation for or Use Case**

Cleanup

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by shrralis** [comment]
Bug bounty claimed https://opencollective.com/generator-jhipster/expenses/200339
