### ISSUE TITLE
Investigate simplifying gateway/microservice oauth2 config.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#20102]
##### **Overview of the feature request**

We currently implement some custom filters which probably can be replaced by spring-cloud features.
Like replacing our custom token relay filter with [token relay filter](https://github.com/spring-cloud/spring-cloud-gateway/blob/3e83068cc24ae5a7987726a62267c4a5b7a26877/docs/src/main/asciidoc/spring-cloud-gateway.adoc#token-relay-gatewayfilter-factory)

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
FWIW, we already use [TokenRelay](https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/resources/config/application.yml.ejs#L174) for Spring Cloud Gateway.

**Comment by mshima** [comment]
Ok https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/client/TokenRelayRequestInterceptor.java.ejs is something else then.

https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/client/AuthorizedUserFeignClient.java.ejs,  https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/client/OAuth2_UserFeignClientInterceptor.java.ejs and https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/client/OAuth2UserClientFeignConfiguration.java.ejs looks unused

**Comment by mshima** [comment]
@mraible what's the reason for those feign configurations?
Can be dropped from default?

**Comment by mshima** [comment]
There is only references at openapi generator.
https://github.com/jhipster/generator-jhipster/search?p=1&q=feign

I suppose we can drop feign support. Or modularize if needed.

**Comment by Tcharl** [comment]
Also noticed that client credentials flow isn't supported by our SecurityUtils class.

I used to use UserFeignInterceptor for service-to-service communication: client credentials vs authorization code flow
