### ISSUE TITLE
Security audits: successful authentication is logged 3 times

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2011]
As mentioned in #1882 when a user successfully logs in, this writes 3 successful events in the audit table.
Of course we should only have one event logged.

**Comment by pascalgrimaud** [comment]
Same here https://github.com/spring-projects/spring-boot/issues/4355

**Comment by pascalgrimaud** [comment]
I think this commit https://github.com/spring-projects/spring-boot/commit/cc3f673874a9ae98e6512ec4e3d8ae13903899fc will fix this issue
