### ISSUE TITLE
Switch to Turbopack

### ISSUE THREAD

**Issue by vicpermir** [jhipster/generator-jhipster#20126]
##### **Overview of the feature request**

Consider using [Turbopack](https://turbo.build/) instead of Webpack.

Link to the github repo: https://github.com/vercel/turbo

##### **Motivation for or Use Case**

Turbopack seems to be the natural successor of Webpack with a focus on extensibility and performance.
Webpack is famously known for being slow, something that Turbopack aims to fix.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by zhx828** [comment]
https://turbo.build/pack/docs/features/frameworks#vue-and-svelte I think we would not consider until it supports Angular/React/Vue?

**Comment by mshima** [comment]
We supported webpack so it was easier and consistent to maintain a single tooling.
But the situation has changed a lot, and we have very good alternatives.
IMO we should support the frontend official tooling now.

angular -> angular-cli (currently uses webpack)
vue -> vite
react -> was webpack through react-react-app, but I think it's somewhat just in maintenance now. developers seems to prefer vite.

**Comment by mraible** [comment]
I agree with your recommendations @mshima.

**Comment by Tcharl** [comment]
The commercial argument for turbopack seems awesome, I think that it needs some tryout at least.
They benchmarked it 1.5s startup compared to 7s on a vite build

**Comment by yelhouti** [comment]
I agree with @mshima too we should always strive to use the default for each framework as it make it easier for existing to projects to migrate in, and though who want to leave to migrate out.
Also it removes the maintenance/migration burden from the jhipster team

**Comment by vicpermir** [comment]
Makes perfect sense to support the official tooling, I opened this issue because turbo seems to be an order of magnitude faster than vite, and several faster than webpack.

In this case, do we just wait for the people behind the frontend frameworks to make the switch themselves?

Thank you.
