### ISSUE TITLE
More frontend only generator with equivalent features (other/generic backend techs etc.) ??

### ISSUE THREAD

**Issue by fabm22** [jhipster/generator-jhipster#2014]
Hi.

Jhipster is a great project, and real missing block. I get it has its "offer" and opiniated way of doing things, and it doesn't aim to cover all use cases, like frontend only generator.

Though I wonder if you guys would know some fork or equivalent that would give the same very cool feature of generating UI for some entities/db objects (pure REST only contracts?) ? Maybe with more options to switch between some UI components ??

**At the moment if I want to use only the UI generating capabilities of JHipster I still HAVE to use it in the form of a full featured Spring project right ?**

Thanks a lot for confirmation.

**Comment by dancancro** [comment]
[Here's](http://www.dancancro.com/information-shortages/) my collection of them. I call them 'Starters'. If you would like to know more about any of them or see detailed trade-off reports, just answer a questionnaire [here](http://www.dancancro.com/technology-questionnaires/) about something you know. 

Sharing is caring.

**Comment by deepu105** [comment]
I guess you got your answer, if not try something like the angular generator
