### ISSUE TITLE
Possibility to chose scale and precision of BigDecimal

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2015]
Currently, the generator uses precision 10 and scale 2 which doesn't cover all use cases

**Comment by jdubois** [comment]
Yes, unfortunately we can't cover all use cases, at some point you need to code something :-)
It's also easier for people to recode something, than to learn what some JHipster option does -> that's why we have policy 2 at http://jhipster.github.io/policies.html

**Comment by cbornet** [comment]
Well, it would just be a constraint validation on BigDecimal fields, not an option of the main generator. So users would see his option only if they want to.

**Comment by cbornet** [comment]
If you don't want to add more questions to the generator which I can understand, can we have it at least for JDL, Jhipster-uml, manual edit ? See https://github.com/jhipster/jhipster-uml/issues/26
I can do the PR if OK.
