### ISSUE TITLE
Please make Jhipster support for vue 3.

### ISSUE THREAD

**Issue by changzheng0101** [jhipster/generator-jhipster#20152]
when I use Jhipster，I choose vue. But I only get code for vue 2.Vue 2 has been deprecated for a long time.Please support for vue 3!Thanks a lot.

**Comment by mshima** [comment]
Vue 2 is not deprecated.
It has recently received a few vue 3 features.

Duplicated of https://github.com/jhipster/generator-jhipster/issues/12558.
You can see discussion about vue3 support there.
