### ISSUE TITLE
Pagination not working correct

### ISSUE THREAD

**Issue by aleksandarbosancic** [jhipster/generator-jhipster#2021]
Pagination not working correct default value is '20' always because client send incorrect query param to server. Need to change in template generator 'per_page' to 'size'.

[Request parameters evaluated for Pageable instances](http://docs.spring.io/spring-data/commons/docs/current/reference/html/#core.web)

>        $scope.loadAll = function () {
>            User.query({page: $scope.page, per_page: 5}, function (result, headers) {
>                $scope.links = ParseLinks.parse(headers('link'));
>                $scope.users = result;
>            });
>        };

to

>        $scope.loadAll = function () {
>            User.query({page: $scope.page, size: 5}, function (result, headers) {
>                $scope.links = ParseLinks.parse(headers('link'));
>                $scope.users = result;
>            });
>        };

**Comment by jdubois** [comment]
This has changed in the latest (2.21.0 version), please follow our guidelines and give us your version number!

I've checked and in the latest release we do use "size", so it should be working, this is why I'm closing this -> if you can check your version number, and do still find the problem, can you comment on this issue? I will reopen it if needed, of course
