### ISSUE TITLE
Max number validation greater than Integer.MAX_VALUE

### ISSUE THREAD

**Issue by dalbelap** [jhipster/generator-jhipster#2025]
This is a very simple little problem. When it is created an entity numeric field, if validation maximum value is greater than Integer.MAX_VALUE(2147483647 in Java), the "Max" annotation must include a "L" at the end (as Long number).

I try in my forked jhipster and commited the changes (sorry, used spaces instead tabulation in new lines):
- [entity/templates/src/main/java/package/domain/field_validators.ejs](https://github.com/dalbelap/generator-jhipster/blob/master/entity/templates/src/main/java/package/domain/field_validators.ejs)
```javascript
 var MAX_VALUE = 2147483647;
  ...
  if (rules.indexOf('max') != -1) {
        var isLong = (field.fieldValidateRulesMax > MAX_VALUE) ? 'L' : '';
        validators.push('@Max(value = ' + field.fieldValidateRulesMax + isLong + ')');
  }
```
- [entity/templates/src/main/java/package/web/rest/dto/_EntityDTO.java](https://github.com/dalbelap/generator-jhipster/blob/master/entity/templates/src/main/java/package/web/rest/dto/_EntityDTO.java)
```javascript
  var MAX_VALUE = 2147483647;
  ...
  @Max(value = <%= fields[fieldId].fieldValidateRulesMax %><%= (fields[fieldId].fieldValidateRulesMax > MAX_VALUE) ? 'L' : '' %>)<% } %><% if (fields[fieldId].fieldValidateRules.indexOf('pattern') != -1) { %>
```

**Comment by jdubois** [comment]
- When you say numeric field -> what option did you select exactly in the entity sub-generator?
- I see you correct the DTO, you should also correct the underlying entity
- As you have coded this, could you also provide a PR? It would be much simpler for us to integrate

**Comment by dalbelap** [comment]
- long
- field_validators.ejs yet creates the code with "@Max(value = [longNumber]L" in the entity class.
- PR send

**Comment by jdubois** [comment]
Close as the PR is merged
