### ISSUE TITLE
need to use jhipster generated entities, etc from standalone application

### ISSUE THREAD

**Issue by smart987** [jhipster/generator-jhipster#2028]
First of all thanks for the excellent tool. Using Jhipster I have successfully configured and running angularjs application fine from front end. I have created many custom entities also successfully. Now, in the project I want to have a load.java file and make use of those created entities to load the data from csv files to those entity tables. I mean with out using front end (Angulars), I should be able to use to all the created entities and crud operations from load.java, is it possible to do it? If yes, any sample code reference would be helpful, i did not find any documentation on this part on the website.
Thanks,

**Comment by deepu105** [comment]
First of all this is not suitable in this forum, try statck overflow with jhipster tag
Second why would you want to do that?  If you just want to load data from csv you can do it via liquibase, take a look at how we load users as csv
