### ISSUE TITLE
User Management broken without Angular Translate

### ISSUE THREAD

**Issue by RoryHunter** [jhipster/generator-jhipster#2030]
The User Management admin feature doesn't work if Angular Translate isn't included.

Steps to reproduce:

1. Generate a jhipster project, accepting all default values but answering "n" to translation support
2. Run the project with `mvn`
3. Go to http://localhost:8080/ and login in with admin/admin
4. Open the "Administration" menu at the top.
    - The text should read "User Management", but instead it reads "user-management"
    - Clicking the link does nothing.

Versions:
- generator-jhipster@2.21.0 
- node v0.12.0
- mvn 3.2.3

**Comment by jdubois** [comment]
I guess we should not have a "-" in "user-management". Can someone test this out?

**Comment by twelve34** [comment]
I think then problem is into the file: user-management.js
The generator didn't remove the translation part into the resolve section (2 times).

--- a/src/main/webapp/scripts/app/admin/user-management/user-management.js
+++ b/src/main/webapp/scripts/app/admin/user-management/user-management.js
@@ -17,10 +17,6 @@ angular.module('testapp')
```javascript
                     }
                 },
                 resolve: {
-                    translatePartialLoader: ['$translate', '$translatePartialLoader', function ($translate, $translatePartialLoader) {
-                        $translatePartialLoader.addPart('user-management');
-                        return $translate.refresh();
-                    }]
                 }
             })

**Comment by atomfrede** [comment]
Both is right, I'll provide a fix for this.

**Comment by jdubois** [comment]
Thanks @atomfrede !
I will do a new minor release soon
