### ISSUE TITLE
Customisation for European Commission: integration with eUI and EU Login

### ISSUE THREAD

**Issue by deck80** [jhipster/generator-jhipster#20312]
##### **Overview of the feature request**

The feature request is about the integration in JHipster of the eUI F/E framework and the EU Login authentication mechanism. 
##### **Motivation for or Use Case**
All the web applications created by the European Commission should be developed following guidelines and best practices.
For Angular-base app, for instance, the eUI platform should be used: https://eui.ecdevops.eu/
In general, all applications should use a two-factor authentication, which is assured by the use of the European Commission's authentication service EU Login : https://webgate.ec.europa.eu/cas/about.html

Having this integration would mean:
- rapid prototyping and creation of internal application that could be easily created without the use of external contractors, thus saving EU contributors' money
- rapid prototyping and creation of applications by EU contractors, thus again saving contributors' money

##### **Related issues or PR**

No similar tickets found in the history list.
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deck80** [comment]
I can take care of this in my (very limited) spare time but I need guidance.
I have little to zero knowledge of JHipster customisation.

**Comment by atomfrede** [comment]
Is this only related to frontend?

**Comment by deck80** [comment]
> Is this only related to frontend?
In short: maybe.
Long version:
I am not sure as it would need a customization of the login mechanism: EU Login is OpenID compliant, so it *could* be just frontend. I was going to investigate how we have integrated this before in other apps...
On the other hand, I still have doubts on the complexity of the integration of eUI as it is not easy to integrate, according to the feedback from other developers.

**Comment by gmarziou** [comment]
Few things:

* this is a niche requirement, who is building apps for the EU in our users?
* eUI covers only Angular, so not a candidate for the core generator

So this makes me think that it should be a blueprint

**Comment by deck80** [comment]
> Few things:
> 
> * this is a niche requirement, who is building apps for the EU in our users?
> * eUI covers only Angular, so not a candidate for the core generator
> 
> So this makes me think that it should be a blueprint

I agree this should be a blueprint.
Regarding the users: I am a PM at the EC and I can assure it would be very interesting to have this blueprint to speed up prototyping.
For the B/E: I would like btw to do the same thing starting from .Net Core blueprint as well.

**Comment by deck80** [comment]
I am coming back to this: do you know any tutorial that is explaining in depth how to create a blueprint? I think the site wiki is quite poor of details...
TIA

**Comment by gmarziou** [comment]
Only these chapters from the official doc: 

- https://www.jhipster.tech/modules/extending-and-customizing/
- https://www.jhipster.tech/modules/creating-a-module/
- https://www.jhipster.tech/modules/creating-a-blueprint/

**Comment by deck80** [comment]
Indeed, gmarziou, I think we can agree we don't have much documentation...
However if anybody (maybe somebody who created a blueprint himself) step by and want to share some insight or documentation it is well appreciated.
I guess I need to start digging a bit.
Maybe I didn't add that I would be interested in having the back-end in .Net core as well. But for this it will be enough to "enrich" the .NET blueprint I find in the list...again, after having taken a look at it.
No pain no gain, isn't it?

**Comment by ko5tik** [comment]
If there is still a demand I can  do this - have spare time between the projects

**Comment by deck80** [comment]
Of course there is still demand...
________________________________

**Comment by ko5tik** [comment]
> Of course there is still demand...
as I do no have any clue yet how those EU libraries are supposed to work ,    gotod starting point would be to share what exactly ought to be  generated.   From this  starting point we can determine which metadata bluepring shall use and create templates

**Comment by ko5tik** [comment]
If you can provide some samples  what ought to be generated   we can whip up a repo and collaborate on it
