### ISSUE TITLE
Update Elasticsearch documentation for Spring Boot 3

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#20348]
##### **Overview of the issue**

It seems it's out of date because it references Jest and we now use the Elasticsearch Java Client with Spring Boot 3.

##### **Motivation for or Use Case**

Docs should be up-to-date. 

##### **Related issues**

- https://github.com/jhipster/generator-jhipster/issues/19934

##### **Suggest a Fix**

Create a PR for the jhipster.github.io repo.

##### **JHipster Version(s)**

v8

**Comment by mraible** [comment]
@frascu Are you interested in helping out with this documentation update?

**Comment by frascu** [comment]
@mraible yes, I can

**Comment by atomfrede** [comment]
I guess we can close this already? Documentation has been updated, correct?

**Comment by frascu** [comment]
Yes, you can
