### ISSUE TITLE
JHipster does not recognize Node.js 18 as LTS

### ISSUE THREAD

**Issue by vdespa** [jhipster/generator-jhipster#20349]
##### **Overview of the issue**

JHipster issues the following warning when used with Node.js 18: "WARNING! Your Node version is not LTS (Long Term Support), use it at your own risk! JHipster does not support non-LTS releases, so if you encounter a bug, please use a LTS version first."

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/1197635/202323488-81a1942c-ecb6-4ea1-b6d5-ffd0aa7b16f2.png">

##### **Reproduce the error**

Run `jhipster`

##### **JHipster Version(s)**

JHipster v7.9.3

##### **Browsers and Operating System**

macOS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Yes, we should fix this. I'll add a bug bounty.

**Comment by mshima** [comment]
@DanielFran assigned to you. 😄 
`WARNING! Your Node version is not LTS (Long Term Support), use it at your own risk! JHipster does not support non-LTS releases, so if you encounter a bug, please use a LTS version first.`
The error message seems the node is 18 prior to LTS version.

The logic looks ok:
https://github.com/jhipster/generator-jhipster/blob/bb188e00ca686d506658737ed7f91c478a7afcce/generators/base/generator-base-private.mjs#L511-L515

Just need a new release.

**Comment by mraible** [comment]
Are we sure JHipster v7 works with Node 18? [This issue](https://github.com/jhipster/generator-jhipster/issues/20362) suggests it does not.

**Comment by antarus** [comment]
![image](https://user-images.githubusercontent.com/928683/202715711-f94b1167-2ea6-4b91-8af1-028340105ce2.png)

**Comment by mshima** [comment]
Following https://github.com/jhipster/generator-jhipster/pull/20394:
- jhipster upgrade test is broken, it install latest released jhipster which is broken. So a new release will fix the upgrade test.
- wait-on is broken due to a node bug: https://github.com/jeffbski/wait-on/issues/127#issuecomment-1300959898

Generation works and as long as `./npmw` is used instead of the system node/npm, the application will work fine.

**Comment by vdespa** [comment]
> with 18, I don't get the same error when I run it.

That is issue #19627

**Comment by dagboujhatem** [comment]
With the node V18.15.2 I don't get the same error when I run it. 
OS: macOS

**Comment by dagboujhatem** [comment]
I fixed the error in my pc and managed to run jhipster with version 18 of the node. 

[Link of pull request](https://github.com/jhipster/generator-jhipster/pull/21726) 💯

**Comment by ljoboy** [comment]
With node v18.16.0 same error
OS: Linux Mint

**Comment by BrayanMnz** [comment]
Are you working on this @DanielFran ?

**Comment by BrayanMnz** [comment]
Seems like just a release was needed and this is not an issue anymore. 
maybe this can be closed.

**Comment by deepu105** [comment]
closing as release v7.9.4 is being done

**Comment by vishal423** [comment]
Blueprints still doesn't work with nodejs v18 due to incorrect module exports on the JHipster side. Refer https://github.com/jhipster/generator-jhipster-svelte/issues/1841

@deepu105 , can we reopen?

**Comment by mshima** [comment]
Changing the package.json exports for generator-jhipster will almost for sure be a breaking change.
We support node 18 in v8.
Closing.
