### ISSUE TITLE
JHipster 7.9.0+ integration tests fail using MariaDB for devDatabaseType 

### ISSUE THREAD

**Issue by logicglobe** [jhipster/generator-jhipster#20352]
##### **Overview of the issue**

All integration tests fail on JHipster 7.9.0, 7.9.2 and 7.9.3, on Windows and Linux, when choosing `devDatabaseType mariadb` or `devDatabaseType postgresql`  (did not test on any other production level databases)

(All integration tests SUCCEED on JHipster 7.8.1 and earlier on Windows and Linux. Additionally, integration tests succeed on JHipster 7.9.0+ if you select the default `devDatabaseType h2Disk`)

You can find more details on Stackoverflow here:
https://stackoverflow.com/questions/74440550/new-jhipster-project-all-integration-tests-fail

##### **Motivation for or Use Case**

To run integration tests against a configuration that more closely matches production.

##### **Reproduce the error**
<details>
<summary>Project configuration file (myapp.jh)</summary>
<pre>
```
application {
  config {
    baseName myapp,
    packageName com.mycompany.app,
    applicationType monolith,
    authenticationType jwt,
    cacheProvider ehcache,
    enableHibernateCache true,
    databaseType sql,
    devDatabaseType mariadb,
    prodDatabaseType mariadb,
    buildTool gradle,
    clientPackageManager npm,
    clientFramework angular,
    clientTheme minty,
    clientThemeVariant primary,
    testFrameworks [cypress],
    nativeLanguage en,
    languages [en, es],
    jhiPrefix myapp,
    jwtSecretKey "YjAwZDU2ODI3NzNjZjk0NjVhY2UzNGViZmY0YjY1ZGY2MDI5MTc5Y2FlZWYxNzE5Yjg5ZjMxOGZhZTgwZjA5NTFkN2VmNDM3ZGMyZDNjZTViNDAwYTg4NmNlMmM2ZDkxZTMwMDk5YmUxNWNkZmE0YTNiNDlhMGNhZmM4OTk1NmQ="
  }
}
```
</pre>
</details>

Performed the following steps in a command shell:
* Install the latest version of JHipster: `npm install -g generator-jhipster` --> **v7.9.3**
* Import the JDL: `jhipster jdl myapp.jh`
* Build the application: `./gradlew build`
* *Alternatively* run the integration tests directly: `./gradlew integrationTest`

*Result*: Everything appears to build nicely up until the integration tests at the end, which **ALL fail!**

Gradle scan output available here: https://scans.gradle.com/s/ur5vwgh7clgxo

(Also repeated tests using Maven build tool -- ALL integration tests failed for the same reasons.)

##### **Related issues**

None that I know of.

##### **Suggest a Fix**

Don't know, but I suspect it has something to do with the test container configuration in `/src/test/java/com/.../app/config/`

(Not a fix, but a temporary solution to get your development going is to choose the default `devDatabaseType h2Disk`, all tests will pass for all versions on all platforms.)

##### **JHipster Version(s)**

Confirmed for 7.9.0, 7.9.2 and 7.9.3 on Windows 10 and Linux (openSUSE 15.4)

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>

```
$ jhipster info
INFO! Switching to JHipster installed locally in current project's node repository (node_modules)
(node:8972) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./lib/util/" in the "exports" field module resolution of the package at C:\Source\IdeaProjects\read_new\0\myapp\node_modules\yeoman-environment\package.json.
Update this package.json to use a subpath pattern like "./lib/util/*".
(Use `node --trace-deprecation ...` to show where the warning was created)

     ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
     ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
     ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                         https://www.jhipster.tech
Welcome to JHipster v7.9.3

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

myapp@0.0.1-SNAPSHOT C:\Source\IdeaProjects\read_new\0\myapp
└── generator-jhipster@7.9.3


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


SUMMARY: .yo-rc.json file:
{
 "generator-jhipster": {
  "applicationIndex": 0,
  "applicationType": "monolith",
  "authenticationType": "jwt",
  "baseName": "myapp",
  "blueprints": [],
  "buildTool": "gradle",
  "cacheProvider": "ehcache",
  "clientFramework": "angularX",
  "clientPackageManager": "npm",
  "clientTheme": "minty",
  "clientThemeVariant": "primary",
  "creationTimestamp": 1668548472998,
  "databaseType": "sql",
  "devDatabaseType": "mariadb",
  "devServerPort": 4200,
  "dtoSuffix": "DTO",
  "enableGradleEnterprise": false,
  "enableHibernateCache": true,
  "enableSwaggerCodegen": false,
  "enableTranslation": true,
  "entities": [],
  "entitySuffix": "",
  "gradleEnterpriseHost": "",
  "jhiPrefix": "myapp",
  "jhipsterVersion": "7.9.3",
  "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
  "languages": ["en", "es"],
  "messageBroker": false,
  "nativeLanguage": "en",
  "otherModules": [],
  "packageFolder": "com/mycompany/app",
  "packageName": "com.mycompany.app",
  "pages": [],
  "prodDatabaseType": "mariadb",
  "reactive": false,
  "searchEngine": false,
  "serverPort": "8080",
  "serviceDiscoveryType": false,
  "skipCheckLengthOfIdentifier": false,
  "skipClient": false,
  "skipFakeData": false,
  "skipUserManagement": false,
  "testFrameworks": ["cypress"],
  "websocket": false,
  "withAdminUi": true
 }
}


##### **Environment and Tools**

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

git version 2.38.1.windows.1
node: v16.17.0
npm: 8.19.1

```

  </pre>
  </details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None.

##### **Browsers and Operating System**

<details>
<summary>My environment</summary>
<pre>
```
Windows 10 22H2 build 19045.2251 (64 bit) and Linux (openSUSE 15.4)
OpenJDK Runtime Environment Temurin-17.0.5+8
node 16.17.0
npm 8.19.1
Gradle 7.5.1
MariaDB 10.6.8 and PostgreSQL 15.1
Chrome 107.0.5304.107
```
</pre>
</details>

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Do you have docker installed and is the daemon running? The error message says no docker environment found.

**Comment by logicglobe** [comment]
Woah! Something funky with my windows docker.  Reinstalled and all is good now!  Thanks for the help!
