### ISSUE TITLE
r2dbc-mariadb doesn't support spring-boot 3 / spring-data-relational

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#20363]
##### **Overview of the issue**

Don't allow to generate webflux + mariadb/mysql if problem persist by final v8.

References:
https://github.com/spring-projects/spring-data-relational/issues/1364#issuecomment-1289124846
https://github.com/jhipster/generator-jhipster/pull/20351

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
@mshima Can this be closed?

**Comment by mshima** [comment]
@atomfrede it was broken again. https://github.com/jhipster/generator-jhipster/pull/24199 should fix it again.
