### ISSUE TITLE
Enhancement request: Add AppId or AppName in the User Management app/database

### ISSUE THREAD

**Issue by vbhatt** [jhipster/generator-jhipster#2037]
I am creating multiple apps using jhipster but want to use the same cassandra backend user management database schema but differentiate the users for each application. Could User Management function be enhanced so multiple apps can leverage that function by just adding an appid or appname attribute in the user/app creation process.

**Comment by atomfrede** [comment]
I think this is a special case that won't make it into the generator. CC @jdubois @deepu105 @gzsombor @gmarziou @andidev what do you think?

**Comment by jdubois** [comment]
Yes, we only do authentication for the current app.
If you need something more complex, and this is indeed something I am looking into, you should use an external authentication server, like CloudFoundy UAA

**Comment by deepu105** [comment]
I guess this should not be added as its a very specific use case. you can reuse the same DB for multiple apps even without this addition

**Comment by vbhatt** [comment]
Currently the user management feature gets generated for each app separately instead I wanted to use the same user management feature for all the apps (they are separate keyspaces) hence this request. The same user could belong to multiple applications so an access control based on an appid would do the trick.

**Comment by gmarziou** [comment]
Correct but as said above we won't do it, feel free to share your experience about an external service as suggested.
