### ISSUE TITLE
Update angular to v15

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#20385]
##### **Overview of the feature request**

Angular v15 has been released.
Dependencies must add support before updating.

- [x] ng-bootstrap: https://github.com/ng-bootstrap/ng-bootstrap/issues/4419
- [x] angular-eslint: https://github.com/angular-eslint/angular-eslint/issues/1205
- [ ] angular-builders: https://github.com/just-jeb/angular-builders/issues/1312
- [ ] angular-jest-preset: https://github.com/thymikee/jest-preset-angular/issues/1838
- [x] ngx-webstorage
- [x] ngx-infinite-scroll: https://github.com/orizens/ngx-infinite-scroll/pull/413

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by alexvrv** [comment]
ngx-webstorage - now supports Angular 15 with v11.1.1

**Comment by mshima** [comment]
@DanielFran bug bounty claimed https://opencollective.com/generator-jhipster/expenses/120309

**Comment by DanielFran** [comment]
@mshima approved
