### ISSUE TITLE
Translation json files of entities have top-level appName

### ISSUE THREAD

**Issue by rroukens** [jhipster/generator-jhipster#2038]
Hi, I don't understand why the translation files of the created entities have as top-level the "appName". All other json files just start with the object of class of whatever-name, not the appName. This is not very consistent and also annoying because I don't want to have my appName everywhere in my code and json and html, etc. This level can be removed when generating the json files from the entities. Or is there a good reason for this?
{
    "myApp": {
        "entity" : {
            "home": {
                "title": "Entity",
       
Could just become:
{
      "entity" : {
          "home": {
              "title": "Entity",

Rogier

**Comment by jdubois** [comment]
The main idea is that they are at a different level than the other keys, so you are free to use whatever keys you want.
Then, we could have called the top prefix "app" or "entities". It just felt better to use the name of your app, at least that's how I would have called it.

**Comment by rroukens** [comment]
I understand that it's a different level than the top-level files. Choosing a name that defines the top-level like "entities" would be more generic and proper in my opinion. But of course I know how this goes and we can discuss this kind of choices for days ;-).

I think it would be better to name the level "entities" but if I'm the only one who thinks that, I will no longer nag about it :-).

**Comment by jdubois** [comment]
- yes this can be discussed for days!
- as we already use "entities" for naming the JS folder, then I agree "entities" would be logical
- then, migrating eveything would be really annoying, and I don't think it would add a lot of value

**Comment by rroukens** [comment]
Fine, thanks for looking into this anyway. You're doing an great job with Jhipster. Keep up the good work!
