### ISSUE TITLE
Grunt doesn't work on jhipster 2.20

### ISSUE THREAD

**Issue by spereverziev** [jhipster/generator-jhipster#2041]
I've generated an app with next steps:

 (1/15) What is the base name of your application? jhipster
 (2/15) What is your default Java package name? com.mycompany.myapp
 (3/15) Do you want to use Java 8? Yes (use Java 8)
 (4/15) Which *type* of authentication would you like to use? Token-based authentication (stateless, with a token)
 (5/15) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL, Oracle)
 (6/15) Which *production* database would you like to use? PostgreSQL
 (7/15) Which *development* database would you like to use? PostgreSQL
 (8/15) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
 (9/15) Do you want to use a search engine in your application? No
 (10/15) Do you want to use clustered HTTP sessions? No
 (11/15) Do you want to use WebSockets? No
 (12/15) Would you like to use Maven or Gradle for building the backend? Maven
 (13/15) Would you like to use Grunt or Gulp.js for building the frontend? Grunt (recommended)
 (14/15) Would you like to use the LibSass stylesheet preprocessor for your CSS? Yes
 (15/15) Would you like to enable translation support with Angular Translate? (Y/n) n

When run grunt from cl I see:

MBPStaneverziev:jproject spereverziev$ grunt serve
Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "ngconstant:dev" (ngconstant) task
Creating module datejinApp at src/main/webapp/scripts/app/app.constants.js...OK

Running "sass:server" (sass) task

Running "browserSync:dev" (browserSync) task
[BS] Proxying: http://localhost:8080
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3004
    External: http://192.168.1.100:3004
 --------------------------------------
          UI: http://localhost:3005
 UI External: http://192.168.1.100:3005
 --------------------------------------
[BS] Watching files...

Running "watch" task
Waiting...

In browser when open http://localhost:3004 the page is just loading forever. 

OS - OS X Yosemite 
Browser - Safari, Chrome
Jhipster -  v 2.20, ( updating to 2.21 doesn't help neither)

**Comment by jdubois** [comment]
Isn't the port 3000, not 3004?

It definitely works on my machine, is anyone able to reproduce?

**Comment by jdubois** [comment]
Hang on: did you ever start your JHipster server first? Like run "mvn" before? It's as simple as that.... Have a look at http://jhipster.github.io/development.html

**Comment by jdubois** [comment]
Closing this as I'm pretty sure you didn't start the Java server...

**Comment by spereverziev** [comment]
You are right, thanks!
