### ISSUE TITLE
Tag @GeneratedByJHipster not added on @interface

### ISSUE THREAD

**Issue by sebastienlabrune** [jhipster/generator-jhipster#20432]
##### **Overview of the issue**

When using "jhipster --with-generated-flag" command, the java generated interface with @interface like EmbeddedMongo.java for exemple have the import tag (import fr.maif.digital.GeneratedByJHipster;), but not the @GeneratedByJHipster.

##### **Motivation for or Use Case**

I'm using jhipster in my french insurance company "MAIF".
Our quality tool tell us that classes are import but not used.

##### **Reproduce the error**

Just run "jhipster --with-generated-flag" and create microservice with mongo support.
The src/test/<package>.config.EmbeddedMongo.java have the import but not the @GeneratedByJHipster

##### **Related issues**

No curent issue.

##### **Suggest a Fix**

Just modify the regular expression in this file: https://github.com/jhipster/generator-jhipster/blob/main/generators/bootstrap/transforms.mjs#L108

      if (!new RegExp(`import ${packageName.replace('.', '\\.')}.GeneratedByJHipster;`).test(content)) {
        const newContent = content
          // add the import statement just after the package statement, prettier will arrange it correctly
          .replace(/(package [\w.]+;\n)/, `$1import ${packageName}.GeneratedByJHipster;\n`)
          // add the annotation before class or interface
          .replace(/\n([a-w ]*(class|@?interface|enum) )/g, '\n@GeneratedByJHipster\n$1');
        file.contents = Buffer.from(newContent);
      }

Just add @? in the regular expression ".replace(/\n([a-w ]*(class|@?interface|enum) )/g, '\n@GeneratedByJHipster\n$1');" will take both form (interface and @interface).

##### **JHipster Version(s)**

Detected with jhipster-generator 7.9.3

##### **Browsers and Operating System**

Macosx

**Comment by DanielFran** [comment]
@sebastienlabrune Can you could nfirm issue is fixed in main branch?

**Comment by mshima** [comment]
It still applies.

**Comment by sebastienlabrune** [comment]
@DanielFran I confirm the problem is not fixed with the main branch. (tested this day)

**Comment by sebastienlabrune** [comment]
Regular expression not ok (it don't include @interface syntax, only interface) in:

https://github.com/jhipster/generator-jhipster/blob/8b7902486bbd80070f49a9e5fc40862b4a19c37e/generators/java/support/generated-annotation-transform.mts#L42

.replace(/\n([a-w ]*(class|@?interface|enum) )/g, '\n@GeneratedByJHipster\n$1'); instead of .replace(/\n([a-w ]*(class|interface|enum) )/g, '\n@GeneratedByJHipster\n$1'); will do so. (The optional @? before interface).

**Comment by DanielFran** [comment]
@sebastienlabrune Can you contribute with a PR?
