### ISSUE TITLE
Custom blueprint: unknown option

### ISSUE THREAD

**Issue by fabianorodrigo** [jhipster/generator-jhipster#20444]
##### **Overview of the issue**

I'm creating a custom blueprint for my organization. I need to ask for a specific information to the blueprint user. So I've done in the PROMPTING priority, it works. 
However, I want the user to be able to pass this info via command line parameter. So I've created a custom parameter (option) in my constructor in the same way I've seem others generators:

```javascript
export default class extends GeneratorBaseEntities {
    constructor(args, opts, features) {
        super(args, opts, { taskPrefix: PRIORITY_PREFIX, ...features });

        this.option('parentProject', {
            desc: 'Inform the parent project',
            type: String,
        });
        ...
```

Then I've executed the command line:

```bash
jhipster jdl --blueprints my-java-blueprint --parentProject MyParentProject --skip-install ~/myjdl.jdl
```

And I've got the following error telling me that my parameter is unknown:

```
INFO! No custom sharedOptions found within blueprint: generator-jhipster-my-java-blueprint at /home/.nvm/versions/node/v16.18.0/lib/node_modules/generator-jhipster-my-java-blueprint
(node:23361) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./lib/util/" in the "exports" field module resolution of the package at /home/.nvm/versions/node/v16.18.0/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json.
Update this package.json to use a subpath pattern like "./lib/util/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
error: unknown option '--parentProject'
```

I've also tried in a differente way but the result is the same:

```javascript
this.jhipsterOptions({
            parentProject: {
                desc: 'Inform the parent project',
                type: String,
                scope: 'generator',
            },
           ...
```

##### **Motivation for or Use Case**

I need my user can pass a necessary info to my blueprint/generator without being prompted

##### **Reproduce the error**

Execute `jhipster generate-blueprint` and select sub-generator: `server`
Change the parent class of generator to `GeneratorBaseEntities` (I had to do this in order to modify the Entity Beans in the POST_WRITING_ENTITIES_PRIORITY)
Include the option in the constructor with "this.option(..."
Execute the "jhipster --blueprints theblueprint --the-parameter ... " command line

##### **JHipster Version(s)**

7.9.3

##### **JHipster Version(s)**

```
/home/fabianorodrigo/Downloads/teste3
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)

git version 2.34.1

node: v16.18.0

npm: 8.19.2

Docker version 20.10.12, build 20.10.12-0ubuntu4

Docker Compose version v2.11.2

##### **Browsers and Operating System**

Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
There are a few issues here:
- you need to generate the `app` generator and put the options there.
- `this.options` is kebabCase: https://github.com/jhipster/generator-jhipster/blob/f12930941afc61f00d3474d9e8bb984fc5d35d5f/generators/app/generator.mjs#L57-L60
- commander node module only supports kebabCase so `--parentProject MyParentProject` needs to be `--parent-project MyParentProject`
- `this.jhipsterOptions` approach may be correct (still needs to be at app generator), but it wasn't widely used at v7, v8 probably will be the default.

**Comment by fabianorodrigo** [comment]
Thank you very much, @mshima . I've generated a `app` generator and now it works
