### ISSUE TITLE
[Question] scss not in main webapp folder

### ISSUE THREAD

**Issue by jd-carroll** [jhipster/generator-jhipster#2044]
Why are the scss files not included in the webapp folder?  It would make more sense to me if they were under `main/webapp/assets/scss` and this is where I have moved them in my project (and not `main/scss`).  Just wondering if I'm going to run into un-foreseen issues.

**Comment by jdubois** [comment]
Those are source files, why do you want to serve them to the end-users?
OK it's just for CSS so there's probably no security risk, but this doesn't make sense.
