### ISSUE TITLE
tests fails for mysql and h2

### ISSUE THREAD

**Issue by crash007** [jhipster/generator-jhipster#20465]
##### **Overview of the issue**
When selecting mysql and h2 persistance database there is failed test.

2022-11-28 18:24:12.900 DEBUG 113921 --- [           main] reactor.core.publisher.Hooks             : Hooking onLastOperator: org.springframework.security.core.context.SecurityContext
2022-11-28 18:24:12.904  WARN 113921 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 23505, SQLState: 23505
2022-11-28 18:24:12.904 ERROR 113921 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:2 */ CAST(2 AS BIGINT), 'user', '$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K', 'User', 'User', 'user@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]
2022-11-28 18:24:12.907 DEBUG 113921 --- [           main] reactor.core.publisher.Hooks             : Reset onLastOperator: org.springframework.security.core.context.SecurityContext

[ERROR] Errors: 
[ERROR]   DomainUserDetailsServiceIT.init:50 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:1 */ CAST(1 AS BIGINT), 'admin', '$2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC', 'Administrator', 'Administrator', 'admin@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   DomainUserDetailsServiceIT.init:50 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:2 */ CAST(2 AS BIGINT), 'user', '$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K', 'User', 'User', 'user@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   UserServiceIT.assertThatOnlyActivatedUserCanRequestPasswordReset:95 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:1 */ CAST(1 AS BIGINT), 'admin', '$2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC', 'Administrator', 'Administrator', 'admin@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   UserServiceIT.assertThatUserMustExistToResetPassword:80 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:2 */ CAST(2 AS BIGINT), 'user', '$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K', 'User', 'User', 'user@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   AccountResourceIT.testRequestPasswordReset:663 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:2 */ CAST(2 AS BIGINT), 'user', '$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K', 'User', 'User', 'user@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   AccountResourceIT.testSaveInvalidEmail:449 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:1 */ CAST(1 AS BIGINT), 'admin', '$2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC', 'Administrator', 'Administrator', 'admin@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   PublicUserResourceIT.getAllPublicUsers:62 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:1 */ CAST(1 AS BIGINT), 'admin', '$2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC', 'Administrator', 'Administrator', 'admin@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   PublicUserResourceIT.getAllUsersSortedByParameters:90 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:2 */ CAST(2 AS BIGINT), 'user', '$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K', 'User', 'User', 'user@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   UserJWTControllerIT.testAuthorize:49 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:2 */ CAST(2 AS BIGINT), 'user', '$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K', 'User', 'User', 'user@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   UserJWTControllerIT.testAuthorizeWithRememberMe:72 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:1 */ CAST(1 AS BIGINT), 'admin', '$2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC', 'Administrator', 'Administrator', 'admin@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   UserResourceIT.createUserWithExistingEmail:217 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:1 */ CAST(1 AS BIGINT), 'admin', '$2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC', 'Administrator', 'Administrator', 'admin@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[ERROR]   UserResourceIT.createUserWithExistingLogin:188 » DataIntegrityViolation could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.JHI_USER(ID) ( /* key:2 */ CAST(2 AS BIGINT), 'user', '$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K', 'User', 'User', 'user@localhost', '', TRUE, 'en', NULL, NULL, 'system', NULL, NULL, 'system', NULL)"; SQL statement:
insert into jhi_user (id, created_by, created_date, last_modified_by, last_modified_date, activated, activation_key, email, first_name, image_url, lang_key, last_name, login, password_hash, reset_date, reset_key) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
[INFO] 
[ERROR] Tests run: 90, Failures: 0, Errors: 12, Skipped: 0

##### **Reproduce the error**
Run jhipster generator, select mysql and h2 perstistance database.

##### **JHipster Version(s)**
7.9.3

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "jh2",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1669656401525,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.3",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "microfrontend": false,
    "microfrontends": [],
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "mysql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

git version 2.34.1

node: v16.17.1

npm: 8.15.0

Docker version 20.10.12, build 20.10.12-0ubuntu4

##### **Browsers and Operating System**
ubuntu 

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kevinbwusa** [comment]
I have this same issue... Any progress on a solution?  It appears that during the DomainUserDetailsServiceIT.java test execution, in the init() method, during the userRepository.save(userOne) is when the exception occurs.  The userOne object looks nothing like what is trying to be saved to the database.  It looks like the data in the user.csv is being saved for user and admin when this call is make to save the userOne object.

**Comment by mshima** [comment]
Fixed in main https://github.com/jhipster/generator-jhipster/issues/19687
