### ISSUE TITLE
ImageBlob upload is broken

### ISSUE THREAD

**Issue by artjomg** [jhipster/generator-jhipster#2048]
Hi,
I have a fresh project generated by jhipster-uml and an Entity sub type ImageBlob.
However the upload fails: with the following error

TypeError: Cannot assign to read only property 'image' of data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA5EAAAJwCAYAAAAQveUsAAAEJGlDQ…ACCiiggAIKKKCAAgoooIACCiiggAIKKKCAAgoooIACCjT/DxiLM5BNR/TVAAAAAElFTkSuQmCC
    at data-dialog.controller.js:79
    at Scope.$eval (angular.js:15878)
    at Scope.$apply (angular.js:15978)
    at FileReader.fileReader.onload (data-dialog.controller.js:78)(anonymous function) @ angular.js:12416

The entity data has a field image:
```
        $scope.setImage = function ($file, data) {
            if ($file && $file.$error == 'pattern') {
                return;
            }
            if ($file) {
                var fileReader = new FileReader();
                fileReader.readAsDataURL($file);
                fileReader.onload = function (e) {
                    var data = e.target.result;
                    var base64Data = data.substr(data.indexOf('base64,') + 'base64,'.length);
                    $scope.$apply(function() {
                        data.image = base64Data;
                    });
                };
            }
        };
```

changing data.image to entity.image works as workaround, but I think this is still an issue.

ArtjomG

**Comment by artjomg** [comment]
Ohh....

looking at the code closer I realized that this is just a name clash.
Since my property is named data and the internal var is also called "var data" I accidentally created a name clash.

ArtjomG

**Comment by andidev** [comment]
Yes it is but it's still a bug I think so I'm reopening it

**Comment by andidev** [comment]
While changing `data.image` to `entity.image` works but is not the correct way to do it.
Could you try setting `data.image` to `$scope.data.image`. Does that solve the problem?

**Comment by andidev** [comment]
Reference to the line of code where we should fix this issue
https://github.com/jhipster/generator-jhipster/blob/master/entity/templates/src/main/webapp/app/_entity-dialog-controller.js#L101

**Comment by andidev** [comment]
Okey after a second look my suggested solution is not that good looking either. We should rather maybe not create the local data variable.

**Comment by artjomg** [comment]
A simple fix would be to pass the entity to the unload function like this.
It is js variable scope issue.

fileReader.onload = function (e,data) {
                    var data = e.target.result;
                    var base64Data = data.substr(data.indexOf('base64,') + 'base64,'.length);
                    $scope.$apply(function() {
                        data.image = base64Data;
                    });
                };

Than even in a clash case the reference works, at least in Chrome

**Comment by artjomg** [comment]
just use e.target.result?

**Comment by andidev** [comment]
yes thats exactly what we should do.

**Comment by artjomg** [comment]
I can, but I haven't done any PR's before. Is this Push request from local IDE? Any permissions required? Or can I do it online? Thanks Another related issue I found is that the preview Image is not rendered in IE on windows 8

**Comment by gmarziou** [comment]
You may get some hints from our [contributing guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-a-pull-request)

**Comment by andidev** [comment]
@artjomg I can fix this if you can't. I have to look into the image not displayed in Internet Explorer bug anyway. I'll  create a separate issue for that right away.

**Comment by artjomg** [comment]
@andidev thanks for merging. 
@gmarziou thanks for the PR guidelines, I will have to do a test run to get your process right. 
However one question I have is how to configure eclipse or Spring Tool Suite to match Intellij IDEA's code style.
