### ISSUE TITLE
Error configuring Jhipster in "production" profile with maven. 

### ISSUE THREAD

**Issue by gaiagilder** [jhipster/generator-jhipster#2052]
I'm experiencing this issue but i can't understand if this is related to Leaflet/angular-leaflet-directive,
i tried to rewire manually dependencies but with no luck,

mainMapScript.js is the file where i inject angular-leaflet-directive module,

    mvn -Pprod package
    ...
    PhantomJS 1.9.8 (Linux 0.0.0) ERROR
    ReferenceError: Can't find variable: L
    at /home/gaia/IdeaProjects/lande/src/main/webapp/scripts/components/map/mainMapScript.js:9
    PhantomJS 1.9.8 (Linux 0.0.0) ERROR
    ReferenceError: Can't find variable: L
    at /home/gaia/IdeaProjects/lande/src/main/webapp/scripts/components/map/mainMapScript.js:9

    PhantomJS 1.9.8 (Linux 0.0.0): Executed 0 of 0 ERROR (0.829 secs / 0 secs)

    Warning: Task "karma:unit" failed. Use --force to continue.

    Aborted due to warnings.

    Execution Time (2015-09-28 20:37:50 UTC)
    loading tasks  120ms  ▇ 2%
    wiredep:test   385ms  ▇▇▇▇ 7%
    karma:unit      5.3s      ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 91%
    Total 5.8s

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 24.782 s
    [INFO] Finished at: 2015-09-28T22:37:56+01:00
    [INFO] Final Memory: 32M/283M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build (run-frontend-    build) on project lande: Error during : grunt test --no-color: Process exited with an error: 3 (Exit value:    3) -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following     articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

***EDITED***

Please does not consider this post

**Comment by atomfrede** [comment]
Have you solved your issue?

**Comment by jdubois** [comment]
This is not a JHipster issue:

- I have no idea what those mainMapScript.js and angular-leaflet-directive but it doesn't come from us
- You have a karma unit error: please run "grunt test" and you will see why your unit fail

**Comment by gaiagilder** [comment]
yep Sir, I'm doing grunt test and the result is always related to angular-leaflet lib:

    Error: [$injector:modulerr] Failed to instantiate module landeApp due to:
    Error: [$injector:modulerr] Failed to instantiate module leaflet-directive due to:
    Error: [$injector:nomod] Module &apos;leaflet-directive&apos; is not available! You either misspelled     the module name or forgot to load it. If registering a module ensure that you specify the dependencies     as the second argument.
    http://errors.angularjs.org/1.4.6/$injector/nomod?p0=leaflet-directive

but I think I did all right because the application is perfectly working, I double-checked many times..

**Comment by jdubois** [comment]
But I have no idea what angular-leaflet is, this doesn't come from us -> why do you think this is a JHipster bug?

**Comment by gaiagilder** [comment]
because Karma don't import libraries installed with bower,

**Comment by jdubois** [comment]
Oh yes, this isn't very logical, as we import them automatically in the index.html... I did it on purpose as I wanted to control manually what I included (you don't always want all the libs when you're doing tests), but I agree this isn't logical -> for me this is a feature request, let me create it and link it here

**Comment by andidev** [comment]
Are you sure about karma not loading Bower dependencies? We have a Bower needle there,  see https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/test/javascript/_karma.conf.js#L14  Am I missing something?

**Comment by jdubois** [comment]
Oh thanks @andidev , I just believed the bug report to be correct... Then I'm closing my issue -> @gaiagilder can you check this is really your issue?

**Comment by gaiagilder** [comment]
curiously after injecting manually libs in Karma.config the list is reupdated and my custom import deleted, always the same error,

**Comment by gmarziou** [comment]
This can happen if the bower.json file from a dependency like angular-leaflet-directive does not define correctly its "main" property.

In such case the solution consists in overriding it in your app's bower.json and of course notify the package author.
