### ISSUE TITLE
🙏 Add jhipster logo to Simple Icons 🎨 

### ISSUE THREAD

**Issue by adriens** [jhipster/generator-jhipster#20533]
Hi, could you please add `Jhipster` logo to [Simple Icons](https://simpleicons.org/?q=jhipster) ❔ 

Thanks you in advance for your help.

**Comment by adriens** [comment]
Hi guys, here is a :gift: tu put under your :christmas_tree: : 

![image](https://user-images.githubusercontent.com/5235127/206796253-3ad314d4-19b4-45b8-a8b6-bdc98754944c.png)


```
http https://endoflife.date/api/jhipster.json
```

![image](https://user-images.githubusercontent.com/5235127/206796528-419edf9d-b5be-4318-ae73-8ca59c127388.png)

**Comment by atomfrede** [comment]
Nice thing with the eol api. Will it be automatically updated when we release jhipster 8? But how is this related to the original request?

**Comment by adriens** [comment]
> Nice thing with the eol api.

:pray: 

>  Will it be automatically updated when we release jhipster 8?

Yes, it should :+1: 

> But how is this related to the original request?

As soos as we get the icon, I'll add it to the jhpster page so it's page will be cleaner :sparkles:
