### ISSUE TITLE
Developing (on Windows?) broken

### ISSUE THREAD

**Issue by OmarHawk** [jhipster/generator-jhipster#20531]
Hi,

I just wanted to figure out something in regard to #20148 with the generator-jhipster project, but already stumbled upon a general problem with current main branch...

When I run the jhipster command against the current main branch (npm link & npm ci commands all done), I do get the following error:

```
PS C:\Users\xxx\git\mt\dvdemo> jhipster
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at new NodeError (node:internal/errors:393:5)
    at fileURLToPath (node:internal/url:1487:11)
    at file:///C:/Users/xxx/git/mt/generator-jhipster/dist/lib/index.mjs:13:52
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_INVALID_URL_SCHEME'
}

Node.js v18.12.1
```

So I put some debug output and found that the URL produced in this file:
https://github.com/jhipster/generator-jhipster/blob/7f1ba62077be5d2789856db7908bdf592ee39344/lib/index.mjs#L10-17

lacks the `"file:///"` prefix, which then produces the given error in Windows (10). Unfortunately, I don't really know the requirements behind the code, i.e. if this is suppsed to always load a local package.json, or if there could be cases where there is a remote package.json supposed to be supported. 

If this is just always local json, I think, placing a file:/// may be sufficient.

@mshima, there were some changes recently by you, maybe you can give some hints about that?

##### **Overview of the issue**

See above.

##### **Motivation for or Use Case**

I would like to help contributing again...

##### **Reproduce the error**
See above

##### **Related issues**
Haven't found that.

##### **JHipster Version(s)**
7.9.3 main branch

##### **Browsers and Operating System**
Windows 10, NODE.js 18.12.1

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by OmarHawk** [comment]
Same on Node 16 by the way.

**Comment by mshima** [comment]
I will take a look.

**Comment by mshima** [comment]
Can be closed?
Snapshots works?

**Comment by OmarHawk** [comment]
> Still not working for me on node 16

For me, main branch **does** work now without any manual adjustments... also using node 16

**Comment by DanielFran** [comment]
> Still not working for me on node 16

I mean, "update snapshots" still did not work... But I believe it is not the good issue

**Comment by OmarHawk** [comment]
Works for me meanwhile. :-)
