### ISSUE TITLE
Improve Heroku sub-generator

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#20541]
##### **Overview of the issue**

The PostgreSQL database for www.jhipster-book.com was dropped on November 30 because I failed to upgrade it from a free plan to a [eco or mini plan](https://blog.heroku.com/eco-and-mini-plans-ga). Luckily, it was easy to recover everything in minutes after I contacted Heroku support. 

To make sure `jhipster heroku` still works, I created a new app with 7.9.3 and deployed it. The good news is **it does still work**. There is a line when deploying that indicates you might be charged, but it doesn't specify for what.

```
remote:  !     The following add-ons were automatically provisioned: . These add-ons may incur additional cost, 
which is prorated to the second. Run `heroku addons` for more info.
```

If I run `heroku addons`, it shows the following:

```
Add-on                                             Plan  Price     State
─────────────────────────────────────────────────  ────  ────────  ───────
heroku-postgresql (postgresql-asymmetrical-03979)  mini  $5/month  created
 └─ as DATABASE

The table above shows add-ons and the attachments to the current app (jhipster-postgresql-test) or other apps.
```

What it doesn't tell you is the dyno itself will cost $7/month.

<img width="622" alt="Screen Shot 2022-12-07 at 19 55 53" src="https://user-images.githubusercontent.com/17892/206345959-87e552e1-5e81-4a94-ac8a-4cee84f105bf.png">

It would be nice if we could capture the output after `The following add-ons were automatically provisioned` if possible. 

Other than that, I found a few other issues I think we should fix:

1. If you're not authenticated with `heroku login`, the `.yo-rc.json` is still modified. IMO, this should happen after authentication succeeds.

```
Creating Heroku application and setting up node environment
✖ Error: Not authenticated. Run 'heroku login' to login to your heroku account and try again.
    force .yo-rc.json
```

2. If I try to deploy again using `jhipster heroku`, it doesn't recognize that the app already exists, and nullifies the `herokuAppName` value in `.yo-rc.json`.

```
Heroku configuration is starting
✖ Could not find application: jhipster-postgresql-test
✖ Run the generator again to create a new application.
    force .yo-rc.json
```

3. If I use my same app name and run the command again, it fails when it tries to add the buildpack.

```
Configuring Heroku
✖ Error: Command failed: heroku buildpacks:add heroku/java --app jhipster-postgresql-test
 ›   Error: The buildpack heroku/java is already set on your app.

    at ChildProcess.exithandler (node:child_process:400:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'heroku buildpacks:add heroku/java --app jhipster-postgresql-test',
  stdout: '',
  stderr: ' ›   Error: The buildpack heroku/java is already set on your app.\n'
}
```

##### **Motivation for or Use Case**

It should be possible to run the `jhipster heroku` command to redeploy the app. It should not modify any files when doing so. 

##### **Reproduce the error**

Create an app with `jhipster jdl default` and run `jhipster heroku` after creating it. Then, try to run the command again. 

##### **JHipster Version(s)**

7.9.3

**Comment by atomfrede** [comment]
I will try to update at least the documentation today as it still states jhipster will not Provision anything that costs money

**Comment by dagboujhatem** [comment]
Hello,  i can try to fix this issue.
