### ISSUE TITLE
problem with  bi-directionnal one-to-many relationship entities

### ISSUE THREAD

**Issue by smart987** [jhipster/generator-jhipster#2056]
I have created 'A bi-directionnal one-to-many relationship', Owner to Car. That is working fine but as stated in the documentation, from the generated Owner entity screen I don't find any link to add and view the cars of the owner.  From Cars screen if I select 'Owner', relevant owner is getting displayed. Similarly from Owner screen I expected a link to display all the cars of the Owner.  But from my generated owner entity screens I did not find any such link in Owners screen ( i.e., from http://localhost:8080/#/owners). However the jhipster document says " we had a bi-directionnal relationship: from a Car instance you could find its owner, and from a Owner instance you could get all of its cars" . In car screen I have a field for owner but in owner screen I don't have any link to display all the cars of a particular owner as stated above "from a Owner instance you could get all of its cars".  From the documentation I feel this feature is in built from jhipster generated entities however I am not finding that in the generated owner entity. Is it a bug in generating the entities or am I missing something?

**Comment by jdubois** [comment]
You have the dependency at the Hibernate level: the documentation talks about how those relationships work with Hibernate, it does not cover the UI layer.

**Comment by smart987** [comment]
First of all thanks Jdubois for the super excellent jhipster. It would be nice if that ui part also could have been included in the generated entities. For now I check for that part in SO. Meanwhile, if you can direct me for sample code for that part from ui, that would be great. Thanks.

**Comment by jdubois** [comment]
Have a look at the [sample app](https://github.com/jhipster/jhipster-sample-app) there is a one-to-many relationship inside (a BankAccount has many Operations)
