### ISSUE TITLE
Thymeleaf Error page doesn't work in prod profile when served as war

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2057]
The `error.html` present in `\src\main\resources\templates\` doesnt seem to work when the application is running in prod profile deployed as war. Im running it is Jboss, will check if behavior is same in tomcat when i find some time

@jdubois any idea where it is configured, i couldnt find it anywhere

**Comment by gmarziou** [comment]
I think ti is auto configred by spring-boot actuator.

**Comment by jdubois** [comment]
Yes, we used to configure it ourselves, but now that's done by actuator

-> this might depend on your version of JBoss, they've had a broken classloader for more than 10 years now (see my comments [here](https://developer.jboss.org/thread/105381?_sscc=t) in 2005!!)

**Comment by deepu105** [comment]
Did some digging and seems its not a jboss issue, i had apache ws in front
of jboss and the page doesnt come up when i go via apache if i hit app
server the page works. Doesnt seem like JH issue, will confirm and close.
We are not doing anything for this in .htaccess ??

**Comment by jdubois** [comment]
@deepu105 the .htaccess comes from HTML5Boilerplate, and I'm not using it myself -> if you use it and see some issue, it can definitely be modified, according to our specific needs

**Comment by deepu105** [comment]
@jdubois i didnt see anything on this in .htaccess, doesnt seem like JH issue anyway ill check with my web server admin

**Comment by deepu105** [comment]
I found the issue, this happens only in IE browsers due to some weird IE implementation related to http://blogs.msdn.com/b/ieinternals/archive/2010/08/19/http-error-pages-in-internet-explorer.aspx
since the error pages are redirects IE stops going to the actual page :(
