### ISSUE TITLE
Errors in swagger-ui, index.html 

### ISSUE THREAD

**Issue by vsarabu** [jhipster/generator-jhipster#2058]
<link rel="icon" type="image/png" href="images/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="images/favicon-16x16.png" sizes="16x16" />
    <link href='../bower_components/swagger-ui/dist/css/typography.css' media='screen' rel='stylesheet' type='text/css'/>
    <link href='../bower_components/swagger-ui/dist/css/reset.css' media='screen' rel='stylesheet' type='text/css'/>
    <link href='../bower_components/swagger-ui/dist/css/screen.css' media='screen' rel='stylesheet' type='text/css'/>
    <link href='../bower_components/swagger-ui/dist/css/reset.css' media='print' rel='stylesheet' type='text/css'/>
    <link href='../bower_components/swagger-ui/dist/css/print.css' media='print' rel='stylesheet' type='text/css'/>
    <script src='../bower_components/swagger-ui/dist/lib/jquery-1.8.0.min.js' type='text/javascript'></script>
    <script src='../bower_components/swagger-ui/dist/lib/jquery.slideto.min.js' type='text/javascript'></script>
    <script src='../bower_components/swagger-ui/dist/lib/jquery.wiggle.min.js' type='text/javascript'></script>
    <script src='../bower_components/swagger-ui/dist/lib/jquery.ba-bbq.min.js' type='text/javascript'></script>
    <script src='../bower_components/swagger-ui/dist/lib/handlebars-2.0.0.js' type='text/javascript'></script>
    <script src='../bower_components/swagger-ui/dist/lib/underscore-min.js' type='text/javascript'></script>
    <script src='../bower_components/swagger-ui/dist/lib/backbone-min.js' type='text/javascript'></script>
    <script src='../bower_components/swagger-ui/dist/swagger-ui.js' type='text/javascript'></script>
    <script src='../bower_components/swagger-ui/dist/lib/highlight.7.3.pack.js' type='text/javascript'></script>
    <script src='../bower_components/swagger-ui/dist/lib/marked.js' type='text/javascript'></script>
    <script src='../bower_components/swagger-ui/dist/lib/swagger-oauth.js' type='text/javascript'></script>

getting error as:

Undefined CSS file ("images/favicon-32x32.png").
Undefined CSS file ("images/favicon-16x16.png").......so on

I am new to jhipster and swagger, can any one please help me to fix this errors in eclipse.
I am able to run the application using command prompt. But getting errors in this folder.

thanks in advance

**Comment by jdubois** [comment]
From my understanding you only have an issue setting up Eclipse -> this depends on your Eclipse setup, which we don't provide. Did you follow our IDE set up?
I'm closing this as this is not a JHipster bug.
