### ISSUE TITLE
Start using "Sign in" instead of "Authenticate" + more

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2059]
I'm not sure the choice of words is the best when looking at the login page and other login related pages. We use "Authenticate" when in fact the de facto standard seems to be "Sign in" (Google, Twitter, Dropbox, etc). Also maybe we should call "Remember me" for what it is which is of course "Rememeber me". The choice of the username as login seems also a bit unusual for me, isn't it better to call it username? 

**All in all I suggest the that we change**
![screen shot 2015-09-29 at 21 21 55](https://cloud.githubusercontent.com/assets/571389/10175641/70d1fca0-66f0-11e5-970a-91e9ed9967b2.png)

**to**
![screen shot 2015-09-29 at 21 20 12](https://cloud.githubusercontent.com/assets/571389/10175633/682dd8e4-66f0-11e5-9006-141d4e7caa34.png)

and of course other related pages.

I'm going to do this for my personal project and instead of doing it there I could to it in the generator if you all agree with me. Maybe there is a reason for the choice of words that I have missed.

@jdubois @atomfrede @deepu105 @gzsombor @moifort @gmarziou @mraible @mraible
What do you say dev team?

**Comment by lluiscanals** [comment]
+1

**Comment by jdubois** [comment]
Yes I didn't do much thinking when I wrote those names -> if this what Google & al do, let's do the same

**Comment by atomfrede** [comment]
Yes let's stick with standard wording. Authenticate sounds really strange for sign in or login

**Comment by deepu105** [comment]
+1
