### ISSUE TITLE
Navbar text isn't collapsing because of obsolete Bootstrap classes

### ISSUE THREAD

**Issue by geraldhumphries** [jhipster/generator-jhipster#2060]
### Overview
The navbar is using `.hidden-tablet` to hide the text for the main nav links, which was changed to `.hidden-sm` in Bootstrap 3. This currently isn't working.
### Use Case
Right now, if the user is logged in as admin on a small screen the navbar buttons will be moved below the app brand. With the text hidden they will stay on the same line.
### JHipster Version
2.21.0
### Reproduce the error
Log in as admin and resize the screen to be between 769 and 992 pixels wide.
### Fix
`.hidden-tablet` references in `navbar.html` should be changed to `.hidden-sm`. I will open a pull request.

**Comment by geraldhumphries** [comment]
Before:
![before](https://cloud.githubusercontent.com/assets/5278953/10176233/884de7ba-66c1-11e5-84e2-8d01d95f3cbc.png)
After:
![after](https://cloud.githubusercontent.com/assets/5278953/10176234/88515a8a-66c1-11e5-90fc-71e0514dffec.png)

**Comment by andidev** [comment]
Not sure if this is by design but the home text does not have the hidden table class. And it is not changed in PR either so the result screenshot is not entirely right. 
Though I think we should hide the home text as well on small screens.

**Comment by geraldhumphries** [comment]
Oh, you're right. I took the screenshot after adding the class to the home button but forgot to commit it. Should I?

**Comment by geraldhumphries** [comment]
I've moved the comment with the images to the pull request.
