### ISSUE TITLE
JHipster Online creating application : summarizing choices made

### ISSUE THREAD

**Issue by skeres** [jhipster/generator-jhipster#20618]
##### **Overview of the feature request**

Using [web site ](https://start.jhipster.tech/) to create a custom application, generate a file ( json, yaml, other ) in the final .zip summarizing choices made by the user on the website. Other solution : add choices in readme.md.

##### **Motivation for or Use Case**

I would have appreciate to find in the generated zip a file resuming my choices made on [web site ](https://start.jhipster.tech/). Coming back on my project after few weeks, it could be good to know at a glance what is embbeded in.

##### **Related issues or PR**

not found

- [ X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by fleboulch** [comment]
Hi @skeres  
You have all the info in the `.yo-rc.json` file ([example](https://github.com/jhipster/jhipster-sample-app/blob/main/.yo-rc.json))
