### ISSUE TITLE
infinite-scroll: should the main application Angular module depend on it by default?

### ISSUE THREAD

**Issue by jokogr** [jhipster/generator-jhipster#2063]
Hello,

I am using jHipster v2.21.1 and I would like to ask if there is any reason for ngInfiniteScroll to be injected by default. The dependency appears at app.js even before creating entities and it remains even if no entities use infinite scrolling. This causes issues when my project is pulled from the repository, e.g. I am building and deploying it to a remote server and I get the following error:

    Error: [$injector:modulerr] Failed to instantiate module jhipsterApp due to:
    [$injector:modulerr] Failed to instantiate module infinite-scroll due to:
    [$injector:nomod] Module 'infinite-scroll' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument

If I delete the dependency at app.js, the application runs as expected.

**Comment by deepu105** [comment]
No specific reason, its way easier this way and generally doesn't cause any harm. You can remove it if you are not using it . Remove from bower json and from app.js reference
