### ISSUE TITLE
ImageBlob image not shown in Internet Explorer 

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2065]
As @artjomg reported in #2048. The image is not displayed correctly in Internet Explorer browser. 
I think the reason could be that we do not specify the image type in the data-ng-src attribute  (we use an * instead, see https://github.com/jhipster/generator-jhipster/blob/master/entity/templates/src/main/webapp/app/_entities.html#L75 ). 

@artjomg could you try changing it to the corresponding file type e.g. jpg if you used JPEG? Does that render?

**Comment by artjomg** [comment]
Yes, I can test it with IE.

**Comment by andidev** [comment]
I'm gonna go ahead and add another field for Blobs that will hold the content type. Hopefully it will solve this issue.
