### ISSUE TITLE
Unauthenticated page request not remembered post authentication

### ISSUE THREAD

**Issue by sdoxsee** [jhipster/generator-jhipster#2066]
When trying to request a protected page (e.g. http://localhost:8080/#/user-management) while still unauthenticated, the user should be shown the login screen and then be automatically brought to the originally requested page. This isn't currently working. Instead, the user is directed to the home page post-login.

Pre
- unauthenticated

Steps
- request http://localhost:8080/#/user-management
- submit admin credentials

Expected
- continue to http://localhost:8080/#/user-management (authenticated)

Actual
- continue to home (i.e. http://localhost:8080/#/) (authenticated)

**Comment by gmarziou** [comment]
Please provide details about your app, what kind of authentication did you use?

**Comment by sdoxsee** [comment]
Sorry, here's my yo-rc.json

```
{
  "generator-jhipster": {
    "baseName": "oidc",
    "packageName": "org.doxsee.oidc",
    "packageFolder": "org/doxsee/oidc",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "51e3c5eaab308ee4c10d239cffea9cbb149e423f"
  }
}

**Comment by andidev** [comment]
This has been bugging me as well so I took a look into it.
We need to store the requested url in the root scope in the `authorize` method (auth.service.js).
And then use it to set the $location.path in the login.controller.

The problem and a solution seems to be described here http://www.jonahnisenson.com/angular-js-ui-router-redirect-after-login-to-requested-url/.

Do you feel like providing a PR?

**Comment by andidev** [comment]
Looks like we already save the previous state so maybe this is a bug after all. Think this needs further investigation.

**Comment by sdoxsee** [comment]
@andidev I've got a fix but I want to test it some more first when I get time. I'll provide a PR in the next couple of days to review.

**Comment by sdoxsee** [comment]
Please review to make sure this is what we want. Let me know if you have any questions. Thanks!
