### ISSUE TITLE
Git commit guidelines contradict themselves

### ISSUE THREAD

**Issue by geraldhumphries** [jhipster/generator-jhipster#2067]
The guidelines [here](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#commit) mention this for the commit body:

>Just as in the Header, use the imperative, present tense: "change" not "changed" nor "changes".

However, the example commit uses the past tense in the body:
```
upgrade to Spring Boot 1.1.7

upgraded the Maven and Gradle builds to use the new Spring Boot 1.1.7,
see http://spring.io/blog/2014/09/26/spring-boot-1-1-7-released

Fix #1234
```
I'm opening an issue because I'm not sure what would rather be used.

Also, Github supports lowercase keywords. Since the guidelines for the header mention "don't capitalize first letter" and the body seems to follow, maybe the footer should as well?

**Comment by jdubois** [comment]
The guidelines are correct, even if I never follow this myself.... I will pay more attention in the future.

**Comment by geraldhumphries** [comment]
What about the example commit?

**Comment by jdubois** [comment]
I'm fixing the example commit :-)
