### ISSUE TITLE
Date widget does not display correctly for Cassandra entities with date attribute

### ISSUE THREAD

**Issue by vbhatt** [jhipster/generator-jhipster#2068]
Date widget in angularjs does display correctly with cassandra generated application with dates in entity.

**Comment by jdubois** [comment]
This is an HTML5 calendar application, so it's only working with Chrome -> as you don't provide your browser information (please follow the guidelines), and as this is an already opened issue, I'm closing this as duplicate

**Comment by vbhatt** [comment]
I am running on Chrome and yet the html5 calendar widget does not show. Try a simple cassandra application with a "date" attribute and you will see the problem.
