### ISSUE TITLE
Update generator test suite to Jest

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#20687]
##### **Overview of the feature request**

Jest is a fast and state of the art javascript test suite

##### **Motivation for or Use Case**

Mocha is a pretty good framework, but the lack of tooling is a big issue for potential contributors:
 - Intellij doesn't support mocha with the --parallel flag, which makes it impossible to execute one single test using IDE features
 - There are many VScode macha plugins, but I didn't find what I wanted (something to execute a single test and that recognizes breakpoints).

I'm also too javascript noob to be able to debug unit test with breakpoint (far from being a javascript guy at heart) and I may not be alone: updating the contributor's guide on a proper generator's IDE coding setup looks to be the bare minimum.

What about adding a bounty on it? 

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
IMO jest is not a good candidate for us. It uses a bloated environment.
`jest-snapshot` have no good alternative.
So, switching from chai to expect, sinon to jest-mock is a something I am already doing for a while so we can use a single stack.

With https://github.com/jhipster/generator-jhipster/pull/20692 you can use mocha-explorer plugin and run a single test and debug works.

<img width="303" alt="Captura de Tela 2023-01-05 às 00 36 24" src="https://user-images.githubusercontent.com/1417183/210696254-bbbfa945-be50-4c2e-a826-909db0b44577.png">

**Comment by Tcharl** [comment]
Still, I'm a bit sad because of https://youtrack.jetbrains.com/issue/WEB-46034
