### ISSUE TITLE
Duplicate Oauth2 Tokens

### ISSUE THREAD

**Issue by svennela** [jhipster/generator-jhipster#2069]
Hi,

I got latest jhipster with mysql. When i logout and login i am running into below issue. Any pointers?

{"error":"server_error","error_description":"PreparedStatementCallback; SQL [insert into oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) values (?, ?, ?, ?, ?, ?, ?)]; Duplicate entry '00d6d414ad51e882b55919d45a26fa63' for key 'PRIMARY'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '00d6d414ad51e882b55919d45a26fa63' for key 'PRIMARY'"}

**Comment by jdubois** [comment]
I remember already seeing this, can you check in the older tickets?

**Comment by svennela** [comment]
Hi Julien,

After adding constraint, I am running into above error. Otherwise it is inserting duplicate rows.

**Comment by jdubois** [comment]
Yes I confirm the issue

**Comment by atomfrede** [comment]
I looked a little bit into this issue and it looks like a spring security issue (as far as I can tell). The ``ClientDetailsUserDetailsService`` tries to load the client details by client id (``clientDetailsService.loadClientByClientId``) and provide the ``username`` as parameter which is used as client id in the sql query. Looks to me that this can't work (or we must configure our client id differently). But maybe I don't get it right.

**Comment by cbornet** [comment]
Wouldn't that be because ClientDetailsServiceConfigurer is now configured with .jdbc() if the database is sql ? If that's the case, I'm very sorry since it comes from my commit for 3-legged oauth.
Can you try setting it back to .inMemory() ?

**Comment by atomfrede** [comment]
Yes, looks like this issue: https://github.com/spring-projects/spring-security-oauth/issues/420

Will try it later today, but it sounds like that is the problem

**Comment by cbornet** [comment]
And of course this doesn't happen with H2 in-memory DB... so I didn't get it during my tests...

**Comment by atomfrede** [comment]
:) Now we have H2 on disk by default everybody gets this error I guess.

**Comment by atomfrede** [comment]
So some new findings (I guess I don't understand spring security here). 

* Using ``inMemory`` instead of jdbc works fine (as expected), but the client is not persisted
* according to https://github.com/spring-projects/spring-security-oauth/issues/420 leaving out withClient during configuration should make it work, but it doesn't -> not login at all
* with the jdbc store the clientDetails are retrieved using the *login* which can't give the correct result -> not client details found -> trying to add new ones (instead of updating or reusing the existing one) -> duplicate key error

So in order to fix this we could switch to in mem store or du some further reserach

**Comment by cbornet** [comment]
I think we should switch back to inMemory and see about jdbc later. Jdbc is useful for multi-client apps config which is not the most common case anyway.

**Comment by cbornet** [comment]
and about https://github.com/spring-projects/spring-security-oauth/issues/420, if you keep jdbc but remove withClient, I think you need to populate the db another way (liquibase or other)

**Comment by atomfrede** [comment]
Yes, I didn't tried it, but I thought so too. So if everyone is okay lets switch back to inMemory, such that we have oAuth working again. CC @jdubois
