### ISSUE TITLE
generator-jhipster Unit Test failed

### ISSUE THREAD

**Issue by fdquinones** [jhipster/generator-jhipster#2071]
Steps to reproduce:
1) Generate a project with jhipster
2) Add an entity (example: Variable)
3) Add a field of type string (Code), with minimum and maximum length of 3.
4) mvn test

When making a "mvn test" produces error,  a not very descriptive error, which is the next "201 STATE EXPECTED BUT FOUND 400".

Modify the test drive to introduce more details of the error so we add "andDo(print())" in mockmvc method being as follows:

<code>
 @Test
    public void createVariable() throws Exception {
        int databaseSizeBeforeCreate = variableRepository.findAll().size();

        // Create the Variable

        restVariableMockMvc.perform(post("/api/variables")
                .contentType(TestUtil.APPLICATION_JSON_UTF8)
                .content(TestUtil.convertObjectToJsonBytes(variable)))
                .andDo(print())
                .andExpect(status().isCreated());

        // Validate the Variable in the database
        List<Variable> variables = variableRepository.findAll();
        assertThat(variables).hasSize(databaseSizeBeforeCreate + 1);
        Variable testVariable = variables.get(variables.size() - 1);
        assertThat(testVariable.getNombre()).isEqualTo(DEFAULT_NOMBRE);
        assertThat(testVariable.getCodigo()).isEqualTo(DEFAULT_CODIGO);
        assertThat(testVariable.getUnidad()).isEqualTo(DEFAULT_UNIDAD);
        assertThat(testVariable.getTipo()).isEqualTo(DEFAULT_TIPO);
        assertThat(testVariable.getDescripcion()).isEqualTo(DEFAULT_DESCRIPCION);
        assertThat(testVariable.getIcono()).isEqualTo(DEFAULT_ICONO);
    }

</code>
After checking found that the problem was not passed validations model as the default text for the CODE field is "SAMPLE_TEXT", which is longer than defined in the model.

**Comment by jdubois** [comment]
This is a duplicate from #1843

**Comment by fdquinones** [comment]
In fact this issue is duplicated, but suggest you add a<pre>HandlerExceptionResolvers</pre> test configuration as the <pre>ExceptionTranslator</pre> not triggered when a test is performed, and this prevents details about the problem.

http://stackoverflow.com/questions/16669356/testing-spring-mvc-exceptionhandler-method-with-spring-mvc-test
