### ISSUE TITLE
Feature: Liquibase support for cassandra

### ISSUE THREAD

**Issue by maklemenz** [jhipster/generator-jhipster#2074]
Liquibase does support cassandra using an official extension:
https://github.com/liquibase/liquibase-cassandra

It would be nice if jhipster would support liquibase for cassandra.

**Comment by jdubois** [comment]
Last time I checked this wasn't ready at all, and I don't think @nvoxland is working on this.

I clearly won't use it until it has reached some popularity and maturity. Besides, the current system works quite well -> it's much easier for Cassandra than for an SQL database, as there aren't any relationships
