### ISSUE TITLE
Add link to project helping to make existing sql DB to JDL

### ISSUE THREAD

**Issue by Blackdread** [jhipster/generator-jhipster#20759]
##### **Overview of the feature request**

Since it has been a few years that the project exist https://github.com/Blackdread/sql-to-jdl and a few stars on the project and contributions since then.
I think it can be beneficial for the community to have that project link in one of the pages of https://www.jhipster.tech/ , it could help teams to change an existing SQL database into JDL.

##### **Motivation for or Use Case**

Simplify translating SQL to JDL of existing databases

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Blackdread** [comment]
@jdubois @mraible Hi, sorry for the ping, I think this could be beneficial to the community.
Let me know what you think.
Thanks

**Comment by mraible** [comment]
@Blackdread It might be good to mention it on the JDL page at https://www.jhipster.tech/jdl/intro. You can create a PR against the website at https://github.com/jhipster/jhipster.github.io.

**Comment by Blackdread** [comment]
Thank you

PR created https://github.com/jhipster/jhipster.github.io/pull/1271
