### ISSUE TITLE
Adding Karakalpak language

### ISSUE THREAD

**Issue by saylaww** [jhipster/generator-jhipster#20758]
##### **Overview of the feature request**
Add the generator jhipster Karakalpak language. 

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Do you speak Karakalpak and would like to provide a PR?

**Comment by saylaww** [comment]
Yes, I wanted to add the Karakalpak language. How can we add?

**Comment by saylaww** [comment]
> https://www.jhipster.tech/installing-new-languages/#how-to-add-a-new-language-that-is-not-supported

I have translated all the files into Karakalpak language, now how can I add them to the generator?

**Comment by mraible** [comment]
If the following doesn't work, please let me know and I'll try to get it updated. 

https://www.jhipster.tech/installing-new-languages/#contributing-the-language-to-generator-jhipster

**Comment by saylaww** [comment]
> If the following doesn't work, please let me know and I'll try to get it updated.
> 
> https://www.jhipster.tech/installing-new-languages/#contributing-the-language-to-generator-jhipster

I cloned the project and translated it locally. Now how can I push to git?

**Comment by saylaww** [comment]
> If the following doesn't work, please let me know and I'll try to get it updated.
> 
> https://www.jhipster.tech/installing-new-languages/#contributing-the-language-to-generator-jhipster

I don't have permission to push or merge to git?

**Comment by mraible** [comment]
> I don't have permission to push or merge to git?

You have to fork it to your own repo, create a branch, then push that. Then, it should prompt you to create a pull request. 

See the following guide for more information:

https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md#setup

**Comment by saylaww** [comment]
> > I don't have permission to push or merge to git?
> 
> You have to fork it to your own repo, create a branch, then push that. Then, it should prompt you to create a pull request.
> 
> See the following guide for more information:
> 
> https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md#setup

I opened a new branch, translated all files into the Karakalpak language and committed to the new branch. What should I do now?

**Comment by saylaww** [comment]
should I press this button?
 
[https://camo.githubusercontent.com/ca3b1cefece5f3b9b3435020e6a357ca024cda5bd2b1e140a15170fcd1ec5381/68747470733a2f2f6669727374636f6e747269627574696f6e732e6769746875622e696f2f6173736574732f526561646d652f636f6d706172652d616e642d70756c6c2e706e67](url)

**Comment by saylaww** [comment]
> Push it to your fork and you should be prompted to create a pull request.On Jan 13, 2023, at 04:30, saylaww ***@***.***> wrote:﻿ I don't have permission to push or merge to git? You have to fork it to your own repo, create a branch, then push that. Then, it should prompt you to create a pull request. See the following guide for more information: https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md#setup I opened a new branch, translated all files into the Karakalpak language and committed to the new branch. What should I do now? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>


should I press this button?

https://camo.githubusercontent.com/ca3b1cefece5f3b9b3435020e6a357ca024cda5bd2b1e140a15170fcd1ec5381/68747470733a2f2f6669727374636f6e747269627574696f6e732e6769746875622e696f2f6173736574732f526561646d652f636f6d706172652d616e642d70756c6c2e706e67

**Comment by mraible** [comment]
Yes

**Comment by saylaww** [comment]
> Yes

I clicked, do I need to do something else?

**Comment by mraible** [comment]
You should add "Fixes #20578" to the description so when we merge the PR, it closes this issue. Other than that, you need to fix tests failures. 

https://github.com/jhipster/generator-jhipster/actions/runs/3910988851/jobs/6685638496#step:10:16039

If you need help, please let me know.

**Comment by mraible** [comment]
It looks like you need to rename the file "messages_kr_Latin_KR.properties. ejs" to not have a space in it.

**Comment by saylaww** [comment]
> 

I edited and pushed to git. Does it work now?

**Comment by saylaww** [comment]
> It looks like you need to rename the file "messages_kr_Latin_KR.properties .ejs" to not have a space in it.

there is another error, what could it be?

**Comment by DanielFran** [comment]
Closed in https://github.com/jhipster/generator-jhipster/pull/20946
