### ISSUE TITLE
Partial update with MapStruct removes child entities

### ISSUE THREAD

**Issue by Clemzd** [jhipster/generator-jhipster#20751]
_I am unsure whether the issue is a result of a technical flaw or if it is a result of my own error._

I have a RaceDTO which contains a list of pilots and a name. When I call the partialUpdate method to update the name of the race, the list of drivers is being removed. This is because the DTO is initialized with new HashSet<>, so the list is not null and MapStruct maps it, causing the service to clear my list of drivers. This should not be the case, as I only want to update the name of the race.

**RaceDTO.class**

`private Set<RelayDTO> relays = new HashSet<>();`

**RaceMapperImpl.class**
```
if ( entity.getPilots() != null ) { 
    Set<Pilot> set1 = pilotDTOSetToPilotSet( dto.getPilots() );
    if ( set1 != null ) { // set1 isn't null because it was initialized with new HashSet<>
        entity.getPilots().clear();
        entity.getPilots().addAll( set1 );
    }
}
```

**Steps to reproduce:**

Call the partialUpdate method on the RaceDTO, only updating the name field
Observe that the list of drivers has been cleared

**Expected behavior:**

The partialUpdate method should only update the name field, and leave the list of drivers unchanged.

**Actual behavior:**

The partialUpdate method clears the list of drivers in the RaceDTO.

**Solution:**

Removes the initialization on the DTO

**Comment by gmarziou** [comment]
@Clemzd So what is your proposal? Have you tried removing the `new HashSet<>()` in DTO?
