### ISSUE TITLE
Sonar no longer works with `main` branch

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#20773]
##### **Overview of the issue**

If I clone the `main` branch and create an app with `jhipster jdl 21-points.jh`, it doesn't work with Sonar out-of-the-box. First, I had to build an M1-compatible Docker image and start it. Then there's an error when I try to run the Gradle command against it:

```
> Task :sonarqube FAILED
Task 'sonarqube' is deprecated. Use 'sonar' instead.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> You're not authorized to run analysis. Please contact the project administrator.
```

I tried using `sonar` instead, but this fails too:

```
./gradlew -Pprod clean check jacocoTestReport sonar -Dsonar.host.url=http://localhost:9001

> Task :sonar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonar'.
> You're not authorized to run analysis. Please contact the project administrator.
```

##### **Motivation for or Use Case**

It'd be cool to see code coverage on a newly created app with v8.

##### **Suggest a Fix**

Maybe Sonar's Docker image needs to have authentication turned off by default? 

##### **JHipster Version(s)**

`main` as of Jan 10, 2023

**Comment by atomfrede** [comment]
Our generated docker compose configuration disables authentication. Did you start the sonar container directly?

**Comment by mraible** [comment]
No, I just used `jhsonarup`. Here's the `sonar.yml` that's generated:

```yaml
# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: healthpoints
services:
  sonar:
    image: sonarqube:9.8.0-community
    # Authentication is turned off for out of the box experience while trying out SonarQube
    # For real use cases delete sonar.forceAuthentication variable or set sonar.forceAuthentication=true
    environment:
      - sonar.forceAuthentication=false
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9001:9000
```

**Comment by atomfrede** [comment]
Ah okay so the env variable seem not to work anymore

**Comment by atomfrede** [comment]
Quick search at the sonar source, should the env variable be named `SONAR_FORCEAUTHENTICATION`?

**Comment by atomfrede** [comment]
Another thing we could do (which is what we have at jhipster lite) is to add default logins to `sonar-project.properties`.

```
sonar.login=admin
sonar.password=admin
```

See https://github.com/jhipster/jhipster-lite/blob/077caddd0575848473b9ff058c76baaf88732873/sonar-project.properties#L4

**Comment by mraible** [comment]
@atomfrede I tried using `SONAR_FORCEAUTHENTICATION=false` and it doesn't seem to work. I'm able to access `http://localhost:9001/` without authenticating, but the Gradle command fails. If I use the properties file approach, everything works, but there are errors in the terminal:

```
A connection to http://localhost:9001/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

> Task :sonar
Property 'sonar.password' is deprecated. It will not be supported in the future. Please instead use the 'sonar.login' parameter with a token.
```

The 2nd approach also requires I update the password when I log in to `http://localhost:9001/`.

**Comment by mraible** [comment]
Added a bug bounty to get this fixed.

**Comment by atomfrede** [comment]
The connection leak seems to be tracked at sonar scanner. Not sure the ticket is still valid https://community.sonarsource.com/t/okhttp3-connection-leak-warning-even-in-sonar-scanner-api-2-15-0-2182/24845

**Comment by mraible** [comment]
Maybe we should just revert to a previous version of Sonar where this issue doesn't happen?

**Comment by atomfrede** [comment]
The gradle plugin documentation states it should just work with a plain sonar installation and authentication can be added as needed, which is confusing. I will have deeper look. Eventually jhipster lite will also be affected
