### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS with Spring Session Data Redis

### ISSUE THREAD

**Issue by jaydeep-punjani** [jhipster/generator-jhipster#20772]
##### **Overview of the issue**

On JHipster v7.9.3 getting ERR_TOO_MANY_REDIRECTS after enabling spring-session-data-redis on gateway application

##### **Motivation for or Use Case**

Unable to scale gateway.

##### **Reproduce the error**

https://github.com/oktadev/okta-spring-session-redis-example

##### **JHipster Version(s)**
v7.9.3

##### **Browsers and Operating System**

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I apologize for missing this. Did you ever get it figured out, @jaydeep-punjani?

**Comment by jaydeep-punjani** [comment]
Sorry @mraible couldn't get it figured.
