### ISSUE TITLE
Major regression on ng-default sample generation.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#20782]
##### **Overview of the issue**

The sample is taking 25min, was 5min.

##### **Reproduce the error**

github ci.

##### **JHipster Version(s)**

main

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
If it can help: seems that it loops many times on the language loop to create entities i18n files here: `async writeClientFiles({ application, entities }) {`

Maybe just because the generator writes so many files on the fs there

**Comment by Tcharl** [comment]
From the diff I did there are only few possible explanation (could be wrong but still).
Can come from the cache disablement (@mshima tried, doesn't seems to be related, but may contribute to).
Can be related to upgrades of fast-xml-parser or commander (I doubt that the last one could impact the perf,may be a third party dep)

**Comment by Tcharl** [comment]
Dependency reorder seems to improve the perf: the 'project' step now takes the same time as previously (5 min instead of 23+).
generate base is still long: I'll try reactivating ejs cache

**Comment by mraible** [comment]
Added a bug bounty to get this fixed.

**Comment by mshima** [comment]
This bug is really trick. I failed to identify the cause.
The updated prettier is triggering a misbehavior at the unrelated `multimatch` (probably `minimatch` dependency).
In any case I think I can implement some optimizations.

**Comment by mshima** [comment]
@DanielFran bug bounty claimed https://opencollective.com/generator-jhipster/expenses/172337

**Comment by DanielFran** [comment]
@mshima approved
