### ISSUE TITLE
Clustered HTTP session with stateless session

### ISSUE THREAD

**Issue by ufoscout** [jhipster/generator-jhipster#2083]
Something strange happens at project generation if OAuth2 or Token-based stateless authentication are selected; in fact at step 10 it asks you if you want to use clustered HTTP sessions:
```
? (4/15) Which *type* of authentication would you like to use? OAuth2 Authentication (stateless, with an OAuth2 server implementation)
...
? (10/15) Do you want to use clustered HTTP sessions? (Use arrow keys)
❯ No 
  Yes, with HazelCast 
```
Shouldn't the application be completely stateless when using one of the two stateless authentication modes?

**Comment by jdubois** [comment]
- Indeed, those authentication mechanism are stateless
- But you still have a session if you want to: maybe some people want to use OAuth2 but store some state in the session, this is a perfectly valid use case

I agree it can look strange at first sight, but there's an explanation.

And anyway, it doesn't hurt to provide this option (it's not always the case in JHipster, but here both option are independant, so for us it's nearly free to provide)
