### ISSUE TITLE
8.0.0-alpha.1 release

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#20849]
##### **Overview of the feature request**

Hi experts,
The generator is missing the Spring 3.0 hype while (close to) be ready to handle it.

What about releasing an alpha release (subject to api change, but ready for end users) in order to get feedback and traction?

##### **Motivation for or Use Case**

Keep being hipsterish

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/20748
https://github.com/jhipster/generator-jhipster/issues/19782
...

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
> I support this notion. Does that mean we should also cut a release of `jhipster-bom` or can we just continue using the snapshot?

The bom project need also a release, we keep in sync the versions between bom and generator

**Comment by Tcharl** [comment]
Yeah, the JBoss way.

Side question can we state that the V8 releases won't support contributor API compatibility between releases?
We have a lot of work to achieve: moving business logic to dedicated `support` packages, switch to typescript (which will also impact API for sure, split lifecycle between generators, ... 

I doubt we'll succeed to fix all all this before reaching Alpha.100 or keep a sane, solid committer community if we wait V9 to fix this up.

**Comment by paris0120** [comment]
Are you posting the alpha releases on npm? Jhipster since 7.9 are not working for me. Looking forward to upgrading my apps.

**Comment by mraible** [comment]
@paris0120 If you're using Node 18, this is a known issue. If you're using Node 16, please provide steps to reproduce.

**Comment by Tcharl** [comment]
Can you raise a ticket for this issue please (and may be contribute a pr to fix)?

**Comment by paris0120** [comment]
> Can you raise a ticket for this issue please (and may be contribute a pr to fix)?

I will try to do that. It looks not very difficult. I'm just wondering which branch I should work on.

**Comment by anothergoodguy** [comment]
Dear Team,
Greetings!

I tried to experiment with the `main` branch of Jhipster Generator. We use Infinispan cache in our apps and here is some observation I'd like to share.
When we use infinispan, the generated `CacheConfiguration.java` needs below changes, due to the upgrades on infinispan's library changes:

Method: `private JChannel getTransportChannel()`

Old Snippet - 1:
		
```
		tcp.setThreadPoolMinThreads(2);
		tcp.setThreadPoolMaxThreads(30);
		tcp.setThreadPoolKeepAliveTime(60000);

```   
        
Old Snippet - 2:        
	
`		nakack.setUseMcastXmit(false);
`
		
New Snippet - 1:
		
```
		tcp.getThreadPool().setMinThreads(2);
		tcp.getThreadPool().setMaxThreads(30);
		tcp.getThreadPool().setKeepAliveTime(60000);

```
		
New Snippet - 2:        

`		nakack.useMcastXmit(false);	
`

I thought this ticket is the right place to share the feedback; however, if you feel there should be a new ticket. I can open one as well.

Also, Please be informed, I have just compiled and ran the test app with the changes and have not worked on any performance benchmarking...



Thank you for such a wonderful tool...

**Comment by atomfrede** [comment]
Thanks @anothergoodguy for the detailed report. I would say create a dedicated ticket so it doesn't get lost.

**Comment by Tcharl** [comment]
@DanielFran do you know who can release the platform?

**Comment by anothergoodguy** [comment]
Hi Team,

Please see one more observation added in relation to Infinispan: https://github.com/jhipster/generator-jhipster/issues/21230#issuecomment-1448861209

**Comment by vidhya03** [comment]
could you please point me how to test 8.0.0-alpha.1 ,  i have started upgrading to spring-boot 3 ,spring 6, java 17

**Comment by mraible** [comment]
@vidhya03 Here's a video that shows you how to use the `main` branch: https://www.youtube.com/watch?v=0UFWJ3JGZa0

Or you could just use these commands:

```
git clone https://github.com/jhipster/generator-jhipster.git --depth=1
cd generator-jhipster
npm i
npm link
```

**Comment by mshima** [comment]
@mraible I would recommend adding a alias to the `bin/jhipster.mjs`:
```
npm uninstall -g generator-jhipster
alias jhipster=".../generator-jhipster/bin/jhipster.mjs"
```

So you don't need to rebuild the typescript source on every change.
Update the contributing docs is pending.

**Comment by mraible** [comment]
@mshima For this to work, you still need to clone the repo, correct? 

Also, in this example, what does `...` mean? It seems like a relative path, whereas I believe aliases should be absolute so they can work anywhere.

**Comment by mshima** [comment]
> @mshima For this to work, you still need to clone the repo, correct?

Sure, I was supposing it was already linked.

> Also, in this example, what does `...` mean? It seems like a relative path, whereas I believe aliases should be absolute so they can work anywhere.

It’s the absolute path.
Updated the instructions to be a install from scratch.

**Comment by vidhya03** [comment]
> @vidhya03 Here's a video that shows you how to use the `main` branch: https://www.youtube.com/watch?v=0UFWJ3JGZa0
> 
> Or you could just use these commands:
> 
> ```
> git clone https://github.com/jhipster/generator-jhipster.git --depth=1
> cd generator-jhipster
> npm i
> npm link
> ```

I tried and executed still it was pointed to old springboot 2.7.3 version, then i have uninstalled jhipster via ```  yarn global remove generator-jhipster``` 

then again executed. 
```
cd generator-jhipster
npm i
npm link
```

I got this error in git bash

```
$ jhipster --version
bash: jhipster: command not found
```
and windows powdershell

```
PS C:\opensource\generator-jhipster> jhipster --version
jhipster : The term 'jhipster' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ jhipster --version
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (jhipster:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by vidhya03** [comment]
> > @vidhya03 Here's a video that shows you how to use the `main` branch: https://www.youtube.com/watch?v=0UFWJ3JGZa0
> > Or you could just use these commands:
> > ```
> > git clone https://github.com/jhipster/generator-jhipster.git --depth=1
> > cd generator-jhipster
> > npm i
> > npm link
> > ```
> 
> I tried and executed still it was pointed to old springboot 2.7.3 version, then i have uninstalled jhipster via ` yarn global remove generator-jhipster`
> 
> then again executed.
> 
> ```
> cd generator-jhipster
> npm i
> npm link
> ```
> 
> I got this error in git bash
> 
> ```
> $ jhipster --version
> bash: jhipster: command not found
> ```
> 
> and windows powdershell
> 
> ```
> PS C:\opensource\generator-jhipster> jhipster --version
> jhipster : The term 'jhipster' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + jhipster --version
> + ~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (jhipster:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> ```
> 
> ```
> PS C:\opensource\generator-jhipster> npm --version
> 8.19.1
> PS C:\opensource\generator-jhipster> node --version
> v18.9.1
> ```
> 
> I have tried with .devcontainer , it is working, however in windows not working.

working with this command
```npx jhipster```

**Comment by anothergoodguy** [comment]
I am using with docker  and it works fine. 

- `docker build -t jhipster:local .`
- `docker container run --name jhipster -v ~/jhipster:/home/jhipster/app -d -t jhipster:local` 
- `docker container exec -it jhipster bash` and `jhipster` command works fine


Not sure if there is an alternate way, but have to build every time I do a `git pull`

**Comment by vidhya03** [comment]
Hi, 
the generated gradle app from main branch using the below pom, however now it is not available , 
https://mvnrepository.com/artifact/tech.jhipster/jhipster-dependencies/8.0.0-SNAPSHOT

how to work with  jhipster dependencies . 
@mraible  please help

**Comment by Tcharl** [comment]
@pascalgrimaud who in in charge of the jh release process now?

**Comment by pascalgrimaud** [comment]
@Tcharl : same as before, all the leaders. @jdubois @deepu105 @DanielFran or me

**Comment by anothergoodguy** [comment]
hi Team,

Added some observation in the issue: [21735](https://github.com/jhipster/generator-jhipster/issues/21735).

**Comment by mraible** [comment]
I added a bug bounty to help motivate an alpha release. I think we can break things after alpha, but we should try to be API complete for a beta release.

**Comment by Tcharl** [comment]
@DanielFran @pascalgrimaud @deepu105 @jdubois 🙏

**Comment by mshima** [comment]
Typescript compile time was fixed yesterday at https://github.com/jhipster/generator-jhipster/pull/21815 dropped from ~2min to ~20s.
There is only one daily builds failure remaining described at https://github.com/jhipster/generator-jhipster/issues/21558 (couchbase is still broken, but it's not a blocker).

https://github.com/jhipster/generator-jhipster/pull/21559 should now, would be nice to merge it before release.

I will open a issue for beta now.

**Comment by pascalgrimaud** [comment]
As @DanielFran follows this repository, I think he's the best for doing this beta release.
I asked to him so I'm waiting his answer.

Otherwise, I can book time to do it

**Comment by vidhya03** [comment]
Yes please release beta.

**Comment by mraible** [comment]
@mshima Do you have a guestimate of when you think things might be ready for a beta release? Selfishly, I'd like to demonstrate it at Devoxx UK on May 11.

**Comment by mshima** [comment]
@mraible IMO the current blockers are https://github.com/jhipster/generator-jhipster/issues/21959.
IMO is really important to have frequent releases. I will set up a fork just for weekly builds.

**Comment by mshima** [comment]
I have an unfinished typescript based yeoman-generator, but I had a lot of problems integrating yeoman-environment/yeoman-test types interdependency.
I will need review the implementation and treat environment as untyped for the time been.

**Comment by deammanickam** [comment]
Hello, I have used Jhipster 7.9.3 for a govt project. Security scanning keeps complaining about upgrading spring-boot. Can I get a alpha-release of 8 some where to see how the scanners see them.

**Comment by DanielFran** [comment]
Generator version [8.0.0-beta.1](https://www.npmjs.com/package/generator-jhipster/v/8.0.0-beta.1) available
