### ISSUE TITLE
Main branch isn't able to generate empty project

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#20850]
See https://github.com/jhipster/generator-jhipster/issues/19782#issuecomment-1384301704

https://github.com/jhipster/generator-jhipster/pull/20838
https://github.com/jhipster/generator-jhipster/pull/20839

**Comment by mraible** [comment]
I was able to generate a project with `jhipster jdl 21-points.jh` and the following commands worked:

```
npm run ci:e2e:prepare
./gradlew 
# open a new terminal
npm run e2e
```

To me, this means that the `main` branch is working just fine.

**Comment by OmarHawk** [comment]
Mh, I tried continue working on some pull request, but after synching my fork's main branch to be identical as current main branch, nothing works anymore with that state of the repo for me on Win10, using Node 16.19.0 - every command I issue on command line ends up like this:

```
C:\Users\jw\git\mt\hipstertests\empty>jhipster
INFO! Using bundled JHipster
ERROR! The requested module '../../jdl/jhipster/index.mjs' does not provide an export named 'getConfigWithDefaults'
file:///C:/Users/jw/git/mt/generator-jhipster/dist/generators/base/generator-base.mjs:39
import { databaseTypes, monitoringTypes, authenticationTypes, buildToolTypes, cacheTypes, websocketTypes, messageBrokerTypes, testFrameworkTypes, applicationTypes, serviceDiscoveryTypes, searchEngineTypes, clientFrameworkTypes, getConfigWithDefaults, } from '../../jdl/jhipster/index.mjs';
                                                                                                                                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module '../../jdl/jhipster/index.mjs' does not provide an export named 'getConfigWithDefaults'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async JHipsterCommand._lazyBuildCommandCallBack (file:///C:/Users/jw/git/mt/generator-jhipster/dist/cli/program.mjs:125:43)
    at async JHipsterCommand._parseCommand (file:///C:/Users/jw/git/mt/generator-jhipster/dist/cli/jhipster-command.mjs:73:13)
    at async JHipsterCommand.parseAsync (C:\Users\jw\git\mt\generator-jhipster\node_modules\commander\lib\command.js:935:5)
```

I tried fixing that (got already around it) - but then other issues popped up making me believe I do something wrong...

**Comment by mshima** [comment]
@OmarHawk try removing node_modules/.cache

**Comment by mshima** [comment]
In any case, I think this issue can be closed already.

**Comment by OmarHawk** [comment]
> @OmarHawk try removing node_modules/.cache

Indeed - cleaning things did work. Wouldn't have expected that tbh. ;-)

**Comment by Tcharl** [comment]
as always, thanks @mshima for the smartest pattern found

**Comment by mshima** [comment]
> > @OmarHawk try removing node_modules/.cache
> 
> Indeed - cleaning things did work. Wouldn't have expected that tbh. ;-)

Old cache is built using cjs.
