### ISSUE TITLE
Please add a section in the wiki, for external configuration

### ISSUE THREAD

**Issue by artjomg** [jhipster/generator-jhipster#2087]
Hi,

since it is not really obvious to beginners, it would be great to explain to in the wiki how external spring boot configuration can be used in WAR mode.
For reference please use: http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

Thanks,
ArtjomG

**Comment by jdubois** [comment]
Thanks, but for me this is normal/standard Spring Boot use, so we shouldn't have to document this.
