### ISSUE TITLE
missing support for Nepali language; request adding support for Nepali language

### ISSUE THREAD

**Issue by psubedi2020** [jhipster/generator-jhipster#20889]
##### **Overview of the feature request**

* Add internationalization language support for Nepali language.

##### **Motivation for or Use Case**

* Saw jHipster supports Hindi and not Nepali

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@psubedi2020 Can you contribute with a PR?
