### ISSUE TITLE
Question Profile configuration (Not an issue)

### ISSUE THREAD

**Issue by maheshkaranjkar** [jhipster/generator-jhipster#2088]
Hi Team,

I know Its silly question. But I want to change active profile to Production. Please in which file I need to made changes . I have changed Both application.dev.yml and same for application.prod.yml with 
following changes.

<code>
spring:
    profiles:
        active: prod
</code>

and

<code>
spring:
    profiles:
        active: dev
</code>

Do I need to either profile inactive so that I will not get 

No Spring profile configured, running with default configuration"

Thanks 

Mahesh

**Comment by jdubois** [comment]
Hi,

This is our bugtracker, not the right place for questions (please follow our guidelines).

To run in production:

- Follow our guide at http://jhipster.github.io/production.html
- Have a look at the Spring Boot docs, we're just doing a Spring Boot app, and we are not documenting Spring Boot :-)
