### ISSUE TITLE
Update the Gradle build to use spring-boot-configuration-processor

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2091]
Sorry @atomfrede I tried to do it, but I definitely suck at Gradle!!

So in the pom.xml we have the new spring-boot-configuration-processor, and we should have it also on the Gradle side.

It's all documented here: http://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html

But this documentation isn't enough for me!

**Comment by atomfrede** [comment]
I'll have a look
