### ISSUE TITLE
jhipster confirmation email

### ISSUE THREAD

**Issue by migorman** [jhipster/generator-jhipster#2094]
Please i'm using jhipster and i'm facing a probleme with mail confirmation for new user (i cant send the email even if i 'm allowing less secure apps for my gmail)
this is my configuration : 
  host: smtp.gmail.com
    port: 587
    user: test@gmail.com
    password: test
    protocol: smtp
    tls: true
    auth: true
    from: test@gmail.com
and this is my log :+1: 
<html>
    <head>
        <title>Activation de votre compte bricole</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    </head>
    <body>
        <p>Cher mounir</p>
        <p>Votre compte bricole a été créé, pour l&#39;activer merci de cliquer sur le lien ci-dessous:</p>
        <p>
            <a href="http://127.0.1.1:8080/#/activate?key=35184515320597616575">mounir</a>
        </p>
        <p>
            <span>Cordialement,</span>
            <br />
            <em>bricole.</em>
        </p>
    </body>
</html>

[DEBUG] com.sun.mail.smtp - useEhlo true, useAuth true
[DEBUG] com.sun.mail.smtp - trying to connect to host "smtp.gmail.com", port 587, isSSL false
[DEBUG] com.sun.mail.smtp - connected to host "smtp.gmail.com", port: 587

[DEBUG] com.sun.mail.smtp - Found extension "SIZE", arg "35882577"
[DEBUG] com.sun.mail.smtp - Found extension "8BITMIME", arg ""
[DEBUG] com.sun.mail.smtp - Found extension "STARTTLS", arg ""
[DEBUG] com.sun.mail.smtp - Found extension "ENHANCEDSTATUSCODES", arg ""
[DEBUG] com.sun.mail.smtp - Found extension "PIPELINING", arg ""
[DEBUG] com.sun.mail.smtp - Found extension "CHUNKING", arg ""
[DEBUG] com.sun.mail.smtp - Found extension "SMTPUTF8", arg ""
[DEBUG] com.sun.mail.smtp - Found extension "SIZE", arg "35882577"
[DEBUG] com.sun.mail.smtp - Found extension "8BITMIME", arg ""
[DEBUG] com.sun.mail.smtp - Found extension "AUTH", arg "LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN XOAUTH OAUTHBEARER"
[DEBUG] com.sun.mail.smtp - Found extension "ENHANCEDSTATUSCODES", arg ""
[DEBUG] com.sun.mail.smtp - Found extension "PIPELINING", arg ""
[DEBUG] com.sun.mail.smtp - Found extension "CHUNKING", arg ""
[DEBUG] com.sun.mail.smtp - Found extension "SMTPUTF8", arg ""
[DEBUG] com.sun.mail.smtp - Attempt to authenticate using mechanisms: LOGIN PLAIN DIGEST-MD5 NTLM 
[WARN] ma.maroc.bricole.service.MailService - E-mail could not be sent to user 'bricole.maroc@gmail.com', exception is: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/answer/14257 pb4sm32897347wjb.8 - gsmtp

[DEBUG] ma.maroc.bricole.aop.logging.LoggingAspect - Exit: ma.maroc.bricole.service.MailService.sendActivationEmail() with result = null

**Comment by jdubois** [comment]
From your stacktrace:

    Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
    535 5.7.8 https://support.google.com/mail/answer/14257 pb4sm32897347wjb.8 - gsmtp

This is not a JHipster issue, you need to configure your SMTP server

**Comment by migorman** [comment]
thank you @jdubois

**Comment by migorman** [comment]
please even if i configure my smtp server i m facing the same problem 
Note : i can send mail trough console (ubuntu)
do u have any idea please ?

**Comment by mraible** [comment]
I tried these settings with my gmail account and I was able to make it work. I also confirmed I could register and receive an email. It seems your username and password are incorrect. All your other settings are the same ones I used.

**Comment by jdubois** [comment]
Oh, and I agree this is not obvious to configure!!

**Comment by atomfrede** [comment]
You have to use a dedicated imap/smtp password for your gmail account (at least for me) the credentials are not the same as your normal google login credentials.

**Comment by migorman** [comment]
it works :!! Thanks

2015-10-06 19:33 GMT+01:00 Frederik Hahne <notifications@github.com>:

> You have to use a dedicated imap/smtp password for your gmail account (at
> least for me) the credentials are not the same as your normal google login
> credentials.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/2094#issuecomment-145957685>
> .
>



-- 
Mounir IGORMAN
Ingénieur Etudes & Développement
Phone : +212617612986
