### ISSUE TITLE
Security: TokenProvider vulnerable to timing attacks

### ISSUE THREAD

**Issue by maklemenz** [jhipster/generator-jhipster#2095]
The TokenProvider uses `String.equals(str)` to compare the given token-signature with a calculated one. This method uses a break-on-inequality algorithm. This makes the TokenProvider vulnerable to timing attacks, where an attacker can forge a token with any username more easily than using brute force.

[Coda Hale did a nice blog post on this topic](http://codahale.com/a-lesson-in-timing-attacks/)

**Comment by jdubois** [comment]
Impressive. I knew about them, and I didn't think we were vulnerable to them.
I didn't write that code but I reviewed it quite carefully, and now you find this!! That's the great thing about JHipster, so many people working together.

Maybe we should also check for OAuth2, and for the standard Spring Security authentication mechanism. @rwinch have you already checked this in Spring Security?

**Comment by rwinch** [comment]
@jdubois Thanks for calling this to my attention.

Spring Security / Spring Security OAuth either uses 

* Constant time comparison (i.e. [PasswordEncoderUtils](https://github.com/spring-projects/spring-security/blob/4.0.2.RELEASE/core/src/main/java/org/springframework/security/authentication/encoding/PasswordEncoderUtils.java#L20) and [MacSigner](https://github.com/spring-projects/spring-security-oauth/blob/jwt1.0.1.RELEASE/spring-security-jwt/src/main/java/org/springframework/security/jwt/crypto/sign/MacSigner.java#L66)) or
* java.security.Signature.verify (i.e. [RsaVerifyier](https://github.com/spring-projects/spring-security-oauth/blob/jwt1.0.1.RELEASE/spring-security-jwt/src/main/java/org/springframework/security/jwt/crypto/sign/RsaVerifier.java#L54)) which takes care of timing attacks as of [JDK 1.6u17](http://www.oracle.com/technetwork/java/javase/6u17-141447.html)

**Comment by jdubois** [comment]
I thought I knew Spring Security quite well, and now I see goes way beyond what I imagined!!

By the way I should check the JWT support from Spring Security: I didn't know about this, it's probably better than our own custom-made solution.

**Comment by pnreddysvu** [comment]
There are few examples if you want to use JWT. Migrating to JWT also solves websocket authentication issue as well. See the below examples for reference.
https://github.com/auth0/socketio-jwt
https://github.com/nielsutrecht/jwt-angular-spring

**Comment by jdubois** [comment]
Thanks @pnreddysvu -> I'll add a new ticket to migrate to JWT

**Comment by jdubois** [comment]
Oh, and if we migrate to JWT, then we might not have to merge this PR -> I'm putting this on hold, until we have a closer look at JWT
