### ISSUE TITLE
jhipster confirmation email

### ISSUE THREAD

**Issue by migorman** [jhipster/generator-jhipster#2097]
Hi sir i cant send mail confirmation for my new users, u v told me to configure an smtp server wich i did and i can send mails from console(ubuntu) but still facing the same probleme with the application
[WARN] ma.maroc.bricole.service.MailService - E-mail could not be sent to user 'bricole.maroc@gmail.com', exception is: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/answer/14257 fr10sm20619218wib.14 - gsmtp

[DEBUG] ma.maroc.bricole.aop.logging.LoggingAspect - Exit: ma.maroc.bricole.service.MailService.sendActivationEmail() with result = null

**Comment by gmarziou** [comment]
Not a JHipster issue, please use stackoverflow to get help.

**Comment by jdubois** [comment]
This is a duplicate from #2094
