### ISSUE TITLE
Jhipster with external UI can not overcome Cors policy

### ISSUE THREAD

**Issue by pierre-filliolaud** [jhipster/generator-jhipster#20987]
##### **Overview of the issue**

Hi, 
due to the commit  [commit 38770697b0ab03a0c63a896faa1dea1cbf875c74](https://github.com/jhipster/generator-jhipster/commit/38770697b0ab03a0c63a896faa1dea1cbf875c74) and OPTIONS request sent by Axios [link:preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request#:%7E:text=It%20is%20an%20OPTIONS%20request,to%20craft%20such%20requests%20themselves.) ,
any external UI is now blocked by an OPTIONS Header CORS error (on localhost dev env).
Issue not reproduced in prod env

Error message:

>Access to XMLHttpRequest at 'http://localhost:8080/api/authenticate' from origin 'http://localhost:9000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

##### **Motivation for or Use Case**

It is a regression compared with the previous JHipster version

##### **Reproduce the error**

Run an external UI on local dev env

##### **Related issues**

Issue linked to [commit 38770697b0ab03a0c63a896faa1dea1cbf875c74](https://github.com/jhipster/generator-jhipster/commit/38770697b0ab03a0c63a896faa1dea1cbf875c74)

##### **Suggest a Fix**

In SecurityConfiguration.java.ejs add this:
```
<%_ if (!applicationTypeMicroservice) { _%>
    requestMatchers(HttpMethod.OPTIONS, "/**").permitAll()
```

##### **JHipster Version(s)**

7.9.3

##### **JHipster configuration**

JHipster Version(s)

server@0.0.0 /Volumes/DEV/jhipster-server-app
└── generator-jhipster@7.9.3

Environment and Tools

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Homebrew (build 17.0.6+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.6+0, mixed mode, sharing)

git version 2.32.0 (Apple Git-132)

node: v18.13.0
npm: 8.19.3

Docker version 20.10.11, build 

No change to package.json was detected. No package manager install will be executed.

##### **Browsers and Operating System**

Mac M1 - macOS Monterey 
Browser: 
- Safari - Version 15.4 (17613.1.17.1.13)
- Firefox - 109.0 (64-bit)
- Chrome - Version 109.0.5414.119 (Official Build) (arm64)

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
Closing as per comments in https://github.com/jhipster/generator-jhipster/pull/20988
