### ISSUE TITLE
baseName can't have capital letters when use microfrontend

### ISSUE THREAD

**Issue by paris0120** [jhipster/generator-jhipster#20986]
##### **Overview of the issue**

Can't use capital letters in baseName, for example "baseName" when use microfront end or will get errors like 
```

Error: Error parsing file webpack/webpack.microfrontend.js: SyntaxError: Unexpected token, expected "," (79:14)
  77 |       }),
  78 |       new DefinePlugin({
> 79 |         BASE NAME_I18N_RESOURCES_PREFIX: JSON.stringify(''),
     |              ^
  80 |       }),
  81 |
  82 |     ],

```

##### **Motivation for or Use Case**
Use CamelCase for baseName 

##### **Reproduce the error**
Use word with capital letters in the middle as baseName, such as "baseName"

 

##### **Suggest a Fix**
Separate names with underlines.

##### **JHipster Version(s)**

7.9.3
##### **JHipster configuration**

```
application {
  config {
    baseName baseName,
    serverPort 8081,
    applicationType microservice,
    authenticationType oauth2,
    databaseType sql,
    prodDatabaseType mysql,
    devDatabaseType mysql,
    clientFramework react,
    testFrameworks [cypress],
    serviceDiscoveryType consul,
    cacheProvider redis,
    buildTool maven,
    reactive true,
    messageBroker kafka
  } 
}
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by bonusware** [comment]
Um facing the same issue.
