### ISSUE TITLE
Liquibase async using fast mode instead of dev

### ISSUE THREAD

**Issue by moifort** [jhipster/generator-jhipster#2099]
@Julien I use Liquibase async feature (cool feature!), I just want to know, why using `SPRING_PROFILE_DEVELOPMENT` mode instead  of `SPRING_PROFILE_FAST` mode. This is my points:
* Using in association with other mode
* It speeds up the application on startup, as the purpose of fast mode
* It speeds up despite some problems (like a normal behavior when using fast mode)

**Comment by jdubois** [comment]
Yes I'm going to change all this:

- There will be more options for Liquibase: like async mode, force locks, etc. It's discussed in https://github.com/jhipster/generator-jhipster/issues/2079#issuecomment-145331017 -> this is why I'm closing this ticket, it's nearly a duplicate
- In fact, things might even go further -> as Liquibase is the biggest thing that slows down startup time, that might be the end of the "fast" profile. Remember we will also have Spring Boot 1.3 dev tools soon, also.... So the "dev" profile should soon be enough! As the fast profile is a pain to test, I would be happy to ditch it!
