### ISSUE TITLE
How to disable elastic search?

### ISSUE THREAD

**Issue by maheshkaranjkar** [jhipster/generator-jhipster#2101]
Hi Guys,

We want to disable elastic search in our application.
Kindly suggest me how to disable the same. In existing application

Regards
Mahesh

**Comment by deepu105** [comment]
You mean you have generated an app with elastic search option?  And now you want to remove it?
If the current state of your app is not customized too much then the easiest way is to take the `.yo-rc.json` file turn elastic search flag off and regenerate app and entities, then compare and merge customizations back into the newly generated app.

I dont think there is an easy way to remove

**Comment by tibistibi** [comment]
i can confirm that removing does not work. even with a freshly generated project. 
after changing .yo-rc.json and re-generating there are a bunch of files still revering to elastic search.

**Comment by gmarziou** [comment]
I don't understand how this would be possible starting from an empty project directory, however if you changed the value in .yo-rc.json and re-generated then of course only files common to both will be modified, old files related to Elasticsearch are not deleted by the re-generation. To do so you probably have to work on a git branch and merge such what the upgrade generator does.

But please don't comment an old closed issue.
Open a new issue with required details if you think you found an issue.

**Comment by tibistibi** [comment]
i don't think this is the kind of issue which needs to be fixed. i only wanted add my remark to others will know it is not possible.

**Comment by deepu105** [comment]
Its absolutely possible to change something in the yo-rc file and
regenerate app. The only thing to take care is to delete files that are not
needed. What I normally do is create a new branch, do a `rm -rf *` and then
do the regeneration, commit, then merge the branch back and resolve
conflicts if any.

**Comment by tibistibi** [comment]
yes this works!

**Comment by mikeyfreake** [comment]
In particular, the field that needs to be updated in `.yo-rc.json` is this:
`"searchEngine": "elasticsearch"`
to this:
`"searchEngine": false`

**Comment by sachinGBrightLifecare** [comment]
Above changes does not help me , having same issue .

**Comment by ghacupha** [comment]
Did you regenerate with entities? If you did they entities will have elastic search code. You need to open .jhipster folder and remove set all search fields in every entity to false

**Comment by kevintanhongann** [comment]
I was thinking about this scenario for a while, and when it comes to us developers doing prototyping, it's difficult to change since the app has already been generated.

If there's a way to enable or disable elasticsearch in the project, I don't know if it can be done via Feature Flag 4j and yml or not. But if it can, would be wonderful.

`elasticsearch:
       enable: true/false`

**Comment by gmarziou** [comment]
@kevintanhongann have you looked at JHipster Lite?

https://www.youtube.com/watch?v=RnLGnY-vzLI
