### ISSUE TITLE
OneToMany relationships implemented as Set, should be List

### ISSUE THREAD

**Issue by fillumina** [jhipster/generator-jhipster#21065]
##### **Overview of the issue**

The Entity generator generates a `OneToMany` relationship as a `Set`, given the generated default `hashCode()` it should be a `List`.

This is an example of a generated code:

```java
@OneToMany(mappedBy = "product")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@JsonIgnoreProperties(value = { "product" }, allowSetters = true)
private Set<ACImage> aCImages = new HashSet<>();
```

but in ACImage class the`hashCode()` method is generated as:

```java
@Override
public int hashCode() {
    // see https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/
    return getClass().hashCode();
}
```

**which returns the same hash code for every ACImage object**. This makes using `Set` very inefficient because at each insertion all the collection has to be scanned to search for an equal object (and there might be even worse outcome in case of lazy fetching).

Hibernate documentation [Implementing equals() and hashCode()](https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#mapping-model-pojo-equalshashcode) properly suggests to use a natural key in `equals()` and `hashCode()` if possible or the default `Object` one otherwise. I would prefer the safer [Mihalcea approach](https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/).

Moreover both [How do Set and List collections behave with JPA and Hibernate](https://vladmihalcea.com/hibernate-facts-favoring-sets-vs-bags/) and Hibernate docs [Bags and lists are the most efficient inverse collections](https://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html/ch20.html#performance-collections-mostefficentinverse) advise to use `List` rather than `Set` for bidirectional associations. As a side note they also advise against using unidirectional associations at all.

Because the generated code should be efficient I would prefer having a `List` by default and eventually changing it to `Set` manually in case of a better customized implementation of `equals()` and `hashCode()`. It would be ideal to leave a message explaining that also.

##### **JHipster Version(s)**

7.9.3

**Comment by vw98075** [comment]
I have the same issue with the collection data type for my recent project. I have chronic data on the "many" side of the many-to-one relationship. The Set data type messes up the chronic order of the collection data. Although it isn't a big deal to change the data type manually, I am wondering any reason for using Set instead List.  In my memory, JHispter used to generate a List, but not a Set for the scenario.

**Comment by nomuna** [comment]
I think it comes from JPA/Hibernate:

https://docs.jboss.org/hibernate/jpa/2.1/api/javax/persistence/OneToMany.html

 To have the many part as a list is a specific use case and in my opinion should be configurable and not default.

**Comment by fillumina** [comment]
If you follow what [Hibernates recommends](https://docs.jboss.org/hibernate/stable/core.old/reference/en/html/persistent-classes-equalshashcode.html) for `equals()` and `hashCode()` yes but because jhipster chose to default on an alternative implementation following the hints of Mihalcea using `Set` leads to sever performance hits as already explained before.

**Comment by nomuna** [comment]
I could go with LinkedHashSet if people want to have an order in the set. List is a bad idea or it is a very specific case and should be configurable and not a default.

**Comment by nomuna** [comment]
"Because the generated code should be efficient I would prefer having a List by default and eventually changing it to Set manually in case of a better customized implementation of equals() and hashCode(). It would be ideal to leave a message explaining that also." Sounds like an (too) early optimization. If you do not like the general implementation that works most of the time but does not fit your use case do the changes yourself later and not force it on the others who have no problem with the defaults.

**Comment by nomuna** [comment]
> Because the generated code should be efficient I would prefer having a `List` by default and eventually changing it to `Set` manually in case of a better customized implementation of `equals()` and `hashCode()`. It would be ideal to leave a message explaining that also.

Sounds like an (too) early optimization. If you do not like the general implementation that works most of the time but does not fit your use case do the changes yourself later and not force it on the others who have no problem with the defaults.

**Comment by fillumina** [comment]
Regarding the different semantic whatever you use, `Set` or `List`, will be filtered for duplicated entries directly at the Hibernate / DB level. The end result will be just the same (but using `List` would avoid wasting comparisons).

**Comment by fillumina** [comment]
This is an extract from the Vlad Mihalcea's [The best way to implement equals, hashCode, and toString with JPA and Hibernate](https://vladmihalcea.com/the-best-way-to-implement-equals-hashcode-and-tostring-with-jpa-and-hibernate/) referring to the penalty in using his proposed solutions (adopted by JH) :

>  The only time when you’ll see a performance bottleneck due to a single hash bucket is if you have a large collection of tens of thousands of entries.
>
>    But then, it implies that you fetched that large collection from the database. The performance penalty of fetching such a collection from the database is multiple orders of magnitude higher than the single bucket overhead.
>
>  That’s why you never map large collections with Hibernate. You use queries for those instead. But then, for small collections.
>
> Also, most of the time you don’t even need to use a Set or a Map. For bidirectional associations, List(s) perform better anyway. 

It seems that I have overestimated the performance penalty of using a `Set` with a constant class hashCode value (the set should contain few entities anyway) and it's obviously working as expected:
 
 1. adding a non persisted entity to the set will always create a new item (`equals()` always `false`)
 2. adding a persisted entity already present will not change the set (as expected) so `size()` is kept coherent

So, being it just a matter of a little performance difference, I apologize and close the issue.
