### ISSUE TITLE
Outdated reference to zalando in package-info

### ISSUE THREAD

**Issue by lmartelli** [jhipster/generator-jhipster#21075]
https://github.com/jhipster/generator-jhipster/blob/c81606b1cd94dc19df3593237916741680470e62/generators/server/templates/src/main/java/package/web/rest/errors/package-info.java.ejs#L20

If I am not mistaken, zalando/problem is not used anymore, so the comment should be updated.

**Comment by DanielFran** [comment]
@lmartelli Can you contribute with a PR?

**Comment by KanniShashankh** [comment]
#21083 There is also a reference to Zalando in api.yml.ejs (generators/server/templates/src/main/resources/swagger/api.yml.ejs), can i update that too? @DanielFran

**Comment by KanniShashankh** [comment]
@DanielFran need some help in understanding how it should be updated, does i replace it with a new schema or delete it altogether?

**Comment by DanielFran** [comment]
Hi @KanniShashankh, sorry for my late answer, I made a suggestion in the PR.
Please fix also the comment in swagger api.yml file
Thanks

**Comment by KanniShashankh** [comment]
Thanks @DanielFran for letting me know how the comment should be added. I have commited the requested changes.

**Comment by DanielFran** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/21507
package-info is now autogenerated and the reference is not available anymore
