### ISSUE TITLE
jhipster.tech: page for freelancers

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#21076]
As discussed during our JHipster Association General Assembly, it would be cool to create a page for the freelancers in the JHipster Core Team members.

I think there can be:
- @PierreBesson 
- @wmarques 
- @avdev4j 
- @pascalgrimaud (me)

**Comment by pascalgrimaud** [comment]
Still todo

**Comment by pascalgrimaud** [comment]
I'll take time to do it

**Comment by mraible** [comment]
I'd be happy to do consulting for generator-jhipster. ;)

**Comment by pascalgrimaud** [comment]
@mraible : oh, are you freelancer now?

**Comment by mraible** [comment]
@pascalgrimaud I'm keeping my options open at this point.
