### ISSUE TITLE
cli and bootstrap improvements.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#21080]
##### **Overview of the feature request**

There is a series of cleanups and improvements to cli and bootstrap.

- [x] improve generation speed `ng(x)-default` takes 4m30s to generate at v7. Due to https://github.com/jhipster/generator-jhipster/issues/20782, it was possible to reduce to 1m20s optimizing mem-fs-editor usage.
- [x] drop fork usage and convert to await/async https://github.com/jhipster/generator-jhipster/pull/21048
- [x] replace yeoman-generator's in constructor option definition with a custom made definition and parsing https://github.com/jhipster/generator-jhipster/pull/21077
- [x] apply new option definition at main generators
- [x] optimize transforms (requires [mem-fs](https://github.com/SBoudrias/mem-fs/pull/27), yeoman-environment and yeoman-generator) improvements.
- [x] modularize `@GeneratedByJHipster` transform.
- [x] check the possibility of converting frontend translations transforms
- [x] convert jdl command into a generator. simplified implementation and adds blueprint support.
- [x] integrate import-jdl into jdl command.
- [x] don’t look for jhipster at local dir and require the standard `npx jhipster` to run the locally installed jhipster.
- [x] move options load from the constructor to the initializing priority at main generators

##### **Motivation for or Use Case**

Improve user experience.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@mshima Anything missing here or all have been done?

**Comment by mshima** [comment]
@DanielFran yes, the description missing items.
https://github.com/jhipster/generator-jhipster/blob/79d717f14c2b1f22adaee33dcf09170c497ec4f2/generators/app/generator.mjs#L48-249

I’ve started the change.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/170968

**Comment by DanielFran** [comment]
@mshima approved
