### ISSUE TITLE
Gradle CI build is failing

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2110]
I have no problem to build it on my machine, only the CI build fails:
https://drone.io/github.com/jhipster/jhipster-sample-app-gradle

@atomfrede can you have a look?

**Comment by atomfrede** [comment]
Yes. I'll try. Looks like a strange error. Will try it on my gitlab ci instance maybe.

**Comment by pascalgrimaud** [comment]
On my computer : work
On my personnal travis-ci : work
So I tested on drone.io : same error

I changed the script :
```
./gradlew test
```

to :
```
bower -v
./gradlew test
```

drone.io logs :
```
/home/ubuntu/.build.sh: line 53: bower: command not found
```

So I manually installed bower:
```
sudo npm install -g bower
bower -v
./gradlew test
```

It works. I suppose drone.io has changed something...

**Comment by atomfrede** [comment]
@jdubois Can you change the setup according to @pascalgrimaud suggestion?

**Comment by jdubois** [comment]
Thanks! It looks better, but now I have some JUnit failing tests... This is probably another matter, so I'm closing this for the moment
