### ISSUE TITLE
gulp-imagein import failed

### ISSUE THREAD

**Issue by Jessy-BAER** [jhipster/generator-jhipster#21119]
##### **Overview of the issue**

On https://github.com/jhipster/jhipster.github.io an error occurred when i run the command `npm run sass` 

This issue is caused by `gulp-imagemin` v8 and this [commit](https://github.com/jhipster/jhipster.github.io/commit/60359a4d77e038aa5bcf4e23f19ae674960d2156)

```
npm run sass

> sass
> gulp sass

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/jessy/workspace/jhipster.github.io/node_modules/gulp-imagemin/index.js from /home/jessy/workspace/jhipster.github.io/gulpfile.js not supported.
Instead change the require of index.js in /home/jessy/workspace/jhipster.github.io/gulpfile.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/jessy/workspace/jhipster.github.io/gulpfile.js:4:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

##### **Suggest a Fix**

[See issue](https://github.com/imagemin/imagemin/issues/392#issuecomment-932981174)

Replace `require` by `import`

```
  imagemin = import("gulp-imagemin");
```

##### **Browsers and Operating System**

Node 19 / Ubuntu 22.04

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
Closed in https://github.com/jhipster/jhipster.github.io/pull/1265

**Comment by SI-Ayush-Shah** [comment]
import stop working due to this

this is error i git
``` ypeError: imagemin is not a function
    at imgTask (D:\New folder\test\gulpfile.js:30:15)
    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (D:\New folder\test\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
[15:55:15] 'default' errored after 5.38 ```
