### ISSUE TITLE
isUserInRole() returning false for an existing role

### ISSUE THREAD

**Issue by jvence** [jhipster/generator-jhipster#2112]
I've generated an oAuth based app. 
Calling SecurityUtils.isUserInRole(...) always returns false as springSecurityUser.getAuthorities() is empty even though userService.getUserWithAuthorities(); returns a user with specific authorities.

**Comment by jdubois** [comment]
There isn't such a method in JHipster. This has been refactored some time ago, so I guess you are using an older version -> please follow our guidelines and give us your version information!

**Comment by andidev** [comment]
@jdubois That's not true 
See https://github.com/jhipster/generator-jhipster/blob/a6dcd5425ca5e3c35b6821fb21baf461869920e5/app/templates/src/main/java/package/security/_SecurityUtils.java#L61

**Comment by jdubois** [comment]
Oh, you're right... I thought I deleted all of those, sorry @jvence !

-> it is not currently being used anywhere in the code, and indeed I doubt it's working (just looking at the code)

**Comment by jdubois** [comment]
So I've just tested it, and in fact it's working fine...

Doing:

    log.debug("user role->" + SecurityUtils.isUserInRole(AuthoritiesConstants.USER));
    log.debug("admin role->" + SecurityUtils.isUserInRole(AuthoritiesConstants.ADMIN));
    log.debug("yolo role->" + SecurityUtils.isUserInRole("ROLE_YOLO"));

I got:

    [DEBUG] eeee.web.rest.FooResource - user role->true
    [DEBUG] eeee.web.rest.FooResource - admin role->true
    [DEBUG] eeee.web.rest.FooResource - yolo role->false

**Comment by jvence** [comment]
Which authentication mechanism are you using on your test app?

**Comment by jvence** [comment]
Ok I've created a brand new project (with oAuth & mongodb) using JHipster Generator v2.21.1, 

I get the following after login in as admin and calling  getAccount()
[DEBUG] com.mycompany.myapp.web.rest.AccountResource - user role->false
[DEBUG] com.mycompany.myapp.web.rest.AccountResource - admin role->false
[DEBUG] com.mycompany.myapp.web.rest.AccountResource - yolo role->false

**Comment by gmarziou** [comment]
@jvence could you share a repo with your sample project? it would help

**Comment by jvence** [comment]
@gmarziou Seriously it would be more of a hassle for you to see the project (which I will share). Simply create a new project as specified above and try it. I made no changes to the default generated project.

**Comment by mrinalsharma** [comment]
@jvence Was this issue ever resolved? I see the same issue.

**Comment by deepu105** [comment]
This is an old issue lot of things have changed since, plz open new issue
if you are facing problems
