### ISSUE TITLE
jhipster.github.io website new design implementation (website tree structure)

### ISSUE THREAD

**Issue by ascelineboullen** [jhipster/generator-jhipster#21139]
I propose to create a specific issue about the website tree structure, It will help for the website redesign implementation mentioned here : https://github.com/jhipster/generator-jhipster/issues/13595

With the mockup we have a first version proposed for redesign with the screens mocked up, but a larger reflection is to be done on the global website structure.

I've init this document to work with @jessy-BAER about the different routing, which links to which page, and differentiate what will be external, or internal, and the links to the documentation. 
https://whimsical.com/jhipster-arborescence-RxvQrWktaDY9P2DTzSSR9P

We're working on it this week and then we'll be able to give you a diagram to discuss .

**Comment by pascalgrimaud** [comment]
First of all, thanks for your work @ascelineboullen and @Jessy-BAER

Just keep in mind the current documentation uses markdown file (see https://github.com/jhipster/jhipster.github.io) so it's easy to update, create new pages and improve the doc.

Then about the architecture of the website, I'm not the best here to provide some advice. Maybe @deepu105 ?

Cc @jdubois  @jhipster/developers too

**Comment by atomfrede** [comment]
Good question @pascalgrimaud . We should try to keep it simple. Right now when someone opens our homepage you can't really tell what jhipster is and where to start. Maybe we should try to guide the users more (Prerequsites, Quick Start, Options) or so. E.g. when you have scrolled down the landing page you have some kind of "up next" link or so.

**Comment by ascelineboullen** [comment]
To give you visibility on progress:
- I finished parsing the current site tree and clipped it to the Whimsical file (there: https://whimsical.com/jhipster-arborescence-RxvQrWktaDY9P2DTzSSR9P). 
- Then I'v defined the global tree propose for the redesign. 
- I'm working on the re-structuring the different parts of the documentation. And I will be able to notifie you friday to confirm the rework structure proposition for the docs 😉

Thx in advance!

**Comment by deepu105** [comment]
One thing to keep in mind is to preserve URLs or add proper redirects to
avoid SEO issues and to retain current SEO

Thanks & Regards,
Deepu
