### ISSUE TITLE
npm bin command is removed in NPM 9+

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#21138]
We use the bin command in upgrade generator (`generators/upgrade/generator.mjs`) and it does not work anymore with NPM 9+

```js
const generatorDir = shelljs.exec('npm bin', { silent: this.silent }).stdout;
```

**Comment by mshima** [comment]
@mraible what do you think about https://github.com/jhipster/generator-jhipster/issues/19779?

**Comment by mraible** [comment]
If it improves the upgrade process, I'm all for it!
