### ISSUE TITLE
Generated project cannot use ng-strict-di which suggests possible problems with prod profile minification

### ISSUE THREAD

**Issue by tmendenhall** [jhipster/generator-jhipster#2113]
I am getting javascript errors with ng-strict-di activated in the index.html running under a non-prod profile.
The application was generated with the following configuration file. 
.yo-rc.json
```javascript
{
  "generator-jhipster": {
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "<redacted>"
  }
}
```
The grunt build task includes the plugin:
```javascript
ngAnnotate: {
            dist: {
                files: [{
                    expand: true,
                    cwd: '.tmp/concat/scripts',
                    src: '*.js',
                    dest: '.tmp/concat/scripts'
                }]
            }
        }
```
for expanding the dependency injection parameters for minification:
[The Angular documentation for 1.4](https://code.angularjs.org/1.4.7/docs/guide/di)
recommends using ng-strict-di for implicit injection in order to guard against minification failures.

I modified the index.html file to include the directive:
```
<body ng-app="testApp" ng-strict-di>
```

Building and executing the project as specified in the README.md file
```
./gradlew -Pprod clean bootRepackage
java -jar build/libs/*.war --spring.profiles.active=prod
```
results in a running application. 
However if I run with a non-prod configuration using the bootRun Gradle task:
```
./gradlew bootRun
```
I get the following console error in my browser:
```javascript
Uncaught Error: [$injector:modulerr] Failed to instantiate module testApp due to:
Error: [$injector:strictdi] function($stateProvider, $urlRouterProvider, $httpProvider, $locationProvider,  httpRequestInterceptorCacheBusterProvider) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.4.5/$injector/strictdi?p0=function(%24statePr…2C%20%24locationProvider%2C%20%20httpRequestInterceptorCacheBusterProvider)
    at REGEX_STRING_REGEXP (http://localhost:8080/bower_components/angular/angular.js:68:12)
    at Function.annotate [as $$annotate] (http://localhost:8080/bower_components/angular/angular.js:3742:17)
    at Object.invoke (http://localhost:8080/bower_components/angular/angular.js:4451:36)
    at runInvokeQueue (http://localhost:8080/bower_components/angular/angular.js:4379:35)
    at http://localhost:8080/bower_components/angular/angular.js:4388:11
    at forEach (http://localhost:8080/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:8080/bower_components/angular/angular.js:4369:5)
    at createInjector (http://localhost:8080/bower_components/angular/angular.js:4294:11)
    at doBootstrap (http://localhost:8080/bower_components/angular/angular.js:1655:20)
    at bootstrap (http://localhost:8080/bower_components/angular/angular.js:1676:12)
http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=testApp&p1=Error%3A…F%2Flocalhost%3A8080%2Fbower_components%2Fangular%2Fangular.js%3A1676%3A12)
```
Thank you for your time and consideration.

**Comment by gmarziou** [comment]
Interesting, I found that [ng-annotate recommends using ng-strict-di](https://github.com/olov/ng-annotate#highly-recommended-enable-ng-strict-di-in-your-minified-builds)

However, I am not very comfortable with this because
- I read our code and I don't understand the error, can you explain it? 
- using ng-annotate and ng-strict-di does not seem so simple: olov/ng-annotate#142, Swiip/generator-gulp-angular#419 and http://peterkellner.net/2014/11/14/angular-ngannotate-better-way/

**Comment by deepu105** [comment]
@gmarziou i didn't take a closer look but from what i understand issue
seems to be this. I might be wrong

Ng strict di validates for proper di syntax which is present in prod
profile as ng annotate adds proper syntax to minified files, but the normal
dev profile non minified code lacks that as ng annotate doesn't act on non
minified files.

One solution would be to remove ng annotate and correct syntax in all our
js manually. I guess @gzsombor already corrected syntax on the entity
controllers and routes.

**Comment by gmarziou** [comment]
Yes it makes sense.
So I guess if we use proper di syntax, ng-annotate is useful only for minification in case we import non strict modules

**Comment by tmendenhall** [comment]
If I get a chance I will check the 2.23.0 import definitions and see if they all follow the recommended di syntax. Thanks.

**Comment by deepu105** [comment]
That will be great Tyler you are welcome to do PR to improve this

**Comment by deepu105** [comment]
This issue will be resolved when https://github.com/jhipster/generator-jhipster/issues/2271 is implemented

**Comment by deepu105** [comment]
this will be done as part of https://github.com/jhipster/generator-jhipster/issues/2271

**Comment by deepu105** [comment]
Im
