### ISSUE TITLE
Sort table is not working in Jhipster angular

### ISSUE THREAD

**Issue by mansourofski** [jhipster/generator-jhipster#21141]
##### **Overview of the feature request**

Sort table is not working in Jhipster angular

##### **Motivation for or Use Case**

when you add a new entity, the sort icon are not working

##### **Related issues or PR**
the solution is:
check the method fillComponentAttributesFromResponseBody

change the content of that method to be like this::
 ` protected fillComponentAttributesFromResponseBody(data: IReferences[] | null): IReferences[] {
    const referencesNew = [];
    if (data) {
      for (const d of data) {
        if (referencesNew.map(op => op.id).indexOf(d.id) === -1) {
          referencesNew.push(d);
        }
      }
    }
    return referencesNew;
  }`

and it will work. enjoy

**Comment by glewe** [comment]
I resolved this by doing this in the list component:
```
  navigateToWithComponentValues(): void {
    this.page = 0;
    this.workstations = [];
    this.handleNavigation(this.page, this.predicate, this.ascending, this.currentSearch);
  }
```

**Comment by mansourofski** [comment]
> navigateToWithComponentValues(): void {

inside this method I have this code:
 navigateToWithComponentValues(): void {
    this.handleNavigation(this.page, this.predicate, this.ascending);
  }
