### ISSUE TITLE
Entity Resource Test - Bug when an entity is created with a Blob attribute

### ISSUE THREAD

**Issue by dalbelap** [jhipster/generator-jhipster#2116]
When an entity is created with a blob attribute, the test class *test.web.rest.[Entity]ResourceTest.java* is created with aditional methods *set[Field]ContentType* for all attributes. This is because of the bellow code:
```javascript
<%_ if (fieldType == 'byte[]') { _%>
 <%= entityInstance %>.set<%= fields[fieldId].fieldInJavaBeanMethod %>ContentType(<%='DEFAULT_' + fields[fieldId].fieldNameUnderscored.toUpperCase()%>_CONTENT_TYPE);
<%_ } _%>
```
Inside the foreach, fieldType var does not exist. So I fix it in my forked repo with this [commit](https://github.com/dalbelap/generator-jhipster/commit/17a0764aacfa33d66111d309708d4fc35aa36d70). But, I'm sorry, I already had send another PR for another feature (language fix).

**Comment by andidev** [comment]
You should create branches and do PR's from them. Then you can have multiple PR's at the same time.

**Comment by jdubois** [comment]
Yes @andidev is right - it's not obvious to use!!

**Comment by andidev** [comment]
This will solve your issues:

```bash
git checkout master
git branch temp
git checkout -b fix-blob-bug
git reset --hard 9d425c5
git cherry-pick 17a0764
git push
```

and then PR the fix-blob-bug branch from github

**Comment by dalbelap** [comment]
Thanks @andidev and @jdubois. Here is the PR #2119 

I used a branch in other PR (#2108) but when I pushed I saw the other files from a third PR (#2107). So in this case I have prefered to ask.. I did not think to use the branch with a hard reset to prevent other local changes.. I have still much to learn with git.

**Comment by andidev** [comment]
Closing this since it is fixed
