### ISSUE TITLE
Migration to Spring Boot 1.3

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2117]
This ticket is to follow the Spring Boot 1.3 migration.

We are working on the [spring_boot_1_3 branch](https://github.com/jhipster/generator-jhipster/tree/spring_boot_1_3).

Current issues:

- Some Liquibase errors: I intend to add some options to force Liquibase locks
- Only tested with MySQL -> I expect issues with H2 (btw, I would like to use H2 disk persistence in the future, and not just in-memory)
- Need to work on `spring.devtools.restart.exclude` and `spring.devtools.restart.additional-paths` properties to see if we can improve things
- Restart could be faster (currently 2 seconds) -> reloading metrics, swagger, etc is not useful, but do they really take much time?
- Need to go through all the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes) to migrate all the rest of the app to Spring Boot 1.3

**Comment by jdubois** [comment]
I have now everything working, excepted an issue on Dates when using DTOs -> this will be changed later, as we need to migrate from JodaTime to new Date API

Is everyone fine with me merging this into the master branch?

**Comment by mraible** [comment]
I'm OK with it, but a pull request that we can comment on might be a bit
easier to digest.

**Comment by andidev** [comment]
+1

**Comment by jdubois** [comment]
The PR is available at #2136

**Comment by pascalgrimaud** [comment]
did you forget updating gradle ?

**Comment by jdubois** [comment]
@pascalgrimaud  Oh yes, totally!

**Comment by jdubois** [comment]
OK I'm trying to merge PR #1640 with it, and it's a nightmare...

So I'm merging this first into master, so I can start working on PR #1640 correctly. Too many branches and conflicts...

**Comment by getintouchapp** [comment]
The gradle.properties still shows spring boot as 1.2.6 and manually changing this to 1.3.0 throws up liquibase errors

**Comment by pascalgrimaud** [comment]
I see 1.3.0.RELEASE in gradle.properties
https://github.com/jhipster/generator-jhipster/blob/master/app/templates/_gradle.properties#L32

**Comment by atomfrede** [comment]
@getintouchapp Which version are you using? Just changing the spring boot version just doesn't work

**Comment by getintouchapp** [comment]
I am using JHipster release 2.25.0

**Comment by atomfrede** [comment]
Have you updated from an older version?

**Comment by getintouchapp** [comment]
Yes I don't know what was the previous version of jhipster. But even if I create a new project now gradle.properties shows Spring Boot 1.2.6
