### ISSUE TITLE
AccountResourceIT for OAuth2 is confusing

### ISSUE THREAD

**Issue by lmartelli** [jhipster/generator-jhipster#21217]
##### **Overview of the feature request**

When using OAuth2, generated AccountResourceIT looks confusing to me (tested on 8.0.0-SNAPSHOT from `main`).

Let me explain :-)

- `@WithMockUser(value = TEST_USER_LOGIN)` is used of the test class but is overridden in almost all test cases, so it doesn't make sense to use it at the class level. In `testGetExistingAccount` we have `TestSecurityContextHolder.getContext().setAuthentication()` which, unless I am missing something totally overwrites the effect of `@WithMockUser`. In `testNonAuthenticatedUser()` it is overridden by  `@WithUnauthenticatedMockUser` and in `testAuthenticatedUser()` `setRemoteUser()` is used, which should not be necessary and make the test depend on the implementation. So in the end, `@WithMockUser` is only ever used `testGetUnknownAccount()` where it triggers an error 500 because `UserService.getUserFromAuthentication()` only accepts `OAuth2AuthenticationToken` or `JwtAuthenticationToken` and  throws an `IllegalArgumentException` otherwise.

- Why would you want an `InternalServerError` in `testGetUnknownAccount()` ? Internal server errors are bugs, by definition, so I see no reason to expect one in a test. It would make more sense to have a 401 Unauthorized.

- It is overkill to use `@IntegrationTest` which triggers the DB test container since the DB is not tested in any way here.

I am willing to submit a PR, before I put my hands in the template, I'd prefer to have a discussion based on the generated file.

For reference, here's the generated file in the non-reactive case :

```
@AutoConfigureMockMvc
@WithMockUser(value = TEST_USER_LOGIN)
@IntegrationTest
class AccountResourceIT {

    @Autowired
    private MockMvc restAccountMockMvc;

    @Autowired
    OAuth2AuthorizedClientService authorizedClientService;

    @Autowired
    ClientRegistration clientRegistration;

    @Test
    @Transactional
    void testGetExistingAccount() throws Exception {
        TestSecurityContextHolder
            .getContext()
            .setAuthentication(registerAuthenticationToken(authorizedClientService, clientRegistration, testAuthenticationToken()));

        restAccountMockMvc
            .perform(get("/api/account").accept(MediaType.APPLICATION_JSON))
            .andExpect(status().isOk())
            .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
            .andExpect(jsonPath("$.login").value(TEST_USER_LOGIN))
            .andExpect(jsonPath("$.email").value("john.doe@jhipster.com"))
            .andExpect(jsonPath("$.authorities").value(AuthoritiesConstants.ADMIN));
    }

    @Test
    void testGetUnknownAccount() throws Exception {
        restAccountMockMvc.perform(get("/api/account").accept(MediaType.APPLICATION_JSON)).andExpect(status().isInternalServerError());
    }

    @Test
    @WithUnauthenticatedMockUser
    void testNonAuthenticatedUser() throws Exception {
        restAccountMockMvc
            .perform(get("/api/authenticate").accept(MediaType.APPLICATION_JSON))
            .andExpect(status().isOk())
            .andExpect(content().string(""));
    }

    @Test
    void testAuthenticatedUser() throws Exception {
        restAccountMockMvc
            .perform(
                get("/api/authenticate")
                    .with(request -> {
                        request.setRemoteUser(TEST_USER_LOGIN);
                        return request;
                    })
                    .accept(MediaType.APPLICATION_JSON)
            )
            .andExpect(status().isOk())
            .andExpect(content().string(TEST_USER_LOGIN));
    }
}
```

**Comment by mraible** [comment]
@lmartelli If you'd like to create a pull request to simplify things, please do!

**Comment by dinu0000** [comment]
i will try to do a PR soon

**Comment by deepu105** [comment]
This is actually way more work in terms of testing and stuff 😂

**Comment by deepu105** [comment]
@DanielFran @mshima do you mind increasing the bounty to 200?
