### ISSUE TITLE
How to enable Swagger within Microservices itself

### ISSUE THREAD

**Issue by xbotuk** [jhipster/generator-jhipster#21228]
I have api-docs Spring profile set for a microservice, however the /v3/api-docs/ returns HTTP 404.

How to enable Swagger within the Microservices itself?

**Comment by mshima** [comment]
The url should be v3 instead of v2. Supposing you are using a not too old jhipster.

**Comment by xbotuk** [comment]
/v3/api-docs/springdocDefault profiles the json output. But what needs to be done to have the actual swagger ui for the microservice?

**Comment by mshima** [comment]
Use the swagger ui from the gateway. It should be possible to use springdoc-openapi-ui dependency.

**Comment by mshima** [comment]
It's not possible out-of-the-box, it should be possible to add springdoc-openapi-ui dependency.

**Comment by xbotuk** [comment]
Added springdoc-openapi-ui dependency, makes no difference

**Comment by mshima** [comment]
Please refer to https://springdoc.org or the related repository. Closing as this is working as expected.
