### ISSUE TITLE
Create a jhipster-blueprint tag on StackOverflow

### ISSUE THREAD

**Issue by timothystone-knsl** [jhipster/generator-jhipster#21245]
##### **Overview of the feature request**

Someone in the community with a 1500+ reputation on SO should create a `jhipster-blueprint` tag.

##### **Motivation for or Use Case**

I see [a few questions](https://stackoverflow.com/questions/tagged/jhipster+blueprint) using `blueprint`, but that's for the Blueprint CSS framework.

##### **Related issues or PR**

External system. No PR. Action to be taken by SO user with reputation. 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by timothystone-knsl** [comment]
@mraible I see you have the rep. 😃  My rep in RPG.SO is high enough, but wrong SO.

**Comment by gmarziou** [comment]
Done.
