### ISSUE TITLE
Add karma tests in Maven lifecycle

### ISSUE THREAD

**Issue by lordlothar99** [jhipster/generator-jhipster#2125]
I find it more convenient when the single `mvn test` command runs both junit and karma tests. This plugin can fix that : https://github.com/karma-runner/maven-karma-plugin

**Comment by jdubois** [comment]
Karma tests are already run when we do the "prod" build, so this is already the case.
At the moment we separate this only in "dev" mode, as it's often two different teams: that way you work on the back end or the front end, but don't have to run their tests until you go to CI or to production.
So for me what we currently have is good enough.
