### ISSUE TITLE
How do I create application with Java17

### ISSUE THREAD

**Issue by venkatnaveen7** [jhipster/generator-jhipster#21297]
Team i would like to create an application with Java17, Spring 6, Spring Boot 3 + React
but the current version 7.9.3 is creating applications with java 11  spring-boot.version=2.7.3

**Comment by mraible** [comment]
See https://github.com/jhipster/generator-jhipster/issues/20849#issuecomment-1451917651.

**Comment by mraible** [comment]
Closing because the issue I linked to describes how to create an app with the latest code in the `main` branch.

**Comment by venkatnaveen7** [comment]
Thanks for the response
