### ISSUE TITLE
Security issue with tracking logged in users with websocket

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2129]
It seems that any authenticated user can listen to the `topic/tracker` and thereby see the user tracking information.

See line 17 websocket security config in [WebsocketSecurityConfiguration.java](https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/java/package/config/_WebsocketSecurityConfiguration.java#L17)

We should configure the tracker topic to only be available for ROLE_ADMIN users with:
```
.simpDestMatchers("/topic/tracker").hasAuthority(AuthoritiesConstants.ADMIN)
```

**Comment by jdubois** [comment]
Yes but I think this isn't working with OAuth2 and JSON token. This is an older issue, can you look in the history?

**Comment by andidev** [comment]
I'll have a look at it. If it does not work with oauth and json token we should still include the security config within an If case authentication type == session.

**Comment by andidev** [comment]
Did not find anything in the history. Though there was a lot of issues to search through. I think I'll try to test it with the other authentication types  instead.

**Comment by jdubois** [comment]
Yes please do test it with the other options, I'm pretty sure they will not work.

-> I didn't put a "authentication type == session" because I wanted to have a consistant behavior, but you are right, it would be better that way. If you have the error with the other authen type, can you add this check? And can you add a comment in the source code to this issue, so we can find again next time?

**Comment by andidev** [comment]
It seems to work with authentication type `session` and `oauth2`. So I will modify my PR to include the authentication config for both  `session` and `oauth2`. And

With `xauth` I get the following authentication error in the console
```
<<< ERROR
message:Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; nested exception is org.springframework.security.access.AccessDeniedException\c Access is denied
content-length:0
```

and from the spring logs
```
[ERROR] org.springframework.web.socket.messaging.StompSubProtocolHandler - Failed to send client message to application via MessageChannel in session myaqtjdp. Sending STOMP ERROR to client.
org.springframework.messaging.MessageDeliveryException: Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; nested exception is org.springframework.security.access.AccessDeniedException: Access is denied
```

so I'll leave xauth as it is.

**Comment by jdubois** [comment]
@andidev yes, anyway we have #2100 to remove XAuth and migrate to JWT
