### ISSUE TITLE
feature request: decouple the security layer of Jhipster

### ISSUE THREAD

**Issue by fernando4530** [jhipster/generator-jhipster#21307]
It would be great to have the ability to decouple the security layer from Jhipster. This could be done from the wizzard command "jhispter" or from the web https://start.jhipster.tech/

There are scenarios where security (authentication and authorization) is delegated to other systems (service mesh for example) and security-related dependencies are not needed in microservices.

**Comment by mraible** [comment]
You might be able to do this with JHipster Lite, but I'm not sure. https://github.com/jhipster/jhipster-lite

**Comment by fernando4530** [comment]
> You might be able to do this with JHipster Lite, but I'm not sure. https://github.com/jhipster/jhipster-lite

Yes, it's a possibility, but we need the rest of the features of the "complete" Jhipster project. Is it known if this feature that I suggest will be on the roadmap of Jhispter v8?

**Comment by mraible** [comment]
> Is it known if this feature that I suggest will be on the roadmap of Jhispter v8?

No, we don't plan to implement this feature. However, if you contribute a pull request that adds the feature, we'll consider it.

**Comment by fernando4530** [comment]
> @fernando4530 By decoupling, do you mean disabling security?
> 
> Could you explain how you would manage RBAC with a service mesh? As far as I know it's done by propagating tokens and so, you would still need security dependencies in your services, right?
> 
> Could you clarify your use case and whether this can be implemented in a generic way? Maybe you could share a git repo of a proof concept project with 2 services.

We will apply RBAC and Service Mesh through Istio https://istio.io/. We also have the possibility of using AWS cloud tools that cover security topics very well (Authentication and authorization).

What we want is that all our microservices only work with the domain applying the BFF pattern for example.
