### ISSUE TITLE
Support REST / APISpark

### ISSUE THREAD

**Issue by templth** [jhipster/generator-jhipster#2133]
Hi all,

As discussed last week with Julien, I created this issue since I would be pleased to contribute an integration with REST providers in JHipster and more particularly regarding APISpark, a platform to create and host Web APIs / RESTful services.

I think that there would be a good match between them and the generator can also lead the creation / update for resources and entities in the platform. APISpark would bring the backend, JHipster the frontend application and the way to interact (with REST principles and HTTP) with it as well. I would see scenarios like this: the commands will create application elements, the way to interact with the backend but also create elements in APISpark. For example, when creating an entity, JHipster would create all elements for screens but also a Web API with the configured structure.

Julien told me that there are two possible approaches: integration directly within the main generator or create a sub generator. He asked me to create an issue to open a discussion around this subject...

Thanks very much by advance for your feedbacks!
Thierry

**Comment by gzsombor** [comment]
It's not clear for me, what is APISpark? Is it a paid service to create web services ? If you can't use it freely, I can't see that many user will use it, and contribute bugfixes / implementations.

**Comment by templth** [comment]
Hi,

Thanks very much for your feedbacks.

APISpark is a platform to create and host easily Web APIs (i.e. RESTful services). The latters can rely on entity storage and / or file storage. The platform handles security, versioning, metrics, documentation, client SDKs for you. There is also supports for languages like Swagger or RAML (import / export).

In fact, everything can be done for free: create REST services, call them, ... Pricing only depends on the concurrent clients you want to handle for your services is taken into account. Up to 10 clients, it's free (see this link for more details).

Hoping to have answered your questions!
Thierry

**Comment by deepu105** [comment]
Im not sure havent heard of API spark, do you have any sample repo which we
can see

**Comment by templth** [comment]
Yes, sure!

I implemented an Angular / D3 application based on APISpark for the backend. This could be a good sample of what can be done with the plateform.

Here are the corresponding links:

* The project page: http://templth.github.io/
* The demo: http://templth.github.io/demo/#/
* The API page in the APISpark console describing the structure of the RESTful service: https://apispark.restlet.com/apis/10896/versions/1/overview
* Some sample calls on the plateform:
  * List of maps: GET https://mapapi.apispark.net/v1/maps/
  * List of layers for a map: GET https://mapapi.apispark.net/v1/layers/?map=1

Feel free to tell me if it's enough for you!
Thierry

**Comment by gzsombor** [comment]
After you implemented your backend with APISpark, is there a way to migrate the application to own hardware, without great effort ? Otherwise, this would be a vendor lock-in, which could be fine for toys, or prototype apps, but I wouldn't start an application, where I can't run the whole stack, on my own.

 Otherwise, it's seems an interesting platform :)

**Comment by templth** [comment]
Thanks for the feedback!

I understand well your point of view. The platform allows you to get the server skeleton for your RESTful service in different technologies (Java Restlet, JAXRS, Node) but you need to connect this to your datastore by hand. You can have a look at the tab "Downloads". You also have access to corresponding Swagger or RAML content, so you'll be able to leverage corresponding generators (like Swagger Codegen, ...).

**Comment by templth** [comment]
My main question at this point is the best way to start. Do I need to create an external project for this integration or to fork the current project to add updates in it?

I'm working on a JavaScript module to "lead" the platform programmatically along with some support for Gulp and Grunt. I mean when you use the generator to create an entity, this module allows you to add it directly in the platform... It's something you should rely on for the REST / APISpark support.

Thanks!

**Comment by verrol** [comment]
I am just throwing in my 2cents.

Disclaimer: I don't much about APISpark. 

But I am sure there are other services like this. This seems like Backend-as-a-Service (BaaS) solution like FireBase for example. Like others on the thread, I am concern that not too many users of JHipster use APISpark. If it was a solution you could deploy on-prem, I would be all for it.

**Comment by templth** [comment]
Hi,

In fact, there are two main things here (perhaps it wasn't so clear):

* REST support in JHipster. This would make possible to plug a RESTful service into the geenrated application. This would handle the CRUD:
  * methods `GET` / `POST` on the list resource for get all / query add an element.
  * methods `GET`, `PUT`, `PATCH` / `DELETE` on the single resource for a particular element.
  * handle relations between resources using hypermedia and links.
  * Security (basic, token-based or oauth2).

* Integration with specific platforms like APISpark to manage structure of RESTful services. In the case of APISpark, for example, when adding an entity from command line, this would be directly added in the platform as well. We could think a bit generic to plug other platforms... because sure, there is other BaaS platform like Firebase, Parse, ...

My 2 cents ;-) Thanks very much for your feedback!
Thierry

**Comment by boutchekkoucht** [comment]
do you have an example of what you say?

**Comment by jdubois** [comment]
Hi @templth , we've made a good progress on doing a "module system" for JHipster: it's not released yet, but this would "normally" be the solution for you.
Would like to be a "beta tester"? Nothing's hidden, we are discussing on the dev mailing list at https://groups.google.com/forum/?hl=en#!forum/jhipster-dev
And have a look at https://groups.google.com/forum/?hl=en#!topic/jhipster-dev/bhpEKIR20SM -> this would be for your!

**Comment by templth** [comment]
Awesome, @jdubois! Exactly what I need ;-) Sure, I'll be a beta tester! I'll keep you up to date with my progress...

**Comment by jdubois** [comment]
@templth I will release the marketplace anytime soon, so I'm closing this -> have a look at the marketplace, and tell us if that's fine for you!!
