### ISSUE TITLE
Why Cascade isn't Defined?

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#21335]
##### **Overview of the feature request**

I notice that Cascade is not given for one-to-one and many-to-one relationships in a JDL file. I need to add the definition to make my code more effective.

##### **Motivation for or Use Case**

An entity has multiple one-to-one and one-to-many relationships (both relationships are defined from the child ends). The data is obtained through a REST API call, but not from the admin UI. To save the data to the local database, I would need to save the parent entity data first and save all child entity data later. That would be a lot of repository method calls when cascade isn't defined. If I have 
```
 @OneToMany(mappedBy = "parent", cascade = CascadeType.ALL)
```
only one repository call is needed.

And I haven't observed any negative impact of the change. I can edit the parent entity data on the admin UI without any issues related to its children.

That lets me wonder why the cascade isn't given in the generator. 

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
https://thorben-janssen.com/avoid-cascadetype-delete-many-assocations/

**Comment by vw98075** [comment]
Thanks for the article. If my memory is correct, the author advised using CascadeType.ALL on StackOverflow. For the many-to-many relationship, I would agree that CascadeType.ALL or CascadeType.DELETE shall be used carefully. For the many-to-one relationship, I don't see any big ideal in terms of deletion, two more select statements for the sample in the article. And you always can delete children individually with the cascade defined.

**Comment by OmarHawk** [comment]
In the next version you'll have the option to cascade DELETE and UPDATEs through corresponding constraints through the liquibase changelog, see #18751
