### ISSUE TITLE
Allow saving/loading AWS configuration

### ISSUE THREAD

**Issue by Vaelyr** [jhipster/generator-jhipster#2135]
How much work would it be to enable storing AWS configuration settings and using them for further deployments. Typing environment, RDS and EC2 details always again is rather tedious.

Maybe it would be more convinient to have it as last option by giving configuration name and then use it to load after :aws 

@wuethrich44 any input?

**Comment by deepu105** [comment]
I guess it should be possible to generate a json and store it in root like
how we do for entities, but this should be generated only of the sub gen is
used

**Comment by Vaelyr** [comment]
Well something like that yes I assume, just would be handy to have different profiles as I wish to deploy to pre-live and production environments.

**Comment by deepu105** [comment]
You can do a PR if you want, try to follow whats done in entity sub gen

**Comment by jdubois** [comment]
The issue with this, is that you will always deploy to the same environment... So if you will need to store several different configs, and we don't have this yet... Maybe we could have a "dev", "test", "prod" pre-defined profiles?
-> if we go this way, we would need to do the same for Heroku (please see with @jkutner ) and OpenShift ( @raphaelbrugier might work on it), so we need to coordinate what we do here

**Comment by wuethrich44** [comment]
@Vaelyr Your request is easy to implement but currently I'm very busy with my studies. I can review and test your PR if you like to provide one.

**Comment by Vaelyr** [comment]
I could look into it when I get more time myself.

As for other environments (Heroku, Openshift) - as all of them have different settings, I assume simple configuration json key for each platform would be just enough with simple documentation provided. Allow user to define the configuration as they please, and when deploying without profile, then ask if you want to save it for further use by giving it name as well.

**Comment by raphaelbrugier** [comment]
As discussed with @jdubois I've started to work on OpenShift, but that's a different problem. 
I'll create a separate issue for it.
If you improve the configuration management for AWS, I'll adapt OpenShift

**Comment by deepu105** [comment]
Is anyone working on this? If not im closing it later

**Comment by Vaelyr** [comment]
I have a working solution that I am using. Will try to do PR on first free moment.

**Comment by deepu105** [comment]
checkout the store property of the promt mechanism in yeoman, that should be a quick solution

**Comment by wuethrich44** [comment]
I will provide a PR in the next few days. So you can leave this open.

**Comment by wuethrich44** [comment]
@deepu105 I think you can close this

**Comment by jdubois** [comment]
@wuethrich44 I don't understand, is this already merged? I don't see the link to your PR

**Comment by cbornet** [comment]
I think it's #2679

**Comment by jdubois** [comment]
OK, thanks!!
