### ISSUE TITLE
Could we add mybatis as an option for choosing the orm framework when we generate the code?

### ISSUE THREAD

**Issue by robin536180** [jhipster/generator-jhipster#21350]
Somebody like spring data jpa，and someone like mybatis，and I think whether give an option to choose orm framework is an good idea or not.

I like to use mybatis，so I want to change the jpa to mybatis.

**Comment by atomfrede** [comment]
This would be a good candidate for a blueprint. I don't think we can maintain it in the main generator as we have already so many options.

**Comment by robin536180** [comment]
Thanks for replying. So how can I add this feature as a blueprint? Could you please give some sugguestion? Is there some guideline on this kind of jobs? Thanks a lot.
