### ISSUE TITLE
Jhipster /managing-relationships/ page not up to date

### ISSUE THREAD

**Issue by mb-undairstand** [jhipster/generator-jhipster#21358]
##### **Overview of the issue**

I have start a basic monolithic app and try to create a many to many relationship between two entities. If i follow the basic page of Jhipster https://www.jhipster.tech/managing-relationships/ for manytomany relationship, there will be error.

##### **Motivation for or Use Case**

Try to have a simple many to many relationship between two entities.

##### **Reproduce the error**

Follow https://www.jhipster.tech/managing-relationships/ ManyToMany section. To create a relation.

##### **Related issues**

Don't know

##### **Suggest a Fix**

I was able to bypass the issue by running differently the command. 
Which is not following the doc page but first generating both entity without relationship. And then only run the command jhipster entity name_entity for the owner of the ManyToMany relation. I guess it should not be run in the non-owner entity because it's cause issue.

##### **JHipster Version(s)**

Latest (7.9.3)

##### **JHipster configuration**

Probably not needed.

**Comment by mraible** [comment]
@mb-undairstand Can you please create a PR in https://github.com/jhipster/jhipster.github.io to fix this?
