### ISSUE TITLE
`NoSuchTypeException` stack trace is printed when the tests are executed

### ISSUE THREAD

**Issue by frascu** [jhipster/generator-jhipster#21359]
As described in this issue https://github.com/reactor/reactor-core/pull/3337, a stack trace is printed during test execution.

This has been fixed using the suggestion of this comment: https://github.com/reactor/BlockHound/issues/311#issuecomment-1370801477.
Therefore, the following dependency has been added:
```xml
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>context-propagation</artifactId>
    <version>1.0.0</version>
</dependency>
```
As suggested by @mraible [here](https://github.com/jhipster/generator-jhipster/pull/21041/files/235bf164ab0658ad50e5a184505b4cc649c4a0f6#r1130049576), I opened this issue in order to remove the dependency when the issue is fixed in the reactor core dependency.

**Comment by mshima** [comment]
Should be fixed by https://github.com/reactor/reactor-core/releases/tag/v3.5.3
