### ISSUE TITLE
JDL import error

### ISSUE THREAD

**Issue by ozzie786** [jhipster/generator-jhipster#21387]
D:\bmapp>jhipster jdl bmjdl.jdl  with/without  --force-no-filtering
INFO! Switching to JHipster installed locally in current project's node repository (node_modules)
INFO! Using bundled JHipster
node:internal/modules/cjs/loader:571
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in C:\Program Files\nodejs\node_modules\generator-jhipster\node_modules\yeoman-environment\package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\generator-jhipster\utils\blueprint.js:19:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.15.0

**Comment by ozzie786** [comment]
> C:\Program Files\nodejs\node_modules\generator-jhipster\node_modules\yeoman-environment\package.json

this error on "npm install"

D:\bmapp>npm install

> business-manager-app@0.0.1-SNAPSHOT prepare
> husky install

fatal: not a git repository (or any of the parent directories): .git

removed 1 package, and audited 1932 packages in 22s

215 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

**Comment by ozzie786** [comment]
deleted old node_modules folder then re "npm install", 
D:\bmapp>npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> business-manager-app@0.0.1-SNAPSHOT prepare
> husky install

fatal: not a git repository (or any of the parent directories): .git

added 1930 packages, and audited 1931 packages in 9m

215 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

**Comment by gmarziou** [comment]
JHipster does not work with node 18.15.0 and few other versions (see #21380), please downgrade to 18.13.0
