### ISSUE TITLE
Bad request header not displaying

### ISSUE THREAD

**Issue by maheshkaranjkar** [jhipster/generator-jhipster#2139]
Hi Guys,

I tried to use bad request header to check unique validation, which we can not check using @valid.

but in dialog.html its just showing red box without message body

<code>
List<Language> lg = languageRepository.findByLanguageName(languageDTO.getLanguage_name());
       if(lg.size()>0){
    	   return ResponseEntity.badRequest().header("Failure", "language name already exists").body(null);
       }
</code>  
![header_issue](https://cloud.githubusercontent.com/assets/10084323/10450749/f63424c6-71b9-11e5-9e40-48bba0854ae4.jpg)

Regards
Mahesh

**Comment by jdubois** [comment]
Please follow the guidelines and tell us how to reproduce your issue. I don't understand what this "bad request header" is doing.

**Comment by maheshkaranjkar** [comment]
Sure @jdubois, we are trying to put validation for unique Language name in our system.

For that we tried to use same logic which is used to do validation for ID new language.

However we are able to restrict user from creating new language.

we request hits at rest-controller after validating DTO, We are trying to check name for uniqueness. 

But response is not getting displayed at front end.

To verify if there is any mistake in my code, I pass ID for new request to check validation for it its getting displayed or not. In this scenario also pop up doesn't showed up any message.
 


Regards
Mahesh

**Comment by jdubois** [comment]
I'm sorry but I don't understand why this would be a JHipster bug.

This is the ticket system for JHipster, can you post your question on StackOverflow instead?
