### ISSUE TITLE
Migration to Java Date Time API

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2140]
I just merged the migration from Java Date Time API at: https://github.com/jhipster/generator-jhipster/commit/b102b1c3c3c0ce5c06e497fba95acf7f6e7eef45

There are still a few issues left:

- There is a JS error when an entity having a DateTime is saved or updated, `Error: [ngModel:datefmt] Expected 2015-12-17 to be a date`
- I didn't test MongoDB and Cassandra (only basic compilation of a project with no entity)
- The performance tests with Gatling should also be tested

**Comment by cbornet** [comment]
Is there a reason why PersistentAuditEvent::auditEventDate is a LocalDateTime and not a ZonedDateTime ?

**Comment by cbornet** [comment]
The format used for ZonedDateTime is ISO_ZONED_DATE_TIME which ouputs 2011-12-03T10:15:30+01:00[Europe/Paris]. I think this format is not compatible with AngularJS...

**Comment by cbornet** [comment]
I will fix this and other things in a PR that will remove jadira and the json annotations.

**Comment by deepu105** [comment]
+1 plz do this PR was long back and hence can be improved a lot

**Comment by cbornet** [comment]
FYI other issues I am facing:  
* we cannot log anymore on mongodb because of an exception in auditing. I have fixed that in my WIP.
* the mongodb tests don't run anymore. Linked to spring boot 1.3 migration ? (java.lang.NoClassDefFoundError: de/flapdoodle/embed/mongo/config/ExtractedArtifactStoreBuilder)

**Comment by jdubois** [comment]
@cbornet Yes I have the same issue with MongoDB, I guess there's a new auto-configuration that we should disable.

**Comment by pascalgrimaud** [comment]
What about migration for existing project ? In .jhipster/*.json : "DateTime" -> "ZonedDateTime" ?
Maybe you'll have to update all you sample-app

**Comment by cbornet** [comment]
@jdubois mabe this one ? https://github.com/spring-projects/spring-boot/commit/2c81907d588690bb623745c95f577a0c60a156f5

**Comment by cbornet** [comment]
Definitely a problem with auto-configuration : I removed MongoConfiguration.java and embedmongo-spring dependency and it tests work again.

**Comment by cbornet** [comment]
@pascalgrimaud It seems existing DateTime fields are mapped to ZonedDateTime when generated

**Comment by jdubois** [comment]
The only issue left is tracked by #2173
