### ISSUE TITLE
How can i create Java17+React application ?

### ISSUE THREAD

**Issue by venkatnaveen7** [jhipster/generator-jhipster#21462]
How can i create a Java17+React application?
I pulled code from the main branch and did the npm link and created the application
it was created with angular by default and no questions were asked

**Comment by atomfrede** [comment]
Did you executed the jhipster command in the repository folder by accident?

**Comment by venkatnaveen7** [comment]
No..created an empty folder and executed jhipster

**Comment by wangxinxx** [comment]
The main branch has such a problem.
