### ISSUE TITLE
jhipster 500 connection error but I can sign in but I can't see entities

### ISSUE THREAD

**Issue by aymanqabbal** [jhipster/generator-jhipster#21469]
JHipster v7.9.3 

##### **JHipster configuration**

it's using a jdl, the jdl was imported before pushing and cloning the project repo, but i ran the jdl generator again and it added 0 applications
##### **Browsers and Operating System**
operagx windows 10

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Can you share your jdl and which commands you are executing to generate the application?
