### ISSUE TITLE
Generate an Eclipse .setup file

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2147]
I have no idea how this works, but this looks really cool: https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-the-eclipse-installer

**Comment by deepu105** [comment]
Is it worth doing if its only for eclipse?

**Comment by jdubois** [comment]
@deepu105 I think most people are using Eclipse, considering the price of Intellij.

**Comment by jdubois** [comment]
OK, this is one of those horrible setup files from Eclipse:
https://github.com/spring-projects/spring-boot/tree/master/eclipse

I've already tried to do that in the past, that's really complex and buggy... So I'm just not doing it!
