### ISSUE TITLE
Custom table name

### ISSUE THREAD

**Issue by farajfarook** [jhipster/generator-jhipster#2149]
I would really appreciate if jhipster can take custom table name for an entity, which a user can 
 - Interactively enter while adding the entity
 - Store it in the .jipster json file and reuse it on regeneration
 - Support in JDL to use with jhipster-uml. 

*I read some issues and goto know that jhipster project has purposely removed the prefix. But the feature which i'm mentioning will give the developers more flexibility if they like to have it. If not, they can simply skip it and stick to the default method.*

**Possibility of contribution**

I can do the code level development on this feature and create a pull request. But I need to know if such implementation is done (under good coding standards), then will it go inline with the project future targets and will it be approved for the master merge.

**Comment by deepu105** [comment]
I think it is good to have option to enter a custom table name, it can have the generated name shown by default and user can override if required. I guess would be nice to have but it adds another layer of option on the already complex generator. @jdubois what do you think? I guess we discussed this long back in a thread if im not wrong

**Comment by jdubois** [comment]
No I don't want to have too many questions, it's already too complicated.

Changing the generated table name, if it doesn't suits you, is really easy, you change it in the entity (and maybe also in Liquibase, depending on how you work), so there's really no added value in asking that question.

**Comment by farajfarook** [comment]
:+1:

**Comment by farajfarook** [comment]
@jdubois Then what about **only** putting an option in the `.hipster` `json` file which will be empty by default and if so take the value from the entity name. 
```javascript
 }
      ...
      "tableName": "app_entity_tab",
      "changelogDate": "20151014174836",
      "dto": "no",
       ...
}
```
<hr/>
**Impact**

End of the day this will not effect any existing flow of jhipster interactive shell. In other words it will not increase or decrease the complexity.
<hr/>
**Why I'm so interested in this feature?**

I believe in the project **jhipster-uml** and **JDL**. Seems absolutely promising. This will enable the JDL to have an option of defining the table name. 

If you still think this is not a feature this project should have. Then I will bid my farewell to this issue.

**Comment by AVE-cesar** [comment]
+1 because, it will be a first step towards reverse engineering of existing database model.

**Comment by deepu105** [comment]
+1 im ok to have it only in the JSON

**Comment by deepu105** [comment]
linked to https://github.com/jhipster/generator-jhipster/issues/2558 this can be tracked there
