### ISSUE TITLE
From address must not be null

### ISSUE THREAD

**Issue by Panthro** [jhipster/generator-jhipster#2151]
#1462 is back from the dead

MailService.java
```
@PostConstruct
    public void init() {
        this.from = env.getProperty("mail.from");
    }

```

but the property is jhipster.mail.from

![image](https://cloud.githubusercontent.com/assets/1565421/10510765/2eeca9ce-7335-11e5-9c48-acb0372bc495.png)

https://github.com/jhipster/generator-jhipster/issues/1462

**Comment by jdubois** [comment]
This will disappear in the next release, so consider it done already!

This is because we migrate to Spring Boot 1.3, which has auto-configuration for emails -> so this will be Spring Boot's fault from now on :-)

**Comment by Panthro** [comment]
👍 thanks for the feedback.
