### ISSUE TITLE
can't install new languages on windows 10 machine, keyboard inputs just not listening.

### ISSUE THREAD

**Issue by MardariG** [jhipster/generator-jhipster#2153]
I'm using Release 2.22.0. After creating a new project, when i try to install new language my console is not responding. Maybe this is hardware specific issue i don't now, maybe someone can confirm.

**Comment by jdubois** [comment]
I can't test it as I don't own a Windows machine, this might be linked to your Node version -> which version are you using?

**Comment by MardariG** [comment]
Node version 2.14.4

**Comment by jdubois** [comment]
I don't think this version exists... Can you do `node --version`?

**Comment by MardariG** [comment]
my bad, i've checked with npm instead. Node version - 4.1.1;  I'll update to latest and try again.

**Comment by MardariG** [comment]
after update problem persist, Node version - 4.2.1

**Comment by Brokando** [comment]
+1 Node-Version: 4.2.1

**Comment by jdubois** [comment]
As there is just a list of languages to choose from, can you explain in detail what you are doing, and what is not working?
I just tried it on my Mac and I can select languages, so this might be Windows-specific, but I need to reproduce exactly what you do.

**Comment by MardariG** [comment]
After running command: **yo jhipster:languages**  the following content appear 
![terminal](https://cloud.githubusercontent.com/assets/8759158/10573127/63475f42-7656-11e5-8738-f99efaae4b70.png)
And at this step i can't move up or down.

**Comment by Brokando** [comment]
And if you click enter, it is installing catalan without click on space

**Comment by jdubois** [comment]
This is probably a Yeoman issue, and it should be Windows-specific (as I don't have the issue).
This is going to be really annoying to test (as a Windows machine is needed).

**Comment by Brokando** [comment]
But in other tasks, like jhipster:entity, it's still working without problems

**Comment by jdubois** [comment]
Correct, and I don't understand where the difference is... Still I'm upgrading "yo" to its latest version, just in case.

**Comment by Brokando** [comment]
ok cool :) thanks for your help.
Do you know, when you will publish the next jhipster version? 
Or should i try it with the actual master?

**Comment by jdubois** [comment]
Not sure for the next version, it's going to be huge, so a lot of test is needed.
Yes you can try from the master, have a look at the "contributing" document, it will guide you (and it's not that difficult, in fact)

**Comment by Brokando** [comment]
does not work with actual yeoman version.

But as described  here:
https://github.com/yeoman/yo/issues/360
Its a node problem, as described here:
https://github.com/nodejs/node/issues/2996

**Comment by gmarziou** [comment]
There are currently issues with NodeJS 4+ and npm 3 on Windows, until Node team fixes them, it's highly recommended to use Node 0.12.x

**Comment by jdubois** [comment]
OK, so this is a NodeJS issue -> yes you need to use 0.12 versions, the other are very new and can lead to problems

**Comment by Brokando** [comment]
with node v0.12.7 its working :)

**Comment by KevinLange** [comment]
With the current stable v5.3.0 this problem seems to be solved.

**Comment by gmarziou** [comment]
We highly recommend not using stable releases, you'd better use LTS (Long Term Support) releases which are more ... stable ;)
