### ISSUE TITLE
Convert vue to composition api.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#21547]
##### **Overview of the feature request**

vue-class-component and vue-property-decorator won't be updated with vue3 support.
If we want to migrate to vue3, we need to reimplement vue ui using [composition api](https://vuejs.org/guide/extras/composition-api-faq.html#what-is-composition-api) which is supported by vue 2.7 and vue 3.

The goal of this issue is to drop vue-class-component and vue-property-decorator and use composition api.
This means we need to reimplement every vue file using composition api replacing the class and property implementation.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran @mraible would be nice to add a bounty, to much work here.

**Comment by mraible** [comment]
@mshima Would you like me to work on this one or up the bounty?

**Comment by mshima** [comment]
@mraible your call, if you want to work on this I can organize the work I've done and create a branch. I can continue if the bounty is increased too.

**Comment by mshima** [comment]
IMO vue 3 is not a requirement for an alpha release.

**Comment by mraible** [comment]
@mshima OK. Can you please create issues to track an alpha, beta, and GA release so everyone can see what needs to be done?

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/140218.

**Comment by DanielFran** [comment]
@mshima approved
