### ISSUE TITLE
Moving the content ui-view

### ISSUE THREAD

**Issue by Jdruwe** [jhipster/generator-jhipster#2154]
Hey there!

First of all I would like to thank the developers for creating this amazing framework! I have been looking into the front end frameworks that exists apart from bootstrap and found [Angular Material](https://material.angularjs.org/latest/demo/whiteframe). I know that this might not be the best place to ask this type of question but I would greatly appreciate any help.

I am trying to move the **ui-view="content"** div into the navbar view but I am failing to do so

index.html (content ui-view is removed):

```html
<div ui-view="navbar" ng-cloak=""></div>

<div class="container">
    <div class="footer">
        <p translate="footer">This is your footer</p>
    </div>
</div>
```

The navbar view links to a 'material' template

```javascript
$stateProvider.state('site', {
            'abstract': true,
            views: {
                'navbar@': {
                    templateUrl: 'scripts/components/navbar/material.html',
                    controller: 'NavbarController'
                }
            },
            resolve: {
                authorize: ['Auth',
                    function (Auth) {
                        return Auth.authorize();
                    }
                ],
                translatePartialLoader: ['$translate', '$translatePartialLoader', function ($translate, $translatePartialLoader) {
                    $translatePartialLoader.addPart('global');
                }]
            }
        });
```

Material template:

```html
<md-content layout="column" flex class="md-padding">
    <div class="well" ui-view="content"></div>
</md-content>
```

When the page gets rendered the content is not shown, I really have no idea how to make this work.

**Comment by jdubois** [comment]
Hi, I'm sorry but please have a look at our guidelines -> this is the place for the bugs, in this is not a bug.
Can you use StackOverflow with the JHipster tag?
