### ISSUE TITLE
[jdl] cleanup jdl support.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#21555]
##### **Overview of the feature request**

Implement jdl generator with blueprint support:
- move file manipulation to jdl generator.
- move configuration merge to jdl generator.
- move validation to the related generator.
- return application configuration exactly as defined in the jdl file (don't apply default config).

##### **Motivation for or Use Case**

Those tasks are already been done at generator level, it's duplicated at jdl.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/177002.

**Comment by DanielFran** [comment]
@mshima approved
