### ISSUE TITLE
What is appendSkipBower for?

### ISSUE THREAD

**Issue by trevershick** [jhipster/generator-jhipster#2156]
The following is generated in Gruntfile.js, but I cannot seem to find where this is used. 

	grunt.registerTask('appendSkipBower', 'Force skip of bower for Gradle', function () {

		if (!grunt.file.exists(filepath)) {
			// Assume this is a maven project
			return true;
		}

		var fileContent = grunt.file.read(filepath);
		var skipBowerIndex = fileContent.indexOf('skipBower=true');
		if (skipBowerIndex !== -1) {
			return true;
		}
		grunt.file.write(filepath, fileContent + '\nskipBower=true\n');
	});

I ask because I'm removing all the jshint errors from the project and 'filepath' is undefined.  I cannot figure out why this is here.

    {
      "generator-jhipster": {
        "baseName": "jhipster",
        "packageName": "com.mycompany.myapp",
        "packageFolder": "com/mycompany/myapp",
        "authenticationType": "session",
        "hibernateCache": "ehcache",
        "clusteredHttpSession": "no",
        "websocket": "no",
        "databaseType": "sql",
        "devDatabaseType": "h2Memory",
        "prodDatabaseType": "mysql",
        "searchEngine": "no",
        "useSass": false,
        "buildTool": "maven",
        "frontendBuilder": "grunt",
        "enableTranslation": true,
        "rememberMeKey": "7ddf09b45859f999244aba245ca23515cdcb1b00"
      }
    }

**Comment by andidev** [comment]
By the description of the task it looks like it should only be there when using Gradle and not maven as in your case.

This was added in commit [Added support for Heroku + Gradle + PostGreSQL](https://github.com/jhipster/generator-jhipster/commit/5bb2d6041d4dde18b6d0754df194f3dd00db2995)

I'm removing this for maven users.

**Comment by andidev** [comment]
The call of this task seems to be removed. It was called in the `buildHeroku` and `deployHeroku` tasks in the initial commit when it was added.

I'm not sure what the purpose of this is.

@trevorackerman
Trevor, you did this commit initially. Have we removed something here that is needed? Can we remove this code? It does not seem to be used.

**Comment by andidev** [comment]
Okey, I'm removing it from Gruntfile since the related code was removed in this commit [Reworked the Heroku generator to use Git deployment](https://github.com/jhipster/generator-jhipster/commit/d3f0487df76b4face71545fa5c834bedeeeb81a5#diff-8b50ebbf3a510307ebab0715e7d7aec4).
It must have been a mistake that it was not removed.
