### ISSUE TITLE
Page title is not translated after changing locale

### ISSUE THREAD

**Issue by konstiak** [jhipster/generator-jhipster#2161]
Page title (html > head > title) is set only when the page is (re)loaded. After changing the locale title is not translated.

**Motivation:** For single page web application it is required to translate title after changing the language without reloading the page.

**JHipster Version:** 2.21.1

**Reproduce the error**
1. Generate app with angular-translation support
2. Set different values for different languages to global.title
3. Run the application and change the language.
4. Page title is not translated.

**Comment by gmarziou** [comment]
Please read our [contribution guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) about how to report an issue with required details

**Comment by jdubois** [comment]
I confirm the issue.

It's quite minor, and it looks a bit complicated to solve, as the title is not in the HTML template!

**Comment by konstiak** [comment]
@gmarziou I'm sorry, next time I'll do it regarding the guidelines. I added some more information to my first message. Is it enough?
