### ISSUE TITLE
Can Semgrep sponsor your project? 

### ISSUE THREAD

**Issue by rajaraodv** [jhipster/generator-jhipster#21622]
Hi there,
My name is [Raja Rao](https://www.linkedin.com/in/rajaraodv/) and I work for OSS [Semgrep](https://pages.r2c.dev/ODI1LVFRWi04OTYAAAGKyHTczf0ZiC1PDpjG7UDQqPjzqEEszor5GmHQTgSUOz1Jcx5Y1_hqm-zdyHs_V_OEFO4aD9u9x7WghI4=) project and work at the [company](https://pages.r2c.dev/ODI1LVFRWi04OTYAAAGKyHTczXjU610ByfsHYqxfKGCP95scvuF5klLQ1E4AuiOf_-boPVIqLrZQPwfQvJMnz2gl2d38lTXaxaw=) by the same name that builds application security products. I'm a big believer in open source and I'm impressed with the work you're doing on generator-jhipster.

Semgrep is used by hundreds of thousands of developers at companies like Gitlab, Snowflake, Slack and many others.

At Semgrep, we're on a mission to build developer tools that have positive security side-effects. To that end, we're launching a program to partner with top OSS projects like yours.

We have two main tools that may interest you:

- Semgrep Code is like a code linter, but instead of checking for syntax errors, it scans for security vulnerabilities. And it's [easy to write rules](https://pages.r2c.dev/ODI1LVFRWi04OTYAAAGKyHTczanz9una9HdhRAWNr4mOF-DxZ61QucnCrtBRMYU2hFqRkX1cx8NcXmpT8lny9PaQFVsAKE85crY=) that look for things that are unique to your project.
- Semgrep Supply Chain is similar to Dependabot or npm audit, but with an added bonus: it only flags vulnerable dependencies that are actually being used by your code, so you don't get bogged down with false positives and unnecessary upgrades.

## The Program:
These products together usually sell for $80 /month /developer. For a project with 100 contributors, that would cost $96,000 per year. But I'd like to support OSS software security efforts by offering them for free to you.

Our request is that if you do try Semgrep and find it valuable, we'd love for you to add a badge to your GitHub repo (optional but recommended to visually see if your project is secure). 

Adding Semgrep takes under a minute: [Sign up to Semgrep cloud](https://semgrep.dev/login), Go to Projects > New Project > Scan New Project > Run scan in CI and add your projects.

Regards,
Raja

**Comment by mraible** [comment]
Hello @rajaraodv,

Is it possible for you to set up this repo as a test in Semgrep cloud and share the results with us?
