### ISSUE TITLE
Bug in generated file: src/main/resources/config/application-dev.yml with Oracle

### ISSUE THREAD

**Issue by AVE-cesar** [jhipster/generator-jhipster#2162]
I generated my app with JHipster latest version today and I find a bug in file  src/main/resources/config/application-dev.yml (this is the same for src/main/resources/config/application-prod.yml).

this is my .yo-rc.json file (should be nice to have generator-jhipster version inside this file):  I am using Oracle.
{
  "generator-jhipster": {
    "baseName": "MyApp",
    "packageName": "ave.bertrand",
    "packageFolder": "ave/bertrand",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "d93add8421c42ed431626375a4e84d1698c12378"
  }
}

In the generated file, there is a variable that is used twice.
You've got this error:
Exception in thread "main" while parsing MappingNode
 in 'reader', line 17, column 9:
            driver-class-name: oracle.jdbc.O ... 
            ^
duplicate key: driver-class-name
 in 'reader', line 23, column 5:
        jpa:

In order to start your application, you have to put in comment the first line: 
driver-class-name: oracle.jdbc.OracleDriver. 

regards,

bertrand

**Comment by andidev** [comment]
I guess we should remove this if case
https://github.com/jhipster/generator-jhipster/blob/c75d18577a8f486cbf8b8826f12f7f35907425cb/app/templates/src/main/resources/config/_application-dev.yml#L23

**Comment by deepu105** [comment]
Ill push a fix

**Comment by deepu105** [comment]
@AVE-cesar can you check with the latest repo code or just remove the `driver-class-name: oracle.jdbc.pool.OracleDataSource` line from the .yml files and try

**Comment by deepu105** [comment]
@AVE-cesar sorry you need to remove the line `driver-class-name: oracle.jdbc.OracleDriver`

**Comment by AVE-cesar** [comment]
it works, thanks
