### ISSUE TITLE
Camelcase broken

### ISSUE THREAD

**Issue by markvgo** [jhipster/generator-jhipster#2163]
I have the latest version of jHipster, when I generate a class that has a relationship with camelcase I lose the capitals. See Set'<'Bankreconciliation'>', Bankreconciliation should be an upper case 'R'.

@OneToMany(mappedBy = "bankAccount")
@JsonIgnore
private Set'<'Bankreconciliation'>' bankReconciliations = new HashSet<>

**Comment by andidev** [comment]
This is probably a jhipster url issue. Are you using jhipster uml? Please always provide the entity.json file located in the .jhipster folder.

**Comment by markvgo** [comment]
Hello Anders 

You are right, it is an  jhipster-uml issue
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "bankreconciliation",
      "relationshipFieldName": "bankReconciliation",
      "otherEntityName": "bankreconciliation",
      "relationshipType": "one-to-many",
      "otherEntityRelationshipName": "bankAccount"
    }
  ],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "description",
      "fieldType": "String"
    },
    {
      "fieldId": 2,
      "fieldName": "accountNumber",
      "fieldType": "String"
    },
    {
      "fieldId": 3,
      "fieldName": "opening",
      "fieldType": "BigDecimal"
    },
    {
      "fieldId": 4,
      "fieldName": "balance",
      "fieldType": "BigDecimal"
    },
    {
      "fieldId": 5,
      "fieldName": "bankOpening",
      "fieldType": "BigDecimal"
    },
    {
      "fieldId": 6,
      "fieldName": "bankBalance",
      "fieldType": "BigDecimal"
    }
  ],
  "changelogDate": "20151018024450",
  "dto": "no",
  "pagination": "no",
  "fieldsContainBigDecimal": true
}

**Comment by jdubois** [comment]
OK, so I'm closing this here, can you add this ticket on the JHipster UML project at https://github.com/jhipster/jhipster-uml ?
cc @MathieuAA
