### ISSUE TITLE
scale Jhipster gateway (stateful) to more than 1 instance

### ISSUE THREAD

**Issue by fabioportieri** [jhipster/generator-jhipster#21646]
##### **Overview of the feature request**

Make the jhipster stateful gateway scalable

When i generate the gateway with the keycloack stateful option, i am under the impression that the gateway is not scalable since the session is used (correct me if i'm wrong), meaning that if i deploy 2+ instances of the gateway an user that is authenticated on instance A and is forwarded on instance B would receive an authentication error

Is there a preferred way to handle this scenario, with sticky sessions perhaps? Any pointers will be appreciated

**Comment by mraible** [comment]
You can use Spring Session + Redis. See [Scaling Secure Applications with Spring Session and Redis](https://developer.okta.com/blog/2020/12/14/spring-session-redis) for more information.

**Comment by fabioportieri** [comment]
thank you very much, i got at the same conclusion, and the link is very helpful

**Comment by mshima** [comment]
- Generated application with jwt is stateless.
- Generated application with oauth2 is stateful but backend supports stateless, see ionic (stateless) integration test which uses jhipster generated backend:
https://github.com/jhipster/generator-jhipster-ionic/actions/runs/4563394095/jobs/8057611031

If there is interest in oauth2 stateless frontend, jwt implementation can be used as source of inspiration and ionic blueprint too.

**Comment by mshima** [comment]
- Generated application with jwt is stateless.
- Generated application with oauth2 is stateful but backend supports stateless, see ionic (stateless) integration test which uses jhipster generated backend:
https://github.com/jhipster/generator-jhipster-ionic/actions/runs/4563394095/jobs/8057611031

If there is interest in oauth2 stateless frontend, jwt implementation can be used as source of inspiration and ionic blueprint too.

**Comment by mshima** [comment]
The question is answered. Closing.
Next time please use stackoverflow for questions.
