### ISSUE TITLE
Join Kafka and pulsar generators into spring-cloud-binder generator.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#21653]
##### **Overview of the feature request**

Implementations should be compatible.

##### **Related issues or PR**

Related to https://github.com/jhipster/generator-jhipster/pull/21563

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
<3

**Comment by mshima** [comment]
Fixed in https://github.com/jhipster/generator-jhipster/pull/22233.
