### ISSUE TITLE
Make use of sub field rather than preferred_username for user identification

### ISSUE THREAD

**Issue by OmarHawk** [jhipster/generator-jhipster#21675]
##### **Overview of the feature request**

At the moment, it seems the field `preferred_username` from an OAuth2 (OIDC) Token is the identifier for a User coming from an IdP:

Retrieve value from token - login = preferred_username
https://github.com/jhipster/generator-jhipster/blob/e087adbee7e6707505dbc40974bc3019584451fb/generators/server/templates/src/main/java/package/service/UserService.java.ejs#L1027-L1046

Create/Update User uses login and no "sub" + "iss" field
https://github.com/jhipster/generator-jhipster/blob/e087adbee7e6707505dbc40974bc3019584451fb/generators/server/templates/src/main/java/package/service/UserService.java.ejs#L947-L971

Principal extraction uses preferred_username
https://github.com/jhipster/generator-jhipster/blob/e087adbee7e6707505dbc40974bc3019584451fb/generators/server/templates/src/main/java/package/security/SecurityUtils.java.ejs#L97-L105

Updating a user goes via login
https://github.com/jhipster/generator-jhipster/blob/e087adbee7e6707505dbc40974bc3019584451fb/generators/server/templates/src/main/java/package/service/UserService.java.ejs#L620-L622

Instead, we should rather use iss + sub to have a stable identifier used in various places for identifying a user, as the same preferred_username value could be used by different users...

##### **Motivation for or Use Case**
According to (OIDC) Specs, it should rather be iss + sub to perform this kind of identification. 

https://openid.net/specs/openid-connect-core-1_0.html#ClaimStability 

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
We feel that email is a unique enough identifier, which is what comes across in the `preferred_username` field. If you'd like to create a PR that fixes this issue, I'd be happy to take a look at it and test it out.

**Comment by mraible** [comment]
Closing due to lack of response.
