### ISSUE TITLE
Generating an Entity with a blob field breaks Faker.js data generation

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#21704]
##### **Overview of the issue**
When an entity is generated, a CSV file is generated to inject fake data for development purposes.
If the entity contains at least one field that is a Blob (image or text) no fake data is present in the CSV.

##### **Motivation for or Use Case**
Whatever the fields are defined for a given entity, the fake data should not be empty unless it has been explicitly defined.

##### **Reproduce the error**
Generate a JHipster, then add an entity, and define at least one field that is a blob.

Here is a sample app that reproduce this behavior: https://github.com/avdev4j/bugJHiEntity

##### **JHipster Version(s)**
7.9.3

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
  <details>
  <summary>Entity configuration</summary>
  <pre>
     {
  "changelogDate": "20230404193607",
  "clientRootFolder": "bugjhient",
  "databaseType": "sql",
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    },
    {
      "fieldName": "attachment",
      "fieldType": "byte[]",
      "fieldTypeBlobContent": "image"
    }
  ],
  "microserviceName": "bugjhient",
  "name": "Conference",
  "pagination": "no",
  "readOnly": false,
  "relationships": [],
  "service": "no"
}
  </pre>
  </details>

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Ebsan** [comment]
Similar to #19940. This was due to the liquibase version being used and is supposed to be fixed in the next release of Jhipster.

**Comment by qmonmert** [comment]
@DanielFran you can close it, fake data is present now for Blob
![image](https://github.com/jhipster/generator-jhipster/assets/9989211/ca023e5f-5e65-4366-9ae0-086aff42d2e2)
![image](https://github.com/jhipster/generator-jhipster/assets/9989211/5d8e8b5d-a7e8-400d-b756-dde411325dc9)
