### ISSUE TITLE
PostgreSqlTestContainer is not compiling with H2Dev databse 

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#21701]
##### **Overview of the issue**
Generating an application with H2 as a dev database and Postgresql as a prod database generates a test class named "PostgreSqlTestContainer" that is not compiling.
The import `import org.testcontainers.containers.PostgreSQLContainer;` is not found.

##### **Motivation for or Use Case**
The application should compile ;D

##### **Reproduce the error**
Generate the app with the following .yo-rc and run the tests.

##### **Related issues**
N/A

##### **Suggest a Fix**
I don't know if that test should be present or not. So, we have two solutions:
* Add the right dependency in the Pom.xml. Currently, the dependency is only added if the DB is SQL type and the dev database is not h2. https://github.com/jhipster/generator-jhipster/blob/v7.9.3/generators/server/templates/pom.xml.ejs#L1649
```
<%_ if (databaseTypeSql) { _%>
                <dependency>
                    <groupId>org.testcontainers</groupId>
  <%_ if (prodDatabaseTypeMysql) { _%>
                    <artifactId>mysql</artifactId>
  <%_ } else if (prodDatabaseTypeMariadb) { _%>
                    <artifactId>mariadb</artifactId>
  <%_ } else if (prodDatabaseTypePostgres) { _%>
                    <artifactId>postgresql</artifactId>
  <%_ } else if (prodDatabaseTypeMssql) { _%>
                    <artifactId>mssqlserver</artifactId>
  <%_ } else if (prodDatabaseTypeOracle) { _%>
                    <artifactId>oracle-xe</artifactId>
  <%_ } _%>
```
* Or, ensure the file is not generated for that scenario https://github.com/jhipster/generator-jhipster/blob/v7.9.3/generators/server/files-sql.js#L227
```
  addSectionsCondition(postgresFiles, context => (context.devDatabaseTypePostgres || context.prodDatabaseTypePostgres) && !context.devDatabaseTypeH2Any)
```

##### **JHipster Version(s)**
7.9.3

##### **JHipster configuration**

  <details>
  <summary>yo-rc.json</summary>
  <pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "authenticationType": "oauth2",
    "baseName": "testjhi",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "hazelcast",
    "clientFramework": "no",
    "creationTimestamp": 1680602367506,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.3",
    "jwtSecretKey": "ZDY1ZDhkZTQ5OGJlODg4ZjYxZTc5YmIyYzU1MzEzYjViYTkyMzc0YjEwYjQ1ODMwZmJkMDA1NWNmMWQzMWExOWUxZjljOTQxNGI4M2IzODY1MzQ4YjFiMGVmYTg2NTAyNmVhM2UwOTZlOTYxYmRhMDdmZjZjYTEzMjJiMGNiMzM=",
    "languages": ["en"],
    "messageBroker": false,
    "microfrontend": false,
    "microfrontends": [],
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8081",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": true,
    "skipFakeData": false,
    "skipUserManagement": true,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": false
  }
}

  </pre>
  </details>

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
I can handle these modifications, but first, let's try to see what would be the best solution.
I think we add the dependency and the test even if h2 is the dev database.

**Comment by mshima** [comment]
The PostgreSQLContainer dependency is supposed to be excluded from dev profile.
https://github.com/jhipster/generator-jhipster/blob/0560fc31c3e5b6664bfa720b283330017ad01126/generators/server/templates/pom.xml.ejs#L1771-L1781

**Comment by nitram84** [comment]
@mshima You are right. But if you are using eclipse and automatic build is enabled, it seems that eclipse ignores this profile for its internal build and this error can be reproduced. In my opinion it's cleaner not to generate a file than to exclude it later.

**Comment by avdev4j** [comment]
@mshima You're right. Launching the tests via Maven works, the classes is ignored.
But with Intellij it is not. It might be equivalent to what @nitram84 is talking about with Eclipse.

**Comment by mshima** [comment]
For eclipse, adding the dependency at `eclipse` profile should fix.
https://github.com/jhipster/generator-jhipster/blob/624d087772edc1737e9db23e513948a91aa5c184/generators/server/templates/pom.xml.ejs#L1891

I don't know for others IDEs.
`IDE` profile maybe?
https://github.com/jhipster/generator-jhipster/blob/624d087772edc1737e9db23e513948a91aa5c184/generators/server/templates/pom.xml.ejs#L1874

**Comment by mraible** [comment]
I've experienced this issue with IntelliJ for the past several months, both in 7.x released versions as well as the `main` branch. It's frustrating.

**Comment by sw-enthusiast** [comment]
> For eclipse, adding the dependency at `eclipse` profile should fix.
> 
> https://github.com/jhipster/generator-jhipster/blob/624d087772edc1737e9db23e513948a91aa5c184/generators/server/templates/pom.xml.ejs#L1891
> 
> I don't know for others IDEs. `IDE` profile maybe?
> 
> https://github.com/jhipster/generator-jhipster/blob/624d087772edc1737e9db23e513948a91aa5c184/generators/server/templates/pom.xml.ejs#L1874

This fix helped me. Thank you!

**Comment by mb-undairstand** [comment]
Hi, sorry to ask but i don't get how to resolve this. I'm in jhipster 7.9.3 and have issue trying to execute Jhipster aws because of that "PostgreSQLContainer cannot be resolved". Any help  ?
