### ISSUE TITLE
Enable cross origin HTTP requests not working for POST requests

### ISSUE THREAD

**Issue by vitornobrega** [jhipster/generator-jhipster#2171]
I created a jhipster project with new entities and new services and i need to use this services in a mobile application. My mobile application have been created with ionic generator and followed the website: http://jhipster.github.io/tips/006_tips_enable_cross_origin_requests.html

I need to call all services from a different origin. When i try GET requests, i see this in console

Remote Address:[::1]:8080
Request URL:http://localhost:8080/api/works?cacheBuster=1445252364661&page=1&per_page=20
Request Method:GET
Status Code:401 Unauthorized

The user shold be authentication to invoke this service, soo the get request is processed.
When i try to make any post (authentication  or create a new work for example), this is the status
Remote Address:[::1]:8080
Request URL:http://localhost:8080/api/works?cacheBuster=1445252364661
Request Method:POST
Status Code:403 Forbidden 

XMLHttpRequest cannot load http://localhost:8080/api/works?cacheBuster=1445252364661. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 403.

What settings should I do to solve this problem? Lack some information on  tips enable cross origin requests page?

**Comment by gmarziou** [comment]
What authentication scheme did you configure in jhipster?

What authorizations did you configure in SecurityConfiguration? 

Also in Ionic, you must set up the Cordova whitelist plugin and put a Content-Security-Policy tag in your index.html.

**Comment by cbornet** [comment]
What type of auth are you using ? Session, Oauth ?

Does your browser send a pre-flight OPTIONS request ?

If you are using Oauth, you need to disable security on OPTIONS http methods in the ResourceServerConfiguration::configure() method. 
```java
.antMatchers(HttpMethod.OPTIONS, "/**").permitAll()
```
(For session auth, the equivalent class is SecurityConfiguration but I don't think it is necessary as your browser should put the auth headers by himself)

Spring boot 1.3 has some support for CORS so this could also be tested

**Comment by vitornobrega** [comment]
I am using http session for authentication but this is not good when my services will be invoked by mobile apps. 

I changed authentication type to token authentication, add a custom filter to allow all origins and know its working. Thanks for your help

**Comment by jvence** [comment]
I'm experiencing the same problem after upgrading to jHipster 2.23. Basically I've generated an app with oauth authentication and suddenly all POST preflighted requests are getting a 403 Forbidden error. I've added  .antMatchers(HttpMethod.OPTIONS, "/**").permitAll(). I've added @CrossOrigin(maxAge = 3600) to my custom @RestController.  
I also have a Cors filter that allows all origins and methods. GETs work fine but not POSTs. At a complete loss as things were working just fine.

**Comment by ViCe2099** [comment]
Could you please specify what end up being the final solution? I'm at a loss here getting 403 only in POST requests.
Thanks in advance.

**Comment by cbornet** [comment]
@ViCe2099 check #2288

**Comment by ViCe2099** [comment]
@cbornet Thanks for the response, I had already checked that thread, my problem was in where I had to add the filter but that is now done. Unfortunately it didn't resolve my problem, I'm trying to make a POST call from a Ionic mobile app to a service in my apache-tomcat 8 and I'm always getting 403, I have no problem with GET calls and I'm at a loss as I thought it was a CORS related problem and this would fix it.

If anyone had a similar problem and found a solution please let me know :)

**Comment by cbornet** [comment]
Does it work with  the generated Angular ?

**Comment by ViCe2099** [comment]
Using Postman I have no problem, when using it through the android emulator it doesn´t work, when using service through the app from my phone it doesn´t work and I cant use ionic serve at this time :/

**Comment by cbornet** [comment]
@ViCe2099 Can you try adding .antMatchers(HttpMethod.OPTIONS, "/**").permitAll() to the WebSecurityConfigurerAdapter together with the cors options of application.yml ?

**Comment by cbornet** [comment]
@ViCe2099 [This](https://github.com/jhipster/generator-jhipster/pull/2650) should solve your issue

**Comment by ViCe2099** [comment]
Thanks for the response, I tried that and more, added all kinds of permissions to every kind of request, after that i created clean projects where I could debug and I now know what the problem is:
isValidOrigin(originHeader)
Basically my originHeader is "file://", i'm running a ionic app on android 4.4.2 and that's the origin it gets and I don't know how to change it, the reason that the request is denied is because that origin ins't compatible with RFC2396, it would have to be something like "file://something.com".
I am trying to add a filter to my web.xml to change the CorsFilter to a class that I created where isValidOrigin returns true when originHeader is "file://".
Right know I'm getting:
java.lang.ClassNotFoundException: org.apache.catalina.myfilters.CorsFilter
I added a copy of the original CorsFilter to my jhipster project with the change that I wanted and added:
        <filter>
		<filter-name>CorsFilter</filter-name>
		<filter-class>org.apache.catalina.myfilters.CorsFilter</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>CorsFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
to my web.xml, if you can help me find what I am doing wrong I would really appreciate it.

**Comment by ViCe2099** [comment]
I still cannot override org.apache.catalina.filters.CorsFilter's method isValidOrigin, any which way I try the method is always used to validate a request.
If anyone have any info on how to accomplish this, or in how to remove the default filter completely so I can add a custom one please let me know.
Thanks in advance.

**Comment by cbornet** [comment]
Your CorsFilter shouldn't be org.apache.catalina.myfilters.CorsFilter but org.springframework.web.filter.CorsFilter. Are you using the latest JHipster version ? There is a CorsFilter bean in WebConfigurer that will be activated if you set the values in your application.yml
