### ISSUE TITLE
Add support for H2 in Liquibase Hibernate with Gradle

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2172]
Copy what has been done in https://github.com/jhipster/generator-jhipster/commit/bf5f3ad8178f7dc18ba57c66c5531560e630593e (in the pom.xml) so we have the Gradle build in sync -> this is for adding H2 support with Liquibase Hibernate

@atomfrede as it's Gradle I'm assigning this to you, but as it's my code I'm of course available to do it if you don't have the time or if you need help

**Comment by atomfrede** [comment]
I'll try to have look on Wednesday. Don't think I have time before.
