### ISSUE TITLE
AngularJS format error when saving a LocalDate

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2173]
This only happens in the current master branch (future 2.23.0 version).

It is because we migrated to the Java Time API.

Everything works well (viewing, saving) but when a LocalTime (not ZonedDateTime!) is saved, AngularJS throws the following error in the console:

    Error: [ngModel:datefmt] Expected `2015-10-01` to be a date
    http://errors.angularjs.org/1.4.5/ngModel/datefmt?p0=2015-10-01
    at angular.js:68
    at Array.<anonymous> (angular.js:21659)
    at Object.ngModelWatch (angular.js:25229)
    at Scope.$digest (angular.js:15707)
    at Scope.$apply (angular.js:15986)
    at HTMLFormElement.<anonymous> (angular.js:23376)
    at HTMLFormElement.jQuery.event.dispatch (jquery.js:4435)
    at HTMLFormElement.elemData.handle (jquery.js:4121)

This is a blocker issue for our 2.23.0 release (even if it's only "graphical").

**Comment by ErickSanVal** [comment]
Hi, @jdubois. Does this have something to do with the Jackson configuration? I've been trying to troubleshoot this issue and it seems that the local date serializer is not specified in the Jackson configuration class. Haven't tested though.

**Comment by jdubois** [comment]
I think it's only on the AngularJS side, but I have no idea what causes this issue at the moment. This is really annoying for our next release!!

**Comment by jdubois** [comment]
So the issue is with the `dateutil.service.js` code, in the `convertLocaleDateToServer` function:

- If we use a date, for a reason I don't understand, we have some timezone issue which makes you lose one day (at least in France, but I expect it's not working correctly for all countries which are before the GMT timezone). For the record, I'm doing:

    return new Date(date.getFullYear(), date.getMonth(), date.getDate());

- The current solution is to code this as a String, which makes the correct date (obviously, as we write it manually!). This works fine on the server side (it's just getting a JSON String anyway), but on the AngularJS side the current stacktrace is produced: this is because we have changed the type of the property from Date to String, so AngularJS as an issue formatting it. It does not have any other issue than this stacktrace.

**Comment by Vaelyr** [comment]
What is the actual Java type you were using here? LocalTime is not a date as mentioned in first post.

I have only used LocalDatetime and Date instances. On angular side formatted with moment and works in any case.

**Comment by deepu105** [comment]
Can you PR it if you are able to solve it

**Comment by jdubois** [comment]
This is fixed as we now use the Angular UI datepicker
