### ISSUE TITLE
Controller spec having invalid identifier

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2175]
This is only in the master branch (upcoming 2.23 version), following the merge of #2152 that was coded by @trevershick 

When creating a new entity, and running `grunt test`, I get:

    ERROR [preprocessor.coverage]: Line 5: Unexpected identifier
      at /Users/julien/workspace/tmp/src/test/javascript/spec/app/entities/foo/foo-detail.controller.spec.js
    Fatal error: Not a string or buffer

**Comment by trevershick** [comment]
what is in your .jhipster folder and what is your .yo-rc.json ?

**Comment by jdubois** [comment]
thanks @trevershick but I just solved it :-)
Just some spaces which shouldn't be there, have a look at https://github.com/jhipster/generator-jhipster/commit/035e44c8e2e617ab6fbdb1270d6a2dc289a44655

**Comment by trevershick** [comment]
Yeah. Thanks. i saw that. I feel silly. I know i tested the entities.  I think my editor has jsformat (which does auto reformat) in it. I need to remove that. sorry for the troubles.
