### ISSUE TITLE
[jdl] Drop deprecated jpaDerivedIdentifier.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#21768]
##### **Overview of the feature request**

Drop deprecated jpaDerivedIdentifier which has been replaced with `@Id`.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/22283
