### ISSUE TITLE
Karma test failing when translation is turned off

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2178]
This is only in the master branch (upcoming 2.23 version), following the merge of #2152 that was coded by @trevershick

When the "no translation" option is selected (`"enableTranslation": false` in the `.yo-rc.json`), there is an error when running `grunt test`

    PhantomJS 1.9.8 (Mac OS X 0.0.0) Controllers Tests  RegisterController should update success to OK after creating an account FAILED
        Expected spy MockTranslate.use to have been called.
    PhantomJS 1.9.8 (Mac OS X 0.0.0) Controllers Tests  RegisterController should update success to OK after creating an account FAILED
        Expected spy MockTranslate.use to have been called.

**Comment by trevershick** [comment]
I'm on it. Is there a way to test all these permutations other than manually?

**Comment by trevershick** [comment]
I'm working the fix for this.

**Comment by jdubois** [comment]
@trevershick I'm using https://github.com/jhipster/jhipster-automated-samples

-> but this does not test everything, there are too many permutations!! This should be improved, but as you can see it already catches quite a good number of issues

**Comment by trevershick** [comment]
I was unaware of that. Thanks!

**Comment by pascalgrimaud** [comment]
@jdubois @trevershick : I'm working with Travis CI to test permutations and other things. I will propose this new project soon... It will complete the jhipster-automated-samples
