### ISSUE TITLE
Use Travis CI to enforce the QA

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#2182]
Hi,

I read this https://groups.google.com/forum/?hl=en#!topic/jhipster-dev/udaVHfPx0ds

So I wanted to improve the QA of JHipster. Since near 1 month, I worked on a personnal project:
* https://github.com/pascalgrimaud/jhipster-integration/

Here an example of Travis CI build:
* https://travis-ci.org/pascalgrimaud/jhipster-integration/builds/86295900

Plz, don't look commits (I tested a lot of things to understand how Travis CI works).
**It's an alpha version !!** I have to monitor commits on generator-jhipster and go on to test build + results

The goal is to let Travis CI test different apps (using matrix). Currently:
* default
* mysl in prod profile
* psql and elasticsearch in prod profile
* mongodb
* cassandra
* gradle
* gulp
* websocket
* noi18n
* oauth2

What the build travis does :

**Prepare environment**

* download docker-compose and pull the images depending on app (mysql, postgres...)
* install all tools needed (yeoman, bower, generator-jhipster...)
* try to speed up the build by downloading the dependency before using yo. 3 differents options :
    * use a sample-app and mvn dependency:go-offline
    * pull the docker image : jdubois/jhipster-docker and cp .m2/ and node_modules/
    * use a personnal repo https://github.com/pascalgrimaud/jhipster-lib to copy m2 and node_modules => this repo will need to be updated when new dependencies are added.

**Test JHipster**
* generate the project with yo jhipster
* generate entities with yo jhipster:entity
* launch tests (mvn/gradle test, and grunt/gulp test)
* launch docker-compose to start the database/service
* launch mvn or gradlew with the choosen profile to start the app (currently, no tests)

**Other things**
* one result (success or failed) instead of X different results, according to the number of builds
* only 5 builds at same time, so I had to choose wisely the order
* a full build time for 1 app can take near 15min~20min (when downloading all dependency m2 / node_modules)
* I had to use a personnal repo to speed up the build: https://github.com/pascalgrimaud/jhipster-lib => maybe someone has better idea ?
* I shouldn't but I used run task to test the deployment
    * so I need to play with sleep <time>... sometimes, sleep time is not enough to the build... need to reajust it
    * sometimes, Travis breaks the build and I don't understand why
    * currently, no tests on run tasks because, the app can be stuck at `[INFO] com.mycompany.myapp.config.WebConfigurer - Web application fully configured`

**Use**
* I think it's not a good idea to integrate to generator-jhipster => the full build is too long...
* Maybe use this project as standalone and manually launch the build manually (by Jdubois) after big commits ? Maybe use it to complete the jhipster-automated-samples

Feedback are welcome. Hope it will help.

**Comment by deepu105** [comment]
Sounds nice man, not very familiar with travis, but what you are trying
would definitely help as testing is one of the main pain point as the
project grows

+1 from me

**Comment by mraible** [comment]
The more testing, the better! +1 from me.

**Comment by atomfrede** [comment]
:+1: Wow that looks pretty cool.

**Comment by cbornet** [comment]
Looks great !  :+1:

**Comment by PeterEltgroth** [comment]
Nice! :+1:

**Comment by jdubois** [comment]
Yes, would be better than what we currently have!

**Comment by pascalgrimaud** [comment]
https://travis-ci.org/pascalgrimaud/jhipster-integration/builds/86295900
app-noi18n => KO, Issue https://github.com/jhipster/generator-jhipster/issues/2178

https://travis-ci.org/pascalgrimaud/jhipster-integration/builds/86554363
All is OK, after the fix https://github.com/jhipster/generator-jhipster/pull/2179

**Comment by pascalgrimaud** [comment]
@jdubois : cassandra build fails since you migrated to spring boot M5 -> RC1
https://travis-ci.org/pascalgrimaud/jhipster-integration/builds/86660667

Is there something related to your PR in official spring boot project ?

**Comment by cbornet** [comment]
Yes, spring-boot now autoconfigures cassandra and that conflicts with our conf.

**Comment by pascalgrimaud** [comment]
Update about my work :
* monitoring differents commits since 1 week and it seems all build do their job
* "Yes, would be better than what we currently have!" => so I will propose to replace the actual travis by this new
* to speed up the build, I use https://github.com/pascalgrimaud/jhipster-lib
    * with git clone, git zip and download the project, so we get all dependencies (m2 and node_modules) faster than download 1 by 1
    * if you disagree with it, we can use travis without this option and let the build download all dependencies (gradle = 14min (without this option), others (mvn) = 7~8min with speedup build)
    * or maybe use an official jhipster/jhipster-lib ?
* I will go on monitoring and do a PR this weekend, unless new ideas :)

**Comment by mraible** [comment]
How long does it take to create a new project when using jhipster-lib?

Could it be used for demos to speed up project creation and npm install?

**Comment by pascalgrimaud** [comment]
On my machine :
* mkdir test && cd test
* launch my personnal script
```
#!/bin/bash
cp -R ~/pgr/jhipster-lib/node_modules .
npm link generator-jhipster
```
* yo jhipster
* answer all questions
* press enter => 25sec

**Comment by cbornet** [comment]
If I understand well, this is about 15 mn to build all projects in parallel with speedup ?
Then IMO, it would be totally worth having it on PRs

**Comment by jdubois** [comment]
Closing this as this is merged -> it's not perfect yet, the discussion goes on at #2292
