### ISSUE TITLE
Update gradle and sonar plugin

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#2183]
When updating to latest gradle 2.8 the sonar plugin should be updated, [because the currently used plugin is deprecated.](https://docs.gradle.org/current/release-notes#the-sonar-and-sonar-runner-plugins-have-been-superseded-by-an-external-plugin-from-sonarqube)

**Comment by phouverneyuff** [comment]
http://docs.sonarqube.org/display/SONAR/Analyzing+with+Gradle#AnalyzingwithGradle-MigrationfromGradleSonarRunnerPlugin
