### ISSUE TITLE
Add a popup to login after session timeout

### ISSUE THREAD

**Issue by magelle** [jhipster/generator-jhipster#2185]
Hi everybody,

I use jhipster with the session authentication.
Sometimes the session expires while working a long time on the same page.
After the session timeout the user is redirected to the login page.
This redirection could lead to loss of work in progress if the current page is a form.

It would be great to add a login popup to avoid the automatic redirection to the login page and to be able to login without leaving the current page.

![jhipster-popup-login](https://cloud.githubusercontent.com/assets/12733623/10610603/e1765e98-7748-11e5-91ca-e2d342be10b1.gif)

**Comment by deepu105** [comment]
Plz check my comments on your commit, also try to squash your merge commits or rebase

**Comment by jdubois** [comment]
I would love to have this in 2.23.0 but there are merge conflicts -> I'm removing the 2.23.0 milestone on this, it will be in a future release.

**Comment by cbornet** [comment]
:+1: 
Would love to have this. I am currently working on Oauth2 3-legged oauth and one of the issues I am facing is that when a 3rd party site accesses /oauth/authorize the user should be asked to authenticate if needed. For the moment I use basic auth but this is not great user experience.

**Comment by Vaelyr** [comment]
Any reason for having separate logic controllers here? What about changing the main login into popup as well to avoid duplication and reuse the controller, view and service.

**Comment by deepu105** [comment]
@jdubois the sample app [here](https://github.com/jhipster/jhipster-sample-app/tree/master/src/main/webapp/scripts/components) seems to have the login-popup folder and code from this PR was it merged by mistake on your local??

**Comment by deepu105** [comment]
@magelle any update on this?

**Comment by jdubois** [comment]
@deepu105 I don't remember merging this...

**Comment by deepu105** [comment]
thats strange then how come the sample app has that folder :O

Thanks & Regards,
Deepu
