### ISSUE TITLE
The mail health check has disappeared

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2187]
Following the commit https://github.com/jhipster/generator-jhipster/commit/64bbe3ccb011c2d0b9cd73dfa89c55079c65e4c3, JHipster is now using the autoconfigured JavaMailSenderImpl from spring-boot.

I tested that the removed JavaMailHealthIndicator correctly injects the bean configured by spring boot so we could still use it.

@jdubois I can pull a PR to set back the indicator if have no objection.

**Comment by jdubois** [comment]
yes I didn't see I removed it -> your PR would be welcome!

**Comment by cbornet** [comment]
I have just realized that the MailHealthIndicator has been added to the actuators so the custom one should not be needed in jhipster (this is probably why you removed it in the first place). I wonder why I don't see it with my app though...
Also CassandraHealthIndicator.java has been added to 1.3.0.RC1 and we could also use the default DataSourceHealthIndicator.java for the SQL databases.

**Comment by cbornet** [comment]
OK. Don't know what I did in the first place but the spring boot MailHealthIndicator works just fine. Probably a wrong config on my side.
I will open another issue to simply remove config.metrics directory when we upgrade to 1.3.0.RC1+ since all the health indicators we use are now included in spring boot.

**Comment by jdubois** [comment]
- yes if could remove all of them
- not sure for the database check -> we have some specific SQL queries, we need to check if the one provided by Spring Boot is good enough
- for Cassandra, it's our own CassandraHealthIndicator which has been contributed to Spring Boot, so I definitely think it should replace ours :-)

Can we close this, as you don't have the issue any more?

**Comment by cbornet** [comment]
As for the datasource, the queries look exactly the [same](https://github.com/spring-projects/spring-boot/blob/v1.3.0.RC1/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/DataSourceHealthIndicator.java)

**Comment by cbornet** [comment]
A for Cassandra, your full autoconfiguration has been included into spring-boot 1.3.0.RC1. Unfortunately, it doesn't include the enhancements from https://github.com/jhipster/generator-jhipster/pull/1564. Do you think we could PR to spring-boot and hope to have it in RC2 ?
Also I think there can  be conflicts between the RC1 autoconfigured cassandra and ours so this will have to be checked when upgrading.
