### ISSUE TITLE
jhipster.github.io website: Adding a Japanese Translation

### ISSUE THREAD

**Issue by hide212131** [jhipster/generator-jhipster#21897]
##### **Overview of the feature request**

I have translated the JHipster website into Japanese to contribute to this project.
Would it be possible to add a link to my Japanese translated site on the main English site (or create a repository with a similar structure to [the existing Chinese site](https://github.com/jhipster/cn
) and put it there)?

https://hide212131.github.io/jhipster.github.io/
https://github.com/hide212131/jhipster.github.io

##### **Motivation for or Use Case**

This would be useful for Japanese developers.
Please note that I can continue to maintain the translated site.

##### **Related issues or PR**
https://github.com/jhipster/jhipster.github.io/pull/768

- [X] Checking this box is mandatory (this is just to show you read everything)

I would like to thank the wonderful JHipster team and all the developers.
Thank you in advance for your consideration.

**Comment by jdubois** [comment]
Yes we can do something similar to the Chinese website.
The main issue we have is maintenance, then the website doesn’t change that often.

**Comment by hide212131** [comment]
Thank you for your response.

If someone could create the repository and grant me commit rights, I would be able to migrate the website.
I also plan to submit a pull request for the language selection dropdown.

I truly empathize with the challenges of maintaining such a project...

**Comment by jdubois** [comment]
@hide212131 I just created the repo at https://github.com/jhipster/jp and invited you in the admin of the repo.
I can't guarantee how things will go to publish it, but that's a very good start!

**Comment by hide212131** [comment]
@jdubois Thanks! I'll get to work on it!

**Comment by hide212131** [comment]
@yoshioterada san, Thank you as well for all your support. I really appreciate it.

I just built a Japanese site.
https://www.jhipster.tech/jp/

The language selector is just a proposal at this point. After this, I plan to submit a pull request to the English repository and discuss further adjustments.

**Comment by jdubois** [comment]
Oh this seems to be working exactly like the Chinese version, I'm surprised! Looking good to me!

**Comment by hide212131** [comment]
@jdubois san, thank you so much for the merge! I'm very pleased!
@yoshioterada san, thank you so much!

I will continue to work hard contributing to JHipster.

In the interest of site consistency, I have submitted a [PR for the CN site](https://github.com/jhipster/cn/pull/44). If it gets merged, this issue will be resolved. I look forward to your support.

**Comment by jdubois** [comment]
Thank you so much, I just merged this other PR!
