### ISSUE TITLE
Docker setup instructions no longer valid.

### ISSUE THREAD

**Issue by indyaah** [jhipster/generator-jhipster#2191]
Given that docker team has released docker toolbox as an alternative to boot2docker, the documentation should be updated for docker toolbox guide.

I am willing to write/update the documentation if jhipster team considers this as valid issue.

**Comment by andidev** [comment]
+1

**Comment by duderoot** [comment]
+1

**Comment by jdubois** [comment]
Thanks @indyaah -> yes this is a perfectly valid issue, feel free to work on it!! Maybe @pascalgrimaud could help you with that, or at least review your code?

**Comment by indyaah** [comment]
@jdubois :Yup, I will updated the document and create a pull request.

**Comment by pascalgrimaud** [comment]
Yes I can review, @indyaah

**Comment by indyaah** [comment]
@pascalgrimaud : Kindly review and let me know if I missed something.

**Comment by pascalgrimaud** [comment]
@indyaah : thanks, I'll review it tonight (after work) :-)
