### ISSUE TITLE
Remove cassandra configuration

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#2195]
@jdubois : your cassandra support is released in spring boot 1.3.0.RC1
https://github.com/spring-projects/spring-boot/tree/v1.3.0.RC1/

More Java code to remove
Java Hipster -> JavaScript Hipster

**Comment by mraible** [comment]
You prompted me to run cloc on the master branch to see how we're doing. Looks like JSON (from i18n files) is the winner these days.

```
$ cloc .
     808 text files.
     726 unique files.
     142 files ignored.

http://cloc.sourceforge.net v 1.64  T=2.26 s (294.6 files/s, 16577.0 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
JSON                            319             34              0           9160
Javascript                      122            948            366           9064
Java                            149           1958            962           8966
HTML                             37            142             30           2293
XML                              11             73             56           1486
YAML                              9             29             89            540
Groovy                           10             63              1            419
Bourne Again Shell                5             31             20            169
CSS                               2             26             22            168
SASS                              1             27              2            166
Scala                             1             14              7            110
DOS Batch                         1             24              2             64
--------------------------------------------------------------------------------
SUM:                            667           3369           1557          32605
--------------------------------------------------------------------------------
```

**Comment by pascalgrimaud** [comment]
So it should be JSon Hipster ? :-O

**Comment by cbornet** [comment]
Note that there has been enhancements in https://github.com/jhipster/generator-jhipster/pull/1564 to our conf that are not part of spring-boot.

**Comment by jdubois** [comment]
Our current Cassandra conf should be far more advanced than the one I contributed in Spring Boot, as we had commit https://github.com/jhipster/generator-jhipster/commit/300f475916ba807313bfcb83c3bd2461862c82e8 from @adejanovski

So I need to check our current conf but:

- I'd keep our current conf for the moment if this is possible, it's more complete and it's easier to do
- @adejanovski could you also propose your changes to Spring Boot, like I did? That way we would still be able to use your code, but without generating it

**Comment by jdubois** [comment]
OK, it seems it going to be difficult to keep our current configuration, and it's quite confusing because we have both configurations having the same class names...

- it seems that the easiest way, and less confusing for users, is to remove our configuration and use the one from Spring Boot
- @adejanovski that would mean we lose your changes (it's still in the history, of course), and that it would be needed to commit them to the official Spring Boot repo

-> @adejanovski can you do this PR to Spring Boot, and link it to this ticket? I could also do it myself, but the idea is that you keep your author information on your code, of course.

**Comment by adejanovski** [comment]
@jdubois ok, I'll try to send a PR asap.

**Comment by pascalgrimaud** [comment]
@jdubois : what about _CassandraHealthIndicator.java ?

**Comment by cbornet** [comment]
@pascalgrimaud  The full config.metrics dir can now be removed :smile:

**Comment by pascalgrimaud** [comment]
Thanks @cbornet
I couldn't test today, just review commits et make suggestions :)

**Comment by cbornet** [comment]
@adejanovski Did you do the PR on Spring Boot ?
Also the link to the jdbc-driver you provided has disappeared so is it still useful ?
