### ISSUE TITLE
H2 disk-based configuration not working properly on Windows

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2202]
On release 2.23.0 we have H2 disk-based support.

As mentioned by @deepu105 at
https://github.com/jhipster/generator-jhipster/commit/bf5f3ad8178f7dc18ba57c66c5531560e630593e#commitcomment-13926605
it looks like it's not working properly on Windows.

From my understanding, the "." does not work properly on Windows: maybe it does not understand it as the current directory?

- This needs to be further investigated
- As I don't have a Windows machine, I have no way of testing this -> anyone having a Windows machine is welcome to test (I guess it might also depend on the Windows version)

**Comment by deepu105** [comment]
I was on windows 10 for the record

**Comment by deepu105** [comment]
I checked H2 documentation couldn't find anything regarding this, will take
a deeper look tomorrow

**Comment by deepu105** [comment]
@jdubois I have tried many combinations at last found one url which works in windows and from the h2 docs seems it should work in mac/unix
`jdbc:h2:file:./target/h2db/db/jhipster;DB_CLOSE_DELAY=-1` 

ill open a PR with this
