### ISSUE TITLE
Help people to fill issues according to the guidelines with a template

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2205]
Click [here](https://github.com/jhipster/generator-jhipster/issues/new?body=*%20**Overview%20of%20the%20issue**%0A%0A%3C!--%20if%20an%20error%20is%20being%20thrown%20a%20stack%20trace%20helps%20--%3E%0A%0A*%20**Motivation%20for%20or%20Use%20Case**%20%0A%0A%3C!--%20explain%20why%20this%20is%20a%20bug%20for%20you%20--%3E%0A%0A*%20**JHipster%20Version(s)**%20%0A%0A%3C!--%20is%20it%20a%20regression%3F%20--%3E%0A%0A*%20**JHipster%20configuration%2C%20a%20%60.yo-rc.json%60%20file%20generated%20in%20the%20root%20folder**%20%0A%0A%3C!--%20this%20will%20help%20us%20to%20replicate%20the%20scenario%2C%20you%20can%20remove%20the%20rememberMe%20key.%20--%3E%0A%0A*%20**Entity%20configuration(s)%20%60entityName.json%60%20files%20generated%20in%20the%20%60.jhipster%60%20directory**%20%0A%0A%3C!--%20-%20if%20the%20error%20is%20during%20an%20entity%20creation%20or%20associated%20with%20a%20specific%20entity%20--%3E%0A%0A*%20**Browsers%20and%20Operating%20System**%20%0A%0A%3C!--%20is%20this%20a%20problem%20with%20all%20browsers%20or%20only%20IE8%3F%20--%3E%0A%0A*%20**Reproduce%20the%20error**%20%0A%0A%3C!--%20an%20unambiguous%20set%20of%20steps%20to%20reproduce%20the%20error.%20If%20you%20have%20a%20JavaScript%20error%2C%20maybe%20you%20can%20provide%20a%20live%20example%20with%0A%20%20%5BJSFiddle%5D(http%3A%2F%2Fjsfiddle.net%2F)%3F%20--%3E%0A%0A*%20**Related%20issues**%20%0A%0A%3C!--%20has%20a%20similar%20issue%20been%20reported%20before%3F%20--%3E%0A%0A*%20**Suggest%20a%20Fix**%20%0A%0A%3C!--%20if%20you%20can%27t%20fix%20the%20bug%20yourself%2C%20perhaps%20you%20can%20point%20to%20what%20might%20be%0A%20%20causing%20the%20problem%20(line%20of%20code%20or%20commit)%20--%3E) to open a new issue prefilled with the guidelines template.

I'm thinking of adding a button in the CONTRIBUTING.md and on jhipster.io

Any other ideas ?

**Comment by mraible** [comment]
👍

**Comment by pascalgrimaud** [comment]
very good idea. But I don't know if a lot of people read CONTRIBUTING.md before going Issues, so maybe a button in the README.md file too ?

**Comment by jdubois** [comment]
Looks good, but do we really need to hold each user by the hand?
Each time you open up an issue, there is already a box with a link asking you to follow the guidelines.
I know a lot of people don't follow the guidelines, but:
- sometimes they have a good reason -> they have just a simple thing they want to share, and we might lose those people
- sometimes, indeed, people aren't being very good citizens -> in that case I have no problem in closing their issues!

**Comment by cbornet** [comment]
This is just a helper which will obviously be used only by good citizens who want to do things properly. when they face a bug. For non bug issues, you can still open issues the way you do now (this very issue is not a bug so I didn't follow the guidelines myself :smiley: )

**Comment by cbornet** [comment]
Maybe we should mention that the guidelines are for bugs only ?

**Comment by cbornet** [comment]
In fact, it already is mentioned... Maybe I should read the guidelines myself :sweat_smile:

**Comment by jdubois** [comment]
Closing as this is merged.
