### ISSUE TITLE
Rename Application to App

### ISSUE THREAD

**Issue by jbadeau** [jhipster/generator-jhipster#2210]
The Application.java file is conflicting with entities being named 'Application' which is a very common name. Would it be possible to rename the 'Application' class to 'App' and 'ApplicationWebXml' to 'AppWebXml'

**Comment by gmarziou** [comment]
This is a rather simple refactoring that anybody can do in his IDE.
However in my projects I often have several JHipster applications and rather than using a generic name like 'Application' or 'App' I prefer to name them as <appName>Application: FrontOfficeApplication, DashboardApplication, ....

**Comment by jbadeau** [comment]
The main issue is when using generator tasks or jhipster-uml, the name 'Application' is assumed and then you are forced to rename all the references, not hard but annoying and time consuming.

**Comment by jdubois** [comment]
Yes we should quite "Application", it's much clearer for users that it's the main application class.

**Comment by deepu105** [comment]
Application is much better

**Comment by jdubois** [comment]
OK, I'm keeping "Application".
For jhipster-uml -> this could be an option, but then I don't understand when it's referenced
