### ISSUE TITLE
SecurityUtils getCurrentUser throws exception

### ISSUE THREAD

**Issue by amitjindal** [jhipster/generator-jhipster#2212]
Hi, I am not sure if I am doing something wrong.
After login in a Resource, I am trying to call:
```
CustomUserDetails currentUser = SecurityUtils.getCurrentUser();
```
This is throwing exception from line 81 of SecurityUtils: IllegalStateException("User not found!")
I tried to debug this also in IntelliJ, and while intellij shows authentication.getPrincipal() is an instance of CustomUserDetails, the instanceof operator fails and even the typecast results in an exception.

I also tried to change the code from:
```
if (authentication.getPrincipal() instanceof CustomUserDetails) {
    return (CustomUserDetails) authentication.getPrincipal();
```
To this:
```
Object principal = authentication.getPrincipal();
if (CustomUserDetails.class.isInstance(principal)) {
    return CustomUserDetails.class.cast(principal);
}
```
It is still not working for me. I must be missing something.
Could you please help!

**Comment by cbornet** [comment]
Please use our [guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue) to fill your issue

**Comment by jdubois** [comment]
Yes, this has been changed recently, we need your version number -> I'm closing this as the guidelines are not followed.

**Comment by amitjindal** [comment]
Refiled: https://github.com/jhipster/generator-jhipster/issues/2216

**Comment by jdubois** [comment]
Great, thanks!
