### ISSUE TITLE
Use autoconfigured H2-console

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2222]
Spring-boot 1.3 starts an H2 web console when devtools is on and h2 is present on the classpath (http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-sql-h2-console). You can test that it is already there with dev profile :smile: at http://localhost:8080/h2-console. As per Policy 1, shouldn't we use it instead of our custom one ? The only drawback I see is that it doesn't get its properties from src/main/resources.

Also, interesting to note: the console is not limited to H2 and can be used with any jdbc driver.

**Comment by jdubois** [comment]
Yes -> for the drawback concerning the properties in src/main/resources I'm not sure it is such an issue. On my laptop Chrome keeps trying to input the wrong login/password so it's not very usable anyway! The best option would be to remove authentication on localhost, I don't know if that's possible.

**Comment by jdubois** [comment]
There is an issue with the built-in h2 console, as it doesn't support our CSRF token (and so with our default authentication scheme it will fail).
Besides, it doesn't use the `.h2.server.properties` file.
So our configuration is quite simple, and provides more features, let's keep it.
I will however disable the default h2 console (no need to have it twice), and map our console to that URL, as it's supposed to be the default one with Spring Boot.

**Comment by jdubois** [comment]
Sorry, for the CSRF issue it's configured in Spring Security, so this isn't a valid argument in fact.

**Comment by jdubois** [comment]
Still, using the h2.server.properties file is important, so we point to the correct database on the H2 console login screen, so let's keep the current configuration and remove the H2 auto-configuration from Spring Boot.
