### ISSUE TITLE
account.login not reloading in other views when login\logout

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#2224]
Architecture of the Principal.service.js do not allow to take correct account.login after login/logout. Example: I have 2 views: navbar and main. Both of them have $scope.isAuthenticated that works fine. In navbar this variable used to show/hide extra options. But what if I want to show username in the navbar? {{account.login}} reloads ONLY in the main controller unlike isAuthenticated. I must reload whole page to refresh {{account.login}}.

**Comment by deepu105** [comment]
@delverdev do you want to PR this?

**Comment by delverdev** [comment]
My website design isn't default JHipster, so I don't know how to fix it.

**Comment by jdubois** [comment]
Indeed, the `auth` service is only for authenticating users, and it doesn't store more information about them, like their login or email address.
That could be interesting for some people, but for other people we shouldn't store unused information, in particular if it's sensitive information.
If you want to have all user information, you need to do a REST request using the `account` service, and then you can store that information, for example in the $rootScope (or, even better, store it in the `account` service: you're not supposed to store stuff in the $rootScope, and the login is probably not going to change so you can "cache" it).
