### ISSUE TITLE
Readd stale workflow.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#22252]
##### **Overview of the feature request**

Readd stale workflow with 3 or 6 months for untouched bugs.

##### **Motivation for or Use Case**

Old bugs are not touched and due to the moving nature of jhipster generated application, most of then should become invalid quick.
Valid bugs doesn't receives attention due to missing triage.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/177001

**Comment by DanielFran** [comment]
@mshima approved
