### ISSUE TITLE
[Vue] move tests near implementation.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#22251]
##### **Overview of the feature request**

Move test files from `src/test/javascript/spec` to the folder of the test.

##### **Motivation for or Use Case**

- tests near the implementation are easier to find.
- will follow angular/react implementation.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by dinu0000** [comment]
i'm working on this

**Comment by dinu0000** [comment]
The tests are failing on Windows for a default app with Vue as front end. Seems like the paths defined like `......../tsconfig` doesn't work on windows. But moving the tests within the components folder seems to fix that
