### ISSUE TITLE
Entity dialog error messages are not translated

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2229]
This is for the notification system from @deepu105 and is linked to #2214

If there is a validation on the server side, the error message is not translated (it does not exist). We have the "global.entity.validation" messages (in the global.json file), it should probably use those messages.

Here is an example:
<img width="918" alt="capture d ecran 2015-10-27 10 32 08" src="https://cloud.githubusercontent.com/assets/316835/10754190/61886052-7c96-11e5-84a5-1a43d3f4ae66.png">

How to reproduce:

- Create an entity with a String and no validation
- Add a @Size(min = 10) to this String
- Add an @Valid to the controller for this entity to validate the String

-> then when updating the entity, there will be a server-side validation error

**Comment by deepu105** [comment]
Ill work on it this weekend
