### ISSUE TITLE
Failed to install Romanian language (sockets selected)

### ISSUE THREAD

**Issue by MardariG** [jhipster/generator-jhipster#2231]
Here's the error:
![untitled](https://cloud.githubusercontent.com/assets/8759158/10759323/67a66ee2-7cbf-11e5-941c-4df1d7d8a457.png)

**Comment by jdubois** [comment]
I confirm the issue with our latest version (please follow our guidelines!!!! give us more information!)

You need to:

- All default options, except Websockets is selected
- Add languages -> Romanian
