### ISSUE TITLE
Add loading gif or any information during login (and maybe some other requests)

### ISSUE THREAD

**Issue by Panthro** [jhipster/generator-jhipster#2232]
When doing the login and the api takes anything more than 500ms to respond, the feeling is like the browser got stuck and won't login.

A common user would probably hit the login button again.

I think it would be nice if in angular we could add some "loading status" to these api calls.

**Comment by mraible** [comment]
Angular Loading Bar was added in #2201. See #2206 if you'd like to add a progress indicator to your submit buttons.

I wrote up a blog post about both of these progress indicators this morning:

http://www.jhipster-book.com/#!/news/entry/progress-indicators-with-angularjs-and-jhipster

**Comment by Panthro** [comment]
Well, guess we're in sync with what is nice to have in jhipster lol!

Great Work! It should be enough!

Thanks for the fast reply

**Comment by geyuqiu** [comment]
@mraible Is it also included for Angular2+
