### ISSUE TITLE
MongoDB and Elasticsearch conflict @Document annotation

### ISSUE THREAD

**Issue by christianmenz** [jhipster/generator-jhipster#2235]
Hi, 

I'm just playing around with jhipster and created a sample project with MongoDB and Elasticsearch support. When I tried to build the app I got errors and I figured out it generates following code:

**import org.springframework.data.elasticsearch.annotations.Document;**
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import org.springframework.data.annotation.Id;
**import org.springframework.data.mongodb.core.mapping.Document;**
import org.springframework.data.mongodb.core.mapping.Field;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.time.ZonedDateTime;

**@Document(collection = "jhi_user")**
**@Document(indexName = "user")**

I guess it should used fully qualified class names in this situation. Thank you!

**Comment by christianmenz** [comment]
This is related to the same issue, if you use mongodb and elasticsearch, it generates an invalid application-xxx.yml as it has two **data** keys.

**Comment by jdubois** [comment]
Did you read our documentation at http://jhipster.github.io/using_elasticsearch.html - it says it only works with SQL databases

-> this is not a bug, as you normally should not have been able to generate this (or there is an issue in our generator, and that case please tell us how you did it)

**Comment by deepu105** [comment]
@jdubois The condition checking DB type was removed during Java 7 removal
it seems, @pascalgrimaud has submitted a fix and I have merged it

Closed #2235 <https://github.com/jhipster/generator-jhipster/issues/2235>.

—
Reply to this email directly or view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/2235#event-447290541>
.

**Comment by christianmenz** [comment]
Thank you very much!
