### ISSUE TITLE
Cache control in http response headers is not working

### ISSUE THREAD

**Issue by Raysmond** [jhipster/generator-jhipster#2239]
CachingHttpHeadersFilter sets Cache-Control, Pragma and Expires headers to http response, however, the cache-control and pragma is somehow override. 

For example:

```
Accept-Ranges:bytes
Cache-Control:no-store
Content-Length:223
Content-Type:application/javascript;charset=UTF-8
Date:Wed, 28 Oct 2015 05:16:31 GMT
Expires:Sat, 28 Nov 2015 05:16:31 GMT
Last-Modified:Wed, 28 Oct 2015 05:15:32 GMT
Pragma:
Server:Apache-Coyote/1.1
```

`Cache-Control` is reset to `no-store` and `Pragma` is empty.

**Comment by jdubois** [comment]
Which version are you using? This has probably changed significantly with Spring Boot 1.3 -> can you follow our guidelines and give your version number?

And how are you launching your application? This also probably change a lot depending whether you use a WAR file (on which app server?), the mvn plugin, etc...

-> please, follow the guidelines and give us more information

**Comment by jdubois** [comment]
I confirm the issue on the latest version, this is very bad news!!

This probably comes from Tomcat 8/Spring Boot 1.3, I have checked that:

- Our CachingHttpHeadersFilter is correctly accessed (if you add a new header you will get it in the response)
- The Cache-Control and Pragma headers are removed, and the Expires header is duplicated -> there is something that messes up what our filter does!!
- I have debugged Tomcat's ExpiresFilter filter, which is would be a logical culprit, and it is not being called!!

This is a major issue for production, and at the moment I have no idea what causes it, so help is welcome!!

**Comment by pascalgrimaud** [comment]
Maybe something has changed with spring-boot-devtools ?
Can you give a try without it ?

I made some tests, sample project mysql in prod profile :

spring-boot 1.3.0.M4 ==> seems ok
spring-boot 1.3.0.M5 ==> seems nok
spring-boot 1.3.0.RC1 => seems nok

**With devtools 1.3.0.RC1**
```
$ curl -i http://localhost:8080/
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-store
Pragma: 
Expires: 0
Set-Cookie: JSESSIONID=B99A628B8421F3B08706396F3AD73E94; Path=/; HttpOnly
Set-Cookie: CSRF-TOKEN=e595143e-6c68-4b49-bb6c-155a37608279; Path=/
X-Application-Context: application:prod:8080
Last-Modified: Thu, 05 Nov 2015 07:18:37 GMT
Accept-Ranges: bytes
Content-Type: text/html;charset=utf-8
Content-Length: 1607
Date: Thu, 05 Nov 2015 07:19:28 GMT
```

**Without devtools 1.3.0.RC1**
```
<!--<dependency>-->
    <!--<groupId>org.springframework.boot</groupId>-->
    <!--<artifactId>spring-boot-devtools</artifactId>-->
    <!--<optional>true</optional>-->
<!--</dependency>-->
```
```
$ curl -i http://localhost:8080/
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Set-Cookie: JSESSIONID=A2F4BBE87E4879FC091162A921C31049; Path=/; HttpOnly
Set-Cookie: CSRF-TOKEN=131562df-56bf-476b-8a24-97f9992938b1; Path=/
X-Application-Context: application:prod:8080
Last-Modified: Thu, 05 Nov 2015 07:22:17 GMT
Accept-Ranges: bytes
Content-Type: text/html;charset=utf-8
Content-Length: 1607
Date: Thu, 05 Nov 2015 07:22:57 GMT
```

**Comment by jdubois** [comment]
Thanks @pascalgrimaud it does have an impact, now all my headers are duplicated!!

    Cache-Control:no-cache, no-store, max-age=0, must-revalidate
    Cache-Control:max-age=2678400000, public

    Expires:Sun, 06 Dec 2015 09:12:00 GMT
    Expires:0

    Pragma:no-cache
    Pragma:cache

This is clearly a bug from Spring Boot or Tomcat, as they shouldn't duplicate any existing header!!

**Comment by deepu105** [comment]
We should open tickets to them

**Comment by jdubois** [comment]
It looks like the culprit is in fact Spring Security.
For security reasons, by default, they remove all cache control -> this is understandable, of course.

Then, those resources are supposed to be ignored by Spring Security, so there is something new which has broken our initial code.

**Comment by jdubois** [comment]
I got it working, but it's in fact a mix of both devtools AND Spring Security. Both of them are setting wrong headers...

**Comment by jdubois** [comment]
Corrected the Spring Boot issue, and a last PR with a mistake is on the way!

**Comment by pmadridb** [comment]
You didn't exactly point out how you fixed this issue.

**Comment by deepu105** [comment]
Check the commit mentioned

**Comment by pmadridb** [comment]
I made those changes in my code base and it didn't work.
