### ISSUE TITLE
Bootstrap v5.3.0 changed the background color.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#22406]
##### **Overview of the issue**

Application generated with angular and bootstrap v5.3.0 have gray background instead of white.

##### **JHipster Version(s)**

main

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
What elements have a gray background? 

I'm still not sure the buttons should have black text, as I mentioned in https://github.com/jhipster/generator-jhipster/issues/18008. The buttons in the screenshots of my JHipster Mini-Book are hard to read.

**Comment by mshima** [comment]
The entire page background is gray.
<img width="827" alt="Captura de Tela 2023-06-02 às 13 23 29" src="https://github.com/jhipster/generator-jhipster/assets/1417183/32ca7a63-37bd-43b6-8037-b1a269183fcb">
