### ISSUE TITLE
spring boot devTools not working. IDEA intellij.

### ISSUE THREAD

**Issue by lluiscanals** [jhipster/generator-jhipster#2242]
* **Overview of the issue**
I recently updated to jhipster 2.23.0. Made all necessary changes and startup the app with the spring boot plugin. (spring-boot:run). It seems that spring boot devTools are not restarting my application when one file is changed, for example one XxxxxResource file.
I'm using IDEA Intellij.

* **Motivation for or Use Case** 

* **JHipster Version(s)** 
2.23.0

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "xauth",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "testFrameworks": [
      "gatling"
    ]
  }
}

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

* **Browsers and Operating System** 
Ubuntu 14.04

* **Reproduce the error** 
 I also have generated one fresh app with the same configuration and seems not to work.

* **Related issues** 
No one.

* **Suggest a Fix**

**Comment by mraible** [comment]
Are you compiling the file after you change it, or just saving it?

**Comment by lluiscanals** [comment]
Just saving. I though that devTools detect changes automatically.

I tried in eclipse and it is working on saving, like this example:
https://spring.io/blog/2015/06/17/devtools-in-spring-boot-1-3

**Comment by mraible** [comment]
This is because Eclipse compiles automatically on save. Here's how to get similar functionality in IntelliJ:

http://stackoverflow.com/questions/12744303/intellij-idea-java-classes-not-auto-compiling-on-save

**Comment by lluiscanals** [comment]
Thank you very much. Works now.
It's just an idea, but maybe a note in the documentation in the intellij part may help other people, or maybe it's only my fault, anyway, thanks for the light-speed response! xD

**Comment by gmarziou** [comment]
@lluiscanals would you consider submitting a PR for documentation on this topic?

**Comment by lluiscanals** [comment]
Yes of course. I have never done before....but always a first time for all
xD. Tomorrow I will read about how to submit a PR and I'll try! :)

**Comment by gmarziou** [comment]
Great :)

**Comment by bourdux** [comment]
@mraible, @lluiscanals  Still IntelliJ will not automatically compile the class when the application is running. But hitting Shift-F9 will do the trick. I don't understand why IntelliJ starts a debugger when reloading the classes though :/
