### ISSUE TITLE
Add integration tests for elasticsearch

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2244]
The regression #2241 made me think that we should implement some IT for elasticsearch REST endpoints

**Comment by geraldhumphries** [comment]
Here is a quick implementation of an integration test based on the getAll test:

```
    @Test
    @Transactional
    public void searchAddresses() throws Exception {
        // Clear preexisting index
        elasticsearchTemplate.deleteIndex(Address.class);

        // Initialize the database
        addressRepository.saveAndFlush(address);
        
        // Initialize the index with the test address
        addressSearchRepository.save(address);

        // Search for an address
        restAddressMockMvc.perform(get("/api/_search/addresss/id:" + address.getId() + "?sort=id,desc"))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.[*].id").value(hasItem(address.getId().intValue())))
                .andExpect(jsonPath("$.[*].streetLine1").value(hasItem(DEFAULT_STREET_LINE1.toString())))
                .andExpect(jsonPath("$.[*].streetLine2").value(hasItem(DEFAULT_STREET_LINE2.toString())))
                .andExpect(jsonPath("$.[*].city").value(hasItem(DEFAULT_CITY.toString())))
                .andExpect(jsonPath("$.[*].provinceState").value(hasItem(DEFAULT_PROVINCE_STATE.toString())))
                .andExpect(jsonPath("$.[*].postalCode").value(hasItem(DEFAULT_POSTAL_CODE.toString())));
    }
```

ElasticsearchTemplate also needs to be injected but nothing else needs to be changed.

Elasticsearch will start embedded in the same folder (by default) as when you're running on develop. The line `elasticsearchTemplate.deleteIndex(Address.class);` will delete all data from the entity's Elasticsearch index. This line is absolutely necessary to make sure the test will output properly and that it won't break on a type mismatch.

If this integration test is run the dev will lose all ES data. This can be hugely annoying. If it somehow runs in prod (super unlikely as the dev would need to configure the test profile's ES instance and their prod profile's ES instance to run in the same folder), that could be disastrous. Both situations can be mitigated with the [Elasticsearch Reindexer module](https://github.com/geraldhumphries/generator-jhipster-elasticsearch-reindexer) if they do happen.

So I think we should also configure ES to run in a different path from dev:

```
src/test/config/application.yml

    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: target/test/elasticsearch/log
                  data: target/test/elasticsearch/data
```

there is already a test-classes folder generated but this doesn't really fit.

**Comment by cbornet** [comment]
:+1: nice !

**Comment by geraldhumphries** [comment]
There is a problem, the line `elasticsearchTemplate.deleteIndex(Address.class);` is a performance issue. It takes 0.5-1.5 seconds to run and that will significantly affect the amount of time the test suite will take.

`elasticsearchTemplate.deleteIndex("_all");` will delete all indexes at once and is a lot faster than deleting them individually (~1.5 seconds to run for 33 entities vs 0.5-1.5 seconds for each), but I am having trouble finding a place to put it. it should be run before any of the integration tests and only under the test profile. Have any suggestions?

**Comment by geraldhumphries** [comment]
Running `clean` will delete the target folder, clearing the index. Other tests will sometimes fail due to ES errors if this isn't done anyways, like when `create` is called through the API. I would rather explicitly clear the indexes, but if that isn't possible without performance/code cleanliness hits, do you think specifying in the docs that `clean` needs to be done before tests would be sufficient?

**Comment by jdubois** [comment]
For me you should delete each index in the "before" method of your test -> you can't run tests if you are not sure the state is correct, and you can't rely on the user to do this (running `mvn clean` manually isn't an option).
So yes you need to delete them -> if the fastest way is to do a `.deleteIndex("_all")`(which I believe is the case), then just do it in the "before" method. It might take some time, but those are integration tests, I'm not too surprised by it.

**Comment by geraldhumphries** [comment]
Is there some kind of beforeAll for the integration tests? Something that will run once before integration tests are done for any entity?

**Comment by cbornet** [comment]
You mean that is run before each test ? Or before the tests for a given entity ?

**Comment by geraldhumphries** [comment]
Something that is run before any integration tests are performed. Calling `deleteIndex("_all")` there would be the best case scenario - if not, then `deleteIndex(Entity.class)` before each of the Elasticsearch tests is the second best.

**Comment by jdubois** [comment]
Either before each test (with JUnit's Before annotation), or only once before each class (with the BeforeClass annotation - if that's a performance optimization).
That's what we already have for testing REST resources, for example.

**Comment by gmarziou** [comment]
Would it make sense to use a JUnit `@Rule` for this?

**Comment by jdubois** [comment]
Oh I'm not used to this kind of new stuff, but yes it could help to reuse this same code over several different tests.
You're such a hipster :-)

**Comment by gmarziou** [comment]
:-)

I remembered it from an article about using @Rule to start a docker container before running tests.

**Comment by cbornet** [comment]
Could we use @Rule to start the embedded cassandra ?

**Comment by jdubois** [comment]
Yes, in fact this is what we did for a client something like 1 year ago.
We had some great improvements over the "normal" Cassandra Unit, I need to
ask my coworker @jxerome if he would be OK to do this.
Le 24 févr. 2016 7:29 AM, "Christophe Bornet" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
anyone doing this?

**Comment by lordlothar99** [comment]
Hi all
I just saw the one @geraldhumphries described, it's just copy/paste to add it to generator ; I can do it if you don't have time to.

I recently had some issues with db/es desynchronization...so I added some tests in my own projects.
Maybe it would be useful to include them too ; in every `createEntity()`, `updateEntity()` and `deleteEntity()` methods, just to ensure data is identical in search repository.

By the way, I haven't faced any performance issue with `deleteIndex(Entity.class)`, or `searchRepository.deleteAll()` call in the `@Before` annotated method (32ms on my computer)...
I can propose a PR if u want ?

**Comment by geraldhumphries** [comment]
@lordlothar99 go ahead. If there are really no performance impacts then it should be okay, but I bet it depends on your computer. I have only tested on an HDD, are you maybe using an SSD?

**Comment by lordlothar99** [comment]
yes I got a SSD... well, let's try with a first version, and then we'll see if it's fast enough on any machine

**Comment by lordlothar99** [comment]
I created PR #3168 and tests are ok, but some jobs are failed (Cannot find module 'phantomjs-prebuilt') ; seems like that's nothing to do with my changes -> in my opinion the PR is ok

**Comment by deepu105** [comment]
closed via #3168

**Comment by lordlothar99** [comment]
Hi all. I recently created some additional tests on my side, and I randomly face some `org.elasticsearch.indices.IndexAlreadyExistsException: [xxx] already exists` exceptions during context load, due to `elasticsearchTemplate.createIndex(entityClass);` calls...
And as @geraldhumphries said, time for reset is annoyingly increasing build time...
@geraldhumphries suggestion works fine for me : use only 1 bean which invokes `elasticsearchTemplate.deleteIndex("_all");` instead of 1 bean per entity. 
I could submit a (last) PR soon...

**Comment by lordlothar99** [comment]
PR #3231 created. tests ok on my computer
