### ISSUE TITLE
Why doesnt appears new releases of jhipster the last is 9 months ago: Release 7.9.3 (2022-09-02)  We need update to new SpringBoot versions with jhipster We need update to new SpringBoot versions with jhipster  Thank yoy very much .

### ISSUE THREAD

**Issue by javachavez** [jhipster/generator-jhipster#22470]
Why doesnt appears new releases of jhipster the last is 9 months ago: Release 7.9.3 (2022-09-02) 

 We need update to new SpringBoot versions with jhipster We need update to new SpringBoot versions with jhipster  Thank yoy very much .

**Comment by mraible** [comment]
The reason there are no new releases is that it's been difficult to upgrade to Spring Boot 3 and to do many refactorings to make the core generator more module. We are close, though, so I'm closing this issue. You can see from the mailing list message I sent earlier this week that we're very motivated to make a new release happen soon.

https://groups.google.com/g/jhipster-dev/c/L6ggD0pIoYQ
