### ISSUE TITLE
Refactor to use UPPER_SNAKE_CASE naming convention for angular translation keys

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2247]
Angular translate mostly uses UPPER_SNAKE_CASE naming conventions for translations keys in their examples. Maybe this is a personal opinion but it reads much better than the current snakeCase convention used today and it makes it easier to distinguish them from the scope variables as well.

@jdubois 
How come JHipster uses camelCase as naming convention? Would a PR to change the keys to UPPER_SNAKE_CASE be welcome?

**Comment by deepu105** [comment]
wouldnt that be hell lot of json files to refactor?

**Comment by gzsombor** [comment]
+ a hell lot of html as well !

**Comment by deepu105** [comment]
i dont know if it will bring any values and also since we are using json to store keys it will look weird having snake_case keys all over it and using something like `ENTITY.ACCOUNT_INFO.MENU.USER_PASSWORD` with snake case and dot notation, so i dont know if its worth the effort

**Comment by andidev** [comment]
Okey, I'm closing this theb
