### ISSUE TITLE
Browser error 'A non-serializable value was detected' in a React app using Redux Toolkit and Axios

### ISSUE THREAD

**Issue by hide212131** [jhipster/generator-jhipster#22490]
##### **Overview of the issue**

In a React app using Redux Toolkit, a browser error stating 'A non-serializable value was detected' appears during server calls made with Axios.

<img width="755" alt="axios-error" src="https://github.com/jhipster/generator-jhipster/assets/3602892/80b5e179-a4e5-442d-8ee5-c0a1b28d94c7">

> redux-toolkit.esm.js:471 A non-serializable value was detected in an action, in the path: `payload.headers`. Value: AxiosHeaders 

This issue consistently occurs when a 'fulfilled' action, such as 'authentication/get_account/fulfilled', is dispatched in Redux.

##### **Motivation for or Use Case**

While this is not resulting in direct malfunction, it does cause confusion for the developer.

##### **Reproduce the error**

Start React app.

##### **Related issues**

#22483

##### **Suggest a Fix**

Under investigation

##### **JHipster Version(s)**
- The issue is present in the React app generated by the main branch (7.10.0)
- This issue does not appear in version 7.9.3.

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "applicationType": "monolith",
  "authenticationType": "jwt",
  "baseName": "myApp",
  "buildTool": "maven",
  "cacheProvider": "ehcache",
  "clientFramework": "react",
  "clientTheme": "none",
  "creationTimestamp": 1686372694068,
  "databaseType": "sql",
  "devDatabaseType": "h2Disk",
  "devServerPort": 9060,
  "dtoSuffix": "DTO",
  "enableGradleEnterprise": null,
  "enableHibernateCache": true,
  "enableSwaggerCodegen": false,
  "enableTranslation": true,
  "entities": [],
  "entitySuffix": "",
  "gradleEnterpriseHost": null,
  "jhiPrefix": "jhi",
  "jhipsterVersion": "7.10.0",
  "languages": [
    "ja",
    "en",
    "fr"
  ],
  "messageBroker": false,
  "microfrontend": false,
  "microfrontends": [],
  "nativeLanguage": "ja",
  "packageFolder": "com/mycompany/myapp",
  "packageName": "com.mycompany.myapp",
  "pages": [],
  "prodDatabaseType": "postgresql",
  "reactive": false,
  "searchEngine": false,
  "serverPort": null,
  "serverSideOptions": [],
  "serviceDiscoveryType": false,
  "skipCheckLengthOfIdentifier": false,
  "skipClient": false,
  "skipFakeData": false,
  "skipUserManagement": false,
  "testFrameworks": [],
  "websocket": false,
  "withAdminUi": true
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

git version 2.39.2 (Apple Git-143)

node: v18.14.2
npm: 9.5.0

Docker version 23.0.5, build bc4487a

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by hide212131** [comment]
The `AxiosHeaders` is a class, which is why it's non-serializable. 

[Do Not Put Non-Serializable Values in State or Actions](https://redux.js.org/style-guide/#do-not-put-non-serializable-values-in-state-or-actions)
> Avoid putting non-serializable values such as Promises, Symbols, Maps/Sets, functions, or class instances into the Redux store state or dispatched actions.

The solution seems to be adding 'headers' to the already existing [ignoredActionPaths](https://redux-toolkit.js.org/api/serializabilityMiddleware#:~:text=meta.baseQueryMeta%27%5D%0A%20%20%20*/-,ignoredActionPaths,-%3F%3A%20) . 

I'll submit a PR.

**Comment by Gautam-Ranpariya** [comment]
A non-serializable value was detected in an action, in the path: `payload`. Value: AxiosError {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …} 
Take a look at the logic that dispatched this action:  {type: 'auth/alreadyUser/fulfilled', payload: AxiosError, meta: {…}} 
(See https://redux.js.org/faq/actions#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants) 
(To allow non-serializable values see) 

how to solve this error ?
