### ISSUE TITLE
Allow Map<String,String> on Entity Generator

### ISSUE THREAD

**Issue by Panthro** [jhipster/generator-jhipster#2250]
Hey guys

One of the things I use a lot on JPA2 is the Map mapping, because it makes it very easy to make your entity more flexible when it can vary and have `attributes`.

What I usually do is:
Giving entity `Example` and field `attributes`.

```java
    @ElementCollection
    @MapKeyColumn(name="name")
    @Column(name="value")
    @CollectionTable(name="example_attributes", joinColumns=@JoinColumn(name="example_id"))
    private Map<String, String> attributes = new HashMap<>();
```

I don't know how this would fit into the Angular app, but sure it would be a nice to have.

**Comment by deepu105** [comment]
This is a very rare use case and I dont think we will be adding this. You can easily add this yourself in generated entity also I dont see how this can be used in the angular side as you mentioned.

**Comment by Panthro** [comment]
I always knew that, just added the issue as a `feature request` just in case many people get to it and find it useful.

BTW, the `liquibase:diff` does not work with this, I had to debug the execution to find that it was throwing a NPE because it was trying to create a primary key for the new table and the primary key name was null.

**Comment by gmarziou** [comment]
Have you reported this issue to the liquibase project?

**Comment by Panthro** [comment]
just for the sake of traceability:

Created the issue because I'm facing this again:

https://github.com/liquibase/liquibase-hibernate/issues/101
