### ISSUE TITLE
Failed to load entities

### ISSUE THREAD

**Issue by eiposgi** [jhipster/generator-jhipster#22518]
##### **Overview of the issue**

Having `Failed to load gateway entities` in Entities UI menu.

##### **Motivation for or Use Case**

Normally Entities menu displays list of loaded entities which can be clicked and used. 

##### **Reproduce the error**

1. Install Jhipster v8.0.0-beta.1
2. Generate a microservice app, and some entity
3. Generate a gateway app, and use generated entity in a microservice app
4. Generate docker-compose launch scripts.
5. Launch docker-compose
6. Open the UI and observe Entities menu, it shows `Failed to load entities` text.

##### **Related issues**

Haven't found.

##### **JHipster Version(s)**

v8.0.0-beta.1
Just before this version i used 7.9 and Entities were showing withouth issues

##### **JHipster configuration**

{
  "generator-jhipster": {
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "baseName": "gateway",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientTheme": "none",
    "creationTimestamp": 1686533768907,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": null,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": ["Product"],
    "entitySuffix": "",
    "gradleEnterpriseHost": null,
    "jhiPrefix": "jhi",
    "jhipsterVersion": "8.0.0-beta.1",
    "jwtSecretKey": "NzEwYmJlMjcxM2M0NmZhYThhN2JmYzZmYTlhNDJkY2U4YzAxYTc4Y2UwNjkzZjgxNGY5N2I2M2Y5OGE2YjY1N2I0YjM4NGNkYjAzNzhlOTVjMTI2NzE5NmJiODQyOGUwZDI5MTQ2OWEyNmI4Mjk1YWI2YzdiZWM1ZDZkYjNkZDU=",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "microfrontend": true,
    "microfrontends": [
      {
        "baseName": "gateway"
      },
      {
        "baseName": "warehouse"
      }
    ],
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": true,
    "searchEngine": false,
    "serverPort": 8080,
    "serverSideOptions": [],
    "serviceDiscoveryType": "consul",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipFakeData": false,
    "skipUserManagement": true,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Product.json
{
  "clientRootFolder": "warehouse",
  "databaseType": "sql",
  "dto": "mapstruct",
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    },
    {
      "fieldName": "desc",
      "fieldType": "String"
    }
  ],
  "jpaMetamodelFiltering": false,
  "microserviceName": "warehouse",
  "microservicePath": "../warehouse",
  "pagination": "infinite-scroll",
  "readOnly": false,
  "relationships": [],
  "service": "serviceImpl"
}

##### **Browsers and Operating System**

Chrome Browser Version 114.0.5735.106 (Official Build) (64-bit)
Ubuntu 22.04

**Comment by mshima** [comment]
The configuration is incorrect.
