### ISSUE TITLE
JHipster timezone configuration fails with hibernate 6.2.x.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#22579]
##### **Overview of the issue**

Upgrading hibernate to v6.2.x breaks https://github.com/jhipster/generator-jhipster/blob/main/generators/spring-data-relational/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs.

##### **Reproduce the error**

Reproducing may depend on system timezone.
```
jhipster --defaults --skip-install
<update to hibernate 6.2.x at pom.xml or build.gradle>
<set config `hibernate.timezone.default_storage=NORMALIZE_UTC`>
npm run backend:unit:test
```

##### **Related issues**

Looks related to https://hibernate.atlassian.net/browse/HHH-16778

##### **Suggest a Fix**

Keep hibernate at v6.1.7 as workaround.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Increasing bug bounty as it would be nice to support Hibernate 6.2 in 8.0 GA.

**Comment by anarsultanov** [comment]
Please take a look at the proposed fix https://github.com/jhipster/generator-jhipster/pull/22946
