### ISSUE TITLE
Can't read swagger JSON

### ISSUE THREAD

**Issue by rreitmann** [jhipster/generator-jhipster#2259]
Hi,

we have just created a new JHipster app and deployed it to Pivotal Web Services. If I access https://metadatamanagement.cfapps.io/swagger-ui/index.html it does not allow me to test the Rest API.

Are there any known limitations?

Our generator choices can be found [here](https://github.com/dzhw/metadatamanagement/blob/master/.yo-rc.json).

**Comment by deepu105** [comment]
Have you deployed with prod profile? Swagger works only in dev profile

**Comment by gmarziou** [comment]
swagger spec file is not available using production profile.

**Comment by gmarziou** [comment]
@deepu105 you're too fast ;)

**Comment by rreitmann** [comment]
Thx, you both were fast :-)

And yes I have deployed with the prod profile. I was not aware of the fact that swagger is supposed to be used only with the dev profile.

**Comment by gmarziou** [comment]
Reason is that swagger-ui index.html is difficult to adapt to all authentication schemes JHipster supports, so we decided to unprotect the spec file and for this reason we did it only in dev profile as it may not be appropriate for all apps to open up their API spec.

If you want to change it, it's easy: just remove the annotation in SwaggerConfiguration

   @Profile("!"+Constants.SPRING_PROFILE_PRODUCTION)
   public class SwaggerConfiguration
