### ISSUE TITLE
Suggestion: migrate from UUIDs to nanoids

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#22605]
##### **Overview of the feature request**

Nanoids use a bigger alphabet than UUIDs, thus you can have more different ids with less bytes used.
Also, they don't allow tracing back generation timestamp or mac address which IIRC is possible with UUIDv4. Especially the timestamp part could be a privacy issue in quite a lot of cases.

See this library for example: https://github.com/ai/nanoid

For backwards compatibility, UUIDs should of course still be available

##### **Motivation for or Use Case**

See above 

##### **Related issues or PR**

Searching for "nanoid" in the repos issues did not yield any such request

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Thanks for the idea! A PR is welcome.

**Comment by CodingSpiderFox** [comment]
Probably won't find time to continue my contributions for the next 2 weeks but after that I am excited to continue them

**Comment by gmarziou** [comment]
@CodingSpiderFox you're pointing to nanoids which is a js lib, does it mean that you would like to generate the ids client-side?

**Comment by atomfrede** [comment]
I have found at least a psql extension to have a dedicated column type like UUID. There is also a java version of the lib but in general it seems like "client" side (java client at least)

**Comment by CodingSpiderFox** [comment]
Yes, that would require client side generation

**Comment by CodingSpiderFox** [comment]
https://github.com/aventrix/jnanoid looks promising

**Comment by gmarziou** [comment]
Well generating the ids in browser would impact non browsers clients of our APIs including inter-services call, that's a major drawback in my opinion..

jnanoid has not evolved for last 5  years, so either it's perfect or it's abandoned :)

Vlad Mihalcea has a good article about TSID https://vladmihalcea.com/uuid-database-primary-key/

**Comment by CodingSpiderFox** [comment]
A common issue with time sortable uuids is that the reader might be able to derive the entity creation date form the ID which can be a privacy issue in many cases

**Comment by CodingSpiderFox** [comment]
@atomfrede well, the lib itself looks ok, there is a fork of a person who upgraded it to Java 17. maybe we can build on top of that.

**Comment by gzsombor** [comment]
That library just generates random strings, so it is not comparable storing a compact UUID, which needs only 16 bytes of storage. Probably you don't need to change the backend at all, just set the PK to String...

**Comment by CodingSpiderFox** [comment]
@gzsombor if I understood correctly, not all database systems store the uuids as a dedicated uuid data type. When you have to store uuidv4 as string it takes a lot more than 16 bytes.
Nanoid helps a lot there

**Comment by CodingSpiderFox** [comment]
> I tend not to put this into the main generator as the maintenance burden is quite high and I also think the java lib is not in good shape.

What other possibilities can we allow? Does JHipster allow writing some kind of plugins or so?

**Comment by atomfrede** [comment]
You can do a [blueprint](https://www.jhipster.tech/modules/extending-and-customizing/). Not sure how stable the api is right now with jhipster 8 around the corner. But with a blueprint it is possible to modify only whats needed for the specific use case without the need to have it in the main generator. It would also be no issue to have just partial support (e.g. only angular + jpa) inside a blueprint. For example the [native blueprint ](https://github.com/jhipster/generator-jhipster-native) only works with certain subset of options.

**Comment by deepu105** [comment]
I don't think the advantage is worth the maintenance burden and complexity, so ofcourse a blueprint would be ideal
