### ISSUE TITLE
Replace nested DTOs with Long field for id usage in JSON body

### ISSUE THREAD

**Issue by hienhoang272** [jhipster/generator-jhipster#22644]
##### **Motivation for or Use Case**

I noticed that all DTO classes are nested inside another DTO class, for example, FileDTO contains FolderDTO, but only the id field of FolderDTO is used in both request and response. Therefore, I suggest replacing all FolderDTO occurrences with a Long folderId field to make the JSON body in requests and responses more concise and easier to read, especially when DTO classes have many nested fields.

##### **Related issues or PR**

Using Long folderId instead of FolderDTO folder will simplify the JSON body in requests and responses, making it easier to understand and debug. It will also reduce unnecessary data transfer and improve performance. Moreover, it will make DTO classes more flexible and easier to manage, as they will not be tightly coupled with other DTO classes.

I could not find any related issues or pull requests regarding this feature request.
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
This was JHipster v6 implementation.
Having dto api similar to non-dto makes overall implementation much simpler.
