### ISSUE TITLE
Setting Java_Home

### ISSUE THREAD

**Issue by skin27** [jhipster/generator-jhipster#22657]
When I run the generator I get the following warning:

Error: JAVA_HOME not found in your environment.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

My JAVA_HOME is set JAVA 11 (as this is the default version we use in the company). I have other Java version (including Java 17) on my machine. When developing I use the toolchain file in Maven. Than in my pom file I have:

```xml
				<plugin>
					<artifactId>maven-toolchains-plugin</artifactId>
					<version>3.1.0</version>
					<executions>
						<execution>
							<goals>
								<goal>toolchain</goal>
							</goals>
							<configuration>
								<toolchains>
									<jdk>
										<version>17</version>
									</jdk>
								</toolchains>
							</configuration>
						</execution>
					</executions>
				</plugin>
```

Maybe it's good that the generator ask me where the location of my Java 17+ is and then I can provide that location or that I can say I use the toolchain (not support by the wrapper?) Of course I work around through manually set the JAVA_HOME in the cmd or on the command line, but I think there maybe good be a more interactive way to ask the user for the java home.

**Comment by mraible** [comment]
I don't think we should prompt for and hard-code a JAVA_HOME location in the app. This will make it non-portable between developer machines and operating systems.
