### ISSUE TITLE
Support "-v" as alternative command line argument for "--version"

### ISSUE THREAD

**Issue by skin27** [jhipster/generator-jhipster#22656]
Consider the following:

D:\intellij\workspace>java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

D:\intellij\workspace>npm -v
9.5.1

D:\intellij\workspace>jhipster --version
8.0.0-beta.1

D:\intellij\workspace>jhipster -v
error: unknown option '-v'

I think that -v as a short form of --version is very common. Maybe support that command line option as well as alternative to the --version.

**Comment by mraible** [comment]
I don't think this is necessary. Java supports --version now and supporting its old -version seems like we'd be going backward.

**Comment by skin27** [comment]
I don't ask to support -version (that was just an example on how people try to get the version when they have a Java background). The feature request was to support "-v" as a short version of "--version".

It's very common that one minus with letter is the short form of two minus signs with a descriptive word.

**Comment by mraible** [comment]
Makes sense. Re-opening to add a `-v` option.

**Comment by mshima** [comment]
Commander default is [-V](https://github.com/tj/commander.js#version-option) if there is no objection PR is welcome

**Comment by deepu105** [comment]
To me this is extremely low priority so feel free to contribute this as a PR. Originally when I wrote the CLI there was some issue with using `-v` due to some conflict with `verbose` or something but that was ages ago.
