### ISSUE TITLE
Add social login to existing jHipster app?

### ISSUE THREAD

**Issue by jahu** [jhipster/generator-jhipster#2265]
I am in the middle of the development of jHipster app and I've just realized you've finally merged Social Login (thanks and congrats! I was planing to do it bymyself :)). Nevertheless - can I somehow add this feature to my existing application or I must generate new app and do merge?

**Comment by gzsombor** [comment]
You can re-generate your app, executing yo jhipster inside your application root folder. But you have to remove the node_modules/generator-jhipster directory before (because it contains the old generator code), and have an up-to-date generator locally. Or wait until the a new version is released

**Comment by cbornet** [comment]
Also, don't forget to regen your entities
```
yo jhipster --force && for f in `ls .jhipster`; do yo jhipster:entity ${f%.*} --force ; done
```

**Comment by deepu105** [comment]
Thats cool @cbornet can you add it in documentation

**Comment by cbornet** [comment]
@deepu105  Yes, I can add it as a tip maybe. Or do you see another place ?

**Comment by deepu105** [comment]
I guess it can go into the documents page for entity

**Comment by deepu105** [comment]
for windows `yo jhipster --force && for %f in (.jhipster/*) do yo jhipster:entity %f --force`

**Comment by deepu105** [comment]
@cbornet are you adding this?

**Comment by cbornet** [comment]
Yes. I'll try to do it today
