### ISSUE TITLE
Error loading component

### ISSUE THREAD

**Issue by skin27** [jhipster/generator-jhipster#22655]
##### **Overview of the issue**

After login in, I have the menu entry "Entities" in the 8.0 beta1. But there it only shows "Error loading component". There are no error (both in the browser console or in the application log). I see this at the main page:

![Error_Loading_Component](https://github.com/jhipster/generator-jhipster/assets/23716892/07b003be-a186-44bc-9012-520179544a3b)

##### **Reproduce the error**

Login and go to "Entities"

##### **JHipster Version(s)**

8.0 beta1

##### **JHipster configuration**

{
  "generator-jhipster": {
    "applicationType": "gateway",
    "authenticationType": "jwt",
    "baseName": "gateway",
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "react",
    "clientTheme": "none",
    "creationTimestamp": 1687526845741,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": null,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [],
    "entitySuffix": "",
    "gradleEnterpriseHost": null,
    "jhiPrefix": "jhi",
    "jhipsterVersion": "8.0.0-beta.1",
    "jwtSecretKey": "YTFhY2FhNGUwZmUyOTIyOWNjMThlODhiOGFmN2ZhNjg4MDA3ZDU3ODIwMTYzMjhhY2RjNTc4N2ZhMGYxMDMyOWNlOGNkZTRhNmE3YjYxYjhiYjA4ZjZkYzUzZDY1ODlmNzQ5ZmUyY2IyNDE0NjBjZmNjYzVhYjgwN2EyNDVjNWE=",
    "messageBroker": false,
    "microfrontend": true,
    "microfrontends": [
      {
        "baseName": "manager"
      },
      {
        "baseName": "designer"
      }
    ],
    "nativeLanguage": "en",
    "packageFolder": "org/assimbly/gateway",
    "packageName": "org.assimbly.gateway",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": true,
    "searchEngine": false,
    "serverPort": "8081",
    "serverSideOptions": [],
    "serviceDiscoveryType": "consul",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities

##### **Browsers and Operating System**

OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
System Model	Precision 5570
System Type	x64-based PC
Processor	12th Gen Intel(R) Core(TM) i7-12700H, 2300 Mhz, 14 Core(s), 20 Logical Processor(s)
Java: Eclipse Temurin 17.0.7
JHipster: 8.0.0-beta.1

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Have you enable microfrontend on purpose?

**Comment by skin27** [comment]
Partly, I want to play with the microfrontend approach later on to investigate if this will be a viable option when we are moving to JHipster 8. It's thus to investigate to have microfrontends (frontend), microservices (backend) + gateway + consul.

I'm currently not really aware what the question "Do you want to enable microfrontends?" mean. (default is Y). It's asked both for the gateway and for a microservice. Microfrontend is not available as an "application". Is the microfrontend a type of microservice or is it part of the gateway project? Not clear yet.

**Comment by mshima** [comment]
> I'm currently not really aware what the question "Do you want to enable microfrontends?" mean. (default is Y)

Should have been false.

> . It's asked both for the gateway and for a microservice. Microfrontend is not available as an "application". Is the microfrontend a type of microservice or is it part of the gateway project? Not clear yet.

Both should be supported by gateways and microservices.

https://github.com/jhipster/generator-jhipster/pull/22659 should set default answer to false and don't to detect microfrontends.

**Comment by mshima** [comment]
`Error loading` means it failed to load entities ui from microservices.

**Comment by skin27** [comment]
OK, as I understand it right now, I can create two microservices that act as a microfrontend and when available will be detected (auto-discovery) by consul and then available within the gateway. Is this correct?

**Comment by mshima** [comment]
The discovery part is not correct.
Microfrontends are not auto-detected.
Microfrontends are specified:
https://github.com/jhipster/generator-jhipster/blob/61ec0be217e40fa96c944bdc624921efb5104bb6/test-integration/jdl-samples/ms-mf-react-eureka-oauth2-mariadb-infinispan/blog-store.jdl#L33

It should be possible to advertise that a microservice contains microfrontends and auto-discover.
But it’s fixed right now.
