### ISSUE TITLE
A diagram on the online JDL-studio isn't usable

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#22666]
##### **Overview of the issue**

A diagram on the online JDL https://start.jhipster.tech/jdl-studio/ isn't usable. It is impossible to identify entities in a real-world situation (see the attached screenshot).

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vw98075** [comment]
![Screenshot_select-area_20230624211357](https://github.com/jhipster/generator-jhipster/assets/10793038/f2ac368e-e827-4029-9937-d09781e8360d)

**Comment by mraible** [comment]
Can you please try the JDL plugin for IntelliJ and see if that works better?

https://plugins.jetbrains.com/plugin/19697-jhipster-jdl/spa/spa/aggregate

**Comment by deepu105** [comment]
can you provide the JDL used otherwise impossible to check

**Comment by vw98075** [comment]
The default sample already shows the issue.
![Screenshot_select-area_20230629114534](https://github.com/jhipster/generator-jhipster/assets/10793038/27cf632a-1137-49c4-b447-e6d8bd26dfe8)

BTW, I have tried the plug-in on the Idea but can't figure out how to turn a JDL file to a diagram.

**Comment by deepu105** [comment]
I dont see any issues on latest version of Chrome or Firefox. If you find any issue specific to brave, feel free to open a PR with the fix
