### ISSUE TITLE
Elasticsearch automatic build is broken

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2268]
See https://drone.io/github.com/jhipster/jhipster-sample-app-elasticsearch/26

I think this comes from #2249 so I'm affecting this to @cbornet

**Comment by cbornet** [comment]
Oops ! Sorry about that ! (Voting +1000 for travis matrix on PRs... )

**Comment by jdubois** [comment]
And the build is green again, thanks!
