### ISSUE TITLE
[Windows only] "Error parsing custom command" in blueprints using 8.0.0-beta.1

### ISSUE THREAD

**Issue by sinedied** [jhipster/generator-jhipster#22728]
##### **Overview of the issue**

**This error occurs only on Windows, using Linux or Mac works fine.**

Blueprints that have a generate with an associated commands fail to run on Windows when invoked using the generated CLI.

##### **Reproduce the error**

Create a new blueprint with `jhipster generate-blueprint` and these settings:

```json
{
  "generator-jhipster": {
    "additionalSubGenerators": "",
    "baseName": "my-blueprint",
    "cli": true,
    "entities": [],
    "generators": {
      "base": {
        "command": true,
        "priorities": ["prompting", "writing", "end"],
        "sbs": false,
        "written": true
      }
    },
    "jhipsterVersion": "8.0.0-beta.1",
    "localBlueprint": false,
    "skipCommitHook": true,
    "subGenerators": ["base"]
  }
}
```

After the installation is complete, run `npm link` then `jhipster-my-blueprint --help` results in this error:

```
INFO! Error parsing custom commands found within blueprint: my-blueprint at C:\Users\sinedied\Documents\projects\my-blueprint/cli/commands.cjs        
```

The custom commands is then not listed on the printed help. Invoking it doesn't work either.

The same steps on a Mac or Linux machine works fine.

##### **JHipster Version(s)**

8.0.0-beta.1

No issues with the previous 7.x version, so it's a regression.

##### **JHipster configuration**

Note: I reproduced the issue in a fresh Windows VM with a minimal install (not my usual work config as I'm on Mac).

```
{
  "additionalSubGenerators": "",
  "baseName": "my-blueprint",
  "cli": true,
  "entities": [],
  "generators": {
    "base": {
      "command": true,
      "priorities": [
        "prompting",
        "writing",
        "end"
      ],
      "sbs": false,
      "written": true
    }
  },
  "jhipsterVersion": "8.0.0-beta.1",
  "localBlueprint": false,
  "skipCommitHook": true,
  "subGenerators": [
    "base"
  ]
}
</pre>
</details>


##### **Environment and Tools**

'java' command could not be found

git version 2.41.0.windows.1

node: v18.15.0
npm: 9.5.0

Docker version 24.0.2, build cb74dfc

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

    force .yo-rc.json

Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Sponsored with ❤️  by @oktadev.
```

##### **Browsers and Operating System**

Errors happens on Windows 11.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by hangwan97** [comment]
I would like to ask if there is any update on this issue.
Given the large amount of Windows users, this may issue may block a fair amount of users to access Jhipster's new features.

**Comment by mraible** [comment]
I've added a bug bounty to help get this fixed.

**Comment by DanielFran** [comment]
@mshima approved
