### ISSUE TITLE
Docs: Prefer [ci skip] in the footer instead of the header

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#22739]
##### **Overview of the issue**

I made a PR and did not 100% correctly follow the Contributing guideline - sorry for that. Just quickly read the lines that mentioned `[ci skip]` should be used for documentation only changes.

##### **Motivation for or Use Case**

It is common practice to limit header line length in git commit messages to 50 chars.
Including `[ci skip]` in the header already takes 9 characters which is almost 20 percent of that 50 chars.
This way it is too hard to write good header lines.

Also, when later looking at the git history, most users would be interested in what change and why that change was made in a certain commit.
The fact that the CI was ignored for that commit is not often relevant (while sometimes it might still be a valuable information)

Also, the current official GitHub documentation does not require the `[ci skip]` in the header. If I understand it correctly, ` [ci skip]` can be used anywhere in the message. 
The documentation also mentions a way to specify it in the commit message footer.
```
Workflows that would otherwise be triggered using on: push or on: pull_request won't be triggered if you add any of the following strings to the commit message in a push, or the HEAD commit of a pull request:

    [skip ci]
    [ci skip]
    [no ci]
    [skip actions]
    [actions skip]

Alternatively, you can end the commit message with two empty lines followed by either:

    skip-checks:true
    skip-checks: true

You won't be able to merge the pull request if your repository is configured to require specific checks to pass first. To allow the pull request to be merged you can push a new commit to the pull request without the skip instruction in the commit message.
```

##### **Reproduce the error**

See #22738

##### **Related issues**

Couldn't find one for "ci skip" as search term.

##### **Suggest a Fix**

Change documentation from 
```
If the commit only involves documentation changes you can skip the continuous integration pipelines using [ci skip] or [skip ci] in your commit message header.
```

to

```
If the commit only involves documentation changes you can skip the continuous integration pipelines using [ci skip] or [skip ci] in your commit message footer (very last line of the commit message).
```

##### **JHipster Version(s)**

Commit 1626a09

##### **Browsers and Operating System**

elementaryOS 7

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
While we have those submission guidelines, I recommend the common sense.
Requiring to follow lengthy guidelines can be discouraging for contributors.
We have detection to trigger related CI.
