### ISSUE TITLE
Docs: Development setup instructions seem to be incomplete

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#22732]
##### **Overview of the issue**

I wanted to try the latest version of JHipster on my developer machine, so I cloned the repository at the default branch and followed the instructions in CONTRIBUTING.md:

> Run `npm link` and then run `npm ci` 

But already the first step failed because the typescript compiler `tsc` could not be found. I was able to fix that by running `npm i -g typescript`

I ran `npm link` again.

Then I got an error message that the node type definitions are not available. So I ran `npm i -g @types/node`.

Ran `npm link` again but got the same error message.

Then I ran `npm ci`. After that, running `npm link` succeeded.

##### **Motivation for or Use Case**

Even unexperienced developers should have an easy way to setup jhipster for contributing

##### **Reproduce the error**
See description above
##### **Suggest a Fix**

In the section `Set NPM to use the cloned project` in CONTRIBUTING.md, instruct the user to run `npm ci` before `npm link`. Currently, these instructions are mentioned in reverse order.

##### **JHipster Version(s)**
Commit 721e7996...
##### **JHipster configuration**
Not applicable
##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jelharou** [comment]
I confirm that changing the order of the execution of those 2 steps addressed the typescript related errors.  I had gone through the same process with the same errors and then repeated it with the new order and it was seamless.

**Comment by mraible** [comment]
Can you please create a PR to fix this in the `CONTRIBUTING.md` document? I'll add a bug bounty to help motivate.

**Comment by jelharou** [comment]
> Can you please create a PR to fix this in the `CONTRIBUTING.md` document? I'll add a bug bounty to help motivate.

Is the PR worth $100?  Can I split it with @CodingSpiderFox who raised the issue?

**Comment by DanielFran** [comment]
@jelharou do not worry, you can request the bug bounty and @CodingSpiderFox also
