### ISSUE TITLE
REST url /api/users is not secured to ADMIN users

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2274]
All user data can be through http://localhost:8080/api/users when any user is logged in with any role since the `@Secured(AuthoritiesConstants.ADMIN)` is not used on [UserResource.getAllUsers](https://github.com/jhipster/generator-jhipster/blob/4a696e9ea8a630ef8f3e7b1d559cfca5d4f1a50e/app/templates/src/main/java/package/web/rest/_UserResource.java#L145) method.

Feels like a big security/integrity issue

**Comment by jdubois** [comment]
This is copied on the Github API, in fact.

This is on purpose, as for many applications you will want to do something with your users.

Like Github, we ecpose logins, names, etc, but of course not the password. So there shouldn't be a risk (like Github, again).

It's easy to secure if you want to.

**Comment by andidev** [comment]
Okey, closing this theb
