### ISSUE TITLE
 .devcontainer for the JHipster generator repository itself to automatically install supported java and npm version when I want to contribute to JHipster

### ISSUE THREAD

**Issue by SandraAhlgrimm** [jhipster/generator-jhipster#22762]
To make contributions to the jHipster generator easier and to welcome more new contributors, having a devcontainer in the generator repo itself makes sense.

"I would also like a .devcontainer for the JHipster generator repository itself to automatically install supported java and npm version when I want to contribute to JHipster"

_Originally posted by @CodingSpiderFox in https://github.com/jhipster/generator-jhipster/issues/17612#issuecomment-1616670405_

**Comment by jdubois** [comment]
Oh that's great, yes let's do this with @SandraAhlgrimm (to be transparent: I'm Sandra's manager at Microsoft )

**Comment by atomfrede** [comment]
I know, that's why I pinged you :)

**Comment by SandraAhlgrimm** [comment]
sure, you can start this or I will @atomfrede

**Comment by mraible** [comment]
Adding a bug bounty since this seems like a nice feature to have.

**Comment by jdubois** [comment]
Thanks @mraible but if this is done by @SandraAhlgrimm I’m afraid this might rise a conflict of interest on the Microsoft side

**Comment by mraible** [comment]
@jdubois It looks like @mshima has started working on it in #22814. I'm not sure how complete it is.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/163438.

**Comment by DanielFran** [comment]
@mshima approved
