### ISSUE TITLE
getPaginationItemsNumber  funtion missing in 0.21.0

### ISSUE THREAD

**Issue by venkatnaveen7** [jhipster/generator-jhipster#22779]
Team
Im upgrading my version of react-jhipster from 0.7.0 to 0.21.0 but getPaginationItemsNumber is missing in the 0.21.0 version
Is this replaced by any other function, May I know where can I find some help

**Comment by mraible** [comment]
@mshima Can you please help with this issue?

**Comment by mshima** [comment]
`react-jhipster` version is specific to a jhipster version.
To use `react-jhipster@0.21.0` you need to regenerate the application. Not sure which jhipster version you need to use.

**Comment by venkatnaveen7** [comment]
found that  usage of getPaginationItemsNumber is no longer needed
we can use the totalItems instead of items prop as alternative like below
<JhiPagination
                          totalItems={totalItems}
                          itemsPerPage={pageSize}
                          activePage={pageIndex}
                          onSelect={handlePaginationCallback}
                          maxButtons={3}
                        />
