### ISSUE TITLE
[UX/angular] Allow view/edit in new tabs from list view

### ISSUE THREAD

**Issue by nitram84** [jhipster/generator-jhipster#22801]
##### **Overview of the issue**

With the current implementation (angular, jhipster 7.9.3/8.0.0-beta.1) it is possible to open an item from the list view in a new tab (use linked ID in ID column). In the new tab switching to edit mode an editing is possible.
But the view and edit function on the right side is implemented with buttons. Therefore is not possible to open or edit in new tabs items in this way. If you simply replace `<button submit="true" ... </button>` with `<a ... </a>`, working in tabs would be possible, even without layout changes.

Is there any reason why viewing and editing in new tabs is allowed on the left side and disallowed on the right side?

##### **Motivation for or Use Case**

A workflow where items could be opened and edited in new tabs would improve productivity, especially when items where filtered or sorted in list view. It would be possible to open all items to process in new tabs without loosing the filtered/sorted list/search result and to edit the items tab for tab.

##### **Reproduce the error**

Open list view of any entity. It is not possible to view/edit an item in a new tab with the buttons in the right side.

##### **Suggest a Fix**

Replacing the buttons with a link solves the problem.

##### **JHipster Version(s)**

7.9.3, 8.0.0-beta.1

##### **JHipster configuration**

No specific configuration needed. Just use angular and define at least one entity.

##### **Browsers and Operating System**

any

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Can you please create a PR to change to what you're proposing? That way, we can see if all CI tests pass or if further refinements need to be made. Please keep in mind that you might need to modify Angular, React, and Vue templates.
