### ISSUE TITLE
faker 8 phone.number broken

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#22811]
##### **Overview of the issue**

in prepare-field.mjs we have a list of field names to generate fake data
After upgrading to faker 8, some of these fields stopped working ex: phone.phoneNumber should be replaced by phone.number

##### **Motivation for or Use Case**

faker to work

##### **Reproduce the error**

try a jdl with a phone number

##### **Suggest a Fix**

replace and add tests for all types present in file

##### **JHipster Version(s)**

latest commit

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by yelhouti** [comment]
@qmonmert  @DanielFran  pinging the author and merger :D

**Comment by mshima** [comment]
Reproducible in daily builds.
