### ISSUE TITLE
Feature request: Update to Hibernate 5

### ISSUE THREAD

**Issue by wzomer** [jhipster/generator-jhipster#2281]
Any plans for this?

**Comment by cbornet** [comment]
It needs to be implemented in spring-boot first. See https://github.com/spring-projects/spring-boot/issues/2763

**Comment by jdubois** [comment]
And it's not supported by liquibase-hibernate yet (I did the ticket for that), so that's a huge blocker

**Comment by cm325** [comment]
Spring Boot 1.4 is at RC1, and Hibernate 5 changes are included. Any news on this feature request?

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4.0-RC1-Release-Notes

**Comment by jdubois** [comment]
Still blocked by Liquibase

**Comment by gmarziou** [comment]
It seems like we also need to update to [SpringFox 2.5.0](https://github.com/springfox/springfox/blob/master/docs/release-notes.md) to fix an issue with [Spring Boot 1.4](https://github.com/springfox/springfox/issues/1268)

**Comment by cm325** [comment]
This got closed, but I just upgraded to jhipster 3.6.1 and I still see hibernate 4?  Is this slated for a different future release?

**Comment by jdubois** [comment]
it's closed because we are blocked by Liquibase. The ticket is opened on their side.

**Comment by zulfahmi** [comment]
It seems that Liquibase Hibernate support Hibernate 5 now

**Comment by gmarziou** [comment]
Yes we know: https://github.com/jhipster/generator-jhipster/issues/4195
