### ISSUE TITLE
Font-Awesome support

### ISSUE THREAD

**Issue by BlackICE1979** [jhipster/generator-jhipster#2283]
I had to add this to my bower.json to make font-awesome work in my project :+1: 
```
    "overrides": {
    ....    
    "font-awesome": {
      "main": [
        "css/font-awesome.css",
        "scss/font-awesome.scss",
        "less/font-awesome.less"
      ]
     }
```
Should be specified somewhere in the documentation!

**Comment by lluiscanals** [comment]
I've made this question in stack over flow time ago and @jdubois answered it.

http://stackoverflow.com/questions/33088283/fontawesome-css-is-not-included-by-gruntfile

Agree to include in the documentation.

**Comment by BlackICE1979** [comment]
Yes thanks but your code misses the "-" in font-awesome.

Thanks!

Jean-François Morneau
Cellulaire: 418-805-0095

**Comment by lluiscanals** [comment]
I have it working without the "-" in font-awesome. Didn't work for you?

**Comment by atomfrede** [comment]
This would be great for the tips & tricks section.

**Comment by BlackICE1979** [comment]
No, it didn't work. I had to put exactly "font-awesome" for it to work.

**Comment by deepu105** [comment]
I have font awesome installed via bower working perfectly fine, what is the
problem here?

**Comment by jdubois** [comment]
It should be installed by Bower automatically, indeed. That's the whole point of using Bower, and that's why we don't include it by default.

**Comment by gmarziou** [comment]
@deepu105 it depends on what you use as CSS pre-processor. Font awesome [bower.json](https://github.com/components/font-awesome/blob/master/bower.json) 'main' property does not include LESS file only SCSS and CSS. So if you use LESS, you may want to include font-awesome.less in jhipster's 'bower.json` overrides property. If you use only CSS, you may want to exclude font-awesome.scss. This is why a generic solution would be sub optimal.

**Comment by deepu105** [comment]
But im using fontawesome 4.1 with less and i didn't do any of these and it
works

**Comment by BlackICE1979** [comment]
True, I use "less" and followed the directives in the tips&sticks section. Maybe it broke the default inclusion of font-awesome? I also use a wrapbootstrap template so I removed completely the main.css included with JHipster to migrate to the less files of the template.

**Comment by jdubois** [comment]
OK, from my understanding this works with the default build, so that's fine for me. Maybe we could add more tips for people using Less? I'm not using it and I don't really know what's needed, so @BlackICE1979 if you want to add or improve a tip for this, it's more than welcome!

**Comment by TonyLuo** [comment]
@BlackICE1979 I have changed bower.json, it  worked in dev model, but it didn't work in prod model. when run the application, the font-awesome icon didn't show.

**Comment by antonevane** [comment]
@TonyLuo Have you  found a solution. I have the same issue with `prod` profile.

**Comment by lluiscanals** [comment]
You have to include this part in gruntfile,

copy: {
            fonts: {
                files: [{
                    expand: true,
                    dot: true,
                    flatten: true,
                    cwd: 'src/main/webapp',
                    dest: '<%= yeoman.dist %>/assets/fonts',
                    src: [
                      'bower_components/bootstrap/fonts/*.*',
                      'bower_components/fontawesome/fonts/*.*'
                    ]
                }]
            },

Tell me if you have more problems.

**Comment by antonevane** [comment]
@lluiscanals thanks for hint, I had similar in my the Grunt.js and I found typo.
