### ISSUE TITLE
Issue with gradle and spoltless

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#22840]
##### **Overview of the issue**

With 8.0.0-beta1 and gradle when I run `gradlew build` I get an error.

Reason: Task ':spotlessJava' uses this output of task ':compileJava' without declaring an explicit or implicit dependency

Workaround/fix:

compileJava.dependsOn spotlessJava

But I would rather not run these kind of tasks (linting) whenever i want to compile, but run them only before running tests.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@CodingSpiderFox Can you take a look at this issue?

**Comment by CodingSpiderFox** [comment]
Unfortunately not until at least Monday

Matt Raible ***@***.***> schrieb am Mi., 12. Juli 2023, 15:47:

**Comment by atomfrede** [comment]
It sounds strange, I can't remember having this dependency in some projects of mine. And it doesn't make sense, why should spotless java depend on the compiled classes? Will try to have a look, maybe some configuration we are doing impacts the spotless configuration (e.g. some code gen)?

**Comment by atomfrede** [comment]
Seems related: https://github.com/diffplug/spotless/issues/1572

**Comment by atomfrede** [comment]
@jhipster/developers Again my development setup is not working (not sure why). I get this error, anyone has seen this? Using node 18, did an npm ci and npm link on the generator. It seems to have set the correct symbolic links

`
ERROR! ERROR! Named export 'IngressTypes' not found. The requested module './kubernetes-platform-types.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from './kubernetes-platform-types.js';
const { IngressTypes: ingressTypes } = pkg;

file:///Users/frederik.hahne/git/github/jhipster/generator-jhipster/dist/jdl/jhipster/index.mjs:30
export { IngressTypes as ingressTypes } from './kubernetes-platform-types.js';
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'IngressTypes' not found. The requested module './kubernetes-platform-types.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from './kubernetes-platform-types.js';
const { IngressTypes: ingressTypes } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
`

**Comment by mshima** [comment]
@atomfrede is your source tree clean?
The error indicates you have an outdated package.json inside `jdl` or `dist/jdl`.

**Comment by mraible** [comment]
I just updated my main branch and ran the following commands:

```
rm -rf node_modules dist
npm i
npm link
```

I didn't get any errors.

**Comment by atomfrede** [comment]
Thanks. I remove node_modules, but did not remove dist, seems like that has fixed it. Thanks.
