### ISSUE TITLE
Relationship Options Lead to Syntax Error

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#22841]
##### **Overview of the issue**

Steps:

1. On the JDL online studio, select the default sample.

2. Copy 

@OnDelete("SET NULL") @OnUpdate("CASCADE") 

from
```
relationship ManyToOne {
   A to @OnDelete("SET NULL") @OnUpdate("CASCADE") B
}
``` 
on the JDL document https://www.jhipster.tech/jdl/relationships and paste it to
```
relationship ManyToOne {
	Employee{manager} to Employee
}
```
in the default sample and results in the following
```
relationship ManyToOne {
	Employee{manager} to @OnDelete("SET NULL") @OnUpdate("CASCADE") Employee
}
```
The change leads to a syntax error, "MismatchedTokenException: Expecting token of type --> NAME <-- but found --> '@' <-- at line..." (see the attached screenshot).

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vw98075** [comment]
![Screenshot_select-area_20230711225419](https://github.com/jhipster/generator-jhipster/assets/10793038/cf885198-c8ee-4280-8cb2-79b4a59b3032)

**Comment by mshima** [comment]
> I'm not sure annotations are allowed in JDL. 

Yes they are.
Maybe jdl studio does not allow annotations.
cc @deepu105

**Comment by vw98075** [comment]
I run the import JDL command with a JDL file containing the annotation. There isn't any error in the process. 

The generated code doesn't have what it should be with the annotation, however. For a many-to-one relationship, 
```
relationship ManyToOne {
	Child to @OnDelete("CASCADE") Parent{children}
}
```
the related Java code on the "one" side,
```
    @OneToMany(mappedBy = "...")
    @JsonIgnoreProperties(value = { "..." }, allowSetters = true)
    private Set<Child> children = new HashSet<>();
``` 
and on the "many" side,
```
    @ManyToOne
    @JsonIgnoreProperties(value = { "...", ..., "..." }, allowSetters = true)
    private Parent parent;
```
The JHipster version is Release 7.9.3.

On a side note, I had a post about this issue on Stackoverflow yesterday. Two people marked the post for deletion. I don't know whether any of them were JHipster team numbers or not.

**Comment by OmarHawk** [comment]
> I run the import JDL command with a JDL file containing the annotation. There isn't any error in the process.
> 
> The generated code doesn't have what it should be with the annotation, however. For a many-to-one relationship,
> 
> ```
> relationship ManyToOne {
> 	Child to @OnDelete("CASCADE") Parent{children}
> }
> ```
> 
> the related Java code on the "one" side,
> 
> ```
>     @OneToMany(mappedBy = "...")
>     @JsonIgnoreProperties(value = { "..." }, allowSetters = true)
>     private Set<Child> children = new HashSet<>();
> ```
> 
> and on the "many" side,
> 
> ```
>     @ManyToOne
>     @JsonIgnoreProperties(value = { "...", ..., "..." }, allowSetters = true)
>     private Parent parent;
> ```
> 
> The JHipster version is Release 7.9.3.
> 
> On a side note, I had a post about this issue on Stackoverflow yesterday. Two people marked the post for deletion. I don't know whether any of them were JHipster team numbers or not.

These @OnDelete and @OnUpdate annotations are supported only from any 8.0.0 release. See #18751

**Comment by deepu105** [comment]
JDL studio needs to be updated to use the latest JDL syntax

**Comment by deepu105** [comment]
Its been a while since JDL studio was updated. Seems like a lot of libs are deprecated and needs to be updated as well so assigning a bounty on this

**Comment by deepu105** [comment]
@mshima @MathieuAA for latest syntax, JDL studio needs to migrate from jhipster-core package to generator-jhipster package (yes it was never updated :facepalm: ) but i'm having trouble importing the parser.

I tried different patterns but none seems to work. on vscode the below patterns don't throw error but fails during compilation with error
```
import JDLParser from "generator-jhipster/dist/jdl/index.mjs";
import JDLParser from "generator-jhipster/dist/jdl/parsing/jdl-parser";
```

error during compilation. should we add these explicitly to package.json?
```
Module not found: Error: Package path ./dist/jdl/parsing/jdl-parser is not exported from package /home/deepu/Workspace/jhipster/jdl-studio/node_modules/generator-jhipster (see exports field in /home/deepu/Workspace/jhipster/jdl-studio/node_modules/generator-jhipster/package.json)
```

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/pull/23194 should export jdl index.
I marked as ready so you can use it.
- If you need more functions or resources, they should be exported at index.

I recommend to add a tsconfig like https://github.com/mshima/generator-jhipster/blob/main/generators/generate-blueprint/templates/tsconfig.json.ejs.
Without this vscode won’t resolve named exports.

**Comment by deepu105** [comment]
@mshima thanks, i'll try it out

**Comment by deepu105** [comment]
@mshima I tried changing the tsconfig to use esm, but then I also have to make the JDL studio project `type: module` in its package json that is throwing a lot of errors from libraries used in the react app. can we also just add the dist folder to exports in package json? I think that will work

**Comment by mshima** [comment]
Esm migration may be trick.
I would say that the first task is to migrate to vite and vitest.
Official react webpack support is been deprecated. And old webpack and jest doesn’t have a good esm support.

**Comment by deepu105** [comment]
@mshima ya that could be the best option forward. This will be more work than I anticipated and probably good idea to do some cleanup as well. I'm bumping the bounty so that I can justify working on this during my parental leave 😂
