### ISSUE TITLE
SpaWebFilter should run before BasicAuthenticationFilter so that access /login directly works

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#22843]
##### **Overview of the issue**

Accessing /login directly with the new SpaWebFilter doesn't work since /login is intercpeted before when using session auth

##### **Reproduce the error**

generate project with session auth

try to access /login directlly.

##### **Suggest a Fix**
```
@Order(Ordered.HIGHEST_PRECEDENCE)
@Component
```

instead of adding the filterAfter BAsicAuth, or figure out the correct filter to add Before

##### **JHipster Version(s)**

8.0.0-beta

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by yelhouti** [comment]
EDIT: I tried creating a PR but found out a case with
```
.addFilterAfter(new SpaWebFilter(), SecurityWebFiltersOrder.HTTPS_REDIRECT)
```

So my suggested fix doesn't work.

Sorry don't have time to fix this

**Comment by mraible** [comment]
Does session authentication still work, or is something broken?

**Comment by yelhouti** [comment]
@mraible session auth still works and something else is borken.

when you use an angular app. Navigation is handled by the angular router. Try to open any page, and it's the index.html that is served thanks to the SPAFilter. Then javascript/angular does the navigation and show the angular login component.

This behavior is broken with the current order of the SpaFilter order.

**Comment by smaestri** [comment]
Hi, I reproduced the issue.
I think I have fixed it in [this PR](https://github.com/jhipster/generator-jhipster/pull/23456/), but I have to do some additional tests (tests only with React for now, need to check with other SPA).
Indeed, as @yelhouti said, `SpaWebFilter` was not triggered when accessing _/login_ directly (by putting the URL in the browser bar for example). So Spring Security was procesing _/login_ HTTP request  and returns the default login form (details [here](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/form.html)). Instead, we want the `SpaWebFilter` triggered beforehand, to get the login form from UI.
Just changing the order of `SpaWebFilter` filter seems to fix the issue : changed from ` .addFilterAfter(new SpaWebFilter(), BasicAuthenticationFilter.class)` to 
`  .addFilterAfter(new SpaWebFilter(), UsernamePasswordAuthenticationFilter.class)`
Please note that I also changed for `CookieCsrfFilter` to be consistent with `SpaWebFilter`, but I have to check if that's fine also, any feedback are welcome, thank you!

**Comment by mraible** [comment]
Just curious, why do you want to access `/login` directly? The only use case I can think of is when you have multiple identity providers with OAuth.

**Comment by mraible** [comment]
Is this still an issue?

**Comment by smaestri** [comment]
Hello, yes I guess so. Unfortunately, I will not be able to fix it soon, but  for me we should definitively fix this (more details in the PR).

**Comment by BrayanMnz** [comment]
Is there a way to replicate this? 
any blueprint project that can be used?
