### ISSUE TITLE
Missing javax.persistence dependency in build.gradle 

### ISSUE THREAD

**Issue by Nixoxo** [jhipster/generator-jhipster#2286]
I have had the following problem with the JSR310PersistenceConverters. It does not find the javax.persistence.* dependency. 
I just generated a new jhipster project using mongodb and gradle. 

* **JHipster Version(s)** 

v2.23.0

* **Suggest a Fix** 
add the hibernate-enver dependency in the build.gradle

compile 'org.hibernate:hibernate-envers:4.3.8.Final'

**Comment by jdubois** [comment]
Hibernate Envers is now included in Hibernate, so this is strange.

**Comment by atomfrede** [comment]
Seems hibernate envers is only added to ``build.gradle`` in case sql is selected. Will fix it.
