### ISSUE TITLE
jhipster entity - not generating java code

### ISSUE THREAD

**Issue by pkral3** [jhipster/generator-jhipster#22873]
`jhipster entity ebook
`
in v8.0.0-beta.2 will generate only .jhipster/Ebook.json but **no java** code as before

**Comment by GeraldAlbe** [comment]
I have the same problem. I am using the jhipster docker container, so it cannot be a problem of my installation.

**Comment by edilsonmendes** [comment]
I reported similar problem on https://github.com/jhipster/generator-jhipster/issues/22132 and the error remains in v8.0.0-beta.2. The command  `jhipster jdl mysample.jdl`  does not generate entities code (Neither java nor angular) at first. As workaround, to generate the entities code I need to run the command `jhipster jdl mysample.jdl` twice.

It seems that the first time the command is run it just generates the json (inside .jhipster) of the entities, but without java/angular code. Only the second time the complete code is generated.

PS: This didn't happen in version 7.9.3

**Comment by GuoqiangJia** [comment]
Hi @edilsonmendes Does this issue get resolved ?

**Comment by edilsonmendes** [comment]
> Hi @edilsonmendes Does this issue get resolved ?

Hi @GuoqiangJia, I'm wating for new jhipster version to check if the issue was fixed.
