### ISSUE TITLE
Generated entities from JDL and imported to project. But It gives following error

### ISSUE THREAD

**Issue by Arjuna-Bandara** [jhipster/generator-jhipster#22870]
██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0-beta.1

```
jhipster-patient-management@0.0.1-SNAPSHOT C:\DEVELOPMENT\jhipsterPatientManagement
`-- generator-jhipster@8.0.0-beta.1
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "applicationType": "monolith",
  "authenticationType": "jwt",
  "baseName": "jhipsterPatientManagement",
  "buildTool": "maven",
  "cacheProvider": "ehcache",
  "clientFramework": "angular",
  "clientTheme": "none",
  "creationTimestamp": 1688920965047,
  "databaseType": "sql",
  "devDatabaseType": "h2Disk",
  "devServerPort": 4200,
  "dtoSuffix": "DTO",
  "enableGradleEnterprise": null,
  "enableHibernateCache": true,
  "enableSwaggerCodegen": false,
  "enableTranslation": true,
  "entities": [
    "Patient",
    "Treatment",
    "Address",
    "Book",
    "Country",
    "Department",
    "Employee",
    "Job",
    "JobHistory",
    "Location",
    "Region",
    "Task"
  ],
  "entitySuffix": "",
  "gradleEnterpriseHost": null,
  "jhiPrefix": "jhi",
  "jhipsterVersion": "8.0.0-beta.1",
  "languages": [
    "en",
    "fr"
  ],
  "lastLiquibaseTimestamp": 1689413849000,
  "messageBroker": false,
  "microfrontend": false,
  "microfrontends": [],
  "nativeLanguage": "en",
  "packageFolder": "com/arjuna",
  "packageName": "com.arjuna",
  "pages": [],
  "prodDatabaseType": "mysql",
  "reactive": false,
  "searchEngine": false,
  "serverPort": null,
  "serverSideOptions": [],
  "serviceDiscoveryType": false,
  "skipCheckLengthOfIdentifier": false,
  "skipClient": false,
  "skipFakeData": false,
  "skipUserManagement": false,
  "testFrameworks": [],
  "websocket": false,
  "withAdminUi": true
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

git version 2.38.1.windows.1

node: v18.16.1
npm: 9.5.1

'docker' command could not be found

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Patient {
  firstName String
  lastName String
  dob LocalDate
  nic String
  phone String
}
entity Treatment {
  details String
  doneBy String
}
entity Address {
  homeAddress String
  officeAddress String
}
entity Book {
  name String required minlength(2) maxlength(30)
  details String
  price Double required min(1)
}
entity Country {
  countryName String
}
entity Department {
  departmentName String required
}
/**
 * The Employee entity.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String
  lastName String
  email String
  phoneNumber String
  hireDate Instant
  salary Long
  commissionPct Long
}
entity Job {
  jobTitle String
  minSalary Long
  maxSalary Long
}
entity JobHistory {
  startDate Instant
  endDate Instant
  language Language
}
/**
 * not an ignored comment
 */
entity Location {
  streetAddress String
  postalCode String
  city String
  stateProvince String
}
entity Region {
  regionName String
}
/**
 * Task entity.\n@author The JHipster team.
 */
entity Task {
  title String
  description String
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region} to Region
  Department{location} to Location
  JobHistory{job} to Job
  JobHistory{department} to Department
  JobHistory{employee} to Employee
  Location{country} to Country
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to Employee
  Employee{job} to Job
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

search Patient, Treatment, Address, Book, Country, Department, Employee, Job, JobHistory, Location, Region, Task with no
paginate Treatment, Address, Book, Job with pagination
paginate Employee, JobHistory with infinite-scroll
service Treatment, Address, Book, Country, Department, JobHistory, Location, Region, Task with serviceImpl
dto Book with mapstruct
filter Book

</pre>
</details>

##### **Overview of the issue**

Generated entities from JDL and imported to project. But It gives following error. Entity forms are not display.

##### **Motivation for or Use Case**

Can not create entities

##### **Reproduce the error**

1. create new jhipster project with jhipster cmd
2. download default JDL from https://start.jhipster.tech/jdl-studio/#/view/31c02aa0-d667-431a-9863-0ecf0a650356
3. copy JDL to the project
4. run. jhipster jdl jhipster-jdl.jdl --force
5. run. mvnw 

##### **JHipster Version(s)**
JHipster v8.0.0-beta.1

##### **JHipster configuration**

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0-beta.1

```
jhipster-patient-management@0.0.1-SNAPSHOT C:\DEVELOPMENT\jhipsterPatientManagement
`-- generator-jhipster@8.0.0-beta.1
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "applicationType": "monolith",
  "authenticationType": "jwt",
  "baseName": "jhipsterPatientManagement",
  "buildTool": "maven",
  "cacheProvider": "ehcache",
  "clientFramework": "angular",
  "clientTheme": "none",
  "creationTimestamp": 1688920965047,
  "databaseType": "sql",
  "devDatabaseType": "h2Disk",
  "devServerPort": 4200,
  "dtoSuffix": "DTO",
  "enableGradleEnterprise": null,
  "enableHibernateCache": true,
  "enableSwaggerCodegen": false,
  "enableTranslation": true,
  "entities": [
    "Patient",
    "Treatment",
    "Address",
    "Book",
    "Country",
    "Department",
    "Employee",
    "Job",
    "JobHistory",
    "Location",
    "Region",
    "Task"
  ],
  "entitySuffix": "",
  "gradleEnterpriseHost": null,
  "jhiPrefix": "jhi",
  "jhipsterVersion": "8.0.0-beta.1",
  "languages": [
    "en",
    "fr"
  ],
  "lastLiquibaseTimestamp": 1689413849000,
  "messageBroker": false,
  "microfrontend": false,
  "microfrontends": [],
  "nativeLanguage": "en",
  "packageFolder": "com/arjuna",
  "packageName": "com.arjuna",
  "pages": [],
  "prodDatabaseType": "mysql",
  "reactive": false,
  "searchEngine": false,
  "serverPort": null,
  "serverSideOptions": [],
  "serviceDiscoveryType": false,
  "skipCheckLengthOfIdentifier": false,
  "skipClient": false,
  "skipFakeData": false,
  "skipUserManagement": false,
  "testFrameworks": [],
  "websocket": false,
  "withAdminUi": true
}
</pre>
</details>

{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "jhipsterPatientManagement",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientTheme": "none",
    "creationTimestamp": 1688920965047,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "Patient",
      "Treatment",
      "Address",
      "Book",
      "Country",
      "Department",
      "Employee",
      "Job",
      "JobHistory",
      "Location",
      "Region",
      "Task"
    ],
    "entitySuffix": "",
    "gradleEnterpriseHost": null,
    "jhiPrefix": "jhi",
    "jhipsterVersion": "8.0.0-beta.1",
    "jwtSecretKey": "NGFlYjRhMWZjNTg0NmRlYmFlYTY3OWFmMzFlNmY4YTUxYjA4NDg3OGEzNDFjODYwNWQwYjVhOTRmNDI5YWM1NGZiYTA3YmQzOTgxZWM2YmJiODhiNmJjNTYyOTA4NGY1ZjIwOGU2N2VmMmM5OTMzN2E5MzZlM2JjODExYTRjNGE=",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1689413849000,
    "messageBroker": false,
    "microfrontend": false,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageFolder": "com/arjuna",
    "packageName": "com.arjuna",
    "pages": [],
    "prodDatabaseType": "mysql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

##### **Environment and Tools**

openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

git version 2.38.1.windows.1

node: v18.16.1
npm: 9.5.1

'docker' command could not be found

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Patient {
  firstName String
  lastName String
  dob LocalDate
  nic String
  phone String
}
entity Treatment {
  details String
  doneBy String
}
entity Address {
  homeAddress String
  officeAddress String
}
entity Book {
  name String required minlength(2) maxlength(30)
  details String
  price Double required min(1)
}
entity Country {
  countryName String
}
entity Department {
  departmentName String required
}
/**
 * The Employee entity.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String
  lastName String
  email String
  phoneNumber String
  hireDate Instant
  salary Long
  commissionPct Long
}
entity Job {
  jobTitle String
  minSalary Long
  maxSalary Long
}
entity JobHistory {
  startDate Instant
  endDate Instant
  language Language
}
/**
 * not an ignored comment
 */
entity Location {
  streetAddress String
  postalCode String
  city String
  stateProvince String
}
entity Region {
  regionName String
}
/**
 * Task entity.\n@author The JHipster team.
 */
entity Task {
  title String
  description String
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region} to Region
  Department{location} to Location
  JobHistory{job} to Job
  JobHistory{department} to Department
  JobHistory{employee} to Employee
  Location{country} to Country
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to Employee
  Employee{job} to Job
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

search Patient, Treatment, Address, Book, Country, Department, Employee, Job, JobHistory, Location, Region, Task with no
paginate Treatment, Address, Book, Job with pagination
paginate Employee, JobHistory with infinite-scroll
service Treatment, Address, Book, Country, Department, JobHistory, Location, Region, Task with serviceImpl
dto Book with mapstruct
filter Book

</pre>
</details>

##### **Browsers and Operating System**

Windows 10. All browsers have this problem.
- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
What error? I dont see any error in your issue description, please provide more info

**Comment by mshima** [comment]
Missing information.
Cannot be reproduced.
