### ISSUE TITLE
Integrate eslint into jhipster generation process.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#22879]
##### **Overview of the feature request**

Run eslint to fix source just like we use prettier.

##### **Motivation for or Use Case**

Improve generated code quality.

##### **Related issues or PR**

Related to https://github.com/jhipster/generator-jhipster/pull/22871#issuecomment-1637176117

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/163435.

**Comment by DanielFran** [comment]
@mshima approved
