### ISSUE TITLE
Unidirectional one-to-one relationship always yields a bi-directional one

### ISSUE THREAD

**Issue by jvence** [jhipster/generator-jhipster#22887]
Using v8.0.0-beta.2 with app configured to use MongoDb

##### **Overview of the issue**
The following relationship definition always yields a bidirectional relationship meaning that both Board and City can access each other:

relationship OneToOne {
  Board{city} to City
}

In generated City.java:
    @DBRef
    private Board board;

In generated Board.java:
    @DBRef
    @Field("city")
    private City city;

PLEASE NOTE that City.json does not have any reference to Board collection. See below

##### **Motivation for or Use Case**

No references to Board from City should be created as it would not be a unidirectional relationship

##### **Reproduce the error**

Create a jdl with two 2 entities Board and City and add the following relationship:
relationship OneToOne {
  Board{city} to City
}

##### **Related issues**

No
##### **JHipster Version(s)**

Using v8.0.0-beta.2

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Relevant code from Board.json:
  "name": "Board",
  "pagination": "pagination",
  "relationships": [
    {
      "otherEntityName": "city",
      "relationshipName": "city",
      "relationshipSide": "left",
      "relationshipType": "one-to-one"
    },

Relevant code from City.json:
  "name": "City",
  "pagination": "pagination",
  "relationships": [
    {
      "otherEntityName": "country",
      "otherEntityRelationshipName": "city",
      "relationshipName": "country",
      "relationshipSide": "right",
      "relationshipType": "many-to-one"
    }
  ],

service * with serviceClass
paginate * with pagination

##### **Browsers and Operating System**

Safari

**Comment by jelharou** [comment]
Same here.  Not an issue in 7.9.3
