### ISSUE TITLE
Configure liquibase:diff with H2 disk-based persistence

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2289]
Now that we have H2 with disk-based persistence working fine, we need to configure correctly the Maven Liquibase Hibernate plugin so that it works correctly, like with Postgresql or MySQL.

We should be able to run "mvn liquibase:diff" and have a correct changelog automatically generated.

**Comment by jdubois** [comment]
Done with https://github.com/jhipster/generator-jhipster/commit/442f319a7e6c64ce2eecfd6347fa4422c3cd116e

Not perfect as we have some dropDefaultValue which appear -> looks like those can't be ignored, and as they are not standard in JPA we can't configure them there.
Could be a good fit for the diffExcludeObjects tag cc @nvoxland

**Comment by Mady-Camara** [comment]
it's possible to use ./mvnw liquibase:diff with database h2?

**Comment by chunhsin** [comment]
can't use this feature, will cause

--
Starting Liquibase at 15:57:46 (version 4.6.1 #98 built at 2021-11-04 20:16+0000)
[INFO] Set default schema name to PUBLIC
[INFO] Executing on Database: jdbc:h2:file:/Users/jamesliao/Documents/Github/aib-acs/target/h2db/db/aibacs.mv.db
[INFO] Reading hibernate configuration hibernate:spring:com.aibizer.acs.domain?dialect=org.hibernate.dialect.H2Dialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
[INFO] Found package com.aibizer.acs.domain
[INFO] HHH000204: Processing PersistenceUnitInfo [name: default]
[INFO] HHH000412: Hibernate ORM core version 5.5.6
[INFO] HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
[WARNING] HHH000181: No appropriate connection provider encountered, assuming application will be supplying connections
[WARNING] HHH000342: Could not obtain connection to query metadata
java.lang.UnsupportedOperationException: The application must supply JDBC connections
---
