### ISSUE TITLE
r2dbc mssql support

### ISSUE THREAD

**Issue by ieliibrahim** [jhipster/generator-jhipster#22916]
Hello
First of all thank you for this amazing tool.
My current issue is, after generating a new project, I noticed that Java code includes r2dbc pool support. 
I am having an issue with connecting to mssql database with the auto-generated url in yml file.
The generated code in yml file is: 
 url: r2dbc:mssql//localhost:1433/<db_name> which does not work, after some research I had to change it like this: 
 url: r2dbc:pool:sqlserver://localhost:1433/<db_name>
but that did not work, so please let me know what is the solution.
Thank you

**Comment by atomfrede** [comment]
@ieliibrahim What are you trying to achive? Spring boot has direct support for r2dbc connection pooling via dedicated properties. https://docs.spring.io/spring-boot/docs/3.1.2/reference/htmlsingle/#application-properties.data.spring.r2dbc.pool.enabled 

In case you want full control I suppose you can customize the `ConnectionFactory` via spring configuration.

**Comment by atomfrede** [comment]
@jhipster/developers Maybe we could enable spring r2dbc connection pool by default?
