### ISSUE TITLE
Create a specific "lib" project for the Travis build

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2292]
I just merged #2248 from @pascalgrimaud and it's looking much better than our previous build (which I will need to clean up, but that's another task).

But there is one issue for me, and it is that we depend on https://github.com/pascalgrimaud/jhipster-lib (see https://github.com/jhipster/generator-jhipster/pull/2248/files#diff-16aaeb358bbf56e769f4064789497dc1R8 )

- We should not depend on another Git project: this could be easily solved by moving this to the JHipster organization. @pascalgrimaud would you agree to migrate this to a new "jhipster/jhipster-travis-build" (or something like this) project? I would create a specific Github team so you have access to it.
- I don't understand very well how this is supposed to work: does this build have the whole npm + maven dependencies? How do you upgrade it? You would need to upgrade it for each library update!! This would not be fully automated, then!

**Comment by pascalgrimaud** [comment]
> it's looking much better than our previous build (which I will need to clean up, but that's another task)

* like @mraible said, "The more testing, the better!" maybe you can keep it ?
* the last build failed... travis-ci didn't manage to install gulp : https://travis-ci.org/jhipster/generator-jhipster/builds/89534904

jhipster/jhipster-travis-build -> completely agree to migrate !

At step 3 with `03-downloadDep.sh`, there are 3 possibilities :
* Option 1 : the build will clone jhipster/jhipster-travis-build and prepare :
    * .m2/repository/
    * put node_modules inside the new project before `yo jhipster`
    * It will try to provide a maximum of library. If one is missing, npm or mvn will download it, as always
* Option 2 : use mvn dependency:go-offline, but node_modules is missing
* Option 3 : do nothing
    * npm install is very long...
    * maven will download 1 by 1 every dependencies
    * every build can take more than 10min (instead of 6~7min) and there are 11 differents permutations and Travis-CI can build 5 simultaneously
I was just trying to speedup the build.

Every upgrade of `jhipster/jhipster-travis-build` will be made to speedup the build. It's not mandatory (I was thinking about it but maybe use pom.xml and package.json...)

**Comment by jdubois** [comment]
For the last build that failed: I already had that issue before, Travis keeps having issue to download stuff, which breaks the builds regularly. That's a real pain!!!

**Comment by jdubois** [comment]
@pascalgrimaud I created a new https://github.com/jhipster/jhipster-travis-build project, and created a new "Builders" team, where there is only you & me with write access (if other people from team want the access, just ask for it, of course)

**Comment by pascalgrimaud** [comment]
Thanks @jdubois !
I will work on it tonight or tomorrow.
