### ISSUE TITLE
Migrate my application to last jhipster to use social sign in

### ISSUE THREAD

**Issue by achraftalbi** [jhipster/generator-jhipster#2293]
Hello,

 We build our application using jhipster 2.20.0.

 Now that the last version of Jhipster introduce the "social sign in" we want to migrate to it. In our application we made some changes in the login part and in roles.

 I want to know if there is a simple way to do this migration to use social sign in ?

 Thanks 

 Helper

**Comment by deepu105** [comment]
The only way is to regenerate and do a manual merge.  Since you want only
the social login you need not regenerate entities just regenerate the app
and merge what is required. If you dont use GIT then you can do a compare
merge with tools like 'beyond compare'

**Comment by achraftalbi** [comment]
Thanks for your response.

 We will do this merge.

 Achraf
