### ISSUE TITLE
Error: This Generator is empty when creating Websocket project

### ISSUE THREAD

**Issue by kgaspar** [jhipster/generator-jhipster#22979]
##### **Overview of the issue**
I have ran into a problem when creating a JHipster project using websockets. The whole project builds and runs without any issues, but upon adding a JDL (used the default JDL studio data for reference) and running _jhipster jdl default.jdl_ the process fails with an yeoman error:

`Error: This Generator is empty. Add at least one method for it to run.
at SpringWebsocketGenerator.queueOwnTasks (file:///home/user/.nvm/versions/node/v18.16.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:181:19)
at SpringWebsocketGenerator._queueTasks (file:///home/user/.nvm/versions/node/v18.16.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:295:14)
at SpringWebsocketGenerator.queueTasks (file:///home/user/.nvm/versions/node/v18.16.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:291:20)
at async runGenerator (file:///home/user/.nvm/versions/node/v18.16.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:327:17)
    at async runLoop.add.once (file:///home/user/.nvm/versions/node/v18.16.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:383:17)
`

When creating a identical project without websocket support the jdl builds successfully.

When using Jhipster 7.9.3. the project builds succesfully

##### **Motivation for or Use Case**

Basically I cant create a project from JDL if there is a need for websocket usage.

##### **Reproduce the error**

1. create jhipster project
2. run ./mvnw to verify it works
3. copy jdl into default.jdl
4. run jhipster jdl default.jdl
5. end

##### **JHipster Version(s)**

JHipster 8.0.0.beta-2

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "applicationType": "monolith",
  "authenticationType": "jwt",
  "baseName": "test-websocket",
  "buildTool": "maven",
  "cacheProvider": "ehcache",
  "clientFramework": "no",
  "creationTimestamp": 1690358246459,
  "databaseType": "sql",
  "devDatabaseType": "h2Memory",
  "dtoSuffix": "DTO",
  "enableGradleEnterprise": null,
  "enableHibernateCache": false,
  "enableSwaggerCodegen": false,
  "enableTranslation": false,
  "entities": [],
  "entitySuffix": "",
  "gradleEnterpriseHost": null,
  "jhiPrefix": "jhi",
  "jhipsterVersion": "8.0.0-beta.2",
  "messageBroker": false,
  "microfrontend": false,
  "microfrontends": [],
  "nativeLanguage": "en",
  "packageFolder": "com/test/websocket",
  "packageName": "com.test.websocket",
  "pages": [],
  "prodDatabaseType": "mysql",
  "reactive": false,
  "searchEngine": false,
  "serverPort": null,
  "serverSideOptions": [
    "websocket:spring-websocket"
  ],
  "serviceDiscoveryType": false,
  "skipCheckLengthOfIdentifier": false,
  "skipClient": true,
  "skipFakeData": false,
  "skipUserManagement": false,
  "testFrameworks": [],
  "websocket": "spring-websocket",
  "withAdminUi": true
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc37) (build 17.0.7+7)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc37) (build 17.0.7+7, mixed mode, sharing)

git version 2.41.0

node: v18.16.1
npm: 9.5.1

Docker version 24.0.4, build 3713ee1

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

entity Region {
	regionName String
}

entity Country {
	countryName String
}

// an ignored comment
/** not an ignored comment */
entity Location {
	streetAddress String,
	postalCode String,
	city String,
	stateProvince String
}

entity Department {
	departmentName String required
}

/**
 * Task entity.
 * @author The JHipster team.
 */
entity Task {
	title String,
	description String
}

/**
 * The Employee entity.
 */
entity Employee {
	/**
	* The firstname attribute.
	*/
	firstName String,
	lastName String,
	email String,
	phoneNumber String,
	hireDate Instant,
	salary Long,
	commissionPct Long
}

entity Job {
	jobTitle String,
	minSalary Long,
	maxSalary Long
}

entity JobHistory {
	startDate Instant,
	endDate Instant,
	language Language
}

enum Language {
    FRENCH, ENGLISH, SPANISH
}

relationship OneToOne {
	Country{region} to Region
}

relationship OneToOne {
	Location{country} to Country
}

relationship OneToOne {
	Department{location} to Location
}

relationship ManyToMany {
	Job{task(title)} to Task{job}
}

// defining multiple OneToMany relationships with comments
relationship OneToMany {
	Employee to Job{employee},
	/**
	* A relationship
	*/
	Department to
	/**
	* Another side of the same relationship
	*/
	Employee{department}
}

relationship ManyToOne {
	Employee{manager} to Employee
}

// defining multiple oneToOne relationships
relationship OneToOne {
	JobHistory{job} to Job,
	JobHistory{department} to Department,
	JobHistory{employee} to Employee
}

// Set pagination options
paginate JobHistory, Employee with infinite-scroll
paginate Job with pagination

// Use Data Transfer Objects (DTO)
// dto * with mapstruct

// Set service options to all except few
service all with serviceImpl except Employee, Job

// Set an angular suffix
// angularSuffix * with mySuffix

</pre>
</details>

##### **Browsers and Operating System**

Fedora Linux 37

- [ ✓] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
I could not reproduce.
