### ISSUE TITLE
Http request to api/account after logout - 401 error

### ISSUE THREAD

**Issue by MateuszPu** [jhipster/generator-jhipster#2298]
Hi,

I generated application using following settings:

{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "ce124135a46f9e8af9e5445c7a750e7fde7cf7f2",
    "testFrameworks": []
  }
}

When i run application and go to localhost:8080/ main page is loaded (im not log in) in console i have http request to api/account:
GET http://127.0.0.1:8080/api/account?cacheBuster=1446887613290 401 (Unauthorized)
When im log in to application and then log out i have the same error:
GET http://127.0.0.1:8080/api/account?cacheBuster=1446887852988 401 (Unauthorized)
Is it a normal behavior?

**Comment by jdubois** [comment]
Yes. Please look at past issues and mark this as a duplicate, for other users.
