### ISSUE TITLE
Websockets Debug & Deploy Help

### ISSUE THREAD

**Issue by jordanbaucke** [jhipster/generator-jhipster#2299]
Hey guys great stuff - I really appreciate the jHipster generator as it encapsulates a lot of functionality that would take **eons** to set-up on one's own (:

Have a few questions:
##### Websockets
  * I want to use websockets (and hopefully debug them in JS locally) - reading a bit I see tokenized authentication option is out (for now) so I regenerated with "oauth" as that seemed to be functional, when I launch the app it works, but I need to **disable browserify** to debug them: **how do I do this besides just commenting out the _grunt_ task**? 

##### Deployment
I've learned from past bad experiences I always want to do a test-deploy periodically so that I know I can get my app running in prod. accessible environment and recognize when I break something locally:
  * **Heroku** (most familiar with), couldn't get the app to start in time, tried making changes to proc file from https://github.com/jhipster/generator-jhipster/pull/2297, but still not starting in time.
  * **openshift** also no luck! Deployed but nothing happened? I used the same app-generated for heroku so maybe the git commit got screwed up? but I'm just seeing the default open-shift landing page?!
  * **cloudfoundary** looks cool, but confusing membership / tools process? "Sign-up" --> _We'll be in touch_ ? Do I have to have to have a phone-call with a salesperson to try this thing? *confused*?
  * **aws** also very familiar with - generator runs and hangs _after_ creating s3 bucket with exception: 
```
Upload WAR to S3
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```

Cloudapp fabrics everywhere and I can't get any of them to work (; 

*recommendations* ? 

Cheers!

**Comment by jdubois** [comment]
Please follow the guidelines, one ticket per issue please.

- Websockets : they don't work with BrowserSync, that's your issue. This is a past issue -> please have a look in the history and mark this as duplicate
- For all cloud platforms : they don't work with Websockets, basically. This is also discussed in older issues.
- And yes we have trouble with Openshift and CloudFoundry, those are already opened issues.

**Comment by jordanbaucke** [comment]
thank you @jdubois will do.

**Comment by jdubois** [comment]
Also, all those issues are really annoying -> so I confirm your issues, and if you find any solution please let us know.
From my understanding there is little interest from cloud providers to support Websockets, which I find very disappointing 
This is probably why mean.io has done their own platform (but there is a strong vendor lock-in in exchange, obviously)
