### ISSUE TITLE
some problem for karma test 

### ISSUE THREAD

**Issue by vrigan** [jhipster/generator-jhipster#2302]
when i run in  test/javascript/spec/app/account/password/password.directive.spec.js
This file will use password.directive.js;This test have three problem;
One{
in line 74-77: 
               iElement.find('ul').children('li')
                                .css({'background': '#DDD'})
                                .slice(0, c.idx)
                                .css({'background': c.col});
The problem is slice is not a function;But if Change to
               $(iElement.find('ul').children('li')
                                .css({'background-color': '#DDD'}))
                                .slice(0, c.idx)
                                .css({'background-color': c.col});
The test is Ok;Is this this question just for me?
}
Two{
The css use .css({'background': '#DDD'});
But password.directive.spec.js use background-color;
like: expect(firstpointStyle).toContain('background-color: rgb(255, 153, 0)');
}
Three{
password.directive.spec.js use $httpBackend.flush();
But no request; so will show error:expect No pending request to flush;
}
These problem I don't know is my fault?I change more file to use requirejs;All test is Ok;Just this test fail

**Comment by gmarziou** [comment]
Could you please follow [our guidelines to submit an issue](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#issue) and format your post?

Closing issue until guidelines followed.
