### ISSUE TITLE
[Feature request] Entity version audit

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2306]
Hi all,

I was toying with Javers as mentioned here #1762 for capturing entity versions for audit and I found it falling short of my expectations and also caused performance impact on my normal entity save/update
so i did some research and then implemented the following which works beautifully

1. JPA has event listeners for preUpdate, preCreate, postUpdate, postCreate, postRemove etc so i hooked a event listener to these
2. I used abstract auditingEntity class to capture created/modified info, so any entity which extends this will be audited
2. the event will pass the entity being persisted/removed so i passed it into an async auditEventConverter (I formatted the entity to json using Jackson mappers already available and version this and persisted into an audit table)
3. Now I have a table with below
       * id
       * entity_type (fully qualified type of entity)
       * entity_id (unique entity id)
       * action (create/update/delete)
       * entity_value (json value)
       * commit_version (incremental version unique to an entity id starting with 1)
       * updated_by
       * updated_time
4. On client side i can fetch these data for each entity type and list down the versions, I wrote an angular object diff plugin to show a visual diff of old values and new values
5. any entries older than 3 months are archived into an archive table by a scheduled job

since all this is async there is no performance impact as well and users can see exactly what changed between each entity versions by whom and when

If there is interest in this feature I can do a PR, its a simple change that doesn't affect any existing functions

**Comment by mraible** [comment]
Sounds pretty sweet to me. I'd love to see the code.

**Comment by jdubois** [comment]
For me this sounds more like something that would be added to the project, like a plugin -> I'm going to send a first proposal for that on the dev mailing list, let's discuss this together and then add tickets here for everyone

**Comment by deepu105** [comment]
oops I almost forgot the mailing list :smile_cat:

**Comment by tapas4java** [comment]
+1

**Comment by gzsombor** [comment]
Sounds interesting! 
 What kind of performance problems did you see, when using Javers? Because from your quick explanation, it seems that you've implemented the same, as Javers did, so I curious, why your solution fares better than that ...

**Comment by deepu105** [comment]
When I persist entities with their relationships the save was taking a long
time with javers, didn't do much research on what was causing issue there,
may be they were serializing all the object dependency, also if some data
is inserted in db directly  javers throws error while updating or deleting
those values, also i think javers wasnt async. So for my simple use javers
felt a bit too much as i wasnt gonna use most of javers diff features anyway

**Comment by jdubois** [comment]
@deepu105 do you think this could be made as a module?
I'm against using Hibernate Envers by default, as I've seen 2 projects failing because of abusing it (not really an Hibernate Envers issue, mostly people don't get how it works or what it does)

**Comment by deepu105** [comment]
Its not with envers, its a simple listner based implementation. I think it
can be a module, let me try when im back will close this later

**Comment by deepu105** [comment]
Here is the feature as a Jhipster module https://github.com/deepu105/generator-jhipster-entity-audit 
this should be available to users from the next Jhipster release

hence closing this issue

@jhipster/developers guys please take a look and let me know if this can be improved, especially the angular interceptor which i would like to avoid as Spring data auditing already marks created by and createdDate but somehow with DTO the bean validation fails hence I had to use an interceptor to set the data

**Comment by gmarziou** [comment]
Why do you set `@NotNull`on createdBy and createdDate fields in DTO? To me client cannot be trusted for these fields and only the server should be able to set them, so I would not require them in DTO.

**Comment by deepu105** [comment]
@gmarziou yes you are correct, I didnt want even the abstractDTO actually but the problem is during updates the createdBy is null and bean validation fails as in the abstarctAuditingEntity these fields are set as notNull,  any idea how to workaround this, plz feel free to PR if you think this can be improved

**Comment by deepu105** [comment]
@gmarziou Im currently using an angular interceptor to set createdBy, modifiedBy etc coz somehow the beanValidation is being trigered before spring sets these, the correct way should be that these are set at server side by spring in AuditingEventListener alone, I was able to get them working for normal entity but for DTO again I had the createdBy null issue during updates
