### ISSUE TITLE
Unreadable white text in alert boxes with some bootswatch themes (tested with 'minty' and 'yeti')

### ISSUE THREAD

**Issue by ebousse** [jhipster/generator-jhipster#23066]
##### **Overview of the issue**

When using specific bootswatch themes, such as `minty` or `yeti`, the text in alert boxes appears white and is therefore almost unredable.

Example with `yeti`:

![Capture d’écran du 2023-08-04 18-41-16](https://github.com/jhipster/generator-jhipster/assets/5868014/caf19506-57a8-40a0-bd55-aa6637f5f935)
![Capture d’écran du 2023-08-04 18-41-24](https://github.com/jhipster/generator-jhipster/assets/5868014/23ad4863-f3f8-4bc0-aa18-e0ea1ab07991)

We can see both white text on light green and white text on light orange.

A similar problem occurs with the `minty` theme. I haven't tried other themes yet.

##### **Motivation for or Use Case**

I think it would be great if the default CSS of a generated project would "just work".

##### **Reproduce the error**

Generate a new project with default choices for everything, and `yeti` as `clientTheme`.

##### **Related issues**

N/A

##### **Suggest a Fix**

Somewhere in the CSS I presume? I couldn't find the place unfortunately.

##### **JHipster Version(s)**

`8.0.0-beta.2`

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "applicationIndex": 0,
  "applicationType": "monolith",
  "authenticationType": "jwt",
  "baseName": "boardgamemanager",
  "buildTool": "maven",
  "cacheProvider": "ehcache",
  "clientFramework": "angular",
  "clientTheme": "yeti",
  "clientThemeVariant": "primary",
  "creationTimestamp": 1691166699484,
  "databaseType": "sql",
  "devDatabaseType": "h2Disk",
  "devServerPort": 4200,
  "dtoSuffix": "DTO",
  "enableGradleEnterprise": false,
  "enableHibernateCache": true,
  "enableSwaggerCodegen": false,
  "enableTranslation": true,
  "entities": [],
  "entitySuffix": "",
  "jhiPrefix": "jhi",
  "jhipsterVersion": "8.0.0-beta.2",
  "languages": [
    "en",
    "fr"
  ],
  "messageBroker": "no",
  "nativeLanguage": "en",
  "packageFolder": "com/mycompany/myapp",
  "packageName": "com.mycompany.myapp",
  "pages": [],
  "prodDatabaseType": "postgresql",
  "reactive": false,
  "searchEngine": "no",
  "serverPort": 8080,
  "serviceDiscoveryType": "no",
  "skipCheckLengthOfIdentifier": false,
  "skipClient": false,
  "skipFakeData": false,
  "skipServer": true,
  "skipUserManagement": false,
  "websocket": "no",
  "withAdminUi": true
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7, mixed mode, sharing)

git version 2.41.0

node: v18.16.1
npm: 9.5.1

Docker version 24.0.5, build ced0996

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities.

##### **Browsers and Operating System**

Fedora 38, the problem occurs on Firefox 116.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by dinu0000** [comment]
i looked into it. it seems like the issue is in the bootswatch theme itself and not with any of the code generated by Jhipster.
i think this issue can be closed.

**Comment by mshima** [comment]
I've generated a new project using the provided `.yo-rc.json` and run `npm start`.
The result looks ok to me:
<img width="943" alt="Captura de Tela 2023-08-14 às 11 22 15" src="https://github.com/jhipster/generator-jhipster/assets/1417183/1682281d-b2ca-4c38-9f6a-8e947ac4bdd5">

As stated by @dinu0000 may be a bug at the theme or bootstrap that may be fixed already.
