### ISSUE TITLE
Development blueprint.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#23086]
##### **Overview of the feature request**

I always had difficulties to generate samples for testing.
This became much easier with vscode launch shortcuts, but the underlying script is still poorly documented and we may need to look at the source for usage.

This `blueprint` will be enabled when jhipster is executed in JIT mode.
It will allow to generate a sample by running `jhipster generate-sample xxxx`.
Maybe others generators like generate a code-workspace multi root may be helpful when multiples samples are needed to be tested.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/165734

**Comment by DanielFran** [comment]
@mshima approved
