### ISSUE TITLE
Spring Security sessionFixation Config

### ISSUE THREAD

**Issue by vrigan** [jhipster/generator-jhipster#2308]
By Default;Spring Security sessionFixation will use changeSessionId;
But after /api/authentication success; The session will lost for every request;
If change sessionFixation to none;Everything ok;
The problem just for me?

**Comment by jdubois** [comment]
Please follow our guidelines -> this probably depends on your authentication mechanism, which one are you using? Which JHipster version?

I'm closing this as the guidelines are not followed, we'll open it up again if you provide enough information.

**Comment by vrigan** [comment]
Hipster Version:2.23.0

**Comment by vrigan** [comment]
new : Is Hazelcast kill my session,I will find why

**Comment by vrigan** [comment]
The problem look like clear;
For example:
    send 'index.html' request
    create new session 123456 and Hazelcast will save it too
    response session 123456
    
    send 'api/authentication' take session 123456 
    
    
    When Spring Security on auth by org/springframework/security/web/authentication/AbstractAuthenticationProcessingFilter.java line 223;
    This function will do Spring Security SessionFixation;
    In servlet3.1 default SessionFixation Strategy is ChangeSessionId,So the session will be change;
    After Hazelcast will auto found the not in originalSessions sesssion and remove it;
    This is why session is null;And sometimes first /api/account request is Ok;
