### ISSUE TITLE
main.css is not getting transpiled from main.scss when run through mvn

### ISSUE THREAD

**Issue by tapas4java** [jhipster/generator-jhipster#2312]
Steps to reproduce:

1. Create a new app with SASS enabled
2. Run `mvn` and access the url in browser
3. Notice the disrupted UI and see the browser console for error

NOTE: Running through gulp/grunt works fine

**Comment by jdubois** [comment]
Yes you need to have grunt or gulp running to have SASS working, they are the one doing the work! If you just use Maven it will not work, that's normal.

In fact, it looks like this is not documented, there should be a specific page for this inside our "options" menu at jhipster.github.io -> I'm marking this as "documentation" as this should be documented.

As I'm not using this myself, who would be available to write this? Just a few lines in MarkDown would be great!

**Comment by tapas4java** [comment]
What about adding main.css to assets directory when we scaffold the app. Just a suggestion :)

**Comment by tapas4java** [comment]
Most of the users will try to check the app after running `mvn` and they will feel something broken. We can describe in doc as if user wants to modify main.scss, he needs client side server running in order to transpile the scss.

**Comment by jdubois** [comment]
Yes I'm not using it myself, I think @deepu105 does -> Deepu, any ideas?

This should at least be better documented, clearly.

**Comment by deepu105** [comment]
Ya i guess it can be improved ill work on it, and few other grunt things
that can be pre generated during app creation

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/commit/8f8b0d2b8ce22205561c26d15931e360b8c4bc4d
