### ISSUE TITLE
Password in UPPERCASE in initial_schema

### ISSUE THREAD

**Issue by Panthro** [jhipster/generator-jhipster#2313]
Is there a reason for that?
https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml#L29

My liquibase diff always tries to generate the password field because it's not there.

I tried to find any issues related to that but couldn't, so sorry if this was discussed earlier.

**Comment by deepu105** [comment]
I think its coz of some reserved keyword with either oracle or posgres

**Comment by Panthro** [comment]
Shouldn't the User.java have the column name on the annotation then?
https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/java/package/domain/_User.java#L57

**Comment by deepu105** [comment]
Not required it resolves properly, i guess the reserved keyword thing is
only during table creation

**Comment by jdubois** [comment]
+1 this doesn't look good, and indeed it's going to make liquibase diff create the field again -> this should be in lowercase

@deepu105 you changed it at https://github.com/jhipster/generator-jhipster/commit/3ba275743a2003602b21253cf2418278aa7f748e but as you say it's good for you there is no need to keep this

**Comment by wuethrich44** [comment]
You could rename it to `password_hash` because it is a password hash that is stored in the database.

**Comment by Panthro** [comment]
+1 for the `password_hash` column name, as it makes even more sense because that's what this field actually is.

**Comment by deepu105** [comment]
+1 for `password_hash` as column name, if we lowercase `password` here it
fails in oracle not sure about posgres
On 10 Nov 2015 08:41, "Rafael Roman" <notifications@github.com> wrote:

+1 for the password_hash column name, as it makes even more sense because
that's what this field actually is.

—
Reply to this email directly or view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/2313#issuecomment-155246571>
.

**Comment by jdubois** [comment]
Yes +1 for me too

**Comment by deepu105** [comment]
@panthro can you do a PR for this

**Comment by Panthro** [comment]
Yes I can, as soon as I arrange some time to work on it :+1:

**Comment by Panthro** [comment]
pull request #2365 created
