### ISSUE TITLE
Method "getCurrentUser" in "SecurityUtils" don't work for me

### ISSUE THREAD

**Issue by wzomer** [jhipster/generator-jhipster#2315]
The user is logged and the method "getCurrentUser" always return exception "User not found!", don't understand why.
The method "getCurrentUserLogin" work correctly.

It is the same with you?

**Comment by gzsombor** [comment]
What kind of authentication do you use? Spring dev-tools could be a culprit, as it does some funky class duplications with the classloaders.

**Comment by wzomer** [comment]
I'm using OAuth.

{
    "generator-jhipster": {
        "authenticationType": "oauth2",
        "hibernateCache": "hazelcast",
        "clusteredHttpSession": "hazelcast",
        "websocket": "no",
        "databaseType": "sql",
        "devDatabaseType": "mysql",
        "prodDatabaseType": "mysql",
        "useCompass": true,
        "buildTool": "maven",
        "frontendBuilder": "grunt",
        "javaVersion": "8",
        "searchEngine": "no",
        "enableTranslation": false,
        "useSass": true,
        "enableSocialSignIn": false,
        "testFrameworks": [
            "gatling"
        ]
    }
}

**Comment by jdubois** [comment]
Duplicate from #2291

We should have a new version today that correct this
