### ISSUE TITLE
Default ukrainian localization is garbage

### ISSUE THREAD

**Issue by twentytwodegreecelcious** [jhipster/generator-jhipster#23153]
So I've just started with jHipster, intending to create a very first application. I chose Ukrainian to be the primary language and the messages_ua.properties is showing garbage.

![image](https://github.com/jhipster/generator-jhipster/assets/13236064/aea9b76e-34c1-4e1f-9345-d7487141faee)

The initializer says that Ukrainian is supported, however it doesn't.

Follow the steps on jhipster.tech On step 4 choose Ukrainian to be the primary language.

idk

##### **JHipster Version(s)**

8.0.0-beta.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "applicationType": "monolith",
  "authenticationType": "session",
  "baseName": "vesta",
  "buildTool": "maven",
  "cacheProvider": "no",
  "clientFramework": "no",
  "creationTimestamp": 1691957431726,
  "databaseType": "sql",
  "devDatabaseType": "postgresql",
  "dtoSuffix": "DTO",
  "enableGradleEnterprise": null,
  "enableHibernateCache": false,
  "enableSwaggerCodegen": false,
  "enableTranslation": true,
  "entities": [],
  "entitySuffix": "",
  "gradleEnterpriseHost": null,
  "jhiPrefix": "jhi",
  "jhipsterVersion": "8.0.0-beta.2",
  "languages": [
    "ua",
    "en",
    "fr"
  ],
  "messageBroker": false,
  "microfrontend": false,
  "microfrontends": [],
  "nativeLanguage": "ua",
  "packageFolder": "com/twentytwodegreescelcius",
  "packageName": "com.twentytwodegreescelcius",
  "pages": [],
  "prodDatabaseType": "postgresql",
  "reactive": false,
  "searchEngine": false,
  "serverPort": null,
  "serverSideOptions": [],
  "serviceDiscoveryType": false,
  "skipCheckLengthOfIdentifier": false,
  "skipClient": true,
  "skipFakeData": false,
  "skipUserManagement": false,
  "testFrameworks": [],
  "websocket": false,
  "withAdminUi": true
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

Windows10, browser is not relevant to the issue

- [+] Checking this box is mandatory (this is just to show you read everything)

**Comment by duderoot** [comment]
Hi @twentytwodegreecelcious did you check the encoding of the editor how are you viewing the file. From the screenshot feels like an encoding issues. As far as I know all the sources that are created are utf8. Could you also start the aplication to see what the application will display?

P.S. maybe you could change the name of the issue, IMHO garbage sound way to hart 😉 Thanks!

**Comment by duderoot** [comment]
As I susspected the problem lies in the config of your IDE, in your case IntelliJ. Looks like default encoding for proeprties is not utf8:
<img width="1211" alt="grafik" src="https://github.com/jhipster/generator-jhipster/assets/4954023/4abea64f-e3d4-4fa2-b139-9eab8b19d071">

After changing the encoding to utf8  all looks good like expected 😄 
<img width="1392" alt="grafik" src="https://github.com/jhipster/generator-jhipster/assets/4954023/18c6f4a6-09e2-4460-9867-66709ebe3c63">

@developers it can be close @atomfrede (I call you since you are closer  geographicaly and I thought you can hear me 🤣 )  maybe you  get the chance to close it 🍺

**Comment by mshima** [comment]
Ukrainian locale looks to be changed from ua to uk.
Can someone confirm if we need to change files too?

**Comment by deepu105** [comment]
@twentytwodegreecelcious we don't appreciate the language. This is an open source project run by volunteers who use their precious time doing this. You are welcome to report issues and if you find something is garbage you are welcome to create a PR to fix it rather than

**Comment by twentytwodegreecelcious** [comment]
> @twentytwodegreecelcious we don't appreciate the language. This is an open source project run by volunteers who use their precious time doing this. You are welcome to report issues and if you find something is garbage you are welcome to create a PR to fix it rather than sounding entitled

I'm sorry for this. I inteded to write "showing garbage". Terribly sorry and I appriciate you guys doing the work.

**Comment by deepu105** [comment]
Cool no worries then
