### ISSUE TITLE
Start migrating blueprints to v8.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#23195]
##### **Overview of the feature request**

Start migrating blueprints to v8.

Migrate [generator-jhipster-entity-audit](https://github.com/jhipster/generator-jhipster-entity-audit/issues/200) to v8.
Export required resources.
Adjusts to generate-blueprint based on the upgrade experience.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by hide212131** [comment]
@mshima Could this issue and related PR possibly be a groundwork for allowing Blueprints to be written in TypeScript? If so, that's fantastic! 😊

**Comment by mshima** [comment]
It should be possible to implement blueprints in typescript, but I don’t think it’s worth the increase of complexity (build, typescript loader, …).
- blueprints has just a few js files.
- jhipster types are not stable.

Autocomplete on the other hand is quite handy.

**Comment by deepu105** [comment]
@mshima added bounty

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/170965

**Comment by DanielFran** [comment]
@mshima approved
