### ISSUE TITLE
[enhancement] update ui-bootstrap

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2321]
ui-bootstrap latest version has some breaking changes we need to update accordingly

**Comment by gzsombor** [comment]
Can you be a bit specific, what could be a breaking change in bootstrap? I haven't found a release notes from them ... :disappointed:

**Comment by deepu105** [comment]
Ya no release notes but they changed their namespace now all directives and
services have uib prepended, for eg uibModal instead of $modal etc

**Comment by deepu105** [comment]
I was trying the new version application broke
