### ISSUE TITLE
Entities extending AbstractAuditingEntity not "completely" cachable by Hazelcast

### ISSUE THREAD

**Issue by Burdu** [jhipster/generator-jhipster#2323]
Hello,

I identified a bug today that involved the User entity, which extends AbstractAuditingEntity: the members of AbstractAuditingEntity were not returned from Hazelcast cache.

I marked with @ Cachable the method from the UserRepository. The user objects (their clones actually) got cached, but when I returned them from cache, the members of the superclass were null (for createdBy and lastModifiedBy) and initialized with Datetime.now() - createdDate and lastModifiedDate

It's because AbstractAuditingEntity does not implement Serializable.
The solution is to implement Serializable on AbstractAuditingEntity and Hazelcast will clone the values of the superclass as well.

**Comment by gzsombor** [comment]
Your explanation make sense, it can be fixed easily

**Comment by gzsombor** [comment]
This was an easy fix, if no one against, we can merge it, can't we?

**Comment by jdubois** [comment]
Looks good -> by the way, at least this time there is a good reason to use the serialVersionUID!!

**Comment by deepu105** [comment]
@gzsombor did you merge this?  Can we close this

**Comment by gzsombor** [comment]
It's already merged !
