### ISSUE TITLE
Document generator-jhipster architecture 

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#23230]
The generator architecture and file structure has changed so much over time and it's becoming difficult to keep track/contribute for even someone like me who has been with the project for a long. So for new contributors, it will be a mammoth task to get up to speed.  We need to document these so that new contributors can onboard faster

- [ ] add a new generator architecture document to root (fils structure, ejs convention used, yeoman setup and explanations, generator hierarchy and architecture, jdl architecture, important config objects, lifecycle, blueprints etc)
- [ ] update contributing.md to refer this for development setup etc
- [ ] provide tips and tricks for local development (linking, building, updating templates etc

**Comment by deepu105** [comment]
@mshima @MathieuAA  I believe you guys are the best folks to do this. WDYT

**Comment by mshima** [comment]
Sure.
