### ISSUE TITLE
Spanish translation is broken

### ISSUE THREAD

**Issue by piedrahitac** [jhipster/generator-jhipster#2324]
### Overview of the issue
Installing Spanish as a language and then selecting it in the dropdown menu results in a javascript error of `Unexpected token }` that breaks the application.

### Motivation for or Use Case
Using spanish language in a jhipster app.

### JHipster Version(s)
2.23.1. I don't think it happened in previous versions but not entirely sure.

### Browsers and Operating System
Chrome and Firefox on Linux

### Reproduce the error
Create a new application, install Spanish language and then select it in the dropdown menu.

### Suggest a fix
It's a reaaaally easy fix, just have to remove a trailing comma in line 110 of es/global.json file (error.size property).

I'm sorry I can't provide a PR right now despite such an easy fix, but I won't be available until the end of the month.

**Comment by gzsombor** [comment]
I think, it's already fixed in 3affe0760b7f10549259aa6cc98bffe9f2c32070
