### ISSUE TITLE
Add support to issue sample generation to development blueprint.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#23282]
##### **Overview of the feature request**

- Add `from-issue` generator to development blueprint.
`jhipster from-issue xxx`
`from-issue` will generate sample application from issue description which should include `jhipster info` output.
Will use `.yo-rc.json` and entities jdl from info output.

- Add a workflow to run default tests using the issue sample.

##### **Motivation for or Use Case**

Improve issue triaging.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/163432.

**Comment by DanielFran** [comment]
@mshima approved
