### ISSUE TITLE
Add support for RxJava

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#233]
This might be optionnal at generation time

RxJava would allow us to build "reactive" web apps, like what Play/Akka does.

See https://github.com/Netflix/RxJava

Ratpack already has some very early support, see https://github.com/ratpack/ratpack/blob/master/ratpack-rx/src/test/groovy/ratpack/rx/RxHttpClientSpec.groovy#L35

**Comment by delverdev** [comment]
What plans about this feature now?

**Comment by cbornet** [comment]
There will be reactive support in Spring 5 / Spring Boot 2 so I guess this will be done when they are released.
