### ISSUE TITLE
Web service Jhipster

### ISSUE THREAD

**Issue by boutchekkoucht** [jhipster/generator-jhipster#2331]
is possible to code a web service using jhipster ?

**Comment by cbornet** [comment]
Well, jhipster **IS** REST-JSON web services.

**Comment by boutchekkoucht** [comment]
yes but , is possible to remove the view part and put it in another project?

**Comment by cbornet** [comment]
Of course you can although I don't know why you would want to do it : JHipster does a lot of optimizations on static resources.
But if you really want to, the webapp is in src/main/webapp. You will probably have to configure the CORS if working cross-domain.

**Comment by boutchekkoucht** [comment]
hank you, I would try to do.
that's the architecture I want to do
![jug-nantes-telosys-tools-avril-2014-31-638](https://cloud.githubusercontent.com/assets/10811506/11127743/ad4b948a-896d-11e5-91ce-4ad745b6fd6e.jpg)

**Comment by jdubois** [comment]
This is already what we provide, I don't think you should remove our web part!
Anyway, this isn't a bug or feature requests so according to our guidelines this should go to StackIverflow and I'm closing this.

**Comment by cbornet** [comment]
Then JHipster is for you as it is exactly the architecture you'll get

**Comment by boutchekkoucht** [comment]
I want to physically separate the two applications, and use json + ssl between the two machines.
I'm sorry if I put this in the parts of bugs

**Comment by jdubois** [comment]
This is not how AngularJS works, it's the client browser which will do the REST requests.

**Comment by boutchekkoucht** [comment]
so if I work with jhipster, I need to develop  my customer client  web service!

**Comment by cbornet** [comment]
@boutchekkoucht You should check some tutorials on the WEB about how AngularJS and REST web-services work. Then you will probably see that JHipster is a perfect match for what you want to do. Anyway, as @jdubois said this is not the good place to get training/information so you should post your question to stackoverflow (with tag jhipster) or on [gitter](https://gitter.im/jhipster/generator-jhipster)
