### ISSUE TITLE
Add an official Vagrant box for developing with JHipster

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2334]
I'm going to do a Vagrantfile for my "JHipster masterclass" trainings, and in the making I think it could be good to have our own official Vagrantfile:

- We could all share & learn to have the best possible Vagrantfile
- It would have the "official" tools for working with JHipster
- The idea is to have something like what they have for Laravel: https://github.com/laravel/homestead

It's going to have:

- A Linux OS, probably Ubuntu as I want something that's well-known for the trainees (even if I'm not a big fan of Ubunty for my own dev environment!)
- The same stack as our Dockerfile -> as our Dockerfile is based on Ubuntu, it's mostly porting the Dockerfile to Vagrant, so that's easy to do and maintain
- Some development tools: probably the SpringSource Tool Suite (we need to stay Open Source for the Vagrantfile), and MySQL tools (as it's the default production database) -> all the necessary tools for our "default" options, but not all the tools for all options (otherwise that would be a huge image -> maybe we can do several Vagrantfiles for those afterwards)
- Maybe also the Heroku tools so we can deploy easily to the cloud

I'm going to create a separate project for that, I will probably call it "DevBox" unless someone has a better idea.

**Comment by pascalgrimaud** [comment]
it's a good idea ! :+1:

**Comment by gmarziou** [comment]
Good idea even though I'd prefer PostgreSQL.
Do we have jhipster's stats about MySql vs. PostgreSQL?

**Comment by cbornet** [comment]
I guess the vagrantfile can include both

**Comment by jdubois** [comment]
I agree for Postgresql, this is what I usually use. But MySQL is the default, as more people use it.

Concerning the stats, today MySQL is 80% of all database used (and PostgreSQL is 11%) -> so MySQL is the clear winner here

**Comment by jdubois** [comment]
The Vagrantfile starts to be working OK:
https://github.com/jhipster/jhipster-devbox

A lot of work still needs to be done, so help if always welcome.

I'll be working on this probably for the next few hours, lots of noise in
Paris with the current ongoing terrorist attacks! And yes I'm coding during
this, because fuck terrorists.

Julien

On Fri, Nov 13, 2015 at 2:47 PM, Christophe Bornet <notifications@github.com
> wrote:

> I guess the vagrantfile can include both
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/2334#issuecomment-156434725>
> .
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by deepu105** [comment]
Just saw the news man its horrible, hope you are well and safe.

Fuckin cowardly bastards :(

**Comment by jdubois** [comment]
Yes, now I'm waiting to see if I know some of the victims.
Le 14 nov. 2015 4:13 AM, "Deepu k Sasidharan" <notifications@github.com> a
écrit :

> Just saw the news man its horrible, hope you are well and safe.
>
> Fuckin cowardly bastards :(

**Comment by jdubois** [comment]
Done at https://github.com/jhipster/jhipster-devbox

It's still marked "under development" but it's ready to use.

**Comment by PeterEltgroth** [comment]
@jdubois I agree, F them.  Very glad you are OK.  My thoughts are with you and your country.
