### ISSUE TITLE
Dockerfile has wrong env variable

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2335]
Our current Dockerfile, on line 25:

https://github.com/jhipster/jhipster-docker/blob/2d6a5355eefc96783a87a63d342f36072dc84a00/Dockerfile#L25

It uses a ${JAVA_VER} variable that does not exist -> how is this even working???

**Comment by pascalgrimaud** [comment]
You're right, it should be $JAVA_VERSION
I don't know how it can work, maybe no impact because this line is used to accept oracle license

**Comment by jdubois** [comment]
Fixed
