### ISSUE TITLE
JWT: auth contains only one value

### ISSUE THREAD

**Issue by dave0688** [jhipster/generator-jhipster#23376]
##### **Overview of the issue**

In the JWT token, there's only one role, even if two authorities are assigned for the user, i.e.:

```
{
  "sub": "my-email@email.de",
  "exp": 1696167323,
  "auth": "ROLE_MEMBER",
  "iat": 1693575323
}
```

So there is a mismatch between the authorities in the DB/User entity, and the JWT token.

The problem is that for example this here: 
```
@PreAuthorize("hasRole(\"" + AuthoritiesConstants.MEMBER + "\")")
```
is not working when the user has 2 roles (and the MEMBER role is the second one).

##### **Motivation for or Use Case**

JWT token gets generated and sent with every request.

##### **Reproduce the error**

Log into a jHipster application with a user. In User Management, assign a second role.

Log out, and log in again: Decode the jwt, and you will see that there's only one string in `auth`

##### **JHipster Version(s)**

8.0.0-beta.2

##### **Browsers and Operating System**

MacOS, Chrome 116

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
It's missing `jhipster info` from the project.

**Comment by mraible** [comment]
Closing because no response.
