### ISSUE TITLE
Getting "403 Forbidden" on "/management/jhiopenapigroups" when using "serviceDiscoveryType": "eureka" and running the application from IDE

### ISSUE THREAD

**Issue by anothergoodguy** [jhipster/generator-jhipster#23382]
##### **Overview of the issue**

Hi Team,
Greetings!
Pre-note: Please note this issue is reproducible only with `serviceDiscoveryType:eureka` in the configuration. I am not sure to file it under `jhipster-registery` or `generator-jhipster`. Please advise if this belongs to `jhipster-registery`, I can refile there.  Also not sure if this is a classpath issue or access issue.

I am using the attached [.yo-rc.json](https://github.com/jhipster/generator-jhipster/files/12506152/yo-rc.json.txt) file with `"serviceDiscoveryType": "eureka"`. application compiles and runs perfectly without any error on both terminal with `java -jar build/libs/store-0.0.1-SNAPSHOT.jar` command and from `the IDE intellij idea`. 

However, when running the generated application in  `the IDE intellij idea`, log-in to the webapp, navigate to `Administration --> API` and you can only see a blank page with console errors on the browser (please see the attached screenshot). Interestingly I don't see any errors in the application's runtime console on the IDE. 

I have tried to add the below lines on different / alternative runs to `*basepackage.conf.SecurityConfiguration`, but with no success.

`.requestMatchers("/management/jhiopenapigroups").permitAll()` 
`.requestMatchers("/management/jhiopenapigroups").hasAuthority(AuthoritiesConstants.ADMIN)`

<img width="1788" alt="image" src="https://github.com/jhipster/generator-jhipster/assets/24761452/121c7e51-b0d1-4665-87ef-fe419df63aec">

##### **Motivation for or Use Case**

Running the application in the IDE will allow to debug the application flows on a rest API, swagger in JHispter has been a great value add to do the same.

##### **Reproduce the error**

- Geenrate the application with the attached [.yo-rc.json](https://github.com/jhipster/generator-jhipster/files/12506152/yo-rc.json.txt) file. 
- Import/Open the generates project in the IDE IntelliJ Idea.
- On a terminal, start the sidecar containers with `docker-compose -f src/main/docker/services.yml up`
- Run the application on the IDE.
- After the server starts listening on the port 8081, please ope a browser and open the url `http://localhost:8081/`
- login with `admin/admin`
- navigate to `Administration --> API` o the web page.
- you can only see a blank page with console errors on the browser (please see the attached screenshot above). Interestingly I don't see any errors in the application's runtime console on the IDE. 

**Note:** this doesn't happen if you build and run the application on a terminal.

##### **Related issues**

N/A

##### **Suggest a Fix**

I have tried to add the below lines on different / alternative runs to `*basepackage.conf.SecurityConfiguration`, but with no success:

- `.requestMatchers("/management/jhiopenapigroups").permitAll()` 
- `.requestMatchers("/management/jhiopenapigroups").hasAuthority(AuthoritiesConstants.ADMIN)`

Also tried adding the following line to `*basepackage.web.filter.SpaWebFilter`, with no success:
- `!path.contains("/management/jhiopenapigroups") `

##### **JHipster Version(s)**

`8.0.0-beta.2`

##### **JHipster configuration**

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0-beta.2

```
store@0.0.1-SNAPSHOT /home/jhipster/app/biskate/tm-trial
└── generator-jhipster@8.0.0-beta.2
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "applicationType": "monolith",
  "authenticationType": "oauth2",
  "baseName": "store",
  "buildTool": "gradle",
  "cacheProvider": "infinispan",
  "clientFramework": "react",
  "clientTheme": "none",
  "creationTimestamp": 1693585493243,
  "databaseType": "sql",
  "devDatabaseType": "mysql",
  "devServerPort": 9060,
  "dtoSuffix": "DTO",
  "enableGradleEnterprise": null,
  "enableHibernateCache": true,
  "enableSwaggerCodegen": false,
  "enableTranslation": true,
  "entities": [],
  "entitySuffix": "",
  "gradleEnterpriseHost": null,
  "jhiPrefix": "jhi",
  "jhipsterVersion": "8.0.0-beta.2",
  "languages": [
    "en",
    "fr"
  ],
  "messageBroker": false,
  "microfrontend": false,
  "microfrontends": [],
  "nativeLanguage": "en",
  "packageFolder": "com/sample/platform",
  "packageName": "com.sample.platform",
  "pages": [],
  "pkType": "UUID",
  "prodDatabaseType": "mysql",
  "reactive": false,
  "searchEngine": "elasticsearch",
  "serverPort": 8081,
  "serverSideOptions": [
    "searchEngine:elasticsearch"
  ],
  "serviceDiscoveryType": "eureka",
  "skipCheckLengthOfIdentifier": false,
  "skipClient": false,
  "skipFakeData": false,
  "skipUserManagement": true,
  "testFrameworks": [],
  "websocket": false,
  "withAdminUi": true
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

git version 2.25.1

node: v18.16.1
npm: 9.5.1

'docker' command could not be found

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Please note this issue occurs  only with the combination of `serviceDiscoveryType:eureka` in the configuration and when we run the application from the IDE only. 

Application generated with `serviceDiscoveryType:false` doesn't produce this issue.

##### **Browsers and Operating System**

- `MACOS - Ventura - 13.4.1 `
- `JDK - openjdk version "17.0.8.1" 2023-08-24`
- `Google Chrome - Version 115.0.5790.170 (Official Build) (x86_64)`

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by anothergoodguy** [comment]
One more additional question team:

I see the generator doesn't ask for options of `Servcie Discovery` for monolith generation and it recomends `consul` for microservice generation. Please advise if there are any plans to retire `jhipster-registery` in the future as it will have significant impact on the existing ecosystem to migrate to `consul`.

**Comment by mshima** [comment]
This issue is not reproducible.
Works the endpoint works for `./gradlew` and `./gradlew -Pprod -Papi-docs`.
You should make sure api-docs profile is enabled.
In any case it's not related to jhipster, please post at stackoverflow.
