### ISSUE TITLE
Date field's not working on Safari

### ISSUE THREAD

**Issue by augurpl** [jhipster/generator-jhipster#2338]
I've generated entity with Date field. While working on Chrome this field has datepicker. When I log into application from safari I've figured that there is no datepicker on this field. I've checked  console and there is no error message

**Comment by atomfrede** [comment]
The datepicker in chrome is provided by chrome, so it doesn't work in other browsers. So this is not an issue as we don't have a datepicker yet. See https://github.com/jhipster/generator-jhipster/issues/1755 and the mailinglist for discussion.
