### ISSUE TITLE
Issue in Installing components through Jhipster from GitHub

### ISSUE THREAD

**Issue by sparun160782** [jhipster/generator-jhipster#2339]
Dear All,

When I tried to create an application with help of JHipster there some issues in fetching the components through git hub with bower.

I'm unable to understand what causes the problem and unable to proceed.

Same issue has also reported in stackoverflow .

At present not able to attach the screenshot in github, kindly please refer at stackoverflow at the below link.

http://stackoverflow.com/questions/33695482/issue-in-installing-components-through-jhipster-from-github.

Kindly let me know in case of more information.

Regards,
Arun

**Comment by jdubois** [comment]
Please don't cross post between StackOverflow and JHipster.... And please follow the guidelines....

This is a Bower issue, not a JHipster issue -> have a look at the Bower doc, it's a very common issue and I'm sure it's documented out there (I don't remember exactly but you need to execute one command)

**Comment by sparun160782** [comment]
Ok Thank You
