### ISSUE TITLE
Minor correction to the documentation on IntelliJ config

### ISSUE THREAD

**Issue by HereThereBeMonsters** [jhipster/generator-jhipster#2341]
Int the documentation on how to set up IntelliJ, section "JS code support" it says :

Go and open "File → Other Settings → Default Settings...."

I think this should actually be the main Preferences dialog i.e. (on Mac) : "IntelliJ → Preferences"

On Windows and Linux the preferences or settings are under the File menu (but I haven't a machine at hand to check exactly right now).

Indeed this setting should be done on a per-project basis, otherwise all new JavaScript projects will use the bower.json file from the current project.

**Comment by geraldhumphries** [comment]
+1

Should also add documentation about useful run configs for building/running/testing the app, e.g. running JS tests with the Karma plugin, Gradle bootRun/test, and Grunt serve (assuming you are using Gradle/Grunt).

**Comment by gmarziou** [comment]
Would you consider submitting a pull request?

**Comment by rampantlion103** [comment]
Hi Julien,
I love  your work, jhipster. Unfortunately, I am watching the local evening news here in New York, New York. The news is giving an update about the Hipster trend is pretty much outdated here in New York, as the news caster interviewed many people on the street and none of them wants to be identified as a Hipster. The younger ones wants to be identified differently, not a hipster. 

So the New Year coming, may I suggest a more easier to pronounce word, "JIPSTER” by removing the “H”. 

This is just a New Year suggestion, and there is no disrespectfulness here. This is just to improve the naming and easier to pronounce.

Sincerely Yours,
Ronald

**Comment by jdubois** [comment]
Hi @rampantlion103 I suggest opening a specific thread for this, as this is another topic and we have high quality requirements for such important matters :-)
Indeed, this is originally a French project, and it seems that we are a few years behind the US in terms of fashion, so for us it's still cool to be hipster, while in the US it's already outdated.

**Comment by rampantlion103** [comment]
It’s good to hear that hipster is still cool in France :-) and I will do what you suggested that I need to open up a separate thread…  But the funny thing is that I am currently using jhipster here in NY, and my client is in Manila Philippines whose parent company is a big French company.  Also, the first time I heard about JHipster was in my interview with Societe Generale Group here in NY. It is really a small world.

Happy New Year,
Sincerely Yours
Ron
