### ISSUE TITLE
Migrate Vue to Vite

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#23416]
##### **Overview of the feature request**

Vite is Vue's default bundler and webpack development is kind of stale.
We are already using vitest as test platform.

Features requiring special attention:
- i18n support with json merging.
- module federation (microfrontends).
- browsersync? is needed or just use hmr? use at microfrontends only since hmr is probably not supported?

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Microfrontend is not migrated because it's not working using vite, but we kept webpack for it.
Let's close it.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/176997

**Comment by DanielFran** [comment]
@mshima approved
