### ISSUE TITLE
Thread dump on the metrics page is not working anymore

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2342]
The thread dump on the metrics page at http://127.0.0.1:8080/#/metrics is not working anymore.

You need to click on the "eye" next to the "Threads", it will open a popup that used to display a thread dump. It's now empty -> maybe this is linked to Spring Boot 1.3.0 or the new Spring Boot devtools

**Comment by deepu105** [comment]
ill check this out this weekend
