### ISSUE TITLE
Add support for MySQL on Heroku

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2343]
Postgresql is the default database provided by Heroku, but 80% of our users are using MySQL, so we should also support it on Heroku.
We would support ClearDB -> https://elements.heroku.com/addons/cleardb
This is what we already do for CloudFoundry

For @jkutner 
- would you be interested in doing this?
- I'm preparing this for our "devbox" at https://github.com/jhipster/jhipster-devbox -> we would have all the default options (so MySQL), with Heroku deploy by default, so I need MySQL support for Heroku

**Comment by mraible** [comment]
I believe this already works on Heroku. I recently created an app with the
defaults (including MySQL) and deployed it to Heroku with no issues.

**Comment by jdubois** [comment]
Oh thanks @mraible I didn't check this in fact!!
I'm keeping this opened until I am sure this works

**Comment by jkutner** [comment]
Yes, this was completed in #2039. It's definitely being used by folks in the wild.

**Comment by jdubois** [comment]
Oh great, can't wait to test it!
That will be the final touch of my new JHipster training!
