### ISSUE TITLE
Expose test helper to blueprints

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#23431]
##### **Overview of the feature request**

Expose jhipster test helpers:
https://github.com/jhipster/generator-jhipster/blob/be3bc1c019b75446caaf6098ed73dd7e74eacad2/test/support/helpers.mts#L86-L205

jhipster helpers provides features that can be used for blueprint like:
```
import {
  basicHelpers,
  /* files are not committed to disk */
  dryRunHelpers,
  /* prettier is ignored for improved speed */
  skipPrettierHelpers,
  /* disables commit and prettier */
  defaultHelpers,
} from 'generator-jhipster/testing';

defaultHelpers.run().withJHipsterConfig();
```

And drop blueprint test utils.
https://github.com/jhipster/generator-jhipster/blob/main/generators/generate-blueprint/templates/test/utils.mjs.ejs

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/170966

**Comment by DanielFran** [comment]
@mshima approved
