### ISSUE TITLE
Simplify microfrontend configuration using @angular-architects/module-federation

### ISSUE THREAD

**Issue by amirensit** [jhipster/generator-jhipster#23457]
##### **Overview of the feature request**
I generated an example of jhipster v8 for microfrontend.
I noticed the native use of ModuleFederationPlugin like this:
```
plugins: [
      new ModuleFederationPlugin({
      ...
      })
      ]
```
But I already see the use of `import { loadRemoteModule } from '@angular-architects/module-federation-runtime';`
As I know, when we use @angular-architects/module-federation, we might not need to explicitly configure the ModuleFederationPlugin ourselves because this package abstracts and simplifies the setup for us.
Here is a an [example](https://github.com/manfredsteyer/module-federation-with-angular-dynamic) of project

**Comment by mshima** [comment]
This maybe true if you have shared libs in external packages.
But we have shared lib in the application:
https://github.com/jhipster/generator-jhipster/blob/516248fa99511115f022216dbb03f51d2fb009b7/generators/angular/templates/webpack/webpack.microfrontend.js.ejs#L67-L100

They must be singletons.

**Comment by mshima** [comment]
We could simplify those shared libs by using
```
cont mapExportedLibs = libs => Object.fromEntries(libs.map(lib, [lib, { singleton: true, import: lib, requiredVersion: version }])):

shared: {
  …mapExportedLibs['app/config/input.constants', …],
},
```

@amirensit can you contribute with a PR?

**Comment by amirensit** [comment]
The problem for contribution is the lack of time. I don't have enough time to contribute by code. I can just give comments and suggest improvements ^^

**Comment by mraible** [comment]
Added bug bounty to encourage contribution.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/176996

**Comment by DanielFran** [comment]
@mshima approved
