### ISSUE TITLE
Html5ModeFilter Enhancement

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#2350]
Html5ModeFilter needs an enhancement. When I reload page on site.com/1, all works fine, but when reload on site.com/1/1, It returns an error. The bug is in StringUtils.countMatches(requestURI, "/") == 1. I fixed it by changing to StringUtils.countMatches(requestURI, "/") <= 2. If I delete it, nothing works.

**Comment by deepu105** [comment]
Why have you opened 3 issues for similar problems.
And the info you provided is not sufficient for us to do anything

**Comment by delverdev** [comment]
I think it is different problems. The solution you can do is change code on your [https://jhipster.github.io/tips/010_tip_configuring_html_5_mode.html](page).

**Comment by deepu105** [comment]
I dont think we have such a tip existing

**Comment by delverdev** [comment]
It means someone edited the code. My [code](http://pastebin.com/qip93C3L) that I copied from that page.

**Comment by jdubois** [comment]
It's on tip from @brevleq so not really a JHipster bug itself -> it has just been updated, can you have a look?
I'm closing this as this isn't a JHipster bug

**Comment by brevleq** [comment]
Hi @delverdev, I've created that tip and corrected it yesterday. The old code was redirecting instead of forward and gave me had some problems in production. Take a look at the tip again, it is less error prone now.

**Comment by delverdev** [comment]
Hi @brevleq. Saw you've created AngularJSForwardController. Seems like it work, but you can beatify the code.
value of RequestMapping annotation can get not only strings but string array too!

    @RequestMapping(value = { "/login**", "/activate*", ........and so on! }, method = RequestMethod.GET)
    public void methodsToRedirect(HttpServletRequest httpRequest, HttpServletResponse httpResponse) {
        redirect(httpRequest, httpResponse);
    }

**Comment by brevleq** [comment]
Thanks for your help @delverdev. I will test this option in my environment and update the tip accordingly

**Comment by delverdev** [comment]
@brevleq, make a little fix in controller:
pageForward method:
redirect(httpRequest, httpResponse); -> forward(httpRequest, httpResponse);
