### ISSUE TITLE
Api doesn't work with Html5ModeFilter

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#2351]
When go to /api/*, it redirects to #/api/* then to / and returns index.html code.

**Comment by delverdev** [comment]
Solved. Changed next line:
if (!requestURI.equals("/") && !requestURI.contains(".html") && StringUtils.countMatches(requestURI, "/") == 1)
to:
if (!requestURI.equals("/") && !requestURI.contains(".html") && StringUtils.countMatches(requestURI, "/") == 1 && !requestURI.startsWith("/api/"))

**Comment by jdubois** [comment]
Same as previous issues #2353 #2350
