### ISSUE TITLE
404 while generating entities on existing project

### ISSUE THREAD

**Issue by kamssiopeia** [jhipster/generator-jhipster#23524]
##### **Overview of the issue**

I'm getting 404 while trying to regenerate entities using `jhipster jdl` command. I notced this issue two days ago, before that everything worked with no problems. Last time I regenerated entities was on 27th of July

```
❯ jhipster jdl db/jhipster_jdl.jh
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Downloading file: https://raw.githubusercontent.com/jhipster/jdl-samples/master/db/jhipster_jdl.jh
Error: Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/master/db/jhipster_jdl.jh: 404 - Not Found
    at ClientRequest.<anonymous> (/home/kamgol/Projekty/ANNKeeper/node_modules/generator-jhipster/cli/jdl.js:44:35)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
```

##### **Motivation for or Use Case**

Adding new entities through `jh` file

##### **Reproduce the error**

Run command `jhipster jdl file_name.jh`

##### **JHipster Version(s)**

* jhipster: `6.10.1`
* node: `16.13.2`
* npm: `8.1.2`

##### **JHipster configuration**

```
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.1",
    "baseName": "",
    "packageName": "",
    "packageFolder": "",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": ["gatling"],
    "jhiPrefix": "jhi",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "pl"],
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "blueprints": [],
    "embeddableLaunchScript": false,
    "creationTimestamp": 1599742219689
  }
}

</pre>
</details>
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Error is during creation but it's not related to entity configuration

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran we should keep jdl-samples master branch for v6 and main for v7

**Comment by kamssiopeia** [comment]
I think i resolved my own issue by using `jhipster import-jdl file_name.jh`. I would like to know if command in documentation is meant to be used by newer jhipster versions?

**Comment by mshima** [comment]
In any case jhipster v6 is not supported anymore.
If the file is not found locally, we try to download from jdl-samples repository.
You should check if the file is present locally.

**Comment by mshima** [comment]
> I think i resolved my own issue by using `jhipster import-jdl file_name.jh`. I would like to know if command in documentation is meant to be used by newer jhipster versions?

Yes. For older jhipster version you should look at the archive.

**Comment by kamssiopeia** [comment]
> > I think i resolved my own issue by using `jhipster import-jdl file_name.jh`. I would like to know if command in documentation is meant to be used by newer jhipster versions?
> 
> Yes. For older jhipster version you should look at the archive.

Ok, thank you!

**Comment by DanielFran** [comment]
> @DanielFran we should keep jdl-samples master branch for v6 and main for v7

Done
