### ISSUE TITLE
JDL file name shall be reported in an error message for JDL import

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#23533]
##### **Overview of the issue**

If an error occurs while importing multiple JDL files, a user won't know which file the error occurs from an error message such as 
```
error: Syntax error message:
        MismatchedTokenException: Found an invalid token '@', at line: 559 and column: 48.
        Please make sure your JDL content does not use invalid characters, keywords or options.

```

##### **Motivation for or Use Case**

A better use experience by making it easier to locate a bug.

##### **JHipster Version(s)**

7.9.4

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@vw98075 can you provide a PR?

**Comment by qmonmert** [comment]
we have the file name in logs
<img width="1305" alt="image" src="https://github.com/jhipster/generator-jhipster/assets/9989211/28c80bca-3085-468a-b65b-39cf8f29589b">
here `jhipster-jdl.jdl`

cc @mshima @DanielFran

**Comment by mshima** [comment]
The issue is about parsing more than one jdl.
All jdl files are concatenated and treated as 1.
To implement this enhancement, we need to add markers to map lines to a jdl filename.
