### ISSUE TITLE
Html5ModeFilter with WebSockets

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#2353]
When I'm on index.html, websockets connect and work but when I'm reload page on other page (not route from main), it returns an error. In browser logs I can see why error appears. Websocket on other page except main goes to localhost:8080/SAMPLEPAGEwebsocket/tracker. I've solved the problem by edit next line from components/tracker/tracker.service.js:
var url = '//' + loc.host + loc.pathname + '/websocket/tracker';
to:
var url = '//' + loc.host + '/websocket/tracker'; 
Seems like all work, but I'm not sure I solved it right.

**Comment by jdubois** [comment]
This is a tip from @brevleq maybe you can contact him or update the tip?

@brevleq can you have a look?

I'm closing this as this isn't a JHipster bug.
