### ISSUE TITLE
@CrossOrigin from Spring 4.2+ plan?

### ISSUE THREAD

**Issue by LaughingLogic** [jhipster/generator-jhipster#2354]
Any plans for adding the Spring 4.2 @CrossOrigin annotation support?

org.springframework.web.bind.annotation.CrossOrigin

Article: https://spring.io/blog/2015/06/08/cors-support-in-spring-framework

**Comment by deepu105** [comment]
I think its already added by @cbornet

**Comment by cbornet** [comment]
Since 2.23.1, you can configure CORS globally from the application.yml file.
The ```@CrossOrigin``` annotation is for more fine-grained configuration of CORS (up to the method level). And since it is supported by Spring, you can of course use it in your JHipster application.

**Comment by LaughingLogic** [comment]
Thanks, good to know.
