### ISSUE TITLE
Upgrade Spring Boot to v1.3.0.RELEASE

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#2356]
Few hours ago, there was a release of spring boot v1.3.0.RELEASE
https://spring.io/blog/2015/11/16/spring-boot-1-3-0-released

We should upgrade 1.3.0.RC1 to 1.3.0.RELEASE

**Comment by deepu105** [comment]
You beat me to it :)
Few things i would like to work on after upgrade
1. Add the new health check endpoints to our health page
2. Show metrics for hazelcast
3. Add more color to jh banner may be :)

**Comment by pascalgrimaud** [comment]
lol the color to JH banner would be fun

**Comment by jdubois** [comment]
Yes, normally we don't have a lot of new stuff as I've already done the migration for 1.3.0.RC1
Be careful with the Hibernate L2 cache, I'm doing some work to monitor the caching of entities and I don't think Spring Boot does this (it's just monitoring of all caches, nothing specific for the Hibernate L2 cache, but I haven't checked this for some time, so it might have changed)
The color banner can be fun, but maybe we could use for something useful?

**Comment by atomfrede** [comment]
:+1: For colored banner ;)

**Comment by mraible** [comment]
A first pass at a colored banner: https://github.com/jhipster/generator-jhipster/pull/2377

**Comment by jdubois** [comment]
I'm closing this as the migration is done! There wasn't anything to do except the color banner :-)
