### ISSUE TITLE
Sources generated with MongoDB and ElasticSearch don't compile

### ISSUE THREAD

**Issue by sircelsiussexy** [jhipster/generator-jhipster#2358]
When running the latest (v2.23.1) generator and setting the following options:

```` json
{
                "databaseType": "mongodb",
                "searchEngine": "elasticsearch"
}
````

The generated sources (by running `mvn`)do not compile with the following error:

````
[ERROR] diagnostic: /home/jhipster/app/src/main/java/com/mycompany/myapp/domain/User.java:11: error: a type with the same simple name is already defined by the single-type-import of org.springframework.data.elasticsearch.annotations.Document
import org.springframework.data.mongodb.core.mapping.Document;
````

This is a pretty easy fix, I'm working on a PR.

AFAIK, this happens both for the generated `User.java` class when running the main generator and for the `_Entity.java` class when running the `entity` sub-generator.

**Comment by pascalgrimaud** [comment]
You should not be able to use mongodb + elasticsearch => http://jhipster.github.io/using_elasticsearch.html
Elasticsearch only works with SQL databases.

How did you manage to have this ? Did you manually change your .yo-rc.json ?

**Comment by sircelsiussexy** [comment]
Nope, I used v2.23.1 out of the box.

**Comment by sircelsiussexy** [comment]
And even if ES is only supported with SQL atm, I think it's worth adding a condition in the templates.

`_User.java` currently has a condition only on `searchEngine == 'elasticsearch'`, it might be woth adding a check on `databaseType` as well I guess.

**Comment by jdubois** [comment]
I need to check, maybe I did an error in the templates that allow you to choose both options, which you shouldn't.

Of course it can be improved, but that's only to prevent the error you add.

**Comment by sircelsiussexy** [comment]
Just checked, I was running `v2.23.0`, my mistake (multiple node environments are error prone :cry: )

`v2.23.1` does remove the ES choice when you pick mongo.

**Comment by pascalgrimaud** [comment]
Yes, I did the fix : https://github.com/jhipster/generator-jhipster/pull/2238
That's why I didn't understand how it is possible ;)
