### ISSUE TITLE
Initial schema creation error when using OAuth2 with Oracle DB

### ISSUE THREAD

**Issue by richteri** [jhipster/generator-jhipster#2359]
* **Overview of the issue**

"ORA-00910: specified length too long for its datatype" error is thrown when creating table oauth_client_details due to VARCHAR2 length limit of 4000 bytes in Oracle.

Caused by: liquibase.exception.DatabaseException: ORA-00910: specified length too long for its datatype
 [Failed SQL: CREATE TABLE TS_APP.oauth_client_details (client_id VARCHAR2(255) NOT NULL, resource_ids VARCHAR2(255), client_secret VARCHAR2(255), scope VARCHAR2(255), authorized_grant_types VARCHAR2(255), web_server_redirect_uri VARCHAR2(255), authorities VARCHAR2(255), access_token_validity NUMBER(10), refresh_token_validity NUMBER(10), additional_information VARCHAR2(4096), autoapprove VARCHAR2(4096), CONSTRAINT PK_OAUTH_CLIENT_DETAILS PRIMARY KEY (client_id))]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:316) ~[liquibase-core-3.4.1.jar:na]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55) ~[liquibase-core-3.4.1.jar:na]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:122) ~[liquibase-core-3.4.1.jar:na]
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1247) ~[liquibase-core-3.4.1.jar:na]
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1230) ~[liquibase-core-3.4.1.jar:na]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:548) ~[liquibase-core-3.4.1.jar:na]
        ... 12 common frames omitted

* **Motivation for or Use Case** 

Using JHipster with Oracle XE Unicode.

* **JHipster Version(s)** 
2.23.1, no regression

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "baseName": "mythos25jh",
    "packageName": "com.adwareresearch.mythos",
    "packageFolder": "com/adwareresearch/mythos",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": "no",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "fd01f0e50924233471b7ad697dbbed3c25cc4942",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ]
  }
}

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
N/A

* **Browsers and Operating System** 
N/A

* **Reproduce the error** 
Chose Oracle and OAuth2 during project init.

* **Related issues** 

* **Suggest a Fix** 

Reduce the size of the columns 'additional_information' and 'autoapprove' in table 'oauth_client_details' in 00000000000000_initial_schema.xml to 4000 bytes from 4096

**Comment by jdubois** [comment]
Yes I remember already seeing this on an older Oracle version -> can you give us your Oracle version?

**Comment by richteri** [comment]
Hi! I'm using Oracle Database 11g Express Edition for development and the non-Express for production. I think 11gR2 is the most recent version in the Express product line. It's easy to modify initial_schema.xml before the first run but do we really need that extra 96 characters? We might, I'm new to OAuth2.

**Comment by jdubois** [comment]
I have to check if it's clearly written (cc @deepu105 ) but we only support the latest version Oracle, and have no plan in supporting earlier versions.
I don't know for "Express Edition", it looks like it doesn't exist anymore in the last (version 12) release.

**Comment by deepu105** [comment]
Yes we only support 12c as 11g is EOL already sorry. I guess we dont have
that issue with 12c

**Comment by richteri** [comment]
OK, np., I'll need to upgrade to 12c.
