### ISSUE TITLE
Encrypt properties in configuration file

### ISSUE THREAD

**Issue by jstradej** [jhipster/generator-jhipster#236]
Is there any way to encrypt properties in the configuration file?

application-prod.yml:

``` properties
mail.smtp.password: ENC(ISahsyegsFssYTTu+izOg==)
```

In old project with Spring 3.1 and XML configuration I use [Jasypt](http://www.jasypt.org/) library.

**Comment by abshkd** [comment]
I'd like to reopen this. In Spring Cloud config server I can easily encrypt the config at rest. However simply specifying `encrypt.key` in bootstrap doesnt work in jhipster. using version 4.2.
Unless I missed something.

**Comment by gmarziou** [comment]
@abshkd commenting a 3 years old closed issue does not really help. Please open a new issue with details.
