### ISSUE TITLE
Saving object with 1-to-n cardinality

### ISSUE THREAD

**Issue by jodevan** [jhipster/generator-jhipster#2360]
I asked this question in StackOverflow:
http://stackoverflow.com/questions/33727749/saving-object-with-1-to-n-cardinality/

I ended up answering it by myself, but I'm still curious to know if this is a JHipster limitation or if I'm not doing it in the correct way. The issue seems to happen whenever I invoke a service and I need to pass a list to it. For instance, if my request sends {id: 1, name: 'whatever'}, this works okay. However, if it sends {id:1, name: ' whatever', colors: ['red', 'green', 'blue']}, the service fails.
It looks like I have to fix the service annotation to accept json content by adding header : "application/json" to it (please, refer to the link in StackOverflow).
Thoughts?

**Comment by Vaelyr** [comment]
Can you share your modified javascript and the rest controller + dto. Thanks.

**Comment by jodevan** [comment]
Sorry for the late response. Here are the relevant parts:

User entity:
```java
public class User extends AbstractAuditingEntity implements Serializable {
    // Default JHipster generated attributes

    @ManyToMany (fetch = FetchType.EAGER)
    @JoinTable(
            name = "USER_SYSTEM",
            joinColumns = {@JoinColumn(name = "user_id", referencedColumnName = "id")},
            inverseJoinColumns = {@JoinColumn(name = "system_id", referencedColumnName = "id")})
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<System> systems = new HashSet<>();

    public Set<System> getSystems() {
        return systems;
    }

    public void setSystems(Set<System> systems) {
        this.systems = systems;
    }
    
}
```

UserDTO:

```java
public class UserDTO {

    // Default JHipster generated attributes
    private Set<System> systems;
    
    public UserDTO() { }

    public UserDTO(String login, String firstName, String lastName, String password, 
		String email, String langKey, Set<System> systems, List<String> roles) {
        this.login = login;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.langKey = langKey;
        this.roles = roles;
        this.systems = systems;
    }
}
```

register.controller.js:
```javascript
'use strict';

angular.module('systemApp')
    .controller('RegisterController', function ($scope, $http, $timeout, $state, Auth) {
        $scope.success = null;
        $scope.error = null;
        $scope.doNotMatch = null;
        $scope.errorUserExists = null;
        $scope.registerAccount = {};
        $scope.registerAccount = {
           /* Array of systems. This is enough to cause the code to break, since 
            * an array will be sent in the json upon submitting the page 
            */
            systems: [] 
        };
        $timeout(function (){angular.element('[ng-model="registerAccount.login"]').focus();});
        // Irrelevant code
    });
```

AccountResource.java:
```java
    @RequestMapping(value = "/register",
            method = RequestMethod.POST,
            headers="Accept=application/json", // relevant line added
            produces = MediaType.TEXT_PLAIN_VALUE)
    @Timed
    public ResponseEntity<?> registerAccount(@Valid @RequestBody UserDTO userDTO, HttpServletRequest request) {
		/* Default JHipster generated code, but now I can do things like userDTO.getSystems() */
    }
```

**Comment by jdubois** [comment]
I just tried something very similar on our `master` branch and it worked without any issue.

- Created a "Foo" entity, which has uses a DTO
- In the DTO, I added a Collection of "Systems"
- In the AngularJS controller, I added an array of Systems, with 2 Strings "aaa" and "bbb" in it

-> the logger gets those Strings in the DTO

    i.g.jhipster.aop.logging.LoggingAspect   : Enter: io.github.jhipster.web.rest.FooResource.updateFoo() with argument[s] = [FooDTO{id=1, aaa='aaaa', systems=[aaa, bbb]}]
    io.github.jhipster.web.rest.FooResource  : REST request to update Foo : FooDTO{id=1, aaa='aaaa', systems=[aaa, bbb]}

So I guess this has been corrected since, or a library upgrade did the trick.

**Comment by jodevan** [comment]
Fair enough.
