### ISSUE TITLE
Unit test getAllEntities() fail for a Entity with more than 19 rows.

### ISSUE THREAD

**Issue by lsolisc** [jhipster/generator-jhipster#2361]
When a entity is populated with more than 19 items, the test "getAllEntities()" fail, how a small contribution to this awesome project i suggest add a sort direction to the GET url using the id field:

        restSkosPropertyMockMvc.perform(get("/api/entities?sort=id,DESC"))

**Comment by jdubois** [comment]
Yes, it fails because of pagination, so I suppose that if you sort it then you'll have the latest ID, which would solve the issue...
Would you like to make the PR, so you are referenced as the author of this?

**Comment by Vaelyr** [comment]
This is not why you assume the test would fail. Why is the test data populated with 19 records at first place? Testing with that amount of data is bad.
