### ISSUE TITLE
data-util.service.js not included in index.html causing error

### ISSUE THREAD

**Issue by l7777777b** [jhipster/generator-jhipster#2363]
anyone knows why `<script src="scripts/components/util/data-util.service.js"></script>` doesn't get included in index.html? since it's causing error on few of my generated entities page.

**Comment by deepu105** [comment]
fixed via https://github.com/jhipster/generator-jhipster/commit/a48fc1fd2ffd61fa2ecdba82f729e02b4e094bb3
