### ISSUE TITLE
Heroku generator update.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#23686]
##### **Overview of the feature request**

There is some discussion about heroku generator future at https://github.com/jhipster/generator-jhipster/issues/19551.
A proposal to drop it was done at https://github.com/jhipster/generator-jhipster/issues/19112.
@mraible wants to keep support for it https://github.com/jhipster/generator-jhipster/issues/19112#issuecomment-1722243400.
And following the comment I agree we should keep it, because old tutorials may be outdated but they keep around forever.
Keeping good promoting materials valid (or near) is good for JHipster.

Blueprints overrides heroku too ([dotnetcore](https://github.com/jhipster/jhipster-dotnetcore/tree/main/generators/heroku), [micronaut](https://github.com/jhipster/generator-jhipster-micronaut/tree/main/generators/heroku)).

Current heroku implementation is too complicated and uses outdated standards. New need to:
- replace `child_process` with `this.spawn[Command][Sync]`.
- drop `run-async` with `async function`.
- simplify.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I'll see if I can bribe @deepu105 into helping me with this next week when we're together at Devoxx Belgium. 😉

**Comment by deepu105** [comment]
I haven't used Heroku in a loooong time. I'll check it out this weekend and
see what I can do

**Comment by mraible** [comment]
@mshima Do you have an example of these refactorings in another sub-generator? Otherwise, I'll just be doing a find-and-replace and hoping things work. It looks like tests will need to change too, since there's code like this:

```js
  beforeEach(() => {
    stub = sinon.stub(ChildProcess, 'exec');
    stub.withArgs('heroku --version').yields(false);
    stub.withArgs('heroku plugins').yields(false, 'heroku-cli-deploy');
    stub.withArgs('git init').yields([false, '', '']);
  });
  afterEach(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (ChildProcess.exec as any).restore();
  });
```

**Comment by mshima** [comment]
You can see spawnMocks here:
https://github.com/jhipster/generator-jhipster/commit/f6e9d3825bb157ea0fa394e6568e43c30870ed7d

To simulate spawn return create a sinon stub:
```
const stub = sinon.stub();
stub.withArgs('spawnCommand', 'heroku --version').yields(false);
```

note that `spawnCommand` can be one of spawn/spawnSync/spawnCommand/spawnCommandSync, the one you used to call the specific command.

and inject:
```
helpers
  …
  .withSpawnMock(stub)
  …;
```

**Comment by mshima** [comment]
Is there microservice stack support?
If no I think ci-cd generator can be used as base.
The ci-cd rework is implemented at https://github.com/jhipster/generator-jhipster/pull/23718/files

**Comment by mraible** [comment]
@mshima There isn't support for deploying a whole microservices stack, but there is support for individual apps. @jdubois published [a tutorial on Heroku's blog](https://blog.heroku.com/bootstrapping_your_microservices_architecture_with_jhipster_and_spring) in 2016 that shows how to do it.

**Comment by mraible** [comment]
@mshima I took a pass at updating the Heroku generator in https://github.com/jhipster/generator-jhipster/pull/23971. I'm not sure I did this one correctly:

* drop `run-async` with `async function`
