### ISSUE TITLE
[enhancement] Make Java code generated checkstyle compliant

### ISSUE THREAD

**Issue by pmadridb** [jhipster/generator-jhipster#2368]
Make the Java code compliant with the default checkstyle configuration.

**Comment by jdubois** [comment]
Not sure about this one, as we already follow Intellij IDEA's style
And last time I used it, Checkstyle rules were not very good (but that was something like 10 years ago)
Maybe we could have our own Checkstyle rules?

**Comment by jdubois** [comment]
As far as I'm concerned I'm happy with our current code style and will not change it, so unless there is a good reason to change this, I'm closing this.
I'd be happy if we had our own Checkstyle rules, so if anybody is interested that would make a good PR. I don't know if Checkstyle is popular or not?

**Comment by geyuqiu** [comment]
work around over: 

`mvnw -q -Dcheckstyle.skip clean verify`
