### ISSUE TITLE
Text duplicated in Documentation

### ISSUE THREAD

**Issue by rgaiacs** [jhipster/generator-jhipster#23738]
I couldn't open an issue at https://github.com/jhipster/jhipster.github.io.

https://www.jhipster.tech/security/#session has

> If you want to use Keycloak with Docker Compose, be sure to read our [Docker Compose documentation](https://www.jhipster.tech/docker-compose/), and configure correctly your /etc/hosts for Keycloak.

twice.

![Screenshot from 2023-10-04 09-42-17](https://github.com/jhipster/generator-jhipster/assets/1506457/ab9fdb57-1c0d-402f-81d2-239d7eec1032)

**Comment by qmonmert** [comment]
well seen @rgaiacs thanks
