### ISSUE TITLE
[enhancement] Add / Delete Users by Admin Users

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#2374]
Currently there is no add / delete users for user management under admin. If nobody has any concern I can do a PR for this.

**Comment by deepu105** [comment]
:+1:

**Comment by gmarziou** [comment]
Well, usually I don't like to delete users, I prefer to flag them as blocked or inactive, it's easier to rollback in case of error.

**Comment by deepu105** [comment]
We already have activate inactive, but i think its good to have a delete
and create as well, as its a common use case i have seen a lot, in
applications where the user provisioning is managed by admins especially in
internal application for companies etc

**Comment by gmarziou** [comment]
You're right and also we have this scheduled purge of unactivated users that I recently forgot to disable in an app without activation ;)

**Comment by deepu105** [comment]
Pr merged
