### ISSUE TITLE
In React, a numeric field of an entity is sent as a string in the JSON via REST API.

### ISSUE THREAD

**Issue by hide212131** [jhipster/generator-jhipster#23763]
##### **Overview of the issue**

I'll provide an example below. `salary` represents the numeric field.

When newly inputted, the field is sent as a string.
<img width="277" alt="field_new" src="https://github.com/jhipster/generator-jhipster/assets/3602892/1ce046c1-babb-4812-9880-fca1a1646d43">

When updated without any changes, the field is sent as a number.
<img width="337" alt="feild_update_nothing" src="https://github.com/jhipster/generator-jhipster/assets/3602892/935ad06f-3909-43fb-9aaa-c6a2abe82af4">

When updated with changes, the field is sent as a string.
<img width="166" alt="field_update" src="https://github.com/jhipster/generator-jhipster/assets/3602892/b9dc1e7d-7b6f-4bc1-b03f-4f95bf318975">

##### **Motivation for or Use Case**

While this doesn't directly cause an error, it can lead to confusion during frontend development that adheres to API specifications.

##### **Reproduce the error**

Perform registration and update operations on numeric fields.

##### **Suggest a Fix**

The following processing should be performed on numeric fields.

{entityname}-update.tsx: 
```typescript
  const saveEntity = values => {
    values.salary = values.salary ? parseInt(values.salary, 10) : values.salary;
```

##### **JHipster Version(s)**

8.0.0-beta.3

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "myApp",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientTestFrameworks": [],
    "clientTheme": "none",
    "creationTimestamp": 1696591837279,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "Employee"
    ],
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.0.0-beta.3",
    "languages": [
      "ja",
      "en",
      "fr"
    ],
    "lastLiquibaseTimestamp": 1696591897000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "ja",
    "packageName": "com.mycompany.myapp",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment GraalVM CE 22.3.3 (build 17.0.8+7-jvmci-22.3-b22)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.3 (build 17.0.8+7-jvmci-22.3-b22, mixed mode, sharing)

git version 2.39.3 (Apple Git-145)

node: v18.17.1
npm: 9.6.7

Docker version 24.0.6, build ed223bc

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Employee {
  firstName String
  salary Long
}
search Employee with no

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>Employee.json</summary>
```
{
  "applications": "*",
  "changelogDate": "20231006113137",
  "entityTableName": "employee",
  "fields": [
    {
      "fieldName": "firstName",
      "fieldType": "String"
    },
    {
      "fieldName": "salary",
      "fieldType": "Long"
    }
  ],
  "name": "Employee",
  "relationships": [],
  "searchEngine": "no"
}
```
</details>

##### **Browsers and Operating System**

chrome , macos

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@hide212131 I don't reproduce, I try with differents numeric fields and it seems to work
![image](https://github.com/jhipster/generator-jhipster/assets/9989211/1859e342-af37-4417-96ac-3b92f24c4aeb)
![image](https://github.com/jhipster/generator-jhipster/assets/9989211/3fa97c39-2f3f-4d86-b9dd-5a325cfa7529)
![image](https://github.com/jhipster/generator-jhipster/assets/9989211/ff0121d9-263d-443a-a1e3-0b1a9725e9bd)

**Comment by hide212131** [comment]
@qmonmert Thank you for investigating the issue. 
I apologize for the lack of clarity in my initial description.
The response message is correct; the issue lies with the request message.

<img width="521" alt="request" src="https://github.com/jhipster/generator-jhipster/assets/3602892/fcfc5a32-058a-4285-9606-d11881180fba">
<img width="401" alt="response" src="https://github.com/jhipster/generator-jhipster/assets/3602892/5205955f-5fc8-49cb-b6b6-4170aa4385b2">

**Comment by qmonmert** [comment]
@hide212131 thanks for the precision, I confirm the bug
