### ISSUE TITLE
Implement angular generator

### ISSUE THREAD

**Issue by superandrew** [jhipster/generator-jhipster#2379]
Hello, I would suggest to implement generator for angular such as 

    yo:angular view mywiew

or

    yo:angular route myroute

or

    yo:angular controller mycontroller

As seen in https://github.com/yeoman/generator-angular

**Comment by deepu105** [comment]
I think you can use angular generator on a jhipster generated folder, as we follow similar code structure. But i font think we have plans to support these subs directly unless we have a plugin system @jdubois correct me if im wrong

**Comment by gmarziou** [comment]
This has been discussed earlier, please search the issues for details.
Conclusion was that some generators may work, some may not.
It's too hard to maintrain compatibility between generators which may not use same coding style.

**Comment by jdubois** [comment]
Yes @deepu105 you are correct:

- They are supposed to work (this was done be @jmirc ) as we have the same structure. But it's not 100% perfect so I'm not writing this everywhere in the doc
- That's the basic idea behind the "plugin" system -> it's mostly facilitating or validating how to use other generators in the JHipster project
