### ISSUE TITLE
Vue frontend doesn't detect custom primary key names

### ISSUE THREAD

**Issue by rjbgaspar** [jhipster/generator-jhipster#23848]
##### **Overview of the issue**

In case we use a primary key with a name other then id the vuejs frontend incorrect generated.

##### **Motivation for or Use Case**
n.a.

##### **Reproduce the error**

Generate a new project using the JDL provided in "JHipster configuration" section, start the project, go to “Employees” entity and you wont be able to see the id.

##### **Related issues**
n.a.

##### **Suggest a Fix**
Change the files responsible for generating the vuejs frontened, to mach the appropriated key. 

It should target the
- src/main/webapp/app/entities/entity/*
- src/main/webapp/app/shared/model/entity.model.ts
- src/test/javascript/spec/app/entities/entity/*

##### **JHipster Version(s)**
[Release 7.9.4](https://www.jhipster.tech/2023/09/05/jhipster-release-7.9.4.html) (2023-09-05)

##### **JHipster configuration**
The following JDL can be use to demonstrate the issue

  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    baseName primarykeynonid,
    reactive true
    applicationType monolith
    authenticationType jwt
    buildTool maven
    packageName com.jhipster.demo.primarykeynonid,
    clientFramework vue
    prodDatabaseType mssql,
    enableTranslation true
    nativeLanguage pt-pt
    languages [en, pt-pt]
  }
  entities *
}

@dto(mapstruct)
@service(serviceClass)
entity Employee(FUNC1) {
    /**
     * The employee number
     */
    @fieldNameAsDatabaseColumn(NFUNC)
    @Id number String required unique
    /**
     * The employee name
     */
    @fieldNameAsDatabaseColumn(NOME)
    name String required
}

  </pre>
  </details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
n.a.

##### **Browsers and Operating System**
n.a.

**Comment by mshima** [comment]
@rjbgaspar can you contribute with a PR?

**Comment by rjbgaspar** [comment]
Hi @mshima, 

As I mentioned in the other issue, I don't have the project knowledge to do it.

**Comment by mshima** [comment]
Go to this folder and replace `id` with `<%- primaryKey.name %>` (`<%- relationship.otherEntity.primaryKey.name %>`) for relationships) whenever applicable.

**Comment by qmonmert** [comment]
@mshima is it normal that the backend sends this for a one-to-one relationship?
![image](https://github.com/jhipster/generator-jhipster/assets/9989211/cb870698-002c-4b63-9ce1-257dccfb3367)

**Comment by mshima** [comment]
> @mshima is it normal that the backend sends this for a one-to-one relationship?

I don't think so.

**Comment by qmonmert** [comment]
I generate same entities with `Vue` and `Angular` and the backend code is different 
`Vue`
``` 
@Table("player")
@SuppressWarnings("common-java:DuplicatedBlocks")
public class Player implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column("id")
    private Long id;

    @Column("name")
    private String name;

    @Transient
    private Foot foot;

    @Column("foot_id")
    private Long footId;
``` 

`Angular`
```
@Entity
@Table(name = "player")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@SuppressWarnings("common-java:DuplicatedBlocks")
public class Player implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequenceGenerator")
    @SequenceGenerator(name = "sequenceGenerator")
    @Column(name = "id")
    private Long id;

    @Column(name = "name")
    private String name;

    @JsonIgnoreProperties(value = { "player" }, allowSetters = true)
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(unique = true)
    private Foot foot;
```

**Comment by mshima** [comment]
The first looks reactive, the second looks imperative.

**Comment by qmonmert** [comment]
ah yes thanks 👍
