### ISSUE TITLE
Cached account data should be force loading on main page ???

### ISSUE THREAD

**Issue by xjiaoyang** [jhipster/generator-jhipster#2386]
i dont think this a very serious issue!!!

USING V2.23.1, Java 8, MySQL

here is how to reproduce：
`login(any account)` --> `go to settings page(maybe: http://127.0.0.1:8080/#/settings)` --> `change first name or the last name` --> `do not save` --> `redirect to main page(usually: http://127.0.0.1:8080/#/)`

and you see the account.userName and account.lastName is the value you set up on settings page without save to server.

there is a very easy way to fix this issue:
navigate to `/scripts/app/main/main.controller.js` at line (about) 5, change `Principal.identity()` to `Principal.identity(true)`  to force loading account data,  problem solved.

maybe this issue is come out of the WHOLE JH-SYSTEM design, and normally just be fine even ignore it. NO BIG DEAL.

**Comment by Vaelyr** [comment]
Problem here is that the account is on root scope. Proper solution would be to have a separate variable for storing name on navigation instead of using the same global. Force query is not needed here.

**Comment by deepu105** [comment]
Agree it should be separate scope variable

**Comment by xjiaoyang** [comment]
@Vaelyr that make sense! maybe i will make a PR later.

**Comment by jdubois** [comment]
Closing this as the PR is merged. I don't understand, you didn't fix the issue in the PR?
