### ISSUE TITLE
[enhancement] Paginate Elasticsearch search results

### ISSUE THREAD

**Issue by geraldhumphries** [jhipster/generator-jhipster#2387]
Right now, searching in an entity list will load all results into the table, and the pagination controls from the regular, non-searched browsing will remain. Spring Data Elasticsearch has support for pagination just like Spring Data JPA repositories. This will return a page of entities:

`Page<Entity> page = entitySearchRepository.search(queryStringQuery(query), pageable);`

This can also be queried on the front end the same (contains code for entity sorting from #2314):

`EntitySearch.query({query: $scope.searchQuery, page: $scope.page, size: 20, sort: $scope.predicate + ',' + ($scope.reverse ? 'asc' : 'desc')}, function(result, headers) { ... `

Some goals:
* Search results should be paginated and sortable
* A search should only be performed or query changed when the user clicks the search button. This means we need different scope variables for the search box model and the "currently searching" query.
* The search should persist until the user clicks a "clear search" button.
* We might want to refactor the search query to being a query string parameter rather than a URI parameter to maintain best practices. This breaks `generatePaginationHttpHeaders()` so this change will require refactoring.

This gist sums up the changes and works perfectly with pagination/sorting but I am unhappy with the front-end code and UI. I would appreciate a code review.

https://gist.github.com/geraldhumphries/569b189c1e1b62fb77d8

I can create a pull request but I would like to wait until #2314 is merged.

**Comment by xjiaoyang** [comment]
seams #2314 is merged, would you create a PR?

**Comment by geraldhumphries** [comment]
Unfortunately it's crunch time at work right now so I don't have any time to work on it. I'll open one as soon as I can!

**Comment by hirro** [comment]
@geraldhumphries I needed to get the search pagination working for a project I'm doing. Is it ok that I submit a PR for this or are you on this issue already?

**Comment by geraldhumphries** [comment]
@hirro go ahead, I haven't had any time to work on it.

**Comment by geraldhumphries** [comment]
@hirro check out my updated gist: https://gist.github.com/geraldhumphries/569b189c1e1b62fb77d8

This is what I've been using for my pages but I haven't had a chance to code it into the generator. This new code is cleaner than my old stuff and satisfies the most important requirements I mentioned in the OP.

It is based off 2.25.0 so it does not have the entity UI changes. I also removed/re-purposed unused methods.

One thing I noticed is that sorting works great for single-word text fields, numbers, etc., but there's something wrong with it when the field you're sorting on has data with multiple words.

**Comment by hirro** [comment]
I will look at that @geraldhumphries! In my current branch everything works besides DTOs. I must get that working before making the PR. Hopefully get it done during the weekend.

**Comment by geraldhumphries** [comment]
@hirro Do you think you would be able to work on this over the weekend? Anything I can do to help? This fix has become very important to me.

**Comment by hirro** [comment]
Sorry, didn't see this until now. But sure, I will send you a mail.

**Comment by geraldhumphries** [comment]
@jdubois @deepu105 what do you think about putting both the search and regular queries in `loadAll`?  Something like :
```
$scope.loadAll = function () {
    if (!searchQuery) {
        Entity.query ...
    } else {
        EntitySearch.query( ...
    }
}
```

Or would it be better to separate them and use an if statement to choose the right query when the state loads?
```    
if (!searchQuery) {
    $scope.loadAll();
 } else {
    $scope.search();
 }
```

@hirro if I make a pull request do you mind if I use some of your code?

**Comment by geraldhumphries** [comment]
I am leaning towards the first solution as it more resembles the activate pattern from the johnpapa style guide: https://github.com/johnpapa/angular-styleguide#style-y080

**Comment by geraldhumphries** [comment]
Also, would it be better to turn the `query` parameter into a query param instead of a path variable on the API? Right now it's a path variable, and because of that an empty query will throw a 404. That's why angular handled 404s in searches and redirected to a regular loadAll.

Like I said in the OP this change will require a new method in PaginationUtil for searches, but if we stick to a path variable it will require things like exception handling in the endpoint. Example for an entity named `address` if we keep path variables:
```
    /**
     * SEARCH  /_search/addresss/:query -> search for the address corresponding
     * to the query.
     */
    @RequestMapping(value = "/_search/addresss/{query}",
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    public ResponseEntity<List<Address>> searchAddresss(@PathVariable String query, Pageable pageable) throws URISyntaxException, UnsupportedEncodingException {
        log.debug("REST request to search Addresss for query {}", query);
        Page<Address> page = addressSearchRepository.search(queryStringQuery(query), pageable);
        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(page, "/_search/addresss/" + URLEncoder.encode(query, "UTF-8"));
        return new ResponseEntity<>(page.getContent(), headers, HttpStatus.OK);
    }
```

With a query param: 
```
    /**
     * SEARCH  /_search/addresss -> search for the address corresponding
     * to the query.
     */
    @RequestMapping(value = "/_search/addresss",
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    public ResponseEntity<List<Address>> searchAddresss(@RequestParam String query, Pageable pageable) throws URISyntaxException {
        log.debug("REST request to search Addresss for query {}", query);
        Page<Address> page = addressSearchRepository.search(queryStringQuery(query), pageable);
        HttpHeaders headers = PaginationUtil.generateSearchPaginationHttpHeaders(page, "/_search/addresss/", query);
        return new ResponseEntity<>(page.getContent(), headers, HttpStatus.OK);
    }
```

**Comment by deepu105** [comment]
Im ok with the change if others agree

**Comment by jdubois** [comment]
- For the loadAll method yes the first option is my favorite too
- For the path variable: I'm fine with our current design, but this can be
discussed. In fact Github uses a query param, for example for
https://github.com/search?utf8=%E2%9C%93&q=jhipster

BTW, you have "addresss", shouldn't this be "addresses" now we have the new
pluralization? Are you on the master branch?

On Fri, Feb 19, 2016 at 12:27 AM, Deepu K Sasidharan <
notifications@github.com> wrote:

> Im ok with the change if others agree
>
> On 19 Feb 2016 04:57, "Gerald Humphries" <notifications@github.com> wrote:
>
> > Also, would it be better to turn the query parameter into a query param
> > instead of a path variable on the API? Right now it's a path variable,
> and
> > because of that an empty query will throw a 404. That's why angular
> handled
> > 404s in searches and redirected to a regular loadAll.
> >
> > Like I said in the OP this change will require a new method in
> > PaginationUtil for searches, but if we stick to a path variable it will
> > require things like exception handling in the endpoint. Example for an
> > entity named address if we keep path variables:
> >
> > /**
> > * SEARCH /_search/addresss/:query -> search for the address corresponding
> > * to the query.
> > */
> > @RequestMapping(value = "/_search/addresss/{query}",
> > method = RequestMethod.GET,
> > produces = MediaType.APPLICATION_JSON_VALUE)
> > @Timed
> > public ResponseEntity<List<Address>> searchAddresss(@PathVariable String
> query, Pageable pageable) throws URISyntaxException,
> UnsupportedEncodingException {
> > log.debug("REST request to search Addresss for query {}", query);
> > Page<Address> page =
> addressSearchRepository.search(queryStringQuery(query), pageable);
> > HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(page,
> "/_search/addresss/" + URLEncoder.encode(query, "UTF-8"));
> > return new ResponseEntity<>(page.getContent(), headers, HttpStatus.OK);
> > }
> >
> > With a query param:
> >
> > /**
> > * SEARCH /_search/addresss -> search for the address corresponding
> > * to the query.
> > */
> > @RequestMapping(value = "/_search/addresss",
> > method = RequestMethod.GET,
> > produces = MediaType.APPLICATION_JSON_VALUE)
> > @Timed
> > public ResponseEntity<List<Address>> searchAddresss(@RequestParam String
> query, Pageable pageable) throws URISyntaxException {
> > log.debug("REST request to search Addresss for query {}", query);
> > Page<Address> page =
> addressSearchRepository.search(queryStringQuery(query), pageable);
> > HttpHeaders headers =
> PaginationUtil.generateSearchPaginationHttpHeaders(page,
> "/_search/addresss/", query);
> > return new ResponseEntity<>(page.getContent(), headers, HttpStatus.OK);
> > }
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jhipster/generator-jhipster/issues/2387#issuecomment-185916279
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/2387#issuecomment-185978768>
> .
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by geraldhumphries** [comment]
@jdubois regarding my pluralization, this is actually code from my project which I've done these changes for, and is still on 2.25.0

**Comment by roblight** [comment]
Just wondering why this hasn't been released yet.  Waiting for 3.0?  Thanks!

**Comment by geraldhumphries** [comment]
Yeah, this will go into the release for 3.0. 2.27.* versions are just maintenance releases for minor fixes, and I think this one is too big for that.
