### ISSUE TITLE
Problems deploying to Amazon AWS

### ISSUE THREAD

**Issue by robertolos** [jhipster/generator-jhipster#2391]
**Overview of the issue** - When trying to deploy my application to Amazon AWS (yo jhipster:aws) I'm getting the following error.
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

[INFO] Total time: 01:14 min

[INFO] Finished at: 2015-11-24T08:21:52+00:00

[INFO] Final Memory: 49M/279M
[INFO] ------------------------------------------------------------------------


Create S3 bucket
✖ null
```
**Motivation for or Use Case** - not possible to use the generator to deploy on aws
**JHipster Version(s)** - 2.24.0
**JHipster configuration, a .yo-rc.json file generated in the root folder** - 
```
{
  "generator-jhipster": {
    "baseName": "abcd",
    "packageName": "com.abcd.server",
    "packageFolder": "com/abcd/server",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": ""
  }
}
```
**Browsers and Operating System** - Arch Linux updated to 23/11/2015
**Reproduce the error** - run yo jhipster:aws
**Related issues** - np
**Suggest a Fix** - np

**Comment by gmarziou** [comment]
Please fiollow our guidelines before submitting an issue: https://github.com/jhipster/generator-jhipster/blob/master/README.md

**Comment by robertolos** [comment]
I was not able to find the guidlines, thanks! I just updated my request

**Comment by wuethrich44** [comment]
I'm currently extremly busy so maybe @deepu105 could take a look at this.

@robertolos Are you sure your IAM user has correct access rights to your S3 buckets?

**Comment by deepu105** [comment]
@robertolos I need more info to reproduce this, what was the options you choose while running `yo jhipster:aws` was there any stacktrace?

**Comment by robertolos** [comment]
I used all the default parameters proposed by jhipster generator. In particular the name of the S3 bucket was the same as the application name.
I just tried to change the s3 bucket name and the deploy ended correclty.
I also checked on the AWS web interface and there is only one s3 bucket, the one created by the last successfully run.

**Comment by deepu105** [comment]
So is this still an issue or can we close it

**Comment by robertolos** [comment]
I think it might be an issue as looks like with the default s3 name the deploy fails

**Comment by deepu105** [comment]
Ok ill check

**Comment by robertolos** [comment]
Hi @deepu105 ,
I just found another issue, after deploying the application on aws the environment was not started. In the Elastic Beantalk web interface I found the following error:
```
The instance profile aws-elasticbeanstalk-ec2-role associated with the environment does not exist.
```
I solved the problem by creating a new inline policy for my user with the following content:
```
{
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by deepu105** [comment]
@robertolos 
normally we dont create IAM roles as it needs to be created before using the subgen, btw you can contribute that to our generator as a PR if you would like

**Comment by piedrahitac** [comment]
I think this issue is related to the name of the bucket. It has happened to me in the past, but I always got around it by choosing a different name.

If I'm not mistaken bucket names are globally unique and have certain constraints regarding case and available characters, so according to my experience, if either of these conditions fail the sub-generator throws that `null` error.

**Comment by jdubois** [comment]
- The title of this issue is not clear -> please @robertolos can you put a clear title, so we know what it refers to?
- from my understanding the first issue is closed, and now you are discussing another issue -> can you open up a new issue for this? This is so we can keep track of each issue

I'm closing this as the original issue looks solved.
