### ISSUE TITLE
Add supported Java and Node versions

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#23933]
I spoke with someone that tried JHipster recently at the NY Java SIG last night. They said they struggled for hours because they were using the wrong version of Node. 

They requested we add documentation about which version of Java and Node we support. Even better, I think we should add something that errors out if the Node version isn't supported, like we do with the Maven Enforcer plugin.

**Comment by mshima** [comment]
The problem is old versions.
We check for compatibility.

```
% n 16
     copying : node/16.20.2
   installed : v16.20.2
% jhipster
jhipster
FATAL! You are running Node version 16.20.2
JHipster requires Node version ^18.13.0 || >= 20.6.1
Please update your version of Node.
```

**Comment by mraible** [comment]
> We check for compatibility.

Nice! Maybe we should just add a table of supported versions in the README?
