### ISSUE TITLE
SkipClient generating webapp files

### ISSUE THREAD

**Issue by minplaal** [jhipster/generator-jhipster#23943]
##### **Overview of the issue**

When generating with JHipster 8.0.0-rc1 an application with SkipClient setting enabled, it generates webapp files  and should not.

##### **Motivation for or Use Case**

Generating server only projects was supported in previous JHipster versions and is expected to be supported with new versions. 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "test",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientTestFrameworks": [],
    "clientTheme": "none",
    "creationTimestamp": 1697980623138,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "MyTest"
    ],
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.0.0-rc.1",
    "languages": [
      "en",
      "fr"
    ],
    "lastLiquibaseTimestamp": 1697980825000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "prodDatabaseType": "mssql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu122.04, mixed mode, sharing)

git version 2.34.1

node: v18.18.1
npm: 9.8.1

Docker version 24.0.6, build ed223bc

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity MyTest {
  testField String
}
dto MyTest with mapstruct
paginate MyTest with pagination
service MyTest with serviceImpl
search MyTest with no
filter MyTest

</pre>
</details>

##### **Suggest a Fix**

Ensure "SkipClient" condition is checked within Language generator, both for loadNativeLanguage and for postWritingEntities

##### **JHipster Version(s)**

8.0.0-rc.1

**Comment by mshima** [comment]
@minplaal can contribute with a PR?

**Comment by minplaal** [comment]
I'll give it a try at least!
