### ISSUE TITLE
Upgrade our build matrix to test on Java 17 + 21

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#23958]
##### **Overview of the feature request**

upgrade our build matrix to test on Java 17 + 21

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Mix java 17/21 or switch every test to Java 21?

**Comment by mraible** [comment]
I think we should test on both 17 and 21 since Spring Boot requires 17 as a minimum.

**Comment by DanielFran** [comment]
I believe we should test using the default JAVA_VERSION = 17 + the max JAVA_COMPATIBLE_VERSIONS = 21

![image](https://github.com/jhipster/generator-jhipster/assets/3706415/fc356222-0d46-4da0-bc86-5c953ed12929)

**Comment by mraible** [comment]
17 + 21 was recommended at Devoxx.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/187983

**Comment by DanielFran** [comment]
@mshima approved
