### ISSUE TITLE
Authorizations in angular state

### ISSUE THREAD

**Issue by MateuszPu** [jhipster/generator-jhipster#2396]
In documentation state that "For each state, the required roles are listed in the state’s data, and when the role list is empty it means that the state can be accessed anonymously." 

So the problem is: when i create new state and configure it like this: 

data: {
                    roles: ['ROLE_USER'],
                    pageTitle: 'index.title'
                },

And have empty controller, then when i'm not log in to application i am able to access this state even the roles is "ROLE_USER". However when i add to controller something related with database for example get list of object from DB the behavior is correct and i am not able to access state and i'm redirect to login page. Is it a normal behavior?   
Tested on version: Release 2.23.1.

**Comment by geraldhumphries** [comment]
The name of the variable was changed from `roles` to `authorities` in 2.21.0:

http://jhipster.github.io/2015/09/16/jhipster-release-2.21.0.html

Try renaming it.

**Comment by jdubois** [comment]
Oh yes, that's the issue, that was in the release notes but that's not obvious, of course.
