### ISSUE TITLE
All users of the same login leave when I give logout with one user (OAuth 2)

### ISSUE THREAD

**Issue by wzomer** [jhipster/generator-jhipster#2397]
{Google translate help}

* **Overview of the issue**

All users of the same login leave when I give logout with one user (OAuth 2), is this right?

* **Motivation for or Use Case** 

For example, if I use facebook on multiple machines, leaving a not out of the other.

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
    "generator-jhipster": {
        "authenticationType": "oauth2",
        "hibernateCache": "hazelcast",
        "clusteredHttpSession": "hazelcast",
        "websocket": "no",
        "databaseType": "sql",
        "devDatabaseType": "mysql",
        "prodDatabaseType": "mysql",
        "useCompass": true,
        "buildTool": "maven",
        "frontendBuilder": "grunt",
        "javaVersion": "8",
        "searchEngine": "no",
        "enableTranslation": false,
        "useSass": true,
        "enableSocialSignIn": false,
        "testFrameworks": [
            "gatling"
        ]
    }
}

**Comment by jdubois** [comment]
I guess it removes all the tokens for this user -> this is handled by Spring Security, not JHipster, so I can't tell if that's "normal" or not, you might ask this on StackOverflow or submit this ticket to Spring Security.
