### ISSUE TITLE
Badges needs update.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#23995]
##### **Overview of the issue**

Daily builds badges are not working updating, it's always green.
See recent failure https://github.com/hipster-labs/jhipster-daily-builds/actions.

##### **JHipster Version(s)**

main

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
@mshima Do you mean the badges in `generator-jhipster` or the ones in the daily builds itself or both? Right now they seem pretty much current, except, in generator-jhipster we don't show the same badges as in the daily builds readme. And I think the heading in the main generator is wrong (`Azure Builds` :))

**Comment by mshima** [comment]
@atomfrede both.
I've just prepared a PR to fix the badges https://github.com/hipster-labs/jhipster-daily-builds/pull/155.

**Comment by mshima** [comment]
Just saw the Azure Builds too 😄 .

**Comment by mshima** [comment]
> Right now they seem pretty much current

Everything has passed today 😄
Daily builds are quite stable for some time.
