### ISSUE TITLE
Too many audit entries for the login event

### ISSUE THREAD

**Issue by cornelcreanga** [jhipster/generator-jhipster#2400]
Hello,

The login event is recorded three times in the audit table (no remember me cookie)

Steps to reproduce:
-create an application (jhipster v2.23.1, HTTP Session Authentication,Mysql ,ehcache local)
-clear all the cookies (just to be sure)
-start the application, login with admin/admin
-the jhi_persistent_audit_event table contain three entries. (

Let me know if you want more info (for example the log file).

Thanks.

**Comment by pascalgrimaud** [comment]
Duplicated issue : https://github.com/jhipster/generator-jhipster/issues/2011
It was fixed by https://github.com/jhipster/generator-jhipster/pull/2357 : spring-boot 1.3.RELEASE

So try to upgrade to JHipster 2.24.0

**Comment by cornelcreanga** [comment]
Thanks, it works with 2.24.0.
