### ISSUE TITLE
Gateway Unauthorized Error on Keycloak Login Error

### ISSUE THREAD

**Issue by bakoorjakkals** [jhipster/generator-jhipster#24010]
##### **Overview of the issue**

I'm using JHipster gateway with Keycloak as identity provider.

Sometimes an error occurs during the Keycloak login process. Keycloak then routes me back to the gateway with this path: https://my-gateway-url/login?error.

The gateway doesn't show a login error page, but instead shows the following:

```json
{
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "title": "Unauthorized",
    "status": 401,
    "detail": "Not Authenticated",
    "path": "/login",
    "message": "error.http.401"
}
```

Is there a way to let the gateway show a custom error page when keycloak redirects to `/login?error`, or if not, possibly a simple way to change the redirect logic in Keycloak so that it doesn't redirect to `/login?error`?

##### **Motivation for or Use Case**

In the event of a login error happening, the client should be redirected to the appropriate error page and not see this JHipster error.

##### **Reproduce the error**

The simplest way to reproduce this is to start up the gateway and navigate to localhost/login?error in a browser

##### **JHipster Version(s)**

I'm using JHipster 7.8.1

##### **Browsers and Operating System**

Firefox and Chrome in Ubuntu 20.04

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I'm closing this issue because the solutation is likely related to Spring Security rather than JHipster. Please re-open if you disagree and provide your opinion about why it should be fixed.
