### ISSUE TITLE
List screens don't show username in relationship

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#24033]
##### **Overview of the issue**

If I create an app with the following JDL and JHipster 8.0.0 RC1, it fails to display the user in the list screens. If I edit the item, the user is assigned correctly, and I can change it.

```
application {
  config {
    applicationType monolith,
    baseName HealthPoints
    packageName com.okta.developer,
    authenticationType jwt,
    prodDatabaseType postgresql,
    buildTool gradle,
    testFrameworks [cypress],
    clientFramework react,
    enableTranslation true,
    nativeLanguage en,
    languages [en, es]
  }
  entities Points, BloodPressure, Weight, Preferences
}

// JDL definition for application 'TwentyOnePoints' generated with command 'jhipster export-jdl'

entity BloodPressure {
  timestamp ZonedDateTime required
  systolic Integer required
  diastolic Integer required
}
entity Weight {
  timestamp ZonedDateTime required
  weight Double required
}
entity Points {
  date LocalDate required
  exercise Integer
  meals Integer
  alcohol Integer
  notes String maxlength(140)
}
entity Preferences {
  weeklyGoal Integer required min(10) max(21)
  weightUnits Units required
}

enum Units {
  KG,
  LB
}

relationship OneToOne {
  Preferences{user(login)} to User with builtInEntity
}
relationship ManyToOne {
  BloodPressure{user(login)} to User with builtInEntity
  Weight{user(login)} to User with builtInEntity
  Points{user(login)} to User with builtInEntity
}

paginate BloodPressure, Weight with infinite-scroll
paginate Points with pagination
```

##### **Motivation for or Use Case**

If there is a relationship with a user, it should be displayed in the list screen.

##### **Reproduce the error**

Create a new app with the JDL above and add a couple of records. No user is displayed on the list screen, but one is selected in the edit screen.

<img width="1144" alt="list" src="https://github.com/jhipster/generator-jhipster/assets/17892/cf68e709-269a-459e-832a-d68ae35914a7">

<img width="1127" alt="edit" src="https://github.com/jhipster/generator-jhipster/assets/17892/99729387-354d-4b92-b7cd-0fa44bddaaf7">

##### **JHipster Version(s)**

```
health-points@0.0.1-SNAPSHOT /Users/mraible/Downloads/21p
└── generator-jhipster@8.0.0-rc.1
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationIndex": 0,
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "HealthPoints",
    "buildTool": "gradle",
    "clientFramework": "react",
    "creationTimestamp": 1698472313459,
    "devServerPort": 9060,
    "enableTranslation": true,
    "entities": [
      "Points",
      "BloodPressure",
      "Weight",
      "Preferences"
    ],
    "herokuAppName": "windypoop",
    "herokuDeployType": "git",
    "herokuJavaVersion": "21",
    "jhipsterVersion": "8.0.0-rc.1",
    "languages": [
      "en",
      "es"
    ],
    "lastLiquibaseTimestamp": 1698472528000,
    "nativeLanguage": "en",
    "packageFolder": "com/okta/developer",
    "packageName": "com.okta.developer",
    "prodDatabaseType": "postgresql",
    "testFrameworks": [
      "cypress"
    ]
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "21" 2023-09-19
OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15)
OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

git version 2.39.3 (Apple Git-145)

node: v18.18.2
npm: 9.8.1

Docker version 24.0.6, build ed223bc

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Points {
  date LocalDate required
  exercise Integer
  meals Integer
  alcohol Integer
  notes String maxlength(140)
}
entity BloodPressure {
  timestamp ZonedDateTime required
  systolic Integer required
  diastolic Integer required
}
entity Weight {
  timestamp ZonedDateTime required
  weight Double required
}
entity Preferences {
  weeklyGoal Integer required min(10) max(21)
  weightUnits Units required
}
enum Units {
  KG,
  LB
}

relationship OneToOne {
  Preferences{user(login)} to User with builtInEntity
}
relationship ManyToOne {
  Points{user(login)} to User with builtInEntity
  BloodPressure{user(login)} to User with builtInEntity
  Weight{user(login)} to User with builtInEntity
}

paginate Points with pagination
paginate BloodPressure, Weight with infinite-scroll
search Points, BloodPressure, Weight, Preferences with no

</pre>
</details>

**Comment by mshima** [comment]
Duplicated of https://github.com/jhipster/generator-jhipster/issues/23917?

**Comment by mraible** [comment]
I tried modifying the JDL to be as follows:

```
relationship ManyToOne {
  BloodPressure{user(login)} to User with builtInEntity
  Weight{user(login)} to User with builtInEntity
  Points{user(login)} to @RelationshipEagerLoad User with builtInEntity
}
```

This results in the following stack trace. I also tried:

```
@RelationshipEagerLoad Points{user(login)} to User with builtInEntity
```

Stack trace:

```
ERROR! An error occured while running jhipster:bootstrap-application-base#loadingEntities
ERROR! ERROR! Error at entity Points: could not find the entity user
Error: Error at entity Points: could not find the entity user
    at loadEntitiesOtherSide (file:///Users/mraible/dev/generator-jhipster/dist/generators/base-application/support/relationship.mjs:60:23)
    at BootstrapApplicationBase.loadingEntities (file:///Users/mraible/dev/generator-jhipster/dist/generators/bootstrap-application-base/generator.mjs:181:37)
    at BootstrapApplicationBase.executeTask (file:///Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:241:26)
    at env.queueTask.once (file:///Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:215:56)
    at runLoop.add.once (file:///Users/mraible/dev/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:381:23)
    at Immediate.<anonymous> (/Users/mraible/dev/generator-jhipster/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:476:21)
```

**Comment by mraible** [comment]
@mshima I tried both of these options in JDL, and neither one results in the user showing up in the list:

```
@RelationshipEagerLoad Points{user(login)} to User with builtInEntity
Points{user(login)} to @RelationshipEagerLoad User with builtInEntity
```

**Comment by hide212131** [comment]
@mraible @mshima 

In the entity list view, the backend returns related entities with only an `id` field, but the frontend expects a different field.

Response JSON and relevant code are as follows:

Response: 
```json
[ 
{
  "id" : 1,
  "date" : "2023-10-29",
  "exercise" : 6654,
  "meals" : 10241,
  "alcohol" : 9875,
  "notes" : "tightly",
  "user" : {
    "id" : 1
  }
},
]
```

employee.tsx:
```react
<td>{points.user ? points.user.login : ''}</td> 
```

I believe it should be `points.user.id`, regardless of the JDL's `{user(login)}`. 
(My understanding is that the JDL's [\<display field\>](https://www.jhipster.tech/jdl/relationships#:~:text=end%20as%20type%2C-,%3Cdisplay%20field%3E,-is%20the%20name) only affects the details and update views.)

**Comment by mshima** [comment]
Display field is supposed to be eager loaded due to this condition.
https://github.com/jhipster/generator-jhipster/blob/20b31a71ed2f413b6e28fc0c4e73daefb1e46d08/generators/base-application/support/prepare-entity.mts#L629

And eager load apis should be generated:
https://github.com/mshima/generator-jhipster/blob/3cdd7445bf31c131f6fd89686536f722c6ee76af/generators/server/templates/src/main/java/_package_/_entityPackage_/repository/_entityClass_Repository.java.ejs#L81

**Comment by mshima** [comment]
I've generated a project, react and probably vue does not eager load the list by default.
