### ISSUE TITLE
Impossible to install AWS-SDK after update to npm v.3.5.0

### ISSUE THREAD

**Issue by robertolos** [jhipster/generator-jhipster#2405]
**Overview of the issue** - After my OS (Archlinux) upgraded npm to version 3.5.0 I'm no longer able to install aws-sdk

**Motivation for or Use Case** - upgrade to npm 3.5.0 brakes the aws-sdk install
**JHipster Version(s)** - 2.24.0
**JHipster configuration, a .yo-rc.json file generated in the root folder** -
```
{
  "generator-jhipster": {
    "baseName": "abcd",
    "packageName": "com.abcd.server",
    "packageFolder": "com/abcd/server",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": ""
  }
}
```
**Browsers and Operating System** - Arch Linux updated to 26/11/2015
**Reproduce the error**- 
Upgrade npm to version 3.5.0
Upgrade jhipster to version 2.24.0
run the following commands:
```
[roberto@asuslpt generator-jhipster]$ cd /usr/lib/node_modules/generator-jhipster
[roberto@asuslpt generator-jhipster]$ sudo npm install aws-sdk progress node-uuid
npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "aws-sdk" "progress" "node-uuid"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/generator-jhipster/npm-debug.log
[roberto@asuslpt generator-jhipster]$ 
```
**Related issues** - I also raised a new issue to npm https://github.com/npm/npm/issues/10565
**Suggest a Fix** - np

**Comment by jdubois** [comment]
From what I read this is an error with the AWS SDK: we don't provide this, it is done by Amazon -> you should ask Amazon support for this
I'm closing this as this isn't a JHipster bug

**Comment by robertolos** [comment]
Ok I'll do it.
Thanks Julien

**Comment by gmarziou** [comment]
One thing you could try is to empty your node_modules folder because npm 3 has changed its layout. I had to do this for an issue not related to AWS though.

**Comment by jdubois** [comment]
Yes good tip @gmarziou

**Comment by deepu105** [comment]
yes also trying to reinstall again if it fails might also help, after node
upgrade I have faced errors as well with some modules
