### ISSUE TITLE
Wrong version of JHipster in multiple places

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#24082]
When you re-generate an existing `.yo-rc` file using a new JHipster version, it regenerates the project and updates to latest code but still put the old version number in the `jhipsterVersion` field in below places. 
- package.json
- Readme
- GeneratedByJHipster.java
Workaround is to delete the `jhipsterVersion` field from ` .yo-rc,json` file before the generation.

**Comment by deepu105** [comment]
@mshima maybe a side effect of some recent refactor

**Comment by mshima** [comment]
Would be nice to have a npm version v8.0.1  with this fix.

**Comment by deepu105** [comment]
I won't have time until the weekend. 8f someone else wanna release before
that please go ahead
