### ISSUE TITLE
Oracle database

### ISSUE THREAD

**Issue by kamfasage** [jhipster/generator-jhipster#2409]
there is a Problem while removing the JHipster generated tables in database,
JHipster doesn't recreate these tables when recompiling the project.

**Comment by jdubois** [comment]
Please follow our guidelines at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

- we need to have your configuration and version number in order to reproduce
- we need to have the steps you did in order to reproduce

**Comment by cbornet** [comment]
It's normal : liquibase doesn't scan the DB. It just plays the xml confs in the order of the master.xml file and has a databasechangelog table to know which changes were applied. You should check the [liquibase doc](http://www.liquibase.org/documentation/). Maybe you can play with the databasechangelog table to have liquibase recreate your table.
