### ISSUE TITLE
jHipster 8.0.0 /admin/docs not working

### ISSUE THREAD

**Issue by kevintanhongann** [jhipster/generator-jhipster#24099]
##### **Overview of the issue**
![image](https://github.com/jhipster/generator-jhipster/assets/359537/1581e8a1-3e6c-4e92-89fc-0ee76d08e717)

##### **Reproduce the error**
Generate a Vue flavor jHipster project, use any JDL script you desire, generate the project and navigate to API (/admin/docs)

##### **Related issues**
N/A

##### **Suggest a Fix**
N/A

##### **JHipster Version(s)**
8.0.0 

##### **JHipster configuration**
```jdl
application {
  config {
    baseName example
    applicationType monolith
    packageName com.example
    authenticationType jwt
    devDatabaseType h2Memory
    prodDatabaseType postgresql
    clientFramework vue
    buildTool gradle
    cacheProvider ehcache
    enableHibernateCache true
  }
  entities *
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
N/A

##### **Browsers and Operating System**

Ubuntu 23.04, Firefox

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kevintanhongann** [comment]
![image](https://github.com/jhipster/generator-jhipster/assets/359537/8836773c-b282-4f66-9da9-18ef642db399)

**Comment by kevintanhongann** [comment]
If there is a quick fix for this, do let me know. I might wanna use that for a project to battle test this full on.

**Comment by kevintanhongann** [comment]
If there is a quick fix for this, do lemme know.

**Comment by anothergoodguy** [comment]
not sure if it's a similar issue, can you see if it's related to build options like stated at [23382](https://github.com/jhipster/generator-jhipster/issues/23382)

**Comment by mshima** [comment]
No reproducible. Next time please provide `jhipster info` so we can use `from-issue` command.
```sh
jhipster jdl app.jdl
./gradlew
```
and
```
jhipster  --defaults --client-framework vue --dev-database-type h2Memory --build gradle
./gradlew
```

Go to Administration/API.

**Comment by mshima** [comment]
Not reproducible.
Closing.

**Comment by kevintanhongann** [comment]
I was generating the app from a JDL script and it still doesn't work. 

![image](https://github.com/jhipster/generator-jhipster/assets/359537/82e33685-067d-4f36-8298-7e2258c94acb)

jhipster info

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationIndex": 0,
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "selfStorage",
    "buildTool": "gradle",
    "cacheProvider": "ehcache",
    "clientFramework": "vue",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "enableTranslation": true,
    "entities": [
      "Facility",
      "Unit",
      "Tenant",
      "Lease",
      "Payment"
    ],
    "jhipsterVersion": "8.1.0",
    "languages": [
      "en",
      "ja",
      "th",
      "id",
      "zh-cn"
    ],
    "lastLiquibaseTimestamp": 1705681485000,
    "nativeLanguage": "en",
    "prodDatabaseType": "postgresql",
    "testFrameworks": [
      "cypress",
      "gatling"
    ]
  }
}
</pre>
</details>


##### **Environment and Tools**

openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment Temurin-20.0.1+9 (build 20.0.1+9)
OpenJDK 64-Bit Server VM Temurin-20.0.1+9 (build 20.0.1+9, mixed mode, sharing)

git version 2.34.1

node: v18.16.0
npm: 9.8.1

Docker version 24.0.7, build afdd53b

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>

Let me know if I missed anything.

**Comment by kevintanhongann** [comment]
I suspect the new syntax for the SecurityConfiguration doesn't work 100 percent. Let me paste an old syntax in and see if everything works again.

**Comment by kevintanhongann** [comment]
Also, /admin/metrics also not working for vue 3's flavor.

**Comment by kevintanhongann** [comment]
From my investigation, it must be because Vue 3 didn't package/copy the swagger-ui properly based on the comparison that I was doing between the old jhipster 7(webpack.common.js) and the new jhipster 8 (vite.config.ts).

**Comment by kevintanhongann** [comment]
@mshima can you please verify that again?

**Comment by kevintanhongann** [comment]
@mraible @deepu105 please reopen this again. It's really broken.

**Comment by mshima** [comment]
I’ve tested again using main branch.
It worked as expected using vire-server or vite.

**Comment by soenkekrusche** [comment]
@kevintanhongann did you manage to solve the issue? I am having the exact same problem

**Comment by soenkekrusche** [comment]
This is my working config on windows now @kevintanhongann 
```
const getFileFromRepo = (file: string) => {
    const res = existsSync(fileURLToPath(new URL(`../node_modules/${file}`, import.meta.url)))
        ? fileURLToPath(new URL(`../node_modules/${file}`, import.meta.url))
        : fileURLToPath(new URL(`./node_modules/${file}`, import.meta.url));
    return normalizePath(res);
};

viteStaticCopy({
            structured: false,
            targets: [
                {
                    src: [
                        // does NOT work
                        `${swaggerUiPath}/*.{js,css,html,png}`,
                        // DOES work
                        `${swaggerUiPath}/swagger-ui.js`,
                        `${swaggerUiPath}/swagger-ui-bundle.js`,
                        `${swaggerUiPath}/swagger-ui-es-bundle.js`,
                        `${swaggerUiPath}/swagger-ui-es-bundle-core.js`,
                        `${swaggerUiPath}/swagger-ui-standalone-preset.js`,
                        `${swaggerUiPath}/swagger-initializer.js`,
                        `${swaggerUiPath}/absolute-path.js`,
                        `${swaggerUiPath}/index.js`,
                        `${swaggerUiPath}/index.css`,
                        `${swaggerUiPath}/swagger-ui.css`,
                        `${swaggerUiPath}/oauth2-redirect.html`,
                        `${swaggerUiPath}/favicon-16x16.png`,
                        `${swaggerUiPath}/favicon-32x32.png`,

                        `!${swaggerUiPath}/**/index.html`,
                        getFileFromRepo('axios/dist/axios.min.js'),
                        normalizePath(fileURLToPath(new URL('./src/main/webapp/swagger-ui/index.html', import.meta.url)))
                    ],
                    dest: 'swagger-ui'
                }
            ]
        })
```

**Comment by mshima** [comment]
@soenkekrusche that commit fixed a clean run of vite-server.
So it fixed this issue for non windows system.
You can see more info in this issue https://github.com/vladshcherbin/rollup-plugin-copy/issues/68.

Check if [this](https://github.com/jhipster/generator-jhipster/pull/26141) PR fixes the issue.
