### ISSUE TITLE
Missed translations in Polish language

### ISSUE THREAD

**Issue by khipis** [jhipster/generator-jhipster#2411]
There are some missed polish translations

**Comment by cbornet** [comment]
@khipis Would you submit a PR to add them ?

**Comment by khipis** [comment]
Yes, I've open issue to fix this but unfortunatly I've returned response that permission is denyied for me :(

**Comment by cbornet** [comment]
You need to fork the project. You should read https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md. Everything is explained there.

**Comment by khipis** [comment]
Sure, will do that
