### ISSUE TITLE
[React] Error during entity deletion process

### ISSUE THREAD

**Issue by nicolas63** [jhipster/generator-jhipster#24115]
##### **Overview of the issue**

Since the update from JHipster v8.0.0-rc.1 to JHipster 8.0.0 on the [dotnet blueprint](https://github.com/jhipster/jhipster-dotnetcore/pull/1402), I've encountered an error in the [e2e tests](https://github.com/jhipster/jhipster-dotnetcore/actions/runs/6762943743/job/18379741738?pr=1402).

My entity is failing during the deletion process, and I believe it's due to [this modification](https://github.com/jhipster/generator-jhipster/pull/22888). I have retried with the old code, and it works well

##### **Reproduce the error**

I'm not sure why only this entity is experiencing the problem

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "namespace": "JhipsterSampleApplication",
    "databaseType": "sql",
    "prodDatabaseType": "mysql",
    "authenticationType": "jwt",
    "serverPort": "5000",
    "jhipsterVersion": "7.9.3",
    "applicationType": "monolith",
    "baseName": "JhipsterSampleApplication",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1587112984699,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "enableTranslation": false
  },
  "generator-jhipster-dotnetcore": {
    "ciType": "Github"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

entity Region {
	regionName String
}

entity Country {
	countryName String
}

// an ignored comment
/** not an ignored comment */
entity Location {
	streetAddress String,
	postalCode String,
	city String,
	stateProvince String
}

entity Department {
	departmentName String required
}

/**
 * PieceOfWork entity.
 * @author The JHipster team.
 */
entity PieceOfWork {
	title String,
	description String
}

/**
 * The Employee entity.
 */
entity Employee {
	/**
	* The firstname attribute.
	*/
	firstName String,
	lastName String,
	email String,
	phoneNumber String,
	hireDate Instant,
	salary Long,
	commissionPct Long
}

entity Job {
	jobTitle String,
	minSalary Long,
	maxSalary Long
}

entity JobHistory {
	startDate Instant,
	endDate Instant,
    language Language
}

enum Language {
    FRENCH, ENGLISH, SPANISH
}

relationship OneToOne {
	Country{region} to Region
}

relationship OneToOne {
	Location{country} to Country
}

relationship OneToOne {
	Department{location} to Location
}

// defining multiple OneToMany relationships with comments
relationship OneToMany {
	Employee to Job{employee},
	/**
	* A relationship
	*/
	Department to
	/**
	* Another side of the same relationship
	*/
	Employee{department}
}

relationship ManyToOne {
	Employee{manager} to Employee
}

// defining multiple oneToOne relationships
relationship OneToOne {
	JobHistory{job} to Job,
	JobHistory{department} to Department,
	JobHistory{employee} to Employee
}

relationship ManyToMany {
	Job{chore(title)} to PieceOfWork{job}
}

// Set pagination options
// .Net does not generates link header for pagination.
// paginate JobHistory, Employee with infinite-scroll
// paginate Job with pagination

// Use Data Transfert Objects (DTO)
dto * with mapstruct

// Set service options to all except few
service all with serviceImpl except Employee, Job

// Set an angular suffix
// angularSuffix * with mySuffix

</pre>
</details>

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
If this is a blocker, we can easily revert at the blueprint for now.

**Comment by nicolas63** [comment]
It's not a blocker but in the blueprint we don't change this code, so i think you have the same problem in the main generator

**Comment by nicolas63** [comment]
Do you have an idea for fixing ?

**Comment by mshima** [comment]
This bug is interesting. `Location` entity instance is matching `location` from `location.href`.

**Comment by mshima** [comment]
The correct fix would be to generate a `tsEntityInstance` prefixed with `jhiPrefix`.
