### ISSUE TITLE
Add Actions repository for shared actions between main repositories and blueprints.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#24135]
##### **Overview of the feature request**

Create a new repository for shared actions to be reused at generator-jhipster, jhipster-bom, daily-builds and blueprints.
Some actions specific to generator-jhipster, jhipster-bom and daily-builds can be kept as a local action here.

Useful actions for blueprints:
- build npm cache. Blueprints uses same frontends.
- save/restore daily cache. daily cache is useful because we don't generate lock file.
- a few tools:
  - setup git.
  - setup keycloak hostname.
- compare generated source with previews.

##### **Motivation for or Use Case**

Facilitate maintenance.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran I can create a repo in hipster-labs org or should be create in jhipster org?

**Comment by DanielFran** [comment]
Better to create in jhipster org

**Comment by mshima** [comment]
@DanielFran https://github.com/hipster-labs/actions, you can move the project to jhipster org.

**Comment by DanielFran** [comment]
@mshima done

**Comment by DanielFran** [comment]
@mshima Are you planning to update the daily builds to use the jhipster actions?

**Comment by mshima** [comment]
> @mshima Are you planning to update the daily builds to use the jhipster actions?

Yes.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/203364
