### ISSUE TITLE
jhipster 8.0.0, need to select twice when generator ask for bootswatch team

### ISSUE THREAD

**Issue by djamel2288** [jhipster/generator-jhipster#24136]
##### **Overview of the issue**

when i tried to test the new version, jhipster-geenrator ask me some question and then, when it's asking about the bootswatch theme, i noticed that we need to click enter then you can choose your theme

##### **Motivation for or Use Case**

in the previews versions, we just need to click just once after choosing our theme

##### **Reproduce the error**

jhipster --skip-server --auth=jwt --jhi-prefix=cha --entity-suffix=cha

##### **JHipster Version(s)**

8.0.0

##### **JHipster configuration**

jhipster info

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0

Welcome to the JHipster Information Sub-Generator

```
my-web-app@0.0.1-SNAPSHOT ******************
`-- generator-jhipster@8.0.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "baseName": "chaSolutionsWebApp",
    "clientFramework": "angular",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "flatly",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1699366100411,
    "cypressAudit": true,
    "cypressCoverage": true,
    "devServerPort": 4200,
    "enableTranslation": true,
    "entities": [],
    "entitySuffix": "cha",
    "jhiPrefix": "cha",
    "jhipsterVersion": "8.0.0",
    "languages": [
      "en",
      "fr",
      "ar-ly"
    ],
    "microfrontend": null,
    "microfrontends": [],
    "monorepository": true,
    "nativeLanguage": "en",
    "skipCommitHook": true,
    "skipServer": true,
    "testFrameworks": [
      "cypress"
    ],
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment Corretto-11.0.17.8.1 (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.17.8.1 (build 11.0.17+8-LTS, mixed mode)

git version 2.23.0.windows.1

node: v20.9.0
npm: 8.13.1

Docker version 24.0.6, build ed223bc

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Thanks for using JHipster!

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Could not reproduce.
Asks for theme and than variant.
```
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Sandstone
? Choose a Bootswatch variant navbar theme (https://bootswatch.com/)? Dark
? Would you like to enable internationalization support? Yes
```

Perhaps windows specific?
