### ISSUE TITLE
Update lodash to version >3.0.0

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2414]
When starting a new JHipster project we have the following warnings:

    npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
    npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.

We should upgrade to the latest version

**Comment by atomfrede** [comment]
:+1:

**Comment by deepu105** [comment]
:+1:  there is also some conflict with angular translate version, we might need to add it in resolutions

**Comment by sendilkumarn** [comment]
:+1: 
But I guess the warning is because some other node modules are using outdated version.

**Comment by jdubois** [comment]
Yes @sendilkumarn this is coming from other modules we depend on, and I'm seeing the same issue with other generators -> I don't think we should migrate, that can in fact cause issues in those modules.
