### ISSUE TITLE
Romanian I18n

### ISSUE THREAD

**Issue by mihaisimi** [jhipster/generator-jhipster#2417]
If romanian language is added later in a project the json is not being generated for entities.

Missing "ro" line at line 1395:
https://github.com/jhipster/generator-jhipster/blob/master/entity/index.js

Related to #1583

**Comment by pascalgrimaud** [comment]
@mihaisimi : would you like to submit a PR to fix it ?

**Comment by mihaisimi** [comment]
I am doing it now.
