### ISSUE TITLE
Jhipster Upgrade fails from 7.7.0 to 8.0.0

### ISSUE THREAD

**Issue by Daszczu** [jhipster/generator-jhipster#24180]
After running `jhipster upgrade` command following stacktrace is shown:

> (node:35276) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> error: unknown option **'--with-entities'**
> ERROR! An error occured while running jhipster:upgrade#generateWithTargetVersion
> 
> ERROR! ERROR! Command failed with exit code 1: "C:\<project>\node_modules\.bin/jhipster" **--with-entities** --force --skip-install --skip-git --ignore-errors --no-insight
> Error: Command failed with exit code 1: "C:\<project>\node_modules\.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight
>     at makeError (file:///C:/nodejs/node_modules/generator-jhipster/node_modules/execa/lib/error.js:60:11)
>     at execaSync (file:///C:/nodejs/node_modules/generator-jhipster/node_modules/execa/index.js:201:17)
>     at execaCommandSync (file:///C:/nodejs/node_modules/generator-jhipster/node_modules/execa/index.js:276:9)
>     at UpgradeGenerator.spawnCommandSync (file:///C:/nodejs/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/spawn-command.js:24:16)
>     at UpgradeGenerator._generate (file:///C:/nodejs/node_modules/generator-jhipster/dist/generators/upgrade/generator.mjs:124:29)
>     at UpgradeGenerator._regenerate (file:///C:/nodejs/node_modules/generator-jhipster/dist/generators/upgrade/generator.mjs:142:14)
>     at UpgradeGenerator.generateWithTargetVersion (file:///C:/nodejs/node_modules/generator-jhipster/dist/generators/upgrade/generator.mjs:372:22)
>     at UpgradeGenerator.executeTask (file:///C:/nodejs/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:26)
>     at env.queueTask.once (file:///C:/nodejs/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:218:56)
>     at runLoop.add.once (file:///C:/nodejs/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:381:23) {
>   shortMessage: 'Command failed with exit code 1: "C:\\<project>\\node_modules\\.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight',
>   command: '"C:\\<project>\\node_modules\\.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight',
>   escapedCommand: '"\\"C:\\<project>\\node_modules\\.bin/jhipster\\"" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight',
>   exitCode: 1,
>   signal: undefined,
>   signalDescription: undefined,
>   stdout: undefined,
>   stderr: undefined,
>   cwd: 'C:\\<project>',
>   failed: true,
>   timedOut: false,
>   isCanceled: false,
>   killed: false
> }

Additionally when I run command `jhipster upgrade -verbose`

https://www.jhipster.tech/upgrading-an-application/

> --verbose - Log each step of the upgrade process in detail

I got an error message

> λ jhipster upgrade --verbose
> (node:27136) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> error: unknown option '--verbose'

**Comment by Loloweb** [comment]
Can reproduce. assuming op meant the latest release 8.1.0 instead of 8.8.0 in the title, upgrading from 7.9.2 to 8.1.0 results in the same error.
>command: 'npm exec --no jhipster -- --with-entities --force --skip-install --skip-git --ignore-errors --no-insight'
>error: unknown option '--with-entities'

**Comment by Daszczu** [comment]
> Can reproduce on Linux. assuming op meant the latest release 8.1.0 instead of 8.8.0 in the title, upgrading from 7.9.2 to 8.1.0 results in the same error.
> 
> > command: 'npm exec --no jhipster -- --with-entities --force --skip-install --skip-git --ignore-errors --no-insight'
> > error: unknown option '--with-entities'

my bad, thanks for spotting it, I meant 8.0.0
