### ISSUE TITLE
Can't find docker-compose version, when docker-compose is instaleld

### ISSUE THREAD

**Issue by drfred1981** [jhipster/generator-jhipster#24191]
##### **Overview of the issue**

When running jhispter docker-compose command, version 8.0.0rc1 and above.

getting this error :
INFO! Docker is installed

ERROR! Docker Compose 1.6.0 or later is not installed on your computer.

         Read https://docs.docker.com/compose/install/

ERROR! An error occured while running jhipster:docker-compose#checkDockerCompose

ERROR! ERROR! Cannot read properties of undefined (reading 'replace')

TypeError: Cannot read properties of undefined (reading 'replace')

    at DockerComposeGenerator.checkDockerCompose (file:///usr/lib/node_modules/generator-jhipster/dist/generators/docker-compose/generator.mjs:74:60)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async DockerComposeGenerator.executeTask (file:///usr/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:13)

    at async runLoop.add.once (file:///usr/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:381:17)

##### **Motivation for or Use Case**

I've have installed docker-compose, with apt and also wia command line, same bug appeared

##### **Reproduce the error**

run : 
jhispter docker-compose on a jhipster project

##### **Suggest a Fix**
Edit : 

generators/docker-compose/generator.mjs

At line 69
replace :
 const { stdout, exitCode } = await this.spawnCommand('docker compose version', { reject: false, stdio: 'pipe' });
by
 const { stdout, exitCode } = await this.spawnCommand('docker-compose version', { reject: false, stdio: 'pipe' });

##### **JHipster configuration**
 8.0.0rc1 and above (ive not tried on v 7 and above

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Is not impacted by entities

##### **Browsers and Operating System**

ubuntu

**Comment by mshima** [comment]
The check seems to be outdated.
I don't know what we should test.

We currently require [Compose file v3](https://docs.docker.com/compose/compose-file/compose-file-v3/).
Looks like we need:
- docker compose version >= 1.10
- docker engine >= 1.13.0 (maybe greater).

**Comment by drfred1981** [comment]
Hello everybody
Sorry if i'm  not clear

please see the code as i point at the picture, the character "-" is missing in the spawnCommand, That's the fix for this bug

![checkComposeInJhipster](https://github.com/jhipster/generator-jhipster/assets/5802342/564c43e5-116c-40b2-b136-fa8db0b79c7e)

Best regards

**Comment by mshima** [comment]
@drfred1981 IFAIK `docker-compose` is now an alias for `docker compose`.

See:
```
% docker-compose --help

Usage:  docker compose [OPTIONS] COMMAND

Define and run multi-container applications with Docker.
```

I don't know how this works or if `docker-compose` can be used standalone.

**Comment by drfred1981** [comment]
@mshima 
Hello thanks for your answer
Docker compose is not a command for docker in my version, 

if it "docker compose" must be used as it, i suggest, to add a complementary check based on the required version of docker


here is my client docker version installer on Ubuntu 22.04.3 LTS
`Client:

 Version:           24.0.5

 API version:       1.43

 Go version:        go1.20.3

 Git commit:        24.0.5-0ubuntu1~22.04.1

 Built:             Mon Aug 21 19:50:14 2023

 OS/Arch:           linux/amd64

 Context:           default



Server:

 Engine:

  Version:          24.0.5

  API version:      1.43 (minimum version 1.12)

  Go version:       go1.20.3

  Git commit:       24.0.5-0ubuntu1~22.04.1

  Built:            Mon Aug 21 19:50:14 2023

  OS/Arch:          linux/amd64

  Experimental:     false

 containerd:

  Version:          1.7.2

  GitCommit:        

 runc:

  Version:          1.1.7-0ubuntu1~22.04.1

  GitCommit:        

 docker-init:

  Version:          0.19.0

  GitCommit:`

**Comment by mshima** [comment]
@drfred1981 `docker compose` is the official command for `docker-compose` v2. Check [upstream issue](https://github.com/docker/compose/issues/8630) and a [possible workaround](https://github.com/docker/compose/issues/8630#issuecomment-1141930536).

Since we use `docker compose` everywhere, we should require `docker compose version` to return the version.

**Comment by mshima** [comment]
`jhipster --skip-checks` ignores that error.
