### ISSUE TITLE
rollback not working well

### ISSUE THREAD

**Issue by tayfunyasar** [jhipster/generator-jhipster#2421]
I was trying to add new entity (yo jhipster:entity user).

I was cancelled operation at override step but, my frontend controller js files were already overridden.

I'm trying to generete new project now.

FYI

**Comment by jdubois** [comment]
I don't know what you call "rollback"... I guess you went to the last question and killed the process while it was generating, so of course you only have half of the files generated. There is no transaction here, we just generate files on the filesystem, so we don't rollback anything if you kill the process.
The only way to have this working, is that you use Git: do a commit before generating, and then do the rollback with Git. I'm using this all the time, and of course this will work.
