### ISSUE TITLE
jHipster Eclipse Javascript formatter

### ISSUE THREAD

**Issue by tayfunyasar** [jhipster/generator-jhipster#2425]
Can anyone share javascript / html / java formatter.xml for eclipse?

Thanks!

**Comment by pascalgrimaud** [comment]
This is not a JHipster issue, you should use StackOverflow instead

**Comment by tayfunyasar** [comment]
Why not? I'm asking this question to jHipster contributors. Not anyone else.

**Comment by jdubois** [comment]
Yes but we have project guidelines, and everyone should follow them.
Even I am following them!
