### ISSUE TITLE
Build failure. UserServiceIT.java:[68,9] cannot find symbol method 'when'

### ISSUE THREAD

**Issue by JojoIce** [jhipster/generator-jhipster#24263]
##### **Overview of the issue**

After building a project with mostly the default settings and then starting it with 
./mvnw
It crashes with:

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/***/hipster/src/test/java/com/***/hipster/service/UserServiceIT.java:[68,9] cannot find symbol
  symbol:   method when(java.util.Optional<java.time.temporal.TemporalAccessor>)
  location: class com.***.hipster.service.UserServiceIT
[ERROR] /Users/***/hipster/src/test/java/com/***/hipster/service/UserServiceIT.java:[150,9] cannot find symbol
  symbol:   method when(java.util.Optional<java.time.temporal.TemporalAccessor>)
  location: class com.***.hipster.service.UserServiceIT
[ERROR] /Users/***/hipster/src/test/java/com/***/hipster/service/UserServiceIT.java:[168,9] cannot find symbol
  symbol:   method when(java.util.Optional<java.time.temporal.TemporalAccessor>)
  location: class com.***.hipster.service.UserServiceIT

(Replaced my own config params with '***'

##### **Motivation for or Use Case**

The ./mvnm command fails to start the application directly after it was created.

##### **Reproduce the error**

SETUP:

WARNING! Your Node version is not LTS (Long Term Support), use it at your own risk! JHipster does not support non-LTS releases, so if you encounter a bug, please use a LTS version first.
? What is the base name of your application? hipster
? May JHipster anonymously report usage statistics to improve the tool over time? No
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? Besides Junit, which testing frameworks would you like to use? 
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? com.***.hipster
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? PostgreSQL
? Which cache do you want to use? (Spring cache abstraction) Ehcache (local cache, for a single node)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? 
? Which *Framework* would you like to use for the client? React
? Besides Jest/Vitest, which testing frameworks would you like to use? 
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to enable internationalization support? No
? Please choose the native language of the application English
? Please choose additional languages to install 
     info Generating 2 048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 99 999 days
     info 	for: CN=Java Hipster, OU=Development, O=com.***.hipster, L=, ST=, C=
     info KeyStore '/Users/***/hipster/src/main/resources/config/tls/keystore.p12' generated successfully.

./mvnm

##### **Related issues**

Could not find any related issue.

##### **Suggest a Fix**

I could make the project compile and start again by adding the following to the created 
com.***.service.UserServiceIT
located in /src/test/java/

import static org.mockito.Mockito.when;

Simple fix, but for someone uninitiated it might be a showstopper, and naturally it would be best that hipster added this one missing line since it is only one line short of making it compile without errors.

##### **JHipster configuration**

{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "hipster",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientTestFrameworks": [],
    "clientTheme": "none",
    "creationTimestamp": 1700136976422,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 9060,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [],
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.0.0",
    "jwtSecretKey": "SECRET=",
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.***.hipster",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

##### **Environment and Tools**

openjdk version "17.0.5" 2022-10-18 LTS
OpenJDK Runtime Environment Zulu17.38+21-CA (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.38+21-CA (build 17.0.5+8-LTS, mixed mode, sharing)

git version 2.39.3 (Apple Git-145)

node: v21.2.0
npm: 10.2.4

'docker' command could not be found

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Empty

##### **Browsers and Operating System**

MacOS
Not yet opened in any browser

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by user-0209** [comment]
Same here. After weeks of successfully generating the application (repeatable, driven by script, starting from completely empty folder). Reinstalled nvm, jhipster, yo: no change. No idea, why this is happening.

openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu122.04, mixed mode, sharing)

git version 2.34.1

node: v20.9.0
npm: 10.1.0

**Comment by mshima** [comment]
This problem is caused due to new java-parser release.
The behavior change caused the remove unused Java imports implementation to remove `when` imports that it shouldn’t due to:
https://github.com/jhipster/prettier-java/blob/87192b463bfe8f9a19dfca5d123f2ebd4f53567c/packages/java-parser/src/tokens.js#L252

It added java 21 support. I wonder if it should have been a major version bump 🤔.
The remove unused dependencies have java-parser pinned now.

**Comment by mshima** [comment]
It’s fixed in main.
There is nothing to do now, closing.

**Comment by krital** [comment]
How do we get around this in the meantime? (noob here). Reinstalling the generator does not help

**Comment by mshima** [comment]
Workaround: 
```
cd $(jhipster --install-path | sed 's/Using jhipster at \(.*\)/\1/')/..
npm install java-parser@2.0.5
```

**Comment by krital** [comment]
Thank you, apologies I missed your suggested fix
