### ISSUE TITLE
show more configuration data to admin configuration screen

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2427]
There are more info available in the /env endpoint which can be shown in current config screen i think its very useful

![image](https://cloud.githubusercontent.com/assets/1107223/11552773/6001be6e-99c3-11e5-9722-7aca4a7ccd71.png)

**Comment by deepu105** [comment]
have masked some customer specific info in image

**Comment by pascalgrimaud** [comment]
@deepu105 do you think this doable in module ?

**Comment by deepu105** [comment]
I dont see value in doing it as a module as it needs just few more lines of
code to the current config moduel

**Comment by pascalgrimaud** [comment]
It can be usefull yes, but I just wonder if, in production, there can be some system information that an administrator in the application shouldn't see
I think about smtp, database url, password (can be replaced by **** like in your screenshot), etc.

**Comment by deepu105** [comment]
Passwords are shown as ** for other stuff it should be controlled by roles

**Comment by cbornet** [comment]
:+1: to have this in main generator
