### ISSUE TITLE
Combine basic auth with form login

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2428]
Form login is adapted for web applications but not for mobile apps or other servers consuming the api. OAuth2 can of course be used but it is not implemented in all clients or already existing softwares.
So it would be great to combine session formlogin with stateless basic auth for /api/**.
[Here](https://github.com/spring-projects/spring-security-javaconfig/blob/master/samples-web.md#sample-multi-http-web-configuration) is a sample project that gives an idea on how to do it.

**Comment by cbornet** [comment]
I'll work on this since I have a concrete need but I will kindly accept help :smile:

**Comment by cbornet** [comment]
This is better explained [here](http://docs.spring.io/spring-security/site/docs/current/reference/html/jc.html#multiple-httpsecurity) and is clearly not what we want. Still searching...

**Comment by cbornet** [comment]
OK. Sometimes the simplest things...
I just added ```and().httpBasic()```to the existing HttpSecurity conf and it worked perfectly...
@jdubois Do have any concerns about that or can I PR ?

**Comment by jdubois** [comment]
@cbornet well a PR for just one line of standard Spring Security code isn't really worth it... It's also against our policy 2 at http://jhipster.github.io/policies.html

**Comment by cbornet** [comment]
I understand but it's not so obvious for everybody (at least it wasn't for me). I thought it could also be a tip but as you said it's just one line... As for policy 2, I'm not proposing it as an option but as default to enhance the http username/password auth and I think it adds value in micro service architectures and mobile oriented applications.

**Comment by cbornet** [comment]
One more killer argument to add this by default : you can now test your API with curl ! And write bash scripts to do various tasks using the API (provisionning, monitoring, ...)

**Comment by deepu105** [comment]
+1

**Comment by jdubois** [comment]
- For micro services architectures I would recommend OAuth2 -> but indeed this part should be worked on, there should be a serious study about his
- For Curl I already do it all the time: just do "copy as Curl" in the Chrome dev tool tab

**Comment by cbornet** [comment]
As for curl, this suppose you have opened a navigator, gone through the login process, found the action that triggers the request you want to test. This is a rather long process compared to:
* ```mvn``` to boot the app
* ```curl http://admin:admin@localhost:8080/api/users``` to get the list of users for instance

And you can't really script that ...

**Comment by cbornet** [comment]
Also for mobile apps and remote servers, form login (with session and csrf token) is not adapted

**Comment by jdubois** [comment]
Yes this is what I do manually. Otherwise, I'm scripting this in the Gatling tests -> I'm not saying it's easy to do, but we already do this

**Comment by jdubois** [comment]
Yes for mobile users, we have people using Cordova or some native UI on top of JHipster, I think they usually use OAuth2 authent. This isn't that complex to do, and probably more secure.

**Comment by cbornet** [comment]
OK. I still think this is a very small change that brings value to people who need it and doesn't interfere with people who don't but if you don't see the interest, you can close this issue.

**Comment by deepu105** [comment]
+1 if it doesn't affect normal session auth

**Comment by cbornet** [comment]
@deepu105 it shall not, of course :-) !

**Comment by cbornet** [comment]
Let's make a module for this :smile: !

**Comment by cbornet** [comment]
In fact, this is not good since with basic auth you want to disable csrf and configure stateless session management. The only solution I found to have usable basic auth in parallel of form login is to duplicate the api endpoints on a "/api_basic" path which is protected by basic auth. This is easily done by adding the path to the RequestMapping of each entity resource. The advantage is that it is completely separated from the form login and can also be run in parallel of oauth2 (and probably x-auth).
@jdubois I need some way to replace the existing RequestMapping in the entity resources. That could be something like
```
@RequestMapping({"/api"
//jhipster-needle
    ,"/api_basic"
})
```
Or a kind of replacement in place à la ```sed```.
What do you think ?

**Comment by jdubois** [comment]
As this is on the generated entities, this looks complex to add a needle here, or do a 'sed' replacement.
You could generate the configuration and then let the users modify manually the entities.

**Comment by cbornet** [comment]
@jdubois That's a good idea and very simple to do. I will do that as a first version.

**Comment by cbornet** [comment]
The question of entity plugin wil surely come-back though...
