### ISSUE TITLE
[Feature Request] Offer Spring REST Docs integration as an option

### ISSUE THREAD

**Issue by c3thethird** [jhipster/generator-jhipster#2430]
Perhaps it be a good idea to offer integration with Spring REST Docs.

In any case, great work on this project.

**Comment by jdubois** [comment]
Thanks, but we already provide Swagger, we can't have 2 tools for the same job.
Everybody looks happy with Swagger (I even had a customer on the phone today, and that was one of his requirements), so I don't think we should move away from it.
Of course it depends on what Spring REST Docs provide, I haven't studied it at all.

**Comment by c3thethird** [comment]
I am not suggesting dumping Swagger, but rather offering Spring REST Docs as an alternative. Like you currently offer a choice of SQL DBs. I obviously understand that would be a low priority feature.

In any case, once again, you guys are doing a great job.

**Comment by jdubois** [comment]
Yes, you are right, we could offer the choice. I didn't have a look at Spring REST Docs yet, but as we rely so heavily on Spring, it makes sense to follow their lead.
I can't answer you until I've taken the time to study Spring REST Docs. I can't commit to when I will do it, but if it's successful I will most certainly do it, as I always do for all Spring products.
