### ISSUE TITLE
MapperTest classes do not contain test

### ISSUE THREAD

**Issue by jperezdelafuente** [jhipster/generator-jhipster#24314]
##### **Overview of the issue**

MapperTest classes do not contain test
An example of a MapperTest class generated by Jhipster:
```
package com.foo.service.mapper;

import org.junit.jupiter.api.BeforeEach;

class FooMapperTest {

    private FooMapper fooMapper;

    @BeforeEach
    public void setUp() {
        fooMapper = new FooMapperImpl();
    }
}
```
The lack of tests in these classes causes blocking code smells:
https://rules.sonarsource.com/java/RSPEC-2187/

The sonar-project.properties file contains:
```
sonar.issue.ignore.multicriteria = S2187,S3437,S4684,S5145,UndocumentedApi
# Rule https://rules.sonarsource.com/java/RSPEC-2187 is ignored, gatling tests are not supported by sonar
sonar.issue.ignore.multicriteria.S2187.resourceKey = src/test/java/gatling/**/*
sonar.issue.ignore.multicriteria.S2187.ruleKey = java:S2187
```
that rule is omitted for the Gatling package as it is not supported

##### **Motivation for or Use Case**

Avoid having code smells in that mapper test package
Achieve code coverage in mapper classes
If it is not considered a bug, perhaps these classes should contain a TODO comment and turn this issue into improvement

##### **JHipster Version(s)**

Jhipster 8.0.0

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
 application {
  config {
    applicationType monolith,
    baseName foo,
    packageName com.foo,
    jhiPrefix gsr,
    authenticationType session,
    databaseType sql,
    devDatabaseType h2Disk,
    prodDatabaseType oracle,
    enableHibernateCache true,
    cacheProvider ehcache,
    buildTool maven,
    testFrameworks [cypress, gatling, cucumber],
    clientFramework angular,
    enableTranslation true,
    nativeLanguage es,
    languages [es, en]
  }
  entities *
}

/** Entity Foo */
entity Foo(foo) {
    /** Foo */
    foo String required maxlength(20)
}

dto * with mapstruct
service all with serviceImpl
paginate all with pagination
  </pre>
  </details>

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@jperezdelafuente can you contribute with a PR?

**Comment by jperezdelafuente** [comment]
@mshima I just wanted to report this issue.

**Comment by jperezdelafuente** [comment]
Related to: https://github.com/jhipster/generator-jhipster/pull/25151

**Comment by jperezdelafuente** [comment]
could be closed
