### ISSUE TITLE
failed to execute "jhipster app --force --client-framework react --skip-prompts --defaults --skip-install --skip-git --skip-commit-hook"

### ISSUE THREAD

**Issue by fhchina** [jhipster/generator-jhipster#24312]
##### **Overview of the issue**

failed to execute "jhipster app --force --client-framework react --skip-prompts --defaults --skip-install --skip-git --skip-commit-hook", report exception:

 create src/main/java/com/mycompany/myapp/config/JacksonConfiguration.java
   create src/main/java/com/mycompany/myapp/config/LoggingAspectConfiguration.java
ERROR! ERROR! Error parsing file src/main/java/com/mycompany/myapp/repository/AuthorityRepository.java: Error: Sad sad panda, parsing errors detected in line: 5, column: 46!
Expecting token of type --> Identifier <-- but found --> '<' <--!
	->compilationUnit
	->ordinaryCompilationUnit
	->typeDeclaration
	->interfaceDeclaration
	->normalInterfaceDeclaration
	->extendsInterfaces
	->interfaceTypeList
	->interfaceType
	->classType at package com.mycompany.myapp.repository;

import com.mycompany.myapp.domain.Authority;

public interface AuthorityRepository extends <Authority, String> {

}

Error: Error parsing file src/main/java/com/mycompany/myapp/repository/AuthorityRepository.java: Error: Sad sad panda, parsing errors detected in line: 5, column: 46!
Expecting token of type --> Identifier <-- but found --> '<' <--!
	->compilationUnit
	->ordinaryCompilationUnit
	->typeDeclaration
	->interfaceDeclaration
	->normalInterfaceDeclaration
	->extendsInterfaces
	->interfaceTypeList
	->interfaceType
	->classType at package com.mycompany.myapp.repository;

import com.mycompany.myapp.domain.Authority;

public interface AuthorityRepository extends <Authority, String> {

}

    at file:///usr/local/lib/node_modules/generator-jhipster/dist/generators/bootstrap/support/java-unused-imports-transform.mjs:20:27
    at Transform.<anonymous> (file:///usr/local/lib/node_modules/generator-jhipster/node_modules/@yeoman/transform/dist/transform.js:42:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Transform.transform [as _transform] (file:///usr/local/lib/node_modules/generator-jhipster/node_modules/@yeoman/transform/dist/transform.js:16:37)

##### **Motivation for or Use Case**

I want to use cli to generate jhipster project ,without any manual interaction, without any prompts. so I can use this command in my script for bigger project.

##### **Reproduce the error**
 
just run:  jhipster app --force --client-framework react --skip-prompts --defaults --skip-install --skip-git --skip-commit-hook

##### **JHipster Version(s)**

8.0.0

##### **JHipster configuration**
(node:22942) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0

Welcome to the JHipster Information Sub-Generator

```
cli-j-hipster@0.0.1-SNAPSHOT /Volumes/Extended/Development/Prototype/CliJHipster
└── (empty)
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "baseName": "CliJHipster",
    "clientFramework": "react",
    "creationTimestamp": 1700563565059,
    "databaseType": "h2",
    "devDatabaseType": "h2",
    "devServerPort": 9060,
    "entities": [],
    "jhipsterVersion": "8.0.0",
    "languages": [
      "en",
      "fr"
    ],
    "nativeLanguage": "en",
    "prodDatabaseType": "h2",
    "skipCommitHook": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

git version 2.38.1

node: v21.1.0
npm: 10.2.0

'docker' command could not be found

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Thanks for using JHipster!

##### **Browsers and Operating System**

MacOS 12.6.6

- [Y] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
The provided cli arguments works.
The configuration does not match the provided cli arguments.
`databaseType: "h2"` is not a valid value.

Closing in favor of https://github.com/jhipster/generator-jhipster/issues/24318.
