### ISSUE TITLE
Unable to select any testing frameworks when generating an application

### ISSUE THREAD

**Issue by naris** [jhipster/generator-jhipster#24315]
##### **Overview of the issue**

When you generate an application, the "? Besides Junit, which testing frameworks would you like to use? (Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)" does not work at all.

It shows the options
❯◯ Gatling
 ◯ Cucumber

but the up and down arrow keys do not move the indicator, space does not select anything and a & i echo a or i to the screen

##### **Motivation for or Use Case**

I would like to select the Gatling testing framework

##### **Reproduce the error**

Attempt to use jhipster to generate an application in windows using the Windows Terminal
Enter a name for the application
Select Monolithic application type
(both of those actions above work as expected)
Attempt to select a testing framework
(which does not work at all -- you have to hit enter and select no testing frameworks to proceed))

##### **JHipster Version(s)**

jhipster 8.0.0

##### **JHipster configuration**

None, yet

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None, yet

##### **Browsers and Operating System**

Windows 11, Windows Terminal 1.18.2822.0

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by naris** [comment]
I have found that once you hit enter, it will NOt advance to the next option and you can then use the arrow keys and space to select a testing framework. :/

**Comment by mshima** [comment]
Works on MacOS. I suppose this is an [inquirer](https://github.com/SBoudrias/Inquirer.js/tree/master/packages/inquirer) bug

**Comment by mshima** [comment]
Not reproducible.
Closing.
