### ISSUE TITLE
Cannot edit user registered with FB or Google

### ISSUE THREAD

**Issue by hyuan** [jhipster/generator-jhipster#2433]
Both FB and Google are using email as user ID in OAuth. So we have to relax the restriction of login a bit to make the /users/:login API work. For example:

UserResource.java
```java
...
    @RequestMapping(value = "/users/{login:[_'.@a-z0-9-]+}",
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_VALUE)
...
```

BTW, it's very common to use email as login. Shall we allow to use email as login when registering?

Here is the PR: https://github.com/jhipster/generator-jhipster/pull/2434

**Comment by xjiaoyang** [comment]
indeed!

**Comment by jdubois** [comment]
Closed as the PR is merged
