### ISSUE TITLE
Vue Translation = false Doesn't work

### ISSUE THREAD

**Issue by oopsaleem** [jhipster/generator-jhipster#24360]
##### **Overview of the issue**

Using the below configurations, I have generated a monolith application using the vue clientFramework. All is working fine.
When I use `jhipster entity MyEntityName` to generate a new entity, I found that .vue files generated contain tags like below: 
<span>Translation missing for entity.action.cancel</span>
<span>Translation missing for entity.action.save</span>
...etc

##### **Motivation for or Use Case**

Even if I opt not to activate i18n, every .vue file for each newly generated entity contains tags: 
<span>Translation missing for entity.action.cancel</span>
<span>Translation missing for entity.action.save</span>
... etc

##### **Reproduce the error**

Would you like to enable internationalization support? No
Please choose the native language of the application English
**Please choose additional languages to install** This option shouldn't appear.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/24204

##### **Suggest a Fix**

No idea.

##### **JHipster Version(s)**
8.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "myapp",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "vue",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "none",
    "creationTimestamp": 1700859185390,
    "cypressAudit": true,
    "cypressCoverage": null,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "devServerPort": 9060,
    "enableGradleEnterprise": null,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [],
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.0.0",
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "prodDatabaseType": "mongodb",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [
      "websocket:spring-websocket"
    ],
    "serviceDiscoveryType": false,
    "testFrameworks": [
      "gatling",
      "cypress"
    ],
    "websocket": "spring-websocket",
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Microsoft-8526870 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Microsoft-8526870 (build 21.0.1+12-LTS, mixed mode, sharing)

git version 2.33.0

node: v20.10.0
npm: 10.2.3

Docker version 24.0.6, build ed223bc

##### **JDL for the Entity configuration(s) `Emp.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
{
  "applications": "*",
  "changelogDate": "20230331001043",
  "dto": "mapstruct",
  "embedded": false,
  "entityTableName": "emp",
  "fields": [
    {
      "fieldName": "firstName",
      "fieldType": "String"
    },
    {
      "fieldName": "lastName",
      "fieldType": "String"
    }
  ],
  "fluentMethods": true,
  "name": "Emp",
  "pagination": "no",
  "readOnly": false,
  "relationships": [],
  "searchEngine": "no",
  "service": "serviceClass"
}
</pre>
</details>

##### **Browsers and Operating System**

Mac OSX 14.1.1 
Safary
Chrome
Firefox

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Should be fixed with https://github.com/jhipster/generator-jhipster/issues/24204.
If you manage to reproduce using git main, please let me know.

**Comment by oopsaleem** [comment]
Hi @mshima 
Thank you for your response. 
To reproduce after generating the app follow the steps as below:  
I run the command `jhipster entity Dept` to create a new entity `Dept`
Then you will see the problem of `WARNING! Translation missing for entity.action.back.` 
I have created [https://github.com/oopsaleem/myapp.git](a repo to reproduce the issue)
Refer to the screenshot.
<img width="1558" alt="Screenshot 2023-11-30 at 12 47 16 PM" src="https://github.com/jhipster/generator-jhipster/assets/3925543/09e5a91c-1a8e-44fc-b4ed-6ddf1daebfe0">
