### ISSUE TITLE
Angular should handle errors from backend better

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#24396]
##### **Overview of the issue**

Today, I noticed that if you return a 401 from a backend method, the Angular UI will redirect you to `/` and log you out. To work around this, I tried returning a 403 instead. This is better because it doesn't log you out but shows a blank screen.

<img width="1283" alt="Screenshot 2023-11-28 at 8 38 48 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/dcd34b71-4aff-41af-89c4-806b18f76bd8">

Code that throws the exception:

```java
throw new ResponseStatusException(HttpStatus.FORBIDDEN, "error.http.403");
```

##### **Motivation for or Use Case**

The error is in the console, and it should be in the UI too. 

##### **Reproduce the error**

Create an app with Angular, add the exception to a method, and hit that method with a call from the UI.

```
blog@0.0.1-SNAPSHOT /Users/mraible/Downloads/blog
└── generator-jhipster@8.0.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "blog",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "none",
    "creationTimestamp": 1701088333195,
    "cypressAudit": true,
    "cypressCoverage": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "Blog",
      "Post",
      "Tag"
    ],
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.0.0",
    "languages": [
      "en",
      "es"
    ],
    "lastLiquibaseTimestamp": 1701088513000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "org.jhipster.blog",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "testFrameworks": [
      "cypress"
    ],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

git version 2.39.3 (Apple Git-145)

node: v18.18.2
npm: 9.8.1

Docker version 24.0.6, build ed223bc

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
@ChangelogDate("20231127123313")
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
@ChangelogDate("20231127123413")
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
@ChangelogDate("20231127123513")
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User with builtInEntity
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

search Blog, Post, Tag with no
paginate Post, Tag with infinite-scroll

</pre>
</details>

**Comment by atomfrede** [comment]
Is this a regression? I am pretty sure at least 403 have once been handled in another way

**Comment by mraible** [comment]
I tested my [jhipster7-demo](https://github.com/mraible/jhipster7-demo) project and the bug happens there too. When you enter a URL for an entity that you don't have access to, you're logged out and redirected to the login page.

**Comment by mraible** [comment]
The 401 is caught by Angular in [`auth-expired.interceptor.ts`](https://github.com/mraible/jhipster7-demo/blob/main/src/main/webapp/app/core/interceptor/auth-expired.interceptor.ts#L24). If I change it to a 403, the behavior is the same in JHipster 7.

<img width="1218" alt="Screenshot 2023-11-30 at 12 08 28 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/9f81bd40-1c56-47c6-8602-a8907e41d3a8">

**Comment by mraible** [comment]
I added a bug bounty.

**Comment by atomfrede** [comment]
@mraible At least for 403 I can't reproduce this. The frontend shows a fine message

**Comment by mraible** [comment]
@atomfrede Does this happen when you click on an item that you don't have access to? In my case, I'm changing the ID in the URL. You can clone my [example](https://github.com/mraible/jhipster8-demo), add a couple of posts that belong to different blogs, then try to access one that you shouldn't be able to.

**Comment by atomfrede** [comment]
@mraible You're right. Entering the url directly in the adressbar leads to an empty page
