### ISSUE TITLE
Add official blueprints to daily builds.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#24417]
##### **Overview of the feature request**

Most of official blueprints have been migrated to v8.
[Native](https://github.com/jhipster/generator-jhipster-native/) and [jOOQ](https://github.com/jhipster/generator-jhipster-jooq/) blueprints release are pending due to 8.0.0 final release regression.
Another regression happened in dotnetcore blueprint ci https://github.com/jhipster/generator-jhipster/issues/24115.

Blueprints daily-builds will help to discover regression earlier.

- add a github sample matrix builder to blueprints dev blueprint.
- run npm test and blueprint samples.
- blueprints:
  - jooq
  - entity-audit
  - micronaut
  - dotnetcore
  - quarkus
  - ionic
  - native

##### **Related issues or PR**

https://github.com/hipster-labs/jhipster-daily-builds/issues/14

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@mshima I think we should add your [migrate blueprint](https://github.com/mshima/generator-jhipster-migrate) and React Native to this list.

**Comment by atomfrede** [comment]
Good idea, it might help to make the blueprints more visible. @mshima I am about to (re)start the playwright blueprint, do we have some docs or best practices how to init a blueprint? @mraible I plan to do a blog post series about that, first doing it on a generated application to show playwright and afterwards how to put that into a blueprint, what do you think, would that be interesting for other people?

**Comment by mraible** [comment]
@atomfrede Yes, this sounds interesting to me! @jdubois might have Playwright connections so nice it's from Microsoft.

**Comment by mshima** [comment]
> @mshima I think we should add your [migrate blueprint](https://github.com/mshima/generator-jhipster-migrate) and React Native to this list.

React Native blueprint has not been ported to v8.
Migrate blueprint use case is quite different, not sure it applies.

**Comment by mshima** [comment]
> Good idea, it might help to make the blueprints more visible. @mshima I am about to (re)start the playwright blueprint, do we have some docs or best practices how to init a blueprint?

@atomfrede https://github.com/mshima/generator-jhipster/blob/main/BLUEPRINTS.md and https://github.com/mshima/generator-jhipster/blob/main/ARCHITECTURE.md

Any opinion to improve the documentation is welcome.

**Comment by DanielFran** [comment]
> @mshima I think we should add your [migrate blueprint](https://github.com/mshima/generator-jhipster-migrate) and React Native to this list.

@mshima Since @mraible already confirmed the blueprint works, we should move it to the Jhipster organisation.
In the future, we can eventually integrate this blueprint back into the generator?

**Comment by mshima** [comment]
@DanielFran moved generator-jhipster-migrate to jhipster-labs.

**Comment by DanielFran** [comment]
> @DanielFran moved generator-jhipster-migrate to jhipster-labs. https://github.com/hipster-labs/generator-jhipster-migrate

Will migrate it tomorrow to jhipster organisation

**Comment by DanielFran** [comment]
> > @DanielFran moved generator-jhipster-migrate to jhipster-labs. https://github.com/hipster-labs/generator-jhipster-migrate
> 
> Will migrate it tomorrow to jhipster organisation

@mshima done
