### ISSUE TITLE
React: Server-fetched instant field remains string type

### ISSUE THREAD

**Issue by hide212131** [jhipster/generator-jhipster#24435]
##### **Overview of the issue**

Related to https://github.com/jhipster/generator-jhipster/issues/23769#issuecomment-1836166233

```typescript
export interface IEmployee {
  hireDate?: dayjs.Dayjs | null;
}

export const EmployeeUpdate = () => {
  const employeeEntity = useAppSelector<IEmployee>(state => state.employee.entity);

  // If we write this expecting hireDate to be a dayjs type, we get an error at runtime. 
  // This is because hireDate can be a **string** type.
  const year = employeeEntity.hireDate?.year(); 
```

With the model as `dayjs` type, the results retrieved from the REST API must be converted.

##### **Motivation for or Use Case**

While this doesn't directly cause an error, it can lead to confusion during frontend development.

##### **Related issues**

#23769

##### **Suggest a Fix**

https://github.com/jhipster/generator-jhipster/issues/23769#issuecomment-1833841120

##### **JHipster Version(s)**

https://github.com/jhipster/generator-jhipster/tree/3c5e8327f8909923a2411aeb20dcd0cbc1e96cfc

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@hide212131 I did what you suggested but I have a warning in the console
<img width="1413" alt="image" src="https://github.com/jhipster/generator-jhipster/assets/9989211/dde13131-54df-4363-a96d-72c415b6f504">
and it seems that it is not a good practice
https://redux.js.org/style-guide/#do-not-put-non-serializable-values-in-state-or-actions
https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state

cc @DanielFran

**Comment by hide212131** [comment]
@qmonmert (cc @DanielFran) You're absolutely right, and I apologize for overlooking that. 
I've also gone through [this discussion](https://github.com/reduxjs/redux-toolkit/issues/456). Given that we are using React + Redux-toolkit, it's recommended that our models are Serializable/Immutable. Unfortunately (as it is less usable than Angular or Vue), this means it would be better to revert to using the **string type**, specifically in the ISO 8601 format.

Additionally, if we decide to use the **string type**, we will need to change the role of `src/main/webapp/app/shared/util/date-utils.ts`.

From:
```typescript
export const convertDateTimeToServer = (date?: string): dayjs.Dayjs | null => (date ? dayjs(date) : null);
```

To:
```typescript
// React components deal with local time, so it's necessary to convert them to UTC.
export const convertLocalToUTC = (date?: string): string | null => (date ? dayjs(date).toISOString() : null);
```

The same applies to `convertDateTimeFromServer`.

Could you please provide your thoughts on whether this approach is appropriate? There's also the option of [overriding the isSerializable option in the serialization check middleware](https://github.com/reduxjs/redux-toolkit/issues/456#issuecomment-1405895351).
