### ISSUE TITLE
Integrate Spring Boot's Docker Compose support

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#24469]
##### **Overview of the issue**

Add Docker Compose support so dependent containers are started automatically. At the bottom of [the docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.docker-compose), it mentions how you can point to a file. It'd be cool if multiple files are allowed.

##### **Motivation for or Use Case**

This is a better developer experience because you do t have to start anything manually. It might help simplify our CI jobs too.

##### **JHipster Version(s)**

8.0.0

**Comment by DanielFran** [comment]
> Hello would like to work on this .Possible to assign me this ?

Go head😉

**Comment by mshima** [comment]
@shwetarkadam have you worked on this?

**Comment by mshima** [comment]
Database not started is the most common error: https://github.com/jhipster/generator-jhipster/issues/27003, https://github.com/jhipster/generator-jhipster/issues/27053, https://github.com/jhipster/generator-jhipster/issues/26375.
I am testing how this integration works and seems to work to avoid this error.

We will probably need to add daily-builds tests.

**Comment by mshima** [comment]
Test plan requires to test every container:
- PostgreSQL, MariaDB, MySQL and h2 in imperative and reactive variants.
- Cassandra, MongoDB, Neo4J in imperative, may require reactive tests.
- Kafka, Redis.

**Comment by DanielFran** [comment]
Increasing bug bounty since it requires lot of work

**Comment by mshima** [comment]
@DanielFran bug bounty claim https://opencollective.com/generator-jhipster/expenses/220550

**Comment by DanielFran** [comment]
@mshima approved

**Comment by vishal423** [comment]
After this change, it seems docker is **must** to run generated applications with a `dev` profile (even though generated applications don't require that). I believe we should highlight this prerequisite and also suggest a way to disable it when not needed via property `spring.docker.compose.enabled=false`
