### ISSUE TITLE
subgen aws lacks gradle support

### ISSUE THREAD

**Issue by seghers** [jhipster/generator-jhipster#2447]
* **Overview of the issue**

Upload WAR to S3
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)

* **Motivation for or Use Case** 

When running the aws subgen I get this breaking error.

* **JHipster Version(s)** 

2.19.0

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "baseName": "captjehipster",
    "packageName": "com.conevoud.captjehipster",
    "packageFolder": "com/conevoud/captjehipster",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "*************"
  }
}

* **Browsers and Operating System** 

Fedora 23 64bit
npm --version:
3.3.12
nvm --version
0.29.0
node --version
v5.1.0

* **Reproduce the error** 

yo jhipster:aws
default input 

* **Related issues** 

I'm not using Websockets
https://github.com/jhipster/generator-jhipster/issues/2299

* **Suggest a Fix** 

/

edit: change path x 2

**Comment by wuethrich44** [comment]
I think there is a problem with hard coded directory in this [line](https://github.com/jhipster/generator-jhipster/blob/master/aws/lib/s3.js#L82).

@deepu105 Do you know how to properly get the path in this line?

**Comment by seghers** [comment]
@wuethrich44 Could be, for me the directory is not 'target' but 'build/libs'

**Comment by wuethrich44** [comment]
ah oke do you use gradle?

**Comment by seghers** [comment]
@wuethrich44  yes

**Comment by seghers** [comment]
@wuethrich44 Where are the 'database username' and 'database password' stored? When rerunning the generator it keeps using stored data.

**Comment by jdubois** [comment]
@seghers it should be in your application-*.yml files

**Comment by jdubois** [comment]
And can you put a better title then "aws subgen error"?

**Comment by wuethrich44** [comment]
You can set a initial password when you run subgen the first time. After that the initial password is used. There is no feature to set the password again. You can do this through AWS Management Console.

@deepu105 Could you switch the path in this two lines ([L82](https://github.com/jhipster/generator-jhipster/blob/master/aws/lib/s3.js#L82 and [L97](https://github.com/jhipster/generator-jhipster/blob/master/aws/lib/s3.js#L97)) if gradle is used as build tool?
