### ISSUE TITLE
Email as user's login issue

### ISSUE THREAD

**Issue by struski** [jhipster/generator-jhipster#2448]
FB signed in users get email as their login. Problem arises if you try to pass that email as a parameter. 
Spring treats everything after the dot as file extension.
Adding :.+ to @RequestMapping(value = "/users/{login:.+}") fixed it for me  
in
com.reptilezilla.web.rest.UserResource.getUser(@PathVariable String login)

**Comment by jdubois** [comment]
Duplicate see #2434
