### ISSUE TITLE
Picture banner of hipster guy

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2451]
With the awesome [PR](https://github.com/spring-projects/spring-boot/pull/4647) of @craigburke, I have generated a nice banner for my jhipster app

![photo](https://cloud.githubusercontent.com/assets/11633333/11624631/6dd41f9a-9cd5-11e5-8df3-82b1bbe2b5f9.png)

I can share the banner.txt if you want :smile:

**Comment by cbornet** [comment]
https://gist.github.com/cbornet/96fb87e390f4c4aad794

**Comment by pascalgrimaud** [comment]
So fun !!!

**Comment by atomfrede** [comment]
:+1:

**Comment by jdubois** [comment]
Yes it's fun, but let's not change our banner with every new release.... Besides it's annoying as we should have the same banner for Spring Boot and for the Yeoman generator, and it's not working the same way.

**Comment by craigburke** [comment]
OMG! Yes!!!

**Comment by cbornet** [comment]
Yes I'm not suggesting to change the banner. I just wanted to show something fun :smile: . This one is 160 columns wide which doesn't respect the standards and thus shouldn't be the default. @craigburke's PR will most certainly be included in SB 1.4 so a long way from now. I'm thinking of making a command line generator (in fact, this is what I did to generate this banner). Or maybe Craig could do it since it is his code after all.

**Comment by craigburke** [comment]
@cbornet When my PR is merged in 1.4 all you'll need is a `banner.jpg` file in the resources folder and it'll generate the ascii art automatically. 

I'm glad to see such an important feature being discussed for JHipster :grinning:

**Comment by cbornet** [comment]
Yes but SB 1.4 release seems so far away... So we need something meanwhile. After all, this is the best SB feature since the devtools !

**Comment by pascalgrimaud** [comment]
@cbornet : I think it could be done in a module ;)

**Comment by cbornet** [comment]
I have done it as a java-cli : see https://github.com/cbornet/image2springbanner and generate your own banner !
As for a jhipster module, this would mean recode it in JS. Probably not worth it...

**Comment by cbornet** [comment]
I think our guru also deserves its banner :smile: 
![jdubois_banner](https://cloud.githubusercontent.com/assets/11633333/11757039/7edbadee-a05e-11e5-8802-1007fdd1c3ba.png)

**Comment by moifort** [comment]
:+1:

**Comment by pascalgrimaud** [comment]
:laughing:
But it's not this picture now! he changed it!

**Comment by cbornet** [comment]
@joshlong from SB team has made it even better : https://github.com/joshlong/bootiful-banners

**Comment by cbornet** [comment]
I forked @joshlong project to get a nice UI over the API. You can check it [here](https://yabb.herokuapp.com)
Note : invert/dark, width, aspect-ratio options available and it uses CIE94 algo

**Comment by jdubois** [comment]
OK this is cool to have my picture at start up, but really I don't know what to do with it... Shouldn't we close this?

**Comment by cbornet** [comment]
Of course this should be closed

**Comment by craigburke** [comment]
lmao :laughing:
