### ISSUE TITLE
Rely on OpenAPI generation for Controllers

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#24512]
##### **Overview of the feature request**

OpenApi maven plugin generates a bit of code based on swagger definition, I propose to rely on Contract first approach in order to generate jhipster's controllers.

##### **Motivation for or Use Case**

* Less code to maintain on Jhipster side (already achieved on open api side, api.yml contract already generated by JH) 
* Contract first makes project more compatible with technologies like 'APIM' and the rest

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
So basically making the current "[api first sub gen](https://www.jhipster.tech/doing-api-first-development/)" the default and jhipster creates its own api spec?

**Comment by Tcharl** [comment]
Yes, this is the idea: use well known generator for what they are good at (i.e. OpenAPIgen, Liquibase entity gen, Mapstruct processor, ...), and jhipster generator using it as a basis for its contribution
