### ISSUE TITLE
Reintroduce the maven (and gradle)-liquibase-maven-plugin snippet

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#24514]
##### **Overview of the feature request**

mvn liquibase diff and other commands (snapshots, doc, ...) where really handy in fast evolving products, also the configuration is really hard to achieve by hand and was well done by the generator. Could it be possible to reintroduce?

##### **Motivation for or Use Case**

update database (not only for generate code, but also custom) incrementally was really helpful on many situations

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Are you sure it’s removed?
https://github.com/jhipster/generator-jhipster/blob/main/generators/liquibase/support/maven-plugin.mts
https://github.com/jhipster/generator-jhipster/blob/4aa14dfee08e3991fd1940f4891adc4c3feeb1f0/generators/liquibase/generator.mts#L322-L360

**Comment by mshima** [comment]
Gradle:
https://github.com/jhipster/generator-jhipster/blob/4aa14dfee08e3991fd1940f4891adc4c3feeb1f0/generators/liquibase/templates/gradle/liquibase.gradle.ejs#L43-L80
