### ISSUE TITLE
Deploy to aws fails to start the environment instance

### ISSUE THREAD

**Issue by robertolos** [jhipster/generator-jhipster#2452]
**Overview of the issue** - AWS fails to start the server instance, in the ElasticBeansTalk web interface I get the following logs:
```
2015-12-07 11:29:44 UTC+0000 	INFO 	Deleting SNS topic for environment wama-env.
2015-12-07 11:29:43 UTC+0000 	ERROR 	Failed to launch environment.
2015-12-07 11:29:43 UTC+0000 	ERROR 	The instance profile aws-elasticbeanstalk-ec2-role associated with the environment does not exist.
2015-12-07 11:26:33 UTC+0000 	INFO 	Using elasticbeanstalk-eu-central-1-265141000127 as Amazon S3 storage bucket for environment data.
2015-12-07 11:26:32 UTC+0000 	INFO 	createEnvironment is starting.
```
**Motivation for or Use Case** - 
**JHipster Version(s)** - 2.24.0
**JHipster configuration, a .yo-rc.json file generated in the root folder** - 
```
{
  "generator-jhipster": {
    "baseName": "abcd",
    "packageName": "com.abcd.server",
    "packageFolder": "com/abcd/server",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": ""
  }
}
```
**Browsers and Operating System** - Arch Linux updated to 07/12/2015
**Reproduce the error** - 
- Create a new IAM user in AWS with the policy 'AWSElasticBeanstalkFullAccess'
- Configure the credentials on your local environment
- run yo jhipster:aws

**Related issues** - np
**Suggest a Fix** - np

**Comment by wuethrich44** [comment]
This is because you doesn't create a instance profile aws-elasticbeanstalk-ec2-role. Create a instance through AWS Managment Console and a profile will automatically generated.

**Comment by robertolos** [comment]
It's the fitst time I use AWS, after searching on internet and playing around with AWS I've been able to deploy my app on AWS. It will be nice if someone adds on the aws jhipster page the exact steps to create the role.

**Comment by deepu105** [comment]
I dont think we should be adding documentation on how to do stuff in AWS it should be referred to in AWS docs

**Comment by wuethrich44** [comment]
I will try to create a role when it not exits. I will provide I PR if I got some time.

**Comment by jeronimoqueiroz** [comment]
Hello @wuethrich44 you need create a role with this format and add it to your user or group.
This action will able your use to create a new roles. 

"Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole"
            ],
            "Resource": "*"
    }
]
