### ISSUE TITLE
Sticky header and footer

### ISSUE THREAD

**Issue by AVE-cesar** [jhipster/generator-jhipster#2455]
As an enhancement, it would be great to have the menu in a sticky header and the phrase "This is your footer" inside a sticky footer.

Perhaps, you can also put some buttons in the sticky footer (like view, edit, delete).

**Comment by jdubois** [comment]
I'm not sure having sticky headers and footers is an improvement: look at Github, it's not sticky and still it's really nice.
It could be a tip in the "tips" section, but I guess that's quite easy to achieve.

**Comment by jdubois** [comment]
No comment here, and I don't want to change the current UI without a good reason
