### ISSUE TITLE
angular - metric page not showing metric params

### ISSUE THREAD

**Issue by manisi** [jhipster/generator-jhipster#24567]
Hi 
metric params not bounding angular  metric page.

<img width="1275" alt="Screen Shot 2023-12-14 at 19 51 27" src="https://github.com/jhipster/generator-jhipster/assets/3120328/7952625d-2043-46d3-ab99-a9cde618946f">

 to JHipster v8.1.0

Welcome to the JHipster Information Sub-Generator

```
new-810@0.0.1-SNAPSHOT /Users/developer/Desktop/new8.1.0
└── generator-jhipster@8.1.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "new810",
    "buildTool": "maven",
    "cacheProvider": "hazelcast",
    "clientFramework": "angular",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "none",
    "creationTimestamp": 1702565323490,
    "cypressAudit": true,
    "cypressCoverage": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "devServerPort": 4200,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [],
    "feignClient": false,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.1.0",
    "languages": [
      "fr",
      "en"
    ],
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "fa",
    "packageName": "com.mycompany.myapp",
    "prodDatabaseType": "mysql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "testFrameworks": [
      "cypress"
    ],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

git version 2.20.1

node: v18.17.1
npm: 10.2.5

Docker version 24.0.6, build ed223bc

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

**Comment by qmonmert** [comment]
@DanielFran I confirm the bug

**Comment by qmonmert** [comment]
@DanielFran https://opencollective.com/generator-jhipster/expenses/178530 🙂

**Comment by DanielFran** [comment]
@qmonmert approved

**Comment by qmonmert** [comment]
@DanielFran thanks
