### ISSUE TITLE
`jhipster ci-cd` prompts for unnecessary answers

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#24564]
##### **Overview of the issue**

I ran `jhipster ci-cd` after creating a new demo app tonight and it asked me far too many questions.

![Screenshot 2023-12-14 at 00 41 12](https://github.com/jhipster/generator-jhipster/assets/17892/a4d25477-423d-4b5b-a054-2952589bb1c9)

##### **Motivation for or Use Case**

It used to be much easier.

##### **Reproduce the error**

Run `jhipster ci-cd` in a new v8 project.

##### **JHipster Version(s)**

```
blog@0.0.1-SNAPSHOT /Users/mraible/dev/jhipster8-demo
└── generator-jhipster@8.1.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "blog",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "none",
    "creationTimestamp": 1702525034689,
    "cypressAudit": true,
    "cypressCoverage": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "Blog",
      "Post",
      "Tag"
    ],
    "feignClient": false,
    "gradleEnterpriseHost": null,
    "herokuAppName": "jhipster8-demo",
    "herokuDeployType": "git",
    "herokuJavaVersion": "21",
    "jhipsterVersion": "8.1.0",
    "languages": [
      "en",
      "es"
    ],
    "lastLiquibaseTimestamp": 1702525214000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "org.jhipster.blog",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "testFrameworks": [
      "cypress"
    ],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

git version 2.39.3 (Apple Git-145)

node: v18.18.2
npm: 9.8.1

Docker version 24.0.7, build afdd53b

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
@ChangelogDate("20231214033814")
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
@ChangelogDate("20231214033914")
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
@ChangelogDate("20231214034014")
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User with builtInEntity
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

search Blog, Post, Tag with no
paginate Post, Tag with infinite-scroll

</pre>
</details>

Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Thanks for using JHipster!

**Comment by mraible** [comment]
Related: the actions that are generated by `jhipster ci-cd` need to be updated.

https://github.com/mraible/jhipster8-demo/pulls

![Screenshot 2023-12-14 at 00 55 33](https://github.com/jhipster/generator-jhipster/assets/17892/91cc730f-fcaa-4161-a3fa-0053a20d9199)

**Comment by mraible** [comment]
Two minutes later, dependabot is aggressive!

![Screenshot 2023-12-14 at 00 56 24](https://github.com/jhipster/generator-jhipster/assets/17892/8cc32251-9ba9-4b43-a149-adcb7f71cdb4)

**Comment by atomfrede** [comment]
It looks like a bug as the promp e.g. for inside docker is supposed to not being shown when selecting github actions: https://github.com/jhipster/generator-jhipster/blob/a9517b22e821c3a351380fb22adbe4a8f4484132/generators/ci-cd/command.ts#L82
