### ISSUE TITLE
jhipster import-jdl command getting stuck midway upon upgrading to jhipster version 8

### ISSUE THREAD

**Issue by raunaqsingh07** [jhipster/generator-jhipster#24574]
while importing jdl with the command jhipster import-jdl my_jdl_FileName.jdl , it starts but gets stuck midway and does not proceed.

Gets stuck at " No change to package.json was detected. No package manager install will be executed.
     info No deployment configured ".

Anyone else faced the same issue upon upgrading to jhipster version 8 and how did you resolve it?

**Comment by atomfrede** [comment]
Are you doing a fresh jdl import inside an empty directory? Or are you trying some kind of update of an older jh7 application?

**Comment by raunaqsingh07** [comment]
no, i have created a new application using jhipster version 8 and then i am importing the jdl into that. i was doing this smoothly before upadting it to jhipster  version 8 but now it stucks midway while importing.

**Comment by atomfrede** [comment]
Can you provide the jdl here for reproducing? I did that multiple times the last week and it worked flawlessy?

**Comment by raunaqsingh07** [comment]
bro i am not even able to import the basic starter jdl that comes up when we open jdl studio.

**Comment by atomfrede** [comment]
Sorry, just trying to help and for that we need as much details as possible. What jhipster version are you using exactly? 8.0 or 8.1? Whats your node/npm environment? Could you please fill the issue template otherwise it is hard to help here.

**Comment by raunaqsingh07** [comment]
node version - v20.9.0
jhipster version - 8.1.0

**Comment by mshima** [comment]
We cannot reproduce the issue since there is not info on how to reproduce.
Please use the bug report template.
The issue seems to be environment related.
