### ISSUE TITLE
ControllerAdvice ExceptionTranslator not get called when exception happen

### ISSUE THREAD

**Issue by TonyLuo** [jhipster/generator-jhipster#2461]
I tried to handle the oauth2 exception in  ExceptionTranslator, but it seems the ExceptionTranslator never got called. Is any configuration need to setup?
`
    @ExceptionHandler(Exception.class)
    @ResponseBody
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public ErrorDTO processSQLException(Exception exception) {
        System.out.println(exception.getMessage());
        return new ErrorDTO(ErrorConstants.ERR_METHOD_NOT_SUPPORTED, exception.getMessage());
    }
`

**Comment by Vaelyr** [comment]
I belueve security exceptions will not be handled by advices at all as they happen outside of that context. These must be handled at service level where AuthenticationManager or Provider is accessed.
