### ISSUE TITLE
Error loading the webapp after upgrade to jhipster 2.25.0

### ISSUE THREAD

**Issue by robertolos** [jhipster/generator-jhipster#2464]
**Overview of the issue** - After the upgrade to jhipster 2.25.0 when I try to access the webapp is loaded only the footer and the Development banner, the spinner keep loading and in the firebug console tab I get the following log:
```
GET http://127.0.0.1:8080/api/account?cacheBuster=1449650354134 401 Unauthorized 98ms	angular.js (line 10765)

GET http://127.0.0.1:8080/i18n/en/global.json 200 OK	6ms	angular.js (line 10765)
GET http://127.0.0.1:8080/i18n/en/main.json 200 OK	4ms	angular.js (line 10765)

Error: JSON.parse: expected ',' or '}' after property value in object at line 32 column 17 of the JSON data
fromJson@http://127.0.0.1:8080/bower_components/angular/angular.js:1271:9
defaultHttpResponseTransform@http://127.0.0.1:8080/bower_components/angular/angular.js:9460:1
transformData/<@http://127.0.0.1:8080/bower_components/angular/angular.js:9551:12
forEach@http://127.0.0.1:8080/bower_components/angular/angular.js:340:11
transformData@http://127.0.0.1:8080/bower_components/angular/angular.js:9550:3
transformResponse@http://127.0.0.1:8080/bower_components/angular/angular.js:10319:21
processQueue@http://127.0.0.1:8080/bower_components/angular/angular.js:14792:28
scheduleProcessQueue/<@http://127.0.0.1:8080/bower_components/angular/angular.js:14808:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://127.0.0.1:8080/bower_components/angular/angular.js:16052:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://127.0.0.1:8080/bower_components/angular/angular.js:15870:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://127.0.0.1:8080/bower_components/angular/angular.js:16160:13
done@http://127.0.0.1:8080/bower_components/angular/angular.js:10589:36
completeRequest@http://127.0.0.1:8080/bower_components/angular/angular.js:10787:7
requestLoaded@http://127.0.0.1:8080/bower_components/angular/angular.js:10728:1
angular.js (line 12520)

Broken interceptor detected: Config object not supplied in rejection: https://github.com/chieffancypants/angular-loading-bar/pull/50 angular.js (line 12520)

"NetworkError: 401 Unauthorized - http://127.0.0.1:8080/api/account?cacheBuster=1449650354134"
account...0354134

GET http://127.0.0.1:8080/scripts/components/navbar/navbar.html 200 OK 3ms	angular.js (line 10765)
```
**Motivation for or Use Case** - The app was upgraded from 2.24.0 to 2.25.0. The app was also previously successfully upgraded to 2.24.0 from 2.23.1 and 2.23.0.
**JHipster Version(s)** - 2.25.0
**JHipster configuration, a .yo-rc.json file generated in the root folder** - 
```
{
  "generator-jhipster": {
    "baseName": "abcd",
    "packageName": "com.abcd.server",
    "packageFolder": "com/abcd/server",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": ""
  }
}
```
**Browsers and Operating System** - Arch Linux updated to 09/12/2015
**Reproduce the error** - 
- Create an app with jhipster 2.24.0
- Upgrade the app to jhipster 2.25.0
- Access the webapp with the browser

**Related issues** - np
**Suggest a Fix** - I noticed that my android app is able to login successfully. I also tried to create a new app with jhipster 2.25.0 and the webapp works fine. I suppose something went wrong in the upgrade process of the webapp. I also checked with git my customisations and there is only some change in the layout of the navbar, no changes in the backend security section. I also tried to substitute the index.html, main.html, navbar.html with the ones of the new app but this doesn't solve the issue.

**Comment by jdubois** [comment]
It looks like you have an error reading a JSON file, and as the last one is the "main.json" file, could you have a look at it? And check if the JSON in this file is correct?
I'm guessing you had a conflict in that file

**Comment by robertolos** [comment]
Hi @jdubois,
The issue was in global.json. There is a missed comma before the new element  "jhipster-needle-004".
Please refer to the attached screenshot

**Comment by jdubois** [comment]
OK, this comes from the first paragraph of our release notes then, on the "needles":
http://jhipster.github.io/2015/12/04/jhipster-release-2.25.0.html

So this is "normal", but indeed I didn't take enough time for this kind of issue... And by the way you will get it again in the next version, as this has changed again :-(

-> the solution is to remove the line with "additionalEntity", this is not used anymore, now we use the new line below it (jhipster-needle-xxx)

**Comment by robertolos** [comment]
Was not clear that is needed to remove "additionalEntity", btw thanks for the help!
