### ISSUE TITLE
Add support for enabling the use of Keycloak with Spring Security

### ISSUE THREAD

**Issue by raehalme** [jhipster/generator-jhipster#2465]
[Keycloak](http://keycloak.jboss.org/) is an open source integrated SSO and IDM solution built on top of OAuth 2.0 and OpenID Connect. Keycloak provides numerous adapters for application types to make it really simple to enable it as the authentication mechanism. Spring Security already has [a ready-made adapter](https://github.com/keycloak/keycloak/tree/master/integration/spring-security) available as part of the distribution. 

It would be great to have direct support for enabling and pre-configuring Keycloak when creating a new application with JHipster. It could be a one more option to the list of authentication types (3/15).

**Comment by jdubois** [comment]
One solution is indeed to add one more question to the list of authentication types.
But, as far as I understand, Keycloak is going to be a third-party service, so in the end it's always complex for us to integrate, as we can't test and support this ourselves (we would need to install a Keycloak server, work with different versions... lots of work).
We are currently rolling out a new "module" system, and it looks like a good option for this. We already have people (ping @cbornet ) doing "security modules", so you also maybe work with them.

This is not officially released yet, but here is:
- [our modules marketplace](https://jhipster.github.io/modules/marketplace.html#/list)
- [how to make a module](https://jhipster.github.io/modules/creating_a_module.html)

For what you do, you will most certainly need a new extension point (or "needle" as we call them): if you go this way, don't hesitate to ask us for this.

**Comment by raehalme** [comment]
Keycloak has pretty extensive test suite available where they are using, for example, Arquillian while running tests against the service. I'm pretty sure the same technique could be used here as well. There're also Docker images available, and I've published [a simple Vagrant setup](https://github.com/AitioGroup/keycloak-vagrantfile) to make testing easier.

But thanks! I'll have a look the "module" system when I've a chance to focus on this a bit more.

**Comment by jdubois** [comment]
Oh, Arquillian, that's exactly why I don't want to go that way! I've worked on several projects using this, I don't want to use that ever again.
So the good thing with modules is that people using Keycloak can still do whatever they want with Arquillian, and I don't have any of those issues, as we are cleanly separated. Should be perfect for everyone!
I'll let you do the module -> I'm closing this as we won't work on this from the JHipster side, but of course you can add more tickets if needed (if you do a module, you might want a new variable, function or needle, just ask!)

**Comment by jdubois** [comment]
Hi @raehalme we've had some recent new works, in the field of microservices, and I'm finding Keycloak looks like a very good idea for #2584
This is quite a different use-case, but if we want to have an OAuth2 server, Keycloak looks like an excellent option, I'm definitely going to test this out!
