### ISSUE TITLE
Unauthorised access of sensitive data on https://dev.azure.com/jhipster/

### ISSUE THREAD

**Issue by 1997pinchu** [jhipster/generator-jhipster#24678]
##### **Overview of the issue**

During the analysis it was observed that your development application unauthorized access and disclosing sensitive data.

##### **Motivation for or Use Case**

This is disclosing username and password publically

##### **Reproduce the error**

1. Navigate to "https://dev.azure.com/jhipster/ff00337a-468d-47ef-a623-6f7e64f027cb/_apis/build/builds/14868/logs/145"
2. And search Username and password.
3. You will get in page.

##### **Suggest a Fix**
It is recommended to remove sensitive data from page

##### **JHipster configuration**
![image](https://github.com/jhipster/generator-jhipster/assets/31610037/8fb6be86-bd5e-4f0d-84f0-62d1fd681f44)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

https://dev.azure.com/jhipster/ff00337a-468d-47ef-a623-6f7e64f027cb/_apis/build/builds/14868/logs/145

##### **Browsers and Operating System**
Firefox

**Comment by atomfrede** [comment]
@jhipster/developers  Closing this as I don't see any issue here as the builds are old, the logins are documented elsewhere anyways and the build just did a curl and thats the homepage content of a microservice.
