### ISSUE TITLE
[Mapstruct] Simplify dto conversion for list (maybe)

### ISSUE THREAD

**Issue by sbert** [jhipster/generator-jhipster#2467]
To convert list to dto list we can use directly mapstruct
in `_entityMapper.java` add something like : 
`List<<%= entityClass %>DTO> <%= entityInstance %>sTo<%= entityClass %>DTOs(List<<%= entityClass %>> <%= entityInstance %>s);`

And change in common templates `<% if (dto == 'mapstruct') { %>.stream()
            .map(<%= entityToDtoReference %>)
            .collect(Collectors.toCollection(LinkedList::new))<% } %>` by a call to the new method

**Comment by cbornet** [comment]
:+1:

**Comment by jdubois** [comment]
Yes can you send a PR?
