### ISSUE TITLE
Health page same url

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#2471]
monitoring.service.js
```javascript
checkHealth: function () {
                return $http.get('health').then(function (response) {
                    return response.data;
                });
            },
```
health.js
    url: '/health',

Page loads through routing, but when refresh or going directly, shows json instead of page. Change 'health' to 'api/health' or something.

The same with metrics.

**Comment by delverdev** [comment]
The same with metrics

**Comment by deepu105** [comment]
route url will be something like `localhost:8080/#/health` the json will appear if you hit api url `localhost:8080/health` that is normal unless you are using html%mode without # in the url. are you??

**Comment by delverdev** [comment]
Yes, I am. What should I do?

**Comment by jdubois** [comment]
The HTML5 version is just a tip, not the "normal" JHipster, so it's not really a JHipster bug.

-> could you have a look at updating the tip? For this you would need to do a PR on https://github.com/jhipster/jhipster.github.io

**Comment by deepu105** [comment]
@delverdev you can rename the angular routes to something like health-page or something that, it wil solve the issue for you

**Comment by jdubois** [comment]
I don't understand if this is an issue with the tip or not -> could you follow the guidelines, give us your version information, how to reproduce, etc.... I'm closing this as this doesn't follow the guidelines

**Comment by delverdev** [comment]
I've solved the issue, but not the best way. First, I added *management.context-path=/api* to *application.yml*. I don't know why, but with this, api/metrics/metrics returns nothing! api/health and api/dump works, so if we will get whats wrong with api/metrics/metrics, I will make the tip more correct.
