### ISSUE TITLE
Split database repositories for easier maintenance.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#24726]
##### **Overview of the feature request**

We currently have a single template for repositories.
Shared code is very small, we should split.

##### **Motivation for or Use Case**

Easier maintenance.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@mshima what file are you thinking of?

**Comment by mshima** [comment]
@qmonmert https://github.com/jhipster/generator-jhipster/pull/24727 for now.
I will take a look if other files applies.
