### ISSUE TITLE
Any way to switch database platform on a running server

### ISSUE THREAD

**Issue by xjiaoyang** [jhipster/generator-jhipster#2472]
for example:
generate with mysql, but now i want use sqlserver or oracle, any way to do that? any sugestions?

**Comment by deepu105** [comment]
take the `.yo-rc.json` file from current folder root, copy to new folder,
change the database to oracle or what you want, rerun yo jhipster, rerun
all entities(check doc for command to rerun all
http://jhipster.github.io/creating_an_entity.html)

then merge using git or beyond compare.

This is the only way as of now
