### ISSUE TITLE
[jhipster-sample-app-websocket] Websocket tracker not working 

### ISSUE THREAD

**Issue by duongxinh2003** [jhipster/generator-jhipster#24722]
##### **Overview of the issue**

Websocket demo app throws 403 Forbidden
##### **Motivation for or Use Case**

Run for example of Spring security WebSocket

##### **Reproduce the error**
Clone source code from repository `jhipster-sample-app-websocket`
1. Run `npm install` to get dependencies
2. Run Backend by command line `./mvnw`
3. Run Frontend by command line `npm start`
When login page http://localhost:9000/ and then checking Devtools -> Network tab, an error occurred when calling Websocket:
http://localhost:9000/websocket/tracker/info?t=1704189156457 (403 Fobidden)
<img width="1643" alt="image" src="https://github.com/jhipster/generator-jhipster/assets/25058528/965d254c-09ab-42aa-a1ae-597cc48de994">

##### **JHipster Version(s)**

8.1.0

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
As stated in the message authentication is required.
Websocket implementation uses sockjs and requires the authorization token to be passed through headers.
The sample implementation is available at admin/tracker.

**Comment by duongxinh2003** [comment]
Thanks!
