### ISSUE TITLE
import angular-dynamic-locale failed

### ISSUE THREAD

**Issue by xjiaoyang** [jhipster/generator-jhipster#2473]
bower_components dir layout changed if i already have angular-dynamic-locale 0.1.29 installed.

![image](https://cloud.githubusercontent.com/assets/728884/11742449/f2ab0518-a03a-11e5-8829-25dfb8234c47.png)

index.html

![image](https://cloud.githubusercontent.com/assets/728884/11742461/0d6c5ad2-a03b-11e5-9d62-2088099693d6.png)
 and in bower.json, required 0.1.28

**Comment by xjiaoyang** [comment]
of course i can easily fix this , but i want hear what you guys say.

**Comment by gmarziou** [comment]
Your report is not clear, it does not follow [our guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md), could you please detail what you have done? bower install, grunt/gulp, ...

The wiredep grunt/gulp task reads the bower.json files for each of your app dependencies., if something is wrong it could be due a wiredep issue or wrong bower.json from angular-dynamic-locale which you could override in your app's bower.json.

**Comment by jdubois** [comment]
Looks like you found an issue, but as I'm closing this as you don't follow the guidelines
