### ISSUE TITLE
UserRepository and PersistentTokenRepository has different implementations, split to each generator.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#24736]
##### **Overview of the feature request**

Server generator should be used for shared code.
UserRepository for Cassandra is specific and should be split.
https://github.com/jhipster/generator-jhipster/blob/283e987c65d9b2debadcb06d0867c8c1bdf1d0b7/generators/server/templates/src/main/java/_package_/repository/UserRepository.java.ejs#L441

Same for PersistentTokenRepository:
https://github.com/jhipster/generator-jhipster/blob/ef5a5d334f710976164ee6a297d593d0ecaad593/generators/server/templates/src/main/java/_package_/repository/PersistentTokenRepository.java.ejs#L86

Others databases has some shared code, but still very different.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by dwarakaprasad** [comment]
> PersistentTokenRepository still missing

Ok, will work on it this week...
