### ISSUE TITLE
What is the best way to change the root path in the frontend, particularly in vuejs? 

### ISSUE THREAD

**Issue by kdevalgas** [jhipster/generator-jhipster#24767]
Motivation for or Use Case
Change the root path '/' to '/dashboard/' without modifying the route generated but the new root path is applied automatically. 

Related issues
No

Suggest a Fix

JHipster Version(s)
8.1.0

**Comment by mshima** [comment]
Public path is not officially supported by JHipster.
Looks like you want just the ui to use another context path, which is more complicated then the entire application.

You can see https://vitejs.dev/guide/build#public-base-path.
But this feature is not officially supported by JHipster.
