### ISSUE TITLE
Oauth websocket problem jhipster v2.5

### ISSUE THREAD

**Issue by aFousan** [jhipster/generator-jhipster#2477]
Oauth websocket with token works perfectly on same origin,but having a problem when get websocket from other external angularjs application.Even disables csrf for websocket in websocket security configuration.And I have a issues with corsfilter from external angular application...any help...

**Comment by aFousan** [comment]
I got this error in console when connecting tracker websocket with my external angularjs application ....."A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:8100' is therefore not allowed access."

**Comment by jdubois** [comment]
Could you follow the guidelines and give version informations, how to reproduce, etc... ?
This kind of thing is tricky, so without the right information we will lose too much time searching for it.
Anyway, it looks like your error is when using another front-end as you speak of "same origin": this is not something we generate, so this is not a JHipster issue.
Might be a "feature request", but once again we need more information.
