### ISSUE TITLE
Support for the Vaadin UI Framework

### ISSUE THREAD

**Issue by josiahhaswell** [jhipster/generator-jhipster#24794]
##### **Overview of the feature request**

As a Vaadin user, it would be nice if JHipster supported the [Vaadin UI framework](https://vaadin.com/)

##### **Motivation for or Use Case**
1. Vaadin is a widely-used Java UI technology
2. Support for Vaadin has the potential to increase breadth of both projects

##### **Related issues or PR**
[I see an old issue related to this request (from 2018)
](https://github.com/jhipster/generator-jhipster/issues/8410)

- [x] Checking this box is mandatory (this is just to show you read everything)

I'm happy to work on contributing this feature if it seems like there's agreement that it should be implemented.  

Vaadin does have commercial features (components, support, etc.)--does that pose a problem?  The core framework and many components are completely open-source.

# Scope
- [ ] Generator for a Vaadin Flow template
- [ ] Generator for a Vaadin Hilla template
- [ ] Integrate with Spring Security
- [ ] Spring framework support
- [ ] Micronaut support
- [ ] Quarkus support 

Before I embark on submitting a PR, are there any comments or considerations I may be missing?

**Comment by mraible** [comment]
This would be best implemented as a [JHipster Blueprint](https://www.jhipster.tech/modules/creating-a-blueprint/). Having it separate from the core should make it easier to maintain. 

Would you just be using Vaadin for the frontend or for the backend, too? 

Also, please keep in mind that creating it is the easy part. Maintaining it for years to come is a lot harder.

**Comment by mshima** [comment]
@josiahhaswell are you willing to contribute?

**Comment by josiahhaswell** [comment]
Hi folks,

Thanks for the responses.  @mraible -- yes, I'm working with the Vaadin team to ensure long-term maintenance.  I may not proceed if I can't secure that.

@mshima Yes, I'd be happy to perform at least the initial work, and contribute towards maintenance long-term

**Comment by atomfrede** [comment]
Thats big news to have the Vaadin team on board. Looking forward to the first result. Do you want us to create a repo under the jhipster org or do you want to start elsewhere?

**Comment by mshima** [comment]
The first step is to generate a working sample project.

**Comment by josiahhaswell** [comment]
> Thats big news to have the Vaadin team on board. Looking forward to the first result. Do you want us to create a repo under the jhipster org or do you want to start elsewhere?

Hi @atomfrede -- we'd love to have a repo under the JHipster org.  I can try to get an initial sample project here shortly.  I'm currently traveling so I wouldn't expect much progress on this before February
