### ISSUE TITLE
Help Request Setting up Apache Http Reverse Proxy for Tomcat

### ISSUE THREAD

**Issue by pvlastaridis** [jhipster/generator-jhipster#2482]
I am trying to work with Apache as Http Reverse Proxy of Tomcat. I get the 403 Exception "Expected CSRF token not found. Has your session expired?" 

The reasons I want to use Apache as a reverse proxy are:
1) One SSL Certificate for php and numerous Tomcat apps.
2) One domain name for php and tomcat apps

But before applying SSL I get this exception. Apache vhost file

<VirtualHost *:80>
ServerName pvlastaridis.users.uth.gr
DocumentRoot /var/www/html/
DirectoryIndex index.html index.php
Alias /  /var/www/html/

<Location /apps/>
ProxyPass http://localhost:8080/
ProxyPassReverse http://localhost:8080/
ProxyPassReverseCookiePath /apps/okeanosjhip/ http://localhost:8080/okeanosjhip/
</Location>

</VirtualHost>

Please take a look here of what is going on:

When I open port 8080 everything works OK
http://pvlastaridis.users.uth.gr:8080/okeanosjhip/

With http proxy it seems the JSESSIONID cookie is not included in the request cookies
http://pvlastaridis.users.uth.gr/apps/okeanosjhip/

**Comment by gmarziou** [comment]
Please read our guidelines, this is a question not an issue with JHipster, we use stackoverflow for such questions.

**Comment by jdubois** [comment]
@gmarziou is correct, this is not a bug report and it should go to StackOverflow.
However this is an interesting subject -> if you have an answer please consider adding a tip to the JHipster website (in the tips and tricks section)

**Comment by pvlastaridis** [comment]
OK Thanks guys. Just a desperate reaction of me. I would not like to hang on stackoverflow my virtual host urls and I thought if someone has done it before it will be helpful for him to also take a look at what is happening.
