### ISSUE TITLE
Just a small improvement regarding gitignore

### ISSUE THREAD

**Issue by mangelovski** [jhipster/generator-jhipster#2484]
add app.constants.js into gitignore, I wouldn't like to commit it after each grunt build since the comment mentions it is generated by NGCONSTANT settings.

the line to be put into gitignore with the folder structure I have is: /src/main/webapp/scripts/app/app.constants.js

Regards,

**Comment by jdubois** [comment]
That means you would need to generate a Grunt build before running the app: here what I like is that someone cloning the project, without even having Bower or Grunt, can run it directly (because of the Maven wrapper).
So I would like to keep this, unless there are other comments?

**Comment by mangelovski** [comment]
Yup, that seems logical. I forgot about that scenario. I'll add it locally :)
