### ISSUE TITLE
Hide "Do you want to generate a feign client?" when the application type is set to "Monolithic application" in the application creation process.

### ISSUE THREAD

**Issue by devalgas-k** [jhipster/generator-jhipster#24842]
##### **Overview of the feature request**

ERROR! An error occured while running jhipster:server#feignMigration

![image](https://githu
![Screenshot_3](https://github.com/jhipster/generator-jhipster/assets/30204875/7338d546-2c91-4264-9ed5-34c4789ac0db)
b.com/jhipster/generator-jhipster/assets/30204875/1a177382-64d0-4cdc-9ab6-b417d54b0269)

##### **Use Case**

```
 I propose that we customize the user experience by hiding this prompt specifically for Monolithic applications
```
JHipster Version(s)

```
jhipster-8.1.0
```

Suggest a Fix

```
```

JHipster configuration
```
```

**Comment by atomfrede** [comment]
This is already done, but not yet released.
