### ISSUE TITLE
How to format ZonedDateTime using @JsonFormat?

### ISSUE THREAD

**Issue by TonyLuo** [jhipster/generator-jhipster#2489]
I would like to format the    lastModifiedDate to be "yyyy-MM-dd HH:mm:ss" using @JsonFormat, but the restful output json is "lastModifiedDate": "2015-12-11T04:47:44Z"?  Is there any mistake?

``
 @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private ZonedDateTime lastModifiedDate;

**Comment by jdubois** [comment]
Please follow the guidelines to report a bug... This should probably go to Stackoverflow, this is why I'm closing this.
Concerning the date format, it is made to work with AngularJS, so if you format it another way, I don't know what that will do with the front end
