### ISSUE TITLE
Users shouldn't be able to delete their own accounts in user management

### ISSUE THREAD

**Issue by rkohel** [jhipster/generator-jhipster#2491]
* **Overview of the issue**

An admin user can delete his own account in user management.

* **Motivation for or Use Case** 

After deleting his own account, the user is still signed in and can try to change his settings or password which would lead to an error because the data to update isn't there anymore.

* **Reproduce the error** 

Sign in as admin
Administration -> User management
Delete admin
Account -> Settings
Change First Name and Last Name
Save

* **Suggest a Fix** 

Disable the delete button for the signed in user in user management.

If my proposed solution is ok, I'll make a PR.

**Comment by wuethrich44** [comment]
:+1:

**Comment by thiagogcm** [comment]
Or logout the user after he deleted himself

**Comment by atomfrede** [comment]
I think it should not be possible to delete one self.

**Comment by sendilkumarn** [comment]
@rkohel  rather we can remove the user from listing in user management screen. Anyhow update of account is available in Account page.

**Comment by rkohel** [comment]
@sendilkumarn first, I was also thinking about to remove the user from the list.
But if an user has "ROLE_ADMIN" but not "ROLE_USER", he cannot access the account pages.
I'm not sure about, but maybe that is just another issue?
Maybe anyone can explain how this is intended to work?
Should an user with "ROLE_ADMIN" but without "ROLE_USER" be able to access the account pages?

**Comment by Vaelyr** [comment]
In front-end you just have to check equality for id or email and hide the button. In backend the same against current principal as one if. What's the problem?

**Comment by rkohel** [comment]
@Vaelyr the question is actually not about how to implement it technically.

**Comment by Vaelyr** [comment]
You confuse 2 different use cases here. Disabling the option to delete in this case is not a correct solution anyway and does not solve the real problem existing. I actually find it correct given described case, the account updating resource should include permission check. The service should always query for existing database record and handle the rest from there. Currently I don't think there was role check for updating the account, that would work at least for token based or oauth authentication, not sure how session acts.

**Comment by dimeros** [comment]
So the technical solution is what @Vaelyr mentioned before: 
1) client side: check equality for id or email and hide the button
2) server side deleting user: if a user tries to delete himself a 403 http response should be thrown. 

Is this correct? I will try to assign this PR to myself

**Comment by jdubois** [comment]
Yes looks correct to me.
You can't assign the issue to someone outside of the team (that's annoying with Github...), but if you tell here that you'll do the PR I don't think anybody will steal it from you :-)

**Comment by dimeros** [comment]
Ok I will try to do it.

**Comment by dimeros** [comment]
So how can I create a pull request for this in order to be reviewed?

**Comment by pascalgrimaud** [comment]
@dimeros : read the [CONTRIBUTING.md](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md)

Fast steps :
- fork generator-jhipster
- clone your fork
- create branch (it's important in my opinion)
- work on your branch
- commit/push to your fork project
- as soon as it's ready, create pull request

**Comment by deepu105** [comment]
Yes indeed, creating a branch is very important :)
