### ISSUE TITLE
Application bootstrapping issue after upgrading ng-jhipster generated application(with angular) to angular 17 and generator-jhipster

### ISSUE THREAD

**Issue by nitin1104** [jhipster/generator-jhipster#24941]
##### **Getting errors upgrading my Angular application generated with ng-jhipster**

I need help resolving an issue I am facing in upgrading my Angular application generated with ng-jhipster, 

Error: Unexpected value 'NgJhipsterModule' imported by the module 'Itrack2SharedLibsModule'. Please add an @NgModule annotation.

**Comment by mshima** [comment]
ng-jhipster has been discontinued for a long time.
Every relevant implementation is been generated in application now.
