### ISSUE TITLE
Main generator tests are output improperly in IntelliJ

### ISSUE THREAD

**Issue by geraldhumphries** [jhipster/generator-jhipster#2495]
* **Overview of the issue**

Multiple `describe`s with the same name in the same file are causing test output to look like this:

![tests3](https://cloud.githubusercontent.com/assets/5278953/11848334/cd033ca0-a3ef-11e5-903b-d5e61a24619c.png)

* **Motivation for or Use Case** 

Makes test output harder to read

* **JHipster Version(s)** 

master

* **Reproduce the error** 

Run the Mocha tests in the main generator through IntelliJ.

* **Suggest a Fix** 

Move the code in all the `before`s to inside its corresponding `it`, then move all `it`s under a single `describe`.

**Comment by jdubois** [comment]
I can't reproduce this:

- Do you mean the tests in `generator-jhipster`?
- You seem to use some kind of plugin to run those tests, what exactly are you using?

If you want to make a PR with this, no problem, looks like you know this better than me!

**Comment by geraldhumphries** [comment]
1. Yeah, the Mocha tests from `generator-jhipster`.

2. I am using a Mocha run config in IntelliJ, which is bundled in the AngularJS plugin. Instructions [here.](https://www.jetbrains.com/idea/help/running-mocha-unit-tests.html)

**Comment by geraldhumphries** [comment]
Here is a screenshot of my config:

![mocha](https://cloud.githubusercontent.com/assets/5278953/12043196/a86698c2-ae50-11e5-8a34-e845f27d8393.png)

**Comment by jdubois** [comment]
Hey, that's super cool!!!! Would like to improve the IDEA setup at http://jhipster.github.io/configuring_ide_idea.html ? Otherwise I will do it when I have the time.

And indeed the names are not good, would you like to do a PR?

**Comment by geraldhumphries** [comment]
I can do a PR. I will also look at updating the docs - this specific configuration is not very useful for JH users (it's for JD developers) but there are other useful configs like Karma.
