### ISSUE TITLE
Update to version 2.26.0. CustomAccessDeniedHandler class is not being created during update.

### ISSUE THREAD

**Issue by lluiscanals** [jhipster/generator-jhipster#2497]
* **Overview of the issue**
    
When updating to jhipster 2.26.0 from 2.25.0 is created a new line of code in SecurityConfiguration class 
```Java
http
            .exceptionHandling()
            .accessDeniedHandler(new CustomAccessDeniedHandler())  // This line is new!!!
            .authenticationEntryPoint(authenticationEntryPoint)
```
But the problem is that the class file is not being created.

* **Motivation for or Use Case** 
   
    Updating a hjipster app.

* **JHipster Version(s)** 
 
    2.26.0

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

 {
  "generator-jhipster": {
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "xauth",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "testFrameworks": [
      "gatling",
      "protractor"
    ]
  }
}

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

* **Browsers and Operating System** 

* **Reproduce the error** 

    Update an app to jhipster 2.26.0

* **Related issues** 

* **Suggest a Fix**

**Comment by jdubois** [comment]
Thanks a lot!!!!!
I don't know how this could have passed our Travis build @pascalgrimaud ???
Let's do an emergency new release

**Comment by lluiscanals** [comment]
You are welcome. Glad to help!

**Comment by pascalgrimaud** [comment]
Strange, no error in Travis Log for `mvn test` / `grunt test`, and the app starts with `mvn spring-boot:run`
I will check this !

**Comment by jdubois** [comment]
Thanks really! Now I understand why it did pass the Travis build: we don't test the XAuth option!!

**Comment by jdubois** [comment]
@pascalgrimaud I'm adding a Docker build for this -> I need to learn what you did so that's a good exercise!!

**Comment by pascalgrimaud** [comment]
Yes ok ! All options are not tested (for example Hazelcast). I tried to cover a lot of combinaisons and we can go on to improve it.

**Comment by jdubois** [comment]
Then we will also need Hazelcast :-)
Yes let's add more options, it's free anyway... Thanks a lot Travis, as all those builds should cost a good amount of money!!

**Comment by lluiscanals** [comment]
Can you confirm it is working? I have made the update with 2.26.1 and the class is not created :(
I'm implementing by hand for now.

Regards!

**Comment by jdubois** [comment]
This is normal: this class is only for CSRF protection and with a stateless autenth you do not need this.
So it's the line in the configuration file which should be deleted.

**Comment by rakishmu** [comment]
hi. can anyone help me ? how to upgrade from version 2.25.0 ? because i already development using that one.

**Comment by pascalgrimaud** [comment]
Look at http://jhipster.github.io/2015/12/17/jhipster-release-2.26.1.html
Don't forget to commit or create branch with git before trying updating to latest version
So you'll be able to rollback

**Comment by rakishmu** [comment]
@pascalgrimaud thanks a lot !
