### ISSUE TITLE
German Administration for Metrics wonky due to locale error

### ISSUE THREAD

**Issue by timothystone-knsl** [jhipster/generator-jhipster#24985]
##### **Overview of the issue**

When generating a new application and selecting German, `de`, for **native** internationalization support, the Administration > Metrics (_Anwendungs-Metriken_) page goes "wonky." The error shown below is reported in the Developer console.

```console
Error: NG02100: InvalidPipeArgument: 'NG0701: Missing locale data for the locale "de".' for pipe 'DecimalPipe'
    at invalidPipeArgumentError (common.mjs:4021:12)
    at DecimalPipe.transform (common.mjs:4819:19)
    at pureFunction2Internal (core.mjs:27550:65)
    at Module.ɵɵpipeBind2 (core.mjs:27771:9)
    at JvmMemoryComponent_Conditional_3_For_4_Conditional_3_Template (jvm-memory.component.html:10:13)
    at executeTemplate (core.mjs:12158:9)
    at refreshView (core.mjs:13390:13)
    at detectChangesInView (core.mjs:13615:9)
    at detectChangesInViewIfAttached (core.mjs:13578:5)
    at detectChangesInEmbeddedViews (core.mjs:13535:13)
```

##### **Motivation for or Use Case**

German should be supported identically as others in I18N.

##### **Reproduce the error**

```shell
jhipster
...
...
select German as NATIVE and optionally add others
```

##### **Related issues**

None identified.

##### **Suggest a Fix**

The console error points to the `metrics.component.ts` then references the `jvm-memory.component.html` (see error above). 

Something here dislikes `de` (German).

##### **JHipster configuration**

**Info**

```
de-en@0.0.1-SNAPSHOT /private/tmp/de-en
└── generator-jhipster@8.1.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "deEn",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "slate",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1706409847503,
    "cypressAudit": true,
    "cypressCoverage": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [],
    "feignClient": false,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.1.0",
    "languages": [
      "de",
      "en"
    ],
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "de",
    "packageName": "com.mycompany.myapp",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "testFrameworks": [
      "gatling",
      "cucumber",
      "cypress"
    ],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode)

git version 2.39.3 (Apple Git-145)

node: v18.19.0
npm: 10.2.3

Docker version 24.0.7, build afdd53b

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None.

##### **Browsers and Operating System**

macOS 14.3
Chrome 121

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
Not reproduced on the main branch

**Comment by timothystone-knsl** [comment]
> Not reproduced on the main branch

Suggesting that something is fixed on the main branch or something else?

**Comment by mshima** [comment]
It’s fixed by https://github.com/jhipster/generator-jhipster/pull/24630

**Comment by qmonmert** [comment]
thanks @mshima it's me which fixed it ^^
