### ISSUE TITLE
Migation of Entities to new Date handling

### ISSUE THREAD

**Issue by TransparencyInternationalEU** [jhipster/generator-jhipster#2499]
This is related to issue #2173 :
I created a jhipster app with the 2.15 generator. During upgrade, I changed the type of various date Fields from the previous default Joda DateTime to ZonedDateTime, which is used in the latest sample app. 
Yet, serializing / deserializing is not working properly. 

Before, the field startDate was ```@Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime")
	@JsonSerialize(using = CustomDateTimeSerializer.class)
	@JsonDeserialize(using = CustomDateTimeDeserializer.class)
	@Column(name = "start_date")
	@JsonView(DataTablesOutput.View.class)
	private DateTime startDate;``` 
which I changed to 

```@JsonSerialize(using = JSR310DateTimeSerializer.class)
	@JsonDeserialize(using = JSR310LocalDateDeserializer.class)
	@Column(name = "start_date")
	private ZonedDateTime startDate;```

Still, jackson complains about incompatible types. 
So, what is the right way to annotate the startDate field?

**Comment by cbornet** [comment]
You don't need to annotate at all. Jackson serializers are registered globally.

**Comment by TransparencyInternationalEU** [comment]
Indeed, without the @JsonSerialize annotations it works. Thank you.
