### ISSUE TITLE
Change the `upgrade` command to print migrate blueprint instructions

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#25033]
##### **Overview of the feature request**

We're getting a lot of issue reports about the `jhipster upgrade` command not working. Rather than having to keep telling to try the migrate blueprint, let's just print the instructions to the console.

##### **Motivation for or Use Case**

Reduce support required.

**Comment by mshima** [comment]
The idea is to update the upgrade with a reduced version of the migrate blueprint. And add a info about the advanced features of the migrate.
I plan to do it this week.
