### ISSUE TITLE
support for kotlin as a server-side language

### ISSUE THREAD

**Issue by jasperblues** [jhipster/generator-jhipster#2505]
Could also be a client side language?

**Comment by jdubois** [comment]
What do you want to do with it???

**Comment by jasperblues** [comment]
Choosing Kotlin (for server-side) as an option would mean you get: 

* A Build file with the Kotlin maven or gradle plugin
* Relevant Spring Boot and other stubs generated in Kotlin instead of Java. 

I'm just starting to use JHipster, so if you like I can come back with something more specific after I see exactly what it can already currently do.

**Comment by jdubois** [comment]
It could be a module, have a look at the "market place".

**Comment by jasperblues** [comment]
:+1: That looks good. It may something Jetbrains are interested in contributing - I'll open a ticket on their tracker and see what they say. Otherwise I or someone will surely do it.

**Comment by jdubois** [comment]
Yes this is done exactly for this kind of need, and I will do my best to support this.

**Comment by jdubois** [comment]
I'm closing this as it's going to be a module -> don't hesitate to open issues if you want more variables/functions for your module!

**Comment by otabekgb** [comment]
IMHO it should rather be core feature not a module, because Kotlin is a hipster language for jvm with 100% and seemless java compatibility. It is really trending at the moment and there are examples to use it with spring boot.

**Comment by vadim-shb** [comment]
It is time to create KHipster with Kotlin, Spting and Angular 2 :)

**Comment by janpetryk** [comment]
Any plans on kotlin support after google's announcement?

**Comment by atomfrede** [comment]
I don't think we can support Java and  kotlin.

**Comment by piotrgwiazda** [comment]
Spring 5 is going to have native Kotlin support but start.spring.io allows it already. Spark already supports Kotlin. Think about it. Kotlin is a nice Java drop-in replacement.

**Comment by janpetryk** [comment]
Is it possible to create yeoman Kotlin generator to replace the default Java based?

**Comment by mraible** [comment]
The @jhipster/hipsters team doesn't have any plans to add a new language for the backend code. It's a lot of work, with not much reward. Also, we'd have to change the name to KHipster if we did. 😉

You're more than welcome to create a module that replaces the Java code with Kotlin. https://jhipster.github.io/modules/creating-a-module/

**Comment by amr** [comment]
You could also just generate your JHipster project, then use the IDE to convert it to Kotlin. The IDE is supposed to be very good at that.

**Comment by gmarziou** [comment]
I found this talk quite interesting [KotlinConf 2017 - You Can, but Should You?](https://www.youtube.com/watch?v=ihdEjDoXOgc).

Personally, I'd like to be able to play with Kotlin in JHipster but only if generator was written by a Kotlin expert not by an [Expert Beginner](https://www.daedtech.com/how-developers-stop-learning-rise-of-the-expert-beginner/) ;)

**Comment by janpetryk** [comment]
@gmarziou how are those links relevant in the discussion of introducing Kotlin to JHipster project?

**Comment by gmarziou** [comment]
I'm just discussing with other team members and unless I'm wrong I guess none of us is an expert in Kotlin which basically concludes that we are not the best ones to introduce Kotlin into JHipster.

**Comment by sendilkumarn** [comment]
I made a good progress in converting the application into kotlin and succeeded in running it (but that doesnt mean am an expert).  But it is somewhat cool, I am checking with the conventions and aligning more towards the design of the language.

**Comment by gmarziou** [comment]
This is cool. It's not very easy to know which idioms to use in another language after years of Java. It seems it will be easier with new versions of Spring / Spring Boot.

**Comment by sendilkumarn** [comment]
yeah exactly. But its like you can have refresher course in java when converting 😉 Most of all it works 😁

**Comment by cbornet** [comment]
@sendilkumarn if you start a module under hipster-labs I will contribute !

**Comment by cbornet** [comment]
Warning though : it's a lot of effort to keep up-to-date with the main gen

**Comment by sendilkumarn** [comment]
yeah exactly. I will do that for sure :)

**Comment by deepu105** [comment]
Do it as a server blueprint


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Also, IntelliJ can auto-convert from Java to Kotlin when copy-pasting in case you guys aren't aware

**Comment by sendilkumarn** [comment]
feel free to try it with constructor

**Comment by mizanRahman** [comment]
spring boot 2.0 supports kotlin now and jhipster should provide support for kotlin, right?

**Comment by deepu105** [comment]
@mizanRahman spring boot supports lot of things, doesnt mean we will support all of them. Anyways @sendilkumarn is working on a Kotlin blueprint for JHipster

**Comment by sendilkumarn** [comment]
Leaving a comment here, so any of you guys interested in contributing towards kotlin server side code, here we go repo is [here](https://github.com/jhipster/jhipster-kotlin)
