### ISSUE TITLE
Clean-up JSHint

### ISSUE THREAD

**Issue by jd-carroll** [jhipster/generator-jhipster#2506]
The current state of the code is a bit of a mess  when it comes to linting.  Running `grunt jshint` after a fresh install produces some 200 errors reported.

**If** the current `.jshintrc` is agreed upon, I would like to start putting together pull requests to address these issues.  Running jshint with only generated code should always come back as clean.

Can someone please confirm whether or not the current configuration for `jshint` is the desired configuration.

JHipster: 0.26.1

```
{
  "generator-jhipster": {
    "baseName": "company",
    "packageName": "com.company",
    "packageFolder": "com/company",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "key",
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

**Comment by jdubois** [comment]
Yes definitely. Have a look at the "John Papa style" ticket also, this should be linked.

**Comment by deepu105** [comment]
@jd-carroll are you working on this?

**Comment by deepu105** [comment]
This needs to be done only for gulp based on https://github.com/jhipster/generator-jhipster/issues/2749

**Comment by PierreBesson** [comment]
I think it would be interesting to have some way to make Travis report when there are jshint errors. Also it would allows us to run jshint on all possible configurations.

**Comment by deepu105** [comment]
It is possible, current jshint gulp task is not wired to build or test
tasks if we sequence it it will run or we can do direct gulp jshint on
script as well

**Comment by PierreBesson** [comment]
I don't know if all users would want to have jshint checks by default when they 'gulp test'.
We could add instructions in the documentation about how to do that or put a commented out section in the gulpfile.
So once when I'm finished with the cleanup is it OK if I add 'gulp jshint' in travis/scripts/04-tests.sh ?

**Comment by deepu105** [comment]
cc @pascalgrimaud what do you think about above comment from @PierreBesson

**Comment by pascalgrimaud** [comment]
it could be interesting yes !
just need to test when gulp jshint failed => what happens ? build failed or it's ok ?

**Comment by deepu105** [comment]
if we make build fail for this it will be a lot of failures and will be
very very annoying.

I think for that purpose we should not make build fail, it could be just a
warning. and with our new notification we can warn user of jhhint errors
during gulp test/build as well but without failing the builds

Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
I agree it should not make the build fail, adding it to the gulp test and/or build task seems like the best idea. If users think a particular warning doesn't apply to their code they can change the .jshintrc.

**Comment by PierreBesson** [comment]
I cleaned up a lot of JSHint errors last week.  Now that #2796 is merged. Can we close this issue ?
