### ISSUE TITLE
Misspelling in generated JwtAuthenticationTestUtils.java

### ISSUE THREAD

**Issue by timothystone-knsl** [jhipster/generator-jhipster#25079]
##### **Overview of the issue**

Observed a misspelling in the `JwtAuthenticationTestUtils.java.ejs` template using the `JwtClaimsSet.builder` setting claims via a Lambda expression.

##### **Motivation for or Use Case**

Tidiness.

##### **Reproduce the error**

Observe diff. See `generators/server/templates/src/test/java/_package_/security/jwt/JwtAuthenticationTestUtils.java.ejs`.

##### **Related issues**

None.

##### **Suggest a Fix**

Correct misspelling. See PR #

##### **JHipster Version(s)**

8.1.0

##### **JHipster configuration**

Not applicable.

##### **Browsers and Operating System**

Not applicable. 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by timothystone-knsl** [comment]
🙏 Thanks @mshima.

**Comment by mshima** [comment]
@timothystone-knsl thank you for the contribution.
