### ISSUE TITLE
Add JHipster version in .yo-rc.json

### ISSUE THREAD

**Issue by moifort** [jhipster/generator-jhipster#2507]
I want to know in my module which JHipster version was used to generate the project. Because I need to know if my module will be able to use the needle. 

Is there any way to know?

If not, I propose to add the JHipster version used in the `.yo-rc.json`

**Comment by gmarziou** [comment]
You can find it in 2 places:
- in package.json
- in comments at the top of your Gruntfile.js or gulpfile.js

**Comment by pascalgrimaud** [comment]
To complete the previous answer. In your module, you can put a minimum version of generator-jhipster in your package.json, for example :
```bash
"generator-jhipster": ">=2.26.0"
```

And when the user uses your module, if needle is not found, there should be a message "unable to find..."

**Comment by moifort** [comment]
Thank you! @gmarziou @pascalgrimaud
