### ISSUE TITLE
Sonar: Unnecessary use of conditional expression for default assignment

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#25097]
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=jhipster-sample-application&open=AY1qKP6qZqAZOZp0Vj8m

![image](https://github.com/jhipster/generator-jhipster/assets/9989211/6be99bdb-5bd7-409b-9523-1e7b8cc157d7)

These two solutions don't work:
`return { predicate: sortParam };`
or
`return { predicate: sortParam ?? undefined };`

Indeed this test is in error:
```
    it('should accept empty string', () => {
      const sortState = service.parseSortParam('');
      expect(sortState).toEqual({});
    });
``` 

A solution which fixes sonar is:
`return { predicate: (sortParam && sortParam !== '') ? sortParam : undefined };`
but `sortParam !== ''` is useless.

Maybe add a `NOSONAR` ...

WDYT @mshima ?

Test:
![image](https://github.com/jhipster/generator-jhipster/assets/9989211/4485316f-5727-4752-8d2b-1807fd1f5989)

**Comment by mshima** [comment]
`return { predicate: sortParam || undefined };`?

**Comment by qmonmert** [comment]
nope 🙂
![image](https://github.com/jhipster/generator-jhipster/assets/9989211/fb5dd380-d582-40cf-903b-d03c83d046cf)

**Comment by mshima** [comment]
`return { predicate: Boolean(sortParam) ? sortParam : undefined };`
`return { predicate: sortParam.length ? sortParam : undefined };`
`return { predicate: sortParam && sortParam.length > 0 ? sortParam : undefined };`

**Comment by qmonmert** [comment]
`return { predicate: sortParam?.length ? sortParam : undefined };` seems good
