### ISSUE TITLE
[Enhancement] Replace @Service with @Named (JSR-330)

### ISSUE THREAD

**Issue by c3thethird** [jhipster/generator-jhipster#2511]
If @Inject is used instead of @Autowired, doesn't it make sense to also use @Named instead of @Service/@Component ?

In truth, I guess there isn't really any practical gain. It's more for consistency's sake. It would make the projects more ... standard, and reduce the dependency on Spring, if ever another IoC container would be considered, but taking into account the project's heavy dependency on Spring in general, it wouldn't bring any immediate advantages.

**Comment by Vaelyr** [comment]
Why is this always brought as an argument, that other IoC might be used? I have never seen that happening anywhere in my career and I doubt this project ever moves away from entire Boot stack, so this does not make any sense.

**Comment by jdubois** [comment]
@Service means we are in the service layer: it doesn't really do anything, but maybe some people use it in their pointcuts, and anyway it's more expressive than @Component or @Named

So I would keep it, but yes there needs some guidelines on what we use, and why.

**Comment by c3thethird** [comment]
@jdubois - I fully agree that @Service, @Repository and @Controller are much better than @Named, and help delimit the various layers of the app. But if using those, JHipster might as well use @Autowired. Again, for consistency, not for any other practical reasons.

@Vaelyr - I am NOT making that argument. I am saying that's the only argument for using the JSR annotations instead of the Spring ones. My argument is for consistency. Either @Named & @Injected, or @Service & @Autowired.

I guess that's one of the downsides of being a programmer: being autistic about certain things. But looking at the code generated by JHipster and how neat and organized it is, it seems to me that the people working on it share my obsession for neat, structured, consistent code.

**Comment by cbornet** [comment]
@c3thethird I don't agree : the equivalent of @Named would be @Component, not @Service. @Service is a specialization of @Component and the difference with @Named is meaningful.
On the other hand @Autowired and @Inject are strictly equivalent in Spring so you can use one or the other indifferently.

**Comment by jdubois** [comment]
OK, so the rule is:
Only use standard annotation, unless the specific one is better.
This also applies to Hibernate (vs JPA)

In the specific cases that are quoted here:
- @Service is used as it is more expressive than @Named
- @Autowired are in fact used, when the injection isn't required - something which is not available in the CDI spec

This wasn't been voted by the dev board, this is my own rule I use on my own projects, but it's the first time I see someone unhappy with this. So if this becomes a real issue I'm open to issue a vote on this.

**Comment by jdubois** [comment]
And yes I need to write it somewhere in the official documentation.

**Comment by c3thethird** [comment]
@jdubois Don't get me wrong. I am faaaar from unhappy. In fact, I think JHipster is an awesome tool and I am trying to spread the word about it among my dev friends. My intention is not to criticise, I am just trying to understand why things are done this way, and thought it might be more consistent to use just one set of annotations, but I am perfectly happy using it the way it is today.

@cbornet I understand the reasoning behind this choice.

Thank you both for the replies.

**Comment by atomfrede** [comment]
@jdubois I understand your choice and have no problem with it.
@c3thethird If your concerns are cleared, can we close this issue?

**Comment by c3thethird** [comment]
@atomfrede Absolutely.
