### ISSUE TITLE
Add option to choose passwords when creating a jhipster app

### ISSUE THREAD

**Issue by mihaisimi** [jhipster/generator-jhipster#2512]
In my opinion the default passwords do create a (small) security risk. I think these should be setup by the user when he creates the jhipster app.
If this is considered interesting to have I am volunteering to implement.

**Comment by Vaelyr** [comment]
Where is the risk while developing? I see none.

**Comment by mihaisimi** [comment]
We can argue that default passwords, even in a dev environment could be a bad idea but these are in the liquibase files. This means they can reach an internet exposed site if devs are not careful or just lazy (after all it is a manual process to change them as you need to alter 3 passwords, change the db config file, change the html files that suggest the defaults).

Perhaps Uncle Sam made a better case here:
https://www.us-cert.gov/ncas/alerts/TA13-175A

"Change the defaults passwords as soon as possible":
"Force Default Password Changes
Vendors can design systems to require password changes the first time a default password is used."

**Comment by Vaelyr** [comment]
That just leaves 100 another things that can be left exposed by not being careful, like configurations or certificates, not just Liquibase scripts. You can't reduce the risk by just eliminating one possibility out of many. The possibility of something like this happening especially in test environment is so small. If someone uses defaults in production or outside local machine then these people should be fired. Simple as that.

**Comment by mihaisimi** [comment]
Mathematically eliminating one problem out of many does reduce the overall risk. Except for the case when many tends to be infinite :).

**Comment by jdubois** [comment]
All projects I can think of do it this way (Vagrant, MySQL...), with a default password.
The only exception I see at the moment is Tomcat, and that's a pain to use... Same thing here, this is going to annoy every user.
You're supposed to installer JHipster on your machine, and you're supposed to have it correctly configured -> if your 8080 or 3000 port is open, then you're probably doing it on purpose.
Of course you need to secure your instance afterwards, but I hope this is obvious to everyone going into production.

**Comment by mihaisimi** [comment]
Mysql asks you to provide a root password when using the GUI installer (see User Accounts and Roles capture here):
https://dev.mysql.com/doc/mysql-installer/en/mysql-installer-gui.html
Tomcat uses defaults, but disables them.

The problem we have is that JHipster being such a great tool we do a lot of prototyping and generate a lot of apps. Is not like mysql that you install 3 times/year :).
Most of them we deploy on AWS and for each we need to change the passwords in the front, and copy paste them to the liquibase files manually. A simple script will do it of course but I wonder if we are the only ones using jhipster in this way.

**Comment by Panthro** [comment]
If you use that much jhipster for new projects and it's a pain in the ass changing passwords, why don't you create a `bash script` that automatically replace your passwords in the jhipster newly generated app right after you create it?

I mean, it makes sense for your use case, but not for the rest of the world that will use jhipster once in a while. (I'm on my third project with jhipster this year and I don't think it's a pain in the ass, really)

**Comment by mihaisimi** [comment]
Ok, closing.
