### ISSUE TITLE
Sonar: Update this function so that its implementation is not identical to the one

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#25134]
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=jhipster-sample-application&open=AY1qKP60ZqAZOZp0Vj8n

![image](https://github.com/jhipster/generator-jhipster/assets/9989211/8497c327-7004-458b-9f82-549666a7f3f6)

@mshima you added directive `SortBySignalDirective` below `SortByDirective`, we kept two directives?

**Comment by mshima** [comment]
We should drop the former one.
I haven’t look into it yet.
I am trying to simplify entity code all over the place.
