### ISSUE TITLE
Neo4j dev database type needs Neo4j Harness just like how relational dev database types have h2

### ISSUE THREAD

**Issue by kevintanhongann** [jhipster/generator-jhipster#25147]
##### **Overview of the feature request**

Neo4j dev database type needs Neo4j Harness just like how relational dev database types have h2

##### **Motivation for or Use Case**

Because it should allow me to work on prototypes easier with dev environments without spinning of a database

##### **Related issues or PR**

N/A

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
I don't know the test harness but what is the issue with having testcontainers and docker? What would be the benefit using the harness (except it might be faster)?

**Comment by kevintanhongann** [comment]
It is faster to get things up and running to prototype quickly without spinning a docker instance. Correct me if I'm wrong. 
On the other hand, I really enjoyed what jhipster can do with neo4j since the AI hype has been picking up nowadays with graph databases.

**Comment by mshima** [comment]
I don't think we have any other database that could be used like this.
Actually it should be possible to use Neo4j https://neo4j.com/docs/java-reference/current/java-embedded.
Depending on the complexity we may accept PRs, but I think it should be closed since we prefer testcontainers for simplicity.

**Comment by mshima** [comment]
Embedded DB is more complex than testcontainers.
We should avoid more maintenance burden.
