### ISSUE TITLE
WebSocketMessageBrokerConfigurer not found

### ISSUE THREAD

**Issue by adnansenyurt** [jhipster/generator-jhipster#25150]
##### **Overview of the issue**

Application is generated with default JHipster parameters and webscoket option. Running it gives the following compilation error:

------------------------------

...

[INFO] Compiling 75 source files with javac [debug target 17] to target/classes
[INFO] /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketSecurityConfiguration.java: /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketSecurityConfiguration.java uses or overrides a deprecated API.
[INFO] /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketSecurityConfiguration.java: Recompile with -Xlint:deprecation for details.
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] system modules path not set in conjunction with -source 17
[WARNING] unknown enum constant javax.annotation.meta.When.MAYBE
  reason: class file for javax.annotation.meta.When not found
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketSecurityConfiguration.java:[10,8] cannot access org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurer
  class file for org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurer not found
[ERROR] /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketConfiguration.java:[9,49] package org.springframework.messaging.simp.config does not exist
[ERROR] /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketConfiguration.java:[12,38] package org.springframework.web.socket does not exist
[ERROR] /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketConfiguration.java:[14,45] package org.springframework.web.socket.server does not exist
[ERROR] /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketConfiguration.java:[15,53] package org.springframework.web.socket.server.support does not exist
[ERROR] /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketConfiguration.java:[20,48] cannot find symbol
  symbol: class WebSocketMessageBrokerConfigurer
[ERROR] /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketConfiguration.java:[19,2] cannot find symbol
  symbol: class EnableWebSocketMessageBroker
[ERROR] /Users/adnansenyurt/Projects/jh/trials/websockets/src/main/java/com/adnans/websockets/config/WebsocketConfiguration.java:[31,40] cannot find symbol
  symbol:   class MessageBrokerRegistry
  location: class com.adnans.websockets.config.WebsocketConfiguration

...

##### **Motivation for or Use Case**

I need a WebSockets client and server implementation

##### **Reproduce the error**

- Create a new JHipster application with WebSockets option selected
- compile it with ./mvnw

##### **JHipster Version(s)**

JHipster v8.1.0

##### **JHipster configuration**
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "websockets",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientTestFrameworks": [],
    "clientTheme": "none",
    "creationTimestamp": 1707463973650,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [],
    "feignClient": false,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.1.0",
    "jwtSecretKey": "MWRiZjY1NmVlNzJhNzM1MTM0YjgzZWQxYzM5Yjc5YWFhMjBlMDBjNmRhYmM0ZTQzZWI2YmRkZTcyNTA3M2Q0ZWY5ZGUxMGQ3OTZjZGUxY2M0ZjNlZDBmOGZlMTJmNGRmYThiYmZhYjVhNDU4NWMxZTU3MzY2NWI0MTAzNDkyMjg=",
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.adnans.websockets",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

##### **Browsers and Operating System**

MacOs, Chrome

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
Not reproduced on the main branch

**Comment by kevintanhongann** [comment]
![image](https://github.com/jhipster/generator-jhipster/assets/359537/30dd78d8-a52c-4014-8228-bbd8a5a0b7eb)

So I guess some of the websocket related stuff is already deprecated, might just need a rewrite.

**Comment by mshima** [comment]
The sample doesn’t even have websocket enabled: `"websocket": false,`
Closing.
