### ISSUE TITLE
Pagination as a field in Rest layer makes swagger-api fail

### ISSUE THREAD

**Issue by Panthro** [jhipster/generator-jhipster#2516]
### Steps to reproduce:

 - Add an entity with pagination (any).

### Expected result:
Valid swagger api-docs http://localhost:8080/#/docs (http://localhost:8080/v2/api-docs)

### Result: 
http://localhost:8080/#/docs (http://localhost:8080/v2/api-docs)
Represents an invalid swagger v2 api docs

has an invalid schema because `Pageable` is not a defined model.

### Why this is bad?
I was trying to generate a client using swagger-codegen and retrofit and got several errors before I figured out it was that.

### Possible solutions
Make swagger ignore the Pageable. As we're using the `HateoasPageableHandlerMethodArgumentResolver` and the pagination is on the links.

in __SwaggerConfiguration.java__ add `.ignoredParameterTypes(Pageable.class)`
or add `@ApiIgnore` to the Pageable parameter. (this is probably bad because will tie jhipster up with spring fox)

**Comment by cbornet** [comment]
would you make a PR for this ?

**Comment by Panthro** [comment]
#2519 done

**Comment by jdubois** [comment]
Closed as PR is merged ( @Panthro next time add a "fix" keyword in your PR, it will close the issue automatically)

**Comment by Panthro** [comment]
Ops sorry. Forgot to do it this time.
