### ISSUE TITLE
Social authentication with Google doesn't work when translation is disabled

### ISSUE THREAD

**Issue by titogeorgep** [jhipster/generator-jhipster#2518]
I have created a new application with "enableTranslation": false, Only google properties are added in applicaton.yml. On sign in I get the error in attached screen shot.  

![screenshot from 2015-12-22 20-16-49](https://cloud.githubusercontent.com/assets/11407285/11957722/6416b9ac-a8e9-11e5-9f8c-1cb8c747d670.png)

```
{
  "generator-jhipster": {
    "baseName": "y",
    "packageName": "com.titogeo.test",
    "packageFolder": "com/titogeo/test",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": false,
    "enableSocialSignIn": true,
    "rememberMeKey": "fb2b171f7741306ae007c05d63194597c661f178",
    "testFrameworks": [
      "gatling"
    ]
  }
}
```
I am using Chrome Version 47.0.2526.80 (64-bit) on Ubuntu 15.10

**Comment by titogeorgep** [comment]
I regenerated the application with ``` "enableTranslation": true ``` and it is working fine.

**Comment by jdubois** [comment]
I'm editing the title of your issue, as this is because your have translations not enabled.

**Comment by jdubois** [comment]
I can't reproduce your issue: I just created a new application with social login and enableTranslation: false, and the application.yml file has all 3 (Google, Facebook, Twitter) configurations.
As you don't give your JHipster version, I guess you are using an older version and this has now been fixed.

**Comment by sdoxsee** [comment]
I have the same issue.

* **Overview of the issue**
screenshot (same as above)
https://www.dropbox.com/s/g95o5hdveaxgx09/Screenshot%202015-12-28%2014.47.48.png?dl=0

I have only tried Google sign in with translation disabled. After I authorize access to my web app on the google consent screen, i get the error screen above.

```
2015-12-28 14:45:03.973 DEBUG 13303 --- [nio-8080-exec-6] c.m.myapp.aop.logging.LoggingAspect      : Enter: org.springframework.social.connect.UsersConnectionRepository.findUserIdsWithConnection() with argument[s] = [org.springframework.social.connect.support.OAuth2Connection@e5be2a4]
Hibernate: select socialuser0_.id as id1_4_, socialuser0_.access_token as access_t2_4_, socialuser0_.display_name as display_3_4_, socialuser0_.expire_time as expire_t4_4_, socialuser0_.image_url as image_ur5_4_, socialuser0_.profile_url as profile_6_4_, socialuser0_.provider_id as provider7_4_, socialuser0_.provider_user_id as provider8_4_, socialuser0_.rank as rank9_4_, socialuser0_.refresh_token as refresh10_4_, socialuser0_.secret as secret11_4_, socialuser0_.user_id as user_id12_4_ from jhi_social_user_connection socialuser0_ where socialuser0_.provider_id=? and socialuser0_.provider_user_id=?
2015-12-28 14:45:03.975 DEBUG 13303 --- [nio-8080-exec-6] c.m.myapp.aop.logging.LoggingAspect      : Exit: org.springframework.social.connect.UsersConnectionRepository.findUserIdsWithConnection() with result = []
```

* **Motivation for or Use Case** 

I'd like to use authentication via Google for my app.

* **JHipster Version(s)** 

Most recent 2.26.1

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "baseName": "lunch",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": false,
    "enableSocialSignIn": true,
    "testFrameworks": [
      "protractor"
    ]
  }
}
```

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

N/A

* **Browsers and Operating System** 

Chrome Version 47.0.2526.106 (64-bit), OSX (10.11.2)

* **Reproduce the error** 

   1. Generate app (yo jhipster)
   1. Configure app with Google (https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret)
   1. set new google client id and secret in application.yml
   1. start jhipster app with ```mvn```
   1. go to http://localhost:8080/#/login
   1. click 'sign in with google'
   1. click 'allow' on google's consent screen
   1. see the error in the screenshot

* **Related issues** 

No

* **Suggest a Fix** 

No suggestion at this time.

**Comment by moifort** [comment]
I have reproduced the error I will try to investigate! (Sherlock Holmes mode activated)

**Comment by titogeorgep** [comment]
Thank you all for a Quick fix!!
