### ISSUE TITLE
JUnit integration tests are too slow.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#25188]
##### **Overview of the issue**

JUnit integration tests are too slow.
Application context is restarted for every class test suit.
Our implementation doesn't allow context reuse.
- use of DirtiesContext
- use of Mock
- some context customizers

Backend test step in ng-default is taking ~5min. It can be reduced to 2min-3min.
The JUnit integration test duration can be reduce by at least 60%.

##### **Motivation for or Use Case**

Improve user experience for Tests.

##### **Suggest a Fix**

Cleanup tests context.

##### **JHipster Version(s)**

main

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by dwarakaprasad** [comment]
@mshima, I am willing to contribute to this issue and have been doing some reading,
[context-reload-sof](https://stackoverflow.com/questions/48929585/spring-boot-test-context-loaded-for-every-test)
[github issue related to this](https://github.com/spring-projects/spring-boot/issues/7174)

Based on [spring.io](https://docs.spring.io/spring-framework/reference/testing/testcontext-framework/ctx-management/caching.html), contexts are cached and re-used as long as context configuration remains unique. I am trying to figure out what this really means from jhipter's backend implementation.

Let me know if you like me to move forward, I see you have made some changes too...

**Comment by mshima** [comment]
@dwarakaprasad great.
I would say that https://github.com/jhipster/generator-jhipster/issues/21853 is the start point.
We use ContextCustomizerFactory which is not compatible with context reuse.

**Comment by dwarakaprasad** [comment]
> We use ContextCustomizerFactory which is not compatible with context reuse.

Yup exactly, was having some fun looking at spring docs and sprint-test context cache [implementation](https://github.com/spring-projects/spring-framework/blob/b1b9ee0ccf1d6eaaea9c8ba15aec1bc110143e20/spring-test/src/main/java/org/springframework/test/context/MergedContextConfiguration.java#L544). The lambda that is being returned from SqlTestContainersSpringContextCustomizerFactory seem to be throwing the hashcode which is causing the context recreation.

I am trying to replace the lambda with an object and see how the cache reacts...
Will keep you posted...

**Comment by mshima** [comment]
That's interesting, we should calculate the hashcode in customizers then.

**Comment by dwarakaprasad** [comment]
@mshima  ng-default with h2 dev has got about 20 - 30 faster. See [reference](https://github.com/dwarakaprasad/jhipster-uTest-optimize). Can drop the DirtiesContext from AuthenticationIntegrationTest.java as well.

For some reason your changes does not seem to show any loading optimization.

**Comment by dwarakaprasad** [comment]
> For some reason your changes does not seem to show any loading optimization

got it, the returned ContextCustomizer needs the overridden hashCode method, your impl seems to be adding it to the ContextCustomizerfactory rather. See my [reference impl](https://github.com/dwarakaprasad/jhipster-uTest-optimize/blob/main/src/test/java/com/mycompany/myapp/config/SqlTestContainersSpringContextCustomizerFactory.java).

**Comment by mshima** [comment]
With the ContextCustomizer hashCode in place the hash conflict is happing in ImportsContextCustomizer.
ImportsContextCustomizer is quite complex and hard to debug.
I've give up for now.

**Comment by mshima** [comment]
Maybe it's related on how the TestContainerCustomizer is implemented.

**Comment by dwarakaprasad** [comment]
> Maybe it's related on how the TestContainerCustomizer is implemented.

I was able to get the non-testContainer based test ("devDatabaseType": "h2Memory") to be loaded optimally ([see this](https://github.com/dwarakaprasad/jhipster-uTest-optimize)), but not for the one using testContainers. I am getting 'liquibase' bean creation error as the spring.dataSource.url seems to be going in as null from TestContainerCustomizer, i.e. the DatasourceProperties object in the LiquibaseConfiguration.java is empty and nothing from the Customizer is propagated.
