### ISSUE TITLE
Circular Reference error with MongoDb on CloudFoundry

### ISSUE THREAD

**Issue by gouravsood** [jhipster/generator-jhipster#2521]
Hi,

I am using Jhipster with mongodb as main database. Its running properly in localhost:8080. But when i deploy it to cloudfoundry, it crash with following exception: 

**Nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'mongoDbFactory': Requested bean is currently in creation: Is there an unresolvable circular reference?**

Resolution mentioned in https://github.com/jhipster/generator-jhipster/issues/1830 doesn't work. 

Please guide.

Thanks,
Gourav.

**Comment by jdubois** [comment]
- I'm editing the title of your issue as this only occurs on CloudFoundry
- MongoDB on CloudFoundry isn't supported, because of Mongeez (see the [documentation](http://jhipster.github.io/cloudfoundry.html)). Did you remove all references to Mongeez? Then maybe it's because of our Cloud connector

**Comment by jdubois** [comment]
I guess it's because of the cloud connector -> as this is not supported anyway, I'm closing this

**Comment by gouravsood** [comment]
Hi @jdubois Yes I have removed the all the references of Mongeez but still it was happening.

Finally to make it work instead of using the Paas service, I used Spring Cloud configs (application-cloud.yml) to load the connection details to MongoDB and connected to the Mongo DB service in cloud. That worked for me.

**Comment by jdubois** [comment]
Can you document this, or provide a PR? This question keeps coming back, and I'm sure many people would benefit from it.
Unfortunately it's quite complex to test, as you need a CloudFoundry + MongoDB instance.

**Comment by gouravsood** [comment]
Sure @jdubois. I will create a working sample app and share the code how I did solve it. I will also try to send a PR with changes.

**Comment by jdubois** [comment]
Thanks a lot!!

**Comment by gouravsood** [comment]
Hi @jdubois  and all,

I have written a sample application in below repo to explain how to work with Spring Boot (following JHipster approach) and connect to MongoDB in local and cloud (Cloud Foundry) database.

https://github.com/gouravsood/SpringBootMongoDBCloud 

I will plan to pick the PR on Jhipster Repo to fix it in code itself.

Hope this helps.

Happy new year to everyone :)

Thanks,
Gourav.

**Comment by jdubois** [comment]
Thanks a lot, and happy new year to you too!
