### ISSUE TITLE
Liquibase Neo4j as an alternative to Neo4j migration in Neo4j database flavor

### ISSUE THREAD

**Issue by kevintanhongann** [jhipster/generator-jhipster#25224]
##### **Overview of the feature request**

(https://neo4j.com/labs/liquibase/docs/quickstart/) The feature request is related to neo4j database migration, in which it has similarity with Liquibase relational database migration implementation for jHipster.  

##### **Motivation for or Use Case**

since jHipster or Spring Boot users might already have familiarized with Liquibase migration as a whole for relational database, technically even the existing gradle tasks for database migration can be emulated to suit this liquibase neo4j migration, in which the current neo4j-migrations implementation doesn't have any gradle commands yet. Would be good to standardize overall. 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
We have that already if I am not mistaken.

**Comment by mshima** [comment]
Entities changelog are not generated for neo4j due to this condition:
https://github.com/jhipster/generator-jhipster/blob/c532c70ca2fe3d78bf325232dd0a733177398d2d/generators/liquibase/generator.ts#L170

Entity changelogs are not required for neither migration technology.

**Comment by atomfrede** [comment]
For reference:

* https://github.com/jhipster/generator-jhipster/issues/16315
* https://github.com/jhipster/generator-jhipster/pull/17956
* https://github.com/jhipster/generator-jhipster/pull/21791
