### ISSUE TITLE
Why the GUI is not working properly?

### ISSUE THREAD

**Issue by ibgithub** [jhipster/generator-jhipster#2522]
Dear all
I ever create jhipster project and run well, but right now when I create again why the GUI is not good, there is no error I found, but the GUI is not good, the menu is not shown properly etc.

below is the screenshot of my application:
<a href="http://tinypic.com?ref=1zzkhlg" target="_blank"><img src="http://i64.tinypic.com/1zzkhlg.png" border="0" alt="jhipster gui"></a>

Best regards
Imam

**Comment by gmarziou** [comment]
Please follow [our guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) it should go to stackoverflow, this is very likely a CSS loading issue, check your browser console and follow up on stackoverflow.

**Comment by ibgithub** [comment]
After try 5 times, I already able to create the project, thank you for the answer.

**Comment by kavenr** [comment]
I had the same problem after starting a new project. You need to run the maven build before starting the project in Eclipse. If you go ahead and run the project in Eclipse right away, the css files aren't generated and you end up with this problem.
