### ISSUE TITLE
jHipster 8.1.0 JDL generated @OneToOne and @ManyToOne relationship was annotated with FetchType.LAZY, getting the attribute of the entity causes LazyInitializationException No Session

### ISSUE THREAD

**Issue by kevintanhongann** [jhipster/generator-jhipster#25241]
##### **Overview of the issue**

 JDL generated @OneToOne relationship was annotated with FetchType.LAZY, getting the attribute of the entity causes LazyInitializationException. Previously it wasn't like that in jHipster 7.9.+

##### **Reproduce the error**

```
application {
  config {
    baseName brokenDemo
    applicationType monolith
    authenticationType jwt
    databaseType sql
    devDatabaseType h2Disk
    prodDatabaseType postgresql
    clientFramework vue
    buildTool gradle
    testFrameworks [gatling,cypress]
  }
  entities *
}

entity Company {
  name String required
  slug String required
  description String required
  logoUrl String
  createdDate Instant required
  createdBy String
  lastModifiedDate Instant
  lastModifiedBy String
}

entity UserCompany {
  createdDate Instant required
  createdBy String
  lastModifiedDate Instant
  lastModifiedBy String
}


relationship OneToOne {
    UserCompany{user(login)} to User with builtInEntity
}


relationship ManyToOne {
    UserCompany{company(name)} to Company
}
```

##### **JHipster Version(s)**
8.1.0

Previously @OneToOne relationships were annotated as per normal in jHipster 7.9.3+ as far as I remember.

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationIndex": 0,
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "brokenDemo",
    "buildTool": "gradle",
    "clientFramework": "vue",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "entities": [
      "Company",
      "UserCompany"
    ],
    "jhipsterVersion": "8.1.0",
    "languages": [
      "en"
    ],
    "lastLiquibaseTimestamp": 1708265818000,
    "nativeLanguage": "en",
    "prodDatabaseType": "postgresql",
    "testFrameworks": [
      "gatling",
      "cypress"
    ]
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

git version 2.40.1

node: v18.19.0
npm: 10.2.3

Docker version 25.0.3, build 4debf41

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
@ChangelogDate("20240218141558")
entity Company {
  name String required
  slug String required
  description String required
  logoUrl String
  createdDate Instant required
  createdBy String
  lastModifiedDate Instant
  lastModifiedBy String
}
@ChangelogDate("20240218141658")
entity UserCompany {
  createdDate Instant required
  createdBy String
  lastModifiedDate Instant
  lastModifiedBy String
}
relationship OneToOne {
  UserCompany{user(login)} to User with builtInEntity
}
relationship ManyToOne {
  UserCompany{company(name)} to Company
}

search Company, UserCompany with no

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationIndex": 0,
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "brokenDemo",
    "buildTool": "gradle",
    "clientFramework": "vue",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "entities": [
      "Company",
      "UserCompany"
    ],
    "jhipsterVersion": "8.1.0",
    "languages": [
      "en"
    ],
    "lastLiquibaseTimestamp": 1708265818000,
    "nativeLanguage": "en",
    "prodDatabaseType": "postgresql",
    "testFrameworks": [
      "gatling",
      "cypress"
    ]
  }
}
</pre>
</details>


##### **Environment and Tools**

openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

git version 2.40.1

node: v18.19.0
npm: 10.2.3

Docker version 25.0.3, build 4debf41

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
@ChangelogDate("20240218141558")
entity Company {
  name String required
  slug String required
  description String required
  logoUrl String
  createdDate Instant required
  createdBy String
  lastModifiedDate Instant
  lastModifiedBy String
}
@ChangelogDate("20240218141658")
entity UserCompany {
  createdDate Instant required
  createdBy String
  lastModifiedDate Instant
  lastModifiedBy String
}
relationship OneToOne {
  UserCompany{user(login)} to User with builtInEntity
}
relationship ManyToOne {
  UserCompany{company(name)} to Company
}

search Company, UserCompany with no

</pre>
</details>
```

##### **Browsers and Operating System**

Ubuntu 23.10 and Firefox

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kevintanhongann** [comment]
![GGoB5pSa8AAruwD](https://github.com/jhipster/generator-jhipster/assets/359537/eaf96f1d-6438-499e-9688-9fa8b49b4f18)

make it make sense...

**Comment by mshima** [comment]
- hibernate 6 uses lazy fetch by default now.
- eager fetch at entity level can fetch much more data than required.
- we use `*WithEagerRelationships` apis for eager fetching. should be enabled by default.
