### ISSUE TITLE
Websockets admin/tracker generated example is broken in jHipster 8.1.0

### ISSUE THREAD

**Issue by kevintanhongann** [jhipster/generator-jhipster#25255]
##### **Overview of the issue**
Websockets admin/tracker generated example is broken in jHipster 8.1.0. It was working in jHipster 7.9.+.

##### **Reproduce the error**

Just generate an app with this config in 7.9.4 and 8.1.0, and compare. While opening the User Tracker application from the Admin menu, use Inspect and refresh the application. It works for 7.9.4, but not 8.1.0.

```
application {
  config {
    baseName documentManagement
    applicationType monolith
    authenticationType jwt
    databaseType sql
    devDatabaseType postgresql
    prodDatabaseType postgresql
    buildTool gradle
    websocket spring-websocket
    clientFramework vue
    testFrameworks [gatling,cypress]
  }
}
```

##### **JHipster Version(s)**
8.1.0

##### **Browsers and Operating System**

Ubuntu 23.10 and Firefox

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
I confirm the bug. The authenticated signal is not working as expected.

**Comment by mraible** [comment]
I see the following in my console with the main branch. 

<img width="509" alt="Screenshot 2024-03-20 at 9 39 38 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/e5ecba32-a70a-4518-adef-7406687aaf22">

What's the behavior you expect to see?

**Comment by kevintanhongann** [comment]
@mraible In the React variant, it will show no errors(the screenshot)or should I say the opposite of that, and as you navigate the admin panels, the logs of which pages you have navigated will show in the tracker page. 

So I will expect the behavior to work the same as that.

**Comment by mraible** [comment]
I can confirm that things work better with v7. I'll add a bug bounty in hopes of getting this fixed.
