### ISSUE TITLE
Spring mail authentication problem

### ISSUE THREAD

**Issue by brevleq** [jhipster/generator-jhipster#2526]
I really like jhipster, and I'm using it in three different projects, but...
I'm having some issues to send e-mail using Zoho and Gmail. The first problem is to set the STARTTLS flag, I've tried add `starttls: true` in application-dev.yml at `spring:mail` options without success. So I've decided to set it directly in MailService.
Then I got another problem: `javax.mail.AuthenticationFailedException` and loose a lot of time to realize that jhipster wasn't setting user and password to send email, again I set these properties in MailService:

     javaMailSender.setUsername(env.getProperty("spring.mail.user"));
     javaMailSender.setPassword(env.getProperty("spring.mail.password"));
     javaMailSender.getJavaMailProperties().put("mail.smtp.starttls.enable",true);

I don't know if this is a bug in spring mail or in jhipster, I only know that is annoying setting these properties twice.

**Comment by gmarziou** [comment]
According to the [spring-boot application properties doc](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html), 'spring.mail.properties.*' is for additional JavaMail session properties.

Have you tried this?

      spring.mail.properties.mail.smtp.starttls.enable: true

**Comment by pascalgrimaud** [comment]
@brevleq : there is a pull request (by @RawSanj) here https://github.com/jhipster/jhipster.github.io/pull/142/files

Can you try this ?

**Comment by brevleq** [comment]
Thanks, it worked
the problem was at property username, was user.
