### ISSUE TITLE
Eclipsestore Support

### ISSUE THREAD

**Issue by hu-chia** [jhipster/generator-jhipster#25310]
##### Overview of the issue

**Support to use [Eclipsestore](https://eclipsestore.io) to be persistence layer.**

Eclipsestore is an interesting idea to replace databases, in my opinion, It is very suitable as the persistence layer of DDD.

##### **Motivation for or Use Case**

I love the JDL, but unfortunately, It is designed to design a SQL model, and SQL is too heavy in many areas, I found that jhipster supports MongoDB, why not eclipsestore?

##### **Related issues or PR**

there is no related issues or PR.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Mostly eclipstore is quite new and imho serves a quite different purpose than the databases we support. It would be best to start this as a blueprint as the maintenance burden is quite huge and the core team can not handle it.

**Comment by hu-chia** [comment]
I'm trying to write a blueprint( overriding spring-mongodb ) to support eclipsestore, please do not close this issue, so that I can post the problems I'm having here.
