### ISSUE TITLE
Duplicated Hazelcast instances

### ISSUE THREAD

**Issue by veejayendraa** [jhipster/generator-jhipster#2531]
Hi.

I'm starting a new project with Jhipster, I am getting Duplicate Hazelcast instance exception while building the project and running auto generated test cases.

Its related to #1688 , but that issue was resolved in 2.18 and I m using 2.26.1

.yo-rc.json is as per below 

`{
  "generator-jhipster": {
    "baseName": "societyManagement",
    "packageName": "com.digiworld.society",
    "packageFolder": "com/digiworld/society",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": true,
    "rememberMeKey": "40aab3883c57abf8a90ad12066fc84e26540fb96",
    "testFrameworks": [
      "cucumber"
    ]
  }
}`

**Comment by pascalgrimaud** [comment]
If you remove Cucumber, it will work.
If you want to keep Cucumber, you have to use gradle instead of maven.

Duplicated : https://github.com/jhipster/generator-jhipster/issues/2502

**Comment by Infrag** [comment]
Shouldn't Jhipster generator disable Cucumber when I choose maven and vice versa?

**Comment by pascalgrimaud** [comment]
don't comment an old ticket
this issue has been resolved
