### ISSUE TITLE
jHipster and Instagram login

### ISSUE THREAD

**Issue by tayfunyasar** [jhipster/generator-jhipster#2533]
I'm trying to do Instagram Integration with jHipster. I saw twitter and facebook login auth but there is no instagram integration.

Will you include instagram login too? When?

**Comment by gmarziou** [comment]
JHipster provides what Spring-social provides, you should have a look at spring-social add-ons, ther'es a community project https://github.com/mattupstate/spring-social-instagram though it seems rather old

**Comment by jdubois** [comment]
Yes we can't do more than what Spring Social provides: you need to ask this (or contribute!) to Spring Social to have more options

**Comment by pascalgrimaud** [comment]
@tayfunyasar : look at this PR https://github.com/jhipster/jhipster.github.io/pull/144
