### ISSUE TITLE
Custom columns names with @fieldNameAsDatabaseColumn(colum_name) in JDL

### ISSUE THREAD

**Issue by jperezdelafuente** [jhipster/generator-jhipster#25348]
##### **Overview of the feature request**

Related to: https://github.com/jhipster/generator-jhipster/issues/15297

@fieldNameAsDatabaseColumn(colum_name) works well with Jhipster 8.1 to custom column names
But I don't know if this is still an internal feature or could be used since Jhipster 7.2
It is not documented in: https://www.jhipster.tech/jdl/entities-fields
I think this feature for allow custom column names is very interesting and should be documented

##### **Motivation for or Use Case**

- You have to 'connect' the new application to an existing database, you cannot align sql column name with java entities field names (usualy sql naming conventions give eyespain).

- You have to respect a java naming convention + a corportate/DBAs SQL naming convention.

##### **Related issues or PR**

Related to: https://github.com/jhipster/generator-jhipster/issues/15297

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
PR is welcome.

**Comment by jperezdelafuente** [comment]
In June 2023 there was already doubt about the current status of this feature:
- https://github.com/jhipster/generator-jhipster/issues/15297#issuecomment-1590943851

I don't know if this is still an internal feature or could be used since Jhipster 7.2
although it works it is not documented in: https://www.jhipster.tech/jdl/entities-fields
Perhaps because it is something internal, which could change suddenly in the future.

**Comment by OmarHawk** [comment]
> In June 2023 there was already doubt about the current status of this feature:
> 
> * [jdl : specify sql column name for any field #15297 (comment)](https://github.com/jhipster/generator-jhipster/issues/15297#issuecomment-1590943851)
> 
> I don't know if this is still an internal feature or could be used since Jhipster 7.2 although it works it is not documented in: https://www.jhipster.tech/jdl/entities-fields Perhaps because it is something internal, which could change suddenly in the future.

I guess, the PR that @mshima mentions is for making this a non-internal feature (by adding some additional test + enhancing the documentation.) ;-)

**Comment by mshima** [comment]
It’s internal and feature.
Almost every entity aspect is customizable.
https://github.com/jhipster/generator-jhipster/blob/main/generators/app/README.md#customizing

Could be added here
https://github.com/jhipster/generator-jhipster/blob/main/generators/app/README.md#fields

**Comment by mshima** [comment]
Those properties should be stable for v8 cycle.

**Comment by mshima** [comment]
PR is welcome to add documentation about this property.
Closing as it’s a minor customization.
