### ISSUE TITLE
Time not editable for ZonedDateTime and date selector is on a separate line

### ISSUE THREAD

**Issue by hirro** [jhipster/generator-jhipster#2537]
**Overview of the issue**

I created a new project using 2.26.1 and found that edit control for ZonedDateTime only is a date selector (I couldn't enter any time at all due to validation errors. Also, the button for the date selector wrapped which doesn't look that good.

![screen shot 2015-12-28 at 00 42 47](https://cloud.githubusercontent.com/assets/4715022/12012579/02f64dba-acfc-11e5-9e48-6370c14ef246.png)

![screen shot 2015-12-28 at 01 28 35](https://cloud.githubusercontent.com/assets/4715022/12012709/5fe5cdba-ad02-11e5-80d4-d25c72dace7b.png)

**Motivation for or Use Case** 

* I can't edit time for type ZonedDateTime using default control.
* I can't edit time for type ZonedDateTime manually due to validation issues.
* Date selector is wrapped which doesn't look ok.

**JHipster Version(s)** 

2.26.1

**JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

[yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/72864/yo-rc.json.txt)

**Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

[TimeEntry.json.txt](https://github.com/jhipster/generator-jhipster/files/72865/TimeEntry.json.txt)

**Browsers and Operating System** 

Chrome 48.0.2564.48 beta (64-bit, OSX)

**Reproduce the error** 

Generate a project with above entity.

**Related issues** 

Didn't find any.

**Suggest a Fix** 

I looked at the code and thought a date-time time picker from angular-bootstrap should be used. Then remembered they don't have one, only separate date and time pickers. In my own project I used angular-bootstrap-datetimepicker.

How would you like to solve it? 

1. angular-bootstrap-datetimepicker (or any other angular all-in-one control)
3. angular-bootstrap datepicker + manual time edit
3. Manual entry
4. angular-bootstrap datepicker + angular-bootstrap timepicker

I can make a PR  for it once I get a go-ahead (unless you prefer using alternative 4 (angular-bootstrap timepicker) which I personally find visually unappealing mainly because it using too much vertical space)

**Comment by jdubois** [comment]
- Yes, I fully agree with this issue, in fact I have the same one!
- I would like to avoid adding too many third-party libs, as everyone will get them (and probably very few people will use that feature). So I would either do it manually (3) or with the timepicker (4). With the timepicker, isn't there a way to make it look better, next to the datepicker? I haven't looked at it in detail.

**Comment by hirro** [comment]
Would it be possible to only include the dependencies angular-bootstrap-datetimepicker and moment iff ZonedDateTime type is used? 

I am currently in the middle of trying out angular-bootstrap-datetimepicker, the component looks ideal for editing ZonedDateTime and it has support for localization through moment (http://momentjs.com/) .

**Comment by geraldhumphries** [comment]
The issue with the styling is probably happening because the input and button are not wrapped in `div.input-group`.

**Comment by hirro** [comment]
Yes, that it correct, input-group is missing. I am soon publishing a PR (hours) that solves the above issues, however with a dependency on angular-bootstrap-datetimepicker and moment. But it looks very nice, please see what you think.

**Comment by deepu105** [comment]
I have used a custome directive to wrap angular-ui date picker and timepicker together and and looks alright, i wouldn't want to add another dependency just for zoned date time, else we should look at using another standard calender/time lib for all date and time fields for consistency

**Comment by hirro** [comment]
Combining the date picker and the timepicker works, but unless you were able to get rid of those up and down toggles it takes too much vertical space. Do you have the possibility to show how it looks like using your  custom directive, screenshot maybe? The specialised date time picker control (angular-bootstrap-datetimepicke) looks very good, well that is my opinion.

Which calender/time lib is currently used by the way?

Is the directive available by any chance or could it be made available? The current status is that ZoneDateTime does not work in the UI.

**Comment by hirro** [comment]
Do you want me to strip this down to manual time entry (plain text input)? 
This would fix the following:
* The wrapping issues will be fixed for both Date and DateTime.
* It is possible to enter data for ZonedDateTime in the edit/new form.

I don't know how the module system works, but is it feasible to implement my PR as a module?

**Comment by deepu105** [comment]
Yes it should be possible, you can use cheerio to amend the generated html,
even better you can do a post entity hook, ill write some documentation
about that soon, check the entity-audit module for sample and bootswatch
module for cheerio sample

**Comment by hirro** [comment]
Ok, I'll reduce the original PR into a fix for:
* The wrapping issues will be fixed for both Date and DateTime.
* It is possible to enter data for ZonedDateTime in the edit/new form.

And later on (might take some time), a module for changing the default input to a custom date-time control. Thanks for the pointers Deepu!

If it sounds ok for you in the developer team; then I proceed with the reduced PR!

**Comment by deepu105** [comment]
Plz proceed to reduce it will solve an issue anyway

**Comment by cbornet** [comment]
@hirro Are you working on this ?

**Comment by hirro** [comment]
@cbornet I am finishing working on #2387 before I will start. For me it is working since I am using the code from the PR that fixed this (they did not want to add dependency to another JS module). If you need a quick fix look at what I did in my jhipster branch.

If you want to fix it feel free to do so, besides my proposed fix replaces the datetime control with a simple edit. It is not the most user friendly approach, but ideally (if we don't add new dependencies) maybe write a directive that combines Bootrstrap's date and time controls.

**Comment by deepu105** [comment]
is this fixed with https://github.com/jhipster/generator-jhipster/pull/2786

**Comment by mraible** [comment]
Yes, I fixed this with #2786.
