### ISSUE TITLE
Integration test not reliable with UUID as primary key 

### ISSUE THREAD

**Issue by emilpaw** [jhipster/generator-jhipster#25387]
##### **Overview of the issue**

While working on https://github.com/jhipster/generator-jhipster-quarkus/issues/220 I noticed that JHipster generates tests as such:

```java
    @Test
    @Transactional
    void getAllMyEntityAS() throws Exception {
        // Initialize the database
        myEntityARepository.saveAndFlush(myEntityA);

        // Get all the myEntityAList
        restMyEntityAMockMvc
            .perform(get(ENTITY_API_URL + "?sort=id,desc"))
            .andExpect(status().isOk())
            .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
            .andExpect(jsonPath("$.[*].id").value(hasItem(myEntityA.getId().intValue())))
            .andExpect(jsonPath("$.[*].fieldName").value(hasItem(DEFAULT_FIELD_NAME)));
    }
```
I assume that `?sort=id,desc` was used so that in the case of pagination, it can be assured that the newly created entity will be in the returned page. This works for the default `Long` IDs because they are auto incremented and as such sortable, but this does not hold true for UUIDs. So, in the case UUID is selected as the ID type, the newly created entity could possibly not be in the returned page and the test would fail. 

##### **Motivation for or Use Case**

The tests should work reliably regardless of the chosen options.

##### **Reproduce the error**

Use an entity with UUID as the type. e.g.

```
entity MyEntityA {
    id UUID
}
```

##### **Related issues**

https://github.com/jhipster/generator-jhipster/pull/13258

##### **Suggest a Fix**

  
I'm happy to help with working on the solution, but I am not sure what a good way to solve this is.

Loading all the entities by iterating over the pages could work, but this would introduce a lot of code.

##### **JHipster Version(s)**

v8.1.0

##### **JHipster configuration**

<details>
<summary>JDL entity definitions</summary>

<pre>
@ChangelogDate("20240301122015")
entity MyEntityA {
  id UUID
}

paginate MyEntityA with pagination
search MyEntityA with no

</pre>
</details>

**Comment by mshima** [comment]
Still applies on main?
Tests were reworked due to Authority entity that have String id.

**Comment by mshima** [comment]
That part of tests were not touched since it looks for the value at every record.
The changed tests assumed the last record are the last inserted.

**Comment by mshima** [comment]
I think the test doesn’t need to test specific values.
Need to test fields content type like optional/required, number/string and pattern.
