### ISSUE TITLE
Issue with dates,two types not supported

### ISSUE THREAD

**Issue by wadael** [jhipster/generator-jhipster#2539]
I had a set of java entities, used VP to turn them to uml, processed the result through jhipster-uml

See http://stackoverflow.com/questions/34497037/date-types-not-supported

(and please create a jhipster-uml tag)

**Comment by MathieuAA** [comment]
Hi again. You should post this issue on the JHipster-UML's "issue tracker", not on the main project's. If I am not mistaken, your problem isn't with the generator (your stack trace speaks for itself by the way).
Feel free to close this one, I'll take care of answering you when you open an issue on the JHipster-UML project page.
