### ISSUE TITLE
Using Entity.id only on equals() lead to unexpected behavior when id = null

### ISSUE THREAD

**Issue by Panthro** [jhipster/generator-jhipster#2543]
### SImple scenario:

when you have 2 entities with a OneToMany relationship and want to use the parent list to maintain the relationship using `CascadeType.ALL` (or persist, or update)

- [ ] Create the Father of the relationship
- [ ] Create 2 new childs of the same type and add them to the parent list.
- [ ] using `CascadeType.PERSIST` on the relationship call `repository.save()`

### Expected result

2 childs added to the database

### Actual result:
only the second child is added, as equals using id returned true when both were `null`.

### How to fix?

something like:
````
 @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        if (id == null || other.id == null) {
            return Objects.equals(field, other.field) && Objects.equals(anotherField, other.anotherField) && Objects.equals(yetAnother, other.yetAnother);
        }
        return Objects.equals(id, buildRequest.id);
    }
```

**Comment by jdubois** [comment]
Agreed, and this is more a "best practice with Hibernate" than an actual issue with JHipster.
Your solution would work, as long as comparing all fields is a correct way to check that both entities are "equals" (a common use case, of course).
You could also do a save() on each entity first, to force them to be created, and hence they would have an id -> not really an optimal solution in terms of code, but at least it would work on all cases, and without generating a complex "equals" method. Anyway, I'm not sure we could generate this scenario easily.
I need to check a few things to be sure this is the best solution, so as far as I'm concerned I will not code this in the near future, unless we have some good documentation/example code -> I'm sure the Hibernate team has something on this, if anyone has any pointer, I'd be happy to have a link.

**Comment by gzsombor** [comment]
If you remove the generated equals and hashCode method, you would get a more consistent behaviour - it's not 100% correct but it's a better default,than the current one (which is known to not following the general, expected contract of hashCode/equals methods)

**Comment by geraldhumphries** [comment]
Autogenerated equals and hashCode in IntelliJ with the default settings look like this (selected all fields, accepted subclasses as parameters, did not use getters/setters, did not make any fields not-null):
```
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Address)) return false;

        Address address = (Address) o;

        if (id != null ? !id.equals(address.id) : address.id != null) return false;
        if (streetLine1 != null ? !streetLine1.equals(address.streetLine1) : address.streetLine1 != null) return false;
        if (streetLine2 != null ? !streetLine2.equals(address.streetLine2) : address.streetLine2 != null) return false;
        if (city != null ? !city.equals(address.city) : address.city != null) return false;
        if (provinceState != null ? !provinceState.equals(address.provinceState) : address.provinceState != null)
            return false;
        return postalCode != null ? postalCode.equals(address.postalCode) : address.postalCode == null;

    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (streetLine1 != null ? streetLine1.hashCode() : 0);
        result = 31 * result + (streetLine2 != null ? streetLine2.hashCode() : 0);
        result = 31 * result + (city != null ? city.hashCode() : 0);
        result = 31 * result + (provinceState != null ? provinceState.hashCode() : 0);
        result = 31 * result + (postalCode != null ? postalCode.hashCode() : 0);
        return result;
    }
```

It seems pretty robust and easy to implement in a generator, maybe we should follow its example?

**Comment by gmarziou** [comment]
Hibernate team's position is that you should better use a business key than a generated key for implementing equalsd/hashCode. See [Hibernate doc](https://docs.jboss.org/hibernate/stable/core.old/reference/en/html/persistent-classes-equalshashcode.html).

Of course, JHipster cannot really know how to build a business key from your entity fields, it could try to guess one by looking at unique constraints but I think that would be fragile.

Problem is that some JHipsters users may take for granted that generated equals/hashCode methods will always work until they fall in some cases where they don't. In the case of @Panthro, it was the use of Cascade which JHipster does not use.

I think a good PR for this issue could include:

- a more robust implementation of equals/hashCode either copies what IntelliJ does or use one from a library like Apache commons-lang  [EqualsBuilder](http://commons.apache.org/proper/commons-lang/javadocs/api-2.5/org/apache/commons/lang/builder/EqualsBuilder.html) and [HashCodeBuilder](http://commons.apache.org/proper/commons-lang/javadocs/api-2.5/org/apache/commons/lang/builder/HashCodeBuilder.html)
- some warning in documentation and in method comments with a link to [Hibernate doc](https://docs.jboss.org/hibernate/stable/core.old/reference/en/html/persistent-classes-equalshashcode.html)
- some unit tests generated per entity that cover few use cases like adding entities to Set collection and reattaching detached instances. This way when developer changes entity, unit test may guide him/her.

**Comment by jdubois** [comment]
@gmarziou yes this is the part I need to check, as originally our equals/hashcode is supposed to be the one generated by Idea... At least that was the case 2 years ago, but so many things have changed since that time!
I am strongly against the commons-lang approach: I have seen several projects where we had a big performance hit (as much as 30%) because of those (as far as I remember it is because they use a lot of reflection)

**Comment by gmarziou** [comment]
Wow 30%, good to know.

**Comment by DanielSBFranco** [comment]
You could store System.nanoTime() in a javax.persistence.Transient field and use this field on equals() and hashcode() only when ID is null.

**Comment by Panthro** [comment]
I'm against commons lang approach too. AFAIK it uses reflection, and in cases you have some complex cases it makes a simple `list.add()` takes a really nice performance hit.

@jdubois The problem with the __save your entity to get an id__ approach is that in my case, the child entity will fail as the father relationship is required, and as a business requirement I should not save the parent until it is 100% OK (there are time based jobs that look for new data in the database).

+1 for the intellij generated one. :+1: 

__my how to fix__ was a fast suggestion :disappointed:

**Comment by gzsombor** [comment]
Including all the fields of an entity class for equality comparison is more broken - because they are entities, and not value classes - than the current equals method, which is using the id field. 
 If I were you, I would just remove that equals, and hashCode method, as the default java equals method would work perfectly fine. And I argue, that would be the correct behaviour : because two different instances from an entity class, never ever could be equals to each other : 
 - two entity without id - they are just two different, new instances
 - two entity with id's - they couldn't be the same, because they have different id. Why? Because the rule is that in one hibernate/jpa session, you shouldn't have two instance with the same persistent identity.

**Comment by geraldhumphries** [comment]
@gzsomber Agreed, comparing across all fields is definitely not correct. It is impossible to generate equals and hashCode using business keys without asking the user, and I would rather have no implementation than an incorrect implementation - but I am not an expert.

If we keep the methods, the current implementation is not the best, but returning false if either object's id is null will make it a little better and match the behavior you outline. That doesn't fix hashCode however. Letting the user define business keys and defaulting to either no implementation or the id would be nice.

**Comment by jdubois** [comment]
Oh yes @gzsombor you are totally right.
Le 31 déc. 2015 2:11 AM, "Gerald Humphries" <notifications@github.com> a
écrit :
