### ISSUE TITLE
Entity names are not capitalized in the Entities dropdown menu

### ISSUE THREAD

**Issue by roblight** [jhipster/generator-jhipster#2544]
Tested with the 2.26.1 release.

**Comment by geraldhumphries** [comment]
Reproduced in https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/webapp/scripts/components/navbar/navbar.html

**Comment by Panthro** [comment]
:+1:

**Comment by jdubois** [comment]
OK, this is in the navigation bar, for the non-i18n text (so it's not visible with Angular Translate).
Very minor issue.

**Comment by deepu105** [comment]
I guess we can put in a camelToHuman filter here as default @jdubois do you
want me to do a PR?

**Comment by jdubois** [comment]
Yes please do!
Le 2 janv. 2016 1:58 PM, "Deepu k Sasidharan" <notifications@github.com> a
écrit :

**Comment by roblight** [comment]
Just wanted to say "thanks" for the quick response!!  :thumbsup:  :smile:
