### ISSUE TITLE
Oracle: liquibaseDiffChangelog gradle task enhancement request

### ISSUE THREAD

**Issue by mhavrlent** [jhipster/generator-jhipster#2546]
In order to use Gradle `liquibaseDiffChangelog` task with Oracle DB I had to do the following changes:
1) Fill in the DB details to the task args in `liquibase.gradle` file. Example:
<pre>
`args "--referenceUrl=hibernate:spring:com.hpe.l4.generator.domain?dialect=org.hibernate.dialect.Oracle10gDialect"
  args "--username=SCHEMA_NAME"
  args "--password=somepass"
  args "--url=jdbc:oracle:thin:@localhost:1521:ORADB"
  args "--driver=oracle.jdbc.OracleDriver"`
</pre>
I couldn't find any documentation on the website regarding this. `Options -> Using Oracle` would be probably the best location. Also I was expecting this task to read the DB details from application.yml file automatically. I think jhipster is already doing this somehow on the new entity creation as there is a new liquibase changelog for each new entity.

This probably applies also to other DBs , not just Oracle DB.

Thanks.

**Comment by geraldhumphries** [comment]
+1

**Comment by atomfrede** [comment]
Do we have the same issue with maven? Nowhere is any statement about oracle.

**Comment by pascalgrimaud** [comment]
maven : https://github.com/jhipster/generator-jhipster/blob/master/app/templates/_pom.xml#L781-L798
gradle : https://github.com/jhipster/generator-jhipster/blob/master/app/templates/_liquibase.gradle#L16-L22

The information for Oracle is not generated, that's explain your issue => PR is welcome
But it works for mysql, postgresql and h2disk.

**Comment by mipas1** [comment]
I've created a PR. Some properties cannot be set directly such as `username` or `password`, but I guess the `driver`, `dialect` and `url` will help users to configure it faster. As of the documentation, I found some info the `Development` page: `If you use Gradle instead of Maven, you can use the same workflow by running ./gradlew liquibaseDiffChangelog, and change the database configuration in liquibase.gradle if required.`, but how about some new Liquibase page where is all the information or perhaps a link from the Oracle page? Can I do a PR for documentation?

**Comment by atomfrede** [comment]
You are right username and password are left blank. The user must enter it. 

If you like you can also open pull request against our documentation repository.

**Comment by deepu105** [comment]
Guys it two different things, as far as I know the maven and gradle task
for liquibase canot read from application yml files, so these have to be
manually changed anyway for all DB

**Comment by deepu105** [comment]
Ok you need to fill just username and password remaining can be generated,
so PR welcome else ill do it when i find time

**Comment by jdubois** [comment]
Yes this is documented at http://jhipster.github.io/development.html
This should work also with Oracle, and I would be very grateful if someone could send a PR with Oracle support.
The only reason why it's not supported yet is that this is a proprietary database, and I don't have a license: so quite obviously I can't work on this or test this.

**Comment by mhavrlent** [comment]
Actually I already sent a PR for this...

**Comment by jdubois** [comment]
Oh sorry, I'm checking this now

**Comment by jdubois** [comment]
This is merged -> can you also do a PR in the documentation ?

**Comment by mhavrlent** [comment]
Btw. you can work with Oracle Enterprise without the license if it's for development (one person/one server). Until you use it in production you don't have to pay the license.
More info here: http://it.toolbox.com/blogs/oracle-guide/does-oracle-require-a-license-for-a-development-database-26422

**Comment by jdubois** [comment]
Yes but they don't have a Mac OSX version... And on Linux it's a pain to install.

**Comment by pascalgrimaud** [comment]
Interesting @mhavrlent. Do you know if there is an official Docker image? I don't see one in Docker Hub...

**Comment by mhavrlent** [comment]
@jdubois  Regarding the documentation PR I would do the following: 
1/ Create a link from `Options -> Using Oracle` page to the `Development` page section where the liquibase udpates are mentioned. 
2/ Update `Development` page with the following:
* Create `Database updates with the Gradle` section.
* Highlight that one needs to update liquibase.gradle with username and password before running the diff task.

Do you agree on this?

@pascalgrimaud  I'm afraid that won't be possible since you need to download Oracle installation files from Oracle site and agree on the license terms. That's why there is no full automatic DB installation using Chef, Docker or whatever. One needs to download it first, then run scripts on top of it...
See some attempts here: https://github.com/wscherphof/oracle-12c

**Comment by jdubois** [comment]
Yes, totally agree

**Comment by jdubois** [comment]
I'm closing this as the PR is merged, @mhavrlent of course another PR for the documentation is most welcome!!!
