### ISSUE TITLE
Deprecated Libraries Upgrading Needed

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#25472]
##### **Overview of the issue**

After the initial project build with the command "jhipster", five messages in regarding deprecated libraries show up as the following.
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated vue@2.7.16: Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.
```
Some of those libraries shall not take too much effort to upgrade.

Vue likely takes some effort to upgrade. Vue 3 was released on September 18, 2020. It is time to get it upgraded.

   
##### **Motivation for or Use Case**

A new project shall use all updated libraries if possible.

##### **JHipster Version(s)**

8.1.0

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
> Some of those libraries shall not take too much effort to upgrade.

Looks ok to me.
I will review the PR.

**Comment by vw98075** [comment]
It likely needs another ticket for Vue. It won't be reasonable to create a new project with EOL components. The JHipster team needs to decide whether Jhipster will continue to have Vue as one of its front-end framework options or not. If yes, Vue needs to be upgraded to the Vue 3.

**Comment by mshima** [comment]
JHipster is already using Vue 3.
Vue 2 is a transitional dependency that some dependency depends on.
Closing as duplicated of https://github.com/jhipster/generator-jhipster/issues/23865.
