### ISSUE TITLE
[Module] Impossible to add a line in a file if another line is the same

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2550]
I am trying to add a line
```xml
<executable>true</executable>
```
by a module in pom.xml in the prod profile.
But as the line already exists in dev profile, the rewrite function in utils.js will not add it.
I can workaround this by adding a \n but it would be better to narrow the haystack to a portion of the file and not the full file.

**Comment by jdubois** [comment]
Can't you use a needle here? With a specific, unique name? That should do the trick.

**Comment by cbornet** [comment]
Yes that's the workaround I found. The true issue is the time I spent banging my head on the wall understanding why my initial needle was not added :smile: .

**Comment by jdubois** [comment]
OK I'm closing this as you need to use a needle for this.
