### ISSUE TITLE
Improve entity list UI

### ISSUE THREAD

**Issue by hirro** [jhipster/generator-jhipster#2552]
* **Overview of the issue**
There are some UI issues with the current entity lists I would like to discuss (also see #2267):
![jhipster_ 2552](https://cloud.githubusercontent.com/assets/4715022/12065466/1c5090ca-afd8-11e5-9cb6-057100a8dc63.png)

  * "Create new <Entity>" is left aligned but has some unnecessary left padding which makes it looks at bit unbalanced.
  * Is the text "Create new ..." required, couldn't it be replace with simply create? Alternatively removed and replace with a standard add icon (with an explanatory popover/hoover text)?
  * The search controls (search input and search button) are not right aligned, instead they seem more aligned to the middle. It does not look good together with the underlying table.
  * Is the entity title supposed to be on its own line? If so, why not make the search bar wider?
  * Can the search button be put in an input group and the text "Search a <Entity>" removed? It is should be obvious from the context if we use a standard search icon. Add a popover text with search help such as the search syntax.
  * The buttons "View", "Edit", and "Delete" could be put in a button group.
  * The button texts for "View", "Edit", and "Delete" could be removed and replaced with popovers.

* **Motivation for or Use Case** 
Make the UI look even better.

* **JHipster Version(s)** 
2.26.1

* **Browsers and Operating System** 
Chrome 48.0.2564.48 beta (64-bit, OSX)

**Comment by deepu105** [comment]
I guess @mraible had opened a same issue, plz check and close if its a
duplicate

**Comment by hirro** [comment]
They are not the same, but the is some overlapping with #2267. Most of my issues (besides the last two points which are overlapping) are related to layout and text outside the table.

**Comment by hirro** [comment]
I have submitted a PR for this, please try it out and see it is ok. 

It has been tested on the following browsers:
OSX: Chrome (latest), Firefox (latest), Safari (latest)
Windows 8: IE 11.0.9600

I have tested with the following generator alternatives:
* Use SCSS: both
* Elastic search: both

**Comment by deepu105** [comment]
Can you paste a screenshot of the new look so that people can take a quick
look

**Comment by hirro** [comment]
Sure! 

![screen shot 2016-01-05 at 18 46 37](https://cloud.githubusercontent.com/assets/4715022/12122658/b12304c8-b3dc-11e5-8bc2-dd1257abbe21.png)
![screen shot 2016-01-05 at 18 45 14](https://cloud.githubusercontent.com/assets/4715022/12122659/b12574f6-b3dc-11e5-9be8-7ac2e6d8aa4d.png)
![screen shot 2016-01-05 at 18 44 51](https://cloud.githubusercontent.com/assets/4715022/12122661/b1272ab2-b3dc-11e5-9c72-aa2ccdbcb443.png)
![screen shot 2016-01-05 at 18 44 00](https://cloud.githubusercontent.com/assets/4715022/12122662/b1292394-b3dc-11e5-92ea-7541c5e7cd01.png)
![screen shot 2016-01-05 at 18 43 33](https://cloud.githubusercontent.com/assets/4715022/12122660/b126575e-b3dc-11e5-8e73-bd090cf14996.png)

**Comment by deepu105** [comment]
I think the create button should have a + icon rather than lightning bolt

**Comment by deepu105** [comment]
There is one small issue in using the tooltip on the buttons, in mobile
touch screens when you touch the button first instead of triggering the
buttons action it will show a tooltip, you need to touch again to trigger
the action so its kind of annoying to a daily user. There is of course a
way to disable it but then in mobiles you wont have the tooltip

I would prefer not having tooltip rather then double tapping buttons

**Comment by hirro** [comment]
Yes, I also think the icon should be a plus. Look a bit more familiar to me.

**Comment by hirro** [comment]
Regarding the buttons: 

What about this?

No tooltips.
On large screens: Show text in buttons.
On small and medium screens: Hide text

This way screen space will be conserved for smaller screens/windows. Currently the edit/view/delete buttons take unproportional amount of horizontal space.

**Comment by deepu105** [comment]
+1

**Comment by moifort** [comment]
:+1:

**Comment by hirro** [comment]
PR is updated now with the following new behaviour:

View/Edit/Delete buttons:
* Text is visible on large+ screens, on smaller screens only the icon is visible.
* Tooltips are not used since there was a usability problem with those pointed out by Deepu.

Search button:
* Tooltip text is moved to the placeholder. This look much nicer.

Table data:
* Bootstrap uses "vertical-align: top" on td by default; to make the row look more balanced it was changed to  "vertical-align: middle" (but still "configurable" in the css). If you look at my previous screenshots, you see text is not in the middle of the row.
