### ISSUE TITLE
`009_tips_using_bootswatch_themes` html page missing {{theme.name}} binding in footer section

### ISSUE THREAD

**Issue by mhavrlent** [jhipster/generator-jhipster#2554]
It seems that the following markdown page `https://github.com/jhipster/jhipster.github.io/blob/master/tips/009_tips_using_bootswatch_themes.md` is not rendered correctly on jhipster site: `https://jhipster.github.io/tips/009_tips_using_bootswatch_themes.html`.

In md file there is a following text in a footer section: `<a href="" jh-switch-theme="theme">{{theme.name}}</a>`
On jhipster site, there is a following text in the footer section and the binding to the theme.name is missing: `<a href="" jh-switch-theme="theme"></a>`.

If there is no binding to the theme name, theme switcher is not very functional:
![capture](https://cloud.githubusercontent.com/assets/11587892/12070803/3bd23d56-b08a-11e5-8aaa-213edbb4fe14.PNG)

Maybe it's a github.io issue? How is the md content transformed to the html?

**Comment by jdubois** [comment]
This is done with Github markdown, by Github pages, I guess @deepu105 didn't test it with Github markdown -> @deepu105 I'm assigning this to you, as you authored the page

**Comment by deepu105** [comment]
@jdubois I usually test using markdown preview in atom and this one renders correctly, no idea whats wrong here anyway ill update it with syntax tags hope it works

anyway i need to convert this to a module

**Comment by pascalgrimaud** [comment]
The new "module" label is a good idea!

**Comment by jdubois** [comment]
OK I'm merging this we'll see the results! Sorry I only got my phone, I can't test.
