### ISSUE TITLE
JHipster 8 doesn't work with Java 22

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#25562]
##### **Overview of the issue**

JHipster 8 doesn't work with Java 22. If you're using Gradle, you get an error:

> BUG! exception in phase 'semantic analysis' in source unit 'precompiled_…' Unsupported class file major version 66

If you're using Maven, `CRLFLogConverterTest` doesn't pass.

<img width="1397" alt="Screenshot 2024-03-20 at 9 06 59 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/057591f0-95ec-4169-b419-cf7a08f3b147">

##### **Motivation for or Use Case**

We should support the latest release of Java.

##### **Reproduce the error**

```
sdk install java open-22
jhipster --defaults
```

##### **Suggest a Fix**

Upgrade to Gradle 8.7 and fix the test. 

##### **JHipster Version(s)**

8.2.0

**Comment by atomfrede** [comment]
Do we have already update to spring boot 3.2.4? The class file error comes from the gradle boot plugin which need to be updated to 3.2.4 for java 22 as far as I can tell.

**Comment by mshima** [comment]
> Do we have already update to spring boot 3.2.4? The class file error comes from the gradle boot plugin which need to be updated to 3.2.4 for java 22 as far as I can tell.
> 
> EDIT: nevermind, it should be 3.2.4 already 🤔

Test

**Comment by mshima** [comment]
> Do we have already update to spring boot 3.2.4? The class file error comes from the gradle boot plugin which need to be updated to 3.2.4 for java 22 as far as I can tell.
> 
> EDIT: nevermind, it should be 3.2.4 already 🤔

v8.2.1 was released with spring-boot 3.2.3.

**Comment by atomfrede** [comment]
On master we have 3.2.4 right? At least thats what I see in a generated application. Didn't check yet if that version is really used eventually.

**Comment by dwarakaprasad** [comment]
Seems like jhipster's reactive stack will have to wait until [byte-buddy](https://github.com/raphw/byte-buddy/issues/1609) && [BlockHound](https://github.com/reactor/BlockHound/issues/404) are resolved...
