### ISSUE TITLE
Missing Information for relationships "with joint fields" in the jhipster documentation.

### ISSUE THREAD

**Issue by rikshith** [jhipster/generator-jhipster#25584]
I have noticed that the JHipster documentation lacks sufficient information on defining relationships with joint fields between entities.  As relationships play a crucial role in developing complex data models within JHipster applications, it is essential to provide relative guidance on this topic.

Documentation Link - https://www.jhipster.tech/jdl/relationships#with-joint-fields.

I believe addressing this missing information in the documentation would improve the user experience and support developers in effectively leveraging JHipster's capabilities for building jHipster applications.

I am interested in contributing to resolving this issue and would be willing to assist in updating the documentation to include the coverage of relationships with joint fields.

**Comment by mraible** [comment]
Hello @rikshith! I'd be happy to review a PR with improved documentation.

**Comment by Lalithkumarponnambalam** [comment]
Hello @mraible I will create a PR for this documentation issue. Could you please review it?
