### ISSUE TITLE
[Feature request] option to have custom table name when creating entity

### ISSUE THREAD

**Issue by mhavrlent** [jhipster/generator-jhipster#2558]
Currently it's not possible to generate Entity with name that matches DB reserved word, such as `Database`, `Column` or `Table`. This restriction should be removed as there is no such restriction in JPA/Java world.
Instead we should ask user for a different table name. This new table name would be saved to the `entityTableName` generator field. 

Example:
* Entity name: Database 
* Table name: app_database  (or any other table name...)

That would generate code like this:
<pre>
@Entity
@Table(name = "app_database")
...
public class Database implements Serializable {
...
</pre>

Btw. is there any guide for building `generator-jhipster` project? I would propose a PR, just don't know how to build it :).

**Comment by deepu105** [comment]
what do you mean by building generator-jhipster project ? its a yeoman
generator you dont have to build it! if you are talking about building the
genrated application then check the documentation here
https://jhipster.github.io/production.html

**Comment by mhavrlent** [comment]
@deepu105 
I mean after you do the changes to the git project. Just `npm install` ?

**Comment by gmarziou** [comment]
You run npm link, see https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup

**Comment by mhavrlent** [comment]
thanks

**Comment by mhavrlent** [comment]
PR has been created. CI build in progress....
Can someone do a code review afterwards?

**Comment by atomfrede** [comment]
I'm not sure if this is only related to tables names. For example the entity can't be named document when using mongo db. Not sure if required, but maybe we need to know the table name when doing any updates to existing entities. So maybe this should be discussed further.

**Comment by mhavrlent** [comment]
It would have to be saved in the entity configuration json file for sure, so that we can read it on entity update...

**Comment by gmarziou** [comment]
I think it's a good thing to be able to name the table as you want even when not using a reserved keyword.

In my company, we have to follow some naming conventions like T_BNK_USER for table storing User entity of Bank feature.

In fact, I would prefer to be always asked for the table name as the default name never matches my requirements.

**Comment by atomfrede** [comment]
:+1: Good point :) For me the table name is mostly not relevant at all.

**Comment by mhavrlent** [comment]
@gmarziou 
Actually this is the same for me and it's the way I did the PR. It always asks for the table name.

If for some people the table name is not relevant at all, we could do a compromise here. Ask a question but predefine answer with the entity name. Similarly to relationship mapping, where field name is predefined to the name of the entity. How about that?

**Comment by gmarziou** [comment]
@mhavrlent this would work for me but I know @jdubois is sometimes reluctent to add new questions unless it's really required, so I'd like to get his feedback.

**Comment by jdubois** [comment]
This has already been discussed before:

- The table name is only written in the @Table annotation on the entities
- (OK, it can also be argued it's also written in the Liquibase changelog)

So this doesn't respect our Policy 2 at http://jhipster.github.io/policies.html

-> having a question for this is more complex than letting people change the @Table annotation. Besides, the annotation is generated exactly for this use case (as we could use the default table name instead)

**Comment by mhavrlent** [comment]
@jdubois 
I understand your point, but this is not actually about changing the @Table annotation. If i cannot use DB reserved word for my entity, I need to name my entity with different name. For example `Database` entity needs to be `AppDatabase`. If I want to refactor that to `Database` it's a lot of changes.

**Comment by mhavrlent** [comment]
Also, once my entity json config is named `AppDatabase` I cannot use the entity generator for that entity again as that would produce `AppDatabase` named files again and I would need to refactor those to `Database` again.

**Comment by jdubois** [comment]
Oh sorry, you got a point

**Comment by cbornet** [comment]
I think you can generate an entity with an "authorized" name and rename the entity json file afterwards.

**Comment by mhavrlent** [comment]
@cbornet 
You are correct. This works actually.

**Comment by gmarziou** [comment]
Changing the table name in @Table annotation is easy, the hardest part is to update the changelog if you want to update also foreign key names, index names, .... 

The naming conventions of my company are so exhaustive that I'm considering building a module to do so. I must admit that I don't even know if a module would be able to override default naming for tables and columns.

**Comment by deepu105** [comment]
@gmarziou i guess a regex replace would do from a module, look at my audit module where i modify entities

**Comment by deepu105** [comment]
@mhavrlent @jdubois instead of asking a question we can have it as an optional argument so `yo jhipster:entity foo` would work as today and return error when keywords are used while `yo jhipster:entity foo foo_table` would take the table name and proceed

**Comment by mhavrlent** [comment]
@deepu105
I'm ok with this.

**Comment by gmarziou** [comment]
@deepu105 I already use a regex but from a bash script and I'm not sure what would be the benefit doing the same in a module. What I'd like is having a hook in entityt generator so that I can "fix" the table and column names before generation.

**Comment by cbornet** [comment]
Maybe they could be optional fields in the json description. So, no question is asked, defaults to entity name but can be overridden.

**Comment by deepu105** [comment]
@gmarziou yes that would be ideal, I guess you can do something similar to
what i did for audit entity hook, but need to figure out how to make the
change persist on commit in yeoman, may be you can try with my jhipster
audit-hook branch and entity-audit module and see if you can figure out a
way

On Sun, Jan 3, 2016 at 10:28 PM, Christophe Bornet <notifications@github.com
> wrote:

> Maybe they could be optional fields in the json description. So, no
> question is asked, defaults to entity name but can be overridden.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/2558#issuecomment-168501473>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by deepu105** [comment]
@mhavrlent are you gonna work on the comments in PR? if not can we close this?

**Comment by mhavrlent** [comment]
@deepu105
Yes, I will try to do it this weekend.

**Comment by deepu105** [comment]
closed via #2842
