### ISSUE TITLE
Building the generator on plain Windows fails

### ISSUE THREAD

**Issue by OmarHawk** [jhipster/generator-jhipster#25598]
##### **Overview of the issue**
Building the generator on Windows runs into a failure. Running npm ci produces the following output:

```
> chmod +x dist/cli/jhipster.cjs || true

Der Befehl "chmod" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "true" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code 1
npm ERR! path C:\Users\jwedding\git\markant\generator-jhipster
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run build
```

##### **Related issues**
#25567

##### **Browsers and Operating System**

Windows 10
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
We need to chmod the binary in posix platform.
Any idea?

**Comment by OmarHawk** [comment]
Maybe something like this works: https://github.com/shelljs/shx . Haven't actually checked it out, but at least sounds like an option.
