### ISSUE TITLE
adminAuthority translation is deleted from global.json after importing jdl

### ISSUE THREAD

**Issue by cevheri** [jhipster/generator-jhipster#25608]
##### **Overview of the issue**

I tried to import standard JDL.
adminAuthority translation is deleted from global.json after importing jdl
![image](https://github.com/jhipster/generator-jhipster/assets/12383547/22122a89-51aa-44f2-9f2b-fe0a73713f9f)

---
![image](https://github.com/jhipster/generator-jhipster/assets/12383547/7d45944f-5b5b-4bc2-b3e6-4082da309bf4)

##### **Reproduce the error**

1. create jhipster:8.2.1 project
1. import default jhipster jdl

##### **JHipster Version(s)**

* JHipster version(s): 8.2.1

##### **JHipster configuration**

* JHipster version(s): 8.2.1
* Monolith
* Maven
* Java JDK:21
* PostgreSQL
* Angular
```json
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "j821",
    "buildTool": "maven",
    "cacheProvider": "hazelcast",
    "clientFramework": "angular",
    "clientTestFrameworks": ["cypress"],
    "clientTheme": "none",
    "creationTimestamp": 1711220283486,
    "cypressAudit": true,
    "cypressCoverage": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "devServerPort": 4200,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": ["Region", "Country", "Location", "Department", "Task", "Employee", "Job", "JobHistory"],
    "feignClient": null,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.2.1",
    "jwtSecretKey": "",
    "languages": ["en", "tr"],
    "lastLiquibaseTimestamp": 1711226203000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "syncUserWithIdp": null,
    "testFrameworks": ["cypress"],
    "websocket": false,
    "withAdminUi": true
  }
}
```

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by timothystone** [comment]
Let's open this back up. This is 100% reproducible. I was about to fix the problem with a PR when I stumbled on this issue. As shown in @cevheri OP, the translation is missing. @mshima points out that it could not be reproduced, but I was experiencing it. Something was creating the problem.

It's not in the core generator, but in the entity subgenerator.

## Reproduction

1. Generate a simple monolith. All standard (or use the below `.yo-rc.json`)
2. Add an entity, e.g., Book, via `jhipster entity Book`
3. One or more fields added
4. Overwrite all on completion
5. `global.menu.entities.adminAuthority` is clobbered (see following diff):

```diff
diff --git a/src/main/webapp/i18n/de/global.json b/src/main/webapp/i18n/de/global.json
index 69184285..04771b9b 100644
--- a/src/main/webapp/i18n/de/global.json
+++ b/src/main/webapp/i18n/de/global.json
@@ -8,7 +8,7 @@
       "entities": {
         "main": "Entitäten",
         "jhipster-needle-menu-add-entry": "JHipster will add additional entities here (do not translate!)",
-        "adminAuthority": "Authority"
+        "book": "Book"
       },
       "account": {
         "main": "Zugang",
```

So I poked around in the Needle API but couldn't untangle it in the Entity sub-generator or elsewhere.

**Update**

Pretty sure the Needles API is not actually used in this issue. It's a JSON Deep Merge. Which begs a different question about the Needle API and its lack of use, to the point of starvation sometimes.

The tests unfortunately don't validate that the previous, or expected, entries in the `global.menu.entities` are still there, like `adminAuthority`. 

(But more learning to do on some of those internals.)

<details>
<summary>`.yo-rc.json` prior to running Entity Sub-Generator</summary>
Running `jhipster entity Book` adds an element to the `"entities"` array, e.g., `["Book"]`. This is not shown. The `jwtSecretKey` is ephemeral and is only provided for completeness.
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "i18NJh",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientTestFrameworks": ["cypress"],
    "clientTheme": "none",
    "creationTimestamp": 1766939012907,
    "cypressAudit": true,
    "cypressCoverage": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableTranslation": true,
    "entities": [],
    "feignClient": null,
    "jhipsterVersion": "8.11.0",
    "jwtSecretKey": "NGFmOTA1MDA0YjgwNDg5NzZjZDIxYWZjMTJkMjY5YWMzMzI0MWQ4ZjBlYzNjNDllM2Y5ZDg0MDZkYjQwMDBjMzg4MDM4MDNiZWNhMmM4MGU1NzgwZTRiZDdhZWYyMGE0NDFkOWZlNWU0MmIxNTc5NTQzMjBkN2E3NWI4YTY2MzM=",
    "languages": ["en", "de"],
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "serverPort": null,
    "serviceDiscoveryType": null,
    "syncUserWithIdp": null,
    "testFrameworks": ["gatling", "cypress"],
    "withAdminUi": true
  }
}
</pre>
</details>

**Comment by timothystone** [comment]
Should I open an issue about the key hierarchy for the `adminAuthority` (and naming convention)? In my investigation I was puzzled by the placement of the key in `global.menu.entities`. I personally see this in the `global.menu.admin` hierarchy. The key also doesn't really follow established naming norms. `authorityManagement` like `userManagement` IMHO. A minor, inconsequential, critique, but aligned to existing keys and in the correct hierarchy.

## Update

This is more of a convenience I see as in [`generators/client/generators/i18n/generator.ts`](https://github.com/jhipster/generator-jhipster/blob/b29a25b68e206cc64a92fe77d44677eab4250854/generators/client/generators/i18n/generator.ts#L71-L92) the call to merge to the `global.menu.entities` is made... in the _Entity_ subgenerator.

**Comment by timothystone** [comment]
I can see the issue happening when the Entity subgenerator calls for i18n overwrite. It appears that this overwrite is pulling the `global.json` template and not performing a deep merge thus "deleting the key."

@cevheri you can skip the overwrite and "remember" (though I don't know what that does and is if not wholly, then poorly, documented). I'll experiment.* However, I think this can be generally fixed and i'm looking into what should be done to instead of calling for an overwrite, but perform a deep merge. May be possible... 🤞 

\* `i` or `remember` during entity generation just adds the file to the `.yo-resolve` file in the root of the project. A helpful reminder, but doesn't do anything.

The _immediate workaround_ is to review the `global.json` file for the changes as a matter of discipline.

**Comment by timothystone** [comment]
I think I narrowed it down to the `if/else` in [`generators/client/generator/i18n/generator.ts`](https://github.com/jhipster/generator-jhipster/blob/b29a25b68e206cc64a92fe77d44677eab4250854/generators/client/generators/i18n/generator.ts#L213C24-L213C45). As adminAuthority is a "builtin entity" I believe this needs to be handled differently. I believe more and more that what is happening is the builtin is not handled and thus not looped over and thus the file is clobbered by the entity loop on import or on executing the Entity subgenerator.
