### ISSUE TITLE
Home page doesn't have login-in menu and  got error page info when click logout herf in oauth2 application with Vue client (v8.2.1)

### ISSUE THREAD

**Issue by yuzhicloudbilly** [jhipster/generator-jhipster#25603]
##### **Overview of the issue**

After completing the automatic generation of code in oauth2 mode with Monolithic.

##### **Reproduce the error**

Just run application will get the erro when open localhost:8080.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I'm able to reproduce this issue with the following steps:

```
jhipster jdl blog-oauth2 --client-framework vue
```

Here's what the homepage looks like:

<img width="1167" alt="Screenshot 2024-03-22 at 9 32 46 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/43ec729a-1a16-4e81-ab55-b0d0caf5b25c">

Everything works fine with Angular.

<img width="1149" alt="Screenshot 2024-03-22 at 9 20 07 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/a0fa830f-cc0e-4550-adb7-bfa61039c5d9">
<img width="1149" alt="Screenshot 2024-03-22 at 9 20 11 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/fe8c2eb6-5e7e-4e9b-9540-d7d2c8f7ba34">
<img width="1149" alt="Screenshot 2024-03-22 at 9 20 16 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/3b2b4557-fa1c-40e2-81c8-87554e7dcd37">

**Comment by yuzhicloudbilly** [comment]
resolved. thanks.
