### ISSUE TITLE
Evaluate `insight` dependency.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#25634]
##### **Overview of the issue**

`insight` is outdated and brings security issues to source tree.

We should evaluate:
- update `insight` package to esm and fix security issues (package is from yeoman organization, I probably can commit and release).
- drop `insight` package and google statics.
- find some alternative.

##### **Motivation for or Use Case**

Don't show warnings at npm install.

##### **Reproduce the error**

```
% npm audit
# npm audit report

request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
Depends on vulnerable versions of tough-cookie
No fix available
node_modules/request
  insight  *
  Depends on vulnerable versions of request
  node_modules/insight

tough-cookie  <4.1.3
Severity: moderate
tough-cookie Prototype Pollution vulnerability - https://github.com/advisories/GHSA-72xf-g2v4-qvf3
No fix available
node_modules/request/node_modules/tough-cookie

3 moderate severity vulnerabilities
```

##### **JHipster Version(s)**

main

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes we can drop it @mshima 
We also get statistics from start.jhipster.tech but they are not as precise.

**Comment by mshima** [comment]
`insight` dependency was removed and more than a hundred transient dependencies.
For the future, we should consider `insight` alternatives and implement in cli so blueprints like `jhipster-migrate` could have statistics too.
Closing.
