### ISSUE TITLE
Replace console.log() by this.log()

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2567]
According to http://yeoman.io/authoring/user-interactions.html, this.log() should be used instead of console.log() in yeoman generators.

**Comment by deepu105** [comment]
Its done for the entity Generator, need to be done for remaining

**Comment by deepu105** [comment]
done for https://github.com/jhipster/generator-jhipster/pull/2634

**Comment by deepu105** [comment]
we can track this in #2603 as it would be better done together
