### ISSUE TITLE
Keycloak realm configuration is broken

### ISSUE THREAD

**Issue by IShostak** [jhipster/generator-jhipster#25675]
##### **Overview of the issue**

Keycloak realm configuration is broken

Some of the imported values are incorrect so keycloak fails to initialize those. this results in broken flows etc

##### **Motivation for or Use Case**

The realm shouldn't be broken. 

##### **Reproduce the error**

1. Generate project with OAuth
2. Run keycloak image in docker - docker compose -f src/main/docker/keycloak.yml up -d
3. Access keycloak via  http://localhost:9080/
4. Change realm to Jhipster
5. Go to Authentication
6. Try to open Registration or Http challenge flow
7. Observe error

<img width="1491" alt="Screenshot 2024-03-29 at 09 44 25" src="https://github.com/jhipster/generator-jhipster/assets/25927572/d124169b-59c5-4957-a03a-c685be291e5b">

Affects:
If self-registration is enabled(realm settings -> Login -> User registration enabled) -> user will see an error on the registration page. 

<img width="884" alt="Screenshot 2024-03-29 at 09 48 24" src="https://github.com/jhipster/generator-jhipster/assets/25927572/8b43d47f-5c91-47a4-a7b6-85aac5e03a5b">

##### **JHipster Version(s)**
9.2.1

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "testkeycloak",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientTestFrameworks": [],
    "clientTheme": "quartz",
    "clientThemeVariant": "dark",
    "creationTimestamp": 1711659457012,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "devServerPort": 9060,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "Region",
      "Country",
      "Location",
      "Department",
      "Task",
      "Employee",
      "Job",
      "JobHistory"
    ],
    "feignClient": null,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.2.1",
    "languages": [
      "en",
      "ua"
    ],
    "lastLiquibaseTimestamp": 1711659959000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "prodDatabaseType": "mysql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "skipUserManagement": true,
    "syncUserWithIdp": null,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-29)
OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)

git version 2.43.0

node: v21.7.0
npm: 10.5.0

Docker version 25.0.3, build 4debf41

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
@ChangelogDate("20240328210552")
entity Region {
  regionName String
}
@ChangelogDate("20240328210553")
entity Country {
  countryName String
}
/**
 * not an ignored comment
 */
@ChangelogDate("20240328210554")
entity Location {
  streetAddress String
  postalCode String
  city String
  stateProvince String
}
@ChangelogDate("20240328210555")
entity Department {
  departmentName String required
}
/**
 * Task entity.\n@author The JHipster team.
 */
@ChangelogDate("20240328210556")
entity Task {
  title String
  description String
}
/**
 * The Employee entity.
 */
@ChangelogDate("20240328210557")
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String
  lastName String
  email String
  phoneNumber String
  hireDate Instant
  salary Long
  commissionPct Long
}
@ChangelogDate("20240328210558")
entity Job {
  jobTitle String
  minSalary Long
  maxSalary Long
}
@ChangelogDate("20240328210559")
entity JobHistory {
  startDate Instant
  endDate Instant
  language Language
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region} to Region
  Location{country} to Country
  Department{location} to Location
  JobHistory{job} to Job
  JobHistory{department} to Department
  JobHistory{employee} to Employee
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to Employee
  Employee{job} to Job
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

service Region, Country, Location, Department, Task, JobHistory with serviceImpl
search Region, Country, Location, Department, Task, Employee, Job, JobHistory with no
paginate Employee, JobHistory with infinite-scroll
paginate Job with pagination

</pre>
</details>

##### **Browsers and Operating System**

mac os sonoma + chrome 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@DanielFran I reproduce
