### ISSUE TITLE
Release 8.3.0 with vulnerabilities fixed in Spring Boot 3.2.4

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#25717]
##### **Overview of the issue**

I upgraded my [jhipster8-demo](https://github.com/mraible/jhipster8-demo) project to 8.2.1 and added it to Snyk to scan for vulnerabilities. It found several in Spring Boot 3.2.3. 

<img width="948" alt="Screenshot 2024-04-02 at 1 48 54 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/be254f0e-0c62-4357-b191-6d0e88010a10">

##### **Motivation for or Use Case**

If we have security vulnerabilities in our last release that are fixed, we should do a new release with the fixes. 

##### **Reproduce the error**

Let me know if you'd like an invite link to my Snyk project. 

##### **Suggest a Fix**

<img width="1224" alt="Screenshot 2024-04-02 at 1 50 06 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/d0817125-6148-4316-9db5-71c2985bf945">

##### **JHipster Version(s)**

8.2.1

**Comment by mshima** [comment]
Next release should be 8.3.0.
There are big changes in dependency management.

**Comment by mraible** [comment]
OK, I updated the title to be 8.3.0. 

@mshima @DanielFran @qmonmert Are there any issues that should be fixed before the release? I'd like to do it this weekend or Monday at the latest.

**Comment by qmonmert** [comment]
@mraible nothing for me

**Comment by DanielFran** [comment]
> OK, I updated the title to be 8.3.0.
> 
> @mshima @DanielFran @qmonmert Are there any issues that should be fixed before the release? I'd like to do it this weekend or Monday at the latest.

Nothing on my side

**Comment by mshima** [comment]
No blocker.

**Comment by mraible** [comment]
I proposed a vote on the mailing list: https://groups.google.com/g/jhipster-dev/c/9cw8FsVd-ck

I think we should also update our [upgrade guide](https://www.jhipster.tech/upgrading-an-application/) to mention the migrate blueprint. I was able to upgrade my 21-Points Health application to 7.9.4 and 8.2.1 using this blueprint, so I'm happy to review a PR or create one myself.

**Comment by mraible** [comment]
Here's a PR for the upgrade guide: https://github.com/jhipster/jhipster.github.io/pull/1341.
