### ISSUE TITLE
Use Yeoman generator.fs functions

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2571]
Yeoman generators have generator.fs.read(), generator.fs.write(), generator.fs.delete() functions that could be used instead of fs.readFileSync, fs.writeFileSync in util functions rewriteFile, replaceContent, ...
The advantage of using these functions is that when changes are made to files using these functions, you get the ```? Overwrite file? (Ynaxdh)```questions

**Comment by deepu105** [comment]
Yes i was thinking this today when i rewrote entity generator, i guess we
can change those step by step

**Comment by deepu105** [comment]
here is the full lsit supported
https://github.com/sboudrias/mem-fs-editor

**Comment by cbornet** [comment]
Working on this. I need to pass "this" to rewriteFile and replaceContent.
Should I keep the old behaviour if "this" is not passed to preserve backward compatibility with modules ? Or should modules do the necessary to upgrade themselves ?

**Comment by deepu105** [comment]
better keep the old behaviour
