### ISSUE TITLE
Add daviddm url to readme to monitor dependency status

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2572]
Add daviddm url to readme to monitor dependency status, the yeoman generator adds this badge in the template and looks cool

here is jhipster dependency status https://david-dm.org/jhipster/generator-jhipster

**Comment by jdubois** [comment]
Oh, and we need to update those... But this moves so fast, we will always be out of date.

**Comment by deepu105** [comment]
Ya it will mostly show yellow, that's fine but we should take a look when its red
