### ISSUE TITLE
Travis : grunt build failed, using the generated .travis.yml file

### ISSUE THREAD

**Issue by mistvan** [jhipster/generator-jhipster#2574]
Hi gyus, 
I generated basic jhipster app and wanted to use travis, but I got unexpected issue.
Can somebody have a look at my travis build log please?
https://travis-ci.org/mistvan/spevnik/builds/100521652

**Comment by jdubois** [comment]
Please, can you follow the [guidelines(https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue) to submit a bug report?

**Comment by mistvan** [comment]
Hi, 
issue was fixed by using karma v0.3.19 based on this https://github.com/karma-runner/karma/issues/1782.
Now build has passed :) https://travis-ci.org/mistvan/spevnik/builds/100551888

**Comment by pascalgrimaud** [comment]
There is something to analyze and to do here:
- upgrade our karma lib to 0.3.19
- maybe the default .travis.yml generated is outdated
- why our travis build didn't fail

I will change title and assign to me
