### ISSUE TITLE
Error creating a basic application with Jhipster 8.3.0

### ISSUE THREAD

**Issue by jperezdelafuente** [jhipster/generator-jhipster#25795]
##### **Overview of the issue**

When creating a basic application with 1 entity with Jhipster 8.3.0 the following error appears:

- **ERROR! An error occured while running jhipster:languages#write**
- **ERROR! Unable to find /home/foo/src/main/webapp/app/shared/language/find-language-from-key.pipe.ts.**

> 
> Welcome to JHipster v8.3.0
> 
> INFO! Generating jdls foo.jh
> info: The dto option is set for FooEntity, the 'serviceClass' value for the 'service' is gonna be set for this entity if no other value has been set.
>      info Generating 1 application
>  _______________________________________________________________________________________________________________
> 
>   Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
> 
>   Application files will be generated in folder: /home/foo
>  _______________________________________________________________________________________________________________
> 
> WARNING! Search engine is enabled at entity level, but disabled at application level. Search engine will be disabled
>      info Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 99,999 days
>      info       for: CN=Java Hipster, OU=Development, O=com.foo, L=, ST=, C=
>      info KeyStore '/home/foo/src/main/resources/config/tls/keystore.p12' generated successfully.
> ✔ applying multi-step templates
> ✔ Git repository initialized.
> **ERROR! An error occured while running jhipster:languages#write**
> **ERROR! ERROR! Unable to find /home/foo/src/main/webapp/app/shared/language/find-language-from-key.pipe.ts.**
> Error: Unable to find /home/foo/src/main/webapp/app/shared/language/find-language-from-key.pipe.ts.
>     at LanguagesGenerator.editFile (file:///home/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/dist/generators/base-core/generator.js:874:23)
>     at LanguagesGenerator.updateLanguagesInPipeTask (file:///home/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/dist/generators/angular/support/update-languages.js:11:10)
>     at LanguagesGenerator.updateLanguagesTask (file:///home/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/dist/generators/angular/support/update-languages.js:37:31)
>     at LanguagesGenerator.write (file:///home/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/dist/generators/languages/generator.js:305:54)
>     at LanguagesGenerator.executeTask (file:///home/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:26)
>     at env.queueTask.once (file:///home/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:218:56)
>     at runLoop.add.once (file:///home/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:395:23)
>     at Immediate.<anonymous> (/home/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/grouped-queue/lib/subqueue.js:48:34)
>     at process.processImmediate (node:internal/timers:478:21)

##### **Reproduce the error**

jhipster jdl foo.jh

##### **JHipster Version(s)**

Jhipster 8.3.0

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    applicationType monolith,
    baseName foo,
    packageName com.foo,
    jhiPrefix sct,
    authenticationType session,
    databaseType sql,
    devDatabaseType h2Disk,
    prodDatabaseType oracle,
    enableHibernateCache true,
    cacheProvider ehcache,
    buildTool maven,
    testFrameworks [cypress, gatling, cucumber],
    clientFramework [angular],
    enableTranslation true,
    nativeLanguage es,
    languages [es, en]
  }
  entities *
}

/** FooEntity */
entity FooEntity {
    /** fooAtribute */
    fooAtribute String maxlength(50)
}

dto * with mapstruct
service all with serviceImpl
paginate FooEntity with pagination
  </pre>
  </details>

##### **Browsers and Operating System**

Ubuntu 22.04.2 LTS
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)
node: v20.11.1 (also with v18.18.2)
npm: 10.2.4 (also with 9.8.1)

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jperezdelafuente** [comment]
I'm using:
- openjdk version "17.0.7" 2023-04-18
- node v18.16.0
- 9.5.1

Because I am using Java 17 I am using Node 18, as indicated in:
https://github.com/jhipster/generator-jhipster?tab=readme-ov-file#supported-java-and-node-versions
Should you still continue using Node 18 with Java 17?

Months ago with previous versions of Jhipster I was able to correctly perform application generations with "jhipster jdl foo.jh" (foo.jh is in previous comment).

Now I have tried to do code generations with previous versions of Jhipster 

Going back to jhipster version 8.0.0-beta.1:
- npm remove -g generator-jhipster
- npm install -g generator-jhipster@8.0.0-beta.1

"jhipster jdl foo.jh" is generated correctly without errors, although these warnings appear:

> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'eslint@9.0.0',
> npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
> npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.7.1' }
> npm WARN EBADENGINE }
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: '@eslint/eslintrc@3.0.2',
> npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
> npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.7.1' }
> npm WARN EBADENGINE }
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: '@eslint/js@9.0.0',
> npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
> npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.7.1' }
> npm WARN EBADENGINE }
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'eslint-scope@8.0.1',
> npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
> npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.7.1' }
> npm WARN EBADENGINE }
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'eslint-visitor-keys@4.0.0',
> npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
> npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.7.1' }
> npm WARN EBADENGINE }
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'espree@10.0.1',
> npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
> npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.7.1' }
> npm WARN EBADENGINE }

With the following versions I have obtained a similar result:
- @8.0.0-beta.2
- @8.0.0-beta.3

**Comment by jperezdelafuente** [comment]
When trying to go back to more advanced versions of the previous comment such as the following:
- @8.0.0-rc.1
- @8.0.0
- @8.1.0
- @8.2.1
- @8.3.0
"jhipster jdl foo.jh" always causes the same error that I indicated in the first message with the complete trace

```
ERROR! An error occured while running jhipster:languages#write
ERROR! ERROR! Unable to find /home/geiser/prueba/src/main/webapp/app/shared/language/find-language-from-key.pipe.ts.
```

I currently have an application running with Jhipster 8.2.1. 
But when trying to update with automatic update using the command: "jhipster upgrade" I get the same above error "jhipster jdl foo.jh"

A few months ago I was able to correctly perform the following automatic updates with "jhipster upgrade":
- from jhipster with version 8.0.0 to version 8.1.0
- from jhipster with version 8.1.0 to version 8.2.1

Since a few months ago in those versions the code generation with "jhipster jdl foo.jh" was correct, I have the following questions
- Does the behavior of jhipster versions of jhipster depend on when they are installed?
- How could I currently automatically update from jhipster with version 8.2.1 to version 8.3.0?
- Should you still continue using Node 18 with Java 17?

**Comment by mshima** [comment]
The jdl has errors.
After fixing comments.
You should fix `clientFramework [angular]` -> `clientFramework angular`.
