### ISSUE TITLE
org.glassfish.jaxb.runtime.v2.util.StackRecorder: null

### ISSUE THREAD

**Issue by MOURADAYOUB** [jhipster/generator-jhipster#25906]
##### **hen I run the App server tomact the app is running and urls works but I've in log tomact this erreur messgae after : { main] o.g.j.r.v2.schemagen.XmlSchemaGenerator : Writing XML Schema for org.glassfish.jaxb.runtime.v2.schemagen.XmlSchemaGenerator@4d793390:........Classes........]...

org.glassfish.jaxb.runtime.v2.util.StackRecorder: null at org.glassfish.jaxb.runtime.v2.schemagen.XmlSchemaGenerator.write(XmlSchemaGenerator.java:379) at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.generateSchema(JAXBContextImpl.java:770) at org.apache.cxf.common.jaxb.JAXBUtils.generateJaxbSchemas(JAXBUtils.java:810) at org.apache.cxf.jaxb.JAXBDataBinding.generateJaxbSchemas(JAXBDataBinding.java:474) at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:391) at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:87) at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromClass(ReflectionServiceFactoryBean.java:469) at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.buildServiceFromClass(JaxWsServiceFactoryBean.java:693) at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:529) at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:262) at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199) at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:103)

I would producing web service from WSDL with this. (Env cxf-spring-boot-starter-jaxws 4.0.4, java 17, maven 4.0.0 in jhipster application micro service)**

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Wsdl is not supported by JHipster, so this doesn't looks a JHipster bug.
JHipster 8.3.0 provides a reworked dependency management implementation, you should try it.
