### ISSUE TITLE
Feature Request: Select which attributes to show in table view

### ISSUE THREAD

**Issue by hirro** [jhipster/generator-jhipster#2590]
* **Overview of the feature request**

I would like to select which attributes (columns) that should be visible in the entities table view. The  info/edit views  still show all the fields of course. 

* **Motivation for this feature** 

Some fields of the entity may not be relevant to be displayed in the table, those fields are only visible/editable in the info/edit view. 
Too many columns make the table look messy, this can make complex entities more pleasing to the eye.
This feature saves manual labor for those that currently manually edit the columns when resynchronising their projects with jHipster.

* **Suggest a Fix** 

1. Additional question when creating entity. "Make this field only visible in info/edit/create view?" (optional?)
2. New field property "hideColumnInUI": "yes"|"no", "no" is default.
3. Update table generator to handle this.

**Comment by deepu105** [comment]
I dont know if there is enough value in this as the entity generator is
already very complex, you just need to comment out the <th> and <td> for
the column in the html which i think is very easy, any way ill leave this
open for others in the team for opinion

**Comment by hirro** [comment]
I would like to apply additional UI functionality for attributes, this could be a first step. Maybe it could be part of the discussion on how to extend this feature request?

* Attribute categories: Make it possible to create localizable attribute categories. More complex entities with a lot of attributes could benefit from grouping attributes in the UI under a category. 
* Advanced attributes: Advanced attributes are not visible by default, they drop down when clicking on "Advanced..." button under the particular attribute category.
* This may require a own feature request since it could involve changes in the back-end (like liquibase) but "Default values": Provide the option to provide a default value for a attributes (in the UI for now).

**Comment by jdubois** [comment]
As @deepu105 points out, this would be against our Policy 2 at http://jhipster.github.io/policies.html
-> we would add one option for something really too simple

I'm very reluctant do add more questions, we already have too many of them.

**Comment by deepu105** [comment]
@hirro Plz let us know if you think there is any more value in this and we will reopen this. You can always convince us if there is enough value to back this

**Comment by hirro** [comment]
Just want to verify one thing before dropping the issue.

Was it only the feature (as stated in the issue) "Select which attributes to show in table view" that was closed? Or did you also consider the additional UI features I mentioned in the discussion  (Attribute categories, Advanced attributes, Default values, Help text)?

**Comment by deepu105** [comment]
To be frank i dont think I have understood the other part properly, can you
give more details on that, open a new issue if required

On Tue, Jan 12, 2016 at 4:03 PM, Jim <notifications@github.com> wrote:

> Just want to verify one thing before dropping the issue.
>
> Was it only the feature (as stated in the issue) "Select which attributes
> to show in table view" that was closed? Or did you also consider the
> additional UI features I mentioned in the discussion (Attribute categories,
> Advanced attributes, Default values, Help text)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/2590#issuecomment-170832162>
> .
>



-- 
thank you,
Deepu.k.s
