### ISSUE TITLE
Warnings when using the generator : generators.Base is deprecated

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#2594]
Some warnings appears since this PR https://github.com/jhipster/generator-jhipster/pull/2592 :
`require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly`

**Comment by deepu105** [comment]
This is thrown from the script-base.js at root, will remove once the restructure PR is merged

**Comment by deepu105** [comment]
this needs to be done for remaining sub generators as well
