### ISSUE TITLE
Release 8.4.0

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#25960]
##### **Overview of the feature request**

Release 8.4.0 with Spring Boot 3.2.5 and blueprint support improvements.
And follow Spring Boot's monthly schedule.

I propose to follow Spring Boot's monthly schedule.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@mshima Do you have a target date for this release?

**Comment by mshima** [comment]
This week, next week. It's up to you.

**Comment by mshima** [comment]
I propose to target 3-7 day after Spring Boot release for the future releases.

**Comment by mraible** [comment]
This release is mostly complete, except for the documentation-archive step. When I try to execute the steps to create the archives, the Jekyll container fails to start on both Apple Silicon and Intel. The error is the same on both.

<img width="1325" alt="Screenshot 2024-04-29 at 9 36 18 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/448357ac-5c16-4e4a-b761-7739ac91ab84">

**Comment by mraible** [comment]
The release is complete. The problem with the Jekyll container was the paths in the container. See https://github.com/jhipster/jhipster-ansible/pull/11 for more information.

**Comment by mraible** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/200734
