### ISSUE TITLE
Delete dialog doesn't show backend response errors  (*-delete-dialog.html doesn't use jh-alert-error)

### ISSUE THREAD

**Issue by rilopez** [jhipster/generator-jhipster#2597]
**Summary:**

The delete dialogs(`*-delete-dialog.html `) doesn't show backend response errors. for example if the `DELETE` request gets a a 500 error , the dialog just stays there  like it hasn't execute the request. 

**Steps to reproduce**

1. Force the response http error by throwing a dummy exception on the DELETE `api/users/`  endpoint (`com.nearsoft.training.web.rest.UserResource#deleteUser`)

```java
    public ResponseEntity<Void> deleteUser(@PathVariable String login) {
        throw new RuntimeException("this is an scary error");
    }
```
 
2. Go to user managment and click the delete action, the delete user dialog appears
3. Click `delete`, the UI doesn't show anything and stay opened like nothing happen. got to the browser console, you should see this response

```json
{"timestamp":"2016-01-09T19:08:21.824+0000","status":500,"error":"Internal Server Error","exception":"java.lang.RuntimeException","message":"this is an scary error","path":"/api/users/system"}
``` 

**Expectation** 
The delete dialog should display the backend error

NOTE: I already have a fix for this , I'll create the PR during the day

**Comment by deepu105** [comment]
Do you want to do a PR for thia, if so its welcome
