### ISSUE TITLE
Discussion on the docker/sonar support and the new "docker" folder

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2600]
I just released we have a new "docker" folder at the root of the project, from @pascalgrimaud 

- I'm not sure this is correct from a Maven point of view
- It only has a Docker Compose configuration for Sonar, and I guess not a lot of people are using each of those tools, and even less are using them together, so having this at the root of the project isn't probably good

By the way, we also have a docker-compose-prod.yml file at the root of the project, so this isn't very homogenous.

So where should we put those images? I agree that Docker Compose looks like at an excellent solution, even thought I'm not using it myself (on the Mac, I just find that running everything inside VirtualBox is horribly slow and annoying)

Some suggestions:

- Have all the Docker Compose files (for dev, prod, sonar...) in the same directory -> for me this is a requirement
- Then find a good folder for all of those files: 
   - what about 'src/main/docker'? But then what do we do of our Docker Compose configurations for testing?
   - Or 'src/main/resources/docker' ? But we would need to filter it so it's not included in the final JAR file!
   - Or a '.docker' repository? Doesn't look good from a Maven point of view, and why hide it?

**Comment by deepu105** [comment]
Since many wont be using this shouldn't this be an option or a module?

The same goes for the cloud sub gens shouldn't they be modules?

**Comment by atomfrede** [comment]
For me (as a Linux user) docker compose (->Databases) is a killer feature :) So I don't like to have it inside a module only. But I agree docker files for non "core" features like sonar could be inside a module. For me a docker folder in the root doesn't sound so bad, but I'm not sure how strict maven conventions are.

**Comment by jdubois** [comment]
For me we need to have some out-of-the-box solutions for deployment, so
they should be sub-generators and not modules. It's much easier for people,
as everything is installed at once.
I would have at least: cloudfoundry, heroku, AWS, and of course Docker, as
they are the main ones.

For Maven conventions: there isn't much for something like Docker anyway,
but everything should be inside the src directory at least, see
https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
.

On Sun, Jan 10, 2016 at 1:57 PM, Frederik Hahne <notifications@github.com>
wrote:

> For me (as a Linux user) docker compose (->Databases) is a killer feature
> :) So I don't like to have it inside a module only. But I agree docker
> files for non "core" features like sonar could be inside a module. For me a
> docker folder in the root doesn't sound so bad, but I'm not sure how strict
> maven conventions are.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/2600#issuecomment-170343071>
> .
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by pascalgrimaud** [comment]
I feel really guilty about this.

For @deepu105 : the discussion about module is here https://github.com/jhipster/generator-jhipster/issues/2509

The main problem why I keep these files at root directory and use the docker/ directory is Cassandra.
If you generate a project with Cassandra, you'll have a lot additional files here.
So Why ? Because, we use opscenter and a new Docker image which is built to have all cql files.
So for Cassandra, the Dockerfile and docker-compose files need to find the cql files in sub directory.

About your suggestions, I prefer the 1st 'src/main/docker' => seems the best beautiful solution, same directory in this [spring boot docker example](https://spring.io/guides/gs/spring-boot-docker/)
- no problem for testing, we can use `docker-compose -f src/main/docker/dev.yml` for example to start the container
- but for Cassandra, it won't work if we put all files in src/main/docker/

Give me time to think about it, and I try to propose a solution for Cassandra

**Comment by pascalgrimaud** [comment]
So, let's move all dockerfile/docker-compose files to 'src/main/docker' directory.
Is it ok for you ?

Here new commands :
MySQL, PostgreSQL, MongoDB in Development:
```
docker-compose -f src/main/docker/dev.yml up -d
```

MySQL, PostgreSQL, MongoDB in Development:
```
docker-compose -f src/main/docker/prod.yml up -d
```

Cassandra in Development:
```
docker-compose -f src/main/docker/dev.yml build
docker-compose -f src/main/docker/dev.yml up -d
docker cp src/main/resources/config/cql/ jhipster-container-id:/
docker exec -it jhipster-container-id init
```

Cassandra in Production, with Opscenter and Clusters:
```
docker-compose -f src/main/docker/prod.yml build
docker-compose -f src/main/docker/prod.yml up -d
docker cp src/main/resources/config/cql/ jhipster-container-id:/
docker exec -it jhipster-container-id init
docker-compose -f src/main/docker/prod.yml scale jhipster-container-node=X
```

**Comment by jdubois** [comment]
Great, I like this, as it's the same as in the Spring Boot Docker sample,
so definitely this looks like the most logical place!

On Sun, Jan 10, 2016 at 6:23 PM, Pascal Grimaud <notifications@github.com>
wrote:

> So, let's move all dockerfile/docker-compose files to 'src/main/docker'
> directory.
> Is it ok for you ?
>
> Here new commands :
> MySQL, PostgreSQL, MongoDB in Development:
>
> docker-compose -f src/main/docker/dev.yml up -d
>
> MySQL, PostgreSQL, MongoDB in Development:
>
> docker-compose -f src/main/docker/prod.yml up -d
>
> Cassandra in Development:
>
> docker-compose -f src/main/docker/dev.yml build
> docker-compose -f src/main/docker/dev.yml up -d
> docker cp src/main/resources/config/cql/ jhipster-container-id:/
> docker exec -it jhipster-container-id init
>
> Cassandra in Production, with Opscenter and Clusters:
>
> docker-compose -f src/main/docker/prod.yml build
> docker-compose -f src/main/docker/prod.yml up -d
> docker cp src/main/resources/config/cql/ jhipster-container-id:/
> docker exec -it jhipster-container-id init
> docker-compose -f src/main/docker/prod.yml scale jhipster-container-node=X
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/2600#issuecomment-170372595>
> .
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by deepu105** [comment]
I think we should atleast have a --skip-docker flag to skip creating docker folders and files for those who dont want it.

I know many enterprises using Jhipster who doesnt do docker due to policies and stuff so for these people it would be unnecessary stuff might even confuse some people who doesnt know what docker is. 


Btw, pascal plz wait untill the app generator restructuring is merged

**Comment by pascalgrimaud** [comment]
Don't worry @deepu105, you made a huge work in https://github.com/jhipster/generator-jhipster/pull/2595
I'll wait your PR is merged and I'll do PR
