### ISSUE TITLE
creating a new user results in activated

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#2602]
I've a question regarding the user management. When creating a new user the user is always activated (such that the user can reset the password). In the ui you can create a new user with activated=false. It is a little confusing for the user I think.

My solution would be to deactivate the checkbox (and check it) when creating a new user. Is everyone ok with that or do I miss something?

**Comment by deepu105** [comment]
I thought it was checked always, but yes should be deactivated as well i
guess
