### ISSUE TITLE
`npx jhipster upgrade` doesn't work to upgrade an app from 8.3.0 to 8.4.0

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#26057]
##### **Overview of the issue**

I tried to use `npx jhipster upgrade` to upgrade my [jhipster8-demo](https://github.com/mraible/jhipster8-demo) project from 8.3.0 to 8.4.0. I know I could use the migrate blueprint, but I figured it'd be good to test the [upgrade instructions](https://www.jhipster.tech/upgrading-an-application/). 

The first time I tried it, the only thing the process changed was the `package-lock.json` file. It did not upgrade `package.json` to use 8.4.0 or modify any other files. I figured this might be caused by existing branches, so I deleted all the branches and tried again. The behavior is the same.

<img width="1442" alt="Screenshot 2024-05-07 at 11 02 57 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/cb85a89a-b9b2-4358-96f8-161ef834bd3c">

##### **Motivation for or Use Case**

Our upgrade instructions should work. If `npx jhipster upgrade` is not working, we should recommend the migrate blueprint first. 

##### **Reproduce the error**

```
git clone https://github.com/mraible/jhipster8-demo.git
cd jhipster8-demo
npm install
npx jhipster upgrade
```

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/25033

##### **Suggest a Fix**

Update the documentation to recommend the migrate blueprint, change the `upgrade` command so it works.

##### **JHipster Version(s)**

```
blog@0.0.1-SNAPSHOT /Users/mraible/dev/jhipster8-demo
├─┬ generator-jhipster-migrate@1.0.0
│ └── generator-jhipster@8.3.0 deduped
└── generator-jhipster@8.3.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "blog",
    "blueprints": [
      {
        "name": "generator-jhipster-migrate",
        "version": "1.0.0"
      }
    ],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "none",
    "creationTimestamp": 1702525034689,
    "cypressAudit": true,
    "cypressCoverage": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "Blog",
      "Post",
      "Tag"
    ],
    "feignClient": false,
    "gradleEnterpriseHost": null,
    "herokuAppName": "jhipster8-demo",
    "herokuDeployType": "git",
    "herokuJavaVersion": "21",
    "jhipsterVersion": "8.3.0",
    "languages": [
      "en",
      "es"
    ],
    "lastLiquibaseTimestamp": 1710952227000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "org.jhipster.blog",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "testFrameworks": [
      "cypress"
    ],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode)

git version 2.39.3 (Apple Git-146)

node: v20.12.1
npm: 10.7.0

Docker version 26.0.0, build 2ae903e

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
@ChangelogDate("20240320163025")
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
@ChangelogDate("20240320163026")
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
@ChangelogDate("20240320163027")
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User with builtInEntity
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

search Blog, Post, Tag with no
paginate Post, Tag with infinite-scroll

</pre>
</details>

**Comment by mshima** [comment]
- drop migrate from .yo-rc.json and package.json (it's not suppose to be there) and commit.
- remove generator-jhipster from global to avoid conflict `npm -g uninstall generator-jhipster`
- upgrade using `npx -y -- generator-jhipster@8.4.0 upgrade`

**Comment by mraible** [comment]
@mshima I tried your suggestions and they worked. It seems like we need to update our documentation because `npx jhipster upgrade` does not work. In [this PR](https://github.com/mraible/jhipster8-demo/pull/139), I used the following sequence:

1. Removed the migrate blueprint from .yo-rc.json and package.json, committed and pushed changes
2. Ran `npx jhipster upgrade`, added the changes from package-lock.json, committed and pushed
3. Ran ` npx -y -- generator-jhipster@8.4.0 upgrade` and pushed the changes

IMHO, it seems like it's easier to remember `jhipster-migrate` than it is to remember the last command.

**Comment by mraible** [comment]
One other strange thing I noticed is the build tool prompt has Maven and Gradle in lowercase. 

<img width="1442" alt="Screenshot 2024-05-07 at 6 37 25 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/c53c9ad3-e37d-4f55-9f13-de4dadafe797">

I also noticed that the questions seem to be in a random order compared to 8.1.0. Here are the questions from 8.1.0:

<img width="1442" alt="JHipster 8.1.0" src="https://github.com/mraible/jhipster8-demo/raw/main/static/generating-blog.png">

With 8.4.0, many of the client questions are asked first, then the Cypress questions are asked at the end. Having the questions change order between releases makes it hard to write evergreen tutorials about JHipster.

<img width="1442" alt="Screenshot 2024-05-07 at 6 39 08 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/91370cb9-ee93-4b46-bb3a-3e2932394f7e">

Also, there's a warning about relationships between entities and I haven't created any yet.

**Comment by mshima** [comment]
> @mshima I tried your suggestions and they worked. It seems like we need to update our documentation because `npx jhipster upgrade` does not work. In [this PR](https://github.com/mraible/jhipster8-demo/pull/139), I used the following sequence:
> 
> 1. Removed the migrate blueprint from .yo-rc.json and package.json, committed and pushed changes
> 2. Ran `npx jhipster upgrade`, added the changes from package-lock.json, committed and pushed
> 3. Ran ` npx -y -- generator-jhipster@8.4.0 upgrade` and pushed the changes
> 
> IMHO, it seems like it's easier to remember `jhipster-migrate` than it is to remember the last command.

Using global installation, they are equivalent:
upgrade:
1. `npm install -g generator-jhipster@latest`
2. `jhipster upgrade`

migrate:
1. `npm install -g generator-jhipster-migrate@latest`
2. `jhipster-migrate`

npx alternative can be simplified:
1. `npx generator-jhipster@latest upgrade` and a prompt may be asked.

**Comment by mraible** [comment]
I just noticed another typo in the questions. Junit should be JUnit.

**Comment by mraible** [comment]
Here's a PR to update the instructions: https://github.com/jhipster/jhipster.github.io/pull/1346

**Comment by mshima** [comment]
> With 8.4.0, many of the client questions are asked first, then the Cypress questions are asked at the end. Having the questions change order between releases makes it hard to write evergreen tutorials about JHipster.

We will need a new priority to make every backend generator to configure before client generators.

**Comment by mshima** [comment]
@mraible is something missing?

**Comment by mraible** [comment]
The upgrade instructions have been updated and other issues have been fixed, so I'll close this as resolved.
