### ISSUE TITLE
Can't read swagger JSON from http://127.0.0.1:8080/v2/api-docs

### ISSUE THREAD

**Issue by eheb** [jhipster/generator-jhipster#2607]
when i deploy jhispter/swagger2 application in tomcat8 with a root web context (by example ods-0.0.1-SNAPSHOT) , swagger api url is getting from http://127.0.0.1:8080/v2/api-docs instead of http://127.0.0.1:8080/ods-0.0.1-SNAPSHOT/v2/api-docs
what can i do ? is there swagger properties to define this url in application-[env].yml ?
best regards

**Comment by jdubois** [comment]
Yes, that's because you have a Web application context when you deploy on Tomcat. There is probably a way to make this URL relative, or as you say write the context somewhere.

**Comment by deepu105** [comment]
It can be made relative like in the websocket tracker service

**Comment by eheb** [comment]
you say write the context somewhere : how ?
 is there swagger properties to define this url in application-[env].yml ?
where and how the path of the swagger.json is built ?
how do developers where thes deploy to Tomacat or another application server ? how do the 'embeddedexecutable' war do because it works ?
Best regards.

**Comment by eheb** [comment]
how to matke this pat to swagger json file relative to the context root ?

**Comment by gmarziou** [comment]
/v2/api-docs is the default path for springfox, as written in [their doc](http://springfox.github.io/springfox/docs/snapshot/#customizing-the-swagger-endpoints).

It should be possible to change this in SwaggerConfiguration by using the Docket initialisation code.

**Comment by eheb** [comment]
SwaggerConfiguration.java, Docker init :        Docket docket = new Docket(DocumentationType.SWAGGER_2)
            .apiInfo(apiInfo)...
Where can i find a complete example for the v2 api path customisation ?

**Comment by eheb** [comment]
I add this part in the appplication-dev.yml as in the doc of springfox but i doesn't work :-(
why ? how to do with the Docket initialisation code in SwaggerConfiguration 
# swagger
# springfox.documentation.swagger.v2.path=/v2/api-docs
# override property for Tomcat deploy : /ods-0.0.1-SNAPSHOT/v2/api-docs
springfox:
  documentation:
     swagger:
        v2:
          path: /ods-0.0.1-SNAPSHOT/v2/api-docs

**Comment by gmarziou** [comment]
Sorry this property is used only by ApiResourceController, the path /v2/api-docs is hard-coded in javascript block in src/main/webapp/swagger-ui/index.html, I guess it could be edited to use a relative path like ../v2/api-docs. Could you try?
