### ISSUE TITLE
Questions should follow the same order between major releases

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#26079]
##### **Overview of the issue**

The questions in 8.4.0 seem to be in a random order compared to 8.1.0. Here are the questions from 8.1.0:

<img width="1442" alt="JHipster 8.1.0" src="https://github.com/mraible/jhipster8-demo/raw/main/static/generating-blog.png">

With 8.4.0, many of the client questions are asked first, then the Cypress questions are asked at the end. 

<img width="1442" alt="Screenshot 2024-05-07 at 6 39 08 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/91370cb9-ee93-4b46-bb3a-3e2932394f7e">

##### **Motivation for or Use Case**

Having the questions change order between releases makes it hard to write evergreen tutorials about JHipster.

##### **Reproduce the error**

Create a project with 8.1.0 and take a screenshot of the question order. Do the same with 8.4.0 and you'll notice they're in a different order. 

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/26057

##### **Suggest a Fix**

Make it so the questions are in the same order in v8 and beyond. You can see the order from previous releases at the links below:

- JHipster 4: https://github.com/mraible/jhipster4-demo/raw/master/static/generating-blog.png
- JHipster 5: https://github.com/mraible/jhipster5-demo/raw/master/static/generating-blog.png
- JHipster 6: https://github.com/mraible/jhipster6-demo/raw/master/static/generating-blog.png
- JHipster 7: https://github.com/mraible/jhipster7-demo/raw/main/static/generating-blog.png

##### **JHipster Version(s)**

8.4.0

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/203374.

**Comment by DanielFran** [comment]
@mshima approved
