### ISSUE TITLE
AngularJS replacement with ReactJS 

### ISSUE THREAD

**Issue by ykushch** [jhipster/generator-jhipster#2608]
Are there any plans regarding the usage of ReactJS instead of AngularJS? 
If there plans - I will be glad to help with this.

**Comment by jdubois** [comment]
We are not going to replace AngularJS by ReactJS.
There is a module currently being written for this, you can have a look at what @deepu105 does at https://github.com/deepu105/generator-jhipster-react

**Comment by deepu105** [comment]
@ykushch I haven't committed anything yet, as its still WIP but if you want
to collaborate you are welcome, ill let you know once i commit the base

**Comment by deepu105** [comment]
@ykushch I have committed an initial version here https://github.com/deepu105/generator-jhipster-react

Plz take a look, I havent added any client side code, this will currently only generate a backend application I have added placeholder methods for front end promts and writing client files.

Would you like to collaborate on this, if so ill provide you access

cc @Dhiviya-Bharathi Arun mentioned that you are interested in this

**Comment by ykushch** [comment]
@deepu105 yes, I would like to start working on that. Planning to use React with Jhipster's backend.

**Comment by deepu105** [comment]
Great let me know if I can help in anyway

**Comment by ykushch** [comment]
@deepu105 sure. Thanks for mentioning. Already forked it. Will start looking through code.

**Comment by deepu105** [comment]
@sendilkumarn you can follow a similar approach as [here](https://github.com/hipster-labs/generator-jhipster-react) if you want to do a jhipster generator with angular material instead of bootstarp

**Comment by christopherthielen** [comment]
Worthy to note that ui-router now also supports react: https://ui-router.github.io/react/
It would make it much easer to create a react version of the generator.

**Comment by deepu105** [comment]
Thanks Chris. Ill try it out when I get a chance. Currently there seems to
be not enough interest in the community for react on jhipster as im not
getting much contribution in the jhipster-react repo.

Btw could you take a look at the PR I mentioned you. Im having some trouble
there with ui-router

Thanks & regards,
Deepu

**Comment by kanderson450** [comment]
I for one would love to see this, but haven't had the time to help out yet....
