### ISSUE TITLE
Wrong jhipster version for modules on jhipster.io

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2609]
All modules on the website are said to be compatible with jhipster > 2.26.2 even though it s not the case in their package.json.

**Comment by deepu105** [comment]
Yes, may be all of us need to correct this for our module entry in the modules.json

**Comment by cbornet** [comment]
The default jhiVersionRequired should probably be 2.26.0 since it's what most early modules use.

**Comment by jdubois** [comment]
Yes this is my fault: when the version is not set, I put "2.6.2" by default, as it was the most recent version...

**Comment by jdubois** [comment]
I could put "version not set" instead

**Comment by jdubois** [comment]
I've written "version not set" if nothing is written, but for all current modules I put "> 2.26.2", as it's a recent version I'm sure it works.
If you know your module works with an older version, please do a PR and I will merge it ASAP

**Comment by cbornet** [comment]
Arf ! I think the only module that needs > 2.26.2 is the entity-audit from @deepu105 . The other ones work with 2.26.0.
Maybe we could get the jhipster version from github's package.json ?

**Comment by cbornet** [comment]
Or even better : directly from npmjs !
http://registry.npmjs.org/generator-jhipster-basic-auth/latest
