### ISSUE TITLE
Is there any way to add property like "CascadeType.ALL" to relationships

### ISSUE THREAD

**Issue by ouyangshixiong** [jhipster/generator-jhipster#2617]
As I known, I can set relationship between entities. 
But I can't set any properties like "CascadeType.ALL" to certain fields.
So, If I add any field to the domain object, I have to modify annotation @ManyToOne to @ManyToOne( cascade = { CascadeType.ALL } ) to certain fields manually.

By the way, I am using jhipster-uml's JDL. there are same problems when add field to exist entities and regenerate entities. Even when use mysql, liquibase can not work unless drop database. It cause lost all exist mysql data.
![problem1](https://cloud.githubusercontent.com/assets/2086862/12256842/ee163eb8-b93b-11e5-8f11-db7cb56d7882.png)

**Comment by MathieuAA** [comment]
Can you post the issue in JHipster-UML's page so that it's verified/fixed?

**Comment by ouyangshixiong** [comment]
Thanks MathieuAA .
I had try this process again.
1. make up JDL file relationship.jh
![problem2](https://cloud.githubusercontent.com/assets/2086862/12286080/164b77ca-b9fc-11e5-85a3-cf87920b8b06.png)
2. Run jhipster-uml relationship, And modify application-dev.xml config; And run mvn to generate db tables.
3.  modify relationship.h add field
![problem3](https://cloud.githubusercontent.com/assets/2086862/12290912/41f891be-ba1f-11e5-9aa8-69d123638732.png)
4. Run jhipster-uml again
5. Run mvn compile liquibase:diff
![problem5](https://cloud.githubusercontent.com/assets/2086862/12291309/60ad624a-ba21-11e5-99fb-42953ac5cad6.png)
6. look at  master.xml
![problem6](https://cloud.githubusercontent.com/assets/2086862/12291341/a039be40-ba21-11e5-9afa-708e47760a37.png)
7. Run mvn. you can see the Error like this：
![problem7](https://cloud.githubusercontent.com/assets/2086862/12291422/158ca784-ba22-11e5-98d4-34af97b691dd.png)

**Comment by deepu105** [comment]
please take this to the Jhipster UML repo as @MathieuAA suggested
