### ISSUE TITLE
Release missing v8 based blueprints.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#26189]
##### **Overview of the feature request**

- [x] generator-jhipster-ionic
- [x] generator-jhipster-react-native
- [x] generator-jhipster-nodejs

Those blueprint are already updated to v8.4, but release based on v8.x are still pending.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@mraible is something missing for ionic and react-native?
@DanielFran do you have permission to release nodejs?

**Comment by mraible** [comment]
@mshima At a glance, Ionic looks like it's ready for a release since there aren't that many pull requests. All dependencies seem to be updated. To feel comfortable doing a release, I'd like to run some smoke tests (generate an app or two) and see if some of the open issues are fixed.

The React Native blueprint seems to have a lot more open PRs that've failed to update dependencies. I don't know if that's a concern.

**Comment by mshima** [comment]
Ionic blueprint has this problem: https://github.com/jhipster/generator-jhipster/issues/26152#issuecomment-2115692273
React Native and NodeJS have outdated packages, but it’s not so simple to upgrade.
I think we should release even with outdated packages.

**Comment by mraible** [comment]
FWIW, when I first authored the Ionic blueprint, I always assumed `syncUserWithIdp` would be true. Therefore, I'm not surprised this issue exists. I can do a release later this week.

**Comment by mshima** [comment]
> FWIW, when I first authored the Ionic blueprint, I always assumed `syncUserWithIdp` would be true. Therefore, I'm not surprised this issue exists.

It's not really a `syncUserWithIdp` problem, but differences in implementation that is fixed in main.

> I can do a release later this week.

I think we can wait for generator-jhipster v8.5.0 with spring-boot 3.3.0 that will be released in 2 days.

**Comment by mraible** [comment]
> I think we can wait for generator-jhipster v8.5.0 with spring-boot 3.3.0 that will be released in 2 days.

OK. In the past, major Spring Boot versions have taken a while to upgrade. We might want to try latest milestone release to see what issues arise.

**Comment by mraible** [comment]
Angular 18 will be [released this week too](https://angular.io/guide/releases#support-policy-and-schedule).

There's also a [What's new in Angular](https://www.youtube.com/watch?v=srP2P6j4Cqw) from Google I/O that was published 4 days ago.

**Comment by mraible** [comment]
It looks like Ionic and React Native are ready to release. Node is [failing in CI](https://github.com/jhipster/generator-jhipster-nodejs/pull/486). 

Micronaut and Native are updated, those could be released too.

Quarkus hasn't been updated. 

Am I missing any blueprints that should be updated?

**Comment by mshima** [comment]
I should release entity-audit tomorrow.
I still need to will work on Native update.
I will take a look in Node blueprint too.

I think Micronaut, Ionic and React Native can be released.

**Comment by mraible** [comment]
The Ionic blueprint [v8.2.0](https://github.com/jhipster/generator-jhipster-ionic/releases/tag/v8.2.0) has been released.

**Comment by mraible** [comment]
An update for the Ionic blueprint, [v8.2.1](https://github.com/jhipster/generator-jhipster-ionic/releases/tag/v8.2.1) is now available.

**Comment by mraible** [comment]
The Micronaut blueprint [v3.4.0](https://github.com/jhipster/generator-jhipster-micronaut/releases/tag/v3.4.0) has been released.

**Comment by mraible** [comment]
React Native [v5.5.0](https://github.com/jhipster/generator-jhipster-react-native/releases/tag/v5.0.0) has been released.

**Comment by mraible** [comment]
The Micronaut blueprint [v3.4.1](https://github.com/jhipster/generator-jhipster-micronaut/releases/tag/v3.4.1) has been released with Micronaut 4.5.0 support.

**Comment by mshima** [comment]
NodeJS blueprint has been updated to v8.5.0.
Anyone have release rights?

**Comment by mraible** [comment]
@mshima I have access to the jhipster org on npmjs.com, so I added myself as a member of the Node.js blueprint.

**Comment by mraible** [comment]
The Quarkus blueprint [v3.2.0](https://github.com/jhipster/generator-jhipster-quarkus/releases/tag/v3.2.0) has been released.

**Comment by mraible** [comment]
The Node.js blueprint [v3.0.0](https://github.com/jhipster/generator-jhipster-nodejs/releases/tag/v3.0.0) has been released.
