### ISSUE TITLE
Grunt useminPrepare uses html files from bower components

### ISSUE THREAD

**Issue by eelcobrolman** [jhipster/generator-jhipster#2618]
Hi,

I ran into a problem when using a bower component "angular-audio": suddenly the -Pprod build failed to generate the minified app.js. After investigation I concluded the following:
* the angular-audio component ships with a ```src/main/webapp/bower_components/angular-audio/app/index.html``` where I found a ```<!-- build:js({app,.tmp}) scripts/main.js -->``` tag.
* the ng-file-upload component (shipped by default with jhipster) provides the file ```src/main/webapp/bower_components/ng-file-upload/index.html``` which **also** declares a ```<!-- build:js({app,.tmp}) scripts/main.js -->``` tag
* the ```Gruntfile.js``` declares the ```useminPrepare:html``` as ```src/main/webapp/**/*.html```, thus including **BOTH** the above tags.

When running ```grunt build```, it shows the warning:
```
Warning: Different sources attempting to write to the same destination:
 {
    "dest": ".tmp/concat/scripts/main.js",
    "src": [
        "{app,.tmp}/scripts/main.js"
    ]
}
  {
    "files": []
} Use --force to continue.
```

Unfortunately, ```--force``` is the default when running this command from ```mvn package -Pprod```.

When running as ```grunt build --force --verbose```, it is clear what fails:
```
Running "ngtemplates:dist" (ngtemplates) task
Verifying property ngtemplates.dist exists in config...OK
Files: scripts/app/account/activate/activate.html, scripts/app/account/login/login.html, 
<snip>
Reading src/main/webapp/scripts/components/navbar/navbar.html...OK
Writing .tmp/templates/templates.js...OK
File .tmp/templates/templates.js created.
Files: [no src] -> src/main/webapp/dist/scripts/vendor.js
Files: [no src] -> src/main/webapp/dist/scripts/main.js
>> Could not find usemin.generated path matching: scripts/app.js
```

As the final result, the minified app.js is not generated, and the app won't run.

My suggestions:
1. Remove the --force in the grunt task (in ```Gruntfile.js```), so it fails for these critical errors
2. Fix the useminPrepare:html, so it excludes the bower_components subdir.

I just used: 
```
 useminPrepare: {
            html: 'src/main/webapp/index.html',
```

and that worked fine, but could be too narrow if you use more than one html entry point for your application.

**Comment by andidev** [comment]
Does neglegating the bower_components folder like this work?

```
 useminPrepare: {
            html: ['src/main/webapp/**/*.html', '!src/main/webapp/bower_components/**/*.*'],
```

But maybe it is better to be clearer to directly point out the html file as you suggest.

**Comment by eelcobrolman** [comment]
> Does neglegating the bower_components folder like this work?
> 
>  useminPrepare: {
>             html: ['src/main/webapp/**/*.html', '!src/main/webapp/bower_components/**/*.*'],

Yes, that works also...!

**Comment by atomfrede** [comment]
@andidev I agree, pointing directly to ``index.html`` makes more sense to me (**Single**Page App). If somebody wants to have multiple entry points it can easily changed.
