### ISSUE TITLE
Changing logback.loglevel in pom.xml has no effect 

### ISSUE THREAD

**Issue by jvence** [jhipster/generator-jhipster#2619]
I'm using jHipster 2.23.0 and have not upgraded because of the amount of work required for out particular project

Trying to modify the logging levels of my app but changing logback.loglevel in pom.xml has no effect. 

logback-spring.xml seems to use logback.loglevel to set the level but it doesn't seem to be working. 

Changing log level from admin log menu is not option as it is not persistent

Might be related to https://github.com/jhipster/generator-jhipster/issues/2419

**Comment by pascalgrimaud** [comment]
Can't test 2.23.0 right now, but maybe can you look this issue https://github.com/jhipster/generator-jhipster/issues/2340
And maybe this PR https://github.com/jhipster/generator-jhipster/pull/2347 can resolve your problem ?

**Comment by pascalgrimaud** [comment]
just tested it, #2347 should fix your problem
