### ISSUE TITLE
Upgrade spring-boot to v3.3.0

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#26205]
##### **Overview of the feature request**

Spring Boot v3.3.0 is scheduled for [May 23](https://github.com/spring-projects/spring-boot/milestone/332).

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/211707.
The undetected regression was fixed and regression tests are in place.

**Comment by DanielFran** [comment]
@mshima approved

**Comment by mshima** [comment]
@DanielFran thanks.
