### ISSUE TITLE
Not generating service files

### ISSUE THREAD

**Issue by sholland236** [jhipster/generator-jhipster#26206]
When using jhipster command to generate a new project, the service files within the java folder are not being created.

Specific to my generation: I selected both keycloak and elasticsearch during the generation process.

First found on 8.3.0, but I've recently updated to 8.4.0 and still experiencing the issue

Running jhipster info provides the following:
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "empty",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientTestFrameworks": [],
    "clientTheme": "none",
    "creationTimestamp": 1715958555511,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 9060,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [],
    "feignClient": null,
    "jhipsterVersion": "8.3.0",
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.empty.experience",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": "elasticsearch",
    "serverPort": null,
    "serverSideOptions": [
      "searchEngine:elasticsearch"
    ],
    "serviceDiscoveryType": false,
    "skipUserManagement": true,
    "syncUserWithIdp": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)

git version 2.35.1.windows.2

node: v20.9.0
npm: 10.2.3

Docker version 20.10.17, build 100c701

**Comment by mraible** [comment]
Can you please elaborate and describe the service files you expect to be created?

**Comment by sholland236** [comment]
Yes, I was expecting the dto, mapper and UserService files as with a previous keycloak generation to be created.

**Comment by mshima** [comment]
`syncUserWithIdp` is default to false to avoid creating User repository/service that is used of relationships only.

- It's enabled if a relationship with User is found.
- If it's manually enabled with `--sync-user-with-idp` option.
