### ISSUE TITLE
Searching for decimal numbers produces no results

### ISSUE THREAD

**Issue by roblight** [jhipster/generator-jhipster#2622]
Using jhipster-sample-app-elasticsearch@90a11f4b87f2d80e28eeee7ca23e8dc2c4858678 app I created a new `BankAccount` entity with a balance of `98.76`.  Searching for `98.76` gives no results on the `/#/bankAccounts` page.

**Comment by pascalgrimaud** [comment]
Correct result in Elasticsearch : http://localhost:9200/_search?q=13.37
```yaml
{"took":5,"timed_out":false,"_shards":{"total":20,"successful":20,"failed":0},"hits":{"total":1,"max_score":0.095891505,"hits":[{"_index":"bankaccount","_type":"bankaccount","_id":"2","_score":0.095891505,"_source":{"id":2,"name":"LEET","balance":13.37,"user":{"id":1,"login":"system","firstName":"System","lastName":"System","email":"system@localhost","activated":true,"langKey":"en","resetKey":null,"resetDate":null}}}]}}
```

Trace in JHipster, for same search:
```
2016-01-13 07:27:32.099 DEBUG 10708 --- [io-8080-exec-10] c.m.myapp.web.rest.BankAccountResource   : REST request to search BankAccounts for query 13
```

**Comment by pascalgrimaud** [comment]
See https://github.com/jhipster/generator-jhipster/pull/2434
In your BankAccountResource.java, can you try :
```java
    @RequestMapping(value = "/_search/bankAccounts/{query:.+}",
```

**Comment by roblight** [comment]
Excellent!  Thank you so much @pascalgrimaud !  That worked perfectly.  :smile:

**Comment by roblight** [comment]
Related question: Searching for `Boolean` values doesn't seem to work.  The URL `http://localhost:8080/api/_search/users/true` returns HTTP 200 and no results.

Should I open another issue?

**Comment by jdubois** [comment]
@roblight looks like another issue, so yes please create a new one.
I'm closing this one as this is OK.

**Comment by roblight** [comment]
Shouldn't there be a change to the generator for all `@RequestMapping` queries as suggested by @pascalgrimaud in https://github.com/jhipster/generator-jhipster/issues/2622#issuecomment-171199847?

**Comment by pascalgrimaud** [comment]
Do you want to make a PR @roblight ?

**Comment by roblight** [comment]
@pascalgrimaud If it's not too much to ask, that would be great!

**Comment by pascalgrimaud** [comment]
The user should be able to search with a 'dot' => so I will reopen this ticket until your PR

**Comment by pascalgrimaud** [comment]
@roblight : any news about this little PR ? => If you don't have time, I'll do it
A new version should be release soon, so it would be interesting to fix this, before the release

**Comment by roblight** [comment]
@pascalgrimaud - If you could do it that would be great.  Thanks so much.
