### ISSUE TITLE
Jhipster Support Sidebar Menu

### ISSUE THREAD

**Issue by wenbin9** [jhipster/generator-jhipster#26229]
Dear JHipster,

Currently, we are using jhispter 8.4.0. Noted that jhipster only provide navbar menu, but some application may need sidebar menu like 
jhispter website(https://www.jhipster.tech/). 

So, it is possible to integrate the sidebar menu features of the jhipster official website(https://www.jhipster.tech/) into the generator-jhipster. On the one hand, it can provide users with more choices, and on the other hand, it can enhance visual effects.

Thanks so much!

![image](https://github.com/jhipster/generator-jhipster/assets/43366674/ada14e57-a7bb-4890-91b4-c835dc8353a7)
![image](https://github.com/jhipster/generator-jhipster/assets/43366674/b1bea844-ed2e-465f-a6dc-fc92ef460290)

**Comment by dwarakaprasad** [comment]
I don't think there is an option in the generator to do this currently but, this can be done with a [blueprint](https://www.jhipster.tech/modules/extending-and-customizing/). If you have the modified app, I can bootstrap a blueprint for you.

**Comment by wenbin9** [comment]
> I don't think there is an option in the generator to do this currently but, this can be done with a [blueprint](https://www.jhipster.tech/modules/extending-and-customizing/). If you have the modified app, I can bootstrap a blueprint for you.

I am trying to build a sidebar menu base on jhipster 8.4.0. Does this blueprint will be maintain by jhipster official?
