### ISSUE TITLE
Release 8.5.0 with Spring Boot 3.3.0 

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#26247]
##### **Overview of the feature request**

Release 8.5.0 with Spring Boot 3.3.0, code quality fixes, and more type safety. 

##### **Motivation for or Use Case**

It's good to keep up with Spring Boot releases. The upgrade to Angular 18 will have to wait for a minor release since related libraries haven't been updated yet. 

##### **Related issues or PR**

- https://github.com/jhipster/generator-jhipster/pull/26242
- https://github.com/jhipster/generator-jhipster/issues/26208

**Comment by mraible** [comment]
@qmonmert @DanielFran @mshima @Tcharl Please let me know if there's anything you'd like to see fixed before this release.

**Comment by qmonmert** [comment]
@mraible nothing for me

**Comment by mshima** [comment]
I have a few things before 8.5.0.

**Comment by Tcharl** [comment]
On my side I'm just improving the codebase right now, so long run and no end user impact (not even blueprint dev for now I think). So release can be done whenever you want.

**Comment by DanielFran** [comment]
All good on my side, but maybe we should update the maven wrapper to version 3.3.2, this will fix some windows issues.
Confirmed it works now on bom project: https://github.com/jhipster/jhipster-bom/pull/1581!

**Comment by mshima** [comment]
> Please wait for #26281.

Done

**Comment by mraible** [comment]
Should we wait until the next version of Spring Cloud is released? It's scheduled for tomorrow. https://github.com/spring-cloud/spring-cloud-release/milestones

**Comment by mraible** [comment]
Look OK to release or to wait for the next version of Spring Cloud? I asked because I saw this issue: https://github.com/spring-cloud/spring-cloud-release/issues/287.

**Comment by mraible** [comment]
OK, I'll wait until Spring Cloud 2023.0.2 is released and upgraded in JHipster.

**Comment by mraible** [comment]
The Spring Cloud 2023.0.2 upgrade is at https://github.com/jhipster/jhipster-bom/pull/1591.

**Comment by mraible** [comment]
@DanielFran bounty claimed: https://opencollective.com/generator-jhipster/expenses/205860

**Comment by DanielFran** [comment]
@mraible approved
