### ISSUE TITLE
generatr-blueprint creates *.js files instead of *.mjs

### ISSUE THREAD

**Issue by dwarakaprasad** [jhipster/generator-jhipster#26244]
##### **Overview of the issue**
Generating a new blueprint using `jhipster generate-blueprint` creates files `<root-folder>/generators/generator.js` instead of *.mjs files. 

##### **Related issues**
#25276 added this [logic](https://github.com/jhipster/generator-jhipster/blame/3aacc3bd31efa41c6f31914d29488e76d57ec74c/generators/generate-blueprint/constants.js#L54C3-L54C41) which only enables if local blueprint is selected.

Is this by design.

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Local blueprint is used in project that can be type commonjs.
Generators are type module, we need to use mjs extension or add a package.json with type module in `.blueprint` dir.

Non local blueprints are packages that we generate as type module. So it can have js extension. `js` is the preferred extension so we use it.

**Comment by mshima** [comment]
If you prefer mjs extension you can use `--no-js` option.

**Comment by dwarakaprasad** [comment]
makes sense, thank you @mshima. Is there any plan in the future to convert the blueprints to typescript.

**Comment by mshima** [comment]
No plans for typescript blueprints in official blueprints and generate-blueprint command.
I don’t see any advantage in adding the typescript complexity in blueprints.
But it’s  possible to create a typescript blueprint.
