### ISSUE TITLE
Pagination bug

### ISSUE THREAD

**Issue by btabo** [jhipster/generator-jhipster#2625]
Pagination is not showing the appropriate number of pages for me.
You can reproduce this issue with  the user management page, or any entity you decide to create with linked pagination : if you try to reduce the page size from 20 to lets say 5 (for example in user-management.controller.js), and add a couple of entities just for testing, you'll expect to find at least 2 pages but I can still see only 1 page, with obviously missing items.

Sorry i've been blocking on that issue without beeing able to explain myself the root cause... if anyone could tell me if you have the same problem or any lead to solve it, it would help a lot. Thx.

(using JHipster Generator v2.26.2 with Chrome, and MongoDB)

**Comment by ruddell** [comment]
When the paging changed to ui-bootstrap in 2.25.0, it started to use a default items-per-page attribute of 20 (uib-pager.config and uib-pagination.config).  The old custom pagination generated the page numbers to display directly in the HTML.

To make the pages generate correctly, set $scope.pageSize, replace the 20 in the query with $scope.pageSize, and set the items-per-page attribute in the uib-pager or uib-pagination directive at the bottom of the HTML.

I will have a pull request up up soon for this.

**Comment by btabo** [comment]
Thanks it is works perfectly fine now ;)
