### ISSUE TITLE
Handle generator-jhipster version compatibility using engines.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#26263]
##### **Overview of the feature request**

We do compatibility checks using `generator-jhipster` version in dependencies or peerDependencies.
But a blueprint can be compatible with versions without depending on that version.

##### **Motivation for or Use Case**

Allow blueprints to depend on a generator-jhipster version while keeping compatible with others generator-jhipster versions on runtime.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by OmarHawk** [comment]
We also ran into  this situation recently. We tried to update from one generator-jhipster version to the other, but are using a blueprint, that is being marked as compatible with that old version (a new version already exists) 

While updating, we get to see an error message asking us to either update the blueprint, or the generator as the current blueprint may not be marked compatible with the new jh version. 
But if we update the blueprint to the required target version first, we would then run into the same error everytime using the jhipster command, as the blueprint would only be compatible with the new version, but jhipster is still on the old version. 

The other option is to use the `--skip-checks` option during the upgrade or to always use the `--skip-checks` from now on until the jhipster upgrade was done. But this not not favorable, as it may disables other desired checks as well...
