### ISSUE TITLE
Searching for boolean values produces no results

### ISSUE THREAD

**Issue by roblight** [jhipster/generator-jhipster#2631]
Searching for `Boolean` values doesn't seem to work. The URL `http://localhost:8080/api/_search/users/true` returns HTTP 200 and no results.

Related #2622.

**Comment by pascalgrimaud** [comment]
it's about elasticsearch mechanism here, not an JHipster issue, IMO
Try this search : `field:true` or `field:false`

**Comment by roblight** [comment]
Yes you are correct!  Tested and working as described by @pascalgrimaud.  Thank you again!

n.b. For others sake, `field` is the name of your `@Entity`'s field.
