### ISSUE TITLE
Login/username with uppercase characters simply can't login...

### ISSUE THREAD

**Issue by amaillere** [jhipster/generator-jhipster#2632]
for example a twitter login (with upper chars) created with Spring Social can't login

this comes from ee2540c26d42b8ffaae0dd1cf0dcc4b09310d922

but nothing prevents the creation of usernames with Uppercase chars...

**Comment by amaillere** [comment]
modifying UserService to lowercase every Login field before save did the trick, 

it worked with automated tests except:
 SocialServiceIntTest.testCreateSocialUserShouldCreateUserWithSocialLoginWhenIsTwitter:232
(comparison should be isEqualToIgnoringCase)
others tests I did myself were OK

@jdubois should I make a PR or was it on purpose for some reason?

**Comment by moifort** [comment]
@amaillere yes make a PR, I will take a look.

**Comment by amaillere** [comment]
I also tested a minor modification that lowercase username in SocialService.getLoginDependingOnProviderId

it works as well

**Comment by amaillere** [comment]
done... with the second solution
The first one has more consequences and design choices to make.

**Comment by deepu105** [comment]
Closed via #2637
