### ISSUE TITLE
[ jhipster.github.io] Get module information from npmjs

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2633]
By using the info from the package.json that we can get on registry.npmjs.org, we could reduce the information in modules.json to just a short name and a npm package name  for jhipster.github.io
See http://registry.npmjs.org/generator-jhipster-basic-auth/latest
We could also output the latest module version available on jhipster.github.io

**Comment by deepu105** [comment]
@cbornet may be you should try it out in the new revamped site first https://github.com/jhipster-redesign/jhipster-redesign.github.io

**Comment by cbornet** [comment]
OK. I will PR on your project if you're OK

**Comment by deepu105** [comment]
100 % ok

**Comment by cbornet** [comment]
Arf ! The registry doesn't set the CORS headers : https://github.com/npm/npm-registry-couchapp/issues/108. Is it ok to use an online-proxy ?

**Comment by deepu105** [comment]
Not sure man, is it worth if it is that complicated?

Thanks & Regards,
Deepu

On Thu, Jan 14, 2016 at 6:50 PM, Christophe Bornet <notifications@github.com

**Comment by cbornet** [comment]
It's not complicated : https://cors-anywhere.herokuapp.com/registry.npmjs.org/generator-jhipster-basic-auth/latest (will not work from a browser address bar)

**Comment by cbornet** [comment]
If you want to have a look : http://cbornet.github.io/modules/marketplace.html (not finished)

**Comment by deepu105** [comment]
But im able to hit the original nom registry itl and see the json content,
why do you want CORS here? Am i missing something

**Comment by deepu105** [comment]
Ok im just being stupid i guess, got it :)

**Comment by deepu105** [comment]
+1

**Comment by cbornet** [comment]
This is now done.
@jdubois can you check if it's ok for you ? http://cbornet.github.io/modules/marketplace.html

**Comment by deepu105** [comment]
Can you update the tiles on home page as well?

**Comment by cbornet** [comment]
Yes I just saw that :smile: . Working on it

**Comment by cbornet** [comment]
@deepu105 @jdubois can you review the PR ?

**Comment by jdubois** [comment]
OK that's not complicated to use, but this "proxy" is really asking for trouble: I'm pretty sure this is going to fail at some point in time.
I'd rather stay with our current system, it's very simple and doesn't need any maintenance from our part.

I know that I'm not being fun here, but I really don't want to have any maintenance to do, as (like all of you) I'm just doing this in my spare time.

**Comment by cbornet** [comment]
Yes, I understand. So, we need to wait that they add CORS headers to npm-registry but since the issue is 2 years old I don't have much hope...
The other possibility is to get the package.json from github. We could have a field for the path to fetch.

**Comment by deepu105** [comment]
Oops I might have jumped the gun and merged it, any way can revert if
needed.

As Julien says im also worried that it might fail at some point.

Does they allow JsonP for this, if so we can do that instead of doing proxy

**Comment by cbornet** [comment]
At least GH correctly sets the CORS so it can be used.
As for JSONP, it doesn't seem possible : https://github.com/npm/npm-registry-couchapp/issues/157

**Comment by cbornet** [comment]
I made a PR to use a package.json file path. Can you review ?

**Comment by deepu105** [comment]
Im closing it here as we will track it in https://github.com/jhipster-redesign/jhipster-redesign.github.io/issues/4 and we are having a discussion there
