### ISSUE TITLE
Blueprint POST_WRITING Hook Fails to Modify pom.xml

### ISSUE THREAD

**Issue by hide212131** [jhipster/generator-jhipster#26385]
##### **Overview of the issue**

After generating `pom.xml` through Blueprint POST_WRITING, I am attempting to replace the contents of the `frontend-maven-plugin` using a Blueprint ([at this line](https://github.com/hide212131/generator-jhipster-llm/blob/a6dbece569076907bd90528dfbc1c156e1dede3f/generators/llamacpp/generator.mjs#L107)). However, since JHipster 8.3.0, an incomplete `pom.xml` has started to appear, and attempts to replace its contents have been failing.

##### **Motivation for or Use Case**

I feel that the behavior of the POST_WRITING hook in JHipster 8.3.0+ might be different from its previous versions.

##### **Reproduce the error**

Write code such as `this.editFile('pom.xml', content => {`, and inspect the contents using a debugger.
<img width="933" alt="スクリーンショット 2024-06-09 19 32 06" src="https://github.com/jhipster/generator-jhipster/assets/3602892/7a6d7154-9d60-463f-9e3b-c932eb6b990b">

##### **Related issues**

It is unclear if this is related, but the issue may be connected to a refactor done in the following pull request: https://github.com/jhipster/generator-jhipster/pull/25733, where some of the core code affecting post file generation processing was moved.

##### **JHipster Version(s)**

8.3.0 or later

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "jhipster",
    "blueprints": [
      {
        "name": "generator-jhipster-llm",
        "version": "0.1.0"
      }
    ],
    "cacheProvider": "no",
    "clientFramework": "react",
    "creationTimestamp": 1717921222125,
    "databaseType": "no",
    "devServerPort": 9060,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": true,
    "entities": [],
    "jhipsterVersion": "8.5.0",
    "languages": [
      "en"
    ],
    "nativeLanguage": "en"
  },
  "generator-jhipster-llm": {
    "llmFramework": "springai",
    "llmLibrary": "llamacpp",
    "llmModelName": "mistral"
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "21" 2023-09-19
OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15)
OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

git version 2.44.0

node: v20.10.0
npm: 10.2.3

Docker version 25.0.5, build 5dc9bcc

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

This is a backend issue, hence browser and operating system specifics are not directly relevant.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
`frontend-plugin` is added in [maven:frontend-plugin](https://github.com/jhipster/generator-jhipster/blob/main/generators/maven/generators/frontend-plugin/generator.ts) generator.
Some generators will be executed before it, others will execute after it. The best bet is to blueprint this generator.

**Comment by hide212131** [comment]
@mshima Thank you. Once I placed the blueprint generator in a directory structure that matched the existing one, as shown [here](https://github.com/hide212131/generator-jhipster-llm/commit/d72ef95b18155b4b2ee9b8b2ec4228799ca4123f#diff-408ce435cd14a9fdb5f602e8aae9f552dc944feb33f33fdca13ccd6e6e5aa770), the `pom.xml` processed by the `maven:frontend-plugin` started to appear. 

However, as the structure has become somewhat difficult to understand, I would prefer to handle this within the custom generator, much like the previous code. Is there a way to ensure the order of execution, such as using dependsOnJHipster('maven:frontend-plugin')?

It appears that this issue is not a bug, so I am thinking of closing it.

**Comment by mshima** [comment]
> @mshima Thank you. Once I placed the blueprint generator in a directory structure that matched the existing one, as shown [here](https://github.com/hide212131/generator-jhipster-llm/commit/d72ef95b18155b4b2ee9b8b2ec4228799ca4123f#diff-408ce435cd14a9fdb5f602e8aae9f552dc944feb33f33fdca13ccd6e6e5aa770), the `pom.xml` processed by the `maven:frontend-plugin` started to appear.
> 
> However, as the structure has become somewhat difficult to understand, I would prefer to handle this within the custom generator, much like the previous code.

It should be possible to create an api to delay the execution:
```
this.delayTask(({ application }) => {
  this.editFile(...);
});
```

Not sure this is a good solution.

> Is there a way to ensure the order of execution, such as using `dependsOnJHipster('maven:frontend-plugin')`?

In this case `maven:frontend-plugin` is conditional on clientFramework, so no. `dependsOnJHipster` only works in `beforeQueue` for non conditional composing.

**Comment by mshima** [comment]
@hide212131 you can make your llamacpp to depend on frontend-plugin if clientFramework and build tool are already set at this point.
