### ISSUE TITLE
JHipster Application Defaults to LTR Instead of RTL for Arabic Language

### ISSUE THREAD

**Issue by root046** [jhipster/generator-jhipster#26400]
##### **Overview of the issue**

I'm working on a simple project using JHipster with React for the frontend and have set Arabic as the default language. However, I'm encountering an issue where the site initially loads in Arabic but with LTR (Left-to-Right) orientation. If I reselect Arabic from the language options (even though it's already set to Arabic), the orientation correctly switches to RTL (Right-to-Left).

To address this, I tried modifying the `index.html` file by setting `<html class="no-js" lang="ar-ly" dir="rtl">`, intending for the site to default to RTL on the first load. Despite this, when inspecting the page, I notice that it reverts to `<html class="no-js" lang="ar-ly" dir="ltr">`, suggesting something overrides my settings.

I suspect there might be JavaScript or a configuration within JHipster that dynamically sets the `dir` attribute based on the selected language, overriding my manual settings in `index.html`. I've set the title language in JHipster to Arabic, hoping it would enforce RTL, but the issue persists.

##### **Motivation for or Use Case**

This is a bug for me because I need the site to load with RTL orientation by default when Arabic is set as the default language. Manually reselecting the language every time to get the correct orientation is not user-friendly.

##### **Reproduce the error**

1. Generate a JHipster project with React as the frontend framework.
2. Set Arabic as the default language.
3. Run the project and observe that the site loads in Arabic but with LTR orientation.
4. Reselect Arabic from the language options to see the orientation switch to RTL.

##### **Related issues**

I have searched for similar issues but could not find any that address this exact problem.

##### **Suggest a Fix**

It seems that the language setting in JHipster dynamically sets the `dir` attribute. Ensuring that the correct `dir` attribute is set based on the default language in the initial load would solve this issue.

##### **JHipster Version(s)**

`8.5.0`

##### **JHipster configuration**

```bash
WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
    If you want to execute the locally installed generator-jhipster, run: npx jhipster

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.5.0

Welcome to the JHipster Information Sub-Generator



fin-manage@0.0.1-SNAPSHOT C:\Users\bader\OneDrive\Desktop\jHipster
`-- generator-jhipster@8.5.0



##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "XX",
    "buildTool": "maven",
    "cacheProvider": "caffeine",
    "clientFramework": "react",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "darkly",
    "clientThemeVariant": "dark",
    "creationTimestamp": 1718044006189,
    "cypressAudit": true,
    "cypressCoverage": null,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 9060,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "entities": [],
    "feignClient": null,
    "jhipsterVersion": "8.5.0",
    "languages": [
      "ar-ly",
      "en"
    ],
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "ar-ly",
    "packageName": "com.xx.project",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [
      "enableSwaggerCodegen:true"
    ],
    "serviceDiscoveryType": false,
    "syncUserWithIdp": null,
    "testFrameworks": [
      "gatling",
      "cypress"
    ],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>


##### **Environment and Tools**

java version "17.0.10" 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.10+11-LTS-240, mixed mode, sharing)

git version 2.45.1.windows.1

node: v20.13.1
npm: 10.8.0

Docker version 26.1.1, build 4cf5afa

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>


</pre>
</details>


Congratulations, JHipster execution is complete!
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

without entities
##### **Browsers and Operating System**

- OS: Windows 10
- Browsers: Chrome, Firefox

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by emilpaw** [comment]
The issue was that the direction is determined based on the content of `locale` stored in session storage, but nothing is stored yet when the page is first loaded.
