### ISSUE TITLE
Unable to Create NaturalPerson Entity with Both father and mother Relationships Due to Duplicate Properties Error

### ISSUE THREAD

**Issue by carlos-farias** [jhipster/generator-jhipster#26419]
##### **Overview of the issue**

When trying to create a table called NaturalPerson that has relationships with both father and mother (both being NaturalPerson), JHipster throws the following error:

```
ERROR! An error occurred while running jhipster:bootstrap-application#checkProperties
ERROR! ERROR! You have duplicate properties in entity NaturalPerson: naturalPerson
Error: You have duplicate properties in entity NaturalPerson: naturalPerson
It seems that JHipster is not accepting having both father and mother relationships simultaneously.
```

##### **Motivation for or Use Case**

This is a bug because the NaturalPerson entity needs to have relationships for both father and mother to accurately represent a natural person in the data model. Removing either relationship allows the model to be created, but this is not a viable solution as it does not reflect the necessary real-world relationships.
##### **Reproduce the error**

1. Define the JDL with the NaturalPerson entity having both father and mother relationships.
2. Run JHipster to generate the entities.
3. Observe the error mentioned above.

Here is the relevant JDL section:
```
entity NaturalPerson {
}

relationship OneToOne {
    NaturalPerson{person} to Person
    NaturalPerson{father} to NaturalPerson
    NaturalPerson{mother} to NaturalPerson
}
```
##### **Related issues**

No similar issues were found in the open or closed issues.

##### **Suggest a Fix**

A potential fix might involve checking the JHipster generation logic to ensure it can handle multiple relationships of the same type to the same entity correctly. Specifically, the check for duplicate properties might need to be revised to allow for relationships like father and mother.

##### **JHipster Version(s)**

Using JHipster version v8.4.0  and tested on v8.5.0

```
docker container run --rm -it -v "$PWD":/home/jhipster/app jhipster/jhipster jhipster
```
and 

```
docker container run --rm -it -v "$PWD":/home/jhipster/app jhipster/jhipster jhipster jdl eflipa-sca.jdl
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Was not generated.

##### **Browsers and Operating System**

This is a backend issue, so it is independent of the browser. Tested on Ubuntu 22.04 LTS.

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
You probably should use ManyToOne otherwise a father/mother will only have a single child:

```
entity NaturalPerson {
}

relationship OneToOne {
    NaturalPerson{person} to Person
}

relationship ManyToOne {
    NaturalPerson{father} to NaturalPerson
    NaturalPerson{mother} to NaturalPerson
}
```

**Comment by mshima** [comment]
OneToOne is currently bidirectional only, refer to https://github.com/jhipster/generator-jhipster/issues/26139.

**Comment by carlos-farias** [comment]
I am going to test it.  Thanks!

**Comment by mshima** [comment]
Seems to be resolved, closing.

**Comment by gerbsen** [comment]
I've tried to run a similar scenario with 8.6.0. I have two unidirectional one-to-one relationships like this: 

```
entity Citizen
entity Passport

relationship OneToOne {
  Citizen{newPassport} to Passport
  Citizen{oldPassport} to Passport
}
```

Which results in some strange `duplicate properties issue`

```
ERROR! An error occured while running jhipster:bootstrap-application#checkProperties
ERROR! ERROR! You have duplicate properties in entity Passport: citizen
Error: You have duplicate properties in entity Passport: citizen
    at BootstrapApplicationGenerator.checkProperties (file:///opt/homebrew/lib/node_modules/generator-jhipster/dist/generators/bootstrap-application/generator.js:136:31)
    at BootstrapApplicationGenerator.executeTask (file:///opt/homebrew/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:264:26)
    at env.queueTask.once (file:///opt/homebrew/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:238:56)
    at runLoop.add.once (file:///opt/homebrew/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:395:23)
    at Immediate.<anonymous> (/opt/homebrew/lib/node_modules/generator-jhipster/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:476:21)
make: *** [jdl] Error 1
```

The error is fixed if I do `Citizen{oldPassport} to Passport{foo}` & `Citizen{newPassport} to Passport{bar}` but I don't want the references in the Passport class.
