### ISSUE TITLE
The attempt to get 'anonymousUser' causes an 405 error.

### ISSUE THREAD

**Issue by worm333** [jhipster/generator-jhipster#2642]
By default, JHipster comes with "anonymousUser", when trying to get this user using api, for example:

curl -X GET --header "Accept: application/json" --header "X-CSRF-TOKEN: e2861624-b75c-427b-af4d-29486ae60a66" "http://localhost:8080/api/users/anonymousUser"

get an 405 error with response body
{
  "message": "error.methodNotSupported",
  "description": "Request method 'GET' not supported",
  "fieldErrors": null
}
Error occurs due to the fact that path variable :login is not matching with "anonymousUser"

JHipster Version:  3.5.3

**Comment by gmarziou** [comment]
Please follow [our guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#issue) when submitting an issue.

**Comment by deepu105** [comment]
That Jhipster version does not even exist.

**Comment by worm333** [comment]
I'm sorry about misinformation with version, actually version is 2.26.2

**Comment by deepu105** [comment]
Still not enough info to actually help you, if you follow our guidelines ill reopen this, or open new issue following our guideline https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue

**Comment by jdubois** [comment]
Well, I think I understand the issue: it's just that you can't get the "anonymousUser", and that's normal, this is not a "real" user, and you will get an error when trying to transform it to a real user.
This is a specific Spring Security user -> maybe we should make this more explicit, you are not supposed to use it directly
In a "normal" JHipster application, you should not see this user, as you need to be logged in to perform the API calls: this is one of the reasons you need to be logged in, of course.
