### ISSUE TITLE
Migration to Spring Web Flux with Eureka and Spring Cloud Gateway

### ISSUE THREAD

**Issue by germanicus9** [jhipster/generator-jhipster#26435]
Hi,

I saw that for migration to  Spring Webflux I should get rid of Zuul and Ribbon and replace them with  Spring Cloud Gateway for routing and load-balancing.
Where are  microservices  registered? Because they can be found on  jhipster-registry and Spring Cloud Gateway as well.

In a **new generated jhipster app** I have:
![image](https://github.com/jhipster/generator-jhipster/assets/172026452/b0f734ba-80f5-4ced-94fb-6711abaaae77)
What is this TokenRelay, is somewhere implemented?

![image](https://github.com/jhipster/generator-jhipster/assets/172026452/ddf39838-3274-4757-b8a6-6c9875813922)
Even that RouteLocator and DiscoveryClient are underlined in red (cannot find the beans), seems to work. Is this a common false alarm?

Thank you!

**Comment by mshima** [comment]
> Where are microservices registered?

Registering is done by spring-boot.

> What is this TokenRelay, is somewhere implemented?

TokenRelay filter is provided by spring-cloud-gateway.

> Is this a common false alarm?

If it’s working is false positive.

This should be posted in stackoverflow to have a broader spring-boot users audience.
