### ISSUE TITLE
Make entity angular controllers and router ui states more unique to avoid name clashes

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2645]
* **Overview of the issue and Motivation for or Use Case**

When generating an entity, lets say Workplace, the following angular controllers are generated for the entity views:
```
WorkplaceController
WorkplaceDeleteController
WorkplaceDetailController
WorkplaceDialogController
```

The ui router state used is `workplace`.

This is a problem when I would like to create general page representing a Workspace. Then the WorkplaceController and the ui router state `workplace` is occupied.

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
 ```
{
    "relationships": [],
    "fields": [],
    "changelogDate": "20160118060622",
    "dto": "no",
    "service": "no",
    "pagination": "no"
}
```

* **Suggest a Fix**

Change the name of the controllers to

 ```
EntityWorkplaceController
EntityWorkplaceDeleteController
EntityWorkplaceDetailController
EntityWorkplaceDialogController
```

and ui router state to: `entity.workplace`.

**Comment by deepu105** [comment]
@andidev but in many cases we would end up customizing the entity page based on our need rite? so in most cases we would be changing what is generated and in very few cases we would want to name something similar to an entity, but for such cases isnt it better to rename the entity manually?

Having keyword entity all over seems very ugly to me. Its just my perspective and i could be wrong.

**Comment by andidev** [comment]
I guess it depends on how you use jhipster. I try to keep the generated admin gui unchanged so I can benefit from jhipster updates.

Maybe a better name would be `AdminWorkplaceController` or `ManageWorkplaceController`. 

I have now encountered a name clash 5 entities out of 20. So the issue is there for me. And I don't want to modify the admin entity gui since I want to keep them for the advanced admin users, though later on I may want to modify them as well but I would still need an admin view and a another non admin view of the entity. It feels like this must be a common situation.

**Comment by deepu105** [comment]
I can understand, lets see what others have to say

Thanks & Regards,
Deepu

**Comment by atomfrede** [comment]
@andidev I think we may have a similar situation (didn't really started my project) but I'll have a public view of some entities and the admin/manager view. Both views are completly different so I like your proposal to seperate the generated ui more.

**Comment by jdubois** [comment]
At least we should have a prefix for the admin pages.
For the entity pages, so are supposed to be "your" code in the end, so they are the ones that shouldn't have a prefix (or have an optional one).
This would be a major change, of course.

**Comment by andidev** [comment]
@jdubois 
Maybe we should not see this as a prefix and rather see it as the names are curretly incorrectly named. The current views that is generated are views that allows the user to **manage** the Entity. Why should'nt the word manage be used in the naming then?

We have actually two types of usecases here:
1. The JHipster user modifies the generated views completely

2. The JHipster user keeps the generated views for admin and add new views for presentation for non admin users.

**Today**
User number 1 handles updates of the entity views with manual work
User number 2 needs to rename the entity views manually to be able to use the entity name in their presentation non admin views and handle updates of the entity views with manual work.

**With this fix**
User number 1 handles updates of the entity views with manual work *STILL SAME PROCESS*
User number 2 does not need to rename the entity views manually nor handle updates of the entity views with manual work *LOT OF LESS WORK*

**Comment by andidev** [comment]
I'm ready to work on this if we all agree on it. Otherwise let's close it.

**Comment by cbornet** [comment]
:+1: something should be done. Either that or set existing angular routes to reserved entity names (for instance if you name your entity "Site" you will have a conflict)

**Comment by gmarziou** [comment]
Could we avoid name conflicts by using separate angular module for entity code?

**Comment by andidev** [comment]
Unfortunately it is not supported by angular 

http://stackoverflow.com/questions/13406791/modules-and-namespace-name-collision-in-angularjs

**Comment by gmarziou** [comment]
Good point, I forgot about this. New DI system in Angular 2 solves this, in the mean time your prefix suggestion is the way to go I think.

**Comment by andidev** [comment]
So how about calling the entity (e.g. with a name Workplace) related files and controllers the following:

related folder:
```
workplace-management
```

related files:
```
workplace-management.controller.js
workplace-management.js
workplace-management-delete-dialog.controller.js
workplace-management-delete-dialog.html
workplace-management-detail.controller.js
workplace-management-detail.html
workplace-management-dialog.controller.js
workplace-management-dialog.html
workplace-management.html
```

related controllers:
```
WorkplaceManagementController
WorkplaceManagementDeleteController
WorkplaceManagementDetailController
WorkplaceManagementDialogController
```

related states:
```
workplace-management
workplace-management.detail
workplace-management.new
workplace-management.edit
workplace-management.delete
```

It would follow the naming convention for the user management view.
The drawback is that if someone wants to change the views from not being management views they will have to change all names manually but still if some one does that there is a lot of refactoring to do either way.

**Comment by atomfrede** [comment]
I like your proposal. Makes it much easier for keeping the default management stuff while adding some nice views for specific entites in addition.

**Comment by jdubois** [comment]
Yes, that would avoid the name clashes -> not a perfect solution, but with AngularJS 1.x there isn't much choices

**Comment by andidev** [comment]
So will we merge this if I'll fix a PR?

**Comment by jdubois** [comment]
As far as I'm concerned this is a good idea and should be merged -> this is quite an important change, thus, so I'd be happy to have other people feedback

**Comment by deepu105** [comment]
Im ok with it since most of you agree

**Comment by andidev** [comment]
@team 
Not sure about this but maybe I should add some code that deletes the old entity files when entities are regenerated. Otherwise people upgrading their entities have to do delete them manually.

**Comment by deepu105** [comment]
@andidev,

I guess this will be a big breaking change for existing users and merging
with existing code will be very tough so I dont think anyone should upgrade
existing app to this without deleteing the existing webapp folder or
atleast the entity sub folder. SO may be document the steps to do in
release notes rather than adding more remove code (ps: @jdubois our
removefile list keeps on increasing, when should we stop removing these
files? may be we should do a release after the next one to just remove the
remove files??)

Thanks & Regards,
Deepu

**Comment by cbornet** [comment]
I think we should automatically regen all existing entities at the end of the main generator. This could include clean up before regen.
