### ISSUE TITLE
Migrate to ESLint v9

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#26471]
##### **Overview of the feature request**

ESLint v9 requires non trivial changes.

- [ ] internal (transform) blocked by https://github.com/import-js/eslint-plugin-import/issues/2556
- [x] blueprints (https://github.com/jhipster/generator-jhipster/pull/26476, https://github.com/jhipster/generator-jhipster/pull/26491)
- [x] angular
- [x] react
- [x] vue

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@mshima A couple of PRs have been merged that are related to this. Is there still more work to do? If so, can some of the items in the description be checked off?

**Comment by mshima** [comment]
@mraible still much do be done.
Monorepository/workspaces support is having this problem:
https://github.com/jhipster/generator-jhipster/actions/runs/9620349477/job/26538382197

So prettier, husky and eslint needs to be split into separated generators to make easier to handle monorepositories.
