### ISSUE TITLE
Bulk Import/export of entities by CSV files

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2648]
A commonly asked featured is to have CSV import and export features of entities. I think this would be interesting to have it in the main generator with endpoints that can take file or text/csv data (REST + Json is sometimes not performant enough) and buttons in the angular views to import/export the data. But if there is not enough interest to do it in the main generator, I can do it as a module.

**Comment by deepu105** [comment]
yes its a very good feature. :+1: either in main generator as default or as module

Actually http://ui-grid.info/docs/#/tutorial/312_exporting_data_complex has these features, may be we could refer that

**Comment by pascalgrimaud** [comment]
Yes ! :+1: too !

**Comment by gmarziou** [comment]
I'm not fully convinced by CSV exporting done by a JS grid, in my experience you'll get better performance from server download unless of course you want to be able to select which rows to export.

BTW, what about replacing our entity table by a real grid  with better look and more features like either ui-grid you mentioned or [ag-grid](https://www.ag-grid.com/) ?

**Comment by mraible** [comment]
I've used this on a project before:

https://github.com/asafdav/ng-csv

**Comment by deepu105** [comment]
I used Ui grid on a JHipster project and i was satisfied with performance
and quality of the csv download and pdf rather than doing a server side
option, but if i wanted excel etc i might go sever side

**Comment by cbornet** [comment]
@deepu105 does the csv download work with our server-side pagination ?

**Comment by deepu105** [comment]
I didn't use server side pagination with Ui grid coz it was handling 50,000
rows without a sweat so client side pagination was more than sufficient,
reading ui grid docs they do support server side pagination and sort

**Comment by jdubois** [comment]
If ng-csv can work with our server-side pagination, then that would be the best solution to the problem: no server-side change to do, only add the directive when it's needed, I love it!

**Comment by cbornet** [comment]
But ng-csv is a small project compared to ui-grid and ag-grid.
It seems quite simple to use ui-grid with spring server-side pagination : https://github.com/naory/spring-data-rest-ng-grid-example
ui-grid and ag-grid also look much more powerful than bootstrap.

**Comment by jdubois** [comment]
OK, then if this can be easily achieve by using one of those 3rd party libs I don't think we should do anything in the project.
It's our usual job -> we make it easy to integrate those, so if people need this it's easy for them to add

Then it would be nice to have this documented somewhere, I think a "tip" on the website would be great!

**Comment by lourai** [comment]
Hi, it'll be a nice function if built-in !

Remember you can do it with liquibase :
- add your csv in a directory
- manually create a changelog to load data : 
...
<loadData encoding="UTF-8" file="config/liquibase/csv/<yourfile>.csv" separator=";" tableName="<table_name_not_entity:D>"> 
...

I'm using it for legacy data transfer for example, but even for every data patch ! Remember liquibase is async, so for large data file, could take time at startup so you get strange behavior on front side.

Remember me another very usefull related function : export to csv or excel (could be very easy, ex : http://jsfiddle.net/lesson8/jWAJ7/light/).

**Comment by jdubois** [comment]
OK I'm closing this as I guess we have settled this:

- For imports, use Liquibase. This is what we already do for users, for example.
- For exports, use a third-party JS library that does the trick -> if someone has experience with one that works well, please submit a tip

**Comment by cbornet** [comment]
OK. 
One note though: the idea is to give the end user the possibility to import data, not the developper. So liquibase can't be used here and you have to use a 3rd party lib like for exports.

**Comment by singhfulda** [comment]
Is there any update on this?
I would like to have a exposed api for CSV/XML Imports from end users.

**Comment by jdubois** [comment]
No, once a ticket is closed we stop working on it

**Comment by ruddell** [comment]
@singhfulda I recommend [PrimeNG's Table component](https://www.primefaces.org/primeng/#/table/export) for easily exporting data to CSV
