### ISSUE TITLE
Broken links with the new website redesign

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2652]
I'm assigning this to @deepu105 as he's the one who did the redesign.

We have some broken links, for example at http://jhipster.github.io/2014/10/13/jhipster-release-1.4.0.html this points to http://jhipster.github.io/creating_an_entity.html

- we need to redirect those old URLs to the new ones
- we need to update all the links -> I guess a good search/replace should do the trick
- @deepu105 I should be able to give you access to our "Google Webmaster tools" account, that gives the 404 errors, but this is always a few days late

**Comment by deepu105** [comment]
I guess i missed that folder in my regex search will update

Thanks & Regards,
Deepu
