### ISSUE TITLE
Unable to access microservice via swagger

### ISSUE THREAD

**Issue by eapriansyah** [jhipster/generator-jhipster#26543]
##### **Overview of the issue**

Cannot access microservices via swagger.
The use cases are default React FE, Default GW, microservice with DB and microservice without DB.
Service Discovery using Eureka

Appears in Jhipster Registry but not in Swagger definition

![image](https://github.com/jhipster/generator-jhipster/assets/1936249/163852bd-144e-46cc-b317-061568f37b56)

![image](https://github.com/jhipster/generator-jhipster/assets/1936249/73d405c9-68f5-432a-9b5e-4334d7af3bdc)

##### **Motivation for or Use Case**

Didn't happen before 8.5.0.

##### **Reproduce the error**

Install four applications by default using local docker. Access the swagger screen. Service definition not found.

##### **JHipster Version(s)**

8.5.0, 8.6.0

##### **JHipster configuration**

```
gw@0.0.1-SNAPSHOT D:\apps\projects\nappl\ntest\nfe
`-- generator-jhipster@8.4.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "baseName": "gw",
    "buildTool": "maven",
    "cacheProvider": "redis",
    "clientFramework": "react",
    "clientTestFrameworks": [],
    "clientTheme": "none",
    "creationTimestamp": 1708182900239,
    "databaseType": "no",
    "devDatabaseType": "no",
    "devServerPort": 9060,
    "enableGradleEnterprise": null,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [],
    "feignClient": false,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.4.0",
    "languages": [
      "en",
      "id"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "id.atiila",
    "prodDatabaseType": "no",
    "reactive": true,
    "searchEngine": false,
    "serverPort": "8110",
    "serverSideOptions": [],
    "serviceDiscoveryType": "eureka",
    "skipServer": true,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "21.0.1" 2023-10-17
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)

git version 2.33.0.windows.2

node: v20.11.1
npm: 10.2.4

Docker version 26.0.0, build 2ae903e

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

----------------------------------------------------------------------

```
gw@0.0.0 D:\apps\projects\nappl\ntest\ngw
`-- generator-jhipster@8.6.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "baseName": "gw",
    "buildTool": "maven",
    "cacheProvider": "redis",
    "creationTimestamp": 1708182900239,
    "databaseType": "no",
    "devDatabaseType": "no",
    "enableGradleEnterprise": null,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [],
    "feignClient": false,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.6.0",
    "languages": [
      "en",
      "id"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "id.atiila",
    "prodDatabaseType": "no",
    "reactive": true,
    "searchEngine": false,
    "serverPort": "8110",
    "serverSideOptions": [],
    "serviceDiscoveryType": "eureka",
    "skipClient": true,
    "skipUserManagement": true,
    "syncUserWithIdp": false,
    "testFrameworks": [],
    "websocket": false
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "21.0.1" 2023-10-17
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)

git version 2.33.0.windows.2

node: v20.11.1
npm: 10.2.4

Docker version 26.0.0, build 2ae903e

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>
----------------------------------------------------------------------

```
service-los@0.0.0 D:\apps\projects\nappl\ntest\service-nlos
`-- generator-jhipster@8.6.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "authenticationType": "oauth2",
    "baseName": "serviceLos",
    "buildTool": "maven",
    "cacheProvider": "redis",
    "creationTimestamp": 1708185015680,
    "databaseType": "no",
    "devDatabaseType": "no",
    "enableGradleEnterprise": null,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [],
    "feignClient": true,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.6.0",
    "languages": [
      "en",
      "id"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "id.atiila",
    "prodDatabaseType": "no",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8741",
    "serverSideOptions": [],
    "serviceDiscoveryType": "eureka",
    "skipClient": true,
    "skipUserManagement": true,
    "syncUserWithIdp": false,
    "testFrameworks": [],
    "websocket": false
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "21.0.1" 2023-10-17
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)

git version 2.33.0.windows.2

node: v20.11.1
npm: 10.2.4

Docker version 26.0.0, build 2ae903e

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

----------------------------------------------------------------------

```
central@0.0.0 D:\apps\projects\nappl\ntest\ncentral
`-- generator-jhipster@8.6.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "authenticationType": "oauth2",
    "baseName": "central",
    "buildTool": "maven",
    "cacheProvider": "redis",
    "creationTimestamp": 1711377672657,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [],
    "feignClient": true,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.6.0",
    "languages": [
      "en",
      "id"
    ],
    "lastLiquibaseTimestamp": 1711380522000,
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "id.atiila",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8111",
    "serverSideOptions": [],
    "serviceDiscoveryType": "eureka",
    "skipClient": true,
    "skipUserManagement": true,
    "syncUserWithIdp": false,
    "testFrameworks": [],
    "websocket": false
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "21.0.1" 2023-10-17
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)

git version 2.33.0.windows.2

node: v20.11.1
npm: 10.2.4

Docker version 26.0.0, build 2ae903e

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Swagger endpoints are scanned at runtime by the UI.
So check your browser console and network history, it may have information about the error.

**Comment by eapriansyah** [comment]
Sorry, late response.

The browser is in incognito mode.
Results when logged in,
![image](https://github.com/jhipster/generator-jhipster/assets/1936249/33b2f062-6b00-4020-948a-c82e27ec8a6e)

Gateway screen
![image](https://github.com/jhipster/generator-jhipster/assets/1936249/c5de4108-670b-42d6-8325-6b10bccffba8)

Admin Docs screen.
![image](https://github.com/jhipster/generator-jhipster/assets/1936249/3cf9d261-a0ce-4d2d-9663-eb2a44accd40)

The following problems were detected..

![image](https://github.com/jhipster/generator-jhipster/assets/1936249/930fe22a-cb62-4756-87c7-c04b68df5282)
