### ISSUE TITLE
Discover modules automatically using npm search

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2660]
This is continuation of discussion at https://github.com/hipster-labs/jhipster-redesign.github.io/pull/4

We can use https://github.com/solids/npmsearch to get all Jhipster modules,so that module writers need not PR to the modules.json at all? we could maintain a moduleConfig map to mark verified generators and to blacklist any generator that might abuse the keyword

we can use the jhipster-module keyword to search like below 
http://npmsearch.com/query?fields=name,keywords,description,author,homepage,version&q=keywords:jhipster-module&size=20&start=0

this would give an array of all modules with each having below info

```
{  
         "author":[  
            "deepu8224"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "created":[  
            "2015-12-29T05:12:08.500Z"
         ],
         "repository":[  
            "git+https://github.com/deepu105/generator-jhipster-entity-audit.git"
         ],
         "description":[  
            "JHipster module to enable entity audit and audit log page"
         ],
         "name":[  
            "generator-jhipster-entity-audit"
         ],
         "homepage":[  
            "https://github.com/deepu105/generator-jhipster-entity-audit"
         ],
         "version":[  
            "1.0.4"
         ]
      },
```

for author it is giving the npm author name alone, there is no author url, but gives repo url and i guess we can use that to point to the authors github page so that might not be a big issue.

But I dont have a solution for dependency version which @cbornet added :( may be we could use the proxy he used to get it from npm for jhipster dependency version alone, so even if it fails module listing will still be present.

Coz with most plugin based systems there, yeoman, slush etc., they search using keywords to show what is available rather than asking plugin writers to PR for changes to directory, in the long run, when we have a lot of modules, may be we could run our own aggregator to find and index available modules

but till then this might be literally maintenance free for us as Module writers can update the info at their will without relying on us to merge PR on documentation sites.

If @jhipster/developers you guys agree I will make this change

**Comment by deepu105** [comment]
@jdubois i have some time this week can I do this?

**Comment by jdubois** [comment]
Yes of course, it looks like less maintenance work for us in the end.
Le 21 janv. 2016 1:51 AM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
Ok :)

Thanks & Regards,
Deepu
