### ISSUE TITLE
refresh access token spring webflux

### ISSUE THREAD

**Issue by germanicus9** [jhipster/generator-jhipster#26616]
Hello,

I have a jHipster Spring Boot Webflux app. and the next filter:

    public class OAuth2ReactiveRefreshTokensWebFilter implements WebFilter {

        private final ReactiveOAuth2AuthorizedClientManager clientManager;

        public OAuth2ReactiveRefreshTokensWebFilter(ReactiveOAuth2AuthorizedClientManager clientManager) {
            this.clientManager = clientManager;
        }

        public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
           return ReactiveSecurityContextHolder.getContext()
               .map(SecurityContext::getAuthentication)
               .filter(authentication -> authentication instanceof OAuth2AuthenticationToken)
               .cast(OAuth2AuthenticationToken.class)
               .flatMap(authentication -> {
                   String clientRegistrationId = authentication.getAuthorizedClientRegistrationId();
                   return clientManager.authorize(OAuth2AuthorizeRequest.withClientRegistrationId(clientRegistrationId)
                       .principal(authentication)
                       .attributes(attrs -> attrs.put(ServerWebExchange.class.getName(), exchange)).build())
                       .flatMap(authorizedClient -> {
                           OAuth2AccessToken accessToken = authorizedClient.getAccessToken();
                           if (isTokenExpired(accessToken)) {
                               return refreshAccessToken(authorizedClient, authentication, exchange, chain);
                           } else {
                               return chain.filter(exchange);
                           }
                       });
               }).switchIfEmpty(chain.filter(exchange));
        }

The behaviour is the following: 
this branch   _else {return chain.filter(exchange);}_ is called every time when I access the app and the access token is renewed automatically when the accessToken is expired. **How is this done, by whom?**
this branch _return refreshAccessToken(authorizedClient, authentication, exchange, chain);_ is never called. **Why?**
In concluzion apparently OAuth2ReactiveRefreshTokensWebFilter do nothing!?? What is the goal of this filter?

On the other hand if I stay 10 min in idle mode (no click) I receive 
_org.springframework.security.oauth2.client.ClientAuthorizationRequiredException: [client_authorization_required] Authorization required for Client Registration Id: oidc_ (probably for /api/account). Who throws this error and how should be controlled?
Is there any example?

Waiting for your comments. Thank you!!

**Comment by germanicus9** [comment]
According to [](https://www.baeldung.com/spring-webclient-oauth2)
Spring Security 5 refresh tokens automatically

On the other hand there is an AuthorizationCodeReactiveOAuth2AuthorizedClientProvider 
and which throws ClientAuthorizationRequiresException.
However I do not know when is triggered this  AuthorizationCodeReactiveOAuth2AuthorizedClientProvider.

**Comment by mraible** [comment]
If you're passing in an `offline_access` scope, you should get a refresh token and it should automatically renew when the access token expires. This blog post shows how I was able to make them work with just Spring Boot and Spring Cloud. https://auth0.com/blog/java-spring-boot-microservices/#Spring-Boot-Microservices-and-Refresh-Tokens

**Comment by germanicus9** [comment]
I cannot use offline_access scope because I do not use Okta. However Spring Security 5 do refresh access_token automatically.
The problem is  that I don't know how to control idle  period for OAuth2AuthorizationContext (throws ClientAuthorizationRequiredException after 10 min of inactivity) and also I do not understand what suppose to do with OAuth2ReactiveRefreshTokenWebFilter generated together with jhipster 8.4.9?

**Comment by mraible** [comment]
The `offline_access` scope is not specific to Okta. It should work with any OAuth 2.0 server.

**Comment by germanicus9** [comment]
Yes, but not work with my OIDC server unfortunately.
In AuthorizationCodeReactiveOAuth2AuthorizedClientProvider is stated: **Throws ClientAuthorizationRequiredException - in order to trigger authorization in which the OAuth2AuthrorizationRequestRedirectWebFilter will catch and initiate the authorization.**
Is somewhere any example in this respect?

**Comment by mshima** [comment]
@germanicus9 the answer is here https://github.com/jhipster/generator-jhipster/issues/26616#issuecomment-2206407657.
Increasing clock skew will force the token to be renewed in the timeframe before expiring.

**Comment by germanicus9** [comment]
Basically I redone the OAuth2ReactiveRefreshTokensWebFilter and now if  I walk through the the application the filter is called and access_token and refresh_token are changed accordingly. I use
`private boolean isTokenExpired(Oauth2AccessToken accessToken) {
return accessToken.getExpired()).minus(1, ChronUnit.Minutes).isBefore(Instant.now()`.
My problem is that in idle mode after refersh_token expiration I get an error.
Is not clear what does this
     ```
 @Bean
        authorizedClientManager.setAuthorizedClientProvider(
            <%= reactivePrefix %>OAuth2AuthorizedClientProviderBuilder
                .builder()
                .authorizationCode()
                .refreshToken(builder -> builder.clockSkew(Duration.ofMinutes(1)))
                .clientCredentials()
                .build()
        );
```
does refersh token automatically or what?

**Comment by mshima** [comment]
clockSkew is used to avoid token timestamp validation and the server timestamp differences conflict.
The token timestamp will be validated according the server timestamp plus the clockSkew.
If the token is expired according to the validation it will be renewed.
The default clockSkew provided by Spring Boot is 60s like the configuration.

So if clockSkew is half of token validation, the token will be refreshed after half of its lifetime.
I don't know if there is a downside in this approach, but IFAIK it's the only way to make Spring Boot refresh it automatically.
In any case this is quite technical question so you should post in stackoverflow to get a broader Spring Boot audience.
