### ISSUE TITLE
Generate front-end code only, based on Swagger

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2661]
In case people want to use an external back-end service, we could only generate our front-end code, based on the Swagger documentation.

For example:

- We have an external service, which uses some kind of proprietary technology
- The user has to code his own Spring MVC REST controller, using that specific technology -> that can't be generated, it depends on the underlying technology
- Based on that Spring MVC REST controller, we automatically have a Swagger documentation
- Use that Swagger documentation to generate the AngularJS front-end

**Comment by cbornet** [comment]
I don't understand the Spring MVC REST controller part : shouldn't the user use or write a swagger doc directly using swagger-editor for instance ?
There is already an Swagger AngularJS generator in swagger-codegen but maybe we could write a jhipster-angular generator so that it fits well with jhipster's existing code

**Comment by jdubois** [comment]
I didn't know about swagger-editor -> yes this could be a broader solution, of course
Then, the problem is to have our own generator, so that what is generated works fine with the rest of the JHipster application

**Comment by deepu105** [comment]
@jdubois are you talking of a new sub gen or a module?

**Comment by jdubois** [comment]
I hear more and more people asking for something like this, so it could be a sub-generator. Then there isn't much difference in the end.

**Comment by cbornet** [comment]
I hink we should start by making a swagger_codegen generator based on https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/TypeScript-Angular

**Comment by deepu105** [comment]
it looks like a module material to me rather than a sub gen

Thanks & Regards,
Deepu

On Thu, Jan 28, 2016 at 4:30 PM, Christophe Bornet <notifications@github.com

**Comment by cbornet** [comment]
Yes I was also thinking of making a module for the back-end based on the Feign swagger-codegen.

**Comment by cbornet** [comment]
There is a [swagger-codegen-maven-plugin](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen-maven-plugin) that can easily be added by a module to generate the code (maven only)

**Comment by jdubois** [comment]
OK if @cbornet you want to do a module of it we can start like this!

**Comment by cbornet** [comment]
The issue I see with the maven plugin is that it will not work with gradle.
We can also use http://generator.swagger.io but with that we don't have control over the generator version (it's the SNAPSHOT)
Eventually, we can use the swagger-codegen-cli jar
Tell me what you prefer.

**Comment by gmarziou** [comment]
@cbornet have you been successful running swagger codegen from cli? 

I could not make it work on my  project and the error messages were so cryptic that I gave up.

**Comment by cbornet** [comment]
@gmarziou yes, I use it all the time !  Which language were you using ?

**Comment by gmarziou** [comment]
I tried both tizen and java feign, it could be something specific to my API, I use @Api* annotations a lot.

**Comment by cbornet** [comment]
A swagger-codegen jhipster-angular generator would also be interesting with the jhipster backend when the user has added its own MVC requestmappings.

**Comment by cbornet** [comment]
Check https://github.com/cbornet/generator-jhipster-swagger-cli.
This is a very first version, lots to do but gives an idea

**Comment by deepu105** [comment]
Since module is started can we close this ticket?

**Comment by cbornet** [comment]
My module generates code for the backend not for the front. There is more work to do for the front as we need to do a swagger-codegen template

**Comment by jdubois** [comment]
Great idea @cbornet I'm looking forward to testing your module

**Comment by cbornet** [comment]
I forgot to add build dependencies...

**Comment by cbornet** [comment]
Fixed

**Comment by deepu105** [comment]
@cbornet is it done can we close this issue then?

**Comment by cbornet** [comment]
@deepu105 No, my module generates backend code and this issue is for front-end.
For the front, we need to make a swagger-codegen template. I don't think I am the right person to do it : I am not skilled in front end...

**Comment by cbornet** [comment]
Swagger-codegen already has a [type-script-angular](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-angular) generator. The code seems easy to integrate in an existing jhipster app. I'll have a look when I have time.

**Comment by cbornet** [comment]
I guess the module should compile the ts directly since the rest of the app is in js ? What do you front-end experts think ?

**Comment by deepu105** [comment]
if its in ts better keep it that way and use a gulp task to compile as we
should be migrating to ts at some point

Thanks & Regards,
Deepu

**Comment by cbornet** [comment]
Shouldn't ts support be driven by the main generator. ?
Meanwhile, I have found https://github.com/wcandillon/swagger-js-codegen that generates pure js angular code. Maybe we can use that. I will integrate it to my module. If you can then test it and give your feedback ?

**Comment by cbornet** [comment]
[Here](https://gist.github.com/cbornet/86d5765521094ecccffb) is some code generated by swagger-js-codegen (for the swagger petstore)

**Comment by cbornet** [comment]
The module now generates also front-end code.

**Comment by cbornet** [comment]
Tip : configure a springfox docket on your non-entity request mappings (using springfox group). Then you can use the module to generate angular code for your own api endpoints !

**Comment by cbornet** [comment]
@jdubois Can you test the latest version of the module (0.3.3) ? It works correclty on my side with session auth and CSRF token. If it responds to the need, maybe we can close this issue and follow feature requests and bugs in the module project.

**Comment by jdubois** [comment]
I'm sorry I don't have the time right now -> @PierreBesson can you test this?

**Comment by PierreBesson** [comment]
Yes I will try it now.

**Comment by PierreBesson** [comment]
@cbornet, for the front-end generator I have an error, it can not retrieve the client.module.js file.
Anyway, this is good that this work, it shows that we can generate REST clients from a Swagger docs and integrate them to JHipster.
However the style of the generated code differs a lot from JHipster's usual code. For the back-end client it is not using Spring RestTemplate and for the front-end client it is not using Angular $resource.
Maybe we should do this code generation ourselves using yeoman so that we can achieve good integration with JHipster.

**Comment by cbornet** [comment]
@PierreBesson 
* as for the front this is indeed not JHipster style. To enhance it, I guess we would have to make a JHipster swagger-codegen template
* Can you open an issue for the bug you have ?
* As for the back, I find feign much nicer than RestTemplate ! Even spring-cloud uses Feign : http://projects.spring.io/spring-cloud/spring-cloud.html#spring-cloud-feign

**Comment by PierreBesson** [comment]
If we keep this generator in a module it does not really matter if we use yeoman or another tool as the generator. Swagger-codegen is already very popular with over 1500 stars it makes sense to use it.

About Feign, I didn't know about it, it looks quite good especially in a microservice context. It seems that it can do [so many things](https://jmnarloch.wordpress.com/2015/08/19/spring-cloud-designing-feign-client/) and integrate with other parts of the netflix stack (Eureka, Zuul).
But if we are going to use it, shouldn't we use the Spring Cloud annotations ?

**Comment by cbornet** [comment]
Spring cloud annotations look awesome and your link is really interesting but I guess this is reserved for micro-services.

**Comment by gmarziou** [comment]
Today, I sucessfully generated a feign client using swagger-codegen against a JHipster API, I found that I had to tweak ApiClient classfor correctly setting up Jackson for seralizing/deserializing LocalDateTime even though I was using java8 only option.

I used it from a spring boot command line app.

I found  that it does a good job especially when using @ApiModel, @ApiParam, ... annotations as the are directly used to create model class names and even javadoc comments.

I think JHipster should use these annotations to provide better doc and better code generation.

**Comment by cbornet** [comment]
@gmarziou If you use the [module](https://github.com/cbornet/generator-jhipster-swagger-cli) it is fixed in the latest version by mapping the swagger datetime type to ZonedDateTime. If you're not,  you can use ```--type-mappings DateTime=ZonedDateTime,Date=LocalDate --import-mappings ZonedDateTime=java.time.ZonedDateTime,LocalDate=java.time.LocalDate``` to force the correct mapping..

**Comment by cbornet** [comment]
@gmarziou as for documenting with swagger annotations, it's already possible on entity fields with the "javadoc" field. 
We could also annotate the REST mappings.

**Comment by gmarziou** [comment]
I did not use your module, sorry I forgot about it. I will try it though as the authentication part is well covered.

**Comment by cbornet** [comment]
As for the REST mappings we could set nice definitions such as "Create a new foo" instead of "createFoo", have nicer operationId for generated code ("createFoo" instead of "createFooUsingPOST") and nicer definition of method parameters ("Foo to create" instead of "foo").
The code would look like this
```java
    /**
     * POST  /foos-> Create a new foo.
     */
    @RequestMapping(value = "/foos",
        method = RequestMethod.POST,
        produces = MediaType.APPLICATION_JSON_VALUE)
    @ApiOperation(value = "Create a new foo", nickname = "createFoo")
    @Timed
    public ResponseEntity<Foo> createFoo(@ApiParam("Foo to create") @Valid @RequestBody Foo foo) throws URISyntaxException {
```
If you're all OK, I can do the PR.
As for the domain, since it's already possible to use the "javadoc" field, I think we can keep it as is, unless you think we should have default definitions if javadoc is not present.

**Comment by gmarziou** [comment]
This PR would be great, I'm not sure what you mean by the "javadoc" field.

I played with your module, it's much better than running the swagger-codegen manually.
I would have liked to be able to generate the code in a new module with its own pom.xml but that 's easy to do anyway.

**Comment by cbornet** [comment]
See [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/src/main/java/package/domain/_Entity.java#L37). javadoc is a field for entity and entity fields that will insert Javadoc and swagger annotations in the domain classes. It's mainly used with jhipster-uml, you don't have yeoman questions for this.
I thought about generating maven modules but I it feels like more work to do it cleanly. Also it would need to be done with gradle which I don't know very well. If you have ideas about it don't hesitate to open issues and PR. When I have time I will put the project in hipster-labs.

**Comment by gmarziou** [comment]
I see, I don't use jhipster-uml.
I think that even with classic jhipster where we don't have the javadoc field we should have an `@ApiModel`annotation with some placeholder text for description just to give an example.

**Comment by deepu105** [comment]
+1 for api modal annotation

**Comment by jdubois** [comment]
Yes but that means everyone will have those annotations, including people not using Swagger. I'm not totally happy with this, but I don't see another solution.

**Comment by deepu105** [comment]
is this still open?

**Comment by cbornet** [comment]
I propose to close and follow issues and feature requests in the module.

**Comment by deepu105** [comment]
Ok

**Comment by jdubois** [comment]
So let's close this :-)
