### ISSUE TITLE
jhipster-dependencies 8.7.1-SNAPSHOT is missing.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#26628]
##### **Overview of the issue**

jhipster-framework daily snapshot is not been generated:
https://oss.sonatype.org/service/local/repositories/snapshots/content/tech/jhipster/jhipster-framework/

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@mraible @DanielFran where snapshots are generated?

**Comment by mraible** [comment]
@mshima Is this still an issue?

**Comment by mshima** [comment]
Still an issue

**Comment by mraible** [comment]
Why is this needed? Should it be looking for 8.7.1-SNAPSHOT now?

**Comment by mshima** [comment]
Snapshots are not been generated.
Closing since we are generating applications with released bom instead of snapshots now.
