### ISSUE TITLE
Show modules readme in the details page

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2665]
It would be very nice to show the modules github readme.md file in the module details page so that there is more info present along with stats

![image](https://cloud.githubusercontent.com/assets/1107223/12471671/cd002d28-c03a-11e5-8200-59768efec78e.png)

**Comment by pascalgrimaud** [comment]
what about the very very long README ?

**Comment by deepu105** [comment]
I dont think it will cause any issues? do you think of any issues?

**Comment by pascalgrimaud** [comment]
no issue, simple question
So maybe display the beautiful graph of download before readme ?

**Comment by deepu105** [comment]
i was thinking from a usefulness perspective, I mean i would like to see info about using the module more than knowing its download counts, but thats personal pref, if you guys feel otherwise I can change it :)

**Comment by pascalgrimaud** [comment]
From this point of view, I completely agree !

**Comment by deepu105** [comment]
@moifort your modules have some images with relative urls which arent visible, may be you should update them to have a fixed url from the repo

**Comment by moifort** [comment]
I will check it!
