### ISSUE TITLE
jhipster liquibase changelog bug

### ISSUE THREAD

**Issue by ouyangshixiong** [jhipster/generator-jhipster#2666]
1. mysql client console,drop database soup; create a new one.
2. mvn -Pprod  generate all tables;
3. mvn clean
4. mvn compile liquibase:diff

### But it is not!
See the attachment for the changelog file.
I am not sure how to fix it.

jhipster version: v2.23.0
yo-rc file:
[yo-rc-json.txt](https://github.com/jhipster/generator-jhipster/files/99055/yo-rc-json.txt)
.jhipster folder
[jhipster.zip](https://github.com/jhipster/generator-jhipster/files/99058/jhipster.zip)
I think it is a backend bug and has no relationship with web browser or JS.
[20160121133433_changelog.txt](https://github.com/jhipster/generator-jhipster/files/98733/20160121133433_changelog.txt)
entity xml:
[entity_xml.zip](https://github.com/jhipster/generator-jhipster/files/99063/entity_xml.zip)

**Comment by pascalgrimaud** [comment]
Please follow [our guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-submission-guidelines) about submitting an issue and provide some details.

We need your .yo-rc.json

**Comment by pascalgrimaud** [comment]
There is no issue here.

Your `.yo-rc.json` file indicates you use a h2Memory so look your `pom.xml` file, there is no configuration for liquibase :
```xml
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>${liquibase.version}</version>
                <configuration>
                    <changeLogFile>src/main/resources/config/liquibase/master.xml</changeLogFile>
                    <diffChangeLogFile>src/main/resources/config/liquibase/changelog/${maven.build.timestamp}_changelog.xml</diffChangeLogFile>
                    <driver></driver>
                    <url></url>
                    <defaultSchemaName></defaultSchemaName>
                    <username></username>
                    <password></password>
                    <referenceUrl>hibernate:spring:com.mycompany.myapp.domain?dialect=</referenceUrl>
                    <verbose>true</verbose>
                    <logging>debug</logging>
                </configuration>
```

Try to update your configuration

**Comment by ouyangshixiong** [comment]
Pascalgrimaud, very disappointed for your haste answer.
Could you pls make it clear,that I am using "prod" profile.
So let me show you part of 
![problem2](https://cloud.githubusercontent.com/assets/2086862/12498592/aab1ac02-c0de-11e5-9688-30cd156b306d.png)
the pom file:

**Comment by cbornet** [comment]
@ouyangshixiong well, you do use h2memory as dev database so this means you edited the pom manually to add your prod config.
Please understand that we do this on our free time so if you want us to help please give as much information as you can. Your issue is that liquibase wants to create "yaAdress_id" instead of the existing "ya_adress_id" column for some of your relationships.

**Comment by deepu105** [comment]
@ouyangshixiong please do understand that no body is paying any of us to do this, so if you are expecting help from us please atleast follow our guidelines and give all the required info when you create an issue

**Comment by jdubois** [comment]
I guess @ouyangshixiong is doing a Liquibase diff on his prod database: that's a very strange way of working, but that's something that could work.
Anyway, @ouyangshixiong if you don't follow the guidelines and don't explain what you do (in particular if that's something unusual) we can't help you.
Maybe you have a Liquibase bug, maybe your setup is wrong... It's very time consuming for us to help you if we don't have enough input.

**Comment by cbornet** [comment]
@ouyangshixiong can you try with the latest JHipster version. See [this](https://github.com/jhipster/generator-jhipster/commit/e86f710187d32dad53792e6d21917ca1eb7ebb3a) commit.

**Comment by ouyangshixiong** [comment]
### Thank you very much. @cbornet  @deepu105 @jdubois 
### Sorry if I offended you. @pascalgrimaud 

Let recalls the way I create the project "soup"：
I‘m doing part time job for a friend's company for free, After I found jhipster project, I think it is a excellent architecture, It may help me to make the backend of the project quickly( The front using Android & iOS).

Because there are not data at that time,So I create the project with H2Memory database on "dev" env. 
I think finally I will use mysql on "prod" env in case of losing user data.
After requirement analysis, I create my JDL using jhipster-uml. Because I have 13 entities and several relationships. But the model changed a lot, as the company modified business requirement as well as Android and iOS developers ask for new features.
When my project came into Intergation phrase. I must persist data for other developers. In the meantime I had to add columns or modified relationship on the model. It made many troubles.

After debugging for several days, I think:
### The most possible reason is the modification of the relationship may not support by liquibase.
### The second reason may be rebulid model or entities . I had do "yo jhipster", "jhipster-uml"
 commands several times in order to generate liquibase config( I had delete all unnecessary liquibase xml manually)

I am still try to fix the bug, I will make my project public for you to debug later.

**Comment by pascalgrimaud** [comment]
no problem @ouyangshixiong 
So you used jhipster-uml ! Maybe something related to jhipster-uml ?

**Comment by ouyangshixiong** [comment]
I had spent some time try to minimize the rang of the bug.
Now I think it is obviouse.
Follow these step, you will reproduce the bug.

1. Upgrade jhipster and jhipster-uml to the latest version.
2. Run yo jhipster generate jhipster code
3. Run jhipster-uml soup.jh generate business model code
4. Run mvn clean compile
5. Run mvn liquibase:diff generate liquibase changelog

Open the changelog file ,you will see some changes appear. 
Very strange. 
I believe there must be no difference.
See the sample project here : https://github.com/ouyangshixiong/soup
my model file here:
[soup.txt](https://github.com/jhipster/generator-jhipster/files/101810/soup.txt)

**Comment by ouyangshixiong** [comment]
I had spent some time try to minimize the rang of the bug.

Follow these steps, you will reproduce the bug.

1. Upgrade jhipster and jhipster-uml to the latest version.
2. Run yo jhipster to generate jhipster code
3. Run jhipster-uml soup.jh to generate business model code
4. Run mvn clean compile
5. Run mvn liquibase:diff to generate liquibase changelog

expected outputs:
1.There is no changes in the changelog due to no modification.

actual outputs:
1.By openning the changelog file ,you can see some changes. 

See the sample project here : https://github.com/ouyangshixiong/soup
my model file here:
[soup.txt](https://github.com/jhipster/generator-jhipster/files/101820/soup.txt)

**Comment by cbornet** [comment]
Seems that some JoinColumn annotations are missing on OneToOne and OneToMany

**Comment by ouyangshixiong** [comment]
Did anybody has suggestion or soluation? 
@cbornet  @pascalgrimaud  @deepu105  @jdubois @jkutner

**Comment by cbornet** [comment]
@ouyangshixiong have you tried adding @JoinColumn annotations on the domain relationships ?

**Comment by cbornet** [comment]
The issue on ManyToOne has already been fixed. There remains an issue with OneToOne : the annotation```@JoinColumn(name = "foo_id", unique=true)``` must be used because Liquibase will not name correctly the column.

**Comment by cbornet** [comment]
FYI,  I opened https://github.com/liquibase/liquibase-hibernate/issues/103
I don't have much hope since there doesn't seem to be any activity on the project...

**Comment by ouyangshixiong** [comment]
Thank you very much @cbornet . 
I will try it right now.

**Comment by ouyangshixiong** [comment]
I believe in the bug had been fixed. But not perfectly fixed. Because @OneToOne had no automatic generate @JoinColumn.

**Comment by cbornet** [comment]
I don't understand your issue. Have you seen #2695 ?

**Comment by ouyangshixiong** [comment]
I have seen #2695 ,did you mean that I should add "&amp;hibernate.ejb.naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy"  in my pom.xml manually?

**Comment by cbornet** [comment]
You should set in manually since you already configured it manually

**Comment by ouyangshixiong** [comment]
Thanks @cbornet  . I try it on my exist project. I believe the bug had been perfectly fixed.
