### ISSUE TITLE
Request to add LDAP authorization

### ISSUE THREAD

**Issue by akeske** [jhipster/generator-jhipster#2670]
Hi, I have a small :-1:  problem with the configuration of LDAP! If anyone has any idea to help me i will appreciate it. I cant find anything from internet about ldap and custom user and roles in database.... thanx

**Comment by pascalgrimaud** [comment]
Please follow [our guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-submission-guidelines) about submitting an issue and provide some details.

Anyway, I don't understand this ticket :
- is it a feature request about supporting LDAP in JHipster ?
- you tried to use LDAP with JHipster and it didn't work ? => post your question to stackoverflow
- you need help for custom user / roles in database for ldap => same, stackoverflow
