### ISSUE TITLE
Spring Boot 1.3.2 is out !

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2671]
And it fixes https://github.com/spring-projects/spring-boot/issues/4866

**Comment by pascalgrimaud** [comment]
good news! :+1:

**Comment by pascalgrimaud** [comment]
Quote from https://spring.io/blog/2016/01/22/spring-boot-1-3-2-released
> If you are upgrading from 1.3.1 there is one potentially breaking change; we now only search for messages.properties (and not messages*.properties) to enable auto-configuration of a message source. If you previously had a message file of the form messages_en.properties and you didn’t include a default messages.properties file, you will now need to add one.

We need to check this

**Comment by cbornet** [comment]
Yes, I guess ot's just about copying our messages_en.properties to messages.properties

**Comment by jdubois** [comment]
Yes it should be simple!

**Comment by cbornet** [comment]
It seems that we aren't using MessageSource autoconfiguration but that we configure it explicitly in LocaleConfiguration.java.
There is a spring.message.basename in application.yml but the autoconfiguration condition doesn't match because it looks for ```classpath*:classpath/i18n/messages*.properties``` on 1.3.1 and  ```classpath*:classpath/i18n/messages.properties``` on 1.3.2.
So I think it's safe to just update the pom.

**Comment by cbornet** [comment]
There is another MessageSource in ThymeleafConfiguration that is obsolete and should be removed.
I'm trying to get autoconfiguration working but I have an issue : I need to set ```/i18n/messages``` for ResourceBundleCondition to find the bundle during autoconf but then it needs to be ```classpath:/i18n/messages``` or else it doesn't work...

**Comment by cbornet** [comment]
OK, it's ```i18n/messages``` and then it works fine.
I'll do messagesource autoconfiguration in a separate PR.
