### ISSUE TITLE
Language keyword should be forbidden

### ISSUE THREAD

**Issue by The-Crocop** [jhipster/generator-jhipster#2672]
When creating an entity called language the ui doesnt work unless you rename the depending language service and all its references. Either the main language service should be renamed to something more specific or entities called language shouldnt be allowed in the first place

**Comment by pascalgrimaud** [comment]
You're correct, @The-Crocop
Do you want to fix it, by PR ?

**Comment by deepu105** [comment]
@The-Crocop add it to the JHipster reserved words

**Comment by The-Crocop** [comment]
OK will do.

**Comment by cbornet** [comment]
See #2645

**Comment by jdubois** [comment]
Yes that's solved in the next version thanks to #2645
