### ISSUE TITLE
Paginate Audits

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#2676]
* **Overview of the issue**
Over the course of a month (the default audit page period), the number of audit events to display can add up.  The Audit Resource currently returns a list of all the audit events, and each event is joined with the event type resulting in another query for each result.  This has been happening since before 2.0.

* **Motivation for or Use Case** 
Loading the Audits page can result in several hundred queries to join the audit tables when several hundred audit events are in the database.  This leads to very long load times.

* **JHipster Version(s)** 
Before 2.0.0 - 2.27.0

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
Any

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
No entities necessary

* **Browsers and Operating System** 
All

* **Reproduce the error** 
Load the Audits page with a large number of Audit events in the datasource with a event_date within the last month.

* **Suggest a Fix** 
Enable pagination for the Audits Resource.  I just added this to my own project and would be glad to send a PR if this is wanted.

**Comment by deepu105** [comment]
Ya this should be paginated its a lot of entries

**Comment by jdubois** [comment]
Yes of course!
