### ISSUE TITLE
What if we had some kind of backend ui, instead of jhipster-uml then we reach django python functionality

### ISSUE THREAD

**Issue by pvlastaridis** [jhipster/generator-jhipster#2678]
Let's make Jhipster a web framework!!!

**Comment by deepu105** [comment]
Is this a feature request?  If so please be more specific.
Jhipster is already a web app framework

**Comment by deepu105** [comment]
If im not wrong Jhipster does more than what django does and in a more efficient and user friendly way

**Comment by MathieuAA** [comment]
Is it April fool's day already? :joke
More seriously though, JHipster UML is not a backend UI, at all.

**Comment by jdubois** [comment]
I'm not totally sure of what you mean -> I don't think we could run JHipster inside a JHipster generated application, as the technologies are very different.
I'm also not sure of the use case, it looks like the current Yeoman questions are good enough for simple needs, and of course we have JHipster UML for more complex needs

**Comment by pvlastaridis** [comment]
I agree with you @jdubois the functionality is there, but the yeoman generator questions are difficult to use especially if you accidentally make a mistake. UML project can handle difficult situations in a better way, but it seems that you have to read UML principles first in order to use it. What if instead of the yeoman questions and the UML project, we had something like a back-end that you answer a form about how your new entities should be and after you submit the required files are created for you. Then all you have to do is to restart your project or run liquibase diff as well?

**Comment by MathieuAA** [comment]
@pvlastaridis could some kind of DSL do the trick?
By the way, this idea may be worth studied.

**Comment by cbornet** [comment]
I'm not sure it would be better than jhipster-uml ...

**Comment by pvlastaridis** [comment]
@MathieuAA I think we can have the front-end in Angular the back-end could be also in Java and be part of the project. Then maybe use yeoman generator to strip it off in production.
@deepu105 I agree with you that jhipster is far superior than django since it has a much stronger front-end, and cloud applicability, and easily integrate top test frameworks and blahblah..... But the entity creator is not as efficient and I think it's a drawback. Also imagine if creating entities is done within Java / Spring and an admin front-end UI then we open up the way for Jhipster to become easily a strong CMS something like drupal or sth even greater.

@cbornet It would be for anyone who has not the time or willing to study UML, or is afraid to do so.

**Comment by pvlastaridis** [comment]
By the way @cbornet I remember being asked twice, a few years ago, by my university tutor to find some resources on UML and the information I found on the web was very little and aged. To my opinion, UML is still popular only among academic societies.

**Comment by cbornet** [comment]
@pvlastaridis not really! UML is widely used in enterprise to modelize entities. The jhipster-uml howto is just one page : really not hard to understand and you get a nice printable chart showing your entities and their relationships.
IMO any project that has more than a dozen entities should use jhipster-uml. Otherwise you will not understand your domain anymore...

**Comment by MathieuAA** [comment]
Or you could just drop the UML, and use the JDL.

Frankly, I like your idea, but it has the same drawback as the current generator: if you don't have a lot of entities, your solution would be good and not too time-consuming. If, however, you want to generate a lot of complex entities (with relationships) you would have to either use the form to create them in the right order, or implement something to do it for you (like I did for JHipster UML). And, even then, you'd lose quite a lot of time completing the form.

**Comment by pvlastaridis** [comment]
Thank you all for sharing your thoughts about my proposal. It seems that I was one of the few that did not find the yeoman entity generator handy and not willing to try the UML project. Also having been involved in Drupal and Django projects I envy the way they deal with entities creation, despite the fact they don't inspire me anywhere near Jhipster does. I wonder what is going to be the next great feature and in what direction. Although what it has been achieved so far is beyond any expectation. Keep up the good work!!!

**Comment by cbornet** [comment]
You should really try jhipster-uml. You will see that it is far easier than what you think.

**Comment by deepu105** [comment]
Yes, once you go beyond 10 or 20 entities you wouldn't want to do it
anything other than UML take it from someone who have build applications
with 100+ entities before Jhipster UML was made :(

There is not a single day that went by were i didnt wish jhipster UML was
released sooner
