### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by arifsbs** [jhipster/generator-jhipster#2681]
I am building this project using command gradlew from a windows cmd prompt. I get the following error

FAILED
FAILURE: Build failed with an exception
--stacktrace
BUILD FAILED

There is no more detail to investigate the root cause of the error. I have tried running build using gradlew -S command but still no extra info is displayed on the console.

I am not getting any lead to resolve this issue. I hope somebody might be able to help me.

Regards
Arif

**Comment by atomfrede** [comment]
Please take a look at our [guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-submission-guidelines) otherwise we can't help you.

**Comment by jdubois** [comment]
I'm sorry but you don't give your version number, .yo-rc.json, etc... So we can't help you, please follow the guidelines next time!
