### ISSUE TITLE
Allow 'file://' Origin on a POST request in jhipster from cordova.

### ISSUE THREAD

**Issue by ViCe2099** [jhipster/generator-jhipster#2682]
I have a JHipster project and I need to access webservices from it with a cordova mobile App.
The thing is, on the POST request from the app the Origin header is sent with the value 'file://', which the isValidOrigin method from the default CorsFilter deems invalid because it doesn't meet the RFC952 standards.
I have tried adding custom filters with the varying methods that are described online, but I cannot override the default isValidOrigin verification and always end up getting 403 error on calls from the app. If anyone has ANY way to make the POST request with 'file://' Origin be accepted by JHipster please let me know, so I can at least have a solution and improve from there.

Thanks in advance.

**Comment by gmarziou** [comment]
Using 'file://' for a remote resource does not make sense, can't you fix the mobile app?

**Comment by ViCe2099** [comment]
Unfortunately I cannot, at least to my knowledge. From the information that I have gathered the 'file://' Origin is set in the preflight request from a POST call to witch I have no access (with newer versions of Android that doesn't happen it seems but i need to work with 4.4.2 at least), using the same code but for a GET call the request gets gets a 'null' Origin and it passes the isValidOrigin verification completing the request. 
So assuming that it isn't possible to change the origin from the client side ( god knows i tried ) is there any other option? I thought of basic services running on the same machine that would receive the POST request and "passed it through" to JHipster bypassing the origin problem, but I would like to avoid it.

**Comment by cbornet** [comment]
From #2171
Your CorsFilter shouldn't be org.apache.catalina.filters.CorsFilter but org.springframework.web.filter.CorsFilter. Are you using the latest JHipster version ? There is a CorsFilter bean in WebConfigurer that will be activated if you set the values in your application.yml

**Comment by ViCe2099** [comment]
No I am not running the latest version, the one I have is 2.16.0 with org.springframework.boot 1.3.0.
My cors filter isn't org.apache.catalina.filters.CorsFilter but that is where the method I want to override is, I just need that 'file://' origin passes the URI check the same way 'null' does, preferably I would like to maintain the other security benefits of the default filter if possible.
I have added filters that where supposed to let all request of my service url pass, but they are still barred at org.apache.catalina.filters.CorsFilter by the isValidOrigin. Is like I'm adding a filter not replacing the default one.

**Comment by deepu105** [comment]
Guys, this should be on SO as this is a non standard use case, Im closing this but if yuu guys wish you can continue the conversation

**Comment by cbornet** [comment]
@ViCe2099 You are not using Spring Boot's CorsFilter so as @deepu105 you should post your use case to SO. JHipster uses the Spring Boot CorsFilter so we can only provide support if you use this one. With the SB filter, the code for checking origin validity is in org.springframework.web.util.WebUtils
```java
/**
	 * Check the given request origin against a list of allowed origins.
	 * A list containing "*" means that all origins are allowed.
	 * An empty list means only same origin is allowed.
	 * @return {@code true} if the request origin is valid, {@code false} otherwise
	 * @since 4.1.5
	 * @see <a href="https://tools.ietf.org/html/rfc6454">RFC 6454: The Web Origin Concept</a>
	 */
	public static boolean isValidOrigin(HttpRequest request, Collection<String> allowedOrigins) {
		Assert.notNull(request, "Request must not be null");
		Assert.notNull(allowedOrigins, "Allowed origins must not be null");

		String origin = request.getHeaders().getOrigin();
		if (origin == null || allowedOrigins.contains("*")) {
			return true;
		}
		else if (CollectionUtils.isEmpty(allowedOrigins)) {
			return isSameOrigin(request);
		}
		else {
			return allowedOrigins.contains(origin);
		}
	}
```
I don't see anything in this that would prevent to allow origin from file:// (I would start by allowing * then narrow when at least this works)
