### ISSUE TITLE
H2 database(in memory) console can not login.

### ISSUE THREAD

**Issue by crossz** [jhipster/generator-jhipster#26826]
https://www.jhipster.tech/development/#using-the-h2-database-in-development

##### **Overview of the issue**
Following the H2 database(in memory) usage on the document of "Using JHipster in development" will lead to 
1. The database works fine.
2. But user can not login this H2 database console.

Therefore no way to do database management and exporting etc.

##### **Motivation for or Use Case**

I want to login the H2(in memory) database console, but failed by following documents on the page of "Using JHipster in development".

By checking the generated application-dev.yml, it turned out that the `h2.console.enabled` is assigned `false`. 
And the comments about this is "disable spring boot built-in h2-console since we start it manually with correct configuration".
But where is it? the H2(in memory) database out of box from JHipster is not working at all.

##### **Reproduce the error**

1. Follow the `jhipster` cli command, and select H2 as database type, especially in the dev profile.
2. Run `./mvnw`, 
3. Login as admin, and select administration -> database to login, here will fail.

##### **Suggest a Fix**

Do better and detailed documentations with more details.

##### **JHipster Version(s)**

8.6.0

##### **JHipster configuration**

Nothing special, just select H2/Mysql as database and select H2(in-memory) in development.

##### **Browsers and Operating System**

Macos 14.5, 
Firefox 128.0.2 (64-bit)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment]
@crossz I generated a simple application named `appangularh2`

Go to http://localhost:8080/h2-console

Login with 
![image](https://github.com/user-attachments/assets/dc95b9eb-4123-4f0c-a3fd-c55c5c5910e9)

And it works 🙂
![image](https://github.com/user-attachments/assets/f0562b8d-19f0-48c4-872a-f0316d82ff35)

cc @DanielFran

**Comment by crossz** [comment]
@qmonmert H2 on disk works, I know this. The issue I raised is for H2 in memory, does it work out of box for you?

**Comment by qmonmert** [comment]
@crossz same result with h2 in memory, it works
<img width="480" alt="image" src="https://github.com/user-attachments/assets/6711b30e-7bf9-4862-8ea1-5264142ef764">
