### ISSUE TITLE
Fixed ZonedDateTime serialization format

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2689]
For ZonedDateTime serialization, we currently have a "dynamic" formatting (```DateTimeFormatter.ISO_OFFSET_DATE_TIME```) which will adapt the number of digits after the seconds depending on whether the date has millis, micro or nano seconds.
Javascript is fine with that but for other clients (eg. android) it can be complex to deserialize (with java7 SimpleDateFormat...).
So shouldn't we fix the format to something like ```YYYY-MM-DD'T'HH:mm:ss.SSS'Z'``` so that it's easier to handle for clients ?
Note : prior to java8 date migration, the format was fixed to ```YYYY-MM-DD'T'HH:mm:ss'Z'```

**Comment by dalbelap** [comment]
I have that problem with an Android using GreenDao for persist. Maybe I must storage as String instead java.util.Date and parse manually in the client.

**Comment by cbornet** [comment]
I even wonder if it wouldn't be interesting to have the possibility to set the format by application.yml file. What do you think ?

**Comment by deepu105** [comment]
Its 100 %  possible technically

**Comment by cbornet** [comment]
@deepu105 you mean already possible ?

**Comment by deepu105** [comment]
I mean of course we can inject the environment and get the property from .yml file and use it right?
