### ISSUE TITLE
regrading bug reports 

### ISSUE THREAD

**Issue by milanjain7906** [jhipster/generator-jhipster#26919]
Hii , Team i hope you are fine ..
I have a question regrading your bug bounty policy just want to know that your website is under scope of your bug bounty program ?

**Comment by mshima** [comment]
It's under the scope, bounties are given for validated security issues reported through mail.
For improvements or fixes it will depend on the task.

**Comment by milanjain7906** [comment]
Can you please provide me with that email address ? Also, I found a bug.
Can you plz tell me where I have to report it ?

**Comment by mshima** [comment]
The info is in the project security policy: https://github.com/jhipster/generator-jhipster#security-ov-file.
