### ISSUE TITLE
Release generator-jhipster 8.7.0

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#26914]
##### **Overview of the feature request**

- Spring Boot 3.3.3
- ESLint v9
- Blueprints/internal improvements.
- Angular let syntax

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by siuburu** [comment]
Maybe include changes from Angular 18.2.0 new migration schematics in generated code:

- `` ng generate @angular/core:inject-migration  ``
- `` ng generate @angular/core:route-lazy-loading-migration  ``

**Comment by OmarHawk** [comment]
Probably now it's worth waiting for Spring Boot 3.3.3 ;-)

**Comment by mshima** [comment]
Spring Boot updated to v3.3.3
@mraible are you available to make a release?

**Comment by mraible** [comment]
Yes. I can do it on Sunday.

**Comment by mraible** [comment]
Released! https://github.com/jhipster/generator-jhipster/releases/tag/v8.7.0

**Comment by mraible** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/217835
