### ISSUE TITLE
[Enhancement Request] Support for AngularJS one time binding

### ISSUE THREAD

**Issue by amitjindal** [jhipster/generator-jhipster#2692]
**Overview of the issue**
This is an [minor] enhancement request to support one time binding for angular views.
http://blog.thoughtram.io/angularjs/2014/10/14/exploring-angular-1.3-one-time-bindings.html

**Motivation for or Use Case**
This avoids excessive watchers and improves performance.

**Comment by jdubois** [comment]
I don't understand: this is a standard (basic) AngularJS feature, of course it works with JHipster. I know many people who use it, I'm even doing this in my AngularJS training :-)

**Comment by amitjindal** [comment]
Hi @jdubois I meant this should be generated in entity-*.html pages.

**Comment by jdubois** [comment]
We could have this for a few examples, then I'm afraid it will confuse beginners. Do you have a specific use case, or screen, where this causes issues? I'm guessing in the database tables?

**Comment by amitjindal** [comment]
Sorry for confusion. What I meant to ask was this:

For example, if I generate the HTML for employee entity this is currently generated:
```
<tr ng-repeat="employee in employees track by employee.id">
                    <td><a ui-sref="employee.detail({id:employee.id})">{{employee.id}}</a></td>
                    <td>{{employee.name}}</td>
                    <td>{{employee.designation}}</td>
                    <td>{{employee.joinDate | date:'medium'}}</td>
                    <td>{{employee.isActive}}</td>
                    <td>
```
I would suggest we should generate this:
```
<tr ng-repeat="employee in employees track by employee.id">
                    <td><a ui-sref="employee.detail({id:employee.id})">{{::employee.id}}</a></td>
                    <td>{{::employee.name}}</td>
                    <td>{{::employee.designation}}</td>
                    <td>{{::employee.joinDate | date:'medium'}}</td>
                    <td>{{::employee.isActive}}</td>
                    <td>
```

This is a minor request so no hurry to do this. Wanted to suggest this for possible future roadmap.

**Comment by jdubois** [comment]
OK, so basically we already "support" this as it's standard AngularJS, but that could be an improvement in performance for the current screens.
On the other hand I'm not sure it will be a big improvement, and I'm afraid it will confuse newer users, so I'm not totally convinced we should do this.
I'm closing this as I don't think we should migrate this now, it should only be a specific tuning on some heavy pages, but yes that's a good performance tip.
