### ISSUE TITLE
[Enhancement Request] Create/Edit should not be a dialog

### ISSUE THREAD

**Issue by amitjindal** [jhipster/generator-jhipster#2693]
**Overview of the issue**
This is [minor] enhancement request if you would like to consider.
Instead of popup the create/edit should be a separate state and on clicking new or edit we should navigate to that page.

**Motivation for or Use Case**
Since the create/edit is a popup if the form is long, scrolling is a problem and by mistake if someone clicks outside the data disappears. We had this problem where entities as long as 55-60 fields were there. Due to that while scrolling if by mistake a click happens the form disappears.
While this is probably not a problem for trained developers, for end users such a mistake (of clicking outside or mis-clicking scrollbar) happens.
If the end user has entered lot of details (say asking a customer on phone), a small mistake loses all data.

**Changes needed in code**
This requires adding an edit state and changing navigation from popup to state change.

**Comment by deepu105** [comment]
Edit, create and delete are already separate states, modals are load3d into the state, you can easily disable the modals in the state resolve and you will see a normal page.

Having said that, click to close could be annoying so may be we can disable that in modal config so that you need to click close icon to close

**Comment by jdubois** [comment]
Yes they are already different states and they even have there own URLs.
Maybe we could create separate pages, but here the idea was to have something behaving a bit like a desktop app, and not refresh everything all the time -> I'm not sure the UI/UX is the best one, and I'm not sure we have a performance improvement in the end, but those where the original ideas.
We can of course challenge those ideas, but given the number of requests we have at the moment, I don't think we have the time to rework those screens now, if there isn't a strong need to do so.

**Comment by amitjindal** [comment]
Ok. I can live with disabling in modal config.
Thanks

**Comment by lrkwz** [comment]
@amitjindal , @deepu105  can you please explain where exactly modal behavior can be disabled?

Thank you.

**Comment by delverdev** [comment]
@lrkwz, if you're asking about closing on outside click, here it is:
Modal opens through `$uibModal.open` and have params like controller, templateUrl etc. Add param `backdrop: 'static'` and modal will not be closed on outside click.

**Comment by lrkwz** [comment]
Well no I am interested in not popping out the modal at all: I'll prefer
having the body inline in the page.

Il 04/nov/2016 00:59, "Delver Developer" <notifications@github.com> ha
scritto:

**Comment by gmarziou** [comment]
Guys, this is an issue tracker, please continue your dicussion where it belongs to: stackoverflow or gitter.
Thanks

**Comment by lrkwz** [comment]
You are right http://stackoverflow.com/questions/40424898/disable-modal-in-jhipster-angular-ui

**Comment by jdubois** [comment]
Guys, what's going in here?
I'm locking this thread.
