### ISSUE TITLE
Java Service compilation issue when using ServicesClass with entitySuffix and Elasticsearch

### ISSUE THREAD

**Issue by khayassine** [jhipster/generator-jhipster#26946]
##### **Overview of the issue**

Hello, We get a compilation error when setting a entitySuffix with serviceClass & searchEngineElasticsearch configurations

##### **Motivation for or Use Case**

Use Suffix for my Entities and ServiceClass and Elasticsearch on the same time !

##### **Reproduce the error**

Just configure the Entity as serviceClass, and enable Elasticsearch as search engine + set entitySuffix on application level

##### **Suggest a Fix**

I think the fix should be this :

File : jhipster/generator-jhipster/blob/main/generators/spring-boot/templates/_global_partials_entity_/**save_template.ejs**
Line to Replace (36) :         return <%- **entityInstance** %>;
Correct line (36) :        return <%- **persistInstance** %>;

##### **JHipster Version(s)**

Last version 8.6.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "testApp",
    "buildTool": "maven",
    "cacheProvider": "caffeine",
    "clientFramework": "react",
    "clientTestFrameworks": [],
    "clientTheme": "darkly",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1723454747256,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "Toto"
    ],
    "entitySuffix": "Entity",
    "feignClient": null,
    "jhipsterVersion": "8.6.0",
    "languages": [
      "fr",
      "en",
      "ar-ly"
    ],
    "lastLiquibaseTimestamp": 1723455044000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "fr",
    "packageFolder": "com/test/app",
    "packageName": "com.test.app",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": "elasticsearch",
    "serverPort": "8080",
    "serverSideOptions": [
      "searchEngine:elasticsearch"
    ],
    "serviceDiscoveryType": false,
    "syncUserWithIdp": null,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "17.0.10" 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.10+11-LTS-240, mixed mode, sharing)

git version 2.43.0.windows.1

node: v20.16.0
npm: 10.8.1

Docker version 26.1.4, build 5650f9b

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
@ChangelogDate("20240812093044")
entity Toto

paginate Toto with pagination
service Toto with serviceClass

</pre>
</details>

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
Hi @khayassine 
Can you please update 1st post and add your jhipster configuration?

Please follow the instructions:
_To provide all information we need, you should run `jhipster info` in the project root folder, and
copy/paste the result here.
The `.yo-rc.json` file generated in the root folder is mandatory for bug reports. This will help us to replicate the scenario.
You should remove any sensitive information like the rememberMe key or the jwtSecretKey key._

Thanks

**Comment by khayassine** [comment]
Tested localy by changing the **Line 36** on file **save_template.ejs** 

this : 
return <%- **entityInstance** %>;

By this :
return <%- **persistInstance** %>;

=> worked fine 👍

**Comment by mshima** [comment]
@khayassine can you provide the PR?
