### ISSUE TITLE
Postgres auto increment

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2696]
It seems that hibernate GenerationType.AUTO strategy uses hibernate_sequence with postgres.
So the PK column should probably not be set to autoIncrement=true since liquibase wants to drop the generated sequences when doing a diff.
Does somebody have an opinion ?

**Comment by geraldhumphries** [comment]
I made Postgres and H2 use the serial sequences by changing GenerationType to IDENTITY. It didn't fix the liquibase issue though.

**Comment by cbornet** [comment]
This [page](https://en.wikibooks.org/wiki/Java_Persistence/Identity_and_Sequencing) seems to go against IDENTITY and to prefer AUTO for insert performance reason. And IDENTITY doesn't seem to be supported by Oracle (but maybe it's not up-to-date). I don't have a strong opinion on this.

**Comment by cbornet** [comment]
Also we should probably set hibernate.id.new_generator_mappings=true as it is the recommended setting.

**Comment by cbornet** [comment]
Also we should probably set hibernate.id.new_generator_mappings=true as it is the recommended setting.

**Comment by cbornet** [comment]
From https://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html/ch03.html
> We recommend all new projects which make use of to use @GeneratedValue to also set hibernate.id.new_generator_mappings=true as the new generators are more efficient and closer to the JPA 2 specification semantic. However they are not backward compatible with existing databases (if a sequence or a table is used for id generation).

**Comment by cbornet** [comment]
I opened https://github.com/liquibase/liquibase-hibernate/issues/105
There is an issue with liquibase diff and postgres so closing until it's fixed on liquibase side.
