### ISSUE TITLE
JHipster 8.6.0 behind a corporate proxy

### ISSUE THREAD

**Issue by xbotuk** [jhipster/generator-jhipster#26971]
##### **Overview of the issue**

used JHipster 8.6.0 to generate a sample monolith app and got this error:

icm : Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"
At line:1 char:72
+ ... 'mvnw.cmd'; icm -ScriptBlock ([Scriptblock]::Create((Get-Content -Raw ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Command], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeCommandCommand
ECHO is off.
Cannot start maven from wrapper

##### **JHipster Version(s)**
8.6.0

##### **JHipster configuration**
none.

##### **Browsers and Operating System**
Windows 10 22H2

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
We use `npmw` that uses:
- mvnw to run maven:
https://maven.apache.org/wrapper/
- frontend-maven-plugin to download node/npm:
https://github.com/eirslett/frontend-maven-plugin?tab=readme-ov-file#proxy-settings

Doesn't looks a JHipster issue.
