### ISSUE TITLE
Site should be a reserved word

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2697]
As it is the parent angular state.
I also think that "docs", "error", "accessdenied", "tracker" and "entity" should be reserved as they correspond to existing angular states.

**Comment by andidev** [comment]
I guess this wont be an issue after #2685 is merged.

**Comment by cbornet** [comment]
Of course. It's either #2685 or this one.

**Comment by jdubois** [comment]
Then it's #2685 :-)

**Comment by cbornet** [comment]
Cool !
We need to have the entity generator clean the old files or there will be cries at the next upgrade.
I've almost finished #2702 (so easy with yeoman) so it will ease the migration

**Comment by cbornet** [comment]
Well, in fact no : you will have to play your ```yo jhipster:entity``` at least once in the correct order before it works automagically

**Comment by jdubois** [comment]
Can you read inside the .json files? There is the timestamp of creation inside it, so you need to replay the entities creation in that order (the timestamp is used by Liquibase, for the same reason)

**Comment by cbornet** [comment]
The problem is that jhipster-uml sets the same changelogDate to all entities

**Comment by jdubois** [comment]
Oh I didn't know that, maybe @MathieuAA @CarlKlagba should increment the last millisecond each time an entity is generated, so we have the right order?
Otherwise this will work for all normal use cases.

**Comment by MathieuAA** [comment]
Do we? I'll check that and fix it if this is the case!

**Comment by cbornet** [comment]
It's also simpler to read a list than fetching each files in the .jhipster dir and comparing the changelogDates

**Comment by MathieuAA** [comment]
@cbornet you are right! Gonna fix it right away, thanks!
