### ISSUE TITLE
Regenerate existing entities from the main generator 

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2702]
This will help to upgrade and could be used to clean old files.
The main challenge is to get the correct order of generation. We can of course read the changelogDate field of each entity json file but it would be simpler to maintain an ordered list of entities to load in the .yo-rc.json or to prefix the entity json files with a number (eg. 001_Foo.json).

**Comment by cbornet** [comment]
See #2645

**Comment by deepu105** [comment]
if we are doing this it should be optional, as someone might want to
regenerate the app base but not the entities

Thanks & Regards,
Deepu

On Wed, Jan 27, 2016 at 5:54 PM, Christophe Bornet <notifications@github.com

**Comment by cbornet** [comment]
I think it should be optional to skip it :smile:

**Comment by cbornet** [comment]
We cannot use changelogDate because jhipster-uml for instance will put the same date for all entities.
I think the simplest is to store a list because prefixing the json files will cause backward compatibility issues with jhipster-uml.
We can also export the function that gets all the entity names to the modules.
