### ISSUE TITLE
Error on "npm install & bower install"

### ISSUE THREAD

**Issue by saahon** [jhipster/generator-jhipster#2705]
After installation, the new jhipster project appeared here such error:

![Error Screen](http://i.stack.imgur.com/uaDOz.jpg)
 
Help me why this error occurs?

**Comment by pascalgrimaud** [comment]
The error is clear (see your screenshot)
You must install all tools (grunt, git, bower etc.)
Follow this http://jhipster.github.io/installation/

**Comment by saahon** [comment]
I have installed yo, bower, grunt-cli  for windows. for each project need separately installed?

**Comment by saahon** [comment]
I have was individually for the project installed grunt, and bower:
`D:\projects\jproject>npm install -g bower`
result:
`C:\Program Files\nodejs\bower -> C:\Program Files\nodejs\node_modules\bower\bin\bower 
C:\Program Files\nodejs 
    └── bower@1.7.7 "`
I have set Maven , the module Spring added, bower.json file showed, configuration database checked, did clean-install and has launched a project with the of spring-boot: run. But the screen browser does not have a is nothing other than the inscription "This is your footer" ....
From Grunt-tasks - serve also did. revealed a bug:
`Running "wiredep:app" (wiredep) task Warning: Error: Cannot find where you keep your Bower packages. Use --force to continue. Aborted due to warnings. –`

**Comment by deepu105** [comment]
dude really somthing wrong with your setup are you sure you followed this https://jhipster.github.io/installation/

make sure node, npm and bower is installed properly, if npm or bower install failed during app generation run it again with `npm install` and `bower install`

**Comment by deepu105** [comment]
its seems you havent installed git or you havent set git on your path
