### ISSUE TITLE
H2 in production

### ISSUE THREAD

**Issue by erikkemperman** [jhipster/generator-jhipster#2706]
It looks deliberate, but I'm curious why H2 (disk or memory) is not an option for production database?

Would something like [this](https://github.com/erikkemperman/generator-jhipster/commit/4baee6284d00cf70c09f9e201232e2204af06c77) be a silly thing to do?

**Comment by jdubois** [comment]
I just wouldn't use H2 in production, it's not a production-ready database.
Use it at your own risk!

**Comment by erikkemperman** [comment]
@jdubois Thanks for the quick response! Well I suppose we would actually prefer an option for no database at all -- we don't have anything to persist really...

But we definitely don't want to have to ask our users to install mariadb or postgres, especially if it's not actually used, so I figured H2 would be more or less painless.

Anyway, thanks again.

**Comment by jdubois** [comment]
And did you try our Docker configurations? Very easy to use and set up, and you get a real database :-)

**Comment by erikkemperman** [comment]
I don't see how that would help us, but I guess our use-case might be uncommon.

We have a lot of Spring code, across several Maven modules, one of which does browser-based visualization off a  backend receiving ephemeral input from the other modules. All of this has to be installable by non-experts (and likely even non-administrators).

We're now looking into rewriting that visualizer, and are considering JHipster to scaffold it. This looks to be a nice match with our existing Spring stuff, and I am a big fan of Angular. But we seem to be getting some features that might get in the way, at least in our specific case.

So the upshot is I might go with H2 in production profile after all, it seems easier to not use H2 than it is to not use Mariadb/Postgres :-)

But like I said, a database-less option would be even better for us.

**Comment by cbornet** [comment]
@erikkemperman if you really don't have production requirements for your database, configuring your application-prod.yml to use H2 is just a few lines to copy from your application-dev.yml

**Comment by jdubois** [comment]
How yes it's uncommun but that's a perfectly valid use-case.
You can just copy/paste our dev code with H2 as @cbornet says, it will work fine enough!
I've used H2 with huge schemas and it's working well for this kind of need.

**Comment by erikkemperman** [comment]
Ah yes, that makes more sense than forking the generator just to accomplish this :-)

Thanks a lot guys!
