### ISSUE TITLE
Entity `update` integration tests are persisting changes to the test database immediately

### ISSUE THREAD

**Issue by geraldhumphries** [jhipster/generator-jhipster#2709]
* **Overview of the issue**

When running integration tests, changes made to the object being tested (the one that's set up in `initTest`) are persisted across all copies of that object. Calling `entity.setAttribute` will immediately change that attribute in copies of the object in lists from `entityRepository.findAll()` and the database.

* **Motivation for or Use Case** 

The update test is not actually testing the API! I am trying to set up a test to make sure certain fields are NOT updated for one of my entities when going through the regular endpoint, but the test is failing.

This might have implications for the other tests as well.

* **JHipster Version(s)** 

Reproduced in 2.25.0 and master.

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "0000000000000000000000000000000000000",
    "testFrameworks": []
  }
}
```

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

address.json
```
{
  "relationships": [],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "streetLine1",
      "fieldType": "String"
    },
    {
      "fieldId": 2,
      "fieldName": "streetLine2",
      "fieldType": "String"
    },
    {
      "fieldId": 3,
      "fieldName": "city",
      "fieldType": "String"
    },
    {
      "fieldId": 4,
      "fieldName": "provinceState",
      "fieldType": "String"
    },
    {
      "fieldId": 5,
      "fieldName": "postalCode",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20150916193741",
  "dto": "no",
  "pagination": "pagination"
}
```

* **Browsers and Operating System** 

Windows 10

* **Reproduce the error** 

Remove the call to `restAddressMockMvc.perform` in `updateAddress()`. Test still passes! 

You can also put the result of `addressRepository.findAll()` into a variable after `addressRepository.saveAndFlush(address);` and watch it with a debugger; as `address` is updated, the address object in `addressRepository.findAll()` is also updated.

**Comment by jdubois** [comment]
I think the biggest issue is that the REST call is not testing anything! I guess this is because the object is updated in the Hibernate 1st level cache, so you have the same value everywhere.
So we need to use a new object, which is not in the cache.

**Comment by jboenisch** [comment]
This probably happens because the freshly saved entity is attached to the Entitiymanager, which takes care of persisting all changes.

A quick fix could be to call entityManager.detach(entity) before modifying any field.
