### ISSUE TITLE
Reorder the Docs sidebar menu

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#27120]
I think we should re-order the docs side bar menu:

New suggested order:
- Getting started
- Setting up your environment -> Rename to `Installation and set up`
- Core JHipster tasks -> Rename to `Create application and entities`
- Options -> Rename to `Add optional technologies`
- JDL
- Development
- Test & QA
- Production
- Microservices
- Blueprints
- Tools
- JHipster Lite
- JHipster in a few minutes
- Release notes
- Getting help
- Contributing
- Tips and tricks
- JHipster Developer Association
- JHipster tech Board
- JHipster meetups
- Artwork

cc @mraible @SvMak

**Comment by SvMak** [comment]
Done: https://github.com/jhipster/jhipster.github.io/pull/1372
