### ISSUE TITLE
Algolia search index is outdated/broken

### ISSUE THREAD

**Issue by Alchemik** [jhipster/generator-jhipster#27139]
##### **1. Overview of the issue**

**The issue is related to [jhipster.github.io](https://github.com/jhipster/jhipster.github.io). As it cannot be created in the original repository, I'm reporting it here.**

Algolia search index seems to be outdated for at least some parts of the JHipster documentation. 

##### **2. Motivation for or Use Case**

The search functionality on JHipster’s official documentation, powered by Algolia, appears to be using an outdated index. When I search for certain terms or topics, the results include outdated pages or miss recent additions and updates to the documentation.

##### **3. Reproduce the error**

* Navigate to the JHipster documentation and use the Algolia search functionality:
  * In the search bar, enter a keyword which no longer exists in docs, in this case, `jpaDerivedIdentifier`
![image](https://github.com/user-attachments/assets/a9f18ce7-45a9-45fe-86f3-eea28873594c)
* Review the search results:
  * Notice that results point to outdated version of documentation, which was modified > 1 year ago
![image](https://github.com/user-attachments/assets/0f1ceb01-5f7a-4a27-97b5-30cd66eb98f4)
* Cross-check with the latest documentation:
  * Confirm that updates are missing from the search results
![image](https://github.com/user-attachments/assets/29164115-aea5-4214-8e60-89f652dd42c2)

**2nd example**
* In the search bar, enter a keyword `angularSuffix` appearing on [docs/jdl/options.mdx](https://github.com/jhipster/jhipster.github.io/blob/ffc441f197e19bf67e4c9ee48ce5adf0d055fd3a/docs/jdl/options.mdx#L361)
* Cross-check with the latest documentation and confirm that search result does not reference the searched page
![image](https://github.com/user-attachments/assets/84720e93-d4bf-4f25-bb0c-11afad703c53)

##### **4. Related issues**

> N/A

##### **5. Suggest a Fix**

> N/A

##### **6. JHipster Version(s)**

> N/A

##### **7. JHipster configuration**

> N/A

##### **8. Browsers and Operating System**

* OS: macOS Sonoma, v14.6.1
* Browser: Google Chrome, Version 128.0.6613.85 (Official Build) (arm64)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Added a bug bounty to try and get this fixed.

**Comment by omurthy** [comment]
It needs to be re-indexed. I applied using the link below. They sent an email to the person registered with Alogolia on behalf of Jhipster. The instructions in that email need to be completed.

https://docsearch.algolia.com/

**Comment by SvMak** [comment]
Detailed docs about search configuration for Docusaurus and fix this issue https://docusaurus.io/docs/search#using-algolia-docsearch

It is necessary to compare the current configuration with the recommended one and manually reindex the new website, by someone with access to the Algolia account.

**Comment by mraible** [comment]
@jdubois Do you have access to the Algolia account or know who does?

**Comment by jdubois** [comment]
This was setup by @sahbi-ktifa several years ago, I'm not sure we have anything else than a token to connect.

**Comment by omurthy** [comment]
I asked for any solution regarding this issue from the Algolia discord channel.

**Comment by omurthy** [comment]
@jdubois I contacted Algolia about access. They gave me access to the Algolia UI console. Also, Algolia's crawling method has changed. They informed us by email about the update but we missed it. Anyway, they told me that we need to update/migrate Jhipster's Algolia account. It took some time to work together and finally, it's done. I deployed it on my side for testing. It looks good. If everything is good enough for you, I'll change it to the live system as well.

@Alchemik Please check the new search on my testing page:
https://omurthy.github.io/jhipster.github.io/

**Comment by jdubois** [comment]
Oh thanks so much, I did a quick test and that's good!!!

**Comment by Alchemik** [comment]
@omurthy thanks for the effort, is the test instance still up? I got 404 on every page except landing page

**Comment by omurthy** [comment]
@Alchemik check here : 
https://deploy-preview-1396--jhipster-site.netlify.app/

**Comment by Alchemik** [comment]
LGTM 👍
