### ISSUE TITLE
Decouple JDL from generators.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#27136]
##### **Overview of the feature request**

JDL and generators should be independent.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Ideally, each jdl statements and values of relative to each generators should be included in the respective generator.
i.e. the JDL's `clientFrameworkType` should be in `generator-client`, jdl acting as an interpretation engine (ast)
