### ISSUE TITLE
ExceptionHandlingAsyncTaskExecutor  execute is not wrapping the task

### ISSUE THREAD

**Issue by ezraroi** [jhipster/generator-jhipster#2714]
The execute is not wrapping the task with the exception handling:

Should be:
```
@Override
    public void execute(Runnable task) {
        executor.execute(createWrappedRunnable(task));
    }
```

**Comment by jdubois** [comment]
Is this code still useful ? This was added at the beginning of the project and I don't even know if this is useful.

**Comment by ezraroi** [comment]
I think that as long as this class can be used the fix should be applied.

Maybe today there is no need for such executor as it is easy to set unhandled exception handler
