### ISSUE TITLE
Update Hikari CP configuration to use native Spring Boot support

### ISSUE THREAD

**Issue by bonhamcm** [jhipster/generator-jhipster#272]
Spring Boot now supports Hikari CP natively so that should be integrated once released:

https://github.com/spring-projects/spring-boot/issues/418

https://github.com/spring-projects/spring-boot/commit/50190a4de7dec55df462fb06c2d888176403d654

**Comment by cbornet** [comment]
I think this is now fully integrated so we can remove "willdolater".
