### ISSUE TITLE
Feature Request: Don't use .original for non exec WAR

### ISSUE THREAD

**Issue by myspivey** [jhipster/generator-jhipster#2720]
jhipster uses sprint-boot:repackage to package an executable and the non executable. Requesting to change this so that both files are .war instead of having one .original.

**Comment by gmarziou** [comment]
Appending "exec" to the executable war name would force users to rename it also because spring boot systemd script uses this name to guess the name of the config file.
The executable war is the preferred way to deploy JHipster apps, I would not want it changes.

**Comment by pascalgrimaud** [comment]
> The executable war is the preferred way to deploy JHipster apps, I would not want it to change especially when we are heading to micro services.

agree with @gmarziou

**Comment by myspivey** [comment]
Can you clarify @gmarziou? Not sure I follow how this is a negative impact as it simply appends -exec before the war package extension on the executable. Also what makes it preferred? All of my large scale installs are existing Tomcat servers that do not have the need for the larger war including tomcat so not prefered in my use cases. Just looking for clarity. Understand it as a negative if this does break existing installs which we all look to avoid. The argument to not look at the change though just seems to devalue anyone that does not need an executable war for somewhat arbitrary reasons as I understand them.

**Comment by pascalgrimaud** [comment]
Currently :
```
jhipster-0.0.1-SNAPSHOT.war
jhipster-0.0.1-SNAPSHOT.war.original
```

With your modification:
```
jhipster-0.0.1-SNAPSHOT-exec.war
jhipster-0.0.1-SNAPSHOT.war
```

We shouldn't change it, because it's how spring-boot seems to work. Look [the documentation here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-maven-packaging)
> You should also see a much smaller file named myproject-0.0.1-SNAPSHOT.jar.original in the target directory. This is the original jar file that Maven created before it was repackaged by Spring Boot.

There is a discussion in spring boot project : https://github.com/spring-projects/spring-boot/issues/141

**Comment by myspivey** [comment]
What you mentioned in the documentation lists the default behavior, and spring-boot provides the manner I added to change it, http://docs.spring.io/autorepo/docs/spring-boot/1.3.0.RELEASE/maven-plugin/examples/repackage-classifier.html. The second link, the discussion, was closed because they added the property I linked above as the fix and closed it. We are actually matching that bug by not using .original and instead using the spring boot classifier exactly as the example. The test is easy to fix by simply changing it to *-exec.war and they will all pass. So this is also how spring-boot works.

**Comment by jdubois** [comment]
As some sub-generators (and I expect some people too) are using those names to deploy their applications, this would be a breaking change.
And as those are not the standard names, this would be against [policy 1](http://jhipster.github.io/policies/), unless we have a good reason to change this -> what is your specific use case for renaming this file?

**Comment by gmarziou** [comment]
I was refering to the way the systemd init script included at the very beginning of the executable jar file uses the name of the maven artifcat to guess the name and location of the [startup conf file](http://docs.spring.io/autorepo/docs/spring-boot/1.3.0.RELEASE/reference/html/deployment-install.html#deployment-script-customization-conf-file)
