### ISSUE TITLE
Move to Typescript

### ISSUE THREAD

**Issue by thiagogcm** [jhipster/generator-jhipster#2723]
[Feature request]

From now on Typescript is able to compile javascript files, which makes the migration easier. 
This could be the first step towards Angular2 support.

http://blogs.msdn.com/b/typescript/archive/2016/01/28/announcing-typescript-1-8-beta.aspx

#823

**Comment by jdubois** [comment]
This is kind of a duplicate to #1933

Yes we will probably move to TypeScript, but that will be when we move to AngularJS 2.0, if that ever happens -> my estimate is that it will be in 6 to 12 months, not before.
