### ISSUE TITLE
[Enhancement Request] Ability to change base URL for generated entities (only entities)

### ISSUE THREAD

**Issue by amitjindal** [jhipster/generator-jhipster#2724]
### Overview of the issue
This is an important enhancement request for a larger scale project.
Currently all entities are generated at the url: /api/<entityname>
I would request that there should be a question to ask the baseUrl where all entities be generated and then they should be generated in sub-url. Sort of like:
`Please provide the base URL where entities should be placed (default: '/api/')?`

### Motivation for or Use Case

**Use Case 1**
When we have a large project, we need to logically separate the resources.
The first set of endpoints are entities that directly represent database schema. Second set of endpoints are services that perform action based on need of the application (like /api/payment/add). If they are all at the same base URL it is difficult to manage the endpoints and how the project evolves. It also makes it difficult to enforce when only services should be used as opposed to entities.

So ideally I would have for Entities: `/api/entities/<entityname>`
and for services: `/api/services/<servicename>`

**Use Case 2**
For a long standing project, we need to version the API. Usually that is done by either header versioning or by URL separation. URL separation is preferred so that mixing of resources will not happen and is simpler to separate and retire older API.

So ideally I would like to have: `/api/v1/entities/<entityname>`

### Changes needed in code
Both of these can be solved by making the base url for entity generation as a variable.
Sort of like: `this.entityBaseUrl = '/api/entities';`

I have done this on a local copy of the jhipster for my purpose. The changes are attached if you would like to see them.
Note that this one is hardcoded version of baseUrl as I didn't know how to add the question in main application generator. This is following the same style of variable as @deepu105 recently used in Pluralise.

[baseUrl-patch.diff.txt](https://github.com/jhipster/generator-jhipster/files/109241/baseUrl-patch.diff.txt)

**Comment by amitjindal** [comment]
Want to add:
Internally we also move our generated Java Entities to a sub-package. However I didn't originally added that in the request as I thought you may not want to do that. It is mostly for logical separation as described above. Needed to make a few small changes in generator code to put the files in right place and correct the package inclusions.

![2016-01-29_09-32-27](https://cloud.githubusercontent.com/assets/3275983/12666951/90e070a0-c66b-11e5-9d0c-207b247333a5.png)

**Comment by deepu105** [comment]
For base url this can be easily done with a module subscribing to post
entity creation hook, its very easy actually, simpler than my audit module.
The hook will call the module and module will ask question for base url and
replace the current url using a regex in the resource files. I can help if
you want to do a module for this

For moving entity resources to a folder, i wouldn't mind but i would let
that for the team to decide

**Comment by amitjindal** [comment]
@deepu105 Ok. Thanks for your offer to help. Then let me try first. That way I will learn. If I have a question I will ask.
I thought about regex also, but figured this was something that was better architecturally so could potentially be in core.

**Comment by deepu105** [comment]
not sure I guess you are the first one asking for such a feature. I have
personally done huge enterprise projects using Jhipster, but never had
these requirement.

You can check my [entity audit](
https://github.com/deepu105/generator-jhipster-entity-audit) module for ref
and also dont forget to use the [module-generator](
https://github.com/jhipster/generator-jhipster-module) to create a
skeleton, choose to post entity hook when asked in promts

Thanks & Regards,
Deepu

**Comment by amitjindal** [comment]
@deepu105 Great, thanks. Will follow your project to implement.
About separation, its not a project requirement, but simply a self imposed habit to separate these. I guess I assumed everyone would want to do this.

**Comment by jdubois** [comment]
The original idea (I'm not saying it's good, I'm just giving the context) is that:

- You have "/api" at the top of your REST controllers, so it's easy to migrate the URLs to something like "/api/v1"
- Classes are generated in their base package, but if needed you just you IDE to move them to another package (of course, re-generating entities will cause problems, but at that time this didn't exist)

Indeed, it could be more properties in the generator/sub-generators, or a specific module using the hooks, for a more complex project than what we provide by default.

**Comment by deepu105** [comment]
@jdubois, I like the idea of moving all entity resource.java to a new
package inside rest, what do you think?

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
@deepu105 it's like for the "domain" package, the idea was that everything is in the same package as it's easier to use (and generate!), and then people can refactor it easily, it's just a drag'n drop with their IDE: this is like our [Policy 2](http://jhipster.github.io/policies/) : having a new question is not worth it if you can do it with just one click with your IDE

**Comment by deepu105** [comment]
@jdubois, no no I don't want to have a new question, i was just suggesting
that having entity resources in a sub package by default might be nice

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Closing this as it will be a module
