### ISSUE TITLE
Update jhipster-ansible project to support new website

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#27288]
See https://github.com/jhipster/jhipster-ansible/issues/12. I'm adding this issue here for visibility and so I can assign a bug bounty to the effort.

##### **Overview of the issue**

The documentation archive process used in releases will fail unless the scripts are updated.

##### **Motivation for or Use Case**

A smooth release process.

##### **Reproduce the error**

Clone the jhipster-ansible project and run the following:

```
ansible-playbook -v playbooks/generator-jhipster-prepare.yml
```

##### **Related issues**

#27102

**Comment by IsitorViper** [comment]
Hi, I would like to be assigned to this task.

**Comment by mraible** [comment]
@IsitorViper You're welcome to start working on this.

**Comment by SvMak** [comment]
@mraible bug bounty claim https://opencollective.com/generator-jhipster/expenses/221135

**Comment by mraible** [comment]
@SvMak Approved.
