### ISSUE TITLE
How i can create a many to many relation with extra fields?

### ISSUE THREAD

**Issue by vitornobrega** [jhipster/generator-jhipster#2730]
Hi, i had read documentation about entities relations but i didn't found anything about many to many with extra fields.

I had create a many relation many to many but i have problems with my service. Maybe the relations aren't correct.

How i can create a many to many relation with aditional fields using jhipster? It's possible to add an option to add fields with jhipster? 

thanks

**Comment by jdubois** [comment]
You mean fields in the relationship table? We don't support this.
You need to do two one-to-many relationships, it's going to do the same result in the end.
I'm closing this as according to our guidelines this should go to StackOverflow -> can you open your question there?

**Comment by vitornobrega** [comment]
If the way to do this is create a two one-to-many relationships, i will do it. It's not necessary to open a new question in stackoverflow.

**Comment by jdubois** [comment]
Yes, it's just so that other people can benefit from the answer. And maybe you will have some better answers, I don't know everything :-)

**Comment by vitornobrega** [comment]
Ok, i will do it!
