### ISSUE TITLE
Documentation archives don't render properly: 404s for JS and CSS files

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#27315]
##### **Overview of the issue**

If you look at one of our documentation archive pages, you'll see it no longer renders properly. 

https://www.jhipster.tech/documentation-archive/v8.7.0/

This is because the HTML references CSS and JS files that no longer exist on the main site. 

##### **Motivation for or Use Case**

Our documentation archives should still work after the new site launch.

##### **Reproduce the error**

Visit https://www.jhipster.tech/documentation-archive/v8.7.0/. 

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/27288

##### **Suggest a Fix**

Update the documentation archive process to copy the CSS and JS with the distribution. Or we could add the missing JS and CSS files to the jhipster.github.io repo.

##### **JHipster Version(s)**

All

**Comment by c0d33ngr** [comment]
Some of the missing files. I'll submit PR to the jhipster.github.io repo
![jhipster_missing_files_screenshot](https://github.com/user-attachments/assets/b54ff38d-1465-4d9d-8ca4-3589e399a25c)

**Comment by mraible** [comment]
Thanks for your help, @SvMak!

**Comment by SvMak** [comment]
@mraible  bug bounty claim https://opencollective.com/generator-jhipster/expenses/221134

**Comment by mraible** [comment]
@SvMak Approved.
