### ISSUE TITLE
Docker container jhipster/jhipster for Apple Silicon CPU

### ISSUE THREAD

**Issue by donsez** [jhipster/generator-jhipster#27321]
##### **Overview of the feature request**

Docker Hub contains only images for Linux AMD64

https://hub.docker.com/r/jhipster/jhipster/tags

Is it possible to add the production and the publishing of images for Apple Silicon CPU ?

##### **Motivation for or Use Case**

More (energy) efficient build and exec on Apple MacOS hosts

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
It’s available in GitHub packages https://github.com/jhipster/generator-jhipster/pkgs/container/generator-jhipster/263811561?tag=v8.7.0.

@mraible maybe build scripts should be adjusted.

**Comment by mraible** [comment]
@mshima I'm not sure which part of the build process publishes Docker images. @pascalgrimaud Do you know?

**Comment by DanielFran** [comment]
@mraible Is this what you are looking for?
https://github.com/jhipster/generator-jhipster/blob/main/.github/workflows/docker-image-publish-github-registry.yml

**Comment by pascalgrimaud** [comment]
@DanielFran is right, it's exactly in this file

**Comment by mshima** [comment]
> @mraible Is this what you are looking for? https://github.com/jhipster/generator-jhipster/blob/main/.github/workflows/docker-image-publish-github-registry.yml

This workflow publishes to GitHub registry.
It’s not publishing to docker.
https://github.com/jhipster/generator-jhipster/actions/runs/10570274925/job/29284486040

**Comment by pascalgrimaud** [comment]
For me, it's published here, as it uses the DOCKERHUB_XXXX information:

https://github.com/jhipster/generator-jhipster/blob/main/.github/workflows/docker-image-publish-github-registry.yml#L60-L68

**Comment by mshima** [comment]
Indeed the action run is https://github.com/jhipster/generator-jhipster/actions/runs/10570274589/job/29284485150

**Comment by mshima** [comment]
Linux/arm64 is been published.

**Comment by DanielFran** [comment]
https://hub.docker.com/layers/jhipster/jhipster/v8.7.0/images/sha256-5de8f7275019fcdc2b85be8298f6fbbf73f56387cf6e8e76e29d8362ca0eb13b?context=explore
![image](https://github.com/user-attachments/assets/5645b1d4-e195-442e-9216-d404c80fc816)

**Comment by donsez** [comment]
Works fine on my Mac M1. Thanks

```
JHIPSTER_DOCKER_VERSION=v8.7.1
# DOCKER_PLATFORM=linux/amd64
DOCKER_PLATFORM=linux/arm64

docker pull  --platform=$DOCKER_PLATFORM jhipster/jhipster:$JHIPSTER_DOCKER_VERSION

docker container run  --platform=$DOCKER_PLATFORM --name jhipster \
    -v ~/jhipster:/home/jhipster/app \
    -v ~/.m2:/home/jhipster/.m2 \
    -v ~/jhipster-banner:/home/jhipster/generator-jhipster/generators/server/templates/src/main/resources \
    -p 8080:8080 -p 9000:9000 -p 3001:3001 \
    -d -t jhipster/jhipster:$JHIPSTER_DOCKER_VERSION

docker container exec -it jhipster bash
```
