### ISSUE TITLE
Java preprocessor doesn't work in JHipster project

### ISSUE THREAD

**Issue by delor** [jhipster/generator-jhipster#2734]
I have tried to use Lombok and http://immutables.github.io/ with JHipster project but it seams that something in build process is "blocking" preprocessor from generating code.

example source code https://bitbucket.org/delor/test_jhipster_immutables

JHipster Generator v2.27.0

**Comment by jdubois** [comment]
Not a JHipster bug, as we don't support Lombok.
And if look at the tickets history, you'll see I'm strongly against Lombok exactly for this kind of reasons.

**Comment by delor** [comment]
What about other libraries based on preprocessor? I do mention also Immutables library.

**Comment by jdubois** [comment]
We do support other Java annotation processors, like MapStruct or JPA, but we do a specific set up for them, and they don't all work together, this is why we limit them.
