### ISSUE TITLE
Upgrade blueprints to generator-jhipster v8.7.1

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#27357]
##### **Overview of the feature request**

Upgrade blueprints that not have an official maintainer, they are maintained by the team.
- [x] generator-jhipster-entity-audit - https://github.com/jhipster/generator-jhipster-entity-audit/pull/271
- [x] generator-jhipster-native - https://github.com/jhipster/generator-jhipster-native/pull/156
- [x] generator-jhipster-migrate - https://github.com/jhipster/generator-jhipster-migrate/pull/23
- [x] ~generator-jhipster-ionic~ - blueprint will require eslint v9 migration
- [ ] ~generator-jhipster-react-native~ - blueprint will require eslint v9 migration and is currently broken due to upstream changes.
- [ ] generator-jhipster-micronaut - https://github.com/jhipster/generator-jhipster-micronaut/pull/409
- ~generator-jhipster-nodejs~ - blueprint will require eslint v9 migration
- [ ] generator-jhipster-quarkus - https://github.com/jhipster/generator-jhipster-quarkus/pull/396
- [x] generator-jhipster-jooq - https://github.com/jhipster/generator-jhipster-jooq/pull/43
- ~generator-jhipster-svelte~ - has a maintainer, blueprint will require eslint v9 migration and has blueprint specifics like prettier and don't share CI patterns a specific issue is required.

Use new patterns in generate-blueprint:
- [x] use `asCommand` utility and try to add migration.
- [x] blueprint option is an array in tests and try to add migration.
- [x] add ignoreExistingGenerators option
- [x] drop vitest.test-setup.ts, not required anymore
- [x] enable queueCommandTasks.
- [x] add skipWorkflows option to avoid override modified workflows and try to add migration,

Node related blueprint will have a specific issue due to complexity.

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I added a bug bounty for this work. If it's not enough, please open additional issues.

**Comment by vishal423** [comment]
Svelte blueprint upgrade to 8.7.1 is almost done, so, you can close the task

**Comment by mshima** [comment]
- react-native blueprint CI is currently broken.
- nodejs blueprint requires eslint v9 adoption increasing difficult due to node nature.

This issue is complete.
