### ISSUE TITLE
Length of value DEFAULT_*FIELD* does not match with validation maxlength

### ISSUE THREAD

**Issue by javasparx** [jhipster/generator-jhipster#2739]
Hi guys,
I did not check minlength(L>5) but I think it has same problem.
I'm using jhipster-uml. But it is same as creating from terminal using 'yo jhipster:entity currency'.
```
entity Currency{
    date LocalDate required,
    rate BigDecimal required,
    code String maxlength(3),
    valid Boolean
}
```

**Currency.java**
```
...
    @Size(max = 3)
    @Column(name = "code", length = 3)
    private String code;
...
```

**CurrencyResourceIntTest.java**
```
...
private static final String DEFAULT_CODE = "AAAAA";
private static final String UPDATED_CODE = "BBBBB";
...
@Before
public void initTest() {
        currency = new Currency();
        currency.setDate(DEFAULT_DATE);
        currency.setRate(DEFAULT_RATE);
        currency.setCode(DEFAULT_CODE); // <---
        currency.setValid(DEFAULT_VALID);
}
```

java.lang.AssertionError: Status 
Expected :201
Actual   :400

**Comment by MathieuAA** [comment]
The problem seems to come from [here](https://github.com/jhipster/generator-jhipster/blob/master/entity/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java#L107).
