### ISSUE TITLE
[Feature] Multiple DB's

### ISSUE THREAD

**Issue by AlainJanssens** [jhipster/generator-jhipster#274]
Hi,

I saw that version 0.14 will support Mongodb, which is nice :-).

But I also saw you need to choose between sql or nosql. 
Wouldn't it be possible (or better ?!?) to be able to have a second DB's in your application?

Primary DB could be the DB where you manage the users, authorisations, ...
An optional second DB can be selected... 

Possible flow:
- What is the base name of your application?
- What is your default Java package name?
- Do you want to use Java 8?
- Which _type_ of database would you like to use as primary database? (H2, MySQL, PostgreSQL, Mongo)
- Which _type_ of database would you like to use as second database? (depends on previous choice or None)
- ...

Repositories linked to JPA go to package <packagename>/repositories/jpa/... or <packagename>/repositories/mongo/...
Idem for the Domain objects...

Can you give me your opinion about this? 
If this could be useful I can help to implement it.

(This will probably also make the implementation of elasticsearch easier in the future).

Regards

**Comment by amareshp** [comment]
@AlainJanssens - do you have a sample jhipster app that's using two databases. I want to use JHipster, but we have both Oracle and Cassandra as our data stores. If you have a sample app, please post the GitHub link.

**Comment by asiftasleem** [comment]
@AlainJanssens I am working on a new application and planning to mix MySQL with MongoDB for different purposes. Could you please share the sample app or the modified JHipster ?

**Comment by AVE-cesar** [comment]
+1

**Comment by jd-carroll** [comment]
IMO, I'm not sure this falls under the list of items JHipster should focus
on...

At the end of the day, it's still only a generator (probably the most
useful/relevant one I've ever found) and it cannot implement all of your
business requirements for you.

**Comment by abhisheksharma85** [comment]
So, I read these comment. 
By the way I am new to jHipster, pretty much just downloaded yesterday. 

We are about to start a new project where I think we need 2 DBs SQL for users and etc and Mongo for searching. Our application will have millions of images and search will have to be performed on Image Metadata. Each image has 50 fields, which user can search. 

I tried something using native Spring Framework, then I took it to Spring Boot but now I decided to use jHipster for my application so any help in this direction of 2 DBs will be very helpful.

**Comment by deepu105** [comment]
Did you try our elastic search option?

**Comment by jdubois** [comment]
And then you can either configure manually a second DB or wait for JHipster 3.0 with our microservice options (and btw the gateway in JHipster 3.0 can have 2 DBs).

**Comment by bhagujava** [comment]
Hey guys !!!

+1 for idea. 

I have seen your JHipster 3.0 release note  but not mention about this feature. any update on this ?

**Comment by alikemalocalan** [comment]
++1

**Comment by pengg** [comment]
++1, any update?

**Comment by jdubois** [comment]
This ticket has been closed 3 years ago, it won't be updated.

**Comment by pengg** [comment]
@jdubois  thanks for response,  is there a sample project for 2 dbs, like 1 for writing and 1 for query, even with 2 types? and where the configuration of 2DBs in gateway of microservices?

**Comment by deepu105** [comment]
No there is no sample as its not something we recommend


Thanks & Regards,
Deepu
