### ISSUE TITLE
Unable to (re)generate CI/CD pipeline with `jhipster ci-cd`

### ISSUE THREAD

**Issue by Alchemik** [jhipster/generator-jhipster#27405]
##### **Overview of the issue**

Since JHipster v8.7.0, I'm not able to generate CI pipeline with `jhipster ci-cd` sub-generator - as shown below, CLI skips initial platform type question and in result does not create any pipeline configuration.

![obraz](https://github.com/user-attachments/assets/efda6810-50d1-45ee-8116-629341ebedef)

I verified that v8.6.0 works as expected:
![obraz](https://github.com/user-attachments/assets/831a3920-0c18-4d9d-9f66-4bdb27aa864a)

##### **Reproduce the error**

* install JHipster: `npm install generator-jhipster@8.7.0`
* bootstrap project: `jhipster`
* run ci-cd subgenerator: `jhipster ci-cd`

##### **Related issues**

N/A

##### **Suggest a Fix**

N/A

##### **JHipster Version(s)**

**8.7.1**

##### **JHipster configuration**

WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
    If you want to execute the locally installed generator-jhipster, run: npx jhipster

Welcome to JHipster v8.7.1

Welcome to the JHipster Information Sub-Generator

```
jhipster-ci-cd-test@0.0.0 /Users/ljasek/IdeaProjects/demo_debug/jhipster-ci-cd-test
└── generator-jhipster@8.7.1
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "jhipsterCiCdTest",
    "buildTool": "gradle",
    "cacheProvider": "caffeine",
    "clientFramework": "no",
    "clientTestFrameworks": null,
    "clientTheme": null,
    "creationTimestamp": 1727173107481,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [],
    "feignClient": null,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.7.1",
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "skipClient": true,
    "syncUserWithIdp": null,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": null
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode)

git version 2.39.3 (Apple Git-146)

node: v20.17.0
npm: 10.8.2

Docker version 27.2.0, build 3ab4256

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Thanks for using JHipster!

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Added bug bounty to get this fixed.

**Comment by mshima** [comment]
As workaround pass the ci-cd options in cli: `jhipster ci-cd github jenkins ...`

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/239502.

**Comment by DanielFran** [comment]
@mshima approved

**Comment by Yahel974** [comment]
Still present on windows jhipster v9
The workaround by passing directly gitlab in the command line worked for me

**Comment by mshima** [comment]
@Yahel974 this is a v9 regression. Please open a new issue.
