### ISSUE TITLE
Rocky 9 - clean install Monolithic Application requires docker

### ISSUE THREAD

**Issue by RobertMolenda** [jhipster/generator-jhipster#27435]
##### **Should not require docker locally**

application will not start "out of box - per installation instructions"

##### **Reproduce the error**

follow installation guide:
install OpenJDK21 / Compiler 21 LTE
Install NodeJS / NPM
npm install -g yo
npm install -g generator-jhipster

mkdir testapp
cd testapp
jhipster
use all defaults - except for...
Databases : Production postgres / Dev H2 disk based

Build is successful

./mvnw
App fails to start

2024-09-28T07:49:49.765-07:00 ERROR 52422 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed 

org.springframework.boot.docker.compose.core.DockerProcessStartException: Unable to start docker process. Is docker correctly installed?
	at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.getDockerCommand(DockerCli.java:140)

.. note if prod database == oracle you get
Docker Compose file 'src/main/docker/services.yml' does not exist

##### **Suggest a Fix**
Require Docker on linux for local run probably - however will it also require on PROD? that's a no-bueno for our organization??

Spring boot is spring boot!

##### **JHipster Version(s)**

Welcome to JHipster v8.7.1

##### **JHipster configuration**
Welcome to JHipster v8.7.1

Welcome to the JHipster Information Sub-Generator

```
regulatory-360@0.0.1-SNAPSHOT /home/rmolenda/SurfingCactus/regulatory360
└── generator-jhipster@8.7.1
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "regulatory360",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientTestFrameworks": [],
    "clientTheme": "none",
    "creationTimestamp": 1727534635339,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [],
    "feignClient": null,
    "jhipsterVersion": "8.7.1",
    "languages": [
      "en"
    ],
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.surfingcactus",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],

    "serviceDiscoveryType": false,
    "syncUserWithIdp": null,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment (Red_Hat-21.0.4.0.7-1) (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.4.0.7-1) (build 21.0.4+7-LTS, mixed mode, sharing)

git version 2.43.5

node: v22.9.0
npm: 10.8.3

'docker' command could not be found

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Thanks for using JHipster!

**Comment by mshima** [comment]
The H2 was fixed in https://github.com/jhipster/generator-jhipster/pull/27380/files.
There is no predefined docker container for oracle and mysql. We probably should disable compose for them.

**Comment by RobertMolenda** [comment]
This issue is marked as closed - however - the current issue is that it still is not fixed under several "test builds"

create the application as previously documented and you will still get the same error (postgres production / H2 dev)

Change the Production Database to Oracle - and you get:
No Docker Compose file found in directory ...

Do I need to create a new ticket or ?
