### ISSUE TITLE
Mongo Java integration tests on entities are not running

### ISSUE THREAD

**Issue by amitjindal** [jhipster/generator-jhipster#2743]
**Overview of the issue**
When I run **mvn clean test** the tests for generated entities are not running.
The output generated is as follows. After that it simply sits there and does nothing:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
objc[30781]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Running com.aquevix.security.SecurityUtilsUnitTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 sec - in com.aquevix.security.SecurityUtilsUnitTest
Running com.aquevix.service.UserServiceIntTest

        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
        ██  ████████     ██     ███████    █████      ██     ██████    ███████
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██

:: JHipster 🤓  :: Running Spring Boot 1.3.1.RELEASE ::
:: http://jhipster.github.io ::

2016-01-31 11:22:34.026  INFO 30781 --- [           main] com.aquevix.service.UserServiceIntTest   : Starting UserServiceIntTest on tonystark.local with PID 30781 (/Users/amitjindal/tmp/jhipster/mongounittests/target/test-classes started by amitjindal in /Users/amitjindal/tmp/jhipster/mongounittests)
2016-01-31 11:22:34.030 DEBUG 30781 --- [           main] com.aquevix.service.UserServiceIntTest   : Running with Spring Boot v1.3.1.RELEASE, Spring v4.2.4.RELEASE
2016-01-31 11:22:34.030  INFO 30781 --- [           main] com.aquevix.service.UserServiceIntTest   : No active profile set, falling back to default profiles: default
2016-01-31 11:22:36.452 DEBUG 30781 --- [           main] com.aquevix.config.AsyncConfiguration    : Creating Async Task Executor
2016-01-31 11:22:36.667 DEBUG 30781 --- [           main] com.aquevix.config.MetricsConfiguration  : Registering JVM gauges
2016-01-31 11:22:36.680 DEBUG 30781 --- [           main] com.aquevix.config.MetricsConfiguration  : Initializing Metrics JMX reporting
2016-01-31 11:22:37.742  INFO 30781 --- [ost-startStop-1] com.aquevix.config.WebConfigurer         : Web application configuration, using profiles: []
2016-01-31 11:22:37.744 DEBUG 30781 --- [ost-startStop-1] com.aquevix.config.WebConfigurer         : Initializing Metrics registries
2016-01-31 11:22:37.748 DEBUG 30781 --- [ost-startStop-1] com.aquevix.config.WebConfigurer         : Registering Metrics Filter
2016-01-31 11:22:37.748 DEBUG 30781 --- [ost-startStop-1] com.aquevix.config.WebConfigurer         : Registering Metrics Servlet
2016-01-31 11:22:37.750  INFO 30781 --- [ost-startStop-1] com.aquevix.config.WebConfigurer         : Web application fully configured
```

**Motivation for or Use Case** 
The test should run.

**JHipster Version(s)** 
2.27.0 (master branch)
Latest. Downloaded 5 minutes ago.

**JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "baseName": "mongounittests",
    "packageName": "com.aquevix",
    "packageFolder": "com/aquevix",
    "authenticationType": "xauth",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "3995d8bb4849e6325446029ab8ba0feea846a06d",
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

**Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

**Entity: Employee**
```
{
    "relationships": [],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "fname",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 2,
            "fieldName": "lname",
            "fieldType": "String"
        },
        {
            "fieldId": 3,
            "fieldName": "createdOn",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 4,
            "fieldName": "isActive",
            "fieldType": "Boolean"
        }
    ],
    "dto": "mapstruct",
    "service": "serviceClass",
    "pagination": "pagination"
}
```

**Browsers and Operating System** 
Operating System: Mac OSX 10.11.2 El Capitan
Browser not relevant. This is command line problem.

**Reproduce the error** 
To reproduce the error:

1. Generate a blank project. Choose DTO, Service (without implementation), Mongodb.
1. Add any simple Entity with basic validation rules.

**Related issues** 
I searched but didn't find any.

**Suggest a Fix** 
This may be related to recent embedded mongo testing.
I tried to search for sunfire config and played with that but could not get it working. From IntelliJ I tried to run the test directly but that does not runs (hangs)

**Comment by amitjindal** [comment]
Could you please give an idea where to look for this. Right now we cannot even package in production as tests hang. I've tried playing with settings for tests also.

Also this is using the latest **master** branch code.

**Comment by jdubois** [comment]
You can try with some other options, or look at what embedded Mongo does: this is a recent change, I haven't used it myself.
I'm sorry but I don't have the time to test this this week.

**Comment by atomfrede** [comment]
@amitjindal Did you check if the unit test consider the generated validation rules?

> JHipster generates unit tests that work for generic entities, without knowing your validation rules: it is possible that the generated tests do not pass the validation rules. In that case, you will need to update the sample values used in your unit tests, so that they pass the validation rules.

**Comment by jdubois** [comment]
Can you check the difference with the sample project from Travis https://github.com/jhipster/generator-jhipster/tree/master/travis/samples/app-mongodb ? This Travis build is working, so obviously you have a different option that causes the issue.
And I'm convinced there is an issue here as [my sample project](https://github.com/jhipster/jhipster-sample-app-mongodb) also has some failing tests.
@pascalgrimaud maybe our Mongodb build isn't enough to test all use cases, it could be improved depending on what we find here.

**Comment by pascalgrimaud** [comment]
the main difference with travis build is : "authenticationType": "xauth"
I'll have a look

**Comment by amitjindal** [comment]
@atomfrede No I did not check the validation rules in all cases but there are simple classes which have no validation rules. Let me check them once.

**Comment by amitjindal** [comment]
@atomfrede Just checked. I had a test from above Employee object with first name required and createdOn required validation. I checked the values and they were correct. I ran only that test. Its still hanging. So most likely that is not the cause.

**Comment by atomfrede** [comment]
@amitjindal Have you tried waiting a little longer? I thought I could reproduce your error (mvn clean install seems to hang at Web application fully configured) but after waiting a little longer all tests passed. A second run is much faster (1st: ~2min, 2nd: ~35sec), it looks like embedded mongo needs to download something in background.

**Comment by amitjindal** [comment]
@atomfrede
Oh, crap. Didn't thought about that. Now its running here as well. I think I was terminating again and again so it probably never finished downloading what it started. I was trying this at home so probably the time taken was much longer due to slower network speed.

Thank you so much!
Sorry for causing inconvenience.
