### ISSUE TITLE
JHipster doc link is broken

### ISSUE THREAD

**Issue by canercin** [jhipster/generator-jhipster#27491]
I want to learn creating Service classes but site say's that error. Can you help me?  https://www.jhipster.tech/creating-a-service/

**Comment by mraible** [comment]
Thanks for the bug report. How are you getting to this URL? Are you able to find the page for the version you're using in our documentation archives? https://www.jhipster.tech/documentation-archive/

**Comment by canercin** [comment]
Hello. I don't try docs archive. I access this link from current docs, https://www.jhipster.tech/creating-an-entity/#generating-a-separate-service-class-for-your-business-logic .
