### ISSUE TITLE
Migrate to gulp and move grunt to a module/tip

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2749]
Based on discussion and vote [here](https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/pSQXz_NWcZ0/iqC3tqUHDQAJ)

Make gulp as default front end build tool.
Remove grunt from main generator 
Make grunt build a module or tip
Improve the gulp build where possible
Add gulp notify coz its cool
Reorganize and simplify gulp build
Move utils used to its own file

**Comment by deepu105** [comment]
Cc @ngasull @erikkemperman @amr

**Comment by pascalgrimaud** [comment]
I can help and rework on Travis build, if you need, @deepu105

**Comment by deepu105** [comment]
ill do first push, take a look and see what needs improvement

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
It can be done separately.
Currently, our Travis uses grunt on 13/14... Only 1 uses gulp. I will change it

**Comment by deepu105** [comment]
I already removed that i guess, let me do a PR its almost ready
