### ISSUE TITLE
Remove beta tag from mapstruct and service options

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2751]
Its been quite a while since these are in beta. We should remove the tags for next major

**Comment by jdubois** [comment]
- For the service option I've had no bad feedback, so yes it could be removed
- For MapStruct we still have at least one ticket opened, and I don't know how to solve this, so for me it's still beta

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/commit/94dca1b724ec6ae089a169c7fda5e4362ce31a6e
