### ISSUE TITLE
Migrate Docker build to JHipster organization

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#2754]
Currently, the official Docker image is jdubois/jhipster-docker

About this migration:
1) rename to jhipster/jhipster (@jdubois will make the final choice)

2) this repository generator-jhipster will contain a new file `Dockerfile` => root or sub folder ? I don't want to confuse people with sub generator. What do you think ?

3) every tag (release) will trigger 2 builds : latest and vX.Y.Z
- jhipster/jhipster:latest = will be the latest release
- jhipster/jhipster:vX.Y.Z = will be the tag

4) Every commit/merge to master will trigger a build
- jhipster/jhipster:master

5) remove grunt-cli #2749

6) the project jhipster/jhipster-docker will be deprecated

**Comment by jdubois** [comment]
Last time I checked (1 months ago) I had an issue with migrating to the JHipster organization: I couldn't have automatic builds for the organization, only on my own "jdubois" name.
Organizations are very new in the Docker interface, and it is still lacking a lot of options.

So my goal is indeed to migrate to the "jhipster" organization, but at the moment I don't think it is possible from a technical point of view.

**Comment by pascalgrimaud** [comment]
@jdubois : I've just created an organization on Docker Hub and I can have automatic builds.
Maybe because I am on the team : **owners**
Can you confirm me if you are in team "owners" on JHipster organization ? I can see only the team "developers"

**Comment by jdubois** [comment]
Yes I am on the team "owners" but that doesn't make any difference anyway: I don't see where you put permissions on a team, so it's the same as the "developers" team.
I've tried again, I can click "automated build", but then I can only do them for my user, not for the organization. Can you test it from end-to-end? As far as I can see this the UI isn't finished yet.

**Comment by pascalgrimaud** [comment]
Just tried it, and it works https://hub.docker.com/r/pgrim/dockerfiles/
- organization : pgrim (created few seconds ago)
- repo : dockerfiles

**Comment by jdubois** [comment]
I just made you an owner of the "jhipster" team: I don't think it does anything, but if you can try...

**Comment by pascalgrimaud** [comment]
I can see jhipster when selecting Repository namespace !
So what is the name you want ?
- jhipster/jhipster ?
- jhipster/generator-jhipster ?
- another ?

**Comment by jdubois** [comment]
jhipster/jhipster has it's our default image, it looks like the most obvious choice.
Are you sure you can do an automated build here???? I really can't find the option

**Comment by pascalgrimaud** [comment]
Yes, I created it : https://hub.docker.com/r/jhipster/jhipster/ :whale: 
I will do PR with a new Dockerfile tomorrow, too tired for tonight :-)

**Comment by jdubois** [comment]
I don't understand how you did it!!!!
Anyway -> I'm just going to rename the description to tell it's not the official image yet! It will become official with the next version

**Comment by pascalgrimaud** [comment]
I don't understand too lol
Yes you're right. You can rename it.

But, should I trigger a new build for every commit/merge to master ?
- jhipster/jhipster:master => current master

For releases :
- jhipster/jhipster:latest => latest tag
- jhipster/jhipster:vX.Y.Z => all old tags

**Comment by jdubois** [comment]
The current build is triggered on every push, but indeed that might not be a good idea! I don't really know what's the best option, I want it to be automated, but maybe not for every push.... In doubt, keep it the way it is today, on every push.

**Comment by deepu105** [comment]
Shouldn't t be for every release?

**Comment by pascalgrimaud** [comment]
It will be for both: current master and tags
I will monitor the master build by docker hub, to check if it's too much

**Comment by pascalgrimaud** [comment]
In fact, the image jdubois/jhipster-docker has only one version: latest
Now, we ll use different version:
master, latest, v3.0.0, v3.1.0 etc...

So there will be different images:
jhipster/jhipster:master 
jhipster/jhipster:latest <== the default, latest tag
jhipster/jhipster:v3.0.0
Etc

**Comment by jdubois** [comment]
Oh I didn't know that, it's much better !
Le 2 févr. 2016 8:56 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by pascalgrimaud** [comment]
@jdubois : last thing to check : can you go to settings in this repository and verify if there is a webhook on Docker plz ?

**Comment by jdubois** [comment]
You mean here: https://hub.docker.com/r/jhipster/jhipster/~/settings/webhooks/
I don't see any webhook there

**Comment by pascalgrimaud** [comment]
No Julien, on Github plz

**Comment by jdubois** [comment]
Oh yes I see a Docker webhook!

**Comment by pascalgrimaud** [comment]
Thanks, I do param on docker hub, let's see if the webhook works

**Comment by pascalgrimaud** [comment]
it seems the webhook doesn't work...
There is only 1 build which has been triggered manually yesterday by me : https://hub.docker.com/r/jhipster/jhipster/builds/

I create a new branch [test-docker-hub](https://github.com/jhipster/generator-jhipster/tree/test-docker-hub) to make tests, every push to this branch should trigger a build

@jdubois : maybe remove the Docker webhook (settings on GitHub generator-jhipster) and re-add it plz ?

**Comment by jdubois** [comment]
OK I will check this, but I won't have much free time until next week.
Le 3 févr. 2016 7:18 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
I have "updated" the webhook, I don't know if it will do anything...

On Wed, Feb 3, 2016 at 8:57 AM, Julien Dubois <julien.dubois@gmail.com>
wrote:

> OK I will check this, but I won't have much free time until next week.
> Le 3 févr. 2016 7:18 AM, "Pascal Grimaud" <notifications@github.com> a
> écrit :
>
>> it seems the webhook doesn't work...
>> There is only 1 build which has been triggered manually yesterday by me :
>> https://hub.docker.com/r/jhipster/jhipster/builds/
>>
>> I create a new branch test-docker-hub
>> <https://github.com/jhipster/generator-jhipster/tree/test-docker-hub> to
>> make tests, every push to this branch should trigger a build
>>
>> @jdubois <https://github.com/jdubois> : maybe remove the Docker webhook
>> (settings on GitHub generator-jhipster) and re-add it plz ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jhipster/generator-jhipster/issues/2754#issuecomment-179031884>
>> .
>>
>


-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by pascalgrimaud** [comment]
it should rather be "Services / Manage Docker" with a button Test service

Anyway, it doesn't work :( Just commit to branch test-docker-hub and no build is triggered

**Comment by jdubois** [comment]
@pascalgrimaud can we close this, now it's done? Next release will use this.

**Comment by pascalgrimaud** [comment]
Not yet, I see some issue (multiple triggers)... I'm investigating

**Comment by pascalgrimaud** [comment]
Finally, it seems to work correctly now!
Thanks Julien !

Next release v3.0.0, I will have a closed look to Docker Hub

**Comment by pascalgrimaud** [comment]
Just FYI, after monitoring during ~20days, I decide to remove the build settings on master.
The image **jhipster/jhipster:master** won't be update after every merge/push
It triggered too much build for Docker Hub and there is no value

The build settings is now:
- tag -> latest
- tag -> vX.Y.Z
