### ISSUE TITLE
Bump transactional dependencies fails due to types

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#27557]
##### **Overview of the issue**

See https://github.com/jhipster/generator-jhipster/actions/runs/11301002835/job/31434750994

Cc @mshima 
##### **JHipster configuration**

To provide all information we need, you should run `jhipster info` in the project root folder (or workspaces root for microservices), and
copy/paste the result here.
`jhipster info` removes sentitive information like rememberKey, jwtSecretKey. Double check if there is any other sensitive info.

As alternative you can add a JDL wrapped in below structure

  <details>
  <summary>JDL definitions</summary>
  <pre>
     JDL content here
  </pre>
  </details>

The information is mandatory for bug reports. This will allow us to use automated tests and genarate the broken sample using `jhipster from-issue` command.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran should be fixed by https://github.com/jhipster/generator-jhipster/pull/27553.

**Comment by DanielFran** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/27553.
