### ISSUE TITLE
Links to module functions doc in the creating-a-module page

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2755]
It would be handy to have links to the script-base's jhipsterFunc from the creating-a-module page to have a quick view of the protoype and the function doc.

**Comment by deepu105** [comment]
yes plz

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Yes, and we should also be able to generate some kind of "javadoc" from those functions -> anyone knows how this works?
@cbornet do you want to make a PR with the links in https://github.com/jhipster/jhipster.github.io/tree/v3_preparation ?

**Comment by deepu105** [comment]
@cbornet can we close this and track it in #2785

**Comment by cbornet** [comment]
@deepu105 yes ! Can you add it to the TODO ?
