### ISSUE TITLE
Content Security Policy (CSP)

### ISSUE THREAD

**Issue by hoang1998lqd** [jhipster/generator-jhipster#27595]
> I am having trouble configuring Content Security Policy (CSP) at the gateway when not using 'unsafe-eval' 'unsafe-inline' in the configuration.

Using jhipster version 6.10.5, Node version 16.17.0

**Comment by mraible** [comment]
Can you please explain your issue in more detail? It's really hard to fix a bug if we can't reproduce it.

**Comment by hoang1998lqd** [comment]
![image](https://github.com/user-attachments/assets/1c926e01-172a-45d3-a116-773bb7d224e4)

> **When I configure the content security section as shown in the image, an error appears in Angular as shown below.**

![image](https://github.com/user-attachments/assets/2432405a-fde9-4843-80b2-bfaeb494af67)

**Comment by OmarHawk** [comment]
You are on a super old version. In more recent versions, the amount of issues regarding such CSPs (without unsafe-inline) dropped   severely, so I do suggest upgrading your application first to the latest version.

**Comment by mshima** [comment]
JHipster 6 is too old. You should upgrade.
