### ISSUE TITLE
includeDBconfig is false even after explicitly setting as true

### ISSUE THREAD

**Issue by VijayDev98** [jhipster/generator-jhipster#27609]
I am working on jhipster 8.5.0 while generating application using prompt i have given database details and i want to do few changes in DB,
while using this.includeDBconfig default it is coming as false .

I tried to add the this.includeDBConfig = true; and even after adding i am getting false.

Below is the yo-rc
"databaseType": "sql",
    "devDatabaseType": "postgresql",

**Comment by mshima** [comment]
`includeDBConfig` doesn't exist.

**Comment by VijayDev98** [comment]
Is there any other flag alternative of includeDBConfig that can be used in custom blueprint?

**Comment by mshima** [comment]
You should explain what issue you are having.

**Comment by mraible** [comment]
Please reopen if you're still having an issue and explain your problem in more detail.
