### ISSUE TITLE
marketplace doesnt work on android browsers

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2762]
Strange issue: marketplace doesnt work on android browsers
seems like the npmsearch.com queries are stuck
same used in slushjs.github.io seems to work in mobile could be some useragent or header issue

**Comment by jdubois** [comment]
Yes that's probably the issue.
Then we are stuck and we can't keep it like that: see why I didn't want to rely on an external service? It always break and we don't have the resources to do maintenance.
Anyway, shouldn't we go back to my original .json file?

**Comment by deepu105** [comment]
problem is the service isn't down, its working I think there is some issue with headers we sent from mobile. lets try to solve it if not we can put back the json as the backup

**Comment by deepu105** [comment]
Found the issue fix is on the way

Thanks & Regards,
Deepu
