### ISSUE TITLE
command `jhipster jdl name.jdl --skip-db-changelog` need execute twice and `liquibase:diff` can not generate remarks

### ISSUE THREAD

**Issue by flyliu33** [jhipster/generator-jhipster#27647]
##### **Overview of the issue**
1. command `jhipster jdl ..\order\src\main\jdl\order.jdl   --skip-db-changelog` need execute twice. First time, it only create entity.json, Second time, it can generate the target code.
2. command `./mvnw compile liquibase:diff` can't generate remarks of liquibase changelogs, though there is comments on the jdl file.

##### **Motivation for or Use Case**
1. I want to use jdl for maintain my code and database.

##### **Reproduce the error**
1. execute command `jhipster jdl ..\order\src\main\jdl\order.jdl   --skip-db-changelog`
2. execute command `./mvnw compile liquibase:diff`

##### **JHipster Version(s)**
8.7.1

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "authenticationType": "jwt",
    "baseName": "management",
    "buildTool": "maven",
    "cacheProvider": "redis",
    "clientFramework": "no",
    "clientTestFrameworks": null,
    "clientTheme": null,
    "creationTimestamp": 1726898624698,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [
      "Invoice"
    ],
    "feignClient": true,
    "jhipsterVersion": "8.7.1",
    "lastLiquibaseTimestamp": 1729564527000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "zh-cn",
    "packageName": "com.pu.management",
    "prodDatabaseType": "mysql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8081",
    "serverSideOptions": [],
    "serviceDiscoveryType": "consul",
    "skipClient": true,
    "skipUserManagement": true,
    "syncUserWithIdp": null,
    "testFrameworks": [
      "gatling"
    ],
    "websocket": false,
    "withAdminUi": null
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.12" 2024-07-16 LTS
OpenJDK Runtime Environment Corretto-17.0.12.7.1 (build 17.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.12.7.1 (build 17.0.12+7-LTS, mixed mode, sharing)

git version 2.45.1.windows.1

node: v20.17.0
npm: 10.8.2

Docker version 27.1.1, build 6312585

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Invoice
 */
@ChangelogDate("20241022023527")
entity Invoice {
  /**
   * Invoice Type
   */
  invoiceType InvoiceType required
  /**
   * Invoice Serial Number
   */
  invoiceNo String maxlength(15) required
  /**
   * Parking Lot Order Number
   */
  orderNo String required
  /**
   * Invoice Amount
   */
  amount Long required
  /**
   * Application Time
   */
  createTime Instant required
  /**
   * Invoice Title
   */
  title String maxlength(50) required
  /**
   * Mobile Number
   */
  mobileNo String maxlength(11) required
  /**
   * Company Tax Number
   */
  taxNo String maxlength(20)
  /**
   * Company Address
   */
  address String maxlength(100)
  /**
   * Telephone Number
   */
  telephoneNo String maxlength(20)
  /**
   * Bank Name
   */
  bankName String maxlength(100)
  /**
   * Bank Account Number
   */
  debitNo String maxlength(20)
  /**
   * Email Address
   */
  email String maxlength(50)
}

enum InvoiceType {
  REGULAR,    // Regular Invoice
  SPECIAL,    // Special Invoice
  PERSON      // Personal Invoice
}

paginate Invoice with pagination
search Invoice with no
microservice Invoice with Order
clientRootFolder Invoice with Order

</pre>
</details>

##### **Browsers and Operating System**

Edition	Windows 11 Pro
Version	23H2
Installed on	‎8/‎19/‎2024
OS build	22631.4317
Experience	Windows Feature Experience Pack 1000.22700.1041.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by flyliu33** [comment]
[park-union.txt](https://github.com/user-attachments/files/17488898/park-union.txt)
I also have to execute `jhipster jdl park-union.jdl` twice to generate the entire code. BTW, even though I assigned a name for dockerRepositoryName, but it still cannot create the correct image reference in the target docker-compose.yml file.
```
services:
  gateway:
    **image: gateway**
    environment:
```

**Comment by flyliu33** [comment]
consider if there was something wrong on my `order.jdl` file. I can generate succeccfully with the official sample file `microservice-ecommerce-reactive.jdl` for one time.

**Comment by mshima** [comment]
Closing, the reproduction jdl file is missing.
