### ISSUE TITLE
Bootstrap fonts not working on production non-sass build.

### ISSUE THREAD

**Issue by erikkemperman** [jhipster/generator-jhipster#2767]
I think this might have been caused by the recent structural changes? Anyway, this is happening for current master.

EDIT Just to be explicit, this is about the icons.

**Comment by deepu105** [comment]
@erikkemperman do you have time to look at this?

**Comment by erikkemperman** [comment]
@deepu105 Not really, sorry..

**Comment by cbornet** [comment]
I think that with gulp, bootstrap fonts are not copied to assets
This is how it was done with grunt:
```javascript
            fonts: {
                files: [{
                    expand: true,
                    dot: true,
                    flatten: true,
                    cwd: 'src/main/webapp',
                    dest: '<%%= yeoman.dist %>/assets/fonts',
                    src: [
                      'bower_components/bootstrap/fonts/*.*'
                    ]
                }]
            }
```
and I don't find a similar task in gulp

**Comment by erikkemperman** [comment]
@cbornet I did see a `copy` task in the [gulpfile](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/gulpfile.js#L62) though, but that doesn't find any fonts in `content`.

**Comment by cbornet** [comment]
Yes. Need to add to this task
```javascript
        gulp.src(config.app + 'bower_components/bootstrap/fonts/*.*')
        .pipe(plumber({errorHandler: handleErrors}))
        .pipe(flatten())
        .pipe(gulp.dest(config.dist + 'content/fonts/'))
```

**Comment by deepu105** [comment]
Can you add that plz

**Comment by erikkemperman** [comment]
Thanks!
