### ISSUE TITLE
Validation query when using Oracle database

### ISSUE THREAD

**Issue by eredwan** [jhipster/generator-jhipster#2769]
EDIT: This fix is relating to a Hikari error with something about isValid(). I am using an oracle database at work. I added a test query and everything worked fine after that. See below.

Add on Line 71 of DatabaseConfiguration.java.
```
 if(dataSourceProperties.getUrl().toString().toUpperCase().contains("ORACLE"))
 {
       config.setConnectionTestQuery("SELECT 1 FROM DUAL");
 }
```

**Comment by eredwan** [comment]
Correction:
```
 if(dataSourceProperties.getUrl().toString().toUpperCase().contains("ORACLE"))
 {
       config.setConnectionTestQuery("SELECT 1 FROM DUAL");
 }
```

**Comment by gmarziou** [comment]
Would you consider to submit a PR?

**Comment by jdubois** [comment]
I edited the title to make it clearer.

**Comment by jdubois** [comment]
And can you follow the [guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) when submitting a bug?

**Comment by deepu105** [comment]
@eredwan Why is this required?? this is already done by actuator health checks. Is there any other need you are adding this for?

**Comment by gmarziou** [comment]
This is used by the connection pool to test whether the connection is still alive, it is usually done either on getting a connection from the pool or on returning it to the pool

**Comment by deepu105** [comment]
oh ok

Thanks & Regards,
Deepu

**Comment by cbornet** [comment]
Does somebody know why we don't use the SB autoconfiguration for the DataSource ?

**Comment by jdubois** [comment]
Initially it was because they didn't provide all the options we needed, and they did not support HikariCP.
Now things have changed, of course, so this something that could be checked: we still have quite a lot of specific JHipster configuration there (for monitoring, for tuning MySQL, etc) so I'm not sure we can use the standard autoconfiguration.

**Comment by cbornet** [comment]
I just tried and HikariCP works well but indeed we lose a lot of dropwizard metrics.
It's too bad that SB doesn't detect dropwizard for datasource and cache...

**Comment by cbornet** [comment]
Then mayby use [@ConfigurationProperties](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties) to enable all datasource properties from the config file (this is what is done by SB autoconf) ?

**Comment by cbornet** [comment]
I have it working with ConfigurationProperties. I'll PR tomorrow.

**Comment by cbornet** [comment]
#2803 allows to configure this from application.yml
Now the question would be : should it be set by default. I don't know what the recommendation is with Hikari

**Comment by cbornet** [comment]
> connectionTestQuery
If your driver supports JDBC4 we strongly recommend not setting this property. This is for "legacy" databases that do not support the JDBC4 Connection.isValid() API. This is the query that will be executed just before a connection is given to you from the pool to validate that the connection to the database is still alive. Again, try running the pool without this property, HikariCP will log an error if your driver is not JDBC4 compliant to let you know. Default: none
So the question is about the JDBC version of Oracle. Anybody knows ?

**Comment by gmarziou** [comment]
Versions 11 and 12 are JDBC 4 compliant.

**Comment by cbornet** [comment]
Reading [this](http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-faq-090281.html), I'm not sure this should be set as default (we use ojdbc7).
@eredwan what is your Oracle version ?

**Comment by deepu105** [comment]
I dont think its request for oracle i have application in production with
Oracle and i didn't set it and i didn't have any error so far

**Comment by eredwan** [comment]
I am using Oracle 10g and ojdbc14

**Comment by deepu105** [comment]
Sorry but we support only 12c and above

**Comment by deepu105** [comment]
If you are interested you can add this as a tip in our documentation site.

**Comment by cbornet** [comment]
@eredwan with the PR #2803 you will be able to do it from your application.yml with 
```yaml
spring.datasource.hikari.connection-test-query: SELECT 1 FROM DUAL
```
Meanwhile, you can use your code configuration

**Comment by eredwan** [comment]
Ya no problem. I've already figured it out with the code configuration. I
am limited to this oracle version because of my corporate work.
