### ISSUE TITLE
Can't read swagger JSON from http://localhost:9000/api-docs/

### ISSUE THREAD

**Issue by firefoxNX** [jhipster/generator-jhipster#277]
The api-docs was working fine earlier. It stopped working and now I get
Can't read swagger JSON from http://localhost:9000/api-docs/

If I change src/main/webapp/swagger-ui/index.html
var apiUrl = "http://localhost:8080/swagger-ui/index.html";
I get "Can't read from server. It may not have the appropriate access-control-origin settings."

**Comment by NicholasRBowers** [comment]
Since this issue has closed, this project has migrated to Gulp.  Is there an analogous fix within the gulpfile?

**Comment by xenogew** [comment]
I can't find any connect/proxies section in Gruntfile.js.

Is it involve with grunt-connect-proxy, do I have to install it before put the configuration to Gruntfile.js?

**Comment by jdubois** [comment]
Please don't comment closed issues, we don't work on them anymore

**Comment by songyalong** [comment]
review your web.xml swagger use selevt DispatcherServlet url-pattern I change *.do to / it's OK
