### ISSUE TITLE
.gitignore must NOT ignore .idea/ folder

### ISSUE THREAD

**Issue by earizon** [jhipster/generator-jhipster#27708]
##### **Overview of the issue**

.gitignore removes .idea from git, but .idea has been designed to be versioned and shared in .git 
Only a few files inside .idea/ must not be versioned as explained in:
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

NOTE: idea itself add an .idea/.gitignore file, so it is quite safe to just remove .idea from .gitignore.

##### **Motivation for or Use Case**

Sharing .idea folder is a "best pattern".

##### **Reproduce the error**

Any new project inherits the .gitignore with the extra ".idea" line.

##### **Suggest a Fix**

Remove .idea from .gitignore.

##### **JHipster Version(s)**

tested in latest version.

##### **JHipster configuration**

N/A

##### **Browsers and Operating System**

Browser/OS independent.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Personally, I like to ignore `.idea/` in .gitignore. Mostly because I don't expect other developers to use IntelliJ IDEA.

**Comment by atomfrede** [comment]
Me too, but I was not aware it contains stuff to be shared and I never tried it on any of my teams.

**Comment by amatosg** [comment]
> Personally, I like to ignore `.idea/` in .gitignore. Mostly because I don't expect other developers to use IntelliJ IDEA.

I think the same, but it doesn't hurt to have it there just in case another user uses IntelliJ. Is just a plus

**Comment by wangxinxx** [comment]
> Personally, I like to ignore `.idea/` in .gitignore. Mostly because I don't expect other developers to use IntelliJ IDEA.

The increase in the number of participants at any time and the more personalized content may have negative effects.

**Comment by earizon** [comment]
I was trying to share the folder with my work colleges. While the official documentation tell to do so, we found quite a lot of problems in my team with "always changing" files. So I guess my initial idea was a bad idea. I close it for now to further investigate how to properly manage this directory in git.
