### ISSUE TITLE
AuthenticationProvider is never be used.

### ISSUE THREAD

**Issue by clong365** [jhipster/generator-jhipster#2772]
It seems that AuthenticationProvider is never be used.

First, I set a breakpoin in method authenticate(), but never bean reached here.

Then, I deleted the AuthenticationProvider.java, and the application worked well.

**Comment by gmarziou** [comment]
Which authentication mechanism did you select when generating your app?

**Comment by jdubois** [comment]
This rings a bell, and I think you are right, at least there is something to check here.
But please, can you follow the [guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md).

**Comment by clong365** [comment]
v2.27.0
`{
  "generator-jhipster": {
    "baseName": "jiashang",
    "packageName": "com.hotelsjianguo.jiashang",
    "packageFolder": "com/hotelsjianguo/jiashang",
    "authenticationType": "xauth",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": false,
    "enableSocialSignIn": false,
    "rememberMeKey": "63ddb1dabbb7dbc94dfc556c510d2301c76e5595",
    "testFrameworks": []
  }
}`

**Comment by jdubois** [comment]
This is only for XAuth (and same thing for JWT which replaces it in 3.0), and indeed it looks like it's being used at all.
