### ISSUE TITLE
.Net blueprint cannot be released due to modularization specifics.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#27764]
##### **Overview of the issue**

.Net blueprint generates a quite different structure.
JHipster modular support needs adjusts.

Java based projects:
```
- package.json
- src/main/webapp (client)
- src/main/docker (docker)
- * (java)
```

.Net:
```
- package.json (husky and prettier that needs to be in git root)
- src/Jhipster/ClientApp (client)
- src/Jhipster/ClientApp/package.json (client dependencies/eslint)
- src/* (dotnetcore)
- test/* (dotnetcore)
```

There are 2 package.json to be considered: at root and at client folder.

Currently if the dependency is in package.json templates it will be written to client's package.json and if the dependency is injected it will be written to root's package.json.
Same for scripts.

We should add an api to write to client's package.json and adjust insertions.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bug bounty claimed https://opencollective.com/generator-jhipster/expenses/233111

**Comment by DanielFran** [comment]
@mshima approved
