### ISSUE TITLE
Documentation archive not updating for 8.7.3

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#27770]
##### **Overview of the issue**

The [documentation archive](https://www.jhipster.tech/documentation-archive/) hasn't been updated for 8.7.3. Builds are [running](https://github.com/jhipster/documentation-archive/actions), but not passing. I'm unsure where this job is configured.

##### **Motivation for or Use Case**

Docs aren't updated for 8.7.3.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/27719

##### **Suggest a Fix**

Not sure.

##### **JHipster Version(s)**

8.7.3

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@pascalgrimaud Do you know why this isn't working? One thought I had is we might've reached our limit on the max size of the repo.

**Comment by pascalgrimaud** [comment]
The last time I work on this project, we already reached the limit, so it looks like the same issue:
- I didn't manage to see the logs: https://github.com/jhipster/documentation-archive/actions/runs/11644067096/job/32446901027

I don't think our users will look the documentation for v2.x for example. So we should delete from git the old folders to clean space

**Comment by mraible** [comment]
I wonder if any of the techniques in this blog post can be used? https://www.jonathancreamer.com/how-we-shrunk-our-git-repo-size-by-94-percent/

**Comment by mraible** [comment]
@SvMak: Should there be hundreds of files under /asset/js? 

https://github.com/jhipster/documentation-archive/tree/gh-pages/v8.7.2/assets/js has 449 files in it.

**Comment by pascalgrimaud** [comment]
here the original issue:
- https://github.com/jhipster/generator-jhipster/issues/18318

here the PR which fixed it:
- https://github.com/jhipster/documentation-archive/pull/130

the old docs should be in this repo:
- https://github.com/jhipster/documentation-archive-v1-to-v5

But, as the architecture has changed since the migration to the new website, I don't understand why we have the old folders here:
![image](https://github.com/user-attachments/assets/f6d5b861-b7e7-4b29-8d41-f5a8c3ede4e1)

As @SvMak did the migration, he probably knows better than us:
- https://github.com/jhipster/jhipster-ansible/pull/13

**Comment by SvMak** [comment]
Thanks for the reporting, I'll check what I can do with it.

Potentially we can remove some duplicates after the previous split repo and create a split repo again, but I need some time for correct solution.

**Comment by SvMak** [comment]
> @SvMak: Should there be hundreds of files under /asset/js?
> 
> https://github.com/jhipster/documentation-archive/tree/gh-pages/v8.7.2/assets/js has 449 files in it.

Yes it's chunks

**Comment by SvMak** [comment]
@mraible We can try merge [cleanup unused](https://github.com/jhipster/documentation-archive/pull/153)

Also I'll need to check the ansible scripts, in v8.7.3 I find `build` folder - that's doubled the output size, as for the rest, I'm still research the issue.

**Comment by SvMak** [comment]
I've improvement the ansible documentation-archive-prepare script, this should prevent duplicates of the same version from being created if someone ran it many times.

Could you create a repo with name documentation-archive-v6-to-v7, I'll need to do two PRs for fixing size issue?

**Comment by SvMak** [comment]
@mraible bug bounty claim https://opencollective.com/generator-jhipster/expenses/227954

**Comment by mraible** [comment]
@SvMak Approved.
