### ISSUE TITLE
Cache does not work

### ISSUE THREAD

**Issue by akeske** [jhipster/generator-jhipster#2778]
I think but correct me if i am wrong that second cache memory does not work, as i said on
[stackoverflow](http://stackoverflow.com/questions/34946471/jhipster-ldap-authentication-query-for-additional-user-attributes/35179255#35179255)

I believe that i have the solution and i want to share it with you, If i am absolutely wrong forgive me! :P

**Comment by gmarziou** [comment]
You answer on SO is not very clear, please follow [our guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-submission-guidelines) to submit an issue here and add required details.

**Comment by jdubois** [comment]
Please follow the [guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md), you're the third one today to submit an incomplete bug report!

**Comment by deepu105** [comment]
closing this as I dont see any issue mentioned about Jhipster and LDAP we don't officially support.

Plz ask to reopen if you have more details
