### ISSUE TITLE
update documentation for next

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2785]
we need to update docs for next major. plz add on if i missed anything @jhipster/developers 

- [x] 1. new angular folder structure & john papa style guideline
- [x] 2. ~~removal of fast~~ - PR submitted
- [x] 3. skip-client option - PR submitted
- [x] 4. grunt to gulp
- [x] 5. docker updates
- [x] 6. microservices - PR submitted, needs more contents
- [x] 7. naming convention updates for angular side and api endpoints, pluralization
- [x] 8. ~~entity update option~~ -PR submitted
- [x] 9. new advanced server & client sub gen 
- [x] 10. update contribution.md to advice new structure changes if required
- [x] 11. we also need to update the presentation 
- [x] 12. ~~update the videos~~ - Done
- [x] 13. We need to update the setting-CI page with gulp and remove the "Configuring Javascript Tests" which is now included by default.
- [x] 14. new --table-name flag in entity sub gen
- [x] 15. --with-entities to regen all entities
- [x] 16. --no-notification flag for gulp
- [x] 17 --angular-suffix option to add entity suffix
- [x] 18 switch to eslint instead of jshint
- [x] 19 --skip-user-management flag
- [x] 20 Internationalization - support for setting native language and additional languages
- [x] 21 have links to the script-base's jhipsterFunc from the creating-a-module page to have a quick view of the protoype and the function doc.
- [x] 22 changes in the generated war structure, no more single war for dev and prod
- [x] 23 Inject of js files with gulp serve and build
- [x] 24 microservice use cases, diagrams and advice
- [x] 25 update customizing_bootstrap.md with the new Gulp configuration
- [x] 26 update the technology stack to add the Netflix stack
- [x] 27 import-jdl sub generator
- [x] 28 docker compose sub generator
- [x] 29 gradle support in cloudfoundry sub gen
- [x] 30 new profile switches for swagger, liquibase
- [x] 31 jhipster registry (spring cloud config part) and jhipster console.

anything else?

**Comment by cbornet** [comment]
--with-entities to regen all entities

**Comment by jdubois** [comment]
Great job Deepu!
I will also create a shared Google doc so we can prepare a clean release
notes document.
Btw the one from the 2.0 release got vandalized, so next time it won't be
opened to comments.
Le 4 févr. 2016 6:45 AM, "Christophe Bornet" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
awesome.

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
we also need to update the presentation and the videos

**Comment by cbornet** [comment]
We need to update the setting-CI page with gulp and remove the "Configuring Javascript Tests" which is now included by default.

**Comment by deepu105** [comment]
@jdubois if you want we can draft the notes in this ticket as well, coz I have locked it within the Jhipster team members and we will have markdown here so easy to copy paste :)

**Comment by jdubois** [comment]
@deepu105 I didn't know we could lock a conversation, that's cool!!!!
In the jhipster.github.io repository I have created a specific branch for the 3.0 version, is it good for you? It's https://github.com/jhipster/jhipster.github.io/tree/v3_preparation

**Comment by deepu105** [comment]
Yes that should be good, so that we can all PR to that branch :) and probably do some dry run before the release 

Btw here is the lock button below the participants :)

![image](https://cloud.githubusercontent.com/assets/1107223/12944463/355b02a2-d022-11e5-99b1-ca1a619d1074.png)

**Comment by gmarziou** [comment]
Here is a drawing I made to explain the JHipster 3 architecture to my team, I thought it could be converted to ASCII art for easier management in github but I think that some color would help or maybe some details should be removed.

![jh3_ms_architecture27022016](https://cloud.githubusercontent.com/assets/361007/13374658/72fa1168-dd8b-11e5-968f-24d4be5c3b89.jpg)

**Comment by jdubois** [comment]
Excellent drawing @gmarziou !!

**Comment by deepu105** [comment]
@gmarziou check this out may be you can model this like [here](http://www.nomnoml.com/#view/[<package>UML%20Representation|%0A%20%20[Compartment|lines:%20string*;nodes:%20Classifier*;relations:%20Relations*]%0A%20%20[Classifier|type:%20string;name:%20string;compartments:%20Compartment*;width:%20int;height:%20int;x:%20int;y:%20int]%0A%20%20[Relation|startLabel:%20string;endLabel:%20string;type:%20string;startShape:%20string;endShape:%20string;path:%20Point*]%0A%20%20[Compartment]+->[Classifier]%0A%20%20[Classifier]+->[Compartment]%0A%20%20[Compartment]+->[Relation]%0A]%0A[parser]-->[UML%20Representation]%0A[layouter||layout(ast:%20Compartment)]%0A[renderer||render(d:%20Compartment)]%0A[parser||parse(source:%20String):%20Classifier]+->[Jison]%0A[layouter]-->[UML%20Representation]%0A[layouter]+->[dagre]%0A[renderer]-->[UML%20Representation]%0A[renderer]o->[<instance>:Canvas]%0A[measurer]<:--[renderer]%0A[layouter]->[measurer])

**Comment by gmarziou** [comment]
nomnoml seems to target only UML class diagrams.

I went for ASCII art using [asciiflow](http://asciiflow.com) and [Ditaa](https://github.com/stathissideris/ditaa).

The benefits I see are:

- ASCII art diagram could be inserted in README.md of Registry and Gateway
- generated image for http://jhipster.github.io/

<pre>
                                                  +--------------+
                                                  |    Browser   |
                                                  +-------+------+
                                                          |
                                                          |
                                                          V 8080
                               +-----------------------------------------------------+
                               | Gateway                                             |
                               | +-----------+    +--------------+      +----------+ |
                               | |           |    |  Zuul Proxy  |      |          | |     +-------+
                               | | Angular   |    |              |      |  Access  +-|---->|  {s}  |
                               | | App       |    +--------------+      |  Control | |     | Users |
                               | |           |    |    Ribbon    |      |          | |     | Roles |
                               | +-----------+    +---+------+---+      +----------+ |     +-------+
                               |                      |      |                       |
                               +-+---------------------------------------------------+
                                 |                    |      |       
                                 |                    |      |                              
                                 |                    |      |                        
                                 |        +-----------+      +----------------+            
+------------------------+       |        |                                   |
| JHipster Registry      |       |        V 8081                              V 8082
|                        |       | +-------------+                     +-------------+
|  +------------------+  |       | |             |     +-----+         |             |     +-----+
|  | Eureka Server    |  |       | |  Service 1  +---->| {s} |         |  Service 2  +---->| {s} |
|  +------------------+  |       | |             |     | DB1 |         |             |     | DB2 |
|  | Config Server    |  |       | +--+-----+----+     +-----+         +--+------+---+     +-----+
|  +--------+---------+  |  8761 |    |     |                             |      |
|           |            |<------+----+-----------------------------------+      |
+------------------------+                  |                                    |
            |                               +------------------------------------+
            V                               |
        +-------+                           V syslog
        |  {s}  |                   +---------------+
        |  Git  |                   |      ELK      |
        |  Repo |                   +---------------+
        +-------+
</pre>

![jhipster 3 0 architecture](https://cloud.githubusercontent.com/assets/361007/13555854/a5881346-e3cb-11e5-9fc9-5a23d645f4a3.png)

**Comment by pascalgrimaud** [comment]
beautiful !

**Comment by gmarziou** [comment]
Thanks.
I thought that may-be we could use color to indicate docker containers we provide: registry and ELK.

Also ELK could be detailed in its 3 components.

**Comment by jdubois** [comment]
Great, indeed! I've been doing the same one with Keynote, but here it must be easier to generate a custom diagram, and of course version it.

**Comment by gmarziou** [comment]
Here is another version using blue for Dockerized components and detailing ELK.
Not sure which one is better.

![jhipster 3 0 architecture](https://cloud.githubusercontent.com/assets/361007/13557803/12e52ce6-e3f7-11e5-808b-eed115c3e264.png)

**Comment by deepu105** [comment]
+1 for colors

**Comment by gmarziou** [comment]
v3_preparation branch is 57 commits behind master for jhipster.github.io 

How should we proceed to submit PRs for JH3 in a way that would be as smooth as possible?

This makes me wonder whether we should keep the v2 site available somewhere or just replace it.

**Comment by deepu105** [comment]
maintaining versioned docs is a pain :(
I don't know how we can maintain another version for 2.x may be we can copy the current site as it is and put in subfolder and link to it like `jhipster.github.io/2x/`

**Comment by deepu105** [comment]
or we can create a new repo called docs-2x in jhipster org and put current site as it is in the gh-pages branch and it will automatically be served in `jhipster.github.io/docs-2x/` similar to how I hosted JDL-Studio

**Comment by jdubois** [comment]
Yes the versioned documentation is necessary, and I have no idea how to do it -> probably like @deepu105 says I need to do a specific repo for that, like for JDL Studio. Then I'm afraid we have many absolute URLs, so that can be really annoying.

**Comment by deepu105** [comment]
I guess Jekyll might handle it coz we append `{{site.url}}` on all urls, may be we can create a repo and try it out by copying from current site. Even if that fails we can assign the correct path to `site.url` var in global jekyll `_config.yml` and it should work

**Comment by deepu105** [comment]
so when someone visits `jhipster.github.io/docs-2x/` they will be seeing a whole new site like JDL studio so there is no interference with the v3 site and v2 site and its easy for us to maintain both seperateley

**Comment by jdubois** [comment]
I just updated the v3 branch with a lot changes. It's not over yet, but at least there's no issue in merging to "master" when needed.
You can see my changes here: https://github.com/jhipster/jhipster.github.io/commits/v3_preparation

I'll need help on the front-end stuff and on the different options, as I didn't follow everything closely enough.

**Comment by deepu105** [comment]
here are some updates https://github.com/jhipster/jhipster.github.io/pull/217

**Comment by deepu105** [comment]
@erikkemperman would you be willing to do item 22 in the todo since you did the PR?

**Comment by deepu105** [comment]
Ill do items 7, 10 , 11 and 25 as well by this week

**Comment by PierreBesson** [comment]
I will add documentation about the jhipster registry (spring cloud config part) and jhipster console.

**Comment by deepu105** [comment]
ok this is good progress so far :)

**Comment by deepu105** [comment]
@jdubois for the presentation (item 11) how do you want me to proceed. Should I use the same presentation and update just the content or do you want me to do a fresh presentation?

**Comment by jdubois** [comment]
@deepu105 it should be in the same presentation, as people want to have a good overview of everything

This doesn't have to be huge, some slides to add that we also support the microservices architecture, with a diagram, and saying that we use the Netflix stack

Can you also add something on our Docker Compose support? This is really great stuff, I don't know if people realize this.

**Comment by deepu105** [comment]
@cbornet about item 13, I dont see the Junit reporter configured anywhere. jenkins seems to be there is that enough? can you check and let me know . For now I have removed that section from docs

**Comment by deepu105** [comment]
@jdubois I have updated presentation [here](https://github.com/jhipster/jhipster.github.io/pull/221) see if its enough or do you want to add more stuff?

**Comment by cbornet** [comment]
@deepu yes, karma-jenkins-reporter is a fork of karma-junit-reporter

**Comment by deepu105** [comment]
So that leaves only two more items to do :)

**Comment by jdubois** [comment]
Great job!!!

**Comment by deepu105** [comment]
@erikkemperman sorry for the locked ticket we were trying to avoid any spam when we draft release notes here. Anyway ill open it till the todo are done.

You can try to add those to using in development and using in production section of the docs

**Comment by pascalgrimaud** [comment]
I'm reviewing all part concerned by Docker and will do some PR

Tips : just tried this : `docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 4000:4000 jekyll/jekyll:pages` to test/view the updated website ;-)

**Comment by jdubois** [comment]
@pascalgrimaud Docker is awesome :-)

**Comment by pascalgrimaud** [comment]
Happy you like Docker !!!

I'm updating the migration jdubois -> jhipster organization
https://hub.docker.com/r/jhipster/jhipster/tags/ -> see the tag v2.27.2

**Comment by deepu105** [comment]
thanks a lot @erikkemperman

**Comment by deepu105** [comment]
just one more item left @PierreBesson I hope you are on to it :)

**Comment by deepu105** [comment]
@jdubois I guess we can use this thread to draft a release note as well what say?

**Comment by jdubois** [comment]
@deepu105 oh yes, I forgot I had to write the release notes... I'll start today.

**Comment by deepu105** [comment]
No worries just put in a skeleton and we all can update it with changelogs and finally you can jsut edit the post and copy the markdown from here :)

**Comment by deepu105** [comment]
btw I have locked this conversation again to collaborators to avoid any vandalism

**Comment by PierreBesson** [comment]
@deepu105 I'm on it since the end of last week. I will PR a new page on alerting with everything on it.

**Comment by jdubois** [comment]
All doc is done now, excepted maybe for the alerting stuff (but that's minor).

The v2 doc is available at https://github.com/jhipster/v2-documentation/tree/gh-pages and you can see it live at http://jhipster.github.io/v2-documentation/

So I'm closing this!

**Comment by deepu105** [comment]
:+1:

**Comment by deepu105** [comment]
@jdubois I have cleaned up some docs here https://github.com/jhipster/v2-documentation/pull/1

and for current repo here https://github.com/jhipster/jhipster.github.io/pull/227
