### ISSUE TITLE
Split bug report template one template for `jhipster info` another for jdl. Add an incremental change/2 jdls template

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#27885]
##### **Overview of the feature request**

Current template says jdl is an alternative, but it’s not clear enough.
Split to be easier to post a good issue.

Add a 2 jdl template for generated application comparison and incremental changelog.

  <details>
  <summary>JDL definitions</summary>
  <pre>
     application { config { baseName app, incrementalChangelog true } }
  </pre>
  </details>

  <details>
  <summary>JDL definitions</summary>
  <pre>
     application { config { baseName app, incrementalChangelog true } entities * } entity Project
  </pre>
  </details>

  <details>
  <summary>JDL definitions</summary>
  <pre>
     application { config { baseName app, incrementalChangelog true } entities * } entity Project entity Label
  </pre>
  </details>

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bug bounty claimed https://opencollective.com/generator-jhipster/expenses/233114

**Comment by DanielFran** [comment]
@mshima approved
