### ISSUE TITLE
create a module or tip for grunt

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2793]
Module will be better

Any body want to volunteer??

**Comment by deepu105** [comment]
looks like no volunteers :(

@PierreBesson would you be interested when you have time?

**Comment by PierreBesson** [comment]
Wouldn't it be better if the grunt module can be maintained by someone who has personal reasons to keep using grunt. Also it would need to be updated to keep up with the main generator and I don't think I have the skills to do it. Although I have used grunt a bit in the past, I would prefer to learn gulp now as it is much faster and seem simpler and more powerful.

Anyway if someone wants to do the module, I think he can base it on your [rm-grunt commit](https://github.com/jhipster/generator-jhipster/commit/207b9008e02cf0f2a18ee39e04b0a4e341468221).

**Comment by deepu105** [comment]
Ya thats the problem, no one seems to be interested in grunt :( including
me :P

**Comment by jdubois** [comment]
Let's not waste time with it: maintaining the Grunt build would be a huge task, I don't think anybody wants to do this.
If someone outside of the dev teams wants to do a tip or a module, he's indeed very welcome to do so, but concerning the dev team we just have too much work already.
