### ISSUE TITLE
ReactiveSecurityContextHolder.getContext() is empty , unable to getCurrentUserLogin() in any service except Gateway

### ISSUE THREAD

**Issue by deceivingrakesh** [jhipster/generator-jhipster#27934]
##### **Overview of the issue**

Unable to fetch current loggedin user from a reactive microservice using the getCurrentUserLogin() method , except it works in Gateway

##### **Motivation for or Use Case**

Need to use current logged in user details in different services

##### **Reproduce the error**

When I changed the method  getCurrentUserLogin() in SecurityUtils class to 
```
 public static Mono<String> getCurrentUserLogin() {
        return ReactiveSecurityContextHolder.getContext().switchIfEmpty(Mono.error(new IllegalStateException("ReactiveSecurityContext is empty")))
            .map(SecurityContext::getAuthentication)
            .flatMap(authentication -> Mono.justOrEmpty(extractPrincipal(authentication)));
    }
```
the context is empty .

##### **JHipster Version(s)**

8.7.3

##### **Browsers and Operating System**

- [ ] Tickets opened without reproduction steps or that doesn't follows the template recommendation will be **closed**.
- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@deceivingrakesh can you provide a PR with the change?

**Comment by deceivingrakesh** [comment]
I don't have the solution for the problem yet , I'm still not able to get current logged in userId from microservices , other than gateway by using the getCurrentUserLogin() , when I debugged I got to know that ReactiveSecurityContextHolder.getContext() is returning empty inside the getCurrentUserLogin() method .

**Comment by deceivingrakesh** [comment]
Is there any update on this issue , as of now I'm using Principal object in controller to get UserId .

**Comment by mraible** [comment]
No update. But if you figure out a solution, please let us know. I'll add a bug bounty to see if that helps get this fixed.

**Comment by kamilkrzywanski** [comment]
Can someone provide example to reproduce this bug? @mraible @deceivingrakesh

**Comment by deceivingrakesh** [comment]
@kamilkrzywanski , Generate a new reactive microservice app , and try to get the current logged in username with SecurityUtils.getCurrentUserLogin() method , it's returns empty . It works in Gateway app , but not in any other service .

**Comment by kamilkrzywanski** [comment]
For me works fine :) It looks like full example is required or you use this method incorrect. 
![image](https://github.com/user-attachments/assets/e29eaca4-9bbe-4c0d-8e3e-a9dd0bb2076d)
![image](https://github.com/user-attachments/assets/e4a55131-3aa7-4e80-9de7-1d141af8afce)
![image](https://github.com/user-attachments/assets/4f26bfa4-31fd-4457-9f87-16a62a7aeae7)

**Comment by deceivingrakesh** [comment]
@kamilkrzywanski  , you are right , If I return a mono , value is present , but if I subscribe to the Mono , I'm unable to use / print it , I guess I'm missing something with reactive / Mono .

@GetMapping(value = "/login", produces = MediaType.APPLICATION_JSON_VALUE)
    public Mono<String> getAllOffers(){
    	SecurityUtils.getCurrentUserLogin()
    	.subscribe(login -> LOG.info(login));
    	return SecurityUtils.getCurrentUserLogin();
    }

Can you help me with this ?

**Comment by kamilkrzywanski** [comment]
Can you try with

{
    return SecurityUtils.getCurrentUserLogin()
        .doOnNext(login -> LOG.info("Current user login: {}", login));
}

**Comment by kamilkrzywanski** [comment]
@deceivingrakesh 
I've checked it and looks fine, another way is pass authentication as method parameter like:
    public Mono<String> getLogin(Authentication authentication) {
        System.out.println(SecurityUtils.extractPrincipal(authentication));
        return SecurityUtils.getCurrentUserLogin()
            .doOnNext(login -> LOG.info("Current user login: {}", login));
    }

**Comment by deceivingrakesh** [comment]
@kamilkrzywanski it worked for me now , I was doing it wrong , followed your code , This isn't a defect .

**Comment by kamilkrzywanski** [comment]
https://opencollective.com/generator-jhipster/expenses/231622
