### ISSUE TITLE
Update Angular to v19

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#27930]
##### **Overview of the feature request**

https://github.com/angular/angular/releases/tag/19.0.0
- standalone is the default.

Dependencies:
- [ ] [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap/issues/4779)
- [x] [fortawesome](https://github.com/FortAwesome/angular-fontawesome/issues/455)
- [x] ~[ngx-translate](https://github.com/ngx-translate/core/issues)~ supports angular >=16
- [x] ngx-cookie-service
- [x] [ngx-infinite-scroll](https://github.com/orizens/ngx-infinite-scroll/issues/445)
- [ ] [angular-builders](https://github.com/just-jeb/angular-builders/issues/1869)
- [x] [jest-preset-angular](https://github.com/thymikee/jest-preset-angular/issues/2856)
- [x] [angular-eslint](https://github.com/angular-eslint/angular-eslint/issues/2117)
- [ ] [Angular Architects](https://github.com/angular-architects/module-federation-plugin/issues/696)

Features:
- [x] esbuild (experimental)

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Angiular 19 only is too small for the bounty.
Lets add esbuild.

**Comment by Myestery** [comment]
Hi @mshima , if this is still open I'll like to work on it

**Comment by mshima** [comment]
@Myestery there isn't much to do for Angular 19.
But esbuild support is quite big. There is a lot to customize.

**Comment by Myestery** [comment]
> @Myestery there isn't much to do for Angular 19. But esbuild support is quite big. There is a lot to customize.

ok great, is there a separate issue for it and should I start working on it here?

**Comment by Govind85** [comment]
@mshima When are we planning to release ng-bootstrap which will support Angular v19?

**Comment by mshima** [comment]
@Govind85 please don’t cross post in 3rd party issue tracker. I am not an official ng-bootstrap contributor.

**Comment by mshima** [comment]
https://github.com/angular/angular-cli/issues/28661 should allow to reduce custom builders dependency due to version passed though maven/gradle.

Needs to be upvoted.

**Comment by chihab** [comment]
@mshima keep in mind this issue before migrating to v19 https://github.com/angular/angular-cli/issues/29003

In a nutshell, `ng test` has a regression on supporting webpack transforms (used by custom webpack builders).

**Comment by mshima** [comment]
> @mshima keep in mind this issue before migrating to v19 [angular/angular-cli#29003](https://github.com/angular/angular-cli/issues/29003)
> 
> In a nutshell, `ng test` has a regression on supporting webpack transforms (used by custom webpack builders).

@chihab thanks, not sure if that applies to use since we use jest.

**Comment by mshima** [comment]
> Will you supported the new api "Resource" from angular instead of using rxjs or you will use both and mixed ?

Resource api is experimental so I don’t think we should adopt it. Once it moves to developer preview we can consider.

**Comment by mshima** [comment]
@DanielFran bug bounty claimed https://opencollective.com/generator-jhipster/expenses/233112

**Comment by DanielFran** [comment]
@mshima approved

**Comment by playanth95978** [comment]
@mshima 
Hello when the update to angular 20 ? Soon i hope, thant you
