### ISSUE TITLE
JHipster generator can't regenerate a jdl change (using issue for one or more Application JDLs)

### ISSUE THREAD

**Issue by jperezdelafuente** [jhipster/generator-jhipster#27944]
##### **Overview of the issue**

I can't regenerate the application with changes in jdl
I indicate the 3 steps to reproduce:

1. I create an application with "jhipster jdl foo.jh" (foo.jh like a JDL definitions section)
2. I add an attribute called foo2 to the entity foo (in the file a second JDL definitions section with second foo2 attribute)
<pre>
 /* Foo 2 */
foo2 String required maxlength(30)
</pre>
3. I try to regenerate the application with "jhipster jdl foo.jh"

##### **JHipster JDL**

  <details>
  <summary>JDL definitions</summary>
  <pre>
 application {
  config {
    applicationType monolith,
    baseName foo,
    packageName com.foo,
    jhiPrefix gsr,
    authenticationType session,
    databaseType sql,
    devDatabaseType h2Disk,
    prodDatabaseType postgresql,
    enableHibernateCache true,
    cacheProvider ehcache,
    buildTool maven,
    testFrameworks [cypress, gatling, cucumber],
    clientFramework angular,
    enableTranslation true,
    nativeLanguage es,
    languages [es, en]
    incrementalChangelog true
  }
  entities *
}

/** Entity Foo */

entity Foo(foo) {

/* Foo */
foo String required maxlength(20)

}

dto * with mapstruct

service all with serviceImpl

paginate all with pagination
  </pre>
  </details>

  <details>
  <summary>JDL definitions (incremental with second foo2 attribute)</summary>
  <pre>
 application {
  config {
    applicationType monolith,
    baseName foo,
    packageName com.foo,
    jhiPrefix gsr,
    authenticationType session,
    databaseType sql,
    devDatabaseType h2Disk,
    prodDatabaseType postgresql,
    enableHibernateCache true,
    cacheProvider ehcache,
    buildTool maven,
    testFrameworks [cypress, gatling, cucumber],
    clientFramework angular,
    enableTranslation true,
    nativeLanguage es,
    languages [es, en]
    incrementalChangelog true
  }
  entities *
}

/** Entity Foo */

entity Foo(foo) {

/* Foo */
foo String required maxlength(20)

/* Foo2 */
foo2 String maxlength(20)

}

dto * with mapstruct

service all with serviceImpl

paginate all with pagination

  </pre>
  </details>

- [X] JDL is mandatory for bug reports. This will allow us to use automated tests and genarate the broken sample using `jhipster from-issue` command.

##### **Motivation for or Use Case**

Perform regenerations in the application with changes in the jdl

### With Node v22.11.0 It finishes without errors and without trying to regenerate the rest of the files
<pre>
(node:29595) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
     info KeyStore '/home/foo22/src/main/resources/config/tls/keystore.p12' already exists. Leaving unchanged.
[@faker-js/faker]: faker.internet.userName() is deprecated since v9.1.0 and will be removed in v10.0.0. Please use faker.internet.username() instead.
✔ applying multi-step templates
     info Using existing git repository.
identical .prettierrc
identical .prettierignore
✔ prettier configuration files committed to disk
✔ loading translations
✔ updating package.json dependencies versions
✔ prettifying sonar-project.properties
✔ adding package-info.java files
✔ sorting pom.xml file
✔ translating angular application
identical sonar-project.properties
identical .husky/pre-commit
identical src/main/resources/banner.txt
identical .devcontainer/Dockerfile
identical pom.xml
identical src/main/resources/logback-spring.xml
identical src/main/resources/i18n/messages.properties
identical src/test/resources/logback.xml
identical src/test/resources/junit-platform.properties
identical mvnw
identical mvnw.cmd
identical .mvn/wrapper/maven-wrapper.jar
identical .mvn/wrapper/maven-wrapper.properties
identical .mvn/jvm.config
identical src/main/docker/jib/entrypoint.sh
identical checkstyle.xml
</pre>

### With Node v20.18.0  finishes with errors and without trying to regenerate the rest of the files:
<pre>
     info KeyStore '/home/foo20/src/main/resources/config/tls/keystore.p12' already exists. Leaving unchanged.
[@faker-js/faker]: faker.internet.userName() is deprecated since v9.1.0 and will be removed in v10.0.0. Please use faker.internet.username() instead.
✔ applying multi-step templates
     info Using existing git repository.
identical .prettierrc
identical .prettierignore
✔ prettier configuration files committed to disk
✔ loading translations
✔ updating package.json dependencies versions
✔ prettifying sonar-project.properties
✔ adding package-info.java files
✔ sorting pom.xml file
✔ translating angular application
identical sonar-project.properties
identical .husky/pre-commit
identical src/main/resources/banner.txt
identical .devcontainer/Dockerfile
identical pom.xml
identical src/main/resources/logback-spring.xml
identical src/main/resources/i18n/messages.properties
identical src/test/resources/logback.xml
identical src/test/resources/junit-platform.properties
identical mvnw
identical mvnw.cmd
identical .mvn/wrapper/maven-wrapper.properties
identical .mvn/wrapper/maven-wrapper.jar
identical .mvn/jvm.config
identical src/main/docker/jib/entrypoint.sh
identical checkstyle.xml
**ERROR! ERROR! Cannot read properties of undefined (reading 'added')
TypeError: Cannot read properties of undefined (reading 'added')
    at Conflicter._detectConflict (file:///home/.nvm/versions/node/v20.18.0/lib/node_modules/generator-jhipster/node_modules/@yeoman/conflicter/dist/conflicter.js:182:58)
    at async Conflicter._checkForCollision (file:///home/.nvm/versions/node/v20.18.0/lib/node_modules/generator-jhipster/node_modules/@yeoman/conflicter/dist/conflicter.js:260:13)
    at async Conflicter.checkForCollision (file:///home/.nvm/versions/node/v20.18.0/lib/node_modules/generator-jhipster/node_modules/@yeoman/conflicter/dist/conflicter.js:205:20)
    at async Object.<anonymous> (file:///home/.nvm/versions/node/v20.18.0/lib/node_modules/generator-jhipster/node_modules/@yeoman/conflicter/dist/conflicter.js:391:36)
    at async file:///home/.nvm/versions/node/v20.18.0/lib/node_modules/generator-jhipster/node_modules/p-transform/dist/queue.js:68:28
    at async file:///home/.nvm/versions/node/v20.18.0/lib/node_modules/generator-jhipster/node_modules/p-queue/dist/index.js:187:36**
</pre>

### With Node v18.20.4  finishes with errors and without trying to regenerate the rest of the files:
<pre>
          info KeyStore '/home/foo18/src/main/resources/config/tls/keystore.p12' already exists. Leaving unchanged.
[@faker-js/faker]: faker.internet.userName() is deprecated since v9.1.0 and will be removed in v10.0.0. Please use faker.internet.username() instead.
✔ applying multi-step templates
     info Using existing git repository.
identical .prettierrc
identical .prettierignore
✔ prettier configuration files committed to disk
✔ loading translations
✔ updating package.json dependencies versions
✔ prettifying sonar-project.properties
✔ adding package-info.java files
✔ sorting pom.xml file
✔ translating angular application
identical sonar-project.properties
identical .husky/pre-commit
identical src/main/resources/banner.txt
identical .devcontainer/Dockerfile
identical pom.xml
identical src/main/resources/logback-spring.xml
identical src/main/resources/i18n/messages.properties
identical src/test/resources/logback.xml
identical src/test/resources/junit-platform.properties
identical mvnw
identical mvnw.cmd
identical .mvn/wrapper/maven-wrapper.jar
identical .mvn/wrapper/maven-wrapper.properties
identical .mvn/jvm.config
identical src/main/docker/jib/entrypoint.sh
identical checkstyle.xml
ERROR! ERROR! Cannot read properties of undefined (reading 'added')
TypeError: Cannot read properties of undefined (reading 'added')
    at Conflicter._detectConflict (file:///home/.nvm/versions/node/v18.20.4/lib/node_modules/generator-jhipster/node_modules/@yeoman/conflicter/dist/conflicter.js:182:58)
    at async Conflicter._checkForCollision (file:///home/.nvm/versions/node/v18.20.4/lib/node_modules/generator-jhipster/node_modules/@yeoman/conflicter/dist/conflicter.js:260:13)
    at async Conflicter.checkForCollision (file:///home/.nvm/versions/node/v18.20.4/lib/node_modules/generator-jhipster/node_modules/@yeoman/conflicter/dist/conflicter.js:205:20)
    at async Object.<anonymous> (file:///home/.nvm/versions/node/v18.20.4/lib/node_modules/generator-jhipster/node_modules/@yeoman/conflicter/dist/conflicter.js:391:36)
    at async file:///home/.nvm/versions/node/v18.20.4/lib/node_modules/generator-jhipster/node_modules/p-transform/dist/queue.js:68:28
    at async file:///home/.nvm/versions/node/v18.20.4/lib/node_modules/generator-jhipster/node_modules/p-queue/dist/index.js:187:36
</pre>

##### **Related issues**

[JHipster generator can't regenerate a jdl change #27866](https://github.com/jhipster/generator-jhipster/issues/27866)

##### **JHipster Version(s)**

8.7.3

##### **Browsers and Operating System**

Ubuntu 22.04.2

##### **Environment and Tools**

openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

git version 2.34.1

node: v22.11.0
npm: 10.9.0

Docker version 24.0.2, build cb74dfc

- [X] Tickets opened without reproduction steps or that doesn't follows the template recommendation will be **closed**.
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Can you try with the following command:

```
jhipster entity Foo --single-entity
```

**Comment by mshima** [comment]
Node 22 issue will be tracked at https://github.com/jhipster/generator-jhipster/issues/27948.

**Comment by mshima** [comment]
This issue is in `@yeoman/conflicter` package due to diff breaking changes https://github.com/kpdecker/jsdiff/blob/master/release-notes.md#600

**Comment by mshima** [comment]
> This issue is in `@yeoman/conflicter` package due to diff breaking changes https://github.com/kpdecker/jsdiff/blob/master/release-notes.md#600

Fix is released.
