### ISSUE TITLE
Feature Request: Support AWS Elasticsearch Service

### ISSUE THREAD

**Issue by myspivey** [jhipster/generator-jhipster#2794]
Would be great to support AWS Elasticsearch service as this makes getting clusters up and running far faster. Currently I believe they only support REST methods for adding data. This could be a great add on module or addition.. http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-gsg.html

**Comment by deepu105** [comment]
you can do it as module as we wont be having the time and resource. FYI @wuethrich44
