### ISSUE TITLE
JHipster is failing silently on node 22 if pipeline tasks like conflicter/prettier fails.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#27948]
##### **Overview of the issue**

JHipster is failing silently on node 22 if pipeline tasks like conflicter/prettier fails.

##### **Reproduce the error**

Change a javascript template to generate an invalid js file.
JHipster execution will fail silently.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/27944

##### **Browsers and Operating System**

- [x] Tickets opened without reproduction steps or that doesn't follows the template recommendation will be **closed**.
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Looks related to https://github.com/nodejs/node/issues/54945

**Comment by mraible** [comment]
Added bug bounty.

**Comment by mshima** [comment]
@DanielFran bug bounty claimed https://opencollective.com/generator-jhipster/expenses/233113

**Comment by DanielFran** [comment]
@mshima approved
