### ISSUE TITLE
Update Spring Boot to v3.4.0.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#27962]
##### **Overview of the feature request**

Spring Boot v3.4.0 minor version has been [released](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.0) 
Spring Cloud support can be tracked at https://github.com/spring-cloud/spring-cloud-release/milestone/147

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/239495.

**Comment by DanielFran** [comment]
@mshima approved
