### ISSUE TITLE
uuid_generate_v4 generates duplicate UUIDs during tests

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#28015]
##### **Overview of the issue**
I have this changeSet:
```xml
<changeSet id="add-uuid-extension" author="alejandro">
  <preConditions onFail="MARK_RAN">
    <not>
      <sqlCheck expectedResult="1">
        SELECT COUNT(*) FROM pg_extension WHERE extname = 'uuid-ossp';
      </sqlCheck>
    </not>
  </preConditions>
  <sql>
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  </sql>
</changeSet>
<changeSet id="add-uuid-generate-v4-function" author="alejandro">
    <preConditions onFail="MARK_RAN">
        <not>
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM pg_proc WHERE proname = 'uuid_generate_v4';
            </sqlCheck>
        </not>
    </preConditions>
    <sql>
        CREATE OR REPLACE FUNCTION uuid_generate_v4() RETURNS uuid
        LANGUAGE c IMMUTABLE STRICT
        AS '$libdir/uuid-ossp', 'uuid_generate_v4';
    </sql>
</changeSet>
```

and I created this test:

```java
@Test
@Transactional
void testUniqueUUIDGeneration() {
    Set<String> uuids = new HashSet<>();
    for (int i = 0; i < 1000; i++) {
        String uuid = em.createNativeQuery("SELECT uuid_generate_v4()")
            .getSingleResult().toString();
        System.out.println(uuid);
        assertTrue(uuids.add(uuid), "Duplicate UUID found after " + i + " tries: " + uuid);
    }
}
```
The test fails after generating 5 (always 5) UUIDs. This could be tested with the following test:

```java
@ParameterizedTest(name = "Generating {0} UUIDs")
@ValueSource(ints = {1, 2, 3, 4, 5, 6})
@Transactional
void testUniqueUUIDGeneration(Integer input) {
    Set<String> uuids = new HashSet<>();
    for (int i = 0; i < input; i++) {
        em.clear();
        String uuid = em
            .createNativeQuery("SELECT uuid_generate_v4()")
            .getSingleResult()
            .toString(); // Llama a uuid_generate_v4() desde PostgreSQL
        System.out.println(uuid);
        assertTrue(uuids.add(uuid), "Duplicate UUID found after " + i + " tries: " + uuid);
    }
}
```
And failing after generating 5 UUIDs:
![image](https://github.com/user-attachments/assets/b27a9234-6a5e-4400-b449-5c797d223605)

##### **Motivation for or Use Case**
This is a bug because UUIDs should be unique.

##### **Reproduce the error**
create the changeLog and run the test. The result will be something like this:

```
91774e9e-716a-4ab2-beea-9d64b9bd767a
7483e971-304f-4928-a7af-1c9db81faa07
1512207c-3486-4a9a-8620-f7f944315b80
1438e32f-a038-4900-910d-18d3ee04c60d
323c5670-0efa-48c4-9394-9f332b0b8ffc
323c5670-0efa-48c4-9394-9f332b0b8ffc

org.opentest4j.AssertionFailedError: Duplicate UUID found after 5 tries: 323c5670-0efa-48c4-9394-9f332b0b8ffc
```

##### **Related issues**
None found

##### **JHipster Version(s)**
v8.7.3

##### **Browsers and Operating System**
EndevourOS

- [x] Tickets opened without reproduction steps or that doesn't follows the template recommendation will be **closed**.
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
That is not generated by JHipster.

**Comment by amatosg** [comment]
@mshima you're right. It wasn't generated by jhipster, sorry about that.

I'm leaving a comment just in case anyone encounters the same issue I had:

When the extension "uuid-ossp" is created using liquibase, it will generated duplicated UUIDs even if you run queries directly in the database.

PostgreSQL has its own method to generate UUIDs so there is no need to install said extension. Replacing any calls from `uuid_generate_v4()` with `gen_random_uuid()` will solve the problem.
