### ISSUE TITLE
move only required bower_component files in war

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2801]
From discussion in https://github.com/jhipster/generator-jhipster/issues/2282

```
156K   ./i18n
44M    ./WEB-INF
28K    ./swagger-ui
216K   ./assets
616K   ./scripts
4,0K   ./META-INF
24M    ./bower_components
8,2M   ./dist
76M    . (all)
```

seems we are packaging a lot more than required in bower_components.
we should see if we can package only the required files

from wiredep documentation:, there seems to be a way to get all file paths required, may be we can write a custom copy task to copy only these instead of moving all in the bower folder during packaging 

Programmatic Access

You can run wiredep without manipulating any files.
```
require('wiredep')();
```
...returns...
```
{
  js: [
    'paths/to/your/js/files.js',
    'in/their/order/of/dependency.js'
  ],
  css: [
    'paths/to/your/css/files.css'
  ],
  // etc.
}
```

**Comment by gmarziou** [comment]
I didn't know that wiredep could do it, for me this is a task for bower-main-files as the file listr can be streamed, filtered and also re-ordered if needed.
We could also concatenate all js files from bower_components to a vendor.js.

I'll work on this.

**Comment by deepu105** [comment]
yes you are right one way or other we should do it

**Comment by gmarziou** [comment]
The more I read about, the more I get confused :(

It seems that the right way to do it would be to use [webpack](http://webpack.github.io/) either from a thin gulpfile like in [yeaoman generator-es6-angular](https://github.com/leftstick/generator-es6-angular) or directly from npm scripts (without gulp). 

In both cases, bower would get out of the picture and be replaced by npm with dependencies listed in package.json

**Comment by gmarziou** [comment]
It seems that ES6 would be required to do so.

**Comment by gmarziou** [comment]
I did a test by excluding completely the bower_components folder from the war in pom*;xml:

    <packagingExcludes>WEB-INF/lib/tomcat-*.jar,bower_components/**</packagingExcludes>

The resulting war file is only 5 MB smaller which is roughly 10% smaller.

I don't think this is worth tuning gulp build using wiredep or any- especially when we could something simpler to maintain with webpack.

So I'm going to try webpack.

**Comment by deepu105** [comment]
But webpack works only with npm right? Its good for react but not sure how
it will work out for angular, i dont think all angular dependency we use
are available in npm.

Again if its only 5 mb reduction we shouldn't bother

**Comment by gmarziou** [comment]
Yes it uses npm and I don't know how this would work for css or fonts.
I'll investigate webpack as it could be useful for ng2.

If you agree, we can close this issue

**Comment by deepu105** [comment]
ok lets close it for now

Thanks & Regards,
Deepu
