### ISSUE TITLE
Testing microservices builds on Travis requires running the registry

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#2804]
Following PR #2802, I have been asked to add Travis builds for the microservice and gateway app using Maven and Gradle. I have finished it and it's [ready for PR here](https://github.com/PierreBesson/generator-jhipster/tree/travis-builds-for-microservices).

But now that I think about it, in order to test the microservices build on Travis we need to have the [Jhipster registry](https://github.com/jhipster/jhipster-registry) running. Otherwise it will throw errors.

Now that @jdubois have pushed the registry (it was 5 min ago :smile:), we need to add a script to make Travis start it. Maybe @pascalgrimaud, you have some ideas of how we can achieve that with docker ?

So I will submit my PR once we decide on a way to start the registry with Travis. I can do it myself but please tell me how do you think it should be done.

**Comment by deepu105** [comment]
This stuff looks very cool, damn i need to learn some docker :P

**Comment by pascalgrimaud** [comment]
In my opinion,

1st version, you can just test mvn test + gulp test. I think it would be enought. Use the variable RUN_APP=0, in .travis.yml

In a 2nd version, we should :
- build a Docker image and put it to Docker hub (automated if possible...)
- in our travis build, just docker pull to get the image and start it, like we do for all database

**Comment by pascalgrimaud** [comment]
You should link your fork generator-jhipster to travis too
So, every push to your fork will trigger a Travis build, so you can really test it before propose PR

**Comment by PierreBesson** [comment]
@pascalgrimaud :+1:, this is a good idea. So if I set RUN_APP=0 it will not execute 05-run.sh but how can I set this only for microservices builds ?

>You should link your fork generator-jhipster to travis too
So, every push to your fork will trigger a Travis build, so you can really test it before propose PR

Good idea, I was just thinking about doing that. I hope Travis will not mind that we use so much of it's resources :smile:.

**Comment by PierreBesson** [comment]
OK, now I understand, .travis.yml has the list of things to run. This should be easy...

**Comment by pascalgrimaud** [comment]
@PierreBesson : plz look https://groups.google.com/forum/?hl=en#!topic/jhipster-dev/8HFvaasM3K0
We can reduce the number of builds from 14 to 12, and adding gateway+microservice, as suggested by Deepu

The current app-gulp and app-default can be replaced.

**Comment by PierreBesson** [comment]
It's reasonable to follow @deepu105's advice and reduce the number of builds but shouldn't we test the microservice build both with maven AND gradle ? Experience has shown that it is easy to make a mistake...
For now, I will add 2 builds (gateway+microservice) and remove app-gulp. Then work on doing further changes as of @deepu105's email.

**Comment by PierreBesson** [comment]
Maybe we could combine the gateway and gradle builds ? Should be good enough for now ?

**Comment by jdubois** [comment]
It would be more complex, just start with one Gateway and one Microservice build, it's already very good for starting
