### ISSUE TITLE
ZonedDateTime and LiquibaseDiff

### ISSUE THREAD

**Issue by thiagonuic** [jhipster/generator-jhipster#2805]
Hi,

When I try to do liquibase diff on an entity with ZonedDateTime I get the following error:

Unexpected error running Liquibase: org.hibernate.MappingException: Could not determine type for: BasicType adapter for AttributeConverter<ZonedDateTime,Date>, at table: hall_aud, for columns: [org.hibernate.mapping.Column(created_date)]

Doing some googling on it, seems to be some issue with Hibernate Envers, but I could not find the solution. 

Is anybody else having the same issue? Are you writing the auditing tables by hand ou generating them?

**Comment by jdubois** [comment]
Yes the _aud suffix is from Hibernate Envers, so it's not a JHipster issue.
If you look at the old tickets you'll see that I'm not a huge fan of Envers :-)
I'm closing this as it's not a JHipster issue.

**Comment by thiagonuic** [comment]
What do you use instead of envers?

**Comment by deepu105** [comment]
@thiagonuic are you looking at envers for auditing? if so take a look at https://github.com/hipster-labs/generator-jhipster-entity-audit

**Comment by thiagonuic** [comment]
@deepu105 Will do, thanks!
