### ISSUE TITLE
Replace confluence-kafka docker image with apache kakfa

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#28064]
##### **Overview of the feature request**

Image available at https://hub.docker.com/r/apache/kafka.

Test containers has confluence-kafka support deprecated.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@DanielFran bug bounty claimed https://opencollective.com/generator-jhipster/expenses/233115

**Comment by DanielFran** [comment]
@mshima approved
