### ISSUE TITLE
websocket doesnt work in JWT

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2807]
```
Opening Web Socket...
stomp.min.js:8 Web Socket Opened...
stomp.min.js:8 >>> CONNECT
accept-version:1.1,1.0
heart-beat:10000,10000

<<< ERROR
message:Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; nested exception is org.springframework.security.access.AccessDeniedException\c Access is denied
content-length:0


```

**Comment by deepu105** [comment]
cc @jdubois @amit2103

**Comment by jdubois** [comment]
Yes it's not surprising, it was already broken with xauth and oauth2.
The good news is that I understand jwt much better now, so maybe I can do something about it.

**Comment by amit2103** [comment]
Will take a look at this...May be  the token is not being sent via the websocket.

**Comment by jdubois** [comment]
Yes it's not being sent: I didn't code this at all :-)

**Comment by amit2103** [comment]
Yes I didnt do it in my pull request too..

**Comment by geesen** [comment]
I just posted a solution for xauth in #1370.
And I think, it could also fit for JWT. If you think so, I could make a PR...

**Comment by jdubois** [comment]
@geesen yes, please do!

**Comment by geesen** [comment]
Added PR #2957

**Comment by superandrew** [comment]
when this change is deployed, what should I do to update my code? should I regenerate the application with `yo jhipster` or is it automatically updated?

**Comment by deepu105** [comment]
unfortunately next version will be a major and hence will have many
breaking changes, so you may not be able to just upgrade your existing
apps. But we can backport some fixes to 2.x maintenance this could be one

Thanks & Regards,
Deepu

**Comment by superandrew** [comment]
ok, anyway if I bring these changes manually in the current code, is it enough or I should re-generate the application?

Thanks
Andrea

**Comment by geesen** [comment]
I fixed the issue using version 2.26.2 (with x-auth instead of JWT) and I added just two parts. 
The essential part is transfering the token in the URL instead of the header (because sockjs does not support custom headers). So you basically only need the one who put the right token in the URL (this is done by the tracker.servcice.js) and the one who fetches the token from the URL (this is done by the filter). After that, the token is handled like it was part of the header. Therefore, the rest is exactly the same and you don't have to regenerate something, if you change the code manually.

**Comment by deepu105** [comment]
I suppose you will do a PR for this?

Thanks & Regards,
Deepu

**Comment by geesen** [comment]
There is already a PR that has been merged and the issue is already fixed :)

**Comment by deepu105** [comment]
ha ha sorry was replying from mail it doesnt show the issue status you see :wink:

**Comment by deepu105** [comment]
@geesen do you also want to propose a PR to backport this to 2.x as well?

**Comment by geesen** [comment]
Yes, I will have a look, if I have some time
