### ISSUE TITLE
Blueprints and modules don't render in Marketplace

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#28104]
##### **Overview of the issue**

Reported [here](https://github.com/jhipster/jhipster.github.io/commit/d238ee70a294de8c3861983b5deaf54e7b39f72b#commitcomment-149947954). 

##### **Motivation for or Use Case**

Blueprints and modules should be rendered in the marketplace. 

##### **Reproduce the error**

Visit https://www.jhipster.tech/modules/marketplace/

**Comment by mraible** [comment]
Do you know what's causing this @SvMak?

**Comment by SvMak** [comment]
Sorry, I was very sick, I couldn't answer earlier(((

Today I'll check what the problem could be

**Comment by SvMak** [comment]
![Screenshot from 2024-12-10 08-55-04](https://github.com/user-attachments/assets/dc9e0fba-f4d4-4c53-b7d1-19224812a0ec)

for some reason for keyword sets empty output, maybe it's a temporary issue.

But I made another implementation for getting modules, now it works.

PR: https://github.com/jhipster/jhipster.github.io/pull/1434

**Comment by SvMak** [comment]
@mraible bug bounty claim https://opencollective.com/generator-jhipster/expenses/231411

**Comment by DanielFran** [comment]
@SvMak approved
