### ISSUE TITLE
Add option not to generate the user management code

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2811]
Add an option --no-user-management

Do not generate:
- tables and Liquibase code
- Java classes
- front-end code

But we still keep the security code.

This is important for microservices where the user management is handled by the gateway, or maybe an external oauth2 server.

**Comment by deepu105** [comment]
@jdubois I have organised the code in client and server to have user managemnt and auth part as seperate blocks so we just need to add 
```
if(skipUserManagement) return;
```

to these methods,  take a look at [this](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/index.js#L317), [this](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/index.js#L392), [this](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/index.js#L463) and [this](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/index.js#L727) 

let me know if it needs any change

**Comment by deepu105** [comment]
ill add the flags anyway and we can decide what to skip and what to keep later

**Comment by deepu105** [comment]
done I added a `skip-user-management` flag. we just need to skip the required file blocks in server and client

**Comment by deepu105** [comment]
if ther are files to skip those needs to be moved to [this block](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/index.js#L955)
```
        writeJavaUserManagementFiles : function () {

            if(this.skipUserManagement) return;
            // user management related files
        },
```

**Comment by deepu105** [comment]
@jdubois do you need help on this?

**Comment by jdubois** [comment]
Yes please. I don't have enough time... @PierreBesson should also work on
it but I don't know if he started
Le 12 févr. 2016 7:01 AM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
@PierreBesson are you working on this?

**Comment by PierreBesson** [comment]
Yes I am working on this but this is a bit painful to do as it involves a lot of testing. Also it was not clear to me at first which classes depends on the User. Fortunately, Julien will be at the office monday so  I will be able to ask him questions about the codebase so it will help me.

**Comment by deepu105** [comment]
Ok let me know if you are stuck or if you need help

**Comment by PierreBesson** [comment]
I have it working on [my branch](https://github.com/PierreBesson/generator-jhipster/tree/remove-user-management-flag) at least for the server part.

**Comment by PierreBesson** [comment]
I have left some JWT auth code as this is needed for microservices to do authorization management on the APIs.
What @jdubois wants to have is that the --skip-user-management flag is automatically used when the user wants to generate a "microservice application", so this should also be done, maybe in a different issue ?

**Comment by jdubois** [comment]
Yes :

- JWT should work without the user management code
- I want user management for monolith and gateway, and not for the microservices. This should be automatic depending on the application type.

This is just the first step, later we will:
- and OAuth2 in parallel to JWT
- allow to remove user management on the monolith and on the gateway (that would be a new question)

**Comment by PierreBesson** [comment]
I have finished working on it and have rebased it on the master. Currently, it works only for the server part. Then, @wmarques will help me to work on removing the user management for the client part.
Finally, we will be able add the new question for the monolith & gateway and force --skip-user-management for the microservice.

**Comment by deepu105** [comment]
I think question should be asked only for gateway as for monolith user
management would be required anyway rite?

Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
Yes, it would be better. For monolith users that really want to remove user management, they can still use the flag or do you plan on removing it ?

**Comment by deepu105** [comment]
Yes flag should be ok, but i dont think a question is required

**Comment by deepu105** [comment]
@PierreBesson is this done or are you working on this?

**Comment by PierreBesson** [comment]
It was done but there seems to be some problems see [this thread](https://github.com/jhipster/generator-jhipster/issues/2954#issuecomment-188303215). When it is fixed, I will notify you and you will be able to close this thread.

**Comment by gmarziou** [comment]
Does it make a diffrence if you start from en empty project or re-generate one from existing .yo-rc.json?

**Comment by PierreBesson** [comment]
@gmarziou Yes ! When generating from an empty dir user management code is still generated but not when there is a .yo-rc.json. If you know what to do can you please fix it.

**Comment by gmarziou** [comment]
I have no idea but maybe others will, in particular @deepu105 who has done lot of work on generators.

**Comment by deepu105** [comment]
If skip-user-management is passed it needs to be saved to yo-rc file and
read on subsequest run, check whats done for skip-client

During subsequent run generator doesnt know about skip-user-management if
not passed I guess

**Comment by deepu105** [comment]
Ok im gonna take a look at this

**Comment by deepu105** [comment]
Its fixed https://github.com/jhipster/generator-jhipster/commit/0b19c2490971e6b2c2a58ceb9add6a9c9cfb7651

@PierreBesson plz check and let me know if there is still any issues

**Comment by PierreBesson** [comment]
I confirm that it is fully fixed.
