### ISSUE TITLE
protractor should be devDependency in generated project

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2812]
Shouldnt protractor be in the `devDependencies` section of package.json of a generated project instead of `dependencies`?

cc @mraible

**Comment by mraible** [comment]
The reason it's in the dependencies section is because this is how I found it best to make things work on Heroku when deploying just using Git (and letting Heroku do the build). Here's the issue I had from another project.

> My Node/AngularJS project uses Grunt to build, test and run integration tests with Protractor. To make it easy for developers to get started, I run bower install and webdriver-update to get all the files necessary to develop and run tests. In package.json, I have:
```
  "scripts": {
    "postinstall": "./node_modules/bower/bin/bower install && ./node_modules/protractor/bin/webdriver-manager update"
  }
```
> I've found that if I want to deploy this project to Heroku, I have to remove the second part of this command where it does a 'webdriver-manager update'. I don't need to run the Protractor tests from Heroku, but it'd be nice if this didn't fail the build. Here's what I see when I try to deploy as-is:
```
remote:        bootstrap#3.3.5 bower_components/bootstrap
remote:        └── jquery#2.1.4
remote:
remote:        font-awesome#4.2.0 bower_components/font-awesome
remote:        sh: 1: ./node_modules/protractor/bin/webdriver-manager: not found
remote:
remote:        npm ERR! Linux 3.13.0-57-generic
remote:        npm ERR! argv "/tmp/build_fd2e3b6993d6341bc7e4abed740e922e/.heroku/node/bin/node" "/tmp/build_fd2e3b6993d6341bc7e4abed740e922e/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_fd2e3b6993d6341bc7e4abed740e922e/.npmrc"
remote:        npm ERR! node v0.12.4
remote:        npm ERR! npm  v2.10.1
remote:        npm ERR! file sh
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno ENOENT
remote:        npm ERR! syscall spawn
remote:        npm ERR! style-select@2.0.0 postinstall: `./node_modules/bower/bin/bower install && ./node_modules/protractor/bin/webdriver-manager update`
remote:        npm ERR! spawn ENOENT
remote:        npm ERR!
remote:        npm ERR! Failed at the style-select@2.0.0 postinstall script './node_modules/bower/bin/bower install && ./node_modules/protractor/bin/webdriver-manager update'.
remote:        npm ERR! This is most likely a problem with the style-select package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     ./node_modules/bower/bin/bower install && ./node_modules/protractor/bin/webdriver-manager update
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls style-select
remote:        npm ERR! There is likely additional logging output above.
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_fd2e3b6993d6341bc7e4abed740e922e/npm-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:
remote:        Love,
remote:        Heroku
remote:
remote:
remote:  !     Push rejected, failed to compile Node.js app
remote:
remote: Verifying deploy....
remote:
remote: !   Push rejected to style-select.
```
> I realize I could move the webdriver-update command into my Jenkins job, or have a separate command for users to run, but I like having it all-in-one. Any advice to workaround this issue on Heroku?

Here's the response I received from Heroku:

> By default, Heroku installs node dependencies using the production flag (both to trigger production options and to speed up the build by skipping development dependencies). Since protractor is in devDependencies, it's not being installed, causing the postinstall script to fail. These lines suggest the root of the problem:
```
remote:        npm ERR! style-select@2.0.0 postinstall: `./node_modules/bower/bin/bower install && ./node_modules/protractor/bin/webdriver-manager update`
remote:        npm ERR! spawn ENOENT
```
> It's trying to execute node_modules/protractor/bin/webdriver-manager update, but that path doesn't exist (ENOENT). You can replicate this locally:
```
rm -rf node_modules && npm install --quiet --production
```
> There are two ways to fix this. The first is to tell Heroku to install all dependencies, including those meant for development:
```
heroku config:set NPM_CONFIG_PRODUCTION=false
```
> Instead, I'd recommend moving only the dependencies you need for the build, like protractor, from devDependencies to dependencies. That will allow you to run what you want without bloating node_modules and slowing down your build.

> Also, I wanted to mention that all npm scripts run in a subshell with an augmented $PATH, so you instead of this:
```
"postinstall": "./node_modules/bower/bin/bower install && ./node_modules/protractor/bin/webdriver-manager update"
```
> you can use this:
```
"postinstall": "bower install && webdriver-manager update"
```
> As a final recommendation, you might get faster builds by caching bower_components. You can do that by specifying a cacheDirectories array in package.json:
```
"cacheDirectories": ["node_modules", "bower_components"]
```

Since we're no longer recommending deploying to Heroku using Git, we can probably move this dependency. However, it would be pretty cool if we did support deploying to Heroku with Git as it's a nice development workflow IMO.
