### ISSUE TITLE
jhipster not generate i18n files for enum type 

### ISSUE THREAD

**Issue by llachiheb** [jhipster/generator-jhipster#2819]
When you use enum type, jhipster generate only English files and when you switch to French language it cause js error : file not found.

**Comment by cbornet** [comment]
Indeed ! enum_fr.json doesn't exist in generators/entity/templates/src/main/webapp/i18n 
Would you do a PR ?

**Comment by llachiheb** [comment]
no _enum_fr.json in my generator-jhipster/entity/templates/src/main/webapp/i18n/

**Comment by cbornet** [comment]
PR is short for "pull request" in case you want to [contribute](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md). If you don't feel like it, no worries, we will do the fix.
