### ISSUE TITLE
Entity with optional blob field not saved

### ISSUE THREAD

**Issue by llachiheb** [jhipster/generator-jhipster#2820]
When you create an entity with optional blob filed, [photo] for example,  and try to add an entry without putting the photo field since it's optional. the system return an error message because of photo_content_type is set to "NOT NULL" in the data base.
I'am using postgres.

**Comment by deepu105** [comment]
Yes I confirm this bug

**Comment by deepu105** [comment]
@andidev since you added this feature, could you kindly take a look?

**Comment by andidev** [comment]
I'll have a closer look at it later.

@llachiheb 
Is it set not null in liquidbase script or in the java file?

I dont see it getting set to nullable=false in the liquibase script at line
https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml#L46

**Comment by andidev** [comment]
Or maybe I need to rewrite that code to make it more readable. I don't get it at the moment. I'll try to clean it up first.

**Comment by llachiheb** [comment]
@andidev in the liquibase xml script
