### ISSUE TITLE
Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: Can not deserialize instance of java.lang.String out of START_OBJECT token

### ISSUE THREAD

**Issue by kante12** [jhipster/generator-jhipster#2822]
Hi All,

I am getting this error whenever I attempt to save information to the backend for a one-to-one related entity to the 'user table' called credentials. 

HERE IS THE CODE FOR THE CREDENTIAL ENTITY CLASS:

package com.wiportal.app.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.springframework.data.elasticsearch.annotations.Document;

import javax.persistence.*;
import javax.validation.constraints.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.Objects;

/**
 * A Credentials.
 */
@Entity
@Table(name = "credentials")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Document(indexName = "credentials")
public class Credentials implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Column(name = "password", nullable = false)
    private String password;

    @NotNull
    @Column(name = "secret_question1", nullable = false)
    private String secretQuestion1;

    @NotNull
    @Column(name = "secret_question2", nullable = false)
    private String secretQuestion2;

    @NotNull
    @Column(name = "secret_answer1", nullable = false)
    private String secretAnswer1;

    @NotNull
    @Column(name = "secret_answer2", nullable = false)
    private String secretAnswer2;

    @OneToOne(mappedBy = "credentials", cascade=CascadeType.ALL)
    @JsonIgnore
    private User user;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSecretQuestion1() {
        return secretQuestion1;
    }

    public void setSecretQuestion1(String secretQuestion1) {
        this.secretQuestion1 = secretQuestion1;
    }

    public String getSecretQuestion2() {
        return secretQuestion2;
    }

    public void setSecretQuestion2(String secretQuestion2) {
        this.secretQuestion2 = secretQuestion2;
    }

    public String getSecretAnswer1() {
        return secretAnswer1;
    }

    public void setSecretAnswer1(String secretAnswer1) {
        this.secretAnswer1 = secretAnswer1;
    }

    public String getSecretAnswer2() {
        return secretAnswer2;
    }

    public void setSecretAnswer2(String secretAnswer2) {
        this.secretAnswer2 = secretAnswer2;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Credentials credentials = (Credentials) o;
        return Objects.equals(id, credentials.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Credentials{" +
            "id=" + id +
            ", password='" + password + "'" +
            ", secretQuestion1='" + secretQuestion1 + "'" +
            ", secretQuestion2='" + secretQuestion2 + "'" +
            ", secretAnswer1='" + secretAnswer1 + "'" +
            ", secretAnswer2='" + secretAnswer2 + "'" +
            '}';
    }
}

CODE IN USER  ENTITY CLASS:

   @OneToOne
    @PrimaryKeyJoinColumn
    private Credentials credentials;

    public Credentials getCredential() {
        return credentials;
    }

    public void setCredential(Credentials credentials) {
        this.credentials = credentials;
    }

HERE IS THE CODE FOR THE JS CLASS:

'use strict';
angular.module('wiPortalApp')
    .controller('PortalController',
        function ($rootScope, $scope, User, $state, Principal, Secret, Credentials) {

        Principal.identity().then(function(account) {
            $scope.account = account;
        });

        $scope.credential = {
            id: null,
            password: null,
            secretQuestion1: null,
            secretQuestion2: null,
            secretAnswer1: null,
            secretAnswer2: null
        };

        $scope.switch = false;
        $scope.questions = [];
            $scope.users = User.query();
        $scope.loadCredentials = function(id) {
            Secret.query(function(result) {
                $scope.questions = result;
            });
         Credentials.query(function(result) {
                $scope.credential = result;
            });
        };

        var onSaveSuccess = function(result){
            $scope.$emit('wiPortalApp:credentialsUpdate', result);
            $scope.isSaving = false;
        }

         var onSaveError = function(result){
            $scope.isSaving = false;
        }

        $scope.loadCredentials();

        $scope.setCredential = function(){
            if($scope.credential.password != $scope.confirm){
                $scope.doNotMatch = 'ERROR'
            }
            else {
                $scope.isSaving = true;
                if ($scope.credential.id != null) {
                    Credentials.update($scope.credential, onSaveSuccess, onSaveError);
                } else {
                    Credentials.save($scope.credential, onSaveSuccess, onSaveError);
                }
                $scope.OnSuccess = true;
                //$state.go('home.profile');
            }
        }

        $scope.verifyCredential = function(){;
            if($scope.credential[0].password != $scope.password){
                $scope.doNotMatch = 'ERROR'
            }
            else{
                $scope.isVerifying = true;
                $scope.OnSuccess = true;
                //$state.go('home.profile');
            }
        }
    });

THIS IS THE ERROR MESSAGE AS A WHOLE:

[WARN] org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver - Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: java.io.PushbackInputStream@1f80f0f0; line: 1, column: 30] (through reference chain: com.wiportal.app.domain.Credentials["secretQuestion1"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: java.io.PushbackInputStream@1f80f0f0; line: 1, column: 30] (through reference chain: com.wiportal.app.domain.Credentials["secretQuestion1"])

However, With this same domain code it allows me to create a credentials object and save it in the db once I click the credentials in the entity tab on the app navbar, but always get this error each time the setCredential() function is called.

**Comment by deepu105** [comment]
plz follow our guidelines https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue

**Comment by jdubois** [comment]
I'm sorry but this is the ticket system for JHipster, we are not going to debug a class you have created. We don't provide any "Credential" class. I'm closing this as this not a JHipster bug.

**Comment by kante12** [comment]
I am really sorry for the inconvenience. I will not bother you again unless it's a real ticket! After reading the guidelines I finally understood this repository is only for jhipster bugs. I will get help in Satck Overflow if needed.

**Comment by jdubois** [comment]
Yes @kante12 please post it on StackOverflow -> you are not bothering you, it's just that we want the questions/tickets on the right tool, so that people can get the best help possible
