### ISSUE TITLE
No marketplace entries found to handle Execution run-frontend-build

### ISSUE THREAD

**Issue by johanvdb** [jhipster/generator-jhipster#2823]
A new installation of STS 3.7.2, new workspace, and a clean import of a newly generated jhipster project, produces the attached error during import. 

I can choose to install the maven-processor-plugin from the marketplace (as per the official jhipster documentation), but not yeoman-maven-plugin.

<img width="1127" alt="screen shot 2016-02-07 at 12 23 26 pm" src="https://cloud.githubusercontent.com/assets/815840/12871847/dd9f5808-cd95-11e5-997d-2eee76771d67.png">

After installing the maven-processor-plugin and restarting, the pom still shows errors as per below:

<img width="1460" alt="screen shot 2016-02-07 at 12 29 13 pm" src="https://cloud.githubusercontent.com/assets/815840/12871856/788c4f24-cd96-11e5-8d49-79ba0b213b98.png">

**Comment by deepu105** [comment]
please follow our guideline https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue

**Comment by jdubois** [comment]
This hugely depends on your JHipster version -> I'm closing this as you didn't provide any version information. I don't have this issue on the master branch, for example.
