### ISSUE TITLE
Generating table head name based on the comments of jdl files

### ISSUE THREAD

**Issue by flyliu33** [jhipster/generator-jhipster#28295]
##### **Overview of the feature request**

a feature that can use the comment of entity defined on jdl as the table head's name of pages in the fronend. 

Since we might define the entity and property with comments, I think maybe it can be a possibility for generating the table head name of the front-end pages based on this kind of comments, this can save us time, make our work more efficient and maintained.

##### **Motivation for or Use Case**

The language of my project is non-English, there will be more than 100 tables in the future, we have the habit to use native language as the comments in jdl, as these kinds of comments can generate the database comments and other entity comments. So I think this comments should be important for our project, and should also be used as table head name. If we define the table head name manually, it would be both disaster and difficult to maintain.
![image](https://github.com/user-attachments/assets/e8447cca-fcbd-429a-8896-96ad61790332)
![image](https://github.com/user-attachments/assets/6f92c626-26d1-4846-8f29-da2718b4b416)

[monolithic.txt](https://github.com/user-attachments/files/18244069/monolithic.txt)

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
You may use https://github.com/jhipster/generator-jhipster/blob/71b6f4e83fdbf3e3b261dfb0ae3b0187e2c1abdb/generators/app/README.md#label-1

**Comment by flyliu33** [comment]
@mshima Thanks a lot, that's what I want. Annotation @EntityClassHumanized("Empresa") and @FieldNameHumanized('Company Name') did help me a lot for my case, and I also found some other awesome annotations might help me in the future , but I'v never found them on the official website until you sent me the link. I could say there might be a lot of unknown and existing features which haven't shown on the official website yet. Is it possible to update the Docs on the official website that makes user more easily to know about jhipster?

**Comment by mshima** [comment]
@flyliu33 glad it worked, since I know the internals I go directly in code to customize.
Outside help is really useful to improve documentation.
