### ISSUE TITLE
Current directory name with '-' cannot be used as app name

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#2832]
This is a regression found on current master, PR #2307 is  no longer working.

How to reproduce:

```
mkdir newApp
cd newApp
```

The proposed app name is "jhipster" while it should be "newApp".

**Comment by deepu105** [comment]
Ill take a look

**Comment by deepu105** [comment]
@gmarziou it works for me with current master, Im on windows, are you on linux/osx if so can you plz take a look. The function is in generator-base.js

```
Generator.prototype.getDefaultAppName = function() {
    return (/^[a-zA-Z0-9_]+$/.test(path.basename(process.cwd())))?path.basename(process.cwd()):'jhipster';
};
```

**Comment by pascalgrimaud** [comment]
it works on the current master too
I'm on Linux

**Comment by atomfrede** [comment]
Same for me. Works with latest master in Linux.

**Comment by gmarziou** [comment]
:disappointed: for me it did not work on both Linux and Windows on 2 different PCs
I'll dig further

**Comment by deepu105** [comment]
Thats strange maybe some issue with node ?

**Comment by gmarziou** [comment]
Sorry I could not reproduce , I don't know what I did

**Comment by gmarziou** [comment]
I found why it failed only for me: it's because my directory name was 'app-name' not 'appName' as I wrote above.

This is because the regexp used for accepting current directory name is `/^[a-zA-Z0-9_]+$/`

In PR #2307, @jdubois proposed to use [slug](https://github.com/dodo/node-slug), I think it would be a better solution using '_' as character replacement and it would also support UTF-8.

What do you think?

**Comment by deepu105** [comment]
Cant we use _.camelize ?

**Comment by jdubois** [comment]
The problem is that the name is used in many places, and I don't know if we can have specific characters like `_` or `-` in those places. That's why I'd rather not use them at all, unless someone does a study on where this is used, and if it causes any problem (probably not, in fact!).
So I'd go with Camelize by default, or Slug if we know it doesn't cause issue. Oh, and I agree Slug looks better.

**Comment by gmarziou** [comment]
OK, I'll make some tests and report here before proposing a PR.
After all, the user can still enter manually the app name so it's not blocking.

**Comment by gmarziou** [comment]
So I've wxritten a little scriot that uses slug

~~~javascript
var slug = require('slug')
var stdin = process.openStdin();

slug.defaults.mode ='pretty';
slug.defaults.modes['pretty'] = {
    replacement: '_',
    symbols: false,
    remove: /[.]/g,
    lower: false,
    charmap: slug.charmap,
    multicharmap: slug.multicharmap
};

stdin.addListener("data", function(d) {
    console.log("> "+ slug(d.toString()));
});
~~~

Below are some results.
I think slug is really robust and would work for our use case.
If you agree, I'll submit a PR.

~~~
ab(cd)[ef]
> abcdef

français
> francais

$£&€
> dollarpoundandeuro

a!?,;.
> a

b=+-_c
> b__c

a/\:b
> ab

a b
> a_b

a"b"c'd'
> abcd
~~~

**Comment by deepu105** [comment]
But we can do regex replace easily as its folder names and on linux, osx
and windows there are fixed rules on folder name pattern so cant we just do
a regex replace rather than addition of a new dependency?

**Comment by cbornet** [comment]
Simply _.underscored() ?

**Comment by gmarziou** [comment]
Slug does much more than a regex can do especially for non English characters like the Eszett

```
Wasserschloß
> Wasserschloss
```

**Comment by deepu105** [comment]
Yes I do agree that slug is very powerful and feature rich my only point is
for app name do we have to consider all these? Given user can always type
what they want even if folder name is not recognised  and we can recognise
most of the popular folder name format by tweaking current regex. But if
you feel that those kind of folder names are common then plz go ahead

**Comment by gmarziou** [comment]
Closing it for lack of interest.
