### ISSUE TITLE
[Entity sub-generator] default request sorts data twice on the "id" field

### ISSUE THREAD

**Issue by nadavlev** [jhipster/generator-jhipster#2834]
When using MS SQL the default sort of the list in an entity list page is not correct, it has a default behavior designed for mysql, sorting by 2 columns.
this syntax is not acceptable by ms sql server.
is it possible to condition this behavior by the data base selected?

**Comment by ruddell** [comment]
Sorting by two columns is acceptable syntax for MSSQL, the issue here is that the default query sorts by 'id' twice.  This doesn't generate an error in other databases but also doesn't do anything (maybe sorts twice?).

The fix is to remove the second 'id' from the 'sort' array in the query.

**Comment by deepu105** [comment]
@nadavlev we do not support MS SQL officially so we cannot do any specific change for that.
but as @ruddell said if there is a generic issue we could see how to fix that.
@geraldhumphries can you please take a look since you did the sorting implementation?

**Comment by jdubois** [comment]
Yes the issue is that MS SQL is proprietary, so we can't test it (we do this on our free time, so there's no $$$ to buy stuff), which makes it very hard for us to support this.
From my understanding it's bad that our default query sorts twice on the id, we should fix this, don't you agree @deepu105 ?

**Comment by deepu105** [comment]
yes we should fix this and then it might be easy for MS SQL use as well as
many people have successfully used MS SQL with minimal change on the .yml
files

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Then should whould reopen this, or create a new ticket for changing the default request?

**Comment by deepu105** [comment]
I think we can reopen and change the title

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
:+1:

**Comment by geraldhumphries** [comment]
This was added to fix #2422.

**Comment by deepu105** [comment]
Can we detect when sorting is by Id to do secondary sort by id only for
other columns

**Comment by geraldhumphries** [comment]
Yeah, that should not be a problem.

From what I gather, sorting by the same column twice is causing issues in MSSQL?

**Comment by ruddell** [comment]
@geraldhumphries that is correct.  The error generated is: "com.microsoft.sqlserver.jdbc.SQLServerException: A column has been specified more than once in the order by list. Columns in the order by list must be unique."

**Comment by geraldhumphries** [comment]
I am trying to come up with a clean way to do this. Here is a possible solution:
```
var sort = [vm.predicate + ',' + (vm.reverse ? 'asc' : 'desc')]
if (vm.predicate !== 'id') {
    sort.push('id');
}
<%= entityClass %>.query({
    page: pagingParams.page - 1,
    size: paginationConstants.itemsPerPage,
    sort: sort
}, onSuccess, onError);
```

**Comment by deepu105** [comment]
It looks better
