### ISSUE TITLE
Application is generated in current directory without a warning!

### ISSUE THREAD

**Issue by saas2813** [jhipster/generator-jhipster#2835]
"yo jhipster" generates a lot of files and happily clobbers the current directory without a warning.

I can see the use for letting the user select and create the target directory, but please add a warning about where you will create all the files, especially if there already are files in that directory!

**Comment by jdubois** [comment]
We are based on Yeoman and that's the way all Yeoman generators work: you generate your application in the current directory, that's documented everywhere.

**Comment by deepu105** [comment]
I dont think a warning is a nice user experience for our users and we would expect our users to have read atleast the getting started or quick start part of the documentation. That means they should know that the files will be put in the directory then run the command from.

If you feel that the documentation is not sufficient we will be happy to improve that

**Comment by cbornet** [comment]
You have at least one question before yo generates or modifies anything so that also prevents unwanted sending of the command (eg. from history) to dirty your current dir.
And the proposed app name is your current dir name so that should also ring a bell if yo proposes  something like "root" as app name.

**Comment by saas2813** [comment]
"everywhere" was not ubiquitous enough to get to me ;-)
Sure, I was a little bit careless and not looking where I was experimenting, and totally uninterested in the Yeoman app, I wanted to try out the JHipster.
I can agree that a warning that needs to be confirmed is not a good user experience, especially for people used to the tool.
Would it be bad to print the target directory directly before or after asking for the basename of the application?
Large amounts of output does not seem to be a problem otherwise.

**Comment by cbornet** [comment]
Yes, I guess that a warning log before the app name question would not hurt.

**Comment by deepu105** [comment]
Ya a log of path should be fine.

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/commit/86051cbdf0f1e073a885b42f02a6275f5c2309c5
