### ISSUE TITLE
Swagger-UI calls don't work with JWT auth

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#2836]
When using swagger UI on an application that uses JWT as authenticationType, the "Try it out" feature fails and return something like this: 
```
{
  "timestamp": "2016-02-09T13:22:08.868+0000",
  "status": 401,
  "error": "Unauthorized",
  "message": "Access Denied",
  "path": "/api/foos"
}
```
It seems that some people have already managed to solve this problem (see [this swagger-ui issue]( https://github.com/swagger-api/swagger-ui/issues/818)).

I plan to do a PR to fix that. What I will do is get the JWT token from localStorage and follow instructions from the previous link.
Please tell me if you have any thought on this.

**Comment by PierreBesson** [comment]
OK, I just got it to work. Just added:

```
function addApiKeyAuthorization() {
  var key = JSON.parse(localStorage.getItem("ls.authentication-token"));
  if (key && key.trim() != "") {
	var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("Authorization", "Bearer " + key, "header");
	window.swaggerUi.api.clientAuthorizations.add("bearer", apiKeyAuth);
	log("Set bearer token: " + key);
  }
}
```
Really JWT is magic, so easy :smiley: !

**Comment by PierreBesson** [comment]
Also, may I suggest an improvement, currently we don't have the "api_key" field on our Swagger-Ui (see for example: http://petstore.swagger.io/). It would be nice at least for JWT to be able to set different tokens directly in Swagger-UI and then try the APIs with those tokens. This is interesting for the ["granular security feature of JWT](https://auth0.com/blog/2014/12/02/using-json-web-tokens-as-api-keys/).

**Comment by gmarziou** [comment]
All changes we make to swagger-ui/_index.html have to be manually merged when we update swagger-ui, this is why we don't have the api_key input field but I like your idea.

This manual merge is a bit painful at the moment. I'm wondering whether there could be a better by externalizing our JS code from the index.html

**Comment by cbornet** [comment]
@PierreBesson  the code for the swagger page comes from springfox (https://github.com/springfox/springfox/tree/master/springfox-swagger-ui/src/web). I have removed the api_key text box on purpose but it is easy to put it again.

**Comment by PierreBesson** [comment]
@gmarziou I see the problem that would arise when updating swagger-ui. But externalizing the js will not be enough to prevent all merge conflicts.

I have an idea on how we could handle this but maybe it's a bit crazy.
So currently we go to http://localhost:8080/#/docs and there we have an iframe to swagger-ui/index.html. So I think that we could inject our custom js into this iframe (with onload="" property on the iframe element)and keep using the vanilla swagger-ui from springfox. What do you think ?

**Comment by PierreBesson** [comment]
Oh and this could mean that we could be using the webjar.

**Comment by gmarziou** [comment]
The index.html provided by springfox is not the original one from swagger-ui.
In particular, it includes springfox.js

**Comment by cbornet** [comment]
springfox.js is just the js code that was extracted from the original index.html and on which they added some special "springfox" features (ui conf from java bean, docket group selection, ...)
I guess the people from springfox will maintain this code in phase with swagger-ui.

**Comment by PierreBesson** [comment]
But shouldn't we move to springfox's swagger-ui ?
It can handle api_keys and security auth code for us (see [springfox.js](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/js/springfox.js)). We will have to set a custom Springfox security config ine java code [like here](https://github.com/springfox/springfox/blob/master/springfox-spring-config/src/main/java/springfox/springconfig/Swagger2SpringBoot.java#L128) and then swagger-ui will be configured from it. This way we stick with sprinfox's client.

**Comment by cbornet** [comment]
@PierreBesson But the apiKey we want to pass (for instance JJWT or CSRF token) comes from javacript, not from java and is dynamic so it can't come from a bean

**Comment by cbornet** [comment]
Maybe we could PR to springfox to have the possibility to add the api key by url

**Comment by PierreBesson** [comment]
@cbornet Oh I see...
>Maybe we could PR to springfox to have the possibility to add the api key by url
Yes it would be nice to have, but would it be enough to handle all our authentication schemes.

**Comment by cbornet** [comment]
Whatever the auth type, we always call SwaggerClient.ApiKeyAuthorization() so that should be OK.
On the other hand, the security impact of passing auth data to an i-frame by url should probably be studied.

**Comment by gmarziou** [comment]
This is why we enabled it only for dev.
An alternative would be to get rid of the iframe and use an angular directive on top of swagger, there a few of them.

**Comment by PierreBesson** [comment]
If we would like to customize swagger-ui a lot, it might be interesting to follow this idea. A second JHipster intern will arrive next week and he has some angular experience, he could help me to develop this. Then we could extends swagger-ui functionality for the gateway, for example to add a way to sort the available API, arrange them by folder or search the available resources)...

**Comment by gmarziou** [comment]
Sounds good, the directive I tried 3 months ago was [angular-swagger-ui](https://github.com/Orange-OpenSource/angular-swagger-ui). I just reviewed it and it is not very active, I checked also 2 others who are even less active.

So I'm afraid that these projects may not offer very good support and not migrate to angular 2 soon.

**Comment by deepu105** [comment]
I dont think it will be hard to write a directive if our own. Its better
than depending on non active projects
