### ISSUE TITLE
generator-jhipster-module not being recognized by yeoman

### ISSUE THREAD

**Issue by thiagonuic** [jhipster/generator-jhipster#2837]
I just installed the generator-jhipster-module, but Yeoman does not seem to find it. The regular jhipster generator works fine.

Node Version: 5.3
OS: MacOS X El Capitan
NPM: 3.3.12
Yeoman: 1.4.6

**Comment by notflorian** [comment]
I had also the same issue, and to solve it I had to install jhipster with `npm install generator-jhipster`, without the -g parameter.

**Comment by thiagonuic** [comment]
Thanks for the help it worked after installing both without the -g flag.
