### ISSUE TITLE
Update setting-up-ci with gulp config

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2839]
The example given is for grunt

**Comment by cbornet** [comment]
Actually, the javascript section can be removed since its already done in karma conf.

**Comment by deepu105** [comment]
Can you update the ticket https://github.com/jhipster/generator-jhipster/issues/2785 and close this, lets track everything in one ticket as we have a lot of documentation to change for next release

**Comment by cbornet** [comment]
Yes. Good idea !
