### ISSUE TITLE
one-to-one relationship: Wrong $scope variable generated in entity dialog controller

### ISSUE THREAD

**Issue by 1968058** [jhipster/generator-jhipster#2840]
JHipster's entity generator generate wrong UI-code for entity dialog controller, for entity that owns a relationship. An error occurs in the browsers console:

`"Error: $scope.wv is undefined
@http://127.0.0.1:8080/scripts/app/entities/www/www-dialog.controller.js:9:17
invoke@http://127.0.0.1:8080/bower_components/angular/angular.js:4523:14
instantiate@http://127.0.0.1:8080/bower_components/angular/angular.js:4531:27
$ControllerProvider/this.$get</<@http://127.0.0.1:8080/bower_components/angular/angular.js:9197:18
resolveSuccess@http://127.0.0.1:8080/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:4142:34
processQueue@http://127.0.0.1:8080/bower_components/angular/angular.js:14792:28
scheduleProcessQueue/<@http://127.0.0.1:8080/bower_components/angular/angular.js:14808:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://127.0.0.1:8080/bower_components/angular/angular.js:16052:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://127.0.0.1:8080/bower_components/angular/angular.js:15870:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://127.0.0.1:8080/bower_components/angular/angular.js:16160:13
done@http://127.0.0.1:8080/bower_components/angular/angular.js:10589:36
completeRequest@http://127.0.0.1:8080/bower_components/angular/angular.js:10787:7
requestLoaded@http://127.0.0.1:8080/bower_components/angular/angular.js:10728:1
"`

When I try to create new entity (http://127.0.0.1:8080/#/wwws/new)

In `src/main/webapp/scripts/app/entities/mmm/mmm-dialog.controller.js` the $scope.mmm variable is created on line 7 instead of $scope.wv, ignoring the input at entity generation:

`=================Vvv=================
Generating relationships with other entities
? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? Www
? What is the name of the relationship? wv
? What is the type of the relationship? one-to-one
? Is this entity the owner of the relationship? No
? What is the name of this relationship in the other entity? vw

=================Www=================
Generating relationships with other entities
? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? Vvv
? What is the name of the relationship? vw
? What is the type of the relationship? one-to-one
? Is this entity the owner of the relationship? Yes
? What is the name of this relationship in the other entity? wv
? When you display this relationship with AngularJS, which field from 'Vvv' do you want to use? id`

I use JHipster **v2.27.0**

`{
  "generator-jhipster": {
    "baseName": "removed",
    "packageName": "removed",
    "packageFolder": "removed",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": true,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "protractor"
    ]
  }
}`

I've created two entities:

**Www.json**

`{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "vw",
            "otherEntityName": "vvv",
            "relationshipType": "one-to-one",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "wv"
        }
    ],
    "fields": [],
    "changelogDate": "20160209011412",
    "dto": "no",
    "service": "no",
    "pagination": "pager"
}`

**Vvv.json**

`{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "wv",
            "otherEntityName": "www",
            "relationshipType": "one-to-one",
            "ownerSide": false,
            "otherEntityRelationshipName": "vw"
        }
    ],
    "fields": [],
    "changelogDate": "20160209011324",
    "dto": "no",
    "service": "no",
    "pagination": "pager"
}`

I use FF, but probably all browsers and OSs are affected.

I could reproduce the error with different relation types, when custom relation names where chosen. 

I wrote a question on [StackOverflow](http://stackoverflow.com/questions/35282934/wrong-scope-variable-in-entity-dialog-controller-in-jhipst

**Comment by deepu105** [comment]
do you want to do a PR to fix this?

**Comment by jdubois** [comment]
I don't understand, this use-case is covered by our tests... So you probably do something specific, can you explain what you do?

**Comment by jdubois** [comment]
Oh you're using one-to-one relationship!!! I'm updating the ticket title

**Comment by andidev** [comment]
I'll have a look at it.

Just one question first, you wrote :

```
In src/main/webapp/scripts/app/entities/mmm/mmm-dialog.controller.js the $scope.mmm variable is created on line 7 instead of $scope.wv, ignoring the input at entity generation:
```
Is `mmm` a typo? Did you mean `www`?

**Comment by andidev** [comment]
Okey so I can confirm this as a bug. I just reporduced it.
