### ISSUE TITLE
Entities - Better pluralisation strategy for names/strings

### ISSUE THREAD

**Issue by epikuruz** [jhipster/generator-jhipster#2843]
Currently entity names and many strings are is crated by appending "s" at the end.

It does not work in some cases 
e.g. category -> categories (and not categorys), 

When generating the entity either user should be asked what's the plural form of given name with some default value proposed  or (it is or not xor) smarter strategy should be implemented

**Comment by andidev** [comment]
Thanks for the suggestion. This is already done and merged in PR #2719 and will be available in the next 3.0 release.
