### ISSUE TITLE
Improved naming convention for Date vs DateTime object 

### ISSUE THREAD

**Issue by epikuruz** [jhipster/generator-jhipster#2845]
Currently there is no distinction in the naming of fields/columns for Dates and DateTimes(Timestamps)

I would suggest the following convention change for distinguishing both from one another:

For TimeDate use:

Java:
private ZonedDateTime xxxDateTime;

SQL/DDL:
Data type: Timestamp datatype in SQL (relational databases)
and field name xxx_at (e.g. created_at, modified_at)

For Date (LocalDate in Java)
private LocalDate xxxDate;

SQL/DDL 
Data type: Date;
field name: xxx_date (e.g. created_date)

EXAMPLE:

Built-in entity user now:

    @Column(name = "reset_date", nullable = true)
    private ZonedDateTime resetDate = null;

With the new convention (reset is not a Date as name suggests by DateTime):

  @Column(name = "reset_at", nullable = true)
    private ZonedDateTime resetDateTime = null;

With this convention it is easy to distinguish date types in Java/JS and databases

**Comment by deepu105** [comment]
Sorry, I don't agree with this. Naming convention should be users choice say if i want to create a field called `flightDate` i wouldn't want it to look like `flightDateDateTime` when generated.

Same way I can have a field called `sta` (standard arrival time) i wouldn't like to see it as `staDateTime`.

So this naming is depending on functional requirement and users should name fields accordingly

**Comment by deepu105** [comment]
Hi Michal,

You can write this in the issue itself rather than sending to me directly as that would help community to view your point of view. I have kept your message at the trail for that

And yes I know that its a good point to have a different naming convention for the field in DB but unfortunately we cannot support each and every use case. our current setup is good enough for most our users and we are very choosy when it comes to adding new options coz every option adds more maintenance work. And we are doing all this for free at our spare time.

Having said that you can try to add this feature using our [post entity creation hook](https://jhipster.github.io/modules/creating-a-module/#hooks) as a [module](https://jhipster.github.io/modules/creating-a-module/)

Thanks & Regards,
Deepu

```
On Wed, Feb 10, 2016 at 4:22 PM, Michal Maczka <michal.maczka@gmail.com> wrote:
Hey Deepu,

I just allow to contact you directly regarding the issue you just have closed. conceding Date & DateTime objects.

I fully agree with everything you said.

Just some clarification from my side as probably I was to brief to be understood properly:


In fact the whole point what I am looking for is sumarized in your last sentence:  that users should be able to chose the name of the fields:

I would like to have a possibility to name a field xxxDateTime or  xxxDate in JAVA depending on my use case, BUT have also the possiblity of calling it xxx_at and xxx_date in my database schema as this good pratices. Certianly calling the field xxx_date for Timestamp data type is not best thing to do and most DBA would agree with this :) 

Second thing:
I think that tendency to call object with Time and Date (e..g ZonedDateTime in Java 8) xxxDate is wrong (to my taste) 
It is a convention inherited from old, dark Java days where Date object was containing both Date and Time but now it can and should be challenged.


There As for HIPSTER there are also 2 things: Generated code and what convention are used in JHIpster builtin-in code. 

In your opinionated bulit-in code you are  using the many conventions (which I like a lot expect this case I am writing about).
I am proposing that JHipster bult-in code may also change the convention for Date/DateTime objects. 

 Of course I am also 100% for letting the users to chose whatever convention they want  in their code (which is not a case now)
I was thinking along the lines:

1. What the name of your filed 
> createdDateTime
2. What the type of the filed:
>DateTime
3. How would you call your database field (default: created_at)
> created_at


I think filed names carrying extra “metadata” about their types are also very useful in the fronted code (JavaScript) as they give a hint what’s the type of the object (Date vs DateTime vs Time)

After what I wrote: Is there a chance to reconsider this point/issue?
I will be happy to elaborate more my point or/and chat with you

BTW: Thanks for great project your are brining!

warm regards!

Michal

P.S.

Obviously the flightDateDateTime is not what I intended to propose :)
It should be flightDateTime (Java & JavaScript) and flight_at (DB)
I just can it right now. 

```
