### ISSUE TITLE
jhipster-sample-app contains obsolete test classes

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#2846]
Not a big issue but if you go to [jhipster-sample-app git repo](https://github.com/jhipster/jhipster-sample-app/tree/master/src/test/java/com/mycompany/myapp/web/rest) you'll find that all *ResourceTest classes are still present while they have been renamed as  *ResourceIntTest.

Probably the CI scripts that re-generate them should cleanup first the previous source files.

**Comment by jdubois** [comment]
Yes I'm generating those manually, I'm correcting the issue!!
