### ISSUE TITLE
Tomcat logging not working

### ISSUE THREAD

**Issue by muralihr** [jhipster/generator-jhipster#2850]
I build the mvn package and put the war file in the tomcat/webapps - but the log file which is configured in the log-back.xml is not created.

on the otherhand when i do just mvn - the log file is created.
How do i enable logging in the tomcat server  ?
***************************************************************************
<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>heritageweblogFile.%d{yyyy-MM-dd}.log</fileNamePattern>
            <maxHistory>90</maxHistory>
        </rollingPolicy>
        <encoder>
            <charset>utf-8</charset>
            <Pattern>%d %-5level [%thread] %logger{0}: %msg%n</Pattern>
        </encoder>
    </appender>

  <root level="@logback.loglevel@">
        <appender-ref ref="CONSOLE"/>
        <appender-ref ref="FILE"/>
    </root>
***************************************************************************

**Comment by jdubois** [comment]
Can you please follow the guidelines and give your version number, etc?

Our current configuration only sends log to the console (this might soon change, for the microservices part, and we'll have the option to send them to an ELK server).

So I don't know what you're doing this, but in your logback-spring.xml file (not "log-back.xml") there is no log file configured by us.

**Comment by olsky** [comment]
I have same issue: no log file in tomcat.

I have uncommented "FILE and ASYNC appenders" in the logback-spring.xml file.

Now, when starting with gradlew in dev -- the file is created in the project folder.
But when deploying war file to tomcat -- no file is created.

Any hints on this?

**Comment by gmarziou** [comment]
@olsky please don't camp on an old issue, open your own issue and provide all details.
