### ISSUE TITLE
missing info url from jhipster-registry

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2851]
when hitting the info url `http://192.168.0.11:8080/info` near status from jhipster-registry it fails with unauthorized access error for both gateway and apps. The error occurs even when im logged into gateway
![image](https://cloud.githubusercontent.com/assets/1107223/12948245/c180d4f0-d03b-11e5-86db-c1cc0e919a17.png)

Is this suppose to be open? or should we need to add a info resource path on the generated gateway and microservice app

**Comment by jdubois** [comment]
This is the dashboard made by Spring Boot and as far as I'm concerned the link is broken.
You don't need it, there's a better one on the gateway :-)

**Comment by deepu105** [comment]
Ok in that case.

Btw im able to access the entire app from gateway like localhost:8080/app1/
is that normal?

In that case a microsrvice can serve its UI via the gateway like this rite?

**Comment by jdubois** [comment]
Yes that's normal for the moment:

- That's why I don't want to generate the front-end on the "app1" service
- And don't forget the whole APIs are secured by Spring Security: so as soon as we have only the APIs, you will only have access to the APIs you have the permission to access
