### ISSUE TITLE
Remove Twitter from Spring social connector

### ISSUE THREAD

**Issue by moifort** [jhipster/generator-jhipster#2855]
I just realize that the Twitter API didn't return the email of the user (see https://twittercommunity.com/t/how-to-get-email-is-using-twitter-api-on-callback-page-using-php/404/20). And is not compatible with Jhipster register.

**Comment by ruddell** [comment]
One work-around that several sites use is to require the user to enter an email before registration is successful when registering with Twitter.  This adds complexity and a separate flow for Twitter registrations which is a pain.

**Comment by deepu105** [comment]
+1 for removing if its complex to workaround

Thanks & Regards,
Deepu

**Comment by cicoub13** [comment]
Twitter API gives email for whitelisted applications (https://dev.twitter.com/rest/reference/get/account/verify_credentials)

**Comment by vivekmore** [comment]
Good point @cicoub13 !
In that case I'd like to vote for keeping Twitter

**Comment by jdubois** [comment]
OK, so in that case it looks logical to keep Twitter, and I'm closing this.

**Comment by deepu105** [comment]
But still if current twitter setup is broken someone has to apply the
workaround fix I guess
