### ISSUE TITLE
Dockerfile still installs grunt

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#2857]
[Dockerfile](https://github.com/jhipster/generator-jhipster/blob/1f99be8c427266ebc6684c501a0bee72a8522afc/Dockerfile#L32) on master still installs grunt-cli.

Sorry, I'm not yet a docker user so I can't test and make a PR.

**Comment by pascalgrimaud** [comment]
good eyes :eyes:

**Comment by thiagogcm** [comment]
just one more thing.

gulp has a new cli package now
https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md

**Comment by pascalgrimaud** [comment]
thanks @thiagogcm !
Just did a PR for using the new gulp-cli
