### ISSUE TITLE
New jhipster project gives "Pre-authenticated entry point called. Rejecting access"

### ISSUE THREAD

**Issue by Burdu** [jhipster/generator-jhipster#2858]
Hi,

Just configured a new jhipster project and I am getting `[nio-8080-exec-6] n.t.s.Http401UnauthorizedEntryPoint      : Pre-authenticated entry point called. Rejecting access` each time I try to access the page. I tried empty cache and hard reload, but nothing. I can't manage to access the page.

`Request URL:http://127.0.0.1:8080/api/account?cacheBuster=1455198881952
Request Method:GET
Status Code:401 Unauthorized
Remote Address:127.0.0.1:8080`

`{timestamp: "2016-02-11T13:54:41.961+0000", status: 401, error: "Unauthorized",…}
error: "Unauthorized"
message: "Access Denied"
path: "/api/account"
status: 401
timestamp: "2016-02-11T13:54:41.961+0000"`

> ? (1/15) What is the base name of your application? MyApp
> ? (2/15) What is your default Java package name? net.MyApp
> ? (3/15) Which *type* of authentication would you like to use? OAuth2 Authentication (stateless, with an OAuth2 server implementatio
> n)
> ? (4/15) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL, Oracle)
> ? (5/15) Which *production* database would you like to use? MySQL
> ? (6/15) Which *development* database would you like to use? MySQL
> ? (7/15) Do you want to use Hibernate 2nd level cache? Yes, with HazelCast (distributed cache, for multiple nodes)
> ? (8/15) Do you want to use a search engine in your application? Yes, with ElasticSearch
> ? (9/15) Do you want to use clustered HTTP sessions? No
> ? (10/15) Do you want to use WebSockets? Yes, with Spring Websocket
> ? (11/15) Would you like to use Maven or Gradle for building the backend? Maven
> ? (12/15) Would you like to use Grunt or Gulp.js for building the frontend? Grunt (recommended)
> ? (13/15) Would you like to use the LibSass stylesheet preprocessor for your CSS? Yes
> ? (14/15) Would you like to enable translation support with Angular Translate? Yes
> ? (15/15) Which testing frameworks would you like to use? Cucumber

**Comment by jdubois** [comment]
You need to log in first. The default password is "admin/admin". After that, you won't have an authentication warning.

**Comment by Burdu** [comment]
Thanks. This was added to not running `npm install` and `grunt build` and the page looked ugly. Sorry for the trouble.
