### ISSUE TITLE
Alphabetical dependencies

### ISSUE THREAD

**Issue by erikkemperman** [jhipster/generator-jhipster#2862]
Would it make sense to ensure that the generator produces dependencies in `bower.json` and `package.json` in alphabetical order?

Currently the first commit after a `bower install --save` or `npm install --save(-dev)` gets kind of ugly, because those tools re-order these files.

A little bit of a hassle to review, I guess, but for what it's worth, it might look something like [this](https://github.com/erikkemperman/generator-jhipster/commit/a20e593071ef32b07be4d83740aea7d4a79abc87).

EDIT on closer inspection, bower doesn't re-order, but it does re-indent...

**Comment by andidev** [comment]
Isn't there a way to set indentation level for Bower somehow? I think I have seen it somewhere.

**Comment by mraible** [comment]
It's in .editorconfig.

**Comment by erikkemperman** [comment]
Well, then perhaps either change `.editorconfig` to 4 for bower, or change the template `_bower.json` to have indent 2?

**Comment by andidev** [comment]
Two spaces has been discussed already #634 

Does Bower look for editorconfig?

**Comment by erikkemperman** [comment]
Updated my [branch](https://github.com/erikkemperman/generator-jhipster/tree/feature-alphabetical) to make `_bower.json` have indent of 2 spaces.

**Comment by andidev** [comment]
Sorry maybe I was not clear enough. Two spaces has been discussed in #634 and rejected. JHipster uses 4 spaces everywhere else.
There seems to be an open issue in the bower rep https://github.com/bower/bower/issues/1338 about this.

**Comment by erikkemperman** [comment]
Ah, I see. Well, the editorconfig currently has 2 for both package and bower, the template `_package.json` has indent 2 and `_bower.json` is 4. So... Not sure how to make this consistent, or indeed if anyone else considers this a (tiny) annoyance...

**Comment by erikkemperman** [comment]
So it looks like @jdubois [changed](https://github.com/jhipster/generator-jhipster/commit/eaf722ee34053b4a15416d34649a79c4f52c6397) `bower.json` to indent 2 at one point, but current master has it at 4.

Whether or not bower respects editorconfig, currently the first commit after `bower install --save` changes basically all of `bower.json` (to 2 space indent).

**Comment by andidev** [comment]
@erikkemperman 
You seem to be right. The commit you are mentioning is actually the commit closing the issue. Sorry my bad!

**Comment by andidev** [comment]
Wow now it gets even worse for me! I'm the guilty one for the four spaces change :scream:

**Comment by andidev** [comment]
@erikkemperman 
Could you please open a PR with your changes?

**Comment by erikkemperman** [comment]
@andidev Done!

**Comment by erikkemperman** [comment]
Closing, PR merged.
