### ISSUE TITLE
Generating an entity with relationship to the User entity and with mapstruct option fails 

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2867]
The new relationship tests in the travis build (PR #2856) has revealed that generating an entity with a relation to the User entity with mapstruct option results in uncompilable code. The UserMapper.java seems to be missing.

The error got when running mvn install is the following
```
[ERROR] diagnostic: /home/travis/app-default-from-scratch/src/main/java/com/mycompany/myapp/web/rest/mapper/RelationshipTestMapstructEntityMapper.java:12: error: cannot find symbol
@Mapper(componentModel = "spring", uses = {UserMapper.class, })
                                           ^
  symbol: class UserMapper
[ERROR] diagnostic: /home/travis/app-default-from-scratch/src/main/java/com/mycompany/myapp/web/rest/mapper/RelationshipTestMapstructEntityMapper.java:12: error: Couldn't retrieve @Mapper annotation
@Mapper(componentModel = "spring", uses = {UserMapper.class, })
```

See Travis ci build for more details
https://travis-ci.org/jhipster/generator-jhipster/jobs/108714652#L2574

The error can also be regenerated with the following entity.json
```json 
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "userManyToManyEntity",
            "otherEntityName": "user",
            "relationshipType": "many-to-many",
            "otherEntityField": "login",
            "ownerSide": true
        }
    ],
    "fields": [],
    "changelogDate": "20160208210109",
    "dto": "mapstruct",
    "service": "no",
    "pagination": "no"
}
```

When this issue is fixed we should revert the tests that was removed in commit [b238510](https://github.com/andidev/generator-jhipster/commit/b238510a4f6ea2982088944ae5304ac66ff0b963)

**Comment by deepu105** [comment]
@andidev could these be related?  https://github.com/jhipster/generator-jhipster/issues/2006

**Comment by andidev** [comment]
I'm not familiar with mapstruct so I could not tell. Maybe I'll try to learn it and investigate it closer.

**Comment by jdubois** [comment]
Yes it looks related. I've been working on the older one yesterday (as part of my daily routine of trying to remove old bugs), and it's indeed a bit tricky. The solution to have a specific user mapper should be good, but I don't have the time right now to test this.
