### ISSUE TITLE
Application class should be named according to app name

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#2868]
With micro services applications being introduced in JHipster 3.0, it will be quite common to have several JHipster applications running at same time in your IDE in its own tab, as each tab is named according to the main class it means that all tabs will be named Application.

I propose to rename Application.java according to app base name.

At least, it should be done for Gateway.

I can do it if agreed.

**Comment by jdubois** [comment]
Interesting idea !!!!! At least we could put something meaningful instead of just "Application". Anybody against this?

**Comment by deepu105** [comment]
+1 for app name

**Comment by pascalgrimaud** [comment]
+1 for app name too

**Comment by gmarziou** [comment]
OK I was thinking of using same name as the angular module for the app but with first letter capitalized: sampletokenApp -> SampletokenApp.java

**Comment by deepu105** [comment]
Sounds good
