### ISSUE TITLE
jHipster fails on Java 8 javadoc compliance

### ISSUE THREAD

**Issue by ddewaele** [jhipster/generator-jhipster#2872]
I noticed when performing a maven release that the javadoc written in jHipster is not Java8 compliant.

Some errors encountered : 

- error: self-closing element not allowed
- error: unexpected end tag: </p>
- error: end tag missing: </a>
- error: bad use of '>'

Some options : 

- Fix all javadocs
- Skip javadoc generator in the pom.xml

**Comment by jdubois** [comment]
Indeed, this is something we overlook too often.
Now should we follow Javadoc? I've seen people using stuff like Asciidoc instead, and that makes the comments more readable (I don't think anybody really generates the javadoc).
I'm a bit afraid to use something most people won't know about (this is bad for our new users). But in the end I think it makes the code much clearer.

**Comment by ddewaele** [comment]
I'm not a big fan of javadoc, but I can understand people wanting to use it. Also hearing a lot of good things about Asciidoc, but I understand it might not fit 100% in the jHipster philosophy. (using as much standard stuff as possible).

I'm more concerned with the fact that an out-of-the box jHipster experience fails when executing a maven release. (that does generate javadocs)

I'm currently just skipping the javadoc generation
```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>2.10.3</version>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                </plugin>
```
 

I would either 

- Fix all the javadocs, providing you can catch future violations somehow in your test-suite (I don't know if your test suite involves generating a jhipster app and seeing if it compiles / runs)
- remove all the javadocs from the generated code 
- skip the javadoc generation by default

**Comment by erikkemperman** [comment]
For what it's worth, I believe this is particularly annoying with Jenkins, which explicitly has to be configured to not fail on javadoc.

The problem is  that the jdk8 tools suddenly strictly validate the html output from javadoc, they were lenient before; the snippet @ddewaele posted above is apparently the de-facto workaround for this in Maven builds.

**Comment by hirro** [comment]
I can use the maven release plugin on jhipster project with the following
option set:

<maven.javadoc.failOnError>false</maven.javadoc.failOnError>



2016-02-13 17:04 GMT+01:00 Erik Kemperman <notifications@github.com>:

**Comment by erikkemperman** [comment]
Or just set that property on the maven-javadoc plugin. Either way, that's definitely better than skipping javadoc entirely. The issue with Jenkins is just that it does `mvn javadoc` by default.

**Comment by jdubois** [comment]
OK, let's correct the Javadoc errors first: this is simple, and we indeed
want to generate something standard and without any issues.
Le 13 févr. 2016 5:14 PM, "Erik Kemperman" <notifications@github.com> a
écrit :

**Comment by erikkemperman** [comment]
That would be ideal, then there'd be no need to supress errors or skip -- but a big and tedious chore.

**Comment by notflorian** [comment]
If that's ok with you, I'm currently working on a PR to correct the errors and make the javadoc doclint compliant.

**Comment by deepu105** [comment]
You are welcome to do PR
