### ISSUE TITLE
TranslationFilterProvider error when creating a new project without translation support

### ISSUE THREAD

**Issue by dhafirnz** [jhipster/generator-jhipster#2874]
I started a new Jhipster application and chose not to have International support. When I started adding my entities AngularJs failed to boot strap on my entities and started to get the following AngularJS error:
Error: [$injector:unpr] Unknown provider: translateFilterProvider <- translateFilter

This is without me adding a single character of code.
I then regenerated the project and this time I chose International support and that went fine and smooth without error.

I created all my entities using jhipster-uml (V1.6.1) JDL script.

**Comment by andidev** [comment]
Need more info 
Please read our bug submission guidelines 
https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue

**Comment by deepu105** [comment]
I think this is fixed in master

**Comment by ruddell** [comment]
I fixed this in #2700 but the 2.27.0 version still has this issue.

**Comment by deepu105** [comment]
Closed as its fixed in next release
