### ISSUE TITLE
Generators are oblivious to automatic JS inclusion

### ISSUE THREAD

**Issue by steeltomato** [jhipster/generator-jhipster#2875]
When using automatic JS inclusion (as given in the Tips and Tricks), the generators will drop new JS files after the  needle. This causes various errors due to the duplicate loading of routes.

Version: 2.27.0

Steps to reproduce:
- Generate a vanilla jhipster application
- Follow the steps here to use automatic JS inclusion: http://jhipster.github.io/tips/002_tip_include_js_grunt.html
- Follow the tutorial here to add an entity: http://jhipster.github.io/creating-an-entity/
- Observe that the the new entity files are included after the  needle and the application fails to start due to duplicate loading of JS files.

**Comment by gmarziou** [comment]
Please follow [our guidelines for submitting an issue](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submit) and provide needed details.

**Comment by deepu105** [comment]
Its just a tip and you have to follow it and do the required changes in
your index.html as well. Show us what you have done and other required
details as per submission guidelines

**Comment by andidev** [comment]
Maybe we should exclude the entity files in the config.

**Comment by deepu105** [comment]
It doesn't duplicate since the include in within build block 
```
<!-- build:js({.tmp,src/main/webapp}) scripts/app.js -->
<!-- !DO NOT EDIT! autogenerated includes, see Gruntfile.js -->
<!-- include: "type": "js", "files": "<%= app.scripts %>" -->
    <!-- Files willbe added here by includeSource-->
<!-- /include -->
<!-- endbuild -->
```

We cannot help you unless you provide proper details

**Comment by deepu105** [comment]
btw were you running grunt serve when adding entities?

**Comment by deepu105** [comment]
and since we are dropping grunt support, I should remove this Tip as well I guess.

You can refer https://github.com/jwvdiermen/grunt-include-source and exclude the entities if required
