### ISSUE TITLE
User Management does not load on project without translation

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#2877]
* **Overview of the issue**
User Management does not load on project without translation enabled.  No stack trace is thrown in the console but the issue is in user-management.js in the resolve methods.

* **Motivation for or Use Case** 
I use JHipster without translation

* **JHipster Version(s)** 
Master - this is not an issue in the current 2.27.0 release.

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
Any project with translation set to no

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
No entities required

* **Browsers and Operating System** 
Issue with all browsers and operating systems

* **Reproduce the error** 
Generate a project without translation.  'translatePartialLoader' is included by default in user-management.js routes of user-management and user-management-detail

* **Suggest a Fix** 
#2878

**Comment by deepu105** [comment]
The translation block should be filtered by the regex, need to check the
regex
