### ISSUE TITLE
Gradle - All Commands Log "Starting the Unit and Integration test"

### ISSUE THREAD

**Issue by lukasbradley** [jhipster/generator-jhipster#2882]
Extremely trivial defect.  When using Gradle for the build system, JHipster 2.27.0 always logs the following message regardless if tests are run:  "Starting the Unit and Integration test"

Example:

```
[lbradley@localhost gardenhood]$ ./gradlew clean
Starting the Unit and Integration test
:clean

BUILD SUCCESSFUL

Total time: 5.217 secs
```

**Comment by phouverneyuff** [comment]
It was fix it in master. 
When the new release is released, you will not see this.
