### ISSUE TITLE
add infinite-scroll & ngFileUpload dependency only when the option is selected in any entity

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2888]
currently the 'infinite-scroll' option is added as a default dependency even if none of the entities have that option selected.

I propose to add the dependency when the option is selected for any entity. we can use the needle present in bower file and app.module.js for this and our needle method will ensure that there is no duplication as well.

Only downside of this is that bower install needs to be run after adding this, it can be triggered using the `bowerInstall` method from entity sub generator.

The same goes for `ngFileUpload` dependency as well

**Comment by jdubois** [comment]
I understand the issue, then those are only small dependencies and it looks complicated to add afterwards: this is not a priority for me

**Comment by deepu105** [comment]
Its not complicated, just an if check and a line of code for each

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
I can do this later

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
you were right the changes are not worth the value
