### ISSUE TITLE
Use gulp-inject instead of wiredep

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2889]
Switch to gulp-inject from wiredep

This will give following benefits on top of what wiredep gives

1. we can remove the manual inject code [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/index.js#L473) , [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L1610) and [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L35)
2. when in serve mode will automatically add user scripts to index

cc @erikkemperman

**Comment by erikkemperman** [comment]
@deepu105 While I think it's possible to use gulp-inject to replace both wiredep and usemin, it might make sense to only replace gulp-usemin for the moment? We had some talk about this on the other issue, and looked at angular fullstack, which uses a combination of gulp-inject and wiredep.

**Comment by deepu105** [comment]
Im ok either way @erikkemperman do you wanna try this out?

**Comment by erikkemperman** [comment]
I think that would be an interesting experiment, but I'm going to be really busy with some other things the next week, maybe even a bit longer...

**Comment by erikkemperman** [comment]
For anyone wanting to take a stab at this, the [gulpfile](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/gulpfile.babel(gulp).js) of angular fullstack might be provide some inspiration. I especially like their use of `lazypipe` for re-usable gulp blocks.

**Comment by deepu105** [comment]
I looked at it but was a lot of tasks, anyway this is not very important
now can be done later also after 3.0 release

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Wiredep is not maintained anymore it seems.

https://github.com/taptapship/wiredep

So we should find an alternative solution soon
