### ISSUE TITLE
Cannot start jhipster (first start)

### ISSUE THREAD

**Issue by lucav** [jhipster/generator-jhipster#2891]
I'm using Windows 10, Eclipse Mars.1, JDK 8.

I have followed today your guides (selected postgresql database for dev and prod): 
1- http://jhipster.github.io/installation/
2- http://jhipster.github.io/creating-an-app/
3- After that, i have imported the project in Eclipse as Maven project.
4- When i launch Maven install, all it's ok (also the tests run: 25, Failures: 0, Errors: 0, Skipped: 0)
5- If i try to launch as Spring Boot App i got the error as attached stack trace. 
(i have upgraded the `spring-boot-starter-parent` to 1.3.2 and `postgresql.version` to `9.4-1206-jdbc42` in the pom.xml file but (after clean, install and run) i got the same error).

[error.txt](https://github.com/jhipster/generator-jhipster/files/131212/error.txt)

**Comment by notflorian** [comment]
Hi,

I don't think this is a bug in JHipster, as it seems there is an issue with your database. Maybe it's not started, or the login/password are wrong, or the database URL is incorrect.

Could you please post your issue on StackOverflow?

Thanks

**Comment by gmarziou** [comment]
As @notflorian said, this is a question for stackoverflow not an issue, so I'm closing it. 

Please read our guidelines: http://jhipster.github.io/help/
