### ISSUE TITLE
Modify build & doc now that Oracle JDBC drivers are on Maven Central

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2894]
See https://blogs.oracle.com/dev2dev/entry/oracle_maven_repository_instructions_for

**Comment by jdubois** [comment]
As written in the blog post, you need to have a valid user & password to use it... So basically it's unusable.
Thank you Oracle for a misleading blog post that made me lose my time....

**Comment by gmarziou** [comment]
They'll never learn how to build simple things.
