### ISSUE TITLE
One letter relationshipName in ManyToOne relationships fails mapping with mapstruct

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2899]
**jdl that does not work (with default app config)**
```
entity A {}
entity B {}

relationship ManyToOne {
  A{b} to B{a}
}

dto A, B with mapstruct
```

fails with the following error when running `mvn clean install`
```bash
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ jh ---
[ERROR] diagnostic: /Users/anders/Workspace/jh/src/main/java/com/mycompany/myapp/web/rest/mapper/AMapper.java:20: error: No property named "bId" exists in source parameter(s).
    @Mapping(source = "bId", target = "b")
    ^
[ERROR] diagnostic: /Users/anders/Workspace/jh/src/main/java/com/mycompany/myapp/web/rest/mapper/AMapper.java:15: error: Unknown property "bId" in return type.
    @Mapping(source = "b.id", target = "bId")
    ^
[WARNING] diagnostic: /Users/anders/Workspace/jh/src/main/java/com/mycompany/myapp/web/rest/mapper/UserMapper.java:23: warning: Unmapped target properties: "createdBy, createdDate, lastModifiedBy, lastModifiedDate, id, activationKey, resetKey, resetDate, persistentTokens".
    User userDTOToUser(UserDTO userDTO);
         ^
[ERROR] error on execute: error during compilation
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**jdl that does works**
```
entity A {}
entity B {}

relationship ManyToOne {
  A{bb} to B{a}
}

dto A, B with mapstruct
```

**Comment by MathieuAA** [comment]
Did you check the dumped JSON? Are they valid?

**Comment by andidev** [comment]
Good point! They seem to be correct though so it's not JHipster UML.

**Comment by andidev** [comment]
**A**
```json
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "b",
      "otherEntityName": "b",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [],
  "changelogDate": "20160216211956",
  "dto": "mapstruct",
  "pagination": "no"
}
```

```json
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "a",
      "otherEntityName": "a",
      "relationshipType": "one-to-many",
      "otherEntityRelationshipName": "b"
    }
  ],
  "fields": [],
  "changelogDate": "20160216211956",
  "dto": "mapstruct",
  "pagination": "no"
}
```

**Comment by MathieuAA** [comment]
Confirmed with JHipster UML 1.6.1+ (and JHipster git-version), with these JSON files:

**For A:**
```
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "b",
      "otherEntityName": "b",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [],
  "changelogDate": "20160216214208",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no"
}
```

**And B:**
```
{
  "relationships": [],
  "fields": [],
  "changelogDate": "20160216214209",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no"
}
```

The JSON are the same with JHipster (Q&A) and JHipster UML.

Quite an interesting bug, nice find!

**Comment by deepu105** [comment]
@andidev could this be a mapstruct bug?

**Comment by deepu105** [comment]
I tried to create the same using entity sub gen and it has same issue. I dont understand why, seems like something to do with mapstruct I guess

**Comment by deepu105** [comment]
I have opened an issue on mapstruct https://github.com/mapstruct/mapstruct/issues/789

**Comment by deepu105** [comment]
From the comments on mapstruct issue I created seems like funny bean spec thingy

> Well, I took a closer look why that happens. The thing is, that according to the Java Bean Specification the correct accessor methods for the property aId would have to be getaId() and setaId(..), as the property name derived from the accessors getAId() / setAId(..) would be AId.
> 
> (from the bean specification 1.01, section 8.8):
> 

```
Thus when we extract a property or event name from the middle of an existing Java name, we
normally convert the first character to lower case. However to support the occasional use of all
upper-case names, we check if the first two characters of the name are both upper case and if
so leave it alone.
```

> MapStruct works on property names derived from the accessor methods and not the actual class attribute names. In your case, you'd have to use "AId" in the @Mapping annotations.
> 
> This may look funny. But I think we should stick to the bean-spec here. Otherwise, what would be the harm being a bit more lax in case we don't find a match with the strict checking... 
> I guess we should think about that...

@jdubois I rememeber we doing something like this on the domain classes once. I guess we need do the same in this case as well

**Comment by jdubois** [comment]
@deepu105 yes we follow the spec, which is completely weird, see this: https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L1455
And yes, that crazy :-)

**Comment by deepu105** [comment]
I think we need to do that for DTO as well

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Fixed by #2899

**Comment by deepu105** [comment]
@jdubois was this closed by mistake?  I dont see any PR or commit

**Comment by jdubois** [comment]
Sorry it's my fault, the commit is https://github.com/jhipster/generator-jhipster/commit/6f4c60ae139306d21ceea80f4296d76af4afad2f

**Comment by deepu105** [comment]
I guess the guys who came up with naming conventions were on a high :P
