### ISSUE TITLE
TranslatePartialLoader not removed by regex

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#2905]
* **Overview of the issue**
The regex that removes translatePartialLoader from projects without translation is not functioning.  None of the translatePartialLoaders are removed.

* **Motivation for or Use Case** 
I use JHipster without translation.
* **JHipster Version(s)** 
Master - Started after #2885 

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
Any project without translation.

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
No entities required.

* **Browsers and Operating System** 
All

* **Reproduce the error** 
Generate a project without translation enabled.

* **Related issues** 
#2877

* **Suggest a Fix** 
Pinging @deepu105 - I'm not the best with regex and you handled the previous change

**Comment by deepu105** [comment]
Ill check

**Comment by cirovladimir** [comment]
Perhaps related to this, when elasticsearch is enabled, it seems to leave a translate filter on placeholder attributes like so

`<input type="text" class="form-control" ng-model="searchQuery" id="searchQuery" placeholder="{{ 'jhipsterApp.book.home.search' | translate }}">`

causing the following error: 
>Error: [$injector:unpr] Unknown provider: translateFilterProvider <- translateFilter

**Comment by ruddell** [comment]
@cirovladimir that was fixed in #2700 but is still in issue in the latest release

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/commit/67c3877b51c2515fc296d38bdc1726c1f3b3b29f
