### ISSUE TITLE
Current master fails protractor tests

### ISSUE THREAD

**Issue by erikkemperman** [jhipster/generator-jhipster#2908]
No time to investigate this unfortunately, but thought you'd want to know.

EDIT Borrowing from a recent Travis build: this is pretty much what I am seeing:
https://travis-ci.org/jhipster/generator-jhipster/jobs/109839487#L3767

**Comment by mraible** [comment]
Looking into this now...

**Comment by pascalgrimaud** [comment]
If I remember well, it comes from https://github.com/jhipster/generator-jhipster/pull/2186 when we add the login popup ; there are some changes with login / home page

But yes, Travis should failed...

**Comment by mraible** [comment]
Yes, this appears to be one of the issues. Also, there's a bug that after logging in, the username doesn't show up. This has been there for a couple weeks. It shows the following on the screen after logging in.

```
You are logged in as user "".
```

**Comment by erikkemperman** [comment]
Thanks for looking into this! I noticed the empty username as well, navigating to another page and back makes it appear.

But shouldn't these failing protractor tests make Travis fail the corresponding build as well? As in the above link, it seems it currently doesn't!
