### ISSUE TITLE
Problème with my jhipster

### ISSUE THREAD

**Issue by francisyuya** [jhipster/generator-jhipster#2909]
Hi. I am new on jhipster. I have created a new projet but when i try to compile the program with the command "mvn spring-boot:run" i have the following error.
Please help me
Thanks...

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building bookstore 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.3.0.RELEASE:run (default-cli) @ bookstore >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ bookstore ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.4.201502262128:prepare-agent (pre-unit-tests) @ bookstore ---
[INFO] surefireArgLine set to -javaagent:C:\\Users\\ME\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.4.201502262128\\org.jacoco.agent-0.7.4.201502262128-runtime.jar=destfile=C:\\eclipseJ2EE\\workspace\\bookstore\\target\\test-results\\coverage\\jacoco\\jacoco.exec
[INFO] 
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ bookstore ---
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:34: error: illegal start of expression
        return () -> {
                ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:34: error: illegal start of expression
        return () -> {
                   ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:34: error: illegal start of expression
        return () -> {
                     ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:44: error: class, interface, or enum expected
    private Runnable createWrappedRunnable(final Runnable task) {
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:44: error: class, interface, or enum expected
    private Runnable createWrappedRunnable(final Runnable task) {
                                                 ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:48: error: class, interface, or enum expected
            } catch (Exception e) {
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:50: error: class, interface, or enum expected
            }
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:52: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:56: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:59: error: class, interface, or enum expected
    public Future<?> submit(Runnable task) {
           ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:61: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:64: error: class, interface, or enum expected
    public <T> Future<T> submit(Callable<T> task) {
           ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:66: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:69: error: class, interface, or enum expected
    public void destroy() throws Exception {
           ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:72: error: class, interface, or enum expected
            bean.destroy();
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:73: error: class, interface, or enum expected
        }
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:77: error: class, interface, or enum expected
    public void afterPropertiesSet() throws Exception {
           ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:80: error: class, interface, or enum expected
            bean.afterPropertiesSet();
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\async\ExceptionHandlingAsyncTaskExecutor.java:81: error: class, interface, or enum expected
        }
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:46: error: illegal start of expression
            taskExecutor.execute(() -> {
                                  ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:46: error: illegal start of expression
            taskExecutor.execute(() -> {
                                     ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:46: error: illegal start of expression
            taskExecutor.execute(() -> {
                                       ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:46: error: ';' expected
            taskExecutor.execute(() -> {
                                        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:50: error: 'catch' without 'try'
                } catch (LiquibaseException e) {
                  ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:50: error: ')' expected
                } catch (LiquibaseException e) {
                                           ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:50: error: not a statement
                } catch (LiquibaseException e) {
                        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:50: error: ';' expected
                } catch (LiquibaseException e) {
                                             ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:53: error: illegal start of expression
            });
             ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:54: error: illegal start of type
        } else {
          ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:54: error: ';' expected
        } else {
              ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:55: error: <identifier> expected
            log.debug("Starting Liquibase synchronously");
                     ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:55: error: illegal start of type
            log.debug("Starting Liquibase synchronously");
                      ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:56: error: invalid method declaration; return type required
            initDb();
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:58: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:62: error: class, interface, or enum expected
        watch.start();
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:63: error: class, interface, or enum expected
        super.afterPropertiesSet();
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:64: error: class, interface, or enum expected
        watch.stop();
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:65: error: class, interface, or enum expected
        log.debug("Started Liquibase in {} ms", watch.getTotalTimeMillis());
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\config\liquibase\AsyncSpringLiquibase.java:66: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:112: error: illegal start of expression
        PersistentToken token = userRepository.findOneByLogin(login).map(u -> {
                                                                            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:112: error: illegal start of expression
        PersistentToken token = userRepository.findOneByLogin(login).map(u -> {
                                                                              ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:112: error: ';' expected
        PersistentToken token = userRepository.findOneByLogin(login).map(u -> {
                                                                               ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:121: error: illegal start of type
        }).orElseThrow(() -> new UsernameNotFoundException("User " + login + " was not found in the database"));
         ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:121: error: ';' expected
        }).orElseThrow(() -> new UsernameNotFoundException("User " + login + " was not found in the database"));
          ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:121: error: invalid method declaration; return type required
        }).orElseThrow(() -> new UsernameNotFoundException("User " + login + " was not found in the database"));
           ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:121: error: illegal start of type
        }).orElseThrow(() -> new UsernameNotFoundException("User " + login + " was not found in the database"));
                       ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:121: error: ';' expected
        }).orElseThrow(() -> new UsernameNotFoundException("User " + login + " was not found in the database"));
                         ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:122: error: illegal start of type
        try {
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:122: error: ';' expected
        try {
           ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:123: error: <identifier> expected
            persistentTokenRepository.saveAndFlush(token);
                                                  ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:123: error: <identifier> expected
            persistentTokenRepository.saveAndFlush(token);
                                                        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:124: error: invalid method declaration; return type required
            addCookie(token, request, response);
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:124: error: <identifier> expected
            addCookie(token, request, response);
                           ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:124: error: <identifier> expected
            addCookie(token, request, response);
                                    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:124: error: <identifier> expected
            addCookie(token, request, response);
                                              ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:125: error: class, interface, or enum expected
        } catch (DataAccessException e) {
          ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:127: error: class, interface, or enum expected
        }
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:138: error: class, interface, or enum expected
    public void logout(HttpServletRequest request, HttpServletResponse response, Authentication authentication) {
           ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:140: error: class, interface, or enum expected
        if (rememberMeCookie != null && rememberMeCookie.length() != 0) {
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:143: error: class, interface, or enum expected
                PersistentToken token = getPersistentToken(cookieTokens);
                ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:144: error: class, interface, or enum expected
                persistentTokenRepository.delete(token);
                ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:145: error: class, interface, or enum expected
            } catch (InvalidCookieException ice) {
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:147: error: class, interface, or enum expected
            } catch (RememberMeAuthenticationException rmae) {
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:149: error: class, interface, or enum expected
            }
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:152: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:161: error: class, interface, or enum expected
        }
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:163: error: class, interface, or enum expected
        String presentedToken = cookieTokens[1];
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:164: error: class, interface, or enum expected
        PersistentToken token = persistentTokenRepository.findOne(presentedSeries);
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:166: error: class, interface, or enum expected
        if (token == null) {
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:169: error: class, interface, or enum expected
        }
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:173: error: class, interface, or enum expected
        if (!presentedToken.equals(token.getTokenValue())) {
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:176: error: class, interface, or enum expected
            throw new CookieTheftException("Invalid remember-me token (Series/token) mismatch. Implies previous " +
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:178: error: class, interface, or enum expected
        }
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:182: error: class, interface, or enum expected
            throw new RememberMeAuthenticationException("Remember-me login has expired");
            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:183: error: class, interface, or enum expected
        }
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:185: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:189: error: class, interface, or enum expected
        random.nextBytes(newSeries);
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:190: error: class, interface, or enum expected
        return new String(Base64.encode(newSeries));
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:191: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:195: error: class, interface, or enum expected
        random.nextBytes(newToken);
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:196: error: class, interface, or enum expected
        return new String(Base64.encode(newToken));
        ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:197: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\CustomPersistentRememberMeServices.java:203: error: class, interface, or enum expected
    }
    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:36: error: illegal start of expression
        return userFromDatabase.map(user -> {
                                          ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:36: error: illegal start of expression
        return userFromDatabase.map(user -> {
                                            ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:36: error: ';' expected
        return userFromDatabase.map(user -> {
                                             ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:37: error: not a statement
            if (!user.getActivated()) {
               ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:37: error: ';' expected
            if (!user.getActivated()) {
                                     ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:41: error: illegal start of expression
                    .map(authority -> new SimpleGrantedAuthority(authority.getName()))
                                    ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:46: error: illegal start of type
        }).orElseThrow(() -> new UsernameNotFoundException("User " + lowercaseLogin + " was not found in the " +
         ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:46: error: ';' expected
        }).orElseThrow(() -> new UsernameNotFoundException("User " + lowercaseLogin + " was not found in the " +
          ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:46: error: invalid method declaration; return type required
        }).orElseThrow(() -> new UsernameNotFoundException("User " + lowercaseLogin + " was not found in the " +
           ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:46: error: illegal start of type
        }).orElseThrow(() -> new UsernameNotFoundException("User " + lowercaseLogin + " was not found in the " +
                       ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:46: error: ';' expected
        }).orElseThrow(() -> new UsernameNotFoundException("User " + lowercaseLogin + " was not found in the " +
                         ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\security\UserDetailsService.java:49: error: class, interface, or enum expected
}
^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\service\AuditEventService.java:52: error: ')' expected
            (auditEventConverter::convertToAuditEvent);
                                ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\service\AuditEventService.java:52: error: illegal start of expression
            (auditEventConverter::convertToAuditEvent);
                                 ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\service\AuditEventService.java:52: error: ';' expected
            (auditEventConverter::convertToAuditEvent);
                                                     ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\service\UserService.java:47: error: illegal start of expression
            .map(user -> {
                       ^
[ERROR] diagnostic: C:\eclipseJ2EE\workspace\bookstore\src\main\java\bookstore\service\UserService.java:47: error: illegal start of expression
            .map(user -> {
                         ^
[ERROR] error on execute: error during compilation
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.453s
[INFO] Finished at: Wed Feb 17 16:47:16 WAT 2016
[INFO] Final Memory: 22M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bsc.maven:maven-processor-plugin:2.2.4:process (process) on project bookstore: Error executing: error during compilation -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by deepu105** [comment]
plz follow our guidelines https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-submission-guidelines and open proper issues
