### ISSUE TITLE
Ask for default language and other languages to include when generating an app with translate support

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2917]
When generating a JHipster app it would be nice to be able to chose the default language configured (currently english) and other languages to include (currently french). Most probably one would want to have the native language of the users country as default and english as secondary. And most probably they don't want the default setup english as default and french as secondary.

This should come as two questions after selecting to enable angular translate support
```
? (14/15) Would you like to enable translation support with Angular Translate? Yes
? (14/15) Would you like to enable translation support with Angular Translate? 
?         Select the default language?
 ◯ Chinese (Simplified)
 ◯ Chinese (Traditional)
 ◯ Danish
 ◯ Dutch
❯◉ English
 ◯ Galician
 ◯ German
 ◯ Hungarian
?         Select other languages?
❯◯ Chinese (Simplified)
 ◯ Chinese (Traditional)
 ◯ Danish
 ◯ Dutch
 ◯ Galician
 ◯ German
 ◯ Hungarian
```

@jhipster/developers 
What do you think of this?

**Comment by deepu105** [comment]
+1 for this, this can be done by skipping en and fr files in app generation
and then composing the language generator at the post run hook I guess it
would be more elegant as currently people might not want French as
secondary and have to remove it manually

**Comment by pascalgrimaud** [comment]
good idea +1

**Comment by andidev** [comment]
@deepu 
Do you know what's the best way to access template files in another generator. Is the best way prefixing the path a `.. /.. /languages/templates`?

**Comment by deepu105** [comment]
I dont get it, are you talking about accessing templates of a sub generator
from main generator?

**Comment by andidev** [comment]
Yes

**Comment by deepu105** [comment]
Cant you just invoke the language sub generator by composition and let it
do the work?

**Comment by andidev** [comment]
Maybe, not sure how to do that. I'm a bit unfamiliar with the new structure.

**Comment by deepu105** [comment]
Check how the main app generator composes client generator and server
generator,  or even better check how the entity generator is composed for
the --with-entities flag

**Comment by andidev** [comment]
Ah thanks I'll do that!
