### ISSUE TITLE
Generated entity service name could clash with JHipster service name 

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2921]
Moving the dissussion from end of old closed issue #1966 to here.

The problem occurs e.g. when generating an entity called `Language` where a service containing the REST API is created with the name `Language`. This will clash with the internal JHipster service also called `Language` which is used to switch the current language. The problem was introduced after issue #2645 was solved since the reserved keywords was removed.

Solutions:
1. Prefix all the generated internal services with `Jhi` e.g. the `JhiLanguage`
2. Postfix all the generated entity service with `Resource` e.g. `LanguageResource` (as it is named in backend)
3. Postfix all the generated entity service with `Api` e.g. `LanguageApi` 
4. Postfix all the generated entity service with `Rest` e.g. `LanguageRest` 
5. Reintroduce the reserved entity names

@jhipster/developers 
Please upvote and downvote the ones you like or dislike with a comment and add more solution suggestions if you have any.

**Comment by jdubois** [comment]
I would go with "JhiLanguage". That's what we already do for database tables and AngularJS directives, so this is usual for JHipster-provided code.
I didn't want to do this at the beginning as I wanted the generated code to be without any trace of JHipster, but in the end I've never seen anyone complaining about this.

**Comment by deepu105** [comment]
+1 for jhi prefix

**Comment by pascalgrimaud** [comment]
+1 for JhiLanguage

**Comment by andidev** [comment]
So I guess that the jhi prefix suggestion means we need to prefix every service and controller and other things created with the angular factory method? 
Should we also prefix the filenames?

**Comment by andidev** [comment]
Also what about the ui-router states? Should they also be prefixed?

**Comment by deepu105** [comment]
i dont think we need to prefix ui routers, lets do services first coz they
cause conflicts

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
no I wouldn't prefix everything, only the minimum
@deepu105 btw we have "jh-alert" directive that you created, shouldn't it be "jhi-alert"?

**Comment by deepu105** [comment]
yes it needs to be renamed for consistency as well

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
@andidev Im assigning this to you hope its ok for you

**Comment by andidev** [comment]
Yes that's okey. I'll work on this as soon as I'm done with #2917

**Comment by jdubois** [comment]
Why don't we have reserved keywords anymore? I don't think this was such a bad idea for this kind of use case.

**Comment by deepu105** [comment]
IMO jhi prefix is better than not allowing users to create entities with those names at all. for example Language, Health etc are very common names used and what we provide are purely admin service modules and not entities so ideally they shouldn't be in for clash

**Comment by jdubois** [comment]
OK then, I guess there aren't that many services do rename?

**Comment by deepu105** [comment]
I guess just the admin ones, health, config, metrics, tracker and language

Thanks & Regards,
Deepu

**Comment by wmarques** [comment]
I'll do this.

**Comment by andidev** [comment]
Now that the angular prefix is optional for entities I think we need to prefix the controllers and states as well.

**Comment by wmarques** [comment]
For now I renamed services @deepu105 mentioned above in [this commit](https://github.com/wmarques/generator-jhipster/commit/ede00ce4f0991bd932d4abee9e8cb6c740516afe). Should I also rename the files ?
I can start renaming controllers and state.

**Comment by gmarziou** [comment]
FYI, on stackoverflow a user had created a Site entity which was conflicting with our site state.

http://stackoverflow.com/questions/35622553/unable-to-add-site-as-an-entity-in-jhipster

**Comment by deepu105** [comment]
Lets leave at the services for now. I dont think we need to rename
everything. What controllers and state do you think has chances of
collision?  Some can be renamed to match what they are doing for example
HealthController can be better renamed to HealthCheckController similarly
MetricsController can be called MetricsMonitoringController so that the
chances of collision are less

**Comment by andidev** [comment]
Yes that could be an option. Though it feels good to be consistent and rename them all the same.

**Comment by deepu105** [comment]
I dont have issue in renaming the admin modules which we provide

Thanks & Regards,
Deepu
