### ISSUE TITLE
Migrate to ngStorage and add a rememberMe option for JWT authentication

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2922]
Currently we use angular-local-storage for working with localstorage.

This is the most popular library for dealing with localstorage in AngularJS, but it has a drawback: its API can be configured to use either localstorage or sessionstorage, but not work with both together.

We need this feature if we want to improve JWT authentication:

- Currently the JWT token is stored in localstorage for 24 hours. This isn't good for security, and this isn't good if people want a good "remember me" service.
- My goal is to add a "remember me" box (like we have for session authentication), and store the JWT token in sessionstorage (if remember me is false) or in localstorage (for 30 days, if remember me is true)

In order to use both sessionstorage and localstorage together, I want to migrate from angular-local-storage to [ngStorage](https://github.com/gsklee/ngStorage) which has got the right API for this.

**Comment by deepu105** [comment]
+1

**Comment by andidev** [comment]
+1
