### ISSUE TITLE
[OAuth2] [MongoDB] “The given entity must not be null” when request token, on jHipster + mongodb installation.

### ISSUE THREAD

**Issue by ndkhoiits** [jhipster/generator-jhipster#2924]
* **Overview of the issue**

Sometime, I cannot refresh or create new access token, with error in json
```
{
  "error": "server_error",
  "error_description": "The given entity must not be null!"
}
```
It's happening with refresh jHipster installation and MongoDB, hard to reproduce if you are running the application within 1 month because of refresh token expiration. So we can change a little from the configuration to reproduce the issue easily.

* **How to reproduce the problem:**
  * Reduce both access and refresh token validity seconds (for quick monitoring) to 10 and 20 seconds for example
  * Request to create new access token several times, every seconds for example
  * After around 20 seconds, cannot get new access token anymore with error : “The given entity must not be null”

* **Suggestion fix**
I gave the workaround here http://stackoverflow.com/questions/32370748/the-given-entity-must-not-be-null-error-when-calling-refresh-token-api-using-o however I think it could be fixed in better way.

**Comment by deepu105** [comment]
can you follow our guidelines https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-submission-guidelines

give  a proper description and title as well, I do not understand your issue

**Comment by ndkhoiits** [comment]
Hi @deepu105 , I changed the title and description, hopefully it's more clear now.

**Comment by deepu105** [comment]
ok now

**Comment by jdubois** [comment]
I added to OAuth2 to your title, as this is what is causing the issue, and that wasn't obvious.
Looks like you needed found an issue when the token needs to be refreshed -> could you do a PR with your fix? As you say there could be a better way, could you explain it?

**Comment by TajPelc** [comment]
I noticed the same problem today. ndkhoiits, your changed resolved the issue.
