### ISSUE TITLE
Transactionnal on protected method

### ISSUE THREAD

**Issue by alexandrepetrillo** [jhipster/generator-jhipster#2930]
In class CustomPersistentRememberMeServices, you set "@Transactionnal" on the public method processAutoLoginCookie.
My sonar say : "Non-public methods should not be "@Transactional""
And indeed , the TransactionnalInterceptor does not intercept this call.

Can you confirm, that this annotation is unsed ?

Thanks,
Best regards

**Comment by jdubois** [comment]
The annotation should not work on a protected method, so it can be safely removed.
However, Sonar is wrong, this would work if we were using AspectJ (which we are not, but Sonar doesn't know about it)
