### ISSUE TITLE
enable auto completion for jhipster cli commands

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2933]
Just to explore the possibility of doing a <TAB> completion for `yo jhipster` entries using something like below

https://github.com/0x00A/complete
or
https://github.com/f/omelette

Im not very sure on how to use this from a yeoman app

ping @0x00A @f guys, as you are the creator of these modules, do you think its feasible

**Comment by jdubois** [comment]
Omelette looks more popular, and it's used by the Azure Cli !
That would be a great improvement, I didn't know this was possible. Would this be cross-platform as well?

**Comment by deepu105** [comment]
Not sure I tried to do it in windows but doesnt seem to work so not sure if
im doing it rite or if its platform issue. Thats why posted as issue so
someone can try on linux/osx and see

**Comment by 0x00A** [comment]
Interesting. i didn't see omelette before, looks pretty cool tbqh :) I'd love to know how either of these work for windows users.

**Comment by deepu105** [comment]
@0x00A do you think complete can be used for a yeoman generator?

**Comment by deepu105** [comment]
I tried out based on your samples and doesnt seem to work on windows :(

**Comment by jdubois** [comment]
If it doesn't work on Windows we could just do it in a .zsh file, it would work well and I'd be very happy with it.
Yes I'm using oh-my-zsh

**Comment by 0x00A** [comment]
@deepu105 i don't use yeoman so im not sure what those use cases are. But it def does not have windows support at the moment. The way it works is by installing a script into your profile script (https://github.com/0x00A/complete/blob/master/lib/complete.js#L268), so it only works with bash/sh/fish/zsh, etc. I would be totally excited to get a PR for windows though ;)

**Comment by deepu105** [comment]
I use babun with oh my zsh as well so let me see if it works there

**Comment by jdubois** [comment]
OK, I lost a couple of hours on this:

- It's in fact quite stupid, it just adds the auto completion to your `.bash_profile` or `.zshrc`. So nothing magical, it just works as usual, and it's not portable.
- I tried to do it with Omelette, doing a specific "jhispter:autocompletion" sub-generator for that -> so it added a line to my `.zshrc` that broke my oh-my-zsh configuration. I could not log in to a console anymore!!! As this is done with their API, it looks like what they generate is not bug-free, and it can have some really bad results for our users. It's a risk I would not take.

I'm not sure it would be that helpful to have autocompletion, as most of the work is done in our question/answer prompts, so this looks to me to be a lot of trouble for not gaining much.

**Comment by jdubois** [comment]
I'm closing this as it's very low priority and can cause big issues, so let's not focus on this.

**Comment by deepu105** [comment]
yes you are right I lost couple of hours to find out that it doesnt work in
windows as well.
And you are right its too complicated compared to the value it gives so ya
lets not waste time on this.

Thanks & Regards,
Deepu
