### ISSUE TITLE
Entity type blob with MySQL DB only allows to store 65,535 bytes of data

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#2934]
Discussion started at the end of issue #1703

Solution is to set type to a database specific type in liquibase scripts. 
Blob type documentation for liquibase is found in this java source file

https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/datatype/core/BlobType.java

**Comment by ruddell** [comment]
I looked into this and the only database we need to change is MySQL from blob to longblob.  I tested H2 and longblob is automatically converted to blob so this is not an issue.

Database | Max Blob Size
------------ | -------------
Mongo (without GridFS) | 16 MB
PostgreSql | 1 GB
H2 | 2 GB
Cassandra | 2 GB
MySQL (longblob) | 4 GB
Oracle | 4 GB

**Comment by jdubois** [comment]
For Cassandra I would definitely not put more than 100mb in a line (so if you have 10 cells in a line, do the division!).
