### ISSUE TITLE
Missing imports of constants (heroku/index.js)

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#2936]
* **Overview of the issue**
The Heroku Generator throws a reference error stating SERVER_MAIN_SRC_DIR is not defined.  This is due to the recent change of using constants (#2923).

* **Motivation for or Use Case** 
I was testing Heroku deployment.

* **JHipster Version(s)** 
Master

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
`{
  "generator-jhipster": {
    "jhipsterVersion": "2.27.0",
    "baseName": "herokutest401",
    "packageName": "com.jruddell.test",
    "packageFolder": "com/jruddell/test",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "ac47156697ee413dd7d3fd9cfbb45c0f09ff0a48",
    "useSass": false,
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ]
  }
}
`
* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
No entities

* **Browsers and Operating System** 
All
* **Reproduce the error** 
run yo jhipster:heroku

* **Related issues** 
#2923 
* **Suggest a Fix** 
Add `SERVER_MAIN_SRC_DIR = constants.SERVER_MAIN_SRC_DIR;` under the constant imports in heroku/index.js:13

**Comment by deepu105** [comment]
Can you PR?

**Comment by ruddell** [comment]
@deepu105 It's already there #2937

**Comment by deepu105** [comment]
Ok thanks
