### ISSUE TITLE
jhipster fat jar with undertow does not work - 404

### ISSUE THREAD

**Issue by rksanket** [jhipster/generator-jhipster#2939]
**Version : The Latest.**

Overview of the Issue: 

I built a jhipster application. Added an entity. Built it with

`mvn -Pprod package`

Application runs fine with tomcat when I use `java -jar xyz.war`

But, since we need Undertow for high load scenarios, I simply change the maven dependency from Tomcat to Undertow in all the places (all the profiles) wherever tomcat starter dependency was mentioned as per the Spring documentation.

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-undertow</artifactId>
</dependency>
```
This runs fine when run from Eclipse and I can see the requests are now served by Undertow and not Tomcat as logs print XNIO as part of thread-ids.

But., when I again build it and try to run it with `java -jar xyz.war`,

Application boots up fine but when I hit the URLs

```
http://127.0.0.1:8081 
or http://127.0.0.1/xyz
```

it says URL not found.

What else do I need to do to put jHipster application with Undertow embedded to work? This issue does not seem to apply to any other 'Hello World' spring-boot apps that I tried but for only on a  jHipster app.

Any quick fixes, code changes etc that I can do on my app?

Here is my yo-rc, its a minimal app : 

```
{
  "generator-jhipster": {
    "baseName": "cfepoc4",
    "packageName": "com.ev.cfe",
    "packageFolder": "com/ev/cfe",
    "authenticationType": "xauth",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": false,
    "enableSocialSignIn": false,
    "rememberMeKey": "7692a9432e00e5005d8e5c926d67290a1346e70d",
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

**Comment by jdubois** [comment]
Please don't cross-post with Stackoverflow, seehttp://stackoverflow.com/questions/35506882/jhipster-executable-jar-with-undertow-does-not-work-404
I'm closing this as this isn't a bug, and stackoverflow is the right place for this.
