### ISSUE TITLE
How to debug 'Your request cannot be processed'?

### ISSUE THREAD

**Issue by qmar** [jhipster/generator-jhipster#2956]
I have a issue running JHipster. I've generated a base project and configured it to html5 clean-urls. I've configured a connection to postgres database. Now when I try to run it (spring-boot:run) in *prod* profile it starts succesfuly and gives me the adresses to access. The problem is that when I enter the address all I get is:

> Your request cannot be processed
> Sorry, an error has occurred.
> 
> Status: Not Found (Not Found)
> Message: No message available

How to debug it? Console is empty, I've tried to setup breakpoints in the code but I can't find any place where it is run. The output comes from the app, so it has to be running somehow. 

The network tab on chrome says: 404 Not Found, and returns the content of resources/templates/error.html.

**Comment by deepu105** [comment]
did you follow this https://jhipster.github.io/tips/010_tip_configuring_html_5_mode.html if not check it out.

Also please follow issue guidelines.

Im closing this as its not a jhipster bug, if you still have issues plz open a SO thread

**Comment by mistvan-perform** [comment]
How did you resolve this @marcinkunert please ? Did you try deploy onto heroku?

**Comment by marcinkunert** [comment]
@mistvan-perform I don't remember what was the reason. I'm no longer using it this way. Now my setup involves nginx which routes the traffic to node for SSR and backend. I've also never deployed it to heroku.
