### ISSUE TITLE
Production builds are broken on both master and v2.x_maintenance branches

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2960]
Our production build is broken, running `mvn -Pprod`:

- On the `v2.x_maintenance` branch, with all default options (which now use `gulp`by default), we are still in "dev" mode: the front end still has the "dev" banner (but is minified??) and the backend still uses H2. This follows a recent backport of code from the master (v3) branch from @atomfrede 
- On the `master` branch (v3 code), the server doesn't even starts and throws a Liquibase error. We also have MySQL warnings about SSL, that should be removed.

**Comment by deepu105** [comment]
how are the travis builds passing then :O

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
- For the front end -> those tests don't check the minified builds or the dev banner
- For Liquibase -> no idea!!

**Comment by pascalgrimaud** [comment]
@deepu105 : I never put the "curl" test on http://localhost:8080 so the build can be green even the app didn't start. I could put it but sometimes, travis didn't manage to start the app, so we'll have false failed build.

See my PR https://github.com/jhipster/generator-jhipster/pull/2950 and comments
There are some issues I tried to resolve this last weekend

**Comment by deepu105** [comment]
we should merge that asap

Thanks & Regards,
Deepu

**Comment by atomfrede** [comment]
Is the dev banner also visible on the master branch? I must admit I didn't noticed the banner, just looked for minified js and css in firebug.

**Comment by jdubois** [comment]
The master branch isn't starting because of the Liquibase issue, so I don't know

**Comment by atomfrede** [comment]
@jdubois I've fix the production build on v2.x-maintenance

**Comment by jdubois** [comment]
Great, thanks @atomfrede !! I'll test this and do the release tomorrow

**Comment by atomfrede** [comment]
@jdubois using ``gradlew -Pprod`` on master with psql works fine for me.

**Comment by jdubois** [comment]
Yes it's working fine in the v2x_maintenance branch thanks to @atomfrede 
But in the master branch we still have the Liquibase error -> can someone confirm this doing `mvn -Pprod`? This looks really strange, and as @deepu105 says why don't we see this in Travis?

**Comment by atomfrede** [comment]
I can't reproduce it:

* created a new project with psql (everything else default)
* startup the production docker container
* mvn -Pprod

-> everything works fine

**Comment by pascalgrimaud** [comment]
Same. I can't reproduce it, like Frede.
I tested it with mysql and psql
mvn -Pprod works fine for both, and no dev banner

**Comment by jdubois** [comment]
Argh it's just be being stupid! Lost 2 hours because I misconfigured my database!!!
But at least I had the pleasure to test the Docker Compose files by @pascalgrimaud -> that's really impressive!!
