### ISSUE TITLE
can we jhipster-hystrix dashboard with zuul / Ribbon proxies? May be it should be a separate thread....

### ISSUE THREAD

**Issue by dearnani** [jhipster/generator-jhipster#2961]
> Please follow the issue template below for bug reports and quiries.
> Bug reports or quiries opened without any of these info will be **closed** without any explanation.
> For feature requests, label the title with [FEATURE] and explain your use case and ideas clearly below, you can remove sections which are not relevant.

##### **Overview of the issue**
can we jhipster-hystrix dashboard with zuul / Ribbon proxies?

##### **Motivation for or Use Case** 
Gives effective fault tolerance mechansim

##### **Suggest a Fix** 
It is an enhanced feature for Microservices

**Comment by jdubois** [comment]
I don't really understand your issue, here...
If you're talking about JHipster 3.0, we already use Ribbon with Zuul.

**Comment by dearnani** [comment]
nice to hear about the Ribbon with zuul usge, well its not an issue, its a
feature - hystrix dasboard for micro services :)

On Mon, Feb 22, 2016 at 8:43 PM, Julien Dubois <notifications@github.com>
wrote:

> I don't really understand your issue, here...
> If you're talking about JHipster 3.0, we already use Ribbon with Zuul.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/2961#issuecomment-187224390>
> .
>



-- 
Thanks 'n Regards
@_sunkara
