### ISSUE TITLE
production not enabled in TOMCAT

### ISSUE THREAD

**Issue by muralihr** [jhipster/generator-jhipster#2962]
* *I have built the production WAR FIle and deployed in the TOMCAT , but production not enabled in TOMCAT.

*I have set the JAVA_OPTS in ubuntu 

  -Dspring.profiles.active=prod is enabled ;

* **Motivation for or Use Case** 
 
My production system is very slow - http://pondy.openrun.com:8080/heritageweb
* **JHipster Version(s)** 
NA

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

NA

* **Browsers and Operating System** 

NA
* **Reproduce the error** 

NA

* **Related issues** 

* **Suggest a Fix**

**Comment by gmarziou** [comment]
This is not a JHipster issue, please post on stackoverflow.
