### ISSUE TITLE
Entity with MySQL: length of foreign key

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#2964]
##### **Overview of the issue**

With MySQL, when using relationship with entities, there can be this error when starting the application:

```
liquibase.exception.DatabaseException: Identifier name 'fk_relationship_test_entity_user_many_to_many_entity_relationshiptestentity_id' is too long [Failed SQL: ALTER TABLE sampleMysql.relationship_test_entity_user_many_to_many_entity ADD CONSTRAINT fk_relationship_test_entity_user_many_to_many_entity_relationshiptestentity_id FOREIGN KEY (user_many_to_many_entitys_id) REFERENCES sampleMysql.jhi_user (id)]
```

It happens when the FK is too long (>64)

##### **JHipster Version(s)** 

Current

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "2.27.0",
    "baseName": "jhtest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "7f607ec58f29623b22e5c17ec3121d9a5490f703",
    "useSass": false,
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

Sorry, I removed them in current master, but I will put them back, as soon as this issue is resolved.
You can find them in this old branch :
https://github.com/pascalgrimaud/generator-jhipster/tree/check-installation-java8/travis/samples/app-default-from-scratch/.jhipster

It's Relationship*.json made by @andidev

##### **Suggest a Fix** 

https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml#L89

We can do the same as Oracle for MySQL.
But to avoid duplicate key, what about adding a random number after `fk` ?
Example: fk123_aaaaaaa_bbbbbbb

As soon as this issue is resolved, I will put back Relationship*.json entities to test with Travis.

**Comment by deepu105** [comment]
I thought MySQL doesnt have such restrictions

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
@pascalgrimaud I have fixed this can you check.I guess there might not be much of a duplicate key issue in real usage what do you think?

**Comment by pascalgrimaud** [comment]
Thanks @deepu105 : I will check it! But with your modifications, it will limit duplicate key

**Comment by pascalgrimaud** [comment]
I made some comments on your commit : https://github.com/jhipster/generator-jhipster/commit/0c89a18d999d2678ec9c7d7085328eaf931e85aa

But honestly, I spend a couple of hours on this, and there is no real solution to avoid duplicate keys with really long entities : https://github.com/pascalgrimaud/generator-jhipster/tree/check-installation-java8/travis/samples/app-default-from-scratch/.jhipster

So IMO, we should let this, and if the user have the problem, he can change directly his own xml files.

**Comment by deepu105** [comment]
Yes those would be very rare edge cases and we can just document that for
users to change manually
