### ISSUE TITLE
Choice of type of application

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2968]
The first question when running ```yo jhipster``` asks to choose between Monolithic and Microservice application.
I think that users that don't know or care about microservices should be guided with something like
```shell
❯ Monolithic application (pick this if you don't know what to choose)
```

**Comment by jdubois** [comment]
Yes -> note that this is documented that when you don't know what to choose, the default option is a safe bet.
But we need to have something more clear, as "monolithic" doesn't sound cool.

**Comment by gmarziou** [comment]
What about "classical JHipster application (recommended for simpler deployment)"?

**Comment by jdubois** [comment]
`Monolithic application (recommended for simple projects)`
And then we will need to document all this, anyway.

**Comment by deepu105** [comment]
We have a lot to document can you update this in the 3.0 documentation
ticket plz
