### ISSUE TITLE
JDL Studio doesn't generate .jdl file

### ISSUE THREAD

**Issue by fraf** [jhipster/generator-jhipster#2976]
##### **Overview of the issue**

URL : https://jhipster.github.io/jdl-studio/
Exported .jdl file is 0Ko

##### **Motivation for or Use Case** 

Try to export JDL (I don't know what it contains)

##### **JHipster Version(s)** 

Link from jhispter website release notes

##### **Browsers and Operating System** 

Chrome or Firefox @ Latest

**Comment by jdubois** [comment]
Yes I had the same issue yesterday cc @deepu105

**Comment by deepu105** [comment]
fixed via https://github.com/jhipster/jdl-studio/commit/d21417fbf8173a3551b68298b2a163049c480db8?diff=unified

Now you can do `ctrl + s` | `cmd + s` to save as .jh file
