### ISSUE TITLE
[Entity sub-generator] The "blob" type is broken

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2980]
This is for the `master` branch, I haven't checked the maintenance branch.

Using the entity sub-generator, creating a new blob (I tried "image" and "file"), the UI is broken: there is just a comma, and an upload button, but it doesn't seem to upload anything and the "view" and "edit" button just show the comma.

I am checking this as part as #2774 as I'm updating the Bower dependencies: there is a new major release of ng-file-upload but it's both broken with the old (10.0.2) and the new (12.0.1) releases.

**Comment by deepu105** [comment]
Ping @andidev

**Comment by andidev** [comment]
Is there any console error? I will have a look as soon as I have time though my todo list is growing a bit to fast so if somebody feels like looking at it feel free.

**Comment by ruddell** [comment]
No console error or message is displayed after choosing a file, just the comma remains (for image Blobs at least).
