### ISSUE TITLE
ErrorDTO constructors are package-private.

### ISSUE THREAD

**Issue by erikkemperman** [jhipster/generator-jhipster#2985]
##### **Overview of the issue**

`ErrorDTO` constructors are package-private.

##### **Motivation for or Use Case** 

We've separated the JHipster-generated classes from our own in terms of package structure, and now I'd like to expand the `ExceptionTranslator` functionality in a new class in our own package. Unfortunately I can't create `ErrorDTO` objects there, because their constructors are package-private. Likewise the `FieldErrorDTO` constructor.

##### **JHipster Version(s)** 

Current Master

##### **Suggest a Fix** 

I might be overlooking a valid reason for restricting access to these constructors... But if not, perhaps they could get a `public` or `protected` -- i.e., be usable from other packages?

**Comment by deepu105** [comment]
I dont see any reason for these to be package private @gzsombor since you coded this any comments plz?

**Comment by erikkemperman** [comment]
Thanks for quick reply @deepu105 ! I'm going to tentatively change this in my app's ErrorDTO for the moment, hoping that the next jhipster-upgrade will have this public/protected.

**Comment by deepu105** [comment]
if @gzsombor doesnt have any objection you can PR this :)

**Comment by erikkemperman** [comment]
It looks like there is a way to get to `ErrorDTO` indirectly, via the `CustomParameterizedException` class in the same package. That will also work for me in this case -- but sooner or later I'm going to just want to throw other exception classes and need something like this after all.

So for now I propose to wait gzsombor's reply patiently, if needed I will make a PR for this in due time?

**Comment by gzsombor** [comment]
There is no specific reason for it, it's just seemed enough in my experiences, to throw CustomParameterizedException - or subclass of it - and not thinking about the serialization / ui handling stuff, as it is handled by the provided exception translator.

**Comment by erikkemperman** [comment]
@gzsombor I think it would be required if one wants to return different http codes than just 400 Bad Request for particular exception type? If there is no objection I will make a PR shortly. Thanks for replying so quickly!

**Comment by erikkemperman** [comment]
PR merged, closing. Thanks guys!

**Comment by mraible** [comment]
Related to this, should we have exception handling for JWT errors like `BadCredentialsException` and `InternalAuthenticationServiceException` (which wraps `UserNotActivatedException`)?

https://groups.google.com/d/msg/jhipster-dev/_hCyebAamRc/Hc2wjluQFAAJ
