### ISSUE TITLE
John papa style for app run and config

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2986]
Since we are doing John papa style for angular I thought we should improve our `app.module.js` and `app.config.js` as per https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#startup-logic

today we have lot of config on the same file we can move all of them to separate files in a block folder and move the run block items to providers

if you guys are ok with this, ill change this. but this means any module which injects config blocks will not work as they would need to add a config file

**Comment by andidev** [comment]
+1

**Comment by deepu105** [comment]
@jhipster/developers anybody using the `addAngularJsConfig` or `addAngularJsInterceptor` method from the module subgen?

**Comment by deepu105** [comment]
I would like to remove `addAngularJsConfig` method and anyone using this currently would need to add the config in its own file to the `app/blocks` folder

**Comment by moifort** [comment]
I use config for material design, Google map, google analytics  module. 

Thibaut.

**Comment by deepu105** [comment]
@moifort will you be OK to change those into files?

**Comment by moifort** [comment]
Yes, don't worry I will do it! I wait the 3.0 release to update my modules. So no problem for me!

**Comment by atomfrede** [comment]
I guess every module adding somethings to the frontend should be updated to conform and work with the JH 3.0

**Comment by deepu105** [comment]
yes :)

Thanks & Regards,
Deepu
