### ISSUE TITLE
[Entities] Generate front-end code on the gateway, based on a microservice

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2987]
This is a JHipster 3.0 only feature, using microservices.

Here is the use case:

- The user generates a "Foo" entity on microservice "app1". This only generates the back-end code.
- Now the user wants to generate the corresponding front-end code on the gateway, that connects to the back-end code

This is in fact quite easy:

- We must re-use the `Foo.json` file from the "app1" microservice, and run it again on the gateway with the --skip-server flag

Now there are a few issues, running `yo jhipster:entity Foo --skip-server` on the gateway:

- How do we move around that `Foo.json` file, from the "app1" microservice? My proposal is to add a new question, asking where the file is (as the user may have cloned the "app1" repository anywhere on his filesystem). This question would be triggered by a new flag, for example (as you might want to create a "normal" entity on the gateway)
- How do we map the AngularJS service to the REST back-end? By default, it will be mapped on `app1/api/Foos` but we should ask for that in a new question (and in the gateway we don't know the `app1` prefix anyway)
- Currently running the above command fails -> it looks like the entity sub-generator isn't finished yet.

**Comment by PierreBesson** [comment]
>How do we map the AngularJS service to the REST back-end? By default, it will be mapped on app1/api/Foos but we should ask for that in a new question (and in the gateway we don't know the app1 prefix anyway)

I have an idea to automatically set that without asking questions, its not perfect but it would speed up the setup. To know the defined routes, we could query the local config server from the Yeoman generator using its REST API.
XML: [http://localhost:8761/config/gateway/prod/master](http://localhost:8761/config/gateway/prod/master)
JSON: [http://localhost:8761/config/master/gateway-prod.json](http://localhost:8761/config/master/gateway-prod.json)
YAML: [http://localhost:8761/config/master/gateway-prod.yml](http://localhost:8761/config/master/gateway-prod.yml)
Then write the zuul routes to a JSON file in `.jhipster`. If the routes have changed relaunch this sub-generator.

**Comment by deepu105** [comment]
We could also think of having a new sub generator for this which would
compose entity sub generator to do this

**Comment by cbornet** [comment]
Maybe the micro-services could expose their entitiy conf online so that it's easier to get it from the gateway ?
Eg : http://PATH_TO_MICRO_SERVICE/entities/Foo.json

**Comment by jdubois** [comment]
It could be a security issue... And you shouldn't need to have the whole infrastructure running to add an entity.

**Comment by cbornet** [comment]
I'm just saying this should be an option as it will be easier to get it that way if you have continuous delivery in place (which you should if you do micro-services).
Something like app1 back-end dev creates entity, commits -> CI/CD puts it online -> front-end dev generates it on the gateway angular app from the dev/staging env.
The front end dev shouldn't have to checkin app1

**Comment by PierreBesson** [comment]
@cbornet's idea sounds good. It will be similar of what should be done for the swagger docs (see #2954), available for dev but not for prod. Except instead of swagger-doc, this is hipster-doc.

**Comment by deepu105** [comment]
or we could simply have an option to save and read entity.json files to and
from an external location, by passing a param or something.
the option could be asked if microservice or gateway is selected as app type
"do you want to save entity configurations for this app to an external
path?"

if user says yes, we will ask for path and save it in the yo-rc file

we can build a subgen which will scan the given/configured path and will
list down available entity.json files and user can select one/many and
generate either a client or server files (could be automatic based on type
of application he is running the subgen from)

this way microservice teams can check in the config files in a central
location for all the apps and everyone can use it as well. and this will
not require any online services

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Well, that was basically my idea: just point to the directory where the
microservice is cloned, and you get the JSON file.
Simple, easy to do, nothing much to change.
Oh and it can only work for generating a client on the gateway, from a
microservice. And not the other way around.
Le 26 févr. 2016 5:02 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

> or we could simply have an option to save and read entity.json files to and
> from an external location, by passing a param or something.
> the option could be asked if microservice or gateway is selected as app
> type
> "do you want to save entity configurations for this app to an external
> path?"
>
> if user says yes, we will ask for path and save it in the yo-rc file
>
> we can build a subgen which will scan the given/configured path and will
> list down available entity.json files and user can select one/many and
> generate either a client or server files (could be automatic based on type
> of application he is running the subgen from)
>
> this way microservice teams can check in the config files in a central
> location for all the apps and everyone can use it as well. and this will
> not require any online services
>
> Thanks & Regards,
> Deepu
>
> On Fri, Feb 26, 2016 at 11:03 PM, Christophe Bornet <

**Comment by deepu105** [comment]
@jdubois if everyone agrees I can do this with an option to save and read json files to any folder the user wants. It can either be a question when microservice/gateway is choosen or can be a CLI parameter.


So if someone chooses microservice or gateway they will have additional question.
```
Where would you like to keep your entity configuration files? (Provide an absolute or relative path)

Default : ./.jhipster
```


or they can pass `--entity-config-path /usr/config`


This would be saved in the yo-rc file and whenever they generate an entity in a microservice the config gets saved here.

So when they run the entity generator from gateway with --skip-server they will generate based on existing json file.

I can also make a small utility sub generator which would scan and list all available entity jsons and users can choose one or many and generate them at a single go (this would be useful when they want to decide which entities to generate clinets for and stuff.)
Ofcourse it will compose entity sub gen to do the work.

**Comment by jdubois** [comment]
@deepu105 the issue is that different people working on the same project might want to store those .json files in different parts of their filesystem.
For me, the best solution is:

- .json files are generated using a microservice -> so we only have the back-end anyway. And this is stored in the usual .jhipster folder. Nothing changes here.
- when the user (or another user!) wants to generate the front-end (and please note there could be several gateways, if people want to follow the [BFF pattern](https://www.thoughtworks.com/insights/blog/bff-soundcloud) ), he gets a new question
- this question is only asked when you are on gateway
- the question is something like "If this entity was previously generated on a microservice application, please enter the path to that application, so we can re-use its configuration"
- The entity configuration is then copied from the microservice application to the gateway. It's a copy, because they can then have different lifecycles.
- A new field is added to the .json in the gateway, the "applicationId", so we know on which path the entity is mapped
- Then the front-end part of the entity is generated on the gateway, using the "applicationId" (so it points to "/app1/api/foos" and not "/api/foos")

**Comment by deepu105** [comment]
thats doable as well? do you want me to do it?

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Yes if you want to do it, please take the lead :-)
I'll probably have less time this week (working for a big JHipster client!)

**Comment by deepu105** [comment]
ok ill do this today

**Comment by PierreBesson** [comment]
@deepu105 Did you have time to make progress on this ? Otherwise @wmarques and me could give it a shot.

**Comment by deepu105** [comment]
Was bit held up, and need to prepare for Jhipster night here. please proceed if you have time :+1:

**Comment by PierreBesson** [comment]
OK, we will try to do it. Good luck for tonight :smile: !

**Comment by deepu105** [comment]
its not today its on 16th I have to prepare it this week as ill be bust
next week

Thanks & Regards,
Deepu

**Comment by andresfuentes** [comment]
Can anyone point me to a place where I can see how to start the client and server apps.. I am having problems when trying to start the client app. I am always gatting an error (400) and the server shows this message


[nio-8280-exec-8] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator

**Comment by jdubois** [comment]
@andresfuentes why are you commenting on a closed issue, and for another subject? Please follow the project guidelines...
