### ISSUE TITLE
Creating JHipster application does not render properly

### ISSUE THREAD

**Issue by Rapster** [jhipster/generator-jhipster#2993]
##### **Overview of the issue**

After creating a JHipster application, the rendering seems strange, like the CSS was not included but it is. However, looking at the Chrome console, it says:

> GET http://127.0.0.1:8080/api/account?cacheBuster=1456435856664 401 (Unauthorized)

##### **Motivation for or Use Case** 

I just follow steps to create JHipster application, I did not change anything and the rendering looks weird already.

##### **JHipster Version(s)** 

 2.27.1

##### **Browsers and Operating System** 

Windows 10

##### **Reproduce the error** 

Create simply an application. I'm working on a brand new laptop, I installed everything needed but I had to install python as well (not mentionned in the doc), but I have this strange error indicating that I have to install .net framework:

> I'm all done. Running npm install & bower install for you to install the required dependencies. If this fails, try running the command yourself.
> 
> 
> npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
> npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
> npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
> npm WARN prefer global marked@0.3.5 should be installed with -g
> npm WARN prefer global jshint@2.9.1 should be installed with -g
> npm WARN prefer global node-gyp@3.3.0 should be installed with -g
> 
> > bufferutil@1.2.1 install D:\Travail\Gifty\node_modules\bufferutil
> > node-gyp rebuild
> 
> 
> D:\Travail\Gifty\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
> MSBUILD : error MSB3428: Impossible de charger le composant Visual C++ "VCBuild.exe". Pour corriger le problème, vous d
> evez 1) installer le Kit de développement .NET Framework 2.0 SDK, 2) installer Microsoft Visual Studio 2005 ou 3) ajout
> er l'emplacement du composant au chemin d'accès système, s'il est installé ailleurs.  [D:\Travail\Gifty\node_modules\bu
> fferutil\build\binding.sln]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:100:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Windows_NT 10.0.10586
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd D:\Travail\Gifty\node_modules\bufferutil
> gyp ERR! node -v v5.7.0
> gyp ERR! node-gyp -v v3.2.1
> gyp ERR! not ok
> npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
> npm WARN install:bufferutil@1.2.1 Exit status 1

Shoud I really installed .net framework?

**Comment by jdubois** [comment]
- You have an error with your node.js setup in Windows -> not sure if you need the .NET framework, but this has been documented before on this bugtracker (I will take a look)
- Yes the 401 error is normal, this is also documented on this bugtracker (I'll let you have a look at this one, this is one is easy)

**Comment by jdubois** [comment]
For the .NET framework error: there are lots of stuff about this on stackoverflow, search for `msbuild.exe` and node.js
So it seems you need to install that: I can't test it as I don't have a Windows machine, but still this looks strange. At my current client I have a Windows 7 machine and it works without any issue (then maybe the .NET framework was already installed).
If you have trouble with this, use our "devbox", it's much easier to develop with it as everything is already set up for you.

**Comment by deepu105** [comment]
Normally the node gyp error is common in windows but shouldn't cause any
issues in running gulp or your app

**Comment by Rapster** [comment]
But it's hard to believe this .net framework issue is related to this result:

![image](https://cloud.githubusercontent.com/assets/7521311/13372584/906fbbcc-dd49-11e5-8054-5c1abb086dbd.png)

**Comment by gmarziou** [comment]
Does it render better when you run `grunt` or `gulp` with maven as explained in the doc?

http://jhipster.github.io/development/

**Comment by Rapster** [comment]
Using Gulp as recommanded by the installation prompt and documentation, it still does not work

**Comment by gmarziou** [comment]
Also which version of nodejs did you install? `node -v`

You should prefer LTS version rather than stable especially on Windows.

**Comment by Rapster** [comment]
I'm using 5.7.0, I just give it a try with LTS: same problem. Probably should I start over the whole process...

**Comment by gmarziou** [comment]
NodeJS on Windows is so much painful than on OSX and Linux.
If you re-install, consider doing it via a node manager like nodist to avoid installing it under a folder that require admin rights.

**Comment by gmarziou** [comment]
Look at my answer on SO:

http://stackoverflow.com/questions/34399362/node-js-issue-angular-is-not-defined-cannot-fined-bower-packages-nodegy/34400294#34400294

**Comment by gmarziou** [comment]
Also as Julien told you, best for you would be to use our devbox

**Comment by gmarziou** [comment]
Also pay attention to any log from npm, bower or gulp.

**Comment by gmarziou** [comment]
Post your .yo-rc.json file so that we know exactly the options you chose.

**Comment by deepu105** [comment]
Im on windows 10 and I dont have these issues and im using latest node as
well. this is really some environment setup issue with your machine

Thanks & Regards,
Deepu

**Comment by Rapster** [comment]
Still not working... I have this in my console each time I refres the page:

> [BS] Serving files from: src/main/webapp/
> Error: connect ECONNREFUSED 127.0.0.1:8080
>     at Object.exports._errnoException (util.js:870:11)
>     at exports._exceptionWithHostPort (util.js:893:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)

**Comment by gmarziou** [comment]
This is normal it means you started gulp (port 3000) but did not started maven spring-boot (port 8080).

**Comment by gmarziou** [comment]
OK so no error in command prompt when you ran npm install, bower install or gulp?
By the way I suppose your run a command prompt, a colleague of mine on Windows 10 had issues using git bash.

Again: Post your .yo-rc.json file so that we know exactly the options you chose.

**Comment by Rapster** [comment]
Yes I'm using Windows command promt. Here is the .yo-rc.json
[.yo-rc.txt](https://github.com/jhipster/generator-jhipster/files/149570/default.yo-rc.txt)

**Comment by gmarziou** [comment]
OK I reproduced the problem, it appears that CSS were not compiled by sass and so you did not have bootstrap stylesheets.
As a quick workaround you can execute `gulp sass` and then restart your app

**Comment by gmarziou** [comment]
sass task is correctly executed when running `gulp watch` but I may have a slightly different version of jhipster as I was running the HEAD in 2.x_maintenance branch.

There is #3000 which seems related.

Could you check your gulpfile.js at line 38, does it show:   ` scss: 'src/main/scss/'` ?

**Comment by Rapster** [comment]
Nop gulp sass didn't solve the problem, but you're right, there is something wrong with the config in gulpfile.js. Instead of` 'src/main/scss/' `I have this` 'src/main/webapp/scss/'`

Fixed by #3008 then

**Comment by gmarziou** [comment]
Yes you can just change to 'src/main/scss/' in gulpfile.js as in #3008 and run 'gulp sass'.
If it does not generate src/main/assets/styles/*.css files then something is wrong in your node sass installation and you should get an error in command prompt.

**Comment by Rapster** [comment]
I solved the problem by modifying gulpfile.js

**Comment by gmarziou** [comment]
Great.

**Comment by jdubois** [comment]
- The gulpfile is indeed now working with Sass, as the CSS is correctly re-generated after a change
- But BrowserSync doesn't pick up that change -> you need to reload you browser manually, even when running `gulp`, which correctly starts BrowserSync and shows the "connected" alert message

-> as BrowserSync isn't working correctly, I'm reopening this.

**Comment by atomfrede** [comment]
I will have a look. I guess browsersync watches the incorrect path.

**Comment by deepu105** [comment]
closed via #3033
