### ISSUE TITLE
[microservice] add an option with no database

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2999]
This is a JHipster 3.0 feature, only for "microservice application" type.

Add an option with no database

In the options, we would have:

    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",

In that case no database would be created, and this would launch much quicker for people who don't need a database.

Use cases are:

- People with specific or legacy back-ends (I see that all the time, for example to query an old COBOL system)
- Managing the JHipster Registry (which doesn't have a database and should still be a JHipster application)
- Doing microservices tests on limited machines (I'm trying to run those on 256m CloudFoundy instances, as they are cheaper)
- Doing performance tests when we don't want to test a third-party database

**Comment by gmarziou** [comment]
+1
It'll be useful also to build service aggregators
