### ISSUE TITLE
Sass file main.scss path is different than gulp scss config

### ISSUE THREAD

**Issue by gniewkos** [jhipster/generator-jhipster#3000]
* **Overview of the issue**

Missing styles after new project generation. Looks like SASS file is in the wrong place.

After clean project generation file main.scss is generate in 

`/src/main/scss/main.scss`

 while gulpfile.js has following path:

`scss: 'src/main/webapp/scss/'`

After moving main.scss to webapp/scss/main.scss everything works OK.

* **JHipster Version(s)** 

v2.27.1

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "baseName": "jhipsterapp",
    "packageName": "pl.ss.jhipsterapp",
    "packageFolder": "pl/ss/jhipsterapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "testFrameworks": []
  }
}

* **Browsers and Operating System** 

Latest Chrome, Windows 7

* **Suggest a Fix** 

Move template  [main.css](https://github.com/jhipster/generator-jhipster/blob/v2.27.1/app/templates/src/main/scss/main.scss) to webapp/scss.

**Comment by deepu105** [comment]
seems like an issue from the backport

Thanks & Regards,
Deepu

**Comment by atomfrede** [comment]
I can take a look.

**Comment by deepu105** [comment]
closed via #3008
