### ISSUE TITLE
Gulp + Gradle runs minify prod stuff on dev profile

### ISSUE THREAD

**Issue by thiagonuic** [jhipster/generator-jhipster#3006]
##### **Overview of the issue**

When I run "build > classes" on dev profile, gradle calls npm install, bower install and gulp build.

##### **Motivation for or Use Case** 

During dev mode there is no need to run gulp build since it is used only during war generation.

##### **JHipster Version(s)** 

2.27.1

##### **Browsers and Operating System** 

Windows, node 0.12.7, gradle using the wrapper provided.

##### **Reproduce the error** 

Just run gradle classes

##### **Suggest a Fix** 

Move "apply from: 'yeoman.gradle'" inside the "if (project.hasProperty('prod')) {"

**Comment by atomfrede** [comment]
Running npm and bower sound reasonable to me in order to make sure all frontend dependencies are available.

**Comment by jdubois** [comment]
Is that like 'mvn package'? I guess it works the same with Maven (and it
should!!!)
Le 26 févr. 2016 6:43 PM, "Frederik Hahne" <notifications@github.com> a
écrit :

**Comment by thiagonuic** [comment]
I think it is more like mvn compile.

**Comment by atomfrede** [comment]
compile does also process resources. Gulp runs when resources are processed, for generating constants and process scss files: ``processResources.dependsOn gulp_build``

**Comment by thiagonuic** [comment]
Another solution would be to allow "npm install" and "bower install" to run even on dev. But the assets compilation to run only on prod.

**Comment by deepu105** [comment]
this is not an issue its designed as such today

**Comment by Vaelyr** [comment]
I think the problem was misunderstood here.

When you run ./gradlew, it also runs the concat and minify tasks which are unnecessary in default dev build, because they are not used. My minify takes good 30 seconds and it's just wasted time on these gulp tasks. This shouldn't be. Grunt in the other hand works fine.

**Comment by deepu105** [comment]
You are right gulp build is not required for dev

**Comment by rodrigomaio** [comment]
Should this be reopened? I guess it's broken for everyone using last version + gulp + gradle, or did I miss something?

**Comment by deepu105** [comment]
What do you mean by its broken?

**Comment by rodrigomaio** [comment]
Creating a project (v2.27.2 + Gradle + Gulp) and running ./gradlew seems to build for prod, e.g. no development tag (upper left), does not show swagger API menu option...

**Comment by deepu105** [comment]
Can you open a new issue with proper details required using the issue
template
