### ISSUE TITLE
[Gateway] Reduce memory consumption by removing Cassandra by default

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3014]
This is a feature for JHipster 3.0 and the gateway.

Currently the gateway ships with the whole Cassandra libs inside it.

- Cassandra is used for the "rate limiting" feature, which is off by default
- But to have a smooth out-of-the-box experience, you can turn on an embedded Cassandra instance -> easy to use and test!

But I'm considering removing this:

- It's taking quite a lot of memory, even if we don't use it (and by default we don't!!!)
- For some reason (I profiled the application but couldn't find the reason), the embedded Cassandra is really slow (so the final experience is not that good anyway)
- Now we should run Cassandra in a Docker container, like in #2988 , and stop doing this kind of thing

**Comment by deepu105** [comment]
I would assume that people might use rate limiting as a production option and in that case should have a Cassandra instance setup anyway so if someone wants to try out in dev as well they would setup an instance I guess

**Comment by jdubois** [comment]
Yes it was only to help with the "dev" profile, but now that we have Docker everywhere this isn't useful anymore.

**Comment by jdubois** [comment]
I have removed the code (commit will be pushed in the next minutes), all it needs is the Docker compose configuration to have Cassandra running -> @PierreBesson as you have already done this for "normal" Cassandra apps, can you do it?

**Comment by PierreBesson** [comment]
OK. You are just asking me to add the correct dev.yml / prod.yml for the gateway ?

**Comment by jdubois** [comment]
Yes, can we have it in a specific Docker compose configuration, as it's optional? For both dev and prod.

Then the only issue is how to create the schema at startup, like what we have for MySQL -> is it possible to run a CQL script at startup? But this in a 2nd time.

**Comment by jdubois** [comment]
OK I've used the incredible configuration from @pascalgrimaud -> it works perfectly, I had nearly nothing to do!!!
