### ISSUE TITLE
jhipster 3.0 release date

### ISSUE THREAD

**Issue by xjiaoyang** [jhipster/generator-jhipster#3022]
Is it possible to estimate a generic timetable for the release?
**Thanks for all your hard work!!!**

**Comment by xjiaoyang** [comment]
i know all of you had already put a lot of time on JHipster 3.0, but i do not find any information about jhipster version 3.0 on the website, is there passible to add a page which will show any further work that is currently in progress? at least show what is done, problems you are working on,  information about architecture and design, etc

@jdubois what do you say?

**Comment by jdubois** [comment]
Release date should be in something like 1 month.
We haven't started documentation etc, and that will be our final work - we can't document before it's done :-)
If you want to track what's going on, follow:

- The JH3.0 tag on the bugtracker: https://github.com/jhipster/generator-jhipster/issues?q=is%3Aissue+is%3Aopen+label%3A%22JH+3.0%22
- The dev mailing list: https://groups.google.com/forum/?hl=en#!forum/jhipster-dev

There isn't anything more, those are the tools we use ourselves to work!

**Comment by xjiaoyang** [comment]
@jdubois :ok_hand
