### ISSUE TITLE
[FEATURE] browser-sync-angular-template

### ISSUE THREAD

**Issue by pvlastaridis** [jhipster/generator-jhipster#3023]
If this works, it will be great to be integrated

[browser-sync-angular-template](https://www.npmjs.com/package/browser-sync-angular-template)

**Comment by jdubois** [comment]
Indeed that looks like an incredibly good idea.

My main concern is that the project doesn't seem very active:

- Only 1 Github star
- The developer ( @pashaigood ) hasn't worked on the project for months

So for me, very unfortunately, that's a no-go.
Maybe there is another project doing the same thing, which is more active?

**Comment by jdubois** [comment]
I'm closing this as nobody answered, and I don't think we should rely on a project with such a low activity. I'd love to have this feature, of course, so if anybody has an alternative don't hesitate to open up a new ticket.
