### ISSUE TITLE
entityTranslationKey doesn't have suffix when using --angular-suffix

### ISSUE THREAD

**Issue by cicoub13** [jhipster/generator-jhipster#3024]
##### **Overview of the issue**

Navbar translation does'nt work for entities when using --angular-suffix (yo jhipster:entity Car --angular-suffix management).

##### **Motivation for or Use Case** 

Key in **global.json** is **car** and translate key is **global.menu.entities.carManagement**. Suffix is missing.

##### **JHipster Version(s)** 

master (2.27.0)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

`{
  "generator-jhipster": {
    "baseName": "test",
    "packageName": "fr.cyril",
    "packageFolder": "fr/cyril",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "blablabla",
    "testFrameworks": [
      "gatling"
    ],
    "jhipsterVersion": "2.27.0",
    "applicationType": "monolith",
    "jwtSecretKey": "blablabla"
  }
}`

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

Car.json

`{
    "relationships": [],
    "fields": [],
    "changelogDate": "20160122215107",
    "dto": "no",
    "service": "no",
    "pagination": "no"
}
`

##### **Browsers and Operating System** 

All browsers, all operating systems.

##### **Reproduce the error** 

Generate an app with .yo-rc.json.
Generate entity with `yo jhipster:entity Car --angular-suffix management`.
Launch app (with gulp for example).

##### **Suggest a Fix** 

I'll do a PR (https://github.com/jhipster/generator-jhipster/commit/11265ac3cb77483e5b4b5efacb6ee0d555202a99#commitcomment-16371437)

**Comment by deepu105** [comment]
Also the suffix needs to be saved to the `entity.json` file so that it can
be used for re generation as well

**Comment by cicoub13** [comment]
Done in PR :)

**Comment by deepu105** [comment]
Thanks
