### ISSUE TITLE
The problem when configuring and deploying the app

### ISSUE THREAD

**Issue by everping** [jhipster/generator-jhipster#3039]
I suffer the following error when deploying the app on Apache Tomcat/8.0.32:

`FAIL - Application at context path /myproject-0.0.1 could not be started
FAIL - Encountered exception org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/myproject-0.0.1]]`

However, all is ok when I run the app by the following command:
`java -jar myproject-0.0.1.war --spring.profiles.active=prod
`
But I can access file .htaccess from `http://localhost:8080/.htaccess`
Is this a security risk?

**Comment by deepu105** [comment]
You are not following our [submission guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md). Ideally I would close such tickets, Im leaving it open just for the security risk part you mentioned, can you plz update the ticket content as per our guideline?

**Comment by jdubois** [comment]
Yes you have 2 different issues:

- For the exception: no idea what you are doing, as you don't follow the submission guidelines (it you don't provide more information I will close it)
- Yes you are correct for the .htaccess. We inherit this from html5boilerplate, on which we are based, but most people using JHipster don't use Apache HTTP Server. So this isn't really a security issue, as it's not used, but I don't think we should keep that file -> I'll remove it in the `master` branch

**Comment by jdubois** [comment]
Oh and I didn't see the title of your ticket: sorry but I'm closing this, I just can't stand having those badly named tickets in my todo list -> please follow the guidelines, we even made a template to help you!
