### ISSUE TITLE
saveAccount REST API doesn't use JSR 303 validation rules on DTO Layer

### ISSUE THREAD

**Issue by gbrehmer** [jhipster/generator-jhipster#3042]
##### **Overview of the issue**

REST API for saveAccount throws internal errors in case of validation problems (produced by hibernate check of JSR 303 annotations)

##### **Motivation for or Use Case** 

AccountResource#saveAccount should have the same validation-rules applied to the given DTO like AccountResource#registerAccount (except password)

##### **JHipster Version(s)** 

2.27.0

##### **Reproduce the error** 

Using api/account with a REST Client & invalid POST body (e.g. missing values)

##### **Suggest a Fix** 

Use different DTOs for registration and changing account settings. Annotate POST Body Entity with @Valid annotation to enable JSR 303 validation rules.

**Comment by notflorian** [comment]
I don't think this is very efficient to have 2 DTO, one with password validation and one without.

Maybe we could remove the `@NotNull` and `@Size(min = PASSWORD_MIN_LENGTH, max = PASSWORD_MAX_LENGTH)` and validate the password explicitly in `AccountResource#registerAccount`.

An other solution could be in `AccountResource#saveAccount` to validate selectively the fields email, firstName, lastName and langKey, but I don't know how to do that. 
Maybe with the `@Validated` anotation like explained here : http://blog.codeleak.pl/2012/03/how-to-method-level-validation-in.html ?

Does anybody has a better idea to fix it?

**Comment by gbrehmer** [comment]
you do not have to duplicate the DTOs. It's possible to extract a field to an upper class like ManagedUserDTO.
It's also not efficient to have validation on several places, one by JSR 303 annotation, another by a manual check. And generated validation errors are different depending on API method .

**Comment by notflorian** [comment]
Do you think you could propose a PR to fix this? :)

**Comment by deepu105** [comment]
@gbrehmer would you consider doing a PR?

**Comment by gandrade** [comment]
PR #3242

**Comment by gandrade** [comment]
@deepu105 Just a heads-up, I've already finished the code changes. 

Thanks

Gustavo Andrade

**Comment by notflorian** [comment]
I finnally had some time to do more test on your PR, and I've written some comments.

Thanks ;)

**Comment by gandrade** [comment]
Don't worries @notflorian. I'll check your comments and as soon as I can, provide the changes. Thanks in advance!
