### ISSUE TITLE
Source in production profile 

### ISSUE THREAD

**Issue by dptinor** [jhipster/generator-jhipster#3044]
Hi.

By deploying the application, in production profile, i get these two folders.

![2016-03-01_100107](https://cloud.githubusercontent.com/assets/5374085/13430953/5f26276a-df95-11e5-9943-44f22ea7507b.png)

in the first folder, it is 'app-..js' and 'vendor-.js', which is normal. But in the second folder, I find the whole application, why?. I must configure something?

Using generator-jhipster 2.27.0

**Comment by atomfrede** [comment]
The generated war files contains also the source files so that is correct.

**Comment by gmarziou** [comment]
This has been discussed several times, search the issues for details

**Comment by deepu105** [comment]
This is normal for 2.x version this will change in 3.0

**Comment by dptinor** [comment]
ok, thanks to all.

**Comment by dptinor** [comment]
But then how do I remove it now?,in other discussions there are solution for this?. My Search not produce results.

**Comment by notflorian** [comment]
The PR linked to this subject is #2945, but it isn't merged yet into the master branch.

**Comment by dptinor** [comment]
@gmarziou We use Gradle and Gulp.

**Comment by gmarziou** [comment]
Well it should be similar in Gradle, just look at how to exclude files from war file when building it.
