### ISSUE TITLE
gulp serve fails when there is eslint error

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3052]
When there is an eslint error like say for example type a random text in any js file the gulp serve task fails and exits due to an error thrown by the `eslint-plugin-angular` seems like NPE I have raised a ticket in the plugin repo https://github.com/Gillespie59/eslint-plugin-angular/issues/363
```
D:\Projects\test\testApp\node_modules\eslint-plugin-angular\rules\utils\angular-rule.js:199
        if (node.type === 'FunctionExpression' || node.type === 'FunctionDeclaration') {
                ^

TypeError: Cannot read property 'type' of undefined
    at findFunctionByNode (D:\Projects\test\testApp\node_modules\eslint-plugin-angular\rules\utils\angular-rule.js:199:17)
    at checkCallee (D:\Projects\test\testApp\node_modules\eslint-plugin-angular\rules\utils\angular-rule.js:147:25)
```

cc @gmarziou @wmarques @erikkemperman any thoughts?

**Comment by deepu105** [comment]
I have [commented ](https://github.com/jhipster/generator-jhipster/commit/f7c95d156b349f7fd6cfd0af350f6ab7c99f07ea#diff-77f3296ef15494e769f9dbc2d73dcfa4R116)the `eslint` task from watch for now. We can enable back once we get this fixed

**Comment by gmarziou** [comment]
Personally, I think that having linting enabled on watch is annoying, it slows you down, I see linting more as a part of testing

**Comment by wmarques** [comment]
Agree with @gmarziou, I prefer run `gulp eslint` once I've finished editing all my files, for "live linting" we can use an eslint plugin in Atom.

**Comment by gmarziou** [comment]
Agree this is more a job for the editor/IDE.

**Comment by deepu105** [comment]
I kind of agree as well. but still this is an issue as it fails eslint on
whole when its ran. so may be lets remove eslint from watch for now

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
ok lets remove eslint from serve task for now
