### ISSUE TITLE
npm install from Gradle fails without local npm

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3053]
There were lot of people complaining that the production build was failing when npm install was running.

I was running production build on a fresh project and seems its indeed true.

the gradle node plugin tries to find a npm installation in the local path which will not be there and fails. Installing npm loaccly by `npm install npm` resolves this but I dont think its required to add npm at every projects node_modules folder.

This thread https://github.com/srs/gradle-node-plugin/issues/87 explains it and seems we have to set download flag true so that its downloads node and executes instead of trying to find it locally.

The bug report on the plugin is still open cc @atomfrede

**Comment by deepu105** [comment]
need to check how the mvn plugin behaves

**Comment by atomfrede** [comment]
You have tried on windows? I'm pretty sure I didn't do ``npm install npm`` on any project. Will try to reproduce it.

**Comment by deepu105** [comment]
may be its a bug only on windows

**Comment by atomfrede** [comment]
What have you done exactly?

* yo jhipster
* gradlew -Pprod -> error?

and 

* yo jhipster
* npm install npm
* gradlew -Pprod -> working fine?

**Comment by deepu105** [comment]
exactly

Thanks & Regards,
Deepu

**Comment by atomfrede** [comment]
Okay will check it today, but I'm pretty sure I never do ``npm install npm``

**Comment by ruddell** [comment]
I don't think this is an issue on Mac.  The project builds and runs successfully for me.  I don't normally use Gradle but the logs I see show the following in regards to npm:
> ruddell@MBP:~/Dev/Contrib/gradeletest$ ./gradlew -Pprod
> :bower
> :nodeSetup SKIPPED
> :npmSetup SKIPPED
> :npmInstall
> :gulp_build
> [11:26:43] Using gulpfile ~/Dev/Contrib/gradeletest/gulpfile.js

**Comment by atomfrede** [comment]
@deepu105 Looks like a windows problem. Created a fresh app, starting up the database via docker-compose and doing ``gradlew -Pprod`` executes gulp without any issues. Can you try the devbox?

**Comment by deepu105** [comment]
Yup seems so. lets close it here as we cannot do much about it. https://github.com/srs/gradle-node-plugin/issues/87 needs to be fixed to resolve this and until windows users may have to do `npm i npm` to get around it

**Comment by Ge94** [comment]
Hi, I am aware that this thread has been closed for ages, but this issue presented itself again on ubuntu 24.04. Installing npm beforehand with `apt install npm` did the trick.
