### ISSUE TITLE
creation mail should use separate text parts

### ISSUE THREAD

**Issue by gbrehmer** [jhipster/generator-jhipster#3057]
##### **Overview of the issue**
Creation mail template reuses activation mail text parts.

##### **JHipster Version(s)** 

2.27.0

##### **Suggest a Fix** 
creation mail text parts should describe password reset instead of clicking an activation link

**Comment by gmarziou** [comment]
I suppose you meant 2.27.0 rather than 2.7.0.
Would consider submitting a pull request? 

https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-a-pull-request

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/commit/d70fdf6809161a03478f997851dfa1841db2b380
