### ISSUE TITLE
Improvement: Gradle + JIRA issue tracker + Gitter chat channel

### ISSUE THREAD

**Issue by donhuvy** [jhipster/generator-jhipster#3063]
> 
> 
> 

##### **Overview of the issue**

This is really a feature, an improvement, not a but or defect. For improvement JHipster development life-cycle.

##### **Motivation for or Use Case** 

- Since Gradle build system is more powerful more than Maven, and Gradle support multi-programming languages, many complex build tasks.
- Gitter is good for team communicating and create community relations.
- JIRA is enterprise grade product for issue tracking, but free for open source project.

##### **JHipster Version(s)** 

many versions

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

N/A

##### **Browsers and Operating System** 

N/A

##### **Reproduce the error** 

N/A

##### **Related issues** 

N/A

##### **Suggest a Fix** 

1. Change build system from Maven to Gradle.
2. Create a Gitter chat channel on gitter.im
3. Migrate build-in Github issue tracker to JIRA bug tracker.
4. Improve reference document, let's see how Spring Framework [1] and Hibernate [2] create their reference docs.<br/>
[1] https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING-DOCUMENTATION.adoc <br/>
[2] https://github.com/hibernate/hibernate-orm/tree/master/documentation

**Comment by deepu105** [comment]
We already support both maven and gradle.
We already have a gitter channel https://gitter.im/jhipster/generator-jhipster

We dont have any plans to move to Jira at this point as github issues are convenient and sufficient
