### ISSUE TITLE
Separate changelogs for foreign key updates

### ISSUE THREAD

**Issue by lourai** [jhipster/generator-jhipster#3067]
##### **Overview of the issue**

The entity generator manage every entity changelog independently. So when you have many tables (i have 50, but depends your database layout), you get mass foreign key error from liquibase changelog as many tables doesn't existe while creating/updating the database.

I'm using jhispter-uml, but it's a jhipster issue as the generator must "know" that he is working on an entity list and not a single entity (see suggested fix bellow), nop ?

##### **JHipster Version(s)** 

JHipster 2.27, using jhipster-uml 1.6.1

##### **Suggest a Fix** 

When entity generator get a list of entity to build (from jhipster-uml), constraint management can be separated in a dedicated changelog file, last called by liquibase ?

**Comment by deepu105** [comment]
This is actually something i was thinking a while ago as well @jhipster/developers may be we can have a seperate changelog file which will have all the constraints changelogs injected. we could do with a needle during entity creation it would remove the need to have entity changelogs in correct order during liquibase table creations. what do you think?

**Comment by lourai** [comment]
Will work 100% and greatly offer suitable way to update existent projects !

I remember @jdubois talking avout update option now available in entity generator but didn't find it : how asking the generator in update mode ?

**Comment by deepu105** [comment]
it will be available in next release but actually you might not be able to
use it on current projects as next release is major with breaking changes

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Oh.
I haven't thought of this.
Looks like an excellent idea, and it would only work with our
sub-generator, not the Liquibase Maven goal.
I need some time to think of it, but at the moment it's +1000 from me!!
Le 7 mars 2016 7:55 AM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by andidev** [comment]
+1000 for me as well! This is  really annoying

**Comment by pascalgrimaud** [comment]
Good idea! :+1: too!

**Comment by deepu105** [comment]
I didnt think of the liquibase goal hmm will it cause issues?

**Comment by deepu105** [comment]
since this would be kind of a breaking change I would prefer to do it for 3.0 or not do at all for now

**Comment by lourai** [comment]
Go for it in 3.0, good !

Remember, if we really want to get confortable in update entity (and xx service base on) update process, we need to tricks every generated files to avoid custom code to be erased. Using abstract generated class/interface and empty not re-generated usable class/interface for exemple, but maybe you have better idea ?

By the way, i'll be happy to help on this one !

**Comment by deepu105** [comment]
you are welcome to do PR @lourai
