### ISSUE TITLE
Remove "spring.active.profiles" in the YAML files

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3069]
For application-dev.yml and application-prod.yml files, setting up the "spring.active.profiles" is probably useless (as we are already using that profile)
See: https://github.com/jhipster/generator-jhipster/blob/152a4421fe63cfbd2f45d78641680f8df9995bad/generators/server/templates/src/main/resources/config/_application-dev.yml#L29

**Comment by gmarziou** [comment]
The only place where it would make sense to me is in src/test/resources/application.yml if we wanted to force some profile.

**Comment by PierreBesson** [comment]
What was the initial reason to put those in the config ? Was it not handled the same in previous version of Spring Boot ?

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/commit/0963aac493072bc151ad0cca319799ae901d154b
