### ISSUE TITLE
Angular: disable debug info for production [FEATURE]

### ISSUE THREAD

**Issue by jbernach** [jhipster/generator-jhipster#3072]
In production profile, I suggest disabling debug info on AngularJS for a performance boost:

https://docs.angularjs.org/guide/production

It only needs a few lines during the module configuration:

myApp.config(['$compileProvider', function ($compileProvider) {
  $compileProvider.debugInfoEnabled(false);
}]);

**Comment by gmarziou** [comment]
Yes good idea it could be done by testing ENV value.

Would you consider submitting a pull request?

https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-a-pull-request

**Comment by jbernach** [comment]
I've cloned the repository and after some research, my confidence was little.

I'll try.

**Comment by jbernach** [comment]
Well, I don't know how to access $rootScope.ENV from inside the config block (it can't be inyected):

```javascript
angular
        .module('<%=angularAppName%>')
        .config(compileServiceConfig);

    compileServiceConfig.$inject = ['$compileProvider'];

    function compileServiceConfig($compileProvider) {
        // disable debug data on prod profile to improve performance
        if($rootScope.ENV == 'prod'){
            $compileProvider.debugInfoEnabled(false);
        }
    }
```
Any clue?

**Comment by gmarziou** [comment]
You should not need to use $rootScope to access ENV, you should just inject ENV and use it directly, it's a constant defined in `src/main/webapp/app/app.constants.js`

**Comment by gmarziou** [comment]
Thanks for your contribution
