### ISSUE TITLE
Pprod failure

### ISSUE THREAD

**Issue by dasss** [jhipster/generator-jhipster#3074]
> Please follow the issue template below for bug reports and quiries.
> Bug reports or quiries opened without any of these info will be **closed** without any explanation.
> For feature requests, label the title with [FEATURE] and explain your use case and ideas clearly below, you can remove sections which are not relevant.

##### **Overview of the issue**
Running "karma:unit" (karma) task
04 03 2016 11:00:26.561:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
04 03 2016 11:00:26.566:INFO [launcher]: Starting browser PhantomJS
04 03 2016 11:00:27.034:INFO [PhantomJS 1.9.8 (Windows 8 0.0.0)]: Connected on socket /#vuTF7gzEvc-jyDHKAAAA with id 16361090
Fatal error: The header content contains invalid characters
##### **Motivation for or Use Case** 
mvn -Pprod -e 
configure nothing except generate some entities.

##### **JHipster Version(s)** 

newest , downloaded last week.

**Comment by gmarziou** [comment]
Please provide requested details in issue template.
Which JHipster version: 2.x from npm or 3.0 from github master?
Post your .yo-rc.json file and node version.

**Comment by jdubois** [comment]
Yes, we need your exact config to understand what you did, I'm closing this as it's incomplete.
