### ISSUE TITLE
Update node and npm for travis builds

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3076]
We should update our node version and npm version to latest LTS versions for our travis build

may be we should also set `npm set progress=false` as it speeds up installs a bit

Node: ->  v4.3.2 I guess it will use NPM bundled with it

we might have to update the cache as well https://github.com/jhipster/jhipster-travis-build.git

cc @pascalgrimaud

**Comment by deepu105** [comment]
seems `2.14.22` is latest NPM LTS version

**Comment by deepu105** [comment]
@pascalgrimaud do we have to update the cache repo

**Comment by pascalgrimaud** [comment]
The cache repo is not mandatory, it's just to speed up the build.
I recently update this, so it should be good for now

**Comment by deepu105** [comment]
Ok
