### ISSUE TITLE
v2.27.1 (latest version) : no css anymore at front end in navigator

### ISSUE THREAD

**Issue by fraf** [jhipster/generator-jhipster#3080]
##### **Overview of the issue**
Missing the css web browing application out of the box in v2.27.1 generator (with gulpjs)
Was ok in version v2.27.0 of generator yet ! (with grunt)

##### **Motivation for or Use Case** 

Need to recode the navbar and all CSS ??

##### **JHipster Version(s)** 

Regression introduce in v2.27.1 compared to v2.27.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

npm update jhipster-generator (I was having the v2.27.0 installed)

->update ok

yo jhipster

->answer form questions the same, but choose gulpjs (recommended) instead of grunt

##### **Browsers and Operating System** 

IE9, FF 42

##### **Reproduce the error** 

generate a new application with v2.27.0 then update generator then generate a new application with v2.27.1 then run application.

**Comment by fraf** [comment]
![no_graphic](https://cloud.githubusercontent.com/assets/17450381/13530162/4ba48c44-e220-11e5-82c4-b0b17dac528d.jpg)

**Comment by jdubois** [comment]
Did you try `npm install` and `bower install`?

**Comment by fraf** [comment]
no. But normally the yeoman-maven-plugin do it when I simply do : 
mvn clean package
or
mvn spring-boot:run

**Comment by jdubois** [comment]
OK, but maybe you had some kind of network issue and didn't see it in your logs. Can you try the commands?

**Comment by fraf** [comment]
I found the bug :) : the faulty is gulpjs !
I regenerated the application with grunt like in v2.27.0 generator.
And then all is working fine like first time.

**Comment by deepu105** [comment]
i think its cox of some path issue we need to make  patch relese

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
related to https://github.com/jhipster/generator-jhipster/issues/2993
