### ISSUE TITLE
[FEATURE] Entity Search Component for Related objects

### ISSUE THREAD

**Issue by bytor99999** [jhipster/generator-jhipster#3083]
##### **Overview of the issue**

Currently on Many To One relationships the UI generates a nice drop down with the first page of data of the associated Entity type. However, as applications get more and more data, the drop down cannot include all the possible values. Typically, in an application you might have the drop down allow typing to do a search of possible values.

##### **Motivation for or Use Case** 

So in our admin application that we are using JHipster for, the users want to add a new record in an entity type that has a Many To One relationship to our Cases Entity. However, we have thousands of cases that they might need to choose one from. We obviously can't have a drop down with thousands of entries, so it would be nice to have a component we can set instead that will be like a drop down with search capabilities.

##### **JHipster Version(s)** 

JHipster Generator v2.27.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

inside our Entity json has

"relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "cases",
            "otherEntityName": "cases",
            "relationshipType": "many-to-one",
            "otherEntityField": "debtor_name"
        }
    ],

##### **Suggest a Fix** 

Another property in the "relationships" object in the array. Maybe "component": "search" would trigger the UI generation to use a new component that gets created. And if the property is not there use the current dropdown component.

Thanks

Mark S.

**Comment by deepu105** [comment]
We already include ui bootstrap which has an autocompletion component which you can easily use for this. Or you can use ui-select or something similar as well.

We will not be doing it as default at this point our hands are quite full already. If you want you can propose a PR and we will see if it can be integrated

**Comment by bytor99999** [comment]
Thanks. Now if I could get that working again. ;)

**Comment by deepu105** [comment]
But only if you could get the ui bootstrap directive working else we can't
add another dependency for this
