### ISSUE TITLE
Swagger UI missing with Gulp

### ISSUE THREAD

**Issue by rksanket** [jhipster/generator-jhipster#3089]
##### **Overview of the issue**

With gulp, swagger API UI does not show up.

##### **Motivation for or Use Case** 

We need swagger API to show up irrespective of gulp or grunt

##### **JHipster Version(s)** 

2.27.1 latest

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```

{
  "generator-jhipster": {
    "baseName": "cfepoc3",
    "packageName": "com.ev.cfe",
    "packageFolder": "com/ev/cfe",
    "authenticationType": "xauth",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": false,
    "enableSocialSignIn": false,
    "rememberMeKey": "2e369cb2f3b74c696615d2ef9d05ef38ef49b9a8",
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

##### **Browsers and Operating System** 

All browsers, Win7

##### **Reproduce the error** 
Step 1. build any app with Gulp, then use `java -jar app.war --spring.profiles.active=prod `
or 
`java -jar app.war`
Now, login to the application and there is no API section under Admin tab. 

Step 2 : Build any app with Grunt, then API section shows up. 

Is it a known and intentional thing?

![noswagger](https://cloud.githubusercontent.com/assets/14866614/13554653/8c12fcf2-e3d3-11e5-9eeb-4aa6e09f17d7.png)

**Comment by jdubois** [comment]
I see you are running with "prod" profile -> this is normal, by default Swagger is only available in "dev" profile, for security reasons (and this is documented somewhere!). You can remove the @Profile on the Swagger configuration so it works on both profiles.

**Comment by gpratte-tiy** [comment]
Which file is the Swagger configuration?

**Comment by PierreBesson** [comment]
@gpratte-tiy please don't comment on an old issue and use stackoverflow for support. Especially in this case as we have since added swagger ui support in prod through the 'swagger ' profile. Refer to the docs please.
