### ISSUE TITLE
Liquibase couldn't find changelogs

### ISSUE THREAD

**Issue by RGFnaGFuIEd1bmF5** [jhipster/generator-jhipster#3092]
When i change this "classpath:config/liquibase/changelog/.."  path into this "src/main/resources/config/liquibase/changelog/.." its running very well.

**Comment by deepu105** [comment]
@RGFnaGFuIEd1bmF5 please follow our issue [guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue). 
Im unable to make out what is your problem and what you are trying to do
