### ISSUE TITLE
docker-compose : refactoring file name

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#3094]
At the moment, the 2 docker-compose files to start database/elasticsearch are:
- `src/main/docker/dev.yml`
- `src/main/docker/prod.yml`

As we will add more docker-compose files in future, we should rename these 2 files to be clearer.
Can I suggest: `db.dev.yml` and `db.prod.yml`
But the prod file can only contain elasticsearch when using oracle, so maybe it's not a good idea

Same question for `registry.yml` ? Maybe `jhipster-registry.yml` ?

cc @atomfrede @cbornet @PierreBesson : because I know you use these files!

**Comment by deepu105** [comment]
Ill vote for a less confusing option for new users

Thanks & Regards,
Deepu

**Comment by atomfrede** [comment]
People using oracle are not beginners, so I guess using ``db.prod.yml`` even when it does not contain the database (when using orcale) is ok for me. I would prefix all containers provided by us with ``jhipster`` or ``jhi`` as you suggested.

**Comment by PierreBesson** [comment]
For the registry, we can call it jhipster-registry.yml as you suggest. It seems like an improvement.
I feel that this file is supposed to define the *dependencies* of an app, not restricted to database and elasticsearch. We can imagine it that in the future it might be used for many other things like a rabbitmq broker (needed in spring cloud bus, I have started to take a look at it...).
So I would call it something like `dependencies` or `extensions`. The name is not so important but it should be clear that this file must be started before you run the app.

I'm not too keen on prefixing the docker-compose with `jhi` as it is telling the user that he can't modify it if he wants and we should encourage them to tweak it to suit their needs. This is not valid for the registry as it is a standalone app that should not need tweaking.

**Comment by deepu105** [comment]
Ok I kind of like what @PierreBesson suggested so +1 for that

**Comment by pascalgrimaud** [comment]
Personaly, I don't care about name, because I use alias sh, to launch compose, instead of using : `docker-compose -f src/main/docker/...`. It's for our users, to not confuse them :-)

- `dev.yml` -> `db.dev.yml`
- `prod.yml` -> `db.prod.yml`
- `registry.yml` -> `registry-dependencies.yml` ? `registry-extensions.yml` ? Or `jhipster-registry.yml` because it's a JHipster project -> [jhipster-registry](https://hub.docker.com/r/jhipster/jhipster-registry/)

It will impact your [jhipster-microservices-docker project](https://github.com/PierreBesson/jhipster-microservices-docker), @PierreBesson, that's why we need to be all ok

**Comment by PierreBesson** [comment]
`jhipster-registry.yml` is good as it is a jhipster project. Don't worry about my side project, it is experimental for now. I would propose we go either with:
* `db.dev.yml` (not completely true but easier to understand for beginners)
* `dep.dev.yml`

**Comment by pascalgrimaud** [comment]
I don't understand the `dep.dev.yml` ?

**Comment by PierreBesson** [comment]
I meant "dependencies".

**Comment by pascalgrimaud** [comment]
yes but what is the origin file ?
**?** -> dep.dev.yml

**Comment by PierreBesson** [comment]
dev.yml -> dep.dev.yml

**Comment by jd-carroll** [comment]
Would it make sense (is it possible) to add a sub folder? That way there
could be a db sub folder and in that folder a dep.dev.yml and dep.prod.yml.

**Comment by pascalgrimaud** [comment]
it's possible to move to db sub folder, but we have to do same for all Cassandra folders...
Let's do simple:
- `dev.yml` -> `db.dev.yml` (I think `dep.dev.yml` is a little bit confuse)
- `prod.yml` -> `db.prod.yml`
- `registry.yml` -> `jhipster-registry.yml`

Are you all ok for this ?
@deepu105 too ? => because you will use Docker soon! :smile:

**Comment by PierreBesson** [comment]
Yes I'm OK with this. It's better than what we have now.

**Comment by deepu105** [comment]
Yup im ok, I have already started to use it :) its pretty cool though a
little rough in windows
