### ISSUE TITLE
Remove Jquery dependency

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3097]
Hello @jhipster/developers I have removed that last dependency on bootstrap js and used ui-bootstrap directives which means we now do not depend on bootstrap js (we were using it only of the navbar collapse and dropdown) here is the commit https://github.com/jhipster/generator-jhipster/commit/ecd57f12f14dfd0b2208b30a1be0564340c05f11

we had jquery as a dependency for bootstrap and since we do not use bootstrap js now we can actually remove jquery dependency or switch to a lighter one like zepto(we use jquery slectors in few of our directives which is supported by zepto as well) or can switch completely to use angulars jqlite alone

Some people might find jquery useful but it will lead to people abusing jquery for DOM manipulations and stuff which is against the angular philosophy what say?

**Comment by jdubois** [comment]
If it's not used, let's just remove it... It's trivial to add it back with Bower for people who have a need for it.

**Comment by erikkemperman** [comment]
Note; I think just removing jquery will not work, or in other words jqlite is not sufficient. Something like zepto will indeed be needed to do selectors -- or otherwise rewrite quite a few `angular.element` calls. I noticed this when upgrading wiredep recently; initially it reversed the order of jquery and angular includes and lots of things stopped working.

**Comment by deepu105** [comment]
yes zepto would be nice to have it has all that we need at < 2kb, Jquery on
the other hand is too much dead code actually

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
anybody against switching to Zepto?

**Comment by deepu105** [comment]
I think this requires more work then I thought and considering that using zepto will require some workarounds as well Im closing this
