### ISSUE TITLE
Test generation failure : regexp pattern constraint not taken into account in test generated code

### ISSUE THREAD

**Issue by fraf** [jhipster/generator-jhipster#3100]
To summarize :

When I generate the entity "typeFichier", having a field named "cdSens", the generated test file is named "TypeFichierResourceIntTest".
Its data members are generated like below :

```
 private static final String DEFAULT_FORMAT = "AAAAA";
    private static final String UPDATED_FORMAT = "BBBBB";
 **   private static final String DEFAULT_CD_SENS = "AAAAA";
    private static final String UPDATED_CD_SENS = "BBBBB";**
    private static final String DEFAULT_LIBELLE_FORMAT = "AAAAA";
    private static final String UPDATED_LIBELLE_FORMAT = "BBBBB";
    private static final String DEFAULT_TYPE = "AAAAA";
    private static final String UPDATED_TYPE = "BBBBB";
    private static final String DEFAULT_NIVEAU = "AAAAA";
    private static final String UPDATED_NIVEAU = "BBBBB";
```

That generated code is wrong ! Because I specified a regexp pattern restriction on field "cdSens" : ([U,D]).
Consequently, tests fails ! I can't package the webapp anymore.

Should be :

```
private static final String DEFAULT_FORMAT = "AAAAA";
    private static final String UPDATED_FORMAT = "BBBBB";
  **  private static final String DEFAULT_CD_SENS = "U";
    private static final String UPDATED_CD_SENS = "D";**
    private static final String DEFAULT_LIBELLE_FORMAT = "AAAAA";
    private static final String UPDATED_LIBELLE_FORMAT = "BBBBB";
    private static final String DEFAULT_TYPE = "AAAAA";
    private static final String UPDATED_TYPE = "BBBBB";
    private static final String DEFAULT_NIVEAU = "AAAAA";
    private static final String UPDATED_NIVEAU = "BBBBB";
```

EDIT : should we help the generator giving it a valid input to generate the code ?

**Comment by jdubois** [comment]
Yes it's a limitation when we generate entities with REGEXP.
It's documented here: http://jhipster.github.io/creating-an-entity/

I'm not happy with this limitation, but we have already worked on this for some time, and couldn't find any good solution, as we don't know what will match your regexp.

The solution, of course, is that you write the correct data that maps your regexp, and then the test will pass.
