### ISSUE TITLE
Add Gulp Inject to automatically inject js in index.html

### ISSUE THREAD

**Issue by moifort** [jhipster/generator-jhipster#3103]
I have implemented gulp-inject with gulp-angular-file to inject automatically (in a good order) new js files inside index.html and it's work well.

I will make a PR, but before, i want to know if it's a good idea to remove the functionality that add js inside index.html and let the gulp task to do the job?

**Comment by moifort** [comment]
Duplicate with #2889

**Comment by deepu105** [comment]
I would prefer the gulp task to do it, we might have to invoke the task after entity creation as well to add the js

**Comment by moifort** [comment]
So you agree?

I just make the test and it's work perfectly and remove 167 code lines  from generator. No more js injection to manage inside the generator.
