### ISSUE TITLE
Incorrect entity ID generation with PostgreSQL

### ISSUE THREAD

**Issue by ashakhov** [jhipster/generator-jhipster#3109]
##### **Overview of the issue**
ID generating annotation 
`@GeneratedValue(strategy = GenerationType.AUTO)`
 in Postgres is working as GenerationType.SEQUENCE. All entities are using the same sequence of ids, so if we have User, Book and Chapter entities, first of books will get id 1001. If we then create a Chapter, its id will be 1002, next one is 1003, next Book is 1004 etc.
Everything works OK if we change strategy to "GenerationType.IDENTITY" for each of our entities. Other solution is to change strategy to SEQUENCE and specify own sequences for entities like that:
```
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "users_seq_gen")
@SequenceGenerator(name = "users_seq_gen", sequenceName = "users_id_seq")
```
Both of the solutions work the same way.
##### **JHipster Version(s)** 

JHipster 2.27.1, jhipster-uml 1.6.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "baseName": "app",
    "packageName": "org.my.app",
    "packageFolder": "org/my/app",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": true,
    "rememberMeKey": "xxx",
    "testFrameworks": [
      "gatling"
    ]
  }
}
##### **Browsers and Operating System** 

Ubuntu 14.04.4 / 15.10, PostgreSQL 9.5

**Comment by deepu105** [comment]
It has same issue in Oracle as well

**Comment by cbornet** [comment]
Is this a problem ?

**Comment by jdubois** [comment]
I don't understand the issue, this is how Hibernate/JPA is working by default, and as per our [Policy 1](http://jhipster.github.io/policies/) we use their default configuration.
Besides, I personally think this is a good configuration, as long as you have the hilo algorithm (I need to check how this work here as this depends on the database implementation and the Hibernate version, but this should be OK).
So, what issue do you have here?

**Comment by deepu105** [comment]
I mean I haven't tried posgres but with Oracle I had this problem where all
the entities were using a single sequence (hibernate_sequence) for ID and
hence resulted in non continuous IDs within an entity means Ill have
scattered IDs. I tried changing strategies but it was all behaving the same
so I just gave up as it seemed like a hibernate or Oracle issue to me. I
wasn't showing the IDs to the end user as it wouldn't make sense to them so
it was not a serious issue for me. But for someone else it could be an issue

Thanks & Regards,
Deepu

**Comment by ashakhov** [comment]
It was a kind of _unexpected behaviour_. Generated applications meant to be database-agnostic, right? I haven't seen any generated database-specific code other than setting of field types in liquibase changesets. But they are not, it works one way with MySQL and another one with Oracle or Postgres. It does not affect data integrity, primary keys are correct, but it was strange that first created entity record is not really first and entity ids are not continuous.
And yes - in my case ids are visible to end users.
OK, maybe it is not so important to be changed in code, but I think that is still worth mentioning in the docs. At least users can wait for something like that and know how to deal with it.

**Comment by jdubois** [comment]
Well, as we are based on JPA, which is the Java standard, and as JPA works that way, the idea is that this *is* the expected behavior.
So yes the PK are scattered, but that shouldn't be an issue as they are just a technical key (another "good practice").
And I agree the JPA "best practice" can be strange to people who don't know how JPA works.

We can discuss a long time about what the "best practice" is, and what is the "most obvious", and what should be documented. That's why we have our [Policy 1](http://jhipster.github.io/policies/) -> we use JPA and follow JPA's "best practice", so that's supposed to be the "most obvious" choice (when you know JPA), and this is documented in the JPA spec (and not our documentation).
