### ISSUE TITLE
[FEATURE] Set server.port when generating micro service applications

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3114]
##### **Overview of the issue**

With micro services architecture, it's becoming annoying to generate applications that by default are configured on port 8081 for services.

With BFF pattern, it would not be unusual to have several gateways (e.g. one for angular app, one for mobiles). So, the same applies to port 8080 for gateways, 

Changing the port manually after generation is painful because you have to do it in several application-*.yml files, several docker yml files and also gulp/serve.js.

##### **JHipster Version(s)** 

3.0

##### **Suggest a Fix** 

Add a question for micro service applications and gateways.

**Comment by jdubois** [comment]
Another solution that needs testing: use port "0".
The application will then have a random port (from the available free ports).
And you will be able to find it through the registry.

**Comment by gmarziou** [comment]
Good point but unfortunately there are some issues like https://github.com/spring-cloud/spring-cloud-config/issues/93

**Comment by jdubois** [comment]
OK, then indeed that would be a new question in the generator, for gateways and microservices apps only.

**Comment by gmarziou** [comment]
Yes and also I don't know how random ports would work with Docker

**Comment by PierreBesson** [comment]
I guess for docker we can override the random port by passing a fixed port as command line arg and then expose this port.
For docker ports are not a problem as you can map a container port to any port on the host.

**Comment by gmarziou** [comment]
Yes but in this case, wouldn't you want to have random port on the host too?

**Comment by PierreBesson** [comment]
@gmarziou It seems `docker run -P` deals with attributing a random port on the host. For docker-compose, the [`ports`](https://docs.docker.com/compose/compose-file/#ports)option can attribute a random port on the host.
