### ISSUE TITLE
Camel cased app names are not correctly handled

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3117]
##### **Overview of the issue**

When generating an application with a camel cased name like `GatewayMobile`, the M capitalization is not used in several places resulting in names that do not follow their respective naming conventions

|  Object              | actual name     | expected name |
|  ------------------- |  ------------------- |   ------------------- | 
| maven artifact | gatewaymobile | gateway-mobile |
| spring boot main class | GatewaymobileApp.java  | GatewayMobileApp.java |
| angular app | gatewaymobileApp  | gatewayMobileApp |

**Comment by wmarques** [comment]
I'm working on this in [this branch](https://github.com/wmarques/generator-jhipster/tree/fix-camel-cased-apps).
