### ISSUE TITLE
Add sub generator to import JDL files

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3118]
This is to give an out of the box experience for our users. From GA stats seems like lot of people are using JDL studio already and providing a sub generator in the main jhipster generator will benefit more people to use JDL effectively and easily. 

Ill look at adding jhipster uml as a dependency and to invoke it with provided JDL file. May be we can add more features like pasting JDL directly on CLI to generate etc as well

@MathieuAA @CarlKlagba any comments

**Comment by MathieuAA** [comment]
None. Just ***patiently*** waiting for the dumped JSON files to be deprecated =)

I guess some work from JHipster should be expected...

@jdubois I'm considering moving the JDL DSL away from JHipster UML, and having a proper GitHub JHipster project for it.

**Comment by jdubois** [comment]
Yes the JDL could be a separate JHipster project.

Here it means people who install JHipster automatically have JHipster UML installed too, which can only be good in terms of usage of JHipster UML.

**Comment by CarlKlagba** [comment]
Having a sub generator for JDL would make JSON files more and more obsolete, wouldn't it? 
I am all for it.

**Comment by deepu105** [comment]
Yes having JDL as separate project would be better we can reuse it as a
dependency where needed. I can may be use it directly to parse in JDL
studio as well.

If JDL gets widely used may be one day we can drop the json files and have
all entitiy config in a .jh file

Ill start work on this soon

**Comment by jdubois** [comment]
Do you want me to create the project? What name should I use, "jhipster-domain-language"?

**Comment by MathieuAA** [comment]
Sounds nice. And it has JHipster in it.

**Comment by deepu105** [comment]
Yup it sounds good. Add me to that repo as well

**Comment by deepu105** [comment]
started here https://github.com/deepu105/generator-jhipster/tree/jdl/generators/import-jdl
waiting for the JDL project
