### ISSUE TITLE
Warnings about graceful-fs

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3126]
When creating a new app with JHipster 3.0, we have several warnings about `graceful-fs``

     graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible

Those look quite serious and should be solved before we release.

**Comment by deepu105** [comment]
Where are we using graceful fs?

**Comment by wmarques** [comment]
Seems that they are dependecies in Node internal module : http://stackoverflow.com/questions/35491905/npm-warn-deprecated-graceful-fs3-0-8-graceful-fs-version-3

**Comment by deepu105** [comment]
I did a project search and seems like we do not use it anywhere in our
code, then I dont know why we are declaring it in our package.json. Can we
remove it

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
@jdubois are using an older node version?

**Comment by wmarques** [comment]
I'm using 4.4.0 (LTS) and have same warning messages. By the way I also have an error that says "cannot find module 'gulp-angular-templatecache"

**Comment by deepu105** [comment]
I have removed the dependency from package json, but in node modules its downloaded again as its required by some other dependency 

Did some digging seems Mocha uses a glob version which depends on older graceful-fs they have corrected it https://github.com/mochajs/mocha/pull/2144 but havent release yet. SO im closing this
