### ISSUE TITLE
REST Api Call returns 406 instead of 400 for invalid passwords

### ISSUE THREAD

**Issue by gbrehmer** [jhipster/generator-jhipster#3127]
##### **Overview of the issue**

Calling api/account/change_password returns HTTP Status Code 406 in case of invalid password requests (instead of Bad Request 400).

##### **JHipster Version(s)** 

2.27.0

##### **Reproduce the error** 

Calling REST api with an invalid (e.g. too short) password

##### **Suggest a Fix** 

Change Produces-Annotation ContentType to TEXT_PLAIN

**Comment by cbornet** [comment]
Well, if we look at the code we see that we try to send a code HttpStatus.BAD_REQUEST with a text/plain content ("Incorrect password").

**Comment by gbrehmer** [comment]
Not acceptable status code is often bound to Accept/Content-Type Header use cases, e.g. if you set Accept-Header as client to text/plain and backend can only produce application/json Content-Type.

**Comment by gbrehmer** [comment]
btw it's the same for api/register. In case of validation errors, the ExceptionTranslator try to return a ErrorDTO, but register method only defines text/plain as possible content-type. I would say it's more a Spring MVC missing feature/bug, but currently you have to define both content-types (because complex type like ErrorDto can not be converted to text/plain automatically) and to add explicitly Content-Type header for text/plain responses in such a case.

**Comment by deepu105** [comment]
closed via #3158
