### ISSUE TITLE
Is one question missing in the app generator?

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#3132]
Hello!

##### **Overview of the issue**

There seems to be one question missing.

![image](http://i.imgur.com/CfYByHn.png)

Am I the only one having this issue?

Update, number 14 seems to be missing too. I guess that it's answer-dependent, and it might be why questions are missing... 

Update 2: is there a 17th question? 
![image2](http://i.imgur.com/9tYCR0j.png)

`node -v # v5.6.0` and `npm -v # 3.7.3`

**Comment by jdubois** [comment]
It's my fault: after asking for the app type, if you are doing a microservice, I added a question to ask for the server port.
So there's a "hidden" question here.
Not sure how we could solve this...

**Comment by MathieuAA** [comment]
So all the paths share a common set of questions, and answering differently could hide/display questions... 
Maybe making everything a bit more "dynamic" could help. I see [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-constants.js#L12) that there's 16 questions. And it's hardcoded, so everytime someone adds a question this number is incremented.
I don't know how you guys keep count of questions, they seem to be written in several files (last time I checked they weren't, ***last time***! Quite a while back).

As for the numerator, testing some things with the [currentQuestion index](https://github.com/jhipster/generator-jhipster/blob/master/generators/app/index.js#L18) could help us finding a way of solving the issue. There must be a "path" where `++currentQuestion` shouldn't be done.

**Comment by deepu105** [comment]
Im working on this will commit mostly today

**Comment by deepu105** [comment]
@jdubois I have fixed the order of questions and number sequence https://github.com/jhipster/generator-jhipster/commit/24dd708fe5c158cc8cce69db874382aea427f6c3

But the total questions will remain same irrespective and to get correct total questions I can try to do some hacky stuff but may not be worth the effort. Should we just show the current question number alone instead of showing `current/total`?

so

```
[ 1 ]  Which *type* of application would you like to create?
```

instead of 
```
(1/16) Which *type* of application would you like to create?
```

**Comment by deepu105** [comment]
closing this as reported issue is resolved
