### ISSUE TITLE
CSS fails to load at first launch with Gulp

### ISSUE THREAD

**Issue by jhhobbs** [jhipster/generator-jhipster#3133]
Just wanted to note a similar (or maybe the same issue) to [this issue](https://github.com/jhipster/generator-jhipster/issues/952), although I'm not using compass

CSS failed to load at first launch with Gulp. 

jhipster v. 2.27.2

OSX 10.10.5

```
{
  "generator-jhipster": {
    "baseName": "...",
    "packageName": "...",
    "packageFolder": "...",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": true,
    "rememberMeKey": "...",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ]
  }
}
```

I ran `gulp serve` and the css loaded.

Thanks for the awesome work!

**Comment by deepu105** [comment]
Are you sure you are running the latest version coz this was fixed in 2.27.2

**Comment by deepu105** [comment]
Did your app generation finished properly with `npm install`, `bower install` and `gulp install` running successfully?

**Comment by jhhobbs** [comment]
The application generation output says 'Welcome to the JHipster Generator v2.27.2'.  I looked for lines in the output that stated explicitly that `npm install`, `bower install` or `gulp install` was successful but did not see any.  I'm not getting any errors when running the generator and can attach the output if that would be helpful.  Thank you.

**Comment by deepu105** [comment]
I confirm this its coz the sass task is not run during initail install

You can run `gulp sass` to solve this for now, we will add sass task to the initial run

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/commit/f1362b12bc9eb3e8f74d1d02b45880d248343ebe
