### ISSUE TITLE
AbstractAuditEntity does not need to have @NotNull

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#3135]
##### **Overview of the issue**
Nowadays, AbstractAuditEntity has @NotNull annotation on its fields, also, the annotations to fill the fields with @CreatedBy, @CreatedDate, so on so forth. Those annotations make @NotNull unnecessary because it will fill the fields with the correct information every time.

Of course, on the database it can be forced to be not null, but in the domain @NotNull is irrelevant once it will not be null any time because of the other annotations mentioned above.

##### **Motivation for or Use Case** 
The motivation here is to use the module AuditEntity. I will open an issue on that module to change the AbstractAuditingDTO in order to change the @NotNull annotation to @ReadOnlyProperty. That way, the fields can be delivered but no need to fill once you do the post.

##### **JHipster Version(s)** 

2.27.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

Using DTOs

##### **Related issues** 

https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/21

##### **Suggest a Fix** 

No need to have @NotNull on AbstractAuditingEntity fields.

**Comment by deepu105** [comment]
@jdubois what is your opinion on this. I also find the @NotNull annotations annoying as it fails bean Validatios coz the data is filled by spring after bean validations

**Comment by jdubois** [comment]
yes it can be removed

**Comment by gandrade** [comment]
#3218

**Comment by deepu105** [comment]
Closed via #3218
