### ISSUE TITLE
Add cache replication configuration

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3137]
This is mostly for JHipster 3.0 with microservices, when you want to scale your nodes.

Currently ehcache only works in "standalone" mode, so if you scale your services you will get cache synchronization issues.

Please note we have the same issue with Hazelcast, but I'm focusing on ehcache here as it's the default cache, and it's what the vast majority of people use. Once this is done, we could open a similar ticket with Hazelcast.

What needs to be done, only for application type "microservice" (it might be interesting for other application types, but first we focus on the main issue):

- Add a distributed cache setting, [here is the documentation](http://www.ehcache.org/generated/2.10.1/html/ehc-all/#page/Ehcache_Documentation_Set%2Fco-use_supported_types.html%23wwconnect_header)
- According to [this site](http://stas-blogspot.blogspot.fr/2011/07/ehcache-replication-rmi-vs-jgroups.html) we should use RMI
- With the Eureka API, get the other instances of the same microservice, and add the current instance to the cluster. This would be a new configuration in the CacheConfiguration class. -> what would happen when a node disappears? Should we refresh this every few minute?
- Add the required configuration in the Docker Compose files, so that the RMI port is available on all instances, and they can join the same cluster

**Comment by deepu105** [comment]
@jdubois why do you think hazelcast has the issue? it is clustered by deafult and should work out of the box. I have done both ehcache and hazelcast and and Im happy with how hazelcast works in clusters compared to ehcache which is not realtime sync, I have tried the ehcache synchronization and it wasnt that great. For micro services I would suggest making hazelcast as the cache option as it would auto discover and cluster out of the box

**Comment by deepu105** [comment]
Also doing with hazelcast would be much easier as normally it will autodiscover if the same application is found in the network and we can even restrict that by IP with a single line in yaml

**Comment by jdubois** [comment]
Oh, if that's a lot simpler with Hazelcast we can start with it, and make it the default for microservices... Let's do a first test with Hazelcast before.

**Comment by deepu105** [comment]
Actually hazelcast will make more sense for microservices, Our default hazelcast config worked for me with an app running on 4 nodes on the same network.

The only issue I had was when I ran dev and staging app on same network as they joined clusters due to auto discovery so I just added a IP whitelisting config to hazelcast in cache config.

may be I can add the same config, its few lines, to our microservices as well if required

**Comment by jdubois** [comment]
Oh if you already know the config, and even have it running in prod, can you do this?
I'll rename the ticket accordingly!

**Comment by deepu105** [comment]
Yup ill give it a try

**Comment by jdubois** [comment]
Thanks @noctarius who pointed me to exactly what I want with Hazelcast - [here is the code](https://github.com/hazelcast-incubator/eurekast/blob/master/src/main/java/org/hazelcast/discovery/eurekast/EurekaDiscoveryStrategy.java).

So the idea is that:

- Hazelcast is used as our 2nd level cache, like normally with JHipster
- But when we scale our service, for example using `docker-compose scale`, new instances are registered in Eureka
- This new code makes those new instances automatically join the cluster

This wouldn't use multi-cast, and would use our "normal" Eureka registry, so this would work much better with our current architecture.

@noctarius can you help us with that code? We would make Hazelcast our default cache for microservices, of course.

**Comment by noctarius** [comment]
Eureka discovery doesn't work yet, trying to build it based on Eureka 2 (RC2), anyhow the examples seem to be outdated (from master) - still fighting :)

If anybody has experience with Eureka 1 I'm happy to do a discovery plugin based on the older version as well. Generally speaking, building a discovery plugin based on Hazelcast 3.6, it basically is 3 classes and you're done.

Happy to help out on integrating Hazelcast seamlessly here. Maybe it makes sense to use JCache as the general abstraction between JHipster and Hazelcast / EHcache - maybe there's another abstraction already in place - not very knowledgable about the internal design, sorry :D

**Comment by jdubois** [comment]
- Yes we got good experience with Eureka 1, our whole JHipster 3.0 microservices architecture is built around it! We will of course migrate to Eureka 2 when it's production-ready.
- For this kind of project, we usually do our own classes, that we generate for our users. If that's successful and the 3rd-party project is happy with it, we then try to contribute it back to the project: that's how our Cassandra integration became Spring Boot's Cassandra integration. Hopefully we can do the same here.

**Comment by jdubois** [comment]
Guys, I've got something running which is much, much simpler :-)
@deepu105 have you started working on it? Otherwise just wait a little bit until my code is ready, I'll commit it directly

**Comment by deepu105** [comment]
Nope I haven't started yet. Plz do even I was wondering why it wouldn't
work simply out of the box using the default discovery mechanism

**Comment by jdubois** [comment]
I got the cluster running, and it looks all easy & simple, but my entities are not in sync between my cluster nodes.
As the cluster looks fine I'm wondering if we don't have another, older issue. Do you have this working fine in multicast ?

**Comment by deepu105** [comment]
Yes I didn't have any issues reported in my prod apps so far

**Comment by jdubois** [comment]
OK I got it working locally (on "localhost"). I'm pretty confident my configuration is also good with a real cluster, and I'm committing it as tomorrow I'll have a full cluster to test this :-)
So we should know quickly if it works in all situations!

**Comment by deepu105** [comment]
Ill test it as well, im gonna do a microservice demo day after tomorrow as
well

**Comment by deepu105** [comment]
Thats very similar to what i did to restrict IPs except I knew the ip so
had them in yml beforehand

**Comment by deepu105** [comment]
I have made hazelcast default when choosing gateway or microservice

**Comment by noctarius** [comment]
Does anybody wants to give this one a shot: https://github.com/hazelcast-incubator/eurekast-one

Simple test is working but I guess you guys know way more about eureka than I do :)
