### ISSUE TITLE
BrowserSync proxy configuration for all APIs

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3138]
I am modifying this because of the Gateway in JHipster 3.0.

-> I'm going to do this right away, this ticket is to document the change and discuss it, as it's quite ugly, and maybe find a better solution afterwards

The issue with BrowserSync and the gateway is that we add microservices on-the-fly. So BrowserSync doesn't know about those new services, and can't forward API requests to them -> that makes all API calls to microservices fail.

The solution, for the moment, is to put the proxy on "/", that is on all requests:

- Yes, that's ugly
- That means that even HTML/CSS/JS which are local are sent to the proxy
- But everything works with this set up: when an HTML file is changed, the browser is refreshed, and instead of reading it on the filesystem it reads it from the proxy

**Comment by gmarziou** [comment]
This could be a good reason for prefixing proxified services with /api on gateway.

**Comment by jdubois** [comment]
Ah yes you are correct! I'll first do the `/management` part, that's my next task this afternoon...
