### ISSUE TITLE
AWS war upload times out after 2 minutes

### ISSUE THREAD

**Issue by dscowan** [jhipster/generator-jhipster#3148]
JHipster v 2.27.2

During the upload of the war the default AWS s3 timeout of 2 minutes is hit if on a slow connection.  modified s3.js to add httpOptions timeout

          var s3 = new this.Aws.S3({
                params: {
                    Bucket: bucket,
                    Key: warKey
                },
                signatureVersion: 'v4',
                **httpOptions: {timeout: 600000}**
            });

It would be nice if this was configurable or set higher for a default

**Comment by deepu105** [comment]
ping @wuethrich44

**Comment by wuethrich44** [comment]
I run into timeout issues too, so if this option fix that issue then it would be nice if you could provide a PR.

**Comment by sendilkumarn** [comment]
This should be more project specific. This option is available as optional in their SDK. I don't think we have to add this.

**Comment by wuethrich44** [comment]
I think for users with slow internet connection this option is quite useful and other user have to wait a little bit longer if there is no internet connection. So I would add this.

@dscowan Could you provide a PR?

**Comment by deepu105** [comment]
close via #3232

**Comment by seghers** [comment]
I think an ending "," is needed ..?

**Comment by deepu105** [comment]
@seghers thanks for pointing it out. Its corrected

**Comment by seghers** [comment]
You're fast, was making a request, Please ignore it.
