### ISSUE TITLE
Allow to easily set the maximumPoolSize in Hikari

### ISSUE THREAD

**Issue by henri-tremblay** [jhipster/generator-jhipster#3150]
##### **Overview of the issue**

Hikari allows to set many properties in `HikariConfig`. For instance the maximumPoolSize. However, the  current usage of the `DataSourceBuilder` and the fact that the `JHipsterProperties` are not passed anymore to the `dataSource()` method makes this almost impossible.

There are only two solutions for someone using a generated application:
1. Change the code pass JHipsterProperties and set the value to the new datasource

```java
    public DataSource dataSource(DataSourceProperties dataSourceProperties, JHipsterProperties jHipsterProperties) {
        // [...]
        HikariDataSource hikariDataSource =  (HikariDataSource) DataSourceBuilder
                .create(dataSourceProperties.getClassLoader())
                .type(HikariDataSource.class)
                .driverClassName(dataSourceProperties.getDriverClassName())
                .url(dataSourceProperties.getUrl())
                .username(dataSourceProperties.getUsername())
                .password(dataSourceProperties.getPassword())
                .build();             hikariDataSource.setMaximumPoolSize(jHipsterProperties.getDatasource().getMaximumPoolSize());
        // [...]
    }
```
2. Set a system property containing a file (-Dhikaricp.configurationFile=the_specific_file.properties)

Both are not obvious.

Also, I might have missed something but I don't see how the specific MySQL optimizations (`cachePrepStmts` and others) are set. They are in the `HerokuDatabaseConfiguration` but not in `DatabaseConfiguration`.

##### **Motivation for or Use Case** 

I would like to provide a pull request giving a pool size of 10 in dev and 200 in prod. With a basic CRUD REST API, 200 matches the number of threads. Benchmarks quickly prove the DB pool to be the bottleneck.

But I don't want to change everything and get a refused pull request. Also, remember that `cachePrepStmts` doesn't seem to be set like it use to.

So, do you acknowledge that it is meaningful. If yes, I will provide a pull request that sets the max pool size. It can then be used to set any other property in `HikariConfig`

##### **JHipster Version(s)** 

Master head 2016-03-13

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```json
{
  "generator-jhipster": {
    "jhipsterVersion": "2.27.0",
    "baseName": "hello",
    "packageName": "pro.tremblay.hello",
    "packageFolder": "pro/tremblay/hello",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
```

##### **Suggest a Fix** 

I can provide a pull request to fix it.

**Comment by deepu105** [comment]
ping @cbornet

**Comment by cbornet** [comment]
With the new datasource configuration that should just be setting "spring.datasource.hikari.maximum-pool-size" property in application-dev.yml.

**Comment by deepu105** [comment]
@henri-tremblay plz refer reply from @cbornet
