### ISSUE TITLE
add profile switches to disable swagger, cache, liquibase

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3151]
Based on discussion https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/jhipster-dev/Jeh8bYV_sdM

**Comment by jdubois** [comment]
Closing this as the PR is merged

**Comment by deepu105** [comment]
i havent added the no-cache yet but its ok

Thanks & Regards,
Deepu
