### ISSUE TITLE
sorry! plz help me fix bug jpaRopository with @Query anotation.

### ISSUE THREAD

**Issue by dienlh** [jhipster/generator-jhipster#3152]
Query : select customer from Customer customer where (?1 ='' or ?1 is null or customer.ic_passport_number like %?1%).
Page<Customer> findAllByIcPassportNumber(Pageable pageable,String ic_passport_number);
i can't get all data like %?1% but using Mysql, with this query i can get all data with like %?1%

**Comment by gmarziou** [comment]
Closing as you did not follow our guidelines

**Comment by gmarziou** [comment]
https://jhipster.github.io/help/
