### ISSUE TITLE
[Internal] remove underscore string and use lodash

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3153]
Lodash has most of the string methods we use https://lodash.com/docs#camelCase

we can may be remove the underscore.string dependency and use lodash alone.

@jdubois I guess underscore was added by you any specific reason?

**Comment by jdubois** [comment]
It's only there for historic reasons -> yes +1 to remove it

**Comment by wmarques** [comment]
+1 for me too

**Comment by deepu105** [comment]
@wmarques im bit held up do you wanna try this?

**Comment by sendilkumarn** [comment]
#3163 Please check and merge if it is okay.

**Comment by sendilkumarn** [comment]
#3163  is ready for merge. Please check.

**Comment by deepu105** [comment]
closed via #3163 @sendilkumarn add the fix #issuenumber for autoclose next time
