### ISSUE TITLE
[SUGGESTION] greenkeeper

### ISSUE THREAD

**Issue by thiagogcm** [jhipster/generator-jhipster#3159]
Sorry if this isn't the right place for it.
Have u guys already considered https://greenkeeper.io/ to keep npm dependencies up to date?

**Comment by deepu105** [comment]
We already use david-dm to track dependency but there is no automation. Im
not sure if we need to automate that as it could cause many issues

**Comment by thiagogcm** [comment]
It creates a new branch for the commit. You still can wait travis and merge manually. See this example from openlayers repo: https://github.com/openlayers/ol3/pull/4975

**Comment by deepu105** [comment]
@jhipster/developers what do you think?

**Comment by jdubois** [comment]
I'm also using VersionEye -> https://www.versioneye.com/user/projects/52a77778632baca59e000003#tab-dependencies

There are just too many tools here!

**Comment by jdubois** [comment]
OK not many comments here: thanks for pointing this @thiagogcm as it might be handy in the future, but we've already have enough tools for the moment

**Comment by thiagogcm** [comment]
No hassle! When I saw this I thought it could be useful, not to just keep track but to automate this task. But I agree that are too many tools to manage.
