### ISSUE TITLE
Dropdown menu not working in 2.27.2

### ISSUE THREAD

**Issue by causevic** [jhipster/generator-jhipster#3160]
**Issue:** When clicking on navbar menus after jhipster generates app, nothing happens.
**Expected:** Menu items should be displayed. 

This is the case for non-authenticated (Language), as well as authenticated menu items (Entities, Administration, Account).

The issue is that the src/main/webapp/index.html includes bootstrap twice, see below:

```
<!-- build:js scripts/vendor.js -->
        <!-- bower:js -->
        <script src="bower_components/jquery/dist/jquery.js"></script>
        <script src="bower_components/angular/angular.js"></script>
        <script src="bower_components/angular-aria/angular-aria.js"></script>
        <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
        <script src="bower_components/angular-cache-buster/angular-cache-buster.js"></script>
        <script src="bower_components/angular-cookies/angular-cookies.js"></script>
        <script src="bower_components/angular-dynamic-locale/src/tmhDynamicLocale.js"></script>
        <script src="bower_components/angular-local-storage/dist/angular-local-storage.js"></script>
        <script src="bower_components/angular-loading-bar/build/loading-bar.js"></script>
        <script src="bower_components/angular-resource/angular-resource.js"></script>
        <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
        <script src="bower_components/angular-translate/angular-translate.js"></script>
        <script src="bower_components/messageformat/messageformat.js"></script>
        <script src="bower_components/angular-translate-interpolation-messageformat/angular-translate-interpolation-messageformat.js"></script>
        <script src="bower_components/angular-translate-loader-partial/angular-translate-loader-partial.js"></script>
        <script src="bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.js"></script>
        <script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
        <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
        <script src="bower_components/json3/lib/json3.js"></script>
        <script src="bower_components/ng-file-upload/ng-file-upload.js"></script>
        <script src="bower_components/ngInfiniteScroll/build/ng-infinite-scroll.js"></script>
        <script src="bower_components/sockjs-client/dist/sockjs.js"></script>
        <script src="bower_components/stomp-websocket/lib/stomp.min.js"></script>
       <script src="bower_components/bootstrap-sass/assets/javascripts/bootstrap.js"></script>
      <script src="bower_components/bootstrap-material-design/dist/js/material.js"></script>
        <script src="bower_components/bootstrap-material-design/dist/js/ripples.js"></script>
        <!-- endbower -->
        <!-- endbuild -->


```

Here's my bower.json:

{
  "name": "21points",
  "version": "0.0.0",
  "appPath": "src/main/webapp",
  "testPath": "src/test/javascript/spec",
  "dependencies": {
    "angular": "1.4.8",
    "angular-aria": "1.4.8",
    "angular-bootstrap": "0.14.3",
    "angular-cache-buster": "0.4.3",
    "angular-cookies": "1.4.8",
    "angular-dynamic-locale": "0.1.28",
    "angular-i18n": "1.4.8",
    "angular-local-storage": "0.2.3",
    "angular-loading-bar": "0.8.0",
    "angular-resource": "1.4.8",
    "angular-sanitize": "1.4.8",
    "angular-translate": "2.8.1",
    "angular-translate-interpolation-messageformat": "2.8.1",
    "angular-translate-loader-partial": "2.8.1",
    "angular-translate-storage-cookie": "2.8.1",
    "angular-ui-router": "0.2.15",
    "bootstrap": "3.3.5",
    "jquery": "2.1.4",
    "json3": "3.3.2",
    "modernizr": "3.2.0",
    "ng-file-upload": "10.0.2",
    "ngInfiniteScroll": "1.2.1",
    "sockjs-client": "1.0.3",
    "stomp-websocket": "2.3.4",
    "swagger-ui": "2.1.3",
    "bootstrap-material-design": "^0.5.9"
  },
  "devDependencies": {
    "angular-mocks": "1.4.8",
    "angular-scenario": "1.4.8"
  },
  "overrides": {
    "bootstrap": {
      "main": [
               "dist/js/bootstrap.js",
        "dist/css/bootstrap.css",
        "less/bootstrap.less"
      ]
    }
  },
  "resolutions": {
    "angular": "1.4.8",
    "angular-cookies": "1.4.8",
    "jquery": "2.1.4"
  }
}

**Comment by deepu105** [comment]
Are you using material-ui module?  Or did you install that yourself?

In either case this wont be an issue with next version as the bootstrap js
is not used anymore

**Comment by deepu105** [comment]
Oh also its not a jhipster issue, material ui adds additional bootstrap sass dependency

**Comment by sendilkumarn** [comment]
@causevic  you can remove bootstrap.js from requires in bower.json then it will be fine.
