### ISSUE TITLE
Remove Twitter from Spring social connector

### ISSUE THREAD

**Issue by moifort** [jhipster/generator-jhipster#3167]
I juste analyze if we can use Twitter if Twitter. Recently you can have the email field. But there is some problems:

* You can have the email but you need to make a special request to Twitter (it's a bit heavy process)
* Apparently Twitter social connector didn't manage to get the email field
* I try and it's didn't work for me :disappointed: 

Link #2855

**Comment by jdubois** [comment]
For me it's not our issue -> we just configure Spring Social, and then if people want to have the email field with Twitter they need to do the paperwork

**Comment by moifort** [comment]
The problem is that the email is mandatory in `User` entity.

**Comment by jdubois** [comment]
Yes, if they don't configure their Twitter account it won't work -> for me it's the same thing as configuring the secret key, etc. If their Twitter configuration isn't correct, that's not working.
But if that annoys you, just remove it: Google and Facebook are far more important anyway.

**Comment by moifort** [comment]
@jdubois yes don't worry, if it's ok for you it's ok for me :). I just want that you have all informations to judge it!
