### ISSUE TITLE
[Gateway] registry's gateway.yml file

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3171]
##### **Overview of the issue**

The registry has a [gateway.yml](https://github.com/jhipster/jhipster-registry/blob/master/central-config/gateway.yml) file in central-config, this does no longer work since a gateway is not necessary named "gateway". This file contains only this:

~~~json
# Used on the gateway's startup to check the config server status
configserver:
    status: ${spring.cloud.config.uri} (OK)
~~~

I think this property should be added to bootstrap.yml or application.yml of generated gateways.

**Comment by gmarziou** [comment]
@PierreBesson as you created this file, do you have any comment?

**Comment by PierreBesson** [comment]
OK, the idea of this was to check if the config server is found as the configserver.status URL can only be displayed if the config server is found.

At the time I didn't know of the common config: application.yml. So this file should be removed and replace an application.yml file like this:

```
#common config shared between all apps
configserver:
    status: ${spring.cloud.config.uri}/${spring.cloud.config.label}/${spring.cloud.config.name}-${spring.cloud.config.profile}.yml
```

If it's OK for you I will PR this to the registry.

**Comment by gmarziou** [comment]
OK for me

**Comment by PierreBesson** [comment]
@gmarziou, It is done in https://github.com/jhipster/jhipster-registry/pull/23.

**Comment by gmarziou** [comment]
I think the URL is wrong, I changed it to make it clickable::

jhipster/jhipster-registry/pull/26
