### ISSUE TITLE
Jpa EntityListener used to synchronize ElasticSearch with database

### ISSUE THREAD

**Issue by lordlothar99** [jhipster/generator-jhipster#3172]
##### **Overview of the issue** 

[Enhancement] For SQL + ElasticSearch applications, usage of EntityListener

##### **Motivation for or Use Case** 

For applications using ElasticSearch, `EntityResource` / `EntityServiceImpl` call both `EntityRepository.save()` and `EntitySearchRepository.save()` ( resp `update()` / `delete()` ), which is not very elegant ; but the real problem is when an attached entity is fetch from `EntityRepository`, and updated, ElasticSearch is not automatically updated, so user need to be careful, and explicitly call `EntitySearchRepository.save()` method. 

##### **JHipster Version(s)** 

2.27.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "samplePsqlEsNoi18n",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useSass": true,
    "buildTool": "maven",
    "enableTranslation": false,
    "enableSocialSignIn": false,
    "rememberMeKey": "efaf561e5400af2877060b33324f34288d671c97",
    "testFrameworks": [
      "gatling",
      "protractor"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

Example :
```
{
    "relationships": [],
    "fields": [
        {
            "fieldName": "label",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "3"
        }
    ],
    "changelogDate": "20150805124936",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

##### **Related issues** 

Desynchronization problems are silent until #2244 is merged 

##### **Suggest a Fix** 

I have the code ready, and will submit a PR soon

**Comment by deepu105** [comment]
closed as PR is closed
