### ISSUE TITLE
[Gateway] one gateway shows other gateways API

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3173]
##### **Overview of the issue**

Minor issue: in case of multiple gateways, the swagger json on one gateway shows the /api/gateway resource of the other gateways.

**Comment by jdubois** [comment]
In fact it sees the gateway as another service, so it manages it the same as a microservice. I need to check what we can pass in the "metadata" section of the service registry, maybe we can tag our services, and in this case ignore the services tagged as "gateway".

**Comment by gmarziou** [comment]
Yes good idea

**Comment by jdubois** [comment]
That's not working so well in fact... When you use the Eureka client API you're going to see them all anyway, 
Another solution would be that the gateways only work as Eureka clients, and do not register themselves on the server: I'm not sure it's possible. And maybe some people would like to see them?? Looks weird, but it could be a use case.

**Comment by jdubois** [comment]
I don't have a good solution for this, and it's minor, so I'm closing this as I really don't have the time to work on it.
