### ISSUE TITLE
Move JDL documentation from UML to new section on menu

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3190]
Currently the JDL documentation is under Jhipster UML https://jhipster.github.io/jhipster-uml/#jdl

I would propose to move it up to be in a section called JDL

so menu would be like below

![image](https://cloud.githubusercontent.com/assets/1107223/13839942/26b0e9e8-ec5a-11e5-8fb1-5263fc4946f8.png)

@MathieuAA FYI

**Comment by jdubois** [comment]
Or have a global menu for "graphical generation" but we need a better word
for this.
Le 17 mars 2016 9:06 AM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
JDL seems to be catching on so I was thinking it would be good to put that
as a separate item

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Maybe have a "GUI tooling" section, which has: the JDL spec, JHipster UML, and the JDL studio

**Comment by deepu105** [comment]
In that case we need to think of a better name then `GUI tooling', I would
prefer simply `Tools` rather than GUI tools

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Im gonna put them under tools for now
