### ISSUE TITLE
Migrate generator-jhipster-docker-compose to a sub-generator

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3193]
The [JHipster Docker Compose generator(https://github.com/jhipster/generator-jhipster-docker-compose) is useful to everyone who wants to do microservices.

Migrating it to a sub-generator means that:

- It's installed for everyone from the start
- It's documented and easy to use in the main documentation

My proposal is that we call it "docker-compose", so that people only need to run "yo jhipster:docker-compose"

**Comment by deepu105** [comment]
I wanted to open this as an issue myself :) +1 it should be a sub gen

Thanks & Regards,
Deepu
