### ISSUE TITLE
OAuth2 with mongoDB error !

### ISSUE THREAD

**Issue by tuanngo** [jhipster/generator-jhipster#320]
When create app with authentication use token and database type is MongoDB.
Error creating bean with name OAuth2ServerConfiguration =>  No qualifying bean of type [javax.sql.DataSource]. Datasource is not Configuration when use MongoDB. Currently, the tokenStore use JdbcTokenStore  not compatible with MongoDB.

**Comment by ashishodia** [comment]
I have sucussfully done the connection with MYSQL now i am storing the data in MongoDB by chaning the DB Conf. as MONGODB. When executing getting error "Unexpected error accessing the API: Error creating bean with name 'mongoDbAuthTokenPersister".

Can Anyone Advise here.....
