### ISSUE TITLE
Spring-boot-dev : Error live reload

### ISSUE THREAD

**Issue by fraf** [jhipster/generator-jhipster#3202]
I installed Jhipster OTB, generated entities, created a Service and a DTO.
All works well.
I started the application with mvn spring-boot:run.
I've got the following final logs at console :+1: 

> ----------------------------------------------------------
>         Local:          http://127.0.0.1:8080
>         External:       http://10.110.5.73:8080
> ----------------------------------------------------------

I navigate for example to user management page to list all users.All is ok,

I decided to test "livereload" feature of spring boot.
Then I go for editing java file "UserResource.java". At "getAllUsers()" method I added at the beginning: 
`log.debug("Appel REST pour getAllUsers");`

Then I saved the file, log console updated like follow : 

> 2016-03-17 17:45:39.184  INFO 4884 --- [      Thread-10] com.tess2i.config.CacheConfiguration     : Remove Cache Manager metrics
> 2016-03-17 17:45:39.201  INFO 4884 --- [      Thread-10] com.tess2i.config.CacheConfiguration     : Closing Cache Manager
> 
>         ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
>         ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
>         ██  ████████     ██     ███████    █████      ██     ██████    ███████
>   ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██
>    ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██
> 
> :: JHipster ?  :: Running Spring Boot 1.3.1.RELEASE ::
> :: http://jhipster.github.io ::
> 
> 2016-03-17 17:45:39.664  INFO 4884 --- [  restartedMain] com.tess2i.Application                   : Starting Application on PCFX150 with PID 4884 (C:\ffournel\eclipseM\workspace\TessiCommunication\target\classes started by ffournel in C:\ff
> 2016-03-17 17:45:39.665 DEBUG 4884 --- [  restartedMain] com.tess2i.Application                   : Running with Spring Boot v1.3.1.RELEASE, Spring v4.2.4.RELEASE
> 2016-03-17 17:45:39.665  INFO 4884 --- [  restartedMain] com.tess2i.Application                   : The following profiles are active: dev
> 2016-03-17 17:45:42.203 DEBUG 4884 --- [  restartedMain] com.tess2i.config.AsyncConfiguration     : Creating Async Task Executor
> 2016-03-17 17:45:42.280 DEBUG 4884 --- [  restartedMain] com.tess2i.config.MetricsConfiguration   : Registering JVM gauges
> 2016-03-17 17:45:42.281 DEBUG 4884 --- [  restartedMain] com.tess2i.config.MetricsConfiguration   : Initializing Metrics JMX reporting
> 2016-03-17 17:45:43.190  INFO 4884 --- [ost-startStop-1] com.tess2i.config.WebConfigurer          : Web application configuration, using profiles: [dev]
> 2016-03-17 17:45:43.191 DEBUG 4884 --- [ost-startStop-1] com.tess2i.config.WebConfigurer          : Initializing Metrics registries
> 2016-03-17 17:45:43.192 DEBUG 4884 --- [ost-startStop-1] com.tess2i.config.WebConfigurer          : Registering Metrics Filter
> 2016-03-17 17:45:43.193 DEBUG 4884 --- [ost-startStop-1] com.tess2i.config.WebConfigurer          : Registering Metrics Servlet
> 2016-03-17 17:45:43.194 DEBUG 4884 --- [ost-startStop-1] com.tess2i.config.WebConfigurer          : Initialize H2 console
> 2016-03-17 17:45:43.195  INFO 4884 --- [ost-startStop-1] com.tess2i.config.WebConfigurer          : Web application fully configured
> 2016-03-17 17:45:43.650 DEBUG 4884 --- [ost-startStop-1] com.tess2i.config.DatabaseConfiguration  : Configuring Datasource
> 2016-03-17 17:45:43.718 DEBUG 4884 --- [ost-startStop-1] com.tess2i.config.DatabaseConfiguration  : Configuring Liquibase
> 2016-03-17 17:45:43.733  WARN 4884 --- [tion-Executor-1] c.t.c.liquibase.AsyncSpringLiquibase     : Starting Liquibase asynchronously, your database might not be ready at startup!
> 2016-03-17 17:45:44.223  WARN 4884 --- [ost-startStop-1] o.h.c.e.AbstractEhcacheRegionFactory     : HHH020003: Could not find a specific ehcache configuration for cache named [com.tess2i.domain.TypeFichier]; using defaults.
> 2016-03-17 17:45:44.295  WARN 4884 --- [ost-startStop-1] o.h.c.e.AbstractEhcacheRegionFactory     : HHH020003: Could not find a specific ehcache configuration for cache named [com.tess2i.domain.ConnexionEbics]; using defaults.
> 2016-03-17 17:45:44.312  WARN 4884 --- [ost-startStop-1] o.h.c.e.AbstractEhcacheRegionFactory     : HHH020003: Could not find a specific ehcache configuration for cache named [com.tess2i.domain.ServiceEntite]; using defaults.
> 2016-03-17 17:45:44.329  WARN 4884 --- [ost-startStop-1] o.h.c.e.AbstractEhcacheRegionFactory     : HHH020003: Could not find a specific ehcache configuration for cache named [com.tess2i.domain.Connexion]; using defaults.
> 2016-03-17 17:45:44.372  WARN 4884 --- [ost-startStop-1] o.h.c.e.AbstractEhcacheRegionFactory     : HHH020003: Could not find a specific ehcache configuration for cache named [com.tess2i.domain.Client]; using defaults.
> 2016-03-17 17:45:44.410  WARN 4884 --- [ost-startStop-1] o.h.c.e.AbstractEhcacheRegionFactory     : HHH020003: Could not find a specific ehcache configuration for cache named [com.tess2i.domain.TypeFichier.services]; using defaults.
> 2016-03-17 17:45:44.418  WARN 4884 --- [ost-startStop-1] o.h.c.e.AbstractEhcacheRegionFactory     : HHH020003: Could not find a specific ehcache configuration for cache named [com.tess2i.domain.ServiceEntite.typeFichiers]; using defaults.
> 2016-03-17 17:45:44.439 DEBUG 4884 --- [tion-Executor-1] c.t.c.liquibase.AsyncSpringLiquibase     : Started Liquibase in 706 ms
> 2016-03-17 17:45:45.223  INFO 4884 --- [ost-startStop-1] com.tess2i.Application                   : Running with Spring profile(s) : [dev]
> 2016-03-17 17:45:45.685  INFO 4884 --- [  restartedMain] c.tess2i.config.ThymeleafConfiguration   : loading non-reloadable mail messages resources
> 2016-03-17 17:45:46.557 ERROR 4884 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed
> 
> java.lang.NoClassDefFoundError: ManagedUserDTO
>         at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_66]
>         at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_66]
>         at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_66]
>         at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:609) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:521) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:507) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:241) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1069) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1042) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
>         at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
>         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
>         at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
>         at com.tess2i.Application.main(Application.java:74) [classes/:na]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
>         at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
>         at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.3.1.RELEASE.jar:1.3.1.RELEASE]
> Caused by: java.lang.ClassNotFoundException: ManagedUserDTO
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_66]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_66]
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_66]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_66]
>         at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.loadClass(RestartClassLoader.java:151) ~[spring-boot-devtools-1.3.1.RELEASE.jar:1.3.1.RELEASE]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_66]
>         ... 28 common frames omitted

After this liveReloading, the application doesn't respond anymore. you can see the error in the stack trace above.
How to correct this error ?

**Comment by jdubois** [comment]
You have a DTO, that comes from your MapStruct configuration, which has not run, so your class has not been compiled -> have a look at how MapStruct has to be configured, that depends on your IDE.
