### ISSUE TITLE
Running ./gradlew (Gulp + Gradle) seems to build for prod

### ISSUE THREAD

**Issue by rodrigomaio** [jhipster/generator-jhipster#3204]
##### **Overview of the issue**

Creating a project (v2.27.2 + Gradle + Gulp) and running ./gradlew seems to build for prod

##### **Motivation for or Use Case** 

Default build should be DEV env, e.g. show swagger API menu option, non-minified css/js, development tag (upper left)

##### **JHipster Version(s)** 

2.27.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
    "authenticationType": "session",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": true,
    "testFrameworks": [
      "gatling"
    ]

##### **Browsers and Operating System** 

OSX 10.11.3 , Node v5.5.0, gradle wrapper

##### **Reproduce the error** 

Run ./gradlew on a Gulp + Gradle project

##### **Related issues** 

https://github.com/jhipster/generator-jhipster/issues/3006

**Comment by atomfrede** [comment]
I have a fix at hand. Will do a PR this evening.

**Comment by atomfrede** [comment]
I'll close the issue. Will be in the next 2.x release. 
@jdubois I think we can release 3.0 first or both at the same time.

**Comment by deepu105** [comment]
it would be better to release a patch b4 3.0 as we should try to minimize
2.x releases after 3.0 to avoid confusion and to drive 3.0 adoption. so 2.x
patches after 3.0 should be aggregated and released only if there is enough
upgrade value or if there is critical bug

Thanks & Regards,
Deepu

**Comment by atomfrede** [comment]
@deepu105 Absoluty right. I was thinking of some sort of "final" 2.x release parallel to the 3.0 release and make clear 2.x is more or less end of life.

**Comment by jdubois** [comment]
I can do a new 2.x bug-fix release tomorrow (Monday). I haven't followed what's happened here, is the code ready for a release?

**Comment by atomfrede** [comment]
Yes it is. Problem was the frontend was always build for production.
