### ISSUE TITLE
Set default spring.jpa.show_sql to false

### ISSUE THREAD

**Issue by lordlothar99** [jhipster/generator-jhipster#3206]
##### **Overview of the issue**

Hibernate queries executions slow down build execution, and fill the console ; developers would rather activate them when necessary, but parameter default value should be `false`

##### **JHipster Version(s)** 

2.27.0

**Comment by jdubois** [comment]
I thought this was only true in the "dev" profile? Are you sure?

**Comment by lordlothar99** [comment]
it was in both `src/main/resources/config/_application-dev.yml` and `src/test/resources/config/_application.yml` ... in my opinion it's better to set it to `false`, so builds are faster ; anyway, developers can always put it to `true` in their own dev environment

**Comment by lordlothar99** [comment]
PR is #3207

**Comment by jdubois** [comment]
No that's on purpose: we output SQL statements in dev so that people see what they are doing. It's not slowing anything down, it's just outputed to the console. Or you have a much, much bigger issue as you are doing a ton of SQL requests (and that's what is slow).
