### ISSUE TITLE
Error on login with user created

### ISSUE THREAD

**Issue by bosofelipe** [jhipster/generator-jhipster#3215]
> Please follow the issue template below for bug reports and quiries.
> Bug reports or quiries opened without any of these info will be **closed** without any explanation.
> For feature requests, label the title with [FEATURE] and explain your use case and ideas clearly below, you can remove sections which are not relevant.

##### **Overview of the issue**

When i try logged with user created show this error

angular.js:12520Broken interceptor detected: Config object not supplied in rejection:
 https://github.com/chieffancypants/angular-loading-bar/pull/50(anonymous function) @ angular.js:12520

##### **Motivation for or Use Case** 

Error on loggin

##### **Browsers and Operating System** 

Chrome

##### **Reproduce the error** 

Create an user and login app

**Comment by jdubois** [comment]
I can't reproduce, we need your app version and options....
