### ISSUE TITLE
Can't create microservice in sub folder once docker-compose sub generator is launched

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#3216]
##### **Overview of the issue**

I can't create another microservice in sub folder, once the docker-compose sub generator is launched 1 time.

##### **JHipster Version(s)** 

master

##### **Reproduce the error** 

1) create root folder for gateway+microservices and go inside
2) create a sub folder and create a microservice inside
3) go to root folder, launch `yo jhipster:docker-compose`
4) select the microservice above
5) all is generated -> ok

6) create another sub folder, for gateway
7) go inside and when doing `yo jhipster`, the app will be generated at root folder

**Comment by jdubois** [comment]
Do you have a `.yo-rc.json` file in your root folder? This is a common and very annoying issue coming from Yeoman.

**Comment by pascalgrimaud** [comment]
Yes, can/should I remove it ?
```yaml
{
  "generator-jhipster": {
    "appsFolders": [
      "01-gateway",
      "02-mysql",
      "03-psql"
    ],
    "useElk": true,
    "jwtSecretKey": "10ce2aad5af87b6018429b0a980f473a2932acc0"
  }
}
```

**Comment by pascalgrimaud** [comment]
Ok I got it. As you said, it comes from Yeoman not our sub-generator -> I close the ticket.

If I launch `yo jhipster:docker-compose` at root folder, the `.yo-rc.json` file is generated, so I have to delete it to create other microservice.

If I launch `yo jhipster:docker-compose` in one of the sub folder microservice, new informations will be  added inside the initial `.yo-rc.json`:
```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "2.27.0",
    "baseName": "jhigateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "66d2c28b1766e87a21a6ee3c261da3331f3a0e7e",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "appsFolders": [
      "01-gateway",
      "02-mysql",
      "03-psql"
    ],
    "useElk": true
  }
}
̀``

**Comment by deepu105** [comment]
Pascal thats usual yeoman behaviour you cant create run a generator in
another generated apps subfolder. I.e you shouldn't have a yo-rc file on
any of your parent folder when yiu are running else yeoman automatically
will set the parent as root. Its documented on their website

**Comment by deepu105** [comment]
You you run docker-compose on its own sub folder which should be a sibling
of other gateway and mocroservice app folders. May be we should document
this clearly

**Comment by pascalgrimaud** [comment]
Thank you, yes, the folder where we should run this sub gen, should be documented
