### ISSUE TITLE
Docker-Compose / JHipster Registry "native" profile not taken into account

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3228]
I'm using:

- A microservices architecture
- JHipster Registry
- ELK

All this running with the docker-compose sub-generator.

When I run Docker Compose, JHipster Registry is started with the correct `SPRING_PROFILES_ACTIVE=prod,native` env variable (from Docker Compose, and I can validate this opening a console in the container), but the app starts with the log `The following profiles are active: prod`.

As the `native` profile is not taken into account, then my configuration isn't correct, of course.

@PierreBesson I know you coded this, is it working for you?

**Comment by deepu105** [comment]
I didnt see anything specific for a native profile in the code. Did I miss
anything?

**Comment by deepu105** [comment]
I did a project search and seems its not used anywhere in the generated apps, its set only on the registry's docker file and profile is defined in registry but doesnt seem to do anything specific

**Comment by PierreBesson** [comment]
@deepu105, the native profile comes from here: http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_environment_repository 

```
File System Backend

There is also a "native" profile in the Config Server that doesn’t use Git, 
but just loads the config files from the local classpath or file system (any static URL you want to
 point to with "spring.cloud.config.server.native.searchLocations"). 
To use the native profile just launch the Config Server with "spring.profiles.active=native".
```

**Comment by deepu105** [comment]
Oh Ok my bad didnt do enough research

Thanks & Regards,
Deepu
