### ISSUE TITLE
JWT - Authentication Token Key is not jhi-authenticationToken in sessionStorage

### ISSUE THREAD

**Issue by cicoub13** [jhipster/generator-jhipster#3235]
##### **Overview of the issue**

When using JWT authentication type :
* Authentication token key in localStorage is `jhi-authenticationToken` (rememberMe checked)
* Authentication token key in sessionStorage is `ngStorage-authenticationToken` (rememberMe not checked)

Prefix is not set when using sessionStorage.

Added in https://github.com/jhipster/generator-jhipster/pull/2927

##### **Motivation for or Use Case** 

Not a blocking bug, authentication is fully working. Maybe a bug from https://github.com/gsklee/ngStorage

##### **JHipster Version(s)** 

2.27.0 (current master)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

`{
  "generator-jhipster": {
    "baseName": "testapp",
    "packageName": "app.test",
    "packageFolder": "app/test",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "gulp",
    "enableTranslation": false,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling"
    ],
    "jhipsterVersion": "2.27.0",
    "applicationType": "monolith",
    "jwtSecretKey": "*****",
    "serverPort": 8080
  }
}`

##### **Browsers and Operating System** 

Chrom Windows/Mac

##### **Reproduce the error** 

* Generate application with .yo-rc.json
* Launch application
* Try authentication with rememberMe unchecked

##### **Suggest a Fix** 

I'll try to reproduce out of JHipster to see if it's come from ngStorage or JHipster. But it was working when pull request was merged.

**Comment by deepu105** [comment]
Thank you do let us know

**Comment by cicoub13** [comment]
Issue reproduced out of JHipster.
Issue created on ngStorage repo (https://github.com/gsklee/ngStorage/issues/206)

**Comment by wmarques** [comment]
Not a JHipster issue so I'm closing this, thanks for the report
