### ISSUE TITLE
Broken foreign key constraints generator

### ISSUE THREAD

**Issue by ashakhov** [jhipster/generator-jhipster#3240]
##### **Overview of the issue**

In some cases generated project can not execute liquibase changesets because of failing creation of foreign keys.
Value of variable `otherEntityTable` in [entity generator](https://github.com/jhipster/generator-jhipster/blob/0c89a18d999d2678ec9c7d7085328eaf931e85aa/generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml#L104) is snake-cased while `joinTableName` is not. Table names can now be defined by user, so if someone use CamelCased table names, his foreign key constraints will be broken.

##### **JHipster Version(s)** 
Commit 294e1d3 from GitHub

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "2.27.0",
    "baseName": "calculation",
    "packageName": "org.jhipster.test",
    "packageFolder": "org/jhipster/test",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "ru",
    "languages": [
      "ru",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

Generated by JHipster-UML 1.6.3 from [JDL](https://jhipster.github.io/jdl-studio/#view/entity%20Customer%20%7B%0A%09lastName%20String%20required%20minlength%281%29%0A%7D%0A%0Aentity%20Country%20%7B%0A%09name%20String%20required%20minlength%281%29%0A%7D%0A%0Aentity%20Region%20%7B%0A%09name%20String%20required%20minlength%281%29%0A%7D%0A%0Aentity%20City%20%7B%0A%09name%20String%20required%20minlength%281%29%0A%7D%0A%0Arelationship%20OneToMany%20%7B%0A%20%20%20%20Country%7Bregion%28name%29%7D%20to%20Region%7Bcountry%28name%29%7D%0A%7D%0A%0Arelationship%20OneToMany%20%7B%0A%20%20%20%20Region%7Bcity%28name%29%7D%20to%20City%7Bregion%28name%29%7D%0A%7D%0A%0Arelationship%20OneToMany%20%7B%0A%20%20%20%20%20City%20to%20Customer%7Bcity%28name%29%7D%0A%7D%0A%0Apaginate%20Customer%20with%20pagination%0A%0Aservice%20Customer%20with%20serviceClass)

```
{
  "relationships": [
    {
      "relationshipName": "region",
      "otherEntityName": "region",
      "relationshipType": "one-to-many",
      "otherEntityRelationshipName": "country",
      "relationshipId": 1
    }
  ],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "name",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "minlength"
      ],
      "fieldValidateRulesMinlength": 1
    }
  ],
  "changelogDate": "20160322173946",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "entityTableName": "Country"
}
```

##### **Suggest a Fix** 

Proposed fix is to remove snake-casing by replacing 
```
                                 var otherEntityTable = getTableName(otherEntityName);
                                 if (otherEntityTable == 'user') { %>jhi_user<% } else { %><%=otherEntityTable %><% } %>"/>
```
with
```
                                 if (otherEntityName.toLowerCase() == 'user') { %>jhi_user<% } else { %><%=otherEntityName %><% } %>"/>
```

**Comment by wmarques** [comment]
`joinTableName` seems snake cased, it's composed by `entityTableName` and `relationshipName`. `EntityTableName` is snaked cased in the entity subgenerator and `relationshipName` is snaked cased using `getTableName` function, which snake case and lowercase the string passed in parameter.

**Comment by deepu105** [comment]
No ideal fix would be to snake case what the user passes as well

**Comment by deepu105** [comment]
I dont understand what is the issue here, all table names are snake acse and even if you pass a table name its snake cased in the entity sub generator. But if you edit the json and camel case a table name then that's your problem.

Im closing this as its not a JHipster issue

**Comment by ashakhov** [comment]
Issue is that constraints in generated changeset for above-mentioned entity look like that:
```        <addForeignKeyConstraint baseColumnNames="country_id"
                                 baseTableName="Region"
                                 constraintName="fk_region_country_id"
                                 referencedColumnNames="id"
                                 referencedTableName="country"/>```

It tries to reference table "country" while its name is "Country". If TableName consist from two words, it would try to reference "table_name".

**Comment by ashakhov** [comment]
OK, it's up to JHipster-UML v.1.6.3 that generated CamelCased table names by default.

**Comment by deepu105** [comment]
Ok let me take another look

**Comment by ashakhov** [comment]
Seems like it was fixed in one of [recent commits](https://github.com/jhipster/jhipster-uml/commit/5e2728d6cd40efc07939954f7c38d3d1b9a9fb3c#diff-eb0fce4be6d89b66837d9c1c6afe3f66) for jhipster-uml but merged only yesterday.
