### ISSUE TITLE
Use eslint in the generator itself

### ISSUE THREAD

**Issue by wmarques** [jhipster/generator-jhipster#3244]
As per https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/-L8ZlfaLPJY/aBfKVqYlBwAJ

Eslint supports natively some coding styles, like Airbnb's one. Using this tool will prevent code unconsistency in our various JS files.

**Comment by wmarques** [comment]
@jhipster/developers if you guys agree on a style (or to use for the moment some simple rules like mandatory commas, triple equals, indent) I can start working on this

**Comment by deepu105** [comment]
ok for me

Thanks & Regards,
Deepu

**Comment by wmarques** [comment]
@deepu105 I've got an error when running with angular plugin 

`Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at findFunctionByNode (/home/ippon/generator-jhipster/node_modules/eslint-plugin-angular/rules/utils/angular-rule.js:199:17)
`

Did you encounter that error also?

**Comment by deepu105** [comment]
I do not understand, why are you using angular plugin.?  For the generator
you should be using only plain javascript or airnb style and not angular
style

**Comment by wmarques** [comment]
Oh ok you just want to run eslint on generator files and not generated files, sorry I misunderstood !

**Comment by deepu105** [comment]
Yes :) for generated files our gulp task already has this covered.

For generator itself this should be a task in npm script block

**Comment by wmarques** [comment]
Ok I see, I'm doing this !
