### ISSUE TITLE
Gradle buildDocker task stuck

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3245]
##### **Overview of the issue**

The `buildDocker` task is always stuck at 94% without completion

```
Deepu@DESKTOP-3NUQHBI MINGW64 /d/Projects/test/microserv/app1
$ ./gradlew -Pprod bootRepackage buildDocker
:processResources UP-TO-DATE
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:war
:bootRepackage
:assemble
:compileTestJava UP-TO-DATE
:compileTestScala UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:cucumberTest UP-TO-DATE
:testReport UP-TO-DATE
:check UP-TO-DATE
:build
> Building 94% > :buildDocker
```

the dockerfile and .yml files are copied to the build/docker folder

here is the detailed log of the build task onwards
```
:build (Thread[main,5,main]) started.
:build
Skipping task ':build' as it has no actions.
:build (Thread[main,5,main]) completed. Took 0.007 secs.
:buildDocker (Thread[main,5,main]) started.
:buildDocker
Executing task ':buildDocker' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
Setting up staging directory.
Creating Dockerfile from file D:\Projects\test\microserv\app1\src\main\docker\Dockerfile.
Determining image tag: app1:latest
Using the native docker binary.
> Building 94% > :buildDocker
```

##### **JHipster Version(s)** 

master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "2.27.0",
    "baseName": "app1",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "gradle",
    "jwtSecretKey": "b1f0cd86b663b97cf58776c004bdf5c68141126a",
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "skipClient": true,
    "skipUserManagement": true,
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false,
    "serverPort": "8080"
  }
}
```

##### **Browsers and Operating System** 

WINDOWS 10

##### **Reproduce the error** 

generate an app with above config and run `./gradlew -Pprod bootRepackage buildDocker`

**Comment by deepu105** [comment]
ping @atomfrede @PierreBesson

**Comment by PierreBesson** [comment]
Hi @deepu105,
A few minutes the Alpine CDN was down, so the image could not install openjdk8. It came back up minutes ago, can you try your gradle docker build again to see if the problem is solved ?

**Comment by PierreBesson** [comment]
Also Julien is moving all images to openjdk-8-jdk-alpine which is a new official openjdk docker image  based on alpine, so the problem will not happen in the future.

**Comment by deepu105** [comment]
oh ok ill try again. Thanks @PierreBesson

**Comment by deepu105** [comment]
I tried with latest change but its still stuck at the same place. I think the image is created though coz when I do `docker-compose up -d` i do see the app being started in docker without any erorr so this seems like the process just not finishing

**Comment by PierreBesson** [comment]
@deepu105, generating a docker image from your .yo-rc.json works well on my linux system.

If you don't see the `BUILD SUCCESSFUL` message. That means that the image didn't build so actually the `docker-compose up` you launch must be using an image that you build in the past and that was also named app1.

Can you try the following:
* check if the image is already present with `docker images`
* remove the image from your system with: `docker rmi <image-id>`

Then docker-compose up should not work anymore.

**Comment by deepu105** [comment]
ok will try, I guess this might be a bug with the docker gradle plugin on
windows

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
@deepu105 : I confirm your issue

**Maven**: no problem with the [docker maven plugin](https://github.com/spotify/docker-maven-plugin), made by spotify
**Gradle**: it seems that this [docker gradle plugin](https://github.com/Transmode/gradle-docker/) is not very active...  although it's proposed in official [spring boot doc](https://spring.io/guides/gs/spring-boot-docker/)

For me, there are 2 solutions:
- give a try to this repo https://github.com/bmuschko/gradle-docker-plugin
- write a sub generator, which will :
    - use shelljs and copy necessary files to folder build/docker
    - launch docker build

**Comment by pascalgrimaud** [comment]
Just tried a 3rd solution. I'm working on gradle with Windows (sorry, I'm total newbie with Gradle, so I prefer not PR before being sure this solution works).

Can you try this, @deepu105 ? cc @atomfrede too our Gradle expert :-)

Replace your `docker.gradle` by this file, and edit **mspsql** by your application name :
```gradle
import org.apache.tools.ant.taskdefs.condition.Os

task buildDocker(type: Exec) {
    doFirst {
        copy {
            from "src/main/docker/"
            into "build/docker/"
            include "*"
        }
        copy {
            from "build/libs"
            into "build/docker/"
            include "*.war*"
        }
    }
    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        commandLine 'cmd', '/c', 'docker', 'build', '-f', 'build/docker/Dockerfile', '-t', 'mspsql', 'build/docker/'
    } else {
        commandLine 'docker', 'build', '-f', 'build/docker/Dockerfile', '-t', 'mspsql', 'build/docker/'
    }
}
```

**Comment by atomfrede** [comment]
Looks like its working. At least the build is not stuck at 94% anymore.
