### ISSUE TITLE
Admin part of code is exposed to the non admin clients. 

### ISSUE THREAD

**Issue by lubo08** [jhipster/generator-jhipster#3246]
I think that problem is that also admin parts of html are exposed to the client even client is log in as user not admin still there is admin code. This can't happened in secure application. Just use thymeleaf with spring security to do not expose this part of code to the client.

`<li ng-class="{active: $state.includes('admin')}" ng-switch-when="true" has-authority="ROLE_ADMIN" class="dropdown pointer ng-scope hidden">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="" id="admin-menu">
                        <span>
                            <span class="glyphicon glyphicon-tower"></span>
                            <span class="hidden-sm ng-scope" translate="global.menu.admin.main">Administration</span>
                            <b class="caret"></b>
                        </span>
                    </a>
                    <ul class="dropdown-menu">
                        <li ui-sref-active="active"><a ui-sref="user-management" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/user-management"><span class="glyphicon glyphicon-user"></span>
                            &nbsp;<span translate="global.menu.admin.user-management" class="ng-scope">User management</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="tracker" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/tracker"><span class="glyphicon glyphicon-eye-open"></span>
                                &nbsp;<span translate="global.menu.admin.tracker" class="ng-scope">User tracker</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="metrics" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/metrics"><span class="glyphicon glyphicon-dashboard"></span>
                            &nbsp;<span translate="global.menu.admin.metrics" class="ng-scope">Metrics</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="health" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/health"><span class="glyphicon glyphicon-heart"></span>
                            &nbsp;<span translate="global.menu.admin.health" class="ng-scope">Health</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="configuration" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/configuration"><span class="glyphicon glyphicon-list-alt"></span>
                            &nbsp;<span translate="global.menu.admin.configuration" class="ng-scope">Configuration</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="audits" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/audits"><span class="glyphicon glyphicon-bell"></span>
                            &nbsp;<span translate="global.menu.admin.audits" class="ng-scope">Audits</span></a></li>
                        <li ui-sref-active="active"><a ui-sref="logs" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/logs"><span class="glyphicon glyphicon-tasks"></span>
                            &nbsp;<span translate="global.menu.admin.logs" class="ng-scope">Logs</span></a></li>
                        <li ng-hide="inProduction" ui-sref-active="active" aria-hidden="false"><a ui-sref="docs" data-toggle="collapse" data-target=".navbar-collapse.in" href="#/docs"><span class="glyphicon glyphicon-book"></span>
                            &nbsp;<span translate="global.menu.admin.apidocs" class="ng-scope">API</span></a></li>
                        
                        <li ng-hide="inProduction" aria-hidden="false"><a href="/h2-console" target="_tab" data-toggle="collapse" data-target=".navbar-collapse.in"><span class="glyphicon glyphicon-hdd"></span>
                            &nbsp;<span translate="global.menu.admin.database" class="ng-scope">Database</span></a></li>
                    </ul>
                </li>`

**Comment by jdubois** [comment]
No, we can't serve it with Thymeleaf, this is pure static HTML pages, so you can serve it from an HTTP server or from a CDN.
There is no security risk, it's just presentation code.

**Comment by deepu105** [comment]
this is not gonna happen and this is not an issue, its only the html thats loaded and not the data, without the data this doent pose any security concern

**Comment by deepu105** [comment]
@jdubois you beat me to it :P

**Comment by lubo08** [comment]
OK but is not security issue if me as a hacker I'm able to see what admin can do? This help so much to discover weakness of the system. Doesn't matter if there are data or not. User shouldn't see what is admin able to do.

**Comment by deepu105** [comment]
I dont know what weakness one can discover from html code!! In that case
the client side js code you expose can expose way more weakness than any
html by your logic

Thanks & Regards,
Deepu

**Comment by lubo08** [comment]
https://en.wikipedia.org/wiki/Attack_surface

Just simple rule even with OWASP security. Minimize risk as possible and do not expose and of course also admin parts of javascript is included also. just split admin javascript code and do not include to html if user is not admin.

**Comment by jhulick** [comment]
@deepu105 the primary issue as I see is not about exposing admin html code but the security roles to the client. A hacker could determine privilege escalation by looking at the markup. With that said, I've commented on the closed issue #1293 and also agree with you and @jdubois

**Comment by deepu105** [comment]
I understand were you are coming from but these are concern only for extremely secure apps. for normal scenarios presentation code shouldn't cause a security concern. For your concern about roles on the client I have something to fix that but will need to find some time to do that on the generator but could be soon.

So yes if you are overly concerned you can use thymeleaf we ship it OOTB anyways but the default setup will remain as it is for now.

**Comment by lubo08** [comment]
Just please consider this as I would like to use it for bank applications also. I think this is great project so I think can't be so hard thinking little bit more secure. Just consider that If hacker have admin look and feel can much easier prepare some social attack and create some admin looks website and send link to administrator to fill some sensitive data. You never be ready to prevent against this social attacks. But you can minimize risk as much as possible. Can't be hard a little refactoring with more than 200 contributors :)  And this project is not about some application this project is base for any kind of application eve those with highest security needs.

**Comment by gmarziou** [comment]
@lubo08 what about contributing yourself?
I'd be curious to see how you implement this and deal with template caching and ui routing.

**Comment by deepu105** [comment]
I would rather rethink my architecture for such critical app. You should
probably consider a microservice like architecture with a gateway for
public access  (this shouldn't have any admin stuff in it at all ) and a
dedicated gateway for admin (this shouldn't be exposed to public and should
be behind a firewall/reverse proxy)

You can reuse some backend services between the 2 gateways. This would
ensure that you have less risk and will keep your assets safe from public.

It would be very risky to have both admin and public part of a banking site
on the same app.

**Comment by jdubois** [comment]
Yes, if that's your need, just do 2 gateways, one public and one private. You shouldn't have your admin API opened publicly anyway.

**Comment by lubo08** [comment]
OK thank you just even this app will be inside private network. Security audit didn't allow application with public admin parts. of course API will be protected but also html sources and javascript have to be protected. Maybe generator should offer if you want use angular templates or  completely run on thymeleaf templates.

**Comment by japharr** [comment]
You can also use the login user role in the server code to determine what will be returned to the html view..

**Comment by jdubois** [comment]
I agree this isn't clearly explained on our website, we should update the
security section.
Le 24 mars 2016 8:28 AM, "Jaleel Adesina" <notifications@github.com> a
écrit :

**Comment by lubo08** [comment]
Maybe this could be the way https://dzone.com/articles/thymeleaf-fragments-and
Just even for single public application not so much with security concern I do not want to have public admin parts and micro-service environment is not always the case. Just would be nice to have this as default.

**Comment by deepu105** [comment]
@lubo08 Sorry but as myself and @jdubois highlighted we wont be doing this in the near future as there is a way to do your use case more elegantly (using a microservice architecture which we would suggest)

**Comment by lubo08** [comment]
So any of users who use jhipster without micro-service architecture are not concern about social attack when hacker mask own site to admin page of your site and sent this to your users? What you think how many of 100 users will fill this form with sensitive data (password, credit card number, etc.)? 5% 10%? 

**So if I'm concern about security have to chose micro-service or otherwise I didn't have to concern about security. **

Right now I'm working on project where micro-service architecture is not possible.

Anyway thank you for help and discussion about this.  

Thank you.

**Comment by jdubois** [comment]
JHipster is just a generator, it can't do everything for everyone. What you describe here is an incredibly complex attack, with someone un-scrambling the minimized admin screens, changing them so they work with another backend, managing to trick users into using his website (and that means people entering their credentials on another website! Isn't this really complex??)... So if you have such a need, then don't expect a generator, which by its nature is something very generic, can do it. We have also a focus on performance and usability, and the current security is very good: in 2,5 years, with nearly 200,000 downloads, we have never, ever had a security vulnerability. I'm not saying what we we do is perfect, but it's secured enough for most people.
If you don't like or want the admin screens, then just remove them: it's just a generator, those screens are not mandatory.
If you want to serve them with Thymeleaf, that's probably very easy to do, too. By default I wouldn't do this, but for your specific use case you can choose to do it.

**Comment by deepu105** [comment]
I think you are just exaggerating something which is a very rare case. If you choose to have admin and public part of a very sensitive app on the same package then you have more architecture security concerns to worry about then static presentation asset which possess minimum risk. 

To me you have choose a poor architecture for a very sensitive app. I work for a big enterprise client and I would never put my admin into the same app which is open to public.

You should really reconsider your architecture if you want to be extremely safe against any attack. I would never put my admin stuff on the public facing part of my network even if it has all admin static assets hidden away as you suggest.

**Comment by deepu105** [comment]
@jdubois we are always in sync :joy:
