### ISSUE TITLE
Heroku deploy

### ISSUE THREAD

**Issue by bosofelipe** [jhipster/generator-jhipster#3248]
##### **Overview of the issue**

Heroku deploy

##### **Motivation for or Use Case** 

Not working heroku deploy

##### **JHipster Version(s)** 

2.27

##### **Reproduce the error** 

When I run yo jhipster:heroku

show error

{ [Error: Command failed: mvn package -Pprod -DskipTests=true && heroku deploy:jar --jar target/*.war --app https://c
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.9
 !    No access to this app
]

What do i do?

**Comment by deepu105** [comment]
We need your .yo-rc file if you need help plz follow our issue guidelines.

**Comment by deepu105** [comment]
its clearly stated in the bug report template as well

**Comment by bosofelipe** [comment]
@deepu105 

{
  "generator-jhipster": {
    "baseName": "eventfy",
    "packageName": "br.com.boso.eventfy",
    "packageFolder": "br/com/boso/eventfy",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "e7b5edbb92c18bd61614e6c3de77f2e21065c2df",
    "testFrameworks": [
      "gatling"
    ]
  }
}

tks.

**Comment by jdubois** [comment]
I cleaned up your ticket, and your title is not clear... Can you put a clear title?

**Comment by jdubois** [comment]
Oh, and did you read your error:

    Not compatible with your operating system or architecture: fsevents@1.0.9

So we need your OS, node version, etc, as required in the guidelines.

**Comment by jdubois** [comment]
Closing this as the guidelines are not followed

**Comment by deepu105** [comment]
@bosofelipe plz open a new ticket with all required details

**Comment by bosofelipe** [comment]
@jkutner This happened because the heroku machine haven´t a npm installed, in my jhipster configuration i choose saas compiler...
Removing saas compiler this error was not showed
