### ISSUE TITLE
aws deployment does not save inputs

### ISSUE THREAD

**Issue by dscowan** [jhipster/generator-jhipster#3249]
Version 2.27 deployment requires re-entry of inputs on every run.   It would be helpful if the input was cached and used on subsequent runs.

**Comment by deepu105** [comment]
we wont be adding features to 2.x branch since we have 3.0 out already. I guess this is something that can be considered for current version. will see what can be done

**Comment by deepu105** [comment]
cc @wuethrich44

**Comment by wuethrich44** [comment]
Fixed in https://github.com/jhipster/generator-jhipster/pull/2679 so you can close this issue.
