### ISSUE TITLE
Add unicity constraint in entities field

### ISSUE THREAD

**Issue by sebastienmoreno** [jhipster/generator-jhipster#3251]
hi,
would it be interesting to be able to add unicity constraint on entity fields when generating ?

I guess, today it is possible in post-generation by modifying liquibase configuration and JPA annotations but not directly by the generator itself.

Regards,
Sebastien

**Comment by deepu105** [comment]
@sebastienmoreno could you add more details on what is the use case and what would be the value of having this. Would be nice if you can explain your use case

**Comment by DiegoEP** [comment]
+1 
When we create entities by importing a JDL it would be great if were possible to indicate some fields as "unique". Currently, I need to import JDL first, then modify the liquibase changelog and finally edit the generated entity. 

This could be done for example as following:
```
entity User {
    id Long,
    email String required unique
}    
```

It would generate this liquibase changelog:
```
<column name="email" type="varchar(255)">
                <constraints unique="true" nullable="false" />
</column>
```
And the following annotation in the JPA Entity:
```
@NotNull
@Column(unique=true, nullable=false)
private String email;
```

**Comment by dornala** [comment]
If I understood correctly, you are asking if adding unique values to fields be any better. Right?

_I personally feel its a good idea. As of now we need to feed them manually._

**Comment by sebastienmoreno** [comment]
Indeed I think it would interesting to have this feature.
Was it not added to JHipster because of legacy database? (if newly add a unique constraints, your current data need to respect this new constraints)

**Comment by dornala** [comment]
@deepu105  I am making this change as part of code "adding required field to Relationship". You can move these both to in-progress.

**Comment by deepu105** [comment]
Please make seperate PR so that one doesnt get stuck coz of other. We
havent yet decided if the unique constraint part adds value or not

**Comment by deepu105** [comment]
@jdubois do you want this? if not lets close it

**Comment by jdubois** [comment]
Not sure we should add this, with regards to our policy 2

**Comment by deepu105** [comment]
Yes thats why I'm hesitant as well

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Let's not do it then, our policy 2 should be followed, as always.
