### ISSUE TITLE
Microservice application generation ends at 12/16

### ISSUE THREAD

**Issue by devlanp** [jhipster/generator-jhipster#3252]
Team,

I do understand that this one is minor just to make this app more awesome. The microservice application ends at 12/16 question !

Welcome to the JHipster Generator v3.0.0
Application files will be generated in folder: D:\Workspace\STS\test
? (1/16) Which *type* of application would you like to create? Microservice application
? (2/16) What is the base name of your application? test
? (3/16) As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8081
? (4/16) What is your default Java package name? com.mycomp.test
? (5/16) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL, Oracle)
? (6/16) Which *production* database would you like to use? PostgreSQL
? (7/16) Which *development* database would you like to use? H2 with in-memory persistence
? (8/16) Do you want to use Hibernate 2nd level cache? No
? (9/16) Do you want to use a search engine in your application? No
? (10/16) Would you like to use Maven or Gradle for building the backend? Maven
? (11/16) Would you like to enable internationalization support? No
? (12/16) Which testing frameworks would you like to use? Gatling, Cucumber

Tx.

**Comment by deepu105** [comment]
Yes we know. Its a very minor glitch which would require some very complex
code, which I did and removed later, which is tough to maintain.

Thanks & Regards,
Deepu

**Comment by devlanp** [comment]
Never mind! Awesome work otherwise. Trying the app now :-)
