### ISSUE TITLE
Jhipster 3.0

### ISSUE THREAD

**Issue by khouloudkhadija** [jhipster/generator-jhipster#3256]
I'm using the new version of jhipster 3.0, and when I create a new application and I run it without any error, no thing is displayed on my browser just a white page with the famous word "footer", I can't understand the problem and I can't solve it.

**Comment by gmarziou** [comment]
I suppose you are the one who asked this question on stackoverflow:
https://stackoverflow.com/questions/36218397/i-cannot-run-jhipster-application-using-the-latest-jhipster-version-3-0

Sorry but your questions are really not detailed enough as I already told you several times. Being a beginner does not excuse everything, especially when you post an issue and don't fill the required information.

**Comment by jdubois** [comment]
Please don't cross-post with StackOverflow, and please follow our guidelines.
