### ISSUE TITLE
JWT does not work with Spring Security Evaluation Extension

### ISSUE THREAD

**Issue by Vaelyr** [jhipster/generator-jhipster#3259]
##### **Overview of the issue**

`SecurityEvaluationContextExtension` bean which provides Security Context for SpEL expressions throws exception during evaluation when using JWT authentication. Works with other auth methods, and also with old Xauth token.

##### **Motivation for or Use Case** 

Using current principal for custom Spring Data queries and on`@PreAuthorize` expressions, to determine the permissions for certain resources. For example:

`@PreAuthorize("@usecaseService.canAccessUsecase(principal.username, #usecaseId)")`
or
`@Query("SELECT uc FROM Usecase uc JOIN uc.usecaseUsers uu WHERE uu.user.email = ?#{principal.username}")
  List<Usecase> findAllForCurrentUser();`

##### **JHipster Version(s)** 

v3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "company",
    "packageName": "com.company.app",
    "packageFolder": "com/company/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "123",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Reproduce the error** 

- Create a method into some service class with boolean return type and return true/false.
- Annotate any resource operation method with `@PreAuthorize(@yourService.yourBooleanMethod(principal.username)")`
- Make a call to the method
- Observe exception thrown

##### **Related issues** 

Could possibly be something similar to what JWT had with Websockets? Not sure, hard to find any reference. 

##### **Suggest a Fix** 

Haven't found yet.

**Comment by jdubois** [comment]
Yes, I didn't test but this is logical, and I think this has already been reported (but your bug report is better, and I couldn't find the other bug...).
For a microservice that's normal, as you don't have user management in microservices.
For a monolith that's different, but as I mainly added JWT for microservices, this isn't something I haven't worked on.

**Comment by Vaelyr** [comment]
Okay after some debugging it seems that it is not Jhipster related. Possibily an undocumented change in Spring Security 4.0.4 (?), as it was fine with earlier when I used it like shown above.

The `principle` now actually just returns String, instead reference to the actual object.
However `authentication` returns the Principal object itself, from where you would get access to the principal name and authorities.

In this case the problem gets solved using these values appropriately:
- `@PreAuthorize("@usecaseService.canAccess(principal, #usecaseId)")`
with method
`public boolean canAccess(String principal, Long id) { .. }`
- `@PreAuthorize("@usecaseService.canAccess(authentication, #usecaseId)")`
with method
`public boolean canAccess(Principal principal, Long id) { .. }`

**Comment by jdubois** [comment]
OK but I think this might be a valid use case so I'm reopening it, I'll study this later.

**Comment by jdubois** [comment]
Indeed that's the use case I was expecting, it's not really a bug, but that makes this use case fail. I'm correcting this.
