### ISSUE TITLE
Delete entity

### ISSUE THREAD

**Issue by Meriem19** [jhipster/generator-jhipster#3260]
Helllo guys 
##### **Overview of the issue**

I, buy mistake added an entity that i don't need.
How can I remove it ??

##### **JHipster Version(s)** 
 2.27.1

**Comment by jdubois** [comment]
Easiest way is to use Git to rollback the code.
I'm sorry but this shouldn't be a ticket, next time please use StackOverflow for this kind of questions.

**Comment by Meriem19** [comment]
Okay thnaks :)
