### ISSUE TITLE
mvn liquibase:diff creates a changelog on fresh project

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#3261]
##### **Overview of the issue**
When using the command 'mvn liquibase:diff' after generating a project, a changelog is generated to make jhi_user's email field allow null values
` <databaseChangeLog> 
<changeSet author="ruddell (generated)" id="1458876730446-1"> 
<dropNotNullConstraint columnDataType="varchar(100)" columnName="email" tableName="jhi_user"/> </changeSet>
 </databaseChangeLog> `

##### **Motivation for or Use Case** 
No changelogs should be generated for a fresh project when using the liquibase:diff goal

##### **JHipster Version(s)** 
3.0.0 and master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
`{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "liquibasetest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "f376d00e2717574dc1795054a2aba87cd4dcaba6",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}`
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

No entities required
##### **Browsers and Operating System** 

All

##### **Reproduce the error** 

yo jhipster
(ensure mysql is running and credentials/database are valid)
mvn
mvn liquibase:diff

##### **Related issues** 
#2674 is the issue where where initial_schema.xml changed to make the email field not null
##### **Suggest a Fix** 
I'm not sure why the changelog is generated

**Comment by davidrdz93** [comment]
I had a hard time trying to use liquibase on my spring boot application. Finally it works with the following dependencies:

Spring boot

```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.2.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```

Liquibase core
``` 
		<dependency>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-core</artifactId>
			<version>3.8.7</version>
		</dependency>
```

Maven plugin 

``` 
			<plugin>
				<groupId>org.liquibase</groupId>
				<artifactId>liquibase-maven-plugin</artifactId>
				<version>3.8.7</version>
				<configuration>
					<propertyFile>src/main/resources/liquibase.properties</propertyFile>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.springframework</groupId>
						<artifactId>spring-core</artifactId>
						<version>${spring-framework.version}</version>
					</dependency>

					<dependency>
						<groupId>org.springframework</groupId>
						<artifactId>spring-beans</artifactId>
						<version>${spring-framework.version}</version>
					</dependency>

					<dependency>
						<groupId>org.springframework</groupId>
						<artifactId>spring-context</artifactId>
						<version>${spring-framework.version}</version>
					</dependency>

					<dependency>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-starter-data-jpa</artifactId>
						<version>${project.parent.version}</version>
					</dependency>

					<dependency>
						<groupId>org.liquibase.ext</groupId>
						<artifactId>liquibase-hibernate5</artifactId>
						<version>3.8</version>
					</dependency>

					<dependency>
						<groupId>javax.xml.bind</groupId>
						<artifactId>jaxb-api</artifactId>
						<version>2.3.1</version>
					</dependency>

					<dependency>
						<groupId>org.glassfish.jaxb</groupId>
						<artifactId>jaxb-runtime</artifactId>
						<version>2.3.1</version>
					</dependency>

					<dependency>
						<groupId>javax.validation</groupId>
						<artifactId>validation-api</artifactId>
						<version>2.0.1.Final</version>
					</dependency>
				</dependencies>
			</plugin>
```

If i take out only one of the dependencies that you see on the plugin, it just doesn't work anymore.

I hope this would be helpful for other people (consider that took me 2 days of trying to get it work)
