### ISSUE TITLE
Should not allow to generate entity when DB is none

### ISSUE THREAD

**Issue by cbehrends** [jhipster/generator-jhipster#3267]
##### **Overview of the issue**

When attempting to generate a new entity on a fresh JHipster project there are multiple failures.  

Adding a new field to the entity never asks for a data type and is always "undefined".  This appears to cause multiple issues downstream when trying to generate the object (which never gets created).

I can post all of the traces if you like, but I"m pretty sure that they are all due to the missing data type for the new field.

Note that this only seems to happen on the "microservice" project type.

##### **JHipster Version(s)** 

3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "corey",
    "packageName": "com.goldstartransportation.loadorg.web",
    "packageFolder": "com/goldstartransportation/loadorg/web",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": "no",
    "buildTool": "gradle",
    "jwtSecretKey": "asdfasdfa",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "skipClient": true,
    "skipUserManagement": true,
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

This never gets created

##### **Reproduce the error** 

Create new app using yo jhipster
Attempt to add a new entity

**Comment by cbehrends** [comment]
I was able to track down what was causing this issue.  Attempting to run the entity generator when the "no database" option was selected results in this issue.

**Comment by jdubois** [comment]
LOL :-)
I'm reopening this as it's a use case we should not allow -> we should do a check and if selected "no database" we should exit with a proper warning message.

**Comment by cbehrends** [comment]
Fair enough sir.  If I get some time today I'll look at it.  I'm guessing it's a pretty simple change.

**Comment by jdubois** [comment]
Oh yes that should be an easy PR, thanks !!!!
