### ISSUE TITLE
[FEATURE] Select entities to be searched

### ISSUE THREAD

**Issue by ashakhov** [jhipster/generator-jhipster#3269]
As for now, if we enable ElasticSearch during project generation, it adds `@Document` and search resource file for every created entity. But sometimes entities doesn't need to be searched so it will be only a waste of resources. Yes, you can remove unwanted parts, but it can be a lot of work if there is a lot of such entities. Maybe it's worth it to add an option for enabling or disabling search in entity generator (and maybe JDL as well)?

**Comment by wmarques** [comment]
So what you want is an additional question in the entity subgen that asks you if you want elasticsearch on your entity or not ?

**Comment by deepu105** [comment]
I dont think there is much value in doing this, if you dont want elastic
search just remove the annotation and be done with it. Yes you might have
some dead left over code but its not that bad. Ir worst case it can be a
command line argument to disable it like `no-search` def not worth another
question

**Comment by ashakhov** [comment]
>So what you want is an additional question in the entity subgen that asks you if you want elasticsearch on your entity or not ?

Maybe. I'm mostly interested in generating entities using JDL, but it still depends on entity subgen.
I can try to make it myself and send a PR, but I thought it would be better to ask if someone else is interested or there is some pitfalls that I don't know about. Or maybe it just doesn't worth it.

**Comment by deepu105** [comment]
Im closing this, will support this with a switch here if its added in JDL cc @MathieuAA plz reopen if you plan to support this

**Comment by MathieuAA** [comment]
I'll open an "issue" (such a stupid name) in the JDL project "issue" tracker as I want to make it available.

**Comment by jdubois** [comment]
As @deepu105 said, let's close this!
