### ISSUE TITLE
Support for LocalDateTime type

### ISSUE THREAD

**Issue by lsgpimentel** [jhipster/generator-jhipster#3271]
Any reason for it not being supported today? :S

**Comment by deepu105** [comment]
I dont understand what you are trying to ask. We already support java 8 localDateTime and zonedDateTime

**Comment by jdubois** [comment]
Indeed, no idea of what you meant!

**Comment by lsgpimentel** [comment]
@deepu105 and @jdubois,

No, it's not supported. Please, look at the code: https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L335
Look at the docs: http://jhipster.github.io/creating-an-entity/

LocalDate is supported, not LocalDateTime.

**Comment by jdubois** [comment]
Sorry, I need to check -> I reopen this until I have time.

**Comment by MathieuAA** [comment]
He's right, the type isn't supported by JHipster, but LocalDate is (you may have been mistaken because of Time suffix Deepu ;)).

@lsgpimentel, Is there a major difference between this type and one of the already supported ones?

**Comment by lsgpimentel** [comment]
> A date-time without a time-zone in the ISO-8601 calendar system, such as 2007-12-03T10:15:30.
...
> This class does not store or represent a time-zone. Instead, it is a description of the date, as used for birthdays, combined with the local time as seen on a wall clock. It cannot represent an instant on the time-line without additional information such as an offset or time-zone.

https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html

Birth dates and other dates that don't need time-zone are usecases.


> A date-time with a time-zone in the ISO-8601 calendar system, such as 2007-12-03T10:15:30+01:00 Europe/Paris.
ZonedDateTime is an immutable representation of a date-time with a time-zone. This class stores all date and time fields, to a precision of nanoseconds, and a time-zone, with a zone offset used to handle ambiguous local date-times. For example, the value "2nd October 2007 at 13:45.30.123456789 +02:00 in the Europe/Paris time-zone" can be stored in a ZonedDateTime.

https://docs.oracle.com/javase/tutorial/datetime/iso/timezones.html

Since it considers the time-zone, DST and other _sui generis_ anomalies are correctly treated.

**Comment by deepu105** [comment]
Oh sorry I didn't look close enough. This is why we need detailed issue
reports or clearer feature requests so that we dont have to dig too much to
understand whats asked :P

**Comment by cbornet** [comment]
I don't see use cases where a LocalDateTime would be useful or better than a ZonedDateTime.

**Comment by jdubois** [comment]
OK, we can't support all available types, and LocalDateTime is very close to ZonedDateTime - I guess it's just a simple type refactoring.
So I don't think we should do it, and if you need it you use first a ZonedDateTime and then do the change.

**Comment by mrozlukasz** [comment]
Hi, In my opinion JHipster implementation should refer to the following specification implemented in a few latest versions: https://hibernate.atlassian.net/browse/HHH-8844 . I think that JHipster isn't implementing it's own data mappings, but should fit into official standards. 
All the best

**Comment by qlerebours** [comment]
Moreover, postgresql doesn't support ZonedDateTime:
`This is closely aligned with tables B-4 and B-5 of the JDBC 4.2 specification. Note that ZonedDateTime, Instant and OffsetTime / TIME [ WITHOUT TIMEZONE ] are not supported. Also note that all OffsetDateTime will instances will have be in UTC (have offset 0). This is because the backend stores them as UTC.`

https://jdbc.postgresql.org/documentation/head/8-date-time.html
