### ISSUE TITLE
Picking up localhost as the datasource URL even in prod profile when deploying in AWS

### ISSUE THREAD

**Issue by ARAtIntBitTech** [jhipster/generator-jhipster#3272]
Even though I built the project using the prod profile and have specified the AWS - RDS instance endpoint in the URL (accepts requests from all IP's), it still fails to deploy on EC2 stating failed to connect to localhost:5432.

> caused by: com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

JHipster is not changing the datasource url correctly.

> JHipster v2.27.2

```
{
  "generator-jhipster": {
    "baseName": "Hello",
    "packageName": "com.intbit.hello",
    "packageFolder": "com/intbit/hello",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

> Ubuntu 14.04.3 LTS

Not sure where its picking up the localhost. To test, I even changed the URL in the application-dev.yml as well, pointed it to the AWS - RDS instance.

**Comment by jdubois** [comment]
This is just for AWS, can you put the right title and détails of what you did?

**Comment by ARAtIntBitTech** [comment]
When the WAR for the prod profile is built. The datasource configuration should pick up the URL specified in application-prod.yml.

**Comment by jdubois** [comment]
This is because you don't run your application with the "prod" profile.
I don't see anything in the AWS sub-gen documentation concerning running in "prod" profile, so this is something we should improve.

**Comment by wuethrich44** [comment]
The RDS Instance doesn't run on localhost. The subgen set the correct url via environment variables. The `prod` profile is also set via environment variables. So if you want your custom datasource url you have to change the environment variable in AWS Management Console.

**Comment by jdubois** [comment]
Looks logical! Thanks !
