### ISSUE TITLE
npm install -g generator-jhipster - Not working in Mac fails at deasync

### ISSUE THREAD

**Issue by smartjaya** [jhipster/generator-jhipster#3274]
##### **Overview of the issue**

jhipster is not getting installed via NPM . It fails at deasync.
##### **Motivation for or Use Case** 

npm install -g generator-jhipster
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> deasync@0.1.4 install /usr/local/lib/node_modules/generator-jhipster/node_modules/deasync
> node ./build.js

  CXX(target) Release/obj.target/deasync/src/deasync.o
  SOLINK_MODULE(target) Release/deasync.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/deasync.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0

##### **Browsers and Operating System** 

Mac OS

Node - 5.0

**Comment by gmarziou** [comment]
This is not a jhipster issue, it's an issue with your node/npm environment, you should ask it on stackoverflow.

    ld: library not found for -lgcc_s.10.5

You probably need to install xcode.

Also you should consider installing an LTS version of node for more stability.

**Comment by smartjaya** [comment]
After installing the LTS version of the node , i am able to get the jhipster installed successfully.  With Node 5  I was facing the issue. Thanks for helping in resolving this issue.

**Comment by gmarziou** [comment]
You're welcome and don't hesitate to use stackoverflow

**Comment by jdubois** [comment]
Yes and we should document which version works, but that's really hard to do as it changes all the time.

**Comment by gmarziou** [comment]
@jdubois I think a safe position is to recommend the current LTS version (whatever it is at the moment where user installs jhipster), so I made this PR

https://github.com/jhipster/jhipster.github.io/pull/240

**Comment by jdubois** [comment]
Yes, and it's logical go have the LTS version

**Comment by gmarziou** [comment]
BTW, I can't accept PR s on jhipster/jhipster.github.io

**Comment by deepu105** [comment]
Just for FYI, latest node with latest npm also works without any issues for
me, but on windows so not sure if its exactly a node issue or just a
combination issue. But yes agree that we should recommend something that
surely works for majority
