### ISSUE TITLE
Logs Table in jhipster created UI is not responsive

### ISSUE THREAD

**Issue by kkorada** [jhipster/generator-jhipster#3276]
##### **Overview of the issue**
Logs Table in jhipster created UI is not responsive.

##### **Motivation for or Use Case** 
It is not adjusting according to the resolution

##### **JHipster Version(s)** 
it is same with 2.x or 3.x

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
NOT RELATED TO .yo-rc.json file

##### **Browsers and Operating System** 
Browser: Chrome 
OS: Windows 7

##### **Reproduce the error** 
run application and open logs page in administration menu, then resize the window ( to some tablet or mobile size) or open in chrome emulator.

##### **Suggest a Fix** 
class table-responsive is added in wrong tag in logs.html page.
try adding **table-responsive** in div which wraps it.
for eg: 
add it in `<div class="well table-responsive"> `

**Comment by gmarziou** [comment]
Would you please consider submitting a Pull Request?

https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by wmarques** [comment]
Thanks for your report, I'm fixing this

**Comment by kkorada** [comment]
i am getting error while pull
 
**requestremote: Permission to jhipster/generator-jhipster.git denied to kkorada.
fatal: unable to access 'https://github.com/jhipster/generator-jhipster.git/': The requested URL returned error: 403**

**Comment by deepu105** [comment]
You cannot push to master fork the repo and work on your fork and create a
PR. Check our contribution guidelines

**Comment by kkorada** [comment]
ok thank you
