### ISSUE TITLE
Update the Heroku generator to prompt for the Registry URL

### ISSUE THREAD

**Issue by jkutner** [jhipster/generator-jhipster#3279]
**NOTE:** I plan to do this work, but wanted to open the ticket so that others can see it is in progress and provide feedback.

##### **Overview of the issue**

The Heroku generator needs to detect when an app is a microservice (or gateway) and prompt for the production JHipster Registry URL.

##### **Motivation for or Use Case** 

Microservices won't work without it.

##### **JHipster Version(s)** 

3.x

**Comment by PierreBesson** [comment]
Very nice ! This is exactly what we need.
