### ISSUE TITLE
Adding new config to angular js is not working in modules

### ISSUE THREAD

**Issue by kkorada** [jhipster/generator-jhipster#3280]
##### **Overview of the issue**

addAngularJsConfig is not present in latest version of jhipster

##### **Motivation for or Use Case** 

without this it is not possible to add new configurations to the angular js modules

##### **JHipster Version(s)** 

v3.0.0

##### **Suggest a Fix** 

try adding a new needle like it was in before version in a new file app.config.js so that we can add any configs if needed while creation of modules.

eg `// jhipster-needle-angularjs-add-config JHipster will add new application configuration here`

**It should look something like this:**

`(function() {
    'use strict';

    angular
        .module('testappApp')
		// jhipster-needle-angularjs-add-config JHipster will add new application configuration here
		;
})();
`

**Comment by wmarques** [comment]
This was removed in #2986, you can add your own config by creating a config file in `src/webapp/app/blocks/config`.
