### ISSUE TITLE
Gateway has no Zuul routes configured

### ISSUE THREAD

**Issue by tomvanrossom** [jhipster/generator-jhipster#3281]
##### **Overview of the issue**

After generating a gateway, the `application.yml` file does not contain any Zuul routes. When running the application, any request return an empty page (200), and the logs contains: 
`o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator`

##### **Motivation for or Use Case** 

Shouldn't there be any routes configured for the gateway?

##### **JHipster Version(s)** 

3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

`{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "...",
    "packageName": "...",
    "packageFolder": "...",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "...",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "nl",
      "fr"
    ],
    "enableSocialSignIn": false
  }
}`

##### **Browsers and Operating System** 

Windows 10 - Chrome

##### **Reproduce the error** 

Startup the registry and generated gateway, go to localhost:8080

**Comment by jdubois** [comment]
No they are created when microservices register to the Registry.
You can of course still configure them manually, but with our default configuration the idea is that you don't have anything to do.

**Comment by tomvanrossom** [comment]
Thanks for the quick reply.

If Zuul is not the problem, then I need to figure out why I only see a blank page when accessing the gateway ...

**Comment by jdubois** [comment]
If you have a blank page with the gateway, then that's another issue, here you were asking about Zuul routes not being created.
Can you create a new ticket, with your exact configuration and stacktrace?

**Comment by imTachu** [comment]
I had the same error. The only thing I had was a warning: o.s.c.n.zuul.web.ZuulHandlerMapping : No routes found from RouteLocator. And when trying to load the app (the microservice-gateway) I had a blank page and it couldn't find any of my .js files... The solution: I had to perform a `npm update -g generator-jhipster` and then a `yo jhipster` and it automatically worked.

**Comment by gmarziou** [comment]
@imTachu have you tried running `bower install` manually before performing  a `npm update -g generator-jhipster` and then a `yo jhipster`?

**Comment by tomvanrossom** [comment]
In some occasions, the generated index.html, is completely empty. That is why I saw a blank page.

Running `gulp clean serve` fixed it.

**Comment by gmarziou** [comment]
Yes it could be due to some yeoman hiccups, in the worst case you may want to run manually
`npm install & bower install & gulp inject`
