### ISSUE TITLE
Documentation on microservices security is inaccurate.

### ISSUE THREAD

**Issue by jvence** [jhipster/generator-jhipster#3292]
Docs http://jhipster.github.io/microservices-architecture/ state that you must "remove the security on those URLs in the gateway’s SecurityConfiguration class." but that's not correct. You must update the microservice's MicroserviceSecurityConfiguration instead. No changes are needed in the gateway’s SecurityConfiguration  class.

**Comment by jdubois** [comment]
Oh yes the class name has changed.

**Comment by jvence** [comment]
Not only the class name but it states that changes must be made to gateway's SecurityConfiguration but it should be made to the microservices's

**Comment by wmarques** [comment]
I've done a PR to fix this on the jhipster.github.io repo (see above), thanks for the report @jvence
