### ISSUE TITLE
Upgrade to Spring Cloud RC 1

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3297]
See https://spring.io/blog/2016/03/24/spring-cloud-brixton-rc1-is-now-available

(Also needs to be done on the registry)

**Comment by PierreBesson** [comment]
I have made a PR for the registry (https://github.com/jhipster/jhipster-registry/pull/33).
Also I noticed something not right on the registry's docker hub: the v1.0.0 tag is getting updated along with master !
https://hub.docker.com/r/jhipster/jhipster-registry/builds/
