### ISSUE TITLE
Active state for Administartion Tab in UI is not working

### ISSUE THREAD

**Issue by kkorada** [jhipster/generator-jhipster#3298]
##### **Overview of the issue**

Administration tab in UI is not chainging its state to active when element in that menu is clicked

##### **Motivation for or Use Case** 

It's state should change to active when element in that menu is clicked.

##### **JHipster Version(s)** 

v3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

UI related

##### **Browsers and Operating System** 

same with chrome and IE.
Tested with Windows 7 OS

##### **Reproduce the error** 

1. Create a new application
2. Login into application
3. Click on any element in administration menu.

##### **Suggest a Fix** 

change the code in navbar.html
**FROM**
`<li ng-class="{active: vm.vm.$state.includes('admin')}"  ng-switch-when="true" has-authority="ROLE_ADMIN" uib-dropdown class="dropdown pointer">`
 
**TO**
`<li ng-class="{active: vm.$state.includes('admin')}"  ng-switch-when="true" has-authority="ROLE_ADMIN" uib-dropdown class="dropdown pointer">`

**Comment by deepu105** [comment]
@kkorada would you like to submit a PR to fix this?

**Comment by kkorada** [comment]
yes
