### ISSUE TITLE
[FEATURE] Generate REST clients with Hystrix circuit breaker and fallback on the gateway

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#3307]
Currently, microservices are accessible through the gateway and have their api accessible at `/app1/api/**`.

However if app1 becames unavailable, we should be able to provide a fallback and not throw errors.
This is provided by Spring Cloud using Hystrix circuit breakers and fallbacks and I'm proposing to integrate it in JHipster.

This is what it looks like:
![architecture](https://cloud.githubusercontent.com/assets/513471/14183048/7f095a16-f76e-11e5-8ec0-5c2f309839f4.png)

I have made a demo to demonstrate it: [PierreBesson/jhipster-circuit-breaker-demo](https://github.com/PierreBesson/jhipster-circuit-breaker-demo)

So my idea is that when creating a "microservice" entity on the gateway, we should have a new question that would allow to generate a REST client with a fallback rather than just setting up the route to the microservice calls.

I have used Netflix's Feign library to write REST clients. Currently, everything is working but there are still some issues to solve:

### Security

In my demo repo, I have disabled the microservice security on /api/** because REST calls needed to have the correct auth header.
Because we use JWT, we should add the correct JWT Header to our request. This is possible by writing a Feign RequestInterceptor similar to what has been done with OAuth2 (https://github.com/spring-cloud/spring-cloud-security/pull/75). I would appreciate help on this.

### DTO

Our REST client needs a DTO to receive the data, I think I will be able to reuse the DTO generation code that was written for Mapstruct, it worked fine for my foo and bar samples.

### Pagination

I don't know if pagination could be made to work across the gateway.

### Integration tests

If we are going to provide this kind to distributed code generation, we should write integration tests for it.

### Rest controllers generation on the gateway
In my demo I have written simple restControllers that make the API available on `/api/app1/foos` instead of the usual `/app1/api/foos`, then we will be able to generate the client side (it could be as an option).

Thank you in advance for your feedback.

ping @cbornet, this might be of interest to you
ping @jdubois

**Comment by gmarziou** [comment]
Have you read this about pagination?

https://github.com/spring-cloud/spring-cloud-netflix/issues/556

**Comment by cbornet** [comment]
That would be quite easy to generate with a swagger-codegen template. I can do one based on your sample

**Comment by jdubois** [comment]
Yes there is a clear need for this, some gateways can be more complex than simple routers (that's what I'm doing right now), and also having an intelligent fallback can be handy.
For pagination: we have our own system, I'm not sure we have that issue.

**Comment by cbornet** [comment]
Or do you prefer to generate with yeoman and the json entity files (this would limit the generation to the CRUD endpoints) ?

**Comment by deepu105** [comment]
@PierreBesson take a look at the ribbon part (Part 2: inter-service communication) in this article as well http://stytex.de/blog/2016/03/25/jhipster3-microservice-tutorial/ it looks good

**Comment by PierreBesson** [comment]
@cbornet I think for start I will generate it with yeoman and json entity files. But if you do the template for swagger, it would be great as it would go beyond CRUD and support both load balancing, circuit breaker and fallback ! Once you create the initial template, I will do some extensive testing on microservice.

But for now, we need to add the correct JWT token the REST client requests.

**Comment by PierreBesson** [comment]
@gmarziou Thanks for the link on the Pagination issue. I think it means that this will eventually be solved upstream.

**Comment by SebastienRene** [comment]
Great job Pierre, this "early" circuit breaker is interesting.
However the gateway souldn't do buisness treatment in fallback methods : "smart endpoints and dumb pipes".
The fallback sould be in the microservice, what do you thnink about it ?

**Comment by deepu105** [comment]
I was having the same thing in mind. Gateway shouldn't duplicate the server
side part of microservice entity rite?  Fallback should ideally be routed
to another node of the same microservice in my opinion

**Comment by gmarziou** [comment]
I'm not sure we can't put the fallback in the service itself because the service could be down but maybe it could be registered by the service in the Eureka registration metadata.

@deepu105 "Fallback should ideally be routed to another node of the same microservice" is already done by Ribbon. here I think the fallback is when there is no service available.

**Comment by gmarziou** [comment]
A common way to implement fallback is to use cached value from previous successful call.

**Comment by deepu105** [comment]
Oops sorry didn't look close enough, ok it makes sense

**Comment by PierreBesson** [comment]
@SebastienRene I think this kind of fallbacks would be mainly used on microservices that are calling other microservices and I agree that the dumb pipe way is better in many cases. But I don't see why it couldn't be done as well on the gateway.

I mostly had in mind the following fallbacks that could apply:
- for "read": retrieve a value from a cache
- for "write": send the posted data to a message queue that would wait for the service to come back up to forward it

**Comment by deepu105** [comment]
@PierreBesson I think @xetys has done exactly your approach in the link i pasted above and has a sample here https://github.com/xetys/jhipster-ribbon-hystrix may be you guys should work together on this

**Comment by xetys** [comment]
when my upcoming PR rolls out of my pipeline there will be sure a lot to do, where I will need help from you. The PR contains springs solution of JWT authorization via oauth, so there will be an option for a extremely fine-grained security, such as granting special privileges on resources, when the requests are coming from a micoservice, rather than from the angular app.

for the use of circuit breaker and ribbon there should be a seperate sub-generator, generating services similar to the entity generator for microservices in gateway, to generate the UI....so this generator would create the entity clients inside consuming APIs from other services. 

I got a plan for this, but need more hands then 2 :-)

**Comment by gmarziou** [comment]
I would drop the "write" part as it is very hard to get it right in a generic way.

For instance, if you wait too long in queue, client may timeout and retry depending on how it is configured which could become messy.

**Comment by PierreBesson** [comment]
@xetys Your PR is great. I agree that we should work on this in priority. I will be available to help you starting on monday. I am definitly following you here as you have more experience than I do.

**Comment by xjiaoyang** [comment]
@PierreBesson what's going on this PR, are you working on?

**Comment by PierreBesson** [comment]
@xjiaoyang yes, but it's on hold as we are waiting for the integration of the uaa (oauth server) as a 4th type of application as this solution will need to be compatible with this.

**Comment by jdubois** [comment]
As discussed with @PierreBesson I'm closing this for lack of interest.
