### ISSUE TITLE
Login Redirection

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#3311]
##### **Overview of the issue**
Login should send the user to the home state when logging in from certain states (reset/activate/register).
##### **Motivation for or Use Case** 
Better user flow.  When the login dialog closes, the user should not remain on the register/reset/activate states.
##### **JHipster Version(s)** 
3.0.0 ([2.x has something similar](https://github.com/jhipster/generator-jhipster/blob/v2.x_maintenance/app/templates/src/main/webapp/scripts/app/account/login/_login.controller.js#L18))
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "loginflow",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "394fdb632f574065aad9a9aaef0dfc0538b11560",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
No entities required
##### **Browsers and Operating System** 
All
##### **Reproduce the error** 
Go to register state and login.  You will find yourself back on the register state.
##### **Suggest a Fix** 
I use the following in LoginController.  Is there a better way?
```javascript
if($state.current.name === 'register' 
    || $state.current.name === 'activate' 
    || $state.current.name === 'finishReset' 
    || $state.current.name === 'requestReset'){ 
                $state.go('home')
}
```
Will gladly send a PR.

**Comment by wmarques** [comment]
This solution looks good to me
