### ISSUE TITLE
Login Dialog Register Link

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#3312]
##### **Overview of the issue**
The 'register' link on the login dialog is overwritten by the translation text in the global.json.  This changes it from calling the register function in LoginController to just using ui-sref to change to the register state.  The issue is the dialog stays open while the register state appears in the background.
##### **Motivation for or Use Case** 
The register link should close the login dialog after taking them to the register form, otherwise the user might not realize the background state changed.
##### **JHipster Version(s)** 
3.0.0
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "loginflow",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "394fdb632f574065aad9a9aaef0dfc0538b11560",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
N/A
##### **Browsers and Operating System** 
All
##### **Reproduce the error** 
Generate an application with translation enabled.
Click Sign In
Click the Register Link on the Login Dialog
The dialog remains open but the state changes to register
##### **Suggest a Fix** 
The two possible routes I see are:
- Copy the register translation to login.json but change the new copy to use ng-click instead of ui-sref
- Replace the ui-sref in the global registration translation to ng-click=vm.register and add register to home controller

**Comment by deepu105** [comment]
Oh Ok now I understand the issue. I guess your second solution you did in the other PR was ok sorry for misunderstanding earlier.

**Comment by wmarques** [comment]
+1 solution 2
Can you PR this ? I can do it if you want.
