### ISSUE TITLE
Wrong path location in gateway access denied error

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3314]
##### **Overview of the issue**

Setup:
- registry
- gateway on port 8080
- srv1 microservice

When calling a proxified api of srv1 through gateway on `/srv1/api/logs` without a JWT token, I get an expected 403 error but the "path" property is `/api/logs` while it should be '/srv1/api/logs`

~~~
curl -X GET --header 'Accept: application/json' 'http://127.0.0.1:8080/srv1/api/logs'
~~~

~~~json
{
 "timestamp":"2016-04-01T13:39:49.220+0000",
 "status":403,
 "error":"Forbidden",
 "message":"Access Denied",
 "path":"/api/logs"
}
~~~

##### **Motivation for or Use Case** 

I'm not sure of the effect but I know that some angular interceptors may depend on the path like our [errorhandler.interceptor.js](https://github.com/jhipster/generator-jhipster/blob/e51b764ff8b32989c299cf426c5ae737413ea44d/generators/client/templates/src/main/webapp/app/blocks/interceptor/_errorhandler.interceptor.js#L18)

##### **JHipster Version(s)** 

3.0 today's master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

Default options of a gateway:

~~~json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "8236c1377cd345f2a83c41efbd726577389066a1",
    "useSass": false,
    "enableTranslation": false,
    "applicationType": "gateway",
    "testFrameworks": [],
    "enableSocialSignIn": false,
    "serverPort": 8080,
    "jhiPrefix": "jhi"
  }
}~~~


##### **Suggest a Fix** 

Not sure, need to investigate more.

**Comment by jdubois** [comment]
Same issue if an entity is created on the gateway, its "location" header does not have the microservice prefix.

This is normal, has nothing has been coded here: we need to add a new Zuul filter, or maybe modify an existing one, to add this prefix to the "Location" headers.

**Comment by jdubois** [comment]
For the "Location" header, when creating an entity, there is an even easier solution: use a relative URL.
Since RFC 7231 this is allowed, and of course it would work anywhere.

For this "Path", which is in fact in the body of the message, it looks like it's intended to be absolute. If it was supposed to be a relative URL, it would always be "", as the error is on the URL we just called. So I'm wondering if it's good to rewrite it.

**Comment by jdubois** [comment]
This is in process of being handled by Spring Cloud Netflix:

https://github.com/spring-cloud/spring-cloud-netflix/issues/8

It looks more logical to me to let Spring Cloud Netflix solve this, as indeed that's an issue at the Zuul level, and not specific to JHipster.
