### ISSUE TITLE
Set MariaDB as datasource.

### ISSUE THREAD

**Issue by flanciskinho** [jhipster/generator-jhipster#3315]
##### **Overview of the issue**

jhipster don't show the option to use MariaDB as datasource. 

##### **Motivation for or Use Case** 

I wanted use MariaDB as a datasource to personal project and jhipster don't configure it. I had to set parameters manually 

##### **JHipster Version(s)** 

3.0.0

##### **Browsers and Operating System** 

All

##### **Suggest a Fix** 

Add the follow content to jhipster.github.io on Tips'n tricks:

change application-dev.yml and application-prod.yml (src/main/resources/config/liquibase) this values:

	url: jdbc:mariadb://localhost:3306/${DBNAME}
	
	database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

and add jdbc driver on pom.xm (see the last version on https://mariadb.com/kb/en/mariadb/about-mariadb-connector-j/)

	<dependency>
	   <groupId>org.mariadb.jdbc</groupId>
	   <artifactId>mariadb-java-client</artifactId>
	   <version>xxx</version>
	</dependency>

**Comment by pascalgrimaud** [comment]
Can you do a PR, as tips'n tricks to https://github.com/jhipster/jhipster.github.io ?
It can be interesting to mention the official docker repo too : https://hub.docker.com/_/mariadb/

**Comment by deepu105** [comment]
Yes plz add to the documentation repo as a PR
