### ISSUE TITLE
CORS fails in microservice environment

### ISSUE THREAD

**Issue by jvence** [jhipster/generator-jhipster#3318]
I've enabled CORS on the microservice & on both gateway and microservice but kept getting a 403 error as below. I can successfully access the service via the browser but fails when done via an AJAX based- app. I ran the gateway & microservice directly from the executable WAR file.

```
cors:
allowed-origins: ""
allowed-methods: GET, PUT, POST, DELETE, OPTIONS
allowed-headers: ""
exposed-headers:
allow-credentials: true
max-age: 1800
```

response header for OPTIONS preflight call:

> HTTP/1.1 403 Forbidden
> Server: Apache-Coyote/1.1
> X-Application-Context: HPGateway:dev:8082
> Allow: GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH
> Content-Length: 20
> Date: Fri, 01 Apr 2016 11:38:13 GMT

here's my config:

```
{
"generator-jhipster": {
"jhipsterVersion": "3.0.0",
"baseName": "HPWebServices",
"packageName": "com.company",
"packageFolder": "com/company",
"serverPort": "8084",
"authenticationType": "jet",
"hibernateCache": "no",
"databaseType": "mongodb",
"devDatabaseType": "mongodb",
"prodDatabaseType": "mongodb",
"searchEngine": "no",
"buildTool": "maven",
"jwtSecretKey": "xxxxxx",
"enableTranslation": true,
"applicationType": "microservice",
"testFrameworks": [
"gatling"
],
"skipClient": true,
"skipUserManagement": true,
"nativeLanguage": "en",
"languages": [
"en",
"fr"
]}}
```

**Comment by gmarziou** [comment]
> "authenticationType": "jet",

What's this? It should be "jwt"

**Comment by jvence** [comment]
It is jwt but was autocorrected by the browser

**Comment by gmarziou** [comment]
Thanks for having clarified.

Have you read #3237?

**Comment by jvence** [comment]
Yes I have read it and it's a different version, running a monolithic app and having problems with oauth calls. This is quite different.

**Comment by cbornet** [comment]
I guess your allowed-origin is "*", not "". Same for your allowed-headers ?

**Comment by jvence** [comment]
Yes "*" on both. Copy and paste messed up somehow.

**Comment by cbornet** [comment]
The response body contains "Invalid CORS request" which comes from [here](https://github.com/spring-projects/spring-framework/blob/v4.2.5.RELEASE/spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java#L110). Could you try setting a breakpoint and check how you got there ? And also understand who rejected : the gateway or the app ?

**Comment by jvence** [comment]
@cbornet I was able to find the problem (but not sure of the solution). The pre-flight rejection occurs at the gateway and not on the microservice. It fails because the CorsConfiguration config==null in DefaultCorsProcessor. The CorsFilter is initialized with the correct CorsConfigurationSource configSource (as specified in the application.yml) - Somehow the configuration is not passed along to Spring's DefaultCorsProcessor.

It fails in DefaultCorsProcessor's processRequest:
`
boolean preFlightRequest = CorsUtils.isPreFlightRequest(request);
		if (config == null) {
			if (preFlightRequest) {
				rejectRequest(serverResponse);
				return false;
			}
			else {
				return true;
			}
		}
`

**Comment by gmarziou** [comment]
> The CorsFilter is initialized with the correct CorsConfigurationSource configSource (as specified in the application.yml)

Is it really application.yml in src/main/resources/config gateway's folder or is it from the registry environment repository? Or even bootstrap.yml?

**Comment by jvence** [comment]
@gmarziou Not sure actually but I know that CorsFilter(CorsConfigurationSource configSource) is initialized with the correct parameters specified in WebConfigurer.corsFilter() which read the config from application.yml

**Comment by jvence** [comment]
Ok I solved the problem. The issue is that we need to specify the url for the microservice in the gateway's corsFilter configuration. So this is what the code in WebConfigurer should look like:

`
    @Bean
    public CorsFilter corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = jHipsterProperties.getCors();
        if (config.getAllowedOrigins() != null && !config.getAllowedOrigins().isEmpty()) {
            source.registerCorsConfiguration("/microservice1/api/**", config);
            source.registerCorsConfiguration("/api/**", config);
            source.registerCorsConfiguration("/v2/api-docs", config);
            source.registerCorsConfiguration("/oauth/**", config);
        }
        return new CorsFilter(source);
    }
`

**Comment by cbornet** [comment]
@jvence so it seems the CORS filter on the microservice actually works but if you don't configure the one on the gw, you get a rejection by the gw. This is not right : if no CORS is configured on the GW, the GW shouldn't reject. Could you try to remove/comment the code for the CORS filter on the GW and activate the filter on the micro service only and see if that works ?

**Comment by jvence** [comment]
@cbornet I tried that already (see comment 1 above). The CORS service on the microservice is never called because the call is blocked by the gw.

**Comment by cbornet** [comment]
@jvence I don't see why the gw would block the call if you completely remove the filter (not just disable in conf but completely remove the code in WebConfigurer.java)

**Comment by cbornet** [comment]
The PR should fix the issue when you don't configure the cors on the GW and configure it on the micro-services.
@jvence As for configuring globally on the GW, can you check if ```source.registerCorsConfiguration("/*/api/**", config);``` works ? This would make a generic solution independant of the microservices names.
