### ISSUE TITLE
Microservice API 403 error, JWT Invalid Signature on newly generated app

### ISSUE THREAD

**Issue by bojanraic** [jhipster/generator-jhipster#3322]
##### **Overview of the issue**

API call from Swagger UI for a microservice API endpoint results in a 403 error. 
JWT was generated and included in the header as  'Authorization: Bearer <JWTString>'

Generated token parses fine, header and payload info looks fine. But the signature seems to be invalid and 403 is thrown. 

API Request via SwaggerUI: 

`curl -X GET --header 'Accept: text/html' --header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTQ2MjE3Njg3OH0.Ds8sQN0W9yp2vK2SSRfc_48MrtBwsS_USQ35P6kQ0my8BNMMWY7rOpKrCydPYJUNMaW7jwjvU0lMy9ndLrUVTg' 'http://127.0.1.1:8080/msapp01/api/customers'`

Response (without text/html header): 

`{"timestamp":"2016-04-02T07:56:52.063+0000","status":403,"error":"Forbidden","message":"Access Denied","path":"/api/customers"}`

Are additional steps or extra configuration needed to get JWT auth to work? 

##### **JHipster Version(s)** 

3.0
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

`{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "msapp01",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "b4adafb432dd3f4562687224261e9e8cbc51ddb7",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}`

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

`{
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": "2",
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldName": "birthdate",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20160402064549",
    "dto": "no",
    "service": "no",
    "entityTableName": "customer",
    "pagination": "no",
    "microserviceName": "msapp01",
    "searchEngine": "elasticsearch"
}`

##### **Browsers and Operating System** 

Ubuntu 15.10 & Chrome 49

##### **Reproduce the error** 
- Create a MS app and an entity
- Create a MS gateway for the MS app
- Start JHipster Registry
- Log into the gateway as admin
- Go to Swagger UI for the MS app
- Try to access an endpoint for the generated entity
- Confirm that the JWT string was passed in the request header
- Used several online tools to verify the JWT token (parsed fine, signature invalid)

1. https://kjur.github.io/jsrsasign/tool_jwtveri.html
2. https://jwt.io/
3. https://py-jwt-decoder.appspot.com/

**Comment by jvence** [comment]
Did you make sure to share your gateway token with all microservices. This worked for me.

**Comment by jdubois** [comment]
Did you follow the documentation, on the JWT token? You need to have the same secret key on all servers.

**Comment by bojanraic** [comment]
Thanks for the quick reply. So if I am understanding this correctly, I should take the secret key from gateway and paste it into microservice's application.yml? I will try and reply later today. 
Maybe this step can be a user prompt when creating a microservice.

**Comment by jdubois** [comment]
Or it should come from the JHipster Registry

**Comment by gmarziou** [comment]
Maybe we should add more instructions in the docs and at least a link to [spring cloud config server documentation](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html), the first way which is to copy the secret in all app's application-*.yml and the second way which is to share it through the registry are probably not detailed enough.

Personally, I prefer the second one and I would not even mention the first way because it's probably not what you will end up with in production. 

Having it defined in one place allows you also to use environment variables to not store it in git repo which is probably what people would do in a cloud hosting  or [cipher it](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_security) if you want to store it in the git repo.

So the instructions could be: 

- You should have a different key in development and production. 
- You should share the key by copying it into the [registry's environment's repository](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_environment_repository)  as `jhipster.security.authentication.jwt.secret` property in global `application-dev.yml` and `application-prod.yml`. These shared yml files are the ones in your native or git-based environment repository not in the `src/main/resources/config` folder of the registry itself.

I also think that in dev profile we should catch JWT invalid signature execption and suggest to read this part of our doc.

**Comment by bojanraic** [comment]
I can verify that after using gateway's secret in microservice app, everything worked as expected. Thanks to @jvence, @jdubois, @gmarziou for tips on this. 
I definitely agree with Gael on providing a few more instructions for beginners in the docs. 
In development though, to get things going quickly, one would think most folks would copy the gateway secret to all app(s). 
Perhaps there could be an extra prompt in the generator asking for the secret (to set this up more quickly). 
That said, this issue can be considered as closed.
Thanks again for your help and suggestions.

**Comment by jdubois** [comment]
I thought this was already sent by the JHipster Registry automatically, by default, but I need to check this.

**Comment by deepu105** [comment]
Yes its sent by registry automatically when we use the docker-compose sub
gen to generate a setup and run in docker. Not sure if it works if you run
things manually

**Comment by rjain-pivotal** [comment]
1. Created in the registry's environment's (central-config/application.yml, application-dev.yml and application-prod.yml)
2. Copied in all the three files  jhipster.security.authentication.jwt.secret

E.g. 

configserver:
    name: JHipster Sample Spring Cloud Config
    status: ${spring.cloud.config.uri}/${spring.cloud.config.label}/${spring.cloud.config.name}-${spring.cloud.config.profile}.yml/
    jhipster.security.authentication.jwt.secret: "8b1f3142324a44623588d9ce3d1b79e0fd1bc244"

3. Copied the same token to the gateway and microservices .yo-rc.json

4. Started the registry, gateway and microservice (mvn) 
5. I still get "Access Denied" 

I am clearly missing something. 

Thanks for your help.

**Comment by gmarziou** [comment]
Yes you copied the key under configserver: , it should be like this

~~~
configserver:
    name: JHipster Sample Spring Cloud Config
    status: ${spring.cloud.config.uri}/${spring.cloud.config.label}/${spring.cloud.config.name}-${spring.cloud.config.profile}.yml/

jhipster.security.authentication.jwt.secret: "8b1f3142324a44623588d9ce3d1b79e0fd1bc244"
~~~
or using indentation

~~~
configserver:
    name: JHipster Sample Spring Cloud Config
    status: ${spring.cloud.config.uri}/${spring.cloud.config.label}/${spring.cloud.config.name}-${spring.cloud.config.profile}.yml/

jhipster:
    security:
        authentication:
            jwt:
                secret: "8b1f3142324a44623588d9ce3d1b79e0fd1bc244"
~~~

**Comment by rjain-pivotal** [comment]
worked, when I had the config with the indentation
jhipster:
    security:
        authentication:
            jwt:
                secret: "8b1f3142324a44623588d9ce3d1b79e0fd1bc244"

Thanks

**Comment by gmarziou** [comment]
@rjain-pivotal then please accept my answer on SO
