### ISSUE TITLE
Setting up Ribbon's Connection timeout in microservice environment

### ISSUE THREAD

**Issue by jvence** [jhipster/generator-jhipster#3323]
I'm trying to configure the gateway's zuul connection timeout and have added the ConnectTimeout parameter to the gateway's application.yml The ConnectTimeout timeout seems to be ignored. We need a way to specify this parameter. 

```
ribbon:
    eureka:
        enabled: true
    ConnectTimeout: 30000
    ReadTimeout: 30000
```

One of my microservices is slow to return a response (and that's ok) so I'm seeing lots of error in the gateway log:

```
Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: hpwebservices timed-out and no fallback available.
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:806)
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:790)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:99)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1521)
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1411)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:314)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:306)

```

**Comment by gmarziou** [comment]
Please use stackoverflow for this kind of question as this is not a jhipster issue, it's a spring cloud configuration issue.
I did solve this at work on Thursday but I l aready forgot, your ribbon config is not at the right place I think it should be under zuul or something, if you don't find I will tell you on stackoverflow on Monday.

**Comment by gmarziou** [comment]
Here is what I use to get it work:

https://github.com/spring-cloud/spring-cloud-netflix/issues/321

**Comment by gmarziou** [comment]
Here is my config, maybe we should consider adding to generated yml files.

~~~yml
zuul:
    host:
        connect-timeout-millis: 5000
        socket-timeout-millis: 10000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000
~~~

**Comment by PierreBesson** [comment]
@gmarziou, if you found them to be useful in preventing issue, I would trust your judgment here, please submit those properties as PR.

More generally, It would be useful to set gateway's properties to their default values, so that people can easily find them. 

For example, these were very important to tweak during our stress tests.
zuul.host.max-total-connections: 200
zuul.host.max-per-route-connections: 20

**Comment by gmarziou** [comment]
I'm not suggesting to use my values (they are specific to my project).

Like you zuul settings, I'm suggesting that we put default values and some comments so that users know what to adjust when they get timeout exceptions.

**Comment by pkrishanth** [comment]
@gmarziou that has saved my time

**Comment by pm0202** [comment]
this is worked for me ... 
https://github.com/spring-cloud/spring-cloud-netflix/issues/321

**Comment by vspdontukurthi** [comment]
Just add below snippet at application.yml where located at gatway-ms that works perfect 

ribbon:
    eureka:
        enabled: true
    connection-timeout: 3000
    ReadTimeout: 60000
# See http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html
zuul: # those values must be configured depending on the application specific needs
    host:
        max-total-connections: 5000
        max-per-route-connections: 10000
        connect-timeout-millis: 5000
        socket-timeout-millis: 60000
    semaphore:
        max-semaphores: 500

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 30000

**Comment by cristianobombazar** [comment]
@vspdontukurthi in my case, ribbon.ReadTimeout solve the problem. Thanks!

**Comment by jsm174** [comment]
We had this issue too. One of our microservices was taking ~3 seconds to complete, so 90% of the time we would get the timeout error even though the service completed successfully. 

Out of the box, Ribbon's `ReadTimeout`, and `ConnectTimeout` are both `1000`. These values are found in [RibbonClientConfiguration.java](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-ribbon/src/main/java/org/springframework/cloud/netflix/ribbon/RibbonClientConfiguration.java#L70)

The Ribbon timeout is calculated in [AbstractRibbonCommand.java](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/support/AbstractRibbonCommand.java#L134):

`ribbonTimeout = (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);`

`maxAutoRetries` and `maxAutoRetriesNextServer` values are found in [DefaultClientConfigImpl.java](https://github.com/Netflix/ribbon/blob/master/ribbon-core/src/main/java/com/netflix/client/config/DefaultClientConfigImpl.java#L121-L123)

I updated our gateway's `application.yml` and added:

```
ribbon:
    ReadTimeout: 4000
```

This keeps the `ribbonTimeout` calculation at `10000` which matches the value of `hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds`.

(4000 + 1000) * (0 + 1) * (1 + 1)

This avoids receiving errors like this:

`gateway-app_1 | 2018-11-14 15:54:36.072 WARN 1 --- [ XNIO-2 task-16] o.s.c.n.z.f.r.s.AbstractRibbonCommand : The Hystrix timeout of 10000ms for the command microservice is set lower than the combination of the Ribbon read and connect timeout, 12000ms.`

Finally, the Ribbon property names are case sensitive, ie `ReadTimeout`, not `read-timeout`, or `readTimeout`.

**Comment by PierreBesson** [comment]
@jsm174 You are welcome to contribute this information to the docs, it would be very useful to document the Spring Cloud stack defaults. Please open PR to https://github.com/jhipster/jhipster.github.io if you can.

**Comment by jsm174** [comment]
@PierreBesson I can do that. Where would the best place to put this?

**Comment by PierreBesson** [comment]
https://github.com/jhipster/jhipster.github.io/blob/master/pages/microservices-in-production.md

**Comment by lakith** [comment]
@vspdontukurthi Your solution worked perfectly. Thank you

**Comment by cmyker** [comment]
> Just add below snippet at application.yml where located at gateway-ms that works perfect
> 
> ```yaml
> hystrix: 
>   command: 
>     default: 
>       execution: 
>         isolation: 
>           thread: 
>             timeoutInMilliseconds: 30000
> ribbon: 
>   ReadTimeout: 60000
>   connection-timeout: 3000
>   eureka: 
>     enabled: true
> zuul: 
>   host: 
>     connect-timeout-millis: 5000
>     max-per-route-connections: 10000
>     max-total-connections: 5000
>     socket-timeout-millis: 60000
>   semaphore: 
>     max-semaphores: 500
> ```

```yaml
ribbon: 
  ReadTimeout: 60000
  ConnectTimeout: 3000
```
