### ISSUE TITLE
regenerating a microservice entity in a gateway application creates entity in gw

### ISSUE THREAD

**Issue by srnm** [jhipster/generator-jhipster#3330]
I'm still learning the corner-cases of the generators, but here's one that creates a problem if you generate the UI for a microservice entity in a gateway app, and later want to update the entity and the UI:

1. generate a microservice entity
2. generate ui in gateway app for microservice entity
3. re-generate entity in gateway app

The gateway app has no liquibase/domain/dto files for the microservice entity after step 2.
But these files appear after step 3.

**Comment by deepu105** [comment]
Could be a bug, will take a look when I find time. PR is welcome as well.

**Comment by jdubois** [comment]
Yes this is an issue !!! I also wanted to report it.

**Comment by jdubois** [comment]
Ping @wmarques on that one -> I think we should store in the json file that the entity was generated from a microservice (and store the name of that microservice so we can re-generate the correct URL in the service)
That will be useful also for doing your tutorial, as you will want to re-generate your gateway when testing

**Comment by wmarques** [comment]
Oh didn't see that, I'm checking this thanks for the report.
