### ISSUE TITLE
Enchancement : use ReflectionToStringBuilder.toString method for toString() method in generated code

### ISSUE THREAD

**Issue by fraf** [jhipster/generator-jhipster#3332]
I generated an entity named "Client".
The generated code was :

```
 @Override
    public String toString() {
        return "ConnexionEbicsDTO{" +
            "id=" + id +
            ", hostId='" + hostId + "'" +
            ", partnerId='" + partnerId + "'" +
            ", userId='" + userId + "'" +
            ", etatAbonnement='" + etatAbonnement + "'" +
            ", formatEnvoi='" + formatEnvoi + "'" +
            ", formatReception='" + formatReception + "'" +
            '}';
    }
```

I can be easily replace by :

```

 @Override
    public String toString() {
    	ReflectionToStringBuilder.toString(this);
    }
```

Note : I don't know if there is an equivalent in Guava librairy

**Comment by gmarziou** [comment]
I guess this was already discussed in another issue and the bottom line we don't want to use reflection for toString() as it can have some bad impacts on performance and also on hibernate lazy loaded fields.

**Comment by fraf** [comment]
You're right for lazy loading. But this kind of log is only for debug doesn't it ?
In this case, we don't care of performance.

**Comment by gmarziou** [comment]
toString() is also used by slf4j for logging
