### ISSUE TITLE
language generator broken

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#3334]
##### **Overview of the issue**

Executing ``yo jhipster:langauges`` results in 

```bash
Languages configuration is starting
identical src/main/webapp/app/components/language/language.constants.js
[21:45:01] Using gulpfile ~/workspace/tests/27-mono/gulpfile.js
[21:45:01] Starting 'wiredep:test'...
[21:45:01] Starting 'wiredep:app'...
[21:45:01] Finished 'wiredep:test' after 102 ms
[21:45:01] Finished 'wiredep:app' after 91 ms
[21:45:01] Starting 'wiredep'...
[21:45:01] Finished 'wiredep' after 14 μs
```

##### **Motivation for or Use Case** 

You can't add additional languages

##### **JHipster Version(s)** 

3.0.0 (and in current master)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

All defaults (monolithic app, maven)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

No Entities

##### **Browsers and Operating System** 

* ArchLinux
* Node v5.10.0
* Npm 3.8.5

**Comment by pascalgrimaud** [comment]
@atomfrede : not only latest master, it's v3.0.0

**Comment by atomfrede** [comment]
@pascalgrimaud Thanks, added the version information.

**Comment by wmarques** [comment]
I'm checking this

**Comment by atomfrede** [comment]
What happens if the user has not selected ``i18n``? I don't know if the subgen checks this before and fails with an error.

**Comment by andidev** [comment]
@wmarques 
The language generator should not ask for languages if the languages is provided as arguments. This is so that the client subgenerator can install languages. 

@atomfrede
I don't think we do any checks for that. At least I did not think of it.

**Comment by wmarques** [comment]
@andidev Oh ok, but it seems that it always pass in the if block, so even if I run the subgenerator without arguments it doesn't ask me for the languages. I'll try to fix this

**Comment by andidev** [comment]
I think currentLanguages needs to be removed from the if expression.
