### ISSUE TITLE
JWT secret should be configured only in application-dev.yml

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3335]
##### **Overview of the issue**

In microservices apps, `jhipster.security.authentication.jwt` is currently configured in `application.yml`.
As we want to encourage using a different secret for dev and prod, it should be configured in `application-dev.yml`from value generated in `.yo-rc.json` and empty in `application-prod.yml`

##### **JHipster Version(s)** 

3.0

**Comment by jdubois** [comment]
Or maybe use a fixed token like "my-secret-token" in dev, and keep the random String we currently have for production only?

**Comment by gmarziou** [comment]
Good idea, this way services and gateway would work immediately in dev

**Comment by jdubois** [comment]
I'm doing this, but anyway in our default config this should be configured through the JHipster Registry.

**Comment by jdubois** [comment]
I'm doing the same thing for the session-based authentication secret key. For the OAuth2 secret key, there is currently no generated random token: as I don't know this very well, I'm leaving it as it is today.
