### ISSUE TITLE
Gateway should not proxy to microservice when token is missing

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3336]
##### **Overview of the issue**

When calling a microservice resource through gateway without a JWT token, the request is passed to microservice app that rejects it.
The request should be rejected by gateway.

##### **Motivation for or Use Case** 

The purpose of the gateway is to protect the backend services from being accessed by unauthorized users even though the issue is minor because it's correctly handled by service.

##### **JHipster Version(s)** 

3.0 current master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

~~~json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "srv1",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "gradle",
    "jwtSecretKey": "9e8cd328e801969f97707b842cfd468993aac613",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false,
    "jhiPrefix": "jhi"
  }
}
~~~

##### **Reproduce the error** 

~~~
curl -X GET --header 'Accept: application/json' 'http://127.0.0.1:8080/srv1/api/books'
~~~

##### **Suggest a Fix** 

Add folowling lines to `SecurityConfiguration` for gateway only:

~~~java
            .antMatchers("/swagger-resources").permitAll()
            .antMatchers("/").permitAll()
            .anyRequest().authenticated()
~~~

It could have been simpler with a prefix for proxified service URLs.

**Comment by sdoxsee** [comment]
It would be safer if the token weren't in the angular app ( browser) at all and it was added to the request server-side. With the oauth2 implementation this shouldn't be a problem since the gateway will add the token and the browser only uses a session cookie.

**Comment by gmarziou** [comment]
I'm not sure to understand your comment, if the token was not in angular app, it seems to me that we would need to hold an http session on gateway, right?

**Comment by sdoxsee** [comment]
Yes, that's my understanding.

**Comment by gmarziou** [comment]
But we want the gateways to be stateless.

**Comment by sdoxsee** [comment]
I guess we want the gateways to be stateless because we want to allow
multiple replicated gateways without the complexity of coordinating them
with hazelcast clustered http sessions or 'sticky sessions'. That's fair.
The angular spring oauth2 tutorial uses sessions (which is something that I
think is still on the roadmap). I might make sense to provide these two
alternative ways of handing gateways. If a stateless gateway is the goal
here then I think your suggestion to stop the request at the gateway is
good. I was just wanting to avoid extra coding for something that wouldn't
happen in a (safer?) session scenario.
