### ISSUE TITLE
stateParams missing after redirect from login page

### ISSUE THREAD

**Issue by gbrehmer** [jhipster/generator-jhipster#3345]
##### **Overview of the issue**
When accessing e.g. an entity detail page, where stateParams are available/required (e.g. the entity id), those params are lost, if user is not authenticated and must login first to access the page. The resulting url after successful login has no url param set and detail page can not load the required data (e.g. /entity/ instead of /entity/1). Root cause is that the used variable name for stateParams in the auth.service.js  is wrong (different to variable name in app.js)

##### **JHipster Version(s)** 

latest / master branch

##### **Suggest a Fix** 

replace '$rootScope.previousStateNameParams' with '$rootScope.previousStateParams' in auth.service.js (two matches)

**Comment by gmarziou** [comment]
Thanks, could you please consider submitting a PR?
