### ISSUE TITLE
Adding entity to gateway forgets to inject bower deps into index.html

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3346]
##### **Overview of the issue**

I created a new microservice named timeEntry with one Entity "timeEntry". 

After that i created a new gateway application, linked to the "timeEntry" Entity in the microservice and try to start it via mvn spring-boot:run. The browser console showed many javascript errors like "undefined angular".

##### **Motivation for or Use Case** 

Gateway App does not start

##### **JHipster Version(s)** 

3.0 master as of today

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

Gateway

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "companyGateway",
    "packageName": "com.company.gateway",
    "packageFolder": "com/company/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "verySecret",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

```
{
    "relationships": [],
    "fields": [
        {
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldName": "date",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "hours",
            "fieldType": "Integer"
        }
    ],
    "changelogDate": "20160324200647",
    "dto": "no",
    "service": "serviceClass",
    "entityTableName": "time_entry",
    "pagination": "no",
    "microserviceName": "timeEntry",
    "searchEngine": "no"
}
```

##### **Possible solution**

The entity sub generator runs only `gulp inject` which does not insert bower dependencies.
Either `gulp inject`should include wiredep or the generator should also call  `gulp wiredep`

**Comment by deepu105** [comment]
But generating a gateway should have already run gulp install which calls
wiredep and all required steps. gulp inject is called to add only newly
created js files. So the issue seems to be something else. When you
generated the gateway fisrt without any entities did it work?

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
I couldnt reproduce this, it works fine for me on windows. is there anything you did differently or this could be random issue similar to the protractor tests failing

**Comment by gmarziou** [comment]
I'll try again and let you know.

**Comment by deepu105** [comment]
@gmarziou were you ableto reproduce?

**Comment by gmarziou** [comment]
I can't for the moment as I'm away from my main laptop, so I'm closing it until I can work on it.
