### ISSUE TITLE
Microservices application with JHipster Cloud Registry does not work on Cloud Foundry

### ISSUE THREAD

**Issue by rjain-pivotal** [jhipster/generator-jhipster#3347]
##### **Overview of the issue**
Pushing a microservices app with JHipster Spring Cloud Registry doesn't work on Cloud Foundry

##### **Motivation for or Use Case** 

Followed the instructions in the documentation, maybe there is a missing step. 

##### **JHipster Version(s)** 

3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "firstms",
    "packageName": "com.example.demo",
    "packageFolder": "com/example/demo",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "8b1f3142324a44623588d9ce3d1b79e0fd1bc244",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}

##### **Reproduce the error** 

1. First push the jhipster spring cloud registry/config server app
    This works
   ./mvnw package -DskipTests -Pprod
  cf push -f ./deploy/cloudfoundry/manifest.yml -p target/*.war

2. Second push the gateway. It fails
 ./mvnw package -DskipTests -Pprod
 cf push -f ./deploy/cloudfoundry/manifest.yml -p target/*.war

3. Third push the microservice. It fails
   ./mvnw package -DskipTests -Pprod
  cf push -f ./deploy/cloudfoundry/manifest.yml -p target/*.war

##### **Suggest a Fix** 

I believe the Spring Cloud Registry has to be bound in the manifest.yml to the gateway and the microservice app, so they can register to the registry when pushed. This needs to be confirmed.

**Comment by jdubois** [comment]
Your title is a bit misleading: it does work, I do it all the time.
However, you need to point to your registry in your application, and maybe the documentation is not clear enough on this point.

**Comment by rjain-pivotal** [comment]
Yes, I should say, doesn't work as documented. The document needs to be updated. Thanks!

**Comment by jdubois** [comment]
In fact I think it's different depending on how you launch the registry.
I need to check this to be sure.
