### ISSUE TITLE
[ENHANCEMENT] Re-factor code in AccessControlFilter.java

### ISSUE THREAD

**Issue by kkorada** [jhipster/generator-jhipster#3358]
##### **Overview of the issue**

Unnecessary looping in code when endpoint is found to be not authorized

##### **JHipster Version(s)** 

verison 3.0.0

##### **Suggest a Fix** 

terminate the loop when it is found that endpoint is not authorized

find the code below

`public boolean shouldFilter() {
        String requestUri = RequestContext.getCurrentContext().getRequest().getRequestURI();

        // If the request Uri does not start with the path of the authorized endpoints, we block the request
        for (Route route : routeLocator.getRoutes()) {
            String serviceUrl = route.getFullPath();
            String serviceName = route.getId();

            // If this route correspond to the current request URI
            // We do a substring to remove the "**" at the end of the route URL
            if (requestUri.startsWith(serviceUrl.substring(0, serviceUrl.length() - 2))) {
                if (isAuthorizedRequest(serviceUrl, serviceName, requestUri)) {
                    return false;
                }else{
					return true;
				}
            }
        }
        return true;
    }`

**Comment by deepu105** [comment]
can you do a PR?

**Comment by kkorada** [comment]
yes
