### ISSUE TITLE
[Elasticsearch] adding Elasticsearch specific annotation to field's domain classesc

### ISSUE THREAD

**Issue by lourai** [jhipster/generator-jhipster#3367]
##### **Overview of the issue**

We're using more and more Elasticsearch with great results, but we have still need some workaround to deal with "special" string containing dash "-".

##### **Motivation for or Use Case** 

In ES, search terms are dash-splitted, so that when you need to get some exact search on some code or UUID type string, it failed.

See https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_exact_values.html for full explanation.

##### **JHipster Version(s)** 

2.27

##### **Suggest a Fix** 

Adding @Field annotation forcing the index not to analyzed term is working great :
@Field(
        index = FieldIndex.not_analyzed,
        store = true
    )
private String code;

So we need a way to manage witch field have to be "not_analyzed" => a work for the entity generator !

Maybe simply activate some new question when entity generator identify a project using elasticsearch (and then let the JDL be able to manage that also !).

OR

adding @Field(...) on every String in every Domain (seems not very delicate but for me it's good way : i can have "-" string on many field : name, code, etc)

OR 

Enable a way to let dev manipulate domain classes cause their is maybe many other case like that (in my old projects, i generated abstract mapping classes and extended empty classes - never overwritten by generator, allowing manual optimisation of that kind). 

I did not already try the update process of entity in 3.0, maybe it can help !

**Comment by deepu105** [comment]
This is a very specific use case and yes I agree that many might have this, but we simply cannot have this option in the entity sub generator. So Im sorry.

But this could be something that can be done via JDL, so if @MathieuAA thinks this is doable in JDL may be we can support it as well.

Btw @MathieuAA this would make a good candidate for field level annotation in entity

Im closing this for now, @MathieuAA plz reopen this if you are willing to support it via JDL

**Comment by MathieuAA** [comment]
@deepu105 if the user wants to use ES in his/her project, why not add the `@Field` annotation in domains (and, of course, not adding unless ES is selected)? I mean, with no questions asked and for every project where a search engine option (currently only ES is available) has been chosen.
Maybe you guys want the user to make the selection process by his/herself and annotate every field manually... but it could be quite painful to manually do it if the user has a lot of entities or just a lot of fields.
Or at least ask a question during entity generation if the search engine flag is not 'no' in the .yo-rc.json file.

@lourai Hi Florent, for me it's a +1, and I already planned on adding the search engine option for JDL users. I just didn't create an issue for it in the JDL project's issue tracker...

**Comment by deepu105** [comment]
@MathieuAA im not sure if it should be added to all fields by default, it would violate our policy 1 and 2

Also im not sure if there would be performance or other issues in doing this. So I would like someone who knows ES well to defend this with details in order to convince that this would add value as a default. I dont see any now. 
Ok that was for the sub generator. Now if you can support this from JDL then we can consider that on a per field basis as it would be optional and upto the user to decide

**Comment by MathieuAA** [comment]
If we do it field-wise, JHipster would have to detect it... but it would be a bad decision anyway as "@Field" annotations could be used a lot and would pollute the JDL. So I'm not so sure about that.
Like you said, we need an ES guru here =)
