### ISSUE TITLE
Fix auto focus on password reset UI (need to update reset.request.controller.js)

### ISSUE THREAD

**Issue by gtiwari333** [jhipster/generator-jhipster#3372]
* **Overview of the request**

Auto focus on password reset screen is not working. I'm using jhipster generator version : 3.0.0 .

* **Motivation for or Use Case** 

Its a small bug, better if it fixed in next release.

* **Browsers and Operating System** 

ALL

* **Related issues** 

Did not noticed any existing report to this issue/bug.

* **Suggest a Fix** 

reset.request.controller.js needs to be updated to include  `vm.` around the $timeout logic to match what we have in reset.request.html file  : 

`        $timeout(function (){angular.element('[ng-model="vm.resetAccount.email"]').focus();});
`
The generated code is missing "vm."

**Comment by deepu105** [comment]
Can you do a PR? also can you change to fetch element by ID instead of
attribute?

Thanks & Regards,
Deepu

**Comment by gtiwari333** [comment]
Okay, I will do a PR. 

FYI, the following four .js files has the same issue ( using attribute instead of ID). I will update them all.

- login.controller.js
- register.controller.js
- reset.request.controller.js
- reset.finish.controller.js

**Comment by gtiwari333** [comment]
Submitted pull request https://github.com/jhipster/generator-jhipster/pull/3373

**Comment by wmarques** [comment]
Fixed by #3373 
@gtiwari333 please add "Fix #issuenumber" on the PR next time, it will autoclose the issue when we merge it :)
