### ISSUE TITLE
[FEATURE] Microservice app access user entity from gateway or gateway app access microservice entities

### ISSUE THREAD

**Issue by xjiaoyang** [jhipster/generator-jhipster#3377]
##### **Overview of the issue**

jhipster microservice is very different from spring-boot microservice . i stared these projects which very useful to start with spring boot microservice:
https://github.com/rohitghatol/spring-boot-microservices
https://github.com/joshlong/bootiful-microservices
https://github.com/kbastani/spring-cloud-microservice-example

these projects both demonstration how to access entities beteween microservice, but jhipster microservice are sames all isolated from each other.

##### **Motivation for or Use Case** 

i want access user entity from microservice app, and gateway app can also access microservice entity

##### **JHipster Version(s)** 
JHipster 3.0

**Comment by PierreBesson** [comment]
We are currently working on it. I think what you want is similar to https://github.com/jhipster/generator-jhipster/issues/3307, we think we can achieve this feature using a sub-generator for generating REST client. However we are first solving the issue of integrating with OAuth2.
Have a look at @xetys article http://stytex.de/blog/2016/03/25/jhipster3-microservice-tutorial/

**Comment by xjiaoyang** [comment]
@PierreBesson great!

**Comment by PierreBesson** [comment]
OK, then let's close this issue and continue the discussion on #3307
