### ISSUE TITLE
[Feature] liquidbase : having the 2 profiles configuration : dev and prod

### ISSUE THREAD

**Issue by fraf** [jhipster/generator-jhipster#3379]
When my developer team implements AngularJS screens, they need to boostrap initial data via CSV file.
These data is needed for GUI developping and testing. These data are dummy, only for test the screens.
Currently, we add custom data creating .CSV file to fill all the tables (with foreign key constraints, etc.). We add <loadData> tags to initial schema creation file.
All these liquidbase configuration modifications are not suitable when we deliver in production environnement.
Can we package separately the configuration for liquidbase according to the profile we run the application : dev or prod.
For instance, packages :
src.main.resources.config\liquibase-dev
src.main.resources.config\liquibase-prod

Any suggestion ?

**Comment by gmarziou** [comment]
This is not a jhipster issue nor a feature request, please ask you question on stackoverflow.
Have a look at Liquibase doc about using contexts.
