### ISSUE TITLE
Changing the default language kills the build

### ISSUE THREAD

**Issue by mathieu-chauvet** [jhipster/generator-jhipster#338]
In the default project with default settings. 

Changing the default language in the file : webapp/scripts/app.js 

```
Line :  $translateProvider.preferredLanguage('en');
```

to any other language breaks the build. 
example : 

```
Line :  $translateProvider.preferredLanguage('fr');
```

this error is generated : 

```
[1A[2K[31mPhantomJS 1.9.7 (Mac OS X) Services Tests  AuthenticationSharedService should call backend on logout then call authService.loginCancelled FAILED[39m
    Error: Unexpected request: GET i18n/de.json
    Expected GET i18n/en.json
        at $httpBackend (/Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1179)
        at sendReq (/Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:7886)
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:7619
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:11033
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:11033
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:11119
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:12045
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:11871
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1452
        at /Users/mathieuchauvet/aeffjhipster/src/test/javascript/spec/servicesSpec.js:39
        at /Users/mathieuchauvet/aeffjhipster/node_modules/karma-jasmine/lib/boot.js:117
        at /Users/mathieuchauvet/aeffjhipster/node_modules/karma-jasmine/lib/adapter.js:171
        at http://localhost:9876/karma.js:189
        at http://localhost:9876/context.html:83
    Error: Unexpected request: GET app/logout
    Expected GET i18n/en.json
        at $httpBackend (/Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1179)
        at sendReq (/Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:7886)
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:7619
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:11033
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:11033
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:11119
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:12045
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular/angular.js:11871
        at /Users/mathieuchauvet/aeffjhipster/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1485
        at /Users/mathieuchauvet/aeffjhipster/src/test/javascript/spec/servicesSpec.js:22
        at /Users/mathieuchauvet/aeffjhipster/node_modules/karma-jasmine/lib/boot.js:117
        at /Users/mathieuchauvet/aeffjhipster/node_modules/karma-jasmine/lib/adapter.js:171
        at http://localhost:9876/karma.js:189
        at http://localhost:9876/context.html:83
PhantomJS 1.9.7 (Mac OS X): Executed 6 of 6[31m (1 FAILED)[39m (0 secs / 0.027 secs)
[1A[2KPhantomJS 1.9.7 (Mac OS X): Executed 6 of 6[31m (1 FAILED)[39m (0.003 secs / 0.027 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

```

**Comment by Rukia05** [comment]
I know I'm a bit late to answer, but, who knows? It might help somebody. 
In the 'test' folder, just find the 'authServicesSpec.js' file, and change these lines : 

 $httpBackend.expectGET('i18n/en/global.json').respond(200, '');
 $httpBackend.expectGET('i18n/en/language.json').respond(200, '');
 $httpBackend.expectGET('i18n/en/global.json').respond(200, '');
 $httpBackend.expectGET('i18n/en/language.json').respond(200, '');
 $httpBackend.expectGET('i18n/en/main.json').respond(200, '');

To match your language. For example, for french : 

$httpBackend.expectGET('i18n/fr/main.json').respond(200, '');

Change all these lines, and it should work. At least, it worked for me! 
Have a nice day!

**Comment by kamauwairegi** [comment]
Wow, thanks a lot this really gave me headache almost quitting :)

On Thu, May 7, 2015 at 12:37 PM, Julia Reboul <notifications@github.com>
wrote:

> I know I'm a bit late to answer, but, who knows? It might help somebody.
> In the 'test' folder, just find the 'authServicesSpec.js' file, and change
> these lines :
>
> $httpBackend.expectGET('i18n/en/global.json').respond(200, '');
> $httpBackend.expectGET('i18n/en/language.json').respond(200, '');
> $httpBackend.expectGET('i18n/en/global.json').respond(200, '');
> $httpBackend.expectGET('i18n/en/language.json').respond(200, '');
> $httpBackend.expectGET('i18n/en/main.json').respond(200, '');
>
> To match your language. For example, for french :
>
> $httpBackend.expectGET('i18n/fr/main.json').respond(200, '');
>
> Change all these lines, and it should work. At least, it worked for me!
> Have a nice day!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/338#issuecomment-99794507>
> .
>



-- 
--Software Developer

**Comment by Rukia05** [comment]
You're welcome, I spent quite some time on it :)

**Comment by kamauwairegi** [comment]
You saved me :)

On Thu, May 7, 2015 at 1:01 PM, Julia Reboul <notifications@github.com>
wrote:

> You're welcome, I spent quite some time on it :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/338#issuecomment-99801278>
> .
>



-- 
--Software Developer
