### ISSUE TITLE
Wrong resourceUrl on microservices

### ISSUE THREAD

**Issue by andresfuentes** [jhipster/generator-jhipster#3384]
##### **Overview of the issue**

When ghenerating an entity in the gateway app the code for <entity>.service.js and <entity>.search.service.js get an incorrect resourceUrl path

it gets

var resourceUrl =  'api/<entity>s/:id';

and It should be

var resourceUrl =  '<microserviceApp>/api/<entity>s/:id';

##### **Motivation for or Use Case** 

code is not working correctly thru generation.. it required a manual fix

##### **JHipster Version(s)** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "gateway",
    "packageName": "com.code348.iw2p2.gateway",
    "packageFolder": "com/code348/iw2p2/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "a781a7ff21819c890bb4d415d10d4c531f1ac120",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ],
    "enableSocialSignIn": false
  }
}

**Comment by deepu105** [comment]
this is working. how are you using the app is it run via docker or started locally or have you deployed with a context?

**Comment by jdubois** [comment]
Closing this as we waited for information for 18 days now....
