### ISSUE TITLE
Blank page when dev database is mysql.

### ISSUE THREAD

**Issue by Kurtzz** [jhipster/generator-jhipster#3385]
##### **Overview of the issue**

localhost:8080/ return blank page only when using mysql as dev database.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "WePlay",
    "packageName": "org.weplay",
    "packageFolder": "org/weplay",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "0dd19bd91096f12ba79b69a74696cb190ebc8914",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "pl"
    ]
  }
}

##### **Suggest a Fix**

**Comment by deepu105** [comment]
Does it work if you use any other database?  I dont think this is a db
related issue. Your initial build might not have run succesfully. Wat
console error do you see in browser. Try to run `npm install` , `bower
install` and `gulp install` one after another and see if it works

**Comment by Kurtzz** [comment]
It build without errors. In browser i don't see anything. If I type /(random chars) I only get "Your request cannot be processed".
Everything is fine when I use H2 instead of MySQL as dev database.
But I will try run those install commands.

**Comment by deepu105** [comment]
what is the error in browsers developer console?

**Comment by lluiscanals** [comment]
Can you take a look at your index.html code? Is "gulp serve" running without errors?

**Comment by Kurtzz** [comment]
`<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>WePlay</title>
    <meta name="description" content="">
    <meta name="google" value="notranslate">
    <meta name="viewport" content="width=device-width">
    
    
    
    
    
    
    <link rel="stylesheet" href="content/css/main.css">
    
</head>
<body ng-app="wePlayApp">
    
    <div ng-show="{{ENV === 'dev'}}" class="development" ng-cloak></div>
    <div ui-view="navbar" ng-cloak></div>
    <div class="container">
        <div class="well" ui-view="content"></div>

        <div class="footer" ng-cloak>
            <p translate="footer">This is your footer</p>
        </div>
    </div>

    

    
    
    
    

    
    
    <script src="app/app.module.js"></script>
    <script src="app/account/social/directive/social.directive.js"></script>
    <script src="app/account/reset/finish/reset.finish.state.js"></script>
    <script src="app/account/reset/finish/reset.finish.controller.js"></script>
    <script src="app/account/reset/request/reset.request.state.js"></script>
    <script src="app/account/reset/request/reset.request.controller.js"></script>
    <script src="app/services/user/user.service.js"></script>
    <script src="app/services/auth/sessions.service.js"></script>
    <script src="app/services/auth/register.service.js"></script>
    <script src="app/services/auth/principal.service.js"></script>
    <script src="app/services/auth/password.service.js"></script>
    <script src="app/services/auth/password-reset-init.service.js"></script>
    <script src="app/services/auth/password-reset-finish.service.js"></script>
    <script src="app/services/auth/has-authority.directive.js"></script>
    <script src="app/services/auth/has-any-authority.directive.js"></script>
    <script src="app/services/auth/auth.session.service.js"></script>
    <script src="app/services/auth/auth.service.js"></script>
    <script src="app/services/auth/activate.service.js"></script>
    <script src="app/services/auth/account.service.js"></script>
    <script src="app/layouts/navbar/navbar.controller.js"></script>
    <script src="app/layouts/navbar/active-menu.directive.js"></script>
    <script src="app/layouts/navbar/active-link.directive.js"></script>
    <script src="app/layouts/error/error.state.js"></script>
    <script src="app/components/util/truncate-words.filter.js"></script>
    <script src="app/components/util/truncate-characters.filter.js"></script>
    <script src="app/components/util/sort.directive.js"></script>
    <script src="app/components/util/sort-by.directive.js"></script>
    <script src="app/components/util/parse-links.service.js"></script>
    <script src="app/components/util/pagination-util.service.js"></script>
    <script src="app/components/util/jhi-item-count.directive.js"></script>
    <script src="app/components/util/date-util.service.js"></script>
    <script src="app/components/util/data-util.service.js"></script>
    <script src="app/components/util/capitalize.filter.js"></script>
    <script src="app/components/util/base64.service.js"></script>
    <script src="app/components/login/login.service.js"></script>
    <script src="app/components/login/login.controller.js"></script>
    <script src="app/components/language/language.service.js"></script>
    <script src="app/components/language/language.filter.js"></script>
    <script src="app/components/language/language.controller.js"></script>
    <script src="app/components/language/language.constants.js"></script>
    <script src="app/components/form/uib-pagination.config.js"></script>
    <script src="app/components/form/uib-pager.config.js"></script>
    <script src="app/components/form/show-validation.directive.js"></script>
    <script src="app/components/form/pagination.constants.js"></script>
    <script src="app/components/form/minbytes.directive.js"></script>
    <script src="app/components/form/maxbytes.directive.js"></script>
    <script src="app/components/alert/alert.service.js"></script>
    <script src="app/components/alert/alert.directive.js"></script>
    <script src="app/components/alert/alert-error.directive.js"></script>
    <script src="app/blocks/interceptor/notification.interceptor.js"></script>
    <script src="app/blocks/interceptor/errorhandler.interceptor.js"></script>
    <script src="app/blocks/interceptor/auth-expired.interceptor.js"></script>
    <script src="app/blocks/handlers/translation.handler.js"></script>
    <script src="app/blocks/handlers/state.handler.js"></script>
    <script src="app/blocks/config/translation.config.js"></script>
    <script src="app/blocks/config/translation-storage.provider.js"></script>
    <script src="app/blocks/config/localstorage.config.js"></script>
    <script src="app/blocks/config/http.config.js"></script>
    <script src="app/blocks/config/compile.config.js"></script>
    <script src="app/blocks/config/alert.config.js"></script>
    <script src="app/admin/user-management/user-management.state.js"></script>
    <script src="app/admin/user-management/user-management.controller.js"></script>
    <script src="app/admin/user-management/user-management-dialog.controller.js"></script>
    <script src="app/admin/user-management/user-management-detail.controller.js"></script>
    <script src="app/admin/user-management/user-management-delete-dialog.controller.js"></script>
    <script src="app/admin/metrics/metrics.state.js"></script>
    <script src="app/admin/metrics/metrics.service.js"></script>
    <script src="app/admin/metrics/metrics.modal.controller.js"></script>
    <script src="app/admin/metrics/metrics.controller.js"></script>
    <script src="app/admin/logs/logs.state.js"></script>
    <script src="app/admin/logs/logs.service.js"></script>
    <script src="app/admin/logs/logs.controller.js"></script>
    <script src="app/admin/health/health.state.js"></script>
    <script src="app/admin/health/health.service.js"></script>
    <script src="app/admin/health/health.modal.controller.js"></script>
    <script src="app/admin/health/health.controller.js"></script>
    <script src="app/admin/docs/docs.state.js"></script>
    <script src="app/admin/configuration/configuration.state.js"></script>
    <script src="app/admin/configuration/configuration.service.js"></script>
    <script src="app/admin/configuration/configuration.controller.js"></script>
    <script src="app/admin/audits/audits.state.js"></script>
    <script src="app/admin/audits/audits.service.js"></script>
    <script src="app/admin/audits/audits.controller.js"></script>
    <script src="app/account/social/social.state.js"></script>
    <script src="app/account/social/social.service.js"></script>
    <script src="app/account/social/social-register.controller.js"></script>
    <script src="app/account/settings/settings.state.js"></script>
    <script src="app/account/settings/settings.controller.js"></script>
    <script src="app/account/sessions/sessions.state.js"></script>
    <script src="app/account/sessions/sessions.controller.js"></script>
    <script src="app/account/register/register.state.js"></script>
    <script src="app/account/register/register.controller.js"></script>
    <script src="app/account/password/password.state.js"></script>
    <script src="app/account/password/password.controller.js"></script>
    <script src="app/account/password/password-strength-bar.directive.js"></script>
    <script src="app/account/activate/activate.state.js"></script>
    <script src="app/account/activate/activate.controller.js"></script>
    <script src="app/home/home.state.js"></script>
    <script src="app/home/home.controller.js"></script>
    <script src="app/entities/entity.state.js"></script>
    <script src="app/admin/admin.state.js"></script>
    <script src="app/account/account.state.js"></script>
    <script src="app/app.state.js"></script>
    <script src="app/app.constants.js"></script>
    
    

</body>
</html>
`

**Comment by Kurtzz** [comment]
Index.html [http://pastebin.com/pYk2Wu9E](url)
I just run app with Maven using spring-boot:run.
I have just installed gulp and it's return:

> SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/kurtz/IdeaProjects/we.play/gulpfile.js:27:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

**Comment by Kurtzz** [comment]
I install nodejs, npm and bower correctly and generated once again whole project. From docker run gulp, which inject some stuff to index.html and now it's working. Thanks!
