### ISSUE TITLE
[FEATURE] Autofocus on the first text field in entity creation dialog

### ISSUE THREAD

**Issue by konfri** [jhipster/generator-jhipster#3388]
Hey,

I just started using JHipster and it's really nice :+1: 

I noticed that the logic dialog automatically sets the focus to the username text field. This is nice and makes the login process even more pleasant.

If I generate an entity the focus in the creation dialog is not set at all. I need to hit "tab" key several times and then I can start to fill the first text field. It would be nice if the focus could be set automatically to first writable field (not the id field) in the creation dialog. I might make sense to omit the focus setting if the user changes an entity (as the htll dialog page is reused for creation and updating, right?).

Does this makes sense? :)

I use the latest JHipster version (3.0.0).

Thank you :)

Konstantin

**Comment by wmarques** [comment]
Makes sense to me :+1:

**Comment by deepu105** [comment]
@konfri would you consider doing a PR?

**Comment by konfri** [comment]
@deepu105 I will check this tonight. Now, I need to get back to work ;)

**Comment by konfri** [comment]
@wmarques Thanks you :+1:
