### ISSUE TITLE
Store previous state in sessionStorage instead of rootScope

### ISSUE THREAD

**Issue by sdoxsee** [jhipster/generator-jhipster#3395]
##### **Overview of the issue**

In order to get OAuth2 SSO with different gateway apps we'll need to redirect to the authorization server and leave the SPA. Storing the previousState in localStorage rather than rootScope will enable us to bring the user back to the originally requested (but protected) page.

For example, http://localhost:8080/#/settings is protected--prompting a login (on the external authorization server). If requested directly, the user should be directed back to the requested page (not just "home") following authorization on the external authorization server. Saving the previousState info in localStorage allows us to do this.

##### **Motivation for or Use Case** 

This works now and will get us ready for OAuth2

##### **Suggest a Fix** 

PR coming

**Comment by deepu105** [comment]
@sdoxsee would it be better to use sessionstorage for this rather than localstorage?

**Comment by jdubois** [comment]
yes I have the same issue for OAuth2, +1 for me
And @deepu105 is right, session storage should be enough

**Comment by deepu105** [comment]
`$sessionStorage` is avilable for injection

**Comment by sdoxsee** [comment]
@deepu105 @jdubois Yes. $sessionStorage is the way to go. Thanks! I've made the change to my PR and I'm just waiting to confirm that the protractor tests are fixed (I've verified locally)
