### ISSUE TITLE
[FEATURE] Hide id text field entity creation dialog

### ISSUE THREAD

**Issue by konfri** [jhipster/generator-jhipster#3401]
Hey,

I was wondering if the id field in the entity creation dialog could be removed (but stay in the edit dialog). It does not add any meaningful informations as the actual database id has not been assigned yet anyway.

At the moment, I'm reading the JHipster Mini Book (http://www.jhipster-book.com) and as it happens  Matt Raible also removes the id field in his 21-point example. I'm not the only one that had this thought ;)

I use the latest JHipster version (3.0.0).

Thank you :)

Konstantin

**Comment by wmarques** [comment]
I guess we display the field to inform the user about the field in the database and also, if he wants to set an id in the creation, he just has to remove some HTML attributes and JS.

**Comment by sendilkumarn** [comment]
I think we can remove it. I would like to do a PR for this

**Comment by konfri** [comment]
It's not just remove some html and js code, as you need to differentiate between create and update (they use the same dialog template, right?).

I guess that most of the user keep using the auto increment flag for the id value, as it is less work and it is saver. So, they won't care about the id during the creation.

Do you think It make sense to hide the field during the creation?
