### ISSUE TITLE
[BUG] Deploying to AWS fails, httpOptions - Unexpected identifier

### ISSUE THREAD

**Issue by vicgrad** [jhipster/generator-jhipster#3406]
##### **Overview of the issue**

I am trying to deploy a jhipster generated project to aws. I have followed the guide here: http://jhipster.github.io/aws/ but when running `yo jhipster:aws` there seems to be an error in the s3 script. The error is:

> VG-MacBook-Pro:cm vg$ yo jhipster:aws
> <...>/node_modules/generator-jhipster/generators/aws/lib/s3.js:87
>                 httpOptions: {timeout: 600000}
>                 ^^^^^^^^^^^
> 
> SyntaxError: Unexpected identifier
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:387:25)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (<...>/node_modules/generator-jhipster/generators/aws/lib/aws.js:2:10)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)

##### **Motivation for or Use Case** 

I cannot go through the workflow to deploy on aws

##### **JHipster Version(s)** 

v3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

> {
>   "generator-jhipster": {
>     "jhipsterVersion": "3.0.0",
>     "baseName": "cm",
>     "packageName": "ro.mobilekinetics.cm",
>     "packageFolder": "ro/mobilekinetics/cm",
>     "serverPort": "8080",
>     "authenticationType": "session",
>     "hibernateCache": "ehcache",
>     "clusteredHttpSession": "no",
>     "websocket": "spring-websocket",
>     "databaseType": "sql",
>     "devDatabaseType": "h2Memory",
>     "prodDatabaseType": "mysql",
>     "searchEngine": "no",
>     "buildTool": "maven",
>     "enableSocialSignIn": false,
>     "rememberMeKey": "",
>     "useSass": false,
>     "applicationType": "monolith",
>     "testFrameworks": [
>       "gatling"
>     ],
>     "enableTranslation": false
>   }
> }

##### **Browsers and Operating System** 

Reproduced the bug on Mac OS X 10.11.4 and Windows 8.1

##### **Reproduce the error** 

Followed the steps in the guide http://jhipster.github.io/aws/
The following command fails 
`yo jhipster:aws`

**Comment by jdubois** [comment]
Can you put a title that is more clear?

**Comment by deepu105** [comment]
ping @wuethrich44

**Comment by wuethrich44** [comment]
This bug is fixed in commit https://github.com/jhipster/generator-jhipster/commit/e062ad592c849a22ffb26dc4139a34d63e8fc870. For a workaround simpliy put a comma after this [line](https://github.com/jhipster/generator-jhipster/commit/834501e441e8433a88ac449ca30b37689fbb9d88#diff-87ec3dd2b5806c87199817c5fcf2d042R87).
