### ISSUE TITLE
Broken link on http://jhipster.github.io/heroku/

### ISSUE THREAD

**Issue by rdanilin** [jhipster/generator-jhipster#3416]
##### **Overview of the issue**
Broken link to 'Spring Boot Heroku documentation' on http://jhipster.github.io/heroku/ page

##### **Motivation for or Use Case** 
Not applicable

##### **JHipster Version(s)** 
v2.x 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

Not applicable
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
Not applicable

##### **Browsers and Operating System** 
MacOS, Safari

##### **Reproduce the error** 
Not applicable

##### **Related issues** 
Not applicable

##### **Suggest a Fix** 
Not applicable

**Comment by gmarziou** [comment]
Thanks, the correct link should be http://docs.spring.io/spring-boot/docs/current/reference/html/cloud-deployment.html#cloud-deployment-heroku 

Fix should be applied to both 3.x and 2.x doc.

I'll dot it.
