### ISSUE TITLE
Add a JHipster oh-my-zsh plugin

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3419]
It would ease development on Mac OS X if we had a [oh-my-zsh plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins), like what currently exists for Rails, etc

**Comment by wmarques** [comment]
I'm working on it !
What are for you guys the best aliases to use for this plugin ?

**Comment by raphaelbrugier** [comment]
+1 I'm huge fan of oh-my-zsh too!

I would not use too small aliases like `jhi`i or `jhie`
I would rather keep with the fullname `jhispter` but add autocompletion and documentation on the commands.

**Comment by jdubois** [comment]
Like Rails, we could have:

- Auto-completion for commands like yo jhipster:entity
- And alias like they have in Rails -> it's just aliases, you don't need to use them, and for rails they have stuff like rc='rails console'. So for me we could have "jh" or "jhi", that's good for me

**Comment by atomfrede** [comment]
I recently switched to fish shell, so maybe I can have a look how to build something for fish shell.

**Comment by wmarques** [comment]
I started my work on this repo. I based my work on the docker plugin.

I'm a totally bash language newbie so I found some problem while working on it:
* `yo jhipster` contains space so I just managed to complete `jhipster` but it's not working with the `yo` before
* The autocomplete put the command with a space after `jhipster` so it renders like this for example: `jhipster :entity` and I couldn't manage to remove this space

If you have any suggestions about this plz tell me :)

**Comment by jdubois** [comment]
I just have one working which is very, very simple.... I'm not sure of why mine works and why the one from @wmarques doesn't work
I'll commit this soon

**Comment by jdubois** [comment]
And it's done:

https://github.com/jhipster/jhipster-oh-my-zsh-plugin
