### ISSUE TITLE
Remove redundant variable used for pattern validation 

### ISSUE THREAD

**Issue by dinhnn** [jhipster/generator-jhipster#3421]
##### **Overview of the issue**

Generate entity with pattern validation
ex:
entity E{
   test String pattern("$\d+^")
}
Result:
class E{
....
@Pattern(regexp = "undefined")
String test;
....
}

##### **JHipster Version(s)** 
JHipster 3.0

##### **Suggest a Fix** 
Edit generators/entity/templates/src/main/java/package/domain/field_validators.ejs
40: -validators.push('@Pattern(regexp = "' + field.fieldValidateRulesPatternJava  + '")');
40: +validators.push('@Pattern(regexp = "' + (field.fieldValidateRulesPattern ? field.fieldValidateRulesPattern.replace(/\\/g, '\\\\') : field.fieldValidateRulesPattern) + '")');

**Comment by deepu105** [comment]
@dinhnn would you like to do a PR to fix this?

**Comment by jmcshane** [comment]
+1 I experienced this as well

**Comment by jdubois** [comment]
I merged the fix but this is making the build fail... It's clearly buggy, I'm going to do another fix

**Comment by jdubois** [comment]
OK that's in fact a bug in the JDL, as your title says, as the fieldValidateRulesPatternJava is probably not set up.

-> this is the generator project, and this should be solved on the JDL project

So:
- I'm keeping this ticket closed, as it's not a correct ticket on this project
- I'm reverting the commit
- @dinhnn can you re-create this ticket on https://github.com/jhipster/jhipster-domain-language ?
- I'm notifying @MathieuAA as he knows this much better than I do!!

**Comment by MathieuAA** [comment]
Indeed @jdubois, I didn't set the `fieldValidateRulesPatternJava` attribute. Can't you guys merge it into `fieldValidateRulesPattern`? There's an ugly redundancy here. < @jhipster/developers

**Comment by deepu105** [comment]
Agree we should try to avoid the redundancy if possible

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
Im re opening this to see if we can remove the redundancy
