### ISSUE TITLE
Is there a reason to have a username, and not just use the email as login?

### ISSUE THREAD

**Issue by AlainJanssens** [jhipster/generator-jhipster#3426]
When you register, you need to give a username. 

Is there a specific reason why Jhipster isn't just using the email? 

Regards,

Alain

**Comment by dornala** [comment]
Nope nothing. It's up to us, we can customize hipster use email instead of username. If you wanna come up with email as username you might need to make changes to UserDetailsService in Security folder.

**Comment by AlainJanssens** [comment]
hmmmm... From my point of view it is a lot more work :-).

I was just wondering why this was not a standard?

**Comment by dornala** [comment]
I don't think it's actually about standard. How often we see people logging in with E-Mail these days. If you have a requirement of using E-mail as User Id I can help you. Happy Coding .. ;)  . Easiest will be making front end ngbind username and email.

**Comment by wmarques** [comment]
It's a choice from us and not a JHipster bug, but thanks for your feedback :+1: 
You can continue the discussion on SO or on [Gitter](https://gitter.im/jhipster/generator-jhipster), I'm closing this issue
