### ISSUE TITLE
Jhipster and SQl server intergration

### ISSUE THREAD

**Issue by glsgolden** [jhipster/generator-jhipster#3430]
##### **Overview of the issue**

How to intergrate the Jhipster and SQl server as database.

##### **Motivation for or Use Case** 
I was trying to change application.yml and pom.xml to intergrate with sql server database.
and also change the liquibase jar to mssql support.
but this is not working for mssql. case

##### **JHipster Version(s)** 
2.0

**Comment by deepu105** [comment]
I hope you are talking about MS SQL server if so check this tip https://jhipster.github.io/tips/004_tip_using_ms_sql_server.html
