### ISSUE TITLE
[FEATURE] Maven multi module project issue with resolving path during startup

### ISSUE THREAD

**Issue by ykushch** [jhipster/generator-jhipster#3431]
##### **Overview of the issue**

We have a large project with many module. When I've created module with Jhipster it is not running correctly due to inability to resolve path:

    File root;
    if (env.acceptsProfiles(Constants.SPRING_PROFILE_PRODUCTION)) {
        root = new File("target/www/"); // this is problem place
    } else {
        root = new File("src/main/webapp/"); // this is problem place
    }
    if (root.exists() && root.isDirectory()) {
        container.setDocumentRoot(root);
    }

##### **Motivation for or Use Case** 

It is not possible to run it as submodule of large number of projects. 

##### **JHipster Version(s)** 

Reproduces on all versions

##### **Browsers and Operating System** 

On every system it could be reproduced

##### **Reproduce the error** 

Create a maven structure that looks like this for example:

    MainModule
    |
    |__ SubModule1
    |   |__ JhipsterProject
    |
    |__ SubModule2

##### **Related issues** 

Found that you are not dealing with multi module projects (dividing core and frontend) but it is not the same. It is about including jhipster module as the separate one but in current structure.

##### **Suggest a Fix** 

I am working on fix for this issue. Could contribute as well.

**Comment by jdubois** [comment]
I'm sorry but we don't generate multi module projects... You mean Maven multi-modules? Or with your IDE?

**Comment by ykushch** [comment]
It seems that I did not describe the issue / feature nicely :) 
I have a project that has many maven-modules with different submodules already. And I am just adding Jhipster project to this hierarchy. And during startup the only issue that prevents it to be successful is inability to resolve the path like I've described above. 
I know that possible it is not the case but anyway - it seems like it is more the feature than bug.

**Comment by ykushch** [comment]
It seems that I've managed to implement / fix this. The key thing here is that instead of looking into directly `JhipsterProject` (from the tree representation above) it looked into `MainModule` and cannot find `src/main/webapp/` path of course. Should test it now on Linux and Mac.

**Comment by deepu105** [comment]
@ykushch if the fix is generic and applicable for default monolith project then plz do a PR

**Comment by ykushch** [comment]
@deepu105 sure, I need to perform some additional tests. Tested it already on mac os - works fine with standard and non-standard layout too.

**Comment by deepu105** [comment]
closed via #3447
