### ISSUE TITLE
generator-jhipster-swagger-cli : expected function  addJavaScriptToIndex not available in generator-base.js

### ISSUE THREAD

**Issue by MBenali** [jhipster/generator-jhipster#3433]
##### **generator-jhipster-swagger-cli :  http://petstore.swagger.io/v2/swagger.json
** 

##### **generator-jhipster-swagger-cli : Generating front end code for petstore (http://petstore.swagger.io/v2/swagger.json)

**TypeError: j#_hipsterFunc.addJavaScriptToIndex is not a function_
    at null.<anonymous> (/home/user/.npm-global/lib/node_modules/generator-jhipster-swagger-cli/generators/app/index.js:243:26)
    at Array.forEach (native)
    at null.<anonymous> (/home/user/.npm-global/lib/node_modules/generator-jhipster-swagger-cli/generators/app/index.js:228:47)
    at Array.forEach (native)
    at module.exports.yeoman.Base.extend.writing.callSwaggerCodegen (/home/user/.npm-global/lib/node_modules/generator-jhipster-swagger-cli/generators/app/index.js:226:40)
    at Object.<anonymous> (/home/user/.npm-global/lib/node_modules/generator-jhipster-swagger-cli/node_modules/yeoman-generator/lib/base.js:436:25)
    at /home/user/.npm-global/lib/node_modules/generator-jhipster-swagger-cli/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25
    at /home/user/.npm-global/lib/node_modules/generator-jhipster-swagger-cli/node_modules/yeoman-generator/node_modules/run-async/index.js:25:19
    at /home/user/.npm-global/lib/node_modules/generator-jhipster-swagger-cli/node_modules/yeoman-generator/lib/base.js:448:8
    at tryOnImmediate (timers.js:534:15)**
**

**Comment by cbornet** [comment]
Yes. I need to upgrade the module to jhipster 3. See https://github.com/cbornet/generator-jhipster-swagger-cli/issues/7
I'll do it asap. Soŕry for the delay.

**Comment by MBenali** [comment]
thank's

**Comment by cbornet** [comment]
@MBenali I just made a new release that should fix it. Can you update and test ?
If you still find issues, please open tickets on the [module project](https://github.com/cbornet/generator-jhipster-swagger-cli/issues/new) and not on the main generator.

**Comment by MBenali** [comment]
@cbornet 
I create a monolitic application whith : yo jhipster, after i make a yo jhipster-swagger-cli

The build is Ok, no errors are thrown

> ~/jhipster/swagger_cli_hdb$ yo jhipster-swagger-cli
> Composing JHipster configuration with module swagger-cli
> Welcome to the JHipster swagger-cli generator! v1.0.0
> 
> Reading the JHipster project configuration for your module
> ? Where is your Swagger/OpenAPI spec (URL or path) ? http://petstore.swagger.io/v2/swagger.json
> ? What is the unique name for your API client ? petstore
> ? Select which type of API client to generate front-end client, back-end client
> ? Do you want to save this config for future reuse ? No
> Generating front end code for petstore (http://petstore.swagger.io/v2/swagger.json)
> Generating back end code for petstore (http://petstore.swagger.io/v2/swagger.json)

mvn spring-boot:run, run whithout exceptions, but i haven't any things when i open link http://127.0.0.1:8080/
Just à white page.

**Comment by cbornet** [comment]
Is there any error in the browser's developper console ?

**Comment by cbornet** [comment]
And you probably need to do a ```gulp build``` to inject the script into the index.html.
I will add this step to the module.

**Comment by MBenali** [comment]
No error, nothing

Ok i will test with gulp build.

**Comment by deepu105** [comment]
its `gulp install` for dev and `gulp build` for prod

Thanks & Regards,
Deepu

**Comment by MBenali** [comment]
@cbornet 
@deepu105 
Thanks,
the application works but under Entities tab, i don't have any thing..
ihaven't petstore items

**Comment by cbornet** [comment]
It's normal : the module only generates code to make API calls. It cannot know what you want to do with the data after that. If you want entities, you need to use the entity generator (or JDL/JHUML).

**Comment by MBenali** [comment]
@cbornet
Ok, thanks.
I thought that the generation of the front part, would also modify the html, js, ..etc

**Comment by cbornet** [comment]
The module generates an angular service (eg. petstore.module.js). I don't really see what generic views could be generated (better than what swagger-ui provides) but if you have ideas, don't hesitate to open a feature request.

**Comment by MBenali** [comment]
Ok,
At the moment I begin with this tool, but when I would be capable of proposing, I would not hesitate

Thanks & Regards,
MBenali

**Comment by cbornet** [comment]
With the latest version of the module, ```gulp install``` will now be called at the end of the module execution.
