### ISSUE TITLE
Build error: Could not find property 'GulpTask' on root project

### ISSUE THREAD

**Issue by trongtran** [jhipster/generator-jhipster#3438]
FAILURE: Build failed with an exception.

* Where:
Script '/path-to-my-project/gradle/profile_dev.gradle' line: 28

* What went wrong:
A problem occurred evaluating script.
> Could not find property 'GulpTask' on root project 'myproject'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

--------------------------------------
line 28: task gulpConstantDev(type: GulpTask) {
    args = ["ngconstant:dev", "--no-notification"]
}

**Comment by trongtran** [comment]
Below are some my optionals when I was created new sample project

.....
? (5/16) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL, Oracle)
? (6/16) Which *production* database would you like to use? MySQL
? (7/16) Which *development* database would you like to use? MySQL
? (8/16) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
? (9/16) Do you want to use a search engine in your application? No
? (10/16) Would you like to use Maven or Gradle for building the backend? Gradle
? (11/16) Would you like to enable internationalization support? Yes
? Please choose the native language of the application? English
? Please choose additional languages to install Japanese
? (12/16) Which testing frameworks would you like to use? Gatling


After that, I just ran **./gradlew**

It thrown above error

**Comment by trongtran** [comment]
@deepu105 How can I resolve this issue?

**Comment by deepu105** [comment]
Please follow our [guidelines ](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#issue) when opening issues if you want us to help you.
For bug reports please follow the template pre populated [here](https://github.com/jhipster/generator-jhipster/issues/new)
Open a new issue with proper details or update this issue with all details and request to re open.
Issues opened without proper details will be closed without explanation.
