### ISSUE TITLE
mvn package -DskipTests=true -B -Pprod command executes gulp tests with PhantomJS where we expect all the tests not to be executed

### ISSUE THREAD

**Issue by pramika** [jhipster/generator-jhipster#3439]
##### **Maven Prod package for Cloud executes Javascript tests using PhantomJS where all the tests are expected not to be executed**

The above issue exists in Jhipster version 3.0.0 also 3.1.0. Did not checked in other versions.

And I am using Apache maven 3.3.3 for packaging.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "MfgTegTracker",
    "packageName": "com.tcs.tegtracker",
    "packageFolder": "com/tcs/tegtracker",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "bdd106ef58940c60b39bea057908728e1fbb29a5",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}

**Comment by deepu105** [comment]
I confirm this

**Comment by jdubois** [comment]
The skipTest option is only for the Java build, which is handled by Maven directly. The gulp test is in the JavaScript build, which is indeed triggered by Maven, but is independant (so Maven has no idea there are tests here, and they are not running as part as the "test" Maven goal).
I agree it would be logical to have also gulp test skipped, but that would be a specific Maven configuration, which isn't done today.

**Comment by atomfrede** [comment]
I guess when buildign on maven with prod profile gulp tests are also executed.

**Comment by atomfrede** [comment]
I think switching to the frontend-maven plugin will solve the issue with maven. https://github.com/jhipster/generator-jhipster/pull/3365

**Comment by deepu105** [comment]
@ddewaele since we merged the front end maven plugin anyway that this gets fixed?

**Comment by deepu105** [comment]
I checked a generated app with the new plugin but it still runs the test with `-DskipTests=true -B -Pprod`

**Comment by ddewaele** [comment]
I will check ... I think we'll need to [specify a phase](https://github.com/eirslett/frontend-maven-plugin#running-karma) for the gulp test command.  (right now, as this issue states the gulp tests will always run).

Once that is done and tested I think this issue can also be closed.

**Comment by jdubois** [comment]
Yes you need to put it in the "test" phase

**Comment by ddewaele** [comment]
@deepu105 : Just did a small test and seems to work fine if we do this : 

```
                            <execution>
                                <id>gulp build</id>
                                <goals>
                                    <goal>gulp</goal>
                                </goals>
                                <configuration>
                                    <arguments>build --no-notification</arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>gulp test</id>
                                <phase>test</phase>
                                <goals>
                                    <goal>gulp</goal>
                                </goals>
                                <configuration>
                                    <arguments>test --no-notification</arguments>
                                </configuration>
                            </execution>
```

- with -DskipTests ```gulp test``` is not executed
- without -DskipTests ```gulp test``` is executed after the java unit tests

**Comment by ddewaele** [comment]
I can do a PR and include @jdubois comment on the version range of the plugin

**Comment by deepu105** [comment]
Yes plz

Thanks & Regards,
Deepu

**Comment by ddewaele** [comment]
[PR created](https://github.com/jhipster/generator-jhipster/pull/3521)

**Comment by jdubois** [comment]
Looks good to me, we will also need to do that for Gradle -> can you open a ticket for that?

**Comment by ddewaele** [comment]
@jdubois  : I think @atomfrede mentioned it was already ok with Gradle.

**Comment by jdubois** [comment]
OK perfect!
