### ISSUE TITLE
Could not find property 'GulpTask' on root project 'xxx'

### ISSUE THREAD

**Issue by trajakovic** [jhipster/generator-jhipster#3442]
##### **Overview of the issue**

Gradle build fails for jhipster microservice application. Reason:

```
* Where:
Script '<cut>/xxxxx/gradle/profile_dev.gradle' line: 28

* What went wrong:
A problem occurred evaluating script.
> Could not find property 'GulpTask' on root project 'xxxxx'.
```

##### **Motivation for or Use Case** 

Since you cannot run gradle build (even gradle clean), it's obviously blocker type of error.

##### **JHipster Version(s)** 

JHipster Generator v3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "jhipsteruservice1",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "10001",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": "no",
    "buildTool": "gradle",
    "jwtSecretKey": "<cut>",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

No entity generated

##### **Browsers and Operating System** 

cat /etc/*-release:
Fedora release 23 (Twenty Three)
NAME=Fedora
VERSION="23 (Twenty Three)"
ID=fedora
VERSION_ID=23
PRETTY_NAME="Fedora 23 (Twenty Three)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:23"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=23
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=23
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
Fedora release 23 (Twenty Three)
Fedora release 23 (Twenty Three)

Browser not involved here

Steps:

* yo jhipster
* Selections:
 * 1/16 Microservice application
 * 2/16 jhipster
 * 3/16 10001
 * 4/16 com.mycompany.myapp
 * 5/16 No database
 * 6/16 Gradle
 * 7/16 n
 * 8/16 deselect all

* after generated code run:
 * ./gradlew clean

which generates error described above

##### **Related issues** 

#3438 has addressed this issue

##### **Suggest a Fix** 

Since I'm not aware of full jhipster generation process, I cannot provide 100% correct suggestion, but i guess that, since it's uService generator, you don't need Gulp part so fix would be or delete gulpConstantDev task on line 28 together with line 46 (gradle/profile_dev.gradle) or to apply proper gulp plugin if it's needed for overall.

Thx

**Comment by deepu105** [comment]
Ok ill take look. I guess there ia PR open which should fix this

**Comment by atomfrede** [comment]
@deepu105 I fixed it some time ago, but maybe there is something different when using microservices I didn't see.

**Comment by xjiaoyang** [comment]
@atomfrede i compare to gradle/profile_pord.gradle, there is no gulpTask, so i delete gulpTask in profile_dev.gradle. i think you maybe just forgot to delete gulpTask on microservice application generation.

**Comment by atomfrede** [comment]
@xjiaoyang It is fixed in latest master. Gulp Task is only added to ``profile_dev.gradle`` if ``skipClient`` equals `` false``.
