### ISSUE TITLE
Error when entity have a attribute enumeration (enum java).

### ISSUE THREAD

**Issue by rraraujop** [jhipster/generator-jhipster#3444]
When I use "entity" sub-generator to create a entity that have a attribute enumeration (enum java), I get an error when click on Menu of entity in Angular.
In fact, nothing happens. In the file "...src\main\webapp\app\entities\myentity\myentity.state.js" I have, in part, the code:

```        
        resolve: {
            translatePartialLoader: ['$translate', '$translatePartialLoader', function ($translate, $translatePartialLoader) {
                $translatePartialLoader.addPart('myEntity');
                $translatePartialLoader.addPart('');
                $translatePartialLoader.addPart('global');
                return $translate.refresh();
            }]
        }
```

When I remove this line: $translatePartialLoader.addPart(''); Everything works well. This would be expected behavior or is it a bug?
Ps. In entities that do not have enumeration (enum java type) this line is not generated.

.yo-rc.json File:

{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "finame",
    "packageName": "br.com.finame",
    "packageFolder": "br/com/finame",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "7cd65d49249f429c58d1d04359454b1c7b2bfb0c",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br",
      "en"
    ]
  }
}

**Comment by rraraujop** [comment]
Gerald said that:

> without it, the enumerator labels will not show correctly when adding/editing an entity. the dropdowns will say something like myApp.myEnum.VALUE instead of just VALUE.

So, the code generator should have created the following code:

```
            resolve: {
                translatePartialLoader: ['$translate', '$translatePartialLoader', function ($translate, $translatePartialLoader) {
                    $translatePartialLoader.addPart('enyity');
                    **$translatePartialLoader.addPart('myEnum');**
                    $translatePartialLoader.addPart('global');
                    return $translate.refresh();
                }]
            }
```

The .json internationalization files were also not generated for myEnum.

I solved the problem adding the line `$translatePartialLoader.addPart('myEnum');` and creating .json files internationalization to my enum .

**Comment by geraldhumphries** [comment]
Can you give your entity config JSON from the `.jhipster` folder?

**Comment by rraraujop** [comment]
Yes, of course! Sorry for the delay to answer your message.

`
{
    "relationships": [],
    "fields": [
        {
            "fieldName": "data",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "descricao",
            "fieldType": "String"
        },
        {
            "fieldName": "valor",
            "fieldType": "Double"
        },
        {
            "fieldName": "isLancado",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "tipoLancamento",
            "fieldType": "TipoLancamento",
            "fieldValues": "RECEITA,DESPESA"
        }
    ],
    "changelogDate": "20160422112550",
    "dto": "no",
    "service": "no",
    "entityTableName": "lancamento",
    "pagination": "no",
    "microserviceName": "finameapi",
    "searchEngine": "no"
}
`

**Comment by rraraujop** [comment]
[Lancamento.json.txt](https://github.com/jhipster/generator-jhipster/files/250275/Lancamento.json.txt)

**Comment by ruddell** [comment]
I generated the project and was stumped here:
`Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8080/i18n/angular-locale_pt.js`
`Resetting invalid cookie language "pt" to prefered language "pt" angular.js:13294`

It looks like the translate cookie is getting set to PT but the valid languages are PT-BR and PT-PT

**Comment by rraraujop** [comment]
Yes!! That's it. What happens is that for some reason , the PT-BR language file for internationalization ins't generated. I solved the problem adding the line $translatePartialLoader.addPart('myEnum'); and creating .json files internationalization to my enum.

**Comment by deepu105** [comment]
So this is happening only for pt-* languages?  I guess i know why let me
take a look

**Comment by deepu105** [comment]
@andidev I guess problem is with `this.nativeLanguageShortName = this.enableTranslation && this.nativeLanguage ? this.nativeLanguage.split('-')[0] : 'en';` as we are splitting the language key at `-` and hence languages like `pt-*` and `zh-*` are having issues coz the angular locale files are ending with `pt-pt` notation but in config we set `$translateProvider.preferredLanguage('<%= nativeLanguageShortName %>');`.

Any idea?  why do we require the `nativeLanguageShortName `?

**Comment by deepu105** [comment]
@rraraujop can you verify if it works for you with latest master branch

**Comment by ruddell** [comment]
@deepu105 I can confirm this issue is fixed in master, the cookie is set to `pt-br` and the translations appear correctly.

**Comment by deepu105** [comment]
Thanks @ruddell

**Comment by rraraujop** [comment]
Worked perfectly. Thank you. @deepu105
