### ISSUE TITLE
Generation a project using Vagrant environment creates a broken main page

### ISSUE THREAD

**Issue by khalilj** [jhipster/generator-jhipster#3445]
Hi,

I'm using 'jhipster/jhipster-devbox' Vagrant box for my development environment, the Vagrant VM is running on VirtualBox on my Win 7 machine.

When creating a Jhipster monolith project, with most default options the server starts correctly but the mail page is not loading (chrome or IE).

JHipster version: v3.0.0

**Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**: Default files

 'jhipster/jhipster-devbox' Vagrant box for my development environment, the Vagrant VM is running on VirtualBox on my Win 7 machine.

Problem on Chrome and IE.

[files.zip](https://github.com/jhipster/generator-jhipster/files/232123/files.zip)

**Comment by pascalgrimaud** [comment]
I dont understand how you test with IE, because the OS of the devbox is ubuntu, so no IE. 
Do you mean you tried to launch IE and access to your vm?

**Comment by khalilj** [comment]
Im exposing port 8080 of the vm to the host. So i can access the server from any browser on the host.
The issue is that the main page of the generated project is blank when trying to view it via chrome or ie

**Comment by gmarziou** [comment]
Please look at the browser's console for errors and paste here if any.

**Comment by jdubois** [comment]
OK, but does it work in the Ubuntu box? Maybe you just have some port fowarding issue

**Comment by deepu105** [comment]
Or your bower install or gulp install tasks didn't run properly, try
running it again with `npm install && bower install && gulp install`

**Comment by khalilj** [comment]
Thanks guys for your answers and sorry for late response.
yo, after generating all sources, runs: npm install ; bower install
i will check if 'gulp install' is the missing part and get back to u.

**Comment by khalilj** [comment]
Thanks!
Looks like gulp install fixed the issue.
Any reason it is not run by yo same as it is running npm/bower install?

**Comment by jdubois** [comment]
You probably had a network error (it's annoying, yes!!), so when you ran it a second time it corrected the issue.

**Comment by khalilj** [comment]
Thanks again!
