### ISSUE TITLE
Login redirect is flakey (we are removing the previous state from sessionStorage before redirect)

### ISSUE THREAD

**Issue by adam-ho** [jhipster/generator-jhipster#3454]
##### **Overview of the issue**

In Firefox and Safari (IE not tested) the redirect to page after login is flakey. 
It means that clicking a link when I'm currently not logged in will not always correctly redirect to the page but leave me on the ugly unauthorised screen.

##### **Motivation for or Use Case** 

It's a common use case to click a link then log in to see the content.

##### **JHipster Version(s)** 

master branch.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

n/a

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

n/a

##### **Browsers and Operating System** 

Mac OS El Capitan, Firefox latest, Safari latest. Chrome is NOT affected.

##### **Reproduce the error** 

Create any entity in the system, go to the details screen and note the URL (eg.: http://localhost:8080/#/candidate/1). Logout and paste in the URL which will pop up the login screen.
In the affected browsers after login the user is stuck on the non-authorised screen.

##### **Related issues** 

n/a

##### **Suggest a Fix** 

EDIT: the actual issue is that we call Auth.logout() on auth-expired.interceptor.js:25. This will destroy previous state data right away, however, this method is called after the login screen pops up.
The Auth.logout() should only execute anything if we aren't already logged out.

**Comment by deepu105** [comment]
Could raise an issue on ngStorage plugin as well please?

**Comment by adam-ho** [comment]
@deepu105  I've isolated the issue and I believe it's not ngStorage after all, but us calling logout(). I believe it might be a race condition and that's why it's working on Chrome and not on Firefox reliably.

**Comment by deepu105** [comment]
May be we should do it in a promise

**Comment by deepu105** [comment]
closed via #3459
