### ISSUE TITLE
Invalid HTML is generated on details page - HR tag is not allowed in DL tags

### ISSUE THREAD

**Issue by adam-ho** [jhipster/generator-jhipster#3455]
##### **Overview of the issue**

The generator creates the entity detail HTML with HR tags within DL tags. This is not allowed according to the HTML standard. To achieve the same visual a small CSS and generator template modification is required.

##### **Motivation for or Use Case** 

W3C validation fails.

##### **JHipster Version(s)** 

master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

n/a

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

n/a

##### **Browsers and Operating System** 

n/a

##### **Reproduce the error** 

Generate entity entity and hav a look at the *-detail.html page.`<hr>` tags are embedded in the `<dl>` tag.

##### **Related issues** 

n/a

##### **Suggest a Fix** 

```
Remove <hr> from _entity-management-detail.html on ln29 and ln73 
Add the following to the main.css before ln370:

.dl-horizontal>dd {
	margin-bottom: 15px;
}

@media screen and (min-width: 768px) {
	.dl-horizontal>dt {
		margin-bottom: 15px;
	}
	.dl-horizontal>dd {
		border-bottom: 1px solid #eee;
		padding-left: 180px;
		margin-left: 0;
	}
}
```

**Comment by deepu105** [comment]
Can you do a PR please?
