### ISSUE TITLE
Error when creating many to one entity and trying to choose. 

### ISSUE THREAD

**Issue by dornala** [jhipster/generator-jhipster#3460]
##### **Overview of the issue**

When I try to create a many to one entity(car) and try to choose an (owner)one to many from  options - values are displayed as undefined. (Can't figureout if it's just happening to me)

##### **Motivation for or Use Case** 

This is a sample jdl file I am getting error with
```
relationship OneToMany {
  Owner{car} to Car{owner(ownerName)}
}

entity Car{
  Cname String required
  Cmodel String required
}

entity Owner{
	Oname String required,
    Ozip Integer
}
```

When I browse web - > Entity Car -> Create Car -> Try choosing previously created owners (All are shown as undefined)

##### **JHipster Version(s)** 

3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```

{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "testmod",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "70a249ee0517c65aeee02fc85c91558ccf5738f1",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

> owner.json
> 
> car.json

##### **Browsers and Operating System** 

Windows 10 Pro
Google Chrome & IE11

##### **Reproduce the error** 

None

##### **Related issues** 

No Idea (I had a look, but found single letter Issue.)

##### **Suggest a Fix** 

Can't figure out :(

**Comment by dornala** [comment]
I think issue is within my machine. My other machine works fine..

**Comment by dornala** [comment]
I tested with same .yo.json guys. Getting same error. Can someone please check.

**Comment by jdubois** [comment]
That's normal, you use `owner(ownerName)` when the name of the owner is `Oname`

You need to use one of the properties you have defined, otherwise, indeed, it will appear as `undefined`

**Comment by dornala** [comment]
lol hahaha So silly.. Thank you @jdubois
