### ISSUE TITLE
Mandatory checkboxes fails validation

### ISSUE THREAD

**Issue by lusorio** [jhipster/generator-jhipster#3471]
##### **Overview of the issue**

When generating mandatory Boolean values in an entity, which translates to checkboxes in the client side, validation fails as default NON checked value is `null` and not `false`

##### **JHipster Version(s)** 

3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "test",
    "packageName": "com.test.api",
    "packageFolder": "com/test/api",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "es"
    ]
  }
}
```

##### **Browsers and Operating System** 

OSX Yosemite / Chrome 50

##### **Reproduce the error** 

Create a property boolean in one of your entities and add the `required` validation

Then go to the app and try to create an element with the checkbox unchecked.

Validation fails

##### **Related issues** 

Didn't find

##### **Suggest a Fix** 

**1.-** I tried to add `ng-false-value="{{ false }}"` but it didn't work, probably because I did something wrong but it would be a solution.

**2.-** As angular doesn't sets the value for undefined properties in the bind model until a change is set, I set the property to false by default in the controller.

```
vm.entity = {
            isPro: false,
            isTutored: false
        };
```
and it works fine.

**Comment by lluiscanals** [comment]
I think it is working out of the box. Entity structure is resolved in entity.state.js file in "entity.new" state. There is set to false by default.

**Comment by lusorio** [comment]
You're totally right. I actually checked this in a modified entity. I don't follow the same workflow list/detail/new and I'd deleted some states in the file. My bad! this is to be closes then.

Thanks!
