### ISSUE TITLE
Lombok dependency for LoC reduction

### ISSUE THREAD

**Issue by imTachu** [jhipster/generator-jhipster#3476]
##### **Overview of the issue**

Lombok dependency could be included in order to reduce the generated LoC and to have 'cleaner' java classes. 

##### **Motivation for or Use Case** 

This issue is just a suggestion since everything works fine now... Lombok allows you to annotate variables and classes in order to generate getters, setters, toString, equals and hashcode. An example:

`@Getter`
`@Setter`
`private String name;`

This will generate the getter and setter for the variable name ONLY in the .class... The .java file will be clean and in the variable definition itself you can see if it already has those methods.

`@Getter`
`@Setter`
`public class AnyClass ...`

By annotating a class, you will automatically have getters and setters for everybody.

See also: @Data, @ToString @EqualsAndHashCode 
https://projectlombok.org/

##### **JHipster Version(s)** 

v3.0.0

##### **Browsers and Operating System** 

Chrome 49 over Windows 8.1

**Comment by mallim** [comment]
Does mapstruct able work with lombok?

**Comment by notflorian** [comment]
I'm afraid lombok is not compatible with Java 9 : https://groups.google.com/forum/#!topic/bazel-discuss/ZRWdqJfYEPw

Also, the author of this library wrote this in Reddit a long time ago :

> I'm the author of project lombok.
> It's a total hack. Using non-public API. Presumptuous casting (knowing that an annotation processor running in javac will get an instance of JavacAnnotationProcessor, which is the internal implementation of AnnotationProcessor (an interface), which so happens to have a couple of extra methods that are used to get at the live AST).
> On eclipse, it's arguably worse (and yet more robust) - a java agent is used to inject code into the eclipse grammar and parser class, which is of course entirely non-public API and totally off limits.
> If you could do what lombok does with standard API, I would have done it that way, but you can't. Still, for what its worth, I developed the eclipse plugin for eclipse v3.5 running on java 1.6, and without making any changes it worked on eclipse v3.4 running on java 1.5 as well, so it's not completely fragile.

Cleaner is not always better if it is then harder to debug, or understand the real code executed by the JVM, without having to decompile the class. Also, the java code is no more portable without having to include the lombok dependency, and can cause confusion when sharing code.

I had a bad experience with an Android Library who did the same thing than lombok, and I lost a lot of time debugging edge case, so I'm very suspicious now when I see Annotation Processing to enhance the class bytecode. I'm also afraid there might be some bugs with other libraries use in JHipster, like Mapstruct, Jackson, Hibernate, Liquidbase and with the IDE.

@imTachu Do you use it in a production application?

**Comment by atomfrede** [comment]
See some of our issues: #2734 #1334 #907 #664
So I'm sorry we don't (and won't) support lombok.

**Comment by imTachu** [comment]
Got it. This was really a duplicate... My bad.

**Comment by jdubois** [comment]
No problem @imTachu that was a good intention!
In more recent code I've been really annoyed by Lombok (again!) in Spring Boot classes, as IDEA sees the source code of the class doesn't match the class, so debugging is really annoying... In the end I have red stuff all over the place in my IDE... This is really more trouble than what it solves :-(

**Comment by Blarne** [comment]
Lombok compatibility with JDK9:
https://projectlombok.org/download-edge.html

**Comment by funder7** [comment]
Hi, before opening a new feature request I came across this one. Actually I'm using lombok in a jHipster project, it seems to work well, no problem whatsoever since now. 

The unique problem is having to remove every piece of code when I update an entity or so and re-import the JDL. 
It's not something that you do every day, but it would really nice to have a `--with-lombok` flag.

Cheers

**Comment by pascalgrimaud** [comment]
It can be done in a blueprint, so feel free to start it, if you need it.
There are a lot of people who loves Lombok, so I'm pretty sure you can get some help.

From my side, I'm totally against adding Lombok flag or something else in main JHipster as I got too much problem with this, in  real projects for my customers.

**Comment by funder7** [comment]
That's a nice idea, I will consider it in case I will have some time. Cheers!
