### ISSUE TITLE
Bower Problem

### ISSUE THREAD

**Issue by sabrineZhr** [jhipster/generator-jhipster#3477]
Hello, 
I created my first jhipster project. When I wanted to run my project executing gulp, this error appears:
Error: Cannot find where you keep your Bower packages.

Any Idea ? 
Thank you

**Comment by deepu105** [comment]
Please follow our [guidelines ](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#issue) when opening issues if you want us to help you.
For bug reports please follow the template pre populated [here](https://github.com/jhipster/generator-jhipster/issues/new)
Open a new issue with proper details or update this issue with all details and request to re open.
Issues opened without proper details will be closed without explanation.
