### ISSUE TITLE
[FEATURE] Add Option for Spock Tests

### ISSUE THREAD

**Issue by jmcshane** [jhipster/generator-jhipster#3481]
I really enjoy the [Spock framework](http://spockframework.github.io/spock/docs/1.0/index.html) for unit testing Java applications as well as the [Spock reports](https://github.com/renatoathaydes/spock-reports) module developed alongside the framework.  I am putting this issue out to see if there are other developers that would be interested in using this framework for testing rather than jUnit, providing another option like:

    #. Which unit testing framework would you like to use?
        ( ) JUnit
        ( ) Spock

If other people are interested, I would be willing to spend some time to investigate how to add this feature.

**Comment by jdubois** [comment]
Would this be a full replacement for what we currently do with JUnit?
I don't know this well enough, but couldn't this be another of the existing options with Gatling, Cucumber and Protractor? In that case, that would be a lot easier to add, as we already have the multiple choice question.

**Comment by jmcshane** [comment]
I generally use Spock in place of JUnit for all my Java projects.  I can give you an example from the code.  In `SecurityUtilsUnitTest`, there is a method named `testIsAuthenticated`.  Here is that method in Spock:

     def `authenticate username password token for admin user`()  {
	    given: 'An empty security context'
	    def securityContext = SecurityContextHolder.createEmptyContext()
	    when: 'Set authentication for admin user'
	    securityContext.setAuthentication(new UsernamePasswordAuthenticationToken('admin', 'admin'))
	    SecurityContextHolder.setContext(securityContext)
	    then: 'SecurityUtils returns isAuthenticated'
	    true == SecurityUtils.isAuthenticated()
	}

Spock allows you to be both more verbose with testing while doing more with each line of code.  The `where` syntax of Spock could join the `testIsAuthenticated` and `testAnonymousIsNotAuthenticated` methods into one:

    @Unroll
	class SecurityUtilsSpec extends Specification {
		
		def 'correctly identifies whether user #user is authenticated'() {
			given: 'An empty security context'
		    def securityContext = SecurityContextHolder.createEmptyContext()
		    when: 'Set authentication for user'
		    securityContext.setAuthentication(new UsernamePasswordAuthenticationToken(username,password))
		    SecurityContextHolder.setContext(securityContext)
		    then: 'SecurityUtils returns isAuthenticated'
		    auth == SecurityUtils.isAuthenticated()
		    where: 'The user and password is given'
		    username    | password    | auth
		    'admin'     | 'admin'     | true
		    'anonymous' | 'anonymous' | false
		}
	}

**Comment by jdubois** [comment]
Yes I understand that, but I don't want yet another question in the generator, we already have too many of them.
So if it's possible to include Spock with the other (optional) test frameworks, that would be easy to add. But if it replaces JUnit, then that means another question, and that would be annoying (at least you wouldn't get my vote on this, but I'm not the only one deciding).

**Comment by jmcshane** [comment]
I understand that, I wasn't sure where the JHipster team stood on the current status of the question sequence.

There is an option where it would not be necessary to add a new question. The logic could be that if Spock is selected in the list of optional test frameworks then the JUnit tests are excluded in place of Spock.  Would that be more acception?

**Comment by jdubois** [comment]
My issue is that we currently have a lot of questions.
Yes we could have a Spock in the list of "optional" test framework, but why remove the current JUnit tests? We have a lot of them, and we are not going to maintain 2 sets of tests.

**Comment by deepu105** [comment]
Yes im also not in favour of maintaining 2 sets of tests for the same
purpose and no vote for adding new question as well. So it should be either
just junit or spock if there is an advantage.

Why do you say spock is better than junit?

**Comment by jmcshane** [comment]
Deepu, I can provide my opinions on Spock and I'd encourage giving it a try to see what you think.  My first argument for Spock is more philosophical than technical. As Java hipsters, there's no more hipster testing library than Spock Framework.

1. Its name is Spock.
2. Spock code looks clean when written out.
3. It produces cool looking reports using Spock Reports, which can be customized using javascript and css (double hipster :) ).

On the more technical side, here are some of the advantages of Spock:

1. Provides multiple methods for providing data to tests in a flexible manner, through the `@Unroll` annotation and data pipes.
2. Spock reports provide a holistic view into the application, reading like descriptions of application code.
3. Spock mocking works well with spring `@Autowire` and allow a reduction in reflection libraries, which I find to be an antipattern (but there are strong arguments on each side)
4. Testing REST APIs in integration tests is easy using the [HttpBuilder](https://github.com/jgritman/httpbuilder) library and the `@EnvironmentEndPoint` extension.

**Comment by jdubois** [comment]
We are just not going to change the default testing framework for everyone, and re-code all the tests. This is a huge work, which would impact a lot of people.

It's just not possible.

The only way we could add Spock, is to have it as an option, with the other optional test frameworks, like for example Cucumber.

**Comment by jmcshane** [comment]
By my count, you have 13 JUnit tests written in this repository, excluding the optional test frameworks  If there are plugins that use Junit, they could continue to do so.  On top of that, the code coverage of a basic project with 1 entity is actually fairly slim (<50%).

I understand if you don't want to change, I just wanted to pose the question. I don't want to spend a couple days creating a PR for Spock if it will be rejected outright, but if there will be at least a healthy discussion I'd be willing to spend some time on it.

**Comment by jdubois** [comment]
Yes, but those tests are already quite a lot of work for us.
Besides, with more than 200,000 downloads, you can understand we can't remove JUnit support for everyone.

If you had Spock as an option, in the existing list of optional test frameworks, like Cucumber or Gatling, there is no reasons for us not to include it.

Then, if you really want to be free on what you do, and not rely on us, I have a much better solution for you: you should do [a module](http://jhipster.github.io/modules/marketplace/#/list). For your use-case, that would be very easy to do. And there is no validation, everyone is free to publish a module, it's all automated, free and open.

**Comment by jmcshane** [comment]
Thanks Julien, I think I'll do that.  Have a good one.

**Comment by jdubois** [comment]
Yes thanks @jmcshane -> this is the best solution in your case, and it was made specifically for this kind of purpose.
