### ISSUE TITLE
Cucumber task created in `build.gradle` when not Cucumber selected

### ISSUE THREAD

**Issue by jmcshane** [jhipster/generator-jhipster#3482]
##### **Overview of the issue**

Some cucumber information shows up in `build.gradle` even when cucumber is not selected.

##### **Motivation for or Use Case** 

Clean `build.gradle` files are essential to help developers understand what is going on in the project.

##### **JHipster Version(s)** 

3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

    {
          "generator-jhipster": {
            "jhipsterVersion": "3.1.0",
            "baseName": "appregistry",
            "packageName": "com.element.appregistry",
            "packageFolder": "com/element/appregistry",
            "serverPort": "8080",
            "authenticationType": "session",
            "hibernateCache": "ehcache",
            "clusteredHttpSession": "no",
            "websocket": "no",
            "databaseType": "sql",
            "devDatabaseType": "h2Disk",
            "prodDatabaseType": "mysql",
            "searchEngine": "elasticsearch",
            "buildTool": "gradle",
            "enableSocialSignIn": false,
            "rememberMeKey": "",
            "useSass": true,
            "applicationType": "monolith",
            "testFrameworks": [],
            "jhiPrefix": "jhi",
            "enableTranslation": false
          }
        }

##### **Browsers and Operating System** 

Windows 7 Professional

##### **Reproduce the error** 

Create a JHipster project selecting Gradle option without cucumber test.

##### **Suggest a Fix** 

I have created a PR for it, linked below.

**Comment by jmcshane** [comment]
See #3484

**Comment by deepu105** [comment]
Thank you
On 28 Apr 2016 07:46, "James McShane" <notifications@github.com> wrote:

See #3484 <https://github.com/jhipster/generator-jhipster/pull/3484>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/3482#issuecomment-215265959>
