### ISSUE TITLE
Update Node.js (and npm) version of generated .travis.yml file

### ISSUE THREAD

**Issue by rodrigomaio** [jhipster/generator-jhipster#3485]
`.travis.yml` file is currently being generated with Node.js version 0.12, which is outdated and does not build correctly. Current LTS version is 4.4.3

**Comment by deepu105** [comment]
No it is with latest LTS which branch are you looking at?

**Comment by rodrigomaio** [comment]
The file on the project itself is updated, but the generated file from the template is not.

**Comment by atomfrede** [comment]
As the PR is merged, I'll close this issue. Thanks @rodrigomaio
