### ISSUE TITLE
How to use single jhipster application with multiple entitymanagers which can be switched dynamically?

### ISSUE THREAD

**Issue by Devalparekh** [jhipster/generator-jhipster#3487]
As per my requirement I need to create multiple entity manager in one application with different db connection.

I am looking for something similar as below. In this example we can define multiple db connection in persistence.xml file with different unit name and create entity manager, I don't know how to implement this same with jhipster?

@PersistenceContext(unitName="myFistUnit")  
EntityManager fistEm;  

@PersistenceContext(unitName="mySecondUnit")  
EntityManager secondEm;

**Comment by jdubois** [comment]
- This is not a bug, this should be on StackOverflow
- And this is a [cross post with StackOverflow](http://stackoverflow.com/questions/36905508/how-to-use-single-jhipster-application-with-multiple-entitymanagers-which-can-be) -> please just post your question at one place, and that right place for this question is Stackoverflow
