### ISSUE TITLE
Translate user-management&social for zh-cn

### ISSUE THREAD

**Issue by flying3615** [jhipster/generator-jhipster#3488]
##### **Overview of the issue**

Help to translate user-management.json & social.json for zh-cn

##### **Motivation for or Use Case** 

I'm using jhi-alert as a pop-up for notice Chines users to know user status has been modified, but the lang is always in English, so I have to translate them by myself

##### **JHipster Version(s)** 
3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "QuayPS",
    "packageName": "com.centling.qps",
    "packageFolder": "com/centling/qps",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "4b5d3ac04bf9a4c8ac332904213fda5e847fdd48",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}

##### **Browsers and Operating System** 

Win10+Chrome

##### **Reproduce the error** 

I added a translate attribute in alter.directive.js aiming to translate user management feedback into Chinese, but it always return in English

` var jhiAlert = {
        template: '<div class="alerts" ng-cloak="">' +
                        '<div ng-repeat="alert in $ctrl.alerts" ng-class="[alert.position, {\'toast\': alert.toast}]">' +
                            '<uib-alert ng-cloak="" type="{{alert.type}}" close="alert.close($ctrl.alerts)"><pre **translate="{{alert.msg}}"**></pre></uib-alert>' +
                        '</div>' +
                  '</div>',
        controller: jhiAlertController
    };`
##### **Suggest a Fix** 

Open a small feature to support Chinese

**Comment by deepu105** [comment]
If you think any translations are incorrect please open a PR to correct them, we do not know Chinese and hence wont be able to help to give correct translations. The alert message is already translated if the keys have translated content

**Comment by flying3615** [comment]
OK, I will open a PR to add new Chinese translation for user-management
