### ISSUE TITLE
Enable strict-di on app generated

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3490]
As per https://docs.angularjs.org/guide/production seems enabling `ng-strict-di` will give some performance improvement. we need to try this out

**Comment by wmarques** [comment]
It's working in a basic monolithic app, I only needed to add `/* @ngInject */` in uib-pagination.config file. But how can we add strict-di only in prod env ?

**Comment by deepu105** [comment]
I think we can have strict DI on dev as well its a good practice

**Comment by wmarques** [comment]
So we can't use ngInject as it's only done in gulp build part, so I'll add $inject manually when we forgot to put it :)

**Comment by deepu105** [comment]
I already did for both files, also moved the config files to block folder

**Comment by deepu105** [comment]
add if $inject is missing on any other files

**Comment by deepu105** [comment]
here https://github.com/jhipster/generator-jhipster/commit/36cdc32265f2e46cb2268bcf133868b54e8d8cd9

**Comment by wmarques** [comment]
Oh yes just saw this, I rebased, I'm waiting for travis tests to check all configs with strict-di mode

**Comment by deepu105** [comment]
@wmarques did you forget to PR?

**Comment by wmarques** [comment]
@deepu105 Sorry ! Totally forgot to PR haha, thanks it's done :smile:

**Comment by jdubois** [comment]
Since we migrated to "strict di" we have errors in the console, I'm adding a ticket for that and link to this issue -> should we rollback this for our next release, or correct the errors?

**Comment by deepu105** [comment]
I have fixed the errors

Thanks & Regards,
Deepu
