### ISSUE TITLE
Feature suggestion:  re-organise back-end structure

### ISSUE THREAD

**Issue by TonyLuo** [jhipster/generator-jhipster#3496]
I would like to suggest re-organise back-end structure to improve folder cohesion:

main
｜－java 
｜ ｜－account
｜ ｜ ｜－－domain
｜ ｜ ｜－－dto
｜ ｜ ｜－－repository
｜ ｜ ｜－－－｜search
｜ ｜ ｜－－resource
｜ ｜ ｜－－service
｜ ｜－audits
｜ ｜ ｜－－domain
｜ ｜ ｜－－dto
｜ ｜ ｜－－repository
｜ ｜ ｜－－－｜search
｜ ｜ ｜－－resource
｜ ｜ ｜－－service

**Comment by deepu105** [comment]
I dont think we will do a folder restructure at this point.

**Comment by jdubois** [comment]
And I'm happy with the current folder structure.
Doing "one package per feature" would also cause other issues, like usually a lot of package tangling - it's not that our current structure is perfect, but this is what most people are doing, and we try to have something which is the less surprising as possible.

**Comment by TonyLuo** [comment]
thanks for replying. 
 I think we can put the common use classes  into common package to avoid  package tangling .
 Meanwhile package by layer would cause low cohesion and low modularity, with high coupling between packages.
FYI
https://www.oracle.com/webfolder/s/delivery_production/docs/FY14h1/doc6/10-Konstantinos-Kapelonis.pdf
