### ISSUE TITLE
Gulp keeps changing index.html on gulp-inject, which messes up VCS

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [jhipster/generator-jhipster#3499]
##### **Overview of the issue**
The Gulp that is used for development (reloads browser on file change) is changing the index.html (injecting the js files). The problem is the files are injected in different order every time, so even when there is no actual change,  the index.html is marked by VCS as modified.

This leads to messing up the versioning (e.g. I want to find a commit with an important change in this file and it is shown in every commit that involved change of angular .js files).

##### **JHipster Version(s)** 
`3.1.0`

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
...
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "8dab5f27baaec77194f7d482be9866580412018c",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "cs"
    ]
  }
}
```
##### **Browsers and Operating System** 
`Windows 7`, `Opera`, `Chrome`

##### **Reproduce the error** 
Run jhipster app, run gulp, change an Angular controller (e.g. home.state.js).

##### **Suggest a Fix** 
Ensure the order of injected files; inject only missing ones...

**Comment by deepu105** [comment]
Yes it seems to be the current behaviour. I think we need to open an issue
to angular file sort plugin

Thanks & Regards,
Deepu

**Comment by WhyINeedToFillUsername** [comment]
Ok, thanks :)

**Comment by wmarques** [comment]
They seem to found how to fix it by using `gulp-natural-sort` : https://github.com/klei/gulp-angular-filesort/issues/17#issuecomment-69228964

**Comment by jdubois** [comment]
[Gulp natural sort](https://github.com/emgeee/gulp-natural-sort) has only got 12 stars... Is that really a random order?

**Comment by deepu105** [comment]
Its a very simple plugin (few lines of code), which has a very specific use
case so I wouldn't mind using it even if stars are less as it would solve
the issue for us. But we can first check if there is a more popular
alternative first.

**Comment by jdubois** [comment]
OK, but is this really random, like every time you have something else generated?
Otherwise OK for me, let's not lose too much time here

**Comment by deepu105** [comment]
Its random for files which has same level of dependency so yes its
irritating for the version control. So IMO we should do this, and if you
are ok  I'll do il this tomorrow

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/commit/3010d7e52de8072ba910c35d5d0bf13c4e9cfc0b
