### ISSUE TITLE
[FEATURE] externalize oauth2 config

### ISSUE THREAD

**Issue by ddewaele** [jhipster/generator-jhipster#3504]
##### **Overview of the issue**

Currently, the Oauth2Server config is a mix of properties coming from jHipsterProperties and hardcoded values.

```
        @Override
        public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
            clients
                .inMemory()
                .withClient(jHipsterProperties.getSecurity().getAuthentication().getOauth().getClientid())
                .scopes("read", "write")
                .authorities(AuthoritiesConstants.ADMIN, AuthoritiesConstants.USER)
                .authorizedGrantTypes("password", "refresh_token", "authorization_code", "implicit")
                .secret(jHipsterProperties.getSecurity().getAuthentication().getOauth().getSecret())
                .accessTokenValiditySeconds(jHipsterProperties.getSecurity().getAuthentication().getOauth().getTokenValidityInSeconds());
        }
```

Proposal is to also externalize the scopes / authorities / authorizedGrantTypes

##### **Motivation for or Use Case** 

A more consistent experience and more flexible solution. 
(for ex: I also allow client_credentials as an authorized grant type). Would be nice to configure this without code changes.

##### **JHipster Version(s)** 

3.1

##### **Suggest a Fix** 

Externalize these properties using ```jHipsterProperties.getSecurity()```

**Comment by jdubois** [comment]
Yes agreed, we could have more JHipster properties for this.

**Comment by ddewaele** [comment]
I'll do a PR.

**Comment by jdubois** [comment]
@ddewaele any update on your PR?
Otherwise shouldn't this be a standard Spring Boot configuration, and not a JHipster one? Maybe you could open this up on Spring Boot, and do the PR there?

**Comment by jdubois** [comment]
Closing this as we have no news for more than 3 months.
