### ISSUE TITLE
[FEATURE] Entity generator selection option tag for a dropdown selection style box

### ISSUE THREAD

**Issue by bflew** [jhipster/generator-jhipster#3513]
##### **Overview of the issue**

There is no way to generate a selection options box for a data type of string (input field only). This makes it difficult to set options for users to select that can be miss typed. Such as Public and Private configuration parameters. I propose the ability to choose the html form element types for the specified data type on the entity (data input form) generation.

##### **Motivation for or Use Case** 

I would like to specify for the user using my entity options for configuration parameters such as private and public for a type of string that cannot be changed or miss typed by the user, and entered into the database as usual. The ability to choose a angular ui widget for a relevant data type on generation and populate it (not sure how that would work when using JDL import unless it prompts for confirmation). I am creating a broadcast stream and would like to have the user select one or the other options without typing it incorrectly.

##### **JHipster Version(s)** 

JHipster Version: 3.1.0

##### **Suggest a Fix** 

A fix could be manually changing it from input box to selection box and setting the options but it kind of defeats the purpose of using the generator in a way, and re-generation of an entity for framework updates would be broken due to customization.

**Comment by deepu105** [comment]
You can use the enum option to get the same behaviour. We wont be adding this to the string field as there is no much value in doing this.

**Comment by sarbajeet1** [comment]
Mannual will be good
