### ISSUE TITLE
Page redirection requirement

### ISSUE THREAD

**Issue by abhi314** [jhipster/generator-jhipster#3514]
##### **Overview of the issue**
I wish to give login page to authenticate the user and then redirect it to jHipster created page.
My requirement is to change login from index.html to login.html but i do not know what changes will be required to be done for it. 
This is not a bug but any help will be appreciated

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "vconnect",
    "packageName": "com.zenfact.vconnect",
    "packageFolder": "com/zenfact/vconnect",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "559bbe3167552d040ba24d16506d389a7ba851c3",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn",
      "fr",
      "hi",
      "ja"
    ]
  }
}

**Comment by jdubois** [comment]
This is not a bug, please use StackOverflow
