### ISSUE TITLE
web.rest.util.HeaderUtil#createFailureAlert has unused parameter

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [jhipster/generator-jhipster#3517]
##### **Overview of the issue**
The method web.rest.util.HeaderUtil#createFailureAlert in generated app has a parameter, that is not used even though it is being set in the app (e.g. in EntityResource).

The parameter's name suggest it should set default alert message (as I intended to use it). I use i18n.

##### **Motivation for or Use Case** 
I want to have a method for alerting entity creation failure, that does not have translation.

##### **JHipster Version(s)** 
3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
...
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "8dab5f27baaec77194f7d482be9866580412018c",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "cs"
    ]
  }
}
```

**Comment by jdubois** [comment]
If you use i18n, then you need to have the translation.

**Comment by WhyINeedToFillUsername** [comment]
So why is the method there? Is it being used in apps without i18n and just stays there when you generate an app with i18n?

**Comment by jdubois** [comment]
There is only one method `createFailureAlert(String entityName, String errorKey, String defaultMessage)`, which has an error key, looks OK to me.
@deepu105 has you coded this, you might have a comment?

**Comment by deepu105** [comment]
Yes its the default message used when translation is not found. Ill take a closer look later to see if there is an issue.

**Comment by WhyINeedToFillUsername** [comment]
Well there is this code in the generated `HeaderUtil`:
```
public static HttpHeaders createFailureAlert(String entityName, String errorKey, String defaultMessage) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("X-tidyUpApp-error", "error." + errorKey);
        headers.add("X-tidyUpApp-params", entityName);
        return headers;
    }
```
As you can see, the param `defaultMessage` is not used, but is passed e.g. at `web.rest.AccountResource#saveAccount`:
```
return ResponseEntity.badRequest().headers(HeaderUtil.createFailureAlert("user-management", "emailexists", "Email already in use")).body(null);
```

**Comment by deepu105** [comment]
@WhyINeedToFillUsername the param is passed for 2 purpose
1. to make the method more readable, if only a key is passed you have to go look at the front end files to see whats the message
2. to simplify i18n false cases, so that we need not have too many switches in place.

Any way to make better use of the param I have added a log statement here https://github.com/jhipster/generator-jhipster/commit/d05890c08d17541dc1fb599a1a97284473ea7e2d
