### ISSUE TITLE
UI shows extra comma on image/binary blob fields

### ISSUE THREAD

**Issue by raphaelbrugier** [jhipster/generator-jhipster#3519]
##### **Overview of the issue**

There is an extra comma shown in the UI for image and binary fields:

<img width="951" alt="screen shot 2016-05-02 at 5 19 53 pm" src="https://cloud.githubusercontent.com/assets/579318/14968829/023a7abe-108d-11e6-9b6b-a619fbea45d4.png">

##### **JHipster Version(s)** 
v3.1

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

.jhipster/Task.json 
```
{
    "relationships": [],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String"
        },
        {
            "fieldName": "content",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "image",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "binContent",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        }
    ],
    "changelogDate": "20160502204230",
    "dto": "no",
    "service": "no",
    "entityTableName": "task",
    "pagination": "no"
}
```

##### **Suggest a Fix** 

The problem comes from this code:
```
<div class="help-block clearfix">
                    <span class="pull-left">{{vm.task.imageContentType}}, {{byteSize(vm.task.image)}}</span>
                    <button ng-click="vm.task.image=null;vm.task.imageContentType=null;"
                            ng-if="vm.task.image"
                            class="btn btn-default btn-xs pull-right">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                </div>
```

Also, after uploading an image and then trying to edit the entity, the directive `{{byteSize(vm.task.image)}}` doesn't show anything.

I can try to fix these but I don't know how it worked before?
The help-block div doesn't exists for the other field types, so I'm wondering if it was forget after a refactoring.

**Comment by andidev** [comment]
```
{{byteSize(vm.task.image)}}
```
should be
```
{{vm.byteSize(vm.task.image)}}
```

and maybe 
```
<span class="pull-left">{{vm.task.imageContentType}}, {{byteSize(vm.task.image)}}</span>
```
should be
```
<span class="pull-left" ng-if="vm.task.image">{{vm.task.imageContentType}}, {{byteSize(vm.task.image)}}</span>
```
not sure about if the last one will hide the coma though

**Comment by raphaelbrugier** [comment]
Thanks for the insights, I'll propose a PR for these.
