### ISSUE TITLE
Using API in external application 

### ISSUE THREAD

**Issue by sabrineZhr** [jhipster/generator-jhipster#3522]
##### **Overview of the issue**
I am trying to call the generated API in another SPA(written with angularjs) and I am getting 
"XMLHttpRequest cannot load http://127.0.0.1:8080/api/scopes. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 401."

##### **Motivation for or Use Case** 
Use the API generated by jhipster in a SPA.

##### **JHipster Version(s)** 

jhipster version : 3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "Hello",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

No
##### **Browsers and Operating System** 

There no errors related to versions

##### **Reproduce the error** 

No

##### **Related issues** 

No

##### **Suggest a Fix** 

I have to change something in Spring Security or to call the API in angularJs with the parameter specified but I don't know how.

**Comment by jdubois** [comment]
Not a bug, please use StackOverflow, read the old issues, and *follow our guidelines*

**Comment by sabrineZhr** [comment]
Thank you for your help ! :+1:

**Comment by jdubois** [comment]
Sorry I know you're unhappy, but if nobody follows our guidelines, we can't make the project move forward.
Please remember this is OSS and we do this on our free time.
