### ISSUE TITLE
Is it possible to create connection objects?

### ISSUE THREAD

**Issue by Jumblemuddle** [jhipster/generator-jhipster#3526]
Is it possible to have a 'connection' object between two other objects of the same type?
I'm looking to add some extra meta data to their relationship.
E.g. A 'Friend Request' can be in three states: Pending, Accepted, Declined.

I'm attempting to do this with JDL at the moment, but can't seem to make it work.

```
entity Profile {
}
entity Connection {
    status ConnectionStatus
}
enum ConnectionStatus {
    PENDING, ACCEPTED, DECLINED
}
relationship OneToMany {
    Profile{following} to Connection
}
relationship OneToMany {
    Profile{followers} to Connection
}
```

This doesn't seem to be what I'm looking for. (At least, on the UI side) I would like the generated frontend to allow me to connect user objects to eachother and set the status of that connection.

Any thoughts? What direction should I be going?

**Comment by Jumblemuddle** [comment]
[Question]
Look like I can't add labels.

**Comment by jdubois** [comment]
Not a bug, please use Stackoverflow.

**Comment by Jumblemuddle** [comment]
My apologies.

**Comment by jdubois** [comment]
No problem, it happens all the time :-)
I just want to keep the bug list clean.
And we also follow Stackoverflow !
