### ISSUE TITLE
Blank screen on Upgrade to Jhipster 3.1

### ISSUE THREAD

**Issue by muralihr** [jhipster/generator-jhipster#3527]
##### **Overview of the issue**
 
I upgraded the Jhipster to 3.1; 
When i run I get a empty screen;

##### **Motivation for or Use Case** 
Nothing is displayed - i am surprised;

##### **JHipster Version(s)** 

3.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "m33",
    "packageName": "com.test.m3",
    "packageFolder": "com/test/m3",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "0ee8d7b8e7124405cf618dcf27965ea7bcb2117d",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi",
      "ta"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

NA

##### **Browsers and Operating System** 
chrome and windows 8
 

##### **Reproduce the error** 

install jhipster-generator
yo jhipster -  create app - 
mvn 

##### **Suggest a Fix** 
I observed that the previous index.html had all the JS files - the latest one does not seem to have the same.
Enclosing the latest index.html;

<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>m33</title>
    <meta name="description" content="">
    <meta name="google" value="notranslate">
    <meta name="viewport" content="width=device-width">
    
    
    
    
    
    
    <link rel="stylesheet" href="content/css/main.css">
    
</head>
<body ng-app="m33App">
    
    <div ng-show="{{ENV === 'dev'}}" class="development" ng-cloak></div>
    <div ui-view="navbar" ng-cloak></div>
    <div class="container">
        <div class="well" ui-view="content"></div>

        <div class="footer" ng-cloak>
            <p translate="footer">This is your footer</p>
        </div>
    </div>

    

    
    
    
    

    
    
    
    

</body>
</html>

***************
as can be seen no angular js files are included.

How do i fix the issue ?

**Comment by gtiwari333** [comment]
I had the similar issue when I upgraded to 3.1.0 from 3.0.0.

**Comment by deepu105** [comment]
I think your gulp install step failed.

Did your npm and bower install finish successfully?

anyways just run these manually
1. `npm install`
2. `bower install`
3. `gulp install`

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
let us know if you have any issue after running above

**Comment by muralihr** [comment]
Deepuuuuu - Thanks !
gulp install did the trick !

**Comment by MorlaRamakrishna** [comment]
I had the similar issue with Angular 4 Gateway application

**Comment by jdubois** [comment]
@MorlaRamakrishna this makes no sense, this ticket is about an AngularJS 1 monolith!
