### ISSUE TITLE
Feature ui-route

### ISSUE THREAD

**Issue by smoothello** [jhipster/generator-jhipster#353]
What about giving the choice in the generator between ng-route and ui-route ?

**Comment by maahelal** [comment]
A. jHipster Rocks, awesome work guys.. I found out about JHipster less than an hour ago and I'm really impressed.
B. I think you should really consider this feature for version 2.0 for, at least, the following two reasons
-ui-router is AngularJs team answer to the severe lacking of features in their ngRoute as compared to EmberJs.
-state machine based routing + multiple nested N views / state, 
do anyone need a third reason ?

-MH

**Comment by gzsombor** [comment]
It's already implemented in the master branch. If you check the code from git, you can enjoy it now!

**Comment by redoc123** [comment]
I dont see v2 released yet. The latest version I see is "1.10.2" in website. Am I missing anything?

**Comment by jdubois** [comment]
No, v2 is not released yet.
But we are not breaking the v1.x as it is in maintenance mode.

**Comment by redoc123** [comment]
Thanks for the response. Can i build the code from V2 branch and play with it? If yes how can i build it?

**Comment by gmarziou** [comment]
Have a look at the [CONTRIBUTING.md](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup) doc
