### ISSUE TITLE
[FEATURE] including jhipster-uml into the docker build 

### ISSUE THREAD

**Issue by oleg-schmidt** [jhipster/generator-jhipster#3531]
##### **Overview of the issue**
Hi,

I'm using the docker JHipster image to create and build microservices, gateway and registry. 
As the "jhipster-uml" and "maven" are not a part of docker build, I had to extend the image myself. 
Obviously, this solution will have some downsides as I don't know how the official docker image might evolve in the future. 

##### **Suggest a Fix** 

Would you guys mind to extend the docker build file with "jhipster-uml" and "maven". 

Best Regards!
Oleg

# install utilities
  apt-get install -y \
     wget \
     curl \
     vim \
     git \
     zip \
     bzip2 \
     fontconfig \
     python \
     g++ \
     build-essential \
     **maven && \**
...........
RUN \
  # install jhipster
  npm install -g /home/jhipster/generator-jhipster && \
  npm install -g jhipster-uml && \

**Comment by pascalgrimaud** [comment]
The initial goal of this image is to provide the JHipster generator. At every release, there will be a docker tag, associated to the release version.
As jhipster-uml is a different project, we would not be a good idea to have both on the same image.

But for your need, you can easily write something like:
FROM jhipster/jhipster:latest
RUN npm install -g jhipster-uml
So you can build your own image.

About Maven, same for gradle, the generator will provide wrapper so by not installing Maven, we reduce a little bit the image size.

**Comment by deepu105** [comment]
Jhipster UML is bundled with JHipster versions post 3.0 as its added as a npm dependency, so you should be able to run JHUML from within any Jhipster app, and thats the logical place were you should run it. Note JHUML wont be available globally since its added as a dependency. But this is good enough IMO. for maven just use `./mvnw` instead of `mvn`
