### ISSUE TITLE
import-jdl sub generator does not work for all the options as per document

### ISSUE THREAD

**Issue by c0nscience** [jhipster/generator-jhipster#3532]
##### **Overview of the issue**

The JDL documentation mention keywords like 'microservice' and 'skipClient'. The JDL Studio it self does not recognise them neither does the 'import-jdl' subgenerator.

##### **Motivation for or Use Case** 

Correct me if I'm wrong, but the idea behind JDL is that I can generate the domain and basic ui with it. Or am I using it wrong? 

##### **JHipster Version(s)** 
I'm using the current jhipster version 3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "playgroundDemo",
    "packageName": "io.ntf.playground.demo",
    "packageFolder": "io/ntf/playground/demo",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "gradle",
    "jwtSecretKey": "197aad57c73870745e33d590a03d46cb7454cee9",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

```
entity Task {
	id Long,
    userId Long,
    title String required,
	note String
}

entity Session {
	id Long,
    start ZonedDateTime,
    end ZonedDateTime
}

relationship OneToMany {
	Task{session} to Session{task}
}

paginate all with pagination

dto all with mapstruct

service all with serviceClass

skipClient for Task,Session
microservice all with myfancyapp
```

##### **Browsers and Operating System** 

OS: OS X 10.11.4 (El Capitan)

**Comment by deepu105** [comment]
Support for these are not yet released.

**Comment by deepu105** [comment]
@MathieuAA as discussed earlier Im still waiting for a new JHUML release or JDL update so that I can update the `import-jdl` generator to work with latest JDL

**Comment by deepu105** [comment]
Lets keep this ticket open so that we can track that

**Comment by MathieuAA** [comment]
Hi, if the sub-gen doesn't support that, that may be because the sub-gen doesn't use the JDL project? 
See [here](https://github.com/jhipster/jhipster-domain-language/commits/v1.0.1).
It's normal it's still not released in JUML as I don't have time to work as much as I'd want to.

**Comment by jdubois** [comment]
Yes that's not surprising that JHipster UML needs some time to have all the features of JHipster

**Comment by deepu105** [comment]
To be quite frank Im kind of fed up explaining this @MathieuAA we had this discussed in few other issues and in the mailing list. 
So to be frank I really dont like having JHUML as a dependency to JDL. I would rather prefer to have JDL as a standalone lib with all its required features like parsing the JDL, creating the entity jsons etc. either by duplicating the required code from JHUML or by making JDL a dependency for JHUML. 
Also I dont like having the import-jdl feature in JHipster and JHUML as it confuses the user a lot and messes up the documentation. currently the documentation has stuff that only works with JHUML and does not work with `import-jdl` sub generator so its very confusing for the user. I would like each project to do only what its meant to do.

@jdubois @MathieuAA  we need to take a decision on this to avoid lot of such discrepancy and issue in the future.

**Comment by lazaropj** [comment]
Hi everyone.

Some news about this?

I created a JDL file, I have begotten the entities from this file at my microservices. I went to my gateway app and I passed the path to my microservice but I got an error too.

**Comment by deepu105** [comment]
we are working on it.

Thanks & Regards,
Deepu

**Comment by tibistibi** [comment]
except does jet not work too

**Comment by deepu105** [comment]
This sub generator needs a major revamp based on the latest https://github.com/jhipster/jhipster-domain-language and will be done soon. Till then i'll recommend everyone to use `jhipster-uml` to import JDL using command `jhipster-uml yourFile.jdl`

**Comment by chrislovecnm** [comment]
Guys, why does the documentation reflect that this functionality is live?

> As of JHipster v3, microservices can be created

Please update the docs ;(

**Comment by jdubois** [comment]
I've updated the documentation, so that should be OK. @MathieuAA is also working on updating the sub-generator to have everything working back again.

**Comment by deepu105** [comment]
@jdubois i would prefer to keep this ticket open as we havent resolved it.
It will be solved only when we release jhipster-core and update the sub gen
to use that. If we wanted to use jhipster-uml directly then there is no
purpose of jhipster-core at all. So this is just an interim workaround.
Once we resolve the issue we should revert the documentation to make jdl
parsing a first class citizen of jhipster

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
OK @deepu105 I'm re-opening it

**Comment by splashBrother** [comment]
Hello guys, is this fix released yet? 
Using jhipstter-uml with microservice keyword in my file doesn't work(I have installed v3.4.2).
Thanks!

**Comment by ruddell** [comment]
@splashBrother A release containing this fix is currently planned for Wednesday.  https://groups.google.com/forum/#!topic/jhipster-dev/7ZtAZJKAPN8

**Comment by splashBrother** [comment]
Ok thanks for your prompt reply and for the great job!

**Comment by jdubois** [comment]
I'll do my best on Wednesday, but no promises :-)
