### ISSUE TITLE
The index.html file is blank after grulp serve

### ISSUE THREAD

**Issue by hielfx** [jhipster/generator-jhipster#3540]
##### **Overview of the issue**

When I run gradle bootRun followed by gulp serve (all throught IntelliJ) it displays a blank page and the index.html file is empty. This happens after the gulp injection.

##### **JHipster Version(s)** 

 3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "baseName": "Volunteercrowd",
    "packageName": "com.hielfsoft.volunteercrowd",
    "packageFolder": "com/hielfsoft/volunteercrowd",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhipsterVersion": "3.0.0",
    "serverPort": "8080",
    "applicationType": "monolith",
    "nativeLanguaje": "es",
    "languages": [
      "en",
      "es"
    ],
    "travis": true
  }
}

Despite the fact that it says the JHipster version is 3.0.0 I am running the 3.1.0
##### **Browsers and Operating System** 

Windows 10 and Mozilla Firefox

##### **Reproduce the error** 

1. Execute gradle bootRun throught IntelliJ in debug mode
2. Execute gulp serve throught IntelliJ in run mode
3. Look at the content of index.html and the blank page at the browser

**Comment by jdubois** [comment]
You probably had an error in your logs, like a network issue.
Without your logs we can't help you.

-> I've created ticket #3541 to help people in your case

**Comment by hielfx** [comment]
It isn't a network issue, is the index.html file wich become empty when gulp serve is executed. After ctrl+z the index.html file, it works fine

**Comment by jdubois** [comment]
Normally "gulp serve" should inject the right JS/CSS inside your index.html, that's supposed to be the solution, not the problem.

**Comment by mladenp** [comment]
I am having the same problem on my Win machine. Everything works until i run gulp i just get a blank page at http://localhost:9000/

**Comment by gmarziou** [comment]
Please don't camp on an old issue, open a new one.
