### ISSUE TITLE
[Feature] Have a default "blank page" for when generation went wrong

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3541]
We have many people complaining about a "blank page" when generation fails.

Usually this could be solved by looking at the logs, running again "jhispster --force", etc... There are already lots of tickets about that.

So my proposal is that our default page shows an error explaining those common causes, where to look at, etc. And it would be modified at the end of the generation.

**Comment by deepu105** [comment]
What we can do is put those instructions inside the ui-view tag in `index.html` like below and if everything went as it should then angular will replace it with the view content, if something fails then they will see the instructions.
```
<div class="container">
        <div class="well" ui-view="content">
                Default instructions and troubleshooting steps here
        </div>

        <div class="footer" ng-cloak>
            <p translate="footer">This is your footer</p>
        </div>
    </div>
```

**Comment by deepu105** [comment]
@jdubois do you want me to do it?

**Comment by jdubois** [comment]
Not sure about that solution, because that's for the developer and not the end-user.
I'd rather have gulp remove that, when it does the JS/CSS injection.
If the injection worked then everything worked, as npm and bower passed.

**Comment by deepu105** [comment]
Ya but when people load the app it will show the instruction like below if
something went wrong, else they will see normal content
```
if you are seeing this, it means something went wrong during the initial
setup of the application.

Please make sure the below steps have completed successfully, else please
run them in below order

steps here
```

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Ok ill try it out first and will push a PR then we can discuss on that if it needs improvement

**Comment by jdubois** [comment]
It's just that having this text in the final app is a bit risky, I wouldn't want an end-user to see those steps. That's why I would delete the text with "gulp wiredep".

**Comment by deepu105** [comment]
Ok sure, will take care of that
