### ISSUE TITLE
Migration to Spring Security 4.1.0

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3547]
Spring Security 4.1.0 was released today and will be included in the next Spring Boot minor release.
Several changes impact us, here are the release notes: http://docs.spring.io/spring-security/site/docs/4.1.x/reference/htmlsingle/#new

**Comment by lschin** [comment]
CookieCsrfTokenRepository provides simple AngularJS & CSRF integration 
http://docs.spring.io/spring-security/site/docs/4.1.x/reference/htmlsingle/#csrf-cookie

**Comment by jdubois** [comment]
Spring Boot 1.3.5 is out: https://spring.io/blog/2016/05/10/spring-boot-1-3-5-released
Need to check if it's updated with Spring Security 4.1.0

**Comment by deepu105** [comment]
Thats fast I update to 1.3.4 in the master few days back :O

Thanks & Regards,
Deepu

**Comment by notflorian** [comment]
Spring Cloud Brixton.RELEASE is also out today: https://spring.io/blog/2016/05/11/spring-cloud-brixton-release-is-available

**Comment by PierreBesson** [comment]
@notflorian This is very good news.
This should really be updated and released as a new JHipster version as soon as possible.
