### ISSUE TITLE
Cannot set negative values for numeric fields of entities

### ISSUE THREAD

**Issue by oderComland** [jhipster/generator-jhipster#3549]
##### **Overview of the issue**
When trying to set negative value for minimum or maximum validation rule for numerical entity filed we get error "Minimum/Maximum must be a number".

##### **Motivation for or Use Case** 
There should be no reason for accepting only positive numbers as validation rules.

##### **Reproduce the error** 
Run:
`yo jhipster:entity Person`

Follow:
? Do you want to add a field to your entity? Yes
? What is the name of your field? some_number
? What is the type of your field? Integer
? Do you want to add validation rules to your field? Yes
? Which validation rules do you want to add? Required, Minimum, Maximum
? What is the minimum of your field? (0) -10
>> Minimum must be a number

##### **Related issues** 
Do not know of any.

##### **Suggest a Fix** 
Change regular expression 
`if (/^([0-9]*)$/.test(input)) return true;`
to 
`if (/^(-?[0-9]*)$/.test(input)) return true;`
for validation of numeric values.

**Comment by jdubois** [comment]
Oh yes! Never tested that :-)
Could you do a pull request? And add a test for this? That would be perfect!

**Comment by oderComland** [comment]
I will do my best :-)
