### ISSUE TITLE
[FEATURE] BigDecimal should use DecimalMin and DecimalMax annotations

### ISSUE THREAD

**Issue by oderComland** [jhipster/generator-jhipster#3551]
##### **Overview of the issue**
Current implementations uses Min and Max annotations for all numeric fields. This doesn't give us a possibility for better precision for BigDecimal numbers. Currently I am not sure if this should be also applicable to float and double since [documentation](https://docs.oracle.com/javaee/7/api/javax/validation/constraints/DecimalMin.html) states that  double and float are not supported due to rounding errors (some providers might provide some approximative support). But the documentation says the same for [Min](https://docs.oracle.com/javaee/7/api/javax/validation/constraints/Min.html).

**Comment by deepu105** [comment]
this would need a bit more work
