### ISSUE TITLE
[FEATURE] Set precision and scale for entity column

### ISSUE THREAD

**Issue by oderComland** [jhipster/generator-jhipster#3552]
##### **Overview of the issue**
Currently you can not set precision and scale for entity column. When using BigDecimal there are some default parameters set:
```
@Column(name = "bigdecimalnumber", precision=10, scale=2)
private BigDecimal bigdecimalnumber;
```
but this should be possible to change. Of course this feature should  be made for entity (Column) and for validation by using [Digit](http://docs.oracle.com/javaee/6/tutorial/doc/gircz.html).
Again I am not sure about double and float. For additional information about double/float check [feature](https://github.com/jhipster/generator-jhipster/issues/3551).

**Comment by deepu105** [comment]
@oderComland what do you mean by you cannot set this currently? you can set this directly in the generated code yourself and thats how it should be done. there is no value in asking a queston for this and setting it.

**Comment by jdubois** [comment]
Closing this, with regards to [policy 2](http://jhipster.github.io/policies/)
