### ISSUE TITLE
Exception thrown when trying to generate entity with BLOB (CLOB - Text Field) fileld type.

### ISSUE THREAD

**Issue by lluiscanals** [jhipster/generator-jhipster#3553]
##### **Overview of the issue**

Exception thrown when trying to generate entity with BLOB (CLOB - Text Field) fileld type.

TypeError: Cannot read property 'toLowerCase' of undefined
    at Function.plural (/home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/pluralize/pluralize.js:134:23)
    at pluralize (/home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/pluralize/pluralize.js:161:46)
    at null.<anonymous> (/home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/generators/entity/index.js:1534:70)
    at Array.forEach (native)
    at module.exports.EntityGenerator.extend.configuring.loadInMemoryData (/home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/generators/entity/index.js:1508:54)
    at Object.<anonymous> (/home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/base.js:436:25)
    at /home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25
    at /home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:25:19
    at /home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/base.js:448:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)

##### **Motivation for or Use Case** 
  Creating an Entity
 

##### **JHipster Version(s)** 
3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "tfrm",
    "packageName": "com.dualion.tfrm",
    "packageFolder": "com/dualion/tfrm",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "60bec227c1ad152324603d021cf53a76134334b4",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ca",
      "es"
    ],
    "jhiPrefix": "jhi"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

The error is thrown before any file is created.
For debug purposes:
    - Entity name: SurveyQex
    - Field name: objectList

 Pasted before.

##### **Browsers and Operating System** 

Ubuntu 14.04

##### **Reproduce the error** 

Try to create the entity with this type field.

##### **Suggest a Fix** 

Not yet.

**Comment by deepu105** [comment]
Im unable to reproduce this, can you paste the console like below, so we can see whats going on?
```
PS D:\Projects\test\testApp> yo jhipster:entity SurveyQex

The entity SurveyQex is being created.


Generating field #1

? Do you want to add a field to your entity? Yes
? What is the name of your field? objectList
? What is the type of your field? [BETA] Blob
? What is the content of the Blob field? A CLOB (Text field)
? Do you want to add validation rules to your field? No

================= SurveyQex =================
Fields
objectList (byte[] text)


Generating field #2

? Do you want to add a field to your entity? No

================= SurveyQex =================
Fields
objectList (byte[] text)


Generating relationships to other entities

? Do you want to add a relationship to another entity? No

================= SurveyQex =================
Fields
objectList (byte[] text)



? Do you want to use a Data Transfer Object (DTO)? No, use the entity directly
? Do you want to use separate service class for your business logic? No, the REST controller should use the repository directly
? Do you want pagination on your entity? No

Everything is configured, generating the entity...

   create .jhipster\SurveyQex.json
   create src\main\java\com\mycompany\myapp\domain\SurveyQex.java
   create src\main\java\com\mycompany\myapp\repository\SurveyQexRepository.java
   create src\main\java\com\mycompany\myapp\web\rest\SurveyQexResource.java
   create src\main\resources\config\liquibase\changelog\20160506110658_added_entity_SurveyQex.xml
 conflict src\main\resources\config\liquibase\master.xml
? Overwrite src\main\resources\config\liquibase\master.xml? overwrite
    force src\main\resources\config\liquibase\master.xml
   create src\main\webapp\app\entities\survey-qex\survey-qexes.html
   create src\main\webapp\app\entities\survey-qex\survey-qex-detail.html
   create src\main\webapp\app\entities\survey-qex\survey-qex-dialog.html
   create src\main\webapp\app\entities\survey-qex\survey-qex-delete-dialog.html
 conflict src\main\webapp\app\layouts\navbar\navbar.html
? Overwrite src\main\webapp\app\layouts\navbar\navbar.html? overwrite
    force src\main\webapp\app\layouts\navbar\navbar.html
   create src\main\webapp\app\entities\survey-qex\survey-qex.state.js
   create src\main\webapp\app\entities\survey-qex\survey-qex.controller.js
   create src\main\webapp\app\entities\survey-qex\survey-qex-dialog.controller.js
   create src\main\webapp\app\entities\survey-qex\survey-qex-delete-dialog.controller.js
   create src\main\webapp\app\entities\survey-qex\survey-qex-detail.controller.js
   create src\main\webapp\app\entities\survey-qex\survey-qex.service.js
   create src\main\webapp\i18n\zh-cn\surveyQex.json
 conflict src\main\webapp\i18n\zh-cn\global.json
? Overwrite src\main\webapp\i18n\zh-cn\global.json? overwrite
    force src\main\webapp\i18n\zh-cn\global.json
   create src\main\webapp\i18n\pt-br\surveyQex.json
 conflict src\main\webapp\i18n\pt-br\global.json
? Overwrite src\main\webapp\i18n\pt-br\global.json? overwrite
    force src\main\webapp\i18n\pt-br\global.json
   create src\test\javascript\spec\app\entities\survey-qex\survey-qex-detail.controller.spec.js
   create src\test\java\com\mycompany\myapp\web\rest\SurveyQexResourceIntTest.java

Running gulp Inject to add javascript to index

[19:08:53] Using gulpfile D:\Projects\test\testApp\gulpfile.js
[19:08:53] Starting 'inject:app'...
[19:08:54] gulp-inject 108 files into index.html.
[19:08:54] Finished 'inject:app' after 954 ms
PS D:\Projects\test\testApp>
```

**Comment by lluiscanals** [comment]
canals@nasa:~/ProyectosWeb/tfrm(dbrefactor)$ yo jhipster:entity SurveyQex

The entity SurveyQex is being created.

Generating field #1

? Do you want to add a field to your entity? Yes
? What is the name of your field? objectList
? What is the type of your field? [BETA] Blob
? What is the content of the Blob field? A CLOB (Text field)
? Do you want to add validation rules to your field? Yes
? Which validation rules do you want to add? Required, Maximum
? What is the maximum of your field? 1000

================= SurveyQex =================
Fields
objectList (byte[] text) required max='1000' 


Generating field #2

? Do you want to add a field to your entity? No

================= SurveyQex =================
Fields
objectList (byte[] text) required max='1000' 

Generating relationships to other entities

? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? User
? What is the name of the relationship? user
? What is the type of the relationship? one-to-one
? Is this entity the owner of the relationship? No

================= SurveyQex =================
Fields
objectList (byte[] text) required max='1000' 

Relationships
user (User) one-to-one

Generating relationships to other entities

? Do you want to add a relationship to another entity? No

================= SurveyQex =================
Fields
objectList (byte[] text) required max='1000' 

Relationships
user (User) one-to-one



? Do you want to use a Data Transfer Object (DTO)? [BETA] Yes, generate a DTO with MapStruct
? Do you want to use separate service class for your business logic? Yes, generate a separate service interface and implementation
? Do you want pagination on your entity? No

Everything is configured, generating the entity...

TypeError: Cannot read property 'toLowerCase' of undefined
    at Function.plural (/home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/pluralize/pluralize.js:134:23)
    at pluralize (/home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/pluralize/pluralize.js:161:46)
    at null.<anonymous> (/home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/generators/entity/index.js:1534:70)
    at Array.forEach (native)
    at module.exports.EntityGenerator.extend.configuring.loadInMemoryData (/home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/generators/entity/index.js:1508:54)
    at Object.<anonymous> (/home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/base.js:436:25)
    at /home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25
    at /home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:25:19
    at /home/canals/.nvm/versions/node/v4.3.2/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/base.js:448:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by deepu105** [comment]
The issue is not with the Blob type. It works fine when i create just the blob. Issue is with the relationship. We currently only support a many-to-one relationship with user, its documented as well, and hence what you try is something which is never tested and might not work. If you want to do a one-to-one then you have to add that manually after generating your entity.

**Comment by deepu105** [comment]
@jdubois shall we remove the other relationship option from the list if entity name entered is `User`?

**Comment by lluiscanals** [comment]
Ahh, ok, thank you very much and sorry for the time!
