### ISSUE TITLE
Application doesnt load i18n files for 5 letter language codes

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3554]
Seems like i18n doesn't load any files and app fails when languages with `pt-*` pattern is selected as native language.

Seems like an issue with setting `nativeLanguageShortName` instead of `nativeLanguage`

If I change to `nativeLanguage` it works

@andidev I do not see why `nativeLanguageShortName` is required? shouldnt it be `nativeLanguage` every where?

**Comment by deepu105** [comment]
the issue https://github.com/jhipster/generator-jhipster/issues/3444 might be related as well

**Comment by andidev** [comment]
I know there was a reason for this but I don't remember why. I need to look into this further.
Maybe `nativeLanguageShortName`was only needed in one place and I thought it was needed everywhere. I can have a look at it tonight.

**Comment by deepu105** [comment]
Ok, let me know if you need any help

Thanks & Regards,
Deepu

**Comment by rraraujop** [comment]
Thanks.

**Comment by andidev** [comment]
Okey so it looks like I made a big mistake. @deepu105, you are right `nativeLanguage` should be used instead.

**Comment by jdubois** [comment]
Should we do a patch release for this?

**Comment by andidev** [comment]
@jdubois 
I would say yes. Though it only effects people in Portugal and China who would like to have an app with their native language and I don't know how common this is. 

There have been one more issues created from a guy in China about this as well.
