### ISSUE TITLE
Fix setter for all type of relationships

### ISSUE THREAD

**Issue by oderComland** [jhipster/generator-jhipster#3556]
##### **Overview of the issue**
All current setter for fileds that are in relationship do not follow jpa standard by setting both sides of relationship. This leads to [object corruption](https://en.wikibooks.org/wiki/Java_Persistence/Relationships#Object_corruption.2C_one_side_of_the_relationship_is_not_updated_after_updating_the_other_side). Also I do not think following lines of code are a good implementation: 
```
public void setPersistentTokens(Set<PersistentToken> persistentTokens) {             
    this.persistentTokens = persistentTokens;                                        
}
```
This means adding one element to persistentTokens means first call getPersistentTokens(), add single persistentToken to this set and then call setPersistentTokens(...).

##### **Motivation for or Use Case** 
Currently this is a bug because of object corruption. If you would remove current setters for fields in relationship then this would be a feature.

##### **Suggest a Fix** 
Change java template in a way that current setter for Set is replaced with functions that add/remove object from set. To get rid of object corruption just follow this [example.](https://en.wikibooks.org/wiki/Java_Persistence/Relationships#Object_corruption.2C_one_side_of_the_relationship_is_not_updated_after_updating_the_other_side)

**Comment by deepu105** [comment]
Doesn't hibernate take care of this?

**Comment by oderComland** [comment]
As far as I know this is not hibernate but [javax.persistance](https://docs.oracle.com/javaee/7/api/javax/persistence/ManyToOne.html).

**Comment by deepu105** [comment]
I know that. What I meant was since we use hibernate for the JPA
implementation doesnt it handle such cases behind the scene?

Thanks & Regards,
Deepu

**Comment by oderComland** [comment]
As far as I know hibernate does update both sides under some conditions (if you set entity from the owner side you "should" get away with it). But this is done after transaction completion and this can cause problems.
Ofc I might be wrong since I'm not a hibernate expert. But this caused me a lot of bugs in out application and I do not want to go through it again :-)

**Comment by jdubois** [comment]
This is "normal", and not a JPA mis-usage.
But indeed, it can be quite disturbing.

This hasn't been discussed yet, but my idea is to use [this new Hibernate 5 feature](http://docs.jboss.org/hibernate/orm/5.1/userguide/html_single/Hibernate_User_Guide.html#BytecodeEnhancement) -> have a look, it clearly describes your use-case, and how this is solved by bytecode enhancement.

So this will definitely be the solution in my opinion.

I haven't started discussion on this, and I haven't worked on it yet for 2 reasons:

- We are stuck on Hibernate 4 as Liquibase doesn't support Hibernate 5 yet. This is becoming to be a problem.
- This new approach isn't well-known yet, and I'm always cautious with bytecode optimization, so this will need further testing

I'm closing this as for me this "works as expected". But I understand your issue, and we should have this solution in a few months.

**Comment by cbornet** [comment]
@oderComland I think https://github.com/jhipster/generator-jhipster/pull/3751/commits/395a1515aaacb15daee99a1d241f04e53cac6c61 does what you want. I notice that your example has some protections that we should probably add...
