### ISSUE TITLE
[FEATURE] Setting default values for entity fileds

### ISSUE THREAD

**Issue by oderComland** [jhipster/generator-jhipster#3557]
##### **Motivation for or Use Case** 
It is impossible to set default value for entity field. This is usually a good option to have especially for the required parameters. But of course I would not bound default value to only required fields since this is not necessity but it is more of a "common" logic.

##### **Suggest a Fix** 
There are quite a few options that I have in mind.

1. Use [columnDefinition](http://stackoverflow.com/a/375202) in Column annotation. I am not sure if this solution is independent of database. If it is not then I would not use this solution.
2. Set default value in field setter method by checking if parameter was set to null.
3. Set default value using [PrePersist](http://stackoverflow.com/a/22935451) annotation.
4. Set default value in constructor.
5. Set default value at parameter definition.

The best would definitely be number 1. since this makes database responsible for default values independently of java persistence. I prefer number 2. because the check condition will be only executed if parameter gets changed. I like number 3. because i like annotations and because all default values can be found at one place. :-) I guess number 4. and 5. should not be used but maybe those still deserve some commenting.

What do you think?

**Comment by deepu105** [comment]
This has been asked few times but we wont be doing it as there no much value in generating this. You could easily add it to the generated class file using any of the way you suggested. Sorry

**Comment by poum** [comment]
Hello. Maybe I'am wrong but having default value at any place in the same time looks as generating value for me (in database, java & javascript form)...
