### ISSUE TITLE
Repository query findByUserIsCurrentUser() stops working after updating to JH 3.2.0

### ISSUE THREAD

**Issue by lluiscanals** [jhipster/generator-jhipster#3560]
##### **Overview of the issue**

Repository query for getting all for current user stops working after updating to JH 3.2.0

##### **Motivation for or Use Case** 

Retrieving all entries for current user.

##### **JHipster Version(s)** 
3.2.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.2.0",
    "baseName": "tfrm",
    "packageName": "com.dualion.tfrm",
    "packageFolder": "com/dualion/tfrm",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ca",
      "es"
    ],
    "jhiPrefix": "jhi"
  }
}
```

##### **Suggest a Fix** 
Change this:
```java
@Query("select sourceQex from SourceQex sourceQex where sourceQex.user.login = ?#{principal}")
List<SourceQex> findByUserIsCurrentUser();
```
To:
```java
@Query("select sourceQex from SourceQex sourceQex where sourceQex.user.login = ?#{principal.username}")
List<SourceQex> findByUserIsCurrentUser();
```

This was changed in the last release and it was working fine. I don't know why stops working.

**Comment by jdubois** [comment]
Yes this request changed when using JWT... In fact you have the opposite from the bug that was opened!
Can you have a look at the closed bugs, to link it here? I'm sorry I won't be able to look at this now.

**Comment by ruddell** [comment]
Previous Issue: https://github.com/jhipster/generator-jhipster/issues/3147
Pull Request: https://github.com/jhipster/generator-jhipster/pull/3247
Commit: https://github.com/jhipster/generator-jhipster/commit/fe53a46c3579c5e4d7dbc19dbdad1f554e6dc4e2

**Comment by jdubois** [comment]
OK I can't test right now, but I confirm I understand this issue and that it's highly possible that this is wrong.
I will try to correct this for our next patch release, which should be out soon.
