### ISSUE TITLE
i18n issues native lan is set to zh-cn, but user.csv lang_key value is zh

### ISSUE THREAD

**Issue by qifali** [jhipster/generator-jhipster#3563]
I using : yo jhipster to generate a monolithic app, I set native language of the app to 
Chinese(Simplified) int step 16,
and then add English as additional languages,

When I use mvn spring-boot:run  to start my app and access the home page,
I've got some Error in console:

http://localhost:8080/i18n/angular-locale_zh.js Failed to load resource: the server responded with a status of 404 (Not Found) 
http://localhost:8080/i18n/zh/home.json Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/i18n/zh/global.json Failed to load resource: the server responded with a status of 404 (Not Found)

It looks like app load the wrong locale js file , I think this would be 
http://localhost:8080/i18n/angular-locale_zh_cn.js
http://localhost:8080/i18n/zh-cn/home.json
http://localhost:8080/i18n/zh-cn/global.json

I'm using Jhipster 3.2.0

chrom mac os

I changed src/main/webapp/blocks/config/translation-storage.provider.js file
`$cookies.putObject(name, 'zh');`
to 
`$cookies.putObject(name, 'zh-cn');`
It works fine now

**Comment by andidev** [comment]
Thus should be fixed in master branch. Will be out next release or in a patch release.
