### ISSUE TITLE
Jhipster skipping relationships when generating entity

### ISSUE THREAD

**Issue by eosimosu** [jhipster/generator-jhipster#3565]
##### **Overview of the issue**
I'm not unable to add relationships when generating entities. Check the screenshot below.

![jhipster](https://cloud.githubusercontent.com/assets/10434280/15093900/b87cb8b6-148c-11e6-8825-367b19e4a4fe.png)

##### **JHipster Version(s)** 
3.1.0 and even after upgrading to 3.2.0

##### **Browsers and Operating System** 
ubuntu 15.04

**Comment by cbornet** [comment]
Please paste your yo-rc.json (as asked in the bug template). We need to know what DB you use since relationships are not available with NoSQL DBs.

**Comment by eosimosu** [comment]
{
  "generator-jhipster": {
    "jhipsterVersion": "3.2.0",
    "baseName": "jhipsterhol",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxx",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "sv"
    ]
  }
}

**Comment by pascalgrimaud** [comment]
As @cbornet said, relationships are not available with NoSQL DBs.
