### ISSUE TITLE
Not using unique naming conventions with separators for sub-modules

### ISSUE THREAD

**Issue by tjasaComland** [jhipster/generator-jhipster#3572]
##### **Overview of the issue**

All modules in Angular app are named as `'yourAppName'` which can cause some name collisions. Also unique naming is standard in John Papa style guide.

##### **Motivation for or Use Case** 

John Papa style guild (https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y020)

> Unique names help avoid module name collisions. Separators help define modules and their submodule hierarchy. For example `app` may be your root module while `app.dashboard` and  `app.users` may be modules that are used as dependencies of app.

##### **JHipster Version(s)** 

v.3.2.1

##### **Reproduce the error** 

- Generate app with JHipster
- All modules in ...state.js are named the same `.module('yourAppName')`

**Comment by deepu105** [comment]
Yes we try to follow John papa style guide as much as possible. But we dont implement every rule and this is one such exclusion. Its bit hard to manage unique names for every module within the app and hence we dont do it currently. It might be done for next major release when we switch to angular2
