### ISSUE TITLE
Couchbase NoSQL database

### ISSUE THREAD

**Issue by billy93** [jhipster/generator-jhipster#3573]
I have already using jhipster 3.0 with mongodb nosql database, and i think it would be nice if the generator adding support for Couchbase database.

**Comment by jdubois** [comment]
I've heard some people at Couchbase were interested in doing it, they are of course most welcome.
At the moment we already have a lot of work supporting the current databases, and we do a lot of work on Cassandra, which is close to Couchbase, so for me:

- I doubt we can have this in the main generator, as this is clearly a lot of work for us, for a database which isn't widely used
- A JHipster Module would be perfect, if someone is interested in doing it
