### ISSUE TITLE
[Internal] externalize the prompts into a file

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3577]
Currently our promts for server and entity are so long and complex, it would be very easy to maintain if they are moved to its own files within the respective generators.

I propose to move the prompts into a `prompts.js` file along side the `index.js` of each generator and then just import it int the `prompting` section of `index.js`

@jhipster/developers what do you think? if you guys have no concerns, then ill do it when i have free time

**Comment by pascalgrimaud** [comment]
Good for me

**Comment by wmarques** [comment]
+1 for me too :+1:
