### ISSUE TITLE
"Username" In application-prod.yml file missing

### ISSUE THREAD

**Issue by kamfasage** [jhipster/generator-jhipster#3578]
##### **Overview of the issue**

The " Username" is missing into the generated file "application-prod.yml" for oracle database..

##### **JHipster Version(s)** 

jhipsterVersion": "3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "ids_v2",
    "packageName": "com.XXX.XXX",
    "packageFolder": "com/XXX/XXX",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "4a0224df7e1a488976814d742791d388aecfb9e2",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de",
      "it",
      "ro",
      "ru"
    ]
  }
}

[Uploading datasource.txt…]()

**Comment by jdubois** [comment]
What is this "username" that is missing? We don't store this in the Yeoman configuration

**Comment by kamfasage** [comment]
I have just updated my project .. but still the fix doesn't work

**Comment by kamfasage** [comment]
the prod database isn't mysql but Oracle.. look out your fix

**Comment by pascalgrimaud** [comment]
@kamfasage : just freshly generate a project, and it is fixed in **master branch** (not released yet).
Here an extract of my `application-prod.yml`, you have to complete with your own information (and be carefull with indentation):
```
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:jhipster
        name:
        username: 
        password:
```

**Comment by kamfasage** [comment]
Ok i thought it was release...Thanks
