### ISSUE TITLE
Invalid message for used email in user settings

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [jhipster/generator-jhipster#3581]
##### **Overview of the issue**
When user tries to change his email to already used one, he gets wrong message
> An error has occurred! Settings could not be saved.

instead of
> <strong>E-mail is already in use!</strong> Please choose another one.

At clean/web/rest/AccountResource.java#saveAccount:150 there is a failure message with `user-management` instead of `userManagement` and then non-existing vm.errorEmailExist value in app/account/settings/settings.html:10:
```
<div class="alert alert-danger" ng-show="vm.errorEmailExists" translate="settings.messages.error.emailexists">
    <strong>E-mail is already in use!</strong> Please choose another one.
</div>
```

I know it is a minor issue in very minor use case.
I would fix it and PR, but I'm in a big time pressure now, so I just wanted to let you know.

##### **Motivation for or Use Case** 
Proper feedback for user; clean code.

##### **JHipster Version(s)** 
`3.1.0`

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "jhipster",
    "packageName": "clean",
    "packageFolder": "clean",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "3bf9311c41987199f59172d808ad8e8e6d36aa42",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "cs"
    ]
  }
}
```
##### **Browsers and Operating System** 
Win 7; Opera

##### **Reproduce the error** 
run app, login, go to user settings, change email to an existing one

##### **Suggest a Fix** 
(see description)

**Comment by deepu105** [comment]
@WhyINeedToFillUsername could you verify with current master?

**Comment by WhyINeedToFillUsername** [comment]
I've updated to 3.3.0, but user is still getting
`An error has occurred! Settings could not be saved.`

In console:
```
2016-05-17 13:14:30.467 ERROR 16860 --- [nio-8080-exec-1] clean.web.rest.util.HeaderUtil           : Entity creation failed, Email already in use
2016-05-17 13:14:30.468 DEBUG 16860 --- [nio-8080-exec-1] clean.aop.logging.LoggingAspect          : Exit: clean.web.rest.AccountResource.saveAccount() with result = <400 Bad Request,{X-jhipsterApp-error=[error.emailexists], X-jhipsterApp-params=[user-management]}>
```

**Comment by deepu105** [comment]
Its not releases yet, you need to check with master by forking the
generator and then doing an npm link. else you can check only after next
release

Thanks & Regards,
Deepu

**Comment by WhyINeedToFillUsername** [comment]
Oh sry, didn't get it. And I apologize, but currently I don't have time to check it (finishing a bachelor thesis based on jhipster :)).

**Comment by deepu105** [comment]
Its ok no probs
