### ISSUE TITLE
Entity detail view is not adjusting for long labels - even on big screen

### ISSUE THREAD

**Issue by dalyc** [jhipster/generator-jhipster#3584]
##### **Overview of the issue**

When I generate an entity with a long label e.g "Settlement Account Number", the label is cut off in the browser. I assume it's because of the move from tr/td (in older versions) to dl/dt

Anyone got a good workaround?
I guess I could use css to make dt wide enough for the longest label but it will look a bit ugly on those that all short. Just so you know - I'm a server side guy and not an expert on the front end (which is why I love jhipster so much - it shows me the way)

##### **JHipster Version(s)** 

3.1.0
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

    {
        "generator-jhipster": {
        "jhipsterVersion": "3.1.0",
        "baseName": "xxx",
        "packageName": "xxx",
        "packageFolder": "xxx",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "hibernateCache": "no",
        "clusteredHttpSession": "no",
        "websocket": "no",
        "databaseType": "sql",
        "devDatabaseType": "postgresql",
        "prodDatabaseType": "postgresql",
        "searchEngine": "no",
        "buildTool": "maven",
        "enableSocialSignIn": false,
        "useSass": false,
        "applicationType": "monolith",
        "testFrameworks": [
          "gatling",
          "cucumber",
          "protractor"
        ],
        "jhiPrefix": "ob",
        "enableTranslation": false
    }    
`                                                                                                                                                           

##### **Browsers and Operating System** 

Gentoo - Chrome

Go back to tables :)

**Comment by ruddell** [comment]
DL/DT have a better UX on mobile than the table (see screenshots), so I think we should keep it the way it is.  The original change and discussion occurred https://github.com/jhipster/generator-jhipster/pull/2824.

<img width="45%" alt="old" src="https://cloud.githubusercontent.com/assets/4294623/17127574/91e315e8-52bb-11e6-9239-a5239fa69de3.png">
<img width="45%" alt="new" src="https://cloud.githubusercontent.com/assets/4294623/17127572/91e1b680-52bb-11e6-8a00-ec36572aad0b.png">


If you need the whole label to show up you can change the DL's css width, I'm not sure of a better way to handle long entity names.

**Comment by deepu105** [comment]
@ruddell is right. bootstrap is mobile first and hence dl/dd has a better UX than table, you would have different issues with table as well with long labels. I think the best solution would be to add some css to break the words into new lines when label is long.

**Comment by jdubois** [comment]
No clean solution here: I understand (and agree) that dl/dd is better than a table, and then our goal is to use "standard" Bootstrap code, without adding too many hacks and tricks.
I guess you indeed need to modify the CSS for long labels, so they display correctly.
