### ISSUE TITLE
Application could not connect to Cassandra node-x running on non-linux Docker

### ISSUE THREAD

**Issue by raphaelbrugier** [jhipster/generator-jhipster#3588]
##### **Overview of the issue**
When the Cassandra cluster is launched within Docker with multiple nodes, the application could not reach the extra nodes when running on non-linux OS.
This is because Docker is running inside a vagrant VM and those the driver could not access directly to the cluster nodes after reaching the contact point.

Error message:
```
2016-05-12 16:47:54.238 DEBUG 6660 --- [uster1-worker-0] com.datastax.driver.core.Host.STATES     : [/172.18.0.3:9042] starting reconnection attempt
2016-05-12 16:47:54.240  WARN 6660 --- [r1-nio-worker-2] com.datastax.driver.core.Session         : Error creating pool to /172.18.0.3:9042
  com.datastax.driver.core.exceptions.ConnectionException: [/172.18.0.3] Pool was closed during initialization
at com.datastax.driver.core.HostConnectionPool$2.onSuccess(HostConnectionPool.java:149)
```

We started discussing this with @jdubois on this [comment](https://github.com/jhipster/generator-jhipster/pull/3570#issuecomment-218781078).

##### **Browsers and Operating System** 

All but linux

##### **Suggest a Fix** 
The current fix is to add a new route to your iptable pointing to the Vragrant ip as explains in [this post](http://krasserm.github.io/2015/07/13/chaos-testing-with-docker-and-cassandra/#port-mapping):
`sudo route -n add 172.18.0.0/16docker-machine ip default`

This is documented in JHipster [docker-compose page](https://github.com/jhipster/jhipster.github.io/blob/master/pages/docker_compose.md#note-for-non-linux-users) but a bit hidden.

@jdubois proposal:
> My main problem is that everything is done with JHipster so that it works "out of the box" -> isn't there a solution for this? Like forbidding to connect to that node? To be honest I haven't understood why you need it, yet. If there is no other solution, you could also catch the exception and print a specific log message, pointing to the documentation

Possible options:
- prevent the driver to ping the other nodes (I don't know if it's possible and a bit against C* philosophy anyway)
- catch the exception and display a better message pointing to the documentation
- do nothing and hope every non-linux users migrate to [native docker for mac](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/) :)

I think I'll implement something by catching the exception unless someone as a better idea on how to handle this. cc @cbornet @pascalgrimaud

**Comment by jdubois** [comment]
@raphaelbrugier I'm using Docker for Mac and I have the same problem! This is because that box is inside the Docker network, and I'm not sure its port should be exposed

**Comment by raphaelbrugier** [comment]
Ah that's interesting. I though it would work that way.
I haven't received my invitation for Docker for Mac so I can't test it.

**Comment by pascalgrimaud** [comment]
I manage to reproduce the issue with **docker-machine**, on my Linux laptop
I have a problem with mounting volume, so the migration didn't work (but it's my config).
After executing manually all cql scripts, here the complete log when I start the application:
```log
2016-05-13 08:10:44.493 ERROR 4187 --- [r1-nio-worker-1] com.datastax.driver.core.Session         : Error creating pool to /172.18.0.4:9042

com.datastax.driver.core.TransportException: [/172.18.0.4:9042] Cannot connect
	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:156)
	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:139)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:268)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:284)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.NoRouteToHostException: Aucun chemin d'accès pour atteindre l'hôte cible: /172.18.0.4:9042
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
	... 6 common frames omitted
```

**Comment by jdubois** [comment]
@pascalgrimaud yes that's the same issue: as that node is in the internal Docker network you can't access it.
My opinion is that:

- If you are in dev, your app is outside Docker and connecting to a Cassandra ring inside Docker -> either you expose ports for all the nodes (which looks strange and complicated), or you only expose one node and force the driver to only use that node. I don't know the new config for that, but that was possible before (and should still be).
- If you are in prod, you have a docker-compose file where your app is in a Docker container next to the Cassandra ring -> in that case it should be able to see each node with its internal IP, and everything will work as expected

**Comment by pascalgrimaud** [comment]
Agree with you @jdubois 

For development, I still think just start cassandra is enought, no need to add a node.
If we go this way, we should remove [these lines](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/docker/_cassandra.yml#L14-L19) in cassandra.yml => I reopen again the discussion with you, @raphaelbrugier  about this

For testing production in development, by using `java -jar target/*.war` or `mvn`, our current [cassandra-cluster.yml](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/docker/_cassandra-cluster.yml) works only for Linux. Different solution to build a cassandra cluster:
- manually install, without docker
- with our current Docker Compose, but we need to add a new route to iptable
- use different docker-machine (different VMs) => so we can access to all nodes

By containerize the application, it should be OK, like you said

**Comment by raphaelbrugier** [comment]
Ok, makes sense for the internal docker ip. But I'm not totally getting why it's seems to work by adding a new route to the iptable then. Maybe it doesn't and I need to run some more tests.

@pascalgrimaud, yes in that case it will make it more easier to have only one node when using `cassandra.yml`. I'll remove that lines.

I'm not getting why you say the current `cassandra-cluster.yml` works only for Linux by using `java -jar` or `mvn`? Except this error to reach the node, it's working isn't it?

I agree with the solutions you proposed for manual and current docker-compose, but I don't see how using docker-machine would work.

If I sum up, I think we could have less options to start a Cassandra cluster with docker:
- For development only: `cassandra.yml` starts a one cluster, executes the migration scripts. You can run the app outside of docker. You can rerun the migration container.
- For "production in development" : `app.yml`: starts a n+1 Cassandra node, executes the migration scripts, start the app.
 - The easiest way to test the app with a multi-node cluster is to have it running in Docker
 - uses `cassandra-cluster.yml` or even remove it completely

If the user does not run Cassandra in Docker, we can assume he installed it and all he has to do to have the application connected to the cluster is to configure the `SPRING_DATA_CASSANDRA_CONTACTPOINTS`

We can discuss to keep or not the opscenter alternative, I think @jdubois wanted to get rid of it?

**Comment by jdubois** [comment]
@raphaelbrugier I agree with everything you wrote! For OpsCenter, DataStax is going to remove it soon, so there's no need for us to keep working on it.

**Comment by pascalgrimaud** [comment]
Yes, I wrote too fast. The `cassandra-cluster.yml` works, except for this error, when reaching the node
For the rest, agree with you @raphaelbrugier !

**Comment by raphaelbrugier** [comment]
I think this issue is not relevant anymore after #3593 and we can close it now? @pascalgrimaud ?

**Comment by pascalgrimaud** [comment]
Yes I think we can close
Le 24 mai 2016 4:51 PM, "Raphaël Brugier" <notifications@github.com> a
écrit :
