### ISSUE TITLE
Updater for jhipster applications

### ISSUE THREAD

**Issue by lordlothar99** [jhipster/generator-jhipster#3594]
##### **Overview of the issue**

Propose a standard updater when new Jhipster versions are available

##### **Motivation for or Use Case** 

Each time a new Jhipster version is published, developpers have to regenerate the whole application from scratch, and then re-apply their changes ; they can forgot some changes, and have to check every file in a manual way

##### **Suggest a Fix** 

I wrote a tiny shell script which avoided me to lose a lot of time ; it's based on Git :
* it switches to a "update_jhipster" branch, which won't ever contain anything but the purely generated code
* it generates the application on this branch
* then upgrades jhipster version
* regenerates the app
* switch back to default branch (which holds modified files due to developments)
* starts the merge with update_jhipster branch

The fact is, every time there is a new jhipster version, merge is easy cause git knows that only some changes are about to be applied

**Comment by jdubois** [comment]
Very, very interesting idea!!!

**Comment by lordlothar99** [comment]
I'm creating a PR..

**Comment by jdubois** [comment]
Don't forget to test if Git is present... I have customers using CVS :-)

**Comment by notflorian** [comment]
Awesome thanks, that's what i'm currently doing manually each time I upgrade my JHispter application. Big kuddos! :+1:

**Comment by cbornet** [comment]
Nice !

**Comment by lordlothar99** [comment]
tested on my computer, let's see what travis thinks

**Comment by deepu105** [comment]
Thats indeed a nice idea :)

**Comment by cadocruz** [comment]
Awesome. Thanks

**Comment by alfredorueda** [comment]
Super useful feature!

**Comment by alireza-hanifi** [comment]
it was my idea to doing these steps manually, But I never told to anyone . :D :-)
Thanks.
