### ISSUE TITLE
Update entity using JDL

### ISSUE THREAD

**Issue by Meriem19** [jhipster/generator-jhipster#3597]
##### **Overview of the issue**

I want to add a relationship to an entity but i'm using JDL so I think i can't add the entity.json and update using the sub generator, i've add it in .json and in the class and run but nothing happens

##### **Motivation for or Use Case** 

I need this relationship so I can proceed.

##### **JHipster Version(s)** 

v 3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
`{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "Banque",
    "packageName": "org.isi",
    "packageFolder": "org/isi",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "b57de896ec080b40fc8d78e542ceb15481efc289",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}`
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

There's no error while runing , just that the entity is not modified.
`{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "compteBancaire",
      "otherEntityName": "compteBancaire",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 2,
      "relationshipName": "typeCredit",
      "otherEntityName": "typeCredit",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 3,
      "relationshipName": "justificatif",
      "otherEntityName": "justificatif",
      "relationshipType": "one-to-many",
      "otherEntityRelationshipName": "demande"
    },
      {
          "relationshipId": 4,
          "relationshipName": "compteApplicatif",
          "otherEntityName": "compteApplicatif",
          "relationshipType": "one-to-one",
          "otherEntityRelationshipName": "demande"
      }
  ],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "dateEmission",
      "fieldType": "ZonedDateTime"
    },
    {
      "fieldId": 2,
      "fieldName": "numero",
      "fieldType": "Long"
    },
    {
      "fieldId": 3,
      "fieldName": "etat",
      "fieldType": "String"
    },
    {
      "fieldId": 4,
      "fieldName": "montant",
      "fieldType": "Long",
      "fieldValidateRules": [
        "required"
      ]
    }
  ],
  "changelogDate": "20160510173614",
  "dto": "no",
  "pagination": "pager",
  "service": "serviceImpl"
}
`

##### **Browsers and Operating System** 

Chrome

**Comment by deepu105** [comment]
I really dont understand what your doing or what your issue is. If you want to update an entity just update the jdl and regenerate entities using import-jdl sub generator or jhipster uml. You can also run the entity sub generator on the entity to add new relationship. Of course it will overwrite your existing code, but you should use git and make a new branch for the update and then merge your changes.

If your facing any issues while doing any of the above then open an issue and give us clear details of what you do and what happened
