### ISSUE TITLE
Use MySQL5InnoDBDialect

### ISSUE THREAD

**Issue by getintouchapp** [jhipster/generator-jhipster#3598]
##### **Overview of the issue**
Feature request: Jhipster should have or support MySQL5InnoDBDialect instead of it's default MySQLInnoDBDialect which is for MySQL 4

##### **Motivation for or Use Case** 
The generated applications throws errors due to this error : http://stackoverflow.com/questions/5231325/mysql-5-5-9-and-hibernate-table-creation-error-on-type

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

application-dev.yml file should have MySQL5InnoDBDialect instead of MySQLInnoDBDialect

**Comment by jdubois** [comment]
OK for updating, of course, but a couple of comments:

- I've never had this issue
- If you are ready to do a little testing first, could you do a PR to solve this?

**Comment by ddamw** [comment]
IIRC this is only an issue when you're not using Liquibase to create the database for you, but rely on Hibernate's hbm2ddl function instead. 

The MySQL 4 dialect uses a deprecated syntax for creating tables, which used to be the standard (see the comments at https://dev.mysql.com/doc/refman/5.5/en/using-innodb-tables.html)

**Comment by jdubois** [comment]
OK, then @getintouchapp it would have been nice to explain you're not using Liquibase!!!!
