### ISSUE TITLE
Data upload using Reading Excel Sheet for Entity.

### ISSUE THREAD

**Issue by mehul1991** [jhipster/generator-jhipster#3611]
##### **Overview of the issue**

My requirement is to insert bulk entry for entity. So I thought of uploading the excel sheet and read values from that which is a lot easier than inserting bulk records manually. 
##### **Motivation for or Use Case** 

I am creating an intranet portal using jhipster for an organization which requires bulk entries for entities which is a lot manual work, to simplify that i used excel upload feature.

##### **JHipster Version(s)** 

 "jhipsterVersion": "3.1.0",

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "jhipsterExcelUploadExample",
    "packageName": "com.zenfact.app",
    "packageFolder": "com/zenfact/app",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "7bb7ca41e752815ff1f86f2b29d46d845e869295",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

{
    "jhipsterExcelUploadExampleApp": {
        "country" : {
            "home": {
                "title": "Countries",
                "createLabel": "Create a new Country",
                "createOrEditLabel": "Create or edit a Country",
                "search": "Search for Country",
                "upload": "Upload"
            },
            "created": "Country is created {{ param }}",
            "updated": "A Country is updated with identifier {{ param }}",
            "deleted": "A Country is deleted with identifier {{ param }}",
            "delete": {
                "question": "Are you sure you want to delete Country {{ id }}?"
            },
            "detail": {
                "title": "Country"
            },
            "countryName": "Country Name",
            "country_code": "Country Code",
            "fileName": "File Name"
        }
    }
}

##### **Reproduce the error** 

This is an enhancement.

[changes_inFiles_that_I_Did.zip](https://github.com/jhipster/generator-jhipster/files/270146/changes_inFiles_that_I_Did.zip)

**Comment by cbornet** [comment]
see #2659. I didn't have time to work on a module...

**Comment by deepu105** [comment]
you are welcome to do PR if you can do it as a import feature on the entity listing page

**Comment by jdubois** [comment]
This would be in a module -> this is a very specific requirement, we can't have everything in the main generator or it will become overweight.
