### ISSUE TITLE
Keep receiving NUMBEROF_RETRIES_NEXTSERVER_EXCEEDED

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#3615]
##### **Overview of the issue**

After some issues my gateway is working fine on Docker Cloud but now my app just don't come up. Apparently everything is fine but every request gets this: `NUMBEROF_RETRIES_NEXTSERVER_EXCEEDED`

any ideas?

my .yo-rc.json
```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "app1",
    "packageName": "br.com.example.app1",
    "packageFolder": "br/com/example/app1",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "blablabla",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "pt-br"
    ],
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false,
    "jhiPrefix": "jhi"
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}
```

**Comment by marcelinobadin** [comment]
update: if I run everything on a single (huge) container, it works fine.

**Comment by jdubois** [comment]
It's a Ribbon error, so I guess the IP that are sent by Eureka are not the good ones -> can you check in the Registry, what IP are registered? You could also see them in the "gateway" admin screen on your gateway.
Your gateway should be able to reach those IPs.

**Comment by marcelinobadin** [comment]
Found! I added the following configuration to the configuration of each gateway and app (the configurations stored in the git repository used by jhipster-repository):

```yaml
eureka:
    instance:
        prefer-ip-address: false
        hostname: ${env.app.hostname}
        nonSecurePort: ${env.app.port}
```

Now it is working!

**Comment by jdubois** [comment]
Great! That's not very surprising, but this is something that depends on each cloud -> we need to do a documentation page for Docker Cloud and explain this, would you be available to help?

**Comment by marcelinobadin** [comment]
Yes, sure. What you suggest, use the wiki?

**Comment by jdubois** [comment]
No, the website - the source is here: https://github.com/jhipster/jhipster.github.io

We could have a specific page for Docker Cloud, like we already have for CloudFoundry, Heroku and AWS. Could you write this in Markdown? Have a look at the .md files, not the HTML files (markdown is much easier).

I'll do the menu, etc: what I mostly want to have is your text, and I'll do the formatting.

**Comment by marcelinobadin** [comment]
ok, perfect. I'll do in a markdown file. The approach will be more "going to production" than only Docker Cloud but of course I will put my docker cloud insights.

I hope by the end of next week I have that and we can talk. Close this issue and I will put the file on the website repo.

Thanks.

**Comment by PierreBesson** [comment]
Personaly I think we should do a **Deploying to Docker** page listing some of the options (docker swarm, docker cloud, amazon, google, etc...). Also, separate it in a monolith and microservice section.

The important thing would be to explain the workflows (involving the docker registry) and some basic knowledge about docker orchestration.
I would be able to write some docs on how to create a swarm with docker machine (virtualbox or cloud-driver) and manage your deployment.

**Comment by marcelinobadin** [comment]
I realize that Docker Cloud is not enough for my requirements. I will try to write something but definitely I am going to Kubernetes.

**Comment by jdubois** [comment]
We should (hopefully) have a Kubernetes page soon, so we'll have to add it there. Then, I've already seen it working with Kubernetes, so I guess this configuration is already correct there.

I'm closing this as this has been opened for quite some time - @marcelinobadin if you find time to add a documentation page, that's most welcome, otherwise I'll test this again when we have Kubernetes support.

**Comment by danielpetisme** [comment]
I can't find any mention of this issue in the doc, could you give me the link please ?

I have a JHipster microservices deployed on Docker Swarm (orchestrated by Rancher). When a service tries to invoke another service hosted on another machine I face the `NUMBEROF_RETRIES_NEXTSERVER_EXCEEDED` issue but if they are hosted on the same machine the request succeed.
I initially thought it was a network issue between containers but they are able to request the DB or RabbitMQ hosted on other machines so... 

I searched for an explanation but the doc about this exception is quite limited.

**Comment by PierreBesson** [comment]
Hi @danielpetisme, some fiddling with Eureka config might work for you. Please refer to the official Spring Cloud and Netflix Eureka docs as this is quite complicated :disappointed:. Also be reminded that this issue concern Docker Cloud which is a service that actually **isn't** based on Docker Swarm at all.
