### ISSUE TITLE
Production build excludes images from bower components

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3617]
##### **Overview of the issue**

Images distributed as part of a bower component like leaflet are not included in the production war.
This was working in 2.x when `bower_components` folder was always included before change #2945 was made.

In the case of leaflet, these images are well declared in their [bower.json](https://github.com/Leaflet/Leaflet/blob/v0.7.7/bower.json) and so could be imported automatically similarly to fonts or css.

##### **JHipster Version(s)** 

JHipster 3.3.0
It's a regression from JHipster 2.x

##### **Reproduce the error** 

Generate a simple monolith app add leaflet to bower components.
Run a production build: `mvn -Pprod package`

Look at the content of the war file, it does not include the images that are in `bower_components/leaflet/dist` are not included.

Here is a repo that reproduces the problem:

https://github.com/gmarziou/bower-images-excluded

##### **Suggest a Fix** 

There could be 2 approaches:

1. minifying and versioning images from `bower_components`, replacing refs to original images in all html, js and css
2. Include only the main parts of bower_components

For leaflet, I could not get the first approach to work because there are no simple reference to image names in  js or css files. Second approach works because there is a leaflet variable to specify the folder where to find images.

@erikkemperman do you have a suggestion?

**Comment by deepu105** [comment]
May be we could define a copy task using the bowerMain files and then
filtering only images from it and copy them to the images folder?

Thanks & Regards,
Deepu

**Comment by gmarziou** [comment]
Yes it could work but I'm afraid of discovering later than we also need other files than images. I'll give it a try.

**Comment by erikkemperman** [comment]
I also think bower-main-files is probably the best way to go... If there are important files missing from the main section for some component's bower.json we can use override in our own bower.json.

**Comment by gmarziou** [comment]
Using main-bower-files works.

I just had to copy to `target/www/bower_components` because otherwise I would have needed to setup the folder variable to different paths indev and prod: `L.Icon.Default.imagePath = '../bower_components/leaflet/dist/images/';`

~~~js
// copy images from bower dependencies
gulp.task('main-bower-images', function() {
    return gulp.src(bowerFiles({filter: ['**/*.gif', '**/*.jpg', '**/*.png']}), { base: config.bower })
        .pipe(gulp.dest(config.dist +  'bower_components'));
});
~~~

**Comment by erikkemperman** [comment]
Cool! I'm not sure how Leaflet links these images in html or css; would it be possible to pass these images through gulp-rev? That might be good because in prod profile the static assets are served with very long cache expiration...

**Comment by gmarziou** [comment]
Unfortunately I could nto fins how the icons paths were built in lefalet, I suspect it's done in JS maybe by concvatenating some strings which would defeat gulp-rev-replace.

**Comment by erikkemperman** [comment]
Sorry I was mistaken -- I just checked, and the long cache headers are only served for assets in `app` and `contents`.

So your images in `bower_components` should not suffer from that... Although *no* cache headers might also not be ideal for such images.

**Comment by jdubois** [comment]
The main-bower-images solution looks like the easiest solution for me. And I'm not good at enough with the gulp build to find a better way...

**Comment by gmarziou** [comment]
I also found that angularjs-slider CSS does not work when minified by nanocss, I tried using `safe: true` option as this is going to be the default mode for next version but it did not help. As I was in a rush, I disabled nanocss and kept *.css files in `bower_components` folder as they usually reference images through relative path and it worked. Overall, I kept bower_components structure for images and css and got rid of vendor.css, it seems that only js are fully safe for minification.

**Comment by deepu105** [comment]
Let me see what I can do

Thanks & Regards,
Deepu

**Comment by erikkemperman** [comment]
Just curious, do you think the problem was with the contents of the minified css or its location (since you're putting images in bower_components)?

**Comment by gmarziou** [comment]
The angularjs-slider CSS does not use any image, so I would say it's related to the minification process only.

**Comment by erikkemperman** [comment]
Sorry, I misunderstood your remark about relatively referenced images I guess.

**Comment by gmarziou** [comment]
No, you understood it clearly, it's just that there were 2 issues. CSS referencing relative images was with leaflet-search.

**Comment by deepu105** [comment]
@gmarziou do you think this is related to #3906 ?

**Comment by gmarziou** [comment]
It could be, I'll run some test on my test project.

**Comment by deepu105** [comment]
@gmarziou can you check this with latest master plz

**Comment by ruddell** [comment]
@deepu105 I tested with [jhipster-leaflet](http://jhipster.github.io/modules/marketplace/#/details/generator-jhipster-leaflet) and it works in Dev, but the images are still missing in Prod (in this case the Search icon found in bower_components relative to the CSS file).

**Comment by jdubois** [comment]
@deepu105 there is still the issue with the current master :-(
Yes the easiest solution is to copy those files, but then the HTTP cache wouldn't be working, a better solution would be to add a md5, like we do all the time.
We're not doing anything specific to JHipster here, so normally the Gulp task should do it (I haven't looked at it, but indeed with JHipster 2.x and Grunt that was working).

**Comment by deepu105** [comment]
@jdubois it was working with 2.x coz we used to bundle `bower_components` in prod as well. I think we can just copy images from bower main like we do for fonts, shouldn't be a big deal. I can do it later. It should work for any images as part of bower but I think the path issue with leaflet needs to be opened as an issue in their repo as they are not playing nice by setting a hardcoded path to bower components. IMO we shouldnt do any workaround for leaflet

**Comment by jdubois** [comment]
Indeed @deepu105 it's an issue with Leaflet and their hardcoded path, so not our fault.
Let's copy the images like you say, and close this!

**Comment by gmarziou** [comment]
@ruddell about the issue with the leaflet Search icon, did you add this line?

~~~js
L.Icon.Default.imagePath = '../bower_components/leaflet/dist/images/';
~~~

@jdubois as you can see, Leaflet does not use hard coded path, so there's no issue on their side

**Comment by jdubois** [comment]
OK @gmarziou ! Then what do we do, just copy the image dir? That's not perfect, but it was working in 2.x.
Then again, we are probably not the only ones doing this, so it's probably us not using the Gulp plugins the right way.

**Comment by gmarziou** [comment]
Yes just copy the image dir, that's what I did in my project.

**Comment by deepu105** [comment]
Ok I was under the impression that leaflet somewhere had the bower path
specified fromdiscussions above. Maybe I misread. If copying images will
work then thats perfectly fine. Ill add this when I find time. If anyone
wants to do it sooner please proceed :)


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
im doing it

**Comment by deepu105** [comment]
@gmarziou can you please see if this is working for your use case?

**Comment by ruddell** [comment]
@deepu105 the fix partially works.  I tested with the jhipster-leaflet module, it copied images from `src/main/webapp/bower_components/leaflet` but not from `src/main/webapp/bower_components/leaflet-search` (where the search-icon is stored).  Both are included in bower.json as dependencies.  After looking into it, leaflet-search does not include the images as part of the main section in [bower.json](https://github.com/stefanocudini/leaflet-search/blob/master/bower.json).  

From the[ bower.json spec](https://github.com/bower/spec/blob/master/json.md), images should not be included as part of the bower main section.  Leaflet [removed the images](https://github.com/Leaflet/Leaflet/commit/b544d5e50349edf5bd9fb0bd7766cef0254de8f3) from their bower.json to follow the spec, so this won't work for them in future versions.  Due to this, I don't think main-bower-files is the way to solve this.

**Comment by deepu105** [comment]
The only other option is to copy all the images from bower_components but
that could be a lot of unwanted images as well

Thanks & regards,
Deepu

**Comment by gmarziou** [comment]
Thanks for the explaination @ruddel, bootstrap has also changed their [bower.json file](https://github.com/twbs/bootstrap/pull/16359) to remove glyphicons fonts.

As you said, bower main will not solve the issue, it means that installing images or fonts required by a bower package should be a manual process.

**Comment by jdubois** [comment]
At some point, yes I understand this is going to be a manual process.

Having a specific folder that will be copied in production could also be interesting for another reason: you never know what people want to have in their app, and maybe they don't want their JS/CSS/image/whatever being handled by the minification process.

From my understanding, we will remove Bower with AngularJS 2, so I don't think we should spend too much time on this -> is this something we could document instead?

**Comment by deepu105** [comment]
Ya documentation might be sufficient with some instructions about manual
steps to do

Thanks & regards,
Deepu
