### ISSUE TITLE
Add a Zuul filter to cache HTTP requests with Memcached

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3621]
This is a follow-up to #3308

Before this ticket is done, we need to:

- Refactor the current Zuul filters (which are not totally consistent)
- Add a specific documentation section for Zuul filters (the rate limiting filter is not even documented)

This filter would allow to cache HTTP requests at the Zuul level:

- It would cache REST requests to microservices: GET/PUT/POST/DELETE requests will update the cache.
- That cache would use Memcached, so it could be hosted easily in the cloud
- There would be a `memcached.yml` Docker configuration, using the official Memcached image
- It would use the [Folsom client](https://github.com/spotify/folsom)
- When HTTP caching is enabled on the gateway, you have the option to generate a cache configuration per entity -> they would be generated when the entity is generated. That means some specific Java code generated on the gateway, which isn't the case today. This is necessary as you want fine-grained control over the cache.
- Some study must be done to see how Memcached failures should be handled. There should be some kind of circuit breaker for Memcached, so that if it fails we quickly stop using it.

**Comment by PierreBesson** [comment]
Shouldn't we try to write a memcached adapter for [Spring Cache Abstraction](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html#cache-plug) ?
This way, the system we put in place can be used with any cache.

**Comment by jdubois** [comment]
The problem is that it doesn't fit very well with the Spring Cache Abstraction. And that should be done in Spring, that shouldn't be generated anyway. Note that if you want to do it, this could be a contribution to Spring, that would be cool!

**Comment by gmarziou** [comment]
What are the benefits of using memcached over ehcache or hazelcast for this Zuul filter?

**Comment by PierreBesson** [comment]
@gmarziou I would argue that memcached seems like a good choice as it can scale independently from the gateway. Also it is very easy to provide a memcached server in dev using docker.

But most of all, every cloud Platform (AWS, GCP, Azure) offers some kind of cache API that uses the memcached protocol.

But anyway, if you would like it to support another cache, I would personally be in favor of adding a cache filter for hazelcast.

**Comment by gmarziou** [comment]
I'm working on a Zuul filter that uses ehcache. 

I have found very interesting the way Convergent-UI project uses Zuul Filter and Spring cache abstraction: they have defined a [ContentService](https://github.com/acesinc/convergent-ui/blob/master/src/main/java/net/acesinc/convergentui/content/ContentService.java) that uses a CacheManager and @Cacheable annotations on methods that fetch content from downstream microservices. This service is then injected into Zuul filters:  [https://github.com/acesinc/convergent-ui/blob/master/src/main/java/net/acesinc/convergentui/ConvergentUIRequestFilter.java](https://github.com/acesinc/convergent-ui/blob/master/src/main/java/net/acesinc/convergentui/ConvergentUIRequestFilter.java) and  [ConvergentUIResponseFilter](ConvergentUIResponseFilter)

**Comment by deepu105** [comment]
+1

Thanks & regards,
Deepu

**Comment by gmarziou** [comment]
I got Spring Cache Abstraction working with Zuul with RestTemplate and also with HttpClient.

As Netflix libs are rather poorly documented, I had to read a lot of their code which is also not very commented and I found that Ribbon/Hystrix already support client caching (see [HttpRequestTemplate](https://github.com/Netflix/ribbon/blob/master/ribbon/src/main/java/com/netflix/ribbon/http/HttpRequestTemplate.java) and [HttpRequest](https://github.com/Netflix/ribbon/blob/master/ribbon/src/main/java/com/netflix/ribbon/http/HttpRequest.java)). They do it by using CacheProvider interface which has 2 implementations: InMemoryCacheProvider that uses ConcurrentHashMap and EVCacheProvier that uses [EVCache](http://techblog.netflix.com/2013/02/announcing-evcache-distributed-in.html) on top of memcached and spymemcached.

#### EVCache

EVCache is a memcached & spymemcached based caching solution

**Comment by gmarziou** [comment]
I gave up on the CacheProvider idea, I don't understand how it works.

I re-worked my initial approach and now I have a much simpler solution that collaborates with other filters. It uses 2 filters:

- CachingPreFilter: reads cache and fill response if URI found in cache
- CachingPostFilter: stores response into cache using URI as key

Cache name uses service id.

I haven't tested various combinations around gzip compression:

- cached response is gzipped but next request does not require gzip
- cached response is not gzipped but next request requires gzip

You can have a look: https://github.com/gmarziou/gateway-ribbon-cache/tree/master/src/main/java/com/mycompany/myapp/gateway/caching

**Comment by jdubois** [comment]
Your solution is good & simple @gmarziou but unfortunately it's going to be much more complex than that:

- we need to have more than URI for cache keys: the key might depend on HTTP headers, for example
- we need some configuration, so not all URLs are cached
- we need some cache invalidation feature

All this makes me realize it's a really complex task, and I just don't have the time to do this.

So I'm closing this because of lack of time to do a good solution. If someone wants to do it, or sponsor the feature, then he's most welcome.

**Comment by deepu105** [comment]
I tried and left it as well coz it was way complex than I thought it would
be. May be we could give it a shot later. We can add willdolater label

Thanks & regards,
Deepu

**Comment by gmarziou** [comment]
I'm more optimistic than you, I don't have time to work on it right now but my idea is to implement org.springframework.cache.interceptor.KeyGenerator or a similar interface and provide a default implementation that uses the request.

If the default implementation does not cover all use cases, users could still implement their own.

**Comment by jdubois** [comment]
@gmarziou  that could be a good candidate for the Hackathon I'd like to organize in our office

**Comment by gmarziou** [comment]
When is your Hackathon?

I will have little time to work on [my example](https://github.com/gmarziou/gateway-ribbon-cache) before beginning of October. I have documented it somehow and added some unit tests.

I agree that configuration is important and could be difficult, I chose a simple approach which is to have a cache per proxified service, this way if the cache does not exist then you know this service is not intended to be cached. But I think that first need, is to write somethin that could be extended by code before writing configuration, I would rather go for a kind of cache toolbox with some basic implmentations so that users can adpat it to their probably richer requirements.

For cache invalidation, I have specified a REST endpoint, combine it with  TTL and we could cover most simple cases.

**Comment by jdubois** [comment]
@gmarziou the hackathon date is not fixed yet (I was waiting to have feedback, but it clearly exceeds expectations!), so probably it would be on September, 20th.
Would you be able to come to Paris? I could ask my company if we need some sponsoring for your trip. Otherwise I could plan to do another one in Lyon (as we are opening a subsidiary there), and that's closer to where you live.

**Comment by gmarziou** [comment]
I'll come back from Rio on September, 20th and I'll probably need to sleep for a whole week to recover from being a supporter at Paralympic Games ;)
Lyon could be a good option.
