### ISSUE TITLE
Issue with Heroku MySQL

### ISSUE THREAD

**Issue by ProDoser** [jhipster/generator-jhipster#3623]
##### **Overview of the issue**
I faced this error after deployed my app to heroku for testing. When I run project locally everythig is fine. Basically every time I triyed to load any entity page, page is loaded but I get this type of error in console:
GET https://myapp.herokuapp.com/api/wish-lists?cacheBuster=1463737763035 500 (Internal Server Error)

When I'm trying to save, the same error for POST and nothing happens. Only pop up errors 

> error.internalServerError

POST https://myapp.herokuapp.com/api/gifts?cacheBuster=1463737780708 500 (Internal Server Error)

**UPDATED**
Errors found at Heroku logs:

> host=mywisher.herokuapp.com request_id=aebcfd58-931d-427e-8fde-d21ba2db21ac fwd="80.220.237.231" dyno=web.1 connect=1ms service=75ms status=404 bytes=741
> 
> 2016-05-20T11:28:26.813006+00:00 app[web.1]: 2016-05-20 11:28:26.812  WARN 3 --- [io-13745-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1146, SQLState: 42S02
> 
> 2016-05-20T11:28:26.813644+00:00 app[web.1]: 2016-05-20 11:28:26.813 ERROR 3 --- [io-13745-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table 'k0eylgvl4u6yvsn8.gift' doesn't exist
> 
> 2016-05-20T11:28:26.823573+00:00 app[web.1]: 2016-05-20 11:28:26.823  WARN 3 --- [io-13745-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Warning Code: 1146, SQLState: 42S02
> 
> 2016-05-20T11:28:26.823741+00:00 app[web.1]: 2016-05-20 11:28:26.823  WARN 3 --- [io-13745-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table 'k0eylgvl4u6yvsn8.gift' doesn't exist

Looks like something wrong with my DB. After standard `yo jhipster:heroku` heroku actomatically add JawsDB MySQL add-on for me. Before I used to add ClearDB by myself without any aditional settings.

Maybe something has changed? Do I need to make some additional configurations to run MySQL at heroku.

Before I used to use MySQL both in development and in production. This time I use H2 in memory database for dev and MySQL for production. 

I used jHipster 2.* versions before and never faced such problems.

What could be the reason for that? Just playing around with 3.1.0 version. 

##### **JHipster Version(s)** 
v3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

> {
>   "generator-jhipster": {
>     "jhipsterVersion": "3.1.0",
>     "baseName": "wisher",
>     "packageName": "com.zador.wisher",
>     "packageFolder": "com/zador/wisher",
>     "serverPort": "8080",
>     "authenticationType": "session",
>     "hibernateCache": "ehcache",
>     "clusteredHttpSession": "no",
>     "websocket": "no",
>     "databaseType": "sql",
>     "devDatabaseType": "h2Disk",
>     "prodDatabaseType": "mysql",
>     "searchEngine": "elasticsearch",
>     "buildTool": "gradle",
>     "enableSocialSignIn": true,
>     "rememberMeKey": "",
>     "useSass": false,
>     "applicationType": "monolith",
>     "testFrameworks": [
>       "gatling"
>     ],
>     "jhiPrefix": "jhi",
>     "enableTranslation": true,
>     "nativeLanguage": "en",
>     "languages": [
>       "en",
>       "ru"
>     ]
>   }
> }

##### **My entity created in JDL-Studio** 
Maybe `"fieldValidateRulesMaxlength": 65000` the case? Just normal String has max 255 character. I found somewere this solution for jHipster. It warks perfect locally. 

> {
>   "relationships": [
>     {
>       "relationshipId": 1,
>       "relationshipName": "wishList",
>       "otherEntityName": "wishList",
>       "relationshipType": "many-to-one",
>       "otherEntityField": "name"
>     }
>   ],
>   "fields": [
>     {
>       "fieldId": 1,
>       "fieldName": "name",
>       "fieldType": "String",
>       "fieldValidateRules": [
>         "required"
>       ]
>     },
>     {
>       "fieldId": 2,
>       "fieldName": "pic",
>       "fieldType": "String",
>       "fieldValidateRules": [
>         "required",
>         "maxlength"
>       ],
>       "fieldValidateRulesMaxlength": 1000
>     },
>     {
>       "fieldId": 3,
>       "fieldName": "desc",
>       "fieldType": "String",
>       "fieldValidateRules": [
>         "maxlength"
>       ],
>       "fieldValidateRulesMaxlength": 65000
>     },
>     {
>       "fieldId": 4,
>       "fieldName": "link",
>       "fieldType": "String",
>       "fieldValidateRules": [
>         "maxlength"
>       ],
>       "fieldValidateRulesMaxlength": 1000
>     },
>     {
>       "fieldId": 5,
>       "fieldName": "price",
>       "fieldType": "String"
>     },
>     {
>       "fieldId": 6,
>       "fieldName": "added",
>       "fieldType": "ZonedDateTime",
>       "fieldValidateRules": [
>         "required"
>       ]
>     }
>   ],
>   "changelogDate": "20160520053812",
>   "dto": "no",
>   "pagination": "infinite-scroll",
>   "service": "no"
> }

**UPDATE 2**

I made connection to heroku DB and find out that my tables were not created. only standard jhi_* tables...

##### **Browsers and Operating System** 

Tried Chrome and Firefox with same results

**Comment by jdubois** [comment]
Cachebuster can't create any 500 error, it's just to prevent your browser from caching HTTP requests.
We need to have your stacktrace in order to help you, at the moment this ticket doesn't have enough information.

**Comment by deepu105** [comment]
It could be a glitch try restarting the server. I faced it few times with Jboss, but it was just random and restart helped. Though I didnt have time then to analyse why.

**Comment by ProDoser** [comment]
Updated.
Looks like this issue with MySQL at heroku. Last time when I used jHipster 2.* I didn't made any aditional settings in my project. Do I need to configure production DB this time in application-prod.yml or Heroku suppose to take care of it?

**Comment by ProDoser** [comment]
Update.
So it was my mistake somewhere in JDL-Studio. I simply made new project but with MySQL database for development. Import the same JDL file and it was SQL syntax error.
Now I have to figure out what went wrong :)
Issue is closed
