### ISSUE TITLE
robots.txt secured in gateway applications

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#3626]
##### **Overview of the issue**
Visiting [http://localhost:8080/robots.txt](http://localhost:8080/robots.txt) when running a Gateway results in a 401 error.  Monolithic applications are fine (tested both session and JWT).

##### **Motivation for or Use Case** 
Web crawlers cannot access the robots.txt of a Gateway

##### **JHipster Version(s)** 
Issue present on both v3.3.0 and master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.3.0",
    "baseName": "gatewaytest",
    "packageName": "com.jruddell.ionic",
    "packageFolder": "com/jruddell/ionic",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "4f0eb99fe364ec781dcd61db222b0e2224dd7c56",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```
##### **Reproduce the error** 
Run a registry and gateway and try to access [http://localhost:8080/robots.txt](http://localhost:8080/robots.txt)
##### **Suggest a Fix** 
Adding an antMatcher for robots.txt [here](https://github.com/jhipster/generator-jhipster/blob/bd09d3bd970331a6447b437bb6e64155ba00211d/generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java#L81) works.  Is this the right approach?

**Comment by jdubois** [comment]
I confirm the issue. It is because the configuration is different from a monolith, but it shouldn't be - we need to have the same security configuration here.
