### ISSUE TITLE
Compilation of fresh project failed when selected Social sign-in services and MongoDB

### ISSUE THREAD

**Issue by kraart** [jhipster/generator-jhipster#3633]
##### **Overview of the issue**

Error:(281, 39) java: cannot find symbol
  symbol:   method flush()
  location: variable socialUserConnectionRepository of type com.mycompany.myapp.repository.SocialUserConnectionRepository

##### **Motivation for or Use Case** 

Compilation of the app in IJ IDEA failed

##### **JHipster Version(s)** 
3.3.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.3.0",
    "baseName": "myApp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pl",
    "languages": [
      "pl",
      "en",
      "ru"
    ]
  }
}

##### **Browsers and Operating System** 

Windows 10(didn't manage to open browser yet)

##### **Reproduce the error** 

install from site. select social media login option. import to intellij idea. select compile on main java file

**Comment by jdubois** [comment]
@deepu105 I think this would require a new minor version

**Comment by deepu105** [comment]
yes It can I guess. And may be we could merge https://github.com/jhipster/generator-jhipster/pull/3624 as well as it is a bug as well currently in master
