### ISSUE TITLE
[FEATURE]Using enum which represent the status of the User instead of ```activated``` flag

### ISSUE THREAD

**Issue by stsatlantis** [jhipster/generator-jhipster#3634]
##### **Overview of the issue**

Adding extra statuses/states for the user Entity is not so efficient because it gives more and more fields to the entity (unnecessarily). For example check if the user is deleted (by delete I mean soft delete in this case) you have to have that extra field  and check if it's true of false. Adding further states/statuses which have their own meaning and there is no overlap with other states like: ```pending_registration```, ```active```, ```deactivated```, ```deleted``` would be way much easier.

##### **Suggest a Fix** 

In the User entity change the activated to an enum which represent to current states of the entity like (registering, active, deactivated). Creating an enumeration package in the domain package.

```
public enum UserStatuses{
    REGISTERING(100)
    ACTIVE(200),
    DEACTIVATED(300);
   
    private int value;

    UserStatuses(int value){
        this.value = value;
    }
}
```
Adding a converter for this enum for mapping in the database. Using the AttributeConverter<A, B> interface implementing
``` 
public class UserStatusConverter implements AttributeConverter<UserStatuses, Integer>{}.
```

Modification in the _User class.
```
<% if (databaseType == 'sql') { %>
    @NotNull
    @Column(name = "status", nullable = false)<% }
    @Convert(converter = UserStatusConverter.class) %>
    private UserStatus status;
```

Of course changing the whole system accordingly.
Using other technologies require further research upon request of the implementation.

Side-note: In our application I've done this modification for databaseType sql and it works.

**Comment by deepu105** [comment]
This is un necessary complication for some specific requirement and hence
it better fone on the generated code by the user itself. It doesnt afd mich
value in generating this and hence I dont think we will do this. Sorry.

**Comment by stsatlantis** [comment]
Thanks for the fast reaction. I see it as a way of providing better opportunity for expansion.

**Comment by deepu105** [comment]
I know but then people can argue the same about so many other things as
well. And we cant do it all you know. We have a policy that we wont add
stuff if it doesn't have any value in terms of effort saved. This is such a
case, you can easily change this in the generated code.
