### ISSUE TITLE
[FEATURE] Support Jenkins 2

### ISSUE THREAD

**Issue by cjyar** [jhipster/generator-jhipster#3635]
##### **Overview of the issue**

JHipster currently generates a readme with instructions for making an old-fashioned Jenkins job. The new hotness in Jenkins is [Pipeline](https://github.com/jenkinsci/pipeline-plugin). Pipeline is a great fit for JHipster because JH can generate a Jenkinsfile that will "just work" out of the box.

##### **Motivation for or Use Case** 

JHipster sets up best practices for a new project. Continuous Integration is a best practice.

##### **JHipster Version(s)** 

1.7.0

##### **Suggest a Fix** 

Here's the official [Pipeline tutorial](https://github.com/jenkinsci/pipeline-plugin/blob/master/TUTORIAL.md). But here's a working Jenkinsfile that's compatible with a Gradle JHipster project:

```groovy
node {
    stage 'checkout'
    checkout scm
    sh "./gradlew clean"

    stage 'build'
    sh "npm install"
    sh "./gradlew assemble"

    stage 'test'
    sh './gradlew build --continue'
}
```

As a related fix, I changed my yeoman.gradle to run bower from mode_modules/.bin instead of the global bower installation. That doesn't seem to break anything, and it makes the Jenkins setup really easy:

1. Install Node.js.
2. Install Jenkins 2 with the default plugins.
3. Make a new Pipeline Multibranch job. The only config settings are the address of the project's repository, and how often to poll.

Here's my bower task from yeoman.gradle:

```groovy
task bower(type: Exec) {
    def bower = file('node_modules/.bin/bower')
    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        commandLine 'cmd', '/c', bower, 'install'
    }else{
        commandLine bower, 'install'
    }
}
```

**Comment by atomfrede** [comment]
Maybe its better to integrate it into https://github.com/pascalgrimaud/generator-jhipster-ci. What do you think @pascalgrimaud ?

**Comment by pascalgrimaud** [comment]
@cjyar: indeed, it's a good idea.
There are different ways to work on this :
1) complete the current documentation 
2) add new generate file in the generator-jhipster Jenkinsfile, like we already do with .travis.yml
3) make your own module: generator-jhipster-jenkins
4) add new Jenkins2 support to the module: generator-jhipster-ci, which already support circle-ci and gitlab, as suggested by @atomfrede

I prefer the 4) of course :-) so PR is welcome
And it will make me to refresh this module

**Comment by PierreBesson** [comment]
I have tested Jenkins 2 with the Pipeline plugin, I agree that it should be supported in JHipster. As we already do it for Travis and Jenkins being much more popular than Travis, I think, we could do option 2) (add a very simple Jenkinsfile in all generated projects).

However, we can still do it in the `generator-jhipster-ci` module and I think we could do interesting things there. Actually, I would like enhance the CI module to be able to automatically set up things like docker build and push and advanced build pipelines for microservices.

**Comment by deepu105** [comment]
:+1: for option 2 as many people use jenkins and its more popular in enterprises and stuff.

**Comment by jdubois** [comment]
I also vote for option 2, as many people will want this, it should be in the main generator

**Comment by jdubois** [comment]
And page http://jhipster.github.io/setting-up-ci/ should also be updated accordingly -> you need to fork https://github.com/jhipster/jhipster.github.io for this

**Comment by pascalgrimaud** [comment]
So let's go for option 2!
@cjyar : do you want to contribute and do a PR for this ?

**Comment by cjyar** [comment]
@pascalgrimaud: I can do that, but it may be a few days before I have time.

**Comment by deepu105** [comment]
Should be ok

Thanks & Regards,
Deepu

**Comment by Vaelyr** [comment]
Any progress on that? It seems nice on paper, but in reality it actually requires some setup to properly have it working. At least well documented guide would be helpful for many.

**Comment by cjyar** [comment]
Nothing yet. I'm a new dad, and my non-work coding time has been seriously reduced.

**Comment by pascalgrimaud** [comment]
Congratulations @cjyar !!!

**Comment by pascalgrimaud** [comment]
I'm working on this

**Comment by cjyar** [comment]
@pascalgrimaud Ha! I just sat down to work on it. Please go ahead; I'd like to review your changes.

**Comment by pascalgrimaud** [comment]
@cjyar : it's done! I tested with maven, gradle and microservices, with normal Jenkins2 and Jenkins2 under Docker

**Comment by jdubois** [comment]
Looks like a huge work!! So help for testing will be welcome!

**Comment by deepu105** [comment]
May be we should put some minimal documentation on how to use it as well
for newbies?

Thanks & regards,
Deepu

**Comment by pascalgrimaud** [comment]
@deepu105: I wrote a new page Jenkins2, with some screenshots as documentation. Is it enough or should I complete ?

**Comment by deepu105** [comment]
That seems fine :+1:


Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
Nice job ! However I just noticed that the generated [travis.yml](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/_travis.yml) doesn't actually run tests. Is it normal ?
Also shouldn't we also add a [.gitlab-ci.yml](http://docs.gitlab.com/ce/ci/quick_start/README.html) ?

And how about the idea of adding more features to the build like docker build and push for microservices. Maybe we could add those but commented out. Another solution would be to somehow add those lines to the Jenkinsfile when using the docker-compose sub-generator. Any idea how to achieve that ?

**Comment by pascalgrimaud** [comment]
**.travis.yml** => yes, I noticed that, I'm already working on this, since this morning

**.gitlab-ci.yml** => there is already something in the module [generator-jhipster-ci](https://github.com/pascalgrimaud/generator-jhipster-ci) : [.gitlab-ci.yml](https://github.com/pascalgrimaud/generator-jhipster-ci/blob/master/generators/app/templates/.gitlab-ci.yml) I know, I have to update it... :-D

These current builds provide only "tests". We can think about "deploying" as you suggest in a second step.

@PierreBesson : I don't understand your idea about Jenkinsfile + Sub Docker-compose generator ?

**Comment by PierreBesson** [comment]
My idea was to somehow add the required CI steps for deploying the app only when using the docker-compose sub-generator. I'm not sure if it's doable but the idea would be to appends some lines to the Jenkinsfile when running the docker-compose sub-generator. We could ask for the URL of the registry the user wants to use and correctly tag images (`registry.com/appName`).
