### ISSUE TITLE
Unable to attach into app container

### ISSUE THREAD

**Issue by kkorada** [jhipster/generator-jhipster#3638]
##### **Unable to attach to docker container**
Application Type: MONOLITH
trying to attach to docker container using command
`sudo docker exec -it <containerid> /bin/bash`

##### **Motivation for or Use Case** 
giving me error while attaching to application container

##### **JHipster Version(s)** 
v3.0.0

##### **Browsers and Operating System** 

OS LINUX

**Comment by jdubois** [comment]
I do this all the time... Can you send us the error? Without knowing what the error is, we can't help you.

**Comment by kkorada** [comment]
sure
please find below error

rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"/bin/bash\": stat /bin/bash: no such file or directory"

**Comment by pascalgrimaud** [comment]
Try : `docker exec -it <container id> sh`
If your base image is Alpine, I don't think there is "bash"

**Comment by kkorada** [comment]
thankyou it worked with sh

**Comment by jdubois** [comment]
Strange, I just tested it and I got it working with bash! But I'm on the "master" branch, so maybe it changed.
Anyway, "sh" is probably a safer choice with Alpine.

**Comment by pascalgrimaud** [comment]
@jdubois : it depends on base image. `bash` works with mysql, postgresql, etc... but I don't think it's installed on Alpine.
Anyway, `sh` is enough
