### ISSUE TITLE
jwt secret in configuration

### ISSUE THREAD

**Issue by gregoiredx** [jhipster/generator-jhipster#3640]
##### **Overview of the issue**

It seems dangerous to me to put JWT secret (and other secrets by the way) in application configuration file (as seen in https://github.com/jhipster/jhipster-sample-app-token/blob/master/src/main/resources/config/application-prod.yml#L73).
Those files generally end up in GIT and in worst case scenario in a public repo.

Shouldn't jhipster prevent this by loading the secret from a non versioned place (like an environment variable)?

##### **Suggest a Fix** 

https://github.com/jhipster/generator-jhipster/commit/595e0adbfb05ae4e04732368a1319751d46c92be

**Comment by jdubois** [comment]
It also works if you use an env variable - that's how Spring Boot works, and it's all automatic.

We just generate a default config that works, but indeed if you don't like it that way, use an env variable directly. That's made on purpose, and we agree!

**Comment by PierreBesson** [comment]
Just set the JHIPSTER_SECURITY_AUTHENTICATION_JWT_SECRET env variable and spring boot will use it.

**Comment by gregoiredx** [comment]
ok, nice
