### ISSUE TITLE
i cant to use jhipster with tomcat... how can i do it??

### ISSUE THREAD

**Issue by conte7** [jhipster/generator-jhipster#3646]
My problem is when a use my applicaction JHIPSTER in an application service  TOMCAT. i have the following error When i push "Ingresar"  (see picture ) i get the error, but when i do the same without  application server (java -jar NameProject) I can login without  problem. Please help me.. i need use the application server TOMCAT

pd: sorry for my english

![prueba](https://cloud.githubusercontent.com/assets/14021677/15548986/f403aa28-2280-11e6-88e8-e1879446c3e3.jpg)

**Comment by jdubois** [comment]
Please write a correct title, of course it works on Tomcat -> this pollutes the ticket system, please be nice with us.
And please follow the guidelines and send us your configuration, I putting the "waiting for information" tag.

**Comment by conte7** [comment]
Sorry, i guess its not a issue just i need help :D

**Comment by conte7** [comment]
i am using jhipster with java and database sql server..... but i dont have a web.xml with the servlet to do the login.... i need de web.xml??? .... what configuration do you send that i send you???

**Comment by conte7** [comment]
When the war its deploy on tomcat and i want to loggin i have this error.. but only with tomcat, if not use tomcat i dont have error

GET http://localhost:8080/api/account?cacheBuster=1464198177090 404 (Not found)

**Comment by jdubois** [comment]
OK then please follow our guidelines -> this isn't a bug, it's a question you need to use StackOverflow
