### ISSUE TITLE
JWT Token Expiration Check is undefined. 

### ISSUE THREAD

**Issue by parmarsanjay** [jhipster/generator-jhipster#3651]
##### **Overview of the issue**

JWT Token Expiration Check is undefined. 

console.log("Testing" + AuthServerProvider.hasValidToken());

##### **Motivation for or Use Case** 

JWT Authentication hasValidToken doesn't work. 

##### **JHipster Version(s)** 

Latest 3.3.0.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "3.3.0",
    "baseName": "testjhip",
    "packageName": "com.testjhip",
    "packageFolder": "com/testjhip",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "b75f2b0540a988d8bd82229e8ab88e0d5ca6f423",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn",
      "zh-tw"
    ]
  }
}
~~~

##### **Browsers and Operating System** 

Latest Chrome Browser.

##### **Reproduce the error** 

Following code in auth.jwt.service.js doens't work. token.expires is undefined.

~~~
function hasValidToken () {
            var token = this.getToken();
            return token && token.expires && token.expires > new Date().getTime();
        }

console.log("Testing" + AuthServerProvider.hasValidToken());
~~~
returns 

Testingundefined

##### **Suggest a Fix** 

Should we be using angular-jwt library to decode the token and check the expiry.

~~~
angular.module('app', ['angular-jwt'])
.controller('Controller', function Controller(jwtHelper) {
  var aToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiQXV0aDAiLCJleHAiOjE0MTIyMzQ3MzB9.ZJzxkw4DNohrdk209erOGyVhfZiAQTRLHMR0BuNUuBA';

  var expireDate = jwtHelper.getTokenExpirationDate(aToken);
  var isExpired = jwtHelper.isTokenExpired(aToken);
});
~~~
https://github.com/auth0/angular-jwt

**Comment by Vaelyr** [comment]
If I am not mistaken, then the service method call to `hasValidToken `is never even used to check the validity.

**Comment by jdubois** [comment]
Yes I think this comes from the session-based authentication, to check the validity of the token. Here it's a whole different token, so it doesn't work.

**Comment by jdubois** [comment]
Following my previous comment, this code should be deleted: it's from another authentication mechanism, and simply doesn't work.

**Comment by parmarsanjay** [comment]
Thanks for the comments. So no check for expired JWT token on Angular side?

**Comment by Vaelyr** [comment]
This is done by `TokenProvider` on back-end for you.
