### ISSUE TITLE
Support for Angular js 1.5 + component based routing in Jhipster generated Angularjs code

### ISSUE THREAD

**Issue by madasuk** [jhipster/generator-jhipster#3656]
Do you have any plans to update with Component Based Routing in Jhipster  generated Angularjs code, which is released in Angularjs 1.5 + instead ui state router which is current being generated in jhipster angularjs code?

**Comment by deepu105** [comment]
We haven't discussed this yet, but if the feature is stable enough we could
give it a try

Thanks & Regards,
Deepu

**Comment by gmarziou** [comment]
I don't see the benefit to spend some time on our angular 1 code to rewrite something that already works and that would be a breaking change for existing projects.

**Comment by wmarques** [comment]
Agree with @gmarziou , it's a nice feature but that would be a breaking change and wouldn't make a big difference on performance. The only value I see in such feature would be an easier transition to angular2 as it seems to use also a component-based router.

**Comment by madasuk** [comment]
@gmarziou / @wmarques, Till now without any other thought, I just use Jhipster for my new projects but now whenever I am about to start new project the first request I am receiving from clients and order from managers is to make the application, compatible with Angurlar 2 for easy migration. So, that newly released component router is becoming a blocker for me to use this cute and awesome Jhipster. I am sure many users  may be feeling the same. As Angularjs 2 is already on its way, I am sure that soon or later (not so later .... ) Jhipster should be ready for its migration to Angular2, so I am feeling now supporting component router will be a first step towards that. In long term, even after Angualr 2 on its way, this makes users to use  Jhipster without any other major considerations as long as they want to use Angularjs 1.X.  However the final cake is in your hands. Thanks to Jhipster team for your super excellent work, and this is one of the best work I have come across.  It would nice if the users express their ideas also on this request.

**Comment by gmarziou** [comment]
> However the final cake is in your hands. 

Not only... community's pull requests are always welcome.

**Comment by jdubois** [comment]
For me this will be done as part of our AngularJS 2 roadmap, see #3664

This is quite a lot of work for us, so indeed if your clients and managers want this, they could also pay you to help us have this done. Contributors are always welcome.

I'm closing this as this should go in #3664 -> we could add a new item there if you think that's necessary.
