### ISSUE TITLE
IDE shows error in pom for the maven-resources-plugin

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3658]
##### **Overview of the issue**

IntelliJ shows an error in pom file in the `maven-resources-plugin` section. Apparently resources tag seems to be incorrect with the set goal of `resources`. If I change the goal to `copy-resources` the error disappears.
![image](https://cloud.githubusercontent.com/assets/1107223/15624403/c098fafe-24b9-11e6-96e6-6c1f5b0dd660.png)

##### **Motivation for or Use Case** 

Just a minor quality issue

##### **JHipster Version(s)** 

Master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

Default config for maven monolith

##### **Browsers and Operating System** 

Windows, IntelliJ 15

##### **Reproduce the error** 

Create a default maven monolith and open the project in IntelliJ

##### **Related issues** 

none

##### **Suggest a Fix** 

I'm not sure if the difference between the `resources` goal and `copy-resources` goal causes any side effect but the latter seems to fix the issue.

**Comment by deepu105** [comment]
cc @erikkemperman

**Comment by erikkemperman** [comment]
That's odd, the [docs](http://maven.apache.org/plugins/maven-resources-plugin/plugin-info.html) say it's a valid goal for this plugin. STS doesn't complain about it.

More to the point, I think these goals (resources vs copy-resources) do different things, and changing it might break things. 

Unfortunately I have no time to look into this more this weekend...

Are the `#placeholders#` replaced as expected, and do the destination files (xml and yml) showing up in the right location?

**Comment by deepu105** [comment]
It seems so. I checked docs, while its a valid goal it uses the resources
defined at the build level. only the copy-resources goal looks for it
inside the plugin execution.

Thanks & Regards,
Deepu

**Comment by erikkemperman** [comment]
> it uses the resources defined at the build level

I'm not sure what that means -- since it was correctly replacing the yml and xml files -- but of course the important thing is it works. I've just replaced the plugin in my project and STS is (remains) fine with it.

**Comment by jdubois** [comment]
I'm updating to the latest (3.0.0) version of the plugin, it solves the issue in the IDE. Hopefully it doesn't break the functionnality!!!

**Comment by erikkemperman** [comment]
Did we not want to change the goal?

**Comment by jdubois** [comment]
@erikkemperman I only corrected the "warnings", and it looks like it's working, but I didn't look at the other plugin

**Comment by erikkemperman** [comment]
@jdubois It was working fine for me before too, but this issue caused us to look closer at the plugin docs and it looks as though the other goal (same plugin, just `resources:copy-resources` instead of `resources:resources`) might be a better fit.

**Comment by jdubois** [comment]
I looked at the doc and to be honest I don't understand the difference between the two goals... With this one it looks like it's working fine, I don't know if `copy-resources` would do anything better. What makes you think it's doing things better?

**Comment by jdubois** [comment]
I'm re-opening this as it's red again in Intellij!!!! WTF? So maybe we should migrate to `copy-resources` indeed

**Comment by erikkemperman** [comment]
I think @deepu105's theory was that this line in the docs for `resources` goal ...

> Always uses the project.build.resources element to specify the resources to copy.

... means that we could not override this property in the configuration/execution, as we were (are) doing. Even though it does seem to be working when invoking maven, apparently IntelliJ considers it an error to have a `resources` element.

The `copy-resources` goal looks like it does more or less the right thing too, from its description, without this restriction. I'm not sure if they run in the same lifecycle phase, though, or if that is even relevant.

For what it's worth, a completely anecdotal experiment in my own project indicated that changing to `copy-resources` doesn't break anything.

**Comment by deepu105** [comment]
I guess we can safely use `copy-resources` I tested and this seems to work without any issues.
