### ISSUE TITLE
Bug - Elastic search not working with blank query

### ISSUE THREAD

**Issue by jsingy** [jhipster/generator-jhipster#3666]
##### **Overview of the issue**

When using elastic search, on the entity list page, pressing the search button with a blank search field creates the following error `vm.loadAll is not a function`.

##### **JHipster Version(s)** 

3.4.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "lc",
    "packageName": "com.bloomersoft.lc",
    "packageFolder": "com/bloomersoft/lc",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "64bcc333be78fa82e7432959fa2f98bbf236c2e0",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
```

##### **Suggest a Fix** 

In the generators/entity/templates/src/main/webapp/app/entities folder, in the following files: infinite-scroll-template.ejs, no-pagination-template.ejs, pagination-template.ejs, add vm.loadAll = loadAll.

Example
```
        <%_ if (searchEngine == 'elasticsearch') { _%>
        vm.clear = clear;
        vm.search = search;
        vm.loadAll = loadAll;
        vm.searchQuery = pagingParams.search;
```

**Comment by deepu105** [comment]
Do you want to do a PR?

**Comment by jsingy** [comment]
I will be happy to do so. I tried following the instructions at https://help.github.com/articles/creating-a-pull-request/.

I tried to push a branch to the jhipster repository, but I am not authorized to do so. 

Is there another way to create a pull request?

**Comment by jdubois** [comment]
Thanks!!
