### ISSUE TITLE
Error: [$injector:strictdi] function(JhiTrackerService) is not using explicit annotation and cannot be invoked in strict mode

### ISSUE THREAD

**Issue by lgscofield** [jhipster/generator-jhipster#3669]
##### **Overview of the issue**

`angular.js:13550 Error: [$injector:strictdi] function(JhiTrackerService) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.5.5/$injector/strictdi?p0=function(JhiTrackerService)
    at angular.js:68
    at Function.annotate [as $$annotate] (angular.js:3903)
    at injectionArgs (angular.js:4626)
    at Object.invoke (angular.js:4657)
    at $state.transition.resolved.then.$state.transition (angular-ui-router.js:3318)
    at processQueue (angular.js:15961)
    at angular.js:15977
    at Scope.$eval (angular.js:17229)
    at Scope.$digest (angular.js:17045)
    at Scope.$apply (angular.js:17337)(anonymous function) @ angular.js:13550(anonymous function) @ angular.js:10225processQueue @ angular.js:15969(anonymous function) @ angular.js:15977Scope.$eval @ angular.js:17229Scope.$digest @ angular.js:17045Scope.$apply @ angular.js:17337done @ angular.js:11572completeRequest @ angular.js:11778requestLoaded @ angular.js:11711`
##### **Motivation for or Use Case** 

http://my-ip:my-port/#/tracker

##### **JHipster Version(s)** 

v3.4.0
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

`{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "JHdap",
    "packageName": "com.wb.jhdap",
    "packageFolder": "com/wb/jhdap",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "b1f058bd61661e7c181cae8fcb257f1dfb85a778",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn"
    ]
  }
}`

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

No Entity...

##### **Browsers and Operating System** 

Chrome: 50.0.2661.102 m (64-bit)  and Windows 10

**Comment by wmarques** [comment]
@lgscofield You have to manually inject dependencies by using `JhiTrackerService.$inject = .. ` as we do in controllers files for example. Would you provide à Pull Request to fix this ?

**Comment by deepu105** [comment]
I guess I already fixed it in master.

**Comment by wmarques** [comment]
Oh ok so @lgscofield check the file on the master and do the same or remove the `strict-di` attribute in index.html file to remove the strict-di mode

**Comment by lgscofield** [comment]
@wmarques All right, I'll try it.

**Comment by lgscofield** [comment]
@wmarques Wow, this is a good solution.

**Comment by wmarques** [comment]
Closing this as it is already fixed in master.
