### ISSUE TITLE
Options in the generator for Auditing

### ISSUE THREAD

**Issue by tg44** [jhipster/generator-jhipster#3674]
* **Overview of the request**

Some steps would be nice in the entity creation dialog where we can add some pregenerated functionality like the User AuditingEntity.

* **Motivation for or Use Case** 

Auditing some other entities too :)
Like if you want to make reports, you can easily audit them, who created, who touched it when these happend etc. It would be nice if the generator can ask me a question like: "Are you want audit fields (created_by, created_at, last_mod_by, last_mod_at) for this object?" And if I say yes ask me another question like "Are you want the audit informations on the list view too?".

**Comment by pascalgrimaud** [comment]
I think the [generator-jhipster-entity-audit module](https://github.com/hipster-labs/generator-jhipster-entity-audit) is what you're looking for
