### ISSUE TITLE
Add Bootswatch themes to Jhipster

### ISSUE THREAD

**Issue by tvd27285** [jhipster/generator-jhipster#3680]
I'm using Jhipster to build my application.

Now, I want add Bootswatch themes to. I get this error:

XMLHttpRequest cannot load https://bootswatch.com/api/3.json?cacheBuster=1464851732487. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.4.13:8080' is therefore not allowed access. 
The response had HTTP status code 403.

Do this error can CORS config?
Please help me!

**Comment by jdubois** [comment]
This is the ticket system, you should ask for help on StackOverflow.
And this is what you are looking for: http://jhipster.github.io/modules/marketplace/#/details/generator-jhipster-bootswatch
