### ISSUE TITLE
SecurityUtils.getCurrentUser() throws an Exception when using ActiveDirectoryLdapAuthenticationProvider

### ISSUE THREAD

**Issue by optimalab** [jhipster/generator-jhipster#3682]
##### **Overview of the issue**

If the application generated is configured to use a different or additional Spring Security Authentication provider, the call to SecurityUtils.getCurrentUser() incorrectly rises a "User not found!" Exception, since the cast to User fails.

##### **Motivation for or Use Case** 

I believe that the cast to the concrete class User is not needed, it's enough to check if authentication.getPrincipal returns an object implementing the UserDetails interface.

##### **JHipster Version(s)** 

Jhipster 2.27.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "baseName": "jRicambi",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "oracle",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "useSass": false,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

Entities generated are irrelevant to the error.

##### **Browsers and Operating System** 

Tested on Mac OSX and Linux Centos 7 on Apache Tomcat 8

##### **Reproduce the error** 

This is how I modified the SecurityConfiguration class to add an optional ActiveDirectory authentication if the default Dao authentication fails:
`    @Bean
    public AuthenticationProvider daoAuthenticationProvider() {
        DaoAuthenticationProvider provider = new DaoAuthenticationProvider();
        provider.setPasswordEncoder( passwordEncoder() );
        provider.setUserDetailsService( userDetailsService );
        return provider;
    }

    @Bean
    public AuthenticationProvider activeDirectoryLdapAuthenticationProvider() {
        ActiveDirectoryLdapAuthenticationProvider provider = new ActiveDirectoryLdapAuthenticationProvider(
            ACTIVE_DIRECTORY_DOMAIN, ACTIVE_DIRECTORY_URL
        );
        provider.setConvertSubErrorCodesToExceptions( true );
        provider.setUseAuthenticationRequestCredentials( true );
        return provider;
    }

    @Inject
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        auth
            .authenticationProvider( daoAuthenticationProvider() )
            .authenticationProvider( activeDirectoryLdapAuthenticationProvider() )
            .userDetailsService(userDetailsService());
    }
`
##### **Related issues** 

None

##### **Suggest a Fix** 

Simply replacing User with the interface UserDetails seems to solve the issue:
```
    public static UserDetails getCurrentUser() {
        SecurityContext securityContext = SecurityContextHolder.getContext();
        Authentication authentication = securityContext.getAuthentication();
        if (authentication != null) {
            if (authentication.getPrincipal() instanceof UserDetails) {
                return (UserDetails) authentication.getPrincipal();
            }
        }
        throw new IllegalStateException("User not found!");
    }

```

**Comment by jdubois** [comment]
I believe this was fixed in a recent version, as we had the same kind of issue with JWT

Of course I can't test your code as this is not a "standard" JHipster feature (we don't provide LDAP authentication out of the box, but it is important to have it working without too much issues).

-> I'm closing this as I can't test and I think it's corrected, if you have time, can you check with a recent 3.4.0 version?

**Comment by optimalab** [comment]
I had a look to 3.4.0, and the method now returns a String and internally casts to UserDetails, so I think it's ok. As soon as I can migrate the application to the latest version (it will take some time), I can confirm, but I'm positive.

Thank you

**Comment by jdubois** [comment]
Thanks @optimalab , that's what I was thinking of
