### ISSUE TITLE
except not working in jdl

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#3683]
##### **Overview of the issue**
i have created a file with the jdl studio with the line:
service all with serviceImpl except Task

and get the error:

    SyntaxError: Expected "/*", "//", "dto", "entity", "enum", "paginate", "relationship", "service", a space or end of input but "e" found.
    at peg$buildException (***/node_modules/generator-jhipster/node_modules/jhipster-uml/lib/dsl/jhGrammar.js:364:14)
    at Object.peg$parse [as parse] (***/node_modules/generator-jhipster/node_modules/jhipster-uml/lib/dsl/jhGrammar.js:4403:13)
    at DSLParser.parse (***/node_modules/generator-jhipster/node_modules/jhipster-uml/lib/dsl/dsl_parser.js:30:27)

##### **JHipster Version(s)** 

3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
[yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/299013/yo-rc.json.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

[tessaBeta.jh.txt](https://github.com/jhipster/generator-jhipster/files/299016/tessaBeta.jh.txt)

##### **Browsers and Operating System** 

ubuntu 

##### **Reproduce the error** 

yo jhipster:import-jdl tessaBeta.jh.txt

could it be somewhere a wrong version?

yo --version gives me:
1.8.4

**Comment by tibistibi** [comment]
as a work around i split the jh file (mine was long)

**Comment by jdubois** [comment]
Could you put a clear title?

**Comment by jdubois** [comment]
I have no idea what this `except Task` is in your JDL file -> for me this is not correct JDL syntax, so quite logically this fails.
I'm not an expert in JDL (you should have opened this ticket on the JDL project), so you find this is a correct syntax, please add a comment.

**Comment by tibistibi** [comment]
according to the documentation this hould be possible:

service all with serviceImpl except A, B, C

see: http://jhipster.github.io/jdl/

**Comment by jdubois** [comment]
Oh you are correct. I'm reopening this, but this should be a ticket on the JDL project, here we probably can't do anything about it.

**Comment by tibistibi** [comment]
thanks. i was not aware of a specific project for jdl. will see if i can move it.

**Comment by jdubois** [comment]
Oh, I'm seeing this is on a recent version, and you are using JHipster 3.0.0 -> I'm guessing your version doesn't have this already.

Can you install JHipster UML, to have a more recent version, and test it with "jhipster-uml yourfile.txt"? It's working the same way, but it's not bundled with JHipster.

**Comment by deepu105** [comment]
This is probably another issue of disparity between JHUML and import-jdl feature due to different versions being used :(

**Comment by tibistibi** [comment]
this could be. maybe it is a good idea to add the version information to the documentation

**Comment by deepu105** [comment]
This is tracked in https://github.com/jhipster/generator-jhipster/issues/3532 so lets close this to avoid confusion.

**Comment by tibistibi** [comment]
is it smart to add this to the documentation (so not everyone has to figure it out again)

**Comment by deepu105** [comment]
Lets see if we are not able to get this fixed soon we could consider
updating the docs.

Thanks & Regards,
Deepu
