### ISSUE TITLE
[DOCS] Add more documentation for jdl on service options

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#3685]
In the jdl documentation on:
http://jhipster.github.io/jdl/
under ''Option declaration'':

    The keywords dto, paginate, service and with were added to the grammar to support these changes.

I would like an extension explaining what the options are for services.
what i did now was make 3 entities one without a service one with class and one with impl to figure it out.  

an option for the documentation is:

No services specified will create a resource class which will call the repository interface directly. This is the default and simplest option. 
Service with serviceClass will make the resource call the service class which will call the repository interface. With service with serviceImpl will make an service interface which will be used by the resource class. The interface is implemented by an impl class which will call the repository interface.

**Comment by deepu105** [comment]
@tibistibi would you like to PR this to our documentation site https://github.com/jhipster/jhipster.github.io

**Comment by tibistibi** [comment]
yes i would with is the procedure to PR?

**Comment by tibistibi** [comment]
note to myself it this page:
https://github.com/jhipster/jhipster.github.io/blob/master/pages/jdl.md

**Comment by deepu105** [comment]
@tibistibi 
1. fork the repo https://github.com/jhipster/jhipster.github.io and get it to your local disk
2. checkout a new branch, update the above markdown page and commit
3. push to your local branch to your fork
4. create a new pull request to the original repo

**Comment by tibistibi** [comment]
sounds like fun ;)

**Comment by tibistibi** [comment]
wondering what PR stands for i think i did it:

https://github.com/jhipster/jhipster.github.io/pull/278

**Comment by jdubois** [comment]
Yes it's done and merged, thanks!
