### ISSUE TITLE
[FEATURE] Modify button in <entity>detail.html page

### ISSUE THREAD

**Issue by lrkwz** [jhipster/generator-jhipster#3695]
##### **Overview of the issue**

It would be usefull having a "Modify" button in <entity>-detail.html page.
I've dropped one with a simple

    <button type="submit" ui-sref="address.edit({id:vm.address.id})" class="btn btn-primary btn-sm">
		<span class="glyphicon glyphicon-pencil"></span>
		<span class="hidden-xs hidden-sm" translate="entity.action.edit"></span>
    </button>    

pressing the button displays the correct form in an overlay with the entities list behind.

##### **Motivation for or Use Case** 

It would be much more "natural" to navigate data and being able to modify what you are looking at.

##### **JHipster Version(s)** 
3.4.0

**Comment by atomfrede** [comment]
I'm working in this. Would like to introduce a new state ``participant-detail.edit`` in order not to switch to the entity list in background and to be able to stay on the detail page after saving the entity.
