### ISSUE TITLE
[FEATURE] remove DB password from application-prod.yml to avoid double config

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#3697]
at this moment the database is configured at 2 places. one in the pom file and one in the application-dev.yml/application-prod.yml
basides this the password is added to these files which are under sourcecontrole. 

2 things i don't like.

my solution is to use maven filtering. a small change in the pom file adding filtering to yml files and adding the placeholders into the yml file will do the trick.

pom.xml

            <resources>
            <resource>
                <directory>src/main/resources/</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.xml</include>
                    <include>**/*.yml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources/</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>**/*.xml</exclude>
                    <exclude>**/*.yml</exclude>
                </excludes>
            </resource>
        </resources>
    <properties> 
    	<db.username>root</db.username>
    	
    	<db.password></db.password>

yml files:

            username: @db.username@
        password: @db.password@

**Comment by jdubois** [comment]
Those don't have to be in source control, have a look at:

- How to configure Spring Boot properties -> in "normal" setup, people will probably use env variable for passwords. This is close to what you want to do.
- How we use Spring Cloud Config in the JHipster Registry -> in "advanced" setup, people should use a JHipster Registry to store such data

But whatever you choose, the idea is that we use standard Spring Boot properties, because that's what people are expecting to use with Spring Boot. This also follows our [policy 1](https://jhipster.github.io/policies/)

**Comment by tibistibi** [comment]
ok thanks.

i looked in the code and see that the filtering is already added to the pom file. so maybe someone is working on this?

**Comment by jdubois** [comment]
Oh yes, there is filtering, but this is used for our "dev" and "prod" profiles, as those need to be configured *before* Spring Boot (as they configure Spring Boot, obviously). So for those we don't have any other choice, as they can't be Spring Boot properties.
Of course, if you want to, you can use the same mechanism yourself.

**Comment by tibistibi** [comment]
thanks :smile: 

i agree that following policy for jhipster is best. and maybe I'm old fashioned that i stick to the appfuse way of filtering. at least my db config is in one place now :smiley: 

while i'm looking i think it is strange the username in the pom file is different thant the username in the yml file:
pom:

    <username><% if (devDatabaseType === 'mysql') { %>root<% } else if (devDatabaseType === 'postgresql' || devDatabaseType === 'h2Disk' || devDatabaseType === 'h2Memory') { %><%= baseName %><% } %></username>

yml:

            username: <% if (devDatabaseType == 'mysql' || devDatabaseType == 'mariadb') { %>root<% } else if (devDatabaseType == 'postgresql' || devDatabaseType == 'h2Disk' || devDatabaseType == 'h2Memory') { %><%= baseName %><% } %>

for mysql (which i use it equal) but for mariadb it is not. 

(i still with propose to make this code in one place avoiding these bugs but if policy is in they way i understand)

**Comment by tibistibi** [comment]
if you want i can make a bug and a PR for this (should mariadb default to root?)

**Comment by jdubois** [comment]
I need more info, where in the pom compared to where, which yml file?
This is working fine for many, many applications, so I'm confident this is correct.

And the current way of configuring Spring Boot is the standard way, which most people are expecting, so I'm not going to change it.

**Comment by tibistibi** [comment]
i agree to stick to the standard way. but just to make sure we are talking on the same thing. i only suggest to not put the username and password in the application-dev.yml and application-prod.yml next to the one in the pom.xml directly. but put them on one place (in the pom.xml) and let the yml copy it via the filter option.
so in the application-dev.yml the change wil be from:

    username: root

to

    username: @db.username@

you think its against the Spring Boot policy i understand this will not go.
 

the other issue is that only in a mariadb option in the application-dev.yml the username will be set to root but in the pom.xml it will not be set (will be empty)

**Comment by Vaelyr** [comment]
For dev this might be okay. Not sure. I never found it to be an issue, you configure it once and that's it. You would never point liquibase plugin against production database anyway.

For placeholders it should work for sure with filters:
http://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html#howto-use-short-command-line-arguments

**Comment by jdubois** [comment]
Oh yes for the Maven Liquibase goal: that's only for development, you're not going to run a Maven goal on a production server, normally.
So yes this goal should have the same configuration as the `application.yml` file, and that's a bit annoying. That's why you should use our Docker configuration, so that everything is set up for you.

**Comment by tibistibi** [comment]
and why not make it a one place config like i suggest?
as you can see the yml and the pom are generated separately prone to bugs

**Comment by jdubois** [comment]
It causes other issues in the `application.yml` file, as you need to have Maven running before launching.
Here's a very classic use-case where this doesn't work:

- check out a project
- open it up in Idea
- click on the "run" button

As Maven didn't run, you won't have the variable replaced. We've had lots of issues with this for the profiles.

**Comment by tibistibi** [comment]
ok. than i agree and will keep the change for my self.

for the difference for the mariadb should a make a bug? or is it not a big problem?

**Comment by Vaelyr** [comment]
What perhaps could be changed, is that the liquibase configuration is moved into it's own properties/yaml file, as the liquibase plugins should support external configurations for sure under classpath resources, instead of having them in the build scripts.

**Comment by deepu105** [comment]
For difference in mariadb a PR fix is welcome

**Comment by tibistibi** [comment]
ok i will do this next week

**Comment by jdubois** [comment]
- yes for MariaDB, of course
- @Vaelyr I don't want to have another specific configuration file - here people are using the Liquibase Maven goal, and have this goal pre-configured, so that's a quite "logical" usage and I don't want to have it more complex. But I agree this isn't perfect.

**Comment by Vaelyr** [comment]
I agree, I also like current approach. Configure it once against local database and no need to touch it anymore.

**Comment by tibistibi** [comment]
i agree, not perfect but best solution

**Comment by tibistibi** [comment]
after one and a halve years i see the yml filtering made it into the pom file.
not sure why but cool :+1:

**Comment by tibistibi** [comment]
the filtering works now out of the box. just add in yml file:

        password: #db.password#

and create package:

       ./mvnw -Pprod package -Ddb.password=mySecret

**Comment by gmarziou** [comment]
Fine but I don't think that putting prod passwords inside the war is something we should recommend.
