### ISSUE TITLE
Inconsistent plural form in generated dialog.controller.js and dialog.html

### ISSUE THREAD

**Issue by dewafer** [jhipster/generator-jhipster#3702]
##### **Overview of the issue**

I was trying importing the default jhipster-jdl.jh provided by https://jhipster.github.io/jdl-studio/ to a new generated project, and I found out that in the Create or edit a Location dialog, the Country drop-drown list is empty. 

The problem is caused by inconsistent plural form in generated dialog.controller.js and dialog.html.

The generated ng-options in location-dialog.html is:

`ng-options="country as country.id for country in vm.countries | orderBy:'id' track by country.id"`

But the generated code in location-dialog.controller.js is:

`vm.countrys = Country.query({filter: 'location-is-null'});`

##### **Motivation for or Use Case** 

I guess this is a bug, right?

##### **JHipster Version(s)** 

JHipster Generator v3.4.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f5c1e2ce32947cddf9693e2ae3dd4b39b597b377",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

```

entity Region {
	regionId Long,
	regionName String
}

entity Country {
	countryId Long,
	countryName String
}

entity Location {
	locationId Long,
	streetAddress String,
	postalCode String,
	city String,
	stateProvince String
}

entity Department {
	departmentId Long,
	departmentName String required
}

entity Task {
	taskId Long,
	title String,
	description String
}

/**
 * The Employee entity.
 */
entity Employee {
	employeeId Long,
	/**
	* The firstname attribute.
	*/
	firstName String,
	lastName String,
	email String,
	phoneNumber String,
	hireDate ZonedDateTime,
	salary Long,
	commissionPct Long
}

entity Job {
	jobId Long,
	jobTitle String,
	minSalary Long,
	maxSalary Long
}

entity JobHistory {
	startDate ZonedDateTime,
	endDate ZonedDateTime,
	language Language
}

entity Test1 {
	testId Long,
	name String,
}

entity Test2 {
	test2Id Long,
    name String,
}

relationship OneToMany {
	Test2{test2Id} to Test1
}

enum Language {
    FRENCH, ENGLISH, SPANISH
}

relationship OneToOne {
	Country{region} to Region
}

relationship OneToOne {
	Location{country} to Country
}

relationship OneToOne {
	Department{location} to Location
}

relationship ManyToMany {
	Job{task(title)} to Task{job}
}

relationship OneToMany {
	Employee{job} to Job
}

relationship OneToMany {
	/**
	* A relationship
	*/
	Department{employee} to
	/**
	* Another side of the same relationship
	*/
	Employee
}

relationship ManyToOne {
	Employee{manager} to Employee
}

relationship OneToOne {
	JobHistory{job} to Job
}

relationship OneToOne {
	JobHistory{department} to Department
}

relationship OneToOne {
	JobHistory{employee} to Employee
}

paginate JobHistory, Employee with infinite-scroll
paginate Job with pagination

dto Employee with mapstruct

service Employee with serviceClass

	
```
##### **Browsers and Operating System** 

Windows 7 and Chrome

##### **Reproduce the error** 

1. generate a new project
2. import jhipster-jdl.jh using `yo jhipster:import-jdl jhipster-jdl.jh` (got from https://jhipster.github.io/jdl-studio/)
3. after startup the new generated project, create some Regions and Countries
4. click `Create a new Location` in Location page
5. the drop-down list of Country is empty although there are some Countries in db

##### **Related issues** 

None

##### **Suggest a Fix** 

Maybe change the following code on line 28 of [_entity-management-dialog.controller.js](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/src/main/webapp/app/entities/_entity-management-dialog.controller.js#L28) from 
```
query = 'vm.' + relationships[idx].relationshipFieldName.toLowerCase() + 's = ' + relationships[idx].otherEntityNameCapitalized + ".query({filter: '" + relationships[idx].otherEntityRelationshipName.toLowerCase() + "-is-null'});"
```
to
```
query = 'vm.' + relationships[idx].relationshipFieldNamePlural + ' = ' + relationships[idx].otherEntityNameCapitalized + ".query({filter: '" + relationships[idx].otherEntityRelationshipName.toLowerCase() + "-is-null'});"
```
?
I'm not sure about this.

Thanks.

**Comment by deepu105** [comment]
yes its a bug. do you want to PR a fix?

**Comment by dewafer** [comment]
Hi @deepu105 , I'd love to, but I can't do it right now. I'll submit a PR fix later.

**Comment by jdubois** [comment]
Oh yes that's a bug!
