### ISSUE TITLE
"show-validation" directive is not in sync with the input validation

### ISSUE THREAD

**Issue by gvsrini** [jhipster/generator-jhipster#3703]
##### Form Validation Issue

This bug is seen for all form validations

##### Appears on all Forms (Dialogs)

Form group unnecessarily turns red even when the input box has correct data

##### All Versions

This is there in all versions of JHipster.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "XXXX",
    "packageName": "XXX",
    "packageFolder": "XXX",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "XXX",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
Default App

##### **Browsers and Operating System** 
Firefox on Windows and Linux

##### **Reproduce the error** 
1. On Home Page, From Menu, Go to Sign In and Forgot Password
2. Enter abc@g. **No error in this value - CORRECT**
3. Enter backspace 
4. Screen will have abc@ and it will show validation errors. But there is no Red Border for Form Group. 
5. Now enter a character "g". Screen should show abc@g. Now the Red border appears - AFTER validation errors disappear. **No Error in this value - RED BORDER INCORRECT**
6. This is a disconnect. Red Border should have appeared along with error message in Step 4 and disappear in Step 5, whereas it appeared freshly in Step 5.
7. This happens in ALL forms ALL fields and is more prominent for other validations.

##### **Related issues** 

Not Applicable

##### **Suggest a Fix** 

**The problem is most probably because of the screen value and model value not being in sync.**

See Code and Screenshots below

This is the code which is causing the problem: src/main/webapp/app/components/form/show-validation.directive.js.

```
                if ($inputs.length > 0) {
                    $inputs.each(function() {
                        var $input = angular.element(this);
                        scope.$watch(function() {
                            return $input.hasClass('ng-invalid') && $input.hasClass('ng-dirty');
                        }, function(isInvalid) {
                            $formGroup.toggleClass('has-error', isInvalid);
                        });
                    });
                }
```

![noerror](https://cloud.githubusercontent.com/assets/150018/15999674/ddd16072-3164-11e6-866c-08af02ef7116.png)

![error](https://cloud.githubusercontent.com/assets/150018/15999683/eea5fcc8-3164-11e6-9887-37bd77b3da9a.png)

**Comment by deepu105** [comment]
would you like to do a PR to fix this


Thanks & Regards,
Deepu

**Comment by gvsrini** [comment]
Though I know the source of the problem, the solution does not look straight forward. Any help in the right direction will be appreciated.

**Comment by jdubois** [comment]
I confirm the issue.
It's major, as everybody gets this issue, and it indeed comes from our "showValidation" directive: it cannot watch correctly a change made in the DOM by another directive.

**Comment by atomfrede** [comment]
I have a working solution. @deepu105 If you have time you can try it and if you are ok with it I'll provide a PR.

```javascript
function linkFunc (scope, element, attrs, formCtrl) {
            element.find('.form-group').each(function() {
                var $formGroup = angular.element(this);
                var $inputs = $formGroup.find('input[ng-model],textarea[ng-model],select[ng-model]');

                if ($inputs.length > 0) {
                    $inputs.each(function() {
                        var $input = angular.element(this);
                        var inputName = $input.attr('name');

                        scope.$watch(function() {
                            return formCtrl[inputName].$invalid && formCtrl[inputName].$dirty;
                        }, function(isInvalid) {
                            $formGroup.toggleClass('has-error', isInvalid);
                        });
                    });
                }
            });
        }
```

**Comment by deepu105** [comment]
The code looks fine, ill have some time this weekend. In the meantime you
can do the PR as we can improve it later if required

Thanks & regards,
Deepu

**Comment by atomfrede** [comment]
I'll do the PR this evening
