### ISSUE TITLE
jhipster deleted table

### ISSUE THREAD

**Issue by sabrineZhr** [jhipster/generator-jhipster#3706]
Hi Guys,
I am using mssql and I deleted jhi_user table and now when I run mvn command I get this error
"com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'jhi_user'"
I thought that it will be regenerated but it's not the case.
Thank you.

**Comment by jdubois** [comment]
This works with Liquibase: you need to learn about how Liquibase works first.
This is a question, and not an issue -> I'm closing this according to our guidelines, please use StackOverflow next time

**Comment by sabrineZhr** [comment]
I know how liquibase works and I did the same thing with h2. And I had no problem with it.

**Comment by jdubois** [comment]
Maybe you dropped your whole H2 database instead?
All database operations must go through Liquibase if you want it to work properly.

**Comment by sabrineZhr** [comment]
Hello,
Yes I am working with only mssql database and liquibase.

2016-06-13 17:33 GMT+02:00 Julien Dubois <notifications@github.com>:

> Maybe you dropped your whole H2 database instead?
> All database operations must go through Liquibase if you want it to work
> properly.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/3706#issuecomment-225617589>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIV_EbnA3NM2vcewazLuovcsV-DdYj3rks5qLXg4gaJpZM4I0aVL>
> .
>



-- 
Cordialement,

ZAHAR Sabrine
