### ISSUE TITLE
User Management with Cassandra Temporarily Broken

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#3719]
##### **Overview of the issue**
From my recent PR #3712, user management does not load because Cassandra does not support sorting.

##### **JHipster Version(s)** 
Master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
Any Cassandra project

##### **Suggest a Fix** 
I will fix the issue this in an hour or two.

**Comment by pascalgrimaud** [comment]
closed by #3712

**Comment by ruddell** [comment]
That PR was for client 2.  My internet went out at home so I'll send in my code tonight

**Comment by pascalgrimaud** [comment]
Oh sorry, I reopen this.
Time to sleep for me :D

**Comment by ruddell** [comment]
I still need to PR Client-2's code but I want to wait for #3726 to get pulled before I update user-management.state.js

**Comment by deepu105** [comment]
Its merged

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
If that's merged can we close this?

**Comment by ruddell** [comment]
Just PRed the angular-2 code so now it should be fixed.
