### ISSUE TITLE
The jdl is being imported

### ISSUE THREAD

**Issue by wnbaq** [jhipster/generator-jhipster#3724]
First I run jhipster succesfully then I am trying to import JDL. But It couldn't produce entities in my project. I just take this:

    C:\Users\PER\alo>yo jhipster:import-jdl jhipster-jdl.jh
    The jdl is being imported.

    C:\Users\PER\alo>

Jhipster-jdl.jh is downloaded from default JDL Studio.

My yo-rc.json is:
{
"generator-jhipster": {
"jhipsterVersion": "3.4.1",
"baseName": "alo",
"packageName": "com.mycompany.myapp",
"packageFolder": "com/mycompany/myapp",
"serverPort": "8080",
"authenticationType": "session",
"hibernateCache": "ehcache",
"clusteredHttpSession": "no",
"websocket": "no",
"databaseType": "sql",
"devDatabaseType": "mysql",
"prodDatabaseType": "mysql",
"searchEngine": "no",
"buildTool": "maven",
"enableSocialSignIn": false,
"rememberMeKey": "596620c1e6cb3dee257f152d8792b4156147f170",
"useSass": false,
"applicationType": "monolith",
"testFrameworks": [
"gatling"
],
"jhiPrefix": "jhi",
"enableTranslation": false
}
}

**Comment by gmarziou** [comment]
Could you share your jdl? 
And also your environment details: node version, OS?

**Comment by wnbaq** [comment]
node version: 3.9.5 , OS: 64bit on

 Windows10 , MySQL 5.7 

entity Region {
	regionId Long,
	regionName String
}

entity Country {
	countryId Long,
	countryName String
}

entity Location {
	locationId Long,
	streetAddress String,
	postalCode String,
	city String,
	stateProvince String
}

entity Department {
	departmentId Long,
	departmentName String required
}

entity Task {
	taskId Long,
	title String,
	description String
}

/**
 * The Employee entity.
 */
entity Employee {
	employeeId Long,
	/**
	* The firstname attribute.
	*/
	firstName String,
	lastName String,
	email String,
	phoneNumber String,
	hireDate ZonedDateTime,
	salary Long,
	commissionPct Long
}

entity Job {
	jobId Long,
	jobTitle String,
	minSalary Long,
	maxSalary Long
}

entity JobHistory {
	startDate ZonedDateTime,
	endDate ZonedDateTime,
	language Language
}

enum Language {
    FRENCH, ENGLISH, SPANISH
}

relationship OneToOne {
	Country{region} to Region
}

relationship OneToOne {
	Location{country} to Country
}

relationship OneToOne {
	Department{location} to Location
}

relationship ManyToMany {
	Job{task(title)} to Task{job}
}

relationship OneToMany {
	Employee{job} to Job
}

relationship OneToMany {
	/**
	* A relationship
	*/
	Department{employee} to
	/**
	* Another side of the same relationship
	*/
	Employee
}

relationship ManyToOne {
	Employee{manager} to Employee
}

relationship OneToOne {
	JobHistory{job} to Job
}

relationship OneToOne {
	JobHistory{department} to Department
}

relationship OneToOne {
	JobHistory{employee} to Employee
}

paginate JobHistory, Employee with infinite-scroll
paginate Job with pagination

dto Employee with mapstruct

service Employee with serviceClass

**Comment by kuhnroyal** [comment]
Same problem using the sample JDL from the studio. 
Linux 4.2.0-38-generic #45~14.04.1-Ubuntu
Node : v4.4.4
Yo: 1.8.4
Jhipster: 3.4.1

**Comment by lrkwz** [comment]
Happened to me when I got some wrong definitions in the jdl: the importer fails silently.
In my case I got some relationship wrong.
Thy to cut them off until  you isolate the offending lines.

**Comment by kuhnroyal** [comment]
I tried it now with this and it is not working. Straight from the samples.

```
entity Book
entity Author

relationship OneToMany {
  Author{book} to Book{writer(name)}
}
```

**Comment by fw060** [comment]
Same problem here. 

Node : v4.4.4
Yo: 1.8.4
Jhipster: 3.4.1
On Mac.

I got the problem gone ONCE by uninstall jhipster 3.4.1 and reinstall 3.4.0. Unfortunately now no matter how many times I uninstall 3.4.1 and reinstall 3.4.0, the problem still exist.

**Comment by deepu105** [comment]
@fw060 can you install `npm i jhipster-uml -g` and run `jhipster-uml yourJDLFile.jdl` and see if you have same issue?

**Comment by manisi** [comment]
same problem
OS : Mac 10.11.4 EL
Node : 4.4.5
Yo : 1.8.4
jhipster : 3.4.1
jh:


entity Department {
  departmentName String required
  departmentCode String
}

entity Personel {
firstName String required,
lastName String required,
nationalCode String required,
birthDate LocalDate required,
personeliNumber  String required,
maritalStatus Marital required,
phoneNumber String ,
jobStratYear LocalDate required,
compflag Boolean
}

entity PersonelAddress{
areaNumber Integer,
mainStreet String required,
compeleteAddress String,
active Boolean ,
fromDate LocalDate required
}

entity City{
cityCode Integer,
cityName String required,
active Boolean
}

entity Ostan{
ostanCode Integer,
ostanName String required,
active Boolean 
}

entity WorkRelation{
relatedKind RelatedKind  required,
active Boolean ,
fromDate LocalDate required
}

enum RelatedKind{
RASMI, GHARARDADI, SAATI, MOSHAVER,
KANESABZ, TAGHEERVAZIAT, SHERKATI,
KHADAMATI, SAYER
}

entity Education {
eduLevel EduLevel required,
uniType  University required,
uniName String,
fieldOfStudy String required,
dateObtaining LocalDate required,
active Boolean 
}

enum EduLevel{
LISANCE, DIPLOM, FOGHELISANCE, DOCTORA, 
FOGHEDOCTORA, SYCLE, SAYER
}

enum University{
SAYER,NOT
}

enum Marital {
 MARRIED, SINGLE
}

entity OrganPosition {
organPositionTitle String required
organPositionCode String
}

entity Family {
firstName String required,
lastName String required,
nationalCode String required,
birthDate LocalDate required,
familyRelation FamilyRelation required,
educationLevel EduLevel required
}

enum FamilyRelation {
SS,NN
}

entity PersoneliPositional{
title String required,
active Boolean
}

entity ServiceLocation {
startDate LocalDate required,
active Boolean
}

relationship ManyToOne {
  PersonelAddress{personel} to Personel
}

relationship ManyToOne {
  Education{personel} to Personel
}

relationship ManyToOne {
  Family{personel} to Personel
}

relationship ManyToOne {
  WorkRelation{personel} to Personel
}

relationship ManyToOne {
  PersoneliPositional{personel} to Personel
}

relationship ManyToOne {
  ServiceLocation{personel} to Personel
}
relationship ManyToOne {
  ServiceLocation{department} to Department
}
relationship ManyToOne {
  PersoneliPositional{organPosition} to OrganPosition
}
relationship ManyToOne {
  PersonelAddress{city} to City
}
relationship ManyToOne {
  City{ostan} to Ostan
}
relationship OneToOne {
  Personel{user} to User
}

paginate ServiceLocation, PersoneliPositional, Family, 
         Education, WorkRelation, PersonelAddress , City, Ostan, OrganPosition  with infinite-scroll

paginate Personel with pagination
service all with serviceImpl

**Comment by wnbaq** [comment]
I fix it. I uninstall jhipster(3.4.1) and install 3.4.0 and now ıt produce entities.
node: v6.2.1 on windows yo: 1.8.4
Thank you,

**Comment by deepu105** [comment]
thats weird


Thanks & Regards,
Deepu

**Comment by fw060** [comment]
@deepu105 yes I can generate all the files with jhipster-uml without any trouble. Thanks!

**Comment by deepu105** [comment]
This sub generator needs a major revamp based on the latest https://github.com/jhipster/jhipster-domain-language and will be done soon. Till then i'll recommend everyone to use jhipster-uml to import JDL using command jhipster-uml yourFile.jdl

This is tracked in issue #3532 hence closing this

**Comment by Paul-Etienne** [comment]
I have got this exact problem but downgrading to a former version isn't a solution for me.
This issue should stay open and looked into.

**Comment by deepu105** [comment]
@Paul-Etienne this has been fixed long back if you have an issue i suggest you open a new ticket with all required details
