### ISSUE TITLE
Test REST controllers with an autenticated user

### ISSUE THREAD

**Issue by lrkwz** [jhipster/generator-jhipster#3725]
##### **Overview of the issue**

REST controller has no current user in junit test; the context contains only the Anonymous un-authenticated user.

##### **Motivation for or Use Case** 

It should be possible to write **and test** controllers who's behavior depends on the current user data.

##### **JHipster Version(s)** 

3.4.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "testjwt",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "c801dd5d5973063641bf9d8f3514d2ee515b9baf",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": [
      "it"
    ]
  }
}
```
 
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

```
$ cat .jhipster/Receipe.json 
{
    "relationships": [],
    "fields": [
        {
            "fieldName": "rnumber",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160616144530",
    "dto": "no",
    "service": "no",
    "entityTableName": "receipe",
    "pagination": "pagination"
}
```

##### **Reproduce the error** 

Add to all REST controllers log something like 

        log.debug("REST {} auth {} request to save Receipe : {}", SecurityUtils.getCurrentUserLogin(), SecurityUtils.isAuthenticated(), receipe);

The output will be 

     REST anonymous auth false request to save Receipe : ...

I've unsuccessfully  tried to include in pom.xml

        <dependency>
		    <groupId>org.springframework.security</groupId>
		    <artifactId>spring-security-test</artifactId>
		    <scope>test</scope>
	</dependency>

and replaced in ReceipeResourceIntTest setup() method

        this.restReceipeMockMvc = MockMvcBuilders.standaloneSetup(receipeResource)
            .setCustomArgumentResolvers(pageableArgumentResolver)
            .setMessageConverters(jacksonMessageConverter).build();

with 

        this.restReceipeMockMvc = MockMvcBuilders.webAppContextSetup(context).apply(springSecurity()).build();

... any suggestions?

**Comment by lrkwz** [comment]
Same for

        "authenticationType": "oauth2",

**Comment by gmarziou** [comment]
It seems to me that it's done in AccountResourceIntTest

https://github.com/jhipster/jhipster-sample-app/blob/master/src/test/java/io/github/jhipster/sample/web/rest/AccountResourceIntTest.java#L97-L107

**Comment by Vaelyr** [comment]
Spring Security Test dependency also provides convenient annotation `@WithMockUser` to allow security context in tests.

**Comment by jdubois** [comment]
Both solutions from @gmarziou and @Vaelyr looks OK to me, and no comments here for 1 month, so I'm closing this.

**Comment by lrkwz** [comment]
Sorry for being absent for a while.
I've further investigated with no success.

I've changed the logging statement in each EntityResource.java including ```SecurityUtils.getCurrentUserLogin()```

See https://github.com/jhipster/generator-jhipster/compare/master...lrkwz:rest_auhentication

If you run tests the current user login is always 'null' since there is no Authentication object in the current security context.

I've tried to change the tests adding (has in @gmarziou suggestion)

    .with(request -> {
                    request.setRemoteUser("user");
                    return request;
    }) 

with no luck.

My second unfortunate guess (has in @Vaelyr suggestion) has been changing the test setup adding ```.apply(SecurityMockMvcConfigurers.springSecurity(springSecurityFilterChain))``` to the ```StandaloneMockMvcBuilder``` generated by ```MockMvcBuilders.standaloneSetup()``` and ```@WithMockUser```.
Something like this:

    @Autowired
    private FilterChainProxy springSecurityFilterChain;

    @PostConstruct
    public void setup() {
        MockitoAnnotations.initMocks(this);
        UserProfileResource userProfileResource = new UserProfileResource();
        ReflectionTestUtils.setField(userProfileResource, "userProfileService", userProfileService);
        this.restUserProfileMockMvc = MockMvcBuilders.standaloneSetup(userProfileResource)
            .setCustomArgumentResolvers(pageableArgumentResolver)
            .setMessageConverters(jacksonMessageConverter).apply(SecurityMockMvcConfigurers.springSecurity(springSecurityFilterChain)).build();
    }

**Comment by haifzhan** [comment]
@lrkwz any luck?  I encountered the same issue when I use getCurrentUserLogin() in my EntityResource file.  The Unit Test always fail and I don't know how to create a Mock User...

**Comment by perry0105** [comment]
http://docs.spring.io/spring-security/site/docs/current/reference/html/test-method.html

**Comment by mraible** [comment]
My [jhipster4-demo tutorial](https://github.com/mraible/jhipster4-demo/blob/master/README.adoc#deploy-to-the-cloud) shows how to use `WithMockUser` to test something like this:

**Comment by andredebuisne** [comment]
Hi! I just had this issue and I used:
`@WithMockUser(username="user@localhost",authorities={"ROLE_USR"}, password = "user")`
You can place this annotation on a specific test or a class of tests, so that all tests benefit from this MockUser!
Then all my Ressources using `SecurityUtils.getCurrentLogin()` work, the user is found with all of his information.

**Comment by tsblackboy** [comment]
Config full security

**Comment by tsblackboy** [comment]
@RunWith(SpringRunner.class)
@SpringBootTest(classes = ...)
@ContextConfiguration
@WebAppConfiguration
public class UserResourceIntTest {

.....
@Autowired
    FilterChainProxy springSecurityFilterChain;

this.restUserMockMvc = MockMvcBuilders.standaloneSetup(userResource)
            .setCustomArgumentResolvers(pageableArgumentResolver)
            .setControllerAdvice(exceptionTranslator)
            .setMessageConverters(jacksonMessageConverter)
            .apply(SecurityMockMvcConfigurers.springSecurity(springSecurityFilterChain))
            .build();

...
@Test
    @Transactional
    @WithMockUser(username="admin", password = "admin", authorities = {"ROLE_ADMIN"})
    public void createUser() throws Exception {
    	createPaisAndSubchefia();
        int databaseSizeBeforeCreate = userRepository.findAll().size();

        // Create the User
        ManagedUserVM managedUserVM = new ManagedUserVM();
        setDefaultManagedUserVM(managedUserVM);

        restUserMockMvc.perform(post("/api/users")
        	.with(csrf())
        	.with(SecurityMockMvcRequestPostProcessors.securityContext(SecurityContextHolder.getContext()))
            .contentType(TestUtil.APPLICATION_JSON_UTF8)
            .content(TestUtil.convertObjectToJsonBytes(managedUserVM)))
        	.andExpect(status().isCreated());

        // Validate the User in the database
        List<User> userList = userRepository.findAll();
        assertThat(userList).hasSize(databaseSizeBeforeCreate + 1);
        User testUser = userList.get(userList.size() - 1);
        assertThat(testUser.getLogin()).isEqualTo(DEFAULT_LOGIN);
        assertThat(testUser.getFirstName()).isEqualTo(DEFAULT_FIRSTNAME);
        assertThat(testUser.getLastName()).isEqualTo(DEFAULT_LASTNAME);
        assertThat(testUser.getEmail()).isEqualTo(DEFAULT_EMAIL);
        assertThat(testUser.getImageUrl()).isEqualTo(DEFAULT_IMAGEURL);
        assertThat(testUser.getLangKey()).isEqualTo(DEFAULT_LANGKEY);
    }
