### ISSUE TITLE
gradle test: NoCacheRegionFactoryAvailableException when second level cache is disabled

### ISSUE THREAD

**Issue by Jie-Yang** [jhipster/generator-jhipster#3730]
##### **Overview of the issue**

When I use jhipster generate an app, I disabled the second level cache. However, when I run "gradle test" to test the app, the test failed because the "NoCacheRegionFactoryAvailableException". I have checked the application.yml in directory "src/test/resources/config", and the second cache is disabled. I do not know the app is still looking for second-cache. Except the test failure, everything else works well, the app can run successfully. 

##### **JHipster Version(s)** 

"jhipsterVersion": "3.4.0"

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "EMS",
    "packageName": "com.test.ems",
    "packageFolder": "com/test/ems",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "e677704271bdaeafa58f64ffae582fd5ec994282",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}

##### **application.yml in src/test/resources/config** 
`spring:
    application:
        name: EMS
    datasource:
        url: jdbc:h2:mem:EMS;DB_CLOSE_DELAY=-1
        name:
        username:
        password:
    jpa:
        database-platform: com.test.ems.domain.util.FixedH2Dialect
        database: H2
        open-in-view: false
        show_sql: true
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.hbm2ddl.auto: validate
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data
    mail:
        host: localhost
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

liquibase:
    contexts: test

security:
    basic:
        enabled: false

server:
    port: 10344
    address: localhost

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: e677704271bdaeafa58f64ffae582fd5ec994282
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
    swagger:
        title: EMS API
        description: EMS API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
        enabled: false`

##### **Browsers and Operating System** 
Ubuntu 15.04

**Comment by jdubois** [comment]
Reading your .yo-rc.json you did configure a cache when JHipster generated the app, so it generated an Ehcache configuration - so from a JHipster perspective, there was no bug at the generation.
Have a look at the CacheConfiguration file, but there's also Spring Boot that will probably configure automatically the cache. There's more to do than just put the second-level cache to false, as there is still an ehcache configuration -> some people may want to use ehcache for something else than Hibernate 2nd level caching, so the cache is still there.
This isn't truly a bug, as if you selected "no cache" at generation, you have had a working configuration (btw you could also try this, and do a diff with your current code, to see the changes), maybe you could also ask this on StackOverflow?

**Comment by Jie-Yang** [comment]
@jdubois 
Thank you for the reply. After spending days on this, finally I found the problem.
Be default, application.yml file is located in "src/test/resources/config" which can not be found by either "gradle test" nor "run as junit test". After I move the file to "src/test/resources", it works now. 
As I know, by default, springboot will look for yml in "src/test/resources", so I must deleted the config for pointing to the yml file in folder "config" instead of the default folder. If yes, could you tell me where is the configuration?

**Comment by jdubois** [comment]
I'm sorry but I've never had any problem with Gradle or "run as Junit" finding the configuration, I'm doing it all the time. Maybe an IDE misconfiguration?

**Comment by Jie-Yang** [comment]
I also have the same suspicion, but I do not know where we can config it in IDE?

Also based on SpringBoot Spec below, just like you said, there should be any problem to find the yml in config folder. 

> SpringApplication will load properties from application.properties files in the following locations and add them to the Spring Environment:
> 1. A /config subdirectory of the current directory.
> 2. The current directory
> 3. A classpath /config package
> 4. The classpath root
> The list is ordered by precedence (properties defined in locations higher in the list override those defined in lower locations).

**Comment by AmineJa** [comment]
Please help me to solve the problem of updating table database
