### ISSUE TITLE
Gulp Build is not working for Production

### ISSUE THREAD

**Issue by cpoepke** [jhipster/generator-jhipster#3743]
##### **Overview of the issue**

When building the application for production, gulp crashes during the templateCache step, because the templates.js is not found:
[INFO] [18:37:15] Starting 'sass'...
[INFO] [18:37:15] Starting 'html'...
[INFO] [18:37:16] Tested 3 tests, 3 passes, 0 failures: PASS
[ERROR] fs.js:839
[ERROR]   return binding.lstat(pathModule._makeLong(path));
[ERROR]                  ^
[ERROR]
[ERROR] Error: ENOENT: no such file or directory, lstat '/test/src/main/webapp/app/templates.js'
[ERROR]     at Error (native)
[ERROR]     at Object.fs.lstatSync (fs.js:839:18)
[ERROR]     at DestroyableTransform.TransformStream [as _transform] (/Volumes/Projects/Private/liquibase/test/node_modules/gulp-header/index.js:38:12)
[ERROR]     at DestroyableTransform.Transform._read (/Volumes/Projects/Private/liquibase/test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
[ERROR]     at DestroyableTransform.Transform._write (/Volumes/Projects/Private/liquibase/test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
[ERROR]     at doWrite (/Volumes/Projects/Private/liquibase/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
[ERROR]     at writeOrBuffer (/Volumes/Projects/Private/liquibase/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
[ERROR]     at DestroyableTransform.Writable.write (/Volumes/Projects/Private/liquibase/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
[ERROR]     at write (/Volumes/Projects/Private/liquibase/test/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:623:24)
[ERROR]     at flow (/Volumes/Projects/Private/liquibase/test/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:632:7)
[ERROR]     at DestroyableTransform.pipeOnReadable (/Volumes/Projects/Private/liquibase/test/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:664:5)
[ERROR]     at emitNone (events.js:67:13)
[ERROR]     at DestroyableTransform.emit (events.js:166:7)
[ERROR]     at emitReadable_ (/Volumes/Projects/Private/liquibase/test/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:448:10)
[ERROR]     at emitReadable (/Volumes/Projects/Private/liquibase/test/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:444:5)
[ERROR]     at readableAddChunk (/Volumes/Projects/Private/liquibase/test/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:187:9)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.896 s
[INFO] Finished at: 2016-06-19T18:37:16+02:00
[INFO] Final Memory: 53M/1075M
[INFO] ------------------------------------------------------------------------

##### **Motivation for or Use Case** 

The application cannot be build for production.

##### **JHipster Version(s)** 

3.4.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.1",
    "baseName": "myApp",
    "packageName": "com.myApp.app",
    "packageFolder": "com/myApp/app",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de",
      "it",
      "es"
    ]
  }
}

##### **Browsers and Operating System** 

OSX 10.11.5

##### **Reproduce the error** 

Just run:
mvn package -Pprod

**Comment by pascalgrimaud** [comment]
Same issue here : https://github.com/jhipster/generator-jhipster/issues/3732
It's already fixed in the master with https://github.com/jhipster/generator-jhipster/pull/3741

You can fix it by upgrading in your `package.json` :
`"gulp-angular-templatecache": "1.9.0"`
