### ISSUE TITLE
jhipster version upgrade v3.4.1 ->3.4.2  does not working

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [jhipster/generator-jhipster#3745]
Hi, thanks for jhipster, but version upgrade does not make any changes. "npm update -g generator-jhipster" does nothing, the version number is still v3.4.1 and warning me that new version available.

[user@u fld]# npm -g  install generator-jhipster
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/generator-jhipster
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
/usr/lib
└── generator-jhipster@3.4.2 

but 
yo jhipster

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: #commented
 
        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
        ██  ████████     ██     ███████    █████      ██     ██████    ███████
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██

                            http://jhipster.github.io

Welcome to the JHipster Generator v3.4.1
Application files will be generated in folder: /home/v/IdeaProjects
 ______________________________________________________________________________

  JHipster update available: 3.4.2 (current: 3.4.1)
  Run npm install -g generator-jhipster to update.

I run it on latest Arch linux

**Comment by vitaliy-kuzmich** [comment]
hmm the reason was my parrent folder:  `.yo-rc.json` in a parent directory.

**Comment by PierreBesson** [comment]
Your issue is the following:
`Just found a .yo-rc.json in a parent directory.`

Due to the way Yeoman works, it will pick up `.yo-rc.json` files in parent directories and attempt to regenerate the project at the parent dir location. Please run the generator in a folder whose parent directories does not contain a `.yo-rc.json` and tell us if it fixes your problem.

**Comment by vitaliy-kuzmich** [comment]
it fixes... thanks.
