### ISSUE TITLE
Document the use of Docker for Mac and Windows

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3752]
Now that Docker for Mac and Windows are out of "private beta", we should update all documentation for this, and this is probably going to simplify some pages, so that's really good.

**Warning** , when running the Maven "docker:build" command, there is one trick to document, the use (at least on Mac) of:

    export DOCKER_HOST=unix:///var/run/docker.sock

To solve the problem at https://github.com/spotify/docker-maven-plugin/issues/218

**Comment by PierreBesson** [comment]
I'm not sure if we should remove the docs about docker-machine use. Especially on Windows were Docker for Windows is only available for "Professional" editions. Also Docker for Mac is still in beta.

**Comment by pascalgrimaud** [comment]
And with Windows7, we have to use docker-machine, right?

**Comment by deepu105** [comment]
may be lets keep both docs as its always better to have more docs :)


Thanks & Regards,
Deepu

**Comment by SgElite** [comment]
Hi, Julien

Dont know if this is the best place to ask this question, currently my setup is as shown below

1. Windows 10
2. Oracle VM VirtualBox - v5.0.20 r106931
3. Docker Toolbox
4. node --version v5.9.0
5. jhipster v3.4.2

Problem/Issue
I have already started jipster registry, but I cannot select Microservice application or gateway 
after running "yo jhipster"

I have create a couple of application using v3.4.0 (also does not have Microservices application option). How do I enable v3.4.2 with Microservices application option ? 

Regards
James

**Comment by PierreBesson** [comment]
@SgElite You probably have a .yo-rc.json in the parent directory. So yeoman take this one and won't prompt you for questions.
Please don't ask for help in the issue tracker. Use Stackoverflow or Gitter.

**Comment by SgElite** [comment]
@PierreBesson

Thanks for the tip, will try that... had problem posting to Stackoverflow, cant find the link in Stackoverflow to raise a question. 

Regards
James

**Comment by jdubois** [comment]
@SgElite I'm not even reading, please open up another ticket if you have a specific issue

Now back to the discussion: It might be a bit early to migrate, OK, so I'm closing this.

**Comment by EvgenyKislyy** [comment]
And what is the value for DOCKER_HOST for windows 10?
