### ISSUE TITLE
Excluding bower_components causes angular support not to work in IntelliJ

### ISSUE THREAD

**Issue by jmayday** [jhipster/generator-jhipster#3753]
Hi, 

I've started using jhipster and IntelliJ at the same time thus I was struggling with problem for some time. The problem is related to IntelliJ Angular support. I didn't get Angular directives being proposed while typing (`<div ng-...`. IntelliJ was suggesting only some cloak related directives like `ng-cloak`, nothing else). 

The problem seems to be caused by excluded `bower_components` directory. This was suggested in documentation: [Configuring Intellij IDEA](https://jhipster.github.io/configuring-ide-idea/).

After cancelling exclusion I have all Angular directives being proposed when typing. 

Could you please clarify what is the reason for excluding directories under IntelliJ? Is it possible that excluding `node_modules` will also cause some IntelliJ functionality not to work correctly?

Thx

**Comment by deepu105** [comment]
You can choose not to exclude `bower_components` and it wont be an issue.
we suggest the exclusions to reduce the time IntelliJ spends on indexing.
You can still exclude node_modules as you would use it only for gulp and I
dont think you will need much code assist there.


Thanks & Regards,
Deepu

**Comment by jmayday** [comment]
Thanks for quick answer. Maybe it's worth mentioning how will it affect IntelliJ behaviour on that page? ([Configuring Intellij IDEA](https://jhipster.github.io/configuring-ide-idea/)).

**Comment by deepu105** [comment]
would you like to do a PR to the documents site?


Thanks & Regards,
Deepu

**Comment by jmayday** [comment]
https://github.com/jhipster/jhipster.github.io/pull/282
