### ISSUE TITLE
Sub generator upgrade: issue with upgrading projects generated prior JHipster 3.4.0

### ISSUE THREAD

**Issue by Invizible** [jhipster/generator-jhipster#3761]
##### **Overview of the issue**

Upgrade sub generator does not work correctly if project is generated with jhipster prior version 3.4.0.
I have a project generated with version 3.0.0. So when I wanted to upgrade it, I updated jhipster

`npm i -g generator-jhipster`

So that upgrade sub generator became available and when I ran it , sub generator created a new branch 'jhipster_upgrade', checked out on this new branch and ran 
`jo jhipster --with-entities`

BUT, since we don't have jhipster installed locally (folder is empty when sub generator checks out on the upgrade branch), yeoman uses global jhipster (3.4.2 for example) and generates project not with 3.0.0 but with current version 3.4.2, for example. Then it upgrades jhipster and generates project again but still with the same version 3.4.2 (because it is the latest). It this situation we don't have a difference between 2 upgrade commits, and there is nothing to merge master branch with. So upgrade does not happen.

##### **Motivation for or Use Case** 

Upgrade sub generator should also work for projects generated with version >=3.0.0

##### **JHipster Version(s)** 

3.0.0.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "app",
    "packageName": "com.app",
    "packageFolder": "com/app",
    "serverPort": "8090",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "rememberMeKey": "60205dc06b687c6b6afd12dda7cc87dc26c08a39",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ru"
    ]
  }
}
```

##### **Browsers and Operating System** 

Windows 10

##### **Reproduce the error** 

1. generate project with jhipster version prior to 3.4.2 (3.0.0, for example)
2. update jhipster version: `npm i -g generator-jhipster`
3. run: `yo jhipster:upgrade`
4. look at logs or commit 'Generated with JHipster 3.0.0' and look at version of jhipster. You will see 3.4.2. instead of 3.0.0

##### **Related issues** 

#3696 

##### **Suggest a Fix** 

I suggest installing locally jhipster with version from yo-rc.json file right after switching to the jhipster_upgrade branch, before generating the app. So correct jhipster version will be used for generation. And then when sub generator upgrades jhipster globally it should also do it locally, so correct version will be used this time as well.
If you don't mind I would like to take this issue and will submit a pull request

**Comment by jdubois** [comment]
The upgrade sub-generator was released with JHipster 3.4.0 - it was never meant to work with older versions, and probably won't.

**Comment by Invizible** [comment]
@jdubois yes, you are right, but per https://github.com/jhipster/generator-jhipster/issues/3696#issuecomment-227824214 comment it can be used with older versions, I mean 3.0.0+ but <3.4.0

**Comment by jdubois** [comment]
Oh I didn't know that, pinging @lordlothar99 about it...
Anyway, does it really make sense to work on older versions for this? They just don't have the feature yet

**Comment by Invizible** [comment]
@jdubois But still there is another related issue, if we have several jhipster projects, generated with different version, 3.4.0, 3.4.1, 3.4.2, and you run jhipster:upgrade, jhipster version installed globally will be used (3.4.2, for example) and 3.4.0, 3.4.1 will not be updated because of the issue which I explained in description.

**Comment by lordlothar99** [comment]
thx @Invizible for creating the issue we talked about ; feel free to propose a PR, let us know if you need help !

**Comment by Invizible** [comment]
@lordlothar99 , please take a look at my PR: https://github.com/jhipster/generator-jhipster/pull/3770

**Comment by deepu105** [comment]
Im not sure if this is something that JHipster should handle. If you want to upgrade an older project you should first init a git repo commit your current code and then invoke the upgrade process. The project should already have a jhipster version in its node modules folder and it will be used when you run yo jhipster in that folder any time.

So for older versions if you want to use the upgrade sub gen then:
1. `git init` and commit current code
2. Do `npm install generator-jhipster` it will update the local instance and not the global
3. Run the upgrade sub generator which will now upgrade the project to new version

I would prefer this to be documented rather than doing work around in code to support older versions

**Comment by Invizible** [comment]
@deepu105  your steps won't work, because when you run upgrade,  sub generator clears the folder, it keeps only .git folder and yo-rc.json. Then it runs hipster. At this point you don't have local node_modules folder, and global hipster will be used

**Comment by lordlothar99** [comment]
hi @deepu105 ! you are right, upgrade process would be slower due `npm install` runs... but at the same time, I know some developpers are expecting jhipster to be able to upgrade their old projects !!
Here's what I propose :
1. as described on https://github.com/npm/npm/issues/11283, people could use `npm set progress=false` to speed that up ; we could either include this command in the generator (event though that's not our responsibility ...), or put a recommendation in the documentation
2. @Invizible proposal seems fine to me ; although I think we could spare time installing locally during normal upgrade process, while installing locally only if necessary, during `jhipster_upgrade` branch preparation, so no time would be wasted unecessarily !  (we need to test global version vs local version, and refactor a little the code so `_installJhipsterLocally` would be invocated in `prepareUpgradeBranch` only  )
:sunglasses: 
what do u think guys ?

**Comment by Invizible** [comment]
@lordlothar99 , I agree I can move _installJhipsterLocally to the  prepareUpgradeBranch task

**Comment by deepu105** [comment]
@Invizible the process of generating the app to get the initial state was a work around to handle case were git repo was not present to avoid code loss. But if you know what you are doing you can very well create a git repo, commit your code and then update the local jhipster and then run the upgrader, it would ofcourse use the global jhipster which would be the latest and that was the point I still dont see why it wouldnt work. Am I missing something.

I'm ok to have this if its optional for people who want to use an older local version, otherwise this shouldn't be done. may be you can have a command line flag to enable this behavior as I don't want everyone to wait for 2 npm install which will take a long time.

**Comment by Invizible** [comment]
@deepu105 take a look at my commit https://github.com/Invizible/generator-jhipster/commit/661d1f0a2e3b9b741a0e0dce12d2fc91f0c177bb
Now it installs jhipster locally only when jhipster_upgrade branch is being created, so it will happen only once.

**Comment by lordlothar99** [comment]
@Invizible seems perfect to me ! one single little comment : plz take some time to read https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-git-commit-guidelines
:)

**Comment by dnitzan** [comment]
I have a jhipster 3.0.0 project on Windows 7. I installed latest jhipster generator globally (3.8.0), but the project is still generated with the newest generator 3.8.0 after creating the jhipster_upgrade branch and not with the 3.0.0 generator. Any ideas?

**Comment by dnitzan** [comment]
Disregard- I removed the global jhipster generator, installed a local generator (3.8.0) and it works perfectly.

**Comment by cbornet** [comment]
BTW, it doesn't work with JHipster 2.x because --with-entities was not available. 
Going manual...

**Comment by cbornet** [comment]
In case some one wants to upgrade from v2.x, here is the script I used
```shell
#!/bin/sh

#If you don't use git already
git init
git add -A
git commit -am "Initial" --allow-empty


# Create jhipster_upgrade branch
git checkout --orphan jhipster_upgrade

#Cleanup
rm -rf !(.yo-rc.json|.git|.jhipster)

#Install jhipster current version locally
npm install generator-jhipster@2.27.0

# Generate app and entities (pre v3 fashioned)
yo jhipster --force
for f in `ls .jhipster`; do yo jhipster:entity ${f%.*} --force ; done

# Commit to jhipster_upgrade
git add -A
git commit -am "Generated with Jhipster 2.27.0" --allow-empty

# Record code generated with old version
git checkout master
git merge --strategy=ours --no-edit jhipster_upgrade

# Generate app and entities (v3 fashioned)
sudo npm install -g generator-jhipster@3.8.0
git checkout jhipster_upgrade
rm -rf !(.yo-rc.json|.git|.jhipster)
yo jhipster --with-entities --force

# Commit to jhipster_upgrade
git add -A
git commit -am "Generated with Jhipster 3.8.0" --allow-empty

# Merge old version to new version changes into master
git checkout master
git merge jhipster_upgrade
```
Then resolve the conflicts and commit.
It worked pretty well for me because I did it on an app on which there was little front-end modifications. For apps that have modified the front-end a lot, I think it will be harder because the whole webapp structure has changed.
Note: this script doesn't do all the checks that are done by jhipster:upgrade. Use at your own risk and preferably understand what it does before.
