### ISSUE TITLE
Too many hibernate dependencies

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#3768]
##### **Overview of the issue**

It looks like when using ``mongo`` some ``hibernate`` dependencies are still added to ``build.gradle`` and ``pom.xml`` 

##### **Motivation for or Use Case** 

Nothing seems broken, but I think that is not correct. I have removed all hibernate dependencies from ``build.gradle`` and everything worked fine.

##### **JHipster Version(s)** 

All

##### **Reproduce the error** 

Create an app and select ``mongodb`` as database/

##### **Suggest a Fix** 

Move the ``sql`` check somewhere else. 

```xml
        <%_ } _%>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-envers</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
        <%_ if (databaseType === 'sql') { _%>
```

**Comment by jdubois** [comment]
- for Envers I'm not sure, as we also have auditing on MongoDB -> I would be surprised there is some common code, but this should be checked before
- for Hibernate Validator I'm pretty sure we need it for Bean Validation

**Comment by atomfrede** [comment]
I also thought so, but I removed all hibernate dependencies from my build file, created an entity vial min and not null validation and everything works fine. I think the ``javax.validation`` is provided by spring validation. Will setup another sample with more validations to check what happens.

**Comment by jdubois** [comment]
I thought Hibernate Validation was providing the implementations for those checks, but I've never looked at it in detail.... It should also add some extra, non-standard annotations: we need to check if people want to have them, or use them

**Comment by atomfrede** [comment]
I've create a sample with some validations on different types of fields and remove all explicit hibernate dependencies from pom.xml. Everything works fine. Modifing the request results in bad request with fine validation error message, so at least for the validations offered by the generator there should be no issue removing hibernate.

Here is the repository:
https://github.com/atomfrede/jhipster-mongo-validation-sample

**Comment by jdubois** [comment]
Great!!! Maybe we should also remove it for SQL and Cassandra ?

**Comment by atomfrede** [comment]
Do we have some tests with validations? I'll create a PR.
