### ISSUE TITLE
sortpom-maven-plugin - sorting of dependencies and plugins

### ISSUE THREAD

**Issue by tomvanrossom** [jhipster/generator-jhipster#3780]
##### **Overview of the issue**

In the [template of the pom.xml](https://github.com/jhipster/generator-jhipster/blob/a4a05caddf6bba72df7f9a17c360cb3f62fe062d/generators/server/templates/_pom.xml), the [sortpom maven plugin](https://github.com/Ekryd/sortpom/wiki) is configured to sort different things during the verify phase, including dependencies and plugins:

```   
<configuration>
     <sortProperties>true</sortProperties>
     <nrOfIndentSpace>4</nrOfIndentSpace>
     <sortDependencies>groupId,artifactId</sortDependencies>
     <sortPlugins>groupId,artifactId</sortPlugins>
     <keepBlankLines>true</keepBlankLines>
     <expandEmptyElements>false</expandEmptyElements>
</configuration>
```

Because sorting dependencies and plugins is considered ['dangerous'](https://github.com/Ekryd/sortpom/wiki/Parameters-that-can-affect-your-build), I wonder if this is the wanted behavior.

##### **Motivation for or Use Case** 

During normal development, the pom is not sorted, but I ran into some problems when trying to upload my war-file to a nexus repository. Suddenly, my gateway, had some ClassNotFoundException, because of the sorted pom.

##### **JHipster Version(s)** 

3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "broncholab",
    "packageName": "com.fluidda.broncholab",
    "packageFolder": "com/fluidda/broncholab",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "***",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "nl",
      "fr"
    ],
    "enableSocialSignIn": false
  }
}

##### **Reproduce the error** 

```
mvn verify
```

##### **Suggest a Fix** 

Is disabling the sorting of dependencies and plugins not safer/better?
Should sorting of the pom be enabled during compilation fase?

```   
<plugin>
    <groupId>com.github.ekryd.sortpom</groupId>
    <artifactId>sortpom-maven-plugin</artifactId>
    <version>${sortpom-maven-plugin.version}</version>
    <executions>
        <execution>
            <phase>compile</phase>
            <goals>
                <goal>sort</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <sortProperties>true</sortProperties>
        <nrOfIndentSpace>4</nrOfIndentSpace>
        <sortDependencies>none</sortDependencies>
        <sortPlugins>none</sortPlugins>
        <keepBlankLines>true</keepBlankLines>
        <expandEmptyElements>false</expandEmptyElements>
    </configuration>
</plugin>
```

**Comment by jdubois** [comment]
Yes that's the expected behavior, as it's easier to find the dependencies when they are sorted.

Then, I totally understand the issues this could cause and I'm not using this myself.

I've tested `mvn verify` with your `.yo-rc.json` file, and it fails because you have "***" as your secret key. If you replace it with a "normal" key, it's working.

So, at least with the current `master` branch, I can't reproduce the error. As this works for me, and as there is a good reason to do it, let's keep it this way.

**Comment by Jonas3ap** [comment]
When I added som dependencies for jasper reporting, I also added a comment. Everything got re-ordered also my comment was not anymore in the right context. Sorting in this case was not so good.
