### ISSUE TITLE
Incorrect Bash Script in Regenerating All Entities

### ISSUE THREAD

**Issue by mzack5020** [jhipster/generator-jhipster#3782]
Error located here : https://jhipster.github.io/creating-an-entity/

The Windows Script on jhipster.github.io is incorrect and will error due to the file extension being included in the parameters (for %f in (.jhipster/*) do yo jhipster:entity %f --force). The %f will result in entityName.json which when run against yo jhipster:entity will error due to special characters (.json) being in the entity name. 

Will error out and will not regenerate any entities.

JHipster Version: 1.8.3

Windows 7 , Chrome

Not sure about the Linux shell command but in Windows it will not work

<strong>Recreate the Issue:</strong>
Run the command listed on the JHipster page : for %f in (.jhipster/*) do yo jhipster:entity %f --force on a brand new yo jhipster project (Configuration is irrelevant for this issue)

<strong>Proposed Solution:</strong>
Use command for %f in (.jhipster/*) do yo jhipster:entity %~nf --force instead.
This will only use the file name and will remove the extension so the yo jhipster:entity generator can run properly.

<strong>References</strong>
Use this stackoverflow post as a reference for the solution
http://stackoverflow.com/questions/11377538/batch-how-to-make-a-txt-file-with-all-files-in-a-folder-without-extensions

**Comment by jdubois** [comment]
The tip isn't correct anymore: you can now run `yo jhipster --with-entities --force` that will do the same thing.
So the tip should be removed in the documentation.

**Comment by deepu105** [comment]
Also the tip is for 2.x + version of jhipster. You seem to be on a very old
version. Newer Jhipster version will ignore the .json extension

**Comment by gmarziou** [comment]
> JHipster Version: 1.8.3

It rather looks like Yeoman's version.

**Comment by mzack5020** [comment]
@gmarziou yes, you are right. I wrote yo jhipster --version to check which was incorrect. I'm unsure which version it was since I just updated before reading this. Seems like it has been resolved so irrelevant now.
