### ISSUE TITLE
why the error in the controller.js?

### ISSUE THREAD

**Issue by robotwater** [jhipster/generator-jhipster#379]
Hi All,

something is awkward with my \src\main\webapp\scripts\foo controller.js . can anyone tell me the error?? i have been searching for the whole day..
thanks and much appreciate.

the error come out with this
"The left-hand side of an assignment must be a variable"

![image](https://cloud.githubusercontent.com/assets/6916779/3310715/c0657286-f6b9-11e3-8271-da3db737e728.png)

**Comment by ChrisMaher** [comment]
Seems to be a whitespace for me before ''Sessions' I deleted the space and retyped.

Some problem with Word Wrapping.
