### ISSUE TITLE
Import JDL

### ISSUE THREAD

**Issue by juceliohv** [jhipster/generator-jhipster#3792]
##### **Overview of the issue**

When i generate a model in jdl studio and try import this through 'yo jhipster:import-jdl myFile.jh', nothing happens. It not generate the entities in the project.

It is happen too when i try with the default model of jdl-studio.

Excuse me for my bad english.

##### **Motivation for or Use Case** 

Because this feature should work!

##### **JHipster Version(s)** 

3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "gtsserver",
    "packageName": "br.inf.gati.gts",
    "packageFolder": "br/inf/gati/gts",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "897c17a8e2a383749c7ebd1623594f3f57cebc2d",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br",
      "en",
      "de"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

jh ---

entity Region {
	regionId Long,
	regionName String
}

entity Country {
	countryId Long,
	countryName String
}

entity Location {
	locationId Long,
	streetAddress String,
	postalCode String,
	city String,
	stateProvince String
}

entity Department {
	departmentId Long,
	departmentName String required
}

entity Task {
	taskId Long,
	title String,
	description String
}

/**
 * The Employee entity.
 */
entity Employee {
	employeeId Long,
	/**
	* The firstname attribute.
	*/
	firstName String,
	lastName String,
	email String,
	phoneNumber String,
	hireDate ZonedDateTime,
	salary Long,
	commissionPct Long
}

entity Job {
	jobId Long,
	jobTitle String,
	minSalary Long,
	maxSalary Long
}

entity JobHistory {
	startDate ZonedDateTime,
	endDate ZonedDateTime,
	language Language
}

enum Language {
    FRENCH, ENGLISH, SPANISH
}

relationship OneToOne {
	Country{region} to Region
}

relationship OneToOne {
	Location{country} to Country
}

relationship OneToOne {
	Department{location} to Location
}

relationship ManyToMany {
	Job{task(title)} to Task{job}
}

relationship OneToMany {
	Employee{job} to Job
}

relationship OneToMany {
	/**
	* A relationship
	*/
	Department{employee} to
	/**
	* Another side of the same relationship
	*/
	Employee
}

relationship ManyToOne {
	Employee{manager} to Employee
}

relationship OneToOne {
	JobHistory{job} to Job
}

relationship OneToOne {
	JobHistory{department} to Department
}

relationship OneToOne {
	JobHistory{employee} to Employee
}

paginate JobHistory, Employee with infinite-scroll
paginate Job with pagination

dto Employee with mapstruct

service Employee with serviceClass

	

##### **Browsers and Operating System** 

SO - windows 10 Pro x64
Browser - Google Chrome Version 51.0.2704.103 m

##### **Reproduce the error** 

yo jhipster
yo jhipster:import-jdl myfile.jh

##### **Related issues** 

I see an question in StackOverFlow, but no answers.

##### **Suggest a Fix** 

It shoud work in this version!

**Comment by jdubois** [comment]
- Do you have any error message?
- What version of NodeJS are you using?

**Comment by juceliohv** [comment]
No error messages.
The version of node is 4.4.7 LTS

**Comment by juceliohv** [comment]
I back generator-jhipster to version 3.4.0 and it works!

**Comment by juceliohv** [comment]
Tank you @jdubois  for your help!

@wmarques, there are any feedback about the problem with 3.4.2 version?

Best Regards.
