### ISSUE TITLE
make components, working with feign, testable

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#3797]
This is an issue I fix later this week on my own.

refering to my outstanding pull request #3662 there comes a need to write accurate tests for usage of feign clients.

the greatest pain is to make one test working, without any eureka and oauth server. So there are several mocking techniques needed, to build a full blown test to both feign clients and mocking OAuth2 authentications during a test.

This comes like always with some issues, I figured out how to solve the past days by speaking to several people, coding my fingers wound and so on...

just need the time to extract a elegant solution to integrate in JHipster

**Comment by PierreBesson** [comment]
Would Spring RestServer mocks work for you ([MockRestServiceServer docs](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/web/client/MockRestServiceServer.html))?
We are using that in our project and it works well. There are actually improvement coming to it in Spring 4.3 (in SB 1.4).

**Comment by xetys** [comment]
actually you can use the fall back implementation of feign to mock foreign objects in tests....which worked good for me, until I reached the point where I need to the the injection of ```Principal``` in a controller.

I have now made a fix inside several JHipster apps, where test method can be annoted with ```@WithMockOAuth2Authentication``` where you can pass username, scopes and roles, to test OAuth2Security in it's detail

**Comment by xetys** [comment]
P.S.: my aim is, to make a whole service testable without any outside tools. This is because we are using gitlab at work, and docker composing is a hard task in gitlab CI runner....since I am the lead developer AND devops of my team....I just cant spent another weeks for more gitlab ci madness (already so many months)

**Comment by PierreBesson** [comment]
This seems to be nicer to use than what I do...

**Comment by deepu105** [comment]
@xetys can this issue be closed?

**Comment by xetys** [comment]
For me, this is closed when #3662 is closed. In that PR `@EnableFeignClients` is provided in a separate configuration class, which is disabled when profile test is active. If there is a bean candidate in test folder for a feign client interface, as explained in my testing guide in the docs, the clients can be stubbed and used for test

**Comment by deepu105** [comment]
@xetys next time add the `fix #isuseNo` in PR so this is autoclosed

**Comment by xetys** [comment]
As I said, it's not completely closed to be since #3662 is still pending, but it's almost done, so it's OK
