### ISSUE TITLE
No errors from import-jdl

### ISSUE THREAD

**Issue by chrislovecnm** [jhipster/generator-jhipster#3798]
trying to run `yo jhipster:import-jdl ./jhipster-jdl.jh` for a microservice.  It runs and does nothing :(  No errors either.  I have noticed that import-jdl does not output any error messages.  

jhipster version:  v3.4.2

jdl file

```console
$ cat jhipster-jdl.jh
entity Task {
	taskId Long,
	title String,
	description String
}

microservice Task with javaexample
```

**Comment by imod** [comment]
same issue, but with application type `monolith` (jhipster v3.4.2)

```
>$ yo jhipster:import-jdl jhipster-jdl.jh 
The jdl is being imported.
>$
```

npm: 3.6.0
bower: 1.7.9
node: v4.2.1
yo: 1.8.4

**Comment by jdubois** [comment]
Is this a duplicate form #3532 ?

The "import-jdl" looks really broken - I'm using JHipster UML directly, maybe this works better? This looks like a major issue @MathieuAA @deepu105 what do you think?

**Comment by MathieuAA** [comment]
JHipster UML works when dealing with JDL, *for now*. The subgen will work as soon as the work in JHipster Core is done. That being said, is there a way to disable the subgen, and re-enabling it when JHipster Core is good to go? It's becoming more and more the source of a lot of issues...

**Comment by deepu105** [comment]
I would rather prefer to finish the jhipster-core and release it as its
almost done. As soon as its released I can push a fix for the sub gen. It
might not be elegant to disable and enable


Thanks & Regards,
Deepu

On Mon, Jul 4, 2016 at 5:54 PM, Mathieu ABOU-AICHI <notifications@github.com

**Comment by jdubois** [comment]
Could we at least update the documentation on the website, so that people have some warnings?

**Comment by jdubois** [comment]
I haven't realized how serious this issue is - sorry!!

@MathieuAA and @deepu105 

- Is "jhipster-uml" working fine? Could we switch all the documentation to use JHipster UML directly instead? That would be a quick and easy fix
- I can easily do a release tomorrow, so if we need to "switch off" the import-jdl sub-generator we need to do it now. The issue is, I'm going on holidays after this, and I'm not going to bring my laptop, so this needs to be done ASAP

**Comment by MathieuAA** [comment]
I'm currently changing the way the subgen uses JHipster UML so that it invokes it directly, just like JHipster UML uses the entity generator directly. I think you can update the doc in the meantime, yes... I don't know how long it's gonna take me to make it work, but I'm close.

**Comment by jdubois** [comment]
OK I'll wait until tomorrow -> but if I change the doc to tell people to use "jhipster-uml" directly, it will solve their problem? That's what I'm using all the time, and I never had such an issue

**Comment by MathieuAA** [comment]
Then let's. If I see an error from the old v1.6.5, I'll make a quick v1.6.6 to fix anything showing up.

**Comment by jdubois** [comment]
I'm not sure I understand you -> you mean I update the doc to point to `jhipster-uml` everywhere?

**Comment by MathieuAA** [comment]
Yes, but if an error is noticed by someone I'll be able to release a quick fix for JHipster UML.
