### ISSUE TITLE
Evaluate Swagger

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#38]
https://developers.helloreverb.com/swagger/

PROs:
- Documenting the APIs is important
- Really cool looking

CONs:
- Seems to require quite a number of new libraries, and we want JHipster to remain lean, and low in memory usage

**Comment by mteodori** [comment]
I am using the maven swagger plugin to avoid the inclusion of the scala runtime generating the docs at build time, would it be worth to do it in jhipster also?

**Comment by jdubois** [comment]
@mteodori if we could get rid of Swagger inside JHipster, I would be really happy. This is really a big performance hit.
