### ISSUE TITLE
Syntax error in import BigDecimal statement of EntityResourceIntTest

### ISSUE THREAD

**Issue by HemanthD** [jhipster/generator-jhipster#3800]
##### **Overview of the issue**

The generated EntityResourceIntTest.java contains a syntax error when the entity includes a BigDecimal attribute.

##### **Motivation for or Use Case** 

Entities created with decimal datatype should have the basic tests run successfully out of the box.

##### **JHipster Version(s)** 

3.3.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

[.yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/345872/default.yo-rc.json.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

[TempEntity.json.txt](https://github.com/jhipster/generator-jhipster/files/345875/TempEntity.json.txt)

##### **Browsers and Operating System** 

Chrome on Win 8.1 with MySQL 5.7

##### **Reproduce the error** 

Create an entity with a decimal attribute
Check the generated EntityResourceIntTest.java - it would have a syntax error in the import statement related to BigDecimal

```
import javax.annotation.PostConstruct;
import javax.inject.Inject;
import java.math.BigDecimal;;
import java.util.List;
```

##### **Related issues** 

Did not find any similar cases.

##### **Suggest a Fix** 

The issue could be with the below piece of code
```
<% if (fieldsContainBigDecimal == true) { %>
import java.math.BigDecimal;;<% } %>
```

in **generator-jhipster/generators/entity/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java** which has an extra unwanted ';'

**Comment by deepu105** [comment]
Do you want to do a PR to fix this?


Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
I dont see any issue here. How can ';;' be a syntax error ?
Anyway, this additional ';' should be removed to have a cleaner code :)

**Comment by HemanthD** [comment]
Sure. I will try to submit a PR by early next week.
