### ISSUE TITLE
Error when create Jhipter project:  inject:test

### ISSUE THREAD

**Issue by ThanhLD24** [jhipster/generator-jhipster#3802]
##### **Overview of the issue**

I create new project Jhipster, and get a bug:

![image](https://cloud.githubusercontent.com/assets/15336708/16572585/4d00afc6-4294-11e6-839a-539df823da04.png)

##### **Motivation for or Use Case** 

Before, I create Jhipster project normal, but today I get this bug.

##### **JHipster Version(s)** 

I'm using the latest version of JHipster, furthermore here is my setup:
java 1.8
npm: 3.9.0
node: v4.4.4
yo: 1.8.4
bower: 1.7.9
gulp: 3.9.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "testjhipster",
    "packageName": "jhipster.test",
    "packageFolder": "jhipster/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "5f0c6716be12c9b1f532a2c45c2d399ec05aa53e",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

I haven't create
##### **Browsers and Operating System** 

Window 7 Ultimate - 64 bit

##### **Reproduce the error** 

I create project same as the project I created before.

Sorry for my English.
Thanks for any help!

**Comment by sendilkumarn** [comment]
`git is not installed or not in the path ` 

Can you check that?

**Comment by ThanhLD24** [comment]
Yes, It is error, I solved it by adding git to environment variables in system. Thank you so much!
