### ISSUE TITLE
Upgrade to Spring Boot 1.4.0

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#3803]
~~https://spring.io/blog/2016/07/04/spring-boot-1-3-6-available-now~~

__EDIT__:
https://spring.io/blog/2016/07/05/spring-boot-1-4-0-rc1-available-now

**Comment by pascalgrimaud** [comment]
Oh already done, didn't see it!

**Comment by cbornet** [comment]
And 1.4.0 RC1 is out so we can begin to check what will need to be done to upgrade.

**Comment by PierreBesson** [comment]
@cbornet I have already did some tests using the 1.4 snapshot version and it worked out of the box.
There are very interesting testing improvements. https://spring.io/blog/2016/04/15/testing-improvements-in-spring-boot-1-4
So we should change some annotations on integration tests to use the new @SpringBootTest.
There is also the improvement from Spring 4.3 where you don't need to add @Autowired anymore for constructor injection: https://spring.io/blog/2016/03/04/core-container-refinements-in-spring-framework-4-3

**Comment by deepu105** [comment]
1.4.0 RC1 also has this fix https://github.com/spring-projects/spring-boot/issues/5998#issuecomment-230573445 so we might be able to remove the workaround done for default profile setting cc @erikkemperman

**Comment by erikkemperman** [comment]
@deepu105 That would be great.  The workaround, even in the improved version, always felt a little... dirty to me :-)

**Comment by pascalgrimaud** [comment]
I reopen this ticket, and update my initial comment for spring boot 1.4.0

**Comment by cm325** [comment]
The GA release is out - https://spring.io/blog/2016/07/28/spring-boot-1-4-released

**Comment by jdubois** [comment]
Closing this as the PR is merged!

**Comment by jdubois** [comment]
@pascalgrimaud @mraible we have a couple of deprecations with Spring Boot 1.4, for `SpringBootServletInitializer` and `ServletContextInitializer` can you have a look at it?

**Comment by mraible** [comment]
@jdubois Looking now...
