### ISSUE TITLE
Do I need to first run gulp build then gulp serve?

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#3804]
##### **Overview of the issue**

I am working on the Gateway's UI and I realize that gulp serve (or using default task) is not actually working with the watch task. 

Any change I do on my code is not reflected on the running version. Also, if I didn't run the gulp build before, gulp serve (or default task) has nothing to serve.

##### **JHipster Version(s)** 

JHipster 3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "gateway",
    "packageName": "com.myexample.gateway",
    "packageFolder": "com/myexample/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "adfafdafasdfasdfasdfasdfasdf",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "pt-br"
    ],
    "enableSocialSignIn": false
  }
}

##### **Browsers and Operating System** 

OSX El Capitan, 10.11.5
Chrome Version 51.0.2704.103 (64-bit)

##### **Reproduce the error** 
1. run gulp clean, then gulp you should see nothing on the browser
2. run gulp, then change your code and nothing you change on the running version on the browser

##### **Related issues** 

I think something very old on version 2.X perhaps.

**Comment by marcelinobadin** [comment]
MY BAD!

I was running the gateway with prod profile. One entire day lost because of that. Sorry. The issue can be closed

**Comment by jdubois** [comment]
Next time have a look at the banner on the top left corner :-)

**Comment by marcelinobadin** [comment]
There was no banner... So I just didn't realize! heheehehehe ;-)
