### ISSUE TITLE
Send full elasticsearch queries to server instead of just the user's query string

### ISSUE THREAD

**Issue by geraldhumphries** [jhipster/generator-jhipster#3805]
##### **Overview of the issue**

Right now the Elasticsearch support works by sending the user's query to the server, then letting the server turn that into a QueryStringQuery. This works fine for simple searches and gives the user some control over more advanced searches, but makes it very difficult for the developer.

For example, if I wanted to change `default_operator` to `AND` for a specific query I need to insert `+` or `AND` before each search term. The proper way to do this is to set `default_operator` on the ES query itself, but with the current solution that would need to be done server-side then can't be applied on a per-query basis. 

If we instead change it so the client app sends a full ES query to the server, it becomes much easier for the developer to fine-tune individual queries.

##### **Motivation for or Use Case** 

A common scenario is searching on a specific field. This can be done with queryStringQuery alone:
```
'lastName:test'
```

What if we need to search on more than one field?
```
'lastName:test firstName:test'
```

What if the user searches by more than one word?
```
'lastName:test1 lastName:test2 firstName:test1 firstName:test2'
```

All search terms need to match, but can match either field?
```
'(lastName:test1 AND firstName:test2) OR (lastName:test2 AND firstName:test1) OR (lastName:test1 AND lastName:test2) ... '
```

QueryStringQuery is powerful but can quickly become too complex to maintain. The other downside is that if the user types reserved characters or otherwise causes a syntax error, the server will return an error. Because of this user queries are generally SimpleQueryStringQuery but then you can't use any advanced search functions like searching by field!

##### **Suggest a Fix** 

Instead of sending the user's query to the client app then using it as a QueryStringQuery directly, we can send a full ES query then use it as a WrapperQuery. This gives developers a LOT more control over ES queries and avoids errors. Ex:
```
EntitySearch.query({
                query: {
                    simple_query_string: {
                        query: $scope.currentSearch,
                        fields: ['firstName', 'lastName'],
                        default_operator: 'AND'
                    }
                },
                page: pagingParams.page - 1,
                size: 20,
                sort: [$scope.predicate + ',' + ($scope.reverse ? 'asc' : 'desc'), 'id']
            }, onSuccess, onError);
```

```
    @RequestMapping(value = "/_search/entities",
            method = RequestMethod.GET,
            produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    public ResponseEntity<List<Entity>> searchEntities(@RequestParam String query, Pageable pageable) throws URISyntaxException, UnsupportedEncodingException {
        ...
        Page<Entity> page = entitySearchRepository.search(wrapperQuery(query), pageable);
        ...
    }
```
This is equivalent to the last query above and will NOT throw errors if the user enters incorrect syntax. 

Using this as the query will match current behaviour:
```
                query: {
                    query_string: {
                        query: $scope.currentSearch
                    }
                },
```

By the way, I am using a modified pre-3.0 version of JHipster so there may be discrepancies in my samples like ES syntax or code style.

**Comment by geraldhumphries** [comment]
I can create a pull request for this, but I'd like to know what everyone things and if I should proceed.

**Comment by jdubois** [comment]
This looks like a good idea to me. I'm the one who did the `QueryStringQuery`, and I just did it that way because that was really easy, but on a real project I agree it won't be enough.
So +1 from me!

**Comment by jdubois** [comment]
Closing this as, unfortunately, the PR was rejected because of security issues.

**Comment by archangel269** [comment]
Hi @jdubois, can you please comment on the security issues you discovered? I have a need to build something similar in my JHipster application and I'd like to make sure I don't create any security problems! Thanks!

**Comment by geraldhumphries** [comment]
Here's the  SO question I opened about it: http://stackoverflow.com/questions/39103547/is-it-safe-to-expose-the-elasticsearch-search-api-directly-through-your-applicat

The answer is very good and explains why you can't give full access to users.

On the other hand, if you view my [pull request](https://github.com/jhipster/generator-jhipster/pull/4013) you can see that this is implemented with a wrapper query. **I think** makes it impossible to run aggregations, which are the main issue. I would like to revisit the security issues and clarify if there are any querys that cause problems.

**Comment by geraldhumphries** [comment]
One of the [issues](https://github.com/elastic/elasticsearch/issues/11511) referenced in the SO answer might shed some light on ways to break ES using queries. 

For example: https://github.com/elastic/elasticsearch/issues/17522

I haven't tested that one using my PR to see if it's possible to perform a query like that, however.

**Comment by jdubois** [comment]
@pkesavulu this is the bug tracker, please follow the project guidelines and use Stackoverflow if you have a question, it's nicer for other users who might have the same question
