### ISSUE TITLE
[solved] Error when add column to exist entity

### ISSUE THREAD

**Issue by ThanhLD24** [jhipster/generator-jhipster#3806]
##### **Overview of the issue**

![image](https://cloud.githubusercontent.com/assets/15336708/16648601/16b160ba-445f-11e6-85dd-311320b03a89.png)

##### **Motivation for or Use Case** 

I use `yo jhipster:entity power` (`power` is entity which I want to add more field) and choose `add more fields...`, when update complete, I back to project and run command: `mvn compile liquibase:diff` to get changelog file, I add this changelog file to `master.xml`, then I run project, it run normal, in my database, column was generated normal. But in jhipster admin display duplicate two entity `power`.

##### **JHipster Version(s)** 

I'm using the latest version of JHipster, furthermore here is my setup:
java 1.8
npm: 3.9.0
node: v4.4.4
yo: 1.8.4
bower: 1.7.9
gulp: 3.9.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

> {
>   "generator-jhipster": {
>     "jhipsterVersion": "3.0.0",
>     "baseName": "dmonitor",
>     "packageName": "vn.sds.dmonitor",
>     "packageFolder": "vn/sds/dmonitor",
>     "serverPort": "8080",
>     "authenticationType": "jwt",
>     "hibernateCache": "ehcache",
>     "clusteredHttpSession": "no",
>     "websocket": "no",
>     "databaseType": "sql",
>     "devDatabaseType": "h2Disk",
>     "prodDatabaseType": "mysql",
>     "searchEngine": "elasticsearch",
>     "buildTool": "maven",
>     "enableSocialSignIn": false,
>     "jwtSecretKey": "a6dbfb47e5059fb999093fe7809a84a36e87cf4f",
>     "useSass": false,
>     "applicationType": "monolith",
>     "testFrameworks": [
>       "gatling"
>     ],
>     "enableTranslation": true,
>     "nativeLanguage": "en",
>     "languages": [
>       "en",
>       "ja"
>     ]
>   }
> }

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
Power.json

> {
>     "relationships": [
>         {
>             "relationshipName": "area",
>             "otherEntityName": "area",
>             "relationshipType": "many-to-many",
>             "ownerSide": false,
>             "otherEntityRelationshipName": "power"
>         }
>     ],
>     "fields": [
>         {
>             "fieldName": "name",
>             "fieldType": "String",
>             "fieldValidateRules": [
>                 "required"
>             ]
>         },
>         {
>             "fieldName": "serial",
>             "fieldType": "String",
>             "fieldValidateRules": [
>                 "required"
>             ]
>         },
>         {
>             "fieldName": "setID",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "manuDate",
>             "fieldType": "LocalDate"
>         },
>         {
>             "fieldName": "expDate",
>             "fieldType": "LocalDate"
>         },
>         {
>             "fieldName": "description",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "counter",
>             "fieldType": "Integer"
>         },
>         {
>             "fieldName": "sellDate",
>             "fieldType": "LocalDate"
>         },
>         {
>             "fieldName": "useDate",
>             "fieldType": "LocalDate"
>         },
>         {
>             "fieldName": "type",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "alias",
>             "fieldType": "String"
>         }
>     ],
>     "changelogDate": "20160620112803",
>     "dto": "no",
>     "service": "no",
>     "entityTableName": "power",
>     "pagination": "pagination"
> }
> 

##### **Browsers and Operating System** 

Windows 7 Ultimate - 64 bit.

Sorry for my English.
Thanks for any help!

**Comment by wmarques** [comment]
If it's solved then I'm closing this.

**Comment by deepu105** [comment]
I dont understand the issue and @wmarques did you commit anything for this?
