### ISSUE TITLE
Do we need JhiLanguageController?

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#3807]
Everywhere in the front-end code where we use this controller can be easily moved to use only the JhiLanguageService. The only change on the service is to add a ```changeLanguage``` method.

Also, it will simplify, because everywhere we have to use the controller we need to inject dependencies that already contained on the service.

On my humble opinion, we can remove the controller and keep only the service, filter and constants.

**Comment by wmarques** [comment]
Agree with you, on top of that, we should avoid to use the `ng-controller` and keep controller assignments in routes.
So it seems logic to me to remove the `LanguageController` and put logic in the service.

**Comment by deepu105** [comment]
yes it can be removed. may be lets do it for ng2 directly


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Im closing this as we agree that this will be removed for ng2
