### ISSUE TITLE
ManyToMany Table name collision

### ISSUE THREAD

**Issue by oaj** [jhipster/generator-jhipster#3809]
This relationship will not run.
~~~
entity Residence {
  number String required maxlength(20)
}
entity ResidenceTag {
  name String required minlength(2) maxlength(20)
}
relationship ManyToMany {
  Residence{tag(name)} to ResidenceTag{residence(number)}
}
~~~
, the join table and the entity table of ResidenceTag will get the same name: "residence_tag"
, so exceptions:
Caused by: org.hibernate.MappingException: Foreign key (FK_39sxu0x5sd7aa9hdk6k912qhc:residence_tag [tags_id])) must have same number of columns as the referenced primary key (residence_tag [residences_id,tags_id])

Maybe better to make join table names based on entity table names and not field names - or add some prefix, maybe even a uid in the table name.

Changing the field name works:
~~~

relationship ManyToMany {
  Residence{residenceTag(name)} to ResidenceTag{residence(number)}
}
~~~

~~~
// Generated on 2016-07-03 using generator-jhipster 3.4.2

.yo-rc.json:
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "colony",
    "packageName": "net.amfibia.colony",
    "packageFolder": "net/amfibia/colony",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "8fd41094dd7c754b1a31b9267968ecdb3808c002",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
~~~

[Colony.json.txt](https://github.com/jhipster/generator-jhipster/files/353178/Colony.json.txt)
[Residence.json.txt](https://github.com/jhipster/generator-jhipster/files/353180/Residence.json.txt)
[ResidenceTag.json.txt](https://github.com/jhipster/generator-jhipster/files/353179/ResidenceTag.json.txt)
[uml1.jh.txt](https://github.com/jhipster/generator-jhipster/files/353181/uml1.jh.txt)

**Comment by jdubois** [comment]
Ticket #3839 is a duplicate from this one, but I find the other ticket better (better title, etc) and it has a proposed solution, so I'm closing this one and keeping the other opened.
