### ISSUE TITLE
v3.4.2

### ISSUE THREAD

**Issue by pplsreport** [jhipster/generator-jhipster#3810]
After upgrading jhipster generator with the latest version 3.4.2
`npm install -g generator-jhipster`
and starting generator with
`yo jhipster`
on a fresh folder (new project) following message appears:

> Welcome to the JHipster Generator v3.4.1
> Application files will be generated in folder: /home/misel/projects/test1
> ______________________________________________________________________________
>
>  JHipster update available: 3.4.2 (current: 3.4.1)
>  Run npm install -g generator-jhipster to update.

npm is showing that v3.4.2 is installed:
```misel@misel-amphinicy[~/temp/t]:
[14:26:25]  $ npm list -g |grep jhipster
├─┬ generator-jhipster@3.4.2
│ ├─┬ jhipster-uml@1.6.5
```

OS is Ubuntu 16.04 x64, running Node v4.4.4.

**Comment by deepu105** [comment]
You are clearly running v3.4.1 from the log output. Check if the local
jhipster in the folder isn't an old one or you have any npm link?

Thanks & regards,
Deepu

**Comment by pplsreport** [comment]
The folder I'm running `yo jhipster` in is empty - no node_modules folder below it:
```
misel@misel-amphinicy[~/temp/t]:
[16:21:24]  $ ls -la
total 8
drwxrwxr-x  2 misel misel 4096 Srp  8 14:21 .
drwxrwxr-x 12 misel misel 4096 Srp  8 14:21 ..
```
But as you said I obviously have some "local" older install:
```misel@misel-amphinicy[~/temp/t]:
[16:14:29]  $ npm list |grep jhipster
├─┬ generator-jhipster@3.4.1
│ ├─┬ jhipster-uml@1.6.5
```
 I have to look into it...

Thanks! Closing...

**Comment by jdubois** [comment]
What an awful ticket title!!! Please follow the guidelines next time
