### ISSUE TITLE
misleading foreign key constraint names for a many-to-many join table

### ISSUE THREAD

**Issue by HemanthD** [jhipster/generator-jhipster#3814]
##### **Overview of the issue**

The foreign key constraint names are misleading for a many-to-many join table. The FK names generated are of the format fk_joinTableName_entity_id and fk_joinTableName_otherEntity_id. However, the former is used for the 'otherEntity' column and the latter for the 'entity' column.

##### **Motivation for or Use Case** 

Error/ exception messages which refer to the foreign key can be misleading.

##### **JHipster Version(s)** 

3.3.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

[.yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/355858/default.yo-rc.json.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

[Foo.json.txt](https://github.com/jhipster/generator-jhipster/files/355859/Foo.json.txt)
[Bar.json.txt](https://github.com/jhipster/generator-jhipster/files/355860/Bar.json.txt)

##### **Browsers and Operating System** 

Chrome on Win 8.1 with MySQL 5.7

##### **Reproduce the error** 

create entity 'foo' with m2m relationship with 'bar' with foo as the owner of the relationship
create entity 'bar'
view the _added_entity_constraints_Foo.xml_
the fk_foo_bar_**bar_id** refers to **foos_id** (instead of bars_id) and fk_foo_bar_**foo_id** refers to **bars_id** (instead of foos_id)

##### **Related issues** 

#2443 reports a similar issue for the 'joinTable' part of the fk name, but this issue (related to the entity name part of the fk) is not addressed.

##### **Suggest a Fix** 

Issue seems to be with the below piece of code

    var constraintName = 'fk_' + joinTableName + '_' + otherEntityName.toLowerCase() + '_id';
    var otherEntityConstraintName = 'fk_' + joinTableName + '_' + name.toLowerCase() + '_id';

in _generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml_ which should be using name and otherEntityName respectively. Also, it might be worth considering using the corresponding plural name in the fk name also so that it is consistent with the column name (for e.g. fk_foo_bar_**foos_id** instead of fk_foo_bar_**foo_id**)

**Comment by systemsplanet** [comment]
FYI, Just reported this problem with the contraint names breaking the build
https://github.com/jhipster/generator-jhipster/issues/3839

**Comment by deepu105** [comment]
Guys if the issues are related can you close one and keep one issue updated?

Thanks & regards,
Deepu
