### ISSUE TITLE
Foreign key constraint lengths are not checked consistently for MySQL database

### ISSUE THREAD

**Issue by HemanthD** [jhipster/generator-jhipster#3815]
##### **Overview of the issue**

Foreign key constraint lengths are not checked consistently for MySQL database. There are possibilities of foreign keys being generated with lengths > 64.

##### **Motivation for or Use Case** 

The generated foreign keys can have longer lengths than allowed by MySQL database, leading to failures during liquibase operations.

##### **JHipster Version(s)** 

3.3.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

[.yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/355969/default.yo-rc.json.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

[EntityFooWithLongNameToTestConstraintLengths.json.txt](https://github.com/jhipster/generator-jhipster/files/355970/EntityFooWithLongNameToTestConstraintLengths.json.txt)
[EntityBarWithLongNameToTestConstraintLengths.json.txt](https://github.com/jhipster/generator-jhipster/files/355971/EntityBarWithLongNameToTestConstraintLengths.json.txt)

##### **Browsers and Operating System** 

Chrome on Win 8.1 with MySQL 5.7

##### **Reproduce the error** 

Create entity EntityFooWithLongNameToTestConstraintLengths with a long name (above 30 char) with a many-to-one relationship with another entity EntityBarWithLongNameToTestConstraintLengths
Create entity EntityBarWithLongNameToTestConstraintLengths with a one-to-many relationship with ...Foo... entity
View the _added_entity_constraints_EntityFooWithLongNameToTestConstraintLengths.xml_
The foreign key will have a length more than 64 char which is not allowed in MySQL
Liquibase fails with the error
`Identifier name 'fk_entityfoowithlongnametotestconstraintlengths_entitybarwithlongnametotestconstraintlengths_id' is too long [Failed SQL: ALTER TABLE atlas.entity_foo_with_long_name_to_test_constraint_lengths ADD CONSTRAINT fk_entityfoowithlongnametotestconstraintlengths_entitybarwithlongnametotestconstraintlengths_id FOREIGN KEY (entity_bar_with_long_name_to_test_constraint_lengths_id) REFERENCES atlas.entity_bar_with_long_name_to_test_constraint_lengths (id)]`

##### **Related issues** 

Did not find any issues reported. Noticed the missing checks while addressing #3814

##### **Suggest a Fix** 

Issue seems to be with missing length check for MySQL in **many-to-one** section of  _generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml_. (Only the check for oracle exists)

Also, in **many-to-many** section of the same file, only the constraintName length is being validated but not the otherConstraintName for both Oracle and MySQL.

`if(prodDatabaseType === 'oracle' && constraintName.length > 30) {`

`if(prodDatabaseType === 'mysql' && constraintName.length > 64) {`

**Comment by deepu105** [comment]
Would you like to do a PR fix?

Thanks & regards,
Deepu
