### ISSUE TITLE
How to inject repository into Mapper?

### ISSUE THREAD

**Issue by spyhunter88** [jhipster/generator-jhipster#3819]
I am using current latest (3.4.2), I use **Many-to-Many** relationship **User-Vendor** and use in Mapper. But when writing vendorsFromVendorDTOs, I can not get Vendor from database with ID from VendorDTO because I can not inject VendorRepository into Mapper interface.
Also, this example need to be updated: https://jhipster.github.io/using-dtos/ because it uses abstract class instead of interface right now.

The other way is edit **MapperImpl** but I don't think it's a good idea, because this file can be re-generated.
And what's best practice to write this function without modify MapperImpl.

**Comment by gmarziou** [comment]
This is not a JHipster issue, please ask a question on Stackoverflow or Gitter.

**Comment by gmarziou** [comment]
I closed it too early because the fix could be in our doc.
I think you should try a reference mapper: 

http://mapstruct.org/documentation/1.0/reference/html/index.html#passing-target-type

**Comment by spyhunter88** [comment]
I'm using MapStruct 1.0.0-Final but not found ApplicationScoped annotation. But I think this is MapStruct problem, not jhipster. I'll try later.
And, I don't really need to get Entity back, just a few properties is ok. Thanks for you support.
So I close this here.

**Comment by gmarziou** [comment]
ApplicationScoped annotation is CDI, so you should adapt the example to Spring
