### ISSUE TITLE
Gradle > 2.12 not working

### ISSUE THREAD

**Issue by mhavrlent** [jhipster/generator-jhipster#3821]
##### **Overview of the issue**

Building project with gradle version > 2.12 produces following error:

FAILURE: Build failed with an exception.

* What went wrong:
Unable to process incoming event 'ProgressComplete ' (ProgressCompleteEvent)

##### **Motivation for or Use Case** 

I've tried with version 2.13, the "latest jhipster version" 2.14 and also 2.14.1-rc-2.
Only 2.12 (and maybe below) works.

##### **JHipster Version(s)** 

3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "app",
    "packageName": "com.test.app",
    "packageFolder": "com/test/app",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

No .jhipster directory present.

##### **Browsers and Operating System** 

Not browser related error.

##### **Reproduce the error** 

gradlew.bat

##### **Related issues** 

https://discuss.gradle.org/t/build-falis-with-unable-to-process-incoming-event-progresscomplete-progresscompleteevent/18434

##### **Suggest a Fix** 

Use gradle version <= 2.12

**Comment by ruddell** [comment]
I am able to compile a project with both v2.12 (local gradle) and v2.14 (`./gradlew`) on OSX.  I am also able to use v2.14 on Windows 10.  Can anyone else reproduce this issue?

**Comment by pascalgrimaud** [comment]
Unable to reproduce with docker image jhipster/jhipster
See the full log at https://travis-ci.org/pascalgrimaud/jhipster-tester/builds/144081660

What is your OS ? What is the command you used to build ?

**Comment by mhavrlent** [comment]
OS is Win 7. Command (as mentioned already) is gradlew.bat, no parameters, just that.

**Comment by ruddell** [comment]
Both the Gradle wrapper and installed Gradle v2.14 works for me on Windows 7.  Can you give us any more information?

**Comment by atomfrede** [comment]
Gradle wrapper 2.14 works fine on Linux
Am 12.07.2016 20:41 schrieb "Jon Ruddell" <notifications@github.com>:

**Comment by mhavrlent** [comment]
Thanks guys. Seems it's really not reproducible by anyone else, so unless you have any idea how to debug this, we can close the ticket.

**Comment by mhavrlent** [comment]
I just tried with local gradle 2.14 (not gradlew.bat) and it works. Then I tried again with the gradlew.bat and it's not.

**Comment by jobinar** [comment]
I am able to reproduce this issue with gradle 2.14.1. However, this issue is intermittent and goes away when retried a couple of times. I cannot paste the gradle file since this is on a closed-source project.

**Comment by deepu105** [comment]
Please dont camp on old issues. Open a new issue if you have one.

Thanks & regards,
Deepu

**Comment by svict4** [comment]
I was having this issue on a newly generated project on Windows 10 as well.
The problem was [reported to Gradle ](https://github.com/gradle/gradle/issues/882) and has been[ fixed recently](https://github.com/gradle/gradle/pull/1155).

Either wait for Gradle's new version to propagate downstream, or update to the fixed nightly build directly by going into `<jhipster installation>\gradle\wrapper` and running [`gradle wrapper --gradle-version 3.4-20170166000026+0000`](https://github.com/gradle/gradle/pull/1155#issuecomment-272836950)
