### ISSUE TITLE
Service class not generated after modifying <jhipster_root_folder>/.jhipster/entityName.json

### ISSUE THREAD

**Issue by eosimosu** [jhipster/generator-jhipster#3822]
##### **Overview of the issue**

I updated <jhipster_root_folder>/.jhipster/entityName.json by making the change  "service": "yes" (from "service": "no"), however, no entityNameService.java was created.  Athough entityNameService is injected into entityNameResource.

fyi, I ran yo:jhipster entityName afterwards.

##### **JHipster Version(s)** 

3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "myapp",
    "packageName": "org.myapp.myapp",
    "packageFolder": "org/myapp/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "enableSocialSignIn": false
  }
}

**Comment by ruddell** [comment]
`yes` is not an option for service because there is more than one answer to that prompt.  The available options are `no`, `serviceClass`, and `serviceImpl`
