### ISSUE TITLE
Would you please change the special font or icon in homepage?

### ISSUE THREAD

**Issue by QianJin2013** [jhipster/generator-jhipster#3828]
I become like JHipster very much TODAY.  Thank you very much.

When i first time enter http://jhipster.github.io, I am really confused by the special big font of several titles because i can not recognize them easily, and i am shocked by the big icons (for modules) because i don't know why so important, i can not help click it but no response:D

I think these things attract reader's attention too much, make some readers loose interesting to continue.

Only very patient people can find the "quick start" in the homepage :D

**Comment by PierreBesson** [comment]
It seems you are not enough of a hipster to use our project :smile: !

However having met a lot of foreign friends I can confirm that "cursive writing" is completely unreadable for some people especially if almost all the latin characters you have seen in your life were on printed text.

Even though I kind of like the current design, my opinion is that we should change the black titles on the main page to a different font than Pacifico. We don't want to make it hard to read for a large part of our users. But please keep the "greetings java hipster" like it is.

**Comment by QianJin2013** [comment]
@PierreBesson Glad to know you know my feeling.  I am new to jhipster but i am not hipster 😄.
I have a idea to keep current design yet make it easy understand:

**change to normal font on hover** 

How?

**Comment by PierreBesson** [comment]
it works adding the following css rule with dev tools but the result is not as pretty as expected.
```
.brand:hover {
    font-family: serif;
}
```

**Comment by deepu105** [comment]
I guess it wouldn't look nice with change on hover and stuff. I guess we
can use a different font for the titles. Let me see.
@jdubois are you ok with this?


Thanks & Regards,
Deepu

**Comment by sendilkumarn** [comment]
How about we redesign the website again?

**Comment by jdubois** [comment]
I'm sorry guys I'm on holidays, without a laptop, so I can't test.
We already have enough work, let's not redesign the website unless that's
necessary. Indeed, we could change the cursive fonts: they are hipster, but
difficult to read.
Le 12 juil. 2016 3:54 PM, "Sendil Kumar N" <notifications@github.com> a
écrit :

**Comment by QianJin2013** [comment]
Thanks for every reply.  I think no need **redesign**, at least not now. Just need some presentation improvement for non-english-native user. I would like to help translate document to chinese and even japanese in my spare time.

This project is best in generator field, or will be best, and i believe it will get big funded, because it can grow to a giant knowledge collector, contains many programing patterns which in turn become the source of AI.

Such a promise project's home page should be very kind to all programers and professionals, english or non-english.

But currently, as i know, Chinese or Japanese still not realize the good of this project, most of them don't get it at first glance of the home page, include me 😓,  but i am patient and read several times and find quick start.

Besides,  there is another trivial doc-related problem(Actually not a problem, i just do not know how to express it). 

A considerable number of users will not follow your doc page to read [Technology stack](https://jhipster.github.io/tech-stack/), then JUST use it immediately. 

When they use the CLI to generate sources, they first encountered with the "Application type" conception. I know the conception and make a choice, but other guys will get stuck. 

So, put the link [Creating an application](https://jhipster.github.io/creating-an-app/) to the CLI will be very helpful. This link is the actual entry point for most people, i think.

```
$ yo
...
? (1/16) Which *type* of application would you like to create? (Use arrow keys)
❯ Monolithic application (recommended for simple projects) 
... ...
     _-----_     ╭───────────────────────╮
 ...
 ...
    ___PUT_IT_HERE___PUT_IT_HERE__PUT_IT_HERE   │
    /___A___\   /╰───────────────────────╯
```

There does have a link to the home page, but it's not easily redirected to the [Creating an application](https://jhipster.github.io/creating-an-app/) link in a second. Of course some patient guys will find it via google but some just abort.

**Comment by QianJin2013** [comment]
I am really moved by the quality of the project. When i randomly chose some pattern to generate source and run test cases of generated source, they all succeeded! even in IntelliJ IDEA, without any boring configuration. 😃

**Comment by deepu105** [comment]
@QianJin2013 I can understand your concern so I'm gonna change the font of the titles. and yes it might be a good idea to put the creating apps link in the CLI.

**Comment by QianJin2013** [comment]
@deepu105 👍

**Comment by deepu105** [comment]
its done here https://github.com/jhipster/jhipster.github.io/pull/287 and https://github.com/jhipster/generator-jhipster/commit/53afa6de1e6a10dc059c65c58c314784a35eb6d8
