### ISSUE TITLE
Pretty print JSON in dev

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#3830]
In dev profile, we should probably enable ```SerializationFeature.INDENT_OUTPUT``` to increase readability (using JSON is all about human readability after all).
In prod, since we compress the response, pretty-printing would not add much traffic (I've read that it was about 2-3%) and ease debugging but that's debatable.
What do you think ?

**Comment by sendilkumarn** [comment]
we can add that in `JacksonConfiguration`.  [ No issues with that ]

>pretty-printing would not add much traffic 


But traffic we need to take a look.

**Comment by gmarziou** [comment]
OK for dev even though tools already do this for us: Chrome extension, swagger-ui, ...

For prod, I'm more reluctent because even if compression optimisse network bandwith consumption, there is still slightly higher memory and CPU consumption when parsing response on a mobile device.

**Comment by jdubois** [comment]
- for dev I also don't have that need, my tools do it for me, but I understand why people would want it - we should have a voting system for this kind of thing 
- for prod we should not do it, it will eat CPU for nothing

**Comment by cbornet** [comment]
> for dev I also don't have that need, my tools do it for me, but I understand why people would want it - we should have a voting system for this kind of thing 

Yes, it's too bad there is no voting system incliuded in gh.
I have to confess that I use a lot of curl to debug. I should be ashamed but I think I'm not the only one... :smile: 

> for prod we should not do it, it will eat CPU for nothing 

Good point. So let's forget it for prod.

**Comment by gmarziou** [comment]
> I have to confess that I use a lot of curl to debug. I should be ashamed but I think I'm not the only one... 

That's right, I forgot about curl, we use it a lot also.

What about having a property set to true in application-dev.yml and to false in application-prod.yml?

**Comment by cbornet** [comment]
@gmarziou I like it : freedom of choice !

**Comment by gmarziou** [comment]
:) and maybe it could be done with spring boot properties, I did not check what could already be done:

http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

**Comment by cbornet** [comment]
Since we provide our own Jackson2ObjectMapperBuilder to load the JSR310 converters I don't know if they still work. I'll check.

**Comment by jdubois** [comment]
I don't like the property because this one would only work in dev, so it's misleading in prod.
If everyone agrees let's have pretty print by default in dev. That's easy and simple, and a logical default behavior.

**Comment by PierreBesson** [comment]
I know this issue was still flagged "needs-discussion" but I still submitted a simple PR.
Please tell me if this is satisfying for everyone.
Another option would be to replace the check for the dev profile by a new jhipster property. I can do it if the team agrees on this.

**Comment by cbornet** [comment]
I managed to customize spring-boot's autoconfigured Jackson2ObjectMapperBuilder (that uses ```spring.jackson``` properties in application-xxx.yml).
So then we can set ```spring.jackson.serialization.INDENT_OUTPUT: true``` only in application-dev.yml.
The advantage is that the user has control of the mapper from the property file.
We can also force some properties. For instance, should I force ```WRITE_DATES_AS_TIMESTAMPS: false``` ?

**Comment by cbornet** [comment]
And if he wants pretty printing in prod, he can always do it easily

**Comment by cbornet** [comment]
And I refactored the full jackson config so it's a lot nicer now

**Comment by gmarziou** [comment]
Great work @cbornet
