### ISSUE TITLE
[FEATURE] Delete existing entity from entity generator

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3835]
##### **Overview of the issue**

Coming from comments on a [SO question](https://stackoverflow.com/questions/38346370/jhipster-deleting-project), it would be great to be able to delete an entity using `yo jhipster:entity <name>`

##### **JHipster Version(s)** 
3.4.2

##### **Suggest a Fix** 

Add a new question, delete generated file and maybe create a new changelog to drop table rather than deleting creation changelog

**Comment by deepu105** [comment]
Its possible but would be more difficult then modification coz of all the
needles we update and stuff, but some regex magic can do the trick. I
thought of doing it when i did the entity update option but then decided to
leave it due to the complexity

Thanks & regards,
Deepu

**Comment by cbornet** [comment]
I had started to work on that but we miss a lot of functions to remove lines from files so I have put it in stand-by

**Comment by cbornet** [comment]
Same as @deepu105 :smile:

**Comment by gmarziou** [comment]
Agreed but as of today it's purely manual and error prone, maybe we could provide some assistance here by picking the low hanging fruits which means deleting all generated files we are sure won't cause any trouble and then print a list of files where the generator could not do it manually and where human decision is required.

**Comment by jdubois** [comment]
That's probably impossible to do properly. There are too many use cases, and it's going to be very annoying to maintain (as this should be maintained when we modify the sub-generator).
My main recommandation is that people should do a commit before running any sub-generator :

- so they can easily check what we modified
- so they can rollback if they need to do

It's not hard to do, and solves a lot of issues.

BTW, I don't know of any competing generator that provides this kind of feature.

**Comment by gmarziou** [comment]
OK, I close it

**Comment by cbornet** [comment]
Actually, the modified files can easily be rolledback by running the generator with --with-entities.
But that will not delete the files that were generated specifically for the entity so maybe we could provide a way to delete them. That would not be very hard to do or to maintain.
