### ISSUE TITLE
[FEATURE] H2 DB URL should include MODE=xxx

### ISSUE THREAD

**Issue by systemsplanet** [jhipster/generator-jhipster#3841]
H2 allows you to specify a Mode that makes it behave like another DB.
This eliminates a lot of queries that would work locally but break in prod

jdbc:h2:file:./.h2/db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;SCHEMA_SEARCH_PATH=SCHEMA1.SCHEMA2;MODE=Oracle

I would also recommend stop using Target as the default db folder. I'd use ./.h2/db

The availalble modes are here, copied below:
http://www.h2database.com/html/features.html 

### HSQLDB Compatibility Modes

To use the HSQLDB mode, use the database URL jdbc:h2:~/test;MODE=HSQLDB or the SQL statement SET MODE HSQLDB.

For aliased columns, ResultSetMetaData.getColumnName() returns the alias name and getTableName() returns null.
When converting the scale of decimal data, the number is only converted if the new scale is smaller than the current scale. Usually, the scale is converted and 0s are added if required.
For unique indexes, NULL is distinct. That means only one row with NULL in one of the columns is allowed.
Text can be concatenated using '+'.

### MS SQL Server Compatibility Mode

To use the MS SQL Server mode, use the database URL jdbc:h2:~/test;MODE=MSSQLServer or the SQL statement SET MODE MSSQLServer.

For aliased columns, ResultSetMetaData.getColumnName() returns the alias name and getTableName() returns null.
Identifiers may be quoted using square brackets as in [Test].
For unique indexes, NULL is distinct. That means only one row with NULL in one of the columns is allowed.
Concatenating NULL with another value results in the other value.
Text can be concatenated using '+'.
MySQL Compatibility Mode

To use the MySQL mode, use the database URL jdbc:h2:~/test;MODE=MySQL or the SQL statement SET MODE MySQL.

When inserting data, if a column is defined to be NOT NULL and NULL is inserted, then a 0 (or empty string, or the current timestamp for timestamp columns) value is used. Usually, this operation is not allowed and an exception is thrown.
Creating indexes in the CREATE TABLE statement is allowed using INDEX(..) or KEY(..). Example: create table test(id int primary key, name varchar(255), key idx_name(name));
Meta data calls return identifiers in lower case.
When converting a floating point number to an integer, the fractional digits are not truncated, but the value is rounded.
Concatenating NULL with another value results in the other value.
Text comparison in MySQL is case insensitive by default, while in H2 it is case sensitive (as in most other databases). H2 does support case insensitive text comparison, but it needs to be set separately, using SET IGNORECASE TRUE. This affects comparison using =, LIKE, REGEXP.

###  Oracle Compatibility Mode

To use the Oracle mode, use the database URL jdbc:h2:~/test;MODE=Oracle or the SQL statement SET MODE Oracle.

For aliased columns, ResultSetMetaData.getColumnName() returns the alias name and getTableName() returns null.
When using unique indexes, multiple rows with NULL in all columns are allowed, however it is not allowed to have multiple rows with the same values otherwise.
Concatenating NULL with another value results in the other value.
Empty strings are treated like NULL values.

### PostgreSQL Compatibility Mode

To use the PostgreSQL mode, use the database URL jdbc:h2:~/test;MODE=PostgreSQL or the SQL statement SET MODE PostgreSQL.

For aliased columns, ResultSetMetaData.getColumnName() returns the alias name and getTableName() returns null.
When converting a floating point number to an integer, the fractional digits are not be truncated, but the value is rounded.
The system columns CTID and OID are supported.
LOG(x) is base 10 in this mode.

**Comment by deepu105** [comment]
That might be a good idea to set based on the prod db choosen. But i would
still prefer target folder as it would be cleaned by builds automatically.

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
- for the target folder: it's good the way it is today, doing a `mvn clean`
to clean it is natural for everyone, and works the same for all
technologies (like the Elasticsearch indexes)
- for the "mode" option: we're supposed to be database independant thanks
to Hibernate & Liquibase, so I haven't seen that need yet. It could be
interesting if people use some specific features of their database, and
bypass Hibernate, but instead I would recommend to use the real database,
for example with Docker. I'm also quite afraid this would cause issues with
Hibernate : as it won't have the good Hibernate dialect, this opens the
door for a huge number of issues - I won't go that way unless there is a
good litterature showing this is safe.

Le 14 juil. 2016 3:35 AM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

That might be a good idea to set based on the prod db choosen. But i would
still prefer target folder as it would be cleaned by builds automatically.

Thanks & regards,
Deepu

On 14 Jul 2016 05:25, "Mike Lawrence" <notifications@github.com> wrote:

> H2 allows you to specify a Mode that makes it behave like another DB.
> This eliminates a lot of queries that would work locally but break in prod
>
>
>
jdbc:h2:file:./.h2/db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;SCHEMA_SEARCH_PATH=SCHEMA1.SCHEMA2;MODE=Oracle
>
> I would also recommend stop using Target as the default db folder. I'd use
> ./.h2/db
>
> The availalble modes are here, copied below:
> http://www.h2database.com/html/features.html
> HSQLDB Compatibility Modes
>
> To use the HSQLDB mode, use the database URL jdbc:h2:~/test;MODE=HSQLDB or
> the SQL statement SET MODE HSQLDB.
>
> For aliased columns, ResultSetMetaData.getColumnName() returns the alias
> name and getTableName() returns null.
> When converting the scale of decimal data, the number is only converted if
> the new scale is smaller than the current scale. Usually, the scale is
> converted and 0s are added if required.
> For unique indexes, NULL is distinct. That means only one row with NULL in
> one of the columns is allowed.
> Text can be concatenated using '+'.
> MS SQL Server Compatibility Mode
>
> To use the MS SQL Server mode, use the database URL
> jdbc:h2:~/test;MODE=MSSQLServer or the SQL statement SET MODE MSSQLServer.
>
> For aliased columns, ResultSetMetaData.getColumnName() returns the alias
> name and getTableName() returns null.
> Identifiers may be quoted using square brackets as in [Test].
> For unique indexes, NULL is distinct. That means only one row with NULL in
> one of the columns is allowed.
> Concatenating NULL with another value results in the other value.
> Text can be concatenated using '+'.
> MySQL Compatibility Mode
>
> To use the MySQL mode, use the database URL jdbc:h2:~/test;MODE=MySQL or
> the SQL statement SET MODE MySQL.
>
> When inserting data, if a column is defined to be NOT NULL and NULL is
> inserted, then a 0 (or empty string, or the current timestamp for
timestamp
> columns) value is used. Usually, this operation is not allowed and an
> exception is thrown.
> Creating indexes in the CREATE TABLE statement is allowed using INDEX(..)
> or KEY(..). Example: create table test(id int primary key, name
> varchar(255), key idx_name(name));
> Meta data calls return identifiers in lower case.
> When converting a floating point number to an integer, the fractional
> digits are not truncated, but the value is rounded.
> Concatenating NULL with another value results in the other value.
> Text comparison in MySQL is case insensitive by default, while in H2 it is
> case sensitive (as in most other databases). H2 does support case
> insensitive text comparison, but it needs to be set separately, using SET
> IGNORECASE TRUE. This affects comparison using =, LIKE, REGEXP.
> Oracle Compatibility Mode
>
> To use the Oracle mode, use the database URL jdbc:h2:~/test;MODE=Oracle or
> the SQL statement SET MODE Oracle.
>
> For aliased columns, ResultSetMetaData.getColumnName() returns the alias
> name and getTableName() returns null.
> When using unique indexes, multiple rows with NULL in all columns are
> allowed, however it is not allowed to have multiple rows with the same
> values otherwise.
> Concatenating NULL with another value results in the other value.
> Empty strings are treated like NULL values.
> PostgreSQL Compatibility Mode
>
> To use the PostgreSQL mode, use the database URL
> jdbc:h2:~/test;MODE=PostgreSQL or the SQL statement SET MODE PostgreSQL.
>
> For aliased columns, ResultSetMetaData.getColumnName() returns the alias
> name and getTableName() returns null.
> When converting a floating point number to an integer, the fractional
> digits are not be truncated, but the value is rounded.
> The system columns CTID and OID are supported.
> LOG(x) is base 10 in this mode.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/3841>, or mute the
> thread
> <
https://github.com/notifications/unsubscribe/ABDlFyrtUrUFCDUhFshYQ-5lhm9yLYQuks5qVXrfgaJpZM4JL9iW
>

> .
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/3841#issuecomment-232533562>,
or mute the thread
<https://github.com/notifications/unsubscribe/AATVo390HVK27dvN2Gn24dEDeFmclp6Dks5qVZJHgaJpZM4JL9iW>
.

**Comment by deepu105** [comment]
Agree that there is no real pressing need for this at the point.



Thanks & Regards,
Deepu
