### ISSUE TITLE
jhipsterFunc.replaceContent() is giving error

### ISSUE THREAD

**Issue by kkorada** [jhipster/generator-jhipster#3842]
##### **Overview of the issue**
 when trying to build a module with jhipster, jhipsterFunc.replaceContent() is giving me error as
**Unable to find [object Object] or missing required pattern. File rewrite failed.**

##### **JHipster Version(s)** 

v3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

not related to yo-rc file

##### **Error while using that method** 
my code is as follows:
```
try {
            jhipsterFunc.replaceContent({
              file: webappDir+'app/content/css/main.css',
              pattern: 'color: #333;',
              content: 'color: #4f5355;',
              regex: true
          }, this);
        } catch (e) {
            this.log(chalk.yellow('\nUnable to find ') + filePath + chalk.yellow(' or missing required pattern. File rewrite failed.\n') + e);
        }
```

output is:
```
Unable to find [object Object] or missing required pattern. File rewrite failed.

TypeError: Path must be a string. Received { file: 'src/main/webapp/app/content/
css/main.css',
  pattern: 'color: #333;',
  content: 'color: #4f5355;',
  regex: true }
```

**Comment by gmarziou** [comment]
Might not be related but why do you set regex to true if you pass a simple string without any wildcard characters in pattern?

**Comment by kkorada** [comment]
yes string appears only once in file. I think regex false should also work. thankyou

**Comment by gmarziou** [comment]
also I'm not sure webappDir ends with a slash so you should put it this way:

file: webappDir+'**/**app/content/css/main.css',

**Comment by kkorada** [comment]
no its ending with slash I have logged it and checked, even it is present in error also.

**Comment by gmarziou** [comment]
I think there are 2 replaceContent functions one in util.js that takes an obect as an argument and one in generator-base.js that takes 4 strings. I suspect that when you use jhipsterFunc, you're calling second one

https://github.com/jhipster/generator-jhipster/blob/53afa6de1e6a10dc059c65c58c314784a35eb6d8/generators/generator-base.js#L931

**Comment by gmarziou** [comment]
Also I don't know what your module does but if it's only about adapting CSS, using SASS would be much simpler.

**Comment by kkorada** [comment]
ok I am trying to add themes via modules, so I need to override some css.

**Comment by gmarziou** [comment]
Did you solve your issue? Can we close it?

**Comment by kkorada** [comment]
no still jhipsterFunc.replaceContent()  is not working !
it is giving me same error

**Comment by kkorada** [comment]
with above mentioned code
i am getting 
Unable to find [object Object] or missing required pattern. File rewrite failed.
```

TypeError: Path must be a string. Received { file: 'src/main/webapp/app/content/
css/main.css',
  pattern: 'color: #333;',
  content: 'color: #4f5355;',
  regex: true }
```
what does it mean by path must be string ?

**Comment by gmarziou** [comment]
It just says that it received an object `{ file: .... }` instead of a string, that's why I suggested

```
jhipsterFunc.replaceContent(
               webappDir+'app/content/css/main.css',
               'color: #333;',
               'color: #4f5355;',
               false)
```

**Comment by kkorada** [comment]
ok thank you thats all i want, by mistake i was looking at below code in utils file

```
function replaceContent(args, _this) {
    args.path = args.path || process.cwd();
    var fullPath = path.join(args.path, args.file);

    var re = args.regex ? new RegExp(args.pattern, 'g') : args.pattern;

    var body = _this.fs.read(fullPath);
    body = body.replace(re, args.content);
    _this.fs.write(fullPath, body);
}
```
so i passed object.

**Comment by gmarziou** [comment]
Yes, I guess these are internal methods that's why they are not commented, the other ones are supposed to be exposed and so are better commented.
