### ISSUE TITLE
Issue in Creating Entities using Jhipster UML

### ISSUE THREAD

**Issue by minu-jain** [jhipster/generator-jhipster#3845]
I treid generating entities with below sample jdl :
I have downloaded latest code from github:

entity Industry {
value String required maxlength(50) }

entity CreditType {
module String required maxlength(17),
credit Integer required max(255),
isActive Boolean required ,
createdby Integer required max(255),
updatedby Integer required max(255),
updatedon ZonedDateTime required ,
createdon ZonedDateTime required }
 
I generated entities using the below command jhipster-uml jhipster-jdl.jh

Entities are getting generated. When I am running the application on all new entities its giving error as Error internal server Error. Snapshot is attached. This error is not coming on Bank account, Label etc.
![issue](https://cloud.githubusercontent.com/assets/20437424/16865606/9e4c2864-4a83-11e6-8e80-7d1b149157a5.png)

**Comment by gmarziou** [comment]
Please provide server log of the error.

**Comment by minu-jain** [comment]
the server logs is
As u can see the error.internal server error and the GET request that is firing

error in server is coming as:
 2016-07-14 11:37:02.373 DEBUG 2044 --- [nio-8080-exec-5] c.m.myapp.aop.logging.LoggingAspect : Enter: com.mycompany.myapp.web.rest.erro
 rs.ExceptionTranslator.processRuntimeException() with argument[s] = [org.springframework.web.method.annotation.MethodArgumentTypeMismatchExc
 eption: Failed to convert value of type [java.lang.String] to required type [java.lang.Long]; nested exception is java.lang.NumberFormatExce
 ption: For input string: "new"]

**Comment by minu-jain** [comment]
Why it is firing a GET request via entity.new state ref ? 
angular.js:11756 GET http://localhost:8080/api/spendpools/new?cacheBuster=1468565532181 500 (Internal Server Error)

**Comment by gmarziou** [comment]
Something is probably wrong with Industry generated entity, have you tried re-generating it with another filed name than `value`? It could be an issue with a reserved word  on angular side

**Comment by minu-jain** [comment]
Its giving for all entities. CreditType is also another entity.
I tried with many still same error coming.

**Comment by ruddell** [comment]
I generated a basic project and ran `jhipster-uml jhipster-jdl.jh` on your JDL, and I have no issues creating any entities.  I am running the master version of jhipster-uml though which is a bit ahead of the latest release though.

Could you please fill out the rest of the issue template (mainly the .yo-rc.json)?

**Comment by minu-jain** [comment]
{
  "generator-jhipster": {
    "baseName": "jhipsterSampleApplication",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "maven",
    "rememberMeKey": "5c37379956bd1242f5636c8cb322c2966ad81277",
    "searchEngine": "no",
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "languages": [
      "en"
    ],
    "serverPort": 8080,
    "jhipsterVersion": "3.4.2",
    "enableSocialSignIn": false,
    "useSass": false,
    "jhiPrefix": "jhi"
  }
}

**Comment by ruddell** [comment]
I still can't reproduce the issue using the latest versions of JHipster (v3.4.2) and JHipster-UML ( v1.6.5).  My only guess would be to run `mvn clean` which will clear the target folder, then retry `mvn`.

**Comment by minu-jain** [comment]
have u checked after doing server up and den trying to create new entity via UI ?

**Comment by ruddell** [comment]
I tried again and it still works fine for me:  [Screenshot](https://cloud.githubusercontent.com/assets/4294623/16867429/a41ddaec-4a26-11e6-8627-0d42e60c7804.png).  Another necessary section of the issue template is "an unambiguous set of steps to reproduce the error."

**Comment by minu-jain** [comment]
Can u write ur steps what u did for this. 
How you have install JHipster-UML (v1.6.5). 

I will replicate your steps as it. Thanks for your time and efforts.

**Comment by ruddell** [comment]
To install JHipster-UML (version in command is optional): `npm install -g jhipster-uml@1.6.5`

To build the project:

- Copy your .yo-rc.json and jhipster-jdl.jh into an empty folder
- Run `yo jhipster`
- Run `jhipster-uml jhipster-jdl.jh`
- Run `./mvnw` (command might slightly differ for Windows).

**Comment by minu-jain** [comment]
I followed the steps provided. Now I am not able to login into that.
Getting error AS:
2016-07-15 14:51:26.884 DEBUG 7548 --- [nio-8080-exec-1] j.s.s.CustomPersistentRememberMeServices : Remember-me cookie detected
Hibernate: select persistent0_.series as series1_13_0_, persistent0_.ip_address as ip_addre2_13_0_, persistent0_.token_date as token_da3_13_
0_, persistent0_.token_value as token_va4_13_0_, persistent0_.user_id as user_id6_13_0_, persistent0_.user_agent as user_age5_13_0_, user1_.
id as id1_14_1_, user1_.created_by as created_2_14_1_, user1_.created_date as created_3_14_1_, user1_.last_modified_by as last_mod4_14_1_, u
ser1_.last_modified_date as last_mod5_14_1_, user1_.activated as activate6_14_1_, user1_.activation_key as activati7_14_1_, user1_.email as
email8_14_1_, user1_.first_name as first_na9_14_1_, user1_.lang_key as lang_ke10_14_1_, user1_.last_name as last_na11_14_1_, user1_.login as
 login12_14_1_, user1_.password_hash as passwor13_14_1_, user1_.reset_date as reset_d14_14_1_, user1_.reset_key as reset_k15_14_1_ from jhi_
persistent_token persistent0_ left outer join jhi_user user1_ on persistent0_.user_id=user1_.id where persistent0_.series=?
2016-07-15 14:51:26.929 DEBUG 7548 --- [nio-8080-exec-1] j.s.s.CustomPersistentRememberMeServices : No persistent token found for series id:
 /Xj2mGLWdBjuIhGF1M79Aw==
2016-07-15 14:51:26.930 DEBUG 7548 --- [nio-8080-exec-1] j.s.s.CustomPersistentRememberMeServices : Cancelling cookie
2016-07-15 14:51:26.998 DEBUG 7548 --- [nio-8080-exec-2] j.s.s.CustomPersistentRememberMeServices : Remember-me cookie detected
Hibernate: select persistent0_.series as series1_13_0_, persistent0_.ip_address as ip_addre2_13_0_, persistent0_.token_date as token_da3_13_
0_, persistent0_.token_value as token_va4_13_0_, persistent0_.user_id as user_id6_13_0_, persistent0_.user_agent as user_age5_13_0_, user1_.
id as id1_14_1_, user1_.created_by as created_2_14_1_, user1_.created_date as created_3_14_1_, user1_.last_modified_by as last_mod4_14_1_, u
ser1_.last_modified_date as last_mod5_14_1_, user1_.activated as activate6_14_1_, user1_.activation_key as activati7_14_1_, user1_.email as
email8_14_1_, user1_.first_name as first_na9_14_1_, user1_.lang_key as lang_ke10_14_1_, user1_.last_name as last_na11_14_1_, user1_.login as
 login12_14_1_, user1_.password_hash as passwor13_14_1_, user1_.reset_date as reset_d14_14_1_, user1_.reset_key as reset_k15_14_1_ from jhi_
persistent_token persistent0_ left outer join jhi_user user1_ on persistent0_.user_id=user1_.id where persistent0_.series=?
2016-07-15 14:51:27.009 DEBUG 7548 --- [nio-8080-exec-2] j.s.s.CustomPersistentRememberMeServices : No persistent token found for series id:
 /Xj2mGLWdBjuIhGF1M79Aw==
2016-07-15 14:51:27.016 DEBUG 7548 --- [nio-8080-exec-2] j.s.s.CustomPersistentRememberMeServices : Cancelling cookie

**Comment by minu-jain** [comment]
The code is picking application.yml file . How can I make it point to application-dev.yml

**Comment by deepu105** [comment]
Please follow our [guidelines ](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#issue) when opening issues if you want us to help you.
For bug reports please follow the template pre populated [here](https://github.com/jhipster/generator-jhipster/issues/new)
Open a new issue with proper details or update this issue with all details and request to re open.
Issues opened without proper details will be closed without explanation.

please update the issue with all the required details or it will be closed.

**Comment by minu-jain** [comment]
Hi Rudell,

Can u try by downloading the sample project  "jhipster-sample-app-master" that is uploaded in github..
I am doing that way only.

There is some proxy issue it seems at my end due to which I am not able to download the project the way you are doing.

Thanks!

**Comment by minu-jain** [comment]
Hi Rudell,

Thanks.
The issue is solved.

Issue was the gulp and bower were not properly installed.

Regards,
Minu
