### ISSUE TITLE
[FEATURE] Locale Entities internalization

### ISSUE THREAD

**Issue by sarrek** [jhipster/generator-jhipster#3847]
##### **Overview of the issue**

Add type " Localized " to jhipster entities.

##### **Motivation for or Use Case** 

This is not a bug to be, but you do not give the possibility to create Collections / Vector / or Map.

##### **JHipster Version(s)** 

Last one 3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "mandefa",
    "packageName": "com.matajo.mandefa",
    "packageFolder": "com/matajo/mandefa",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "803ef351e2ac3e6e83ba4339694c0558ead9517c",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

No ...

##### **Browsers and Operating System** 

Chrome and Firefox
##### **Reproduce the error** 

It's a suggestions

##### **Related issues** 
///

##### **Suggest a Fix** 

Look at this : https://github.com/malkusch/localized

I have implemented some parts ...
[patched-svn.txt](https://github.com/jhipster/generator-jhipster/files/366843/patched-svn.txt)

**Comment by deepu105** [comment]
I dont think we will be doing this as you are the first one to ask for
this. We cant spend time and effort on maintaining something thats not
useful to most people. We handle i18n differently and it works very well at
the moment. Hence i dont find a need for this. If you want you can go ahead
and implement a jhipster module to do this and anyone interested can very
well use your module.

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
Im sorry btw
