### ISSUE TITLE
Translation not removed from Enum HTML

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#3851]
##### **Overview of the issue**
When generating an entity with the Enum type, translation is not removed by the [regex via stripHtml](https://github.com/jhipster/generator-jhipster/blob/53afa6de1e6a10dc059c65c58c314784a35eb6d8/generators/generator-base.js#L858).  Translate attributes can be found in `foos.html` and `foo-detail.html` around the entity's Enum value.

`            <span translate="{{'notransApp.Specialty.' + vm.foo.specialty}}">{{vm.foo.specialty}}</span>`

##### **JHipster Version(s)** 
3.0.0+

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "notrans",
    "packageName": "com.mycompany.app",
    "packageFolder": "com/mycompany/app",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "f117103c1108a6288bbd7171c1ac2cc52c8c71e4",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
```
{
    "relationships": [],
    "fields": [
        {
            "fieldName": "specialty",
            "fieldType": "Specialty",
            "fieldValues": "Cardiology,Immunology,Dermatology"
        }
    ],
    "changelogDate": "20160719000929",
    "dto": "mapstruct",
    "service": "serviceClass",
    "entityTableName": "foo",
    "pagination": "pagination"
}
```
##### **Reproduce the error** 

- Generate a project with translation disabled
- Generate an entity with an Enum field

##### **Suggest a Fix** 
Should the translate regex pick this up, or should we add <% if (enableTranslation) { %> around the translate attribute?

**Comment by deepu105** [comment]
The regex needs modifications to pick this up and we need to make sure it
doesn't break current filtering. The regex was hard to get right earlier.
But im not an expert in regex so if you know regex well then plz feel free
to update it.

Thanks & regards,
Deepu
