### ISSUE TITLE
Problem with Hystrix and Microservice generated with Jhipster

### ISSUE THREAD

**Issue by samshay** [jhipster/generator-jhipster#3856]
I have created a Microservice with Jhipster and i want to add hystrix, but i have a problem.
I had @EnableHystrix on my ***ServiceApp.java, and @HystrixCommand on method (@RequestMapping).
But when i want to access on http://localhost:8081/hystrix.stream (it's the good port), i this page 
"Your request cannot be processed"

I do not know from where it comes, security problem, but i can't success solve ...

Thanks for your help.
Sorry for my bad english

**Comment by jdubois** [comment]
Please follow our guidelines, this isn't a bug -> please use Stackoverflow with the "jhipster" tag

**Comment by samshay** [comment]
Hy, 
I understand, it's not a bug, but i just want use hystrix dashboard, and i don't undestand why it does not work with a jhipster microservice ?

**Comment by gmarziou** [comment]
This is an issue tracker, it's not the right place for questions, please use stackoverflow or gitter.

**Comment by SebastienRene** [comment]
Not a bug, just configuration =)

http://stackoverflow.com/questions/38503549/jhipster-microservice-and-hystrix/38531666#38531666
