### ISSUE TITLE
[FEATURE] DRY application.yml

### ISSUE THREAD

**Issue by systemsplanet** [jhipster/generator-jhipster#3857]
##### **Overview of the issue**

Most of the configuration in application-dev.yml and application-prod.yml are duplicates.
My my case, out of 100 lines, 90 are duplicates.
The duplicate lines should be moved to an app-common.yml shared file.

##### **Motivation for or Use Case** 

To be DRY
To eliminate copy-paste errors
To make git diffs easier to read

##### **Suggest a Fix** 

If the build finds an app-common.yml file, it consumes it, applying any properties it finds.
Then it applies the profile application-xxx.yml to override the common settings. 

This is backward compatible. Existing configurations work as normal.
New configurations can take advantage of app-common.yml at any time.

The contents of application-dev.yml and application-prod.yml 
will then be very small and only contain the changes to 
app-common.yml needed for the active profile.

**Comment by ruddell** [comment]
Is the application.yml found in the same folder what you want?  What lines do you think should be moved there?

The point in having the two different files is for when you customize the environments, for example H2disk and MySQL have very different setups.  Caching, email, logging settings, etc also differ in my environments.

**Comment by jdubois** [comment]
Currently we "repeat" two types of configuration:

- The standard Spring Boot configuration properties that should be different between `dev` and `prod`.  For example, the datasource or the Spring Boot devtools
- The JHipster-specific configuration properties: same idea as the Spring Boot configuration, we only write those which should be different in `dev` and `prod`, for example your JWT secret token

So the current setup looks "DRY" to me. I agree some properties could be removed, like the `spring.mail.port`, as this is probably `25` both in `dev` and `prod`, but in my usual setup I'd be surprised to have 90 lines similar between `dev` and `prod`.

The `app-common.yml` you refer to already exists, that's the `application.yml` file, and indeed you should move your common configuration there.

I'm closing this as I really don't find that many duplicates, maybe you could list them in detail so we can discuss them one by one?

**Comment by systemsplanet** [comment]
I misread the comment in application.yml:
       This configuration will be overriden by the Spring profile you use,
       for example application-dev.yml if you use the "dev" profile.

I took that to mean when you build the dev profile, the build will perform a 
    copy application-dev.yml application.yml
so the application.yml would be overriden (not inherited).  Now I understand you meant the properties will override the ones in application.yml.  Maybe adding this verbage would help clarify:

    "This file contains the JH properties common to all profiles. All properties added here will be inherited by the active profile, for example application-dev.yml. The active profile may easily override any of these properties by simply including their own copy of the propery name with a different property value."



In the first JH app I created, there were only 13 out of 87 lines different between prod and dev as you can see in these screenshots. 

![image](https://cloud.githubusercontent.com/assets/660529/17007416/9c99a6cc-4eb6-11e6-9ae6-e1d14320d94d.png)

![image](https://cloud.githubusercontent.com/assets/660529/17007458/f0cecaba-4eb6-11e6-9f8e-252980e3e238.png)



I would think all the lines below only need to appear in application.yml. To eyes new to JH, it seems redundant. However, I can certainly understand your argument that they belong in both. I  can move them myself for my app. No problem, Thanks


# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    devtools:
        restart:
        livereload:
    datasource:
        name:
        password:
    jpa:
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:

liquibase:

server:
    port: 8080

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: cb00e3ab9d4d90a5d022c05b1a8a7713c3639b56
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: ASDLC@localhost
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: ASDLC
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512

**Comment by deepu105** [comment]
This could be similar or different based on your config and project some
people might have different properties for all those keys. So better to
leave it as it is and let the user decide.

Thanks & regards,
Deepu

**Comment by noel-yap** [comment]
I'm also looking for a way to keep YML files DRY. In our case, we have two projects in which we would like to share the same settings for some of the properties. I was thinking `spring.profiles.include` might be of some use in our situation but I'm not seeing exactly how it would be done.

**Comment by jdubois** [comment]
This is a very old ticket, and now I also understand better the issues with those .yml files. In fact, we should repeat more things!!! My issue is that you can't override one configuration with its default value anymore.

For example: if you put a your SMTP port to `2525` in `application.yml`, then you can't get the default value in any profile anymore. So it's probably better to repeat those configurations in several profiles, rather than put them once in the main configuration.

Also, we should have more "smaller" profiles that we can group together.

This is one the many things I want to work on for JHipster 7.

**Comment by gmarziou** [comment]
One way to share between 2 apps is to use a Spring Cloud Config Server like JHipster registry.
