### ISSUE TITLE
Generated detail page for many to many doesn't work with String IDs

### ISSUE THREAD

**Issue by mwhitis** [jhipster/generator-jhipster#3858]
##### **Overview of the issue**

This seems to be an issue with angular usage of double braces `{{}}` vs. single braces`{}`.

I've got a many to many association that I defined in JDL and imported.  One of the sides has a string primary key.  I've gone through and modified all of the relevant server-side code to use the string.

The generated angular pages work fine for all pages for both sides with one exception.  The links on the non-string entity are not generated properly for anything that has a text key. 

Looking at the difference between the angular directives in the list page of the String Key, and the Detail page of the non-string key, I noticed that there are different angular directives being used:

List Page of String Key (works fine):

`<a ui-sref="aspera-product-detail({id:asperaProduct.id})">{{asperaProduct.id}}</a>`

Detail Page of non-String Key (does not work for keys with text)
`<a ui-sref="aspera-product-detail({id:{{product.id}}})">{{product.id}}</a>`

The difference is that the List page that works uses the json object single brace syntax whereas the non-working detail page uses the double brace angular evaluation syntax.

Note that the double brace syntax works fine for my number - number associations as well as String Ids that are fully numeric.

##### **Motivation for or Use Case** 

Not able to browse across the association.

##### **JHipster Version(s)** 

3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
[yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/374510/yo-rc.json.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
[Application.json.txt](https://github.com/jhipster/generator-jhipster/files/374509/Application.json.txt)
[AsperaProduct.json.txt](https://github.com/jhipster/generator-jhipster/files/374508/AsperaProduct.json.txt)

##### **Browsers and Operating System** 
Windows 10 - All Browsers

##### **Reproduce the error** 

Import the attached JDL.
Modify the liquibase, entity, etc. for AsperaProduct to have the Id field be a String.

##### **Suggest a Fix** 

Recommend evaluating the possibility of switching the template to use the single brace syntax for the detail page rather than the double brace.

**Comment by deepu105** [comment]
You seem to have modified a lot here and I dont think we should generate that syntax at all, check what you have modified and you can submit a PR to remove the double brace if you would like so.
