### ISSUE TITLE
jhipster microservice memory footprint

### ISSUE THREAD

**Issue by malikhan5049** [jhipster/generator-jhipster#3860]
##### **Overview of the issue**

I have create microservices architecture using jhipster which is using 
uaa for authentication
hazelcast for entities cache

then i build the image for the service and run a container from that the problem is the container for a microservice is talking > 2.5 GB of memory and i am trying to figure out why need help

##### **Motivation for or Use Case** 

this is not a bug but a performance issue

##### **JHipster Version(s)** 

1.8.4

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "jobsapi",
    "packageName": "asdf",
    "packageFolder": "casdf,
    "serverPort": "13783",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
   
    "buildTool": "maven",
    "jwtSecretKey": "86aca8f6e75e2d387073bcb29082491c827ab9dbasdfasdf",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

didnt create any yet

##### **Browsers and Operating System** 

OS is ubuntu 16.04 LTS

##### **Reproduce the error** 

generate microservice with uaa authentication/hazelcastcase/elasticsearch

**Comment by gmarziou** [comment]
Have you read this? https://github.com/jhipster/generator-jhipster/issues/3791

**Comment by malikhan5049** [comment]
looking at it looks like giving jvm memory argument will solve the problem but if so shouldnt it be part of jhipster code generation?

**Comment by malikhan5049** [comment]
I got my problem resolved by giving jvm heapsize arguments in relevant docker files kindly make it part of code generation

**Comment by gmarziou** [comment]
Well so far, we have considered it should be only documented and as you may have seen the PR #283 is waiting for approval.

**Comment by jdubois** [comment]
And the PR has just been merged :-)

**Comment by jdubois** [comment]
Sorry I should have put more comments!

This of course depends on your exact conf, but if you have a distributed cache (depends of the size of the cache, but if you have one you're expecting to put data in it!), and Elasticsearch (is it embedded or not?), and no specific tuning, this doesn't look too strange to me.

Please remember that UAA is in total BETA, I don't even know if this works, so feedback and help are highly appreciated, but you can definitely have issues here.

**Comment by malikhan5049** [comment]
currently i ve just created microservices project with hazelcast cache
currently no even created any entity yet with elastic search enabled for
each component didnt do any configuration for cache and elastic search yet
currently putting jvm heap arguments in docker file works for me
