### ISSUE TITLE
docker compose up service hangs not starting dependencies first e.g. jhipster-registery

### ISSUE THREAD

**Issue by malikhan5049** [jhipster/generator-jhipster#3863]
##### **Overview of the issue**

I am trying to run one microservice with docker-compose up servicename command but it is not starting up its dependencies first and the service hangs trying to connect with registry eventually dies 

##### **Motivation for or Use Case** 

should be able to start individual service with its dependencies

##### **JHipster Version(s)** 

1.8.4

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.0",
    "baseName": "activitimvcapi",
    "packageName": "com.lollibond.seahorse.activiti",
    "packageFolder": "com/lollibond/seahorse/activiti",
    "serverPort": "13786",
    "authenticationType": "uaa",
    "uaaBaseName": "uaaserver",
    "hibernateCache": "hazelcast",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "34e86d8ddb876428058f2f3279aff43f4c4c2a82",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

no entities
##### **Browsers and Operating System** 

ubuntu 16.04

##### **Reproduce the error** 

create microservice architecture with uaa server, gateway and some services
generate docker-compose configuration using yo jhipster:docker-compose
cd into docker folder 
try to run something like docker-compose up servicename
it will hang trying to search for registry which is not started by docker

**Comment by pascalgrimaud** [comment]
At the moment, I don't think the docker-compose works with uaa server, because there is no docker-compose file generated for the uaa server => I need to check it, to confirm what I said :)

**Comment by malikhan5049** [comment]
uaa server is in beta you can create but but that is not the point point is it is starting up docker services individually with its dependencies it is starting up the whole system though i mean docker-compose up working fine but not docker-compose up servicename

**Comment by ruddell** [comment]
@malikhan5049 to start up just a single service, you can run that service's app.yml:
 `docker-compose -f src/main/docker/app.yml up`  The docker-compose.yml file from the subgenerator is for running all of the projects you selected in the subgenerator.  Everything is documented http://jhipster.github.io/docker-compose/

If you are running just a single microservice/gateway, you currently need to add the following to src/main/docker/central-server-config/application.yml so it can register with the JHipster Registry correctly (#3848):
```
 eureka:
     client:
         serviceUrl:
             defaultZone: http://admin:admin@registry:8761/eureka/
```

I'm not sure how this works with UAA, I haven't tested that part yet.

**Comment by jdubois** [comment]
There isn't support for UAA with Docker Compose, so this just not going to work.
UAA is in BETA, it's not even documented -> there is no support for Docker Compose yet, as this needs to be out of beta first

**Comment by sdoxsee** [comment]
In case people are having trouble starting up the UAA flavour of jhipster microservices (as stackoverflow indicates) I've posted an answer with a screencast for how to start it up (without docker-compose): http://stackoverflow.com/a/38624600/1098564
