### ISSUE TITLE
"import-jdl" subgenerator is not generating correct imports

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3871]
This is using JHipster 3.5.0, where the "import-jdl" sub-generator is back.

- Using the default JDL Studio sample application (the Oracle HR application)
- With JHipster UML -> everything works fine
- With the "import-jdl" sub-generator, the "jsonignore" imports are not imported

It looks like the `importJsonignore` variable is not correctly set up when using the "import-jdl" sub-generator, which ends up with missing imports.

-> this is very easy to correct for an end-user (just import the missing class), but it's a major issue for us as there is a compilation error on first run, for a fresh project using our sample application. So that's really a bad first experience with JHipster for new users.
-> Easy work-around is to use JHipster UML directly

@MathieuAA @deepu105 I know you worked on this, do you have any idea about this bug? I will have time until Monday afternoon, after that I won't have Internet access for one week, so if we do an emergency release it should be pretty quick

**Comment by MathieuAA** [comment]
This is weird. JUML uses JHipster (plain ol' `yo jhipster:entity <NAME>`) to generate entities. @deepu105, how does the generator do it?
I see [this](https://github.com/jhipster/generator-jhipster/blob/master/generators/import-jdl/index.js#L54) so I think you use the generator directly instead of the command, am I right?

**Comment by deepu105** [comment]
@MathieuAA its equivalent of using the command directly. Thats not the issue.
Seems like the issue is with the ejs imports not being used when an entity is being generated from json file. Im getting the same issue when i run `yo jhipster:entity` on any json. looking further into it

**Comment by deepu105** [comment]
OK I found the issue. Seems like its coming from the jhipster-core. ill push a fix immediately.

**Comment by deepu105** [comment]
@MathieuAA can you do a patch release please, may be along with fix for https://github.com/jhipster/generator-jhipster/issues/3870

**Comment by deepu105** [comment]
ill push a lib update for jhipster as soon as the core patch is released

**Comment by deepu105** [comment]
Im ashamed that I didnt do an `mvn test` when doing this earlier :(

**Comment by jdubois** [comment]
I'll be able to do a patch release during the week-end, just ping me when you're ready

**Comment by MathieuAA** [comment]
Where is the issue? 

Le 22 juillet 2016 18:31:59 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>OK I found the issue. Seems like its coming from the jhipster-core. ill
>push a fix immediately. 
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/3871#issuecomment-234591546

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
look at the commit above

**Comment by MathieuAA** [comment]
If everything works, can you make a quick patch release? 

Le 22 juillet 2016 18:31:59 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>OK I found the issue. Seems like its coming from the jhipster-core. ill
>push a fix immediately. 
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/3871#issuecomment-234591546

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
@MathieuAA you havent added me as npm colloborator in the project

**Comment by MathieuAA** [comment]
Really? I thought I did. Sorry. Releasing v1.1.2 (I think) in 5 minutes.

**Comment by deepu105** [comment]
can you also add me to the npm project

**Comment by MathieuAA** [comment]
What's your NPM name Deepu?

**Comment by deepu105** [comment]
deepu105


Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
Done, I'll release in a bit... just need to add one more test.

**Comment by MathieuAA** [comment]
v1.1.2 is released.

**Comment by deepu105** [comment]
@jdubois I have tested with the sample JDL from the studio and all seems good. In either case please check once if you have time coz another set of eyes are always better
