### ISSUE TITLE
[QUESTION] How to access Hystrix Dasboard from Gateway

### ISSUE THREAD

**Issue by vfonsecapv** [jhipster/generator-jhipster#3872]
There's any route for circuit or hystrix on gateway?

**Comment by jdubois** [comment]
Can you ask your question on StackOverflow? This is the bug report system, and we do not have Hystrix Dashboard officially supported yet

**Comment by gmarziou** [comment]
Hint: have a look at this question on SO: https://stackoverflow.com/questions/38503549/jhipster-microservice-and-hystrix
