### ISSUE TITLE
Question Microservices

### ISSUE THREAD

**Issue by chrislovecnm** [jhipster/generator-jhipster#3878]
Does jhipster have options to not include Eureka and Elasticsearch in a microservice?  I don't think Eureka is needed for discovery within kubernetes.  Trying to build a simple example of service that includes swagger, without Elastic or Eureka.

**Comment by deepu105** [comment]
Elasticsearch is optional, you can choose not to enable that during generation.
Unfortunateley Eureka is not optional.

@PierreBesson do you have a commnet on it?

**Comment by chrislovecnm** [comment]
@deepu105 is just pulling the Eureka framework applicable?  And where is the doc on making elastic optional? Did I miss it in the setup?  Also was there a reason this was closed?

**Comment by ruddell** [comment]
@chrislovecnm When generating a microservice, there is a prompt with the default value of No:
```
? (10/16) Do you want to use a search engine in your application? (Use arrow keys)
❯ No 
  Yes, with ElasticSearch 
``` 
I'm assuming @deepu105 hit the `Close and comment` button instead of `Comment` so I'll reopen this for discussion (correct me if I'm wrong please).  

I can't comment on the removal of Eureka, not sure if that works with our current setup and our Kubernetes support is in early beta.

**Comment by jdubois** [comment]
- yes Elasticsearch is optional, it's just a question -> have a look at the doc
- no Eureka can't be removed, the whole stack relies on it -> or you need to recode everything, and we can't support everything. Only thing that could be added in the future is support for Consul.

**Comment by PierreBesson** [comment]
@chrislovecnm
Eureka is not intended to be optional at the moment as our approach of the microservice architecture heavily depends on the Netflix stack: Hystrix, Ribbon, etc. And service discovery is very important to easily use those features.

In the future we might consider allowing to replace Eureka by Consul (using Spring Cloud Consul) or even Kubernetes' own service discovery (see https://github.com/fabric8io/spring-cloud-kubernetes and https://github.com/spencergibb/spring-cloud-kubernetes).

In the meantime you should be able to disable Eureka client discovery with:

eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false

**Comment by chrislovecnm** [comment]
Yanking the eureka dependencies for a simple rest microservice was pretty trivial. I understand the discovery pattern that you are using utilizes eureka, but I cannot justify running a discovery service on top of a platform that has discovery ;)  Does spring cloud have a eureka service? Just wondering if discovery could be uncoupled.

Only using simple rest microservice without the gateway.  So at this point unhooking eureka is simple.  Thanks for the pointer to spring-cloud-kubernetes stuff! 

Anyone know if someone could uncouple eureka with an abstraction layer? Gotta be a library out there ;)

**Comment by deepu105** [comment]
I closed it by intention :) coz this wasn't an issue or feature request and
ideally should be in SO. May be I should have mentioned it.  No worries
anyway.

Thanks & regards,
Deepu
