### ISSUE TITLE
Jhipster-Microservices-Error while trying to connect a microservice from IDE to jhipster registery running in docker container

### ISSUE THREAD

**Issue by malikhan5049** [jhipster/generator-jhipster#3882]
##### **Overview of the issue**

I have created my microservices infrastructure with jhipster and what i am trying to do is say we have 3 micro services and in a dev environment i need to run two micro services inside docker containers and 1 service in my local IDE the problem i am facing is the services running in containers are able to register themselves in registry but service running on IDE failed with exception "java.net.UnknownHostException: registry: unknown error", PFA my configurations;

docker-compose file has one service commented which i am trying to run through IDE
you can find configuration files for microservice in microservice folder

[local microservices.zip](https://github.com/jhipster/generator-jhipster/files/383943/local.microservices.zip)

##### **Motivation for or Use Case**

N/A

##### **Reproduce the error**

generate jhipster gateway app with JWT authentication
generate microservices using JWT authentication
create docker folder and run yo jhipster:docker-compose to generate unified docker-compose file
add port forwarding in services defined in docker-compose yml so that you should be able to connect to say database etc using these ports

##### **Related issues**

N/A

##### **Suggest a Fix**

N/A

#### **JHipster Version(s)**
1.8.4

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

[yorcjson.zip](https://github.com/jhipster/generator-jhipster/files/383951/yorcjson.zip)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
N/A

##### **Browsers and Operating System**

ubuntu 16.04

also i am seeing discoverycomposite - eureka as unknown in jhipster registry http://www.awesomescreenshot.com/image/1426508/685d8bc12ee582038c29ac79faa3f1cf

**Comment by ruddell** [comment]
@malikhan5049 Did you change the application-dev.yml for the IDE microservice to point to the docker IP instead of localhost?  

The property to change is eureke.serviceUrl.defaultZone, for me Docker uses 192.168.99.100 so it would be `http://admin:admin.@192.168.99.100:8761/eureka/` (also change the password to what you set in the docker-compose subgenerator).

**Comment by jdubois** [comment]
Closing this as we didn't have an answer -> I think @ruddell is correct
