### ISSUE TITLE
generator-jhipster separate client with server

### ISSUE THREAD

**Issue by kurt1993** [jhipster/generator-jhipster#3884]
Hello,
I work on a project with jhipster where I 'm supposed to separate my back and my front. I do that by typing the command yo jhipster:client and yo jhipster:server but the performance I get the following error:

Votre demande ne peut être traitée
Désolé, une erreur s'est produite.

Status: Not Found (Not Found)
Message: No message available
Autres suggestions :
Rechercher sur localhost:9000 :

I wonder if I should actually separate the two parts of my project into different folder or just put them in the same folder as for a while.

Thank you.

**Comment by gmarziou** [comment]
This is not an issue, please use stackoverflow or gitter to ask questions.
