### ISSUE TITLE
Heroku generator fails on data.search is not a function

### ISSUE THREAD

**Issue by jkutner** [jhipster/generator-jhipster#3885]
The Heroku generator is failing on this error:

```
Creating Heroku application and setting up node environment
heroku create fooasdfh-334343 --addons heroku-postgresql
/Users/jkutner/workspace/heroku/kissaten/jhipster-example/node_modules/generator-jhipster/generators/heroku/index.js:191
                if (data.search('Heroku credentials') >= 0) {
                         ^

TypeError: data.search is not a function
    at .<anonymous> (/Users/jkutner/workspace/heroku/kissaten/jhipster-example/node_modules/generator-jhipster/generators/heroku/index.js:191:26)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20)
```

I'll investigate this, but wanted to track it here in case anyone else runs into it.

**Comment by jkutner** [comment]
It looks like this is fixed in master. But I don't know what did it. Maybe 5af57a6f475a4a91ac417b011c1f14cfa5fd5787

Anyways, can we get a release out to fix this?

**Comment by ruddell** [comment]
@jkutner There was a release four days ago so that commit should be in the latest version.

I couldn't reproduce the error with v3.5.1

**Comment by jkutner** [comment]
@ruddell thanks for the info! there must be something in my local env that's causing this. I will close and continue to investigate.
