### ISSUE TITLE
Numbers in a project name cause Java compilation issues

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#3889]
If I choose `21points` as my application base name, there's compilation problems. For example:

```
:compileJava
/Users/mraible/dev/21-points/src/main/java/org/jhipster/health/21PointsApp.java:27: error: <identifier> expected
public class 21PointsApp {
```

I'd suggest reverting to the previous behavior, where `Application` is used. I'll create a PR.

**Comment by gmarziou** [comment]
Why not fixing the issue by rejecting wrong names.?

**Comment by gmarziou** [comment]
Simple regexp "[A-Za-z_$]+[a-zA-Z0-9_$]*" would be enough.

**Comment by gzsombor** [comment]
+1 for regexp :-)

**Comment by gmarziou** [comment]
Original discussion for change:  https://github.com/jhipster/generator-jhipster/issues/2868

**Comment by sendilkumarn** [comment]
Let the app name be anything, why we need to restrict it?
It would be better if we just remove the numbers if it starts with number.

like `21Points` -> `points` or even `points21`

P.s - Don't feel great about restricting users [personal opinion]

**Comment by wmarques** [comment]
@sendilkumarn Agree with that but if we rename the app maybe we should inform the user at least, like "21points will be renamed as points21 for class naming, do you agree?"

**Comment by sendilkumarn** [comment]
💯 that should be the case `warning` message.

**Comment by jdubois** [comment]
Naming it "Application" is good to me -> at least it's the name everywhere,
so it helps in automation and in documentation. And as it's in the root
package what it does is quite clear.

Le 28 juil. 2016 10:27 AM, "Sendil Kumar N" <notifications@github.com> a
écrit :

**Comment by gmarziou** [comment]
See my proposed alternative PR to fix the issue while retaining the JHipster 3;x application naming which is very convenient in the context of microservices.
