### ISSUE TITLE
import-jdl sub-generator not creating correct entity configurations with microservice + gateway usage

### ISSUE THREAD

**Issue by wired00** [jhipster/generator-jhipster#3899]
##### **Overview of the issue**

Entity Configurations are not being generated correctly for scenerio using microservice & gateway.

Receiving error `ERROR! Microservice name for the entity is not found. Entity cannot be generated!` when running `yo jhipster:entity <entity name>` from microservice gateway. 

This is due to the entity configuration json file created using JDL import populating microservice element as `"microservice": "<entityname>"` instead of `"microserviceName": <entityname>"`. 

After manually changing, entity import to gateway works perfectly.

##### **Reproduce the error**

- create JDL file containing :
```
entity User {
    name String
    updatedAt LocalDate
}

microservice * with mymicroservice
```
- save JDL file as `mymicroservice.jh`
- create test jhipster project named `mymicroservice` in fresh directory `yo jhipster` 
- once created, import entity via jdl `yo jhipster:import mymicroservice.jh`
- observe the auto generated .jhipster/User.json - `cat .jhipster/User.json`
- It now contains `"microservice": "mymicroservice"`. Which is wrong. It will not work with a gateway based sub generator creation. 

To test:
- Create a new directory and generate new jhipster `Gateway Application` type.
- cd to gateway directory
- run `jhipster:entity user`, point to your `mymicroservice` directory.
- you will receive error `ERROR! Microservice name for the entity is not found. Entity cannot be generated!`
- Now modify the /mymycroservice/.jhipster/User.json so that it reads `"microserviceName": "mymicroservice"`
- retry `jhipster:entity user` for the gateway
- it will succeed.

##### **Suggest a Fix**

- The generated entity json file (in this case `User.json`) should generate with json value of 
`"microserviceName": "<entityname>"` instead of `"microservice": <entityname>"

- Manually adding an entity to the microservice via manual sub-generator `jhipster:entity user` works to create the correct entity json, only using import JDL does not work

##### **JHipster Version(s)**

`3.5.1`

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "classificationservice5",
    "packageName": "com.pavilionhealth.classificationservice",
    "packageFolder": "com/pavilionhealth/classificationservice",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "jwtSecretKey": "88c66cdf9545f0e5d9986ced583aaf4363294e49",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true
  }
}```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
```{
  "relationships": [],
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    },
    {
      "fieldName": "updatedAt",
      "fieldType": "LocalDate"
    }
  ],
  "changelogDate": "20160729013701",
  "entityTableName": "user",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "microservice": "mymicroservice"
}```

**Comment by ruddell** [comment]
This was recently fixed in jhipster-core (https://github.com/jhipster/jhipster-core/issues/41), but a release of both jhipster-core and generator-jhipster will be needed to fix it.

**Comment by wired00** [comment]
Great thanks for prompt reply @ruddell, that certainly looks the same issue, should this be closed?

**Comment by deepu105** [comment]
Keep it open for tracking, ill update the core version here once its released and will close it

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/commit/a08ec7c8b4dc547fbb564363f329d84379b00661

**Comment by jlopezjuy** [comment]
hi, im using jhipster 4.1.1, im create microservice app and "microserviceName": "microservicename" not in json file of entity, this is ok?

**Comment by rosefirefish** [comment]
I am not sure if I am doing everything correctly, but, it seems that with 4.6.1 and 4.6.2, jhipster import-jdl does not add the microserviceName into the .EntityName file...

**Comment by gmarziou** [comment]
@rosefirefish please don't comment on a one year old closed  issue, please open a new one with required details

**Comment by hermeslm** [comment]
@jlopezjuy and @rosefirefish you may check if you are specifying this option in JDL definition as micorservice app:

`microservice * with mymicroservice`

because jhipster:import will omit "microserviceName" property in your generated entities and jhipster-generator will fails.
