### ISSUE TITLE
Keytool command used in generateKeyStore doesnt work in windows

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3903]
The `keytool` command is used for UAA server option in `generateKeyStore` method of `generator-base.js` its not cross platform as the command needs to be executed from the jdk/jre bin folder. not sure if this is applicable for mac and linux @jhipster/developers can anyone check

@sdoxsee since this is from you could you check?

**Comment by sdoxsee** [comment]
Sorry about that. I'm on osx. Shouldn't it work in Windows if the jdk bin folder is set in PATH?

**Comment by deepu105** [comment]
but normally only the JDK folder will be set when you install jdk I guess

**Comment by deepu105** [comment]
In windows oracle uses `C:\ProgramData\Oracle\Java\javapath` as path which has symlinks for `java.exe` and few other binary, it doesnt have keytool in it. 
I dont know if similar issue could exist in default setup(if you havent set the java bin path manually) for osx or linux

may be we could get JAVA_HOME and execute keytool against bin from there

**Comment by sdoxsee** [comment]
I was considering the same thing. We probably shouldn't expect java (or
keytool) on the path so using keytool relative to java_home should do it.
I'll PR in a few days. Thanks!
