### ISSUE TITLE
Database metrics missing in metrics page

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3905]
The metrics page used to have some stats and metrics for database earlier.

But on the current master it seems to be missing for a default app

Might have something to do with recent spring boot updates. need to investigate further

**Comment by jdubois** [comment]
I don't know the reason, but the Metrics gauge has been renamed from `HikariPool-0` to `HikariPool-1`.
I'm doing the PR -> but this should be ported to ng2 also

**Comment by deepu105** [comment]
cc @wmarques since he is migrating the health & metrics page

**Comment by jdubois** [comment]
I'm cherry-picking the change and also updating the ng2 page, no need to do it @wmarques :-)

**Comment by jdubois** [comment]
Done, and I linked the commits to this ticket.
