### ISSUE TITLE
Querydsl tip doesn't work with current setup

### ISSUE THREAD

**Issue by cm325** [jhipster/generator-jhipster#3908]
##### **Overview of the issue**

The querydsl tip here:

https://jhipster.github.io/tips/003_tip_add_querydsl_support.html

doesn't actually work with the current jhipster setup. 

##### **Motivation for or Use Case**

1. The tip uses querydsl 4 configuration, but that depends on spring data jpa 1.10, which isn't bundled until spring boot 1.4, and jhipster is still at 1.3.5. So really, by default, the tip needs to link to the 3.6.3 version of the querydsl docs. The 3.6.3 dependencies also require more than just a different version, because packages were renamed between v3 and v4. The right doc link for maven integration would be: http://www.querydsl.com/static/querydsl/3.6.3/reference/html_single/#d0e128

2. Regardless of the version of the querydsl docs you look at, they all suggest that for maven you add the slf4j-log4j12 dependency, but spring boot already has the log4j-over-slf4j dependency, so that borks the build, and you have to remove it to get the build to succeed. 

3. There's also a typo in the code example

`public interface NameRepository extends MongoRepository<Name, String>, **QuerydslPredicateExecutor**<Name> {`

it should be:
 
`public interface NameRepository extends MongoRepository<Name, String>, **QueryDslPredicateExecutor**<Name> {`

##### **Suggest a Fix**

Until jhipster is on spring boot 1.4, the querydsl version needs to be downgraded, and the other problems above just need to be either mentioned or fixed

##### **JHipster Version(s)**

3.4.1

**Comment by atomfrede** [comment]
All tips are provided by jhipsters users. Maybe the original author @omrzljak can have a look and update the tip according to your findings.

**Comment by jdubois** [comment]
Yes @atomfrede is right. If the tip isn't corrected, we might delete it in the end, as we are not going to support this anyway.

**Comment by omrzljak** [comment]
I wil try to update it. But I agree also if you decide to delete it.

**Comment by deepu105** [comment]
If you can update it then no need to delete. We will remove only obsolete
items

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
Yes if anybody is ready to update, please do it -> it's quite easy, and it looks like it's useful to many people.

**Comment by cm325** [comment]
Just to update this, now that jhipster 3.6.1 is out, and spring boot has been upgraded to 1.4, which comes along with spring data jpa 1.10, the changes needed to this tip a more minor. You still need to exclude the suggested slf4j-log4j12 maven dependency, and there is still that typo, but that's not such a big deal. Before, given the packages were entirely off, it led to a whole host of problems-

**Comment by jdubois** [comment]
I corrected the typo with https://github.com/jhipster/jhipster.github.io/commit/b2feb7754405ceb3ab86772354dd6bd2fa64a3fc

However I don't understand where the `slf4j-log4j12` needs to be excluded, could you do a PR on the project for that?

**Comment by jdubois** [comment]
This has been broken for a long time, and I have no idea what to do... So I'll remove the tip in a couple of days
