### ISSUE TITLE
[impor-jdl] On OneToMany relationships, liquibase 'referencedTable" tag does not get table's specific name

### ISSUE THREAD

**Issue by luizmiranda7** [jhipster/generator-jhipster#3909]
##### **Overview of the issue**

Once you have a bidirectional OneToMany relationship, the tag "referencedTable" does not get table's specific name

##### **Motivation for or Use Case**

JDL .json file
```
entity A (mark_a) {}
entity B (mark_b) {}

relationship OneToMany {
    A(b) to B(a)
}
```
Liquibase generated:

```
        <addForeignKeyConstraint baseColumnNames="a_id"
                                 baseTableName="mark_b"
                                 constraintName="xxxxxx"
                                 referencedColumnNames="id"
                                 referencedTableName="a"/>
```

##### **Reproduce the error**

Cannot be reproduced by jsfiddle.

##### **JHipster Version(s)**

v3.5.1

**Comment by deepu105** [comment]
This is fixed in the current master, will be available in next release.
