### ISSUE TITLE
Can a gateway run without a database ?

### ISSUE THREAD

**Issue by MBenali** [jhipster/generator-jhipster#3919]
Hi everyone,

**We use a LDAP authentication instead of a login/password authentication, thus we have to remove our gateway database.**
We can already connect to the LDAP and log on our application (we don't need the login page anymore) so we want to remove the gateway database and its user logic.

How can we remove the database ? 

**Used JHipster (v3.1.0)**

Thanks

**Comment by jdubois** [comment]
This is not something we provide out-of-the-box, and it depends on the features you want.
You would probably need to remove quite a lot things, but I guess that's possible, as we already have that option for microservices, and that was surprisingly easy to do.

**Comment by MBenali** [comment]
thanks

**Comment by jdubois** [comment]
@MBenali if you do this, can you send us some feedback? This is something I'd like to do after our AngularJS 2 update.

**Comment by MBenali** [comment]
Ok, I would

**Comment by gmarziou** [comment]
Yes it's easy, I did one for internal tools

**Comment by jdubois** [comment]
OK so maybe we should provide it as an option, like for the microservices. I definitely see a use-case here.
But then, should it be generated? If it's the same gateway for everyone, we could release it pre-packaged.

**Comment by deepu105** [comment]
We could just make it an option when gateway is selected. in DB option we
can add another to have no DB


Thanks & Regards,
Deepu

**Comment by MBenali** [comment]
we add some classes : 
1)UserLdap : pojo with (sn, cn, uid, appliDn...
and User with fields (name, id, ....)

2)enum ProfilLDAP

3) class LdapProvider { 
        - public LdapContext getLdapContext() {....}
        - public User getUserLdap(String remoteUser) {....
        - public org.springframework.security.core.Authentication getAuthentication(User user) {....

4) public class LdapFilter extends GenericFilterBean { 
      ...
        @Override
	public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain)
...........
}

5) public class LdapConfigurer extends SecurityConfigurerAdapter<DefaultSecurityFilterChain, HttpSecurity> {
  @Override
	public void configure(HttpSecurity http) throws Exception {
		LdapFilter customFilter = new LdapFilter(ldapProvider, userCache);
		http.addFilterBefore(customFilter, UsernamePasswordAuthenticationFilter.class);
	}


6) in public class SecurityConfiguration extends WebSecurityConfigurerAdapter {
       @Inject
	private LdapProvider ldapProvider;

	@Inject
	private UserCache userCache;
private LdapConfigurer securityConfigurerAdapter() {
		userCache.init();
		return new LdapConfigurer(ldapProvider, userCache);
	}
*) usercache use com.google.common.cache.LoadingCache<String, User>

***I deleted everything related to the config of the datasource, jpa, mysql and Liquibase in applicationXXX.yml and in the pom.xml.
but it still does not work.***

**Comment by MBenali** [comment]
A quick and not clean workaround is to generate gateway with memory DataBase option (DB will not used).
(I can't have a docker for the gateway DB)
