### ISSUE TITLE
[FEATURE] Social profile integration

### ISSUE THREAD

**Issue by ProDoser** [jhipster/generator-jhipster#3924]
Right now JHipster provide us with nice feature "Social Login". Once user log in via social profile JHipster will create `jhi_user` and `jhi_social_user_connection` tables, but how they are connected?

##### **Overview of the issue**

I tried to figure out myself, but stacked. How to get data from `jhi_social_user_connection` and use it? I didn't find any documentation for this case.

##### **Motivation for or Use Case**

`jhi_social_user_connection` table already contain data such us User Profile picture, Facebook ID etc.. I want to use this data for displaying User pictures and for social features like add friends from Facebook to friends list in my app.

Here is my question at StackOverflow https://stackoverflow.com/questions/38642148/jhipster-3-5-1-how-to-use-data-from-social-login if there is any way how to do this now, I will appreciate any help.

For example how can I get `image_url` stored in `jhi_social_user_connection` table for current user? 

##### **Suggest a Fix**

Some documentation here https://jhipster.github.io/tips/012_tip_add_new_spring_social_connector.html will be great!

I think there is no need to modify `User` entity and double the data, just make some relation between this two tables. 

##### **JHipster Version(s)**

3.5.1

**Comment by jdubois** [comment]
JHipster uses [Spring Social](http://projects.spring.io/spring-social/), you should have all the documentation you need there.
I haven't used it myself, but you should get the relevant data using the Spring Social API.

**Comment by ProDoser** [comment]
Maybe I describe my case a bit not clear. There is a class `SocialUserConnection.java` generated by JHipster (if Social Login was chosen during generation). Seems there is no relation to User entity.

`package com.mycompany.myapp.domain;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Objects;

/**
 * A Social user.
 */
@Entity
@Table(name = "jhi_social_user_connection")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class SocialUserConnection implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Column(name = "user_id", length = 255, nullable = false)
    private String userId;

    @NotNull
    @Column(name = "provider_id", length = 255, nullable = false)
    private String providerId;

    @NotNull
    @Column(name = "provider_user_id", length = 255, nullable = false)
    private String providerUserId;

    @NotNull
    @Column(nullable = false)
    private Long rank;

    @Column(name = "display_name", length = 255)
    private String displayName;

    @Column(name = "profile_url", length = 255)
    private String profileURL;

    @Column(name = "image_url", length = 255)
    private String imageURL;

    @NotNull
    @Column(name = "access_token", length = 255, nullable = false)
    private String accessToken;

    @Column(length = 255)
    private String secret;

    @Column(name = "refresh_token", length = 255)
    private String refreshToken;

    @Column(name = "expire_time")
    private Long expireTime;

    public SocialUserConnection() {}
    public SocialUserConnection(String userId,
                                String providerId,
                                String providerUserId,
                                Long rank,
                                String displayName,
                                String profileURL,
                                String imageURL,
                                String accessToken,
                                String secret,
                                String refreshToken,
                                Long expireTime) {
        this.userId = userId;
        this.providerId = providerId;
        this.providerUserId = providerUserId;
        this.rank = rank;
        this.displayName = displayName;
        this.profileURL = profileURL;
        this.imageURL = imageURL;
        this.accessToken = accessToken;
        this.secret = secret;
        this.refreshToken = refreshToken;
        this.expireTime = expireTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getProviderId() {
        return providerId;
    }

    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

    public String getProviderUserId() {
        return providerUserId;
    }

    public void setProviderUserId(String providerUserId) {
        this.providerUserId = providerUserId;
    }

    public Long getRank() {
        return rank;
    }

    public void setRank(Long rank) {
        this.rank = rank;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getProfileURL() {
        return profileURL;
    }

    public void setProfileURL(String profileURL) {
        this.profileURL = profileURL;
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getSecret() {
        return secret;
    }

    public void setSecret(String secret) {
        this.secret = secret;
    }

    public String getRefreshToken() {
        return refreshToken;
    }

    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    public Long getExpireTime() {
        return expireTime;
    }

    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        SocialUserConnection user = (SocialUserConnection) o;

        if (!id.equals(user.id)) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "SocialUserConnection{" +
            "id=" + id +
            ", userId=" + userId +
            ", providerId='" + providerId + '\'' +
            ", providerUserId='" + providerUserId + '\'' +
            ", rank=" + rank +
            ", displayName='" + displayName + '\'' +
            ", profileURL='" + profileURL + '\'' +
            ", imageURL='" + imageURL + '\'' +
            ", accessToken='" + accessToken + '\'' +
            ", secret='" + secret + '\'' +
            ", refreshToken='" + refreshToken + '\'' +
            ", expireTime=" + expireTime +
            '}';
    }
}`

Is it possible to make relationship between  this entity and User entity with entity sub-generator or it should be done only manually? Basically all data I need already there.  I just can't figure out how to associate it with User and do not broke something.

It would be great to have an option to access this data.

**Comment by jdubois** [comment]
Oh sorry: yes, you're going to need to modify this manually. It's not "known" by the entity sub-generator, so it's like the "User" entity: some relationships will work (uni-directional), but not all.
