### ISSUE TITLE
401 Unauthorized Error: Access Denied

### ISSUE THREAD

**Issue by wnbaq** [jhipster/generator-jhipster#3925]
I'm triying to test my DTO in Postman app. I want to GET http://127.0.0.1:8080/api/incidents but I just  take this: 
{ "timestamp" : "2016-08-03T11:19:31.497+0000", "status" : 401, "error" : "Unauthorized", "message" : "Access Denied", "path" : "/api/incidents" }

What is the reason of that? I choosed No Auth option It didn't work  maybe I should choose the other options I don't know.

entity Incidents {
  name ... ,
  description... ,
}
entity Cases{
    .....
}
relationship ManyToOne {
	Incidents{incidents} to Cases
}
dto Incidents with mapstruct
service Incidents with serviceImpl

## yo-rc.json:
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "yen",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "e38f0035138549f3db76b6927bdbf2803ec2fb3b",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

**Comment by atomfrede** [comment]
You need a session to access the api. But I don't know how to tell postman to create a valid session on the server side. I think your question is better suited at [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster), so I'm closing this as its not a jhipster issue.
