### ISSUE TITLE
gateway microservice communication error

### ISSUE THREAD

**Issue by fmatuszewski** [jhipster/generator-jhipster#3927]
* **Overview of the request**

2016-08-04 01:37:40.903  INFO 1937 --- [nio-8088-exec-8] me.zubi.security.jwt.TokenProvider       : Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.

* **Motivation for or Use Case** 

a bug. blocking. No communication can be made between microservice and gateway

* **Browsers and Operating System** 

Microservice project Stack trace from microservice

* **Related issues** 

* **Suggest a Fix**

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
