### ISSUE TITLE
Chat Facility for Website logged in users

### ISSUE THREAD

**Issue by guessmyfuture** [jhipster/generator-jhipster#3928]
I would like to propose a facility that you can provide us so that many will be using the Jhipster in forthcoming years.

Many of my friends and I googled for a chat facility for our own website. But we cant find a better solution till now.

If possible can you please provide us the facility. If you do this, I am sure many will be using JHipster to develop their application as it more convenient than others.

My requirement is only logged in users should be able to chat with other logged in users. As a whole I am looking for a chat facility like facebook.

If you cant i am happy, Please suggest me a way to do this.

**Comment by jdubois** [comment]
JHipster is just a starter project, we don't code business use cases.

Have a look at our WebSocket support, it will help you code a chat room.

**Comment by cbornet** [comment]
@guessmyfuture you could do it as a module.

**Comment by deepu105** [comment]
I have done this for a Jhipster project but I dont have time to make it
into a module. Ill see when I have time

Thanks & regards,
Deepu

**Comment by guessmyfuture** [comment]
@deepu105 
Deepu K Sasidharan Thanks :+1: 

Can you please Share me your project, I can create that into a module.

**Comment by deepu105** [comment]
Unfortunately its not a public project

Thanks & regards,
Deepu

**Comment by guessmyfuture** [comment]
Its ok, Deepu...
Can you please explain how to do that... It will be helpful for me

**Comment by PierreBesson** [comment]
@guessmyfuture Have a look at this project : https://github.com/salmar/spring-websocket-chat
I'm sorry we can't help you further.
