### ISSUE TITLE
If you run `gulp test` before `git init`, PhantomJS* files are created

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#3931]
For example, on a Mac, the following file is produced:

PhantomJS_2.1.1_(Mac_OS_X_0.0.0)/build/test-results/karma/TESTS-results.xml

This should be excluded in `.gitignore`.

**Comment by deepu105** [comment]
Isnt the entire build folder excluded?

Thanks & regards,
Deepu

**Comment by ruddell** [comment]
The `PhantomJS_2.1.1_(Mac_OS_X_0.0.0)` directory is created in the project root.  Changing the output directory to begin with `../` puts it into the target folder
