### ISSUE TITLE
weblogic prod

### ISSUE THREAD

**Issue by serdarturkmen** [jhipster/generator-jhipster#3936]
is there any problem using with web logic with prod profile

**Comment by gmarziou** [comment]
This is no an issue, for questions please use Stackoverflow or Gitter as [explained in our documentation](https://jhipster.github.io/help/).

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
