### ISSUE TITLE
Deploy Jhipster on weblogic

### ISSUE THREAD

**Issue by tvd27285** [jhipster/generator-jhipster#3938]
Dear all,

I'm deployment jhipster on weblogic.
Before export war file, I modified some file in jhipster project
1. implements WebApplicationInitializer in ApplicationWebXml class
2. add file weblogic.xml to webapp/WEB-INF
<?xml version="1.0" encoding="UTF-8"?>
<wls:weblogic-web-app
    xmlns:wls="http://xmlns.oracle.com/weblogic/weblogic-web-app"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
        http://java.sun.com/xml/ns/javaee/ejb-jar_3_0.xsd
        http://xmlns.oracle.com/weblogic/weblogic-web-app
        http://xmlns.oracle.com/weblogic/weblogic-web-app/1.4/weblogic-web-app.xsd">
    <wls:container-descriptor>
        <wls:prefer-application-packages>
            <wls:package-name>org.slf4j</wls:package-name>
        </wls:prefer-application-packages>

    </wls:container-descriptor>
</wls:weblogic-web-app>

When deploy war to WLS 12c, i get  this error:
java.lang.IllegalAccessError: tried to access method com.fasterxml.jackson.databind.ser.std.StdSerializer.<init>(Ljava/lang/Class;)V from class com.fasterxml.jackson.datatype.jsr310.JavaTimeModule

I think this error due to conflict version jackson.
Please help me fix it.

Many thanks!

**Comment by jdubois** [comment]
It works on all other app servers -> did you ask WebLogic support about this?
You've got a paid support from them, so I'd like to hear from them first, before we spend our (free) time here.

**Comment by tvd27285** [comment]
Dear jdubois,
My company have a License Packages for WebLogic 12 c. 
Now we going to deploy new application builiding on jhispter.
I created data source (using JNDI) on weblogic application server and  Jhipster configured using JNDI.
Everything is ok. However, when start it, it get error.

Do you can help me?

**Comment by jdubois** [comment]
I'm not a Weblogic customer or user, but I think you should follow [this stackoverflow question](http://stackoverflow.com/questions/26361136/using-jersey-2-x-web-service-on-weblogic-12-1-1) as well as [this Oracle help entry](https://docs.oracle.com/cd/E24329_01/web.1211/e24983/version.htm#RESTF201).

This looks like a common issue with Weblogic, and you need to solve it by changing your classloader order.

**Comment by hosijj** [comment]
@tvd27285 Did you solved your problem?
