### ISSUE TITLE
Application Offline

### ISSUE THREAD

**Issue by sarrek** [jhipster/generator-jhipster#3945]
Hello, 

I am currently trying to make a web application completely offline . 
Have you ever thought about effective optimisation ? 
Apparently the manifest system is obsolete and cache should go through a "service workers" . 

Any idea on this?

Thanks.

**Comment by deepu105** [comment]
This is not on our roadmap yet as its a complex usecase. could be developed as a module though if someone is interested.

**Comment by sendilkumarn** [comment]
Service Workers library [esp offline/ cache] currently works perfect with Chrome and well with firefox. 

But they are still in `beta` right ? Again adding this is not a bigger step in our application. It will not take more than few hours to add this and test in a jhipster generated application. 

Let me know, if you need any help on that? If you know it already we can add it as a tip.

@jhipster/developers  can we add this as an extra step ?

**Comment by sendilkumarn** [comment]
@deepu105 I think we can have this ? Since `PWA` is gaining its popularity adding this to our application will be a great boost.

**Comment by deepu105** [comment]
@sendilkumarn you can do a module if you want. we cannot have everything here as it would be difficult to maintain and our hands are already quite full with ng2 and stuff rite?

**Comment by mraible** [comment]
Here's some good PWA articles I saw today. I'd love to add PWA support to
JHipster.

https://twitter.com/slightlylate/status/763776499941912576

**Comment by sendilkumarn** [comment]
Actually it will great value to our project. I also feel that we have to add it.
