### ISSUE TITLE
Using id instead of login property

### ISSUE THREAD

**Issue by ghahramani** [jhipster/generator-jhipster#3950]
Hi, I'm using another language instead of English in my application and we have non-English characters in the user database in login property. And of we want to use it in GET method for loading one row of user we encountered to problem with decoding it turns to question mark in parameter which has request making Annotation. I think to not face any problem like that, it's better to use it instead login

Please let me know what are your ideas?

**Comment by gmarziou** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by ghahramani** [comment]
@gmarziou Why did you close my issue? I didn't follow the template because it's not a bug, it is a suggestion. All the templates that you mentioned in Guidelines are about new bug or feature which my case is not none of them. It's not related to any version, It is same in version 2 and 3. It's not related to any OS or other things.

Please give a link that help me for new suggestion or new idea or another use case.

**Comment by gmarziou** [comment]
This space is an issue tracker, it's used for reporting bugs or proposing  new feature. I had the impression that you were just looking for opening a discussion, if true then our gitter channel is more appropriate.

Now, if you want to propose a feature request, please reword your issue to clarify and include technical details.

**Comment by deepu105** [comment]
I think we have discussed and considered using ID but then decided against
it. I cant fetch the discussion now coz im on my mobile

Thanks & regards,
Deepu
