### ISSUE TITLE
Heroku with Postgresql throws Duplicate @ConfigurationProperties 

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#3952]
##### **Overview of the issue**
When deploying a Postgresql Monolith to Heroku, the error `Duplicate @ConfigurationProperties definition for prefix 'spring.datasource.hikari'` is thrown and the app fails to build.

##### **Reproduce the error**
Generate a postgresql app (with master) and run `yo jhipster:heroku`

##### **Suggest a Fix**
Removing `@ConfigurationProperties` from [DatabaseConfiguration](https://github.com/jhipster/generator-jhipster/blob/a74d244b8a829fae264ad74ac4bb9661986e1b5b/generators/server/templates/src/main/java/package/config/_DatabaseConfiguration.java#L85) or [HerokuDatabaseConfiguration](https://github.com/jhipster/generator-jhipster/blob/6db557c0aab25d859dc63eae15db80d5b9783fb6/generators/heroku/templates/src/main/java/package/config/_HerokuDatabaseConfiguration.java#L22) fixes it, is this property needed anymore? The app runs without it.

##### **JHipster Version(s)**
Master, does not affect v3.5.1 (Maybe started with Spring Boot v1.4 upgrade?)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "pgsqltest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "d84fac31892ef2bdfd040cec5455e6754078fee3",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

**Comment by sendilkumarn** [comment]
In `spring 1.4`, there is change in `@ConfigurationProperties`.

we `need` to have this property. Rather give `different` prefixes for both of them.

I think that would solve the problem.

**Comment by jdubois** [comment]
They configure the same thing, so they need the same prefix... They are both mutually exclusive (using profiles, in an expression), so there shouldn't be an issue there, but then I understand the issue from a validation perspective.

**Comment by sendilkumarn** [comment]
@ruddell current master ? 
It seems to work fine.

**Comment by cbornet** [comment]
The @ConfigurationProperties is needed to automatically apply extended settings to the underlying database. This is based on what SB does when it auto configures the datasource. There has been changes in SB naming of datasource properties so maybe there is now a conflict that was not there before.

**Comment by cbornet** [comment]
See https://github.com/spring-projects/spring-boot/blob/10012cfddc5479ee9a5cbe98bfe4f76483965bd1/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration.java#L74

**Comment by cbornet** [comment]
Forget my previous comments.

**Comment by jdubois** [comment]
I confirm the issue.

**Comment by jdubois** [comment]
Then, I don't know why those annotations are there, they are not doing anything! Looks like an error to me -> I'm testing this, and if it's OK the fix should be very easy.

**Comment by cbornet** [comment]
Don't remove these annotations ! They are here to automatically configure the datasource including advanced database options.

**Comment by cbornet** [comment]
Or at least keep it for the normal datasource.

**Comment by jdubois** [comment]
Oups sorry! Are you sure? For me they were just for configuring specific properties, like we have in `JHipsterProperties`. I'm re-opening this, I need to check.

**Comment by cbornet** [comment]
See #2803

**Comment by cbornet** [comment]
Mysql advanced options that we generate such as cachePrepStmts won't work without them

**Comment by cbornet** [comment]
Do you see the regular Datasource bean being created ? Maybe the conditional expression doesn't work in SB 1.4

**Comment by jdubois** [comment]
@cbornet I think there's a mistake here: the properties are standard Spring Boot properties, and handled correctly, but as we create the datasource ourselves, they are not taken into account.

This looks like an error to me, I'm going to work on correcting this.

**Comment by jdubois** [comment]
@cbornet I've debugged this several times, and the configuration is quite complex, but to me it looks like those properties are not read or used at all, whether we use the annotation or not. And the Spring Boot configuration looks wrong to me.

**Comment by jdubois** [comment]
OK let's stop trying to be clever: the standard Spring Boot configuration now works perfectly well - I debugged it and the properties are correct, and that was what we were trying to do in the first place.
I'm going to simplify all this! Good to see Spring Boot catching up with us :-)

**Comment by cbornet** [comment]
The SB autoconf doesn't wire the dropwizard metrics. I am positive that it was working at the time of the PR.

**Comment by jdubois** [comment]
@cbornet yes I'm adding them in the Metrics bean
I guess it's something that changed in Spring Boot, but that's much cleaner that way as there is less code, and it's also better with #3957

**Comment by cbornet** [comment]
You mean you can configure hikari dropwizard metrics outside of the datasource bean ? Then yes that would be great ! With #3957 that's 2 files removed !

**Comment by jdubois** [comment]
- yes that's what I just did, and indeed that's a lot better
- unfortunately that doesn't remove that file, as we need it for Liquibase -> then maybe it's not well named now

**Comment by cbornet** [comment]
:+1:
