### ISSUE TITLE
DOC: Please add Oracle 12c as a requirement to doc page

### ISSUE THREAD

**Issue by systemsplanet** [jhipster/generator-jhipster#3953]
https://jhipster.github.io/using-oracle/

This comment says 12c is required
https://github.com/jhipster/generator-jhipster/issues/2769#issuecomment-180428274

RELATED
https://github.com/jhipster/generator-jhipster/issues/2035
http://stackoverflow.com/questions/32095530/cannot-initialize-database-while-using-an-oracle-for-jhipster-application
http://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_7002.htm#sthref7262

**Comment by jdubois** [comment]
I thought this was already documented! You are correct, we should add this.

**Comment by systemsplanet** [comment]
FYI, In addition to upgrading to 12c, the dba must set compatibility to 12.1.
     SELECT name, value FROM v$parameter         WHERE name = 'compatible';

Otherwise you will get error:
   ORA-00405: COMPATIBLE parameter needs to be 12.0.0.0.0 or greater
   ORA-00722: Feature "SQL identity columns"

DETAILS

jhipster generates Liquibase identity columns using autoincrement 
<column name="id" type="bigint" autoIncrement="true">
   <constraints primaryKey="true" nullable="false"/>
</column>

When run agains an Oracle data source, this creates the SQL:
    CREATE TABLE xxxx (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL);

It also automatically creates a unique sequence:
   CREATE SEQUENCE ISEQ$$_82572 START WITH 1 MAXVALUE 9999999999999999999999999999    MINVALUE 1 NOCYCLE CACHE 20 NOORDER

And sets the Table column to use the Sequence's next value as a default:
   CREATE TABLE TEST ( ID NUMBER(38) DEFAULT ISEQ$$_82572.nextval NOT NULL 

https://oracle-base.com/articles/12c/identity-columns-in-oracle-12cr1

**Comment by systemsplanet** [comment]
You can run Jhipster  on older versions of oracle if you manually edit the Liquibase output.
This has the added benefits that the sequence names contain the table name and the
sequence values are sequential per table.  This can make troubleshooting easier.

Edit the xml generated by liquibase for each java entity: 
   src\main\resources\config\liquibase\changelog\NNNNNNN_added_entity_TABLE_NAME.xml

1. Disable autoIncrement for oracle 
Change
<property name="autoIncrement" value="true" dbms="mysql,h2,postgresql,oralce"/>
To
 <property name="autoIncrement" value="false" dbms="oracle"/>   
 <property name="autoIncrement" value="true" dbms="mysql,h2,postgresql"/>

2. Add a new changeset to the bottom of the xml file to create a sequence and trigger. 
In the template below, 
  A. Replace NNNNNN from the xml filename, 
  B. Replace TABLE_NAME with your Oracle table, 
  C. Replace ID_COLUMN with your column that contains the generated key.  

Make sure you dont have any oracle reserve words as columns or table names.

<changeSet id="NNNNNNN-2" author="legacy-oracle-user" dbms="oracle">
        <createSequence sequenceName="sq_TABLE_NAME" startValue="1000" incrementBy="1"/>
        
        <createProcedure>
            CREATE OR REPLACE TRIGGER tg_TABLE_NAME
            BEFORE INSERT
            ON TABLE_NAME
            FOR EACH ROW
            DECLARE
            BEGIN
            SELECT sq_TABLE_NAME.nextval INTO :new.ID_COLUMN FROM DUAL;
            END tg_TABLE_NAME;
        </createProcedure>
        <rollback>
            DROP TRIGGER tg_TABLE_NAME;
            DROP SEQUENCE sq_TABLE_NAME;
        </rollback>
    </changeSet>


Enable Hibernate SQL Logging to see the generated SQL, from the GUI, or logback config:
    src\main\resources\logback-spring.xml
       <logger name="org.hibernate.SQL" level="DEBUG"/>
      <logger name="org.hibernate.type" level="TRACE"/>

**Comment by jdubois** [comment]
You seem to have a very good experience with Oracle & JHipster @systemsplanet !!!

Would you like adding this as a tip to https://jhipster.github.io/tips/ ?
Or maybe even contribute to our Oracle specific code? My issue is that I don't have access to an Oracle database, so it's impossible for me to test.
