### ISSUE TITLE
failed to load elasticsearch nodes : org.elasticsearch.indices.IndexAlreadyExistsException

### ISSUE THREAD

**Issue by israeleriston** [jhipster/generator-jhipster#3958]
hello, to start my application using jhipster latest version presented this error has, does anyone know how to solve?

2016-08-09 14:31:20.744 ERROR 22707 --- [  restartedMain] .d.e.r.s.AbstractElasticsearchRepository : failed to load elasticsearch nodes : org.elasticsearch.indices.IndexAlreadyExistsException: [parents] already exists

**Comment by jdubois** [comment]
Looks like your index already exists, but as you didn't provide any information, I just can't help you!

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
