### ISSUE TITLE
Profile-Info secured for Gateways using UAA

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#3973]
##### **Overview of the issue**
This issue only affects UAA applications.  Accessing http://localhost:8080/api/profile-info gives a 401 error when not logged in.  This prevents the development ribbon from showing up.

##### **Reproduce the error**
Generate a UAA and Gateway
Run Gateway, development ribbon will be missing

##### **Suggest a Fix**
I'm not familiar at all with how UAA handles securing endpoints, maybe look in _UaaConfiguration.java.

##### **JHipster Version(s)**
Only tested master and 3.5.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
  <summary>Basic UAA App (Click to expand)</summary>
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "uaa",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableTranslation": true,
    "applicationType": "uaa",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false
  }
}
```
</details>

<details>
  <summary>Basic Gateway using UAA (Click to expand)</summary>
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "testgateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "enableSocialSignIn": false
  }
}
```
</details>

**Comment by deepu105** [comment]
`.antMatchers("/api/profile-info").permitAll()` this line is missing in configure method of `_UaaConfiguration.java`

**Comment by deepu105** [comment]
there seems to be lot more items not in sync here. `UaaConfiguration.java` needs to be in sync with `SecurityConfiguration.java` in what it does.
cc @sdoxsee @xetys
