### ISSUE TITLE
Ask for a table name if the entity name is too long

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3974]
This comes from [this discussion](https://github.com/jhipster/generator-jhipster/issues/3839#issuecomment-239376087).

When an entity name is too long, it is a good idea to have a shorter table name:

- Long table names cause issues with Oracle and MySQL (see #3839 ) - I'm not taking MySQL into account as the limit is 64 characters so that should be big enough
- Long table names can be annoying when typing the requests manually

So the idea is:

- When the user didn't use the --table-name option
- On Oracle, when an entity name has more than 14 characters (because of the Oracle limitation of 30, and the JPA spec which says that a mapping table is in the form TABLE1_TABLE2)
- On other databases, when the entity is more than 30 characters

Then:

- A new question appears asking if the user wants another, shorter table name
- With a clear warning that longer table names could cause errors if the user is on Oracle

**Comment by deepu105** [comment]
Ill do this
