### ISSUE TITLE
Improve entity relationship question for the User entity

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3975]
As mentioned in the [managing relationships page](http://jhipster.github.io/managing-relationships/), the `User` entity is specific, and not all relationships work with it.

So when it is selected, we should only allow the working relationships:

- many-to-one
- many-to-many (owner)
- one-to-one (owner)

**Comment by wmarques** [comment]
@jdubois I can do this, we just have to hide the one-to-many option in this case, right ?

**Comment by jdubois** [comment]
Yes go ahead.

But you also need to hide the "owner" question for many-to-many and one-to-one, and select "yes" always
