### ISSUE TITLE
Add documentation for the Kubernetes sub-generator

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3980]
The Kubernetes sub-generator has been merged, thanks to the hard work of @saturnism @pascalgrimaud , however we have no documentation for it!

I'll prepare a page for it (I will link it to this ticket), but I need help to document and test it, as it's quite big.

One of my issues is that it's working a bit differently from the CloudFoundry and Heroku sub-generator, it's more like the Docker Compose sub-generator, and that might not be obvious for everyone.

So if @saturnism @pascalgrimaud or anyone else want to help, please comment!

**Comment by jdubois** [comment]
- I've added a page at https://github.com/jhipster/jhipster.github.io/commit/017d4196d66e00d9f5fb15ef3102a56f6be4a22c
- This is in the [kubernetes-documentation](https://github.com/jhipster/jhipster.github.io/commits/kubernetes-documentation) branch, I will merge it when the next release comes

**Comment by pascalgrimaud** [comment]
Just completed a little bit the documentation.
For your information, Elasticsearch and Cassandra are not supported yet

**Comment by jdubois** [comment]
I'm closing this as the basic page is up, now we must improve it, like any other page of the website!
