### ISSUE TITLE
application.yml created for mongodb does not have show-sql clause

### ISSUE THREAD

**Issue by mayurbais** [jhipster/generator-jhipster#3981]
##### **Overview of the issue**

application.yml created for mongodb does not have show-sql clause.

##### **Motivation for or Use Case**
 
I am trying to see queries generated via mongorepository. I tried adding 
```
spring:
    jpa:
        show-sql: true.
```

It did not help.

I have repository as 
```
   public interface ParentRepository extends MongoRepository<Parent,String> {

	Parent findOneByIrisUserId(String id);
	
	@Query("{'irisUser.id' : ?0}")
	Parent findAllByIrisUserId(String id);

```

**Comment by jdubois** [comment]
You're using MongoDB, it's not an SQL database.

**Comment by mayurbais** [comment]
so , how do I see whats queries/function are getting fired ? 
is there any equivalent.

( I know, its not a jhipster question. but you might know it :) .I am not able to find it any where else.

**Comment by jdubois** [comment]
From Google: enable DEBUG for org.springframework.data.document.mongodb

You should have a look, or post the question, on StackOverflow

**Comment by mayurbais** [comment]
I had come across that post n StackOverflow....but that also did not help..
Any ways thanks for your time and help

**Comment by jdubois** [comment]
In case you missed, the logger is configured here:
https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/resources/logback-spring.xml

You could try putting the whole org.springframework.data in DEBUG

**Comment by mayurbais** [comment]
i had tried that, that also did not help..
this is very popular with log4j. I am thinking of configuring that separately.

**Comment by mayurbais** [comment]
i also changed
     
                <logback.loglevel>DEBUG</logback.loglevel> 

in pom.xml..
no help :(

**Comment by mayurbais** [comment]
didnt need to configure..log4j..it worked with slf4j only..
added debug on parent class :) 

 <logger name="org.springframework.data" level="DEBUG"/>

sharing here just to let you know, thanks again!
