### ISSUE TITLE
JHipster should check for illegal characters in microservice name according to URI specification

### ISSUE THREAD

**Issue by russTbaker** [jhipster/generator-jhipster#3984]
##### **Overview of the issue**

If an underscore is used in a microservice name, it will cause problems later if a FeignClient is used to access any of the endpoints of that service. The microservice name is used as the server name, which then may be used in calls using a FeignClient. When the FeignClient or a  @LoadBalanced    RestTemplate will result in a NullPointerException. The org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient uses the following code in the execute method to resolve the host:

~~~java
			URI asUri = URI.create(request.url());
			String clientName = asUri.getHost();
			URI uriWithoutHost = cleanUrl(request.url(), clientName);
                              ...

                     static URI cleanUrl(String originalUrl, String host) {
		             return URI.create(originalUrl.replaceFirst(host, ""));
	              }
~~~

however, when the URI contains an underscore, the host is null and the subsequent call to cleanUrl results in a NullPointerException.

##### **Motivation for or Use Case**

I would like to the FeignClient to leverage load balancing and dynamic URL creation instead of hard-coding the url (e.g. http://localhost:&lt;gateway-port&gt;/&lt;serviceName&gt;) which may change in a cloud environment. 

If JHipster had a warning when generating either the gateway or the other microservices when the user tried to use an underscore to name the microservice, then this problem could be avoided. Having to change this name after the service is generated is going to require a lot of refactoring and testing. 

##### **Reproduce the error**

1) Create a microservice with an underscore in the name
2) Create another microservice that uses @FeignClient("&lt;service name with underscore&gt;")
3) Make a call to the FeignClient 

##### **Related issues**

Not sure, probably not

##### **Suggest a Fix**

Add warning/error when user tries to generate microservice with an underscore or illegal character according to URI spec in the service name.

##### **JHipster Version(s)**

3.4.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.1",
    "baseName": "my_app",
    "packageName": "<redacted>",
    "packageFolder": "<redacted>",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ro",
      "es"
    ]
  }
}
~~~

**Comment by gmarziou** [comment]
Good catch.
Personally, I think the gateway should not expose service name in URLs, it makes too hard refactoring services later on.
