### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by francisyuya** [jhipster/generator-jhipster#3989]
##### **Overview of the issue**

Need Help

Hi all, I am new to Jhipster and I like to know how to integrate an online payment system like PayPal?

I not only want the user to be redirected to the paypal site to make the payment; but that my application was able to know when the payment is make and then active some menus.

I do not know where to start.

Thank you for your help.

Merci pour votre aide.
##### **JHipster Version(s)**
2.27.0

##### **Browsers and Operating System**
google chrome, Windows 8

**Comment by atomfrede** [comment]
Your question is better suited for [stackoverflow](http://stackoverflow.com/tags/jhipster). This issue tracker should only be used for jhipster issues.

**Comment by francisyuya** [comment]
Ok. Thank you, I'll try with stackoverflow
