### ISSUE TITLE
upgrade to gradle 3

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3994]
upgrade to gradle 3.0
https://docs.gradle.org/current/release-notes

the deamon claims to be giving 75% performance boost. may be we should enable it by default?

**Comment by deepu105** [comment]
we can also see if we can use parallel task execution to make builds faster

we need to keep an eye on some breaking changes in scala and sonar plugin

**Comment by octoroid** [comment]
+1

**Comment by atomfrede** [comment]
The daemon is enabled by default with 3.0. I have updated some projects yesterday (no java hipsters projects) and there was no problem, so lets try it out.

**Comment by jdubois** [comment]
Just tried it: I can't get `./gradlew clean test war bootRepackage -Pprod` to generate a prod war file...
It also seems there is the issue with Gradle 2.x, but I'm not sure: did you try it? How do you build a prod WAR file with Gradle?

**Comment by atomfrede** [comment]
I din't try it lately, but ``./gradlew -Pprod bootRepackage`` should be enough

**Comment by jdubois** [comment]
@atomfrede thanks -> I tried it, it didn't generate a war file :-(

**Comment by atomfrede** [comment]
@jdubois I'll try to have a look today.

**Comment by atomfrede** [comment]
@jdubois I tried an older app generated with 3.4.1 using gradle 2 and the war is generated just fine with ``./gradlew -Pprod clean test bootRepackage``. The same here for the project generated with the gradle 3 branch.

**Comment by jdubois** [comment]
Thanks @atomfrede - I just tried it again on the current master branch (and on v3.4.1), and I didn't get any war file generated, in "build" or "target" :-(

**Comment by atomfrede** [comment]
Do you have any special config? I've tested with 

```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.1",
    "baseName": "sternenschwimmen",
    "packageName": "com.gitlab.atomfrede",
    "packageFolder": "com/gitlab/atomfrede",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de"
    ]
  }
}
```

and for gradle 3 with 

```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "3d158653e31b869a375766bc77617e4b49befa7d",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

**Comment by jdubois** [comment]
Oh yes I've got an old .yo-rc.json - I'll try again at lunch time... Now I need to go to work :-)

**Comment by jdubois** [comment]
Just tried it -> thanks @atomfrede , it works! I wonder what we changed in the .yo-rc.json - but I really don't have the time now
