### ISSUE TITLE
Cannot authenticate with either authentication option

### ISSUE THREAD

**Issue by JeffSherman** [jhipster/generator-jhipster#400]
I installed jhipster v.16 using the local install option

I created a project...
Options selected are:
[?](1/13) What is the base name of your application? myapp
[?](2/13) Would you like to use Maven or Gradle? Maven
[?](3/13) What is your default Java package name? com.myapp
[?](4/13) Do you want to use Java 8? No (use Java 7)
[?](5/13) Which _type_ of authentication would you like to use? Cookie-Based Authentication (Session)
[?](6/13) Which _type_ of database would you like to use? NoSQL (MongoDB)
[?](7/13) Do you want to use cache? No
[?](8/13) Do you want to use clustered HTTP sessions? No
[?](9/13) Do you want to use WebSockets? No
[?](10/13) Which _production_ database would you like to use? MongoDB
[?](11/13) Which _development_ database would you like to use? MongoDB
[?](12/13) Would you like to use Grunt or Gulp.js for building the frontend? Grunt
[?](13/13) Would you like to use the Compass CSS Authoring Framework? No

I ran the server with:
mvn spring-boot:run

Server output after authentication attempt with user = admin, pass = admin

[DEBUG] com.adaje.aop.logging.LoggingAspect - Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Sat Jun 21 13:03:58 EDT 2014, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={message=Access is denied, type=org.springframework.security.access.AccessDeniedException}]]
[DEBUG] com.adaje.aop.logging.LoggingAspect - Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
[DEBUG] com.adaje.security.Http401UnauthorizedEntryPoint - Pre-authenticated entry point called. Rejecting access
[DEBUG] com.adaje.aop.logging.LoggingAspect - Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Sat Jun 21 13:04:09 EDT 2014, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={message=Access is denied, type=org.springframework.security.access.AccessDeniedException}]]
[DEBUG] com.adaje.aop.logging.LoggingAspect - Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
[DEBUG] com.adaje.security.Http401UnauthorizedEntryPoint - Pre-authenticated entry point called. Rejecting access
[WARN] org.springframework.web.servlet.PageNotFound - Request method 'POST' not supported

I also created a project with the OAuth2 authentication option and am seeing similar results to:
https://github.com/jhipster/generator-jhipster/issues/341

Specifically, I get:
[DEBUG] com.chomnoue.jstarter2.security.UserDetailsService - Authenticating jhip
sterapp

Not sure if this is bug or I'm doing something incorrectly...

**Comment by zszsoldos** [comment]
I installed v2.5.0 and I have the same problem with postgres.

[WARN] org.springframework.web.servlet.PageNotFound - Request method 'POST' not supported

What am I doing wrong?

Thanks.

**Comment by jdubois** [comment]
This is an old issue, with MongoDB, this probably is very different to your use case -> can you open up a new ticket, with all details of you are doing
