### ISSUE TITLE
Elasticsearch Blocks Startup

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#4000]
##### **Overview of the issue**
The application does not connect to the current version of Elasticsearch (1.7.5) during startup.  A warning is thrown and the app never starts.    This affects both, running a local cluster and running elasticsearch through docker.

**Java Warning**
`
2016-08-18 06:49:40.342  INFO 9 --- [           main] com.mycompany.myapp.DockertestApp        : Running with Spring profile(s) : [prod, swagger]
2016-08-18 06:49:42.829  WARN 9 --- [ I/O worker #1}] org.elasticsearch.transport.netty        : [Danielle Moonstar] exception caught on transport layer [[id: 0xc0db708e, /172.19.0.2:50011 => elasticsearch/172.19.0.3:9300]], closing connection
java.lang.NullPointerException: null
at org.elasticsearch.transport.netty.MessageChannelHandler.handleException(MessageChannelHandler.java:207)
`
**Elasticsearch Warning**
`[2016-08-17 23:55:59,517][WARN ][transport.netty          ] [Mad Thinker] Message not fully read (request) for requestId [0], action [cluster:monitor/nodes/liveness], readerIndex [50] vs expected [51]; resetting`

##### **Motivation for or Use Case**
Microservices are stuck in the 'starting' phase if they use elasticsearch with the generated docker configs

##### **Reproduce the error**
Generate a monolith or microservice (faster) that uses elasticsearch
Package it for docker with `./mvnw package -DskipTests -Pprod docker:build`
Run `docker-compose -f src/main/docker/app.yml up -d` to start the app, database, and elasticsearch
(You can also test with a local elasticsearch, it has the same result)

##### **Suggest a Fix**
Spring Boot 1.4 has support for newer versions of Elasticsearch.  Upgrading to Elasticsearch v2.3.5 fixed the error for me, I was able to create and search a basic entity.  This would be a major change for people upgrading their applications though.  There might be an easier fix, this was the first thing I tried.

##### **JHipster Version(s)**
v3.6.0 and master, I think this started with the Spring Boot upgrade.  

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.0",
    "baseName": "dockertest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "a925c446c4a1c15880d6768823bc7b626c3780b3",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Any, not necessary.

**Comment by jdubois** [comment]
We're trying to follow newer versions of everything we use: I didn't check for our Elasticsearch version, but it looks logical to me that we update it to the latest possible version.
And if that fixes the issue, it's even better!

**Comment by jdubois** [comment]
So Spring Boot 1.4 comes with Elasticsearch 2.3.4:

- This fully works in "dev" mode as we are using an in-memory version
- What doesn't work is our Docker Compose file, as it relies on Elasticsearch 1.7.5 -> @ruddell do you confirm this is the issue?

My solution is:

- Upgrade our Docker Compose file to Elasticsearch 2.3.5 (the latest released version at the time of this writing)

Of course people will need to migrate, but:

1. That's the same issue with all datastores, like MySQL or Cassandra... You need to run your upgrade scripts
2. For Elasticsearch that's a minor issue, as you should NOT use it as a datastore. Data is not securely written in Elasticsearch, so you need a way to re-index it (and we have specific module for it: http://jhipster.github.io/modules/marketplace/#/details/generator-jhipster-elasticsearch-reindexer - but please note I've never used it, I do my own re-index code myself )

**Comment by jdubois** [comment]
Oh thanks @ruddell I see you've done a PR with exactly the same thing!

-> I'll what a little bit to see if everything is correct, and that might trigger a minor release, as a lot of people are using Elasticsearch with JHipster

**Comment by pascalgrimaud** [comment]
@ruddell : is it the same error in this log ? https://travis-ci.org/jhipster/generator-jhipster/jobs/152995969

**Comment by ruddell** [comment]
@pascalgrimaud Yeah that's the error.

**Comment by pascalgrimaud** [comment]
thx @ruddell !
I don't understand why the build is green... it shouldn't be !

**Comment by ruddell** [comment]
Well the NullPointerException is gone, but the app still aborts protractor after trying to connect 11 times.  https://travis-ci.org/jhipster/generator-jhipster/jobs/153194755#L3197

**Comment by pascalgrimaud** [comment]
@ruddell : these logs (build number 2) concern gradle, right ? no elasticsearch in this config

The build number 4 is with psql+es: https://travis-ci.org/jhipster/generator-jhipster/jobs/153194757
it seems to be OK! :)
