### ISSUE TITLE
Prod and Dev profile with email properties

### ISSUE THREAD

**Issue by chegola** [jhipster/generator-jhipster#4014]
##### **Overview of the issue**

When supplying email properties in both prod and dev profile, such as 
mail:
        host: smtp-mail.outlook.com
        port: 587
        username: example@test.com
        password: 1234exam

Somehow system encrypts the password field in dev profile but not in prod profile, when running in production , I have got error message  of email authentication but this issue does not happen in dev profile. So I am not really sure this is an issue or I have missed configuration.

Dev profile (password will be encrypted) 
        username: example_dev@test.com
        password: qwedafees

Prod profile (password will not be encrypted)
        username: example_prod@test.com
        password: real_password

I have limited knowledge of bower or process of building Prod profile so would it be great if you could have a look of this one?

**Comment by gmarziou** [comment]
Any reason why you did not fill the issue template?

**Comment by gmarziou** [comment]
This is very likely an environment problem, please use stackoverflow for such issues and you may provide the full mail configuration there like https://github.com/chegola/myprop/blob/master/src/main/resources/config/application-prod.yml#L33-L43
