### ISSUE TITLE
Cannot resolve method 'createEntity(EntityManager em)' in UserResourceIntTest

### ISSUE THREAD

**Issue by xiasenhai** [jhipster/generator-jhipster#4025]
##### **Overview of the issue**

If entity(DemoObject) has relationship with User, the generated test class in /src/test/java/.../web/rest/DemoObjectResourceIntTest will call an method 'createEntity' on UserResourceIntTest which not exists.

```java
UserResourceIntTest.createEntity(em);
```

##### **Reproduce the error**
Entity structure of DemoObject:

```json
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "relationshipValidateRules": [
                "required"
            ],
            "otherEntityField": "id",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "demoName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "demoNumber",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20160823101354",
    "dto": "no",
    "service": "no",
    "entityTableName": "demo_object",
    "pagination": "pagination"
}
```

##### **Suggest a Fix**

create an method in UserResourceIntTest.java
```java
    public static User createEntity(EntityManager em) {
        Set<Authority> authorities = new HashSet<>();
        Authority authority = new Authority();
        authority.setName(AuthoritiesConstants.ADMIN);
        authorities.add(authority);

        User user = new User();
        user.setLogin("test");
        user.setFirstName("john");
        user.setLastName("doe");
        user.setEmail("john.doe@jhipter.com");
        user.setAuthorities(authorities);

        em.persist(user);
        em.flush();
        return em.find(User.class, "test");
    }
```

##### **JHipster Version(s)**

```
 "jhipsterVersion": "3.6.1"
```

**Comment by deepu105** [comment]
seems to be related to https://github.com/jhipster/generator-jhipster/issues/3769

**Comment by tsaqova** [comment]
same problem here, because the relationship to User was required, generator create UserResourceIntTest.createEntity(em) which is not exist.

**Comment by Throckmortra** [comment]
using a createEntity method like xiasenhai's suggested fix will result in detached entity error. Played around with it but unable to get it to work.

A temporary fix would be to return the default user:

```
public static User createEntity(EntityManager em) {
     return em.find(User.class, 1L);
}
```

**Comment by jdubois** [comment]
Yes, this is my fault.
I'm fixing it.

**Comment by tsaqova** [comment]
@jdubois i think there is still a bug here when there are more than 1 relationship to user from one table / entity, because the login field is unique and it will throw constraint violation exception.

**Comment by dtrabalza** [comment]
@tsaqova I confirm the bug when there are more than 1 relationships to User.
It could be solved by not persisting the user though, or creating it only if not existing

**Comment by ruddell** [comment]
@tsaqova @dtrabalza I could not reproduce the issue with any of the relationship types.  If this is still an issue, please open a new issue and post your entity JSON files so that we can fix it.
