### ISSUE TITLE
Deploying To Three Service Providers [FEATURE]

### ISSUE THREAD

**Issue by maektwain** [jhipster/generator-jhipster#4026]
##### **Overview of the issue**

When deploying application over to these service providers 

1.Pivotal Web Services

2.AWS

3.Heroku

##### **Motivation for or Use Case**

We are using these restful services for image text extraction which uses google vision api and other third party integrations and mostly interact with other third party restful services 

I would like to sum this, in small 

AWS Failed(Because we cannot use websocket) No CHOICE HERE

With PWS We were able to deploy it successfully and then again web socket was not working !

I ran it again with the changed code in tracker.service.js 

`var url = '//' + loc.host+":4443" + loc.pathname + 'websocket/tracker';`

Above line will make sure that you get connected to web socket on PWS

With Herkou Everything is working fine but when adding GOOGLE_APPLICATION_CREDENTIALS 

as config vars , because we need to reference it as a file 

https://developers.google.com/identity/protocols/application-default-credentials

Also i am getting another INFO LEVEL from hazelcast too which was trying to connect within every second and due to it was getting out of memory 

##### **Related issues**

http://stackoverflow.com/questions/14410539/does-cloud-foundry-support-web-sockets

https://github.com/jhipster/generator-jhipster/issues/963

##### **Suggest a Fix**

We can be more direct about the documentation in part this is what i have seen in many open source source code and they lack navigated documentation like what is available 

I am ready to invest some time on documentation if given chance !

##### **JHipster Version(s)**

v3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

When deploying to these services i have this JHipster Configuration

`{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "frontend",
    "packageName": "com.upscale.front",
    "packageFolder": "com/upscale/front",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "enableSocialSignIn": false
  }
}`

**Comment by jdubois** [comment]
- You have to select options that are compatible with your cloud provider. For example Hazelcast won't work with Heroku, as they don't allow you to open ports between apps. So if you want to help on documenting what works or not, yes it's a valuable input.
- Websockets do work on PWS and AWS: you just need to go around ELB, so you'll be using a specific port. For AWS that's only if you use ELB (and in that case that's obvious it can't work with Websocket, so normally people know about it), and with CloudFoundry it depends on your CF provider: you have the issue with PCF (and need to use port 4443), but that's not the case on other providers. So here again you need to read the documentation and get in touch with your hosting provider.

**Comment by deepu105** [comment]
@jdubois do we have to do anything here? if not lets close it

**Comment by jdubois** [comment]
No not really... As always, more documentation is always better -> maybe we should update the "contributing" doc for this, as we shouldn't require a ticket for this

@maektwain if you do a PR on the website, I'll review it directly, and merge it
