### ISSUE TITLE
Generate a unique business key in entities

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#4027]
Our current hashCode() and equals() methods are based on the auto-generated id which can lead to bad side effects. Thus it is recommended to use a unique immutable "business key" to implement them.
See https://vladmihalcea.com/2013/10/23/hibernate-facts-equals-and-hashcode/

The alternative but with an impact on performance for large collections would be to use a fixed hashCode. See https://vladmihalcea.com/2016/06/06/how-to-implement-equals-and-hashcode-using-the-entity-identifier/

**Comment by jdubois** [comment]
Yes I fully agree with the business key (I didn't even read the link you provided!!). We just provide a default, which is only technical, and then you should change it according to your business needs.
Maybe we should make it clear in the Javadoc of the method.

**Comment by jdubois** [comment]
And by the way, this default is the one automatically generated by Intellij IDEA.

**Comment by cbornet** [comment]
What if we generated a unique immutable entity field as a UUID or timestamp ?

**Comment by jdubois** [comment]
- timestamps won't be unique (at least there's a risk)
- uuid would be too uniques -> that would be the same issue as the default hashcode, when 2 objects which are equals (from a business point of view) don't have the same hashcode

**Comment by cbornet** [comment]
Actually IDEA generates equals and hashcode including all fields (not only id)

**Comment by cbornet** [comment]
For timestamp, there is indeed a risk.
For UUID, I don't see the issue since the UUID would precisely be the business key

**Comment by cbornet** [comment]
Something like
```java
    @Column(name="__UUID__", unique=true, nullable=false, updatable=false, length = 36)
    private String uuid = java.util.UUID.randomUUID().toString();
```

**Comment by ShaneOctopus** [comment]
Would the ability to override the creation of a system id be related? Like in Active Record, you can specify {:id => false} at the entity level, then add a column attribute maybe like uniqueIdentifier to allow proper relationship and index generation.

**Comment by jdubois** [comment]
Sorry @cbornet , I thought you wanted to generate the UUID in-memory
So if you store them in the DB, that's a little bit better than the PK (as you have it before doing a save(), so less issues when adding the instance in a collection for example), but still that's the same thing as a PK afterwards.
Another solution for this is to save the object immediately after creation, to have the PK, and then use it in the same transaction (so everything could be rolled back).
Your solution would be a bit better, but on the other hand it's going to cost more resources.
Anyway, a business key would be better: my original idea was to tell people they can use the PK by default, but that they should code a business key instead if they want to have a better quality app.

**Comment by jdubois** [comment]
Closing this as I don't think we're going to change this any time soon. I'm quite happy with the current system, but of course this can be discussed & improved.
