### ISSUE TITLE
Using includeAll tag in master.xml 

### ISSUE THREAD

**Issue by chegola** [jhipster/generator-jhipster#4034]
##### **Overview of the issue**

Using includeAll tag in master.xml  could  shorten code change .
##### **Motivation for or Use Case**
After adding a new entity using jhipster sub-generator entity, jhipster will add a new xml file under config/liquibase/changelog/ and also update  **master.xml.**

Instead keep updating master.xml, can we use only tag below. It will automatically grab all xml files under config/liquibase/changelog.
  <//includeAll path="classpath:config/liquibase/changelog/" />

##### **Reproduce the error**

Add a new entity using jhipster sub-generator

##### **Suggest a Fix**
Replace the include tag with includeAll tag in master.xml
  <//includeAll path="classpath:config/liquibase/changelog/" />

##### **JHipster Version(s)**
3.5.1

**Comment by cbornet** [comment]
That's a good idea but we would need first to ensure the alphabetical order for loading which is currently not the case for constraints changeset.

**Comment by gmarziou** [comment]
RIght and this could cause backward compatibility issues for existing projects. I prefer explicit order rather than implicit.

**Comment by jdubois** [comment]
I didn't do it on purpose, because of the warning here: http://www.liquibase.org/documentation/includeall.html

**Comment by chegola** [comment]
Thanks for your opinion

**Comment by chegola** [comment]
Thanks for your opinion
