### ISSUE TITLE
CORS not working properly

### ISSUE THREAD

**Issue by ercancelik** [jhipster/generator-jhipster#4035]
Hi,

I am using jhipster for only server side code generation. I separate server and client projects. Front end project is build by grunt. When i run "grunt serve", it opens the url as localhost:9000 and the backend resources are located at localhost:8080. 
The below scenarios are tried in login page. I use spring security configuration which is configured by jhipster.

**There are 2 scenarios that I tried.**

**1. If I do not modify anything(I mean I do not add any code, or modify configuration files for CORS support) it throws the error below:**

~~~
XMLHttpRequest cannot load http://localhost:8080/api/authentication?cacheBuster=1472210597486. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 403.
~~~

When I look at network logs of the browser, i see that it only tries OPTIONS method.

**2. If I uncomment the CORS part of application.yml, this time it throws the same error but there are two network access attempts in the log.**

* **OPTIONS request is success.** And these headers are added to response headers:
   Access-Control-Allow-Credentials:true
   Access-Control-Allow-Headers:authorization
   Access-Control-Allow-Methods:GET,PUT,POST,DELETE,OPTIONS
   Access-Control-Allow-Origin:http://localhost:9000
   Access-Control-Max-Age:1800

* **POST request failed with code 403**. The response headers do not includes 
  Access-Control- Allow-* headers. All the response headers are:
  Cache-Control:no-cache, no-store, max-age=0, must-revalidate
  Content-Type:application/json;charset=UTF-8
  Date:Fri, 26 Aug 2016 11:29:30 GMT
  Expires:0
  Pragma:no-cache
  Server:Apache-Coyote/1.1
  Set-Cookie:JSESSIONID=8232A843BDC6F30EF40F863A2CBB919D; Path=/; HttpOnly
  Set-Cookie:CSRF-TOKEN=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
  Transfer-Encoding:chunked
  X-Content-Type-Options:nosniff
  X-XSS-Protection:1; mode=block

So i couldn't understand, although the OPTIONS request is succeeded and the "Access-Control-Allow-Origin" header is added, but POST request got 403 without the "Access-Control-Allow-Origin" header.

**My configuration is as follow :** 

jhipsterVersion: "3.5.1"
java version "1.8.0_25"
git version 2.6.4 (Apple Git-63)
node: v5.5.0
npm: 3.3.12
bower: 1.7.9
gulp:
CLI version 3.9.1
Local version 3.9.1
yeoman: 1.8.4

**Comment by gmarziou** [comment]
> I separate server and client projects

Is it only for dev or is it going to be separated also in prod?

~~~
Access-Control-Allow-Origin:http://localhost:9000
~~~

To me this means that you are using proxy feature of grunt serve, have you checked that it forwards CORS headers?
Also if you plan to deploy your client app on another server, you could get rid of grunt proxy to access your server API.

**Comment by ercancelik** [comment]
Yes as you mentioned i am using grunt proxy feature for only development environment. Doing "grunt build" for every simple front-end change costs too much. 

In my older project i didn't use jhipster, but in that project i also separated front-end(grunt used) and back-end(spring mvc). In that project i only added org.apache.catalina.filters.CorsFilter to my web.xml and it worked properly. I mean i didn't do any grunt CORS header forward configuration in grunt.

**Comment by gmarziou** [comment]
In your case, using grunt serve does not mean you have to use grunt proxy for your client app to access your jhipster backend. Configure your angular app to access API directly on port 8080, use grunt serve only for client part for hot reload feature, this way you can work the same way as your older project.

**Comment by abuechler** [comment]
I can reproduce this, with a fresh generated monolithic app.

### Steps to reproduce
1. Create monolithic app with oauth2
1. For the prod profile to work, copy datasource relevant sections from dev to prod profile
1. Run: mvn -Pprod
1. Copy curl command from API page and add -v switch to see the headers

### The output I get is:

```
$ curl -v -X GET --header 'Accept: application/json' --header 'Authorization: Bearer 3b2a1b8c-efea-4164-8014-57dbf072031f' 'http://localhost:8080/api/account'
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /api/account HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: application/json
> Authorization: Bearer 3b2a1b8c-efea-4164-8014-57dbf072031f
> 
< HTTP/1.1 200 
< X-Application-Context: jhipster:prod:8080
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Vary: Accept-Encoding
< Date: Fri, 26 Aug 2016 12:46:48 GMT
< 
* Connection #0 to host localhost left intact
{  
   "login":"admin",
   "firstName":"Administrator",
   "lastName":"Administrator",
   "email":"admin@localhost",
   "activated":true,
   "langKey":"en",
   "authorities":[  
      "ROLE_USER",
      "ROLE_ADMIN"
   ]
}
```

The CORS section of application.yml looks like this:

```
# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors: #By default CORS are not enabled. Uncomment to enable.
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    mail:
        from: jhipster@localhost
...
....
```

**Comment by gmarziou** [comment]
Your curl command does not provide CORS headers in request, so it does not mimic a browser request.

https://stackoverflow.com/questions/12173990/how-can-you-debug-a-cors-request-with-curl

**Comment by ercancelik** [comment]
**OPTIONS method's curl**

```
curl -v 'http://localhost:8080/api/authentication?cacheBuster=1472216202268' -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: http://localhost:9000' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8,tr;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://localhost:9000/' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: authorization' --compressed
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> OPTIONS /api/authentication?cacheBuster=1472216202268 HTTP/1.1
> Host: localhost:8080
> Access-Control-Request-Method: POST
> Origin: http://localhost:9000
> Accept-Encoding: gzip, deflate, sdch
> Accept-Language: en-US,en;q=0.8,tr;q=0.6
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
> Accept: */*
> Referer: http://localhost:9000/
> Connection: keep-alive
> Access-Control-Request-Headers: authorization
> 
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Access-Control-Allow-Origin: http://localhost:9000
< Vary: Origin
< Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
< Access-Control-Allow-Headers: authorization
< Access-Control-Allow-Credentials: true
< Access-Control-Max-Age: 1800
< Content-Length: 0
< Date: Fri, 26 Aug 2016 13:01:26 GMT
< 
* Connection #0 to host localhost left intact
```

**POST method's curl**

`curl -v 'http://localhost:8080/api/authentication?cacheBuster=1472216202268' -H 'Origin: http://localhost:9000' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,tr;q=0.6' -H 'Authorization: Basic' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost:9000/' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36' -H 'Connection: keep-alive' --data 'j_username=admin&j_password=admin&remember-me=true&submit=Login' --compressed
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> POST /api/authentication?cacheBuster=1472216202268 HTTP/1.1
> Host: localhost:8080
> Origin: http://localhost:9000
> Accept-Encoding: gzip, deflate
> Accept-Language: en-US,en;q=0.8,tr;q=0.6
> Authorization: Basic
> Content-Type: application/x-www-form-urlencoded
> Accept: application/json, text/plain, */*
> Referer: http://localhost:9000/
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
> Connection: keep-alive
> Content-Length: 63
> 
* upload completely sent off: 63 out of 63 bytes
< HTTP/1.1 403 Forbidden
< Server: Apache-Coyote/1.1
< Set-Cookie: JSESSIONID=B7B98C391ABB06267A01CF5431EB16A2; Path=/; HttpOnly
< Set-Cookie: CSRF-TOKEN=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Fri, 26 Aug 2016 13:02:04 GMT
< 
{
  "timestamp" : "2016-08-26T13:02:04.943+0000",
  "status" : 403,
  "error" : "Forbidden",
  "message" : "Could not verify the provided CSRF token because your session was not found.",
  "path" : "/api/authentication"
* Connection #0 to host localhost left intact
`

**Comment by ercancelik** [comment]
I forgot to add my .yo-rc.json file. As you can see i use session based authentication : 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "aaa",
    "packageName": "com.xxx.yyy",
    "packageFolder": "com/xxx/yyy",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": "no",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "0d14b22692d6b6e0beb24cb0dc7d7d6765eb9a68",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "tr",
    "languages": [
      "tr",
      "en"
    ]
  }
}
```

**Comment by jdubois** [comment]
I don't understand, you're using "grunt serve" with JHipster 3.5.1, which isn't something we do at all... So it looks like you modified quite a lot of things, are you sure this is a JHipster issue?  Do you have the same error with the gulp configuration we provide?

**Comment by cbornet** [comment]
This is not a CORS issue : the server rejected the request because it didn't find the CSRF token.

**Comment by cbornet** [comment]
Note : when CORS requirements are not met, it's the browser that rejects the response, not the server.

**Comment by abuechler** [comment]
@gmarziou Thanks for pointing that out!

**Comment by ercancelik** [comment]
@Christophe i don't understand how can csrf token not added to header. My SecurityConfiguration class's configure method is like below. And in that method CsrfCookieGeneratorFilter is added. 

If i use grunt build and the compiled frontend files copied into backend project everything works properly. Because everything runs on localhost:8080.

When i run "grunt serve" to use hard reload feature, calling api's located at localhost:8080 from localhost:9000 produces this error.

What causes CSRF Token be not added to header?

   ```
 protected void configure(HttpSecurity http) throws Exception {
        http
            .csrf()
        .and()
            .addFilterAfter(new CsrfCookieGeneratorFilter(), CsrfFilter.class)
            .exceptionHandling()
            .accessDeniedHandler(new CustomAccessDeniedHandler())
            .authenticationEntryPoint(authenticationEntryPoint)
        .and()
            .rememberMe()
            .rememberMeServices(rememberMeServices)
            .rememberMeParameter("remember-me")
            .key(jHipsterProperties.getSecurity().getRememberMe().getKey())
        .and()
            .formLogin()
            .loginProcessingUrl("/api/authentication")
            .successHandler(ajaxAuthenticationSuccessHandler)
            .failureHandler(ajaxAuthenticationFailureHandler)
            .usernameParameter("j_username")
            .passwordParameter("j_password")
            .permitAll()
        .and()
            .logout()
            .logoutUrl("/api/logout")
            .logoutSuccessHandler(ajaxLogoutSuccessHandler)
            .deleteCookies("JSESSIONID", "CSRF-TOKEN")
            .permitAll()
        .and()
            .headers()
            .frameOptions()
            .disable()
        .and()
            .authorizeRequests()
            .antMatchers("/api/register").permitAll()
            .antMatchers("/api/activate").permitAll()
            .antMatchers("/api/authenticate").permitAll()
            .antMatchers("/api/account/reset_password/init").permitAll()
            .antMatchers("/api/account/reset_password/finish").permitAll()
            .antMatchers("/api/profile-info").permitAll()
            .antMatchers("/api/**").authenticated()
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN)
            .antMatchers("/v2/api-docs/**").permitAll()
            .antMatchers("/swagger-resources/configuration/ui").permitAll()
            .antMatchers("/swagger-ui/index.html").hasAuthority(AuthoritiesConstants.ADMIN);

    }
```

**Comment by abuechler** [comment]
Shouldn't there be CORS headers, also for 401 responses (e.g. when the token has expired and needs to be refreshed)?

![screen shot 2016-08-26 at 16 02 24](https://cloud.githubusercontent.com/assets/1309626/18008038/dd2e6ada-6ba6-11e6-9c2f-bff5e0a409b7.png)

**Comment by cbornet** [comment]
It's angular client that should add the token

**Comment by deepu105** [comment]
Why are there mentions of grunt? We do not have grunt anymore at all it
should be gulp

Thanks & regards,
Deepu

**Comment by ruddell** [comment]
@abuechler When I was testing CORS the other day, the headers were not added when making a request from the same origin, only an outside origin.

**Comment by abuechler** [comment]
@ruddell Thanks a lot! Is there any reason why these headers are not send? I was expecting that the configuration as defined in application.yml gets always added, but this is not the case:


```
@Component
public class Http401UnauthorizedEntryPoint implements AuthenticationEntryPoint {

    private final Logger log = LoggerFactory.getLogger(Http401UnauthorizedEntryPoint.class);

    /**
     * Always returns a 401 error code to the client.
     */
    @Override
    public void commence(HttpServletRequest request, HttpServletResponse response, AuthenticationException arg2)
        throws IOException,
        ServletException {

        log.debug("Pre-authenticated entry point called. Rejecting access");
        response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "Access Denied");
    }
}

```

Why not add these before reponse.sendError()?

**Comment by jdubois** [comment]
I'm sorry, again, I don't understand where we have a bug here. So I'm closing this -> if you want to discuss CORS issue, etc, please go to StackOverflow, not our issue tracker.

**Comment by May004** [comment]
![Uploading cors-cofig.png…]()

**Comment by May004** [comment]
![cors-cofig](https://user-images.githubusercontent.com/80736368/111255665-13092380-864a-11eb-85e5-6af463575b7a.png)

**Comment by mraible** [comment]
Please don't comment on a closed issue. It's better to open a new one and provide steps to reproduce the issue you're seeing.
