### ISSUE TITLE
Swagger UI adds a :80 to the request url when used with https

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#4036]
##### **Overview of the issue**

My app is based on an microservice architecture and the gateway as a certificate
In the Swagger API docs, when I try use the generated form to perform a request the request url is set properly (`https://x.y.z`) but when I try to request a microservice the request url appends :80 added (`https://x.y.z:80/myService`).

When I hit the `Try it out!` button I get an empty response body and 0 as response code.

If I request `/v2/api-docs` on the gateway I got the proper host (`x.y.z`) and basePath (`/`) on the service the host field is set to `x.y.z:80` and the basePath is good.

If I use the generated `curl` command, it works if I remove the `:80` port. 
##### **Motivation for or Use Case**

The API doc is a powerfull tool fro frontend developers to consume my services. This issue is not blocking at all is just a pain to no be able to use the swagger forms.

##### **Reproduce the error**

* Generate a JHipster microservice app (gateway + 1 service).
* Add a certificate to the gateway
* Start the app with the `swagger` profile
* Log as admin
* Go `Administration` > `API`
* Test to do a request from the gateway and from a service.

##### **Suggest a Fix**

Since the issue is visible in the JSON generated by `/v2/api-docs`, I don't think the issue is on the client side.
I didn't find any related issue on Jhipster.
I found some leads:
* [A CORS issue?](https://groups.google.com/forum/#!topic/swagger-swaggersocket/WjyS1SrJo7c)
I tried to enable the `CORS` (uncommenting the `jhipster.cors` properties in `application.yml` on both the gateway and service, it didn't work)

* [SwaggerUI with https](http://stackoverflow.com/questions/36625000/how-do-i-get-swagger-ui-to-use-port-443-with-swashbuckle)

* [StackOverlow without answer](http://stackoverflow.com/questions/33117478/springfox-swagger-generating-requests-with-port-80-for-https-urls)
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
Gateway
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "api",
    "packageName": "",
    "packageFolder": "",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
```
Service
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "myteepi",
    "packageName": "",
    "packageFolder": "",
    "serverPort": "8085",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false
  }
}
```

**Comment by gmarziou** [comment]
Yes I remember having also this issue but i can't test it right niow.
Have you tried by forcing default https port in URL: 443? `https://x.y.z:443`

**Comment by danielpetisme** [comment]
>forcing default https port in URL
Where ? Indeed if I replace `:80` by `:443` in the curl comamnd, it works.
But how can I force the *request url* in the swagger UI?

**Comment by cbornet** [comment]
I think there is a springfox property for that

**Comment by gmarziou** [comment]
I was just thinking about adding it to the url of web app before accessing the API menu.

**Comment by danielpetisme** [comment]
@gmarziou 
if I try to access to my gateway via https://x.y.z:443 the browser remove `:443` (since is redundant).
@cbornet any pointer?

It's weird because the gateway urls are ok but the behavior is only on the the micro-services.

**Comment by PierreBesson** [comment]
I reproduced the setup on my local machine and I don't have the issue. I used a gateway on localhost:443 with a self-signed certificate and a microservice. I also tried replacing localhost by 127.0.0.1.

## Gateway Swagger
![capture du 2016-09-06 14-43-53](https://cloud.githubusercontent.com/assets/513471/18274003/8898bb72-7440-11e6-8521-927273d297b6.png)

## Microservice Swagger
![capture du 2016-09-06 14-43-21](https://cloud.githubusercontent.com/assets/513471/18274002/8896d960-7440-11e6-926d-7155047a3b3e.png)

The only thing that changes is that you have the the `:443` port is added for some reason but it does not cause a problem.

I really don't know were this `:80`of your come from.

**Comment by danielpetisme** [comment]
@PierreBesson The only thing different from you is that I have a traefik reverse proxy in front of my services (docker hosted).
![image](https://cloud.githubusercontent.com/assets/593564/18275131/0bce88b4-7446-11e6-8ecf-6da70fdada63.png)

I'll try to rebuild locally the architecture too.

**Comment by PierreBesson** [comment]
You got to have told me earlier about this traefik reverse proxy ! :smile: 

I think I understand what's going on here. So basically your gateway is exposed on port 80 so naturally the swagger docs point to port 80. Then you put a reverse proxy in front on port 443 (default https port) and redirect to the gateway. 

I think I have a workaround for you. Can you try tweaking the  [SwaggerBasePathRewritingFilter.java](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/gateway/responserewriting/_SwaggerBasePathRewritingFilter.java) to rewrite the host in the /v2/api-docs JSON response. Just add the following lines:

```
map.put("basePath", basePath);
String[] host = ((String) map.get("host")).split(":");
String rewrittenPort = "443";
map.put("host", host[0] + ":" + rewrittenPort);
```

If this approach works, maybe I can add a property to allow rewriting of this port. But this would really only be needed when using a reverse proxy in front.

**Comment by jdubois** [comment]
If you have a reverse proxy before our reverse proxy, you're asking for trouble :-)
And anyway perf isn't going to be good if you add more and more networks hops.

Anyway: that's not a JHipster issue so I'm closing it, then it could indeed be documented or improved

**Comment by danielpetisme** [comment]
@PierreBesson It works ! Thanks !!! in order to make the test path I just wrapped your snipper with `if(map.containsKey("host"))`

@jdubois unfortunately for the moment I have only one machine for many tools so I had to add a reverse proxy in top of my application 😢

**Comment by PierreBesson** [comment]
@danielpetisme That good to hear. Although I don't think we can put this code in the generator.

**Comment by RamjiVE** [comment]
Hi @PierreBesson @danielpetisme , I have the same issue here..
Can I able to modify at the docker label level instead of modifying the code? can i able to do that??
