### ISSUE TITLE
Displaying records from mysql database

### ISSUE THREAD

**Issue by sabari9f** [jhipster/generator-jhipster#4041]
##### **Overview of the issue**

how to retrieve and display data into a custom page from mysql database

##### **Browsers and Operating System**

64bit Windows7 Professional. Sony waio Laptop

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
