### ISSUE TITLE
Request to API not rejected for a non registered user (JWT authentication)

### ISSUE THREAD

**Issue by sergeiqiniu** [jhipster/generator-jhipster#4051]
##### **Overview of the issue**

Hi,

I am in charge of writing a webapp which is part of a bigger system. I have chosen jHipster.

Authentication is done by another webapp which is not written for the moment. I know it will send a JWT token to me.  We will share the same secret enabling me to read the information in the token.

I was not aware of this standard so I have started experimenting. I have set up one jHipster app which is supposed to mimic the authentication app and another where I should code my business logic. My main concern was to identify what were the mandatory communications between the authentication and my app so that they work together.

Doing so I have tried to send an API request with a token relative to a user defined in the authentication app but not in the business one. Surprisingly the request was not rejected. 

##### **Reproduce the error**

* Create a first monolithic Jhipster app with  JWT authentication (this is supposed to simulate the authentication app)
* For this app create a new user (let's call it "unknown")
* Fire a request for this user and write down the JWT token used for this request
* Create a second monolithic Jhipster app with  JWT authentication (this is supposed to be the business logic app). For this app there is no "unkwnon" user
* Fire a request with the token you took from the first app. For instance

curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer eyJhbGciOiJIUzUxM iJ9.eyJzdWIiOiJ1bmtub3duIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTQ3NTMyNDU0N30.30fMgrWnbpyBCs2-LXrSwY7 RkUbSRQiNRk5q-gNBvrWs7ByfsLm98hI20somsvnFUxb_JKIEm6MoPzqp3UvnJw' 'http://localhost:8080/api/users'

* The request is not rejected and produce results

##### **Suggest a Fix**

With my limited Spring experience I have noticed that such a request to the API would require authentication as stated in SecurityConfiguration class : 
```java
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .exceptionHandling()
            .authenticationEntryPoint(authenticationEntryPoint)
        .and()
            .csrf()
            .disable()
            .headers()
            .frameOptions()
            .disable()
        .and()
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        .and()
            .authorizeRequests()
            .antMatchers("/api/register").permitAll()
            .antMatchers("/api/activate").permitAll()
            .antMatchers("/api/authenticate").permitAll()
            .antMatchers("/api/account/reset_password/init").permitAll()
            .antMatchers("/api/account/reset_password/finish").permitAll()
            .antMatchers("/api/profile-info").permitAll()
------->.antMatchers("/api/**").authenticated()
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN)
            .antMatchers("/v2/api-docs/**").permitAll()
            .antMatchers("/swagger-resources/configuration/ui").permitAll()
            .antMatchers("/swagger-ui/index.html").hasAuthority(AuthoritiesConstants.ADMIN)
        .and()
            .apply(securityConfigurerAdapter());

    }
```

The authentication object is retrieved by TokenProvider  

```java
    public Authentication getAuthentication(String token) {
        Claims claims = Jwts.parser()
            .setSigningKey(secretKey)
            .parseClaimsJws(token)
            .getBody();

        Collection<? extends GrantedAuthority> authorities =
            Arrays.asList(claims.get(AUTHORITIES_KEY).toString().split(",")).stream()
                .map(authority -> new SimpleGrantedAuthority(authority))
                .collect(Collectors.toList());

        User principal = new User(claims.getSubject(), "",
            authorities);

---->  return new UsernamePasswordAuthenticationToken(principal, "", authorities);
```

In Spring javadoc I have read that this "constructor should only be used by AuthenticationManager or AuthenticationProvider implementations that are satisfied with producing a trusted (i.e. AbstractAuthenticationToken.isAuthenticated() = true) authentication token."

If I chose the two-parameters version of the constructor I get 

```json
{                                              
  "timestamp" : "2016-09-01T13:09:30.721+0000",
  "status" : 401,                              
  "error" : "Unauthorized",                    
  "message" : "Access Denied",                 
  "path" : "/api/users"                        
}
```                                       
although I do not provide any role anymore

##### **JHipster Version(s)**                                                    
                                                                                                
java version "1.8.0_91"                                                                         
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)                                            
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)                                 
                                                                                                
git version 1.9.5.msysgit.1                                                                     
                                                                                                
node: v6.3.1                                                                                    
                                                                                                
npm: 3.10.6                                                                                     
                                                                                                
bower: 1.7.9                                                                                    
                                                                                                
gulp:                                                                                           
[15:12:30] CLI version 3.9.1                                                                    
                                                                                                
yeoman: 1.8.5                                                                                   

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "app2",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "81cd696ffb0e0ab38649c10044f8046e0ff86bc6",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

Windows 7, Chrome 52

**Comment by jdubois** [comment]
Do you share the same secret token for both of your applications? If so, then they trust each other, so the second app is authenticating the user.

**Comment by sergeiqiniu** [comment]
Yes they share the same secret.

What I do not get is that I can fire a request with a JWT token containing a sub set to a principal unknown to the app and that it is not rejected.

Did I miss something ?

**Comment by jdubois** [comment]
If the second app has the same secret key, it trusts the first one, so it automatically authenticates the user, even if it doesn't exist.

This isn't the normal use case for JHipster, you either have:

- Independent monoliths, that don't share the same secret
- Microservices, that share the same secret, and where only one app (the gateway) has user information

As you don't have a gateway, you'll find that sharing the secret between 2 monoliths won't do anything -> how are you going to pass the JWT token from app to another? That's not possible from a browser.

I'm closing this as this is not a bug.

**Comment by sergeiqiniu** [comment]
Thanks for that comment

I was hoping to avoid doing microservices but I think I have to switch to it

**Comment by capgeminiab** [comment]
aaaaaaaaaa
