### ISSUE TITLE
findAllWithAuthorities,  pageable content and count num are not equal.

### ISSUE THREAD

**Issue by clong365** [jhipster/generator-jhipster#4056]
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.0",
    "baseName": "gateway",
    "packageName": "net.jiean.iedu",
    "packageFolder": "net/jiean/iedu",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "551141a35253810f721e8260b273db887aa76a9b",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Overview of the issue**

findAllWithAuthorities  pageable content and count num are not equal.

##### **Motivation for or Use Case**

@Query(value = "select distinct user from User user join fetch user.authorities",
        countQuery = "select count(user) from User user")

countQuery get all users in the User domain, but the select sentence do not return anonymous user that with no authorities.

**Comment by jdubois** [comment]
Looks like a good catch!
In fact the method name isn't that good (my fault!), what I meant is "users with eager loading of authorities", so there should be an outer join here (to also take users with no authorities)

**Comment by MuhammadHewedy** [comment]
Also, this query returns all users from the database to hibernate where hibernate do pseudo paging, Is this consider a performance issue?
`HHH000104: firstResult/maxResults specified with collection fetch; applying in memory!`
