### ISSUE TITLE
Revisit the logic for default profile setup

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#4059]
In order to have the default profile used for build in deploy as well `dev|prod` we currently read the `application.yml` and set it manually due to a spring boot bug discussion here https://github.com/jhipster/generator-jhipster/pull/3585
Since spring boot 1.4 has a partial fix https://github.com/spring-projects/spring-boot/issues/5998 so we can revisit and see if we can remove the workaround code 

- [x] Test default bootrun
- [x] Test default bootrun -Pprod
- [x] Test package
- [x] Test package -Pprod
- [x] Test IDE run
- [x] Test IDE run -Pprod

**Comment by jdubois** [comment]
Good! I didn't like that hack :-)

**Comment by deepu105** [comment]
Me too, I was waiting to remove the hack, I have tried and it works but unfortunately there is another side effect/glitch as mentioned [here](https://github.com/spring-projects/spring-boot/issues/5998#issuecomment-244528333) It can be worked around but I'm not liking the work around as it needs changes in many places. so lets wait to see what the spring guys have to say first
