### ISSUE TITLE
Remove Jackson configuration bean

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#4060]
The default serialization of ZonedDateTime by Jackson is "yyyy-MM-dd'T'HH:mm:ss.SXXX" where the fractional seconds can go up to 9 digits. We currently replace that by "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" to ensure serialization in UTC time zone with a fixed 3 fractional seconds digits.
Although the ES5 spec specifies 3 fractional seconds digits, I've tested on Chrome52, Firefox 47 and IE 11 that the string "2016-09-02T22:30:44.168123456+02:00" is correctly parsed.
Also since we convert ZonedDateTime to Date before storage, the nanoseconds are lost anyway.

So I wonder if we can remove our custom jackson config and use jackson-datatype-jsr310's default one as per Policy 1.
It would also benefit to people that want to transmit the time-offset for something or that need to use nanosecond precision for some services (not for entities since we don't store the time-offset).

Or does anyone knows a browser version for which that will cause issue ?

**Comment by jdubois** [comment]
Oh, I'm the one who coded that, and I didn't go to that level of detail!

**Comment by cbornet** [comment]
Other note : We are currently using ZonedDateTime as an Instant but in reality ZonedDateTime is not directly an Instant. It's a LocalDateTime + a ZoneId that is converted to an Instant using ZoneRules and these rules may change for political reasons (imagine France abandons daylight saving time).
So ZonedDateTime would be used for calendar appointments and such (my meeting will be at 8 AM [Europe/Paris] even if the ZoneRules change since then) whereas OffsetDateTime/Instant would be used for timestamping (independant of DST).
Fully supporting ZonedDateTime would mean storing it as a localdate + zone ID so that if the rules change between storage and reading, the Instant also changes.
And we would need to support OffsetDateTime or Instant because most of the time what people actually want is a timestamp.

**Comment by cbornet** [comment]
I also tested it OK with Safari 5.1.7.
Any expert front-end dev with an old IE9/10 versions that could do the test ?
