### ISSUE TITLE
Run yo jhipster:aws nothing happens

### ISSUE THREAD

**Issue by jeansousasantos** [jhipster/generator-jhipster#4064]
Hi,

This my   `.yo-rc.json` 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "gestor_6_0",
    "packageName": "com.everest.gestor",
    "packageFolder": "com/everest/gestor",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "8b1f1ea204ab7bdf1f978cea689f52085fc962d4",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br",
      "en"
    ]
  }
}

I try to deploy jhipster application in aws. I follow the https://jhipster.github.io/aws/.

But when i run 'yo jhipster:aws' notthing happens. Just go to prompt again.

Anyone help me please?

I'm using Chrome and OS El Captain.

Regards.

**Comment by ruddell** [comment]
@jeansousasantos Please read the [AWS Subgenerator docs](http://jhipster.github.io/aws/) and install the required dependencies.  There was an issue where the error message did not display, but in the next release the dependencies will automatically install for the user.

**Comment by jeansousasantos** [comment]
@ruddell thank you very much by quick and accurate answer. Its working fine now.
