### ISSUE TITLE
HeaderUtil headers incorrect on microservices

### ISSUE THREAD

**Issue by danielbrutti** [jhipster/generator-jhipster#4075]
##### **Overview of the issue**

Hi, I'm working on a microservices application. I had to develop a new validation based on `idexists` one, I just sending this response on the Resource controller:

``` java
return ResponseEntity.badRequest().headers(HeaderUtil.createFailureAlert("Device", "identifierexists", "An existent Device has the same Identifier.")).body(null);
```

and then in `global.json` added this:

``` json
"error": {
       ...
        "identifierexists": "An existent {{ entityName }} has the same Identifier"
    }
```

However, when returning the error to angular using the `HeaderUtil.createFailureAlert` method as above, the response does not contains the headers `X-budderflyManagementApp-error` and `X-budderflyManagementApp-params`. Both headers are not received on `errorhandler.interceptor.js` and eventually on `alert-error.directive.js`

The microservice backend project/module is `budderflyManagementApp` and the gateway `budderflyManagementGatewayApp`
##### **JHipster Version(s)**

3.4.2
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

``` json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "BudderflyManagement",
    "packageName": "com.cme.budderfly",
    "packageFolder": "com/cme/budderfly",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "2233589c5c88d0cf88bbea5c0ada3e44ec16693f",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
```
##### **Browsers and Operating System**

ElementaryOS (based on Ubuntu 14.04), Chrome Version 49.0.2623.75

**Comment by ruddell** [comment]
Instructions to reproduce

1. Generate a UAA (unrelated), microservice (`micro`), and gateway (`gway`).
2. Generate an entity in the microservice.
3. Replace the `return` in the create method with the `return` from the first post
4. On an entity creation, I see the headers `X-microApp-error:error.identifierexists`, `X-microApp-params:Device`
5. I can verify the error is received in `errorhandler.interceptor.js` and `alert-error.directive.js`
6. A red error alert is displayed, but no text.

The lack of text is because lines 51/52 of `alert-error.directive.js` (see below) hardcode the error header's name using the gateway's appName.
```
var errorHeader = httpResponse.headers('X-gwayApp-error');
var entityKey = httpResponse.headers('X-gwayApp-params');
```
There will only be one error header at a time, so we should check for `X-*-error` and `X-*-params` headers.  The following code solves the issue and displays errors from any microservice/gateway.  Is there an easier way to filter HTTP headers?

```
var headers = Object.keys(httpResponse.headers()).filter(function (header) {
    return header.split('-')[2] === 'error' || header.split('-')[2] === 'params'
});
var errorHeader = httpResponse.headers(headers[0]);
var entityKey = httpResponse.headers(headers[1]);
```

**Comment by mehmet-aslan** [comment]
Entity create/update/delete alerts have similar issue. Microservice adds `X-microApp-alert` and `X-microApp-params` to headers but gateway tries to get alert&params headers using `gatewayAppName` at `notification.interceptor.js`.
``` javascript
var alertKey = response.headers('X-gatewayApp-alert');
if (angular.isString(alertKey)) {
	AlertService.success(alertKey, { param : response.headers('X-gatewayApp-params')});
}
```
I tried @ruddell's solution, it seems that `headers` is filled in reverse order so `headers[0]` and `headers[1]` should be switched.

Also `X-microApp-alert` header's value includes name of microservice app for created/updated/deleted alerts but their messages are under the `gatewayAppName` in `entity.json`.
```
{
    "gatewayApp": {
        "foo" : {
            ...
            "created": "A new Foo is created with identifier {{ param }}",
            "updated": "A Foo is updated with identifier {{ param }}",
            "deleted": "A Foo is deleted with identifier {{ param }}",
            ...
        }
    }
}
```
These lines may be moved under the `microserviceAppName` if the entity belongs to a microservice.

**Comment by mehmet-aslan** [comment]
@ruddell if you are not working on this, I will make a PR to correct both error and alert headers using your solution.

**Comment by jdubois** [comment]
This is all my fault, and I know this is not working, but the original idea is that you have different headers depending on which microservice sends the message. I'm not sure it was such a great idea, now, and we have no use case for this, that I know of.

There are other solutions like:

- Have a Zuul filter that modifies the request: headers could be re-written there.
- Have the same headers for all microservices (when the microservice type is selected), like 'X-jhipster-error'

That second solution might be easier, what do you think?

**Comment by mehmet-aslan** [comment]
Don't you prefer the javascript parse option? Even if microservices use same headers, created/updated/deleted messages need to move under this header name. It isn't much different and maybe different headers could be meaningful at sometime(even though you said no use case for now).

**Comment by jdubois** [comment]
I'm afraid that looking for `X-*-error` could make you find other headers than the ones sent by JHipster, they are not specific enough. Then, of course, this would work and be less trouble.
I'm eager to have feedback here!

**Comment by ruddell** [comment]
@jdubois To make sure we only get JHipster headers, we can search for `X-*App-error` or `X-*App-params` ('App' is added on to the base name automatically).  I prefer having the app name rather than a generic `X-jhipster-error` header - this really only benefits the developer though.

@mehmet-aslan Feel free to claim this fix, I would wait until the correct path is decided.

**Comment by jdubois** [comment]
@ruddell the original idea what that we never wrote "jhipster" anywhere: it's just a generator, and then that's your app, so it's your code... This has changed quite a lot in the last 2 years, and now we do have some "jhipster" from time to time, and that doesn't seem to annoy people.
What I'm afraid with `X-*App-error` is that you could get this message from elsewhere (agreed, the `App` probably limits this), and that it's not very clear. Then, of course, it allows to separate microservices if needed, which was the original goal: we don't have a use case for this now, but I can imagine people might use this.
Anyway, I haven't got a strong opinion on this, if you'd rather do `X-*App-error`, then at least it's less work (no work on the backend!!), so let's do it this way.

**Comment by mehmet-aslan** [comment]
Could `jhiPrefix` variable be added as prefix to headers? `X-<jhiPrefix>-*App-error` will be more specific to JHipster apps. I saw it only used in client generator and you prefer to use it at minimum but it might be meaningful in this case.

**Comment by mehmet-aslan** [comment]
Oh nevermind, I messed it up. It is application specific too.
