### ISSUE TITLE
[question] Any reasons for the spaces after AbstractAuditingEntity.last_modified_date field name

### ISSUE THREAD

**Issue by fingahoverit** [jhipster/generator-jhipster#4077]
##### **Overview of the issue**
I was just wondering why the Field annotation value for **lastModifiedDate** (on **AbstractAuditingEntity** class) has 2 spaces at the end.

```java
    @LastModifiedDate
    @Field("last_modified_date  ")
    @JsonIgnore
    private ZonedDateTime lastModifiedDate = ZonedDateTime.now();
```

##### **Motivation for or Use Case**
I'm just reading code for learning best practices and understanding hipster code.

##### **Suggest a Fix**
Remove the spaces?

**Comment by xetys** [comment]
It looks like some typo to be, too. For me, there is no meaningful reason to keep it like that. We'll check that

**Comment by deepu105** [comment]
Yes definitely a typo

Thanks & regards,
Deepu
