### ISSUE TITLE
[FEATURE] Password Strength Bar should apply a saner policy

### ISSUE THREAD

**Issue by toolforger** [jhipster/generator-jhipster#4080]
(Newbie warning: I have a few decades of programming under my belt, but do not know much about Angular, JHipster, or even JavaScript. I hope I did everything right, please bear with me if I didn't.)

##### **Overview of the issue**

`generator-jhipster/generators/client/templates/src/main/webapp/app/account/password/_password-strength-bar.directive.js` puts much weight on the presence of characters from multiple sets (lowercase, uppercase, digits, specials).

##### **Motivation for or Use Case**

The strength meter display is wildly inaccurate. For example, a five-word Diceware-style password will be flagged as weak, but in reality it is pretty strong.

##### **Reproduce the error**

Use the password-change page on a JHipster-generated app.
Enter the two example passwords from https://xkcd.com/936/ :
"Tr0ub4dor&3" (28 bits of entropy) gives full five bars and green.
"correct horse battery staple" (44 bits of entropy) gives a single red bar.
I.e. the password that's safer by orders of magnitues is given a much worse rating.

##### **Related issues**

I didn't find any.

##### **Suggest a Fix**

Rewrite `generator-jhipster/generators/client/templates/src/main/webapp/app/account/password/_password-strength-bar.directive.js` so that it applies a saner metrics.

One approach would be to calculate the average number of attempts to brute-force the password, and relate that to the number of brute-force attempts per seconds that are available to an attacker at semiprofessional level (33 billions per second, see http://blog.zorinaq.com/whitepixel-v2-configurable-charset-higher-performance-331-billio/ as a source).
I know the basic format of the formula (it's `password_lengh/log(character_set_size)*some-constant`, where `character_set_size` would be the number of different characters in the password (minus deductions for patterns like `1234`), plus a bit of logarithm fiddling and second-to-years conversions to figure out `some-constant`.

I general, I wouldn't trust any metrics that do not come with an explanation of the math involved: these tend to be arbitrary, which means that they will almost always be either too strict or too lenient, raise false alarms of let through truly unsafe passwords.

##### **JHipster Version(s)**

3.6.1 (current as of writing this issue)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

Couldn't find that file - I guess it was removed (I didn't run the generator).
I hope it's irrelevant to the issue :-)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Entities do not affect this I believe.

##### **Browsers and Operating System**

Independent of browser and OS.

**Comment by jdubois** [comment]
- You are correct, this directive was like our first attempt at showing how to do a directive in JHipster, so it's pretty basic.
- But directives will die with AngularJS 2, and we are now focusing on the AngularJS 2 migration -> all the AngularJS 1 code is frozen for the moment

I'm closing this for this reason, but yes we will need a better algorithm, both for AngularJS 1 and 2, and hopefully we could find one outside of the project, and not code it ourselves.

**Comment by toolforger** [comment]
I googled a bit, I didn't find any good algorithm - vast majority was more-or-less the same as here, none explained what they were trying to achieve.
Well... given that this isn't going to be fixed anytime soon, and that I'm not going to get the time budget to fix this in our project, I guess we'll simply disable password strength checking.
Anyway - thanks for the feedback! It's very reassuring to know that the problem as such is acknowledged, and it's helpful to know why it cannot be fixed by the project.

**Comment by jdubois** [comment]
It's just that we need to prioritize, and we can't have both AngularJS 1 and AngularJS 2 being developed at the same time.
BTW, if you have the budget (or anyone has), feel free to do a PR with a solution
