### ISSUE TITLE
LocalDate entity fields get empty and invalid between save request and modal closing

### ISSUE THREAD

**Issue by ArturoGalan** [jhipster/generator-jhipster#4081]
##### **Overview of the issue**

Microservice Gateway and a Microservice application:
I've created an entity Patient with the DateTime field 'birthDate', when I access to the Create Dialog in the gateway front for this entity, fill the birthDate, and submit the form pressing the Save button:  The field 'birthDate' gets empty and in validation error (red color) for a couple of seconds. After that the Dialog closes and the registry is correctly created with the birthDate time that I previously filled.

##### **Motivation for or Use Case**
The entity is correctly created, but the user experience is not correct because you don't know if the Date field has been created when you see the empty input for a couple of seconds while the 'saving' process is executing.

##### **Suggest a Fix**

In the service angular file created for the entity, (entity.service.js) the methods POST and PUT are using the transformation functions with the data object passed by parameter directly. 

```
         'save': {
                method: 'POST',
                transformRequest: function (data) {
                    data.birthDate = DateUtils.convertLocalDateToServer(data.birthDate);
                    return angular.toJson(data);
                }
            },
```

This is not recommended as you can see in [https://docs.angularjs.org/api/ng/service/$http](https://docs.angularjs.org/api/ng/service/$http)  (Transforming Requests and Responses section)

Modifications to the object's properties in a transformRequest function will be reflected on the scope and in any templates where the object is data-bound.

I suggest to make a copy of the passed object, to transform the date that is going to be sent to the server:

```
         'save': {
                method: 'POST',  
                transformRequest: function (data) {  
                    var dataToSend = angular.copy(data);
                    dataToSend.birthDate = DateUtils.convertLocalDateToServer(dataToSend.birthDate);
                    return angular.toJson(dataToSend);
                }
            }
```

##### **JHipster Version(s)**
jHipster 3.6.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "gateway",
    "packageName": "com.ecosw.test",
    "packageFolder": "com/ecosw/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "dc9022fc3c19f98c45c070a06a10f8dfeaab013f",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es",
      "en"
    ],
    "enableSocialSignIn": false
  }
}

##### **Browsers and Operating System**
Windows 7, Chrome v 52.0.2743.116 m

**Comment by FritzLuber** [comment]
This occours for Monolithic applications too. Same fix works
