### ISSUE TITLE
createdBy-value missing in User-Management-Details-View

### ISSUE THREAD

**Issue by FritzLuber** [jhipster/generator-jhipster#4082]
**Overview of the issue**
I noticed, that in the user-management-detail-view the field "createdBy" never contains sth.

**Reproduce the error**
To reproduce the error simply add a new user in a newly generated app and navigate to the details view. createdBy should be missing

**Suggest a Fix**
I figured out, that the class src/main/java/*.*.*.web.rest.vm.ManagedUserVM (in 3.6.0 replace VM with DTO) misses:
- the attribute "private ZonedDateTime createdDate;"
- the following line in the constructor ManageUserVM(User user) "this.setCreatedBy(user.getCreatedBy());"

If unit-tests should check this as well, the other constructor misses the same line and needs a "createdBy" parameter as well. The affected unit-test would be AccountResourceIntTest.

**JHipster Version(s)**
generator-jhipster@3.6.1 (previous Version as well)

**JHipster configuration**
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "myapp",
    "packageName": "com.test.app",
    "packageFolder": "com/test/app",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ]
  }
}
**Entity configuration(s)**
no entities

**Browsers and Operating System**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)
git version 2.9.2.windows.1
node: v6.3.1
npm: 3.10.3
bower: 1.7.9
gulp:
[16:41:00] CLI version 3.9.1
[16:41:00] Local version 3.9.1
yeoman: 1.8.5
Docker version 1.10.3, build 20f81dd
docker-compose version 1.6.2, build e80fc83

Browser firefox latest.

I haven't had the time to test this on an other browser/pc but it should appear there too.

**finally**
since this is my first bug report on github i hope i did everything right. If not, pls critizize as much as you can, so i can learn from my mistakes :)

**Comment by ruddell** [comment]
@FritzLuber Nice catch, thank you for your first bug report!  It was easy to follow and the fix is already merged.

**Comment by FritzLuber** [comment]
Thanks for the feedback! Keep up the good work.
