### ISSUE TITLE
Why CustomAuditEventRepository is skipping AUTHORIZATION_FAILURE auditing

### ISSUE THREAD

**Issue by gouravsood** [jhipster/generator-jhipster#4085]
Hi,

I am working on JHipster code base to build my test app and just figured out, in the CustomAuditEventRepository (used as implementation of Spring Boot's AuditEventRepository), auditing of AUTHORIZATION_FAILURE is specifically being avoided. Is there any specific reason why this has been done?

I think its better to audit AUTHORIZATION_FAILURE as well, because with that you can find how many API calls are happening with authorization failure.

Thanks,
Gourav.

##### **JHipster Version(s)**

generator-jhipster@3.5.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
`
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "test",
    "packageName": "com.test.platform",
    "packageFolder": "com/test/platform",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
`

##### **Browsers and Operating System**

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)

git version 1.9.5.msysgit.1

node: v4.4.4

npm: 3.9.2

bower: 1.7.9

**Comment by jdubois** [comment]
Can you check in the older tickets?
I remember this was being thrown each time a non-logged in user did a request, and that was filling the table with useless information. This should also be linked to the commit message for that part of the code, can you have a look?
Sorry I'm using my phone so I can't do this at the moment.

**Comment by pascalgrimaud** [comment]
@gouravsood : you can look the discussion on this ticket https://github.com/jhipster/generator-jhipster/issues/1882

**Comment by gouravsood** [comment]
Thanks @pascalgrimaud and @jdubois for sharing the insights & pointers. I will followup these thread.

**Comment by jdubois** [comment]
Happy to still have a good memory :-)
