### ISSUE TITLE
How can i use data from social login

### ISSUE THREAD

**Issue by rhpereda** [jhipster/generator-jhipster#4086]
When hjipster generate login for social networks, it includes the data retrieved (image_url, provider_id, profile_url, etc) into a table with named jhi_social_user_connection, but in the login process only load from database the data from the jhi_user table. 
I need the the image_url from the social network that the user use to authenticate (the user can authenticate for more than one social network) in the user profile page.
This could be achieve easily if I could know somehow wich kind of user is authenticated, but I can´t found the way to do this...
Any help or suggestions will be appreciated...
thanks in advance

**Comment by jdubois** [comment]
This isn't a bug, could you post this on Stackoverflow with the jhipster tag?
