### ISSUE TITLE
Feature Request - Add image for user

### ISSUE THREAD

**Issue by rhpereda** [jhipster/generator-jhipster#4095]
In several sites, the user can load to his profile an image for his account, or load it automatically when user use social login. 
Is possible to include this into new releases?

Best regards

**Comment by jdubois** [comment]
If this is just for social login:

- I guess Google/Twitter/Facebook all have some pre-defined URLs for those images, so we just need to know those URLs, and that's very easy
- If it's not the case, then the URL should come from Spring Social - hopefully they provide this!

@rhpereda as you are asking for this, did you have a look at this? Do you know how it works? That looks like an easy PR to do.

**Comment by jdubois** [comment]
Sorry, we can't do this right now, as we must first complete the AngularJS 2 migration (my fault, I should have answered that in the first place).
So I'm closing this and putting a "willdolater" label, but that's definitely something we could have in the project.
@rhpereda can you still check how this should be done? This will make it easier to do later, anyway, so it's time well-spent.

**Comment by deepu105** [comment]
@rhpereda dont worry this is part of my plan for #4110 hence please add your comments there if you are doing any research on this
