### ISSUE TITLE
[FEATURE] Using local bower in yeoman.gradle

### ISSUE THREAD

**Issue by bjoernw** [jhipster/generator-jhipster#4102]
##### **Overview of the issue**

When setting up a jenkins job for my jhipster project I was able to avoid having to install bower globally by changing yeoman.gradle to use the local version of bower in node_modules.

```
task bower(type: Exec) {
    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        commandLine 'cmd', '/c', 'bower', 'install'
    }else{
        commandLine 'node_modules/bower/bin/bower', 'install'
    }
}
```
What do you think? We already download bower, might as well use it.

**Comment by deepu105** [comment]
If there is a local version present `bower install` would use that. Thats my understanding of how npm stuff works. SO I dont know why you need to point it to the local copy specifically?

**Comment by atomfrede** [comment]
Does is it also work on Windows and with gradle? But I don't see the advantage at the moment.

**Comment by bjoernw** [comment]
Jenkins kept complaining about not knowing the command "bower". It's not installed with npm install -g on the Jenkins box. The only thing, besides installing bower globally that fixed it for me was to point it at the local copy.

**Comment by atomfrede** [comment]
Have you locked at http://jhipster.github.io/setting-up-ci-linux/? When using the Jenkins node plugin you can declare globally installed packages which works fine.

**Comment by bjoernw** [comment]
@atomfrede Yes, I saw that. I could have installed them (or in my case, asked another team to please install them whenever they get to it...) but in the end it was just easier to point it at the local versions that npm already downloaded (both gulp and bower).
Not a big deal, just a little hiccup when you don't have admin rights on your CI system.

**Comment by atomfrede** [comment]
@bjoernw Ah I see (and I know the problem). Maybe you can put it into the tips section of the documentation? http://jhipster.github.io/tips/

**Comment by jdubois** [comment]
From my understanding this will disappear with AngularJS 2 -> let's focus on AngularJS 2 instead

**Comment by jdubois** [comment]
I'm closing this, as the AngularJS 2 focus is more important at the moment, and Bower should die after that.
