### ISSUE TITLE
DNS Service Discovery with Kubernetes

### ISSUE THREAD

**Issue by pkrishanth** [jhipster/generator-jhipster#4106]
##### **Overview of the issue**

Currently deploying jhipster micro services on kubernetes cluster which is using jhipster registry for service discovery. But we would like to use DNS for service discovery and kubernetes config map for application properties 

##### **Motivation for or Use Case**
We would like to use the default functionality of kubernetes and eliminate the overhead of deploying additional jhipster registry container  on the cluster

**Comment by jdubois** [comment]
I'm sorry but you use a DNS server instead of the Registry, then we would need to remove the whole Netflix stack... Not something we could do easily.
Besides, that would remove all service breakers, load balancing, automatic fail-over... Which is not something I'd like at the moment.

**Comment by xetys** [comment]
in addition to this, there is some project [kubeflix][], which combines the strenghts from both....and I have seen some good article some days ago...I will take a look.

For the moment I think some individual solution must be found for that issue


[kubeflix]: https://github.com/fabric8io/kubeflix

**Comment by PierreBesson** [comment]
@pkrishanth Eventually this might come to JHipster in the future.
What you are looking for is: [https://github.com/fabric8io/spring-cloud-kubernetes](https://github.com/fabric8io/spring-cloud-kubernetes).

It's very easy to replace `spring-cloud-eureka` by this, I have already done it. You will even have all your kubernetes services showing up in the gateway.

Moreover on the contrary to what @jdubois said, components of the Netflix (Ribbon, Hystrix, Zuul) stack will still be working.

**Comment by pkrishanth** [comment]
Thanks @PierreBesson , I have done that already :) in a branch , need to deploy & test it on the cluster.

Have you changed anything in the code ?

**Comment by PierreBesson** [comment]
@pkrishanth You normaly just need to change a few properties and annotations on the main class.  You can use minikube to test in dev first.

If you can please give feedback and propose improvement on the kubernetes subgen.

**Comment by pkrishanth** [comment]
@PierreBesson , I have removed EnableEurekaClient annotation , removed eureka related properties from ymal file and added spring-cloud-kubernetes in the pom.

But getting "UnknownHostException: kubernetes.default.svc: unknown error"

Have you got any Idea?

**Comment by PierreBesson** [comment]
Sorry @pkrishanth I don't have any idea.

**Comment by pkrishanth** [comment]
Re-generating my apps with 3.9.1 version
Hope no service discovery & configuration option gonna help me

**Comment by PierreBesson** [comment]
@pkrishanth please dont comment on an old issue. For support please use Stackoverflow rather than github issues.

**Comment by mootezbessifi** [comment]
@PierreBesson  thank you for you clarification but may you give me more explanation of this [comment](https://github.com/jhipster/generator-jhipster/issues/4106#issuecomment-245946986) what exactly i need to do in the purpose of replacing Eureka service discovery with kubernetes dns

**Comment by PierreBesson** [comment]
@mootezbessifi, this is currently out of the scope of JHipster. Have a look at the spring cloud kubernetes project linked above but I can't help you further not being a user myself.

And please don't comment on an old issue.

**Comment by jdubois** [comment]
Sorry guys but this is a bug tracker, only for JHipster issues... I'm locking this conversation
