### ISSUE TITLE
Promote the JHipster Docker Hub

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#4119]
Something I wanted to do for long time: promote our [Docker Hub page](https://hub.docker.com/u/jhipster/dashboard/) by adding sample applications + documentation. If I remember well, @jdubois you wanted it too!
- [X] code a Dockerfile to make automated build possible
- [X] jhipster-sample-app
    - [X] config docker hub
    - [X] config the settings on github project
    - [X] pull request to jhipster-sample-app
    - [X] check and test the Docker image
- [X] jhipster-sample-app-elasticsearch
    - [X] config docker hub
    - [X] config the settings on github project
    - [X] pull request to jhipster-sample-app-elasticsearch
    - [X] check and test the Docker image
- [X] jhipster-sample-app-mongodb
    - [X] config docker hub
    - [X] config the settings on github project
    - [X] pull request to jhipster-sample-app-mongodb
    - [X] check and test the Docker image
- [X] jhipster-sample-app-cassandra
    - [X] config docker hub
    - [X] config the settings on github project
    - [X] pull request to jhipster-sample-app-cassandra
    - [X] check and test the Docker image
- [X] jhipster-sample-app-gateway
    - [X] create project on github
    - [X] add project to [jhipster-automated-samples](https://github.com/jhipster/jhipster-automated-samples)
    - [X] config docker hub
    - [X] config the settings on github project
    - [X] pull request to jhipster-sample-app-gateway
    - [X] check and test the Docker image
- [X] jhipster-sample-app-microservice
    - [X] create project on github
    - [X] add project to [jhipster-automated-samples](https://github.com/jhipster/jhipster-automated-samples)
    - [X] config docker hub
    - [X] config the settings on github project
    - [X] pull request to jhipster-sample-app-microservice
    - [X] check and test the Docker image
- [X] create new project which will contain all docker-compose files (generated by our subgenerator docker-compose), using these official images
- [X] write documentation on all jhipster images we provide

The main goal is to provide an example of a generated application, like jhipster-registry

**Comment by PierreBesson** [comment]
This was on my mind as well.
I would also like to have new samples for microservice and gateway apps (maybe with some entities generated).
Also ideally we should tag those app images with the jhipster version.

What I was thinking was that instead of using a docker hub automated build to create those images we could instead use Travis to build the docker images with the maven plugin and then push those to docker hub.

**Comment by pascalgrimaud** [comment]
@PierreBesson :
- good idea about gateway and microservice, I update my ticket
- about Travis, we could push to docker hub, but I already see few minor issues:
    - we already use a lot of Travis ressource
    - we will lost the tag "automated build" on docker hub -> I think a lot of people prefer using an automated image instead of a pushed image, they can check the source code before launching the image on their machine (that's why I always do)
    - can you tell me why you think it's better to push the image with Travis ?

**Comment by PierreBesson** [comment]
I think you do have a point with the advantages of the automated build, especially being able to see the code might be very important for users, so let's go your route.
However those would be my reason to build with Travis:
- Follow best practices: "ship artifacts not build environment"
- Be able to have a fine grained control on tags, for example push images with both build version and git commit tags.
- More naturally fit into a CI pipeline (don't even try to build the image if the build fails).
- Works with other registries than Docker Hub
Then maybe this could be done as part of a separate demo to showcase how to manage your builds artifacts with JHipster and Docker.

**Comment by pascalgrimaud** [comment]
Nice points! For a real project, we should follow this pipeline.

**Comment by atomfrede** [comment]
Sounds cool. I have started to make an example how to build, release and deploy with gitlab and gitlab ci. The deploy step is not yet implemented, but building a pipeline is pretty cool.

**Comment by pascalgrimaud** [comment]
The first image is online. To test it, simply run docker with:
`docker run -p 8080:8080 -e SPRING_PROFILES_ACTIVE=dev jhipster/jhipster-sample-app:master`

**Comment by PierreBesson** [comment]
@pascalgrimaud Let's do the microservice docker hub sample together on wednesday at the JHipster Hackaton.

**Comment by pascalgrimaud** [comment]
@jdubois : are you ok to create a new project, which will contain all docker-compose files (generated with the sub generator) to use all these new images ?
if yes, how can we call it ? jhipster-docker-hub ?

**Comment by pascalgrimaud** [comment]
@jdubois : yesterday, you did a new release, and used your [jhipster-automated-samples project](https://github.com/jhipster/jhipster-automated-samples)

But it seems that the 3 projects (elasticsearch, mongodb and cassandra) weren't updated -> probably because of my pull requests, so your local projects have conflicts when you wanted to update them. Can you have a look plz ?

**Comment by jdubois** [comment]
Sorry I won't have time until next week - is that really bad?

**Comment by pascalgrimaud** [comment]
Not bad and not urgent at all.
I just wanted to notice you
Le 23 sept. 2016 8:52 AM, "Julien Dubois" <notifications@github.com> a
écrit :

Sorry I won't have time until next week - is that really bad?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/4119#issuecomment-249116290>,
or mute the thread

**Comment by pascalgrimaud** [comment]
@PierreBesson : I start this https://github.com/pascalgrimaud/jhipster-docker-hub
If you have time for testing this, plz

**Comment by pascalgrimaud** [comment]
@PierreBesson : I did everything on my side!
If you think you can work on gateway+microservice app, I let this ticket opened. Otherwise, it can be done later and I close this (to reduce the number of tickets opened)

**Comment by PierreBesson** [comment]
Good job ! I just used your work to demo the Console to a colleague yesterday. I will do the microservice and gateway later and close the ticket.

**Comment by pascalgrimaud** [comment]
Thanks Pierre ! So let's wait before tweeting about this ;-)

**Comment by pascalgrimaud** [comment]
@PierreBesson : do you need help on this ?

**Comment by PierreBesson** [comment]
Yes I dont know when I will have the time to do it. I also have other things of higher priority like the docs/readme issue and some checking on newly introduced consul acl management.

Also I was thinking that it would be more interesting to do a full featured microservice demo rather than just one gateway and one microservice. So that we can test a more real usecase and showcase monitoring, I would also like to try out tracing requests with Zipkin. So many things to do.....

**Comment by pascalgrimaud** [comment]
I think we should do something very simple first, for the gateway and one microservice.
Because with these images, we will be able to build a bigger microservice architecture.

So for starting this, as you has full right, can you init a simple README.md on :
- https://github.com/jhipster/jhipster-sample-app-gateway
- https://github.com/jhipster/jhipster-sample-app-microservice
Then, I will PR on these projects

**Comment by PierreBesson** [comment]
@pascalgrimaud I initialized the projects so you can now PR on them.

**Comment by pascalgrimaud** [comment]
Thanks @PierreBesson !!!
Le 14 oct. 2016 6:07 PM, "Pierre Besson" <notifications@github.com> a
écrit :

**Comment by pascalgrimaud** [comment]
I'm updating the documentation, then I can close this ticket
