### ISSUE TITLE
[feature] Package layout

### ISSUE THREAD

**Issue by lrkwz** [jhipster/generator-jhipster#4125]
I see that jhipsters have choosed the "package by layer" approach; I think it would be extremely nice to have the chance to choose between "package by layer" and package by feature" approach.

PRO:

* reduced coupling between packages
* modularization
* ...

How deep is this behavior in jhipster's code?
How easily can it be changed/overloaded?

**Comment by jdubois** [comment]
This has already been discussed many times...

**Comment by lrkwz** [comment]
sorry I searched for it a little but didn't find ...
What do you think about it?

**Comment by jdubois** [comment]
#3496 for example.
Besides, we now have the microservices architecture for more complex needs.

**Comment by jdubois** [comment]
But I agree there is something to study here: our front-end code has been refactored some time ago to be more "package by feature", so we have an inconsistancy.

**Comment by jdubois** [comment]
Anyway, it's highly complex to do, and I'm not sure it's such a good idea:

- lots of package tangling (this is going to be annoying with Hibernate, for example)
- if you can split your app in totally separate modules then you'd better do microservices
- we can't do any "business" requirement, we're just a technical project -> then you need to refactor your app according to your business needs, which is very easy with an IDE
