### ISSUE TITLE
Swagger profile not active by default in dev mode

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4130]
On JHipster 3.7.0, when the app is run in "dev" mode from an IDE, the "swagger" profile is not active by default, so the API is not available.

**Comment by PierreBesson** [comment]
@deepu105, already notified me of this bug (#4112). Would be nice if we could work around it or if we can't do that add some documentation about it.

**Comment by deepu105** [comment]
I have already added documentation for it here http://jhipster.github.io/profiles/

@jdubois its a glitch only when run from IDE its due to https://github.com/spring-projects/spring-boot/issues/6833#issuecomment-246093943

**Comment by deepu105** [comment]
closed via #4146
