### ISSUE TITLE
Cannot run jhipster.github.io using docker

### ISSUE THREAD

**Issue by mhavrlent** [jhipster/generator-jhipster#4131]
##### **Overview of the issue**

When I follow instructions on how to run jhipster.github.io using docker [here](https://github.com/jhipster/jhipster.github.io) I get this error message:

```
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:35:in `block in setup': You have already activated json 2.0.2, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `map'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `setup'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
	from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<main>'
sh: can't kill pid 150: No such process

```

##### **Motivation for or Use Case**

I was trying to fix another bug in documentation.

##### **Reproduce the error**

git clone https://github.com/jhipster/jhipster.github.io.git
cd jhipster.github.io.git
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll:pages

##### **Browsers and Operating System**

Ubuntu 16.04

**Comment by pascalgrimaud** [comment]
It's because the jekyll/jekyll:pages doesn't work well.. It worked on the past but since few months, it's broken => we should remove this instruction about docker

Currently, I use:
`docker run --rm --label=jekyll --volume=$(pwd):/site -p 4000:4000 andredumas/github-pages serve --watch`
Dockerhub: https://hub.docker.com/r/andredumas/github-pages/
Github project: https://github.com/andredumas/docker-github-pages

@mhavrlent : tell me if it works for you

**Comment by PierreBesson** [comment]
It's actually been broken for quite some time already... :cry:
I just appended the command `bundle exec jekyll serve` and it seems to work !
`docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll:pages bundle exec jekyll serve`

**Comment by mhavrlent** [comment]
Thanks guys. Both commands worked. Which one should go to the PR? :)

**Comment by pascalgrimaud** [comment]
Oh if it works with jekyll/jekyll:pages, keep this image! So, it's the command provided by @PierreBesson !

**Comment by PierreBesson** [comment]
I just did the PR myself as the "127.0.0.1" part of the command is useless. Let's consider this fixed.
