### ISSUE TITLE
HTTP session clustering with Hazelcast doesn't work with JHipster 3.7.0

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4136]
This is probably caused by our migration to Undertow.

**Comment by deepu105** [comment]
I would rather have undertow than a feature which is used very rareley


Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
I also agree to remove it and replace it by a tip in the docs.

Le 13 sept. 2016 7:49 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
Let me try to make it work :-)
Yes distributed caches are something I love :-)

**Comment by jdubois** [comment]
Wrong alert, turns out I can't read my own configuration :-)

For the record: in "dev" mode, multicast is disabled so you don't make clusters with your fellow co-workers. And it is enabled in prod mode.
