### ISSUE TITLE
Error generating mvn package -Pprod gulp test

### ISSUE THREAD

**Issue by israeleriston** [jhipster/generator-jhipster#4139]
Good gentlemen, I have a problem when I'll run mvn -Pprod package to generate .war, all entities have this error low
PhantomJS 2.1.1 (Linux 0.0.0) Controller Tests RG Management Controller Root Detail Scope Listening Unregisters root scope listener upon scope destruction FAILED, already reinstalled all npm dependencies, as gulp, bower and among others, but not for error. ..
TypeError: undefined is not a function (Evaluating 'createController ()') in src / test / javascript / spec / app / entities / historico-macon-store / historico-macon-store-detail.controller.spec.js (line 9 ) if someone has at least one north to guide ...

**Comment by pascalgrimaud** [comment]
You didn't provide any information about your configuration, your entities, etc.
Hard to help.

Please follow our guideline https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue
