### ISSUE TITLE
[Feature] Add consul support and a new "service discovery and configuration" question

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#4143]
As discussed on our mailing list: https://groups.google.com/forum/#!topic/jhipster-dev/ihZLebYVN5Y, we are going to add support for Consul.
This will take the form of a new question asked by the generator

> 
> Do you want to enable  Service Discovery and Configuration ?
> ❯ No
> ❯ Yes with the JHipster Registry (using Eureka and Spring Cloud Config) 
> ❯ Yes with Consul (using Spring Cloud Consul) 

cc @ogomezm
Initially discussed in #3608

**Comment by pascalgrimaud** [comment]
PR https://github.com/jhipster/generator-jhipster/pull/4165 is merged!
