### ISSUE TITLE
jdl creates "many-side" in both entities for relationship manyToOne

### ISSUE THREAD

**Issue by FritzLuber** [jhipster/generator-jhipster#4147]
#**Overview of the issue**

When generating 2 entities and a manyToOne relationship between them via jdl-import, the generated entities both have the relation set as manyToOne. (server- and client-/UI-side)
If i generate the same entities with a oneToMany relationship between them, everything is as expected.

i.e.: 
**jdl**
```
entity C{}
entity D{}
relationship ManyToOne {
	C{d} to D{cs}
}
dto * with mapstruct
paginate C with infinite-scroll
paginate D with infinite-scroll
```
**C.java**
```
@Entity
@Table(name = "c")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Document(indexName = "c")
public class C implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToOne
    private D d;
```
**D.java**
```
@Entity
@Table(name = "d")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Document(indexName = "d")
public class D implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToOne
    private C cs;   <----------------this should be OneToMany
```

**Reproduce the error**

generate a monolith app and import the jdl from above

**JHipster Version(s)**

generator-jhipster@3.6.1

**JHipster configuration**
```
{
"generator-jhipster": {
"jhipsterVersion": "3.6.1",
"baseName": "myapp",
"packageName": "com.test.app",
"packageFolder": "com/test/app",
"serverPort": "8080",
"authenticationType": "session",
"hibernateCache": "ehcache",
"clusteredHttpSession": "no",
"websocket": "no",
"databaseType": "sql",
"devDatabaseType": "h2Memory",
"prodDatabaseType": "postgresql",
"searchEngine": "elasticsearch",
"buildTool": "maven",
"enableSocialSignIn": false,
"useSass": true,
"applicationType": "monolith",
"testFrameworks": [
"gatling",
"cucumber",
"protractor"
],
"jhiPrefix": "jhi",
"enableTranslation": true,
"nativeLanguage": "en",
"languages": [
"en",
"de"
]
}
}
```
**Entity configuration(s)**
no entities

**Browsers and Operating System**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)
git version 2.9.2.windows.1
node: v6.3.1
npm: 3.10.3
bower: 1.7.9
gulp:
[16:41:00] CLI version 3.9.1
[16:41:00] Local version 3.9.1
yeoman: 1.8.5
Docker version 1.10.3, build 20f81dd
docker-compose version 1.6.2, build e80fc83

Browser firefox latest.

**suggest a Fix**
Look into the oneToMany relationship generator (corect working) and find the differences to ManyToOne generator (not working)

**Related Question**
bsp.:  owner ---1:N--- car
Since my plan was to display the relation on both entities, i'm a bit confused, what should have been generated on the owner side (owner.java; ownerDTO.java; ownerMapper) related to the relationship and what relates to the "this is not implemented on ui so far"(https://github.com/jhipster/generator-jhipster/issues/2056) and if this is still the case. I've looked through a few of those sample-apps, but sadly i couldn't find one with dto and mapstruct...
I'm thankfull for any Information on this Topic

**Comment by deepu105** [comment]
ping @MathieuAA

**Comment by MathieuAA** [comment]
Hi, I'll see about that in the afternoon.

**Comment by MathieuAA** [comment]
@deepu105 I've fixed it, validate everything before I release v1.1.9 tomorrow please.

**Comment by deepu105** [comment]
@MathieuAA LGTM see https://github.com/jhipster/jhipster-core/commit/ab1472b3c53c6708c90ce0e6f4b2209ff274638e

**Comment by FritzLuber** [comment]
Any chance one of you could answer my Question about displaying the bidirectional Relationship?
I'm still searching why I'm getting an empty field when getting the Set. i.e.: "vm.accountEntity.customerAccounts" in accountEntityDetails.html

**accountEntity.java** (only changed fetchType, rest is jhipster-generated)
@OneToMany(mappedBy = "servicePartner", fetch = FetchType.EAGER)
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<AccountEntity> customerAccounts = new HashSet<>();
@ManyToOne
    private AccountEntity servicePartner;

**accountEntity** (added Set)
private Long servicePartnerId;
private Set<AccountEntityDTO> customerAccounts = new HashSet<>();

**AccountEntityMapper** (removed the ignore for customerAccounts)
public interface AccountEntityMapper {
    @Mapping(source = "servicePartner.id", target = "servicePartnerId")
    AccountEntityDTO accountEntityToAccountEntityDTO(
            AccountEntity accountEntity);
    List<AccountEntityDTO> accountEntitiesToAccountEntityDTOs(
            List<AccountEntity> accountEntities);
    @Mapping(source = "servicePartnerId", target = "servicePartner")
    AccountEntity accountEntityDTOToAccountEntity(
            AccountEntityDTO accountEntityDTO);
    List<AccountEntity> accountEntityDTOsToAccountEntities(
            List<AccountEntityDTO> accountEntityDTOs);
...}

This is just the simplest example; i can't get it working for relations between entities ether.
Since i'm new to mapstruct and hibernate and i havn't found any example with DTOs with mapstruct , i hope you can tell me what i'm doing wrong.

**Comment by ruddell** [comment]
@FritzLuber I believe it is because you have `@JsonIgnore` in your accountEntity.java - if you have any more questions that aren't issues with the generator, please come to our [Gitter chat](https://gitter.im/jhipster/generator-jhipster) or use [StackOverflow](https://stackoverflow.com/questions/tagged/jhipster).

**Comment by FritzLuber** [comment]
Thanks for the quick answer and sorry for asking the question here.

The final solution i found, if anyone ever has the same problem: 
change the @JsonIgnore to @JsonIgnoreProperties({"<mappedBy-value>"}) and delete the @cache (only the one related to the relation)
