### ISSUE TITLE
Use form-check instead of form-control for bolean radio/checkbox

### ISSUE THREAD

**Issue by mtdx** [jhipster/generator-jhipster#4148]
I believe according to boostrap docs for radio/checkboxs you should use form-check, form-check-label, form-check-input instead of the usual  form-control. 

```
<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input" type="checkbox" value="">
    Option one is this and that&mdash;be sure to include why it's great
  </label>
</div>
```

**Comment by deepu105** [comment]
since our UI is frozen for ng2 this can be considered for ng2 branch

**Comment by sendilkumarn** [comment]
We can close once #4751 is merged 👍

**Comment by deepu105** [comment]
it will be merged anyway
