### ISSUE TITLE
VM Support for jdl, jdl-studio, jhipster-uml

### ISSUE THREAD

**Issue by sohibegit** [jhipster/generator-jhipster#4153]
feature request to generate view model in web.rest.vm package
Thank you

**Comment by deepu105** [comment]
This could be something we can consider for `jhipster:util` discussed in https://github.com/jhipster/generator-jhipster/pull/4104 if we are going that way, I'll also like to move the `jhipster:service` sub generator into the `jhipster:util`

**Comment by jdubois** [comment]
- AngularJS 1 is "frozen" at the moment, until we migrate to AngularJS 2, so we can't do it right now
- For AngularJS 2 we need to see if we can be compatible with tools like https://github.com/angular/angular-cli , which would support "simple" generations like this one

Then, of course, I totally like the idea of generating more "simple" templates, not everyone want full-fledge CRUD support.

**Comment by deepu105** [comment]
@jdubois I think @sohibegit want to generate a server side `VM` in the `web.rest.vm` package.

**Comment by jdubois** [comment]
Oh sorry! And that was my idea to call them both "vm" as it's easier to have the same concepts on both sides :-)
Yes we should also have those as an option, but it would be quite a simple generator as I guess it would mostly be generating an empty file.

**Comment by sohibegit** [comment]
It would be perfect if I can do this without relations:
```
vm entityAVM{
   entityA EntityA,
   entityB EntityC,
   listOfEntiyB List<EntityB>,
  ...
}
```

**Comment by jdubois** [comment]
Is anyone interested in working on this?

I think everybody agrees this would be a good feature, then that's a lot of work and I'd rather focus on Angular 2 at the moment.

Otherwise I will close this for "lack of interest", as I don't want to have old tickets staying opened if nobody works on them.

**Comment by jdubois** [comment]
I'm closing this for "lack of interest", this is something we can work on after the Angular 2 release, but that's going to take some time.
