### ISSUE TITLE
ZonedDateTime

### ISSUE THREAD

**Issue by superandrew** [jhipster/generator-jhipster#4154]
##### **Overview of the issue**

An entity created with ZonedDateTime should have a TIMESTAMP WITH TIME ZONE type in Posgres

Creating or modifying and regenerating on an empty DB a field of type ZonedDateTime generates in Postgres a TIMESTAMP WITHOUT TIME ZONE
##### **Motivation for or Use Case**

the postgres field TIMESTAMP WITH TIME ZONE should track the zone
##### **Reproduce the error**

- Create an entity
- assign a field a type ZonedDateTime (using the generator)
- check the field type on PostgreSQL

##### **JHipster Version(s)**

v 3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "baseName": "--",
    "packageName": "--",
    "packageFolder": "--",
    "authenticationType": "xauth",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "--",
    "testFrameworks": [
      "gatling"
    ]
  }
}
##### **Entity configuration(s) `Activity.json` files generated in the `.jhipster` directory**
{
    "relationships": [],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "createdDate",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldId": 2,
            "fieldName": "type",
            "fieldType": "Long"
        },
        {
            "fieldId": 3,
            "fieldName": "objectId",
            "fieldType": "Long"
        },
        {
            "fieldId": 4,
            "fieldName": "subjectId",
            "fieldType": "Long"
        },
        {
            "fieldId": 5,
            "fieldName": "action",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160913150809",
    "dto": "no",
    "service": "no",
    "pagination": "infinite-scroll"
}

##### **Browsers and Operating System**
Mac OS

**Comment by cbornet** [comment]
We are converting ZonedDateTime to Date before storing. Note that Hibernate 5 which has integrated support for JDK8 dates does the same.
There is a discussion thread in the hibernate-dev mailing list about whether they should support storing the timezone for DBs that have a TIMESTAMP WITH TIME ZONE type but they seem reluctant to do it for various reasons.
Also note that PostgreSQL doesn't store the timezone when using TIMESTAMP WITH TIME ZONE (other dbs such as Oracle do store it). So when fetching the date, you will not get the TZ of the data you stored but most likely the tz of your PSQL instance.
