### ISSUE TITLE
Mssql-Server support from command line.

### ISSUE THREAD

**Issue by Moshiour027** [jhipster/generator-jhipster#4161]
It would be great to find support from mssql server in jhipster console. 
To integrate Mssql with linquibase later creates problem and no guideline is found in any documentation.

**Comment by pascalgrimaud** [comment]
MS SQL is not supported in JHipster because it's a proprietary database on Windows.
Anyway, you have:
- this tips: http://jhipster.github.io/tips/004_tip_using_ms_sql_server.html
- this module: http://jhipster.github.io/modules/marketplace/#/details/generator-jhipster-mssql
