### ISSUE TITLE
Deploying to Google App Engine

### ISSUE THREAD

**Issue by eosimosu** [jhipster/generator-jhipster#4162]
##### **Overview of the issue**

I am trying to deploy a Jhipster + MongoDB app to google's new flexible app engine environment.

[https://cloud.google.com/appengine/docs/flexible/java/quickstart
](https://cloud.google.com/appengine/docs/flexible/java/quickstart
)
[https://kiosk-dot-codelabs-site.appspot.com/codelabs/cloud-app-engine-springboot/index.html#0](https://kiosk-dot-codelabs-site.appspot.com/codelabs/cloud-app-engine-springboot/index.html#0)
Has anyone tried this? Any pointers?

By the way, they give $300 free credit for new signups like AWS and CF.

**Comment by PierreBesson** [comment]
It seems Google are updating their "App engine" offering to Java 8 and Servlet 3.1: https://cloud.google.com/appengine/docs/flexible/java/dev-jetty9
Note that this is still in beta but that means JHipster should work run on it without problems. You would just need to configure your app to use jetty instead of tomcat/undertow (see the relevant  [Spring boot docs](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-configure-jetty)) and then follow the instructions on the first link I gave.

It would be great to have Google officially support us for this. ping @saturnism :-)

**Comment by eosimosu** [comment]
Thanks, I'll follow the instructions and the outcome here.

**Comment by jdubois** [comment]
This is a very early release of new GAE APIs, which are not stable yet -> I'm closing this as I don't think we can support it officially until they have some stable APIs.

Then, of course:
 
- Please do add comments here if you manage to make it work
- When it's stable, we should definitely support it

**Comment by eosimosu** [comment]
@PierreBesson Replacing the tomcat depedency with jetty generated the following error:

`[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) on project server: An exception occurred while running. null: InvocationTargetException: Failed to start bean 'stompWebSocketHandlerMapping'; nested exception is java.lang.IllegalStateException: Unable to initialize Jetty WebSocketServerFactory: Not running on Jetty, WebSocket support unavailable -> [Help 1]
`

**Comment by xetys** [comment]
@eosimosu the Google container engine is also part of Google cloud services, which is compatible with our kubernetes support. With this I already deployed a JHipster microservice with effort, and I am pretty sure this will work for monoliths, too

**Comment by eosimosu** [comment]
I couldn't get it to work with jetty, something with websocket not supported. I tried tomcat and included the google app engine maven plugin. This time got the following error:

`[INFO] GCLOUD: ERROR: (gcloud.app.deploy) There is a Dockerfile in the current directory, and the runtime field in /home/eo/IdeaProjects/jhipster-angular2-nativescript/server/target/appengine-staging/app.yaml is currently set to [runtime: java]. To use your Dockerfile to build a custom runtime, set the runtime field in /home/eo/IdeaProjects/jhipster-angular2-nativescript/server/target/appengine-staging/app.yaml to [runtime: custom]. To continue using the [java] runtime, please omit the Dockerfile from this direct`

**Comment by eosimosu** [comment]
@PierreBesson DId you ever get it to work or you just assumed it should ?

**Comment by PierreBesson** [comment]
No I didn't try it yet. But I just assumed it would work as we are just building a standard war.
I don't know, you could try to remove the Docker file as explained in the error message... But this means GAE now support Docker deployment and  this is something that we also support !
Anyway I will look at it when I have the time, thanks for the feedback.

**Comment by eosimosu** [comment]
I got it to work on App engine by the way. Thanks for the help.

**Comment by khalilj** [comment]
Hi eosimosu. can you share the steps?

**Comment by anilbb23a** [comment]
I am trying to deploy jhipster monolithic app on the Google App Engine (Flex and Standard env).  Getting errors
Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.
 
**Can someone please share the steps** ?

**Comment by jdubois** [comment]
This cannot work yet, GAE is only çompatible with the latest Spring Boot release.

**Comment by anilbb23a** [comment]
We are using latest jhipster which uses Spring 1.5.4.RELEASE.
@eosimosu : Hi, How did you achieve it? Please share the steps.

**Comment by eosimosu** [comment]
@khalilj Any reasons you don't want to use kubernetes ? I got it to work on App Engine with only Docker but I only use Kubernetes now.

**Comment by khalilj** [comment]
@eosimosu it's requires much less OPS to work with GAE.

**Comment by anilbb23a** [comment]
@eosimosu: Please share the steps.
I am trying to deploy it on the Standard GAE for past 3 days. but could not do so.

**Comment by jdubois** [comment]
It cannot work yet, you need the latest 1.5.6 Spring Boot release
