### ISSUE TITLE
Graphical representation of Boolean fieldType in entity's records list

### ISSUE THREAD

**Issue by shadowrider-pl** [jhipster/generator-jhipster#4163]
- **Overview of the request**

Hi. It's my suggestion to change boolean values from 'true' or 'false' to icons.
- **Motivation for or Use Case** 

Looks nice and we skip i18n.
It's used i.e. in SonataAdminBundle [php, Symfony]

![booltest 3 s opera_004](https://cloud.githubusercontent.com/assets/9105435/18630140/cff59cc2-7e6a-11e6-9c63-b8b19a9603c4.png)

![booltest 3 s opera_003](https://cloud.githubusercontent.com/assets/9105435/18629108/d5ded09c-7e63-11e6-8a23-ee299e16c16c.png)
- **Related issues** 

Didn't find any.
- **Suggest a Fix** 

In /src/main/webapp/app/entities/product-new/product-new.html I changed:

```
<tbody>
                <tr ng-repeat="productNew in vm.productNews track by productNew.id">
                    <td><a ui-sref="product-new-detail({id:productNew.id})">{{productNew.id}}</a></td>
                    <td>{{productNew.name}}</td>

                    <td>{{productNew.active}}</td>
```

to:

```
            <tbody>
                <tr ng-repeat="productNew in vm.productNews track by productNew.id">
                    <td><a ui-sref="product-new-detail({id:productNew.id})">{{productNew.id}}</a></td>
                    <td>{{productNew.name}}</td>

                    <!--
                    <td>{{productNew.active}}</td>-->
                    <td>
                    <span class="glyphicon glyphicon glyphicon-ok" style="color:green" ng-show="productNew.active"></span>
                    <span class="glyphicon glyphicon glyphicon-remove" style="color:red" ng-show="!productNew.active"></span>
                    </td> 
```

I tried to add in _entity-management.html additional 'else if' statement:

```
else if (fieldType == 'Boolean') { _%>
            <span class="glyphicon glyphicon glyphicon-ok" style="color:green" ng-show="entityInstance.fieldName"></span>
            <span class="glyphicon glyphicon glyphicon-remove" style="color:red" ng-show="!entityInstance.fieldName"></span>
                        <%_ }
```

but it doesn't work for me...

**Comment by deepu105** [comment]
We have frozen the angular 1 related development in favor of Angular2. hence this can be considered for ng2 branch

**Comment by gmarziou** [comment]
@shadowrider-pl your change raises an accessibility issue for screen readers.

**Comment by jdubois** [comment]
@gmarziou is right, and let's keep things simple for the moment: AngularJS 1 is frozen, and Angular 2 is already enough work... It's very easy to customize to your taste once generated, so this shouldn't be a big problem in the end.
