### ISSUE TITLE
No Metrics 

### ISSUE THREAD

**Issue by AntoineMary** [jhipster/generator-jhipster#417]
Hi,

I just install yeoman (1.2.0)  and create a project with generator-jhipster (0.17.2) but when I launch it with "mvn spring-boot:run" I get this trouble.

![Bug](https://cloud.githubusercontent.com/assets/8077943/3487781/1e549d7c-04a2-11e4-8392-d59947d12b95.png)

I've got no error in console, and I don't have edit any file yet.
(a couple days ago it was working fine with 0.17.0)

ps : Java SE 7u60

**Comment by Zyst** [comment]
Also had this issue, can replicate on a browser without Adblockers working, and browsers with Adblockers not working. Super weird stuff.
