### ISSUE TITLE
Static resources not included in WAR

### ISSUE THREAD

**Issue by eosimosu** [jhipster/generator-jhipster#4170]
##### **Overview of the issue**

I generated a jhipster backend using the ` yo jhipster:server ` command, then generated a frontend app using angular 2 cli. Then I made sure the static resources are compiled to the server folder `build/www`. Everything works fine when I run with `./gradlew`. The problem is when I generate WAR using `./gradlew -Pprod bootRepackage`, the static resources are not included and not served. Any pointers?

##### **JHipster Version(s)**
3.7.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
{
  "generator-jhipster": {
    "jhipsterVersion": "3.7.0",
    "baseName": "server",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "xxx",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "sv"
    ]
  }
}

**Comment by atomfrede** [comment]
Where did you put your static resources? Everything under ``src/main/webapp`` and ``src/main/resources`` are compiled into the resulting war file.

**Comment by deepu105** [comment]
From your comments you are using angular cli for front end app and hence this might not be a jhipster issue. Please open a SO question for such items. From your troubleshooting if you can confirm this as a Jhipster issue then ask to reopen the issue or open a new issue with more details as per the issue template.

**Comment by eosimosu** [comment]
@atomfrede Since I generated only backend using `yo jhipster:server`, so there is no gulp compilation or `webapp` folder. I am manually compiling the static assets to `/build/www` from a separate project.

@deepu105 I think this may be a jhipster issue? I am reading the instructions on this page [Generating an optimized JavaScript application with Gulp](https://jhipster.github.io/production/), and it says assets added to `build/www` will be included in your final production WAR.

**Comment by deepu105** [comment]
> This will process all your static resources (CSS, JavaScript, HTML, JavaScript, images…) in order to generate an optimized client-side application.
> 
> Those optimized assets will be generated in target/www for Maven or build/www for Gradle, and will be included in your final production WAR.
@eosimosu yes the above is with respect to the `gulpfile.js` we generate, we have tasks which are run as part of production build which ensures that things are packaged as required. We cannot test or support every combination that you could manually do for the client here. Our hands are already full and I'm sorry but we wont be able to help you much here as we dont know what you are doing for the client side. Thats why I said if you can clearly point an issue arising from JHipster I'll be happy to take a look and see if we can fix it.

**Comment by eosimosu** [comment]
Solved it by added the following to my pom.xml in a maven project:
```
                    <plugin>
                        <configuration>
                            <warSourceDirectory>target/www/</warSourceDirectory>
                            <packagingExcludes>WEB-INF/lib/tomcat-*.jar</packagingExcludes>
                        </configuration>
                    </plugin>
```
Thanks for the help and the work you're doing on jhipster!

**Comment by deepu105** [comment]
You said you were using gradle

Thanks & regards,
Deepu

**Comment by eosimosu** [comment]
Yeah, I did but I have more experience with maven, so I recreated the app with maven to debug it.
