### ISSUE TITLE
Password is being written to console/log

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#4176]
##### **Overview of the issue**

Password is being written to console/log when a user login into the system.

##### **Motivation for or Use Case**

From the security point of view, password should not written to console/log.

##### **Reproduce the error**

1. Generate a new application

2. Run `./mvnw`

3. Login using browser with `user:user` 

4. Check console log, following message will be displayed.

`2016-09-21 03:24:23.996 DEBUG 11795 --- [ XNIO-2 task-17] p.a.j.aop.logging.LoggingAspect          : Enter: pm.apps.myapp.web.rest.UserJWTController.authorize() with argument[s] = [LoginVM{password='user', username='user', rememberMe=true}, com.codahale.metrics.servlet.AbstractInstrumentedFilter$StatusExposingServletResponse@431cef9c]
`
##### **Related issues**

-

##### **Suggest a Fix**
Modify `toString` method from `LoginVM.java` to print some other characters such as xxxxxx or ******.

Change following
`    @Override
    public String toString() {
        return "LoginVM{" +
            "password='" + password + '\'' +
            ", username='" + username + '\'' +
            ", rememberMe=" + rememberMe +
            '}';
    }
`
to
`
    @Override
    public String toString() {
        return "LoginVM{" +
            "password='**********'" +
            ", username='" + username + '\'' +
            ", rememberMe=" + rememberMe +
            '}';
    }
`

##### **JHipster Version(s)**

generator-jhipster@3.7.1 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.7.1",
    "baseName": "myapp",
    "packageName": "pm.apps.myapp",
    "packageFolder": "pm/apps/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi",
      "mr",
      "ta"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

-

##### **Browsers and Operating System**

Windows 7, Chrome 52.x.x.x.x.

**Comment by pascalgrimaud** [comment]
So we have this security issue since 3.6.0
