### ISSUE TITLE
`gulp test` doesn't work with OAuth2 + WebSocket

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4192]
This originally comes from #4175.

With JHipster 3.7.1, use the following `.yo-rc.json` file:

    {
      "generator-jhipster": {
        "jhipsterVersion": "3.7.1",
        "baseName": "gleac",
        "packageName": "br.com.gleac",
        "packageFolder": "br/com/gleac",
        "serverPort": "8080",
        "authenticationType": "oauth2",
        "hibernateCache": "ehcache",
        "clusteredHttpSession": false,
        "websocket": "spring-websocket",
        "databaseType": "sql",
        "devDatabaseType": "postgresql",
        "prodDatabaseType": "postgresql",
        "searchEngine": false,
        "buildTool": "maven",
        "useSass": false,
        "applicationType": "monolith",
        "testFrameworks": [
          "gatling"
        ],
        "jhiPrefix": "jhi",
        "enableTranslation": false,
        "messageBroker": false,
        "enableSocialSignIn": false
      }
    }

This will make `gulp test` fail with `Error: <spyOn> : getItem has already been spied upon` when testing the password directive.

This happens when both WebSockets and OAuth2 are selected, so there is an incompatibility here.

**Comment by israeleriston** [comment]
julian, has been resolved?

**Comment by israeleriston** [comment]
when it will be available to fix?

**Comment by jdubois** [comment]
As it's just one line, the easiest thing for you is to delete it in your `password-strength-bar.directive.spec.js` file.

I don't know when the next release will be available, probably in one week or two, it depends on what we do.
