### ISSUE TITLE
Using import-jdl multiple times: liquibase master.xml contains multiple entries for same entity causing error

### ISSUE THREAD

**Issue by piprog** [jhipster/generator-jhipster#4193]
##### **Overview of the issue**

My workflow is that I make modifications to the jhipster-jdl.jh file with Studio, then run yo jhipster:import-jdl jhipster-jdl.jh to apply the changes. This results in correct detection of which entities have changed, but instead of modifying them, a new add entry is generated in liquibase and the liquibase master.xml will thus include multiple entries for adding a specific entity to the database which results in an SQL create error.

##### **Motivation for or Use Case**

Running import-jdl multiple times is practical since all entities are nicely documented there. Since there is no update generated for the table it has to be dropped before re-generation loosing all data.

##### **Reproduce the error**

See above. It happens always.

##### **Related issues**

n/a

##### **Suggest a Fix**

Workaround: edit the master.xml file after each import to get rid of the old entries for an entity. 

##### **JHipster Version(s)**

3.6.x, 3.7.x (probably more)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.7.1",
    "baseName": "LLMS",
    "packageName": "com.pannonrex.llms",
    "packageFolder": "com/pannonrex/llms",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "...",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de",
      "hu"
    ]
  }
}

##### **Browsers and Operating System**

Win10/Chrome

**Comment by deepu105** [comment]
This is the intended behaviour currently as we do not update a changelog
when there are updates. Let me see if we can generate the same file names
atleast. But cannot assure anything

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
The workflow in that case is to use the Liquibase Maven goal -> it's far too complex to generate this ourselves, the Maven goal will do a much better job, and we don't have to do anything.

**Comment by piprog** [comment]
@jdubois: do you think of mvnw liquibase:update?

**Comment by pascalgrimaud** [comment]
@piprog: you can read this page for more details http://jhipster.github.io/development/

**Comment by jdubois** [comment]
Yes it's documented and we do a huge job to maintain it.

**Comment by piprog** [comment]
@jdubois @deepu105 @pascalgrimaud  Thx folks!

**Comment by deepu105** [comment]
the issue with incorrect changelogdate is fixed upstream in jhipster core
