### ISSUE TITLE
Upgrade to Hibernate 5.2 and Ehcache 3

### ISSUE THREAD

**Issue by henri-tremblay** [jhipster/generator-jhipster#4195]
This is a feature request.

A pull request will follow since we are working on it.

We would like to upgrade JHipster to use Hibernate 5.2 and Ehcache 3.

This requires a bit of work. We have identified the following tasks:
- Upgrade to Hibernate 5.2
- Use `jackson-datatype-hibernate` to 5
- Add hibernate JCache support
- Code `liquibase-hibernate52`
- Update to Ehcache 3
- Connect Hibernate to Ehcache 3 using JCache
- Connect Spring to Ehcache 3 using JCache
- Code Codehale Metrics support to Ehcache 3

If someone has partially done some of these tasks, please communicate with me.

If you think something was forgotten, please tell me.

**Comment by jdubois** [comment]
Thanks @henri-tremblay !
For Hibernate 5 support in Liquibase, have a look at https://github.com/liquibase/liquibase-hibernate/issues/96 - there are already people working on it, but it's not finished yet, and this has been stalled for a long time

**Comment by nvoxland** [comment]
Support for Hibernate 5.2 has been pushed to the liquibase/liquibase-hibernate master branch. If you could do some testing with it and let me know how it goes I would greatly appreciate it.

**Comment by cbornet** [comment]
For hibernate, I guess we should use Spring Boot 1.4 version which is 5.0 (from dependency management)

**Comment by nvoxland** [comment]
I pushed a new change to liquibase-hibernate master to depend on Hibernate 5.0.10. Just a small change to the hibernate APIs I was calling and my tests are still passing.

**Comment by henri-tremblay** [comment]
@nvoxland Will test. So your stuff now works on Hibernate 5.0 and 5.2? Am I getting it right?

@cbornet What do you mean? JHipster seems to use Spring Boot 1.4.1 already

**Comment by nvoxland** [comment]
Yes, it should work with any version of hibernate 5.0 and above.

**Comment by cbornet** [comment]
I mean that we should use the same hibernate version as SB unless we have a good reason not to do so and that version is 5.0

**Comment by jdubois** [comment]
Yes we should have the SB version, unless we have a good reason to change it, that's one of the project policies at http://jhipster.github.io/policies/

**Comment by henri-tremblay** [comment]
Sorry, for some reason the last comments went lost in my inbox. What is SB? (newbie question I guess)

**Comment by lluiscanals** [comment]
SB stands for "Spring Boot"

Regards!

**Comment by henri-tremblay** [comment]
Ok... This is a problem I must say. Because right now my implementation is using JCache. And Hibernate has started to support JCache in 5.2. We are also working on a JCache metrics connector. Not using JCache would be a bit more complicated.

**Comment by jdubois** [comment]
Well, maybe this could fit in our definition of "a good reason to change it" :-)
Our biggest issue is that this needs to work with Spring Data JPA, but I have no reason to think this would cause any issue.
And anyway, if we just wait a little bit, Spring Boot will probably update to Hibernate 5.2. So that shouldn't be a blocker issue.
@henri-tremblay unless this causes any issue with Spring Data (which I doubt, and which we could probably solve anyway), let's go for Hibernate 5.2

**Comment by henri-tremblay** [comment]
I've been running in this version since the beginning of the week and had no issue so far.

**Comment by henri-tremblay** [comment]
However, about `liquibase-hibernate5`, I had no issues running the application. However, the  `liquibase-maven-plugin` doesn't work yet (`liquibase:diff`). 

A little summary for @nvoxland 
* I've added these dependencies to the plugin.
```xml
                    <dependency>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-core</artifactId>
                        <version>${hibernate.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-validator</artifactId>
                        <version>${hibernate.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>javax.el</groupId>
                        <artifactId>el-api</artifactId>
                        <version>2.2</version>
                    </dependency>
```
* I need to update the strategy setup of the plugin. There is now an implicit and physical strategy in hibernate
* Then it is still failing about an error on the second level cache that can't be loaded. I need to investigate.

**Comment by jdubois** [comment]
@henri-tremblay if you want to have a good test with the "liquibase:diff" goal:

- generate a sample app, using MySQL as your "dev" database
- add a few entities -> you can copy/paste the 3 from the sample app at https://github.com/jhipster/jhipster-sample-app/tree/master/.jhipster
- run the app, so the database is created
- add one field somewhere in one entity

-> when you run "liquibase:diff", you should only get that new field in the changelog.

**Comment by henri-tremblay** [comment]
Ok. Thanks. It should fails if I use H2 Disk? (currently, it does)

**Comment by jdubois** [comment]
_Probably_ not :-)
I haven't used it for a long time (I use MySQL), but H2 should have a port opened (I remember configuring this), and the Maven goal can then use it to connect to the database and do the diff.

**Comment by henri-tremblay** [comment]
Indeed, it works with a normal generation (without me modification). If tails if I use liquibase 3.5.2 though. Some detail at liquibase/liquibase-hibernate/issues#96

**Comment by henri-tremblay** [comment]
I've done a pull request on liquibase/liquibase-hibernate#96. Everything seems to work fine. I still need to do the MySQL test but we are close to the end,

**Comment by jdubois** [comment]
Great news! I'll do a specific release when this is ready

**Comment by nvoxland** [comment]
Liquibase-hibernate5 v3.6 has been released

**Comment by henri-tremblay** [comment]
Yep. Next step is the PR to jhipster. I have all the working code locally, I "just" need to move it in the generator.

**Comment by deepu105** [comment]
Awesome

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
@henri-tremblay @nvoxland it looks like you are pretty close to have something fully working. My idea is that this is such a big update that it needs to be its own release, so when you have the PR ready we need to synchronize.

My goal is to have a release with all your changes in one place, and have the correct release notes (I'll need your help), and of course go through the usual Twitter, etc to have everybody knows about this upgrade.

**Comment by henri-tremblay** [comment]
Sure. I'm stuck on something else but starting next week, my free time
should be dedicated to it.

**Comment by nkolosnjaji** [comment]
Could ehcache be replaced with caffeine cache ? 
[Caffeine is a Java 8 rewrite of Guava’s cache and will supersede the Guava support in Spring Boot 2.0.](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-caching-provider-caffeine)
Also, here are behcnmarks: https://github.com/ben-manes/caffeine/wiki/Benchmarks

**Comment by gmarziou** [comment]
@nkolosnjaji can caffeine be used as second level cache for hibernate?

**Comment by nkolosnjaji** [comment]
yes it can with JCache JSR 
https://hibernate.atlassian.net/browse/HHH-10770

**Comment by henri-tremblay** [comment]
Yes. I will provide a patch using Ehcache... because I'm kinda working on Ehcache. But the implementation including metrics is fully JCache compliant. So switching to another framework will be much more easier.

Should be able to work on it next week during Devoxx.

**Comment by ben-manes** [comment]
I'm a big believer in those doing the work should get the credit, so @henri-tremblay advocating Ehcache in the patch / documentation is a nice reward. Mentioning other providers in the documentation would be reasonable, but perhaps with less emphasis.

If the generator supported multiple providers, changed defaults, etc. that could be a different discussion. But I wouldn't want to detract from @henri-tremblay effort by promoting Caffeine.

Thanks @henri-tremblay and @nkolosnjaji.

**Comment by jdubois** [comment]
Thanks @ben-manes that is really fair from you!

**Comment by henri-tremblay** [comment]
Thanks guys. BTW, if you want to see the generated result, it is now an [Ehcache sample](https://github.com/ehcache/ehcache3-samples/tree/master/fullstack). That's what I need to move to the generator.

**Comment by jdubois** [comment]
OMG, you mean some of my code is now part of the official ehcache sample? I'm so proud!!!!!!

**Comment by henri-tremblay** [comment]
:-)

**Comment by mraible** [comment]
@henri-tremblay I tried to build the fullstack example, but I get the following error:

```
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ demo ---
[ERROR] diagnostic: /Users/mraible/dev/ehcache3-samples/fullstack/src/main/java/org/terracotta/demo/config/jcache/SpringCacheRegionFactory.java:3: error: package org.hibernate.boot.spi does not exist
import org.hibernate.boot.spi.SessionFactoryOptions;
                             ^
[ERROR] diagnostic: /Users/mraible/dev/ehcache3-samples/fullstack/src/main/java/org/terracotta/demo/config/jcache/SpringCacheRegionFactory.java:5: error: package org.hibernate.cache.jcache does not exist
import org.hibernate.cache.jcache.JCacheRegionFactory;
                                 ^
[ERROR] diagnostic: /Users/mraible/dev/ehcache3-samples/fullstack/src/main/java/org/terracotta/demo/config/jcache/SpringCacheRegionFactory.java:15: error: cannot find symbol
public class SpringCacheRegionFactory extends JCacheRegionFactory {
                                              ^
  symbol: class JCacheRegionFactory
[ERROR] diagnostic: /Users/mraible/dev/ehcache3-samples/fullstack/src/main/java/org/terracotta/demo/config/jcache/SpringCacheRegionFactory.java:18: error: cannot find symbol
    public void start(SessionFactoryOptions options, Properties properties) throws CacheException {
                      ^
  symbol:   class SessionFactoryOptions
  location: class org.terracotta.demo.config.jcache.SpringCacheRegionFactory
[ERROR] diagnostic: /Users/mraible/dev/ehcache3-samples/fullstack/src/main/java/org/terracotta/demo/config/JCacheGaugeSet.java:19: error: package javax.cache.management does not exist
import javax.cache.management.CacheStatisticsMXBean;
                             ^
[ERROR] diagnostic: /Users/mraible/dev/ehcache3-samples/fullstack/src/main/java/org/terracotta/demo/service/WeatherService.java:19: error: package javax.cache.annotation does not exist
import javax.cache.annotation.CacheResult;
                             ^
[ERROR] diagnostic: /Users/mraible/dev/ehcache3-samples/fullstack/src/main/java/org/terracotta/demo/service/WeatherService.java:43: error: cannot find symbol
    @CacheResult(cacheName = "weatherReports")
     ^
  symbol:   class CacheResult
  location: class org.terracotta.demo.service.WeatherService
[ERROR] error on execute: error during compilation
```

My environment:

```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T05:57:37-06:00)
Maven home: /opt/tools/maven
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

**Comment by mraible** [comment]
Actually, this happens when I run `yo jhipster` on the project, which is likely expected. If I just try to build using `./mvnw`, I get:

```
[ERROR] Failed to execute goal on project fullstack: Could not resolve dependencies for project 
org.ehcache.sample:fullstack:war:1.0.0-SNAPSHOT: The following artifacts could not be resolved: 
org.terracotta.management:management-entity-client:jar:5.0.6.beta5, 
org.terracotta.management:management-model:jar:5.0.7.beta: Failure to find 
org.terracotta.management:management-entity-client:jar:5.0.6.beta5 in 
https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be 
reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

**Comment by henri-tremblay** [comment]
Oh! That's interesting. I guess I need to add Terracotta repositories. Let
me see.

**Comment by henri-tremblay** [comment]
Can you add this at the end of your pom:

```xml
    <repositories>
        <repository>
            <id>terracotta</id>
            <url>http://repo.terracotta.org/maven2</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
```

**Comment by henri-tremblay** [comment]
I've removed the bad dependencies. So if you pull the new code, it should work nicely without the Terracotta repo. Thanks @anthonydahanne you did the code sample with me and just approved the PR containing the fix :-)

**Comment by mraible** [comment]
@henri-tremblay Adding the repositories works, as does pulling the latest code. 

I'm interested in this sample because it uses EhCache and we, at Stormpath, have had [an issue](https://github.com/stormpath/stormpath-sdk-java/issues/1024) with the caching setup in a JHipster application. It seems we have to add entries in `ehcache.xml` for things to work. 

This seems strange since I took your example, commented out all the JHipster-specific entries and it works just fine. However, when I integrate Stormpath, it blows up. Note that if I create a JHipster app with Hazelcast, Stormpath caching doesn't need any additional configuration.

**Comment by PierreBesson** [comment]
@henri-tremblay I just had a look at the ehcache sample and really liked it. Thanks a lot for working on this. 

I also noticed that there is a "clustered" config with a docker config for an off-heap server. It would be very interesting for https://github.com/jhipster/generator-jhipster/issues/3621 which was an idea we had of adding a scalable cache for requests that passed through our Zuul Gateway.

Do you think this could work ?

**Comment by anthonydahanne** [comment]
@PierreBesson good catch :-)
The clustered cache configuration can be used to connect your client caches to a terracotta server (that is using offheap storage to store your cache elements).
With [this demo](https://github.com/ehcache/ehcache3-samples/tree/master/fullstack), @henri-tremblay  and I show that it is possible to start with local caching and then easily switch (changing few lines in ehcache.xml) to clustered caching : several instances of your jhipster app keeping their caches in sync using a [Terracotta server](https://github.com/anthonydahanne/terracotta-oss-docker/tree/5.0.0) (if instance1 loaded actorA, then instance2 will have it in cache via its clustered store)

Quickly browsing through #3621 I understand you wanted to try using a cache integrated with spring cache; I'd say ehcache3 is a pretty good match :-) and for scaling, yes, this use case is covered with clustered ehcache3

**Comment by PierreBesson** [comment]
@anthonydahanne This looks really interesting, it would interesting to integrate this and have an option for the clustered cache in JHipster as well.

**Comment by zulfahmi** [comment]
Will support for Hibernate 5.x mean that Geometry/Spatial data type will be available in entity?
I hope this will. Thank you.

**Comment by jdubois** [comment]
@zulfahmi we are just doing an upgrade for the moment, so nothing more. This ticket is about doing this upgrade, if you want new features please add a new ticket.

**Comment by zulfahmi** [comment]
@jdubois I see, thanks
