### ISSUE TITLE
Where is app.js?

### ISSUE THREAD

**Issue by jamiedejong** [jhipster/generator-jhipster#4200]
Hey,

I have installed the newest version of JHipster (v3.8.0) with Maven and followed the tutorials on the website, but I have still a problem, because I cannot find the "scripts" folder. I would like to change the startup controller, so I need the app.js for that.. But where can I find it!?

Thanks,

Jamie

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by deepu105** [comment]
There is no scripts folder what tutorial are you referring to. Look inside
webapp/app folder

Thanks & regards,
Deepu

**Comment by jamiedejong** [comment]
@deepu105, https://jhipster.github.io/configuring-ide-eclipse/, scroll down and you see the folder: "scripts". But where can I find app.js? Where else can I change the startup controller?

**Comment by jdubois** [comment]
I'm locking this conversation: this is the bug tracker, not the discussion board.
