### ISSUE TITLE
Old v 2.x screenshots in 3.x documentation pages

### ISSUE THREAD

**Issue by jamiedejong** [jhipster/generator-jhipster#4201]
##### **Overview of the issue**

In the tutorial it is saying "scripts" folder -> https://jhipster.github.io/configuring-ide-eclipse. If you scroll down you will see the folder. But I don't have it.

##### **Motivation for or Use Case**

I would like to change in the app.js the start-up controller (which can be found in the "scripts" folder), so it will start a custom new page instead of the default page.

##### **JHipster Version(s)**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.8.0",
    "baseName": "name",
    "packageName": "name",
    "packageFolder": "name",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "97f40243eac4cbdce2a7904361dbd5762220b6c2",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "nl",
    "languages": [
      "nl",
      "en",
      "fr"
    ]
  }
}
```
##### **Browsers and Operating System**

Google Chrome Version 53.0.2785.116 m

**Comment by jdubois** [comment]
It's an old screenshot, yes we need to update it -> I'm keeping this opened until this is updated.

Have a look at https://jhipster.github.io/using-angularjs/ to learn about our current front-end architecture.
