### ISSUE TITLE
[FEATURE] extend user-management-dialog.controller | create authorities service

### ISSUE THREAD

**Issue by leeder** [jhipster/generator-jhipster#4207]
##### **Motivation for or Use Case**

If would be nice if the user-management would reflect the newly added "ROLE"s.
I've extended the already existing user roles('ROLE_USER', 'ROLE_ADMIN') with a new role, and I wanted to assign the role to a newly created user during run time. I have created a new user and on the user-management-dialog page I saw that my new role does not appear among the build in roles.

##### **Suggest a Fix**
Extend the user-management-dialog.contorller.js file, so that it dynamically reads the roles from the jhi_authority table from the db.

**Comment by deepu105** [comment]
im putting this request on hold for ng2 migration

**Comment by jdubois** [comment]
We just don't have the bandwidth for this... We have 31 opened bugs, we will indeed have a look at this after NG2 migration, and after the bugs are managed. Probably not in the next 3 months, so I'm closing this.
Then, indeed @leeder you are right, we should have a management screen for roles.
