### ISSUE TITLE
Improve the generated Readme

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#4209]
Some improvements could be made to the generated README file. I think quite a lot can be done to make it clearer so that users can use it as a real getting started guide.
- [x] Specify which version of the generator has been used for generating the app and link to the documentation archive
- [x] Instead of including the microservice diagram, link to the `doing microservices` page which host a much cleaner version
- [x] Add a link to the `http://jhipster.github.io/development/` page
- [x] Add a section on using docker: how to build a docker image,  start a prod db using docker-compose, run the app.yml
- [x] Move the Jenkins docs from the Readme to the website and simply link to `http://jhipster.github.io/setting-up-ci/` also the website could also say that besides Jenkins we also support Travis, Circle and Gitlab (thought the [ci-module](https://www.npmjs.com/package/generator-jhipster-ci))
- [x] Add a section on service discovery and configuration for microservices

<s> [ ]  Move the README file from the server subgen to the app subgen </s> Not practical for now as most of the docs relate to the server side, possible to do separate readme template for skipServer in the future.
- [x] Correct the docs about the docker-compose subgen and monolith
- [x] Add a warning banner on the archive.

If you have additional ideas or disagree with some of the points I made please let me know and I will edit the check-list.

**Comment by deepu105** [comment]
a big 👍

**Comment by jdubois** [comment]
Yes +1

**Comment by jdubois** [comment]
But don't duplicate the documentation from the website: all "long explanations" should be on the website (easier to manage), and then put links to them from the readme.

**Comment by PierreBesson** [comment]
Should we also move the Readme out of the `server` subgen as we can now have JHipster apps that don't have a backend, should I put it in the `app` subgen instead ?

**Comment by jdubois** [comment]
Oh yes

**Comment by PierreBesson** [comment]
Question: Should I link to the archive for all links in the README or just the first one ?

Also I just noticed that this section: http://jhipster.github.io/docker-compose/#microservices incorrectly states that the docker-compose subgen can only by used with microservices however it works very nicely for monolith as demonstrated [here](https://github.com/jhipster/jhipster-docker-hub/blob/master/jhipster-sample-app/prod-elk.yml).

@jdubois Do I have your permission to mention the docker-compose subgen on the README so we can boost adoption ?

**Comment by jdubois** [comment]
- I would point to the archive everywhere in the readme, or the documentation might not be correct.
- I had no idea the docker-compose subgen could be used in monoliths... And I coded a big part of it :-) So yes if you can use it in monoliths, don't hesitate to change the doc!

**Comment by PierreBesson** [comment]
I'm done with readme improvements, I will close this issue once I have finished the few docs improvements that I want to do.

**Comment by pascalgrimaud** [comment]
@PierreBesson : FYI, I think there is an issue with the current README
I saw 'undefined':
`This application was generated using JHipster , you can find documentation and help at [https://jhipster.github.io/documentation-archive/vundefined](https://jhipster.github.io/documentation-archive/vundefined).

**Comment by PierreBesson** [comment]
What remains to do here is:
- improve CI docs as I removed the CI section in the readme
- add a warning banner to the archive pages.
Then we can close the issue.

**Comment by jdubois** [comment]
I have the warning banner working, let me finish testing and publishing!

**Comment by jdubois** [comment]
The warning should be OK! There are so many pages it's impossible to test everything, of course.

**Comment by PierreBesson** [comment]
I have done a PR to the docs. Finally all the boxes are ticked.

**Comment by PierreBesson** [comment]
@jdubois, It does work but the banner is quite ugly on the V3 website because of the sidebar...

![capture du 2016-11-04 00-10-15](https://cloud.githubusercontent.com/assets/513471/19988916/4ef5969a-a223-11e6-88bc-ab2f91e254ca.png)
![capture du 2016-11-04 00-10-05](https://cloud.githubusercontent.com/assets/513471/19988917/4efbd2c6-a223-11e6-89e3-bcd8a36eb7d0.png)

Now, that I'm thinking about it, we could make use of one of those cookie popup libs like this one:
https://github.com/dobarkod/cookie-banner
Usually, I'm annoyed by those but this would be quite a nice use of it as the users could click to hide it once and it will be remembered thanks to the cookie !

**Comment by PierreBesson** [comment]
@jdubois, It does work but the banner is quite ugly on the V3 website because of the sidebar...

![capture du 2016-11-04 00-10-15](https://cloud.githubusercontent.com/assets/513471/19988916/4ef5969a-a223-11e6-88bc-ab2f91e254ca.png)
![capture du 2016-11-04 00-10-05](https://cloud.githubusercontent.com/assets/513471/19988917/4efbd2c6-a223-11e6-89e3-bcd8a36eb7d0.png)

Now, that I'm thinking about it, we could make use of one of those cookie popup libs like this one:
https://github.com/dobarkod/cookie-banner
Usually, I'm annoyed by those but this would be quite a nice use of it as the users could click to hide it once and it will be remembered thanks to the cookie !

**Comment by jdubois** [comment]
Yes +1 for doing this, can you do it? Not sure when I will the time.
Otherwise I know it's ugly, but at least it's clear!
