### ISSUE TITLE
mvn liquibase:update gives liquibase.exception.SetupException

### ISSUE THREAD

**Issue by brunnels** [jhipster/generator-jhipster#4216]
Issue #1130 still exists but it was closed.  I have tested and removing all ```classpath:``` from the master.xml for all the include files fixed the maven goal and didn't break anything with the spring-boot:run goal or any other goal I tried.

**Comment by jdubois** [comment]
See my comment at https://github.com/jhipster/generator-jhipster/issues/1130#issuecomment-73987509
I'm sorry but I have no idea what you are doing with this goal, I have never used it and I don't know what it's supposed to do.

- We are doing a major update of Liquibase at the moment, so hopefully this will solve your issue, and make everybody happy
- If you have a good use case for this goal, please document it and post it: either here, or even as a tip on the website. At least I will learn what you are trying to do, and that can only be good.

**Comment by brunnels** [comment]
I'm just utilizing liquibase as intended for normal database updates, migrations, etc... unrelated to jhipster project generation.  The reason for this ticket is that it's just something else to diff/update whenever I generate or upgrade a jhipster project and it doesn't appear that removing ```classpath:``` from the generated master.xml impacts anything that jhipster is doing.

**Comment by agoncal** [comment]
@jdubois I agree with @brunnels. 

You are focusing on `mvn liquibase:update` but there are other goals such as `liquibase:status`, for example, that do not work if you don't fix the `classpath:`. I got rid of the `classpath:` on the `master.xml` file and it's working fine : runtime and mvn commands (I have around 40 Liquibase XML files). 

I think this should be fixed. WDYT ?

**Comment by jdubois** [comment]
@agoncal I never looked at those other goals, so you know better than me!!! So yes if you can fix something there, PR is welcome

**Comment by gmarziou** [comment]
This makes me wonder why we don't use [liquibase-gradle-plugin](https://github.com/liquibase/liquibase-gradle-plugin), it seems to be maintained by Liquibase project.

**Comment by deepu105** [comment]
If they do then we should I guess


Thanks & Regards,
Deepu

**Comment by skilledboy** [comment]
How to run the rollbacktag of Liquibase in Jhipster?
and tried to rollback tag of liquibase in jhipster, but I do not succeed.
```
def liquibaseCommand(command) {
    javaexec {
        if (OperatingSystem.current().isWindows()) {
            classpath files(pathingLiquibaseJar.archivePath)
        } else {
            classpath sourceSets.main.runtimeClasspath
            classpath configurations.liquibase
        }
        main = "liquibase.integration.commandline.Main"

        args "--changeLogFile=src/main/resources/config/liquibase/changelog/" + buildTimestamp() +"_changelog.xml"
        args "--referenceUrl=hibernate:spring:cl.databin.fact.domain?dialect=org.hibernate.dialect.PostgreSQL82Dialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"
        args "--username=postgres"
        args "--password=mypass"
        args "--url=jdbc:postgresql://localhost:5432/testdbjhipster"
        args "--driver=org.postgresql.Driver"
        args command
    }
}
task rollbackTag(dependsOn: initPaths) {
    doLast {
        liquibaseCommand("rollback")
    }
}
```
and when I execute
` ./gradlew rollbackTag -PliquibaseCommandValue=1.0.0-0.1`
ERROR liquibase - rollback requires a rollback tag

Thank!
