### ISSUE TITLE
Skip github check if the application is a microservice

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#4217]
Since a microservice doesn't have a front end, gh check is unnecessary and slows down the generator (until timeout) if the app is generated off-line.

**Comment by jdubois** [comment]
Then isn't it an issue, as we are supposed to have the `generator-jhipster` in `node_modules` so we use the same version when we re-generate a project?

**Comment by cbornet** [comment]
Indeed, a microservice doesn't have a package.json...

**Comment by pascalgrimaud** [comment]
@cbornet : FYI, you could use `yo jhipster --no-check-installation` to avoid this check

But the github check is done before the 1st question, so how can we know the user will generate a microservice?
Do you mean for regenerating a project with an `.yo-rc.json` ?

**Comment by jdubois** [comment]
And I guess we also use this check to see if there is a new release and warn the user, which I find pretty neat.

**Comment by deepu105** [comment]
@jdubois that check is a different one. But I do find the the below check time consuming and I'm wondering do we really have to do a github connectivity check?
```
checkGitConnection: function () {
            if (!this.gitInstalled) return;
            var done = this.async();
            exec('git ls-remote git://github.com/jhipster/generator-jhipster.git HEAD', {timeout: 15000}, function (error) {
                if (error) {
                    this.warning('Failed to connect to "git://github.com"\n',
                        ' 1. Check your Internet connection.\n',
                        ' 2. If you are using an HTTP proxy, try this command: ' + chalk.yellow('git config --global url."https://".insteadOf git://')
                    );
                }
                done();
            }.bind(this));
        },
```

**Comment by pascalgrimaud** [comment]
bower needs it for download their libs, right ?

**Comment by deepu105** [comment]
@pascalgrimaud yes and if github isnt connected user would know anyway right? atleast we could make this particular check async by calling the `done();` outside the `exec` block. only downside being we might see a warning log somewhere inbetween a generation

**Comment by jdubois** [comment]
It's very important to warn people when there is a network issue. Since we have this check, we have a lot less errors from people behind corporate proxies.
So I really like it, and it's good that it's at the beginning of the script, so that people have immediate feedback when there is an error. I wouldn't move it, and we have a lot more better things to do, we have lots of opened bugs at the moment.
