### ISSUE TITLE
Add generator-jhipster as an npm dependency if the app is a microservice

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#4218]
See #4217 

We should ensure that the same version of jhipster is used when regenererating a micro-service.

**Comment by pascalgrimaud** [comment]
what do you think about adding documentation for this with `npm install generator-jhipster` ?

**Comment by jdubois** [comment]
- I would like this to be automated, so no I don't want to have just documentation for this
- This means we need the `frontend-maven-plugin` for microservices too, which is quite annoying

**Comment by cbornet** [comment]
Why not just a package.json + npm/yarn install ?

**Comment by PierreBesson** [comment]
@jdubois Why would we need the frontend-maven plugin ? Maybe we can use this simple lib (https://github.com/npm/init-package-json) and run `npm install`

**Comment by jdubois** [comment]
You know this better than I do :-)

**Comment by deepu105** [comment]
Lest just put a package.json for this no need of another lib I guess

Thanks & regards,
Deepu
