### ISSUE TITLE
[FEATURE] HTTPS support out of the box

### ISSUE THREAD

**Issue by bjoernw** [jhipster/generator-jhipster#4219]
I know there is a write-up in the tips and tricks section about enabling SSL but given the ease of getting ssl working with Lets Encrypt I was wondering whether jhipster shouldn't just go https by default. Any thoughts?

**Comment by mraible** [comment]
+1, but it might make it difficult to develop locally since you'll have to generate a certificate and click past Chrome's warning. On a similar note, I'd like to see HTTP/2 as the default.

**Comment by bjoernw** [comment]
@mraible I have ssl turned off in dev. Also, Lets Encrypt gets you a proper cert signed by an authority that your browser already knows. SSL could also just be a recommended option during the setup process.

**Comment by jdubois** [comment]
I'd love to have it, but I haven't found a good way to set it up.
Biggest issue is that you need to have port 80 opened to the outside world, and that's impossible in many use-cases: people behind corporate proxies or for microservices...
So if you have a good setup please describe it.

**Comment by bjoernw** [comment]
We could get around that by forwarding all 80 traffic to the 43. Good to hear that there is support for a proper solution. Let me brainstorm and come up with some ideas around implementation. I'll add my pitch here.

**Comment by PierreBesson** [comment]
I have already done the LetsEncryp setup for a JHipster app (actually it was the JHipster-Registry), it was very easy, here are the steps I followed from a note that was sitting around in my computer.

###  On your server, run let's encrypt, for example with docker:
```
docker run -it --rm -p 443:443 -p 80:80 --name certbot \
            -v "/etc/letsencrypt:/etc/letsencrypt" \
            -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
            quay.io/letsencrypt/letsencrypt:latest certonly
```
> Answer the questions that are asked....

### Generate the pkcs12 keystore:
Go to your keys directory:
`cd /etc/letsencrypt/live/pbesson.com/`

Generate the keystore.p12 file from your .pem files.
`openssl pkcs12 -export -in fullchain.pem -inkey privkey.pem -out keystore.p12 -name tomcat -CAfile chain.pem -caname root`
> You will be prompted for a password

### Launch your app with the correct properties
Then I run my app using docker with the following command : 

```
docker run -p 443:8761 -d \
    -v /etc/letsencrypt/live/pbesson.com/:/letsencrypt/ \
    -e SECURITY_REQUIRE_SSL=true \
    -e SERVER_SSL_KEY_STORE=/letsencrypt/keystore.p12 \
    -e SERVER_SSL_KEY_STORE_PASSWORD=123456 \
    -e SERVER_SSL_KEYSTORETYPE=PKCS12 \
    -e SERVER_SSL_KEYALIAS=tomcat \
     jhipster/jhipster-registry
```
If you don't have a way to pass those env vars, you could add them to your prod properties by the config server or maybe define a specific `ssl profile` that contain those keys.

@mraible Also really interested by HTTP2, I had try before but it was complicated to do with Tomcat, but it should be possible now that we have moved to Undertow, let's try to have it as default for JHipster 4.0 !

**Comment by jdubois** [comment]
Yes that's perfect for a tip, but still I don't know how this could be automated. You need to have the ports opened, that's just not possible (and not a good idea!) for a lot of people.

**Comment by bjoernw** [comment]
If we take the Lets Encrypt piece out of it and make the use of SSL in production "recommended" but clearly an option during the project generation then we could generate a self-signed cert to start with and add a section to the documentation on how to get a cert from Lets Encrypt.

**Comment by jdubois** [comment]
- We cannot enforce this for everyone. A lot of people are behind corporate firewalls, doing internal apps, so this isn't good for them.
- Doing "normal SSL" (not letsencrypt) is very easy, it's probably even against our [Policy 2](http://jhipster.github.io/policies/) to include it.
- @PierreBesson I'd love to have your letsencrypt configuration as a tip: could you do it? If you don't have the time, can we copy/paste it?
- for Hazelcast that's a totally different issue: I don't understand why you are encrypting your own internal network, this is eating your performance and if an attacker is here you're in a very bad position anyway (are your JDBC connections encrypted too?). And if you need SSL, just do a tunnel, you won't have to pay for it and performance might be better (as it wouldn't use Java for doing the encryption).

I'm closing this as I think this should just be a "tip", and hopefully @PierreBesson will do it.

**Comment by PierreBesson** [comment]
I will do the tip, also check if it works one last time.

**Comment by xetys** [comment]
@PierreBesson as an alternative, we maybe should provide some docs how to use letsencrypt instead?

**Comment by PierreBesson** [comment]
@xetys, I don't understand, my post was precisely about using letsencrypt.
