### ISSUE TITLE
App incompatible with MySQL 5.5

### ISSUE THREAD

**Issue by ddamw** [jhipster/generator-jhipster#4226]
##### **Overview of the issue**

The following commit breaks compatibility with MySQL 5.5:
[https://github.com/jhipster/generator-jhipster/commit/cfb846868328cf4262a20112aec614217ca3f4ff#diff-bdea77b7a2867f44460ea2e17da52ae0
](https://github.com/jhipster/generator-jhipster/commit/cfb846868328cf4262a20112aec614217ca3f4ff#diff-bdea77b7a2867f44460ea2e17da52ae0
)

The commit introduced a second default of now() to a column in the jhi_user table. MySQL 5.5 does not support this:

`Error: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause [Failed SQL: CREATE TABLE tcwallboard.jhi_user (id BIGINT AUTO_INCREMENT NOT NULL, login VARCHAR(50) NOT NULL, password_hash VARCHAR(60) NULL, first_name VARCHAR(50) NULL, last_name VARCHAR(50) NULL, email VARCHAR(100) NULL, activated BIT(1) NOT NULL, lang_key VARCHAR(5) NULL, activation_key VARCHAR(20) NULL, reset_key VARCHAR(20) NULL, created_by VARCHAR(50) NOT NULL, created_date timestamp DEFAULT NOW() NOT NULL, reset_date timestamp NULL, last_modified_by VARCHAR(50) NULL, last_modified_date timestamp DEFAULT NOW() NULL, CONSTRAINT PK_JHI_USER PRIMARY KEY (id), UNIQUE (login), UNIQUE (email))]`

The MySQL error code is 1293.

Support for multiple defaults at now() was added to MySQL 5.6

##### **Motivation for or Use Case**

Although the stable version of MySQL is currently 5.7, our applications run mostly on Debian based systems. The current version of Debian (Jessie) has MySQL 5.5 in it's official repositories. 

##### **Reproduce the error**

Generate a new application with MySQL database support, run it in prod profile and connect it to a MySQL 5.5 server

##### **Suggest a Fix**

I can think of a few fixes:

1. revert the change
2. add MySQL >=5.6 as an official requirement (when using MySQL)
3. add a warning to the generator when selecting MySQL as a database backend

##### **JHipster Version(s)**

3.5.0 and upwards

##### **JHipster configuration**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.8.0",
    "baseName": "OurApp",
    "packageName": "com.company.ourapp",
    "packageFolder": "com/company/ourapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "messageBroker": false
  }
}

**Comment by jdubois** [comment]
Yes I know this, our MySQL Docker image was updated for this use-case.

We could have another look at how to solve this, but we can't support old versions of all databases.

**Comment by ddamw** [comment]
I understand and support that view. I mainly wrote this issue for others that encounter similar issues to find, as I could not find one myself.

Is it possible to have an official statement on which (external) systems are supported?

**Comment by jdubois** [comment]
Basically we support the versions that are in our Docker files, as they are the ones we use for testing.
Then, usually we don't have the kind of issues we have here, so we support much broader version ranges - it's just they are not tested!

**Comment by jdubois** [comment]
I had a look, and using that "now" function isn't very important: we used to have NULL fields here before, and this wasn't doing much harm.
So I think we should remove it -> @deepu105 as you are the one who did the change, are you OK with it?

**Comment by deepu105** [comment]
Let me take a look

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
Ok i had a look. personally I think we shouldnt be supported all the older versions of every DB as that would restrict what we can do in terms of hip stuff. having said that as @jdubois said using now() here is not very important. So ill make a fix for this

**Comment by jdubois** [comment]
Fully agreed!
Thanks Deepu!!

Le 30 sept. 2016 7:10 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by ddamw** [comment]
Thanks everyone, this sure helps us a lot!

**Comment by deepu105** [comment]
Btw you could have removed it from your changelog as well. I think its
really silly of mysql to have such a restriction

Thanks & regards,
Deepu
