### ISSUE TITLE
SecurityBeanOverride in UAA is unecessary and makes tests fail

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#4228]
this a issue for me to solve soonly:

SecurituBeanOverride makes no sense to use inside UAA apps, as they don't fetch token keys from uaa...obviously....so it should be removed that, in order to have no failing tests (for me, this happened today)

**Comment by pascalgrimaud** [comment]
@xetys : is the problem resolved ? I ask you because our new Travis build with uaa seems to work perfectly

**Comment by xetys** [comment]
I will check this asap

пт, 14 Окт 2016 г., 8:10 Pascal Grimaud <notifications@github.com>:
