### ISSUE TITLE
The marketplace is broken

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4230]
Going to https://jhipster.github.io/modules/marketplace/#/list gives an empty list... There's an error in the REST endpoint

**Comment by cbornet** [comment]
Works fine for me.
Are you on mobile ?

**Comment by ruddell** [comment]
It's only broken for https.  The issue is that npmsearch.com's SSL chain is invalid.

**Comment by jdubois** [comment]
Yes, I've opened a ticket on https://github.com/solids/npmsearch/issues/38
But that's a small project, and that seems self-hosted, so I don't think we should rely on them for something as important as the marketplace

**Comment by jdubois** [comment]
It has been very quickly by @tmpvar !!! That's great!

**Comment by tmpvar** [comment]
yeah, sorry for the hiccup y'all!
