### ISSUE TITLE
JDL unable to generate angular suffix

### ISSUE THREAD

**Issue by sanjayrawat1** [jhipster/generator-jhipster#4232]
##### **Overview of the issue**

When generating entities with **angularSuffix** option via import-jdl, the generated entities not including angular suffix. When I generate same entity via **yo jhipster:entity X --angular-suffix mySuperEntity**  command, entities are including angular suffix.

Sample JDL file:-
**jhipster-jdl.jh**
```
entity X

angularSuffix * with mySuperEntity
```

##### **Motivation for or Use Case**

When I am generating entities via import-jdl then it is creating json file as:-
**X.json**
```
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [],
    "changelogDate": "20160929055517",
    "entityTableName": "x",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "angularSuffix": "mySuperEntity"
}
```

But when I create same entity using command **yo jhipster:entity X --angular-suffix mySuperEntity** then it is creating json file as:-
**X.json**
```
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [],
    "changelogDate": "20160929055830",
    "dto": "no",
    "service": "no",
    "entityTableName": "x",
    "pagination": "no",
    "angularJSSuffix": "-mySuperEntity"
}
```
Now from the above json file we can see the difference(1st approach using **angularSuffix** while 2nd approach using **angularJSSuffix** in json file), and the second approach (i.e **yo jhipster:entity X --angular-suffix mySuperEntity** command) is working fine.

##### **Reproduce the error**

Use above mention jdl file using **yo jhipster:import-jdl jhipster-jdl.jh** command or create entity using **yo jhipster:entity X --angular-suffix mySuperEntity** command.

##### **Suggest a Fix**

As we can see from generated json files the attribute is different in both case(angularSuffix and angularJSSuffix respectively). If angularJSSuffix is the right way then when json files are generated using import-jdl generate json with correct syntax.

##### **JHipster Version(s)**

v3.8.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.8.0",
    "baseName": "testApp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "1-1-1-1-1",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Json files are specified above.

##### **Browsers and Operating System**

OS: Fedora release 23 (Twenty Three)

**Comment by cbornet** [comment]
This is fixed in jhipster-core (https://github.com/jhipster/jhipster-core/pull/65). So we need a new version of jhipster-core and an update of the jhipster dependencies.

**Comment by cbornet** [comment]
cc @MathieuAA

**Comment by MathieuAA** [comment]
Thanks

Le 29 septembre 2016 09:50:02 GMT+02:00, Christophe Bornet <notifications@github.com> a écrit :
>cc @MathieuAA 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/4232#issuecomment-250395562

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
@MathieuAA there are quite a few fixes I guess cana we have a patch release? If you dont have time I can do it

**Comment by MathieuAA** [comment]
@deepu105 Waiting for #60 to be closed.

**Comment by MathieuAA** [comment]
@deepu105 if you think it will take too long to get it done, tell me. I'll release ASAP.

**Comment by deepu105** [comment]
Yes 60 is tricky so will take some time. It can be for next release if it
all it needs work here in the first place. Im thinking of handling it from
the import jdl sub gen itself

Thanks & regards,
Deepu

**Comment by MathieuAA** [comment]
Got it Deepu. I'm going to do a release right now.
