### ISSUE TITLE
Issue while running **mvn clean install** nested exception is org.hibernate.HibernateException: Missing table: order ... There are 76 nested exceptions... Build Failed

### ISSUE THREAD

**Issue by vaidyaanand** [jhipster/generator-jhipster#4234]
##### **Overview of the issue**
This app was developed in 2015. But now I have to make some enhancements in the app. I have check jhipster release version 2.8.0 their they specify : 
one big change in JHipster: we are changing the way we name our database tables!
We now check for reserved keywords when an entity is being generated: you can’t use Java, MySQL, PostgreSQL or Cassandra reserved keywords.

Is this error generated due to this reason ? 

##### **Reproduce the error**
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.setFilterChainProxySecurityConfigurer(org.springframework.security.config.annotation.ObjectPostProcessor,java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'securityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.security.core.userdetails.UserDetailsService com.orderone.app.config.SecurityConfiguration.userDetailsService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userDetailsService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.orderone.app.repository.UserRepository com.orderone.app.security.UserDetailsService.userRepository; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Cannot create inner bean '(inner bean)#34e5fa14' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#34e5fa14': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Missing table: order

##### **Related issues**
Results :

Tests in error: 
  UserServiceTest.assertThatOnlyActivatedUserCanRequestPasswordReset » IllegalState
  UserServiceTest.assertThatUserMustExistToResetPassword » IllegalState Failed t...
  UserServiceTest.assertThatResetKeyMustBeValid » IllegalState Failed to load Ap...
  UserServiceTest.assertThatUserCanResetPassword » IllegalState Failed to load A...
  UserServiceTest.testFindNotActivatedUsersByCreationDateBefore » IllegalState F...
  UserServiceTest.assertThatResetKeyMustNotBeOlderThan24Hours » IllegalState Fai...
  AccountResourceTest.testRegisterInvalidEmail » IllegalState Failed to load App...
  AccountResourceTest.testRegisterInvalidLogin » IllegalState Failed to load App...
  AccountResourceTest.testRegisterAdminIsIgnored » IllegalState Failed to load A...
  AccountResourceTest.testGetUnknownAccount » IllegalState Failed to load Applic...
  AccountResourceTest.testRegisterDuplicateEmail » IllegalState Failed to load A...
  AccountResourceTest.testRegisterDuplicateLogin » IllegalState Failed to load A...
  AccountResourceTest.testAuthenticatedUser » IllegalState Failed to load Applic...
  AccountResourceTest.testRegisterValid » IllegalState Failed to load Applicatio...
  AccountResourceTest.testNonAuthenticatedUser » IllegalState Failed to load App...
  AccountResourceTest.testGetExistingAccount » IllegalState Failed to load Appli...
  AuditResourceTest.getNonExistingAudit » IllegalState Failed to load Applicatio...
  AuditResourceTest.getAllAudits » IllegalState Failed to load ApplicationContex...
  AuditResourceTest.getAudit » IllegalState Failed to load ApplicationContext
  CategoryResourceTest.getNonExistingCategory » IllegalState Failed to load Appl...
  CategoryResourceTest.deleteCategory » IllegalState Failed to load ApplicationC...
  CategoryResourceTest.getAllCategorys » IllegalState Failed to load Application...
  CategoryResourceTest.updateCategory » IllegalState Failed to load ApplicationC...
  CategoryResourceTest.createCategory » IllegalState Failed to load ApplicationC...
  CategoryResourceTest.checkNameIsRequired » IllegalState Failed to load Applica...
  CategoryResourceTest.getCategory » IllegalState Failed to load ApplicationCont...
  FeedbackResourceTest.updateFeedback » IllegalState Failed to load ApplicationC...
  FeedbackResourceTest.createFeedback » IllegalState Failed to load ApplicationC...
  FeedbackResourceTest.getAllFeedbacks » IllegalState Failed to load Application...
  FeedbackResourceTest.getFeedback » IllegalState Failed to load ApplicationCont...
  FeedbackResourceTest.getNonExistingFeedback » IllegalState Failed to load Appl...
  FeedbackResourceTest.deleteFeedback » IllegalState Failed to load ApplicationC...
  InventoryResourceTest.getInventory » IllegalState Failed to load ApplicationCo...
  InventoryResourceTest.deleteInventory » IllegalState Failed to load Applicatio...
  InventoryResourceTest.updateInventory » IllegalState Failed to load Applicatio...
  InventoryResourceTest.getAllInventorys » IllegalState Failed to load Applicati...
  InventoryResourceTest.getNonExistingInventory » IllegalState Failed to load Ap...
  InventoryResourceTest.createInventory » IllegalState Failed to load Applicatio...
  InvitationResourceTest.createInvitation » IllegalState Failed to load Applicat...
  InvitationResourceTest.deleteInvitation » IllegalState Failed to load Applicat...
  InvitationResourceTest.updateInvitation » IllegalState Failed to load Applicat...
  InvitationResourceTest.getNonExistingInvitation » IllegalState Failed to load ...
  InvitationResourceTest.getInvitation » IllegalState Failed to load Application...
  InvitationResourceTest.getAllInvitations » IllegalState Failed to load Applica...
  InvitationResourceTest.checkNameIsRequired » IllegalState Failed to load Appli...
  NotificationResourceTest.getNotification » IllegalState Failed to load Applica...
  NotificationResourceTest.createNotification » IllegalState Failed to load Appl...
  NotificationResourceTest.getAllNotifications » IllegalState Failed to load App...
  NotificationResourceTest.deleteNotification » IllegalState Failed to load Appl...
  NotificationResourceTest.updateNotification » IllegalState Failed to load Appl...
  NotificationResourceTest.getNonExistingNotification » IllegalState Failed to l...
  NotificationResourceTest.checkTextIsRequired » IllegalState Failed to load App...
  OrderResourceTest.createOrderone » IllegalState Failed to load ApplicationCont...
  OrderResourceTest.getAllOrderones » IllegalState Failed to load ApplicationCon...
  OrderResourceTest.checkOrderDateIsRequired » IllegalState Failed to load Appli...
  OrderResourceTest.getOrderone » IllegalState Failed to load ApplicationContext
  OrderResourceTest.getNonExistingOrderone » IllegalState Failed to load Applica...
  OrderResourceTest.deleteOrderone » IllegalState Failed to load ApplicationCont...
  OrderResourceTest.checkOrderNumberIsRequired » IllegalState Failed to load App...
  OrderResourceTest.updateOrderone » IllegalState Failed to load ApplicationCont...
  ProductResourceTest.updateProduct » IllegalState Failed to load ApplicationCon...
  ProductResourceTest.getAllProducts » IllegalState Failed to load ApplicationCo...
  ProductResourceTest.deleteProduct » IllegalState Failed to load ApplicationCon...
  ProductResourceTest.getProduct » IllegalState Failed to load ApplicationContex...
  ProductResourceTest.getNonExistingProduct » IllegalState Failed to load Applic...
  ProductResourceTest.checkNameIsRequired » IllegalState Failed to load Applicat...
  ProductResourceTest.createProduct » IllegalState Failed to load ApplicationCon...
  ShopResourceTest.getAllShops » IllegalState Failed to load ApplicationContext
  ShopResourceTest.updateShop » IllegalState Failed to load ApplicationContext
  ShopResourceTest.getShop » IllegalState Failed to load ApplicationContext
  ShopResourceTest.getNonExistingShop » IllegalState Failed to load ApplicationC...
  ShopResourceTest.createShop » IllegalState Failed to load ApplicationContext
  ShopResourceTest.checkNameIsRequired » IllegalState Failed to load Application...
  ShopResourceTest.deleteShop » IllegalState Failed to load ApplicationContext
  UserResourceTest.testGetUnknownUser » IllegalState Failed to load ApplicationC...
  UserResourceTest.testGetExistingUser » IllegalState Failed to load Application...

Tests run: 79, Failures: 0, Errors: 76, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:34 min
[INFO] Finished at: 2016-09-29T17:34:30+05:30
[INFO] Final Memory: 40M/398M

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

order.JSON
{
    "relationships": [],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "dsn_number",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 2,
            "fieldName": "dsn_date",
            "fieldType": "DateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20151207161922",
    "dto": "no",
    "pagination": "no"
}
##### **Browsers and Operating System**
Windows 7

**Comment by jdubois** [comment]
- You did not provide your .yo-rc.json file, so I'm closing to close this
- Calling a table "order" looks very strange, isn't it a reserved SQL keyword? Anyway your issue is that the "order" table is missing, so you probably had a problem running Liquibase, but you don't give the correct stacktrace for that

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by vaidyaanand** [comment]
So what data yo need ?

**Comment by jdubois** [comment]
your .yo-rc.json file, and the correct stacktrace.

**Comment by vaidyaanand** [comment]
ok I will provide it... reopen it...

**Comment by vaidyaanand** [comment]
editing the contents

**Comment by jdubois** [comment]
And I just tried creating an "Order" table and correctly had the following error message:

    ERROR! The table name cannot contain a MYSQL reserved keyword

So I don't know what you did, but this shouldn't be possible

**Comment by vaidyaanand** [comment]
Yes I already know that... I havent generated the code... as i mention this app was coded in 2015. at that time jhipster didnt throw error while creating entity by this name... now I have to make some enhancements in my project.

**Comment by vaidyaanand** [comment]
I am uploading the test logs and .yo-rc file please wait

**Comment by jdubois** [comment]
OK thanks for updating the comments, but then I don't see why this is a JHipster bug? At least this is solved for 1 year, as we don't allow to use reserved keywords.
And in 2015, the idea was that people would not well enough their database, and would not use reserved keywords.

**Comment by vaidyaanand** [comment]
Yes I agree a great step make from your side to block use of reserved keywords... But sir I need a solution to make enhancement in project ... I just want to change name of entity order. I am even not able to rename order entity by cmd.exe...

**Comment by jdubois** [comment]
OK but this is not a JHipster bug. You are developing your project, and I'm very happy for you that your project is successful, but if you want to "enhance" it, that's just normal software development.
The bug tracker is only for JHipster bugs.

**Comment by vaidyaanand** [comment]
Yes. so, where should I raise this issue to get the solution ?

**Comment by vaidyaanand** [comment]
can you be able to suggest the solution here ?

**Comment by jdubois** [comment]
We can ask StackOverflow or gitter.im, maybe someone will help you -> please follow the project guidelines
