### ISSUE TITLE
yo jhipster:upgrade fails on 3.7.1 to 3.8.0 upgrade on first upgrade

### ISSUE THREAD

**Issue by piprog** [jhipster/generator-jhipster#4239]
##### **Overview of the issue**

Tried `yo jhipster:upgrade` on a project generated with 3.7.1 that is under git (and also has a Remote on BitBucket, everything pushed). This was the first try to upgrade so "Specific steps executed on first upgrade" was in effect. Build with 3.7.1 went well, then the following error message came:

```
Successfully regenerated app with jhipster 3.7.1
Committed with message "Generated with JHipster 3.7.1"
Checked out branch "master"
Error jhipster:upgrade

ERROR! Unable to record current code has been generated with version 3.7.1:
 fatal: refusing to merge unrelated histories

```

##### **Motivation for or Use Case**

Typical use case.

##### **Reproduce the error**

run yo jhipster:upgrade

##### **Related issues**

none with the "refusing to merge unrelated histories" message

##### **Suggest a Fix**

none

##### **JHipster Version(s)**

3.7.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.7.1",
    "baseName": "LLMS",
    "packageName": "com.pannonrex.llms",
    "packageFolder": "com/pannonrex/llms",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "...",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de",
      "hu"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

Chorme 53.0.2785.116 m (64-bit) (latest) / Win10

**Comment by piprog** [comment]
Git version may be relevant: git version 2.10.0.windows.1

**Comment by jdubois** [comment]
I confirm, I have the same issue on Mac OS X....
Ping @lordlothar99 as he coded this part!

**Comment by lordlothar99** [comment]
seems like it's a Git issue ; I'll try to reproduce that with same Git version
