### ISSUE TITLE
i18n missing social label

### ISSUE THREAD

**Issue by lrkwz** [jhipster/generator-jhipster#4245]
I cannot understand where the social label come from: 
I've deployed a bi-lingual app (english + italian) here http://garanteasy.com/app/#/register (beta!) and the registration form correctly displays the social registration buttons in English only; if you switch to Italian ther's written "{label}" instead of "Google, ...".

jhipster 3.5.1

**Comment by pascalgrimaud** [comment]
Comparing [en/social.json](https://github.com/jhipster/generator-jhipster/blob/master/generators/languages/templates/src/main/webapp/i18n/en/social.json#L3) and [it/social.json](https://github.com/jhipster/generator-jhipster/blob/master/generators/languages/templates/src/main/webapp/i18n/it/social.json#L3), maybe a `{` is missing

I think it should be `"btnLabel": "Accedi con {{ label }}"` instead. Can you try this ?

**Comment by lrkwz** [comment]
Yes fantastic I read it dozed of times without noticing it.

**Comment by deepu105** [comment]
Can some one PR a patch?

Thanks & regards,
Deepu

**Comment by pascalgrimaud** [comment]
I will do that
Le 3 oct. 2016 6:56 AM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

> Can some one PR a patch?
>
> Thanks & regards,
> Deepu
>

**Comment by jdubois** [comment]
Re-opened until there is a PR.
