### ISSUE TITLE
Configuring IDEA "compile on save"

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#4258]
I have IDEA "compile on save" working with the following config steps:
* File -> Settings -> Build, Execution, Deployment -> Compiler : enable "Make project automatically"
* Open Registry (Linux : `CTRL+SHIFT+A`, choose `Registry...`) and enable `compiler.automake.allow.when.app.running`

Should we update the jhipster.github.io configuring-ide with this setup ?
I think the command to open the action window is `CTRL+COMMAND+A` on OSX and `CTRL+ALT+SHIFT+/` on Windows but could someone verify on those OSes ?

**Comment by PierreBesson** [comment]
Good initiative, it is Cmd+Shift+A on Mac OS.

2016-10-04 14:35 GMT+02:00 Christophe Bornet <notifications@github.com>:

**Comment by pascalgrimaud** [comment]
+1 for improving our docs!

**Comment by brunnels** [comment]
Confirmed it's ```CTRL+ALT+SHIFT+/``` on Windows

Testing it out now

**Comment by jdubois** [comment]
Closing as the PR is merged
