### ISSUE TITLE
Update the CSRF protection mechanism

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4272]
We currently have our own CSRF cookie implementation:

- This configuration could be found both in `CsrfCookieGeneratorFilter` and `CustomAccessDeniedHandler`
- It works well, and we haven't had any bugs with it for a long time

But it causes 2 issues:

- Sonar sees the cookie as a security issue, as it doesn't have the "secure" attribute. We can't use that attribute, or the application wouldn't run in HTTP, and that's annoying (at least for development). This is 2 out of the 3 vulnerabilities seen by Sonar, so it would be good to solve this.
- Spring Security has progressed on this part, see their [CSRF documentation](http://docs.spring.io/spring-security/site/docs/current/reference/html/csrf.html) which didn't exist when we coded the CSRF cookie in JHipster -> so probably we could use this implementation, and remove most of our code

So I'd like to migrate to the CSRF implementation from Spring Security, as it would solve the Sonar issue and remove a lot of useless lines.

Of course this needs to have very good testing, so that's quite a lot of work (you need to test when the session times out, and for the various error cases - when the token is invalid, etc).

**Comment by lluiscanals** [comment]
Do you think it will allow using CSRF with websockets? As far as I know this implementation is broken as said in jhipster documentation. Maybe another thing to test 😅

**Comment by jdubois** [comment]
No idea! Yes one more thing to look at.

**Comment by nkolosnjaji** [comment]
Did somebody started working on this? If not, I can try this one.

**Comment by jdubois** [comment]
Oh @nkolosnjaji that would be really nice of you! I wanted to do it, but I'll start a new gig tomorrow and it's clear I won't have the time in the next few days.
I know this fairly well, so I'll be able to test and review your code.

Some important things to note:

- Testing this is really annoying, you need to do a CSRF attack yourself to see if it works or not
- You can follow [this article from Dave Syer](https://spring.io/blog/2015/01/12/the-login-page-angular-js-and-spring-security-part-ii). Usually the Spring guys do it the other way around, they reconfigure AngularJS (when we re-configure Spring). That's probably easier, but that would cause issue with our AngularJS 2 migration -> have a look at the "ng2" branch, you need to test that too...
- We should only have the issue only with "session-based" authentication, but you need to test the others just in case you break anything
- Testing with Gatling and Protractor both use this, so you need to make sure they also work
- As @lluiscanals you also need to check with Websockets - it's currently not working as far as I remember

So that's quite a lot of testing :-)
But an important upgrade!!!

**Comment by nkolosnjaji** [comment]
Spring Security 4.1 introduced [link to Google!](http://docs.spring.io/spring-security/site/docs/4.1.3.RELEASE/reference/htmlsingle/#csrf-cookie) which default to Angular naming conventions so I will first try with that.

Regarding testing, I will try to change user's password (i.e. POST on /account/change_password with payload "evil") to perform attack with disabled/enabled CSRF feature... I think this is evil enough :). I'm not sure where to commit sources for "evil.com" host (html + js which will perform attack on body load event).

**Comment by nkolosnjaji** [comment]
JHipster uses HttpSession to persist CSRF tokens, which doesn't scale horizontally easily.

Here are my findings about CookieCsrfTokenRepository

- easy integration, defaults are used on angular side and on java side.
- it uses client/browser (cookie) to persist value
- uses Reflection to set cookie without httpOnly flag

Also I did found out that jhipster apps generate **JSESSIONID** without **httpOnly** flag. Spring security does generate cookies with httpOnly but embeded tomcat doesn't allow this by default. I was able to override this behavior by adding SB property

server.session.cookie.http-only=true

Another thing is that I don't know use-case for **CustomAccessDeniedHandler** when it is necessary to set CSRF token to empty value. Can somebody clarify?

**Comment by xetys** [comment]
IMHO using springs default solutions is more comfortable with our policies, then providing custom solutions, so feel free to go ahead :smile:

**Comment by erikkemperman** [comment]
Hi, sorry to comment on closed thread -- but did anyone actually test this new CRSF stuff with websockets?

I have a fairly basic app, at least the websockets part, but it stopped working after I merged these changes. Specifically, it is complaining about "Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'".

Does that sound familiar?

**Comment by erikkemperman** [comment]
Apologies, never mind! I've found my problem (it was between the keyboard and the chair).
