### ISSUE TITLE
Documentation of profile selection contrary to spring boot suggestions

### ISSUE THREAD

**Issue by mbergumi** [jhipster/generator-jhipster#4273]
##### **Overview of the issue**

The documentation that describe the usage of the spring boot profiles suggests using -- parameters to specify profiles at launch.
https://jhipster.github.io/profiles/#spring-profiles-switches

That being said, Spring boot Documentation differs and suggest using a -D parameter:
http://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html#howto-set-active-spring-profiles

##### **Motivation for or Use Case**

N/A

##### **Reproduce the error**

N/A

##### **Related issues**

N/A

##### **Suggest a Fix**

N/A

##### **JHipster Version(s)**

N/A

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A

**Comment by jdubois** [comment]
It depends where you look at, for example it's documented at http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

I don't think it makes much difference in the end, I'd just rather use the "--" method as you can put them anywhere (the "-D" must be put before the JAR file, or it won't work), and I find it also easier to read.
