### ISSUE TITLE
Facebook social login can be registered but can't sign in

### ISSUE THREAD

**Issue by chegola** [jhipster/generator-jhipster#4276]
##### **Overview of the issue**
The issue is when sign in with Facebook social, the system works fine when Registration as you will get message "Registration saved! Please check your email for confirmation." But when you click Sign in with Facebook button,  you will get message "Registration failed! Please try again later." (try to login many times but still not work)

Since I am not sure whether this is jhipster's issue or Spring's social issue but I am able to reproduce the problem, please someone take a look and close if it is not related to jhipser.

##### **Motivation for or Use Case**
Web Application is required to sign in with Facebook, the system creates the user's information in table jhi_user and jhi_social_user_connection but unable to sign in with Facebook later.

However, this issue won't happen in my dev machine (localhost) but will happen on Heroku which I have been stuck here for a long while.

##### **Reproduce the error**
1. Generate jhipster as monolith
2. Supply Facebook App ID and secret ID in application.yml
3. When testing on localhost, set Facebook App Domain as **localhost** and Site Url as **http://localhost:8080**
4. System **able** to Register and Sign in with Facebook properly.
5. Deploy to Heroku
6. Change Facebook App Domain to **myjhi.herokuapp.com** and Site Url as **https://myjhi.herokuapp.com**
**Note**: I am still using the same Facebook app ID.
7. Try to Register with Facebook, it will show successful message.
8. Attempt to Sign in with Facebook but not successful.
9.  Here is the site I deployed [https://myjhi.herokuapp.com/#/](url)
10. Here is the source code on github https://github.com/chegola/myjhi

##### **JHipster Version(s)**
3.8.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
{
  "generator-jhipster": {
    "jhipsterVersion": "3.8.0",
    "baseName": "myjhi",
    "packageName": "com.myjhi",
    "packageFolder": "com/myjhi",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "bb166e25278dd7c4fe7284f971b263670a4dfd59",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
N/A

##### **Browsers and Operating System**
Windows 7 and Chrome

**Comment by jdubois** [comment]
If it works on localhost, it's going to be hard to test... There is obviously an environment issue in this case: could you configure your logback configuration to have debug logs for Spring Social, etc?

**Comment by chegola** [comment]
Ok, thank you, and here is log when for debug of Spring Social and Facebook. Seemed to me there is nothing wrong!!?? except Memory quota exceeded  is this cause of issue?

[spring-social.txt](https://github.com/jhipster/generator-jhipster/files/514927/spring-social.txt)

**Comment by jdubois** [comment]
I don't think you have your logs in DEBUG level for Spring Social and Spring Security here -> could you change that in your logback-spring.xml file? So we know what happens

**Comment by chegola** [comment]
Oh Ok, hopefully this is correct one. Note that I could not find Spring Social in logback-sprig.xml but Spring Security is there. Sorry to get back late as I was on travelling.

[spring-social.txt](https://github.com/jhipster/generator-jhipster/files/516340/spring-social.txt)

**Comment by chegola** [comment]
I 've tried a couple of experiments and seemed that this issue is not a bug as secure web https would need certificate and keys. Myself dont have much experience on this. If I just generate jhipster with statefull option and deploy on Heroku I ll get http and social works fine. So I ll close this and thank @jdubois for your reply.
