### ISSUE TITLE
VOLUME declaration in Dockerfile prevents downstream modifications to /home/jhipster/app

### ISSUE THREAD

**Issue by gotgenes** [jhipster/generator-jhipster#4277]
The Dockerfile in this project declares a `VOLUME` for `/home/jhipster/app`. The `VOLUME` declaration was likely intended provide data persistence beyond the life of a container, which is well-meaning. Unfortunately, this prevents downstream images that declare this image as the base (i.e., `FROM jhipster/jhipster`) from making modifications to `/home/jhipster/app` and any of its contents.

The negative effects of `VOLUME` on downstream images are discussed in docker/docker#3639. Note that this issue remains open with no solution in the foreseeable future.

In our particular use case, we wanted to create another volume mount under `/home/jhipster/app/ourdir`. The problem is that we could not create an image with an existing `/home/jhipster/app/ourdir`, because `/home/jhipster/app` is declared as `VOLUME` in this project's `Dockerfile`. When trying to mount `-v /home/jhipster/app/ourdir`, `/home/jhipster/app/ourdir` was mounted with owner and group of `root`. This is the default behavior for volumes when the path in the image does not exist.

**Comment by pascalgrimaud** [comment]
Hi @gotgenes

1) why not simply create your own folder+volume instead of using the a sub folder on the existing `/home/jhipster/app` ?

2) as I find it interesting, I tried my self. See the full log. I don't have any issue, with mounting volume. I just don't mkdir. Maybe I'm doing a different use case ?

```shell
╭─pgrimaud@pgrxps  ~/test  
╰─$ mkdir issue4277
╭─pgrimaud@pgrxps  ~/test  
╰─$ cd issue4277 
╭─pgrimaud@pgrxps  ~/test/issue4277  
╰─$ vim Dockerfile
╭─pgrimaud@pgrxps  ~/test/issue4277  
╰─$ cat Dockerfile 
FROM jhipster/jhipster:v3.6.1
VOLUME /home/jhipster/app/ourdir

╭─pgrimaud@pgrxps  ~/test/issue4277  
╰─$ mkdir ourdir
╭─pgrimaud@pgrxps  ~/test/issue4277  
╰─$ ls -al
total 16
drwxrwxr-x  3 pgrimaud pgrimaud 4096 oct.   7 08:08 .
drwxrwxr-x 15 pgrimaud pgrimaud 4096 oct.   7 08:07 ..
-rw-rw-r--  1 pgrimaud pgrimaud   64 oct.   7 08:08 Dockerfile
drwxrwxr-x  2 pgrimaud pgrimaud 4096 oct.   7 08:08 ourdir
╭─pgrimaud@pgrxps  ~/test/issue4277  
╰─$ docker build -t test:4277 .
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM jhipster/jhipster:v3.6.1
 ---> 7793ff7cb4de
Step 2 : VOLUME /home/jhipster/app/ourdir
 ---> Using cache
 ---> 40ffdcc05f84
Successfully built 40ffdcc05f84
╭─pgrimaud@pgrxps  ~/test/issue4277  
╰─$ docker run --name test4277 -d -P -v /home/pgrimaud/test/issue4277/ourdir:/home/jhipster/app/ourdir test:4277
419d0d19108dbd49f881c20ad57ed86116208bbf19400b36803c6b5f5694fc73
╭─pgrimaud@pgrxps  ~/test/issue4277  
╰─$ docker exec -it test4277 bash
jhipster@419d0d19108d:~/app$ ls -al                                                                  
total 12
drwxr-xr-x 3 jhipster jhipster 4096 Oct  7 06:10 .
drwxr-xr-x 6 jhipster jhipster 4096 Aug 18 14:30 ..
drwxrwxr-x 2 jhipster jhipster 4096 Oct  7 06:08 ourdir
jhipster@419d0d19108d:~/app$ cd ourdir/
jhipster@419d0d19108d:~/app/ourdir$ touch helloJHipster.txt
jhipster@419d0d19108d:~/app/ourdir$ ls -al
total 8
drwxrwxr-x 2 jhipster jhipster 4096 Oct  7 06:11 .
drwxr-xr-x 3 jhipster jhipster 4096 Oct  7 06:10 ..
-rw-r--r-- 1 jhipster jhipster    0 Oct  7 06:11 helloJHipster.txt
jhipster@419d0d19108d:~/app/ourdir$ exit
exit
╭─pgrimaud@pgrxps  ~/test/issue4277  
╰─$ ls -al ourdir 
total 8
drwxrwxr-x 2 pgrimaud pgrimaud 4096 oct.   7 08:11 .
drwxrwxr-x 3 pgrimaud pgrimaud 4096 oct.   7 08:08 ..
-rw-r--r-- 1 pgrimaud pgrimaud    0 oct.   7 08:11 helloJHipster.txt
╭─pgrimaud@pgrxps  ~/test/issue4277  
╰─$ 
```

**Comment by gotgenes** [comment]
@pascalgrimaud This is the `Dockerfile` to demonstrate the issue:

```
FROM jhipster/jhipster
RUN mkdir -p /home/jhipster/app/ourdir && chown jhipster:jhipster /home/jhipster/app/ourdir
```

```
$  docker build -t jhipourdir .
Sending build context to Docker daemon 14.85 kB
Step 1 : FROM jhipster/jhipster
 ---> 97dd7b0686d2
Step 2 : RUN mkdir -p /home/jhipster/app/ourdir && chown jhipster:jhipster /home/jhipster/app/ourdir
 ---> Running in d07834bd2e4e
 ---> f65fde55d347
Removing intermediate container d07834bd2e4e
Successfully built f65fde55d347
$ docker run --rm -v /home/jhipster/app/ourdir jhipourdir stat -c "%U %G" /home/jhipster/app/ourdir
root root
$ docker run --rm jhipourdir stat -c "%U %G" /home/jhipster/app/ourdir
stat: cannot stat '/home/jhipster/app/ourdir': No such file or directory
```

**Comment by pascalgrimaud** [comment]
It's because you didn't map to a local volume
Try:
```
$ mkdir ~/something
$ docker run --rm -v ~/something:/home/jhipster/app/ourdir jhipourdir stat -c "%U %G" /home/jhipster/app/ourdir
jhipster jhipster
```

Anyway, it's not a JHipster issue. All related to the use of Docker.
So I'm closing this.

**Comment by gotgenes** [comment]
> Anyway, it's not a JHipster issue. All related to the use of Docker.

It is a Docker issue in the sense that `VOLUME`:

1. should never have existed 
2. has no way to be overridden, at present

It is _also_ this project's issue because this project chooses to declare `VOLUME`, in the `Dockerfile`.

I strongly encourage this project's maintainers to visit docker/docker#3639. I have pasted some of the pertinent comments below:

>  [As soon as you mark a directory as a volume you have very few options to control its contents… I personally wish there was never a VOLUME directive for Dockerfiles, instead it should have always been inside the run syntax only.](https://github.com/docker/docker/issues/3639#issuecomment-144206271)

and

> [Basically, don't declare VOLUME unless you are done with that directory.](https://github.com/docker/docker/issues/3639#issuecomment-162872954)

and

> [When are you (or everyone who might ever start `FROM` your Dockerfile) ever _done_ with a directory? I was bitten by this trying to extend an official image.](https://github.com/docker/docker/issues/3639#issuecomment-164508990)

Docker's own maintainers admit that `VOLUME` is under-documented, and the repercussions non-obvious. As you can see by [this list](https://github.com/docker/docker/issues/3639#issuecomment-229490630) plenty of official projects, not just this one own, are under-informed of the repercussions. We can now consider this project informed.
