### ISSUE TITLE
Travis: increasing number of builds

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#4280]
Recently, we add new options : uaa, kafka, consul, etc...
These configurations are not covered by our Travis build.

Travis can do 5 builds in parallele. Currently, we have 13 builds / 15. So there is 2 slots available left.
I think we should increase the number to 20, that means:
- 7 new slots available, so we can test more options
- using more Travis ressource (which is Open Source)
- increasing the global time for the build

Are you ok with that?
If yes, I will begin to work on it.

**Comment by jdubois** [comment]
Yes, the more builds the better.
Most people don't work "full time" on JHipster: we just do one small task, and then go back to our "real" work. So if the build takes 2 hours it's not a big issue, as we switched to something else anyway. At least that's how I work :-)

**Comment by deepu105** [comment]
Ok, but do reserve one or two slots for ng2 so that we can add protractor
test for that

Thanks & regards,
Deepu
