### ISSUE TITLE
Ready to join the Mybatis and Hibernate switch it?  

### ISSUE THREAD

**Issue by An0nymous0** [jhipster/generator-jhipster#4284]
Ready to join the Mybatis and Hibernate switch it?

**Comment by pascalgrimaud** [comment]
You can read this ticket :
https://github.com/jhipster/generator-jhipster/issues/1252

I dont think it has changed. We wont support it.

**Comment by cbornet** [comment]
@An0nymous0 if you want, you can do a module for this.
