### ISSUE TITLE
Why not a one-to-many relationship？

### ISSUE THREAD

**Issue by clp334264003** [jhipster/generator-jhipster#4287]
##### **Overview of the issue**
Generating relationships to other entities

? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? User
? What is the name of the relationship? user
? What is the type of the relationship?
  many-to-one
> many-to-many
  one-to-one

**Comment by jdubois** [comment]
Not a bug, read the documentation...

**Comment by clp334264003** [comment]
where?

**Comment by deepu105** [comment]
https://jhipster.github.io/managing-relationships/


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Please, this is the bug tracker, not a place for questions.
