### ISSUE TITLE
Improvement of front-end websocket's architecture

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#4290]
##### **Overview of the issue**

With one service that uses websocket, all works. But usually an app has more subscriptions (divided by role, mutual or not). If a new service will be created, it will be duplicate code (connection, disconnection, subscription, unsubscription). I think it should be a main websocket service (websocket.service.js) and other services will be just inject it and subscribe whatever they want.
##### **Motivation for or Use Case**

No duplicate code and more flexible websocket architecture.
##### **Reproduce the error**

 Take a look at the [service in the example](https://github.com/jhipster/jhipster-sample-app-websocket/blob/master/src/main/webapp/app/admin/tracker/tracker.service.js) and imagine that you will have to create another subscription for not admin (for example, live blog).
##### **Suggest a Fix**

You can take a look at my websocket service at [Code Review](http://codereview.stackexchange.com/questions/143415/angular-websocket-factory) but it has an [issue](https://stackoverflow.com/questions/39918159/second-controller-receive-wont-work). 
##### **JHipster Version(s)**

All JHipster versions that supports websockets and older.

**Comment by jdubois** [comment]
Yes +1
What I don't understand with Websockets is that a lot of people select the option, but we have never any contribution or improvement

**Comment by deepu105** [comment]
Yes right and since ng1 code is frozen we will do it for ng2

**Comment by deepu105** [comment]
I have already refactored and moved the tracker service into the shared folder. we just need to make it generic. but can be done after initial migration.

**Comment by erikkemperman** [comment]
Found this issue looking for any JH users running into websocket reconnect problems. In particular, re-starting the server is more or less transparent to clients (no F5 required) because of persistent session management, but the websocket part doesn't reconnect, leaving the front-end half-functional and the users fully-confused.

Would it make sense to include something like that in the shared service? Unfortunately I won't be migrating our app to ng2 any time soon, so would have to backport or something.

**Comment by jdubois** [comment]
Yes we could have some re-connect solution here, just we need it both for ng1 and ng2, or just ng2. At least it can't be ng1-only.
Once again, the current "tracker" screen is just a helper to get started, I didn't code this with such advanced use-case, and I'm surprised we have so many people using it and nobody is ever contributing back! So yes it can definitely be improved, that's really clear for me.

**Comment by erikkemperman** [comment]
@jdubois Thanks for the quick reply! I guess it "just works" for most people, most of the time. I just noticed another possible issue which is the usage of stomp-websocket, which seems to be no longer maintained.

All right, I will have to make a quick-and-dirty fix in our app, but I will keep an eye on this issue and if I feel there's anything I can contribute I will jump in!

**Comment by jdubois** [comment]
No work here for more than 1 month, and I think it's stuck until we release Angular 2.

So I would like to close this, as we all agree this needs to be improved, but it won't be done in the immediate future.
