### ISSUE TITLE
jhipster:upgrade fails on the devbox

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#4296]
##### **Overview of the issue**

When upgrading a jhipster app on the devbox. The process fails and the app isn't upgraded

##### **Reproduce the error**

Download the 3.8.0 devbox or install manually with `sudo npm install -g generator-jhipster@3.8.0`
Generate an app (with `--skip-client` for quick generation)
Run `yo jhipster:upgrade`

##### **Suggest a Fix**

Several issues there:
1/ the default shell for the devbox is zsh and the command [rm -rf !(.yo-rc.json|.git)](https://github.com/jhipster/generator-jhipster/blob/master/generators/upgrade/index.js#L44) fails on this shell
2/ the global npm folder is `/usr/lib/modules` and needs root permissions for writing so the installation of the new version fails.

The workarounds are:
* change to bash shell before launching the upgrade (but most of the time, I forget and I lose a lot of time...)
* in the devbox, change ownership of /usr/lib/node_modules to vagrant (not sure it is secure)

Wouldn't it be better to install the new version locally ? I think there are a lot of reasons that could make the global install fail.

##### **JHipster Version(s)**

3.8.0/3.9.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.8.0",
    "baseName": "standard",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "47b4e760a1684605304b6a03d26cc6f2496a0914",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "serviceDiscoveryType": false,
    "skipClient": true
  }
}
```
##### **Browsers and Operating System**

Devbox : ubuntu 16 amd64

**Comment by cbornet** [comment]
Other interesting think to note : the ` shelljs.rm` doesn't remove hidden files and folders so the filter is actually useless. That's why the entities are regenerated even though the `.jhipster` folder is not part of the filter ...

**Comment by cbornet** [comment]
So shelljs.rm is not a true shell rm. It uses js functions to mimic the behavior but has less options.
I'm fixing this as part of #4294

**Comment by ashakhov** [comment]
BTW, there already was a [related issue](https://github.com/jhipster/generator-jhipster/issues/4033).

**Comment by jdubois** [comment]
Closing as #4306 is merged
