### ISSUE TITLE
Getting started guide for Jhipster 4, Angular-2 branch is ready. Can you add it to readme?

### ISSUE THREAD

**Issue by otabekgb** [jhipster/generator-jhipster#4299]
I wrote the guide at stackoverflow site. Can you include it on readme file until it's released? Someone might want check out that branch.
http://stackoverflow.com/questions/39919026/getting-started-guide-for-jhipster-4-latest-state/39948043#39948043

**Comment by deepu105** [comment]
Actually its the same process as using master branch for development. Anyway if it helps people to get started I'll be happy to write a small guide wiki

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/blob/angular-2/NG2-GUIDE.md

**Comment by deepu105** [comment]
Btw this would be removed once ng2 support is out of Beta
