### ISSUE TITLE
create entitry field is not null,but swagger say optional

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#4308]
i creating an entity e.g. `Blog`

jdl code like this
```
entity Blog {
   name String required
}
```

save as jhipster-jdl.jh

`yo jhipster:import-jdl jhipster.jh`

```java
@Entity
@Table(name = "blog")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Blog implements Serializable {
 private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Column(name = "name", nullable = false)
    private String name;

    //.....
}
```
but on the swagger(http://localhost:8080/#/docs  admin>API->choose Blog Resource->Model) ,it's optional, like this
![sp20161011_163202](https://cloud.githubusercontent.com/assets/15098916/19263721/4e283778-8fd0-11e6-87d4-cc96cd33877b.png)

i have to change Blog.java

```java
    //...

    @NotNull
    @ApiModelProperty(required=true)
    @Column(name = "name", nullable = false)
    private String name;
    //...
```

**Comment by cbornet** [comment]
Maybe we could include springfox-bean-validators

**Comment by anjia0532** [comment]
https://jhipster.github.io/jdl/#a-namecommentingjdla-commenting--javadoc support java-doc it's so cool,but something is wrong with the `yo jhipster:import-jdl`

jdl code like this
```
/**
 * blog demo
 */
entity Blog {
   /**
     * author's name
     */
   name String required
}
```

generator Blog.java like this

```java

/**
 * blog demo                                                                          //(about 70 space)
 * 
 */
@ApiModel(description = ""
    + "Class comments.@author The JHipster team.                              "
    + "")
@Entity
@Table(name = "blog")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Blog implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * deptartment's Code                                                      
     * 
     */
    @ApiModelProperty(value = ""
        + "deptartment's Code                                                 "
        + "")
    @NotNull
    @Column(name = "dept_id", nullable = false)
    private String deptId;
```

it has too many space and wrap to manual remove it

**Comment by cbornet** [comment]
Yes, that's another issue. Can you open a new one ?

**Comment by anjia0532** [comment]
@cbornet
ok,thanks ,i will open a new issus

**Comment by deepu105** [comment]
The new issue should be opened in jhipster-core project as the jdl parsing
is done there


Thanks & Regards,
Deepu

**Comment by cbornet** [comment]
@anjia0532 have you tried including springfox-bean-validators ? It might be a good idea to include it.

**Comment by deepu105** [comment]
@anjia0532 why did you close the issues?

**Comment by anjia0532** [comment]
@deepu105 sorry,i try to manul modify.


[domain/_Entity.java#L62](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/src/main/java/package/domain/_Entity.java#L60)

```java
   if (typeof fields[idx].javadoc != 'undefined') { _%>
<%- formatAsFieldJavadoc(fields[idx].javadoc) %>
    @ApiModelProperty(value = "<%- formatAsApiModelProperty(fields[idx].javadoc) %>")
    <%_ }
```

the @ApiModelProperty based on javadoc !=undefined ,it's not  @NotNull or  @Column(nullable=false)

**Comment by cbornet** [comment]
@anjia0532 I don't want to be insistant, but have you tried to add the [springfox-bean-validators](http://springfox.github.io/springfox/docs/current/#support-for-jsr-303) dependency to your pom.xml ?

**Comment by anjia0532** [comment]
@cbornet 
i create gateway app use `yo jhipster `  as default ,and pom.xml haven't [springfox-bean-validators 2.5.0 api](http://springfox.github.io/springfox/docs/2.5.0/#support-for-jsr-303) and i add the springfox-bean-validators dependency to pom.xml( gateway and micro app)
```xml
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-bean-validators</artifactId>
			<version>${springfox.version}</version>
		</dependency>
```
then 
Import the configuration from the springfox-bean-validators module( gateway and micro app)
```java
//For java config
@Import({springfox.bean.validators.configuration.BeanValidatorPluginsConfiguration.class})
```
then run both of them

open http://localhost:8080/#/docs and choose my micro app api docs

when i hover the field，shown `@size` annotation  max length,but `@notnull` and `nullable` is did't work,it's still optional

![spring-fox](https://cloud.githubusercontent.com/assets/15098916/19373254/30bb5414-91f5-11e6-8521-5a43f3ef99e8.png)
![spring-fox1](https://cloud.githubusercontent.com/assets/15098916/19373255/30be5560-91f5-11e6-916b-aa38ab29d9d5.png)

**Comment by jdubois** [comment]
- Concerning the 2nd issue you raise, it's closed and should be OK
- Concerning your first issue, I confirm it, and this is because Swagger doesn't understand the Bean validation annotations by default. I've also tried to add `springfox-bean-validators` and that doesn't work either -> for me this is a Springfox issue, not a JHipster issue. When Springfox corrects this bug, we can look at adding this new package to JHipster, as indeed it's providing some added value - but no guarantee, if this is an optional Springfox package there must be a reason (performance issue maybe?)

**Comment by cbornet** [comment]
I tried springfox-bean-validators and it's working perfectly well for me on 3.9.1 as long as I don't add javadoc on the field. If there is javadoc, the @ApiModelProperty( required=false)  takes the lead.

**Comment by cbornet** [comment]
Pics or didn't happen:

![swagger](https://cloud.githubusercontent.com/assets/11633333/19704686/e5502064-9b08-11e6-940c-688e5b64309a.png)

(myString is required)

**Comment by jdubois** [comment]
Great, happy to have this solved!

Le 25 oct. 2016 11:17 PM, "Christophe Bornet" <notifications@github.com> a
écrit :
