### ISSUE TITLE
entity sub-generator: invalid dependency between --regenerate and --table-name for entities with reserved words as names

### ISSUE THREAD

**Issue by HemanthD** [jhipster/generator-jhipster#4311]
##### **Overview of the issue**

The entity sub-gen allows for overridden table names using the --table-name option. The entity name (by default) or the overridden table name is validated for database specific reserved words. However, during --regenerate (during which the json file is directly used), the check becomes invalid/ redundant if the --table-name is not specified explicitly as the check will be performed, by default, against the entity name.

This issue manifests only where the entity name itself is a reserved word but --table-name is not specified explicitly even though the entity is only being regenerated.
##### **Motivation for or Use Case**
1. Since the --regenerate operates on an existing json file, validating the table name
   - (a) based on the entity name is incorrect
   - (b) may be redundant as the expectation is that the json file would be valid (in typical cases)
2. The 'upgrade' sub-gen invokes '--with-entities' which in turn results in invoking of entity sub-gen with --regenerate. If there are entities with reserved words as names, such apps cannot be upgraded as there is no way to explicitly specify --table-name during the process.
##### **Reproduce the error**

Case 1
- Create a typical monolith app
- Create an entity 'option' yo jhipster:entity option --table-name pa_option
- Try to regenerate this entity yo jhipster:entity option --regenerate
- It fails citing 'ERROR! The table name cannot contain a MYSQL reserved keyword' even though the valid overridden table name is present in the json

Case 2
- Consider upgrading such an app using yo jhipster:upgrade
- The upgrade aborts due to a similar error
##### **Related issues**

None
##### **Suggest a Fix**

We can, perhaps, skip the table name validation if --regenerate is specified and --table-name is not specified.

Refer **generator-jhipster\generators\entity\index.js** > _validateTableName (Line 159)_

Introduce the below code:

``` javascript
if (this.regenerate && this.options['table-name'] == undefined) {
    // if regenerating the entity, skip table-name validation if it is not explicitly specified in the options
    // as the overridden table-name may be available in the entity json file
    this.warning(`\nRegenerating entity ${this.name}, skipping table-name validation!\n`);
    return;
}
```
##### **JHipster Version(s)**

3.8.0
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

[.yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/521892/default.yo-rc.json.txt)
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

[Criteria.json.txt](https://github.com/jhipster/generator-jhipster/files/521900/Criteria.json.txt)
[Option.json.txt](https://github.com/jhipster/generator-jhipster/files/521899/Option.json.txt)
##### **Browsers and Operating System**

Windows 10 with MySQL 5.7.15 and Chrome

**Comment by deepu105** [comment]
The correct fix should be to check if table name exist in entity json and validate that when regenerating

**Comment by HemanthD** [comment]
Then, we may have to move the setupVars to immediately after getConfig and before the validate* functions, so that the entity json is loaded prior to the validation steps.
