### ISSUE TITLE
 generator-jhipster-react generator is not working

### ISSUE THREAD

**Issue by caritosteph** [jhipster/generator-jhipster#4312]
I got stuck when tried to create a project. It's show me a message "Would you like to enable this option? (Y/n)" and Y or n doesn't make any difference . Error message : there are no package.json or bower json file. 

npm WARN enoent ENOENT: no such file or directory, 
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.
bower ENOENT        No bower.json present

**Comment by cbornet** [comment]
generator-jhipster-react is a module for generator-jhipster.
You need to generate a jhipster app before

**Comment by deepu105** [comment]
If you have issues create it in the modules repo not here

**Comment by deepu105** [comment]
@cbornet for the react module jhipster app is not required as it creates the app itself
