### ISSUE TITLE
Move all translate directives to new jhi-translate

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#4313]
Related to https://github.com/jhipster/generator-jhipster/pull/4304
- [x] Migrate all the `translate` directives to `jhi-translate` **edit** will wait for https://github.com/ocombe/ng2-translate/pull/31
- [x] Migrate $translate service uses
- [x] remove angular-i18n dependency
- [x] Add `&quot;{{value}}&quot;` to values in `translate-values` **edit** will wait for https://github.com/ocombe/ng2-translate/pull/277
- [x] Fix the constant update logic
- [x] Fix issue when templates which needs compile (workaround #4429)

**Comment by gaurav20-07** [comment]
@deepu105 the commit of ng2-translate is not working. The contents of i18n folder are not getting loaded when the app is run.

**Comment by deepu105** [comment]
Try the latest angular2 branch. Generate an app with more than 1 language, make sure your npm install, bower install and gulp install finish successfully after that check. If you still see an issue give me more details like stack trace, any errors, your yo-rc.json etc
