### ISSUE TITLE
[Feature] Split entity sub generator into entity-client and entity-server and compose them

### ISSUE THREAD

**Issue by fmatuszewski** [jhipster/generator-jhipster#4319]
##### **Overview of the issue**

Divide jhipster generator into frontend and backend generators that work together.
Make it easy to compose (plugin) different frontend generators with backend.

Right now there is client, and entity module.
client module contains only frontend code but
entity module contains both Java and frontend.
It would be great to split entity module and separate it into different repository.
 

##### **Motivation for or Use Case**

Keep angular 1.4 in future releases.
Make it possible to choose from different front end libraries.
Add React, Native Script, Angular + Angular Material (instead of bootstrap) front end implementations.
Maintain front end code in separate git repository
Make it easy to plug in new frontend technologies.
Make it easy to migrate to different front end libraries.

**Comment by deepu105** [comment]
its not that easy to actually do as it will require tremendous effort to maintain. we will be supporting ng1 and ng2 soon, there is separate work going on for generator-jhipster-react.
So we already have client and server that means you can write a genrator to compose what is required and provide your own implementation of client or server, that is what I did for jhipster-react.

So the only part left here is splitting the entity sub gen to client and server and yes thats something I had in mind and will be doing it as part of the angular migration. Hence I'm gonna rename the issue accordingly.

We wont be moving stuff to different repos any time soon and I dont think thats required

**Comment by fmatuszewski** [comment]
It is not required for me to move various client implementations to other repository, but for me as a developer it would be nice to have easy way to plug in  different frontend module that is not a part of main repository. That could be in the future added to main repository easily.

**Comment by fmatuszewski** [comment]
I would like to contribute. I will need some help to start.

**Comment by fmatuszewski** [comment]
I would like to migrate angular 1 to 1.5 and use components architecture and maybe migrate to webpack.
I have also knowledge of angular material and already migrated jhipster generated application to webpack angular material and components architecture and wrap everything up as Cordova application, but I don't have experience in writing generators.

**Comment by deepu105** [comment]
@fmatuszewski we are already on angular 1.5, we have few components as well and frankly our current concentration is on ng2 hence we have frozen ng1 code for now. we will only do high priority fixes and stuff on that. If you want to help you can help with our ng2 migration here #3664 

Generators are easy. we use yeoman so check their documentation to get started. Its all JavaScript and ejs templates. Just look at our source

**Comment by fmatuszewski** [comment]
I think about differents options how to divide this modules
1st option
- /client
  - index.js - keep only prompts 
  - prompts.js
  - /angular-1
    - /templates - move all templates for angular 1
    - index.js - move all generation code for angular 1
  - /angular-2
    - /templates
    - index.js
- /entity
  - index.js
  - prompts.js
  - /entity-server
  - /entity-client
    - /angular-1
      - /templates
      - index.js
    - /angular-2
      - /templates
      - index.js

**Comment by fmatuszewski** [comment]
2nd options cleaner simpler
- /client
  - /angular-1
    - /templates
    - index.js
  - /angular-2
    - /templates
    - index.js
- /entity
  - /entity-server
  - /entity-client-angular-1
  - /entity-client-angular-2

**Comment by deepu105** [comment]
@fmatuszewski this is not how yeoman works. Thats why we have sub generators. Look at the angular2 branch you will find client and client-2 similarly when i split entity it will be entity-client, entity-client-2 and entity-server sub generators the structure will be flat and not nested.

But this for the time being. I will be revisiting the naming before the actual beta release and might change to more meaningful names.

**Comment by jdubois** [comment]
I'm sorry but we just can't do it now... Our AngularJS 2 migration is taking far too long, we have tons of bugs opened. We can't refactor our code at the same time.
But yes the entity sub-generator should be split for AngularJS / AngularJS 2 support, but we will do this after the main generator has a correct AngularJS 2 support.
