### ISSUE TITLE
[Feature] Migrate  generator to ES6

### ISSUE THREAD

**Issue by fmatuszewski** [jhipster/generator-jhipster#4321]
##### **Overview of the issue**

Migrate generators to ES6
http://mammal.io/articles/yeoman-generators-es6/

##### **Motivation for or Use Case**

Ease of development.
Consistency

**Comment by jdubois** [comment]
I'm sorry but we can't do everything -> the current priority is the AngularJS 2 migration, and we have tons of bugs waiting, so we can't do such a change at the moment.
But yes I agree it should be done in the long term.

**Comment by deepu105** [comment]
@fmatuszewski I can understand your enthusiasm, but please I would suggest you take a look at the source and study it before proposing changes, enchancements to the core. We are already using es6 as its a node project. Its just that most of us are comfortable witj current code and we use es6 features only when necessary
