### ISSUE TITLE
Spring Boot repackage generating incorrect WAR file

### ISSUE THREAD

**Issue by parmarsanjay** [jhipster/generator-jhipster#4326]
##### **Overview of the issue**

Spring Gradle Boot Repackage generates incorrect WAR file. When I deploy this file to AWS Elastic Beanstalk, it doesn't work. It complains with following information.

[build/libs/Project-0.0.1-SNAPSHOT.war]:  6972 extra bytes at beginning or within zipfile

When I try to use jar -xvf .WAR file, it doesn't do anything. It doesn't extract the file. 

##### **Motivation for or Use Case**

Can't deploy generated war file to AWS Beanstalk. 

##### **JHipster Version(s)**

Using Latest JHipster version 3.9.1.

**Comment by atomfrede** [comment]
Can you post your complete ``.yo-rc.json`` content? Which OS are you using?

**Comment by gmarziou** [comment]
> [build/libs/Project-0.0.1-SNAPSHOT.war]: 6972 extra bytes at beginning or within zipfile

Looks like the shell script that [Spring Boot adds to the executable jar](http://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-install).
If you don't need an executable jar because you deploy in a servlet container, you can set execitable to false.

~~~
springBoot {
    executable = false
}
~~~

**Comment by atomfrede** [comment]
@parmarsanjay Are you generating a *jar* or a *war*? By default jhipster only generates two *war* files. One executable an the one named ``jhipster-0.0.1-SNAPSHOT.war.original`` for example. The ``.war`` ending with ``original`` is supposed to be deployed in an application/sevlet container. have you tried this? All in all this doesn't look like a jhipster issue to me in fact.

**Comment by parmarsanjay** [comment]
I am using Mac OS. Here's the content of .yo-rc.json.

{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "testjhip",
    "packageName": "com.testjhip",
    "packageFolder": "com/testjhip",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache

": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "71a23836ba2973d3f0e656e2127b45fe76a465b2",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn",
      "zh-tw"
    ],
    "messageBroker": false,
    "serviceDiscoveryType": false
  }
}

**Comment by parmarsanjay** [comment]
Changing executable = false fixed the issue for me.

springBoot {
    executable = false
}

@atomfrede I was just generating WAR file. Whatever comes default in jhipster gradle config. Thanks for the info .original.

**Comment by alexee** [comment]
Does not look as a solution for me, what if I need jar to be executable?

**Comment by gmarziou** [comment]
@alexee, please don't comment an old closed issue. Open a new one with all required details.
