### ISSUE TITLE
 Couldn't connect to host, port: smtp.mail.yahoo.com, 587;  ?

### ISSUE THREAD

**Issue by clp334264003** [jhipster/generator-jhipster#4329]
##### **Overview of the issue**

mail:
        host: smtp.mail.yahoo.com
        port: 587
        username: ipnaasp@yahoo.com
        password: ....
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.mail.yahoo.com

2016-10-13 23:32:41.383  WARN 5076 --- [aasp-Executor-2] com.qm.ipnaasp.service.MailService       : E-mail could not be sent to user '334264003@qq.com'

org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.mail.yahoo.com, 587; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection timed out: connect. Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.mail.yahoo.com, 587; timeout -1;

**Comment by cbornet** [comment]
Please fill the issue properly
