### ISSUE TITLE
Advanced customisation missing instructions

### ISSUE THREAD

**Issue by octavioamu** [jhipster/generator-jhipster#4331]
I had been playing a lot with the bootstrap [advanced customisation](https://jhipster.github.io/customizing-bootstrap/#advanced-customisation) trying to avoid bootstrap to be injected two times because looks like '!/bootstrap-sass/assets/stylesheets/' in gulp is beeing ignored.

After a lot of try I had commented the overrides in bower.json so no files in main file will be injected, but don't find this one a good solution. Has anyone faced the same issue?

```

"bootstrap-sass": {
      "main": [
        // "assets/stylesheets/_bootstrap.scss"
      ]
    }
```

```

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "vulpi",
    "packageName": "com.vulpi.app",
    "packageFolder": "com/vulpi/app",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "08689654f3721a37000a479aef8f9c3d9ea16353",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br",
      "en"
    ]
  }
}
```

**Comment by jdubois** [comment]
All I know is that at the beginning of the doc it says `you must exclude the standard Bootstrap SASS files from the inject task`, but I'm not using it and I have no feedback.
I'm not sure this is a bug, and no one as answered you here -> could you try using StackOverflow with the `jhipster` tag?

**Comment by octavioamu** [comment]
I had followed the instructions, changed the inject task like the instructions, the problem is the instructions are incomplete, If you don't comment that override in the bower.json the bootstrap is going to be added two times , one in the inject and the other in the custom bootstrap.

**Comment by deepu105** [comment]
Would you consider doing a PR to correct the docs?

Thanks & regards,
Deepu

**Comment by octavioamu** [comment]
Yes, I will upgrade my version of jhipster in my project and make the corrects tests. I want to take a look deeper to the css/sass tasks because in my browser is reloading all the page each time I change something and also I had to save main.scss to any _custom-file.scss take effect.

**Comment by octavioamu** [comment]
I had made a pr #4366  about the problem with imports in main.scss will fix part of the problem the others is in the docs, but I will se if I find some better solution than remove a line in bower
