### ISSUE TITLE
@Cache doesn't work for generated JpaRepository's methods

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#4332]
##### **Overview of the issue**

I noticed, that `userRepository.findOneById(long id)` doesn't cache returned user (I enabled hibernate.show_sql and spammed "/api/account"). However, `userRepository.findOne(long id)` works.

##### **Motivation for or Use Case**

Cache annotations becoming useless.

##### **Related issues**

This applies to all methods from JpaRepository, that is `generated` (`findOneById`, `findOneByLogin`, `findOneByEmail` and so on).

##### **Suggest a Fix**

Create wrappers in services:

```java 
@Transactional(readOnly = true)
public Optional<User> getUserById(long id) {
    return Optional.ofNullable(userRepository.findOne(id)).map(user -> {
        user.getAuthorities().size();
        return user;
    });
}
```

P.S. This solution doesn't fix searching by params except an id and I didn't test it with lazy collections.

##### **JHipster Version(s)**

All versions with '2nd level cache' option.

**Comment by jdubois** [comment]
Good catch!!!
Thanks for reviewing the cache!

- for all methods like `findOneByLogin` or `findOneByEmail` this is normal, as the 2nd level cache only works on the PK. We are not using the query cache (we can also talk about this one, but I think the query cache is very often a bad idea, so we shouldn't have it by default)
- for the `findById` that's a real issue. I confirm what you found, and this should be cached. What's strange is that if you use `org.springframework.data.repository.Repository` you could have something similar working, but not with `org.springframework.data.repository.JpaRepository`.... And of course we need to use the `JpaRepository` to have access to the paging and sorting, which we use extensively. This looks like a bad design in Spring Data JPA to me, at least I don't understand why it doesn't work.
I'm going to solve it by using the `findOne()` method and then wrapping it in an Optional. I'm not a big fan, but this is only used once in the code, and again I think this is an issue with Spring Data JPA

**Comment by delverdev** [comment]
I would also suggest to replace `getCurrentUserLogin` to `getCurrentUserId` so it will hit the cache more. Maybe it's a bit dirty solution, but I pass `String.valueOf(id);`  instead `login` in `UserDetailsService``s first param.

**Comment by jdubois** [comment]
Oh, that looks good for performance, even if it's indeed some kind of a hack. I tried it, but I have several cases where it doesn't work, for example with the social login.
So I'm not sure that we can do this everywhere - but maybe it could be helpful to remove some requests.
