### ISSUE TITLE
Improvement for Cache

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#4333]
##### **Overview of the issue**

1. CacheConfiguration isn't flexible. It has strange code that uses entity manager and also doesn't allow to use `region` param on `@Cache` annotation.
2. I cannot understand [this line](https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/java/io/github/jhipster/sample/config/CacheConfiguration.java#L74). What if I need `timeToLiveSeconds = 5` instead `3600`? With that line even param `timeToLiveSeconds` in `ehcache.xml` is useless. I suggest to remove it and define default params in `<defaultCache/>` (It must be deleted in `Properties.java` too).
3. In `/management/metrics`, cache's `mean-get-time` and `mean-search-time` is `NaN`.<br>
**UPDATE:**
As I understood, demo application has older version. However, I have version ~3.6.0 and if I direct go to `/management/metrics`, it always returns NaN, but on the loaded page all works (magic). But it also shows numbers from 50,000 to 1,000,000, so I think it's microseconds, not ms.
4. `@Cache` on collections doesn't seem to work (at least in [your demo app](http://jhipster-demo.herokuapp.com/#/metrics)). In my application (I use "region"), I have all collections in `Ehcache statistics` table. If it really doesn't work and it will be fixed, it may be _collisions_ at the metrics page. For example:
_io.jhipster.domain.Topic.links_ and _io.jhipster.domain.Comment.links_ will be shown as _links_ and _links_ in `Ehcache statistics` table. That's one more motivation to use regions with `-` or `_` delimeter (for ex., `topic-links` and `comment-links`).

##### **Motivation for or Use Case**

Some developers would like to use region instead classpath: it's more flexible (I have to change path in ehcache.xml each time I move file to another directory or rename it). Another motivation is less code in the configation.

##### **Suggest a Fix**

I suggest next code for CacheConfiguration::cacheManager:

```java
@Bean
public CacheManager cacheManager(Properties properties) {
    log.debug("Starting Ehcache");
    cacheManager = net.sf.ehcache.CacheManager.create();      
    cacheManager.getConfiguration().setMaxBytesLocalHeap(properties.getCache().getEhcache().getMaxBytesLocalHeap());
    log.debug("Registering Ehcache Metrics gauges");
    Stream.of(cacheManager.getCacheNames()).forEach(name -> {
        net.sf.ehcache.Cache cache = cacheManager.getCache(name);
        cacheManager.replaceCacheWithDecoratedCache(cache, InstrumentedEhcache.instrument(metricRegistry, cache));
    });
    EhCacheCacheManager ehCacheManager = new EhCacheCacheManager();
    ehCacheManager.setCacheManager(cacheManager);
    return ehCacheManager;
} 
```

And also remove entity manager.
With this configuration, you may use `region` or not.

**Comment by jdubois** [comment]
Thanks a lot. Lots of points here, to answer you shortly: this is code I wrote at the very beginning of JHipster, and I think you're the first one to provide feedback on it.
Many things have changed this that time, and I think we should use most of what you provide. I'm going to work on integrating this now.

**Comment by mraible** [comment]
On a related note, when I integrated Stormpath into JHipster, it expected cache's to be auto-created. With the default Spring Cache implementation, this works. With JHipster's EhCache configuration, it does not. https://github.com/stormpath/stormpath-sdk-java/issues/1024

**Comment by jdubois** [comment]
@delverdev I'm taking most of your code and include it in JHipster. I'm only extracting some stuff for Hazelcast.
For your point 3 (the `mean-get-time`) I have the same issue: I'm just going to remove this column, as I can't get it to work. It's not very important, and we are in the process of migrating to ehcache3, so this will probably totally change very soon.
