### ISSUE TITLE
[FEATURE] jhipster:entity - Support grouping of entities into 'modules'

### ISSUE THREAD

**Issue by HemanthD** [jhipster/generator-jhipster#4339]
##### **Overview of the issue**

Support a sub-package/module name for entities which can be used to group entities and their back-end/front-end code.

##### **Motivation for or Use Case**

When the monolith app has many entities, it'd be helpful to be able to group them into logical 'modules'. This will also help in being able to reuse the same name for similar entities in different modules.

The request is not change the package structure itself, but to be able to support an additional leaf-level package such as domain._module1_.entity1.java, web.rest._module2_.entityResource.java, _added_entity_module4_Entity4.xml, app/entities/_module3_/*.js etc.

The --table-name, in some ways, support the database table 'grouping' by being able to provide an overridden table name with specific prefixes.

##### **Reproduce the error**

NA

##### **Related issues**

Similar requests have not been reported - but there have been feature requests for changing the package structure #4125, #3496 etc.

##### **Suggest a Fix**

An optional parameter --module-name can be accepted during jhipster:entity which will redirect/read the json from .jhipster/_module_/entity.json and will also store the module-name within the json. This can be used as a suffix to suitably modify the package name in the templates.

##### **JHipster Version(s)**

3.8.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

NA

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

NA

##### **Browsers and Operating System**

Windows 10 with MySQL 5.7.15 and Chrome

**Comment by gmarziou** [comment]
> This will also help in being able to reuse the same name for similar entities in different modules.

That would be a code smell for me.

What about the REST routes?

**Comment by HemanthD** [comment]
The resourceUrls could be changed from the existing /api/entities to /api/module/entities.
The state names could have the module as a prefix such as module-entity, module-entity.new etc.

Of course, this is just a suggestion and perhaps can be implemented as BETA with a few limitations (handling entity relationships across modules esp. if they have the same name etc.) to see if it gets too complicated to manage.

**Comment by jdubois** [comment]
My original idea was that we just generate CRUD screens, and if you have more complex business needs you're going to refactor the code. Moving a package with an IDE is much easier (for relationships for example) than generating it in another place with JHipster.
Then that's just the original idea, things have changed a lot since that time, but still I think this is going to add more questions and more complexity.

**Comment by deepu105** [comment]
Yes I dont see much need for such usecase. It could be easily done in the
IDE we cant cover every use case out there.


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
OK, closing it then...

**Comment by HemanthD** [comment]
The problem with doing it via the IDE is the upgrades etc. cannot be easily handled. We will have manually reconcile the changes. Perhaps the most complex item with this requirement would be supporting same names across modules - but this can be restricted. If we restrict that we need have unique entities across the module, the implementation could become simpler.
