### ISSUE TITLE
service discovery doesn't work with ACL

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#4345]
##### **Overview of the issue**

When applications start and register themselves with consul using ACL, they get registered successfully, but never listed in service discovery, which makes all features based on this to fail, as zuul, ribbon, feign etc...

##### **Motivation for or Use Case**

move consul forward to be a possible full replacement for eureka, with security enabled (in this case, ACL(
##### **Reproduce the error**

Just try to use consul with the latest release

##### **Related issues**

The issue is not at JHipster, but https://github.com/spring-cloud/spring-cloud-consul/issues/201

##### **Suggest a Fix**

wait until https://github.com/spring-cloud/spring-cloud-consul/pull/233 is merged, a new version of cloud consul is released, and use the new version here

##### **JHipster Version(s)**

 3.9.1

**Comment by PierreBesson** [comment]
Good job @xetys of fixing this upstream ! Spring Cloud just released their Camdem.SR1 but hopefully we can have this fixed in just a matter of weeks.

**Comment by PierreBesson** [comment]
Shouldn't we rollback to the previous config-loader without all then. As this one is broken !! ?

**Comment by xetys** [comment]
I am not sure, this would mean insecure service discovery...if someone will use this in production, everyone who is familiar with consuls API can look at the services registered, and register own ones etc...

if you think we should rollback this, then only the loader (just use the last working previous version of loader), which doesn't perform ACL setup....

for my personal taste I am ok with using the JHipster Registry until all consul problems are resolved....there are more than just ACL ;)

**Comment by PierreBesson** [comment]
You are right, if people want to use consul now they must know what they are doing and it will be fine.

**Comment by jdubois** [comment]
Looks like they are not ready to merge this, and I don't like long-running tickets...
For me we'd better rollback on ACLs, and this will be unsecured, like normal Eureka (people forget about it, but one of the enhancements of JHipster Registry is that it adds HTTP Basic autenth on top of Eureka)

**Comment by xetys** [comment]
@jdubois you think we should do it similar in consul, too? like just setting some reverse proxy with http basic auth is not that hard to do...while this is hanging

**Comment by PierreBesson** [comment]
@jdubois I'm OK to remove the ACL for now. For the reverse proxy, I don't feel like it's our job to do it.

**Comment by jdubois** [comment]
@PierreBesson anyway we can't stay with something broken, with the hope that the Spring team will one day do something about this.
Could you revert the change, and close the ticket?

**Comment by PierreBesson** [comment]
Ok I will do it.
