### ISSUE TITLE
[FEATURE] Add SpringBoot cloud connectors starter

### ISSUE THREAD

**Issue by nkolosnjaji** [jhipster/generator-jhipster#4346]
##### **Overview of the issue**

Add SpringBoot cloud connectors starter
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-cloud-connectors/1.4.1.RELEASE

##### **Motivation for or Use Case**

It will reduce dependencies in pom.

##### **Suggest a Fix**

I can create a PR.

##### **JHipster Version(s)**

version 3.9.1

**Comment by jdubois** [comment]
I'm not sure of what this does, but if it reduces the number of dependencies it would be good. Be careful, you also need to do it for Gradle.

**Comment by cbornet** [comment]
It bundles
```xml
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-spring-service-connector</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-cloudfoundry-connector</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-heroku-connector</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-localconfig-connector</artifactId>
		</dependency>
	</dependencies>
```

**Comment by jdubois** [comment]
If it bundles the same dependencies, but with just 1 import, let's do this!
(and don't forget Gradle!)

**Comment by jdubois** [comment]
@nkolosnjaji we let you do the PR?

**Comment by nkolosnjaji** [comment]
yes, please, it will be ready soon

**Comment by nkolosnjaji** [comment]
this can be closed now PR was merged, but I didn't put correct **FIX** footer commit message
