### ISSUE TITLE
Pagination is causing issues when changing the number of items per page

### ISSUE THREAD

**Issue by heppa** [jhipster/generator-jhipster#4347]
##### **Overview of the issue**

When using pagination as pagination ("pagination":"pagination") and changing the items per page, the bootstrap paginations are not correct.

##### **Motivation for or Use Case**

I wanted to change the items per page when using pagination, as the page became too big for most user's screens and they had to scroll and click on each page...

##### **Reproduce the error**

1. create an application with "pagination" for at least one entity (bootstrap pagination).
2. in {entity-name}.controller.js change the line `vm.itemsPerPage = paginationConstants.itemsPerPage;` to eg. `vm.itemsPerPage = 15;`
3. generate enough simple test-data so that you can test pagination.
4. in a browser, open the the entity list, 
5. navigate to the last page. It does not really jump to the last page (still using 20 for the calculation of the links).

##### **Related issues**

Could not find any.

##### **Suggest a Fix**

you could add `items-per-page="vm.itemsPerPage"` to the uib-pagination element. This should fix the problem.

##### **JHipster Version(s)**

I have upgraded to be using 3.9.1. Not sure, which versions already had the problem.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "fertigungsplaner",
    "packageName": "<removed>",
    "packageFolder": "<removed>",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "<removed>",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en"
    ],
    "messageBroker": false,
    "serviceDiscoveryType": false
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
```

{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "originalNr",
            "fieldType": "Long"
        },
        ... // stripped as not really relevant
    ],
    "changelogDate": "20161013140301",
    "entityTableName": "manufacture_task",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl",
    "searchEngine": "elasticsearch"
}

```
##### **Browsers and Operating System**

The Problem occurs in chrome and firefox and OS should not be relevant, as it's a calculation issue in the pagination.

EDIT: Thanks! ;)

**Comment by jdubois** [comment]
Good catch!!! I confirm the issue

**Comment by heppa** [comment]
btw: when changing the value in pagination.constant.js, it works correctly, but this changes it for all entities. It would be nice to be able to change this for one view only.
