### ISSUE TITLE
url params not manteined when returned from entity detail view [Feature]

### ISSUE THREAD

**Issue by lluiscanals** [jhipster/generator-jhipster#4350]
##### **Overview of the issue**

When enter entity detail view from entity view with params in url (ordering, search or page), when returning back those params are not mantained.

##### **Motivation for or Use Case**

   Maintain last state of entity page. E.g. if you were on the third page with an order criteria and enter in a detail view and go back to entity list, you expect to return to that page with that order.

##### **Reproduce the error**
n/a

##### **Suggest a Fix**

In _entity-management-detail.controller.js
```javascript
vm.goBack = goBack;

function goBack() {
  $state.go(previousState.name, previousState.params)
}
```
In _entity-management-detail.html
```html
<button type="submit"
            ng-click="vm.goBack()"
            class="btn btn-info">
        <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;<span data-translate="entity.action.back"> Back</span>
    </button>
```

Also in user-management, etc... generated files.

I can provide al PR if this solution is ok for you.

##### **JHipster Version(s)**
3.9.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "jhipster",
    "packageName": "com.dualion.jhipster",
    "packageFolder": "com/dualion/jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ca"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
n/a

##### **Browsers and Operating System**
n/a

**Comment by ruddell** [comment]
Related to #4188 

The problem with the proposed solution is when you go from one entity-detail to another entity-detail (relationship), the back button goes between them those entity-detail instead of back in history.

**Comment by lluiscanals** [comment]
Ok, didnt try that case. So as said in related issue and because ng1 develoment is frozen I think that this can be closed and we will see in ng2 which is the behavior and we can discuss there. What do you think?

**Comment by deepu105** [comment]
yes lets revisit for ng2
