### ISSUE TITLE
Suggestions on Generating Large Numbers of Entities

### ISSUE THREAD

**Issue by somewhereMrli** [jhipster/generator-jhipster#4358]
Why not generate code from the database, so as long as the tools to support the generation of the database can be easily used, and now this is generated from the xml code is not suitable for complex engineering code migration.

**Comment by deepu105** [comment]
If you have a feature request please provide use case with proper explanation and solutions if any.

Please follow our [guidelines ](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#issue) when opening issues if you want us to help you.
For bug reports please follow the template pre populated [here](https://github.com/jhipster/generator-jhipster/issues/new)
Open a new issue with proper details or update this issue with all details and request to re open.
Issues opened without proper details will be closed without explanation.
