### ISSUE TITLE
Use HTML5 pushState

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4362]
We currently use a hash in our URL to handle our routing.

I'm currently working for a customer who wants to have his application crawled by Google, with (obviously) a good SEO.

- Using HTML 5 pushState removes the hash -> makes the URL a bit nicer, but until today I haven't found a better usage for that
- This can be used by the Google crawler to index the page correctly -> if you have the hash, Google will only "see" the root page of your application, and will not follow what is after the hash. Looks like with HTML pushState, the whole link will be followed, which would allow the whole application to be crawled.

I'm going to do some tests on this:

- I might test it on our documentation website, as it's already fully configured with Google Webmaster tools (if I do some test commits, I will link them to this issue)
- If this works well, I'll update the current generator -> this will need to be modified also for AngularJS 2, so I'm cc:'ing @deepu105 @wmarques @flaviencathala

If you have any comments or insights on AngularJS + SEO optimization, I'll be happy to read them!

**Comment by deepu105** [comment]
we already discussed this in https://github.com/jhipster/generator-jhipster/issues/2965

Also we had below requests for the same as well

https://github.com/jhipster/generator-jhipster/issues/1297
https://github.com/jhipster/generator-jhipster/issues/374

This is definetely good for SEO but bit tricky to do on NG1 but easier on NG2. For NG2 im gonna add a step to do this as default

**Comment by jdubois** [comment]
Oh sorry, I did a search on "pushState" and didn't see those...
I'm really tired, as [this comment](https://github.com/jhipster/generator-jhipster/issues/1297#issuecomment-89344900) perfectly summarize everything, and I wrote it myself :-)
OK let's not do this in JHipster (but I'll do it for my client, of course)

**Comment by gmarziou** [comment]
I really doubt this is easy with current URL scheme, especially for a gateway because we use service names as URL prefixes of our routes, this was [my point on dev list.](https://groups.google.com/forum/#!msg/jhipster-dev/1RtCU3qt3Tk/ShiBOgI5BQAJ;context-place=forum/jhipster-dev).

So either we add complexity in a zuul or servlet filter by plugging it to service registry at the risk of introducing URL conflicts between client and server or we introduce breaking changes in the gateway routes.
