### ISSUE TITLE
Tests generated for ZonedDateTime entity attributes are failing

### ISSUE THREAD

**Issue by mmaia** [jhipster/generator-jhipster#4373]
##### **Overview of the issue**

Tests generated for ZonedDateTime entity attributes are failing, basically the generated tests are using ZoneId.systemDefault() which causes the test to fail.

The fix is to use UTC instead as discussed here: http://stackoverflow.com/questions/40191004/integration-tests-with-zoneddatetime-using-spring-boot-1-4-error

So this is how it's generated: 

``` java
private static final ZonedDateTime DEFAULT_DATE = ZonedDateTime.ofInstant(Instant.ofEpochMilli(0L), ZoneId.systemDefault());
private static final String DEFAULT_DATE_STR = DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(DEFAULT_DATE);
```

and this is the fix: 

``` java
private static final ZonedDateTime DEFAULT_DATE = ZonedDateTime.ofInstant(Instant.ofEpochMilli(0L), ZoneOffset.UTC);
private static final String DEFAULT_DATE_STR = DateTimeFormatter.ISO_INSTANT.format(DEFAULT_DATE);
```
##### **Motivation for or Use Case**

When generating a new entity and creating an attribute as a ZonedDateTime the integration tests fail. 
##### **Reproduce the error**

Create a new jhipster project. 
Create a new entity using `yo jhipster:entity MyEntity`
Add a property of type ZonedDateTime to your entity
Run generated tests for this entity

Tests will fail with an error like: 

```
java.lang.AssertionError: JSON path "$.[*].date"
Expected: a collection containing "1970-01-01T01:00:00+01:00"
 but: was "1970-01-01T00:00:00.000Z"
```

I've extensively tested that generating 3 projects and always had the same issue.
##### **Related issues**

issue #815 was a similar one: 
https://github.com/jhipster/generator-jhipster/issues/815
##### **Suggest a Fix**

The fix that worked for me is to stop using system default zone and use UTC instead, issue and solution properly described here: 

http://stackoverflow.com/questions/40191004/integration-tests-with-zoneddatetime-using-spring-boot-1-4-error
##### **JHipster Version(s)**

JHipster Generator v3.9.1
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

``` json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "zonedDateTime",
    "packageName": "com.mmaia.jhipster",
    "packageFolder": "com/mmaia/jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "cb6b76d9c4f0de727e19d364e0886bd5b23d2e36",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

``` json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "birthDate",
            "fieldType": "ZonedDateTime"
        }
    ],
    "changelogDate": "20161024120111",
    "dto": "no",
    "service": "no",
    "entityTableName": "my_entity",
    "pagination": "no"
}
```
##### **Browsers and Operating System**

Integration test problem. Tested in a Fedora 23 O.S using java 8

**Comment by cbornet** [comment]
What does the tests give if you use ehCache ?

**Comment by mmaia** [comment]
Hi @cbornet - I just created a project picking EHCache and I have exactly the same error when running the tests.

**Comment by cbornet** [comment]
OK. So this is when you use ElasticSearch with failure on the search endpoint test.
* it's true that it is not wise to use the system TZ in tests. We should set it to a fixed TZ. The easiest is probably UTC as it would be the same jsonpath string to compare between elasticsearch's test and other tests. 
* we should also probably set the CI servers TZ to something else than UTC to detect this kind of issue

**Comment by pascalgrimaud** [comment]
I confirm this issue in my local.

But using Travis, I didn't manage to reproduce
I tried to change the timezone but it doesn't change anything, all tests are ok:
```yaml
before_install:
    - export TZ=Australia/Canberra
    - date
```

**Comment by cbornet** [comment]
We have a test with both ES and ZonedDateTime so that's strange...

**Comment by jdubois** [comment]
I confirm the issue, and the fix by @mmaia works for me.
