### ISSUE TITLE
Changing a property type of an entity

### ISSUE THREAD

**Issue by boubou158** [jhipster/generator-jhipster#4380]
##### **Overview of the issue**

Hello,

I'm trying to understand how liquibase and entity works with Jhipster because I will need to be able to make a lots of changes in my entities when the project will grow up. I really can't figure out how it works : 
If I modify my JPA object, add a new property in the class and launch ./mvnw compile liquibase:diff, I get a good result in the diff change log file.
Add a test property in the JPA class : 
@Column(name = "essai_titi")
    private Long essaiTiti;
    
    public Long getEssaiTiti() {
        return essaiTiti;
    }

    public CalendrierFacturation essaiTiti(Long essaiTiti) {
        this.essaiTiti = essaiTiti;
        return this;
    }

    public void setEssaiTiti(Long essaiTiti) {
        this.essaiTiti = essaiTiti;
    }

My changelog contains 
```
<addColumn tableName="****">
            <column name="essai_titi" type="varchar2(255 CHAR)"/>
</addColumn>
```
So it works.

But when I try to change the type of my property from Long to String and relaunch ./mvnw compile liquibase:diff then the change is not detected in the diff log file.

Do you have any idea of what is going wrong? Maybe I missed something in the functioning of liquibase. For me it compares the JPA class with its master.xml containing all database XML file changes, right?

Thanks a lot in advance,

Remi

**Comment by jdubois** [comment]
I confirm the issue, it looks like the Liquibase goal doesn't support refactoring the type of a property... Then, that would be really strange, what do you want it to do to your database? Like drop the column, and create a new one? Doesn't look a very normal use case.

Also note we are in the process of upgrading Liquibase, so maybe it will solve your issue.

Anyway I'm closing this as this is a Liquibase usage question, so it shouldn't be posted on the JHipster bug tracker: it's either a SO question, or a ticket for Liquibase.
