### ISSUE TITLE
Use default methods in JpaRepository to separate repository and service layers

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#4382]
##### **Overview of the issue**

Let's take a look at `UserService`. Methods `getUserWith...` assigned only from controller. But in larger apps they may be assigned from the same service too. If it is, lazy collections will not be loaded and `LazyInitializationException` will be throwed. I don't know details, but Spring uses proxy for transaction s and transaction will be closed before collection will be loaded. So methods, annotated with `@Transactional` cannot invoke each other in one service (I faced this problem several times). It also will partially solve [this issue](https://github.com/jhipster/generator-jhipster/issues/4332). I don't know is it a bad practice or not, but it works for me and I didn't face any errors yet.

##### **Suggest a Fix**

Move `getUserWith...` methods to `UserRepository` (and for all similar entities):

    public interface UserRepository extends JpaRepository<User, Long> {
        //existing methods

        @Transactional(readOnly = true)
        default Optional<User> get(long id) {
            return Optional.ofNullable(findOne(id)).map(user -> {
                user.getAuthorities().size();
                return user;
            }); 
        }

        //and so on  
    }

**Comment by jdubois** [comment]
Did you check the service layer? It is here to handle such a use case, including transactions, which are defined at this level.

**Comment by delverdev** [comment]
The limitation of Spring is when calling method on the same bean, call is not intercepted by the system and no annotation based modifications will be applied. That's why `@Transactional` annotation on `getUserWith...` will not work if they'll be called from the same bean. So if I will call for ex. `getUserWithAuthorities` in `UserService`'s method, it will throw `LazyInitializationException`.

**Comment by jdubois** [comment]
Yes that's normal, unless you use AspectJ.
I'm sorry but this is normal Spring, even normal Java stuff: if you call a method within the same bean, the AOP proxies won't be applied. There are many ways to go around this, but usually people do it on purpose (you don't want to have your security annotations applied twice), and that could also be a sign of bad design (you probably need a service layer here).

I'm closing this as this is not a JHipster bug, it's the way Spring works.
