### ISSUE TITLE
swagger-ui jar dependecy adding

### ISSUE THREAD

**Issue by sonersivri** [jhipster/generator-jhipster#4384]
swagger-ui.jar can be added to build files. 
generators/server/templates/_build.gradle
generators/server/templates/_pom.xml
adding swagger-ui may be parametric
server api more useful i guess

**Comment by jdubois** [comment]
I'm sorry but I have no idea what this would add to our current setup...

**Comment by jdubois** [comment]
Oh sorry, this is a "webjars"! This is the opposite philosophy to what JHipster does, and our current setup should work well for you.

**Comment by sonersivri** [comment]
Ok
I use only server side code generation of jhibster
I go on add manually.

**Comment by jdubois** [comment]
I understand! Hopefully we can have a solution for people like you, this could be interesting for microservices.

**Comment by PierreBesson** [comment]
Well, for this usecase we already have the gateway (when doing microservice). However if generating a monolith with SkipCkient this could be an interesting addition. We would need to add the webjar only in this case.
I have seen some people actually using the angular client only for swagger UI !

@jhipster/developers Would everyone agree to add the choice no front-end to the angular1/angular2 question.

If generated without front-end then we could add a log with the swagger-ui URL (from the webjar) at startup.

**Comment by cbornet** [comment]
For apps without front-end, you can also run swagger-ui in docker (just needs some CORS config)

**Comment by jdubois** [comment]
For monoliths, if you don't want a frontend, I don't see much interest in using JHipster... I understand some people do this, but I don't think we should spend time on this, or modify anything for them.

**Comment by cbornet** [comment]
Or even easier : just use the one deployed at http://petstore.swagger.io/

**Comment by PierreBesson** [comment]
@cbornet I confirm it works with any Swagger UI but you do need to enable cors (uncommenting properties in application.yml).
Also you will need to authenticate by hand or remove security so that you can test endpoints.
So in the end that's a lot of work to support this with few benefits.
