### ISSUE TITLE
change user password with admin account

### ISSUE THREAD

**Issue by heppa** [jhipster/generator-jhipster#4386]
* **Overview of the request**

It seems that an admin cannot easily set new passwords for users in the user edit screen in user management.

* **Motivation for or Use Case** 

Our admins should be able to set passwords for users.

* **Browsers and Operating System** 

Irrelevant

* **Related issues** 

Could not find any.

* **Suggest a Fix** 

Add input fields to set new passwords for users in the edit user screen in user management.

Thanks a lot!

**Comment by jdubois** [comment]
That means admins know the users' passwords... I'm sorry but that would be illegal in several countries (at least mine!), so we can't have this by default.
It's very easy to customize, and those screens are generated for this very reason: once they are generated, just add the password field, and allow your admins to change it.

This isn't a bug, this is more a StackOverflow question, so I'm closing this -> please use StackOverflow for more questions!

**Comment by heppa** [comment]
Julien, I understand your reasoning for closing and not allowing a general fix and I know, how to change it in my code, I just thought it would be an interesting feature for others as well in the generated code.

You don't agree, fine. But I don't agree that it should've been a question to be put on SO! ;)

Sorry for bothering!

**Comment by jdubois** [comment]
Oh yes sorry @heppa -> I thought you didn't know how to modify this.
In this case, indeed this is a feature request, and the right place is here, and I apologize.
Anyway, I'm sorry but as this is illegal in some countries, this really can't be the default.

**Comment by heppa** [comment]
@jdubois no worries... If I didn't know how to modify this, I would run into many other issues! ;)

Thanks anyway and I understand! It's maybe because we are not running a public website but migrating internal tools to become webapps.

**Comment by jdubois** [comment]
Oh yes was thinking of a public website, if it's an internal app it's a whole different business.
Then most people use an LDAP directory for this, and we lack support (or at least documentation) on how to integrate JHipster with an LDAP server.

**Comment by heppa** [comment]
Currently, we are in Beta and I'm waiting for our IT department to finish migration towards Active Directory to start integrating LDAP auth. Once I faced this and know more about it, I may spend some time to help with documentation. But it's true, that this integration would make this feature obsolete anyway. good point! ;)

But one other point related to your concerns with user passwords: I just checked and saw, that user passwords are transmitted via AJAX requests in clear text and unencrypted (when registering or when changing). This means, that at least operations would be able to see user passwords then (because they would be able to set log level to DEBUG which logs the password as well in clear text as it's part of the argument to UserService#createUser -> I guess, changing the LoggingAspect should help?

On the other hand, TLS encryption could also help to protect from sniffed HTTP traffic?

Just a few thoughts...

KR.
Alex

**Comment by jdubois** [comment]
- Yes you need to use HTTPS, this will solve all the Ajax issues, and that's totally normal
- Normally you shouldn't be able to see the passwords in the logs, but we've had this issue in the past. Basically, they are not shown in the "toString" methods. For the LoggingAspect it's another issue, and you are correct, but then it is disabled in "prod" mode, and that's the whole idea :-)

**Comment by heppa** [comment]
Yes, I totally agree. My bad for not checking the solutions with HTTPS earlier and that the LoggingAspect is only active in dev profile...

Thanks again!
