### ISSUE TITLE
[FEATURE] gitignore could have folders and not files

### ISSUE THREAD

**Issue by dpalomar** [jhipster/generator-jhipster#4387]
##### **Overview of the issue**

When you make a `git clean -df` some folders like node folders are removed even if they are in _.gitignore_ file

##### **Motivation for or Use Case**

Common development of Jhipster tasks require to use git to control changes and errors because some features are difficult to remove or change without impact. So automated discard of untracked files, results in remove some necessary files accidentally.

##### **Reproduce the error**

- Make a new entity or modify one.
- (new files and folder are created)
- run **gulp install** 
- (new files and folder are created)
- **git status** shows modified files and untracked files
- **git checkout .** to back to previous state.
- (untracked files remain)
- **git clean -df**
- git  removes these files and folders and others also, like node_modules

##### **Suggest a Fix**

when you write some like that: `node_modules/**` in _.gitignore_ file git does not ignore the folder, only the files, and therefore when you execute `git clean -df` git will remove the folders because they are not ignored

So because it is a auto generated file, the solution could be to write only folders and not files:

Change `folder_name/**` by `folder_name`

##### **JHipster Version(s)**

- Jhipster: 3.9.1
- git version 1.9.1
- node: v4.6.1
- npm: 3.10.9
- bower: 1.7.9
- gulp:[11:33:27] CLI version 1.2.2
- yeoman: 1.8.5

##### **Browsers and Operating System**
O.S:
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"

**Comment by jdubois** [comment]
I'm the culprit for this, and I've never used "git clean" to be honest... So comments are welcome, as I'm not using this personally, but this looks like a good improvement.
@dpalomar would you like to do a PR for this? It shouldn't be very difficult.

**Comment by dpalomar** [comment]
It does not appear to be difficult, let me see how the generator works. Really I don't know if .gitignore is hardcoded or dinamically generated.

**Comment by jdubois** [comment]
Have a look at [the documentation](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup) - honestly it should be very easy

**Comment by PierreBesson** [comment]
👍  For this suggestion.
It will be very easy, just PR changes to this file: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/gitignore

**Comment by dpalomar** [comment]
I've got it.

Thanks
