### ISSUE TITLE
Unable to generate entities for serverless jhipster app

### ISSUE THREAD

**Issue by openworker** [jhipster/generator-jhipster#4399]
##### **Overview of the issue**

Attempting to create a client only jhipster app using the --skip-server flag.  When I attempt to add an entity, the following error occurs on Windows 10 and OSX 10.11.6
Using 3.10 but 3.9.1 (at least is also affected).

C:\Users\asani.SANI-ITA\jhipster-serverless-test2>yo jhipster:entity book --skip-server
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.isReservedTableName (C:\Users\asani.SANI-ITA\jhipster-serverless-test2\node_modules\jhipster-core\lib\core\jhipster\reserved_keywords.js:26:23)
    at module.exports.EntityGenerator.extend.initializing.validateTableName (C:\Users\asani.SANI-ITA\jhipster-serverless-test2\node_modules\generator-jhipster\generators\entity\index.js:158:32)
    at Object.<anonymous> (C:\Users\asani.SANI-ITA\jhipster-serverless-test2\node_modules\yeoman-generator\lib\base.js:439:23)
    at C:\Users\asani.SANI-ITA\jhipster-serverless-test2\node_modules\yeoman-generator\node_modules\run-async\index.js:26:25
    at C:\Users\asani.SANI-ITA\jhipster-serverless-test2\node_modules\yeoman-generator\node_modules\run-async\index.js:25:19
    at C:\Users\asani.SANI-ITA\jhipster-serverless-test2\node_modules\yeoman-generator\lib\base.js:440:9
    at processImmediate [as _immediateCallback](timers.js:383:17)
##### **Motivation for or Use Case**

Unable to create serverless jhipster app.
##### **Reproduce the error**

create app directory
yo jhipster --skip-server
accept defaults
use protractor
yo jhipster:entity book --skip-server
##### **JHipster Version(s)**

```
jhipster@0.0.0 C:\Users\asani.SANI-ITA\jhipster-serverless-test2
`-- generator-jhipster@3.10.0

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

``` yaml
{
  "generator-jhipster": {
    "useSass": false,
    "jhipsterVersion": "3.10.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "skipServer": true,
    "enableTranslation": false
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.5.0.windows.1

node: v4.4.3

npm: 3.8.8

bower: 1.7.9

gulp:
[09:17:06] CLI version 3.9.1
[09:17:06] Local version 3.9.1

yeoman: 1.7.0
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "useSass": false,
    "jhipsterVersion": "3.10.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "skipServer": true,
    "enableTranslation": false
  }
}
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no such file generated due to error.
##### **Browsers and Operating System**

entity generation error is pre-browser.  None tested.

**Comment by gmarziou** [comment]
Are you sure that the -skip-server option is supported by the entity sub generator? I would expect it to not require it as it should be saved by the app generator you used first.

**Comment by openworker** [comment]
I tried without the -skip-server as well with same problem.

**Comment by gmarziou** [comment]
OK, so just debug reserved_keyword.js to find out which string it is failing for.
