### ISSUE TITLE
Minor problem when removing a field in a class

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#4404]
Hi guys, I've created a simple class (`ClassA`) containing a simple field (`myAttribute`) and nothing else.
The problem is when I want to remove my field, the generator actually asks me to choose which relationship I want removed... Even if I don't have any.

My bug:

```
The entity Toto is being updated.

? Do you want to update the entity? This will replace the existing files for thi
s entity, all your custom code will be overwritten [BETA] Yes, remove fields and
 relationships
? Please choose the fields you want to remove myAttribute
? Are you sure to remove these fields? Yes

Removing fields: myAttribute

? Please choose the relationships you want to remove (Press <space> to select)
? Are you sure to remove these relationships? Yes

Removing relationships: 

```

To reproduce:
  - `yo jhipster` to have the following .yo-rc.json file:
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "66b53d60f13fc3787e21f7095a6040f9e31efa98",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
  - `yo jhipster:entity Toto` and create only one field (whatever the name/type)
  - No relationships
  - No option
  - `yo jhipster:entity Toto` and select the removal option
  - Remove the field
  - And you have the bug.

Version: 3.9.1

**Comment by deepu105** [comment]
Not exactly a bug, just an aesthetic glitch. Its an easy fix need to add a
validation to check if there are fields or relationships b4 asking the
question. You can do a PR if required for me its not a priority item

Thanks & regards,
Deepu

**Comment by MathieuAA** [comment]
Me neither, just telling you guys. And I did mention it was minor.

**Comment by MathieuAA** [comment]
Thanks Jon!
