### ISSUE TITLE
Bug with pagination - can't see all entities in list when edit/add other entity with relation

### ISSUE THREAD

**Issue by Patresss** [jhipster/generator-jhipster#4409]
When I use pagination I can't see (and select) all entities in list when I want to edit or add other entity with relation. 
For example. I want to add division to teacher. I can see only 20 division. 
http://i.imgur.com/qQ2pWrs.png
When I add division (in my database) which isn't in first 20 I see empty space in my teacher.
I use version: 3.9.1

**Comment by gmarziou** [comment]
Please rewrite your issue by following our issue template and provide all requested information.
Please also clarify your last sentence.
