### ISSUE TITLE
Bug with pagination - can't see all entities in list when edit/add other entity with relation

### ISSUE THREAD

**Issue by Patresss** [jhipster/generator-jhipster#4410]
##### **Overview of the issue**

When I use pagination I can't see (and select) all entities in list when I want to edit or add other entity with relation. 
For example:
1. I have a division "Francuski 1 gr. 1" which is in second page in my list
http://i.imgur.com/7nFScR1.png
2. I want to add this division(owner) to my place but I can see only 20 division in list:
http://i.imgur.com/qQ2pWrs.png
3. I can't add my division(owner) to place so I add it from databse
 UPDATE public.place SET owner_id=1023 WHERE id=1112;
It work's:
http://i.imgur.com/dbjOKsx.png
4.  But when I want edit my place I can't see current division(owner) I can see only empty space:
http://i.imgur.com/FrgKVSd.png

##### **Motivation for or Use Case**
I want to connect my entity with other entity. 

##### **Suggest a Fix**
When user use pagination then REST get always few (20) objects. In edit/add mode REST should return all objects to select

##### **JHipster Version(s)**
3.9.1

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

.yo-rc.json
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "Timetable",
    "packageName": "com.patres.timetable",
    "packageFolder": "com/patres/timetable",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "271bc39c461698f6af12bc1cabc4c280deac1d72",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pl",
    "languages": [
      "pl",
      "en"
    ],
    "messageBroker": false,
    "serviceDiscoveryType": false
  }
}
```

Division:
```
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "timetable",
            "otherEntityName": "timetable",
            "otherEntityRelationshipName": "division"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "curriculum",
            "otherEntityName": "curriculum",
            "otherEntityRelationshipName": "division"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "divisionPlace",
            "otherEntityName": "place",
            "otherEntityRelationshipName": "owner"
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "",
            "relationshipName": "parent",
            "otherEntityName": "division",
            "otherEntityField": "name",
            "ownerSide": true
        },
        {
            "relationshipType": "many-to-many",
            "relationshipName": "teacher",
            "otherEntityName": "teacher",
            "ownerSide": false,
            "otherEntityRelationshipName": "division"
        },
        {
            "relationshipType": "many-to-many",
            "relationshipName": "subject",
            "otherEntityName": "subject",
            "ownerSide": false,
            "otherEntityRelationshipName": "division"
        },
        {
            "relationshipType": "many-to-many",
            "relationshipName": "lesson",
            "otherEntityName": "lesson",
            "ownerSide": false,
            "otherEntityRelationshipName": "division"
        },
        {
            "relationshipType": "many-to-many",
            "relationshipName": "place",
            "otherEntityName": "place",
            "ownerSide": false,
            "otherEntityRelationshipName": "preferredDivision"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "shortName",
            "fieldType": "String"
        },
        {
            "fieldName": "numberOfPeople",
            "fieldType": "Long"
        },
        {
            "fieldName": "divisionType",
            "fieldType": "DivisionType",
            "fieldValues": "SCHOOL,CLASS,SUBGROUP"
        },
        {
            "fieldName": "color",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20161012190223",
    "entityTableName": "division",
    "dto": "no",
    "pagination": "pager",
    "service": "no"
}
```

Place:
```
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "timetable",
            "otherEntityName": "timetable",
            "otherEntityRelationshipName": "place"
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "place",
            "relationshipName": "preferredSubject",
            "otherEntityName": "subject",
            "otherEntityField": "name",
            "ownerSide": true
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "place",
            "relationshipName": "preferredDivision",
            "otherEntityName": "division",
            "otherEntityField": "name",
            "ownerSide": true
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "place",
            "relationshipName": "preferredTeacher",
            "otherEntityName": "teacher",
            "otherEntityField": "surname",
            "ownerSide": true
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "owner",
            "otherEntityName": "division",
            "otherEntityField": "name"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "numberOfSeats",
            "fieldType": "Long"
        },
        {
            "fieldName": "shortName",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20161012190226",
    "entityTableName": "place",
    "dto": "no",
    "pagination": "pager",
    "service": "no"
}
```

##### **Browsers and Operating System**
Windows 10, All browsers

**Comment by ruddell** [comment]
The issue here is that the default page size in Spring is 20.  In order to get the entire list of entities to appear in the dropdown, you need to change the `size` of the query. 

For example, in the `place-dialog.controller.js` change the line `vm.divisions = Division.query();` to include a size param: `vm.divisions = Division.query({size: 100});`

This becomes an issue as the entity list grows, and you also wouldn't want to get the entire list if there are hundreds/thousands of entities.

**Comment by deepu105** [comment]
You still havent given all details required in the issue template like the `yo-rc.json` file, please provide all required information or the issue will be closed.

Though from your explanation it seems like a known issue with pagination as pagination causes just the first 20 to be displayed. Ideally you should handle this own your own depending on your use case cc @jdubois

**Comment by jdubois** [comment]
You selected pagination, and then fill a bug because you have pagination :-)
I understand this isn't obvious, but it's also against our guidelines to document the underlying frameworks: the solution from @ruddell is good, this is why I'm closing this.

**Comment by Patresss** [comment]
Thank you @ruddell! You suggested add size parametr for example 100. Is it possible to add parametr for getting all list? Something like this: 
`Division.query({size: MAX});`

**Comment by jdubois** [comment]
This is typically the kind of classical use case where we need some tutorial. That would be a huge job...

**Comment by cbornet** [comment]
Maybe a dropdown that handles pagination could be useful. I don't know if that exists...

**Comment by jdubois** [comment]
Unfortunately I don't think there's a good solution here... If you want everything then don't use pagination (Spring Data will still put a limit, but it's quite high... And you need one anyway or your app could crash at some point).
Best solution is not to use a Drop down list, but then that would be some custom dev for you.

**Comment by deepu105** [comment]
I would use an autocomplete with a custom query to handle such use cases.
If your dropdown is gonna have more than 20 entries its bad UX already so
better use an autocomplete or linked select that shows less items based on
a query or some other criteria

Thanks & regards,
Deepu
