### ISSUE TITLE
when i use get() in angular2,it get null

### ISSUE THREAD

**Issue by clp334264003** [jhipster/generator-jhipster#4417]
##### **Overview of the issue**
import { Injectable } from '@angular/core';
import { Http, Response } from '@angular/http';
import { Observable } from 'rxjs/Rx';

@Injectable()
export class AccountService  {
  constructor(private http: Http) { }

  get(): Observable<any> {
    return this.http.get('api/account').map((res: Response) => res.json());
  }

  save(account: any): Observable<Response> {
    return this.http.post('api/account', account);
  }
}

**Comment by deepu105** [comment]
This is unreleased code so please don't open bug reports. If you find issues and wanna help please comment on the issue #4407 with clear explanation and stack trace. Even better you can do PR to fix it
