### ISSUE TITLE
want to create app using jhipster with angular 2 branch

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#4423]
I have an interest to create an app from jhipster upcomming release from angulae 2 branch, how an i create app from the branch. not as the generator i want it ass the jhipster app.

**Comment by jdubois** [comment]
Sorry but this is the bug tracker...

**Comment by deepu105** [comment]
Read the ng2 guide in the angular2 branch

Thanks & regards,
Deepu
