### ISSUE TITLE
Set column name other than field name 

### ISSUE THREAD

**Issue by CFabbricante81** [jhipster/generator-jhipster#4425]
##### **Motivation for or Use Case**

I would put in .json (or in JDL IDE ) a column name other than field name to not lose the mapping regenerating the entity

##### **JHipster Version(s)**

All

**Comment by pascalgrimaud** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
