### ISSUE TITLE
Use entity in other microservice

### ISSUE THREAD

**Issue by alialrabi** [jhipster/generator-jhipster#4430]
hi,I have problem to use entities  between  Microservices ,I have microservice1 has Team entity I need to use Team  entity in microservice2 ,I mean I need to import  TeamRepository.java in microservice2,How can  do that with jhipster?

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
Sorry but this should go to SO

**Comment by pascalgrimaud** [comment]
@alialrabi : as said, it's a question for StackOverFlow. But you can find some information in this ticket that can help you too: https://github.com/jhipster/generator-jhipster/issues/3649 -> lot of links, blog, projects etc.
