### ISSUE TITLE
using entity in other microservice

### ISSUE THREAD

**Issue by alialrabi** [jhipster/generator-jhipster#4431]
##### **Overview of the issue**
hi,I have problem to use entities between Microservices ,I have microservice1 has Team entity I need to use Team entity in microservice2 ,I mean I need to import TeamRepository.java in microservice2,How can do that with jhipster?

##### **JHipster Version(s)**
JHipster 3.9.1

##### **Browsers and Operating System**
google chrome and ubuntu 14

**Comment by jdubois** [comment]
I'm sorry but this is the bug tracker and you don't have a bug.
The good place to go is Stackoverflow with the jhipster tag.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
