### ISSUE TITLE
Log file missing in deployed war (tomcat)

### ISSUE THREAD

**Issue by olsky** [jhipster/generator-jhipster#4432]
Missing log file: jhipster war file deployed to tomcat.

The file appender uncommented in logback-spring.xml as in example.

Now when I start with gradlew in dev profile -- the file is created, but not when deployed.

Any idea on how to get the log?

Version info:

- jhipsterVersion: 3.6.0
- tomcat 8
- node: v6.3.0
- yeoman: 1.8.4

**Comment by gmarziou** [comment]
Look at tomcat logs to see how slf4j and logback are initialized, so far there's no evidence that logback-spring.xml is loaded and applied. You can put `<configuration debug=true` in logback-spring.xml to get more logs at init.

I suppose that logback-spring.xml is embedded in your war file, please confirm.

**Comment by olsky** [comment]
I will use the template next time! 👍 

The logback-spring.xml is embedded in the war file, let me try to get it out...

**Comment by olsky** [comment]
so, modified catalina.sh added extra conf for logback.configurationFile...

> 05-Nov-2016 18:43:55.660 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlogback.configurationFile=/usr/local/tomcat/conf/logback-spring.xml

but still no evidence of tomcat picking the conf up.

Am I doing it wrong?

**Comment by ruddell** [comment]
I uncommented the lines in logback-spring.xml and see a `logFile.2016-11-05.log` created in the root of my Tomcat folder (`/usr/local/tomcat`).  It stays at 0 bytes though, even in the dev profile...

**Comment by gmarziou** [comment]
> -Dlogback.configurationFile=/usr/local/tomcat/conf/logback-spring.xml

This option look suspicious to me, as far as I remember it should be:

`-Dlogging.file=file:/usr/local/tomcat/conf/logback-spring.xml`

**Comment by olsky** [comment]
thank you for your input, I will try it.

**Comment by gmarziou** [comment]
Oops it should be 

-Dlogging.configuration=file:/usr/local/tomcat/conf/logback-spring.xml

logging .file is for log file loacation, see http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

**Comment by olsky** [comment]
here is what I've tried now:


>             
>             <fileNamePattern>${catalina.base}/logs/logFile.%d{yyyy-MM-dd}.log</fileNamePattern>

this is tomcat specific, but it worked out and I see log file created with content.

**Comment by gmarziou** [comment]
It works because by default, your app prints to STDOUT but how will you change loglevel with this workaround?

**Comment by pascalgrimaud** [comment]
For me, I use these 2 steps:
1) uncomment https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/resources/logback-spring.xml#L7-L23
2) change from CONSOLE to FILE here: https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/resources/logback-spring.xml#L59

**Comment by olsky** [comment]
@gmarziou I see your point, I was on my way to try the external config file. Will try the: -Dlogging.configuration

**Comment by gmarziou** [comment]
I close the issue as it does not seem to be related to JHipster: more likely a spring-boot logging configuration question.
