### ISSUE TITLE
Credentials for default users not working

### ISSUE THREAD

**Issue by EmilMichalczewski** [jhipster/generator-jhipster#4434]
I generated app with MongoDb database and OAuth2 authentication and after run i am trying to login with admin - admin and user - user credentials and both don't work.  There is one Warning which could be the cause :

>  Cannot enhance @Configuration bean definition 'org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerEndpointsConfiguration$TokenKeyEndpointRegistrar' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.

**Comment by jdubois** [comment]
It really depends on your JHipster version and the options you selected. We can't just "imagine" what you do, and please remember we all do this on our free time... So please help us by providing more information.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
