### ISSUE TITLE
baseURL in mail is localhost

### ISSUE THREAD

**Issue by lrkwz** [jhipster/generator-jhipster#4436]
When used behind a proxy (nginx, varnish, ...) the technique used to retrieve baseUrl to be injected in email templates resolves in http://localhost:8080

            String baseUrl = request.getScheme() + // "http"
            "://" +                                // "://"
            request.getServerName() +              // "myhost"
            ":" +                                  // ":"
            request.getServerPort() +              // "80"
            request.getContextPath();              // "/myContextPath" or "" if deployed in root context
            mailService.sendCreationEmail(newUser, baseUrl);

I think this should take in account the presence of the [defacto standard headers](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields) ```X-Forwarded-Proto```, ```X-Forwarded-for```, ```X-Forwarded-URI```

**Comment by jdubois** [comment]
- We probably have the same issue with the microservice architecture -> for me that's even worse, as what we provide out of the box isn't fully working
- Then we only use here the standard Servlet API, and going away from it could cause issues

Anyway, this whole line could be a custom Spring Boot property, and that would probably solve the issue for everyone:

- In our default conf this property is not set, so by default we still have the current mechanism and this works "out of the box" for most people
- If that's not good, you then need to set the property to whatever you want

**Comment by gmarziou** [comment]
There is probably something that can be done in same vein as this: http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-use-tomcat-behind-a-proxy-server

**Comment by jdubois** [comment]
Oh that would be even better, thanks @gmarziou 
This needs to be tested, but if it works let's use that.

**Comment by lrkwz** [comment]
@gmarziou I've run a quick test of using the "Forgotten password" link and is seems to not resolve the port problem correctly:

    http://172.27.0.1:8080/#/reset/finish?key=21325569793582422291

The hostname (localhost) is replaced by the proxy ip (172.27.01 in my case because I'm using a dockerized httpd) but the port is still there.

My application.yml is

    server:
        port: 8080
        use-forward-headers: true

**Comment by gmarziou** [comment]
Of course, it is documented to solve the HTTP redirection not your mail use case.
What I proposed is to look in Spring Boot source code how rediretion is solved and pottentially re-use whatever beans or services they used in another context: mail.

**Comment by gmarziou** [comment]
Thuguh it might not be possible as they use a Tomcat valve:

https://github.com/spring-projects/spring-boot/blob/98a3ae9ac4e617afe72de786ebc3033532bb125d/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java#L806

**Comment by jdubois** [comment]
Yes I've had a look at it and it seems quite complex to re-implement for mail, and besides I'm sure there are use cases which will not cover.
I'm going to do my first proposal, which is much easier, and add a configuration property.

**Comment by lrkwz** [comment]
+1 Makes sense

Il 13/nov/2016 18:35, "Julien Dubois" <notifications@github.com> ha scritto:
