### ISSUE TITLE
[FEATURE] Prometheus support (Metrics)

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#4445]
I think the metrics aspect of JHipster is not put forward enough as this stuff is really cool. Our official monitoring solution is the JHipster Console (of which I'm releasing a v2 and not planning to abandon) but it might not fit everyone use case (for exemple if you already have a log management solution) so it might be interesting to offer an alternative.

In the mean time some new technologies around metrics have come up recently like Influxdb and Prometheus.
It seems that there is already an InfluxDB reporter in dropwizard metrics however it is not yet released although the PR has been merged for more than a year ! However we could still integrate it using a third party lib like [davidB/metrics-influxdb](https://github.com/davidB/metrics-influxdb)

However, what I'm more interested in is Prometheus (https://prometheus.io/) which has been conceived as a monitoring solution for microservices. Main advantages for this solution :
- Fully open source unlike the offering from InfluxData (features like clustering only available in the proprietary version of InfluxDB)
- Easily scalable, retrieve metrics by polling an endpoint on the service rather than receiving data over a socket like most other systems. Also support consul service discovery for finding nodes.
- Good UI
- Alerting
- De facto standard for Kubernetes monitoring

So I'm suggesting that we do the following:
- [x] Remove the Spark Exporter. I'm sure no one uses it and it is not developped anymore by its author (@ahars a collegue at IpponTech)
- [x] Configure a prometheus exporter using the official client ([prometheus/client_java](https://github.com/prometheus/client_java)) that support dropwizard out of the box.
- [x] Add an option to the docker-compose subgen to setup prometheus

See my demo: [PierreBesson/jhipster-prometheus-demo](https://github.com/PierreBesson/jhipster-prometheus-demo)

**Comment by cbornet** [comment]
But ELK has the advantage to handle both logs and metrics. That's the reason why we didn't use Graphite initially.

**Comment by pascalgrimaud** [comment]
@PierreBesson : I got this error when launching docker-compose up:
`ERROR: Service 'prometheus' depends on service 'cadvisor' which is undefined.`

**Comment by PierreBesson** [comment]
@cbornet you are right I still want to work on elk but have a look at prometheus it has a lot of interesting features and is already present in many kubernetes/docker setups for monitoring the infrastructure. Also it's very easy to add support for it as you just need to expose the metrics on an endpoint similar to what is done by spring boot...

**Comment by PierreBesson** [comment]
@pascalgrimaud I just fixed it.

**Comment by jdubois** [comment]
@PierreBesson I just realised, after releasing JHipster v3.12.0, that this adds JARs for Prometheus in all projects... I don't want to have those very specific libraries everywhere: they will make every project bigger, and can add all kind of issues.
Can't we only have the Prometheus when needed? Maybe with a specific profile, at least?

**Comment by PierreBesson** [comment]
I'm aware of this. However those seems quite small to me, sImilar to the spark or graphite reporter we had before...
We could put it in a specific profile but then we need to also create one for the logback encoder, graphite... Should we do it ? Or maybe together as part of a "monitoring" profile...

**Comment by jdubois** [comment]
I forgot we had this for Graphite.... For me logback should be mandatory, as everybody's using it, and then we should have Graphite and Prometheus as optional.
The easiest solution would be to have a Maven + Gradle profile for each, then it's going to be a lot of profiles in the end, I agree.
Still, I find that it's better than having some unused libraries in the code.

**Comment by deepu105** [comment]
I would really like to have additional dependencies only if needed so a
profile switch would make sense.


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
I think its ok to have profile switches, its just like swagger,
no-liquibase stuff, people who really want those can add the switch


Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
I will work on adding new profiles then.

**Comment by jdubois** [comment]
Having specific profiles isn't a good solution: the generated code will need to be compiled by the end-user, so the Prometheus JARs need to be in the classpath....
This is the same issue for Grafana, and probably for other things as well.

I see two solutions here:

- Remove this code from the main generator and make it a module: this is what we usually do, but the difference here is that it would be some kind of "official" module, which we have never done yet.
- Create our own JHipster library, where this code comes pre-compiled (and thus no compilation issue). This is what Spring Boot does all the time. This is a discussion we've already had many times, is JHipster "just" a generator, or should it evolve into a library at some point?

**Comment by deepu105** [comment]
I'm all for evolving this to a library where required (Some things are just
never changed by end user, and even if it needs change we could come up
with an architecture like spring boot so that user can extend the class and
override the implementation)
We need to accept the fact that we are growing tremendously and we need
some better strategy to manage the code else as options grow code becomes
unmanageable.
One negative feedback I hear sometimes is that we generate far too much
code, its good and bad based on what you like
So this might be a good topic for JHipster 5.0 a total architecture revamp
aimed towards easy extensibility and upgrades
If we can do that JHipster would be killer in all senses.


Thanks & Regards,
Deepu

**Comment by cbornet** [comment]
Another solution is to add it to the "additional technology" question during project generation (as with Kafka).

**Comment by jdubois** [comment]
Why wait for JHipster 5? It's a smaller change than constructor-based injection, and Angular 2 isn't finished yet, so there is time for this.
I'll have a look at all this and send a proposal on the dev mailing list

**Comment by deepu105** [comment]
I meant architecture revamp on JH5 yes this can be on next release

**Comment by jdubois** [comment]
Closing as work is being done at #4674 - I'll reopen if the JHipster lib ends up being a bad idea, but it looks good to me at the moment
