### ISSUE TITLE
yo jhipster:client generator doesn't ask which type of authentication you want.

### ISSUE THREAD

**Issue by NijsTom** [jhipster/generator-jhipster#4447]
When generating the client, it doesn't ask which type of authentication the user would like to implement:
session-based: (stateful), token-based: (stateless), ...
It uses session-based by default and this causes some issues when using a token-based authentication implementation in the server.

![image](https://cloud.githubusercontent.com/assets/16881115/20097731/dfd857b0-a5a7-11e6-9157-97a221941b3f.png)

**Comment by gmarziou** [comment]
Are you sure that you can use the client generator directly?

In my understanding this is always used through the app generator with `yo jhipster --skip-server` but I could be wrong.H ave you tried?

**Comment by deepu105** [comment]
Please read the docs. If you are using the client directly you need to pass
the auth and other details as command line flags. It's documented on the
website.

Thanks & regards,
Deepu
