### ISSUE TITLE
Java Service Class is not generated while regenerating entity

### ISSUE THREAD

**Issue by becjit** [jhipster/generator-jhipster#4451]
##### **Overview of the issue**

Java Service Class is not getting generated while regenerating entities by  modifying <entity>.json file

TestEntity.json after generating it 

{
    "fluentMethods": true,
    "fields": [
        {
            "fieldName": "isDefault",
            "fieldType": "Boolean"
        }
    ],
    "changelogDate": "20161106174609",
    "dto": "no",
    **"service": "no",**
    "entityTableName": "score_card_set_up",
    "pagination": "no",
    "javadoc": "not an ignored comment"
}

Next if I modify and make it **_"service:yes"_** it is not generating Java Service Class. 

##### **Motivation for or Use Case**

While in resource classes it correctly adding Service reference however the main service class still stays missing which throws compiler error

##### **Reproduce the error**

yo jhipster:entity TestEntity

The entity TestEntity is being created.

Generating field #1

? Do you want to add a field to your entity? Yes
? What is the name of your field? isDefault
? What is the type of your field? Boolean
? Do you want to add validation rules to your field? No

================= TestEntity =================
Fields
isDefault (Boolean) 

Generating field #2

? Do you want to add a field to your entity? No

================= TestEntity =================
Fields
isDefault (Boolean) 

Generating relationships to other entities

? Do you want to add a relationship to another entity? No

================= TestEntity =================
Fields
isDefault (Boolean) 

? Do you want to use a Data Transfer Object (DTO)? No, use the entity directly
? Do you want to use separate service class for your business logic? No, the RES
T controller should use the repository directly
? Do you want pagination on your entity? No

Everything is configured, generating the entity...

   create .jhipster/TestEntity.json

change the TestEntity.json and mark service yes. Regenerating the entity does not add Service Class

##### **JHipster Version(s)**
Latest

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
{
    "fluentMethods": true,
    "fields": [
        {
            "fieldName": "isDefault",
            "fieldType": "Boolean"
        }
    ],
    "changelogDate": "20161106174609",
    "dto": "no",
    "service": "no",
    "entityTableName": "score_card_set_up",
    "pagination": "no",
    "javadoc": "not an ignored comment"
}

**Comment by mehmet-aslan** [comment]
You could write `serviceClass` or `serviceImpl` to generate service class/interface&implementation. It does not have option `yes`.

**Comment by jdubois** [comment]
Yes indeed!

**Comment by becjit** [comment]
Thanks. Can this be added in the documentation of regenerating/updating entity? It would be helpful
