### ISSUE TITLE
Removing trailing whitespaces

### ISSUE THREAD

**Issue by SidMorad** [jhipster/generator-jhipster#4456]
Hi everyone,

JHipster : 3.10.0

I do check for trailing whitespaces by .git/hooks/pre-commit hook.

Since I may not be the only one, would you please doing this last step
to make new generated app by JHipster trailing whitespace free?

Doing this fix for generating new Entity will be great too. Imagine I
am doing this boring task again and again while you could fix it for
me and everyone else in one place only once!

This is my console log before first commit:

server/src/main/java/aval/server/web/rest/UserResource.java:144:
trailing whitespace.
+     *
server/src/main/java/aval/server/web/rest/errors/CustomParameterizedException.java:6:
trailing whitespace.
+ *
server/src/main/java/aval/server/web/rest/errors/CustomParameterizedException.java:10:
trailing whitespace.
+ *
server/src/main/java/aval/server/web/rest/errors/CustomParameterizedException.java:12:
trailing whitespace.
+ *
server/src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml:22:
trailing whitespace.
+
server/src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml:54:
trailing whitespace.
+
server/src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml:66:
trailing whitespace.
+
server/src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml:113:
trailing whitespace.
+
server/src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml:154:
trailing whitespace.
+
server/src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml:156:
trailing whitespace.
+
server/src/main/resources/ehcache.xml:39: trailing whitespace.
+
server/src/main/resources/i18n/messages.properties:22: new blank line at EOF.
server/src/main/resources/i18n/messages_de.properties:22: new blank line at EOF.
server/src/main/resources/i18n/messages_en.properties:22: new blank line at EOF.
server/src/main/webapp/app/admin/metrics/metrics.html:173: trailing whitespace.
+
server/src/main/webapp/app/admin/metrics/metrics.html:197: trailing whitespace.
+
server/src/main/webapp/app/admin/user-management/user-management.controller.js:30:
trailing whitespace.
+
server/src/main/webapp/app/app.module.js:6: trailing whitespace.
+            'ngStorage',
server/src/main/webapp/app/app.module.js:8: trailing whitespace.
+            'pascalprecht.translate',
server/src/main/webapp/app/blocks/config/compile.config.js:13:
trailing whitespace.
+
server/src/main/webapp/app/blocks/handlers/state.handler.js:35:
trailing whitespace.
+
server/src/main/webapp/app/blocks/handlers/state.handler.js:40:
trailing whitespace.
+
server/src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.js:8:
trailing whitespace.
+
server/src/main/webapp/app/blocks/interceptor/auth.interceptor.js:21:
trailing whitespace.
+
server/src/main/webapp/app/blocks/interceptor/auth.interceptor.js:25:
trailing whitespace.
+
server/src/main/webapp/app/components/util/truncate-characters.filter.js:7:
trailing whitespace.
+
server/src/main/webapp/app/components/util/truncate-words.filter.js:24:
trailing whitespace.
+
server/src/main/webapp/i18n/de/metrics.json:81: space before tab in indent.
+               "usage": "Usage",
server/src/main/webapp/i18n/en/metrics.json:81: space before tab in indent.
+               "usage": "Usage",
server/src/main/webapp/swagger-ui/index.html:86: trailing whitespace.
+
server/src/main/webapp/swagger-ui/index.html:87: trailing whitespace.
+
server/src/main/webapp/swagger-ui/index.html:88: trailing whitespace.
+
server/src/main/webapp/swagger-ui/index.html:89: trailing whitespace.
+
server/src/main/webapp/swagger-ui/index.html:93: trailing whitespace.
+
server/src/test/features/user/user.feature:1: trailing whitespace.
+Feature: User management
server/src/test/features/user/user.feature:3: trailing whitespace.
+       Scenario: Retrieve administrator user
server/src/test/features/user/user.feature:4: trailing whitespace.
+               When I search user 'admin'
server/src/test/features/user/user.feature:5: trailing whitespace.
+               Then the user is found

Thanks,
Sid

**Comment by deepu105** [comment]
You can submit a PR we will be happy to merge

Thanks & regards,
Deepu

**Comment by SidMorad** [comment]
I notice `jhipster upgrade` command will fail if `.git/hooks/pre-commit.sample` hook is activated.

I know this is a minor issue, but please make this last step to make things more neat!

Plus I think `.git/hooks/pre-commit` hook is a very nice automatic check before each commit. and I hope JHipster developers will use it too(for JHipster development) for preventing this kind of issues! and keep things even more clean and organised.

Thank you.

p.s. My workaround is to disable/enable pre-commit hook before and after each upgrade.

**Comment by pascalgrimaud** [comment]
I'm still thinking about proposing to remove the `jhipster upgrade` , as it causes so much issue. Everyone has a different config (yarn, npm), a specific environment (using a release version, or the master version), now, it's a config with git
@SidMorad : so if you know how to fix the `jhipster upgrade`, go ahead and PR the fix

**Comment by tientq** [comment]
Actually, `jhipster upgrade` command help me a lot. I knew some minor issues, and i will do PR when I have time.

**Comment by SidMorad** [comment]
@pascalgrimaud Thanks for your attention. I think this is not a `jhipster upgrade` issue. and `jhipster upgrade` will work for majority of Git users without any problem. In the other hand if you have `.git/hooks/pre-commit` hook activated then `jhipster upgrade` can not finish it's job.

To reproduce this issue, we could run following command manually: `git diff --staged --check`
Which in my case(a JHipster microservice) shows following report:
```
backend/route/src/main/resources/i18n/messages.properties:22: new blank line at EOF.
backend/route/src/main/resources/i18n/messages_en.properties:22: new blank line at EOF.

```
and if is a JHipster UAA:
```
backend/uaa/README.md:88: new blank line at EOF.
backend/uaa/src/main/resources/i18n/messages.properties:22: new blank line at EOF.
backend/uaa/src/main/resources/i18n/messages_en.properties:22: new blank line at EOF.
```

and if a JHipster Gateway:
```
backend/gateway/src/main/resources/i18n/messages.properties:22: new blank line at EOF.
backend/gateway/src/main/resources/i18n/messages_en.properties:22: new blank line at EOF.
backend/gateway/src/main/webapp/app/admin/metrics/metrics.component.html:179: trailing whitespace.
+    
backend/gateway/src/main/webapp/app/home/home.css:26: new blank line at EOF.
backend/gateway/src/main/webapp/content/css/vendor.css:4: new blank line at EOF.
backend/gateway/src/test/resources/config/application.yml:95: trailing whitespace.
+                secret: 
```
As you see number of affected files are not many and this minor issue can be fixed simply by opening above files with an editor and removing trailing whitespaces.

I don't mind to create a pull request for this and fix it for now, but this issue can reappear easily if JHipster developers doesn't do this last check(either manually or automatically) before their commits. 

Please let me know if more information needed, thanks.

p.s. Above outputs are result of upgrading from `v4.5.6` to `v4.6.0`.

**Comment by deepu105** [comment]
@SidMorad thinking again, actually you don't have to do the whitespace check at all. Git automatically handles that when you push your files and that is why we don't do anything for that and we are not planning to do as well. We make sure the generated code conforms to the lint and editorconfig config. So if you want to do something special thats up to you. If you think this can be improved in either tslint, gitattributes or editorconfig you are welcome to suggest a PR

**Comment by SidMorad** [comment]
>actually you don't have to do the whitespace check at all. Git automatically handles that when you push your files

@deepu105 I am not sure about this part, maybe Github has an option for doing this!(?).

And thanks for mentioning `.editorconfig`. I think it can be use to do the same thing. To be specific I think following configs has direct connection with our issues here.
```
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```
and changing it to
```
trim_trailing_whitespace = true
insert_final_newline = false
```
may help JHipster to avoid such issues.

**Comment by deepu105** [comment]
@SidMorad we have that on purpose. It's a style thing mostly and also having a blank line is good when you use code across OS with different return characters. So if you want you can change it but we will not change the setting

**Comment by SidMorad** [comment]
> we have that on purpose. It's a style thing mostly and also having a blank line is good when you use code across OS with different return characters.

@deepu105 I respect the decision, and in my case I am going to follow Git recommended approach[1]! :-)

[1] no blank line at the end of a text file

**Comment by deepu105** [comment]
@SidMorad yes, it should be just one blank line. Btw just curious I didn't know that Git recommends having no blank line. If so we could consider changing this as we want to follow recommended best practices where possible. Could you please point me to the recommendation id docs/article or something?

**Comment by SidMorad** [comment]
@deepu105 Regards to _no blank line as last line_, It seems I was wrong, because `git diff --staged --check` will not throw error(at least for some file extensions) always. I also wish to know a good source as reference, but my only reference are `git diff --staged --check` and `man git-diff` commands. Please let me know if you find a better document as guideline, thanks.
