### ISSUE TITLE
Help me,What is wrong result?

### ISSUE THREAD

**Issue by swit1983** [jhipster/generator-jhipster#4457]
G:\kenlenecd>yo jhipster
F:\node-global\node_modules\yo\node_modules\rx-lite\rx.lite.js:75
    throw e;
    ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at MuteStream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at MuteStream.emit (events.js:188:7)

**Comment by ruddell** [comment]
This is your second issue with the same content.  Please follow the issue template before opening another one.  I would try re-installing or upgrading yeoman `npm install -g yo`.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by ruddell** [comment]
This looks like an issue with the newer versions of node (> v7.0.0).  The current 'workaround' is to either use v7.0.0 or LTS 

https://github.com/nodejs/node/issues/9542

**Comment by jdubois** [comment]
Oh yes, then this ticket could have been good!!! Can you rewrite the title?

**Comment by ruddell** [comment]
I updated the title, I don't think there's much we can do until it gets fixed upstream.

This issue only affects Windows users using the newest node version

**Comment by deepu105** [comment]
Just use an LTS guys

Thanks & regards,
Deepu

**Comment by swit1983** [comment]
I'm sorry, I didn't see the first question that had been closed. 

Thank everyone.

**Comment by egorlitvinenko** [comment]
@jdubois 

Similar
Error: https://pastebin.com/Eh20XXMX
Info: https://pastebin.com/SRCTbqMn
In jhipster's docker container.

**Comment by gmarziou** [comment]
Please don't use pastebin or file attachment for output of `jhipster info,` it has been made to be directly pasted into github issue.

**Comment by gmarziou** [comment]
More important @egorlitvinenko : don't post on an old and closed issue, please open a new one.

**Comment by gmarziou** [comment]
@egorlitvinenko : don't post on an old and closed issue, please open a new one.
Please don't use pastebin or file attachment for output of `jhipster info,` it has been formatted especially to be pasted into github issue.
