### ISSUE TITLE
Performance decrease with byte[] fields in entities.

### ISSUE THREAD

**Issue by daddy32** [jhipster/generator-jhipster#4467]
##### **Overview of the issue**
I see following issue with otherwise excellent blob support in JHipster.

As per design, the REST response is returning all the file contents directly. This is problematic in listing templates - when displaying a list of several records, page is not rendered until the angular client finishes downloading ALL the files from the server - of course, only after the query from backend to the database is finished. Even with pagination of the list (depending on the file size), this can take very long. 

##### **Motivation for or Use Case**
User may not be interested in the file contents at all - he may be looking at other fields of the entity. Regardless, pre-fetching contents of all the blob fields in all the entities in the list is an overkill.

##### **Reproduce the error**
Generate an application with entity containing byte[] field. Run the application and create at least 5 records with byte[] field filled with at least 1 MB of data. Open the page listing all the records.

##### **Related issues**
None known

##### **Suggest a Fix**

Maybe implementing lazy loading for the blob contents. 

##### **JHipster Version(s)**
3.9.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "",
    "packageName": "",
    "packageFolder": "",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "sk",
    "languages": [
      "sk",
      "en"
    ],
    "serviceDiscoveryType": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "templDataMap",
            "otherEntityName": "templDataMap",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "fileName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 400
        },
        {
            "fieldName": "fileContents",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "message",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 1000
        },
        {
            "fieldName": "recipient",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 400
        },
        {
            "fieldName": "status",
            "fieldType": "FileStatus",
            "fieldValues": "GENERATED,PREPARED,SENT,ERROR"
        }
    ],
    "changelogDate": "20161025090849",
    "javadoc": "Generated file - template with its field filled.",
    "entityTableName": "output_file",
    "dto": "mapstruct",
    "pagination": "pager",
    "service": "serviceImpl",
    "angularJSSuffix": "_pdfff"
}

##### **Browsers and Operating System**
Probably all of them.

**Comment by jdubois** [comment]
Yes I understand your issue, as you ask to have 5 big entities loaded.
Maybe you could have those big attributes lazy-loaded: in this specific use case it wouldn't help as you are loading everything anyway (it might even make things worse), but you could also hide those attributes from the UI and not load them at all.
That could be a solution, then there are other people who will want to do the opposite (loading everything), and so that means we would need to do a new option for that... And in that case we need to follow [Policy 2](https://jhipster.github.io/policies/), and I'm not sure that option is worth being added.
I'm closing this as I don't think this is worth adding, but if you have a try, using a lazy-loaded attribute, and if indeed it ends up being complex, please do notify us on this ticket, so we can add the option.

**Comment by daddy32** [comment]
Thank you for an answer.

But I would argue that current behavior is almost never desirable - so even if there is no option, default behavior should be other way around:  **never** load the contents of byte[] fields, at least in the listings. 
But of course, I don't have the usage statistics (small files vs bigger files) to support this claim.

> as you ask to have 5 big entities loaded

Just to be clear: I've used generated application with no changes to code and the listing screen got much slower with each new row added. I didn't ask to have them loaded, I've just opened a page :)

Anyway, I respect your decision, I just wanted to make sure there is no misunderstanding (thanks to my english or anything else).

>  you could also hide those attributes from the UI and not load them at all

Could you please point me in the way of how to do this? I'll figure the rest - loading them later etc. - on my own.

Have a nice day.

**Comment by ruddell** [comment]
I solved this in the past by using DTOs.  When fetching lists of the entity, I used a DTO that excluded the blob field.  When creating/updating/loading a single entity, I used a DTO that included the blob field.

**Comment by jdubois** [comment]
Oh yes that's even easier @ruddell !

**Comment by daddy32** [comment]
OK, thank you both! I will use the DTO approach.
