### ISSUE TITLE
Strange Behaviour if entity name contain "Node" word

### ISSUE THREAD

**Issue by zulfahmi** [jhipster/generator-jhipster#4468]
I think there is an issue when application using word 'node' or word contain 'node' as entity name.
I created simple jhipster app, then I add some entities and one of them is entity Node. I can generate and run application. But when I try create new Node data in new form, there is no form shown, only grey page. There is no problem with other entity CRUD test. I thought there was a problem with my entity and try to change relationship but still the same problem. Then I try to rename my entity to NetworkNode, but still face the same problem.
I try to create application only with one entity that is entity with 'Node' name, like this:
entity Node {
  nodeName String,
  nodeType String
}
I don't know why but the new/edit form can not be shown either.
But when I try with other name, there is no problem at all.

Is there any constraint on using 'node' word in entity or other part of jhipster? maybe conflict with node command?

For now my solution only change entity name to other word.

Test on Windows 7 and Mac OS El Capitan
I am using latest jhipster 3.10

regards,

zulfahmi

**Comment by jdubois** [comment]
Next time, can you follow the guidelines so I can more easily reproduce? I'm trying to create one now

**Comment by jdubois** [comment]
I confirm the issue, looks like an issue in AngularJS, maybe `node` or `nodeName` is a reserved keyword there?

**Comment by jdubois** [comment]
Here is my `.jhipster/Node.json` file:

    {
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "nodeName",
            "fieldType": "String"
        },
        {
            "fieldName": "nodeType",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20161114151048",
    "dto": "no",
    "service": "no",
    "entityTableName": "node",
    "pagination": "no"
    }

**Comment by zulfahmi** [comment]
@jdubois  Thanks for remind me about the guidelines.
And also for swift response.

**Comment by jdubois** [comment]
I guess we will need to have a new "reserved keywords" for the front end, like we have for databases

**Comment by deepu105** [comment]
I dont think angular has such reserved keywords. needs some investigation
here


Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
`nodeName` and `nodeType` seem to be used by Angular.
You can open your `bower_components/angular/angular.js` file to see them

**Comment by jdubois** [comment]
OK I'm adding a specific reserved keywords list for AngularJS

**Comment by MathieuAA** [comment]
For the generator's next release, you can use v1.2.1 of JHipster Core for this.

**Comment by jdubois** [comment]
Yes it's [updated here](https://github.com/jhipster/generator-jhipster/commit/e8d523188f53a02e523a90fa236dab38ae98a661)
