### ISSUE TITLE
[FEATURE] Geometry field type support

### ISSUE THREAD

**Issue by zulfahmi** [jhipster/generator-jhipster#4469]
I think it will be very helpful if field type Geometry added to entity when jhipster upgrade to Hibernate 5 because this Hibernate version already include spatial data type in its release.

My wish list anyway :)

Thanks and regards,

zulfahmi

**Comment by gmarziou** [comment]
This could be not easy because not all databases support Geometry. At work, we use it for both PostgreSQL and H2, there's also a 3rd party extension for Liquibase.

**Comment by jdubois** [comment]
Oh indeed, this probably won't work with MySQL, and won't be supported by JPA...

**Comment by jdubois** [comment]
OK, I've had a look, and indeed that's specific, and would need to add extra libraries - which of course we can't do for everyone.
So sorry @zulfahmi but we can't add this for everyone - this would need to be a module, but I'm not sure we can do it as it's also part of the entity sub-generator.
