### ISSUE TITLE
[FEATURE] Support Vietnamese

### ISSUE THREAD

**Issue by tientq** [jhipster/generator-jhipster#4473]
* **Overview of the request**

Hello, I'm Vietnamese. I'm going to use jhipster to kick start my project. And I recognize that jhipster has not support Vietnamese yet.
I read guidelines about how to add a new language that is not supported. But I want to use Vietnamese as the main language. And everyone especially Vietnamese can use it. 

* **Motivation for or Use Case** 

Support Vietnamese.

* **Browsers and Operating System** 

* **Related issues** 

* **Suggest a Fix** 

I would like to help. I can translate from English to Vietnamese.

**Comment by pascalgrimaud** [comment]
New language is welcome.
Can you do a PR?

**Comment by tientq** [comment]
I'm sorry, what do you mean "PR"?

**Comment by jdubois** [comment]
A Pull Request, that's how people contribute. Have a look at our "CONTRIBUTING" document on the root directory of the project.

**Comment by tientq** [comment]
Yes, of course. I'm translating. I will commit it when I complete the translation.

**Comment by jdubois** [comment]
OK perfect @tientq ! In your commit, don't forget to close this issue using the specific "Fix" keyword.

**Comment by tientq** [comment]
Yes, thank you.
