### ISSUE TITLE
[BUG] Cassandra - Session token is not persisted in the persistent_token table

### ISSUE THREAD

**Issue by raphaelbrugier** [jhipster/generator-jhipster#4483]
##### **Overview of the issue**

When using Cassandra, the session token is not persisted in the `persistent_token` table.
The table exists and the CustomPersistentRememberMeServices tries to read the token and delete it, but never saves it.
With a SQL database, the token is persisted in the `onLoginSuccess` method.

NB: The session mechanism works, fine. It's just the token is never persisted and those can not be invalidated.

##### **Reproduce the error**

- Create a JHipster monolith application with Cassandra and a "Session" security.
- Log in the app.
- See the `persistent_token` table is still empty.

##### **Suggest a Fix**

I'm not sure what is the expected behavior, having the token working with Cassandra - in that case it should be saved - or not working and JHipster should not generate Token related code.

I could propose a PR based on the expected behavior.

##### **JHipster Version(s)**

3.11

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.11.0",
    "baseName": "jhisecurity",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "serviceDiscoveryType": false,
    "jwtSecretKey": "9eb2dba9a24dad2315af2d3443d68016af60236c",
    "rememberMeKey": "a1fff3e15cb7761550e69b712b3919bdf470a624"
  }
}
```

**Comment by jdubois** [comment]
Oh, thanks for testing!! This is obviously my fault :-)
So the token should be saved, of course. It should work the same as with JPA or MongoDB.
