### ISSUE TITLE
Generator.prototype.registerModule can be called only once

### ISSUE THREAD

**Issue by gzsombor** [jhipster/generator-jhipster#4489]
##### **Overview of the issue**

If a module tries to call the Generator.prototype.registerModule more than once - for example for registering app and entity hooks), only the last one is written out

##### **Motivation for or Use Case**

I try to write a module, which is called every time when an entity is generated, or when the whole app is regenerated.

##### **Reproduce the error**

With the jhipster-module-generator create a module, and modify the main generator and add 
a second call, something like this: 
      `  jhipsterFunc.registerModule("generator-jhipster-random-thought", "app", "post");`

Use `yo jhipster-random-thought` - after check the .jhipster/modules/jhi-hooks.json file, notice, that only one hook is registered

##### **Suggest a Fix**

The cause of this problem is very subtle - the registerModule function use this.fs object to read and write files, but this is a memory only filesystem, and the real write only happens after the final generator step, but the shelljs.test checks the real filesystem, so this is what happens:
1, first registerModule call
2, shelljs returns, that there is no callback file
3, the code creates a callback list with the newly added config
4, second registerModule call
5, shelljs still doesn't see the callback file
6, the code creates a callback list again, with only the second config

**Comment by deepu105** [comment]
Nice catch. Thanks
