### ISSUE TITLE
MongoDB: ZonedDateTime causing generated Int tests to fail

### ISSUE THREAD

**Issue by thejames42** [jhipster/generator-jhipster#4491]
##### **Overview of the issue**

When creating a new project with jhipster v3.11.0, the generated ResourceIntTest.get and .getAll fail when using a ZonedDateTime in the entity.
```
java.lang.AssertionError: JSON path "$.zdt" 
Expected :1970-01-01T00:00:00Z
Actual   :1969-12-31T18:00:00-06:00
```

##### **Motivation for or Use Case**

Generated tests must be fixed manually before I can build the project.

##### **Reproduce the error**
1. create new microservice project using mongoDB.
2. create new entity with a ZonedDateTime field.
3. build the project.
4. 2 tests fail with assertion errors.

##### **Related issues**
The fix implemented for Issue #4373 seems to have caused my local failures.

##### **Suggest a Fix**
I was able to get my tests working by reverting to modifying my tests to match a project generated with v3.10.0. 
At least one other person with whom I discussed this on gitter has been unable to recreate the issue in v3.11.0. 
It could be related to my current time zone. It could also be related to how the ZonedDateTime datatype is persisted or retrieved with mongo.

##### **JHipster Version(s)**
3.11.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.11.0",
    "baseName": "zdtFail",
    "packageName": "com.thejames.zdtfail",
    "packageFolder": "com/thejames/zdtfail",
    "serverPort": "8085",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "3ae7586b632df7845a3666e95f82fe5394589405",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
```
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "zdt",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "dto": "mapstruct",
    "service": "serviceImpl",
    "entityTableName": "zdt",
    "pagination": "no",
    "microserviceName": "zdtFail",
    "searchEngine": false
}
```

##### **Browsers and Operating System**
OSx Sierra. tests fail when run from Intellij or iterm2.

**Comment by ruddell** [comment]
I'm the person from Gitter that couldn't reproduce it - with the full `.yo-rc.json` I can confirm the error.  It does not affect MySQL

**Comment by cbornet** [comment]
Indeed : the converters we use for Mongo use the system TZ and we changed the test to use UTC because of Elastic Search.

**Comment by pascalgrimaud** [comment]
I manage to reproduce this issue using the same [config](https://github.com/pascalgrimaud/jhipster-travis-tester/blob/issue-4491-TZ-mongo/app/.yo-rc.json) with Travis, by changing the TZ:
- Travis log: https://travis-ci.org/pascalgrimaud/jhipster-travis-tester/builds/177093227
- here code to change TZ in `.travis.yml` file:
```yaml
before_install:.
    - export TZ=Australia/Canberra
    - date
```

**Comment by cbornet** [comment]
I have a fix involving a custom harmcrest Matcher to compare the datetime's instant instead of the string (to be independant of TZ). Will PR soon.

**Comment by cbornet** [comment]
@pascalgrimaud I think it's useful to have the tests passed in a TZ distinct from UTC. Can you PR your travis config ?

**Comment by pascalgrimaud** [comment]
@cbornet : yes I will do it !
