### ISSUE TITLE
[FEATURE] Can use List instead of Set for relation

### ISSUE THREAD

**Issue by Dufgui** [jhipster/generator-jhipster#4494]
##### **Motivation for or Use Case**

We want to keep order of sub element (relation) when we do a find with a fetch join eager ordered relation

##### **Suggest a Fix**

We can add variable of the expected type for relation (Set or List) used in :
https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/src/main/java/package/domain/_Entity.java

It can be done globally with an option of the entity generator. Or if you prefere it can be store in the json describing the relation. As you prefere. I can do a PR. 

##### **JHipster Version(s)**

3.11.0 (but all previous too)

**Comment by ruddell** [comment]
I think the `@OrderBy` JPA annotation solves this.  It sorts your sets by a child entity property.  See http://www.objectdb.com/api/java/jpa/OrderBy

    @Entity 
    public class Person {
         ...
       @OrderBy("zipcode.zip, zipcode.plusFour")
       public Set<Address> getResidences() {...};
       ...
    }

**Comment by Dufgui** [comment]
As explain the javadoc the Set doesn't respect any order
http://docs.oracle.com/javase/6/docs/api/java/util/HashSet.html#iterator()
So even if Hibernate get the data ordered, the set don"t keep this information

**Comment by cbornet** [comment]
The TreeSet would preserve the order but I don't know if it's performance-wise.

**Comment by Dufgui** [comment]
or the http://docs.oracle.com/javase/6/docs/api/java/util/LinkedHashSet.html
But I think it's a bad idea to keep order and unicity information by default.

As explain here, it's a choice depending of what you want.
http://stackoverflow.com/questions/6562673/onetomany-list-vs-set-difference

**Comment by jdubois** [comment]
I see you answered yourself, but to be clear:

- We use Set by default, as our relationships are not ordered. And an
unordered table, with unique rows, is basically a Set
- If you want your relationships to be ordered, yes you should use a List
to preserve the order

Julien

**Comment by jdubois** [comment]
I'm closing this as for me this is clear - I hope that's fine with everyone!

**Comment by gzsombor** [comment]
... and if you want proper List, then you need to add a @OrderColumn annotation, and a new column to the child entity ( http://wiki.eclipse.org/EclipseLink/Examples/JPA/2.0/OrderColumns )

**Comment by mohamedzaki90** [comment]
should the set cause performance issues while adding a new element to a large collection? according to this https://www.thoughts-on-java.org/association-mappings-bag-list-set/
List is treated as bag which could be more performant in case of large collections

**Comment by Blackdread** [comment]
this is old issue, create new one.
Set is better.
If you have 1k+ 10k+ list items to fetch with JPA you should first think about what you trying to achieve before trying to "optimize" between Set and List
