### ISSUE TITLE
When using a UAA delgate the email templates and baseURL to the caller microservice

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#4498]
##### **Overview of the issue**
When using a uaa server the baseUrl and the emails templates used arre managed by the uaa server itself, the aim is to let the microservice provide those assets to the uaa in order to have a per microservice personalization of the emails.

##### **Motivation for or Use Case**

Imaging to have a set of microservices and you have 2 gateways (which represent 2 differents products, let's say Facebook and What's App) at the end all the users details will be managed in the same uaa server but you want to send customized emails depending on the product.

When using a uaa server, the component is responsible to send the activation, creation or password reset emails. Currently everything is managed by the uaa forcing to have one unified baseUrl and email model for all the gateways. 

##### **Reproduce the error**
Create an uaa server and 2  gateway microservices (ie. 2 different application within a same ecosystem) and try to send mails with different baseUrl or email template.

##### **Suggest a Fix**

So far what I imagine

1. Passing everything as parameter, this implies to wrap the current parameters into a weird DTO which aggregate the current object (ie. `ManagedUserVM` and a `String)  + a `MailInfo` (which the templates as Strings + baseUrl+etc.). By default if the MailInfo is empty, we fallback on the uaa config.

2. Take advantage of the Config Server to get these details. 

3. Store everything (templates + values) on the uaa make them accessible via a key (the name of the microservice for instance). This implies we have to re-deploy the uaa server everytime there is an update.

**Comment by pascalgrimaud** [comment]
@danielpetisme : does this https://github.com/jhipster/generator-jhipster/issues/4507 help on this ?

**Comment by danielpetisme** [comment]
@pascalgrimaud Jhipster properties will do the job when the activation link target one and only one frontend service (most of the time your gateway). But when several frontends application use the same uaa you want to redirect the user on one particular application.

I don't know if I have to continue the discusion on this issue or react to the #4507 ?

**Comment by pascalgrimaud** [comment]
I think we should continue the discussion here, as it's a specific use case, and it's about UAA.
As UAA is still in beta, we need some feedbacks like you did!

Ping @xetys as he coded UAA : do you have some opinion about this?

**Comment by danielpetisme** [comment]
@jdubois what do you think of this feature ? Do you think it's overkill
compared to the jhipster properties approach ?

Le 19 nov. 2016 4:51 PM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
With #4507 for me the issue is solved: you can push this from the config server if you want to, and have either a common or specific property for your services.

**Comment by danielpetisme** [comment]
Not sure to understand this part

Imagine I have a service `appA` and a `uaa` server.
I will have a `uaa-prod.yml` config file with the `baseUrl` according to the #4507 the uaa server will use this value (it's actually what I do today.

But this config (ie. activation link and template) will be generic for all by services.
I can't define a per service mailing config and let the `uaa` use it (ie. have a `baseUrl` value in the `appA-prod.yml` config)

I don't understand this part actually
>specific property for your services.

That means by example I can't have 2 activation links for 2 gateways. I will force the user to go to one of this two and then redirect it to the appropriate one.

If you have a look to the [Github Oauth](https://developer.github.com/v3/oauth/) doc you can see a 
parameter [`redirect_uri` ](https://developer.github.com/v3/oauth/#redirect-urls).

**Comment by jdubois** [comment]
Oh sorry you want that in the UAA server... So no it wouldn't work.
You'll need specific code for that, or a common URL.

**Comment by jdubois** [comment]
@danielpetisme I've read your issue again (sorry, I was away from home, so I just got your mention, and didn't read the full issue), and indeed there is no solution for this currently.
From what I remember with CAS, it gets a parameter with the URL, so that would be your solution 1. At least it's easy to do.
Then this is quite a specific case, I'm not sure we should go that far in the generator.

**Comment by danielpetisme** [comment]
@jdubois indeed if the typical micro-service architecture is to propose 1 product, then you're right and my case is specific.  But if you have multiple products with differences....
That's also features that Stormpath-like companies sell (email customization per project).

If I have time I'll try to propose something easy, basically everytime you generate a microservice in a uaa context it asks to the uaa directory, in that case it's easy to create a `resources/templates/<microservice-name>` folder with templates to customize per projet. Then we'll invoke `/activate` we could provide the projet name + baseUrl as parameters to select the templates + the values to inject.

Tell me if it's something that could interested JHipster.

I think we can close this issue with the conclusion that nowadays, this a specific need the generator won't cover.

Thanks

**Comment by jdubois** [comment]
Yes that could be an improvement in the future, so if you have a solution, your contribution is definitely interesting.
