### ISSUE TITLE
Only use the JHipsterProperties to generate the baseURL for sending emails

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4507]
This comes from [this change and discussion](https://github.com/jhipster/generator-jhipster/commit/ccaf66377fbabeb25926a921081fdfb1e8d1e7e7)

Let me first give some context:

When we send an email, we often need a "base URL" so we can send a link to users in the body of the e-mail. This is a link to the current application so users can reset their password, validate an email address, etc.

We've always used the `HttpServletRequest` to generate this "base URL", and use it to find the current host name, port, and context. This works well for simple use-cases, but of course it doesn't work well if you have a gateway or router in front of your application.

This is why I just added a specific JHipster property, so you can set whatever "base URL" you want.

Now for the issues:

- the `HttpServletRequest` should not be sent to the service layer. It could be seen as an architecture issue (it should not go past the controllers).
- Using the `HttpServletRequest` in an async service (which is our case here) can also lead to lots of technical issues: the request is probably re-used by the app server when we use it in the service, and I don't even want to think of the issues here.
- Having a `HttpServletRequest` as a parameter in our method call, but in the end not using it because we have a JHipster property, is just misleading.

So for those 3 reasons, I find the current code really bad. And please note I'm the main author of all this :-)

So my proposal is just to suppress all this, and just use the JHipster property instead. This is already what we do for the "from" address, and this is isn't causing any issue, so I don't think it would cause any trouble to have 2 properties instead of one.

**Comment by deepu105** [comment]
👍 for external property and we can set localhost as default and people can change as they need later

**Comment by sendilkumarn** [comment]
Agree to that... one more thing that we always move to external property. +1
