### ISSUE TITLE
[FEATURE] Add a CLOB explanation on JDL documentation

### ISSUE THREAD

**Issue by timpamungkas** [jhipster/generator-jhipster#4508]
I found this [feature](https://github.com/jhipster/generator-jhipster/issues/1974) about CLOB datatype, but I can't found any explanation on [JDL Documentation](https://jhipster.github.io/jdl/#entitydeclaration)

Also, when I use jhipster:entity generator, no option of "CLOB" displayed when selecting datatype.

How can I use CLOB on my entity?

**Comment by ruddell** [comment]
When using the entity generator, choose Blob and then `Text - A CLOB (Text field)`.  If you want to use it in JDL, use the TextBlob type.

I will PR the docs

**Comment by timpamungkas** [comment]
Thanks @ruddell
