### ISSUE TITLE
[FEATURE] Cassandra tests improvements

### ISSUE THREAD

**Issue by raphaelbrugier** [jhipster/generator-jhipster#4513]
I'd like to propose two improvements for the Cassandra tests.

## 1/ Start Cassandra unit only once for all the tests.
Currently, the cluster is started before each test class.
After starting, all CQL scripts are applied to prepare the tables.
We found in our current project that it was a very expensive operation to do for every test class.

We reduced our tests duration by starting the cassandra-unit cluster only once, using a simple boolean. see [here](https://github.com/raphaelbrugier/jhipster-experiment/blob/cassandra-rdm-port/src/test/java/com/mycompany/myapp/AbstractCassandraTest.java#L37).

## 2/ Start the cassandra-unit embedded cluster on a random port
Currently, it's not possible to run multiple continuous integration jobs in parallel because Cassandra-unit starts on the default port 9042.
Only one job will pass and the others will fail with the error:
`org.apache.cassandra.exceptions.ConfigurationException: /127.0.0.1:7010 is in use by another process.  Change listen_address:storage_port in cassandra.yaml to values that do not conflict with other services`

Cassandra-unit can start on a random port since jsevellec/cassandra-unit#119

To use this feature I needed to do the following:
- copy a custom configuration file for Cassandra-unit because of this bug: jsevellec/cassandra-unit#176
- start Cassandra-unit on a random port before starting the Spring Context. [see here](https://github.com/raphaelbrugier/jhipster-experiment/blob/cassandra-rdm-port/src/test/java/com/mycompany/myapp/AbstractCassandraTest.java#L42)
- add a spring 'Test' profile to override the Cassandra Configuration for the tests. [see here](https://github.com/raphaelbrugier/jhipster-experiment/blob/cassandra-rdm-port/src/main/java/com/mycompany/myapp/config/Constants.java#L11)
- return the random port to instantiate the Cassandra client. [see here](https://github.com/raphaelbrugier/jhipster-experiment/blob/cassandra-rdm-port/src/test/java/com/mycompany/myapp/config/CassandraTestConfiguration.java#L26)

The main problem was to inject the Random port into the Cassandra cluster client configuration. Ideas welcome for a better way ;)

See [this commit](https://github.com/raphaelbrugier/jhipster-experiment/commit/899d8c1bc3bba72508378e7cff9f4cdb38dfcb88) for an overall idea of the changes.

If these features and implementations seem good to you, I'll submit a PR.

**Comment by pascalgrimaud** [comment]
Good to me!

**Comment by jdubois** [comment]
+1 from me too!
I saw in your code that you put "-1" for the port: I think that should be "0" instead

**Comment by pascalgrimaud** [comment]
Sorry for late answer on this, but some additional ideas @raphaelbrugier as I am on the same case that you.
- on Windows, using embedded Cassandra doesn't work very well (some randomly fails) That's why we decide to use a real Cassandra on a special keyspace for testing. It's much faster
- on setup:
    - truncate all tables
    - execute all cql to insert data
These methods were implemented in AbstractCassandraTest 

As I use a real cassandra, I don't know if it's a good idea, but I had to try to:
- use a random keyspace
- delete the keyspace at the end of execution

**Comment by raphaelbrugier** [comment]
This PR has been merged already but I like your approach.

Few questions that crossed my mind:

- Do you run the Cassandra cluster on a server or locally for each
developer?
- After generating the random name for the keyspace how do you inject it in
the Cassandra Configuration?
- Did you have to do like I did, by overriding this class for the tests?

**Comment by pascalgrimaud** [comment]
- locally for each developper
- the random name isn't done yet. I need to test this idea to allow Jenkins to run different jobs at the same time

**Comment by raphaelbrugier** [comment]
ok! Please let me know how you do it in the end ;)
