### ISSUE TITLE
[FEATURE] MSSQL Support

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#4518]
This was brought up in the mailing list and on Twitter - now that Microsoft has open-sourced their driver and released a docker image, we can support MSSQL as a first-class JHipster database type! 🎉   I set up a repository showing the [changes needed for MSSQL](https://github.com/ruddell/jhipster-mssql-example/commit/9b89e3281be7fa47ae6dc5611c97b046f7d2e2a4) (starting from MySQL).

You need to manually create the SQL Server database, I couldn't find any docker settings that create a database on startup.  Would this be an issue for our Travis tests?

Should I go ahead and create a PR for this?

**Comment by pascalgrimaud** [comment]
I'm not worried about creating database manually. You can launch some command with `docker exec -it`. We already did this in the past with Cassandra.

> Running this image requires 3.25 GB of RAM available for the container

I'm worried about this :-)

**Comment by PierreBesson** [comment]
And the reason it is so big is hilarious... They are actually shipping a big part of windows with it...
http://www.theregister.co.uk/2016/11/18/microsoft_running_windows_apps_on_linux/?mt=1479600840575

**Comment by deepu105** [comment]
We can still support it but skip travis test for it like we do for oracle

Thanks & regards,
Deepu
