### ISSUE TITLE
OAuth2 with MongoDB: Error removing access token during refresh

### ISSUE THREAD

**Issue by jaredsieling** [jhipster/generator-jhipster#4523]
##### **Overview of the issue**

When using OAuth2 authentication with MongoDB, if a "Refresh Token" request is made for an access token that has already been removed, it throws a 500 error and won't create a new access token.

##### **Reproduce the error**

Setup a project using OAuth2 authentication with MongoDB.  Authenticate at the endpoint `/oauth/token` to receive an access token.  Allow the access token to expire (you can shorten the expiration time down in `application.yml`).  **Submit a non-authenticating request**.  This is required because it will return an `invalid_token` response, but also delete the current access token from the DB.  Finally, make a request to refresh the token. 

The error occurs when `MongoDBTokenStore::removeAccessTokenUsingRefreshToken()` is called.  The reason is that the argument passed to `oAuth2AccessTokenRepository.delete()` is null, since the access token has already been removed.

##### **Suggest a Fix**

In `MongoDBTokenStore.java`, change 

```
@Override
    public void removeAccessTokenUsingRefreshToken(OAuth2RefreshToken refreshToken) {
        oAuth2AccessTokenRepository.delete(oAuth2AccessTokenRepository.findByRefreshToken(refreshToken.getValue()));
    }
```

to

```
@Override
    public void removeAccessTokenUsingRefreshToken(OAuth2RefreshToken refreshToken) {
        OAuth2AuthenticationAccessToken accessToken = oAuth2AccessTokenRepository.findByRefreshToken(refreshToken.getValue());
        if(accessToken != null) {
            oAuth2AccessTokenRepository.delete(accessToken);
        }
    }
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
{
  "generator-jhipster": {
    "baseName": "sample",
    "packageName": "com.sample",
    "packageFolder": "com/sample",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "gulp",
    "enableTranslation": false,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

**Comment by jdubois** [comment]
I'm the culprit here: I coded this part a long time ago, and indeed at that time I didn't how the refresh token worked...
As you have found a solution, would you do a PR for this?

**Comment by jaredsieling** [comment]
I can try to figure out how to do that...

**Comment by cbornet** [comment]
You can read [here](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-a-pull-request) to start
