### ISSUE TITLE
[FEATURE] Ability to generate JAX-RS resources instead of the Spring REST resource

### ISSUE THREAD

**Issue by ekougs** [jhipster/generator-jhipster#4524]
Even if Spring provides a nice library to make REST resources, it would be nice to be able to generate JAX-RS resources instead.
I use and really like jhipster, thx to all the contributors for the amazing work.

But when starting a project, I always find myself changing the generated resources to use JAX-RS.
Because I find the REST resources testing easier with the existing JAX-RS libraries and the JAX-RS API seems more intuitive and rich to me than the Spring one.
Pardon me if this has already been debated or already exists, but I didn't find anything in the documentation nor in this repository issues. 
The only issue about JAX-RS, is this one #814. But it is related to performance gain not user preference as I'm currently asking.

As it is already supported by Spring, would it be possible to create an option in the generator to use JAX-RS ?

**Comment by jdubois** [comment]
You mean using [Jersey](https://github.com/jersey/jersey/) like in this [great article](http://www.oracle.com/technetwork/articles/java/jersey-part1-159891.html) (yeah, I got paid for that)? Not sure it will change much from our Spring MVC REST API, so yes that should be possible to have an option for that.
I'm not sure much people would be interested by this, so here's my proposal:

- If anyone wants to do a PR with this as an option, he's most welcome
- I will do my best to merge this, but of course the burden of maintenance will then be on our shoulders, so if it's not a simple option I won't be able to do the merge
- And if nobody is interested in the next month, I'll close this

I'm also pinging @agoncal as I'm sure it will interest him (and we have lunch together this week, so we'll talk about it)

**Comment by ekougs** [comment]
It's true that once it is part of the project, it will be the contributors responsibility to maintain the feature, which can be quite cumbersome.
Do you think it would be easily feasible to do this as a third party module ?
I saw that there are modules for react for example which could be used instead of angular.

**Comment by gzsombor** [comment]
You can write a module, which register itself to run at every time a new entity is generated, or the whole app is re-generated, and you can do the necessary adjustments there, so yes, it's possible to write a third party module for this.

**Comment by gmarziou** [comment]
What is the equivalent of Springfox for JAX-RS? In clear how to generate swagger spec from JAX-RS?

**Comment by ekougs** [comment]
Given all these arguments and that this feature has never been asked despite the technology being around all the time, I really think writing a third party module seems a better alternative.
Some popular technologies has been introduced has 3rd party as well.
I close this issue.

**Comment by ekougs** [comment]
@gmarziou I think you can generate it by following this https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-JAX-RS-Project-Setup-1.5.X#hooking-up-swagger-core-in-your-application

**Comment by jdubois** [comment]
OK, we can also put it the other way around:

- Do a module with JAX-RS support
- If the module works well (lots of downloads), we can then integrate it into the main generator

**Comment by ekougs** [comment]
Yes it could be another perspective. I will certainly use the generator in my company in a near future to serve as a base for a bunch of projects. If jersey is chosen as the technology to implement REST resources, I think we will try to write the module and see if it gains some traction.
Thanks to you all for the prompt answers and advices.

**Comment by agoncal** [comment]
Funny. I've Tweeted about this : https://twitter.com/agoncal/status/799661003717931008. On 21 vote, 38% would like to have JAX-RS and 33% Spring (only 14% would like to have both). As you can see, it's not a *big* win in favour of JAX-RS, but people seem concern about it.

Due to my Java EE background, I love to see JPA / Bean Validation and @Inject (even if it's not CDI ;o)  in JHipster. Makes the code nice to read. But it's true that the only thing I miss is JAX-RS for the REST endpoints. 

So yes, I would be willing to help in this aspect... but first, Angular 2 ;o)

**Comment by cbornet** [comment]
@agoncal well, I think you can add the 15% "What is JAX-RS ?" trolls to the 33% Spring-only 😄 
Small issue when you switch to JAX-RS: you can't put the Pageable in the method and you need to pass the page, size, limit, sort as query parameters and build the PageRequest yourself.
Also, I found springfox much more advanced than swagger-jersey2-jaxrs (eg. I can output multiple spec/dockets with filtering for different purpose)
Eventually, even if it's a great lib, I'm not sure if there is a big gain with Jersey/JAX-RS when you don't come from Java EE...

**Comment by mohsenr7596** [comment]
+1
