### ISSUE TITLE
Update docker compose sub gen to use new JH console 2.0

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#4527]
@PierreBesson any reason this is not done yet? I tried to update manually but seems v 2.0.0 tags are not published to docker hub

**Comment by pascalgrimaud** [comment]
@deepu105 : see here https://hub.docker.com/r/jhipster/jhipster-console/tags/
It is still in beta. The tag is v2.0.0-beta

**Comment by deepu105** [comment]
Oh ok I missed that


Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
I want to do this soon but I'm waiting for elastalert to release a new version compatible with elasticsearch v5.

**Comment by jdubois** [comment]
OK so it's not released yet, that's all there is to say :-)
