### ISSUE TITLE
Jhipster 3.11 does not generate client app by default

### ISSUE THREAD

**Issue by timpamungkas** [jhipster/generator-jhipster#4528]
Just generate a new jhipster project using jhipster 3.11 and found some issue:

1. `yo jhipster` (no additional flag) does not generate client app. I'm pretty sure that before I update generator to 3.11, both server & client app were generated using single command.
I've noticed that during this phase, my yo-rc.json `skipClient` is `true`. Is this the expected behaviour?
Also skip-client-management is true.
Based on the [doc](https://jhipster.github.io/creating-an-app/) it should generate both server and client app, and also skip-client-management is false by default. 

2. Since client app does not generated, I run `yo jhipster:client` but found some funny code on command log. I use Windows 10 with Oracle JDK 8 installed.
The "funny code" on command prompt
```
errorReferenceError: ejs:14
    12|         },
    13|         "indicator": {
 >> 14| <%_ if (messageBroker === 'kafka') { _%>
    15|             "binders": "Message broker",
    16| <%_ } _%>
    17| <%_ if (applicationType === 'gateway') { _%>
```

3. I created a new entity "Employee". The server side is generated, but I didn't see any angular created. Running the apps and access it into localhost:8082 displays blank screen

I attached my yo-rc.json, command prompt (Windows) log
[Yo-rc and Log](https://github.com/jhipster/generator-jhipster/files/605784/spring-ms-employee.zip)

Thanks a lot

**Comment by timpamungkas** [comment]
I've also re-installed jhipster but does not solve the problem

**Comment by PierreBesson** [comment]
Well you chose the microservice application type so it is normal that it there is no client. Please read our docs on microservices.

**Comment by jdubois** [comment]
Please next time put your `.yo-rc.json` in the ticket, so we can see it directly (I'm mostly doing this with my phone while I take the bus/metro...).
So yes you selected a microservice, so that's normal you have no UI.
