### ISSUE TITLE
Menu item not active (highlighted) on entity detail page

### ISSUE THREAD

**Issue by chicobento** [jhipster/generator-jhipster#4533]
##### **Overview of the issue**

Menu item doesnt get (highlighted) on entity detail page. User can't figure out which section of the system he's at by looking at the menu.
This is a minor issue on ng1 entity sub-generator, found migrating an app to AdminLTE template.

##### **Motivation for or Use Case**

On entity list page, the menu item (eg. Bank Account), both "Entity" and "Bank Account" menus are highlighted. On an entity detail page, just the "Entity" menu is highlighted making it hard to figure-out whats the current section. 
Same happens with the User Management GUI.
While this bug cannot be easily detected on the default template due to the navbar dropdown menu, its more prominent on templates with left sidebar menu (eg. AdminLTE), 

##### **Reproduce the error**

1. Click on "User Management". Notice that both "Administration" and "User Management" menus are highlighted. 
2. Click on an user "view" button to go to user detail page. Notice that while "Administration" is still highlighted, "User Management" is not.

##### **Suggest a Fix**

State [_entity-detail_ is child of _entity_ state](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/src/main/webapp/app/entities/_entity-management.state.js#L63
). It should be child of  _<%= entityStateName %>_ state instead - similar to _entity.new_, _entity.delete_ and _entity.edit_ states.
Same for _user-management-detail_ state.
* Not sure if it could cause any collateral effect though. Haven't found any on basic tests.

This configuration is conflicting with the following directives `<li ng-class="{active: vm.$state.includes('entity')}"` and `<li ui-sref-active="active">`  on navbar.html menu hierarchy.

##### **JHipster Version(s)**

3.11.0. Reproducible on jhipster-sample-app.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

See jhipster-sample-app.

##### **Browsers and Operating System**

Ubuntu, Firefox

*edited to make sure fix suggestion more clear

**Comment by jdubois** [comment]
Same issue in our "angular 2" version, I'm correcting both.
