### ISSUE TITLE
Check compatibility between Angular 2 generated code and NG CLI

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#4534]
##### **Overview of the issue**

JHispter 4.x will have an Angular 2 implementation. It would be good to check the compatibility between the code generated by JHipster and NG CLI

##### **Motivation for or Use Case**

NG CLI allows to generate modules, components.... They are "empty shells" with no business code in it, but at least, they give the developper a working project. It would be good for JHipster to follow the NG CLI guide lines and coding style. This way, a developper could generate a full Angular 2 project with JHipster, and then, use NG CLI to add bits and pieces here and there.

**Comment by agoncal** [comment]
After installing [Angular CLI](https://github.com/angular/angular-cli) 1.x : 

```
$ npm install -g angular-cli
$ ng version
angular-cli: 1.0.0-beta.21
```
We create a new project with :
```
$ ng new myapp
```
This is what we get when generating an empty project : 
```
├── README.md
├── angular-cli.json
├── e2e
│   ├── app.e2e-spec.ts
│   ├── app.po.ts
│   └── tsconfig.json
├── karma.conf.js
├── package.json
├── protractor.conf.js
├── src
│   ├── app
│   │   ├── app.component.css
│   │   ├── app.component.html
│   │   ├── app.component.spec.ts
│   │   ├── app.component.ts
│   │   ├── app.module.ts
│   │   └── index.ts
│   ├── assets
│   ├── environments
│   │   ├── environment.prod.ts
│   │   └── environment.ts
│   ├── favicon.ico
│   ├── index.html
│   ├── main.ts
│   ├── polyfills.ts
│   ├── styles.css
│   ├── test.ts
│   ├── tsconfig.json
│   └── typings.d.ts
└── tslint.json
```

By default we see that Angular CLI creates config files for [Karma](https://karma-runner.github.io/1.0/index.html) and [Protractor](http://www.protractortest.org/#/) tests, as well as [TSLint](https://palantir.github.io/tslint/)

**Comment by agoncal** [comment]
Then, for example, we can create the `account` module and sub components with the following commands : 

```
$ ng generate module account
$ cd src/app/account/

$ ng generate component activate
$ ng generate component password
$ ng generate component register
$ ng generate component sessions
$ ng generate component settings

$ cd activate
$ ng generate service activate
```

This is what we get with NG CLI

```
├── account.module.ts
├── activate
│   ├── activate.component.css
│   ├── activate.component.html
│   ├── activate.component.spec.ts
│   ├── activate.component.ts
│   ├── activate.service.spec.ts
│   └── activate.service.ts
```

Which is quite identical from what we get with JHipster (notice the `spec` test files)

```
├── account.module.ts
├── account.state.ts
├── activate
│   ├── activate.component.html
│   ├── activate.component.ts
│   ├── activate.service.ts
│   └── activate.state.ts
```

**Comment by agoncal** [comment]
The generated component looks like this : 

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-activate',
  templateUrl: './activate.component.html',
  styleUrls: ['./activate.component.css']
})
export class ActivateComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }
}
```

The main difference with the code generated by JHipster is the relative path for the HTML template (and of course, the CSS file) : 

```
  // JHipster
  templateUrl: 'app/account/activate/activate.component.html'
  // Angular CLI
  templateUrl: './activate.component.html',
```

**Comment by agoncal** [comment]
The `AccountModule` is quite different though. This is what's get generated from Angular CLI :   

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AccountComponent } from './account.component';
import { ActivateComponent } from './activate/activate.component';
import { PasswordComponent } from './password/password.component';
import { RegisterComponent } from './register/register.component';
import { SessionsComponent } from './sessions/sessions.component';
import { SettingsComponent } from './settings/settings.component';

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [AccountComponent, ActivateComponent, PasswordComponent, RegisterComponent, SessionsComponent, SettingsComponent]
})
export class AccountModule { }
``` 

While the JHipster looks like this :  

```
import * as angular from 'angular';

import { upgradeAdapter } from '../upgrade_adapter';

import {
    Register,
    Activate,
    Password,
    PasswordResetInit,
    PasswordResetFinish,
    SessionsService,
    SessionsComponent,
    PasswordStrengthBarComponent,
    RegisterComponent,
    ActivateComponent,
    PasswordComponent,
    PasswordResetInitComponent,
    PasswordResetFinishComponent,
    SettingsComponent
} from './';

angular
    .module('jhipsterng2App.account', [
        'tmh.dynamicLocale',
        'ngResource',
        'ui.bootstrap'
    ])
    .directive('passwordStrengthBar', <angular.IDirectiveFactory> upgradeAdapter.downgradeNg2Component(PasswordStrengthBarComponent))
    .directive('jhiRegister', <angular.IDirectiveFactory> upgradeAdapter.downgradeNg2Component(RegisterComponent))
    .directive('activate', <angular.IDirectiveFactory> upgradeAdapter.downgradeNg2Component(ActivateComponent))
    .directive('password', <angular.IDirectiveFactory> upgradeAdapter.downgradeNg2Component(PasswordComponent))
    .directive('passwordResetInit', <angular.IDirectiveFactory> upgradeAdapter.downgradeNg2Component(PasswordResetInitComponent))
    .directive('passwordResetFinish', <angular.IDirectiveFactory> upgradeAdapter.downgradeNg2Component(PasswordResetFinishComponent))
    .directive('sessions', <angular.IDirectiveFactory> upgradeAdapter.downgradeNg2Component(SessionsComponent))
    .directive('settings', <angular.IDirectiveFactory> upgradeAdapter.downgradeNg2Component(SettingsComponent));

```

**Comment by agoncal** [comment]
So that you know, here the code generated by NG CLI

$ ng generate class myclass

```
export class Myclass {
}
```

$ ng generate component mycomponent

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-mycomponent',
  templateUrl: './mycomponent.component.html',
  styleUrls: ['./mycomponent.component.css']
})
export class MycomponentComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }
}
```

$ ng generate directive mydirective

```
import { Directive } from '@angular/core';

@Directive({
  selector: '[appMydirective]'
})
export class MydirectiveDirective {

  constructor() { }

}
```

$ ng generate enum myenum

```
export enum Myenum {
}
```

$ ng generate  interface myinterface

```
export interface Myinterface {
}
```

$ ng generate pipe mypipe

```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'mypipe'
})
export class MypipePipe implements PipeTransform {

  transform(value: any, args?: any): any {
    return null;
  }

}

```

$ ng generate service myservice

```
import { Injectable } from '@angular/core';

@Injectable()
export class MyserviceService {

  constructor() { }

}

```

**Comment by jdubois** [comment]
As Angluar CLI looks to be the only working and "official" generator at the moment, I think it's very important to be compatible with it, because that's what people are learning now.

Please note that it's still in beta, and it's just generating very simple, "hello world"-like applications and components.

- As the router is going to be a huge issue, I have started a [Twitter poll](https://twitter.com/java_hipster/status/809801106515705857) on this. We'll see what people prefer.
- Angular CLI can be configured using the [angular-cli.json file](https://github.com/angular/angular-cli/blob/master/packages/angular-cli/blueprints/ng2/files/angular-cli.json) configuration file. So if we generate that file correctly, I hope we can have something compatible.

There's quite a lot things to study here, so if anyone is interested in this ticket, we definitely need help.

**Comment by jdubois** [comment]
I got an `angular-cli.json` file which is kinda of working fine, I'll commit this in the next couple of days.

**Comment by jdubois** [comment]
So I have something very simple working:

- Generating components, etc, works, with 2 limitations:
  - Tests would be generated in the same folder as the components, and not in our `src/test` folder, so I had to disable them in the `angular-cli.json` file. I haven't found a way to configure that, this is something that should definitely be done.
  - CSS files were causing problems, the TS compiler doing an error saying that they should be configured in an "array" -> this is totally generated by Angular CLI, and this is indeed an array, so I can only think there is an error somewhere in Angular CLI. So I decided to "inline" the CSS, which isn't that bad, as this is how it's working elsewhere in JHipster (we have a customized Bootstrap for all components, and I think it's better for consistency)
- Other commands like `ng test` or `ng build` aren't working, or are not working very well -> we could make them work with a little help, but it doesn't make much sense as we already have the same commands inside JHispter. By the way, JHipster goes the Yeoman way of not "hidding" the underlying commands, which I find much better than Angular CLI.

**Comment by deepu105** [comment]
Please keep in mind being compatible with angular cli doesn't mean we
should support every command or do everything it does.

To me being compatible is letting users use angular cli to generate
components/pipes/services and our builds being able to work with that.
Thats all

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
Agreed @deepu105 , and this is already OK, that's why I closed this.

**Comment by geyuqiu** [comment]
ng generate component is not generating .spec.ts under test/javaScript/spec/..., will it be supported in the future ?

**Comment by pascalgrimaud** [comment]
@geyuqiu : plz don't comment old ticket ; `ng` is not compatible with JHipster, that's all
