### ISSUE TITLE
[FEATURE] Add a gulp task to serve files from dist folder (build)

### ISSUE THREAD

**Issue by ivan-dalmet** [jhipster/generator-jhipster#4535]
* **Overview of the request**

Add possibility, in development, to run BrowserSync with the files from the dist folder (after the build task).

* **Motivation for or Use Case** 

Add possibility too debug with build files.
Example: Images path who render properly in develop (serve task) but not in prod (build task).

* **Suggest a Fix** 

Add a task `serve:dist`

For that only 2 files need modifications: **[_gulpfile.js](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/_gulpfile.js)** and **[gulp/_serve.js](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/gulp/_serve.js)**

---

Old in **[_gulpfile.js](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/_gulpfile.js)**
```
[...]

gulp.task('serve', ['install'], serve);

[...]
```

New in **[_gulpfile.js](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/_gulpfile.js)**
```
[...]

gulp.task('serve', ['install'], serve.app);
gulp.task('serve:dist', ['build'], serve.dist);

[...]
```

---

Old in **[gulp/_serve.js](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/gulp/_serve.js)**
```
[...]

module.exports = function () {
   
    [...]

    browserSync({
        open: true,
        port: config.port,
        server: {
            baseDir: config.app,
            middleware: proxies
        }
    });

    gulp.start('watch');
};
```

New in **[gulp/_serve.js](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/gulp/_serve.js)**
```
[...]

var browserSyncInit = function (baseDir, watchEnabled) {
    baseDir = baseDir || config.app;
    watchEnabled = watchEnabled || true;

    [...]

    browserSync({
        open: true,
        port: config.port,
        server: {
            baseDir: baseDir,
            middleware: proxies
        }
    });

    if (watchEnabled) {
        gulp.start('watch');
    }
});

module.exports = {
    app: browserSyncInit(config.app, true),
    dist: browserSyncInit(config.dist, false)
};
```

**Comment by jdubois** [comment]
Looks interesting, and it looks like you know how to do it: could you do a PR for this?

**Comment by ivan-dalmet** [comment]
Ok, I will do the PR in the next few days.
(After the [Codeurs en Seine](http://www.codeursenseine.com/) event #freeAd #Normandy ^^)

**Comment by jdubois** [comment]
Thanks! We won't work on this at the moment, there is just too much work on Angular 2

**Comment by jdubois** [comment]
This definitely won't be done for Angular 2, as it's pretty sure we will remove Gulp in favor of Webpack.

That's why I'm closing this (we won't do it), but @ivan-dalmet if you want to do a PR, and if it's easy to merge, don't hesitate to do it, and I will merge it.
