### ISSUE TITLE
Application crash is you change the theme

### ISSUE THREAD

**Issue by rochakchauhan** [jhipster/generator-jhipster#4547]
##### **Overview of the issue**
The application Crashed when we try to add theme by editing src/main/webapp/index.html. The HTML throws the following error "An error has occured :-("

##### **Motivation for or Use Case**

We need to update the current theme while preserving the features like type-scripting.  However we can not even add a simple text in the HTML page. SOS

##### **Reproduce the error**

Just open "src/main/webapp/index.html", add a simple html/text in the file. Re-run the application and get an exception/error.

**Comment by atomfrede** [comment]
Can you describe what you are trying to do and how to reproduce your issue exactly?

**Comment by gmarziou** [comment]
Provide browser's console log.

**Comment by jdubois** [comment]
C'mon, there isn't even the version number... We just can't work like that.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
