### ISSUE TITLE
What should we do with non-transient value-based classes?

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4553]
Our Sonar analysis [available here](https://sonarqube.com/dashboard/?id=1054756) shows we often have the same "bug", which is `Make this value-based field transient so it is not included in the serialization of this class`.

To have an explanation on why value-based fields must not be transient [have a look here](http://blog.codefx.org/java/value-based-classes/). In fact, this isn't a bug "yet", it just might be in the future.

Now this is in fact a real problem:

- Our JPA entities need to be `Serializable` as it's part of the JPA spec, and as it's very likely people will put them in a cache (which can be distributed, or off heap)
- We obviously have dates in those entities, and classes from `java.time` are marked as value-based
- The solution proposed by Sonar, which is to make those fields `transient`, is not possible: those fields should not be `transient`, they should be saved in a database, and they should be available in a cache... You just don't resolve a problem by deleting it!

So I'm wondering what's the best solution is!

**Comment by jdubois** [comment]
So it looks like nobody has a solution :-(

This really looks like one those Sonar rules that shouldn't be there in the first place. It's probably OK in plain Java code, but when using Hibernate this just makes no sense to have the field transient.

**Comment by cbornet** [comment]
We could maybe have a page for configuring Sonar in which we explain why this rule (and probably others) must be deactivated ?

**Comment by jdubois** [comment]
In fact I'm starting to think we should have our own Sonar rules... The default rules are really not good for us.

**Comment by rzauel** [comment]
@SuppressWarnings("squid:S3437")

**Comment by felipeaffonso** [comment]
@rzauel thanks for giving the solution. I was worried about this issue, but in my case I don't actually need to Serialize the objects, since I'm using SpringData instead of JPA.

@jdubois JPA Specs says that you have some situations you have to implement Serializable, as you can see: https://stackoverflow.com/questions/2020904/when-and-why-jpa-entities-should-implement-serializable-interface. I don't know if it is you case.
