### ISSUE TITLE
cb() never called

### ISSUE THREAD

**Issue by jmellano** [jhipster/generator-jhipster#4557]
##### **Overview of the issue**
When I try to install jhipster project with 'npm i' command, I have a "cb() never called" error. 
If I remove  "generator-jhipster": "3.0.0" line in package.json it passed.

##### **Motivation for or Use Case**

I can't have a frontend working.

##### **Reproduce the error**

yo jhipster

##### **JHipster Version(s)**

3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

~~~
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "MonProjet",
    "packageName": "com.maboite.monProjet",
    "packageFolder": "com/maboite/monProjet",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
~~~

##### **Browsers and Operating System**

Chrome
Windows 10
PowerShell V5
node : 5.9.0
npm : 4.0.2

**Comment by pascalgrimaud** [comment]
Why do you try to use old JHipster version 3.0.0 instead of the latest 3.11.0 ?
You should update your node version to a LTS version too

**Comment by jmellano** [comment]
when I try to install : `npm install -g generator-jhipster` or  npm install -g generator-jhipster`@3.11.0` I've got the same error

**Comment by pascalgrimaud** [comment]
Reproduce your issue with node 5.9.0:
See the log here : https://travis-ci.org/pascalgrimaud/jhipster-travis-tester/builds/179076349
```
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm ERR! cb() never called!
```

Using node 6.9.1 and it works perfectly:
See https://travis-ci.org/pascalgrimaud/jhipster-travis-tester/builds/179078140

So update your node version and everything should be ok

**Comment by jdubois** [comment]
Yes, don't use unstable versions of Node!

**Comment by jmellano** [comment]
Thanks a lot !
I update to LTS 6.9.1 and yo 1.8.5 and it works perfectly !
