### ISSUE TITLE
Consider using PrimeNG as UI component lib

### ISSUE THREAD

**Issue by derehls** [jhipster/generator-jhipster#4567]
Have you considered using PrimeNG http://www.primefaces.org/primeng as UI Component Framwork? Bootstrap 4 still seems to need some time until a release and PrimeNG looks like they have a lot of components and a release version.

**Comment by deepu105** [comment]
No and sorry. We are not going to migrate another framework for this. We already have too much work. You can very well do a module for this if you are interested

**Comment by mfalzetta** [comment]
Hi @deepu105,

Im trying to include primeng on jHipster project but i have a error on dependences (quill).

Please, can you can guive me tip how to do this?

Sorry for any tire.

**Comment by jdubois** [comment]
Hi, this is the bug tracker, not the right place for this.

**Comment by sudheerj** [comment]
The editor component depends on quill package and it is not resolved by adding to vendor.ts file. Instead you can add resource path to html page.

The JHipster-PrimeNG module is under development and you can have a look on it

https://github.com/sudheerj/generator-jhipster-primeng
