### ISSUE TITLE
"npm test" on the generator is failing

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4569]
Running `npm test` on the current master fails with 3 errors, for example I have:

    AssertionError: src/main/java/com/mycompany/myapp/config/MicroserviceSecurityConfiguration.java, no such file or directory

And this definitely looks like a real error, not a Node version issue (btw, I'm using Node v6.9.1).

Are we still running `npm test` with Travis? There's something wrong here.

**Comment by pascalgrimaud** [comment]
@jdubois : strange, we still run npm test on Travis but it is with yarn
Look at the log here at line 344:
https://travis-ci.org/jhipster/generator-jhipster/jobs/179683912

I don't see any problem.
On my computer, all tests are OK

**Comment by jdubois** [comment]
Well, I have 11 fails on my machine... Quite strange, but as long as the CI passes the test, that's fine, I must have some env issue (I'm with dev versions of many tools, so it must be my fault).
