### ISSUE TITLE
Phantom.js tests failing, when the Websocket option is checked

### ISSUE THREAD

**Issue by ndjordjevic** [jhipster/generator-jhipster#457]
Created jhipster app with gulp.js option. Running gulp test one fails:

[20:21:32] Starting 'test'...
[20:21:32] Finished 'test' after 3.57 ms
INFO [karma]: Karma v0.12.16 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.7 (Mac OS X)]: Connected on socket fdgwi9crSmIi07P6dPWg with id 20022132
PhantomJS 1.9.7 (Mac OS X) Services Tests  AuthenticationSharedService should call backend on logout then call authService.loginCancelled FAILED
    Error: Unexpected request: GET protected/transparent.gif
    Expected GET app/rest/authenticate
        at $httpBackend (/Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1179)
        at sendReq (/Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:8249)
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:7980
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:11446
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:11446
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:11532
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:12556
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:12368
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1438
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/test/javascript/spec/servicesSpec.js:42
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/node_modules/karma-jasmine/lib/boot.js:117
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/node_modules/karma-jasmine/lib/adapter.js:171
        at http://localhost:9876/karma.js:189
        at http://localhost:9876/context.html:85
    Error: Unexpected request: GET views/main.html
    Expected GET app/rest/authenticate
        at $httpBackend (/Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1179)
        at sendReq (/Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:8249)
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:7980
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:11446
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:11446
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:11532
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:12556
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular/angular.js:12368
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1470
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/src/test/javascript/spec/servicesSpec.js:22
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/node_modules/karma-jasmine/lib/boot.js:117
        at /Users/ndjordjevic/Java/IdeaProjects/jhipster18-gulp/node_modules/karma-jasmine/lib/adapter.js:171
        at http://localhost:9876/karma.js:189
        at http://localhost:9876/context.html:85
PhantomJS 1.9.7 (Mac OS X): Executed 6 of 6 (1 FAILED) (0.004 secs / 0.054 secs)

**Comment by fontanellif** [comment]
When i try to run mvn -Pprod spring-boot:run i catch this error:

Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket efv9WlKx2MFU9eZQOn6q with id 32802763
DUMP: 'background-image: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(153, 255, 0); background-position: initial initial; background-repeat: initial initial; '
PhantomJS 1.9.8 (Mac OS X) Services Tests  Auth should call backend on logout then call authServerProvider.logout FAILED
	Error: Unsatisfied requests: GET /api\/account\?cacheBuster=\d+/
	    at /Users/fontanellif/jhipster-sql/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1559
	    at /Users/fontanellif/jhipster-sql/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1538
	    at /Users/fontanellif/jhipster-sql/src/test/javascript/spec/components/auth/authServicesSpec.js:45
	Error: Unsatisfied requests: GET /api\/account\?cacheBuster=\d+/
	    at /Users/fontanellif/jhipster-sql/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:1559
	    at /Users/fontanellif/jhipster-sql/src/test/javascript/spec/components/auth/authServicesSpec.js:32
PhantomJS 1.9.8 (Mac OS X): Executed 8 of 8 (1 FAILED) (0.009 secs / 0.257 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

I don't modify the code of the project, just create it with the jhipster  generator and then run the command.

**Comment by gmarziou** [comment]
@fontanellif Your issue seems different from the original one which is closed and was opened against JHipster 1.x while your is against 2.x, you should open a new issue and provide the options you selected while generating your application.
