### ISSUE TITLE
Unable to login to JHipster app deployed in Tomcat 6

### ISSUE THREAD

**Issue by duderoot** [jhipster/generator-jhipster#4570]
##### **Overview of the issue**

Deployed the JHipster generated app in Tomcat 6 Unable to login to the application using default login credentials(admin/admin). 

##### **Reproduce the error**
The problem is that the login try to make a POST on 
http://localhost:8080/jhipsterapp/oauth/token
but the app returns a 404
If I run in a fat jar then the login works wihtout problems

##### **JHipster Version(s)**
3.5.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "de.duderoot",
    "packageFolder": "de/duderoot",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "searchEngine": "no",
    "enableTranslation": true,
    "useSass": false,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling"
    ],
    "jhipsterVersion": "3.5.1",
    "serverPort": "8080",
    "applicationType": "monolith",
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "de"
    ]
  }
}

##### **Browsers and Operating System**

OS X El Capitan

**Comment by jdubois** [comment]
Please don't cross post, I already commented on your question at http://stackoverflow.com/questions/40857956/unable-to-login-to-jhipster-app-deployed-in-tomcat-6

**Comment by duderoot** [comment]
ok but the bug still exist and I was able to reproduce it. How should I proceed?

**Comment by jdubois** [comment]
I'll have a look at StackOverflow. Anyway, if you replace our app server by a very old Tomcat version, don't expect much help from the community!

**Comment by duderoot** [comment]
I don't have the problem, I was just want to help the guy which post the question and I am also a JHipster user and I like it a lot and that's why I want to help. So I just mage to reproduce the bug with the latest JHipster version. I remove my comment on StackOverflow since it was not correct.
I will push to my git the source where you can reproduce it
Can I open after that the this issue?

**Comment by jdubois** [comment]
The issue is that we will have the same question at 2 different places, then it's annoying for people to find an answer! That user is really annoying, even his question was wrong (I edited it on StackOverflow as he spelled "Timcat" instead of Tomcat), and he was not giving any details on his bug...
Then, if that's a JHipster bug you can reproduce, yes, let's open this ticket again. Are you it's not related to Tomcat 6?

**Comment by duderoot** [comment]
I just push my example app with wich we can reporoduce it.
https://github.com/duderoot/jhipster-4570
I have deploied it on a tomcat-6.0.48 and indeed the POST request is returning a 404 :(

**Comment by jdubois** [comment]
Are you deploying it to a specific Tomcat context?

**Comment by duderoot** [comment]
no I just copy the duderoot-0.0.1-SNAPSHOT.war.original to TOMCAT_HOME/webapps/duderoot-0.0.1-SNAPSHOT.war and then I start tomcat which explode the war to  duderoot-0.0.1-SNAPSHOT
and then I access the app under:
http://localhost:8080/duderoot-0.0.1-SNAPSHOT/#/

**Comment by ruddell** [comment]
You need to use a more recent version of Tomcat. Spring Boot does not support Tomcat 6 (Servlet 2.5), it requires Servlet 3 which can be found in Tomcat 7+ ([Tomcat and Servlet versions](http://tomcat.apache.org/whichversion.html)). If you need to use an older version of Tomcat, you can try to implement https://github.com/dsyer/spring-boot-legacy

**Comment by deepu105** [comment]
we never had support for tomcat6


Thanks & Regards,
Deepu
