### ISSUE TITLE
[FEATURE] API Rate Limits

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#4595]
##### **Overview of the issue**

For security reasons, it would be great if rate limiting would exist. Rate limiting reduces request that user can send in certain amount of time (for example, 1 request per second).

##### **Motivation for or Use Case**

Partial protection from the requests flood.

##### **Suggest a Fix**

At the moment I use the following code:

`RateLimit`

```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface RateLimit {

    //amount of requests that user can send in duration time
    int limit() default 1;

    long duration() default 1;

    TimeUnit unit() default TimeUnit.SECONDS;

}
```

by default, user could send 1 request per second.

`RateLimitAspect`

```

@Slf4j
@Aspect
@Component
public class RateLimitAspect {

    private Map<String, RateLimiter> rateLimiters = new HashMap<>();

    @Pointcut("@annotation(rateLimit)")
    private void annotatedWithRateLimit(RateLimit rateLimit) {
    }

    @Pointcut("@within(org.springframework.stereotype.Controller) || @within(org.springframework.web.bind.annotation.RestController)")
    private void controllerMethods() {
    }

    @Before(value = "controllerMethods() && annotatedWithRateLimit(rateLimit)", argNames = "joinPoint,rateLimit")
    public void rateLimitProcess(final JoinPoint joinPoint, RateLimit rateLimit) throws RateLimitException {
        HttpServletRequest request = null;
        for (Object arg : joinPoint.getArgs())
            if (arg instanceof HttpServletRequest) {
                request = (HttpServletRequest) arg;
                break;
            }
        if (request == null) {
            log.error("Method, annotated @RateLimit should has HttpServletRequest parameter.");
            return;
        }
        String ipAddress = Util.getIpAddress(request);
        String uri = request.getRequestURI();
        String key = ipAddress + "," + uri;
        rateLimiters.putIfAbsent(key, RateLimiter.create(rateLimit.limit(), rateLimit.duration(), rateLimit.unit()));
        RateLimiter rateLimiter = rateLimiters.get(key);
        if (rateLimiter != null && !rateLimiter.tryAcquire()) {
            log.warn("User with IP {} has exceeded the limit of requests. URI: {}", ipAddress, uri);
            throw new RateLimitException();
        }
    }

    @Scheduled(cron = "0 0/1 * * * ?")
    protected void clearRateLimiters() {
        rateLimiters = new HashMap<>();
    }

}

```

This aspect uses `google-common`. I didn't find better `RateLimiter`.

`Util::getIpAddress`

```
public static String getIpAddress(HttpServletRequest request) {
    String ip = request.getRemoteAddr();
    String[] ipHeaders = new String[] {
        "X-Real-IP", "X-Forwarded-For", "Proxy-Client_IP",
        "WL-Proxy-Client-IP", "HTTP_CLIENT_IP", "HTTP_X_FORWARDED_FOR"
    };
    for (String ipHeader : ipHeaders)
        if (ip != null && ip.length() > 0 && "unknown".equalsIgnoreCase(ip)) {
            ip = ipHeader;
            break;
        }
    return ip;
}
```
`RateLimitException`

```
@ResponseStatus(value = HttpStatus.TOO_MANY_REQUESTS)
class RateLimitException extends RuntimeException {

    private static final long serialVersionUID = -5649100415539733155L;

    RateLimitException() {
        super("Rate limit exceeded.");
    }

}
```

Now we can annotate any REST mapping method by `RateLimit`. If rate limit exceeded, `429 (Too many requests)` will returned. The only limitation is that annotated method must have `HttpServletRequest` parameter.

**Comment by jdubois** [comment]
This already exists in the gateway, did you see it?

**Comment by delverdev** [comment]
No, I use monolithic app. This suggestion could be applied to it.

**Comment by jdubois** [comment]
Yes, but it already exists on the gateway, with a Cassandra back-end. I coded it :-)

**Comment by deepu105** [comment]
You can generate the gateway and its a monolith with bells and whistles in a way. So you can use it with some tweaks. For monoliths this is not a generic use case hence I dont think we should do it

**Comment by PierreBesson** [comment]
However you could submit this as a tip on our website: https://github.com/jhipster/jhipster.github.io

**Comment by delverdev** [comment]
I would like to get your feedback about existing code before submitting a tip. Maybe it needs some edits.

**Comment by PierreBesson** [comment]
@delverdev ok, just push a sample project to github and I will test it later.

**Comment by jdubois** [comment]
Can you check the existing rate limiting code? I don't want to have 2 different implementations of the same feature, it would be better to join forces.

**Comment by delverdev** [comment]
@PierreBesson, [here it is](https://github.com/delverdev/ratelimiter).

**Comment by PierreBesson** [comment]
The ZuulFilter is specific to the Zuul gateway and not applicable to monoliths. In the JHipster microservice architecture, the gateway acts as a reverse proxy to the microservices and we have the rate limiting feature there.
However a configuration mechanism could be shared for both solutions. We could also share the core logic.

The real problem is that your solution cannot scale to more than one server as the rate limiting data is kept in memory. Perhaps the rate limiting data could be stored in database.

I really like your idea of creating a specific config builder like Spring Security 👍. This would be nice to have for our ZuulFilter too. @jdubois do you agree ?

**Comment by jdubois** [comment]
@PierreBesson I'm not sure it's going to add much to the current code... This part is left to be modified by the developer in the end, as you can have some business rules (for example some types of users might have higher limits than others).
