### ISSUE TITLE
Using Eureka or DNS on kubernetes for discovery service.

### ISSUE THREAD

**Issue by mootezbessifi** [jhipster/generator-jhipster#4605]
Hi all,
We have spring boot micro-service application running with jhipster and netflix OSS.
Now, i was trying to migrate it under kubernetes cluster, so i want to know what is the best practice: using DNS in stead of Eureka service (and how to do it) or keep Eureka running (and how also to do it).?
i tried the second alternative but Eureka pods won't to see each other as replicas. 
This is the issue on [stackoverflow](http://stackoverflow.com/questions/40905303/integrate-eureka-with-kubernetes-issue) and still waiting for util answers.

**Comment by jdubois** [comment]
Stackoverflow is the good place for questions, as this is not a bug (please follow the guidelines...).
And please don't cross post with Stackoverflow, it just makes things even harder.

**Comment by jdubois** [comment]
BTW you didn't add the `jhipster` tag on the Stackoverflow question...

**Comment by chijey** [comment]
spring-cloud-kuberntets
