### ISSUE TITLE
DateTime objects documented as object in api docs

### ISSUE THREAD

**Issue by brunnels** [jhipster/generator-jhipster#4614]
api docs for ZonedDateTime and other Date objects are documented as the full object.  The prior behavior was just a string.

This occured in JH 3.12.0 with #4438 removal of the following in SwaggerConfiguration.java

```
             .ignoredParameterTypes(java.sql.Date.class)
             .directModelSubstitute(java.time.LocalDate.class, java.sql.Date.class)
             .directModelSubstitute(java.time.ZonedDateTime.class, Date.class)
             .directModelSubstitute(java.time.LocalDateTime.class, Date.class)
```

**Comment by cbornet** [comment]
Strange. I had checked that it worked when upgrading to springfox 2.6.1. I'll have a look again.

**Comment by cbornet** [comment]
@brunnels I don't reproduce your issue. Please fill the issue with the proper info from the issue template.

**Comment by brunnels** [comment]
I'll try again with 2.6.1 springfox. It may have been that I reverted the
paging class and Pom to springfox 2.5.0 and then noticed this issue.

**Comment by brunnels** [comment]
Yes, that was the case.  This issue is not valid.  Sorry for the confusion.
