### ISSUE TITLE
Paging and sorting parameters missing from api docs

### ISSUE THREAD

**Issue by brunnels** [jhipster/generator-jhipster#4615]
With the update to springfox 2.6.1 in JH 3.12.0 paging and sorting parameters are missing from the api docs.  If I revert the changes from #4438 the issue is resolved.

**Comment by cbornet** [comment]
Yes. See https://github.com/springfox/springfox/issues/755

**Comment by jdubois** [comment]
@cbornet should this be closed?

**Comment by cbornet** [comment]
No, there is apparently an issue with springfox 2.6.1 so a workaround should be found. I'll have a look asap.

**Comment by brunnels** [comment]
I have verified the addition of the `@ApiParam` annotation resolves the issue.
