### ISSUE TITLE
Run gulp in jhipster docker image

### ISSUE THREAD

**Issue by lrkwz** [jhipster/generator-jhipster#4618]
I've noticed that gulp is installed into jhipster container.
Why don't you ```CMD ["gulp"]``` instead of tailing the log file?
The ```/home/jhipster/generator-jhipster/generators/server/templates/src/main/resources/banner-no-color.txt``` makes little sense to me since it is populated only when yo (```docker exec jhipster yo ...```) is run and in that case yo itself shows it's log.

As an alternative gulp could be run demonized in addition to tail

Having gulp run in background will help in providing a nice dockerized dev environment without the hassle to install locally all the required dependencies (npm, ...)

**Comment by pascalgrimaud** [comment]
I don't understand this issue.
The first time to run the Docker container, there is nothing, no generated project, so why running 'gulp' on nothing?

The goal of the `jhipster/jhipster` image is to provided all tools without installing anything on your computer. Then, every users can create their own docker image by using `jhipster/jhipster` as based image. So you can do something, if you need it:
```
FROM jhipster/jhipster
CMD ["gulp"]
```

**Comment by lrkwz** [comment]
[sorry it isn't an issue ... just an improvement suggestion]
Oh yes of course, any developer can extend the image as he/she likes.

The idea is to provide a dev environment without having the user to do anything except running the container.

Tailing the logfile is there only to keep the container "alive and kicking" otherwise it will simply terminate; running gulp will have exactly the same effect with the side effect of being useful: nice isn't it?

**Comment by pascalgrimaud** [comment]
Not sure about this. If you launch gulp and there is no gulpfile.js, gulp should failed with something like that:
```
╭─pgrimaud@pgrxps  ~/tmp  
╰─$ gulp
[22:51:28] Local gulp not found in ~/tmp
[22:51:28] Try running: npm install gulp
```

And if I'm not wrong, the container should exit with 1 as value status or something else
I need to test that

**Comment by PierreBesson** [comment]
I'm also against adding the `cmd gulp` at the end in the dockerfile. @lrkwz, It would not really achieve what you want and as @pascalgrimaud points out it would output errors in many cases.
Also I personally do not think of the JHipster docker image as a development environment, you will realize that it is very impractical to use it that way.

**Comment by lrkwz** [comment]
I'm now convinced about the errors: "cmd gulp" in the jhipster image is not
a good idea: sorry.

Althought using docker image as a dev environment is working well in my
experience: I have a project stick on 3.5.1 while I'm able to prototype
other apps using the latest version without worrying about "polluting" with
various dependencies.

Il 07/dic/2016 11:39, "Pierre Besson" <notifications@github.com> ha scritto:

**Comment by pascalgrimaud** [comment]
I agree with you:
>  I have a project stick on 3.5.1 while I'm able to prototype
other apps using the latest version without worrying about "polluting" with
various dependencies.

Anyway, thanks for your feedback :-)
I'm closing this, as we agree about not adding gulp in default CMD
