### ISSUE TITLE
Save button should be disabled when submitting form - user-management-dialog.html

### ISSUE THREAD

**Issue by mhavrlent** [jhipster/generator-jhipster#4622]
##### **Overview of the issue**

Save button should be disabled when submitting form on the following page: user-management-dialog.html

##### **Reproduce the error**

Create or edit user -> user management dialog will be displayed.
Press Save button -> save button should be disabled while saving.

##### **Suggest a Fix**

Change the following on line 109 in ./generators/client/templates/src/main/webapp/app/admin/user-management/_user-management-dialog.html file:
from: ng-disabled="editForm.$invalid || isSaving"
to: ng-disabled="editForm.$invalid || vm.isSaving"

##### **JHipster Version(s)**

```
generator-jhipster@3.12.0 /home/toor/git/generator-jhipster
└── (empty)

```

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.7.4

node: v6.9.1

npm: 3.10.6

bower: 1.8.0

gulp:
[09:37:00] CLI version 1.2.2

yeoman: 1.8.5

Docker version 1.12.3, build 6b644ec

**Comment by wmarques** [comment]
@ruddell why is this closed ? Is that already fixed ?

**Comment by ruddell** [comment]
Yeah the PR is https://github.com/jhipster/generator-jhipster/pull/4623, I had to manually close it since the `Fix` had 'for' in it
