### ISSUE TITLE
HikariCP key in metrics keeps changing

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#4627]
I was working on the Ng2 branch and noticed that the Hikaripool key in the metrics data `.gauges["HikariPool-3.pool.ActiveConnections"]` keeps shifting, we have `HikariPool-1` in code but I was getting 2 and 3 each time there was some hot reload happening.

I'm pretty sure that its happening on master as well (didnt check though)

we need to see if its an upline bug and how to workaround

cc @jdubois

**Comment by jdubois** [comment]
I think there were corrections here, both in HikariCP and Cache metrics, when we upgraded to JCache. That  was done in the master branch and should be ported to the ng2 branch.

**Comment by jdubois** [comment]
I've tested this and this is indeed an issue with HikariCP.

This isn't really our fault, for me it's a bug in HikariCP when using hot reload.

We could do a trick on the client side to solve this, but for me we should leave it this way:

- This is an HikariCP bug, they will probably correct it at some point, we should better wait for this
- This is only happening with hot reload in dev mode, and this metric is mostly (only?) interesting in prod mode, so this really isn't a big problem for us

-> for those reasons I'm closing this, I hope @deepu105 you are fine with this
