### ISSUE TITLE
Prepare for Yeoman 1.0

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4631]
As mentioned [here](https://github.com/yeoman/generator/issues/766#issuecomment-265658238) Yeoman 1.0 will soon be released.
There is a [blog post](https://github.com/yeoman/yeoman.github.io/blob/a87b3452377b1b232145f910d6a945804bf84d2c/app/_posts/blog/2016-12-03-hello-generator-1.0.md) describing the upgrade process and new features, we should follow it.

**Comment by jdubois** [comment]
Yeoman 1.0 is released: http://yeoman.io/blog/hello-generator-1.0.html

**Comment by jdubois** [comment]
Couple of issues here:

- I don't see the new release on https://www.npmjs.com/package/yeoman-generator - @SBoudrias is this normal? I thought it was released?
- I don't understand how the new `composeWith` API works when you use `args`, like [here](https://github.com/jhipster/generator-jhipster/blob/v3.12.1/generators/app/index.js#L323). Then I'm with release `0.24.2` (see point above), so maybe I need to wait until 1.0 is available

**Comment by SBoudrias** [comment]
@jdubois it's properly release to npm, I don't know why it's not showing as the latest release though... Looks like a bug.

About args and options, they've been merged to expose a single API. You access both arguments and options with `this.options.name` and you pass them the same way using `composeWith`.

```js
this.composeWith(require.resolve('generator-x'), {
  optionName: 'foo',
  argName: 'bar'
});
```

That being said, if the generator being composed (`generator-x` in the prev example) doesn't use v1.0, then you'll need to pass them as:

```js
this.composeWith(require.resolve('generator-x'), {
  optionName: 'foo',
  arguments: ['bar']
});
```

**Comment by jdubois** [comment]
Thanks a lot @SBoudrias !

- For the NPM website, yes they often take some time to update, I have the issue all the time with JHipster!
- For the `composeWith` then that's a serious issue for us. We "compose" our sub-generator (and that's OK), but we now have [28 modules](https://jhipster.github.io/modules/marketplace/#/list) done by other people, and they're all going to break. I have no idea how we can handle that use case!!! Maybe we should let the module upgrade first, and let them do this in the next 2-3 months?

**Comment by gzsombor** [comment]
Probably we should request to the module developers to have a 'jhipster-4.0' tag in their package definitions, to mark them compatible with JHipster 4 / Yeoman 1

**Comment by jdubois** [comment]
@gzsombor yes but that would mean we start JHipster 4 with 0 available module...

**Comment by gzsombor** [comment]
As lot's of modules have not updated since January of 2016, I bet, they are incompatible, no matter if we list them, or not. Especially because the introduction of Angular 2. At least, they need to updated to declare if they can handle Angular 2, or not

**Comment by jdubois** [comment]
Oh, that's a very good point!!! Angular 2 breaks everything, anyway!
So OK, let's do this!

**Comment by deepu105** [comment]
@jdubois I think for JHipster 4.0 its not mandatory to use yeoman 1.0 as this is internal we cant do it at any point later as well

**Comment by jdubois** [comment]
Oh you are correct @deepu105 and JHipster 4 is already late & complex to release... So let's do it, but not right now, as we don't have the time. Maybe it will be in a minor release, maybe for JHipster 5.

**Comment by SBoudrias** [comment]
@jdubois can you explain why you think they'll break? The composition should stay compatible across versions (that is: 1.0 composing with older versions and older generators composing with 1.0)

**Comment by jdubois** [comment]
Oh I didn't understand this @SBoudrias ! OK I'll reopen this, let me try this out!

**Comment by jdubois** [comment]
I've tried it out, and there are more stuff that changed, including how inheritance works, see http://yeoman.io/blog/cleanup.html

I have no idea how all this works, and upgrading seems long and painful as we have a lot of code relying on this.

So for me we'll stay on an older version, until:

- We have a blocking issue or a new feature that forces us to upgrade
- Someone is interested in spending time on this (I can't, we already have a lot of work preparing JHipster 4, and my nights and week-ends are limited...)

**Comment by SBoudrias** [comment]
@jdubois the inheritance is still only JavaScript, so `utils.inherits` will still works. We only recommend using standard es6 classes from now on (`class extends Generator {}`); but we're still exporting a standard JS class you can extend in any way you prefer.

**Comment by jdubois** [comment]
OK, but still this is totally failing and I have no idea why.

**Comment by SBoudrias** [comment]
@jdubois oh, we changed the exports. before you had `

```js
// Before
var Base = require('yeoman-generator').Base;

// After
var Base = require('yeoman-generator');
```

**Comment by jdubois** [comment]
OK I'll have another look during Christmas...

**Comment by SBoudrias** [comment]
@jdubois let me know if you hit any hurdles that are hard to overcome. I'm all in to help you update as easily as possible.

**Comment by jdubois** [comment]
Oh that's very kind of you!!

**Comment by deepu105** [comment]
@jdubois Its doable and I did have some ideas on how to improve our base. I
would like to do this after our ng2 release. And I already migrated most of
the file writing into our own metadata format so upgrading to 1.0 should be
easy. The only tough part is that we use compose a lot and that too in ways
which yeoman has not documented. I think im partly to blame here. But i
would like to improve that and make it less complex.

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
OK... I just tried it again, and I just have no idea what I'm doing :-(

**Comment by deepu105** [comment]
Let me do it later :) I have already started something on a branch but
didnt proceed as I didnt have time


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
you can keep the ticket open so that I dont forget later


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
OK, I pushed my current code to https://github.com/jhipster/generator-jhipster/tree/migration-to-yeoman-1.0 but this is clearly not working!

**Comment by deepu105** [comment]
Ok ill take a look later

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
I corrected a few bugs, but it's still not complete yet - I've updated the https://github.com/jhipster/generator-jhipster/tree/migration-to-yeoman-1.0 branch with it.

All of my errors come from the fact that when I do a "composeWith", I'm losing the current context, so it doesn't look for the templates in the correct directories....

**Comment by deepu105** [comment]
Julien, ill work on this when I have some time. Anyway its not very urgent
as it doesn't add any new features or fix so we can take our time. I would
also like to use more es6 features for this like converting the index.js
files and base into es6 classes etc.

Thanks & regards,
Deepu

On 23 Feb 2017 11:12 p.m., "Julien Dubois" <notifications@github.com> wrote:

I corrected a few bugs, but it's still not complete yet - I've updated the
https://github.com/jhipster/generator-jhipster/tree/migration-to-yeoman-1.0
branch with it.

All of my errors come from the fact that when I do a "composeWith", I'm
losing the current context, so it doesn't look for the templates in the
correct directories....

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/4631#issuecomment-282065265>,
or mute the thread

**Comment by deepu105** [comment]
@SBoudrias I'm working on this migration and I'm facing a final hurdle. When using the new yarnInstall method. I have raised a ticket here https://github.com/yeoman/generator-generator/issues/179
Any pointers?

**Comment by deepu105** [comment]
@jdubois so its done. I have fixed all the bugs and the builds should be green now.

There is one thing though and I have no idea what to do for that may be @SBoudrias could be able to help

The file writing seems to be much slower now (around 5 times slower). We haven't changed anything we just switched to `fs.copyTpl` and `fs.copy` instead of the `template` and `copy` method provided by the generator. 

I'm not sure what to do here could it be an issue with mem-fs editor?

**Comment by jdubois** [comment]
Great job!!!!
We need to merge this ASAP as this will cause merge conflicts.

**Comment by deepu105** [comment]
lets wait for the tests to be green

**Comment by deepu105** [comment]
@SBoudrias So here is the performance numbers


**With yeoman 1.x**

Each log is for writing an array of files which calls the `fs.copyTpl` and `fs.copy` methods by looping the array here https://github.com/jhipster/generator-jhipster/blob/migration-to-yeoman-1.0/generators/generator-base.js#L1675

```
DEBUG! Time taken to write files: 5330ms
DEBUG! Time taken to write files: 587ms
DEBUG! Time taken to write files: 682ms
DEBUG! Time taken to write files: 412ms
DEBUG! Time taken to write files: 723ms
DEBUG! Time taken to write files: 414ms
DEBUG! Time taken to write files: 769ms
DEBUG! Time taken to write files: 371ms
DEBUG! Time taken to write files: 764ms
DEBUG! Time taken to write files: 376ms
DEBUG! Time taken to write files: 778ms
DEBUG! Time taken to write files: 507ms
DEBUG! Time taken to write files: 795ms
DEBUG! Time taken to write files: 516ms
DEBUG! Time taken to write files: 838ms
DEBUG! Time taken to write files: 401ms
DEBUG! Time taken to write files: 839ms
DEBUG! Time taken to write files: 479ms
DEBUG! Time taken to write files: 855ms
DEBUG! Time taken to write files: 420ms
DEBUG! Time taken to write files: 875ms
DEBUG! Time taken to write files: 550ms
DEBUG! Time taken to write files: 874ms
DEBUG! Time taken to write files: 499ms
DEBUG! Time taken to write files: 894ms
DEBUG! Time taken to write files: 579ms
DEBUG! Time taken to write files: 911ms
DEBUG! Time taken to write files: 443ms
DEBUG! Time taken to write files: 932ms
DEBUG! Time taken to write files: 531ms
DEBUG! Time taken to write files: 953ms
DEBUG! Time taken to write files: 612ms
DEBUG! Time taken to write files: 983ms
DEBUG! Time taken to write files: 706ms
DEBUG! Time taken to write files: 995ms
DEBUG! Time taken to write files: 812ms
DEBUG! Time taken to write files: 1028ms
DEBUG! Time taken to write files: 694ms
DEBUG! Time taken to write files: 1058ms
DEBUG! Time taken to write files: 778ms
DEBUG! Time taken to write files: 1073ms
DEBUG! Time taken to write files: 863ms
DEBUG! Time taken to write files: 1129ms
```

**With Yeoman 0.x**

Its the same method as above but this calls `template` and `copy` methods from generator here https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L1692

```
Time taken to write files: 140ms
Time taken to write files: 55ms
Time taken to write files: 30ms
Time taken to write files: 35ms
Time taken to write files: 40ms
Time taken to write files: 39ms
Time taken to write files: 22ms
Time taken to write files: 35ms
Time taken to write files: 34ms
Time taken to write files: 27ms
Time taken to write files: 39ms
Time taken to write files: 34ms
Time taken to write files: 37ms
Time taken to write files: 35ms
Time taken to write files: 33ms
Time taken to write files: 27ms
Time taken to write files: 32ms
Time taken to write files: 35ms
Time taken to write files: 35ms
Time taken to write files: 24ms
Time taken to write files: 35ms
Time taken to write files: 24ms
Time taken to write files: 15ms
Time taken to write files: 25ms
Time taken to write files: 16ms
Time taken to write files: 25ms
Time taken to write files: 15ms
Time taken to write files: 21ms
Time taken to write files: 14ms
Time taken to write files: 25ms
Time taken to write files: 14ms
Time taken to write files: 25ms
Time taken to write files: 13ms
Time taken to write files: 29ms
Time taken to write files: 15ms
Time taken to write files: 26ms
Time taken to write files: 18ms
Time taken to write files: 20ms
Time taken to write files: 19ms
Time taken to write files: 26ms
Time taken to write files: 16ms
Time taken to write files: 30ms
Time taken to write files: 13ms
```

The tasks are the same and you can see the time taken to write files are more than 10 times than the previous version :(

**Comment by SBoudrias** [comment]
@deepu105 could you share code example of how you got those numbers?

**Comment by deepu105** [comment]
@SBoudrias it was from the below branches
Yeoman 1.x : https://github.com/jhipster/generator-jhipster/tree/migration-to-yeoman-1.0
Yeoman 0.x : https://github.com/jhipster/generator-jhipster/tree/master

In both branches we have the method `writeFilesToDisk` [this](https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L1692) which iterates through the files and calls different methods to write them to disk. In master branch the method outputs the 2nd set of numbers from above. And in master branch we use `generator.template` and `generator.copy` methods to write most of the files, there are some custom methods where we manually write files after some processing as well. In the new migration branch we used `fs.copyTpl` and `fs.copy` instead of the deprecated methods and now the numbers are much much higher. Please note that I'm not sure if its related to the `fs` methods as the same methods when used in the master branch with yeoman 0.x works as fast as the deprecated `template` and `copy` methods so this is something thats happening only when using yeoman 1.x

**Comment by deepu105** [comment]
I have drilled down to the exact line causing the issue its below
```
_this.fs.copyTpl(_this.templatePath(template), _this.destinationPath(destination), _context, options);
```

So it seems definetely something to do with implementation of `copyTpl` method. As a workaround I have implemented my own simple copy template and this has reduced the performance impact and now its close to master the exact commit is [here](https://github.com/jhipster/generator-jhipster/commit/5c3aacb427f02d8c42e4193bc9f4c142e0b867df)
```
    template(source, destination, generator, options = {}, context) {
        const _this = generator || this;
        const _context = context || _this;
        ejs.renderFile(_this.templatePath(source), _context, options, (err, res) => {
            if(!err) {
                _this.fs.write(_this.destinationPath(destination), res);
            } else {
                _this.error(`Copying template ${source} failed. [${err}]`);
            }
        });
    }
```

**Comment by SBoudrias** [comment]
@deepu105 mem-fs-editor does glob matching, and might be expensive if it can't figure out the type of the source target immediately. My guess is either of these things is happening.

**Comment by deepu105** [comment]
@SBoudrias probably, but looking at the source of `copyTpl` method it seems it calls the `fs.copy` method internally which does the glob part. I'm still using the `fs.copy` method and it doesnt seem to cause that much of a difference. but not using the `copyTpl` method shows massive difference. Hope it helps

**Comment by deepu105** [comment]
@jhipster/developers @jhipster/hipsters please note that with this upgrade some modules might break hence modules will need to update how it composes this generator and also modules will need to update to yeoman 1.x to avoid edge cases

**Comment by jdubois** [comment]
Yes we will release the next version as 5.1.x to show that, and we'll need to discuss the new opportunities: I see you can now use a parser as a template parameter, we could have a Java parser that would allow more advanced use cases.

**Comment by deepu105** [comment]
@jdubois there are some javadoc issues and some more linting that I would like to do. I have sent a mail on our forum regarding this.

Regarding parser I hope you are talking about the gulp pipe transform support?

**Comment by deepu105** [comment]
@jdubois Btw it might not break all modules. I tested some of mine and they worked so may be we can test few more to see if they work and in that case we can still release it as a minor version @jhipster/developers  could you please test your modules with master and give feedback?

**Comment by jdubois** [comment]
@deepu105 no I'm talking about the tip at the end of http://yeoman.io/authoring/file-system.html -> we could have a Java AST parser (or maybe our own, if none exists), which could ease editing existing files. For example we could have a very basic one that handles package imports, which is just getting crazy in our current code.

**Comment by deepu105** [comment]
Oh that. Its not new this is parsing the js or html content, there are lot
of libraries for that and ofcourse for java files there should be. I
already do html file parsinv in one of the modules. Yes we might find uses
for that

Thanks & regards,
Deepu
