### ISSUE TITLE
Cannot log into generated application

### ISSUE THREAD

**Issue by razorvind** [jhipster/generator-jhipster#4645]
##### **Overview of the issue**
I use jhipster 1.8.5 and jhipster generator 3.12.1
I generated application:
- session based with spring security
- MySQL database
- spring web socket
- all other options by default
- no entities (as I'm interested in the web socket implementation)

I've create database and user in MySQL as:
`create database wsnew;

CREATE USER wsnew@'%' IDENTIFIED BY '1111';
GRANT ALL ON wsnew.* TO wsnew@'%';
FLUSH PRIVILEGES;`

Here is my application-dev.yml config:
`        url: jdbc:mysql://localhost:3306/wsnew?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: wsnew
        password: 1111`

Here is the log from IDEA console:
2016-12-11 02:32:04.062 DEBUG 8032 --- [ XNIO-2 task-58] m.m.s.CustomPersistentRememberMeServices : Remember-me cookie detected
Hibernate: select persistent0_.series as series1_3_0_, persistent0_.ip_address as ip_addre2_3_0_, persistent0_.token_date as token_da3_3_0_, persistent0_.token_value as token_va4_3_0_, persistent0_.user_id as user_id6_3_0_, persistent0_.user_agent as user_age5_3_0_, user1_.id as id1_4_1_, user1_.created_by as created_2_4_1_, user1_.created_date as created_3_4_1_, user1_.last_modified_by as last_mod4_4_1_, user1_.last_modified_date as last_mod5_4_1_, user1_.activated as activate6_4_1_, user1_.activation_key as activati7_4_1_, user1_.email as email8_4_1_, user1_.first_name as first_na9_4_1_, user1_.lang_key as lang_ke10_4_1_, user1_.last_name as last_na11_4_1_, user1_.login as login12_4_1_, user1_.password_hash as passwor13_4_1_, user1_.reset_date as reset_d14_4_1_, user1_.reset_key as reset_k15_4_1_ from jhi_persistent_token persistent0_ left outer join jhi_user user1_ on persistent0_.user_id=user1_.id where persistent0_.series=?
2016-12-11 02:32:04.071 DEBUG 8032 --- [ XNIO-2 task-58] m.m.s.CustomPersistentRememberMeServices : No persistent token found for series id: 0Z8DGHQHJy+kJ+6nZ2xsmg==
2016-12-11 02:32:04.074 DEBUG 8032 --- [ XNIO-2 task-58] m.m.s.CustomPersistentRememberMeServices : Cancelling cookie
2016-12-11 02:32:04.076 DEBUG 8032 --- [ XNIO-2 task-58] c.m.myapp.aop.logging.LoggingAspect      : Enter: com.mycompany.myapp.web.rest.ProfileInfoResource.getActiveProfiles() with argument[s] = []
2016-12-11 02:32:04.077 DEBUG 8032 --- [ XNIO-2 task-58] c.m.myapp.aop.logging.LoggingAspect      : Exit: com.mycompany.myapp.web.rest.ProfileInfoResource.getActiveProfiles() with result = com.mycompany.myapp.web.rest.ProfileInfoResource$ProfileInfoResponse@5f89944a
2016-12-11 02:32:04.079 DEBUG 8032 --- [ XNIO-2 task-63] m.m.s.CustomPersistentRememberMeServices : Remember-me cookie detected
Hibernate: select persistent0_.series as series1_3_0_, persistent0_.ip_address as ip_addre2_3_0_, persistent0_.token_date as token_da3_3_0_, persistent0_.token_value as token_va4_3_0_, persistent0_.user_id as user_id6_3_0_, persistent0_.user_agent as user_age5_3_0_, user1_.id as id1_4_1_, user1_.created_by as created_2_4_1_, user1_.created_date as created_3_4_1_, user1_.last_modified_by as last_mod4_4_1_, user1_.last_modified_date as last_mod5_4_1_, user1_.activated as activate6_4_1_, user1_.activation_key as activati7_4_1_, user1_.email as email8_4_1_, user1_.first_name as first_na9_4_1_, user1_.lang_key as lang_ke10_4_1_, user1_.last_name as last_na11_4_1_, user1_.login as login12_4_1_, user1_.password_hash as passwor13_4_1_, user1_.reset_date as reset_d14_4_1_, user1_.reset_key as reset_k15_4_1_ from jhi_persistent_token persistent0_ left outer join jhi_user user1_ on persistent0_.user_id=user1_.id where persistent0_.series=?
2016-12-11 02:32:04.086 DEBUG 8032 --- [ XNIO-2 task-63] m.m.s.CustomPersistentRememberMeServices : No persistent token found for series id: 0Z8DGHQHJy+kJ+6nZ2xsmg==
2016-12-11 02:32:04.086 DEBUG 8032 --- [ XNIO-2 task-63] m.m.s.CustomPersistentRememberMeServices : Cancelling cookie
2016-12-11 02:32:04.088 DEBUG 8032 --- [ XNIO-2 task-63] c.m.myapp.aop.logging.LoggingAspect      : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Sun Dec 11 02:32:04 MSK 2016, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2016-12-11 02:32:04.089 DEBUG 8032 --- [ XNIO-2 task-63] c.m.myapp.aop.logging.LoggingAspect      : Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
2016-12-11 02:32:04.089 DEBUG 8032 --- [ XNIO-2 task-63] c.m.m.s.Http401UnauthorizedEntryPoint    : Pre-authenticated entry point called. Rejecting access

Here is the log form browser:
http://localhost:9000/api/authentication?cacheBuster=1481414325497 Failed to load resource: the server responded with a status of 403 (Forbidden)
##### **Motivation for or Use Case**
I cannot login in generated application, so I can't get jhipster's features while developing my application.

##### **Reproduce the error**
1) Generate application with latest version of jhipster an jhipster's generator:
- session based with spring security
- MySQL database
- spring websocket
- all other options by default
- run application and try to log in as admin/admin

2) create database and user in MySQL as:
`create database wsnew;

CREATE USER wsnew@'%' IDENTIFIED BY '1111';
GRANT ALL ON wsnew.* TO wsnew@'%';
FLUSH PRIVILEGES;`

3) update application-dev.yml config as:
`        url: jdbc:mysql://localhost:3306/wsnew?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: wsnew
        password: 1111`

##### **Related issues**
I didn't find any related issues.

##### **Suggest a Fix**
I guess I do something wrong as this bug is very obvious - and it is impossible that no one reported it.

##### **JHipster Version(s)**
generator-jhipster@3.12.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.1",
    "baseName": "wsnew",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "a8547d84e1c37605ae3ddc12afca1280e2e65413",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
no entities

##### **Browsers and Operating System**
Windows 7
Chrome Version 54.0.2840.99 m

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)

**Comment by pascalgrimaud** [comment]
Is this `.yo-rc.json` correct ? I saw `"websocket": false,` in your configuration

Anyway, I change to `"websocket": "spring-websocket"`, generate a project with your config and I don't have any problem to log into the application

What is your mysql version?

**Comment by jdubois** [comment]
From what I see in your log you have a `remember me` cookie detected, so you did manage to log in at some point.
But that cookie is invalidated because its id isn't in the database anymore: this is probably because you dropped your database and created a new one.

**Comment by razorvind** [comment]
**pascalgrimaud**, thanks for quick reply!
You are correct - I missed web socket.
So I re-generated the application. 
Here is .yo-rc.json:
`{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.1",
    "baseName": "wsnew",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "525a030fd663ddb264bf7d07d37fc34ac0fb6a52",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}`

MySQL version is "5.7.13"

I still cannot login.
Here is what I have in application-dev.yml:
`    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/wsnew?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: wsnew
        password: 1111
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
            hibernate.javax.cache.uri: ${spring.cache.jcache.config}
            hibernate.cache.region.factory_class: com.mycompany.myapp.config.jcache.SpringCacheRegionFactory`

And here is what I have for another application generated by jhipster (2.26.2) - where I can login into the application:
`    datasource:
        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/wstest?useUnicode=true&characterEncoding=utf8
        name:
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        show_sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory`

**Comment by razorvind** [comment]
**jdubois**, thanks for quick reply!
Sorry, but I didn't manage to log into the application generated as I described.
By the way, I use IDEA 2016.1.2

**Comment by jdubois** [comment]
@razorvind oh I understand you had another application, so the cookie must have been set by this other app, and that's normal then

**Comment by jdubois** [comment]
I just tried it with your `.yo-rc.json`, using JHipster 3.12.1, and running with our provided MySQL Docker image. I had no problem at all to log in.
So I'm sorry but I can't reproduce, from what you tell it looks related to your database, could you try using our Docker image? `docker-compose -f src/main/docker/mysql.yml up -d`

**Comment by razorvind** [comment]
@jdubois ok, I'll try docker. But today I've generated the same application with H2 in memory db instead of MySQL on disk - so I have the same errors while trying to log in:
`2016-12-12 23:19:43.737 DEBUG 12428 --- [ XNIO-2 task-51] m.m.s.CustomPersistentRememberMeServices : No persistent token found for series id: 0Z8DGHQHJy+kJ+6nZ2xsmg==
2016-12-12 23:19:43.737 DEBUG 12428 --- [ XNIO-2 task-51] m.m.s.CustomPersistentRememberMeServices : Cancelling cookie
2016-12-12 23:19:43.758 DEBUG 12428 --- [ XNIO-2 task-51] c.m.myapp.aop.logging.LoggingAspect      : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Mon Dec 12 23:19:43 MSK 2016, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@b364: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2016-12-12 23:19:43.759 DEBUG 12428 --- [ XNIO-2 task-51] c.m.myapp.aop.logging.LoggingAspect      : Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
2016-12-12 23:19:43.760 DEBUG 12428 --- [ XNIO-2 task-51] c.m.m.s.Http401UnauthorizedEntryPoint    : Pre-authenticated entry point called. Rejecting access
2016-12-12 23:19:43.783 DEBUG 12428 --- [ XNIO-2 task-54] c.m.myapp.aop.logging.LoggingAspect      : Enter: com.mycompany.myapp.web.rest.ProfileInfoResource.getActiveProfiles() with argument[s] = []
2016-12-12 23:19:43.787 DEBUG 12428 --- [ XNIO-2 task-54] c.m.myapp.aop.logging.LoggingAspect      : Exit: com.mycompany.myapp.web.rest.ProfileInfoResource.getActiveProfiles() with result = com.mycompany.myapp.web.rest.ProfileInfoResource$ProfileInfoResponse@fd8253c`

**Comment by ruddell** [comment]
@razorvind Those logs are from visiting the home page of a fresh app, there's nothing about you attempting to login.... If you tried, it would say `Interactive login attempt was unsuccessful.`

**Comment by pascalgrimaud** [comment]
Same here, I can't reproduce too.
Maybe try in private navigation with your browser?

**Comment by jdubois** [comment]
Hang on, we've already been through this: @razorvind do you have an antivirus or an add blocker? We've already had issues because of misconfigured Chrome plugins, etc... Could you try using our [Devbox](https://github.com/jhipster/jhipster-devbox) and see if you reproduce?

**Comment by razorvind** [comment]
I really used AdBlock and Symantec Endpoint Protection (cant' turn it off due to company policy).
So I cannot login in Chrome while turning off the AdBlock plugin.
But the good news is I managed to login with Firefox 50.0.2
Seems like there some problem with my Chrome like @jdubois said.

Actually the reason of my investigation - some WebSocket errors, so I've updated jhipster and generated new application to make sure I didn't miss anything. 
The error I'm talking about is "WebSocket connection to 'ws://localhost:9000/websocket/tracker/998/10vfea54/websocket' failed: Connection closed before receiving a handshake response" - and seems like it Browser Sync issue https://github.com/BrowserSync/browser-sync/issues/780
While starting front end without browser sync (in my work project: node server.js) - I see no errors.

I believe you can close this ticket.
Our project used jhipster as start point a yesr ago works fine (even in my Chrome :) ) - thank you jhipster team! We really saved lots of time!
