### ISSUE TITLE
How to debug on production mode

### ISSUE THREAD

**Issue by marcelohack** [jhipster/generator-jhipster#4657]
Hi guys,

My application works fine on dev, but I've been facing an error in production mode. Probably is a build issue, How can I debug this?

Cheers,
Marcelo

**Comment by jdubois** [comment]
We need more information than that you "have an error", could you follow the guidelines please?

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
