### ISSUE TITLE
[FEATURE] Provide a generator option for a "light" Jhipster

### ISSUE THREAD

**Issue by mleneveut** [jhipster/generator-jhipster#4661]
##### **Overview of the issue**

It is the second time I want to generate a "light" Jhipster application, in which I don't need security, database, users, ...

It is hard and time consuming to "clean" all the generated code that I don't need (all user, authority, profile beans/services/..., all spring security, ...).

It could be great for some use cases to generate a light application with just Angular and Spring Boot, without all the features of Jhipster.

##### **Suggest a Fix**

Having one or several options to not generate the code (enable security, no database, no users, ...)

What do you think about it ?

**Comment by jdubois** [comment]
If you don't need anything, just use Spring Boot initializer :-)

Of course a solution is to add more questions, but that's going to make the generator more complex. Another solution, and I was just going to create a ticket for that, is to migrate some parts of JHipster into a library, instead of generating it. Most of the code you're talking about isn't changed by users, so we could migrate this without much impact - for you, that means less stuff to change when you want to "remove" stuff. What do you think about this?

**Comment by gmarziou** [comment]
> If you don't need anything, just use Spring Boot initializer :-)

or spring boot cli

Otherwise there are already some command line options that let you opt out some of the features you listed like ` --skip-user-management` and in  `.yo-rc.json ` file you can set`"databaseType": "no",`

**Comment by mleneveut** [comment]
Spring Boot initializer won't create the Angular part, the mecanics linking them together and all the wonderful tools in JHipster (gulp, maven, ...) ;)

A lib could be great yes, but we would need the Front part too and the tools.

**Comment by gmarziou** [comment]
If you move to angular 2, you could use angular-cli to deal with frontend tooling.

**Comment by jdubois** [comment]
Yes for the frontend, the goal is:

- To also have a module there (same as the server-side part, but we'll do it afterwards because we first need to have a stable NG 2 release)
- To have Angular CLI working with JHipster

So this is all under control :-)

**Comment by deepu105** [comment]
I'm closing this as we wont do anything specific for this. as @gmarziou @jdubois said there is already ways to opt out of some parts of the code but then you cant have everthing as pluggable atleast for now

**Comment by pascalgrimaud** [comment]
FYI, this project will help to have this approach: https://github.com/jhipster/jhipster-lite
