### ISSUE TITLE
[FEATURE] Addition of compodoc for Angular 2 projects

### ISSUE THREAD

**Issue by vogloblinsky** [jhipster/generator-jhipster#4663]
[Disclaimer] I'm the maintainer of the suggested tool

Out of the box, this tool generate a documentation of an Angular application (2 for now, 1.5+ soon), with a clean overview of all APIs (components, modules, directives, etc).

![Compodoc screenshot](https://raw.githubusercontent.com/groupe-sii/compodoc/master/screenshots/main-view.png)

The project is available [here](https://github.com/compodoc/compodoc) and there is a live demo [here](https://compodoc.github.io/compodoc-demo-todomvc-angular2).

It could great if it could be integrated in this generator ?

**Comment by atomfrede** [comment]
Looks quite cool, have you considered applying a [jhipster module?](https://jhipster.github.io/modules/creating-a-module/)

**Comment by jdubois** [comment]
Yes we already discussed this on [Reddit](https://www.reddit.com/r/Angular2/comments/5hv5y8/compodoc_documentation_tool_for_your_angular/).

I don't know how this works (yet), so I might be wrong, but for me this would be a good use-case for a module. As soon as it's a module, we could include it in the build mechanism for the sample projects, and that would be a good use case and a good documentation for our upcoming release.

@vogloblinsky can you have a look at our modules system? We could help you do one, if that's complicated.

**Comment by deepu105** [comment]
This indeed looks good. and yes it should be a module

**Comment by jdubois** [comment]
OK I'm closing this as this should be a module, so that's not really a JHipster feature, but @vogloblinsky do notify us when it's ready, and we'll see how we can include it in our documentation. For me that's the same thing as what we do with Sonar at https://jhipster.github.io/code-quality/

**Comment by vogloblinsky** [comment]
Ok no problem, i will do this module soon and notify when it's ready.

**Comment by vogloblinsky** [comment]
@jdubois 
The module is ready and available : https://jhipster.github.io/modules/marketplace/#/details/generator-jhipster-compodoc
