### ISSUE TITLE
Use the gradle node plugin to download node, npm, ...

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#4667]
Just like with the frontend-maven-plugin, we should setup gradle to install node, npm and such from a gradle task.
This way, the only requirement to build a JHipster project is JDK8.

**Comment by cbornet** [comment]
Working on a PR.

**Comment by cbornet** [comment]
So there is the issue https://github.com/srs/gradle-node-plugin/issues/134 which makes npmInstall fail during yodoctor check (which does a npm -v) if we setup a downloaded npm.
A workaround is to install a local npm with `./gradlew npm_install_npm` which will be used by yodoctor.
The build `./gradlew bootRepackage` now does a npmInstall. Do you think it's OK to include a local npm download step before (we could force the version) ?

**Comment by deepu105** [comment]
Im not in favor of trying hard to work without nodejs as its not productive
especially if you are gonna work on ng2 as you need webpack running for
development its ok to do all these for prod but for dev it doesn't serve
much purpose IMO

Thanks & regards,
Deepu

**Comment by cbornet** [comment]
Yes I agree. Then I'll see if it can be done as a command-line property (off by default).

**Comment by cbornet** [comment]
However note that the purpose is not to remove node/npm in dev (you'll always need it for yeoman) but for build/packaging so that the project can be built on simpler setups (eg. in CI). With maven, the packaging already uses a downloaded node through frontend-maven-plugin.

**Comment by deepu105** [comment]
ok if its for prod


Thanks & Regards,
Deepu

On Wed, Dec 14, 2016 at 6:59 AM, Christophe Bornet <notifications@github.com
