### ISSUE TITLE
"From address must not be null" exception while registering

### ISSUE THREAD

**Issue by fyelci** [jhipster/generator-jhipster#467]
There is no "from" keyword in application.yml file. But there is a code in MailService expects taht keyword.

We should add a from keyword to application.yml or change "spring.mail.from" to "spring.mail.user". But I think, second option may not be ok for some mail servers.

```
@PostConstruct
public void init() {
    this.from = env.getProperty("spring.mail.from");
}
```

```
[WARN] com.fyelci.project.service.MailService - E-mail could not be sent to user 'xxx@gmail.com', exception is: From address must not be null
```

**Comment by Yacine-krk** [comment]
Hello,

Just to warn that I still get this error. The from is always null. I posted on stackoverflow, if you can you help :)

http://stackoverflow.com/questions/30154733/jhipster-from-address-must-not-be-null-exception-while-registering

Thanks a lot!
