### ISSUE TITLE
changes to index.html are gone when i do mvn package

### ISSUE THREAD

**Issue by svennela** [jhipster/generator-jhipster#4678]
Hi ,

I am adding below line in my index.html. but when ./mvnw -Pprod clean package. entry is not there anymore. I know, i am missing some thing. Any help.

<script src="http://d3js.org/d3.v3.min.js"></script>

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
