### ISSUE TITLE
Incorrect ordering properties/libs in pom.xml

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#4685]
By adding a lot of librairies, the current pom.xml is not correctly ordered.

Someone in your project could do a `mvn clean install` and commit it.
Then, upgrading to a newer JHipster version is a pain, specially for the pom.xml file, because there is a lot of changes.

Step to reproduce:
1) generate a Maven projet
2) git init
3) git add .
4) git commit -m "init"
5) mvn clean install
6) git status

So you will see a lot of changes.

I would like to reorder everything. Are you ok with that?

**Comment by jdubois** [comment]
Yes but there is some impact with my current "lib". I'm pretty sure we will merge it, so can you do this in `migration-to-jhipster-library`branch?

**Comment by pascalgrimaud** [comment]
Sure, if all agree, I can begin to work on it
But it's not urgent, it is just something I notice when using mvn clean install

**Comment by jdubois** [comment]
Closing as the PR has been merged, and properties are now re-ordered correctly.

**Comment by pascalgrimaud** [comment]
In fact, it's not finished.
All dependencies are not ordered correctly. Launching `mvn install` will still change the pom.xml.

I started to work on it, but it's a huge work, so I think I will do it later

**Comment by jdubois** [comment]
OK, that's not very important...
