### ISSUE TITLE
JWT authentication

### ISSUE THREAD

**Issue by ukurmi** [jhipster/generator-jhipster#4686]
Hi
I have created jhipster application and used stateless authentication technique JWT. So when i logged in 
into application , i am getting a jwt token. Till here everything is okay. When i restart my tomcat server and reload the page (any screen), it remains on the same page(For user those clicks on Logout button, this stack is working fine, cauz  we are deleting jwt token programmatic ally).
    As per my functional knowledge when any user reloads page (after server got restarted), user should be thrown to the login screen.
Here my concern is why jhipster is keeping this token in localStorage?
Is there any way to remove this token from localStorage (when server rebooted)?

I am using google Chrome as client on Windows7 machine.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
