### ISSUE TITLE
Fresh banner for JHipster 4.0

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#4688]
As suggested by @PierreBesson here https://github.com/jhipster/generator-jhipster/pull/4684, what do you think about a new banner ?
Post here your suggestions!

**Comment by pascalgrimaud** [comment]
Here the same banner in 3D:
![jhipster4_banner](https://cloud.githubusercontent.com/assets/9156882/21224194/327b1b52-c2cb-11e6-8d06-23133f8d9eb8.png)

**Comment by PierreBesson** [comment]
Yes !!!!

**Comment by pascalgrimaud** [comment]
**v1**, 2014:
```shell
 _     _   ___   __  _____  ____  ___       __  _____   __    __    _
| |_| | | | |_) ( (`  | |  | |_  | |_)     ( (`  | |   / /\  / /`  | |_/
|_| | |_| |_|   _)_)  |_|  |_|__ |_| \     _)_)  |_|  /_/--\ \_\_, |_| \
                             ____  ___   ___
                            | |_  / / \ | |_)
                            |_|   \_\_/ |_| \
              _    __    _       __        ___   ____  _      __
             | |  / /\  \ \  /  / /\      | | \ | |_  \ \  / ( (`
           \_|_| /_/--\  \_\/  /_/--\     |_|_/ |_|__  \_\/  _)_)
```

**v2**, 2015:
```shell
       __   __    __   __  .______     _______.___________. _______ .______
      |  | |  |  |  | |  | |   _  \   /       |           ||   ____||   _  \
      |  | |  |__|  | |  | |  |_)  | |   (----`---|  |----`|  |__   |  |_)  |
.--.  |  | |   __   | |  | |   ___/   \   \       |  |     |   __|  |      /
|  `--'  | |  |  |  | |  | |  |   .----)   |      |  |     |  |____ |  |\  \----.
 \______/  |__|  |__| |__| | _|   |_______/       |__|     |_______|| _| `._____|
```

**v3**, 2016:
```
        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
        ██  ████████     ██     ███████    █████      ██     ██████    ███████
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██
```

**Comment by deepu105** [comment]
I think since boot now supports images we can add something like but ya bit better I can cook up an image in photoshop if you want
![327b1b52-c2cb-11e6-8d06-23133f8d9eb8](https://cloud.githubusercontent.com/assets/1107223/21226361/6c96045a-c2d5-11e6-9d03-7464867d75aa.png)

**Comment by deepu105** [comment]
thumbs up my comment if you guys want an image to be the logo :)

**Comment by cbornet** [comment]
Some warning: the picture is translated to ASCII art so the resolution is not huge. Unless you make a banner with a loooot of lines...

**Comment by sendilkumarn** [comment]
I was about to ping this...

**Comment by deepu105** [comment]
oh hmm lets try and see locally :) else we will go with 3D


Thanks & Regards,
Deepu

**Comment by wmarques** [comment]
Why is this labelled as minor ? It's a major thing for me :o 
I'd go for the image if it renders well, the 3D is also awesome !

**Comment by cbornet** [comment]
@pascalgrimaud how did you generate the 3D ?

**Comment by pascalgrimaud** [comment]
@cbornet : by hand, after lunch time :smile: 
https://github.com/spring-cloud/spring-cloud-cli/blob/master/spring-cloud-launcher/spring-cloud-launcher-deployer/src/main/resources/launcher-banner.txt

**Comment by sendilkumarn** [comment]
@pascalgrimaud 😮 👏

**Comment by deepu105** [comment]
You could have saved some time with this
http://patorjk.com/software/taag/#p=display&f=3-D&t=JHIPSTER


Thanks & Regards,
Deepu

**Comment by cbornet** [comment]
@deepu105 I know this site but I haven't found an ascii art as nice as Pascal's
@pascalgrimaud I was hoping this was a SW we could have integrated to generate the banner from the app name...

**Comment by deepu105** [comment]
Oh ya hand made is always better as its more love


Thanks & Regards,
Deepu

On Thu, Dec 15, 2016 at 5:26 PM, Christophe Bornet <notifications@github.com

**Comment by gmarziou** [comment]
I like the 3D ASCII art.

I'm not a big fan of images as I don't know how they would work in log files or ELK beside console.

**Comment by jdubois** [comment]
Yes images can fail, and might slow down startup time. The 3D image is cool.

**Comment by deepu105** [comment]
OK 3d IT IS THEN :)


Thanks & Regards,
Deepu

**Comment by cbornet** [comment]
Just found this : http://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=Jhipster
So we could generate the banner based on the application name (provided it's not too long)

**Comment by gmarziou** [comment]
This is cool but I'm not sure we would like to depend on an external service that could be down.

**Comment by jdubois** [comment]
Yes, and I'm happy with having some JHipster advertisement everywhere!!

**Comment by cbornet** [comment]
Found https://github.com/patorjk/figlet.js . And it's javascript ! I vote for a banner subgen !

**Comment by deepu105** [comment]
That looks interesting. We could consider generating a banner based on app name using this as long we also append some JHipster love to it :smiling_imp: 
Something like
```
███╗   ███╗██╗   ██╗     █████╗ ██╗    ██╗███████╗███████╗ ██████╗ ███╗   ███╗███████╗     █████╗ ██████╗ ██████╗ 
████╗ ████║╚██╗ ██╔╝    ██╔══██╗██║    ██║██╔════╝██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔══██╗██╔══██╗██╔══██╗
██╔████╔██║ ╚████╔╝     ███████║██║ █╗ ██║█████╗  ███████╗██║   ██║██╔████╔██║█████╗      ███████║██████╔╝██████╔╝
██║╚██╔╝██║  ╚██╔╝      ██╔══██║██║███╗██║██╔══╝  ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██╔══██║██╔═══╝ ██╔═══╝ 
██║ ╚═╝ ██║   ██║       ██║  ██║╚███╔███╔╝███████╗███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ██║  ██║██║     ██║     
╚═╝     ╚═╝   ╚═╝       ╚═╝  ╚═╝ ╚══╝╚══╝ ╚══════╝╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝    ╚═╝  ╚═╝╚═╝     ╚═╝     

Generated with ♥ by
                                                                                                                  
     ██╗██╗  ██╗██╗██████╗ ███████╗████████╗███████╗██████╗                                                       
     ██║██║  ██║██║██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗                                                      
     ██║███████║██║██████╔╝███████╗   ██║   █████╗  ██████╔╝                                                      
██   ██║██╔══██║██║██╔═══╝ ╚════██║   ██║   ██╔══╝  ██╔══██╗                                                      
╚█████╔╝██║  ██║██║██║     ███████║   ██║   ███████╗██║  ██║                                                      
 ╚════╝ ╚═╝  ╚═╝╚═╝╚═╝     ╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝                                                      
```

**Comment by deepu105** [comment]
@PierreBesson I think we can go easy on the `generated by ` part of the message else it will a huge banner :)

**Comment by PierreBesson** [comment]
@deepu105 yes I much prefer yours 😄 .

**Comment by jdubois** [comment]
I'd much rather keep some JHipster advertisement... And I don't want to rely on yet another third party service than can fail, or another lib we need to update

**Comment by cbornet** [comment]
@jdubois then we make it as a `jhipster:banner` subgen ?

**Comment by jdubois** [comment]
Honestly, that's more maintenance work, and I really don't see the interest.

**Comment by deepu105** [comment]
Yes guys lets not keep adding on stuff for trivial stuff. The generator is
already so huge and it was a real pain when I was migrating it to ES6 and
Yeoman 1. Its far more difficult to test as well. may be its much better to
build these as modules


Thanks & Regards,
Deepu
