### ISSUE TITLE
Home page of generated application keeps loading and doesn't fully display in IE11

### ISSUE THREAD

**Issue by dlmxsn** [jhipster/generator-jhipster#4699]
##### **Overview of the issue**

If I try to access applications I generated with JHipster 3.12.0 using Internet Explorer 11, the application's home page keeps loading for a long time and most of the page (including the menu at the top of the screen, see also the attached screenshot) is never displayed.

![jhipsteremptyappdoesnotload](https://cloud.githubusercontent.com/assets/24608323/21267077/07c960ba-c3a9-11e6-9e34-1c64f33a74ee.PNG)

The Internet Explorer developer console shows the following errors:

```
TypeError: Object doesn't support property or method 'endsWith'
   at Anonymous function (http://localhost:8080/app/blocks/interceptor/notification.interceptor.js:19:17)
   at response (http://localhost:8080/app/blocks/interceptor/notification.interceptor.js:18:13)
   at processQueue (http://localhost:8080/bower_components/angular/angular.js:16383:11)
   at Anonymous function (http://localhost:8080/bower_components/angular/angular.js:16399:27)
   at Scope.prototype.$eval (http://localhost:8080/bower_components/angular/angular.js:17682:9)
   at Scope.prototype.$digest (http://localhost:8080/bower_components/angular/angular.js:17495:15)
   at Scope.prototype.$apply (http://localhost:8080/bower_components/angular/angular.js:17790:13)
   at done (http://localhost:8080/bower_components/angular/angular.js:11831:36)
   at completeRequest (http://localhost:8080/bower_components/angular/angular.js:12033:7)
   at requestLoaded (http://localhost:8080/bower_components/angular/angular.js:11966:9)
Broken interceptor detected: Config object not supplied in rejection:
 https://github.com/chieffancypants/angular-loading-bar/pull/50
```

In Mozilla Firefox 50, everything works fine.

##### **Use Case**

I think Internet Explorer 11 can be considered one of the major and widely-used browsers and it's in the best interest of the JHipster project to support it out-of-the-box if possible. I'm not sure if every little detail needs to look perfect but the web site should at least be functional. This issue is a rather blocking one, particularly for users who don't have access to other browsers.

Additionally, I would like to make it clear that I consider JHipster a great tool and that I personally don't urgently need a fix for this issue. I have just opened this issue, so the JHipster community knows this problem exists.

##### **Reproduce the error**

1. Create a JHipster application (using JHipster [3.12.0).]
2. Run the application (I have imported the project as Maven project into Eclipse and used "Run as Java Application")
3. Try to access the application using Internet Explorer 11.

##### **Related issues**

I haven't found any related issue in the JHipster project. In AngularJS, I've found the following issue

https://github.com/chieffancypants/angular-loading-bar/pull/50

I don't think that the AngularJS issue is really the root cause. Although I'm still quite new to AngularJS, it seems to me that there could be all kinds of reasons for this (see comment section of the AngularJS issue).

##### **JHipster Version(s)**

I have observed this issue when using JHipster 3.12.0 or 3.12.1. Because I haven't been able to reproduce the issue with version 3.11.0, I think it's probably a regression.

Other system information:

JRE 8 (build 1.8.0_112-b15 ,64 bits)
git 2.10.2.windows.1
Node.js 6.9.1 (I was also able to reproduce the issue on a different machine which runs 4.4.1)
npm 3.10.9
bower 1.7.9
gulp CLI 1.2.2, local version 3.9.1
yeoman 1.8.5

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.0",
    "baseName": "emptyApp",
    "packageName": "com.example.empty.app",
    "packageFolder": "com/example/empty/app",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "6b809f6b6024754cf1bb4487ce995cb74e7df104",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

Operating System: Windows 7 Professional

Browsers:
Internet Explorer 11.0.9600.17959
Mozilla Firefox 50.0.2

As mentioned above, the issue only occurs in Internet Explorer.

**Comment by dimeros** [comment]
This bug is dublicate of bug  https://github.com/jhipster/generator-jhipster/pull/4687 (fix IE11 endsWidth issue in notification interceptor)

**Comment by deepu105** [comment]
This will be fixed in our next release for now you can apply the fix from the PR https://github.com/jhipster/generator-jhipster/pull/4687 to your code to get it working

**Comment by dlmxsn** [comment]
Thanks, and sorry for the duplicate ticket.

**Comment by jdubois** [comment]
Don't be sorry, this shows me I should do a patch release when I have the time!
