### ISSUE TITLE
Documentation site updates for v4

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#4703]
We need to update the documentation site for v4 release. Atleast for below

1. Angular 2 option
2. Bootstrap4 in Angular2 option
3. JHipster library
4. Spring constructor injection
5. Graphite and prometheus switches
6. Yarn support

@jhipster/developers please add on if I missed stuff

**Comment by deepu105** [comment]
And of course we need volunteers :smile:

**Comment by pascalgrimaud** [comment]
I will work on the point 6: Yarn support

**Comment by pascalgrimaud** [comment]
@jdubois : should we create a new branch at https://github.com/jhipster/jhipster.github.io ?
So we can PR to this branch.

**Comment by jdubois** [comment]
Yes.
And I'll do constructor injection and JHipster lib, but those should be
pretty small, I guess only details un the release notes.

Le 21 déc. 2016 8:12 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
There's a new `prepare-jhipster-4` branch available on https://github.com/jhipster/jhipster.github.io/tree/prepare-jhipster-4 - let's update this for JHipster 4!

**Comment by jdubois** [comment]
- Installation with Yarn is added
- Full documentation of the JHipster properties is added (and that's why I just cleaned them up!)

Most of the work left would be on https://jhipster.github.io/development/ and https://jhipster.github.io/using-angularjs/ for Angular 2, and https://jhipster.github.io/customizing-bootstrap/ for BootStrap 4.

If there is too much difference, which is probably the case, we might need to duplicate those pages, and have an AngularJS 1 and an Angular 2 version.

**Comment by medmes** [comment]
Is this issue still opened ? i want to contribute.

**Comment by deepu105** [comment]
Yes please


Thanks & Regards,
Deepu

**Comment by gmarziou** [comment]
I tried to find a way to present instructions about frontend tools for both ng1 and ng2 in development.md.
I used tabs and to be able to mix markdown with HTML I have added a jekyll plugin.

Here are the changes in my clone:

https://github.com/gmarziou/jhipster.github.io/tree/dual-doc

Here is how it looks, maybe we should have split documents with comon partials.

![screenshot from 2017-01-21 01-56-42](https://cloud.githubusercontent.com/assets/361007/22170554/64dabbcc-df7f-11e6-9410-5ecb35be5ad6.png)

**Comment by deepu105** [comment]
But markdown with html already works on our doc site doesnt it. Why is a
new plugin required

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
My main concern is, does it work well with GitHub pages? Not all plugins are supported, and sometimes they don't work as expected (who knows what version of Jekyll they use, how they tune it, how they upgrade it...).
Then, visually it's quite cool, and otherwise we would probably end up with 2 different pages: there are pros and cons for each methods, but this looks simpler for everyone.

**Comment by gmarziou** [comment]
Deepu, markdown did not work within `<div>`, maybe the reverse works.
Do you have an example?

Julien, I'll test with Github pages on my clone, first time ;)
Gem versions were conflicting, I solved it by requiring version 1.0 of the plugin rather than 1.1.
BTW, any reason why Gemfile.lock was excluded from git? It's like yarn.lock it must be shared, not surprising as Bundler people also contributed to Yarn.

Hopefully we can get rid of this module once we obsolete ng1.

**Comment by deepu105** [comment]
Yes take a look at the team.md page it has nested html inside markdown

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
Ok wait a minute I think I got your point you are trying to write markdown
inside a DIV. Ya thats doesnt work

Thanks & regards,
Deepu

**Comment by gmarziou** [comment]
Can someone explain me how to publish my fork ?
I activated gh pages but I can see only a broken site:
https://gmarziou.github.io/jhipster.github.io/

Working only with master is also painful, so far I'm not impressed by gh pages 😞

**Comment by jdubois** [comment]
@gmarziou I have no idea :-(
I only test this with Jekyll in Docker, but I know there are differences with Github pages, because they have different plugin versions, and not all plugins are available...
That's why I'm careful about this!!

**Comment by gmarziou** [comment]
Ok then the only way test is to push to master, I'll create a smaller repo

**Comment by deepu105** [comment]
We need to also document that webpack needs to be globally installed in order to have chilprocess run without error from mvn/gradle
`npm i webpack -g` or yarn equivalent

**Comment by gmarziou** [comment]
I never installed webpack globally and it works fine for me.

**Comment by deepu105** [comment]
It fails when executing child process from mvn after a clean with new HMR stuff. Anyways I fixed it to work without a global. ill commit that soon

**Comment by deepu105** [comment]
you cannot publish it as it is. You need to make it your default GH page or
You can publish it a s sub domain of your GH page at max by having it on
the gh-pages branch of any project. then you can access say for example
deepu.github.io/my-gh-page-site


Thanks & Regards,
Deepu

**Comment by gmarziou** [comment]
As this plugin was not supported by github, I tried another approach using jQuery to load fragments.

Here is the result: https://gmarziou.github.io/github-pages-sandbox/test

Here test.html contains the [tab structure](https://github.com/gmarziou/github-pages-sandbox/blob/master/test.html#L134-L149) and
[content loading](https://github.com/gmarziou/github-pages-sandbox/blob/master/test.html#L158-L166) using jQuery

The 2 fragments are HTML files generated from markdown files: https://github.com/gmarziou/github-pages-sandbox/

This is a hack but it is supposed to live only until we drop angular1.

**Comment by jdubois** [comment]
Don't waste time on this, a basic HTML page with a summary is perfect, and
will always ne better for SEO (and a lot of people also use our search box)

Le 24 janv. 2017 2:31 AM, "Gaël Marziou" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
ill try to update some docs tomorrow

**Comment by jdubois** [comment]
Yes and I'll have 4 hours of train on Tuesday, so I'll write more doc at that time.

**Comment by jdubois** [comment]
I began to merge all documentation on my laptop, so if you want any changes please do some new PRs.
@gmarziou I haven't looked at what you did, I'll do it tomorrow

**Comment by jdubois** [comment]
@gmarziou OK so you did several different changes, could you do a PR? Please don't use any JS stuff, just basic markdown, that's really less trouble in the end.
I'll be updated the documentation today.

**Comment by gmarziou** [comment]
I can do it only tonight

**Comment by jdubois** [comment]
No problem @gmarziou !

**Comment by jdubois** [comment]
I've added the Angular 2+ documentation at: 

https://jhipster.github.io/using-angular/

Help is welcome, I did the best I could, but I'm not the greatest expert on this part.

**Comment by jdubois** [comment]
I also added a Bootrstap 4 page at https://jhipster.github.io/customizing-bootstrap-4/ but I suck so much at Sass, that I can't write anything useful!!!

**Comment by jdubois** [comment]
So Bootstrap 4 isn't very good, but I think I updated everything now, that's why I'm closing this
