### ISSUE TITLE
CORS Headers Blocked by 401

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#4704]
##### **Overview of the issue**
The CorsFilter (when enabled) is added after the UsernamePasswordAuthenticationFilter, meaning any requests that result in 401 do not have the expected CORS headers.  The CorsFilter bean is setup in WebConfigurer.java

##### **Motivation for or Use Case**
Anything that uses CORS, such as other frontends/apps using a JHipster backend.

##### **Reproduce the error**
Generate any app, enable CORS in application.yml, start it, and run the following CURL (origin/referrer headers to cause Access Control Headers to appear).
```
curl http://localhost:8080/api/account -H 'Origin: http://192.168.99.100:8100' -H 'Referrer: http://192.168.99.100:8100/' -v
curl http://localhost:8080/api/profile-info -H 'Origin: http://192.168.99.100:8100' -H 'Referrer: http://192.168.99.100:8100/' -v
```
The first request won't have the CORS headers due to the 401 error, the second request will have the CORS headers.

##### **Suggest a Fix**
Similar to the code in JWTConfigurer.java, the below code fixes the headers.
`http.addFilterBefore(corsFilter, UsernamePasswordAuthenticationFilter.class);`

I'm not sure where this should go (it works as a quick fix in the last line of `SecurityConfiguration.configure()`), and it is dependent on CORS being enabled.

##### **Related Issues**
#4035 (this issue is actually mentioned at the end)

##### **JHipster Version(s)**
v3 and master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
Any

**Comment by cbornet** [comment]
Can it be solved by @Order annotation ?

**Comment by jdubois** [comment]
@cbornet no it's a Spring Security filter order, indeed the `http.addFilterBefore` will work.
The best place to do it is in the `SecurityConfiguration` class, indeed. I would put it after the CSRF configuration, with a comment explaining what it's about (and how to enable CORS), so that it's with the other filters (CSRF and remember me are filters too, and I think the filter order would be respected, but I haven't checked)
