### ISSUE TITLE
Jhipster Deployment in Weblogic no rollback transaction

### ISSUE THREAD

**Issue by tvd27285** [jhipster/generator-jhipster#4705]
Dear all,
My application use Jhipster v2.27.2. 
In method of service layer, I insert into three table. 
Everything running on tomcat is ok (It will rollback all it insert failed)
When I deploy it on weblogic application server, I get error no rollback transaction).
I think weblogic application server use JTA transaction, should be Transaction of Spring framework error this case.
Anyone can help me fix it.

Thanks!

**Comment by pascalgrimaud** [comment]
It's not a JHipster bug, it's related to Weblogic.
Post your question on stackoverflow
