### ISSUE TITLE
[FEATURE] Additional module sub-generator

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#4709]
Since #4562 we can now add additional module to the package.json with a new question. BTW great work @gzsombor !
However, I think that this is an operation that you might want to do after the initial generation. Moreover, you might want to do it more than once. So in my opinion this is better suited for a sub-generator than an initial question. This would be something like:

`yo jhipster:add-module
`

Then maybe we should also keep it as a question as it can raise awareness about our module system and we would like to see more people developing modules.

**Comment by jdubois** [comment]
Yes, it's great for marketing, but not very good when doing project re-generation! +1 from me.

**Comment by jdubois** [comment]
However I wouldn't do this at the moment, we already have a ton of work for JHipster 4, and I'm also quite worried by #4631 , so for me it's too much new things for now. Are you OK to postpone this?

**Comment by gzsombor** [comment]
This doesn't seem to difficult to do it, I thought about it initially, but my main goal was to give more instant visibility to the modules, which are a bit hidden treasures for JHipster. If you want to make a PR, I wouoldn't oppose ;-)

**Comment by jdubois** [comment]
Oh, I would be happy to have it, too! It's just that I'm afraid we start too many things right now, and that our Angular 2 migration is not finished yet. I'd like to release JHipster 4 in the next couple of weeks.

**Comment by PierreBesson** [comment]
Really it would be simple enough to do. @jdubois don't worry I can do it

**Comment by deepu105** [comment]
Also you can compose the sub generator from the main generator during the
first generation of app so thats its visible easily (its easy to detect
based on availability of yo-rc file)


Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
I might have overestimated my JS/yeoman skills. If someone else is able to work on this, please help.

**Comment by jdubois** [comment]
Then @PierreBesson I would rather close this, and we can still have a look at it later. We already have too much work at the moment, I want to focus on JHipster 4.

**Comment by jdubois** [comment]
Let's close this and focus on JHipster 4. This looks complex, we don't have the time.
