### ISSUE TITLE
[FEATURE] Add jpa custom constraints generation to entities

### ISSUE THREAD

**Issue by fbn-roussel** [jhipster/generator-jhipster#4710]
##### **Overview of the issue**

It could be nice having a jpa custom constraint annotation (at class level) generated with the entity for any specific validation that cannot be done by standard validators. See more on https://docs.jboss.org/hibernate/validator/5.0/reference/en-US/html/validator-customconstraints.html#section-class-level-constraints

##### **Motivation for or Use Case**

In most of projects I worked for each entity had his own constraint annotation. It is not taking that long to create one but if it was generated with the entity I think it could be more productive. Of course it will be empty at first but ready for the developer to focus on business logic validation or anything else.

##### **Suggest a Fix**

I already tried to implement this feature and it was quite simple. You let me know if you want a PR or not.

Anyway great job for the project, I'm totally loving it ;)

**Comment by jdubois** [comment]
Indeed, constraints are a pain to code, so this would help!
Then, in my opinion constraints are meant to be share, I would like to re-use them, so they would not be tied to an entity.
We could have a specific sub-generator just for contraints, maybe? Or @fbn-roussel would like to do a module for this, first? I think modules are great to test out ideas, as you don't depend on us and can go faster, and if it's a widespread usage we can move the code to an "official" sub-generator.

**Comment by fbn-roussel** [comment]
A module seems also good to me, I'll go for it ! Thanks for the idea.

**Comment by jdubois** [comment]
OK so I'm closing this, and we can discuss this again once your module is ready, of course. BTW, don't hesitate to mention @java_hipster on Twitter, and I'll RT you!
