### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:npm (npm install) on project jhipster-cassandra-sample-application  when we do mvnw package -Pprod docker:build

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#4714]
[INFO] --- frontend-maven-plugin:1.2:npm (npm install) @ jhipster-cassandra-sample-application ---
[INFO] Running 'npm install' in C:\Users\Admin\app\jhipster-sample-app-cassandra
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:01 min
[INFO] Finished at: 2016-12-19T08:38:10+05:30
[INFO] Final Memory: 30M/226M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:npm (npm install) on project jhipster-cassandra-sample-application: Failed to run task: 'npm install' failed. java.io.IOException: Cannot run program "C:\Users\Admin\app\jhipster-sample-app-cassandra\node\node.exe" (in directory "C:\Users\Admin\app\jhipster-sample-app-cassandra"): CreateProcess error=193, %1 is not a valid Win32 application -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by pascalgrimaud** [comment]
> Cannot run program "C:\Users\Admin\app\jhipster-sample-app-cassandra\node\node.exe" (in directory "C:\Users\Admin\app\jhipster-sample-app-cassandra"): CreateProcess error=193, %1 is not a valid Win32 application

**Comment by JinnaBalu** [comment]
I am unable to find out the solution for this kind of issue, I have tried replcing the node.exe with supported version, but still facing the same issue.

**Comment by gmarziou** [comment]
Problem is probable not node.exe, it is %1.
It seems you have cloned our sample repo, please try generating an app the normal way as it will run some verifications or your environment
