### ISSUE TITLE
[FEATURE] Move maven dependencies and plugins in a parent pom

### ISSUE THREAD

**Issue by dacloutier** [jhipster/generator-jhipster#4724]
##### **Overview of the issue**
Currently, the jhipster generator creates a maven pom.xml that defines springboot-starter-parent as the parent pom:

```
    <parent>
        <artifactId>spring-boot-starter-parent</artifactId>
        <groupId>org.springframework.boot</groupId>
        <version>1.4.2.RELEASE</version>
        <relativePath/>
    </parent>
```
Then goes to define all the properties, dependencies and plugins required for the jhipster application.

##### **Motivation for or Use Case**
If you then modify the pom.xml for your application, adding properties, dependencies or plugins, these changes are at risk of being overridden when you update the jhipster version in the future.

Also, these poms are quite repetitive between all your generated apps. This can lead to confusion and minor discrepancies are hard to detect.

Also, I tried to do this myself, and created a custom parent pom for all my projects, but then I upgraded from 3.10 to 3.12 and the upgrade process changed my pom from top to bottom.

##### **Suggest a Fix**
If the JHipster team created a public parent pom and deployed it on maven central then the pom.xml generated by the jhipster generator could be a lot simpler and easy to maintain as the app ages.

Example:

```
<?xml version="1.0" encoding="UTF-8"?>
<project ......   >
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.jhipster</groupId>
        <artifactId>jhipster-parent</artifactId>
        <version>3.12.2</version>
        <relativePath/>
    </parent>
    <groupId>app.package</groupId>
    <artifactId>app.name</artifactId>
    <version>0.0.1-SNAPOSHOT</version>
    <name>Your App</name>
    <prerequisites>
        <maven>3.0.0</maven>
    </prerequisites>

    <dependencies>
        <!-- custom dependencies based on the choices entered in the app generator -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
        </dependency>
        <!-- jhipster-needle-maven-add-dependency -->
    </dependencies>
</project>
```

So, the yo jhipster:upgrade could just change the version of the parent pom and it's job would be done.

##### **JHipster Version(s)**
jhipsterVersion: "3.12.2"
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
git version 2.7.4
node: v6.9.1
npm: 3.10.9
bower: 1.8.0
gulp:
    CLI version 1.2.2
    Local version 3.9.1
yeoman: 1.8.5
Docker version 1.12.3, build 6b644ec
docker-compose version 1.8.1, build 878cff1

**Comment by gzsombor** [comment]
Interesting idea ! I have similar problem, only that I would rather not inherit from spring-boot - because I want a multi-module maven setup. Spring-boot has a partial solution for this - mentioned here : http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-build-systems.html#using-boot-maven-without-a-parent Unfortunately not all the settings could be imported, I had to copy a lot of plugin configuration. Maven is a mess if you want a slightly complex setup

**Comment by jdubois** [comment]
This is an idea I've had for years!! For me this was solved (at least!) by Spring Boot, but indeed it's now not enough for JHipster, as we go farther than Spring Boot.
Until very recently we didn't have a solution with JHipster, but now we have https://github.com/jhipster/jhipster that is published on Maven Central, things have changed!
So that looks a really good idea, and that would be quite easy to implement.
This is linked to #4685 -> @pascalgrimaud do you agree?

**Comment by pascalgrimaud** [comment]
I agree, it's completely linked to #4685 !

So I will finish the work on this PR https://github.com/jhipster/generator-jhipster/pull/4721 (only reordering the properties) and hold on, depending if we go to a JHipster pom parent

**Comment by pascalgrimaud** [comment]
Agree with you @jdubois : I think some clients can be reluctant to have "jhipster" as pom parent, instead of "spring-boot-starter-parent"

**Comment by dacloutier** [comment]
Well, as long as the parents are versioned, it didn't force the users into anything, and if they want to branch out of hipster then they could just extract the values for it. 

The way the poms are built now, it's very hard to put custom stuff into the pom without it getting overridden during an update.

**Comment by jdubois** [comment]
Still, I believe it goes too far for a first version of the JHipster lib.
Yes, I think it's a great idea, and I believe it's what we should do in the future.
But I don't want to do it yet, having a JHipster lib is already a huge shift from what we do, I want first to have feedback from users before going farther.
So I'm closing this for the moment, but if the feedback is positive on the JHipster lib, we can definitely do this in a future version.
