### ISSUE TITLE
Refactor Hibernate ID generation

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4725]
This comes from the discussion at #4690

For our entity IDs generation, we currently use the "Auto" generator from JPA. It's standard, and then Hibernate has to use an implementation working with the current database.

This has worked well since the beginning, I coded the original implementation and I don't think we had any issue with it.

However, with JHipster 4 I'd like to make some breaking changes here.

I want to use the new `SequenceStyleGenerator` from Hibernate. In fact, we currently have a warning because with "Auto" we use the older Sequence generator (which is kind of stupid, with "Auto" it shouldn't select a deprecated generator...). This new generator is supposed to be `optimized` (I looked at the code and this also looks quite stupid, I don't see where there is an optimization here), and can automatically fall back to using a table if your database doesn't support sequences (that's for MySQL, which is used by 50% of our users - and yes that's also stupid to call "Sequence" a generator that can use a table...).

PROs:

- No more warning when Hibernate starts because we use the older Sequence
- Do not use "identity" anymore with MySQL: this costs a few more requests, but in the end it's worth it as we can now use JPA batches and table per class inheritance. So a lot more features, with a very tiny performance impact.

CONs:

- The configuration is a overly complex. But as we generate it, it shouldn't be a big issue.
- We can be backward compatible with JHipster 3, but that requires a few tweaks (basically starting the sequence with the higher number than any previously existing ID)

Thoughts, comments?

**Comment by ctamisier** [comment]
If we want to be backward compatible, the already existing liquibase changeset must not be changed (liquibase checksums already stored in DB). And then only new migrations can be added altering tables and/or sequences.

What I see from this is to have many migrations even for a brand new starting project. (may confuse the new jhipster user). But still, as a jhipster 3 user, I want to upgrade to jhipster 4... (add a new option in the yeoman generator ? :( )

**Comment by jdubois** [comment]
I'm not too worried for migrations: it's still using the same sequence (for databases that use sequences), and for MySQL then you need a new changeset to add the table. That doesn't look too complex for me.

**Comment by gzsombor** [comment]
I'm a bit confused, for MySQL, do you suggest to not use auto-increment fields anymore? I don't understand why this could be an improvement :(

**Comment by jdubois** [comment]
@gzsombor yes, because auto-increment (aka "identity") has two drawbacks: it doesn't support batching, and table per class inheritance.

**Comment by gzsombor** [comment]
Do we support any inheritance strategy? (I would rather suggest to use single table inheritance, or joined, multi-table inheritance, because you can properly query them, and have working foreign keys)
For bulk inserts, I understand, there could be a performance penalty, if hibernate wants to retrieve all the newly generated ids, I haven't tested yet, as I was more worried about the single entity insertions performance.

**Comment by jdubois** [comment]
Indeed those are edge cases... But the performance penalty is very low anyway.
I still need to do more testing on this. I literally spent the night on this, it's quite simple in the end, but so badly documented you need a lot of time !

**Comment by jdubois** [comment]
I'm having second thoughts now:

- This is really hard to configure, and quite verbose, so it's not really
good for end-users. In fact, this is so badly documented that I doubt
anybody is doing this. I will post a sample when I have my computer (yeah,
50% of JHipster is coded on my phone while I'm commuting!)
- The performance penalty for all write requests is indeed starting to
worry me
- Why break something that bas been battle-tested for years, without any
issue or complain?

**Comment by jdubois** [comment]
Best solution for me is:

- Use IDENTITY with MySQL
- Use Sequence with the new "optimized" algorithm for all other databases

I've commited my test code on a specific branch: https://github.com/jhipster/generator-jhipster/tree/refactor-hibernate-id-generator

**Comment by jdubois** [comment]
My branch is building OK, and I'm quite convinced it's the best solution: is anybody having any comments? Otherwise I'll merge this tomorrow.

**Comment by ctamisier** [comment]
`incrementBy="50"`
is this something like "recommended" by the generator strategy ? (instead of 1).

and it will break the existing md5 liquibase changeset sequence ? (because of the 50 ?).

**Comment by jdubois** [comment]
Yes that's the new strategy

**Comment by ctamisier** [comment]
ok nice, and that solve my concern with my duplicated postgres sequence. thanks ! :).

But i'm still wondering how to migration to this new version. The md5 has changed so the application won't start. Should we update manually the databasechangelog table to update with the expected MD5 ? (maybe there is already docs about this that I missed.. ).

**Comment by jdubois** [comment]
We'll need to try, but I would do a new changeset that recreates the sequence, and which starts with a number higher to what has already been used.

**Comment by ctamisier** [comment]
ok I see we just adapt the migration schema (new changesets) according the existing ones and our needs.

**Comment by jdubois** [comment]
OK, let's do this!
