### ISSUE TITLE
Spring Boot 1.4.3 makes the "dev" profile fail (404 error)

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4756]
Following #4750 which was just merged in the master branch, the application shows a 404 error when running in dev mode.

This is because in the `WebConfigurer`, our trick to set the document root is not taken into account any more.

The solution I'm working on is to use Spring Boot standard's path, like `classpath:/resources` instead of `target/www`. It would solve the issue and remove a lot of code.

**Comment by pascalgrimaud** [comment]
You're right. To reproduce the bug:
- start the main class
- `./mvnw`

When packaging and start with `java -jar target/*.war`, there is no problem.

I should change on Travis build (for 1 build at least) to launch direct `./mvnw` instead of `java -jar` to detect this kind of problem

**Comment by jdubois** [comment]
I won't have the time to find a solution soon, I think we should revert the commit to Spring Boot 1.4.2

**Comment by pascalgrimaud** [comment]
@jdubois : sorry for going too fast. Let revert

**Comment by pascalgrimaud** [comment]
I will do all the PR for that

**Comment by jdubois** [comment]
Can you do it? I'm only with my phone :-)

**Comment by pascalgrimaud** [comment]
@jdubois : done! here the 3 PR:
- generator-jhipster: https://github.com/jhipster/generator-jhipster/pull/4757
- jhipster: https://github.com/jhipster/jhipster/pull/4
- jhipster-registry: https://github.com/jhipster/jhipster-registry/pull/94

Let investigate it after :christmas_tree:

**Comment by jdubois** [comment]
Thanks, I might have a better solution than our current `target/www` hack, that would solve the issue.
But there's a lot to test: Gradle/Maven, AngularJS/Angular, dev and prod profiles...

**Comment by deepu105** [comment]
ahhh. I didnt see this issue and wasted time analysing it coz I was on a branch without the revert

**Comment by jdubois** [comment]
I'm closing this as it's merged

**Comment by sylvainlecoy** [comment]
I confirm the bug as well and reverting to spring boot 1.4.2 fixed the 404 error on main profile as well (not only dev).

**Comment by pascalgrimaud** [comment]
@sylvainlecoy : you can look this ticket https://github.com/jhipster/generator-jhipster/issues/4762
The upgrade to 1.4.3 has been done

**Comment by sylvainlecoy** [comment]
Well I have the issue with spring boot 1.4.3. Downgrading to 1.4.2 fixed my 404 on default profile.

**Comment by sylvainlecoy** [comment]
@pascalgrimaud If I upgrade again to spring boot 1.4.3 I actually get the issue. My JS files are in src/main/webapp, is it something that has been changed ? Do I need to configure something now ? Its unclear in the change log of the ticket you mentionned how it affect my project.

Thanks for your time.

**Comment by pascalgrimaud** [comment]
@sylvainlecoy : have a look at this commit https://github.com/jhipster/generator-jhipster/commit/a9e5189bf018f932b9b6834e81877e255586308d

You have to use the old version of spring boot devtools:
```xml
                  <dependency>
                     <groupId>org.springframework.boot</groupId>
                      <artifactId>spring-boot-devtools</artifactId>
                     <version>1.4.2.RELEASE</version>
                      <optional>true</optional>
                  </dependency>
```

**Comment by sylvainlecoy** [comment]
@pascalgrimaud Thank you for the tip, is this a quick fix or I need a better way ? I mean its a temporary regression or I have to update something on my future projects to maintain compatibility ?

**Comment by pascalgrimaud** [comment]
@sylvainlecoy : it's a tempory fix here. But the real problem comes directly from spring boot, not from our project. So I'm pretty sure the spring boot team will fix it.

**Comment by pascalgrimaud** [comment]
@sylvainlecoy : and here, the commit from spring boot: https://github.com/spring-projects/spring-boot/commit/61c931943f19f96db1c0b21e1563a56a116f77d8 with full explaination

**Comment by sylvainlecoy** [comment]
@pascalgrimaud Thanks for the info and your time.
