### ISSUE TITLE
Can't launch newly generated app + 1 entity with last master

### ISSUE THREAD

**Issue by MathieuLorber** [jhipster/generator-jhipster#4759]
##### Can't launch generated app with 1 entity since id generation refactor

I have a problem on current master (a409b6), on an empty project, the app stops to launch as soon as I create a (simple) entity.
It logs "Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed". Suggested solutions to the problem don't work.
When I revert this patch, it's ok again => an empty project + 1 entity launchs (I still have a ng2 state problem, I can't find the entity, but it's another problem).

##### Reproduce the error

https://github.com/MathieuLorber/jhipster-demo => everything is ok on master (fresh new generated app), on branch issue (+1 entity), app won't launch.

##### **Suggest a Fix**

Obviously not a fix but reverting https://github.com/jhipster/generator-jhipster/pull/4742 makes it ok.

##### **JHipster Version(s)**

Current master (a409b6)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.1",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "7636773e72dcb680504a2b837b5ed21361ceedc1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "pwet",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20161223165929",
    "dto": "no",
    "service": "no",
    "entityTableName": "hello",
    "pagination": "no"
}

**Comment by MathieuLorber** [comment]
first version of my repo doesn't reproduce the bug sorry =s

**Comment by jdubois** [comment]
Can you write a better title?

**Comment by MathieuLorber** [comment]
my repo is now ok : branch master works, branch issue fails

**Comment by jdubois** [comment]
oh, you're using the entity sub-generator with Angular 2, this is in active development, it can fail all the time... In fact I can't even generate it at the moment!!
So that's not surprising: either switch to AngularJS 1, or don't do entities with Angular 2. This should be stable very soon.

**Comment by MathieuLorber** [comment]
Ok !
Thank you.

**Comment by jdubois** [comment]
@MathieuLorber by the way the current issue was caused today, I'm currently correcting it, and I have your conf working right in front of me! Just wait for my next commit :-)
