### ISSUE TITLE
Refactor front-end packaging for Spring Boot 1.4.3

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4762]
This issue is necessary for migrating to Spring Boot 1.4.3, see #4756

We've set up quite a complex system to have our front-end build in `target/www`, which has a few drawbacks:

- It's quite complex, and as it's generated in `WebConfigurer` it's not very good for the end user
- This was done before we had "official" public folders in Spring Boot, and of course it's better to use those official folders -> here I will use `classpath:/resources` but there are several others, and this can be discussed

I have pushed a proposal at https://github.com/jhipster/generator-jhipster/tree/prepare-spring-boot-1.4.3

This proposal has a lot less code, and is easier to understand. And of course it should work with Spring Boot 1.4.3.

It is quite complex to test has we have a matrix of options here:

- AngularJS 1 & Angular 2
- dev and prod profiles (as well as packaging in prod, which can be different than just running in prod from Maven/Gradle)
- Maven & Gradle

There are several things not working at the moment:

- Angular 2: when building in `prod` mode, prod files get fixed up with dev files as everything goes into the same build folder in the end. The folder should be cleaned up before. This is also an existing issue with the current build!! There is also still a banner (which has no text), and the HTTP cache filter is not working.
- Gradle & Angular 1: in `prod` doing an audit with Chrome Dev Tools shows lots of issues, we are probably in a mix of dev/prod mode.
- With Gradle I'm not sure where those files should go: `build/classes` or `build/classes/main`

**Comment by deepu105** [comment]
:+1: if we can reduce complexity but please note that we need to test below 18 cases

NG1: for both maven and gradle (12 cases)
- [ ] Test default bootrun
- [ ] Test default bootrun -Pprod
- [ ] Test package
- [ ] Test package -Pprod
- [ ] Test IDE run
- [ ] Test IDE run -Pprod

NG2: (the prod build is not complete anyway hence it can wait) for both maven/gradle so 6 cases
- [ ] Test default bootrun
- [ ] Test package
- [ ] Test IDE run

**Comment by jdubois** [comment]
I spent a couple of hours on this, this is **much** more complex than expected!!! There's definitely stuff do here anyway, as for NG2 we must have a "dev" and a "prod" dist folder.

**Comment by jdubois** [comment]
I opened ticket https://github.com/spring-projects/spring-boot/issues/7756 on Spring Boot for the original issue.
As we need even more flexibility with Angular 2, with a "dev" and a "prod" folder for the generated JavaScript, I'm not sure anymore that we can simplify the existing mechanism. I need to do more testing, and hopefully find a workaround for the original issue.

**Comment by jdubois** [comment]
Got it :-)
This is because of https://github.com/spring-projects/spring-boot/issues/7752
Many many many thanks to @felx who found the issue, I spent hours on this believing it was our fault!!

Bottom line is:

- Our current system is complex, but I haven't found a better way to do it
- It will become even more complex with Angular 2, as we will need 2 build folders, one for dev and one for prod -> there is clearly work to do it, @deepu105 is this in your task list?
- I'm doing the Spring Boot 1.4.3 upgrade, expect a commit soon

**Comment by gmarziou** [comment]
Could we have a simpler setup if we were clearly splitting client code from server in 2 modules?

I did it for a ng2 gateway and it was easier to work with angular-cli, it was also simpler with webpack than previously with gulp. In a way, it consists in using Jenkinsfile to build and assemble the 2 parts in prod, while in dev you benefit from webpack server proxification.

**Comment by deepu105** [comment]
I haven't started to work on prod profile for ng2 as its not a priority for
the beta support it will need to be tackled after we release the first
version

Thanks & regards,
Deepu

**Comment by gzsombor** [comment]
Why do we need 2 separate frontend build? The full, minified, compressed js with source maps are good enough, in my experience. The less the difference between the prod and the dev environment is, the better.  
 In one of my project, we removed it altogether, because there were some issues, which is only popped out in minified angularjs code, and building two war files, one for the staging server, with dev profile, and one for the live server hide that, until it was too late.

**Comment by deepu105** [comment]
Yes I'm also of the same opinion that for ng2 we should have same build
with sourcemaps for frontend in prod and when running watch we will just
disable uglify to make builds faster. Its doable with webpack. So in the
end everything will be output as the same files


Thanks & Regards,
Deepu
