### ISSUE TITLE
Webpack compilation error with Protractor

### ISSUE THREAD

**Issue by mohamed2a** [jhipster/generator-jhipster#4768]
##### **Overview of the issue**

During the webpack compilation, I have this : 
```
[INFO] ERROR in [at-loader] node_modules\protractor\built\browser.d.ts:260:37
[INFO]     Cannot find namespace 'webdriver'.
[INFO]
[INFO] ERROR in [at-loader] node_modules\protractor\built\browser.d.ts:267:55
[INFO]     Cannot find namespace 'webdriver'.
[INFO]
[INFO] ERROR in [at-loader] node_modules\protractor\built\browser.d.ts:267:78
[INFO]     Cannot find namespace 'webdriver'.
[INFO]
[INFO] ERROR in [at-loader] node_modules\protractor\built\browser.d.ts:358:31
[INFO]     Cannot find namespace 'webdriver'.
[INFO]
[INFO] ERROR in [at-loader] node_modules\protractor\built\browser.d.ts:369:26
[INFO]     Cannot find namespace 'webdriver'.
[INFO]
[INFO] ERROR in [at-loader] node_modules\protractor\built\browser.d.ts:425:36
[INFO]     Cannot find namespace 'webdriver'.
[INFO]
[INFO] ERROR in [at-loader] node_modules\protractor\built\ptor.d.ts:13:29
[INFO]     Cannot find namespace 'webdriver'.

.............................


[INFO] BUILD FAILURE
```

##### **Motivation for or Use Case**

I can't run my generated application.

##### **Reproduce the error**

Start generating a new application, during the prompt choose "Protractor". At the end, run your application, the webpack compilation fails !

##### **JHipster Version(s)**

Version 3.12.1
It's a regression related to webpack configuration changes

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.1",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "********",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

**Comment by jdubois** [comment]
No problem for me, I guess we upgraded something in the master branch in the meantime! That's quite impressive to see Protractor working on Angular 2, great work @mohamed2a @mraible !!

I saw a couple of issues on this, I'll open up a separate ticket for this.

**Comment by jdubois** [comment]
Sorry @mohamed2a I have the same issue with Karma, did you meant Karma instead of Protractor?

**Comment by mohamed2a** [comment]
@jdubois It works with karma, it fails when I choose Protractor in my generated application.

**Comment by jdubois** [comment]
@mohamed2a even now? That's really weird

**Comment by mohamed2a** [comment]
Thank you @jdubois.

Best regards

**Comment by mohamed2a** [comment]
I noticed that a lot of karma tests related to angularJs have been removed, why ? look at [the karma spec folder](https://github.com/jhipster/generator-jhipster/tree/master/generators/client/templates/angularjs/src/test/javascript/spec/app)

**Comment by deepu105** [comment]
Yes we need to put them back

Thanks & regards,
Deepu

**Comment by mohamed2a** [comment]
I deleted the comment : 
> I noticed that a lot of karma tests related to angularJs have been
> removed, why ? look at the karma spec folder
Because I just found out that they are always here :)
