### ISSUE TITLE
[FEATURE] Add addNpmDependency & addNpmDevDependency functions

### ISSUE THREAD

**Issue by vogloblinsky** [jhipster/generator-jhipster#4798]
I am working on a jhipster-module which add a npm dependency to a jhipster project.
The function addBowerDependency is available, and it would be nice to have the same for npm.

I propose this PR : [#4797](https://github.com/jhipster/generator-jhipster/pull/4797)

**Comment by pascalgrimaud** [comment]
@vogloblinsky : once the PR is accepted, could you PR for updating this page too ?
https://jhipster.github.io/modules/creating-a-module/

**Comment by vogloblinsky** [comment]
Yes, i was searching right now the source ?

**Comment by vogloblinsky** [comment]
@pascalgrimaud i had for my jhipster module to edit the main gulpfile.js at the root of the generated project for adding a new gulp task.
Is it ok if i read the file, and override it with `jhipsterFunc.rewriteFile` ?

**Comment by pascalgrimaud** [comment]
@vogloblinsky : I would say, it's your module, so you can do what you want! That's what I find modules so powerful.

**Comment by vogloblinsky** [comment]
ok @pascalgrimaud, just waiting for the PR validation for updating the public page ;)

**Comment by deepu105** [comment]
closed via #4797
