### ISSUE TITLE
Jhipster-ionic Generator Exception

### ISSUE THREAD

**Issue by huiqiangyang** [jhipster/generator-jhipster#4799]
Hello my friends, I need your help ,today I want to use  `JHipster Ionic Generator` , when I geneator code,show this error 
```shell
Files will be generated in folder: /home/yhq/pro1612/hui-app
? Where is the parent directory of the JHipster monolith/gateway located ? ../
1 applications found at /home/yhq/pro1612/
? Which application do you want to generate from? hui-web
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn cordova ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
My system is Ubuntu,node version v6.9.2 ,npm version 4.1.1, Jhipster version latest
Could you tell me a method to solve  this question,thank you~!

**Comment by pascalgrimaud** [comment]
Could you open a ticket to the appropriate project : https://github.com/ruddell/generator-jhipster-ionic/issues ?

**Comment by huiqiangyang** [comment]
@pascalgrimaud I`m sorry, this error appear in `[BETA] JHipster UAA server (for microservice OAuth2 authentication) ` too , is my one plugin version has too low? are you meet this question?

**Comment by pascalgrimaud** [comment]
If you have an issue with the generator-jhipster it self, we need:
- full description
- all steps, so we can reproduce your error
- your configuration file: .yo-rc.json, entities.json if you have, etc.
- all information on all your tools

You can simply follow the template, and use yo jhipster:info
