### ISSUE TITLE
Work on the frontend-maven-plugin

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#48]
Usage of the front-maven-plugin was coded by @eirslett see #40 

However it causes some trouble when using a corporate firewall, as we can't download node/npm directly

I need to take a closer look at all this.

**Comment by SCarlinINWK** [comment]
@jdubois - I am trying to run a JHipster generated app with no internet access on the machine, using Sinopia and other private repositories hosted internally, but node is still trying to download packages, directly.  Have you seen this before, know of a work around or have any advice?
