### ISSUE TITLE
Running Docker in the docker container fails with Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by jmkhael** [jhipster/generator-jhipster#4804]
* **Overview of the request**

Add the ability to run docker from within the docker container, in order to successfully execute commands such as from within it:

`./gradlew bootRepackage -Pprod buildDocker`

Note that the docker container is started with:

```
docker run --name jhipster \
    -v $(which docker):/usr/bin/docker \
    -v /data/apps/jhipster/app/.m2:/home/jhipster/.m2 \
    -v /data/apps/jhipster/app/.gradle:/home/jhipster/.gradle \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /data/apps/jhipster/app:/home/jhipster/app \
    -v /lib64/libdevmapper.so.1.02:/usr/lib/x86_64-linux-gnu/libdevmapper.so.1.02 \
    -v /lib64/libudev.so.0:/usr/lib/x86_64-linux-gnu/libudev.so.0 \
    --privileged=true \
    -p 8080:8080 -p 3000:3000 -p 3001:3001 -d -t jhipster/jhipster
```

and  /data/apps/jhipster/app is owned by id=1000.

* **Motivation for or Use Case** 

In order to use an already packaged jhipster dev container, but also do docker magic!

* **Browsers and Operating System** 

NA

* **Related issues** 

NA

* **Suggest a Fix** 
The current state is that the user jhipster cannot contact the /var/run/docker.sock, because it isn't in the docker group.

jhipster@uniqueid:~/app$ ls -lart /var/run/docker.sock
srw-rw---- 1 root 979 0 Dec 15 16:36 /var/run/docker.sock

```
$ docker exec -it jhipster bash
jhipster@f65455ab5cfd:~/app$ docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

in theory, a simple groupadd docker and -g docker in the [Dockerfile](https://hub.docker.com/r/jhipster/jhipster/~/dockerfile/) should be enough.

` groupadd jhipster && groupadd docker \
  useradd jhipster -s /bin/bash -m -g jhipster -g docker -G sudo && \`

I also noticed that sudo isn't installed (not a default package anymore)
```
sudo groupadd docker
bash: sudo: command not found
```

I can contribute to this if you can point me to:

1. how to rebuild this generator and test it
2. how to execute commands as sudo in this container

**Comment by PierreBesson** [comment]
@jmkhael  you have a good idea here ! I think it would be OK to add the jhipster user to the docker group so that you can do a docker build from within docker.
However some remarks : 
- Although sudo is not installed but you can log in as root with the `-u 0` arg to the docker cli.
`-v $(which docker):/usr/bin/docker` : this doesn't work out of the box with Docker for Mac and for good reason, also it seems a bit dangerous. However, you can simply download the `docker cli` binary (extract it from the release tar here https://github.com/docker/docker/releases) and execute it. I just tried it and it works !

**Comment by pascalgrimaud** [comment]
Honestly, I only use `jhipster/jhipster` images for regenerating old version of JHipster or testing another config (node, npm etc) and never use it for development
What you mention here is interesting (same subject about Running Docker in Jenkins inside Docker), but can be hard because it need to be tested on 3 OS (Linux, Mac and Windows).

And I suppose there are very few users who use this image (because we have very few feebacks), so I'm not sure it's worth to do it.
Let discuss...

**Comment by cbornet** [comment]
You could do a user namespace remap. See [here](https://docs.oracle.com/cd/E37670_01/E75728/html/ol-docker-userns-remap.html). It works on Linux. Don't know on Mac...

**Comment by pascalgrimaud** [comment]
@jmkhael : to answer to your questions, you can read https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

To resume:
- fork the project
- clone your fork
- go inside your project
- create a local branch
- edit the Dockerfile at the root folder
- then, you can build a new image with: `docker build -t jmkhael/jhipster .` and test your image

**Comment by cbornet** [comment]
@jmkhael Actually, what you should do is not running in privileged mode (this is bad for security) but add the uid 1000 to the docker group of the **host** . Then use `-u 1000` when bash logging.

**Comment by jmkhael** [comment]
thank you all for the helpful comments. 

Indeed, this resembles the Docker in a Docker but launching siblings containers on the host. (discussed [here](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/))

To make the use case a bit clearer, what I'd like to accomplish is to use a Raspberry Pi as a "development environment". The idea is that i'd like to rebuild a Raspberry Pi image for JHipster to make it more hip and demo a Netflix Stack built with Jhipster on a Raspberry Pi Swarm!

Here is what i did after reading your comments:

* removed the --privileged flag (which I added only for testing...)
* docker exec -it --user=0 jhipster bash
* groupadd docker -g 979 (note that the id must match the host's docker group id)
* usermod -aG docker jhipster

Now i can successfully execute docker commands from within the container:

```
jhipster@423a42765c98:~/app$ docker service ls
ID            NAME               REPLICAS  IMAGE                                              COMMAND
2br2tco0j9fw  viz                1/1       manomarks/visualizer
6b8v75c40ith  portainer-swarm    1/1       portainer/portainer                                --swarm
...
```

Note that 
* this fails if the group docker in the container doesn't have the same id as the group docker on the host. Do you have any idea how to circumvent that?
* There is an issue [suggesting a fixed Docker group ID of # 357](https://github.com/docker/docker/issues/21184)
* If I do `docker exec -it --user=0 jhipster bash` it just works, no need to do add group/user to group commands.

**Comment by cbornet** [comment]
> If I do docker exec -it --user=0 jhipster bash and then any docker command just works, no need to do add group/user to group commands.

Yes but be warned that you are using the root user of the host. Probably not very secure...

**Comment by cbornet** [comment]
Also I don't think you need to add a docker group in the container. Docker should use the permissions from the host. Just use in your container a uid that has permissions on the host.

**Comment by jmkhael** [comment]
indeed. that's what i did with the group-add.

**Comment by cbornet** [comment]
Note : we should probably force the uid/gid of the jhipster user to a defined value. This is what is done in the [node Dockerfile](https://github.com/nodejs/docker-node/blob/master/6.9/Dockerfile) for instance.

**Comment by cbornet** [comment]
@jmkhael I mean you shouldn't need to do any `groupadd` !

**Comment by cbornet** [comment]
Just saw that my earlier comment about using -u 1000 is wrong since we currently don't force the jhipster uid.

**Comment by jmkhael** [comment]
@cbornet i retried without the group-add it doesn't seem to work. 

This is what happens:

```
docker run --name jhipster \
    -v $(which docker):/usr/bin/docker \
    -v /data/apps/jhipster/app/.m2:/home/jhipster/.m2 \
    -v /data/apps/jhipster/app/.gradle:/home/jhipster/.gradle \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /data/apps/jhipster/app:/home/jhipster/app \
    -v /lib64/libdevmapper.so.1.02:/usr/lib/x86_64-linux-gnu/libdevmapper.so.1.02 \
    -v /lib64/libudev.so.0:/usr/lib/x86_64-linux-gnu/libudev.so.0 \
    -p 8080:8080 -p 3000:3000 -p 3001:3001 -d -t jhipster/jhipster

```

Knowing that on the host:
$ id
uid=15085(jmkhael) gid=5000(murex) groups=5000(murex),979(docker)

```
docker exec -it --user=15085 jhipster bash
I have no name!@87c737c45b2d:/home/jhipster/app$ docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
I have no name!@87c737c45b2d:/home/jhipster/app$ id
uid=15085 gid=0(root) groups=0(root)
```

**Comment by cbornet** [comment]
Try `docker exec -it --user=15085:979 jhipster bash`
But then you will have another issue : the uid/gid you doesn't exist in the docker container. And bower doesn't like that...

**Comment by jmkhael** [comment]
@cbornet indeed. 
I also faced other errors related to permissions...

I have no name!@25bfc2bfe160:/home/jhipster/appdocker$ yo jhipster:docker-compose
/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

```
I have no name!@25bfc2bfe160:/home/jhipster/app/docker$ yo jhipster:docker-compose
/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/.config'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at sync (/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:77:24)
    at Object.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:38:13)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:172:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

The group-add works for most cases till now.

**Comment by cbornet** [comment]
Oh ! I didn't see you were talking of the `--group-add` option ! Yes, that should work !

**Comment by cbornet** [comment]
@jmkhael tested the group-add and it works well. Good catch !

**Comment by cbornet** [comment]
@jmkhael would you PR to add this to the jhipster.github.io doc ?

**Comment by jmkhael** [comment]
@cbornet: I will do so.

I will also prepare an JHipster image for the Raspberry Pi.
I can submit a pull request for that too if you think it is worth sharing.

**Comment by jmkhael** [comment]
I've created [Pull 368](https://github.com/jhipster/jhipster.github.io/pull/368) for the documentation.

**Comment by pascalgrimaud** [comment]
I think documentation should be enough, as it's a specific use case

**Comment by jdubois** [comment]
OK, I've had a look at it and it's good -> I just want to do a few changes before merging
