### ISSUE TITLE
gulp/browserSync doesn't serve the page

### ISSUE THREAD

**Issue by kennyx46** [jhipster/generator-jhipster#4812]
##### **Overview of the issue**

gulp/browserSync doesn't serve the page

##### **Reproduce the error**
start both processes 
`gulp`
`./mvnw`

press ctrl+shift+r in the browser few times in a row or run protractor e2e test few times in a row (sometimes 3-4 times is enough, sometimes about 10). After few times the loading page chrome indicator is shown but it takes about 2 minutes to actually load the page. This is critical for protractor tests, as it does not start running tests and fails with timeout error (I have about 20 seconds timeout).

The app is very small, no big amount of code.

##### **JHipster Version(s)**

`generator-jhipster@3.4.0`

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

`{  
    "generator-jhipster": {      
    "jhipsterVersion": "3.4.0",
    "baseName": "hpweb",  
    "packageName": "com.hammerpriced.hpweb",  
    "packageFolder": "com/hammerpriced/hpweb",  
    "serverPort": "8080",  
    "authenticationType": "session",  
    "hibernateCache": "ehcache",  
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "06b4f1ce9ee6f8c4f109ea229b71b1d3f7853163",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}`

##### **Browsers and Operating System**

`gulp  
CLI version 3.9.1  
Local version 3.9.1  `

`macOS Sierra 10.12.1`

`Google Chrome	55.0.2883.95`

**Comment by jdubois** [comment]
tons of people (including me) are using this all the time, so I'm pretty confident it works :-)

As you are using a rather old version of JHipster, I'm guessing this is an environment issue between the BrowserSync version and Chrome. Could you try a newer version?

**Comment by pascalgrimaud** [comment]
Just tested it and I dont have the issue.
Reading your ticket, it seems you start gulp first, then mvnw ? It should be mvnw first, then gulp, instead

1/ running mvnw alone -> can you access to the application ? http://localhost:8080
2/ do you have some antivirus or addblock in chrome?

**Comment by jdubois** [comment]
Oh yes, and we already had tons of false issues because of ad blockers... Have a look with another, "clean" browser.
