### ISSUE TITLE
NG2: no error handling on GET one entity

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#4823]
##### **Overview of the issue**

Error while loading details of an entity is not handled

##### **Reproduce the error**

Create an entity called `Player`.

Modify resource method `getPlayer(id)` so that it throws a RuntimeException.

It returns an HTTP error 500 with correct JSON response:

```
{
  "message" : "error.internalServerError",
  "description" : "Internal server error",
  "fieldErrors" : null
}
```

Click on view button on list of entities, the transition to detail state is made but the view is empty.

The console shows an error in `PlayerDetailComponent.load`

##### **Suggest a Fix**

The entity load should probably be done in resolve of `PlayerDetailState` so that the transition is not done.
Then in terms of UI, maybe an alert should be displayed.

##### **JHipster Version(s)**

Current master ng2 commit 7222db7c7f8794092a4f9a4a7ada1e9ae06f7c82

**Comment by gmarziou** [comment]
I have been able to resolve the entity before transitioning to detail state and when there is an error the transition fails and the user stays on list view.

~~~typescript
export const playerDetailState = {
    name: 'player-detail',
    parent: 'entity',
    url: '/player/:id',
    data: {
        authorities: ['ROLE_USER'],
        pageTitle: 'parattApp.player.detail.title'
    },
    views: {
        'content@': { component: PlayerDetailComponent }
    },
    resolve: [
        {
            token: 'player',
            deps: [Transition, PlayerService],
            resolveFn: (trans: Transition, playerService: PlayerService) => {
                let id = trans.params()['id'];
                return playerService.find(id).toPromise();
            }
        }
    ]
};
~~~

with a very thin component which declares the resolved player as an injected value:

~~~typescript
import {Component, Input} from "@angular/core";
import {Player} from "./player.model";

@Component({
    selector: 'jhi-player-detail',
    templateUrl: './player-detail.component.html'
})
export class PlayerDetailComponent {

    @Input()
    player: Player;
}
~~~

The only thing I don't know is how to show an error message to the user when player could not be resolved. @christopherthielen could you explain me please?

**Comment by christopherthielen** [comment]
A couple of options I've used in the past:

Use something like a Toast library to show an error when they click the link -- something like http://codeseven.github.io/toastr/demo.html

Something like (pseudo code):
```js
transSvc: TransitionService;
transSvc.onError({ to: 'player-detail' }, trans => 
  trans.injector().get(ToasterService).toast("Error: activating player-detail: " + trans.error()));
```

Another way is to handle the transition promise rejection from .go().

```js
@Component({})
class SomeComponent {
  constructor(public router: UIRouter) {}
  playerDetail(player) {
    router.stateService.go('player-detail', { id: player.id }).catch(this.handleError);
  }
  handleError(trans: Transition) {
    // handle error
  }
}
```

As a note to self: this second example might be a good argument for a new attribute related to `uiSref` for handling errors, such as `uiSrefOnError="handleError(error)"`

**Comment by gmarziou** [comment]
Thanks a lot.

I implemented successfully first option as a global hook in `register-transition-hooks.ts`

~~~typescript
    // When a transition failed, show an alert
    transitionService.onError({}, (transition: Transition) => {
        alertService.error('global.messages.error.transitionerror', {error: transition.error()}, null);
    });
~~~

Ideally, I'd like to be able to register specific hooks per entity (from within entity source folder) but it seems hooks can be registered only by `UIRouterModule.forRoot()` and not by `UIRouterModule.forChild()`.

**Comment by deepu105** [comment]
@gmarziou please note that `AlertService` has been moved to `ng-jhipster` lib

**Comment by gmarziou** [comment]
OK, it's a good thing. I have looked at it and I may contribute some comments.
I must say that the comments from ui-router are very good, great work @christopherthielen

**Comment by gmarziou** [comment]
I put this on hold until we clarify whether we support both ui-router and ng router or only ng-router.

**Comment by jdubois** [comment]
It's going to be NG Router, so can we remove the "on-hold" tag?

**Comment by gmarziou** [comment]
Sure, I close it. I check the behavior with ng router.
