### ISSUE TITLE
Model importation failing without error.

### ISSUE THREAD

**Issue by Paul-Etienne** [jhipster/generator-jhipster#4833]
I am working on a JHipster application and had successfully imported my model back in summer.
Now though, I must have updated the generator because the importation isn't working anymore.
The `jhipster-uml file.jh` command is throwing an error  :

> Cannot read property 'hasOwnProperty' of undefined

But this is a normal behaviour since a more recent version of jhipster-uml.
However, the command `yo jhipster:import-jdl file.jh` isn't working either, the only result I am getting from this is :

> The jdl is being imported.

And nothing else happens.

To reproduce this error, creating a fresh new app with the version I am using and trying to import this sample model should be enough :

`entity Person {
	name String,
	age Integer
}`

An issue had already been posted here : https://github.com/jhipster/generator-jhipster/issues/3724
But it got closed without a fix (the only "fix" the author had found was downgrading to a former version, which doesn't satisfy me).
Apparently this issue had been fixed actually, I am facing the same problem though.

This is my .yo-rc.json file :

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "vraiJhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "key",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}

I am not sharing the entity configuration for confidential purposes.

**Comment by deepu105** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by pascalgrimaud** [comment]
Sorry but it wil be hard to help you if we dont have enough information to reproduce your issue.
