### ISSUE TITLE
elasticsearch is broken

### ISSUE THREAD

**Issue by xiangwan** [jhipster/generator-jhipster#4836]
##### **Overview of the issue**

this file 
generators/entity/templates/client/angular/src/main/webapp/app/entities/pagination-template.ejs
 has lost search() and close() 

and the input  name attribute must be exist
 <input type="text" class="form-control" [(ngModel)]="searchQuery" name="searchQuery"

##### **JHipster Version(s)**

4.0

My English is not good,I hope you can understand. 

哪位同学看到了，可以帮忙翻译下吗，上面写的不知道能不能被理解。

##### **Overview of the issue**

这个文件：
generators/entity/templates/client/angular/src/main/webapp/app/entities/pagination-template.ejs
缺少了 search() 和close() 方法。
 

这个文件：
generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management.component.html
搜索框的input必须有name属性，因为angular要求的
 <input type="text" class="form-control" [(ngModel)]="searchQuery" name="searchQuery"

##### **JHipster Version(s)**

github上最新的代码 4.0

**Comment by jdubois** [comment]
That's normal, JHipster 4 is being coded, this part isn't finished yet, we know it.
Help is welcome if you want to do a PR.

**Comment by xiangwan** [comment]
I will try do this later
