### ISSUE TITLE
Jhipster generated entity compilation issue with entityTableName 'Test'

### ISSUE THREAD

**Issue by PrashanthRaghu** [jhipster/generator-jhipster#4837]
##### **Jhipster generated entity compilation issue**

Latest source code of entity generator throws a compilation issue in the maven test compile phase

P.S: I am using the latest code of jhipster from github.

##### **Motivation for or Use Case**

I am trying to generate a basic entity on a project.

##### **Reproduce the error**

$yo jhipster
Monolithic Project, Angular 2, Mysql production and development, No Sass

$yo jhipster:entity Test

No fields, no relations.

##### **Suggest a Fix**

I am not knowledgeable in this.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.1",
    "baseName": "sample2",
    "packageName": "com.sensei.newapp",
    "packageFolder": "com/sensei/newapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "334d62b449c3256080d1eddc05f522220897c443",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
    "fluentMethods": true,
    "relationships": [],
    "fields": [],
    "changelogDate": "20170110054229",
    "dto": "mapstruct",
    "service": "serviceImpl",
    "entityTableName": "test",
    "pagination": "pager"
}

**Comment by pascalgrimaud** [comment]
Can you:
- provide your log error
- use `yo jhipster:info` : you didn't show your node, yarn, npm version, etc.

**Comment by pascalgrimaud** [comment]
Ok, I see. There is a conflict between:
- your entity: com.sensei.newapp.domain.Test
- the class from junit: org.junit.Test

Maybe we should exclude this entity name.

**Comment by jdubois** [comment]
Yes we should exclude the entity name
