### ISSUE TITLE
Error when gulp install with angular1 + websocket + noi18n

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#4838]
##### **Overview of the issue**

When generating a project with angular1 + websocket + noi18n,
there is an error in the tracker.state.js

Here the error log:

```
$ gulp install
[08:12:56] Using gulpfile ~/tmp/07-toto/gulpfile.js
[08:12:56] Starting 'install'...
[08:12:56] Starting 'inject:test'...
[08:12:56] Starting 'inject:vendor'...
[08:12:56] Starting 'ngconstant:dev'...
[08:12:56] Finished 'install' after 169 ms
[08:12:56] Finished 'ngconstant:dev' after 139 ms
[08:12:56] gulp-inject 19 files into karma.conf.js.
[08:12:56] gulp-inject 20 files into index.html.
[08:12:56] Finished 'inject:test' after 212 ms
[08:12:56] Finished 'inject:vendor' after 174 ms
[08:12:56] Starting 'inject:dep'...
[08:12:56] Finished 'inject:dep' after 4.83 μs
[08:12:56] Starting 'inject:app'...
[08:12:56] gulp-notify: [JHipster Gulp Build] Error: Error in parsing: "admin/tracker/tracker.state.js", Line 24: Unexpected token )
[08:12:56] gulp-inject Nothing to inject into index.html.
[08:12:56] Finished 'inject:app' after 224 ms
[08:12:56] Starting 'inject:troubleshoot'...
[08:12:56] gulp-inject Nothing to inject into index.html.
[08:12:56] Finished 'inject:troubleshoot' after 9.02 ms
```

##### **Suggest a Fix**

In fact, there is a simple missing `}`

As the copy template is specific (see https://github.com/jhipster/generator-jhipster/blob/master/generators/client/files-angularjs.js#L238-L245)
immediatly, I don't see where it can be fixed.

Maybe here:
https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L1093-L1097

##### **JHipster Version(s)**

Current master

```
toto@0.0.0 /home/pgrimaud/tmp/11-toto
└── generator-jhipster@3.12.2  -> /home/pgrimaud/projects/jhipster/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "toto",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "356298c542ce158727aa755f54f22b70a3a077e9",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular1",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.7.4

node: v6.9.2

npm: 4.0.5

bower: 1.8.0

gulp:
[08:51:35] CLI version 1.2.2
[08:51:35] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.18.1

Docker version 1.12.5, build 7392c3b

docker-compose version 1.9.0, build 2585387

**Comment by jdubois** [comment]
Very surprised we haven't found this before! Can you do a PR?

**Comment by pascalgrimaud** [comment]
I didn't find a quick fix, that's why I didn't PR immediatly.
I'll try to have a look tonight (as day work begins right now...)

**Comment by deepu105** [comment]
@pascalgrimaud could you try with this regex
`/(\,[\s]*(resolve)\:[\s]*[\[]?[\{][\s]*(translatePartialLoader|token: 'translate')[\[]?[\'a-zA-Z0-9\$\,\(\)\{\.\<\%\=\-\>\;\s\:\[\]]*(\;[\s]*\}\][\s]*\}|\)[\s]*\}\]))|(import\s\{\s?[a-zA-Z0-9\=\<\>\%]*LanguageService\s?\}\sfrom\s[\"|\']ng-jhipster[\"|\']\;)/g`

**Comment by deepu105** [comment]
you can see it in action here http://regexr.com/3f1f2

**Comment by pascalgrimaud** [comment]
it seems to fix the issue. I'm doing the PR!
Thanks!
