### ISSUE TITLE
Datepicker and pagination not affected by internationalization

### ISSUE THREAD

**Issue by Sarevok117** [jhipster/generator-jhipster#4841]
##### **Overview of the issue**

Datepicker still has the bottom buttons in English even when another language is selected.
Days and months are all translated though.

The pagination, especially the "Showing n - n of n items." isn't translated either.
 
##### **Reproduce the error**

I simply generated an entity with a ZonedDateTime field and enabled the pagination.

##### **Suggest a Fix**

I fixed the datepicker by adding this to the controller:

`        
function openCalendar (date) {
        	vm.datePickerOpenStatus[date] = true;
        	uiDatetimePickerConfig.buttonBar.today.text = $translate.instant('global.datepicker.today');
        	uiDatetimePickerConfig.buttonBar.now.text = $translate.instant('global.datepicker.now');
        	uiDatetimePickerConfig.buttonBar.time.text = $translate.instant('global.datepicker.time');
        	uiDatetimePickerConfig.buttonBar.date.text = $translate.instant('global.datepicker.date');
        	uiDatetimePickerConfig.buttonBar.clear.text = $translate.instant('global.datepicker.clear');
        	uiDatetimePickerConfig.buttonBar.close.text = $translate.instant('global.datepicker.close');
        }
`

However it seems more like a hack than a real fix. I also believe the pagination issue could be solved a similar way.

##### **JHipster Version(s)**

Using JHipster 3.12.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

`{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "mdc",
    "packageName": "com.carrefour.fr.mdc",
    "packageFolder": "com/carrefour/fr/mdc",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "7821c9c0b7b41b1eda73a4f612b2f25d308ee66e",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}`

##### **Browsers and Operating System**

Both the issues occur on Chrome and Edge.

**Comment by jdubois** [comment]
I remember coding this: indeed, the DatePicker isn't internationalized. This is an external component, from Angular UI, and its internationalization system doesn't really work well with Angular Translate.

-> it looks like you found a solution, so a PR is welcome

For the pager it's another issue, so that should be another ticket.

Anyway, this AngularJS 1 code, we're not going to improve it now, as this will be replaced by Angular 2.

So if you do a PR, we can of course merge it, and otherwise this will become deprecated with our AngularJS 1 support. And by the way, we probably have the same issue with Angular 2, as once again we are not developing those components.

**Comment by jdubois** [comment]
I'm closing this as this is a limitation in JHipster 3.x (it comes from an external component, not our specific code), and it will be replaced in JHipster 4 (where we probably still have this kind of issue).
If anybody wants to improve this, a PR is definitely welcome.
