### ISSUE TITLE
Add FeignConfiguration to uaa server

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#4847]
##### **Overview of the issue**
The uaa server centralises Authentication and Authorisation mechanism, thus it's responsible of the `User` concept. In a micro-services architecture the components interacts to get all the information. In the current design the uaa component isn't configured to use Feign.

##### **Motivation for or Use Case**

In my particular case, the User has a set of devices. Before adding a device to the user and I want to interact with the device-management micro-service to ensure the device exists and retrieve its information.

##### **Suggest a Fix**

The fix seems easy (copy/paste the configuration) but I'm sure I'm missing something...

**Comment by jdubois** [comment]
@xetys you're the boss on this part, can you take a look?
@danielpetisme I guess it's just that this wasn't coded yet, I'm not sure there's any issue or tricky part here

**Comment by xetys** [comment]
there are the good news and the bad news...

the good: if you just copy all the things into the UAA to retrieve information from other services using OAuth 2 client auth flow, then it will simply work as expected.

The less good: despite the UAA works along the OAuth2 protocol, it initially performs a auth request to itself, to to log itself in, to get a token. In theory the UAA could skip this step, as it is able to generate a token directly, not via request. For this direct way I still got no "clean" way, as for my projects I can live with this double requesting.

If you don't have any bigger issues with having a UAA which logs itself in into UAA, you can do this.

As an official way, I would prefer to have a workaround (maybe in jhipster libaray) to get the token directly....but in fact you are the first one who asks for this :smile:

**Comment by jdubois** [comment]
OK so I guess there is a solution for the moment, and if @xetys has the time, and if enough people want this, this could be improved and part of JHipster.
As UAA is still in beta, and this seems to be quite specific, I'm closing this -> first we release a version that works, then we improve it :-)

**Comment by danielpetisme** [comment]
Since my user was involved in a bidirectionnal relation, I deported the details to the other service and add `<not-uaa-service>/api/users/` and `<not-uaa-service>/api/account` endpoints. From a design point of view is not completely stupid (even if I would prefer to gather routes).

@xetys I think having a kind of loopback authentication for the uaa service isn't chocking in a first implementation. 

@jdubois 👍  Release first, Improve after (BTW I have also an issue on using the current user token rather than the `internal` one but it's another story 😄 )
