### ISSUE TITLE
[FEATURE] Add support for long paths in Windows for liquibaseDiffChangelog gradle task

### ISSUE THREAD

**Issue by sergio-otero** [jhipster/generator-jhipster#4848]
Gradle has a known problem with long classpaths in Windows, as it generates an exception "java.io.IOException: CreateProcess error=206, The filename or extension is too long"

http://stackoverflow.com/questions/39756475/execution-of-gradle-bootrun-fails

JHipster has already applied the workaround to the bootRun task but it's missing in liquibaseDiffChangelog in v3.12.2 as can be checked executing "gradlew liquibaseDiffChangelog --stacktrace --info"

I've already applied the same workaround as in bootRun in gradle/liquibase.gradle and it should be easy to integrate into the generator

From:

```
	task liquibaseDiffChangelog(dependsOn: compileJava, type: JavaExec) {
	    group = "liquibase"
	
	    classpath sourceSets.main.runtimeClasspath
	    classpath configurations.liquibase
	            
	    main = "liquibase.integration.commandline.Main"
	
	    args "--changeLogFile=src/main/resources/config/liquibase/changelog/" + buildTimestamp() +"_changelog.xml"
	    args "--referenceUrl=hibernate:spring:com.test.jhipster.fooservice.domain?dialect=org.hibernate.dialect.MySQL5InnoDBDialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"
	    args "--username=fooservice"
	    args "--password=fooservice"
	    args "--url=jdbc:mysql://localhost:3306/fooservice"
	    args "--driver=com.mysql.jdbc.Driver"
	    args "diffChangeLog"
	    
	}
```

To:

```
if (OperatingSystem.current().isWindows()) {
	task pathingLiquibaseJar(type: Jar) {
        dependsOn configurations.liquibase
        appendix = 'pathingLiquibase'

        doFirst {
            manifest {
                attributes 'Class-Path': 
               		configurations.liquibase.plus(sourceSets.main.runtimeClasspath)
                	.collect {
                    	it.toURL().toString().replaceFirst(/file:\/+/, '/')
                	}.join(' ')
            }
        }
    }

	task liquibaseDiffChangelog(dependsOn: compileJava, type: JavaExec) {
	    group = "liquibase"
	
		dependsOn pathingLiquibaseJar
		doFirst {
	    	classpath = files(pathingLiquibaseJar.archivePath)
	    }
	
	    main = "liquibase.integration.commandline.Main"
	
	    args "--changeLogFile=src/main/resources/config/liquibase/changelog/" + buildTimestamp() +"_changelog.xml"
	    args "--referenceUrl=hibernate:spring:com.test.jhipster.fooservice.domain?dialect=org.hibernate.dialect.MySQL5InnoDBDialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"
	    args "--username=fooservice"
	    args "--password=fooservice"
	    args "--url=jdbc:mysql://localhost:3306/fooservice"
	    args "--driver=com.mysql.jdbc.Driver"
	    args "diffChangeLog"
	    
	}
} else {
	task liquibaseDiffChangelog(dependsOn: compileJava, type: JavaExec) {
	    group = "liquibase"
	
	    classpath sourceSets.main.runtimeClasspath
	    classpath configurations.liquibase
	            
	    main = "liquibase.integration.commandline.Main"
	
	    args "--changeLogFile=src/main/resources/config/liquibase/changelog/" + buildTimestamp() +"_changelog.xml"
	    args "--referenceUrl=hibernate:spring:com.test.jhipster.fooservice.domain?dialect=org.hibernate.dialect.MySQL5InnoDBDialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"
	    args "--username=fooservice"
	    args "--password=fooservice"
	    args "--url=jdbc:mysql://localhost:3306/fooservice"
	    args "--driver=com.mysql.jdbc.Driver"
	    args "diffChangeLog"
	    
	}
}
```

**Comment by atomfrede** [comment]
Would you mind to create a PR with your changes?

**Comment by deepu105** [comment]
we are already doing the manifest solution for gatling and prod build for
windows already> i wonder if there is a way to extract this into a common
method or somthing


Thanks & Regards,
Deepu

**Comment by sergio-otero** [comment]
I'm not an expert in NodeJS, Yeoman, etc., but I'll give it a try this weekend

**Comment by jdubois** [comment]
@sergii-ostroverkhov did you have the time to test this during the week-end?

**Comment by sergii-ostroverkhov** [comment]
@jdubois I guess, you have meant @sergio-otero

**Comment by jdubois** [comment]
Oh sorry @sergii-ostroverkhov it autocompleted your name because you also contributed to the project!
Too many contributors :-)

**Comment by sergio-otero** [comment]
Just submitted the PR.

Testing in Windows i found that depending on the order of 'configurations.liquibase.plus' vs 'sourceSets.main.runtimeClasspath' i get a runtime error 'Unexpected error running Liquibase: liquibase.structure.core.ForeignKey.addForeignKeyColumn(Lliquibase/structure/core/Column;)Lliquibase/structure/core/ForeignKey;'

The problem is that the classpath has 'liquibase-core-3.5.3.jar' and 'liquibase-core-3.4.2.jar'. Depending on the classpath order, it doesn't work.

Before making changes, i've tested in a new brand jhipster linux project and the problem also happens, so i've changed the order of the classpath clauses in both Windows and Linux to first configurations.liquibase.plus' and then 'sourceSets.main.runtimeClasspath'.

Please confirm that the problem is real and the change is correct.

Maybe someone should take a look at why there is 2 liquibase versions together.

**Comment by jdubois** [comment]
Liquibase should be at version 3.5.3, it's probably a mistake in the Gradle build -> I'm upgrading it and linking it to this ticket.

**Comment by sergio-otero** [comment]
I've found a problem with liquibaseDiffChangeLog with LocalDatime being converted to tinyblob due to having in the classpath liquibase hibernate-core-5.0.11 and hibernate-core-5.2.4.

Now that the liquibase version is fixed in gradle.build, the line

configurations.liquibase.plus(sourceSets.main.runtimeClasspath)

can be changed to 

sourceSets.main.runtimeClasspath.plus(configurations.liquibase)

an it works, generating a timestamp field.

I'll try on linux at home to see if it's also affected and will do another PR.
