### ISSUE TITLE
liquibase:diff and required relation with entity generator

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#4849]
##### **Overview of the issue**
When generating an entity with 'yo jhipster:entity' and specifying a required relation.
If we run 'mvn clean compile liquibase:diff', the changelog contains a dropNotNullConstraint.

the generator produces in the java class:
`@ManyToOne
    @NotNull
    private User user;`

##### **Motivation for or Use Case**

It is a required relation so we do not want a dropNotNullConstraint
##### **Suggest a Fix**
the generator should produce:
`  @ManyToOne(optional = false)
    @NotNull
    private User user;`

and with this, liquibase does not generate the dropNotNullConstraint

##### **JHipster Version(s)**
jhipster 3.12.1 (maybe it is already fixed in master branch but I don't know yet where I can check this)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

> {
>     "fluentMethods": true,
>     "relationships": [
>         {
>             "relationshipName": "freeMailType",
>             "otherEntityName": "freeMailType",
>             "relationshipType": "many-to-one",
>             "relationshipValidateRules": [
>                 "required"
>             ],
>             "otherEntityField": "code"
>         },
>         {
>             "relationshipName": "user",
>             "otherEntityName": "user",
>             "relationshipType": "many-to-one",
>             "relationshipValidateRules": [
>                 "required"
>             ],
>             "otherEntityField": "login",
>             "ownerSide": true
>         }
>     ],
>     "fields": [
>         {
>             "fieldName": "dayDate",
>             "fieldType": "LocalDate",
>             "fieldValidateRules": [
>                 "required"
>             ]
>         }
>     ],
>     "changelogDate": "20170112170527",
>     "dto": "mapstruct",
>     "service": "serviceClass",
>     "entityTableName": "free_mail_day",
>     "pagination": "pagination"
> }

**Comment by gmarziou** [comment]
Please include your .yo-rc.json as it could be related to your database or other options

**Comment by jdubois** [comment]
Without your `.yo-rc.json` we can't test it, this highly depends on the database you use.

Then, you also need to check if it's a Liquibase bug or not, this might not be our fault at all.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by ctamisier** [comment]
I am adding some info about this issue, this will help me to find out if this can fixed on jhipster side or liquibase side.

I tried with postgres 9.6 and mysql 5.7.16 and I have this same behavior.

with those JPA annotations:
`@ManyToOne `
`@NotNull `
`private User user;`
Liquibase concludes that user can be null (not what we want). 
It wouldn't be the case (I tried it) if the type is a String (not an entity relation). 

With `@NotNull` and a String, we have the following liquibase behavior:
> liquibase intelligently picks up on these constraints and translates them into database constraints
(http://stackoverflow.com/questions/7439504/confusion-notnull-vs-columnnullable-false)

But it doesn't seem to be the case when `@ManyToOne` and `@NotNull` are used. 

Should liquibase  fix this ? I don't think because these annotations (like `@NotNull`) are "more about validation than database schema". 

I would say the use of `@ManyToOne(optional = false)` would be more suitable because this is about the database schema (and this works, liquibase does not add a dropNotNullConstraint in a migration).

I will check on liquibase side, if this could be a bug or if it is voluntarily unsupported.

**Comment by jdubois** [comment]
Re-opening this as you gave more information

**Comment by jdubois** [comment]
Yes you are correct, I don't think Liquibase picks up validation annotations -> what you suggest makes sense, can you test it?
Then that could be an easy PR if you want to do it (otherwise we can do it, of course, but it's just so you get credit for your work)

**Comment by ctamisier** [comment]
Yes I will check the entity generator code.

Actually I realized that it does not work even with a String type. (The entity generator adds nullable=false on the `@Column`, and I didn't pay attention to this :( ).

So it does not intelligently picks up on the `@NotNull` annotation as I mentionned.

So the work would be to add `@ManyToOne(optional = false)` when we choose that the field is required. (I tried and this is working)

When we choose `@OneToOne`, the required option is not available, so there is nothing to do here but this would be a new feature. I think the required option should be available as well.

**Comment by ctamisier** [comment]
there are 2 solutions and both works (I tried):
either modifying `@ManyToOne(optional = false)` 
or adding a new annotation`@JoinColumn(nullable = false)`

**Comment by jdubois** [comment]
I haven't tested, but doing `@ManyToOne(optional = false)` is one less line, and easy to read, so I would go with this.
Can you make the PR? Have a look at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md it's honestly not that difficult

**Comment by ctamisier** [comment]
Yeah I did the change but I want to run it locally.
I did `ln -s ~/projects/generator-jhipster generator-jhipster` in my `/usr/local/lib/node_modules` like I do when I want to try a local generator-jhipster.

But it does use the templates in the generator/server directory but not the ones in generator/entity as I updated `_Entity.java` file...

**Comment by jdubois** [comment]
You need to do a "link" in the project itself (same as doing a "ln -s" in fact...), see https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup

BTW this isn't updated for JHipster 4, and we now support Yarn -> works exactly the same, but much faster!

**Comment by ctamisier** [comment]
Ok I got it

**Comment by jdubois** [comment]
Closing as the PR is merged

**Comment by jdubois** [comment]
Thanks @ctamisier for the PR!!
