### ISSUE TITLE
Failed to generate Blob, AnyBlob, ImageBlob, TextBlob types

### ISSUE THREAD

**Issue by nghib** [jhipster/generator-jhipster#4856]
#### **Overview of the issue**

yo jhipster:entity FileStore --regenerate

Found the .jhipster/FileStore.json configuration file, entity can be automatically generated!

The entity FileStore is being updated.

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: /Users/nghib/spring/generator-jhipster/generators/entity/templates/server/src/test/java/package/web/rest/_EntityResourceIntTest.java:125
    123|     private static final String <%=defaultValueName %> = "<%=sampleTextString %>";
    124|     private static final String <%=updatedValueName %> = "<%=updatedTextString %>";
 >> 125| <%_ } else if (fieldType == 'Integer') { _%>
    126|
    127|     private static final Integer <%=defaultValueName %> = <%= defaultValue %>;
    128|     private static final Integer <%=updatedValueName %> = <%= updatedValue %>;

Cannot read property 'replace' of undefined
    at eval (eval at compile (/Users/nghib/spring/generator-jhipster/node_modules/ejs/lib/ejs.js:495:12), <anonymous>:207:45)
    at returnedFn (/Users/nghib/spring/generator-jhipster/node_modules/ejs/lib/ejs.js:524:17)
    at Object.exports.render (/Users/nghib/spring/generator-jhipster/node_modules/ejs/lib/ejs.js:332:37)
    at process (/Users/nghib/spring/generator-jhipster/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/Users/nghib/spring/generator-jhipster/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/Users/nghib/spring/generator-jhipster/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/Users/nghib/spring/generator-jhipster/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/nghib/spring/generator-jhipster/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at constructor.template (/Users/nghib/spring/generator-jhipster/node_modules/yeoman-generator/lib/actions/actions.js:124:11)
    at blockTemplate.templates.map.templateObj (/Users/nghib/spring/generator-jhipster/generators/generator-base.js:1752:38)

##### **Reproduce the error**

FileStore.json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "contentType",
            "fieldType": "String"
        },
        {
            "fieldName": "size",
            "fieldType": "String"
        },
        {
            "fieldName": "path",
            "fieldType": "String"
        },
        {
            "fieldName": "content",
            "fieldType": "Blob" /// if this is changed to "String", "Long", "Boolean", ... It works well
        }
    ],
    "changelogDate": "20161202031626",
    "dto": "mapstruct",
    "service": "serviceClass",
    "entityTableName": "file_store",
    "pagination": "pagination"
}

##### **Suggest a Fix**

Blob, AnyBlob, ImageBlob, TextBlob types is missing supported inside generator-jhipster/generators/entity/templates/server/src/test/java/package/web/rest/_EntityResourceIntTest.java

##### **JHipster Version(s)**

JHipster master branch - git hash: f2befef828c5703bcc5f64744cd0c1c3496ffd85

**Comment by pascalgrimaud** [comment]
Same comment
Plz use yo jhipster:info
So we have your .yo-rc.json to reproduce and all version about your tools too

**Comment by nghib** [comment]
this is my .yo-rc.json

{
  "generator-jhipster": {
    "baseName": "myapp",
    "packageName": "com.rf.myapp",
    "packageFolder": "com/rf/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "73a2b4f6246112334728c77c8e215b71ae3025f2",
    "useSass": true,
    "yarn": true,
    "applicationType": "monolith",
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "myapp",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "vi"
    ],
    "serviceDiscoveryType": false,
    "jhipsterVersion": "3.12.1",
    "clientFramework": "angular1"
  }
}

**Comment by gmarziou** [comment]
@nghib, If Pascal asked you to paste infos from `yo jhipster:info`, it's because it lists also your environment like nodejs version, etc... 
Your `.yo-rc.json` file is not enough.

**Comment by jdubois** [comment]
I'm seeing `"clientPackageManager": "yarn"` here, so you're on the master branch, this hasn't been released yet.
We can't support what's on the master branch, this is currently being developed, and not ready to use. So that's perfectly normal you have issues, please use a released version if you want to have something stable.

**Comment by pascalgrimaud** [comment]
I just wonder if it's possible to have `"fieldType": "Blob"` in your json file
It should be `image`, `any` or `text`, according to this code: https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/prompts.js#L601-L622

Any way, you didn't give information, on how you generate the json file: with entity sub generator, with jdl studio, etc...

**Comment by nghib** [comment]
Thanks @pascalgrimaud so much. It's my bad. I mapped jdl datatypes to json entity and It's not identical. I enjoy hacking .json entities directly because feeling debug jdl take more time.
