### ISSUE TITLE
Missing file with angular 2 and social 

### ISSUE THREAD

**Issue by ggaulard** [jhipster/generator-jhipster#4862]
##### **Overview of the issue**

Missing file

##### **Reproduce the error**

After generating the angular 2 (on master branch) with social there is a missing file:
There it is:
Module not found: Error: Can't resolve './login.component.html' in '/Users/ggaulard/Workspace/zenika/platon/src/main/webapp/app/account/social'

##### **JHipster Version(s)**

"jhipsterVersion": "3.12.2",

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "platon",
    "packageName": "com.zenika.platon",
    "packageFolder": "com/zenika/platon",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "...",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-swagger-cli",
        "version": "2.0.5"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}

##### **Browsers and Operating System**

Mac

**Comment by jdubois** [comment]
Hey welcome back @ggaulard :-)
To everyone on the team, we own *a lot* to @ggaulard because he's the one who created our logo!!

To answer your question, it's probably not finished yet (not sure we coded the social login yet for Angular 2!!).

**Comment by jdubois** [comment]
I just checked https://github.com/jhipster/generator-jhipster/issues/4301 and indeed that's not tested, and probably not coded yet.

For Angular 2 we are only focusing on the "default" options at the moment, but having most of the options (like this one) shouldn't be very hard.

This allows us to work on a much better developer experience than what you currently have, and hopefully release something very soon.

-> I'm closing this as it's just not coded yet (that's the trouble when you're on the master branch!!), but if you want to fix this a PR shouldn't be very hard, and is of course very welcome
