### ISSUE TITLE
Marketplace is broken again

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4866]
Going to https://jhipster.github.io/modules/marketplace/#/list only shows 10 modules, when there should be 31.... Maybe they added some pagination ?

**Comment by deepu105** [comment]
Hey there is a new official npm search api. May be ill give that a shot

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
Yes that's the way to go if that supports CORS... By the way we have the same issue with the "install modules from the marketplace" question in the generator, so this also needs to be changed (and in that case couldn't we use the NPM CLI? How is Yeoman doing this?) - @gzsombor you coded this part, does this make sense to you?

**Comment by deepu105** [comment]
I'm gonna give https://npms.io/ a shot which is the search engine used by NPM cli and yes from the generator we should be able to use it

https://npms.io/search?q=keywords%3Ajhipster-module
