### ISSUE TITLE
Remove the use of the Web layer in the service layer

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4867]
As discussed in #4865

We have some Web/REST objects being called from the service layer, which is an architecture error, and causes package tangling (this should be seen by Sonar, I need to check).

Typically, the `ManagedUserVM` shouldn't be used in the service layer, that's why we have a `UserDTO`-> the `VM` is for "View Model", that's used for displaying in the Angular/HTML views, and the `DTO` is for "Data Transfer Object", that's used for transferring the object from one layer to another (if the entity isn't enough). Of course a DTO can be used as a VM, but the opposite isn't true.

**Comment by gzsombor** [comment]
In my opinion, the DTO-s should be returned from the service layer - and calling the service layer from the web layer should use DTO-s as well - so the web layer doesn't depend on the back-end domain model. This has the following advantages, at least:
* You can create and ship a separate API modul - which just contains the necessary DTO's, which can be used in any java based rest client, without exposing the domain entities
*  No more lazy loading problems during creating the DTO's, as the DTO is created _inside_ the service layer, _inside_ a transaction
* No more lazy loading problems during the JSON creation, as the DTO's doesn't have any lazy loaded, hibernate managed variables
* You can add various restrictions and validations to the DTO's, even with annotations, which can be easily verified in the call site, as opposed to calling the service with domain entities, where you can't specify easily, which constraints is needs to fulfilled.

**Comment by jdubois** [comment]
@gzsombor we totally agree for the DTO -> the VMs are different, they are only needed for displaying on the Web layer, something specific.

So we have:

- Entities by default: that's the easiest to use and manage
- DTOs as an option, served by the service layer: better for everything you just said, including lazy loading and business rules
- VMs as an option, served by the Web/REST layer: only for displaying something specific on the view layer

And you can have entities + DTO + VMs all at the same time, that's a bit complex, but if you have complex business requirements, that doesn't shock me.

**Comment by jdubois** [comment]
@gzsombor I'm pretty sure we agree here, there is just a small misunderstanding: I'm going to refactor this in a branch, and let you have a look.

**Comment by jdubois** [comment]
@gzsombor please have a look at #4877 and tell me what you think
