### ISSUE TITLE
Add remote debug configuration to Spring Boot for dev profile

### ISSUE THREAD

**Issue by fromi** [jhipster/generator-jhipster#487]
Hi,
To be able to debug with Spring Boot, I had to add to the plugin configuration in the pom.xml those lines:

```
<jvmArguments>
      -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
</jvmArguments>
```

Maybe this could be included by the the generator ?
Cheers

**Comment by davidweianibone** [comment]
Hi, I'm trying to debug my application using Netbeans. I added the line mentioned above but still cannot debug. seems like a connection issue. Do I need to add the secret key somewhere to be able to connect ?

**Comment by knasim** [comment]
same for me.  i followed and cannot attach from intellij.
