### ISSUE TITLE
Heroku deploy fails on Windows because of lack of wildcard expansion

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#4871]
##### **Overview of the issue**

Running on Windows, `yo jhipster:heroku` fails when uploading jar file because command prompt does not expand wilcard like `target\*.war` before passing it to heroku deploy task. 

Moreover, it would not work because what is passed uses forward slashes.

##### **Motivation for or Use Case**

To show some love to our Windows users ;)

##### **Reproduce the error**

~~~
yo jhipster:heroku
...
Deploying application

Uploading your application code.
This may take several minutes depending on your connection speed...
× { Error: Command failed: heroku deploy:jar target/*.war --app paratt
 !    JAR file not found: target/*.war

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'heroku deploy:jar target/*.war --app paratt' }
~~~

##### **Suggest a Fix**

`jhipster:heroku` should expand the wildcards before calling heroku-cli, this would also take of converting slashes. Alternatively, `heroku-cli` could implement it.

[Our doc](https://jhipster.github.io/heroku/) should be amended too.

##### **JHipster Version(s)**

3.12.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "paratt",
    "packageName": "com.ittf",
    "packageFolder": "com/ittf",
    "serverPort": "8100",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f99b837817b1c7d1f30fdbc487ccaf13305b6337",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "pt-br",
      "ru",
      "es"
    ],
    "serviceDiscoveryType": false,
    "clientFramework": "angular2",
    "herokuAppName": "paratt"
  }
}
~~~

##### **Browsers and Operating System**

Windows 10.

**Comment by gmarziou** [comment]
@jkutner are you still maintaining the heroku sub generator? What do you think of doing the wildcard expansion in the sub  generator?

**Comment by jkutner** [comment]
Yes, I'm maintaining. I'll get this fixed.

**Comment by gmarziou** [comment]
Thanks a lot @jkutner, I tested your fix successfully.
