### ISSUE TITLE
yo jhipster:heroku not working properly after 'heroku destroy [app name]'

### ISSUE THREAD

**Issue by lancescape** [jhipster/generator-jhipster#4875]
##### **Overview of the issue**
heroku destroyo [app name]  will make make future "yo jhipster:heroku' and such commands not work any more  due to missing herokuAppName on server

issues the yo:jhipster heroku command will result in 
~~~
Heroku configuration is starting
× { [Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "heroku apps:info --json"
 !    No app specified.
 !    USAGE: heroku info my-app
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "heroku apps:info --json"' }
~~~

##### **Reproduce the error**
execute
yo jhipster:heroku
heroku destory [herokuAppName]

##### **Suggest a Fix**
having the yo jhipster:heroku command test for existance of ther herokuApp on the server, 
1) prompt the user that it does not exist create a new app on heroku using name:   [herokuAppName - from .yo-rc.json] 
2) create the app on heroku
3) update the .yo-rc.json with app name

easy self fix once you realize jhipster puts heroku app name in .yo-rc.json

##### **JHipster Version(s)**
3.12.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "ResourceManagement",
    "packageName": "com.tripteria",
    "packageFolder": "com/tripteria",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "rememberMeKey": "51c7387177fbee1c75981acab162fad066b2a762",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ],
    "herokuAppName": "young-thicket-14182"
  }
}
~~~

**Comment by jdubois** [comment]
@jkutner I affected the issue to you, is this OK with you?

**Comment by jkutner** [comment]
@jdubois yes, please continue to do this or I will miss issues related to Heroku.

**Comment by jdubois** [comment]
@jkutner we will soon be in code freeze mode, for JHipster 4 -> will you be able to fix this in the next couple of days? Otherwise this will go for the next release

**Comment by jkutner** [comment]
I'll take a look at it today. I should be able to provide a solution before the freeze.
