### ISSUE TITLE
Use Oracle12cDialect instead of Oracle10gDialect

### ISSUE THREAD

**Issue by Rosetjau** [jhipster/generator-jhipster#4876]
##### **Overview of the issue**

Use the Hibernate dialect for the current Oracle Database version

##### **Motivation for or Use Case**

According to the [official documentation](https://jhipster.github.io/using-oracle/) only Oracle version 12c or higher is supported. However if you choose Oracle as your persistence layer the generated application will use the dialect for Oracle 10g instead of Oracle 12c.
While I do not think this will create issues it will also disable new features added by Oracle 12c

##### **Reproduce the error**

Just generate a new application using Oracle as DBMS

##### **Suggest a Fix**

I can make a pull request if necessary

##### **JHipster Version(s)**

I am using version 3.12.2

**Comment by jdubois** [comment]
Sounds great to me, our only problem is that we don't have an Oracle license, so we can't test -> if you have the opportunity to test, yes please do the PR

**Comment by Rosetjau** [comment]
Ok, as soon as I have an Oracle instance up I will test and then make a pull request.

**Comment by deepu105** [comment]
When I coded the feature there was no 12c dialect and the latest I git was 10g though 12c DB was there.
But if it works without any issues and if you can test it then please PR

**Comment by jdubois** [comment]
When you do the change, please do a search on the whole project, `Oracle10gDialect` is used 4 times normally

**Comment by jdubois** [comment]
I'm currently running Oracle 12c in a Docker container on my Mac, using https://hub.docker.com/r/sath89/oracle-12c/ !!! This is really great, I'll try to have this by default.

**Comment by jdubois** [comment]
And it's done!!! That's really incredible to use Oracle on my Mac using Docker.
