### ISSUE TITLE
Travis tests are flaky

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#4884]
Our travis builds are acting very flaky recently. We had to restart several jobs to get it pass.
Here is an example https://travis-ci.org/jhipster/generator-jhipster/jobs/192443191

Most of the times the failure is from Protractor and sometimes JWT or cassandra builds

Its really annoying and time wasting

cc @pascalgrimaud @jdubois

**Comment by pascalgrimaud** [comment]
Yes I notice that since we migrate from firefox to chrome. I try to analyse the reason but it's really hard because it's totally random.

So sorry @deepu105 but be sure as soon as it's possible, I ll try to reduce these random failures.

**Comment by mraible** [comment]
One of the reasons I switched to Firefox last year was because I saw issues with Chrome and logging out. Sometimes it worked, sometimes it didn't. It always worked with Firefox. However, it looks like there's still issues with Protractor and the latest Firefox. https://github.com/angular/protractor/issues/3750

**Comment by jdubois** [comment]
Most failures I had recently were legitimate, I didn't notice that.
I'll be more careful about it.

**Comment by deepu105** [comment]
@pascalgrimaud since its mostly protractor can we try to catch if there is a failure and retry once again just the protractor step?
I know its not a solution but I'll rather have that then to go and restart builds manually

**Comment by pascalgrimaud** [comment]
@deepu105 : it's sound ok for me. I will give a try
