### ISSUE TITLE
openjdk+cxf throw java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#4888]
i know it's not jhipster's bug . 

my microservice need invoke other SOA service and i choose cxf. 

pom.xml

```xml
<!-- ... -->
<!--<cxf.version>3.1.9</cxf.version>-->
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-jaxws</artifactId>
            <version>${cxf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-transports-http</artifactId>
            <version>${cxf.version}</version>
        </dependency>
<!-- ... -->
```

i build docker image and run it , throw exception  `java.lang.ClassNotFoundException: com/sun/tools/internal/xjc/api/XJC`

i modify `\src\main\docker\Dockerfile` change `FROM openjdk:8-jre-alpine` to `FROM java:8` rebuild and run it, it's ok.

**Comment by hookszhang** [comment]
Include the cxf-rt-core in your Maven dependencies.

**Comment by jdubois** [comment]
Indeed, not a JHipster bug...

**Comment by anjia0532** [comment]
@hookszhang thanks , but it's not work([like this](http://stackoverflow.com/questions/13039670/apache-cxf-dynamic-client-creation#answer-30467528)).i follow the [first page](http://stackoverflow.com/search?q=java.lang.ClassNotFoundException%3A+com%2Fsun%2Ftools%2Finternal%2Fxjc%2Fapi%2FXJC) in the stackoverflow and it's not work before i change the openjdk to oracle jdk
