### ISSUE TITLE
Ng2: sort directive throw error

### ISSUE THREAD

**Issue by xuyukuan** [jhipster/generator-jhipster#4889]
##### **Overview of the issue**
I run ng2 version and open the user management page. then I try to click the sort field to sort data, but no response, I open the console and got below error:  

> VM24995:57 Error: Failed to execute 'remove' on 'DOMTokenList': The token provided ('fa-sort-asc fa-sort-desc') contains HTML space characters, which are not valid in tokens.
>     at JhiSortDirective.resetClasses (eval at <anonymous> (vendor.bundle.js:2953), <anonymous>:36:30)
>     at JhiSortDirective.sort (eval at <anonymous> (vendor.bundle.js:2953), <anonymous>:22:14)
>     at JhiSortByDirective.onClick (eval at <anonymous> (vendor.bundle.js:4633), <anonymous>:21:26)
>     at Wrapper_JhiSortByDirective.handleEvent (wrapper.ngfactory.js:33)
>     at View_UserMgmtComponent1.handleEvent_38 (component.ngfactory.js:473)
>     at HTMLTableCellElement.eval (eval at <anonymous> (vendor.bundle.js:1575), <anonymous>:512:53)
>     at ZoneDelegate.invokeTask (eval at 832 (polyfills.bundle.js:36), <anonymous>:275:35)
>     at Object.onInvokeTask (eval at <anonymous> (vendor.bundle.js:1049), <anonymous>:262:37)
>     at ZoneDelegate.invokeTask (eval at 832 (polyfills.bundle.js:36), <anonymous>:274:40)
>     at Zone.runTask (eval at 832 (polyfills.bundle.js:36), <anonymous>:151:47)
>     at HTMLTableCellElement.ZoneTask.invoke (eval at 832 (polyfills.bundle.js:36), <anonymous>:345:33)

I debug the code and find the line which throw the error:  
```
JhiSortDirective.prototype.resetClasses = function () {
        var allThIcons = this.element.querySelectorAll(this.sortIconSelector)[0];
        allThIcons.classList.remove(this.sortAscIcon + ' ' + this.sortDescIcon);//this line throw error
        allThIcons.classList.add(this.sortIcon);
    };
```

**Comment by jdubois** [comment]
Yes we know it, it's one of the last remaining things to be coded at #4407

**Comment by jdubois** [comment]
Should be OK soon, see #4893
