### ISSUE TITLE
HazelCast starting twice

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#49]
When you select HazelCast for Hibernate caching AND HTTP session clustering, HazelCast gets started twice.
It even does a cluster between those two instances.
cc @jmirc

**Comment by deepu105** [comment]
@jdubois how did you solve the below issue? its slow to start with lot of members on LAN
> "Hazelcast is a bit slow to start, and having a cluster un dev mode is annoying, as your app will try to make a cluster with the other members of your team"

**Comment by jdubois** [comment]
We didn't solve this! We solve the "starting twice" issue, not the "slow to start" comment.
So maybe this shouldn't be enabled by default for dev mode.

**Comment by deepu105** [comment]
As per there [docs] (http://docs.hazelcast.org/docs/latest/manual/html/springintegration.html) seems like we can define the IP for clusters rite, can we set this in the JH application property YML files? or do we have to create an XML config file?

**Comment by jdubois** [comment]
In that case you could create your own keys in the application.yml file, indeed!

**Comment by deepu105** [comment]
do I have to configure anything else or just having the keys in yml would do? couldnt find any docs on hazelcast on what keys if it needs to be on spring boot properties
