### ISSUE TITLE
Error when using Sass with latest master branch

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#4900]
[Reported on Twitter](https://twitter.com/wstidolph/status/821790225332510720), by someone trying to build the blog from my [Get Started with JHipster 4](http://www.eclipse.org/community/eclipse_newsletter/2017/january/article3.php) article.

##### **Overview of the issue**

```
[INFO] WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
[INFO] 69:15 Critical dependency: the request of a dependency is an expression
[INFO]
[INFO] WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
[INFO] 85:15 Critical dependency: the request of a dependency is an expression
[INFO]
[INFO] ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/main/webapp/content/scss/global.scss
[INFO] Module build failed: Error: No PostCSS Config found in: /Users/mraible/dev/jhipster4-demo/src/main/webapp/content/scss
[INFO]     at Error (native)
[INFO]     at /Users/mraible/dev/jhipster4-demo/node_modules/postcss-load-config/index.js:51:26
[INFO]  @ ./src/main/webapp/content/scss/global.scss 4:14-195
[INFO]
[INFO] ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/main/webapp/content/scss/vendor.scss
[INFO] Module build failed: Error: No PostCSS Config found in: /Users/mraible/dev/jhipster4-demo/src/main/webapp/content/scss
[INFO]     at Error (native)
[INFO]     at /Users/mraible/dev/jhipster4-demo/node_modules/postcss-load-config/index.js:51:26
[INFO]  @ ./src/main/webapp/content/scss/vendor.scss 4:14-195
[INFO]  @ ./src/main/webapp/app/vendor.ts
[INFO]  @ multi vendor
[INFO] Child html-webpack-plugin for "index.html":
[INFO]        [0] ./~/lodash/lodash.js 540 kB {0} [built]
[INFO]        [1] (webpack)/buildin/global.js 506 bytes {0} [built]
[INFO]        [2] (webpack)/buildin/module.js 548 bytes {0} [built]
[INFO]        [3] ./~/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.ejs 1.81 kB {0} [built]
```

##### **Motivation for or Use Case**

Project won't build.

##### **Reproduce the error**

`npm link` on latest master branch
Create an app using the following `.yo-rc.json`

```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "blog",
    "packageName": "org.jhipster",
    "packageFolder": "org/jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "fac063fc9ee4dade2472173f04f4d19c4c434aba",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
```

Run `./mvnw` to see the error.

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.10.2

node: v6.9.1

npm: 3.10.8

bower: 1.8.0

gulp:
[15:19:01] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.18.1

Docker version 1.12.6, build 78d1802

docker-compose version 1.9.0, build 2585387

**Comment by gmarziou** [comment]
Wasn't it fixed by #4851 ?

**Comment by wstidolph** [comment]
I'm the one who reported a problem to  Matt via twitter. My issue manifested a bit differently - after the app was generated (no reported problems) it fails on first .\mvnw with an npm complaint about not finding a node-sass binding for Win10 64 bit node 6. I got the same error whether I started by copying in Matt's .yo-rc and running ```yo jhipster``` or running ```yo jhipster``` and answering the questions on my own. But, the error output kindly pointed out it found bindings for node 7, which is what I had installed already. So I changed the POM  to be the versions I have installed (```<node.version>v7.3.0</node.version>```, ```<yarn.version>v0.19.1</yarn.version>```) and then .\mvnw completes and the app runs, saying:
```
INFO] --- frontend-maven-plugin:1.3:install-node-and-yarn (install node and yarn) @ blog ---
[INFO] Node v7.3.0 is already installed.
[INFO] Yarn 0.19.1 is already installed.```

**Comment by jdubois** [comment]
Interesting... On a related note, we officially only support LTS releases of Node, so currently this is Node 6.
But, if you're using Homebrew on Mac (which I do, and which I expect most people do), if you install Yarn, it will bring Node 7 as a transitive dependency. So in the end, most people (including me) are using Node 7...

**Comment by deepu105** [comment]
I had no issues with node sass on windows 10 with node 6. So i guess there
might be somthing wrong with the way you have setup your environment. you
could try to install node-sass globally to see if it solves the issue


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Closing as this seems solved

**Comment by firefoxNX** [comment]
On macOS Sierra with node 6.9.4, yarn 0.0.19.1 and got the same issue. Fix by @wstidolph did not work. I removed 'postcss-loader' on https://github.com/mraible/jhipster4-demo/blob/master/webpack/webpack.common.js#L83 and it worked.
