### ISSUE TITLE
NoClassDefFoundError org/hibernate/bytecode/instrumentation/internal/FieldInterceptionHelper

### ISSUE THREAD

**Issue by jordanbaucke** [jhipster/generator-jhipster#4910]
##### **Overview of the issue**

When attempting to deploy application to Tomcat8 container, I received a "NoClassDefFoundError":

> org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration$DispatcherServletRegistrationConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties' defined in class path resource [org/springframework/boot/autoconfigure/web/ServerPropertiesAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/hibernate/bytecode/instrumentation/internal/FieldInterceptionHelper

##### **Motivation for or Use Case**

I was unable to deploy my application to Tomcat8 application container.

##### **Reproduce the error**

Tomcat8 install:
```
[18:31:18 root@app03:~] # apt show tomcat8
Package: tomcat8
Version: 8.0.32-1ubuntu1.2
Priority: optional
Section: java
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Java Maintainers <pkg-java-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 306 kB
Depends: adduser, tomcat8-common (>= 8.0.32-1ubuntu1.2), ucf, debconf (>= 0.5) | debconf-2.0
Recommends: authbind
Suggests: libtcnative-1 (>= 1.1.30), tomcat8-admin (>= 8.0.32-1ubuntu1.2), tomcat8-docs (>= 8.0.32-1ubuntu1.2), tomcat8-examples (>= 8.0.32-1ubuntu1.2), tomcat8-user (>= 8.0.32-1ubuntu1.2)
Homepage: http://tomcat.apache.org
Task: tomcat-server
Supported: 5y
Download-Size: 41.9 kB
APT-Manual-Installed: yes
APT-Sources: http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
Description: Apache Tomcat 8 - Servlet and JSP engine
 Apache Tomcat implements the Java Servlet and the JavaServer Pages (JSP)
 specifications from Oracle, and provides a "pure Java" HTTP web
 server environment for Java code to run.
```

##### **Suggest a Fix**
Added the following dependency (Gradle)
`    compile "org.hibernate:hibernate-entitymanager:${hibernate_version}"`

##### **JHipster Version(s)**
`3.12.2`

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "evasyst",
    "packageName": "com.evasyst.api",
    "packageFolder": "com/evasyst/api",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "43148b0dba6d4dc86b39629aa39468dd6044d7f6",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "serviceDiscoveryType": false
  }
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**
This issue _does not occur_ when deploying to local Tomcat8 (installed with brew) `macOS 10.12.2`

It does on:
```
[20:54:50 root@app03:/] # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

**Comment by gmarziou** [comment]
Looks like a classpath issue between spring boot and tomcat 8. Definitely not aJHipster issue.

**Comment by jordanbaucke** [comment]
@gmarziou thanks I'll take it up with them
