### ISSUE TITLE
Monolithic app crashes every day

### ISSUE THREAD

**Issue by KristiyanYordanov** [jhipster/generator-jhipster#4912]
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
git version 2.9.2.windows.1
node: v6.5.0
npm: 4.0.5
bower: 1.8.0
gulp:
[11:00:49] CLI version 3.9.1
[11:00:49] Local version 3.9.1
yeoman: 1.8.5
##### **Overview of the issue**

I start my web application with:  java -jar app.war -Dspring.profiles.active=prod
and every night it stops working.  

Exception: 
2017-01-19 22:33:23,149 INFO  [Thread-2] CacheConfiguration: Closing Cache Manager
2017-01-19 22:33:23,149 INFO  [Thread-2] CacheConfiguration: Closing Cache Manager
2017-01-19 22:33:23,171 WARN  [Thread-2] DisposableBeanAdapter: Invocation of destroy method failed on bean with name 'entityManagerFactory': java.lang.IllegalStateException: Eh107CacheManager[jar:file:/root/addly/version/0.0.2/addly-0.0.2-SNAPSHOT.war!/WEB-INF/classes!/ehcache.xml] is closed
2017-01-19 22:33:23,171 WARN  [Thread-2] DisposableBeanAdapter: Invocation of destroy method failed on bean with name 'entityManagerFactory': java.lang.IllegalStateException: Eh107CacheManager[jar:file:/root/addly/version/0.0.2/addly-0.0.2-SNAPSHOT.war!/WEB-INF/classes!/ehcache.xml] is closed

##### **JHipster Version(s)**

4.05

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "addly",
    "packageName": "com.addly.addly",
    "packageFolder": "com/addly/addly",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ],
    "serviceDiscoveryType": false
  }
}

##### **Browsers and Operating System**
CentOS

**Comment by jdubois** [comment]
I'm sorry but there is no way we can reproduce your issue.... Can we have your full stacktrace? Here there's just the end of it, maybe there's something interesting before?

Is your app crashing everyday at the same hour? Like here it crashed just after 22:30, is it crashing at 22:30 everyday? This would mean you have some external process, probably a backup process, that hangs the application.

For example, I had this some time ago on a Tomcat server that was hosted on a SAN: when the backup procedure ran, it locked all the files. This includes the log files (and by the way this why we don't log to a file, but to the console, but maybe you then pipe it to a file...). So all logs were locked, which means all threads were quickly locked, and when you run out of threads, the application crashes.

I'm closing this as obviously this is an environment problem on your side, but please do comment if you have more information, as other people might need this.
