### ISSUE TITLE
Each entity should have its own module

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#4918]
While working on fixing entity pagination with ng router, I found that entity.module.ts was 300 lines long for only 11 entities and also it was difficult to expose `<Entity>ResolvePagingParams` as a provider in this file without putting lot of logic in generator.

This is why I propose that each entity should have its own module.

**Comment by deepu105** [comment]
Yes it might be good. But we should find a way to reduce some boiler plate

Thanks & regards,
Deepu

**Comment by gmarziou** [comment]
I did it on a branch, it works fine for 10 of my entities and fail for one.

https://github.com/gmarziou/generator-jhipster/tree/module-per-entity

This is very strange, all the entities have same configuration, but for this one 2 routes have lost their component and the router rejects stops. It looks like a framework bug.

**Comment by sendilkumarn** [comment]
👍 for the idea. we can have that.

**Comment by jdubois** [comment]
@gmarziou looks like you are stuck on this one, can we help you?

**Comment by gmarziou** [comment]
Well it's difficult because it seems to depend on my entities, I'll try to reproduce it with a smaller project and see if I can find something

**Comment by gmarziou** [comment]
I just rebased on master and still have the same problem, I even tried ng 4.0 beta 5 and it fails the same.

https://github.com/gmarziou/generator-jhipster/tree/module-per-entity

I have narrowed the problem from 11 to 3 entities and setup a repo that shows the problem on `yarn start`

https://github.com/gmarziou/issue-module

**Comment by jdubois** [comment]
Thanks, this should be our top priority at the moment.

**Comment by deepu105** [comment]
Ill take a look at it today

Thanks & regards,
Deepu

**Comment by kaidohallik** [comment]
I tested and found in `tournament-dialog.component.ts` following:
```
import {
    TournamentType,
    RankingList,
    } from '../';


import {
    TournamentTypeService,
    RankingListService,
    } from '../';
```
Shouldn't these imports refer to tournament-type and ranking-list subdirectories?  
I have to go and can't test to the end before evening, sorry. I thought that I give that finding as hint.

**Comment by gmarziou** [comment]
Good point, I'll try

**Comment by gmarziou** [comment]
In fact ther is a barrel in entities, it was easier to generate from existing generator

**Comment by gmarziou** [comment]
This was an excellent hint: I used the imports both in `tournament-dialog.component.ts` and in the `@NgModule` of `tournament-module.component.ts` and now it works.

I made the changes in generated code:

https://github.com/gmarziou/issue-module/commit/04343a3285a1db6bd24877d0bc63c08d6f1c1961

Now I must do it in the generator which means I need to iterate on related entities which already exists for fields so it should be quite easy.

**Comment by deepu105** [comment]
Ok something about barrels. When suing a barrel it works well when we import the barrel from a directory which is not a subfolder of the folder where `index.ts` with barrel is defined. So in short if we have a barrel for entity it should be at the entity folder and should be used only when importing any of the entity components outside of that folder but within the folder we should always import by relative path else it will cause circular dependency errors(Angular has very bad error messages for these, they are pointless)

Also something to note when we import something in TS/ES6 it executes the imported file and recursively executes the `import declarations` hence if we use a barrel within a component of the barrel itself it causes stuff to be executed even before the component is loaded causing errors and  circular dependency.
I figured it out the hard way when migrating stuff to shared modules. and thats why within the shared modules we import stuff by relative path only.

Hope this helps
