### ISSUE TITLE
Inconsistent route paths for composed entity names

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#4923]
The route paths generated for an entity with camel cased name like TournamentType are not consistent:
- the normal routes (list and detail) use dash case: tournament-type
- the popup routes use camel case: tournamentType 

~~~
   path: 'tournament-type',
   path: 'tournament-type/:id',
   path: 'tournamentType-new',
   path: 'tournamentType-edit/:id',
   path: 'tournamentType-delete/:id',
~~~

The addEntityToMenu() function which is used to add entries to the navbar use dash case.

I think we should be consistent.
If we use dashcase then we may have problems with some entity names containing New, Edit or Delete like what we have with user management and :login.

Maybe we should define a better route scheme:

~~~
   path: 'tournament-type/list',
   path: 'tournament-type/detail/:id',
   path: 'tournament-type/new',
   path: 'tournament-type/edit/:id',
   path: 'tournament-type/delete/:id',
~~~

Maybe we can find some good practices.

**Comment by deepu105** [comment]
I think it might be an overlooked mistake. I guess its better to have dash
case for urls as it is better for SEO and is common practice

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
Yes, definitely dash!

**Comment by gmarziou** [comment]
OK, but what do you think of my proposal to use dash AND to separate the entity name from the "action"? @sendilkumarn any comment?

**Comment by sendilkumarn** [comment]
@gmarziou yeah dashed definitely. I guess it is my mistake.

**Comment by deepu105** [comment]
@gmarziou im gonn a change this to your proposal as im fixing tests

**Comment by gmarziou** [comment]
Thanks, I will review and test yourPR

**Comment by deepu105** [comment]
I'm modifying it a bit to follow what we had for ng1 its more standard I guess but we can ofcourse change if there is a better way

**Comment by gmarziou** [comment]
I guess that our ng1 conventions were highly driven by the notion of state, ng2 routes may lead to slightly different conventions. In partiicular I think we could have a componentless route to be able to manage authorities globally for the entity or to add a resolve property. This would be the equivalent of ui-router abstract state.

You can do it with my suggestion to use anaction.

```
tournament-type   Componentless
tournament-type/<action>
```

**Comment by deepu105** [comment]
i'm talking about the ng1 urls, which IMO follows REST url conventions closeley

```
   path: 'tournament-type',
   path: 'tournament-type/:id',
   path: 'tournament-type/new',
   path: 'tournament-type/:id/edit',
   path: 'tournament-type/:id/delete',
```

**Comment by deepu105** [comment]
Ahhh its much harder to get it working with ng-router. I'm hating it more and more. i'm giving up for now. Ill just correct existing routes and commit it. @gmarziou if you wanna give it a shot please go ahead.

**Comment by deepu105** [comment]
its bit more consistent now but it would be nice to have the below as it would be close to the REST conventions
```
   path: 'entity',
   path: 'entity/:id',
   path: 'entity/new',
   path: 'entity/:id/edit',
   path: 'entity/:id/delete',
```
then even with this the routes of model dialog look really weird something like `http://localhost:8080/#/user-management(popup:user-management-new)` hope their is a better way to do this like ui-router

**Comment by jdubois** [comment]
What exactly needs to be done here, for JHipster 4? Can we close, or postpone this?

**Comment by deepu105** [comment]
Lets put it on hold or add it to the TODO for next ticket so that we can do
it later

Thanks & regards,
Deepu

On 29 Jan 2017 12:26 a.m., "Julien Dubois" <notifications@github.com> wrote:

What exactly needs to be done here, for JHipster 4? Can we close, or
postpone this?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/4923#issuecomment-275882132>,
or mute the thread

**Comment by gmarziou** [comment]
Well my proposition for defining all routes with an action did not convince others so I close the issue.

'entity/:id' route works as long as id is a number, when id can be anything there can be conflicts like what we have for user management routes.
