### ISSUE TITLE
[Enhance] Upgrade to Bootstrap 4.0.0 to latest release

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#4928]
Upgrade bootstrap to 4.0.0-alpha.6 or latest and update ng-bootstrap to latest.

BS4 alpha 6 has some breaking changes. Flexbox is now default hence it disrupts our UI.

We need to move `navbar-toggleable-md` class from inner div to the nav element
We also need to add below to navbar.css/scss for getting link colors back
```
.jh-navbar a:not(.dropdown-item) {
    color: rgba(255, 255, 255, 0.7);
}

.jh-navbar a:not(.dropdown-item):hover {
    color: #ffffff;
}
```

There seems to be float issues as normal css float wont work in flexbox
In dialog headers the order of close btn and header text needs to be swapped

**Comment by jdubois** [comment]
Let's do this after the code freeze, this isn't urgent.

**Comment by jdubois** [comment]
I'm removing the v4 tag, as this will be done after the release
