### ISSUE TITLE
Ng2 router should store destination route

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#4930]
To avoid forgetting it as this is the last issue to solve before being able to remove ui-router completely from package.json

`register-transition-hooks.ts` used to configure ui-router , it had 3 responsibilities on state transitions:

1. store destination state in case to bring user to it later in case she has to login first
2. support for external URLs in ui-router
3. set page title

Only first one is not yet covered and relates to `StateStorageService` that should probably be renamed to `RouteStorageService`.

~~~js
    $transitions.onStart({}, (transition: Transition) => {
        let $storageService = transition.injector().get(StateStorageService);
        $storageService.storeDestinationState(transition.to(), transition.params(), transition.from());
        let principal = transition.injector().get(Principal);
        let auth = transition.injector().get(AuthService);
        if (principal.isIdentityResolved()) {
            auth.authorize();
        }

        <%_ if (enableTranslation) { _%>
        // Update the language //FIXME not sure if this is required, its causing some weird error as well
        /*let languageService = transition.injector().get(JhiLanguageService);
        languageService.getCurrent().then(current => {
            languageService.changeLanguage(current);
        });*/
        <%_ } _%>
    });
~~~

**Comment by VictorADS** [comment]
I'm on it

**Comment by gmarziou** [comment]
Great, one thing I did not understand is that this code seems to be related to session authentication while in my understanding it should work for others as well (JWT in particular)

**Comment by VictorADS** [comment]
@gmarziou  @sendilkumarn So far I've tried to reproduce what we were doing with ui-router using the `RoutesRecognized` event from the Router but that way, for example, if the user is logged in and he tries to acces the register page it will start rendering the html for register, then it will redirect to the home page ( because a connected user shouldn't access register). So my idea is to use another `canActivate` Service so that the router waits before starting to render the page.

Are you guys okay with that solution ?

**Comment by gmarziou** [comment]
CanActivate seems good, I just wonder whether it could be set globally rather than for each route.
Something I haven't tested like 

     { path: '**', canActivate: [StoreRouteGuard] },

**Comment by deepu105** [comment]
The workarounds to make stuff work with ng router seems to be growing. Its
making me wonder is it worth the switch

Thanks & regards,
Deepu

**Comment by VictorADS** [comment]
@deepu105  I wouldn't call this workarounds, it's just another way to treat routes. Also, even though it was easier in ui-router, I remember it had some problems with regards to the transition hooker. I think migrating to ng-router is for the better

**Comment by deepu105** [comment]
I hope so


Thanks & Regards,
Deepu
