### ISSUE TITLE
javax.inject dependency is missing in pom file for jhipster v3.12.2-snapshot

### ISSUE THREAD

**Issue by pierre-filliolaud** [jhipster/generator-jhipster#4938]
##### **Overview of the issue**

javax.inject dependency is missing in pom file when java SE is used as default jvm (Java(TM) SE Runtime Environment (build 1.8.0_25-b17)).
This issue exists in jhipster-generator v3 dev version not in v3 released

##### **Motivation for or Use Case**

The XML pom file must be fixed manually by adding in pom file:
		<dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>${javax.inject.version}</version>
        </dependency>

##### **Reproduce the error**
Use java SE as default jvm.
Generate JHipster project with an entity + Service class
Import your jhipster project with mvn command:
mvn eclipse:clean eclipse:eclipse -DdownloadSources=true -DdownloadJavadocs=true -Dwtpversion=2.0
Check your eclipse problem window:
Inject cannot be resolved to a type (in your EntityResource class)

##### **Related issues**
no

##### **Suggest a Fix**
Add javax.inject dependency in pom/gradle? files as jhipster v3 version

		<dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>${javax.inject.version}</version>
        </dependency>

##### **JHipster Version(s)**
generator-jhipster@3.12.2 dev version
regression from v3

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "angular2",
    "packageName": "net.filecode.angular2",
    "packageFolder": "net/filecode/angular2",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Item.json

{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "quantity",
            "fieldType": "Double"
        },
        {
            "fieldName": "price",
            "fieldType": "BigDecimal"
        }
    ],
    "dto": "no",
    "service": "serviceClass",
    "entityTableName": "item",
    "pagination": "pagination"
}

##### **Browsers and Operating System**

Operating System: MacOSX 10.12.1

$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by jdubois** [comment]
Yes it was removed on purpose, as it became useless.

Why do you need it, do you have a compilation issue somewhere ?

**Comment by pascalgrimaud** [comment]
it has been removed here : https://github.com/jhipster/generator-jhipster/issues/4554
The generated code shouldn't have `@Inject` anymore

**Comment by jdubois** [comment]
I'm sure this is because you didn't do a "yarn link generator-jhipster" on your project.

**Comment by pierre-filliolaud** [comment]
@jdubois by default Jhipster requires Java SE version not JavaEE version. Let me know if I am wrong.
I dont see @Inject in UserResource class but I still have it in new generated Service see my Item.json file.

**Comment by pascalgrimaud** [comment]
@pierre-filliolaud : don't you have this ?

```java
@Service
@Transactional
public class ItemService {

    private final Logger log = LoggerFactory.getLogger(ItemService.class);
    
    private final ItemRepository itemRepository;

    public ItemService(ItemRepository itemRepository) {
        this.itemRepository = itemRepository;
    }

    /**
     * Save a item.
     *
     * @param item the entity to save
     * @return the persisted entity
     */
    public Item save(Item item) {
        log.debug("Request to save Item : {}", item);
        Item result = itemRepository.save(item);
        return result;
    }

    /**
     *  Get all the items.
     *  
     *  @param pageable the pagination information
     *  @return the list of entities
     */
    @Transactional(readOnly = true)
    public Page<Item> findAll(Pageable pageable) {
        log.debug("Request to get all Items");
        Page<Item> result = itemRepository.findAll(pageable);
        return result;
    }

    /**
     *  Get one item by id.
     *
     *  @param id the id of the entity
     *  @return the entity
     */
    @Transactional(readOnly = true)
    public Item findOne(Long id) {
        log.debug("Request to get Item : {}", id);
        Item item = itemRepository.findOne(id);
        return item;
    }

    /**
     *  Delete the  item by id.
     *
     *  @param id the id of the entity
     */
    public void delete(Long id) {
        log.debug("Request to delete Item : {}", id);
        itemRepository.delete(id);
    }
}
```

**Comment by pierre-filliolaud** [comment]
Here is what I get after "yarn link generator-jhipster" on my project. 

jhipster-angular2 pierre$ yarn link generator-jhipster
yarn link v0.18.1
error No registered module found called "generator-jhipster".
info Visit https://yarnpkg.com/en/docs/cli/link for documentation about this command.

FYI, I followed the tuto from Matt Raible at http://www.eclipse.org/community/eclipse_newsletter/2017/january/article3.php.

Tks for your support!

**Comment by pierre-filliolaud** [comment]
@pascalgrimaud no, here is what I get:

@RestController
@RequestMapping("/api")
public class ItemResource {

    private final Logger log = LoggerFactory.getLogger(ItemResource.class);
        
    @Inject
    private ItemService itemService;

    /**
     * POST  /items : Create a new item.
     *
     * @param item the item to create
     * @return the ResponseEntity with status 201 (Created) and with body the new item, or with status 400 (Bad Request) if the item has already an ID
     * @throws URISyntaxException if the Location URI syntax is incorrect
     */
    @PostMapping("/items")
    @Timed
    public ResponseEntity<Item> createItem(@RequestBody Item item) throws URISyntaxException {
        log.debug("REST request to save Item : {}", item);
        if (item.getId() != null) {
            return ResponseEntity.badRequest().headers(HeaderUtil.createFailureAlert("item", "idexists", "A new item cannot already have an ID")).body(null);
        }
        Item result = itemService.save(item);
        return ResponseEntity.created(new URI("/api/items/" + result.getId()))
            .headers(HeaderUtil.createEntityCreationAlert("item", result.getId().toString()))
            .body(result);
    }

    /**
     * PUT  /items : Updates an existing item.
     *
     * @param item the item to update
     * @return the ResponseEntity with status 200 (OK) and with body the updated item,
     * or with status 400 (Bad Request) if the item is not valid,
     * or with status 500 (Internal Server Error) if the item couldnt be updated
     * @throws URISyntaxException if the Location URI syntax is incorrect
     */
    @PutMapping("/items")
    @Timed
    public ResponseEntity<Item> updateItem(@RequestBody Item item) throws URISyntaxException {
        log.debug("REST request to update Item : {}", item);
        if (item.getId() == null) {
            return createItem(item);
        }
        Item result = itemService.save(item);
        return ResponseEntity.ok()
            .headers(HeaderUtil.createEntityUpdateAlert("item", item.getId().toString()))
            .body(result);
    }

    /**
     * GET  /items : get all the items.
     *
     * @param pageable the pagination information
     * @return the ResponseEntity with status 200 (OK) and the list of items in body
     * @throws URISyntaxException if there is an error to generate the pagination HTTP headers
     */
    @GetMapping("/items")
    @Timed
    public ResponseEntity<List<Item>> getAllItems(@ApiParam Pageable pageable)
        throws URISyntaxException {
        log.debug("REST request to get a page of Items");
        Page<Item> page = itemService.findAll(pageable);
        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(page, "/api/items");
        return new ResponseEntity<>(page.getContent(), headers, HttpStatus.OK);
    }

    /**
     * GET  /items/:id : get the "id" item.
     *
     * @param id the id of the item to retrieve
     * @return the ResponseEntity with status 200 (OK) and with body the item, or with status 404 (Not Found)
     */
    @GetMapping("/items/{id}")
    @Timed
    public ResponseEntity<Item> getItem(@PathVariable String id) {
        log.debug("REST request to get Item : {}", id);
        Item item = itemService.findOne(id);
        return Optional.ofNullable(item)
            .map(result -> new ResponseEntity<>(
                result,
                HttpStatus.OK))
            .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * DELETE  /items/:id : delete the "id" item.
     *
     * @param id the id of the item to delete
     * @return the ResponseEntity with status 200 (OK)
     */
    @DeleteMapping("/items/{id}")
    @Timed
    public ResponseEntity<Void> deleteItem(@PathVariable String id) {
        log.debug("REST request to delete Item : {}", id);
        itemService.delete(id);
        return ResponseEntity.ok().headers(HeaderUtil.createEntityDeletionAlert("item", id.toString())).build();
    }

}

**Comment by pascalgrimaud** [comment]
@pierre-filliolaud : you need to do this
- in your generator-jhipster: yarn link
- in your generated project: yarn link generator-jhipster

**Comment by pierre-filliolaud** [comment]
After doing 
* in your generator-jhipster: yarn link
* in your generated project: yarn link generator-jhipster

I am getting the expected result!

Tks!

`@RestController
@RequestMapping("/api")
public class Item2Resource {

    private final Logger log = LoggerFactory.getLogger(Item2Resource.class);

    private static final String ENTITY_NAME = "item2";
        
    private final Item2Service item2Service;

    public Item2Resource(Item2Service item2Service) {
        this.item2Service = item2Service;
    }

    /**
     * POST  /item-2-s : Create a new item2.
     *
     * @param item2 the item2 to create
     * @return the ResponseEntity with status 201 (Created) and with body the new item2, or with status 400 (Bad Request) if the item2 has already an ID
     * @throws URISyntaxException if the Location URI syntax is incorrect
     */
    @PostMapping("/item-2-s")
    @Timed
    public ResponseEntity<Item2> createItem2(@RequestBody Item2 item2) throws URISyntaxException {
        log.debug("REST request to save Item2 : {}", item2);
        if (item2.getId() != null) {
            return ResponseEntity.badRequest().headers(HeaderUtil.createFailureAlert(ENTITY_NAME, "idexists", "A new item2 cannot already have an ID")).body(null);
        }
        Item2 result = item2Service.save(item2);
        return ResponseEntity.created(new URI("/api/item-2-s/" + result.getId()))
            .headers(HeaderUtil.createEntityCreationAlert(ENTITY_NAME, result.getId().toString()))
            .body(result);
    }

    /**
     * PUT  /item-2-s : Updates an existing item2.
     *
     * @param item2 the item2 to update
     * @return the ResponseEntity with status 200 (OK) and with body the updated item2,
     * or with status 400 (Bad Request) if the item2 is not valid,
     * or with status 500 (Internal Server Error) if the item2 couldnt be updated
     * @throws URISyntaxException if the Location URI syntax is incorrect
     */
    @PutMapping("/item-2-s")
    @Timed
    public ResponseEntity<Item2> updateItem2(@RequestBody Item2 item2) throws URISyntaxException {
        log.debug("REST request to update Item2 : {}", item2);
        if (item2.getId() == null) {
            return createItem2(item2);
        }
        Item2 result = item2Service.save(item2);
        return ResponseEntity.ok()
            .headers(HeaderUtil.createEntityUpdateAlert(ENTITY_NAME, item2.getId().toString()))
            .body(result);
    }

    /**
     * GET  /item-2-s : get all the item2S.
     *
     * @param pageable the pagination information
     * @return the ResponseEntity with status 200 (OK) and the list of item2S in body
     * @throws URISyntaxException if there is an error to generate the pagination HTTP headers
     */
    @GetMapping("/item-2-s")
    @Timed
    public ResponseEntity<List<Item2>> getAllItem2S(@ApiParam Pageable pageable)
        throws URISyntaxException {
        log.debug("REST request to get a page of Item2S");
        Page<Item2> page = item2Service.findAll(pageable);
        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(page, "/api/item-2-s");
        return new ResponseEntity<>(page.getContent(), headers, HttpStatus.OK);
    }

    /**
     * GET  /item-2-s/:id : get the "id" item2.
     *
     * @param id the id of the item2 to retrieve
     * @return the ResponseEntity with status 200 (OK) and with body the item2, or with status 404 (Not Found)
     */
    @GetMapping("/item-2-s/{id}")
    @Timed
    public ResponseEntity<Item2> getItem2(@PathVariable String id) {
        log.debug("REST request to get Item2 : {}", id);
        Item2 item2 = item2Service.findOne(id);
        return ResponseUtil.wrapOrNotFound(Optional.ofNullable(item2));
    }

    /**
     * DELETE  /item-2-s/:id : delete the "id" item2.
     *
     * @param id the id of the item2 to delete
     * @return the ResponseEntity with status 200 (OK)
     */
    @DeleteMapping("/item-2-s/{id}")
    @Timed
    public ResponseEntity<Void> deleteItem2(@PathVariable String id) {
        log.debug("REST request to delete Item2 : {}", id);
        item2Service.delete(id);
        return ResponseEntity.ok().headers(HeaderUtil.createEntityDeletionAlert(ENTITY_NAME, id.toString())).build();
    }

}`

The tuto from Matt Raible should be fixed then
[tuto](http://www.eclipse.org/community/eclipse_newsletter/2017/january/article3.php)

Tks for the support!

**Comment by jdubois** [comment]
Well, working on the master branch isn't a great idea, we will release a stable version soon.

**Comment by pierre-filliolaud** [comment]
My bad the "npm link generator-jhipster" command is present in the tutorial.
