### ISSUE TITLE
Unable to start generated project due to relationships problem

### ISSUE THREAD

**Issue by bajdekm** [jhipster/generator-jhipster#4939]
I have problem with generated project. Everytime when Im trying to generate relationship between two Entities I get similar problem:

`[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.200 s
[INFO] Finished at: 2017-01-24T00:27:39+01:00
[INFO] Final Memory: 47M/133M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project kompetencyjny: Compilation failure: Compilation failure:
[ERROR] /home/mike/Pulpit/kompetencyjny/src/main/java/com/mycompany/myapp/domain/Participant.java:[79,16] cannot find symbol
[ERROR] symbol:   method setParticipant(com.mycompany.myapp.domain.Participant)
[ERROR] location: variable payment of type com.mycompany.myapp.domain.Payment
[ERROR] /home/mike/Pulpit/kompetencyjny/src/main/java/com/mycompany/myapp/domain/Participant.java:[85,16] cannot find symbol
[ERROR] symbol:   method setParticipant(<nulltype>)
[ERROR] location: variable payment of type com.mycompany.myapp.domain.Payment
[ERROR] /home/mike/Pulpit/kompetencyjny/src/main/java/com/mycompany/myapp/domain/Trainer.java:[79,21] cannot find symbol
[ERROR] symbol:   method setTrainer(com.mycompany.myapp.domain.Trainer)
[ERROR] location: variable swimmerGroup of type com.mycompany.myapp.domain.SwimmerGroup
[ERROR] /home/mike/Pulpit/kompetencyjny/src/main/java/com/mycompany/myapp/domain/Trainer.java:[85,21] cannot find symbol
[ERROR] symbol:   method setTrainer(<nulltype>)
[ERROR] location: variable swimmerGroup of type com.mycompany.myapp.domain.SwimmerGroup
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
` 

I did several attempts and I get the same result everytime (both for MacOS Sierra and Ubuntu 16.04 and framework version v3.12.2). How can I deal with this problem?

**Comment by pascalgrimaud** [comment]
Can you follow the template issue and provide :
- full information about your configuration and tools -> use yo jhipster:info
- all steps so we can reproduce your issue -> describe your steps

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
