### ISSUE TITLE
Change index.ejs back to html file as we dont use ui router visualizer anymore

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#4949]

**Comment by jdubois** [comment]
Yes big +1 !!!
That was my initial idea with @flaviencathala but now it's cool that we can remove this. I think there was a specific dependency in package.json to handle this, you should be able to remove it.

**Comment by deepu105** [comment]
Nope we still need the plugin to place dependencies on the html


Thanks & Regards,
Deepu
