### ISSUE TITLE
Generated application can not start properly with OAuth and Oracle Database

### ISSUE THREAD

**Issue by gcoban** [jhipster/generator-jhipster#4954]
##### **Overview of the issue**

Generated application can not start properly with OAuth and Oracle Database because foreign key called "fk_oauth_client_token_user_name" defined in 00000000000000_initial_schema.xml is too long (31 chars) for an Oracle object name. Oracle object names can be 30 chars length at most.

##### **Motivation for or Use Case**

Generated application can't be started.

##### **Reproduce the error**

Just generate an aplication with OAuth and Oracle Database and simply try to run it.

##### **Related issues**

No.

##### **Suggest a Fix**

Change the foreign key name from "fk_oauth_client_token_**user_name**" to "fk_oauth_client_token_**username**" which is one char less.

##### **JHipster Version(s)**

generator-jhipster@3.12.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "GCPlatform",
    "packageName": "com.gcoban.platform",
    "packageFolder": "com/gcoban/platform",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "tr"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entity defined yet.

##### **Browsers and Operating System**

Chrome on MacOS Sierra. The problem is irrelevant with Browser or OS.

**Comment by jdubois** [comment]
This is fixed on #4947 can you check?

**Comment by jdubois** [comment]
Oh sorry it looks the same but it's not!

**Comment by jdubois** [comment]
We should change this now, as we are preparing JHipster 4, so it's the only time when we can break our API (major release)
