### ISSUE TITLE
Gradle error on some Windows machines, jHipster v3.12.2

### ISSUE THREAD

**Issue by s-t-x** [jhipster/generator-jhipster#4958]
##### **Overview of the issue**

Gradle build produces this error on Windows machines, where gradle cache path contains spaces: 

> java.lang.NoClassDefFoundError: org/springframework/core/env/Environment
>         at java.lang.Class.getDeclaredMethods0(Native Method)
>         at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
>         at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
>         at java.lang.Class.getMethod0(Class.java:3018)
>         at java.lang.Class.getMethod(Class.java:1784)
>         at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
>         at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
> Caused by: java.lang.ClassNotFoundException: org.springframework.core.env.Environment
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         ... 7 more
> Error: A JNI error has occurred, please check your installation and try again
> Exception in thread "main" :bootRun FAILED

##### **Motivation for or Use Case**
My user name on Windows contains spaces and this is the problem here. 

##### **Suggest a Fix**
I patched my classpath so that it does not contain spaces any more and the error is gone. This needs a better approach, like surrounding classpath entries with "", or something alike. I am just evaluating, so this quick patch worked for me:

Note: this example assumes the culprit are spaces in Windows user name (gradle caches are a subpath of it), and I replaced "User Name" with "userna~1" (which is a Windows long directory names replacement with an 8-char equivalent), just to get rid of spaces in classpath: 

build.gradle, close to line 55:
```
attributes 'Class-Path': configurations.runtime.files.collect {
     it.toURL().toString().replaceFirst(/file:\/+/, '/').replace('user name', 'userna~1')
}.join(' ')
```

##### **JHipster Version(s)**
v3.12.2

**Comment by deepu105** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
