### ISSUE TITLE
Gradle error on Windows when classpath contains spaces, jHipster v3.12.2

### ISSUE THREAD

**Issue by s-t-x** [jhipster/generator-jhipster#4960]
##### **Overview of the issue**

Starting jhipster produces this error on Windows, when gradle build is used and classpath to gradle caches contains spaces:

> java.lang.NoClassDefFoundError: org/springframework/core/env/Environment
> at java.lang.Class.getDeclaredMethods0(Native Method)
> at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
> at java.lang.Class.getMethod0(Class.java:3018)
> at java.lang.Class.getMethod(Class.java:1784)
> at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
> at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
> Caused by: java.lang.ClassNotFoundException: org.springframework.core.env.Environment
> at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ... 7 more
> Error: A JNI error has occurred, please check your installation and try again
> Exception in thread "main" :bootRun FAILED

##### **Motivation for or Use Case**

If classpath to gradle caches contains spaces, you cannot run jhipster at all.

##### **Reproduce the error**

1. Install jHipster on any Windows where path to gradle cache contains spaces. (The most likely case is that your Windows user name consists of a first name and a last name, separated by a space.)
2. Create an application with gradle build using "yo jhipster".
3. run "gradlew". 
After that you will get this error, and Jhipster will not start.

##### **Related issues**

It is not rare that spaces create problems in paths in Windows. I am not aware of similar issues relating to jhipster.

##### **Suggest a Fix**

I patched my classpath so that it does not contain spaces any more and the error is gone. The actual fix needs a slightly better approach, like surrounding classpath entries with "", or something alike. I am just evaluating, so this quick patch worked for me, and it also proves the issue.

Note: this example assumes the culprit are spaces in Windows user name (gradle caches are a subpath of it), and I replaced "User Name" with "userna~1" (which is a Windows long directory names replacement with an 8-char equivalent), just to get rid of spaces in classpath:

build.gradle, close to line 55:

```

attributes 'Class-Path': configurations.runtime.files.collect {
     it.toURL().toString().replaceFirst(/file:\/+/, '/').replace('user name', 'userna~1')
}.join(' ')

```

##### **JHipster Version(s)**
```
bsurvey-2@0.0.0 D:\jhipster\bsurvey2
+-- generator-jhipster@3.12.2
+-- generator-jhipster-google-analytics@0.0.1
| `-- generator-jhipster@2.25.0
`-- generator-jhipster-google-maps@0.0.1
  `-- generator-jhipster@2.25.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "bsurvey2",
    "packageName": "com.bsurvey",
    "packageFolder": "com/bsurvey",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "<removed>",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-swagger-cli",
        "version": "2.0.5"
      },
      {
        "name": "generator-jhipster-google-analytics",
        "version": "0.0.1"
      },
      {
        "name": "generator-jhipster-ionic",
        "version": "2.1.6"
      },
      {
        "name": "generator-jhipster-google-maps",
        "version": "0.0.1"
      },
      {
        "name": "generator-jhipster-bootstrap-material-design",
        "version": "3.5.1"
      },
      {
        "name": "generator-jhipster-angular-datatables",
        "version": "1.3.1"
      },
      {
        "name": "generator-jhipster-swagger2markup",
        "version": "1.1.0"
      },
      {
        "name": "generator-jhipster-ci",
        "version": "1.0.0"
      },
      {
        "name": "generator-jhipster-spring-social-connectors",
        "version": "0.0.1"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de"
    ]
  }
}

```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
No entities created yet.

##### **Browsers and Operating System**
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 1.9.5.msysgit.1

node: v5.5.0

npm: 4.1.1

bower: 1.8.0

gulp:
[01:45:32] CLI version 1.2.2
[01:45:32] Local version 3.9.1

yeoman: 1.8.5

Docker version 1.12.5, build 7392c3b
Windows: Microsoft Windows [Version 6.1.7600]

No browsers used yet. The error affects the startup of jHipster.

**Comment by pascalgrimaud** [comment]
I understand the issue with space in classpath, but I'm not sure it is only related to JHipster.

For me, 'avoid spaces in folder name' is a good practice for developers.
That's why I always install tools on personnal folders like `C:\app`, `D:\app`, etc... instead of letting by default 'C:\program files' which contains a space...

**Comment by jdubois** [comment]
We don't have this with Maven so for me this yet another Gradle issue

Le 25 janv. 2017 9:51 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
I'm closing this as:

- This is a Gradle bug (we don't have the issue with Maven), so maybe they will correct this in a next release
- There is an easy workaround, and indeed I would recommend you not to use a space on Windows (and not to use Windows at all!)
