### ISSUE TITLE
Back Button and Dialog Issues

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#4961]
##### **Overview of the issue**
The back button on the entity-detail-component doesn't work if you use the edit button first.  [Watch this GIF for the full experience.](https://cloud.githubusercontent.com/assets/4294623/22273347/16da2268-e255-11e6-9f0a-b85f864dc2d6.gif)

This also affects the browser back button after editing/deleting any entity/user from the listing page.
##### **Reproduce the error**
Generate any entity
Click on view entity to navigate to the entity-detail-component
Click the edit button and click either cancel/save
Click on the back button - the popup reappears 
Even the browser's back button reopens the edit dialog

Or go to the User Management listings
Click delete
Click cancel
Click your browser's back and the dialog will reopen and stay open for any number of "back" clicks
##### **Related issues**
https://github.com/jhipster/generator-jhipster/issues/4188
https://github.com/jhipster/generator-jhipster/issues/4727

##### **Suggest a Fix**
My suggested fix is using replaceUrl on the popup when it's opened and closed ([docs, but they don't document anything...](https://angular.io/docs/ts/latest/api/router/index/RouterLink-directive.html#!#replaceUrl-anchor)). Essentially, the dialog is treated as a popup instead of its own state (route?) in history.  Pressing back acts like the dialog was never there.  This fixes it for both the entity/user listings and the edit button on the entity page.

The only problem is the browser's "back" doesn't close the dialog when it is open - but that is the current behavior, and it's better than the back button not working after editing/deleting.

Any other solutions are welcome.

##### **JHipster Version(s)**
master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
Any
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "ng2",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "2d3cdef422b55b0a3ec2c3bb90c4afa3e8500313",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ],
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Foo.json (or any entity)
```
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170124235155",
    "dto": "mapstruct",
    "service": "serviceClass",
    "entityTableName": "foo",
    "pagination": "pagination"
}
```

**Comment by deepu105** [comment]
This has always been troublesome and has become more so after router migration so if you have any nice way of dealing with please do so :)

**Comment by diegohsi** [comment]
Does that already have a solution?
