### ISSUE TITLE
Pb with show index page

### ISSUE THREAD

**Issue by banya16** [jhipster/generator-jhipster#4964]
All mornings, when i do connect to my app, i do refresh my page beacause for the first entry we can't show index page.

All nigths i stop application and all mornings i restart them.

I thinks the problem come to cookies or cache.

Do you had this probleme ?

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
