### ISSUE TITLE
gateway + OAuth2 + UAA: the main page needs to be reloaded on first entry

### ISSUE THREAD

**Issue by banya16** [jhipster/generator-jhipster#4965]
##### **Overview of the issue**

When i come on application i have a white page.

##### **Motivation for or Use Case**

All users do refresh page for enter in my application.

##### **Reproduce the error**

All mornings, when i do connect to my app, i do refresh my page beacause for the first entry we can't show index page.

All nigths i stop application and all mornings i restart them.

I thinks the problem come to cookies or cache.

Do you had this probleme ?

##### **Suggest a Fix**

No know to fix bug.

##### **JHipster Version(s)**

"jhipsterVersion": "3.5.1"

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "gatewayOAuth2",
    "packageName": "fr.smatis.gateway",
    "packageFolder": "fr/smatis/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entity.

##### **Browsers and Operating System**

This problem is on all browsers and operating System.

**Comment by deepu105** [comment]
You seem to be using a gateway with UAA authentication. You need to give us the yo-rc files of all the apps you have as what you have provided is too little info to reproduce the issue cc @xetys

**Comment by jdubois** [comment]
Can you rename the title to something more explicit?

**Comment by jdubois** [comment]
And do you have a stacktrace (server side) or log (in your browser debug console) when that empty page shows?

**Comment by banya16** [comment]
Hi,

Thank you for rename title.

yo-rc file gateway : 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "gatewayOAuth2",
    "packageName": "fr.smatis.gateway",
    "packageFolder": "fr/smatis/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}

yo-rc file uaa : 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.7.0",
    "baseName": "uaa",
    "packageName": "fr.smatis.server",
    "packageFolder": "fr/smatis/server",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableTranslation": true,
    "applicationType": "uaa",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}

yo-rc file registry : 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "jhipsterRegistry",
    "packageName": "io.github.jhipster.registry",
    "packageFolder": "io/github/jhipster/registry",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "serverPort": "8080",
    "jwtSecretKey": "c9d37cefc48581919939d587c750ea215020765b"
  }
}

And i have this errors in console : 

http://localhost:8080/uaa/api/account?cacheBuster=1485333301142 -> Failed to load resource: the server responded with a status of 401 (Unauthorized)
http://localhost:8080/api/profile-info?cacheBuster=1485333301087 -> Failed to load resource: the server responded with a status of 401 (Unauthorized)
http://localhost:8080/i18n/fr/home.json -> Failed to load resource: the server responded with a status of 401 (Unauthorized)
http://localhost:8080/i18n/fr/global.json -> Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by jdubois** [comment]
With JHipster 4 I don't exactly have the same error as you. Everything starts up correctly, but the login form gets a 404 error (and my UAA server is correctly seen from the Registry, so the Gateway should have a route opened to this URL, and we shouldn't get a 404 error).
@xetys as you coded this part, can you check?

**Comment by ruddell** [comment]
@jdubois I fixed your 404 issue in #5025

I can't reproduce this issue. :(  From the logs it's clear the JS is loading and executing, so I'm not sure why the page would not be visible.  Maybe try opening up `/api/profile-info` in your gateway's `MicroserviceSecurityConfiguration.java` - it shouldn't cause issues but we fixed it since v3.5.1

Add `.antMatchers("/api/profile-info").permitAll()`

**Comment by jdubois** [comment]
OK then I believe this is fixed.

**Comment by banya16** [comment]
Ok i test to make permitAll and i say you if it's ok tomorow.

**Comment by ruddell** [comment]
You sent the log `http://localhost:8080/api/profile-info?cacheBuster=1485333301087 -> Failed to load resource: the server responded with a status of 401 (Unauthorized)` which shows the gateway endpoint of `/api/profile-info` is secured

**Comment by banya16** [comment]
Yes, i d'on't enderstand why i have this error. It's possible she come UAA ?

**Comment by banya16** [comment]
This problem for load page come juste the morning before the first connection. I thinks the problem come a cookie or cash configuration.

**Comment by satish-pokala** [comment]
what is the solution for this problem, even I am getting the same issue with "jhipsterVersion": "4.3.0" when UI is trying to load global.json file it ended up with 401 & the UI does not have any labels.
labels files must be allowed to everyone, even if there is no signed in user for us.

**Comment by ruddell** [comment]
@satish-pokala I fixed this in a separate project by adding [a WebSecurityConfiguration.java](https://gist.github.com/ruddell/585811967589120130e8c7fd6e78b841) into the Gateway's `config` package.  I opened an issue to track this #6310
