### ISSUE TITLE
Backslashes in validation patterns are not escaped in `translateValues`

### ISSUE THREAD

**Issue by ddidier** [jhipster/generator-jhipster#4966]
##### **Overview of the issue**

Backslashes in validation patterns are not escaped in the `translateValues` causing an unrecoverable client-side error.

##### **Motivation for or Use Case**

Add a valid pattern to a field, here a "non blank" pattern.

##### **Reproduce the error**

1. Generate an entity X with the validation pattern `^.*[\\S]+.*$` (see attachment below)
2. Open the `Create a new X` dialog
3. A JavaScript error is raised and all translated texts are blank 

##### **Related issues**

n/a

##### **Suggest a Fix**

The associated input field has a generated `translateValues="{ pattern: '^.*[\S]+.*$' }"` which is wrong: it should be `translateValues="{ pattern: '^.*[\\S]+.*$' }"` with 2 backslashes.

##### **JHipster Version(s)**

Master branch, commit 16e2184748a39d300bae2eaeb57856e4650d0370

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

[yo-rc.json](https://github.com/jhipster/generator-jhipster/files/730281/yo-rc.json.zip)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

[Platform.json](https://github.com/jhipster/generator-jhipster/files/730286/Platform.json.zip)

##### **Browsers and Operating System**

Chrome

**Comment by deepu105** [comment]
would appreciate if you can do a PR. anyway thanks for the report
