### ISSUE TITLE
[FEATURE] Add a "not blank" field validation rule to the entity generator

### ISSUE THREAD

**Issue by ddidier** [jhipster/generator-jhipster#4967]
For a `String` field, it would be nice to be able to generate a "non blank" validation rule using:

- `org.hibernate.validator.constraints.NotBlank` on the server side for the entity and the DTO
- `^.*[\S]+.*$` on the client side

**Comment by deepu105** [comment]
We already have required and if you need something more like non whitepace check use the regex option

**Comment by ddidier** [comment]
That's what I've done but I thought this might be a common enough requirement. Anyway, this is just a feature request :)

**Comment by jdubois** [comment]
Not sure if a lot of people would need this, and yes it should be a regexp.
For me we should stick to the standard & basic validators, at least for the
moment (we can discuss this again when AngularJS 1 is removed, and Angular
2 is very stable).

Le 25 janv. 2017 6:20 PM, "David DIDIER" <notifications@github.com> a
écrit :
