### ISSUE TITLE
NoSuchMethodError if using gradle

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#4975]
##### **Overview of the issue**

when using gradle, there are various steps in jhipster application, which lead to a 

```
Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.security.core.userdetails.User.withUsername
```

*  #4882
* generating any simple entity in a microservice (JWT and UAA)

this does not happen when using maven 

##### **Reproduce the error**

``` 
$ mkdir setup
$ cd setup
$ mkdir uaa foo gateway
$ cd uaa
$ yarn link generator-jhipster
$ jh # generate a uaa server with mysql, gradle
$ ./gradlew build -Pprod buildDocker # everything ok
$ cd ../foo
$ yarn link generator-jhipster
$ jh # generate microsvc with uaa authentication
$ yarn link generator-jhipster
$ jhe Foo # one column "value" with type string, no relations, validation, directly used in controller
$ ./gradlew build -Pprod buildDocker # all tests failing with the 
```

This happens also on gateway, and also using JWT...so this is not a uaa specific issue. I try to find out why it works on travis but not in real world

##### **Browsers and Operating System**

tested from 2 linux based machines

**Comment by pascalgrimaud** [comment]
@xetys : did you try to clean your .m2 folder ? It seems like you have a corrupted spring security library

**Comment by xetys** [comment]
removing m2 did not changed the situation...currently testing on a third machine

**Comment by xetys** [comment]
I reproduced this issue on a clean machine....just generated a jwt microservice with a simple foo entity and started the tests

**Comment by xetys** [comment]
really strange, this happens exclusively in gradle...I will update this issue to make it more clear

**Comment by atomfrede** [comment]
@xetys I will try too. Sounds like a missing dependency or some dependency missmatch. Have you tried to look (I use IDEA for that, quick and simple) which versions are resolved when using maven and which when using gradle?

**Comment by pascalgrimaud** [comment]
@xetys : ok, I manage to reproduce it.
There is an issue with the lib from gradle.

Here an extract of the dependency tree from 
```
[INFO] +- org.springframework.security:spring-security-test:jar:4.2.1.RELEASE:test
[INFO] |  \- org.springframework.security:spring-security-core:jar:4.2.1.RELEASE:compile
[INFO] |     \- aopalliance:aopalliance:jar:1.0:compile
```

Here from gradle:
```
+--- org.springframework.security:spring-security-test: -> 4.1.4.RELEASE
|    +--- org.springframework.security:spring-security-core:4.1.4.RELEASE (*)
|    +--- org.springframework.security:spring-security-web:4.1.4.RELEASE -> 4.2.1.RELEASE (*)
|    +--- org.springframework:spring-core:4.3.5.RELEASE
|    \--- org.springframework:spring-test:4.3.5.RELEASE (*)
```

A quick fix in `your gradle.build` file, to force the `spring-security-core` version:
```
testCompile "org.springframework.security:spring-security-test:${spring_security_version}"
testCompile "org.springframework.security:spring-security-core:${spring_security_version}"
```

As I'm not a Gradle user, I will let you guy doing the appropriate fix

**Comment by atomfrede** [comment]
@pascalgrimaud @xetys It looks like we are overwriting ``spring-security-core``, as the [spring-boot documentation ](http://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html)says the blessed version ``4.1.4.RELEASE``.

**Comment by xetys** [comment]
but as this haoppens for uaa, why it do also fails for JWT microservices? Or am I missing something

**Comment by mraible** [comment]
Spring Boot 1.5 (due out this week) depends on Spring Security 4.2. Might fix this issue.

**Comment by atomfrede** [comment]
@xetys Maybe because of the not present overwrite here:

`` testCompile "org.springframework.security:spring-security-test"``
