### ISSUE TITLE
Travis: improvement for NG2

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#4985]
##### **Overview of the issue**

As NG1 is frozen, our Travis builds should cover NG2

The project from Hipster Labs https://github.com/hipster-labs/jhipster-travis-build will launch a nightly build : https://travis-ci.org/hipster-labs/jhipster-travis-build/ 

##### **Related issues**

Following discussion here: https://github.com/jhipster/generator-jhipster/issues/4301

##### **Suggest a Fix**

Some improvements which can be done:
- [ ] there should not be duplicate builds between main generator-jhipster and hipster-labs -> don't hesitate to propose a full list
- [X] missing build for NG2: with prod profile
- [X] missing build for NG2: elasticsearch
- [ ] protractor : default behavior like now. When merged into master, protractor for all app!
- [X] logs: I would like to add `-Dspring.jpa.show-sql=false` when launching tests to reduce the logs. What do you think?
- [X] Sonar analysis: switch to NG2 ?

**Comment by deepu105** [comment]
:+1: for reducing logs as we are only concerned about error logs there. we could also try to specify log levels so we dont see all the info and debug logs I guess

**Comment by jdubois** [comment]
yes error logs are a huge problem for me, as most of the time I read them on my phone...

**Comment by pascalgrimaud** [comment]
@jdubois : it's funny because I do the same, scroll, scroll, scroll and boring about Hibernate logs!

**Comment by pascalgrimaud** [comment]
About Sonar, I don't see a Typescript profile: https://sonarqube.com/profiles
Do you confirm me you want to switch to NG2 for Sonar analysis ?

**Comment by jdubois** [comment]
Yes, everybody is going to switch to NG2 anyway... This is like the rest of the build, in fact.
Probably Sonar will add one soon (we have it at work, so I guess SonarQube will update their config soon)

**Comment by pascalgrimaud** [comment]
The 1st nightly build : https://travis-ci.org/hipster-labs/jhipster-travis-build/builds/195992165
The Cron Jobs from Travis work well !!

**Comment by jdubois** [comment]
I'm removing angular 2 and v4 tags, as this is not directly related. This is not a blocker issue for releasing JHipster 4, anyway.

**Comment by pascalgrimaud** [comment]
Yes, total agree

**Comment by deepu105** [comment]
Im getting a protractor failure in travis for the ng2-default app but when
I run it locally it works fine I have no idea whats going on there. Note
that it also uses a custom jhiPrefix


Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
@deepu105 : I'm having a look

**Comment by pascalgrimaud** [comment]
Reproduced. I will open a specific issue, as I'm not sure how it should be fixed
