### ISSUE TITLE
[FEATURE]  constants for jdl

### ISSUE THREAD

**Issue by aledesc** [jhipster/generator-jhipster#4986]
##### **Overview of the issue**

possibility to declare constants in the jdl so they can be reused along the script

##### **Motivation for or Use Case**

it would be nice to use expressive constanst for length of String fields for example, I do have some field that are descriptions, and give them 1600 chars (aprox. a page of plain text) , but for other String fields I allocate 1024 Kb, so 1Mb or even 1 Gb

e.g.

DESCRIPTION_LEN = 1660
NAME_LEN = 75

entity ProjectPhase
{
name String required maxlength(NAME_LEN),
description String maxlength(DESCRIPTION_LEN)
}

**Comment by MathieuAA** [comment]
Hi! 
First, this issue should go in the JHipster Core project, as the generator only deals with the import feature.
This use case is not that common, but I think it would be nice to have that.
I'm closing this, and re-opening another issue in the right project.
Thanks for the suggestion
