### ISSUE TITLE
Microservices + no database + Elasticsearch is failing

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4994]
This was [posted on Twitter](https://twitter.com/karunakerreddyv/status/825215462275289088).

We've had this issue for a very long time, as I never thought of doing this:

- Application type: microservices
- No database (this option is only available for microservices)
- Elasticsearch

As Elasticsearch uses entities, it "requires" a database at the moment. But we could have a simple setup that just configures Elasticsearch without requiring this.

For JHipster 4, as we have a very close deadline, we could also just remove the option!

**Comment by jdubois** [comment]
Just tested it, in fact this option is not available, so I did think of it!!
No idea what the person on Twitter did exactly, so I'm closing this.

**Comment by gzsombor** [comment]
I guess, they used ElasticSearch as a full blown persistence layer, just like Cassandra or MongoDB or MySQL.

**Comment by jdubois** [comment]
Yes, this is an option we could also have, but not during the code freeze. And I need to check in the stats if many people really use the "no database" option, to know if that's worth doing.
