### ISSUE TITLE
Build is broken because of _Elasticsearchonfiguration.java

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4996]
Sorry everyone, I broke the build with https://github.com/jhipster/generator-jhipster/commit/e5a7fced3be5418d197b9173cfbe3133d72c7dea

I must have some filesystem issue, on my laptop the file is correctly named `_Elasticsearchonfiguration.java` (and tests pass!!), but on GitHub I see it `_ElasticSearchonfiguration.java` (with the capital S). And I'm not able to rename it: doing a `git status` after renaming it does nothing!

I'll check this later, sorry.

**Comment by pascalgrimaud** [comment]
I already had this issue when I was on Windows.
Maybe you have to use `git mv old_file new_file` if I remember well

**Comment by jdubois** [comment]
Yes I understand this on Windows, but I'm on a Mac! Never occurred to me before!
Thanks!!!
