### ISSUE TITLE
[ng2] Too many compilation warnings in browser

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#4998]
In ng2, when using `yarn start` the browser's console shows too many compilation warnings about files that the user cannot change:  `reflect-metadata/Reflect.ts`, `polyfill.ts`, .... As a result, user has to scroll up a lot to see real errors.

We should find a way to exclude them to have a greater user experience.

**Comment by deepu105** [comment]
Absoluteley but this can be part of our post release improvement can you add this as an item in #4794

**Comment by jdubois** [comment]
Yes indeed, we don't have the time at the moment for this, let's do it after the release

**Comment by jdubois** [comment]
Closing this as it's already listed in #4794
