### ISSUE TITLE
CacheConfiguration.java template is generating the class with missing imports.

### ISSUE THREAD

**Issue by smouelhi** [jhipster/generator-jhipster#5000]
##### **Overview of the issue**

When creating a miscroservice gateway, the CacheConfiguration.java is missing some dependencies. 

##### **Motivation for or Use Case**

the project doesn't build after jhipster creation.

##### **Reproduce the error**

Create a microservice gateway, select kafka hazel cast and web sockets, build the project --> CacheConfiguration.java is missing some imports.

##### **Suggest a Fix**

add the following:
import org.springframework.boot.autoconfigure.web.ServerProperties;
import org.springframework.cloud.client.discovery.DiscoveryClient;

when choosing hazel cast + web sockets + kafka.

##### **JHipster Version(s)**

3.12.2 as of January 29th.

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "Dashboard",
    "packageName": "com.talquest.platform.gw.dashboard",
    "packageFolder": "com/talquest/platform/gw/dashboard",
    "serverPort": "8780",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "52196e0fd9bdd0b66d9a36341916ccea5a9da5ed",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "clientFramework": "angular2",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-ionic",
        "version": "2.1.6"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de"
    ]
  }
}
```

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Hi @smouelhi ! I confirm your issue. Would you like to do a PR ?

**Comment by smouelhi** [comment]
@jdubois was definitely faster than me! Thanks @jdubois !
