### ISSUE TITLE
Social login doesn't work

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5002]
This comes from our JHipster 4 tests, see https://github.com/jhipster/generator-jhipster/issues/4301#issuecomment-275880677

- With Angular 2, the login seems to work, but we get redirected to a page with no view (there's the menu and footer, but nothing in the middle)
- With AngularJS 1 I can't get authenticated by Google (and I'm using the same codes as for Angular 2, in the previous point). When logging in, Google sends back the error `The redirect URI in the request, http://localhost:8080/signin/google, does not match the ones authorized for the OAuth client`

**Comment by ruddell** [comment]
For NG1, that looks like a misconfiguration on the google side.  Your authorized redirect URIs should include "http://localhost:8080/signin/google" like below:
<img width="628" alt="screen shot 2017-01-29 at 10 06 39 am" src="https://cloud.githubusercontent.com/assets/4294623/22406610/af72fe60-e60a-11e6-9f3a-fb55876d220d.png">

**Comment by jdubois** [comment]
@ruddell you know this better than me, so if for you that's OK, don't hesitate to close the issue. Thanks for your help on this difficult issue!!

**Comment by haifzhan** [comment]
@ruddell Your post really helps, thanks!
