### ISSUE TITLE
Prod profile errors

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5004]
This comes from our JHipster 4 tests, see https://github.com/jhipster/generator-jhipster/issues/4301#issuecomment-275880677

On all projects, when doing a "prod" build, there is still a banner (the "ribbon" that shows we are in dev mode).

- If the project has i18n enabled, the ribbon gets the message "translation-not-found".
- If the project hasn't got i18n, the ribbon doesn't have any message in it

This is probably an error in the Webpack configuration.

**Comment by deepu105** [comment]
I guess prod profile might still be using dev config for client side. this needs to be checked

**Comment by VictorADS** [comment]
I think it is handled in the application.yml ```    ribbon:
        display-on-active-profiles: dev```

**Comment by deepu105** [comment]
yes but maybe when webpack prod build is called this param isnt set properly in the `app.constants.ts` file

**Comment by deepu105** [comment]
oh wait there should be an backedn service providing that data I guess. Im away from computer ill check later

**Comment by jdubois** [comment]
I'm not sure how it works: it used to be some kind of regexp that was removing the banner during the prod build, but now I think it's a REST request that reads the profile information, and displays it. It's one more request, but it works for all profiles, and many people add test, pre-prod, etc profiles.

**Comment by jdubois** [comment]
I got it, let me do it.
