### ISSUE TITLE
"dev" mode with Websocket isn't user-friendly

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5005]
This comes from our Angular 2 test cases - see https://github.com/jhipster/generator-jhipster/issues/4301#issuecomment-275883927

With Websockets selected:

- it works in "prod" mode
- in "dev" mode there is no way to use it correctly: with just HMR (port 9060) or with BrowserSync + HMR (port 9000) the socket can't be opened, so it's impossible to develop easily. You need to restart everything, as far as I can tell.

I'm not sure this is easy to solve because of HMR, but we should provide a work-around so people can work effectively with Websockets

**Comment by jdubois** [comment]
Removing the v4 tag, it's less urgent than the other tickets.

**Comment by flaviencathala** [comment]
I made a PR for this but it's still not really fixed.

**Comment by ruddell** [comment]
One option for this is to add `http://localhost:9000` as an allowed origin to the websockets.  [This one line](https://github.com/ruddell/jhipster-examples/commit/edbade1823ca278996b8f311ffcc256e2b43fb75) allows port 9000 to connect.  The browser console still shows a connection error but all websocket messages send/receive correctly.  Is there a downside to this?

**Comment by jdubois** [comment]
@ruddell we also have a JHipster-specific CORS configuration, see https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/resources/config/application.yml#L68 (and this is configured in the WebConfigurer class). We could have this enabled in "dev" mode only, and not "prod". I find this quite a good solution, in fact.
Could you have a look and tell me what you think of it? Maybe even test it and do the PR?

**Comment by ruddell** [comment]
I will handle it this week
