### ISSUE TITLE
LocalDate and ZonedDateTime do not work properly

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5006]
This comes from our JHipster 4 tests at https://github.com/jhipster/generator-jhipster/issues/4301#issuecomment-275901699

- LocalDate and ZoneDateTime cannot be edited - when you edit the entity, there is an error and the page reloads
- ZoneDateTime doesn't show the time (it's the same as LocalDate), so it can't be used properly

**Comment by pascalgrimaud** [comment]
I spend a couple of hours on it, but I didn't manage to find the appropriate solution. It seems to be more complex than I expected...
Here some links which can help :
- https://github.com/ng-bootstrap/ng-bootstrap/issues/754
- http://stackoverflow.com/questions/41658935/ngbdatepicker-how-to-bind-longdate-string-to-ngmodel

**Comment by jdubois** [comment]
The DatePicker component (see https://ng-bootstrap.github.io/#/components/datepicker ) doesn't support the time, so it won't work with ZonedDateTime whatever we do...
So we must either find another solution, or removed this option for the moment. I guess the LocalDate is what everybody use anyway.

**Comment by jdubois** [comment]
Another solution for LocalDate (and maybe also ZonedDateTime) is to use the standard HTML5 component.

That's what we used to do: it's not very pretty, it doesn't work on all browsers, and it's not possible to configure it, but at least it's easy to work with, and it's "standard".

**Comment by VictorADS** [comment]
I'm working on it

**Comment by jdubois** [comment]
Great @VictorADS -> your fix "works on my machine", so I'm merging it.

For ZonedDateTime we have no solution at the moment, except using the HTML5 component, which is not really good:

- I keep this ticket open for this ZonedDateTime issue
- I will remove the ZonedDateTime from the options in JHipster 4, and thus remove the v4 tag here, so we can move forward

**Comment by cbornet** [comment]
ZonedDateTime is our only type to describe a date+time (LocalDate is date only). So removing it seems a bit harsh. I would rather have the HTML5 component even if it's unsatisfying and needs to be replaced later.

**Comment by cbornet** [comment]
Actually, my whole app is about timeseries. So please don't remove ZonedDateTime or I won't be able to upgrade !!

**Comment by jdubois** [comment]
Oh, OK @cbornet -> then let's go for the HTML5 component, it's better than nothing... @VictorADS do you think you could do it? @cbornet could you help?

**Comment by pascalgrimaud** [comment]
Good job @VictorADS !
I agree, we can go HTML5 component, then improve it later, after the release of JHipster 4

**Comment by deepu105** [comment]
ng-bootstrap doesnt have a dateTimePicker but we certainly can combine datePicker and Timepicker to do it like we do on angular1. I'll implement that directive in ng-jhipster after our Beta release hence im tagging this with ng-jhipster

**Comment by jdubois** [comment]
Totally agree @deepu105 but in the meantime are you OK to go full HTML5 for the ZonedDateTime ?

**Comment by deepu105** [comment]
yes absolutely its better than nothing

**Comment by jdubois** [comment]
In that case we would use input type=datetime-local but we might need to add a specific method in ng-jhipster to transform that String to a Date.

**Comment by VictorADS** [comment]
@jdubois  Maybe Date has already some function to convert it. I'm on it.

**Comment by jdubois** [comment]
Great :-)

**Comment by gmarziou** [comment]
Due to current state of NgbDatePicker, at work we switched to PrimeNG. I mention it here just in case some users wants a better alternative that works.

**Comment by deepu105** [comment]
@gmarziou yes its a good toolkit but I dont think it plays nice with BS4 as they have their own theming system which is more of jquery-ui like

**Comment by gmarziou** [comment]
So far it works fine with BS4 grid, though I used only calendar, slider and dataGrid
