### ISSUE TITLE
"Pager" is not implemented

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5007]
This comes from our JHipster 4 tests at https://github.com/jhipster/generator-jhipster/issues/4301#issuecomment-275901699

When creating an entity, selecting a "pager" gives in fact a "pagination" component.

This is mostly useful for Cassandra, and maybe in some performance-specific scenarios if you use an SQL or a MongoDB database. Otherwise, the "pagination" is always better, that's why I'm putting this as "minor".

**Comment by deepu105** [comment]
we use ng-bootstrap and it doesn not have a pager component hence we either need to implement our own or remove the option.
We could implement it in ng-jhipster if needed. it would a simple component

**Comment by jdubois** [comment]
OK @deepu105 
So I will remove the option in the "prompts", and remove the v4 label, and we'll correct that later.

**Comment by jdubois** [comment]
So there's nothing available in ng-bootstrap, and this is not a very important component - I mostly kept it for Cassandra (you can't have proper pagination with Cassandra as you shouldn't do `count`), but we have less than 0.5% of people using Cassandra.
It's not really worth to do our own component: when one will be ready in ng-bootstrap, we will use it, and in the meantime I'm closing this.

**Comment by sendilkumarn** [comment]
Since bs4 did not have pager. Ng-bootstrap removed it.
