### ISSUE TITLE
Installation of Jhipster is getting failed giving error.

### ISSUE THREAD

**Issue by pankajppr** [jhipster/generator-jhipster#5015]
##### **Overview of the issue**

Installation of Jhipster is getting failed giving error.

##### **Motivation for or Use Case**

Cloned the Git repo https://github.com/jhipster/generator-jhipster.git and unable to proceed further. followed all the instruction given for installation but it is failing giving below error in the end.

##### **Reproduce the error**

C:\Users\panka\workspace\Hipster\generator-jhipster>yo jhipster
...
...
...
? (14/15) Would you like to enable internationalization support? No
? (15/15) Besides JUnit and Karma, which testing frameworks would you like to use? (Press to select, to toggle all, to inverse selection)
events.js:141
throw er; // Unhandled 'error' event
^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in C:\Users\panka\workspace\Hipster\generator-jhipster\generators\server\templates_README.md while compiling ejs
at Function (native)
at Object.Template.compile (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\ejs\lib\ejs.js:495:12)
at Object.compile (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\ejs\l

##### **Related issues**

Not yet

##### **JHipster Version(s)**

It is regression
##### **JHipster configuration**

generator-jhipster@3.12.2 C:\Users\panka\workspace\Hipster\generator-jhipster
`-- generator-jhipster@3.12.2  -> C:\Users\panka\workspace\Hipster\generator-jhipster extraneous
cat: no such file or directory: .yo-rc.json
ls: no such file or directory: .jhipster/*.json
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

node: v4.4.7
npm: 4.1.2
bower: 1.8.0
gulp:
[22:43:37] CLI version 1.2.2
yeoman: 1.8.5
yarn: 0.19.1

##### **Browsers and Operating System**

Win10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Try upgrading to a newer Node version, and you could also try Yarn instead of NPM. We don't support older Node versions.

**Comment by chakshugupta04** [comment]
getting an error "   Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm " please help me in tis
![untitled](https://user-images.githubusercontent.com/45142996/48674115-e7a3c600-eb6e-11e8-9056-80dfc85dbe91.png)
