### ISSUE TITLE
Webpack dev config should exclude some directories from watching

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#5033]
On my Fedora PC, hot reloading was not working, I rebooted and it worked like a charm but then after I launched GitKraken who warned me that it would not be able to watch my repos because the maximum number of inotify watchers was exceeded. My guess is that when this limit is exceeded, Webpack can't do hot reloading. I made some research and found that my kernel was configured for 8192 inotify, I raised the limit to 100000.

On OSX, these are called fsevents.

My point is that with only watchers for project files , I would never have exceeded this limit, so to me it means that Webpack is watching more files than it should, most obvious culprits would be watching `node_modules`, `node`,`target` or `build` directories.

So it seems there are several ways to ignore some folders from being watched:
- https://webpack.js.org/configuration/watch/ which seems limited to one folder name or one regex
- [WatchIgnorePlugin](https://github.com/webpack/docs/wiki/list-of-plugins#watchignoreplugin) which seems to be more configurable 

I know nothing about Webpack so I could be completely wrong. I'd appreciate if one of our experts could have a look because I suspect it could be a big performance boost.

**Comment by jdubois** [comment]
Yes that's important for v4!

**Comment by deepu105** [comment]
I'll take a look as well, I don't think we are watching node_modules

Thanks & regards,
Deepu

**Comment by VictorADS** [comment]
We are watching nor node_modules nor target folders. Only src which contains also the test, should I try to get rid of it ?

**Comment by deepu105** [comment]
We should only watch src/main/webapp

**Comment by gmarziou** [comment]
OK then I don't understand how I could exceed inotify watchers with only 120 files and a limit of 8192.

**Comment by gmarziou** [comment]
I confirm that changing a file in `node_modules` or `target` does not trigger a reload.
Watching only `src/main/webapp` is an improvement though over `src`: from 696 to 450 on my project.

So, probably the issue is somewhere else, I was running IDEA, VS Code and webpack when it occured.

**Comment by mraible** [comment]
@gmarziou Do you have TypeScript compilation turned on? I never do this in IntelliJ because it litters my source tree with .js files.

**Comment by gmarziou** [comment]
Same as you Matt, I disable this as I got caught once.

**Comment by gmarziou** [comment]
Let's close this issue as I doubt there's more we can do.
