### ISSUE TITLE
Docker file fails to build

### ISSUE THREAD

**Issue by MitchDresdner** [jhipster/generator-jhipster#5041]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

Unable to build Docker image

##### **Motivation for or Use Case**

Needed for Docker

##### **Reproduce the error**

run: gradle buildDocker

##### **Related issues**

I dunno?

##### **Suggest a Fix**

Change references from: war   to: jar

In src/main/Docker/Dockerfile
    gradle/docker.gradle

##### **JHipster Version(s)**

latest

##### **JHipster configuration**

n/a

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

Windows10

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Can you also give us the error?  And by latest version do you mean v3.12.2?

**Comment by jdubois** [comment]
Sorry but you're not giving enough information to reproduce.... No `.yo-rc.json`, no version (what is "latest"??).
I'm giving it a try with the latest master, as we'll do a release soon it's worth checking.

**Comment by MitchDresdner** [comment]
It dies at stage 3 bc Gradle is building jar files, though the Dockerfile and docker.gradle are expecting .war:buildDocker   Step 1/7 : FROM openjdk:8-jre-alpine ---> d85b17c6762euildDockerStep 2/7 : ENV JHIPSTER_SLEEP 0 ---> Using cache ---> d035ab6c47d9Step 3/7 : ADD *.war /app.warNo source files were specified:buildDocker FAILED-----Original Message-----

**Comment by jdubois** [comment]
Could we have something clear, please?

**Comment by MitchDresdner** [comment]
Welcome to the JHipster Generator v3.12.2-----Original Message-----

**Comment by jdubois** [comment]
Anyway, me test worked perfectly, so I can't reproduce... I'm not wasting any more time here, sorry but if you want me to help, I need a clear ticket!

**Comment by pascalgrimaud** [comment]
@MitchDresdner : your messages are very hard to read... 

Anyway, your logs indicate your problem:
```
Using cache ---> d035ab6c47d9Step
3/7 : ADD *.war /app.war
No source files were specified
:buildDocker FAILED
```

Your command is not enough: `gradle buildDocker`

You need the war file, so it is: `gradle bootRepackage buildDocker`

**Comment by gmarziou** [comment]
> your messages are very hard to read...

Yes, replying to github by mail can be very bad depending on which mail client you use.

**Comment by MitchDresdner** [comment]
thanks!was planning to get back to it in the morning and thinking gradle wasn't in the proper state to build the docker image, as you confirm.  -----Original Message-----

**Comment by MitchDresdner** [comment]
works like a charm, thanks again!-----Original Message-----

**Comment by gmarziou** [comment]
@MitchDresdner please stop posting via email until you use a working mail client, it's impossible to read !!

**Comment by jdubois** [comment]
Sorry but I'm not even reading this...
