### ISSUE TITLE
Account Register component not working properly

### ISSUE THREAD

**Issue by nicoraynaud** [jhipster/generator-jhipster#5044]
##### **Overview of the issue**

While working with latest master branch, with angular 2, i noticed that the register form is not displaying errors when server side web service returns an HTTP 400 response.

##### **Motivation for or Use Case**

I feel this is just a ng2 migration issue, and could be easily fixed before the release coming soon.

##### **Reproduce the error**

Install latest generator-jhipster (as of today), create an app, run it and 
- go to http://localhost:9000/#/register
- set "admin" as username (this is to get the "login already exists" error)
- Fill in the other fields without errors.
- Click "subscribe

=> The form does not show the related error's div while the query has been made the server returned the HTTP 400.

##### **Suggest a Fix**

in **/app/account/register/register.component.ts** : i moved the content of "processError" private method as a lambda directly following the service call. This way, the changes made on the components data gets picked up by the template. 
I also had to change the check on the content of the response. It was checking whether response.data === "the string" while I had to check against **reponse._body**

Note that I am a js and ng2 beginner, so i'm really not sure i got this the proper way !

```
register() {
        if (this.registerAccount.password !== this.confirmPassword) {
            this.doNotMatch = 'ERROR';
        } else {
            this.doNotMatch = null;
            this.error = null;
            this.errorUserExists = null;
            this.errorEmailExists = null;
            this.languageService.getCurrent().then(key => {
                this.registerAccount.langKey = key;
                this.registerService.save(this.registerAccount).subscribe(() => {
                    this.success = true;
                }, error => {
                    this.success = null;
                    if (error.status === 400 && error._body === 'login already in use') {
                        this.errorUserExists = 'ERROR';
                    } else if (error.status === 400 && error._body === 'e-mail address already in use') {
                        this.errorEmailExists = 'ERROR';
                    } else {
                        this.error = 'ERROR';
                    }
                });
            });
        }
    }
```

Note that if i were to suggest more changes to this component, i would change the error variables from "string" to "boolean" data type, to make it more readable. (right now, we set "ERROR" when there is an error and null otherwise => this seems to me like a boolean type being disguised :D ).

##### **JHipster Version(s)**

JHipster v.3.12.2

##### **JHipster configuration**
.yo-rc.json

```
{                                                              
  "generator-jhipster": {                                      
    "jhipsterVersion": "3.12.2",                               
    "baseName": "optone",                                      
    "packageName": "nc.opt.template",                          
    "packageFolder": "nc/opt/template",                        
    "serverPort": "8080",                                      
    "authenticationType": "jwt",                               
    "hibernateCache": "ehcache",                               
    "clusteredHttpSession": false,                             
    "websocket": false,                                        
    "databaseType": "sql",                                     
    "devDatabaseType": "h2Disk",                               
    "prodDatabaseType": "postgresql",                          
    "searchEngine": false,                                     
    "messageBroker": false,                                    
    "buildTool": "maven",                                      
    "enableSocialSignIn": false,                               
    "jwtSecretKey": "70a20309af8c06c2652019d9bf7570c92df7de9e",
    "useSass": true,                                           
    "clientPackageManager": "yarn",                            
    "applicationType": "monolith",                             
    "clientFramework": "angular2",                             
    "testFrameworks": [                                        
      "gatling"                                                
    ],                                                         
    "jhiPrefix": "jhi",                                        
    "enableTranslation": true,                                 
    "nativeLanguage": "fr",                                    
    "languages": [                                             
      "fr"                                                     
    ]                                                          
  }                                                            
}          
```                                                    

##### **Browsers and Operating System**

OS: Windows 10 Pro
Browser: Chrome v55.0.2883.87 m (64-bit)

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by flaviencathala** [comment]
@nicoraynaud It's fixed, thanks to you we will not have this bug in the 4.0 !
