### ISSUE TITLE
Convert BS3 hidden-* to BS4

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#5047]
The CSS classes from Bootstrap 3 that we use to hide things have been replaced in Bootstrap 4.

BS 3 | BS 4
------------ | -------------
 hidden-xs | hidden-xs-down
 hidden-xs hidden-sm | hidden-sm-down

See http://v4-alpha.getbootstrap.com/layout/responsive-utilities/

I can PR it tomight, if someone can do it now in the afternoon, please do so.

**Comment by wmarques** [comment]
Also it seems that we have to replace all our hidden-sm-down by hidden-lg-down (from BS4 doc) : 

> Note that the changes to the grid breakpoints in v4 means that you’ll need to go one breakpoint larger to achieve the same results (e.g. .hidden-md is more similar to .hidden-lg-down than to .hidden-md-down).

**Comment by gmarziou** [comment]
good point, I did not know

**Comment by wmarques** [comment]
Didn't test yet I'll let you know 👍

**Comment by VictorADS** [comment]
@gmarziou  @wmarques I don't think we can hide a specific screen size (except for xs and lg) due to how `hidden-*-down` and `hidden-*-up` works.
Btw `hidden-sm-down hidden-sm-up` will not work because it will hide for every screen size !

**Comment by gmarziou** [comment]
What about ` hidden-sm-down hidden-md-up` ?

**Comment by VictorADS** [comment]
@gmarziou  It will show only to users with `sm` screen size

**Comment by gmarziou** [comment]
OK

**Comment by deepu105** [comment]
I think we changed it in most places. I did a find now and see only one
place where we didnt change this


Thanks & Regards,
Deepu
