### ISSUE TITLE
MockMvc doesn't use ExceptionTranslator in the integration tests

### ISSUE THREAD

**Issue by ddidier** [jhipster/generator-jhipster#5049]
##### **Overview of the issue**

The handlers in `ExceptionTranslator` are not taken into account by the `MockMvc` in the `XxxResourceIntTest`.

##### **Motivation for or Use Case**

I want to test my custom exception handling.

##### **Reproduce the error**

Add a handler in `ExceptionTranslator` such as 

```
    @ExceptionHandler(DataIntegrityViolationException.class)
    @ResponseStatus(CONFLICT)
    @ResponseBody
    public ErrorVM processDataIntegrityViolationException(DataIntegrityViolationException ex) {
        return new ErrorVM("DataIntegrityViolationException");
    }
```

Then raise a `DataIntegrityViolationException` from the service.
When you access this service with the server running you get a 409: OK
When you access this service from the integration test, you get a `NestedServletException` if I recall: KO

##### **Related issues**

n/a

##### **Suggest a Fix**

I'm no expert in Spring (I'm actually a complete noob), but I think the generated code must use `setControllerAdvice()`. So we should replace in the `setup()` method:

```
        this.restXxxMockMvc = MockMvcBuilders.standaloneSetup(xxxResource)
                .setCustomArgumentResolvers(pageableArgumentResolver)
                .setMessageConverters(jacksonMessageConverter)
                .build();
```

by

```
        this.restXxxMockMvc = MockMvcBuilders.standaloneSetup(xxxResource)
                .setCustomArgumentResolvers(pageableArgumentResolver)
      =====>    .setControllerAdvice(exceptionTranslator)
                .setMessageConverters(jacksonMessageConverter)
                .build();
```

##### **JHipster Version(s)**

I was on the master branch, not sure where since I upgraded.

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "inPhase",
    "packageName": "xxx",
    "packageFolder": "xxx",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "xxx",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

n/a

**Comment by jdubois** [comment]
Not sure if that would solve that problem, but indeed this method should be added.
I'm testing this.
