### ISSUE TITLE
Anonymous user is send whereas it should not

### ISSUE THREAD

**Issue by nicoraynaud** [jhipster/generator-jhipster#5052]
##### **Overview of the issue**

The pagination elements generated for entities are not working (tested only with ng2)

##### **Reproduce the error**

- Create an app
- Generate an entity with pagination "entity"
- create many elements (or change pagination default size)
- try to use the pagination buttons in the generated component "entity.component.html"

=> The buttons don't work as expected.

In comparison, the pagination elements in the Audit admin view work ok.

##### **Suggest a Fix**

I think the paginated elements should be changed in the entity generator from

```
<div class="text-xs-center" *ngIf="jobs && jobs.length">
            <jhi-item-count [page]="page" [total]="queryCount" [itemsPerPage]="itemsPerPage"></jhi-item-count>
            <ngb-pagination [collectionSize]="totalItems" [(page)]="page" (pageChange)="loadPage(page)"></ngb-pagination>
        </div>
```
to
```
<div class="text-xs-center" *ngIf="jobs && jobs.length">
            <jhi-item-count [page]="page" [total]="queryCount" [itemsPerPage]="itemsPerPage"></jhi-item-count>
            <ngb-pagination [collectionSize]="totalItems" [(page)]="page" [pageSize]="itemsPerPage"  (pageChange)="loadPage(page)"></ngb-pagination>
        </div>
```

##### **JHipster Version(s)**

JHipster v.3.12.2

##### **JHipster configuration**
.yo-rc.json

```
{                                                              
  "generator-jhipster": {                                      
    "jhipsterVersion": "3.12.2",                               
    "baseName": "optone",                                      
    "packageName": "nc.opt.template",                          
    "packageFolder": "nc/opt/template",                        
    "serverPort": "8080",                                      
    "authenticationType": "jwt",                               
    "hibernateCache": "ehcache",                               
    "clusteredHttpSession": false,                             
    "websocket": false,                                        
    "databaseType": "sql",                                     
    "devDatabaseType": "h2Disk",                               
    "prodDatabaseType": "postgresql",                          
    "searchEngine": false,                                     
    "messageBroker": false,                                    
    "buildTool": "maven",                                      
    "enableSocialSignIn": false,                               
    "jwtSecretKey": "70a20309af8c06c2652019d9bf7570c92df7de9e",
    "useSass": true,                                           
    "clientPackageManager": "yarn",                            
    "applicationType": "monolith",                             
    "clientFramework": "angular2",                             
    "testFrameworks": [                                        
      "gatling"                                                
    ],                                                         
    "jhiPrefix": "jhi",                                        
    "enableTranslation": true,                                 
    "nativeLanguage": "fr",                                    
    "languages": [                                             
      "fr"                                                     
    ]                                                          
  }                                                            
}          
```                                                    

##### **Browsers and Operating System**

OS: Windows 10 Pro
Browser: Chrome v55.0.2883.87 m (64-bit)

[x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Could you clarify what does not work because for me it seems to work though I tested only with 24 elements.

**Comment by nicoraynaud** [comment]
Oops, I re did a project with latest generator and it seems to work perfectly for generated entities. Very sorry for the wrong info. I think that bug was fixed and i did not regenerated my entities since.

The pagination in Audit and User management is still a bit weird though

In order to test i have changed **src\main\webapp\app\shared\constants\pagination.constants.ts**
to set  **ITEMS_PER_PAGE = 2;**

- **user management view** : with a pagination of 2, the first page shows 1 item, and the second page the 2 others. If i change the sort property to login:desc, i get 2 items on the first page and 1 item on the second one. this seems a minor bug though, data is here !

- **audits view** : here it is different : when i click on "nextPage", it triggers the ws call but the screen doesn't get refreshed. When i click on the page number that is already selected : then it displays the correct data.
again : if i click on a page number, nothing happens (only the ws call in the background), and i need to click it again to show the page's content.

do I need to correct this issue's title ?

**Comment by gmarziou** [comment]
Yes please change for a better title

**Comment by ruddell** [comment]
The reason user management is weird is because we hide anonymousUser (even though it is retrieved from the server).  Not sure about audits

**Comment by VictorADS** [comment]
I think we forgot to migrate Audits component properly, I see that we are not resolving the params in auditsRoute so I'll make a PR to fix that.

**Comment by jdubois** [comment]
- For the audit this is fixed, the PR is merged

**Comment by flaviencathala** [comment]
@nicoraynaud About the user management view issue, the pagination works actually well.
The reason is that in the first page there is an "anonymous" user, and it was hidden, so only one user was printed.
I will make a fix to remove this filter for anonymous user, and we will change the back code so the client don't receive at all this anonymous user.
Thanks for having pointed out this issue.

**Comment by gmarziou** [comment]
> I will make a fix to remove this filter for anonymous user, and we will change the back code so the client don't receive at all this anonymous user.

If you do it on server side, don't forget to change also the angular 1 code.

**Comment by flaviencathala** [comment]
@gmarziou Thanks, I just removed it for ng1 in my PR.

**Comment by jdubois** [comment]
Closing as #5203 is merged
