### ISSUE TITLE
Obsolete CSS classes for sorting in ng2

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#5055]
In ng1, we had less visible sorting icons in table headers unless mouse over.
This was based on glyphicons and `jh-table` classes, so either:
- we update these classes to get same behavior in ng2 with fontawesome
- we remove theses classes if we don't want same look and feel

~~~css
.jh-table > tbody > tr > td {
    /* Align text in td verifically (top aligned by Bootstrap) */
    vertical-align: middle;
}

.jh-table > thead > tr > th > .glyphicon-sort, .jh-table > thead > tr > th > .glyphicon-sort-by-attributes, .jh-table > thead > tr > th > .glyphicon-sort-by-attributes-alt {
    /* less visible sorting icons */
    opacity: 0.5;
}

.jh-table > thead > tr > th > .glyphicon-sort:hover, .jh-table > thead > tr > th > .glyphicon-sort-by-attributes:hover, .jh-table > thead > tr > th > .glyphicon-sort-by-attributes-alt:hover {
    /* full visible sorting icons and pointer when mouse is over them */
    opacity: 1;
    cursor: pointer;
}
~~~

**Comment by deepu105** [comment]
Lests remove it as the icons are now configurable

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
Else we can make it generic to work with any icons

Thanks & regards,
Deepu

**Comment by gmarziou** [comment]
Let's remove them, the new icons are less intrusive than the old ones, so maybe no need to play with their opacity.

**Comment by deepu105** [comment]
ok


Thanks & Regards,
Deepu
