### ISSUE TITLE
Node 6.9.0 should be required

### ISSUE THREAD

**Issue by jvence** [jhipster/generator-jhipster#5065]
Welcome to the JHipster Generator v4.0.0
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: /Users/alain/dev/project/myapp/HPWebServices2.1/gateway
WARNING! yarn is not found on your computer.

? (1/15) Which *type* of application would you like to create? Microservice gateway
? (2/15) Which *Framework* would you like to use for the client? [BETA] Angular 2.x
? (3/15) What is the base name of your application? hpgateway
? (4/15) Would you like to install other generators from the JHipster Marketplace? No
? (5/15) As you are running in a microservice architecture, on which port would like your server to run? It should be
 unique to avoid port conflicts. 8082
? (6/15) What is your default Java package name? com.myapp.gateway
? (7/15) Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? (8/15) Which Service Discovery and Configuration solution would you like to use? JHipster Registry (using Eureka an
d Spring Cloud Config)
? (9/15) Which *type* of database would you like to use? MongoDB
? (10/15) Would you like to use Maven or Gradle for building the backend? Maven
? (11/15) Which other technologies would you like to use? (Press <space> to select)
? (12/15) Would you like to use the LibSass stylesheet preprocessor for your CSS? No
? (13/15) Would you like to enable internationalization support? No
? (14/15) Besides JUnit and Karma, which testing frameworks would you like to use? Gatling
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in /usr/local/lib/node_modules/generator-jhipster/generators/server/templates/_README.md while compiling ejs
    at Function (native)
    at Object.Template.compile (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:495:12)
    at Object.compile (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:306:16)
    at handleCache (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:169:18)
    at Object.exports.render (/usr/local/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:332:10)
    at copy.extend.process (/usr/local/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
gateway >>

**Comment by jdubois** [comment]
No node/npm version, no help....

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jvence** [comment]
NPM 4.1.2
Node v4.4.1

**Comment by jdubois** [comment]
Thanks @jvence !
Then you need to upgrade, as we don't support node version less than 6.9.0.

This shouldn't happen, as we forced this in our package.json, that's why I'm reopening this as a bug.

And if you don't want any trouble, use Yarn instead!

**Comment by jdubois** [comment]
I have also renamed the ticket to make it clearer.

**Comment by jvence** [comment]
Upgrading Node solves issue.

**Comment by jdubois** [comment]
Thanks @jvence - that's normal :-)
Then I don't understand why you could run the generator in the first place, it should refuse to start if you have an older version. This is why I'm keeping this open.

**Comment by gmarziou** [comment]
Maybe we should use engineStrict

http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html#enginestrict

**Comment by gmarziou** [comment]
Useful info: http://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-packages-json

**Comment by jdubois** [comment]
Closing as I merged the PR from @pascalgrimaud
