### ISSUE TITLE
User Management Page With Wrong ID in Delete Popup Message

### ISSUE THREAD

**Issue by mfalzetta** [jhipster/generator-jhipster#5074]
##### **Overview of the issue**

**Bug en deletion popup.**
The message showed is "Are you sure you want to delete this User {{ id }}?".
The ide is show de login of the user, but show the string "{{ id }}".

##### **Motivation for or Use Case**

The popup for delete User show string {{id}}, when the correct is a long id of the user.

##### **Reproduce the error**

1. Go to User Management Page.
2. Choose a User for delete.
3. Click in the delete button
4. Se the message "Are you sure you want to delete this User {{ id }}?"

##### **Suggest a Fix**

**If want to show the id, change user-management.component.html as below:**
**From:**
[routerLink]="['/', { outlets: { popup: 'user-management/'+ **user.login** + '/delete'} }]"
**To:**
[routerLink]="['/', { outlets: { popup: 'user-management/'+ **user.id** + '/delete'} }]"

**If want to show the login in deletion page, change user-management.json**
**From:**
"question": "Are you sure you want to delete this User {{ **id** }}?"
**To:**
"question": "Are you sure you want to delete this User {{ **login** }}?"

##### **JHipster Version(s)**

I'm user the JHipster 4.0.0 versin with Angular 2.

##### **JHipster configuration**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.11.0

node: v6.9.5

npm: 3.10.10

bower: 1.8.0

gulp:
[01:20:20] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.20.0

cat .yo-rc.json 
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.0",
    "baseName": "smartnoteweb",
    "packageName": "com.quatroc.smartnote",
    "packageFolder": "com/quatroc/smartnote",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-module",
        "version": "1.1.0"
      },
      {
        "name": "generator-jhipster-gitlab-ci-build-status",
        "version": "0.0.1"
      },
      {
        "name": "generator-jhipster-nav-element",
        "version": "0.0.5"
      },
      {
        "name": "generator-jhipster-angular-ui",
        "version": "0.0.2"
      },
      {
        "name": "generator-jhipster-webservice",
        "version": "0.1.0"
      },
      {
        "name": "generator-jhipster-vuejs",
        "version": "0.0.3"
      },
      {
        "name": "generator-jhipster-stormpath",
        "version": "0.0.3"
      },
      {
        "name": "generator-jhipster-swagger-cli",
        "version": "2.0.5"
      },
      {
        "name": "generator-jhipster-material",
        "version": "0.0.0"
      },
      {
        "name": "generator-jhipster-entity-audit",
        "version": "2.2.2"
      },
      {
        "name": "generator-jhipster-darktheme",
        "version": "0.0.7"
      },
      {
        "name": "generator-jhipster-google-analytics",
        "version": "0.0.1"
      },
      {
        "name": "generator-jhipster-mssql",
        "version": "2.1.1"
      },
      {
        "name": "generator-jhipster-ionic",
        "version": "2.1.6"
      },
      {
        "name": "generator-jhipster-debian-packager",
        "version": "1.0.1"
      },
      {
        "name": "generator-jhipster-google-maps",
        "version": "0.0.1"
      },
      {
        "name": "generator-jhipster-bootswatch",
        "version": "1.0.2"
      },
      {
        "name": "generator-jhipster-elasticsearch-reindexer",
        "version": "0.2.0"
      },
      {
        "name": "generator-jhipster-bootstrap-material-design",
        "version": "3.5.1"
      },
      {
        "name": "generator-jhipster-react",
        "version": "0.0.0"
      },
      {
        "name": "generator-jhipster-leaflet",
        "version": "1.0.0"
      },
      {
        "name": "generator-jhipster-entity-audit-and-delete",
        "version": "2.2.2"
      },
      {
        "name": "generator-jhipster-angular-datatables",
        "version": "1.3.1"
      },
      {
        "name": "generator-jhipster-basic-auth",
        "version": "1.0.1"
      },
      {
        "name": "generator-jhipster-transasia",
        "version": "1.0.6"
      },
      {
        "name": "generator-jhipster-fortune",
        "version": "0.0.2"
      },
      {
        "name": "generator-jhipster-docker",
        "version": "2.2.0"
      },
      {
        "name": "generator-jhipster-swagger2markup",
        "version": "1.1.0"
      },
      {
        "name": "generator-jhipster-ci",
        "version": "1.0.0"
      },
      {
        "name": "generator-jhipster-spring-social-connectors",
        "version": "0.0.1"
      },
      {
        "name": "generator-jhipster-compodoc",
        "version": "0.0.1"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br"
    ]
  }

##### **Browsers and Operating System**

Chrome and Safari latest version.
MacOs Sierra 10.12.2

**Comment by gmarziou** [comment]
Would you submit a PR?

**Comment by mfalzetta** [comment]
Hi,
What is a PR?

---
Marlon Falzetta

**Comment by gmarziou** [comment]
a pull request

**Comment by khocef** [comment]
i'm unable to reproduce this issue, the user login seems to be correctly displayed!

**Comment by VictorADS** [comment]
Same for me, it is correctly displaying the login.
Can you provide a screenshot of the problem  ?

**Comment by mfalzetta** [comment]
Hi,
Im working hard in this weekenk. Tomorrow i Will try to reproduce.

Greetings.

---
Marlon Falzetta

**Comment by JulienMrgrd** [comment]
Hi, error reproduced.
It works well in English, but it appears when we select the Brazilian language.

![wrongid](https://cloud.githubusercontent.com/assets/11616517/22745294/597aeb6c-ee20-11e6-943f-a5dcbd3104ef.png)

I'm working on it.

**Comment by pascalgrimaud** [comment]
welcome @JulienMrgrd !

**Comment by mfalzetta** [comment]
Yeaaaahhh!!!!

Thanks for this. Im very worried in to reproduce this error for help
improve jHipster, but im in production upgrade problems and all of my
effort are dedicated in production tasks.

[]'s



*__*

*Marlon Falzetta*

2017-02-08 14:20 GMT-02:00 Pascal Grimaud <notifications@github.com>:
