### ISSUE TITLE
Jhipster prod Profile overwritten CSS style

### ISSUE THREAD

**Issue by nicoguevara** [jhipster/generator-jhipster#5075]
Good morning, I have the inconvenience for some time and I still can not solve it, every time I run the project with the Prod profile, the styles are overwritten, since they are imported into the vendor.scss, but I modify it and also Overrides when running the project.
I appreciate your help and answers.
Regards

**Comment by deepu105** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
