### ISSUE TITLE
Jhipster 4 can not see entities

### ISSUE THREAD

**Issue by alachebbi** [jhipster/generator-jhipster#5076]
I create a project jhipster 4 : 
Monolothic Application
Mongodb
Then i generate an entity using :  yo jhipster:entity NameEntity
But when i excute with ./mvnw and yarn start 
i can not see my entities in the interface .

The link of my project is : 
https://github.com/alachebbi/Jhipster

**Comment by jdubois** [comment]
Yes you need to do `yarn start`

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by suyalcinkaya** [comment]
Had the same problem. Upgrading the project to v.4.0.1 worked for me.

**Comment by jdubois** [comment]
Are you sure you did `yarn start`?? That's basically what upgrading does, but you need to have this running all the time to get live reload

**Comment by alachebbi** [comment]
Yes
