### ISSUE TITLE
jhipster4 even with yarn start entities doesn't work 

### ISSUE THREAD

**Issue by alachebbi** [jhipster/generator-jhipster#5078]
even with yarn start entities doesn't work 
monolothic APP
Mongodb

**Comment by cbornet** [comment]
Seriously, did you read why your previous issue was closed ??

**Comment by atomfrede** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
Please follow the issue template....

**Comment by deepu105** [comment]
@alachebbi if you want our help you need to respect our guidelines. please remember we are doing this for free in our free time

**Comment by alachebbi** [comment]
I don't know what i did :o , i just had a problem and asked you about it. You invite me to create a ticket and ask my question to had a answer.

**Comment by ruddell** [comment]
@alachebbi You need to fill out the template in the New Issue window.  Without that information, we can't help.

The top two lines of the template:
> 
> - Please follow the issue template below for bug reports and feature requests.
> - Tickets opened without any of these informations will be **closed** without any explanation.
>

**Comment by jdubois** [comment]
Yes, create a ticket using the template, we need it to help you

**Comment by alachebbi** [comment]
Ah ok . Sorry because i wasn't know formalities
