### ISSUE TITLE
[JHipster 4] MongoDB entities karma tests are failing

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5085]
The karma test that is generated for MongoDB is wrong, the `_entity-management-detail.component.spec.ts` is doing on line 70:

    spyOn(service, 'find').and.returnValue(Observable.of(new <%= entityClass %>(10)));

So it's expecting an entity with an id of type number, but for MongoDB, it is a UUID. So this doesn't compile.

- There is also probably the same error for Cassandra
- The Travis builds show the error, but still pass!!!

**Comment by jdubois** [comment]
If you have that issue at the moment, the workaround is easy: either put a String there, or even delete the test...

**Comment by ruddell** [comment]
@alachebbi Here's the solution to your issue from earlier

**Comment by pascalgrimaud** [comment]
@jdubois : when there is this kind of problem with Travis, don't hesitate to notice me, so I can put the ticket on my todo list for improving our Travis builds system

**Comment by jdubois** [comment]
Yes thanks @pascalgrimaud but I know you'll get notified as you follow the tickets, anyway

**Comment by pascalgrimaud** [comment]
I was able to made few tests this morning... It seems like the `webpack:build` after the `yo jhipster` phase will exit 0, although there are some errors, so it's not related to mongodb

First, I need to understand this phase: https://github.com/jhipster/generator-jhipster/blob/master/generators/client/index.js#L317-L363

I will made other tests as soon as I can (maybe tonight) and will open an issue if I confirm that

**Comment by jdubois** [comment]
Thanks @pascalgrimaud 
There's no rush as the bugs are fixed, but indeed it would be better to have the build fail when there are test errors :-)
