### ISSUE TITLE
CacheConfiguration.java with ehcache

### ISSUE THREAD

**Issue by svpace** [jhipster/generator-jhipster#5086]
##### **Overview of the issue**

In CacheConfiguration.java generated with ehcache. The "log" and "cacheManager" fields does not seem to have any purpose anymore
 
##### **Motivation for or Use Case**

Clean up unused code

##### **Reproduce the error**

Generate a project using ehcache

##### **Suggest a Fix**

Remove the fields

##### **JHipster Version(s)**

4.0.0

**Comment by gmarziou** [comment]
It seems you are right for ehcache.
However CacheManager is still used by Hazelcast (see [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/_CacheConfiguration.java)), would you consider submitting a pull request?

**Comment by jdubois** [comment]
Yes those need to be cleaned up, but the template code is quite tricky, it depends on a lot of conditions

**Comment by svpace** [comment]
AFAICT the changes in the template seems simple enough. I will try to submit a PR.

**Comment by jdubois** [comment]
Yes, but be careful to test:

- [ ] No cache, no Hazelcast session clustering
- [ ] No cache + Hazelcast session clustering
- [ ] Ehcache, no Hazelcast session clustering
- [ ] Ehcache + Hazelcast session clustering
- [ ] Hazelcast 2nd level cache, no Hazelcast session clustering
- [ ] Hazelcast 2nd level cache + Hazelcast session clustering

That's the annoying part of this code, now you know why I didn't want to touch this :-)

**Comment by jdubois** [comment]
Hang on, this is all wrong!! I removed the minor tag for this.
The ehcache configuration should use the properties from https://jhipster.github.io/common-application-properties/ and this code has been suppressed!! I don't know who did this, but that explains why the class is empty.

**Comment by jdubois** [comment]
Oh and there's also the `@EnableCaching` annotation on this class, but it shouldn't be there by default!
What happened here???

**Comment by jdubois** [comment]
OK I have refactored everything.
As it's quite tricky, I'm a bit afraid to do this, but this needed to be done urgently, as our documentation was false.
