### ISSUE TITLE
yo jhispter wrongly warns for old version of npm

### ISSUE THREAD

**Issue by ecukalla** [jhipster/generator-jhipster#5088]
Greetings and thanks for jhipster 4 release!!!

##### **Overview of the issue**
I have node 7.5.0, while yo jhipster, warns that I should have at least 6.9.0+

    WARNING! Your node version is too old (v7.5.0). You should use at least Node v6.9.0+

<img width="562" alt="screen shot 2017-02-04 at 12 55 47" src="https://cloud.githubusercontent.com/assets/775064/22618608/0f18e336-eae1-11e6-8450-57b7f1744398.png">

##### **Motivation for or Use Case**

It seems to me like a bug, wrongly reporting a minor version of 6.9.0

##### **Reproduce the error**

Just run yo jhipster.

##### **JHipster configuration**

    yo jhipster:info
    Welcome to the JHipster Information Sub-Generator
    
    ##### **JHipster Version(s)**
    
    ```
    /Users/edmond/Documents/ws/smth
    └── (empty)
    
    ```
    
    cat: no such file or directory: .yo-rc.json
    
    ##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
    
    ```yaml
    
    ```
    
    
    ##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
    
    ls: no such file or directory: .jhipster/*.json
    
    ##### **Browsers and Operating System**
    
    java version "1.8.0_101"
    Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
    
    git version 2.10.1 (Apple Git-78)
    
    node: v7.5.0
    
    npm: 4.1.2
    
    bower: 1.8.0
    
    gulp:
    [13:50:01] CLI version 1.2.2
    
    yeoman: 1.8.5
    
    yarn: 0.17.10
    
    Docker version 1.13.0, build 49bf474
    
    docker-compose version 1.10.0, build 4bd6f1a

**Comment by pascalgrimaud** [comment]
@ecukalla : I code it too fast yesterday sorry. The condition should be with == instead of >=

**Comment by alachebbi** [comment]
project doesn't work with jhipster 4.0.1 
error jhipster-core@1.2.8: The engine "node" is incompatible with this module. Expected version ">=6.9.5".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error jhipster 

ERROR! yarn install failed.

**Comment by pascalgrimaud** [comment]
@alachebbi : it's related to https://github.com/jhipster/jhipster-core/commit/8eb2f5e5848b9395bfddba6b496a27764e3e6645
The next version should require nodejs 6.9.0 instead of 6.9.5 currently
Simply use last LTS version of NodeJS
