### ISSUE TITLE
yarn's bug `yarn global add yo` not work

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#5089]
i know it's not jhipster's bug 

##### **Overview of the issue**

I want to use generator-jhipster@4.0.0 and when I run the `yarn global add yo` but yo not work

throw exception `The filename, directory name, or volume label syntax is incorrect.`

my issues https://github.com/yarnpkg/yarn/issues/2630 

> Wrong bin path on Windows 10
> On path variable, the path to global bin executables installed by yarn is set to `C:\Users\username\AppData\Local\Yarn\.bin`  when it should be `C:\Users\username\AppData\Local\Yarn\config\global\node_modules\.bin`

[Wrong bin path on Windows 10 issues ](https://github.com/yarnpkg/yarn/issues/2565)

**Comment by gmarziou** [comment]
Yes it's a known issue on Windows.
I usually delete the scripts created in node installation foder.

As it is not a JHipster issue, I close it.

**Comment by eceraghavulu** [comment]
After 'Yo JHipster' command, I got an error in installing the 'Yarn install' command
