### ISSUE TITLE
Make the security audits optional

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5095]
Since the early days of the project we had Spring Security audits enabled by default.

Lots of people love it, as it gives an audit trail of who did what. This has sometimes been a bit buggy (because the Spring Security implementation was buggy, not our fault!!), but now this works really well.

But there is one thing I don't like about it, since the beginning: it's really bad for performance, because when someone logs in, there is an "insert" statement. Of course, that really depends on what you do:

- For a "business" website, one "insert" statement is nothing, and having a security audit is really important
- But we have more and more big websites using JHipster - the biggest I know is https://www.pwnwin.com/ which has 350,000 users with JHipster (and I know several others having roughly 50,000 users)

And, last but not least, that's not really good when people load test a JHipster application with Gatling.

My current idea would be to add the audits in our JHipster application properties, and make them optional by default. That would solve the issue, but the "audit" page would stay empty until someone enables the audits. That's the easiest solution.

What do you think? Vote 👍 or 👎 on this ticket, or add comments if you have other ideas

**Comment by mraible** [comment]
How would you enable auditing? A simple property or environment variable?

**Comment by jdubois** [comment]
@mraible that would be a Spring Boot property, in https://jhipster.github.io/common-application-properties/

**Comment by jdubois** [comment]
Just tested it: the perf impact is on fact quite low (less than 1% on a normal scenario), so I won't do it now.
