### ISSUE TITLE
Translations for register.* missing when using enableSocialSignIn

### ISSUE THREAD

**Issue by eelcobrolman** [jhipster/generator-jhipster#5102]
##### **Overview of the issue**

When generating the jhipster app (angular2) with the social plugin, i18n translations don't work on the register page (/#/register):

![screen shot 2017-02-04 at 23 41 16](https://cloud.githubusercontent.com/assets/5680995/22622157/842320a4-eb33-11e6-80a9-8a14c5871652.png)

##### **Reproduce the error**

When enabling socialplugin (edit .yo-rc.json, enableSocialSignIn=true, yo jhipster, overwrite all), the translations for all the register.* (i.e. register.title and register.form.button) are missing.

##### **Related issues**

Maybe has something to do with #5066?

##### **JHipster Version(s)**

4.0.1

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.1",
    "baseName": "zhub",
    "packageName": "nl.zhub.app",
    "packageFolder": "nl/zhub/app",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "nl",
    "languages": [
      "nl",
      "en",
      "pl",
      "tr"
    ],
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}
```

##### **Browsers and Operating System**

Both Safari and Chrome.

**Comment by gmarziou** [comment]
In `JhiSocialComponent`, try to add the 'register' location like this:

~~~ts
    ngOnInit() {
        this.languageService.setLocations(['social', 'register']);
~~~

**Comment by eelcobrolman** [comment]
Yes, that fixes it, a created a pull request for it.

**Comment by eelcobrolman** [comment]
Ok, it seems we also need "login" and "home".

"home" due to the fact the you can click on login from the homepage, and otherwise the translations on the home page are missing behind the login-popup.

I will create a PR.
