### ISSUE TITLE
Health Refresh (ng2) should map data in case its 503 error (service down)

### ISSUE THREAD

**Issue by angusoid** [jhipster/generator-jhipster#5110]
##### **Overview of the issue**

When doing health check and there is a certain service down, the server will return 503 with body response. 

Current code (ng2) for refreshing health is not covering that scenario as  shown below.

_health.component.ts_

    refresh() {
        this.updatingHealth = true;

        this.healthService.checkHealth().subscribe(health => {
            this.healthData = this.healthService.transformHealthData(health);
            this.updatingHealth = false;
        });
    }

Example from ng1 client
```
        vm.updatingHealth = true;
            <%=jhiPrefixCapitalized%>HealthService.checkHealth().then(function (response) {
                vm.healthData = <%=jhiPrefixCapitalized%>HealthService.transformHealthData(response);
                vm.updatingHealth = false;
            }, function (response) {
                vm.healthData =  <%=jhiPrefixCapitalized%>HealthService.transformHealthData(response.data);
                vm.updatingHealth = false;
            });
```
##### **Suggest a Fix**

_health.component.ts_
```
    refresh() {
        this.updatingHealth = true;

        this.healthService.checkHealth().subscribe(health => {
            this.healthData = this.healthService.transformHealthData(health);
            this.updatingHealth = false;
        }, error=> {
            if (error.status == 503) {
                this.healthData = this.healthService.transformHealthData(error.json());
                this.updatingHealth = false;
            }
        });
    }
```

##### **JHipster Version(s)**

Latest

**Comment by jdubois** [comment]
Looks like you for the solution -> could you do a PR?

**Comment by angusoid** [comment]
Sure

**Comment by jdubois** [comment]
Thanks for the PR, closing this as it's merged
