### ISSUE TITLE
NetworkError: 401 Unauthorized api/account?cacheBuster=1486313231433

### ISSUE THREAD

**Issue by sonersivri** [jhipster/generator-jhipster#5114]
version 4.0.1
production
Admin user logins and gets error
"NetworkError: 401 Unauthorized - http://52.23.175.251/api/account?cacheBuster=1486313231433"

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
@sonersivri that the second bug report you send us without following the guidelines, please read them
