### ISSUE TITLE
Applicatin do not build itself when I use querydsl library

### ISSUE THREAD

**Issue by appservice** [jhipster/generator-jhipster#5124]
I added to build.gradle file a querydsl library as below:
    compile group: 'com.querydsl', name: 'querydsl-apt', version: '4.1.3'
    compile group: 'com.querydsl', name: 'querydsl-jpa', version: '4.1.3'
and to generate Q files dynamically I added a plugin: 
plugins {
    id "com.ewerk.gradle.plugins.querydsl" version "1.0.7"
}

querydsl {
    querydslSourcesDir = "$buildDir/generated-sources/apt"
    jpa = true
}

When I tried to build this code, a JPAAnnotationProcessor correclty prepared Q  files (according to Entities) but build process crashed.
I received this  message: 
":compileQuerydsl FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Cannot convert path to File. path='net.ltgt.gradle.apt.AptPlugin$_apply_closure1$_closure14@14a13cfe' basedir='D:\priv\mag\magazyn'
"

I userd JHipster 4.0.1
My OS is WIN10

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
And QueryDSL is not provided by JHipster, so that's not our responsibility if there's a bug with it

**Comment by bruno-ayres** [comment]
@appservice I'm with the same error. Did you solve it?

**Comment by nghib** [comment]
@bruno-ayres I reported an issue on https://github.com/tbroyer/gradle-apt-plugin/issues/41

**Comment by appservice** [comment]
I'm downgraded gradle from 3.3 to 3.2 and this fix this issue (query dsl compiled correctly).
