### ISSUE TITLE
mapstruct-1.0.0.Final.jar is loading to library 

### ISSUE THREAD

**Issue by appservice** [jhipster/generator-jhipster#5125]
Despite in build.gradle is loading : 
mapstruct-jdk8 and mapstruct-1.0.0. is excluded from  swagger2, this library is in external libraries too.
Intelij show it as a bug because it loaded mapstruct insteed mapsturct-jdk8 (mapstruct don't have a annotation @Repetable whic is introduces in mapstruck-jdk8)
I checked that that is because mapstruct is a dependency in io.github.jhipster.
After excluding a mapstruct from io.github.jhipster problems dissappere.

**Comment by jdubois** [comment]
Could you please follow the guidelines?

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
