### ISSUE TITLE
Docker 1.13

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#5128]
Docker 1.13 has been released few weeks ago, so I would like to update:
- [X] the documentation, to use the new Docker API
- [X] the docker-compose files: it was implemented at v1! Since the v1, Docker Network has been improved a lot. So we should remove all `links` or `external_links` for using DNS alias instead
- [X] update compose files at https://github.com/jhipster/jhipster-docker-hub

Then, it need to be tested, as I know it's something all of you use in demo, specially with MicroServices.
Are you ok with that ?

**Comment by PierreBesson** [comment]
I was going to add this feature request as well.

I think we should remove all links, external-links, container-name and move to docker-compose v3. This will let us deploy on swarm mode from the docker-compose file (At last !).

That would mean we require docker >= 1.13.

**Comment by jdubois** [comment]
Yes +1 of course
I would also like to be compatible with http://rancher.com/rancher-os/ (they have their own .yml format, and a load balancer to configure), it shouldn't be very hard. And if you want to play with it, I have my own cluster at Ippon :-)

**Comment by pascalgrimaud** [comment]
@PierreBesson : I already finish to remove all links and external_links on my computer and begin to test everything since this morning. I need to remove container name too, as suggested.
As soon as it's ready, I will PR to let you test it

@jdubois : never tested rancher, but let me have a look on this!

**Comment by PierreBesson** [comment]
@pascalgrimaud Amazing ! I will try it on a swarm mode cluster. It really easy to do thanks to docker-machine.
@jdubois, For rancher, if the format differs from docker-compose, this would be a specific sub-generator. I'm looking forward to try it.

**Comment by pascalgrimaud** [comment]
Agree with you @PierreBesson !
@jdubois : should we open a new ticket for Rancher ?

**Comment by jdubois** [comment]
Yes new ticket for Rancher! You should be able to run it on your laptop, but I have "true" cluster at Ippon, so I will be able to do some much better tests.
Just so you know my cunning plan: I'm preparing the new "onboarding" at Ippon for new hires, and I want them to deploy to RancherOS an application that can scale automatically. Sounds like fun :-)

**Comment by pascalgrimaud** [comment]
ahaha sounds very fun!
It's incredible to work for JHipster. After Angular2, there are still so much ideas to improve the project!

**Comment by jdubois** [comment]
Now that the Docker PR are merged, I'm closing this.
