### ISSUE TITLE
Modification to any html file  doesn't load Jhipster4.0.1 and Jhipster 4.0.2

### ISSUE THREAD

**Issue by alachebbi** [jhipster/generator-jhipster#5129]
I did many modification on many Html pages even i deleted the contain of home.component.html and write 
another code but it always load the previous page .

navigator cache : deactivated .
Jhipster monolothic Application . 
Project started with yarn start and ./mvnw
someone can help ???

**Comment by gmarziou** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by gmarziou** [comment]
It's the 3rd issue you open without following guidelines !!!

**Comment by deepu105** [comment]
@alachebbi you keep opening issues without following our guideline (you need to read the bug template and fill out all required info) if you have any issue understanding our issue template let us know and we will help but we cannot help you if you keep opening issues without any proper info.
