### ISSUE TITLE
Build errors in 4.0.2 

### ISSUE THREAD

**Issue by daparthimanu** [jhipster/generator-jhipster#5130]
##### **Overview of the issue**
Upgraded microservices project to 4.0.2, looks like the constants class is missing the properties.

```
[ERROR] /C:/Company/wrp-services/src/main/java/com/Company/wrp/config/ElasticSearchConfiguration.java:[16,8] class ElasticsearchConfiguration is public, should be declared in a file named ElasticsearchConfiguration.java
[ERROR] /C:/Company/wrp-services/src/main/java/com/Company/wrp/config/apidoc/SwaggerConfiguration.java:[29,19] cannot find symbol
[ERROR] symbol:   variable SPRING_PROFILE_SWAGGER
[ERROR] location: class com.Company.wrp.config.Constants
[ERROR] /C:/Company/wrp-services/src/main/java/com/Company/wrp/config/apidoc/PageableParameterBuilderPlugin.java:[30,19] cannot find symbol
[ERROR] symbol:   variable SPRING_PROFILE_SWAGGER
[ERROR] location: class com.Company.wrp.config.Constants
[ERROR] /C:/Company/wrp-services/src/main/java/com/Company/wrp/config/liquibase/AsyncSpringLiquibase.java:[45,43] cannot find symbol
[ERROR] symbol:   variable SPRING_PROFILE_NO_LIQUIBASE
[ERROR] location: class com.Company.wrp.config.Constants
[ERROR] /C:/Company/wrp-services/src/main/java/com/Company/wrp/config/liquibase/AsyncSpringLiquibase.java:[46,46] cannot find symbol
[ERROR] symbol:   variable SPRING_PROFILE_DEVELOPMENT
[ERROR] location: class com.Company.wrp.config.Constants
[ERROR] /C:/Company/wrp-services/src/main/java/com/Company/wrp/config/liquibase/AsyncSpringLiquibase.java:[46,84] cannot find symbol
[ERROR] symbol:   variable SPRING_PROFILE_HEROKU
[ERROR] location: class com.Company.wrp.config.Constants
```
##### **Reproduce the error**
Upgrgrade to 4.0.2 

##### **Suggest a Fix**
Add properties to the Constants.java class and change the class name to "Elastic**S**earchConfiguration" instead of ElasticsearchConfiguration.

##### **JHipster Version(s)**
4.0.2

##### **Browsers and Operating System**
windows 7 64 bit

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
We have renamed ElasticSearchConfiguration to ElasticsearchConfiguration but that really depend on your versions, and on what you did, so I can only give you this hint. Next time, please follow the guidelines, to have more help!

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
