### ISSUE TITLE
Remove the Spring Boot remote shell

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5136]
I know this was added by @cbornet and that he loved it, but it looks like the Spring Boot remote shell (documented at https://jhipster.github.io/profiles/ ) is going to be removed from Spring Boot, see http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-remote-shell.html
So we should remove it...

**Comment by cbornet** [comment]
Yes, this is sad...

**Comment by deepu105** [comment]
Dont forget the docs :)


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Yes it's also done, look at the commits :-)

**Comment by deepu105** [comment]
Awesome

Thanks & regards,
Deepu
