### ISSUE TITLE
RancherOS support

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#5138]
Following the comments:
- https://github.com/jhipster/generator-jhipster/issues/5128#issuecomment-277940736
- https://github.com/jhipster/generator-jhipster/issues/5128#issuecomment-278147543
- https://github.com/jhipster/generator-jhipster/issues/4955#issuecomment-278143008

It would be cool to support http://rancher.com/rancher-os/ 
The documentation: https://docs.rancher.com/rancher/v1.4/en/

@PierreBesson suggested a new sub generator, but as I never use rancher, I let you guys take the lead on this.

**Comment by stevehouel** [comment]
I already start this new sub generator. I will send PR asap.

@jdubois : I will test it on my own rancher cluster (built locally). I will keep u in touch if you want to test it on Ippon cluster.

**Comment by PierreBesson** [comment]
@stevehouel very cool ! The only thing that is worrying me is that the rancher-compose syntax might have incompatibility with docker-compose but you might not be able to do it by extracting the data from the current docker-compose files but like we did for the docker-compose subgen. Please have a careful look at both the docker-compose and kubernetes subgen and then choose the best approach. Good luck !

**Comment by stevehouel** [comment]
Yes I already check that and I will use docker-compose files from his dedicated subgen which looks much better, regarding Rancher compose file it is mainly used to define scale option or healthchecks so not a very big deal.

**Comment by stevehouel** [comment]
Subgen will also have a prompt to choose between using rancher loadbalancer or not
