### ISSUE TITLE
Bug Translate

### ISSUE THREAD

**Issue by Jpmmdf** [jhipster/generator-jhipster#5141]
When I submit a request with invalid values ​​the application can not return the error.

Chrome

The email is incorrect.

![captura de tela 2017-02-07 as 22 25 26 2](https://cloud.githubusercontent.com/assets/8302424/22717886/acec51ce-ed84-11e6-9f35-d89129dd328d.png)

**Comment by jdubois** [comment]
I'm sure you found something interesting, but if you don't bother following the guidelines I won't spend time on this.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
