### ISSUE TITLE
Support for java.util.UUID as @Id Column in SQL Databases

### ISSUE THREAD

**Issue by DanielSBFranco** [jhipster/generator-jhipster#5147]
##### **Overview of the issue**

Feature Request: Allow the use of java.util.UUID as ID with SQL Databases

##### **Motivation for or Use Case**

It may not be as fast as Long, but can be generated safely outside the database, being an interesting option for microservices using separate databases

With Spring Data included in Spring Boot 1.5.1, both Spring Data JPA and Spring Data Elasticsearch support Repositories with java.util.UUID as ID.  Also Hibernate v5.2.4 (used in JHipster 4) supports @GeneratedValue without the need to define any custom generator

I tested a monolith application using JHipster v4.0.0 with PostgreSQL, using H2 as test database, and after upgrading to Spring Boot 1.5.1, no @UserType or any configuration of the sort was needed, setting the column type as "uuid" in liquibase was enough

I don't know if the other databases supported by JHipster also support uuid as a column type, but if the user wants to use UUID even if the selected database doesn't support it, the key could be a varchar(36) or varchar(32) (UUID without dashes)

##### **Related issues**

If such feature is added, it's better to wait until #5045 is merged

##### **JHipster Version(s)**

v4

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Here some old links about this feature request:
https://github.com/jhipster/generator-jhipster/issues/3060
https://github.com/jhipster/generator-jhipster/issues/1235

I don't know if someone tried to make it as module or not

**Comment by jdubois** [comment]
I'm really not convinced by this: lots of work, probably bad performance, all because people don't want to use a correct business key or secure correctly their API (and both are bad reasons for me).

This is also going to add a lot of maintenance cost, as we have those IDs everywhere, so even if you do a PR for this, I'm really not keen on merging it, as the team will then need to maintain it.

So I'm not *totally* against this, but we clearly have higher priority issues, and I'd rather not spend all that time on this at the moment.

This is also the third time someone comes with this: I understand some people want this, but then we just keep on repeating the same things over again, and that's just boring for me...

**Comment by deepu105** [comment]
yes its a lot of work compared to benefit

**Comment by pascalgrimaud** [comment]
@DanielSBFranco : I think you can help @amitjindal if he already started this feature as a module (see his https://github.com/jhipster/generator-jhipster/issues/3060#issuecomment-273972118)
If not, you are free to start one

**Comment by amitjindal** [comment]
@DanielSBFranco : I added my code. Its not extensively tested but we have been using this internally for almost 10 months with minimal problems. See here: https://github.com/amitjindal/generator-jhipster-postgresuuid-converter

In next few days I will polish this and submit this to NPM repository.

**Comment by DanielSBFranco** [comment]
That's great! 

I took a quick look at your code, and it seems to do the same I was doing manually, except for the annotations above the id field in the entities
With hibernate version in spring boot 1.5.1 (in use by latest JHipster version) it works with @Id and @GeneratedValue no need for generator and @Type, although I was using UUID v4 while testing. This way it also worked in H2

**Comment by amitjindal** [comment]
@DanielSBFranco  My pleasure. If you tell me the changes, I would add and upload.
The code definitely needs cleaning because we just did this quickly.

**Comment by DanielSBFranco** [comment]
In the entitities, try declaring id as

@Id
@GeneratedValue
private UUID id;

But this way I don't know what kind of UUID will be generated

**Comment by amitjindal** [comment]
@DanielSBFranco Just released latest version with change as you requested. Please take a look.
