### ISSUE TITLE
Release 4.0.2   run product

### ISSUE THREAD

**Issue by jmying** [jhipster/generator-jhipster#5151]
./mvnw -Pprod clean package

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:install-node-and-yarn (install node and yarn) on project jeremy: Could not
extract the Yarn archive: Could not extract archive: 'C:\Users\xxx\.m2\repository\com\github\eirslett\yarn\0.19.1\yarn-0.19.1.\yarn-v0.19.1.tar.gz': EOF
Exception -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by jdubois** [comment]
Delete your .m2 repo and download again....
