### ISSUE TITLE
Install JHipster: yarn global add generator-jhipster

### ISSUE THREAD

**Issue by sinoryan** [jhipster/generator-jhipster#5153]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by sinoryan** [comment]
cmd  exec this command:
D:\Program Files (x86)\Yarn\bin>yarn global add generator-jhipster
yarn global v0.19.1
warning No license field
[1/4] Resolving packages...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/lodash.reduce: connect ETIMEDOUT 104.16.63.173:443".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\yf\\AppData\\Local\\Yarn\\config\\global\\yarn-error.log".

**Comment by jdubois** [comment]
I don't understand what you mean?
