### ISSUE TITLE
LocalTime in entity generator 

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#5163]
I am using LocalTime type in jhipster to submit working hours.
Would it be interesting for you in the entity generator ?

I started here : https://github.com/ctamisier/generator-jhipster/tree/localtime
it's 90% done for angular 1.
I still need to do the java integration tests ,some small fixes in the UI, refactoring.
It's using `uib-timepicker` (already in the project dependencies from angular UI)

Let me know if this can be interesting to be merged ? and in this case I can continue and apply it to angular 2.

**Comment by jdubois** [comment]
That could be interesting, but I'm really worried about the Angular 2 part - we already don't have a good solution for ZonedDateTime (see #5006 ) and we can't add new "date" types unless we have something clean here.

**Comment by cbornet** [comment]
Note that there is no swagger type/format to represent a time and it will have to be mapped to String

**Comment by jdubois** [comment]
So that's too complex for us at the moment.
