### ISSUE TITLE
[Enhancement] - React & Jhipster

### ISSUE THREAD

**Issue by ramzimaalej** [jhipster/generator-jhipster#5166]
I'm currently thinking about using React with Jhipster and I'm wondering how much effort do you think it will take to replace Angular2 with React?

**Comment by jdubois** [comment]
You need to recode the whole front end... We just did it for Angular 2, it took the team a full year, and it's not finished yet.

**Comment by gmarziou** [comment]
For sure, it would be an ambitious project.

It could be easier if you selected only a smaller subset of the many options we currently support for angular. Something like only one way to authenticate, one kind of pagination, no internationalization and selecting a widget library that could provide menu, grid, notifications, form valdiation out of the box.

**Comment by pascalgrimaud** [comment]
You can look this projzct: https://github.com/hipster-labs/generator-jhipster-react
Not sure if it's still in dev, but I think you can help if you want react

**Comment by deepu105** [comment]
@ramzimaalej I already started https://github.com/hipster-labs/generator-jhipster-react for that but didnt have enough time between ng2 migration and my real work. I'm starting a React project for my real work and hence I intent to finish the jhipster-react generator soon. If you are interested you can join the development. I'll commit a base version within next week so that there is something to start there.

**Comment by Julienng** [comment]
Do you plan to use `redux` with `react` ?

**Comment by deepu105** [comment]
Yes

**Comment by deepu105** [comment]
here are the dependencies im working on
```
"dependencies": {
    "axios": "^0.15.3",
    "counterpart": "^0.17.2",
    "deep-equal": "^1.0.1",
    "flexboxgrid": "^6.3.1",
    "lodash.debounce": "^4.0.8",
    "material-ui": "^0.16.7",
    "react": "^15.3.1",
    "react-dom": "^15.3.1",
    "react-interpolate-component": "^0.10.0",
    "react-redux": "^5.0.2",
    "react-router": "^3.0.2",
    "react-router-redux": "^4.0.2",
    "react-tap-event-plugin": "^2.0.1",
    "react-translate-component": "^0.13.2",
    "redux": "^3.5.2"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.17.0",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.5",
    "babel-plugin-module-alias": "^1.2.0",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-1": "^6.22.0",
    "connect-history-api-fallback": "^1.2.0",
    "cross-env": "^3.1.4",
    "css-loader": "^0.26.1",
    "enzyme": "^2.2.0",
    "eslint": "^3.1.1",
    "eslint-config-airbnb": "^14.0.0",
    "eslint-plugin-ava": "^4.0.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-react": "^6.9.0",
    "expect": "^1.16.0",
    "express": "^4.13.4",
    "extract-text-webpack-plugin": "^1.0.1",
    "html-webpack-plugin": "^2.15.0",
    "http-proxy-middleware": "^0.17.3",
    "jsdom-global": "^2.1.1",
    "json-loader": "^0.5.4",
    "mocha": "^3.2.0",
    "node-sass": "4.5.0",
    "postcss-loader": "1.2.2",
    "react-addons-test-utils": "^15.0.0",
    "redux-devtools": "^3.2.0",
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-devtools-log-monitor": "^1.0.9",
    "sass-loader": "5.0.1",
    "stripcomment-loader": "^0.1.0",
    "style-loader": "^0.13.1",
    "webpack": "^2.2.1",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-hot-middleware": "^2.10.0"
  }
```

**Comment by ramzimaalej** [comment]
@deepu105 which scenario are you focusing on first? I will try to take a look on your branch.
