### ISSUE TITLE
Kubernetes generator generates YAML file w/ `imagePullPolicy: IfNotPresent`

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#5172]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

Kubernetes generator currently generates YAML file with `imagePullPolicy: IfNotPresent`. This may be great for the first deployment w/o having to pull from a remote registry. However, if you rebuild the image, it won't automatically be repulled from the registry either.

If we remove this - then every time you redeploy, it'll try to pull the latest image. This is also not desired in production.

The better practice is to tag the image w/ a version (potentially githash, or a build number, but not the artifact version), and deploy the tagged images instead.

##### **Motivation for or Use Case**

To avoid unnecessary image pulls, but also don't want to pull for latest image every time.

##### **Reproduce the error**

`yo jhipster:kubernetes`

##### **Related issues**
N/A

##### **Suggest a Fix**

Tag the image w/ a version (potentially githash, or a build number, but not the artifact version), and deploy the tagged images instead.

##### **JHipster Version(s)**

v4.0.2

##### **JHipster configuration**
N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Irrelevant

##### **Browsers and Operating System**
All browsers/OS.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Thanks @saturnism for reviewing our code!

For this ticket, I'm working on it:
- adding a new question to ask the tag
- remove imagePullPolicy

**Comment by jdubois** [comment]
@pascalgrimaud I see you referenced this in a closed PR, should we also close this ticket?

**Comment by pascalgrimaud** [comment]
@jdubois : I proposed a very simple solution which resolved this ticket but @PierreBesson wasn't agree with my solution. We discussed about it but I dont know if Pierre worked on it since the last time we met.

**Comment by pascalgrimaud** [comment]
@jdubois : in details, my solution added a new question to the user, and asked him which tag hz wants:
- if he let the default answer: the generator will use latest, exactly same as currently
- if he choose to put a specific tag, for example v1.2.3, it would be the same tag for all microservices, but no repull from Docker Hub if the image already exists, as suggested by Ray. Then, for me, the user can edit these configuration, as it's hard to code something to ask every version for every microservices

**Comment by PierreBesson** [comment]
I agree with Pascal that it's maybe better for the users to modify the version themselves. I had an idea to setup the docker plugin to add the maven version as tag and then read the pom in the subgen to set the correct version. I think it would work.
But I don't have time to work on this currently because I'm on vacation.

**Comment by jdubois** [comment]
This has been opened for way too long, and our list of tickets is growing too big - I'm closing this as I understand there was some kind of solution, and as no work is being done here.
