### ISSUE TITLE
Kubernetes descriptors to use dynamic volume provisioning

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#5173]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

Currently, databases are mounting volumes from EmptyDir. This is convenient to get started with, but data will not survive restarts. Production deployment needs to be reconfigured.

##### **Motivation for or Use Case**

Make sure there is a good production deployment path.

##### **Reproduce the error**

`yo jhipster:kubernetes`

##### **Related issues**
N/A

##### **Suggest a Fix**
Use PVC & depend on dynamic volume provisioning (require StorageClass yaml)

See http://blog.kubernetes.io/2016/10/dynamic-provisioning-and-storage-in-kubernetes.html

##### **JHipster Version(s)**

v4.0.2

##### **JHipster configuration**
N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Irrelevant

##### **Browsers and Operating System**
All browsers/OS.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@PierreBesson : as you already use volumes for registry and consul, could you have a look to this ticket plz ?

**Comment by PierreBesson** [comment]
Yes of course.

**Comment by jdubois** [comment]
Hi guys, this has been opened for a long time - @PierreBesson or @saturnism would you be ready to work on this? Otherwise, unfortunately, I will close this, as we have too many bugs opened at the moment

**Comment by xetys** [comment]
I think I can cover this

**Comment by deepu105** [comment]
@xetys if this is included in #5603 please close this

**Comment by jdubois** [comment]
Looks like this is being done in #5603 and this has been opened for way too long, so I'm closing this
