### ISSUE TITLE
Kubernetes generator should expose Monolith and API gateway on port 80, or use Ingress

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#5174]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

When the service is created for the API gateway, it's exposed via port 8080.

##### **Motivation for or Use Case**
Usually users expect the web frontend to be on port 80.

##### **Reproduce the error**
`yo jhipster:kubernetes`

##### **Related issues**
N/A

##### **Suggest a Fix**
In the service YAML, add both port and targetPort, so that port = 80, and targetPort = 8080.
Alternatively, add an Ingress yaml to create a HTTP ingress.

##### **JHipster Version(s)**
v4.0.2

##### **JHipster configuration**
N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Irrelevant

##### **Browsers and Operating System**
Irrelevant

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
I think we should do both : exposing on port 80 as default and add a question for ingress.

**Comment by pascalgrimaud** [comment]
@PierreBesson : It's already done for port 80 on my local, I'm currently testing it to confirm it works well. I will let you add ingress if you want

**Comment by deepu105** [comment]
Guys any update on this?

**Comment by pascalgrimaud** [comment]
@deepu105 : it was already done for port 80 (instead of ingress) in this PR https://github.com/jhipster/generator-jhipster/pull/5210 (which resolved 2 tickets)
but was closed because of this comment https://github.com/jhipster/generator-jhipster/issues/5172#issuecomment-297818067

**Comment by jdubois** [comment]
I'm not totally sure this is done, but this has been stucked for a very long time, with no work being done, so I'm closing this.

**Comment by xetys** [comment]
I would suggest adding an ingress question. I'm always copy-pasting that from other sources, as we don't provide that option.

Is it ok, if I re-open that with that update?

**Comment by pascalgrimaud** [comment]
I'm ok, if someone works on it
