### ISSUE TITLE
Created Entity not displayed under entity menu in Angular 2

### ISSUE THREAD

**Issue by pkmyl** [jhipster/generator-jhipster#5182]
Overview of the issue

Unable to view the created entities under entity menu. But the generated codes are available in the respected area. There is no error while creating the entity as well the application startup.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by ysf08** [comment]
Many people having this issue but no answers at all
