### ISSUE TITLE
Update the generated travis.yml to support Angular 2

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5185]
With JHipster 4, we still generate the same `travis.yml` as with JHipster 3.

We should:

- Support Angular 2
- Support Webpack
- Update some dependencies

**Comment by pascalgrimaud** [comment]
I take the ticket and will work on it

**Comment by jdubois** [comment]
Hang on, I'm also working on it :-)

**Comment by jdubois** [comment]
I'll push this to a branch so you can check it

**Comment by pascalgrimaud** [comment]
oh ok, but when I say "I will work", it was tonight or tomorrow morning

**Comment by jdubois** [comment]
In fact I'm going to push it directly, it's already better than the current one -> I'll link my commit to this ticket, @pascalgrimaud if you can have a look, I'll let you close the ticket if that's fine for you

**Comment by jdubois** [comment]
Commit is at https://github.com/jhipster/generator-jhipster/commit/f7d7de8ac546835a47920130c5512eb99f987ced

**Comment by pascalgrimaud** [comment]
Looking on my phone, it seems ok, excepting the install of yo (no need).
I ll try to test it tonight or tomorrow morning and then close this ticket

**Comment by pascalgrimaud** [comment]
It works perfectly!
