### ISSUE TITLE
Wrong questions amount

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#5187]
##### **Overview of the issue**

When generating an application, the generator shows 15 questions, but I only passed 14.

##### **Reproduce the error**

![capture](https://cloud.githubusercontent.com/assets/7104443/22886104/1509a3ae-f205-11e6-9483-976ffbbb86b6.PNG)

##### **JHipster Version(s)**

4.0.3 (didn't check older versions)

##### **Browsers and Operating System**

Microsoft Windows [Version 10.0.14393]

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
We know this minor and esthetic issue, as the generator can't know in advance the global number of questions.
I tried to fix it but it was a hack: https://github.com/jhipster/generator-jhipster/pull/3632 so we didn't merge it.

So don't hesitate if you have a proper solution :)

**Comment by delverdev** [comment]
I don't know the full tree of questions, but seems like their amount depends on the `type` of application. So the amount could depend on the type (the amount may be hidden in the first question). Otherwise subparagraphs (like in language question). If the amount depends on many factors, then I would remove it at all, because it may confuse ("14/15? something broke?")

**Comment by jdubois** [comment]
Indeed the number of questions depends on what you select, so they vary... So we can't have an exact number at the beginning. But that number is supposed to change: the total number of question should adapt, like you have (1/15) at the beginning but you could finish with (10/10) at the end.
Maybe we could put some kind of progress bar instead, but that's probably going to cause more issues than some simple text.
I've known this for a long time, but we haven't got a good solution.

**Comment by delverdev** [comment]
> you have (1/15) at the beginning but you could finish with (10/10) at the end

yes, but without re-rendering, `1/15` will not become `1/10`.  
As idea: print something like "questions remained: N".

**Comment by deepu105** [comment]
I tried multiple times to get it working but it was all a hack and was very
difficult to maintain so ill rather leave it as it is or remove the total
and print only current number as getting the correct total is impossible as
we would never know what you are going to select so it will be wrong for
one or the other case

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
Yes we have more than 30 opened issues at the moment, this is very minor, this why I'm closing this.
