### ISSUE TITLE
Document & improve the CI-CD sub-generator

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5188]
The new ci-cd sub-generator from @cbornet is great!!

We need 2 things to make it awesome:

- Support Angular 2 (I'll have a look)
- Document it on the website (if it's not documented it doesn't exist)

**Comment by jdubois** [comment]
And we also need to move our Travis configuration there (it's currently generated in the root folder for every project)

**Comment by jdubois** [comment]
- not sure the gulp & webpack build run OK, I see lots of errors & strange things in the Gitlab CI file
- the Heroku key is stored directly -> that's not good, if you push your code on a public repo everybody sees your key

**Comment by jdubois** [comment]
For Travis, I managed to have it deploy to Heroku automatically. You need to have the `HEROKU_API_KEY` set up in the env variables, and then the end of the conf in `.travis.yml` is:

```
 - yarn global add yo
 - wget -qO- https://toolbelt.heroku.com/install.sh | sh
 - /usr/local/heroku/bin/heroku plugins:install heroku-cli-deploy
install:
 - yarn install
script:
 - ./mvnw clean test
 - yarn test
 - ./mvnw package -Pprod -DskipTests
 - /usr/local/heroku/bin/heroku deploy:jar target/jhipster-0.0.1-SNAPSHOT.war --app <heroku_app_name>
```

**Comment by cbornet** [comment]
On jenkins I think we could use the Credentials plugin to hide the key. I wanted to do it, just didn't get the time :smile: 
Same for the doc... I can do it next week or do you want to do it ?

**Comment by jdubois** [comment]
@cbornet I won't have time to do it.... I have lots of "day work", and this is huge.
I'll try to make another ticket everything, but my idea is that:

- We should remove Jenkins and Travis by default in the main generator
- Your sub-generator should be "composed" in the main generator, and add a new question at the end: "which continuous integration system do you want to use?" With checkboxes (you could select several) for Jenkins, Travis, GitLab, CircleCI (I don't know that last one, so it's less important for me).
- Not sure if we could then deploy automatically to Heroku (and others of course), as the Heroku sub-generator will not have run already. But if that's possible, then have a new question if one CI system is selected: "Do you want to deploy your application automatically to a cloud provider?" With a checkbox having just Heroku for the moment
- As we are beginning to have tons of options, and to keep things simple: only support Yarn and not NPM (even if you have NPM on your system, you would build with Yarn - it's much faster and should work the same), and only support Angular 2 / Webpack as AngularJS 1 will disappear anyway

Sounds good to you?

**Comment by cbornet** [comment]
Yes a lot of work indeed.
Ok to attach it to the main gen. The question about the deployment can be asked when you run the heroku subgen.
And of course we need to support Angular before ptomoting it !

**Comment by jdubois** [comment]
I don't understand your last point -> as long as you support Yarn, then you have WebPack, and then you have Angular 2. It's in fact easier than AngularJS 1, and as Yarn is faster and has less errors (as it uses checksums), it should be much better.

**Comment by cbornet** [comment]
I said Angular as in Itsjustangular so I think we agree :smile:

**Comment by pascalgrimaud** [comment]
@jdubois @cbornet : I can help. Just let me know if you decide to work on this, so we won't work on the same thing.
I will do little PR:
- move Travis file first -> I'm starting it right now (and probably finish it tonight)
- remove the condition on angular2 and improve files:
    - Jenkinsfile
    - Gitlab CI
    - Circle CI
- documentation

**Comment by cbornet** [comment]
@pascalgrimaud please do !

**Comment by kaidohallik** [comment]
As I studied and tested and got working Jenkinsfile in connection with #5177 then I wrote down generator changes needed to get Jenkins with JHipster generated Jenkinsfile green with Angular 2, yarn and gradle: https://github.com/kaidohallik/generator-jhipster/commit/f6422f25cb36d21bc21f67d63d5ed0d01b2ec074

My setup what worked:
* Jenkins 2.45
* Docker 1.12.6
* Centos 7.3

Tried also with yarn_install instead of npmInstall, but no success.

Maybe some piece of this information is useful for you.

**Comment by pascalgrimaud** [comment]
thanks @kaidohallik 
So do you mean, including your changes in profile_prod.gradle and build.gradle, we still can't use `./gradlew yarn_install` ?

**Comment by pascalgrimaud** [comment]
@ruddell : seeing your comment https://github.com/jhipster/generator-jhipster/issues/5177#issuecomment-279246157 about this error:
```
ERROR in ./src/main/webapp/content/images/hipster.png
Module build failed: Error: spawn /home/vagrant/projects/jhipster-gradle/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./~/css-loader!./src/main/webapp/app/home/home.css 6:307-350
 @ ./src/main/webapp/app/home/home.css
 @ ./src/main/webapp/app/home/home.component.ts
 @ ./src/main/webapp/app/home/index.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
```

Sometimes, I encounter this error, testing with Jenkins, sometimes not. I think there is something to do here. Can you do a PR ?

**Comment by kaidohallik** [comment]
My testing result related to pngquant error.

With **gradle node plugin version 1.1.1** I can't reproduce this pngquant error if there is no previous build errors happened with `yarn_install`, the following has never failed so far: `./gradlew yarn_install -PnodeInstall`

I can constantly reproduce pngquant error in this way:
* at first doing `yarn_install` with **gradle node plugin version 1.0.1**: `./gradlew yarn_install -PnodeInstall`
this constantly failes with `throw new Error('Version ' + version + ' is not valid semver');`
* after that changing **gradle node plugin version to 1.1.1** and rerun `./gradlew yarn_install -PnodeInstall`
this constantly failes with pngquant error
* after applying @ruddell patch build successful if rerun `./gradlew yarn_install -PnodeInstall`
* then after removing @ruddell patch build still successful if rerun `./gradlew yarn_install -PnodeInstall`

So in my case seems that pngquant error appears if there is some problem in node_modules folder and seems that @ruddell patch cures this node_modules corruption problem.

**Comment by pascalgrimaud** [comment]
I will start to work on the documentation tomorrow morning: https://jhipster.github.io/setting-up-ci/
