### ISSUE TITLE
Backport Webpack+Yarn build system to Angular 1

### ISSUE THREAD

**Issue by svpace** [jhipster/generator-jhipster#5202]
##### **Overview of the issue**

Backport Webpack+Yarn build system to Angular 1

##### **Motivation for or Use Case**

This would allow users of the Angular 1 client to take advantage of the new build tools available for Angular 2 and facilitate the migration path.
  
##### **Reproduce the error**

Feature request

##### **Suggest a Fix**

Although I understand that new options should not be added without careful consideration, I believe that it would be the best option here.  
 
##### **JHipster Version(s)**

1.4

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
No, really, that's too much work for something that will disappear in the future. Even if somebody wanted to code this, I wouldn't take the time to test everything, document again... I don't think you realize the amount of work here.

**Comment by svpace** [comment]
I believe that It would be a lot of work, to say the least. Nonetheless Angular 1 projects can really benefit from typescript/webpack and I was under the impression that Angular 1 would remain a first class citizen within JHipster for the foreseeable future and therefore convergence with Angular 2 seemed to me like a good thing. On the other hand If Angular 1 is going away soon, I agree with you, it is too much work for the benefit.
