### ISSUE TITLE
Move the development ribbon to bottom left of the page

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#5211]
Hey guys I kind of feel that the development ribbon at top left is aesthetically  a bit annoying so I actually move them to bottom left corner for my apps. Should we do that for the default app what do you guys prefer @jhipster/developers

**Comment by gmarziou** [comment]
bottom-right seems a good place at least for left to right languages.

**Comment by jdubois** [comment]
I prefer to have it on the top, as you see it straight away, and usually the "GitHub ribbons" are on the top.
At the moment we have 34 opened tickets, don't waste time on this, nobody ever complained about it

**Comment by JulienMrgrd** [comment]
Why not remove the ribbon and replace the Hipster icon ?

By example (sorry for my low level in design)
![workinprogresshipster](https://cloud.githubusercontent.com/assets/11616517/22970729/7f3e7fc8-f373-11e6-8600-e36a25ab7114.png)

**Comment by jdubois** [comment]
:-)
I'm closing this as we really more important issues at the moment
