### ISSUE TITLE
Move the clientFramework question into client sub generator

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#5212]
Today the `clientFramework` question is triggered from the main app generator but ideally this should be moved to the `client` generator. I had this here as I started off with 2 client sub gens but since we merged them into a single one its better to move the question there so that its more modular and the modules which would replace angular with react/vue etc can benefit as well

I'll do this later this week. Please note that this will change the position of the question. Doc site needs to be updated as well

**Comment by deepu105** [comment]
@jdubois @jhipster/developers please note that the position of the question has changed with this. I'm doing a PR to update docs as well

**Comment by jdubois** [comment]
yes I just saw it, no problem
