### ISSUE TITLE
Social Login Problem 4.0.3

### ISSUE THREAD

**Issue by carpanese** [jhipster/generator-jhipster#5214]
When trying to connect with facebook, it displays the following error:

`2017-02-15 10:44:42.501 ERROR 707 --- [bio-8080-exec-5] b.com.digidev.web.rest.SocialController : Exception creating social user: 

org.springframework.social.UncategorizedApiException: (#12) bio field is deprecated for versions v2.8 and higher`

Version: 4.0.3

**Comment by jdubois** [comment]
Isn't this an issue with Spring Social instead?

**Comment by jdubois** [comment]
Yes it's a Spring Social issue, see:

http://stackoverflow.com/questions/39890885/error-message-is-12-bio-field-is-deprecated-for-versions-v2-8-and-higher

And there's even a JHipster workaround in the answers!!!

**Comment by vw98075** [comment]
The problem can be resolved with the latest Spring Social Facebook, 3.0.0M1.
