### ISSUE TITLE
How can i configure API_URL in a monolitic app?

### ISSUE THREAD

**Issue by lvffilho** [jhipster/generator-jhipster#5220]
I created a Monolithic app with the new version (4.0) then i´m trying to separeting backend from frontend.
I start backend with 'gradle' using port 8080. And trying to start frontend with 'yarn start' using port 9000.
But jhipster uses relative URL to access API. Where can i configure API_URL in frontend?

**Comment by jdubois** [comment]
I'm sorry but I don't understand what you mean... You don't seem to have a bug, so the guidelines say you should use StackOverflow for a usage question, please post your question there.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
