### ISSUE TITLE
Gradle build displays a warning message.

### ISSUE THREAD

**Issue by javadev** [jhipster/generator-jhipster#5229]
The plugin id 'spring-boot' is deprecated. Please use 'org.springframework.boot' instead.

**Comment by atomfrede** [comment]
Please follow our i[ssue guidelines](https://github.com/jhipster/generator-jhipster/issues/new?body=*%20**Overview%20of%20the%20request**%0A%0A%3C!--%20what%20is%20the%20query%20or%20request%20--%3E%0A%0A*%20**Motivation%20for%20or%20Use%20Case**%20%0A%0A%3C!--%20explain%20why%20this%20is%20a%20required%20for%20you%20--%3E%0A%0A%0A*%20**Browsers%20and%20Operating%20System**%20%0A%0A%3C!--%20is%20this%20a%20problem%20with%20all%20browsers%20or%20only%20IE8%3F%20--%3E%0A%0A%0A*%20**Related%20issues**%20%0A%0A%3C!--%20has%20a%20similar%20issue%20been%20reported%20before%3F%20--%3E%0A%0A*%20**Suggest%20a%20Fix**%20%0A%0A%3C!--%20if%20you%20can%27t%20fix%20this%20yourself%2C%20perhaps%20you%20can%20point%20to%20what%20might%20be%0A%20%20causing%20the%20problem%20(line%20of%20code%20or%20commit)%20--%3E). I am sure you are using an older jhipster version as we are using the new plugin already: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/_build.gradle#L30
