### ISSUE TITLE
ElasticSearch is not consistent with the database

### ISSUE THREAD

**Issue by ddidier** [jhipster/generator-jhipster#5231]
##### **Overview of the issue**

The generated code seems to consider that ElasticSearch supports 2PC which it doesn't.

##### **Motivation for or Use Case**

I want my data in the DB to be consistent with my data in the index.

##### **Reproduce the error**

Create an entity A referencing an entity B with a mandatory FK in the DB. Save an entity A without a B: A won't be created because of the constraint but since the error is raised at commit time, the data is already saved into the index.

##### **Related issues**

n/a

##### **Suggest a Fix**

This is quite a big issue so there is no simple fix for that IMHO. The simplest one would be to just document this fact but that's not satisfying to say the least. Otherwise, one could use application events stored in the DB in the same transaction then a scheduled process would poll the DB and index the associated data. A third way would be to use a JMS queue involved in a 2PC with the DB if performance is not critical.

##### **JHipster Version(s)**

4.0.3

##### **JHipster configuration**

PostgreSQL

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

n/a

**Comment by jdubois** [comment]
Of course it isn't.
That's just the way Elasticsearch works: it is not a database, and it is not transactional.
We never said we "solved" this, we just configure the tools, that's all.
Many people use the Elasticsearch re-index module (in our marketplace) to get around this.

**Comment by ddidier** [comment]
I think you should actually document it somewhere as I suspect a lot of people don't know that

**Comment by jdubois** [comment]
We have a policy that says we don't document underlying technologies. Like Spring, Angular...
But yes we could add this on the "using Elasticsearch" page.

**Comment by ddidier** [comment]
that's not documenting the technology per se but the usage of it, thanks

**Comment by jdubois** [comment]
Yes, and I've already seen many, many "architects" and "experts" that tell that Elasticsearch can be used as a database... We need to put this clearly.

**Comment by jdubois** [comment]
Done!
