### ISSUE TITLE
Jhipster 4 + Angular 2 Problem in War Deploy.

### ISSUE THREAD

**Issue by carpanese** [jhipster/generator-jhipster#5235]
Hello.

I made the application packaging to deploy to tomcat however, accessing a metrics screen, do I have the following problem?
![error](https://cloud.githubusercontent.com/assets/3074947/23046342/16998102-f490-11e6-91d0-1af9927abcd4.PNG)
![error2](https://cloud.githubusercontent.com/assets/3074947/23046341/169515a4-f490-11e6-8081-fc5123d78965.PNG)

**Comment by gemron** [comment]
i have this problem too.

**Comment by jdubois** [comment]
Can you put a correct title and follow the guidelines?

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
