### ISSUE TITLE
gulp config does not copy all scss files in a bower_components subdirectory

### ISSUE THREAD

**Issue by arnogeismar** [jhipster/generator-jhipster#5237]
I believe the problem lies here:

.pipe(inject(gulp.src(bowerFiles({filter:['**/*.{scss,sass}']}), {read: false}), {
            name: 'bower',
            relative: true
        }))

I added slick-carousel to my bower.json.
after bower install the dependency is added and after
gulp build it loads 
slick.scss
and injects
<link rel="stylesheet" href="bower_components/slick-carousel/slick/slick.css">
into my index.html

The library contains another scss file called slick-theme.scss and this is not added to my index.html

**Comment by pascalgrimaud** [comment]
You have probably found an issue, maybe not.
But without more information and a correct description to reproduce, it is hard to help

**Comment by pascalgrimaud** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by arnogeismar** [comment]
@pascalgrimaud 

I will try to follow the guidelines next time.

I managed to fix it by adding this to my overrides although it feels like a workaround: 

"overrides": {
        "angular": {
            "dependencies": {
                "jquery": "3.1.0"
            }
        },
        "angular-cache-buster": {
            "dependencies": {
                "angular": "1.5.8"
            }
        },
        "angular-dynamic-locale": {
            "dependencies": {
                "angular": "1.5.8"
            }
        },
        "bootstrap-sass": {
            "main": [
                "assets/stylesheets/_bootstrap.scss"
            ]
        },
        "slick-carousel": {
            **"main": [
                "slick/slick-theme.css",
                "slick/slick.css",
                "slick/slick-theme.scss",
                "slick/slick.scss",
                "slick/slick.js"
            ]**
        }

**Comment by deepu105** [comment]
Its the correct way as the library you use should have all main files
defined else you need to add it yourself like this. Its not a Jhipster issue


Thanks & Regards,
Deepu
