### ISSUE TITLE
this.eventManager.subscribe('userListModification', (response) => this.loadAll()); not working in lazy loaded module

### ISSUE THREAD

**Issue by seawenzhu** [jhipster/generator-jhipster#5251]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

make admin module with lazy loaded, User list is not updated after user changed(new,edit,delete).

##### **Motivation for or Use Case**

In UserMgmtComponent bellow line is not triggered after user changed(new,edit,delete)
this.eventManager.subscribe('userListModification', (response) => this.loadAll());

##### **Reproduce the error**

jhipster a new project make the admin module lazy loaded, in user management function create a new user.

##### **Suggest a Fix**

it seems the EventManager problem

##### **JHipster Version(s)**

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.0",
    "baseName": "dos",
    "packageName": "xxx.xxx",
    "packageFolder": "xxx/xxx",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "189796dbc913677acc996f00d8d55f972287f901",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

git version 2.10.1 (Apple Git-78)

node: v6.9.5

npm: 3.10.10

bower: 1.8.0

gulp:
[20:49:10] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.19.1

##### **Browsers and Operating System**

macOS 10.12.8 , all browsers

**Comment by flaviencathala** [comment]
@seawenzhu I don't understand the issue, the user management works perfectly with me. Can't you provide more information ?

**Comment by jdubois** [comment]
Just tried it with @flaviencathala and the page is indeed updated when a user is modified.

I'm sorry but I don't understand your use case.

**Comment by seawenzhu** [comment]
@flaviencathala and @jdubois 
I create the case (change admin module to lazy loaded) 
https://github.com/seawenzhu/lazy.git

you can clone the project and run

**Comment by jdubois** [comment]
You seem to use https://github.com/brandonroberts/angular-router-loader - I'm sorry but we don't use that dependency currently

**Comment by seawenzhu** [comment]
@jdubois  
Yes, I need angular2 lazy load feature,  and it is important to improve the first page loaded performance. Is there any way to avoid this problem
thanks.

**Comment by jdubois** [comment]
I'm sorry but I don't know this library, and our aim is to use "normal" Angular 2 as much as we can. And also avoid little-known libraries (this one doesn't even have 100 stars).
If we don't do this, we'll have lots of maintenance issues, and it's already complex enough.

**Comment by deepu105** [comment]
If you want to lazy load the module why dont you do it using angular router
as it does lazy loading OOB

Thanks & regards,
Deepu

On 20 Feb 2017 2:33 p.m., "Julien Dubois" <notifications@github.com> wrote:

I'm sorry but I don't know this library, and our aim is to use "normal"
Angular 2 as much as we can. And also avoid little-known libraries (this
one doesn't even have 100 stars).
If we don't do this, we'll have lots of maintenance issues, and it's
already complex enough.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5251#issuecomment-281080257>,
or mute the thread

**Comment by narimanmandi** [comment]
i have the same problem with different situation , i have two outlets (parent->child) and the route that prevents a component with second outlet is lazy.i called second outlet as "profile"
when in profile outlet i click logout and broadcast an event , i want to subscribe this event in my topBarHeaderComponent that is in outlet1(parent)
but it doesn't work.
by the way i am using jhiEventManager all over of my application and it doesn't work only in this situation.
any idea?
@jdubois @flaviencathala @deepu105

**Comment by SudharakaP** [comment]
@narimanmandi : Thanks for bringing this up, but since this is a very old issue I would suggest opening a new issue if you think the problem still exists. Provide all the information (such as `.yo-rc.json` and JDL files) to recreate the issue (you can print them out via `jhipster info`).
