### ISSUE TITLE
Question HTTP authentication

### ISSUE THREAD

**Issue by samouraii** [jhipster/generator-jhipster#5269]
Hello,

Sorry for my question and for my English.

I'm working with jhipster for a software and i have a web site. Now i would like connect the user in my software with the account of my website. 

Can i authenticate the user in the application or need to copy the information? I can create a jwt, nut after i need to talk with the jhipster for give the token.

i'm lost and i don't find tutorials.

thank you for your help

**Comment by pascalgrimaud** [comment]
Sorry, it is not the right place.
You should go to stackoverflow.

**Comment by samouraii** [comment]
I say, and i'm sorry! But in stackoverflow he don't Say....

**Comment by pascalgrimaud** [comment]
I closed your ticket because it is a bug tracker and not a support channel.
StackOverFlow is the right place if you need help to implement a specific code.
