### ISSUE TITLE
logstash does work after add spring cloud stream kafka 

### ISSUE THREAD

**Issue by YuanZhencai** [jhipster/generator-jhipster#5290]
##### **Overview of the issue**

generator-jhipster vesion is 3.12.2. After add spring cloud stream kafka, the logstash does not work after the application started.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
