### ISSUE TITLE
Jhipster dev profile only working when used in combination with yarn / browsersync ?

### ISSUE THREAD

**Issue by kbjp** [jhipster/generator-jhipster#5297]
##### **Overview of the issue**

Is the Jhipster dev profile only working when used in combination with yarn / browsersync ?

##### **Motivation for or Use Case**

Jhipster's online doc says that the application is assumed to be available under localhost:8080 when running mvnw (default **dev** profile) but the returned index.html page is blank because no javascript file is included in that page (indeed, in the pom.xml, the frontend-maven-plugin is not called by the dev profile during the build).
Is the pom wrong or the doco wrong ?

##### **Reproduce the error**

From the command line, run "yo jhipster" (yarn, angularjs2, maven options). then "mvnw". open browser with "localhost:8080". The returned page is blank.

##### **Related issues**

N.A.

##### **Suggest a Fix**

Is the jhipster **dev** profile only assumed to be used in combination with yarn (BrowserSync) ?
(in which case, the "creating an application" documentation page should be corrected)
OR
should the frontend-maven-plugin (which calls yarn) be part of the dev profile ?
(in which case the pom,xml file would need to be corrected)

In any case, the app running under maven's dev profile doesn't seem to work as-is on port 8080 (the index.html page is blank because yarn is not part of the build, so there's no javascript included to that page by maven).

##### **JHipster Version(s)**

4.0.6

##### **JHipster configuration**

yo options: yarn, angularjs2, maven

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N.A.

##### **Browsers and Operating System**

Chrome 56.0 under ubuntu 16.04

**Comment by gmarziou** [comment]
> Is the jhipster dev profile only assumed to be used in combination with yarn (BrowserSync) ?
(in which case, the "creating an application" documentation page should be corrected)

And no need to crosspost on stackoverflow https://stackoverflow.com/questions/42432902/how-does-maven-running-under-dev-profile-include-the-javascript-files-inside-i
