### ISSUE TITLE
Generating and running a WAR file. My brower got nothing. You are using an outdated browser.

### ISSUE THREAD

**Issue by ljohnny** [jhipster/generator-jhipster#5302]
if i used idea to start the example project .that's ok. whats wrong with it?i used the latest version.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by ljohnny** [comment]
i have not any wrong message,just run ./gradlew -Pprod bootRepackage and then run ./jhipster-0.0.1-SNAPSHOT.war,then get a white page in brower.

**Comment by deepu105** [comment]
@ljohnny as said above we cant help you if you dont follow our guidelines and provide all required info

**Comment by ljohnny** [comment]
i have follow your guidelines and face some probleam.And i ask a new question in stackoverflow.
http://stackoverflow.com/questions/42458410/generating-and-running-a-war-file-my-brower-got-nothing-you-are-using-an-outda

in my case,i cant get any wrong message.erverything look ok.but when i generating the monolithic application as a war and running it .and then i get a white page in any brower.

**Comment by jdubois** [comment]
No you are not. And please don't cross post on SO, this is also against the project rules.

**Comment by ljohnny** [comment]
sorry for my way of asking,i dont read the rules at first when i asking question.i know this issue have appeared,but i dont know whats wrong with my case.can i get some help?

**Comment by deepu105** [comment]
@ljohnny I'm not sure what problem you could possibly face in reading our bug template and providing the required template. If you have issue with English you could easily use a translation service(Google translate) and we really cant help you without the details required in the bug template. I suggest you open a new issue, read through the template filled first and provide all required info if you need our help

**Comment by ljohnny** [comment]
it really without any other message
![image](https://cloud.githubusercontent.com/assets/9734646/23336776/8361bf3a-fc14-11e6-88bd-44a6630755a3.png)

**Comment by ljohnny** [comment]
i am so reckless.jhipster's Guidelines have write clear.i dont read seriously.thanks for your help.
