### ISSUE TITLE
Error creating new app: error Received malformed response from registry for undefined. The registry may be down.

### ISSUE THREAD

**Issue by joxzaren** [jhipster/generator-jhipster#5308]
##### **Overview of the issue**

Running >yo jhipster results in error
   ...
   create src/main/webapp/i18n/en/global.json
   create src/main/webapp/i18n/en/health.json
   create src/main/webapp/i18n/en/reset.json
   create src/main/resources/i18n/messages_en.properties
yarn install v0.20.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error jhipster 

ERROR! yarn install failed.

The following options were set:

 (1/15) Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? (2/15) What is the base name of your application? xxx
? (3/15) Would you like to install other generators from the JHipster Marketplace? No
? (4/15) What is your default Java package name? xxx.xxx.xxx
? (5/15) Which *type* of authentication would you like to use? HTTP Session Authentication (stateful, default Spring Security mechanism)
? (6/15) Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? (7/15) Which *production* database would you like to use? MySQL
? (8/15) Which *development* database would you like to use? MySQL
? (9/15) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
? (10/15) Would you like to use Maven or Gradle for building the backend? Maven
? (11/15) Which other technologies would you like to use? (Press <space> to select, <a> to toggle all, <i> to inverse selection)
? (12/15) Which *Framework* would you like to use for the client? [BETA] Angular 2.x
? (13/15) Would you like to use the LibSass stylesheet preprocessor for your CSS? No
? (14/15) Would you like to enable internationalization support? Yes
? Please choose the native language of the application? Swedish
? Please choose additional languages to install English
? (15/15) Besides JUnit and Karma, which testing frameworks would you like to use? (Press <space> to select, <a> to toggle all, <i> to inverse selection)
##### **Motivation for or Use Case**

Trying to create an app fails

##### **Related issues**

No

##### **JHipster Version(s)**

jhipsterVersion": "4.0.6",
node: v7.6.0
yarn: 0.20.3
npm: 4.3.0

##### **JHipster configuration**

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

git version 2.10.1 (Apple Git-78)

node: v7.6.0

npm: 4.3.0

yeoman: 1.8.5

yarn: 0.20.3

##### **Browsers and Operating System**

macOS sierra

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Did you retry as the error says yarn registry might be down. Also are you
behind any firewall or corporate proxy?

Thanks & regards,
Deepu

**Comment by joxzaren** [comment]
No, no firewalls or corporate proxies. 

I've retried it several times with the same result. If https://registry.yarnpkg.com is the yarn registry it seems to up and running.

Thanks,
Per

**Comment by joxzaren** [comment]
Running yarn install —verbose gives the following information:

verbose Request "https://registry.yarnpkg.com/@angular%2fcli" finished with status code 503.

**Comment by gmarziou** [comment]
Yes but it works, so it might be a temporary hiccup from yarn regsitry.

**Comment by gmarziou** [comment]
Closing as it is not a jhipster issue.

**Comment by sami93** [comment]
its solved for me with this command : 
yarn config set strict -ssl false
