### ISSUE TITLE
Problems with integration with materialize-css framework

### ISSUE THREAD

**Issue by SerhiiTsybulskyi** [jhipster/generator-jhipster#5309]
##### **Overview of the issue**

When I tried to connect '[materialize-css](https://www.npmjs.com/package/angular2-materialize#installing--configuring-angular2-materialize-in-projects-created-with-angular-cli)' (using this instruction) I get an error:

> HomeComponent - inline template:0:0 caused by: $(...).carousel is not a function

But when I try it on clean angular CLI project it works fine. Test clear angular CLI project with integrated materialize-css available at this [repo](https://github.com/SerhiiTsybulskyi/a2Cli)

##### **Motivation for or Use Case**

I want to use the material design for my project. This library more functional than others.

##### **Reproduce the error**

For reproducing this bug you can apply [this](https://gist.github.com/SerhiiTsybulskyi/ac2ed7c0db02f625a810580bd0f8a51e) patch 

##### **JHipster Version(s)**
JHipster Version: 4.0.6
##### **JHipster configuration**
Jopenjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
git version 2.7.4
node: v7.5.0
npm: 4.1.2
bower: 1.8.0
gulp: CLI version 3.9.1
yeoman: 1.8.5
yarn: 0.19.1

The [.yo-rc.json](https://gist.github.com/SerhiiTsybulskyi/e8922c7ddc0aee8763c7a5eebdb0ad2d)

##### **Browsers and Operating System**
Operating System: Ubuntu 16.04.2 LTS
Google Chrome: Version 56.0.2924.87 (64-bit)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Can you follow the guidelines, please? Paste your config here, I'm on my phone I can't read this.

**Comment by gmarziou** [comment]
This is rather a question for stackoverflow than a jhipster issue.

**Comment by SerhiiTsybulskyi** [comment]
I've inserted link on my .yo-rc.json. Do you mean this config?

> {
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "onlinegid",
    "packageName": "onlinegid.site",
    "packageFolder": "onlinegid/site",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "", //removed
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-material",
        "version": "0.0.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ru"
    ],
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}

**Comment by SerhiiTsybulskyi** [comment]
@gmarziou but your link about another module.
I want ti integrate this module https://www.npmjs.com/package/angular2-materialize

**Comment by gmarziou** [comment]
I know, this is just to give you an example where you sould add your module and css, you still have some work to figure how to adapt to this non standard lib.
