### ISSUE TITLE
Social Login Failure "Cannot POST" Angular2

### ISSUE THREAD

**Issue by jd-carroll** [jhipster/generator-jhipster#5314]
##### **Overview of the issue**
Social login does not appear to be working. When I navigate to the registration page and click on Google or Facebook I see something similar to:
`Cannot POST /signin/facebook`

(Angular2)

##### **Motivation for or Use Case**

All default social login connectors seem to be broken

##### **Reproduce the error**

Install latest version of JHipster and use the `yo-rc` provided below.  Navigate to the registration page and select one of the connectors.

##### **Related issues**

Not sure how or if this is related to #5002 

##### **Suggest a Fix**

Not sure what the issue is... (Maybe something I am [not] doing)

##### **JHipster Version(s)**

JHipster: v4.0.6

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "sample",
    "packageName": "com.sample",
    "packageFolder": "com/sample",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "13a3f6c1bd19073e8203f8873f0708108ebaa6ee",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Browsers and Operating System**

OS X: 10.11.6
Chrome: 56.0.2924.87 (64-bit)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Did you follow the Spring Social documentation, and set up your API keys?

**Comment by jd-carroll** [comment]
That's probably it, I was just prototyping something quickly (never used the social connectors) and missed the doc's in the .yml files.  I'll try creating those, which I'm fairly confident will solve the issue.  Closing pre-emptively

**Comment by s-t-x** [comment]
This looks exactly like your spring security is not enabled.

**Comment by s-t-x** [comment]
API key are not enough. If you are accessing the app via http, enable spring security and when you do switch to https, it will work.

**Comment by AndersonSM** [comment]
Sorry, but can you be a little more specific? My backend is running on HTTPS now, but not my frontend.
This is how my application.yml file looks like.
![untitled](https://user-images.githubusercontent.com/9259316/27802072-e6096358-5ff7-11e7-8bf6-3da85a006f3d.jpg)

**Comment by jdubois** [comment]
I'm sorry but this isn't a bug -> can you discuss this on Stackoverflow, using the "jhipster" tag? As written in the guidelines, this bug tracker is just for tracking bug, it's not a support forum. The right place for this is Stackoverflow, and you will have there more people helping you (and you will also help more people there)
