### ISSUE TITLE
Is there any forum or foundation about JHipster?

### ISSUE THREAD

**Issue by eacdy** [jhipster/generator-jhipster#5323]
Is there any forum or foundaton about JHipster?
I've get the domain `jhipster.io` . I'd like to found a forum about it.
May I?
@amr @ahars @andidev

**Comment by gmarziou** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by gmarziou** [comment]
https://gitter.im/jhipster/generator-jhipster

**Comment by gmarziou** [comment]
Or use twitter
