### ISSUE TITLE
Images referred in HTML templates are not found

### ISSUE THREAD

**Issue by santoshkt** [jhipster/generator-jhipster#5333]
##### **Overview of the issue**

I generated a project using jH 4.0.3 version. I copied all my actual navbar content into navbar.html. The logo in navbar.html is referring to `../../../content/images/my_logo.png`

All the images in default project are referred in css files and not from HTML files. I can't figure how to get this working with images referred directly from HTML. When I start the application, the image is not found. Also, I checked in www folder under build. There is no generated hash file name for `my_logo.png`.

##### **Motivation for or Use Case**

Component HTML must be able to refer to images in `.../content/images/...` directly without involving CSS

##### **Reproduce the error**

Add a new image in `/content/images` folder and refer to that image directly using `<img src> `

##### **JHipster Version(s)**

4.0.3

##### **Other**

node: v7.5.0
npm: 4.2.0
bower: 1.8.0
gulp: 3.9.1
yarn: 0.19.1

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Are you using AngularJS 1 or Angular 2? Please follow the guidelines...

**Comment by santoshkt** [comment]
I'm using Angular 2. Sorry, the template din't ask for Angular version when filing issue.

**Comment by jdubois** [comment]
It does, that's in your `.yo-rc.json`- we need your full config to test

**Comment by santoshkt** [comment]
```
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "WebPresence",
    "packageName": "com.company.my.app",
    "packageFolder": "com/company/my/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "randomkey",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}
```

**Comment by jdubois** [comment]
Thanks

**Comment by deepu105** [comment]
@jdubois seems you are in a very good mood :smiling_imp: you didnt close the ticket for not following guidelines :rofl:

**Comment by santoshkt** [comment]
Anyone has clues on what I should be looking into ? This looks like a webpack issue to me. I was going through webpack config files but no clue yet. I'm using webpack for first time. so don't know much about it.

**Comment by deepu105** [comment]
@santoshkt I dont have enough time at the moment but you should start looking at the rules in webpack config to see if it covers images from html, else you might need to add a rule for image loaders to find images in html

**Comment by gmarziou** [comment]
If you don't care about versioning images with hashed use file-loader as we do for favicon.ico

**Comment by santoshkt** [comment]
Based on http://stackoverflow.com/questions/35400733/webpack-and-angular-html-image-loading, I have to use html-loader instead of raw-loader. But for life of me, I can't figure why I'm getting lot of errors like below when I use html-loader

```
ERROR in ./src/main/webapp/app/account/password-reset/init/password-reset-init.component.ts
Module not found: Error: Can't resolve 'html-loader' in '/Users/company/folder/myapp'
 @ ./src/main/webapp/app/account/password-reset/init/password-reset-init.component.ts 46:18-65
 @ ./src/main/webapp/app/account/index.ts
 @ ./src/main/webapp/app/account/account.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
 @ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/app/app.main

```

All I'm doing is replacing raw-loader and index.html exclude with html-loader.

**Comment by gmarziou** [comment]
My suggestion was simpler....

**Comment by santoshkt** [comment]
Yes, it is. I was kind of hoping to take advantage of compression and cache busting if possible..

**Comment by santoshkt** [comment]
I stupidly did not put html-loader in package.json assuming webpack knows how to pick it. That fixed the issue for me.

**Comment by deepu105** [comment]
You could do a PR if its a generic solution

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
Just got the same issue today, so I confirm this is a problem :-)
