### ISSUE TITLE
Test configuration missing: messages: basename: i18n/messages

### ISSUE THREAD

**Issue by mguillem** [jhipster/generator-jhipster#5334]
Generated test configuration `src/test/resources/config/application.yml` is missing settings for messages like in the generated `src/main/resources/config/application.yml` what causes `MessageResource` injected in unit tests to be empty.

The problem is in https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/test/resources/config/_application.yml which is missing following:
```
    messages:
        basename: i18n/messages
```

**Comment by deepu105** [comment]
@mguillem can you do a PR

**Comment by mguillem** [comment]
@deepu105 no, I haven't cloned the project and for this very small change it is not worth doing it.

**Comment by jdubois** [comment]
Then let's close this if even the person reporting the bug doesn't care

**Comment by mguillem** [comment]
Seriously, would I have opened the issue if I don't care?

It would take you exactly 20 seconds to understand the problem and fix it. It would take me 10 minutes to fork the project and create a pull request. For such a minimal change, I think that it isn't worth the time because you can do it really faster. It doesn't mean that there is no problem. Nevertheless, if you don't want to fix it, it's up to you, but it is still a bug.

**Comment by jdubois** [comment]
Let's not waste even more time by arguing... We have all better things to do (like a PR)

**Comment by deepu105** [comment]
@mguillem If everyone had your attitude then there wont be any free and OSS projects. Dont you think we would also have better things to do than this? While we dont expect you to appreciate what we do we do expect you to respect that we do all this for free on our free time. So if you want something to be fixed you either do it, regardless of how long it takes, or you could atleast politely ask us.

**Comment by mguillem** [comment]
@deepu105 it may surprise you, but you're not the only one with large experience in OSS projects.

@jdubois what about documenting that you only accept push requests, even for obvious issues?

**Comment by jdubois** [comment]
Guys, I have no time for this, really.



Le 2 mars 2017 9:05 AM, "mguillem" <notifications@github.com> a écrit :

@deepu105 <https://github.com/deepu105> it may surprise you, but you're not
the only one with large experience in OSS projects.

@jdubois <https://github.com/jdubois> what about documenting that you only
accept push requests, even for obvious issues?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5334#issuecomment-283584063>,
or mute the thread

**Comment by jdubois** [comment]
Let me take 5 minutes: I'm doing this on the train, with my phone. Of course it's much easier for me if you do a PR: I click on merge, and it's done.
I won't have access to my computer until late at night, and I have tons of other tickets, so if you just open a ticket its priority will be much lower than a PR. And then, I can't have too many opened tickets, so if you say it's not worth 10 minutes of your time, then it's probably not worth 10 minutes of mine. And no, I don't code PRs quicker than you. It's just a question of managing priorities.

**Comment by deepu105** [comment]
Im not talking about any ones experience here and I dont care to be frank.
I was talking about attitude and I have made my point so lets stop the
discussion so we dont waste any ones time further.

Sorry Julien.

Thanks & regards,
Deepu
