### ISSUE TITLE
Request JDL files could import/include each other

### ISSUE THREAD

**Issue by BryanYin** [jhipster/generator-jhipster#5341]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

I use jhipster JDL to create entities and relationships. I separated entities into different .jh files for a good modeling like configuration entity, dynamic entity, etc. But seems JDL didn't provide the import/include mechanism such that I can't refer an entity in the other file, e.g. I can't create a product(in dynamic.jh) with relationship to a rate(in configuration.jh), I tried to use `entity Rate` as declaration in dynamic.jh, but `import-jdl` will create a new entity for me.

##### **Motivation for or Use Case**

For microservice or modeling reason, we will put entities in different files, it's common we will refer entities in other place.

##### **Reproduce the error**

new feature request.

##### **Suggest a Fix**

suggest we could use import/include or export to expose entities to other files.

##### **JHipster Version(s)**

4.0.6
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Hi. Have you tried passing more than one JDL file to the import submodule?
Maybe one day I'll implement something like this, but there are other priorities.

**Comment by jdubois** [comment]
OK, it's an interesting idea but we lack time -> let's close this as we don't currently have the time to implement this

**Comment by BryanYin** [comment]
Okay... Thank you guys, I figured out the way to do this...say a.jh refers entities from b.jh, then it should write like this `entity B(T_B_TABLE_NAME)` in a.jh then `yo jhipster:import-jdl a.jh b.jh`, in this way, entity B generated in b.jh will overwrite empty entity B generated in a.jh.

**Comment by jdubois** [comment]
Yes that looks like a good idea.

**Comment by MathieuAA** [comment]
There's no need to write twice the same entity in two separate files (you can replace 2 by `n` here).
When parsing, JHipster will read every file **before** interpreting the unified content.
