### ISSUE TITLE
import-JDL won't take my skips

### ISSUE THREAD

**Issue by BryanYin** [jhipster/generator-jhipster#5342]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

I reported PR [#251](https://github.com/jhipster/jhipster-uml/issues/251#issuecomment-281637937) in Jhipster-UML reported the issue `skipClient` and `skipServer` don't work for me. After @MathieuAA checked, it turns out to be a sub generator issue related with jhipster-core. So I put it here.

##### **Motivation for or Use Case**

import-jdl skipped my skips, this is a bug.

##### **Related issues**

[#251](https://github.com/jhipster/jhipster-uml/issues/251#issuecomment-281637937)

##### **Suggest a Fix**

The JDL parser can correctly parse my skips but when transfer this to .json files in .jhipster dir, these skips are lost. In entity_parse.js in function setOptions() below code skipped all options:
    if (option.getType() === 'UNARY' && option.name !== UnaryOptions.NO_FLUENT_METHOD) {
      continue;
    }
I'm not quite understand why it is doing this. Here should add code to deal with other options, like `skipClient` and `skipServer`.
##### **JHipster Version(s)**

4.0.6

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
entity MonitorLocation (T_MLOCATION) {
	description String maxlength(40),
	geoId Integer,
	operId Integer,
	mpTypeId Integer,
	ip String maxlength(40),
	latitude Float,
	longitude Float
}
skipClient for MonitorLocation
skipServer for MonitorLocation
```
##### **Browsers and Operating System**
chrome in windows 7

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
You both skip the server AND the client? I have no idea what you're trying to do, but I don't expect this to work at all.... What do you want, an empty project?

**Comment by MathieuAA** [comment]
Why not? ;) the problem is easy to fix (it's implemented in JUML for instance). I just didn't have the time to propose a PR. I still don't but I'll try to get it done by saturday.

Le 2 mars 2017 07:17:21 GMT+01:00, Julien Dubois <notifications@github.com> a écrit :
>You both skip the server AND the client? I have no idea what you're
>trying to do, but I don't expect this to work at all.... What do you
>want, an empty project?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/5342#issuecomment-283566825

-- 
Mathieu ABOU-AICHI

**Comment by jdubois** [comment]
OK but I don't understand what the output should be - an empty directory ?

Le 2 mars 2017 8:44 AM, "Mathieu ABOU-AICHI" <notifications@github.com> a
écrit :

**Comment by BryanYin** [comment]
Julien, I was intended to create some internal configurable DB table for DBA, so I was hoping Liquibase changelog can be generated if I skip both. But now the DBA want to do this by himself. Maybe you can consider this and just generate changelog if skip both?
Actually the point here is skip doesn't work, thank you both to help with this. Jhipster is really a wonderful tool!

**Comment by ruddell** [comment]
The liquibase files are part of the server and I don't think it makes sense to separate them out.

If you want just the liquibase files, skip only the client and copy the liquibase files from `src/main/resources/config/liquibase`.

**Comment by jdubois** [comment]
Indeed, if you skip the server, than you have no Liquibase either, it's part of the server files. @ruddell is correct, and anyway I'm sure you can find a way to delete the server files you don't like, or select only the Liquibase files...
I don't think you'll much trouble here, but you have quite a specific case, of course.
Then we should check that people don't combine both options - probably just exit and print a message saying those options are not compatible with each other.

**Comment by jdubois** [comment]
I just checked and this is already validated, see [here](https://github.com/jhipster/generator-jhipster/blob/v4.0.7/generators/app/index.js#L174).
So I don't know how you managed to have both options, but they should not work together, and that's normal and validated.

**Comment by deepu105** [comment]
I think he tried it for specific entity and its not validated on the entity sub generator. We could add the validation there as well but passing both doesnt make sense anyway

**Comment by BryanYin** [comment]
Hey guys, the point here is not about skip both, I submit the PR because it won't take **ANY** skip even if i just either skipClient or skipServer. And after several days usage, I agree with @ruddell , we need server side code together with entities.

**Comment by BryanYin** [comment]
Julien, I don't think the code goes such far to the validation place, please see my `suggested fix` the skip options are `continued` by that `if` check.

**Comment by jdubois** [comment]
I'm re opening this, and will take another look.

**Comment by MathieuAA** [comment]
The only thing we have to do here is to pass special flags to the command array (like in JUML).

Le 8 mars 2017 07:32:39 GMT+01:00, Julien Dubois <notifications@github.com> a écrit :
>I'm re opening this, and will take another look.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/5342#issuecomment-284959585

-- 
Mathieu ABOU-AICHI

**Comment by jdubois** [comment]
OK, I didn't code this part but I see the logic here:

- The "skip server" and "skip client" should come from the "global" project, so they come from your `.yo-rc.json`. Indeed, it makes no sense to generate a project with "skip server" and then ask to have the server files in an entity. This is why "skip server" and "skip client" are not saved per entity.
- Now, the way the sub-generator works is that you pass it arguments: so the "global" generator can send "skip client" and "skip server" to the entity sub-generator. And indeed, you can use the same config to do the same yourself (which is what I guess you did).

So for me, it's logical that:

- You can send the "--skip-server" and "--skip-client" flags
- Those are not saved in the `.json` files for each entity

And in the end this all look good, even if it's not totally obvious.
