### ISSUE TITLE
On error during entity update, save button is not enabled back

### ISSUE THREAD

**Issue by rakeshkalra1983** [jhipster/generator-jhipster#5346]
##### **Overview of the issue**

When editing an entity, on pressing save button, if error is received from the server save button is not enabled back.
I believe this happens only when enableTranslation is false, as I don't see this issue in Jhipster Sample application from git.

##### **JHipster Version(s)**

Jhipster Version 4.0.7

##### **JHipster configuration**

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

Browser: Chrome & Firefox
OS: Mac OS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
FWIW, Dennis and I saw this in our workshop last week too.

**Comment by wmarques** [comment]
@rakeshkalra1983 
Thanks for the report !
Can you do a PR ? (same question for your other issues :smile: )

**Comment by ruddell** [comment]
One cause of this is that Angular doesn't have support for min/max validation on the number input...

**Comment by wmarques** [comment]
Save button isn't enabled because when we catch the error, we do a `res.json()`, but sometimes it's just a text message (for example when we didn't start spring boot), so we should catch the exception raised by res.json() and then do a `res.text()` instead.
I don't know if we should do this in the service or in the onSave method... What do you think guys ?
