### ISSUE TITLE
Entity should be refreshed when edited from entity detail page

### ISSUE THREAD

**Issue by rakeshkalra1983** [jhipster/generator-jhipster#5347]
##### **Overview of the issue**

When I click Edit button from Entity Detail page, edit entity modal is opened. On pressing save button, modal is closed but entity on the detail page is not updated. We have to refresh the entity detail page to reflect the changes on page.

If entity is edited from Entity List page, on pressing save button, modal is closed and entities are updated fine.

##### **Motivation for or Use Case**

Its nice to see entity edited from entity detail page 

##### **Suggest a Fix**

Like we are subscribing to entityListModification event on entity list page, and reset the entities there, we can subscribe to entityListModification event on entity detail page.

##### **JHipster Version(s)**

4.0.7

##### **JHipster configuration**

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "eachfit",
    "packageName": "com.eachfit",
    "packageFolder": "com/eachfit",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
I fixed this, I'll PR this later tonight (was in the train so couldn't push...).
