### ISSUE TITLE
jhiTranslate is present for Enum Type fields even when translation is disabled

### ISSUE THREAD

**Issue by rakeshkalra1983** [jhipster/generator-jhipster#5348]
##### **Overview of the issue**

Even though translations was disabled when creating jhipster project, still we get related attributes for entity field of enum type.

This is how my entity-dialog html file looks like:

`<select class="form-control" name="companyType" [(ngModel)]="company.companyType" id="field_companyType"  required>
                <option value="ATYPE" jhiTranslate="eachfitApp.CompanyType.ATYPE">ATYPE</option>
                <option value="BTYPE" jhiTranslate="eachfitApp.CompanyType.BTYPE">BTYPE</option>                </select>` 

I have to latter manually remove these jhiTranslate attribute from html code.

##### **JHipster Version(s)**

4.0.7

##### **JHipster configuration**

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "eachfit",
    "packageName": "com.eachfit",
    "packageFolder": "com/eachfit",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
jhiTranslate is present in other files even if you don't choose translation... So I don't think this is a bug.

**Comment by gmarziou** [comment]
> I have to latter manually remove these jhiTranslate attribute from html code.

Why?

**Comment by jdubois** [comment]
I don't think this cause any trouble, but indeed the "enum" type should not generate those if the i18n isn't selected. This is just a matter of adding a "if ... then ... else" in the template, probably.

**Comment by gmarziou** [comment]
Maybe it could be done globally by stripping them in [copyTemplate](https://github.com/jhipster/generator-jhipster/blob/556bbcfb247adffc47eff528094a1306803d5e73/generators/generator-base.js#L1039)

**Comment by jdubois** [comment]
Just tried it, and I can't reproduce. So I'm sorry but I have no idea how you managed to have this issue.

**Comment by deepu105** [comment]
Yes we already pass these through `processHtml` method which calls `copyTemplate` so I'm not sure how you got this. @rakeshkalra1983 can you try with latest version?
