### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by JackFish** [jhipster/generator-jhipster#5351]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

use docker build, issue on yarn add node-sass

use docker create jenkins then run the pipeline

[INFO] yarn install v0.20.3
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...
[WARNING] warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
[INFO] info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[INFO] [3/4] Linking dependencies...
[WARNING] warning "@angular/compiler-cli@2.4.8" has incorrect peer dependency "@angular/compiler@2.4.8".
[WARNING] warning "@angular/compiler-cli@2.4.8" has incorrect peer dependency "@angular/core@2.4.8".
[WARNING] warning "@ngtools/webpack@1.2.11" has unmet peer dependency "@angular/tsc-wrapped@^0.5.0 || >=4.0.0-beta <5.0.0".
[INFO] [4/4] Building fresh packages...
[ERROR] error /var/jenkins_home/workspace/checking_spring1.5.1-3RE3GJ3C57FMCMFYIILQHGFLDNELZL3QEUGV5QH5UELN2NGWH5GQ/node_modules/node-sass: Command failed.
[ERROR] Exit code: 135
[ERROR] Command: sh
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ERROR] Arguments: -c node scripts/build.js
[ERROR] Directory: /var/jenkins_home/workspace/checking_spring1.5.1-3RE3GJ3C57FMCMFYIILQHGFLDNELZL3QEUGV5QH5UELN2NGWH5GQ/node_modules/node-sass
[ERROR] Output:
[ERROR] Binary found at /var/jenkins_home/workspace/checking_spring1.5.1-3RE3GJ3C57FMCMFYIILQHGFLDNELZL3QEUGV5QH5UELN2NGWH5GQ/node_modules/node-sass/vendor/linux-x64-51/binding.node
[ERROR] Testing binary
[ERROR] Bus error (core dumped)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:12 min
[INFO] Finished at: 2017-03-03T09:51:14+00:00
[INFO] Final Memory: 11M/241M
[INFO] ------------------------------------------------------------------------

##### **Suggest a Fix**

4.0.7

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "credit_checking",
    "packageName": "com.zwo.credit",
    "packageFolder": "com/zwo/credit",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f82aa17ff3673ea72b79c04def945bca7ab9b336",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

{
  "name": "credit-checking",
  "version": "0.0.0",
  "description": "Description for credit_checking",
  "private": true,
  "cacheDirectories": [
    "node_modules"
  ],
  "dependencies": {
    "@angular/common": "2.4.7",
    "@angular/compiler": "2.4.7",
    "@angular/core": "2.4.7",
    "@angular/forms": "2.4.7",
    "@angular/http": "2.4.7",
    "@angular/platform-browser": "2.4.7",
    "@angular/platform-browser-dynamic": "2.4.7",
    "@angular/router": "3.4.7",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.20",
    "angular2-infinite-scroll": "0.3.0",
    "bootstrap": "4.0.0-alpha.6",
    "font-awesome": "4.7.0",
    "angular2-cookie": "1.2.6",
    "core-js": "2.4.1",
    "jquery": "3.1.1",
    "ng-jhipster": "0.1.8",
    "ng2-webstorage": "1.5.0",
    "reflect-metadata": "0.1.9",
    "rxjs": "5.1.0",
    "swagger-ui": "2.2.10",
    "sockjs-client": "1.1.2",
    "webstomp-client": "1.0.5",
    "tether": "1.4.0",
    "zone.js": "0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-beta.28.3",
    "@types/jasmine": "2.5.42",
    "@types/node": "7.0.5",
    "add-asset-html-webpack-plugin": "1.0.2",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.0.4-rc.2",
    "browser-sync": "2.18.7",
    "browser-sync-webpack-plugin": "1.1.4",
    "codelyzer": "2.0.0",
    "copy-webpack-plugin": "4.0.1",
    "css-loader": "0.26.1",
    "del": "2.2.2",
    "event-stream": "3.3.4",
    "exports-loader": "0.6.3",
    "extract-text-webpack-plugin": "2.0.0-beta.5",
    "file-loader": "0.10.0",
    "generator-jhipster": "4.0.6",
    "html-webpack-plugin": "2.28.0",
    "image-webpack-loader": "3.2.0",
    "jasmine-core": "2.5.2",
    "karma": "1.4.1",
    "karma-chrome-launcher": "2.0.0",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "1.1.0",
    "karma-junit-reporter": "1.2.0",
    "karma-phantomjs-launcher": "1.0.2",
    "karma-remap-istanbul": "0.6.0",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "2.0.2",
    "lazypipe": "1.0.1",
    "lodash": "4.17.4",
    "map-stream": "0.0.6",
    "phantomjs-prebuilt": "2.1.14",
    "proxy-middleware": "0.15.0",
    "raw-loader": "0.5.1",
    "run-sequence": "1.2.2",
    "sourcemap-istanbul-instrumenter-loader": "0.2.0",
    "string-replace-webpack-plugin": "0.0.5",
    "style-loader": "0.13.1",
    "to-string-loader": "1.1.5",
    "tslint": "4.4.2",
    "tslint-loader": "3.4.1",
    "typescript": "2.1.6",
    "webpack": "2.2.1",
    "webpack-dev-server": "2.3.0",
    "webpack-merge": "2.6.1",
    "webpack-visualizer-plugin": "0.1.10",
    "write-file-webpack-plugin": "3.4.2",
    "xml2js": "0.4.17",
    "yargs": "6.6.0"
  },
  "engines": {
    "node": ">=6.9.0"
  },
  "scripts": {
    "lint": "tslint 'src/main/webapp/app/**/*.ts' --force",
    "lint:fix": "tslint 'src/main/webapp/app/**/*.ts' --fix --force",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "start": "yarn run webpack:dev",
    "webpack:build": "webpack --config webpack/webpack.vendor.js && webpack --config webpack/webpack.dev.js",
    "webpack:build:dev": "webpack --config webpack/webpack.dev.js",
    "webpack:dev": "webpack-dev-server --config webpack/webpack.dev.js  --progress --inline --hot --profile --port=9060",
    "webpack:prod": "yarn test && webpack -p --config webpack/webpack.vendor.js && webpack -p --config webpack/webpack.prod.js",
    "test": "yarn run lint && karma start src/test/javascript/karma.conf.js",
    "test:watch": "karma start --watch",
    "postinstall": "node node_modules/pngquant-bin/lib/install.js && node node_modules/phantomjs-prebuilt/install.js && yarn run webpack:build"
  }
}

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Isn't this a duplicate from #5343 ?

**Comment by jdubois** [comment]
And please give a better title to the ticket

**Comment by pascalgrimaud** [comment]
I don't understand the issue, not enough information.
I don't know if it's a local build or Jenkins build or Docker+Jenkins build
> use docker build, issue on yarn add node-sass
> use docker create jenkins then run the pipeline

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
