### ISSUE TITLE
Error while mapping foreign key contraint

### ISSUE THREAD

**Issue by sumantsahney** [jhipster/generator-jhipster#5352]
I have two entities having many to one relationship. I changed the name of one key of the entity and individually its working fine.
While using findALl() from other entity SQLGrammarException is thrown.

select scan_segme0_.id as id1_7_, scan_segme0_.duration as duration2_7_, scan_segme0_.inserted_date as inserted_date3_7_, scan_segme0_.scan_containers_id_scan_container_id as scan_containers_id6_7_, scan_segme0_.scan_segment_type as scan_segment_type4_7_, scan_segme0_.status as status5_7_
 from scan_segments scan_segme0_

This query is being called but the column name "scan_containers_id_scan_container_id"  is not part of table instead it should be "scan_containers_id_id".

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "VRQWeb",
    "packageName": "com.vrqwebapp",
    "packageFolder": "com.vrqwebapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "c19146df278a333f78e11a21645839fd6b943169",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-bootstrap-material-design",
        "version": "3.5.1"
      },
      {
        "name": "generator-jhipster-angular-datatables",
        "version": "1.3.8"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}

{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "session_id",
            "fieldType": "Integer"
        },
        {
            "fieldName": "scan_initiator",
            "fieldType": "String"
        },
        {
            "fieldName": "status",
            "fieldType": "Integer"
        },
        {
            "fieldName": "duration",
            "fieldType": "Integer"
        },
        {
            "fieldName": "inserted_date",
            "fieldType": "ZonedDateTime"
        }
    ],
    "changelogDate": "20170302065028",
    "dto": "mapstruct",
    "service": "serviceImpl",
    "entityTableName": "scan_containers",
    "pagination": "no"
}

{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "scan_containers_id",
            "otherEntityName": "scan_containers",
            "relationshipType": "many-to-one",
            "otherEntityField": "scan_container_id"
        }
    ],
    "fields": [
        {
            "fieldName": "duration",
            "fieldType": "Integer"
        },
        {
            "fieldName": "scan_segment_type",
            "fieldType": "Integer"
        },
        {
            "fieldName": "inserted_date",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "status",
            "fieldType": "Integer"
        }
    ],
    "changelogDate": "20170303055149",
    "dto": "mapstruct",
    "service": "serviceImpl",
    "entityTableName": "scan_segments",
    "pagination": "no"
}

**Comment by jdubois** [comment]
You write that you modified the name of your key - then you are not with our default configuration, and I guess this is a bug you introduced yourself.
Are you sure the issue comes from our code, and not your modification?
And please give a better title to the ticket

**Comment by sumantsahney** [comment]
I think that error is in the JPA or DTO which are created and mapping as when I removed the foreign key it started working. So can you suggest me how to deal with it ?

**Comment by jdubois** [comment]
Oh sorry you are mixing DTOs and JPA, so that's normal it doesn't work.
This is a duplicate from #5227
