### ISSUE TITLE
"yarn start" stopped working after updating yarn

### ISSUE THREAD

**Issue by Zacorich** [jhipster/generator-jhipster#5362]
##### **Overview of the issue**

I've updated yarn to version 0.21.3 at some point and by running "yarn start" I ended up at the blank screen at locahost:9000 when webpack seems to be injected and "yarn start" finished without errors. 

##### **Motivation for or Use Case**

After some time wasted on deleting node_modules in my project root directory and recreating it,
I gave up and created a new jHipster project with the same configuration I started my project with. I made directories content diff between clean jHipster and my project and didn't find any significant differences. All 3 ways I use to start the application during development ended up at the blank screen - prod build with maven, dev build with maven and yarn start(just for frontend).

##### **Reproduce the error**

1. create jHipster 4.0.6 basic configuration with Angular 2
2. update you system yarn or change yarn version in pom.xml
3. try to run "yarn start" on project

##### **Suggest a Fix**

1. delete yarn.lock file from project root folder
2. run "yarn install" to generate yarn.lock for current project configuration
3. run "yarn start" again

I would suggest adding this short instruction for newcomers  to yarn and jHipster(somewhere here: [https://jhipster.github.io/development/#running-webpack](url)). 
Another aspect of yarn that is that it downloads all packages into cache and recreates node_modules inside target project from that cache to save network bandwidth. I bet there might a bug in future when node_modules end up with some wrong content but by simply deleting node_modules directory won't solve the broken cache so the last needs to be cleared and recreated: [http://stackoverflow.com/questions/39991508/how-to-clear-cache-in-yarn](url)

##### **JHipster Version(s)**

jHipster 4.0.6 with Angular 2

##### **Browsers and Operating System**

Windows 10,, Google Chrome Version 56.0.2924.87 (64-bit)

**Comment by Zacorich** [comment]
Please add some notes of this pitfall to [https://jhipster.github.io/development/#running-webpack](url)

**Comment by gmarziou** [comment]
Would you consider submitting a pull request for this doc? You seem to be the best person to do so.
