### ISSUE TITLE
Rework the UserResourceIntTest

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#5365]
See the https://sonarqube.com/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application

Since my PR https://github.com/jhipster/generator-jhipster/pull/5288, we were at 80,2%. And few days ago, we were at 80,4%!
But today, we are at 79,8% coverage.

I looked the details and see:
- src/main/java/io/github/jhipster/sample/web/rest/UserResource.java -> 19,2%
-  src/main/java/io/github/jhipster/sample/web/rest/AccountResource.java -> 31,6%

For me, the UserResource should be at least at 90% as it is one of the most important Resource.

I already begin to work. I would like to make the UserResource as closer to the entities we generate: all of them are between 93,5% and 100%.
So I will probably rewamp this file a lot -> are you ok with that ?

**Comment by jdubois** [comment]
Yes of course !

Le 5 mars 2017 1:05 PM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by pascalgrimaud** [comment]
I'm so happy ! 81.8% Coverage !!
