### ISSUE TITLE
Add "fromName" to email configuration

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/generator-jhipster#5368]
##### **Overview of the issue**

Add a fromName configuration property in order to store the name of outgoing e-mails

##### **Motivation for or Use Case**

It's not nice to see the email of the sender, we'd prefer a name.

##### **Reproduce the error**

Send a mail

##### **Suggest a Fix**

In MailService.sendEmail, you could add this property as the second argument of message.setFrom

##### **JHipster Version(s)**

4.0.6

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I totally understand your use-case, and I'm totally willing to have counter-arguments by core team members.
But, as this is just one line in the `MailService` class, for me this is against our [Policy 2](https://jhipster.github.io/policies/), so I don't think we should do it. Of course, this is trivial for you to modify, but for other people this is one more parameter to understand.
