### ISSUE TITLE
Not logged user can access to /entityName pages

### ISSUE THREAD

**Issue by wmarques** [jhipster/generator-jhipster#5372]
##### **Overview of the issue**

Even if a user is not logged in, he can access to an entity page. The data is not loaded of course but the user should be redirected to login modal.

##### **Motivation for or Use Case**

We should have a correct redirection.

##### **Reproduce the error**

Create an app
Create an entity
Access to the entity page via /entityname

##### **Related issues**
None.

##### **Suggest a Fix**

It's in the main.component.ts file. Sometimes it's correct to do this:
`let destinationEvent = event.state.root.firstChild.children[0];`

But sometimes we shouldn't get firstChild but 'root'. I can commit this "dirty" fix tonight if you want.
I don't know if there is a better fix for this...

Maybe we can check this : https://angular.io/docs/ts/latest/guide/router.html "Guard the admin feature"

##### **JHipster Version(s)**

master

##### **JHipster configuration**

All defaults options

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Any entity will do

##### **Browsers and Operating System**

Mac OS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@wmarques : maybe it is the same issue https://github.com/jhipster/generator-jhipster/issues/5249 ?

**Comment by wmarques** [comment]
Seems to be the same but it's not fixed in master. The problem here is the route interceptor that we made in the main component.

**Comment by jdubois** [comment]
Yes for me this is a duplicate from #5249 - and I don't understand why it's not fixed
