### ISSUE TITLE
Detail page is weird since .dl-horizontal has been replaced by .row

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/generator-jhipster#5373]
##### **Overview of the issue**

AngularJS detail pages are broken since .row is used instead of dl-horizontal

##### **Reproduce the error**

generate an entity and go to the detail page

##### **Suggest a Fix**

keep .dl-horizontal for AngularJS / Bootstrap 3 (until we upgrade to Bootstrap 4)

##### **JHipster Version(s)**

since commit: Bootstrap 4 - dl-horizontal has been dropped (#4807)
b802f3ca0c3e1564c33c55868d6b083dde653cf7

##### **JHipster configuration**

AngularJS

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Please follow the guidelines and give your full configuration - it takes time to understand what you mean here!! Indeed, in the "detail" view the data is a bit on the right, which is not the case in Angular 2. Then I have no idea if that's normal or not with Bootstrap 4!
The ticket and commit message look good, and as I don't know if the result is "weird" or "normal", or what you are expecting, for me this looks OK.

**Comment by jdubois** [comment]
Looks like @ruddell did the fix, I'll merge this!

**Comment by pblanchardie** [comment]
Thanks!
