### ISSUE TITLE
Default application- Heroku & Postgres internal server error on registration

### ISSUE THREAD

**Issue by michaelkengel** [jhipster/generator-jhipster#5374]
##### **Overview of the issue**
Jhipster default application fails for registration, pops internal server error on Heroku. I found this issue after testing an existing application. To confirm the issue, I clean created and deployed a default application and am receiving the same error.

**Steps to replicate issue:**
Clean install new Jhipster app (Angular 1.~), no testing frameworks, HTTP session auth
<img width="1020" alt="setup" src="https://cloud.githubusercontent.com/assets/15005150/23612037/ca0bc208-0247-11e7-8cb4-de21d9be421b.png">
Open the app directory in intellij and let maven do its thing
Deploy to new heroku app in all default settings

<img width="594" alt="heroba" src="https://cloud.githubusercontent.com/assets/15005150/23612437/6ed134f2-0249-11e7-8aed-81143a3a789d.png">
... deploying...
<img width="515" alt="herokub" src="https://cloud.githubusercontent.com/assets/15005150/23612439/70c6b340-0249-11e7-95e1-5359500e7171.png">

Then, without touching anything else, attempt a registration

<img width="750" alt="ise" src="https://cloud.githubusercontent.com/assets/15005150/23612462/862da4b4-0249-11e7-9fb5-6e7e825a290b.png">

Responds with internal server error

**Here is the only log I can get from Heroku about the error:**
2017-03-06T13:46:04.520149+00:00 heroku[router]: at=info method=POST path="/api/register?cacheBuster=1488807963782" host=bugdemotestz.herokuapp.com request_id=818978c8-1d50-4c59-b551-a8f3570221aa fwd="98.217.172.153" dyno=web.1 connect=0ms service=739ms status=500 bytes=546

**Everything else is the default generated application**

##### **Browsers and Operating System**

I am running OS X, Chrome browser. Jhipster 4.0.7

**Comment by jdubois** [comment]
I'm sorry but you should follow the guidelines and give your full configuration, including how you configure your SMTP server.
Like this, I can't reproduce your issue - I'm doing this all the time and I confirm it's working.
