### ISSUE TITLE
node-sass

### ISSUE THREAD

**Issue by loverto** [jhipster/generator-jhipster#5382]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

Create a "monolithic" application without sass,phantomjs

##### **Motivation for or Use Case**

Create a "monolithic" application without sass

##### **Reproduce the error**

create a application

##### **Related issues**
[1/8] ⠁ node-sass: Downloading binary from https://github.com/sass/node
[8/8] ⠄ phantomjs-prebuilt: Receiving..

##### **JHipster Version(s)**

jhpster:4.0.7
node:6.10.0
yarn: v0.21.3
os:win10

##### **JHipster configuration**

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "uss",
    "packageName": "com.sx",
    "packageFolder": "com/sx",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "a1b9fa6fba7d10d262739bcefdac2d70518a502c",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ]
  }
}

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

@jkutner

**Comment by bastienmichaux** [comment]
I doubt this is an issue, since you do not have to use Sass or Phantom.js if you don't want to. You may be interested in creating a [submodule](https://jhipster.github.io/modules/creating-a-module/) if you want to prevent the generation of some resources for a particular project.

**Comment by gmarziou** [comment]
node-sass is not a direct dependency; it's a transitive dependency which is brought by bootstrap 4 and angular-cli.
I'm nto sure we can do somerthing to exclude it without broking build.

For phantomjs, it's different because it's used for frontend testing, so our build process requires it.

I'm closing the issue as I don't see how we could do differently. Feel free to try to get rid of them and propose a change if you succeed

**Comment by loverto** [comment]
Phantomjs is installed by yarn? Why is my phantomjs stuck  @gmarziou

**Comment by gmarziou** [comment]
Yes, something went wrong and now you need to cleanup your environment and re-install.
