### ISSUE TITLE
Login with Facebook with spring-social component

### ISSUE THREAD

**Issue by godbolerr** [jhipster/generator-jhipster#5383]
##### **Overview of the issue**

Login with facebook functionality uses spring-social-facebook module which has deprecated functionality and Facebook API invocation fails as there is no support for 'bio' attribute in the current Facebook API.

##### **Motivation for or Use Case**

Login with facebook fails to retrieve user information and sign-in can not happen.

##### **Reproduce the error**

You can try login with facebook by associating proper app id and app secret .

##### **Related issues**

None.

##### **Suggest a Fix**
Upgrade existing spring social from version  2.0.3.RELEASE  to version 3.0.0.M1

In pom.xml you will have to add the following repository entry as well to get the latest spring social.

<spring-social-facebook.version>3.0.0.M1</spring-social-facebook.version>

Note: this artifact it located at Alfresco Public repository (https://artifacts.alfresco.com/nexus/content/repositories/public/)

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This is a duplicate #5214

Please follow the guidelines next time, thanks!

**Comment by godbolerr** [comment]
Thanks.  I looked at issue and if the issue is closed, fix should be present in the latest version. Since it was not there, I suggested a fix.

I will look at the guidelines from next time.

**Comment by jdubois** [comment]
Yes, no worries :-)
