### ISSUE TITLE
Request to have option of saving images on file system

### ISSUE THREAD

**Issue by rakeshkalra1983** [jhipster/generator-jhipster#5386]
##### **Motivation for or Use Case**

While creating entity, we have option to have image type field which is saved as lob in database. But most of the time we like to save images on file system instead of database.

I do below steps to modify Jhipster generated entities a little and achieve the same:
* Create entity type with image type field and also have another field called as imageFileSystemPath
* I make lob field generated in entity for storing image data set as transient, and run liquibase:diff command again, to ensure the column is removed from database.
* When saving a new entity on server side: 
  * Generate a unique name using UUID for image.
  * Set imageFileSystemPath field as <some-static-path>/<entity-name>/<year>/<month>/<date>/UUID
  * Save data as image to file system in two sizes for thumbnail and original (name file as: UUID-thumbnail and UUID-original)
  * Save the entity.
(Kindly note that I might have forgot few of the steps above, but just thought to share roughly few of the things I do)

I do have to do certain changes to retrieve the images based on I want to keep images as public or images should be accessible based on role or to authenticated user.

I am not sure how much of this is achievable but thought to raise a request.

##### **JHipster Version(s)**

JHipster Version is 4.0.7

##### **JHipster configuration**

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This is a duplicate (please use the search box and it link it here).
We can't do this as this is against the 12 factors.
