### ISSUE TITLE
Gateway rate-limiting: drop the need for Cassandra

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5388]
The gateway application type uses Cassandra for doing rate limiting (it stores counters in Cassandra, like many competing solutions).
A better solution would be to use something like https://github.com/vladimir-bukhtoyarov/bucket4j and store the bucket in Hazelcast:

- No more need for Cassandra, so a much easier and lighter implementation
- The bucket system is also more precise than counting requests in Cassandra

**Comment by PierreBesson** [comment]
I'm just wondering, if using Hazelcast to store the counters, what would happen if the gateway restarts, will all the counters be reset ? In this case should we also run a standalone Hazelcast server for example using docker ?

**Comment by jdubois** [comment]
Yes they would be lost, unless you have a cluster, of course. So I wouldn't run an external Hazelcast server just for that - if you want to have high availability, run 2 gateways with an Hazelcast cluster.

**Comment by PierreBesson** [comment]
I guess it would be alright and I'm also thinking that it's a good idea to move to Hazelcast for this. However as I understand it, this means that the counters are no longer persisted. Should we configure a cron job to periodically save the hazelcast counter data to the SQL database ?

**Comment by deepu105** [comment]
I Think hazelcast has an option to periodically sync the data to file
system and restore from that.


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
I've had a look at other solutions, like https://github.com/bbeck/token-bucket but they are much more simple, and don't provide Hazelcast integration, so this is definitely the way to go.
Besides, the project is quite active actually, so that's really interesting for us.

I only have one simple issue, so I'm pinging @vladimir-bukhtoyarov (who is the author of bucket4j): for us, this needs to be delivered through Maven Central -> Vladimir, we currently do it and it's quite simple, would you consider doing it? We could help each other here, I'm sure.

**Comment by deepu105** [comment]
We have jcenter defined for our Gradle build but not in maven build. May be we could add it there as well

**Comment by jdubois** [comment]
@deepu105 I think this is because they need it for some specific Gradle plugins

My biggest issue is that this will cause a lot more configuration issues for people behind corporate proxies.

**Comment by deepu105** [comment]
Oh ya proxies are always issues

**Comment by jdubois** [comment]
I've assigned myself - I got it working at 90%

**Comment by vladimir-bukhtoyarov** [comment]
@jdubois I plan to start use Maven Central since version 1.4, this is issue to do this https://github.com/vladimir-bukhtoyarov/bucket4j/issues/23 

Unfortunately, I can not provide any estimate when 1.4.0 will be released, because I am very busy at current moment, most likely in 1-2 weeks, but something can go wrong and release can be postponed to better times. So, I recommend to just add jcenter repo to your pom.xml
```xml
<repository>
    <id>jcenter</id>
    <url>http://jcenter.bintray.com</url>
</repository>
```

**Comment by vladimir-bukhtoyarov** [comment]
According to persistence:

Bucket4j detects the situations when state of bucket was lost by any reason, and requires [to provide reaction](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/src/main/java/com/github/bucket4j/grid/RecoveryStrategy.java) which need to be applied in this case. I want to speculate that just reinitialization of bucket from original parameters will be most suitable for all cases.

**Comment by jdubois** [comment]
Thanks for your answers @vladimir-bukhtoyarov !!
Waiting for 1-2 weeks is perfectly OK for us: I need to finish my work and test it, and this is probably going to take something like 2-4 weeks (I'll also have some very busy weeks).

**Comment by delverdev** [comment]
Will it be available with monolith?

**Comment by jdubois** [comment]
@delverdev "it depends" :-)

- At the moment this is a Zuul filter, only working on the gateway
- The idea is that the gateway protects everything, so that's quite different from a monolith

-> so, first answer is "no"

Then, migrating the Zuul filter to a Servlet filter would be trivial!

**Comment by jdubois** [comment]
For everyone following this, I added [this comment](https://github.com/vladimir-bukhtoyarov/bucket4j/issues/26) on the Bucket4J bug tracker as I'm currently stucked with an implementation that doesn't look good to me. Help is welcome, of course.

**Comment by vladimir-bukhtoyarov** [comment]
@jdubois just follow to [this example](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/jcache-usage.md#example-1---limiting-access-to-http-server-by-ip-address)

**Comment by jdubois** [comment]
@vladimir-bukhtoyarov thanks! I'll work on this in the next 1 to 2 weeks

**Comment by jdubois** [comment]
I got it working, thanks @vladimir-bukhtoyarov !!!! I just need time to re-write the JHipster templates now.

**Comment by vladimir-bukhtoyarov** [comment]
Hello Guys, 
it is need to update to 2.0.1 because of [this serialization problem](https://github.com/vladimir-bukhtoyarov/bucket4j/issues/32).

**Comment by njnareshjoshi** [comment]
@jdubois I was also looking for the same thing because running Cassandra is becoming very heavy. But is this feature available in v4.4.1 and if not then how can I avail it?

**Comment by jdubois** [comment]
It's available, read the last release notes

**Comment by njnareshjoshi** [comment]
But there is no document on how to generate gateway without using Cassandra should I go with No for 
? (9/16) Which *type* of database would you like to use?

**Comment by jdubois** [comment]
You can choose the database you want there -> this is the ticket system, can you use Stackoverflow or Gitter for general questions?
