### ISSUE TITLE
gulp-angular-filesort says don't use it

### ISSUE THREAD

**Issue by NenadP** [jhipster/generator-jhipster#5394]
In Angular 1.x app, ```gulp-angular-filesort``` is used ( ```gulp/inject.js```):
``` .pipe(angularFilesort())``` 

On its github page it says:
> WARNING: Considering this for new apps? Don't!
> Use something like Browserify or Webpack instead!

Do you plan to follow their advice and  replace ```gulp-angular-filesort``` with something else in the near future?

- [+] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes, we migrated to Webpack for Angular 2, so we did follow that advice!

**Comment by NenadP** [comment]
Thanks @jdubois , If I might ask does that mean that Angular 1 in jHipster will probably be abandoned / deprecated?

**Comment by deepu105** [comment]
@NenadP it depends on where the Angular community is heading
