### ISSUE TITLE
JHIPSTER with firebird database

### ISSUE THREAD

**Issue by kyilintun2017** [jhipster/generator-jhipster#5395]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

I setup the url for firebird in application-dev.yml, application-prod.yml and pom.xml replace with mysql to firebird.

##### **Motivation for or Use Case**

It is my first time configuring firebird with jhipster.
Is it possible

##### **Reproduce the error**

NA

##### **Related issues**
No

##### **Suggest a Fix**

No Idea

##### **JHipster Version(s)**

JHipster 4

##### **JHipster configuration**

1.,monolithic application
2.blog
3.no
4.org.jhipster
5.JWT authentication
6.SQL(H2,Mysql......)
7.MySQL
8.MYSQL
9.ehcache
10.maven
11.social login
12.[beta] angular 2.x
13.no
14.no
15.Gatling , protractor

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

NA

##### **Browsers and Operating System**
Windows 10 Home

- [ *] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Probably, but this is not a bug. Please follow the guidelines, use Stackoverflow.
