### ISSUE TITLE
Live reload with Angular 2 using "yarn start" acting weird

### ISSUE THREAD

**Issue by jeansaigne** [jhipster/generator-jhipster#5396]
Using command "yarn start", live-reload is not working as expected.
On my Linux Mint i get no live-reload at all and on Windows 10 i get a weird behavior with live-reload, here i'm only going to explain the problem from Windows 10.

##### **Overview of the issue**

 Using IntelliJ, I can see in the console the recompiling when i make a change but when i look to the browser, i see a "Nothing changed", then when i continu adding changes and it effectively does apply it, it's not the latest changes i can see, it's the previous changes. So in order to see what i've done i need to first do what i want, then save in order to see the recompiling (with the "Nothing changed" appearing) and then add bullshit changes to see it really recompiling. It's the general case, but not so regular because sometimes i have to do it several times in order to see it applying in the browser. Sometimes i get stuck with webpack throwing an error about a chunk of code i just corrected, it's frustrating.

##### **Motivation for or Use Case**

While doing frontend developpement i want to see my changes applied directly without having to do "yarn start" every time.

##### **Reproduce the error**

I just followed [the official tutorial video](https://www.youtube.com/watch?v=XRREt1KB4Y8&ab_channel=MattRaible) to get started with a Monolitic application. The only change i made is choosing postgresql as database, adding websockets support and elasticsearch.

##### **Related issues**

I saw several people complaining about not having hot reload working correctly, mostly not understanding they had to use "yarn start" and one that ring my bell was the fact that webpack was maybe watching for too many files but nothing as weird as what i get.

##### **Suggest a Fix**

Sorry for my lazyness and lack of time i didn't try to fix it and expected it to just...work as easy peezy double wheezy as the get started.

##### **JHipster Version(s)**
I'm using generator-jhipster 4.0.7

##### **JHipster configuration**
[yo jhipster:info](http://pastebin.com/xdRNz4kt)

##### **Browsers and Operating System**

I get no livereload at all on Linux Mint 18, and this weird behavior on Windows 10. With both i tried on Google Chrome and Firefox, both up to date.

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
For Linux, maybe you have inotify settings too low, so it can't watch your files.
Try our devbox, that's the only way we can reproduce your issue. Here it depends on many other things, like OS settings, etc.

**Comment by gmarziou** [comment]
Have you configured IDEA to not use safe write as advised in [webpack dev server 's doc](https://webpack.github.io/docs/webpack-dev-server.html#working-with-editors-ides-supporting-safe-write)?

**Comment by AmbroseChase** [comment]
I have the same issue using Ubuntu 16.04. Yarn start is running, but the changes are not reflected in the browser. There's any solution?

**Comment by gmarziou** [comment]
Please don't comment on an old issue, open a new one with all required details.
