### ISSUE TITLE
JHipster with Angular 2+ fails to compile with Angular 4.0.0 RC3

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#5400]
I was able to upgrade to Angular 4.0.0 RC2 on my [ng-demo](https://github.com/mraible/ng-demo) project, so I figured I'd try it on [jhipster4-demo](https://github.com/mraible/jhipster4-demo). I used the following command to upgrade.

```
npm install @angular/{animations,common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router}@next @angular/material@latest typescript@latest --save --save-exact
```

From https://gist.github.com/StephenFluin/cbb5a3764a04de17abbf78ba0a33b53f

When I ran `mvn package -Pprod`, the build fails:

```
[INFO]   [14] delegated ./node_modules/style-loader/addStyles.js from dll-reference vendor 42 bytes {2} [not cacheable] [built]
[INFO]     + 194 hidden modules
[INFO]
[INFO] ERROR in [at-loader] node_modules/reflect-metadata/Reflect.ts:18:10
[INFO]     TS2457: Type alias name cannot be 'object'
[INFO]
[INFO] ERROR in [at-loader] src/test/javascript/spec/app/account/settings/settings.component.spec.ts:48:13
[INFO]     TS2322: Type 'AccountService' is not assignable to type 'MockAccountService'.
[INFO]   Property 'getSpy' is missing in type 'AccountService'.
[INFO]
[INFO] ERROR in [at-loader] src/test/javascript/spec/app/account/settings/settings.component.spec.ts:49:13
[INFO]     TS2322: Type 'Principal' is not assignable to type 'MockPrincipal'.
[INFO]   Property 'identitySpy' is missing in type 'Principal'.
[INFO] Child html-webpack-plugin for "index.html":
[INFO]     [./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html] ./~/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html 1.21 kB {0} [built]
[ERROR] error Command failed with exit code 2.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:24 min
[INFO] Finished at: 2017-03-10T13:22:52-07:00
[INFO] Final Memory: 26M/223M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:yarn (yarn install) on project blog: Failed to run task: 'yarn install --force' failed. (error code 1) -> [Help 1]
```

Shortly after doing this, I saw that [RC3 was released](https://twitter.com/ocombe/status/840303291527487489), so I tried again. The error is the same.

**Comment by gmarziou** [comment]
Any reason why you seem to mix npm and yarn?

**Comment by mraible** [comment]
No, I just copied the npm command from the gist and my project was created with yarn.

**Comment by deepu105** [comment]
Hi Guys, while we need to upgrade to latest releases I would rather wait for stable releases rather than spending our effort on RCs at the moment. We had lot of issues with ng 2 rc releases so lets upgrade once there is a stable ng4 release instead of doing multiple rc updates

**Comment by jdubois** [comment]
I agree with @deepu105 -> the Angular team has shown numerous times they produce very low quality RC releases.
BTW we should also upgrade our Angular CLI support: at work we have lost many, many days on this, as it has the same quality issues as Angular.

**Comment by deepu105** [comment]
Guys I'm closing this as we need to focus on getting our Angular2 support out of BETA fisrt. we can spend effort to upgrade to NG4 once its stable
