### ISSUE TITLE
JHipster with Angular 2 fails on different context path

### ISSUE THREAD

**Issue by andrea81it** [jhipster/generator-jhipster#5416]
Deploying an application generated with JHipster and Angular 2 fails deployng a generated WAR file.
According to documentation and what i found on Stackoverflow, i made the following changes on the generated project:

- added ```server: contextPath: /hellohipster``` in ```/src/main/resources/config/application-dev.yml```
- changed ```<base href="" />``` to ```<base href="/hellohipster" />``` in ```/src/main/webapp/index.html```

Running ```./mvnw``` the application starts correctly, but it's unusable due to 404 error on these requests:

```- localhost/:26 GET http://localhost:8080/global.bundle.js ```
```- localhost/:26 GET http://localhost:8080/manifest.bundle.js ```
```- localhost/:26 GET http://localhost:8080/polyfills.bundle.js ```
```- localhost/:26 GET http://localhost:8080/main.bundle.js ```
```- localhost/:26 GET http://localhost:8080/global.bundle.js ```

Please note that using ```hellohipster``` instead of ```/hellohipster``` in ```href``` attribute of ```base``` tag in ```index.html``` evrerything's ok except for the resulting context of the webapp: invoking ```http://localhost:8080/hellohipster``` the application redirects to ```http://localhost:8080/hellohipster/hellohipster#/``` but everything's working fine, including API.

Then i tried to deploy the same war on a standalone Tomcat using ```./mvnw -Pdev package```.
In ```target``` directory of my project.
Using the runnable WAR ```hellohipster-0.0.1-SNAPSHOT.war``` the resulting index page at ```http://localhost:8080/hellohipster``` isn't working.
It's not working because of missing js files imports in the source code:

```<script type="text/javascript" src="vendor.dll.js"></script>```
```<script type="text/javascript" src="manifest.bundle.js"></script>```
```<script type="text/javascript" src="polyfills.bundle.js"></script>```
```<script type="text/javascript" src="main.bundle.js"></script>```
```<script type="text/javascript" src="global.bundle.js"></script></body>```

Looking at the war content i wasn't able to find these js files.

##### **Reproduce the error**
Simply generate a new app with this configuration:
- Version:
```jhipster 4.0.8```

- Modules:
```generator-jhipster-material-0.0.0```
```JWT Auth```
```MySql```
```Angular2.x```
```LibSass```

Please note that the Spring layer (API) is working properly in each case above mentioned.

**Comment by ndywicki** [comment]
Try to change `<base href="/" />` to `<base href="./" />` (dot).
And keep `server: contextPath: /hellohipster` in `/src/main/resources/config/application-dev.yml`

Then go to http://localhost:8080/hellohipster it should be worked.
But not working on Dev with BrowserSyncPlugin (ie on proxy port 9000). Maybe also adapte the webpack conf.

Note: if you deploy the war on tomcat for example with prod profile, the context path by default will be the war name, so you only need to change the `base ref` to `<base href="./" />`

**Comment by jdubois** [comment]
I'm sorry but we don't support HTML 5 pushstate "out of the box", so this isn't a JHipster bug. It's perfectly fine to modify what is generated, and that's the whole point of the project, but we only accept bugs on our own code, not on what you did afterwards.
Have a look at https://jhipster.github.io/tips/010_tip_configuring_html_5_mode.html -> I don't think you configured the HTML 5 mode in Angular, and that's probably your issue.

FYI, we will probably support this in the near future, and definitely that's the way to go, it's just you're ahead of us for the moment.
