### ISSUE TITLE
webpack proxy doesn't include requests to gateway forwarded APIs

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#5417]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

in #5263 there was mentioned a issue I found already some time ago. When using our current microservice setup there is an issue, were requests to zuul routed microservice APIs don't work, as the paths are missing in webpack config

##### **Reproduce the error**

just generate a microservice application and try to open the UI on entity pages. All requests to `localhost:9000/<service-name>` are running into a 404.

##### **Related issues**

was mentioned in #5263 

##### **Suggest a Fix**

when creating entities, the sub-generator should add the paths here: https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/webpack/_webpack.dev.js#L24

##### **JHipster Version(s)**

4.0.8

I can PR a solution for this

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
- I confirm the issue
- That's really a huge, huge issue for me, I don't undestand how we missed that (it was probably working before, and we broke this at some point)
- Sorry @jnuc093 @cagecat we had so many people not running `yarn start` that at some point I was closing all related issues
- Thanks @xetys for seeing this -> yes please do a PR if you have time

-> for me this is very important, so I'll release a new version ASAP (but ASAP can take some time as we just had a big migration to Yeoman 1.0, depends on how stable our master branch is at the moment)

**Comment by xetys** [comment]
my theory is, it never worked, but the workaround is so quick so I don't even think about that
