### ISSUE TITLE
Cannot deploy microservice with hazelcast into docker swarm

### ISSUE THREAD

**Issue by lokinell** [jhipster/generator-jhipster#5419]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

When I deploy my application by docker swarm. My application cannot start successfully. 
It throw bellow exception.

I guess it is caused by hazelcast with swarm. Because I can start it successfully by docker compose. And I find the issue in hazelcast [https://github.com/hazelcast/hazelcast/issues/9963](url)

pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:92)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:101)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:85)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:103)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:249)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:992)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:966)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:472)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	... 18 common frames omitted
pdas_studio-app.1.pl6gn8zwprad@slave01    | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cache.interceptor.BeanFactoryCacheOperationSourceAdvisor]: Factory method 'cacheAdvisor' threw exception; nested exception is java.lang.NullPointerException
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	... 34 common frames omitted
pdas_studio-app.1.pl6gn8zwprad@slave01    | Caused by: java.lang.NullPointerException: null
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.cache.annotation.ProxyCachingConfiguration.cacheAdvisor(ProxyCachingConfiguration.java:47)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.cache.annotation.ProxyCachingConfiguration$$EnhancerBySpringCGLIB$$dbe97398.CGLIB$cacheAdvisor$0(<generated>)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.cache.annotation.ProxyCachingConfiguration$$EnhancerBySpringCGLIB$$dbe97398$$FastClassBySpringCGLIB$$da1ace2d.invoke(<generated>)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.cache.annotation.ProxyCachingConfiguration$$EnhancerBySpringCGLIB$$dbe97398.cacheAdvisor(<generated>)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at sun.reflect.GeneratedMethodAccessor305.invoke(Unknown Source)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at java.lang.reflect.Method.invoke(Method.java:498)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
pdas_studio-app.1.pl6gn8zwprad@slave01    | 	... 35 common frames omitted
pdas_studio-app.1.pl6gn8zwprad@slave01    |
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
