### ISSUE TITLE
Add the cool webpack dev server dashboard

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#5420]
Integrate https://github.com/FormidableLabs/webpack-dashboard for Angular 2

![image](https://cloud.githubusercontent.com/assets/1107223/23949229/c29a2370-0986-11e7-8cbd-41df0353bdd5.png)

**Comment by jdubois** [comment]
Yes I know it and it's cool, but I'm not sure it works well on all terminals... Maybe we could have it by default, but add a new goal that does the current `yarn start`, as a fallback for people who can't use it.

**Comment by jdubois** [comment]
See my comment https://github.com/jhipster/generator-jhipster/pull/5421#issuecomment-291237632 -> if you have something that works well, we could do it, but here that looks like a lot of trouble, and it's not really doing much except for the "wow" effect.
I'd rather have the TypeScript compilation working well in IDEA, that's way more important.
