### ISSUE TITLE
Error creating bean with name 'mongobee'

### ISSUE THREAD

**Issue by zgding1979** [jhipster/generator-jhipster#5424]
----- first step by step  ---
? (1/15) Which *type* of application would you like to create? Microservice application
? (2/15) What is the base name of your application? crm
? (3/15) Would you like to install other generators from the JHipster Marketplace? No
? (4/15) As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8083
? (5/15) What is your default Java package name? com.zgding.crm
? (6/15) Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? (7/15) Which Service Discovery and Configuration solution would you like to use? JHipster Registry (using Eureka and Spring Cloud Config)
? (8/15) Which *type* of database would you like to use? MongoDB
? (9/15) Would you like to use Maven or Gradle for building the backend? Maven
? (10/15) Which other technologies would you like to use? [BETA] Asynchronous messages using Apache Kafka
? (11/15) Would you like to enable internationalization support? No
? (12/15) Besides JUnit and Karma, which testing frameworks would you like to use? Gatling

---the **# ERROR** is  this ::: ----
org.springframework.beans.factory.BeanCreationException: **Error creating bean with name 'mongobee' defined in class path resource [com/zgding/crm/config/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches** ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]

---v4.0.8-----

**Comment by gmarziou** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by deepu105** [comment]
The info you provided is not useful for us. Please read the content shown when you open a new issue and follow it and provide the details asked for
