### ISSUE TITLE
Support database reserved keywords

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5427]
Reading this https://forum.hibernate.org/viewtopic.php?f=1&t=1044123&p=2491803#p2491803

I think we could support database reserved keywords in the jhipster-core (cc @MathieuAA )

**Comment by MathieuAA** [comment]
Indeed

Le 17 mars 2017 07:29:22 GMT+01:00, Julien Dubois <notifications@github.com> a écrit :
>Reading this
>https://forum.hibernate.org/viewtopic.php?f=1&t=1044123&p=2491803#p2491803
>
>I think we could support database reserved keywords in the
>jhipster-core (cc @MathieuAA )
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/5427

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
We **do** support [reserved keywords](https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/reserved_keywords.js). The link you're referring to is about someone who used a forbidden keyword but found a workaround. Supporting this wouldn't be too difficult.

**Comment by jdubois** [comment]
Yes there is a misunderstanding : I would like JHipster to accept database
reserved keywords (like 'order') with this setup.

Le 17 mars 2017 9:05 AM, "Mathieu ABOU-AICHI" <notifications@github.com> a
écrit :

We *do* support reserved keywords
<https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/reserved_keywords.js>.
The link you're referring to is about someone who used a forbidden keyword
but found a workaround. Supporting this wouldn't be too difficult.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5427#issuecomment-287291586>,
or mute the thread

**Comment by MathieuAA** [comment]
Ah =) f the check returns false (the entity/field/etc) can't be named 'RESERVED_KEYWORD' then we use this trick to allow it. I'll create an issue on the JHipster-Core issue tracker for this.

**Comment by jdubois** [comment]
I got this working, let me commit this in the next few days.

**Comment by MathieuAA** [comment]
Roger that

Le 24 mars 2017 00:01:44 GMT+01:00, Julien Dubois <notifications@github.com> a écrit :
>I got this working, let me commit this in the next few days.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/5427#issuecomment-288886435

-- 
Mathieu ABOU-AICHI

**Comment by jdubois** [comment]
@MathieuAA I did the merge+commit, can we do a new release? We'll need to see with the NPM organization, also

**Comment by MathieuAA** [comment]
As someone once said, yes we can. When do you want to release the new version? 

Le 24 mars 2017 10:42:34 GMT+01:00, Julien Dubois <notifications@github.com> a écrit :
>@MathieuAA I did the merge+commit, can we do a new release? We'll need
>to see with the NPM organization, also
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/5427#issuecomment-288976620

-- 
Mathieu ABOU-AICHI

**Comment by jdubois** [comment]
Hang on, I think I did a mistake. I'm not sure my code is portable across all databases, let me check.

**Comment by MathieuAA** [comment]
Ooops :)

**Comment by jdubois** [comment]
OK, so this definitely sucks big time... Look for `liquibase.database.core.HsqlDatabase` -> so Liquibase has its own list of reserved keywords. For example, `FROM` is a reserved keyword (this is what I used in my tests), but `LABEL` is not. Issue is, `LABEL` is a reserved keyword in Oracle, so this isn't portable.
And of course, as soon as you use quotes, this all becomes case-sensitive, so when Liquibase thinks there is a reserved keyword, it must be in uppercase everywhere...

If we want something portable (we develop on H2, and run in production on Oracle), we need to have:

- The same reserved keywords in all databases, for Liquibase (`LABEL` should be in uppercase everywhere)
- The same reserved keywords in JHipster as in Liquibase (so we add quotes in the `@Column` annotations correctly)

-> this looks very complex to me.... An easier solution is just to have a prefix, what do you think of this? Each reserved keyword is prefixed by "JHI_", like we already do for our own tables: `FROM` becomes `JHI_FROM`. This solves everything, and makes it clear this was modified by JHipster.

Is everyone OK with that?

**Comment by tezcane** [comment]
"JHI_" looks great.

**Comment by MathieuAA** [comment]
Makes sense. +1

**Comment by deepu105** [comment]
Yes and we can use the jhiPrefix param so that people can override it if
required


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
@deepu105 that's a very good idea, but currently this is hard-coded for table names, for example the `jhi_user` table, so for consistency I'd rather keep it that way now.
By the way, it is in lower case, so I'm keeping it `jhi_`, also for consistency.
