### ISSUE TITLE
Lower Eureka client timeouts

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5430]
The default Eureka timeouts are quite high, and we already lower some of them (in Zuul and Hystrix).

So when doing microservices, adding/removing servers take a bit too long. My proposal is to have:

    eureka:
        client:
            registryFetchIntervalSeconds: 10
            instanceInfoReplicationIntervalSeconds: 10
        instance:
            appname: cart
            leaseRenewalIntervalInSeconds: 5
            leaseExpirationDurationInSeconds: 10

Besides, I see that the Eureka configuration doesn't use our correct "dasherized" naming, by the camel case one, so I would rename them, for example `timeoutInMilliseconds`-> `timeout-in-milliseconds`

**Comment by jdubois** [comment]
While renaming the properties to use the "dasherized" names, as mentioned by https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html , I discovered two of them do not work `eureka.client.service-url.defaultZone` and `eureka.instance.instanceId`.

For me this is clearly a bug in Spring Boot: I'll try to do a ticket and link it here, but it's a very strange issue and I'm not sure what I can tell them.

I'll still do the refactoring but this worries me, as there could be more of those!

**Comment by jdubois** [comment]
More properties can't be renamed.... Now I have some 401 errors with the registry: so the Spring Boot documentation is clearly wrong, and also those properties are not correctly validated by Spring Boot (there should be an error if there is a property with a wrong name, this is supposed to be checked!).

So now I'm sure if those should be refactored, this is quite risky.

**Comment by pascalgrimaud** [comment]
@jdubois : about 401, is it this error ?
```
ERROR 28981 --- [get_localhost-0] c.n.e.cluster.ReplicationTaskProcessor   : Batch update failure with HTTP status code 401; discarding 2 replication tasks
```

If yes, I mentionned it there: https://github.com/jhipster/generator-jhipster/issues/5240#issuecomment-280798004 (with link to another ticket)

**Comment by jdubois** [comment]
@pascalgrimaud yes, looks like it.... This all looks super buggy: Spring Boot property that are not recognized, 401 errors... What's happening?
I also found out that they modified the way Eureka/Ribbon work (not the round-robin algorithm anymore, not the same way to remove a server with the "ping" method...) and that causes a lot of errors we didn't have before. Not satisfied with all of this!

**Comment by jdubois** [comment]
Oh, and now I'm really lucky: the error in the Registry comes from the same bug as in the applications, using `eureka.client.service-url.default-zone` doesn't work, you need to use `eureka.client.service-url.defaultZone`. Quite incredible!

I guess this is because the method is in fact `setServiceUrl(Map<String, String> serviceUrl)`, and then the person who coded this isn't using the relaxed properties from Spring Boot. Anyway, we got the solution!

**Comment by jdubois** [comment]
@JulienMrgrd be careful in your JHipster Registry branch, you'll need to do the set up above, with `defaultZone`
