### ISSUE TITLE
use ts compiler option noUnusedLocals and remove unused imports

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#5434]
##### **Overview of the issue**

At the moment there is a lot of unused imports in *.ts files.

##### **Motivation for or Use Case**

If examining the source code, it's confusing, why are these imports there.

##### **Reproduce the error**

Two ways to see unused imports:
* First option: modify `tslint.json`, add line:
```
    "no-unused-variable": true,
```
* Second option: modify `tsconfig.json`, add line:
```
        "noUnusedLocals": true,
```

Using `no-unused-variable` produces warnings, but is deprecated.  
`noUnusedLocals` produces errors. So if with some configuration remain unused locals then build fails after project generation.

##### **Suggest a Fix**

Use compilerOption `"noUnusedLocals": true` in `tsconfig.json` and with this help remove unused locals from *.ts files.

##### **JHipster Version(s)**

Current master.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
`"noUnusedLocals": true,` in `tsconfig.json` gives false errors for dependency injection in constructors.  
So suggested fix by me will not work correctly.  
I'll do PR which removes unused imports what I found.

**Comment by ramsunvtech** [comment]
Still this issue is exist in TypeScript - 2.5.2
