### ISSUE TITLE
Add a jhipster:client prompt when auth is uaa

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#5451]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

When you I try to create a client for an existing microservice with an authentication provided by a Jhipster uaa server, the generation fail because I can't provide the uaa application base name.

##### **Motivation for or Use Case**

I work in a team where back and front application are splitted to ease their dev./deployment/scaling. When I use a microservice architecture, I want to generate the back and front separately.

##### **Reproduce the error**
Simply run the following command
`yo jhipster:client --auth uaa`

For instance:

```
yo jhipster:client --auth uaa
? (1/4) What is the base name of your application? foo
? (2/4) Which *Framework* would you like to use for the client? [BETA] Angular 2.x
? (3/4) Would you like to use the LibSass stylesheet preprocessor for your CSS? No
? (4/4) Would you like to enable internationalization support? Yes
? Please choose the native language of the application? English
? Please choose additional languages to install French

Installing languages: en, fr for client
Error jhipster:client --auth uaa

ERROR! Copying template angular/src/main/webapp/app/account/activate/_activate.service.ts failed. [ReferenceError: /usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular/src/main/webapp/app/account/activate/_activate.service.ts:14
    12|         params.set('key', key);
    13|
 >> 14|         return this.http.get(<% if (authenticationType === 'uaa') { %>'<%= uaaBaseName.toLowerCase() %>/api/activate'<%} else { %>'api/activate'<% } %>, {
    15|             search: params
    16|         }).map((res: Response) => res);
    17|     }

uaaBaseName is not defined]
```

##### **Suggest a Fix**
The easiest one would be to prompt for the uaa basename when the `auth==uaa` 

##### **JHipster Version(s)**

`4.1.0`

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by xetys** [comment]
I will take a look on this one

**Comment by danielpetisme** [comment]
I also noticed that the uaa base name is hard coded in `webpack.dev.js`
https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/webpack/_webpack.dev.js#L24

**Comment by xetys** [comment]
oh...thanks a lot....this shows well, that we are consistently testing with that name only 😨

**Comment by danielpetisme** [comment]
Great job!
Thanks @xetys for the reactivity!
