### ISSUE TITLE
"webpack/webpack.vendor.js" as "SystemJs.config.js"

### ISSUE THREAD

**Issue by MorlaRamakrishna** [jhipster/generator-jhipster#5461]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

Can we use "webpack/webpack.vendor.js" as "SystemJs.config.js". could you guide me how to add plugins to Jhipster Angular2 application

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Sorry, we use Webpack, not System.js.
And this is not a support forum, this is the bug tracker, please use StackOverflow instead.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
