### ISSUE TITLE
Angular2 Material Integration

### ISSUE THREAD

**Issue by premkumarsp** [jhipster/generator-jhipster#5463]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

I have followed so many video tutorials. But it couldn't help me.
Could you help me how to integrate Angular2 Material for Jhipster Angualr2 project.

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I closed your ticket because it is a bug tracker and not a support channel.
StackOverFlow is the right place for your need.
