### ISSUE TITLE
Error in Mapper

### ISSUE THREAD

**Issue by Joseluisce2011** [jhipster/generator-jhipster#5464]
Hi, I'm new to JHipster, just a couple of weeks, to see if you can help me. I have imported a .jh file for my project. When I run my project I get the following:

`"C:\Program Files\Java\jdk1.8.0_121\bin\java" -Dspring.output.ansi.enabled=always -Didea.launcher.port=7532 "-Didea.launcher.bin.path=C:\Users\Jose Luis\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\163.13906.18\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_121\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\rt.jar;C:\Users\Jose Luis\miaplicacion2\target\classes;C:\Users\Jose Luis\.m2\repository\io\github\jhipster\jhipster\1.1.0\jhipster-1.1.0.jar;C:\Users\Jose Luis\.m2\repository\io\dropwizard\metrics\metrics-core\3.1.3\metrics-core-3.1.3.jar;C:\Users\Jose Luis\.m2\repository\org\slf4j\slf4j-api\1.7.24\slf4j-api-1.7.24.jar;C:\Users\Jose Luis\.m2\repository\io\dropwizard\metrics\metrics-annotation\3.1.3\metrics-annotation-3.1.3.jar;C:\Users\Jose Luis\.m2\repository\io\dropwizard\metrics\metrics-json\3.1.3\metrics-json-3.1.3.jar;C:\Users\Jose Luis\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.8.7\jackson-databind-2.8.7.jar;C:\Users\Jose Luis\.m2\repository\io\dropwizard\metrics\metrics-jvm\3.1.3\metrics-jvm-3.1.3.jar;C:\Users\Jose Luis\.m2\repository\io\dropwizard\metrics\metrics-servlet\3.1.3\metrics-servlet-3.1.3.jar;C:\Users\Jose Luis\.m2\repository\io\dropwizard\metrics\metrics-servlets\3.1.3\metrics-servlets-3.1.3.jar;C:\Users\Jose Luis\.m2\repository\io\dropwizard\metrics\metrics-healthchecks\3.1.3\metrics-healthchecks-3.1.3.jar;C:\Users\Jose Luis\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-hibernate5\2.8.7\jackson-datatype-hibernate5-2.8.7.jar;C:\Users\Jose Luis\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.8.7\jackson-core-2.8.7.jar;C:\Users\Jose Luis\.m2\repository\javax\transaction\jta\1.1\jta-1.1.jar;C:\Users\Jose Luis\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-hppc\2.8.7\jackson-datatype-hppc-2.8.7.jar;C:\Users\Jose Luis\.m2\repository\com\carrotsearch\hppc\0.7.1\hppc-0.7.1.jar;C:\Users\Jose Luis\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.8.7\jackson-datatype-jsr310-2.8.7.jar;C:\Users\Jose Luis\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.8.0\jackson-annotations-2.8.0.jar;C:\Users\Jose Luis\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-json-org\2.8.7\jackson-datatype-json-org-2.8.7.jar;C:\Users\Jose Luis\.m2\repository\org\apache\geronimo\bundles\json\20090211_1\json-20090211_1.jar;C:\Users\Jose Luis\.m2\repository\com\h2database\h2\1.4.193\h2-1.4.193.jar;C:\Users\Jose Luis\.m2\repository\io\springfox\springfox-swagger2\2.6.1\springfox-swagger2-2.6.1.jar;C:\Users\Jose Luis\.m2\repository\io\swagger\swagger-annotations\1.5.10\swagger-annotations-1.5.10.jar;C:\Users\Jose Luis\.m2\repository\io\swagger\swagger-models\1.5.10\swagger-models-1.5.10.jar;C:\Users\Jose Luis\.m2\repository\io\springfox\springfox-spi\2.6.1\springfox-spi-2.6.1.jar;C:\Users\Jose Luis\.m2\repository\io\springfox\springfox-core\2.6.1\springfox-core-2.6.1.jar;C:\Users\Jose Luis\.m2\repository\io\springfox\springfox-schema\2.6.1\springfox-schema-2.6.1.jar;C:\Users\Jose Luis\.m2\repository\io\springfox\springfox-swagger-common\2.6.1\springfox-swagger-common-2.6.1.jar;C:\Users\Jose Luis\.m2\repository\io\springfox\springfox-spring-web\2.6.1\springfox-spring-web-2.6.1.jar;C:\Users\Jose Luis\.m2\repository\com\google\guava\guava\18.0\guava-18.0.jar;C:\Users\Jose Luis\.m2\repository\com\fasterxml\classmate\1.3.3\classmate-1.3.3.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\plugin\spring-plugin-core\1.2.0.RELEASE\spring-plugin-core-1.2.0.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\plugin\spring-plugin-metadata\1.2.0.RELEASE\spring-plugin-metadata-1.2.0.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\io\springfox\springfox-bean-validators\2.6.1\springfox-bean-validators-2.6.1.jar;C:\Users\Jose Luis\.m2\repository\com\mattbertolini\liquibase-slf4j\2.0.0\liquibase-slf4j-2.0.0.jar;C:\Users\Jose Luis\.m2\repository\com\ryantenney\metrics\metrics-spring\3.1.3\metrics-spring-3.1.3.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-core\4.3.7.RELEASE\spring-core-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-beans\4.3.7.RELEASE\spring-beans-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-aop\4.3.7.RELEASE\spring-aop-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\com\zaxxer\HikariCP\2.6.0\HikariCP-2.6.0.jar;C:\Users\Jose Luis\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\Jose Luis\.m2\repository\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\Jose Luis\.m2\repository\com\jcraft\jzlib\1.1.3\jzlib-1.1.3.jar;C:\Users\Jose Luis\.m2\repository\javax\cache\cache-api\1.0.0\cache-api-1.0.0.jar;C:\Users\Jose Luis\.m2\repository\mysql\mysql-connector-java\5.1.41\mysql-connector-java-5.1.41.jar;C:\Users\Jose Luis\.m2\repository\org\ehcache\ehcache\3.2.1\ehcache-3.2.1.jar;C:\Users\Jose Luis\.m2\repository\org\hibernate\hibernate-jcache\5.2.8.Final\hibernate-jcache-5.2.8.Final.jar;C:\Users\Jose Luis\.m2\repository\org\jboss\logging\jboss-logging\3.3.0.Final\jboss-logging-3.3.0.Final.jar;C:\Users\Jose Luis\.m2\repository\org\hibernate\hibernate-core\5.2.8.Final\hibernate-core-5.2.8.Final.jar;C:\Users\Jose Luis\.m2\repository\org\hibernate\javax\persistence\hibernate-jpa-2.1-api\1.0.0.Final\hibernate-jpa-2.1-api-1.0.0.Final.jar;C:\Users\Jose Luis\.m2\repository\org\javassist\javassist\3.21.0-GA\javassist-3.21.0-GA.jar;C:\Users\Jose Luis\.m2\repository\antlr\antlr\2.7.7\antlr-2.7.7.jar;C:\Users\Jose Luis\.m2\repository\org\jboss\spec\javax\transaction\jboss-transaction-api_1.2_spec\1.0.1.Final\jboss-transaction-api_1.2_spec-1.0.1.Final.jar;C:\Users\Jose Luis\.m2\repository\org\jboss\jandex\2.0.3.Final\jandex-2.0.3.Final.jar;C:\Users\Jose Luis\.m2\repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;C:\Users\Jose Luis\.m2\repository\org\hibernate\common\hibernate-commons-annotations\5.0.1.Final\hibernate-commons-annotations-5.0.1.Final.jar;C:\Users\Jose Luis\.m2\repository\org\hibernate\hibernate-envers\5.2.8.Final\hibernate-envers-5.2.8.Final.jar;C:\Users\Jose Luis\.m2\repository\org\hibernate\hibernate-validator\5.3.4.Final\hibernate-validator-5.3.4.Final.jar;C:\Users\Jose Luis\.m2\repository\javax\validation\validation-api\1.1.0.Final\validation-api-1.1.0.Final.jar;C:\Users\Jose Luis\.m2\repository\org\liquibase\liquibase-core\3.5.3\liquibase-core-3.5.3.jar;C:\Users\Jose Luis\.m2\repository\org\yaml\snakeyaml\1.17\snakeyaml-1.17.jar;C:\Users\Jose Luis\.m2\repository\org\mapstruct\mapstruct-jdk8\1.1.0.Final\mapstruct-jdk8-1.1.0.Final.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-context-support\4.3.7.RELEASE\spring-context-support-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-context\4.3.7.RELEASE\spring-context-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-expression\4.3.7.RELEASE\spring-expression-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-actuator\1.5.2.RELEASE\spring-boot-actuator-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot\1.5.2.RELEASE\spring-boot-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-autoconfigure\1.5.2.RELEASE\spring-boot-autoconfigure-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-configuration-processor\1.5.2.RELEASE\spring-boot-configuration-processor-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\com\vaadin\external\google\android-json\0.0.20131108.vaadin1\android-json-0.0.20131108.vaadin1.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-loader-tools\1.5.2.RELEASE\spring-boot-loader-tools-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter-aop\1.5.2.RELEASE\spring-boot-starter-aop-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter\1.5.2.RELEASE\spring-boot-starter-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\aspectj\aspectjweaver\1.8.9\aspectjweaver-1.8.9.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter-data-jpa\1.5.2.RELEASE\spring-boot-starter-data-jpa-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter-jdbc\1.5.2.RELEASE\spring-boot-starter-jdbc-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\apache\tomcat\tomcat-jdbc\8.5.11\tomcat-jdbc-8.5.11.jar;C:\Users\Jose Luis\.m2\repository\org\apache\tomcat\tomcat-juli\8.5.11\tomcat-juli-8.5.11.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-jdbc\4.3.7.RELEASE\spring-jdbc-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\hibernate\hibernate-entitymanager\5.2.8.Final\hibernate-entitymanager-5.2.8.Final.jar;C:\Users\Jose Luis\.m2\repository\net\bytebuddy\byte-buddy\1.6.6\byte-buddy-1.6.6.jar;C:\Users\Jose Luis\.m2\repository\javax\transaction\javax.transaction-api\1.2\javax.transaction-api-1.2.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\data\spring-data-jpa\1.11.1.RELEASE\spring-data-jpa-1.11.1.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-orm\4.3.7.RELEASE\spring-orm-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-tx\4.3.7.RELEASE\spring-tx-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-aspects\4.3.7.RELEASE\spring-aspects-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter-logging\1.5.2.RELEASE\spring-boot-starter-logging-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\ch\qos\logback\logback-classic\1.1.11\logback-classic-1.1.11.jar;C:\Users\Jose Luis\.m2\repository\ch\qos\logback\logback-core\1.1.11\logback-core-1.1.11.jar;C:\Users\Jose Luis\.m2\repository\org\slf4j\jcl-over-slf4j\1.7.24\jcl-over-slf4j-1.7.24.jar;C:\Users\Jose Luis\.m2\repository\org\slf4j\jul-to-slf4j\1.7.24\jul-to-slf4j-1.7.24.jar;C:\Users\Jose Luis\.m2\repository\org\slf4j\log4j-over-slf4j\1.7.24\log4j-over-slf4j-1.7.24.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter-mail\1.5.2.RELEASE\spring-boot-starter-mail-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\com\sun\mail\javax.mail\1.5.6\javax.mail-1.5.6.jar;C:\Users\Jose Luis\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter-security\1.5.2.RELEASE\spring-boot-starter-security-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\security\spring-security-config\4.2.2.RELEASE\spring-security-config-4.2.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\security\spring-security-web\4.2.2.RELEASE\spring-security-web-4.2.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\security\spring-security-core\4.2.2.RELEASE\spring-security-core-4.2.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter-thymeleaf\1.5.2.RELEASE\spring-boot-starter-thymeleaf-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\thymeleaf\thymeleaf-spring4\2.1.5.RELEASE\thymeleaf-spring4-2.1.5.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\thymeleaf\thymeleaf\2.1.5.RELEASE\thymeleaf-2.1.5.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\ognl\ognl\3.0.8\ognl-3.0.8.jar;C:\Users\Jose Luis\.m2\repository\org\unbescape\unbescape\1.1.0.RELEASE\unbescape-1.1.0.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\nz\net\ultraq\thymeleaf\thymeleaf-layout-dialect\1.4.0\thymeleaf-layout-dialect-1.4.0.jar;C:\Users\Jose Luis\.m2\repository\org\codehaus\groovy\groovy\2.4.9\groovy-2.4.9.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter-web\1.5.2.RELEASE\spring-boot-starter-web-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-web\4.3.7.RELEASE\spring-web-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\spring-webmvc\4.3.7.RELEASE\spring-webmvc-4.3.7.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\net\logstash\logback\logstash-logback-encoder\4.8\logstash-logback-encoder-4.8.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter-cloud-connectors\1.5.2.RELEASE\spring-boot-starter-cloud-connectors-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\cloud\spring-cloud-spring-service-connector\1.2.3.RELEASE\spring-cloud-spring-service-connector-1.2.3.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\cloud\spring-cloud-core\1.2.3.RELEASE\spring-cloud-core-1.2.3.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\cloud\spring-cloud-cloudfoundry-connector\1.2.3.RELEASE\spring-cloud-cloudfoundry-connector-1.2.3.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\cloud\spring-cloud-heroku-connector\1.2.3.RELEASE\spring-cloud-heroku-connector-1.2.3.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\cloud\spring-cloud-localconfig-connector\1.2.3.RELEASE\spring-cloud-localconfig-connector-1.2.3.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\security\spring-security-data\4.2.2.RELEASE\spring-security-data-4.2.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\data\spring-data-commons\1.13.1.RELEASE\spring-data-commons-1.13.1.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-starter-undertow\1.5.2.RELEASE\spring-boot-starter-undertow-1.5.2.RELEASE.jar;C:\Users\Jose Luis\.m2\repository\io\undertow\undertow-core\1.4.10.Final\undertow-core-1.4.10.Final.jar;C:\Users\Jose Luis\.m2\repository\org\jboss\xnio\xnio-api\3.3.6.Final\xnio-api-3.3.6.Final.jar;C:\Users\Jose Luis\.m2\repository\org\jboss\xnio\xnio-nio\3.3.6.Final\xnio-nio-3.3.6.Final.jar;C:\Users\Jose Luis\.m2\repository\io\undertow\undertow-servlet\1.4.10.Final\undertow-servlet-1.4.10.Final.jar;C:\Users\Jose Luis\.m2\repository\org\jboss\spec\javax\annotation\jboss-annotations-api_1.2_spec\1.0.0.Final\jboss-annotations-api_1.2_spec-1.0.0.Final.jar;C:\Users\Jose Luis\.m2\repository\io\undertow\undertow-websockets-jsr\1.4.10.Final\undertow-websockets-jsr-1.4.10.Final.jar;C:\Users\Jose Luis\.m2\repository\org\jboss\spec\javax\websocket\jboss-websocket-api_1.1_spec\1.1.0.Final\jboss-websocket-api_1.1_spec-1.1.0.Final.jar;C:\Users\Jose Luis\.m2\repository\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;C:\Users\Jose Luis\.m2\repository\org\glassfish\javax.el\3.0.0\javax.el-3.0.0.jar;C:\Users\Jose Luis\.m2\repository\org\springframework\boot\spring-boot-devtools\1.5.2.RELEASE\spring-boot-devtools-1.5.2.RELEASE.jar;C:\Users\Jose Luis\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\163.13906.18\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain com.miaplicacion2.jhipster.Miaplicacion2App
08:45:30.425 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Included patterns for restart : []
08:45:30.430 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Excluded patterns for restart : [/spring-boot-starter/target/classes/, /spring-boot-autoconfigure/target/classes/, /spring-boot-starter-[\w-]+/, /spring-boot/target/classes/, /spring-boot-actuator/target/classes/, /spring-boot-devtools/target/classes/]
08:45:30.430 [main] DEBUG org.springframework.boot.devtools.restart.ChangeableUrls - Matching URLs for reloading : [file:/C:/Users/Jose%20Luis/miaplicacion2/target/classes/]

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

:: JHipster 🤓  :: Running Spring Boot 1.5.2.RELEASE ::
:: http://jhipster.github.io ::

2017-03-22 08:45:33.780  INFO 3972 --- [  restartedMain] c.m.jhipster.Miaplicacion2App            : Starting Miaplicacion2App on ETDA-20 with PID 3972 (started by Jose Luis in C:\Users\Jose Luis\miaplicacion2)
2017-03-22 08:45:33.782 DEBUG 3972 --- [  restartedMain] c.m.jhipster.Miaplicacion2App            : Running with Spring Boot v1.5.2.RELEASE, Spring v4.3.7.RELEASE
2017-03-22 08:45:33.790  INFO 3972 --- [  restartedMain] c.m.jhipster.Miaplicacion2App            : The following profiles are active: swagger,dev
2017-03-22 08:45:34.618 DEBUG 3972 --- [kground-preinit] org.jboss.logging                        : Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
2017-03-22 08:45:47.115 DEBUG 3972 --- [  restartedMain] c.m.jhipster.config.AsyncConfiguration   : Creating Async Task Executor
2017-03-22 08:45:50.378 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.jhipster.domain.User           : Initialize successful.
2017-03-22 08:45:50.413 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.jhipster.domain.Authority      : Initialize successful.
2017-03-22 08:45:50.478 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.j.domain.User.authorities      : Initialize successful.
2017-03-22 08:45:50.490 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.j.domain.PersistentToken       : Initialize successful.
2017-03-22 08:45:50.499 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.j.d.User.persistentTokens      : Initialize successful.
2017-03-22 08:45:50.508 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.jhipster.domain.Noticia        : Initialize successful.
2017-03-22 08:45:50.518 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.jhipster.domain.Usuario        : Initialize successful.
2017-03-22 08:45:50.746 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.j.domain.Usuario.noticias      : Initialize successful.
2017-03-22 08:45:52.818 DEBUG 3972 --- [  restartedMain] c.m.j.config.MetricsConfiguration        : Registering JVM gauges
2017-03-22 08:45:53.498 DEBUG 3972 --- [  restartedMain] c.m.j.config.MetricsConfiguration        : Monitoring the datasource
2017-03-22 08:45:53.499 DEBUG 3972 --- [  restartedMain] c.m.j.config.MetricsConfiguration        : Initializing Metrics JMX reporting
2017-03-22 08:46:01.175  INFO 3972 --- [  restartedMain] c.m.jhipster.config.WebConfigurer        : Web application configuration, using profiles: swagger
2017-03-22 08:46:01.213 DEBUG 3972 --- [  restartedMain] c.m.jhipster.config.WebConfigurer        : Initializing Metrics registries
2017-03-22 08:46:01.227 DEBUG 3972 --- [  restartedMain] c.m.jhipster.config.WebConfigurer        : Registering Metrics Filter
2017-03-22 08:46:01.228 DEBUG 3972 --- [  restartedMain] c.m.jhipster.config.WebConfigurer        : Registering Metrics Servlet
2017-03-22 08:46:01.235 DEBUG 3972 --- [  restartedMain] c.m.jhipster.config.WebConfigurer        : Initialize H2 console
2017-03-22 08:46:01.236  INFO 3972 --- [  restartedMain] c.m.jhipster.config.WebConfigurer        : Web application fully configured
2017-03-22 08:46:02.852 DEBUG 3972 --- [  restartedMain] c.m.j.config.DatabaseConfiguration       : Configuring Liquibase
2017-03-22 08:46:03.048  WARN 3972 --- [on-2-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase asynchronously, your database might not be ready at startup!
2017-03-22 08:46:09.546 DEBUG 3972 --- [on-2-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Started Liquibase in 6469 ms
2017-03-22 08:46:16.405  WARN 3972 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'noticiaService' defined in file [C:\Users\Jose Luis\miaplicacion2\target\classes\com\miaplicacion2\jhipster\service\NoticiaService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.miaplicacion2.jhipster.service.mapper.NoticiaMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2017-03-22 08:46:16.500 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.jhipster.domain.Authority      : Close successful.
2017-03-22 08:46:16.548 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.jhipster.domain.Usuario        : Close successful.
2017-03-22 08:46:16.583 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.jhipster.domain.Noticia        : Close successful.
2017-03-22 08:46:16.586 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.j.domain.PersistentToken       : Close successful.
2017-03-22 08:46:16.588 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.jhipster.domain.User           : Close successful.
2017-03-22 08:46:16.594 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.j.domain.User.authorities      : Close successful.
2017-03-22 08:46:16.770 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.j.d.User.persistentTokens      : Close successful.
2017-03-22 08:46:16.771 DEBUG 3972 --- [  restartedMain] c.e.c.E.m.j.domain.Usuario.noticias      : Close successful.
2017-03-22 08:46:16.827  WARN 3972 --- [  restartedMain] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available)
2017-03-22 08:46:17.701 ERROR 3972 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in com.miaplicacion2.jhipster.service.NoticiaService required a bean of type 'com.miaplicacion2.jhipster.service.mapper.NoticiaMapper' that could not be found.

Action:

Consider defining a bean of type 'com.miaplicacion2.jhipster.service.mapper.NoticiaMapper' in your configuration.

Process finished with exit code 0
`

## How can I solve this error?

**Comment by deepu105** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
