### ISSUE TITLE
Alert Service Internationalization testing (Protractor)

### ISSUE THREAD

**Issue by MatthewGouws** [jhipster/generator-jhipster#5473]
##### **Overview of the issue**

Writing of integration tests using protractor requires the use of the text in the language of use rather than the translation key as used in the given code tests.

##### **Motivation for or Use Case**

It would be preferable to use the translation key to ensure the correct text will be displayed to the end user.

##### **Suggest a Fix**

The following files can be edited to allow for internationalization in testing of alerts (Similar to the warning on input fields).

- Remove the translation service from the alert.service.js (80-82), 
- node_modules/ng-jhipster/bundles/index.js (2425 - 2438),
- node_modules/generator-jhipster/generators/client/templates/angularjs/src/main/webapp/app/components/alert/_alert.service.js (116-118)

in the alert.component.ts and alert-error.component.ts
- Replace
` <pre>...</pre> `
with 
`<span jhiTranslate="{{alert.msg}}"></span>` (Line 9/11)

##### **JHipster Version(s)**

 "jhipsterVersion": "4.0.3"

##### **JHipster configuration**

Type of application? - Monolithic
Name of Application? - X
Would you like to install other generators? - N
What is the default packageName - com.X
Type of Authentication - OAUTH2
Type of Production Database - SQL
PostgreSQL
Type of Development Database - PostgreSQL
Do you want to use Hibernate 2nd level cache? - N (http://www.javatpoint.com/hibernate-second-level-cache)
Gradle/Maven - Gradle
Which other technologies would you like to use?
Social Login - Y
Search Engine using elasticSearch - N
Clustered HTTP using Hazelcast - N
WebSockets - N
Apache Kafka [BETA] - N
LibSass stylesheet - N
Internationalization Support - To be discussed (Language Cover etc)
Testing Frameworks - Gatling and Protractor

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@MatthewGouws would you like to submit a PR for this?

**Comment by jdubois** [comment]
I'm closing this as no work has been done, and we have far too many opened bugs, so we need to prioritize
