### ISSUE TITLE
re

### ISSUE THREAD

**Issue by AmineJa** [jhipster/generator-jhipster#5478]
![errr](https://cloud.githubusercontent.com/assets/24399300/24256064/7df229d6-0fe7-11e7-867b-65e5f2a350f7.jpg)
#5476

**Comment by jdubois** [comment]
This is the third time to open up a ticket without any information! Please stop or I will fill an abuse report.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by AmineJa** [comment]
I have many probleme in jhipster and i need a help 

    On Thursday, March 23, 2017 4:46 PM, Julien Dubois <notifications@github.com> wrote:
 

 This is the third time to open up a ticket without any information! Please stop or I will fill an abuse report.—

**Comment by jdubois** [comment]
Yes but this is the bug tracker, if you don't do a clean bug report we can't help you. Here you're spamming the whole team, for nothing.

**Comment by deepu105** [comment]
@AmineJa if you have an issue follow our issue template guidelines and open a proper issue with all details.
