### ISSUE TITLE
Upgrade to Angular 4

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5481]
Angular 4 is out: http://angularjs.blogspot.fr/2017/03/angular-400-now-available.html?m=1

At some point we will have to migrate, and this also includes Angular CLI which is now out of beta.

So my proposal is that we migrate here issues #4794 ##5186 #5325 so we code them with the new release, hoping we will have less bugs than with the current release.

Now we need someone responsible for this: I won't be able to do this (too much work on other parts of the code), so who wants to do this? @deepu105 I guess you are focusing on React now? @sendilkumarn maybe? We're definitely lacking manpower here, I guess everyone got fed up with the Angular 2 migration, which I perfectly understand.

**Comment by sendilkumarn** [comment]
The app runs on ang4

But it is the aot that has problem.

**Comment by sendilkumarn** [comment]
Let us release ang4 now and then work on aot.

**Comment by jdubois** [comment]
OK @sendilkumarn you take the lead on Angular 4 ?

**Comment by sendilkumarn** [comment]
Okay 👍 I will try my level best

**Comment by jdubois** [comment]
Closing as the PR is merged!

**Comment by cbornet** [comment]
Wow fast ! 🥇
