### ISSUE TITLE
Adding extra attributes to jhipster default entities

### ISSUE THREAD

**Issue by SafeKhayati** [jhipster/generator-jhipster#5482]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) wth the jHipster tag.
- For bug reports its mandatory to paste the result of command `yo jhipster:info` run in your project root folder.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

I generated some entities from a jdl file and now i want to find a way to add some attributes to the default entities generated by jhipster user entity and persistentAudit entity.

##### **Motivation for or Use Case**

We work on a project and we have an entity called user which has some extra attributes like telephone number so i want to add these attributes

##### **JHipster Version(s)**

4.1.0
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This isn't a bug, please follow our guidelines.... Have a look on the
"tips" section of the website, and on Stackoverflow, plenty of stuff there
for this question.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
