### ISSUE TITLE
intellij idea typescript debug

### ISSUE THREAD

**Issue by pdaniel-frk** [jhipster/generator-jhipster#5488]
I try to debug typescript using intellij idea and chrome extension. My breakpoints are not geting triggered. Do i need to do something special to be able to debug typescript using intellij idea? I can debug other typescript projects, but the ones generated with jhipster, no.

**Comment by jdubois** [comment]
I'm sorry, but this is the JHipster bug tracker, not a forum on how to configure IDEA.
As this is only available with the IDEA Enterprise edition, you should have full access to their (professional) support, could you ask them about it? Of course, if they give you some good configuration tips, it would be nice to help us improve our documentation.
I'll also have a look at this when I have time, as I have basically the same issue (but I work just with Chrome and Augury, as I'm trying to keep working with free tools only, so JHipster users are not locked in).

**Comment by pdaniel-frk** [comment]
I managed to activate the debug in chrome by putting in webpack.dev.js this line : 

devtool: 'source-map',

The file looks like :

module.exports = webpackMerge(commonConfig({env: ENV}), {
    devtool: 'source-map',
    module: {
        rules: [{
            test: /\.ts$/,
            loaders: [
                'tslint-loader'
            ],
            exclude: ['node_modules', /reflect-metadata\/Reflect\.ts/]
        }]
    },
    plugins: [
        new BrowserSyncPlugin({
            host: 'localhost',
            port: 9000,
            proxy: 'http://localhost:8080'
        }),
        new ExtractTextPlugin('styles.css'),
        new webpack.NoErrorsPlugin()
    ]
});

in tsconfig.json make sure that         "sourceMap": true, is set to true.

The debug now works on Intellij Idea also.

**Comment by deepu105** [comment]
We already generate source maps and debug works in chrome I guess

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
Yes @deepu105 is right, you shouldn't need to do that.... This is definitely strange -> we need to improve https://jhipster.github.io/configuring-ide-idea/ when we have a good setup
