### ISSUE TITLE
pom.xml whitespace off for cucumber line

### ISSUE THREAD

**Issue by tezcane** [jhipster/generator-jhipster#5491]
##### **Overview of the issue**

Small typo in pom.xml:
```
<configuration>
    <includes>
      <include>**/*Cucumber*.java</include>
    </includes>
</configuration>
```
Should be:
```
<configuration>
    <includes>
        <include>**/*Cucumber*.java</include>
    </includes>
</configuration>
```

##### **Motivation for or Use Case**

Should match code convention of rest of pom.xml

##### **Reproduce the error**

N/A

##### **Related issues**

N/A

##### **Suggest a Fix**

Just add the spaces in _pom.xml in generator-jhipster project.

##### **JHipster Version(s)**

4.1.1

##### **JHipster configuration**
 
Maven build

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A

- [ X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@tezcane : can you PR with [ci skip] in your message commit ? it's minor so no need to trigger a full builds for that

**Comment by tezcane** [comment]
Yeah, sure.
