### ISSUE TITLE
E-mail/Email is not consistent across the app

### ISSUE THREAD

**Issue by tezcane** [jhipster/generator-jhipster#5493]
##### **Overview of the issue**

Sometimes Email is used, other times E-mail.

##### **Motivation for or Use Case**

It is better to stay consistent and use one way to do things, especially since e-mail/email is returned in some error cases.

##### **Reproduce the error**

N/A

##### **Related issues**

No

##### **Suggest a Fix**

I did a replace all with preserving case in my IDE from e-mail to email, and all worked as expected afterwards.

##### **JHipster Version(s)**

All

##### **JHipster configuration**

N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A

- [ X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Use [ci-skip] for typo corrections in comments and docs

**Comment by pascalgrimaud** [comment]
it's [ci skip] exactly

**Comment by tezcane** [comment]
I recommend we do a full Travis CI run for this one since "e-mail ..." is actually returned from the backend and looked for on UI code.

**Comment by pascalgrimaud** [comment]
yes, if it's in the code, let Travis CI run the full builds
if it's only in comments or docs, [ci skip] is better

**Comment by jdubois** [comment]
Closing as the PR is merged
