### ISSUE TITLE
When I import the gradle project with idea is importing all libraries as provided

### ISSUE THREAD

**Issue by atdi** [jhipster/generator-jhipster#5494]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) wth the jHipster tag.
- For bug reports its mandatory to paste the result of command `yo jhipster:info` run in your project root folder.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

When I import the gradle project with idea is importing all libraries as provided

##### **Motivation for or Use Case**

I cannot execute the application from idea in order to debug the java code
##### **Reproduce the error**

1. Generate a new jhipster project with gradle
2. Import the project to IDEA
3. When import is finished check the in the gradle view: <project name> -> Source Sets -> main -> Dependencies and you will see all libraries with scope Provided
##### **Suggest a Fix**

I don't know how to fix it, I've just recreate manually the gradle file I've copy paste the dependencies, plugins etc. from generated project and was working fine
##### **JHipster Version(s)**

JHipster is v4.1.1 and I've notice the same behaviour with jhipster 4.1.0
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
