### ISSUE TITLE
Upgrade to the JHipster Console v2

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#5502]
I just released v2.0.0 of the JHipster Console : [jhipster/jhipster-console/releases/tag/v2.0.0](https://github.com/jhipster/jhipster-console/releases/tag/v2.0.0).

This release includes Zipkin support which will be enabled for microservice and serviceDiscovery enabled apps using Spring Cloud Sleuth.

**Comment by pascalgrimaud** [comment]
It should be v2.0.1 instead
