### ISSUE TITLE
Karma tests for the AuditComponent are wrong at the end of each month

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5505]
Like last month, we have the AuditComponent test that fails:

https://travis-ci.org/jhipster/generator-jhipster/jobs/216062184

I tried to correct it with https://github.com/jhipster/generator-jhipster/commit/89cbbe0d17722bde106830db54369bb24479a0b9 (which I think was obviously false), but this is clearly not enough....

The issue is that we need to format dates to send them to a Java server (where months start with '0', so January is '0'), from a JavaScript component (formatted by Angular's datepipe, where January is '1').

Of course, this will work agina in a few hours, but it will fail again next month if we don't do anything!

**Comment by stevehouel** [comment]
@jdubois  I corrected it, I send the fix in 5min

**Comment by stevehouel** [comment]
As soon that I fix my merge problems ... I try Github desktop yesterday and that crash all my branches.

**Comment by jdubois** [comment]
@stevehouel if you did this, you are officially better than me at JavaScript!

**Comment by stevehouel** [comment]
Na, you must make a mistake on why test crash. It s not on Today day but when calculating the fromDate on previousMonth method. The it() message was wrong

**Comment by stevehouel** [comment]
So I still have some crappy Merge remote-tracking stuffs :( But this should be ok
