### ISSUE TITLE
No bean validation in Cassandra

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#5511]
There is currently no bean validation done at the repository level when persisting an entity to Cassandra (there is validation only at the view layer).
This is particularly annoying when using user services such as `createUser(String login, String password, String firstName, String lastName, String email, String langKey)` since you don't have a bean and you can't do the validation by yourself before calling the service.
So I would like to add a validation stage in the `save()` operation (like what is done when using spring data). Or do you see any objection ?

**Comment by jdubois** [comment]
- I didn't know there was a practical use for this "second validation", that's interesting. Now, if you just do the same thing as the Hibernate listener, I guess this is a good idea.
- There's probably the same issue with MongoDB, and we have far more people using MongoDB - do you think this could be some common code for non-JPA options?

**Comment by cbornet** [comment]
@jdubois I don't know if spring-data does any validation for mongoDB. I don't think it would be done the same way as it's code to add in the repository class.

**Comment by jdubois** [comment]
@cbornet I don't think it does, this is specific to Hibernate, that's why you should have the same issue with MongoDB and Cassandra

**Comment by cbornet** [comment]
I think mongo validation can be activated with a ValidatingMongoEventListener. I'll test asap.

**Comment by jdubois** [comment]
Indeed!

**Comment by deepu105** [comment]
Is it worth the effort? as Cassandra usage is so less? but ofcourse @cbornet if you want it for your use then fine

**Comment by jdubois** [comment]
Indeed, @cbornet you shouldn't worry for Cassandra, it's not worth the effort

**Comment by cbornet** [comment]
I'll do the PR as I need it in the gRPC module 😄 
Don't worry, it's only 3 lines of code !
