### ISSUE TITLE
Login modal jumps to page bottom

### ISSUE THREAD

**Issue by eosimosu** [jhipster/generator-jhipster#5513]
##### **Overview of the issue**
For long home page, the login modal jumps to the bottom when clicked. I know this is a minor issue but I've been trying to fix this behaviour (make it appear at the top) without luck.

<img width="1008" alt="screen shot 2017-03-29 at 23 06 05" src="https://cloud.githubusercontent.com/assets/10434280/24476709/a523fa6a-14d4-11e7-8df7-8ffad9852e2e.png">

##### **JHipster configuration**
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "my-app"
    },
    "jhipsterVersion": "4.1.0",
    "baseName": "my-app",
    "packageName": "my-app",
    "packageFolder": "my-app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxx",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**
macOS Seirra
Chrome Version 56.0.2924.87 (64-bit)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
@eosimosu I succeeded to fix this by adding a `container:'nav'` parameter when calling the open method in the loginModalService.
@deepu105 @sendilkumarn If that's ok with you I can PR this.

**Comment by deepu105** [comment]
@wmarques yes please

**Comment by eosimosu** [comment]
@wmarques great thanks!!
