### ISSUE TITLE
add mobile # to the user model

### ISSUE THREAD

**Issue by tezcane** [jhipster/generator-jhipster#5514]
##### **Overview of the issue**

A common field that I believe is missing from the user model is the user's mobile # (phone #).

##### **Motivation for or Use Case**

Many sites providing services to users, especially around mobile, will require a mobile #.  Since this personal information is similar to a user's username/login, email, name, etc. it is best to put it in this same user model that stores and updates this information.  It is otherwise annoying to have to add extra business logic, REST and database calls to update this one main field I believe is missing.

##### **Reproduce the error**

N/A

##### **Related issues**

None

##### **Suggest a Fix**

I can do PR for this.

Add a "mobileNum" field in code and display it as "Mobile #" in the UI (Mobile is pretty common across many languages to mean cell phone so even without translation it will be understood by many).  I'm thinking to make this a 10 digit string ( e.g. (408) 123-4567 will be stored as "4081234567").  String is probably easier to work with to convert to desired display format later.  Optionally there should be a way to store the country code in this same field or possibly separate field.

Some places needing the update: User.java JPA, UserDTO.java, REST update functions, unit tests, Angular 1/2 UI (settings page, user management).

Later, a drop down list with all the flags of each country that will auto choose the country code of the phone number.  Also, with a country code, every user's phone number will have to be unique so it can also be used as another way to login.  This would be overkill as reference code, but it is necessary to support international apps.

Another thought, to keep the code minimal and simple is to remove imageUrl (basically replace it with mobile #).  I doubt most people use imageUrl (probably store the actual binary PNG/JPG instead).  Also, imageURL is not supported in certain DB's too (not sure why since it is just a string path) and I didn't see any UI for updating/viewing ImageURL too.  In fact, it was also not even updated in the REST layer until I found the bug for that last week so probably no one cared to even test or use it before.

##### **JHipster Version(s)**

All

##### **JHipster configuration**

N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A

- [ X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry but we already had a similar discussion when adding images to the user: I don't want to have too many fields here, it's just going to be too big and bloated.
This is like the entity sub-generator: people wanted to add so many features, that now it's complicated to work with the generated screens, and I would like to have a new option to have "basic" screens instead.

**Comment by pascalgrimaud** [comment]
The possibility would be to do a module. For that, the main generator-jhipster need to add new needles to all files related to user.
Behide that, there are a lot of use cases:
- simple add phone number, or another field?
- support all databases (liquibase files, cql files, etc.)
- support the front
- support uaa / microservices
- add integration tests
- add gatling tests
- etc...

It can be a complex module or a simply one, depending on how far you want to go.
But I'm pretty sure you will find people interested by this, as it's a real business logic.

**Comment by jdubois** [comment]
Yes, updating the User entity is a very common question, we should work on that. And I'm not sure a module is the easiest solution, indeed.

I'm closing this, as quite frankly I don't want anymore new features for the moment on the User: it's also difficult to update because it's already too big, so I would rather remove features than add new ones.

**Comment by tezcane** [comment]
No worries, I had concerns of adding another field too.

In case you missed it, I proposed to replace image URL with the mobile #, copied here for your convenience:

> Another thought, to keep the code minimal and simple is to remove imageUrl (basically replace it with mobile #). I doubt most people use imageUrl (probably store the actual binary PNG/JPG instead). Also, imageURL is not supported in certain DB's too (not sure why since it is just a string path) and I didn't see any UI for updating/viewing ImageURL too. In fact, it was also not even updated in the REST layer until I found the bug for that last week so probably no one cared to even test or use it before.

**Comment by deepu105** [comment]
@tezcane it was added for social login where you will get image url from the service provider. Its not usually used for normal login

**Comment by tezcane** [comment]
OK, I thought that might be the case.
