### ISSUE TITLE
jhipster:entity error if translation vietnamese - _entity_vi.json not found

### ISSUE THREAD

**Issue by zuize47** [jhipster/generator-jhipster#5516]
##### **Overview of the issue**
My Jhipster support translate with vietnamese. When I add new entity by command jhipster:entity.
On the last step when generator, it thow error: "Copying template client/i18n/_entity_vi.json failed."

I have check, on folder ./node_modules/generator-jhipster/generators/entity/templates/client/i18n/ have no file _entity_vi.json. I copy from _entity_en.json to _entity_vi.json and the problem when create entity has been fixed. 

Please add default file _entity_vi.json for vietnamese language.

my yo-rc.json

```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "me.hoangnd.learn",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.1",
    "baseName": "salt",
    "packageName": "me.hoangnd.learn",
    "packageFolder": "me/hoangnd/learn",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "********",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "vi"
    ]
  }
}
```
Jhipster version: V4.1.1
Jhipster on docker host in Ubuntu 46.04

**Comment by jdubois** [comment]
Yes, can you do a PR with the missing file? I could add it, of course, but I would just copy/paste the English file, as I don't speak Vietnamese

**Comment by zuize47** [comment]
Thank you,

this _entity_vi.json in vietnamese.
[_entity_vi.json.zip](https://github.com/jhipster/generator-jhipster/files/881580/_entity_vi.json.zip)
