### ISSUE TITLE
JDL generation BLOB and filename

### ISSUE THREAD

**Issue by webskin** [jhipster/generator-jhipster#5517]
##### **Overview of the issue**

**Feature request :** handle filename for JDL BLOB generation

For example :
```
entity MyEntity {
	attributeName Blob
}
```

Currently these are the generated columns :
${attributeName}  BLOB 
${attributeName}_CONTENT_TYPE VARCHAR

**Column to add  :
${attributeName}_FILE_NAME VARCHAR**

##### **Motivation**

With this new column client will be able to download file preserving its name.

**Comment by jdubois** [comment]
Yes great idea.
But that's a lot of work: you need to support all 3 databases, and rework the front ends for both AngularJS 1 and Angular. Can you do a PR for that?

**Comment by webskin** [comment]
When you say 3 databases, you mean 
MySQL, PostgreSQL and Oracle
Or
{MySQL, PostgreSQL and Oracle}, MongoDB and Cassandra ?

**Comment by pascalgrimaud** [comment]
Yes, it's the type of database:
```
(6/15) Which *type* of database would you like to use? (Use arrow keys)
❯ SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL) 
  MongoDB 
  Cassandra
```

**Comment by jdubois** [comment]
As nobody as been working on this for 2 months and a half, and as it's a lot of work, I'm closing this for lack of interest
