### ISSUE TITLE
Postgresql update

### ISSUE THREAD

**Issue by AmineJa** [jhipster/generator-jhipster#5519]
When I write another entity or add an attribute or relation, the database does not change it however it writes the .xml files under the "config.liquibase.changelog" folder and add them to the master.xml file , That is to say at the application level all goes well but nothing changes to the database

**Comment by PierreBesson** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
