### ISSUE TITLE
Use AOT generated files for prod build

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#5530]
#5495 has made the angular 2 code AOT compatible. Now we need to change the prod build to use this instead of normal ts compiled files
cc @sendilkumarn

**Comment by jdubois** [comment]
+1 and for the back end we need to:

- [ ] Add a hash in front of `vendor.dll`
- [ ] Configure the HTTP caching filter to cache all those assets, like we did for AngularJS 1

**Comment by jdubois** [comment]
Closing as this is in #4794
