### ISSUE TITLE
Travis builds fail because of old Chrome version

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5539]
This follows issue #5536

Current Travis are failing, see [a raw log here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/218371442/log.txt) because of error "Chrome version must be >= 56.0.2884.0".

This is because the latest Selenium version requires a recent Chrome release, which is not provided by default by Travis.

So 2 solutions here:

- Upgrade the Chrome version in Travis
- Downgrade the Selenium version in our build

I guess the second point is easier for us, but of course that's bad in the long run.

**Comment by pascalgrimaud** [comment]
@jdubois : I can have a look but it seems your fix in the branch is correct
So ping me if needed

**Comment by pascalgrimaud** [comment]
This fix seems to work too:
- the diff: https://github.com/pascalgrimaud/generator-jhipster/commit/649d7e1e23dcab674b48fc6f60a0fe708f7bf6a7
- the build: https://travis-ci.org/pascalgrimaud/generator-jhipster/builds/218421658

**Comment by jdubois** [comment]
@pascalgrimaud OK, your fix looks better, I'm taking it
