### ISSUE TITLE
After installing Yeoman, getting "'yo' is not recognized as an internal or external command, operable program or batch file." error

### ISSUE THREAD

**Issue by AmsaveniMidhun** [jhipster/generator-jhipster#5549]
1. I am new to jhipster. Started with Installation. Followed the below steps,

Install Java 8 from Oracle.
Install Git from https://git-scm.com.
Install Node.js from http://nodejs.org. I used Node 6.9.1 to write this article.
Install Yarn using the Yarn installation instructions.
Run the following command to install Yeoman.
yarn global add yo
Since JHipster 4 is not released yet, you'll need to clone its GitHub repository to create a project with it.

git clone https://github.com/jhipster/generator-jhipster
After cloning it locally, you'll need to run npm link in the generator-jhipster directory so npm knows to use your local copy instead of trying to download and install it.

And tried to create a new project, with the command "Yo Jhipster", i am getting the following error.

'yo' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AdrienHorgnies** [comment]
It's not a bug. You must run `npm link generator-jhipster` inside the directory where you want to create an application.
I suggest you to try and go to [the jhipster gitter](https://gitter.im/jhipster/generator-jhipster) to ask for help for such cases before opening an issue.

**Comment by AmsaveniMidhun** [comment]
I did as you said, still stuck with the same issue

**Comment by PierreBesson** [comment]
@AmsaveniMidhun If you are using yarn, you should use `yarn link generator-jhipster` instead.

**Comment by AmsaveniMidhun** [comment]
@PierreBesson  Is thats the isse? i thought It can be linked either using npm or Yarn. Tried with Yarn link generator-jhipster in the folder where i want to create an application.

And again tried yo jhipster command, sill getting the same error.

**Comment by delverdev** [comment]
Until you find the solution, just type the full path to `yo` instead of "yo". Also, [this](http://stackoverflow.com/questions/42105179/yeoman-the-filename-directory-name-or-volume-label-syntax-is-incorrect) may helps.

**Comment by AmsaveniMidhun** [comment]
@delverdev Thanks a lot ! Working now :)

**Comment by deepu105** [comment]
Why are you cloning the repo insted of just installing it

**Comment by gmarziou** [comment]
@AmsaveniMidhun the instructions you used are **obsolete**, just follow the [official doc](https://jhipster.github.io).

> Install Node.js from http://nodejs.org. I used Node 6.9.1 to write this article.

JHipster requires 6.9.5 currently.

> Since JHipster 4 is not released yet, you'll need to clone its GitHub repository to create a project with it.

JHipster 4 has been released at the beginning of February.

**Comment by kartiksky** [comment]
Place your node path to user PATH variable this works for me.

**Comment by asifaftab87** [comment]
Each and every thing was fine only problem was path so I set path in environment variable.

This path I set in environment variabel

C:\Users\user\.npm-packages

where 'user' is my user name, please use your user name.

Then my 'yo', 'bower' command start to executed 
Thanks
