### ISSUE TITLE
Unique constraint added for one-to-one relationship (owner)

### ISSUE THREAD

**Issue by vambo** [jhipster/generator-jhipster#5550]
* **Overview of the request**

I see that by default a unique constraint is added to the column for the owner side of the one-to-one relation, and I have tracked it down to the following commit:

https://github.com/jhipster/generator-jhipster/commit/528b0ecb0c453ce7dbad5961651943209afe02e9
* **Motivation for or Use Case** 

Take for example a game, where there could be two one-to-one relationships from Game to Team: e.g. homeTeam and awayTeam. It should be possible for either team to be added to more than one game, which the unique constraint would prohibit currently.

Could someone at least explain the background of the current logic to me, maybe I am missing something?

* **Browsers and Operating System** 

* **Related issues** 

* **Suggest a Fix** 

Removing the unique constraint (or making it optional)

**Comment by andidev** [comment]
I'm the owner of this commit and I'll try to defend myself 😁 
The relationship you are talking about isn't it two one to one relationships where the owner is Game? I'm actually not that familiar with hibernate relationship design so please correct me if I'm wrong.

**Comment by andidev** [comment]
Sorry for my last commit, you may be right here

**Comment by andidev** [comment]
Or isn't that really two one to many relationship?

**Comment by jdubois** [comment]
If it's not `unique`, then this isn't a `one-to-one` relationship at the database level. Your use case is very strange, doing 2 `one-to-one` relationships on the same 2 entities - I'm not really sure if this makes sense, but here I'm just focusing on the technical part (this is the bug tracker, not StackOverflow...).
For me this it would be wrong do remove the `unique` constraint, as it's correct for a normal usage.

**Comment by vambo** [comment]
You are right, having the unique constraint for one-to-one seems to be the standard, and in this case I can declare two unidirectional many-to-one relationships instead.

Thanks for your time guys and keep up the good work.

**Comment by jdubois** [comment]
Thanks for the feedback @vambo !!
