### ISSUE TITLE
Proposal to consolidate dependency management

### ISSUE THREAD

**Issue by erikkemperman** [jhipster/generator-jhipster#5551]
##### **Overview of the issue**

Request for comment: proposal to consolidate dependency management into a single POM and use that from both Maven and Gradle. Additionally, for Maven, separate most of the JHipster stuff into a parent POM to unclutter the main user-visible POM.

##### **Motivation for or Use Case**

Advantages:
- No longer need to maintain version strings separately for Maven and Gradle (the gradle dependency management plugin can read the proposed jhipster-dependencies POM).
- Open-ended parent hierarchy (for Maven) so we can attach corporate parent on top, and/or collective of microservices can inherit from a single parent.
- A lot less generic stuff in the user-visible build files, easier to work with generated apps and subsequent JH upgrades should result in fewer conflicts.

Disadvantages:
- Requires a separate release of the jhipster-dependencies POM (actually I suppose this could be a benefit, depending on how you look at it).
- The first time users upgrade from before to after something like this proposal being implemented it might be a bit tricky.

##### **Rough outline of the proposal**

Basically I am suggesting to introduce a new Maven artifact, jhipster-dependencies, which will have spring-boot-dependencies as its parent and includes all dependencyManagement that we inherit from spring-boot and everything that JH adds to that. So basically a kind of merge of spring-boot-dependencies and our current generator/server/templates/_pom.xml. We can then import this (with scope=import and type=pom for Maven, or the gradle dependency management plugin otherwise) into the JH project so we don't have to specify explicit versions there.

In addition I would like to propose moving a lot of what remains in the generated pom.xml into a separate parent/pom.xml. That way the immediately user-visible POM will be relatively small, clean, and robust under upgrades. To compensate for the fact that we will be importing dependencyManagement from spring-boot-dependencies, instead of inheriting from spring-boot-starter-parent, we will have to duplicate from the latter a bit of pluginManagement.

I made a (literally) back-of-the-envelope sketch of the before and after situation of this idea:

![img_1267](https://cloud.githubusercontent.com/assets/3100637/24758663/534f158e-1ae3-11e7-9de1-b673dc2cba76.JPG)

##### **Questions for the core team and community**

Does this sound like a good idea? Are there any (dis)advantages I might be overlooking? I have a rough version of this which works. I'd be willing to put in some more time to polish it, but would like to ask for input first!

EDIT Some links with background info:
http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-build-systems.html#using-boot-maven-without-a-parent
https://github.com/spring-gradle-plugins/dependency-management-plugin

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
- I've wanted to have our own "parent pom" from a long time, that was one of my original ideas with JHipster. Indeed, our build would be much simpler and cleaner.
- But that goes against being just a "generator". All users will then depend on JHipster, and I'm not sure everyone will like it. I know we already did that with our library, but this goes even further.

**Comment by erikkemperman** [comment]
Hi Julien, thanks for your quick response! 

For what it's worth, I don't think this would make users depend more (or less) on JHipster. If I understand your remark properly.

The direct dependency on the server lib would move out of sight for end users and in its place would come a single dependencyManagement POM (which users could still override if they want to).

The benefit for jhipster devs would be unification of dependecy management across Maven and Gradle.

**Comment by jdubois** [comment]
Sorry @erikkemperman I just wanted to give pros/cons -> yes that's definitely worth discussing/trying. I have a few doubts, so I would like opinions from more people, or perhaps see a first "alpha" release so we can see the end result.

**Comment by erikkemperman** [comment]
Of course! I'll have some time to make an alpha probably Sunday.

**Comment by jdubois** [comment]
@erikkemperman looks like you stopped working on this? I'm closing this as it looks stucked, don't hesitate to comment or re-open if you still want to do it.

**Comment by erikkemperman** [comment]
@jdubois Yes, sorry for not mentioning it here, but I've been occupied with various other things lately. If/when I find time to get back to this (which I still think might be a decent idea) I will re-open the issue.
