### ISSUE TITLE
Proposal for more types

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#5552]
Hello @jhipster/developers!

##### **Overview of the issue**

What if I could have this JDL file:
```
entity Toto {
  firstField String
  badassList List<String>
  anotherBadassThing Map<String, List<Long>>
}
```
And JHipster would know that there's no supported type such as `List` or `Map`, but would just add the field to the class with no database mapping... except for MongoDB (sorry Julien ;)) and Cassandra.

##### Motivation for or Use 

@doanduyhai would like these "new" types to be supported so that JHipster, somehow, would use these types in Cassandra.

#### Proposed workflow

Workflow:
  - Write a JDL with a special type (Map, List, whatever),
  - Have JHipster notice the type and bypass the database management for the entity,
  - If the app's DB is Cassandra (or MongoDB, later) -> map it.

There would be work:
  - In the JHipster core project (little work, only)
  - In the generator (the heavy work)
  - The JDL studio (because it has to be updated)

- [X] Checking this box is mandatory (this is just to show you read everything)

I'd like your input on this. I think this could be a good idea, but I have some reservations and doubts about this.

**Comment by deepu105** [comment]
What is the use case to do this from JDL?

**Comment by MathieuAA** [comment]
Hi Deepu, as the JDL is imported and JHipster generates everything, the goal here is to have these from the JDL so that it could be supported and detected. If the app's DB is Cassandra then we allow these types and make the modifications in Cassandra.
Why from the JDL? Because I hardly see a new question pop to ask if the user wants a List of Strings or something like that. The JDL is the only place for such types.

**Comment by deepu105** [comment]
​I wouldnt really bother if its only for Cassandra as the usage is so little it might not be worth the maintenance effort. Please check with @jdubois on what he thinks.

**Comment by MathieuAA** [comment]
I did. That's why I wanted other opinions on the matter.
And, as I said, it wouldn't end with Cassandra but with mongodb. That's my chief motive. Cassandra is only a pretext for me.

Le 6 avril 2017 21:46:33 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>​I wouldnt really bother if its only for Cassandra as the usage is so
>little it might not be worth the maintenance effort. Please check with
>@jdubois on what he thinks.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/5552#issuecomment-292293224

-- 
Mathieu ABOU-AICHI

**Comment by doanduyhai** [comment]
> its only for Cassandra as the usage is so little

Maybe because right now the support for Cassandra is very limited with JHipster. If we support more Cassandra data types and operation, it will help increase adoption

**Comment by pascalgrimaud** [comment]
It was discussed at DevoxxFR and clearly, our Cassandra support is outdated as there are very few pull requests about Cassandra.
Any help to improve the Cassandra support is welcome, so I will be very happy if Doan can help us for that.

**Comment by jdubois** [comment]
Yes, Cassandra is 0.4% of all generations (and probably half of them are me doing tests...), so it has a high maintenance cost for us, for little benefit. I'd love to have DuyHai do this, as he works for DataStax and obviously knows Cassandra very well.

**Comment by deepu105** [comment]
Is this being pursued? Else can we close it as we have too many more pressing stuff in backlog

**Comment by doanduyhai** [comment]
Close it for now
