### ISSUE TITLE
Remove pngquant/optipng

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5553]
I haven't looked very closely at pngquant/optipng but we keep having issues with those:

- Those are native libraries that do image minification
- They need to be native (you can't do that kind of thing in JavaScript)
- They rely on libraries that should be installed on the machine, which make them fail quite often on Linux (and also on Windows, see #5547 )

Apart from those errors, as those are native librairies, they should be downloaded at each project generation (they can't be stored in the Yarn cache), and that's a real pain when generating an application.

I find those are totally useless. Images should be done by graphic designers, and they don't work with PNG or JPEG. So when images are put into the application, they should already be minified, and shouldn't be touched by our minification process.

So I'm opening this ticket to remove those.

**Comment by deepu105** [comment]
I wouldn't mind removing image min to reduce complexity. It could be added
as a tip instead

**Comment by jdubois** [comment]
OK I'm doing it - I'm so fed up with those image issues!

**Comment by stevehouel** [comment]
+1 @jdubois :)

**Comment by stevehouel** [comment]
@jdubois you were faster that me lol

**Comment by ruddell** [comment]
We also should revert https://github.com/jhipster/generator-jhipster/commit/da24c3a7a89064a6f2e99a8bda3b1aee859303bf

**Comment by jdubois** [comment]
Oh sorry I missed this one, thanks @ruddell

**Comment by sdoxsee** [comment]
@ruddell @jdubois the phantomjs part seemed to be needed for me but I can't tell you exactly why yet. I added it back and everything worked. ref: https://github.com/karma-runner/karma-phantomjs-launcher/issues/120#issuecomment-262634703

**Comment by ruddell** [comment]
@sdoxsee I originally added those lines without much reason besides that several people had to run into that same issue, I can't reproduce it anymore though.  Also our Travis tests seem to be passing without a problem, so maybe it's related to node version or operating system?  If you can reproduce it or have more info on why it happens, please open a new issue with the details
