### ISSUE TITLE
Can you add a excel import and export module

### ISSUE THREAD

**Issue by liumaobudao** [jhipster/generator-jhipster#5557]
Hello, can you add a excel import and export module。
Thank you

**Comment by jdubois** [comment]
Duplicate from #3611

This goes way too far for the generator, and would make it really bloated. This would be very interesting as a module, if anyone is interested in doing this.

**Comment by locationguru-git** [comment]
I would like to take this up

**Comment by jdubois** [comment]
@locationguru-git I don't think anyone is working on this, feel free to do the module, it looks like a lot of people want this feature (and don't hesitate to mention @java_hipster on Twitter when you release, so we help you to communicate on this)
