### ISSUE TITLE
Using Angular CLI with JHipster

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5558]
Angular CLI works with JHipster, but it's not documented.

We should:

- Test it better, and check everything that works well and makes sense (no all tasks make sense with JHipster)
- Write a complete documentation at https://jhipster.github.io/using-angular/ (source is at https://github.com/jhipster/jhipster.github.io/blob/master/pages/using_angular.md )

**Comment by stevehouel** [comment]
@jdubois I'm on it if nobody already did it

**Comment by jdubois** [comment]
Then it's all yours :-)

**Comment by jdubois** [comment]
I just invited you to the org so the task can be assigned to you, tell me when you approve the invitation

**Comment by pascalgrimaud** [comment]
@stevehouel : and don't forget to param correctly your local git config (to be sync with your github account), so you won't lost the "green points" on your github profile!

**Comment by stevehouel** [comment]
Now, I will update documentation on Website for AngularCli usage.

**Comment by jdubois** [comment]
Closing this as the documentation is done - there are a few changes to make, but I'll do it when I do the release, no problem

**Comment by tonny008** [comment]
Angular cli not working in the latest version. which is v5.1.0

**Comment by PierreBesson** [comment]
Yes this has also been reported to me. But @tonny008 please open a new issue.

**Comment by WiteCastle** [comment]
Any updates? The documentation isn't necessarily clear because it states that a `.angular-cli.json` config file is generated by JHipster ([using_angular.md L172](https://github.com/jhipster/jhipster.github.io/blame/master/pages/using_angular.md#L172)) but the latest version doesn't generate this for me.

**Comment by gmarziou** [comment]
It's `angular.json` now.
