### ISSUE TITLE
How to Delete the existing entity from the jhipster

### ISSUE THREAD

**Issue by NABEEL-AHMED-JAMIL** [jhipster/generator-jhipster#5559]
Hi,
   I'm working on the project and i'm new to used this tool. is any one help me.
well the problem is i want to remove's the entity's from my project and replace the new (Jdl) structured entity in this project .
Example :- mean that i put first in my project two entity like (Author and Book) and i want to remove this from my project and want to put the new entity like(Person , Father , Student , Teacher ) . 
What i do........

**Comment by gmarziou** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by gmarziou** [comment]
This is a question not an issue, please go to stackoverflow or gitter

**Comment by NABEEL-AHMED-JAMIL** [comment]
Ok Thank Q

**Comment by NABEEL-AHMED-JAMIL** [comment]
but there is also one issue suppose the above example as i Question (Author and Book) I add some new attribute in the Author entity (for updating the Author) then i Run my project this show the new attribute but after i again the update my Author entity this time entity not update?
(Note: first update add 3 attribute and the second update want to remove the 2 attribute but the entity class show the all attribute of 3 why he not show the 1 attribute and it's method)?

**Comment by pascalgrimaud** [comment]
As said by Gmarziou, you should go to stackoverflow. 
What you described here, is your own code.
