### ISSUE TITLE
Generate UI pages / forms / site map  and associate backend layer

### ISSUE THREAD

**Issue by Dufgui** [jhipster/generator-jhipster#5566]
##### **Overview of the issue**

generate pages and associate menus and backend services.

##### **Motivation for or Use Case**

Most of the time, when we want to start an application we speak with final users (customers) and they don't talk about model and entities but most of the time they speak about pages, screen and workflow.

##### **Suggest a Fix**

my proposition is to : 

1. add a dedicated generator (maybe extrernal repo)
2. add screen/page in entity's json
3. add screen/page in jdl

Most of the time a page is an aggregation of some entities but there is one main entity so i propose to link all pages to one main entity.
Maybe we can add some validation as we can see in some client side generator : http://schemaform.io/

##### **JHipster Version(s)**

All

##### **JHipster configuration**

NA

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

I have not yet a fixed way to describe it.

##### **Browsers and Operating System**

NA

- [X] Checking this box is mandatory (this is just to show you read everything)

######## DEV PR ########

I can do it myself, so i think i create it but do you want it in the core / generator / ... ?

My proposal is just to go "To infinity and beyond!”, hope you like it.
I think it's a good to have a demo effect with some customer

**Comment by pascalgrimaud** [comment]
Did you have a look at https://jhipster.github.io/modules/creating-a-module/
I think you can do a module for that

**Comment by jdubois** [comment]
I totally agree with this idea, but first I would like to have #5558 fixed.

That would mean that:

- For CRUD generation we have the current entity sub-generator
- For very simple pages we have Angular CLI

Then, indeed, there could be a middle ground, but there's quite a lot of discussion to do here. If you want to be free, you could do a module like @pascalgrimaud suggest, and then if everybody agrees on it, it could be merged in the main generator.

**Comment by jdubois** [comment]
We clearly don't have the time to work on this at the moment: we have tons of opened bugs, so we need to prioritize.
@Dufgui this would be a good use case for a module, if you're interested. And if that's successful, we can then integrate it back into the main project.

**Comment by Dufgui** [comment]
I will do it
Le ven. 28 avr. 2017 à 16:37, Julien Dubois <notifications@github.com> a
écrit :

**Comment by Dufgui** [comment]
Hello, just to have a feedback, i start to code it:
http://www.jhipster.tech/modules/marketplace/#/details/generator-jhipster-pages.
It's work for form and just angular js. I will do angular 4 and table if people use it.

**Comment by jdubois** [comment]
Looks good! I also would like to have more sub-generator (at the moment I'm needing a simple "create Spring MVC REST controller"), and there's a good spot to work here

**Comment by cbornet** [comment]
@jdubois don't create Spring MVC controllers, generate them from a swagger file 😉

**Comment by PierreBesson** [comment]
@cbornet, Agree with you that it's best to do that through swagger.

Either we generate only in `target/` like we do for API first or we could add a subgen that would execute the swagger-codegen jar from the `.m2`. 
I'm thinking that the jar could eventually be retrieved with `mvn dependency:get` if it's not already present.

**Comment by jdubois** [comment]
@cbornet I would just like to have a `jhipster controller` like we have a `jhipster service`. It would just create simple files, like Angular CLI can do on the client side. Would be good for microservices.

**Comment by Dufgui** [comment]
Hello,

just for info, now it's works with angular 4 and table.
I think some things can be include in the core.
I add 2 functions to manage menu and sub menu. It could be interesting for module to have it in the core.

For the rest of my dev, it could be interesting to share template between me and entities templates....

have a nice day

**Comment by abhayc77** [comment]
@Dufgui Are you planning the upgrade for JHipster 4.14. This sub-generator is not working with Angular 5

**Comment by deepu105** [comment]
@abhayc77 this feature was never implemented
