### ISSUE TITLE
Using JHipster in production got stuck at "yarn run webpack:build"

### ISSUE THREAD

**Issue by johnnygaobx** [jhipster/generator-jhipster#5570]
C:\Users\Administrator\Desktop\attendance\src>mvnw -Pprod package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Attendance 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:copy-resources (default-resources) @ att
endance ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] Copying 13 resources
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ attendan
ce ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] Copying 13 resources
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-versions) @ attendance -
--
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:prepare-agent (pre-unit-tests)
 @ attendance ---
[INFO] argLine set to -javaagent:C:\\Users\\Administrator\\.m2\\repository\\org\
\jacoco\\org.jacoco.agent\\0.7.7.201606060606\\org.jacoco.agent-0.7.7.2016060606
06-runtime.jar=destfile=C:\\Users\\Administrator\\Desktop\\attendance\\src\\targ
et\\test-results\\coverage\\jacoco\\jacoco.exec -Djava.security.egd=file:/dev/./
urandom -Xmx256m
[INFO]
[INFO] --- frontend-maven-plugin:1.3:install-node-and-yarn (install node and yar
n) @ attendance ---
[INFO] Node v6.9.5 is already installed.
[INFO] Yarn 0.19.1 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.3:yarn (yarn install) @ attendance ---
[INFO] Running 'yarn install' in C:\Users\Administrator\Desktop\attendance\src
[INFO] yarn install ### v0.19.1
[INFO] [1/4] Resolving packages...
[INFO] success Already up-to-date.
[INFO] $ yarn run webpack:build

**Comment by pascalgrimaud** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

Open a new issue with proper details or update this issue with all details and request to re open.
Issues opened without proper details will be closed without explanation.
