### ISSUE TITLE
User Registration and Add user from admin panel not working : JHipster version 4.2.0

### ISSUE THREAD

**Issue by Drishika** [jhipster/generator-jhipster#5572]
I recently upgraded to version 4.2.0 and the registration and add user from admin panel are not working.

1. On clicking registration instead of taking me to registration page the link launches login modal.
2. When I add a new user from admin panel , I tried adding user as ROLE_USER, the email link launches login modal. I would have expected it to take me to password reset screen as the router link shows "/reset/finish?key=xxxxx"

**Comment by jdubois** [comment]
Duplicate #5542
