### ISSUE TITLE
Server side rendering with Angular Universal

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#5575]
Server side rendering is pretty important for SEO. It's also should be faster. [Angular Universal](https://github.com/angular/universal) has changed the current state:

> Universal platform API has been merged into Angular 4.0!

It's also has [an upgrade guide](https://github.com/angular/universal/blob/master/UPGRADE-GUIDE.md) from 2.x to 4.

More info [here](https://universal.angular.io/) and [here](https://medium.com/@NodeArt/google-friendly-angular-applications-c5f3a033528f).

**Comment by jdubois** [comment]
You need a node.js server for that... So it just won't work with our current setup.

**Comment by hadirsa** [comment]
Hi @jdubois  , i need to have sever-side-rendering in my app. So to have server-side-rending in our `jhipster `app, You mean that we separate the `REST  API ` of Spring boot from the Angular part and then add a `nodejs `server to it?

**Comment by deepu105** [comment]
https://stackoverflow.com/questions/37699744/can-we-use-angular2-universal-with-server-side-java


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
You need to generate the server side rendering and serve it from Spring Boot.
This should be discussed on StackOverflow, and then summarized as a tip on our website.

**Comment by hadirsa** [comment]
@deepu105 , @jdubois Thanks for help. I have separated the `Webapp` and `API` and then add the 
angular universal to the project. it seems the solution is like this until we have Angular universal in lovely jhipster generator.

**Comment by gmarziou** [comment]
I'm curious, can you share a repo ?

**Comment by riaprocoumai** [comment]
https://github.com/swaechter/angularj-universal
