### ISSUE TITLE
jhiAlertError not showing alerts after hot module reloading

### ISSUE THREAD

**Issue by santoshkt** [jhipster/generator-jhipster#5587]
##### **Overview of the issue**

jhiAlertError intercepts response and displays error messages after I start the application. But when I make any changes, hot module replacing happens and after that it cannot display error messages in the selector. I don't have any custom changes in my webpack.

##### **Motivation for or Use Case**

HMR should work with jhiAlertError so it will be easy in development

##### **Reproduce the error**

Try to reproduce a scenario which will show errors in jhiAlertError. 
Make some changes in the code to trigger HMR
Try reproducing the same error again

##### **JHipster Version(s)**
```
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.8",
    "baseName": "jhipster",
    "packageName": "com.github.santoskt.ngxpipes",
    "packageFolder": "com/github/santoskt/ngxpipes",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "2d99b780856b9651aecf8fe9c51ed01e38455852",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}```

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Fixed via https://github.com/jhipster/ng-jhipster/pull/33
Lib needs to be released and upgraded here hence keeping this open

**Comment by jdubois** [comment]
@deepu105 can you do the ng-jhipster release soon? I'd like to do a generator-jhipster release during the week-end

**Comment by deepu105** [comment]
Sure ill do it today

**Comment by deepu105** [comment]
closing as per comment by @pascalgrimaud in #5829
