### ISSUE TITLE
StringReplacePlugin for webpack doesnt work

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#5589]
We use StringReplacePlugin in `webpack.common.js` to update the `app.constants.ts` file. It doesnt seem to work in latest master as the values below marked for replace are not done
```
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
```

**Comment by jdubois** [comment]
I confirm the issue, the code does get executed but the values do not change :-(

**Comment by jdubois** [comment]
I can't find the solution for this at the moment, so this will be in the next release...

**Comment by deepu105** [comment]
Ill take a look over the weekend

**Comment by stevehouel** [comment]
I was thinking @jdubois  and @deepu105 when doing my task on Angular Cli. Do we really need now to have two way of build and deploying the application. Angualr Cli is now released and not in beta, so why not removing all JHipster webpack stuffs and just use Angular Cli for build and tests.

**Comment by deepu105** [comment]
We do much more than what Angular CLI does I believe. But ofcourse if
someone can get the same workflow working with CLI then we could consider
that. Also Im not sure how far Angular CLI is customizable to the end user

**Comment by deepu105** [comment]
Ahh. Seems like it does work but instead of changing the app.constants.ts file it does the change directly in the main.bundle.js. So it basically works :)

**Comment by dancancro** [comment]
This seems to mean that configuration settings won't work in JHipster apps until the next release. Do I understand that correctly? Did they work in the past? @deepu105 How do you keep the Typescript compiler happy with any references to app.constants.ts? Do you have an example? I would like to add some settings to [my app](https://github.com/dancancro/great-big-example-application/blob/dev/src/main/webapp/app/app.constants.ts).

I am also in favor of adopting an industry standard approach to configuration settings, and angular-cli's, now with an eject option, seems like a good choice to me. Of [all the ways](https://docs.google.com/spreadsheets/d/1nMv8TqUx3gUoC3M6BRPB4E4FMTSYGT_OLERguXGjePc/edit#gid=1404564369) development approaches vary, configuration is one of the most varied.

**Comment by jdubois** [comment]
How on earth did I miss your app, Dan???? This is awesome ! We know each
other, why didn't you tell me?
I would love to have it on our showcase page, is it OK for you?

**Comment by deepu105** [comment]
@dancancro this want an issue at all actually. The plugin works fine. the replacement happens at compile time and on the generated bundle and not on the source itself. so if you look at the source it will always be the template but the bundle will have the correct value replaced. Are you facing any issue?

**Comment by dancancro** [comment]
@jdubois thanks.  It's a work in progress. I've had its parts in various situations over the past year while I was mostly learning Redux and new Angular. I only put them into a JHipster app a little while ago. I'm happy to have it in the showcase, but it does have bugs. 

However if a JHipster expert would like to help me polish it...... :)

@deepu105 That's good. Maybe the only problem would be the editor indicating errors. I'm using VSCode and it puts nice red squiggly lines under problems. I don't think it would know about these replacements.

**Comment by deepu105** [comment]
Yes it wouldnt. Thats why I added  /* tslint:disable */ on it


Thanks & Regards,
Deepu
