### ISSUE TITLE
Upgrade to Spring Cloud Dalston

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5590]
Spring Cloud Dalston was just released:

https://spring.io/blog/2017/04/12/spring-cloud-dalston-released

2 important things about it:

- It should solve the Kafka issues we used to have
- The DiscoveryClient has been refactored, and this might impact the future JHipster Registry release we are working on with @JulienMrgrd - so this needs to be checked

**Comment by jdubois** [comment]
First tests show no error at all, but we need to watch out for the Kafka issues, it wasn't obvious.

**Comment by PierreBesson** [comment]
We need to do some testing with Consul. Also there is a new feature to deregister zombie consul instances which was a big issue with Consul.
