### ISSUE TITLE
why jhioster is categorized in javascript?

### ISSUE THREAD

**Issue by ghaseminya** [jhipster/generator-jhipster#5592]
Hi
why jhioster is categorized in javascript?

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
- This is done automatically by GitHub
- The project is done in JavaScript, and there's a lot of generated JavaScript, so quite simply that's the most used language in the project
