### ISSUE TITLE
Prometheus Metrics are broken

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#5593]
##### **Overview of the issue**

Activating Prometheus doesn't take effect. It should offer metrics out on /prometheusMetrics. But this page leads into a 404 Error

##### **Motivation for or Use Case**

Prometheus is very awesome, especially with kubernetes. I want to use that! :smile: 

##### **Reproduce the error**

Pick any JHipster version from 4.0.2 to 4.3.0 and enable prometheus over config. Neither via environment, nor with direct configuration in `application-*.yaml` the prometheus endpoint start to work.

##### **JHipster Version(s)**

up from 4. Tested with 3.12 and it works!

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by tezcane** [comment]
Does this service require running a Promethius based server instance (probably a docker image)?

**Comment by PierreBesson** [comment]
@xetys Did you package the app with the "Prometheus" maven profile. Like this : `mvn -Pdev,prometheus` ?

@tezcane you can generate the Prometheus server files with the docker-compose subgen.

Guys, don't hesitate to improve the docs on this. I have received little feedback.

**Comment by tezcane** [comment]
I am planning to go through and make many updates to the Docs one of these days.  I must have read each page 3 times by now... I was a software application engineering for a few years so write a lot of tech docs and ref code...  did this as an software engineer too.

**Comment by tezcane** [comment]
For the problem, it sounds like he did not launch the docker-compose image...

**Comment by xetys** [comment]
No, I am talking about the metrics endpoints. I didn't know it's bound to a
profile, as this seems to be new from version 4. If you take a 3.12
application and go /prometheusMetrics, there will be the expected output,
and has nothing to do with docker.

I will check that, especially if it also works with gradle

tezcane <notifications@github.com> schrieb am Fr., 14. Apr. 2017, 10:10:

**Comment by PierreBesson** [comment]
@xetys, yes it's new from 4.0, it came with the JHipster lib.

**Comment by xetys** [comment]
ok, I tried it out and it worked.

in gradle I use 

```
$ ./gradlew -P prod -P prometheus -x test build buildDocker
```

to build a working image. This **really** should be better documented!

**Comment by ruddell** [comment]
@xetys Is there another step besides adding the profile?  I'll be testing this and the JHipster Console v2 soon.  

I created a PR to the docs to say refer to all applications instead of "maven applications", if there's something else we should add please do so.
>Note that in order to enable prometheus metrics reporting, you will need to build the application with the prometheus profile so that the prometheus client libraries are available on the classpath.

**Comment by xetys** [comment]
@ruddell you need to enable it via configuration, of course. I am doing this using spring cloud config so every microservice is logging by default
