### ISSUE TITLE
make entity generated with entity sub generator non persistable

### ISSUE THREAD

**Issue by bayrem404** [jhipster/generator-jhipster#5598]
##### **Overview of the issue**

 i want to make an entity generated with entity sub generator non persist-able   

##### **Motivation for or Use Case**
i want to use entities that dont need to be located in database , i want to the rest webservice to get elements that will be displayed from a json file in local directory in my project  

##### **Suggest a Fix**

 make the entityrepository dont extends from jpa repository is the forst step i guess 

##### **JHipster Version(s)**

4.1.0

##### **Browsers and Operating System**

 ubuntu 16.04 lts , chrome

**Comment by jdubois** [comment]
I'm sorry but we won't add another option there, it's already overly complex. You should indeed delete the repository part, that's quite easy to do (just delete the file, and then remove the methods calling it, there should be very few of them).

**Comment by gmarziou** [comment]
Don't forget to remove also the database migration files, git is your friend ;)

**Comment by bayrem404** [comment]
thank you @gael and @julien

2017-04-14 23:01 GMT+01:00 Gaël Marziou <notifications@github.com>:

**Comment by julien** [comment]
You're welcome
