### ISSUE TITLE
Unable to upgrade to 4.30 due to an exception

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#5600]
##### **Overview of the issue**

 ~ $ yo jhipster:upgrade
Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
Looking for latest generator-jhipster version...
/home/oem/.config/yarn/global/node_modules/semver/semver.js:279
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: undefined
    at new SemVer (/home/oem/.config/yarn/global/node_modules/semver/semver.js:279:11)
    at compare (/home/oem/.config/yarn/global/node_modules/semver/semver.js:566:10)
    at Function.lt (/home/oem/.config/yarn/global/node_modules/semver/semver.js:600:10)
    at shelljs.exec (/home/oem/.config/yarn/global/node_modules/generator-jhipster/generators/upgrade/index.js:106:28)
    at /home/oem/.config/yarn/global/node_modules/shelljs/src/exec.js:199:9
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)

##### **Related issues**

NA

##### **Suggest a Fix**

?

##### **JHipster Version(s)**

4.2.0

##### **JHipster configuration**

$ yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/home/oem
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml

```

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.22.0

Docker version 17.03.1-ce, build c6d412e

##### **Browsers and Operating System**

Linux Mint 18.1

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I couldn't reproduce this with v4.2.0 or v4.3.0

I do get this error if I disable my internet though.  You need an active internet connection to upgrade.  I fixed that error message in a PR

**Comment by vw98075** [comment]
Thank Jon for looking into this problem. And no, there wasn't any
internet connection problem. After upgrading yarn, the problem is
resolved.

On 2017-04-14 23:56, Jon Ruddell wrote:

> I couldn't reproduce this with v4.2.0 or v4.3.0 
> 
> I do get this error if I disable my internet though. You need an active internet connection to upgrade. I fixed that error message in a PR 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/jhipster/generator-jhipster/issues/5600#issuecomment-294257890
[2]
