### ISSUE TITLE
kubernetes improvements

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#5603]
I was deploying JHipster microservice to a production like kubernetes cluster and noticed a few thing we could do better, and I want to PR that. Here are the points:

- [x] improving namespace integration, so it works better with non-default namespace
- [x] adding livenessProbe to /health, so kubernetes recognizes failing pods earlier
- [x] adding readinessProbe, so rollout kills pods on real readiness, instead of as container is running
- [x] adding JHipster Console as option, with the corresponding adjustment to env / application config
- [x] add a "service exposure selection" to let the user choose between "LoadBalancer", "NodePort" or Ingress
- [x] adding Prometheus as option (using the Prometheus operator for kubernetes)
- [x] adding README.md with first step instructions (e.g. what is printed by sub-gen after run)
- [ ] adding Zipkin as option
- [x] _adding consul (already implemented earlier)_

feel free to add points or discuss the mentioned. I will maybe need some support of @PierreBesson, especially on Zipkin, as I didn't everything, yet.

**Comment by jdubois** [comment]
Do you have the Registry working well? We're doing a big work to improve it, so it's my current priority

**Comment by xetys** [comment]
Hard to say. It's working, so far. There are some strange things happening like random unavailability of one replica, or the fact that currently one replica replies within 50ms, while the other is taking 5 seconds. But can't say what the cause is.

In general I have no big issues​ with the registry.

**Comment by PierreBesson** [comment]
@xetys, you have basically listed the things I had in mind for improvements to our k8s subgen. I would really like to work on it but I have no time right now. If you can help that would be awesome. Once all of this is done then we can take k8s out of beta.

Also, I thought I already did consul for k8s. Did you try it ?

**Comment by xetys** [comment]
to be honest, I first tried that, what's there. Currently, it is only JHipster Registry, so I started with that. I already tried Consul some time ago in a pure docker based environment. 

Once I generated these k8s configs, I started to change and tune them, by adding Prometheus operator, JHipster console, ingresses, and more. But for completeness a PR would only make sense, if I do also the stuff, I didn't try, yet. Like Consul and Zipkin.

**Comment by xetys** [comment]
@jdubois I fear the registry is not really ready for kubernetes, yet. For a demo setup, there are no issues. But when something bad happens, like a full crash of one minion, the registry doesn't respawn working. I also experience different issues, when starting, while a couple of microservices are trying to connect to the registry...

for the moment, that is my short list:

* the registry initially recognize itself running in replica mode...it forgets that over time
* it happens, that one replica loose all registered services, and generates some kind of a dead zone, especially its bad for gateway and UAA based setups
* it happens, that one replica answers fix within 5 seconds, while the other does in 50ms, and I have no idea why
* during operation, services randomly loose connection to the registry for config renew...for no clear reason

The bad is, I hadn't time to check what's causing that issues in details. But I am running also different stuff as prometheus, kibana, grafana...also running in StatefulSets like the registry do, without issues like this. Even worse is, that these issues might not happen at the beginning. I am watching that and reporting....

@PierreBesson I think I will take a look this week at consul, as it might perform better than eureka. I am also more favoring consistency for my setups over availability. It's super annoying when at the end of a day all the devs are pushing to the CICD pipeline, and it takes up to 10 minutes, till every service is routing to the right service, as a lot of zombie instances are still listed

I hope I will have the time to take ACL support back to the config loader...as my spring cloud consul fix is shipped with Dalston.RELEASE.

**Comment by xetys** [comment]
update, replicating totally failing with 2.6.0, while it works with 2.5.8

**Comment by PierreBesson** [comment]
@xetys I am aware that the registry statefulset is not prod ready and I have never pretented that it was ! It is just a first step toward running a replicated registry (and yes I only tested demo scenarios, I'm not lucky to be able to use this for a real life use case).

#### registry problems
This doesn't surprise me at all, Eureka is tricky to operate and also whatever you do Eureka is much less resilient to failures than Consul.
There are a number of ressources online that explain the Eureka behavior like this one: http://blog.abhijitsarkar.org/technical/netflix-eureka/
I still think that the jhipster-registry can be an appropriate choice for simple architectures but maybe we need to provide a lot of docs.

Also sad to learn that replication is broken with the 2.6 (probably because of the Dalston update)...

**Comment by pascalgrimaud** [comment]
@xetys : are you working on this ticket ? It has been opened since 2 months

**Comment by xetys** [comment]
yes. I've got this in focus. I'm currently working on optimizing larger workloads (~50 services running). I'll contribute my settings soon

**Comment by xetys** [comment]
I would like to add the following point:

[ ] add a "service exposure selection" to let the user choose between "LoadBalancer", "NodePort" or Ingress

as currently `type: LoadBalancer` is used by default, but only works in certain public cloud kubernetes providers, but neither in Minikube nor in custom / bare-metal clusters.

**Comment by PierreBesson** [comment]
@xetys it's a good point. Of course this option is needed. Eventually we would not need the nodePort option if we can configure the ingress for minikube as well.

**Comment by xetys** [comment]
I want to have all 3 options available, as there are a lot of various types of k8s cluster, so our k8s support will be more universal

**Comment by xetys** [comment]
ingress and co. are done.

Now should go on with Prometheus monitoring, and have a question here. On my setups, I'm using the [Prometheus Operator](https://github.com/coreos/prometheus-operator) instead of using own deployments of Prometheus itself. This is nice, as I can just "wire" the metric endpoints to a TPR, which handles the actual Prometheus configuration. 

However, this required the cluster have the operator up and running. Providing manual deployments of Prometheus would be more universal, but also less elegant in k8s terms. What do you thing? @PierreBesson  @pascalgrimaud

**Comment by PierreBesson** [comment]
I already know about the prometheus operator. I think it's OK to use it because it simplifies configuration for us. Also if you already have a working setup then we should go with that.
I wish there was an Elasticsearch operator that we can use for the JHipster Console... Deploying a production Elasticsearch in docker is quite hard...

**Comment by xetys** [comment]
As I continued my work today I noticed a lack of a README file, which at least refers to the instructions printed out by the sub-generator. I would also some more stuff, as it is crucial for the developer to have a small hint how to kick off, what has been generated. I added the point to the list

**Comment by PierreBesson** [comment]
@xetys, Good idea for the readme file. I have recently done something similar for the docker-compose subgen: https://github.com/jhipster/generator-jhipster/blob/master/generators/docker-compose/templates/_README-DOCKER-COMPOSE.md

**Comment by xetys** [comment]
Thanks @PierreBesson for the template

I hope that short doc is helpful. I put some pitfalls of my experience during operating JHipster the past few months. I am thinking of pasting some code of this into our documentation

**Comment by xetys** [comment]
Now only Zipkin is open on my list. As I have to play around with it for some time, I am considering moving that task into a distinct PR and let you all review my current PR and merge it, as there is a lot of useful stuff already, and I don't want to block this because of one missing feature. WDYT? @PierreBesson @jdubois

**Comment by PierreBesson** [comment]
@xetys. Yes the PR is OK like that. I will add Zipkin when I have the time.

**Comment by PierreBesson** [comment]
I will review this soon...

**Comment by xetys** [comment]
As #5927 is merged and was tested on 2 different production grade kubernetes clusters, should we move the sub-gen out of beta? I would suggest doing this as soon as I provide docs for the new updates. WDYT? @jhipster/developers

**Comment by deepu105** [comment]
Im ok with it

**Comment by jdubois** [comment]
Yes let's do this

**Comment by pascalgrimaud** [comment]
+1

**Comment by deepu105** [comment]
@xetys can this issue be closed?

**Comment by xetys** [comment]
If that is ok, I would do that today / tomorrow after extending the docs, to be consistent
