### ISSUE TITLE
[Suggestion] Use getters in entities/DTO equals and hashcode

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#5604]
##### **Overview of the issue**

Equals and hashcode are now using attributes call instead of getters: it would be easier to use them in many aspects

##### **Motivation for or Use Case**

Inheritance of entities need fewer rework of generated entities/dto

##### **Suggest a Fix**

Modify the according Yo template (I can do it if you're ok)

##### **JHipster Version(s)**

4.2.0
##### **JHipster configuration**
N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
N/A

##### **Browsers and Operating System**

Any

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Can you give an example, before/after refactoring ?
This would have a big impact on many people, so I wouldn't change this lightly.
For the record : the original implementation was copied on what Intellij IDEA generates, so we had the same code when you generated those methods with both tools, and that's interesting for consistency.

**Comment by Tcharl** [comment]
Hi jdubois,

I don't think this is a very big change, but I understand the IJ argument: so bad that they don't generate the correct stuff ^^.

Here's the code before refactoring:

`@Entity
public class Project implements Serializable {
@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "title")
    private String title;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public Project title(String title) {
        this.title = title;
        return this;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Project project = (Project) o;
        if (project.id == null || id == null) {
            return false;
        }
        return Objects.equals(id, project.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Project{" +
            "id=" + id +
            ", title='" + title + "'" +
            '}';
    }
}
`


And the one after refactoring of the 'equals' 'hashcode' and 'toString' methods.

` @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Project project = (Project) o;
        if (project.getId() == null || getId() == null) {
            return false;
        }
        return Objects.equals(getId(), project.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(getId());
    }

    @Override
    public String toString() {
        return "Project{" +
            "id=" + getId() +
            ", title='" + getTitle() + "'" +
            '}';
    }`

The idea behind this is that using the refactored code, it's for example easier to move the 'id' attribute in a super class (I'm used to implement an @MappedSuperclass AbstractEntity class where I put my technical stuff like Id, Version, Listeners, Etc.). And if you like the idea I can also implements the according yo generators...

However, this is not a crucial concern, and if it's gonna impact many developper it's not worth it.

**Comment by Tcharl** [comment]
I also googled if that was a good or bad thing to used accessors or not within equals and hashcode and found this article: http://www.ideyatech.com/effective-java-equals-and-hashcode/

They've another argument in favor of the usage of them within these methods: without calling the accessor, the 'other' instance can be a proxy.

**Comment by jdubois** [comment]
Thanks for the clarification, I understand better now.

- I have no idea why Intellij IDEA does it this way -> maybe the performance is a little bit better?
- I don't know if people actually know (and use) our generated code with Intellij IDEA, as they are "compatible"

So I don't have a strong opinion here: I'm quite happy with the current code, and I'm a bit afraid to change it, but on the other hand I agree your implementation looks better.

Does anybody has a strong opinion here? Otherwise I would vote not to change this, as this would impact everyone, and people with existing projects will need to upgrade all their methods

**Comment by Tcharl** [comment]
I don't think that there's a performance issue with 'my' solution (I hope that the compilation or java runtime automagically do the stuff :p).
And I have a 'strong' opinion on it ;), the idea is long term: I hope that one day, JHipster will be able to handle Inheritance and this would be a first step. 
I'm a Modeling (Sirius) and textual DSL (XText) expert, so that I'm able to implement that kind of stuff, but it wouldn't be without any tradeoff: is there a channel where we could discuss about it? Or I can may be write a ticket about it explaining the pros and cons so that we can exchange, but an audio could be a better starter...

**Comment by jdubois** [comment]
- I'm convinced as in your link it looks recommended by "Effective Java"
- Your background is very interesting, as I understand better why you want to do this!
- I think there's still a performance penalty, but that's really minimal

-> can you do a PR?

**Comment by ctamisier** [comment]
It's an option in IntellijIDEA to generate equals/hashcode using getters or not.

**Comment by jdubois** [comment]
Closing as the PR is merged!
