### ISSUE TITLE
WARNING in ./src/main/webapp/app/app.constants.ts

### ISSUE THREAD

**Issue by glxiong** [jhipster/generator-jhipster#5616]
I am using JHipster 4.3. After the default generation, I got two warnings when I run yarn start.
JHipster 4.2 was fine though.

WARNING in ./src/main/webapp/app/app.constants.ts
[2, 5]: Identifier '_VERSION' is never reassigned; use 'const' instead of 'let'.
[3, 5]: Identifier '_DEBUG_INFO_ENABLED' is never reassigned; use 'const' instead of 'let'.

 @ ./src/main/webapp/app/blocks/config/prod.config.ts 4:22-52
 @ ./src/main/webapp/app/app.main.ts
 @ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/app/app.main

**Comment by deepu105** [comment]
Its normal and should go away in next release
