### ISSUE TITLE
Removing IntelliJ configuration file while using yo jhipster:upgrade

### ISSUE THREAD

**Issue by Ckram** [jhipster/generator-jhipster#5618]
##### **Overview of the issue**

When using yo jhipster:upgrade for the first time (when no jhipster_upgrade branch exists yet) it deletes the IDE (IntelliJ IDEA) configuration files

##### **Motivation for or Use Case**

It should not delete them because  they should be ignored.

##### **Reproduce the error**

run yo jhipster:upgrade
Then IntelliJ does not recognize the project

 I think its done in the cleanUp() of the subGenerator.

{
  "generator-jhipster": {
    "jhipsterVersion": "4.3.0",
    "baseName": "name",
    "packageName": "com.package.name",
    "packageFolder": "com/package/name",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.10.0

node: v6.10.0

npm: 4.3.0

bower: 1.8.0

gulp:
[10:25:16] CLI version 1.2.2
[10:25:16] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Skit5** [comment]
Have you tried to ignore them like explained here ?
https://jhipster.github.io/configuring-ide-idea/

**Comment by Ckram** [comment]
Yes I had to do it again after the upgrade to let idea recognize my files

**Comment by pascalgrimaud** [comment]
The subgenerator upgrade used git to upgrade by starting on a clean branch, without your idea config
So I confirm the issue, but I'm not sure if we can do something about that

If you have something to propose to improve this subgenerator, feel free to do a PR @Ckram

**Comment by jdubois** [comment]
Closing as the PR is merged
