### ISSUE TITLE
Switch to AngularCli

### ISSUE THREAD

**Issue by stevehouel** [jhipster/generator-jhipster#5624]
Check and migrate our actual Webpack configuration to be fully compatible with Angular-Cli

 - [ ] Add compatibility for tests (Protractor and Karma) 
 - [ ] Manage environnement vars (Version and Debug_Info)
 - [ ] Manage Build for Dev and Prod with those build options :
  * Build TS
  * Import Vendor scripts
  * Notify build status
  * Compile SCSS files
  * Manage CSS
  * Manage images / policy loading
  * BrowserSync
  * Webpack Visualizer
  * SourceMap
  * PostCSS
 - [ ] Proxify server backend API
 - [ ] Lint 

I guess that I write all our webpack actual work.

**Comment by gmarziou** [comment]
Are we really using PostCSS? I can see it btu with an empty config file so I'm not sure it does something.

**Comment by deepu105** [comment]
@gmarziou we are not using but we provide the setup so that people can add if they want. may be we could provide some basic setup

**Comment by jdubois** [comment]
- Not sure it's doable as we are doing so much more than Angular CLI. And don't forget we also need to have the prod build working (with caching, etc).
- We should start working **soon** on JHipster React, so I'd rather have a common Webpack configuration for both

Then, indeed, I agree this would be much simpler, and probably much better: I see you are working on a PR on this, and all I wanted to state is that it's going to be hard :-)
@deepu105 @sendilkumarn are you OK with this?

**Comment by deepu105** [comment]
@jdubois I have the same feeling as well but if @stevehouel is confident that it can be done we should give him a chance to do a PR and we can decide after reviewing it

**Comment by jdubois** [comment]
Yes totally agreed! Good luck @stevehouel :-)

**Comment by stevehouel** [comment]
Yess I know thx @jdubois :)
Le jeu. 20 avr. 2017 à 11:45, Julien Dubois <notifications@github.com> a
écrit :

**Comment by muralihr** [comment]
Hi,
does it mean that if i say ng new component that will be created ?

**Comment by jdubois** [comment]
Please use Stackoverflow, don't pollute the thread

**Comment by deepu105** [comment]
@muralihr yes it should be but don't expect it to be completely wired into the app like how JHipster does. You will get exactly what the CLI generates

**Comment by deepu105** [comment]
and yes please use SO or our Gitter chat if you have further question

**Comment by muralihr** [comment]
Pardon ~ @jdubois  @deepu105

**Comment by deepu105** [comment]
I don't think we are gonna do this as our config has become even more complex. @stevehouel sorry that you already spent quite a lot of effort on this. Let's revisit in the future

**Comment by jdubois** [comment]
I'm really sad we didn't merge this, really sorry @stevehouel !!!! I was really hoping this worked out.
Then we also need to prepare for React support, and hopefully it's possible to have some common code for both.

**Comment by stevehouel** [comment]
No worries :) Maybe we could add a question for user to choose between
webpack and angularcli on project generation. Otherwise a will do a
submodule on market place :)
Le lun. 26 juin 2017 à 10:17, Julien Dubois <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
Yes, and what is **very very very** important to me is that we are compatible with Angular CLI. I'm doing a side-project with JHipster, and that is really useful when you don't do CRUD.
