### ISSUE TITLE
#Bug# Validation is wrong for maximum value in text field

### ISSUE THREAD

**Issue by AmsaveniMidhun** [jhipster/generator-jhipster#5630]
I have created an entity and created some fileds along with validations. For one field- Contact number, I have enables validations like Required, Minimum Value as 10 and Maximum Value as 20.

Here, the maximum value, instead of considering about the number of digits, its considering the Value entered. (i.e)  If i provide 10 digit , its showing error. If i type 20 or less than that, its not showing any error.

I feel its a defect, since in validation, minimum and maximum value supposed to be number of digits rather than value.
![error](https://cloud.githubusercontent.com/assets/26814654/25223628/817945c8-25d9-11e7-8452-eba0358cc6a2.PNG)

**Comment by jdubois** [comment]
This depends on your configuration, version, database... Sorry but we need more information

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
