### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by raghava-k2** [jhipster/generator-jhipster#5632]
Hi
Can you tell me how we can deploy spring boot war and www static content in tomcat-8.
I tried to deploy bit the static content base url is different from war name because of this the rest calls are failing.if we change the base url to app context name the static js are not getting loaded.
So please  let me know the steps for deployment

**Comment by gmarziou** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
