### ISSUE TITLE
Regression: Generating a TextBlob creates a file upload field in 4.3.0

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#5634]
In JHipster 4.3.0, using `TextBlob` as a field in JDL results in a file upload field being generated. In 4.0.8, a `<textarea>` is generated.

JDL: https://github.com/jhipster/jdl-samples/blob/master/blog.jh

<img width="841" alt="screen shot 2017-04-20 at 10 29 20 pm" src="https://cloud.githubusercontent.com/assets/17892/25262979/5b363426-2619-11e7-8657-8e3d378aab3a.png">

Issue reported in jhipster4-demo project: https://github.com/mraible/jhipster4-demo/issues/6

**Comment by deepu105** [comment]
Hi Matt there was a bug in JHipster core. Its corrected and released. We need to update the version in jhipster for next release. Ill do it in master today.

**Comment by mraible** [comment]
@deepu105 What release will this fix be in? I need this to work for conference demos next week (at J-Spring and Devoxx UK), or I'll have to use an older version.

**Comment by deepu105** [comment]
Its updated in master so should be in the next release. Can you use master?

**Comment by mraible** [comment]
Yes, I can use `master` for demos. However, I'm also writing a tutorial and doing a screencast. I'd rather use a released version for those. I can write a draft of the tutorial, and update/publish it after the next release.

**Comment by jdubois** [comment]
Not sure when I'll do the next release - I'd like to have the new registry (with the work from @JulienMrgrd ), but it's not totally finished and I don't have much time to work on the project at the moment

**Comment by deepu105** [comment]
may be we can do a patch release inbetween


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
I'm going to try to do a release on Friday, or over the week-end. It depends on the bugs we still have opened.

**Comment by deepu105** [comment]
Closed in jhipster-core
