### ISSUE TITLE
Symlinks' yarn error in docker-container on Windows

### ISSUE THREAD

**Issue by thecolas** [jhipster/generator-jhipster#5643]
**I open the issue here because I can't open issue in the project [jhipster.github.io](https://github.com/jhipster/jhipster.github.io)**

On Windows only administrator can create symlinks. So there are an error during the `yarn install`.
To fix it you need to launch docker quick terminal as administrator.

Can you add a note in the [Installing JHipster documentation](https://jhipster.github.io/installation/) ?

> *Warning*: On Windows, you need to execute the **Docker Quick Terminal** as **Administrator** to be able to create **symlinks** during the `yarn install` step.

**Comment by pascalgrimaud** [comment]
I don't understand the issue.
Can you describe in details what you did plz?

**Comment by thecolas** [comment]
I try to use jhipster with the docker container on Windows. So I install Docker-ToolBox and create a new jhipster container and execute `yo jhipster`.

During the `yarn install` step of `yo jhipster` I got a error that said that I cannot create symlinks. Run `yo jhipster` with `--npm` or exectue the install step manualy didn't fix the problem.

I got this error because, on windows, only administrator can create symlinks. To solve this you need to launch **Docker Quick Terminal** in administrator mode.

So I asked if you can add a tip in this page [https://jhipster.github.io/installation/](https://jhipster.github.io/installation/) to help people who try to use jhipster whith docker-container on WIndows. I write the tips just below : 

> *Warning*: On Windows, you need to execute the **Docker Quick Terminal** as **Administrator** to be able to create **symlinks** during the `yarn install` step.

---------------------------

I know that is not the right project for this issue but I can create issue on jhipster/jhipster.github.io.

**Comment by pascalgrimaud** [comment]
@thecolas : you're in the right place for opening ticket to improve our documentation. It was me who didn't understand your use case.
So yes, plz can you PR to jhipster.github.io to improve the installation page. I reopen the ticket until it is documented.

**Comment by jdubois** [comment]
I did the change, and now checking the documentation I see it's already done (see the "Your first project" section) -> so I'm reverting my change, and keeping this closed

**Comment by thecolas** [comment]
It's not the same problem. If you use the `--npm` you also get the symlinks problem on Windows.
`npm install` or `yarn install` create symslinks, so you realy need to run docker quick terminal (or Kitenatic) as administrator to allow the install step to create symlinks.

**Comment by jdubois** [comment]
Then I don't really understand this... Can you check https://github.com/jhipster/jhipster.github.io/commit/fc35317c93afb7ba94c5e336ca0d96181dde0258 if that's fine with you? I can revert it back.
Or you can do a PR to that file, with what you think is better, as you clearly know this better than me.

**Comment by thecolas** [comment]
I think you can revert back. I will reproduce the problem this WE to give more revelant log in this issue.

**Comment by jdubois** [comment]
Done!
