### ISSUE TITLE
Always Error 401 after a successful authentication!

### ISSUE THREAD

**Issue by oussama-benmahmoud** [jhipster/generator-jhipster#565]
Hi there, I'm using latest version of jHipster, but I deleted all the webapp files I just made an index file that says something like "Server is running..." I wanted to separate front-end code and backend code. I implemented CORSFilter to enable cross-origin AJAX requests. The front-end app made with angularJs, I used the same authentication techniques from jHipster and it uses port 9000. The backend app uses port 8080. Everything works fine with Logs, Audits, Api-doc...but when I wanted to make the security part works now I always gets Error 401 Access Denied in the console. I used the same angularJs services that you used like "AuthenticationSharedService", "Sessions", "Session"...

Here's what I've got in Eclipse console:

<code>
[DEBUG] com.reserveandcollect.adminapp.security.UserDetailsService - Authenticating admin
Hibernate: select user0_.login as login1_14_0_, user0_.created_by as created_2_14_0_, user0_.created_date as created_3_14_0_, user0_.last_modified_by as last_mod4_14_0_, user0_.last_modified_date as last_mod5_14_0_, user0_.user_activated as user_act6_14_0_, user0_.user_activation_key as user_act7_14_0_, user0_.user_address as user_add8_14_0_, user0_.user_cin as user_cin9_14_0_, user0_.user_email as user_em10_14_0_, user0_.user_fullname as user_fu11_14_0_, user0_.user_lang_key as user_la12_14_0_, user0_.user_password as user_pa13_14_0_, user0_.user_status as user_st14_14_0_ from T_USER user0_ where user0_.login=?
Hibernate: select authoritie0_.login as login1_14_0_, authoritie0_.authority_name as authorit2_15_0_, authority1_.authority_name as authorit1_1_1_ from T_USER_AUTHORITY authoritie0_ inner join T_AUTHORITY authority1_ on authoritie0_.authority_name=authority1_.authority_name where authoritie0_.login=?
[DEBUG] com.reserveandcollect.adminapp.security.CustomPersistentRememberMeServices - Creating new persistent login for user admin
Hibernate: select persistent0_.series as series1_6_0_, persistent0_.ip_address as ip_addre2_6_0_, persistent0_.token_date as token_da3_6_0_, persistent0_.token_value as token_va4_6_0_, persistent0_.user_login as user_log6_6_0_, persistent0_.user_agent as user_age5_6_0_ from T_PERSISTENT_TOKEN persistent0_ where persistent0_.series=?
Hibernate: insert into T_PERSISTENT_TOKEN (ip_address, token_date, token_value, user_login, user_agent, series) values (?, ?, ?, ?, ?, ?)
[DEBUG] com.reserveandcollect.adminapp.aop.logging.LoggingAspect - Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Mon Sep 08 22:53:44 CET 2014, principal=admin, type=AUTHENTICATION_SUCCESS, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@b364: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: null}]]
Hibernate: insert into T_PERSISTENT_AUDIT_EVENT (event_date, event_type, principal, event_id) values (?, ?, ?, ?)
Hibernate: insert into T_PERSISTENT_AUDIT_EVENT_DATA (event_id, name, value) values (?, ?, ?)
[DEBUG] com.reserveandcollect.adminapp.aop.logging.LoggingAspect - Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
[DEBUG] com.reserveandcollect.adminapp.aop.logging.LoggingAspect - Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Mon Sep 08 22:53:44 CET 2014, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={message=Access is denied, type=org.springframework.security.access.AccessDeniedException}]]
Hibernate: insert into T_PERSISTENT_AUDIT_EVENT (event_date, event_type, principal, event_id) values (?, ?, ?, ?)
Hibernate: insert into T_PERSISTENT_AUDIT_EVENT_DATA (event_id, name, value) values (?, ?, ?)
Hibernate: insert into T_PERSISTENT_AUDIT_EVENT_DATA (event_id, name, value) values (?, ?, ?)
[DEBUG] com.reserveandcollect.adminapp.aop.logging.LoggingAspect - Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
[DEBUG] com.reserveandcollect.adminapp.security.Http401UnauthorizedEntryPoint - Pre-authenticated entry point called. Rejecting access</code>

And here's what I've got in Safari console: 

<code>
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized)
http://localhost:8080/app/rest/account
</code>

I hope you can assist me on this issue.
Thank you.

**Comment by sanderman123** [comment]
Maybe still helpful to someone:
I had a similar issue when I was testing the swagger API docs of the standard JHipster generated app using grunt (port 3000), if however I went directly to the webapp running on port 8080 it worked.

**Comment by cbornet** [comment]
The issue with grunt is that springfox (swagger lib) detects port 8080 for the host instead of 3000 so the requests are made cross domain. I think you can force the springfox host in your application.yml.
As for making CORS work with the session, you need to put the withCredentials flag on the xhr request and configure access-control-allow-credentials to true on the server.
Note that swagger-ui doesn't set the withCredentials flag by default

**Comment by cbornet** [comment]
@sanderman123 see #2654
