### ISSUE TITLE
Social login Routes from android application

### ISSUE THREAD

**Issue by khocef** [jhipster/generator-jhipster#5651]
Hello,
(This is not a bug)
Can someone explain how to use jhipster social login from another web app or mobile app (hybrid or native). 

This POST route  http://localohost:90s00/sitgnin/facebook retuns a webpage 

Thanks

**Comment by jdubois** [comment]
Please use StackOverflow for questions, we're there too

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
