### ISSUE TITLE
Is there a GUI client for `generator-jhipster`

### ISSUE THREAD

**Issue by dinukadesilva** [jhipster/generator-jhipster#5656]
I'm looking a way to create a GUI client for my jhipster-generator and was searching whether such a feature is already available with jhipster or as a plugin.

Appreciate your comments on this and I would like to contribute creating a new plugin if this is not available.

Regards,
@dinukadesilva

**Comment by cloud4288** [comment]
There are yeoman generator plugin for both IntelliJ and Netbeans, you can use those.

**Comment by jdubois** [comment]
There are GUIs for Yeoman, and my original idea that those would provide GUIs for free for JHipster.
Unfortunately, all those I have tried do not work well. So I don't recommend any of them.

**Comment by dinukadesilva** [comment]
@cloud4288 

My question is whether I can get opened a UI (may be in the browser) at the time I generate a project. As an alternative to command line prompts.

For an example,

![image](https://cloud.githubusercontent.com/assets/10680296/25370523/fcbc87b8-29a8-11e7-816d-2fb117ab8c46.png)

**Comment by jdubois** [comment]
And that was my answer... Have a look at the Yeoman GUIs, but they have issues with prompt validation and sub-generators. We use the Yeoman APIs in a rather advanced way.

**Comment by dinukadesilva** [comment]
Thanks @jdubois

 I'll have a look
