### ISSUE TITLE
Jhipster unable to regenerate table

### ISSUE THREAD

**Issue by dhiren-hamal** [jhipster/generator-jhipster#5663]
Hi! Jhipster team,
I've a JHipster project where I created a simple entity called VehicleAuthority which was working pretty fine. However, I deleted its corresponding table from H2 console for some reson, now when I restarted jhipster, the table is not being created.

Thanks

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
