### ISSUE TITLE
How to change App build version displayed on the home page?

### ISSUE THREAD

**Issue by delkant** [jhipster/generator-jhipster#5665]
I couldn't find a documentation on how to upgrade my app version(hopefully running a jhipster or mvn command)

If I have to do it manually, what is the best place to change this value?

Thanks.

**Comment by jdubois** [comment]
In your `pom.xml`

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by delkant** [comment]
I did that before and didn't work just changing the value and running mvn. 

You have to run independently: 

`gulp install
` 

This will take the value changed in the pom.xml, but thanks for confirming that was the place.

**Comment by deepu105** [comment]
Its a bug as we are reading package.json instead of POM. Its in the TODO
for angular improvements
