### ISSUE TITLE
DB Migration issue with docker compose

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#5668]
.yo-rc.json file

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "gateway1",
      "microservicePath": "microservice1"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "gatewayapp",
    "packageName": "com.gateway.com",
    "packageFolder": "com/gateway/com",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "1cb3d805808656382fa1bb75ba7654d17b4a1dea",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

I have database for my gate way app. 

docker compose file like this. 

version: '2'
services:
    microservice-app:
        image: microservice-app
        external_links:
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:ws123@registry:8761/config
            - JHIPSTER_SLEEP=10
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    gateway-app:
        image: hiringapp
        external_links:
            - gateway-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:ws123@registry:8761/config
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
        ports:
            - 8081:8081
    gateway-cassandra-node:
        image: cassandra:3.9
        links:
            - gateway-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
        volumes:
            - /home/ubuntu/db/cassandra:/var/lib/cassandra
    gateway-cassandra-migration:
        container_name: gateway-cassandra-migration
        environment:
            - CASSANDRA_CONTACT_POINT=gateway-cassandra
            - USER=docker-cassandra-migration
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
        build:
            context: ../gateway/src/main/docker
            dockerfile: cassandra/Cassandra-Migration.Dockerfile
        volumes:
            - ../gateway/src/main/resources/config/cql:/cql:ro
        links:
            - gatway-cassandra
    gateway-cassandra:
        container_name: gateway-cassandra
        image: cassandra:3.9
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
    jhipster-logstash:
        extends:
          file: jhipster-console.yml
          service: jhipster-logstash
    jhipster-console:
        extends:
            file: jhipster-console.yml
            service: jhipster-console

When i do docker compose up, migration container will drop the exiting key space and recreate the keyspace and run cql scripts again. 

I want to maintain data in production but not in local. How to achieve this docker compose, if not docker compose what would be best option

**Comment by pascalgrimaud** [comment]
You need to have a look at how the migration cassandra works with Docker: https://jhipster.github.io/using-cassandra/

The process won't never drop an existing keyspace, and won't run an existing cql scripts if it has already run. 

You need to be carefull about your container too, as there is no volume mount by default (you can uncomment the volume in docker compose files) if you stop and delete your container, you will delete the data too.

Closing this ticket as there is no issue for me.

**Comment by JinnaBalu** [comment]
I have mounted this docker container to my local volume 
gateway-cassandra-node:
image: cassandra:3.9
links:
- gateway-cassandra:seed
environment:
- CASSANDRA_SEEDS=seed
volumes:
- /home/ubuntu/db/cassandra:/var/lib/cassandra

Where can i give the volume in the above services.

**Comment by pascalgrimaud** [comment]
You should use stackoverflow instead, and look at the docs about Cassandra and Docker.
There is no issue here with JHipster, unless you can describe all steps to reproduce it.
