### ISSUE TITLE
Generated Web Rest Tests should not reference EntityManager class

### ISSUE THREAD

**Issue by systemsplanet** [jhipster/generator-jhipster#5670]
##### **Overview of the issue**
All references to EntityManager class should be removed from Generated Web Rest Unit Tests.
The Generated Test class makes rest calls to Repos that use the EntityManager. 
The Generated Web Rest Tests themselves to not need EntityManagers.
##### **Motivation for or Use Case**

Unnecessary Dependency. Confusing.  

##### **Reproduce the error**

Just build a project

##### **Related issues**
Not necessary, but it would make it much easier for people to add new data sources if HJ includes the  Repo Annotations and add the default config for EntityManagerFactory and TransactionManager.

Edit https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/java/io/github/jhipster/sample/config/DatabaseConfiguration.java

Add lines:
  @Primary
  @Bean(name = "transactionManager")
    public PlatformTransactionManager transactionManager(@Qualifier("entityManagerFactory") EntityManagerFactory entityManagerFactory) {
        return new JpaTransactionManager(entityManagerFactory);
    }

    @Primary
    @Bean(name = "entityManagerFactory")
    public LocalContainerEntityManagerFactoryBean entityManagerFactory(EntityManagerFactoryBuilder builder, @Qualifier("dataSource") DataSource dataSource) {
        LocalContainerEntityManagerFactoryBean _emf = builder
                    .dataSource(dataSource)
                    .packages(User.class.getPackage().getName())
                    .persistenceUnit("primary")
                    .build();
        return _emf;
    }

Edit repos, for example: https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/java/io/github/jhipster/sample/repository/BankAccountRepository.java

Add lines:
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;
@PersistenceContext(unitName = "primary")
@Transactional(transactionManager = "entityManagerFactory", readOnly = true)

With these simple changes in place, adding a new data souce, or moving a repo is simple:
1. add a new spring DataSource bean 
 @Bean(name = "NEW_DS", destroyMethod = "close")
    public DataSource fixDataSource() {... }

2. clone the transactionManager above
  change     @Bean(name = "NEW_MGR") and @Qualifier("NEW_FACTORY")

3. clone the entityManagerFactory 
  remove @Primary
  change  @Bean(name="NEW_FACTORY") @Qualifier("NEW_DS") .packages(NEW_DOMAN_PACKAGES) .persistenceUnit("NEW_UNIT")

4. configure Repos that use the new data souce with the annotations 
PersistenceContext(unitName = "NEW_UNIT")
Transactional(transactionManager = "NEW_FACTORY", readOnly = true)

##### **Suggest a Fix**
To fix this generated test:
https://github.com/jhipster/jhipster-sample-app/blob/master/src/test/java/io/github/jhipster/sample/web/rest/BankAccountResourceIntTest.java

Remove:  @Autowired       private EntityManager em;
Change: createEntity(EntityManager em) to  createEntity()
Change:   bankAccount = createEntity(em);   to    bankAccount = createEntity();
##### **JHipster Version(s)**
Current
##### **JHipster configuration**
ALL
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
ALL
##### **Browsers and Operating System**
ALL
- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Sorry, this is not obvious but we need this, for testing other entities that have a relationship with the current entity.
This is annoying and I would have liked to find a better solution, but there is no way to know if an entity will have a relationship in the future, so we keep that method just on case.
Then, you have a very specific use case with 2 datasources, which is not our default setup (and not something I would advise, but you probably have a good reason to do this).
