### ISSUE TITLE
After a first social login, shall the user be signed in instead of having an email confirmation?

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#5674]
##### **Overview of the issue**

After a first Facebook successfully signing in, you will get the following message:

Registration with
Registration saved! Please check your email for confirmation.
Sign in with Facebook

##### **Motivation for or Use Case**

The email is a notification without any action request for the user. For this user case, one should be signed into the application as what the sign in action shall do.

##### **Reproduce the error**

To reproduce this case, click the Facebook sign in. You need to upgrade the spring-social-facebook to 3.0.0.M1 first.

##### **Suggest a Fix**

Inserting a line of Spring Security sign in in the createUserIfNotExist method of the SocialService class. For the front end, a tool bar refresh is needed.

I have the back end code change. If someone can point me where the front end code change taking place, I can get it done as well.

##### **JHipster Version(s)**

4.3.0

**Comment by jdubois** [comment]
We can't upgrade to a milestone version as it's not in the main Maven central repo, so this can't be done right now.
Then for the use case itself, I'm not totally sure: this was clearly coded on purpose, look for the `sendSocialRegistrationValidationEmail` method and the `socialRegistrationValidationEmail.html` template... I think it's to have the same workflow as the rest. I'm not the author of this code, so I'm only guessing here, but it doesn't look bad to me.

**Comment by jdubois** [comment]
We have far too many issues opened right now, and I need to prioritize, and as this isn't broken, I'm closing this.

**Comment by vw98075** [comment]
The current release of Spring Social Facebook isn't working due to some changes on the FB side. The release date is Dec, 2015. I understand it isn't a high priority item. I thought that I could fix on my own project and contribute my fixes.
