### ISSUE TITLE
OpenId / Steam Login

### ISSUE THREAD

**Issue by mtdx** [jhipster/generator-jhipster#5686]
Hello

I've been tying to implement openid steam login without any luck, I'm adding at.molindo.social open id spring social and OpenIdConnectionFactory to addConnectionFactories but it doesn't work, I don't even know where to put the steam API key, while there are many login options, there is no alternative to openId for steam API.  

Thanks

**Comment by pascalgrimaud** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by pascalgrimaud** [comment]
This is a bug tracker here.
You should go to stackoverflow instead.

**Comment by mtdx** [comment]
@pascalgrimaud this was a feature request, openid is just missing is not a bug, the problem was approached on stackoverflow and the answer is just that is a missing feature.

**Comment by pascalgrimaud** [comment]
I don't think we will implement it as we have a lot of issues right now.
You can read the old ticket here: https://github.com/jhipster/generator-jhipster/issues/2204
Maybe you will find something interesting.

Don't hesitate to try to do it as a module too: https://jhipster.github.io/modules/creating-a-module/

**Comment by mtdx** [comment]
@pascalgrimaud I did read first the old ticket and went further, tried to do it, without luck, it did not work.
