### ISSUE TITLE
Remote Elasticsearch cluster connection issue with the existing code

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#5704]
[prod]
running app, database, elasticsearch in three different instances(ubuntu servers). 

able to connect app with remote instance of cssandra cluster, the following changes are made in application-prod.yml

         

    data:

        cassandra:
            contactPoints: 10.0.0.11
            protocolVersion: V4
            compression: LZ4
            keyspaceName: jhipsterdb
            repositories:
                enabled: false

 not able to connect to the elasticsearch

      data:
        elasticsearch:
            cluster-name: elasticsearch
            cluster-nodes: 10.0.0.10:9300

do we need to wright any code for this to be connected

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
Please use Stackoverflow
