### ISSUE TITLE
is there any way to generated code for android (or ios) client?

### ISSUE THREAD

**Issue by zzsoszz** [jhipster/generator-jhipster#5705]
* **Overview of the request**

is there any way to generated code for android (or ios) client?

* **Motivation for or Use Case** 

there is  a eixsits android(or ios) app,and i want some client code generated by jhipster.just like the android client generated  by swagger

* **Browsers and Operating System** 

win 10

* **Related issues** 

https://github.com/jhipster/generator-jhipster/issues/5687

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
Please use Stackoverflow

**Comment by jdubois** [comment]
I just realize that's the second time you do this: please don't spam the bug tracker, this will just get you banned. Follow the guidelines, use Stackoverflow, and don't waste our time.
