### ISSUE TITLE
Move common code for cloud deployment sub generators to base

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#5710]
Currently `docker-compose/prompts` promts are reused in k8s and rancher sub gen and they are used in upcoming openshift generator #5703 as well so I think it wiull be better to refactor all the common code into a bsed file to avoid duplication and side effects if something changes in future. We dont want rancher failing if we change something in docker-compose sub gen and so on

**Comment by stevehouel** [comment]
I already did that refactoring when implementing my generator for Mesos Marathon. So when PR will be merged for Openshift I will do my refactor on it to. I was also thinking on doing only one module for Cloud generator and have a multi-choice  on which export to do (rancher, mesos, openshift, k8s ...) and then merge all code into one (lot of work I know) which will remove all duplicate code

**Comment by pascalgrimaud** [comment]
I was thinking about this when there was the new Kubernetes subgenerator which uses some methods from docker-compose subgenerator.
So +1

**Comment by deepu105** [comment]
Lets fisrt move common code. Merging all together will make it too complex
at this point


Thanks & Regards,
Deepu

**Comment by stevehouel** [comment]
Ok, so that will be done with my new mesos marathon module. So you can
assign it to me if you want
Le ven. 5 mai 2017 à 18:21, Deepu K Sasidharan <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
@stevehouel are you working on this?

**Comment by stevehouel** [comment]
Yes i m working on it. My new mesos marathon module and the code
refactoring should be available this week

**Comment by deepu105** [comment]
Merged
