### ISSUE TITLE
Rename "javascript" into "typescript" for test folder

### ISSUE THREAD

**Issue by wmarques** [jhipster/generator-jhipster#5718]
##### **Overview of the issue**

The folder containing front end tests should be named typescript when we use Angular, and javascript when we use AngularJS

##### **Motivation for or Use Case**

It can be confusing to see "javascript" in a typescript app 😄 

##### **Reproduce the error**

Generate an app and choose Angular 4

##### **JHipster Version(s)**

master

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
it makes sense, so +1

**Comment by sendilkumarn** [comment]
this also means that we have to change the `conf` files to `typescript` right ?

**Comment by pascalgrimaud** [comment]
Just look for this change:
- it will impact a lot of files (package.json, tsconfig.json, README.md, .angular-cli.json, .gitignore)
- then, in our generator, we use this constant [CLIENT_TEST_SRC_DIR](https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-constants.js#L76), so we need to add another one specific for Angular2, which impact again a lot of files

So, it makes sense but I change my mind as there is no real value to do this and it's a lot of work.
What do you think @wmarques ? Maybe do this later ?

**Comment by deepu105** [comment]
Yes its not much value and ts is just a js superset so it doesn't matter

**Comment by deepu105** [comment]
Closing this as we have far more pressing issues in backlog
