### ISSUE TITLE
Steam OpenId Login

### ISSUE THREAD

**Issue by mtdx** [jhipster/generator-jhipster#5728]
Any way we can get steamcommunity.com login?, if not can anyone point me in the right direction, I can try to submit a PR but I have no idea where to start from, of even if it is possible. 

Thanks

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
I also answered you on Twitter... Please don't spam the team
