### ISSUE TITLE
Use Instant in PersistentAuditEvent instead of LocalDateTime

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#5738]
I think Instant would be more relevant than LocalDateTime for auditEventDate field of PersistentAuditEvent.
If agree, I can PR.

**Comment by pascalgrimaud** [comment]
Agree for this change. 
But will the existing applications / existing database be impacted by this change ? I dont think so, but I want to be sure.

**Comment by cbornet** [comment]
Well, there will probably be an offset if you had the dangerous idea of setting your server/JVM timezone to anything other than UTC...
On the other hand, I really think storing local datetimes in db with the jvm timezone like we do now is a bad bad idea.

**Comment by cbornet** [comment]
I don't even want to start to imagine what happens if the db is in yet another timezone...
