### ISSUE TITLE
Remove autocmdr dependency

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#5747]
I added [autocmdr](https://github.com/Hypercubed/autocmdr) for #5726 but seems like they have a bunch of very old dependencies which was causing a node engine incompatibility issue in our travis build. 
Its temporarily fixed by using the yarn `--ignore-engines` flag but its better to have the dependencies updated.

I raised an [issue with autocmdr](https://github.com/Hypercubed/autocmdr/issues/20) for this but if there is no response on that I think its better to remove the dependency and use the required features (logger, auto completion and help) directly using appropriate libs.

**Comment by jdubois** [comment]
I didn't know about this dependency, but it only has 15 stars and hasn't been updated for 2 years -> we shouldn't be using this in the first place, we need to build on top of well-established, well-maintained libraries. We shouldn't wait for them, let's remove this.

**Comment by sendilkumarn** [comment]
yeah please remove it

**Comment by deepu105** [comment]
@jdubois I already started work to remove it but not enough time to finish but I will do it probably next week

**Comment by deepu105** [comment]
@jdubois its removed and autocompletion is implemented directly using node-tabtab works well on my system. can you test it please? @pascalgrimaud @ruddell @sendilkumarn can you guys test as well

**Comment by pascalgrimaud** [comment]
it works! great @deepu105 

I install it with Yarn. I had an error because I don't use `sudo yarn` but the `jhipster` is installed in this folder: `~/.config/yarn/globa/node_modules/.bin/`

Here my logs:

```
╭─pgrimaud@xps ~/projects/jhipster/generator-jhipster  ‹master› 
╰─$ yarn global add file:/home/pgrimaud/projects/jhipster/generator-jhipster         141 ↵
yarn global v0.23.2
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "generator-jhipster@4.4.1" with binaries:
      - jhipster
warning No license field
error We don't have permissions to touch the file "/usr/bin/jhipster".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
╭─pgrimaud@xps ~/projects/jhipster/generator-jhipster  ‹master› 
╰─$ which jhipster                                                                     1 ↵
/home/pgrimaud/.config/yarn/global/node_modules/.bin/jhipster
╭─pgrimaud@xps ~/projects/jhipster/generator-jhipster  ‹master› 
╰─$ jhipster --help

  Usage: jhipster [command] [options]


  Commands:

    app|a                          Creates a new JHipster application based on the selected options
    aws                            Initializes a AWS app and generates a WAR file that is ready to push to AWS.
    ci-cd|ci                       Creates pipeline scripts for various CI/CD tools based on the selected options
    client                         Creates a new JHipster client side application based on the selected options
    cloudfoundry|cf                Generates a `deploy/cloudfoundry` folder with a specific manifest.yml to deploy to Cloud Foundry
    docker-compose|dc              Creates all required Docker deployment configuration for the selected applications
    entity|e [name]                Creates a new JHipster entity: JPA entity, Spring server side components and Angular client side components
    export-jdl|ejdl [jdlFile]      Creates JDL from the json entities
    heroku|hr                      Initializes a Heroku app and generates a WAR file that is ready to push to Heroku
    import-jdl|ijdl [jdlFiles...]  Creates entities from the passed JDL file location
    info|i                         Display information about your current project and system
    kubernetes|k8                  Creates all required Kubernetes deployment configuration for the selected applications
    languages|ln [languages...]    Select languages from a list of available languages. The i18n files will be copied to the /webapp/i18n folder
    openshift|os                   Creates all required OpenShift deployment configuration for the selected applications
    rancher-compose|rc             Creates all required rancher-compose deployment configuration for the selected applications
    server                         Creates a new JHipster server side application based on the selected options
    service [name]                 Creates a new JHipster service: this is a simple transactional Spring service bean
    upgrade|up                     Updates JHipster version, and upgrades generated application
    completion                     Print command completion script

  Options:

    -h, --help     output usage information
    -d, --debug    enable debugger
    -V, --version  output the version number

  For more info visit https://jhipster.github.io

```

**Comment by pascalgrimaud** [comment]
Because I use the generator-jhipster from master, I had to change the link:

```
╭─pgrimaud@xps ~/tmp/15-toto  
╰─$ cd ~/.config/yarn/global/node_modules/.bin 
╭─pgrimaud@xps ~/.config/yarn/global/node_modules/.bin  
╰─$ ls -al
total 24
drwxr-xr-x   2 pgrimaud pgrimaud  4096 mai   16 08:10 .
drwxr-xr-x 558 pgrimaud pgrimaud 20480 mai   16 08:10 ..
lrwxrwxrwx   1 pgrimaud pgrimaud    18 mai   16 08:10 bower -> ../bower/bin/bower
lrwxrwxrwx   1 pgrimaud pgrimaud    23 mai   16 08:10 gulp -> ../gulp-cli/bin/gulp.js
lrwxrwxrwx   1 pgrimaud pgrimaud    22 mai   16 08:10 istanbul -> ../istanbul/lib/cli.js
lrwxrwxrwx   1 pgrimaud pgrimaud    37 mai   16 08:10 jhipster -> ../generator-jhipster/cli/jhipster.js
lrwxrwxrwx   1 pgrimaud pgrimaud    16 mai   16 08:10 yo -> ../yo/lib/cli.js
lrwxrwxrwx   1 pgrimaud pgrimaud    29 mai   16 08:10 yo-complete -> ../yo/lib/completion/index.js
╭─pgrimaud@xps ~/.config/yarn/global/node_modules/.bin  
╰─$ rm jhipster 
╭─pgrimaud@xps ~/.config/yarn/global/node_modules/.bin  
╰─$ ln -s /home/pgrimaud/projects/jhipster/generator-jhipster/cli/jhipster.js jhipster
╭─pgrimaud@xps ~/.config/yarn/global/node_modules/.bin  
╰─$ ls -al
total 28
drwxr-xr-x   2 pgrimaud pgrimaud  4096 mai   16 08:26 .
drwxr-xr-x 558 pgrimaud pgrimaud 20480 mai   16 08:10 ..
lrwxrwxrwx   1 pgrimaud pgrimaud    18 mai   16 08:10 bower -> ../bower/bin/bower
lrwxrwxrwx   1 pgrimaud pgrimaud    23 mai   16 08:10 gulp -> ../gulp-cli/bin/gulp.js
lrwxrwxrwx   1 pgrimaud pgrimaud    22 mai   16 08:10 istanbul -> ../istanbul/lib/cli.js
lrwxrwxrwx   1 pgrimaud pgrimaud    67 mai   16 08:26 jhipster -> /home/pgrimaud/projects/jhipster/generator-jhipster/cli/jhipster.js
lrwxrwxrwx   1 pgrimaud pgrimaud    16 mai   16 08:10 yo -> ../yo/lib/cli.js
lrwxrwxrwx   1 pgrimaud pgrimaud    29 mai   16 08:10 yo-complete -> ../yo/lib/completion/index.js
╭─pgrimaud@xps ~/.config/yarn/global/node_modules/.bin  
╰─$ 
```

Now my `jhipster` command uses my correct `generator-jhipster` from master

**Comment by deepu105** [comment]
I think thats normal if you are using master. I have configured npm/yarn to
install to my home so that I dong have to do sudo. But once we release this
it should work the same way as any other node executable like yo, npm etc

**Comment by pascalgrimaud** [comment]
Yes it's normal.
I wanted to put here all information so other people can test it ! :-)

**Comment by gmarziou** [comment]
Is it supposed to work on Windows? I can test it tonight if you want but I'm not sure how to test.

**Comment by deepu105** [comment]
Yes it should work on windows as well. Except for autocompletion ofcourse

**Comment by deepu105** [comment]
Just follow the same instructions. Since its run by node it handles the
cross platform compatibility

**Comment by jdubois** [comment]
- it's working with Yarn for me, it's awesome!!
- autocompletion is great, but we must check what is being completed: there are lots of completions that are not clear at all, like "ijdl" "e" or "os"... Now that we have autocompletion, we could write the complete command name, like "import-jdl", "entity" and "openshift".

**Comment by ruddell** [comment]
Everything works great.  Is there a way to limit the autocompletion to one phrase? 

For example, pressing tab after `jhipster` should list all commands.  On the other hand, pressing tab after `jhipster import-jdl`, I want to see the files in the folder instead of more JHipster commands.

**Comment by deepu105** [comment]
@jdubois Those are the short alias for commands. Check the `commands.js` for details. Feel free to change them if you want but they are useful IMO. we can do `jhipster e test` instaed of `jhipster entity test` for example. Or we could have alias only for long commands like docker-compose etc. Removing alias is easy just remove the alias line form the object
```
    cloudfoundry: {
        alias: 'cf',
        desc: 'Generates a `deploy/cloudfoundry` folder with a specific manifest.yml to deploy to Cloud Foundry'
    },
```

Yes this is the first iteration and ofcourse we can improve the autocompletion a lot. look at `completion.js`. We ca even configure autocomplete per command to do awesome stuff

**Comment by deepu105** [comment]
@ruddell we can fine tune it to work specifically for each command check this https://github.com/mklabs/node-tabtab#documentation
we can do it after the first release

**Comment by jdubois** [comment]
For the autocompletion:

- Using "full names" like "entity" makes the commands easily understandable
for everyone. They are longer, but that's the whole point of autocompletion.
- Using "short names" like "e" misses the whole point of autocompletion
- Using both just adds confusion

So I just want to have the full names. I hope that's OK with everyone ?

Le 16 mai 2017 10:16 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
Yes its fine in that case I'll remove short names from autocompletion


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Its done :)


Thanks & Regards,
Deepu
