### ISSUE TITLE
Field loadbalancerestTemplate in  required a bean of type 'org.springframework.web.client.RestOperations' that could not be found.

### ISSUE THREAD

**Issue by bhagujava** [jhipster/generator-jhipster#5748]
I have just created new microservice and trying to call another microservice. I got the below but not sure its configuration issue ? 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field loadbalancerestTemplate in com.demo.service.ServiceClass required a bean of type 'org.springframework.web.client.RestOperations' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.web.client.RestOperations' in your configuration.

I am using  v4.4.1.

**Comment by pascalgrimaud** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
