### ISSUE TITLE
CacheConfiguration hazelcast cluster

### ISSUE THREAD

**Issue by trendsoa** [jhipster/generator-jhipster#5749]
from the code, hazelcast will setup cluster by search the instance from eureka when use prod profile, but first time there is no any instance in eureka,  then we bring up 5 instance at same time(maybe by docker orchestration), seems it can not setup a hazelcast cluster. is my understanding correct?

##### **JHipster Version(s)**

latest version

**Comment by jdubois** [comment]
Yes, if they all come up at the same time and you don't have luck.
The initial idea is that you start one instance and then scale up, but you
just need one starting after the others, basically.
So yes you understand correctly.
