### ISSUE TITLE
Jhipster is not generating application with angular 2

### ISSUE THREAD

**Issue by ryanfrnnds** [jhipster/generator-jhipster#5753]
![image](https://cloud.githubusercontent.com/assets/7664019/26016438/5fd2237c-373b-11e7-9dda-ead3ec7e16dc.png)

I'm starting jhipster and creating my first project. But I would like to create a project with angular 2 and verified in your stack that it would be possible. However, following the steps https://jhipster.github.io/installation/ is not possible with the ANGULAR 2. What could be happening?

**Comment by pascalgrimaud** [comment]
Look at https://angular.io/
> Angular v4.0 is out! Smaller, faster, no biggie...

We try to support the last version of Angular, which is Angular4, not Angular2 anymore.
So, you need to select **Angular 4**.
