### ISSUE TITLE
yo jhipster:heroku  { Error: stdout maxBuffer exceeded 

### ISSUE THREAD

**Issue by kalyandas** [jhipster/generator-jhipster#5757]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) with the JHipster tag.
- For bug reports its mandatory to paste the result of command `jhipster info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**

I am running yo jhipster:heroku
and it gives me this error
 { Error: stdout maxBuffer exceeded    at Socket.<anonymous> (child_process.js:264:14)     at emitOne (events.js:101:20)     at Socket.emit (events.js:188:7)     at readableAddChunk (_stream_readable.js:176:18)     at Socket.Readable.push (_stream_readable.js:134:10)     at Pipe.onread (net.js:551:20) cmd: './mvnw package -DskipTests=true -B -Pprod' }

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
