### ISSUE TITLE
multiple HazelcastInstance instances on gateway

### ISSUE THREAD

**Issue by trendsoa** [jhipster/generator-jhipster#5759]
##### **Overview of the issue**
when enable rate limit in gateway application, it seems create two HazelcastInstance instances, one is come from CacheConfiguration, another is come from RateLimitingFilter(hazelcast-default.xml ), and hazelcast for rate limit is node cluster mode. do we have a way to only have one hazelcast cluster in gateway?

##### **Motivation for or Use Case**

only need one hazelcast cluster for gateway with rate limit enabled.

##### **JHipster Version(s)**

latest version.

**Comment by jdubois** [comment]
The goal is that you have only one instance, but we 2 different caches in them -> are you sure you have 2 instances?

- I'm closing this as you need to post your configuration, as per our guidelines (that makes it impossible to reproduce for me)
- As Hazelcast uses a port to replicate, if you have 2 instances, you should get a port conflict, have a look at this

-> please post an update if you have more info, this is new and tricky in our code base, so help is welcome

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
