### ISSUE TITLE
Supporting ROLE BASED  view with  Angular JS 2 in Jhipster?

### ISSUE THREAD

**Issue by muralihr** [jhipster/generator-jhipster#5761]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) with the JHipster tag.
- For bug reports its mandatory to paste the result of command `jhipster info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**

I created a app that has two new ROLES - MANAGER/STK_MANAGER;
When i login with any one of the above users - i also happen to see the Create Entity Menu with permission to edit the entity DB.

Urgently i need this to be implemented ~ Any idea how to resolve this till we get a feature upgrade;

Feature request
##### **Motivation for or Use Case**

When a entity is created a minimum security has to be mentioned so that the views are only assigned to specified ROLES and not to all ROLES.

##### **Reproduce the error**

Log in a s new role and have a look at the menu.

##### **Suggest a Fix**

No idea;

##### **JHipster Version(s)**

JHipster release 4.0.5

##### **JHipster configuration**

Welcome to the JHipster Generator v4.0.5
Documentation for creating an application: https://jhipster.github.io/creating-a
n-app/
Application files will be generated in folder: E:\nammanimmacycle\nncfsw\gitproj
\serverapp\sw
 ______________________________________________________________________________

  JHipster update available: 4.4.1 (current: 4.0.5)
  Run npm install -g generator-jhipster to update.
 ______________________________________________________________________________

This is an existing project, using the configuration from your .yo-rc.json file

to re-generate the project...

Installing languages: hi, en, ta

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

NA
##### **Browsers and Operating System**

WIndows
CHROME/FIREFOX;
- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
You don't provide any evidence that there is an issue with JHipster code, please show some code.
By default, Spring Security role names must be prefixed by "ROLE_", do your roles resepct this or did you change spring security configuration?

**Comment by muralihr** [comment]
Sorry ! Apologies 
By default, Spring Security role names must be prefixed by "ROLE_", do your roles respect this or did you change spring security configuration?
I have followed the Spring Security convention ~ROLE_ pls see below !
My configuration is as mentioned below 
************
authorities.csv
ROLE_ADMIN
ROLE_USER
ROLE_NODE_MANAGER
ROLE_STOCK_MANAGER
************
user_authorities.csv

4;ROLE_USER
5;ROLE_NODE_MANAGER
6;ROLE_STOCK_MANAGER
************
users.csv
5;nodemanager;$2a*********** ;User;User;nodemanager@localhost;;true;hi;system;system
6;stockmanager;$2a*********** ;User;User;stockmanager@localhost;;true;hi;system;system
************
I changed the entity file to reflect that (ROLE_ADMIN) AUTHORITIES alone can change the file ~ but still it is allowing ROLE_STOCK_MANAGER to create the entity;

Sample of the file ~
entities/type-of-id-card/'type-of-id-card.route.ts 

export const typeOfIDCardRoute: Routes = [
  {
    path: 'type-of-id-card',
    component: TypeOfIDCardComponent,
    resolve: {
      'pagingParams': TypeOfIDCardResolvePagingParams
    },
    data: {
        authorities: ['ROLE_ADMIN'],
        pageTitle: 'eazybikeApp.typeOfIDCard.home.title'
    }
  }, {
    path: 'type-of-id-card/:id',
    component: TypeOfIDCardDetailComponent,
    data: {
        authorities: ['ROLE_ADMIN'], 
        pageTitle: 'eazybikeApp.typeOfIDCard.home.title'
    }
  }
];

Hope this helps ~
murali

**Comment by gmarziou** [comment]
You're using a rather old version of Jhipster, please upgrade to latest as there has been lot of work done on this topic since.

**Comment by jdubois** [comment]
Yes our roles start with ROLE_, one of our policies is to follow the standard configuration of third party libs, and we do it here.
I'm sorry but I don't see the issue here.

**Comment by gmarziou** [comment]
I have tested it with JHipster 4.4.1 and it works for me. I just authorized ROLE_ADMIN to access one entity routes and when I'm logged with ROLE_USER I get an access denied error when accessing this entity.

So I'm closing this issue until you clearly show there is a problem with 4.4.1

**Comment by muralihr** [comment]
Hey Thanks ~ It is working fine ~ I am using 4.9;
