### ISSUE TITLE
doc security section outh2 secret key proprerty name

### ISSUE THREAD

**Issue by Xnave2** [jhipster/generator-jhipster#5763]
https://jhipster.github.io/security/  - at the end of this doc it says:
"This solution uses a secret key, which should be configured in your application.yml file, as the “authentication.oauth.secret” property."
the property is actually found at: security.authentication.client-secret.

By the way, what should I do if I want to change the key?

**Comment by jdubois** [comment]
I'm updating the documentation, thanks (have a look at the commit below)
