### ISSUE TITLE
How to use elasticsearch from jhipster-console

### ISSUE THREAD

**Issue by Oleg25** [jhipster/generator-jhipster#5774]
When i try to start application which look on docker image with elasticsearch from jhipster-console.yml i've got error:

ERROR main o.s.d.e.r.s.AbstractElasticsearchRepository:80 - failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9300}]

But when i do same with docker image (in docker folder of my project - elasticsearch.yml) - it starts successfully

FYI:
I think it because Kibana use more newest version of elasticserch -5 . But jhipster-generator use elasticsearch version 2

**Comment by jdubois** [comment]
Looks like you didn't start up Elasticsearch, according to the error.
Anyway, this isn't a bug, as it's working with Docker, it's a configuration issue.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by ruddell** [comment]
@Oleg25 Your thinking is correct - JHipster apps use [spring-data-elasticsearch](https://github.com/spring-projects/spring-data-elasticsearch) which only works with v2 of Elasticsearch.  That's why using JHipster Console's version of Elasticsearch (v5) doesn't work
