### ISSUE TITLE
Adding new Authority shows access_denied

### ISSUE THREAD

**Issue by arushijain45** [jhipster/generator-jhipster#5791]
I wanted to add a new role in JHI_AUTHORITY so I have inserted a new record in JHI_AUTHORITY document in mongo {"_id" : "ROLE_MANAGER"}

Now I want that only user with either ROLE_ADMIN or ROLE_MANAGER is authorized for one of the api.
So I have added following LOC in my api:
@Secured({"ROLE_ADMIN", "ROLE_MANAGER"})

But when I tried to access the api with user having role: ROLE_ADMIN it works great but with user having role: ROLE_MANAGER, it shows me error:

> {
>   "error": "access_denied",
>   "error_description": "Access is denied"
> }

Please let me know if there is any step that is missing?

**Comment by jdubois** [comment]
Can you ask this on Stackoverflow using our "jhispter" tag?

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
