### ISSUE TITLE
Getting Typecast errors in settings.component.spec.ts file after upgrading to Angular 4

### ISSUE THREAD

**Issue by MorlaRamakrishna** [jhipster/generator-jhipster#5792]
I have upgraded my gateway application via following [https://progblog.io/How-to-upgrade-to-Angular-4/]()

After that, I have reinstalled node modules via npm install

The application is running but getting below errors:

**Error:1**
 [at-loader] ./src/test/javascript/spec/app/account/settings/settings.component.spec.ts:48:13 
    TS2322: Type 'AccountService' is not assignable to type 'MockAccountService'.
  Property 'getSpy' is missing in type 'AccountService'.

**Error:2**
 [at-loader] ./src/test/javascript/spec/app/account/settings/settings.component.spec.ts:49:13 
    TS2322: Type 'Principal' is not assignable to type 'MockPrincipal'.
  Property 'identitySpy' is missing in type 'Principal'.

**Comment by jdubois** [comment]
I'm sorry but I have no idea what this blog is, the issue doesn't come from us -> could you ask this on Stackoverflow using our "jhipster" tag?

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
