### ISSUE TITLE
Feature Request: Friendly names or labels for entities and attributes

### ISSUE THREAD

**Issue by allquixotic** [jhipster/generator-jhipster#5794]
##### **Overview of the issue**

Sometimes, the name we want to display on the front-end differs from the name that the field should have in the backend. JDL should support the ability to supply a friendly name for an entity or a field, and use the friendly name for all user-visible content (HTML, etc.) and use the logical name (what we currently have) for all coding purposes.

##### **Motivation for and Use Case**

 - Certain words are impossible to use directly as the variable or entity names, such as `Character` (a Role Playing Game has entities called "characters" that are playable actors/people in the game.) Instead, some other name has to be given in the entity JDL; currently this logical name is interpreted to create the UI, which ends up in the UI having the wrong names and having to be manually edited.
 - When you get bitten by this, then, each time the model is regenerated (say, to make a schema change), you have to manually hit "y" / "n" during the overwrite prompt for `jdl-import`, or else allow it to overwrite and then *re-make* the changes.
 - Sometimes, you want to have a longer description for a field on the page, but you're content with a very short, memorable, easy to type logical identifer. For instance, you might want to label a field logically as `chr` (as someone familiar with the app, it's not hard to guess what that means), but you want the user to see a page letting them edit `Characters`, not `Chrs`.

##### **Suggest a Fix**

Here is example, hypothetical JDL for what I'd like to do:

```
entity Chr as "Character" {
  str String required as "Name"
}

entity B { }

relationship OneToOne {
  Chr{b} to B{chr(str) as "Character Name"}
}
```

In code, the DTOs, services, domain model, etc. would include the logical names just like JDL currently does. In anything the user can normally see in the front-end (client code), the string in quotes after `as` would be used instead, without any casing interpolation or auto space insertion (just take the value literally, so `abcdEfgh` would not render as `Abcd Efgh`, but as `abcdEfgh`.)

##### **JHipster Version(s)**

Latest stable 4.x

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
We spoke in the Gitter chat.  While you can't use Java/Angular reserved words in entities (like `char`), you can use reserved database words in tables like `Character` by customizing the table name:
```
entity Character (jhi_character) {
  name String
}
```
I don't think there's enough added-value for the extra entity fields and work this would take to maintain.  I recommend that you create a separate UI for users to interact with (copying code is fine).

Slightly off topic, but one way we could improve the JDL experience is to allow importing a single entity from a JDL file.  Currently the developer is forced to go through each entity's conflicts every time any entity is changed via JDL

**Comment by deepu105** [comment]
Actually I think it might be useful to have a display name option atleast via JDL. In terms of maintenance this shouldn't be too much as we already use a different variable internally for display name so that we could use jhiPrefix. So it might be easy to hook this up to that actually. So I'm actually inclined to do this. What do you think @jdubois  @MathieuAA ?

@ruddell I think if a jdl has changes only in one entity then others will not regenerate. So behaviour should be same as you expected. This was working like this I checked last. Can you check again?

**Comment by ruddell** [comment]
@deepu105 Testing with two entities, when I make UI changes for EntityOne and JDL changes for EntityTwo, importing the JDL regenerates both EntityOne and EntityTwo and prompts to overwrite the UI changes

**Comment by cbornet** [comment]
Note that entities also have a pluralized form

**Comment by MathieuAA** [comment]
Good idea. If it gets supported by the generator one day, I don't see why not.
The only change I'd make to the proposed form of this feature is:

```
entity Chr as "Character" {
  someName String required as Name // without quotes
}
```

**Comment by allquixotic** [comment]
So a few wrinkles so far:

 - For *entity* display names, it's redundant with the table name override
 - Omit quotes for the names or not? Are quotes needed to help escape special characters, etc? 
 - Plurality

**Comment by jdubois** [comment]
I would also like to add the "business type" of data, so we can use https://github.com/marak/Faker.js/ to generate fake data.
My main issue is that if we add too many of those, it's going to be very complex to maintain

**Comment by jdubois** [comment]
Seems like a lot of work, and nobody has started anything on this during the last month, I'm closing this for lack of interest.
