### ISSUE TITLE
Feature: codecov support

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#5799]
As suggested on Twitter [here](https://twitter.com/pascalgrimaud/status/864776871589949441), I want to propose the support for [codecov.io](https://codecov.io)  in our CICD subgenerator
- the result is similar to Sonar: look in one of my personnal project: https://codecov.io/gh/pascalgrimaud/qualitoast
- easy to support (very few lines to add: https://github.com/pascalgrimaud/qualitoast/commit/f7d73bf02fd5f3e1235220319e2d05f8cedbef14)
- it is free for personnal account (not for organization): https://codecov.io/pricing

What do you think? Do you agree?
If not, it can be easily done in a module.

Ping @atomfrede ;-)

**Comment by atomfrede** [comment]
+1 from me. It also works well with gitlab ci, so maybe another question (like the heroku thing), ` do you wan to use codecov.io for coverage reporting?`. The best thing about codecov are the pull request comments.

**Comment by pascalgrimaud** [comment]
@atomfrede : oh about cobertura, I just follow a wrong doc https://github.com/codecov/example-java-maven instead of https://github.com/codecov/example-java

**Comment by jdubois** [comment]
Would that be a competitor to SonarQube? In that case we should also propose the Sonar option, they've been very nice to us.
It could also be a module, I'm afraid we're going so much options here...

**Comment by pascalgrimaud** [comment]
We already support Sonar Analyzis in CICD sub gen.
It would be an additional support here.

No worry, I will do a module for now, we'll see later if it's popular, to
integrate it here.

So let's close this.

**Comment by jdubois** [comment]
Oh, I didn't know about Sonar, sorry!

**Comment by atomfrede** [comment]
Cool. But from my point of view sonar is much more powerful than codecov so no competition there. Let's do the module first!
