### ISSUE TITLE
DTO and lazily initialize

### ISSUE THREAD

**Issue by Patresss** [jhipster/generator-jhipster#5802]
##### **Overview of the issue**

When I generate application with DTO and relation ManyToMany I have the error with lazily initialize:
`org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.patres.timetable.domain.Division.parents, could not initialize proxy - no Session`

##### **Motivation for or Use Case**

Using DTO with relation many to many

##### **Reproduce the error**

1. In JDL I create entities: Teacher, Division with 2 relations many to many:

- Division{parent(name)} to Division
- Division{preferredTeacher(surname)} to Teacher{preferredDivision}

2. After generate in my web application I tried creating Division, but I got error:
`org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.patres.timetable.domain.Division.parents, could not initialize proxy - no Session`
3 . When I removed relation Division{parent(name)} to Division I have similar error with relation:
 Division{preferredTeacher(surname)} to Teacher{preferredDivision}

`org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.patres.timetable.domain.Division.preferredTeachers, could not initialize proxy - no Session`

##### **Related issues**

N/A

##### **Suggest a Fix**

Add: @MayToMany(fetch = FetchType.EAGER) but I don't think it's the best solution

##### **JHipster Version(s)**

4.5.1

##### **JHipster configuration**

.yo-rc.json:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.patres.timetable",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.1",
    "baseName": "Timetable",
    "packageName": "com.patres.timetable",
    "packageFolder": "com/patres/timetable",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "a20c1e6a743eeed01623cb3c2abea26a593140ff",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "pl"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

JDL:
```
enum DivisionType {
    SCHOOL,
    CLASS,
    SUBGROUP
}

entity Division {
    name String required,
    shortName String,
    numberOfPeople Long,
    divisionType DivisionType required,
    colorBackground String,
    colorText String,
}

relationship ManyToMany {
    Division{parent(name)} to Division
}


entity Teacher {
name String required,
surname String required,
degree String,
shortName String
}

relationship ManyToMany {
Division{preferredTeacher(surname)} to Teacher{preferredDivision}
}

paginate Teacher, Division with pagination

dto * with mapstruct

```

##### **Browsers and Operating System**

Windows 10. Google Chrome.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Duplicate from #5629

**Comment by jdubois** [comment]
Sorry, I haven't had much time for this... Shouldn't be hard to solve
