### ISSUE TITLE
DB2 support SQL dialects

### ISSUE THREAD

**Issue by eucariop** [jhipster/generator-jhipster#5804]
It can support those SQL Dialects, but how?

**Comment by deepu105** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

Open a new issue with proper details or update this issue with all details and request to re open.
Issues opened without proper details will be closed without explanation.
