### ISSUE TITLE
UnsatisfiedDependencyException on UserResourceIntTest when running inside Intellij IDEA

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5808]
This was introduced by https://github.com/jhipster/generator-jhipster/commit/9382350efc44e70c036373e2a8bff258047d44e4 from @cbornet 

There is no issue when running the tests with Maven, but with Intellij IDEA we have errors when running `UserResourceIntTest`:

    org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.xxx.web.rest.UserResourceIntTest': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.xxx.service.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)

The problem is that the test runner from Intellij IDEA doesn't seem to understand that the `UserMapper` is handled by MapStruct. This also fails when the "post processor" option in Intellij IDEA is checked.

This is annoying as you can't run the tests in Intellij IDEA anymore.

**Comment by tezcane** [comment]
I see this too. If I run the maven test it generates the mapped files, then I can run the idea tests without errors after that (temp workaround)

**Comment by jdubois** [comment]
Of course this works if you use the "IDE" profile, see the last section of https://jhipster.github.io/configuring-ide-idea/

But that's not really easy-to-use for people starting with JHipster.

**Comment by jdubois** [comment]
An easy solution would be to replace the use of MapStruct for the UserMapper, by writing the code directly.
It's less elegant, but it would solve the issue, and remove the need for MapStruct in a "normal" project, which I find good.

**Comment by tezcane** [comment]
drop into User.java?

```
public static final User.Builder toBuilder(User user) {
        User.Builder builder = new User.Builder();
        return builder.id           (user.id           )
                      .authorities  (user.authorities  )
                      .activated    (user.activated    )
                      .resetDate    (user.resetDate    )
                      .activationKey(user.activationKey)
                      .resetKey     (user.resetKey     )
                      .langKey      (user.langKey      )
                      .password     (user.password     )
                      .firstName    (user.firstName    )
                      .lastName     (user.lastName     )
                      .login        (user.login        )
                      .email        (user.email        );
    }
    private User(Builder builder) {
        setId           (builder.id           );
        setAuthorities  (builder.authorities  );
        setActivated    (builder.activated    );
        setResetDate    (builder.resetDate    );
        setActivationKey(builder.activationKey);
        setResetKey     (builder.resetKey     );
        setLangKey      (builder.langKey      );
        setPassword     (builder.password     );
        setFirstName    (builder.firstName    );
        setLastName     (builder.lastName     );
        setLogin        (builder.login        );
        setEmail        (builder.email        );
    }
    private static final class Builder {
        private Long           id;
        private Set<Authority> authorities;
        private Boolean        activated;
        private ZonedDateTime  resetDate;
        private String         activationKey;
        private String         resetKey;
        private String         langKey;
        private String         password;
        private String         firstName;
        private String         lastName;
        private String         login;
        private String         email;
        public Builder() {}
        public User build() { return new User(this); }
        public Builder id           (Long           v) { if(v != null) id            = v; return this; }
        public Builder authorities  (Set<Authority> v) { if(v != null) authorities   = v; return this; }
        public Builder activated    (Boolean        v) { if(v != null) activated     = v; return this; }
        public Builder resetDate    (ZonedDateTime  v) { if(v != null) resetDate     = v; return this; }
        public Builder activationKey(String         v) { if(v != null) activationKey = v; return this; }
        public Builder resetKey     (String         v) { if(v != null) resetKey      = v; return this; }
        public Builder langKey      (String         v) { if(v != null) langKey       = v; return this; }
        public Builder password     (String         v) { if(v != null) password      = v; return this; }
        public Builder firstName    (String         v) { if(v != null) firstName     = v; return this; }
        public Builder lastName     (String         v) { if(v != null) lastName      = v; return this; }
        public Builder login        (String         v) { if(v != null) login         = v; return this; }
        public Builder email        (String         v) { if(v != null) email         = v; return this; }
```

**Comment by jdubois** [comment]
@cbornet this might lower our code coverage :-)

**Comment by cbornet** [comment]
@jdubois if that's the case it should be easy to cover. I didn't know the tests were supposed to pass on IDEA without the IDE profile. I always activate it. Are you sure tests for an entity with a required relationship on User do ?

**Comment by jdubois** [comment]
@cbornet I tested the relationships to the User entity, but that's some rather tricky code, I'm not guaranteeing this is perfect

**Comment by tezcane** [comment]
I saw the IDE profile but had not clue what it does... I tried enabling it on failed unit tests in the past but it did not fix them (other issues at the time).  Documentation...

**Comment by jdubois** [comment]
Yes it's documented, and now fixed

**Comment by tezcane** [comment]
Are you talking about this doc?:
https://jhipster.github.io/profiles/

It does not provide much details or mention most of the current profiles, including IDE...

**Comment by jdubois** [comment]
No: https://jhipster.github.io/configuring-ide-idea/

Anyway that's fixed in the next release - I won't have time to do it before next week, anyway

**Comment by cremich** [comment]
@jdubois i stumbled about the current implementation of the `UserMapper.java` and wondered, why this is a hard-coded Mapper and not a MapStruct mapper. After a little research i found this issue and tried experimenting with my current IntelliJ version (2018.3.4 Build 183.5429.30). Sorry if this is not the right place. If you like i can open another issue. But before that i thought it would be better to discuss here first.

So i refactored the hard-coded UserMapper to a MapStruct mapper in a sample application. If i run the junit tests directly via IntelliJ (without maven), the tests do not produce the "UnsatisfiedDependencyException". I assume that something must have changed in IntelliJ?

Do you see a chance to re-write the UserMapper back to a MapStruct mapper? 
In this context i was wondering, why the hard-coded UserMapper ist not used in the UserService for example. Actually my IntelliJ complains about some code-douplications every time a user is created from a user-dto vice versa. Maybe this can be refactored independently.

By the way: after the "UserMapper refactoring" some tests in the `UserResourceIntTest.java` fail. This ist because the hard-coded version does not map all fields like "createdBy", but the Mapstruct Mapper does. In fact this could be a little improvement? What do you think about my thoughts?

**Comment by cremich** [comment]
I think it works, because the `mapstruct-processor` plugin is part of the `maven-compiler-plugin` configuration:
```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                        <!-- For JPA static metamodel generation -->
                        <path>
                            <groupId>org.hibernate</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>${hibernate.version}</version>
                        </path>

                    </annotationProcessorPaths>
                </configuration>
            </plugin>
```

So i think the dependency in the `IDE` profile can be removed.
