### ISSUE TITLE
CSRF Protection for Everybody

### ISSUE THREAD

**Issue by Metavirulent** [jhipster/generator-jhipster#5814]
* **Overview of the request**

The JHipster security page mentions in the section **CSRF Protection** that Angular and Spring Security both have CRSF protection but they don't work together and they have been reconfigured to correctly work together. This seems outdated, as they work together nicely. However, even worse, taking a closer look, it's not possible to find out how JHipster tries to accomplish said CSRF protection.

Neither the generated code nor a black-box examination show any signs of CSRF protection for the majority of security models (version 4.5.1). Only with stateful Spring sessions, CSRF protection is enabled. The rest of the security models (e.g. JWT, UAA microservices, ...) seem to be left out.

* **Motivation for or Use Case** 

CSRF protection is highly recommended but in contrast to what the documentation suggests, it doesn't seem to be in place with the exception of the stateful Http Session authentication. I don't see the reason why the other security options shouldn't be protected, too.

* **Browsers and Operating System** 

n/a

* **Related issues** 

#4272 suggested a fix
#4368 tried to switch to Spring's CSRF handling but only did it for one security model

* **Suggest a Fix** 

Use Spring's cookie-based CSRF protection for other security models, too.

In other terms, in SecurityConfiguration.java/MicroserviceSecurityConfiguration.java, replace
`            .csrf()`
`            .disable()`
by
`            .csrf()`
`            .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())`
`        .and()`

**Comment by ruddell** [comment]
I'll start this out with saying I'm not the most familiar with the security aspects.

I thought the reason CSRF is only present for Session auth is that it is the only auth type that uses cookies.  Doesn't CSRF depend on the use of cookies? Another site can make a request to your JHipster app's API, but without the JWT token (stored in local storage thus inaccessible) it shouldn't matter?

Thanks for taking the time to review our config and offer improvements.

**Comment by jdubois** [comment]
Indeed, it's only done for stateful authentication, as it's the only mechanism where CSRF attacks should be possible.

@Metavirulent did you find a way to do a CSRF attack with our JWT authentication mechanism? We shouldn't use cookies at all, but who knows...

And indeed, you're probably the first one to tell us of doing such a review, and I spent a lot of time on this, so it's good not to be alone :-)

**Comment by Metavirulent** [comment]
I was probably getting ahead of myself, since I just submitted PR #5812 today, CSRF will be a requirement once that one will be merged in. I probably should have included it in that request anyway. I'll update the PR.

**Comment by jdubois** [comment]
Thanks @Metavirulent -> then I'm closing this, and I'll answer you on the PR, as it seems to have everything included

**Comment by nickshoe** [comment]
CSRF protection may be sensible in case of login forms: https://support.detectify.com/support/solutions/articles/48001048951-login-csrf.

Example:
- myapp.com has a frontend app serving a login page, which sends login requests to the backend (eg: api.myapp.com)

- evil.com has a frontend app serving an exact copy of the original login page, but it performs a login request to the original backend (api.myapp.com) with the attacker's credentials

- upon login (withe the attacker credentials), evil.com redirects the user to the real app and the user starts using the app thinking it is now logged with his own account, potentially disclosing sensitive data (that will be stored into the attacker's account)

In general, if the login API endpoint isn't protected against CSRF it could accept login requests from a different frontend; this may not be desirable in general. On the other hand, for cross-site authentication/authorization there are protocols such as OpenID Connect and OAuth2.
