### ISSUE TITLE
Registration of a new user fails

### ISSUE THREAD

**Issue by yfain** [jhipster/generator-jhipster#5816]
I just generated a new app (Angular 4) using JHipster 4.5.1 and started the app with ./mvnw. Opened localhost:8080 and selected the menu Account | Register. Filled out the form and got the message that the registration email was sent, but I never received any emails. Opened the Chrome browser console and it shows errors (see attached).
<img width="1258" alt="jh" src="https://cloud.githubusercontent.com/assets/2254842/26338762/658803b0-3f8b-11e7-837e-3844c23264f6.png">

**Comment by jdubois** [comment]
If you're in dev mode and didn't configure a mail server, the message will be available in the console.

**Comment by yfain** [comment]
Thank you for your response, but I've configured the mail server in application-dev.yml as follows (I enterd my email and pwd):

mail:
        host: smtp.gmail.com
        port: 587
        username: gmailuserid@gmail.com  #Replace this field with your Gmail username.
        password: ************           #Replace this field with your Gmail password.
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com

But the error rmains the same.
