### ISSUE TITLE
Generation hung on Windows due to notification

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#5820]
##### **Overview of the issue**

Seen on Windows 7: when generating a new app with `yo run jhipster` the generation never ends it seems to hang on html-webpack-plugin, in fact there a notification icon (yellow bubble) opened in the system icon tray. When you click on the icon, the generation finsishes.

This does happen with Angular 4 but not with Angular 1, so maybe related to webpack.

I'll try to fix it but at least I wanted to document the workaround for other users.

##### **JHipster Version(s)**

4.5.1

##### **JHipster configuration**

Not related to a particular config, I reproduced it with a gateway and a monolith, not with a service and only with Angular 4.

##### **Browsers and Operating System**

Windows 7.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Just tested on Windows 10 and could not reproduce.

**Comment by deepu105** [comment]
Its probably something to do with the windows 7 notification system. If you cant fix it I suggest we either document it or ignore it as windows 7 isn't main stream any more (only used in corporates mostly)

**Comment by tezcane** [comment]
You can just detect Windows 7 and avoid the command that hangs...

**Comment by gmarziou** [comment]
Yes, I know, unfortunately my colleagues are in this case and I have to convice our sys admin to either move them to Linux like myself or to Windows 10 ;)

Do you know which part could be responsible for this notification? Would it be in the generator itself or in the webpack part?

**Comment by gmarziou** [comment]
Good idea @tezcane

**Comment by jdubois** [comment]
There are 2 notifications (I coded both), but they use underneath the same lib (so probably it works the same for both).

- look for `WebpackNotifierPlugin` in webpack-common.js
- look for `notifyReporter` in karma.conf.js

**Comment by gmarziou** [comment]
Thanks, I have looked at the versions in yarn.lock and it seems that the related transitive deps are recent except for node-notifier, I'll try tomorrow.

**Comment by gmarziou** [comment]
I'm closing it for now as I don't have time to debug it at work.
