### ISSUE TITLE
Default lang config in angular2 app ?

### ISSUE THREAD

**Issue by muralihr** [jhipster/generator-jhipster#5836]
##### **Overview of the issue**
When i generated the Jhipster app i had not given attention to default language 
With my friend suggesting that ENG be the default language - i wanted to change the language 
After doing for a serach i found the solution lies in modifying the nativeLanguage 
 "enableTranslation": true,
    "nativeLanguage": "hi",
    "languages": [
      "hi",
      "en",
      "ta"
    ]

I changed it to ~
    "nativeLanguage": "en",
    "languages": [
      "hi",
      "en",
      "ta"
    ]

##### **Motivation for or Use Case**
Enabling reconfiguration of default language

##### **Reproduce the error**
chanage the lang setting in  .yo-rc.json  variable  "nativeLanguage": "fr" to     "nativeLanguage": "en",
The default language should be change in the NAVIGATION MENU.

##### **Related issues**

https://github.com/jhipster/jhipster-devbox/issues/39
https://github.com/jhipster/generator-jhipster/issues/1447
##### **Suggest a Fix**
system should automatically take what is configured in json.
I did a yarn clean and then it gave lot of errors - i had to clean mvn and node_modules to restart all things over again.

##### **JHipster Version(s)**
    "jhipsterVersion": "4.0.5",

##### **JHipster configuration**

  "generator-jhipster": {
    "jhipsterVersion": "4.0.5",
    "baseName": "eazybike",
    "packageName": "org.nncf.eazybike",
    "packageFolder": "org/nncf/eazybike",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "3eaa51a5b94f67dd6a4f227c1e3de352d2093e9f",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "hi",
      "en",
      "ta"
    ]
  }
}

##### **Browsers and Operating System**
chrome/firefox

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by muralihr** [comment]
Do i need to do anything else to change the Default language in .json ?

**Comment by pascalgrimaud** [comment]
In you decide to change de default language:
- change the `nativeLanguage` value in your `.yo-rc.json` from `hi` -> `en`
- regenerate your application
- as you use MySQL database, your existing users were created with your previous default language (`hi`). See [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/liquibase/users.csv#L2-L5)
- so you have to update your existing users if you want this change
- the new users should be created with your new default language (`en`)

It is a normal behavior, there is no issue here, so I'm closing this.

**Comment by jdubois** [comment]
Please don't pollute the ticket system, and use Stackoverflow instead

**Comment by muralihr** [comment]
UserService.java (1 hit) HERE WE HAVE THIS setting
	Line 125:             user.setLangKey("hi"); // default language
   user.setLangKey("en"); // default language

I changed this end still it is only showing Hindi...

if (userDTO.getLangKey() == null) {
            user.setLangKey("en"); // default language
        } else {
            user.setLangKey(userDTO.getLangKey());
        }

How is this getting the input for the default language ?

regenerate your application
>> I am scared of regenerating as it is asking to overwrite many files like pom.xml and others....

**Comment by pascalgrimaud** [comment]
Sorry @muralihr but it's a channel for bug tracker not for help.
If you need help, ask it at StackOverFlow.

You can regenerate your application, type 'd' to see the diff, then, type 'n' to skip. You don't have to overwrite any file. Then, you will see all files you have to update with your new language.
