### ISSUE TITLE
[JHIPSTER] How to send Request/Information from Gateway to Microservice 

### ISSUE THREAD

**Issue by sugarissimo** [jhipster/generator-jhipster#5840]
Hi guyz,

I am using Jhipster Microservice Archi which suit better for my need.

I am trying to find a way to send request from Gateway to Microservice, Or at least send some more user information (Phone number, email ...) to microservice. Is there is any way to do that ?

What i wanted to do is basically when an user are just freshly registered, i want to send a request from the gateway to microservice in order to create for example TaxiLocation if the authority of the user is taxi, or create a shop if the user is a Shop manager ...

Thanks for your help.

**Comment by pascalgrimaud** [comment]
Sorry @sugarissimo , but it is a bug tracker, there is no issue here.
You should use the [JHipster tag on StackOverflow](http://stackoverflow.com/tags/jhipster) or join our [Gitter.im chat room](https://gitter.im/jhipster/generator-jhipster).

This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by sugarissimo** [comment]
Thanks Pascal sorry for that.. Here the request https://stackoverflow.com/questions/44202383/jhipster-how-to-send-request-information-from-gateway-to-microservice
