### ISSUE TITLE
NPE gets thrown when a null password is sent on AccountResource.registerAccount.

### ISSUE THREAD

**Issue by greenstevester** [jhipster/generator-jhipster#5848]
##### **Overview of the issue**

NPE gets thrown when a null password is sent on AccountResource.registerAccount.

##### **Motivation for or Use Case**

I am building a Nativescript client and didn't have all my client side validation in place yet and found this out by accident.

##### **Reproduce the error**

1. post a new user account to /api/register with a null password.
2. see this NPE:

```
c.o.web.rest.errors.ExceptionTranslator  : null

java.lang.NullPointerException: null
	at org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder.encode(BCryptPasswordEncoder.java:80)
	at com.observable.service.UserService.createUser(UserService.java:89)
```

##### **Suggest a Fix**

Add NotBlank annotation to password member variable of ManagedUserVM

##### **JHipster Version(s)**

v 4.5.1

##### **JHipster configuration**

N/A

##### **Entity configuration(s) 

N/A

##### **Browsers and Operating System**

N/A

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by cbornet** [comment]
@greenstevester would you do the PR ?

**Comment by greenstevester** [comment]
will do!

**Comment by pascalgrimaud** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/5857
