### ISSUE TITLE
Remove Yeoman from installation instructions?

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5854]
In our documentation, for example https://jhipster.github.io/installation/ we tell people to install Yeoman before installing JHipster:

    yarn global add yo
    yarn global add generator-jhipster

Now that we have the JHipster CLI, I don't think this is needed, so we could just do:

    yarn global add generator-jhipster

Of course that's easier. I'm not totally sure about this:

- Do you think this is a good idea? Maybe some people are happy to run "yo" also?
- Is there an issue somewhere? As my machine doesn't have a "normal" setup, I'm afraid it would fail for end-users (like we had when we released the CLI the first time)

**Comment by gmarziou** [comment]
Can you run modules without yo installed?

**Comment by jdubois** [comment]
Probably not @gmarziou -> I'm closing this for the moment, then

**Comment by deepu105** [comment]
Yes people might still run yo * commands out of old habits so its better to have it. May be we can remove it from the home page quick start and still keep it on the detailed installations page with a note saying its required to run jhipster the legacy way and to run modules.

We can also create a command in our CLI to run modules directly without YO as well :) Its easy
