### ISSUE TITLE
Wrong mappings of some DTO child entities

### ISSUE THREAD

**Issue by xdelox** [jhipster/generator-jhipster#5855]
[jhipster-jdl.zip](https://github.com/jhipster/generator-jhipster/files/1037835/jhipster-jdl.zip)

##### **Overview of the issue**

Until now, the *OneToOne*, *OneToMany* and *ManyToOne*  relationships seems to be not mapped correctly in the corresponding DTOs (or just not mapped, in some cases).

In fact, the child entities are generally mapped as a Long childEntityId at the "many" side of the relationships and there is no corresponding on the "one" side, in most of cases.

The relationships described above, in my humble opinion, are necessaries because of the impossibility of regenerate an entity with all the involved children starting from the corresponding DTO.

##### **Motivation for or Use Case**

Looking at the code seems that the aspects I'm going to describe have not been yet implemented, so this should be a <u>new feature</u>.

I will describe with some examples what the current release (4.5.2) generates case by case and what I expect.

I will use the preloaded JDL file that you can find when you run JDL Studio (https://jhipster.github.io/jdl-studio/)  for the first time. For the sake of completeness I'll attach it to this issue.

**NOTE:** Below I'll omit the getters and setters, but it is implied that they must have a match.

*1) <u>OneToOne relationship</u>*

Let's consider the *Department-Location* relationship. 

The entity, from the Department side, looks like:

```java
@OneToOne
@JoinColumn(unique = true)
private Location location;
```

While the corresponding DTO contains only the identifier of the Location entity:

```java
private Long locationId;
```

What would I expect? Something like:
```java
private LocationDTO location;
```

*<u>2) OneToMany relationship</u>*

Let's consider the relationship between *Employee* and *Job*

The generated entity:

```java
@OneToMany(mappedBy = "employee")
@JsonIgnore
private Set<Job> jobs = new HashSet<>();
```

The generated DTO currently <u>doesn't contain nothing regarding this relationship</u>.

Instead, I was expecting something like:

```
private Set<JobDTO> jobs = new HashSet<>();
```

<u>*3) ManyToOne relationship*</u>

Let's consider the relationship *Employee{manager} to Employee*

The generated entity:

```java
@ManyToOne
private Employee manager;
```

The corresponding piece of code in the generated DTO:

```java
private Long managerId;
```

What I was expecting:

```java
private EmployeeDTO manager;
```

##### Reproduce the error**

N.A.

##### **Related issues**

None

##### **Suggest a Fix**

I guess that implementing all the points described above should be pretty simple, because I guess that only a couple of files have to be modified (_EntityDTO.java and _EntityMapper.java).

I do not know if the JHipster team's expectations are the same as mine but,  in any case, I am willing to contribute to the development of this feature.

##### **JHipster Version(s)**

All versions up to the current one (4.5.2)

##### **JHipster configuration**

> Executing jhipster:info
> Welcome to the JHipster Information Sub-Generator
>
> ##### **JHipster Version(s)**
>
> ```
> /home/sergio/projects/jhipster-sandbox/test-service
> └─┬ generator-jhipster@4.5.2  -> /home/sergio/projects/generator-jhipster
>   └── generator-jhipster@4.5.2  extraneous
>
> ```
>
>
> ##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
>
> ```yaml
> {
>   "generator-jhipster": {
>     "promptValues": {
>       "packageName": "com.xdelox.test"
>     },
>     "jhipsterVersion": "4.5.2",
>     "baseName": "test",
>     "packageName": "com.xdelox.test",
>     "packageFolder": "com/xdelox/test",
>     "serverPort": "8081",
>     "authenticationType": "jwt",
>     "hibernateCache": "no",
>     "clusteredHttpSession": false,
>     "websocket": false,
>     "databaseType": "sql",
>     "devDatabaseType": "postgresql",
>     "prodDatabaseType": "postgresql",
>     "searchEngine": false,
>     "messageBroker": false,
>     "serviceDiscoveryType": false,
>     "buildTool": "maven",
>     "enableSocialSignIn": false,
>     "jwtSecretKey": "OMITTED",
>     "enableTranslation": false,
>     "applicationType": "microservice",
>     "testFrameworks": [],
>     "jhiPrefix": "jhi",
>     "skipClient": true,
>     "skipUserManagement": true,
>     "clientPackageManager": "yarn"
>   }
> }
> ```
>
>
> ##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
>
> Country.json
>
> ```yaml
> {
>     "fluentMethods": true,
>     "relationships": [
>         {
>             "relationshipType": "one-to-one",
>             "relationshipName": "region",
>             "otherEntityName": "region",
>             "otherEntityField": "id",
>             "ownerSide": true,
>             "otherEntityRelationshipName": "country"
>         }
>     ],
>     "fields": [
>         {
>             "fieldName": "countryName",
>             "fieldType": "String"
>         }
>     ],
>     "changelogDate": "20170529152829",
>     "entityTableName": "country",
>     "dto": "mapstruct",
>     "pagination": "no",
>     "service": "serviceImpl",
>     "angularJSSuffix": "mySuffix"
> }
> ```
>
> Department.json
>
> ```yaml
> {
>     "fluentMethods": true,
>     "relationships": [
>         {
>             "relationshipType": "one-to-one",
>             "relationshipName": "location",
>             "otherEntityName": "location",
>             "otherEntityField": "id",
>             "ownerSide": true,
>             "otherEntityRelationshipName": "department"
>         },
>         {
>             "relationshipType": "one-to-many",
>             "javadoc": "A relationship",
>             "relationshipName": "employee",
>             "otherEntityName": "employee",
>             "otherEntityRelationshipName": "department"
>         }
>     ],
>     "fields": [
>         {
>             "fieldName": "departmentName",
>             "fieldType": "String",
>             "fieldValidateRules": [
>                 "required"
>             ]
>         }
>     ],
>     "changelogDate": "20170529152831",
>     "entityTableName": "department",
>     "dto": "mapstruct",
>     "pagination": "no",
>     "service": "serviceImpl",
>     "angularJSSuffix": "mySuffix"
> }
> ```
>
> Employee.json
>
> ```yaml
> {
>     "fluentMethods": true,
>     "relationships": [
>         {
>             "relationshipName": "department",
>             "otherEntityName": "department",
>             "relationshipType": "many-to-one",
>             "otherEntityField": "id"
>         },
>         {
>             "relationshipType": "one-to-many",
>             "relationshipName": "job",
>             "otherEntityName": "job",
>             "otherEntityRelationshipName": "employee"
>         },
>         {
>             "relationshipType": "many-to-one",
>             "relationshipName": "manager",
>             "otherEntityName": "employee",
>             "otherEntityField": "id"
>         }
>     ],
>     "fields": [
>         {
>             "fieldName": "firstName",
>             "javadoc": "The firstname attribute.",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "lastName",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "email",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "phoneNumber",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "hireDate",
>             "fieldType": "ZonedDateTime"
>         },
>         {
>             "fieldName": "salary",
>             "fieldType": "Long"
>         },
>         {
>             "fieldName": "commissionPct",
>             "fieldType": "Long"
>         }
>     ],
>     "changelogDate": "20170529152833",
>     "javadoc": "The Employee entity.",
>     "entityTableName": "employee",
>     "dto": "mapstruct",
>     "pagination": "infinite-scroll",
>     "service": "no",
>     "angularJSSuffix": "mySuffix"
> }
> ```
>
> Job.json
>
> ```yaml
> {
>     "fluentMethods": true,
>     "relationships": [
>         {
>             "relationshipName": "employee",
>             "otherEntityName": "employee",
>             "relationshipType": "many-to-one",
>             "otherEntityField": "id"
>         },
>         {
>             "relationshipType": "many-to-many",
>             "otherEntityRelationshipName": "job",
>             "relationshipName": "task",
>             "otherEntityName": "task",
>             "otherEntityField": "title",
>             "ownerSide": true
>         }
>     ],
>     "fields": [
>         {
>             "fieldName": "jobTitle",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "minSalary",
>             "fieldType": "Long"
>         },
>         {
>             "fieldName": "maxSalary",
>             "fieldType": "Long"
>         }
>     ],
>     "changelogDate": "20170529152834",
>     "entityTableName": "job",
>     "dto": "mapstruct",
>     "pagination": "pagination",
>     "service": "no",
>     "angularJSSuffix": "mySuffix"
> }
> ```
>
> JobHistory.json
>
> ```yaml
> {
>     "fluentMethods": true,
>     "relationships": [
>         {
>             "relationshipType": "one-to-one",
>             "relationshipName": "job",
>             "otherEntityName": "job",
>             "otherEntityField": "id",
>             "ownerSide": true,
>             "otherEntityRelationshipName": "jobHistory"
>         },
>         {
>             "relationshipType": "one-to-one",
>             "relationshipName": "department",
>             "otherEntityName": "department",
>             "otherEntityField": "id",
>             "ownerSide": true,
>             "otherEntityRelationshipName": "jobHistory"
>         },
>         {
>             "relationshipType": "one-to-one",
>             "relationshipName": "employee",
>             "otherEntityName": "employee",
>             "otherEntityField": "id",
>             "ownerSide": true,
>             "otherEntityRelationshipName": "jobHistory"
>         }
>     ],
>     "fields": [
>         {
>             "fieldName": "startDate",
>             "fieldType": "ZonedDateTime"
>         },
>         {
>             "fieldName": "endDate",
>             "fieldType": "ZonedDateTime"
>         },
>         {
>             "fieldName": "language",
>             "fieldType": "Language",
>             "fieldValues": "FRENCH,ENGLISH,SPANISH"
>         }
>     ],
>     "changelogDate": "20170529152835",
>     "entityTableName": "job_history",
>     "dto": "mapstruct",
>     "pagination": "infinite-scroll",
>     "service": "serviceImpl",
>     "angularJSSuffix": "mySuffix"
> }
> ```
>
> Location.json
>
> ```yaml
> {
>     "fluentMethods": true,
>     "relationships": [
>         {
>             "relationshipType": "one-to-one",
>             "relationshipName": "country",
>             "otherEntityName": "country",
>             "otherEntityField": "id",
>             "ownerSide": true,
>             "otherEntityRelationshipName": "location"
>         }
>     ],
>     "fields": [
>         {
>             "fieldName": "streetAddress",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "postalCode",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "city",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "stateProvince",
>             "fieldType": "String"
>         }
>     ],
>     "changelogDate": "20170529152830",
>     "javadoc": "not an ignored comment",
>     "entityTableName": "location",
>     "dto": "mapstruct",
>     "pagination": "no",
>     "service": "serviceImpl",
>     "angularJSSuffix": "mySuffix"
> }
> ```
>
> Region.json
>
> ```yaml
> {
>     "fluentMethods": true,
>     "relationships": [],
>     "fields": [
>         {
>             "fieldName": "regionName",
>             "fieldType": "String"
>         }
>     ],
>     "changelogDate": "20170529152828",
>     "entityTableName": "region",
>     "dto": "mapstruct",
>     "pagination": "no",
>     "service": "serviceImpl",
>     "angularJSSuffix": "mySuffix"
> }
> ```
>
> Task.json
>
> ```yaml
> {
>     "fluentMethods": true,
>     "relationships": [
>         {
>             "relationshipType": "many-to-many",
>             "relationshipName": "job",
>             "otherEntityName": "job",
>             "ownerSide": false,
>             "otherEntityRelationshipName": "task"
>         }
>     ],
>     "fields": [
>         {
>             "fieldName": "title",
>             "fieldType": "String"
>         },
>         {
>             "fieldName": "description",
>             "fieldType": "String"
>         }
>     ],
>     "changelogDate": "20170529152832",
>     "javadoc": "Task entity.\n@author The JHipster team.",
>     "entityTableName": "task",
>     "dto": "mapstruct",
>     "pagination": "no",
>     "service": "serviceImpl",
>     "angularJSSuffix": "mySuffix"
> }
> ```
>
>
> ##### **Browsers and Operating System**
>
> java version "1.8.0_131"
> Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
>
> git version 2.7.4
>
> node: v6.10.3
>
> npm: 3.10.10
>
> yeoman: 1.8.5
>
> yarn: 0.24.5
>
> Docker version 17.05.0-ce, build 89658be
>
> docker-compose version 1.9.0, build 2585387
>
> Execution complete

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N.A.

##### **Browsers and Operating System**

N.A.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
- They should be mapped the same way as what we do with Jackson 
- We do this, both for Jackson and DTOs, as otherwise we would get the whole entity graph, and also because there are bi-directional relationships (our default) which cause circular graph issues

**Comment by deepu105** [comment]
@jdubois should we close this or do you think its a good idea?

**Comment by jdubois** [comment]
@deepu105 this has been opened for so long, with no comment or work, let's close this

**Comment by xdelox** [comment]
I apologize for not having responded anymore.
Bidirectionalism, in fact, makes the problem not trivial. The implementation I expected is what has been done in the case of many-to-many relationships, which seems to be unidirectional.

For this reason, the question could probably be addressed on two levels:
1. By introducing the concept of optional unidirectional relationship also for other types of relationships, which are not always bidirectional in many implementations.
2. Avoiding loops through an advanced mapping with mapstruct (for example, on the non-owner side of the report, in the DTO, the corresponding field of the owner-side could be left blank or not mapped at all). But I do not know if this solution is actually feasible and reasonable.

I apologize again for not keeping the thread alive.

Regards.
S.

**Comment by deepu105** [comment]
@xdelox we won't be adding uni directional relationships please see https://github.com/jhipster/generator-jhipster/issues/1569 for discussion on that so that is not an option.
