### ISSUE TITLE
Small frontend issue

### ISSUE THREAD

**Issue by mtdx** [jhipster/generator-jhipster#5856]
I know there is a template but maybe just an image will suffice

https://gyazo.com/61dd0762032221da5c277a73f8679f45

There are 2 small issues in that gif, first when you're in a popup and some error happens, it also shows in the back, and the problem is the image being to big, the "Field Image cannot be empty" isn't that descriptive.

**Comment by jdubois** [comment]
Are you using AngularJS 1 or Angular 4? I'm sorry but could you follow the guidelines?

**Comment by mtdx** [comment]
angular 4, with a freshly generated 1.5.2 app, chrome, a basic entity with an image field, and a max bytes restriction.

**Comment by gmarziou** [comment]
1.5.2 is not a JHipster version, please re-open a new issue and follow guidelines

**Comment by mtdx** [comment]
Sorry I meant 4.5.2

**Comment by gmarziou** [comment]
Anyway we cannot spend time trying to reproduce your problem if you don't provide the required details like the ones specified in template.

**Comment by deepu105** [comment]
We ask for the details for a reason


Thanks & Regards,
Deepu
