### ISSUE TITLE
OAuth Grant Type Password is showing Client-Id and Secret

### ISSUE THREAD

**Issue by bassemZohdy** [jhipster/generator-jhipster#586]
there is using for OAuth2 grant type password, and for this type you have to provide the client with client Id and secret, for that you are sharing the client id and secret in service.js which mean that any one can access it from browser, I am suggesting in case of js client to use implicate grant type.

**Comment by maxleiko** [comment]
Seems like jHipster 2.x is still giving free access to the secret in `components/auth/provider/auth.oauth2.service.js` **and** uses `Basic` auth in the end.  

Do you plan on modifying this, or is it like that on purpose ?

**Comment by maxleiko** [comment]
@jdubois @jmirc

**Comment by jdubois** [comment]
From my understanding, and from the comment from @jmirc , the secret key is mandatory for OAuth2 to work. It's the only way to have the correct encryption, and it looks like it's the normal default behavior.

**Comment by maxleiko** [comment]
Agreed, the thing is, as it is available in the client code-base, it is available for "the world".  
I am asking if this is intended, and if it is, then why do every online documentations about OAuth2 mention that your **client_secret** must remain hidden.

**Comment by jdubois** [comment]
I have no idea... We just use the OAuth service provided by Spring Security, and it seems that it's supposed to work that way: we did not modify it, and it's waiting for this parameter.

I didn't code this, and I don't know OAuth2, so I'm not the best person to answer you on this.

**Comment by flythebluesky** [comment]
AFAIK, the key here is that the user must also provide a password (which is
truly secret), so public exposure of the client_secret is not sufficient to
gain access to a user's data (as would be the case for regular OAuth2).
