### ISSUE TITLE
Current user entity

### ISSUE THREAD

**Issue by mtdx** [jhipster/generator-jhipster#5861]
##### **Overview of the issue**

Not a bug but a feature request, an option that makes an entity accessible only to the user that created it, (current user).

##### **Motivation for or Use Case**

You can add a one-to-one relationship to the current user and get the findByUserIsCurrentUser for the get all endpoint, but that's just a start, you need to do a lot of hacking around, to secure all the other rest endpoints, otherwise anyone can just try random ids, and GET, PUT, etc other user entities, let's say you can secure those too by querying the database, then there is the elastic search which will search all entities.

I think the need for such entity is common enough to be included as an option, eg. invoices, user images, emails, notifications, user profiles etc. 

Thanks

**Comment by deepu105** [comment]
Currently JHipster doesn't handle the Authorisation part. You have to do it yourself as this will vary based on your business case. Its difficult to make this generic without having a proper Authorization workflow. I tried to do something long back but there wasnt much interest and hence it was not pursued. So i'm afraid we wont be doing this in the near future as there are no generic solution here.

You can ofcourse try to build a JHipster module to do this and if you are successful we could consider pulling it into the generator

**Comment by louisn** [comment]
I am interested in building such a module.  I have read as much as I can find on the topic and also created a module with the module generator.

1. Is there documentation on the template mechanism used?
2. Is there anyone actively working on such a module for collaboration?

**Comment by jdubois** [comment]
The template mechanism is called EJS: http://ejs.co/  - it's very simple, in fact I have never read the documentation :-)
I don't think anybody is working on this

**Comment by gmarziou** [comment]
Yes this is a common use case, having done it in several projects. I would advise that your module does not alter the JHipster entity REST APsI as you're going to need them for admin purpose, I would rather define new endpoints maybe as nested resources of user or with a path prefix like "my" (e.g. `/api/my/invoices`)

**Comment by louisn** [comment]
Thanks so much for your comments!  I have created a github project for the module. https://github.com/louisn/jhipster-user-module
I was hoping not to modify each entity layer and perhaps creating a cross-cut or filter chain type of solution that just takes care of the User for each entity at the data layer.  However a separate api path should still be in place.
