### ISSUE TITLE
want to modify the name of ID field before creating an entity

### ISSUE THREAD

**Issue by AmsaveniMidhun** [jhipster/generator-jhipster#5863]
This is not a bug, but a suggestion.

When we create an entity, by default ID field gets generated. 

As per my project requirement, i do not want ID field in all my table, instead i want to change the name of the ID field, say tenant_id, likewise.

Is there any way to do so, before creating an entity ?

**Comment by jdubois** [comment]
Not really. As this is a question, could you use StackOverflow instead?

**Comment by gmarziou** [comment]
I think https://www.npmjs.com/package/generator-jhipster-db-helper is bale to rename columns.

**Comment by AmsaveniMidhun** [comment]
gmarziou, i tried using the mentioned plugin. That helps to rename the table name and columns. But, couldn't rename ID column name, as that does not provides option for that.

As per my project requirement, i want to rename the ID coulmn name to Tenant_Id for all the entitites. IS there any way to achieve this ? 

I have posted this concern in stackoverflow, but dint get any help !!

**Comment by gmarziou** [comment]
This is work in progress: https://github.com/bastienmichaux/generator-jhipster-db-helper/issues/20

You did not get any help on stackoverflow because there's currently no generic solution and you have to do it manually.

**Comment by AdrienHorgnies** [comment]
I have ended this feature and I've merge it in our dev branch. However I'll add some test cases before merging into master.
