### ISSUE TITLE
Missed update in Elasticsearch after update user via service/UserService.updateUser

### ISSUE THREAD

**Issue by FireWolf2007** [jhipster/generator-jhipster#5867]
##### **Overview of the issue**

Missed update in Elasticsearch after update user via service/UserService.updateUser

##### **Motivation for or Use Case**

Update user from REST doesn't update it's elasticsearch record.

##### **Reproduce the error**

Update, for example, user name and search user in elasticsearch repository - old name will be returned.

##### **Suggest a Fix**
Add save into updateUser method if used ElasticSearch engine in application.

Our patch for service/UserService.java.java updateUser method:
```
--- a/service/UserService.java
+++ b/service/UserService.java
@@ -190,6 +190,7 @@ public class UserService {
                 userDTO.getAuthorities().stream()
                     .map(authorityRepository::findOne)
                     .forEach(managedAuthorities::add);
+                userSearchRepository.save(user);
                 log.debug("Changed Information for User: {}", user);
                 return user;
             })
```

Patched method:
```
    /**
     * Update all information for a specific user, and return the modified user.
     *
     * @param userDTO user to update
     * @return updated user
     */
    public Optional<UserDTO> updateUser(UserDTO userDTO) {
        return Optional.of(userRepository
            .findOne(userDTO.getId()))
            .map(user -> {
                user.setLogin(userDTO.getLogin());
                user.setFirstName(userDTO.getFirstName());
                user.setLastName(userDTO.getLastName());
                user.setEmail(userDTO.getEmail());
                user.setImageUrl(userDTO.getImageUrl());
                user.setActivated(userDTO.isActivated());
                user.setLangKey(userDTO.getLangKey());
                Set<Authority> managedAuthorities = user.getAuthorities();
                managedAuthorities.clear();
                userDTO.getAuthorities().stream()
                    .map(authorityRepository::findOne)
                    .forEach(managedAuthorities::add);
                userSearchRepository.save(user);
                log.debug("Changed Information for User: {}", user);
                return user;
            })
            .map(UserDTO::new);
    }
```

##### **JHipster Version(s)**

```
telestat@0.0.0 /
├── generator-jhipster@4.5.2 
└─┬ generator-jhipster-elasticsearch-reindexer@0.3.0
  └── generator-jhipster@4.5.1 

```

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v6.10.3

npm: 3.10.10

bower: 1.8.0

gulp:
[09:11:18] CLI version 1.3.0
[09:11:18] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.24.4

Docker version 1.12.6, build 78d1802

docker-compose version 1.11.2, build dfed245

##### **Browsers and Operating System**
Any OS, any browser.

- [v] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@FireWolf2007 : would you like to do a PR to fix that ?
