### ISSUE TITLE
Feature Request: Infinispan cache support

### ISSUE THREAD

**Issue by srinivasa-vasu** [jhipster/generator-jhipster#5874]
[Infinispan](http://infinispan.org/about/)

I was wondering if it would make sense to add Infinispan support as an L2 cache (with jcache and spring cache compatibility), will do a PR.

As an L2 embedded cache to begin with and later on support for client/server mode as well to offer a pure play micro services support by offloading cache layer separately.

**Comment by sendilkumarn** [comment]
#1491 just for your reference. 

But recent interaction with Bernard makes me think why can't we have it ;)

**Comment by jdubois** [comment]
Yes +1

- We now use JCache so that should make it easier for you
- We also support Spring Cache, it shouldn't be hard but you also need this (not only Hibernate L2 cache)

**Comment by jdubois** [comment]
So @srinivasa-vasu will you do this as a PR? Do you know when you'll be working on this?

**Comment by srinivasa-vasu** [comment]
@jdubois - Yes, I will. I have started this, will send across the request in couple of days.

**Comment by jdubois** [comment]
Closing as the PR is merged -> this is still very beta, and I put some comments on the PR, but at least it looks like it's working fine :-)
