### ISSUE TITLE
Liquibase 3.2.0 makes the exectuable WAR fail

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#588]
Liquibase was upgraded to 3.2.0 (I think this was by @jmirc - Jérôme do you confirm?)

- create an exectuable WAR ("mvn package")
- run it ("java -jar mywar.war")

You will get the following error: http://stackoverflow.com/questions/24928673/spring-boot-jetty-liquibase-jar-not-find-implementation-of-liquibase-logging

Downgrading to Liquibase 3.1.1 solves the problem. This is a blocker issue for our next release.

**Comment by jdubois** [comment]
@nvoxland this is in fact a Spring issue! I'm correcting it...

**Comment by jdubois** [comment]
@nvoxland I have no problem with the executable WAR, as of version 3.5.0-SNAPSHOT from yesterday!
When can you release?

**Comment by nvoxland** [comment]
Good it is all working. If you have everythign you need with the liquibase-hibernate build with 3.5.0 I'll get it released today or tomorrow.

**Comment by jdubois** [comment]
@nvoxland we stil have the NPE from https://github.com/jhipster/generator-jhipster/issues/754#issuecomment-68447462 and this is really a blocker

**Comment by nvoxland** [comment]
The NPE should be fixed now.
