### ISSUE TITLE
Provide translate values during page title translation in Angular2

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#5895]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) with the JHipster tag.
- For bug reports its mandatory to paste the result of command `jhipster info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**

Nowadays, the page title is dynamically changed to match the curent route thanks to a metadata provided. For some page it would be nice to have a title template and instanciate it with extra data
Example:
URL: `settings/john`
Route: `settings/:login`
Page Title: `Settings {{login}}`
Rendered Title: `Settings john`

##### **Motivation for or Use Case**

This feature sounds like a minor thing but IMHO it enhances the UX of the app.
It could also be a showcase of how to setup a mechanism to have dynamic titles (for notifications mechanism for example).

##### **Suggest a Fix**

The hardest part is to know how to provide the translate-values.
In the route definition we have a static metadata field `data` but we can't react to a route param or call a service.
In the `main.component.ts` we retrieve the route and its metadata to get the title translation. We get access to the route param. Maybe we can only provide the [ActivatedRouteSnapshot#params](https://angular.io/docs/ts/latest/api/router/index/ActivatedRouteSnapshot-interface.html#!#params-anchor) object to the translation (the object is a map of `RouteParamName:RouteParamValue`, for example {login:john}. 

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
What about removing pageTitle from route meta data to disable it and calling Title.setTitle() from component?

**Comment by danielpetisme** [comment]
Indeed it's a way to achieve it indeed (a bit afraid of the copy/paste in every component). I imagined there is a more generic way but your answer makes totally sense and we could close this issue with just a tips to publish a snippet somewhere.
So up to you to maintain this issue open or not.

**Comment by gmarziou** [comment]
To avoid copy/pasting in every component, we could define a I18nTitle service that would wrap Title service and provide translations.

Let's close it for now unless someone wants to propose a pull request.
