### ISSUE TITLE
In Navbar More Than One Menu Selected

### ISSUE THREAD

**Issue by uyeliksiz** [jhipster/generator-jhipster#5897]
##### **Overview of the issue**

In Navbar list, _routerLinkActive="active"_ provides to showing selected link. But in similar routes it may set multiple menus as active. 

##### **Motivation for or Use Case**

In my case i have two routes: 
-  /apps  
-  /apps/analytics

when i route to **/apps/analytics** Navbar set both of them shown as active 

![image](https://user-images.githubusercontent.com/24546039/26973687-50dd6282-4d20-11e7-820c-b5e756a09b1b.png)

##### **Suggest a Fix**

adding  **[routerLinkActiveOptions]="{ exact: true }"** to _<a class="dropdown-item" routerLink="apps/analytics" routerLinkActive="active"_ solves the problem. 

##### **JHipster Version(s)**

4.5.2

##### **JHipster configuration**

    "jhipsterVersion": "4.5.2",
    "clientFramework": "angular2",

**Comment by gmarziou** [comment]
Thanks, would you like to submit a pull request?

**Comment by sendilkumarn** [comment]
closed by #5898
