### ISSUE TITLE
docker-compose up does not starts gateway properly

### ISSUE THREAD

**Issue by ygokirmak** [jhipster/generator-jhipster#5903]
##### **Overview of the issue**

When  gateway is run within general docker-compose configuration, ui rendered as empty.

##### **Reproduce the error**

```
mkdir jhipster-demo
cd jhipster-demo
mkdir gateway
cd gateway
jhipster ( create gateway )
yarn start ( it is ok! )
./mvnw package -Pdev docker:build
cd ..
mkdir docker-compose
cd docker-compose
jhipster docker-compose
docker-compose up -d
```
Gateway starts successfully but bec js fiels are not inserted to index.html UI is empty.

##### **JHipster Version(s)**
4.5.3

##### **JHipster configuration**

```
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

gateway@0.0.0 /home/infoowl/git/jhipster-demo/gateway
├── UNMET PEER DEPENDENCY @angular/common@4.1.3
├── UNMET PEER DEPENDENCY @angular/core@4.1.3
└── generator-jhipster@4.5.3 
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.beyondpredict.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.3",
    "baseName": "gateway",
    "packageName": "io.beyondpredict.gateway",
    "packageFolder": "io/beyondpredict/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "fcdab8ce94a0c704407ed174b00e7fd977435703",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Browsers and Operating System**
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v7.10.0

npm: 4.2.0

yeoman: 1.8.5

yarn: 0.24.5

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.13.0, build 1719ceb

Execution complete

```

##### **Browsers and Operating System**
```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

- [x] Checking this box is mandatory (this is just to show you read everything)

### Index HTML
```

<!doctype html>
<html class="no-js" lang="en">
<head>
    <base href="./" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>gateway</title>
    <meta name="description" content="">
    <meta name="google" value="notranslate">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#000000">
    <link rel="shortcut icon" href="favicon.ico" />
    <link rel="manifest" href="manifest.webapp" />
</head>
<body>
    <!--[if lt IE 9]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <jhi-main></jhi-main>
    <script>
        // load shim for IE
        if (window.navigator.userAgent.indexOf('Trident/') > 0) {
            var script = document.createElement('script');
            script.src = 'core-js-shim.min.js';
            script.type = 'text/javascript';
            document.getElementsByTagName('head')[0].appendChild(script)
        }
    </script>
    <noscript>
        <h1>You must enable javascript to view this page.</h1>
    </noscript>
    <!-- uncomment this for adding service worker
        <script>
            if ('serviceWorker' in navigator) {
                 navigator.serviceWorker
                    .register('./sw.js')
                    .then(function() { console.log('Service Worker Registered'); });
            }
        </script>
    -->
    <!-- Google Analytics: uncomment and change UA-XXXXX-X to be your site's ID.
    <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='//www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','UA-XXXXX-X');ga('send','pageview');
    </script>-->
</body>
</html>

```

**Comment by jdubois** [comment]
That's because you packaged it with the dev profile !
Have a look at the documentation, only prod profile makes sense if you do a Docker image.

**Comment by ygokirmak** [comment]
@jdubois what is the reason for this. I am getting hard to understand new version's docker-compose usage. I mean it seem now it is not feasible to use single docker-compose for local development because I need to build applications in prod profile and prod profile has prod configuration...

What do you advice for developing in local with say a gateway and a microservice

**Comment by ygokirmak** [comment]
Thanks @jdubois let me clarify my use case in case there may be others in same situation. 

I am developing a microservice application which has a gateway and a microservice. During development I need
- Changes on code should reflected to UI without restarting gateway ( so I need to run with yarn )
- Applications should run with dev profile ( so running with docker does not work bec it works correctly with prod profile )
- Both gateway and microservice should be up and connected each other via jhipster-registery

The simplest way I found is below
- create docker compose folder and run `jhipster docker-compose` in it
- remove gateway and microservice from docker-compose configuration
- make minor changes on docker configuration ( [check this](https://github.com/ygokirmak/jhipster-sample-v4.5/commit/52f6b8c208cec12a7865ef0ac75f212bb47cccde) ) 
- docker-compose up -d ( starts mongo, registery and elk )
- cd into gateway; first `./mvnw` then `yarn start`
- cd into microservice `/mvnw` 

this setup reasonable for me but may be I am doing something wrong and I am sure you have a simpler advice :)

**Comment by jdubois** [comment]
Well, you have the choice:

- If you want "dev" mode, don't run with Docker (you won't have hot reload, obviously), so it's "./mvnw" and "yarn start" in your app
- If you don't want to work on a microservice (for example it comes from another team), then it's easier to use it as a Docker image (so you have the database, and everything fully setup without having to think about it)

That's why the "docker-compose" sub-generator asks you which images you want to include: you can choose, and mix those options depending on your needs.

**Comment by ygokirmak** [comment]
ok.. I got the point. thanks
