### ISSUE TITLE
Bug with Node.js 8.1.0 on Linux

### ISSUE THREAD

**Issue by JulioJu** [jhipster/generator-jhipster#5905]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) with the JHipster tag.
- For bug reports its mandatory to paste the result of command `jhipster info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**

On Linux , with NodeJS 8.1.0,  it's impossible to use arrow keys when we generate a new project with command `jhipster` or `yo jhipster`.

I've tried with zsh, sh, bash, and with Gnome-Terminal, XTerm, tty, and with Yeoman 1.8.5 or 2.0.0 and with Jhipster 4.3.0, 4.5.2 and 4.5.3.  

If we kill yeoman (`pkill yo`), after having use this command, in the same shell there are many other issues with other commands like sudo (can't enter passwords).

With Nodejs 8.1.0, there is no problems with command  `jhipster entity myentityname`.

With NodeJS 7.9.0, there isn't any problem. All work fine. 

##### **Motivation for or Use Case**

It's a bug because we can't generate a new project ! And it's a bug because after having kill yo, there are a lot of other issues with other commands like sudo !

##### **Reproduce the error**

* Install Linux and Node.js 8.1.0
* In a new folder, type `yo jhipster` or `jhipster`
* Try to use arrow keys. Doesn't work.
* In an other terminal, kill yeoman (`pkill yo`)
* In the first terminal, try to run `sudo` it's not possible to enter password. 
* Try other commands with inputs, like ([Y/n]. 

##### **Related issues**

Nothing found on https://github.com/yeoman/yo/issues

##### **Suggest a Fix**

Is it a bug with JHipster generator ? Or Yeoman ? 

##### **JHipster Version(s)**

Bug with Jhipster 4.3.0, or 4.5.2 or 4.5.3. 

##### **JHipster configuration**

It's for a new project. So this section it's irrelevant. 

##### **Browsers and Operating System**

Linux

- [ *] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
That's why we tell to use an LTS version in our documentation...

**Comment by JulioJu** [comment]
Maybe, I must add a bug report on Yeoman ?

**Comment by jdubois** [comment]
Yes

**Comment by miclill** [comment]
This is a bug in nodejs. It was fixed then reintroduced. 6.x LTS works. See here:
https://github.com/yeoman/yo/issues/360

**Comment by JulioJu** [comment]
Ok !
