### ISSUE TITLE
Upgrading 4.5.2 to 4.5.3 problems

### ISSUE THREAD

**Issue by uyeliksiz** [jhipster/generator-jhipster#5906]
##### **Overview of the issue**

I am running _jhipster upgrade_  but after all process there is no change. 

##### **Motivation for or Use Case**

i am tring to upgrade jhipster 4.5.2 to 4.5.3. 
after upgrading, .yo-rc.json file shows jhipsterVersion still 4.5.2. 
I then tried it with --verbose. I show that The new version(4.5.3) of jhipster-generator is installed but does not generate with it.
![image](https://user-images.githubusercontent.com/24546039/27004716-cc514806-4e16-11e7-8b0d-5644abbd19dd.png)
I dont know why..

##### **JHipster Version(s)**

4.5.2 -> 4.5.3

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "a.b.c.d"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "OakWebApp",
    "packageName": "a.b.c.d",
    "packageFolder": "a/b/c/d",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "########################################",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

Win10

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
There is already an opened ticket about the sub generator upgrade: https://github.com/jhipster/generator-jhipster/issues/5883

I'm closing this ticket.
