### ISSUE TITLE
resource filter is not working with generated pom.xml

### ISSUE THREAD

**Issue by ranjitkumarsingh** [jhipster/generator-jhipster#5910]
##### **Overview of the issue**
Maven resource filter is not working if trying to add properties with bind variables.

##### **Reproduce the error**
If I add following property or similar into application.yml, it should be substituted accordingly after each maven build which is not happening.
version: @project.version@

##### **Suggest a Fix**
removing everything related to "maven-resources-plugin"  into generated pom.xml should fix this issue as it seems this is irreverent and causing some adverse effect opposed to what is already there in parent pom.

##### **JHipster Version(s)**
4.3.0

##### **Browsers and Operating System**

- [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
The delimiter is `#`, so if you use `#project.version#`, it should work.

Look at this line: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/_pom.xml#L923

For example [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/_logback-spring.xml#L43), the `#logback.loglevel#` is used and it works well.

Can you try ?

**Comment by ranjitkumarsingh** [comment]
Yes you are right, its working with #. I din't realize the delimiter has been set to #. closing this issue.
