### ISSUE TITLE
Relation "datcat_attribute_metadata" does not exist

### ISSUE THREAD

**Issue by manishjn** [jhipster/generator-jhipster#5914]
JHipster is not creating the table **DatcatAttributeMetadata** to the database. This is a child table with a foreign key relationship manyToOne with parent table DatcatAttributeMetadata.
Parent table was created earlier but when adding DatcatAttributeMetadata using entity module this table is not being added to PostgresSql and throwing an error ERROR: relation "datcat_attribute_metadata" does not exist

Jhipster version v4.0.8

[Master_changelog.zip](https://github.com/jhipster/generator-jhipster/files/1069467/Master_changelog.zip)

**Comment by ruddell** [comment]
Please fill out the template and provide your configuration.

This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by manishjn** [comment]
Have opened it stackoverflow for now with detailed description.

https://stackoverflow.com/questions/44509426/jhipsterrelation-datcat-attribute-metadata-does-not-exist

**Comment by jdubois** [comment]
Please follow the guidelines, and don't cross post with Stackoverflow, this makes us lose time
