### ISSUE TITLE
Feature Request: Swap PhantomJS for Headless Chrome

### ISSUE THREAD

**Issue by ggotti** [jhipster/generator-jhipster#5915]
##### **Overview of the issue**
With Chrome now supporting a [headless option](https://developers.google.com/web/updates/2017/04/headless-chrome), PhantomJS support has been dropped from [Protractor](https://github.com/angular/protractor/blob/master/docs/browser-setup.md#setting-up-phantomjs). I'd like to see Headless Chrome replace PhantomJS as the preferred browser for Protractor and Karma.

##### **Motivation for or Use Case**
Unfortunately the lead maintainer for [PhantomJS](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE) is stepping down, meaning there will likely be no additional releases of PhantomJS.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by cbornet** [comment]
We need to check first if Chrome 59 can be installed easily on any system (dev computer but also CI, docker, ...). It seems Travis supports it : https://github.com/travis-ci/travis-ci/issues/7650

**Comment by PierreBesson** [comment]
@cbornet Chrome 59 is already available for Mac os and linux which support headless mode. However headless will only be supported on Windows for Chrome 60: https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by deepu105** [comment]
this is not urgent. lets wait until its available everywhere. Also another
thing to consider is will everyone have chrome? I have colleagues who
doesnt use chrome at all, so its not uncommon


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Let's not rush for this. We have something which is very stable today, and doesn't cause any issue: we clearly have higher priorities at the moment.

**Comment by PierreBesson** [comment]
Personally I think the benefits of headless chrome are huge. Also phantomjs is often causing problems in some environments (in my experience) so I think it would be a good move to do the switch. Chrome could be launched in a docker image which would work everywhere for example with this: https://hub.docker.com/r/selenium/standalone-chrome/.
