### ISSUE TITLE
Bug: Ubuntu - jhipster:app freezes when specifying app type

### ISSUE THREAD

**Issue by cm45t3r** [jhipster/generator-jhipster#5916]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) with the JHipster tag.
- For bug reports its mandatory to paste the result of command `jhipster info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**

jhipster app generator freezes when asking for application type, not allowing to choose among the options. When it happens, the terminal does not respond to any key (from Ctrl+C / Z to digits).

##### **Motivation for or Use Case**

Debugging the generator or yeoman do not show anything but seem to lock the terminal.

##### **Reproduce the error**

1. Install yeoman and generator-jhipster using yarn or npm.
2. mkdir myapp && cd myapp
3. jhipster
4. It asks to choose application type using arrows, but it completely freezes/hangs this time.

##### **Suggest a Fix**

Seems to be caused directly by yeoman.

##### **JHipster Version(s)**

generator-jhipster@4.5.3

##### **JHipster configuration**

user@host:~/myapplication$ yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/home/user/myapplication
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v8.1.0

npm: 5.0.3

yeoman: 2.0.0

yarn: 0.24.6

##### **Browsers and Operating System**

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Linux main 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
The problem comes from node 8. You should use a LTS version instead. 
You can see this ticket https://github.com/jhipster/generator-jhipster/issues/5905

**Comment by cm45t3r** [comment]
Thank you!
