### ISSUE TITLE
Modelio UML example file is invalid

### ISSUE THREAD

**Issue by MKITConsulting** [jhipster/generator-jhipster#5924]
Hello,

the Modelio file ([link](https://github.com/jhipster/jhipster-uml/blob/master/test/xmi/modelio.xmi)) linked on the [jhipster-uml example page](https://jhipster.github.io/jhipster-uml/#examples) cannot be imported:

![modelio 3 6 import error](https://user-images.githubusercontent.com/29451012/27172565-fe126c92-51b5-11e7-9dd5-a942958233bb.png)

I've just tested this on Modelio 3.6.

**Comment by deepu105** [comment]
@MKITConsulting please open the issue on the JHipster UML project https://github.com/jhipster/jhipster-uml
