### ISSUE TITLE
angular2-cookie library Deprecated, Please replace it with ngx-cookie

### ISSUE THREAD

**Issue by unikzforce** [jhipster/generator-jhipster#5925]
##### **Overview of the issue**
replacing  old angular2-cookies with the newer ngx-cookies.

##### **Motivation for or Use Case**

the old angular2-cookies library is giving some warnings, when running 'yarn install', stating that the old angular2-cookies has incorrect peer dependency angular/core 2.
but for ngx-cookie this warning disappears.
would you please replace it with the newer library from the same person on github?

the 'angular2-cookie' repo ---> https://github.com/salemdar/angular2-cookie
in his repository salemdar stated that 'angular2-cookie' is deprecated, and suggested to use 'ngx-cookie'

##### **Suggest a Fix**

the 'ngx-cookie' repo ---> https://github.com/salemdar/ngx-cookie

in package.json and webpack.vendor.js replace angular2-cookie with ngx-cookie. 
and in 'shared.module.ts' & csrf.service.ts. replace ngx-cookie with angular2-cookie in import clauses , like this:
import { CookieService } from 'ngx-cookie';

##### **JHipster Version(s)**

4.5.3

##### **Browsers and Operating System**

- [+ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
This is already done in master
