### ISSUE TITLE
JDL on Visual Stadio Isn't Working

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#5928]
##### **Overview of the issue**

I would like to generate a class diagram for a .jdl file

##### **Reproduce the error**

After loading a jdl file, I run PlantUML according to the instruction on https://jhipster.github.io/jhipster-ide/ and I get an error, "Image file .png not found!"

##### **Suggest a Fix**

?

##### **JHipster Version(s)**

4.5.2

##### **JHipster configuration**

Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/home/oem
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 4.5.0

bower: 1.8.0

gulp:
[09:36:46] CLI version 1.3.0

yeoman: 1.8.5

yarn: 0.23.4

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.8.0, build unknown

##### **Browsers and Operating System**

Linux Mint 18.1

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Could you please open the issue in the jhipster-ide project

**Comment by vw98075** [comment]
I will do so. Sorry for posting in a wrong project.
