### ISSUE TITLE
 generators from the JHipster Marketplace?  yes create fail

### ISSUE THREAD

**Issue by yanweiqi** [jhipster/generator-jhipster#5934]
██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔══ ═██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://jhipster.github.io

Welcome to the JHipster Generator v4.5.3
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: E:\er\jhipster\blog
? (1/16) Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? (2/16) What is the base name of your application? ywqblog
? (3/16) Would you like to install other generators from the JHipster Marketplace? Yes
undefined:1
Internal Server Error
^

SyntaxError: Unexpected token I in JSON at position 0
    at Object.parse (native)
    at generator.httpsGet (D:\deveolpTools\node\node_global\node_modules\generator-jhipster\generators\app\prompts.js:159:37)
    at IncomingMessage.res.on (D:\deveolpTools\node\node_global\node_modules\generator-jhipster\generators\generator-base.js:2097:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by deepu105** [comment]
I tried this and yes its failing. I think there is a package that is malformed. I'm gonna make sure that package errors dont propogate here so that its just warns and continues

**Comment by deepu105** [comment]
fixed via https://github.com/jhipster/generator-jhipster/commit/d53c4034a8b7c340aa0959e221827f627399a333

**Comment by deepu105** [comment]
@jdubois I think we need to do a patch release for this

**Comment by deepu105** [comment]
doc updated https://github.com/jhipster/jhipster.github.io/pull/447

I think the npms.io service is down temporarily
