### ISSUE TITLE
Give the possibility to invalidate a password after a given timespan (and allow to set the timespan via yaml)

### ISSUE THREAD

**Issue by Pinguwien** [jhipster/generator-jhipster#5938]
##### **Overview of the issue**

Let jhipster generate a password reset key or an account actication key, at the moment these keys are usable forever. 
In many use cases where you create a portal-app, this is not preferred. Often it is more something along these lines: "This key is usable for the next 24h". So, instead of being usable forever, I'd like to request a possibility to enter a timespan after which the values will be deleted.

##### **Motivation for or Use Case**

If it is not intended to add such feature to the core project, I'd like to discuss the implementation for me if you don't mind.
At the moment I just thought about checking the created_date and reset_date fields every hour with a scheduled timer and then removing the activation_key and reset_key in jhi_user for the entries which are older than 24 hours (and a few minutes). But tbh, I don't know if this is a good way to do this, or if there may be better ways in terms of performance and db queries.

##### **Reproduce the error**

--not applicable

##### **Related issues**

There were some talk about this feature in https://github.com/jhipster/generator-jhipster/issues/508

##### **Suggest a Fix**

--not applicable

##### **JHipster Version(s)**

4.5.2

##### **JHipster configuration**

--can be given, if needed.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

--not applicable

##### **Browsers and Operating System**
--not important

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
In fact at least the password reset key is checked for expiration when trying to consume that key:
`.filter(user -> user.getResetDate().isAfter(Instant.now().minusSeconds(86400)))`

So it is hard coded to 24 hours, which is easy to make configurable or do you mean something else?

**Comment by jdubois** [comment]
- the title is wrong, you speak of the keys and not the passwords, could you rewrite it?
- the keys do have a limited time validity, have a look at the code (sorry, I'm using my phone)

**Comment by jdubois** [comment]
Thanks @atomfrede - I'm closing this as it's easy to put in a Yaml config, so this would be against our policies

**Comment by Pinguwien** [comment]
Sorry for the inconvenience, just found the code. my bad.
