### ISSUE TITLE
can't install generator-jhipster-spring-batch module from jhipster, markeplace link is broken. I need help. Thanks

### ISSUE THREAD

**Issue by ibrodjabi** [jhipster/generator-jhipster#5939]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) with the JHipster tag.
- For bug reports its mandatory to paste the result of command `jhipster info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
The npm search service is down https://github.com/npms-io/npms-www/issues/174.
You can install the module manually but I dont think such a module exist
