### ISSUE TITLE
Configuring which entities to alert about

### ISSUE THREAD

**Issue by xtremebiker** [jhipster/generator-jhipster#5940]
I've generate a jHipster project with the 4.5.1 version and it does a really nice job. However, I'm already modifying the generated code, which is CRUD focused for all entities, and want to unify many of them.

That said, I would like to be able to choose which entities to alert about using UI-Bootstrap. Now, when I save EntityA which manages EntityB in the same view, I get two alerts for each of the entities. I just want to get the message about the first one. 

Is there any way to do it? Or just better, to disable the automatic entity messaging and doing it by hand in the controllers?

**Comment by jdubois** [comment]
I'm sorry, this isn't a bug -> could you ask your question on Stackoverflow?

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by xtremebiker** [comment]
Sure! https://stackoverflow.com/questions/44602225/configuring-which-entities-to-alert-about-in-jhipster Thanks!
