### ISSUE TITLE
Cannot generate microservice application with marketplace generators

### ISSUE THREAD

**Issue by rex-sheridan** [jhipster/generator-jhipster#5941]
##### **Overview of the issue**

When creating a microservice application and selecting to install other generators from the marketplace I receive the following error:

`
$ jhipster
Running default command
Executing jhipster:app

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://jhipster.github.io

Welcome to the JHipster Generator v4.5.3
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: /Users/rsheridan/test
? (1/16) Which *type* of application would you like to create? Microservice application
? (2/16) What is the base name of your application? test
? (3/16) Would you like to install other generators from the JHipster Marketplace? Yes
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at generator.httpsGet (/Users/rsheridan/.config/yarn/global/node_modules/generator-jhipster/generators/app/prompts.js:159:37)
    at IncomingMessage.res.on (/Users/rsheridan/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:2097:17)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
`
Screenshot
<img width="972" alt="screen shot 2017-06-16 at 10 36 39 am" src="https://user-images.githubusercontent.com/975368/27231251-06af3ce8-5280-11e7-9e9b-ae79bf0573fe.png">

##### **Motivation for or Use Case**

This was working yesterday and only began failing today after I did `yarn global upgrade generator-jhipster`.  

##### **JHipster Version(s)**
$ jhipster version
4.5.3

##### **JHipster configuration**

Here is the output of "jhipster info":

`
$ jhipster info
Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/Users/rsheridan/test
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.13.0

node: v8.1.2

npm: 5.0.3

yeoman: 1.8.5

yarn: 0.24.6

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245

Execution complete

`

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**

OS: Mac Sierra

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes that's a duplicate. Release under way!
