### ISSUE TITLE
jhipster docker setup error -  New state of 'nil' is invalid

### ISSUE THREAD

**Issue by dharmjit** [jhipster/generator-jhipster#5944]
* **Jhipster installation error Docker**

Getting below error when generating a project in docker

* **Motivation for or Use Case** 

I want to set Jhipster and start with one of the sample project but getting this error. I have also seen there is one question on SO which is not answered.

Running default command
Executing jhipster:app --npm
        New state of 'nil' is invalid.

* **Browsers and Operating System** 
Windows 7 and Chrome Browser

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
