### ISSUE TITLE
Move Authentication and User Management to micro services architecture

### ISSUE THREAD

**Issue by adnans-coviot** [jhipster/generator-jhipster#5951]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) with the JHipster tag.
- For bug reports its mandatory to paste the result of command `jhipster info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**

User and ACL management is on gateway application. This architecture makes multiple user type and multiple channel implementations very complex. 
- If we have different user types (like customer, supplier, student, teacher etc.) in the domain, these are implemented on micro services app because they need to be close to business logic. In this case, it is not easy to build one-to-one relationship with jhipster user object and say customer object, because they are in different apps. So specific customer registration, login, authentication etc. code becomes very complex.
- If there are other channels beside existing web gateway, then usual approach is to develop / generate separate gateway apps for each channel and access to the same micro services app. This leads us to have multiple user and acl repositories, which will be very complex to manage. I can think of problems with user mismatches between channels, single sign on, etc. 

##### **Motivation for or Use Case**

This is clearly a feature request, not easy to implement. Consider moving the user and acl repository to micro services app. Yes, gateway app needs to do a rest call for each user registration, login etc, but this will have a minimal performance impact. Benefits:
- Inherit / extend / relate different user types easily since they are in the same repository.
- Generate extended jwt tokens that takes specific information on user type into account. For example: Customer auth tokens will hold customer id, Supplier tokens will hold company registration id, etc.
- Extend authentication to non-user domains like iot devices easily, by not accessing user table but other specific tables in the domain.
- Allow multiple gateway apps to share same user repository
- Provide a single user management console for all channels
- Provide single sign on between multiple channels

Even better approach will be to have option to generate user management in either on the gateway sie or on micro services side, or on a separate micro services app of its own. Although last option will be a more complex architecture, it will open new doors to integrate with existing user management repositories like ldap, custom, etc.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/5920

##### **JHipster configuration**

This applies to micro services architecture of JHipster

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by xetys** [comment]
Take a look at [JHipster UAA](https://jhipster.github.io/using-uaa). This is exactly what you are asking for. It's a separate microservice, holding the user (and related) domain, and providing authentication using an OpenID-compatible flow, as well as authorization using OAuth 2 from Spring Security. So you can use OAuth 2 for internal security, and share your data to federated projects. 

As you are suggest something already implemented, I can close that issue
