### ISSUE TITLE
Upgrade to Webpack 3

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#5955]
Webpack 3 was just released:
https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

This is only for Angular 4, not AngularJS 1.

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/commit/9676d42fe8cadc71e666024126cd25b7405cd526

**Comment by jdubois** [comment]
What, already????

**Comment by jdubois** [comment]
There's a trailing comma issue, I'm on it

**Comment by deepu105** [comment]
https://github.com/jhipster/generator-jhipster/commit/f907c12ed42f7dbbd01e223a3886226f3dbbb56c
