### ISSUE TITLE
generator supports customize primary key type is possible?

### ISSUE THREAD

**Issue by dancewing** [jhipster/generator-jhipster#5957]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) with the JHipster tag.
- For bug reports its mandatory to paste the result of command `jhipster info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**

Because in actual projects, it maybe use UUID or other primary key type, will it be possible to support customize primary key type, including SQL/NoSQL.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
You can look at this module:
https://github.com/amitjindal/generator-jhipster-postgresuuid-converter

It would be a good start for what you ask and you can help to improve this module.

As already discussed, not sure we can support it, directly in our generator.

**Comment by jdubois** [comment]
And this has been already discussed, and UUID are a bad idea for database PKs.
Please use the search engine and link the existing tickets to yours.
