### ISSUE TITLE
Entity sub generator: Incorrect type for id in BaseEntity when using NoSQL

### ISSUE THREAD

**Issue by conerck** [jhipster/generator-jhipster#5958]
- For bug reports its mandatory to paste the result of command `jhipster info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**

With 4.5.5 base-entity.ts was introduced as an interface with only one property `id?: number`.
However, when using NoSQL backends ids are strings, which causes an error when running the entity generator during at-loader step of webpack compilation

```
[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
[15:14:54] [write-file-webpack-plugin] compiler.outputFileSystem is "NodeOutputFileSystem".
Hash: 49cb6275fe690133eef8
Version: webpack 2.6.1
Time: 19223ms
[./src/main/webapp/manifest.webapp] ./src/main/webapp/manifest.webapp 61 bytes {1} [built]
   [0] delegated ./node_modules/@angular/core/@angular/core.es5.js from dll-reference vendor 42 bytes {0} [not cacheable] [built]
[./node_modules/css-loader/index.js!./node_modules/postcss-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/main/webapp/content/scss/global.scss] ./~/css-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./src/main/webapp/content/scss/global.s
css 4.7 kB {2} [built]
[./node_modules/reflect-metadata/Reflect.ts] ./~/reflect-metadata/Reflect.ts 48.4 kB {1} [built]
[./node_modules/zone.js/dist/zone.js] ./~/zone.js/dist/zone.js 94.2 kB {1} [built]
[./src/main/webapp/app/account/account.module.ts] ./src/main/webapp/app/account/account.module.ts 1.87 kB {0} [built]
[./src/main/webapp/app/admin/admin.module.ts] ./src/main/webapp/app/admin/admin.module.ts 2.79 kB {0} [built]
[./src/main/webapp/app/app.constants.ts] ./src/main/webapp/app/app.constants.ts 513 bytes {0} [built]
[./src/main/webapp/app/app.main.ts] ./src/main/webapp/app/app.main.ts 594 bytes {0} [built]
[./src/main/webapp/app/app.module.ts] ./src/main/webapp/app/app.module.ts 2.73 kB {0} [built]
[./src/main/webapp/app/blocks/config/prod.config.ts] ./src/main/webapp/app/blocks/config/prod.config.ts 391 bytes {0} [built]
[./src/main/webapp/app/polyfills.ts] ./src/main/webapp/app/polyfills.ts 202 bytes {1} [built]
[./src/main/webapp/content/scss/global.scss] ./src/main/webapp/content/scss/global.scss 1.27 kB {2} [built]
  [15] delegated ./node_modules/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js from dll-reference vendor 42 bytes {0} [not cacheable] [built]
  [16] delegated ./node_modules/style-loader/addStyles.js from dll-reference vendor 42 bytes {2} [not cacheable] [built]
    + 178 hidden modules

ERROR in [at-loader] ./src/main/webapp/app/entities/picture/picture.model.ts:3:14
    TS2420: Class 'Picture' incorrectly implements interface 'BaseEntity'.
  Types of property 'id' are incompatible.
    Type 'string' is not assignable to type 'number'.
Child html-webpack-plugin for "index.html":
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html] ./~/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html 1.22 kB {0} [built]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Execution complete
```

##### **Motivation for or Use Case**

* Standard Use Case.

##### **Reproduce the error**

* Running `yo jhipster entity` with a mongoDB backend

##### **Related issues**

* None that I could find

##### **Suggest a Fix**

* base-entity.ts needs to be generated parametrized or `id` needs to be a union type. That would also allow having a gateway with backend services that use different database types or different database types for development and production mode

##### **JHipster Version(s)**

`-- generator-jhipster@4.5.5`

##### **Browsers and Operating System**

```
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)
Picked up _JAVA_OPTIONS: -Xmx2048M

git version 2.9.0.windows.1

node: v6.11.0

npm: 3.10.10

yeoman: 1.7.0

yarn: 0.24.6

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build f963d76f

```

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Yes similar to https://github.com/jhipster/generator-jhipster/blob/85b36f94e8b3540b5f493f89827ff8205fcb13b4/generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity.model.ts#L23-L29

Would you please consider submitting a pull request?

**Comment by ruddell** [comment]
Related to [this issue](https://github.com/jhipster/generator-jhipster/pull/5837), we can determine the ID type off of the database.  Note that the issue remains for gateways with microservices using differing databaseTypes.

Can we just use `string|number`, or do we need to add a third EJS check for gateways?

**Comment by jdubois** [comment]
Yes, maybe the simplest solution is to do `string|number` for gateways... Still, we do generate specific UI on the gateway depending on the backend (when Elasticsearch is selected, for instance), so we should be able to get the correct type.

**Comment by conerck** [comment]
I'll see if I can provide a pull request in the next couple of days. 
I'm pretty new to jhipster and just started evaluating it for further use in our projects, so it might take a bit until I understand the entire architecture and ramifications even for something that seems as simple as this.

**Comment by deepu105** [comment]
This has been fixed in the latest release

**Comment by deepu105** [comment]
Btw its a dirty fix with type `id?: any` in base entity now
