### ISSUE TITLE
Where is the create_tables.cql script?

### ISSUE THREAD

**Issue by piaofudeyu** [jhipster/generator-jhipster#5963]
Hi , when we try the ratelimiting ,we see GatewayConfiguration  and the commit said 
A schema with the JHipster rate-limiting tables configured, using the
     * "create_keyspace.cql" and "create_tables.cql" scripts from the
     * "src/main/resources/config/cql" directory

But , we only find the create_keyspace.cql . where is the create_tables.cql?

**Comment by jdubois** [comment]
Those should not be generated, why do we have this bug again?

**Comment by jdubois** [comment]
Just checked: they are not generated....

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by pascalgrimaud** [comment]
@jdubois : I can see this reference -> https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/_GatewayConfiguration.java#L53-L65
These comments need to be updated

**Comment by jdubois** [comment]
Oh sorry, thanks @pascalgrimaud 
@piaofudeyu next time please follow the guidelines, we're all losing time here

**Comment by jdubois** [comment]
@pascalgrimaud I'm modifying the documentation and linking my commit here

**Comment by piaofudeyu** [comment]
@jdubois  Those should not be generated ? but we see your https://github.com/jhipster/jhipster-sample-app-gateway/tree/master/src/main/resources/config/cql   there also not have this file .. 

is this our mistake do not generated?

**Comment by jdubois** [comment]
@piaofudeyu this is an old sample application - I usually re-generate them with each release, I don't know why we don't it for this one... Anyway, that's how that used to work, but it's not the case any more.

**Comment by pascalgrimaud** [comment]
It's my fault.

@jdubois : the 2 following projects were created during a Hackathon at Ippon, with @PierreBesson :
- https://github.com/jhipster/jhipster-sample-app-gateway
- https://github.com/jhipster/jhipster-sample-app-microservice

I made this pull request https://github.com/jhipster/jhipster-automated-samples/pull/3 to update them
But as it wasn't accepted, these 2 projects were not in the classic workflow.

**Comment by jdubois** [comment]
Oh sorry @pascalgrimaud I totally missed this PR, I never look at this repo!!! I have updated the scripts quite a lot, so I don't think this can be merged as is. Do you have time to have a look? Indeed, those should be generated.

**Comment by pascalgrimaud** [comment]
Ok, I would be able to rebase my PR, after lunch time :hamburger:

**Comment by deepu105** [comment]
@jdubois @pascalgrimaud I think it would also be cool to generate a complete microservice stack during each release and link it to our home page

**Comment by piaofudeyu** [comment]
@jdubois @deepu105  Thanks for your reply.

Because when I open the api limiting , it will check limiting

public RateLimitingRepository(Session session) {
        this.session = session;
        this.rateLimitingIncrement = session.prepare(
            "UPDATE gateway_ratelimiting\n" +
                "  SET value = value + 1\n" +
                "  WHERE id = :id AND time_unit = :time_unit AND time = :time");

        this.rateLimitingCount = session.prepare(
            "SELECT value\n" +
                "  FROM gateway_ratelimiting\n" +
                "  WHERE id = :id AND time_unit = :time_unit AND time = :time"
        );
    }

i think we will have the script of gateway_ratelimiting table in Cassandra.
so this is why the issues i ask.

**Comment by piaofudeyu** [comment]
@jdubois  OK . Sorry for that ,I will flow the guidelines next time. sorry again.

I try the generator version @4.5.5 . but there also have no the script, when generator the gate there is a error 52.216.80.0:443 time out . I will try again. maybe is the network issue, China will often GWF. By the way , is there a complete newer gateway application in this repository? I want to get the script to continus my ratelimiting test..  Thanks

**Comment by piaofudeyu** [comment]
Try the generator V4.5.5, also have no script . maybe it is no use. 
and try the ratelimiting , it works fine without no special config. 

Thanks all.

**Comment by pascalgrimaud** [comment]
@piaofudeyu : you can read this ticket https://github.com/jhipster/generator-jhipster/issues/5388
It was replaced by bucket4j

**Comment by piaofudeyu** [comment]
@pascalgrimaud  OK ,Thanks. but for this time ,we will no update all application. 
can we only update the gateway?

**Comment by pascalgrimaud** [comment]
That's why microservices architecture is interesting, you can upgrade 1 application without impacting all the others. So my answer would be 'yes', give it a try

**Comment by piaofudeyu** [comment]
@pascalgrimaud  wonderful !!! I will try.
