### ISSUE TITLE
[QUESTION] - Swagger documentation and UI

### ISSUE THREAD

**Issue by clun** [jhipster/generator-jhipster#5968]
Hi, I noticed that any rest controller annotated with a request mapping starting by "/api" (ex:`@RequestMapping("/api/ff4j")`) will be displayed in Swagger UI but not others like `@RequestMapping("/ff4j")` or  `@RequestMapping("/management")`.  

**Could you please point me where is define the SwaggerResourceProvider or the Docket ? Can i override it to add new patterns to scan ?**

Use Case : I'm currently working on the FF4J generator. As all the REST Controllers already exist in a dependency `ff4j-spring-boot-webapi` with request Mapping like `/ff4j/....` I would like to reuse it (yes, I also will update configuration and webpack but still...). If not possible I will import them in another way ....but it' a work around.

**Comment by PierreBesson** [comment]
I have a PR pending addressing this use case specifically: https://github.com/jhipster/generator-jhipster/pull/5892

**Comment by clun** [comment]
Well, as so we can close this issue and mark it as label Duplicated :)
