### ISSUE TITLE
Intermittent unexpected results when calling microservices

### ISSUE THREAD

**Issue by DiegoEP** [jhipster/generator-jhipster#5972]
I'm using a JHipster Gateway (using Spring Boot 1.4.4) that provides routing to a microservice (using Spring Boot 1.5.3.RELEASE). When I make a request directly to the microservice, it is OK. When I make a request via gateway (e.g. http://localhost:8080/microservice/api/resource) it works as expected in the majority of the cases. However, sometimes I receive HTML as result (instead JSON). It is pretty confusing since this route is exclusive for API access. The received HTML contains something like the header structure of the index.html (loading css and javascript resources).
I've already tried to disable the cache (I'm using ehCache), both in microservice and gateway, but it hasn't any effect.
When this situation occurs, the request not even comes to the microservice and nothing is printed in the log. It occurs for any rest request in any resource.

**Comment by pascalgrimaud** [comment]
Very very strange... 
But we need all information to reproduce, so plz complete the template. 
At least, a sample of projet on Github and a use case to reproduce, otherwise, it will be hard to help

**Comment by jdubois** [comment]
Yes please follow the guidelines, that's really annoying

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
