### ISSUE TITLE
Unidirectional and Bidirectional OneToMany Yield The Same Generated Code Structure

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#5973]
##### **Overview of the issue**

The two types of one-to-many relationship yield the same code structure. That is a big problem for me since it blocks my project. With multiple one-to-many relationships, my generated classes have duplicated attributes along with duplicated getters and setters. And Db schema has duplicated column names.

##### **Reproduce the error**

The problem can be reproduced by running this file: https://github.com/jhipster/jdl-samples/blob/master/online-shop.jh

A unidirectional one-to-many is defined as

    relationship OneToMany {
	Wishlist{product(title)} to Product
    }

and the generated code:

    @Entity
    @Table(name = "wishlist")
    @ Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    @Document(indexName = "wishlist")
    public class Wishlist implements Serializable {
      ....
        @OneToMany(mappedBy = "wishlist")
        @JsonIgnore
        @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
        private Set<Product> products = new HashSet<>();
      ...
    }

    @Entity
    @Table(name = "product")
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    @Document(indexName = "product")
    public class Product implements Serializable {
      ...
       @ManyToOne
       private Wishlist wishlist;
      ...
    }

A bidirectional one-to-many relationship is defined as

    relationship OneToMany {
	Customer{whislist(title)} to Wishlist{customer}
    }

and the generated classes

    @Entity
    @Table(name = "wishlist")
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    @Document(indexName = "wishlist")
    public class Wishlist implements Serializable {
      ....
       @ManyToOne
       private Customer customer;
    ...
    }

    @Entity
    @Table(name = "customer")
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    @Document(indexName = "customer")
    public class Customer implements Serializable {
    ...
      @OneToMany(mappedBy = "customer")
      @JsonIgnore
      @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
      private Set<Wishlist> whislists = new HashSet<>();
    ...
    }

##### **Suggest a Fix**

It shall not have a reference of the other class on the one side.

##### **JHipster Version(s)**

4.5.5

##### **JHipster Version(s)**

```
/home/oem
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

    {
      "generator-jhipster": {
        "promptValues": {
          "packageName": "com.abc.app"
        },
        "jhipsterVersion": "4.5.5",
        "baseName": "sampleOnlineShopJH",
        "packageName": "com.abc.app",
        "packageFolder": "com/abc/app",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "hibernateCache": "ehcache",
        "clusteredHttpSession": false,
        "websocket": "spring-websocket",
        "databaseType": "sql",
       "devDatabaseType": "h2Memory",
       "prodDatabaseType": "postgresql",
       "searchEngine": "elasticsearch",
       "messageBroker": false,
       "serviceDiscoveryType": false,
       "buildTool": "gradle",
       "enableSocialSignIn": true,
       "jwtSecretKey": "eb42dd54269cd595d79facdcd2e05eadec685246",
       "clientFramework": "angular1",
       "useSass": true,
       "clientPackageManager": "yarn",
       "applicationType": "monolith",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
       "otherModules": [
        {
          "name": "generator-jhipster-entity-audit",
          "version": "2.4.1"
        },
        {
          "name": "generator-jhipster-entity-audit-and-delete",
          "version": "2.2.2"
        },
        {
          "name": "generator-jhipster-vuejs",
           "version": "0.0.3"
        }
      ],
      "enableTranslation": false
       }
    }

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 4.5.0

bower: 1.8.0

gulp:
[19:04:13] CLI version 1.3.0

yeoman: 2.0.0

yarn: 0.23.4

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.8.0, build unknown

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Address.json

    {
        "fluentMethods": true,
        "relationships": [
          {
              "relationshipType": "many-to-one",
              "relationshipName": "customer",
              "otherEntityName": "customer",
              "otherEntityField": "id"
          }
       ],
       "fields": [
          {
              "fieldName": "address1",
              "fieldType": "String"
          },
          {
              "fieldName": "address2",
              "fieldType": "String"
          },
          {
              "fieldName": "city",
              "fieldType": "String"
          },
          {
              "fieldName": "postcode",
              "fieldType": "String",
              "fieldValidateRules": [
                "required",
                "maxlength"
              ],
              "fieldValidateRulesMaxlength": 10
          },
          {
              "fieldName": "country",
              "fieldType": "String",
              "fieldValidateRules": [
                  "required",
                  "maxlength"
              ],
              "fieldValidateRulesMaxlength": 2
          }
      ],
      "changelogDate": "20170621174058",
      "entityTableName": "address",
      "dto": "no",
      "pagination": "pager",
      "service": "no"
    }

Category.json

    {
      "fluentMethods": true,
      "relationships": [
          {
              "relationshipType": "many-to-one",
              "relationshipName": "parent",
              "otherEntityName": "category",
              "otherEntityField": "id"
          },
          {
              "relationshipType": "many-to-many",
              "otherEntityRelationshipName": "category",
              "relationshipName": "product",
              "otherEntityName": "product",
              "otherEntityField": "title",
              "ownerSide": true
          }
      ],
      "fields": [
          {
              "fieldName": "linky",
              "fieldType": "String",
              "fieldValidateRules": [
                  "required"
              ]
          },
          {
              "fieldName": "description",
              "fieldType": "String",
              "fieldValidateRules": [
                  "required"
              ]
          },
          {
              "fieldName": "sortOrder",
              "fieldType": "Integer"
          }, 
          {
              "fieldName": "dateAdded",
              "fieldType": "LocalDate"
          },
          {
              "fieldName": "dateModified",
              "fieldType": "LocalDate"
          },
          {
              "fieldName": "status",
              "fieldType": "CategoryStatus",
              "fieldValues": "AVAILABLE,RESTRICTED,DISABLED"
          }
      ],
      "changelogDate": "20170621174055",
      "entityTableName": "category",
      "dto": "no",
      "pagination": "pagination",
      "service": "serviceClass"
    }

Customer.json

    {
      "fluentMethods": true,
      "relationships": [
          {
              "relationshipType": "one-to-many",
              "relationshipName": "address",
              "otherEntityName": "address",
              "otherEntityRelationshipName": "customer"
          },
          {
              "relationshipType": "one-to-many",
              "relationshipName": "whislist",
              "otherEntityName": "wishlist",
              "otherEntityRelationshipName": "customer"
          }
      ],
      "fields": [
          {
              "fieldName": "firstName",
              "fieldType": "String"
          },
          {
              "fieldName": "lastName",
              "fieldType": "String"
          },
          {
              "fieldName": "email",
              "fieldType": "String"
          },
          {
              "fieldName": "telephone",
              "fieldType": "String"
          }
      ],
      "changelogDate": "20170621174057",
      "entityTableName": "customer",
      "dto": "no",
      "pagination": "pagination",
      "service": "no"
    }

Product.json

    {
      "fluentMethods": true,
      "relationships": [
          {
              "relationshipType": "many-to-many",
              "relationshipName": "category",
              "otherEntityName": "category",
              "ownerSide": false,
              "otherEntityRelationshipName": "product"
          },
          {
              "relationshipName": "wishlist",
              "otherEntityName": "wishlist",
              "relationshipType": "many-to-one",
              "otherEntityField": "id"
          }
      ],
      "fields": [
          {
              "fieldName": "title",
              "fieldType": "String",
              "fieldValidateRules": [
                  "required"
              ]
          },
          {
              "fieldName": "keywords",
              "fieldType": "String"
          },
          {
              "fieldName": "description",
              "fieldType": "String"
          },
          {
              "fieldName": "rating",
              "fieldType": "Integer"
          },
          {
              "fieldName": "dateAdded",
              "fieldType": "LocalDate"
          },
          {
              "fieldName": "dateModified",
              "fieldType": "LocalDate"
          }
      ],
      "changelogDate": "20170621174056",
      "entityTableName": "product",
      "dto": "no",
      "pagination": "infinite-scroll",
      "service": "no"
    }

Wishlist.json

    {
      "fluentMethods": true,
      "relationships": [
          {
              "relationshipType": "one-to-many",
              "relationshipName": "product",
              "otherEntityName": "product",
              "otherEntityRelationshipName": "wishlist"
           },
          {
              "relationshipType": "many-to-one",
              "relationshipName": "customer",
              "otherEntityName": "customer",
              "otherEntityField": "id"
          }
      ],
      "fields": [
          {
              "fieldName": "title",
              "fieldType": "String",
              "fieldValidateRules": [
                  "required"
              ]
          },
          {
              "fieldName": "restricted",
              "fieldType": "Boolean"
          }
      ],
      "changelogDate": "20170621174059",
      "entityTableName": "wishlist",
      "dto": "no",
      "pagination": "no",
      "service": "no"
    }

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry, I read your ticket three times but I don't understand your issue.... The JDL you refer to was coded by me, I'm pretty sure it works, I'm testing it.
And please follow the guidelines: I don't have your `.yo-rc.json` file, so I have no idea what your configuration is... You might have something specific with it.

**Comment by jdubois** [comment]
I regenerated a whole app and used the JDL you said caused the issue, I had no problem at all.

Next time, please send your full configuration!!!!!!

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by vw98075** [comment]
Hi, 

I have tried three times and get the same type of errors. I don't know whether it is due to vue or not.

Here is the file you are asking for:



  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.abc.myapp"
    },
    "jhipsterVersion": "4.5.5",
    "baseName": "jhipster",
    "packageName": "com.abc.myapp",
    "packageFolder": "com/abc/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "97cf9787e82949580e1c682e7f52a00dbaf3addb",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-entity-audit",
        "version": "2.4.1"
      },
      {
        "name": "generator-jhipster-entity-audit-and-delete",
        "version": "2.2.2"
      },
      {
        "name": "generator-jhipster-vuejs",
        "version": "0.0.3"
      }
    ],
    "enableTranslation": false
  }
}

**Comment by jdubois** [comment]
I'm sorry but I need your entity configurations to test. Please read the
guidelines ! You just need to run 'jhipster info'.

**Comment by vw98075** [comment]
I updated the original report with the additional information you asked. Please let me know if you need more.

**Comment by vw98075** [comment]
Please advise what is wrong on my part. Why my result is different from yours? Marking it as invalid doesn't let the problem going away for me.

**Comment by jdubois** [comment]
I put it "invalid" before you updated the ticket... I already spent quite a lot of time on your issue.

**Comment by vw98075** [comment]
Thanks very much for your help. Please let me know if you need other things else to resolve this issue.

**Comment by ruddell** [comment]
JHipster currently only supports bidirectional relationships for `@OneToMany`.  Previous (and recent) discussion here https://github.com/jhipster/generator-jhipster/issues/1569

**Comment by vw98075** [comment]
Thanks very much for the info. I just want to post a follow-up which the latest 4.5.6 exhibits the same behaviour in a simple class model. That really is a big problem for any modeling other than some small toy ones. I have two or three duplicatations of two attributes in the same entity class. The model contains about 30 entity classes.

Just for my curiousity, it seems the problem could be prevented somehow based on jdubois'  words. If so, how?

**Comment by deepu105** [comment]
@vw98075 we do not support unidirectional one to many and hence the behavior is intentional. Did you read the discussion posted by @ruddell above?

**Comment by vw98075** [comment]
So, I need to remove some code on the "many" side. I use Gradle. How to change the DB schema?

**Comment by vw98075** [comment]
There are quite a few unidirectional one to many relationships in our model. Changing them to bidirectional one to many don't make any business sense. For example, a coupon can be applied to many product categories and a category doesn't need to know which coupon it is applied. If we have to change it to a bidirectional relationship, that would be a many-to-many. That would make the code unnecessary complex. Please advice the best working around solution.

**Comment by deepu105** [comment]
I advise you read what was suggested in #1569, Vlad Mihalcea is from the Hibernate team, so I would assume he knows about relationships better than any of us. You can still remove the unwanted mapping in the entity files if you need but we are not gonna support this by default anytime soon.

**Comment by ruddell** [comment]
To use Gradle with Liquibase:
>If you use Gradle instead of Maven, you can use the same workflow by running `./gradlew liquibaseDiffChangelog`, and change the database configuration in `liquibase.gradle` if required.
https://jhipster.github.io/development/#using-a-database
