### ISSUE TITLE
jhipster-registry beyond 2.5.8 not working on k8s

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#5975]
##### **Overview of the issue**

After several updates to JHipster registry and the kubernetes sub-generator, the recent versions of the registry don't work properly. I had the first contact with that issue with version 2.6.0 and mentioned it in #5603. The cluster setup fails, and services effectively are registering to 2 distinct registries.

##### **Motivation for or Use Case**

I want to use the cool brand new registry in kubernetes, too!

##### **Reproduce the error**

Just generate microservices and a corresponding kubernetes setup and run it against a recent version of kubernetes (1.6.4 in my case). The "replicas" page will every time show an empty array and listing localhost, while reloading of applications will show 2 different zones.

##### **Suggest a Fix**

I already have an (upcoming) fix for that in #5927, which has a working configuration, tested on a self-hosted CoreOS kubernetes cluster.

The first is that self-registering Eureka to itself when clustering, is a bad idea. It was wrong configured, until https://github.com/jhipster/generator-jhipster/commit/23d746696547ab9478bc8b5c0483959f1975b3ac. After the fix, the configuration was correct and the misbehavior started. The same commit provides a correction for `EUREKA_CLIENT_SERVICEURL_DEFAULTZONE` to `EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE`, which should be the correct convention for that attribute. As far as I can say, there still is that issue that the 'wrong' version of the variables works, while to correct does not. This is crucial for Eureka to connect in a cluster.

Another point is, that the current version of JHipster Registry doesn't preloads the `jhipster.registry.password` attribute from config server, while connection to the other nodes, so clustering fails, even with the correct variable. Passing JHIPSTER_REGISTRY_PASSWORD in env file solves that trivially.

##### **JHipster Version(s)**

current upstream and JHipster Registry 2.6.0 and later

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I already had numerous issues with those: are you going to do a PR for this? I'll test it as soon as it's ready, this is a part I know quite well so it shouldn't be too hard.

**Comment by xetys** [comment]
I could PR that outside of my WIP PR immediately. Is it ok if I PR this now, as of your code-freeze?

**Comment by jdubois** [comment]
If you PR that's never an issue anyway :-)
And this is on the registry, I just released v3.0.3 so it's already released, so really no issue at all

**Comment by xetys** [comment]
k, give me a minute :smile:

**Comment by jdubois** [comment]
Closing as the PR is merged
