### ISSUE TITLE
jhipster module generator for angular 2 exit with error 

### ISSUE THREAD

**Issue by gioma68** [jhipster/generator-jhipster#5978]
##### **Overview of the issue**

I'm tring to create a module for angular 2 JHI projects

##### **Motivation for or Use Case**

I put in the index.js of module generator some `jhipsterFunc` for inserting npm dependencies and to copy custom files. It work ok, but if I add a line to call the function **addAngularModule** to insert angular 2 module dependencies I get the error: 

> TypeError: jhipsterFunc.addAngularModule is not a function

##### **Reproduce the error**
the piece of index.js file where I get the error:
`        this.fileCopy('my/scss/', this.webappDir + '/content/cui-scss/');
		// OK: copy custom files
		jhipsterFunc.addNpmDependency('ngx-bootstrap','latest');
		// OK: add npm dependencies
		jhipsterFunc.addAngularModule('Tabs','','ngx-bootstrap','tabs',false,'ng2'); // <--- here FAIL with error`

##### **Suggest a Fix**

I've seen that in the actual generator-jhipster/generators/modules/index.js of modules generator, **addAngularModule is not exported**.

##### **JHipster Version(s)**
Latest

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I followed this [comments](https://github.com/jhipster/generator-jhipster/pull/5437#issuecomment-287646079) from @deepu105 and indeed, we didn't need the function to be exported!
In fact, you can use every functions!

Can you look at my code ?
- at the beginning of the [index.js](https://github.com/pascalgrimaud/generator-jhipster-primeng-charts/blob/master/generators/app/index.js#L7-L19)
- then, you can use the function without using jhipsterFunc:
    - [addNpmDependency](https://github.com/pascalgrimaud/generator-jhipster-primeng-charts/blob/master/generators/app/index.js#L108-L110)
    - [addAngularModule](https://github.com/pascalgrimaud/generator-jhipster-primeng-charts/blob/master/generators/app/index.js#L124)

I'm closing this, as there is no bug in the generator.
I need to update the [generator-jhipster-module](https://github.com/jhipster/generator-jhipster-module)

**Comment by deepu105** [comment]
Pascal could you also update the documentation on module page suggesting
how to use the methods

**Comment by pascalgrimaud** [comment]
Yes of course @deepu105, it is on my todolist (update docs and update generator-jhipster-module + new release)

**Comment by gioma68** [comment]
Thanks to all for your prompt support!!
