### ISSUE TITLE
ui-select component for select multiple

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#5980]
Hi!,

What do you think about having ui-select (https://angular-ui.github.io/ui-select/demo-multiple-selection.html, part of the AngularUI companion suite: https://angular-ui.github.io/) to select authorities in user-management dialog ?

For me the multiple select of browsers is not really nice to use, need to press control key to select several options... and then if we just click without pressing control key we lose all the current selection... It's quite hard to handle when we have more than 5 authorities.

It looks like this: https://ui-select-demo.herokuapp.com/#/user-management/user/edit
user and pass: admin/admin.

It's a free heroku account so you might wait a bit until the app starts.

I can make a PR for angular 1 and then check for a similar component for angular 4 and BS4 if this change makes sense for you

**Comment by jdubois** [comment]
- Don't forget our [Policy 2](https://jhipster.github.io/policies/) - the idea is that if it's very easy to add to JHipster, then we shouldn't package it
- For AngularJS 1.x, this is going to die, so we we only correct bugs there

**Comment by ctamisier** [comment]
Yes it's quite easy to integrate it. For me handling a big list of authorities with the default multiple select of browser is impossible (except on mobile that have checkboxes). So I was thinking to have this component right away after jhipster generation, but I can make a jhipster module.

**Comment by deepu105** [comment]
Yes, agree with @jdubois for angular 1 we won't add any new major functionality. For angular x this is trivial to add so I don't want to bloat the generator by default with this
