### ISSUE TITLE
Improve security of AccountResource and UserResource

### ISSUE THREAD

**Issue by sergio-otero** [jhipster/generator-jhipster#5981]
##### **Overview of the issue**

Improve security of some of the rest APIs exposed

##### **Motivation for or Use Case**

I think that the following changes would make things more secure:

- AccountResource.saveAccount & changePassword: protect it with current password. It's a best practice to avoid someone stealing the account if a user leaves the website open
- AccountResource.saveAccount: validate the new email to avoid mistakes from the user and in the future losing the ability to requestPasswordReset
- UserResource.getAllUsers and getUser: protect with admin role

If someone from the project thinks it makes sense, i could take a look at the generator and make a pull request with the changes (at least the first and the last, because validating the changed email seems a bit tricky to do without new field or something)

##### **JHipster Version(s)**

4.5.4

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
1) I'd prefer just Change Password to be secured but you could still just change the email and reset the password

2) The email is validated according to the spec by the frontend (input type=email) and backend (`@Email` over the field in User.java).  What other validation is possible?

3) For the reasoning of getAllUsers and getUser being open, see the discussion: https://groups.google.com/forum/#!topic/jhipster-dev/hyM6dEsjk_o

**Comment by gzsombor** [comment]
I always disable the email address changing "feature". I have never had time to implement proper validations - I mean, sending emails to the original email address, about the 'takeover'.
Unfortunately the UserResource.getAllUsers mixes to different functionalities - the listing users for the admin pages, and picking users for entity relations. This would need proper separations

**Comment by sergio-otero** [comment]
About the email validation process, I was talking about validating that you have access to the new email address like when you create the user. 

If the user writes the new email with a typo and doesn't realize, it could loose access if the password is regenerated. 

As I said, maybe this one is too complicated because it would need more fields or even tables in the database. 

Github do this by having a list of validated emails

**Comment by jdubois** [comment]
That's a tricky ticket:

1. & 2. we're trying to keep this simple, as people will usually modify everything according to their own business requirements. But your changes make sense, and aren't probably very complicated -> if you have time to do it, and if you feel like doing the PR, yes we could merge this. I only have 2 requirements: that those changes are "simple" (not 1,000 lines!), and that you implement the front-end code both with AngularJS 1.x and Angular 4

3. As pointed by @ruddell this is on purpose. I totally agree this can be seen as a security issue, and personally I often secure this part. Then we also need to generate something useful: if we don't do this, all relationships to the user will fail, unless people remove the security. Basically we are only copying the GitHub here, which looks "reasonable", but that's just a point of view. So I would keep it, as it's useful for people, and we haven't had any serious issue with that, but I don't have a strong argument here, I agree.

**Comment by jdubois** [comment]
I'm closing this as there have been no discussion for more than 1 week:

- For points 1 & 2, as long as you keep things simple, don't hesitate to do a PR
- For point 3, so we all agree it's not great, but this needs more thinking - let's wait and keep it that way for the moment
