### ISSUE TITLE
npm install generator-jhipster is error！！！

### ISSUE THREAD

**Issue by Demon-liao** [jhipster/generator-jhipster#5987]
How can i deal with it?

![image](https://user-images.githubusercontent.com/2654683/27522888-e9e32910-5a5b-11e7-8483-595b3323c638.png)

**Comment by pascalgrimaud** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
