### ISSUE TITLE
JHipster Unauthorized errors

### ISSUE THREAD

**Issue by magaton** [jhipster/generator-jhipster#599]
Hi, I am facing unexpected rest calls to /app/rest/account when user is not authenticated.

{"timestamp":1411476893948,"status":401,"error":"Unauthorized","message":"Access Denied","path":"/app/rest/account"}

This happens, when I am on any "public" page, unauthenticated, for example main.html or login.html.
I can see 401 errors in my developer console.
The problem is that this causes accumulating meaningless audit events in the db.

I'd expect audit event is created when user tries to access protected resource: for example metrics, but login and main html are public pages, hence I think this is a bug.

best,
Milan

**Comment by DavidMCook** [comment]
Hi guys, were you able to create a fix for this issue in a future release, or have any suggestions? I am running Angular 1.3 on jHipster 0.12.
```
GET http://localhost:8080/protected/authentication_check.gif 401 (Unauthorized) angular.js:9866 
(anonymous function)     angular.js:9667 
sendReq                    angular.js:9383 
$get.serverRequest        angular.js:13248 
processQueue               angular.js:13264 
(anonymous function)     angular.js:14466 
$get.Scope.$eval           angular.js:14282 
$get.Scope.$digest        hint.js:1468 
scopePrototype.$digest   angular.js:14571 
$get.Scope.$apply         hint.js:1478 
scopePrototype.$apply    angular.js:1455 
bootstrapApply           angular.js:4203 
invoke                     angular.js:1453 
doBootstrap              angular.js:1481 
angular.resumeBootstrap     hint.js:535 
maybeBootstrap
```

**Comment by jdubois** [comment]
@DavidMCook we don't check the /authentication_check.gif anymore, so that's corrected.
But we still do a check, and there is still a 401 error if you are not authorized: this is normal, there is no other way to know if you are authenticated or not.

**Comment by DavidMCook** [comment]
Hey Julien, I'm rather far into my project at this point and have stepped
away from the generated entities, so it actually would be rather difficult
for me to directly upgrade. Would you please share the new authorization
check code, or if easier could you point me to it in the project directory?

Thank you again for your help!

**Comment by jdubois** [comment]
You can compare on the sample project:

https://github.com/jhipster/jhipster-sample-app

Each version is tagged, so you can do a diff between your version and the latest version.

But there has been so many changes this might be difficult.
