### ISSUE TITLE
Missing liquibase Properties in DatabaseConfiguration.java

### ISSUE THREAD

**Issue by jmesa-sistel** [jhipster/generator-jhipster#5994]
Hi

jhipsterVersion: 4.5.4

I'm using MSSQL and I want to use autoIncrement fields so I have added 

```
liquibase:
    parameters:
      autoIncrement: true

```
in application-dev.yml  &  application-prod.yml but is not working, so to fix it I have had to add:

`liquibase.setChangeLogParameters(liquibaseProperties.getParameters());`

in DatabaseConfigurationclass
Now I can create the id fields with autoIncrement

Regards

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
