### ISSUE TITLE
Let's use lombok

### ISSUE THREAD

**Issue by bitsal** [jhipster/generator-jhipster#5997]
##### **Overview of the issue**

Use Lombok

##### **Motivation for or Use Case**

I'm using jHipster and lombok. The Lombok definitely saves time. I have to remove a lot of redundant code after jHipster generation in favour of lombok usage.

##### **JHipster Version(s)**
4.5.6

**Comment by jdubois** [comment]
Oh no, not again :-(

**Comment by bitsal** [comment]
@jdubois I guess you already discuss it... :)

**Comment by cbornet** [comment]
Indeed : https://github.com/jhipster/generator-jhipster/issues?utf8=%E2%9C%93&q=lombok%20

**Comment by jdubois** [comment]
Oh yes :-)
And at work I just had a team (from another company, so they didn't do like us) who just lost several hours because of it (yet again, that's my 4th failed project with Lombok !!).
So latest issue is that it doesn't work well with Jacoco so your Jenkins/Sonar build will fail.

**Comment by jdubois** [comment]
Currently I also heard if was failing with Jackson Afterburner. But the list goes on :-)

**Comment by bitsal** [comment]
hmm... I've read several issues` discussions
I've got your pain :)
I felt the same when configured lombok with Maven, but I finished it without any issues on Bamboo and Jenkins CI servers. It works like a song now.

But I agree that lombok can be a wrong solution in some cases (e.g. when you start specifying field names in annotations as a string).

**Comment by pascalgrimaud** [comment]
Why don't you try to do a module for that ?
- scan existing files, replace the code you don't want
- post hook on entity, replace all getter, setter, etc

A module for your need would be perfect, there are so many people who want Lombok but no one want try to do a module :(

After seeing tonight what can be done with module (db-helper and ff4j), I'm sure it's doable

**Comment by jdubois** [comment]
Oh yes. And if it works well, I would be happy to be proven wrong, and integrate this into JHipster.

**Comment by bitsal** [comment]
Yea, it is a good idea. Probably, I will try. Thanks, guys!

**Comment by gmarziou** [comment]
Just for the record, spring-cloud-netflix project has just removed Lombok in 1.4.0.M1

**Comment by ASaunin** [comment]
@gmarziou Do you know the reason for this removal? Unfortunately couldn't find any details in web

**Comment by gmarziou** [comment]
No, I suppose the discussion was not public.

**Comment by AzharMobeen** [comment]
Thanks for keep updating us.
