### ISSUE TITLE
Arrow key not work in ubunu

### ISSUE THREAD

**Issue by majidbha** [jhipster/generator-jhipster#6002]
Hi
My os is ubunu 16.0.4.
When create new application arrow keys not working.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
I'm pretty sure this is a duplicate, because you're not using Node LTS support -> follow the guidelines and find the duplicate ticket, and please link it here.
