### ISSUE TITLE
Use jhiPrefix to prefix JHipster tables

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6004]
##### **Overview of the issue**

As stated in the [documentation](https://jhipster.github.io/creating-an-app/#3) : 

> --jhi-prefix - Add prefix before services, components and state/route names (Default: jhi)

I think the `jhiPrefix` could also be used to change the name of the JHipster tables : 

* `jhi_user`
* `jhi_authority`
* `jhi_user_authority`
* `jhi_persistent_token`

These names are hard-coded in the [Liquibase initial schema](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml#L60) or in the entity [@Table annotation](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/domain/_User.java#L55). And this way, we would have : 

* `custom_user`
* `custom_authority`
* `custom_user_authority`
* `custom_persistent_token`

WDYT ?

##### **Motivation for or Use Case**

When having several microservices applications, you end up with a few different databases, and all have a `jhi_user` table. It would be better to have `reg_user`, `order_user`.... depending on the prefix.

##### **JHipster Version(s)**

4.5.6

**Comment by deepu105** [comment]
Makes sense. Im ok with it. Would you like to do it?

**Comment by gmarziou** [comment]
+1 but I would like to mention that your example with User table is not realistic because User entity exists only in gateways not in microservices apps.

**Comment by agoncal** [comment]
@deepu105 Why not, I could try to implement that... but after my summer holidays ;o) So leave it open, tag it as a new feature and assign it to me.

@gmarziou Maybe I wasn't clear: I have several gateways too (dozens of microservices and five gateways). So I have several `jhi_user` tables. When I develop I like to have only one single Postgres instances (with dozens of separate schemas of course). Having different names would help.

**Comment by gmarziou** [comment]
Understood but User is a special case in the generator code, if you do some search on it you get an idea that there could be some side effect.

**Comment by gmarziou** [comment]
I have worked on a similar project last year but this was not a problem for us because in dev we used h2 for gateways and this worked well because gateways have such a simple data model and nothing specific to a database engine.

**Comment by mabujaber** [comment]
I love this feature but there is alot of missing replacement for it, such as css classes and angular directive
