### ISSUE TITLE
Deploy to AWS problems

### ISSUE THREAD

**Issue by ndjordjevic** [jhipster/generator-jhipster#6019]
Hi,

Generated the app with a latest jhipster and tried to deploy it to AWS. I'm getting the following error:

> Executing jhipster:aws
> Installing AWS dependencies into your JHipster folder
> events.js:163
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: ERROR! Something went wrong while installing:
> warning Pattern ["uuid@^3.1.0"] is trying to unpack in the same destination "/Users/ndjordjevic/Library/Caches/Yarn/v1/npm-uuid-3.1.0-3dd3d3e790abc24d7b0d3a034ffababe28ebbc04" as pattern ["uuid@^3.0.0"]. This could result in a non deterministic behavior, skipping.
> error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/ndjordjevic/IdeaProjects/bus-ride-platform-backend/node_modules/generator-jhipster/node_modules/less'".
> 
>     at Environment.error (/Users/ndjordjevic/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:89:38)
>     at child.error (/Users/ndjordjevic/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:1596:18)
>     at AwsFactory.shelljs.exec (/Users/ndjordjevic/.config/yarn/global/node_modules/generator-jhipster/generators/aws/lib/aws.js:21:39)
>     at /Users/ndjordjevic/.config/yarn/global/node_modules/shelljs/src/exec.js:204:9
>     at ChildProcess.exithandler (child_process.js:212:5)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:194:7)
>     at maybeClose (internal/child_process.js:899:16)
>     at Socket.<anonymous> (internal/child_process.js:342:11)
>     at emitOne (events.js:96:13)

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by supercobra** [comment]
Same issue as @ndjordjevic. Tried on Linux and macOS.

**Comment by gmarziou** [comment]
@supercobra please open your own issue with all the required details
