### ISSUE TITLE
JHipster installation issues with Yarn and windows

### ISSUE THREAD

**Issue by sudheerj** [jhipster/generator-jhipster#6030]
I tried to install jhipster through Yarn local package manager. Jhipster command failed with unknown characters. As an alternative I can use npm package manager for now.

C:\myapplication>"$basedir/../../Users/name/AppData/Local/Yarn/config/global/node_modules/.bin/jhipster.cmd"   "$@"
ERROR! $@ is not a known command. See 'jhipster --help'.

Thanks,

**Comment by jdubois** [comment]
This depends on your OS, etc...

**Comment by deepu105** [comment]
@sudheerj please give info asked in the issue template or open new ticket with all data.
Also please explain what steps you did
Seems you are on windows and I'm interested to see why the JHipster cli failed for you

**Comment by sudheerj** [comment]
@jdubois  
Julien, Sorry for the wrong format of github issue. Actually I was in hurry. I'am from PrimeFaces/PrimeNG open source team. We are the partners of PrimeFaces just like Ippon Technologies. Great to know about jhipster. I'am trying to do some research and planning to create a PrimeNG plugin for jHipster. Recently I saw PrimeNG charts module too.

@deepu105 Thanks for the response. Greetings to Chennai :) I'am providing the below information. If required, I can provide more information too.

**Overview of the issue** -
I'am facing an issue with jhipster installation. As per jhipster installation guide I tried with Yarn local package manager. But Jhipster command failed with an unknown characters. As an alternative I used npm package manager.

```
C:\myapplication>jhipster
C:\myapplication>"$basedir/../../Users/name/AppData/Local/Yarn/config/global/node_modules/.bin/jhipster.cmd" "$@"
ERROR! $@ is not a known command. See 'jhipster --help'.
```

**`Motivation for or Use Case `-**  
The motivation is to create Angular application based on jhipster. But the installation failed with windows and yarn combination .

**Reproduce the error -** 
Local installation with Yarn (https://jhipster.github.io/installation/)
OS: Windows
**Related issues** - 
This is a first time setup issue.
**Suggest a Fix** - 
The issue is caused by special characters in generated jhipster.cmd file.
**JHipster Version(s) -** 
Latest stable version

**Browsers and Operating System -**
This is not a browser related issue

Thanks,
Sudheer

**Comment by deepu105** [comment]
Seems like in windows it passes some unknown characters to CLI. Can you try the below steps and let me know? 
1. run `jhipster --debug`
2. run `yo jhipster` You need to install Yo first if you haven't already
3. If you are on Windows 10, try to run it from bash or Git bash

I'll try to reproduce in my windows machine when I find time, but may take a while

**Comment by gmarziou** [comment]
@deepu105 Are you sure that jhipster.cmd could run from git bash? 

@sudheerj `$@` is just variable name for command arguments, which kind of shell window did you use to execute jhipster? Which version of Yarn?

**Comment by deepu105** [comment]
@gmarziou I'm not sure. I havent tried that.

**Comment by sudheerj** [comment]
@deepu105 Due to an issue with Yarn installation, I tried with npm and it works good. So I can't see any debugging information using jhipster --debug. I'am using windows7 with CMD.

@gmarziou Yes, it is part of cmd code snippets.I'am using windows cmd with latest yarn version(using yarn upgrade). The command yarn global bin prints the nodejs location as below

c:\program files\nodejs

BTW, I didn't face any issue with my MAC machine.Thanks.

**Comment by deepu105** [comment]
I'm really not sure what to do here @gmarziou any idea?

**Comment by deepu105** [comment]
May be we should advice people to use npm on windows, as yarn has some quirks in windows anyways.
@jdubois WDYT?

**Comment by gmarziou** [comment]
> The command yarn global bin prints the nodejs location as below
> c:\program files\nodejs

Well I was expecting it to match "$basedir/../../Users/name/AppData/Local/Yarn/config/global/node_modules/.bin/"
Also installing nodejs under c:\program files can bring some issues as it requires to be administrator.
Maybe there's something wrong in your PATH.

If you search yarn project about global binaries, you'll find many issues on WIndows mainly, so recommending npm on Windows is probably a good thing though I haven't tried npm 5 yet.

**Comment by jdubois** [comment]
As I don't have Windows, I have no opinions here, and I can't test anything.... What's sure is that we have many people using JHipster on Windows, so I'm pretty sure it works!
We really need all your information: for example, which NodeJS version you are using, etc... I'm sorry but without all those informations, I still keeping this closed

**Comment by arthurvernon** [comment]
I have hit a very similar problem with jhipster/yarn on Windows. Very easy to reproduce...
On a Windows 10 box, follow the recommended installation instructions for Jhipster using Yarn.
Do a git init, commit code and then try and run jhipster upgrade --force.
There is nothing to upgrade with a fresh installation, but this fails...

Error: ERROR! Something went wrong while generating project! '$' is not recognized as an internal or external command, operable program or batch file.
in ...\npm\node_modules\generator-jhipster\generators\upgrade\index.js, line 82
generatorCommand = this.clientPackageManager === 'yarn' ? '$(yarn bin)/jhipster' : '$(npm bin)/jhipster';

produces $(yarn bin)/jhipster which is where the upgrade process fails.

Recommend that windows users are advised not to use yarn @ https://jhipster.github.io/installation/

**Comment by gmarziou** [comment]
Thanks @arthurvernon  but this has been reported as #6161 and has been fixed, ti will part of next patch release and bug affected both npm and yarn.
