### ISSUE TITLE
Hipster upgrade not working

### ISSUE THREAD

**Issue by Drishika** [jhipster/generator-jhipster#6031]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) with the JHipster tag.
- For bug reports its mandatory to paste the result of command `jhipster info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**

I am trying to upgrade jhipster version to 4.4.1. I checked out code that is already on 4.4.1 and ran upgrade command on my machine that is on 4.0.4 to upgrade it to 4.4.1.

However it is failing with the following error.

I used the command as described on the page "jhipster upgrade --target-version=4.4.1".

However it fails after generating the branch and code giving the following error.

To install your dependencies manually, run: yarn install

Running post run module hooks

Server application generated successfully.

Run your Spring Boot application:
./gradlew

Client application generated successfully.

Start your Webpack development server with:
yarn start

Running post run module hooks

Error jhipster --with-entities --force --skip-install

You don’t seem to have a generator with the name “jhipster-elasticsearch-reindexer:app” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-jhipster-elasticsearch-reindexer:app.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.

at Environment.error (/Users/Buni/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:89:38)
at constructor.error (/Users/Buni/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:1596:18)
at shelljs.exec (/Users/Buni/.config/yarn/global/node_modules/generator-jhipster/generators/upgrade/index.js:84:23)
at /Users/Buni/.config/yarn/global/node_modules/shelljs/src/exec.js:204:9
at ChildProcess.exithandler (child_process.js:218:5)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:885:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

##### **Motivation for or Use Case**

I was able to upgrade earlier but now get the error above. I did nom install for the elastic search reindeer but that did not help.

##### **Reproduce the error**

Please run the following command

jhipster upgrade --target-version=4.4.1

##### **JHipster Version(s)**

i am on 4.0.4 trying to upgrade to 4.4.1

##### **JHipster configuration**
 .yo-rc file

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.drishika.gradzcircle",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.4.1",
    "baseName": "gradzcircle",
    "packageName": "com.drishika.gradzcircle",
    "packageFolder": "com/drishika/gradzcircle",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "5482eb4f18bb056e37ed636bcf6cd42cf7b31266",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi"
    ]
  }
}

##### **Browsers and Operating System**

I am on MacOs Sierra

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Duplicate from #6023
