### ISSUE TITLE
Social Login not works

### ISSUE THREAD

**Issue by uyeliksiz** [jhipster/generator-jhipster#6037]
##### **Overview of the issue**

when tring social login, it throws and exception:

> java.lang.IllegalStateException: The OAuth2 'state' parameter is missing or doesn't match.
> 	at org.springframework.social.connect.web.ConnectSupport.verifyStateParameter(ConnectSupport.java:173)
> 	at org.springframework.social.connect.web.ConnectSupport.completeConnection(ConnectSupport.java:155)
> 

##### **Motivation for or Use Case**

It is not working..

##### **Reproduce the error**

i inserted client-id and secrets in application.yml. When i click any provider button, it prints error after returning from provider. Because not found stored state in session.

##### **JHipster Version(s)**

4.5.2

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
Also, please write a good title next time
