### ISSUE TITLE
how to save multiple records in one entity

### ISSUE THREAD

**Issue by tanugarg2006** [jhipster/generator-jhipster#6039]
I need to save multiple records in loop. In dialog.js i m getting my correct object which i m sending to service js to save. calling service js in loop only. while i m running this service js save function is called after dailog js loop. how is this happening?? How can i save data in loop?? Please suggest. \

This is my Dialog-controller.js

     function save () {
    vm.isSaving = true;

for(var i in resourceData)
{

         vm.timesheet.sunday=resourceData[i].sunday;
         vm.timesheet.monday=resourceData[i].monday;
         vm.timesheet.tuesday=resourceData[i].tuesday;
         vm.timesheet.wednesday=resourceData[i].wednesday;
         vm.timesheet.thursday=resourceData[i].thursday;
         vm.timesheet.friday=resourceData[i].friday;
         vm.timesheet.saturday=resourceData[i].saturday;
         vm.timesheet.resource=resourceData[i].saturday;
         vm.timesheet.resource=resourceData[i];

        Timesheet.save(vm.timesheet,onSaveSuccess, onSaveError);

 }

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
