### ISSUE TITLE
Unable to create entity with name ending in "detail"

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#6047]
##### **Overview of the issue**

I have an entity called **Entry** which has a **oneToMany** relationship to **EntryDetail**. When trying to generate the _EntryDetail_ entity, it fails complaining that the entity cannot end with _detail_ but I see (in the error log) no reason why this should a normal behavior.

##### **Motivation for or Use Case**

After searching I found the constraint here:

https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L199

but I don't understand why is that as there are no comments on that part of the file.

##### **Reproduce the error**

Generate an entity ending with _Detail_

##### **Related issues**

None

##### **Suggest a Fix**

Either show a more logical reason for such behavior when generating the entity or comment the linked file.

##### **JHipster Version(s)**

Lastest.

##### **JHipster configuration**

Not needed

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entity was generated

##### **Browsers and Operating System**

Unrelated

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
FYI, the related issue https://github.com/jhipster/generator-jhipster/issues/1414

**Comment by amatosg** [comment]
thank you @pascalgrimaud! I wonder if I should use _Details_ instead of just _Detail_...

**Comment by pascalgrimaud** [comment]
I let the ticket opened because the related issue was fixed 2 years ago, and I just wonder if we need to keep this restriction, specially with Angular4

**Comment by deepu105** [comment]
@pascalgrimaud I think the restriction I still applicable to AngularJS 1.x and having another set of restriction forAngular alone is too much, but it could be the solution

**Comment by pascalgrimaud** [comment]
Not only for AngularJS but for Gateway too, using a microservice with `Detail`
I'd rather keep like that, as @amatosg knows the reason why it is forbidden

**Comment by deepu105** [comment]
ok so we are not gonna remove the restriction here for time being
