### ISSUE TITLE
Strip rememberMe, JWT secrets from `info` command output

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#6056]
When we output jhipster config using the info command we should strip the fields with sensitive content like `jwtSecret` and `rememberMe`. Of course it's not our responsibility to ensure that people don't post such stuff in public forums, but still, I think we can do it to avoid people accidentally doing that

@jdubois @pascalgrimaud

**Comment by pascalgrimaud** [comment]
it's a good idea @deepu105 
You can assign this ticket to me, I will try to do it

**Comment by deepu105** [comment]
cc @gmarziou

**Comment by PierreBesson** [comment]
It might also be useful to anonymize the baseName, packageName and folder. Although, I recognize it's fun to know which companies use JHipster and have bugs...

**Comment by pascalgrimaud** [comment]
yes it's fun @PierreBesson and baseName / packageName are not really sensitive information for me.
So if people don't want to tell which companies use JHipster, they need to be carefull when sharing their configuration

**Comment by gmarziou** [comment]
Usually we get the package name in stack traces too :)

**Comment by jdubois** [comment]
Yes it's already very good like this! Thanks for #6057 !
