### ISSUE TITLE
[Enhancement] make a master JHipster pom instead of 'hardcoding' dependencies and plugin management

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#6061]
##### **Overview of the issue**
The actual way for managing 'server' dependencies on pom.xml is to declare dependencies version and plugin behavior directly in the generated pom.xml

Instead of doing this, we could make that generated pom inherit from 'jhipster:jhipster-pom:${jhipster.version} instead of generating it.
##### **Motivation for or Use Case**

It will ease that pom maintenance (the _pom.xml template will be far easy, containing less code), as well as ease the pom upgrade (dependency or plugin management): client will just have to update their parent pom's ${jhipster.version} instead of backporting changes.

So that it will permit to tweak the pom more easily (like generating site, using more plugins, etc.
I've already made a good OSS pom on my previous [project](https://github.com/OsgiliathEnterprise/net.osgiliath.parent/tree/master/net.osgiliath.poms), may be I can make a PR?
It should be nice to make the same thing for Gradle project, as it would ease the maintenance of both frameworks, but I don't know anything about this build tool.

##### **Suggest a Fix**

Make a new jhipster project (jhipster-pom), adding dependencies and dependencymanagement on this pom. Then we should release these pom on maven central, then modifying the generator-jhipster/server/_pom.xml template to inherit from the newly created pom

##### **JHipster Version(s)**
4.6.x

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I think @erikkemperman was working on something like that?

**Comment by erikkemperman** [comment]
Yes, I was. But a lot of other stuff got in the way :-)

If someone else wants to try: the gradle dependency management plugin, from the spring guys, should make it possible for the gradle build to use the same versions as the maven build (it reads poms!)

**Comment by Tcharl** [comment]
So I'm on it ;-). Could a JHipster guy create a repo for the parent pom? For example jhipster-poms or jhipster-parent?

**Comment by jdubois** [comment]
We could put it in jhipster/jhipster as everyone already depends on it.
Then, I'm not sure people will be happy to be tied too much to JHipster.  I believe they like their generated pom, and modify it as they want.

**Comment by gzsombor** [comment]
Instead of creating a parent pom, it would be better if maven's import mechanism is used. So JHipster could be used in a multi-module maven project too.

**Comment by Tcharl** [comment]
@jdubois  with a parent pom, you just have dependency update for free (you do not have to tweak your pom dependencies, just increase the version of the parent.
on the other way, the <dependencies/> and <plugins/>  will stay on the generated part: user who want to tweak this just have to copy/paste the <dependencyManagement/> section of the parent (or just override the unwanted part). This could be explained on the docs (a section telling 'how to I do not depend to jhipster anymore'), but I think users are already tied to it (the jhi- prefix on the client side, the jhipster registry/uaa which are nice stuff, and that ugly guy on the front page).

@gzsombor  why should we use 'import'? This is just for dependencies, not plugin management, nor properties, nor reporting, scm, license,...

**Comment by gmarziou** [comment]
I also like importing a pom rather than having a parent pom, it's like what spring cloud does.

**Comment by erikkemperman** [comment]
For what it's worth, this was my original issue and it contains an image of how I thought it might work:
https://github.com/jhipster/generator-jhipster/issues/5551

**Comment by Tcharl** [comment]
I'm really sorry, but I do not understand the point.
When you use jhipster, you already depends on org.springframework.boot as parent. What's the difference if you depend on jhipster-parent?

**Comment by erikkemperman** [comment]
@Tcharl Speaking just for myself, I would like to attach my own parent to jhipster-generated projects... Does that make sense?

**Comment by jdubois** [comment]
The issue here is that we get some negative feedback from "some" users on non-generated code, so let me try to explain first why they feel like that:

- There's a French bank who is upset, because their legal department don't want to use non-validated third party libs -> that's stupid because with a JHipster app you already pull a huge number of third-party apps (Java and JavaScript!!!), and JHipster is probably one those causing the less trouble
- There are many "architects" in big companies that want "full control" on the code -> that's also stupid, it just shows they have no idea how Spring Boot works (or Maven, in this case)
- There are several big IT companies who like to invoice their clients for all that generated code: basically they run JHipster and invoice 2 weeks of work for doing the project setup -> I also don't care about them a lot

So that's why we did https://github.com/jhipster/jhipster anyway, but didn't go too far. Here you could use the same "rules" we followed:

- Everything you do should be easy to override -> that's why importing a pom is probably better than extending one (many companies already have their own parent pom, and there are very good reasons for that)
- Don't go too far, at least on a first release: it's fine if there are still lots of generated code, let's do this step by step and wait for people's feedback

And sorry if I sounded a bit negative: I love the idea, it's just that I'm afraid of other people's reaction on this.

**Comment by Tcharl** [comment]
@erikkemperman you can, as long as your parent pom has the jhipster one as parent ;-).

@jdubois 

- On the first bullet: it changes nothing, as the <dependencies/> and <plugins/> sections continues to belong to the child pom, only the versions does not. My company have these kind of rules, but they do not enforce versions (and I think that it's ok for more legals). At worth, the maven generated site shows the mvn dependendencies:graph.

- On the second: architects sucks, I'm one of them.

- Some contractors tried to do this for my company, bad luck that I was the reviewer...

- Maybe we can generate empty plugins sections with <configuration combine.self="merge"/> in order to let them override the behavior easily (I haven't tested this solution)?

- The 'all in the generated code' is good indeed, it let the user feel more in control with the code, so as you said, let not disturb them (@deepu105).

I'll try to make a nice on steroid pom to manage jhipster/jhipster, may be the registry and other jhipster team's managed modules if you see an added value to this. May be adding some comments for those who wants to migrate to this mecanisms (or maybe a generator option)?

Finally, @jdubois, the comments were not negative (a litlle bit more explanation on the cons would have been nice, but it's my fault: I should have read in depth the real good @erikkemperman study on the subject). Its just kind of hard to understand why depending on a Pivotal pom is better than depending on a vendor-free one ;-)

**Comment by erikkemperman** [comment]
@Tcharl Actually I suspect many corps will have an already made parent, not so easy to change the grandparent... I know my project is in that situation.

Maybe ask it the other way around; what would you like to achieve, in addition to dependency management, that would work with a parent but not with an import?

**Comment by Tcharl** [comment]
@erikkemperman we can do everything with a generated pom, all is about readability.

But generating the information section, reporting section, dependencies section, plugins section, profiles, Etc. in a single pom.xml leads to unreadable, scarying stuff very hard to maintain in time.

**Comment by erikkemperman** [comment]
@Tcharl Agreed, actually in my earlier proposal I have a separate parent to clean up the main one -- but within the generated structure, and without a grandparent.

**Comment by Tcharl** [comment]
Aaaaaah, understood.
Aren't the jhipster users scary about the amount of generated code? IMHO generating another project (even if it only contains a pom) will lead to have an even scarier fwk ;-)

**Comment by Tcharl** [comment]
I made a PR [here](https://github.com/jhipster/jhipster/pull/22) with a 'grand-parent' pom + a bom.

Feel free to review, integrate, comment...

**Comment by tientq** [comment]
I'm not prefer this. Because It's not clear for me about what is going on inside parent pom. What should I do when I want to use other version of `spring-cloud-stream`. What should I do If my company already have a parent pom.

**Comment by Tcharl** [comment]
@tientq 

- There's no plugin execution, nor implicit dependencies in the parent pom: everything is listed on the generated one (you've have no easter egg ;-)). 
- You've got a point here, but do you prefer backporting pom changes each time?
- The goal of jhipster is to ensure that the stack it provides runs well, so I would not advise you to do so ;-). You can always override the version of the dependency in your generated pom, nothing prevent against this :-p.
- Actual jhipster generation already use spring-boot pom as a parent, what does your company for this? I plan to provide a jhipster-generator option (to keep the pom things as they are generated actually or use that parent pom to have some bonus stuff).

Keep in mind that this PR offers: 
- A good way to release your artifacts, either within your company or in maven central, for example, in a CI/CD pipeline.
- Less pom maintenance for the end user during jhipster upgrades.
- Static project's description site generation (which your company could need ,-)). 
- Some accelerators for jhipster organisation members.
And I don't think that there is an other way to have this for free (but maybe @erikkemperman  has the answer ;-)).

What do you think about it?

**Comment by tientq** [comment]
Thank you for your answer. It's much clear for me now. In most case, I'm ok with that. In some specific case, I'll custom by myself.

**Comment by Tcharl** [comment]
Hi @tientq, you'll be glad to hear that I've implemented a solution that you'll be able to customize! @erikkemperman had a wonderful idea to bridge the best of all world's: the referenced or is all about that.

Best regards, and thank you all for the feedback

**Comment by jdubois** [comment]
As the PR is ready we should further discuss this, as this is definitely a major change.

- Having our own BOM will frighten some people. JHipster is becoming more and more a framework (I'm not against it, but this is a change that everybody might not agree with)
- OTOH, this will make version upgrades easier, like we do with the JHipster server lib

-> Overall I'm not totally convinced. As our current `pom.xml` is becoming huge and hard to maintain, I would vote for this, but I'd really like to have more feedback.

Other issues I have:

- If we go this way, we need to have Gradle use the same BOM -> I thought this wasn't possible? And that Spring Boot did some trick to have it work? That would be a stopper issue, as we can't have different builds with Maven and Gradle
- In the PR, you provide lots of other code, and no BOM. I understand you want the reporting to work (with `site.xml`), but can we do that afterwards, and first just do a refactoring of what we already have? I'd like to see the exact difference (currently the PR adds a lot of lines, which should not be the case)

**Comment by erikkemperman** [comment]
@jdubois My understanding is that this Gradle [plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin/) does exactly that (read a Maven POM and extract its dependencies, including parent, exclusion, and so on) and that is what makes Gradle work with Spring in the first place.

**Comment by jdubois** [comment]
To have more feedback, I just launched at Twitter poll at https://twitter.com/java_hipster/status/910063512390635521

**Comment by atomfrede** [comment]
@jdubois In the hangout with Stefan and Eric we talked about dependency management and the problem of staying in sync with the maven build and using a bom is currently the way to go. I hope I find some time soon to setup an initial jhipster-gradle plugin. But we should check how far we go in the end, as it will make it more like a framework (but of course every relevant detail can be overwritten by the user later).

**Comment by jdubois** [comment]
@atomfrede if you tell me it's the way to go, and discussed this with the Gradle team, so that's perfect for me!
Then of course, we need to have this working with Gradle before releasing anything, so this might cause some delay

**Comment by atomfrede** [comment]
I will try to check with a minimal project what the [gradle plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin/) provides us. Will the bom be published somewhere or read from local file within the generated project? Maybe lets put @oehme here for some feedback.

**Comment by jdubois** [comment]
For publishing the bom: I could create a https://github.com/jhipster/jhipster-parent project, and release it like I already release  https://github.com/jhipster/jhipster - doesn't look like a big issue to me.
@Tcharl @atomfrede do you want me to create that repo now, so you can start working on this?

**Comment by oehme** [comment]
Publishing the BOM sounds like the right idea. The Spring DM plugin supports resolving BOMs until we support them natively in Gradle.

**Comment by erikkemperman** [comment]
@atomfrede @jdubois For what it's worth, I think it has to be published or installed locally (~/.m2) for the gradle plugin to find it. If published I would propose `jhipster-dependencies` instead of `-parent` for the BOM, exactly like the spring-boot modules. Does that make sense?

**Comment by jdubois** [comment]
- Thanks @oehme -> great to know that Gradle will help us (then this needs to be coded, of course!)
- OK @erikkemperman -> let's use https://github.com/jhipster/jhipster-dependencies

**Comment by Tcharl** [comment]
Hi All, glad to have started a nice discussion :-).

@jdubois , I already did the bom project, jhipster community just have to fork it: https://github.com/Tcharl/jhipster-parent (I can merge the two poms in one).

Also, my initial idea was to bring some maven on steroid capabilities to the build: reporting, javadoc, release, ... bom was just a plus to ease migration between jhipster release.
I didn't know that the bom was usable within gradle, so IMO it was a nice idea !

This PR is usable even without the bom (with some adaptation), in order to bring reporting/site/stuff, so as the community wish ;-).

**Comment by jdubois** [comment]
- Working & thinking on this: yes I agree having a bom is the way to go
- The Gradle team says the same, as well as our Twitter poll: https://twitter.com/java_hipster/status/910063512390635521 (72% voted for it)
- This is why I put it in our next release's roadmap, see https://groups.google.com/d/msg/jhipster-dev/CfBEt5wC_yI/WMJr4XLOBwAJ

As a result:
- There is still work to have this working clean, and with Gradle
- I would also like to review everything
- please let's remove the "steroid capabilities", let's have a simple PR, and then improve it - as you can see on the roadmap above, we are drowning in big PRs, that's really hard for us as we mostly work in the evenings and week-ends
- I just created the https://github.com/jhipster/jhipster-dependencies repository, as discussed. The whole "core team" as access to it, and @Tcharl you can of course do a PR (and if that's too annoying I'll give write access, that's really no big deal)

**Comment by Tcharl** [comment]
Hi @jdubois will do it, kinda bad for the steroid stuff, it wasn't that complicated (no template, only standard maven mojo config) and helped my company. I thought it would help @erikkemperman too.

Np to do it in some steps (I think I'll make another PR, to keep steroids available when possible), will work on it this wk end.

Regards

**Comment by PierreBesson** [comment]
@tcharl I think we would be interested to have easy maven releases, eventually automated through Travis. Deploying to central is complex and takes valuable time for @jdubois. We would gladly accept your advice here.

**Comment by jdubois** [comment]
@PierreBesson I will publish my "release documentation" when I have the time to write it cleanly

**Comment by Tcharl** [comment]
My "steroid" features embed configuration that ease that process:
You only have to get a local gpg, then use mvn release:prepare release:perform to perform checks, tag scm and release on sonatype staging. I don't know if it's doable on travis, as you must prove that you're the owner of the repo (so having a local gpg key) to publish on central.
The jhipster-dependencies and the generator generated project will get this feature OFTB.

**Comment by PierreBesson** [comment]
@Tcharl I You can put secrets in Travis ENV vars and this specific use case seems doable (see for example: https://dracoblue.net/dev/uploading-snapshots-and-releases-to-maven-central-with-travis/).

**Comment by jdubois** [comment]
So @Tcharl transfered his repository to me -> now we have https://github.com/jhipster/jhipster-dependencies which will be our BOM repo!
The whole core team as well as @Tcharl have write access to this repo, use this wisely!

**Comment by erikkemperman** [comment]
So the plan is for that repo to be just a POM file, basically, with only version properties and dependencyManagement?

Because at the moment it looks like it might be intended to be used as parent... Which, but maybe that's just me, was not the idea of this module?

**Comment by erikkemperman** [comment]
Sorry perhaps I'm just looking at this too soon and work is still being done on it :-)

**Comment by jdubois** [comment]
No for me it's just going to be a BOM, not a parent pom.

**Comment by erikkemperman** [comment]
Well, at the moment its artifactId is `jhipster-parent` and it has things like pluginManagement and profiles which only work from parents...

But like I said, probably I was too quick to look and this is just an intermediate state of affairs.

**Comment by Tcharl** [comment]
This project is split in two parts:
- A jhipster-parent pom (good catch erik) which is intended to ease the release of any jhipster organization project (for example, the bom). I can put all the code inside in the dependencies one, but this part would then be intended to be replicated in all jhipster products. Basically, it configures the maven release plugin to be able to perform a simple 'mvn release:prepare release:perform -Pprod' (within travis with a little bit of work) to release an artifact to maven central. It also configures apache rats to ensure the APLv2 compliancy of any jhipster (organization) project. Note that this pom can be sanitized.
- A jhipster-dependency module, which is the effective bom containing up to date jhipster-generator maven dependencies versions

**Comment by erikkemperman** [comment]
@Tcharl Oh, I see. So this parent would not "reach" the generator POM, since the BOM would simply be a dependencies import. All right! I guess the server-lib would also use this parent? Not too much replication then, just (eventually) some of the "steroid" stuff within the user's (generated) POM(s).

**Comment by Tcharl** [comment]
Right, the parent won't 'reach' the generated code, so users won't be impacted.

But core projects (jhipster-generator, registry, etc.) can inherit from it to benefit from these features  (i.e. releasing on central with a single command). We'll then be able to add many more 'steroid' capacities to this pom (reporting, javadoc generation, technical site generation containing all the sanity reports, changelog, ...), so that every 'jhipster core' project will all benefit from new 'steroid' capacities  (if wished).

My PR on client generator already contains that similar 'steroid' capabilities (@jdubois my PR without it will arrive soon) but within the generated code itself, so without depending on any jhipster maven stuff but the bom as dependency (the parent poms are generated by the template).
So that the users can modify the behavior if wanted, or keep the default, as it does not impact their actual development and just bring them free lunch.

**Comment by erikkemperman** [comment]
I would just suggest maybe keep the jhipster-dependencies POM clean, with just version properties and dependencyManagement, and put the other stuff in a separate jhipster-parent module?

**Comment by jdubois** [comment]
Quite a long discussion!!! Yes @Tcharl I think we all agree!  For me the BOM is more important than the parent POM (which is mostly for me, and that's easy to do manually today)

**Comment by jdubois** [comment]
Closing as #6509 is merged
