### ISSUE TITLE
The gradle build on windows is broken

### ISSUE THREAD

**Issue by carloca68** [jhipster/generator-jhipster#6064]
##### **Overview of the issue**

Generating a new application on windows 10 targeting gradle is not working.

##### **Motivation for or Use Case**

1 - You are not able to run the app because spring boot apparently can't find the app class:

> Task :bootRun
Error: Could not find or load main class com.... (class name removed, it's correct)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.

2 - If you run the app using yarn it works but you don't get the "Develop" red banner.

##### **Reproduce the error**

Just generate the app on windows 10, jdk 1.8 and gradle, you'll get this errors, I did it multiple times.
Copy .yo-rc.json to a new folder, replace gradle for maven, run the jhipster generator and it works just fine.

##### **Related issues**

None until now.

##### **Suggest a Fix**

I'm checking the gradle 4 build script but I've no clue yet.

##### **JHipster Version(s)**

4.6.0

[gradle.out.txt](https://github.com/jhipster/generator-jhipster/files/1133568/gradle.out.txt)

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "xxxxxxxx",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.0",
    "baseName": "Linkcrm",
    "packageName": "xxxxxxx",
    "packageFolder": "xxxxxxx",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "6ccb10503756a4797bd37579de3b50657ac800b8",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "pt-br",
      "es"
    ]
  }
}

##### **Browsers and Operating System**

Firefox
Windows 10 Home
Jdk 1.8

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Unfortunately I don't have Windows 10 to test... I don't think anyone in the team has one.... Can anybody confirm the issue?
@carloca68 did you already use JHipster in a prior version, was it working with Gradle 3? We just did the upgrade to Gradle 4, so that could be the issue

**Comment by carloca68** [comment]
Hi Julien, thanks for the quick response, I've never had this kind of issues before using exactly the same environment. I was working fine out of the box in the prior versions.

**Comment by jdubois** [comment]
That's really annoying that we can't test on Windows - I should hopefully have a solution in a couple of months (no promises!!), but in the meantime we can only hope to have help from the community.

**Comment by atomfrede** [comment]
I will try to check via a VM. @carloca68 anything special about the gateway setup or all default except language selection?

**Comment by carloca68** [comment]
Hi Frederik, I guess it makes no difference since the error is basically related on how the gradle plugin build the classpath, just a guess, but it is what make some sense to me. It may be some small mistake on how the folder and paths are created, I'll do a look on it as soon as I've some free time.

**Comment by atomfrede** [comment]
Yes seems so. Will check before on my Linux machine. But when I migrated to gradle 4 gateway worked fine. Maybe some later commits broke it but need to take a look.

**Comment by gmarziou** [comment]
As I don't know anything abut gradle, I tested obvious things on W10
- update to gradle 4.0.1
- update to spring boot 1.5.5-SNAPSHOT
All failed same way.

**Comment by gmarziou** [comment]
I generated a grade project from https://start.spring.io/, changed gradle version to 4.0 and project runs fine.
So it seems to be specific to jhipster.

**Comment by atomfrede** [comment]
I will check later if we have a general problem here.

**Comment by kaidohallik** [comment]
I have the same issue in Windows 7. Sharing my finding. If I run `gradlew -d` then I can see that bootRun is running java with classpath containing `...build\classes\main` but if I look at build folder then I can see that correct path is `...build\classes\java\main`.

**Comment by kaidohallik** [comment]
If I changed in my `build.gradle` this line:
```
            classpath = files("$buildDir/classes/main", "$buildDir/resources/main", pathingJar.archivePath)
```
to this:
```
            classpath = files("$buildDir/classes/java/main", "$buildDir/resources/main", pathingJar.archivePath)
```
then my app started successfully.

**Comment by atomfrede** [comment]
That's strange. Should be also a problem on Linux but during my tests all apps started just fine. But yes gradle now has now separate output dirs for each JVM language. Will provide fix asap. Thanks @kaidohallik for the hint

**Comment by jdubois** [comment]
@atomfrede this is quite an important issue so I'll do a specific patch release for this

**Comment by atomfrede** [comment]
@jdubois I am on it. Now I see why no tests showed that problem (as i already mentioned, we are doing some things to make everything work in windows fine) and when building the classpath we are doing `if (OperatingSystem.current().isWindows()) {`. I'll try to check if that is still required with newer spring boot plugin or not ( i hope we can remove it)
