### ISSUE TITLE
[FEATURE] Support Indonesia language

### ISSUE THREAD

**Issue by mirzaakhena** [jhipster/generator-jhipster#6085]
##### **Overview of the issue**

Adding the Bahasa Indonesia language. So Indonesia developer/user can use this bahasa

##### **Motivation for or Use Case**

Because i'm and indonesian, i use jhipster and i want to contribute to this project.

##### **Suggest a Fix**

I am adding bahasa indonesia in `languages` folder and `generator-base.js` file (getAllSupportedLanguageOptions)

##### **JHipster Version(s)**
v4.6.1

- [v] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
Please do a PR. 👍

**Comment by mirzaakhena** [comment]
i already fork the generator-jhipster then

modified:
- generators/generator-base.js
- test/test-languages.js

add two new files:
- generators/languages/templates/src/main/resources/i18n/_messages_id.properties
- generators/languages/templates/src/main/webapp/i18n/id/ 

do `yarn link` in the generator-jhipster project that i forked (has language feature in it) then
do `mkdir testlanguage` to testing the generator then `cd testlanguage` then
do `yarn link generator-jhipster` in the testlanguage project then
do `jhipster` then checklist some question adn option

but i dont see the indonesia language option in jhipster questions?
Am i missing some step here?

**Comment by deepu105** [comment]
please follow last section of https://jhipster.github.io/installing-new-languages/

**Comment by mirzaakhena** [comment]
Ok @deepu105 maybe tonight i'll try again. Thanks.

**Comment by jdubois** [comment]
Closing as the PR is merged
