### ISSUE TITLE
An Exception After Decreasing A Long Entity Name

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#6088]
##### **Overview of the issue**

During an importing entity definition file, I get the following message:

    The table name for this entity is too long to form constraint names. Please use a shorter table name ff_payment_transaction

And I have a shorter table name as ff_payment_transaction. After starting the app, I get the following exception, however. 

2017-07-11 14:38:07.067 ERROR 4527 --- [ader-Executor-1] liquibase                                : 
   classpath:config/liquibase/master.xml: 
 classpath:config/liquibase/changelog/20170711213548_added_entity_constraints_FulfillmentPaymentTr
    ansaction.xml::20170711213548-2::jhipster: Change Set classpath:config/liquibase/changelog/20170711213548_added_entity_constraints_FulfillmentPaymentTr
    ansaction.xml::20170711213548-2::jhipster failed.  Error: Table 
    "FULFILLMENT_PAYMENT_TRANSACTION" not found; SQL statement:
   ALTER TABLE PUBLIC.ff_payment_transaction ADD CONSTRAINT fk_fulfillment_payment_transaction_parent_transaction_id FOREIGN KEY (parent_transaction_id) REFERENCES PUBLIC.fulfillment_payment_transaction (id) [42102-195] [Failed SQL: ALTER TABLE PUBLIC.ff_payment_transaction ADD CONSTRAINT fk_fulfillment_payment_transaction_parent_transaction_id FOREIGN KEY (parent_transaction_id) REFERENCES PUBLIC.fulfillment_payment_transaction (id)]
    2017-07-11 14:38:07.074 ERROR 4527 --- [ader-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: Migration failed for change set classpath:config/liquibase/changelog/20170711213548_added_entity_constraints_FulfillmentPaymentTransaction.xml::20170711213548-2::jhipster:
     Reason: liquibase.exception.DatabaseException: Table "FULFILLMENT_PAYMENT_TRANSACTION" not found; SQL statement:
ALTER TABLE PUBLIC.ff_payment_transaction ADD CONSTRAINT fk_fulfillment_payment_transaction_parent_transaction_id FOREIGN KEY (parent_transaction_id) REFERENCES PUBLIC.fulfillment_payment_transaction (id) [42102-195] [Failed SQL: ALTER TABLE PUBLIC.ff_payment_transaction ADD CONSTRAINT fk_fulfillment_payment_transaction_parent_transaction_id FOREIGN KEY (parent_transaction_id) REFERENCES PUBLIC.fulfillment_payment_transaction (id)]

liquibase.exception.MigrationFailedException: Migration failed for change set classpath:config/liquibase/changelog/20170711213548_added_entity_constraints_FulfillmentPaymentTransaction.xml::20170711213548-2::jhipster:
     Reason: liquibase.exception.DatabaseException: Table "FULFILLMENT_PAYMENT_TRANSACTION" not found; SQL statement:
ALTER TABLE PUBLIC.ff_payment_transaction ADD CONSTRAINT fk_fulfillment_payment_transaction_parent_transaction_id FOREIGN KEY (parent_transaction_id) REFERENCES PUBLIC.fulfillment_payment_transaction (id) [42102-195] [Failed SQL: ALTER TABLE PUBLIC.ff_payment_transaction ADD CONSTRAINT fk_fulfillment_payment_transaction_parent_transaction_id FOREIGN KEY (parent_transaction_id) REFERENCES PUBLIC.fulfillment_payment_transaction (id)]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
        at liquibase.Liquibase.update(Liquibase.java:214)
        at liquibase.Liquibase.update(Liquibase.java:192)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
        at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:82)
        at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:64)
        at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: liquibase.exception.DatabaseException: Table "FULFILLMENT_PAYMENT_TRANSACTION" not found; SQL statement:
ALTER TABLE PUBLIC.ff_payment_transaction ADD CONSTRAINT fk_fulfillment_payment_transaction_parent_transaction_id FOREIGN KEY (parent_transaction_id) REFERENCES PUBLIC.fulfillment_payment_transaction (id) [42102-195] [Failed SQL: ALTER TABLE PUBLIC.ff_payment_transaction ADD CONSTRAINT fk_fulfillment_payment_transaction_parent_transaction_id FOREIGN KEY (parent_transaction_id) REFERENCES PUBLIC.fulfillment_payment_transaction (id)]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:309)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582)
        ... 12 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Table "FULFILLMENT_PAYMENT_TRANSACTION" not found; SQL statement:
ALTER TABLE PUBLIC.ff_payment_transaction ADD CONSTRAINT fk_fulfillment_payment_transaction_parent_transaction_id FOREIGN KEY (parent_transaction_id) REFERENCES PUBLIC.fulfillment_payment_transaction (id) [42102-195]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.schema.Schema.getTableOrView(Schema.java:456)
        at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:201)
        at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:77)
        at org.h2.command.CommandContainer.update(CommandContainer.java:101)
        at org.h2.command.Command.executeUpdate(Command.java:260)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307)
  
The table name is not changed in table references.

##### **JHipster Version(s)**

4.6.1

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
pacific-trader@0.0.0 /home/oem/Workspace-dev/e-commerce/pacificTrader
└── generator-jhipster@4.6.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.6.1",
    "baseName": "myapp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Category (category) {
  name String required minlength(2) maxlength(80),
  keywords String maxlength(80),
  activeStartDate ZonedDateTime required,
  activeEndDate ZonedDateTime,
  status String maxlength(8),
  sortOrder Integer,
  isLeaf Boolean required
}
entity Product (product) {
  brand String required maxlength(80),
  name String required maxlength(80),
  model String maxlength(80),
  keywords String,
  description byte[] required maxbytes(500),
  unitPriceRange String required maxlength(40),
  unitSalePriceRange String maxlength(40),
  taxCode String maxlength(40),
  specification String maxlength(255),
  featured Boolean required,
  hasVariants Boolean required,
  variantAvailibityMatrix String,
  status String required maxlength(8),
  discountable Boolean required,
  taxable Boolean required,
  limitationPerCustomer Integer min(1)
}
entity ProductSaleSummary (product_sale_summary) {
  lastUpdatedTime ZonedDateTime required,
  totalNumberOfSales Integer min required,
  totalNumberOfSalesInPast30Days Integer required min
}
entity CategoryCrossSaleProduct (category_cross_sale_product) {
  weight Integer min max(10)
}
entity CategoryUpSaleProduct (category_up_sale_product) {
  weight Integer min max(10)
}
entity ProductCrossSaleProduct (product_cross_sale_product) {
  weight Integer min max(10)
}
entity ProductUpSaleProduct (product_up_sale_product) {
  weight Integer min max(10)
}
entity Sku (sku) {
  name String required maxlength(80),
  description byte[] maxbytes(500),
  quantityAvailable Integer min,
  discountable Boolean required,
  taxable Boolean required,
  taxCode String maxlength(9),
  activeStartDate ZonedDateTime required,
  activeEndDate ZonedDateTime,
  specifications String,
  idx1 Integer required min,
  idx2 Integer min,
  inventoryType String required maxlength(8),
  unitPrice BigDecimal required min,
  unitSalePrice BigDecimal min,
  expressShippingFee BigDecimal min
}
entity VolumnPricing (volumn_pricing) {
  lowBound Integer required min(2),
  upBound Integer min(5),
  step Integer min(1),
  unitPrice BigDecimal required min,
  unitSalePrice BigDecimal min,
  expressShippingFee BigDecimal min
}
entity VolumnPricingSup (volumn_pricing_sup) {
  lowBound Integer required min(2),
  upBound Integer min(3),
  step Integer min(1),
  currency String required maxlength(8),
  price BigDecimal required min,
  expressShippingFee BigDecimal min
}
entity RatingSummary (rating_summary) {
  averageProductRating Float min max(5) required,
  averageServiceRating Float min max(5) required,
  votingCounter Integer required min
}
entity Rating (rating) {
  productRating Integer required min(1) max(5),
  serviceRating Integer required min(1) max(5),
  submittedDate ZonedDateTime required
}
entity Review (review) {
  content byte[] required minbytes(20) maxbytes(5000),
  submittedDate ZonedDateTime required,
  helpfulCount Integer min,
  notHelpfulCount Integer min
}
entity ReviewHelpfulRecord (review_helpful_record) {
  helpful Boolean required,
  submittedDate ZonedDateTime required
}
entity ReviewFeelback (review_feelback) {
  helpful Boolean required
}
entity ReviewResponse (review_response) {
  content String required minlength(9),
  submittedDate ZonedDateTime required
}
entity ReviewSup (review_sup) {
  content String required minlength(9),
  submittedDate ZonedDateTime required,
  helpfulCount Integer min,
  notHelpfulCount Integer min
}
entity ReviewResponseSup (review_response_sup) {
  content String required minlength(9),
  submittedDate ZonedDateTime required
}
entity RatingSummarySup (rating_summary_sup) {
  averageProductRating Float min max(5) required,
  averageServiceRating Float min max(5) required,
  votingCounter Integer required min
}
entity Question (question) {
  content String required maxlength(150),
  submittedDate ZonedDateTime required,
  havingTheCounter Integer min
}
entity SameQuestionRecord (same_question_record) {
  submittedDate ZonedDateTime required
}
entity Answer (answer) {
  content byte[] required maxbytes(500),
  submittedDate ZonedDateTime required,
  inaccurateCounter Integer min
}
entity AnswerFeelback (answer_feelback) {
  inaccurate Boolean required
}
entity QuestionSup (question_sup) {
  content String required maxlength(150),
  submittedDate ZonedDateTime required
}
entity AnswerSup (answer_sup) {
  content byte[] required maxbytes(5000),
  submittedDate ZonedDateTime required,
  helpfulCount Integer min
}
entity Supplier (supplier) {
  name String required minlength(2) maxlength(80),
  description byte[] required maxbytes(5000),
  tMallStoreUrl String maxlength(255),
  jdStoreUrl String maxlength(255),
  phoneNumber String required maxlength(80),
  emaillAddress String required maxlength(255),
  weChatID String required maxlength(80),
  distributeCountries String maxlength(80),
  ableToReadCommentsInEnglish Boolean required,
  ableToRespondQuestionsInEnglish Boolean required,
  businessAddressAddressLine1 String required maxlength(80),
  businessAddressAddressLine2 String maxlength(90),
  businessAddressCity String required maxlength(90),
  businessAddressProvince String required maxlength(80),
  businessAddressPostalCode String required maxlength(12),
  businessAddressCounty String required maxlength(12)
}
entity SuppliersProductCategory (suppliers_product_category) {
  status String
}
entity SupplierReviewSummary (supplier_review_summary) {
  averageProductRating String maxlength(80),
  averageServiceRating String maxlength(80)
}
entity ProductSup (product_sup) {
  brand String required maxlength(80),
  name String required maxlength(80),
  model String maxlength(80),
  keywords String,
  description byte[] required maxbytes(5000),
  specification String maxlength(255),
  hasVariants Boolean required,
  variantAvailibityMatrix String,
  status String required maxlength(8),
  tMallProductURL String maxlength(255),
  jdProductURL String maxlength(255),
  inEnglish Boolean required,
  limitationPerCustomer Integer min(1)
}
entity SkuSup (sku_sup) {
  name String maxlength(80),
  description byte[] maxbytes(5000),
  upc String maxlength(80),
  specifications String,
  unitPrice BigDecimal required min,
  expressShippingFee BigDecimal min,
  activeStartDate ZonedDateTime required,
  activeEndDate ZonedDateTime,
  idx1 Integer required min,
  idx2 Integer min,
  inventoryType String required maxlength(8),
  quantityAvailable Integer min,
  inEnglish Boolean required
}
entity Order (order) {
  status String,
  createdTime ZonedDateTime required,
  lastUpdatedTime ZonedDateTime required,
  subTotal BigDecimal min,
  total BigDecimal min,
  totalSale BigDecimal min,
  instruction byte[] maxbytes(255),
  deliveryMethod String required maxlength(9),
  shippingAddressAddressLine1 String required maxlength(80),
  shippingAddressAddressLine2 String maxlength(80),
  shippingAddressCity String required maxlength(40),
  shippingAddressState String required maxlength(80),
  shippingAddressListZipCode String required maxlength(12),
  shippingAddressCounty String required maxlength(12)
}
entity OrderItem (order_item) {
  itemName String required maxlength(80),
  unitPrice BigDecimal min,
  unitSalePrice BigDecimal min,
  quantity Integer min(1)
}
entity OrderTrackingInfo (order_tracking_info) {
  numberOfItems Integer required min(1),
  shippingTrackingNumber String required maxlength(80),
  trackingInfoUrl String maxlength(255),
  recordTime ZonedDateTime required
}
entity OrderPayment (order_payment) {
  currency String required maxlength(8),
  amount BigDecimal required min,
  status String maxlength(80),
  referenceNumber String maxlength(80),
  paymentType String maxlength(80),
  isArchived Boolean required,
  billingAddressAddressLine1 String required maxlength(80),
  billingAddressAddressLine2 String maxlength(90),
  billingAddressCity String required maxlength(90),
  billingAddressState String required maxlength(80),
  billingAddressZipCode String required maxlength(12),
  county String required maxlength(12)
}
entity OrderPaymentTransaction (order_payment_transaction) {
  currency String required maxlength(8),
  amount BigDecimal required min,
  transcationDate ZonedDateTime required,
  rawResponse String maxlength(255),
  customerIPAddress String maxlength(255),
  transactionType String maxlength(8),
  isSuccess Boolean required
}
entity FulfillmentGroup (fulfillment_group) {
  deliveryMethod String required,
  instruction byte[] maxbytes(255),
  referenceNumber String maxlength(80),
  status String,
  totalPrice BigDecimal required min,
  shippingTrackingNumber String maxlength(80),
  shippingAddressAddressLine1 String required maxlength(80),
  shippingAddressAddressLine2 String maxlength(80),
  shippingAddressCity String required maxlength(40),
  shippingAddressState String required maxlength(80),
  shippingListZipCode String required maxlength(12),
  shippingAddressCounty String required maxlength(12)
}
entity FulfillmentItem (fulfillment_item) {
  quantity Integer required min(1),
  totalItemAmount BigDecimal min,
  shippingTrackingNumber String maxlength(80)
}
entity FulfillmentPayment (fulfillment_payment) {
  currency String required maxlength(8),
  amount BigDecimal required min,
  status String maxlength(80),
  referenceNumber String maxlength(80),
  isArchived Boolean required
}
entity FulfillmentPaymentTransaction (fulfillment_payment_transaction) {
  currency String required maxlength(8),
  amount BigDecimal required min,
  transcationDate ZonedDateTime required,
  rawResponse String maxlength(255),
  isSuccess Boolean required
}
entity ShoppingList (shopping_list) {
  lastUpdateTime ZonedDateTime required
}
entity Coupon (coupon) {
  code String required maxlength(80),
  percentOff Integer min(1) max(99),
  startDate ZonedDateTime required,
  endDate ZonedDateTime required,
  maxItemsPerOrder Integer min(1),
  maxPricePerOrder BigDecimal min(1),
  maxUsesPerCustomer Integer min(1),
  maxUsesPerOrder Integer min(1),
  maxUsesInTotal Integer min(1),
  exceedMaxUsesInTotalMessage String maxlength(255)
}
entity CouponAudit (coupon_audit) {
  appliedDate ZonedDateTime required
}
entity Notification (notification) {
  content String required maxlength(255),
  status String,
  submittedDate ZonedDateTime
}
entity UserAccount (user_account) {
  deactived Boolean required,
  challengeQuestion String,
  points Integer,
  phone String required,
  homeAddressAddressLine1 String required maxlength(80),
  homeAddressAddressLine2 String maxlength(90),
  homeAddressCity String required maxlength(90),
  homeAddressState String required maxlength(80),
  homeAddressZipCode String required maxlength(12),
  homeAddressCountry String required maxlength(12)
}
entity Event (event) {
  entityName String required maxlength(80),
  operationType String required maxlength(80),
  payload String required,
  journeyTime ZonedDateTime required
}

relationship OneToOne {
  ProductSaleSummary{product(name)} to Product,
  RatingSummary{product(name)} to Product,
  Review{rating} to Rating,
  Review{response} to ReviewResponse,
  ReviewResponse{responser} to User,
  ReviewSup{response} to ReviewResponseSup,
  ReviewResponseSup{responser} to User,
  RatingSummarySup{product(name)} to ProductSup,
  SuppliersProductCategory{category} to Category,
  SupplierReviewSummary{supplier} to Supplier{reviewSummary},
  OrderPaymentTransaction{parenetnTraction} to OrderPaymentTransaction,
  FulfillmentPaymentTransaction{parentTransaction} to FulfillmentPaymentTransaction,
  ShoppingList{shopper} to User,
  CouponAudit{order} to Order
}
relationship OneToMany {
  Product{skus} to Sku{product},
  Question{answers} to Answer{question},
  QuestionSup{answers} to AnswerSup{question},
  ProductSup{skus} to SkuSup{product},
  Order{items} to OrderItem{order},
  Order{payment} to OrderPayment{order},
  OrderPayment{transactions} to OrderPaymentTransaction{payment},
  FulfillmentGroup{payment} to FulfillmentPayment{fullfillment},
  FulfillmentPayment{transactions} to FulfillmentPaymentTransaction{payment}
}
relationship ManyToOne {
  Category{parent(name)} to Category,
  Product{supplier} to Supplier,
  CategoryCrossSaleProduct{category} to Category,
  CategoryCrossSaleProduct{product} to Product,
  CategoryUpSaleProduct{category} to Category,
  CategoryUpSaleProduct{product} to Product,
  ProductCrossSaleProduct{product1} to Product,
  ProductCrossSaleProduct{product2} to Product,
  ProductUpSaleProduct{product1} to Product,
  ProductUpSaleProduct{product2} to Product,
  VolumnPricing{sku} to Sku,
  VolumnPricingSup{sku} to SkuSup,
  Rating{customer} to User,
  Rating{summary} to RatingSummary,
  Review{summary} to RatingSummary,
  ReviewHelpfulRecord{user} to User,
  ReviewHelpfulRecord{review} to Review,
  ReviewFeelback{user} to User,
  ReviewFeelback{review} to Review,
  Question{product} to Product,
  Question{user} to User,
  SameQuestionRecord{user} to User,
  SameQuestionRecord{question} to Question,
  Answer{user} to User,
  Answer{answerer} to User,
  AnswerFeelback{anwser} to Answer,
  AnswerFeelback{user} to User,
  QuestionSup{asker} to User,
  Supplier{owner} to User,
  SuppliersProductCategory{supplier} to Supplier,
  Order{customer} to User,
  Order{appliedCoupon} to Coupon,
  OrderItem{sku} to Sku,
  OrderTrackingInfo{order} to Order,
  OrderTrackingInfo{fulfillmentGroup} to FulfillmentGroup,
  FulfillmentGroup{supplier} to Supplier,
  FulfillmentGroup{order} to Order,
  FulfillmentItem{group} to FulfillmentGroup,
  FulfillmentItem{sku} to SkuSup,
  CouponAudit{user} to User,
  CouponAudit{coupon} to Coupon,
  Notification{sender} to User,
  Notification{recipient} to User
}
relationship ManyToMany {
  Category{product(name)} to Product{category},
  ProductSup{category} to Category,
  ShoppingList{product(name)} to Sku{shoppingList},
  Coupon{applicableCategories(name)} to Category
}

paginate Category with pagination
service Category with serviceClass
paginate Product with pagination
service Product with serviceClass
paginate ProductSaleSummary with pagination
paginate CategoryCrossSaleProduct with pagination
paginate CategoryUpSaleProduct with pagination
paginate ProductCrossSaleProduct with pagination
paginate ProductUpSaleProduct with pagination
paginate Sku with pagination
service Sku with serviceClass
paginate VolumnPricing with pagination
service VolumnPricing with serviceClass
paginate VolumnPricingSup with pagination
service VolumnPricingSup with serviceClass
paginate RatingSummary with pagination
paginate Rating with pagination
paginate Review with pagination
service Review with serviceClass
paginate ReviewHelpfulRecord with pagination
paginate ReviewFeelback with pagination
paginate ReviewResponse with pagination
service ReviewResponse with serviceClass
paginate ReviewSup with pagination
service ReviewSup with serviceClass
paginate ReviewResponseSup with pagination
service ReviewResponseSup with serviceClass
paginate RatingSummarySup with pagination
service RatingSummarySup with serviceClass
paginate Question with pagination
service Question with serviceClass
paginate SameQuestionRecord with pagination
paginate Answer with pagination
service Answer with serviceClass
paginate AnswerFeelback with pagination
paginate QuestionSup with pagination
service QuestionSup with serviceClass
paginate AnswerSup with pagination
service AnswerSup with serviceClass
paginate Supplier with pagination
service Supplier with serviceClass
paginate SuppliersProductCategory with pagination
paginate SupplierReviewSummary with pagination
paginate ProductSup with pagination
service ProductSup with serviceClass
paginate SkuSup with pagination
service SkuSup with serviceClass
paginate Order with pagination
service Order with serviceClass
paginate OrderItem with pagination
paginate OrderTrackingInfo with pagination
paginate OrderPayment with pagination
paginate OrderPaymentTransaction with pagination
paginate FulfillmentGroup with pagination
service FulfillmentGroup with serviceClass
paginate FulfillmentItem with pagination
paginate FulfillmentPayment with pagination
paginate FulfillmentPaymentTransaction with pagination
paginate ShoppingList with pagination
paginate Coupon with pagination
paginate CouponAudit with pagination
paginate Notification with pagination
paginate UserAccount with pagination
service UserAccount with serviceClass
paginate Event with pagination
service Event with serviceClass

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 4.5.0

bower: 1.8.0

gulp:
[16:06:58] CLI version 1.3.0
[16:06:58] Local version 3.9.1

yeoman: 2.0.0

yarn: 0.27.5

docker-compose version 1.8.0, build unknown

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "relationshipName": "parentTransaction",
            "otherEntityName": "fulfillmentPaymentTransaction",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "fulfillmentPaymentTransaction"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "payment",
            "otherEntityName": "fulfillmentPayment",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "currency",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 8
        },
        {
            "fieldName": "amount",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required",
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "transcationDate",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "rawResponse",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 255
        },
        {
            "fieldName": "isSuccess",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170711213548",
    "entityTableName": "fulfillment_payment_transaction",
    "dto": "no",
    "pagination": "pagination",
    "service": "no"
}

##### **Browsers and Operating System**

Linux Mint 18.2

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry but in your configuration, the table name is indeed `fulfillment_payment_transaction`
