### ISSUE TITLE
Unable to run Cucumber feature file in microservice

### ISSUE THREAD

**Issue by kcrane3576** [jhipster/generator-jhipster#6107]
##### **Overview of the issue**
I am unable to create cucumber feature and run the tests. I created a microservice application on its own as well as with a registry, but was unable to run the below feature setup.

##### **Motivation for or Use Case**
I would like to use cucumber tests for a microservice.

##### **Reproduce the error**
- Run the jhipster generator
    - Run the jhipster generator in a new directory
    - Select Microservice application
    - No other generators were installed
    - Port 8081
    - Did not use the JHipster registry (Did attempt to in another attempt)
    - JWT Authentication
    - SQL database
    - MySQL production database
    - H2 with disk-based persistence development database
    - HazelCast 2nd level cache
    - Maven
    - No other technologies
    - No internationalization support
    - English
    - No additional languages
    - Cucumber testing framework

- Create a “temp.feature” file with the below information inside of src/test/features:

~~~
    Feature: Belly
        Scenario: a few cukes
            Given I have 42 cukes in my belly
~~~

- Added “StepDefs.java” inside of com.mycompany.myapp/cucumber/stepdefs and below “protected ResultActions actions;”:
~~~java
        @Given("^I have (\\d+) cukes in my belly$")
        public void i_have_cukes_in_my_belly(int arg1) throws Throwable {}
~~~

- Right click on “temp.feature” and select “Run ‘Feature: temp’”
    - The result of the run is below:
~~~
		Undefined step: Given  I have 42 cukes in my belly
                1 Scenarios (1 undefined)
                1 Steps (1 undefined)
                0m0.000s
                You can implement missing steps with the snippets below:
                @Given("^I have (\\d+) cukes in my belly$")
                public void i_have_cukes_in_my_belly(int arg1) throws Throwable {
                    // Write code here that turns the phrase above into concrete actions
                    throw new PendingException();
                }
~~~

- Run/Debug Configuration:
    Main class: cucumber.api.cli.Main
    Glue: cucumber.api.spring com.mycompany.myapp.cucumber.stepdefs
    Feature or folder path: /Users/kylecrane/Desktop/micro/src/test/features/temp.feature
    Program arguments:  --pluginorg.jetbrains.plugins.cucumber.java.run.CucumberJvmSMFormatter --monochrome

##### **Related issues**
I searched for “cucumber” with no filter and did not see any submissions that were similar. 

##### **Suggest a Fix**
I was able to successfully execute the “user.feature” file with a monolithic application.
Note: The "##### **Browsers and Operating System**" is the same for as below requirements.

I am not sure what may be the cause. During the process of attempting to find out if it was user error, I installed a monolithic application with the below JHipster configuration:
~~~
    {
     "generator-jhipster": {
     "promptValues": {
     "packageName": "com.mycompany.myapp",
     "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.1",
    "baseName": "temp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
 }
~~~

##### **JHipster Version(s)**
└── generator-jhipster@4.5.1 

##### **JHipster configuration**
~~~
 {
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.1",
    "baseName": "micro",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn"
  }
 }
~~~

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
git version 2.13.1
node: v6.11.0
npm: 5.0.3
bower: 1.8.0
gulp:
CLI version 3.9.1
yeoman: 1.8.5
yarn: 0.24.6
Docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.14.0, build c7bdf9e

- [✓ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Excuse me but  I don't understand what the issue is.
What makes you think it's a JHipster issue?

**Comment by gmarziou** [comment]
OK I have reproduced the issue, the step definition is not taken into account.

**Comment by gmarziou** [comment]
It works for me.

> Added “StepDefs.java” inside of com.mycompany.myapp/cucumber/stepdefs and below “protected ResultActions actions;”:
        @Given("^I have (\\d+) cukes in my belly$")
        public void i_have_cukes_in_my_belly(int arg1) throws Throwable {}

This is not how it is done in monolith for user feature.
StepDefs is an abstract class, you should not put your `@Given` here, instead you should define a class that extends it.

~~~java
package com.mycompany.myapp.cucumber.stepdefs;

import cucumber.api.PendingException;
import cucumber.api.java.en.Given;

public class TempStefDefs extends StepDefs {

    @Given("^I have (\\d+) cukes in my belly$")
    public void i_have_cukes_in_my_belly(int arg1) throws Throwable {
        // Write code here that turns the phrase above into concrete actions
        throw new PendingException();
    }
}
~~~

Output of `mvnw test`

~~~
2017-07-14 00:22:52.247  INFO 7928 --- [           main] c.m.m.cucumber.stepdefs.TempStefDefs     : Started TempStefDefs in 32.57 seconds (JVM running for 35.214)

  Scenario: a few cukes               # temp.feature:2
    Given I have 42 cukes in my belly # TempStefDefs.i_have_cukes_in_my_belly(int)
      cucumber.api.PendingException: TODO: implement me
        at com.mycompany.myapp.cucumber.stepdefs.TempStefDefs.i_have_cukes_in_my_belly(TempStefDefs.java:11)
        at ?.Given I have 42 cukes in my belly(temp.feature:3)


1 Scenarios (1 pending)
1 Steps (1 pending)
0m0,169s

cucumber.api.PendingException: TODO: implement me
        at com.mycompany.myapp.cucumber.stepdefs.TempStefDefs.i_have_cukes_in_my_belly(TempStefDefs.java:11)
        at ?.Given I have 42 cukes in my belly(temp.feature:3)
~~~

**Comment by kcrane3576** [comment]
Ok. Sorry, but thank you.

**Comment by jdubois** [comment]
This really doesn't look like a bug, please use Stackoverflow next time - you will have better answers and it will help more people
