### ISSUE TITLE
Restrict creating entity with entity name as "Entity"

### ISSUE THREAD

**Issue by FirstSamurai** [jhipster/generator-jhipster#6110]
- Need to restrict the user from able to create an entity with name as "Entity"

eg: **yo jhipster:entity Entity**

Jhipster Version: v4.6.1

**Comment by gmarziou** [comment]
Please submit a PR.

**Comment by gmarziou** [comment]
Thanks for the report, would you please consider submitting a pull request against jhipster-core?

https://github.com/jhipster/jhipster-core/blob/8d1e2445dcfa9882fa862b48c35a4f869bcd3acc/lib/core/jhipster/reserved_keywords.js#L40-L46

**Comment by FirstSamurai** [comment]
Hi,

I tried raising a PR, but I got the following error.

remote: Permission to jhipster/jhipster-core.git denied to FirstSamurai.
fatal: unable to access 'https://github.com/jhipster/jhipster-core.git/': The requested URL returned error: 403

This is the first time I am trying to raise a PR for Jhipster.

**Comment by deepu105** [comment]
@FirstSamurai you need to clone the repo and the create PR from your fork please follow https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md and https://opensource.guide/how-to-contribute/#opening-a-pull-request

**Comment by jdubois** [comment]
@FirstSamurai yes you need to fork the repository first.
Here is our documentation: https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by jdubois** [comment]
@deepu105 we're in sync :-)

**Comment by deepu105** [comment]
@jdubois :smile_cat:

**Comment by deepu105** [comment]
I'm gonna add https://opensource.guide/how-to-contribute/#opening-a-pull-request to our contribution guide. will be useful for beginners

**Comment by FirstSamurai** [comment]
Thanks I have raised a PR. Please let me know if any mistakes.

https://github.com/jhipster/jhipster-core/pull/136

**Comment by deepu105** [comment]
pr merged
