### ISSUE TITLE
AuditEventConverter NPE for single events

### ISSUE THREAD

**Issue by abshkd** [jhipster/generator-jhipster#6114]
##### **Overview of the issue**
AuditEventConverter will throw an NPE if a singular Null AuditEvent is passed.
for e.g. 
`return auditEventConverter.convertToAuditEvent(persistentAuditEvent);`

The same is handled correctly in the case of multiple AuditEvents like this, source from `AuditEventConverter.java`
```
if (persistentAuditEvents == null) {
            return Collections.emptyList();
        }
```

##### **Motivation for or Use Case**

I am adding a new method to `CustomAuditEventRepository.java` that will return only one event if it exists for certain `AuditEvent.type`. it is entirely possible that the no results are returned in which case we can easily handle the Null value in our implementation.

Given the way the rest of the custom audit repository behaves, we could expect any implementation to use the same consistent approach. I would suggest it be fixed in generator.

##### **Reproduce the error**
```
    public AuditEvent getLatest(String principal, String type){
        PersistentAuditEvent persistentAuditEvent = persistenceAuditEventRepository
            .findFirstByPrincipalAndAuditEventDateIsBeforeAndAuditEventTypeOrderByAuditEventDateDesc(
                principal,
            LocalDateTime.now(),
                type
            );
        return auditEventConverter.convertToAuditEvent(persistentAuditEvent);
    }
```
##### **Related issues**

too old to be mentioned.

##### **Suggest a Fix**
I am not familiar with generators and I will try to fix it myself if the good folks agree. If i cannot DIY this is my suggested fix in AuditEventConverter

```
    public AuditEvent convertToAuditEvent(PersistentAuditEvent persistentAuditEvent) {
        if(persistentAuditEvent == null) {
            return null;
        }
            Instant instant = persistentAuditEvent.getAuditEventDate().atZone(ZoneId.systemDefault()).toInstant();
            return new AuditEvent(Date.from(instant), persistentAuditEvent.getPrincipal(),
                persistentAuditEvent.getAuditEventType(), convertDataToObjects(persistentAuditEvent.getData()));

    }
```

The other way is to explicitly add `NullPointerException` and let it propagate upstream so we know that it needs to be handled.

##### **JHipster Version(s)**

generator-jhipster@4.4.1

**Comment by deepu105** [comment]
Please do a PR

**Comment by michael-wirth** [comment]
1+
