### ISSUE TITLE
Proposed changes to application file structure and naming

### ISSUE THREAD

**Issue by dancancro** [jhipster/generator-jhipster#6117]
##### **Overview of the issue**

The purpose of this issue is to provide a single place to discuss proposals for changes to application file naming and organization.

##### **Motivation for or Use Case**

Uniformity of file structure between applications is always valuable because it makes life simpler. Formal and de facto standards exist, and the JHipster applications do not always adhere to them. Sometimes the standards are less unanimous than others. Sometimes deviation from standards is also valuable. 

In any case, the reasons for doing things a certain way should be made clear, debated and weighed against the alternatives. Traditionally, these discussions occur on Gitter or another way that makes it hard for everyone to know every argument for and against every structural opinion. Having this be kept in a central place solves that problem.

Enter proposals as comments to this issue in the following format. Update the comment as people contribute thoughts. Use 👍  or 👎  to express your opinions of proposals.

-----
## Proposal: < proposal name >
< proposal description >

### For
1. < arguments in favor of proposal >

### Against 
2. < arguments against proposal >
-----
-----
### [Co-locate front end unit tests with tested code](https://github.com/jhipster/generator-jhipster/issues/6117#issuecomment-315551717)

**Comment by dancancro** [comment]
To begin, here are some proposed changes.

1) Move what is in the `src/main/webapp/app/blocks` directory into a `core` directory and create a `CoreModule`, according to [the Angular style guide](https://angular.io/guide/styleguide#core-feature-module). Arguments are listed in the style guide.

2) Move the javascript test files from `src/test` to the directories where the tested code exists, according to [the Angular style guide](https://angular.io/guide/styleguide#overall-structural-guidelines). Arguments are listed in the style guide. To me the most compelling reason is that this would make it easier to move directories around without breaking references. It would also let you see whether a given application file has a test file.

**Comment by deepu105** [comment]
@dancancro is this discussion only about Angular code? It seems so from your comments. I completely agree for your first point and would you like to do a PR for that?

As for the second point the Angular style guide doesn't take into consideration a full stack application structure, the proposed structure is geared more towards front end only apps where it would make sense. In a maven/gradle monolithic app where all your other tests are in a test directory it would be very odd to find the front end specs in the src which would be new to back end developers. Please also note that these style recommendations are not golden standards, for example React suggests having tests in a __test__ folder. When we add react support soon we have to be consistent as much as possible as well. So I'm pretty ok with our current test structure and wouldn't want to change it unless there is great value in doing so

**Comment by deepu105** [comment]
React suggests `__test__` folder

**Comment by dancancro** [comment]
@deepu105 Thanks for your feedback!

Hmm I should be able to do a pull request for this. I have not actually dived into the generator code at all, but this seems like a good opportunity. Let me give that some thought and get back to you.

My intention was for this issue to cover all of the JHipster code, front and back. Because each structural change could impact other structural decisions, rather than having a separate issue for each proposed change we would use just this one so it's easier to find competing interests.

I definitely value adherence to industry practices. If you know of the practical reasons behind React's approach, that would help clear this up. I'm sure there are reasons, but without knowing them, I'm going to be a little uneasy. I have added a list of the pros and cons to my original comment. In integrating code from a demo into my big application I have spent a good deal of time moving things around and the inconvenience of updating references was pretty apparent. Without knowing the advantages of the prevailing approach the case for change seems pretty strong to me. To become front end devs, Java back end programmers will need to learn a lot of things. That tests are located in a different place should be among the simplest of them.

**Comment by dancancro** [comment]
## Proposal: Co-locate front end tests with tested code
Move the front end test files from `src/test/javascript` to the directories where the tested code exists.

### For
1) Easier to move files around without breaking references. Things are self-contained.
2) Easier to read/understand references because they're shorter.
3) Easier to see whether a given app file does or does not have tests.
4) Consistent with [Angular style guide](https://angular.io/guide/styleguide#overall-structural-guidelines).
5) Consistent with how [Google organizes](https://gitter.im/angular/angular?at=59694aac0de4d2545e2b2541) their own Angular applications.

### Against
1) Easier to see how many total tests your app has.
2) Consistent with Java and back end programmer practices.
3) Consistent with React's file organization.

I made this a separate comment from the blocks one so that people could use 👍  and 👎  to express opinions.

**Comment by deepu105** [comment]
@dancancro I agree that having tests in the same folder might help when you move stuff around but then that's why we use IDE for those, for example, IntelliJ updates reference automatically when we move stuff around. There are plugins that do this for Vscode as well. So for me, this is a good reason but not good enough to change our current structure. we had a lot of discussion regarding this when we started angular migration and decided to stay with the current approach. 

Also I think you misunderstood my comment about React, they normally propose to put test files in the src folder of the component under a `__test__` directory.

Then I believe that the convention from React and Angular for these are more based on the agreement/preference from their community (Which tends to agree when some important person from the project comes up with the idea :smiling_imp:  ) rather than based on any practical issue/difficulty. So things like these are heavily dependent on preferences.

With Jhipster, one of our aim is to provide same user experience and similar structure as much as possible when using different options so once we add React, which will be soon, we would like it to have tests in similar fashion as ng1 and ngx. We wouldn't want to react fans to complain that we follow Angular style guide but not React?

Anyway I'll wait for more opinions here and if there is overwhelming support to move it into same folders then we can consider that.

Btw one more minor item for con would be that we would have to make sure to exclude test files during packaging the app

**Comment by jdubois** [comment]
I am against this: we follow the Maven guidelines here, and I hate to have my source code mixed up with my tests, those are 2 different things.
This also makes packaging more complex.

**Comment by dancancro** [comment]
@deepu105 Thanks for clarifying the React approach. As I now understand it, it seems more like an argument **in favor of** colocation rather than keeping things the way they are. Having `mycomponent/__test__/mycomponent.spec.ts` seems unnecessarily complex to me compared to `mycomponent/mycomponent.spec.ts`, especially with a React component that already has fewer files, but if I'm understanding correctly it's more like the proposal than like the prevailing approach.

**Comment by jdubois** [comment]
Thinking of this again: separating the source code from the tests has been the norm in Java for something like 20 years. So I wouldn't change it for some new idea by the Angular team, which has had many bad ideas recently...
Anyway you'll hit a technical issue : I would be surprised you could do that change in Maven, and many IDEs won't like this too. And there's a very good reason for that : your classpath should not be the same for source and test...

**Comment by dancancro** [comment]
@jdubois I'm only proposing this change be made for the front-end, javascript/typescript, code. So it should not affect Java classpath requirements. 

If React is also putting their tests where their code lives, then it's not specifically an Angular idea, but it seems to be unsettled in React too. [Here's](https://github.com/react-boilerplate/react-boilerplate) a very popular React boilerplate that does it. [Here's](https://github.com/kriasoft/react-starter-kit) another popular one that doesn't.

I'll look around to the other front-end frameworks and see what conventions I can find.

**Comment by jdubois** [comment]
Oh sorry Dan!!! Yes this makes much more sense like this. My main issue is that we won't be consistant in JHipster, all the tests are normally under src/test (to follow the Maven way). But indeed, there is no technical issue.

**Comment by gmarziou** [comment]
The easier refactoring argument makes a lot of sense as the JS IDEs are not as good as the java IDEs to deal with related test classes. Also this would help some users who wants to move client code to dedicated folder/project rather than src/main/webapp

**Comment by Tcharl** [comment]
Hi,

Personally, I would prefer using the same convention for the backend and frontend: it would be disturbing for 'full stack' dev to find either test with source, and either in the src/test folder.
My two cents.

**Comment by jdubois** [comment]
This has been opened for 2 months with very few comments - I know it was the holidays, but I hate to have long running issues.
I perfectly understand the need to rework our directories, but for me this isn't the priority at the moment:

- We have React support coming, and we can't change directories at the same time
- The current directory structure doesn't worry much people
- This would be easier if we work on separating the front end and the back end, see #5754 - but I'm not guaranteeing this will lead somewhere, as it's quite complex
