### ISSUE TITLE
Adding Support for Offline web apps and other progressive web features.

### ISSUE THREAD

**Issue by amrsalem87** [jhipster/generator-jhipster#6119]
##### **Overview of the feature request**

Adding support for offline web apps and other progressive web app features as possible.

##### **Motivation for or Use Case**

Stop treating a lack of connectivity like an error. enable app  to handle disconnections.

##### **Reproduce the error**

Open Gateway web app from external URL, then just disconnect your network. and you will get browser's connectivity error message.

##### **Suggest a Fix**
Leverage existing technologies based on Service Workers, and Cache Manifest, like offline.js angular-offline sw-precache and other available libraries.

##### **JHipster Version(s)**
Upcoming JHipster and Angular 2+

##### **Browsers and Operating System**

Chrome 32, Opera 19, Firefox 29, Safari 8 & Microsoft Edge
- [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
it's something interesting and it can help people during demo or conference. 
But you have to describe what you have in mind, than just :
> Leverage existing technologies based on Service Workers, and Cache Manifest, like offline.js angular-offline sw-precache and other available libraries.

**Comment by gmarziou** [comment]
> But you have to describe what you have in mind

Yes please show some code with a prototype.
Then maybe @sendilkumarn may have a look as he has started working on this topic.

**Comment by amrsalem87** [comment]
Well, in so many places over the world, there are limitations and possible interruptions for the internet connections and services in general, even for those countries with advanced service providers, still internet is not available in every rural areas, or all flights.

What I have in mind is to ship JHipster with out of the box solution to address such problem and which can be extended by user to address much more complex business scenarios.

So I as user should be able to generate a web app which totally supports offline mode for basic web pages, assets, and select entities [a question during generation can be added to mark entity as offline] so that my generated application's user can have an enhanced user experience operating the app without connection loss interruptions for critical business modules.

Now, technically speaking on how to implement this, I believe we have different ways to implement this like a stand alone Service Worker that act as a proxy for our app to Cache required web assets in one or multiple cache mangers per design.

Also we might consider caching different responses to different AJAX calls so that list of certain entry records are always available offline, as well as saving ajax requests for creating new records locally until connection is back, then fire all pending requests automatically.

More about Service Workers and code samples can be found [here](https://developers.google.com/web/fundamentals/getting-started/primers/service-workers).

Also there is Sample App called [NG-Pokédex](https://coryrylan.com/blog/fast-offline-angular-apps-with-service-workers) expressing a quick showcase for utilizing Service Workers to make fast offline angular app.

**Comment by sendilkumarn** [comment]
@amrsalem87 I do completely understand your point.
We have added serviceworkers for both ng1 & ngx app. But they are commented, if you want to use you can uncomment and use them. 

I am also ✍️ the detailed documentation on how to enable offline mode (#6111)

Note 🗒  :  Service workers don't cache all the necessary things ( like the dynamically generated js and stuffs). 
This requires a lot of work (since we have to do for both ng1 and ngx) and we will be happy to get some PRs for this and I can review the same :)

I am closing this ticket, feel free to let us know if there is something you want to add.
