### ISSUE TITLE
Enhancement: moving actual backend  end-to end tests to src/it

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#6131]
##### **Overview of the issue**

Actual jhipster generated tests are not unit tests: they are actually integration ones as they are hitting the database and trying to use rest interface.

The Maven convention to these tests is then to:
* Put them in a src/it/java|ts|resource folder
* Prefix them by IT
* Use the maven failsafe plugin instead of the surefire one (so launching them during the integration-test phase)
* Use the integration-test goal of jacoco and reporting them in the parent artefact (that's ok: jhipster is mono module), but **appending** them in an jacoco-it.exec file.
* Using sonar.jacoco.itReportPath variable
* Using the build-helper-maven-plugin to add a new source folder within IDEs

##### **Motivation for or Use Case**

We could generate fully mocked ServiceImpl unit tests in the src/test/xxx folder and End to end test within src/it/...
Also we can configure surefire to avoid scanning any class but the service ones as it should be where all the business logic should be.

We could then have testing coverage for IT and UT tests!

##### **Reproduce the error**

generate a new jhipster project: no src/it folder! 

##### **Related issues**

Not really related, but #6117 speaks about test layout!

##### **Suggest a Fix**

As always, I can make a PR

##### **JHipster Version(s)**

4.6.1

##### **Browsers and Operating System**

Any

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
- I totally agree with you, we have a confusion between integration tests and unit tests.
- This is quite common in the Java world, coming from "JUnit" (which doesn't just do unit tests), and last time I checked there was the same issue with Maven.

-> I totally agree "in theory", but "in practice" I always see Maven users putting their tests in "src/test" - for example there is a "test" scope but no "integration" scope for Maven dependencies... And it's the same thing with IDEs, they mix both.

So in the end, we just do the way people usually do, which is roughly the spirit of [Policy 1](https://jhipster.github.io/policies/).

**Comment by Tcharl** [comment]
I think that this is because src/it does not exist by default within the maven structure (I had the same problem with Eclipse plugin wizard not generating a 'test' folder, leading the plugin developers not testing their projects ;-)).

Another example of unused maven standard folder is the src/main/filters...

So what about having a kind of tradeoff:

1) Prefixing actual tests classes by 'IT' [ ]
2) Generating tests in 'src/test/java/integration/<groupId> [ ]
3) Excluding tests on surefire when package starts by 'integration' [ ]
4) Including in the failsafe plugin packages which starts by 'integration' and where classes starts by 'IT' [ ]
5) Generating two jacoco reports (jacoco-ut.exec, jacoco-it.exec)[ ]
6) Idem for TS [ ]
7) An alternative to 2 and 3 could be to only differentiate test kind by prefix/suffix (starting by IT or ending by Test) [ ], or using a junit Category [ ].


So that mvn package would not execute that long IT tests (but the unit ones) as install would do.
It could be a nice velocity gain for those who use it.

I would personally prefer the first statement, and think that JHipster can bring the good habits to the end users, but we can always find 'baby steps' ;-)

**Comment by jdubois** [comment]
- yes, in fact I'm not using `src/it` as I know some plugins hardcode `src/test` - I discussed this a long time ago with some Maven committers and they told me it was better that way (but that was when migrating from Maven 1 to Maven 2, so that's really old)
- Prefixing with `IT` will indeed always work, no problem with that.
- The issue with `src/test/java/integration/` is that you won't be in the same package as the components you are testing -> the "trick" here is that some people use package scope on some attributes on methods, so they could be used in tests, and not in the rest of the application. So you're supposed to be in the same package.

**Comment by Tcharl** [comment]
Ok, so I understand that you're Ok for a PR that:

1) Prefixes actual tests classes by 'IT' (and removes the 'Test' suffix)
2) Excludes tests on surefire when name starts by 'IT'
3) Includes in the failsafe plugin classes which starts by 'IT'
4) Generates two jacoco reports (jacoco-ut.exec, jacoco-it.exec)
5) Idem for TS ? (I don't looked too much at the protractor tests, I'm more a backend guy)
6)  Using a junit Category to differentiate them once more (I think that this is better to filter the junit vs failsafe test class affectation by using category if doable).

Waiting for your ack ;)!

**Comment by deepu105** [comment]
Wouldnt Suffixing `IntTest` or `IntegrationTest` be clearer?

For TS I think its already in correct naming convention, but folder ofcourse is not as per angular style guide so I think you dont need to change anything there

**Comment by Tcharl** [comment]
This is a convention from the [failsafe-maven-plugin](http://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html), so that users already familiar with this won't be lost

**Comment by nicoraynaud** [comment]
Hi,
I have been reading this thread and can't help to give my 2 cents as a JHipster user !

@Tcharl : In the end, I understand all you want is to change the naming convention for classes doing IT. I don't understand the actual concrete need for this : as the failsafe-maven-plugin states : using suffixes is supported as well as a configuration of the plugin to state other patterns (like the one currently in place).

I'm not sure this kind of breaking change (i am thinking of users upgrading their app) is necessary because one maven plugin likes it better. We need to keep in mind that we also use gradle (which does not use failsafe plugin) and that the current suffix naming is widely used among today's developers.

**Comment by pascalgrimaud** [comment]
As @nicoraynaud said, it's a breaking change.
The users who upgrade their app (with jhipster upgrade or manually) will have all these new files in their project:
- we can't delete old files as there can be specific code
- we can't rename existing files (possible but not so easy) 
So not really a solution for this problem.

**Comment by deepu105** [comment]
Yes and to be frank I have seen the suffix based naming more often and
frankly have never seen something prefixed with IT in my career

On 20 Jul 2017 7:52 am, "Pascal Grimaud" <notifications@github.com> wrote:

As @nicoraynaud <https://github.com/nicoraynaud> said, it's a breaking
change.
The users who upgrade their app (with jhipster upgrade or manually) will
have all these new files in their project:

   - we can't delete old files as there can be specific code
   - we can't rename existing files (possible but not so easy)
   So not really a solution for this problem.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/6131#issuecomment-316604022>,
or mute the thread

**Comment by deepu105** [comment]
Also as pascal highlighted this would be annoying for people who upgrade as
there is no real value for them to rename all their existing tests before
upgrading (including me)

**Comment by Tcharl** [comment]
NP, there's no issue re-suffixing them by 'IntTest', instead of the IT prefix.

I was just wandering which choice was the best and made an arbitrary choice:

* Renaming all existing projects test class names (kind of tedious, IDEs tend to make a good job in this area).
* Force all the future project developers to suffix all their integration tests by 'IntTest': it's 5 characters more! ^^.

**Comment by deepu105** [comment]
@Tcharl I will try to respond to your comments here

> NP, there's no issue re-suffixing them by 'IntTest', instead of the IT prefix.

> I was just wandering which choice was the best and made an arbitrary choice:
> 
> Renaming all existing projects test class names (kind of tedious, IDEs tend to make a good job in this area).
Yes, but its still annoying to do isnt it?
> Force all the future project developers to suffix all their integration tests by 'IntTest': it's 5 characters more! ^^.
I don't think technically anyone cares about the length of file names!!
Its more about ease of understanding, `IntTest` IMO is more explicit the IT, for people who are not familiar. Its harder to guess just by `IT` than `IntTest` telling from personal experience and what I have seen generally (FYI I have built a lot of enterprise apps in my Career mostly with Gradle and Ant initially). We dont want to force the majority of our users who are rather a novice to intermediate to relearn stuff without a concrete reason.

> I thought your +1 smiley means that you were inline with this.

Yes, Initially but I changed my mind after reading comments from @pascalgrimaud and @nicoraynaud 

> The main added value here is that you can execute 'mvn package' to execute your unit tests so that it's pretty quick to be sure that your 'ServiceImpl' are good enough, while executing 'mvn install' will launch slower tests (IT one) in order to ensure that your End to End stack is working well.

Can't you configure the plugin to do the same without changing filenames?

> I can always rename the Integration tests name with 'IntTest', but its more a matter of taste: once you're familiar with, prefixing your tests with 'IT' is shorter than suffixing them by 'IntTest' ;-)

Exactly and please remember the needs of the many outweighs the needs of the few :smile:

**Comment by Tcharl** [comment]
> Can't you configure the plugin to do the same without changing filenames?

Sure I can, and will do it ASAP!

**Comment by deepu105** [comment]
> The main added value here is that you can execute 'mvn package' to execute your unit tests so that it's pretty quick to be sure that your 'ServiceImpl' are good enough, while executing 'mvn install' will launch slower tests (IT one) in order to ensure that your End to End stack is working well.

Wait a minute, we actually use package to build for production so shouldn't all tests be executed for that?

**Comment by deepu105** [comment]
@jhipster/developers Since i'm not that used to maven, I'm not the ebst person to evaluate or decide here can someone take a look at this please. @Tcharl could you please hold off untill we make a decision so that you dont waste a lot of time changing stuff

**Comment by Tcharl** [comment]
> Wait a minute, we actually use package to build for production so shouldn't all tests be executed for that?
No, not really: Maven has well defined [lifecycle](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) incremental lifecycle.
The 'package' phase is the one build your deliverable (your war/jar, or your container), but then, you'll have an 'install phase', installing your binary on your local environment, and a 'deploy' phase to deploy your binary (in a production environment for example).

Note that you will always be able to execute integration tests w/o installing in your local env executing 'mvn verify'.

Note2: most of the IDEs (Eclipse, IJ) bind the default lifecycle execution step to the 'install' phase.

> could you please hold off

Sure, I'll refocus on my Infrastructure as code project, or submit another Jhipster enhancement PR ;-)

**Comment by Tcharl** [comment]
Could I take the opportunity to join the party? I really like the project and ecosystem, follow the PR on a day to day basis and think that I can help on some areas, also I'll do my best to make Jhipster great.

**Comment by deepu105** [comment]
@Tcharl our policy on new members to the core team is as below, we are more than happy to welcome new members once they contribute considerably to the project (This could even be just 1 or 2  PR with a very big feature). I suggest you continue exploring and contributing to the project and when the time is right we will initiate a Vote for you. Does that sound fair?
 
> How to join the board of developers?
> Participate regularly in the project (commits, PRs, etc)
> Ask someone from the current board, with some bio and background information, and he will submit a vote on the dev mailing list
> Everybody on the dev mailing list can vote (+1 if they agree, -1 if they don’t)
> Just one “-1” vote will reject the new member, but the person who votes “-1” will need to explain why

**Comment by Tcharl** [comment]
Sure, this is the same way other communities do it: I'm an Eclipse committer, and an Apache active contributor too ;-).

Best regards,

**Comment by jdubois** [comment]
Well, @Tcharl is correct, then I've never seen anyone using `mvn install` or `mvn verify` for running integration tests. People expect to run `mvn test` and have all their tests run, including integration tests.
I also agree with @nicoraynaud and anyway we can't do a breaking change unless we release a new major release - and none is planned at the moment.
I'm sorry but this all look very complicated, and we don't have that much of an issue in the first place: I agree we mix integration and unit tests, and that's bad, but that's what the vast majority of people are doing in the Java world.

**Comment by Tcharl** [comment]
May be I'm too perfectionist :-), and I perfectly understand to argument.
@jdubois , you're a lucky one working with smart guys: on my side, I've never seen a developper using mvn test, all I've seen use mvn clean install all the time, as the front one uses yarn install to launch their tests.
I think I'll make a module (keeping the jhipster convention) of this, as the PR is simple and can potentially have a little added value to some customers (also will be used internally by my teams).

**Comment by deepu105** [comment]
closing as the PR is closed without merge.
