### ISSUE TITLE
Authentication feature

### ISSUE THREAD

**Issue by stevehouel** [jhipster/generator-jhipster#6138]
Hello Team,

I would like to start implement new authentication option using Cloud services for JHipster like Auth0 or AWS Cognito or Firebase.

Would you like to integrate it directly on main generator as authentication option or would you prefer  a separate submodule ?

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
We already have several people working on OpenID integration, for instance with Keycloack -> do you want any contacts with them? I'd rather have OpenID than a specific cloud service

**Comment by stevehouel** [comment]
Sure @jdubois send me contact. I already integrate OpenID with KeyCloak on a project so maybe I could help them.

Regarding other authentication method, I will do a separate submodule.

**Comment by jdubois** [comment]
Oh you should work with @bleporini then!!
-> how about a specific ticket on Keycloak, instead of this one?

**Comment by stevehouel** [comment]
Sure why not

**Comment by deepu105** [comment]
ok closing this then
