### ISSUE TITLE
Keycloak integration feature

### ISSUE THREAD

**Issue by stevehouel** [jhipster/generator-jhipster#6139]
New ticket regarding Keycloak and OpenID integration feature

@bleporini if you need help I am here. I already integrate it on a project so if I can help tell me.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by stevehouel** [comment]
@bleporini any news from your side ?

**Comment by jdubois** [comment]
There is #6361 which might solve this issue -> @bleporini can you have a look?

**Comment by jdubois** [comment]
I'm closing this in favor of #6360 - it looks like @mraible has got everything working
