### ISSUE TITLE
Syntax error for Lybian Arabic in i18n properties on server

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#6140]
##### **Overview of the issue**

The message properties `email.activation.greeting`, `email.reset.greeting` and `email.social.registration.greeting` for Lybian Arabic seem wrong when message contains a parameter `{0}`

https://github.com/jhipster/generator-jhipster/blob/master/generators/languages/templates/src/main/resources/i18n/_messages_ar_ly.properties#L27

It should be confirmed by @sohibegit

##### **Motivation for or Use Case**

Greetings in email messages will be wrong.

##### **Suggest a Fix**

Use `{0}`.

##### **JHipster Version(s)**

master 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "ar-ly"
    },
    "jhipsterVersion": "4.6.1",
    "baseName": "rtl",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "ar-ly",
    "languages": [
      "ar-ly",
      "en",
      "fa"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.12.0.windows.1

node: v6.10.2

npm: 3.10.10

bower: 1.8.0

gulp:
[18:20:29] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.27.5

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.14.0, build c7bdf9e3

**Comment by sohibegit** [comment]
@gmarziou It works fine, don't worry, it's not wrong, that's a behavior when mixing LTR and RTL languages.

**Comment by gmarziou** [comment]
OK, I did not see same thing with Farsi language so I was confused ;)

**Comment by sohibegit** [comment]
the deference is:
{0} RTL word <---- farsi uses      {0}عزيز    
RTL word {0} <---- arabic uses   عزيزي {0}

**Comment by gmarziou** [comment]
Interesting, thanks.

**Comment by deepu105** [comment]
I still dont get how it works :smile_cat: may be thymeleaf handles it!
