### ISSUE TITLE
Select Option values not shown in Internet Explorer 11

### ISSUE THREAD

**Issue by stieler-it** [jhipster/generator-jhipster#6147]
##### **Overview of the issue**

When creating an entity that references an Enum, the option values are not shown in IE.
![ie-listen-leer](https://user-images.githubusercontent.com/2007728/28364191-b8f29d6a-6c83-11e7-880d-5faaf1819e26.png)

##### **Motivation for or Use Case**

It makes our application unusable in IE which will be a main browser in our user base.

##### **Reproduce the error**

Generate an application using a JDL containing an Enum (see below).

Open the applicatoin in IE11, Entities -> JobHistory, create a new. The select box shows two empty entries. The same application works in Chrome and FF.

##### **Related issues**

Nothing found for jhipster, however it could to be related to:
https://stackoverflow.com/questions/12942681/how-to-fix-ie-select-issue-when-dynamically-changing-options

##### **Suggest a Fix**

See SO ticket for some hacks, also using Angular's translate pipe instead of the JHipster component seems to fix the issue.

Does not work:
`<option value="M" jhiTranslate="babsappApp.Geschlecht.M">M</option>`
Works:
`<option value="M">{{'babsappApp.Geschlecht.M' | translate}}</option>`

Surprisingly (ok, actually not so much for IE), it is enough to change the *first* option to the pipe variant. Even if there is a second option still using the jhiTranslate, it is still fixed.

##### **JHipster Version(s)**

JHipster 4.5.3 but I was also able to reproduce it with the latest version (from last week).

##### **JHipster configuration**

[jhipster-info.out.txt](https://github.com/jhipster/generator-jhipster/files/1158801/jhipster-info.out.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

The critial part seems to be the enum, e.g.:
```
entity JobHistory {
	startDate ZonedDateTime,
	endDate ZonedDateTime,
	language Language
}

enum Language {
    FRENCH, ENGLISH, SPANISH
}
```

##### **Browsers and Operating System**

Windows, IE 11

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Unfortunately I don't think anyone in the team has a Windows machine, so this will take time for us to reproduce and validate.

**Comment by stieler-it** [comment]
I see. I included a screenshot and also a possible workaround that doesn't look too bad for me. However I'm probably not aware why jhiTranslate is used in this case.
In any case, we will test the app with this change and if you agree, I can open a PR.

**Comment by jdubois** [comment]
Oh yes please do: anyway, without a Windows machine, we are stuck...

**Comment by deepu105** [comment]
yes you can change the options to the pipe varient. Please PR

**Comment by amirensit** [comment]
I have the same problem using chrome.
[http://imgur.com/a/MaLkN](url)

**Comment by gmarziou** [comment]
@amirensit so you can help by testing the changes proposed by @stieler-it in his commits.

**Comment by stieler-it** [comment]
Please note that this issue only refers to Enums, not relations. I cannot tell from the screenshot what kind of field is opened.

**Comment by gmarziou** [comment]
Good point, from the filed name in French in screenshot, I guess Assure is a relationship.
So @amirensit this is probably not the same issue and it could be an issue in your relationship definition and data rather than a JHipster issue, so please open a new issue with all required details.
