### ISSUE TITLE
It is not possible to select the first entry of a ManyToOne relationship in Internet Explorer 11

### ISSUE THREAD

**Issue by stieler-it** [jhipster/generator-jhipster#6148]
##### **Overview of the issue**

When creating an entity A that has a *required* ManyToOne relationship to entity B, it is not possible to select an instance of type B while creating a new entity A - or at least not directly (see reproduction).

##### **Motivation for or Use Case**

In case 1 this is a blocker, in case 2 it degrades the usability.

##### **Reproduce the error**

1. If there is only one entity of type B, IE shows this one as selected when the dialog is opened. You can open the select box and select it again, but it does not update the model, so the required field is still empty. *It is not possible to create an entity of type A in this case!*
2. If there are more entity, it is not possible to select the first (selected) one directly. However, you can select another one, and then switch back to the first one to finally select it.

Case 1 (Validation fails although item is selected)
![ie-selected-required](https://user-images.githubusercontent.com/2007728/28364731-096f719e-6c86-11e7-80d8-a6ee6ac01b84.png)

##### **Related issues**

I did not find a related issue.

##### **Suggest a Fix**

A possible fix would be to *always* include an empty option element, even if the relationship is required. It is still not possible to save an invalid entity. This seems to be valid since the current initial state (an option is selected that does not even exist), could be wrong anyway.

##### **JHipster Version(s)**

4.5.3

##### **JHipster configuration**

[jhipster-info.out.txt](https://github.com/jhipster/generator-jhipster/files/1158932/jhipster-info.out.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Seems to be already included in the info file.

##### **Browsers and Operating System**

Windows, IE11. The same application works on Chrome and Firefox.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Its difficult for us to test IE as most of use Linux or Mac. If you find a solution you are welcome to PR

**Comment by deepu105** [comment]
Probabaly its an angular bug

**Comment by stieler-it** [comment]
Would you be fine with my proposal of adding an empty option element even if it is a required field? I will check some other web site how it is solved there...

**Comment by deepu105** [comment]
If there is no other option then it should be ok but then we could set the
second element as default selected


Thanks & Regards,
Deepu

**Comment by stieler-it** [comment]
Chrome & Firefox show "nothing selected" as the initial state. I think we should keep it that way because it corresponds to the model which is invalid (with the field null) in that case. The only tradeoff is that the user could unselect an already selected required field. However, this it is also possible to clear a required text box, so that sounds fine.

**Comment by deepu105** [comment]
Ok

**Comment by deepu105** [comment]
@stieler-it are you going to PR this and the other issue?

**Comment by stieler-it** [comment]
Yes, I have not forgotten about it. I will need some spare time for this..

**Comment by stieler-it** [comment]
After some more research I was able to reproduce this with a pretty basic Angular example, so it looks like an Angular/IE bug to me. See also https://github.com/angular/angular/issues/14505. Still, we have to find a workaround for our project. I will share our solution and then we can decide if this should be a PR against JHipster.
