### ISSUE TITLE
Adding new language

### ISSUE THREAD

**Issue by bonsmik** [jhipster/generator-jhipster#6154]
##### **Overview of the issue**

Documentation for adding new language missing steps (at least on webpack build)

##### **Motivation for or Use Case**

Tried to add language and changing to new language didn't work. 

##### **Reproduce the error**

Follow the documentation to add new language for angular 2+

##### **Suggest a Fix**

New language must be added to webpack.common.js e.g.
```
          new MergeJsonWebpackPlugin({
                output: {
                    groupBy: [
                        { pattern: "./src/main/webapp/i18n/en/*.json", fileName: "./i18n/en.json" },
                        { pattern: "./src/main/webapp/i18n/fi/*.json", fileName: "./i18n/fi.json" }
                        // jhipster-needle-i18n-language-webpack - JHipster will add/remove languages in this array
                    ]
                }
            }),
```
  
##### **JHipster Version(s)**

4.6.2

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.xx.xx",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "vulvodynia",
    "packageName": "com.xx.xx",
    "packageFolder": "com/xx/xx",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Browsers and Operating System**

mac

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
The `webpack.common.js` file is automatically updated with this function:
https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base-private.js#L179-L198

That's why there is a `needle` here.

So I don't know where you have a problem for adding a new language.

**Comment by pascalgrimaud** [comment]
Ok understood.
It's for a specific language which is not supported? so yes, this part is missing.

Following the code [here](https://github.com/jhipster/generator-jhipster/blob/04b79da6993d88e101faf78efa0d858aa2ecf57e/generators/languages/index.js#L198-L204) :
```
this.updateLanguagesInLanguagePipe(this.config.get('languages'));
if (this.clientFramework === 'angular1') {
    this.updateLanguagesInLanguageConstant(this.config.get('languages')); // --> documented
} else {
    this.updateLanguagesInLanguageConstantNG2(this.config.get('languages')); // --> documented
    this.updateLanguagesInWebpack(this.config.get('languages')); // --> missing doc
}
```
