### ISSUE TITLE
For Angular client, AlertService not working with different jhiPrefix values

### ISSUE THREAD

**Issue by uyeliksiz** [jhipster/generator-jhipster#6155]
##### **Overview of the issue**

For angularX, Alert service is not running when a different value is set for jhiPrefix value in .yo-rc.json file. Errors, Warnings, Success messages does not appear.

##### **Suggest a Fix**

Replace all "jhi-alert", with <%=jhiPrefix%>-alert

##### **JHipster Version(s)**

4.6.2

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "a.b.c"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "abc",
    "packageName": "a.b.c",
    "packageFolder": "a/b/c",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "XXXXXXXXXX",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "oak",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Would you like to do a PR
