### ISSUE TITLE
Angular 4 - prod build performance

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6159]
Doing a perf audit shows our Angular 4 prod build is slower and bigger than our AngularJS 1 prod build.
This comes from our main js bundle:
- it's very big (500kb) without GZipping (gzip works really well on it, which shows there's a problem !!)
- time spent executing it is too long (and that's because it's really big)

Opening it shows our compiled components in a definitely non efficient format: it works, but it's big and slow.

I guess this comes from our AOT configuration.

**Comment by deepu105** [comment]
Julien ofcourse the bundle size would be more than ng1 as we have lot more
js code than ng1 in ng2, and the libraries now are huge as well. but
shouldn't be very drastically huge. When i checked last time it was descent
and loading was pretty fast. Ill check again

**Comment by delverdev** [comment]
Did you have an idea to separate user and admin`s parts? Yes, perhaps there is no much code in the admin part, but some projects can have libraries that will be used only by admins (charts libraries, datatables etc.). It can slow users that don't need them. Also, some admin panel would be more convenient and productive (dropdowns take time, a vertical menu would be great). *-management pages have much code and html that can slow a loading too.

**Comment by jdubois** [comment]
Yes, but this is another issue

**Comment by deepu105** [comment]
@jdubois lets track this in #5833 I'll add a line item there

**Comment by deepu105** [comment]
@jdubois also what did you mean by `Opening it shows our compiled components in a definitely non efficient format: it works, but it's big and slow.`?

**Comment by jdubois** [comment]
If you open up the "main.js", you'll see the generated code is really verbose, here's a screenshot below.
I guess there's an issue in the aot configuration.
This is why the file is so big, gets compressed so well (lots of duplicate stuff in it), and why the "scripting" performance of our prod build is so bad.

<img width="1440" alt="screenshot 2017-07-21 14 50 50" src="https://user-images.githubusercontent.com/316835/28747501-3d8660a6-74a0-11e7-9e5a-fb9986dcf07f.png">

**Comment by deepu105** [comment]
When I tested the prod profile I didn't find its performance bad, and yes
the generated code is verbose due to AOT, but its minified. I assume your
browser formatted it. Anyway let me check again

**Comment by jdubois** [comment]
yes I clicked on the `{}` icon to format it, still it isn't minified correctly, and it's really bad. It should be 20-30kb only

**Comment by deepu105** [comment]
Ok ill check this tomorrow

**Comment by atomfrede** [comment]
I need to check with the current configuration but during beta phase I used to get "Script not responding" on my mobile (which is not high end but also not low end), which was quite suprising to me as we don't have that much angular code. An loading on a typical german cellular took some time, but need to check with the current configuraiton again.

**Comment by jdubois** [comment]
It takes 1,5 seconds on my high-end Macbook Pro, so I wouldn't be surprised it doesn't work well on your phone @atomfrede - I'm convinced we have an issue here

**Comment by deepu105** [comment]
Ok I made some tests. here are the results. I generated the same config with both angular and angularx and run them in prod mode. So yes AngularX performance is not better than AngulaJS as per this (But its not that bad IMO, but could have been better). I'll try to see if something can be configured in webpack to reduce bundle size

My laptop config is below for ref
![image](https://user-images.githubusercontent.com/1107223/28790622-253a347e-762a-11e7-9ca0-65fb8b24cc31.png)


## AngularJS

### Asset loading
![image](https://user-images.githubusercontent.com/1107223/28790537-d348e110-7629-11e7-82fa-9889dccb0a8b.png)

### Performance
![image](https://user-images.githubusercontent.com/1107223/28790671-4aed4b70-762a-11e7-9b6d-ca6455cd1527.png)

### minified assets
![image](https://user-images.githubusercontent.com/1107223/28790811-bbd276bc-762a-11e7-91af-61f42eb4f214.png)


## Angular X

### Asset loading
![image](https://user-images.githubusercontent.com/1107223/28790683-5717dad2-762a-11e7-9fc5-033d1fe6bd74.png)

### Performance
![image](https://user-images.githubusercontent.com/1107223/28790694-600af6d8-762a-11e7-9a7c-33d8cd413c42.png)

### minified assets
![image](https://user-images.githubusercontent.com/1107223/28790750-85a4fe0c-762a-11e7-9f56-a107cc9cf4f6.png)

**Comment by deepu105** [comment]
I also tried both apps on my Samsung Galaxy s7 and there wasn't any noticeable performance difference. They loaded up pretty fast

**Comment by deepu105** [comment]
Look at my PR https://github.com/jhipster/generator-jhipster/pull/6185

## Asset loading (one image is not generated)
![image](https://user-images.githubusercontent.com/1107223/28798507-019cbdc8-7645-11e7-95ba-55e4d0d89eab.png)

## Performance
![image](https://user-images.githubusercontent.com/1107223/28798535-11118fb8-7645-11e7-80e2-a80fe6debf02.png)

## minified assets
![image](https://user-images.githubusercontent.com/1107223/28798545-19267894-7645-11e7-8521-b5862e0027a6.png)

**Comment by deepu105** [comment]
Also please note that we will never get bundle size similar to ng1 as the amount of code in Angular2 is significantly higher (almost double) due to below reasons hence I guess there is no point in comparing the bundle size here. Performance IMO is similar in both
- Angular2+ has more code in forms of decorators and stuff
- There are more libraries and their dependencies here than the flat bower stuff in ng1
- TS to ES5 transpilation results in more code due to polyfills and generated code
- AOT creates more code as all the HTML are converted into JS, but this code technically performs better than JIT as it is optimized for the browser
