### ISSUE TITLE
Fail on create entity jdl model when selecting Indonesian Language

### ISSUE THREAD

**Issue by mirzaakhena** [jhipster/generator-jhipster#6165]
##### **Overview of the issue**

It cannot generate the entity model with generator jhipster:import-jdl only in Indonesia language

##### **Reproduce the error**

Create a regular jhipster project and include the Indonesian Language as i18n. 
Then generate any entity model using jhipster:import-jdl

```
Error jhipster:import-jdl model.jdl 

ERROR! Copying template client/i18n/_entity_id.json failed. [Error: ENOENT: no such file or directory, open '/MY_PROJECT_FOLDER/node_modules/generator-jhipster/generators/entity/templates/client/i18n/_entity_id.json']
```

##### **Related issues**

This issue clearly because the generator can not found the node_modules/generator-jhipster/generators/entity/templates/client/i18n/_entity_id.json file

##### **Suggest a Fix**

Create a new file _entity_id.json under node_modules/generator-jhipster/generators/entity/templates/client/i18n/ folder

##### **JHipster Version(s)**

v4.6.2

- [v ] Checking this box is mandatory (this is just to show you read everything)

I think you guys should put some documentation on how to adding a new language. For now i found that adding new language in this 6 different place:

1. generators/generator-base.js
2. test/test-languages.js
3. generators/languages/templates/src/main/resources/i18n/_messages_id.properties
4. generators/languages/templates/src/main/webapp/i18n/id/
5. generators/client/templates/angular/src/main/webapp/app/shared/language/_find-language-from-key.pipe.ts
6. generators/client/templates/angularjs/src/main/webapp/app/components/language/_language.filter.js
7. generator-jhipster/generators/entity/templates/client/i18n/

I also already create a pull request [here](https://github.com/jhipster/generator-jhipster/pull/6164)

**Comment by deepu105** [comment]
closed via PR #6164
