### ISSUE TITLE
AuthorizedFeignClient not working between microservices with @Secured

### ISSUE THREAD

**Issue by dapperdanman** [jhipster/generator-jhipster#6173]
##### **Overview of the issue**

I followed the documentation on the website for using Microservices with UAA, and tried to write some test code to have one microservice call another using the `AuthorizedFeignClient`. It works OK until I protect a given REST method on a microservice with `@Secured` annotations. I now get a server 500 error with a stack trace saying the REST call is unauthorized. 

Ideally, I'd like the internal REST call to happen on behalf of the user calling the first method. 

```
2017-07-26 11:36:17.662 DEBUG 8491 --- [  XNIO-2 task-6] c.d.m.w.rest.errors.ExceptionTranslator  : An unexpected error occurred: status 403 reading MyDemoMicroService2Client#getStringSecured(); content:
{
  "message" : "error.accessDenied",
  "description" : "Access is denied",
  "fieldErrors" : null
}

feign.FeignException: status 403 reading MyDemoMicroService2Client#getStringSecured(); content:
{
  "message" : "error.accessDenied",
  "description" : "Access is denied",
  "fieldErrors" : null
}
    at feign.FeignException.errorStatus(FeignException.java:62)
    at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91)
    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
    at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
    at com.sun.proxy.$Proxy120.getStringSecured(Unknown Source)
    at com.demo.microservice1.web.rest.DemoResource.getStringSecured(DemoResource.java:54)
```

##### **Motivation for or Use Case**

I wanted to use the AuthorizedFeignClient because I have  use-case where one microservice needs to talk to another in the background to perform an operation. It seems like a straight-forward use-case. 

##### **Reproduce the error**

The following GitHub repos duplicate the problem:

- https://github.com/dapperdanman/MyDemoRegistry
- https://github.com/dapperdanman/MyDemoUAA
- https://github.com/dapperdanman/MyDemoGateway
- https://github.com/dapperdanman/MyDemoMicroservice1
- https://github.com/dapperdanman/MyDemoMicroservice2

I used the Swagger UI in a browser to GET from `http://localhost:8080/mydemomicroservice1/api/demo/secured/string2`

##### **Related issues**

unknown

##### **Suggest a Fix**

unknown

##### **JHipster Version(s)**

4.5.5

This is the first time I've tried to do this.

##### **JHipster configuration**

See linked GitHub repos above that duplicate the issue.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no entities yet

##### **Browsers and Operating System**

Firefox on Linux and Windows 7

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Thanks for the well written report with demo project. 
Ping @xetys.

**Comment by xetys** [comment]
first point here is, `@Secured` is used to be in conjunction with roles, while authorized Feign clients are using client credential based clients, which currently only have scopes. 

The other point is, that indeed `@Secured("ADMIN")` doesn't work, while `@PreAuthorize("hasRole('ROLE_ADMIN')")` does work. This is a bug from Spring security.

**Comment by xetys** [comment]
p.s.

try `@PreAuthorize("authenticated()")` instead of `@Secured`

**Comment by dapperdanman** [comment]
What username/credentials are the authorized Feign clients using? jhipster.security.client-authorization.client-id=internal?

**Comment by dapperdanman** [comment]
Also, I would prefer that the microservice-to-microservice connection be done on behalf of the user making the original request on microservice1. Should I continue to use a Feign client, or use another technique (RestTemplate?)

**Comment by cbornet** [comment]
@dapperdanman you should be able to relay the token with a Feign request interceptor from your OAuth2ClientContext

**Comment by dapperdanman** [comment]
@xetys I tried using @PreAuthorize and I couldn't get it to work. See my https://github.com/dapperdanman/MyDemoMicroservice2 demo project.

**Comment by dapperdanman** [comment]
@cbornet I'm new to Spring and JHipster, so I don't know how to do what you suggest with the request interceptor. Would you be willing to make the changes in my project on Github, or make a pull request?

**Comment by deepu105** [comment]
This doesn't seem like a bug or feature request to me. @PierreBesson @xetys @cbornet please reopen if you think otherwise

**Comment by dapperdanman** [comment]
I'm not sure what is is either, but the code generated by JHipster does not seem to work for Role based access for URL's. Maybe it is a Spring bug or not I don't know. I don't know enough about Spring yet to work around the issue or offer a suggestion. 

In my own investigations, I can't figure out how to use plain RestTemplate's either. My current plan is to go back to a pure JWT solution and try to get that to work.

**Comment by Tcharl** [comment]
I maybe wrong, but [this article](https://jmnarloch.wordpress.com/2015/10/14/spring-cloud-feign-oauth2-authentication/) could help
