### ISSUE TITLE
Update entity  using sub-generator break liquibase checksum

### ISSUE THREAD

**Issue by freemanpolys** [jhipster/generator-jhipster#6176]
##### **Overview of the issue**
The jdl sub-generator update liquibase xxx_added_entity_zzzz.xml file when changing entity field type. This breaks liquibase versioning checksum so database update fails.
```

ready: Validation Failed:
     1 change sets check sum
          classpath:config/liquibase/changelog/20170724170916_added_entity_Transaction.xml::20170724170916-1::jhipster was: 7:35080fe5018db314e32723780afb33fc but is now: 7:a03e3f8a8aa39ab7bdd0b126e0acc40a


liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          classpath:config/liquibase/changelog/20170724170916_added_entity_Transaction.xml::20170724170916-1::jhipster was: 7:35080fe5018db314e32723780afb33fc but is now: 7:a03e3f8a8aa39ab7bdd0b126e0acc40a
```

##### **Motivation for or Use Case**
The db need to be deleted

##### **Reproduce the error**

Create jdl entity, import it with the sub-generator. Update one field in the jdl, use the sub-generator to import it again.
##### **Suggest a Fix**
Create new changeset file for every update.

##### **JHipster Version(s)**
generator-jhipster@4.6.1

**Comment by jdubois** [comment]
Did you read the documentation? Once it's generated you can use the Maven Liquibase goal.
If you re-generate, nothing is magical.

**Comment by pascalgrimaud** [comment]
Related to this ticket: https://github.com/jhipster/generator-jhipster/issues/5954
@gimoh already started the work here: https://github.com/jhipster/generator-jhipster/pull/6016

**Comment by freemanpolys** [comment]
Great.
Good job guys!

**Comment by Jonas3ap** [comment]
Did you read the documentation? Once it's generated you can use the Maven Liquibase goal.
If you re-generate, nothing is magical.

Which goal exactly?
