### ISSUE TITLE
aws beanstalk http 404 

### ISSUE THREAD

**Issue by dllongo** [jhipster/generator-jhipster#6186]
##### **Overview of the issue**
I generate an app using latest version of jhipster and deploy on aws elastic beanstalk using default java config, accessing the url result on http 404, api request works fine.
Running the prod profile on my machine everything works fine.

log of application when access '/'

https://pastebin.com/U2FrvPrp

nginx log:
`189.54.144.44 - - [01/Aug/2017:02:47:29 +0000] "GET / HTTP/1.1" 404 1307 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8" "-"
`
jhipster info:

`Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
testeapp-2@0.0.0 /Users/longo/dev/workspaces/workspace_diz/testeapp2
└── generator-jhipster@4.6.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.test",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "testeapp2",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.11.0 (Apple Git-81)

node: v6.10.0

npm: 3.10.10

bower: 1.8.0

gulp:
[23:59:31] CLI version 1.3.0

yeoman: 2.0.0

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.14.0, build c7bdf9e

Execution complete`

##### **Reproduce the error**
Generate app, deploy on aws beanstalk using java config.

##### **Browsers and Operating System**

I test on all OS with chrome and safari.
- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Have you tried to get a static resource (image, css, index.html) rather than only `/`?

**Comment by dllongo** [comment]
Hi @gmarziou, yes I tried with static resources, the same error appear, here is the log for index.html
https://pastebin.com/KyWyfgnb

**Comment by gmarziou** [comment]
What about my other suggestions, especially the diff between local and aws logs?

**Comment by dllongo** [comment]
running local with eclipse the log is different:
https://pastebin.com/GGqgYL4e

and with java -jar 
https://pastebin.com/XNix1MU7

it's appear following a different checkers on request chain.

**Comment by gmarziou** [comment]
Can't you post the diff output?

**Comment by deepu105** [comment]
@dllongo please post diff of both log output. You cant expect us to spend time comparing the logs its not interesting for anyone to spend a weekend on

**Comment by dllongo** [comment]
@gmarziou sorry for my late response, here's the diff:
https://www.diffchecker.com/tC6u1IEB
on the left app run ok, on right side I get 404

**Comment by gmarziou** [comment]
But this is only the log of the request processing, I think you should better at the app startup when everything gets configured because here you can see that on left side there are 14 filters  and on the right side only 12.

**Comment by gmarziou** [comment]
You may have also noted that only the right side shows thymeleaf log statements.

**Comment by dllongo** [comment]
Here a full diff using a tomcat at localhot to compare:
https://www.diffnow.com/?report=s92fn
@gmarziou yes only right has thymeleaf, but I think this log has relation with the "/error" request.

**Comment by jdubois** [comment]
I'm sorry but we only support applications deployed using [our sub-generator](https://jhipster.github.io/aws/).

As you are talking about NGinx and sending your logs, it looks like you did your own configuration here -> this is a configuration question that should go to StackOverflow, not a bug report on our sub-generator.
