### ISSUE TITLE
Blank Screen after deployed to Heroku

### ISSUE THREAD

**Issue by SheikhZayed** [jhipster/generator-jhipster#6189]
I have created a simple app with one entity in jhipster,which works fine in my local machine.After deploying it to heroku I just get a blank screen without any contents.though the title of the page and favicon gets displayed properly.
This is my Heroku App
https://tool-box-api.herokuapp.com/

Heroku logs are normal and doesnt show any error message,since the app is up and running .. please look into this.

Jhipsterinfo command output = 
> Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
tool-box-api@0.0.0 /home/techjini/Desktop/ToolBoxAppAdmin
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitHubOrganization": "SheikhZayed",
    "baseName": "ToolBoxAPI",
    "packageName": "io.github.ashif",
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "enableTranslation": false,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientFramework": "angularX",
    "jhipsterVersion": "4.6.2",
    "packageFolder": "io/github/ashif",
    "jwtSecretKey": "replaced-by-jhipster-info",
    "jhiPrefix": "jhi"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Product (product) {
  name String,
  amount Integer,
  image String,
  discount Long
}

paginate Product with pagination
service Product with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.7.4

node: v8.2.1

npm: 5.3.0

bower: 1.8.0

gulp:
[11:47:49] CLI version 1.2.2

yeoman: 2.0.0

yarn: 0.27.5

**Comment by pascalgrimaud** [comment]
Really hard to help with only these infos.

Can you post (check if there are personnal information before posting here):
- all your stacktrace when using Heroku generator
- all heroku logs

As you used MySQL, see the comment [here](https://github.com/jhipster/generator-jhipster/issues/5510#issuecomment-290230397) :
> I think I figured out the reason. My credit card was not verified on heroku. Without credit card information heroku does not allow the installation of JawsDB MySQL add-on. After verification, I deployed it again. And now it is working fine.

Did you add this?

**Comment by SheikhZayed** [comment]
@pascalgrimaud I have my credit card verified by heroku and have other spring boot rest api's running with them..what more info do you need,so that i can help you with this..?

**Comment by deepu105** [comment]
Provide the logs from Jhipster heroku command. It should have build your app with prod profile successfully

**Comment by SheikhZayed** [comment]
@deepu105 I had an issue deploying with "jhipster heroku" command which throwed me "java.lang.RuntimeException: Could not get API key! Please install the toolbelt and login with `heroku login` or set the HEROKU_API_KEY environment variable."
after a  quick google search on this,i came to know that this is a bug on heroku ..

so I have deployed the app directly from the dashboard by connecting it to my git branch

**Comment by deepu105** [comment]
Ok I didn't get it. It works for us, so if you think yiu are facing some heroku bug then ill close this as there is nothing we can do here

**Comment by SheikhZayed** [comment]
:+1:

**Comment by pascalgrimaud** [comment]
If you launch in local:
- be sure you are logged to Heroku, with `heroku login`

If you want to deploy with Travis or another continuous integration tool:
- be sure the HEROKU_API_KEY is set (see https://jhipster.github.io/setting-up-ci/)

**Comment by SheikhZayed** [comment]
@pascalgrimaud logged in with heroku,still it fails.As of now no CI tools
