### ISSUE TITLE
JDL Import with microservices options don't create the tables for the gateway

### ISSUE THREAD

**Issue by setterlee** [jhipster/generator-jhipster#6193]
##### **Overview of the issue**

I'm using a sample model to test the microservices options defining one table for the gateway a two more tables for two microservices but the jdl import don't create the gateway tables and create all tables in the microservices

the model:

`entity Car{
	name String required
	color Color
}

enum Color{
	BLACK,WHITE,BLUE,GREEN,YELLOW
}

entity House{
	address String required
}

entity Info{
	phone String required
}

relationship OneToOne{
	Info{user(login) required} to User
}

microservice Info with gateway
microservice Car with app1
microservice House with app2
search * with elasticsearch
`

##### **Motivation for or Use Case**

I follow the documentations indications but the importer don't build entities in the right place  

##### **Reproduce the error**

first create a gateway project:

$: mkdir gateway && cd gateway && yo jhipster
$: yo jhipster:import-jdl model.jdl

then create the app1

$: mkdir app1 && cd app1 && yo jhipster
$: yo jhipster:import-jdl model.jdl

and then the app2:

$: mkdir app2 && cd app2 && yo jhipster
$: yo jhipster:import-jdl model.jdl

all with the same model described before

##### **JHipster Version(s)**

Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/setterlee/Development/labs/test/gateway
└── generator-jhipster@4.6.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "cl.stechsolutions.lab.jhipster",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "gateway",
    "packageName": "cl.stechsolutions.lab.jhipster",
    "packageFolder": "cl/stechsolutions/lab/jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Car (car) {
  name String required,
  color Color
}
entity House (house) {
  address String required
}
entity Info (info) {
  phone String required
}

enum Color {
  BLACK,
  WHITE,
  BLUE,
  GREEN,
  YELLOW
}

relationship OneToOne {
  Info{user(login) required} to User
}

search Car with elasticsearch
microservice Car with app1
search House with elasticsearch
microservice House with app2
search Info with elasticsearch
microservice Info with gateway

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

git version 2.11.0 (Apple Git-81)

node: v8.2.1

npm: 5.3.0

bower: 1.8.0

gulp:
[16:54:02] CLI version 1.3.0

yeoman: 2.0.0

yarn: 0.27.5

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.14.0, build c7bdf9e

Execution complete

##### **Browsers and Operating System**

Mac OS Sierra and Safari

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
The gateway isn't a microservice, so just remove `microservice Info with gateway` from your JDL.  

If you still have issues after that, please fill out the complete template.

**Comment by setterlee** [comment]
I just remove the line for the gateway and the table `Info` appear in the changelog Folder but in the microservices app1 and app2 still appear all tables including `Info`

**Comment by setterlee** [comment]
Here the json files generated in every application

[json files.zip](https://github.com/jhipster/generator-jhipster/files/1195327/json.files.zip)

**Comment by ruddell** [comment]
So the issue looks like it's not possible to specify in JDL that an entity belongs on a gateway.

We could check if the gateway's name matches the entity's microserviceName and then generate the backend as well.  I haven't looked at the code to see how easy this is but I'm guessing that's how it works with microservices

**Comment by setterlee** [comment]
No just that, the importer are building the entire  JDL model in every microservice

**Comment by setterlee** [comment]
I guess that this model with all entities just must be used to generate the gateway project and for the microservices must be used a simplified model just with they own tables.

If this is right, maybe this tips must be included in the JDL docs [here](https://jhipster.github.io/jdl/#microserviceoptions)

**Comment by PierreBesson** [comment]
Yes @setterlee, the way it works is not what you thought. When importing a jdl in an app it generates all entities described in the JDL file. The `microservice` option is merely hints that is effective when generating entities on a gateway app.

**Comment by setterlee** [comment]
oh! thanks @PierreBesson. In that case, this is not a issue and must be closed.
