### ISSUE TITLE
[FEATURE] Migrate from spotify's deprecated docker-maven-plugin to new dockerfile-maven-plugin

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#6194]
##### **Overview of the issue**

Spotify has "deprecated" their docker-maven-plugin which should be replaced with the new dockerfile-maven-plugin. So I suggest we migrate to this new plugin.
This is going to have a minimal impact on the projects as we were already using the dockerfile workflow to build docker images.

See: https://github.com/spotify/docker-maven-plugin#the-future-of-docker-maven-plugin

##### **Motivation for or Use Case**

- Keep up to date with upstream docker-maven-plugin which seems to not be maintained anymore.
- Benefit from better caching

Note: the command to build docker images will change from `mvn docker:build` to `mvn dockerfile:build`.

##### **JHipster Version(s)**

v4.6.2

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
+1
@PierreBesson do you want to do this ?

**Comment by PierreBesson** [comment]
@pascalgrimaud Yes I will do it in the coming days.

**Comment by pascalgrimaud** [comment]
There are 3 tasks:
- change the lib here, in the generator-jhipster
- change the lib in jhipster-registry
- update the documentation

**Comment by agoncal** [comment]
Have you considered the [fabric8io/docker-maven-plugin](https://dmp.fabric8.io/) ? It's quite rich actually (but maybe too rich for your usecase).

**Comment by PierreBesson** [comment]
@agoncal I did have a look to the fabric8 plugin when I initially added docker support and evaluated the different docker plugins. However it was more complicated to setup and had fewer stars than spotify's one at the time.

I'm really satisfied with spotify's plugin and the new dockerfile plugin is even better. I would stick with it for the time being. 

The fabric8 plugin has a lot of additional lot to start/stop containers, create volumes etc. but I'm not interested in those as I would prefer to use the `testcontainers` library for this use case rather than a maven plugin.
