### ISSUE TITLE
CLI should run local generator-jhipster rather than global one

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#6208]
##### **Overview of the issue**

`jhipster` command runs globally installed generator-jhipster rather than project locally installed generator-jhipster. `yo jhipster` works as expected.

I tested only on Windows 10, not sure this is the same for other OS.

I'm not sure this happens also for npm.

The steps to reproduce are rather easy.

Maybe this is something specific to my environment but it explains why I could not get rid of the tabtab error.

##### **Motivation for or Use Case**

This could impact 2 kinds of users:
- JHipster developers or advanced users who use master and `yarn link`.
- users who run different versions of JHipster in different projects

##### **Reproduce the error**

- Install generator-jhipster 4.6.1 globally `yarn global add generator-jhipster@4.6.1`
- in a project, install generator-jhipster 4.6.2 locally with `yarn add generator-jhipster@4.6.2`
- execute `jhipster`, it will print 4.6.1 
- execute `yo jhipster`, it will print 4.6.2 

In my environment, `jhipster.CMD` is located in `C:\Users\Gaël\AppData\Local\Yarn\config\global\node_modules\.bin` folder.

It runs `C:\Users\Gaël\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\cli\jhipster.js`

It should run the project's local version of generator-jhipster, in my case `e:\projets\issues\clarity\node_modules\generator-jhipster\cli\jhipster.js`

##### **Suggest a Fix**

jhipster command points to `C:\Users\Gaël\AppData\Local\Yarn\bin\jhipster.CMD`
~~~
@"%~dp0\..\config\global\node_modules\.bin\jhipster.cmd"   %*
~~~
which points to `C:\Users\Gaël\AppData\Local\Yarn\config\global\node_modules\.bin\jhipster.cmd`
~~~
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\generator-jhipster\cli\jhipster.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\generator-jhipster\cli\jhipster.js" %*
)
~~~

`%~dp0` always point to global directory.

The test on node.exe existence will never be true for yarn on Windows.

All the node commands I checked are written the same way, so this is quite strange.

##### **JHipster Version(s)**

I suppose since CLI was introduced.

##### **Environment and Tools**

java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

git version 2.12.0.windows.1

node: v6.11.1

npm: 3.10.10

gulp:
[01:11:10] CLI version 1.4.0

yeoman: 2.0.0

yarn: 0.27.5

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.14.0, build c7bdf9e3

##### **Browsers and Operating System**

Windows 10 Pro.

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I could reproduce this on Mac, the CLI uses the global version even when a local version is installed.

```
mkdir cli-test && cd cli-test
npm install generator-jhipster@4.0.0
jhipster
# the latest jhipster version runs
yo jhipster
# the local jhipster version runs
```

**Comment by gmarziou** [comment]
Thanks, I was starting to think I was alone.

To me this script should use current directory as `%CD%` on Windows and `$PWD` on Mac and Linux.

**Comment by deepu105** [comment]
That script is generated right? I mean we dont create that. Do you guys see
same behaviour with other CLI tools like angular CLI etc?

**Comment by ruddell** [comment]
@deepu105 With the Angular CLI I see the expected behavior, it looks like they compare versions [here](https://github.com/angular/angular-cli/blob/f1251bfb4d4d1ac97d92e4c3da2eb8de67776437/packages/%40angular/cli/bin/ng#L149-L165).
```
Your global Angular CLI version (1.2.7) is greater than your local
version (1.2.0). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
```

**Comment by deepu105** [comment]
May be we could do the same

**Comment by gmarziou** [comment]
gulp does also something similar to angular cli, it's good we can fix this in the JS code rather than in shell.
This bug could also explain why upgrade may fail depending on whether cli was used or yo.

I can work on it at the end of the week.

**Comment by tientq** [comment]
I had to do the trick, run jhipster cli in local. Ex: `~/Documents/Project/generator-jhipster/cli/jhipster.js upgrade --with-entities --verbose` after `yarn link`.

**Comment by gmarziou** [comment]
I did not implement angular-cli's version comparison because I think we should always respect the local version in the project because we already warn the user when there is a more recent version available.

The only exception to this rule might be for except for `jhipster upgrade` where we would like to have the most recent version most of the time, so I prefer to fix this issue and open another one for upgrade.

**Comment by deepu105** [comment]
We need not compare but we could add atleast a debug log printing which CLI
is being used

**Comment by gmarziou** [comment]
Well, I thought we would do the same as `yo jhipster`, no surprise to the user but I can add a log.
