### ISSUE TITLE
Data URLs removed in Chrome

### ISSUE THREAD

**Issue by eosimosu** [jhipster/generator-jhipster#6209]
##### **Overview of the issue**
Latest version of Chrome blocks web pages from loading Data URLs. It means I'm no longer able to open Blob such as pdf. It works fine in other browsers.

More info: 
[https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM)

##### **Reproduce the error**
Generate a new app, create a entity with field type TextBlob, upload a pdf file and attempt to open it.

##### **Suggest a Fix**
My workaround is to download the file using the following snippet:

`<a *ngIf="profile.resume" [href]="sanitizer.bypassSecurityTrustUrl('data:' + profile.resumeContentType + ';base64,' + profile.resume)" target="_blank" download>open</a>`

I'm injecting `DomSanitizer` into my component class to sanitize the data url.

##### **JHipster Version(s)**
4.6.2

##### **JHipster configuration**
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "myapp"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "myapp",
    "packageName": "myapp",
    "packageFolder": "myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xx",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**
Operating system: macOs 10.12.4
Browser: Chrome Version 60.0.3112.90 (Official Build) (64-bit)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Closing as https://github.com/jhipster/ng-jhipster/pull/47 is merged
