### ISSUE TITLE
Security Issue in User List

### ISSUE THREAD

**Issue by uyeliksiz** [jhipster/generator-jhipster#6212]
##### **Overview of the issue**

Any user can see all users with user data

##### **Motivation for or Use Case**

User datas have to be secured and hidden.

##### **Suggest a Fix**

**UserResource.java**

```
    @GetMapping("/users")
    @Timed
    public ResponseEntity<List<UserDTO>> getAllUsers(@ApiParam Pageable pageable) {
```

```
    @GetMapping("/users/{login:" + Constants.LOGIN_REGEX + "}")
    @Timed
    public ResponseEntity<UserDTO> getUser(@PathVariable String login) {
```

make these methods  secured.

##### **JHipster Version(s)**

4.6.2

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Duplicate...
