### ISSUE TITLE
JHipster module hooks error

### ISSUE THREAD

**Issue by henkelb** [jhipster/generator-jhipster#6218]
##### **Overview of the issue**

I have a jhipster [project ](https://github.com/henkelb/jhipster-project-demo) for whom I installed some jhipster modules (yeoman generators) that should behave as post-entity hooks. One of the jhipster modules is not created by me (the other one for which i am receiving the error too is create by me), it is actually [jhipster-entity-audit](https://github.com/hipster-labs/generator-jhipster-entity-audit). 

When I run the jdl importer, as new entities are being created, I am expecting to see jhipster-entity-audit (and the other one) executing for each newly created entity as it should behave as a post entity hook. Instead, I am receiving this output, for each entity:
https://i.stack.imgur.com/iqVv4.png
![image](https://user-images.githubusercontent.com/8615775/29215430-a3a7e068-7eb3-11e7-9f04-e72936ff9a76.png)

I do mention that I created myself a generator to prove that the problem is not just with  [jhipster-entity-audit](https://github.com/hipster-labs/generator-jhipster-entity-audit). 

##### **Motivation for or Use Case**
This impacts developers and other existing modules that need to be ran mandatory after entity creation.

##### **Reproduce the error**
- clone the above project
`git clone https://github.com/henkelb/jhipster-project-demo.git`
- to add the generator created for me run
`yarn add https://github.com/henkelb/generator-jhipster-hook-test `
- to force (re)creation of new entities to see the same output
`jhipster import-jdl jhipster-jdl.jh --force`

##### **JHipster Version(s)**
4.6.2

##### **JHipster configuration**
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
absence-management@0.0.0 D:\data\git-repos\a-new-jhip-proj
+-- generator-jhipster@4.6.2
`-- generator-jhipster-entity-audit@2.5.0
  `-- generator-jhipster@4.6.2  deduped

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.crispico.absence_management",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "absence_management",
    "packageName": "com.crispico.absence_management",
    "packageFolder": "com/crispico/absence_management",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "jhiPrefix": "jhi"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * <jhipster-entity-replacer>
 * replacer.insertElement("aboove classe");
 * </jhipster-entity-replacer>
 */
entity Blog (blog) {
  name String required minlength(3),
  handle String required minlength(2)
}
/**
 * <jhipster-entity-replacer>
 * replacer.replaceRegexWithCurlyBraceBlock("\\s*?(?:@Override)?\\s*public boolean equals\\(\\w+ \\w+\\)");
 * </jhipster-entity-replacer>
 */
entity Entry (entry) {
  title String required,
  content byte[] required,
  date ZonedDateTime required
}
entity Berry (berry) {
  title String required,
  content byte[] required,
  date ZonedDateTime required
}
entity Cherry (cherry) {
  title String required,
  content byte[] required,
  date ZonedDateTime required
}
entity Category (category) {
  /**
   * <jhipster-entity-replacer>
   * replacer.replaceRegex("@Id[\\s\\S]*?;", "");
   * replacer.storeReplacements("defaultAbstractEntity",
   * function(replacer) {
   * replacer.replaceRegex("@Override\\s*public int hashCode\\([\\s\\S]*?\\)\\s*{[\\s\\S]*?}\\s*(?=[\\w\\W])", "")
   * }
   * );
   * replacer.insertElement('@Named');
   * </jhipster-entity-replacer>
   */
  name String required minlength(2)
}
entity Tag (tag) {
  /**
   * <jhipster-entity-replacer>replacer.applyStoredReplacements("defaultAbstractEntity");
   * replacer.insertElement("@Named"); </jhipster-entity-replacer>
   */
  name String required minlength(2)
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Entry{blog(name)} to Blog
}
relationship ManyToMany {
  Entry{tag(name)} to Tag{entry}
}

paginate Entry with infinite-scroll
paginate Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

git version 2.7.1.windows.2

node: v6.11.1

npm: 5.3.0

bower: 1.7.7

gulp:
[16:31:23] CLI version 3.9.1

yeoman: 2.0.0

yarn: 0.27.5

Execution complete

##### **Browsers and Operating System**

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Have you tried with `yo` rather than the CLI?

`yo jhipster import-jdl jhipster-jdl.jh --force`

**Comment by deepu105** [comment]
You need to install the modules locally in the project where you are
executing it. Yeoman changed the way generators are composed. Please
install the the modules locally and try again

**Comment by henkelb** [comment]
deepu105 , just having the modules installed locally did not make any difference.
It worked with the command `yo jhipster:import-jdl jhipster-jdl.jh --force ` as gmarziou indicated, regardless whetther the modules were installes locally or not.
Although I do not understand why this solution works if i have the modules installed globally, for example.
I looked to what the cli command points and it points to executing generator-jhipster/cli/cli.js
By running  `yo jhipster:import-jdl jhipster-jdl.jh --force ` don't we get to execute the same thing?

Thank you very much for your prompt answer. Sorry for my lateness, here, in Romania, we had some national free days.

**Comment by deepu105** [comment]
I need to check this. This was working for me not sure what going wrong for you.

**Comment by deepu105** [comment]
Tests:

- [ ] 1. No global module. Install locally for the project only, with entity hook
- [ ] 2. Only global module, with entity hook

**Comment by AdrienHorgnies** [comment]
**Happy to see this issues was fixed !** Anyway, I've done some search and here is the result :

I've just tested with **4.6.2** and I don't have this problem anymore while I had it with my module a while back :
https://github.com/bastienmichaux/generator-jhipster-db-helper/issues/46 . So I can confirm this issue ran for **4.5.6**.

The option `--force` is used by `import-jdl` here and I don't quite understand what it does as I wasn't able to find `exportToJSON` in jhipster-core (**help?**) :
```javascript
this.changedEntities = jhiCore.exportToJSON(entities, this.options.force);
```

Anyway, I can see that it passes the option to the entity generator :
```javascript
this.composeWith(require.resolve('../entity'), {
                            force: this.options.force, // <===== HERE
                            regenerate: true,
                            'skip-install': true,
                            'skip-client': entity.definition.skipClient,
                            'skip-server': entity.definition.skipServer,
                            'no-fluent-methods': entity.definition.noFluentMethod,
                            'skip-user-management': entity.definition.skipUserManagement,
                            arguments: [entity.name],
                        });
```

The entity generator :
* skips questions if option `--force` is set
* and in turn, **passes the option to his hooks**
```javascript
this.callHooks('entity', 'post', {
   entityConfig,
   force: this.options.force
}, done);
```

So I suppose it is possible that **generator-jhipster-entity-audit** interprets the option and do special things (I don't have time right now to check his source code, anyway @deepu105 is the right person to tell us that). As for my module, `generator-jhipster-db-helper`, it does interpret `--force` and skips questions if configuration files are satisfactory.

**Comment by deepu105** [comment]
Everything works fine in master. I have released new version for the
entity-audit module and a new Jhiptser version will be released soon


Thanks & Regards,
Deepu
