### ISSUE TITLE
Typo in _Jenkinsfile , non Yarn deployment

### ISSUE THREAD

**Issue by jakubstrama** [jhipster/generator-jhipster#6222]
##### **Overview of the issue**
There is most likely a typo in 
_/generators/ci-cd/templates/jenkins/_Jenkinsfile 
Lines: 81-83. A _yarn_ argument is being used instead of _npm_ argument. 

##### **Motivation for or Use Case**

Brakes the non Yarn Jenkins deployment, 
`frontend-maven-plugin:npm -Dfrontend.yarn.arguments=test`
resolves to `npm install` instead of `npm test`

##### **Reproduce the error**

Deploy with Jenkins without Yarn

##### **Suggest a Fix**

change to:

`./mvnw com.github.eirslett:frontend-maven-plugin:npm -Dfrontend.npm.arguments=test
`

##### **JHipster Version(s)**
4.6.2

##### **JHipster configuration**

Executing jhipster:info
Options: 
##### **JHipster Version(s)**

```
leavemyride@0.0.0 /Users/jakubstrama/dev/leavemyride
└── generator-jhipster@4.6.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.leavemyride",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "leavemyride",
    "packageName": "com.leavemyride",
    "packageFolder": "com/leavemyride",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de",
      "pl"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

git version 2.8.4 (Apple Git-73)

node: v7.7.1

npm: 4.1.2

yeoman: 2.0.0

Docker version 1.12.1, build 23cf638

Execution complete

[yo-rc.txt](https://github.com/jhipster/generator-jhipster/files/1220504/yo-rc.txt)

##### **Browsers and Operating System**

- [v] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Thanks, would you please consider submitting a pull request?

**Comment by jakubstrama** [comment]
Hi, I do not have the code base checked out at the moment, just went through the github page quickly.

**Comment by gmarziou** [comment]
There's no emergency
