### ISSUE TITLE
Upgrade ng-bootstrap and bootstrap depedency

### ISSUE THREAD

**Issue by liaoyunhe** [jhipster/generator-jhipster#6225]
##### **Overview of the issue**
 Bootstrap released beta : https://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/ 
 Ng Bootstrap release beta: https://github.com/ng-bootstrap/ng-bootstrap/issues/1679

##### **Motivation for or Use Case**
Upgrade to latest Bootstrap 4 Beta Release

N/A
##### **Reproduce the error**
N/A

N/A
##### **Related issues**
N/A

N/A
##### **Suggest a Fix**
N/A

##### **JHipster Version(s)**
4.6.2

N/A
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Yes Im aware and will be done eventually. If you want you can try to PR this
I'm closing the ticket as this will be done like every other dependencies
