### ISSUE TITLE
how to get real userName  rather than `internal`

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#6227]
##### **Overview of the issue**

req->microService1's uri->invoke mecroService2's uri.

microService1's method use SecurityUtils.getCurrentUserLogin() to get real userName(e.g. admin).

but mecroService2 use SecurityUtils.getCurrentUserLogin() got the userName is `internal`?

##### **Motivation for or Use Case**

I print the mecroService all headers.

mecroService1's headers
```
Accept:[*/*]
x-forwarded-proto:[http]
User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3178.0 Safari/537.36]
Connection:[Keep-Alive]
Referer:[http://localhost:8080/swagger-ui/index.html]
x-forwarded-port:[8080]
Host:[localhost:8081]
Accept-Encoding:[gzip]
DNT:[1]
x-forwarded-for:[0:0:0:0:0:0:0:1]
authorization:[Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDI3MzU1ODcsInVzZXJfbmFtZSI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJqdGkiOiIwOGI4YzhmZi0wYjRmLTQ4ZGQtYTk3Zi0yNmI2NzYyMWViMDAiLCJjbGllbnRfaWQiOiJ3ZWJfYXBwIiwic2NvcGUiOlsib3BlbmlkIl19.G5ELVazqsof6sAruhXvkJUl9Sqy_g9l_F-luiD7eXDy_I-V2-qNkADIx6ZDgN6-fXR_kpg6IlX8zL05CwG_moqWNibp3FWvYrAWOJ47xCAN9MZ86DwPFFpsI4Yb9iMug_v0bN1uWOIDz5vZ_LrYs1xhBTa0Wuq2ck3adqLu3Ts_ddUM2wEdvNzZx7m_J5VcCcE3TZ9i5gi4ctHk3StpfPHh1MsiWOAWbrAvfrzNXaL3P79NfU44mtDATFypgr1PDDEBAyx_1sNZ3lnkhqrrroV8cI0SVLxFZ7NH9LT8QCKsrfcmZUwhAgGU90s7WbDAFDfK_97fOrjoicaJspziAhg]
x-forwarded-host:[localhost:8080]
x-forwarded-prefix:[/foo]
Accept-Language:[zh-CN,zh;q=0.8]
Content-Length:[0]
```
expand accessToken,the payload data like

```javascript
{
  "exp": 1502735587,
  "user_name": "admin",
  "authorities": [
    "ROLE_ADMIN",
    "ROLE_USER"
  ],
  "jti": "08b8c8ff-0b4f-48dd-a97f-26b67621eb00",
  "client_id": "web_app",
  "scope": [
    "openid"
  ]
}
```

mecroService2's headers
```
Authorization:[Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJ3ZWItYXBwIl0sImV4cCI6MTUwMjczNzk5NiwianRpIjoiN2MxZmYwMTYtOWZjYi00NjNhLWFlZTctZGExYTM2NThhOGFkIiwiY2xpZW50X2lkIjoiaW50ZXJuYWwifQ.cIVLuQ5CplHwMXcR7VBvl7Ovu74IY1ltvtHaCNcfdg1tlyJqXR5AnwTSWW_RaPmTlgzG9bKrWgQW5KCKav1k_IewXqVcqb80x3itg4todGiWzQXuVhRwG7kpNUvK-VWkf6sXRzUKSWSjSG7kX7P5Gs9ShbgPBj2f_kyW5RD6F432fkcaalUIBJyz6vsAomWyN2jN4iMJIjwbcHezSYXr2yexS_P8LElGjYPB77-JBc77A2HySjZRy6-u4W3vfsOckhb3unVZI8enj1lBjavdMhdVVdaXrX0KrpXn8VE-YP28dqXiEoeg5nbIVTRUht9rlIz7iiIo4gA9l2sKsT4UsQ]
Accept:[application/json]
Connection:[keep-alive]
User-Agent:[Java/1.8.0_121]
Host:[127.0.0.1:8081]
```
 expand accessToken,the payload data like 
```javascript
{
  "scope": [
    "web-app"
  ],
  "exp": 1502737996,
  "jti": "7c1ff016-9fcb-463a-aee7-da1a3658a8ad",
  "client_id": "internal"
}
```

##### **Reproduce the error**

demo repo [anjia0532/fegin-internal-invoke](https://github.com/anjia0532/fegin-internal-invoke)

##### **Related issues**

https://github.com/spring-cloud/spring-cloud-netflix/issues/288

https://stackoverflow.com/questions/39606744/how-to-consume-basic-authentication-protected-restful-web-service-via-feign-clie

https://github.com/spring-cloud/spring-cloud-netflix/issues/1380

##### **JHipster Version(s)**

v4.4.1

##### **Browsers and Operating System**

OS verion :  windows 10 build 1703

chrome version : 62.0.3178.0 dev 64bit

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Many people do this, and it's a feature we should support, but at the moment we don't generate code to have a microservice call another microservice.
It's not hard to do (as you can see one small issue is the security part), it's just we haven't created the templates yet (many people in the team do this, but we need to agree on "the official way" to do it).
So at the moment it's not supported, so it's not a bug: you should use Stackoverflow (and I'm pretty sure it's already explained there).

**Comment by jdubois** [comment]
Sorry just saw your PR - are you using OAuth2??? If you don't give your full info it's hard to help you

**Comment by anjia0532** [comment]
yes,i use uaa, and i've already give the demo repo [anjia0532/fegin-internal-invoke](https://github.com/anjia0532/fegin-internal-invoke) .

>##### **Reproduce the error**

>demo repo [anjia0532/fegin-internal-invoke](https://github.com/anjia0532/fegin-internal-invoke)

**Comment by jdubois** [comment]
Yes sorry but I don't have time to read your code (I'm with my phone, with limited access) - please follow the guidelines next time

**Comment by anjia0532** [comment]
@jdubois recommend a github mobile app (not official)，named FastHub.

**Comment by gmarziou** [comment]
FastHub won't work for me as it is only for Android

**Comment by anjia0532** [comment]
yup

> FastHub the ultimate GitHub client for Android.

but ,You know that's not the point!   : )
