### ISSUE TITLE
unable to bind data in angular with jhipster project

### ISSUE THREAD

**Issue by amirensit** [jhipster/generator-jhipster#6230]
I have generated jhipster project. I use several entities among them ContratEntity and VoitureEntity.

I used JDL STUDIO.

My problem is that i tried to add some modification in contrat-dialog.component.html.

As verification, I tried to show in console the value of my parameter, but It can't bind data.

> ERROR TypeError:_co.contrat.voiture is undefined

**[contrat.component.html]** 

 `<form name="editForm" role="form" novalidate #editForm="ngForm">
   ...
   <div class="form-group">
                    <label class="form-control-label" jhiTranslate="assistanceApp.voiture.immatriculation" 
       for="field_immatriculation">Immatriculation</label>
                    <input type="text" class="form-control" name="immatriculation" id="field_immatriculation" 
       [(ngModel)]="contrat.voiture.immatriculation"
                         required pattern="\d{4}TU\d+" />
      </div>
      <button type="button"  class="btn btn-primary" 
      (click)="addVoitureToContrat()" >
                    ADD
                </button>
     </form>`

**[contrat.component.ts]**

import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Response } from '@angular/http';

import { Observable } from 'rxjs/Rx';
import { NgbActiveModal, NgbModalRef } from '@ng-bootstrap/ng-
bootstrap';

import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { Contrat } from './contrat.model';
import { ContratPopupService } from './contrat-popup.service';
import { ContratService } from './contrat.service';
import { Voiture, VoitureService } from '../voiture';
import { Assuree, AssureeService } from '../assuree';
import { RefPack, RefPackService } from '../ref-pack';
import { RefCompagnie, RefCompagnieService } from '../ref-compagnie';
import { VoiturePopupService } from '../voiture/voiture-
popup.service';
import { ResponseWrapper } from '../../shared';
import { RefMarque, RefMarqueService } from '../ref-marque';

@Component({
selector: 'jhi-contrat-dialog',
templateUrl: './contrat-dialog.component.html',
styleUrls: [
    'contrat-dialog.css'
]
})
export class ContratDialogComponent implements OnInit {

contrat: Contrat;

addVoitureToContrat()
{
  console.log(this.contrat.voiture);
}

**Comment by jdubois** [comment]
In you original text (before editing it) you referenced a Stackoverflow question, can you link to it again ?

**Comment by amirensit** [comment]
https://stackoverflow.com/questions/45672708/unable-to-bind-data-in-angular-with-jhipster-project

**Comment by amirensit** [comment]
Unable to add here the code of contrat.component.html

**Comment by jdubois** [comment]
Sorry, but this question is the same as this ticket - please don't cross post, it's not nice for the team and for other users.

**Comment by amirensit** [comment]
I post either here either in stackoverflow ?

**Comment by gmarziou** [comment]
stackoverflow
