### ISSUE TITLE
jhipster upgrade should be verbose by default

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#6237]
##### **Overview of the issue**

Currently, there is a `--verbose` option for `jhipster upgrade`, I think it should be the default mode because it gives more information to the user about what is being done to her git repository.
Also, some operations like npm install can take long time to complete and when output is muted user has no idea whether things are running smoothly or process is hung for some reason and may never complete.
In case of failure, user may have a clue on what went wrong and maybe fix it by herself.

So, I propose:
- to set verbose mode by default
- to remove `--verbose` option and maybe to add `--silent` or `--quiet` 
- to display the exact command that is currently being executed (git, npm, yarn, ...)

**Comment by deepu105** [comment]
Ok for me

**Comment by mraible** [comment]
+1

**Comment by gmarziou** [comment]
BTW, I found that yeoman offers some logging helpers and with some color conventions for different statuses: http://yeoman.io/environment/log.js.html

I like the log.ok() method with green checkmark as it clearly states a success and still is color-blind friendly.

![2017-08-16_23h46_37](https://user-images.githubusercontent.com/361007/29386662-282baa2c-82dd-11e7-8105-361cccd8ca82.png)

**Comment by gmarziou** [comment]
Here is the output with `--silent` option:
![2017-08-18_03h25_08](https://user-images.githubusercontent.com/361007/29440417-f2ad4e80-83c4-11e7-9484-9758a7f54cc3.png)
