### ISSUE TITLE
Openshift opens 2 mongodb ports with the same name

### ISSUE THREAD

**Issue by gfouquet** [jhipster/generator-jhipster#6240]
##### **Overview of the issue**

When deploying in minishift a mongodb-based project, I get this error message : 

`The Service "jhipster-mongodb" is invalid: spec.ports[1].name: Duplicate value: "mongodb-bc"`

As a result, the mongodb container / service is not started, neither is the app.
 

##### **Motivation for or Use Case**

Deploy the project in openshift (minishift)

##### **Reproduce the error**

. Start minishift 
. Create a jhipster application which uses mongodb. Other parameters are set to default
. Create openshift configuration : `jhipster openshift`
. Build the project `./mvnw package -Pprod docker:build`
. Tag the docker image `docker tag jhipster $(minishift openshift registry)/myproject/jhipster`
. Push the image to the minishift registry `docker push $(minishift openshift registry)/myproject/jhipster`
. Deploy `..//ocp/ocp-apply.sh`

My output is : 
```
serviceaccount "jhipster" configured
Error from server (Forbidden): User "developer" cannot get securitycontextconstraints at the cluster scope
secret "ds-secret-ref" configured
deploymentconfig "jhipster-mongodb" created
The Service "jhipster-mongodb" is invalid: spec.ports[1].name: Duplicate value: "mongodb-bc"
deploymentconfig "jhipster" created
service "jhipster" created
route "jhipster" created
```

##### **Related issues**

None found

##### **Suggest a Fix**

The generated `ocp/jhipster/jhipster-mongodb.yml` file declares twice a port named "mongodb-bc".
Other db generators suggest that port 80 should be opened with the "mongodb" name.

I'll submit a pull request

##### **JHipster Version(s)**

4.6.2

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "jhipster",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "jhipster",
    "packageName": "jhipster",
    "packageFolder": "jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "appsFolders": [
      "issue-jhip"
    ],
    "directoryPath": "../",
    "monitoring": "no",
    "dockerRepositoryName": "",
    "dockerPushCommand": "docker push",
    "openshiftNamespace": "default",
    "storageType": "ephemeral",
    "registryReplicas": 2
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.11.0

node: v8.2.1

npm: 5.3.0

yarn: 0.27.5

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.8.0, build unknown

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by srinivasa-vasu** [comment]
@gfouquet - Please make sure you have the necessary privileges (may require admin) to run scc service that is required to run some of the pods. Some of the containers require custom scc becoz of the base image and 'developer' may not have sufficient privileges to run those containers. Better to run as 'admin'

**Comment by gfouquet** [comment]
@srinivasa-vasu Thanks for your feedback.

When I run as admin I get the same symptoms (minus the security constraint message) :
``` 
serviceaccount "jhipster" configured
securitycontextconstraints "jhipster-scc" configured
secret "ds-secret-ref" configured
deploymentconfig "jhipster-mongodb" created
The Service "jhipster-mongodb" is invalid: spec.ports[1].name: Duplicate value: "mongodb-bc"
deploymentconfig "jhipster" created
service "jhipster" created
route "jhipster" created
```

When I rename port 80 to "mongodb" in `ocp/jhipster/jhipster-mongodb.yml`, app starts as expected.

```
    spec:
      ports:
        -
          name: mongodb-bc
          protocol: TCP
          port: 27017
          targetPort: 27017
        -
          name: mongodb
          protocol: TCP
          port: 80
          targetPort: 27017
```

**Comment by srinivasa-vasu** [comment]
@gfouquet Yes, admin recommendation is just to get rid of scc error and for the duplicate port name it needs to be changed. I saw your pull request, that's fine.
