### ISSUE TITLE
Add needles for fields and getters/setters into entity classes

### ISSUE THREAD

**Issue by geesen** [jhipster/generator-jhipster#6246]
* **Overview of the request**

We have started a module for migrating entities for addin and, removing fields. At the moment it is very hard to inject new getters/setters and the field into the domain entity. 

* **Motivation for or Use Case** 

We have multiple jhipster applications that are already in production, running at our customers.
During the further development we often need to change fields/columns (mostly adding new fields and relationships). The "normal" add/remove field feature is not working for us, because of several problems:

- the entity class is overwritten: we often change some definitions like JsonIgnore, eager-fetching or we add some derived methods. These changes get lost or one have to merge that (which is, compared to just injecting the code) a lot of unneeded work
- the changelog is overwritten: this only works, if you would rollback to that changelog or the checksum would fail. This is not possible when your app is already in production, shipped to the customers and filled with data. The suggested alternative with `mvn liquibase:diff` does not work well, because it generates and changes a lot of other stuff, the naming and style are not equal to app/jhipster naming. A simple changelog with just "addColumn"-tags would be enough. Therefore we manually create a new changelog-file for the field like "20170818074012_migrate_product.xml"

We know that adding or removing fields is a bit more complex (e.g. changes in the client - which we don't need). Thus, we started a jhipster module called "generator-jhipster-migrate", which just adds the fields and the mentioned changelogs. However, changes to the java domain classes are not possible by default, after they were generated by jhipster. So we suggest to introduce some needels for this.

* **Browsers and Operating System** 

no specific browser or os

* **Related issues** 

#2668

* **Suggest a Fix** 

One solutiuon would be to add needles to the generated domain classes for an entity (like they are used in the liquibase master and changelogs), e.g. like:

`// jhipster-needle-entity-add-field - Jhipster will add fields here, do not remove`
and
`// jhipster-needle-entity-add-getters-setters - Jhipster will add getters and setters here, do not remove`

**Comment by deepu105** [comment]
@geesen you can add or remove fields out of the box in entity generator! have you tried it? 
![image](https://user-images.githubusercontent.com/1107223/29454834-f662dad2-840e-11e7-860a-c2df7a6ce185.png)

**Comment by deepu105** [comment]
@geesen ah OK you wanna add/remove without regenerating entity.
Ok can you submit a PR with needles required?

**Comment by geesen** [comment]
yes, that's the difference :) 
I will submit one!
