### ISSUE TITLE
Entity named 'Alert' should not be allowed : the generated "private alertService AlertService" name clash with "private alertService: JhiAlertService"

### ISSUE THREAD

**Issue by xdworkshop** [jhipster/generator-jhipster#6257]
##### **Overview of the issue**

Entity named 'Alert' should be reserved

ERROR in [at-loader] ./src/main/webapp/app/entities/alert/alert.component.ts:21:17
    TS2300: Duplicate identifier 'alertService'.

The generated contructor for AlertComponent is : 
```typescript
    constructor(
        private alertService: AlertService,
        private alertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {
    }
```

Subsequent variable declarations must have the same type. Variable 'alertService' must be of type 'AlertService', but here has type 'JhiAlertService'.

##### **Motivation for or Use Case**

Duplicate (name clash) at generation for the constructors (alertService)

##### **Reproduce the error**

Generate with an Entity name 'Alert'

##### **JHipster Version(s)**

generator-jhipster@4.6.2

##### **JHipster configuration**
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
zzzzzzz@0.0.0 D:\Developpement\git\zzzzzzzzzz
`-- generator-jhipster@4.6.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "zzzzz",
    "packageName": "com",
    "packageFolder": "com",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Stock (stock) {
  name String,
  symboleGoogle String,
  lastPrice BigDecimal,
  lastUpdated LocalDate
}
entity Alert (alert) {
  priceThreshold BigDecimal,
  enabled Boolean,
  creationDate LocalDate
}

relationship OneToMany {
  Stock{alert} to Alert{stock}
}
relationship ManyToOne {
  Alert{user} to User
}

service Stock with serviceImpl
service Alert with serviceImpl

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

git version 2.10.2.windows.1

node: v6.11.2

npm: 3.10.10

yeoman: 2.0.0

yarn: 0.27.5

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.14.0, build c7bdf9e3

Execution complete

##### **JHipster Version(s)**

```
zzzzzzzzz@0.0.0 D:\Developpement\git\zzzzzzzz
`-- generator-jhipster@4.6.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "zzzzzz",
    "packageName": "com",
    "packageFolder": "com",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "zzzzz",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `Alert.json` files generated in the `.jhipster` directory**
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "stock",
            "otherEntityName": "stock",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "priceThreshold",
            "fieldType": "BigDecimal"
        },
        {
            "fieldName": "enabled",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "creationDate",
            "fieldType": "LocalDate"
        }
    ],
    "changelogDate": "20170819210507",
    "entityTableName": "alert",
    "dto": "no",
    "pagination": "no",
    "service": "serviceImpl"
}

##### **Entity configuration(s) `Stock.json` files generated in the `.jhipster` directory**
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "alert",
            "otherEntityName": "alert",
            "otherEntityRelationshipName": "stock"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "symboleGoogle",
            "fieldType": "String"
        },
        {
            "fieldName": "lastPrice",
            "fieldType": "BigDecimal"
        },
        {
            "fieldName": "lastUpdated",
            "fieldType": "LocalDate"
        }
    ],
    "changelogDate": "20170819194714",
    "entityTableName": "stock",
    "dto": "no",
    "pagination": "no",
    "service": "serviceImpl"
}

I'm using Jhipster IDE

##### **Browsers and Operating System**

W10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Does renaming ` private alertService: JhiAlertService,` to ` private jhiAlertService: JhiAlertService,` fix the conflicts?

**Comment by deepu105** [comment]
It would I guess uless the jhi prefix doesnt collide as well


Thanks & Regards,
Deepu

**Comment by xdworkshop** [comment]
I don't know. I wanted to code my project and as a workaround, i've renammed my entity to StockAlert ...
