### ISSUE TITLE
problem in adding a nav element

### ISSUE THREAD

**Issue by alisedaghatbaf** [jhipster/generator-jhipster#6261]
##### **JHipster Version(s)**

```
twcfd@0.0.0 D:\projects\twcfd
`-- generator-jhipster@4.6.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.me.simple",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "twcfd",
    "packageName": "com.me.simple",
    "packageFolder": "com/me/simple",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

git version 2.13.3.windows.1

node: v8.2.1

npm: 5.3.0

bower: 1.8.0

gulp:
[19:35:50] CLI version 1.4.0

yeoman: 2.0.0

yarn: 0.27.5

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.14.0, build c7bdf9e3

##### **Overview of the issue**

whenever I use the nav-element generator to add a new element to the navbar of my jhipster application, I get the following compilation error:
TS2339: Property 'setLocations' does not exist on type 'JhiLanguageService'.
Any help would be appreciated.
##### **Motivation for or Use Case**
 
I used the nav-element generator to quickly add a new element to my app, but the generated element does not appear on the navbar.

##### **Reproduce the error**

yarn start v0.27.5
$ yarn run webpack:dev
 10% building modules 3/3 modules 0 active[HPM] Proxy created: [ '/api',
  '/management',
  '/swagger-resources',
  '/v2/api-docs',
  '/h2-console' ]  ->  http://127.0.0.1:8080

Project is running at http://localhost:9060/
webpack output is served from /
Content not from webpack is served from ./target/www                 11% building modules 10/15 modules 5 active ...dules\webpack\hot\log-apply-result.jsWarning: The 'no-use-before-declare' rule requires type infomation.

[at-loader] Using typescript@2.4.1 from typescript and "tsconfig.json" from D:\projects\twcfd/tsconfig.json.
                         10637ms building modules
32ms sealing
0ms optimizing
0ms basic module optimization
15ms module optimization
0ms advanced module optimization
25ms basic chunk optimization
0ms chunk optimization
1ms advanced chunk optimization
0ms module and chunk tree optimization
0ms chunk modules optimization
1ms advanced chunk modules optimization
13ms module reviving
13ms module order optimization
20ms module id optimization
11ms chunk reviving
2ms chunk order optimization
17ms chunk id optimization
32ms hashing
2ms module assets processing
4717ms chunk assets processing
133ms additional chunk assets processing
1ms recording
1ms additional asset processing
1ms chunk asset optimization
 94% asset optimization
[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors                                            195ms asset optimization
Hash: a9ad3e22139c62607fe5
Version: webpack 3.3.0
Time: 15868ms
[./node_modules/webpack-dev-server/client/index.js?http:/localhost:9060] (webpack)-dev-server/client?http://localhost:9060 5.59 kB {2} [built]
       [] -> factory:42ms building:33ms dependencies:759ms = 834ms
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.6 kB {2} [built]
       [] -> factory:24ms building:730ms = 754ms
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 856 bytes {2} [built]
       [] -> factory:24ms building:722ms = 746ms
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 kB {2} [built]
       [] -> factory:82ms building:15ms = 97ms
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {2} [built]
       [] -> factory:4ms building:732ms = 736ms
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.31 kB {2} [built]
       [] -> factory:751ms building:2516ms dependencies:2ms = 3269ms
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.04 kB {2} [built]
       [] -> factory:750ms building:2520ms = 3270ms
[./src/main/webapp/app/app.main.ts] ./src/main/webapp/app/app.main.ts 584 bytes {1} [built]
       [] -> factory:354ms building:2935ms = 3289ms
[./src/main/webapp/app/blocks/config/prod.config.ts] ./src/main/webapp/app/blocks/config/prod.config.ts 391 bytes {1} [built]
       [] -> factory:89ms building:131ms dependencies:656ms = 876ms
[./src/main/webapp/app/polyfills.ts] ./src/main/webapp/app/polyfills.ts 202 bytes {2} [built]
       [] -> factory:128ms building:3098ms = 3226ms
[./src/main/webapp/content/css/global.css] ./src/main/webapp/content/css/global.css 1.05 kB {3} [built]
       [] -> factory:101ms building:24ms = 125ms
[./src/main/webapp/manifest.webapp] ./src/main/webapp/manifest.webapp 61 bytes {2} [built]
       [] -> factory:726ms dependencies:1ms building:521ms = 1248ms
   [0] multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/app/polyfills 52 bytes {2} [built]
        factory:0ms building:2ms = 2ms
   [1] multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/content/css/global.css 52 bytes {3} [built]
        factory:0ms building:1ms dependencies:81ms = 82ms
   [2] multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/app/app.main 52 bytes {1} [built]
        factory:0ms building:4ms dependencies:77ms = 81ms
    + 750 hidden modules

ERROR in [at-loader] ./src/main/webapp/app/about-us/about-us.component.ts:16:29
    TS2339: Property 'setLocations' does not exist on type 'JhiLanguageService'.
Child html-webpack-plugin for "index.html":
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html 1.22 kB {0} [built]
            factory:369ms building:2942ms = 3311ms
webpack: Failed to compile.
[BS] Proxying: http://localhost:9060
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:9000
    External: http://192.168.56.1:9000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.56.1:3001
 -------------------------------------
##### **Browsers and Operating System**
Google Chrme on MS Windows 10 
- [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
> I used the nav-element generator to quickly add a new element to my app, but the generated element does not appear on the navbar.

What makes you think it's an issue with generator-jhipster and not with generator-jhipster-nav-element?
You should also report the version of generator-jhipster-nav-element.
Have you considered reporting this to the author of the module?

Unrelated to your issue: be aware that we recommend using LTS versions of node and you're using node 8.x

**Comment by gmarziou** [comment]
Discussion for JHipster team: https://groups.google.com/forum/#!topic/jhipster-dev/ZvUl3YFar_I

**Comment by deepu105** [comment]
In any case this issue should be reported to the specific module and not here
