### ISSUE TITLE
[Feature request] Provide angular auth/security directives and services as npm/yarn package

### ISSUE THREAD

**Issue by PatrickHuetter** [jhipster/generator-jhipster#6266]
##### **Overview of the issue**
At this time the the jhiHasAnyAuthority directive isn't available as npm/yarn dependency. It would be fine to have it within the ng-jhipster project so that it would be possible to use external angular apps and themes.

##### **Motivation for or Use Case**
We would like to use jhipster microservice architecture with a custom external angular 4 app (based on a theme and angular cli). I like the authorization pattern and system you've build within jhipster and i think it should be easy to integrate it within external angular applications.

At this time i thought about "adding the ng-jhipster-auth" dependency to an angular application, define an endpoint within the angular configuration and you have the possibility to display parts and routes based on the users role and so on like it's also done within the internal angular app (as default).

What do you think about this?

**Comment by deepu105** [comment]
Sorry but our focus is not this and this is not something we have the bandwidth to support. Moving these directive ng-jhipster is difficult as it depends on some services that are generated based on many options. So i'm sorry. You are welcome to try
