### ISSUE TITLE
Migrate to the new HttpClientModule from Angular 4.3

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6281]
##### **Overview of the issue**

Angular 4.3 brings a new module for HTTP communication. This new module has "_updated API's with support for progress events, json deserialization by default, Interceptors and many other great features_".

##### **Motivation for or Use Case**

JHispter 4.7 has upgraded Angular from 4.2.6 to 4.3.2. From Angular 4.3 a new HTTP module has arrived and it should be the one to use (the "old" one might get deprecated). 

I've liste a few external references below on how to migrate and so on. Basically, the "old" `HttpModule` located under `@angular/http`, is replaced by the new `HttpClientModule` from `@angular/common/http`. 

##### **External references**

* [HTTPClient](https://angular.io/guide/http)
* [The Angular HTTP Client - Quickstart Guide](http://blog.angular-university.io/angular-http/)
* [Migrating to HttpClient](http://brianflove.com/2017/07/21/migrating-to-http-client/)
* [Migrating from Angular HttpModule to new Angular 4.3 HttpClientModule](https://devops.datenkollektiv.de/migrating-from-angular-httpmodule-to-new-angular-43-httpclientmodule.html)
* [Difference between HTTP and HTTPClient in angular 4?](https://stackoverflow.com/questions/45129790/difference-between-http-and-httpclient-in-angular-4)
* [what's the difference between HttpModule and HttpClientModule in Angular2?](https://stackoverflow.com/questions/45405593/whats-the-difference-between-httpmodule-and-httpclientmodule-in-angular2)
* [Angular - How to use HttpClientModule?](http://blog.ninja-squad.com/2017/07/17/http-client-module/)

##### **JHipster Version(s)**

JHipster 4.7

**Comment by Thisen** [comment]
I'm currently working on a migration to HttpClient in the Angular template. I could be assigned to this, if you don't mind.

**Comment by jdubois** [comment]
Oh that's nice @Thisen -> I'm sending you an invite as you need to be a member of the project to have a task assigned (that's how GitHub works, I always find it not user friendly...)

**Comment by Thisen** [comment]
I have accepted the invite now @jdubois.

**Comment by Thisen** [comment]
Just a quick update: I haven't forgot about this issue, but holiday, moving project at work and sickness have stalled me. I believe I will get back to working on it in the weekend.

**Comment by chegola** [comment]
@Thisen  I am interesting on HttpClientModule, pls let me if I can help on something.

**Comment by gmarziou** [comment]
Panda bear and koala bear as avatars, you are made to work together :)

**Comment by Thisen** [comment]
I'll continue working on it today @chegola. I won't be needing any help, but thanks anyway. 👍

**Comment by Thisen** [comment]
If you're up for helping, I'm actually having a problem migrating user.service.ts:
`export const createRequestOption = (req?: any): BaseRequestOptions => {
    const options: BaseRequestOptions = new BaseRequestOptions();
    if (req) {
        const params: URLSearchParams = new URLSearchParams();
        params.set('page', req.page);
        params.set('size', req.size);
        if (req.sort) {
            params.paramsMap.set('sort', req.sort);
        }
        params.set('query', req.query);

        options.params = params;
    }
    return options;
};`
I can't seem to wrap my head around a good solution for changing the `req.sort`, since it's set on `URLSearchParams.paramsMap`, which the `HttpParams` API doesn't have.

**Comment by Thisen** [comment]
If you're up for helping, I'm actually having a problem migrating `user.service.ts` and the util function it uses in `request-util.ts`:
```
export const createRequestOption = (req?: any): BaseRequestOptions => {
    const options: BaseRequestOptions = new BaseRequestOptions();
    if (req) {
        const params: URLSearchParams = new URLSearchParams();
        params.set('page', req.page);
        params.set('size', req.size);
        if (req.sort) {
            params.paramsMap.set('sort', req.sort);
        }
        params.set('query', req.query);

        options.params = params;
    }
    return options;
};
```
I can't seem to wrap my head around a good solution for changing `req.sort`, since it's set on `URLSearchParams.paramsMap` attribute, which `theHttpParams` API doesn't have.

Any ideas?

**Comment by chegola** [comment]
I have no idea neither as there is no API in HttpParams that accept array object. Is that possible to raise this to Angular and not sure how long it going to available. :(

**Comment by ruddell** [comment]
@Thisen This could probably be cleaned up a little but the below code returns the same parameters as the current code:
```
import { HttpParams } from '@angular/common/http';

export const createRequestOption = (req?: any): HttpParams => {
    let options: HttpParams = new HttpParams();
    if (req) {
        options = options.set('page', req.page);
        options = options.set('size', req.size);
        req.sort.forEach((sort)=>{
            options = options.append('sort', sort)
        });
        if (req.query) {
            options = options.set('query', req.query);
        }
    }
    return options;
};
```

**Comment by gzsombor** [comment]
Maybe, this could be used: 
```
import { HttpParams } from '@angular/common/http';

export const createRequestOption = (req?: any, sort?: any): HttpParams => {
    let options: HttpParams = new HttpParams();
    if (req) {
        for (const key in req) {
            if (req.hasOwnProperty(key)) {
                options.set(key, req[key]);
            }
         }
        if (sort) { 
            sort.forEach((sort)=>{
                options = options.append('sort', sort)
           });
       }
    }
    return options;
};

```

Yes, slightly different method signature, but after this, you could pass any query parameter to your backend. It's a big plus, if you have filtering :wink:

**Comment by Thisen** [comment]
I'm down to two Angular services needing to get migrated - `auth.service.ts` and `auth-oauth2.service.ts`.

**For `auth.service.ts`:**
In the `authenticationType === 'uaa'` version of the service, we send an instance of `URLSearchParams` as the body of `http.post`. How should this be migrated to `HttpClient`?

**For `auth-oauth2.service.ts`:**
I can't even get a jhipster project generated with this service. Is it deprecated, or could you supply some generator options, which will get this service generated?

Thanks in advance.

**Comment by mraible** [comment]
auth-oauth2.service.ts is no longer used. I deleted it last week with the OIDC support.

**Comment by Thisen** [comment]
That's great @mraible, thank you for updating me. Now I just need some clarification about `auth.service.ts`, when using uaa.

**Comment by Thisen** [comment]
Still on hold, since I'm not sure about what I should do about `auth.service.ts`.

I will repeat myself from 3 Oct:
In the `authenticationType === 'uaa'` version of the service, we send an instance of `URLSearchParams` as the body of `http.post`. How should this be migrated to `HttpClient`?

Could anyone help me with clarifying this? I'm not really sure what the desired behavior is. @jdubois, @mraible or anyone else?

**Comment by ruddell** [comment]
@Thisen Could you open a PR with your work so you can point to exactly where you need help?  The section you are referring to has changed and no longer sends URLSearchParams 

https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/shared/auth/_auth-jwt.service.ts#L44-L58

**Comment by uyeliksiz** [comment]
@thisen use `HttpParams` with `HttpClient` . You can use `toString` method of `HttpParams` in order to get parameters as string. Docs says 

> Serialize the body to an encoded string, where key-value pairs (separated by `=`) are separated by `&`s.`

**Comment by kevcodez** [comment]
What is the current status?

@Thisen Can you provide a PR for what you have done so far, so we can finish this up?

**Comment by yelhouti** [comment]
it seems like @Thisen is no longer working on this (2 months since his last comment), his last commit to his own repo was event 1 month before that (https://github.com/Thisen/generator-jhipster) maybe someone else should get assigned this issue. 
@jdubois

**Comment by gmarziou** [comment]
@yelhouti are you volunteering?

**Comment by yelhouti** [comment]
@gmarziou ,  Unfortunately, I'm under a lot of work right now so I would just transfert the problem to my self, I think other people have volunteered to help in the previous comments. On the other hand, I would gladly review the code, and help if someone is stuck somewhere.

**Comment by jdubois** [comment]
Yes that's a very important issue, as now the older HTTP API is deprecated, that makes our generated code quite ugly. I can't work on it right now as I'm really struggling with the Spring Boot 2 migration, we need to find someone for this.

-> if anybody is interested please step up, otherwise I'll ask for help on Twitter

**Comment by NilsWild** [comment]
I merged @Thisen work into my fork and updated the components to their current implementation. It is packed without any wenpack errors or warnings. Only generated default application with jhipster --force and everything default values. You can't do anything right now as we have to update ng-jhipster JhiHttpInterceptor first.

**Comment by deepu105** [comment]
Can you PR that to ng-jhipster first?


Thanks & Regards,
Deepu

**Comment by Thisen** [comment]
Oops. Sorry for being unresponsive, apparently I wasn't getting any notifications for some reason. I kinda stopped looking at it, since I thought I wasn't getting replies. My bad. I don't have time at the moment to finish the migration, but if @NilsWild or any other have questions about my implementation, feel free to ask. ( My notifications are on correctly now :P )

**Comment by NilsWild** [comment]
@deepu105 i think we dont need ng-jhipster at all for this as we can register interceptors easily by adding them as providers to HTTP_INTERCEPTORS. or am i missing something? asking you as you are a contributor to the current http implementation

**Comment by deepu105** [comment]
@NilsWild the base interceptor is in the ng-jhipster lib, you said that `we have to update ng-jhipster JhiHttpInterceptor first so the token is forwarded.` so I asked you to do PR there. I havent had a close look at this yet

**Comment by NilsWild** [comment]
ok i upgraded everything at least with jwt and the sample-application from dubois everything works fine had no time to test more configurations as i dont have configurations for that

**Comment by deepu105** [comment]
Pr merged
