### ISSUE TITLE
Either MissingServletRequestPartException and MissingServletRequestParameterException should throw a Bad Request error code

### ISSUE THREAD

**Issue by xtremebiker** [jhipster/generator-jhipster#6283]
##### **Overview of the issue**

The generated ExceptionTranslator catches the `MethodArgumentNotValidException` and the `CustomParameterizedException`, but `MissingServletRequestPartException` and `MissingServletRequestParameterException` should as well be caught and treated to return bad request codes.

##### **Reproduce the error**

Created a new REST endpoint to display entity field suggestions with this signature:

```
@GetMapping("/installations/suggestions")
@Timed
public Set<String> getSuggestions(
@RequestParam(required = false, defaultValue = "") String pattern,
			@RequestParam String field);
```

Then created a new integration test that should return 400 since the required `field` parameter is missing:

```
@Test
@Transactional
public void suggestionsRequiredType() throws Exception {
	// Get the installation
	restInstallationMockMvc.perform(get("/api/installations/suggestions?pattern=cio", installation.getId()))
			.andExpect(status().isBadRequest());
}
```

But the test fails as the endpoint returns a 500 response instead of 400. That's because the exception is caught by the standard processor:

```
@ExceptionHandler(Exception.class)
public ResponseEntity<ErrorVM> processException(Exception ex) {
	log.error(ex.getMessage(), ex);
	BodyBuilder builder;
	ErrorVM errorVM;
	ResponseStatus responseStatus = AnnotationUtils.findAnnotation(ex.getClass(), ResponseStatus.class);
	if (responseStatus != null) {
		builder = ResponseEntity.status(responseStatus.value());
		errorVM = new ErrorVM("error." + responseStatus.value().value(), responseStatus.reason());
	} else {
		builder = ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR);
		errorVM = new ErrorVM(ErrorConstants.ERR_INTERNAL_SERVER_ERROR, "Internal server error");
	}
	return builder.body(errorVM);
}
```

##### **Suggest a Fix**

Adding this in the `ExceptionTranslator` solved it:
```
@ExceptionHandler(MissingServletRequestParameterException.class)
@ResponseBody
@ResponseStatus(HttpStatus.BAD_REQUEST)
public ErrorVM processMissingServletRequestParameterException(MissingServletRequestParameterException exception) {
	return new ErrorVM(ErrorConstants.ERR_BAD_REQUEST, exception.getMessage());
}
```

##### **JHipster Version(s)**

4.4.1

**Comment by jdubois** [comment]
Understood -> this part of JHipster isn't very clear, let me "handle" this :-)

**Comment by jdubois** [comment]
OK so this part of JHipster is much worse than I thought!!

- The back-end code isn't as good as it should be, which is what you point to
- It also sends error messages that should be taken into account by the front-end, using our i18n error codes, but none of them are present. Even worse, there's a "error.accessDenied" and "error.403" that do the same thing but don't work together...

Anyway: that's bad, it takes some time to fix (as i18n is huge now), and I know what to do -> I should have some time this week (I have a 7 hour flight on Thursday), so I'm assigning this to myself.

**Comment by cbornet** [comment]
There are other standard Spring exceptions that we override : https://github.com/spring-projects/spring-framework/blob/a0bce618c2f51d8af1fc00ee2c3868ba2c8e0045/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ResponseEntityExceptionHandler.java#L106
We should probably do something for them also.
Also, I propose to use [rfc7807](https://tools.ietf.org/html/rfc7807) application/problem+json errors. I believe they should work well with our front-end.

**Comment by cbornet** [comment]
After some digging, I think we should remove our `ExceptionHandler` beans and use a global `ErrorAttributes` instead. I'll try something asap.
