### ISSUE TITLE
Jhipster heroku does not support ClearDB

### ISSUE THREAD

**Issue by AresSec** [jhipster/generator-jhipster#6284]
##### **Overview of the issue**

I'm using JHipster Heroku to deploy my app to Heroku. Within Heroku I'm using a ClearDB instance as database. Everytime I deploy via:

`jhipster heroku`

It creates a new JawsDB as addon and not the ClearDB which is already in place:
```
Using existing Git repository

Heroku CLI deployment plugin already installed

Provisioning addons
Created jawsdb:kitefin --as JAWSDB

Creating Heroku deployment files
identical src/main/resources/config/bootstrap-heroku.yml
identical src/main/resources/config/application-heroku.yml
identical Procfile
```

When the deployment is finished I've two running DBs:

```
heroku addons

Add-on                              Plan     Price  State  
──────────────────────────────────  ───────  ─────  ───────
cleardb (cleardb-horizontal-68105)  ignite   free   created
 └─ as CLEARDB_DATABASE

jawsdb (jawsdb-curved-69063)        kitefin  free   created
```

How is it possible to change the heroku plugin to use ClearDB instead of JawsDB and also doesn't create every deploy a new DB instance (I could live with that if it would be ClearDB and not JawsDB).

##### **Motivation for or Use Case**

JawsDB has some limitations when using it instead of ClearDB. I as a developer should be able to define in the config or during deploy process which DB I want to use as --addons

##### **Reproduce the error**

`jhipster heroku` in your project and a new JawsDB will be created

##### **Suggest a Fix**

Add a config parameter to select which kind of addon is going to be used or use the already existing one if it's in place, like:

```
heroku config
=== securityrat Config Vars
CLEARDB_DATABASE_URL: mysql:/xxxxxx@eu-cdbr-west-01.cleardb.com/xxxxx?reconnect=true
```

##### **JHipster Version(s)**

4.7.0

##### **JHipster configuration**

`jhipster info
Using JHipster version installed globally
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
sdlctool@0.0.0 /home/ares/SecurityRAT
└── generator-jhipster@2.20.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "baseName": "sdlctool",
    "packageName": "org.appsec.sdlctool",
    "packageFolder": "org/appsec/sdlctool",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "herokuAppName": "securityrat"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity CollectionCategory (CollectionCategory) {
  name String,
  description String,
  showOrder Integer,
  active Boolean
}
entity CollectionInstance (CollectionInstance) {
  name String,
  description String,
  showOrder Integer,
  active Boolean
}
entity TagCategory (TagCategory) {
  name String,
  description String,
  showOrder Integer,
  active Boolean
}
entity TagInstance (TagInstance) {
  name String,
  description String,
  showOrder Integer,
  active Boolean
}
entity ReqCategory (ReqCategory) {
  name String,
  shortcut String,
  description String,
  showOrder Integer,
  active Boolean
}
entity StatusColumn (StatusColumn) {
  name String,
  description String,
  isEnum Boolean,
  showOrder Integer,
  active Boolean
}
entity StatusColumnValue (StatusColumnValue) {
  name String,
  description String,
  showOrder Integer,
  active Boolean
}
entity OptColumnType (OptColumnType) {
  name String,
  description String
}
entity OptColumn (OptColumn) {
  name String,
  description String,
  showOrder Integer,
  active Boolean
}
entity AlternativeSet (AlternativeSet) {
  name String,
  description String,
  showOrder Integer,
  active Boolean
}
entity ProjectType (ProjectType) {
  name String,
  description String,
  showOrder Integer,
  active Boolean
}
entity RequirementSkeleton (RequirementSkeleton) {
  universalId String,
  shortName String,
  description String,
  showOrder Integer,
  active Boolean
}
entity AlternativeInstance (AlternativeInstance) {
  content String
}
entity OptColumnContent (OptColumnContent) {
  content String
}

relationship OneToMany {
  CollectionCategory{collectionInstance} to CollectionInstance{collectionCategory(name)},
  TagCategory{tagInstance} to TagInstance{tagCategory(name)},
  StatusColumn{statusColumnValue} to StatusColumnValue{statusColumn(name)},
  OptColumnType{optColumn} to OptColumn{optColumnType(name)},
  OptColumn{alternativeSet} to AlternativeSet{optColumn(name)},
  ReqCategory{requirementSkeleton} to RequirementSkeleton{reqCategory(name)},
  AlternativeSet{alternativeInstance} to AlternativeInstance{alternativeSet(name)},
  RequirementSkeleton{alternativeInstance} to AlternativeInstance{requirementSkeleton(shortName)},
  OptColumn{optColumnContent} to OptColumnContent{optColumn(name)},
  RequirementSkeleton{optColumnContent} to OptColumnContent{requirementSkeleton(shortName)}
}
relationship ManyToMany {
  ProjectType{statusColumn(name)} to StatusColumn{projectType},
  ProjectType{optColumn(name)} to OptColumn{projectType},
  RequirementSkeleton{tagInstance(name)} to TagInstance{requirementSkeleton},
  RequirementSkeleton{collectionInstance(name)} to CollectionInstance{requirementSkeleton},
  RequirementSkeleton{projectType(name)} to ProjectType{requirementSkeleton}
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.7.4

node: v6.11.2

npm: 5.3.0

bower: 1.8.0

yeoman: 2.0.0

Execution complete
`

`.yo-rc.json:

{
  "generator-jhipster": {
    "baseName": "sdlctool",
    "packageName": "org.appsec.sdlctool",
    "packageFolder": "org/appsec/sdlctool",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "xxxx",
    "herokuAppName": "securityrat"
  }
}`

##### **Browsers and Operating System**

`cat /proc/version:
Linux version 4.10.0-32-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017
`

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
ping @jkutner

**Comment by jkutner** [comment]
@AresSec thanks for reporting this. I don't think I'll add the ability to select ClearDB as an addon, because I don't want to encourage people to use it (I've had way too many problems with it). But I could improve the Heroku generator to avoid adding the JawsDB addon if the ClearDB addon has been manually added. 

Would that work for you?

**Comment by AresSec** [comment]
@jkutner thank you for the really quick response. Indeed for me (and hopefully for others as well) it would work if the generator would use a manually added addon if it's already there.
