### ISSUE TITLE
ExtractTextPlugin and Thymeleaf interaction

### ISSUE THREAD

**Issue by irbian** [jhipster/generator-jhipster#6285]
##### **Overview of the issue**

Please excuse my inexperience, I´m far from an expert on jhipster or webpack. Here is the thing

I got this error when deploying the webpack:prod build

    Caused by: org.xml.sax.SAXParseException: The element type "link" must be terminated by the matching end-tag "</link>".
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1749)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)

Examining the index.html I can see two <link> that are not well closed (don´t close as />)

Checking another old project made with JHipster, I can see that the webpack.prod is different in several points, but more interesting, on the use of ExtractTextPlugin.

What it works:
    
        },
        {
            test: /(vendor\.scss|global\.scss)/,
            use: ['style-loader', 'css-loader', 'postcss-loader', 'sass-loader']
        },
        {
            test: /\.css$/,
            loaders: ['to-string-loader', 'css-loader'],
            exclude: /(vendor\.css|global\.css)/
        },
        {
            test: /(vendor\.css|global\.css)/,
            use: ['style-loader', 'css-loader']
        }] 

What it doesn´t 

        {
            test: /(vendor\.scss|global\.scss)/,
            use: extractSASS.extract({
                fallback: 'style-loader',
                use: ['css-loader', 'postcss-loader', 'sass-loader']
            })
        },
        {
            test: /\.css$/,
            loaders: ['to-string-loader', 'css-loader'],
            exclude: /(vendor\.css|global\.css)/
        },
        {
            test: /(vendor\.css|global\.css)/,
            use: extractCSS.extract({
                fallback: 'style-loader',
                use: ['css-loader']
            })
        }]

I mean, I guess I´m missing some functionality, but here enters my inexperience of webpack: I guess that the difference is that one will serve the styles as linked stylesheets while the other one will add it to the body.

##### **JHipster Version(s)**

4.6.2

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "my.package",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "my_package",
    "packageName": "my.package",
    "packageFolder": "my/package",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "asdasdasdasdasdasdasdasdas",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}

##### **Browsers and Operating System**

Windows and Linux

- [v] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I dont understand your issue at all. Can you explain clearly what you are trying to do? Are you able to reproduce this issue with a fresh app generated using the same config?

**Comment by irbian** [comment]
I started a new project from zero and I can see now why this doesn´t happen on new projects. Because by default index.html is not parsed as a thymeleaf template

If you try to do it (for example for exposing some config from the server), you´ll get the error that I´m talking about (Caused by: org.xml.sax.SAXParseException: The element type "link" must be terminated by the matching end-tag "</link>".)

Why this happens now? Because now the styles are linked via style-loader, instead of hot-loaded

**Comment by deepu105** [comment]
This is by design as the index.html is supposed to be an angular app and not handled by thyme leaf. This is a very rare use case. If you wish you could try to configure the plugin add end tags to make it compatible with Thymeleaf but I dont think we will have bandwidth to do this

**Comment by deepu105** [comment]
FYI. The links are added to index.html by the `HtmlWebpackPlugin` so you should start looking at the docs of that plugin. I found this option

`xhtml: true | false` If true render the link tags as self-closing, XHTML compliant. Default is `false`

So this would solve your issue. You could PR this if you wish

**Comment by irbian** [comment]
Cool this will be very helpful

**Comment by irbian** [comment]
Just curious, how you people expose server properties if needed, through some api?

**Comment by deepu105** [comment]
take a look at profileResource
