### ISSUE TITLE
JDL support for filtering is missing in 4.7.0

### ISSUE THREAD

**Issue by shekvl** [jhipster/generator-jhipster#6286]
##### **Overview of the issue**

In 4.7.0, jdl-import generator does not create `"jpaMetamodelFiltering": true` entries in .jhipster/*.json files (enabling criteria query generation), and there seems to be no way currently to enable such generation from JDL.

##### **Motivation for or Use Case**

Without this functionality, it is not possible to correctly update filtering-enabled entities from JDL, as, after every update, the filtering support is switched off (as it defaults to "no").

##### **Reproduce the error**

Run jhipster import-jdl with any JDL file and check the resulting .json files.

##### **Suggest a Fix**

The option like 

`filtering for <entity-name | *>`

can be added to the JDL syntax. Such option, if enabled, should lead to the generation of the `"jpaMetamodelFiltering": true` entry in .json file for the corresponding entity.

##### **JHipster Version(s)**

4.7.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
ping @MathieuAA

**Comment by deepu105** [comment]
@shekvl the feature is not supported by JDL yet

**Comment by MathieuAA** [comment]
@deepu105 Roger that, I'll handle it

**Comment by jdubois** [comment]
Thanks @MathieuAA -> I'm closing this here as this should be handled in jhipster-core

**Comment by colameo** [comment]
is the keyword 'for' in the 'filter' optional or mandatory?

see [example](https://github.com/jhipster/jhipster-core/blob/master/test/test_files/filtering.jdl) and [documentation](http://www.jhipster.tech/jdl/)

**They can be used like this: `<OPTION> <ENTITIES | * | all> except? <ENTITIES>`**

**Comment by ruddell** [comment]
@colameo The word `for` is not allowed with `filter`.  Only statement 1 is correct

**Comment by colameo** [comment]
ok, thanks @ruddell

**Comment by colameo** [comment]
...hm, the documentation is a bit unclear as the 'for' word is allowed for the following options:

skipClient 
skipServer
noFluentMethod

...but not for filter.

**Comment by ruddell** [comment]
@colameo I see your point, it doesn't really make sense why some keywords use `for` while others do not.  I answered based on what worked when importing JDL, JDL Studio should also highlight invalid JDL.  This looks like an issue to take up in the jhipster-core project

**Comment by MathieuAA** [comment]
I'll fix it today.
