### ISSUE TITLE
Null Dates in entities from JDL using Angular4

### ISSUE THREAD

**Issue by DorBashan** [jhipster/generator-jhipster#6290]
##### **Overview of the issue**

I generated an Angular4 project and used JDL to generate an entity with a date field.
When i tried to save the entity with a chosen date i found out that the date from the view
is returning null, means there is no binding between the entity model and the view.

##### **Motivation for or Use Case**

After reading about possible solutions I found out that `[(ngModel)]` is not binding for date
the same that it's binding for text, number...etc.  [discussion here](https://stackoverflow.com/questions/38175251/angular-2-date-input-not-binding-to-date-value) 

##### **Reproduce the error**

1) Generate a project with Angular4.
2) Generate an entity with Date field using JDL.
3) Go to the create/update dialog of this component, pick a date and try to save the entity.

HTML generated example:

~~~html
<div class="form-group">
            <label class="form-control-label" for="field_birthDate">Birth Date</label>
            <div class="d-flex">
                <input id="field_birthDate" type="datetime-local" class="form-control" name="birthDate" [(ngModel)]="animal.birthDate"
                  />
            </div>
        </div>`
~~~

4) Print the entity before sending it to the service and you'll see null in the date field.

##### **Related issues**

1) https://stackoverflow.com/questions/38175251/angular-2-date-input-not-binding-to-date-value

##### **Suggest a Fix**

To solve it: 
1) I implemented the date binding solution as it suggested at the post above.
2) After fixing it I found out the `this.dateUtils.toDate` of JHipster is causing problems because I'm producing Date from the view (don't need to convert) so i removed it.
3) Next I had to remove `@JsonFormat(pattern = "dd/MM/yyyy")` annotation from the DaoEntity.

I suggest to fix the binding of date fields for Angular4 in the view, and think about removing dates conversion by default.   

##### **JHipster Version(s)**

v.4.6.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "bashan.adoptme"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "AdoptMe",
    "packageName": "bashan.adoptme",
    "packageFolder": "bashan/adoptme",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Animal (animal) {
  animalName String required,
  animalType AnimalType,
  animalColor AnimalColor,
  animalSize AnimalSize,
  imageUrl String,
  birthDate ZonedDateTime,
  shortDescription String,
  longDescription String,
  isTrained Boolean,
  animalGender AnimalGender
}

##### **Browsers and Operating System**

MacOS Sierra 10.12.6
Chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Im confused. This is something that works well and what is that line about
jsonFormat? I dont think we do that at all.

**Comment by DorBashan** [comment]
Forget about how i solved it in my specific situation, bottom line is that
the date input inside the dialog of the entity with date field that being
generated by JHipster does not bind to the entity [see related
stackoverflow issue].
Please follow the steps to reproduce it.

**Comment by deepu105** [comment]
I have no idea what you are doing I tried to reproduce this and all 3 types of date works fine.
![image](https://user-images.githubusercontent.com/1107223/29740537-0454d55a-8a59-11e7-9501-47bbe79619db.png)

**Comment by deepu105** [comment]
![image](https://user-images.githubusercontent.com/1107223/29740610-b3eeaa1c-8a5a-11e7-848a-38f511f7a9e4.png)
