### ISSUE TITLE
liquibase:diff produces bytea entries for LocalDate, Instant, and ZonedDateTime properties

### ISSUE THREAD

**Issue by shekvl** [jhipster/generator-jhipster#6291]
##### **Overview of the issue**

Running `mvnw liquibase:diff` after adding a `LocalDate`, `Instant`, or `ZonedDateTime` property to the entity (e.g from JDL) produces a command to add column of `bytea` type in the liquibase changelog instead of `date` or `timestamp`.

##### **Motivation for or Use Case**

Resulting fields are not compatible with the intended values, leading to exceptions at runtime

##### **Reproduce the error**

1. create a JHipster project (or use an existing one)
2. create the following JDL (foo.jdl)
```
entity Foo {
    currentDate LocalDate 
}
```
3. add it to JHipster project

`jhipster import-jdl foo.jdl`

4. compile the project

`mvnw compile`

5. run liquibase diff

`mvnw liquibase:diff`

6. check the resulting changelog: it will contain the entity like this:
```
<createTable tableName="foo">
<column name="current_date" type="bytea"/>
</createTable>
```
##### **Suggest a Fix**

JHipster generates the following entity code fragments (in `com.mycompany.myproject.domain`) for the columns of these types:
```java
@Column(name = "current_date")
    private LocalDate currentDate; // also ZonedDateTime, Instant
```
this is not enough for `liquibase:diff` to guess the type of the column and it falls back to `bytea` type. I fixed this for me by following standard JPA procedure for mapping java8 time classes by creating the converters for these types:

LocalDateConverter.java:
```java
package com.mycompany.myproject.domain;

import javax.persistence.AttributeConverter;
import javax.persistence.Converter;
import java.sql.Date;
import java.time.LocalDate;

@Converter(autoApply = true)
public class LocalDateConverter implements AttributeConverter<LocalDate, Date> {
// also ZonedDateTimeConverter and InstantConverter

    @Override
    public Date convertToDatabaseColumn(LocalDate localDate) {
        return localDate != null ? Date.valueOf(localDate) : null;
    }

    @Override
    public LocalDate convertToEntityAttribute(Date date) {
        return date != null ? date.toLocalDate() : null;
    }
}
```
Unfortunately, due to unclear reasons the autowiring (autoApply = true) does not work for such converters, so it was also necessary to add the explicit calls to the converter to all fields of these types in all the entities in `com.mycompany.myproject.domain` package:
```java
@Column(name = "current_date")
@Convert(converter = LocalDateConverter.class)
private LocalDate currentDate;
```

This also applies to the standard classes like `User` or `AbstractAuditingEntity` (which include `Instant` fields which are also the subject of this problem).

I managed to do it via perl script processing the files in `domain` , but this is a workaround and not a fix.

It still can be a configuration problem as the documentation suggests that newer versions of hibernate (the current project shows 5.2.8 as current version) should map these types without problems (maybe the version of JPA is important in this case, which is 2.1 I believe). 

##### **JHipster Version(s)**

4.6.2, 4.7.0

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
##### **JHipster Version(s)**

myproject@0.0.0 c:\projects\myproject
`-- (empty)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myproject",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "myproject",
    "packageName": "com.mycompany.myproject",
    "packageFolder": "com/mycompany/myproject",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "rememberMeKey": "hidden",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Foo (foo) {
  currentDate LocalDate
}

dto Foo with mapstruct
service Foo with serviceClass
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
git version 1.9.4.msysgit.1
node: v6.9.5
npm: 5.3.0
bower: 1.8.0
yeoman: 2.0.0
yarn: 0.27.5
Execution complete 

##### **Browsers and Operating System**

Windows 7

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Shouldn't this be something that liquibase should be fixing?

**Comment by cbornet** [comment]
Yes probably on liquibase side from Hibernate 5 migration.

**Comment by deepu105** [comment]
@nvoxland do you think this should be handled at liquibase side?

**Comment by jdubois** [comment]
Yes this is a limitation on Liquibase - so this should be reported to @nvoxland and we can't do anything about it ourselves.
