### ISSUE TITLE
Gitlab CI + Heroku deploy failed using gradle.

### ISSUE THREAD

**Issue by willcrisis** [jhipster/generator-jhipster#6293]
##### **Overview of the issue**

Generated a new JHipster application using Gradle + Angular 4, added Gitlab CI support and checked to deploy to Heroku. Got the following error:

```
Task 'deployHeroku' not found in root project 'project-name'.
```

The full GitLab Pipeline log can be viewed below:

<details>
<summary>log</summary>
<pre>
Running with gitlab-ci-multi-runner 9.5.0 (413da38)
  on docker-auto-scale (4e4528ca)
Using Docker executor with image openjdk:8 ...
Using docker image sha256:04c488ddd9f85055b98c8d727e7452e91e481082846533c06ae53c60623d1ffd for predefined container...
Pulling docker image openjdk:8 ...
Using docker image openjdk:8 ID=sha256:4551430cfe804686c4a06341a1f1e5ef28906ed6e44b1899759341a5b69df26e for build container...
Running on runner-4e4528ca-project-4007260-concurrent-0 via runner-4e4528ca-machine-1503795094-bb4ce5a3-digital-ocean-2gb...
Cloning repository...
Cloning into '/builds/willcrisis/aratu'...
Checking out f2bf2bb8 as master...
Skipping Git submodules setup
Checking cache for master...
Downloading cache.zip from http://runners-cache-5-internal.gitlab.com:444/runner/project/4007260/master 
Successfully extracted cache
Downloading artifacts for gradle-test (30399296)...
Downloading artifacts from coordinator... ok        id=30399296 responseStatus=200 OK token=5JgRa6Wk
Downloading artifacts for gradle-front-test (30399297)...
Downloading artifacts from coordinator... ok        id=30399297 responseStatus=200 OK token=6VzczU95
Downloading artifacts for gradle-repackage (30399298)...
Downloading artifacts from coordinator... ok        id=30399298 responseStatus=200 OK token=LXgA828d
$ export GRADLE_USER_HOME=`pwd`/.gradle
$ chmod +x gradlew
$ ./gradlew yarn_install -PnodeInstall --no-daemon
:nodeSetup
:yarnSetup
/builds/willcrisis/aratu/.gradle/yarn/yarn-v0.27.5/bin/yarn -> /builds/willcrisis/aratu/.gradle/yarn/yarn-v0.27.5/lib/node_modules/yarn/bin/yarn.js
/builds/willcrisis/aratu/.gradle/yarn/yarn-v0.27.5/bin/yarnpkg -> /builds/willcrisis/aratu/.gradle/yarn/yarn-v0.27.5/lib/node_modules/yarn/bin/yarn.js
/builds/willcrisis/aratu/.gradle/yarn/yarn-v0.27.5/lib
└─┬ yarn@0.27.5 
  ├─┬ babel-runtime@6.26.0 
  │ ├── core-js@2.5.0 
  │ └── regenerator-runtime@0.11.0 
  ├── bytes@2.5.0 
  ├── camelcase@4.1.0 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.1.1 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ cmd-shim@2.0.2 
  │ └── graceful-fs@4.1.11 
  ├── commander@2.11.0 
  ├── death@1.1.0 
  ├─┬ debug@2.6.8 
  │ └── ms@2.0.0 
  ├── detect-indent@5.0.0 
  ├─┬ glob@7.1.2 
  │ ├── fs.realpath@1.0.0 
  │ ├─┬ inflight@1.0.6 
  │ │ └── wrappy@1.0.2 
  │ ├── inherits@2.0.3 
  │ ├─┬ minimatch@3.0.4 
  │ │ └─┬ brace-expansion@1.1.8 
  │ │   ├── balanced-match@1.0.0 
  │ │   └── concat-map@0.0.1 
  │ ├── once@1.4.0 
  │ └── path-is-absolute@1.0.1 
  ├─┬ gunzip-maybe@1.4.1 
  │ ├─┬ browserify-zlib@0.1.4 
  │ │ └── pako@0.2.9 
  │ ├── is-deflate@1.0.0 
  │ ├── is-gzip@1.0.0 
  │ ├─┬ peek-stream@1.1.2 
  │ │ └─┬ duplexify@3.5.1 
  │ │   └── stream-shift@1.0.0 
  │ ├── pumpify@1.3.5 
  │ └── through2@2.0.3 
  ├── ini@1.3.4 
  ├─┬ inquirer@3.2.2 
  │ ├── ansi-escapes@2.0.0 
  │ ├─┬ chalk@2.1.0 
  │ │ ├─┬ ansi-styles@3.2.0 
  │ │ │ └─┬ color-convert@1.9.0 
  │ │ │   └── color-name@1.1.3 
  │ │ └─┬ supports-color@4.2.1 
  │ │   └── has-flag@2.0.0 
  │ ├─┬ cli-cursor@2.1.0 
  │ │ └─┬ restore-cursor@2.0.0 
  │ │   └─┬ onetime@2.0.1 
  │ │     └── mimic-fn@1.1.0 
  │ ├── cli-width@2.2.0 
  │ ├─┬ external-editor@2.0.4 
  │ │ ├── iconv-lite@0.4.18 
  │ │ ├── jschardet@1.5.1 
  │ │ └─┬ tmp@0.0.31 
  │ │   └── os-tmpdir@1.0.2 
  │ ├── figures@2.0.0 
  │ ├── lodash@4.17.4 
  │ ├── mute-stream@0.0.7 
  │ ├─┬ run-async@2.3.0 
  │ │ └── is-promise@2.1.0 
  │ ├── rx-lite@4.0.8 
  │ ├── rx-lite-aggregates@4.0.8 
  │ ├─┬ string-width@2.1.1 
  │ │ ├── is-fullwidth-code-point@2.0.0 
  │ │ └─┬ strip-ansi@4.0.0 
  │ │   └── ansi-regex@3.0.0 
  │ ├─┬ strip-ansi@4.0.0 
  │ │ └── ansi-regex@3.0.0 
  │ └── through@2.3.8 
  ├─┬ invariant@2.2.2 
  │ └─┬ loose-envify@1.3.1 
  │   └── js-tokens@3.0.2 
  ├─┬ is-builtin-module@1.0.0 
  │ └── builtin-modules@1.1.1 
  ├─┬ is-ci@1.0.10 
  │ └── ci-info@1.0.0 
  ├── leven@2.1.0 
  ├─┬ loud-rejection@1.6.0 
  │ ├─┬ currently-unhandled@0.4.1 
  │ │ └── array-find-index@1.0.2 
  │ └── signal-exit@3.0.2 
  ├─┬ micromatch@2.3.11 
  │ ├─┬ arr-diff@2.0.0 
  │ │ └── arr-flatten@1.1.0 
  │ ├── array-unique@0.2.1 
  │ ├─┬ braces@1.8.5 
  │ │ ├─┬ expand-range@1.8.2 
  │ │ │ └─┬ fill-range@2.2.3 
  │ │ │   ├── is-number@2.1.0 
  │ │ │   ├── isobject@2.1.0 
  │ │ │   ├─┬ randomatic@1.1.7 
  │ │ │   │ ├─┬ is-number@3.0.0 
  │ │ │   │ │ └── kind-of@3.2.2 
  │ │ │   │ └── kind-of@4.0.0 
  │ │ │   └── repeat-string@1.6.1 
  │ │ ├── preserve@0.2.0 
  │ │ └── repeat-element@1.1.2 
  │ ├─┬ expand-brackets@0.1.5 
  │ │ └── is-posix-bracket@0.1.1 
  │ ├── extglob@0.3.2 
  │ ├── filename-regex@2.0.1 
  │ ├── is-extglob@1.0.0 
  │ ├── is-glob@2.0.1 
  │ ├─┬ kind-of@3.2.2 
  │ │ └── is-buffer@1.1.5 
  │ ├─┬ normalize-path@2.1.1 
  │ │ └── remove-trailing-separator@1.1.0 
  │ ├─┬ object.omit@2.0.1 
  │ │ ├─┬ for-own@0.1.5 
  │ │ │ └── for-in@1.0.2 
  │ │ └── is-extendable@0.1.1 
  │ ├─┬ parse-glob@3.0.4 
  │ │ ├─┬ glob-base@0.3.0 
  │ │ │ └── glob-parent@2.0.0 
  │ │ └── is-dotfile@1.0.3 
  │ └─┬ regex-cache@0.4.3 
  │   ├── is-equal-shallow@0.1.3 
  │   └── is-primitive@2.0.0 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├─┬ node-emoji@1.8.1 
  │ └── lodash.toarray@4.4.0 
  ├── object-path@0.11.4 
  ├─┬ proper-lockfile@2.0.1 
  │ └── retry@0.10.1 
  ├── read@1.0.7 
  ├─┬ request@2.81.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.6.0 
  │ ├── caseless@0.12.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.1 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@2.1.4 
  │ │ └── asynckit@0.4.0 
  │ ├─┬ har-validator@4.2.1 
  │ │ ├─┬ ajv@4.11.8 
  │ │ │ ├── co@4.6.0 
  │ │ │ └─┬ json-stable-stringify@1.0.1 
  │ │ │   └── jsonify@0.0.0 
  │ │ └── har-schema@1.0.5 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.4.1 
  │ │ │ ├── assert-plus@1.0.0 
  │ │ │ ├── extsprintf@1.3.0 
  │ │ │ ├── json-schema@0.2.3 
  │ │ │ └─┬ verror@1.10.0 
  │ │ │   └── assert-plus@1.0.0 
  │ │ └─┬ sshpk@1.13.1 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├── bcrypt-pbkdf@1.0.1 
  │ │   ├─┬ dashdash@1.14.1 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.7 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jsbn@0.1.1 
  │ │   └── tweetnacl@0.14.5 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.16 
  │ │ └── mime-db@1.29.0 
  │ ├── oauth-sign@0.8.2 
  │ ├── performance-now@0.2.0 
  │ ├── qs@6.4.0 
  │ ├── safe-buffer@5.1.1 
  │ ├── stringstream@0.0.5 
  │ ├─┬ tough-cookie@2.3.2 
  │ │ └── punycode@1.4.1 
  │ └── tunnel-agent@0.6.0 
  ├── request-capture-har@1.2.2 
  ├── rimraf@2.6.1 
  ├── semver@5.4.1 
  ├── strip-bom@3.0.0 
  ├─┬ tar-fs@1.15.3 
  │ ├── chownr@1.0.1 
  │ └── pump@1.0.2 
  ├─┬ tar-stream@1.5.4 
  │ ├── bl@1.2.1 
  │ ├── end-of-stream@1.4.0 
  │ ├─┬ readable-stream@2.3.3 
  │ │ ├── core-util-is@1.0.2 
  │ │ ├── isarray@1.0.0 
  │ │ ├── process-nextick-args@1.0.7 
  │ │ ├── string_decoder@1.0.3 
  │ │ └── util-deprecate@1.0.2 
  │ └── xtend@4.0.1 
  ├── uuid@3.1.0 
  ├── v8-compile-cache@1.1.0 
  └─┬ validate-npm-package-license@3.0.1 
    ├─┬ spdx-correct@1.0.2 
    │ └── spdx-license-ids@1.2.2 
    └── spdx-expression-parse@1.0.4 

:yarn_install
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
$ node node_modules/phantomjs-prebuilt/install.js
Found PhantomJS at /builds/willcrisis/aratu/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ...verifying
PhantomJS is previously installed at /builds/willcrisis/aratu/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
Done in 2.85s.

BUILD SUCCESSFUL in 41s
3 actionable tasks: 3 executed
$ ./gradlew deployHeroku --no-daemon

FAILURE: Build failed with an exception.

* What went wrong:
Task 'deployHeroku' not found in root project 'aratu'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 6s
ERROR: Job failed: exit code 1
</pre>
</details>

##### **Motivation for or Use Case**

After executing all the CI-CD process, automatically deploy the application to Heroku.

##### **Reproduce the error**

* Generate a new application using `jhipster app`
* Choose to use Gradle and Angular 4
* (optional) Generate a new domain with a few fields
* Add CI-CD support using `jhipster ci-cd`
* Choose GitLab CI
* Choose `Deploy to Heroku` on GitLab CI
* Configure `HEROKU_API_KEY` in GitLab Pipelines settings
* Commit + push to GitLab repo
* Pipeline will fail at `gradle-deploy` job

##### **Related issues**

N/A

##### **JHipster Version(s)**

4.7.0

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
aratu@0.0.0 D:\des\aratu
+-- generator-jhipster@4.7.0 
`-- UNMET PEER DEPENDENCY popper.js@^1.11.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.willcrisis.aratu",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "aratu",
    "packageName": "com.willcrisis.aratu",
    "packageFolder": "com/willcrisis/aratu",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Produto (produto) {
  nome String required minlength(1) maxlength(200),
  unidadeMedida String required minlength(2) maxlength(10),
  quantidadeEstoque Integer required
}

paginate Produto with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.1.windows.1

node: v6.11.2

npm: 3.10.10

bower: 1.8.0

gulp:
[22:34:30] CLI version 1.4.0

yeoman: 2.0.0

yarn: 0.27.5

Execution complete

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Provided above.

##### **Browsers and Operating System**

* Windows 10
* Google Chrome 60.0.3112.113

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Have you deployed or added heroku before to the generated application? Otherwise the required heroku setup and plugin is not added to the build script I think.

**Comment by jdubois** [comment]
Yes @atomfrede is right, you need to deploy first so everything is created for you

**Comment by willcrisis** [comment]
Ok. Realized that after running `jhipster heroku` everything worked fine. Shouldn't this information be on the docs? Preferrable at [Setting up Continuous Integration](http://www.jhipster.tech/setting-up-ci/) section.

**Comment by jdubois** [comment]
Yes indeed - I'm having a look at this, could you then review what I write?

**Comment by jdubois** [comment]
In fact I'm not sure you shouldn't first deploy to Heroku when using Maven, also (in order to generate the app + database configuration).

-> @pascalgrimaud as you coded this, could you have a look? Could you improve the "deploy to Heroku" section?

**Comment by pascalgrimaud** [comment]
yes back from holidays, I will have a look on this

**Comment by jdubois** [comment]
Thanks @pascalgrimaud :-)
