### ISSUE TITLE
deploy on Tomcat 7 + ubuntu not working

### ISSUE THREAD

**Issue by thiagonuic** [jhipster/generator-jhipster#630]
Hi,

I am trying to deploy on tomcat 7 + ubuntu 14.04LTS and the tomcat is not loading spring-boot backend. At first I thought it was something on my application, but I did the following commands:
yo jhipster (default options with postgresql)
mvn package

copied the .war.original file and renamed to ROOT.war in the webapps folder.

And did't work either.

**Comment by nnimmaga** [comment]
I am trying to deploy on Tomcat 8 Ubuntu 14.04.3 LTS + Tomcat 8.0.30
1. mvn package to build the war
2. Renamed the war as ROOT.war (assuming it is a must)
3. placed the war in webapps folder of Tomcat server.

WAR got unzipped.

I see the following in logs

29-Feb-2016 12:04:34.920 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /sandboxes/waygum/utils/apache-tomcat-8.0.30/webapps/ROOT.war
org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /sandboxes/waygum/utils/apache-tomcat-8.0.30/webapps/ROOT.war has finished in 8,944 ms

As you see, the WAR is not deployed
If it is deployed, it does tell me that Server has started

**Comment by gmarziou** [comment]
Please don't comment an old and closed issue, open a new one and provide required details.
