### ISSUE TITLE
Online-generated app doesn't show the menu Languages

### ISSUE THREAD

**Issue by yfain** [jhipster/generator-jhipster#6301]
##### **Overview of the issue**

The online-generated monolithic app doesn't show the menu Languages, while the locally-generated app does.

##### **Motivation for or Use Case**

The online-generated app should be consistent with locally-generated app in terms of the internationalization support.

##### **Reproduce the error**

Download and run the newly generated monolithic app from http://bit.ly/2gmzZN7

##### **JHipster info**
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
nyc-1@0.0.0 /Users/yfain11/Downloads/nyc1
└── generator-jhipster@4.7.0 

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitHubOrganization": "",
    "baseName": "nyc1",
    "packageName": "io.github.jhipster.application",
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "enableTranslation": false,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ru"
    ],
    "clientFramework": "angularX",
    "jhipsterVersion": "4.7.0",
    "packageFolder": "io/github/jhipster/application",
    "jwtSecretKey": "replaced-by-jhipster-info",
    "jhiPrefix": "jhi"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.10.1

node: v8.1.3

npm: 5.3.0

yeoman: 2.0.0

yarn: 0.27.5

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245

Execution complete

##### **Browsers and Operating System**

MAC OS 10.11.6,  Chrome 60

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
I think this issue should be opened on this tracker: https://github.com/jhipster/jhipster-online/issues as it doesn't concern the generator itself.

Anyway, can you try running the `jhipster` command again in your generated app. If the app was corectly generated by JHipster Online there should be no conflict.

**Comment by yfain** [comment]
Opened this issue here: https://github.com/jhipster/jhipster-online/issues/15
