### ISSUE TITLE
EntityRepository generator in jhipster for microservices still refers to User object

### ISSUE THREAD

**Issue by ganeshkrishnan1** [jhipster/generator-jhipster#6304]
Line 71 _EntityRepository.java of generator generates entity object with incorrect SQL

   @Query("select <%= entityTableName %> from <%= entityClass %> <%= entityTableName %> where <%= entityTableName %>.<%= relationships[idx].relationshipFieldName %>.login = ?#{principal.username}")

For microservices (with oauth or otherwise) the principal object is not longer User object (as that is somewhere else on uaa project) and is a string. hence this generated sql with principal.username fails as principal is a string object now not a User object (as it was in earlier versions of jhipster)
 

For example the below code generated with jhipster 4.7.0 would fail
    @Query("select salesForecast from SalesForecast salesForecast where salesForecast.userId = ?#{principal.username}")
    List<SalesForecast> findByUserIsCurrentUser();

The query has to be
    @Query("select salesForecast from SalesForecast salesForecast where salesForecast.userId = ?#{principal}")
    List<SalesForecast> findByUserIsCurrentUser();

**Comment by ganeshkrishnan1** [comment]
And to add to this, this is only for micro-services project and not monoliths. Not sure how to fix this in _EntityRepository.java for the generator

**Comment by deepu105** [comment]
These queries should not be generated for microservice

**Comment by pascalgrimaud** [comment]
See https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/server/src/main/java/package/repository/_EntityRepository.java#L68-L73
There is a condition `if (relationships[idx].relationshipType === 'many-to-one' && relationships[idx].otherEntityName === 'user') {` so it should not be generated

It depends on your configuration, your entities and what you did.
Can you provide all your information, using `jhipster:info` for every of your projects plz ?

**Comment by ganeshkrishnan1** [comment]
So it seems on microservices (or anything other than uaa) User is a reserved entity. 
This seems to be a edge case when a custom User object is created on a micro service (or gateway)

**Comment by pascalgrimaud** [comment]
Yes, User is a reserved entity. You need to choose another name.
So it seems there is no issue, I'm closing this.
