### ISSUE TITLE
Add Client side Vue.js support

### ISSUE THREAD

**Issue by harryho** [jhipster/generator-jhipster#6305]
* **Overview of the request**

* **Motivation for or Use Case** 

* **Browsers and Operating System** 

* **Related issues** 

* **Suggest a Fix**

**Comment by deepu105** [comment]
Please follow our guidelines. Current focus is to add React. There is a VueJS module from our core team check that out

**Comment by donalmurtagh** [comment]
@deepu105 could you provide a link to this VueJS module?

**Comment by mraible** [comment]
@donalmurtagh There is no Vue.js module.

**Comment by deepu105** [comment]
@mraible there is one from @atomfrede :smile: 
http://www.jhipster.tech/modules/marketplace/#/details/generator-jhipster-vuejs

**Comment by donalmurtagh** [comment]
Although this Vue.js module does indeed exist, [by the author's own admission](https://github.com/atomfrede/generator-jhipster-vuejs/issues/3) it is far from production ready.

Is supporting alternative JS frameworks such as Vue and React on the roadmap at all?

**Comment by jdubois** [comment]
Yes it is - please, this is the bug tracking system, don't spam everyone if you don't have a real bug

**Comment by donalmurtagh** [comment]
> Yes it is

Do you mean, "Yes, it is production ready" or "Yes, it is _not_ production ready"?
If this is not the right place for such discussions, where would be more appropriate, Gitter?

**Comment by jdubois** [comment]
@donalmurtagh I was answering to the comment you deleted, which asked `Is supporting alternative JS frameworks such as Vue and React on the roadmap at all?`
So yes it's on the roadmap, then it's OSS, so it depends on who does it.
And yes Gitter is a better place for chatting.

**Comment by dotw** [comment]
how about the progress now?
