### ISSUE TITLE
Support for embedded and elementcollection

### ISSUE THREAD

**Issue by acartapanis** [jhipster/generator-jhipster#6306]
Please add support for Embedded and ElementCollection.
The main requirement is to be able to add a simple entity, that is embedded in a standard entity rather that have his own table/collection.

Typical sample is an Address class, that only contains a few strings. Address object is used by many other entities, but we do not want do create a table of addresses.

Element collection is simply a collection of primitive type or embedded elements.

In SQL/Hibernate it could be mapped to @Embedded and @ElementCollection.
In NoSQL it could be mapped to subdocument, or subdocument array.

In JDL, there could be an embeddable type for the definition of the entity, and or embedded or elementCollection type for the definition of the relationship.

Exemple :
```
embeddable Address {
    city String
}
entity User {
    name String
}
relationship Embedded {
   User{address} to  Address
}
relationship ElementCollection {
    User{addresses} to Address
}
relationship ElementCollection {
    User{loginDates} to Instant // for a collection of primitive type
}
```

For angular, there is no need of a specific pages to edit those entities, rather having en embedded popup for exemple, or something like this.

**Comment by jdubois** [comment]
- Totally understand the use case, in fact I'm doing this quite often personally
- But that's a lot of work: the JDL part, the Java part, and most importantly the AngularJS/Angular/React parts...

-> for me we can't have a high priority for this at the moment (as we are going to add the React support), but I really see this as a "best practice" not many people use, and I would love to push this

Now my problem is that I don't want to have too many opened tickets for too long, and I guess this might take a few months - what do other people think? Would someone be ready to do this feature? Maybe without the front-end part, so we could have a first working implementation sooner?

**Comment by pascalgrimaud** [comment]
Agree with you @jdubois 
Currently, it is really faster to directly code to your personnal project, than coding all parts (JDL, Java, Front, etc.) in the generator. As you said, it can take weeks/months to code everything, for all database.

Not sure it is worth it... Maybe @acartapanis you want to contribute for a first working implementation?

**Comment by jdubois** [comment]
In fact @pascalgrimaud that means this ticket would be against [Policy 2](http://www.jhipster.tech/policies/) and this is why I'm closing it.
Anyway, we can't develop this at the moment, the back-end code must be stable while we finish ReactJS support.

**Comment by haresh333** [comment]
What if you use TypeORM with MongoDB? With that u can generate embedded entities and interface with MongoDB. With probably minimal change the embeded document support can be implemented. On Angualr you many not have to do many changes

**Comment by coolduebtn** [comment]
Do you plan to do this soon ? I am designing my model and felt the strong need need for embedded at multiple places. Was a bit disappointed to not find it in jhipster.

**Comment by pascalgrimaud** [comment]
@coolduebtn : I totally understand your need. But we can't add all features in JHipster as it's a lot of work for us. Just keep in mind we are doing this during our free time, during evening and week-end. We are not paid for that. So if no one want to contribute and do this, it will never be done.

About this feature, I still thing the same:
> Currently, it is really faster to directly code to your personnal project, than coding all parts (JDL, Java, Front, etc.) in the generator. As you said, it can take weeks/months to code everything, for all database.

**Comment by coolduebtn** [comment]
@pascalgrimaud totally understand . thanks for the fast response.. :+1:

**Comment by cbornet** [comment]
And of course PRs are welcome. It could be done step by step. First for apps without front-end (micro-service), for a given DB type (eg. SQL), etc ...
