### ISSUE TITLE
Angularjs website not running on safari (on desktop)

### ISSUE THREAD

**Issue by arushijain45** [jhipster/generator-jhipster#6313]
I have created an angularjs website with generator-jhipster. It is working nicely in all browsers except safari (on desktop). It is working even in iPhone but the website is not able to open in Safari on desktop.

After inspecting I can find following error:

> [$injector:modulerr] Failed to instantiate module movementsJhipsterOauth2App due to:
> [$injector:nomod] Module 'movementsJhipsterOauth2App' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I am not getting what the error is all about as it is opening in other browsers without any error. Please suggest some solution.

**Version**: generator-jhipster 2.18.0
**Angular Version**: Angular 1.4.8
**Configuration**:
{
  "generator-jhipster": {
    "baseName": "movements_jhipster_oauth2",
    "packageName": "com.xxx.xxx",
    "packageFolder": "com.xxx.xxx",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "7",
    "enableTranslation": false,
    "rememberMeKey": "xxx"
  }
}
**Browsers**: Safari
**OS**: MacOS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry but JHipster 2.x is so old, this is bound to happen. 
And we cannot support such an old release.

**Comment by arushijain45** [comment]
So I got my answer myself. Anyone else suffering from this issue please check every state in stateProvider.
I had params defined two times in one of my state like this:

> .state('state1', {
>         url: '/url',
>         params:{
>             'data1' : {}
>         },,
>         params:{
>             'data2' : {}
>         },
>         views: {
>             'content@': {
>                 templateUrl: 'xxx',
>                 controller: 'xxx'
>             }
>         },
>         resolve: {
>         }
>     })

Adding data2 in first block of param removed my issue for Safari.

**Comment by jdubois** [comment]
Thanks for posting your answer!!! Too few people do this

**Comment by gmarziou** [comment]
@arushijain45 sorry that you spent time on this as tools can spot it within seconds.
Running `gulp eslint` (`grunt slint`in your case) first detects  `,,`:

~~~
[17:31:35] gulp-notify: [JHipster Gulp Build] Error: Parsing error: Unexpected token ,
[17:31:35] Finished 'eslint' after 2.24 s
[17:31:40]
e:\projets\issues\jhipster-sample-app\src\main\webapp\app\app.state.js
  14:19  error  Parsing error: Unexpected token ,

✖ 1 problem (1 error, 0 warnings)
~~~

Fixing it and re-running again detects the repeated `param` 

~~~
[17:32:36] gulp-notify: [JHipster Gulp Build] Error: Parsing error: Redefinition of property
[17:32:36] Finished 'eslint' after 874 ms
[17:32:40]
e:\projets\issues\jhipster-sample-app\src\main\webapp\app\app.state.js
  15:17  error  Parsing error: Redefinition of property

✖ 1 problem (1 error, 0 warnings)
~~~
