### ISSUE TITLE
Routes not being correctly allowed by the UserRouteAccessService

### ISSUE THREAD

**Issue by thainan10** [jhipster/generator-jhipster#6318]
##### **Overview of the issue**

The `UserRouteAccessService` route guard is not correctly allowing routes by the user's authorities.

##### **Motivation for or Use Case**

I've created a component route, added this guard into it and tried to access this route with a simple user. It gives me access to this route.

##### **Reproduce the error**

Do the steps cited in the Use Case section.

##### **Suggest a Fix**

I suggested a fix in the PR [#6276](https://github.com/jhipster/generator-jhipster/pull/6276)

##### **JHipster Version(s)**

4.7.0

### .yo-rc.json file
> {
>   "generator-jhipster": {
>     "promptValues": {
>       "packageName": "br.com.dynavideo.cinema.gateway",
>       "nativeLanguage": "en"
>     },
>     "jhipsterVersion": "4.7.0",
>     "baseName": "cinema",
>     "packageName": "br.com.dynavideo.cinema.gateway",
>     "packageFolder": "br/com/dynavideo/cinema/gateway",
>     "serverPort": "8080",
>     "authenticationType": "jwt",
>     "hibernateCache": "ehcache",
>     "clusteredHttpSession": false,
>     "websocket": false,
>     "databaseType": "sql",
>     "devDatabaseType": "postgresql",
>     "prodDatabaseType": "postgresql",
>     "searchEngine": false,
>     "messageBroker": false,
>     "serviceDiscoveryType": "eureka",
>     "buildTool": "maven",
>     "enableSocialSignIn": false,
>     "clientFramework": "angular2",
>     "useSass": true,
>     "clientPackageManager": "yarn",
>     "applicationType": "gateway",
>     "testFrameworks": [],
>     "jhiPrefix": "jhi",
>     "enableTranslation": true,
>     "nativeLanguage": "en",
>     "languages": [
>       "en"
>     ]
>   }
> }

##### **Browsers and Operating System**

Running in ElementaryOs, but tested in Ubuntu, MacOSX and Windows, in the browsers Chrome, Firefox, Safari and Epiphany.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Closing as the PR is merged (next time, please automatically close the ticket with your commit - have a look at the "fix" keyword in GitHub and in our guidelines)
