### ISSUE TITLE
Editing entities with Instant property converts date wrong in IE11

### ISSUE THREAD

**Issue by stieler-it** [jhipster/generator-jhipster#6321]
##### **Overview of the issue**

When working with entities and the data type "Instant" the date is shown wrong when opening an entity for editing.

##### **Motivation for or Use Case**

All data types should work with supported browsers, even if it is IE.

##### **Reproduce the error**

Generate application, start and login, goto a list of entities, click edit on any entity containing a date.

Expected behaviour: The correct date of the entity is shown in the input box, e.g. `1. Dez 2017 14:00:00` (German locale). Even if IE has no custom input type for dates, I would expect to see something that can be saved without corrupting the data.

Actual behaviour: The input box shows a wrong format, e.g. `2017-12-01T02:01.12.2017 14:00:00`. Clicking on save without any changes, the date fields are corrupted.

When replacing the shown value with e.g. an ISO 8601 date string, it is saved correctly.

##### **Related issues**

Nothing found.

##### **Suggest a Fix**

I debugged and stepped into the entity service and verified that the conversion is done correct until there.

That means the following line:
`entity.from = this.dateUtils.convertDateTimeFromServer(entity.from);`

works as expected and converts the ISO 8601 string into a Javascript date.

I have not yet understood what happens after that, though.

##### **JHipster Version(s)**

4.6.2

##### **JHipster configuration**

.yo-rc.json

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.hidden",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "hidden",
    "packageName": "de.hidden",
    "packageFolder": "de/hidden",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "oracle",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
    "fields": [
        {
            "fieldName": "from",
            "fieldType": "Instant",
            "fieldValidateRules": [
                "required"
            ]
        }
    ]
```

##### **Browsers and Operating System**

The problem occurs in IE11, Chrome works and shows the browser native datetime input.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Unfortunately nobody on the team has a Windows machine so we can't test this easily... If you find a solution (or anybody else), I'll be happy to merge it.

**Comment by stieler-it** [comment]
We tracked this down further and it appears to be a [bug](https://github.com/angular/angular/issues/9524) in Angular's date pipe that will be fixed in Angular 5.x. If we decide to fix this using a workaround for JHipster I will let you know.

**Comment by jdubois** [comment]
Thanks a lot!! If you don't find a workaround, then we'll close this as we can't test it and we can't do workarounds for all Angular bugs - we'll upgrade to Angular 5 when it's ready anyway.

**Comment by deepu105** [comment]
I'm closing this as the core team wont be doing anything here. @stieler-it if you find a workaround please do a PR linking to this ticket

**Comment by stieler-it** [comment]
Our workaround ist *not* using the Angular date pipe. I think we ended using momentjs to format the date.  Since Angular 5 will be fixed and is expected for next month, I think we shouldn't invest time in a workaround but try to adopt the new version in time.
