### ISSUE TITLE
After session expires, login page doesn't popup

### ISSUE THREAD

**Issue by rubenrobles** [jhipster/generator-jhipster#6323]
##### **Overview of the issue**

After a session expires, the login popup fails.  Users see the page they clicked on without data (See attached image, which shows the error).  The Access denied or Login page don't appear after the session expires.

##### **Motivation for or Use Case**
Behavior was available in prior versions

##### **Suggest a Fix**

Working on Angular 4 for the first time coming from AngularJS. 

##### **JHipster Version(s)**
4.7

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.lucrotest",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "lucrotest",
    "packageName": "com.lucrotest",
    "packageFolder": "com/lucrotest",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

NA

##### **Browsers and Operating System**

Ubuntu 16.04 LTS
Chrome Version 60.0.3112
![screenshot from 2017-09-06 22-54-24](https://user-images.githubusercontent.com/3465458/30149251-c550238a-935b-11e7-887e-115668783e51.png)
.113 (Official Build) (64-bit)
Firefox 49 

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This has changed slightly recently as the error handling has been improved: you don't have the stacktrace in the console anymore.
But yes, I confirm the issue.

**Comment by jdubois** [comment]
I'm committing the solution that solves the error, but the UX is still not 100% perfect. At least it should work like in AngularJS 1.

**Comment by jdubois** [comment]
The UX issue is that when it fails I can't get the current route, so I'm redirecting to the main route - at the same time, as we have a session, this isn't probably a good idea to keep the current route and try to go to it.

**Comment by rubenrobles** [comment]
I agree.  Current solution works and makes sense.  Thanks!
