### ISSUE TITLE
Bootstrap hidden classes changed with 4.0.0-beta

### ISSUE THREAD

**Issue by uyeliksiz** [jhipster/generator-jhipster#6344]
##### **Overview of the issue**

`hidden-*-down` and `hidden-*-up` css classes removed

##### **Motivation for or Use Case**

responsive buttons are not working

##### **Reproduce the error**

`hidden-*-up` and `hidden-*-down` classes are removed and 
`d-none` `d-block` `d-inline` `d-*-block` `d-*-none` are added

##### **Suggest a Fix**

- replace all buttons which have `hidden-` classes  ( `<span class="hidden-md-down">`) with  ( ` <span class="d-none d-md-inline"> ` )

- and replace any other `hidden-*-down` and` hidden-*-up` classes

- https://stackoverflow.com/a/45667422

##### **JHipster Version(s)**

4.7.0

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Closing as PR is merged
