### ISSUE TITLE
LocalDate format changed when relation entity saved

### ISSUE THREAD

**Issue by ghost** [jhipster/generator-jhipster#6349]
##### **Overview of the issue**
I have created 2 entities : 

```
entity Employee {
	firstName String,
	hireDate LocalDate
}
entity Job {
    jobTitle String,
    jobDate LocalDate
}
relationship OneToMany {
	Employee{job} to Job
}
```

Job entity can be saved successfully and job.jobDate LocalDate format string (like : "2017-09-16") passed to server when saving.
But when saving the employee entity , it also sends the Job detail to server where
emplyee.hireDate is like "2017-09-16" (valid)
job.jobDate is like "2017-09-15T18:30:00.000Z"
 
##### **Motivation for or Use Case**

When saving employee entity the relationship field Job data should be passed to server in same format as received from server.

##### **Reproduce the error**

Use the same relationship with LocalDate. Check the chrome -> network.

##### **JHipster Version(s)**

v4.7.0

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "sample"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "myapp",
    "packageName": "sample",
    "packageFolder": "sample",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "931cedeed30165c39aa342d17013ab704c01e419",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
- I confirm the issue
- This does not do any bug on the generated code, as we only save a "job", and not the whole graph of objects -> so in the end nothing bad happens in the generated application

Of course, if you decide to use the "employee" object, then in fact the date will be changed, you are right.

I'm not sure what the correct solution would be here:

-> @ghost a PR or some comments on how you solved this are welcome

**Comment by duderoot** [comment]
In order to have the **hireDate** as a string of form '**yyyy-MM-dd**' one can transform the **hireDate** which is a JavaScript Date object before sending to the server in the proper format.
[JhiDateUtils](https://github.com/jhipster/ng-jhipster/blob/master/src/service/date-util.service.ts) has some methods for transforming the date from JSON to JavaScript and vice versa.  I am questioning what will be the benefit of transforming the **hireDate** before sending it to the server. On the server side one receive the **hireDate** as a LocalDate object.

**Comment by duderoot** [comment]
@jdubois I suggest closing this since IMHO there is a solution there how to work with the date in the client site or @ghost do you have any suggestion or need some more help to solve your problem?

**Comment by jdubois** [comment]
I'd rather have a "clean" solution, but indeed we could close this - let's wait a little bit to have more comments

**Comment by gmarziou** [comment]
After reading [this article](http://codeboje.de/jackson-java-8-datetime-handling/) I'm wondering whether our Jackson config is right. Spring Boot team might change default for 2.0: https://twitter.com/olivergierke/status/932209641915895813

**Comment by cbornet** [comment]
@gmarziou we already serialize datetimes as string with the JavaTimeModule

**Comment by jdubois** [comment]
Not a lot of comments, so I'm closing this!
