### ISSUE TITLE
@project.build.finalName@.war: no such file or directory in Dockerfile

### ISSUE THREAD

**Issue by pierre-filliolaud** [jhipster/generator-jhipster#6353]
##### **Overview of the issue**

The commit 258649bd14939aabaeebfe4daff913827182eca2 has introduced a regression in generated Dockerfile (from generators/server/templates/src/main/docker/_Dockerfile).

-# add directly the war
 -ADD *.war /app.war
+ADD @project.build.finalName@.war /app.war

+ docker build -t filliolaud/plumber build/docker
Sending build context to Docker daemon  84.59MB

Stacktrace:
Step 1/5 : FROM openjdk:8-jre-alpine
 ---> 58ce9579eac6
Step 2/5 : ENV SPRING_OUTPUT_ANSI_ENABLED ALWAYS JHIPSTER_SLEEP 0 JAVA_OPTS ""
 ---> Using cache
 ---> d8dea482c51d
Step 3/5 : ADD @project.build.finalName@.war /app.war
lstat @project.build.finalName@.war: no such file or directory
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

##### **Motivation for or Use Case**

Generate a jhipster project with gradle and generated Dockerfile with ci-cd command:
jhipster ci-cd

##### **Related issues**

issue introduced by commit 258649bd14939aabaeebfe4daff913827182eca2

##### **Suggest a Fix**

In generators/server/templates/src/main/docker/_Dockerfile
Replace:
ADD @project.build.finalName@.war /app.war

By:
ADD *.war /app.war

##### **JHipster Version(s)**

v4.8.1

##### **Environment and Tools**

java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

git version 2.14.1

node: v6.9.5

npm: 4.1.2

bower: 1.8.0

gulp:
[16:37:53] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.09.0-ce-rc1, build ae21824

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

OsX 10.12.3

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I see you are using Gradle, is this related to #6348 ?

**Comment by pierre-filliolaud** [comment]
yes. It seems that it is the same issue.

**Comment by atomfrede** [comment]
Using docker build directly won't work anymore. Should be same for maven. Will check

**Comment by jdubois** [comment]
OK @atomfrede can you tell me if #6354 would fix the issue?
I can do a release tomorrow, just tell me if/when you think everything is good (and next week it will be more complicated for me to do a release)

**Comment by PierreBesson** [comment]
Yes you should not build the docker image directly but use `./gradlew buildDocker`. There might be something broken about it for some use cases but there is a good reason I changed the `ADD *.war`. The *.war method had wasn't working if you didn't clean the build directory and had several war files.

**Comment by atomfrede** [comment]
@pierre-filliolaud If you use `docker build` directly this won't work anymore (both for gradle and maven) as we are doing the a filter here as @PierreBesson already said. So I think we should not merge https://github.com/jhipster/generator-jhipster/pull/6354 but maybe update our documentation or put something in the release notes that you must use maven or gradle to build a docker image.

**Comment by pierre-filliolaud** [comment]
Jenkinsfile should be fixed then. With PierreBesson's change, my Jenkins pipeline does not work for Docker task. By using ADD *.war, it works.

**Comment by atomfrede** [comment]
Have you used our ci-cd sub generator? I think you might be correct. Jenkins seem to call docker directly.

**Comment by pierre-filliolaud** [comment]
Yes, I use your sub ci-cd generator for Jenkinsfile.
My stack trace comes from my Jenkins pipeline logs.

**Comment by atomfrede** [comment]
@PierreBesson I've not used the new jenkins pipeline config, but I guess `dockerImage = docker.build('<%= baseName.toLowerCase() %>', 'build/docker')` is using a docker plugin, we should replace it with the corresponding build tool commands if possible.

**Comment by pascalgrimaud** [comment]
The only issue with *.war is for people who change the version of the project, then package+docker build without cleaning. They will have 2 war in the target or build folder, so it will fail. 

Otherwise, I don't see any other problem with that, so what about reverting and use *.war like before, @PierreBesson ?

**Comment by jdubois** [comment]
I agree with you Pascal, but if you do a prod build I would recommend you do a 'clean' first. Anyway, I remember doing this at the beginning and we had no issue with it.

**Comment by jdubois** [comment]
Not a perfect solution, but it's easy and it works...

**Comment by atomfrede** [comment]
OK, I will update that in the PR for https://github.com/jhipster/generator-jhipster/issues/6348 accordingly.

**Comment by PierreBesson** [comment]
The fix is merged and there is going to be a fix release so I'm closing this.
