### ISSUE TITLE
project fails to start after generating the project WINDOWS 7

### ISSUE THREAD

**Issue by kipierre** [jhipster/generator-jhipster#6355]
1. Overview of the issue

# Running  mvnw on generated project fails with compilation error
  mvnw compile runs successfully.

[ERROR]   location: class com.cephas.app.web.rest.AuditResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/LogsResource.
java:[9,32] package org.springframework.http does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/LogsResource.
java:[18,2] cannot find symbol
[ERROR]   symbol: class RestController
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/LogsResource.
java:[19,2] cannot find symbol
[ERROR]   symbol: class RequestMapping
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[16,19] package io.undertow does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[21,36] package org.springframework.web.cors does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[22,36] package org.springframework.web.cors does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[23,38] package org.springframework.web.filter does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[51,27] cannot find symbol
[ERROR]   symbol:   class ServletContext
[ERROR]   location: class com.cephas.app.config.WebConfigurer
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[51,65] cannot find symbol
[ERROR]   symbol:   class ServletException
[ERROR]   location: class com.cephas.app.config.WebConfigurer
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[118,47] cannot find symbol
[ERROR]   symbol:   class ServletContext
[ERROR]   location: class com.cephas.app.config.WebConfigurer
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[119,55] cannot find symbol
[ERROR]   symbol:   class DispatcherType
[ERROR]   location: class com.cephas.app.config.WebConfigurer
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[133,30] cannot find symbol
[ERROR]   symbol:   class ServletContext
[ERROR]   location: class com.cephas.app.config.WebConfigurer
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[133,69] cannot find symbol
[ERROR]   symbol:   class DispatcherType
[ERROR]   location: class com.cephas.app.config.WebConfigurer
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/WebConfigurer.j
ava:[157,12] cannot find symbol
[ERROR]   symbol:   class CorsFilter
[ERROR]   location: class com.cephas.app.config.WebConfigurer
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[6,38] package org.springframework.web.filter does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[8,21] package javax.servlet does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[9,21] package javax.servlet does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[10,21] package javax.servlet does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[11,21] package javax.servlet does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[12,26] package javax.servlet.http does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[19,32] cannot find symbol
[ERROR]   symbol: class GenericFilterBean
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[28,26] cannot find symbol
[ERROR]   symbol:   class ServletRequest
[ERROR]   location: class com.cephas.app.security.jwt.JWTFilter
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[28,57] cannot find symbol
[ERROR]   symbol:   class ServletResponse
[ERROR]   location: class com.cephas.app.security.jwt.JWTFilter
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[28,90] cannot find symbol
[ERROR]   symbol:   class FilterChain
[ERROR]   location: class com.cephas.app.security.jwt.JWTFilter
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[29,29] cannot find symbol
[ERROR]   symbol:   class ServletException
[ERROR]   location: class com.cephas.app.security.jwt.JWTFilter
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/jwt/JWTFilter
.java:[39,33] cannot find symbol
[ERROR]   symbol:   class HttpServletRequest
[ERROR]   location: class com.cephas.app.security.jwt.JWTFilter
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/ThymeleafConfig
uration.java:[7,38] package org.thymeleaf.templateresolver does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/ThymeleafConfig
uration.java:[17,12] cannot find symbol
[ERROR]   symbol:   class ClassLoaderTemplateResolver
[ERROR]   location: class com.cephas.app.config.ThymeleafConfiguration
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[19,32] package org.springframework.http does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[20,32] package org.springframework.http does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[31,2] cannot find symbol
[ERROR]   symbol: class RestController
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[32,2] cannot find symbol
[ERROR]   symbol: class RequestMapping
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[62,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.AccountResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[94,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.AccountResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[108,35] cannot find symbol
[ERROR]   symbol:   class HttpServletRequest
[ERROR]   location: class com.cephas.app.web.rest.AccountResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[120,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.AccountResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[134,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.AccountResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[159,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.AccountResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[176,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.AccountResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AccountResour
ce.java:[194,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.AccountResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserResource.
java:[23,32] package org.springframework.http does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserResource.
java:[61,2] cannot find symbol
[ERROR]   symbol: class RestController
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserResource.
java:[62,2] cannot find symbol
[ERROR]   symbol: class RequestMapping
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserResource.
java:[100,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.UserResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserResource.
java:[136,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.UserResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserResource.
java:[160,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.UserResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserResource.
java:[184,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.UserResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserResource.
java:[200,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.UserResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/ProfileInfoRe
source.java:[17,2] cannot find symbol
[ERROR]   symbol: class RestController
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/ProfileInfoRe
source.java:[18,2] cannot find symbol
[ERROR]   symbol: class RequestMapping
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/util/HeaderUt
il.java:[18,19] cannot find symbol
[ERROR]   symbol:   class HttpHeaders
[ERROR]   location: class com.cephas.app.web.rest.util.HeaderUtil
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/util/HeaderUt
il.java:[25,19] cannot find symbol
[ERROR]   symbol:   class HttpHeaders
[ERROR]   location: class com.cephas.app.web.rest.util.HeaderUtil
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/util/HeaderUt
il.java:[29,19] cannot find symbol
[ERROR]   symbol:   class HttpHeaders
[ERROR]   location: class com.cephas.app.web.rest.util.HeaderUtil
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/util/HeaderUt
il.java:[33,19] cannot find symbol
[ERROR]   symbol:   class HttpHeaders
[ERROR]   location: class com.cephas.app.web.rest.util.HeaderUtil
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/util/HeaderUt
il.java:[37,19] cannot find symbol
[ERROR]   symbol:   class HttpHeaders
[ERROR]   location: class com.cephas.app.web.rest.util.HeaderUtil
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserJWTContro
ller.java:[12,32] package org.springframework.http does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserJWTContro
ller.java:[21,26] package javax.servlet.http does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserJWTContro
ller.java:[28,2] cannot find symbol
[ERROR]   symbol: class RestController
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserJWTContro
ller.java:[29,2] cannot find symbol
[ERROR]   symbol: class RequestMapping
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserJWTContro
ller.java:[45,74] cannot find symbol
[ERROR]   symbol:   class HttpServletResponse
[ERROR]   location: class com.cephas.app.web.rest.UserJWTController
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/UserJWTContro
ller.java:[45,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.UserJWTController
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/errors/Except
ionTranslator.java:[9,32] package org.springframework.http does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/errors/Except
ionTranslator.java:[15,31] cannot find symbol
[ERROR]   symbol:   class HttpRequestMethodNotSupportedException
[ERROR]   location: package org.springframework.web
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/errors/Except
ionTranslator.java:[16,36] package org.springframework.web.bind does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/errors/Except
ionTranslator.java:[22,2] cannot find symbol
[ERROR]   symbol: class ControllerAdvice
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/errors/Except
ionTranslator.java:[37,43] cannot find symbol
[ERROR]   symbol:   class MethodArgumentNotValidException
[ERROR]   location: class com.cephas.app.web.rest.errors.ExceptionTranslator
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/errors/Except
ionTranslator.java:[64,55] cannot find symbol
[ERROR]   symbol:   class HttpRequestMethodNotSupportedException
[ERROR]   location: class com.cephas.app.web.rest.errors.ExceptionTranslator
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/errors/Except
ionTranslator.java:[69,12] cannot find symbol
[ERROR]   symbol:   class ResponseEntity
[ERROR]   location: class com.cephas.app.web.rest.errors.ExceptionTranslator
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/util/Paginati
onUtil.java:[5,36] package org.springframework.web.util does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/util/Paginati
onUtil.java:[22,19] cannot find symbol
[ERROR]   symbol:   class HttpHeaders
[ERROR]   location: class com.cephas.app.web.rest.util.PaginationUtil
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/util/Paginati
onUtil.java:[49,19] cannot find symbol
[ERROR]   symbol:   class HttpHeaders
[ERROR]   location: class com.cephas.app.web.rest.util.PaginationUtil
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/social/Custom
SignInAdapter.java:[17,47] package org.springframework.web.context.request does
not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/social/Custom
SignInAdapter.java:[19,47] package org.springframework.web.context.request does
not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/social/Custom
SignInAdapter.java:[20,26] package javax.servlet.http does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/social/Custom
SignInAdapter.java:[42,67] cannot find symbol
[ERROR]   symbol:   class NativeWebRequest
[ERROR]   location: class com.cephas.app.security.social.CustomSignInAdapter
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/security/social/Custom
SignInAdapter.java:[61,13] cannot find symbol
[ERROR]   symbol:   class Cookie
[ERROR]   location: class com.cephas.app.security.social.CustomSignInAdapter
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/SocialControl
ler.java:[12,47] package org.springframework.web.context.request does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/SocialControl
ler.java:[15,2] cannot find symbol
[ERROR]   symbol: class RestController
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/SocialControl
ler.java:[16,2] cannot find symbol
[ERROR]   symbol: class RequestMapping
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/SocialControl
ler.java:[31,32] cannot find symbol
[ERROR]   symbol:   class WebRequest
[ERROR]   location: class com.cephas.app.web.rest.SocialController
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/ElasticsearchCo
nfiguration.java:[10,47] package org.springframework.http.converter.json does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/ElasticsearchCo
nfiguration.java:[19,71] cannot find symbol
[ERROR]   symbol:   class Jackson2ObjectMapperBuilder
[ERROR]   location: class com.cephas.app.config.ElasticsearchConfiguration
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/SecurityConfigu
ration.java:[11,32] package org.springframework.http does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/SecurityConfigu
ration.java:[24,38] package org.springframework.web.filter does not exist
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/SecurityConfigu
ration.java:[39,19] cannot find symbol
[ERROR]   symbol:   class CorsFilter
[ERROR]   location: class com.cephas.app.config.SecurityConfiguration
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/config/SecurityConfigu
ration.java:[43,9] cannot find symbol
[ERROR]   symbol:   class CorsFilter
[ERROR]   location: class com.cephas.app.config.SecurityConfiguration
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AuditResource
.java:[39,6] cannot find symbol
[ERROR]   symbol:   class GetMapping
[ERROR]   location: class com.cephas.app.web.rest.AuditResource
[ERROR] /C:/Users/cephas/jhk/src/main/java/com/cephas/app/web/rest/AuditResource
.java:[56,10] cannot find symbol
[ERROR]   symbol:   class RequestParam
[ERROR]   location: class com.cephas.app.web.rest.AuditResource
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Motivation for or Use Case

Generated project should run without any compilation error.

Below is the .yo-rc.json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.cephas.app",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "jhk",
    "packageName": "com.cephas.app",
    "packageFolder": "com/cephas/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "7ef16f2860fe7a49cf82a6f24ef263d7655867b8",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}

mvn -v

Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:0
6+02:00)
Maven home: C:\Program Files\apache-maven-3.5.0\bin\..
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_60\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"

**Comment by jdubois** [comment]
`package org.springframework.web.cors` how is this even possible? Are you sure your Maven repository works correctly?

**Comment by jdubois** [comment]
Please follow our guidelines next time, this is really annoying for me to test...

Anyway, I can't reproduce, so this is definitely a problem with your Maven repo.
