### ISSUE TITLE
Feature request: Add Docker Organization Name in Jenkinsfile for publishing correctly on DockerHub

### ISSUE THREAD

**Issue by pierre-filliolaud** [jhipster/generator-jhipster#6365]
##### **Overview of the issue**
Add Docker Organization Name in Jenkinsfile during task "publishDocker/build docker". By default, it should be set to docker login. 

##### **Motivation for or Use Case**
Actually, each Jenkinsfile created by sub generator ci-cd command must be re-edited by adding the correct organization name (or docker login) before publishing on DockerHub:
dockerImage = docker.build('organizationName/projectName', 'build/docker')

##### **Reproduce the error**
Generate a JHipster project
Execute ci-cd command to generate Jenkinsfile.
Check the Jenkinsfile, by default it does not contain the organization name in docker.build()
Jenkins is not able to push the docker image to Docker hub

Stacktrace:
The push refers to a repository [registry.hub.docker.com/sample]
43866f53717b: Preparing
5c9f60e933c4: Preparing
68816a1ad86d: Preparing
3fb66f713c9f: Preparing
error parsing HTTP 404 response body: invalid character '<'

##### **Suggest a Fix**

Files to enhance:
/generator-jhipster/generators/ci-cd/templates/jenkins/_Jenkinsfile
/generator-jhipster/generators/ci-cd/prompts.js

##### **JHipster Version(s)**

Using JHipster version installed globally
4.8.1

##### **Environment and Tools**

java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

git version 2.14.1

node: v6.9.5

npm: 4.1.2

bower: 1.8.0

gulp:
[15:05:47] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.09.0-ce-rc1, build ae21824

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

OsX 10.12.3
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pierre-filliolaud** [comment]
Linked to PR #6366

**Comment by ruddell** [comment]
Closing as the PR was merged
