### ISSUE TITLE
Property 'sort' does not exist on type 'SampleComponent'

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#6370]
Issue with the latest release. Property 'sort' does not exist on type 'SampleComponent'

Created application with this configuration

![image](https://user-images.githubusercontent.com/11784253/30509765-9235062e-9ad5-11e7-9c70-0016df276dce.png)

When I created a entity using _**yo jhipster:entity Sample**_ i got this issue

![image](https://user-images.githubusercontent.com/11784253/30509752-50bfe970-9ad5-11e7-8b37-7ab7ed93ce29.png)

**Comment by jdubois** [comment]
Please follow the guidelines and send your configuration, we can't work like that...

**Comment by gmarziou** [comment]
@JinnaBalu it's the 3rd issue you open without following guidelines, is there something you don't understand in how we work? #6262 #6256

**Comment by Georangelg** [comment]
Que mamones, si no van a ayudar mejor ni comenten :D

**Comment by gmarziou** [comment]
Please stay polite @Georangelg

**Comment by jdubois** [comment]
@Georangelg this does not follow our code of conduct, I will fill an abuse request and ban you from the project.
