### ISSUE TITLE
www.jhipster.tech not easily searchable

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#6375]
##### **Overview of the issue**

- search input is not easily found at the very bottom of the page, it should be at the top
- google indexation could be tuned, searching for "upgrade" returns all release notes before "Upgrading an application" doc which is due to release notes content being very repetitive

**Comment by PierreBesson** [comment]
I think we could apply for Algolia open source plan : https://www.algolia.com/for-open-source. Their search tools are very powerful and useful. The only restriction is that the free plan is strictly for non commercial use (not a problem yet as we are strictly non commercial for now).
For examples, see: https://community.algolia.com/instantsearch.js/documentation/

**Comment by gmarziou** [comment]
Before using another tool, I'd like to try tune google indexing first by using [`<!--googleoff: index-->`](https://www.google.com/support/enterprise/static/gsa/docs/admin/70/gsa_doc_set/admin_crawl/preparing.html#1076243) on some parts of release notes: the ones that are always the same.

**Comment by gmarziou** [comment]
Or maybe a more drastic approach: let's not index release notes at all by adding  `<meta name="robots" content="noindex"/>` at the top of each page.

**Comment by jdubois** [comment]
Indeed, my stats show nobody uses the search engine...
I'd rather stick with Google because I know this is "free" without any issue - I'm not totally sure of what Algolia is doing (this seems created by ex-Exalead employees? And looking at Google Trends they are less popular than JHipster...)

**Comment by gmarziou** [comment]
I proposed this simple PR to exclude release notes from indexing so hat search returns only doc.
Using robots.txt is simple and should work for all search engines, if you agree let's do it and see if it has an impact within few days otherwise it'll be easy to rollback.

**Comment by PierreBesson** [comment]
I have a bad news. I just checked and "Google Site Search" will close their service on April 2018 : https://enterprise.google.com/search/products/gss.html
So our choice will be either to move to the new "Google Custom Search" service offered on GCP (https://developers.google.com/custom-search/docs/overview) which is not free AFAIK or to use a competitor.

An alternative is to just put a text box with a redirect to a Google search for "site:jhipster.tech".

**Comment by gmarziou** [comment]
Simple link is better for me as it offers more options to user. I never really liked the display of results in a popup.

**Comment by gmarziou** [comment]
Also I just tried [a link](https://www.google.com/search?site=www.jhipster.tech) and then searched for "upgrade": the first link is the "Updating an application" chapter of the doc.

![image](https://user-images.githubusercontent.com/361007/30617051-add5e8dc-9d94-11e7-9a43-5974751d24f2.png)

When using the search box from our site, the results are very different and less relevant:

![image](https://user-images.githubusercontent.com/361007/30616954-4d1dad9a-9d94-11e7-976a-eaf80900b1ca.png)

**Comment by PierreBesson** [comment]
That's crazy I hadn't realized half the result page is taken by ads (personally using adblock) and the results are so bad... We should definitely do the redirect to Google search thing.

**Comment by jdubois** [comment]
Yes you are correct, and I'm going to have a look at the PR from @gmarziou right away.
Then, please note we just migrated to www.jhipster.tech and it takes time for Google to index it correctly.
Have a look at the current Google Webmaster Tools report, from the last 4 weeks, as you can see it's still getting up to date:
![screenshot 2017-09-20 10 32 29](https://user-images.githubusercontent.com/316835/30634369-2a9efdae-9def-11e7-9020-e14ab113eaa6.png)
