### ISSUE TITLE
Port the git-based upgrade process to the entity generation process 

### ISSUE THREAD

**Issue by Brzhk** [jhipster/generator-jhipster#6382]
##### **Overview of the issue**
The current entity/app generation process "merges" files one by one, which is tedious and quite uncomfortable since it attempts to regenerate a vanilla application and makes us merge files one by one.

##### **Motivation for or Use Case**
We could use the git trick used by the upgrade process instead:
- It replaces the file-by-file step with a whole git merge situation we are accustomed to.
- it would replay the previous corrections and therefore reduce labor overhead.
- it would let the developer use his usual tools

##### **Related issues**
not that i could find?

##### **Suggest a Fix**
cant just yet, but might.

##### **JHipster Version(s)**
4.8.2

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
The current merge step is provided by yeoman as we do not do anything special for it. I know it might be a tedious process but atleast its not buggy. Our upgrade sub generator has been buggy for quite a while and I dont think its a good idea to do that for normal app generations. If you want to regenerate with upgrade generator then its possible as there is a force flag do `jhipster upgrade --help` to see flags.
So no we dont want to add more maintenance burden here as most people are ok with this

**Comment by PierreBesson** [comment]
Does the upgrade generator not currently regenerate entities as well ?

**Comment by deepu105** [comment]
Yes it does that's why I said you could use it just to regenerate as well

**Comment by deepu105** [comment]
@Brzhk running `jhipster upgrade --force` would do exactly what you want

**Comment by Brzhk** [comment]
i did not say it cannot be done. I'm saying the default processes for modifying an entity or adding a new one does not leverage this and the documentation does not suggest doing that either. Actually, the upgrade task documentation **explicitely** warns against using the upgrade branch to commit changes.

I actually tested and suggests changing the default process of the entity tasks to work as follows:
- switch to the jhipster_upgrade branch.
- create/modify entities json file as usual and re-generate the application using the` jhipster --force --with-entities` command.
- Commit the generated code to the _jhipster_upgrade_ branch.
- Merge the _jhipster_upgrade_ branch back to the original branch from where the` jhipster entity` command was launched.

This is not what the entity tasks do by default, neither what the documentation says (it actually discourages any commit on the _jhipster_upgrade_ branch). 
I suggests renaming the _jhipster_upgrade_ branch to _jhipster_vanilla_ branch. It would be used each time you use the _entity_ or _upgrade_ tasks rather than have both default processes work differently.
