### ISSUE TITLE
Build with production profile on Jenkins always hang at 92%

### ISSUE THREAD

**Issue by liaoyunhe** [jhipster/generator-jhipster#6386]
##### **Overview of the issue**

After upgrade to JHipster 4.7.0, webpack production build on jenkins always hang at 92%: 

*****************************************************************************************************
modules 1144/1146 modules 2 active ...\main\webapp\content\scss\vendor.scss 69% building modules 1145/1146 modules 1 active ...\main\webapp\content\scss\vendor.scss                                          70% building modules 1146/1146 modules 0 active                         9657ms building modules
[ERROR]  79% module and chunk tree optimization 0ms module and chunk tree optimization
[ERROR]  80% chunk modules optimization 0ms chunk modules optimization
[ERROR]  81% advanced chunk modules optimization 0ms advanced chunk modules optimization
[ERROR]  82% module reviving32ms module reviving
[ERROR]  83% module order optimization31ms module order optimization
[ERROR]  84% module id optimization47ms module id optimization
[ERROR]  85% chunk reviving 0ms chunk reviving
[ERROR]  86% chunk order optimization 0ms chunk order optimization
[ERROR]  87% chunk id optimization187ms chunk id optimization
[ERROR]  88% hashing234ms hashing
[ERROR]  89% module assets processing15ms module assets processing
[ERROR]  90% chunk assets processing578ms chunk assets processing
[ERROR]  91% additional chunk assets processing795ms additional chunk assets processing
[ERROR]  92% recording 0ms recording
*****************************************************************************************************
##### **Motivation for or Use Case**
Can not complete production build on Jenkins

##### **Reproduce the error**

1. Generate project use JHipster 4.7.0
2. Configure Jenkins to execute maven target 'mvn -Pprod package'

##### **Suggest a Fix**
Set "parallel" to "false" in webpack.prod.js 

        new UglifyJSPlugin({ 
            ....... 
            parallel: false 
            } 
        }), 

##### **JHipster Version(s)**
4.7.0

##### **JHipster configuration**
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.monolith.generated",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "IconnectSampleAppMonolith",
    "packageName": "com.mycompany.monolith.generated",
    "packageFolder": "com/mycompany/monolith/generated",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "131b7d0a45cc951ad28e9f8293f65f433f575185",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "ic",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "iconnectShowCase": true,
    "languages": [
      "en",
      "zh-cn"
    ]
  }
}

##### **Browsers and Operating System**

- Jenkins 2.5 running as service on Windows Server 2012

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
The `parallel: false ` was added by @deepu105 to improve build time performance: while this is important with the `dev` profile, I don't think it's very important with the `prod` profile, we should be used by Jenkins.
-> @deepu105 what do you think about remove it in `prod` build?

**Comment by jdubois** [comment]
Then, this does work on Travis, so maybe this is linked to your environnement @liaoyunhe ? I see you are running Jenkins on top of Windows 2012, and I guess you're probably one of the only ones in the world - are you sure this isn't linked to Windows? Isn't this a Windows issue, and not a Jenkins issue?

**Comment by liaoyunhe** [comment]
Hi @jdubios, I do not have this problem with jhipster 4.6.2 on same jenkins,  production build works fine on my windows 7 as well. 

If not for the upgrade it will take much longer to find out the root cause. If not merged I suggest we add it to FAQ or add  some comments in build config so it will help people encounter the same problem in future

**Comment by jdubois** [comment]
@liaoyunhe it works on your local machine (Windows 7), but not on Jenkins (Windows 2012)? I'm just trying to understand, otherwise I'd be pretty conservative and remove the option.

**Comment by liaoyunhe** [comment]
@jdubois on windows 7 I run 'mvn -Pprod package' from command line, not Jenkins, and it works.

On windows 2012 server Jenkins , there are 20+ runs on two projects, and the jobs always stop at the same line 92%, so it's consistent
