### ISSUE TITLE
skip-server option and missing code in security module

### ISSUE THREAD

**Issue by koptan** [jhipster/generator-jhipster#6389]
Overview of the issue

When I am trying to use `--skip-server` option many issues happen in Security model when trying to build the system.

~~~
ERROR in [at-loader] ./src/main/webapp/app/blocks/interceptor/http.provider.ts:23:17
TS2304: Cannot find name 'AuthExpiredInterceptor'.

ERROR in [at-loader] ./src/main/webapp/app/shared/login/login.service.ts:19:18
TS2339: Property 'authServerProvider' does not exist on type 'LoginService'.

ERROR in [at-loader] ./src/main/webapp/app/shared/login/login.service.ts:38:21
TS2339: Property 'authServerProvider' does not exist on type 'LoginService'.

ERROR in [at-loader] ./src/main/webapp/app/shared/login/login.service.ts:42:14
TS2339: Property 'authServerProvider' does not exist on type 'LoginService'.**
~~~

After some debugging, I found that we are using some Services thas should not be in the code if we are 

using --skip-server option like below in 'login-service.ts':

`if (this.principal.isAuthenticated()) { this.authServerProvider.logout().subscribe(); }`

because we have condition that will remove authServerProvider from the class :

`<%_ if (!skipServer) { _%> private authServerProvider: AuthServerProvider <%_ } _%>`

P.S : not only this file there are other files which have the same issue.

##### **Reproduce the error**
`jhipster --skip-server --auth=jwt --db=sql `

##### **Related issues**
https://github.com/jhipster/generator-jhipster/issues/5429

##### **Suggest a Fix**
none

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
koptan@0.0.0 C:\JS\jh-frontend
+-- generator-jhipster@4.8.2
`-- UNMET PEER DEPENDENCY popper.js@^1.11.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.8.2",
    "baseName": "koptan",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "authenticationType": "jwt",
    "databaseType": "sql",
    "devDatabaseType": "sql",
    "prodDatabaseType": "sql",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipServer": true,
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>
<pre>
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.14.1.windows.1

node: v6.10.2

npm: 3.10.10

bower: 1.8.0

yeoman: 2.0.0

##### **Browsers and Operating System**
Windows 10 , Chrome

**Comment by gmarziou** [comment]
Thanks it seems you have well identified the issue, please consider submitting a pull request.

**Comment by koptan** [comment]
Frankly i am not good with git and jhipster , and this is first time for me working with jhipster i was doing some RND for me new project and I faced this issue.

So pleas if someone expert can fix this issue it would be better.

I am ready for any questions.

**Comment by gmarziou** [comment]
OK, as your use-case is not very common, it may take some time before someone fixes it.
In case you change your mind, we can guide you and you can have a look at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by sendilkumarn** [comment]
Curious question here, how are we gonna make this authentication happen here? `empty methods` and user populate the things?

**Comment by clarenced** [comment]
Hi @gmarziou, here is a proposed PR for this issue #6507

**Comment by thealan759** [comment]
I am running the following: jhipster --skip-server --with-entities --skip-user-management --auth=jwt --db=sql

However, I still get the above errors with latest version of jHipster (Release 4.10.2). When will these make it to the next release and which will that release be?

**Comment by Alan759** [comment]
I still get the above errors with jHipster 4.10.2. when I generate the app using:
jhipster --skip-server --with-entities --skip-user-management --auth=jwt --db=sql

Which release(and when) will this fix go into?

**Comment by pascalgrimaud** [comment]
For the next release, as always, we don't have date.

If you can't wait, you can use directly the master branch. See https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md
