### ISSUE TITLE
JHipster AngularJS & MongoDB deployment issue on Heroku / MongoLab

### ISSUE THREAD

**Issue by ymedaghri** [jhipster/generator-jhipster#6398]
##### **Overview of the issue**

When trying to deploy the application using heroku **authMode=scram-sha1** is not working with MongoDB on MLab.
To make it work I had to change it by **authMechanism=SCRAM-SHA-1** in the template
_application-heroku.yml

##### **Motivation for or Use Case**

That seems to be a bug for me.

##### **Reproduce the error**

- Setup a JHipster AngularJS Monolithic application with MongoDB Database
- Create a Database on MLab
- Create a user for this database

Scenario 1 : prod
- Configure the database in application-prod.yml using all possible syntaxes including this one :
mongodb://myuser:mypass@ds14xxxx.mlab.com:47544/mydatabase?authMode=scram-sha1 

Scenario2 : heroku
- Build your prod war
- deploy with heroku
  - jhipster heroku
  - heroku config:set MONGODB_URI="mongodb://<sameasprod>"
 
##### **Related issues**

No similar issue

##### **Suggest a Fix**

Change template
_application-heroku.yml 
```
<%_ } else if (prodDatabaseType === 'mongodb') { _%>
    data:
        mongodb:
            uri: ${MONGODB_URI}?authMechanism=SCRAM-SHA-1
<%_ } _%>
```

##### **JHipster Version(s)**

```
retrogames@0.0.0 /Users/medaghrialaouiyoussef/Documents/Work/DevelopmentRepositories/jhipster/monoMongo
└── generator-jhipster@4.8.2 
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.ymedaghri.retrogames",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.8.2",
    "baseName": "retrogames",
    "packageName": "com.ymedaghri.retrogames",
    "packageFolder": "com/ymedaghri/retrogames",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "herokuAppName": "retrogames-ymedaghri"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Retro (retro) {
  name String required,
  description String
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

git version 2.12.2

node: v7.9.0

npm: 5.0.3

bower: 1.8.2

gulp:
[13:54:12] CLI version 3.9.1
[13:54:12] Local version 3.9.1

yeoman: 2.0.0

yarn: 0.27.5

Docker version 17.03.1-ce-rc1, build 3476dbf

docker-compose version 1.11.2, build dfed245
```

##### **Browsers and Operating System**

MacOs

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Is this a duplicate to #6393 ? cc @jkutner

**Comment by ymedaghri** [comment]
No This one is specific to MongoDB configuration not heroku.
(Both for prod or heroku)

Regards,

Youssef MEDAGHRI-ALAOUI
Full Stack Sr Java Developer
Mobile: +33 (0)7 82 39 78 23

**Comment by jdubois** [comment]
I have a doubt: are you using the MongoLab instance provided by Heroku? I mean, do you do something like "heroku addons:create mongolab:sandbox" and use https://elements.heroku.com/addons/mongolab ?

**Comment by jdubois** [comment]
Yes but then you are not using the Heroku features - the Heroku sub-generator can only work if you use Heroku... If you're doing something else, this is your own configuration, and thus this isn't a bug but your own personal issue.

**Comment by ymedaghri** [comment]
Indeed, in that case you are most probably right.
I'm going to spend some time playing with various configs for the heroku sub-generator.
Thank you,
Best Regards,

**Comment by jkutner** [comment]
@ymedaghri are you saying the difference is in capitalization (that is, `scram-sha1` versus `SCRAM-SHA-1`)?

Can you clarify: does the lower-case version work on Heroku? Or does the uppercase version work on Heroku?

**Comment by ymedaghri** [comment]
No The difference is in the command : 
authMode vs authMechanism

authMode did not work for me I had to change it by authMechanism

**Comment by jkutner** [comment]
@ymedaghri i think "Scenario2" is the better solution if that works. If you set the `MONGODB_URI` config var, then the `yo jhipster:heroku` command should skip the addon creation. Is that right?

**Comment by ymedaghri** [comment]
No, the Heroku server returns the following exception when authMode is use instead of authMechanism:
```
2017-09-22T13:38:31.804793+00:00 app[web.1]: 2017-09-22 13:38:31.804  WARN 4 --- [           main] org.mongodb.driver.uri                   : Unsupported option 'authmode' in the connection string 'mongodb://jhipster:jhipster_pass@dsxxxxx.mlab.com:47544/mydb?authMode=scram-sha1'.
```
