### ISSUE TITLE
Mapper implementation cannot be found in Idea IDE with gradle

### ISSUE THREAD

**Issue by EdisonXu** [jhipster/generator-jhipster#6403]
##### **Overview of the issue**
I followed the instruction in [creating-an-app](http://www.jhipster.tech/creating-an-app/) and [creating-an-entity](http://www.jhipster.tech/creating-an-entity/) to create a new monolithic application (using Gradle), and I tried to add some new entities, but the app would not start due to the following error messages:

```` 
Parameter 1 of constructor in com.edi.web.rest.AuthorResource required a bean of type 'com.edi.service.mapper.AuthorMapper' that could not be found.

Action:

Consider defining a bean of type 'com.edi.service.mapper.AuthorMapper' in your configuration.
````

I saw the codes generated under %{ROOT}%/build/generated/source/apt/main folder, but those classes were not built at all, thus no generated classes under %{ROOT}%/out/production/classes/. 
I tried to mark the generated/source/apt/main folder as a "Generated Sources ROOT",  but there was only a "generated" folder coming out under the /out/production/classes/ folder, so also failed.

It's OK to copy those gen codes to source folder, but obviously this will lose the meaning of bringing in the MapStruct. Meanwhile, using command "gradle bootRun" will work, but that's not convenient and friendly in IDE, right?

##### **Motivation for or Use Case**
The application cannot start.

##### **Reproduce the error**
1. create a sample application with the given JHipster config
2. import any entity jh file

##### **Related issues**
[6170](https://github.com/jhipster/generator-jhipster/issues/6170)

Tried the solution given there, but not working.

##### **Suggest a Fix**
None.

##### **JHipster Version(s)**
4.8.2

##### **JHipster configuration**
`{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.edi"
    },
    "jhipsterVersion": "4.8.2",
    "baseName": "jhipster_intro",
    "packageName": "com.edi",
    "packageFolder": "com/edi",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "447bcfc9dbbfc5544428f896b01677e21edd8454",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-entity-audit",
        "version": "2.6.1"
      }
    ],
    "enableTranslation": false
  }
}`

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
`{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "book",
            "otherEntityName": "book",
            "otherEntityRelationshipName": "author"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "sex",
            "fieldType": "Sex",
            "fieldValues": "MALE,FEMALE"
        }
    ],
    "changelogDate": "20170925035647",
    "entityTableName": "author",
    "dto": "mapstruct",
    "pagination": "infinite-scroll",
    "service": "no",
    "angularJSSuffix": "mySuffix"
}`
`{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "author",
            "otherEntityName": "author",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "publishDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "price",
            "fieldType": "Double"
        }
    ],
    "changelogDate": "20170925035648",
    "entityTableName": "book",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "no",
    "angularJSSuffix": "mySuffix"
}`

##### **Browsers and Operating System**
Win10 + Intellj IDEA 2017.2.4

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Did you read the little notes at the end of http://www.jhipster.tech/configuring-ide-idea/ ?
This is because IDEA doesn't run the postprocessor automatically (and that's one of the reasons why MapStruct is still in BETA)

**Comment by EdisonXu** [comment]
I'm new to JHipster, I just followed the document step by step. I saw the little notes there, but it's all "Maven" related. I suggest add more warning or detail explanation in that chapter.
PS:
IDEA actually supports the annotation processors refers to the [doc of 2017.2](https://www.jetbrains.com/help/idea/annotation-processors-support.html) . 
Maybe you should try and put it in the "Configure IDE" section?

**Comment by jdubois** [comment]
Yes IDEA supports it, but it's disabled by default... And that's not specific to Maven or Gradle, it's disabled with both :-(
I know it sucks -> what do you mean by the "configure IDE" section, that's where it already is (OK, not easy to find, I agree)

**Comment by EdisonXu** [comment]
@jdubois 
In [configuring-ide](http://www.jhipster.tech/configuring-ide/), there're a "Configuring Eclipse with Gradle", in which it's clearly described "Add apt generated source folder to build path". 
Actually, in IDEA, it's also working. But clearly, if I'm using IDEA, I would pass the Eclipse configure parts, then I will face this problem in a good chance. 
It will save lots of time for newbie :(
