### ISSUE TITLE
Jackson serialization issue of Problem

### ISSUE THREAD

**Issue by henri-tremblay** [jhipster/generator-jhipster#6409]
##### **Overview of the issue**

The project below is a plain generation with only one commit on top. In this commit, I add an `ExceptionTranslator` because I want to test the final error. I also use the `ObjectMapper` created by Spring.

Finally, I retrieve the result and deserialize it to do some asserts. However, I get an error at deserialization. This error comes from a wrong serialization. Instead of using the `StatusTypeSerializer`, a plain `EnumSerializer` have been used. I have no idea why.

```
com.fasterxml.jackson.databind.JsonMappingException: Current token (VALUE_STRING) not numeric, can not use numeric value accessors
 at [Source: [B@2aa85cc4; line: 1, column: 10181]
 at [Source: [B@2aa85cc4; line: 1, column: 10180] (through reference chain: org.zalando.problem.DefaultProblem["status"])
```

##### **Motivation for or Use Case**

The wrong serializer is used. It doesn't happen on all my tests. However, every constraint validation error fails. The problem is not only my test case, it also mean that the wrong format was returned from my API.

##### **Reproduce the error**

A full project is available [here](https://github.com/henri-tremblay/jacksonissue). Just run `AccountResourceIntTest.testRegisterInvalidLogin`

##### **Suggest a Fix**

I have no idea how to fix it. I don't know how the priorities are established in Jackson to pick a serializer. It might a Spring, Jackson or Zalando bug. I've started to doubt it is a direct JHipster bug.

##### **JHipster Version(s)**

4.8.2

##### **JHipster configuration**

See git repo

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

See git repo

##### **Browsers and Operating System**

Not important

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by cbornet** [comment]
This doesn't look like a JHipster issue. Can you post your question on StackOverFlow ?

**Comment by henri-tremblay** [comment]
Done. https://stackoverflow.com/questions/46428757/zalando-rfc7807-wrong-serializer-picked-for-status-with-jackson (and vote -1 for an unknown reason that might be related to the code not in the question... but I can't)

**Comment by Falydoor** [comment]
Check my answer, the fix is very simple :relaxed:

**Comment by henri-tremblay** [comment]
@Falydoor You saved me! I think it is really something that needs to be improved in the current integration tests. MockMvc are configured in different places and not entirely like actual production resources. So, here, `restUserMockMvc` is not using the converters but `restMvc` is. I'll try to push ideas about that.
