### ISSUE TITLE
If an authorized user opens a concrete entity(in entities) to the navbar and refreshes the page, the user will become unauthorized.

### ISSUE THREAD

**Issue by kukasha** [jhipster/generator-jhipster#6413]
##### **Overview of the issue**

The user receives the status not authorized after the page is refresh on a particular entity.
I found a similar question (https://github.com/jhipster/generator-jhipster/issues/6190) and saw the commit "decisive" problem. The commit was 20 days ago and I have the latest version of the jipper. I can safely say that the last fix did not solve the problem.

##### **Reproduce the error**
Authorize user, open concrete entyti in navbar, refresh page.

##### **JHipster Version(s)**

4.8.2

##### **JHipster configuration, a .yo-rc.json file generated in the root folder**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "ru.javablog.blog",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.8.2",
    "baseName": "javablog",
    "packageName": "ru.javablog.blog",
    "packageFolder": "ru/javablog/blog",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "eefdb2a631a1a1c21b563d59fa1ccb8908d4769e",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ru"
    ]
  }
}

##### **Browsers and Operating System**

OS: Archlinux

openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.1

node: v8.5.0

npm: 5.3.0

yeoman: 1.8.5

yarn: 1.0.2

Docker version 17.07.0-ce, build 87847530f7

docker-compose version 1.16.1, build unknown

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pelmegov** [comment]
I have similar problem, i added new route in generated routes 
```
            pageTitle: 'javablogApp.post.home.title'
        },
        canActivate: [UserRouteAccessService]
    }, {
        path: 'front/post/:id',
        component: FrontPostDetailComponent,
        data: {
            authorities: [],
            pageTitle: 'javablogApp.post.home.title'
        },
        canActivate: [UserRouteAccessService]
    }
```
and after refresh entity i have unauthorization navbar. 
If click another page, i will again authorized.
I use last jhipster version.

**Comment by jdubois** [comment]
@pelmegov are you sure it's the same issue? Are you also on v4.8.2? I'm sorry but this is confusing
@kukasha what do you mean by a "concrete entity"?
And when you mean he is not authenticated, do you mean that in the UI it looks he isn't authenticated, but if you go to another entity it works? Or that you are logged out, and need to log in again?

**Comment by pelmegov** [comment]
@jdubois yes, my jhipster version v4.8.2 and my problem similar.
I authenticate. I go to the detail view entity page and refresh page and i again unauthorized.
But if i click another page, i again authorized automatically.

**Comment by kukasha** [comment]
@jdubois , my situation was described to you by @pelmegov . It's similar problem.

**Comment by gzsombor** [comment]
Yes, it's the same issue, I could reproduce it. The referred problem is not fixed, as I see.

I think, I have a solution for it.
