### ISSUE TITLE
[BUG] [OpenShift generator] Conflict with name of the secret reference

### ISSUE THREAD

**Issue by hufon** [jhipster/generator-jhipster#6418]
##### **Overview of the issue**

When using the openshift generator with :

- PostGreSQL BDD
- Multiple microservices (1 gateway and >1 microservices)

user and password (generated) are stored in a "Secret" object. This object is shared among all applications, and now the name of the "secret" is the same with all microservice (https://github.com/jhipster/generator-jhipster/blob/master/generators/openshift/templates/db/_postgresql.yml#L51) ds-secret-ref

so that microservices use randomly bad credentials on their BDD

##### **Motivation for or Use Case**

We need to fix manually this issue by prefixing secret name in all -posgresql.yml files

##### **Reproduce the error**

Create an application with 2 microservices with a PostGreSQL backend
run openshift generator
deploy oc-apply.sh on your openshit instance (reproducible with minishift)

- 1 microservices doesn't start because it authenticate with his neighbor credentials

##### **Suggest a Fix**

Add a prefix like  <%= app.baseName.toLowerCase() %> bedore ds-secret-ref in 
https://github.com/jhipster/generator-jhipster/blob/master/generators/openshift/templates/db/_postgresql.yml#L51

##### **JHipster Version(s)**

4.8.2 / master

##### **JHipster configuration**
No need

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
No need

##### **Browsers and Operating System**
ALL

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
cc @srinivasa-vasu

**Comment by jdubois** [comment]
Closing as PR is merged
