### ISSUE TITLE
JHipster working somewhat like Teamviewer.

### ISSUE THREAD

**Issue by hassnainali** [jhipster/generator-jhipster#6428]
##### **Overview of the issue**

I'm using jHipster with OAuth2 + Client in Angular 4. While doing some work I'm facing a critical issue. i.e I'm working in **development mode** and I've generated my client and server code separately. One of my machines is the server, on which client and server are running.  What happens is when I access the URL of the client from the different systems it works somewhat like a TeamViewer session.
 I've tested this issue with 3 systems.

##### **Motivation for or Use Case**

One of my machines is the server, on which client and server are running.  What happens is when I access the URL of the client from the different systems it works somewhat like a TeamViewer session.
e.g.  On one system if I enter username and password sign-in page, it enters data on another machine as well, in which the same URI is open.

##### **Reproduce the error**
1. Run client and server on the same system
2. Open the client portal from different system 
3. Click on the sign-in pop up in the navbar, enter data in the form and it will replicate the data in all those systems which are accessing the same sign-in URL at the time.
4. All UI screens are synchronized. Try entring or navigating.

##### **Related issues**
None

##### **JHipster Version(s)**
generator-jhipster@4.7.0

##### **JHipster configuration**

Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
app@0.0.0 D:\Hassnain\projects\blockchain\jhipster-official\client
`-- generator-jhipster@4.7.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "app",
    "clientFramework": "angularX",
    "useSass": true,
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "clientPackageManager": "yarn"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.9.0.windows.1

node: v6.11.2

npm: 5.3.0

bower: 1.8.0

gulp:
[20:02:55] CLI version 1.4.0

yeoman: 2.0.0

yarn: 0.27.5

Docker version 17.07.0-ce, build 8784753

docker-compose version 1.15.0, build e12f3b94

Execution complete

##### **Browsers and Operating System**

Windows 7 , Google Chrome
- [* ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
That's BrowserSync :-)

**Comment by hassnainali** [comment]
Thank you for replying. @jdubois can you please tell me what should I do to run my client in the production environment. or how can I disable BrowserSync in jHipster.

**Comment by deepu105** [comment]
Please read the documentation website on how to run in production it is clearly explained there http://www.jhipster.tech/production/

**Comment by deepu105** [comment]
This is the first time a feature is reported as bug :smile:
