### ISSUE TITLE
Improve OAuth 2.0 / OIDC Integration

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#6432]
This issue is to track the improvements needed to make the OAuth 2.0 / OIDC integration into a wonderful developer experience. The [main PR](https://github.com/jhipster/generator-jhipster/pull/6361) has been merged, these are the items remaining:

- [x] Exclude AngularJS as an option when `oauth2` is authentication type
- [x] Fix redirect to http://localhost:9000 when using `yarn start` - https://github.com/jhipster/generator-jhipster/pull/6436
- [x] Integrate it into the `docker-compose` sub-generator, using [the Traefik PR as a reference](https://github.com/jhipster/generator-jhipster/pull/6412/files). Start of PR [here](https://github.com/jhipster/generator-jhipster/pull/6442)
- [x] Add a specific documentation page, and add the new properties to http://www.jhipster.tech/common-application-properties/ (if needed, not sure if there are some)

@jdubois You mentioned [here](https://github.com/jhipster/generator-jhipster/pull/6361#issuecomment-333103601) that documentation should be added in <http://www.jhipster.tech/microservices-architecture/>. However, I only verified this works in a monolith. I don't believe it will work in a microservices architecture. @danielpetisme [created a PR to add microservices support](https://github.com/jhipster/generator-jhipster/pull/6435).

**Comment by jdubois** [comment]
Oh I thought it would work with microservices :-(
But you made a good decision: let's start simple, and then improve, we'll have this later!

**Comment by jdubois** [comment]
@mraible I edited your "todo list" to add a new item on documentation

**Comment by mraible** [comment]
PR https://github.com/jhipster/generator-jhipster/pull/6436 fixes the redirect to localhost:9000 issue.

**Comment by mraible** [comment]
@deepu105 Do you have any advice on how to default to Angular 4 and disable prompting when OAuth 2.0 is selected?

**Comment by mraible** [comment]
@jdubois For the `docker-compose` sub-generator, should I prompt to see if the user wants Keycloak, or just assume they do if `authenticationType === "oauth2"`? The reason I ask is because they might not need Keycloak if they've configured a different IdP for their app.

**Comment by deepu105** [comment]
@mraible i'll do that on master tomorrow

**Comment by jdubois** [comment]
@mraible 
- for the `docker-compose` sub-generator: if they have selected `authenticationType === "oauth2"` yes you should be automatically the Docker Compose configuration for Keycloak (doesn't do much harm anyway). But yes don't hesitate to do some advertisement for Okta - at least on the documentation (I don't think anybody would use that feature without reading the documentation)
- then there is something I'm not sure I fully understand: do you store anything in the Servlet `HttpSession`? I know this is supposed to be stateful, but I don't find where it's done, is that automatic with Spring Security? Anyway, I'm wondering what happens when you scale your application: if you don't have HTTP session clustering, does it work? Otherwise, does it work out-of-the-box with our Hazelcast and Infinispan session clustering?

**Comment by deepu105** [comment]
@mraible i didn't disable prompting as I figured we would soon add React there anyway so I just removed Angular 1 from options when oauth selected, IMO its better as user wont be confused why the prompt didn't show up and in Oauth2 docs we need to say that Angular 1.x is not supported

**Comment by mraible** [comment]
> then there is something I'm not sure I fully understand: do you store anything in the Servlet HttpSession? I know this is supposed to be stateful, but I don't find where it's done, is that automatic with Spring Security? Anyway, I'm wondering what happens when you scale your application: if you don't have HTTP session clustering, does it work? Otherwise, does it work out-of-the-box with our Hazelcast and Infinispan session clustering?

@jdubois The only thing I store in the session is the login-origin-uri for redirecting back to the correct location for the client in dev mode. All the rest is handled automatically by Spring Security. I'm guessing it'll work with Hazelcast and Infinispan for session clustering, but haven't tested.

**Comment by jdubois** [comment]
@mraible great, so this should be tested, but indeed that should be OK

**Comment by jdubois** [comment]
Closing this as it's all done
