### ISSUE TITLE
can't import jdl from only client side

### ISSUE THREAD

**Issue by zccbbg** [jhipster/generator-jhipster#6439]
##### **Overview of the issue**

I use the below command to create angular 4 jhipster client side.
`jhipster client --auth=jwt`

I want to import jdl file to generate entities but get failed.

but it works on my app side

##### **Motivation for or Use Case**

I import jdl from the below command 
`jhipster import-jdl ./model.jh --json-only`

##### **Reproduce the error**

but got fail for the following reason
`The jdl is being parsed.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! 
Error while parsing entities from JDL

    at Environment.error (/Users/zcc/TestRepo/ng-app-c/node_modules/yeoman-environment/lib/environment.js:140:40)
    at constructor.error (/Users/zcc/TestRepo/ng-app-c/node_modules/generator-jhipster/generators/generator-base.js:1682:18)
    at constructor.parseJDL (/Users/zcc/TestRepo/ng-app-c/node_modules/generator-jhipster/generators/import-jdl/index.js:108:22)
    at Object.<anonymous> (/Users/zcc/TestRepo/ng-app-c/node_modules/yeoman-generator/lib/index.js:417:23)
    at /Users/zcc/TestRepo/ng-app-c/node_modules/run-async/index.js:25:25
    at Promise (<anonymous>)
    at /Users/zcc/TestRepo/ng-app-c/node_modules/run-async/index.js:24:19
    at /Users/zcc/TestRepo/ng-app-c/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
`

##### **JHipster Version(s)**

4.7.0
##### **JHipster configuration**

`{
  "generator-jhipster": {
    "jhipsterVersion": "4.7.0",
    "baseName": "web",
    "clientFramework": "angularX",
    "useSass": false,
    "enableTranslation": false,
    "clientPackageManager": "yarn"
  }
}`
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

`##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>
`
##### **Browsers and Operating System**
mac os

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry but can you edit the ticket to add your JDL configuration, so we can try to reproduce? Your `.yo-rc.json` looks strange, also, are you sure it's correct?

**Comment by deepu105** [comment]
Please run `jhipster info` on your project and paste the output here

**Comment by jdubois** [comment]
Closing as we didn't get more info
