### ISSUE TITLE
[Feature] Create a "git init" sub-generator

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6453]
This is the same idea as #6440

I would like to have a small sub-generator for Git:

- `jhipster git-init` would initialize a Git repository, add all files to it, and commit with message "Initial application generation by JHipster" (like https://start.jhipster.tech does today)
- This would run by default after each generation, but could be disabled with a flag

I'm also wondering if we could have the same after an entity is generated, but I'm less sure it's a good idea.

**Comment by deepu105** [comment]
@jdubois should this be a sub-generator? do you foresee use beyond the initial generation? if not we could do it after initial generation using our builtIn gitExec command in 3 lines

**Comment by jdubois** [comment]
Indeed, it would be easier to maintain if that was inside the main generator

**Comment by deepu105** [comment]
so you ok to do it directly in the app generator without a sub gen?

**Comment by jdubois** [comment]
yes you are correct, it would be better inside the main generator, so no sub gen

**Comment by PierreBesson** [comment]
@sendilkumarn that was fast !
But when regenerating the application, should we still have the "initial generation" message ?
Also it would be great to have the jhipster version in the commit message and I think we should add a log like this : "Automatically committing all generated files to git, to prevent this behavior use `jhipster --skip-git`".

**Comment by jdubois** [comment]
Yes @PierreBesson that's a nice message - but anyway if this doesn't suit the user, he just needs to do `rm -rf .git`, that's not very hard.
@sendilkumarn @deepu105 we also need to check if Git is installed, and I have some comments here:
- If Git isn't installed, let's just do a nice log message saying "The generated application could not be added to Git, as Git is not installed on your system"
- But we still require to install Git at http://www.jhipster.tech/installation/ -> I think this comes from the old times when we were using Bower, is it still required today? This would make the installation even easier

**Comment by deepu105** [comment]
Git is still required due to our upgrade sub gen

**Comment by sendilkumarn** [comment]
@jdubois git is still required by sub gen. I have added this `nice log message` 😉 

> But when regenerating the application, should we still have the "initial generation" message ?

@PierreBesson that is indeed an awesome idea.

**Comment by jdubois** [comment]
Thanks @sendilkumarn - and yes we can still require Git, I'm not sure many people use the upgrade sub-generator, but as of today everybody uses Git, so it's not much an issue.
When we re-generate the application I wouldn't do any Git commit -> it's different from generating a new app, where initializing the repo is important (and that's 3 commands in total)

**Comment by sendilkumarn** [comment]
Added a condition to check whether `git init` has already happened

**Comment by jdubois** [comment]
I'm going to change this a little bit: this creates quite a lot of log messages at the end of a project generation, and this is confusing (it hides the more important messages above). So I'm going to remove most log messages - I'll link the commit here, please add comments if you disagree.

**Comment by jdubois** [comment]
Sorry I did a wrong commit above!

**Comment by jdubois** [comment]
Argh I messed up my commit!!!!!
So this was fixed by https://github.com/jhipster/generator-jhipster/commit/1e4730c7a385e207222c7229646a2b0f994f4e2a and I'm closing this manually... Too much work :-(

**Comment by jdubois** [comment]
So I removed the logs, but I'm not sure it's good for error handling.... Anyway, as long as Git is installed, all commands should work (if you can do a `git init`, I don't understand how a `git add .`would fail)
