### ISSUE TITLE
Activiti Integration

### ISSUE THREAD

**Issue by ryandawsonuk** [jhipster/generator-jhipster#6454]
Hi, I'm from the Activiti open source BPM project. We're centering v7 of Activiti around Spring Cloud and are interested in providing the ability to generate Activiti apps using JHipster. We've got several cloud-based components we'd want to be able to build through JHipster and are wondering if we could have a chat to see if you agree that it's a good fit and if so to make sure we approach it in the best way possible.

You can easily reach us on our gitter channel https://gitter.im/Activiti/Activiti7 and we'd be very happy to explain further. If you'd like something to refer to about what Activiti7 apps look like, see https://github.com/Activiti/activiti-cloud-examples or https://activiti.gitbooks.io/activiti-7-developers-guide/content/

**Comment by jdubois** [comment]
Hi, welcome to JHipster :-)

- I haven't used Activiti personally, but I know we have some projects using it in my company, and having Activity/JHispter integration can only be good for both projects
- Doing a chat with the team is always very complicated, as we all have day jobs - if some people are interested, please comment here, but @ryandawsonuk we usually work in async mode
- My main issue with the integration is that Activiti looks huge, and we're usually quite bad with huge integrations (same reason as above, we all have day jobs) -> if you want to go fast, did you have a look at http://www.jhipster.tech/modules/marketplace ? In fact, I had originally the "marketplace" idea for someone who wanted to integrate Alfresco with JHipster, and I see you work at Alfresco :-)
- I also had a quick look at your documentation: maybe you would be interested in http://www.jhipster.tech/jhipster-registry/ ? Did go through are microservices documentation?

**Comment by PierreBesson** [comment]
Very good idea, there is a great potential for JHipster microservice + BPM. In our current project, we have integrated JHipster microservices with a BPM system.. Among other things we have extended the JHipster Registry to be able to deploy processes to our BPM microservice (using JBPM).

The first step would be to create a JHipster module to demonstrate the concept. It would be really nice to have a vendor supported module.

**Comment by agoncal** [comment]
Hi guys. We are actually planning to use Activiti in my coming project. So, for me, being able to integrate Activiti with JHipster would be awesome !

@ryandawsonuk I am not the best person to have a chat with (I've never used Activiti myself) but I am available all day Thursday if you want a first contact. Let me know (I can also add the second developer I'll be working with) and we can manage a quick chat.

**Comment by Salaboy** [comment]
@PierreBesson @agoncal Thanks for the feedback guys. We are working with @ryandawsonuk  to make sure that Activiti works well in distributed environments so we are very keen to interact with the JHipster community to make sure that users can integrate their apps easily. You can take a look at this blog post explaining our Cloud strategy: https://salaboy.com/2017/09/11/activiti-cloud-meets-kubernetes-and-they-like-each-other/ 

@agoncal it will be great to have a quick chat on Thursday. By the way we are based in London and we are actively looking for these kind of collaborations that benefit the wider community, if anyone else is interested to join these efforts please get in touch. 

We are also in Gitter everyday, so @agoncal please feel free to ping us here: https://gitter.im/Activiti/Activiti7 to coordinate.

**Comment by ryandawsonuk** [comment]
Yeah we in the Activiti team would expect to lead the integration so the size of the project would be our problem to solve. We certainly are interested in the JHipster microservices architecture as we're also using spring cloud. We are indeed looking at the documentation and thinking about what generators for our modules would be like.

I'm currently not sure that this would be as straightforward as having a module that could be added to any JHipster application. We could add an Activiti spring boot starter to a spring boot application and that would embed the activiti engine in that application (and that is something we could look at) but we don't want to just embed the engine in a single service for a cloud environment (and cloud is our main focus right now). 

For cloud we want to run Activiti across a set of microservices. The central executor services are called runtime bundles. An implementation of one of these can be found here - https://github.com/Activiti/activiti-cloud-runtime-bundle. It is not quite the case that adding the activiti-cloud-starter-runtime-bundle makes that application a fully-functioning runtime bundle that could work anywhere. The main reasons for this are:
- It will assume keycloak to be the IDM provider - it does need to know what the IDM is as it has to make calls to find a user's groups (I'm thinking selection of IDM would need to be extracted into additional starters)
- We're using spring boot 2.0
- The spring-boot-maven-plugin configuration matters as it enables the app to scan a directory for files
- It needs to be configured (in properties or environment variables) to point to other parts of an Activiti microservices setup. It's not intended to run on its own.

Could anyone point me at how JHipster generates a microservice application (as opposed to a normal spring boot application)? That would help me to understand the situation better.

**Comment by PierreBesson** [comment]
@ryandawsonuk A JHipster microservice is normal spring boot application with eureka, spring cloud config and a database pre-configured. We also have specific "sub-generators" that can generate docker-compose and kubernetes configuration files for a set of jhipster microservices/gateways ([jhipster.tech/docker-compose/#docker-compose-subgen](http://www.jhipster.tech/docker-compose/#docker-compose-subgen)). You might be interested by this part as it seems that your dev setup also relies on docker/k8s.

The current module system should let you go quite far already but we are working on extending its capabilities, see issue https://github.com/jhipster/generator-jhipster/issues/6372.

**Comment by agoncal** [comment]
@ryandawsonuk My usecase just needs Activity embedded. Out of our 5 microservices, only one uses Activiti (so we don't have the use case where we have Activiti across a set of microservices). 

Maybe your JHipster module could be configurable: embedded or distributed Activiti.

**Comment by Salaboy** [comment]
@agoncal we can discuss this on Thursday, but we are already covering your use case as well.

**Comment by ryandawsonuk** [comment]
Thought I should share that work is underway on a generator at https://github.com/Activiti/generator-jhipster-activiti

**Comment by deepu105** [comment]
closing as this will be a module. Feel free to continue the discussion here though
