### ISSUE TITLE
Error creating bean with name 'boletoResource'

### ISSUE THREAD

**Issue by lucasbarrossantos** [jhipster/generator-jhipster#6461]
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "br.com.metaselecoes",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "4.8.2",
    "baseName": "metaselecoes",
    "packageName": "br.com.metaselecoes",
    "packageFolder": "br/com/metaselecoes",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br",
      "en",
      "es"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Candidato (candidato) {
  nome String required,
  nomeSocial String,
  cpf String required,
  email String,
  senha String required,
  confirmarSenha String required,
  identidade String required,
  dataDeNascimento LocalDate,
  nomeDoPai String required,
  nomeDaMae String required,
  corOuRaca String required,
  sexo Sexo required,
  escolaridade Escolaridade required,
  notificarMe Boolean,
  cep String required,
  logradouro String required,
  numero String,
  complemento String,
  bairro String required,
  estado String required,
  cidade String required,
  latitude String,
  longitude String,
  telefoneResidencial String,
  telefoneComercial String,
  celular String
}
entity Inscricao (inscricao) {
  necessidadeEspecial Boolean required,
  termosECondicoes Boolean required
}
entity Cargo (cargo) {
  descricao String required,
  tipo TipoDoCargo,
  quantidadeDeVagas Integer,
  quantidadeDeVagasParaDeficientes Integer
}
entity Prova (prova) {
  nome String required
}
entity ItemDaProva (item_da_prova) {
  descricao String,
  numeroDaQuestao String,
  resposta String
}
entity ItemDoGabarito (item_do_gabarito) {
  numeroDaQuestao String required,
  resposta String required
}
entity GabaritoDaProva (gabarito_da_prova)
entity Selecao (selecao) {
  descricao String required,
  dataDeInicio LocalDate required,
  dataDeEncerramento LocalDate required
}
entity Documento (documento) {
  descricao String required,
  anexo byte[]
}
entity Estabelecimento (estabelecimento) {
  descricao String required,
  cep String required,
  logradouro String required,
  numero String,
  complemento String,
  bairro String required,
  estado String required,
  cidade String required,
  latitude String,
  longitude String,
  telefoneResidencial String,
  telefoneComercial String,
  celular String,
  email String
}
entity Sala (sala) {
  descricao String required,
  quantidadeMaxima Integer required
}
entity Fiscal (fiscal) {
  nome String required,
  nomeSocial String,
  sexo Sexo required,
  cpf String required,
  rg String,
  cep String required,
  logradouro String required,
  numero String,
  complemento String,
  bairro String required,
  estado String required,
  cidade String required,
  latitude String,
  longitude String,
  telefoneResidencial String,
  telefoneComercial String,
  celular String,
  email String
}
entity Boleto (boleto) {
  cnumban String,
  empcnpj String,
  empema String,
  empendnum String,
  empendbai String,
  empendcep String,
  empendcid String,
  empendcom String,
  empendlog String,
  empendpai String,
  empenduf String,
  empnom String,
  emptel String,
  titcarcod String,
  titconvcod Integer,
  titdescdt LocalDate,
  titdescval BigDecimal,
  titdtemi LocalDate,
  titdtven LocalDate,
  titespcod Integer,
  titjurval BigDecimal,
  titpraprot Integer,
  titmens1 String,
  titmens2 String,
  titmens3 String,
  titnumdoc String,
  titnosnum String,
  titval BigDecimal,
  lay String
}
entity Comunicado (comunicado) {
  descricao String required,
  titulo String required,
  dataDaPublicacao LocalDate required
}

enum Sexo {
  MASCULINO,
  FEMININO
}

enum Escolaridade {
  FUNDAMENTAL_INCOMPLETO,
  FUNDAMENTAL_COMPLETO,
  MEDIO_INCOMPLETO,
  MEDIO_COMPLETO,
  SUPERIOR_INCOMPLETO,
  SUPERIOR_COMPLETO,
  POS_GRADUACAO_INCOMPLETO,
  POS_GRADUACAO_COMPLETO
}

enum TipoDoCargo {
  MEDIO,
  TECNICO,
  SUPERIOR
}

relationship OneToOne {
  Inscricao{gabarito} to GabaritoDaProva,
  Inscricao{boleto} to Boleto,
  Inscricao{prova} to Prova
}
relationship OneToMany {
  Inscricao{cargos} to Cargo{inscricao},
  Selecao{cargos} to Cargo{selecao},
  Cargo{provas} to Prova{cargo},
  Prova{itensDaProva} to ItemDaProva{prova},
  GabaritoDaProva{itensDoGabarito} to ItemDoGabarito{gabaritoDaProva},
  Selecao{documentos} to Documento{selecao},
  Estabelecimento{salas} to Sala{estabelecimento},
  Sala{fiscais} to Fiscal{sala}
}
relationship ManyToOne {
  Candidato{inscricao} to Inscricao
}

dto Candidato with mapstruct
paginate Candidato with pagination
dto Inscricao with mapstruct
paginate Inscricao with pagination
dto Cargo with mapstruct
paginate Cargo with pagination
dto Prova with mapstruct
paginate Prova with pagination
dto ItemDaProva with mapstruct
paginate ItemDaProva with pagination
dto ItemDoGabarito with mapstruct
paginate ItemDoGabarito with pagination
dto GabaritoDaProva with mapstruct
paginate GabaritoDaProva with pagination
dto Selecao with mapstruct
paginate Selecao with pagination
dto Documento with mapstruct
paginate Documento with pagination
dto Estabelecimento with mapstruct
paginate Estabelecimento with pagination
dto Sala with mapstruct
paginate Sala with pagination
dto Fiscal with mapstruct
paginate Fiscal with pagination
dto Boleto with mapstruct
paginate Boleto with pagination
dto Comunicado with mapstruct
paginate Comunicado with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) Client VM (build 25.131-b11, mixed mode)

git version 2.13.3.windows.1

node: v8.4.0

npm: 5.3.0

bower: 1.8.0

gulp:
[15:05:16] CLI version 1.3.0

yeoman: 2.0.0

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in br.com.metaselecoes.web.rest.BoletoResource required a bean of type 'br.com.metaselecoes.service.mapper.BoletoMapper' that could not be found.

Action:

Consider defining a bean of type 'br.com.metaselecoes.service.mapper.BoletoMapper' in your configuration.

**Comment by jdubois** [comment]
That's because you use MapStruct:

- Run your application with Maven and it will work
- Read the documentation on IDE configuration, you need to use the "ide" profile -> I know it's not well placed in the documentation, but that's because MapStruct is a BETA feature, so we can't push this on the top (normal users won't use this)
