### ISSUE TITLE
Production build error when using internal npm repository behind corporate proxy

### ISSUE THREAD

**Issue by riverd3** [jhipster/generator-jhipster#6464]
##### **Overview of the issue**
When working behind corporate proxy,  frontend-maven-plugin use maven proxy to download nodejs while executing "install-node-and-npm", this work fine.

To allow nodejs download from internal nexus repository, I configured " <nonProxyHosts>192.168.*|localhost|*.mycompany.com.</nonProxyHosts>", However "npm install" does not respect maven nonProxyHosts configuration and build will fail.

This is related to https://github.com/eirslett/frontend-maven-plugin/issues/523

##### **Motivation for or Use Case**
Production build failed behind proxy during "npm install" when using internal npm nexus repository.

##### **Reproduce the error**
- Configure maven proxy in setting.xml with noProxyHost
    <proxy>
      <id>http</id>
      <protocol>http</protocol>
      <active>true</active>
      <host>proxy.com.mycompany</host>
      <port>8080</port>
      <nonProxyHosts>192.168.*|localhost|*.com.mycompany|10.176.*</nonProxyHosts>
    </proxy>

- Configure npm proxy in .npmrc as below:
proxy=http://proxy.com.mycompany:8080
https-proxy=http://proxy.com.mycompany:8080
no-proxy=localhost,127.0.0.1,192.168.*,*.com.mycompany
registry=http://mycompany.com/nexus/repository/npm-public/

- Execute "mvn -Pprod Package"

Below error message:
************************************Error************************************
[INFO] --- frontend-maven-plugin:1.4:npm (npm install) @ sample-app-mon
olith ---
[INFO] Found proxies: [http{protocol='http', host='proxy.com.mycompany', port=8
080}, https{protocol='https', host='proxy.com.mycompany', port=8080}]
[INFO] Running 'npm install --https-proxy=http://proxy.com.mycompany:8080 --proxy=h
ttp://proxy.com.mycompany:8080' in D:\examples\iframe-sample-app-
monolith
[ERROR] module.js:487
[ERROR]     throw err;
[ERROR]     ^
[ERROR]
[ERROR] Error: Cannot find module 'semver'
[ERROR]     at Function.Module._resolveFilename (module.js:485:15)
[ERROR]     at Function.Module._load (module.js:437:25)
[ERROR]     at Module.require (module.js:513:17)
[ERROR]     at require (internal/module.js:11:18)
[ERROR]     at Object.<anonymous> (D:\examples\iframe-sample-a
pp-monolith\node\node_modules\npm\lib\utils\unsupported.js:2:14)
[ERROR]     at Module._compile (module.js:569:30)
[ERROR]     at Object.Module._extensions..js (module.js:580:10)
[ERROR]     at Module.load (module.js:503:32)
[ERROR]     at tryModuleLoad (module.js:466:12)
[ERROR]     at Function.Module._load (module.js:458:3)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.001 s
[INFO] Finished at: 2017-10-03T15:02:39+08:00
[INFO] Final Memory: 39M/446M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:npm
 (npm install) on project sample-app-monolith: Failed to run task: 'npm
 install --https-proxy=http://proxy.com.mycompany:8080 --proxy=http://proxy.com.mycompany:8080' failed. org.apache.commons.exec.ExecuteException: Process exited with
an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
************************************Error************************************
##### **Suggest a Fix**
Add "npmInheritsProxyConfigFromMaven" to false in "npm install" configuration
           <execution>
                            <id>npm install</id>
                            <goals>
                                <goal>npm</goal>
                            </goals>
                            <configuration>
                                <arguments>install</arguments>
                                <npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
                            </configuration>
                        </execution>

##### **JHipster Version(s)**
4.7.0

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I understand your use case but I don't there is something to do in the generator because it is too specific to every company.
So I think the documentation can be improved: http://www.jhipster.tech/configuring-a-corporate-proxy/

Would you like to submit a PR https://github.com/jhipster/jhipster.github.io

**Comment by jdubois** [comment]
Yes +1 for documentation
