### ISSUE TITLE
Create JHipster project without database but still with Elasticsearch

### ISSUE THREAD

**Issue by anthonyrichir** [jhipster/generator-jhipster#6467]
##### **Overview of the issue**

Allow to create a JHipster project without database and allow to have Elasticsearch and create domain objects that would only be Elasticsearch documents.

##### **Motivation for or Use Case**

In our case, the application data will be fed by an external provider and there is no need for us to save the data in a database. When the external provider calls the API with new content, we only want our application to add the relevant data to the index of Elasticsearch.

JHipster could generate a domain object which would be annotated with @Document, generate the search repositories, services and endpoints to work with Elasticsearch only.

And also, no 

##### **JHipster Version(s)**

4.6.2

**Comment by deepu105** [comment]
That's a lot of work in terms of templating :(

**Comment by jdubois** [comment]
Too much work, we should not do this - and Elasticsearch is not a database, so that's not a good idea.

**Comment by jdubois** [comment]
I'm closing this because we already have way too much work, we just can't do this in the next following months

**Comment by cbornet** [comment]
@anthonyrichir you can do a module if it's important to you.

**Comment by anthonyrichir** [comment]
@cbornet I will have a look, to see if I can handle this or not
