### ISSUE TITLE
Localisation json file can stay in http cache

### ISSUE THREAD

**Issue by stieler-it** [jhipster/generator-jhipster#6473]
##### **Overview of the issue**

After deploying a new release to our environments, we always experience problems with missing or outdated translation keys. We found out that browsers (in our case, Chrome) don't request the new file but use the cached version. All JS files, CSS files and images contain a hash in the production filename and thus are not affected.

##### **Motivation for or Use Case**

In our case we are deploying to an Oracle WebLogic server and don't have control over the cache headers that are sent. But even if we had: Cache or rather cache busting is a complicated topic because not all browsers (or rather, proxies) respect HTTP caching headers as they should. After all, localisation files can become rather large and don't change often, so it should be possible to have them in caches as long as possible. However, caching can only be used if it can be ensured that a new version will be fetched when present.

##### **Reproduce the error**

1. Deploy a production build and open it in a browser
2. Deploy a new version with changed localisation keys and open it in a browser

Expected: Changed localisation keys are shown
Actual: It happens that the old keys are shown. F5 / Shift-F5 does not solve the issue.

##### **Related issues**

n/a

##### **Suggest a Fix**

1. If possible, json files should be built with a hash in their name, too. Of course the reference to them had to be changed as well.
2. Translations could also be integrated in the built javascript files but we probably don't always want all languages to be loaded.

##### **JHipster Version(s)**

4.6.2

##### **JHipster configuration**

.yo-rc.json:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.XXX",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "XXX",
    "packageName": "de.XXX",
    "packageFolder": "XXX",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "oracle",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not related to entities.

##### **Browsers and Operating System**

Chrome on Windows 7, Oracle WebLogic as server

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes you are correct:

- We are very careful not to set cache headers to those, and this is why we have a specific prod configuration -> if you have some kind of caching system in front of it, it should be correctly configured, or work consistently (but I understand your issue)
- Of course, there should be a hash and those should be cached. This would be the best solution both for the project and your specific configuration
- However we still haven't found a good way to do it: I thought we could do it with Webpack, but I just checked and we're not doing it. I don't know why - but we've had this since the beginnings of JHipster, so I know for sure this isn't easy.

-> Help from a Webpack guru is welcome here, otherwise I'm afraid we won't find a good solution, and stay with the current config

**Comment by ctamisier** [comment]
I had the same problem with AngularJS 1 (https://github.com/jhipster/generator-jhipster/pull/6024 + some extra commits).
I didn't have this problem with Angular 4 (but with Tomcat) so the fix in only in AngularJS 1.
Maybe we can apply somehow the same strategy.

**Comment by thmsltmnn** [comment]
I think an additional problem is that the path for the translation files is now determined in the ng-jhipster module, which does not know anything about the build timestamp of the generated application. This makes the solution suggested by @ctamisier impossible. Simply adding the current timestamp would work, but also breaks caching when we want it.

**Comment by atomfrede** [comment]
As the PR https://github.com/jhipster/ng-jhipster/pull/49 is merged, we can close this issue?

**Comment by jdubois** [comment]
I had no idea this was done, that's impressive!! :-)
We should do a new release of ng-jhipster @deepu105 can you do it?

**Comment by deepu105** [comment]
v0.3.1 released

**Comment by stieler-it** [comment]
Thanks a lot!
