### ISSUE TITLE
Missing files and declaration on --skip-server build

### ISSUE THREAD

**Issue by megabitplanet** [jhipster/generator-jhipster#6483]
##### **Overview of the issue**
After the creation of the client with jhipster generator using --skip-server parameter the file auth-expired.interceptor.ts is not present and in login.service.ts in constructor section is not present the private authServerProvider: AuthServerProvider initializtion.
In http.provider.ts missing the folowing import statement:
-import { AuthExpiredInterceptor } from './auth-expired.interceptor';

##### **Motivation for or Use Case**

The appplication doesn't start.

##### **Reproduce the error**

-Generate new jhipster project with --skip-server --auth=jwt --db=mysql
-Run the application with yarn start.

##### **Related issues**

Nope

##### **Suggest a Fix**

-Add the missing file auth-expired.interceptor.ts.
-Add import statement at the top of http.provider.ts.
-Initialize authServerProvider in login.service.ts.

##### **JHipster Version(s)**

4.9.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "FamilyBalanceClient",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "authenticationType": "jwt",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipServer": true,
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": [
      "it",
      "en"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Nope

##### **Browsers and Operating System**

-Chrome Versione 61.0.3163.100 (Build ufficiale) (a 64 bit).
-Windows 10 64bit professional.

**Comment by jdubois** [comment]
Is this a duplicate from #6389 ?

**Comment by megabitplanet** [comment]
Yes.

**Comment by jdubois** [comment]
Then I'm closing this as a duplicate, thanks!
