### ISSUE TITLE
Reproduce a travis build on a local computer

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#6485]
##### **Overview of the issue**

Build a docker image and some script to reproduce the CI build on a local machine

##### **Motivation for or Use Case**

Travis CI tests are the more complete test suite. They run the generator tests + they generate a matrix of sample apps to tests the backend and frontend applications + associated dockers + functional testing.

If a dev want to reproduce all these tests, he has to transform the `.travis-ci.yml` file into a script with some adaptions. 

##### **Suggest a Fix**

The idea is to produce:
1. A docker image withe de desired OS + environement set for testing
2. Scripts that set the appropriate environment variables and run the required installation steps

These scripts could be reused as is in the current travis file.
Another benefits is to be able to reproduce the Travis build on any other CI tool that accepts docker images (Companies could use it in their internal software toolchain).

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
This script already exists! Look at https://github.com/jhipster/generator-jhipster/blob/master/travis/build-samples.sh
But I used it just once... So don't hesitate to improve it.

**Comment by xetys** [comment]
I've also made a similar project for testing a particular travis task, which you can find here: https://github.com/xetys/jhipster-travis-helper

its a bit outdated, but feel free to PR
