### ISSUE TITLE
Facility to add Third-Party libraries(PrimeNG) resources and contents

### ISSUE THREAD

**Issue by sudheerj** [jhipster/generator-jhipster#6493]
The Webpack common file need a Jhipster needle to copy third-party or external libraries contents in to the target folder. The current jhipster-primeng module requires some of the resource files(images,video files and JSON files) to be copied inside target folder. 

The PR is available here https://github.com/jhipster/generator-jhipster/pull/6492

Project: https://github.com/sudheerj/generator-jhipster-primeng

Jhipster version: 4.9.0

**Comment by deepu105** [comment]
PR merged
