### ISSUE TITLE
can't use import-jdl with jdl generated in online JDL-Studio

### ISSUE THREAD

**Issue by GoncaloPT** [jhipster/generator-jhipster#6501]
##### **Overview of the issue**
When i run jhipster import-jdl jhipster-jdl.jh i get the following stacktrace:
 

> 
> The jdl is being parsed.
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: ERROR!
> Error while parsing entities from JDL
> 
>     at Environment.error (D:\projetos\pessoal\jw-meeting-manager\node_modules\yeoman-environment\lib\environment.js:157:40)
>     at error (D:\projetos\pessoal\jw-meeting-manager\node_modules\generator-jhipster\generators\generator-base.js:1676:18)
>     at parseJDL (D:\projetos\pessoal\jw-meeting-manager\node_modules\generator-jhipster\generators\import-jdl\index.js:105:26)
>     at Object.<anonymous> (D:\projetos\pessoal\jw-meeting-manager\node_modules\yeoman-generator\lib\index.js:399:25)
>     at D:\projetos\pessoal\jw-meeting-manager\node_modules\run-async\index.js:25:25
>     at D:\projetos\pessoal\jw-meeting-manager\node_modules\run-async\index.js:24:19
>     at self.env.runLoop.add.completed (D:\projetos\pessoal\jw-meeting-manager\node_modules\yeoman-generator\lib\index.js:400:11)
>     at runCallback (timers.js:672:20)
>     at tryOnImmediate (timers.js:645:5)
>     at processImmediate [as _immediateCallback] (timers.js:617:5)
> 

##### **Motivation for or Use Case**

I'm not being able to import JDL although this is only a small test and i've only 3 entities. No error in JDL-STUDIO

##### **JHipster Version(s)**

 JHipster Generator v4.9.0

##### **JHipster configuration**

jhipster info:

> Using JHipster version installed locally in current project's node_modules
> Executing jhipster:info
> Options:
> Welcome to the JHipster Information Sub-Generator
> 
> ##### **JHipster Version(s)**
> 
> ```
> jwmeetingmanager@0.0.0 D:\projetos\pessoal\jw-meeting-manager
> +-- generator-jhipster@4.9.0
> `-- UNMET PEER DEPENDENCY popper.js@^1.11.0
> 
> ```
> 
> 
> ##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
> 
> 
> <details>
> <summary>.yo-rc.json file</summary>
> <pre>
> {
>   "generator-jhipster": {
>     "promptValues": {
>       "packageName": "pt.goncalo"
>     },
>     "jhipsterVersion": "4.9.0",
>     "baseName": "jwmeetingmanager",
>     "packageName": "pt.goncalo",
>     "packageFolder": "pt/goncalo",
>     "serverPort": "8080",
>     "authenticationType": "jwt",
>     "hibernateCache": "ehcache",
>     "clusteredHttpSession": false,
>     "websocket": false,
>     "databaseType": "sql",
>     "devDatabaseType": "mysql",
>     "prodDatabaseType": "mysql",
>     "searchEngine": false,
>     "messageBroker": false,
>     "serviceDiscoveryType": "eureka",
>     "buildTool": "maven",
>     "enableSocialSignIn": true,
>     "enableSwaggerCodegen": false,
>     "jwtSecretKey": "replaced-by-jhipster-info",
>     "clientFramework": "angularX",
>     "useSass": false,
>     "clientPackageManager": "yarn",
>     "applicationType": "monolith",
>     "testFrameworks": [],
>     "jhiPrefix": "jhi",
>     "enableTranslation": false
>   }
> }
> </pre>
> </details>
> 
> 
> ##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
> 
> <details>
> <summary>JDL entity definitions</summary>
> 
> <pre>
> 
> 
> 
> 
> 
> </pre>
> </details>
> 
> 
> ##### **Environment and Tools**
> 
> java version "1.8.0_144"
> Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
> Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
> 
> git version 2.6.3.windows.1
> 
> node: v6.11.4
> 
> npm: 3.10.10
> 
> bower: 1.8.2
> 
> gulp:
> [18:24:12] CLI version 1.2.1
> 
> yeoman: 2.0.0
> 
> yarn: 1.2.0
> 
> Execution complete

##### **Browsers and Operating System**

Windows 7

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Hi, I'll test it. It may have been a regression...

Checking this out right now.

**Comment by deepu105** [comment]
@MathieuAA hold on the ticket is incomplete. There is no JDL here.
Also I improved the error reporting to show error message produced from jh core.

@GoncaloPT please paste the JDL you used and also try to run `hipster import-jdl jhipster-jdl.jh --debug` and paste the stacktrace

**Comment by MathieuAA** [comment]
> I'm not being able to import JDL although this is only a small test and i've only 3 entities

This is not the default JDL, isn't? 
This is the default one:
```
entity Region {
	regionName String
}

entity Country {
	countryName String
}

// an ignored comment
/** not an ignored comment */
entity Location {
	streetAddress String,
	postalCode String,
	city String,
	stateProvince String
}

entity Department {
	departmentName String required
}

/**
 * Task entity.
 * @author The JHipster team.
 */
entity Task {
	title String,
	description String
}

/**
 * The Employee entity.
 */
entity Employee {
	/**
	* The firstname attribute.
	*/
	firstName String,
	lastName String,
	email String,
	phoneNumber String,
	hireDate ZonedDateTime,
	salary Long,
	commissionPct Long
}

entity Job {
	jobTitle String,
	minSalary Long,
	maxSalary Long
}

entity JobHistory {
	startDate ZonedDateTime,
	endDate ZonedDateTime,
	language Language
}

enum Language {
    FRENCH, ENGLISH, SPANISH
}

relationship OneToOne {
	Country{region} to Region
}

relationship OneToOne {
	Location{country} to Country
}

relationship OneToOne {
	Department{location} to Location
}

relationship ManyToMany {
	Job{task(title)} to Task{job}
}

// defining multiple OneToMany relationships with comments
relationship OneToMany {
	Employee{job} to Job,
	/**
	* A relationship
	*/
	Department{employee} to
	/**
	* Another side of the same relationship
	*/
	Employee
}

relationship ManyToOne {
	Employee{manager} to Employee
}

// defining multiple oneToOne relationships
relationship OneToOne {
	JobHistory{job} to Job,
	JobHistory{department} to Department,
	JobHistory{employee} to Employee
}

// Set pagination options
paginate JobHistory, Employee with infinite-scroll
paginate Job with pagination

dto * with mapstruct

// Set service options to all except few
service all with serviceImpl except Employee, Job
// Set an angular suffix
angularSuffix * with mySuffix
```
Please, do copy/paste your JDL.

**Comment by MathieuAA** [comment]
@deepu105 you're a bit faster than I am ;)

**Comment by GoncaloPT** [comment]
Hi,
I get this error with any jdl...
I remember that the jdl was generated using JDL-Studio, and no errors exist in there.
The last JDL i tried:
```

entity Table1 {
	data Date required
}
entity Table2{
	nome String required,
    duracao Int required
}
```
I get the exact same error.

Thanks for your time

**Comment by MathieuAA** [comment]
> Also I improved the error reporting to show error message produced from jh core.

@deepu105 can you enable the `--debug` flag by default or your improvement is enough?

**Comment by deepu105** [comment]
The improvement is enough, --debug is only needed for troubleshooting[ this line](https://github.com/jhipster/generator-jhipster/blob/master/generators/import-jdl/index.js#L111) should already show proper error message

**Comment by MathieuAA** [comment]
Thanks!
