### ISSUE TITLE
Adding a field on entity after first generation modifies the first changeset

### ISSUE THREAD

**Issue by anthonyrichir** [jhipster/generator-jhipster#6508]
##### **Overview of the issue**

When adding a field on an existing entity, Jhipster modifies the create column statement.
This leads to errors with Liquibase when the project has already been deployed, as the changeset checksum will change.

##### **Motivation for or Use Case**

Although Jhipster is meant for bootstrapping a project, it should also allow to modify and redeploy a project generated with it.

##### **Reproduce the error**

1. Generate a new project with a DB such as MySQL
2. Create an entity with one field
3. Run the project
4. Add a field to your entity
5. Rerun the project

##### **Suggest a Fix**

Each time the entity subgenerator is called, Jhipster should create a new changeset.

**Comment by gmarziou** [comment]
https://github.com/jhipster/generator-jhipster/pull/6016

**Comment by jdubois** [comment]
- yes you are correct, but this isn't easy to do -> indeed, there's already PR #6016 on this
- otherwise the recommended workflow for this is to use `mvn liquibase:diff` -> see http://www.jhipster.tech/development/#using-a-database

I'm closing this as work is being done on #6016
