### ISSUE TITLE
Swagger generator issue

### ISSUE THREAD

**Issue by jimmysyss** [jhipster/generator-jhipster#6512]
##### **Overview of the issue**

JHipster generated project runs well when triggers from command line. However, it sucks with the bootRun Gradle tasks in Eclipse. 

The failing reasons is the Swagger sub task gradle file miss a "file" setting, which cause the Gradle tasks fail in Eclipse. 

##### **Suggest a Fix**

Before
`
swagger {
    inputSpec = 'src/main/resources/swagger/api.yml'
    outputDir = file('build/swagger')
    lang = 'spring'
`
Fixed
`
swagger {
    inputSpec = file('src/main/resources/swagger/api.yml')
    outputDir = file('build/swagger')
    lang = 'spring'
`
The issue has to be fixed on the generator side. 

##### **JHipster Version(s)**

JHipster 4.7.0

##### **JHipster configuration**

`
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jimmy.easysme",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "easysme",
    "packageName": "com.jimmy.easysme",
    "packageFolder": "com/jimmy/easysme",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "XXXXXX",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn",
      "zh-tw"
    ]
  }
}
`

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

Ubuntu 16.04.03 LTS
Eclipse Oxygen
JDK 1.8.0_144

**Comment by cbornet** [comment]
This should be solved by #6468 . Can you check on master ?

**Comment by deepu105** [comment]
@jimmysyss please ask to reopen if you the fix is not working
