### ISSUE TITLE
consul cannot change host and port

### ISSUE THREAD

**Issue by frank8559** [jhipster/generator-jhipster#6513]
Hello,

##### **Overview of the issue**

The documentation http://cloud.spring.io/spring-cloud-consul/multi/multi_spring-cloud-consul-discovery.html explain that if using Spring Cloud Consul Config, the following code 

> spring:
  cloud:
    consul:
      host: localhost
      port: 8500

must be put in bootstrap.yml is not in application.yml

##### **Motivation for or Use Case**

I want to be able to use an external consul cluster

##### **Reproduce the error**

Try changing the name of the host consul, spring boot always uses localhost, idem if you change the port

##### **Related issues**

none

##### **Suggest a Fix**

move the configuration of the host and port in the bootstrap.yml file

##### **JHipster Version(s)**

4.9.0

Sorry for my english
And great job

**Comment by jdubois** [comment]
I don't know what to say - I do this all the time (with Docker, the Consul host is "consul", not localhost), so I don't get what your issue can be. Besides, those shouldn't be in `bootstrap.yml` or Spring Cloud Config server couldn't re-configure this.
Maybe I'm wrong, but I just don't understand. Comments from people experiencing this issue (or not!!) are welcome, to help me understand.

**Comment by frank8559** [comment]
Hello,
my cluster consul is outside of my docker swarm cluster.
So it is accessible via a fqdn consul.intranet.fr.
If I put consul.intranet.fr as a host, and I do mvnw (on my dev machine), spring boot tries to connect to localhost: 8500.
If I move the configuration to the bootstrap file, it works.(as it is written in the documentation cited in my first post)
When I use the docker-compose sub generator, it actually works. But running all the stack on my dev machine is much too slow. So I try to outsource services that will not be changed regularly (here consul)

**Comment by xetys** [comment]
did you check if there is some consul configuration inside the app-wide config delivered by the consul KV?

**Comment by PierreBesson** [comment]
@frank8559 I agree that this property should be in our bootstrap.yml file to document that it can be changed. We already do this with Eureka so we are not consistent here.

The reason it cannot be in application.yml comes from spring cloud config. The app starts with the boostrap context (so it knows only boostrap properties at first) then connect to the config server to retrieve further properties, which is the consul kv store so it needs to know its URL. The application.yml properties are loaded next **only** for properties not defined in the central config source which have the highest precedence.

@frank8559 Can you submit a PR ?

**Comment by frank8559** [comment]
I forgot to specify that I also have to change the CONSUL_URL variable of the service consul-config-loader to point to consul.intranet.fr.
Without that I had logically no data in the K / V.

I just regenerated a gateway from scratch.
I then use the sub generator docker-compose.

- In the **consul.ym**l file, I have modified the **CONSUL_URL** variable with the **consul.intranet.fr** value.

- In the **docker-compose.yml** file, I disabled the gateway-app service and the consul service. i didn't disable the consul-config-loader service.
I have to add port forwarding for posgres, kafka and elasticsearch in order to use localhost.

- I then modify in the file **application-dev.yml**, the variable **cloud.consul.host** from **localhost** to **consul.intranet.fr**.
Then i did _docker-compose up_ and into another shell i start _mvnw_ .
At the start of the application (with mvnw), i have a unable to connect localhost: 8500.
The consul-config-loader service correctly fills the K / V of my consul.intranet.fr

I then move the code cloud.consul.host (and port) into bootstrap.yml
I restart _mvnw_ and my gateway is accessible, and is visible in my cluster consul

I can't share code, nor copy paste the stack trace, because  security restriction (Department of Defense :D).

Thanks

**Comment by PierreBesson** [comment]
Yes as I have said before the `consul.host/port` must be set in bootstrap.yml otherwise, we have this sequence of events:
- The application starts in bootstrap context phase.
- The Spring Cloud Config client tries to connect to consul for retrieving centrally defined properties.
- It reads the value of `consul.host` to know the URL of the consul server. By default it is set to `localhost:8500` (see: [spring-cloud/spring-cloud-consul/ConsulProperties](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-core/src/main/java/org/springframework/cloud/consul/ConsulProperties.java#L35))
- You get the error: `unable to connect to localhost`
- It finally loads the application.yml but it's too late.

**Comment by frank8559** [comment]
@PierreBesson It is currently impossible to do a PR.
I will try to submit a procedure to my hierarchy to be able to PR.
We develop offline which complicates quite a lot ...

**Comment by Abhishek9166919669** [comment]
A
