### ISSUE TITLE
OIDC and microservices current issues

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6519]
This is a ticket to follow up #6514 and to help discussing with @danielpetisme @mraible @sendilkumarn who are all helping here.

- [x] The current build is broken because we don't have UserMapper in a microservice -> @mraible and @danielpetisme introduced a method to sync user data between the gateway and the microservices, which makes the microservices have a "User" object. However, if you choose to use DTOs (another entity which uses a DTO has a relationship to the `User`), this means you also need a `UserMapper` and a `UserDTO`, specific for microservices. This sounds quite complex to me!
- [x] Once compilation is done, we also have a testing issue. The current code (if it compiled) would fail because `resourceServerProperties.getJwt().getKeyUri()` is not configured in the test resources `application.yml` file. Configuring it wouldn't solve the issue: you need an OIDC server to do the tests. That's also pretty bad, as this prevents us to do unit tests unless we run that server: as this works for monoliths without doing this, we need to check how it works for monoliths, and apply the same method to gateways and microservices.
- [x]  We need to test monoliths, gateways and microservices with Cassandra
- [x]  When doing a gateway + microservice: create an entity in the microservice, and then create its front-end on the gateway. There is a CSRF token issue that prevents write requests to work from the gateway to the microservice - I don't know if we should pass the CSRF token or ignore it (not sure OIDC allows CSRF attacks)
- [x]  Swagger UI does not work with OAuth2
- [x]  When doing a monolith, and selecting JHipster Registry, we currently force the use of JWT. We should be able to use OAuth2 also.
- [x]  The JHipster Registry does not work with OIDC. We should do a specific Spring profile for OIDC.
- [x]  For microservice, we need to check that doing `csrf().disabled()` in the Spring Security configuration doesn't cause a security risk

**Comment by mraible** [comment]
I only know about monoliths, not microservices, so my comments pertain to that. 

I found that I needed to have the same 'security.oauth2' properties in src/test/resources/application.yml as I had in the main one to get tests to pass. I didn't need to have an OAuth server running, it just needed this properties.

**Comment by jdubois** [comment]
@mraible what, you don't know about microservices?? :-)
Indeed it works for monoliths - I don't know what you did, but we need the same for gateways and microservices -> I'm updating the todo list accordingly

**Comment by jdubois** [comment]
OK for microservices it's a bit different from monoliths as there is a JWT exchange from the OIDC server to the microservice - I think I got this, I'll commit something soon.

**Comment by danielpetisme** [comment]
@jdubois when you use `uaa` the microservice fails to start if the authorization server is down . I using `uaa` since 6months so yes it's annoying to have an OAuth server running but IMHO it's an understandable constraints. 
For the unit test issue, maybe https://www.testcontainers.org/ could be a neat solution. I didn't tested yet but programatatically starting a Keycloak container for unit test could solve the issue.

Again with `uaa` I was used to create my `User` representation in service which need one + a `uaa` Feign client in the service. I didn't sync locally the user it only exist once in the IdP. Duplicating this responsability could be tricky (as always you try to maintain sync 2 things in different places).

**Comment by jdubois** [comment]
Thanks @danielpetisme but it's solved easily, see my commit https://github.com/jhipster/generator-jhipster/commit/e4c34c7f119c0a5407eab2b05c5e24b9b2a69916 above :-)

**Comment by danielpetisme** [comment]
Neat indeed!

Le 14 oct. 2017 9:51 PM, "Julien Dubois" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
So for the first point, I don't think we can do a relationship to the User, when OIDC is selected, see [my comment here](https://github.com/jhipster/generator-jhipster/pull/6523#issuecomment-336715667). At least not in a first release. WDYT?

**Comment by mraible** [comment]
@jdubois I'd vote that we **don't allow** a relationship to `User` when microservices is selected, but we **do** when it's a monolith. I had that working with my user synching code. That way, the following expression works.

```
@Query("select blog from Blog blog where blog.user.login = ?#{principal.username}")
```

**Comment by danielpetisme** [comment]
+1

**Comment by jdubois** [comment]
Yes, totally agree. And that would be consistent with JWT authentication which is perfect.

**Comment by jdubois** [comment]
Oh sorry @mraible @danielpetisme I started testing the monolith (I was just working on microservices) but that's the same issue: as long as the `User` isn't a JPA entity you can't do relationships with it.

- I don't think that could work
- With DTOs that's going to be even more complex
- I'm worried to have a `User` table in each application, that is just a copy of the OIDC server, that's not good to copy/paste such information everywhere

I'm afraid we are stuck here, unless there's something I don't understand? Otherwise I would like to remove that user sync code, so we can move on with a first release (lots of people and PRs are waiting). If we find a solution later, we can still add it in a future release.

**Comment by mraible** [comment]
@jdubois I'm working on making monoliths work with a `User` table and JPA entity. This was working before the accidental merge of OIDC microservices. I'll keep the current implementation for microservices.

**Comment by jdubois** [comment]
Oh OK @mraible I'm eager to see your code

**Comment by sendilkumarn** [comment]
I do agree with @mraible here. I saw his code was working well for monolith. 

👍 for removing that in microservices

**Comment by danielpetisme** [comment]
This is the snippet I used to code to fullfill the `api/account` endpoint without syncing the user.
```
   /**
     * GET  /authenticate : check if the user is authenticated, and return its login.
     *
     * @param request the HTTP request
     * @return the login if the user is authenticated
     */
    @GetMapping("/authenticate")
    @Timed
    public String isAuthenticated(HttpServletRequest request) {
        log.debug("REST request to check if the current user is authenticated");
        return request.getRemoteUser();
    }

   /**
     * GET  /account : get the current user.
     *
     * @return the current user
     * @throws RuntimeException 500 (Internal Server Error) if the user couldn't be returned
     */
    @GetMapping("/account")
    @Timed
    @SuppressWarnings("unchecked")
    public ResponseEntity<User> getAccount(Principal principal) {
        return Optional.ofNullable(principal)
            .filter(it -> it instanceof OAuth2Authentication)
            .map(it -> ((OAuth2Authentication) it).getUserAuthentication())
            .map(authentication -> {
                    Map<String, Object> details = (Map<String, Object>) authentication.getDetails();
                    return new User(
                        authentication.getName(),
                        (String) details.get("given_name"),
                        (String) details.get("family_name"),
                        (String) details.get("email"),
                        (String) details.get("langKey"),
                        (String) details.get("imageUrl"),
                        (Boolean) details.get("email_verified"),
                        authentication.getAuthorities().stream().map(it -> it.getAuthority()).collect(Collectors.toSet())
                    );
                }
            )
            .map(user -> new ResponseEntity<>(user, HttpStatus.OK))
            .orElse(new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR));
    }
```

**Comment by mraible** [comment]
I just pushed changes to add user synchronization back to an OAuth monolith. PR > https://github.com/jhipster/generator-jhipster/pull/6523. 

@danielpetisme I found that `(String) details.get("email")` throws a NPE. Not sure if you need a null check for microservices too.

**Comment by mraible** [comment]
@jdubois Build should be fixed if you merge https://github.com/jhipster/generator-jhipster/pull/6523.

**Comment by jdubois** [comment]
So the big issues are fixed, I just added a new todo on a CSRF issue - I need to check this a little bit and we'll probably end up removing CSRF on microservices (as it basically doesn't make any sense)

**Comment by sdoxsee** [comment]
@jdubois I think you're right. As far as I understand it, CSRF makes sense from browser to gateway for session-based oidc  but not from gateway to downstream microservices as those receive JWTs.

**Comment by jdubois** [comment]
Thanks @sdoxsee I just checked and indeed we have `csrf().disabled()` in our Spring Security config from the beginning, both for gateways and microservices.
Here the error message comes from a microservice, and I have **no idea** how to remove it, as it's already disabled!!! Totally stuck here :-(

**Comment by danielpetisme** [comment]
@jdubois did you get a specific error message? How can I reproduce?

**Comment by jdubois** [comment]
@danielpetisme thanks for helping, here are:

- My gateway: https://github.com/jdubois/oidc-gateway
- My microservice: https://github.com/jdubois/oidc-microservice

They both use the code from the current master branch, and need a JHipster Registry and Keycloak to work, so in the gateway you must run:

    docker-compose -f src/main/docker/jhipster-registry.yml up -d
    docker-compose -f src/main/docker/keycloak.yml up -d

Then start both projects by running `./mvnw`

Once you are logged in, go to the `Yolo` entity and create a new entity. This entity comes from the microservice, and is served through the Zuul proxy.

On the first "create" request you will get:

<img width="847" alt="screenshot 2017-10-17 12 18 05" src="https://user-images.githubusercontent.com/316835/31659925-ff9e2524-b335-11e7-8eb2-a9e7e2657ed4.png">

And if you do a second "create" request:

<img width="856" alt="screenshot 2017-10-17 12 18 14" src="https://user-images.githubusercontent.com/316835/31659957-1c3a3cd6-b336-11e7-8174-50e0e6570084.png">

**Comment by jdubois** [comment]
@danielpetisme this is worrying:

- In order to work, you must disable CSRF in the `OAuth2SsoConfiguration` in the gateway. That's weird as this is already disabled in `MicroserviceSecurityConfiguration` but the conf there looks ignored.
- From what I see, there is a stateful mechanism here, so does that mean we should keep the CSRF protection?
- Once this is done, I have an "unauthorized" error on the microservice: it looks like security did not get propagated...

**Comment by jdubois** [comment]
OK I got it working and I'm going to push my changes soon:

- I'm disabling CSRF in `OAuth2SsoConfiguration` as mentioned in my comment above: I'm not sure it causes an issue (which is worrying, and which is why this is still BETA), but anyway I don't think this can work in a microservice architecture (as the CSRF token would need to be shared everywhere, which is stupid)
- I just realized that @danielpetisme only worked on making authentication work with a Feign client, using `TokenRelayRequestInterceptor`. I just needed to use the same code in the Zuul `TokenRelayFilter` on the gateway, and you have Zuul working :-)

**Comment by danielpetisme** [comment]
Great! We're so close!!! I can smell the merge coming :)

**Comment by danielpetisme** [comment]
after you merge #6548  is there other blocking issues you're aware of?

**Comment by jdubois** [comment]
Not blocker, but Swagger UI is not working

**Comment by jdubois** [comment]
@danielpetisme I'm adding some stuff in the todo list on top of this ticket

**Comment by danielpetisme** [comment]
@jdubois the swagger UI issue comes from a frame options configuration. It's set to deny.
In `OAuth2SsoConfiguration` update the method like the following snippet and it work.
```
@Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .headers().frameOptions().sameOrigin();
        http
            .requestMatcher(new NegatedRequestMatcher(authorizationHeaderRequestMatcher))
            .authorizeRequests()
            .anyRequest().permitAll();
    }
```
it looks like a common issue for application using oauth and trying to embed external content into an iframe (like youtube for instance).

**Comment by jdubois** [comment]
I'm adding a new todo item: the JHipster Registry just doesn't work with OIDC. That should be simple to solve, but then do we do a specific JHipster Registry build? Or add a Spring profile?

**Comment by jdubois** [comment]
I started to implement OIDC support in the JHipster Registry -> the ticket on the registry is https://github.com/jhipster/jhipster-registry/issues/193

**Comment by danielpetisme** [comment]
I have a working prototype of OIDC with `angular-oauth2-oidc` that means no more user management code on the backend side (except if you need a user sync). Wondering if it interests anyone? Does it worth a PR?
The implementation requires to have a look to #6565

**Comment by jdubois** [comment]
@danielpetisme I have no idea what this will do - at the moment I'm still stuck with https://github.com/jhipster/jhipster-registry/issues/193 - I spent a few hours on it today again, but no luck :-(

**Comment by jdubois** [comment]
Closing as everything is done
