### ISSUE TITLE
Integration test fail with ConstraintViolationException when User is used twice

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6521]
##### **Overview of the issue**

In `UserResourceIntTest` the default login is `johndoe` but because the login must be unique, creating a domain object with two relations on User fails with a `ConstraintViolationException`.

##### **Motivation for or Use Case**

The `UserResourceIntTest` sets the default login to a fix value (`johndoe`):

```
public class UserResourceIntTest {
    private static final String DEFAULT_LOGIN = "johndoe";
}
```
Login has a unique constraint defined in the Liquibase file (`unique="true"`):

```
<column name="login" type="varchar(50)">
    <constraints unique="true" nullable="false"/>
</column>
```
So when you have a domain that is related twice (indirectly) to User, two users `johndoe` are created, therefore, there is a `ConstraintViolationException`

##### **Reproduce the error**

Take a JHipster monolith and import the following JDL. Because we can't add extra information on `User`, here, I've created a `Representative` that has a one to one relation to `User`. Now, let's say that an `Invoice` is signed by a `Representative` (a `User`), an `Invoice` is related to a `Contract`, which can be signed by a different `Representative`.

```
entity Contract {
    price Integer,
    discountRate Float,
    vatRate Float,
    nbTicketsAttendee Integer,
    nbTicketsExhibitor Integer,
    additionalInformation String
    createdOn Instant
}

entity Invoice {
    limitPaymentDate LocalDate,
}

entity Representative {
    phoneArea String,
    phoneNumber String
}

relationship ManyToOne {
    Invoice{representativeSigning(lastName) required} to Representative,
    Contract{representativeSigning(lastName) required} to Representative
}

relationship OneToOne {
    Representative{user(lastName) required} to User
}

relationship OneToMany {
    Contract{invoices} to Invoice{contract required}
}
```

The `InvoiceResourceIntTest` creates an invoice, creates and persists the representative for the invoice (therefore, one `johndoe`), creates and persists the representative of the contract (that is the second `johndoe`).

##### **Suggest a Fix**

Because the login must be unique, instead of setting a fix value, it should be a random string. So, instead of:

```
public static User createEntity(EntityManager em) {
    User user = new User();
    user.setLogin(DEFAULT_LOGIN);
    user.setPassword(RandomStringUtils.random(60));
    ...
    return user;
}
```

It could be something like 

```
public static User createEntity(EntityManager em) {
    User user = new User();
    user.setLogin(DEFAULT_LOGIN + RandomStringUtils.random(10));
    user.setPassword(RandomStringUtils.random(60));
    ...
    return user;
}
```

And, instead of checking that the login is equal to `johndoe`:

```
assertThat(testUser.getLogin()).isEqualTo(DEFAULT_LOGIN);
```

Maybe just check that it's starts with `johndoe`:

```
assertThat(testUser.getLogin()).startsWith(DEFAULT_LOGIN);
```

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
##### **JHipster Version(s)**

```
sponsors@0.0.0 /Users/agoncal/Documents/Code/Temp/jhipster/sponsors
└── generator-jhipster@4.9.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.quantixx.sponsor"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "sponsors",
    "packageName": "io.quantixx.sponsor",
    "packageFolder": "io/quantixx/sponsor",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Contract (contract) {
  price Integer,
  discountRate Float,
  vatRate Float,
  nbTicketsAttendee Integer,
  nbTicketsExhibitor Integer,
  additionalInformation String,
  createdOn Instant
}
entity Representative (representative) {
  phoneArea String,
  phoneNumber String
}
entity Invoice (spn_invoice) {
  limitPaymentDate LocalDate
}

relationship OneToOne {
  Representative{user(lastName) required} to User
}
relationship OneToMany {
  Contract{invoices} to Invoice{contract required}
}
relationship ManyToOne {
  Contract{representativeSigning(lastName) required} to Representative,
  Contract{representativeAccepting(lastName) required} to Representative,
  Invoice{representativeSigning(lastName) required} to Representative
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.14.2

node: v8.7.0

npm: 5.4.2

bower: 1.8.0

gulp:
[16:58:25] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.2.1

Docker version 17.09.0-ce, build afdb6d4

**Comment by Blackdread** [comment]
Just a note:
[RandomStringUtils](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/RandomStringUtils.html) for apache is deprecated for next version (3.6) if jHipster updates that dependency after.

**Comment by agoncal** [comment]
And the same issue might also occur with email. Email and login are both declared unique in the `00000000000000_initial_schema.xml` file.

**Comment by deepu105** [comment]
PR please

**Comment by jdubois** [comment]
Yes but don't use a random String: it would change when you re-generate, so you get overwritten lines for no real reason. That's more work when you upgrade, for nothing.

**Comment by agoncal** [comment]
@jdubois Sorry, I didn't understand.

Having a random string is not the right solution (except if we change the tests) because the `createUserWithExistingLogin` method expects `johndoe` to already exist. With a random suffix, the test breaks.

I don't know what to do to fix the bug and minimize changing the test.

**Comment by agoncal** [comment]
@jdubois Sorry, I didn't understand.

Having a random string is not the right solution (except if we change the tests) because the `createUserWithExistingLogin` method expects `johndoe` to already exist. With a random suffix, the test breaks.

I don't know what to do to fix the bug and minimize changing the test.

**Comment by jdubois** [comment]
@agoncal as you posted the same comment twice, I deleted the second one :-)

So the issue is that a random String will change with each generation, so that will be annoying for upgrades. Usually we increment a number -> the idea is to have something different, but which is reproductible when we re-generate

**Comment by duderoot** [comment]
When creating an _Invoice_ in _InvoiceResourceIntTest_ a _Representative_ and a _Contract_ are created.
A _Representative_ is creating a _User_ which is ok. The problem is that a _Contract_ it's also creating a _Representative_ which is also trying to create a _User_ and because of unique constrains it's fails.
IMHO I will stay with @agoncal options of adding a random string on the unique keys of user, i.e. login and email. On the other hand I totally agree with @jdubois that the test should be the same after an update.
I will add a PR which is adding the id of the last inserted user in the db as a string to the login and email.
There could have been also a second option: when creating an Invoice first create a Contract which is creating a Representative and then add to the Invoice the Representative which was created  in contract.
  ``` 
Contract contract = ContractResourceIntTest.createEntity(em);
em.persist(contract);
em.flush();
invoice.setContract(contract);
invoice.setRepresentativeSigning(contract.getRepresentativeSigning());
```
I think that it will be a huge overhead to implement such logic in the generator. Please let me know if that will be feasible and I will be grateful for some hints.
In the meanwhile I will submit a PR with the first solution

**Comment by cbornet** [comment]
@jdubois the random string is created at test runtime so I don't see the problem with regeneration. We do the same for the password.
@agoncal for `createUserWithExistingLogin`, we can test with `user.getLogin()`

I would find a Random string less complex than getting the last user id

**Comment by cbornet** [comment]
Hint : use `randomAlphabetic` and not `random`  to prevent issues with forbidden chars in login and email.

**Comment by jdubois** [comment]
No we store the JWT key in .yo-rc.json for this reason. The idea is that if you re generate it should give the same output.

**Comment by cbornet** [comment]
But it's only for JAVA tests. The random is not done by the generator !

**Comment by cbornet** [comment]
If you regenerate, you will get the same output !

**Comment by duderoot** [comment]
@cbornet what will be the motivation for random compare to the current solution which is the id of the last inserted User?

**Comment by jdubois** [comment]
Oh sorry I was on my phone - yes if the random is done in Java, but not by the generator, then that's totally OK

**Comment by cbornet** [comment]
@duderoot simpler, less code

**Comment by duderoot** [comment]
@cbornet that was short and concise 😄  👍 I just cahnge the code to use a `randomAlphabetic` with a size of five.
