### ISSUE TITLE
jhiPrefix remains "jhi" after in .angular-cli.json being specified with --jhi-prefix

### ISSUE THREAD

**Issue by mahatosourav91** [jhipster/generator-jhipster#6525]
**Overview of the issue**

I am trying to generate a monolithic an Angular 4 app with jhipster. I have specified a custom -- jhi-prefix but my generated angular components are services still have the "jhi" default prefix

 **Motivation for or Use Case**
 As per the documentation, mentioning --jhi-prefix should 

> "Add prefix before services, components and state/route names (Default: jhi)"

**Reproduce the error**

I am generating the app using the following command

`yo jhipster:app --skip-install --skip-user-management --jhi-prefix app --npm --skip-cache`

**Related issues**
[https://github.com/jhipster/generator-jhipster/issues/6003](url)

 **JHipster Version(s)** 4.9.0

**JHipster configuration**
.yo-rc.json
`{
  "generator-jhipster": {
    "jhipsterVersion": "4.9.0",
    "baseName": "sonarpulse",
    "packageName": "com.sonarpulse",
    "packageFolder": "com/sonarpulse",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "04c629cd4d358cbc94bee0c282430bcd394878a4",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "app",
    "skipUserManagement": true,
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}`

.angular-cli.json

`{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "project": {
        "name": "sonarpulse"
    },
    "apps": [{
        "root": "src/main/webapp",
        "outDir": "target/www/app",
        "assets": [
            "content",
            "i18n",
            "favicon.ico"
        ],
        "index": "index.html",
        "main": "app/app.main.ts",
        "polyfills": "app/polyfills.ts",
        "test": "src/test/javascript/spec/entry.ts",
        "tsconfig": "../../../tsconfig.json",
        "prefix": "jhi",
        "mobile": false,
        "styles": [
            "content/css/vendor.css",
            "content/css/global.css"
        ],
        "scripts": []
    }],
    "lint": [{
            "project": "../../../tsconfig.json"
        },
        {
            "project": "../../../tsconfig-aot.json"
        }
    ],
    "test": {
        "karma": {
            "config": "src/test/javascript/karma.conf.js"
        }
    },
    "defaults": {
        "styleExt": "css",
        "prefixInterfaces": false,
        "component" : {
            "inlineStyle" : true,
            "inlineTemplate": false,
            "spec": false
        },
        "directive" : {
            "spec": false
        },
        "guard" : {
            "spec": false
        },
        "pipe" : {
            "spec": false
        },
        "service" : {
            "spec": false
        }
    },
    "packageManager": "yarn"
}
`

**Comment by deepu105** [comment]
probably a missing template interpolation. should be very easy to fix by replacing the hard coded value in the template with the variable

**Comment by sophiekoonin** [comment]
Think I've spotted the issue - I'll take this

**Comment by mahatosourav91** [comment]
Can anybody please tell where in generator-jhipster node module I should change to get an expected result?  I want to fix locally till a patch is given.
@sophiekoonin @deepu105

**Comment by sophiekoonin** [comment]
Damn. Thought I had it, but I can't get it to change in .angular-cli.json (despite the template interpolation already being there). 

My hunch was, in`app/index.json`:

```
 this.jhiPrefix = this.configOptions.jhiPrefix || this.config.get('jhiPrefix') || this.options['jhi-prefix'];
```

should have been
```
this.jhiPrefix = this.configOptions.jhiPrefix = this.config.get('jhiPrefix') || this.options['jhi-prefix'];
```

But I'm not sure this has made a difference. Perhaps someone else has a better idea?

**Comment by deepu105** [comment]
@sophiekoonin yes Indeed in `app/index.js` its should be `this.jhiPrefix = this.configOptions.jhiPrefix = this.config.get('jhiPrefix') || this.options['jhi-prefix'];` that should fix the issue.
In the meantime, you can use the master branch to use the fixed code just clone the repo and run `npm link` on the folder to use the master branch instead of the global installed generator. If you have an existing project then you also need to run `npm link generator-jhipster` in that project folder.

If you wish you can submit the fix as a PR, we are planning to do a release soon

**Comment by sophiekoonin** [comment]
@deepu105 Great, that's what I'd done - but I couldn't get it to change the prefix listed in `.angular-cli.json`, so I couldn't assert it had changed in a unit test!

**Comment by jdubois** [comment]
The `npm link` should do the trick (but now I'm using `yarn link` and I have quite a number of issues with it, so I hope it works well for you). At least, if you see your changed code in a generated project, that should be OK.

**Comment by sophiekoonin** [comment]
Sweet, pull request incoming!

**Comment by mahatosourav91** [comment]
Hi, @sophiekoonin @deepu105 
Should the use of `--npm` option, will "`packageManager": "yarn"` in .angular-cli.json?

**Comment by deepu105** [comment]
@mahatosourav91 I think if using npm it should be same there as well. Again missing template I guess
