### ISSUE TITLE
Universal DateTime Picker Support

### ISSUE THREAD

**Issue by areifers** [jhipster/generator-jhipster#654]
First off, this is an awesome project. The default DateTime picker for input date fields only works in Chrome.  Support for falling back to jQuery's DateTime picker in the autogenerated Date input field would be a great enhancement.

**Comment by jgribonvald** [comment]
Some docs on how to integrate a datepicker would be great in this case for each date like datetime and localdate, what do you think ?

**Comment by jdubois** [comment]
Yes, as we can't solve it, the best thing would be to document it

**Comment by hunterino** [comment]
Look like this may not be an active discussion, but I would recommend datepicker interface, that uses as close as possible, the HTML5 approach, so that people can implement that interface, and have whatever date picker they need.
