### ISSUE TITLE
Running ChromiumHeadless as root (in docker)

### ISSUE THREAD

**Issue by ValentinCunci** [jhipster/generator-jhipster#6545]
##### **Overview of the issue**

Issue occurs when executing the frontend tests on docker (in my case, using gitlab ci is triggering the build). Chromium cannot be started. See error below :

`[INFO] 17 10 2017 07:25:33.822:ERROR [launcher]: ChromiumHeadless stderr: [1017/072533.820415:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`

##### **Motivation for or Use Case**

It used to work with phantomjs, does not work anymore with lastest version using chromium. Now, that said, maybe I'm doing things wrong, and I should create a specific user in my docker, if someone has any thought on this, I'd like to hear it. 
However, running chromium with --no-sandboxing option does not seem like a problem or a security issue in this particular case.

##### **Reproduce the error**

Run mvn clean install -Pprod using the following docker image :

```
FROM maven:3
RUN apt-get -y update && apt-get install -y chromium libgconf-2-4
```

##### **Suggest a Fix**

Fix : 
Add --no-sandbox option for chromium execution in karma.conf.js

```
browsers: ['ChromiumHeadlessNoSandbox'],

        customLaunchers: {
            ChromiumHeadlessNoSandbox: {
                base: 'ChromiumHeadless',
                    flags: ['--no-sandbox']
            }
        },
```

I'm creating a pull request for this, in case you think it's a good solution.

##### **JHipster Version(s)**

4.9.0

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.asten.telesuivi",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "telesuivi",
    "packageName": "com.asten.telesuivi",
    "packageFolder": "com/asten/telesuivi",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mssql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}
</pre>
</details>

##### **Browsers and Operating System**

Chromium and docker

Problem occurs on Docker
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
@ValentinCunci You don't actually need to installation Chromium on your system/docker image. Pupetteer will take care if downloading the chromium binary for you.

Otherwise I'm OK with this change.

**Comment by ValentinCunci** [comment]
@PierreBesson yes you're right, I actually installed chromium because the maven docker image was missing some dependencies (libxss1 at least) which prevented chromium from starting, and I didn't wan't to waste time on this at the time (I don't know if other dependencies are missing).

Thanks for your feedback !

**Comment by ramzimaalej** [comment]
I run into a similar issue with chrome headless, and adding this flag solved it.
