### ISSUE TITLE
Always declare ResponseEntity class in controller methods

### ISSUE THREAD

**Issue by encos** [jhipster/generator-jhipster#6558]
##### **Overview of the issue**

Now that Problem is used everywhere to handle errors we could avoid using an empty ResponseEntity in method declarations. Instead we could always use:
`ResponseEntity<Void>`
or 
`ResponseEntity<MyClass>`

Only two classes are affected:
**UserResource**
`public ResponseEntity createUser(@Valid @RequestBody ManagedUserVM managedUserVM) throws URISyntaxException`

**UserJWTController**
`public ResponseEntity authorize(@Valid @RequestBody LoginVM loginVM, HttpServletResponse response)`

##### **Motivation for or Use Case**

A method with this kind of declaration is not handled properly by swagger springfox, resulting in having an object like this:

```
"ResponseEntity": {
"type": "object",
"properties": {
"body": {
"type": "object"
},
"statusCode": {
"type": "string",
"enum": [
"100",
"101",
...
"statusCodeValue": {
"type": "integer",
"format": "int32"
}
```

In the _definitions_ of the generated swagger json file.

##### **Suggest a Fix**

Since  #6404 fixed the issue of having controllers handling both errors and responses. We could change the methods into something like this.

`public ResponseEntity<JWTToken> authorize(@Valid @RequestBody LoginVM loginVM, HttpServletResponse response)`
and
`public ResponseEntity<User> createUser(@Valid @RequestBody ManagedUserVM managedUserVM) throws URISyntaxException`

This would result in a cleaner swagger json.

##### **JHipster Version(s)**

4.10.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by encos** [comment]
Take a look at the commit, I could fire the pull request if it's fine for you.

**Comment by cbornet** [comment]
Yes please do the PR. I made some comments on your commit.

**Comment by encos** [comment]
Ok I Removed the try catch in the UserJWTController as you suggested. I forked again to have a single commit.
