### ISSUE TITLE
Correct UserResourceIntTest with OIDC support

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6563]
This ticket is for the merged PR https://github.com/jhipster/generator-jhipster/pull/6553 that introduced several issues.

This is only for the `AccountResourceIntTest` when running with the new OIDC support:

- [x] For monoliths, this should not restart a new Spring context, but re-use the existing one because of the `@MockBean` annotation
- [x] This is a different bean, but `OAuth2TokenMockUtil` also has the same problem, and should also be corrected
- [x] For microservices, this code does not compile
- [x] For gateways, this also does not compile

For the last 2 points: it should be refactored to look like `AccountResource`, where this is basically 2 classes in a row, as it's just too complex.

**Comment by jdubois** [comment]
For the monolith, the Spring context is restarted because of the `@MockBean` annotation. There is also a formatting issue just after `restUserMockMvc.perform(get("/api/account")`

**Comment by jdubois** [comment]
I'm adding a todo item on `OAuth2TokenMockUtil` as it has the same issue

**Comment by mraible** [comment]
@jdubois Please let me know if I can help with this.

**Comment by jdubois** [comment]
Thanks @mraible I should be able to do it, no worries. I'll keep you updated!

**Comment by jdubois** [comment]
Checking the `OAuth2TokenMockUtil` item without doing anything, as it doesn't cause the issue (I just tested). Very strange!

**Comment by jdubois** [comment]
I refactored everything at https://github.com/jhipster/generator-jhipster/commit/b21002e6d653e1f2b48b811ac6e1b6f802e196ce -> I will merge & close the issue if Travis works

**Comment by mraible** [comment]
LGTM! Ship it!

**Comment by jdubois** [comment]
Closing as #6571 is merged
