### ISSUE TITLE
Angular Routing Strategy forRoot vs forChild

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#6565]
##### **Overview of the issue**

Currently Angular modules use `RouterModule.forRoot` to install the routes. According to Angular doc `https://angular.io/guide/router` feature module should use `Router.forChild` and `forRoot` should be using in the top level `AppRoutingModule` to define global behavior (such as default route or page not found).

##### **Motivation for or Use Case**

When customizing the generated front app this current strategy could be confusing because every module act as a an application module.

##### **Suggest a Fix**

Replace modules `RouterModule.forRoot` by `RouterModule.forChild` and define a top level `AppRoutingModule`.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by danielpetisme** [comment]
@deepu105 Do you mind to have a look on this issue, juste to know if it worths a discussion or we close it, please?
I tried to look into the existing issues but since I'm not an Angular Expert I'm not sure if the point is already covered somewhere else.

Thank you

**Comment by deepu105** [comment]
@danielpetisme This could be an improvement if somebody can contribute it as PR else we can add it to #5833 and close this

**Comment by gmarziou** [comment]
@dancancro I remember you also reported it on gitter, have you some comments?

**Comment by dancancro** [comment]
@gmarziou That's right. I think I just changed every forRoot to a forChild in my own app like [this](https://github.com/dancancro/great-big-example-application/blob/meals_patches/src/main/webapp/app/entities/contact/contact.module.ts#L26) but didn't do a PR for the generator. How I do it in my feature modules is [a little different](https://github.com/dancancro/great-big-example-application/blob/meals_patches/src/main/webapp/app/features/contacts/contacts.routing.ts) from how the jhipster generated modules under `/entities` work. 

I think the `AppRoutingModule` is called [`LayoutRoutingModule`](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/layouts/_layout-routing.module.ts) in a jhipster app. I call it [`AppRouting`](https://github.com/dancancro/great-big-example-application/blob/meals_patches/src/main/webapp/app/app.routing.ts) in mine.

**Comment by danielpetisme** [comment]
Close #6605

**Comment by deepu105** [comment]
PR merged
