### ISSUE TITLE
Simplify the installation procedure

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6568]
Our current installation procedure has some historical settings, and I'm wondering if we could simplify them:

- [ ] We check if the "git://" URLs are accessible (see [here](https://github.com/jhipster/generator-jhipster/blob/v4.10.0/generators/generator-base-private.js#L610)), because this will cause issues with Bower. As Bower is only used for AngularJS 1, this makes many errors for people using Angular 4, for no reasons. I would just check if an "http" URL is available to check for network connectivity.
- [ ] On our [installation page](http://www.jhipster.tech/installation/) we tell that Git is a requirement -> this is the same issue as one above, this is only a requirement for AngularJS 1. And I guess most people already have Git. So that's one setup instruction that is not very useful.
- [ ] On our [installation page](http://www.jhipster.tech/installation/) we tell to install Yeoman. I don't think this is needed anymore, now that we have the JHipster CLI. Has anyone tried to install JHipster without having Yeoman in the first place?

I propose that we discuss those points here, and I will check them when we have a decision (and I will add the decision here also)

**Comment by deepu105** [comment]
I guess Git is still needed due to upgrade sub gen and our new Git init
step.
As for Yeoman JHipster works without it but if the users use other JHipster
modules they would need yeoman installed


Thanks & Regards,
Deepu

**Comment by cbornet** [comment]
Then it should be the upgrade gen which checks git (I think it already does) and the initial commit shall just be ignored if git is not detected

**Comment by jdubois** [comment]
Yes the new Git init step only runs if Git is installed. And for the upgrade sub-generator it could just be a specific documentation for it, no need to force Git to everyone.

**Comment by jdubois** [comment]
For Yeoman yes you need it for modules, maybe we could also document this specifically.
