### ISSUE TITLE
Study (again) Java hot reload agents

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6573]
At the beginning of JHipster, one of the core feature was providing hot reload of Java classes, see our old repo: https://github.com/jhipster/jhipster-loaded

The current status on JHipster is that:

- I have already spent a lot of time on this, and I know the problem quite well
- We currently use Spring Boot devtools, which in my opinion killed the game a few years ago: it's a bit slow, but works well as it's a simple trick which restarts a classloader
- We also use it to refresh the database state using Liquibase, which is nice

Now, there are 2 issues:

- There are some people (including @mraible ) who tell me Spring Boot devtools doesn't work very well for them
- It's quite slow, so that's not really "hot reload" for me. More like "warm reload" :-)

There is an old project, which I studied at the time, called DCEVM, that is getting a new life. I hear people are starting to use this successfully, and the repositories look quite popular. So there are actually 2 solutions:

- https://github.com/dcevm/dcevm which is a fork of the original DCEVM
- https://github.com/HotswapProjects/HotswapAgent which is new to me, and looks also based on DCEVM -> from what I read it looks a bit more advanced

So I would like to have a study on both tools, in particular HotswapAgent, to see if this could improve our current dev workflow. Who would be interested for this?

**Comment by jdubois** [comment]
I'm closing this as we have too many opened tickets at the moment. We need to freeze new features for some time.
If anyone is interested please comment here.

**Comment by Tcharl** [comment]
The only way we could have hot reload is to use osgi ;-)

**Comment by jdubois** [comment]
I can confirm Spring Loaded is dead... Currently we only work with the Spring Boot devtools: it's very basic but it does the job quite well, and there's no risk to have much bugs with it (it just reloads everything). That looks "good enough" for me, even if I'd like something better, of course.
