### ISSUE TITLE
Having a method that checks all the entity attributes for nullity

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6574]
##### **Overview of the issue**

Depending on how your API is called, the data is more or less valid. When we receive a graph of entities, we tend to check if the relations are null, as well as all the attributes of the entity. This validation could be generated inside the Entity itself.

##### **Motivation for or Use Case**

Let's say you have a `Contract` with one `Address`:

```
@Entity
public class Contract implements Serializable {

    @OneToOne
    private Address address;
}

@Entity
public class Address implements Serializable {

    private String street;
    private String street2;
}

```

We expose the API to create a `Contract`, and some times the `Address` object is null, but sometimes its not *but all its values are null*. So what we do, is that we add a `isNull` method (`isEmpty` is also a good name) in the entity (we don't use reflexion, a Stream is fine):

```
@Entity
public class Address implements Serializable {

    private Long id;
    private String street;
    private String street2;

    public boolean isNull() {
        return Stream.of(getId(), getStreet(), getStreet2()).allMatch(Objects::isNull);
    }
}
```

This way we can safely save a contract with non-null non-empty address like this:

```
@Service
@Transactional
public class  ContractService {

    public Contract save(Contract contract) {
        log.debug("Request to save Contract : {}", contract);

        // Saving address
        if (contract.getAddress() != null && contract.getAddress().isNull()) {
            contract.setAddress(null);
        } else {
            addressRepository.save(contract.getAddress());
        }

        // Saving Contract
        return contractRepository.save(contract);
    }
```

We actually endup having this kind of code in a few entities, so I was wondering if it was a pattern that could be interested to generate in JHipster ?

**Comment by gzsombor** [comment]
You should add @NotNull annotations to your domain entities, no need to duplicate this functionality with custom code. Or you should use DTOs, which is a much safer choice.

**Comment by agoncal** [comment]
@gzsombor There are plenty of different solutions but we find this one easy and not too intrusive (these pieces of our code are generated from Swagger and we don't want to change it). We just wonder if this could help other use cases (where you can't always change the code of your entities)

**Comment by gzsombor** [comment]
If you can create a contract with no address, then why do you want to create an address entity ?

I tend to favor DTOs, to separate the entity life-time level constraints, and the actual request level constraints. If I need something more tricky, it is relatively easy to add new constraint validator with an annotation, or just write a _validate()_ method on the entity, and call it before save.
 For me, this entity level isNull method seems a bit too domain specific - for your case.

**Comment by agoncal** [comment]
@gzsombor yes, we can create a contract with no address... and sometimes, our APIs receive non-null addresses, but totally empty. It's a pattern that we need for some of our APIs. I was just wondering if this pattern could be of an interest for others. If JHipster could generate it (a bit like the builder pattern in the entities that I like), good, if you think it's not appropriate to have it in all entities, fine, let's close this issue.
