### ISSUE TITLE
Pagination looks weird (getting out of screen)

### ISSUE THREAD

**Issue by Akuka** [jhipster/generator-jhipster#6577]
##### **Overview of the issue**

When using pagination as pagination ("pagination":"pagination") with entity with a lot pages (more than 50, depends on your screen size), the pagination section getting out of the screen (Attached screenshot)

![screen shot 2017-10-22 at 11 35 20](https://user-images.githubusercontent.com/3299903/31860044-2f652e3e-b71d-11e7-8f77-939ee420e03e.png)

##### **Reproduce the error**

1. create an application with "pagination" for at least one entity (bootstrap pagination).
2. generate enough simple test-data so that you can test pagination, more pages than your screen width.
3. in a browser, open the the entity list
4. You will not be able to see the first or the last page, and the pagination section getting out of the screen width.

##### **Related issues**

Until the last version (or some versions before) the pagination section was in collapse style. now its in expand style, I cannot find the PR, but it can be related.

##### **JHipster Version(s)**

4.10.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.company.customer"
    },
    "jhipsterVersion": "4.10.0",
    "baseName": "customer",
    "packageName": "com.company.customer",
    "packageFolder": "com/company/customer",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Myentity (myentity) {
  label String
}

paginate Myentity with pagination
service Myentity with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.13.5 (Apple Git-94)

node: v6.11.4

npm: 5.4.2

yeoman: 2.0.0

yarn: 1.2.1

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Mac OS X, Chrome.

- [V] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This might be because we updated ng-bootstrap
