### ISSUE TITLE
When microservcies OAuth2 security filter should be applied before Actuator's filter

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#6586]
##### **Overview of the issue**

In a microservice architecture, when OAuth2 is used Actuator security filter is invoked before oauth2. In consequence, the security rules defined in JHipster are not applied.

##### **Motivation for or Use Case**

This issue prevents to collect service metrics into the Jhipster-registry. See https://github.com/jhipster/jhipster-registry/issues/193

##### **Reproduce the error**

* Run a registry
* Generate a service
* Go to the metrics page and try to visualize the service metrics

##### **Related issues**

https://github.com/jhipster/jhipster-registry/issues/193

##### **Suggest a Fix**

As explained in the followin SO post and in the Spring Boot 1.5 release note, since this version oauth2 filter is applied after actuator's filter. The solution is ro restore the default value.
https://stackoverflow.com/questions/43526821/setting-spring-boot-actuator-with-oauth2-in-the-authorisation-server
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#oauth-2-resource-filter

It's already done for `uaa` simply update the condition.
https://github.com/jhipster/generator-jhipster/blob/4f62e49476dd9a0dad6d6751086803c7fc65afed/generators/server/templates/src/main/resources/config/_application.yml#L186
https://github.com/jhipster/generator-jhipster/blob/4f62e49476dd9a0dad6d6751086803c7fc65afed/generators/server/templates/src/test/resources/config/_application.yml#L151
##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm doing this

**Comment by mraible** [comment]
Sorry guys, I remember removing that property when integrating OIDC. It didn't seem necessary at the time.
