### ISSUE TITLE
jhipster pages generator Glyphicons error

### ISSUE THREAD

**Issue by KevinArdon** [jhipster/generator-jhipster#6588]
##### **Overview of the issue**

ERROR! Copying template client/angular/src/main/webapp/app/pages/_page-set.service.ts failed. [Error: ENOENT: no such file or directory, open '/home/yopo/Escritorio/log/node_modules/generator-jhipster-pages/generators/app/templates/client/angular/src/main/webapp/app/pages/_page-set.service.ts']

##### **Motivation for or Use Case**
When initializing the page generator to create a blank page, the following questions are answered without problem: Create page in the following pages set: Create a new pages set
? Create page set with the following name: test
? Which king of page you want to add? Client Only
? Enter the page name: test

However, when answering "? Enter the page glyphicon name" for example with "glyphicon glyphicon-eur" and hitting enter, the error happens right after that. I tried looking for _page-set.service.ts following the route described but it's nowhere to be found, when getting to the end of the route I can only find _page.module.ts., then I tried creating the page just to see what happens but it keeps asking for more files like _page-set.route.ts, etc and getting nowhere (naturally, those files where deleted after that).

##### **Reproduce the error**
Enter "yo jhipster-pages" 
Answer questions (it has examples on another try): 
 Create page in the following pages set: Create a new pages set
? Create page set with the following name: Test
? Which king of page you want to add? Client Only
? Enter the page name: Test
? Enter the page glyphicon name (see https://getbootstrap.com/components/): pages glyphicons-87-display.png
Error jhipster-pages 

##### **Related issues**

Found none

##### **JHipster Version(s)**
4.10.0

##### **JHipster configuration**

Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/home/yopo
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.11.0
node: v6.11.4
npm: 5.5.1
bower: 1.8.2
gulp:
[11:52:36] CLI version 1.4.0
yeoman: 2.0.0
yarn: 1.2.1

##### **Browsers and Operating System**

Ubuntu 17.04

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry but I have no idea what "jhipster pages" is - is that a module you installed?

**Comment by KevinArdon** [comment]
generator-jhipster-pages -> https://www.npmjs.com/package/generator-jhipster-pages

**Comment by jdubois** [comment]
OK, so that's a module made by someone outside of the JHipster team (which is very good, we can't do everything!), and so you should use the project's bug tracker at https://github.com/Magillem/generator-jhipster-pages/issues
