### ISSUE TITLE
[Documentation] Add OIDC documentation for the gateway

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6589]
The gateway documentation at http://www.jhipster.tech/api-gateway/ is not complete:

- [x] JHipster UAA is not in BETA anymore
- [x] There is no documentation on OIDC!!!

**Comment by jdubois** [comment]
@mraible @danielpetisme I'm sorry I have to prepare Devoxx and I have no time for this, but this is really important - does one of you have time for this?

**Comment by mraible** [comment]
@danielpetisme Can you help with this? I haven't played with OIDC-based microservices yet, I hope make time next week. If you don't have time, I can take a stab at it.

**Comment by danielpetisme** [comment]
Actually most of the `UAA` documentation is valid for OIDC. The only change is the use of Keycloak as IdP rather than the generated app.

Should I complete `uaa` doc or reuse it in a new page? I try to work on it in the coming week.

**Comment by jdubois** [comment]
@danielpetisme I would like to have http://www.jhipster.tech/api-gateway/#security up-to-date: this should be a specific section in order not to confuse people (even if there is some copy/pasting stuff from UAA). Then, this probably requires a specific page, like http://www.jhipster.tech/using-uaa/ and of course that's good!
Keep me updated - if you don't have time to do it or to finish, I'll also work on it, as it's very important.

**Comment by danielpetisme** [comment]
@jdubois sorry bu nothing new on my side, November is a nightmare for me. Don't count on me before December to update the documentation :/

Sorry

**Comment by jdubois** [comment]
No problem! It's Open Source it's ready when it's done :-)
