### ISSUE TITLE
paginated navigation entity - the edit popup lost the url param

### ISSUE THREAD

**Issue by ndywicki** [jhipster/generator-jhipster#6592]
##### **Overview of the issue**

Bug when edit an entity popup cancel changed the url navigation of pagination

##### **Reproduce the error**

1) Create an entity with one attribut and enable pagination
ex. jhipster car

2) Inject data > item per page = 20
3) Go to entity list on page 2, browser url show :
http://localhost:9000/#/car?page=2&size=20&sort=id,asc
4) View an entity #21:
http://localhost:9000/#/car/21
5) Click on back buton and return to http://localhost:9000/#/car?page=2&size=20&sort=id,asc
6) Edit an entity in page 2, the url change for: http://localhost:9000/#/car(popup:car/21/edit)

7) Click on cancel button in the popup url changed to http://localhost:9000/#/car => navigation params lost

##### **Related issues**

Maybe link with
https://github.com/jhipster/generator-jhipster/pull/5103
or https://github.com/jhipster/generator-jhipster/pull/4962

##### **Suggest a Fix**

N/A

##### **JHipster Version(s)**

tested on v4.8.0 and v4.10.0

##### **JHipster configuration**

Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
navissue@0.0.0 C:\workspace\jhipster\navissue
+-- generator-jhipster@4.10.0
`-- UNMET PEER DEPENDENCY popper.js@^1.11.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.10.0",
    "baseName": "navissue",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Car (car) {
  name String
}

paginate Car with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.9.3.windows.1

node: v6.10.2

npm: 3.10.10

gulp:
[11:14:29] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.24.4

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac219

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Car.json:
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20171025085526",
    "dto": "no",
    "service": "no",
    "entityTableName": "car",
    "jpaMetamodelFiltering": false,
    "pagination": "pagination"
}

##### **Browsers and Operating System**

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm doing this :-)

**Comment by ndywicki** [comment]
Great :) 
Thanks you @jdubois

**Comment by jdubois** [comment]
Oh that was really fun to do :-)

**Comment by ndywicki** [comment]
Sure Angular routing is fun ;-)
