### ISSUE TITLE
Website not showing latest changes after enabling PWA

### ISSUE THREAD

**Issue by rakeshkalra1983** [jhipster/generator-jhipster#6594]
##### **Overview of the issue**

If you do any change to your to your web-site and re-release it after enabling Service Worker: site doesn't come up. To fix this I have to clear the local cache data, and then it starts working.

Since I am naive on UI side, my guess is that we are saying in manifest.mf to cache index.html, and index.html have enteries for all css and java-scripts with some random number in its name. And since this random-numbers change with every release, hence site stops responding.

I will really appreciate your help.

##### **Motivation for or Use Case**

To enable PWA for my site, as it makes my site very fast and can be used like app on android.

##### **Reproduce the error**

To reproduce this error perform:
* Enable service worker in your app and release to production
* Everything will work fine, infact reload of site will happen very fast
* Now change anything in index.html or any css and release your site again to production.
* On visiting your website page, you will see blank screen.
To take care of this, you have clear your browser history and cached files.

##### **Related issues**

This issue is discussed here (last few comments): https://github.com/jhipster/generator-jhipster/pull/5880

##### **JHipster Version(s)**

4.7.0

##### **JHipster configuration**

~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "4.7.0",
    "baseName": "testapp",
    "packageName": "com.testapp",
    "packageFolder": "com/testapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
~~~

##### **Browsers and Operating System**

MacOS, Chrome Browser

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
ping @sendilkumarn

**Comment by dishaverma1987** [comment]
@sendilkumarn I am facing same issue as mentioned above, any help is really appreciated.

**Comment by geetanjalip24** [comment]
Did you guys get the solution of this problem?

**Comment by sendilkumarn** [comment]
Sorry guys, I was really having a hard time. I have added #6716 to address this. Hopefully that will solve the issue. 

But how are we gonna handle authentication when offline @jhipster/developers ?

**Comment by deepu105** [comment]
in JWT mode what happens if you are offline currently?
