### ISSUE TITLE
Clean up login/logout files when OIDC is selected

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6599]
`app/shared/login/login.service.ts` is not used when OIDC is selected, it shouldn't be generated with this option.

It is used in a few classes, those references should also be removed.

**Comment by mraible** [comment]
This service is used when doing a monolith with OIDC.

**Comment by jdubois** [comment]
Sorry you are correct... At least there is the `login` method in `app/shared/auth/auth-session.service.ts` that isn't used - so there is stuff to clean up there. I'm updating the title.
