### ISSUE TITLE
Bring back the "fast" profile

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6601]
Some time ago we had a "fast" profile, which was removing some non-essential Spring beans in order to boot faster.

I just did a test with the simplest possible microservice (no database, no registry, etc...) and startup time is nearly 8 seconds! That's incredibly slow for something so simple.

Doing a simple `fast` profile I could bring down that startup time to 5.5 seconds, and I'm pretty sure we could do better.

So how about bringing back the "fast" profile?

**Comment by pascalgrimaud** [comment]
+1

**Comment by PierreBesson** [comment]
And maybe we could remove the cc (continious compilation) profile. I'm not sure anyone is using it.

**Comment by cbornet** [comment]
@PierreBesson I'm using it !

**Comment by lukasw44** [comment]
👍

**Comment by jdubois** [comment]
I see many of you want this, but for the moment I'm giving up...

Here are the reasons:

- This complexifies the code, as you have the `fast` profile everywhere.
- I can win a bit more than 2 seconds at start-up, which isn't that much. Besides, we have hot-reload, so that's even less interesting.
- It's a bit complex to use, as there are less features.

Here is a patch of what I did on a "simple" application. It's pretty easy to use it and test.
[patch.txt](https://github.com/jhipster/generator-jhipster/files/1455315/patch.txt)
