### ISSUE TITLE
Liquibase changelog generation via gradle doesn't work

### ISSUE THREAD

**Issue by Loktor** [jhipster/generator-jhipster#6602]
##### **Overview of the issue**

The generated liquibase.gradle file of jhipster currently has a bug. The gradle command: liquibaseDiffChangeLog doesn't work at the moment due to a gradle script error.

##### **Motivation for or Use Case**

Generating liquibase change sets, doesn't work currently

##### **Reproduce the error**

Just run liquibaseDiffChangeLog for a project that is configured via gradle

##### **Suggest a Fix**

The problem relies withing liquibase.gradle:

The line 

`args liquibaseCommand` inside `def liquibaseCommand(command)`

should actually be 

`args command`

since liquibaseCommand is not the parameter name

##### **JHipster Version(s)**

Master and 4.10.1

**Comment by atomfrede** [comment]
@Loktor Thx for the report. Can you do a PR, as you have a solution ready?

**Comment by Loktor** [comment]
Sure :) PR is already open for you guys to review/merge
