### ISSUE TITLE
JHipster registry does not start with native cloud config profile in generated jhipster-registry.yml docker compose file

### ISSUE THREAD

**Issue by vberetti** [jhipster/generator-jhipster#6612]
##### **Overview of the issue**

- Generate a jhipster microservice gateway with jhipster registry and eureka
- in src/main/docker/jhipster-registry.yml, change SPRING_PROFILES_ACTIVE from "dev" to "dev,native" in order to use native mode cloud config.
- docker-compose run -f jhipster-registry.yml will fail because "jhipster.registry.password" property is missing

##### **Motivation for or Use Case**

Can not use the native mode of cloud config server just by adding ",native" to the spring active profiles.

##### **Suggest a Fix**

This is due to the generated local file "src/main/docker/central-server-config/localhost-config/application.yml" that has the following definition :

eureka.client.service-url.defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/

Docker compose for jhipster registry should contain a JHIPSTER_REGISTRY_PASSWORD environment variable.

PR : #6613

##### **JHipster Version(s)**

4.10.2

**Comment by pascalgrimaud** [comment]
Closing this, as the PR is merged
