### ISSUE TITLE
Quick question: runtime profile switches?

### ISSUE THREAD

**Issue by erikkemperman** [jhipster/generator-jhipster#6624]
Quick question: does anyone actually ever use the `swagger` and `no-liquibase` profiles to change the behaviour of an already packaged WAR?

I'm looking into making my (production) WAR file somewhat smaller, and would be able to make significant cuts if I were allowed to exclude liquibase and swagger from it. In other words, I would like these profiles to not just be runtime switches, but actually strip some dependencies from the package.

It's pretty straightforward to do this for my generated app, of course, but it'll cause some pain every time I update JH. So I was wondering if it might make sense to do it out of the box?

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
The purpose of those was to be runtime switches exactly so that you don't have to rebuild the artifact to do that. I say both approaches might be useful to someone. Personally, I prefer the runtime switches so that I can move the same artifact to different environments and decide if liquibase/swagger needs to run or not. Also note that in many companies the process would be to build an artifact test it in UAT/staging and move the same artifact to prod and in prod I could disable swagger and liquibase if required while not in UAT

**Comment by erikkemperman** [comment]
@deepu105 Thanks for the quick response! Yeah, I understand the purpose of these switches, just wasn't sure if they were actually being used. Appararently, then, yes :-)

Could it work in both ways, somehow? So, for example if I package with the `no-liquibase` profile active then those dependencies are stripped and I can no longer choose at runtime. But if I don't, the dependencies will be in the WAR and I can still choose at runtime.

**Comment by deepu105** [comment]
Probably but then the behaviour might be confusing to some people

**Comment by erikkemperman** [comment]
Probably true, sure. Unless perhaps the name were different, like `strip-liquibase` -- and of course a line added to the docs saying that if you build with `strip-xxx` than the runtime switch won't have any effect.

That might still be too complicated, I guess. If so, I'm likely just going to keep doing this in my own app (and be slightly inconvenienced when upgrading JH).

BTW I have found some dependencies that are actually not being used, or not in all configurations, and might submit a PR to address that. That should shave a couple of MB off the archive, for common configurations, at no cost.

**Comment by mraible** [comment]
If you're looking to reduce the size of your WARs, you could use https://github.com/dsyer/spring-boot-thin-launcher. This makes WARs very small, and downloads dependencies when your app starts.

**Comment by erikkemperman** [comment]
@mraible Thanks, that looks good!

However, it appears to end up looking at the pom and so if that casts too wide a net it will still fetch unneeded artifacts.

Also, in some cases (but not mine) I imagine downloading stuff straight to a production server runs afoul of security policies.

I will probably try to do both, then: limit the jhipster pom to strip some unused dependencies and use this wrapper to make the WAR small.

**Comment by erikkemperman** [comment]
Thanks guys, I'll close this now.
