### ISSUE TITLE
Add PageSpeed optimizations for Angular

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#6626]
##### **Overview of the issue**

When I developed 21-Points with AngularJS, we were never able to get a great PageSpeed score. See [this ticket](https://github.com/mraible/21-points/issues/10) for more information, but we basically never got it above a 71.

Today, I implemented forced HTTPS on Heroku using [this technique](https://stackoverflow.com/a/47038681/65681). 

It works in that the app now gets 99/100:

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.21-points.com%2F&tab=mobile

However, you can see in the screenshots that there's no page rendered. I think it's worth investigating server-side rendering to fix this. 

I think this project will work for this: https://github.com/swaechter/angularj-universal

##### **Motivation for or Use Case**

Better performance.

**Comment by jdubois** [comment]
Yes you need HTTPS to have 99/100 (and maybe HTTP/2? At least I use them both and I get 100 on Lighthouse - Chrome Devtools / Audit). Main issue is that you need an SSL key, that you must generate, and I'm not sure we can automate this. For me that should be documented (it is documented in the code, but not on our website), but not more.

I don't understand why your page isn't rendered: you shouldn't need Angular Universal for this, our application should be "understood" correctly by Google. At least that was working totally fine with AngularJS 1.x, as I did this for a client - hopefully this still works with Angular 4!

**Comment by gmarziou** [comment]
We could generate self signed certs or use letsencrypt.
[node-greenlock](https://github.com/Daplie/node-greenlock) uses letsencrypt but unfortunately it doesn't run on Windows, there's also a java client [acme4j](https://github.com/shred/acme4j).

**Comment by mraible** [comment]
FWIW, Heroku let's you easily configure HTTPS and handles all the certificate stuff (via Let's Encrypt) for you. However, you do need a "force HTTPS" filter like this one:

https://stackoverflow.com/questions/46956877/how-do-i-force-https-for-a-spring-boot-app-on-heroku/47038681#47038681

Cloud Foundry has a `FORCE_HTTPS` environment variable you can use.

I'm not sure why my page doesn't render on PageSpeed Insights.

**Comment by jdubois** [comment]
I have the same "99/100" with https://start.jhipster.tech/ - see https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fstart.jhipster.tech%2F&tab=desktop

- That's a great result, of course!
- For HTTPS, I added a detailed documentation at http://www.jhipster.tech/production/#security 
- For website rendering, I have the same issue - I have no idea if that's a bug on the Google side, or if they really can't render our website

**Comment by jdubois** [comment]
I'm closing this as this has been stalled for a long time: our default performance is very good, so no need to worry.
For website rendering that's another issue, but from my experience we have no problem in getting JHipster websites indexed by Google, so this looks like a bug on the Google side.
