### ISSUE TITLE
Fill local User "imageURL" with OIDC "picture" field

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#6646]
##### **Overview of the issue**

Currently, the OIDC doesn't fill the imageURL of the local User.

##### **Suggest a Fix**
Add in UserService::getUser `if databaseType !== cassandra`
```java
        if (details.get("picture") != null) {
            user.setImageURL((String) details.get("picture"));
        }
```

##### **JHipster Version(s)**

master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "travisOauth2",
    "packageName": "io.github.jhipster.travis",
    "packageFolder": "io/github/jhipster/travis",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "useSass": false,
    "buildTool": "maven",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "enableSocialSignIn": false,
    "testFrameworks": [
      "protractor"
    ],
    "serverPort": "8080",
    "jhiPrefix": "jhi",
    "travis": true,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "clientPackageManager": "yarn",
    "clientFramework": "angularX",
    "jhipsterVersion": "4.10.2"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v6.11.3

npm: 5.4.2

bower: 1.8.2

gulp:
[16:01:19] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.0.2

Docker version 17.07.0-ce, build 8784753

docker-compose version 1.16.1, build 6d1ac21

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by cbornet** [comment]
@mraible WDYT ?

**Comment by mraible** [comment]
Are you able to add a picture to Keycloak and see it after this change?

**Comment by cbornet** [comment]
I don't think Keycloack support adding picture to users. Maybe Okta ? Can you check ?

**Comment by mraible** [comment]
It looks like Okta uses `profileUrl`. Here's all the default properties:

```
login
firstName
lastName
middleName
honorificPrefix
honorificSuffix
email
title
displayName
nickName
profileUrl
secondEmail
mobilePhone
primaryPhone
streetAddress
city
state
zipCode
countryCode
postalAddress
preferredLanguage
locale
timezone
userType
employeeNumber
costCenter
organization
division
department
managerId
manager
```

**Comment by cbornet** [comment]
profile | string | URL of the End-User's profile page. The contents of this Web page SHOULD be about the End-User.
-- | -- | --
picture | string | URL of the End-User's profile picture. This URL MUST refer to an image file (for example, a PNG, JPEG, or GIF image file), rather than to a Web page containing an image. Note that this URL SHOULD specifically reference a profile photo of the End-User suitable for displaying when describing the End-User, rather than an arbitrary photo taken by the End-User.

So I think we cant' use profile. I'll implement with picture since it can't do any harm.

**Comment by gmarziou** [comment]
Keycloak supports custom user atributes
