### ISSUE TITLE
Jhipster blank page in home

### ISSUE THREAD

**Issue by adm220** [jhipster/generator-jhipster#6649]
##### **Overview of the issue**

I've created a new project using jhipster and jdl studio. Everything were ok until I push the generated code to Bitbucket and clone in another PC.  The application has been started successfully but, when I try to access the home page, a blank page appear. Just the jhipster log is showed in tab.

##### **Reproduce the error**

the project is hosted in https://bitbucket.org/diogo_martinez/vilar_formoso/
execute ./mvnw

##### **JHipster Version(s)**

I cant remember exactly version I used, but it has 2 weeks, so it were a newer version

##### **JHipster configuration**

Using JHipster version installed globally
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
vilar-formoso@0.0.0 /home/diogo/dev/repository/vilar_formoso
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "br.com.vilarformoso",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "4.10.0",
    "baseName": "VilarFormoso",
    "packageName": "br.com.vilarformoso",
    "packageFolder": "br/com/vilarformoso",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Cliente (cliente) {
  nome String required,
  telefone String required,
  endereco String required,
  email String,
  aniversario LocalDate
}
entity Pedido (pedido) {
  enderecoEntrega String required,
  meioPagamento MeioPagamento required,
  prato String required,
  guarnicao String,
  bebida String,
  sobremesa String,
  valor BigDecimal required,
  troco BigDecimal,
  observacao String,
  horaEntrega ZonedDateTime required
}
entity Produto (produto) {
  descricao String required,
  valorUnitario BigDecimal required
}

enum MeioPagamento {
  DEBITO,
  CREDITO,
  DINHEIRO,
  VALE_REFEICAO
}

relationship OneToMany {
  Cliente{pedido} to Pedido{cliente(nome)}
}
relationship ManyToMany {
  Pedido{produto(descricao)} to Produto{pedido}
}

paginate Cliente, Pedido, Produto with infinite-scroll
search Cliente, Pedido, Produto with elasticsearch

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.14.1

node: v8.9.0

npm: 5.5.1

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

##### **Browsers and Operating System**

Ubuntu 17.10
Firefox 56.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
You can read the README file. All instructions are there.

After cloning your project:
- `npm install`
- `./mvnw` : to start the back
- `npm start` : to start the front

**Comment by adm220** [comment]
I'm so sorry, I did not payed attention for this in README file. thank you. I just did it and worked well.

**Comment by adm220** [comment]
My fault, after running npm install doesnt work, I've started a recently created project, thats why I thought worked.
I tryed using yarn, in a new repository, and the same issue happens. I asked a friend to try run the application clonning the repository, and the same problem occurs.

**Comment by adm220** [comment]
Worked for me runnnig in 2 separated terminals the ./mvnw and yarn start.  Is that the unique way to run in dev after git clone?

**Comment by deepu105** [comment]
Please read the Readme or our docs its clearly explained there
