### ISSUE TITLE
[Feature request ] Handle JTA transactions

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#6651]
##### **Overview of the issue**

As of today, JHipster rely on spring tx to be transactional. However, spring-tx is only transaction-local and not JTA, so not allowing distributed tx, or handling multiple Entity managers.

##### **Motivation for or Use Case**

One more JHipster cool feature :-)

##### **Reproduce the error**

Declare 2 em and try to execute a transaction across both, or use a JMS/XA broker (to PR too ;-)) and try to do the same.

##### **Related issues**

I searched, but didn't find any

##### **Suggest a Fix**

I could do a PR with an option asking to use either Local tx, JBoss Narayana, Atomikos, Bitronix or JOTM.
In a first time, I think that JBN is fairly simple (as it has a spring-boot module), and I can handle Atomikos (as I already used it in the past).

##### **JHipster Version(s)**

4.10.2

##### **JHipster configuration**

Unrelated

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Unrelated

##### **Browsers and Operating System**
Unrelated

- [X ] Checking this box is mandatory (this is just to show you read everything)

What do you think about this feature?

**Comment by pascalgrimaud** [comment]
Sure, it's a cool feature but currently, we have too much features and it's really hard to add all of them. 

That's why the module system was created, everyone can support a specific feature, and if it's really popular, it would be easy to integrate it to the main generator-jhipster.

**Comment by Tcharl** [comment]
NP, will help on current issues then ;-)

**Comment by pascalgrimaud** [comment]
If you have the time, don't hesitate to try to do it as a module

**Comment by jdubois** [comment]
- It supports JTA when inside an app server, but not XA with an external transaction manager
- XA is a bad solution in most cases: it is slow, can still have errors, and is very proprietary. There are many easiest and better solutions.

For example, if I take your use case of 2 databases: with Oracle just import the other tables using a database link.

Or if you use a DB and a JMS server, which is more common: by default Spring will first commit the database (so the DB is always correct) and then try to commit the JMS message: that means you only need to make sure your messages are indempotent (hint: there's a JMS header telling you a message has already been sent).

So this is not the kind of technical approach I would like to highlight with JHipster.
