### ISSUE TITLE
Incorrect rebuild instruction included in vendor.scss

### ISSUE THREAD

**Issue by peter-gergely-horvath** [jhipster/generator-jhipster#6665]
##### **Overview of the issue**

Not a big deal, but the file `src/main/webapp/content/scss/vendor.scss` contains incorrect instructions on how to rebuild the project with webpack. The instruction included is incorrect:
```
/* after changing this file run 'yarn run 'yarn run webpack:build' */
```

This should be 
```
/* after changing this file run 'yarn run webpack:build' */
```

##### **Motivation for or Use Case**

N/A

##### **Reproduce the error**
Generate a new web application using JHIpster command line with the following options accepted during the command line wizard:
monolithic type, SQL database, multilang support, SCSS enabled
 
##### **Related issues**

N/A

##### **Suggest a Fix**

The generated file should contains the correct command name

##### **JHipster Version(s)**

4.10.1

##### **JHipster configuration**

```
$ jhipster info
Using JHipster version installed globally
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**


/Users/XXXXXX
└── (empty)



cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>




</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (Zulu 8.21.0.1-macosx) (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (Zulu 8.21.0.1-macosx) (build 25.131-b11, mixed mode)

git version 2.13.5 (Apple Git-94)

node: v8.9.0

npm: 5.5.1

yarn: 1.2.1

Congratulations, JHipster execution is complete!
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Indeed, do you want to do a pull request to fix this @peter-gergely-horvath ?
