### ISSUE TITLE
Logstash stop working after a while

### ISSUE THREAD

**Issue by lmbai** [jhipster/generator-jhipster#6668]
##### **Overview of the issue**

The logstash stop working after a while.

##### **Reproduce the error**

start microsevice with the jhipster-console with logstash.
we can observe that logstashappender was been killed after a while.
1. the `LogstashSocketAppender` was added in to the `LoggerContext` from the `LoggingConfiguration.java`
2. after a while, the **Spring Boot** trigger a event will make the app reconfig. 
3. It call the `initializeWithConventions` in the `AbstractLoggingSystem.java`
4. then it will call the `loadConfiguration` in the `LogbackLoggingSystem.java`
5 then it will `stopAndReset(loggerContext)`. here it will stop all the appenders, and it will **resetAllListeners();**, which will clear the `LogbackLoggerContextListener`. 
6. after that the `LogbackLoggerContextListener` is been cleared. and the `logstashappender ` will never work anymore. 
7. After that, the app will just load the config from the `logback-spring.xml`
```
	protected void loadConfiguration(LoggingInitializationContext initializationContext,
			String location, LogFile logFile) {
		super.loadConfiguration(initializationContext, location, logFile);
		LoggerContext loggerContext = getLoggerContext();
		stopAndReset(loggerContext);
		try {
			configureByResourceUrl(initializationContext, loggerContext,
					ResourceUtils.getURL(location));
```

i am not sure why the spring trigger a event will cause the whole app refresh again after the `logstashappeder` has been added into the `LoggerContext`. but it will stop the log appender and `LogbackLoggerContextListener`. 

##### **Related issues**

  #6402 
  [Logstash appender stops working after logback-spring.xml change](https://github.com/jhipster/generator-jhipster/issues/4031)
 [Not forwarding logs after a while](https://github.com/jhipster/jhipster-console/issues/41)

##### **Suggest a Fix**

currently i am not sure the cause of the app reconfig. but from the above observation. since it will use the `logback-spring.xml`. we can add the logstashappender into the 'logback-spring.xml'

#6402 

##### **JHipster Version(s)**

 "jhipsterVersion": "4.9.0",

##### **JHipster configuration**

```
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "xxxxxx",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "iris",
    "dockerRegistryURL": "xxxxxx",
    "dockerRegistryOrganizationName": "xxx",
    "packageName": "xxxx",
    "packageFolder": "xxxx",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "xxxxxx",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ],
    "clientPackageManager": "yarn"
  }
}
</pre>
</details>
```
 **Environment and Tools**
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.2.windows.3
node: v6.11.4
npm: 3.10.10
yeoman: 2.0.0
yarn: 1.2.1
Execution complete
```
##### **Browsers and Operating System**
Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)
# # #

**Comment by gmarziou** [comment]
Configuring the logstash appender in xml and abandoning the `LoggingConfiguration`. seems a good solution.

Another possibility I've found recently is that the logstash appender automatically converts the contents of the MDC to json fields, I haven't tested it but I guess it could be used to set custom fields app_name, app_port, instance_id, version. Though it would require setting up a filter or an interceptor to fill up the MDC, probably not ideal for performance but I've used it successfully to add some security fields like subject so maybe it would make sense to combine these 2 aspects in the future.

**Comment by lmbai** [comment]
@gmarziou , i did try the above solution "use the xml configration to replcae the  Logingconfiguration". it works.  

[logback-spring.txt](https://github.com/jhipster/generator-jhipster/files/1464344/logback-spring.txt)
(From  @dancewing)

Actually, it it a bit troublesome
1. we have to code some logic in the xml file.
1. in order to make the logic work, we have to import more dependecny "Janino library" to make the expression work.
1. we have to import the spring properties. because the logback doesn't understand the spring EL expression 

So, i digged this more:
First, since the springboot refresh will log the xml, can we implement a self-defined logback appender and config it in the xml, so that it will load every fresh.

Secondly, something i don't understand is that, the refresh process will reload all the configrations, we also put the `configuration` annnotation for the "the "LoggingConfiguration.java", so why it is not being reloaded?  
>while, Actually the beans in spring are singleton by defualt. in the process logic, spring try to reload the configrations. but the bean is already been created, so........ Actually there is a `@RefreshScope` will re-create the bean when there is cofig change.

**Comment by gmarziou** [comment]
Interesting.

As you said, coding logic in XML is not very pretty, especially when you need to duplicate it:

    <if condition='property("eureka_client_enabled").contains("true") &amp;&amp; !isNull("logstash_enabled")  &amp;&amp; property("logstash_enabled").contains("true")'>

I wonder if the condition above could be computed and added as a property with a specific name by a PropertiesPropertySource.

**Comment by lmbai** [comment]
@gmarziou 
Good news, the `@RefreshScope` works. i may need more time to observe it. but it seems like we don't need to change a lot. just add an annotation in the `LoggingConfiguration.java` will solve this issue.

**Comment by gmarziou** [comment]
Excellent, thanks.

**Comment by PierreBesson** [comment]
Closing this as https://github.com/jhipster/generator-jhipster/pull/6679 is merged.

**Comment by tchlyah** [comment]
It doesn't work for me. I still loose my logs everytime a configuration refresh happens!
Worse, `@Conditional` doesn't work with `@RefreshScop` : if I start the application without Consul, I have this message : 

`A component required a bean named 'scopedTarget.loggingConfiguration' that could not be found.`

@lmbai, do you confirm that it is still working for you?
