### ISSUE TITLE
[React] No login errors when invalid password

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#6669]
##### **Overview of the issue**

There's two issues related to trying to login with invalid credentials.

1. On the `jh-react` branch, when you try to login with username `foo` and password `bar`, there's a validation error in the console about the password being too short, but nothing is displayed to the user.

![screen shot 2017-11-09 at 10 38 45 am](https://user-images.githubusercontent.com/17892/32598637-8c8dae4e-c53a-11e7-98d9-5364f4801e3d.png)

2. When you login with invalid credentials, but a password that's long enough (e.g. `user/user123`), no message about failed login is displayed to the user. There is an error in the console, but not on the screen.

![screen shot 2017-11-09 at 10 38 55 am](https://user-images.githubusercontent.com/17892/32598687-ac647f68-c53a-11e7-8833-05da1ac250c8.png)

**Comment by pascalgrimaud** [comment]
As React is with experimental flag, maybe it should be included in https://github.com/jhipster/generator-jhipster/issues/6044 ?
So we can reduce the number of opened tickets
