### ISSUE TITLE
[React] Changing password doesn't work

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#6670]
After logging in, if you change your password, it doesn't work. I'm not sure if the password is updated or not as there's no feedback given to the user after they click "Save". However, I do know that it changes something because I'm unable to login with the new (or old) password after trying to update it.

![screen shot 2017-11-09 at 10 39 24 am](https://user-images.githubusercontent.com/17892/32598827-045b87de-c53b-11e7-9d07-84fe40a703d2.png)

**Comment by pascalgrimaud** [comment]
As React is with experimental flag, maybe it should be included in https://github.com/jhipster/generator-jhipster/issues/6044 ?
So we can reduce the number of opened tickets
