### ISSUE TITLE
Error in unit testing with hibernate

### ISSUE THREAD

**Issue by MathieuJ** [jhipster/generator-jhipster#6671]
##### **Overview of the issue**

the use of Hibernate in integration tests hides some potential bugs; you can see it with jhipster sample app and the bank account entity integration test: 
https://github.com/jhipster/jhipster-sample-app/blob/master/src/test/java/io/github/jhipster/sample/web/rest/BankAccountResourceIntTest.java

Code : 
```java
        // Update the bankAccount
        BankAccount updatedBankAccount = bankAccountRepository.findOne(bankAccount.getId());
        updatedBankAccount.setName(UPDATED_NAME);
        updatedBankAccount.setBalance(UPDATED_BALANCE);

        restBankAccountMockMvc.perform(put("/api/bank-accounts")
            .contentType(TestUtil.APPLICATION_JSON_UTF8)
            .content(TestUtil.convertObjectToJsonBytes(updatedBankAccount)))
            .andExpect(status().isOk());

        // Validate the BankAccount in the database
        List<BankAccount> bankAccountList = bankAccountRepository.findAll();
        assertThat(bankAccountList).hasSize(databaseSizeBeforeUpdate);
        BankAccount testBankAccount = bankAccountList.get(bankAccountList.size() - 1);
        assertThat(testBankAccount.getName()).isEqualTo(UPDATED_NAME);
        assertThat(testBankAccount.getBalance()).isEqualTo(UPDATED_BALANCE);
```

We take the bank account entity from database and update it, and transform it into a DTO. The test being transactional, the findAll has the updated values even if the webservice call restBankAccountMockMvc.perform(put("/api/bank-accounts") is commented.

If there is a problem in the resource, service or in the mapping DTO => entity, the test may return a false positive.

##### **Suggest a Fix**

The integration test should take a pure DTO and send it to the service.
It should not taken the same entity from DB that we update and we check after.

##### **JHipster Version(s)**

4.10.2

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.roger.client"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "roger",
    "packageName": "com.roger.client",
    "packageFolder": "com/roger/client",
   "serverPort": "8086",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "1406581a9ba8818640933960cdde47d2e08b117a",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "clientPackageManager": "yarn"
  }
}

##### **Browsers and Operating System**

Mac

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@MathieuJ would you like to do PR to fix it?
