### ISSUE TITLE
Uncaught Error: Can't resolve all parameters for JhiAlertService:

### ISSUE THREAD

**Issue by kookle** [jhipster/generator-jhipster#6684]
jhipster-sample-app-ng2 downloaded then upgrade angular 5.0,  anyone have an idea?

##### **Overview of the issue**
compiler.js?dd9e:466 Uncaught Error: Can't resolve all parameters for JhiAlertService: (?, ?, ?).
    at syntaxError (compiler.js?dd9e:466)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js?dd9e:15546)
    at CompileMetadataResolver._getTypeMetadata (compiler.js?dd9e:15381)
    at CompileMetadataResolver._getInjectableMetadata (compiler.js?dd9e:15361)
    at CompileMetadataResolver.getProviderMetadata (compiler.js?dd9e:15721)
    at eval (compiler.js?dd9e:15632)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (compiler.js?dd9e:15592)
    at eval (compiler.js?dd9e:15080)
    at Array.forEach (<anonymous>)
syntaxError @ compiler.js?dd9e:466
CompileMetadataResolver._getDependenciesMetadata @ compiler.js?dd9e:15546
CompileMetadataResolver._getTypeMetadata @ compiler.js?dd9e:15381
CompileMetadataResolver._getInjectableMetadata @ compiler.js?dd9e:15361
CompileMetadataResolver.getProviderMetadata @ compiler.js?dd9e:15721
(anonymous) @ compiler.js?dd9e:15632
CompileMetadataResolver._getProvidersMetadata @ compiler.js?dd9e:15592
(anonymous) @ compiler.js?dd9e:15080
CompileMetadataResolver.getNgModuleMetadata @ compiler.js?dd9e:15071
CompileMetadataResolver.getNgModuleSummary @ compiler.js?dd9e:14998
(anonymous) @ compiler.js?dd9e:15086
CompileMetadataResolver.getNgModuleMetadata @ compiler.js?dd9e:15071
CompileMetadataResolver.getNgModuleSummary @ compiler.js?dd9e:14998
(anonymous) @ compiler.js?dd9e:15086
CompileMetadataResolver.getNgModuleMetadata @ compiler.js?dd9e:15071
JitCompiler._loadModules @ compiler.js?dd9e:33486
JitCompiler._compileModuleAndComponents @ compiler.js?dd9e:33447
JitCompiler.compileModuleAsync @ compiler.js?dd9e:33363
CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js?e0f5:230
PlatformRef.bootstrapModule @ core.js?593e:5446
(anonymous) @ app.main.ts?3881:11
./src/main/webapp/app/app.main.ts @ main.bundle.js:571
__webpack_require__ @ manifest.bundle.js:713
fn @ manifest.bundle.js:118
2 @ main.bundle.js:1411
__webpack_require__ @ manifest.bundle.js:713
webpackJsonpCallback @ manifest.bundle.js:26
(anonymous) @ main.bundle.js:1

##### **JHipster Version(s)**
v0.3.0

##### **Browsers and Operating System**
Chrome and Mac OS High Sierra

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Migration to Angular 5 is not done yet, if you want to participate please contribute to #6632
