### ISSUE TITLE
Add EJS Lint

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#6687]
https://github.com/RyanZim/EJS-Lint would be very helpful for us so need to explore this

**Comment by PierreBesson** [comment]
I did a quick check of EJS-Lint and it does give you an error with invalid EJS code. The project readme says that the way it works is by removing all non ejs code and checking standard js syntax. It can ever output the line number of the problem.
This seems very valuable to me to prevent small mistakes. However it doesn't integrate into eslint. So we have to write some boilerplate to run it on all our template files, for this it could be useful to add an `.ejs` or `.template` extension to all our templates.
I think it would be interesting to develop an ejs-lint eslint plugin for this.

As a side note, I want to mention that I use VSCode to work on the generator and it provides coloring/auto-completion of EJS code !

**Comment by deepu105** [comment]
This will now be run as part of the lint phase. To run it separate use `yarn ejs-lint` command
