### ISSUE TITLE
<yarn.version> property in Maven build is in the wrong section

### ISSUE THREAD

**Issue by thomastardy** [jhipster/generator-jhipster#6692]
##### **Overview of the issue**

The property <yarn.version> in the generated pom.xml is in the section , but should be along side the property <node.version>

##### **Motivation for or Use Case**

Have similar properties close to each other and definitely not in the wrong section.

##### **Reproduce the error**

Generated a standard app. Can be seen in https://github.com/jhipster/jhipster-sample-app/blob/master/pom.xml as well.

##### **Suggest a Fix**

Move the line up right after <node.version>.
I will create a PR later on.

##### **JHipster Version(s)**

```
pexapark@0.0.0 /Users/tardy/Projects/pexapark/pexapark-mvp
└── generator-jhipster@4.10.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.pexapark.platform"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "pexapark",
    "packageName": "com.pexapark.platform",
    "packageFolder": "com/pexapark/platform",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.15.0

node: v8.9.1

npm: 5.5.1

bower: 1.8.2

gulp:
[10:11:37] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

MacOS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This is already migrated in the `master` branch - you're unlucky because this has been totally refactored to use https://github.com/jhipster/jhipster-dependencies in the next release, so that's a bit hard to understand (it will be documented before the release, but that's not done yet)
