### ISSUE TITLE
Testing JHipster with JDK 10 Early Access builds

### ISSUE THREAD

**Issue by robilad** [jhipster/generator-jhipster#6696]
##### **Overview of the issue**

JDK 10 Early Access builds are now available at http://jdk.java.net/10 . As part of the OpenJDK Quality Outreach, we're trying to evaluate how far along popular FOSS projects, such as JHipster, are regarding testing with the upcoming JDK (major or update) releases, to encourage their contributors to start testing if they haven't done so yet, and, most importantly, provide advice, feedback and assistance on filing and handling JDK-related issues, if they are discovered during testing,

##### **Motivation for or Use Case**

I'd love to see as many popular FOSS projects as possible be able to move with confidence from one major JDK release to the next, as that also enables those projects's developers and their users to benefit from performance and other enhancements in newer JDKs faster. Thats' what we're trying to achieve through the OpenJDK Quality Outreach effort at https://wiki.openjdk.java.net/display/quality/Quality+Outreach .

##### **Suggest a Fix**

Ideally, someone involved in JHipster development would volunteer to sign up as the JHipster contact for the Quality Outreach. They'd receive an anouncement e-mail every 2-3 weeks depending on contents of the builds, e.g. http://mail.openjdk.java.net/pipermail/quality-discuss/2017-November/000721.html . Those announcements try to highlight significant changes in the builds, allowing you to decide if you might want to test with a particular build. We don't expect you to test every build, it's entirely up to you. 

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@robilad thanks for reaching out. Our immediate goal is to support Java 9 see https://github.com/jhipster/generator-jhipster/issues/6391 so testing Java 10 would have to wait until that I guess. But once Java 9 is out of the way it should be possible. I can volunteer to be the contact for this unless @jdubois wants to that. cc @jhipster/developers

**Comment by jdubois** [comment]
I'd love to, but I just don't have the time... We have 40+ opened tickets, those are my priority.

**Comment by mraible** [comment]
I’d be happy to be the contact.

**Comment by deepu105** [comment]
I guess then @mraible is the best choice :)

**Comment by robilad** [comment]
Awesome - @mraible , do you mind if I send you an e-mail with the details?

**Comment by mraible** [comment]
Please do. I might be slow to respond this week though. It’s a short week and most people in the US don’t work Thursday and Friday.

**Comment by jdubois** [comment]
Hi guys, I'm closing this as this seems OK between @robilad and @mraible - otherwise please don't hesitate to re-open the issue!
