### ISSUE TITLE
Webpack bundling fails on CentOS 7

### ISSUE THREAD

**Issue by thomastardy** [jhipster/generator-jhipster#6697]
##### **Overview of the issue**

Webpack bundling fails on CentOS 7, but works fine on MacOS. I regenerated a fresh application based on the .yo-rc.json and could reproduce it.

```
[INFO] --- frontend-maven-plugin:1.6:yarn (webpack build prod) @ pexapark ---
[INFO] Running 'yarn run webpack:prod' in /tmp/jhipster-test
[INFO] yarn run v1.2.1
[INFO] $ yarn run cleanup && yarn run webpack:prod:main && yarn run clean-www
[ERROR] warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
[INFO] Starting compilation using the angular compiler.
[INFO] Angular compilation done, starting webpack bundling.
[ERROR] Error: Unexpected value 'LogsComponent in /tmp/jhipster-test/src/main/webapp/app/admin/index.ts' declared by the module 'PexaparkAdminModule in /tmp/jhipster-test/src/main/webapp/app/admin/admin.module.ts'. Please add a @Pipe/@Directive/@Component annotation.
[ERROR]     at Error (native)
[ERROR]     at syntaxError (/tmp/jhipster-test/node_modules/@angular/compiler/bundles/compiler.umd.js:1725:34)
[ERROR]     at /tmp/jhipster-test/node_modules/@angular/compiler/bundles/compiler.umd.js:15469:40
[ERROR]     at Array.forEach (native)
[ERROR]     at CompileMetadataResolver.getNgModuleMetadata (/tmp/jhipster-test/node_modules/@angular/compiler/bundles/compiler.umd.js:15451:54)
[ERROR]     at addNgModule (/tmp/jhipster-test/node_modules/@angular/compiler/bundles/compiler.umd.js:24245:58)
[ERROR]     at /tmp/jhipster-test/node_modules/@angular/compiler/bundles/compiler.umd.js:24256:14
[ERROR]     at Array.forEach (native)
[ERROR]     at _createNgModules (/tmp/jhipster-test/node_modules/@angular/compiler/bundles/compiler.umd.js:24255:26)
[ERROR]     at analyzeNgModules (/tmp/jhipster-test/node_modules/@angular/compiler/bundles/compiler.umd.js:24130:14)
[ERROR]     at analyzeAndValidateNgModules (/tmp/jhipster-test/node_modules/@angular/compiler/bundles/compiler.umd.js:24140:35)
[ERROR]     at AotCompiler.analyzeModulesAsync (/tmp/jhipster-test/node_modules/@angular/compiler/bundles/compiler.umd.js:23776:46)
[ERROR]     at CodeGenerator.codegen (/tmp/jhipster-test/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
[ERROR]     at /tmp/jhipster-test/node_modules/ngc-webpack/src/main.js:12:103
[ERROR]     at Object.main (/tmp/jhipster-test/node_modules/@angular/tsc-wrapped/src/main.js:106:16)
[ERROR]     at Object.runInternal (/tmp/jhipster-test/node_modules/ngc-webpack/src/main.js:16:27)
[ERROR]     at /tmp/jhipster-test/node_modules/ngc-webpack/src/plugin.js:54:48
[ERROR]     at process._tickCallback (internal/process/next_tick.js:109:7)
[ERROR]     at Module.runMain (module.js:606:11)
[ERROR]     at run (bootstrap_node.js:383:7)
[ERROR]     at startup (bootstrap_node.js:149:9)
[ERROR]     at bootstrap_node.js:496:3
[ERROR] error Command failed with exit code 1.
[ERROR] error Command failed with exit code 1.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

##### **Motivation for or Use Case**

Doing CI for the JHipster Application on CentOS 7 fails.

##### **Reproduce the error**

1. Generate the application according to the `.yo-rc.json`
2. Execute `./mvnw -Pprod -DskipTests package` on CentOS 7

##### **JHipster Version(s)**

```
pexapark@0.0.0 /Users/tardy/Temp/jhipster-test
└── generator-jhipster@4.10.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.pexapark.platform"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "pexapark",
    "packageName": "com.pexapark.platform",
    "packageFolder": "com/pexapark/platform",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.15.0

node: v8.9.1

npm: 5.5.1

bower: 1.8.2

gulp:
[17:11:12] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

CentOS 7 minimal

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This is a compilation issue in your code, are you sure this works on Mac OS X?

**Comment by thomastardy** [comment]
Yes, it worked on Mac OS X, but ... and now the embarrassing part comes ... I had a rule in the global gitignore which ignored the logs folder :'( Sorry for bothering you with this and thanks for the help.
