### ISSUE TITLE
Use https://nodesecurity.io for npm dependencies

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#6699]
Use https://nodesecurity.io to check for known vulnerabilities in dependencies used
This can be added to both generator as well as the generated project using nsp node module

**Comment by gmarziou** [comment]
Do you know where is their doc? I could not find any that explains how to exclude some files for false positives.

**Comment by deepu105** [comment]
@gmarziou I didnt check I was just exploring it and thought might be useful. Did you check their website?

**Comment by gmarziou** [comment]
I just tried on generator-jhipster, tool reported 3 vulnerabilities with one reported twice.
Advisories [525](https://nodesecurity.io/advisories/525) and [534](https://nodesecurity.io/advisories/534) apply only to a node webapp, I found in their github project a [doc about excluding some CVEs](https://github.com/nodesecurity/nsp/blob/bea294ec35c5e8755410e24d559cc65669ef0825/README.md#exceptions).
I think this tool is useless for the generator itself,  I will try on a generated app.

![image](https://user-images.githubusercontent.com/361007/32993499-493a3596-cd59-11e7-9285-d44d7f342cb1.png) https://nodesecurity.io/advisories/534

**Comment by gmarziou** [comment]
Tried on jhipster-sample-app-ng2 and it reported 0 vulnerabilities and no clue about what it has done even in verbose mode. So, not impressed.

**Comment by deepu105** [comment]
Then lets not do it. Thanks for evaluating @gmarziou

**Comment by gmarziou** [comment]
I am now involved in security at work, I may evaluate few tools in coming months that could apply to JHipster.
