### ISSUE TITLE
Feature Request: Login also with E-Mail address

### ISSUE THREAD

**Issue by bluegaspode** [jhipster/generator-jhipster#6701]
##### **Overview of the issue**
A user should be able to also login with his email address rather than his login-name

##### **Motivation for or Use Case**
- users tend to forget their username on webapplication, but often are able to remember their email address they used when registering. 
- more and more webapplication switch to only having the email-address as the main information for login
- there is a "nasty" Firefox autocompletion "feature", which autocompletes the users email address into the login form of a JHipster webapp. This is due to the fact, that Firefox remembers the textfield before a password field (which is the email on JHipster registration form).

On my JHipster based App I already had several users stumbling over this issue.

##### **Suggest a Fix**
I do have a working version locally, but am not sure I'm able to provide a proper fix on the generator sources. This might also influence other types of generators (like MongoDB) which I'm not capable of testing.

The changes are in a single class and quite easy.
Please look into DomainUserDetailsService. It's the central class of Spring to resolve a loginname into a UsersDetail object.
First we need to try to find a user also by his email.

```
        Optional<User> userFromDatabase = userRepository.findOneWithAuthoritiesByLogin(lowercaseLogin);
       // try also to retrieve by email
        if (!userFromDatabase.isPresent()) {
            userFromDatabase = userRepository.findOneWithAuthoritiesByEmail(login);
        }
```
As 'lowercaseLogin' might contain the email-address its important to not use it for creating 
org.springframework.security.core.userdetails.User.
Rather we use the login from the fetched userFormDatabase

```
            return new org.springframework.security.core.userdetails.User(
                // use the official login, rather than 'lowercaseLogin'
                user.getLogin(),
                user.getPassword(),
                grantedAuthorities);
```

##### **JHipster Version(s)**
the current version as of writing the feature request: 4.10.2

##### **JHipster configuration**
Currently I'm running in a monolith SQL based scenario.

**Comment by jdubois** [comment]
Oh yes, this is so annoying!! And I didn't know the Firefox "feature, thanks.
However we have so many opened issues that I don't think the team can do it anytime soon, so a PR would be really welcome.

**Comment by gzsombor** [comment]
You can write a new function, findOneWithAuthoritiesByLoginOrEmail(...), so the 2 round trip won't be necessary. Of course, the case sensitiveness needs to be handled :)

**Comment by deepu105** [comment]
Yes we should do this. Its very annoying

**Comment by BorisZubchenko** [comment]
It is also annoying in the online generator.

**Comment by thomastardy** [comment]
I could try to take this one up if nobody is already working on it.

But on one point I definitely need your input. Currently, logins must be unique and email addresses must be unique. But it is possible to have the same email address as the login on one user and the email address on the other user. This means, it's possible to find more than one user with the login information.
This is an issue in the `DomainUserDetailsService`. Let's assume further that the user, which tries to login is not activated. I'm not sure how the `DomainUserDetailsService` should decide between a UserNotActivatedException and using the other user, which would result in an BadCredentialException.

Another approach would be to prevent this situation from happening and the uniqueness of login and email must be extended, meaning login and email must be unique values, but not on the same user object (login and email is the same).
I think this would be a good solution, but it has issues with all the existing JHipster applications, which don't fulfill this condition. This could be handled by a DB check on startup which fails the application, if the condition is not met.

Which one of these approaches would you prefer? Do you see another solution?

**Comment by jdubois** [comment]
Oh you are totally right, in fact this would be a big security issue!! I don't think this would be easy to check on existing applications...
For me here is something that would work:

- We first test using the e-mail -> as this is validated, we know this is correct
- If (and only if) this doesn't work, then fallback to the user login

-> so if a malicious user chooses as a login an existing e-mail, this trick wouldn't work

What do you think?

**Comment by thomastardy** [comment]
@jdubois sounds reasonable to me as it prevents hijacking of an account.

**Comment by ramzimaalej** [comment]
Why not just use email and make it simpler. As mentioned many apps use the email. I have actually did in one of my projects.

**Comment by deepu105** [comment]
coz both are valid use cases


Thanks & Regards,
Deepu

**Comment by thomastardy** [comment]
@ramzimaalej an easy change you can do and we did that in another JHipster application is to not expose the login and always set the login to the email address. But you should not allow to change the email address in this case.

**Comment by gzsombor** [comment]
I think, the more problematic part is that, the users can freely change their email address, without confirmation/validation/notification, which could cause a lot of problems. Most of the time, I just simply disable the email address changing code.
