### ISSUE TITLE
Maven resource filtering does not work: illegal log file is generated

### ISSUE THREAD

**Issue by peter-gergely-horvath** [jhipster/generator-jhipster#6703]
##### **Overview of the issue**

The file `src/main/resources/logback-spring.xml` contains Logback log configuration used by the backend. For certain loggers, this file contains placeholders, which I believe, should be substituted during the build:

```
    <logger name="com.jhipstersample" level="#logback.loglevel#"/>

    <logger name="io.github.jhipster" level="#logback.loglevel#"/>

```

Unfortunately, this does not seem to work, the filtered (generated) log configuration file in the output contains the placeholders, and NOT the wanted actual log level values.

##### **Motivation for or Use Case**

The dev/prod profile should generate a slightly different output JAR file, with different log levels. At this moment, this does not work. One can only manually alter the log file, which is cumbersome and error prone. (E.g. accidentally going to production with debug log levels.)

##### **Reproduce the error**

1.) Generate a Maven based build 
2.) Run a build with dev/prod profile enabled
3.) Check the content of the `logback-spring.xml` file: there should be NO `#logback.loglevel#` in the actual log configuration file

##### **Suggest a Fix**

I think Maven filtering understands the `${...}` pattern only: change the template to use `${...}` placeholder and try a full generate - build cycle. The output file should contain the variables coming from the Maven build configuration. 

##### **JHipster configuration**

$ jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipstersample@0.0.0 /Users/FOOBAR/jhipster-sample
└── generator-jhipster@4.10.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jhipstersample"
    },
    "jhipsterVersion": "4.10.1",
    "baseName": "jhipstersample",
    "packageName": "com.jhipstersample",
    "packageFolder": "com/jhipstersample",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (Zulu 8.21.0.1-macosx) (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (Zulu 8.21.0.1-macosx) (build 25.131-b11, mixed mode)

git version 2.13.5 (Apple Git-94)

node: v8.9.0

npm: 5.5.1

yarn: 1.2.1

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A
##### **Browsers and Operating System**

Build related issue: no browser involved.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
- I just tested and it works
- Lots of people use it, so I'd be very surprised it doesn't work

-> I'm pretty sure you are not filling this bug by mistake, so there's something strange here!!! Could you just try a `./mvnw clean package -Pprod` to see if your `target/classes/logback-spring.xml` file is correct?

**Comment by peter-gergely-horvath** [comment]
Hi,

I tested `mvn clean package -Pprod` and it indeed it works. This seems to be a race condition between my IntelliJ IDE and Maven: IntelliJ does not perform the same substitution as Maven does, but simply copies the original file to the same location. You run the Maven build and then an internal IntelliJ rebuild is triggered: as a result you see the file appearing without substitution in the `target` directory after you did a Maven build -- quite confusing! Sorry for the incorrect bug report.

**Comment by jdubois** [comment]
OK I understand - this is indeed unfortunate, and for me this is a valid bug! I'm just keeping this closed because I have no idea what we can do about it :-(

**Comment by PierreBesson** [comment]
Yes the IDE cannot do the substitution without invoking maven/gradle but this is normal. This is also the reason why we don't have the version number in `/management/info` when running the app from IDE without running maven once (or after cleaning).

@jdubois However, I think there might be a way to work around this logger issue. We could set the loggers in YAML config. That way it will correctly ignore the `#` and not set it as the logger value.
```
logging:
     level:
          com.jhipstersample: #logback.loglevel#
```
@jdubois Can I submit this as a PR ?

**Comment by jdubois** [comment]
@PierreBesson that's a great idea and that's what we do elsewhere, so +1 from me.
My only issue is that this is going to break everyone's configuration, and I'm not sure people are used to configure Logback using Yaml....
So my proposal is that you create a new issue specifically for this, and ask for a vote (also tweet about it and mention @java_hipster so I RT you)
