### ISSUE TITLE
Fix SonarQube issue in LoggingConfiguration for not using appender name constants

### ISSUE THREAD

**Issue by thomastardy** [jhipster/generator-jhipster#6704]
##### **Overview of the issue**

In `LoggingConfiguration` constants are being defined for the appender names (`LOGSTASH_APPENDER_NAME` and `ASYNC_LOGSTASH_APPENDER_NAME`). But they are not used when configuring the appenders. Instead, the string constants are repeated.

##### **Motivation for or Use Case**

Code quality

##### **Reproduce the error**

Generate application with defaults. Can be seen in [jhipster-sample-app-ng2](https://github.com/jhipster/jhipster-sample-app-ng2/blob/master/src/main/java/io/github/jhipster/sample/config/LoggingConfiguration.java) as well.

##### **Suggest a Fix**

Use the defined constants.
If you think this is worth fixing it, I can have a look at it.

##### **JHipster Version(s)**

```
pexapark@0.0.0 /Users/tardy/Projects/pexapark/pexapark-mvp
└── generator-jhipster@4.10.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.pexapark.platform"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "pexapark",
    "packageName": "com.pexapark.platform",
    "packageFolder": "com/pexapark/platform",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.15.0

node: v8.9.1

npm: 5.5.1

bower: 1.8.2

gulp:
[16:37:02] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

macOS High Sierra

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Good catch! Let me do it
