### ISSUE TITLE
CI: Execute ./mvnw verify instead of ./mvnw package

### ISSUE THREAD

**Issue by thomastardy** [jhipster/generator-jhipster#6705]
##### **Overview of the issue**

The generated config files for Continuous Integration execute `./mvnw package`. This should be change to `./mvnw verify`.

##### **Motivation for or Use Case**

As the generated artefacts are being used for the deployment, the `verify` phase of Maven should be executed as well.

##### **Reproduce the error**

Generate application with defaults and run the sub-generator `ci-cd`.

##### **Suggest a Fix**

Execute phase `verify` instead of `package`. Probably update some documentation as well.
If you think this is worth fixing it, I can have a look at it.

##### **JHipster Version(s)**

```
pexapark@0.0.0 /Users/tardy/Projects/pexapark/pexapark-mvp
└── generator-jhipster@4.10.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.pexapark.platform"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "pexapark",
    "packageName": "com.pexapark.platform",
    "packageFolder": "com/pexapark/platform",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.15.0

node: v8.9.1

npm: 5.5.1

bower: 1.8.2

gulp:
[16:37:02] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

macOS High Sierra

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
- Yes the correct lifecycle goal we should run is indeed `verify`, not `package`
- However we don't do anything specific in the `verify` step, so that shouldn't make any difference

I don't think many people use this, so that shouldn't break any existing setup - Iet's do this as this is cleaner, even if that probably doesn't change anything in the end.

@thomastardy yes if you want to do some PRs to fix this, they are welcome: they should be easy to do, and of course we're here to help.

**Comment by Tcharl** [comment]
Premises to the use of Failsafe?
