### ISSUE TITLE
Documentation 'Caching with Ehcache' out of date

### ISSUE THREAD

**Issue by thomastardy** [jhipster/generator-jhipster#6707]
##### **Overview of the issue**

The documentation on [caching with ehcache](http://www.jhipster.tech/using-cache/) still talks about `ehcache-dev.xml` and `ehcache-prod.xml`. As far as I can tell these files don't exists anymore and the cache are configured in `application-dev.properties` and `application-prod.properties`.

##### **Motivation for or Use Case**

Up-to-date documentation

##### **Reproduce the error**

See http://www.jhipster.tech/using-cache/

##### **Suggest a Fix**

Update documentation

##### **JHipster Version(s)**

```
pexapark@0.0.0 /Users/tardy/Projects/pexapark/pexapark-mvp
└── generator-jhipster@4.10.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.pexapark.platform"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "pexapark",
    "packageName": "com.pexapark.platform",
    "packageFolder": "com/pexapark/platform",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.15.0

node: v8.9.1

npm: 5.5.1

bower: 1.8.2

gulp:
[16:37:02] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

macOS High Sierra

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Good catch, thanks!!
