### ISSUE TITLE
property conflict when project generated with UserExtra

### ISSUE THREAD

**Issue by robertofd1995** [jhipster/generator-jhipster#6710]
##### **Overview of the issue**

I get a problem with a project create from scratch with the JHipster UML , trying to follow this http://www.jhipster.tech/tips/022_tip_registering_user_with_additional_information.html

##### **Motivation for or Use Case**

I just create a project from scratch and use the JHipster UML to create my schema and entities, just after that and without doing anything that executing ./mvnw I get the following error 

"[ERROR] /Users/robertofernandez/Documents/testvoto/src/main/java/com/mysmartcity/myvoto/service/mapper/UserExtraMapper.java:[18,18] No property named "user.name" exists in source parameter(s)."

It should't generate an error a project created from 0 and without any manual change. I think i didn't miss read any step on the guide on the web page

I guess the error is related some how with the fact that userExtra extends User entity and probably there is a conflict.

##### **Reproduce the error**

Create a new project and use the schema that is down below

##### **JHipster Version(s)**

```
 generator-jhipster@4.10.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mysmartcity.myvoto",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "testvoto",
    "packageName": "com.mysmartcity.myvoto",
    "packageFolder": "com/mysmartcity/myvoto",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Propuesta (propuesta) {
  titulo String required,
  descripcion String required,
  numeroApoyos Long required
}
entity Categoria (categoria) {
  titulo String required,
  descripcion String
}
entity Ciudad (ciudad) {
  nombre String required,
  codigoPostal String required
}
entity UserExtra (user_extra) {
  telefono String
}

relationship OneToOne {
  UserExtra{country} to Propuesta,
  UserExtra{user(name)} to User
}
relationship OneToMany {
  Ciudad{userExtra} to UserExtra{pertenece}
}
relationship ManyToOne {
  Propuesta{ciudad(nombre)} to Ciudad
}
relationship ManyToMany {
  Propuesta{categorias} to Categoria
}

dto Propuesta, Categoria, Ciudad, UserExtra with mapstruct
service Propuesta, Categoria, Ciudad, UserExtra with serviceImpl
angularSuffix Propuesta, Categoria, Ciudad, UserExtra with myVoto

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.13.5 (Apple Git-94)

node: v8.9.1

npm: 5.5.1

yeoman: 2.0.0

yarn: 1.3.2

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

User Extra.json
```
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "relationshipName": "country",
            "otherEntityName": "propuesta",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "userExtra"
        },
        {
            "relationshipType": "one-to-one",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "name",
            "ownerSide": true,
            "otherEntityRelationshipName": "userExtra"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "pertenece",
            "otherEntityName": "ciudad",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "telefono",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20171120193521",
    "entityTableName": "user_extra",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "angularJSSuffix": "myVoto"
}
```

Propuesta.json
``` 
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "ciudad",
            "otherEntityName": "ciudad",
            "otherEntityField": "nombre"
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "",
            "relationshipName": "categorias",
            "otherEntityName": "categoria",
            "otherEntityField": "id",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "titulo",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "descripcion",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "numeroApoyos",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20171120193518",
    "entityTableName": "propuesta",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "angularJSSuffix": "myVoto"
}
```

Ciudad.json
``` 
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "userExtra",
            "otherEntityName": "userExtra",
            "otherEntityRelationshipName": "pertenece"
        }
    ],
    "fields": [
        {
            "fieldName": "nombre",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "codigoPostal",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20171120193520",
    "entityTableName": "ciudad",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "angularJSSuffix": "myVoto"
}
```

Categoria.json
``` 
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "titulo",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "descripcion",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20171120193519",
    "entityTableName": "categoria",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "angularJSSuffix": "myVoto"
}
```

##### **Browsers and Operating System**

Mac Os High Sierra 10.13.1
Chrome 62

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
In your JDL you do this relationship: `UserExtra{user(name)} to User` and indeed, a user doesn't have a `name` property, as the error message says.
If you do `UserExtra{user(login)} to User` (as `login` is an existing property), the code compiles.

**Comment by robertofd1995** [comment]
Just as detail , i think it will be interesting to publish on the managing-relationships part of the web page , where you speak about the tip of user , it will be interesting to speak about the properties of the entity User. 

Given that this entity exists from 0, and adding information to the user entity is often a operation that is done, it will be good to add this information together with [this tip already available](http://www.jhipster.tech/tips/022_tip_registering_user_with_additional_information.html) and make it a little bit clear.

I know this is a really big project and complicated to keep track of all the needs or doubts that people could have and I appreciate all this  awesome work you are doing.

Also i am following this project since several years but it wasn't until a few days that I start to put it on practice , and i think you should give [more visibility to the book](https://www.infoq.com/minibooks/jhipster-4-mini-book) you have written that explains good how to do a project  for newbies , maybe you could [add it here](http://www.jhipster.tech/help/) ?
