### ISSUE TITLE
Internationalization options not working for start.jhipster.tech

### ISSUE THREAD

**Issue by gomesp** [jhipster/generator-jhipster#6713]
##### **Overview of the issue**

I generated two apps using https://start.jhipster.tech/#/generate-application

Their repos are located here: https://github.com/gomesp/amigosecreto and https://github.com/gomesp/amigosecreto2 

The first repo was generated with internationalization options (English as default and PT-BR as secondary).

When starting the app I get a 404 in my browser console. It seems that one of the i18n files is not being generated.

ERROR {…}_body: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /i18n/en.json</pre>\n</body>\n</html>\n"headers: Object { _headers: Map, _normalizedNames: Map }ok: falsestatus: 404statusText: "Not Found"type: 2url: "http://localhost:9000/i18n/en.json"__proto__: Object { constructor: Response(), toString: Response.prototype.toString() } core.es5.js:1020

##### **JHipster Version(s)**

```
➜  amigosecreto git:(master) ✗ jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**


##### **JHipster configuration**

```
amigosecreto@0.0.0 /Users/gomesp/src/amigosecreto
└── generator-jhipster@4.10.2

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitHubOrganization": "gomesp",
    "baseName": "amigosecreto",
    "packageName": "io.github.jhipster.application",
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "enableSwaggerCodegen": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "pt-br"
    ],
    "clientFramework": "angularX",
    "jhipsterVersion": "4.10.2",
    "packageFolder": "io/github/jhipster/application",
    "jwtSecretKey": "replaced-by-jhipster-info",
    "jhiPrefix": "jhi"
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>




</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

git version 2.14.2

node: v8.7.0

npm: 5.5.1

bower: 1.8.2

yeoman: 2.0.0

yarn: 1.2.1

Docker version 17.11.0-ce-rc3, build 5b4af4f

docker-compose version 1.17.0, build ac53b73

Congratulations, JHipster execution is complete!
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities generated

##### **Browsers and Operating System**

* Firefox and macOS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I confirm the bug. It concerns projects generated with [start.jhipster.tech](https://start.jhipster.tech)

When choosing additional languages, the native language is not added to the other languages.
Here your [.yo-rc.json](https://github.com/gomesp/amigosecreto/blob/master/.yo-rc.json) :

```yaml
    "nativeLanguage": "en",
    "languages": [
      "pt-br"
    ],
```
instead of:
```yaml
    "nativeLanguage": "en",
    "languages": [
      "en", // <---- missing en
      "pt-br"
    ],
```

Only @jdubois can fix it. I assign this ticket to you.

**Comment by jdubois** [comment]
It's corrected (will be released in a few days, I'm doing some big work at the moment there). For the moment, the workaround is to keep the "native" language selected in the language list (anyway, it doesn't make much sense to say your native language is English, and then de-select it in the supported languages!)

**Comment by gomesp** [comment]
@jdubois Thanks for clarifying it. I didn't realise I had to keep English in the supported languages. I thought it had been added by default as the native.

Thanks for the quick response.

**Comment by jdubois** [comment]
Yes that's a stupid mistake on my side, and only for JHipster Online!
Thanks for the report!!!
