### ISSUE TITLE
@FeingClient not using default system user for interservice communication

### ISSUE THREAD

**Issue by arnogeismar** [jhipster/generator-jhipster#6714]
##### **Overview of the issue**
I have an microservice endpoint with @Preauthorized("hasRole("ROLE_ADMIN") global method security enabled.
Another one of my microservices wants to consume this endpoint by using a Feignclient

@FeignClient(name = "fooService")
public interface fooServiceClient {

I am getting a 403 forbidden because the user jwt is forwarded and the user only hasRole("ROLE_USER")

##### **Motivation for or Use Case**

I would expect that interservice communication should always use the system account since it is inter system communication

##### **Reproduce the error**

1) create a restcontroller annotated with @EnableGlobalMethodSecurity true 
2) create an endpoint with @Preauthorized("hasRole("ROLE_ADMIN"))
3) create a feignclient in another microservice application
4) call the endpoint by using the feignclient inside an endpoint with ROLE_USER

##### **Related issues**

Not that I am aware of 

##### **Suggest a Fix**

Always use system user for inter service communication

##### **JHipster Version(s)**

4.10.2

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "be.techninja.auctions",
      "nativeLanguage": "nl"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "bidService",
    "packageName": "be.techninja.auctions",
    "packageFolder": "be/techninja/auctions",
    "serverPort": "8083",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "c5115718a5c7f81ea5efd4f739393f54ee892f60",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "nl",
    "languages": [
      "nl",
      "en",
      "fr",
      "de"
    ],
    "clientPackageManager": "yarn"
  }
}

##### **Browsers and Operating System**
all browsers mac os

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Indeed, we propagate the user from microservice to microservice, so it is called using the current user's permissions, and not the system user's permissions.
This is basically like when you call a Spring Bean locally: you do that call with the current user's permissions.
For me, what you want to do would cause a security risk, and we are also very happy to have the current user's login and permissions, as many features are usually served using the current user's context.
If you don't want to secure your microservices, you can remove the security option, or maybe configure your Feign client specifically.

**Comment by pascalgrimaud** [comment]
You can look this ticket: https://github.com/jhipster/generator-jhipster/issues/3649
You have everything :
- article
- module
- sample code
- link to some code
etc. 

I don't think there is something to do in the current generator-jhipster
