### ISSUE TITLE
The url of "Change password" is wrong on API gateway frontend with Jhipster UAA

### ISSUE THREAD

**Issue by jihlee** [jhipster/generator-jhipster#6720]
##### **Overview of the issue**
The url of "Change password" is wrong on API gateway frontend with Jhipster UAA enabled.
It should be "/api/account/change_password", but currently "/api/account/change-password".

##### **Motivation for or Use Case**
At the moment, we cannot change password from API gateway frontend.

##### **Reproduce the error**
1. clone jhipster-registry from git
2. create uaa service with jhipster
3. create api-gateway with jhipster
4. login with admin/admin
5. try to change the password using password change feature, yet doesn't work.

##### **Related issues**
Maybe #6670 ? Seems that this would be occur since #6282.

##### **Suggest a Fix**
Two different approach.
1. change the url in the frontend template 
2. change the mapped url in UAA template

Tried 1 and works fine, but according to #6282, second way would be better?

##### **JHipster Version(s)**
4.8.2

##### **JHipster configuration**
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
apigateway@0.0.0 /Users/jihunlee/Development/git-repos/vroong3.0-msa/vroong-apigateway
└── generator-jhipster@4.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "*****",
      "nativeLanguage": "en",
      "microservicePath": "../*****"
    },
    "jhipsterVersion": "4.8.2",
    "baseName": "apigateway",
    "packageName": "*****",
    "packageFolder": "*****",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ko"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.13.6 (Apple Git-96)

node: v8.5.0

npm: 5.3.0

bower: 1.3.5

gulp:
[12:23:58] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.1.0

Docker version 17.10.0-ce, build f4ffd25

docker-compose version 1.16.1, build 6d1ac21

Execution complete

##### **Browsers and Operating System**
macOSX High Sierra. Tested on Chrome and Safari

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I didn't manage to reproduce, but I tested with current master and not 4.8.2, as a lot of code about UAA has changed since this version. 

Can you test with 4.10.2 and confirm it's OK now ? Don't hesitate to reopen the ticket if you still have the issue.
