### ISSUE TITLE
About React support

### ISSUE THREAD

**Issue by wangh09** [jhipster/generator-jhipster#6721]
Hi,
    I'm sorry to ask here, but I posted the following question on stackoverflow but no one answered:
https://stackoverflow.com/questions/47427947/jhipster-how-to-generate-react-projects

I noticed that the react support has been merged into generator-jhipster, but found no guide on this topic. Could anyone help me on this ?

**Comment by jdubois** [comment]
The right place for questions is on SO, please don't pollute the ticket system (or we would have even less time to answer you on SO). I'll answer you there.

**Comment by jdubois** [comment]
Sorry I can't answer you on SO as your question was put on hold. Please follow the SO guidelines.

**Comment by wangh09** [comment]
Thanks a lot! and I'm very sorry for polluting here, but this fascinating project just drive me crazy and I'm eager to find out whether it could support what I usually use.  I'm not familiar with it so I didn't notice that the question was on hold :^) I just opened a new question on SO (https://stackoverflow.com/questions/47458681/how-can-i-generate-react-projects-by-jhipster-generator).
