### ISSUE TITLE
Gateway is unauthorized to connect to Keycloak

### ISSUE THREAD

**Issue by ThomasWilhelmUR** [jhipster/generator-jhipster#6723]
##### **Overview of the issue**

In a freshly generated microservice environment, the gateway is not authorized to communicate with Keycloak. When clicking "sign in" it will take you to "keycloak:9080" (instead of "localhost:9080"). Manually changing it, will let you log in but on the redirect this happens:

```
Sorry, an error has occurred.

Status:  (Unauthorized)
Message: Authentication Failed: Could not obtain user details from token
```

##### **Motivation for or Use Case**

Trying out the Keycloak integration.

##### **Reproduce the error**

1. Create new microservice using keycloak
2. Create new gateway using keycloak
3. Create a dummy entity (like "foo") and regenerate.
4. Run the docker-compose subgenerator
5. Start all of the apps using "docker-compose up -d"
6. "Sign in" on the gateway, manually change URL from "keycloack:9080" to "localhost:9080" 

##### **Related issues**

#6722 

##### **Suggest a Fix**

Idea: Do you have to add the realm key or client's public key to the app configuration files? If so, I have not seen this documented anywhere (pointers appreciated).

##### **JHipster Version(s)**

4.10.2

##### **JHipster configuration**

Service:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "en.something",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "service",
    "packageName": "en.something",
    "packageFolder": "en/something",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "1372d952e81cee4ed366b7d48c803dd3904c35cd",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "de",
    "languages": [
      "de"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

Gateway:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "en.something",
      "nativeLanguage": "de",
      "microservicePath": "../service"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "gateway",
    "packageName": "en.something",
    "packageFolder": "en/something",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
Foo.json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "fooname",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20171123142052",
    "dto": "no",
    "service": "no",
    "entityTableName": "foo",
    "jpaMetamodelFiltering": false,
    "pagination": "no",
    "microserviceName": "service",
    "searchEngine": "elasticsearch"
}
```

##### **Browsers and Operating System**

Windows 10, Chrome/FF, Docker

**Comment by jdubois** [comment]
Yes you need a specific realm, that's out of the box if you use our Docker Compose configuration (`docker-compose -f src/main/docker/keycloak.yml up -d`), but if you don't, then you need to do it yourself.

**Comment by ThomasWilhelmUR** [comment]
Sorry but I can not follow you.

The `keycloak.yml` in `gateway/.../src/main/docker/` and the one generated by the docker-compose subgenerator.

Starting up keycloak from both places leads to a working keycloak instance with the "jhipster" realm in it, configured the way it says in `application.yml`. Error in both cases.

The gateway uses the "web_app" client that does not require a secret since it is configured to use the access type "public". 

Would love advice / pointers to relevant discussion on here, thanks.

**Comment by ThomasWilhelmUR** [comment]
I am using the out-of-the-box keycloak.

Solution: As per #6722 adding keycloak to the hosts file also fixes this.
