### ISSUE TITLE
Being able to configure the default @Pageable size

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6734]
##### **Overview of the issue**

By default the `Pageable` size of a request is 20. It would be good to be able to customize it (like we do in the front with `ITEMS_PER_PAGE = 20`).

##### **Motivation for or Use Case**

On the Angular side, we can easily change the number of items per page just by setting the  `ITEMS_PER_PAGE`. But on the REST calls, by default, the size is 20, so the combobox are limited to 20. It would be good to be able to configure this as easily on the back as we do on the front.

You can configure this size (eg. 99) on a per method basis by using the it either by using the [PageableDefault](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/web/PageableDefault.html) annotation:

```
public ResponseEntity<List<Country>> getAllCountries(CountryCriteria criteria,@PageableDefault(size = 99) Pageable pageable) {
```

But you can also configure the default size for *all* the calls with the following code:

```
@Configuration
public class PageableConfiguration extends WebMvcConfigurerAdapter {

    static final Pageable DEFAULT_PAGE_REQUEST = new PageRequest(0, 99);

    @Override
    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> argumentResolvers) {
        PageableHandlerMethodArgumentResolver resolver = new PageableHandlerMethodArgumentResolver();
        resolver.setFallbackPageable(DEFAULT_PAGE_REQUEST);
        argumentResolvers.add(resolver);
        super.addArgumentResolvers(argumentResolvers);
    }
}
```

##### **References**

* https://stackoverflow.com/questions/27032433/set-default-page-size-for-jpa-pageable-object
* https://stackoverflow.com/questions/40685063/setting-default-page-size-for-spring-pageable-not-taking-effect
* https://medium.com/@rasheedamir/java-spring-default-page-default-sort-cab2f410f8b0

##### **Suggest a Fix**

If this can be of an interest, I can do a PR with the previous code (`PageableConfiguration`). Let me know.

##### **JHipster Version(s)**

4.11

**Comment by jdubois** [comment]
I know this is a common request, but wouldn't that be against our [Policy 1](http://www.jhipster.tech/policies/)?
I'm not a big fan of having yet another configuration file, and anyway I guess the number would change depending on the business rules: I like the `@PageableDefault(size = 99)` much better.

Now this is a very nice tip, and I'm sure many people who like to know this - how about just documenting this on the pagination section on http://www.jhipster.tech/creating-an-entity/ ?

**Comment by agoncal** [comment]
@jdubois It's up to you. I can either send a PR with code, or with documentation ;o)

**Comment by jdubois** [comment]
Let's do documentation then - it's easier and that should be enough for most people

**Comment by ruddell** [comment]
>But on the REST calls, by default, the size is 20, so the combobox are limited to 20. 

If you are referring to relationships, you can set the size of the query when loading the entities, [such as here](https://github.com/jhipster/jhipster-sample-app-ng2/blob/master/src/main/webapp/app/entities/operation/operation-dialog.component.ts#L41): `this.bankAccountService.query()` -> `this.bankAccountService.query({size: 99})`

I would also prefer documentation over a new config file.

**Comment by cbornet** [comment]
Note that Spring Boot 2 will have a [spring.data.web.pageable.default-page-size](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M2-Configuration-Changelog) property to use instead of the PageableHandlerMethodArgumentResolver.

**Comment by ctamisier** [comment]
The suggested code about pageable configuration such as:
```
@Configuration
public class PageableConfiguration extends WebMvcConfigurerAdapter {
[...]
}
```
is what I put in all my JHipster projects as well.

For me if we make a `query()` with no `page` and `size` informations means that we want everything.
But we might think that it could be unsafe when we have a lot of data.
But in `PageableHandlerMethodArgumentResolver` we actually can just go up to 2000 (`int DEFAULT_MAX_PAGE_SIZE = 2000;`) which will be the maximum anyway even if you put higher in your page request. So it's not that unsafe IMHO. It's like we have security... (??)

So what about having (until Spring Boot 2) the following code as a tip as you said. And explain about the 2000 limit:
```
@Configuration
public class PageableConfiguration extends WebMvcConfigurerAdapter {

    static final Pageable DEFAULT_PAGE_REQUEST = new PageRequest(0, 2000);

    @Override
    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> argumentResolvers) {
        PageableHandlerMethodArgumentResolver resolver = new PageableHandlerMethodArgumentResolver();
        resolver.setFallbackPageable(DEFAULT_PAGE_REQUEST);
        argumentResolvers.add(resolver);
        super.addArgumentResolvers(argumentResolvers);
    }
}
```

**Comment by jdubois** [comment]
Closing this as it has been stuck for 1 month -> as @cbornet wrote this will be just a standard configuration property with Spring Boot 2, and this is where our current efforts are going (and this should be out in a couple of months)

**Comment by JavaHelper** [comment]
@All - Could you please guide me here: https://stackoverflow.com/questions/27032433/set-default-page-size-for-jpa-pageable-object, as Spring Boot 2.1.x , things are not working ?

**Comment by JavaHelper** [comment]
@All - Could you please guide me here https://stackoverflow.com/questions/56786158/unable-to-override-defaults-of-pagination-in-spring-boot-2-1-5-release ?

**Comment by jdubois** [comment]
@JavaHelper spamming the whole team is not nice, especially 2 times on an old and unrelevant ticket (not the same Spring Boot version), and as it's a cross post from StackOverflow, and as it's not even a JHipster bug at at all. Please have a look at our [contributing guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md).
