### ISSUE TITLE
Cannot start Webpack Development Server

### ISSUE THREAD

**Issue by kcsunny** [jhipster/generator-jhipster#6753]
##### **Overview of the issue**
yo jhipster!
I am a beginner to JHipster. I just created a simple app using jhipster and have not added any code myself. So at the end of project generation, it gives following error:

$ node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/
webpack.dev.js --progress --profile
error Command failed with exit code 3221225477.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

However the server and client application are being generated successfully. Now, when I run the server in localhost, it runs without any error but the browser displays nothing. I tried running the client server with `yarn start` but it again displays above mentioned error. 

##### **Reproduce the error**

I know its working for you, but I just generated the project and ran it. Nothing fancy here.

##### **JHipster Version(s)**
4.11.1

##### **JHipster configuration**
`jhipster info` result:
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipsterapp@0.0.0 C:\Users\Windows7\IdeaProjects\jhipsterapp
`-- generator-jhipster@4.11.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycomp.jhipsterapp"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "jhipsterapp",
    "packageName": "com.mycomp.jhipsterapp",
    "packageFolder": "com/mycomp/jhipsterapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `
.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) Client VM (build 25.152-b16, mixed mode, sharing)

git version 2.13.2.windows.1

node: v8.9.1

npm: 5.5.1

gulp:
[15:42:06] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.3.2

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Google Chrome : 62.0.3202.94 (Official Build) (32-bit) (cohort: Stable)
Operating System : Windows 7 Ultimate SP 1 - 32 bit
Processor: Intel Core 2 Duo @ 1.66 GHz
RAM: 3 GB 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Seems like Yarn issue on Windows and nothing specific to JHipster.

Can you create a new folder and run `yarn add bootstrap` and see if it works?

**Comment by pascalgrimaud** [comment]
Maybe because of: Operating System : Windows 7 Ultimate SP 1 - 32 bit ?

**Comment by MathieuAA** [comment]
@pascalgrimaud perhaps! I wonder... does this `--max_old_space_size=4096` work for 32bit? I know there are limitations but I haven't had the time to dig into it today.

**Comment by kcsunny** [comment]
@deepu105 yes, it works

**Comment by deepu105** [comment]
ok so @pascalgrimaud @MathieuAA suggested the issue might be with the OS setup.

Can you open your package.json and change the below line from `"webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js",` to `"webpack": "node node_modules/webpack/bin/webpack.js",` ?

**Comment by kcsunny** [comment]
@deepu105 @pascalgrimaud @MathieuAA Thank you so much, it executed successfully. However, will my machine get me into these kind problems into future? Or, is my machine compatible?

**Comment by gmarziou** [comment]
Your machine is far from being adequate for development, 3 GB RAM is too low, Windows 7 is not supported anymore by JHipster (you could encounter issues with notifications in in taskbar).
If you cannot upgrade hardware, you should consider migrating to Linux for better usage of limited resources and better support  for Node.

**Comment by deepu105** [comment]
Closing this as we cant do much here.
