### ISSUE TITLE
Login doesn't work in gateway generated with option "Clustered HTTP sessions using Hazelcast"

### ISSUE THREAD

**Issue by maznag** [jhipster/generator-jhipster#6756]
##### **Overview of the issue**

When I generate the gateway with the option "Clustered HTTP sessions using Hazelcast" I can't login to gateway using OIDC keycloak or OKTA. It seems like it's a CORS error. With keycloak I have this error:

Failed to load http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth?client_id=web_app&redirect_uri=http://localhost:8080/login&response_type=code&scope=openid%20profile%20email&state=dSg8Z6: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

I tried to add "*" to 'Web Origins' in Clients/web_app using keycloak UI without success.

Same error with Okta:

Failed to load https://dev-XXXXXX.oktapreview.com/oauth2/default/v1/authorize?client_id=XXXXXXXXXXXXXXX&redirect_uri=http://localhost:8080/login&response_type=code&scope=openid%20profile%20email&state=5uBGXn: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

##### **Motivation for or Use Case**

Testing Micro-services with OIDC

##### **Reproduce the error**

- Generate Gateway application as following:

<details>
<summary>mkdir gateway && cd gateway && jhipster</summary>
<pre>
? Which *type* of application would you like to create? Microservice gateway
? What is the base name of your application? gateway
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8080
? What is your default Java package name? com.gateway
? Which service discovery server do you want to use? Consul
? Which *type* of authentication would you like to use? OAuth 2.0 / OIDC Authentication (stateful, works with Keycloak and Okta)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? Clustered HTTP sessions using Hazelcast
? Which *Framework* would you like to use for the client? Angular 4
? Would you like to enable *SASS* support using the LibSass stylesheet preprocessor? Yes
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install French
? Besides JUnit and Karma, which testing frameworks would you like to use? Gatling, Protractor
? Would you like to install other generators from the JHipster Marketplace? No
</pre>
</details>

- Access to http://localhost:8080 and click 'login'

##### **Related issues**

Issue #6724

##### **Suggest a Fix**

No idea !

##### **JHipster Version(s)**

4.11.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "gateway",
    "packageName": "com.gateway",
    "packageFolder": "com/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.13.1
node: v8.7.0
npm: 5.5.1
bower: 1.8.2
gulp:
[00:05:25] CLI version 1.4.0
yeoman: 2.0.0
yarn: 1.3.2
Docker version 17.09.0-ce, build afdb6d4
docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

- MacOS 10.13.1
- Tested with Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
FWIW, a monolith makes a request to `/api/account` and gets a 401 response, rather than a 302.

<img width="1517" alt="screen shot 2017-11-28 at 11 55 08 am" src="https://user-images.githubusercontent.com/17892/33338350-14650068-d433-11e7-82a9-d14795fbff27.png">

**Comment by mraible** [comment]
I also discovered that removing `requestMatcher(authorizationHeaderRequestMatcher())` from the following code block in `MiroserviceSecurityConfiguration.java` changes the 302 to a 401. However, it also causes http://localhost:8080/login to result in a 404.

```java
@Override
public void configure(HttpSecurity http) throws Exception {
    http
        .csrf()
        .disable()
        .exceptionHandling()
        .authenticationEntryPoint(problemSupport)
        .accessDeniedHandler(problemSupport)
    .and()
        .headers()
        .frameOptions()
        .disable()
    .and()
        .sessionManagement()
        .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
    .and()
        .requestMatcher(authorizationHeaderRequestMatcher())
        .authorizeRequests()
        .antMatchers("/api/profile-info").permitAll()
        .antMatchers("/api/**").authenticated()
        .antMatchers("/management/health").permitAll()
        .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN);
}
```

**Comment by jdubois** [comment]
Are you sure this is cause by Hazelcast session clustering? Can you try removing it, to know if that solves the issue?
I have absolutely no idea why configuring Hazelcast would cause a CORS issue! That doesn't make sense to me.

**Comment by mraible** [comment]
Just to be clear, the CORS issue doesn't have anything to do with logging in. It happens for microservices, but not for a monolith. This is because microservices return a 302 for `/api/account` rather than a 401 like a monolith does.

**Comment by jdubois** [comment]
I'm sorry but I am lost:

- "Hazelcast" is the title of this ticket, but this has nothing to do with the issue?
- I also don't understand the issue with `/api/account` on microservices - they don't hold any account management code (the gateway does), so of course they give back an error response. Why is that an issue?

**Comment by mraible** [comment]
Sorry, I was just talking about CORS. I meant to say "gateway" rather than "microservice".

This bug is accurate: when you use clustered HTTP sessions with Hazelcast, login doesn't work.

**Comment by jdubois** [comment]
OK, and is there any stacktraces on the Hazelcast side? I guess there is something in the session that can't be serialized?
Anyway, I wouldn't recommend using distributed sessions, and even less for authentication, so this OpenID Connect + session clustering is a combination of options we should not allow.

**Comment by maznag** [comment]
@jdubois I'm sure this is cause by Hazelcast session clustering. When I generate the gateway without "Clustered HTTP sessions using Hazelcast" option, the login works well. But I noticed that when accessing at http://localhost:8080, the error I described above is displayed:

No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http: // localhost: 8080' is therefore not allowed access.

So if I understood correctly it's useless to have both OIDC and "Clustered HTTP sessions using Hazelcast" options. In this case, we simply disable Hazelcast session clustering for microservices with OIDC.

**Comment by jdubois** [comment]
Yes @maznag I think that will be the end result - anyway, for the last 3 months, our stats show Hazelcast session clustering was used by 0,49% of projects... So maybe it's time to dump it.

**Comment by maznag** [comment]
So let's add a simple condition to disable this option when the gateway and OIDC are selected :-). I wonder if this is the case for gateway with UAA or not ?? it deserves a test.

**Comment by maznag** [comment]
It's work well with UAA server. I did this:

- Generate UAA Server
- Generate Gateway without "Hazelcast session clustering" and login works well
- Re-generate Gateway with "Hazelcast session clustering" and login works also well

So, this issue is happened when we combine OIDC and Hazelcast session clustering. I'll look in more detail to see why this issue.

**Comment by maznag** [comment]
@jdubois @mraible After looking in detail on the gateway generated with OIDC and "Hazelcast session clustering" options, I found that the problem comes from urls mapping for hazelcastWebFilter. The login works well when I delete the following line (See config/WebConfigure.java class, initClusteredHttpSessionFilter method):

hazelcastWebFilter.addMappingForUrlPatterns(disps, true, "/*");

but I do not know what impact has on the Hazelcast session clustering mecanism. It seems that there is a conflict somewhere.

Do you know please how I can do to test whether clustering works well or not.

**Comment by mraible** [comment]
Nice investigative work @maznag! I'm not sure how to test clustering, but I imagine it has something to do with firing up multiple nodes, shutting down a server or two, then confirming everything still works.

**Comment by jdubois** [comment]
- awesome work!
- To test: fire up 2 notes, look at the console logs you will clearly see Hazelcast (look for "Members" with list of nodes in the cluster). You can put something in HttpSession to test.

But really I do not think it's worth the trouble

**Comment by gmarziou** [comment]
Great work but as Julien said it does not make sense to use Hazelcast for sessions when we don't use sessions. Gateways should be stateless, so we should prevent this option,  even though Hazelcast can still be used as Hibernate second level cache. If a developer wants to use session clustering it means probably that it's fora specific se-case which dos require putting business logic on the gateway and in this case this developer should know what is required to do so.

**Comment by jdubois** [comment]
BTW we need to rework our caching support - we also use Spring Cache so it
shouldn't work only with Hibernate.
That should be another issue.

**Comment by maznag** [comment]
Thank you all. It starts well then for me the contribution to this famous project 👍 

Okay, as you all agree that it's not a good idea to combine these two options so we can disable Hazelcast Sessions Clustering for OIDC. 

But I don't understand why this problem only happens when OIDC is selected, because there is no particular problem for microservice with UAA.

@jdubois Do you want me to add the condition to disable the "Hazelcast sessions clustering" option when OIDC is selected and submit a new PR.

**Comment by jdubois** [comment]
- that's because OIDC is stateful: It's probably storing stuff in HttpSession that Hazelcast doesn't like
- yes you can do a PR It's welcome!
