### ISSUE TITLE
Color overrides in _bootstrap-variables.scss do not work since bootstrap 4 beta

### ISSUE THREAD

**Issue by ThomasWilhelmUR** [jhipster/generator-jhipster#6757]
I briefly talked about this with @deepu105 before, so here is the issue:

##### **Overview of the issue**

Overriding theme colors in bootstrap 4 beta is different from the alpha versions. Therefore the generated _bootstrap-variables.scss file is outdated. Changing color values will not affect the built files. Changing variables (like $enable-rounded) is not affected.

##### **Motivation for or Use Case**

Theming a JHipster application.

##### **Reproduce the error**

1. Create a new gateway with Angular(4) and Bootstrap 4 beta 
2. yarn start
3. Change a color variable, like $brand-primary
4. look for changes on the gateway

##### **Suggest a Fix**

The bootstrap documentation states that changing theme colors now works differently:

in _bootstrap-variables:
```
$theme-colors: (
  "primary": #0074d9,
  "danger": #ff4136
);
```

Note that this uses sass functions that at this point are not yet included. Therefore the build fails. Importing required files for theming as per the boostrap docs breaks the resulting css (as stated in the JHipster docs).

Maybe changing the build setup so that importing functions earlier will work, but I am not sure and have not been successful so far. I'd appreciate suggestions and would gladly PR the fix.

##### **JHipster Version(s)**

tested with 4.10 - 4.11.1 (probably all versions using bootstrap 4 beta and up are affected)

##### **JHipster configuration**

Gateway config:

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "en.something",
      "nativeLanguage": "de",
      "microservicePath": "../service"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "gateway",
    "packageName": "en.something",
    "packageFolder": "en/something",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

Windows 10, Chrome/FF

**Comment by deepu105** [comment]
I would have to take look at this as lot changed between current BS beta and the last time I tested this

**Comment by ruddell** [comment]
I have not confirmed this, but someone in our Gitter chat mentioned that to customize Bootstrap's colors, they needed to do the following:

in global.scss
```
$theme-colors: (
        primary: #601d73
);
```
and in bootstrap-variables-scss:
```
$theme-colors: () !default;
$theme-colors: map-merge((
        primary: $brand-primary,
        success: $brand-success,
        info: $brand-info,
        warning: $brand-warning,
        danger: $brand-danger
), $theme-colors);
```

**Comment by ThomasWilhelmUR** [comment]
Can confirm that this works for me.

**Comment by gmarziou** [comment]
Well, from what I have tried, it is simpler: we just have to rename $brand-primary to $primary.
