### ISSUE TITLE
Api first codegen error building from different folder 

### ISSUE THREAD

**Issue by sghino** [jhipster/generator-jhipster#6758]
##### **Overview of the issue**
With Api First generatorm when I build from a different folder (ex: `mvn -f jhipster-project/pom.xml clean package`) there is the below error:
java.io.FileNotFoundException: src/main/resources/swagger/api.yml (No such file or directory)

##### **Motivation for or Use Case**

This is a bug that can be easily fixed adding ${project.basedir} at the inputSpec node of swagger-codegen-maven-plugin

##### **Reproduce the error**

Run mvn package from the parent folder of the project:
`mvn -f jhipster-project/pom.xml clean package`

##### **Suggest a Fix**
Adding ${project.basedir} to the inputSpec node
```
<artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>${swagger-codegen-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/swagger/api.yml</inputSpec>
                            <language>spring</language>
```

##### **JHipster Version(s)**

```
faianagaziende@0.0.0 /home/rob/git/FAI/fainp-ms/fainp-ms-anagaziende/fainp-ms-anagaziende
└── generator-jhipster@4.11.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "it.fai.ms.anagaziende"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "faianagaziende",
    "packageName": "it.fai.ms.anagaziende",
    "packageFolder": "it/fai/ms/anagaziende",
    "serverPort": "9011",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.7.4

node: v8.3.0

npm: 5.4.2

bower: 1.8.0

gulp:
[11:50:14] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.0.1

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.11.2, build dfed245

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by cbornet** [comment]
@sghino would you do a PR for this ?

**Comment by jdubois** [comment]
Otherwise I really don't understand at all why you want to run this from another folder! If you do the PR it will probably be merged, otherwise I'm not sure anybody is interested in doing this PR.

**Comment by antarus** [comment]
This request can be explained easily, personally, if I want to build several jhipster applications easily, I make a script in a parent folder :)
I have never noticed a problem but I do not use (yet) this feature.

**Comment by antarus** [comment]
I made the modification locally, I do the PR later when I come back from work

**Comment by sghino** [comment]
@antarus thanks for the PR. It's very usefull for my jenkins builds.
