### ISSUE TITLE
[React] Error when generate my first react project

### ISSUE THREAD

**Issue by romainlouvet** [jhipster/generator-jhipster#6761]
[at-loader] Checking finished with 3 errors
1022ms asset optimization
Hash: 81e6c356c906de705f5f
Version: webpack 3.8.1
Time: 16994ms
 7 assets
[./src/main/webapp/app/app.css] ./src/main/webapp/app/app.css 1.04 kB {1} [built]
       [] -> factory:1171ms building:23ms = 1194ms
[./src/main/webapp/app/app.tsx] ./src/main/webapp/app/app.tsx 3.59 kB {1} [built]
       [] -> factory:406ms building:587ms dependencies:94ms = 1087ms
[./src/main/webapp/app/config/axios-interceptor.ts] ./src/main/webapp/app/config/axios-interceptor.ts 2.33 kB {1} [built]
       [] -> factory:405ms building:182ms = 587ms
[./src/main/webapp/app/config/devtools.tsx] ./src/main/webapp/app/config/devtools.tsx 1.68 kB {1} [built]
       [] -> factory:408ms building:643ms dependencies:30ms = 1081ms
[./src/main/webapp/app/config/error-middleware.ts] ./src/main/webapp/app/config/error-middleware.ts 2.5 kB {1} [built]
       [] -> factory:596ms building:84ms = 680ms
[./src/main/webapp/app/config/logger-middleware.ts] ./src/main/webapp/app/config/logger-middleware.ts 1.57 kB {1} [built]
       [] -> factory:598ms building:155ms = 753ms
[./src/main/webapp/app/config/notification-middleware.ts] ./src/main/webapp/app/config/notification-middleware.ts 2.03 kB {1} [built]
       [] -> factory:597ms building:120ms dependencies:1346ms = 2063ms
[./src/main/webapp/app/config/store.ts] ./src/main/webapp/app/config/store.ts 2.85 kB {1} [built]
       [] -> factory:404ms building:112ms dependencies:572ms = 1088ms
[./src/main/webapp/app/index.tsx] ./src/main/webapp/app/index.tsx 2.54 kB {1} [built]
       [] -> factory:89ms building:3158ms = 3247ms
[./src/main/webapp/app/reducers/action-type.util.ts] ./src/main/webapp/app/reducers/action-type.util.ts 1.47 kB {1} [built]
       [] -> factory:345ms building:178ms = 523ms
[./src/main/webapp/app/reducers/authentication.ts] ./src/main/webapp/app/reducers/authentication.ts 9.02 kB {1} [built]
       [] -> factory:405ms building:365ms dependencies:1394ms = 2164ms
[./src/main/webapp/app/reducers/index.ts] ./src/main/webapp/app/reducers/index.ts 1.65 kB {1} [built]
       [] -> factory:1696ms building:418ms dependencies:2ms = 2116ms
   [0] multi react-hot-loader/patch ./src/main/webapp/app/index 40 bytes {1} [built]
        factory:0ms building:2ms = 2ms
[./src/main/webapp/app/shared/layout/header/header.tsx] ./src/main/webapp/app/shared/layout/header/header.tsx 9.62 kB {1} [built] [1 warning]
       [] -> factory:312ms building:812ms dependencies:457ms = 1581ms
[./src/main/webapp/app/shared/util/storage-util.ts] ./src/main/webapp/app/shared/util/storage-util.ts 2.55 kB {1} [built]
       [] -> factory:548ms building:229ms = 777ms
    + 1703 hidden modules

WARNING in ./src/main/webapp/app/shared/layout/header/header.tsx
[58, 98]: Multiple spaces found before ']'.

 @ ./src/main/webapp/app/app.tsx 20:15-55
 @ ./src/main/webapp/app/index.tsx
 @ multi react-hot-loader/patch ./src/main/webapp/app/index

ERROR in [at-loader] ./src/main/webapp/app/shared/layout/header/header.tsx:46:13
    TS2459: Type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>' has no property 'currentLocale' and no string index signature.

ERROR in [at-loader] ./src/main/webapp/app/shared/layout/header/header.tsx:46:28
    TS2459: Type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>' has no property 'isAuthenticated' and no string index signature.

ERROR in [at-loader] ./src/test/javascript/spec/app/shared/layout/header.spec.tsx:19:17
    TS2339: Property 'isAuthenticated' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Header> & Readonly<{ children?: ReactNode; }> & Re...'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by romainlouvet** [comment]
after `yarn start`

WARNING in ./src/main/webapp/app/shared/layout/header/header.tsx
[58, 98]: Multiple spaces found before ']'.

 @ ./src/main/webapp/app/app.tsx 20:15-55
 @ ./src/main/webapp/app/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server react-hot-loader/patch ./src/main/webapp/app/index

ERROR in [at-loader] ./src/main/webapp/app/shared/layout/header/header.tsx:46:13
    TS2459: Type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>' has no property 'currentLocale' and no string index signature.

ERROR in [at-loader] ./src/main/webapp/app/shared/layout/header/header.tsx:46:28
    TS2459: Type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>' has no property 'isAuthenticated' and no string index signature.

ERROR in [at-loader] ./src/test/javascript/spec/app/shared/layout/header.spec.tsx:19:17
    TS2339: Property 'isAuthenticated' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Header> & Readonly<{ children?: ReactNode; }> & Re...'.
webpack: Failed to compile

**Comment by mraible** [comment]
Please provide steps to reproduce. And include your `.yo-rc.json` file.

**Comment by romainlouvet** [comment]
Step to reproduce:

**Comment by romainlouvet** [comment]
my .yo-rc.json:

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "fr.mobileagri.fermetivoly"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "testJhipsterReact",
    "packageName": "fr.mobileagri.fermetivoly",
    "packageFolder": "fr/mobileagri/fermetivoly",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "e970ab0c6265e474bd7785352b3d60766cc38f2e",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

**Comment by pascalgrimaud** [comment]
It is because you set `enableTranslation` to `false`
I'm not sure it is support today. See https://github.com/jhipster/generator-jhipster/issues/6044

**Comment by jdubois** [comment]
No it's not supported.
I wrote it in the release notes, as this is **experimental** only default options work.
Help to code this is of course very welcome.
