### ISSUE TITLE
Logstash still does not working with kafka? 

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#6764]
##### **Overview of the issue**

My application run as a microservice, using UAA and kafka on all applications running on kubernetes cluster.

The only application that logs to the logstash and I can see in Kibana (jhipster-console) is the jhipster-registry.

Apparently, #6668 persists.

##### **JHipster Version(s)**

All the generated code was upgraded to 4.11.1

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
- are you sure you have the changes from https://github.com/jhipster/generator-jhipster/pull/6679 ?

**Comment by PierreBesson** [comment]
The initial problem only occurred when hot refreshing configuration. So this must be a configuration issue. Without a demo project recreating this issue I cannot help further.

**Comment by marcelinobadin** [comment]
Just for documentation and history purposes I did it work for me. @PierreBesson you were right. It was a configuration problem. What I did was to generate a docker-compose configuration and then I have did the adjustments on the kubernetes configuration. Thanks!
