### ISSUE TITLE
[Microservice + Keycloak] Make AuthorizationHeaderUtil safer

### ISSUE THREAD

**Issue by JohnnyCosta** [jhipster/generator-jhipster#6767]
##### **Overview of the issue**

The code on AuthorizationHeaderUtil may need more safe approach, I got a nullpoint exception.

##### **Motivation for or Use Case**
Internal Authentication, making one service call another
##### **Reproduce the error**
Call via feign an internal service
##### **Suggest a Fix**

I fixed with:
public class AuthorizationHeaderUtil {

    public static Optional<String> getAuthorizationHeader() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

        Object details = authentication.getDetails();
        if (details != null && details instanceof OAuth2AuthenticationDetails){
            OAuth2AuthenticationDetails oAuth2AuthenticationDetails =
                (OAuth2AuthenticationDetails) authentication.getDetails();
            return Optional.of(String.format("%s %s", oAuth2AuthenticationDetails.getTokenType(), oAuth2AuthenticationDetails.getTokenValue()));
        } else {
            return Optional.empty();
        }
    }
}

##### **JHipster Version(s)**
4.11.1

**Comment by jdubois** [comment]
LGTM, I'm doing this
