### ISSUE TITLE
[Feature Request] AWS Containerisation

### ISSUE THREAD

**Issue by ggotti** [jhipster/generator-jhipster#6773]
##### **Overview of the issue**
The existing JHipster AWS Deployment option uses Elastic Beanstalk, which is no longer being encouraged as the way of deploying applications to AWS. It's also still in Beta, and there are some reliability issues with the sub-generator in its current state.

Based on the recent announcements at AWS re:Invent, we’d like to modify the generator to support the following deployment options (instead of Elastic Beanstalk):
- [AWS Fargate](https://aws.amazon.com/blogs/aws/aws-fargate/) : Initially for Monolithic applications only, with the option to run databases as either containers, or as Amazon RDS.
- [AWS EKS](https://aws.amazon.com/eks/)) (when it becomes available): Initially for Microservices only. We’ll potentially want to extend the existing Kubernetes deployment option to make it more AWS-centric.

Our current thinking is to re-use the existing plugin interface and structure, but modify the deployment to leverage CloudFormation more extensively (similar to how the [Serverless Framework](https://serverless.com/framework/docs/providers/aws/guide/resources/)  does it)

I believe supporting a Docker-first paradigm will help standardise the JHipster deployment options, and make it easier to deploy moving forward. [carvallegro](https://github.com/carvallegro)  and myself ([ggotti](https://github.com/ggotti)) and will be working on this throughout December. We’ll update this ticket with more details as we progress. Any assistance would be appreciated :)

##### **Motivation for or Use Case**
- AWS is fairly dominant in the Australia market, and the lack of modern AWS integration is a serious issue.
- Move the AWS plugin out of Beta. We've discovered some reliability issues with the current implementation.

**Comment by deepu105** [comment]
You are welcome to do it :)

**Comment by ggotti** [comment]
Just a status update for those that are interested. Our branch is located in [this repository](https://github.com/carvallegro/generator-jhipster), and our development branch is feature/aws-generator, if you'd like to run it. The generator itself is currently called "more-aws"; we'll rename is later on, probably to something like aws-containers as a way to maintain compatibility with the existing aws generator. We're currently only focusing on the monolith version (using Fargate).

**Status**
We've got the majority of prompts working, and talking back to AWS for valid value entry.
- SpringCloud integration with Amazon SSM
- We have the Cloud Formation scripts being uploaded into new s3 buckets, passwords being stored in SSM, and docker client login.
- Streaming of Cloud Formation log to terminal.
- At a high level, the Cloud Formation is able to create the following:
  - Execution Role
  - ECR Registry
  - DBCluster (for Aurora)
  -  DBInstances
  -  ECS Task Definiton
  - ECS Cluster 
  - ECS Service
  - ALB for Target Application

**To Do** (when we come back to work in the new year):
- Build/Tag/Upload new Image to Amazon ECS Registry
- Update Cloud Formation stack to register and start the service.
- Tidy up the project scan functionality to behave more like the docker-compose generator.

**Current Issues** 
- Only works with Maria/Mysql with Aurora
- Generator currently does not work with Node 6.9.0.
- The execution role for the ECS Task is currently way too open (it has the logical name jhipsterRunRole  in the Cloud Formation yaml file). We need to lock it down but I haven't gone through the required permissions as yet.
