### ISSUE TITLE
SimpleAuthoritiesExtractor extracting to USER role

### ISSUE THREAD

**Issue by JohnnyCosta** [jhipster/generator-jhipster#6775]
##### **Overview of the issue**
This is happening with microservice and keycloak generated code.
Current code is using ROLE_USER when authentication does not belongs to an authority
##### **Motivation for or Use Case**
At least on my case I do not want any authentication to be defaulted to user
##### **Reproduce the error**
Login with an user without roles, then it will be USER.
##### **Suggest a Fix**
My suggestion is to use Anonymous role:
public class SimpleAuthoritiesExtractor implements AuthoritiesExtractor {

    private final String oauth2AuthoritiesAttribute;

    public SimpleAuthoritiesExtractor(String oauth2AuthoritiesAttribute) {
        this.oauth2AuthoritiesAttribute = oauth2AuthoritiesAttribute;
    }

    @Override
    public List<GrantedAuthority> extractAuthorities(Map<String, Object> map) {
        return Optional.ofNullable((List<String>) map.get(oauth2AuthoritiesAttribute))
            .filter(it -> !it.isEmpty())
            .orElse(Collections.singletonList(AuthoritiesConstants.ANONYMOUS))
            .stream()
            .map(role -> new SimpleGrantedAuthority(role))
            .collect(toList());
    }
}
##### **JHipster Version(s)**
4.11.1

**Comment by jdubois** [comment]
You are correct: this is quite bad, I don't understand why we give the user a role, when he doesn't have one!!

- I'm not sure you can use ANONYMOUS here, this is used by Spring Security when a user is not authenticated, which is not the case here. I would just don't give him any role at all (empty list).
- This needs to be tested, as I guess the person who did that had good intentions

**Comment by jdubois** [comment]
I just tested, and replacing it with an empty list, which looks more correct, works fine.
