### ISSUE TITLE
Exporting/importing a JDL file loses the "jpaMetamodelFiltering" property

### ISSUE THREAD

**Issue by netstart** [jhipster/generator-jhipster#6779]
I have a model with  "jpaMetamodelFiltering": true

When I export jdl (jhipster export-jdl model.jdl) after import the file generated (jhipster import-jdl model.jdl) I expected that the same code and  the same definitions in .jhipster\file.json. But it's not true  all files contem  "jpaMetamodelFiltering": false,
but the correct is  "jpaMetamodelFiltering": true

**Comment by jdubois** [comment]
I haven't tested, but this is a new property, so I guess the person who did that forgot to code it in the export sub-generator.

**Comment by MathieuAA** [comment]
I'll look into it

**Comment by MathieuAA** [comment]
@netstart please, next time, **do* follow our guidelines concerning how an issue is created! We need every bit of info we can so as to make sure your issue is solved ASAP.
Having said that, I need the version of the generator you're using.

**Comment by MathieuAA** [comment]
My bad! I've forgotten to add it to the exporting method. Fixing it, testing it and releasing a new patch version ASAP.

**Comment by pascalgrimaud** [comment]
fixed by https://github.com/jhipster/generator-jhipster/pull/6785
