### ISSUE TITLE
 JDL exporter  should not use byte[] for Blob types

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#6781]
##### **Overview of the issue**

I created an entity with one BLOB field using `jhipster entity Image`.
It created `.jhipster/Image.json` as below:

~~~json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "blob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "changelogDate": "20171130231749",
    "dto": "no",
    "service": "no",
    "entityTableName": "image",
    "jpaMetamodelFiltering": false,
    "pagination": "no"
}
~~~

Then I exported it as JDL  using `jhipster export-jdl` it created the file below:

~~~
// JDL definition for application 'blobJDL' generated with command 'jhipster export-jdl'

entity Image (image) {
    blob byte[]
  }
~~~
  
When I imported it back with `jhipster import-jdl`, it failed as below:

~~~
  An error has occurred:
          SyntaxError
  Error message:
          Expected ['\t'|' '| | ] or [A-Z] but "b" found.
  Position:
          At l.4.
  Error: SyntaxError: Expected ['\t'|' '| | ] or [A-Z] but "b" found.
  events.js:160
        throw er; // Unhandled 'error' event
        ^
  
  Error: ERROR!
  Error while parsing entities from JDL
  
      at Environment.error (e:\projets\jhipster-projects\issues\blobJDL\node_modules\yeoman-environment\lib\environment.js:157:40)
      at error (e:\projets\jhipster-projects\issues\blobJDL\node_modules\generator-jhipster\generators\generator-base.js:1964:18)
      at parseJDL (e:\projets\jhipster-projects\issues\blobJDL\node_modules\generator-jhipster\generators\import-jdl\index.js:113:26)
      at Object.<anonymous> (e:\projets\jhipster-projects\issues\blobJDL\node_modules\yeoman-generator\lib\index.js:399:25)
      at e:\projets\jhipster-projects\issues\blobJDL\node_modules\run-async\index.js:25:25
      at e:\projets\jhipster-projects\issues\blobJDL\node_modules\run-async\index.js:24:19
      at self.env.runLoop.add.completed (e:\projets\jhipster-projects\issues\blobJDL\node_modules\yeoman-generator\lib\index.js:400:11)
      at runCallback (timers.js:672:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)
~~~

I don't know if the problem is in the exporter or the importer.

##### **JHipster Version(s)**

```
blob-jdl@0.0.0 e:\projets\jhipster-projects\issues\blobJDL
`-- generator-jhipster@4.11.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "blobJDL",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.12.0.windows.1

node: v6.11.1

npm: 3.10.10

bower: 1.8.0

gulp:
[00:26:44] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.06.2-ce, build cec0b72

docker-compose version 1.14.0, build c7bdf9e3

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Yes, that's correct. Here's why:
  - `byte[]` doesn't start with a capitalized character, that's why you have this error
  - it's not supported as the following are the only supported Blob types (you can see them [here](https://github.com/jhipster/jhipster-core/blob/18b3eb3647d8ceb2c71e39e512b9212dbf5a2ea3/lib/parser/entity_parser.js#L206)):
    - `Blob`
    - `AnyBlob`
    - `TextBlob`
    - `ImageBlob`
  - these usual suspects do set the `fieldTypeBlobContent` values according to the type
    - `Blob` & `AnyBlob` -> `any`
    - `ImageBlob` -> `image`
    - `TextBlob` -> `text`
  - the `fieldType`, however, is set to `blob[]`, is it what you tried to achieve here?

**Comment by deepu105** [comment]
@gmarziou can we close it then?

**Comment by gmarziou** [comment]
No we can't close it as it means that the bug is in the exporter which should not write byte[] but rather one of the types that @MathieuAA  listed. As I explained I did not alter any generated code.

**Comment by deepu105** [comment]
Oh, ok sorry I dindt read the error report fully


Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
@gmarziou ah!! Now I understand!! Sorry, I'll fix it tonight.
