### ISSUE TITLE
Travis build is green even with some errors

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#6794]
##### **Overview of the issue**

It seems like there is an issue with travis build, there are quite a few `java` tests failing 

like this,

<img width="851" alt="screen shot 2017-12-03 at 23 16 22" src="https://user-images.githubusercontent.com/12471122/33530476-49685070-d880-11e7-83b2-154c768f0f67.png">

**Comment by cbornet** [comment]
I think it's normal : the test is here precisely to check that an error is thrown when a wrong reset key is sent.

**Comment by sendilkumarn** [comment]
Thanks. My bad. Let me close this 😁

**Comment by deepu105** [comment]
Arent they test meant to fail?


Thanks & Regards,
Deepu
