### ISSUE TITLE
Improve spring cache implementation

### ISSUE THREAD

**Issue by antarus** [jhipster/generator-jhipster#6796]
Hello,
 I would like to improve the cache support. For that I would like to add 'spring-boot-starter-cache' to dependencies, and give the possibility to the user to choose a cache system.
But before starting I have some questions.
Which default implementation do you want to use?
Spring cache offers the following services:
    - Generic
    - JCache (JSR-107) (EhCache 3, Hazelcast, Infinispan, etc.)
    - EhCache 2.x
    - Hazelcast
    - Infinispan
    - Couchbase
    - Redis
    - Caffeine
    - Guava (deprecated)
    - Simple
I have to add questions to configure the different implementations. if so which ones in priority?
It must be checked that the selected implementations do not collide with the selected hibernate cache.

I will take again the modifications made by erikkemperman https://github.com/jhipster/generator-jhipster/pull/6666

thanks

**Comment by jdubois** [comment]
- In fact we already support it, have a look at http://www.jhipster.tech/using-cache/
- What is bad, is that for historic reasons this is using a "hibernateCache" variable, and this is linked to our "2nd level Hibernate cache" questions, so it only works with SQL databases

-> we should keep what we already have, but refactor it

**Comment by antarus** [comment]
yes i know the cache is manage at some level in jhipster. The title of the issue should have been 'improve' and not add:)
I will try to look in more detail how refactor the 2nd level cache with spring-boot-starter-cache

**Comment by antarus** [comment]
I look at the impact of refactoring the variable 'hibernateCache', it's a big job ..
I propose to create a variable 'cache'.
If the 'hibernatecache' variable is set, then we set its value to the 'cache' variable.
If there is no database, or if the value of 'hibernatecache' is 'no', then we add a question. Would you like to use spring cache? y / n
Then, if the cache variable is filled (not 'no'), we copy the class CacheConfiguration.java and configure it.
I also propose to use the 'cache' variable instead of 'hibernateCache' for the gateway case as hazelcast is mandatory

This solution has the merit of not modifying everything, we remain consistent on the cache configuration for hibernate and we have another variable for the cache spring.

What do you think ?

**Comment by PierreBesson** [comment]
@antarus I think it's a very good Idea ! Very nice for no-db apps and clearer when your app actually does'nt have hibernate.

**Comment by antarus** [comment]
@erikkemperman @PierreBesson   
I made the modification of the cache variable, add the dependency spring start cache and start the configuration of the cache.
Thanks to @jdubois for referencing this issue it allowed me to see a problem.
In the persistentTokenRememberMeService class, that currently uses the guava cache, the changes to use spring cache should be just put caching annotation on processAutoLoginCookie method and remove references to upgradedTokenCache.
But, if in questions, we ask the user if he wants to use the cache, and he answers no, how do we store the token?

**Comment by jdubois** [comment]
For the variable name: the good thing with `hibernateCache` is that even if it's spread all around our code base, it's easy to do a search-and-replace:

- So migrating to something else should in fact be easy
- We never talked about this for other variables, but calling it `cache` will now make it very difficult to refactor. We should keep a "unique" name: how about `cacheImplementation`?

**Comment by antarus** [comment]
Yes search and replace is not complicated, but it has a lot of code impact. and given the number of PRs and current issue, I do not know if it's appropriate.
I will rename 'cache' to 'cacheImplementation', I will do the PR when coming home from work.

**Comment by deepu105** [comment]
@jdubois sorry I didn't know that you suggested `cacheImplementation` I suggested `cacheProvider` on the PR as its the term used by Spring and JCache for providers

**Comment by antarus** [comment]
If I need to replace hibernatecache everywhere, I can change to cacheProvider at the same time;)

**Comment by jdubois** [comment]
Oh yes +1 for cacheProvider

**Comment by antarus** [comment]
@jdubois @deepu105 
Ok, how do you want to name the configuration variable for hibernate second level cache?

**Comment by deepu105** [comment]
@antarus which config variable?

Ideally we should have only one variable called `cacheProvider` and use the same everywhere including for hibernateCache, why is another variable needed? may be im missing something

**Comment by antarus** [comment]
If you want to use the cache spring without configuring the cache hibernate for example

**Comment by deepu105** [comment]
sorry, i'm still lost, I guess its much better to look at code, just add a name you like and update the PR and ping me. I'll take a look and suggest if I see a room for improvement. Is that okay?

**Comment by antarus** [comment]
ok i do that and update when coming home from work.

**Comment by antarus** [comment]
I rename, locally, hibernateCache to CacheProvider.
Since the hibernateCache variable no longer exists, how do you manage the upgrade of an application that has hibernateCache in the yo.rc file?

**Comment by deepu105** [comment]
Thats easy while reading config you first look for `CacheProvider` and if its undefined you look for `hibernateCache` to set the value for cache

**Comment by deepu105** [comment]
If you still have doubt just do the remaining part of the PR and i'll guide you during review on how to do it

**Comment by erikkemperman** [comment]
@antarus Sorry I missed your pinging me on this issue... I have had some detailed [feedback](https://github.com/jhipster/generator-jhipster/issues/6648#issuecomment-349087792) from an expert (Caffeine principal author) on my little custom map implementation to use for persistent tokens, which I made to be able to get rid of Guava on my classpath.

If I understand it properly, the argument is that for this specific use-case (no need for multi-thread safety, and fixed expiration interval) the usual suspects available via Spring Cache might not be a great fit, and my custom bit might actually be quite appropriate.

@ben-manes I hope I do your remarks justice here, please correct me if not!

So just FYI, I am planning to improve #6666 taking Ben's remarks into account. Will probably wait until the mono-repo PR #6812 has landed so I can easily move the custom cache out of generated code and into the server-lib.

But, having said all that, if you guys don't think it's a good idea to have a custom cache for this very specific use case, please let me know and I won't waste time on it :-)

**Comment by antarus** [comment]
@erikkemperman 
I do not know what is the best. But, as we use spring cache for hibernate, adding the spring cache option for the application does not seem like a bad thing.
After about the cache to use (spring cache or your implementation) for the session cache, I will not say, I am not an expert: D
I still agree on removing guava!

**Comment by ben-manes** [comment]
I don’t know about the choice, other than that @erikkemperman’s implementation is reasonable and I doubt that Spring’s unbounded cache is the desired default if no provider was configured.

**Comment by jdubois** [comment]
Lots of discussion here, sorry I wasn't totally clear:

- Yes let's replace `hibernateCache` by `cacheProvider`
- We do use Spring Cache a little bit everywhere, and sometimes even without a database: have a look at our gateway+oidc+no database option, which doesn't have any database (so no Hibernate at all). It still uses Hazelcast, as gateways need Hazelcast to sync their rate limiting algorithm. So here having a `hibernateCache` variable really doesn't make any sense.
- Then, there is the question of using just Spring Cache, or Spring Cache + Hibernate, or just Hibernate... I would just mix those: let's use Spring Cache all the time (if you select a cache, this is always helpful), and if the user selects a SQL database, then he also has Hibernate L2 cache. This makes things so much simpler.
- I'm not sure if Caffeine can be used as a L2 Hibernate cache -> in that case, it would only be available if the user didn't select an SQL database
- HTTP Session clustering only works with Hazelcast -> this is a very annoying feature, so if we can keep it easily let's keep it, otherwise let's drop it.

**Comment by antarus** [comment]
PR update,

@jdubois,  I have just seen your message ...

I did not quite, did what you wanted ...

I replaced hibernateCache by cacheProvider
I added a question if we wanted to use spring cache.
If we use it, we ask if we want to configure the hibernate cache.
So I create an enableHibernateCache variable that is use at yaml spring file level

I find it nice to give the possibility to use spring cache without necessarily configure hibernate

If this does not suit you, I would correct;)

**Comment by ben-manes** [comment]
> I'm not sure if Caffeine can be used as a L2 Hibernate cache -> in that case, it would only be available if the user didn't select an SQL database

Hibernate does not want to add (maintain) new caching providers and the implementations appear complex, so providing it externally is an ordeal. Instead they now offer a JCache provider which should allow Caffeine to be used if the `caffeine-jcache` dependency is added.

**Comment by jdubois** [comment]
I'll test this more during the next week, that's awesome work @antarus !!
@ben-manes seeing your comment, I guess Caffeine doesn't work as an Hibernate L2 cache - not very nice of them, before they did their own implementation they were far more open about adding more providers :-(
BTW they also force to use Infinispan as the default cache, but my stats shows nobody wants to use it (less than 0,5% of our users during the last month).

**Comment by ben-manes** [comment]
@jdubois Is there a problem using the JCache L2 adapter, with Caffeine's JCache extension? It should work out of the box and support most of the features a native one might (since Caffeine is local only). It is also how Ehcache 3 integrates, though I'd guess that v2 is the most popular choice?

Infinispan swapped out their internal cache for Caffeine in v9, so technically Caffeine is the default too. :)

**Comment by pascalgrimaud** [comment]
I'm working on Travis builds and I noticed some change in the current master.
Here the possible options (current master):


**Monolith SQL**

Spring cache:
- ehcache <-- as default
- Hazelcast
- Infinispan
- No

Hibernate 2nd level cache: Y/n

**Monolith NoSQL (MongoDB, Cassandra, Couchbase)**

Spring cache:
- ehcache <-- as default, is it correct?
- Hazelcast
- Infinispan
- No

**Gateway SQL**:

Hazelcast is default.

Only this question:
Hibernate 2nd level cache: Y/n

Should we add the choice between Hazelcast and Infinispan?

**Gateway NoSQL**:

Hazelcast is default.

Should we add the choice between Hazelcast and Infinispan?

**Microservice SQL**:

Spring cache:
- ehcache
- Hazelcast <-- as default
- Infinispan
- No

Hibernate 2nd level cache: Y/n

**Microservice NoSQL**:

Spring cache:
- ehcache <-- is it correct?
- Hazelcast <-- as default
- Infinispan
- No

@jdubois @deepu105 @antarus : can you confirm the possible options ?
Sorry, I'm not an expert on Cache system, simply a user. So I need your input here to be sure our options are correct.

**Comment by deepu105** [comment]
I think the current options are correct. For gateway I guess Julien coded
the part to make hazelcast the default as its used to store the rate
limiting data. So not sure if it will work with Infinispan. But do you
think the behaviour is different from previous?

**Comment by pascalgrimaud** [comment]
Yes it's different. When you choose monolith and nosql database, you
couldn't select cache.
It is the behavior at v4.13.0 and current start.jhipster.tech


Le 17 déc. 2017 11:39 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
@pascalgrimaud yes that I know as now hibernate cache and cache is seperated so thats fine. I was asking about the behaviour in Gateway for cache selection

**Comment by pascalgrimaud** [comment]
The behaviour in Gateway is the same. As you said, it should be ok.
Thank you for answers Deepu.

**Comment by jdubois** [comment]
Just for the record (to be clear), here is the "old" behavior:

- Monoliths -> default is ehcache (as it's faster and easier, and the focus is not on scalability)
- Microservices & gateways -> default is Hazelcast (as the focus is on scalability)

Now that we can have a cache that isn't linked to Hibernate, we will need to discuss in the future:

- The default Spring Cache implementation when there is no Hibernate (for example with MongoDB) -> why not use Caffeine by default? At least for monoliths (with no scalability)
- When we want a distributed Spring Cache implementation and no Hibernate (= scalability) -> maybe Memcache would be a good solution. I'd love to use Memcache + MongoDB on Heroku, by the way.

**Comment by jdubois** [comment]
I found a few strange bugs coming from the PR -> I'm going to test & solve all of them, I will link my changes here, stay tuned :-)

**Comment by antarus** [comment]
Oops, what kind of bug?

**Comment by jdubois** [comment]
@antarus no worries, there was some @Cacheable missing, but it triggered some tests issues, that's interesting :-)

**Comment by pascalgrimaud** [comment]
I saw this morning a bug with a config: Cassandra and all other by default -> it will select ehcache, and it seems to not compile
Here the log: https://travis-ci.org/hipster-labs/jhipster-travis-build/jobs/318487922
