### ISSUE TITLE
Adding JWT token when using SERVER_API_URL 

### ISSUE THREAD

**Issue by koptan** [jhipster/generator-jhipster#6798]
##### **Overview of the issue**

In last few comments , SERVER_API_URL in webpack.common.js has been add , 
If we changed the URL to different server , there if statement in auth.interceptor.ts always returning True if there is word http in URL , and if the expression is True the JWT token is not been added to the request .

This is the expression : 
`  
if (!options || !options.url || /^http/.test(options.url)) {
            return options;
 }
`

##### **Reproduce the error**

Fill SERVER_API_URL  value in webpack.common.js

##### **Suggest a Fix**

Changing the expression to exclude any URL not start with  SERVER_API_URL 

##### **JHipster Version(s)**

4.10.2

##### **JHipster configuration**

```
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.Koptan",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "Muqeem",
    "packageName": "com.Koptan",
    "packageFolder": "com/Koptan",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mssql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly"
    ]
  }
}
</pre>
</details>
```

##### **Browsers and Operating System**

Chrome , Windows 10

**Comment by jdubois** [comment]
I guess this check is there as a security measure, to check that you send your authentication request to the same server as the one your front-end app is:

- Can someone confirm this?
- I guess you could log in if CORS is enabled on your server API, but then is that really a good idea to send credentials to another server?

**Comment by jdubois** [comment]
I'm closing this as this is indeed a security measure. You are of course free to remove it, but I wouldn't send my login credentials to another server.
