### ISSUE TITLE
LoggingConfiguration depends on Eureka

### ISSUE THREAD

**Issue by fhopf** [jhipster/generator-jhipster#6799]
##### **Overview of the issue**

Currently the LoggingConfiguration has @ConditionalOnProperty("eureka.client.enabled") annotation set which makes the configuration disabled without eureka. It would be good to have some parts enabled even if the registry is not active.

##### **Motivation for or Use Case**

There is a generated test that tests that the async appender is set. When running the tests with eureka disabled (which seems reasonable) this test will fail as the appender is not set.

##### **Reproduce the error**

Run the tests with eureka.client.enabled: false

##### **Suggest a Fix**

I'll provide a PR soon that uses Autowired(required=false) for the eureka instance id in this case instead but keeps the rest of the configuration enabled.

##### **JHipster Version(s)**

4.7.0

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@fhopf this depends on your config. Please follow our issue guidelines and provid ethe configuration else the ticket will be closed.

**Comment by fhopf** [comment]
JHipster Configuration

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.0 /Users/fhopf/projects/temp-jh-alt
└── generator-jhipster@4.11.1 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>




</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.15.0

node: v8.9.1

npm: 5.5.1

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

Congratulations, JHipster execution is complete!

**Comment by fhopf** [comment]
This is for the latest version checked out recently.
