### ISSUE TITLE
DTO getter does not have the same format as in toString

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6801]
##### **Overview of the issue**

When generating a DTO for an entity with an attributed called `m49`, the DTO gets a getter called `getm49()` (lowercase m) and the `toString` method refers to `getM49()` (uppercase M). So the code does not compile.

##### **Motivation for or Use Case**

Countries have a few codes such as ISO2, ISO3 or [M49](https://unstats.un.org/unsd/methodology/m49/). So when I model the entity as follow:

```
entity Country {
    iso2 String required maxlength(2),
    iso3 String required maxlength(3),
    m49 Integer required,
    name String required
}
```

[The entity gets generated ok](https://github.com/jhipster/generator-jhipster/issues/6005). But when I generate DTOs for Mapstruct, I get the following code : 

```
public class CountryDTO implements Serializable {

    @NotNull
    private Integer m49;

    public Integer getm49() {
        return m49;
    }

    @Override
    public String toString() {
        return "CountryDTO{" +
            "id=" + getId() +
            ", m49=" + getM49() +
            "}";
    }
```

##### **Reproduce the error**

Just generate an app with the following JDL:

```
entity Country {
    iso2 String required maxlength(2),
    iso3 String required maxlength(3),
    m49 Integer required,
    name String required
}

dto * with mapstruct
```

##### **Related issues**

* [Entity getter does not have the same format as in toString](https://github.com/jhipster/generator-jhipster/issues/6005)
* [Javabean methods not correct when several capital letters follow the first letter](https://github.com/jhipster/generator-jhipster/issues/5969)
* [using getter in equals() and hashcode() methods](https://github.com/jhipster/generator-jhipster/pull/5681)

##### **JHipster Version(s)**

```
bugdto@0.0.0 /Users/agoncal/Documents/Code/Temp/jhipster/bugdto
└── generator-jhipster@4.11.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.agoncal.bugdto"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "bugdto",
    "packageName": "org.agoncal.bugdto",
    "packageFolder": "org/agoncal/bugdto",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Country (country) {
  iso2 String required maxlength(2),
  iso3 String required maxlength(3),
  m49 Integer required,
  name String required
}

dto Country with mapstruct

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.15.0

node: v8.9.0

npm: 5.5.1

bower: 1.8.0

gulp:
[15:00:51] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
The fix should be very easy just replace the template on the toString with the same one used in getter
