### ISSUE TITLE
Add Docker image for Hazelcast management center

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6807]
Now that #6727 from @anjia0532 has been merged, let's add a Docker Compose configuration for Hazelcast management center:

https://hub.docker.com/r/hazelcast/management-center/

We shouldn't add this to our docker-compose sub-generator:

- This is proprietary software, and limited to 2 nodes, so for me the only real usage for us is development/testing
- People paying for it will probably have this running elsewhere, and won't want to use our Docker Compose configuration anyway

**Comment by anjia0532** [comment]
yup,It's not free.
