### ISSUE TITLE
Social login using Facebook don't works

### ISSUE THREAD

**Issue by netstart** [jhipster/generator-jhipster#6809]
##### **Overview of the issue**
After include client-id  client-secret  in application.yml
Social Login don´t works, I think the Angular code is incorret

Click in Account> Register> Facebok > Sign in with Facebook
It will open http://localhost:9000/signin/facebook

I think we dont have router to signin/facebook

##### **Reproduce the error**
Generate app using command jhipster app and below options:
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? yourapp
? What is your default Java package name? com.mycompany.myapp
? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
? Would you like to use Maven or Gradle for building the backend? Gradle
? Which other technologies would you like to use? Social login (Google, Facebook, Twitter)
? Which *Framework* would you like to use for the client? Angular 4
? Would you like to enable *SASS* support using the LibSass stylesheet preprocessor? (y/N)
? Would you like to enable *SASS* support using the LibSass stylesheet preprocessor? No
? Would you like to enable internationalization support? No
? Besides JUnit and Karma, which testing frameworks would you like to use? Gatling
? Would you like to install other generators from the JHipster Marketplace? No

##### **JHipster Version(s)**
generator-jhipster@4.11.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "monolito",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **Browsers and Operating System**
Windows 10
Chrome  62.0.3202.94 64 bits

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
where do you see `Cannot POST /signin/facebook`, is it in your browser console? Can you try using port 9060 instead of 9000? And if it still doesn't work, can you try with port 8080?

**Comment by netstart** [comment]
Ok, my bad, but I have other issue 

After execute command: gradlew
and open: http://localhost:8080/
Click in Account> Register> Facebok

![image](https://user-images.githubusercontent.com/200232/33616881-60eeacb2-d9c5-11e7-919a-c4d995174abd.png)

**Comment by jdubois** [comment]
That's because you need to generate your front-end before running Maven - with port 8080 it's not dynamic anymore.
So you can run `./mvnw -Pdev,webpack`

**Comment by ruddell** [comment]
Does your backend have any logs? There is also an issue with Facebook Login in Spring Social v2.

See https://github.com/jhipster/generator-jhipster/issues/5214 and [several workarounds]( https://stackoverflow.com/questions/39890885/error-message-is-12-bio-field-is-deprecated-for-versions-v2-8-and-higher)

**Comment by netstart** [comment]
OMG.... Sorry for my fault
That is it!
Thank you!

**Comment by jdubois** [comment]
Oh OK!
At least I'm happy to see that this works, as we can't test this easily (need a Facebook account, etc)

**Comment by netstart** [comment]
You will need to update the version of spring social
Using the atual version, 2.3.0 Release throw
`org.springframework.social.UncategorizedApiException: (#12) bio field is deprecated for versions v2.8 and higher`


In the spring-social-facebook have an issue about it https://github.com/spring-projects/spring-social-facebook/pull/218

**Comment by gmarziou** [comment]
spring social facebook 3.0.x requires Spring 5  and Spring Boot 2 which JHipster does not support yet.
