### ISSUE TITLE
Add the support of yarn in angularjs 1.5 jhipster app generation

### ISSUE THREAD

**Issue by aimad-majdou** [jhipster/generator-jhipster#6815]
**Overview of the issue**

As Bower support is dropping, and the bower team is recommending developers to move over to Yarn, it would be nice if the jhipster team add an option when installing jhipster (for angualrjs 1.x) to choose between Yarn or Bower.

**Related issues**

https://github.com/bower/bower/issues/2467

**Comment by deepu105** [comment]
We are planning to drop Angular 1.x in the future and hence there won't be any new feature additions to it at least from the core team. If this is important for you please do consider making a PR.

@jhipster/developers maybe its time to mark angular 1.x as Deprecated and may be later move it into a blueprint out of the main generator

**Comment by jdubois** [comment]
Indeed our AngularJS 1.x support is slowly dying.
We still have 10%-15% of people using it, but none of them are contributing, so at some point this will be the end...
The team is currently focusing on Angular 5 and React. In the future I hope we can also do VueJS. We just can't do everything, unless we have contributions of course.

**Comment by pascalgrimaud** [comment]
@deepu105 : I'm ok with you. So I will remove all Travis builds for Angular1. They are still tested but in our hipster-labs

**Comment by deepu105** [comment]
@pascalgrimaud my plan was to replace the ng1 builds with React as we finish each options.
