### ISSUE TITLE
Not all TypeScript services use SERVER_API_URL to prefix URL

### ISSUE THREAD

**Issue by thomastardy** [jhipster/generator-jhipster#6819]
##### **Overview of the issue**

Some TypeScript services don't use the constant SERVER_API_URL to prefix the URL. This means configuring it in webpack.common.js effects some services, but not all of them.

##### **Motivation for or Use Case**

Exposed configuration options should be used everywhere.

##### **Reproduce the error**

Generate app-ng2-default and look at audits.services.ts, configuration.service.ts, health.service.ts, logs.service.ts, metrics.service.ts.

##### **Related issues**

#6798, #6813

##### **Suggest a Fix**

Will submit a PR shortly.

##### **JHipster Version(s)**

```
travis-ng-2@0.0.0 /Users/tardy/Projects/jhipster/generator-jhipster/travis/samples/app-ng2-default-sample
└─┬ generator-jhipster@4.11.1  -> /Users/tardy/Projects/jhipster/generator-jhipster
  └── generator-jhipster@4.11.1  extraneous

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "baseName": "travisNg2",
    "packageName": "io.github.jhipster.travis",
    "packageFolder": "io/github/jhipster/travis",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "myPrefix",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "travis": true,
    "serviceDiscoveryType": false,
    "clientPackageManager": "yarn",
    "clientFramework": "angularX",
    "jhipsterVersion": "4.11.1",
    "jwtSecretKey": "replaced-by-jhipster-info"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount (BankAccount) {
  name String required,
  bankNumber Integer,
  agencyNumber Long,
  lastOperationDuration Float,
  meanOperationDuration Double,
  balance BigDecimal required,
  openingDay LocalDate,
  lastOperationDate Instant,
  active Boolean,
  accountType BankAccountType,
  attachment byte[],
  description byte[]
}
entity Label (Label) {
  labelName String required minlength(3)
}
entity Operation (Operation) {
  date Instant required,
  description String,
  amount BigDecimal required
}
entity FieldTestEntity (FieldTestEntity) {
  stringTom String,
  stringRequiredTom String required,
  stringMinlengthTom String minlength(0),
  stringMaxlengthTom String maxlength(20),
  stringPatternTom String pattern(^[a-zA-Z0-9]*$),
  integerTom Integer,
  integerRequiredTom Integer required,
  integerMinTom Integer min(0),
  integerMaxTom Integer max(100),
  longTom Long,
  longRequiredTom Long required,
  longMinTom Long min(0),
  longMaxTom Long max(100),
  floatTom Float,
  floatRequiredTom Float required,
  floatMinTom Float min(0),
  floatMaxTom Float max(100),
  doubleRequiredTom Double required,
  doubleMinTom Double min(0),
  doubleMaxTom Double max(100),
  bigDecimalRequiredTom BigDecimal required,
  bigDecimalMinTom BigDecimal min(0),
  bigDecimalMaxTom BigDecimal max(100),
  localDateTom LocalDate,
  localDateRequiredTom LocalDate required,
  instantTom Instant,
  instanteRequiredTom Instant required,
  zonedDateTimeTom ZonedDateTime,
  zonedDateTimeRequiredTom ZonedDateTime required,
  booleanTom Boolean,
  booleanRequiredTom Boolean required,
  enumTom EnumFieldClass,
  enumRequiredTom EnumRequiredFieldClass required,
  byteImageTom byte[],
  byteImageRequiredTom byte[] required,
  byteImageMinbytesTom byte[] minbytes(0),
  byteImageMaxbytesTom byte[] maxbytes(10000),
  byteAnyTom byte[],
  byteAnyRequiredTom byte[] required,
  byteAnyMinbytesTom byte[] minbytes(0),
  byteAnyMaxbytesTom byte[] maxbytes(10000),
  byteTextTom byte[],
  byteTextRequiredTom byte[] required,
  byteTextMinbytesTom byte[] minbytes(0),
  byteTextMaxbytesTom byte[] maxbytes(10000)
}
entity FieldTestPagerEntity (FieldTestPagerEntity) {
  stringJade String,
  stringRequiredJade String required,
  stringMinlengthJade String minlength(0),
  stringMaxlengthJade String maxlength(20),
  stringPatternJade String pattern(^[a-zA-Z0-9]*$),
  integerJade Integer,
  integerRequiredJade Integer required,
  integerMinJade Integer min(0),
  integerMaxJade Integer max(100),
  longJade Long,
  longRequiredJade Long required,
  longMinJade Long min(0),
  longMaxJade Long max(100),
  floatJade Float,
  floatRequiredJade Float required,
  floatMinJade Float min(0),
  floatMaxJade Float max(100),
  doubleRequiredJade Double required,
  doubleMinJade Double min(0),
  doubleMaxJade Double max(100),
  bigDecimalRequiredJade BigDecimal required,
  bigDecimalMinJade BigDecimal min(0),
  bigDecimalMaxJade BigDecimal max(100),
  localDateJade LocalDate,
  localDateRequiredJade LocalDate required,
  instantJade Instant,
  instanteRequiredJade Instant required,
  zonedDateTimeJade ZonedDateTime,
  zonedDateTimeRequiredJade ZonedDateTime required,
  booleanJade Boolean,
  booleanRequiredJade Boolean required,
  enumJade EnumFieldClass,
  enumRequiredJade EnumRequiredFieldClass required,
  byteImageJade byte[],
  byteImageRequiredJade byte[] required,
  byteImageMinbytesJade byte[] minbytes(0),
  byteImageMaxbytesJade byte[] maxbytes(10000),
  byteAnyJade byte[],
  byteAnyRequiredJade byte[] required,
  byteAnyMinbytesJade byte[] minbytes(0),
  byteAnyMaxbytesJade byte[] maxbytes(10000),
  byteTextJade byte[],
  byteTextRequiredJade byte[] required,
  byteTextMinbytesJade byte[] minbytes(0),
  byteTextMaxbytesJade byte[] maxbytes(10000)
}
entity FieldTestMapstructEntity (FieldTestMapstructEntity) {
  stringEva String,
  stringRequiredEva String required,
  stringMinlengthEva String minlength(0),
  stringMaxlengthEva String maxlength(20),
  stringPatternEva String pattern(^[a-zA-Z0-9]*$),
  integerEva Integer,
  integerRequiredEva Integer required,
  integerMinEva Integer min(0),
  integerMaxEva Integer max(100),
  longEva Long,
  longRequiredEva Long required,
  longMinEva Long min(0),
  longMaxEva Long max(100),
  floatEva Float,
  floatRequiredEva Float required,
  floatMinEva Float min(0),
  floatMaxEva Float max(100),
  doubleRequiredEva Double required,
  doubleMinEva Double min(0),
  doubleMaxEva Double max(100),
  bigDecimalRequiredEva BigDecimal required,
  bigDecimalMinEva BigDecimal min(0),
  bigDecimalMaxEva BigDecimal max(100),
  localDateEva LocalDate,
  localDateRequiredEva LocalDate required,
  instantEva Instant,
  instanteRequiredEva Instant required,
  zonedDateTimeEva ZonedDateTime,
  zonedDateTimeRequiredEva ZonedDateTime required,
  booleanEva Boolean,
  booleanRequiredEva Boolean required,
  enumEva EnumFieldClass,
  enumRequiredEva EnumRequiredFieldClass required,
  byteImageEva byte[],
  byteImageRequiredEva byte[] required,
  byteImageMinbytesEva byte[] minbytes(0),
  byteImageMaxbytesEva byte[] maxbytes(10000),
  byteAnyEva byte[],
  byteAnyRequiredEva byte[] required,
  byteAnyMinbytesEva byte[] minbytes(0),
  byteAnyMaxbytesEva byte[] maxbytes(10000),
  byteTextEva byte[],
  byteTextRequiredEva byte[] required,
  byteTextMinbytesEva byte[] minbytes(0),
  byteTextMaxbytesEva byte[] maxbytes(10000)
}
entity FieldTestServiceImplEntity (FieldTestServiceImplEntity) {
  stringMika String,
  stringRequiredMika String required,
  stringMinlengthMika String minlength(0),
  stringMaxlengthMika String maxlength(20),
  stringPatternMika String pattern(^[a-zA-Z0-9]*$),
  integerMika Integer,
  integerRequiredMika Integer required,
  integerMinMika Integer min(0),
  integerMaxMika Integer max(100),
  longMika Long,
  longRequiredMika Long required,
  longMinMika Long min(0),
  longMaxMika Long max(100),
  floatMika Float,
  floatRequiredMika Float required,
  floatMinMika Float min(0),
  floatMaxMika Float max(100),
  doubleRequiredMika Double required,
  doubleMinMika Double min(0),
  doubleMaxMika Double max(100),
  bigDecimalRequiredMika BigDecimal required,
  bigDecimalMinMika BigDecimal min(0),
  bigDecimalMaxMika BigDecimal max(100),
  localDateMika LocalDate,
  localDateRequiredMika LocalDate required,
  instantMika Instant,
  instanteRequiredMika Instant required,
  zonedDateTimeMika ZonedDateTime,
  zonedDateTimeRequiredMika ZonedDateTime required,
  booleanMika Boolean,
  booleanRequiredMika Boolean required,
  enumMika EnumFieldClass,
  enumRequiredMika EnumRequiredFieldClass required,
  byteImageMika byte[],
  byteImageRequiredMika byte[] required,
  byteImageMinbytesMika byte[] minbytes(0),
  byteImageMaxbytesMika byte[] maxbytes(10000),
  byteAnyMika byte[],
  byteAnyRequiredMika byte[] required,
  byteAnyMinbytesMika byte[] minbytes(0),
  byteAnyMaxbytesMika byte[] maxbytes(10000),
  byteTextMika byte[],
  byteTextRequiredMika byte[] required,
  byteTextMinbytesMika byte[] minbytes(0),
  byteTextMaxbytesMika byte[] maxbytes(10000)
}
entity FieldTestInfiniteScrollEntity (FieldTestInfiniteScrollEntity) {
  stringHugo String,
  stringRequiredHugo String required,
  stringMinlengthHugo String minlength(0),
  stringMaxlengthHugo String maxlength(20),
  stringPatternHugo String pattern(^[a-zA-Z0-9]*$),
  integerHugo Integer,
  integerRequiredHugo Integer required,
  integerMinHugo Integer min(0),
  integerMaxHugo Integer max(100),
  longHugo Long,
  longRequiredHugo Long required,
  longMinHugo Long min(0),
  longMaxHugo Long max(100),
  floatHugo Float,
  floatRequiredHugo Float required,
  floatMinHugo Float min(0),
  floatMaxHugo Float max(100),
  doubleRequiredHugo Double required,
  doubleMinHugo Double min(0),
  doubleMaxHugo Double max(100),
  bigDecimalRequiredHugo BigDecimal required,
  bigDecimalMinHugo BigDecimal min(0),
  bigDecimalMaxHugo BigDecimal max(100),
  localDateHugo LocalDate,
  localDateRequiredHugo LocalDate required,
  instantHugo Instant,
  instanteRequiredHugo Instant required,
  zonedDateTimeHugo ZonedDateTime,
  zonedDateTimeRequiredHugo ZonedDateTime required,
  booleanHugo Boolean,
  booleanRequiredHugo Boolean required,
  enumHugo EnumFieldClass,
  enumRequiredHugo EnumRequiredFieldClass required,
  byteImageHugo byte[],
  byteImageRequiredHugo byte[] required,
  byteImageMinbytesHugo byte[] minbytes(0),
  byteImageMaxbytesHugo byte[] maxbytes(10000),
  byteAnyHugo byte[],
  byteAnyRequiredHugo byte[] required,
  byteAnyMinbytesHugo byte[] minbytes(0),
  byteAnyMaxbytesHugo byte[] maxbytes(10000),
  byteTextHugo byte[],
  byteTextRequiredHugo byte[] required,
  byteTextMinbytesHugo byte[] minbytes(0),
  byteTextMaxbytesHugo byte[] maxbytes(10000)
}
entity FieldTestServiceClassEntity (FieldTestServiceClassEntity) {
  stringBob String,
  stringRequiredBob String required,
  stringMinlengthBob String minlength(0),
  stringMaxlengthBob String maxlength(20),
  stringPatternBob String pattern(^[a-zA-Z0-9]*$),
  integerBob Integer,
  integerRequiredBob Integer required,
  integerMinBob Integer min(0),
  integerMaxBob Integer max(100),
  longBob Long,
  longRequiredBob Long required,
  longMinBob Long min(0),
  longMaxBob Long max(100),
  floatBob Float,
  floatRequiredBob Float required,
  floatMinBob Float min(0),
  floatMaxBob Float max(100),
  doubleRequiredBob Double required,
  doubleMinBob Double min(0),
  doubleMaxBob Double max(100),
  bigDecimalRequiredBob BigDecimal required,
  bigDecimalMinBob BigDecimal min(0),
  bigDecimalMaxBob BigDecimal max(100),
  localDateBob LocalDate,
  localDateRequiredBob LocalDate required,
  instantBob Instant,
  instanteRequiredBob Instant required,
  zonedDateTimeBob ZonedDateTime,
  zonedDateTimeRequiredBob ZonedDateTime required,
  booleanBob Boolean,
  booleanRequiredBob Boolean required,
  enumBob EnumFieldClass,
  enumRequiredBob EnumRequiredFieldClass required,
  byteImageBob byte[],
  byteImageRequiredBob byte[] required,
  byteImageMinbytesBob byte[] minbytes(0),
  byteImageMaxbytesBob byte[] maxbytes(10000),
  byteAnyBob byte[],
  byteAnyRequiredBob byte[] required,
  byteAnyMinbytesBob byte[] minbytes(0),
  byteAnyMaxbytesBob byte[] maxbytes(10000),
  byteTextBob byte[],
  byteTextRequiredBob byte[] required,
  byteTextMinbytesBob byte[] minbytes(0),
  byteTextMaxbytesBob byte[] maxbytes(10000)
}
entity FieldTestPaginationEntity (FieldTestPaginationEntity) {
  stringAlice String,
  stringRequiredAlice String required,
  stringMinlengthAlice String minlength(0),
  stringMaxlengthAlice String maxlength(20),
  stringPatternAlice String pattern(^[a-zA-Z0-9]*$),
  integerAlice Integer,
  integerRequiredAlice Integer required,
  integerMinAlice Integer min(0),
  integerMaxAlice Integer max(100),
  longAlice Long,
  longRequiredAlice Long required,
  longMinAlice Long min(0),
  longMaxAlice Long max(100),
  floatAlice Float,
  floatRequiredAlice Float required,
  floatMinAlice Float min(0),
  floatMaxAlice Float max(100),
  doubleRequiredAlice Double required,
  doubleMinAlice Double min(0),
  doubleMaxAlice Double max(100),
  bigDecimalRequiredAlice BigDecimal required,
  bigDecimalMinAlice BigDecimal min(0),
  bigDecimalMaxAlice BigDecimal max(100),
  localDateAlice LocalDate,
  localDateRequiredAlice LocalDate required,
  instantAlice Instant,
  instanteRequiredAlice Instant required,
  zonedDateTimeAlice ZonedDateTime,
  zonedDateTimeRequiredAlice ZonedDateTime required,
  booleanAlice Boolean,
  booleanRequiredAlice Boolean required,
  enumAlice EnumFieldClass,
  enumRequiredAlice EnumRequiredFieldClass required,
  byteImageAlice byte[],
  byteImageRequiredAlice byte[] required,
  byteImageMinbytesAlice byte[] minbytes(0),
  byteImageMaxbytesAlice byte[] maxbytes(10000),
  byteAnyAlice byte[],
  byteAnyRequiredAlice byte[] required,
  byteAnyMinbytesAlice byte[] minbytes(0),
  byteAnyMaxbytesAlice byte[] maxbytes(10000),
  byteTextAlice byte[],
  byteTextRequiredAlice byte[] required,
  byteTextMinbytesAlice byte[] minbytes(0),
  byteTextMaxbytesAlice byte[] maxbytes(10000)
}
entity EntityWithDTO (entity_with_dto) {
  emma String
}
entity EntityWithServiceClass (entity_with_service_class) {
  zoe String
}
entity EntityWithServiceImpl (entity_with_service_impl) {
  clara String
}
entity EntityWithPagination (entity_with_pagination) {
  nathan String
}
entity EntityWithServiceClassAndPagination (entity_with_service_class_and_pagination) {
  enzo String
}
entity EntityWithServiceImplAndPagination (entity_with_service_impl_and_pagination) {
  hugo String
}
entity EntityWithServiceClassAndDTO (entity_with_service_class_and_dto) {
  lucas String
}
entity EntityWithServiceImplAndDTO (entity_with_service_impl_and_dto) {
  louis String
}
entity EntityWithPaginationAndDTO (entity_with_pagination_and_dto) {
  lea String
}
entity EntityWithServiceClassPaginationAndDTO (entity_with_service_class_pagination_and_dto) {
  lena String
}
entity EntityWithServiceImplPaginationAndDTO (entity_with_service_impl_pagination_and_dto) {
  theo String
}

enum BankAccountType {
  CHECKING,
  SAVINGS,
  LOAN
}

enum EnumFieldClass {
  ENUM_VALUE_1,
  ENUM_VALUE_2,
  ENUM_VALUE_3
}

enum EnumRequiredFieldClass {
  ENUM_VALUE_1,
  ENUM_VALUE_2,
  ENUM_VALUE_3
}

relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)}
}
relationship ManyToOne {
  BankAccount{user(login)} to User
}
relationship ManyToMany {
  Operation{label(labelName)} to Label{operation}
}

dto BankAccount, FieldTestMapstructEntity, EntityWithDTO, EntityWithServiceClassAndDTO, EntityWithServiceImplAndDTO, EntityWithPaginationAndDTO, EntityWithServiceClassPaginationAndDTO, EntityWithServiceImplPaginationAndDTO with mapstruct
service BankAccount, FieldTestServiceImplEntity, EntityWithServiceImpl, EntityWithServiceImplAndPagination, EntityWithServiceImplAndDTO, EntityWithServiceImplPaginationAndDTO with serviceImpl
angularSuffix BankAccount with mySuffix
paginate Label, FieldTestPaginationEntity, EntityWithPagination, EntityWithServiceClassAndPagination, EntityWithServiceImplAndPagination, EntityWithPaginationAndDTO, EntityWithServiceClassPaginationAndDTO, EntityWithServiceImplPaginationAndDTO with pagination
service Label, FieldTestServiceClassEntity, EntityWithServiceClass, EntityWithServiceClassAndPagination, EntityWithServiceClassAndDTO, EntityWithServiceClassPaginationAndDTO with serviceClass
paginate Operation, FieldTestInfiniteScrollEntity with infinite-scroll
paginate FieldTestPagerEntity with pager

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.15.0

node: v8.9.1

npm: 5.5.1

bower: 1.8.2

gulp:
[15:26:28] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

macOS High Sierra 10.13.1, Google Chrome 62.0.3202.94

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Oh, good catch!!!!
