### ISSUE TITLE
Required constraint for ManyToOne relationships

### ISSUE THREAD

**Issue by thilux** [jhipster/generator-jhipster#6835]
##### **Overview of the issue**

Using the jhipster JDL plugin for visual code, with the entities below, I am told by the plugin that required constraints are not allowed for ManyToOne relationships and Plant UML result confirms this.

```
entity Category {
  name String required
}

entity Post

relationship ManyToOne {
  Category{user required} to User,
  Post{category required} to Category
}
```

Basically:
    - every User can have none or multiple Categories and every Category must belong to a user.
    - every Category can have one or multiple Post and every Post must belong to a Category

Please note that OneToMany is not used instead because it only support bidirectional relationships and User cannot be modified (and I don't see the point in creating a separate table/model just for the relationship between User and Category).

##### **Motivation for or Use Case**

This is similar to issue [#1859](https://github.com/jhipster/generator-jhipster/issues/1859) but this time specific to the constraint on relationships.

If this is not possible through JDL then one is forced to set the relationship attribute as @NotNull directly on the domain entity and change the liquibase settings so that the relationship field is not nullable.

##### **JHipster Version(s)**

4.10.2

##### **JHipster configuration**

Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
minitodo@0.0.0 /Volumes/UData/Users/tsantana/Documents/study/jhipster/minitodo/minitodo
└── generator-jhipster@4.10.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.thilux.minitodo"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "minitodo",
    "packageName": "com.thilux.minitodo",
    "packageFolder": "com/thilux/minitodo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Category (category) {
  name String,
  description String,
  creationDate ZonedDateTime
}
entity TodoItem (todo_item) {
  name String,
  description String,
  creationDate ZonedDateTime,
  targetDate LocalDate,
  status TodoItemStatus,
  completionDate ZonedDateTime
}

enum TodoItemStatus {
  PENDING,
  COMPLETE,
  DELETED
}

relationship ManyToOne {
  Category{user} to User,
  TodoItem{category} to Category
}

dto Category, TodoItem with mapstruct
paginate Category with infinite-scroll
service Category, TodoItem with serviceImpl
angularSuffix Category, TodoItem with mySuffix
paginate TodoItem with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

git version 2.11.0 (Apple Git-81)

node: v8.9.0

npm: 5.5.1

bower: 1.7.9

gulp:
[23:27:14] CLI version 3.9.1

yeoman: 1.8.4

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

Congratulations, JHipster execution is complete!

[yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/1544250/yo-rc.json.txt)

**Comment by deepu105** [comment]
required relationship is supported only for many-to-one and owner side of many-to-many & one-to-one
To be frank I dont understand what your issue is, can you explain if you are facing an error or something if so please paste a stacktrace

**Comment by thilux** [comment]
Hi @deepu105 , as I mentioned in the original description, I'd like to be able to declare the "required" constraint on a ManyToOne relationship. I get no errors, I just can't get my model with the right constraint in the relationship.

In the example I provided before, the "user" attribute in the Category entity class is not marked @NotNull and in the corresponding liquibase the field user_id for the Category entity is marked "nullable=true". If the required constraint worked, it should be marked @NotNull in the entity class and "nullable=false" in the corresponding liquibase.

**Comment by deepu105** [comment]
@MathieuAA is this the correct usage of required for relationships?

**Comment by MathieuAA** [comment]
@deepu105 @thilux I don't see what's wrong here... I'm going to investigate right now.

**Comment by pascalgrimaud** [comment]
Maybe it concerns the plugin ?
> Using the jhipster JDL plugin for visual code

**Comment by MathieuAA** [comment]
@pascalgrimaud I don't know =/ I don't think it has this kind of power over the user's JDL, right?

**Comment by MathieuAA** [comment]
@pascalgrimaud You may be right.

**Comment by MathieuAA** [comment]
@deepu105 @pascalgrimaud considering the issue's nature, is this issue tracker the right place for such an issue?

**Comment by pascalgrimaud** [comment]
The few tests I did, everything works for me.
The last test I didn't do yet, is to install the plugin for VSCode -> if the issue comes from the plugin, the issue should be opened there
