### ISSUE TITLE
Missing locale data and UI issues

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#6836]
A freshly generated app causes some issues:

<img width="1270" alt="screen shot 2017-12-09 at 16 28 40" src="https://user-images.githubusercontent.com/766263/33796900-1a6e1f8e-dcfe-11e7-8bea-a934d5566de9.png">

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.12.0",
    "baseName": "jhi",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

git version 2.15.1

node: v6.12.1

npm: 5.5.1

bower: 1.8.0

gulp:
[16:25:51] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

**Comment by deepu105** [comment]
Did you run `mvn clean` while yarn start was running?
Ideally, you should run `yarn start` after `./mvnw`

**Comment by ctamisier** [comment]
It is what I did actually, I start the backend `./mvnw` and then the front-end `yarn start`. I will update it in the ticket as it is confusing.

**Comment by deepu105** [comment]
Ok i'm trying it

**Comment by pascalgrimaud** [comment]
I confirm the issue, I saw it this morning but didn't have time to open an issue.
It seems to be related to native language, when it's different from 'en'

**Comment by deepu105** [comment]
I confirm the issue. Happens when you go to user management page

**Comment by pascalgrimaud** [comment]
Some analyze:
- it works before the migration to Angular5: https://github.com/jhipster/generator-jhipster/pull/6789
- it seems to be related to date and locale, as it only happens when displaying date
- `<td>{{user.createdDate | date:'dd/MM/yy HH:mm'}}</td>` only works when it's `en`

**Comment by pascalgrimaud** [comment]
The only current solution I found is to use `en` instead of `nativeLanguage` at this line:
- https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/shared/_shared-libs.module.ts#L35

**Comment by ctamisier** [comment]
It works if we do this: https://angular.io/guide/i18n#i18n-pipes

like:
```
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';
[...]
export class JhiSharedCommonModule {
    constructor() {
        registerLocaleData(localeFr);
    }
}
```

**Comment by ctamisier** [comment]
should we have a patch release ? this affects all JHipster apps having something else than English as native language.

**Comment by jdubois** [comment]
Sorry I didn't follow closely enough -> if we need a release I can do it on Wednesday

**Comment by pascalgrimaud** [comment]
Closing this, as the PR was merged
