### ISSUE TITLE
UAA manual recommends using "password" code grant, which is insecure for pure web clients

### ISSUE THREAD

**Issue by pragmasoft-ua** [jhipster/generator-jhipster#6859]
[UAA Manual](http://www.jhipster.tech/using-uaa/#oauth2) mentions:

> A “client” is a abstract word for things like “AngularJS $http client”, some “REST-Client”, “curl”, or anything able to perform requests.
...
> Clients accessing resources with user authentication, are authenticated using “password grant”

According to Oauth [specification](https://tools.ietf.org/html/rfc6749#section-4.2), pure web clients, like AngularJS apps, need to use "implicit" grant type instead, because they cannot securely store client secret, needed for "password" grant type

**Comment by mraible** [comment]
You are correct that OAuth does not recommend the password grant type. In fact, the only reason it exists is for legacy clients (like desktop apps). This is one of the reasons I rewrote our OAuth support. We were using a secret in the client, which is an even bigger no no.

**Comment by ruddell** [comment]
Those docs are a bit out of date since the UAA Refresh Token PR https://github.com/jhipster/generator-jhipster/pull/5812.  The UAA still uses the password grant type, but the clientId/clientSecret are now in the gateway (instead of the Angular client).  It also uses cookies and automatically handles refresh tokens, both of which the docs don't mention.

**Comment by pragmasoft-ua** [comment]
Would appreciate if you update documentation, as my developers implemented it this way, according to documentation, it's luckily I noticed it during the code review

**Comment by jdubois** [comment]
Yes thanks @pragmasoft-ua for reporting the issue - unfortunately I don't know this well enough, who can update the doc @ruddell @mraible @xetys ? Maybe even you @pragmasoft-ua ?

**Comment by ruddell** [comment]
I can read through it this weekend and update the sections I'm familiar with
