### ISSUE TITLE
Angular CLI 1.6 global clashes with the 1.5.5 local

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6861]
##### **Overview of the issue**

JHipster 4.12 uses Angular CLI 1.5.5, but if you have Angular CLI 1.6 installed globally, you can't use NG CLI commands.

##### **Motivation for or Use Case**

This is a known [Angular CLI issue](https://github.com/angular/angular-cli/issues/8782) and it is still opened. If you have Angular CLI 1.6 installed globally, you will not be able to use NG Cli in your JHipster project, except if you remove the local 1.5.5

##### **Reproduce the error**

Generate a JHipster project (any one), and then enter a NG command (eg. `ng generate component dummy`). You will get:

```
input.mergeMap is not a function
TypeError: input.mergeMap is not a function
    at Object.callRule (/Users/agoncal/Documents/Code/Quantixx/demo-keycloak/gateway/node_modules/@angular-devkit/schematics/src/rules/call.js:70:18)
    at SchematicImpl.call (/Users/agoncal/Documents/Code/Quantixx/demo-keycloak/gateway/node_modules/@angular-devkit/schematics/src/engine/schematic.js:35:23)
    at Promise (/Users/agoncal/Documents/Code/Quantixx/demo-keycloak/gateway/node_modules/@angular/cli/tasks/schematic-run.js:73:23)
    at new Promise (<anonymous>)
    at Class.run (/Users/agoncal/Documents/Code/Quantixx/demo-keycloak/gateway/node_modules/@angular/cli/tasks/schematic-run.js:72:16)
    at Class.run (/Users/agoncal/Documents/Code/Quantixx/demo-keycloak/gateway/node_modules/@angular/cli/commands/generate.js:152:33)
    at resolve (/Users/agoncal/Documents/Code/Quantixx/demo-keycloak/gateway/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (/Users/agoncal/Documents/Code/Quantixx/demo-keycloak/gateway/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/Users/agoncal/Documents/Code/Quantixx/demo-keycloak/gateway/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)
```

##### **Related issues**

* https://github.com/angular/angular-cli/issues/8782

##### **Suggest a Fix**

As stated in the [Angluar CLI issue](https://github.com/angular/angular-cli/issues/8782), I've tried upgrading `@angular-devkit/schematics: 0.0.41` but it didn't work out for me.

Removing Angular CLI 1.5.5 locally solved the problem `yarn remove @angular/cli`

##### **JHipster Version(s)**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/agoncal/Documents/Code/Quantixx/demo-keycloak/gateway
├── generator-jhipster@4.12.0 
└─┬ generator-jhipster-swagger-cli@2.0.5
  └── generator-jhipster@4.12.0  deduped

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.demo.gateway",
      "microservicePath": "/Users/zouheircadi/Documents/devhome/devoxx-tools/demo-keycloak/book-api/"
    },
    "jhipsterVersion": "4.12.0",
    "baseName": "gateway",
    "packageName": "org.demo.gateway",
    "packageFolder": "org/demo/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-swagger-cli",
        "version": "2.0.5"
      }
    ],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.15.0

node: v8.9.0

npm: 5.5.1

bower: 1.8.0

gulp:
[16:15:01] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.1-ce, build 19e2cf6

docker-compose version 1.17.1, build 6d101fb

Congratulations, JHipster execution is complete!

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by agoncal** [comment]
I've created this issue to help other people if they have the same problem. But I'm not sure what the JHipster can do about it.

**Comment by deepu105** [comment]
We already upgraded to Angular CLI 1.6.0 in the package.json. Can you test the master branch please

**Comment by jdubois** [comment]
@deepu105 I tested and I have the same error

**Comment by deepu105** [comment]
On master? but that doesn't make sense coz both should then be the same version right?

**Comment by jdubois** [comment]
Yes on master.... I'm testing removing my globally installed Angular CLI

**Comment by deepu105** [comment]
I hope you tried the following, I dont have time now to try but can do later
1. Keep your global CLI version to > 1.5
2. Generate a fresh project, without existing node_modules or yarn lock file
3. Try ng commands
4. Remove angular cli locally and try ng commands

**Comment by agoncal** [comment]
It's working with the master. I have ng cli 1.6 globally and now with 1.6 locally. 


##### **JHipster Version(s)**

```
temp@0.0.0 /Users/agoncal/Documents/Code/JHipster/temp
└─┬ generator-jhipster@4.12.0  -> /Users/agoncal/Documents/Code/JHipster/generator-jhipster
  └── generator-jhipster@4.12.0  extraneous

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.agoncal.bugngcli"
    },
    "jhipsterVersion": "4.12.0",
    "baseName": "temp",
    "packageName": "org.agoncal.bugngcli",
    "packageFolder": "org/agoncal/bugngcli",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>




</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.15.0

node: v8.9.0

npm: 5.5.1

bower: 1.8.0

gulp:
[16:37:10] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.1-ce, build 19e2cf6

docker-compose version 1.17.1, build 6d101fb

Congratulations, JHipster execution is complete!

**Comment by deepu105** [comment]
@jdubois can we close it then?

**Comment by jdubois** [comment]
I still can't make it work, but I'm lost with Yarn and Angular CLI - I just never use it... If it works for @agoncal it should be good - does it work for you @deepu105 ?

**Comment by jdubois** [comment]
OK let's trust @agoncal - after all he's the one who opened up the ticket!

**Comment by matiishyn** [comment]
tried all mentioned solutions but doesn't work for me.
I have the latest versions of CLI and TS both locally and globally. Removing `node_modules` and installing it doesn't help. Removing `package-lock.json` doesn't help either.

Any other variants?
