### ISSUE TITLE
ERROR Error: Missing locale data for the locale "zh-cn"

### ISSUE THREAD

**Issue by ku2madman** [jhipster/generator-jhipster#6863]
##### **Overview of the issue**
After generated gateway, get error message in chrome:
JhiMetricsMonitoringComponent.html:1 ERROR Error: Missing locale data for the locale "zh-cn".
    at findLocaleData (common.js?5e3c:1475)
    at getLocaleNumberFormat (common.js?5e3c:1318)
    at formatNumber$1 (common.js?5e3c:4913)
    at DecimalPipe.transform (common.js?5e3c:6020)
    at checkAndUpdatePureExpressionInline (core.js?593e:12900)
    at checkAndUpdateNodeInline (core.js?593e:13603)
    at checkAndUpdateNode (core.js?593e:13542)
    at debugCheckAndUpdateNode (core.js?593e:14414)
    at debugCheckRenderNodeFn (core.js?593e:14393)
at Object.eval [as updateRenderer] (JhiMetricsMonitoringComponent.html:1)

##### **Reproduce the error**

start kafka and jhipster registry
start gateway
click administration -> metrics

##### **Suggest a Fix**

https://stackoverflow.com/questions/46564972/angular-5-breaking-change-manually-import-locale

##### **JHipster Version(s)**

4.12.0

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/JHipster/xxx/gateway
└── generator-jhipster@4.12.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.xxx.gateway",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "4.12.0",
    "baseName": "gateway",
    "packageName": "com.xxx.gateway",
    "packageFolder": "com/xxx/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

git version 2.14.3 (Apple Git-98)

node: v8.0.0

npm: 5.5.1

bower: 1.8.0

gulp:
[12:49:43] CLI version 3.9.1

yeoman: 2.0.0

yarn: 0.24.5

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Sierra & Chrome

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Thanks for reporting issue, but it has already been reported here https://github.com/jhipster/generator-jhipster/issues/6836

Here the fix https://github.com/jhipster/generator-jhipster/pull/6843

**Comment by jdubois** [comment]
Yes, I should do a release with the fix this afternoon

**Comment by lovelytong** [comment]
if you use angular-cli, plz  try this:
open file :main.ts
add code:`import { registerLocaleData } from '@angular/common';
import zh from '@angular/common/locales/zh';
registerLocaleData(zh);`

**Comment by PierreBesson** [comment]
@lovelytong Please don't comment on an old issue, if you have a feature request please open a new issue with explanations in ordre to start a discussion.

**Comment by colordove** [comment]
> if you use angular-cli, plz try this:
> open file :main.ts
> add code:
> `import { registerLocaleData } from '@angular/common'; import zh from '@angular/common/locales/zh'; registerLocaleData(zh);`

Thanks for your comment, it works for me.

**Comment by webcrack4** [comment]
> if you use angular-cli, plz try this:
> open file :main.ts
> add code:
> `import { registerLocaleData } from '@angular/common'; import zh from '@angular/common/locales/zh'; registerLocaleData(zh);`

It works, thank you
