### ISSUE TITLE
Problem with Mapper bean while creating entities.

### ISSUE THREAD

**Issue by devMaheshJava** [jhipster/generator-jhipster#6865]
##### **Overview of the issue**

I'm getting started with jHipster4.
And I'm following the demo of @mraible 
**the demo link is** :: [https://github.com/mraible/jhipster4-demo](url)
Everything is fine before adding entities.
I changed the default Oracle 12c to Oracle 11g.(Runs fine)

After adding new Entities as it is below I got errors and application failed to start.
`
<tt>
entity Blog {
	name String required minlength(3),
	handle String required minlength(2)
}

entity Entrie {
	title String required,
	content TextBlob required,
	date ZonedDateTime required
}

entity Tag {
	name String required minlength(2)
}

relationship ManyToOne {
	Blog{user(login)} to User,
	Entrie{blog(name)} to Blog
}

relationship ManyToMany {
	Entrie{tag(name)} to Tag{entrie}
}

paginate Entrie, Tag with infinite-scroll

dto * with mapstruct

// Set service options to all except few
service all with serviceImpl 
// Set an angular suffix
angularSuffix * with mySuffix
</tt>`
The console showing this:
<kbd>
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in com.bil.service.impl.BlogServiceImpl required a bean of type 'com.bil.service.mapper.BlogMapper' that could not be found.

Action:

Consider defining a bean of type 'com.bil.service.mapper.BlogMapper' in your configuration.
</kbd>

##### **Motivation for or Use Case**

I tried to add entities .
##### **Reproduce the error**

`
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in com.bil.service.impl.BlogServiceImpl required a bean of type 'com.bil.service.mapper.BlogMapper' that could not be found.

Action:

Consider defining a bean of type 'com.bil.service.mapper.BlogMapper' in your configuration.
`
##### **JHipster Version(s)**

jHipster4
##### **JHipster configuration**
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
blog@0.0.0 D:\springWorkspace\blog
`-- generator-jhipster@4.12.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.bil"
    },
    "jhipsterVersion": "4.12.0",
    "baseName": "blog",
    "packageName": "com.bil",
    "packageFolder": "com/bil",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog (blog) {
  name String required minlength(3),
  handle String required minlength(2)
}
entity Entrie (entrie) {
  title String required,
  content TextBlob required,
  date ZonedDateTime required
}
entity Tag (tag) {
  name String required minlength(2)
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Entrie{blog(name)} to Blog
}
relationship ManyToMany {
  Entrie{tag(name)} to Tag{entrie}
}

dto Blog, Entrie, Tag with mapstruct
service Blog, Entrie, Tag with serviceImpl
angularSuffix Blog, Entrie, Tag with mySuffix
paginate Entrie, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.15.1.windows.2

node: v8.9.3

npm: 5.6.0

bower: 1.8.2

gulp:
[20:36:17] CLI version 3.9.1
[20:36:17] Local version 3.9.1

yeoman: 2.0.0

yarn: 1.3.2

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<div class="panel panel-default">
      <div class="panel-heading">Blog.json</div>
      <div class="panel-body"><pre>
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "login"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": 3
        },
        {
            "fieldName": "handle",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": 2
        }
    ],
    "changelogDate": "20171214121010",
    "entityTableName": "blog",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "angularJSSuffix": "mySuffix"
}
</pre></div>
    </div>
<div class="panel panel-default">
      <div class="panel-heading">Entrie.json</div>
      <div class="panel-body">
<pre>{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "blog",
            "otherEntityName": "blog",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "entrie",
            "relationshipName": "tag",
            "otherEntityName": "tag",
            "otherEntityField": "name",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "content",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "date",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20171214121011",
    "entityTableName": "entrie",
    "dto": "mapstruct",
    "pagination": "infinite-scroll",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "angularJSSuffix": "mySuffix"
}</pre>
</div>
    </div>
 <div class="panel panel-default">
      <div class="panel-heading">Tag.json</div>
      <div class="panel-body"><pre>
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "relationshipName": "entrie",
            "otherEntityName": "entrie",
            "ownerSide": false,
            "otherEntityRelationshipName": "tag"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": 2
        }
    ],
    "changelogDate": "20171214121012",
    "entityTableName": "tag",
    "dto": "mapstruct",
    "pagination": "infinite-scroll",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "angularJSSuffix": "mySuffix"
}
</pre></div>
    </div>
##### **Browsers and Operating System**

**OS:** WINDOWS 10
**BROWSERS:** Chrome,Mozilla 
- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by devMaheshJava** [comment]
@erikkemperman , @jdubois 
Please see this issue

**Comment by jdubois** [comment]
That's because you use MapStruct, which is still in BETA, largely because you need to configure your IDE.
Have a look at the doc and at the old issues, lots of stuff on this already.

**Comment by jdubois** [comment]
I'm closing this because this is a configuration issue in your IDE.

**Comment by devMaheshJava** [comment]
jdubois thanks for your response

**Comment by jdubois** [comment]
@devMaheshJava have a look at http://www.jhipster.tech/configuring-ide-eclipse/ and the "Maven IDE profile"

**Comment by devMaheshJava** [comment]
Thanks again **Mr.Julien Dubois**
