### ISSUE TITLE
Incorrect JhiTrackerService is being imported in test module

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#6869]
##### **Overview of the issue**

If app is generated with custom prefix, technically with `jhiPrefix`, `yarn start` is failing.

##### **Motivation for or Use Case**

While the `XXXXXTrackerService` is generated using `<%=jhiPrefixCapitalized%>TrackerService`, in `test.module.ts` it is not being imported as `<%=jhiPrefixCapitalized%>TrackerService` but rather as `JhiTrackerService`.

##### **Reproduce the error**

1. Generate an app with default settings.
2. Modify `jhiPrefix` in `.yo-rc.json` and regenerate app.
3. `yarn start`

##### **Related issues**
-

##### **Suggest a Fix**

The import should be  `<%=jhiPrefixCapitalized%>TrackerService` in `test.module.ts`

##### **JHipster Version(s)**
4.13.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.tutorials",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.0",
    "baseName": "tutorials",
    "packageName": "com.tutorials",
    "packageFolder": "com/tutorials",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "tutorials",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi"
    ]
  }
}
</pre>
</details>

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Would you consider doing a PR to fix this


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
@pascalgrimaud we have a websocket build in travis right, may be we should add a prefix for all travis builds so that these cases are checked
