### ISSUE TITLE
if generating entity client in gateway for microservices entity then entity .json file is not created

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#6871]
##### **Overview of the issue**

Starting from JHipster version 4.11.0 entity .json file is not generated if generating front-end in gateway for entity which back-end is in microservice.  
JHipster version 4.10.2 generates entity .json file in gateway.

##### **Motivation for or Use Case**

Missing entity .json file in gateway causes some problems, for example if regenerating project with `--with-entities` flag then entities are not regenerated and references to the entity are deleted from general files (for example from navbar).

##### **Reproduce the error**

1. create microservice: `jhipster`
2. add entity to microservice: `jhipster entity MyEntity`
3. create gateway: `jhipster`
4. generate front-end for entity declared in microservice: `jhipster entity MyEntity`
 - answer "Yes" to "Do you want to generate this entity from an existing microservice?"
 - enter microservice path
 - choose "Yes, re generate the entity"

##### **Suggest a Fix**

Seems that this comes from https://github.com/jhipster/generator-jhipster/commit/6cab1fb  
Seems that previously `saveRemoteEntityPath` was executed both in client side and server side generation, but after this change only in server side generation.

##### **JHipster Version(s)**

```
ms@0.0.0 C:\projects\teest\ms
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.0",
    "baseName": "ms",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity MyEntity (my_entity) {
  field1 String
}

microservice MyEntity with ms

</pre>
</details>

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en",
      "microservicePath": "..\\ms"
    },
    "jhipsterVersion": "4.13.0",
    "baseName": "gw",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.7.0.windows.1

node: v8.9.3

npm: 4.1.2

bower: 1.8.0

gulp:
[14:02:09] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.1-ce, build 19e2cf6

docker-compose version 1.17.1, build 6d101fb0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
That's expected behavior as the json will reside in the actual microservice and gateway should read from there. When you regenerate I guess the issue is it doesn't read from the microservice so the real issue will be that.

**Comment by kaidohallik** [comment]
Some notes:
1. If there is no entity .json in gateway then all source information is lost and impossible to regenerate.
2. If answer to question `Do you want to update the entity? This will replace the existing files for this entity, all your custom code will be overwritten (Use arrow keys)` is from list below:

* `Yes, add more fields and relationships`
* `Yes, remove fields and relationships`

then .json file is generated and it becomes different from .json in microservice.

Some possible alternative solutions for use case **gateway is using entity from microservice**:

1. entity .json contains path to microservice, like:
```
{
    "microservicePath": "PathToMicroservice"
}
```
and gateway generator loads entity .json from that path  
it seems bad idea, if microservice path changes then must modify .json before regeneration and if microservice is not available then can't regenerate at all

2. entity .json in gateway is copy of entity .json in microservice, after generating new version of .json in microservice must generate new .json also in gateway, generator asks only for microservice path from where to copy .json

Current version is in general usable. If you know how it behaves then you can handle that. This is not obvious bug. So I'm closing this.

**Comment by deepu105** [comment]
Seems like docs can be improved to explain this better. Would you like to
contribute a PR for docs?

**Comment by ruddell** [comment]
@deepu105 Can we revert to the previous behavior? In previous versions, the gateway saved a copy of the entity's JSON in its `.jhipster` folder.  We don't store microservice paths, so we can't reference the JSON files from another project automatically.

Without the copy in the gateway, the `--with-entities` flag is useless and the entity UI will never upgrade with `jhipster upgrade` (which could lead to incompatibilities with the back end)

**Comment by deepu105** [comment]
Oh, If it was the previous behaviour then I didn't change anything and may
be there is some bug here

**Comment by kaidohallik** [comment]
@deepu105 Problem is: function `saveRemoteEntityPath` must be in entity-client instead of entity-server. This change restores previous behaviour.

**Comment by deepu105** [comment]
probably it needs to be moved to the entity sub gen itself


Thanks & Regards,
Deepu

**Comment by kaidohallik** [comment]
Both versions are working, moving this to entity or entity-client.  
`saveRemoteEntityPath` can be in entity-client because this function is doing something only if in gateway generating client for entity in microservice.
