### ISSUE TITLE
[Feature Request] Subset of REST methods

### ISSUE THREAD

**Issue by mtdx** [jhipster/generator-jhipster#6874]
**Overview of the issue**

Now if you need just a subset of the all rest method, you need to comment quite a lot of text, back-end, tests, front-end, and you can't afford any mistakes, let's say you have a transactions entity that are added internally, forgetting to comment out post/put would be very bad, also if you regenerate the entity the code will be uncommented.  

**Motivation for or Use Case**

I think the need for "partial" entities is common enough, and should not be hard to implement, eg. add a flag -get, -post, -put otherwise it defaults to all.

In my experience with Jhipster, I rarely had entities where I needed the full suite, sometimes I don't even need the get all, as in `user settings`, but other common examples would be, transactions, invoices,  notifications,  orders, deposits, withdraws, payments (you don't want to let the user DELETE, PUT these) etc.

**Comment by deepu105** [comment]
i dont think this will be high on our todo list, if you wish you can try to implement this as PR

**Comment by cbornet** [comment]
It’s always possible to hide some endpoints using permissions

**Comment by gmarziou** [comment]
Right @cbornet but maybe it would help if JHipster supported high level roles combining low level permissions per entity. Though it would not be easily transposed in client code.

**Comment by pascalgrimaud** [comment]
JHipster provides the CRUD on an entity.
From my understand, you want to mixte and not provide full CRUD, for example:
- CD
- RD
- only C
- only D
etc.

From my point of view, it would be hard to test all possible options and provide a correct UI for the user.
It is far easier to comment or delete the part you don't need, and keep this in a Git patch, so you can reapply the fix after regenerating the entiy.

**Comment by gmarziou** [comment]
Maybe we could [apply CQRS](http://www.baeldung.com/cqrs-for-a-spring-rest-api) and so it would be easier to manage permissions

**Comment by jdubois** [comment]
- If that's just deleting or securing one method, then that would be against [Policy 2](http://www.jhipster.tech/policies/)
- Today you have 2 options: either use the "entity" sub-generator and have a full CRUD, that you should customize, or use the "spring-controller" sub-generator (maybe with Angular CLI) and code the rest manually. There could be a middle-ground, but as @pascalgrimaud said it's going to be a nightmare to test - we just don't have the bandwidth for this.
- For the reason above (too much work to test & maintenance would be a nightmare), I'm even against a PR for this, as we would then get all the maintenance cost.

**Comment by deepu105** [comment]
Ok then lets close this


Thanks & Regards,
Deepu
