### ISSUE TITLE
Infinite loop of 401 exceptions

### ISSUE THREAD

**Issue by wpanas** [jhipster/generator-jhipster#6882]
##### **Overview of the issue**

When using UAA, the AuthExpiredInterceptor cause infinite loop of 401 exceptions. It occurs when user is logged out by the server, but the client doesn't know about it. The interceptor catches a 401 exception and then sends a logout call to the server and it causes another 401 exception.

##### **Motivation for or Use Case**

It completely crashes browser, when it happens.

##### **Reproduce the error**

Open client in two tabs and login in one of them. Refresh the other and then logout from it. Go back to the first and try to go to any site that's requires authorization.

##### **Related issues**

I searched, but I haven't found any.

##### **Suggest a Fix**

I can fix it myself. I managed to do this in my own repo.

##### **JHipster Version(s)**

I used 4.10.2 in that project, but I've checked and 4.13.0 has the same problem.

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "pl.logihome.gateway",
      "nativeLanguage": "pl",
      "microservicePath": "../data"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "gateway",
    "packageName": "pl.logihome.gateway",
    "packageFolder": "pl/logihome/gateway",
    "serverPort": "10080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pl",
    "languages": [
      "pl"
    ]
  }
}
</pre>
</details>

##### **Browsers and Operating System**

Browser doesn't matter in this case scenario, but I've checked on Google Chrome & Firefox on both Ubuntu 16.04 LTS and Windows 10.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Hi, can you make a PR for this?

**Comment by wpanas** [comment]
Yeah 😄

**Comment by MathieuAA** [comment]
Nice, thanks!

**Comment by wpanas** [comment]
I only have a problem with modals. I can't manage to close the active one and show only a login modal. My dirty workaround was to refresh whole page, but it seems unnecessary. I'm open for suggestions in this matter.

**Comment by wpanas** [comment]
Ok, I managed to solve this, but I've changed the container of the login modal from nav to default container, so this modal can be visible above all modals. If this fix doesn't satisfy you, I can change it to refreshing whole page. I don't know why this modal was bind to nav element, but it seems to work properly for not logged users.

In this moment when someone has opened a modal, tries to save an entity and doesn't have proper authorization, login modal pops up. If user logs in, then he can retry to save it.

**Comment by MathieuAA** [comment]
As far as I'm concerned, this behaviour is good. Is the saving performed even though the current user isn't logged in?

**Comment by wpanas** [comment]
The server throws 401 when user tries to save for the first time, then the modal for authentication shows up and after user logs in, saving can be retried, because the original modal didn't close up.

**Comment by MathieuAA** [comment]
Ok!

**Comment by wpanas** [comment]
Ok, so now I'm waiting for review and it can be closed :wink:
