### ISSUE TITLE
Application fails to start with ehcache and default JDL sample

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#6884]
Here is the failing config
@pascalgrimaud may be we should add once build each for each cache type, as this is clear compilation error that we missed in travis

```
 Task :compileJava
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.12.Final
/home/deepu/workspace/temp/jhtemp/src/main/java/com/test/comp/config/CacheConfiguration.java:4: error: package org.ehcache.config.builders does not exist
import org.ehcache.config.builders.CacheConfigurationBuilder;
                                  ^
/home/deepu/workspace/temp/jhtemp/src/main/java/com/test/comp/config/CacheConfiguration.java:5: error: package org.ehcache.config.builders does not exist
import org.ehcache.config.builders.ResourcePoolsBuilder;
                                  ^
/home/deepu/workspace/temp/jhtemp/src/main/java/com/test/comp/config/CacheConfiguration.java:6: error: package org.ehcache.expiry does not exist
import org.ehcache.expiry.Duration;
                         ^
/home/deepu/workspace/temp/jhtemp/src/main/java/com/test/comp/config/CacheConfiguration.java:7: error: package org.ehcache.expiry does not exist
import org.ehcache.expiry.Expirations;
                         ^
/home/deepu/workspace/temp/jhtemp/src/main/java/com/test/comp/config/CacheConfiguration.java:8: error: package org.ehcache.jsr107 does not exist
import org.ehcache.jsr107.Eh107Configuration;
                         ^
/home/deepu/workspace/temp/jhtemp/src/main/java/com/test/comp/config/CacheConfiguration.java:24: error: package javax.cache.configuration does not exist
    private final javax.cache.configuration.Configuration<Object, Object> jcacheConfiguration;
                                           ^
6 errors

```
##### **JHipster Version(s)**

```
jhtemp@0.0.0 /home/deepu/workspace/temp/jhtemp
└── generator-jhipster@4.13.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.test.comp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.0",
    "baseName": "jhtemp",
    "packageName": "com.test.comp",
    "packageFolder": "com/test/comp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "hibernateCache": "no"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Region (region) {
  regionName String
}
entity Country (country) {
  countryName String
}
/**
 * not an ignored comment
 */
entity Location (location) {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Department (department) {
  departmentName String required
}
/**
 * Task entity.
 * @author The JHipster team.
 */
entity Task (task) {
  title String,
  description String
}
/**
 * The Employee entity.
 */
entity Employee (employee) {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate Instant,
  salary Long,
  commissionPct Long
}
entity Job (job) {
  jobTitle String,
  minSalary Long,
  maxSalary Long
}
entity JobHistory (job_history) {
  startDate Instant,
  endDate Instant,
  language Language
}

enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region} to Region,
  Location{country} to Country,
  Department{location} to Location,
  JobHistory{job} to Job,
  JobHistory{department} to Department,
  JobHistory{employee} to Employee
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to Employee{department},
  Employee{job} to Job{employee}
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

dto Region, Country, Location, Department, Task, Employee, Job, JobHistory with mapstruct
service Region, Country, Location, Department, Task, JobHistory with serviceImpl
angularSuffix Region, Country, Location, Department, Task, Employee, Job, JobHistory with mySuffix
paginate Employee, JobHistory with infinite-scroll
paginate Job with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.14.3

node: v8.9.1

npm: 5.3.0

bower: 1.8.0

gulp:
[22:23:02] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.05.0-ce, build 89658be

docker-compose version 1.17.1, build 6d101fb

**Comment by deepu105** [comment]
ping @pascalgrimaud

**Comment by deepu105** [comment]
Ah damn it totally my bad I forgot to do yarn link on the generated project. Sorry to bother you @pascalgrimaud

**Comment by pascalgrimaud** [comment]
no worry :-)

**Comment by suryaaki** [comment]
I have imported blog jdl into blog project but when I start the application, am getting some java package errors:
Error:(6, 26) java: package org.ehcache.jsr107 does not exist
Error:(24, 23) java: Duplicate `@ConfigurationProperties` definition for prefix 'spring.datasource.hikari'

**Comment by MathieuAA** [comment]
@suryaaki please don't comment on old issues. If you think you're experiencing the same thing, the best way to help us help you is to create a new issue with the issue template filled with all the required information.
Thanks
