### ISSUE TITLE
Webpack does not build AOT ngfactory files for lazy route modules

### ISSUE THREAD

**Issue by sinaghazi** [jhipster/generator-jhipster#6885]
##### **Overview of the issue**
On a fresh JHipster version 4.13.0 with Angular 5.1 we changed the home module to have lazy route. On dev profile everything is fine but once trying to go with prod, the chunk files are not getting generated in the destined folder /target/www/app/

##### **Motivation for or Use Case**
I am not sure if lazy loading + aot is supposed to be working on this version. Having the latest and high performance change is something we would like to use. 

##### **Reproduce the error**

Step 1. Generate a Fresh JHipster 4.13.0 
Step 2. Changed the route in app-routing.module.ts to following
`const LAYOUT_ROUTES: Routes = [
    navbarRoute,
    {
        path: '',
        loadChildren: './home/home.module#GwoperatorHomeModule'
    },
    ...errorRoute
];`

Step 3. Commented the home module from the app.module.ts
` imports: [
        BrowserModule,
        GwoperatorAppRoutingModule,
        Ng2Webstorage.forRoot({ prefix: 'jhi', separator: '-'}),
        GwoperatorSharedModule,
        //GwoperatorHomeModule,
        GwoperatorAdminModule,
        GwoperatorAccountModule,
        GwoperatorEntityModule,
        // jhipster-needle-angular-add-module JHipster will add new module here
    ],`

Step 4. Removed the home path from app/home/home.route.ts as following: 
`export const HOME_ROUTE: Route = {
    path: '',
    component: HomeComponent,
    data: {
        authorities: [],
        pageTitle: 'home.title'
    }`

Step 5. start the application using: 
`yarn webpack:prod`

The output we get on Google chrome console is: 

```
ERROR Error: Uncaught (in promise): Error: Cannot find module './home/home.module.ngfactory'.
Error: Cannot find module './home/home.module.ngfactory'.
    at main.139c4bb250b234578d96.bundle.js:1
```

We also tried putting the following in the tsconfig-aot.json 
`  "include":[
        "src/main/webapp/app/app.main.ts",
        "src/main/webapp/app/polyfills.ts",
        "src/main/webapp/app/vendor.ts",
        "src/main/webapp/app/home/home.module.ts"
    ],`

##### **JHipster Version(s)**
4.13.0

We have had a working config on upto version 4.10.2 which used the old config of webpack. 

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.testing",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.13.0",
    "baseName": "gwoperator",
    "packageName": "com.testing",
    "packageFolder": "com/testing",
    "serverPort": "8055",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.14.1.windows.1

node: v6.11.5

npm: 3.10.10

yeoman: 2.0.0

yarn: 1.3.2

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
We havent implemented any support for lazy loading yet. Take a look at #5712 which started some work. I suggest you take this to our Gitter channel or stackoverflow and if we would also appreciate any help with implementing lazy loading
