### ISSUE TITLE
Error when upgrading to 4.13.0. on Windows 10

### ISSUE THREAD

**Issue by pvlastaridis** [jhipster/generator-jhipster#6887]
##### **Overview of the issue**

Error when upgrading to 4.13.0. on Windows 10. After running jhipster upgrade
yarn info v1.3.2
4.13.0
Done in 0.63s.
WARNING! Something went wrong fetching the latest JHipster version number...

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! Exiting process
    at Environment.error (C:\Users\panos\AppData\Local\Yarn\config\global\node_modules\yeoman-environment\lib\environment.js:157:40)
    at module.exports.error (C:\Users\panos\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\generator-base.js:1974:18)
    at shelljs.exec (C:\Users\panos\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\upgrade\index.js:155:30)
    at C:\Users\panos\AppData\Local\Yarn\config\global\node_modules\shelljs\src\exec.js:199:9
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

##### **Reproduce the error**

Install version 4.12.0 and try to upgrade it to 4.13.0 on Windows 10

##### **Related issues**

#6161

##### **Suggest a Fix**

Look above error description

##### **JHipster Version(s)**

4.12.0

#### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "uth.bioinf.llr"
    },
    "jhipsterVersion": "4.12.0",
    "baseName": "llr",
    "packageName": "uth.bioinf.llr",
    "packageFolder": "uth/bioinf/llr",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.6.3.windows.1

node: v8.9.0

npm: 5.5.1

bower: 1.8.0

gulp:
[07:51:52] CLI version 1.3.0

yeoman: 1.8.5

yarn: 1.3.2

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entitities

##### **Browsers and Operating System**

Win 10 Pro 64x

- [Yes] Checking this box is mandatory (this is just to show you read everything)

**Comment by antarus** [comment]
I couldn't reproduce the error with your config file.
Same version of windows, node, yeoman.
the only difference is yarn I have in 1.1.0. I will try to upgrade.
I am in an environment without internet connection but npm mirror is up to date

**Comment by pvlastaridis** [comment]
I do not have microsoft tools for linux.

**Comment by antarus** [comment]
no problem after upgrade yarn.. 
I do not have too much time to test by removing tools linux, reboot, etc. if anyone has ideas for testing, I can help

**Comment by deepu105** [comment]
Looks like an intermittent environment error. Can you try to run it again if it fails try running `yarn add generator-jhipster `manually

**Comment by henry2man** [comment]
@pvlastaridis @antarus @deepu105 

I had this also on vagrant linux box. 

Workarround -> **force version using --target-version**

`jhipster upgrade --target-version=4.13.0`

**Comment by henry2man** [comment]
I also had to execute the following command to update the generator:

yarn upgrade generator-jhipster@4.13.0 -D

**Comment by pvlastaridis** [comment]
@henry2man Thank you for your advice unfortunatley all it does is to update the version of ng-hipster in package.json. I thought upgrade is supposed to do more at least update more dependancies on packge.json

**Comment by jdubois** [comment]
I'm pretty sure this is because you didn't upgrade JHipster first - this is why @antarus and myself can't reproduce

-> please upgrade first your global version of JHipster, and if this still fails, please comment the ticket and I will reopen it
