### ISSUE TITLE
Missing local when native language is not 'en'

### ISSUE THREAD

**Issue by antarus** [jhipster/generator-jhipster#6889]
##### **Overview of the issue**
A  generated app causes some local issues.
Missing local error on `metrics`, `audits` and `user-management` pages.

##### **Reproduce the error**

Take the yo-rc file below, then in console `jhipster` then `./mvnw` and in another console `yarn start`
When the application is started, log in with admin / admin and go to the `metrics` administration page

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/6836

##### **JHipster Version(s)**

4.13.0

##### **JHipster configuration**
handwritten file as I can't transfer the file...
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com",
      "nativeLanguage" : "fr"
    },
    "jhipsterVersion": "4.13.0",
    "baseName": "app",
    "packageName": "com",
    "packageFolder": "com",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
    "gatling",
    "protractor"
     ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage" : "fr",
    "language": [
     "fr",
    "en"
]
  }
}
```
##### **Browsers and Operating System**

Windows 10, firefox and chome

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by antarus** [comment]
Sorry, I missed the conflict resolution during the upgrade

**Comment by deepu105** [comment]
Did you check the master branch, this was fixed recently


Thanks & Regards,
Deepu
