### ISSUE TITLE
Missing template when creating Microservice Gateway administration/gateway/gateway.tsx

### ISSUE THREAD

**Issue by delkant** [jhipster/generator-jhipster#6911]
##### **JHipster Version(s)**

```
/Users/user/git
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)

git version 2.11.0 (Apple Git-81)

node: v8.9.1

npm: 5.5.1

bower: 1.8.0

gulp:
[16:44:04] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

##### **Overview of the issue**

No such file or directory, open 'generator-jhipster/generators/client/templates/react/src/main/webapp/app/modules/administration/gateway/gateway.tsx

##### **Motivation for or Use Case**

I would like to use microservices with React, but a gateway cannot be created because of this. I know this is in experimental but just wanted to point this issue in case you don't know about it yet.

##### **Reproduce the error**
1. run jhipster --experimental
2. create microservices gateway
3. Select React as front-end 

##### **Related issues**

did not find anything related.

##### **Suggest a Fix**
gateway templates for microservices need to be migrated to React templates.

##### **JHipster Version(s)**
 v4.13.0

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

none

##### **Browsers and Operating System**

osx 

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
React is "experimental", it's only working with the basic options. This is not done yet.

**Comment by deepu105** [comment]
You can ofcourse PR an implementation

**Comment by jdubois** [comment]
@deepu105 we have @arthurescriou who is starting to work on this :-)

**Comment by deepu105** [comment]
@jdubois oh thats nice.
