### ISSUE TITLE
Invalid JAVA syntax due to double quotes in JDL JavaDoc 

### ISSUE THREAD

**Issue by dkefer** [jhipster/generator-jhipster#6918]
##### **Motivation for or Use Case**
The affected JAVA files have invalid syntax and the Build fails.

##### **Reproduce the error**

Create a JDL file containing a JavaDoc comment for an entity containing double quotes. e.g.
```
/**
* Entity "Foo bar"
*/
entity Foobar {}
```
The annotation will look like this:
```
@ApiModel(description = "Entity "Foo bar"")
```

##### **Related issues**
Haven't found any.

##### **Suggest a Fix**
Escape the double quotes with backslash (as it's done when filling this annotation.

##### **JHipster Version(s)**
```
requirement@0.0.0 /home/vagrant/securityratv2/requirement
└── generator-jhipster@4.13.1 
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.securityrat.requirementms"
    },
    "jhipsterVersion": "4.13.1",
    "baseName": "requirement",
    "packageName": "org.securityrat.requirementms",
    "packageFolder": "org/securityrat/requirementms",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Requirements are organized in different sets.
 * These define also the structure of contained requirements.
 * Selecting a suitable requirement set is the initial step when creating a "case".
 */
entity RequirementSet (requirement_set) {
  name String required,
  description TextBlob,
  showOrder Integer,
  active Boolean required
}
/**
 * The "core" part of a particular requirement.
 */
entity Skeleton (skeleton) {
  name String required,
  description TextBlob,
  showOrder Integer,
  active Boolean required
}
/**
 * Describes one group/collection of requirement attributes.
 * E.g. "Criticality" for Low, Medium, High.
 */
entity AttributeGroup (attribute_group) {
  name String required,
  description TextBlob,
  type AttributeType required,
  showOrder Integer,
  active Boolean required
}
/**
 * Every requirement can be classified in many ways
 * according to different attributes.
 */
entity Attribute (attribute) {
  name String required,
  description TextBlob,
  showOrder Integer,
  active Boolean required
}
/**
 * Describes properties of one type of a requirement extension.
 */
entity ExtensionDefinition (extension_definition) {
  name String required,
  description TextBlob,
  section ExtensionSection required,
  type ExtensionType,
  showOrder Integer,
  active Boolean required
}
/**
 * Requirement extension (extending the requirement skeleton).
 */
entity Extension (extension) {
  content TextBlob required,
  description TextBlob,
  showOrder Integer,
  active Boolean required
}
/**
 * Implements ternary relation of req. skeleton, attribute an extension.
 * Requirement extension can be added to a skeleton if a particular attribute is set.
 */
entity SkAtEx (sk_at_ex)

enum AttributeType {
  FE_TAG,
  PARAMETER,
  CATEGORY
}

enum ExtensionSection {
  STATUS,
  ENHANCEMENT
}

enum ExtensionType {
  ENUM,
  FREETEXT
}

relationship OneToMany {
  RequirementSet{skeleton} to Skeleton{requirementSet(name)},
  RequirementSet{attributeGroup} to AttributeGroup{requirementSet(name)},
  AttributeGroup{attribute} to Attribute{attributeGroup(name)},
  RequirementSet{extensionDefinition} to ExtensionDefinition{requirementSet(name)},
  ExtensionDefinition{extension} to Extension{extensionDefinition(name)},
  Skeleton{skAtEx} to SkAtEx{skeleton(name)},
  Attribute{skAtEx} to SkAtEx{attribute(name)},
  Extension{skAtEx} to SkAtEx{extension(content)}
}
relationship ManyToOne {
  Attribute{parent} to Attribute
}

paginate RequirementSet, Skeleton, AttributeGroup, Attribute, ExtensionDefinition, Extension, SkAtEx with infinite-scroll
service RequirementSet, Skeleton, AttributeGroup, Attribute, ExtensionDefinition, Extension, SkAtEx with serviceClass
microservice RequirementSet, Skeleton, AttributeGroup, Attribute, ExtensionDefinition, Extension, SkAtEx with requirement
filter RequirementSet, Skeleton, AttributeGroup, Attribute, ExtensionDefinition, Extension, SkAtEx

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.11.0

node: v8.9.3

npm: 5.6.0

bower: 1.8.2

gulp:
[17:27:40] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.11.0-ce, build 1caf76c

##### **Browsers and Operating System**

JHipster DevBox 4.13.1

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Indeed I don't think that's a use case we already thought of. @MathieuAA what do you think?

**Comment by MathieuAA** [comment]
@jdubois Indeed. If the quote is present in such a use case, wouldn't it be better to have an utils method (in the generator) to format it in critical places?
The quote is legit if it's in a javadoc comment, but not in the other case...

**Comment by MathieuAA** [comment]
@jdubois I'll have some time next week to implement something. Are you okay if I do this in the generator? I'd rather not have it in JCore, as the project shouldn't have any knowledge of how it's gonna be used.

**Comment by pascalgrimaud** [comment]
maybe the fix is simply on this line ? 
https://github.com/jhipster/generator-jhipster/blob/16b549c21f059bb736e13684428616d72dd9df4c/generators/entity-server/templates/src/main/java/package/domain/_Entity.java#L91

**Comment by MathieuAA** [comment]
@pascalgrimaud It would seem so. This function has to change a bit
https://github.com/jhipster/generator-jhipster/blob/16b549c21f059bb736e13684428616d72dd9df4c/generators/generator-base-private.js#L341..L355

to have a simple 
```javascript
description = rows[i].replace(/"/g, '\"');
```

**Comment by pascalgrimaud** [comment]
yes, let's do it
