### ISSUE TITLE
Unused import in e2e tests for entities with byte+text

### ISSUE THREAD

**Issue by dkefer** [jhipster/generator-jhipster#6919]
##### **Overview of the issue**

I'm trying to create a docker image for microservice gateway using
```
./mvnw verify -Pprod dockerfile:build 

```
It looks like the tests are failing:
```
[ERROR] error Command failed with exit code 2.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:30 min
[INFO] Finished at: 2017-12-29T18:56:26Z
[INFO] Final Memory: 37M/90M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (webpack build test) on project gateway: Failed to run task: 'yarn run webpack:test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

##### **Motivation for or Use Case**

Failed build of the docker image

##### **Reproduce the error**

Try to create a docker image with settings listed below. 

##### **Related issues**

Haven't found any.

##### **Suggest a Fix**

Don't know.

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/vagrant/securityratv2/gateway
└── generator-jhipster@4.13.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.securityrat.gateway"
    },
    "jhipsterVersion": "4.13.1",
    "baseName": "gateway",
    "packageName": "org.securityrat.gateway",
    "packageFolder": "org/securityrat/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Requirements are organized in different sets.
 * These define also the structure of contained requirements.
 * Selecting a suitable requirement set is the initial step when creating a "case".
 */
entity RequirementSet (requirement_set) {
  name String required,
  description TextBlob,
  showOrder Integer,
  active Boolean required
}
/**
 * The "core" part of a particular requirement.
 */
entity Skeleton (skeleton) {
  name String required,
  description TextBlob,
  showOrder Integer,
  active Boolean required
}
/**
 * Describes one group/collection of requirement attributes.
 * E.g. "Criticality" for Low, Medium, High.
 */
entity AttributeGroup (attribute_group) {
  name String required,
  description TextBlob,
  type AttributeType required,
  showOrder Integer,
  active Boolean required
}
/**
 * Every requirement can be classified in many ways
 * according to different attributes.
 */
entity Attribute (attribute) {
  name String required,
  description TextBlob,
  showOrder Integer,
  active Boolean required
}
/**
 * Describes properties of one type of a requirement extension.
 */
entity ExtensionDefinition (extension_definition) {
  name String required,
  description TextBlob,
  section ExtensionSection required,
  type ExtensionType,
  showOrder Integer,
  active Boolean required
}
/**
 * Requirement extension (extending the requirement skeleton).
 */
entity Extension (extension) {
  content TextBlob required,
  description TextBlob,
  showOrder Integer,
  active Boolean required
}
/**
 * Implements ternary relation of req. skeleton, attribute an extension.
 * Requirement extension can be added to a skeleton if a particular attribute is set.
 */
entity SkAtEx (sk_at_ex)

enum AttributeType {
  FE_TAG,
  PARAMETER,
  CATEGORY
}

enum ExtensionSection {
  STATUS,
  ENHANCEMENT
}

enum ExtensionType {
  ENUM,
  FREETEXT
}

relationship OneToMany {
  RequirementSet{skeleton} to Skeleton{requirementSet(name)},
  RequirementSet{attributeGroup} to AttributeGroup{requirementSet(name)},
  AttributeGroup{attribute} to Attribute{attributeGroup(name)},
  RequirementSet{extensionDefinition} to ExtensionDefinition{requirementSet(name)},
  ExtensionDefinition{extension} to Extension{extensionDefinition(name)},
  Skeleton{skAtEx} to SkAtEx{skeleton(name)},
  Attribute{skAtEx} to SkAtEx{attribute(name)},
  Extension{skAtEx} to SkAtEx{extension(content)}
}
relationship ManyToOne {
  Attribute{parent} to Attribute
}

paginate RequirementSet, Skeleton, AttributeGroup, Attribute, ExtensionDefinition, Extension, SkAtEx with infinite-scroll
service RequirementSet, Skeleton, AttributeGroup, Attribute, ExtensionDefinition, Extension, SkAtEx with serviceClass
microservice RequirementSet, Skeleton, AttributeGroup, Attribute, ExtensionDefinition, Extension, SkAtEx with requirement
filter RequirementSet, Skeleton, AttributeGroup, Attribute, ExtensionDefinition, Extension, SkAtEx

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.11.0

node: v8.9.3

npm: 5.6.0

bower: 1.8.2

gulp:
[18:56:08] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.11.0-ce, build 1caf76c

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
As the error says, Yarn couldn't run:

Can you run it "normally", just doing `yarn install` or `yarn start`?

Anyway that's a configuration issue, not a bug, people use this all the time, it's sure that Yarn works on Ubuntu. You probably have a network error, I guess you are behind a proxy.

**Comment by gmarziou** [comment]
Also the maven log extract you pasted does not show the real error which is probably printed lines above.

**Comment by dkefer** [comment]
@jdubois: Sorry, I think the issue name and description is misleading (my first steps with yarn...). Nevertheless I don't consider it a  configuration issue.

Both ```yarn install``` and ```yarn start``` ran successfully, but when I ran ```yarn run webpack:test``` I got:

```
gateway git:(master) ✗ yarn run webpack:test
yarn run v1.3.2
$ yarn run test
$ yarn run lint && karma start src/test/javascript/karma.conf.js
$ tslint --project tsconfig.json -e 'node_modules/**'

ERROR: /home/vagrant/securityratv2/gateway/src/test/javascript/e2e/entities/attribute-group.spec.ts[10, 11]: 'absolutePath' is declared but never used.
ERROR: /home/vagrant/securityratv2/gateway/src/test/javascript/e2e/entities/attribute.spec.ts[10, 11]: 'absolutePath' is declared but never used.
ERROR: /home/vagrant/securityratv2/gateway/src/test/javascript/e2e/entities/extension-definition.spec.ts[10, 11]: 'absolutePath' is declared but never used.
ERROR: /home/vagrant/securityratv2/gateway/src/test/javascript/e2e/entities/extension.spec.ts[10, 11]: 'absolutePath' is declared but never used.
ERROR: /home/vagrant/securityratv2/gateway/src/test/javascript/e2e/entities/requirement-set.spec.ts[10, 11]: 'absolutePath' is declared but never used.
ERROR: /home/vagrant/securityratv2/gateway/src/test/javascript/e2e/entities/skeleton.spec.ts[10, 11]: 'absolutePath' is declared but never used.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
When I comment out the respective lines (+ the one before defining "path" and "fileToUpload"). The command runs ok and so does the docker image creation. 

So I would still consider this an issue, what do you think?

**Comment by dkefer** [comment]
@gmarziou : Indeed, copy&pase mistake, sorry!

**Comment by pascalgrimaud** [comment]
I confirm the issue.
It's because some of your entities use:
```
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
```

In our generator, this condition is not correct: https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-client/templates/angular/src/test/javascript/e2e/entities/_entity.spec.ts#L50-L53

If you want to fix it, just tell me. This one is harder to fix and test than your other ticket.
Otherwise, I can do it.

**Comment by dkefer** [comment]
@pascalgrimaud : Yup, I suggest you fix it if you know how to do it. That apparently requires way deeper knowledge of what's happening there than I have currently.
