### ISSUE TITLE
Invalid syntax of docker-compose.yml when using Keycloak

### ISSUE THREAD

**Issue by dkefer** [jhipster/generator-jhipster#6920]
##### **Overview of the issue**

When using Keycloak, an invalid docker-compose.yml file is created. 

The relevant part of file:
```
volumes:
    prometheus_data: {}
    grafana_data: {}
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak

```
##### **Motivation for or Use Case**

An invalid docker-compose.yml file is created.

##### **Reproduce the error**

Run "jhipster docker-compose" with the settings listed below. 

##### **Related issues**

Haven't found any.

##### **Suggest a Fix**

Put the keycloak part before the "volumes" section.

##### **JHipster Version(s)**
4.13.1
```
/home/vagrant/securityratv2/dc1
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "appsFolders": [
      "gateway",
      "requirement"
    ],
    "directoryPath": "../",
    "gatewayType": "zuul",
    "monitoring": "prometheus",
    "serviceDiscoveryType": "consul",
    "jwtSecretKey": "replaced-by-jhipster-info"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.11.0

node: v8.9.3

npm: 5.6.0

bower: 1.8.2

gulp:
[19:06:26] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.11.0-ce, build 1caf76c
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@dkefer : it's an easy fix. Would you like to contribute and do a PR ?
https://github.com/jhipster/generator-jhipster/blob/master/generators/docker-compose/templates/_docker-compose.yml#L118-L123

**Comment by dkefer** [comment]
@pascalgrimaud : Thanks for the generous offer :) I'll look into it tomorrow.

**Comment by pascalgrimaud** [comment]
You're welcome. We are happy to see new contributors.
You can read this: https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

Don't hesitate to ping me if you need help.

**Comment by dkefer** [comment]
@pascalgrimaud : Indeed, the fix looks trivial. 

However, would test be expected in the PR? I had a look at https://github.com/jhipster/generator-jhipster/blob/master/test/docker-compose.spec.js (not sure if it's the correct file), but haven't seen tests validating the structure of the docker compose file. That would most probably be a bigger deal for me.

**Comment by pascalgrimaud** [comment]
@dkefer : no test expected in this PR. As you said, there are no test validating the structure of the docker compose... it's not trivial to do, because the structure can change, depending the version of docker-compose

**Comment by dkefer** [comment]
@pascalgrimaud : Thanks for the support - please see https://github.com/jhipster/generator-jhipster/pull/6924
