### ISSUE TITLE
import-jdl not working with gateway with no database

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#6930]
##### **Overview of the issue**

When using the gateway with no database, import-jdl doesn't work any more:

```
Error: ERROR! The entity cannot be generated as the application does not have a database configured!
    at Environment.error (/Users/test/gateway/node_modules/yeoman-environment/lib/environment.js:157:40)
    at error (/Users/test/gateway/node_modules/generator-jhipster/generators/generator-base.js:1974:18)
    at validateDbExistence (/Users/test/gateway/node_modules/generator-jhipster/generators/entity/index.js:175:30)
    at Object.<anonymous> (/Users/test/gateway/node_modules/yeoman-generator/lib/index.js:399:25)
    at /Users/test/gateway/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /Users/test/gateway/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/test/gateway/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

##### **Motivation for or Use Case**

without this the no-database option is uselesss

##### **Reproduce the error**

1. Generate a gateway with: no Database
2. run: jhipster import-jdl test.js --skipServer

(generate entity doesn't work either)

##### **Related issues**

I didn't find any
##### **JHipster Version(s)**
4.12.0, 4.13.0

In some sense yes
##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.elhouti.corpman",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.0",
    "baseName": "corpmanGateway",
    "packageName": "com.elhouti.corpman",
    "packageFolder": "com/elhouti/corpman",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

in fact this not relevant even if it's about jdl, and once the import fails, the files are creates and you don't see the errors anymore

##### **Browsers and Operating System**

OSx
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
That does makes sense, if you have no database, then you're not going to have any entities... That's also what the error message says, so it's all logical to me.
Besides, a gateway with no backend ("skipServer") doesn't make any sense to me - I'm really not sure what you're going to have in the end.

**Comment by PierreBesson** [comment]
I think a gateway with no database makes sense as a pure zuul proxy. And he only wants to generate the front-end for microservice entities.

So I think we should remove the nodatabase entity check for gateways.

**Comment by PierreBesson** [comment]
After some reflexion I'm not so sure it seems @yelhouti is generating a normal entity on a no database gateway. And I'm not sure if it should make sense or not.

**Comment by pascalgrimaud** [comment]
@yelhouti : we need your JDL file too, to understand what you tried to do, and if you JDL file can work with your configuration

**Comment by yelhouti** [comment]
hey guys, thank you in advance for your help, this is what I'm trying to achieve so you have the whole context:
I'm trying to build an app with a microservice architecture, the [doc](http://www.jhipster.tech/creating-microservices/) says 

> ...Then, on the gateway(s), run the entity sub-generator again. A new question will appear at the beginning, which is specific to gateways:...

So after generating the microservice (backend), I want to generate the frontend (angular) based on that same JDL.

but maybe I'm doing it wrong, here is how my JDL as some of you asked for it (even thow it's not relevant IMO)

```
entity Business {
    name String required
    hq Boolean required
    phone String required
    email String required
    fax String
    country String required
    city String required
    postalCode String required
    address1 String required
    address2 String
    lat Long
    lng Long
}

entity Employee{
    userId String required
    country String required
    city String required
    postalCode String required
    address1 String required
    address2 String
}

entity BusinessEmployee{
    rate Integer required
    salary Integer required
    startDate LocalDate required
    endDate LocalDate
}
```

**Comment by pascalgrimaud** [comment]
After some analyse:
1) there is indeed a bug : we can't use `jhipster entity` on a Gateway+No database application -> I'm fixing it
2) your use of JDL is incorrect. You tried to generate a full entities (with backend and frontend) on a Gateway+No database application: there are no `microservice` keyword -> you need to read the [JDL doc](http://www.jhipster.tech/jdl/)

**Comment by yelhouti** [comment]
sorry I forget to include that in the issue:
I'll edit the question

**Comment by pascalgrimaud** [comment]
Maybe this ticket is linked : https://github.com/jhipster/generator-jhipster/issues/6871
Plz, have a look too.

PR done to fix the nodatabase + gateway + oauth2, configuration

**Comment by yelhouti** [comment]
thanks you are amazing, I'm taking a look

**Comment by jdubois** [comment]
Oh yes -> sorry about my first message, now I understand. Thanks @pascalgrimaud for the fix! And thanks @yelhouti for the bug report!
That's kind of a new use case for gateways (the no db option is very new for gateways), and that's really cool.
