### ISSUE TITLE
OIDC realm jhipster is not loaded on Cloud Foundry deployment

### ISSUE THREAD

**Issue by adnansenyurt** [jhipster/generator-jhipster#6934]
##### **Overview of the issue**

On startup, keycloak docker deployment is loading jhipster realm from the external volume directory as set in keycloak.yml:

~~~yml
version: '2'
services:
  keycloak:
    image: jboss/keycloak:3.3.0.Final
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Djboss.socket.binding.port-offset=1000"]
    volumes:
      **- ./realm-config:/opt/jboss/keycloak/realm-config**
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
~~~

This setup works in local deployment, but not in cloud foundry case. There is no external file system or service that can provide ./realm-config directory.

So jhipster realm is not loaded and apps gateway, microservices or registry) can not access keycloak server.

##### **Motivation for or Use Case**

We need to deploy Keycloak server as a separate service on cloud, accessible from internet.

##### **Reproduce the error**

Deploy to cloud foundry:
cf push keycloak --docker-image keycloak

##### **Suggest a Fix**

- As in configuration server case, production deployment can be done via a github repository loading.
or 
- a custom Keycloak image can be prepared that has jhipster realm already loaded.

##### **JHipster Version(s)**

4.13.1

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by srinivasa-vasu** [comment]
Docker images are not run through docker runtime in CF. Instead Garden-runc runs the container images and there are certain limitations in running docker images. You can't run an image that mounts a file system locally rather it has to be done through volume services. Either create a volume service from the market place or write your own broker. You can not run docker images with complex networking requirements in CF(ERT). These docker artefacts are best to run in Swarm/K8s and not CF.

**Comment by adnansenyurt** [comment]
I'm aware of this. Unfortunately, changing our infrastructure decisions is not possible at this stage. Also, volume services are not available in all cloud providers.

So does this mean that Keycloak option is not supported for CF deployments? In this case we need to revert back to UAA option.

**Comment by gmarziou** [comment]
Have you considered configuring your realm otherwise: through admin console or admin CLI?

**Comment by adnansenyurt** [comment]
Actually yes, I've tried but admin console is only accessible by https due to the default settings. I've opened another issue for this.

**Comment by srinivasa-vasu** [comment]
@adnansenyurt - SSL gets offloaded at LB/Go Router. Internal comm is again on http. Can you ssh to the container and use REST endpoints thr localhost?

**Comment by mraible** [comment]
@adnansenyurt You could always use Okta instead of Keycloak. 7000 active monthly users for free! https://developer.okta.com ;)

**Comment by deepu105** [comment]
@mraible does any of your recent PRs address this?

**Comment by mraible** [comment]
@deepu105 No, and I don't think we should. The default user realm is meant for developing and testing, not for production IMO.

**Comment by deepu105** [comment]
ok lets close it then
