### ISSUE TITLE
Tests on AuditsComponent fail with Prod profile

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6937]
##### **Overview of the issue**

When you generate an application with Karma tests, 2 tests fail on `AuditsComponent` when the `prod` profile is activated

```
[INFO] PhantomJS 2.1.1 (Mac OS X 0.0.0) Component Tests AuditsComponent By default, on init should set all default values correctly FAILED
[INFO] 	Expected '2018-01-03' to be '2018-1-03'.
[INFO] PhantomJS 2.1.1 (Mac OS X 0.0.0) Component Tests AuditsComponent today function  should set toDate to current date FAILED
[INFO] 	Expected '2018-01-03' to be '2018-1-03'.
```

##### **Reproduce the error**

Generate an app with the following `.yo-rc.json`, no need to create entities, and build with the `prod` profile.

$ mvn clean install -Pprod

##### **JHipster Version(s)**

```
temp@0.0.0 /Users/agoncal/Documents/Code/Quantixx/temp/temp
└── generator-jhipster@4.13.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.1",
    "baseName": "temp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.15.1

node: v9.3.0

npm: 5.6.0

bower: 1.8.0

gulp:
[18:55:09] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.1-ce, build 19e2cf6

docker-compose version 1.17.1, build 6d101fb

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@agoncal could you try the current master. It was fixed by @pascalgrimaud recently

**Comment by pascalgrimaud** [comment]
Yes, here the PR : https://github.com/jhipster/generator-jhipster/pull/6926

**Comment by agoncal** [comment]
Yes, I just tried and it works. Thanks @pascalgrimaud

**Comment by tapas4java** [comment]
Probably we should cut a new minor release, all newly generated app is suffering this issue from 1st Jan.

**Comment by jdubois** [comment]
Yes you are right @tapas4java - I'll propose a new release on our mailing list
