### ISSUE TITLE
looks like login pattern make Okta login fail

### ISSUE THREAD

**Issue by mathieu-chauvet** [jhipster/generator-jhipster#6943]
##### **Overview of the issue**

I use Okta as open ID provider and after following the configuration instruction, it did not work. 
After having a look onto the problem, I could solve it by commenting the pattern (LOGIN_REGEX) of the login.

`    @NotNull
//    @Pattern(regexp = Constants.LOGIN_REGEX)
    @Size(min = 1, max = 50)
    @Indexed
    private String login;
`

##### **Motivation for or Use Case**

As Okta is not explicitly configured during the application setup, I think the documentation should be updated. 

##### **Reproduce the error**

Setup an app with mongoDB, and Okta as Authentification provider. 

##### **Suggest a Fix**

Update documentation or update the REGEX to be compliant with OKTA login (mail address). 

##### **JHipster Version(s)**

I use JHipster 4.13.1

##### **JHipster configuration**
```
├── generator-jhipster@4.13.1 
└── UNMET PEER DEPENDENCY popper.js@^1.12.3
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.home",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.13.1",
    "baseName": "BoweConnaissance",
    "packageName": "com.home",
    "packageFolder": "com/home",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

git version 2.14.3 (Apple Git-98)

node: v6.10.2

npm: 3.10.10

bower: 1.7.9

gulp:
[23:23:21] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.12.0-ce-rc4, build 6a2c058

docker-compose version 1.18.0, build 8dd22a9

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
None

##### **Browsers and Operating System**

OSX 10.13.2
Chrome as Browser.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mathieu-chauvet** [comment]
@mraible I think this one is for you Matt ! 
Thank you and all the dev team for this great work.

**Comment by jdubois** [comment]
And this is basically the same issue as #6923 - we changed that not so long ago, let me explain:

- You can now login both with your username or your email
- But this causes a security issue: if you use someone's else email as your login, then that other person couldn't use his email address anymore to login. So we removed the option to use an "@" in a login name. Now I guess that was a bad decision!

**Comment by mathieu-chauvet** [comment]
Oups... didn't see #6923 ... 
Yes, that exactly the same issue.

**Comment by deepu105** [comment]
duplicate of #6923
