### ISSUE TITLE
Support SAML for authentication

### ISSUE THREAD

**Issue by davidstrauss** [jhipster/generator-jhipster#695]
Spring Security has release-candidate support now for SAML [1], and it would be a useful option in addition to normal sessions and OAuth2.

[1] http://projects.spring.io/spring-security-saml/

**Comment by sendilkumarn** [comment]
It would be great if we add Spring SAML authentication in jhipster as 4th option. Can we open this?

**Comment by pnreddysvu** [comment]
instead of supporting these many authentication/authorization options better go for https://github.com/keycloak/keycloak. Some one pointed this last week. I gone through the youtube videos. This is really cool. It supports many things which typical web developer needs.

**Comment by pnreddysvu** [comment]
See the extensive feature set.

Features
OpenID Connect and SAML 2.0 SSO and Single Log Out for browser applications
Social Broker.  Enable Google, Facebook, Yahoo, Twitter social login with no code required.
Identity Broker.  Delegate to an external SAML 2.0 or OIDC broker for auth.
Optional LDAP/Active Directory integration
Optional User Registration, with optional Recaptcha ability
Password and TOTP support (via Google Authenticator).  Client cert auth coming soon.
User session management from both admin and user perspective
Customizable themes for user facing pages: login, grant pages, account management, emails, and admin console all customizable!
OAuth 2.0 Bearer token auth for REST Services
Integrated Browser App to REST Service token propagation
Admin REST API
CORS Support
Completely centrally managed user and role mapping metadata.  Minimal configuration at the application side
Admin Console for managing users, roles, role mappings, applications, user sessions, allowed CORS web origins, and OAuth clients.
Deployable as a WAR, appliance, or an Openshift  cloud service (SaaS).
Supports JBoss AS7, EAP 6.x, Wildfly, Tomcat, Jetty, and Pure Javascript applications.   Plans to support Node.js, RAILS, GRAILS, and other non-Java applications.
HTTP Security Proxy for environments/platforms/languages that don't have a client adapter
Javascript/HTML 5 adapter for pure Javascript apps
Session management from admin console
Claim/assertion mappings.  Make your tokens and assertion XML look however you want.
Revocation policies
Password policies
Impersonation.  Allow your admins to impersonate a user to debug problems.

**Comment by jdubois** [comment]
If this is supported by Spring Security, the "normal way" for JHipster would be to use Spring Security, and not Keycloak.
Let's not add 3rd party libs if we don't need to.
All those could be released as modules (there will be announcement on this during this week), so everybody can code his solution, anyway

**Comment by sendilkumarn** [comment]
@jdubois  :+1: I too agree reg 3rd party apps integration. But SAML, is yet to be configured in Jhipster which will be a good move if we add this functionality inside

**Comment by sendilkumarn** [comment]
@jdubois @deepu105 Can this be added in JH3?

**Comment by sasconsul** [comment]
+1 For  supporting SAML as another SSO option.

**Comment by pascalgrimaud** [comment]
@sasconsul : you can do a module for that, look at this page https://jhipster.github.io/modules/creating-a-module/
