### ISSUE TITLE
Build failure because Oracle Maven Repository doesn't provide ojdbc7 jar

### ISSUE THREAD

**Issue by oswaldo-sd** [jhipster/generator-jhipster#6952]
##### **Overview of the issue**

On a machine without prior use of Oracle JDBC driver (hence not installed on local Maven repository), creating a new project fails to compile because Oracle Maven Repository doesn't provide **ojdbc7** artifact:

```
[ERROR] Failed to execute goal on project demo: Could not resolve dependencies for project demo:demo:war:0.0.1-SNAPSHOT: Could not find artifact com.oracle.jdbc:ojdbc7:jar:12.2.0.1 in maven.oracle.com (https://maven.oracle.com)
```

##### **Motivation for or Use Case**

It prevents from building the project for new users.

##### **Reproduce the error**

Create a new jHipster project with Oracle database support on a machine whithout ojdbc7 artifact installed on local Maven repository.

##### **Related issues**

None that I'm aware of.

##### **Suggest a Fix**

Using ojdbc8 version 12.2.0.1 dependency (mentioned on https://blogs.oracle.com/dev2dev/entry/how_to_get_oracle_jdbc) seems to work, but I'm yet to check other dependencies.

##### **JHipster Version(s)**

4.13.2

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
demo@0.0.0 C:\projects\demos\jhipster_plain
+-- generator-jhipster@4.13.2
`-- UNMET PEER DEPENDENCY popper.js@^1.12.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "demo"
    },
    "jhipsterVersion": "4.13.2",
    "baseName": "demo",
    "packageName": "demo",
    "packageFolder": "demo",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.14.2.windows.2

node: v6.11.0

npm: 3.10.10

bower: 1.8.0

gulp:
[12:42:41] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.07.0-ce, build 8784753

docker-compose version 1.15.0, build e12f3b94

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None.

##### **Browsers and Operating System**
Tested on Windows 10. Seems browser an OS independent.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Thanks for the report, please consider submitting a pull request. See https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by GuiF007** [comment]
Well, maybe you have an Oracle library in your .m2 with that version and not the out-of-the-box version ?
Please read this :
[Using Oracle with jHipster](http://www.jhipster.tech/using-oracle/)

**Comment by jdubois** [comment]
I'm pretty sure you didn't follow our documentation on how to connect to the Oracle Maven repository - and basically they come from Oracle itself - so that's why I'm closing this.
If you did follow the documentation, and that you are correct that Oracle does not provide its JDBC driver anymore:

- Please notify us so we try to find a solution
- Please ask Oracle support about it: you're paying for the support, so you should ask them directly

**Comment by GuiF007** [comment]
However, shouldn't be ojdbc8 instead of ojdbc7 with version 12.2.0.1 ?
[http://www.oracle.com/technetwork/database/features/jdbc/jdbc-ucp-122-3110062.html](http://www.oracle.com/technetwork/database/features/jdbc/jdbc-ucp-122-3110062.html)

**Comment by jdubois** [comment]
I don't remember why we stick to ojdbc7 - our main issue is that it's very painful to test, as it's a proprietary product. If you tested a JHipster app with ojdbc8, we could easily upgrade - most of the work is done by Hibernate/Liquibase anyway, so if a normal application boots up, basically everything else will also work.

**Comment by oswaldo-sd** [comment]
I did follow the documentation. There's a table on https://blogs.oracle.com/dev2dev/get-oracle-jdbc-drivers-and-ucp-from-oracle-maven-repository-without-ides (the link from jHipster's "Using Oracle" page) listing all the artifacts available on Oracle Maven Repository; it doesn't mention ojdbc7, only ojdbc8.

**Comment by GuiF007** [comment]
I've never tested to use jHipster app with Oracle, for the reason you said @jdubois... Agree with you about Hibernate/Liquibase, everything is done by this couple... No big deal I think to go to ojdbc8...

For me, the bug is that you have the v12.2.0.1 with ojdbc7, which does not work in **Oracle Maven Repository**... 
Two solutions : ojdbc8 or v12.1.0.1 !

**Comment by jdubois** [comment]
You are correct, sorry!!!!!!
I'm testing and will do a fix

**Comment by oswaldo-sd** [comment]
Sorry, took me a while to configure. ojdbc8 version 12.2.0.1 works ok on a test entity.

**Comment by jdubois** [comment]
Oh sorry -> I merged this as I also tested and that was working fine. So it will be all OK in the next release.
