### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [jhipster/generator-jhipster#6957]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature,

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by jdubois** [comment]
Our current perf is very good, and I'm very happy with the EJS team and community.
Anyway, we're not going to change something so central in our project for a lib with just 3 GitHub stars.

**Comment by deepu105** [comment]
And most importantly it will be a humongous task to migrate all our templates which we are not willing to do without any concrete reasons sorry @Drulac
