### ISSUE TITLE
Support for new major release of Consul (version 1)

### ISSUE THREAD

**Issue by michaelstievenart** [jhipster/generator-jhipster#6962]
##### **Overview of the issue**
Adding Support for major release of Consul 1.0.* (Current stable release is 1.0.2)
Major release of Consul with a number of valuable fixes and improvements as well as
increased stability in Kubernetes.

Is there currently any plan to move consul to the new major version?

**Comment by jdubois** [comment]
Last time we tried it wasn't compatible with Spring Cloud. Maybe it's working now: if anybody has the time to try & test this....
We don't have "plans" for this kind of stuff -> if you have time to test this, don't hesitate to do a PR, we'll merge it

**Comment by DanielFran** [comment]
See: https://github.com/jhipster/generator-jhipster/issues/6755
