### ISSUE TITLE
Test fails with Social Login and MongoDB

### ISSUE THREAD

**Issue by WinterN** [jhipster/generator-jhipster#6968]
##### **Overview of the issue**

I just created a monolithic application with social login and MongoDB. After the application is succesfully created, if run ./mvnw clean package it return 2 failing tests and 8 error test, all from SocialServiceIntTest.java

<details>
<summary>Maven ouput</summary>
<pre>
Failed tests: 
  SocialServiceIntTest.testCreateSocialUserShouldCreateUserIfNotExist:149 
Expecting Optional to contain a value but was empty.
  SocialServiceIntTest.testCreateSocialUserShouldNotCreateUserIfEmailAlreadyExist:306 expected:<1[2]L> but was:<1[3]L>
Tests in error: 
  SocialServiceIntTest.testCreateSocialUserShouldCreateActivatedUserWithRoleUserAndPassword:192 » NoSuchElement
  SocialServiceIntTest.testCreateSocialUserShouldCreateSocialConnection:282 » NoSuchElement
  SocialServiceIntTest.testCreateSocialUserShouldCreateUserWithExactLangKey:216 » NoSuchElement
  SocialServiceIntTest.testCreateSocialUserShouldCreateUserWithLoginSameAsEmailIfNotTwitter:237 » NoSuchElement
  SocialServiceIntTest.testCreateSocialUserShouldCreateUserWithSocialInformation:169 » NoSuchElement
  SocialServiceIntTest.testCreateSocialUserShouldCreateUserWithSocialLoginWhenIsTwitter:258 » NoSuchElement
  SocialServiceIntTest.testCreateSocialUserShouldNotChangeUserIfEmailAlreadyExist:332 » NoSuchElement
  SocialServiceIntTest.testCreateSocialUserShouldSendRegistrationValidationEmail:358 » NoSuchElement

Tests run: 177, Failures: 2, Errors: 8, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.445 s
[INFO] Finished at: 2018-01-10T12:38:15+01:00
[INFO] Final Memory: 55M/538M
[INFO] ------------------------------------------------------------------------
</pre>
</details>

##### **Motivation for or Use Case**

I'd like to use social login in my new application.

##### **Reproduce the error**

Create a new application with the options described below. Then run ./mvnw clean package.

##### **JHipster Version(s)**

```
tierdeck@0.0.0 /home/javier/sts-workspace/tierdeck
└── generator-jhipster@4.13.3 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.tierdeck.www",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "tierdeck",
    "packageName": "com.tierdeck.www",
    "packageFolder": "com/tierdeck/www",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

git version 2.11.0

node: v8.9.4

npm: 5.5.1

bower: 1.8.2

gulp:
[12:39:25] CLI version 1.2.2

yeoman: 1.8.5

yarn: 1.3.2

Docker version 1.13.1, build 092cba3

docker-compose version 1.8.0, build unknown

##### **Browsers and Operating System**

Ubuntu 17.04

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Oh I'm pretty sure this is because of https://github.com/jhipster/generator-jhipster/issues/6923

**Comment by WinterN** [comment]
It seems to be a different issue. I debugged the test and I found that the user is created in database, but the method call: userRepository.findOneByEmailIgnoreCase("mail@mail.com").get(); returns an empty Optional.

I thought about a cache problem. I removed the annotation @Cacheable(cacheNames = USERS_BY_EMAIL_CACHE) from that repository method and now all tests pass.
