### ISSUE TITLE
 Interceptors throw incorrect information.

### ISSUE THREAD

**Issue by jaoropeza** [jhipster/generator-jhipster#6975]
##### **Overview of the issue**
`errorhandler.interceptor.ts` received a variable error with:  `Observable_1.Observable.throw is not a function`

##### **Motivation for or Use Case**

`TypeError: Observable_1.Observable.throw is not a function
    at CatchSubscriber.eval [as selector] (auth-expired.interceptor.ts?d4a4:24)
    at CatchSubscriber.error (catchError.js?4f88:105)
    at XMLHttpRequest.onLoad (http.js?34ea:1596)
    at ZoneDelegate.invokeTask (zone.js?6524:424)
    at Object.onInvokeTask (core.js?593e:4747)
    at ZoneDelegate.invokeTask (zone.js?6524:423)
    at Zone.runTask (zone.js?6524:191)
    at ZoneTask.invokeTask [as invoke] (zone.js?6524:498)
    at invokeTask (zone.js?6524:1370)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js?6524:1388)`

##### **Reproduce the error**

Create a user with username `test` and email `test@test`. Then create a user with the same username or email. Note that the form doesn't show the warning: "Login already in use" or "Email address already in use"

##### **Related issues**

I didn't find something related.

##### **Suggest a Fix**

Add in the `auth-expired.interceptor.ts`, `errorhandler.interceptor.ts` and `notification.interceptor.ts` files the line: `import 'rxjs/add/observable/throw';`

##### **JHipster Version(s)**
4.13.3

##### **JHipster configuration**
```javascript
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "ErrorHandler",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "3236efaedc4f74652582baf80efb9de642053fa5",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es",
      "en"
    ]
  }
}
```

##### **Browsers and Operating System**

Google Chrome 63.0.3239.132  (64 bits) and Windows 10
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
This is related to https://github.com/jhipster/generator-jhipster/pull/6899, sorry about that. I missed that we use the `throw` operator.  We also use the `of` operator in some cases.

The fix is to add the following to [_vendor.ts](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/_vendor.ts#L27) next to the other rxjs imports.  Would you like to do the PR?
```
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/throw';
```

**Comment by jaoropeza** [comment]
Sure @ruddell, I do the PR.
Thanks.
