### ISSUE TITLE
Angular - LocalDatetime handling could be better

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#6984]
##### **Overview of the issue**
In Angular X, this is how Date are handled.

* When coming from the server, a String if converted to es-Date in Js by the jhipster front lib
* When edited, Date are converted in a {Year,Month,Day} json object, and affected to the same attribute
* Before sending to the server, the data is then converted in a string yyyy-mm-dd by the jhipster front lib
I think that with a little bit of engineering we could handle it better (for example, having a Date all along the process).

##### **Motivation for or Use Case**

This object edition trick is kind of hard to understand by the end user, and forces some guards and assertions when editing Date within JHipster.

##### **Reproduce the error**

Make a jdl with an attribute of type LocalDate

##### **Related issues**

Maybe [Angular TODO](https://github.com/jhipster/generator-jhipster/issues/5833)

##### **Suggest a Fix**

Modifying angular client lib and generator jhipster date handling

##### **JHipster Version(s)**

4.13.3
##### **JHipster configuration**

Choose Angular X as option

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

An entity, with a localDate attr

##### **Browsers and Operating System**

Mac, or Linux, depends...

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I agree this really can be improved. We could also consider using moment to support all the date conversions as it has methods to convert to Java date format back and forth etc.

**Comment by Tcharl** [comment]
Moment looks really nice for the purpose :-)! The first time I read the doc...

**Comment by jdubois** [comment]
Yes this part is definitely not good... Then be careful, that's very hard to have this correctly! I guess that's why nobody dared to touch this yet!
Then there's a huge added-value for our end-users here.

**Comment by NilsWild** [comment]
As far as i understand we would need a custom NgbDateAdapter for the datepicker part. the rest can be handeled relatively easy with the new strong typed HttpClient by providing correct constructors for each model that handle the Moment logic. we can then remove all the from and to server conversions currently done in the service.

Ever LocalDate Instant and ZonedDateTime would then by typed as Moment.

If you agree so far i could probably help implementing that.

**Comment by deepu105** [comment]
Yes please proceed

**Comment by Tcharl** [comment]
There's a nice calendar, but it's in the angular-material library.
NilsWild, sorry, but I threw a bottle in the sea: I can do it if you're busy, but I think you would do better than me ^^.

**Comment by NilsWild** [comment]
@Tcharl right now i am busy not sure when i can proceed, i do have my exams at university right now. I wouldn't go for another calendar as its another dependency and NgbDateAdapter enables an easy conversion in one place without the need to handle any json date anywhere except for NgbDateAdapter

**Comment by Tcharl** [comment]
I'm on it, I've a working ngx-defaut-sample, just have to push it back to the main codebase.
And yes, I added a new 'MomentNgbDateAdapter', as well as switched every entity generated dates to moments.
I'm just a little worried about this [6711](https://github.com/jhipster/generator-jhipster/issues/6711), which may overlap my contrib. I may implement both features

**Comment by ruddell** [comment]
PR merged
