### ISSUE TITLE
Errors when entity is named "Result"

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#6985]
##### **Overview of the issue**

Found when helping a user on stackoverflow, when there is an entity named `Result` generated code does not compile in java and has warning in angular.

See git repository: https://github.com/gmarziou/jh-6985

Errors in java compilation

~~~
[ERROR] COMPILATION ERROR :                                                                                                                                                                     
[INFO] -------------------------------------------------------------                                                                                                                            
[ERROR] /e:/projets/jhipster-projects/issues/result/src/main/java/it/manuelgozzi/conductiontest/web/rest/ResultResource.java:[52,16] variable result is already defined in method createResult(it.manuelgozzi.conductiontest.domain.Result)                                                                                                                                                     
[ERROR] /e:/projets/jhipster-projects/issues/result/src/main/java/it/manuelgozzi/conductiontest/web/rest/ResultResource.java:[74,16] variable result is already defined in method updateResult(it.manuelgozzi.conductiontest.domain.Result)                                                                                                                                                     
[INFO] 2 errors                                                                                                                                                                                 
~~~

https://github.com/gmarziou/jh-6985/blob/master/src/main/java/it/manuelgozzi/conductiontest/web/rest/ResultResource.java#L52

https://github.com/gmarziou/jh-6985/blob/master/src/main/java/it/manuelgozzi/conductiontest/web/rest/ResultResource.java#L74

Warning in angular code 

~~~
WARNING in ./src/main/webapp/app/entities/result/result-popup.service.ts
[45, 31]: Shadowed name: 'result'

 @ ./src/main/webapp/app/entities/result/index.ts 7:9-42
 @ ./src/main/webapp/app/entities/result/result.module.ts
 @ ./src/main/webapp/app/entities/entity.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
~~~

##### **Suggest a Fix**

Either we prevent from using Result as an entity name or we modify generated code.

I'd prefer to modify variable name in generated code from `result` to `savedResult` though it could cause issues for existing projects when upgrading JHipster.

WDYT?

##### **JHipster Version(s)**

```
conduction-tests@0.0.0 e:\projets\jhipster-projects\issues\result
`-- generator-jhipster@4.13.3 

```

https://github.com/gmarziou/jh-6985/blob/master/src/main/webapp/app/entities/result/result-popup.service.ts#L45

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "it.manuelgozzi.conductiontest"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "ConductionTests",
    "packageName": "it.manuelgozzi.conductiontest",
    "packageFolder": "it/manuelgozzi/conductiontest",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "enableHibernateCache": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Result (result) {
  obtainedMarks String,
  percentage Double,
  appearedOn String
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.12.0.windows.1

node: v8.9.3

npm: 5.5.1

bower: 1.8.0

gulp:
[17:47:14] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.06.2-ce, build cec0b72

docker-compose version 1.14.0, build c7bdf9e3

##### **Browsers and Operating System**

N/A

**Comment by jdubois** [comment]
It's much easier for us to add Result to the list of reserved keywords -> @gmarziou are you fine with that? Could you do a PR?

**Comment by gmarziou** [comment]
OK I will do it.

**Comment by jdubois** [comment]
Thanks!!

Le 16 janv. 2018 00:08, "Mathieu ABOU-AICHI" <notifications@github.com> a
écrit :
