### ISSUE TITLE
UAA Cookie generation : "Not a valid domain name" error raised, when the uaa server is called with a direct IP address

### ISSUE THREAD

**Issue by Mimetis** [jhipster/generator-jhipster#6986]
##### **Overview of the issue**

I'm using the microservices architecture within the UAA server.   
Basically, everything is running on a local dev machine, but it's not working as expected once deployed in a cloud kubernetes environment.   
It seems that a kubernetes cluster without any domain causes the failure during cookie generation.  
Indeed, my cluster uses direct IP without any domain (ie! my test application address is [http://52.174.25.153:8080](http://52.174.25.153:8080) for instance.

##### **Reproduce the error**

For testing purpose, just create:
* A simple helloworld application using one Gateway, one MicroService and one UAA server.
* Deploy it to any cloud kubernetes solution
* Test the authentication process (using admin / admin to log in) 

##### **Suggest a Fix**

After getting the logs from my Gateway pods, it seems that the bug occurs in the `getCookieDomain` method in the `OAuth2CookieHelper` class

```
        //strip off subdomains, leaving the top level domain only
        InternetDomainName domainName = InternetDomainName.from(domain);

```

Here is the (simplified) stacktrace from my pod logs:

```
java.lang.IllegalArgumentException: Not a valid domain name: '52.174.25.153'
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:210)
        at com.google.common.net.InternetDomainName.<init>(InternetDomainName.java:155)
        at com.google.common.net.InternetDomainName.from(InternetDomainName.java:216)
        at com.mycompany.myapp.security.oauth2.OAuth2CookieHelper.getCookieDomain(OAuth2CookieHelper.java:296)
        at com.mycompany.myapp.security.oauth2.OAuth2CookieHelper.createCookies(OAuth2CookieHelper.java:109)
        at com.mycompany.myapp.security.oauth2.OAuth2AuthenticationService.authenticate(OAuth2AuthenticationService.java:70)
        at com.mycompany.myapp.web.rest.AuthResource.authenticate(AuthResource.java:51)

```

##### **JHipster Version(s)**

```
contoso@0.0.0 C:\PROJECTS\JHIPSTER\Jhispter-Kubernetes\contoso
`-- generator-jhipster@4.13.2

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

``` xml
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "microservicePath": "../catalog"
    },
    "jhipsterVersion": "4.13.2",
    "baseName": "contoso",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>
```

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
``` 
<details>
<summary>JDL entity definitions</summary>
<pre>
</pre>
</details>
``` 

##### **Environment and Tools**

java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

git version 2.15.1.windows.2
node: v9.3.0
npm: 5.5.1
yeoman: 2.0.0
yarn: 1.3.2
Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a96
##### **Browsers and Operating System**

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Mimetis** [comment]
By the way, adding a DNS name in my cloud configuration made it works as expected.   
For instance 
* Accessing the JHipster application through http://52.174.25.153:8080 doesn't work (at least communication with the UAA server) 
* Accessing the JHipster application through the sub domain registered ( http://snowkub.westeurope.cloudapp.azure.com:8080 for instance) works very well !

Sebastien

**Comment by Mimetis** [comment]
Yep, the idea is to find another solution than a cookie if we have an IP ;)
The problem is that it's working on a dev machin and not in a production mode

**Comment by jdubois** [comment]
Oh sorry I didn't recognize you @Mimetis !
So the bug is in our code, but I don't think it's possible to use a cookie on an IP address anyway - so I'm not sure of what we can do here
