### ISSUE TITLE
Not allowed to navigate top frame to data URL error when trying to open a blob object on Google Chrome

### ISSUE THREAD

**Issue by stefanobertini** [jhipster/generator-jhipster#6988]
##### **Overview of the issue**

When opening a Blob Attachment, Chrome shows an empty page.
Looking at the console you can find this error:
**http://localhost:8080/app/components/util/data-util.service.js:66 Not allowed to navigate top frame to data URL**

##### **Motivation for or Use Case**

Seems related to this: https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/top$20level$20data/blink-dev/GbVcuwg_QjM/JY6uJ6Q4BwAJ

##### **Reproduce the error**

Just create an entity with a blob field.
Run the app and add an entry to that entity, attaching a file.
Save the new entity and open it again.

Pressing "open" on the blob field causes the error.

##### **JHipster Version(s)**

4.13.3

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gestione-cv@0.0.0 /Users/sbertini/Progetti/Plansoft/GestioneCV
└── generator-jhipster@4.13.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "it.plan.gestionecv",
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "GestioneCV",
    "packageName": "it.plan.gestionecv",
    "packageFolder": "it/plan/gestionecv",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": [
      "it"
    ],
    "cacheProvider": "no",
    "enableHibernateCache": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Generated by JHipster IDE plugin
 */
entity Skill (skill) {
  descr String required maxlength(30),
  order Long required
}
entity ContractType (contract_type) {
  descr String required maxlength(30),
  order Long required
}
entity Seniority (seniority) {
  descr String required maxlength(30),
  order Long required
}
entity Person (person) {
  name String required maxlength(50),
  surname String required maxlength(50),
  birthdate LocalDate,
  email String pattern(.+@.+\..+),
  phone String pattern([0-9]+),
  cv AnyBlob,
  interviewdate LocalDate,
  interviewResult Long min(0) max(10),
  currentSalary String,
  contractLevel String,
  noticeDays Long,
  notes String
}

relationship OneToMany {
  Seniority{person} to Person{seniority(descr)},
  ContractType{person} to Person{contractType(descr)}
}
relationship ManyToMany {
  Person{skill(descr)} to Skill{person}
}

dto Skill, ContractType, Seniority, Person with mapstruct
service Skill, ContractType, Seniority, Person with serviceImpl
paginate Person with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.14.3 (Apple Git-98)

node: v6.10.1

npm: 5.6.0

bower: 1.8.0

gulp:
[15:20:32] CLI version 1.2.2
[15:20:32] Local version 3.9.1

yeoman: 2.0.0
yarn: 0.21.3

Docker version 17.09.1-ce, build 19e2cf6
docker-compose version 1.17.1, build 6d101fb

##### **Browsers and Operating System**

MacOs Sierra 10.12.6 
Google Chrome 63.0.3239.132

The problem happens only on Google Chrome

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by NilsWild** [comment]
I took a look at this issue i can't reproduce that with Google Chrome 63.0.3239.132 on ubuntu probably MacOs related? 

I did it with an xml file though. what did you use @stefanobertini ?
and i expect that you did use angular x
