### ISSUE TITLE
Remove AngularJS 1 from main generator and move to blueprint

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#6991]
We have decided to remove support for AngularJS version 1.x from the core generator for next major version.
The feature will be moved into a blueprint(beta feature) and will become an official blueprint which will be maintained independently of the core.

Team discussion here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/jhipster-dev/v5v4xgpu6Kc

**Comment by riaprocoumai** [comment]
What is name of blue print of angular js ?
