### ISSUE TITLE
import-jdl - error with new line without * char inside a comment block

### ISSUE THREAD

**Issue by henkelb** [jhipster/generator-jhipster#6994]
##### **Overview of the issue**
When a new line begins without a * char:
![image](https://user-images.githubusercontent.com/8615775/34985823-10bd5d32-fabe-11e7-89ab-ae83bb2ff4c4.png)
After putting * char:
![image](https://user-images.githubusercontent.com/8615775/34987083-9ac3c2ec-fac2-11e7-958c-75707a730e7e.png)

In the jdl file, I temporary solved the issue by removing `skipClient for all` from the beginning of the file.

##### **Motivation for or Use Case**
On previous versions, this error was not being thrown => motivation: no backward compatibility
 
##### **Reproduce the error**

@see image capture

##### **Suggest a Fix**
I remeber that I once inspected the code that does the text retrieval from comments. I think that part has changed.

##### **JHipster Version(s)**

It is an upgradefrom 4.10.1 to **4.13.3**

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
C:\Users\PowerUser
`-- (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

git version 2.7.1.windows.2

node: v6.11.1

npm: 3.10.10

gulp:
[13:12:39] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.3.2

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Windows 10

- [ .] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Thanks for reporting this.
@jdubois I'll keep this one open and link to a new issue on JCore's issue tracker. When I'm done with it, I'll close the issue. Is that okay for you?

**Comment by jdubois** [comment]
@MathieuAA yes of course!

**Comment by MathieuAA** [comment]
@jdubois I don't think this is one is for me. The JDL in the screenshots (both of them) are valid according to the latest grammar. And it hasn't changed for comments in a long while (that, or I don't remember, which is actually possible).
In JDL Studio, however, the error is present after the parser consumes the JDL.

**Comment by deepu105** [comment]
May be JDL studio is using an older version of parser

**Comment by deepu105** [comment]
@MathieuAA I updated to latest parser but the error still exists. https://github.com/jhipster/jdl-studio/commit/7c062703c85de6f53248aee2e0ed7cc1952fff76

Let me see

@jdubois what is the process to update the jhipster-online branch? should I just merge gh-pages into it?  if there is anything special to be done could you plz add it to the contributing.md file
