### ISSUE TITLE
[feature] Add Possibility to change the default timeout of jhiAlertService

### ISSUE THREAD

**Issue by antarus** [jhipster/generator-jhipster#6996]
##### **Overview of the feature**
Hello, I would like the possibility to change the default timeout notifications of class JhiAlertService ng-jhipster project.

##### **Suggest a Fix**
Replace the line https://github.com/jhipster/ng-jhipster/blob/master/src/service/alert.service.ts#L57
by 
```this.timeout = config.alertTimeout```
and add in https://github.com/jhipster/ng-jhipster/blob/master/src/config.ts#35
``` alertTimeout? = 5000;```
This will give the user the ability to change the default configuration in jhispter app in the ```shared-libs.module.ts``` file.

##### **JHipster Version(s)**

4.13.3

- [ x] Checking this box is mandatory (this is just to show you read everything)

I can do the PR later after work.

Thanks

**Comment by deepu105** [comment]
You can do a PR if you wish. You can already override this while calling
the alert methods


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Thanks @antarus !
