### ISSUE TITLE
Angular project problems running on IE11

### ISSUE THREAD

**Issue by nachocoig** [jhipster/generator-jhipster#7001]
##### **Overview of the issue**

Maybe should add new polyfill in angular project, because when i try to run webapp, this fail.

##### **Motivation for or Use Case**

I need to use Internet Explorer 11, but i had problems.

##### **Reproduce the error**

1- Generate app.
2- Run app.
3- Use IE11 for access.
4- Try login and navigate to some administration component.
5- Show console.

##### **Related issues**

When I tried to run my app on Internet Explorer 11, i received the following error on IE console:

**EXCEPTION: Object doesn't support property or method 'includes'**

##### **Suggest a Fix**

In my case, only add these polyfills into polyfills.ts :

import 'core-js/es6/array';
import 'core-js/es7/array';

seen in https://github.com/angular/angular-cli/issues/4128

##### **JHipster Version(s)**

JHipster 4.11.1

##### **Browsers and Operating System**

Windows 10 and Internet Explorer 11

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes this was corrected on a recent version, and as you have v4.11.1, you are on an older release :-)
Thanks for the bug report!

**Comment by nachocoig** [comment]
ouch! Its true!!!
 
Im sorry! And thanks
