### ISSUE TITLE
Keycloak integration usage of sub

### ISSUE THREAD

**Issue by RobinKamps** [jhipster/generator-jhipster#7008]
##### **Overview of the issue**

I mentionend this in a comment before - just reporting this as an issue to be more manageable (find/close the issue etc.).

Keycloak default configuration sends sub (an uuid in this case) for auth-usage.

JHipsters Integration is using "preferred_username" in `UserService` as an unique identifier, wich is not intendend for this kind of usage 
(as the docs say: "The RP MUST NOT rely upon this value being unique", http://openid.net/specs/openid-connect-core-1_0.html search for preferred_username)

```
private static User getUser(Map<String, Object> details) {
        User user = new User();
        user.setLogin((String) details.get("preferred_username"));
```

##### **Motivation for or Use Case**

If you delete a user and then another user registers with same username in keycloak, 
he will impersonate the old user in jhipster.

(If you do not delete users ever in keycloak you wont have that problem)

##### **Reproduce the error**

Just do as above, perhaps with an user who owns entites.

##### **Related issues**

Login as pk/fk/Principal/sub is not best - it will be dropped in Spring 5 anyway.
Octa integration might be missing storing the sub, too.

##### **Suggest a Fix**

Get the sub stored as login just as a quick and dirty assumption to fix.
If you have already a userbase in jhipster sync with preferred_username as login, then of course you must select the uuid with preferred_username from keycloak and update them in jhipster afterwards.

How to restore a user then?
If you dropped an user by accident in keyclock, look his uuid up in jhipster userbase , than create a new user in keycloak and set his uuid as dbadmin in keycloak.

(more advanced perhaps make keycloak aware, that user has still data in your system/microservices etc. then decide if you want to allow drop, or force to wipe out all data together with user or to archieve user and data etc.)

**Comment by mraible** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/7106.
