### ISSUE TITLE
Support different types for primary key fields

### ISSUE THREAD

**Issue by cavarzan** [jhipster/generator-jhipster#7019]
##### **Overview of the issue**

Today jhipster supports only Long as primary key for entities in projects using JPA (relational databases).

The main idea is support different types of primary keys, like `Strings` generated by `UUID` (hibernate does it automatically), `ObjectId`, `UUID` itself or another strategy.

This could be an option in the jhipster configuration to select what type of primary key the user want to use, after that, another option is shown to select the strategy.

##### **Motivation for or Use Case**

There a few articles that represent the pros and cons about this approach, but I believe that many projects and companies opt for using string hashses / uuid for primary keys.

https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439

https://stackoverflow.com/questions/45399/advantages-and-disadvantages-of-guid-uuid-database-keys

https://medium.com/@jdedek/using-uuids-as-primary-keys-ca1fb409bb7c

https://medium.com/@Mareks_082/auto-increment-keys-vs-uuid-a74d81f7476a

##### **Reproduce the error**

N/A

##### **Suggest a Fix**

N/A

##### **JHipster Version(s)**

4.13.1

##### **JHipster configuration**

N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
https://github.com/jhipster/generator-jhipster/issues/5957

https://github.com/jhipster/generator-jhipster/issues/5147

https://github.com/jhipster/generator-jhipster/issues/4027

https://github.com/jhipster/generator-jhipster/issues/3060

https://github.com/jhipster/generator-jhipster/issues/1235

**Comment by deepu105** [comment]
Thanks @gmarziou, I was gonna look for them :smile:

**Comment by cavarzan** [comment]
@gmarziou well, I need to search better! hehehe
Since this was discussed before, you can close it if it's invalid.
