### ISSUE TITLE
Entity generator must save table name when prefixed to avoid reserved word

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#7028]
##### **Overview of the issue**

When creating an entity using a reserved word like Order, the entity sub generator adds a prefix to table name in generated code but does not save it to `.jhipster/Order.json`, as a consequence, export-jdl cannot generate correct JDL

~~~
jhipster entity Order

The entity Order is being created.

WARNING! The table name cannot contain the 'ORDER' reserved keyword, so it will be prefixed with 'jhi_'
~~~

.jhipster/Order.json

~~~json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "total",
            "fieldType": "Integer"
        }
    ],
    "changelogDate": "20180120224654",
    "dto": "no",
    "service": "no",
    "entityTableName": "order",
    "jpaMetamodelFiltering": false,
    "pagination": "no",
    "microserviceName": "order",
    "searchEngine": false
}
~~~

##### **JHipster Version(s)**

```
order@0.0.0 /home/gael/jhipster/issues/order2
└── generator-jhipster@4.13.3 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "order",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Order (order) {
  total Integer
}

microservice Order with order

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.14.1

node: v8.9.3

npm: 5.5.1

yarn: 1.3.2

Docker version 17.10.0-ce, build f4ffd25

docker-compose version 1.14.0, build c7bdf9e

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
@gmarziou Thanks for reporting this, I'm on it!

**Comment by gmarziou** [comment]
@MathieuAA export-jdl works well with table names specified in Order.json so the issue is only in teh entity generator when saving to JSON. I can handle it if you want.

**Comment by MathieuAA** [comment]
@gmarziou that'd be great, thanks :)

**Comment by gmarziou** [comment]
OK I have rewritten the issue.
