### ISSUE TITLE
remap-istanbul break code coverage and CI

### ISSUE THREAD

**Issue by Dufgui** [jhipster/generator-jhipster#7031]
##### **Overview of the issue**

It's not our problem but just to follow the problem and upgrade to the new version of:
"karma-remap-istanbul": "0.6.0",
"karma-sourcemap-loader": "0.3.7",
When they solve it.

##### **Motivation for or Use Case**

Build from CI failed now with last version of source-map (7.0) and remap-istambul.
21 01 2018 18:48:53.449:ERROR [karma]: TypeError: sourceMap.originalPositionFor is not a function
    at getMapping (/home/travis/app/node_modules/remap-istanbul/src/getMapping.js:19:26)
    at getMappingResolved (/home/travis/app/node_modules/remap-istanbul/src/CoverageTransformer.js:171:20)
    at remapBranch (/home/travis/app/node_modules/remap-istanbul/src/remapBranch.js:6:19)
    at /home/travis/app/node_modules/remap-istanbul/src/CoverageTransformer.js:181:17
    at Array.forEach (<anonymous>)
    at CoverageTransformer.addFileCoverage (/home/travis/app/node_modules/remap-istanbul/src/CoverageTransformer.js:177:39)
    at /home/travis/app/node_modules/remap-istanbul/src/CoverageTransformer.js:235:10
    at Array.forEach (<anonymous>)
    at CoverageTransformer.addCoverage (/home/travis/app/node_modules/remap-istanbul/src/CoverageTransformer.js:233:5)
    at /home/travis/app/node_modules/remap-istanbul/src/remap.js:34:7
    at Array.forEach (<anonymous>)
    at remap (/home/travis/app/node_modules/remap-istanbul/src/remap.js:33:11)
    at KarmaRemapIstanbul.onRunComplete (/home/travis/app/node_modules/karma-remap-istanbul/index.js:58:23)
    at Server.<anonymous> (/home/travis/app/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:131:20)
    at Server.emit (events.js:214:7)

##### **Reproduce the error**

launch yarn test 

##### **Related issues**

https://github.com/SitePen/remap-istanbul/issues/160

##### **Suggest a Fix**

wait new version and upgrade to it

##### **JHipster Version(s)**

NA

##### **JHipster configuration**

NA

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

NA

##### **Browsers and Operating System**

NA

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Thanks so much! I knew we had this kind of issue, but no time to look at it!

**Comment by Dufgui** [comment]
it's lock my PR. I am egoist ;o)

**Comment by Dufgui** [comment]
If they don't fix it quickly, we can use package.json resolution to fix sub dependency. 
"resolutions": {
    "source-map": "0.6.1"
  }

**Comment by bahrmichael** [comment]
+1, no more prod builds :(

**Comment by pascalgrimaud** [comment]
Thanks @Dufgui for the analyze.

IMO, not sure if we should wait them for a new release. 
We should apply the fix you suggested, and as soon as there is a new release, we can revert the fix, and upgrade the version.

The fix must be similar to this https://github.com/jhipster/generator-jhipster/pull/6912
So, it will work for both: NPM and Yarn

**Comment by jdubois** [comment]
No we should not wait for them:

- you never know when they will fix it
- they already broke everyone's build, let's not trust them too much

That's at least the 3rd time this happens for us, and each time we fixed it ourselves, before (of course) switching back once the project has corrected his issue.

**Comment by jdubois** [comment]
I'm doing the fix

**Comment by jdubois** [comment]
If the build passes, should I do an emergency patch release? Not sure when I'll have time

**Comment by pascalgrimaud** [comment]
This fix will work for Yarn, but not for NPM, I think.
We need to do similar fix than https://github.com/jhipster/generator-jhipster/pull/6912/files

**Comment by deepu105** [comment]
@jdubois The fix should be on the template files and not on our package.json I guess. Anyway i'm fixing this dont worry

**Comment by deepu105** [comment]
done, lets wait for CI

**Comment by jdubois** [comment]
Oh yes sorry ! I'm on my mobile too, fixing bugs from the Paris subway :-)

Le 21 janv. 2018 14:50, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
Oh, can you also do this fix on the spring-boot-2 branch? I'm eager to see
if it's green now I migrated Elasticsearch tests to use mocks.

**Comment by deepu105** [comment]
Sure will do


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
done

**Comment by deepu105** [comment]
Master builds seems to be passing. Once green i'll retrigger some of the PR that are on hold coz of this

@jdubois what do you think of enabling the below settings for the master branch? It will let us update PRs to use the latest branch easily using a button on PR? 
![image](https://user-images.githubusercontent.com/1107223/35195088-7553d9f2-febe-11e7-9252-54935bac277d.png)

**Comment by jdubois** [comment]
Not sure this is a good idea as master moves too fast - it's impossible to follow

**Comment by juliusdavies** [comment]
I found pinning "remap-istanbul" worked better for me instead of pinning "source-map":

  "resolutions": {
      "remap-istanbul": "0.9.6"
  },

More info here:  https://github.com/SitePen/remap-istanbul/issues/160

**Comment by deepu105** [comment]
Would you like to PR?


Thanks & Regards,
Deepu
