### ISSUE TITLE
Microservices: HTTP 403 for the micro-app URL /v2/api/docs from the gateway

### ISSUE THREAD

**Issue by ndywicki** [jhipster/generator-jhipster#7038]
##### **Overview of the issue**

Hello Jhipster team, 
I have an issue with microservices and Zuul: an micro application API docs can't be reachable from the gateway URL (ie. http://localhost:8080/app1/v2/api/docs)

![gateway_error_500](https://user-images.githubusercontent.com/1721344/35248928-42ff697c-ffd0-11e7-8a72-72ef77c57805.JPG)

**Notes:**

* Root cause is an HTTP 403 from ZullRequest result. Backend gateway log:

```
2018-01-22 22:02:57.278  INFO 6 --- [ XNIO-2 task-10] c.m.myapp.security.jwt.TokenProvider     : Invalid JWT signature.
2018-01-22 22:02:57.281  INFO 6 --- [  XNIO-2 task-9] c.m.myapp.security.jwt.TokenProvider     : Invalid JWT signature.
2018-01-22 22:02:57.415  WARN 6 --- [ XNIO-2 task-10] o.z.p.spring.web.advice.AdviceTrait      : Unauthorized: Full authentication is required to access this resource  
```

* With trace on Zuul `RequestContext`:

```
context:{retryable=false, 
request=org.springframework.cloud.netflix.zuul.filters.pre.Servlet30RequestWrapper@3326a449, 
ignoredHeaders=[set-cookie, 
expires, 
x-content-type-options, 
x-xss-protection, 
cookie, 
x-frame-options, 
cache-control, 
pragma], 
originResponseHeaders=[com.netflix.util.Pair@55de715b], 
zuulRequestHeaders={x-forwarded-host=localhost:8080, 
x-forwarded-proto=http, 
x-forwarded-prefix=/app1, 
x-forwarded-port=8080, 
x-forwarded-for=172.18.0.1}, 
zuulEngineRan=true, 
requestURI=/v2/api-docs, 
isDispatcherServletRequest=true, 
responseStatusCode=403, 
proxy=app1, 
response=com.netflix.zuul.http.HttpServletResponseWrapper@1564f70c, 
sendZuulResponse=false, 
executedFilters=ServletDetectionFilter[SUCCESS][1ms], 
Servlet30WrapperFilter[SUCCESS][2ms], 
AccessControlFilter[SUCCESS][0ms], 
PreDecorationFilter[SUCCESS][1ms], 
TokenRelayFilter[SUCCESS][0ms], 
serviceId=app1}
````

* Then issue cause an HTTP 500 for an nullPointerException in SwaggerBasePathRewritingFilter:

```
com.netflix.zuul.exception.ZuulException: Filter threw Exception
....
Caused by: java.lang.NullPointerException: null
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at com.mycompany.myapp.gateway.responserewriting.SwaggerBasePathRewritingFilter.rewriteBasePath(SwaggerBasePathRewritingFilter.java:63)
        at com.mycompany.myapp.gateway.responserewriting.SwaggerBasePathRewritingFilter.run(SwaggerBasePathRewritingFilter.java:52)
        at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
        at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
```
  
* Same issue with jhipster-registy or Consul configuration
* Only in Prod configuration (no problem in dev mode) with all stack deployed on Docker or Openshift
* I've also try to rise the Hystrix timeout

##### **Motivation for or Use Case**

Microservice gateway can't access to the API docs backend

##### **Reproduce the error**

Generate micro application with standard options (`app1`)
Generate gateway with standard options (`gateway`)
Generate Docker-compose files
Package and create docker images for app and gateway (`mvnw verify -Pprod dockerfile:build`)
Run all : app1, gateway, databases, jhipster-registry (`docker-compose up -d`)
Login in the Gateway and go to API > app1/v2/api-docs

##### **Related issues**

Maybe : 
* https://github.com/jhipster/generator-jhipster/pull/3329
* https://github.com/jhipster/generator-jhipster/pull/3113

JWT token seem the issue, but the `/v2/api-docs/**`  was setup with `permitAll` in Spring Security.
Why with prod configuration ? It's a mystery.

##### **Suggest a Fix**

No idea

##### **JHipster Version(s)**

```
app-1@0.0.0 C:\workspace\jhipster\bug-micro\app1
`-- generator-jhipster@4.13.3

```

```
gateway@0.0.0 C:\workspace\jhipster\bug-micro\gateway
`-- generator-jhipster@4.13.3

```

###### App1

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "app1",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8082",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

###### Gateway

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

###### Docker

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "appsFolders": [
      "app1",
      "gateway"
    ],
    "directoryPath": "../",
    "gatewayType": "zuul",
    "monitoring": "no",
    "serviceDiscoveryType": "eureka",
    "adminPassword": "admin",
    "jwtSecretKey": "replaced-by-jhipster-info"
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.9.3.windows.1

node: v8.9.1

npm: 5.5.1

gulp:
[23:38:31] CLI version 3.9.1

yeoman: 1.8.5

yarn: 1.3.2

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a96

##### **Browsers and Operating System**

Windows 10 Pro Version 10.0.16299 Numéro 16299

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Can you show your generated docker-compose file too ?

**Comment by ndywicki** [comment]
Hi Pascal,

Please find archive contains all docker-compose generated project.

[docker.zip](https://github.com/jhipster/generator-jhipster/files/1655049/docker.zip)

**Comment by pascalgrimaud** [comment]
I can't reproduce your issue. Everything works fine with your exact configuration and the `docker-compose.yml` you provided.

![capture d ecran de 2018-01-23 22-11-00](https://user-images.githubusercontent.com/9156882/35300920-550f96a4-008a-11e8-8c1a-4572c1a0dada.png)

It is really similar to the discussion in this ticket: https://github.com/jhipster/jhipster-registry/issues/237
Can you have a look?

According to your error `c.m.myapp.security.jwt.TokenProvider     : Invalid JWT signature.` it's like your Registry didn't share the configuration in `central-server-config/application.yml`, and specially the `jhipster.security.authentication.jwt.secret`

As you are with Windows, maybe it's because your `docker-compose.yml` is not under `C:\Users\<username>` : that would explain why the volume are not mounted. To confirm it, try:
- enter the registry container with `docker exec -it docker_jhipster-registry_1 sh`
- then, check: `cat central-config/application.yml`

**Comment by ndywicki** [comment]
I thought your remark was point the finger at the probleme of the docker mount point. In particulare with this issue https://github.com/docker/for-win/issues/1560 for example.
Unfortunately, I still have the same issue. 
I deleted the containers and the volumes, restarted all via a `docker-compose up -d`.
I also use the full path instead of relative path.
The file `central-config/application.yml` is correctly mapped inside the container:

```
λ docker exec -it 1d sh
/ # ls
bin                    media                  sys
central-config         mnt                    target
dev                    proc                   tmp
etc                    root                   usr
home                   run                    var
jhipster-registry.war  sbin
lib                    srv
/ # cat central-config/application.yml
#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: 30dxxxxxxxxxxxxxxxxxxxxxx872

eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
/ #
```

JHipster-Registry UI show the same configuration and Gateway UI show also app1 up
I still investigating and I'll try on a Linux vm.

Thanks

**Comment by ndywicki** [comment]
Hi Pascal,

I see on your screen that you use Swagger UI from Jhipster Registry. I tried and it work for me.
Could you please confirm that work with the Swagger UI of the Gateway for you ?

In case of Consul is the registry the only acces of Swagger UI is on the Gateway.

Thanks.

**Comment by pascalgrimaud** [comment]
@ndywicki : oh ok, reproduced.

Same stack than you, with `500 : {"timestamp":"2018-01-24T21:21:24.950+0000","status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"post:SwaggerBasePathRewritingFilter"} http://localhost:8080/app1/v2/api-docs`

**Comment by pascalgrimaud** [comment]
@ndywicki : I understand now, and it's the normal behaviour.
The name of your microservice is **app1**.

You can look at `application-prod.yml` of your **gateway**. You have this configuration:
```json
jhipster:
    gateway:
        rate-limiting:
            enabled: false
        authorized-microservices-endpoints: # Access Control Policy, if left empty for a route, all endpoints will be accessible
            app1: /api
```

So, the Zuul route is defined for `/app1/api` only, not for `/app1/v2`, which is used for Swagger. You can simply redefined this value and everything should work fine.
Some solutions:
1) modify your `application-prod.yml` in `gateway`, and repackage everything

2) or, you can add `gateway.yml` in your `central-server-config` folder:

```yaml
jhipster:
    gateway:
        authorized-microservices-endpoints: # Access Control Policy, if left empty for a route, all endpoints will be accessible
            app1: /api,/v2
```
Don't let it blank value, otherwise, it will use the default value in your gateway.war

3) use env variable in your docker-compose file

I'm closing this, as I think there is no bug here.
Don't hesitate to comment or reopen, if you think there is still a real issue

**Comment by ndywicki** [comment]
Oh ok, Its more clear for me now. I added `/v2` path in application-prod.yml and its ok.
 
May be I'll purposed a PR to avoid the nullPointerException in `SwaggerBasePathRewritingFilter` and have the right HTTP error code in case of Zuul route issue.

Many thanks Pascal

**Comment by pascalgrimaud** [comment]
A `NullPointerException` is always bad and if we can avoid it, it should be better.
But I don't have suggestion on how to handle it, so go ahead ;)
