### ISSUE TITLE
Adding DateTime option to jdl

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#7040]
##### **Overview of the issue**

Using JDL to generate entities with mysql database gives already two options for dates:
LocalDate and ZonedDateTime. LocalDate will be a date field in mysql, ZonedDateTime will be a timestamp. In the front-end a LocalDate will get a nice calendar gui and ZonedDateTime not.

What i would like to add (to make jhipster even better) is a Datetime field. As I understand it timestamp is used for automatic increments like for createnDate or modificationDate. Datetime is used (like date) for domain fields like start of project. 
This datetime field could have a calendar gui with date and time selection option.

If adding datetime will make stuff to complex it would at least be cool to have a calendar gui with date and time option for the ZonedDateTime.

##### **Workaround**

Use a LocalDate and change the liquibase generated file to create a Datetime instead of a Date column. 
I have not jet found where to change the datepicker.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by tibistibi** [comment]
found this issue #5006 where is explained that the datepicker does not support time's :(

**Comment by jdubois** [comment]
Indeed, that's why we couldn't do it :-(
Maybe in a future release of ng-bootrap (but yes we lost a lot of great features when migrating from AngularJS 1 to Angular X!!)

**Comment by tibistibi** [comment]
so there is no option for date and time fields :(

**Comment by tibistibi** [comment]
and what about the difference between timestamp and datetime?

**Comment by jdubois** [comment]
Currently I don't think so with ng-bootstrap, but they are currently moving faster so this needs to be checked - or maybe help the project (that would be the best thing to do).
Another solution is to use our PrimeNG support (have a look in the marketplace, it's currently number 1), but adding it just for one component is a bit overkill

**Comment by tibistibi** [comment]
anyone looked into this one?
https://npm.runkit.com/ng-bootstrap-datetime-picker

**Comment by tibistibi** [comment]
i think it is based on this one:
https://ng-bootstrap.github.io/#/components/timepicker/api

would that be better than PrimeNG?

**Comment by deepu105** [comment]
I think thats the plugin we use for AngularJS, but for ng-bootstrap there
is no plugin yet, its not difficult to build we can combine datepicker and
timepicker to build a component in ng-jhipster, that would be the best
solution. Feel free to do that if you are up for it.


Thanks & Regards,
Deepu

**Comment by tibistibi** [comment]
@deepu105 this one seems to be from bootstrap:
https://npm.runkit.com/ng-bootstrap-datetime-picker

**Comment by tibistibi** [comment]
@deepu105 sorry wrong link. this is the base project link:
https://www.npmjs.com/package/ng-bootstrap-datetime-picker

**Comment by deepu105** [comment]
No it is for ui-bootstrap which is for angular 1, check their docs. We use
ng-bootstrap, the plugin has misleading name


Thanks & Regards,
Deepu

**Comment by tibistibi** [comment]
@deepu105 thanks that was not clear to me. so to conclude this one 
https://ng-bootstrap.github.io/#/components/timepicker/api
is good but there is no option (jet) to you both date and timepicker on one field.
