### ISSUE TITLE
Microservice Gateway with React

### ISSUE THREAD

**Issue by jcarlosmorales** [jhipster/generator-jhipster#7041]
##### **Overview of the issue**
I have a problem when i am trying to create a Gateway with React

##### **Motivation for or Use Case**

I think that is not implement yet.

##### **Reproduce the error**

You can see the image to reproduce the error:
![jhipster1](https://user-images.githubusercontent.com/35455826/35271135-6f13def6-0031-11e8-9085-ea5dbe79e6a3.JPG)

And this is the error:

![jhipster2](https://user-images.githubusercontent.com/35455826/35271503-9efb6a16-0032-11e8-984c-f7922d0192f7.JPG)

##### **Related issues**

This issue #6999 is closed and similar. 

##### **Suggest a Fix**

I haven´t idea to suggest a fix.

##### **JHipster Version(s)**
v4.13.3

##### **JHipster configuration**

I can't see it because the project isn't created

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not entity in this moment.

##### **Browsers and Operating System**

I can't open it because the project isn't created
Operating System: Linux

**Comment by jdubois** [comment]
This is not implemented yet, React is "experimental", this just not done yet - but help is definitely welcome on this part (nobody works on this at the moment)

**Comment by jcarlosmorales** [comment]
How shall i help you?

**Comment by deepu105** [comment]
You can try to fix the templates/features for the gateway for example and
submit the PR


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Yes have a look at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md and then the React code is in our master branch
