### ISSUE TITLE
Remove gatling-maven-plugin

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7042]
The gatling-maven-plugin is great as it's automatically configured, but it causes numerous issues with our builds, as it uses the same classpath as the rest of the project:

- This is why Gatling doesn't work with Kafka in JHipster 4.
- With Spring Boot 2, we will upgrade many things, including Netty, and those all fail with Gatling (which uses an older Netty version). At the moment, this prevents our Cassandra build from running (as Cassandra uses Netty), and the gatling-maven-plugin fails in all projects, probably because Undertow uses Netty underneath.

I don't know how it works with Gradle, but that's yet another issue as we need to be in sync with both build tools.

As Gatling can be installed standalone, this would be a much better solution as it doesn't cause any issue with our classpath, so here is what I will do:

- Keep all currently generated Gatling test (we will need to validate that they still work in v5, once the build is stable)
- Remove the Maven gatling-maven-plugin (as well as the gatling-charts-highcharts dependency we have in the test scope, and which also causes issues)

**Comment by jdubois** [comment]
Done in https://github.com/jhipster/generator-jhipster/commit/0e12c2a8a580d6a266c490d518f85597ff1a281c

**Comment by atomfrede** [comment]
In gradle the problem should not be as significant as it is with maven (just experienced it today with a simple mvn, spring boot project and log4j2). In gradle we use different configurations for the gatling and the application test part, but of course there may be overlapping parts (need to check).

**Comment by jdubois** [comment]
Yes I had a quick look and this *could* be OK with Gradle, that's why I left it

**Comment by cbornet** [comment]
You just made a gift to the gRPC module :smile:
