### ISSUE TITLE
selected profile doesn't work

### ISSUE THREAD

**Issue by erichui2017** [jhipster/generator-jhipster#7048]
##### **Overview of the issue**

selected profile doesn't work.

##### **Reproduce the error**

1. package the uaa/gateway project use mvn package -Pprod
2. "java -jar uaa.war"  on ubuntu server,
the war start use dev profile not the prod profile。i have to use "--spring.profiles.active=prod" to active prod profile.

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This depends on your version, but as you don't provide it (please follow the guidelines!) we can't help you.
