### ISSUE TITLE
Integrate with web3j.io ( Feature request )

### ISSUE THREAD

**Issue by duymap** [jhipster/generator-jhipster#7053]
##### **Overview of the issue**

Due to the trend of decentralize app using Etherum platform, it would be great if we can have options to tick feature web3j into spring app.
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
It would be interesting to do this in a module, but not directly in generator-jhipster, as it's a specific need.
You can have a look at this page: http://www.jhipster.tech/modules/creating-a-module/

Don't hesitate to reply in this ticket as soon as you started it.
