### ISSUE TITLE
Update to webpack 4

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7055]
Webpack 4 beta is out and release is planned in a month. It brings in lot of performance improvement and simplified config. Would be nice to have for v5 on both Angular and React

Work should start once we make master v5 branch

**Comment by deepu105** [comment]
@sendilkumarn as a webpack contributor, I think you are the best person to do this. Can I assign this to you?

**Comment by sendilkumarn** [comment]
ofcourse yes. I am actually waiting for our plugin's migration.

**Comment by wmarques** [comment]
I tried to upgrade without success, too many plugins are not yet upgraded as @sendilkumarn said :(

**Comment by deepu105** [comment]
lets wait then


Thanks & Regards,
Deepu

**Comment by notflorian** [comment]
Webpack 4 has been released today : https://medium.com/webpack/webpack-4-released-today-6cdb994702d4

**Comment by wmarques** [comment]
I check this tonight !

**Comment by sendilkumarn** [comment]
@wmarques I will create a PR. 

We need to change the webpack-dev-server to all new and shiny webpack-serve 

then we are good to go, I guess

**Comment by jdubois** [comment]
I'm eager to see the perf improvement!

**Comment by sendilkumarn** [comment]
well in dev we get around 1-3s faster builds 
on prod, it is around 3-4s 
(it varies wildly between builds, there will be some corner cases I think)

OTOH, would love to see what @deepu105 's laptop is showing 😉 😛

**Comment by deepu105** [comment]
Webpack was claiming upto 80% increase in speed. Thats a bit disappointing

On 27 Feb 2018 11:27 pm, "Julien Dubois" <notifications@github.com> wrote:

Closed #7055 <https://github.com/jhipster/generator-jhipster/issues/7055>
via #7186 <https://github.com/jhipster/generator-jhipster/pull/7186>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/7055#event-1495511211>,
or mute the thread

**Comment by jdubois** [comment]
And on my `yarn test` on my project I went from 150 seconds to 180 seconds :-(

**Comment by jdubois** [comment]
And we also don't gain anything in Travis, in fact the master branch looks a bit slower -> so Spring Boot 2 + Webpack 4 don't make us gain anything, it's a bit disappointing, indeed
