### ISSUE TITLE
A microservices gateway cannot be turned into a PWA

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7058]
When you create a microservices gateway, the `index.html` file has the commented code for service workers, but there's no `sw.js` created, nor is there any entries for it in webpack files. I think it should be possible to make a gateway into a PWA. Therefore, this file and entry should be added when creating a gateway.

**Comment by ruddell** [comment]
The hardcoded sw.js file [was removed](https://github.com/jhipster/generator-jhipster/pull/6716) in favor of one that is dynamically generated by [workbox-webpack-plugin](https://www.npmjs.com/package/workbox-webpack-plugin).  If you uncomment the code in index.html, it should load when running in `prod`

**Comment by mraible** [comment]
Cool! I just tried it and it worked. Is that documented anywhere? At the very least, it should be in the README (IMHO). I fumbled through this in my Pluralsight video last week and thought it was a bug.

**Comment by ruddell** [comment]
The readme mentions:
>Note: workbox creates the respective service worker and dynamically generate the sw.js
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/_README.md#service-workers

**Comment by mraible** [comment]
Great! I'll close this issue then.
