### ISSUE TITLE
[Feature Request] Support for Vue Js UI Generators

### ISSUE THREAD

**Issue by bhavik1st** [jhipster/generator-jhipster#7066]
##### **Overview of the issue**

Vue generator for Jhipster (have angular/react/ionic already)

##### **Motivation for or Use Case**

Vue is easy to use and popular UI framework with good performance compared to angular.

##### **JHipster Version(s)**

All-Latest

**Comment by jdubois** [comment]
Unfortunately, there are lots of people who ask for VueJS, but nobody is ready to work on that feature.
The current core team is already having a very hard time maintaining AngularJS and Angular, and now adding React. It is not possible for the current team to provide yet another option, even if we would like to have it.
So unless a team of contributors gathers and works on that feature, like we have for many other features, this simply won't be done.

As we have already asked for help several times on Twitter on this, and nobody wanted to work on this, I'm closing this, as it is unlikely this is done in the next year.
