### ISSUE TITLE
[Feature Request]  Support Oracle 12.2 with 128 bytes maximum object name length

### ISSUE THREAD

**Issue by develguys** [jhipster/generator-jhipster#7070]
##### **Overview of the issue**

Add an option to bypass the maximum (30) table name length or joinTableName

##### **Motivation for or Use Case**

In Oracle 12.2 and above the maximum object name length is 128 bytes.

##### **JHipster Version(s)**

All-Latest

**Comment by deepu105** [comment]
You can make PR to upgrade to this version and increase the limit

**Comment by jdubois** [comment]
Yes @develguys it's hard for us to test on Oracle, as it requires a license.
That would remove lots of annoying code in JHipster, so big +1 from me.

**Comment by develguys** [comment]
I will try to implement this feature.

**Comment by jdubois** [comment]
Awesome!

**Comment by jdubois** [comment]
If nobody is doing this I remove this for the moment:

- This will cause issues to anybody using an older version. I know we don't support older version, but let's not annoy people who want to do this without a good reason
- This is quite a big refactoring and we have 40+ issues opened, we just have better things to do at the moment

(and if your company has enough $$$ to pay for Oracle, they can also contribute to an Open Source project)

Of course in the long term we will need to do this change.

**Comment by deepu105** [comment]
@develguys if you wann do the PR you are still welcome

**Comment by develguys** [comment]
Sorry for my late reply, I got some unwanted stuff.
I'm new to jhipster and yeoman. However, I think it will be more flexible if we add an option such as [--skip-check-length-of-identifier] to skip checking the length of the identifier.
I created a PR below, please see.
#7320
