### ISSUE TITLE
Tips at jhipster.github.io

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#7075]
In this folder: https://github.com/jhipster/jhipster.github.io/tree/master/tips
We can see:
```
➜ ls tips 
003_tip_add_querydsl_support.md             014_tip_using_mariadb.md
004_tip_using_ms_sql_server.md              015_tip_local_smtp_server.md
006_tips_enable_cross_origin_requests.md    016_tip_ldap_authentication.md
007_tips_enforce_https.md                   017_tip_repl_with_the_remote_shell.md
008_tips_static_swagger_docs.md             018_tip_kubernetes_and_google_cloud_sql.md
009_tips_using_bootswatch_themes.md         019_tip_infinite_scroll_with_slice.md
010_tip_configuring_html_5_mode.md          020_tip_using_docker_containers_as_localhost_on_mac_and_windows.md
011_tip_configuring_email_in_jhipster.md    021_tip_prevent_error_and_hanging_on_windows_when_using_gradle.md
012_tip_add_new_spring_social_connector.md  022_tip_registering_user_with_additional_information.md
013_tip_speed_up_generator.md
```

These files begin with number and it's not consistent with [tips.md](https://github.com/jhipster/jhipster.github.io/blob/master/pages/tips.md)

Is there a specific reason the tips begin with number ?
Can I refactor all these files to remove the number ?
Ex: `013_tip_speed_up_generator.html` -> `tip_speed_up_generator.html`

**Comment by deepu105** [comment]
I don't remember properly but I think it was used to identify the order in
which it was added. But in anycase confirm with Julien as well

**Comment by jdubois** [comment]
Yes it's know in which order they were written.
Please don't refactor the URLs as this would make 404 errors for the Google
Bot and for people who linked to them.

Le 2 févr. 2018 09:35, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

> I don't remember properly but I think it was used to identify the order in
> which it was added. But in anycase confirm with Julien as well
>

**Comment by pascalgrimaud** [comment]
ok, so let's close this
ping @agoncal as we discussed about it
