### ISSUE TITLE
Remove the module sub generator as we deprecated it long back

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7077]
@jhipster/developers is everyone ok with it? any old modules relying on it need to update in order to work with v5

**Comment by jdubois** [comment]
I didn't know it was deprecated! But I'm not doing many modules, to be honest!

**Comment by pascalgrimaud** [comment]
Ok to remove it.
We should ping all authors of module here. I can do it tomorrow.

**Comment by deepu105** [comment]
Yes Julien :) as we don't need it anymore for building modules after the
yeoman 2 migration I did long back

**Comment by deepu105** [comment]
done via https://github.com/jhipster/generator-jhipster/commit/0eb35dbfd2eb2de073775aa1b8b0d3fd3aa683b2
