### ISSUE TITLE
Use Tslib to reduce bundle size

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7084]
Typescript recommends the use of https://www.npmjs.com/package/tslib in prod to reduce bundle size. We should do it for both Angular and React

**Comment by vishal423** [comment]
@deepu105, have you started on this?

**Comment by deepu105** [comment]
@vishal423 nope would you like to do it?

**Comment by vishal423** [comment]
sure.. will raise request for angular in few minutes. For react, i am not sure what needs to be changed

**Comment by vishal423** [comment]
@deepu105 , On side note I noticed that we still use tether.js to manage popovers whereas bootstrap 4 has already migrated to popper.js and specify that as peer dependency. Also, as per tether.js github page, they recommend to use popper.js as they may not actively maintain the library. Any good reasons to not migrate?

**Comment by deepu105** [comment]
We shouldn't be using it directly as we use ng-bootstrap. let me take a look


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
I think we should just remove it.


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
done via #7135
