### ISSUE TITLE
Error during template compile *AppRoutingModule

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#7091]
##### **Overview of the issue**

running:

    ./mvnw -Pprod clean package

gives this error:

    [INFO] ERROR in src/main/webapp/app/app-routing.module.ts(5,2): Error during template compile of 'StandBystandAppRoutingModule'
    [INFO]   Function expressions are not supported in decorators in 'NgModule'
    [INFO]     'NgModule' contains the error at @angular/core/core.ts(194,31)
    [INFO]       Consider changing the function expression into an exported function.

##### **Motivation for or Use Case**

I had no problem with above command when a had 4.13.3 I did an upgrade to 4.14.0 and some other work (added a static  page). Now I have this error. I will investigate more but hope someone know the solution already.
The interesting thing is running without -Pprod (running the default profile) it does not give an error.

The error can alse be reproduced with this sub-command:

    yarn run webpack:prod

- [X]

**Comment by tibistibi** [comment]
checkout the version before the upgrade (which worked) also gives me this error:

    ERROR in src/main/webapp/app/app-routing.module.ts(10,2): Error during template compile of 'StandBystandAppRoutingModule'    
     Function expressions are not supported in decorators in 'NgModule'
      'NgModule' contains the error at @angular/core/core.ts(194,31)
        Consider changing the function expression into an exported function.

**Comment by tibistibi** [comment]
a fresh install of jhipster does not give the error

**Comment by tibistibi** [comment]
i ran `jhipster` again in a different folder with my .yo-rc.json:

    {
    "generator-jhipster": {
    "promptValues": {
      "packageName": "nl.tibi.sbys",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "standBystand",
    "packageName": "nl.tibi.sbys",
    "packageFolder": "nl/tibi/sbys",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "9e97ee7ad98095efac531b435d415970e3d2bdfb",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "nl",
      "de"
    ]
    }
    }

than i get different errors:

[INFO] [at-loader] Checking started in a separate process...
[ERROR] 
[ERROR] [at-loader] Checking finished with 84 errors
[ERROR] Hash: e9b39027373b9e3f3c38
[ERROR] Version: webpack 3.10.0
[INFO] webpack: Failed to compile.
[ERROR] Time: 54018ms
[ERROR]         Asset     Size  Chunks                    Chunk Names
[ERROR] spec/entry.ts  20.8 MB       0  [emitted]  [big]  spec/entry.ts
[ERROR]    [4] ./node_modules/@angular/core/esm5/testing.js 49.6 kB {0} [built]
[ERROR]  [297] ./node_modules/rxjs/Rx.js 9.79 kB {0} [built]
[ERROR]  [563] ./src/test/javascript/spec/entry.ts 853 bytes {0} [built]
[ERROR]  [564] ./node_modules/core-js/index.js 639 bytes {0} [built]
[ERROR]  [752] ./node_modules/zone.js/dist/zone.js 129 kB {0} [built]
[ERROR]  [753] ./node_modules/zone.js/dist/long-stack-trace-zone.js 6.16 kB {0} [built]
[ERROR]  [754] ./node_modules/zone.js/dist/async-test.js 3.23 kB {0} [built]
[ERROR]  [755] ./node_modules/zone.js/dist/fake-async-test.js 19.6 kB {0} [built]
[ERROR]  [756] ./node_modules/zone.js/dist/sync-test.js 1.41 kB {0} [built]
[ERROR]  [757] ./node_modules/zone.js/dist/proxy.js 5.6 kB {0} [built]
[ERROR]  [758] ./node_modules/zone.js/dist/jasmine-patch.js 6.5 kB {0} [built]
[ERROR]  [868] ./node_modules/rxjs/add/operator/do.js 232 bytes {0} [built]
[ERROR] [1023] ./node_modules/intl/locale-data/jsonp/en-US.js 24 kB {0} [built]
[ERROR] [1024] ./node_modules/@angular/platform-browser-dynamic/esm5/testing.js 17.9 kB {0} [built]
[ERROR] [1028] ./src/test/javascript/spec \.spec 6.77 kB {0} [built]
[ERROR]     + 1156 hidden modules
[ERROR] 
[ERROR] WARNING in ./node_modules/@angular/core/esm5/core.js
[ERROR] 6541:15-36 Critical dependency: the request of a dependency is an expression
[ERROR]  @ ./node_modules/@angular/core/esm5/core.js
[ERROR]  @ ./node_modules/@angular/platform-browser/esm5/platform-browser.js
[ERROR]  @ ./node_modules/@angular/platform-browser-dynamic/esm5/testing.js
[ERROR]  @ ./src/test/javascript/spec/entry.ts
[ERROR] 
[ERROR] WARNING in ./node_modules/@angular/core/esm5/core.js
[ERROR] 6561:15-102 Critical dependency: the request of a dependency is an expression
[ERROR]  @ ./node_modules/@angular/core/esm5/core.js
[ERROR]  @ ./node_modules/@angular/platform-browser/esm5/platform-browser.js
[ERROR]  @ ./node_modules/@angular/platform-browser-dynamic/esm5/testing.js
[ERROR]  @ ./src/test/javascript/spec/entry.ts
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/account/activate/activate.service.ts:12:9 
[ERROR]     TS2322: Type 'Observable<Object>' is not assignable to type 'Observable<any>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/account/password-reset/finish/password-reset-finish.service.ts:12:9 
[ERROR]     TS2322: Type 'Observable<Object>' is not assignable to type 'Observable<any>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/account/password-reset/init/password-reset-init.service.ts:12:9 
[ERROR]     TS2322: Type 'Observable<Object>' is not assignable to type 'Observable<any>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/account/password/password.service.ts:12:9 
[ERROR]     TS2322: Type 'Observable<Object>' is not assignable to type 'Observable<any>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/account/register/register.service.ts:12:9 
[ERROR]     TS2322: Type 'Observable<Object>' is not assignable to type 'Observable<any>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/account/sessions/sessions.service.ts:15:9 
[ERROR]     TS90010: Type 'Observable<Session[]>' is not assignable to type 'Observable<Session[]>'. Two different types with this name exist, but they are unrelated.
[ERROR]   Property 'concat' is missing in type 'Observable<Session[]>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/account/sessions/sessions.service.ts:19:9 
[ERROR]     TS2322: Type 'Observable<HttpResponse<Object>>' is not assignable to type 'Observable<HttpResponse<any>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/admin/audits/audits.service.ts:17:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<Audit[]>>' is not assignable to type 'Observable<HttpResponse<Audit[]>>'. Two different types with this name exist, but they are unrelated.
[ERROR]   Property 'concat' is missing in type 'Observable<HttpResponse<Audit[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/admin/configuration/configuration.service.ts:13:98 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Object>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/admin/configuration/configuration.service.ts:32:90 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Object>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/admin/health/health.service.ts:16:9 
[ERROR]     TS2322: Type 'Observable<Object>' is not assignable to type 'Observable<any>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/admin/logs/logs.service.ts:13:9 
[ERROR]     TS2322: Type 'Observable<HttpResponse<Object>>' is not assignable to type 'Observable<HttpResponse<any>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/admin/logs/logs.service.ts:17:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<Log[]>>' is not assignable to type 'Observable<HttpResponse<Log[]>>'. Two different types with this name exist, but they are unrelated.
[ERROR]   Property 'concat' is missing in type 'Observable<HttpResponse<Log[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/admin/metrics/metrics.service.ts:12:9 
[ERROR]     TS2322: Type 'Observable<Object>' is not assignable to type 'Observable<any>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/admin/metrics/metrics.service.ts:16:9 
[ERROR]     TS2322: Type 'Observable<Object>' is not assignable to type 'Observable<any>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/admin/user-management/user-management-detail.component.ts:23:9 
[ERROR]     TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
[ERROR]   Property '_parent' is protected but type 'Subscription' is not a class derived from 'Subscription'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts:9:14 
[ERROR]     TS2420: Class 'AuthExpiredInterceptor' incorrectly implements interface 'HttpInterceptor'.
[ERROR]   Types of property 'intercept' are incompatible.
[ERROR]     Type '(request: HttpRequest<any>, next: HttpHandler) => Observable<HttpEvent<any>>' is not assignable to type '(req: HttpRequest<any>, next: HttpHandler) => Observable<HttpEvent<any>>'.
[ERROR]       Type 'Observable<HttpEvent<any>>' is not assignable to type 'Observable<HttpEvent<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR]         Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts:17:37 
[ERROR]     TS2339: Property 'do' does not exist on type 'Observable<HttpEvent<any>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts:6:14 
[ERROR]     TS2420: Class 'ErrorHandlerInterceptor' incorrectly implements interface 'HttpInterceptor'.
[ERROR]   Types of property 'intercept' are incompatible.
[ERROR]     Type '(request: HttpRequest<any>, next: HttpHandler) => Observable<HttpEvent<any>>' is not assignable to type '(req: HttpRequest<any>, next: HttpHandler) => Observable<HttpEvent<any>>'.
[ERROR]       Type 'Observable<HttpEvent<any>>' is not assignable to type 'Observable<HttpEvent<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts:12:37 
[ERROR]     TS2339: Property 'do' does not exist on type 'Observable<HttpEvent<any>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/blocks/interceptor/notification.interceptor.ts:7:14 
[ERROR]     TS2420: Class 'NotificationInterceptor' incorrectly implements interface 'HttpInterceptor'.
[ERROR]   Types of property 'intercept' are incompatible.
[ERROR]     Type '(request: HttpRequest<any>, next: HttpHandler) => Observable<HttpEvent<any>>' is not assignable to type '(req: HttpRequest<any>, next: HttpHandler) => Observable<HttpEvent<any>>'.
[ERROR]       Type 'Observable<HttpEvent<any>>' is not assignable to type 'Observable<HttpEvent<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/blocks/interceptor/notification.interceptor.ts:17:37 
[ERROR]     TS2339: Property 'do' does not exist on type 'Observable<HttpEvent<any>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/address/address-detail.component.ts:28:9 
[ERROR]     TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/address/address.service.ts:21:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Address>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/address/address.service.ts:27:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Address>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/address/address.service.ts:32:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Address>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/address/address.service.ts:38:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Address[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/address/address.service.ts:42:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<any>>' is not assignable to type 'Observable<HttpResponse<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR]   Property 'concat' is missing in type 'Observable<HttpResponse<any>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/client/client-detail.component.ts:28:9 
[ERROR]     TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/client/client.service.ts:21:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Client>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/client/client.service.ts:27:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Client>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/client/client.service.ts:32:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Client>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/client/client.service.ts:38:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Client[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/client/client.service.ts:42:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<any>>' is not assignable to type 'Observable<HttpResponse<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/freelancer/freelancer-detail.component.ts:28:9 
[ERROR]     TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/freelancer/freelancer.service.ts:21:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Freelancer>>'.
[INFO] 07 02 2018 15:43:19.321:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/freelancer/freelancer.service.ts:27:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Freelancer>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/freelancer/freelancer.service.ts:32:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Freelancer>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/freelancer/freelancer.service.ts:38:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Freelancer[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/freelancer/freelancer.service.ts:42:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<any>>' is not assignable to type 'Observable<HttpResponse<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/language/language-detail.component.ts:28:9 
[ERROR]     TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/language/language.service.ts:21:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Language>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/language/language.service.ts:27:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Language>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/language/language.service.ts:32:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Language>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/language/language.service.ts:38:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Language[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/language/language.service.ts:42:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<any>>' is not assignable to type 'Observable<HttpResponse<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/licence/licence-detail.component.ts:28:9 
[ERROR]     TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/licence/licence.service.ts:21:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Licence>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/licence/licence.service.ts:27:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Licence>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/licence/licence.service.ts:32:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Licence>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/licence/licence.service.ts:38:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Licence[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/licence/licence.service.ts:42:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<any>>' is not assignable to type 'Observable<HttpResponse<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/position/position-detail.component.ts:28:9 
[ERROR]     TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/position/position.service.ts:21:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Position>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/position/position.service.ts:27:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Position>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/position/position.service.ts:32:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Position>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/position/position.service.ts:38:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Position[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/position/position.service.ts:42:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<any>>' is not assignable to type 'Observable<HttpResponse<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/project/project-detail.component.ts:28:9 
[ERROR]     TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/project/project.service.ts:23:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Project>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/project/project.service.ts:29:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Project>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/project/project.service.ts:34:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Project>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/project/project.service.ts:40:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Project[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/project/project.service.ts:44:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<any>>' is not assignable to type 'Observable<HttpResponse<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/skill/skill-detail.component.ts:28:9 
[ERROR]     TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/skill/skill.service.ts:21:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Skill>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/skill/skill.service.ts:27:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Skill>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/skill/skill.service.ts:32:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Skill>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/skill/skill.service.ts:38:14 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Skill[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/entities/skill/skill.service.ts:42:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<any>>' is not assignable to type 'Observable<HttpResponse<any>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/layouts/profiles/profile.service.ts:18:18 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<ProfileInfo>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/shared/auth/account.service.ts:11:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<Account>>' is not assignable to type 'Observable<HttpResponse<Account>>'. Two different types with this name exist, but they are unrelated.
[ERROR]   Property 'concat' is missing in type 'Observable<HttpResponse<Account>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/shared/auth/account.service.ts:15:9 
[ERROR]     TS2322: Type 'Observable<HttpResponse<Object>>' is not assignable to type 'Observable<HttpResponse<any>>'.
[ERROR]   Property 'concat' is missing in type 'Observable<HttpResponse<Object>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/shared/auth/auth-session.service.ts:19:9 
[ERROR]     TS2322: Type 'Observable<Object>' is not assignable to type 'Observable<any>'.
[ERROR]   Property 'concat' is missing in type 'Observable<Object>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/shared/auth/auth-session.service.ts:24:91 
[ERROR]     TS2339: Property 'map' does not exist on type 'Observable<HttpResponse<Object>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/shared/user/user.service.ts:16:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<User>>' is not assignable to type 'Observable<HttpResponse<User>>'. Two different types with this name exist, but they are unrelated.
[ERROR]   Property 'concat' is missing in type 'Observable<HttpResponse<User>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/shared/user/user.service.ts:20:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<User>>' is not assignable to type 'Observable<HttpResponse<User>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/shared/user/user.service.ts:24:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<User>>' is not assignable to type 'Observable<HttpResponse<User>>'. Two different types with this name exist, but they are unrelated.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/shared/user/user.service.ts:29:9 
[ERROR]     TS90010: Type 'Observable<HttpResponse<User[]>>' is not assignable to type 'Observable<HttpResponse<User[]>>'. Two different types with this name exist, but they are unrelated.
[ERROR]   Property 'concat' is missing in type 'Observable<HttpResponse<User[]>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/shared/user/user.service.ts:33:9 
[ERROR]     TS2322: Type 'Observable<HttpResponse<Object>>' is not assignable to type 'Observable<HttpResponse<any>>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/main/webapp/app/shared/user/user.service.ts:37:9 
[ERROR]     TS90010: Type 'Observable<string[]>' is not assignable to type 'Observable<string[]>'. Two different types with this name exist, but they are unrelated.
[ERROR]   Property 'concat' is missing in type 'Observable<string[]>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/test/javascript/spec/helpers/mock-route.service.ts:10:9 
[ERROR]     TS2322: Type 'Observable<any>' is not assignable to type 'Observable<Params>'.
[ERROR]   Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/test/javascript/spec/helpers/mock-route.service.ts:11:9 
[ERROR]     TS2322: Type 'Observable<any>' is not assignable to type 'Observable<Params>'.
[ERROR] 
[ERROR] ERROR in [at-loader] ./src/test/javascript/spec/helpers/mock-route.service.ts:12:9 
[ERROR]     TS2322: Type 'Observable<any>' is not assignable to type 'Observable<Data>'.
[ERROR]   Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
[INFO] 07 02 2018 15:43:19.324:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
[INFO] 07 02 2018 15:43:19.473:INFO [launcher]: Starting browser PhantomJS
[INFO] 07 02 2018 15:43:20.616:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket Mfj8A9339rCl7hNvAAAA with id 36863745
        PhantomJS 2.1.1 (Linux 0.0.0): Executed 22 of 124 SUCCESS (0 secs / 0.741 secs)
[INFO] .
[

**Comment by tibistibi** [comment]
i guess there are two problems. will make a new issue for the error with a new project generation

**Comment by tibistibi** [comment]
after running an upgrade via ncu -u my error changed to: 

[INFO] ERROR in src/main/webapp/app/app-routing.module.ts(11,2): Error during template compile of 'StandBystandAppRoutingModule'
[INFO]   Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
[INFO]     'NgModule' calls 'ɵmakeDecorator'.

**Comment by jdubois** [comment]
I have no idea what "ncu" does, but if you touch our configuration, then you're on your own, that's not a JHipster bug. We spend a lot of time to have everything working properly, don't believe you can upgrade everything automatically like that.

**Comment by tibistibi** [comment]
ok but how should i upgrade than?

**Comment by jdubois** [comment]
if you want to upgrade anything in `package.json`, you need to validate that it works with everything else. That can't be automated, you need to test everything.
That's what we do, and what you get for free with a JHipster stable release. If you want to do it yourself, you can of course do it, but then you're on your own and we won't be able to help. We're not the ones making all those packages that are incompatibles with each other.

**Comment by tibistibi** [comment]
i understand so i do not want to upgrade by myself i trust you guy's. but in this #7092 issue the problem was resolved by upgrading. so I guessed i could try this here as well. 

so what would should i do?

**Comment by tibistibi** [comment]
with the same yo-rc.json file I can generate with jhipster fine.
when i add the source folder into this project (removing the old one) i do not get above errors (but a test failure). this is interesting and i will look into it tomorrow.

**Comment by deepu105** [comment]
In the first place the error you see seems valid to me as you cant have
inline functions when compiling for AOT and in prod we compile with AOT.
Did you follow the instruction from the error and export your function? Do
you see this issue in a freshly generated app or is this code added by you?

Remember upgrading package is not always a solution

**Comment by tibistibi** [comment]
thanks for the help!
the thing is the same code is in a fresh install of jhipster. i did not change anything.
so the question is why do i get this error in my app and not in a fresh install.

**Comment by tibistibi** [comment]
i compared the working fresh install and my not working app (with above error) and noticed i had a `bin` and `etc` dir. i deleted them and now it is compiling without above error. 

now i'm at the next point of the not working tests ;)

**Comment by jdubois** [comment]
I'm closing this because those aren't JHipster bugs - you modified the build, so it's not a fresh install. For configuration / upgrade questions, StackOverflow is a much better place.

**Comment by deepu105** [comment]
Same comment as in the other tickets.

**Comment by tibistibi** [comment]
StackOverflow is fine but to be clear i did not modify the build and the issue is fixed after removing the `bin` and `etc` dirs.
