### ISSUE TITLE
Error message not shown with password reset

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#7098]
Because json() is replaced with error the error message is not shown any more in the password rest page.
I have a fix and will add a pull request

**Comment by jdubois** [comment]
Thanks! We have some weird errors here! And please have a look at the Karma tests, they probably check this and are broken too.

**Comment by tibistibi** [comment]
yes added that as well. test are not working i see, but i have this working localy

**Comment by tibistibi** [comment]
#7099

**Comment by tibistibi** [comment]
this issue is equal to: #7085
