### ISSUE TITLE
Build jhipster using travis-ci.org

### ISSUE THREAD

**Issue by jmirc** [jhipster/generator-jhipster#71]

**Comment by KoljaTM** [comment]
fwiw, I had the same problem as reported in the StackOverflow article and fixed it by changing

    @Inject
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        auth
            .userDetailsService(userDetailsService)
                .passwordEncoder(passwordEncoder());
    }

to

    @Override
    public void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth
            .userDetailsService(userDetailsService)
                .passwordEncoder(passwordEncoder());
    }

I don't really know what exactly that is changing, or why it was necessary for Ci build (Teamcity) but not for local build.

**Comment by jlfuentes** [comment]
The fix proposed KoljaTM works fine, here the explanation:

http://stackoverflow.com/questions/26348877/can-not-apply-daoauthenticationconfigurer-to-already-built-object

Thx!
