### ISSUE TITLE
Create destroy generators that reverses the effect of creator generators

### ISSUE THREAD

**Issue by mkhanal** [jhipster/generator-jhipster#710]
eg of creator generator

```
yo jhipster:entity <entity-name>
```

eg of destroy generator

```
yo jhipster:destroy <entity-name>
```

same goes for other generators as well (service, and anything to come up)

this feature is inspired by **rails** destroy method that reverses the effect of generate.
The syntax may vary to fit requirements, like instead of a common destroy method,
it could be implemented as 

```
yo jhipster:destroyEntity <entity-name>
yo jhipster:destroyService <service-name>
```

**Comment by cm325** [comment]
I think having the destroy generator would indeed be useful, but as you pointed out, it's useful mainly for people who weren't careful in the beginning with git. If git is truly the way to do this, then perhaps what's needed are some helpful reminders that it's worth committing a couple of times early on. I just started using jhipster, and assumed (as other people are, by all the posts on this topic), that if you're using a tool that generates changes, it would also be able to remove them as well. If I was instructed to commit after initial generation, and after each entity was added, I'd be in a much better situation now-

**Comment by jdubois** [comment]
It's implied that use a version control system. At the moment, the only sub-generator that requires Git is the "upgrade" sub-generator, as we need to control the version control system to do the upgrades.
For all other generators, I didn't want to force people to use a specific version control system: you are free to use whatever you want, even if most people are using Git in the end.

And you are correct, we should add more "best practices" like this one in the documentation.

**Comment by gmarziou** [comment]
Just a comment about db migrations, the way  `rails destroy model` works is just by deleting the files created by  `rails generate model` which includes the db migration file, so people often forget to rollback this migration while it exists prior to running destroy.

JHipster has to support several migration tools, this makes it even more difficult to support this.

What if we took the db migrations out of the picture? Let's destroy code only and don't mess with user's data. After all, the code is expected to be version controlled while the database might not be especially in dev.

**Comment by gmarziou** [comment]
Pedantic and useless remark: the comparison with `rails destroy model` is wrong, we should compare with `rails destroy scaffold` ;)

**Comment by cbornet** [comment]
Agreed.
IMO, DB migrations in prod should not be fully automated and cannot be safely generated. Imagine you change a table name or column. So the best way for me is to make a liquibase:diff on a DB that has the same schema as the prod, then edit the diff manually to make the changes liquibase couldn't detect by itself. Often you also have to add manually some custom operations such as transfering existing data from a table to a new one. Then add the diff to master.xml.
