### ISSUE TITLE
Enable fullTemplateTypeCheck for angular compiler

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#7103]
##### **Overview of the issue**

Found while working on #7093.

I added  `"fullTemplateTypeCheck": true` to `angularCompilerOptions` in `tsconfig-aot.json` and it raised few errors on jhipster-sample-app that should be fixed:

~~~
yarn run ngc
$ ngc -p tsconfig-aot.json
src\main\webapp\app\admin\audits\audits.component.html(11,93): : Expected 0 arguments, but got 1.
src\main\webapp\app\admin\audits\audits.component.html(16,93): : Expected 0 arguments, but got 1.
src\main\webapp\app\admin\health\health-modal.component.html(21,25): : Expected 2 arguments, but got 1.
src\main\webapp\app\admin\metrics\metrics.component.html(165,17): : Expected 2 arguments, but got 1.
src\main\webapp\app\admin\metrics\metrics.component.html(200,17): : Expected 2 arguments, but got 1.
src\main\webapp\app\admin\metrics\metrics-modal.component.html(25,22): : Expected 2 arguments, but got 1.
src\main\webapp\app\admin\metrics\metrics-modal.component.html(15,22): : Expected 2 arguments, but got 1.
src\main\webapp\app\entities\operation\operation-detail.component.html(22,80): : Property 'name' does not exist on type 'BaseEntity'.
~~~

##### **Motivation for or Use Case**

Template compilation detects real errors and should be enabled.

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes, in fact I thought we already had this, it's one of the big selling point of Angular to me! And Intellij/VSCode/tslint/prettier don't see any of those issues...

**Comment by gmarziou** [comment]
I need help.

One error comes from the entity angular models using `BaseEntity` type for relationships, I remember @deepu105 explaining the reason for `BaseEntity`, was it about cyclic dependencies?

Template below binds to `name` property of `operation.bankAccount` but type checking fails because `operation.bankAccount` is of type `BaseEntity`.

~~~html
<a [routerLink]="['/bank-account', operation.bankAccount?.id]">{{operation.bankAccount?.name}}</a>
~~~

~~~ts
export class Operation implements BaseEntity {
    constructor(
        public id?: number,
        public date?: any,
        public description?: string,
        public amount?: number,
        public bankAccount?: BaseEntity,
        public labels?: BaseEntity[],
    ) {
    }
}
~~~

**Comment by deepu105** [comment]
@gmarziou baseEntity is removed in my PR for folder structure improvement so this issue should resolve when its merged. Ill try to merge it today

**Comment by jdubois** [comment]
Awesome! @Deepu105 don't forget to delete the BaseEntity in the cleanup.js I think it's still there after an upgrade

**Comment by deepu105** [comment]
oh ya
