### ISSUE TITLE
V5 documentation updates

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7117]
For v5 we need to update the below documentation compulsory before release.

- [x] Removal of AngularJS to blueprint
- [x] React support
- [x] Blueprint support
- [x] Spring boot 2 updates
- [ ] Angular folder structure updates
- [x] JDL app generation syntax
- [x] Removal of module sub gen
- [ ] Prettier support
- [ ] Oidc updates
- [ ] Add an option [--skip-check-length-of-identifier] to skip check of the length of identifier when generating entity 
- [x] Update how to use Gatling
- [x] How to use Memcached
- [x] Embedded elasticsearch is not available starting from v5 hence better to mention the alternative available ways.

We could also use this ticket to draft the changelogs. Wdyt @jdubois 
@jhipster/developers plz include if I have missed anything

**Comment by gmarziou** [comment]
Can we create a v5 branch on https://github.com/jhipster/jhipster.github.io?

**Comment by jdubois** [comment]
Yes, there's a lot to do here!

**Comment by jdubois** [comment]
I forgot about this one -- this is mostly done, I'm going to tick most boxes, and then we should probably close it

**Comment by pascalgrimaud** [comment]
I'm adding Gatling to the list: https://www.jhipster.tech/running-tests/

**Comment by pmverma** [comment]
Embedded elasticsearch is not available starting from v5 hence better to mention the alternative available ways.

**Comment by jdubois** [comment]
Not sure if everything is done, but v5 is out for some time and the current documentation is good enough for me, let's close this
