### ISSUE TITLE
testRegisterAdminIsIgnored registeres a User instead of an Admin

### ISSUE THREAD

**Issue by phischde** [jhipster/generator-jhipster#7119]
The **AccountResource** generator also generates the test `AccountResourceIntTest.testRegisterAdminIsIgnored()`. 

From the test method name I understand that this test ensures no one can gain admin access by submitting Authorities. The **ROLE_USER** is explicitly set in the `UserService` and is not taken from the `ManagedUserVM`.

However, the test in `AccountResourceIntTest` submits a **ROLE_USER** as an authority which is ignored but later set by the `UserService` explicitly and tests for **ROLE_USER**

I would expect this test to submit the Authority **ROLE_ADMIN** in Line 644 and check in Line 655 that the user did not gain admin access. 

Line in question: 
https://github.com/jhipster/generator-jhipster/blob/313b09f230b8ac240541a4d484996c6c5edfbb3b/generators/server/templates/src/test/java/package/web/rest/_AccountResourceIntTest.java#L644

**Comment by deepu105** [comment]
Could you do a PR to fix it plz


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
You are right - I'm just in this code, let me do the correction, thanks @phischde !
