### ISSUE TITLE
Issue loading static assets when the application is deployed on a path which has a folder with space in it

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7123]
In our JHipster app, today we encountered an error when testing in a particular Jenkins CI, that the front end was not being loaded. On further investigation, I found that its coz of the `resolvePathPrefix` method in our `WebConfigurer.java` file. For now I did the below fix, is there a better fix or is the below fine if so I'll update the same here as well

Here is my diff of the fix 
```
     private String resolvePathPrefix() {
-        String fullExecutablePath = this.getClass().getResource("").getPath();
+        String fullExecutablePath;
+        try {
+            fullExecutablePath = decode(this.getClass().getResource("").getPath(), "UTF-8");
+        } catch (UnsupportedEncodingException e) {
+            /* try without decoding if this ever happens */
+            fullExecutablePath = this.getClass().getResource("").getPath();
+        }
         String rootPath = Paths.get(".").toUri().normalize().getPath();
         String extractedPath = fullExecutablePath.replace(rootPath, "");
         int extractionEndIndex = extractedPath.indexOf("build/");
         if (extractionEndIndex <= 0) {
             return "";
         }
         return extractedPath.substring(0, extractionEndIndex);
     }
```

This can be reproduced by following steps.

1. Create a folder with space in its name, for example `mkdir "test folder"`
2. create another folder inside the above
3. generate an app using all the default options
4. start the app by running `./mvnw` or `./gradlew`
5. try to access the app

Below is my config, I have react but the same is applicable for angular as well

##### **JHipster Version(s)**

latest/master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "jhipsterVersion": "4.10.2",
    "baseName": "myapp",
    "packageName": "com.xebialabs.myapp",
    "packageFolder": "com/xebialabs/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "useSass": true,
    "clientPackageManager": "yarn",
    "clientFramework": "react",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "nl"
    ]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

doesnt matter

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.14.3

node: v8.9.4

npm: 5.3.0

bower: 1.8.0

gulp:
[21:03:02] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.05.0-ce, build 89658be

docker-compose version 1.17.1, build 6d101fb

**Comment by jdubois** [comment]
Weird, is that on Windows?
On my Mac, I often have fun putting emojis in my folder name (yeah, that's just to have fun...) and it works - so I'm surprised a space causes an issue.
Otherwise we should merge this, this can only make things better.

**Comment by deepu105** [comment]
Nope on linux

**Comment by deepu105** [comment]
@jdubois if you think my fix is good, I will update it with a PR

**Comment by jdubois** [comment]
Using UTF-8 to decode can only be good - and that's fixing your bug. So yes let's do this.
