### ISSUE TITLE
Fix issues with i18n for microservices

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7124]
The new folder structure updates introduced in https://github.com/jhipster/generator-jhipster/pull/7079 cause a bug in i18n, when doing microservices, as per https://github.com/jhipster/generator-jhipster/pull/7079#issuecomment-365350893

This issue is so that I dont forget to fix it and any related issues

**Comment by mraible** [comment]
I can confirm that i18n success messages don't work when using microservices.

**Comment by mraible** [comment]
FWIW, I still see issues with i18n and microservices. Mostly with success messages.
<img width="1372" alt="screen shot 2018-04-15 at 10 17 11 am" src="https://user-images.githubusercontent.com/17892/38780578-2ff0330a-4096-11e8-8e67-af8703eaff63.png">

**Comment by FireWolf2007** [comment]
Translation problem on internal error

![2018-05-03 15-14-01](https://user-images.githubusercontent.com/1145904/39575878-c9985db4-4ee4-11e8-8318-4416376f31d0.png)

**Comment by FireWolf2007** [comment]
error.Min/error.Max on inputs with nulls allowed.
JH 5.0.0.beta1

Example https://github.com/FireWolf2007/hockey-match
Reproduce: Create team1, team2, tournament1.
On creating game with "Goals Team 1" == -1 we have "translation-not-found[error.Min]"

**Comment by deepu105** [comment]
I'll try to spend some time on this ticket this week

**Comment by octgsoftware** [comment]
I am running into this with JHipster v5.1.0 with and without translation.

**Comment by octgsoftware** [comment]
I was able to get the translations working with the following:

jhipster import-jdl test.jdl --force --skip-ui-grouping --client-root-folder ""

**Comment by lazzrov** [comment]
I also have translation issues, but for a monolith. I add new words with translations but they are not found when I use jhiTranslate (not even an error is reported)

**Comment by PierreBesson** [comment]
I suggest that we bump this bounty to 200$ as the issue as been opened for 6 months.

**Comment by jdubois** [comment]
I also tested today and this is indeed broken, and I find this is major as you have the error on all i18n microservices!
@PierreBesson unfortunately we just have a $100 tag, and even if that's a major issue, I'm not sure it's that complex to do, so that should be enough.

**Comment by pascalgrimaud** [comment]
@ruddell did a fix, which was reverted. There are something to do with the clientRootFolder

**Comment by deepu105** [comment]
This is a tricky one. If I find some time I'll try to fix. I fixed some
issues earlier but this seem to have missed
