### ISSUE TITLE
Problem with the project generated by Jhipster ?

### ISSUE THREAD

**Issue by MouliChandu171** [jhipster/generator-jhipster#7125]
The project works fine when i am running everything through command line. but when i import the maven project into eclipse all the angular 5 code goes with errors. There is no problem with the spring boot code. I am working on ubuntu 17.04 version and i am using eclipse oxygen.

Here is the command run for jhipster-info

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
fhx-example@0.0.0 /home/chandra/ExampleApp-2
`-- generator-jhipster@4.14.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.intellect.fhx"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "FHXExample",
    "packageName": "com.intellect.fhx",
    "packageFolder": "com/intellect/fhx",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Pacs (pacs) {
  name String,
  noOfCounters Integer,
  dateOfUpgrade ZonedDateTime
}
entity DCCBBranch (dccb_branch) {
  name String,
  comment String
}

relationship OneToMany {
  DCCBBranch{pacs} to Pacs{dccbbranch(name) required}
}

dto Pacs, DCCBBranch with mapstruct
paginate Pacs, DCCBBranch with pagination
service Pacs, DCCBBranch with serviceImpl

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.14.1

node: v6.11.4

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.3.2

Congratulations, JHipster execution is complete!

**Comment by jdubois** [comment]
It's a problem with your IDE configuration, please use Stackoverflow for this
