### ISSUE TITLE
Gateway generated with service discovery server option 'Consul' , shows "translation-not-found[health.indicator.consul]" instead of "Consul" in the health checks view.

### ISSUE THREAD

**Issue by anandsudhir** [jhipster/generator-jhipster#7150]
##### **Overview of the issue**

Gateway generated with service discovery server option 'Consul' , shows "translation-not-found[health.indicator.consul]" instead of "Consul" in the health checks view.

![image](https://user-images.githubusercontent.com/3252403/36428112-549b9fda-164f-11e8-9660-91729ec80eca.png)

##### **Motivation for or Use Case**

Clearly a minor oversight

##### **Reproduce the error**

Generate a `gateway`, start the application and navigate to 'Administration' -> 'Health' 
(http://localhost:8080/#/jhi-health)

##### **Related issues**

Can't find any currently open

##### **Suggest a Fix**

Add the missing entry to health.json for all languages. I can try to patch this and submit a PR later today.

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/vagrant/Desktop/myrepo/gateway
└── generator-jhipster@4.14.0 

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "1234",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.11.0

node: v8.9.4

npm: 5.6.0

bower: 1.8.2

gulp:
[13:39:58] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.12.0-ce, build c97c6d6

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not related to entities

##### **Browsers and Operating System**

Not specific to browsers or OS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes it just wasn't translated - if you can submit a PR it's most welcome!
