### ISSUE TITLE
No access to webserver after enabling SSL

### ISSUE THREAD

**Issue by kgruhler** [jhipster/generator-jhipster#7154]
##### **Overview of the issue**

I enabled SSL like described in application-prod.yml / application-dev.yml:
```
# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias tars -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: mypass
#        key-store-type: PKCS12
#        key-alias: tars
# ===================================================================
```
I generated a keystore file with keytool for local development and set the server properties in yml file.
Everything works fine during startup, but if I want to connect to 'https://localhost:8443/' the connection is refused with no errors. Neither in the console nor in the browser window or the browser developer console. 

Chrome just says: ERR_CONNECTION_CLOSED. 

What I tried: 
- Different ports
- Different Keystores
- Different Certificate (and self signed cert for localhost)  
- Added Certificate to Java keystore file 'cacerts'

**I have two other applications with an older Version of Jhipster (v3.8.0) with enabled SSL and everything works fine, but not with this new app.** 

What can I do now to solve my issue?
It would be a charm to have logs for this...

##### **JHipster Version(s)**
v4.14

##### **JHipster configuration**

yo-rc.json
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "package.name.testapp"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "testapp",
    "packageName": "package.name.testapp",
    "packageFolder": "package/name/testapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "72654654654d4db5bc05f3e06c87a354c65f",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}
```
##### **Browsers and Operating System**

OS: Windows 7 x64 on 
Browsers: Chrome (Version 64.0.3282.167) , Firefox (52.6.0 (32-bit)) and IE

**Comment by ruddell** [comment]
I can't reproduce and I have another app running in prod with these settings.  Are you sure you modified the correct YML config file for the profile you are running?

What I did to test:
 - Generated the keystore.p12 with the `keytool` command
 - Updated the `server` section of application-dev.yml with the provided config
 - The project starts and is accessible on port 8443 - after accepting the self-signed certificate

**Comment by kgruhler** [comment]
I'm 100% sure having the correct YML config. I testet it by changing the keystore password and I immediately got an error.  
Is there any way to log the ssl handshake or set the log level higher as debug?

I'm going to try it out with a complete new project now. Let's see.

**Comment by kgruhler** [comment]
It was my fault. I didn't create an alias for the server cert. There was only a '1' as alias and therefore the cert couldn't be loaded. But I'm wondering why there wasn't a single error.

Thanks and enjoy your day!
