### ISSUE TITLE
Add CI/CD with ECS deploy for enterprise use

### ISSUE THREAD

**Issue by ssavageVT** [jhipster/generator-jhipster#7159]
##### **Overview of the issue**

Hello from Ippon USA!  We have a use case for which we would like to generate a Jenkins pipeline for deploying a JHipster application in a corporate environment.  We need to provide a configurable pipeline script that runs from Jenkins in a Docker container on a remote RHEL server.

##### **Motivation for or Use Case**

JHipster is awesome on our local machines, but in an established enterprise we are unable to deploy directly.  We had a situation where we needed a pipeline that could deploy from a Jenkins instance running in a container that needed to share resources with a RHEL host.  So we spun up a centOS image, installed Docker, and then configured a Jenkins instance to run our build and deployment.  This requires significant modification to the Jenkinsfile generated by the ci-cd subgen.

We have added an additional subgen folder which was based on ci-cd.  We would like to propose using this a BETA enhancement to JHipster and to get feedback from the dev team.  Our changes have been tested and deployed to AWS, and we our finalizing documentation and ready to submit a PR.

Please let us know how to proceed - we don't want to add additional overhead, and if this could be done better, please let us know
<img width="626" alt="screen shot 2018-02-22 at 11 25 12 pm" src="https://user-images.githubusercontent.com/20446573/36577825-b5a06390-1827-11e8-8976-5eff9679e206.png">
<img width="1126" alt="screen shot 2018-02-22 at 11 03 50 pm" src="https://user-images.githubusercontent.com/20446573/36577829-bad95b00-1827-11e8-9b54-02238abf139f.png">

.

Thanks!  

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I'm ok to have this in the main generator if it is done as an option in the existing ci-cd sub gen. Adding another sub gene for this is an overkill IMO if it cant be incorporated into existing ci-cd subgen, then its more suitable to be a module.

**Comment by cbornet** [comment]
AWS ECS deployment is another subgen. IMO the AWS config shouldn’t be in the ci-cd subgen. Here it should only be a simple command to deploy (like what is done for Heroku)

**Comment by deepu105** [comment]
We already have 2 AWS sub gen, we cant have everything. Either this should
be a module or need to find a way to add it to an existing subgen


Thanks & Regards,
Deepu

**Comment by ssavageVT** [comment]
Thanks.  We will re-evaluate and check on the module approach.  I also agree that it is a lot of configuration that could be done elsewhere and might not be ideal to have here.  Thanks for the feedback!
