### ISSUE TITLE
Refactoring src/test/javascript to src/test/typescript

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7161]
As @deepu105 just finished #7147 and as we can break some stuff for JHipster 5, isn't it time for us to refactor `src/test/javascript` to `src/test/typescript` ?
As we only have Typescript files in that directory now.

**Comment by deepu105** [comment]
Technically its transpiled to JS, so I don't have a preference here. If you prefer it that way it's fine. Btw tje protractor and karma config files are in js

**Comment by jdubois** [comment]
Ok let's keep it that way
