### ISSUE TITLE
Remove the Gatling Maven/Gradle plugin

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7164]
This is already done in the master branch for Maven.

Using the Gatling Maven plugin causes many issues, as it requires to have Gatling in the classpath, and it is not compatible with several other technologies we use. There is an issue with Kafka (as both use different versions of Scala), and also with Spring Boot 2 (which is a blocker issue, of course).

Anyway, Gatling can perfectly be used as a separate application, which is what I currently do, so there's no need to add this plugin and maintain its version.

Here's my plan:

- [x] Remove the Gatling plugin in Maven
- [x] Add the possibility to use Gatling and Kafka together in the generator
- [x] Add the possibility to use Gatling and Kafka together in https://start.jhipster.tech/
- [x] Remove the Gatling plugin in Gradle (ping @atomfrede - I don't think there is any problem here, but this is to be consistent)
- [x] Document the use of Gatling (I don't think it's even documented today, so that should have been done anyway)

**Comment by atomfrede** [comment]
Yes we can remove the gradle plugin too. I also find it much easier to have a seperate load testing module (which can use the plugin if desired).
