### ISSUE TITLE
Prettier runs too late and causes conflicts during re-generation

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#7172]
Currently, prettier runs after code generation.

Due to this, when re-generating an entity or an app, yeoman shows many conflicts (~25% of generated files) only due to reformatting that runs later.

I don't know enough yeoman to say whether it is easy to run prettier after template rendering and before yeoman compares file contents.

**Comment by deepu105** [comment]
I was also thinking about doing that and I guess it should be possible using the yeoman pipe feature. I'll look into this later

**Comment by gmarziou** [comment]
I have something starting to work by using yeoman registerTranformStream(), for now it only uses default settings, I must pass it our configuration

https://github.com/gmarziou/generator-jhipster/commit/b88051b3bf2006d4d9a9f5163bbf2bdf065c4319

**Comment by deepu105** [comment]
Nice work. I assume it would be easy to pass our settings. I didn't look at
the code yet, but assume you will be using gulp filters

**Comment by gmarziou** [comment]
Yes I used gup-filter, I also used gulp-prettier but I had to modify its code a little so finally I rewrote it as a short inner function

**Comment by gmarziou** [comment]
@deepu105 there's a bootstrap issue here: `.prettierrc` is generated from an EJS template, so on first generation it does not exist and on next generations it exists and could have been customized by user. 

I don't know what I could do with yeoman's in-memory filesystem.

A simple approach could be to define our `.prettierrc` file as a plain file not a template and that user's configuration file is ignored during generation.

**Comment by gmarziou** [comment]
I could not find a way to specify a configuration file path through API so I may do the reverse: define options in a variable and generate the `.prettierrc` file from it.

**Comment by deepu105** [comment]
Can you create a PR with what you hv so far, ill work on it tomorrow. I'll
find a way

**Comment by gmarziou** [comment]
Here it is, I added it only to app generator.
