### ISSUE TITLE
[CI] Upgrade CircleCI 1.0 to 2.0 syntax

### ISSUE THREAD

**Issue by Akuka** [jhipster/generator-jhipster#7192]
CircleCI: "Action Required: We are sunsetting CircleCI 1.0 on August 31, 2018"
You’ll need to update all of your config files to the CircleCI 2.0 syntax in order to migrate your projects to CircleCI 2.0 over the next 6 months.

Original post:
https://circleci.com/blog/sunsetting-1-0

**Comment by cbornet** [comment]
@Akuka would you do a PR for this ?

**Comment by pascalgrimaud** [comment]
There is already a module for that https://github.com/jeantsai/generator-jhipster-circleci-2 made by @jeantsai
It would be cool to upgrade to CircleCI 2.0 in the main generator but we have other priorities for now.

I'm closing this as it seems no one is motivated for PR and it can be done later.
