### ISSUE TITLE
CORS Filter Not Working

### ISSUE THREAD

**Issue by jigarpt** [jhipster/generator-jhipster#7197]
##### **Overview of the issue**

With "dev" profile following use case is not working.

User is not authenticated with below error:

> {
>   "type" : "jm-services/problem-with-message",
>   "title" : "Forbidden",
>   "status" : 403,
>   "detail" : "Could not verify the provided CSRF token because your session was not found.",
>   "path" : "/api/authentication",
>   "message" : "error.http.403"
> }

Project Structure: API and UI are generated separately.
Steps to reproduce:
1. On server side for "dev" profile CORS is enabled by default. (Server URL: http://localhost:8080)
2. On UI - In webpack.common.js -> pass SERVER_API_URL.  (UI URL: http://localhost:9000, SERVER_API_URL: http://localhost:8080)
3. Just to make sure UI is not utilizing proxy, proxy part is commented in webpack.dev.js. 

Here, I am expecting that since CORS is enabled on API side; UI should be working fine. Instead, I am getting following error.

(With PROXY enabled on UI side, everything works fine. Looks like I am missing something obvious)

OPTION REQUEST
![image](https://user-images.githubusercontent.com/28896871/36789180-9b44f982-1cb6-11e8-9542-5252eedda16a.png)

Here in OPTION request, how Access-Control-Allow-Origin: **http://localhost:9000** is set to UI URL, it should be *. 

POST REQUEST
![image](https://user-images.githubusercontent.com/28896871/36789234-ca6c5188-1cb6-11e8-8eaf-24900762aeb1.png)

Now, it obvious that server is going to reject the request because request is originated with 8080 port where as allowed origin is with 9000 port. 

##### **Related issues**
#3233 #3237

##### **JHipster Version(s)**
4.13.3

##### **JHipster configuration**

~~~json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.java.soa",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "SOA",
    "packageName": "com.java.soa",
    "packageFolder": "com/java/soa",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,    
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ],
    "rememberMeKey": ""
  }
}
~~~

##### **Browsers and Operating System**

Windows 10, Chrome, Firefox

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
The error message you give is about the CSRF token, are you sure you have a CORS issue? I'm pretty sure this part works

**Comment by jigarpt** [comment]
Hi Julien, 

Thanks a lot for your reply. 

Yes indeed, error is about "CSRF token", however I still believe that this issue is about CORS because when I enable gulp proxy on client side, everything works as expected.  Another reason to believe this is a CORS issue is "response" header - it shows that allowed source is Access-Control-Allow-Origin is "http://localhost:9000" - I am expecting it to be "*" or "http://localhost:8080".

Please let me know if any additional information required to trace this issue. 

Best regards

**Comment by jdubois** [comment]
It's not Gulp anymore, it's Webpack dev server + BrowserSync with Angular -> your `.yo-rc.json` is strange as it doesn't say if you use AngularJS or Angular, does it come from an old application that you upgraded?

**Comment by jigarpt** [comment]
Hi Julien, 

That's right, it's Webpack + BrowserSync and I was referring to dev server proxy defined in webpack.dev.js. 

I am using Angular. And this Angular application is generated separately. 

Best regards,

**Comment by ruddell** [comment]
There's no CORS issue here.  When CORS is used to make a request from another origin, that domain will populate the response header `Access-Control-Allow-Origin`, it does not display `*` or any other domains configured.  That's why you see localhost:9000 when you make a request from localhost:9000.

**Comment by jdubois** [comment]
I'm following @ruddell here -> for me you have a CSRF issue, as that's what the error message says, and if you have separated your front-end from your back-end, who knows what can be wrong here.... that's impossible to reproduce on our side

**Comment by jigarpt** [comment]
Hi @jdubois , @ruddell  I understand your reasoning. Thanks for your response. 

@ruddell  - When I enable proxy on UI side everything works fine. No CSRF token issue at all. 
@jdubois - For reproducing this issue 

1. Simply generate server side application (session based authentication) and then generate client side application separately.
2. Run both of them - by default everything will work fine as expected.
3. On client side in webpack.common.js - give server (API) url for SERVER_API_URL. (line: 50). I gave it like this: SERVER_API_URL: `'${options.url}'` - option.url is "http://localhost:8080" (defined in webpack.dev.js). 

Now you will start seeing CSRF error. 

Based on this discussion I understand there are 2 possible issues here:
1. CSRF - CSRF tokens are not generated and send correctly for respective request URLs. May be when requests are going to APIs using 9000 port CSRF works fine; but when it goes with 8080 port CSRF breaks.
2. CORS (because now API requests are going like "http://localhost:8080/api/authenticate" instead of "http://localhost:9000/api/authenticate". 

Even lets say it's CSRF issue, I don't understand why and how to correct it?

Once again thanks for your inputs; I am still trying to understand the root cause for this scenario. 

Best regards.

**Comment by jdubois** [comment]
Can you give your `.yo-rc.json` for both applications?

**Comment by jigarpt** [comment]
Hi @jdubois 

For UI:
```
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "UI",
    "clientFramework": "angularX",
    "useSass": true,
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ],
    "clientPackageManager": "yarn",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql"
  }
}
```

Server API:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.java.soa",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "JavaSOA",
    "packageName": "com.java.soa",
    "packageFolder": "com/java/soa",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ],
    "rememberMeKey": ""
  }
}
```

**Comment by gmarziou** [comment]
There's no "authenticationType" in .yo-rc.json of the UI, how would the client code for handling authentication could be generated?

**Comment by jdubois** [comment]
Indeed you have no security, this doesn't make any sense... For CSRF you need session-based security, on both sides. This is probably your issue.

**Comment by jigarpt** [comment]
Oh.. let me try to put authenticationType in .yo-rc.json of the UI. I will regenerate the app and get back to you. 

Thanks a lot. @jdubois @gmarziou @ruddell
