### ISSUE TITLE
Performance issues and Cascade failure with Gateway

### ISSUE THREAD

**Issue by abshkd** [jhipster/generator-jhipster#7198]
##### **Overview of the issue**

On AWS I have used boxfuse to deploy the gateway with the health checks etc preconfigured. With a t2.large in autoscale we find that at a very specific concurrency we get a cascade failure such that there are no instances available and the service is essentially down.

This happens when requests are proxied or forwarded to microservices that are slow to respond. The requests builds up to about few 100 concurrent users and fewer than 30 requests per seconds per instance. At which point the failures starts.

### What I've tried

- Default timeouts for Zuul, Ribbon and Hystrix are high like 10 seconds. There were reduced to about 1-2 seconds. This only delays the problem
- Undertow is being used by JHipster and it defaults to 32 Threads. Which shows in the Gateway metrics as "Active requests" when fully used. Changing the instances for CPU core count does not seem to change that value. 
 - If I set the `server.undertow.thread-count=512` more requests can be handled but the failure still occurs eventually.
- changed ribbon client to `okhttp3`
- updated Spring Cloud to Edgware.SR2

### how can you recreate. 
 - Take a default gateway generated
 - add a static route to a slow service or just to non existing url like this 
```
zuul.routes.slowapi: http://doesnotexist.local
```
 - use apache bench or any load test utility to start over 32 concurrent requests. while the requests are running continue to check the `/management/health` endpoint. It will become inaccessible after a short while. There is no lack of resources on the physical system.

It may be easier to reproduce on AWS. The failure is almost guaranteed. The weirdest part is that AWS will not Autoscale here as CPU is barely used, it will simply remove the instance as `OutOfService` I havent figured out why it does that but I suppose not being able to reach `healthcheck` may have something to do with it.

**Comment by pascalgrimaud** [comment]
It's an interesting subject, but I don't see where there is a bug in JHipster ?

From what I can read, your slow microservice wouldn't pass the gatling tests, so maybe the problem is here and not in JHipster generated code?

**Comment by gmarziou** [comment]
Have you asked undertow and spring-cloud-netflix projects?
How much slow are your microservices?

**Comment by jdubois** [comment]
I've never experienced this, and for me Zuul does a great job here, but I can understand that as Zuul is a Servlet filter, having slow microservices can indeed eat your whole Undertow threadpool.
(again, this is something I find "logical", but I haven't experienced this, even with very high load).
If that is indeed the case, I don't know what we can do - the only answer would be to add more gateways, so basically you have more threads available. But in the end if you have lots of users waiting everywhere for a slow microservice, that's not going to be good.
For me this is a question for StackOverflow, we can't do much here, as we basically rely on Zuul. And I'm not sure there could be another approach, as this is also protecting your microservice: if it's already very slow, allowing thousands of requests to it will not end up well.

**Comment by gmarziou** [comment]
Maybe using Traefik with the registry could help?

**Comment by abshkd** [comment]
@jdubois I dont disagree that this can happen and there is a clear explanation of slow connections tying up the gateway. However, the concern is why does the gateway explode and disappear completely and so quickly. Shouldn't there be some way to protect the gateway from slow microservices.

If one microservice is slow then gateway is not protecting but breaking all microservices by dying.
How do we add instances dynamically when resources are not used. Is there a way to make healthcheck do a busy signal earlier based on active thread pool count, will that work?

@gmarziou Thanks. I was going to look for something along those lines. I will check out Traefik.

I have asked in spring-cloud. I will post this in StackOverflow.

**Comment by jdubois** [comment]
Oh yes but for those you have the specific Zuul configuration like `zuul.host.max-total-connections` - it's pre-configured in your `application.yml` but should be tuned depending on your needs
