### ISSUE TITLE
Feature request - custom Angular front end location

### ISSUE THREAD

**Issue by slavP** [jhipster/generator-jhipster#7204]
Currently jhipster project generation places Angular front end on the root of the project.
I think it would be great to allow users to select desired location.

**Comment by jdubois** [comment]
Yes but that would be a huge, huge work. We can't do this at the moment, we have 40+ opened tickets, that's just impossible.

**Comment by gmarziou** [comment]
Maybe I misunderstood but I think @deepu105 did something about it in #7079 with `client-root-folder` flag.

**Comment by deepu105** [comment]
@gmarziou it only adds a folder for entities within the webapp folder. I think what @slavP wants is to have a different folder than webapp altogether. @slavP I would suggest you to use the skip-client and skip-server flags to generate the structure you like and then use CORS to get what you want as per http://www.jhipster.tech/separating-front-end-and-api/

**Comment by gmarziou** [comment]
OK, thanks.
