### ISSUE TITLE
entity enum type validation is permissive (class name and members name)

### ISSUE THREAD

**Issue by AdrienHorgnies** [jhipster/generator-jhipster#7205]
##### **Overview of the issue**

entity generator (or import-jdl generator) will accept java reserved keywords such as `true` and `false` with the fields of java enum type. Furthermore, the class name accepts values containing invalid characters such as the comma `,`.

##### **Motivation for or Use Case**

The application will fail to start, it's tedious to recover if you didn't commit right before doing it and if you're using the entity generator, you must restart its creation.

##### **Reproduce the error**

Create an entity with reserved keyword such as `true` (through entity generator or JDL).

##### **Related issues**

Searched with the keywords `enum` and `validation` and didn't find any pertinent ones.

###### Entity generator :
1. Reference an existing method that validates java class names from the inquirer prompt that ask the enum name.
2. Implement a method that split around the character comma `,` and send resulting `String`s through an existing validation method that forbids java reserved keywords
3. Reference this new method from the `validate` field of the inquirer prompt that ask the question about the values of the enumeration.

###### JDL :
I don't know the JDL code as much as the entity generator but something similar could be done I guess. 
I know there is already something in place but if it can help, I implemented [something for a JHipster module](https://github.com/bastienmichaux/db-importer/blob/dev/lib/validation.js) that use a **single implementation** to validation inquirer prompts and a configuration file (could be the JDL if adapted).

##### **JHipster Version(s)**

4.14.0

##### **JHipster configuration**

Irrelevant

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "myenumfield",
            "fieldType": "True,false,hello",
            "fieldValues": "true,false,hello"
        }
    ],
    "changelogDate": "20180301134309",
    "dto": "no",
    "service": "no",
    "entityTableName": "boop",
    "jpaMetamodelFiltering": false,
    "pagination": "no"
}
```

##### **Browsers and Operating System**
Irrelevant

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
The fix I did will actually still let you use TRUE and FALSE as enum values.  `true`, `false`, and `null` aren't in the reserved words list for Java, maybe we should add them?  We usually check multiple lists instead of just Java which is why we haven't seen issues.
