### ISSUE TITLE
Running a jhipster gateway from IntelliJ gives 404 error on all pages

### ISSUE THREAD

**Issue by KyneSilverhide** [jhipster/generator-jhipster#7210]
##### **Overview of the issue**

Running a jhipster gateway from IntelliJ (as a spring boot application) starts the server but every page I try to access displays a 404 error with "Your request cannot be processed". Running as `./gradlew` works. I followed the README.md and run `yarn install` first.

##### **Motivation for or Use Case**

I'm really missing the debugger...

##### **Reproduce the error**

- Checkout gateway
- `yarn install`
- Run AppGateway.java from IntelliJ

##### **JHipster Version(s)**
I'm using an "old" version, this problem occurs on an existing project, not a new one (not tested yet)
**4.5.2**

##### **JHipster configuration**

> {
  "generator-jhipster": {
    "promptValues": {
      "packageName": "be.xperthis.imt.gateway",
      "nativeLanguage": "en",
      "microservicePath": "../incident-service/"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "gateway",
    "packageName": "be.xperthis.imt.gateway",
    "packageFolder": "be/xperthis/imt/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "REMOVED",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "nl",
      "fr"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

/

##### **Browsers and Operating System**

Windows 10 64 bits, with all browsers.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Are you running `yarn start` also?

**Comment by gmarziou** [comment]
You must run `gulp serve` and access your app at  http://localhost:9000 or you must build frontend first.
See http://www.jhipster.tech/development/#working-with-angularjs-1

**Comment by KyneSilverhide** [comment]
@gmarziou Yes, I'm running `gulp serve` (or just `gulp`), and I have the exact same behavior. It's like the "web" part is not properly deployed when using intellij. 


Note : I tried with the last version of Jhipster, and I don't have the problem on a fresh install (and using `yarn start` instead)

**Comment by gmarziou** [comment]
But are you using the right port?

**Comment by KyneSilverhide** [comment]
@gmarziou  I guess, I'm using http://localhost:9000 (it opens automatically when running gulp).
