### ISSUE TITLE
Spring Cloud Stream adding Micrometer to the application

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7214]
This is to follow ticket https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/324 on our side, and provide more details specific to JHipster.

We are not moving to Micrometer yet because of #7100 - but that should normally happen in the long term.

At the moment, Spring Cloud Stream adds Micrometer in the classpath and configures it, and it can't be turned off. Of course that's a (small) performance issue, but the biggest problem is that it prevents the application from starting, as it monitors HikariCP - and HikariCP doesn't support being monitored by 2 different systems.

So with a "classical" `.yo-rc.json` with Kafka enabled:

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "tmp2",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "0dcc8ed0a9a63867f204a2fe9322d802e952071e",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

The error is:

```
Caused by: java.lang.IllegalStateException: cannot use setMetricRegistry() and setMetricsTrackerFactory() together
	at com.zaxxer.hikari.HikariConfig.setMetricRegistry(HikariConfig.java:734)
	at com.zaxxer.hikari.HikariDataSource.setMetricRegistry(HikariDataSource.java:237)
	at com.mycompany.myapp.config.MetricsConfiguration.init(MetricsConfiguration.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

The workaround for the moment is to remove database monitoring with Dropwizard Metrics when Kafka is configured.

**Comment by jkschneider** [comment]
Could also simply exclude `DataSourcePoolMetricsAutoConfiguration` from your autoconfiguration.

**Comment by pascalgrimaud** [comment]
@jdubois : that explains the failures here https://travis-ci.org/hipster-labs/jhipster-travis-build/builds/348114568
In fact, it's tested but only in our hipster-labs repo, not the official one.

**Comment by jdubois** [comment]
Ah I was wondering that, thanks @pascalgrimaud - this should be solved now by https://github.com/jhipster/generator-jhipster/commit/e67e7312712dcb87bdc36e78fbbcb27637ebe029

**Comment by jdubois** [comment]
I recoded the workaround using your suggestion @jkschneider - thanks a lot!

**Comment by jdubois** [comment]
Closing this as we have a fix for the moment - of course we'll need to migrated to Micrometer in the future, but that's another ticket!
