### ISSUE TITLE
Cannot read property 'clientRootFolder' of undefined

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7216]
##### **Overview of the issue**

I tried to create my [latest blog post](https://developer.okta.com/blog/2018/03/01/develop-microservices-jhipster-oauth) with the code from the `master` branch today.

Unfortunately, it fails when I try to generate a UI for tags in the gateway. 

`$ jhipster entity tag`
Using JHipster version installed globally
Executing jhipster:entity tag
Options:

The entity tag is being created.

? Do you want to generate this entity from an existing microservice? `Yes`
? Enter the path to the microservice root directory: `../blog`

Found the .jhipster/Tag.json configuration file, entity can be automatically generated!

? Do you want to update the entity? This will replace the existing files for this entity, all your
 custom code will be overwritten `Yes, re-generate the entity`

events.js:137
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'clientRootFolder' of undefined
    at context.relationships.forEach (/Users/mraible/dev/generator-jhipster/generators/entity/index.js:669:131)
    at Array.forEach (<anonymous>)
    at module.exports.loadInMemoryData (/Users/mraible/dev/generator-jhipster/generators/entity/index.js:568:39)
    at Object.<anonymous> (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/lib/index.js:399:25)
    at /Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)

##### **Reproduce the error**

Create a gateway app and a blog microservice app. Run import-jdl to import [blog.jh](https://github.com/jhipster/jdl-samples/blob/master/blog.jh) in the blog microservice app. Run `jhipster entity tag` in the gateway app.

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/mraible/apps-v5/gateway
└── generator-jhipster@4.14.0  -> /Users/mraible/dev/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer.gateway",
      "nativeLanguage": "en",
      "microservicePath": "../blog"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "gateway",
    "packageName": "com.okta.developer.gateway",
    "packageFolder": "com/okta/developer/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-tw"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.1

node: v9.5.0

npm: 5.6.0

bower: 1.8.2

yeoman: 2.0.1

yarn: 1.3.2

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I think its becoz the property is not present in old json files. We need to set to default if its not present for backward compatibility

**Comment by MathieuAA** [comment]
@deepu105 I think it's a bit more complicated than that.
It tries to read a `.jhipster/Tag.json` file inside the gateway (nothing has been generated yet there, only the microservice has been filled with entities). The correct path should have been `../blog/.jhipster/Tag.json`.

I've reproduced it yesterday evening and tried to fix it but I don't think my fix was good enough.

**Comment by MathieuAA** [comment]
@deepu105 I'll try to fix it after JCore v2, I see you're quite busy :)

**Comment by mraible** [comment]
FWIW, this still happens using the `master` branch.

**Comment by MathieuAA** [comment]
@mraible Hi. Nobody's on it right now. However, the bug is really easy to reproduce and test so if anyone's got some time to work on it... I expected to be done with JCore v2 by today, but I have to test the subgens work as intended.

**Comment by clement26695** [comment]
Hi everyone. I tried to looked at that and it seems for that the only issue was that the getEntityJson function in the generator-base was trying to read the .json file in the wrong directory when there is a microservice.

I tried to make a fix and it seems working in the context described by @mraible . 

Since I'm new to the JHipster generator and the contributing community, please let me know if I have done something wrong, or if I have to add some tests, etc.
