### ISSUE TITLE
Gateway always shows microservices homepage

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7218]
##### **Overview of the issue**

Using the latest `master` branch, a microservices gateway always shows the microservices (no UI) homepage. 

![image](https://user-images.githubusercontent.com/17892/36924088-9844c9f4-1e2a-11e8-9c37-6a99f966a549.png)

If you run `yarn start`, it shows the expected homepage on port 9000. Running `npm run webpack:build` does not seem to fix this issue.

##### **Motivation for or Use Case**

In previous versions, after running the entity generator, you could run the app with Maven and see the correct homepage.

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/mraible/apps-v5/gateway
└──  (generator-jhipster) invalid error: ENOENT: no such file or directory, open '/Users/mraible/apps-v5/gateway/node_modules/generator-jhipster/package.json

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer.gateway",
      "nativeLanguage": "en",
      "microservicePath": "../blog"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "gateway",
    "packageName": "com.okta.developer.gateway",
    "packageFolder": "com/okta/developer/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-tw"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.1

node: v9.5.0

npm: 5.6.0

bower: 1.8.2

yeoman: 2.0.1

yarn: 1.3.2

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

macOS High Sierra v10.13.3 (17D102)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Yes, I noticed it when testing oauth2 yesterday.
The fix is already done in this PR: https://github.com/jhipster/generator-jhipster/pull/7215
