### ISSUE TITLE
Support for Mongo Altas cloud

### ISSUE THREAD

**Issue by kktam** [jhipster/generator-jhipster#7219]
This is a feature request

Currently it appears that JHipster Mongo does not support Mongo DB Altas cloud. 

In the app.yml, the parameter SPRING_DATA_MONGODB_URI does not support mongdb+srv uri

```
SPRING_DATA_MONGODB_URI=mongodb://jhipstermonoapplication-mongodb:27017
```

when the application run, it will throw an exception.

At this point I am not sure if it an issue with spring-boot-starter-data-mongodb. 

Information about Mongo DB Atlas can be found in here:
[https://docs.atlas.mongodb.com/driver-connection/][https://docs.atlas.mongodb.com/driver-connection/]

**Comment by jdubois** [comment]
Yes we just wrap `spring-boot-starter-data-mongodb` here, and `SPRING_DATA_MONGODB_URI` is a standard Spring Boot propery, so the issue on the Spring Boot/ Spring Data side, not ours.
If there needs to do something specific, that is not provided by Spring Boot, we can do it, of course.

**Comment by jdubois** [comment]
For me this is really a Spring Boot/ Spring Data issue - if we need to do something more, please don't hesitate to tell us, I'll reopen the ticket, of course.
