### ISSUE TITLE
Error while importing jhipster project in eclipse

### ISSUE THREAD

**Issue by DikshantBhatia** [jhipster/generator-jhipster#723]
I scaffolded the jhipster project from jhipster.github.io  Now when i imported the jhipster project in eclipse, the following error comes in workspace. I am attaching the screenshot of the errors.
Please look into this
![err-described](https://cloud.githubusercontent.com/assets/9398275/4875073/c76b892e-6281-11e4-855f-f398d9dc77be.PNG)
![jhiperr](https://cloud.githubusercontent.com/assets/9398275/4875061/3ee485a6-6281-11e4-86a0-3f7525b77d64.PNG)
![jhip project](https://cloud.githubusercontent.com/assets/9398275/4875070/8c6d79ea-6281-11e4-9a0c-ab6e2258873f.PNG)

**Comment by michaelisvy** [comment]
See here: #1446
