### ISSUE TITLE
Not possible to update JHipster to latest JHipster release 4.14.1

### ISSUE THREAD

**Issue by batterista87** [jhipster/generator-jhipster#7232]
##### **Overview of the issue**

Using the command `yarn global upgrade generator-jhipster` is not possible to upgrade the generator. After using it, if I use the command `jhipster --version` I see always the old version 4.14.0

##### **Reproduce the error**

Try to run command `yarn global upgrade generator-jhipster`

##### **JHipster Version(s)**

Currently I've the version 4.14.0

##### **Browsers and Operating System**

Microsoft Windows [Version 10.0.16299.248]
Node 9.7.1 x64
Yarn 1.5.1
Git 2.16.2

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm guessing you are running JHipster in a specific project's folder? If yes, then it's "normal", it's using the version of JHipster that was used in that specific project.
Could you try in a new, empty folder?

**Comment by batterista87** [comment]
Hello Julien,

I tried also in an empty folder (in this case SCANNER-FEED). It seems that it downloads new files, but the version is always 4.14.0

 

C:\SCANNER-FEED>yarn global upgrade generator-jhipster

yarn global v1.5.1

[1/4] Resolving packages...

[2/4] Fetching packages...

[3/4] Linking dependencies...

[4/4] Rebuilding all packages...

success Saved lockfile.

success Saved 268 new dependencies.

info Direct dependencies

└─ generator-jhipster@4.14.1

info All dependencies

├─ ajv@5.5.2

├─ ansi-styles@3.2.1

├─ ansi@0.3.1

├─ are-we-there-yet@1.1.4

├─ argparse@1.0.10

├─ array-differ@1.0.0

├─ array-find-index@1.0.2

├─ array-uniq@1.0.3

├─ arrify@1.0.1

├─ asn1@0.2.3

├─ async@1.5.2

├─ asynckit@0.4.0

├─ aws-sign2@0.7.0

├─ aws4@1.6.0

├─ babel-polyfill@6.23.0

├─ babel-runtime@6.26.0

├─ balanced-match@1.0.0

├─ bcrypt-pbkdf@1.0.1

├─ binaryextensions@2.1.1

├─ boom@4.3.1

├─ brace-expansion@1.1.11

├─ builtin-modules@1.1.1

├─ camelcase-keys@2.1.0

├─ camelcase@2.1.1

├─ caseless@0.12.0

├─ chardet@0.4.2

├─ cheerio@0.22.0

├─ cli-table@0.3.1

├─ clone-buffer@1.0.0

├─ clone-stats@0.0.1

├─ clone@1.0.3

├─ cloneable-readable@1.0.0

├─ co@4.6.0

├─ color-convert@1.9.1

├─ color-name@1.1.3

├─ colors@1.0.3

├─ combined-stream@1.0.6

├─ commander@2.12.2

├─ commondir@1.0.1

├─ concat-map@0.0.1

├─ concat-stream@1.6.1

├─ configstore@1.4.0

├─ core-util-is@1.0.2

├─ cross-spawn@5.1.0

├─ cryptiles@3.1.2

├─ css-select@1.2.0

├─ css-what@2.1.0

├─ currently-unhandled@0.4.1

├─ cycle@1.0.3

├─ dargs@5.1.0

├─ dashdash@1.14.1

├─ dateformat@3.0.3

├─ decamelize@1.2.0

├─ decompress-response@3.3.0

├─ deep-extend@0.4.2

├─ delayed-stream@1.0.0

├─ delegates@1.0.0

├─ detect-conflict@1.0.1

├─ detect-newline@1.0.3

├─ didyoumean@1.2.1

├─ diff@3.5.0

├─ discontinuous-range@1.0.0

├─ domhandler@2.4.1

├─ domutils@1.5.1

├─ duplexer3@0.1.4

├─ ecc-jsbn@0.1.1

├─ editions@1.3.4

├─ ejs@2.5.7

├─ encoding@0.1.12

├─ entities@1.1.1

├─ error-ex@1.3.1

├─ error@7.0.2

├─ esprima@4.0.0

├─ exit-hook@1.1.1

├─ extend@3.0.1

├─ external-editor@2.1.0

├─ extsprintf@1.3.0

├─ eyes@0.1.8

├─ fast-deep-equal@1.1.0

├─ fast-json-stable-stringify@2.0.0

├─ find-up@2.1.0

├─ first-chunk-stream@2.0.0

├─ forever-agent@0.6.1

├─ form-data@2.3.2

├─ fs.realpath@1.0.0

├─ gauge@1.2.7

├─ generator-jhipster@4.14.1

├─ get-stream@3.0.0

├─ getpass@0.1.7

├─ gh-got@6.0.0

├─ github-username@4.1.0

├─ got@7.1.0

├─ grouped-queue@0.3.3

├─ har-schema@2.0.0

├─ har-validator@5.0.3

├─ has-ansi@2.0.0

├─ has-flag@2.0.0

├─ has-symbol-support-x@1.4.2

├─ has-to-string-tag-x@1.4.1

├─ has-unicode@2.0.1

├─ hawk@6.0.2

├─ hosted-git-info@2.5.0

├─ html-wiring@1.2.0

├─ htmlparser2@3.9.2

├─ http-signature@1.2.0

├─ iconv-lite@0.4.19

├─ imurmurhash@0.1.4

├─ indent-string@2.1.0

├─ inflight@1.0.6

├─ inherits@2.0.3

├─ inquirer@3.0.6

├─ insight@0.8.4

├─ interpret@1.1.0

├─ is-arrayish@0.2.1

├─ is-builtin-module@1.0.0

├─ is-finite@1.0.2

├─ is-object@1.0.1

├─ is-promise@2.1.0

├─ is-retry-allowed@1.1.0

├─ is-scoped@1.0.0

├─ is-stream@1.1.0

├─ is-typedarray@1.0.0

├─ is-utf8@0.2.1

├─ isarray@1.0.0

├─ isexe@2.0.0

├─ isstream@0.1.2

├─ istextorbinary@2.2.1

├─ isurl@1.0.0

├─ jhipster-core@1.4.4

├─ js-yaml@3.10.0

├─ json-schema-traverse@0.3.1

├─ json-schema@0.2.3

├─ json-stringify-safe@5.0.1

├─ jsprim@1.4.1

├─ load-json-file@1.1.0

├─ locate-path@2.0.0

├─ lodash._getnative@3.9.1

├─ lodash.assignin@4.2.0

├─ lodash.bind@4.2.1

├─ lodash.debounce@3.1.1

├─ lodash.defaults@4.2.0

├─ lodash.difference@4.5.0

├─ lodash.filter@4.6.0

├─ lodash.flatten@4.4.0

├─ lodash.foreach@4.5.0

├─ lodash.map@4.6.0

├─ lodash.merge@4.6.1

├─ lodash.pad@4.5.1

├─ lodash.padend@4.6.1

├─ lodash.padstart@4.6.1

├─ lodash.pick@4.4.0

├─ lodash.reduce@4.6.0

├─ lodash.reject@4.6.0

├─ lodash.some@4.6.0

├─ lodash.uniq@4.5.0

├─ lodash@4.17.5

├─ log-symbols@2.2.0

├─ loud-rejection@1.6.0

├─ lowercase-keys@1.0.0

├─ lru-cache@4.1.1

├─ make-dir@1.2.0

├─ map-obj@1.0.1

├─ mem-fs-editor@3.0.2

├─ mem-fs@1.1.3

├─ meow@3.7.0

├─ mime-db@1.33.0

├─ mime-types@2.1.18

├─ mimic-fn@1.2.0

├─ mimic-response@1.0.0

├─ minimatch@3.0.4

├─ multimatch@2.1.0

├─ node-fetch@1.6.3

├─ npmlog@2.0.4

├─ nth-check@1.0.1

├─ oauth-sign@0.8.2

├─ onetime@1.1.0

├─ opencollective@1.0.3

├─ opn@4.0.2

├─ os-name@1.0.3

├─ os-shim@0.1.3

├─ os-tmpdir@1.0.2

├─ osenv@0.1.5

├─ osx-release@1.1.0

├─ p-cancelable@0.3.0

├─ p-finally@1.0.0

├─ p-limit@1.2.0

├─ p-locate@2.0.0

├─ p-timeout@1.2.1

├─ p-try@1.0.0

├─ path-exists@3.0.0

├─ path-is-absolute@1.0.1

├─ path-parse@1.0.5

├─ path-type@1.1.0

├─ performance-now@2.1.0

├─ pinkie@2.0.4

├─ pluralize@7.0.0

├─ prepend-http@1.0.4

├─ pretty-bytes@4.0.2

├─ process-nextick-args@2.0.0

├─ pseudomap@1.0.2

├─ punycode@1.4.1

├─ qs@6.5.1

├─ randexp@0.4.6

├─ read-chunk@2.1.0

├─ read-pkg-up@1.0.1

├─ read-pkg@1.1.0

├─ readline2@1.0.1

├─ rechoir@0.6.2

├─ redent@1.0.0

├─ regenerator-runtime@0.10.5

├─ remove-trailing-separator@1.1.0

├─ repeating@2.0.1

├─ replace-ext@0.0.1

├─ request@2.83.0

├─ resolve@1.5.0

├─ restore-cursor@1.0.1

├─ ret@0.1.15

├─ rimraf@2.6.2

├─ rx-lite-aggregates@4.0.8

├─ rx-lite@4.0.8

├─ scoped-regex@1.0.0

├─ semver@5.5.0

├─ shebang-command@1.2.0

├─ shebang-regex@1.0.0

├─ shelljs@0.7.8

├─ signal-exit@3.0.2

├─ slide@1.1.6

├─ sntp@2.1.0

├─ spawn-sync@1.0.15

├─ spdx-correct@3.0.0

├─ spdx-exceptions@2.1.0

├─ sprintf-js@1.0.3

├─ sshpk@1.13.1

├─ stack-trace@0.0.10

├─ string_decoder@1.0.3

├─ string-template@0.2.1

├─ string-width@2.1.1

├─ stringstream@0.0.5

├─ strip-bom-stream@2.0.0

├─ strip-indent@1.0.1

├─ supports-color@2.0.0

├─ tabtab@2.2.2

├─ textextensions@2.2.0

├─ through2@2.0.3

├─ timed-out@4.0.1

├─ tmp@0.0.33

├─ tough-cookie@2.3.4

├─ trim-newlines@1.0.0

├─ tunnel-agent@0.6.0

├─ tweetnacl@0.14.5

├─ typedarray@0.0.6

├─ untildify@3.0.2

├─ url-parse-lax@1.0.0

├─ url-to-options@1.0.1

├─ util-deprecate@1.0.2

├─ uuid@3.2.1

├─ validate-npm-package-license@3.0.3

├─ verror@1.10.0

├─ vinyl-file@2.0.0

├─ which@1.3.0

├─ win-release@1.1.1

├─ winston@2.4.0

├─ write-file-atomic@1.3.4

├─ xdg-basedir@2.0.0

├─ xtend@4.0.1

├─ yallist@2.1.2

├─ yeoman-environment@2.0.5

└─ yeoman-generator@2.0.1

Done in 10.52s.

 

C:\SCANNER-FEED>jhipster --version

Using JHipster version installed globally

4.14.0

 

Da: Julien Dubois [mailto:notifications@github.com] 
Inviato: lunedì 5 marzo 2018 14:49
A: jhipster/generator-jhipster <generator-jhipster@noreply.github.com>
Cc: batterista87 <andrey87@alice.it>; Author <author@noreply.github.com>
Oggetto: Re: [jhipster/generator-jhipster] Not possible to update JHipster to latest JHipster release 4.14.1 (#7232)

 

I'm guessing you are running JHipster in a specific project's folder? If yes, then it's "normal", it's using the version of JHipster that was used in that specific project.
Could you try in a new, empty folder?

**Comment by jdubois** [comment]
And how did you install JHipster in the first place?

**Comment by batterista87** [comment]
To be honest, I don’t remember. I think in C:\Users\Andrea (I tried also in this directory…and also in C:\)

 

But in general, I always upgraded jhipster when I am in path C:\Users\Andrea on the command line

 

Da: Julien Dubois [mailto:notifications@github.com] 
Inviato: lunedì 5 marzo 2018 15:13
A: jhipster/generator-jhipster <generator-jhipster@noreply.github.com>
Cc: batterista87 <andrey87@alice.it>; Author <author@noreply.github.com>
Oggetto: Re: [jhipster/generator-jhipster] Not possible to update JHipster to latest JHipster release 4.14.1 (#7232)

 

And how did you install JHipster in the first place?

**Comment by gmarziou** [comment]
> C:\SCANNER-FEED>jhipster --version
> Using JHipster version installed globally

It clearly states that it uses the global jhipster and not the local one.
So, I guess that something could be wrong in your path or maybe you once installed jhipster using npm rather than yarn.
You could check it with `where jhipster`.

**Comment by jdubois** [comment]
Yes @gmarziou is correct - unless you installed JHipster using Chocolatey or something else, but as you don't remember, it's hard to tell!
Checkout your PATH variable
