### ISSUE TITLE
Verify fs usage

### ISSUE THREAD

**Issue by BridgeAR** [jhipster/generator-jhipster#7236]
##### **Overview of the issue**

I am going through a lot of modules that might have issues using the Node.js fs module by swalling errors. Here in this project there are multiple fs calls without a callback. I can not easily see if those calls are going to Node.js or not. I guess they are not but I just wanted to verify this.

Reference: https://github.com/nodejs/node/pull/18668

**Comment by deepu105** [comment]
We are mostly using the fs instance provided by yeoman, will check this

**Comment by MathieuAA** [comment]
I've just checked and everything looks fine. As Deepu said, most of the code we use (from the fs API) uses the xxxSync version of the functions.

**Comment by jdubois** [comment]
If @MathieuAA says it's fine, then I'm closing this.
Thanks for the warning @BridgeAR !
