### ISSUE TITLE
 Hibernate 2nd-level cache not available when Spring Cache has not selected

### ISSUE THREAD

**Issue by pavankjadda** [jhipster/generator-jhipster#7241]
Hibernate 2nd-level cache not available when Spring Cache has not selected during microservice setup and the cache documentation says "**We do not recommend to use both the Spring cache abstraction and the Hibernate 2nd-level cache for the same objects, as this will make cache invalidation issues even more complex**". How to enable Hibernate 2nd level cache without enabling Spring Cache Abstraction?

**Comment by deepu105** [comment]
You need to enable SPring cache to use Hibernate 2nd level. The comments in the doc is more about adding Spring cache manually for the entity. Maybe the doc can be improved. WDYT @jdubois ?

**Comment by jdubois** [comment]
Oh yes the doc is wrong. Well, not totally wrong, let me improve it.

**Comment by pavankjadda** [comment]
Thanks @jdubois @deepu105
