### ISSUE TITLE
React doesn't support parent-child relationships of the same entity

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7252]
This is on the current master branch, using React.

Using the configuration below, the React front-end will not compile:
```
ERROR in [at-loader] ./src/main/webapp/app/entities/category/category.reducer.ts:13:3
    TS1117: An object literal cannot have multiple properties with the same name in strict mode.

ERROR in [at-loader] ./src/main/webapp/app/entities/category/category.reducer.ts:13:3
    TS2300: Duplicate identifier 'FETCH_CATEGORIES'.
```

I'm also worried that near to that line we have:
```
// TODO: this should be replaced by using the action and state from the related entity
```
I'm not sure if there is a link with that TODO, but it should also be solved.

Here's the output of `jhipster info` in order to reproduce:

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.jhipster.demo"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "tmp",
    "packageName": "io.jhipster.demo",
    "packageFolder": "io/jhipster/demo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "aws": {
      "apps": [
        {
          "baseName": "tmp",
          "performance": "low",
          "fargate": {
            "CPU": "1024",
            "memory": "2GB",
            "taskCount": 1
          },
          "database": {
            "size": "db.t2.small",
            "supportedEngines": [
              "mariadb",
              "mysql"
            ],
            "instances": 1
          },
          "scaling": "low",
          "dbType": "mysql",
          "auroraEngine": "aurora-mysql",
          "auroraFamily": "aurora-mysql5.7",
          "auroraClusterParam": "character_set_database: utf8",
          "auroraDbParam": "sql_mode: IGNORE_SPACE",
          "auroraClusterParameterGroupName": "default.aurora-mysql5.7",
          "stackId": "arn:aws:cloudformation:us-east-1:773603265307:stack/jhipster-test-ippon-tmp-1TJNBPYYOU71Q/68f75810-2154-11e8-abbd-500c28b4e4fd",
          "EcrRepositoryName": "jhipster-test-ippon/tmp",
          "EcrRepositoryUri": "773603265307.dkr.ecr.us-east-1.amazonaws.com/jhipster-test-ippon/tmp",
          "dockerImageTag": "773603265307.dkr.ecr.us-east-1.amazonaws.com/jhipster-test-ippon/tmp:latest"
        }
      ],
      "vpc": {
        "id": "vpc-5601c02d",
        "cidr": "172.31.0.0/16",
        "elbSubnets": [
          "subnet-a87f43cc",
          "subnet-38246b65"
        ],
        "appSubnets": [
          "subnet-a87f43cc",
          "subnet-38246b65"
        ],
        "appSubnetsLaunchWithPublicIP": true
      },
      "region": "us-east-1",
      "cloudFormationName": "jhipster-test-ippon",
      "s3BucketName": "jhipster-test-ippon-1519857484651",
      "s3bucketLocation": "/jhipster-test-ippon-1519857484651",
      "s3BaseTemplate": {
        "ETag": "\"812287f74fa112d41119bd33a27ec856\"",
        "Location": "https://jhipster-test-ippon-1519857484651.s3.amazonaws.com/base.template.yml",
        "key": "base.template.yml",
        "Key": "base.template.yml",
        "Bucket": "jhipster-test-ippon-1519857484651"
      }
    }
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Category (category) {
  description String required,
  sortOrder Integer,
  dateAdded LocalDate,
  dateModified LocalDate,
  status CategoryStatus
}
entity Product (product) {
  title String required,
  keywords String,
  description String,
  rating Integer,
  dateAdded LocalDate,
  dateModified LocalDate
}
entity Customer (customer) {
  firstName String,
  lastName String,
  email String,
  telephone String
}
entity Address (address) {
  address1 String,
  address2 String,
  city String,
  postcode String required maxlength(10),
  country String required maxlength(2)
}

enum CategoryStatus {
  AVAILABLE,
  RESTRICTED,
  DISABLED
}

relationship OneToMany {
  Customer{address} to Address{customer}
}
relationship ManyToOne {
  Category{parent} to Category
}
relationship ManyToMany {
  Category{product(title)} to Product{category}
}

paginate Category, Customer with pagination
service Category with serviceClass
paginate Product with infinite-scroll
paginate Address with pager

</pre>
</details>

**Comment by deepu105** [comment]
I added that TODO as the current code is not the correct way to handle
relationships, i'll be working on this soon, so assign this to me


Thanks & Regards,
Deepu
