### ISSUE TITLE
Generated Jenkins Pipeline Fails

### ISSUE THREAD

**Issue by mmajor73** [jhipster/generator-jhipster#7253]
##### **Overview of the issue**

When I attempt to integrate cdi-cd using a jenkins files Generate using JHipster the pipleine fails when installing yarn..[workspace] Running shell script

+ ./mvnw com.github.eirslett:frontend-maven-plugin:yarn
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Contact Mono 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:yarn (default-cli) @ contract-mono ---
[INFO] Running 'yarn ' in /var/lib/jenkins/jobs/contactmono2/workspace
[INFO] yarn install v1.5.1
[INFO] [1/5] Validating package.json...
[INFO] [2/5] Resolving packages...
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@0.5.x"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.3"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@0.1.x"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.3"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@~0.4.1"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@0.5.x"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.7"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@~0.5.1"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.4.2"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.3"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@~0.5.0"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.3"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.1"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@~0.2.0"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.4.4"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.1.41"
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.4.2"
[INFO] [3/5] Fetching packages...
[INFO] info fsevents@1.1.3: The platform "linux" is incompatible with this module.
[INFO] info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[INFO] [4/5] Linking dependencies...
[ERROR] warning " > bootstrap@4.0.0" has unmet peer dependency "popper.js@^1.12.9".
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code -1
Finished: FAILURE

##### **JHipster Version(s)**
4.14.1

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.myage.contacts_app_mono"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "contractMono",
    "packageName": "com.myage.contacts_app_mono",
    "packageFolder": "com/myage/contacts_app_mono",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "6fcd795f067a6f64e98b4e32fd9708ca3b063f71",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Is your Jenkins machine properly configured? please provide steps to reproduce. Please follow our issue templates properly

**Comment by gmarziou** [comment]
Where's the error? I can see only warnings.

**Comment by mmajor73** [comment]
The script exits with -1. I will upload the jenkins file.

**Comment by mmajor73** [comment]
I generated the Jenkins file using jhipster ci-cd
Started a jenkins instance in openshift.
created  jenkins pipeline project that references my github project.
selected build now on my project in jenkins
Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Deepu K Sasidharan <notifications@github.com> Date: 3/7/18  5:24 PM  (GMT-05:00) To: jhipster/generator-jhipster <generator-jhipster@noreply.github.com> Cc: mmajor73 <mmajor@agetechnology.com>, Author <author@noreply.github.com> Subject: Re: [jhipster/generator-jhipster] Generated Jenkins Pipeline Fails (#7253) 
Is your Jenkins machine properly configured? please provide steps to reproduce. Please follow our issue templates properly

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jhipster/generator-jhipster","title":"jhipster/generator-jhipster","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jhipster/generator-jhipster"}},"updates":{"snippets":[{"icon":"PERSON","message":"@deepu105 in #7253: Is your Jenkins machine properly configured? please provide steps to reproduce. Please follow our issue templates properly"}],"action":{"name":"View Issue","url":"https://github.com/jhipster/generator-jhipster/issues/7253#issuecomment-371306926"}}}

**Comment by gmarziou** [comment]
> The script exits with -1. I will upload the jenkins file.

Yes but why? There's nothing in what you have provided us that can help diagnose the issue.
Closing until we get more information as there's currently no evidence it's a JHipster issue.
