### ISSUE TITLE
Lint + Prettier Rule Collision (Angular)

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#7257]
##### **Overview of the issue**
Prettier causes lint issues, noticed while `yarn start` was running and made a commit (the `precommit` git hook runs prettier).  Doesn't look like it affects React.

Error from extra semicolon added by prettier: `ERROR: /src/main/webapp/app/home/home.component.ts[43, 6]: Unnecessary semicolon`

Related, prettier changes `'You\'re Online!'` to `"You're Online!"` which also fails due to double quotes.  According to prettier docs, "If the number of quotes outweighs the other quote, the quote which is less used will be used to format the string"

##### **Motivation for or Use Case**
Prettier should not cause lint issues, the project would fail a prod build due to lint issues created during  the `precommit` hook.  It also affects any CI builds.

##### **Reproduce the error**
Generate a project
Add an arrow method to a component:
```
    arrowMethod = () => {
        alert('You\'re online');
    }
```
Run prettier
`yarn prettier:format`
Run lint and there are issues
`yarn run lint`

##### **Suggest a Fix**

I would update the `.prettierrc` for the semicolon issue but it looks like it's intended behavior https://github.com/prettier/prettier/issues/1444

Not sure what to do about the quotes issue besides disabling tslint in my project for that line.

##### **JHipster Version(s)**
master c519a9bd115050c823f773e4690c419fe0567dc6

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
We should disable lint rules that are conflicting with prettier, so if prettier handles something that should have a higher preference. That is the suggested approach.
