### ISSUE TITLE
React default generation is not working

### ISSUE THREAD

**Issue by agaspardcilia** [jhipster/generator-jhipster#7261]
##### **Overview of the issue**

Error when trying to generate an App using default settings for React.
```
[ERROR] /home/ippon/repos/testReact/src/main/java/com/mycompany/myapp/config/CacheConfiguration.java:[38,73] cannot find symbol
  symbol:   variable USERS_BY_LOGIN_CACHE
  location: interface com.mycompany.myapp.repository.UserRepository
[ERROR] /home/ippon/repos/testReact/src/main/java/com/mycompany/myapp/config/CacheConfiguration.java:[39,73] cannot find symbol
  symbol:   variable USERS_BY_EMAIL_CACHE
  location: interface com.mycompany.myapp.repository.UserRepository

```

##### **Reproduce the error**

Just build any React project with default settings.

##### **Suggest a Fix**

Probably have something to do with #7254

##### **JHipster Version(s)**

4.14.0

##### **JHipster configuration**

Using JHipster version installed globally
Executing jhipster:info
Options: 
##### **JHipster Version(s)**

```
test-react@0.0.0 /home/ippon/repos/testReact
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "testReact",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v8.10.0

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.3.2

Docker version 17.12.1-ce, build 7390fc6

docker-compose version 1.16.1, build 6d1ac21

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

none

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I don't understand why the current status of the build is green... :worried:

**Comment by ruddell** [comment]
This was happening for all apps, both Angular and React.  `this.cacheManagerIsAvailable` is always false on the first generation because it was declared before the prompts.  After running `jhipster` again, it prompts to insert all of the cache statements then the project will compile.  @pascalgrimaud  Do we call `jhipster` twice in the Travis tests? 

I moved the declaration below the prompts in my PR.

**Comment by pascalgrimaud** [comment]
@ruddell : no, it should call once
https://github.com/jhipster/generator-jhipster/blob/master/travis/scripts/02-generate-project.sh

So strange

**Comment by ruddell** [comment]
@pascalgrimaud The tests pass because we generate from an existing .yo-rc.json, so the variable was filled correctly.  If you answer the prompts like a user would, it fails.

**Comment by pascalgrimaud** [comment]
oh I see ! Travis can't answer the question, so it will always generate project from existing configuration
