### ISSUE TITLE
Update libraries before v5

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7272]
Update to latest libraries before v5

- [ ] Generator npm dependencies
- [ ] Angular client side libs
- [x] Webpack libs -> need to remove custom repo definitions
- [x] React libs
- [x] Maven/Gradle plugins
- [x] Server-side libs
- [x] Docker deps

**Comment by deepu105** [comment]
@jhipster/developers it would be nice if we can split this among us

**Comment by atomfrede** [comment]
I will take care of the gradle part (already did something https://github.com/jhipster/generator-jhipster/pull/7226, but there is more to update I've seen)

**Comment by erikkemperman** [comment]
For jhipster-dependencies, and server-side lib, and through those indirectly the generator, it would be great if spring-platform Cairo were available prior to JHv5... It looks like the first RC is done, but not yet released:

https://github.com/spring-io/platform/milestone/28?closed=1

It says overdue by 4 days, so I'm hoping it might come out this week!

**Comment by erikkemperman** [comment]
But even before that's out, we could take a look at aligning the versions. I'll try to do that but would first like to update the PR re: unification of server lib and dependencies. That might otherwise conflict with efforts to bump dependencies.

**Comment by erikkemperman** [comment]
I've updated the single-repo PR: https://github.com/jhipster/jhipster/pull/29

**Comment by gmarziou** [comment]
Sorry I can't help here, I'm on holidays for next 10 days.

**Comment by deepu105** [comment]
I update many of the react and Angular deps, but need to do one more pass right before release

**Comment by jdubois** [comment]
On the server-side nearly everything is under control.
For Docker I already updated many things, it should be good.

**Comment by erikkemperman** [comment]
One artifact was left behind while upgrading the server-side dependencies: infinispan. I put some effort into resolving this, but have been unable to get things working...

I have to move on to other things now, so perhaps someone else could take a look? Julien mentioned earlier that @srinivasa-vasu probably knows this stuff well?

I'm reasonably confident (but not 100% certain) that what I have done thus far is more or less correct -- it's just that there's still something missing. Here are my changes:

https://github.com/erikkemperman/jhipster/commits/upgrade-infinispan  (disregard the last commit, it just points Travis to my fork of the generator)

https://github.com/erikkemperman/generator-jhipster/commits/upgrade-infinispan

Here is the failing build, if that helps:
https://travis-ci.org/erikkemperman/jhipster/builds/355867062

**Comment by pascalgrimaud** [comment]
Ping @tchlyah, as he's the one who made the initial support. Can you help us ?

**Comment by pascalgrimaud** [comment]
Oops, sorry @tchlyah, it's infinispan, and not couchbase, sorry for pinging you

**Comment by erikkemperman** [comment]
@pascalgrimaud Do you remember why you removed this `&&`?
https://github.com/jhipster/generator-jhipster/commit/56749899c124e283577a25097fd400db75de4c5d
(And similar in the gradle build)

I thought maybe it can be put back if `infinispan-hibernate-cache` replaces `hibernate-infinispan`.

**Comment by jdubois** [comment]
I'm closing this as:

- For NPM it's currently quite stable, and I just updated Insight (which was causing a security warning)
- For Angular I don't think we are very late behind
- Everything else is up to date

**Comment by erikkemperman** [comment]
> Everything else is up to date

Except infinispan! (Sorry to repeat myself from another thread)

**Comment by jdubois** [comment]
Oh yes but it's used only by a tiny tiny portion of users so we shouldn't focus on it.
