### ISSUE TITLE
"enableSocialSignIn":  remains ..false 

### ISSUE THREAD

**Issue by nutrimax1987** [jhipster/generator-jhipster#7274]
##### **Overview of the issue**
While generating app and after selecting 'generator-jhipster-spring-social-connectors' ..it still remains
    "enableSocialSignIn": false - 

##### **How i fix it ..**
1. changing it manually to
2.  run 'jhipster --force --with-entities'

##### **Reproduce the error**
? Which *type* of application would you like to create? Microservice gateway
? What is the base name of your application? gate
? As you are running in a microservice architecture, on which port would like your server to run? It should b
e unique to avoid port conflicts. 8080
? What is your default Java package name? com.gate.app
? Which service discovery server do you want to use? JHipster Registry (uses Eureka, provides Spring Cloud Co
nfig support and monitoring dashboards)
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? PostgreSQL
? Do you want to use Hibernate 2nd level cache? No
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? Search engine using Elasticsearch, WebSockets using Spring
Websocket, API first development using swagger-codegen
? Which *Framework* would you like to use for the client? Angular 5
? Would you like to enable *SASS* support using the LibSass stylesheet preprocessor? Yes
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install French, German, Russian, Spanish
? Besides JUnit and Karma, which testing frameworks would you like to use? Gatling
? Would you like to install other generators from the JHipster Marketplace? Yes
? Which other modules would you like to use? (generator-jhipster-db-helper-1.0.0) A JHipster module for already existing da tabases, (generator-jhipster-docker-2.4.0) Additional Docker support: Docker Hub, Local SMTP Server, NGinx, (generator-jhip ster-ci-1.0.0) JHipster module, Continuous Integration support in your JHipster application, (generator-jhipster-bootstrap- material-design-3.5.1) Add Material design to your JHipster application, (generator-jhipster-elasticsearch-reindexer-1.1.0)  Generates a service that reindexes all database rows for each of your entities, (generator-jhipster-ionic-3.1.1) A JHipste r Module that generates an Ionic Client, (generator-jhipster-swagger-api-first-1.0.1) JHipster module to support API first
development using swagger, (generator-jhipster-leaflet-1.0.0) JHipster module to install a sample of ui-leaflet maps on you r JHipster application., (generator-jhipster-elasticsearch-rest-client-1.0.0) JHipster module, Elasticsearch rest client.,
(generator-jhipster-swagger-cli-2.0.5) JHipster module to generate swagger client code from a swagger definition, (generato r-jhipster-postgresuuid-converter-0.2.2) Postgresql Long to UUID converter, (generator-jhipster-spring-social-connectors-0. 0.1) Add Spring social connector to your JHipster application

Installing languages: en, fr, de, ru, es
   create package.json
   create README.md
   create .gitignore

##### **JHipster Version(s)**
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.gate.app",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "gateway",
    "packageName": "com.gate.app",
    "packageFolder": "com/gate/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-db-helper",
        "version": "1.0.0"
      },
      {
        "name": "generator-jhipster-docker",
        "version": "2.4.0"
      },
      {
        "name": "generator-jhipster-ci",
        "version": "1.0.0"
      },
      {
        "name": "generator-jhipster-bootstrap-material-design",
        "version": "3.5.1"
      },
      {
        "name": "generator-jhipster-elasticsearch-reindexer",
        "version": "1.1.0"
      },
      {
        "name": "generator-jhipster-ionic",
        "version": "3.1.1"
      },
      {
        "name": "generator-jhipster-swagger-api-first",
        "version": "1.0.1"
      },
      {
        "name": "generator-jhipster-leaflet",
        "version": "1.0.0"
      },
      {
        "name": "generator-jhipster-swagger-cli",
        "version": "2.0.5"
      },
      {
        "name": "generator-jhipster-postgresuuid-converter",
        "version": "0.2.2"
      },
      {
        "name": "generator-jhipster-spring-social-connectors",
        "version": "0.0.1"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de",
      "ro",
      "es"
    ]
  }
}

##### **Environment and Tools**
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.14.2.windows.2
node: v9.3.0
npm: 5.6.0
gulp:
[22:48:16] CLI version 2.0.1
yeoman: 2.0.1
yarn: 1.3.2
Docker version 18.03.0-ce-rc1, build c160c73
docker-compose version 1.19.0, build 9e633ef3

##### **Browsers and Operating System**
Windows 10 , Chrome

**Comment by ruddell** [comment]
You need to select to enable Social Login when generating your project.  

```
Which other technologies would you like to use?
❯◯ Social login (Google, Facebook, Twitter)
 ◯ Search engine using Elasticsearch
 ◯ WebSockets using Spring Websocket
 ◯ API first development using swagger-codegen
 ◯ Asynchronous messages using Apache Kafka
```

**Comment by nutrimax1987** [comment]
I do select but it looks different ..like generator-jhipster-spring-social-connectors-0. 0.1
