### ISSUE TITLE
The cli generator hangs on nested questions when using node 8.1.0

### ISSUE THREAD

**Issue by Jiri-Kremser** [jhipster/generator-jhipster#7279]
##### **Overview of the issue**

When using node `8.1.0` the first question works well, but the inquirer library stop working on second nested question, it doesn't accept any input nor `CTRL+C` so I had to close the tab w/ it. It's probably related to https://github.com/SBoudrias/Inquirer.js/issues/547

Easy workaround is upgrading the node.

Sorry in advance in case it is a known issue or duplicate :)

##### **Browsers and Operating System**

Fedora 26

**Comment by deepu105** [comment]
Please use an LTS version of node (8.9.x) and that is the minimum we support

Also please follow our issue template when opening issues, else we cant help you
