### ISSUE TITLE
Feature Request: Adding a backend option for .net core

### ISSUE THREAD

**Issue by waynethompson** [jhipster/generator-jhipster#7283]
This request has come from a [reddit post a few months ago](https://www.reddit.com/r/dotnet/comments/7l6o16/is_there_anything_like_jhipster_for_net_and_if/)
 where it was talked about with the new .net core being similar to spring boot, it could be conceived that jhipster could add .net core as a backend option.

.net core is cross platform and has [minimal requirements](https://www.microsoft.com/net/learn/get-started/macos) to get started. This addition to the project would allow those users who are mandated to use .net still reap the rewards of the jhipster end to end scaffolding which is something missing in the .net world. The c# language is not that far removed from java (some may say that it is a copy) so I would assume that many of the same functions within the generator could be reused or copied and altered slightly.

**Comment by deepu105** [comment]
Hi we won't be doing this in the main generator but this is something that can be a blueprint, its a new feature that we are adding to JHipster that lets you override some parts of the generator. Take a look at the kotlin blueprint for example. You could build a .net blueprint and we will help you were possible. https://github.com/jhipster/jhipster-kotlin

**Comment by jdubois** [comment]
yes @deepu105 is correct
@waynethompson I know several person who also want this, and I think it would be quite successful, so we'll do our best to support you if you want to do it. Just wait a little bit for JHipster 5, the blueprint support should be the solution for you, indeed.

**Comment by gmarziou** [comment]
This would a huge effort, the biggest difficulty would not be the different language but the libraries. Kotlin is much simpler in comparison as it is a JVM language and so can use same libs as the java. I'd be very admirative of someone who succeeds in doing it.
