### ISSUE TITLE
Enable application generation from JDL

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7284]
With JDL v2, it would be possible to generate applications form JDL, the import-jdl sub gen needs to support this.

- [ ] Generate apps if JDL has any via import-jdl
- [ ] Create a shortcut flag to run import jdl from app generator
- [ ] Update the JDL studio sample with app config
- [ ] Update docs for this

**Comment by deepu105** [comment]
@MathieuAA i'll work on this once v2 is published. For app generation, JHcore generates the yo-rc file right? else could you update this ticket with some details on what it will generate

**Comment by MathieuAA** [comment]
I have the code needed for the subgens update. It's pushed and tested. I can do the update if you wantLe 13 mars 2018 08:47, Deepu K Sasidharan <notifications@github.com> a écrit :@MathieuAA i'll work on this once v2 is published. For app generation, JHcore generates the yo-rc file right? else could you update this ticket with some details on what it will generate

**Comment by deepu105** [comment]
@MathieuAA can you do a PR, i'll take a look and update if needed

**Comment by MathieuAA** [comment]
I'll try to make a PR this week-end or tomorrow at best. I'm currently struggling with the application aspect of the JDL and its link with the generator.

**Comment by deepu105** [comment]
Let me know if you need help, just make a WIP PR with what you have and we
can work together on it


Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
Okay, JCore v2 is out. I'll make a PR before it's raining bugs :)

**Comment by MathieuAA** [comment]
Nevermind, it's not raining but snowing bugs (for those in France, you know what I'm talking about).
The PR is mostly ready but some tests fail and I've got to find out why. I expect to be done by tomorrow or the day after.

**Comment by MathieuAA** [comment]
@deepu105 ok, I got it working. Gonna patch release JCore to v2.0.1 to fix some things and propose a PR ASAP.

**Comment by deepu105** [comment]
The PR is merged
