### ISSUE TITLE
Translation not working on Gateway UI

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#7288]
Translations for gateway application is not working on the current master. 

Getting Translation not found error. 

@deepu105 can you check this, probably because of the recent wp4 updates.

**Comment by pascalgrimaud** [comment]
Not only for Gateway. I have the same for simple monolith, in administration's page

**Comment by deepu105** [comment]
I'll take a look this weekend


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
duplicate of #7307
