### ISSUE TITLE
JHipster UAA does not work on the master branch

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7301]
I'm testing the current master branch, which will become JHipster 5 soon.

Doing a simple microservice architecture with JHipster UAA, I'm not redirected to the UAA server, so obviously I'm not correctly authenticated and it fails.

@xetys do you have the time to take a look? It might not be very complex, we didn't touch that part as far as I remember

**Comment by xetys** [comment]
seems like it's time to move all my kubernetes/go/bachelor-thesis stuff aside...I'll schedule the next weeks for more JHipster topics as the list is growing..

**Comment by jdubois** [comment]
I'm sorry about this @xetys - I hope it's not something very complex, I don't understand why there is anything broken here, we're mostly working on React, so the Angular part should work as well as before

**Comment by xetys** [comment]
don't feel sorry, you are doing a huge piece of work on v5 and it's obvious that stuff gets broken. I just had a lot of time problems in the past, as of my k8s focus and pending thesis and some private issues...

hard to keep everything in focus, but yeah, I will do that the next days.

**Comment by jdubois** [comment]
Oh, but whatever happens, put your private issues first....

**Comment by BhawaniSingh** [comment]
I'll look over this weekend.

**Comment by BhawaniSingh** [comment]
@jdubois I think I've found the source of issue,

Issue is in UAA

In Spring security 4,  in DaoAuthenticationProvider class,  PasswordEncoder from package `org.springframework.security.authentication.encoding` is used, and for matching the password `boolean isPasswordValid(String encPass, String rawPass, Object salt);` was being used, for requests with Basic Authorization Header `salt` is null, so the encPass && rawPass is always same (changeit)

But In Spring security 5,  in DaoAuthenticationProvider class,  PasswordEncoder from package  `org.springframework.security.crypto.password` is used, and for matching the password
`boolean matches(CharSequence rawPassword, String encodedPassword);` is used, but the value for rawPassword, encodedPassword is same (changeit in our case), but encodedPassword has to be a BcryptString or else it will, this is causing UAA to fail

When I generated the UAA from the latest release (4.14.1) and other part of microservices from the master branch, login was success

Let me know If more detail is required,

Sorry for my bad English

**Comment by BhawaniSingh** [comment]
To fix this issue, we need to add `PasswordEncoder` dependency from package `org.springframework.security.crypto.password.PasswordEncoder` in UaaConfiguration and encode the inMemory Secret.

I've tested it and It works fine

**Comment by jdubois** [comment]
Oh thanks so much for the detailed analysis!!! Could you do a PR on this?

**Comment by BhawaniSingh** [comment]
Sure, but it’s too late over here now, I’ll do one over the weekend

**Comment by jdubois** [comment]
Closing as #7310 is merged
