### ISSUE TITLE
Duplication code

### ISSUE THREAD

**Issue by JulioJu** [jhipster/generator-jhipster#7302]
##### **Overview of the issue**
* https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/webapp/app/app.route.ts seems to not be used. This code is duplicatated with https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/webapp/app/layouts/navbar/navbar.route.ts.
* In an entity generated, entity.service.ts have two methods identicals : `convertItemFromServer` and `convert`. We could see that for example in https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/webapp/app/entities/bank-account/bank-account.service.ts.

##### **Motivation for or Use Case**

It could be cool to not have duplicated code. Simpler to understand the code. Safer. 

##### **Related issues**

No related issues found. I've searched with keywords « navbar.route.ts » , « app.route.ts », « convertItemFromServer ».

##### **JHipster Version(s)**
JHipster 4.14.1

##### **JHipster configuration**
Irrelevant. All configurations. See the official sample  https://github.com/jhipster/jhipster-sample-app/.

**Comment by jdubois** [comment]
Oh yes they should be refactored.
For the entities, maybe there could be some common code in https://github.com/jhipster/ng-jhipster

I don't think we'll have time to do this before JHipster 5, @JulioJu could you provide a PR? It's not that hard, and we'll help you.

**Comment by JulioJu** [comment]
@jdubois.
I passed some time on the code of [bank-account.service.ts](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts). If I understand well, some code in this file are only copy of objects, but maybe there are not useful ? 
For example:
1. `convertItemFromServer` and `convert` is simply compiled as below:
```javascript
BankAccountService.prototype.convert = function(bankAccount) {
    var copy = Object.assign({}, bankAccount);
    return copy;
};
``` 
Why it is useful to copy this object ? This  prototype is used only in class methode `create` and `update`. Why it is useful to use copy of object `bankAccount` instead of directly the object `bankAccount` at lines [19](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts#L19) and [25](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts#L25) ?

2. Same question for `BankAccountService.prototype.convertItemFromServer` at lines [46](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts#L46) and [54](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts#L54) 

3. In definition of the class methods `convertResponse` and `convertArrayResponse`  I don't understand why there is `res.clone({body})` at lines [47](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts#L47) and [56](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts#L56). `res` and `res.clone({body})` are equals (comparaison with `JSON.stringify(res) === JSON.stringify(res.clone({body}))` as explained in [Stackoverflow](https://stackoverflow.com/questions/1068834/object-comparison-in-javascript)). 

4. Moreover, it's not useful to return a copy of the Object, and not directly this object at lines [21](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts#L21), [27](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts#L27), [32](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts#L32) and [38](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts#L38).

==> Therfore, maybe  [bank-account.service.ts](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/bank-account/bank-account.service.ts) could only have following class methods.
```typescript
    create(bankAccount: BankAccount): Observable<EntityResponseType> {
        return this.http.post<BankAccount>(this.resourceUrl, bankAccount, { observe: 'response' });
    }

    update(bankAccount: BankAccount): Observable<EntityResponseType> {
        return this.http.put<BankAccount>(this.resourceUrl, bankAccount, { observe: 'response' });
    }

    find(id: number): Observable<EntityResponseType> {
        return this.http.get<BankAccount>(`${this.resourceUrl}/${id}`, { observe: 'response'});
    }

    query(req?: any): Observable<HttpResponse<BankAccount[]>> {
        const options = createRequestOption(req);
        return this.http.get<BankAccount[]>(this.resourceUrl, { params: options, observe: 'response' });
    }

    delete(id: number): Observable<HttpResponse<any>> {
        return this.http.delete<any>(`${this.resourceUrl}/${id}`, { observe: 'response'});
    }
```

What do you think about that ?

**Comment by deepu105** [comment]
I think the idea of creating a copy so that the object is not mutated
started from old code, may be its not required anymore. Let me take a
closer look at the code

**Comment by deepu105** [comment]
// the `convert` call can be inlined in below line for these 2 methods
```
    create(bankAccount: BankAccount): Observable<EntityResponseType> {
        const copy = this.convert(bankAccount);
        return this.http.post<BankAccount>(this.resourceUrl, copy, { observe: 'response' })
            .map((res: EntityResponseType) => this.convertResponse(res));
    }

    update(bankAccount: BankAccount): Observable<EntityResponseType> {
        const copy = this.convert(bankAccount); // the convert call can be inlined in below line
        return this.http.put<BankAccount>(this.resourceUrl, copy, { observe: 'response' })
            .map((res: EntityResponseType) => this.convertResponse(res));
    }
```

// this method can be avoided and we can call `res.clone({ body: this.convertItemFromServer(res.body) })` directly I guess
```
    private convertResponse(res: EntityResponseType): EntityResponseType {
        const body: BankAccount = this.convertItemFromServer(res.body);
        return res.clone({body});
    }
```

This method is still needed as its difficult to avoid in the template as when you have date fields the method will have unique logic inside, but indeed the cloning inside this is not needed, take a look at our template and if you are willing to spend time to get rid of the method when not needed then i'll welcome the change, I just dont have the time myself
```
    /**
     * Convert a returned JSON object to BankAccount.
     */
    private convertItemFromServer(bankAccount: BankAccount): BankAccount {
        const copy: BankAccount = Object.assign({}, bankAccount);
        return copy;
    }
```
Same goes for this method, its needed if you have dates in an entity. But since we convert input object here the clone is needed to avoid mutating the object that is bound to the model
```
    /**
     * Convert a BankAccount to a JSON which can be sent to the server.
     */
    private convert(bankAccount: BankAccount): BankAccount {
        const copy: BankAccount = Object.assign({}, bankAccount);
        return copy;
    }
}
```

**Comment by JulioJu** [comment]
Thanks for your answer @deepu105. Ok, some code it's useful when the entity have date. We could see  for example in [operation.service.ts](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/operation/operation.service.ts).

Please considere the code at the end of this comment.

* In methods `create`, `update`, `find`, and `query` we return the mutated EntityResponseType (named « res »), and not the original EntityResponseType. So the original EntityResponseType is not useful and could be directrly mutated in methods `convert*`. In any case, in methods `create` and `update`, the original object is kept thanks the line `const copy = Object.assign({}, operation);`

* We could see than in [banck-account.service](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/operation/bank-account.service), « , private dateUtils: JhiDateUtils » is not generated. Contrary to  [operation.service.ts](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/operation/operation.service.ts), where « , private dateUtils: JhiDateUtils » is generated. We could follow the same rules for generate:
  1.  the `map` expression in methods `create`, `update`, `find` and `query`.
  2.  functions `convertDate` and `convertDateArrayResponse` 

With this considerations, we could generate the following code for the file [operation.service.ts](https://github.com/jhipster/jhipster-sample-app/blob/070c03df773dce566f7610f978669798e0a04c92/src/main/webapp/app/entities/operation/operation.service.ts) (without the comments). 

```typescript
@Injectable()
export class OperationService {

    private resourceUrl =  SERVER_API_URL + 'api/operations';

    constructor(private http: HttpClient, private dateUtils: JhiDateUtils) { }

    create(operation: Operation): Observable<EntityResponseType> {
        const copy = Object.assign({}, operation);
        return this.http.post<Operation>(this.resourceUrl, copy, { observe: 'response' })
            // We could see than in banck-account.service, « , private dateUtils: JhiDateUtils » is not generated.
            // In the template, for the next line use the same rule as for generate the variable dateUtils.
            .map((res: EntityResponseType) => this.convertDate(res))
        ;
    }

    update(operation: Operation): Observable<EntityResponseType> {
        const copy = Object.assign({}, operation);
        return this.http.put<Operation>(this.resourceUrl, copy, { observe: 'response' })
            // Same comment as in create method.
            .map((res: EntityResponseType) => this.convertDate(res))
        ;
    }

    find(id: number): Observable<EntityResponseType> {
        return this.http.get<Operation>(`${this.resourceUrl}/${id}`, { observe: 'response'})
            // Same comment as in create method.
            .map((res: EntityResponseType) => this.convertDate(res))
        ;
    }

    query(req?: any): Observable<HttpResponse<Operation[]>> {
        const options = createRequestOption(req);
        return this.http.get<Operation[]>(this.resourceUrl, { params: options, observe: 'response' })
            // Same comment as in create method.
            .map((res: HttpResponse<Operation[]>) => this.convertDateArrayResponse(res))
        ;
    }

    delete(id: number): Observable<HttpResponse<any>> {
        return this.http.delete<any>(`${this.resourceUrl}/${id}`, { observe: 'response'});
    }

    // In the template, for the next function use the same rule as for generate the variable dateUtils.
    private convertDate(res: EntityResponseType): EntityResponseType {
        res.body.date = this.dateUtils.convertDateTimeFromServer(res.body.date);
        return res;
    }

    // In the template, for the next function use the same rule as for generate the variable dateUtils.
    private convertDateArrayResponse(res: HttpResponse<Operation[]>): HttpResponse<Operation[]> {
        for (let i = 0; i < res.body.length; i++) {
            res.body[i].date = this.dateUtils.convertDateTimeFromServer(res.body[i].date);
        }
        return res;
    }

}
```

What do you think about that ?

**Comment by deepu105** [comment]
Yes, if you are interested in doing a PR its fine by me


Thanks & Regards,
Deepu
