### ISSUE TITLE
Admin Module Translations Missing for Angular

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#7307]
##### **Overview of the issue**
The translations are not loading for the administration pages in Angular webapps.

##### **Reproduce the error**
Generate an app (i18n enabled) and go to user management

##### **Related issues**

I think it's related to lazy-loading the admin module https://github.com/jhipster/generator-jhipster/pull/7235

##### **Suggest a Fix**
Not sure

##### **JHipster Version(s)**
Master 239acc14495d0069c64a35842065cb09ff6ea6ff
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "newtest",
    "reactive": false,
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Environment and Tools**

<details>
<summary>Environment and Tools</summary>

<pre>
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.3 (Apple Git-98)

node: v8.9.3

npm: 5.6.0

bower: 1.8.2

gulp:
[14:34:49] CLI version 3.9.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 18.03.0-ce-rc1, build c160c73

docker-compose version 1.19.0, build 9e633ef

</pre>
</details>

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Thanks a lot - I confirm this as I have the same issue, but didn't think this was related to the lazy loading!! Good catch!

**Comment by mraible** [comment]
I saw this today with success messages on a microservice app too.

**Comment by jdubois** [comment]
Yes I confirm the issue, and I guess this comes from the changes that @wmarques did - but I have no idea how to solve this! This is quite a blocker issue

**Comment by agaspardcilia** [comment]
@wmarques It's still not working.
