### ISSUE TITLE
Minor DTO toString Method do not generate getId for ManyToOne

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#7312]
##### **Overview of the issue**

Using Dto, getters and setters are generated for ManyToOneAssociations (for Id Fields), but toStringMethod do not display it.

##### **Motivation for or Use Case**

Keeping generation coherent and debugging better.

##### **Reproduce the error**

Generate a Dto with a OneToMany bidirectional Association, and look at the ManyToOne side generated dto

##### **Related issues**

None
##### **Suggest a Fix**

I Can PR on that

##### **JHipster Version(s)**

4.14.1

##### **JHipster configuration**

a JDL:
```
entity ApplicationView {
	id Long
        version Long
	operation String
	timestamp Instant
	applicationId Long required
}
entity Dashboard {
	id Long
        version Long
	operation String
	timestamp Instant
        name String required minlength(2)
	description String
}
relationship OneToMany {
	Dashboard{applicationViews} to ApplicationView{dashboard}
}
dto * with mapstruct
```

##### **Browsers and Operating System**

any
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Feel free to PR.  The field should be in toString

**Comment by deepu105** [comment]
closed via #7395 
@Tcharl please add the fix #xxx keyword in PR to autoclose ticket next time.
@Tcharl btw you have been contributing a lot, would you like to join the core team?

**Comment by Tcharl** [comment]
Hi @deepu105,

I've some more to learn on Github features :-).
I contribute because Jhipster offers me so much! Btw joining the core team would be an honour if the vote is positive.

**Comment by deepu105** [comment]
Ok could you email me your email Id, Full name, twitter handle(if any) to d4udts (at) gmail (dot) com
