### ISSUE TITLE
Syntax error: Unexpected Token } on yarn global add generator-jhipster

### ISSUE THREAD

**Issue by NasrinD** [jhipster/generator-jhipster#7316]
##### **Overview of the issue**

I am trying to install JHipster based on the JHipster Quick Start instruction on this page: [https://www.jhipster.tech/](url)
And when I run this command in my command line: 
`yarn global add [generator-jhipster`]
I get this error:
![image](https://user-images.githubusercontent.com/13658426/37566881-3c804782-2abf-11e8-8369-4b331cc04aab.png)

##### **Reproduce the error**

My system information:
- Windows 7
- Yarn 1.5.1
- Node.js v8.9.3
- git version 2.9.9.windows.1
- Java version 1.8.0_60
- Yeoman 2.0.1

**Comment by gmarziou** [comment]
I have this issue also but only when I use yarn link on generator-jhipster clone, not with released version.
This is related to opencollective using postinstall, one thing you could try is to ignore scripts so that postinstall is not executed:  'yarn global add --ignore-scripts generator-jhipster'

**Comment by ruddell** [comment]
They were able to get it to work by installing with `npm` instead of `yarn`

**Comment by jdubois** [comment]
What is this `opencollective using postinstall`? I have no idea why we would need a postinstall script for OpenCollective in the generator

**Comment by jdubois** [comment]
So I just realized we were using https://www.npmjs.com/package/opencollective in our `package.json`, and I don't understand why - we don't really need those features, and it causes this issue.
I guess this was added by @deepu105 -> Deepu would you be OK to remove this?

**Comment by gmarziou** [comment]
I reported it on dev ML without much interest :( https://groups.google.com/forum/#!topic/jhipster-dev/WOqh5fAo7Yo

**Comment by deepu105** [comment]
I guess it was requested to be added by the OpenCollective team in their
original PR, but yes i'm OK to remove it


Thanks & Regards,
Deepu
