### ISSUE TITLE
yarn install fails

### ISSUE THREAD

**Issue by iObsidian** [jhipster/generator-jhipster#7318]
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/internal-host/-/internal-host-1.2.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "E:\\RealmSpy\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error https://registry.yarnpkg.com/is-my-host-valid/-/is-my-host-valid-1.0.0.tgz: Request failed "404 Not Found"

![image](https://user-images.githubusercontent.com/4276275/37568551-fc6f2ecc-2aac-11e8-8088-933cc2958698.png)

##### **Overview of the issue**

I get this error when trying to deploy to Heroku

##### **Reproduce the error**

Create a JHipster project and use

jhipster heroku

and

mvnw package -Pprod -DskipTests

##### **Related issues**

I get 
```

error Refusing to download the git repo {"hostname":"github.com","protocol":"https:","repository":"https://github.com/heroku/heroku-deploy@latest"} over HTTPS without a commit hash - possible
 !    certificate error?
```

when executing : heroku plugins:install https://github.com/heroku/heroku-deploy

aswell (probably not related)

##### **JHipster configuration**

jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
realm-spy@0.0.0 E:\RealmSpy
`-- generator-jhipster@4.14.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "realmspy"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "RealmSpy",
    "packageName": "realmspy",
    "packageFolder": "realmspy",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "herokuDeployType": "jar",
    "herokuAppName": "realm-spy"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Events (events)
entity Status (status)
entity Termofservice (termofservice)
entity About (about)
entity Privacy (privacy)

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.16.1.windows.1

node: v8.9.4

npm: 5.6.0

gulp:
[13:09:27] CLI version 2.0.1

yeoman: 2.0.1

yarn: 1.5.1

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a96

Congratulations, JHipster execution is complete!

```

**Comment by ruddell** [comment]
Did `yarn cache clean` fix this for you?  From our chat in the Gitter it sounds like you resolved your problems and I can't reproduce it on my end.

**Comment by iObsidian** [comment]
yarn cache clean 

+

yarn update

fixed it! Thanks

**Comment by celine305** [comment]
yarn cache clean
*yarn upgrade
