### ISSUE TITLE
running yarn at gateway frontend did not proxy requests to corresponding backends

### ISSUE THREAD

**Issue by wpcfan** [jhipster/generator-jhipster#7324]
##### **Overview of the issue**

1. use JHipster to generate an uaa, api-gateway and a microservice, all using JHipster Registry
2. in gateway folder, generate client-only code for the microservice
3. in gateway folder, run `yarn start`
4. under Entities menu, select any entity of the microservice
5. watch the chrome developer tool's network tab, you will see errors

it seems the proxy.conf did not work

##### **Motivation for or Use Case**

it seems  a bug and should be fixed.

##### **Reproduce the error**

as above said

##### **Related issues**

none

##### **Suggest a Fix**

none

##### **JHipster Version(s)**

4.14.1

##### **JHipster configuration**

```
homegateway@0.0.0 /Users/wangpeng/workspace/smart/home-gateway
└── generator-jhipster@4.14.1 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.sc.smart",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "homegateway",
    "packageName": "com.sc.smart",
    "packageFolder": "com/sc/smart",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
omitted, as it is confidential

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.16.1

node: v9.4.0

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.5.1

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

Congratulations, JHipster execution is complete!
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

none

##### **Browsers and Operating System**

macOS, Chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
It sounds like you generated an entity on the gateway instead of the microservice, otherwise the microservice path would be in the `entity.service.ts` files.  This would also explain why the microservice path doesn't exist in the proxy config, it should be added automatically when you generate the microservice's entity on the gateway.  How did you generate the entity?

**Comment by wpcfan** [comment]
yes, I use `jhipster import-jdl ~/Downloads/microservice-server.jh` in microservice folder and issue `jhipster import-jdl ~/Downloads/microservice-client.jh` in gateway folder. And in server.jh I specified the `skipClient *` and vice vera

**Comment by ruddell** [comment]
When doing JDL with microservices, you should set the microservice names like [described in the JDL docs](https://www.jhipster.tech/jdl/#microserviceoptions).  Is that present in your JDL?

**Comment by wpcfan** [comment]
I got it, thanks, I am closing this

**Comment by ruddell** [comment]
In the future please fill out the issue template complete, I would have been able to spot this from your entity config or JDL.

**Comment by wpcfan** [comment]
sure, I will follow the template next time
