### ISSUE TITLE
jhipster with keycloak : error 401 not forwarded to login

### ISSUE THREAD

**Issue by warnonphilippe** [jhipster/generator-jhipster#7328]
##### **Overview of the issue**

When a service send a 401 status, redirection to /login doesn't executed.

An interceptor (auth-expired.interceptor.ts) is defined to handle the error, but it doesn't work correctly.

In the if condition, error.json() doesn't contain path, so the condition is false and the redirection is never executed.

~~~ts
if (error.status === 401 && error.text() !== ''
                && error.json().path && !error.json().path.includes('/api/account')) {

            const destination = this.stateStorageService.getDestinationState();
            if (destination !== null) {
                const to = destination.destination;
                const toParams = destination.params;
                if (to.name === 'accessdenied') {
                    this.stateStorageService.storePreviousState(to.name, toParams);
                }
            } else {
                this.stateStorageService.storeUrl('/');
            }
            const loginService: LoginService = this.injector.get(LoginService);
            loginService.login();
        }
        return Observable.throw(error);
~~~

I disabled the check on "error.json().path...", the redirection is called but fails "often", it works sometimes, I didn't found a explanation. Even if I kill all sessions in the keycloak admin console, the browsers redirects to the home page, not the keycloak login form.

##### **Reproduce the error**
To get a 401,
1. Log in
2. Close the session in keycloak
3. try to access a secured service

Or,
1  log in 
2. get a coffee
3. drink slowly
4. try to access a secured service

##### **Suggest a Fix**
The if-condition including error.json().path && !error.json().path.includes('/api/account') should be corrected (or the path set), but even if this test is disabled, it still remain an error while redirecting

##### **JHipster Version(s)**

generator-jhipster@4.13.3

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "be.civadis.efinancegateway"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "efinancegateway",
    "packageName": "be.civadis.efinancegateway",
    "packageFolder": "be/civadis/efinancegateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BonCommande (bon_commande) {
  date Instant,
  numero Integer,
  type String,
  statut String,
  fournisseurCode String,
  articleBudgCode String,
  articleBudgExercice Long
}
entity NatureDepense (nature_depense) {
  type String,
  code String,
  libelle String
}
entity Contexte (contexte) {
  date Instant,
  type String,
  numeroObjet String,
  numeroCSC String
}
entity Action (action) {
  date Instant,
  type String,
  commentaire String,
  user String
}
entity CentreEmetteur (centre_emetteur) {
  code String,
  libelle String,
  adresse String,
  numero String,
  ville String,
  codePostal String,
  numeroIban String
}
entity ListeCollege (liste_college) {
  numero Long,
  date Instant,
  exercice Integer,
  clotureListe Boolean,
  datePassageCollege Instant,
  acterCollege Boolean
}
entity Article (article) {
  code String,
  libelle String,
  quantite Double,
  prixUnitaire Double,
  tva Double,
  total Double,
  commentaire String
}
entity NaturePatrimoine (nature_patrimoine) {
  code String,
  libelle String
}
entity Service (service) {
  code String,
  libelle String,
  actif Boolean
}
entity Fournisseur (fournisseur) {
  nom String,
  prenom String,
  numNat String,
  numTVA String,
  rue String,
  numero String,
  codePostal String,
  ville String,
  pays String,
  rueEnvoi String,
  numeroEnvoi String,
  codePostalEnvoi String,
  villeEnvoi String,
  paysEnvoi String
}
entity ArticleBudg (article_budg) {
  exercice Integer,
  code String,
  nom String,
  type String,
  serviceBudget String,
  millesime Integer,
  isMillesime Boolean,
  assujettissementTVA String,
  budgetInitial Double,
  budgetEnCours Double,
  creditsEnCours Double,
  tousCredits Double,
  montantReserveNonEngage Double,
  montantEngage Double,
  montantImpute Double,
  disponible Double,
  compteNMoins1 Double,
  compteNMoins2 Double,
  compteNMoins3 Double,
  compteNMoins4 Double,
  compteNMoins5 Double,
  montantAdapteNMoins1 Double,
  budgetNMoins1 Double,
  groupeEconomique String,
  codeEconomique String,
  codeFonctionnel String,
  codeProjet String,
  codeEconomiqueComplet String
}
entity Imputation (imputation) {
  numero Integer,
  libelle String,
  tiers String,
  tiersBenef String,
  montantImputation Double,
  montantOp Double,
  dateComptable Instant,
  dateEcheance Instant
}
entity EngagementDefinitif (engagement_definitif) {
  exercice Integer,
  numero Integer,
  libelle String,
  tiers String,
  montantEd Double,
  montantPe Double,
  montantImput Double,
  montantOp Double,
  montantPayeExt Double,
  dateComptable Instant,
  dateEcheance Instant
}
entity OrdrePaiement (ordre_paiement) {
  dateComptable Instant,
  montantPayeOp Double
}
entity ExtraitCompte (extrait_compte) {
  dateExtrait Instant,
  montantPaye Double
}
entity NonEngage (non_engage) {
  numeroCommande Integer,
  fournisseur String,
  montantTVAC Double,
  etatCommande String
}
entity DroitConstate (droit_constate) {
  numero Integer,
  libelle String,
  tiers String,
  tiersBenef String,
  montantAPercevoir Double,
  montantHtvaDef Double,
  montantTvacDef Double,
  montantHtvaNv Double,
  montantTvacNv Double,
  pieceJustificative String
}

relationship OneToMany {
  BonCommande{contexte} to Contexte{bonCommande},
  BonCommande{action} to Action{bonCommande},
  BonCommande{article} to Article{bonCommande},
  ArticleBudg{imputation} to Imputation{articleBudg},
  ArticleBudg{engagementDefinitif} to EngagementDefinitif{articleBudg},
  Imputation{ordrePaiement} to OrdrePaiement{imputation},
  Imputation{extraitCompte} to ExtraitCompte{imputation},
  ArticleBudg{nonEngage} to NonEngage{articleBudg},
  ArticleBudg{droitConstate} to DroitConstate{articleBudg}
}
relationship ManyToOne {
  BonCommande{natureDepense} to NatureDepense,
  BonCommande{centreEmetteur} to CentreEmetteur,
  BonCommande{naturePatrimoine} to NaturePatrimoine,
  BonCommande{service(serviceCode)} to Service,
  BonCommande{fournisseur} to Fournisseur,
  BonCommande{articleBudg} to ArticleBudg,
  CentreEmetteur{service(serviceCode)} to Service,
  EngagementDefinitif{imputation} to Imputation
}
relationship ManyToMany {
  ListeCollege{bonCommande} to BonCommande
}

paginate BonCommande, NatureDepense, Contexte, Action, CentreEmetteur, ListeCollege, Article, NaturePatrimoine, Service, Fournisseur, ArticleBudg, Imputation, EngagementDefinitif, OrdrePaiement, ExtraitCompte, NonEngage, DroitConstate with pagination
service BonCommande with serviceClass
microservice BonCommande, NatureDepense, Contexte, Action, CentreEmetteur, ListeCollege, Article, NaturePatrimoine, Service with ecommandeservice
microservice Fournisseur with stcservice
microservice ArticleBudg, Imputation, EngagementDefinitif, OrdrePaiement, ExtraitCompte, NonEngage, DroitConstate with financeservice

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode)

git version 2.15.0.windows.1

node: v9.1.0

npm: 5.5.1

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a96

##### **Browsers and Operating System**

Windows 10, OS X
Chrome, Firefox
- [V] Checking this box is mandatory (this is just to show you read everything)

**Comment by warnonphilippe** [comment]
I regenerated the a sample project with JHipster 4.14.1 (One Gateway + 2 microservices). I logged in and then killed the session. When I tried to access the service, I received a 401, redirection is called (it was not in 4.13.3), but I'm still redirected to home page, not to keycloak login form, despite there's no session on keycloak.

**Comment by warnonphilippe** [comment]
I fixed the bug in my generated app. I changed in the AuthExpiredInterceptor, it could be a solution to the problem.

First, I replace the if-condition

`if (error.status === 401 && error.text() !== ''
&& error.json().path && !error.json().path.includes('/api/account'))`

by 

`if (error.status === 401 && error.text() !== ''
                    && (!error.json().path || !error.json().path.includes('/api/account')))`

This allows to execute the redirection. 

Then, I put the return statement in the else, it caused a problem when executed with the login() function, I was redirected to the home page, now I'm well redirected to keycloak. 

Below the modified responseIntercept function in AuthExpiredInterceptor 

`
responseIntercept(observable: Observable<Response>): Observable<Response> {
        return <Observable<Response>> observable.catch((error) => {
          if (error.status === 401 && error.text() !== ''
                && (!error.json().path || !error.json().path.includes('/api/account'))) {

                console.log('AuthExpiredInterceptor :: 401 detected')
                const destination = this.stateStorageService.getDestinationState();
                if (destination !== null) {
                    const to = destination.destination;
                    const toParams = destination.params;
                    if (to.name === 'accessdenied') {
                        this.stateStorageService.storePreviousState(to.name, toParams);
                    }
                } else {
                    this.stateStorageService.storeUrl('/');
                }
                const loginService: LoginService = this.injector.get(LoginService);
                loginService.login();

            } else {
                return Observable.throw(error); 
            }
            
        });
    }
`

**Comment by warnonphilippe** [comment]
Closed by error

**Comment by mraible** [comment]
@warnonphilippe Can you please submit a PR with this fix?

**Comment by warnonphilippe** [comment]
@mraible Certainly, probably next week.

**Comment by warnonphilippe** [comment]
I created new projects in 4.14.4, redirection to keycloak is ok. In the code, the return statement causing the error has already been removed.
