### ISSUE TITLE
Prepare migration to Gradle 5

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7336]
On the current master branch (future JHipster 5), we have the following warning when running Gradle:

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings
```

This is because we use annotations processors, which should have their own classpath (as far as I understand!).

We should correct this, so users can run JHipster with Gradle 5.

**Comment by atomfrede** [comment]
I will have a look, but I thought the `apt` plugin si already gradle 5 compatible. Will check if there is more we need to take care of.

**Comment by jdubois** [comment]
Thanks @atomfrede !!

**Comment by atomfrede** [comment]
In deed its something with annotations processors on the classpath. Anyone aware of a dependency not seperating their processors from core jar (looks like Log4j is doing it for example: https://discuss.gradle.org/t/regarding-the-annotation-processors-on-compile-classpath-warning-in-gradle-4-6/26144/9).

**Comment by jdubois** [comment]
Oh I got it @atomfrede - let me do it after lunchtime :-)

**Comment by jdubois** [comment]
Oh sorry my commit doesn't fix the issue, and breaks the build :-(

**Comment by atomfrede** [comment]
Interesting it didn't work in `mapstruct.gradle` :thinking:

**Comment by jdubois** [comment]
In fact it's because it's **also** in the test dependencies...
