### ISSUE TITLE
Remove warning with Angular when running a Webpack build

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7340]
On the current master branch, when generating any application with the "Angular" option, we have 2 times this warning:
```
WARNING in ./node_modules/@angular/core/esm5/core.js
System.import() is deprecated and will be removed soon. Use import() instead.
```
This will appear in the popup every time we compile anything, and that's very annoying. We should correct this before the v5 release.

**Comment by deepu105** [comment]
I comes from a dependency and i'm not sure if we can do anything untill
they fix it


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
And do you know which dependency it is? Maybe we can help them

**Comment by sendilkumarn** [comment]
IIUC, it is coming from the angular lib. So here it is how to fix that 😄
