### ISSUE TITLE
jhiSort don't allow fontawesome selectors inside it

### ISSUE THREAD

**Issue by irbian** [jhipster/generator-jhipster#7344]
##### **Overview of the issue**

jhiSort don´t allow fontawesome selectors inside it without meddling with them

##### **Motivation for or Use Case**

jhiSort needs to use a different mechanism to handle the changes on theire icons

##### **Reproduce the error**

````
<tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="transition.bind(this)">
    <th style="width: 3%">
        <span class="fa fa-box"></span> This is an unrelated icon, a column without sorting
        <p-checkbox> This is a primeng component, with a fa icon inside
    </th>
    <th style="width: 12%" jhiSortBy="code">
        <span jhiTranslate="app.code.label">Code</span>
        <span class="fa fa-sort"></span>
</th>
````

When I click on the code column sort, my fa-box icon disappear, and the p-checkbox icon inside disappear

##### **Suggest a Fix**

The problem is the sortIconSelection https://github.com/jhipster/ng-jhipster/blob/e2fa067a2c0f75502ebe8afd0556cb2260d4d130/src/directive/sort.directive.ts#L63

You could use a input on it, so I can modify it for something more concise

Or maybe use the jhiSortBy son selector?

##### **JHipster Version(s)**

    "ng-jhipster": "0.2.7",

**Comment by deepu105** [comment]
You can override them by passing it in the config in the sharedLibModule declaration in `<AppName>ApplicationSharedLibsModule`
```
NgJhipsterModule.forRoot({
            // set below to true to make alerts look like toast
            alertAsToast: false,
            i18nEnabled: true,
            defaultI18nLang: 'en'
        }),
```
The config accepts https://github.com/jhipster/ng-jhipster/blob/e2fa067a2c0f75502ebe8afd0556cb2260d4d130/src/config.ts

**Comment by deepu105** [comment]
If you can improve this part in anyway PR is welcome
