### ISSUE TITLE
JHipster generator creating Multiple Kafka containers when using with Kubernetes

### ISSUE THREAD

**Issue by pavankjadda** [jhipster/generator-jhipster#7345]
##### **Overview of the issue**

I have a project with two microservices and gateway generated through JHipster. Each service generated with Kafka support. When I run docker-compose up, it creates one kafka container and one zookeeper container for all services, as mentioned JHipster documentation. But when I generate Kubernetes configuration files with Jhipster generator and deploy in AWS or minikube (local machine), I see three containers for Kafka and three containers for Zookeeper. When I send object from one microservice, it's not being received by another microservice as they do not share same kafka server

```
$docker ps
f9e85a2ac169        gateway                             "/bin/sh -c 'echo \"T…"   3 seconds ago       Up Less than a second   5701/udp, 0.0.0.0:8080->8080/tcp       dockercompose_gateway-app_1
e56e4d3360ed        chargecodes                         "/bin/sh -c 'echo \"T…"   4 seconds ago       Up 2 seconds            5701/udp, 8082/tcp                     dockercompose_chargecodes-app_1
30c161ce5ffb        projects                            "/bin/sh -c 'echo \"T…"   4 seconds ago       Up 1 second             5701/udp, 8081/tcp                     dockercompose_projects-app_1
aba8bd5f75ff        jhipster/jhipster-registry:v3.2.4   "/bin/sh -c 'java   …"    44 hours ago        Up 1 second             0.0.0.0:8761->8761/tcp                 dockercompose_jhipster-registry_1
7121db802225        mysql:5.7.20                        "docker-entrypoint.s…"    44 hours ago        Up 2 seconds            3306/tcp                               dockercompose_gateway-mysql_1
dc511e51e0ad        wurstmeister/kafka:1.0.0            "start-kafka.sh"          44 hours ago        Up 1 second                                                    dockercompose_kafka_1
69b1c17bc606        wurstmeister/zookeeper:3.4.6        "/bin/sh -c '/usr/sb…"    44 hours ago        Up 1 second             22/tcp, 2181/tcp, 2888/tcp, 3888/tcp   dockercompose_zookeeper_1
a5d37154abe9        mysql:5.7.20                        "docker-entrypoint.s…"    44 hours ago        Up 2 seconds            3306/tcp                               dockercompose_chargecodes-mysql_1
530c6d243e61        mysql:5.7.20                        "docker-entrypoint.s…"    44 hours ago        Up 2 seconds            3306/tcp                               dockercompose_projects-mysql_1
```
```
pjadda$ kubectl get pods -n duppoc
NAME                                     READY     STATUS    RESTARTS   AGE
chargecodes-7b88d78549-6sd89             1/1       Running   0          12m
chargecodes-kafka-5799d8f99b-vc4v7       1/1       Running   0          1d
chargecodes-mysql-5d8f4c9484-gd5l5       1/1       Running   0          1d
chargecodes-zookeeper-85d59f6759-q8hj8   1/1       Running   0          1d
gateway-574d689f-k6gwc                   1/1       Running   0          12m
gateway-574d689f-ppqk5                   1/1       Running   0          12m
gateway-kafka-78c7f7d7dd-7wvcx           1/1       Running   2          1d
gateway-mysql-5c5d75bbdd-d4w2k           1/1       Running   0          1d
gateway-zookeeper-c755c69c5-x49k5        1/1       Running   0          1d
jhipster-registry-0                      1/1       Running   0          1d
jhipster-registry-1                      1/1       Running   0          1d
projects-55c4d7f85b-ztrs6                1/1       Running   0          12m
projects-kafka-6fd569c66-lh69n           1/1       Running   0          1d
projects-mysql-6d87bf98fd-qxqxf          1/1       Running   0          1d
projects-zookeeper-644dc595d7-n7hqf      1/1       Running   0          1d

```
##### **Motivation for or Use Case**

I think Kubernetes configuration generation causing this.

##### **Reproduce the error**

Clone this [repository](https://github.com/pavankjadda/Kubernetes-SpringCloudStream-Kafka-Docker) and deploy in local machine (use minikube for the cluster) or aws

##### **JHipster Version(s)**

4.14.1

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "appsFolders": [
      "chargecodes",
      "gateway",
      "projects"
    ],
    "directoryPath": "../",
    "serviceDiscoveryType": "eureka",
    "jwtSecretKey": "replaced-by-jhipster-info",
    "dockerRepositoryName": "645729154151.dkr.ecr.us-west-2.amazonaws.com/duppoc",
    "dockerPushCommand": "docker push",
    "kubernetesNamespace": "duppoc",
    "kubernetesServiceType": "LoadBalancer"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.13.1

node: v8.9.4

bower: 1.8.2

gulp:
[20:46:44] CLI version 3.9.1

yarn: 1.5.1

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

##### **Browsers and Operating System**

Chrome 65, macOS HighSierra

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This is probably an error in the Kubernetes sub-generator -> @saturnism @PierreBesson is one of you available for this?

**Comment by PierreBesson** [comment]
This should be easy to fix, currently Kafka/Zookeeper seems to be considered as a database/dependant service so we generate one deployment for each microservice, what should be done instead is something similar to what we do with the registry.
Ideally we should create a side-project to do kubenetes CI testing in minikube with Travis to make sure the k8s subgen stays in a working state.

**Comment by pavankjadda** [comment]
I am able to fix this by following two steps mentioned below
1. Deleted chargescode-kafka.yml and projects-kafka.yml files
2. Modified chargecodes-deployment.yml and projects-deployment.yml files to point them to Gateway Kafka  and zookeeper containers

But it would be nice if Kubernetes Sub generator can do this. I hope we get this future release.

**Comment by PierreBesson** [comment]
@pavakjadda Would you like to try to contribute the fix and make a PR ?

**Comment by pavankjadda** [comment]
@PierreBesson Sure. But, I do not know the process.

**Comment by pavankjadda** [comment]
Sure. Let me know the process.

**Comment by extremenelson** [comment]
There is also a tool from the Kubernetes project (http://kompose.io/) that will take an existing Docker Compose file and generate the Kubernetes resources.

**Comment by PierreBesson** [comment]
@pavankjadda Please have a look at our CONTRIBUTING.md docs.

**Comment by deepu105** [comment]
@pavankjadda @PierreBesson does the PR linked above work for you?

**Comment by pavankjadda** [comment]
@deepu105 Let me check

**Comment by pavankjadda** [comment]
@deepu105 @PierreBesson I tested new pull request just now and  it fixed the issue. But there is another problem. Here is what I did

1. I created folder **kubernetes** and ran `jhipster kubernetes` command
2. It created another folder called **k8s** and left kubernetes folder empty
```
   create ../k8s/chargecodes/chargecodes-deployment.yml
   create ../k8s/chargecodes/chargecodes-service.yml
   create ../k8s/chargecodes/chargecodes-mysql.yml
   create ../k8s/gateway/gateway-deployment.yml
   create ../k8s/gateway/gateway-service.yml
   create ../k8s/gateway/gateway-mysql.yml
   create ../k8s/projects/projects-deployment.yml
   create ../k8s/projects/projects-service.yml
   create ../k8s/projects/projects-mysql.yml
   create ../k8s/README.md
   create ../k8s/namespace.yml
   create ../k8s/messagebroker/kafka.yml
   create ../k8s/registry/jhipster-registry.yml
   create ../k8s/registry/application-configmap.yml
   create ../k8s/kubectl-apply.sh
```
I don't think it's a right idea to create another folder by leaving kubernetes folder empty.

**Comment by PierreBesson** [comment]
Oh I thought this weird issue was fixed. Maybe the PR is based on an older version that still had the bug. Let me have a look next week.

**Comment by srinivasa-vasu** [comment]
@pavankjadda That is intended. No need to create a kubernetes folder. You can run the k8s sub generator from any of the project's folder. Subgenerator will create k8s folder and generate all artifacts within it. Even when you generate the artifacts for multi projects, it will be properly grouped under k8s folder.

**Comment by PierreBesson** [comment]
@srinivasa-vasu Oh I see your point but this is not at all how we intended it to work originally. This goes back to when we were doing the initial design of the docker-compose subgen in 2016 with @jdubois and @wmarques.

The idea is that files are generated in the current directory just like it does for "normal" yeoman generators. This is what we have always done for docker-compose files. The user should already know that and create their k8s/kubernetes folder before invoking `jhipster kubernetes`.

Note that it's written in our docs that you should do it this way, see: `https://www.jhipster.tech/kubernetes/`.

**Comment by PierreBesson** [comment]
For now I've merged @srinivasa-vasu's PR. I will fix the `k8s` folder issue in a future PR. Assuming we all agree on this of course.

**Comment by srinivasa-vasu** [comment]
@PierreBesson just few thoughts - let's say you run the sub-generator at one shot for multiple apps  (app1, app2,..appn) from within a specific project folder (lets say app1), then all the manifests for all apps will be generated under app1/kubernetes/.. (given, kubernetes folder is created under app1). I thought it wld be better to actually create the folder automatically and group it under the root folder irrespective of whether you are running it for single app or multiple apps at one go. In this case it creates a k8s folder automatically at ../app[n]/k8s and aligns all the app manifests. In this case we wouldn't be grouping manifests of other apps within 'a specific app' where you run the subgenerator.

**Comment by PierreBesson** [comment]
I totally see your point but whatever we decide to do we have to be consistent.
Also there are subtle things that happen here, for exemple yeoman generators (including the subgen) will generate a .yo-rc.json file and if you run a subgen in an existing app folder it will append things to the existing .yo-rc. This is why people should not generate apps if there is any .yo-rc in a parent folder as yeoman will use it to remember the selected options.
