### ISSUE TITLE
Dates types are incorrectly regenerated by Liquibase

### ISSUE THREAD

**Issue by iObsidian** [jhipster/generator-jhipster#7346]
##### **Overview of the issue**

When generating a liquibase:diff changelog, the dates are incorrectly set to binary types

##### **Motivation for or Use Case**

"Instants" are stored using the wrong type

##### **Reproduce the error**

How to replicate :

Generate a project using 'yo jhipster' and all the default options

then manually rename the tables (like renaming jhi_authority to rs_authority)

then use 'mvn liquibase:diff' to generate a changelog

inside the changelog you will see

BINARY(255), if you chose the default (h2 in memory db)
TINYBLOB, if you chose mysql

##### **JHipster Version(s)**

Latest version

##### **JHipster configuration**

Pressed 'enter' a couple times after 'yo jhipster'

**Comment by ruddell** [comment]
I reproduced it, but it seems to be a Liquibase issue.  We can't control what Liquibase outputs, what I would expect is that Liquibase maps Instants to timestamps.

Here's a related issue but using Postgresql https://github.com/jhipster/generator-jhipster/issues/6291, based on the comments there you should report this to the Liquibase team.
