### ISSUE TITLE
[oAuth2] Unable to login when user has a specific role rather than default roles (ROLE_USER and ROLE_ADMIN)

### ISSUE THREAD

**Issue by maznag** [jhipster/generator-jhipster#7350]
##### **Overview of the issue**

When I try to connect to JHipster application (Monolith with oAuth2 in my case) using a new user created with a specific role (ROLE_MANAGER for example), the server generate this exception:

<details>
<summary>Unable to find com.mycompany.myapp.domain.Authority with id ROLE_MANAGER'</summary>
<pre>
Exception in com.mycompany.myapp.service.UserService.getUserFromAuthentication() with cause = 'javax.persistence.EntityNotFoundException: Unable to find com.mycompany.myapp.domain.Authority with id ROLE_MANAGER' and exception = 'Unable to find com.mycompany.myapp.domain.Authority with id ROLE_MANAGER; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.mycompany.myapp.domain.Authority with id ROLE_MANAGER'
</pre>
</details>

Tested with keycloak and OKTA

##### **Motivation for or Use Case**

Testing JHipster with oAuth2

##### **Reproduce the error**

1. Generate a simple application Monolith with oAuth2 and default options or using the following .yo-rc.json file.
mkdir test-monolith && cd test-monolith && jhipster
2. Launch keycloak server with docker-compose
docker-compose -f src/main/docker/keycloak.yml up -d
3. Start app
./mvnw
4. Connect to keycloak to add new Role and new User
- Add new role ROLE_MANAGER
http://keycloak:9080/auth/admin/master/console/#/realms/jhipster/roles
- Add new user 'manager' with password 'manager' and assign it ROLE_USER and ROLE_MANAGER roles
http://keycloak:9080/auth/admin/master/console/#/realms/jhipster/users

Note: add '127.0.0.1 keycloak' to your /etc/hosts if not exists

5. Try to login to the generated application

6. Oups ! login doesn't work

##### **Related issues**

Issue #7065

##### **Suggest a Fix**

To fix this bug, we must synchronise also the user authorities (extract from OAuth2Authentication) between IdP and JHipster's local database. To do this, I propose to modify the UserService.syncUserWithIdP as follow:
<details>
<summary>UserService.syncUserWithIdP</summary>
<pre>
private User syncUserWithIdP(Map<String, Object> details, User user) {
        // save authorities in to sync user roles/groups between IdP and JHipster's local database
        List<String> dbAuthorities = getAuthorities();
        List<String> userAuthorities = user.getAuthorities().stream().map(Authority::getName).collect(Collectors.toList());
        for (String authority :userAuthorities) {
            if (!dbAuthorities.contains(authority)) {
                log.debug("Saving authority '{}' in local database ...", authority);
                Authority authoritytoSave = new Authority();
                authoritytoSave.setName(authority);
                authorityRepository.save(authoritytoSave);
            }
        }
        // save account in to sync users between IdP and JHipster's local database
        ...... here the code to save/update user on the local database

        return user;
    }
</pre>
</details>

I'll submit the proposed PR !

##### **JHipster Version(s)**

4.14.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "jhipster",
    "reactive": false,
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.13.1

node: v9.8.0

npm: 5.6.0

bower: 1.8.2

gulp:
[19:25:44] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.5.1

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

**Comment by mraible** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/7351.
