### ISSUE TITLE
Remove Popup from CRUD navigation

### ISSUE THREAD

**Issue by azizkhani** [jhipster/generator-jhipster#7352]
Hi, i am using JHipster and think current navigation make JHipster code complex and management of code is very hard ,one of big problem in business application is change management and upgrade to new feature . 
I suggest change navigation to this way.
When user click on view or edit button .route change and component render in default outlet instead of open in popup .
When user click on delete button .confirm dialog open and after user select ok .entity remove and grid reload;
 This gift show this navigation .

![mar-24-2018 19-36-34](https://user-images.githubusercontent.com/35541507/37865533-811aef38-2f9b-11e8-952c-eb8b1da45dce.gif)

In this navigation .all pop component and service remove and create on resolver for load data in resolver;

Current navigation 

Disadvantage:
1. Complex code 
2. More Code 
3. High cohesion: change propert outside of component using componentInstance in (entity-detail.component.ts and entity-dialog.component.ts) 
4. Popup dose not good for a lot of  input and complex form 

what is opinion of jhipster team about this navigation and advantage and disadvantage of this scenario?

**Comment by gmarziou** [comment]
Personally, I don't see the benefit of modals for editing or viewing details, so I'm in favor of getting rid of it as proposed by @azizkhani

**Comment by deepu105** [comment]
Ya probably its time to get rid of models for edit and create. But for
delete its needed. It will remove a lot of boilerplate for entities that we
added since Angular router doesn't play very nice with dialog models

**Comment by jdubois** [comment]
Oh yes, I've also never liked the modals... but do we have time to refactor this before JHipster 5?

**Comment by gmarziou** [comment]
@deepu105 is it done also with modals in React?

@azizkhani would you like to contribute?

**Comment by azizkhani** [comment]
@gmarziou yes i like that ,but i dont know how will do it .

**Comment by rasoolghafari** [comment]
Dear @azizkhani that's right, it's very annoying design for navigation

**Comment by gzsombor** [comment]
Yes, modals are a bit annoying for the back button, but it's simpler to put the same modal dialog to different pages, and communicate with the "host" page, after the modal is finished.

**Comment by gmarziou** [comment]
@azizkhani you could clone the generator repo, start from master branch and follow [our guide](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup). All work should be in https://github.com/jhipster/generator-jhipster/tree/master/generators/entity-client/templates/angular/src

We will help you.

**Comment by jdubois** [comment]
So I think we all agree about this, but unless there's an easy way to do it, we won't merge this for JHipster v5 - this leaves time to do it well, and @azizkhani if you want to do it, you are most welcome
(and this needs to be done for Angular and React)

**Comment by deepu105** [comment]
For React I'll probably do it as its simple anyway, for angular it would be
a breaking change, at least in terms of URL and stuff, so if doing I would
propose to do it for JH5, anyway, it shouldn't be such a huge change, I
would have done it if I had the time, but if someone is up for it i'll
review and merge it


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Oh if you can do it easily @deepu105 do go on, but we have 40+ opened bugs, and I'd like to make our beta release

**Comment by deepu105** [comment]
Dont hold up beta for this


Thanks & Regards,
Deepu

**Comment by azizkhani** [comment]
@gmarziou @deepu105 @jdubois I'm so happy to be able to do this with your help and I hope to do it well.I was worried about not being familiar with the process and time of doing it. It is good news that you won't merge this for JHipster v5 ,and I have time to do the right thing .

**Comment by azizkhani** [comment]
Is not it better? First, I'll write an example with this navigation and we agree about that and then start applying to generator?

**Comment by gmarziou** [comment]
OK, let's do it this way: start from a simple app, make you changes as a single commit that could be discussed.

**Comment by azizkhani** [comment]
I changed  label navigation and push to https://github.com/azizkhani/jhipster-sample-app,
please check that .

**Comment by gmarziou** [comment]
Great work @azizkhani ! I tested the web app interactively and I like the new navigation.

Minor thing: `yarn test` fails on tslint and karma.

**Comment by deepu105** [comment]
Can you do the same on the template and PR to this repo?

Few things to note,

get rid of all Model related code for the edit/create pages since its not
needed anymore (keep it only for delete)
Make sure karma tests and e2e tests are working

Thanks & Regards,
Deepu

**Comment by azizkhani** [comment]
Yes I can do it ,But need help

**Comment by deepu105** [comment]
What kind of help do you need?

Thanks & Regards,
Deepu

**Comment by azizkhani** [comment]
Answer to some question during do that.

**Comment by deepu105** [comment]
@azizkhani ofcourse, you can ping me if you have any questions. I will also review your PR

**Comment by azizkhani** [comment]
@deepu105 I change that for entity and push in this repository.
https://github.com/azizkhani/generator-jhipster
will i send a PR or you can see my change before that?

**Comment by deepu105** [comment]
Please send a PR

Thanks & Regards,
Deepu

**Comment by gmarziou** [comment]
@azizkhani a PR will trigger our Travis builds, so it is very useful

**Comment by azizkhani** [comment]
@deepu105 @gmarziou I sent a PR

**Comment by gmarziou** [comment]
I saw it  :)
One thing you could do in your PR comment is to add `Fix #7352` on a line so that your PR is linked to this issue and also once merged it will close it.

**Comment by azizkhani** [comment]
@gmarziou how can i test travis like test in local instead of push and see travis?

**Comment by gmarziou** [comment]
@azizkhani see https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#local-travis-build

**Comment by gmarziou** [comment]
Not sure yet but the upgrade generator could be in trouble with the renaming of the dialog components. I'll try on my project as soon as a beta is released.

**Comment by hejerdj** [comment]
Hi all, i'am a beginner in jhipster. I modify the files like @azizkhani  but when i run my app it shows me an error and i don't understand what the source of the problem. 

BasicinfoDialogComponent.html:1 ERROR TypeError: Cannot read property 'id' of undefined
    at Object.eval [as updateDirectives] (BasicinfoDialogComponent.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js?593e:14640)
    at checkAndUpdateView (core.js?593e:13787)
    at callViewAction (core.js?593e:14138)
    at execComponentViewsAction (core.js?593e:14070)
    at checkAndUpdateView (core.js?593e:13793)
    at callViewAction (core.js?593e:14138)
    at execEmbeddedViewsAction (core.js?593e:14096)
    at checkAndUpdateView (core.js?593e:13788)
    at callViewAction (core.js?593e:14138) 

Can someone help me?

**Comment by Tri-vikram** [comment]
can u send me the link of global address info ... it would be helpfull to me
