### ISSUE TITLE
Liquibase and H2 database : misconfiguration ?

### ISSUE THREAD

**Issue by GuiF007** [jhipster/generator-jhipster#7377]
##### **Overview of the issue**
With jHipster v4.14.1, I created a fresh new app, with H2 file database in dev environment.
I used `./mvnw liquibase:diff` with the just created application-dev.yml and pom.xml.

It occurs the liquibase created me a file saying I have to create the whole base, instead of "nothing to be created/modified" file...

I don't have the problem with MySQL in dev.

##### **Motivation for or Use Case**

Liquibase and H2 should work properly right ?

##### **Reproduce the error**

With jHipster v4.14.1, just create a new app with H2 in dev and try to ask Liquibase a diff file...

##### **Suggest a Fix**

It seems there is a problem with MV_STORE parameter. Spring-Boot creates the file at startup in databasename.h2.db while Liquibase is expecting (and creating) an databasename.mv.db file.

I added the parameter `;MV_STORE=FALSE` in pom.xml in the liquibase plugin configuration and it works as it should expect (according to me at least...)

##### **JHipster Version(s)**
4.14.1

##### **JHipster configuration**

> {
>   "generator-jhipster": {
>     "promptValues": {
>       "packageName": "com.mycompany.myapp",
>       "nativeLanguage": "fr"
>     },
>     "jhipsterVersion": "4.14.1",
>     "baseName": "test2",
>     "packageName": "com.mycompany.myapp",
>     "packageFolder": "com/mycompany/myapp",
>     "serverPort": "8080",
>     "authenticationType": "jwt",
>     "cacheProvider": "ehcache",
>     "enableHibernateCache": true,
>     "websocket": false,
>     "databaseType": "sql",
>     "devDatabaseType": "h2Disk",
>     "prodDatabaseType": "mysql",
>     "searchEngine": false,
>     "messageBroker": false,
>     "serviceDiscoveryType": false,
>     "buildTool": "maven",
>     "enableSocialSignIn": false,
>     "enableSwaggerCodegen": false,
>     "jwtSecretKey": "738e0179ac72afdcced0567136922b1aa850b20a",
>     "clientFramework": "angularX",
>     "useSass": false,
>     "clientPackageManager": "yarn",
>     "applicationType": "monolith",
>     "testFrameworks": [],
>     "jhiPrefix": "jhi",
>     "enableTranslation": true,
>     "nativeLanguage": "fr",
>     "languages": [
>       "fr"
>     ]
>   }
> }
> 

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
H2 doesn't have an opened port so liquibase:diff can't work with H2.
You need to use a "real" database for this, it should be in the
documentation.

**Comment by pascalgrimaud** [comment]
The documentation is here:
https://www.jhipster.tech/development/

> If you are running H2 with disk-based persistence, this workflow is not yet working perfectly, but you can start trying to use it (and send us feedback!).

**Comment by GuiF007** [comment]
@pascalgrimaud Mea culpa, I did not read this 👎  

I managed to make it works with the attribute I added in the pom.xml... Not really tons of tests, but adding an attribute works well with this parameter. But I take note it's not really supported and I think I will gave up the use of H2 with liquibase...

**Comment by pascalgrimaud** [comment]
Yes, H2 is for demo or very quick start.
If you decide to begin real development, it's always better to use a real database.

**Comment by jdubois** [comment]
Well if you know how to make it work you can do a PR on this.
But indeed this is used by "advanced users" and usually those people use a real database. We should explain this better, maybe we should set "starter level" and "advanced level" tips in the doc.

**Comment by GuiF007** [comment]
> Well if you know how to make it work you can do a PR on this.

I will try to make some tests with Liquibase and H2 database with this parameter and then I can submit a PR to make sure everything works better.
