### ISSUE TITLE
Angular: user management page bugged when trying to CRUD

### ISSUE THREAD

**Issue by chrisdns** [jhipster/generator-jhipster#7383]
##### **Overview of the issue**
When we try to interact with the user management page by CRUDing, the page is bugged and we can't no longer interact with it until a page refresh.

##### **Reproduce the error**

- Generate an angular application
- Launch it
- Log in as an administrator
- Go to User Management page
- Interact with the page by clicking the buttons
- Try to interact once again with the page
- Notice the bug

##### **Related issues**
It might be related to the lazy-loading admin module

We get this message on the web browser console :
`Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'user-management'`

##### **JHipster Version(s)**
The latest master 

##### **JHipster configuration

> {
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "anguladminbug",
    "reactive": false,
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "1abaae359e479d1e12a2562031ac839549659724",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Its a known issue after the lazy loading change. Was planning to work on it, but its quite tricky

**Comment by deepu105** [comment]
@wmarques @sendilkumarn does any of you have time to look at this, I'm tied up with finishing React stuff

**Comment by deepu105** [comment]
@chrisdns you are welcome to try as well

**Comment by deepu105** [comment]
@jdubois may be we should revert lazy loading until we find a solution for this

**Comment by jdubois** [comment]
Yes but I have no idea what to revert as there has been quite a lot of changes here.

**Comment by vishal423** [comment]
@deepu105, I think after your change 'Administration' menu is broken. I can see below console errors when try to navigate to any submenu under Administration.

```
platform-browser.js?393a:380 Router Event: NavigationError
platform-browser.js?393a:367 NavigationError(id: 2, url: '/admin/gateway', error: Error: Cannot match any routes. URL Segment: 'admin/gateway')
platform-browser.js?393a:367 NavigationError {id: 2, url: "/admin/gateway", error: Error: Cannot match any routes. URL Segment: 'admin/gateway'
    at ApplyRedirects.noMatchError (web…}
core.js?df1b:1448 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'admin/gateway'
Error: Cannot match any routes. URL Segment: 'admin/gateway'
    at ApplyRedirects.noMatchError (router.js?9a13:1760)
    at CatchSubscriber.eval [as selector] (router.js?9a13:1725)
```

**Comment by jdubois** [comment]
@vishal423 can you give your .yo-rc.json ?

**Comment by vishal423** [comment]
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "gtw3",
    "reactive": false,
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "e983d829bed048285ce0a8864c8c6cbf4fbbc10d",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

**Comment by deepu105** [comment]
Thats strange, it works fine for me, but i'm on a monolith. You are on a
gateway, but that shouldnt matter in theory

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
is only gateway page broken?  In admin.route.ts can you change from `path:
'admin',` to `path: '',` and try?

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
I confirm the issue with admin page for Gateway, and your suggestion is good @deepu105 : `path: '',`

**Comment by deepu105** [comment]
@pascalgrimaud so it happens only for gateway right but not for other pages?

**Comment by vishal423** [comment]
I tried with monolithic as well and that also resulted into same issue. So, it's not something related to gateway application.

Above suggestion fixes the issue, however, that would cause similar issue delete user dialog

**Comment by vishal423** [comment]
@deepu105 , issue is not limited to just gateway submenu, but, also submenu under Administration

**Comment by deepu105** [comment]
But wait i'm running monolith from master and I dont have the issue

**Comment by deepu105** [comment]
For me its seems to work fine with or without `path:
'admin'` so i'm removing it.  can you try master

**Comment by vishal423** [comment]
With lazy loaded admin module, we add 'admin' to route hierarchy and again in 'admin.route.ts' we add 'admin' as child. So, in order to access child route, we should provide path like 'admin/admin/gateway' or 'admin/admin/user-management' etc. This should fix current issue, however, I prefer to remove intermediate 'admin' from route hierarchy. With either fix, delete user dialog needs to be fixed

**Comment by jdubois** [comment]
@vishal423 it's not lazy loaded any more since yesterday, when did you sync with the master branch?

**Comment by deepu105** [comment]
@jdubois its still lazy loaded but I fixed the issues.

**Comment by deepu105** [comment]
@vishal423 I dont see any issues in current master

**Comment by deepu105** [comment]
here is the config i'm testing

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jhipsterbook.demo",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "jhtemp",
    "reactive": false,
    "packageName": "com.jhipsterbook.demo",
    "packageFolder": "com/jhipsterbook/demo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly"
    ],
    "enableSocialSignIn": false
  }
}
```

**Comment by deepu105** [comment]
@pascalgrimaud can you try latest master plz?

**Comment by vishal423** [comment]
@deepu105, With either fix (remove intermediate 'admin' or update navbar routerLink), delete user dialog needs to be fixed.

With your current change to remove intermediate 'admin', I see below error when try to delete user:

core.js?df1b:1448 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'user-management/system/delete'
Error: Cannot match any routes. URL Segment: 'user-management/system/delete'
    at ApplyRedirects.noMatchError (router.js?9a13:1760)
    at CatchSubscriber.eval [as selector] (router.js?9a13:1725)
    at CatchSubscriber.error (catchError.js?e534:105)

**Comment by deepu105** [comment]
![image](https://user-images.githubusercontent.com/1107223/38238139-41868130-3729-11e8-9d5d-ba182470b4af.png)

**Comment by vishal423** [comment]
@deepu105 , I haven't done that recently. However, with my current setup, I don't feel it's required as I always get latest code :)

**Comment by deepu105** [comment]
yes but if you generate a project it will use the local version of generator unless you do the link, else you need to delete node_modules before each regeneration or always create fresh projects

**Comment by vishal423** [comment]
I always create fresh project :)
