### ISSUE TITLE
Bug with date in generated services

### ISSUE THREAD

**Issue by piyiotisk** [jhipster/generator-jhipster#7396]
##### **Overview of the issue**

In generated services there is a method like the one below:

~~~ts
   /**
     * Convert a returned JSON object to Repair.
     */
    private convertItemFromServer(repair: Repair): Repair {
        const copy: Repair = Object.assign({}, repair);
        copy.repairDate = this.dateUtils
            .convertLocalDateFromServer(repair.repairDate);
        return copy;
    }
~~~

However the resulting copy object has a wrong date. The date is one day earlier than the correct date. 

##### **Motivation for or Use Case**

N/A

##### **Reproduce the error**
Just create a new jHipster project and debug to see the error.

##### **Suggest a Fix**

I fixed it by creating a new Date object a shown below.

~~~ts
   /**
     * Convert a returned JSON object to Repair.
     */
    private convertItemFromServer(repair: Repair): Repair {
        const copy: Repair = Object.assign({}, repair);
        // copy.repairDate = this.dateUtils.convertLocalDateFromServer(repair.repairDate);
        const date: Date = new Date(repair.repairDate);
        copy.repairDate = date;
        return copy;
    }
~~~

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
rightclima@0.0.0 /Users/pigiotisk/Workspace/rightclima
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.rightclima.crm",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "rightclima",
    "packageName": "com.rightclima.crm",
    "packageFolder": "com/rightclima/crm",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "el"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * The Customer entity.
 */
entity Customer (customer) {
  name String,
  email String,
  phoneNumber String,
  streetAddress String,
  contacts TextBlob
}
/**
 * The Repair entity.
 */
entity Repair (repair) {
  repairDate LocalDate,
  recurring Boolean,
  occurrence Integer,
  repairCategory RepairCategory,
  total BigDecimal,
  amountPaid BigDecimal,
  amountRemaining BigDecimal,
  paid Boolean,
  description TextBlob,
  completed Boolean
}
/**
 * The Work entity.
 */
entity Work (work) {
  workDate LocalDate,
  total BigDecimal,
  amountPaid BigDecimal,
  amountRemaining BigDecimal,
  paid Boolean,
  description TextBlob
}
/**
 * The RepairPayment entity.
 */
entity RepairPayment (repair_payment) {
  paymentDate LocalDate,
  amountPaid BigDecimal,
  description TextBlob
}
/**
 * The WorkPayment entity.
 */
entity WorkPayment (work_payment) {
  paymentDate LocalDate,
  amountPaid BigDecimal,
  description TextBlob
}

enum RepairCategory {
  AIR_CONDITION,
  HEATING,
  FILTERS,
  PLUMBING
}

relationship OneToMany {
  Customer{repair} to Repair{customer},
  Customer{work} to Work{customer},
  Repair{payment} to RepairPayment{repair},
  Work{payment} to WorkPayment{work}
}

paginate Customer, Repair, Work, RepairPayment, WorkPayment with pagination
service Customer, Repair, Work, RepairPayment, WorkPayment with serviceImpl

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.15.1 (Apple Git-101)

node: v9.7.1

npm: 5.6.0

yarn: 1.5.1

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.14.0, build c7bdf9e

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

MacOS X 
Firefox latest

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I couldn't reproduce with the Repair entity in the example (using v4.14.1 code), it seems to work correctly but may have something to do with a timezone setting.  I also tested with the new Moment code which replaced the referenced code and couldn't reproduce.

**Comment by Tcharl** [comment]
Date in jdl generates Moment attribute type in the angular front: I don't think that creating a Date could work

**Comment by deepu105** [comment]
@piyiotisk could you please check with JHipster v5 beta and see if you can reproduce the issue?

**Comment by deepu105** [comment]
closing this as there is no response form @piyiotisk and we couldn't reproduce it. @piyiotisk if you are able to reproduce it let us know and we will re open this

**Comment by piyiotisk** [comment]
Hello guys, sorry for the delay. I will try to reproduce it and report back. Thanks!
