### ISSUE TITLE
JhiMainComponent error while starting project in Prod mode

### ISSUE THREAD

**Issue by OzturkArda** [jhipster/generator-jhipster#7399]
##### **Overview of the issue**

When I start project in prod mod (./mvnw -Pprod) I get this error message;

ERROR in : Type JhiMainComponent in C:/Projects/companyName/ProjectFolder/projectName/src/main/webapp/app/layouts/main/main.component.ts is part of the declarations of 2 modules: ProjectNameAppModule in C:/Projects/companyName/ProjectFolder/projectName/src/main/webapp/app/app.module.ts and ProjectNameMainModule in C:/Projects/companyName/ProjectFolder/projectName/src/main/webapp/app/layouts/main/main.module.ts! Please consider moving JhiMainComponent in C:/Projects/companyName/ProjectFolder/projectName/src/main/webapp/app/layouts/main/main.component.ts to a higher module that imports ProjectNameA
ppModule in C:/Projects/companyName/ProjectFolder/projectName/src/main/webapp/app/app.module.ts and ProjectNameMainModule in C:/Projects/companyName/ProjectFolder/projectName/src/main/webapp/app/layouts/main/main.module.ts. You can also create a new NgModule that exports and includes JhiMainComponent in C:/Projects/companyName/ProjectFolder/projectName/src/main/webapp/app/layouts/main/main.component.ts then import that NgModule in ProjectNameAppModule in C:/Projects/companyName/ProjectFolder/projectName/src/main/webapp/app/app.module.ts and ProjectNameMainModule in C:/Projects/companyName/ProjectFolder/projectName/src/mai
n/webapp/app/layouts/main/main.module.ts.

##### **Motivation for or Use Case**

To start project in Production mode. 

##### **Reproduce the error**

run './mvnw -Pprod'

##### **JHipster Version(s)**

4.14.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "tr.com.***.***",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "****",
    "packageName": "tr.com.***.***",
    "packageFolder": "tr/com/***/***",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "tr"
    ]
  }
}

git version 2.16.1.windows.2

node: v9.5.0

npm: 5.6.0

gulp: CLI version 2.0.1

yeoman: 2.0.1

yarn: 1.3.2

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.20.1, build 5d8c71b2

**Comment by deepu105** [comment]
We do not generate such a main module 'src/main/webapp/app/layouts/main/main.module.ts'  did you add this yourself? I couldnt reproduce this as we dont generate the component you mention

**Comment by OzturkArda** [comment]
Hi, 

Thanks for the fast reply. I double checked, this file is definitely auto-genrated. You can confirm by generating the project using the given jhipster configuration in the issue definition. 

BR.

**Comment by deepu105** [comment]
That is not possible, we do not have such a template, see below, try a clean project from scratch
![image](https://user-images.githubusercontent.com/1107223/38233774-104d2dd8-371c-11e8-87ed-4495f71c33bd.png)

**Comment by OzturkArda** [comment]
Hi,

I just created the project from '.yo-rc.json' and the file was there. Could you please try the same?

Thanks,

BR.

![image](https://user-images.githubusercontent.com/15789442/38233921-e51c8bfa-3724-11e8-8972-84cf12e3e4ee.png)

**Comment by deepu105** [comment]
@OzturkArda what are you talking about? there is no file named `main.module.ts` in your screenshot? we do not generate `main.module.ts` your issue comes from that file, please create a project from scratch and you will see there is no issue here.

**Comment by OzturkArda** [comment]
Yes, sory for the confusion.. My mistake. I'll try to clarify the source of the issue on our side. 
We can close the issue as it is now. Thank you for your time.
