### ISSUE TITLE
mixed content warning with HTTPS+nginx

### ISSUE THREAD

**Issue by epsilonhalbe** [jhipster/generator-jhipster#7405]
##### **Overview of the issue**

Serving a JHipster Gateway with Nginx - yields a mixed content warning (when not logged in).
about the route `/login`.

##### **Motivation for or Use Case**

I am serving my (jhipster)microservice application with nginx as reverse proxy, which also provides TLS-termination.

##### **Reproduce the error**
```
mkdir {gateway,docker-compose} && mkdir docker-compose/{certs,conf}
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout docker-compose/certs/nginx.key -out docker-compose/certs/nginx.crt
wget https://github.com/jhipster/generator-jhipster/files/1872584/gateway.yo-rc.json.txt -O gateway/.yo-rc.json
wget https://github.com/jhipster/generator-jhipster/files/1872572/docker-compose.yo-rc.json.txt -O docker-compose/.yo-rc.json
wget https://github.com/jhipster/generator-jhipster/files/1872568/nginx.conf.txt docker-compose/conf/nginx.conf
wget https://github.com/jhipster/generator-jhipster/files/1872604/nginx.yml.txt -O docker-compose/nginx.yml
cd gateway && jhipster && ./mvnw verify -DskipTests -Pprod dockerfile:build   # -DskipTests to make the build faster
cd ../docker-compose && jhipster
```
generate a gateway app with [`gateway.yo-rc.json`](https://github.com/jhipster/generator-jhipster/files/1872584/gateway.yo-rc.json.txt) and a docker-compose setup with [`docker-compose.yo-rc.json`](https://github.com/jhipster/generator-jhipster/files/1872572/docker-compose.yo-rc.json.txt) and add the following to your `docker-compose.yml`

```
    nginx:
        depends_on:
            - gateway-app
            - jhipster-registry
        extends:
            file: nginx.yml
            service: nginx
```
Replace the `<your-docker-host-IP>` in [docker-compose/conf/nginx.conf](https://github.com/jhipster/generator-jhipster/files/1872568/nginx.conf.txt) with your local IP address.

and include the [`nginx.yml`](https://github.com/jhipster/generator-jhipster/files/1872604/nginx.yml.txt)
then start the application with
```
docker-compose up -d
```
open a firefox or chrome at `localhost` which should forward you to https://localhost/#/ (accept the security warning for the self signed certificate) and opening developer tools you get a mixed content warning (n.b. if you accept to load (insecurely) http content you will a CORS warning, which is unrelated to this issue (I believe)).

I tried to find the cause of this, debugged the front end with XHR-Breakpoints in Chrome (to no avail).
And looked at the backend route `/api/account` which seems to trigger the xhr to `/login`, but could not fix this issue.

when logging in via the login button (which calls `https://localhost/login` - without any problems) - the mixed content warning disappears, but reappears when logging out

##### **Related issues**

none that I know of

##### **Suggest a Fix**

Unfortunately not

##### **JHipster Version(s)**
```
jhipster --version
Using JHipster version installed globally
4.14.1
```
##### **JHipster configuration**
 - see above for the `yo-rc.json`-files

##### **Environment and Tools**
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
git version 2.7.4
node: v8.11.1
npm: 5.6.0
yeoman: 2.0.1
yarn: 1.5.1
Docker version 18.03.0-ce, build 0520e24
docker-compose version 1.18.0, build 8dd22a9
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no entities present

##### **Browsers and Operating System**

OS: Linux Mint/Debian
Browsers used: Firefox (59), Chrome(64)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by epsilonhalbe** [comment]
note -  I am a beginner at jhipster/nginx so if I might have not thought of something obvious - that is totally my fault! ;-) - Thanks by the way for providing the framework and keep it clean/up to date.

**Comment by jdubois** [comment]
Can you post your `.yo-rc.json` here?

**Comment by epsilonhalbe** [comment]
@jdubois sure

gateway: `.yo-rc.json`
-
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "mixed.content"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "gateway",
    "packageName": "mixed.content",
    "packageFolder": "mixed/content",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
docker-compose: .yo-rc.json
-
```
{
  "generator-jhipster": {
    "appsFolders": [
      "gateway"
    ],
    "directoryPath": "../",
    "gatewayType": "zuul",
    "monitoring": "no",
    "serviceDiscoveryType": "eureka",
    "adminPassword": "admin",
    "jwtSecretKey": "10a3f687c8a12a1717fe7ebd911035bb6cf6c3cb"
  }
}
```

**Comment by epsilonhalbe** [comment]
A colleague helped me:

set `server.use-forward-headers: true` in the `application.yml` fixed the call to http and with it the mixed content warning,

I think this could be included in the documentation for running jhipster behind a reverse proxy.

**Comment by ruddell** [comment]
This is [documented in Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html#howto-use-tomcat-behind-a-proxy-server), I don't think we have a page dedicated to configuring a reverse proxy and we can't copy all of Spring Boot's docs onto our site.

This issue may affect our Traefik integration (when using OIDC, it uses 302 redirects) so it could be documented there.  I haven't tested the Traefik+OIDC combo
