### ISSUE TITLE
Generator does not prompt authentication question if "Yes" is answered to t he registry question

### ISSUE THREAD

**Issue by ofaklintrafo** [jhipster/generator-jhipster#7418]
##### **Overview of the issue**

The JHipster generator version 4.14.1 on windows does not prompt for authentication method if 
I choose to configure the JHipster Registry.

##### **Reproduce the error**

* Navigate to empty folder|
* Start JHipster generator

Below is the sequence if I choose Yes to the registry question. Note that it skips the authentication question.

    ? Do you want to use the JHipster Registry to configure, monitor and scale your application? Yes
    ? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)

This is the sequence of questions if I choose "No" to the registry question.

    ? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
    ? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
    ? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)

##### **JHipster Version(s)**

4.14.4

##### **Browsers and Operating System**

Windows 10

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes that's because for a monolith the registry only works with JWT, so there's no need to ask for the question.
I need to check if that's still true with JHipster 5, but for JHipster 4 that's no a bug, it's a feature :-)

**Comment by gmarziou** [comment]
I confirm the issue, there's something in conditions for monolith+eureka in conditions in https://github.com/jhipster/generator-jhipster/blob/v4.x_maintenance/generators/server/prompts.js
