### ISSUE TITLE
Add QueryDsl 

### ISSUE THREAD

**Issue by thiagonuic** [jhipster/generator-jhipster#742]
I think it would be nice to have query dsl already bundled in jhipster. 

On the maven side, you just need to add the dependency and plugin to generate the code. 

On the repository side, make it inherit from QueryDslPredicateExecutor.

If you guys agree I can make a PR this weekend.

**Comment by omrzljak** [comment]
QueyDSL is also easy to use with Gradle. I made small "how to" [here](http://osmanmrzljak.blogspot.nl/2015/05/add-querydsl-to-jhipster-spring-data.html).

Let me know if you want to have it somewhere on JHipster wiki or .... just copy and paste my text ;-)

**Comment by jdubois** [comment]
@omrzljak we are preparing a "tips" section, for contributors (the Github wiki isn't good enough)
You need to add it to the "tip" directory, like in this PR: https://github.com/jhipster/jhipster.github.io/pull/54

Feel free to add it, it's made for it!
