### ISSUE TITLE
Settings Page doesnt include formfield to set an image for the user.

### ISSUE THREAD

**Issue by kseyhan** [jhipster/generator-jhipster#7435]
##### **Overview of the issue**

Settings Page doesnt include formfield to set an image for the user.

##### **Motivation for or Use Case**

There is plenty of functionality included to set and show an image in the navbar, but the formfield to set this image is missing in the user settings page and in the create account dialog so that its just possible to set this image by some custom http requests which isnt the intended way i would say.

##### **Suggest a Fix**

Either that functionality should get removed or some fields included to set the image .

##### **JHipster Version(s)**

5.0.0-beta.0

##### **JHipster Version(s)**

```
hipsterblog@0.0.0 /home/ks_private_dev/eclipse-new/hipsterblog
└── generator-jhipster@5.0.0-beta.0 

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.codecut"
    },
    "jhipsterVersion": "5.0.0-beta.0",
    "baseName": "hipsterblog",
    "reactive": true,
    "packageName": "de.codecut",
    "packageFolder": "de/codecut",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog (blog) {
  name String required minlength(3),
  handle String required minlength(2)
}
entity Entry (entry) {
  title String required,
  content TextBlob required,
  date ZonedDateTime required
}
entity Tag (tag) {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User,
  Entry{blog(name)} to Blog
}
relationship ManyToMany {
  Entry{tag(name)} to Tag{entry}
}

paginate Entry, Tag with infinite-scroll

</pre>
</details>

**Comment by ruddell** [comment]
This was [originally added for social login](https://github.com/jhipster/generator-jhipster/pull/4772) which was recently removed.  So we can either remove it or add a field to the settings page that accepts a URL for the profile image

**Comment by deepu105** [comment]
@kseyhan are you working on this? else we can close this

**Comment by kseyhan** [comment]
Well, then i suggest removing that junk out. I'll take a look into it.

**Comment by jdubois** [comment]
Nobody is working on this so I'm closing it.

Indeed that would be a good feature, but implementing this for both Angular and React is a lot of work and maintenance.
