### ISSUE TITLE
@JsonIgnore annotation in the class AbstractAuditingEntity gets ignored.

### ISSUE THREAD

**Issue by kseyhan** [jhipster/generator-jhipster#7436]
##### **Overview of the issue**

@JsonIgnore annotation in the class AbstractAuditingEntity gets ignored.

##### **Reproduce the error**

Open the settings page and check the results of the json response to the "account" endpoint which looks like this:

~~~json
{
  "id" : 4,
  "login" : "user",
  "firstName" : "User",
  "lastName" : "User",
  "email" : "user@localhost1234",
  "imageUrl" : "|",
  "activated" : true,
  "langKey" : "en",
  "createdBy" : "system",
  "createdDate" : "2018-04-07T02:42:44.316Z",
  "lastModifiedBy" : "user",
  "lastModifiedDate" : "2018-04-08T07:09:05.280Z",
  "authorities" : [ "ROLE_USER" ]
}
~~~

expected behaviour is that the createdBy, createdDate, lastModifiedBy and lastModifiedDate dont show up in the response.

Addition:
While writing this bug request i just recognised that the @JsonIgnore annotation for the authorities field in the User.class gets ignored aswell.

##### **JHipster Version(s)**

5.0.0-beta.0

##### **JHipster Version(s)**

```
hipsterblog@0.0.0 /home/ks_private_dev/eclipse-new/hipsterblog
└── generator-jhipster@5.0.0-beta.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.codecut"
    },
    "jhipsterVersion": "5.0.0-beta.0",
    "baseName": "hipsterblog",
    "reactive": true,
    "packageName": "de.codecut",
    "packageFolder": "de/codecut",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog (blog) {
  name String required minlength(3),
  handle String required minlength(2)
}
entity Entry (entry) {
  title String required,
  content TextBlob required,
  date ZonedDateTime required
}
entity Tag (tag) {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User,
  Entry{blog(name)} to Blog
}
relationship ManyToMany {
  Entry{tag(name)} to Tag{entry}
}

paginate Entry, Tag with infinite-scroll

</pre>
</details>

**Comment by gmarziou** [comment]
I don't know why it  is not working but I think we should rather not using `@JsonIgnore` on this abstract entity because there are some cases where you want to display these fields in UI. So it could be better to use  `@JsonIgnoreProperties` on sub classes to give more control to the app developer.

**Comment by kseyhan** [comment]
If you ask me i would ignore it directly in this class. I dont see a reason why you should need those fields in the frontend at all.

**Comment by gmarziou** [comment]
For instance because admin users need them. Even for the blog example, it's very common to show when the post was created and when it was last updated.

**Comment by kseyhan** [comment]
ok well thats a usecase for the date fields what about the by fields?
p.s. i found the reason why it doesnt work as intended now. It happens because there is this dto mapping happening which doesnt cares about the annotations at all.

**Comment by gmarziou** [comment]
There are many other use cases for he other fields too.

Anyway,there's no DTO in your JDL.

If you really use DTOs, then it's normal that the properties are not ignored because in this case entities are not serialized (Jackson does not see them at all).

**Comment by kseyhan** [comment]
The UserDTO gets generated by default whatever option you choose.

**Comment by gmarziou** [comment]
Oh OK so this has nothing to do with AbstractAuditEntity at all. `@JsonIgnore` should be set on UserDTO if this is what you want but I don't see any issue in JHipster.

**Comment by gmarziou** [comment]
In fact, I don't think there's a JHipster issue.
Those fields are displayed in the UI, so they must not be ignored.

**Comment by buseodaci** [comment]
> I don't know why it is not working but I think we should rather not using `@JsonIgnore` on this abstract entity because there are some cases where you want to display these fields in UI. So it could be better to use `@JsonIgnoreProperties` on sub classes to give more control to the app developer.

This answer helped me a lot :)
