### ISSUE TITLE
Sonar quality gate

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7442]
Seems we failed Sonal quality gate again, I don't know what went wrong, may be due to the coverage on new code

**Comment by deepu105** [comment]
@jdubois @pascalgrimaud are you guys aware of this?

**Comment by pascalgrimaud** [comment]
@deepu105 : yes, I know, not sure how we can fix it

**Comment by jdubois** [comment]
Well, we need to do more tests, that's how we can fix it :-)

**Comment by jdubois** [comment]
Closing as nobody works on this - we should always have Sonar in mind, and only create a specific ticket if someone is going to work on this specifically. Unfortunately nobody does :-(

**Comment by pascalgrimaud** [comment]
FYI, it's back to `passed` and we didn't do anything.

**Comment by deepu105** [comment]
Thats strange
