### ISSUE TITLE
Creating monolithic application with JHipster Registry

### ISSUE THREAD

**Issue by shadowrider-pl** [jhipster/generator-jhipster#7445]
##### **Overview of the issue**

From https://www.jhipster.tech/creating-an-app/:
The JHipster Registry is an Open Source tool used to manage your application at runtime.

It is required when using a microservices architecture (this is why this question is only asked when generating a monolith).

But when monolithic application is choosen, this question appears anyway. 

##### **Motivation for or Use Case**

Choosing 'yes' generating problems in prod profile.

##### **Reproduce the error**

Simple jhipster command -> Monolithic application

##### **JHipster Version(s)**

4.14.2

##### **JHipster configuration**

not generated yet

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

not generated yet

##### **Browsers and Operating System**

Ubuntu 16

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes it's required to have a service discovery when doing microservices, but it's optional for monoliths. You can choose not to use it if you don't find it interesting.
