### ISSUE TITLE
[AngularX] production build fail for a v5.0.0-beta.0 project with multiple Lazy Loaded module

### ISSUE THREAD

**Issue by Ayuob-Alfouzan** [jhipster/generator-jhipster#7450]
At start, what a great library, I have been working on a jhipster project for 5 months, and I could not be happier with your works.
I know Lazy Loading is not a priority with this huge project, but if I may raise an issue I faced, or I am sorry and feel free to close it,

##### **Overview of the issue**

In 5.0.0-beta.0 the admin module is lazy loaded and it works fine with AoT production build. However, when adding another lazy loaded module, and running:
```
yarn run webpack:prod
```
the build terminate without errors, but isn't successful, and no files are emitted to target/www

```
C://.../jh5> yarn run webpack:prod
yarn run v1.3.2
$ yarn run cleanup && yarn run webpack:prod:main && yarn run clean-www
$ rimraf target/{aot,www}
$ yarn run webpack -- --config webpack/webpack.prod.js --profile
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.prod.js --profile
(node:388) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
$ rimraf target//www/app/{src,target/}
Done in 80.09s.
C://.../jh5>
```
##### **Motivation for or Use Case**

I think more than one lazy loaded module is needed and used

##### **Reproduce the error**

1. generate a new project with jhipster v5.0.0-beta.0 using angularX, SASS, and i18n options.
2. run yarn install.
3. Create any new module.
4. in app-routing.module.ts, add a new lazy route referencing the new module,
5. run yarn run webpack:prod

##### **Related issues**

I could not find one,

##### **Suggest a Fix**

I spent three days to find and try to fix the problem, but I could not :(.
What make it more deficult, there are no errors thrown,

##### **JHipster Version(s)**

```
`-- generator-jhipster@5.0.0-beta.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.0",
    "baseName": "jh5",
    "reactive": true,
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.15.0.windows.1

node: v8.9.4

npm: 5.6.0

yeoman: 2.0.0

yarn: 1.3.2

##### **Browsers and Operating System**

Windows 10, browser is not applicable,

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Thanks so much @Ayuob-Alfouzan for your kind words. It looks like lazy-loading + routing is pretty buggy in Angular - we had a lot of trouble to have it working, and now you are experiencing the same issue...

**Comment by deepu105** [comment]
This issue might be different as the build is failing. May be try to enable
all kind debug options for webpack/yarn and run it, as without an error its
quite hard to pinpoint the issue. Also try to play with it by removing
admin module and see if the other module alone works, could be some issue
you unknowingly introduced while making your other module lazy loaded.
Unfortunately we wont have time to help you here as its your own code. But
if you pinpoint the issue back to JHipster configuration or of you want to
improve something feel free to make a PR. Sorry I have to close this as its
not a priority for us. But ofcourse I can reopen if you find that it indeed
is an issue in code generated by Jhipster.

**Comment by jdubois** [comment]
Really sorry about this @Ayuob-Alfouzan but @deepu105 is right - I don't think this is a JHipster issue. But I'm really disappointed by Angular on this part, this looks overly complex and buggy.

**Comment by pauloegk** [comment]
I'm also having the same problem, building an application without jhipster lazy loading works correctly

**Comment by ruddell** [comment]
@pauloegk This is being tracked in https://github.com/jhipster/generator-jhipster/issues/7798
