### ISSUE TITLE
Use Prettier to css and scss files

### ISSUE THREAD

**Issue by JulioJu** [jhipster/generator-jhipster#7451]
##### **Overview of the issue**

Actually some css and scss files have style coding problems. This cause style inconsistence.

I've found some errors on css files and scss files in React and Angular part. 

##### **Related issues**

* pull #7448 from @agaspardcilia  or #7449 with their issue #7446 who show some css rules problems
* Pull: #7265 and its corresponding issue #7172 by @gmarziou who introduced the actual behaviour of Prettier
* issue: #7431 who debate about code indentation. 

##### **Suggest a Fix**
1. As said @deepu105, we could use Prettier to resolve easly this problems. Majors problems are the indentation, and some rules likes space around ":" or space around ">" or carriage-return after ",".  It's sometimes inconsistent. With Prettier, we could easy fix that, as @deepu105 says.
2. Make a PR to correct actual all `(s)css.ejs` problems (I could do that, it's easy). I work on a PR to fix that. We will have consistent (s)css.ejs if you accept that. 

##### **JHipster Version(s)**
JHipster 5.0.0-beta.0

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by JulioJu** [comment]
@deepu105 
In React, why css files have 4 spaces of indentation, and scss and ts(x) files have 2 spaces of indentation?

**Comment by jdubois** [comment]
Yes +1 from me, at least for correcting the issues "manually". Prettier support is less important, as we don't have a lot of CSS/SCSS, and as they are much, much easier to generate than Typescript or Java code.

**Comment by deepu105** [comment]
Yes go ahead and add a transformation stream for it

**Comment by deepu105** [comment]
yes go with 2

Thanks & Regards,
Deepu
