### ISSUE TITLE
OneToOne Relationships Foreign Key on Wrong Side Of Relationship

### ISSUE THREAD

**Issue by gigantedocil** [jhipster/generator-jhipster#7453]
##### **Overview of the issue**

Hello, everyone. I believe I have found a problem with the OneToOne relationship generation. Please consider the following relationship:

```
entity Citizen
entity Passport
relationship OneToOne {
    Citizen{passport} to Passport
}
```

This relationship means that the Citizen entity is the owner entity and the Passport is the owned entity, because Citizen will contain a Passport. At the database level, this will generate two tables, a Citizen table with an ID (UK) and a FK (UK) to Passport and a Passport table with an ID (UK). This is wrong because the FK should be on the Passport table. In the current state this means that if I create a Passport and then a Citizen with that Passport I won't be able to delete the passport unless I delete the citizen first (because of referential integrity) which makes no sense; it should be the other way around. I should be able to delete the Passport without a problem, but if I delete a Citizen with a passport it should give an error because I have to remove the associated passport first.

##### **Motivation for or Use Case**

This is an issue because it affects the way you model your domain with JDL. As explained in the previous section, if I make a OneToOne relationship where a Citizen has 0..1 Passport, I expect to be able to delete the passport without a problem and that is not possible at the moment.

##### **Reproduce the error**

Generate a JHipster app with the JDL from the first section. Create a Passport, then create a Citizen and associate the Passport. Now try to delete the Passport. It will give an Internal Error because of the referential integrity and the foreign key on the Citizen table.

##### **Related issues**

None.

##### **Suggest a Fix**

When modelling a OneToOne relationship like in the JDL I provided, the foreign key should be on the owned (in this example on the Passport) side with a unique key to prevent more than one entry.

##### **JHipster Version(s)**

```
citizen@0.0.0 /Users/joao/Desktop/Programming/Citizen
└── generator-jhipster@4.14.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.organon.pomar",
      "nativeLanguage": "pt-pt"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "Citizen",
    "packageName": "com.organon.pomar",
    "packageFolder": "com/organon/pomar",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-pt",
    "languages": [
      "pt-pt"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Citizen (citizen)
entity Passport (passport)

relationship OneToOne {
  Citizen{passport} to Passport
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.13.6 (Apple Git-96)

node: v8.6.0

npm: 5.6.0

yeoman: 2.0.0

yarn: 1.5.1

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
The owning side of the relation tracked by Hibernate is the side of the relation that owns the foreign key in the database.
https://stackoverflow.com/a/21068644/3737815

Based on that StackOverflow post and your comment "the FK should be on the Passport table", the Passport should be the owning entity.  Then the relationship will work as you expect.

**Comment by deepu105** [comment]
@ruddell @MathieuAA can this be closed? TLDR

**Comment by ruddell** [comment]
I think it's working as expected.
