### ISSUE TITLE
Remove the .dockerignore

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7455]
On the current master, our `.dockerignore` fails when building an application with Cassandra:

```
 ~/workspace/tmp3  docker-compose -f src/main/docker/cassandra.yml up -d
Building tmp3-cassandra-migration
Step 1/6 : FROM cassandra:3.9
 ---> 2da6dfd682cb
Step 2/6 : ADD cassandra/scripts/autoMigrate.sh /usr/local/bin/autoMigrate
ERROR: Service 'tmp3-cassandra-migration' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder158382573/cassandra/scripts/autoMigrate.sh: no such file or directory
```

This seems to be the culprit: https://github.com/docker/for-mac/issues/1922

Removing the `.dockerignore` file makes everything works again, but I'm not sure why this file is useful -> @pascalgrimaud you're the expert here, that's why I'm assigning the ticket to you, could you have a look? Otherwise let's just remove the file.

**Comment by jdubois** [comment]
Let me do it, I found the solution

**Comment by jdubois** [comment]
Argh no, wrong solution :-(

**Comment by pascalgrimaud** [comment]
Let remove this file.
We control the files we add in Dockerfile, so this dockerignore is not really usefull

**Comment by jdubois** [comment]
OK I'll wait for your comments @PierreBesson @pascalgrimaud - you're the best persons here!

**Comment by pascalgrimaud** [comment]
You're right, @PierreBesson but the gain is really minor.
Here some tests:

Without this `.dockerignore` file:

```
➜ docker build -t jhipster:latest .
Sending build context to Docker daemon  202.4MB
Step 1/5 : FROM openjdk:8-jre-alpine
 ---> b1bd879ca9b3
Step 2/5 : ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS     JHIPSTER_SLEEP=0     JAVA_OPTS=""
 ---> Using cache
 ---> 7871c5a227e1
Step 3/5 : CMD echo "The application will start in ${JHIPSTER_SLEEP}s..." &&     sleep ${JHIPSTER_SLEEP} &&     java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.war
 ---> Using cache
 ---> 5abe69a0e03a
Step 4/5 : EXPOSE 8080
 ---> Using cache
 ---> 575b9460e09b
Step 5/5 : ADD *.war /app.war
 ---> Using cache
 ---> 0edf8347a68e
Successfully built 0edf8347a68e
Successfully tagged jhipster:latest
```

With this `.dockerignore` file:

```
➜ docker build -t jhipster:latest .
Sending build context to Docker daemon  58.84MB
Step 1/5 : FROM openjdk:8-jre-alpine
 ---> b1bd879ca9b3
Step 2/5 : ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS     JHIPSTER_SLEEP=0     JAVA_OPTS=""
 ---> Using cache
 ---> 7871c5a227e1
Step 3/5 : CMD echo "The application will start in ${JHIPSTER_SLEEP}s..." &&     sleep ${JHIPSTER_SLEEP} &&     java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.war
 ---> Using cache
 ---> 5abe69a0e03a
Step 4/5 : EXPOSE 8080
 ---> Using cache
 ---> 575b9460e09b
Step 5/5 : ADD *.war /app.war
 ---> Using cache
 ---> 0edf8347a68e
Successfully built 0edf8347a68e
Successfully tagged jhipster:latest
```

**Comment by pascalgrimaud** [comment]
What the need to do, is to understand why the cassandra folder isn't ignore:
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/docker/.dockerignore.ejs#L24-L29

**Comment by PierreBesson** [comment]
202MB vs 59MB is not minor and it's fast only because you have a SSD. It would take several seconds on a slow machine

**Comment by hdurix** [comment]
Or what we could do is to exclude the target directories, as they are big, unwanted and may provoke dependency conflicts during the Docker build.

Here what I exclude in my current project:
```
target/*
node/*
node_modules/*
```

**Comment by hdurix** [comment]
@pascalgrimaud Just to be sure with your last comment, the cassandra folder is not ignored.
Everything is ignored except .war, .jar and cassandra folder (I don't know why it's not working with @jdubois).

**Comment by jdubois** [comment]
@hdurix from my understanding it's not working because of a bug in Docker 4 Mac (or at least in Docker). It was working before!

**Comment by pascalgrimaud** [comment]
Agree with you @PierreBesson but it seems to work well on Linux, and we don't have other system (Mac or Windows) to reproduce and try to fix it.

So the very quick fix is simply remove this file: https://github.com/jhipster/generator-jhipster/pull/7459
Another fix would take more time, to find a machine and test it

**Comment by pascalgrimaud** [comment]
@hdurix : here what we need to check and to exclude:

```
➜ ls -al target 
total 107552
drwxrwxr-x 11 pgrimaud pgrimaud     4096 avril 10 12:40 .
drwxrwxr-x  9 pgrimaud pgrimaud     4096 avril 10 09:32 ..
drwxrwxr-x  6 pgrimaud pgrimaud     4096 avril 10 09:51 classes
drwxrwxr-x  2 pgrimaud pgrimaud     4096 avril 10 09:52 docker
-rw-rw-r--  1 pgrimaud pgrimaud      318 avril 10 09:50 Dockerfile
-rw-rw-r--  1 pgrimaud pgrimaud      140 avril 10 09:50 .dockerignore
drwxrwxr-x  3 pgrimaud pgrimaud     4096 avril 10 09:50 generated-sources
drwxrwxr-x  3 pgrimaud pgrimaud     4096 avril 10 09:51 generated-test-sources
drwxrwxr-x  8 pgrimaud pgrimaud     4096 avril 10 09:51 jhipster-0.0.1-SNAPSHOT
-rw-rw-r--  1 pgrimaud pgrimaud     9198 avril 10 09:52 jhipster-0.0.1-SNAPSHOT-docker-info.jar
-rwxrw-r--  1 pgrimaud pgrimaud 58827209 avril 10 09:51 jhipster-0.0.1-SNAPSHOT.war
-rw-rw-r--  1 pgrimaud pgrimaud 51228815 avril 10 09:51 jhipster-0.0.1-SNAPSHOT.war.original
drwxrwxr-x  2 pgrimaud pgrimaud     4096 avril 10 09:51 maven-archiver
drwxrwxr-x  3 pgrimaud pgrimaud     4096 avril 10 09:50 maven-status
drwxrwxr-x  7 pgrimaud pgrimaud     4096 avril 10 09:52 test-classes
drwxrwxr-x  6 pgrimaud pgrimaud     4096 avril 10 09:32 www
```

**Comment by PierreBesson** [comment]
Maybe it would work if the gitignore doesn't have any `!` in it. Maybe a blacklist strategy would work and be cleaner as it will be less surprising for users as the default behavior will not be to ignore files.
