### ISSUE TITLE
rxjs should be used with pipeable operators

### ISSUE THREAD

**Issue by maku** [jhipster/generator-jhipster#7458]
##### **Overview of the issue**

In the generated sources (angular) **rxjs** is used with the patched operators for dot-chaining. This is not the suggested usage anymore.
Therefore pipe should be used instead: see https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

##### **Motivation for or Use Case**

Should lead to a better tree-shakeability of the app

##### **JHipster Version(s)**
5.0.0-beta.0

**Comment by deepu105** [comment]
Would you consider doing a PR?

**Comment by JulioJu** [comment]
Maybe I could try… But without guarantee…

**Comment by wmarques** [comment]
@deepu105 @JulioJu I think this is done in #7582

**Comment by JulioJu** [comment]
@wmarques sorry, the last month I was less time was I thought. If it's done, it's so cool :-).

**Comment by ruddell** [comment]
Fixed in the Angular 6 migration
