### ISSUE TITLE
Add a flag so jHipster won't generate comments

### ISSUE THREAD

**Issue by aBnormaLz** [jhipster/generator-jhipster#7464]
##### **Overview of the issue**

It would be awesome if I yould tell jHipster not to generate any comments or javadoc into the code

##### **Motivation for or Use Case**

The idea behind this is that lot of coders doesn't like comments, because they have to keep the comment up-to-date with the code, and sometimes they forget to update it. So comments get into an out-of-date state very often.

**Comment by jdubois** [comment]
- One of our "rules" is that we only do comments when it's necessary, as we do believe the same thing as you (we do agree!)
- Removing comments has also a strange (but nice) side effect: currently they break https://github.com/thorbenvh8/prettier-java ! So I would also like to get rid of them

Now we just can't remove them like that, it would be a lot of work -> I think that once we have https://github.com/thorbenvh8/prettier-java we could be able to configure it to remove comments, and that would solve your issue elegantly.

I'm closing this as I think this is a good solution, but that will be in the future as https://github.com/thorbenvh8/prettier-java isn't stable yet, and we don't keep opened tickets for too long unless we really need to.
