### ISSUE TITLE
Could not find a valid JHipster UAA server in path "uaa" 

### ISSUE THREAD

**Issue by cmcruzata** [jhipster/generator-jhipster#7466]
Hi, I know I'm late but, I'm trying to generate an app with Microservice application and continue the same issue. Here's a snapshot of issue.

Welcome to the JHipster Generator v4.14.2
Application files will be generated in folder: N:\SRA

? Which type of application would you like to create? Microservice application
? What is the base name of your application? SRA
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8081
? What is your default Java package name? com.sra.server
? Which service discovery server do you want to use? No service discovery
? Which type of authentication would you like to use? Authentication with JHipster UAA server (the server must be generate
d separately)
? What is the folder path of your UAA application? (../uaa)

Could not find a valid JHipster UAA server in path "../uaa"

Folder structure:
SRA(root)
-----ClientWeb
-----uaa

OS: windows10
yeoman: 2.0.1
yarn: 1.5.1
node: 8.9.3
npm: 5.7.1

**Comment by ruddell** [comment]
Did you generate the UAA before the microservice? I could not reproduce, maybe it is specific to Windows.

**Comment by gmarziou** [comment]
> Application files will be generated in folder: N:\SRA
> Could not find a valid JHipster UAA server in path "../uaa"

I don't understand what you are doing.
You run the generator in`N:\SRA`   so it expects to find uaa in `N:\SRA\..\uaa` which resolves in `N:\uaa`  which does not exist.

You should `cd N:\SRA\ClientWeb` before running the generator.

**Comment by ruddell** [comment]
Sounds like the issue was solved.  @cmcruzata Let us know if you are still having issues and we can reopen

**Comment by cmcruzata** [comment]
Issue was solved.
