### ISSUE TITLE
remove redundance 2-level cache,change to spring cache

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#7471]
**sorry, my english is not very good.please a little more patience**

##### **Overview of the issue**

jpa + Hibernate 2-level cache is not work.

the main code

https://github.com/jhipster/generator-jhipster/blob/5c58e1ce7b551c9e97f71cd42e9dbd0dc57d5235/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs#L98-L105

when you exec sql query ,it will save the entity to cache engine, but never used.

##### **Motivation for or Use Case**

my demo repo https://github.com/anjia0532/jhipster-2level-cache-demo . 

git diff https://github.com/anjia0532/jhipster-2level-cache-demo/commit/ab489524540a8fcceb2feb3d5c524ec7f9978d18

download hazelcast management-center from https://hazelcast.org/download/#management-center

##### **Reproduce the error**
1. startup management-center and setup auth config

2. startup jhipster-2level-cache-demo

3. `curl http://127.0.0.1:12345/api/users`   2 times

4. console log `Hibernate: select user0_.id as ....` was 2 times.

5. login h2-console and exec `update JHI_USER set first_name ='user_test' where login='user'`

6. `curl http://127.0.0.1:12345/api/users` the account `user`'s first_name is change to `user_test`

7. login management-center and connect to `dev` env

8. ![haze1](https://user-images.githubusercontent.com/15098916/38657358-539f144c-3e52-11e8-973e-d6577078357d.png)

9. ![haze2](https://user-images.githubusercontent.com/15098916/38657367-642b9196-3e52-11e8-8066-d5e79437e3fb.png)

10. `curl http://127.0.0.1:12345/api/users/user` the account `user`'s first_name is `user_test`

11. ![haze3](https://user-images.githubusercontent.com/15098916/38657414-a889db90-3e52-11e8-9701-a5b628e087c5.png)

12. exec `update JHI_USER set first_name ='foo' where login='user'` and  `curl http://127.0.0.1:12345/api/users/user` the account `user`'s first_name is `user_test` too.

if i create a big table(100 million rows) and query all of them. it will cached by hazelcast or ehcache. **NOTE: this cache be  never used** 

so https://github.com/anjia0532/jhipster-2level-cache-demo/blob/ab489524540a8fcceb2feb3d5c524ec7f9978d18/src/main/java/com/mycompany/myapp/domain/User.java#L28 
`@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)`
it's redundance .

hazelcast map max size is `MaxSizePolicy.USED_HEAP_SIZE`

https://github.com/jhipster/generator-jhipster/blob/5c58e1ce7b551c9e97f71cd42e9dbd0dc57d5235/generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs#L294
```java
 mapConfig.setMaxSizeConfig(new MaxSizeConfig(0, MaxSizeConfig.MaxSizePolicy.USED_HEAP_SIZE));
```

ref http://docs.hazelcast.org/docs/3.9.3/manual/html-single/index.html#configuring-map-eviction

> max-size: Maximum size of the map. When maximum size is reached, the map is evicted based on the policy defined. Valid values are integers between 0 and Integer.MAX VALUE. Default value is 0, which means infinite. If you want max-size to work, set the eviction-policy property to a value other than NONE. Its attributes are described below.

>> USED_HEAP_SIZE: Maximum used heap size in megabytes per map for each Hazelcast instance. Please note that this policy does not work when in-memory format is set to OBJECT, since the memory footprint cannot be determined when data is put as OBJECT.

>> PER_NODE: Maximum number of map entries in each cluster member. This is the default policy. If you use this option, please note that you cannot set the max-size to a value lower than (partition-count/member-count) (Partition count is 271 by default).

##### **Suggest a Fix**

1. remove `@Cache` from entity and use spring cache 
like jhipster generator app's code 

[@Cacheable(cacheNames = USERS_BY_EMAIL_CACHE)](https://github.com/anjia0532/jhipster-2level-cache-demo/blob/ab489524540a8fcceb2feb3d5c524ec7f9978d18/src/main/java/com/mycompany/myapp/repository/UserRepository.java#L43) and [cacheManager.getCache(UserRepository.USERS_BY_EMAIL_CACHE).evict(user.getEmail());](https://github.com/anjia0532/jhipster-2level-cache-demo/blob/ab489524540a8fcceb2feb3d5c524ec7f9978d18/src/main/java/com/mycompany/myapp/repository/UserRepository.java#L43)

or 2. use `@QueryHints`
preserved  `@Cache`

set `spring.jpa.properties.hibernate.cache.use_query_cache: true`
added `@QueryHints` to  EntityRepository's method

```java
    @QueryHints({ @QueryHint(name = "org.hibernate.cacheable", value ="true") })
    Page<User> findAllByLoginNot(Pageable pageable, String login);
```

3. set the eviction-policy property to `PER_NODE` and default max-size e.g. 2000? or 5000?

**ref**
1. https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-hints
2. http://www.baeldung.com/hibernate-second-level-cache
3. https://www.thoughts-on-java.org/11-jpa-hibernate-query-hints-every-developer-know/

**Note: Chinese blog**
1. http://www.spring4all.com/article/467
2. http://leobluewing.iteye.com/blog/2032396

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
cache@0.0.0 G:\cache
`-- generator-jhipster@4.14.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.3",
    "baseName": "cache",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.11.0.windows.3

node: v8.9.4

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.5.1

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Blackdread** [comment]
Cache is working, you should check hibernate, it uses cache with ID so findOne(ID), etc.
You are querying a list of entities, it will not work like you expect -> for that you can add \@Cacheable (**Spring cache abstraction**) to a repository method or a service method (the result will be cached and used if parameters are equals between different calls).
Collections in entities are cached (if annotated) and only the id is cached as the entity itself is cached in another namespace of Hibernate.

By default jhipster put a configuration of 1000 entries per namespace, this is default you can change and have more cache configuration that fit your business logic.

**Comment by anjia0532** [comment]
@Blackdread thanks for your reply. yes, u r right,  @Cache is work. 

but
> By default jhipster put a configuration of 1000 entries per namespace?

from the master branch code
https://github.com/jhipster/generator-jhipster/blob/3ac4037833b4b2e6b4d811c50f4587b2798565a4/generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs#L269-L297


l'll close this issues.
