### ISSUE TITLE
Secure direct upload to S3 from the client side as an option while generating the app

### ISSUE THREAD

**Issue by levioza** [jhipster/generator-jhipster#7473]
##### **Overview of the issue**

Allow the client application (React or Angular) to upload to Amazon S3 using secured signed requests.

##### **Motivation for or Use Case**

Please read: https://medium.com/@levioza/storing-your-blobs-on-a-cloud-storage-provider-amazon-s3-da6c1515cc76

##### **Suggest a Fix**

I create a sample app [here](https://github.com/levioza/spring-boot-amazon-s3). This should be merged with the application.

Regarding testing, a mock is needed for the AmazonS3Service as the current test is a live integration test.

**Comment by deepu105** [comment]
Sorry, this is too specific use case and hence we won't be able to do it.

**Comment by pascalgrimaud** [comment]
It could probably be a module.
See https://www.jhipster.tech/modules/creating-a-module/
