### ISSUE TITLE
autoMigrate.sh file In cassandra/scripts

### ISSUE THREAD

**Issue by dhireshartron** [jhipster/generator-jhipster#7474]
##### **Overview of the issue**
Actually there is little bit of error in autoMigrate.sh file of cassandra/scripts
whose actual path is ./generators/server/templates/src/main/docker/cassandra/scripts/

actually when you specify path other than ./generators/server/templates/src/main/resources/config/cql/changelog it creates an error. which is actually a bug which is very little mistake.
EXECUTE_CQL_SCRIPT=$SCRIPT_DIR'/execute-cql.sh'
but actually it should be EXECUTE_CQL_SCRIPT=$SCRIPT_DIR'/execute-cql'
as been specified in dockerFile of cassandra migration which is 
both automigrate.sh and execute-cql.sh been moved as autoMigrate and execute-cql excluding .sh extension in /usr/local/bin folder of cassandra migration image.
##### **Motivation for or Use Case**

it is bug for me because when i tried changing the path to different location other than changelog it throws an error that there is no such file (execute-cql.sh). 
##### **Reproduce the error**
this is error
EXECUTE_CQL_SCRIPT=$SCRIPT_DIR'/execute-cql.sh' 
in ./generators/server/templates/src/main/docker/cassandra/scripts/autoMigrate.sh

try entering command line argument which is basically the path of folder other than changelog 
by using 'command:' attribute in cassandra.yml for the cassandra migration
##### **Suggest a Fix**
it will be fix of solution
EXECUTE_CQL_SCRIPT=$SCRIPT_DIR'/execute-cql'
in ./generators/server/templates/src/main/docker/cassandra/scripts/autoMigrate.sh

##### **JHipster Version(s)**

i am using version 4.12.0
##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
friends-book@0.0.0 /media/hartron/0051c455-8329-4a3d-9872-40a0be719ae5/FriendsBook/FriendsBook
+-- generator-jhipster@4.6.2 
`-- generator-jhipster-nav-element@1.4.16
  `-- generator-jhipster@4.10.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "friends",
      "microservicePath": "../StatusUpdate"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "FriendsBook",
    "packageName": "friends",
    "packageFolder": "friends",
    "serverPort": "8000",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>
<pre>
</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)

git version 2.7.4

node: v8.11.1

npm: 5.6.0

gulp:
[16:49:19] CLI version 1.4.0
[16:49:19] Local version 3.9.1

yeoman: 2.0.0

yarn: 1.5.1

Docker version 17.06.1-ce, build 874a737

docker-compose version 1.8.0, build unknown

Execution complete

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I don't understand this issue. You didn't describe all steps in details to reproduce it.

`./generators/server/templates/src/main/docker/cassandra/scripts/autoMigrate.sh` can't exist in your project -> it's normal because this file belongs to `generator-jhipster`

The `autoMigrate.sh` file is in: `src/main/docker/cassandra/scripts/`
And if you want to use it, you need to start a Cassandra yourself -> you didn't mention it in your ticket.

Just tested:
- generate a new Cassandra project
- docker-compose -f src/main/docker/cassandra.yml up -d
- everything is working as expected

**Comment by pascalgrimaud** [comment]
Feel free to comment, add all steps to understand your issue and we can reopen if there is a real issue

**Comment by dhireshartron** [comment]
add a line in casaandra.yml file so that it looks like this 
version: '2'
services:
    project-cassandra:
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/project/cassandra/:/var/lib/cassandra/data
        volumes:
            - ~/csvfiles:/csvfiles
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160

    project-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: project-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
        command: /cql/myCqlFiles/
extra line is this "command: /cql/myCqlFiles/"
what this line will do is will pass an argument /cql/myCqlFiles/ to automigrate so that now instead of changelog folder files will be executed from myCqlFiles folder .
so create a folder in src/main/resources/config/cql named myCqlFiles and put your cql files there 

now run this command 

docker-compose -f src/main/docker/cassandra.yml up -d
error will be reproduced
