### ISSUE TITLE
BigDecimal is incorrectly handled by generated liquibase configuration

### ISSUE THREAD

**Issue by agilob** [jhipster/generator-jhipster#7485]
##### **Overview of the issue**
Fields of type `BigDecimal` are saved as Decimal, because generated liquibase does not specify precision. Example:
Generate a class that has field of type BigDecimal, purpose of the field is to store high precision value.
This is generated as:

    @NotNull
    @Column(name = "jhi_value", precision=10, scale=8, nullable = false)
    private BigDecimal value;

Corresponding liquibase field will have definition as follows:

            <column name="jhi_value" type="DECIMAL">
                <constraints nullable="false" />
            </column>

When field with value `120.2131232141` is saved to production database and tables (that was also generated with jhipster) will have value of `120`, all values between `0..1` like `0.1231231`, `0.000002` will be saved just as `0`. 

Problem affects mariadb and postgresql databases, but does not affect in memory database h2, makes behaviour inconsistent between dev and production systems.

##### **Suggest a Fix**

Fix is to change type in liquibase to `DECIMAL(18, 8)` for mariadb (tested) and to `DECIMAL(10,8)` for postgress (not tested)

##### **JHipster Version(s)**
```
➜  ~ jhipster -V    
Using JHipster version installed globally
4.13.0
```

**Comment by Blackdread** [comment]
For me, jhipster 4.14.0 it generated:
```
<column name="min_value" type="decimal(10,2)">
                <constraints nullable="false" />
</column>
```
and
```
@NotNull
@Column(name = "min_value", precision=10, scale=2, nullable = false)
private BigDecimal minValue;
```

**Comment by gmarziou** [comment]
Yes @Blackdread is right, this is handled [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs#L80-L81)
