### ISSUE TITLE
tslint.json -> tslint.yml and tslint rules

### ISSUE THREAD

**Issue by JulioJu** [jhipster/generator-jhipster#7486]
##### **Overview of the issue**
It could be cool to have tslint.yml instead of tslint.json because yaml is much more readable and it's natively commentable. 

##### **Motivation for or Use Case**

It cool be cool to write a tslint.yml commented, with rules ordered by type and by letter like in https://palantir.github.io/tslint/rules/. We could use their titles section.

##### **Related issues**

Nothing found. I've search "tslint.yml" and "tslint.yaml"

##### **Suggest a Fix**
If you are ok, I would like to make a PR.
##### **JHipster Version(s)**
For JHipster 5.0.

##### **JHipster configuration**
Irrelevant

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
As we copy our tslint config from Angular CLI, in order to have the same rules as the official Angular generator, can you check if they use a tslint.json or a tslint.yml? Otherwise it could be hard for us to migrate.

**Comment by JulioJu** [comment]
@jdubois angular-cli use json files. But thanks https://www.json2yaml.com/ it's very very very easy to migrate :-). I think it's a good idea to migrate because there isn't too much differences between yaml and json, but yaml it's very more readable ;-). 

And as we could see bellow, there is already lot of differences between angular-cli tslint rules and jhipster tslint rules   ;-).  With  https://www.json2yaml.com/ it could be also quickly to see the difference. The yaml filetype give use the benefit to add a link to this tool at the beginning of the file ;-). And more comments to have more informations about rules… 

#### Maybe add some rules.
Your comment give me idea to compare both. There are more rules in angular than in JHipster.

##### List of rules
Quickly, I've done a list of differences for angular.  The list is below.

For the following diff, I've readden https://github.com/jhipster/generator-jhipster/issues/7257.

```json
       // rules who are not in the JHipster tslint.json
        "deprecation": {
            "severity": "warn"
        },
        "import-blacklist": [
            true,
            "rxjs",
            "rxjs/Rx"
        ],
        "no-inferrable-types": [
            true,
            "ignore-params"
        ],
        "no-empty-interface": true,
        "no-misused-new": true,
        "no-non-null-assertion": true,
        "no-string-throw": true,
        "no-unnecessary-initializer": true,
        "no-use-before-declare": true,
        "unified-signatures": true,
        "no-duplicate-super": true,

        // differ (there are other differences but I understand why there are different)
        "max-line-length": [
            true,
            180
        ],
        "member-ordering": [
            true,
            {
                "order": [
                    "static-field",
                    "instance-field",
                    "static-method",
                    "instance-method"
                ]
            }
        ],
```

##### depreciation warning


```
        "deprecation": {
            "severity": "warn"
        },
``` 
give use than we should use Renderer2 and not the old Renderer. What do you think about that? I could see that…


##### Other rules
With the rules above I have following errors. I can try to fix it if you want.
```
ERROR: (import-blacklist) /home/julioprayer/generator-jhipster/travis/samples/ngx-default-sample/src/main/webapp/app/core/language/language.helper.ts[5, 46
]: This import is blacklisted, import a submodule instead
ERROR: (no-use-before-declare) /home/julioprayer/generator-jhipster/travis/samples/ngx-default-sample/src/test/javascript/e2e/page-objects/jhi-page-objects
.ts[62, 20]: variable 'SignInPage' used before declaration
ERROR: (no-use-before-declare) /home/julioprayer/generator-jhipster/travis/samples/ngx-default-sample/src/test/javascript/e2e/page-objects/jhi-page-objects
.ts[67, 20]: variable 'PasswordPage' used before declaration
ERROR: (no-use-before-declare) /home/julioprayer/generator-jhipster/travis/samples/ngx-default-sample/src/test/javascript/e2e/page-objects/jhi-page-objects
.ts[73, 20]: variable 'SettingsPage' used before declaration
ERROR: (import-blacklist) /home/julioprayer/generator-jhipster/travis/samples/ngx-default-sample/src/test/javascript/spec/entry.ts[10, 9]: This import is b
lacklisted, import a submodule instead
ERROR: (import-blacklist) /home/julioprayer/generator-jhipster/travis/samples/ngx-default-sample/src/test/javascript/spec/helpers/mock-route.service.ts[3,
29]: This import is blacklisted, import a submodule instead

```

##### Change `yarn lint` behaviour

If you like, we could also change the command `yarn link`.

The list above is given thanks my command `$ tslint --project tsconfig.json src/**/*.ts --format verbose`. Actually the command is `tslint --project tsconfig.json -e 'node_modules/**'`.

Maybe the command with the parameter `-format verbose` is better because we could know what is the name of the rule who failed. Better to have explanation on Google / Stackoverflow, https://palantir.github.io/tslint/rules/ or https://github.com/palantir/tslint/tree/master/test/rules.

**Comment by gmarziou** [comment]
@JulioJu I think that the point about angular cli using tslint.json rather than tslint.yml was not about migration, it was more about staying as compatible as possible with angular cli.

Also we can already use comments in tslint.json as stated in [tslint doc](https://palantir.github.io/tslint/usage/configuration/)

> tslint.json configuration files may have JavaScript-style // single-line and /* multi-line */ comments in them (even though this is technically invalid JSON). If this confuses your syntax highlighter, you may want to switch it to JavaScript format.

**Comment by JulioJu** [comment]
@gmarziou ok :-). 

For the other subject, what do you think about add some tslint rules in tslint.json? To match nearer angular-cli?

**Comment by gmarziou** [comment]
I did not look into the details of these rules but as long as sample app passes (with potential minor fixesà it's OK.

I had same thoughts about the ng compiler options in tsconfig-aot.json, some were missing so I just added them and then got some errors on sample app that seemed useless so I got rid of half of them.

**Comment by deepu105** [comment]
@jdubois we didn't copy our rules from NG CLI, this is our own set of rules, so we can use yml if its supported OOB. Regarding Angular CLI we only ensure that any code generated by it is compatible with our rules so yes, our rules do match what Angular CLI generates a bit, but of course we can choose to disable some rules, especially due to prettier.

Now about YML itself, I dont see any value, as we can already have comments and its more wideley supported in all IDE and editors so lets stick to the default unless there is a good reason to do so, which is our policy

**Comment by jdubois** [comment]
@deepu105 it probably changed, but I did copy the rules from NG CLI at the begining :-)

**Comment by agoncal** [comment]
And one day, we will come back to XML ;o)
