### ISSUE TITLE
Alerts not displaying in IE 11 using prod profile on JHipster 4.14.2

### ISSUE THREAD

**Issue by dudleybutt** [jhipster/generator-jhipster#7493]
##### **Overview of the issue**

Alerts are working using the dev profile in ALL browsers.
Alerts are not appearing only in IE 11, when doing a package build using the prod profile command
`./mvnw -Pprod clean package`

Screenshots and further info can be found on the link below.
https://stackoverflow.com/questions/49730955/alerts-not-displaying-in-ie-11-using-prod-profile-on-jhipster-4-14-2

##### **Motivation for or Use Case**

My client still only uses IE 11. 

##### **Reproduce the error**

1. Using the prod profile, simply add a new user with existing details using IE 11.
2. The alert error is not displayed correctly.
OR
1. Using the prod profile, simply add a new user in IE 11.
2. No alert is displayed but the user is created successfully.

##### **Suggest a Fix**

It looks like some polyfills might not be getting into the prod profile package?

##### **JHipster Version(s)**

jhipster-4.14.2

##### **JHipster configuration**

`
$ jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
online-tool@0.0.0 C:\Users\U203455\IdeaProjects\online-tool
`-- generator-jhipster@4.14.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com...."
    },
    "jhipsterVersion": "4.14.2",
    "baseName": "OnlineTool",
    "packageName": "com...",
    "packageFolder": "com/..",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mssql",
    "prodDatabaseType": "mssql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "cacheProvider": "no",
    "enableHibernateCache": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

REMOVED SENSITIVE INFO
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.15.1.windows.2

node: v8.9.4

npm: 5.6.0

bower: 1.8.2

yeoman: 2.0.0

yarn: 1.3.2

Congratulations, JHipster execution is complete!
`

##### **Browsers and Operating System**

Win 7 Professional with IE 11 ONLY

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
This could be related to #7641 @chrisdns plz confirm
@dudleybutt can you check and let us know if you see the issue in latest master branch
