### ISSUE TITLE
Redis support for cache

### ISSUE THREAD

**Issue by micobarac** [jhipster/generator-jhipster#7503]
##### **Overview of the issue**

jHipster generator doesn't offer Redis caching engine during project generation process.

##### **Motivation for or Use Case**

If I choose Hazelcast during project generation, how do I replace it with Redis? I know that I have to add Redis dependency to `pom.xml`, but how do I change `CacheConfiguration.java` to support Redis? 

##### **JHipster Version(s)**

JHipster 4.14.0

##### **Browsers and Operating System**

MacOS High Sierra
Google Chrome

**Comment by micobarac** [comment]
Oh, come on, I followed guidelines as much as I could. 
This isn't actually a bug, more like a feature change.
If you don't want to help, that's another thing.

**Comment by pascalgrimaud** [comment]
Sorry @micobarac but the title of this ticket is a question, and not a feature request.

If it's a question / help: use stackoverflow or gitter instead

If it's a feature request, we can discuss about it. In that case, are you ready to code this part? In the generator directlyt if all members are ok, or in a module, that you will be the main author ?

We don't ignore Redis, this is simply nobody want to code it.

**Comment by jdubois** [comment]
I have planned to do this for a long time, along with Memcached support, but that's like a zillion other things we could do if we had more time on the project... It's just not going to be done soon, unless someone wants to step in.

**Comment by pascalgrimaud** [comment]
No more comment since the last 7 days. So let close this.
If someone want to add the support, just tell it in this ticket and we will discuss about it.

**Comment by DanielFran** [comment]
I would love to have it but did not have time yet to investigate what is needed...

**Comment by jdubois** [comment]
I'll do a special stream for Redis and Memcached, probably with my trainees, but not until a few months as we have far too much work at the moment
