### ISSUE TITLE
Needles are broken due to prettier formatting

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7505]
Our needle system normally checks for existing content before inserting anything to avoid duplication. Since we started using Prettier some of the needles are inserting duplicate content as it couldn't find the existing content which was modified by prettier.

We need to ensure that we insert content via needles with same formatting as prettier to avoid this issue.

The issue is evident in React and Angular code now, but could affect CSS/SASS as well

**Comment by jdubois** [comment]
@deepu105 can you give an example? I'm trying to reproduce

**Comment by deepu105** [comment]
The React header where we add the new entity items to menu for example. Sorry on my phone so can't point to exact line. 
One option is to turn off prettier for the nodes which are used as needles using the prettier ignore comments in the code.

**Comment by deepu105** [comment]
closed via https://github.com/jhipster/generator-jhipster/pull/7558
