### ISSUE TITLE
javascript source maps

### ISSUE THREAD

**Issue by smoothello** [jhipster/generator-jhipster#751]
Apologies in advance if the answer to my question is obvious but I can't find the javascript source map file for the production profle...did I look in the wrong place (and missed it) or is that feature not implemented yet ?

**Comment by erikkemperman** [comment]
Sorry to comment on old and closed topic... But I would love to have an option for sourcemaps as well! Any chance of reconsidering this?

It would mean that users who encounter errors will be able to provide meaningful reports / stacktraces. I know most of the relevant grunt/gulp plugins know about sourcemaps these days (certainly concat and uglify). The production war includes all the unminified material anyway, so it's basically free.

And it works for stylesheets as well, so your browser inspector might link back to scss files even...

Refs (gulp plugins all have similar options):
- [grunt-concat](https://github.com/gruntjs/grunt-contrib-concat#sourcemap)
- [grunt-uglify](https://github.com/gruntjs/grunt-contrib-uglify#sourcemap)
- [node-sass](https://github.com/sass/node-sass#sourcemap)

**Comment by jdubois** [comment]
Yes @erikkemperman this has been opened again :-)
Nobody is currently working on this, so if you want to take the lead, just go ahead!
