### ISSUE TITLE
Max and Min validators for number input fields  don't work in Angular5

### ISSUE THREAD

**Issue by stefanobertini** [jhipster/generator-jhipster#7514]
##### **Overview of the issue**

Min and Max validators have no effects on numeric input fields in Angular5.
No error is generated inserting bad values.

##### **Reproduce the error**

Create an entity with a numeric field and insert a max and min constraints.

##### **JHipster Version(s)**

```
test-validation@0.0.0 /Users/sbertini/Temp/_Delete/30/TestValidation
└── generator-jhipster@4.14.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.14.3",
    "baseName": "TestValidation",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity TestEntity (test_entity) {
  testValue Integer required min(0) max(10)
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.14.3 (Apple Git-98)

node: v6.10.1

npm: 5.6.0

bower: 1.8.2

gulp:
[18:35:17] CLI version 1.2.2

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by GuiF007** [comment]
Which browser do you use to try ?

**Comment by stefanobertini** [comment]
Sorry, forgot to report the browsers.

Tried on:
- Chrome 66.0.3359.117 
- Firefox 52.6
- Safari 11.1 (12605.1.33.1.3)

**Comment by DanielFran** [comment]
Did not found any open ticket for this issue, only with messages missing for Min/Max validators in v4: https://github.com/jhipster/generator-jhipster/issues/7305

**Comment by Dufgui** [comment]
Hello,

according to this SOF https://stackoverflow.com/questions/39847862/min-max-validator-in-angular-2-final/
Angular does n't provide a min max validator. So 2 choices:

1. implement our validator
2. use a lib like https://github.com/yuyang041060120/ng2-validation

Personally I prefere the first option. Core team, what to you prefere ?

**Comment by Dufgui** [comment]
@deepu105 I don't know for tree but the lib alone take 1.3 Mo but with their dep it's close to 40 Mo.... so NO ! ;)
I start a dev to add min max validator in ng jhipster

**Comment by Dufgui** [comment]
validator done in ng-jhipster. now I test it on generator side
