### ISSUE TITLE
Feature request: Support font-awesome v.5

### ISSUE THREAD

**Issue by gomesp** [jhipster/generator-jhipster#7516]
##### **Overview of the issue**

JHipster is currently supporting font-awesome 4.7.0. The project has now released version 5.0.10. Could we please add support to it?

Unfortunately it is not a simple change of the package version, as the icon names [have changed slightly](https://fontawesome.com/how-to-use/upgrading-from-4). 

This could even trigger another option for the generator, e.g. "What font-awesome icon set would you like to include in your project? 1. Solid, 2. Regular, 3. Light".

I am keen to have a go and open a pull-request at some point if the project is in agreement for the change.

##### **Motivation for or Use Case**

To keep up with the font-awesome project development.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
+1
Yes we should upgrade.

> This could even trigger another option for the generator, e.g. "What font-awesome icon set would you like to include in your project? 1. Solid, 2. Regular, 3. Light".

Currently we have 63 places where we use icons in our templates.
It's very easy for a user to do a search/replace on `class="fa` to select another variant.
So I'm not sure a new question is really needed.

**Comment by pascalgrimaud** [comment]
+1 too

**Comment by deepu105** [comment]
Will you consider doing a PR

**Comment by gomesp** [comment]
@deepu105 if you give me 1 week I can do a PR. I imagine that the agreement is to simply replace the package with v.5 and test the generator again, right? 

I will keep the icon set with the solid family (fas or fa) to avoid a lot of regression testing. I may have change the css class for any icons that are now under the "font-awesome brands" (e.g. github, etc).

**Comment by jdubois** [comment]
Yes it should not be very hard but that's quite time consuming to test... oh and please have a look at Angular and React - for this part it should be very similar. 
Anyway big big +1 if you do that PR!
(At work we are still with v4 and I'd love to have some of the new v5 icons)

**Comment by gomesp** [comment]
I just opened the pull request https://github.com/jhipster/generator-jhipster/pull/7519.

I decided to open it sooner so that you guys could give feedback faster. I'm not sure if my approach for including the SVG/JS icon set is according to guidelines. If not I can change it and resubmit the PR. 

@jdubois I only worked in the angular codebase. But that was mostly because I could not find any instance of the FA icons in the react codebase! That may have to do with me not knowing the first thing about react. ;)

I can look into the react codebase again tomorrow to figure out where FA is being used and open another PR just for react.

**Comment by jdubois** [comment]
Oh I know the Angular codebase much better - maybe it's not included in React.

**Comment by deepu105** [comment]
@agaspardcilia @gomesp FA now has an official binding for React so maybe we could switch to that as well

**Comment by gomesp** [comment]
@deepu105 I will have a look at the react codebase later this week to see what's involved.

**Comment by gomesp** [comment]
@agaspardcilia By all means go ahead. I am new to React, so I'd have to spend some time exploring until I'd do something useful. Tag me on the PR so I can read what you've done and learn something too. 👍

**Comment by agaspardcilia** [comment]
@gomesp Alright then.

**Comment by maznag** [comment]
here is a PR to fix sort icon names for fontawesome v5 https://github.com/jhipster/ng-jhipster/pull/70

fa-sort-up and fa-sort-down instead of fa-sort-asc and fa-sort-desc

**Comment by jdubois** [comment]
Closing as this is done for Angular and React!
