### ISSUE TITLE
Token can't be saved to the local storage when the expires_at is NaN

### ISSUE THREAD

**Issue by bluecitymoon** [jhipster/generator-jhipster#7518]
![image](https://user-images.githubusercontent.com/248692/39085850-80c5b640-45bb-11e8-900f-9eba63e545c1.png)

I changed oauth_client_details.access_token_validaty to -1 , yep I know it's a little bit weird. But after doing that, the response string which contains a NaN varible can't be saved to the local storage. That's pretty fun so that I want to share with you guys.

Using Jhipster v 4.9.0 (last version before the built-in oauth2 server is removed)

Regards,
Jerry

**Comment by bluecitymoon** [comment]
This is the one working...
![image](https://user-images.githubusercontent.com/248692/39085940-14293ed8-45bd-11e8-83be-c363e082a703.png)
![image](https://user-images.githubusercontent.com/248692/39085943-250edeba-45bd-11e8-8041-915f39b6f045.png)

**Comment by gmarziou** [comment]
Thanks for sharing but as you said, this option is no longer supported so I'm closing the issue.
