### ISSUE TITLE
AWS Subgenerator returns 404

### ISSUE THREAD

**Issue by ggotti** [jhipster/generator-jhipster#7520]
##### **Overview of the issue**
When the AWS Subgenerator successfully deploys an Application to AWS, the html page screen appears, but all services return a 404.

The issue is the WAR generated in the new JHipster 5.0x version does not have the [necessary SpringBootServletInitializer code](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-create-a-deployable-war-file) to allow the WAR to be scanned correctly by Tomcat; it appears that this functionality was previously in the "_ApplicationWebXml.java" file.

##### **Motivation for or Use Case**
Feature doesn't work.

##### **Reproduce the error**
- Generate a new monolothic project.
- Run the `jhipster aws` generator. Get a coffee.
- Navigate to the load balancer address, and then attempt to login.

##### **Related issues**
#7061, #7086, #7457 

##### **Suggest a Fix**
- Modify the [AWS generator to use Docker](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker.html), instead of the Tomcat based model.
- Reinstate the WAR startup code.
- Remove the AWS generator.

##### **JHipster Version(s)**

```
monday@0.0.0 /Users/gerard/Code/jhipster/demo/monday
└── generator-jhipster@5.0.0-beta.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.0",
    "baseName": "monday",
    "reactive": false,
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "aws": {
      "applicationName": "ggigliotti-mon",
      "environmentName": "ggigiotti-mon",
      "bucketName": "ggigliotti-mon-b",
      "instanceType": "t2.small",
      "awsRegion": "us-east-1",
      "dbName": "ggigliottiMon",
      "dbInstanceClass": "db.t2.small"
    }
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.16.2

node: v8.9.4

npm: 5.6.0

yeoman: 1.8.5

yarn: 1.5.1

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.20.1, build 5d8c71b

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Ok that's my fault - I had the idea that WARs were not used anymore, and that's still the case here. We should put the file back, it doesn't cost much and solves the issue.

**Comment by jdubois** [comment]
Thanks @ggotti this works now perfectly, following commit https://github.com/jhipster/generator-jhipster/commit/0269dae888b0487305129d4a5fdcb00b9dae3864
