### ISSUE TITLE
Log file not being populated

### ISSUE THREAD

**Issue by GuyJackson** [jhipster/generator-jhipster#7527]
##### **Overview of the issue**

Log file does not get populated when the example "production configuration" is uncommented in logback-spring.xml.

If I add re-introduce:

`<root level="${logging.level.root}"> <appender-ref ref="ASYNC"/> </root>`

...which looks like it was removed [here](https://github.com/jhipster/generator-jhipster/pull/6726), the log file gets populated. 

@PierreBesson mentioned this is not expected and might be a bug.

##### **Motivation for or Use Case**

Need to use files for logging.

##### **Reproduce the error**

Uncomment the example "production configuration" in logback-spring.xml.
Run the application.
Observe that a log file gets created but not populated.
Stop the application.
Add, at the bottom:
`<root level="${logging.level.root}"> <appender-ref ref="ASYNC"/> </root>`
Run the application.
Observe that the log file gets populated.

##### **Related issues**

#6726

##### **Suggest a Fix**

-

##### **JHipster Version(s)**

4.14

##### **JHipster Version(s)**

```
my-test-app@0.0.0 /srv/git/myTestApp
└── generator-jhipster@4.14.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.mta"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "myTestApp",
    "packageName": "org.mta",
    "packageFolder": "org/mta",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.7.4

node: v8.9.4

npm: 5.6.0

bower: 1.8.2

yarn: 1.3.2

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.19.0, build 9e633ef

**yo-rc.json:**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.mta"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "myTestApp",
    "packageName": "org.mta",
    "packageFolder": "org/mta",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "2d891c89b6531f4c312db9448fa537d1b6eac518",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no entities created.

##### **Browsers and Operating System**

Ubuntu 16.04.3 LTS

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
@GuyJackson Thank you for following through with the issue. Indeed this is not expected at all, I just did a quick check and I confirm the issue.
