### ISSUE TITLE
Can't fetch profile info in React client

### ISSUE THREAD

**Issue by agaspardcilia** [jhipster/generator-jhipster#7534]
##### **Overview of the issue**

#7050 Removed an endpoint that was providing the client some profile information.

##### **Motivation for or Use Case**

Profile aren't working anymore with React.

##### **Reproduce the error**

Create any kind of React application.

##### **Related issues**

None.

##### **Suggest a Fix**

Just call the new endpoint. We might need to add some more data in the new endpoint or make the client interpolate some translation keys to get the ribbon right.

##### **JHipster Version(s)**

Current master.

**Comment by PierreBesson** [comment]
It was not ! It's just that the trainees are working too fast !
@agaspardcilia You should now get profile data from the /info endpoint. Make sure that you upgrade the jhipster lib and you should be able to test it.
Otherwise I can do it.

**Comment by agaspardcilia** [comment]
@PierreBesson Are you sure it's working ?
The only thing answered by `http://localhost:8080/management/info` is:
```json
{
  "display-ribbon-on-profiles" : "dev"
}
```
Isn't that endpoint supposed to return something like: 
```json
{
  "display-ribbon-on-profiles" : "dev",
  "git" : {
    "commit" : {
      "id" : {
        "abbrev" : "92e2d29",
        "describe" : "92e2d29-dirty"
      }
    },
    "branch" : "master"
  },
  "build" : {
    "version" : "0.0.1-SNAPSHOT",
    "artifact" : "sb-2-t-2",
    "name" : "Sb 2 T 2",
    "group" : "com.mycompany.myapp",
    "time" : "2018-01-26T16:59:48Z"
  },
  "active-profiles" : [ "swagger", "dev" ]
}
```
? 
The ribbon is not being displayed in Angular too.

**Comment by PierreBesson** [comment]
@agaspardcilia Please update your JHipster lib to the latest master and make sur that your pom is using it.

**Comment by agaspardcilia** [comment]
Oh right, I forgot about that. Thank you.

**Comment by PierreBesson** [comment]
It will get easier once @jdubois will do a release of the lib :smiley:.
