### ISSUE TITLE
Constraint name with 31 characters - Oracle

### ISSUE THREAD

**Issue by danielmenezesbr** [jhipster/generator-jhipster#7537]
##### **Overview of the issue**

JHipster generates constraint name with 31 characters on Oracle.
[](url)
Although the [generator says it will be truncate constraint name to 30 characters](https://gist.github.com/danielmenezesbr/c4839f6db0b9e608da745c784f50463e#file-jhispter_log-L605), it generates a constraint name with [31 characters](https://github.com/danielmenezesbr/jhipster_oracle_limits_and_skipclient/blob/master/src/main/resources/config/liquibase/changelog/20180425143957_added_entity_constraints_NucleoEtapaSubtipoProcesso.xml#L13) on **Oracle**.

I imported [this JDL](https://github.com/danielmenezesbr/jhipster_oracle_limits_and_skipclient/blob/master/model.jh).

##### **Reproduce the error**
I put steps to reproduce [here](https://gist.github.com/danielmenezesbr/c4839f6db0b9e608da745c784f50463e) and [here](https://github.com/danielmenezesbr/jhipster_oracle_limits_and_skipclient)

##### **Suggest a Fix**

Truncate constraint name to 30 characters.

##### **JHipster Version(s)**
v4.14.3

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by GuiF007** [comment]
I got this problem too as I'm working with Oracle right now ! Painful when Oracle refuses the changelog :(

**Comment by pascalgrimaud** [comment]
Strange ! According to this code, it shouldn't happen: https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L1949-L1963

Here some recent ticket / PR, so you can have a look:
- https://github.com/jhipster/generator-jhipster/issues/7070
- https://github.com/jhipster/generator-jhipster/pull/7323

**Comment by ruddell** [comment]
@pascalgrimaud It truncates it, but there's one too many characters.  That also explains that weird failing test https://github.com/jhipster/generator-jhipster/pull/7489 because `test_many_rel_with_pagination_a_test_many_rel_with_pagination__id` is 65 and mysql's limit is 64

**Comment by pascalgrimaud** [comment]
lol !!! I spend 1 night on this, and I thought it was because the entity name was too long !
I will become crazy with this :D

**Comment by GuiF007** [comment]
OK, I found the problem...

https://github.com/jhipster/generator-jhipster/blob/5b5d4ff8e1efbab389bf4741c157f6d75ad97c75/generators/generator-base.js
```
    getConstraintName(entityName, relationshipName, prodDatabaseType, noSnakeCase) {
        let constraintName;
        if (noSnakeCase) {
            constraintName = `fk_${entityName}_${relationshipName}_id`;
        } else {
            constraintName = `fk_${this.getTableName(entityName)}_${this.getTableName(relationshipName)}_id`;
        }
        let limit = 0;

        if (prodDatabaseType === 'oracle' && constraintName.length > 30 && !this.skipCheckLengthOfIdentifier) {
            this.warning(`The generated constraint name "${constraintName}" is too long for Oracle (which has a 30 characters limit). It will be truncated!`);

            limit = 28;
        } else if (prodDatabaseType === 'mysql' && constraintName.length > 64 && !this.skipCheckLengthOfIdentifier) {
            this.warning(`The generated constraint name "${constraintName}" is too long for MySQL (which has a 64 characters limit). It will be truncated!`);

            limit = 62;
        }
        if (limit > 0) {
            const halfLimit = Math.floor(limit / 2);
            const entityTable = noSnakeCase ? entityName.substring(0, halfLimit) : _.snakeCase(this.getTableName(entityName).substring(0, halfLimit));
            const relationTable = noSnakeCase ? relationshipName.substring(0, halfLimit - 1) : _.snakeCase(this.getTableName(relationshipName).substring(0, halfLimit - 1));
            return `${entityTable}_${relationTable}_id`;
        }
        return constraintName;
```
EntityTable.length with noSnakeCase : 14
RelationTable.length wih noSnakeCase : 13
return 14+1+13+3 = 31 !
 
And even worse with Snakecase I think.

**Comment by pascalgrimaud** [comment]
Hope, this PR should fix this: https://github.com/jhipster/generator-jhipster/pull/7545

**Comment by GuiF007** [comment]
Well, It doesn't for sure if noSnakeCase is not false...

_.snakeCase('fooBar');
// => 'foo_bar'

6 characters become 7 ! (But I did not check all the code, maybe my case is not applicable here)
