### ISSUE TITLE
Can't read swagger JSON from http://localhost:9000/app/v2/api-docs

### ISSUE THREAD

**Issue by majiajue** [jhipster/generator-jhipster#7539]
##### **Overview of the issue**
When I create MicroService app and gateway,registry,uaa, I can see gateway api and uaa api,

![image](https://user-images.githubusercontent.com/128642/39282977-65474344-493e-11e8-8e5b-88020952d717.png)
![image](https://user-images.githubusercontent.com/128642/39283145-6d3fe8c0-493f-11e8-8ca4-09bb8391fd11.png)
when select app api
![image](https://user-images.githubusercontent.com/128642/39283167-957090c4-493f-11e8-920b-c16d729a34ee.png)

##### **JHipster Version(s)**
 4.14.3

##### **JHipster configuration**

app configuration

##### **JHipster Version(s)**

```
first@0.0.0 D:\csair_work\api-demo
`-- generator-jhipster@4.14.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.csair.b2c.service.first"
    },
    "jhipsterVersion": "4.14.3",
    "baseName": "first",
    "packageName": "com.csair.b2c.service.first",
    "packageFolder": "com/csair/b2c/service/first",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "csairuaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.16.1.windows.1

node: v6.9.5

npm: 5.8.0

gulp:
[10:52:19] CLI version 2.0.0

yeoman: 2.0.1

yarn: 1.5.1

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.20.1, build 5d8c71b2

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Kelvin-Meyer** [comment]
I got the same problem:
Addions:
**Environment and tools**
This also seems to affect:
 java version "1.8.0_171"
node v9.11.1|
npm v 5.6.0 and 6.0.0
yeoman 2.0.2
yarn 1.6.0
docker 18.003.1-ce build 9ee9f40

**Browsers and Operation Sytem**
Does not seem to matter
Latest: Chorme / Firefox / IE  
Windows 10 64 bit

**Comment by ruddell** [comment]
Are you sure you gave enough time for the application to start, register with the JHipster registry, then for the gateway to refresh the routes?  You can verify that the ribbon path is available by looking at http://localhost:9000/#/admin/gateway  I can't reproduce the issue you are having.  But I do see https://github.com/jhipster/generator-jhipster/issues/7185 which would block this from working anyway.

**Comment by ruddell** [comment]
Looking at this again, you don't have any entities so the microservice path has not been added to your `yarn` proxy config.  You can add this manually or generate an entity which will add the microservice path for you [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/react/webpack/webpack.dev.js.ejs#L64).  

There's no way for the gateway to know about microservices until you generate an entity, so I don't think there's anything we can do on our end.

**Comment by mueller-fr** [comment]
We saw the same error on the WebUi. And it was because of the property ´SPRING_PROFILES_ACTIVE´ which was set to `prod` instead of `prod,swagger` in the deployment configuration (`docker-compose.yml` or for kubernetes deployment `api-deployment.yml`, ...).
The default for this property is `prod,swagger`, so if you do not set it at all, the api is visible, too.
