### ISSUE TITLE
about code-splitting in the React project

### ISSUE THREAD

**Issue by Yangzhedi** [jhipster/generator-jhipster#7540]
I'm afraid we don’t have code-splitting feature in the project.

I hope it can use [react-loadable](https://github.com/jamiebuilds/react-loadable) to make code splitting simple

there is the example 

I make the Register Component with dynamic imports
```
const Register = Loadable({
  loader: () => import('app/modules/account/register/register'),
  loading: () => <div>loading ...</div>
});
```

![first](http://cdn.blog.yangzhedi.com/jhipster/jhipster.png)

![second](http://cdn.blog.yangzhedi.com/jhipster/jhipster2.jpg)

**Comment by deepu105** [comment]
PR merged

**Comment by deepu105** [comment]
Entity modules can also be easily lazy loaded with same approach
