### ISSUE TITLE
Neo4j

### ISSUE THREAD

**Issue by yuniel-acosta** [jhipster/generator-jhipster#7543]
I need to know if in the future there will be the possibility of using Neo4j in JHipster.

**Comment by pascalgrimaud** [comment]
Look at the old ticket: https://github.com/jhipster/generator-jhipster/issues?utf8=%E2%9C%93&q=neo4j
There is an old repo https://github.com/jhipster/jhipster-neo4j-app too

But as already discussed, we won't support it.
