### ISSUE TITLE
jhi_social_user_connection table script dosent work on mySQL because of RANK column

### ISSUE THREAD

**Issue by pravinkhandke** [jhipster/generator-jhipster#7568]
##### **Overview of the issue**
  Using Jhipster to generate the monolithic application with spring  Social functionality on MySQL database.  After generation of application if you configure and run then it does not work because of jhi_social_user_connection and rank column which is a MySQL keyword/ function. 
 

##### **Motivation for or Use Case**
  This is the defect in the fix we need to change table name of jhi_social_user_connection from rank to some other name. if we change it to other it works fine.   I am using MySQL 8.0.11. It gives following error.

Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank BIGINT NOT NULL,
   display_name VARCHAR(255) NULL,
   profile_url VARCHAR(' at line 7
SQLState:  42000
ErrorCode: 1064

##### **Reproduce the error**
Generate application for MySQL with spring social functionality and try to execute in eclipse. Please use MySQL 8  

##### **Suggest a Fix**
rename rank column of jhi_social_user_connection to user_rank

rename rank column of jhi_social_user_connection to user_rank
##### **JHipster Version(s)**

This is not regression. I am using v4.14.3
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I guess this is a new keyword in MySQL? Because I've used that for years without this issue... Do you  have some explanation here?
Anyway we are removing social login in JHipster 5, and I don't think there will many people ready to do maintenance on JHipster 4, so I can't guarantee this will be fixed. Would you be ready to do a PR?

**Comment by ruddell** [comment]
MySQL 8 brings in a new set of reserved words that we need to add to the list https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-in-current-series

**Comment by jdubois** [comment]
Oh sorry I missed that, thanks @ruddell 
Indeed, we don't support MySQL 8 at the moment - not sure when we should migrate, I guess very few people have already done it.

**Comment by pravinkhandke** [comment]
social login was the important to feature of JHipster.

**Comment by jdubois** [comment]
Yes it's not maintained any more on the Spring side, so we can't support it either. We also have better and easier options now, like using Keycloak/Okta,or even OAuth2 directly.

**Comment by pravinkhandke** [comment]
Thanks a lot. Can we connect to Facebook and Google with  JHipster 5?

**Comment by ruddell** [comment]
@pravinkhandke Yes here's a [link to the tip](https://www.jhipster.tech/tips/024_tip_enabling_social_login_with_oauth2.html) that explains how to enable it

**Comment by ruddell** [comment]
I don't have the time to test, but you should be able to set the `name` in the `@Column` annotation on the `rank` field and change the liquibase initial_changelog to match the name you choose.  By default I'd use `jhi_rank`.

I opened a PR in jhipster-core adding MySQL 8's reserved words.
