### ISSUE TITLE
LocalDates in entity create and update are altered by moment js 

### ISSUE THREAD

**Issue by Belkacem** [jhipster/generator-jhipster#7569]
##### **Overview of the issue**

In entity edit and create pages generated by jhipster, the dates are transformed to json witch converts the date to the local locale, here's a debugger code : 
The date goes in may 3rd and transforms into may 2nd 

![image](https://user-images.githubusercontent.com/419224/39640754-4e2a4186-4fcc-11e8-9a07-17c8e56e1dd8.png)

##### **Reproduce the error**

Create an entity with LocalDate field.
go to creation page and crete a new one, the date will be never the one saved :)

##### **Suggest a Fix**

get rid of moment JS 😄 

##### **JHipster Version(s)**

5,0,0-beta1

**Comment by Belkacem** [comment]
I Have similar error in the Edit page for entities that have fields of type Instant.

**Comment by hdurix** [comment]
I reproduce the error with `LocalDate` (wrong day), thanks!

But I don't notice any error with `Instant`: the instant is saved then displayed correctly. Could you explain how to reproduce?

**Comment by Belkacem** [comment]
it's saved and displayed correctly, but if you edit it (keeping the hour at midnight) the instant will be saved at 22h00 the day before.

**Comment by Belkacem** [comment]
Is it possible to get rid of moment.js ? it's adding weight to the bundle size and it's not used frequently.

**Comment by jdubois** [comment]
I didn't follow this closely, but it looked like a highlight of the latest beta release, and I thought people were happy about it as it's the most popular date handling library. I'm quite disappointed if it causes issues and if you dislike it :-(

**Comment by hdurix** [comment]
Indeed the lib is not used a lot when the app is generated.
But I find it very useful as soon as you have some dates to handle in your app (more than CRUD I mean), I used to add it whenever I was creating a new JHipster project.

**Comment by Belkacem** [comment]
In my opinion it’s better to leave the choice to the développer to include it or not, as momentjs adds 250k to the bundle(uncompressed)

**Comment by Tcharl** [comment]
Hi,

DateTime Picker should work as usual as it's the same mecanism used:

- In the update dialog, a string attribute is created for each date in the component

- The Datetime picker manipulates this string to update date

- In the save() method of the component, we create a moment from that string and affect it to the attribute.

BTW, I'm really enjoying moment.js within my project where every entity has a date, also, I really don't like any angular attribute typed with 'any' and hunt it every day as it's more difficult to maintain in time
: may be we could fix that time shifting issue and provide a module to switch the previous behavior?

**Comment by Belkacem** [comment]
Moment is an overkill for this usage, if the "any" type is an issue we can define a date type and use it.

**Comment by jdubois** [comment]
For me this is solved by https://github.com/jhipster/generator-jhipster/pull/7584 but I'm not the best expert on this part - so I'm closing this but the comments are still opened, please discuss if that doesn't suit you and I'll re-open

**Comment by Belkacem** [comment]
Hi,
Here's the problem that moment causes in a project with webpack:  
https://github.com/webpack/webpack/issues/3128

The moment team couldn't resolve this problem, and sought help, the webpack team created the following plugin : 


plugins: [
    new webpack.ContextReplacementPlugin(/moment[\\\/]locale$/, /^\.\/(en|ko|ja|zh-cn)$/)
]


There another date library that is very compact and useful : 
https://github.com/date-fns/date-fns

Cheers
