### ISSUE TITLE
react client active checkbox broken in user-management

### ISSUE THREAD

**Issue by mohctp001** [jhipster/generator-jhipster#7572]
"jhipsterVersion": "5.0.0-beta.1"

##### **Overview of the issue**

When installing 5.0.0-beta.1 gateway with react the web client is broken in the admin / management section for updating a user.

##### **Motivation for or Use Case**

This is core functionality that should be fixed

##### **Reproduce the error**

1) load page: http://127.0.0.1:8080/#/admin/user-management
2) select edit for a user, which takes you to: http://127.0.0.1:8080/#/admin/user-management/user/edit
3)the Activated checkbox is always unchecked.  So when editing an Activated user and then clicking save the user is deactivated.
##### **Suggest a Fix**

in user-management-update.tsx.ejs

update line 196 

from: `<AvInput type="checkbox" name="activated" />`
to: `<AvInput type="checkbox" name="activated" value={user.activated} />`

##### **JHipster Version(s)**

v5 with react
##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Could you follow the guidelines and also post your `jhipster info` information here? This is to be sure we can easily reproduce

**Comment by BhawaniSingh** [comment]
@jdubois React is not my strong point, but I think I got the issue what @mohctp001 trying to refer
[user-management-update.tsx.ejs](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs#L196), ``` value={user.activated} ``` is missing. Because of which ```user.activated=false``` is getting saved when ever he is trying to edit & save the user.

**Comment by mohctp001** [comment]
Sorry, I am new to submitting requests on git like this.  I usually consume projects, but I really like jhipster and react, so I'm hoping to contribute.

I think I have done this correctly to submit the change request.

https://github.com/jhipster/generator-jhipster/pull/7573
