### ISSUE TITLE
Feature request - util class for query specification

### ISSUE THREAD

**Issue by Blackdread** [jhipster/generator-jhipster#7574]
##### **Motivation for or Use Case**

Allow to have specification for:
- joins of more than 1 entity => A -> B -> C or A -> B -> C -> D or etc
- filter not only on foreign keys when using join/get

Reason is it can be necessary to filter controllers result when calling "getAll(criteria, pageable)" but data to filter is not part of the first and second entity (or not the fk) but in the third/fourth/etc.
In order make it work, we also need to modify generated criteria and add another filter then modify the XXXXQueryService for that entity and build the specification.
For example I allow any user to call "getAll(...)" but I force some criterias values to be within an allowed given range of values based on user role (throw exception or override some criteria values).
Without this feature it is necessary add to the criteria a IN filter to make sure that only those can be seen but it should be used only for IN where its size is low (never for more 1000/10000/etc).

Another point to talk about is "[database NF design](https://en.wikipedia.org/wiki/Database_normalization)" (3NF in that matter), to "solve" this issue, user could duplicate its business logic into the entity itself so he would be able to filter on it without 2/3/4/etc joins but this is very bad design.
Except for foreign keys that **never** change but that's another point of view and not everybody would agree on this one.
For example:
We have 5 entities: user, userProfile, company, post, postComment
Let's suppose we want to filter postComment only by a given company but this information is in userProfile (a user have one userProfile and userProfile has one company). It would require 3 to 4 join in order to filter on the company.
If companyId is duplicated across different entities like in post or even postComment, the number of joins can be reduced to 0 or 1 (if the business logic of this application is: if a post is created by an user, the post is own by the current company of the user, and if user changes of company later the post ownership stays unchanged), but we are breaking the 3NF (but I would argue that in some business logic, this can be better to do that -> only if company value will **never** change in post and postComment -> so once a post is created, it is own by the company and never other company but eventually the user could change of company and so it would not be able to see post (and associated postComment) from his previous company).
If a user decide to duplicate some values like companyId then there is no need for this feature otherwise it is required.
Hope this example was clear, from the business logic given before there would be a companyId in the Post entity. And if design programmer decide to "simplify" the filtering he could also duplicate companyId in postComment but it breaks the 3NF.

##### **Reproduce the error**

No error

##### **Related issues**

No related issues

##### **Suggest a Fix**

Either put more methods in QueryService but it will make it very big so instead, could put in a QueryUtil class.
I give an example of code, method names are not final, this is just a demonstration purpose.

```
    /*
     * For a relation: A -> B -> C where U is the fk of B (so value inside table B) we will get one inner join and a where b.c_id = ... (good, we skip a join)
     * For a relation: A -> B -> C where U is a column of C (so value not inside table B) we will get one inner join, a cross join and a where with cross join comparison and c.column_name = ... <- not very good but that's where method joinAndFinalGet can fix that
     */
    public static <U, ENTITY1, ENTITY2, ENTITY3> Specification<ENTITY1> joinAndGet(Filter<U> filter, SingularAttribute<ENTITY1, ENTITY2> e1, SingularAttribute<ENTITY2, ENTITY3> e2, SingularAttribute<ENTITY3, U> e3) {
        // only put equals but it can be similar code of buildSpecification/buildReferringEntitySpecification
        return (root, query, builder) -> builder.equal(root.join(e1).get(e2).get(e3), filter.getEquals());
    }
    public static <U, ENTITY1, ENTITY2, ENTITY3> Specification<ENTITY1> joinAndGetEquals(U value, SingularAttribute<ENTITY1, ENTITY2> e1, SingularAttribute<ENTITY2, ENTITY3> e2, SingularAttribute<ENTITY3, U> e3) {
        return (root, query, builder) -> builder.equal(root.join(e1).get(e2).get(e3), value);
    }
```

```
    /*
     * For a relation: A -> B -> C where U is the fk of B (so value inside table B) we will get two inner join and a where c.column_name = ... (good as well, we just get 2 inner join)
     * For a relation: A -> B -> C where U is a column of C (so value not inside table B) we will get two inner join and a where c.column_name = ... (similar to fk)
     *
     */
    public static <U, ENTITY1, ENTITY2, ENTITY3> Specification<ENTITY1> joinAndFinalGet(Filter<U> filter, SingularAttribute<? super ENTITY1, ENTITY2> e1, SingularAttribute<? super ENTITY2, ENTITY3> e2, SingularAttribute<ENTITY3, U> e3) {
        // only put equals but it can be similar code of buildSpecification/buildReferringEntitySpecification
        return (root, query, builder) -> builder.equal(root.join(e1).join(e2).get(e3), filter.getEquals());
    }
    public static <U, ENTITY1, ENTITY2, ENTITY3> Specification<ENTITY1> joinAndFinalGetEquals(U value, SingularAttribute<? super ENTITY1, ENTITY2> e1, SingularAttribute<? super ENTITY2, ENTITY3> e2, SingularAttribute<ENTITY3, U> e3) {
        return (root, query, builder) -> builder.equal(root.join(e1).join(e2).get(e3), value);
    }
```

- [x] Checking this box is mandatory (this is just to show you read everything)

@gzsombor 

To help criteria creation I have a util class "CriteriaUtil" with methods like:
```
    public static LongFilter buildEqualsCriteria(@NotNull final Long value) {
        return buildEqualsCriteria(new LongFilter(), value);
    }

    public static LongFilter buildEqualsCriteria(@Nullable final LongFilter criteriaPassed, @NotNull final Long value) {
        if (value == null)
            throw new IllegalArgumentException("Value param cannot be null");

        final LongFilter criteria = criteriaPassed == null ? new LongFilter() : criteriaPassed;
        criteria.setEquals(value);
        return criteria;
    }

   public static BooleanFilter buildEqualsCriteria(@NotNull final Boolean value) {
        return buildEqualsCriteria(new BooleanFilter(), value);
    }

   /*
    * Other methods ommited (string, etc), buildInCriteria, etc
    * Other methods to throw or override if a filter is not null and contains values not authorized
    * etc
    */
```

EDIT: I can do a pull request on jhipster/jhipster to add QueryUtil and CriteriaUtil

**Comment by BhawaniSingh** [comment]
I did something. Like this in my one of my project

**Comment by Blackdread** [comment]
I created a branch to show small part of what CriteriaUtil class could look like: [add-util-query-and-criteria](https://github.com/Blackdread/jhipster/tree/add-util-query-and-criteria).
I create and push later QueryUtil it jhipster team thinks these both classes can be useful. It can remove a lot of implementations for users that want to do similar things (CriteriaUtil and QueryUtil).

**Comment by gzsombor** [comment]
My original idea to use lambdas to simplify the situation.
For example, we can add the 'genericEqualsSpecification method, and with this, we can deprecate the current equalsSpecification/equalsSetSpecification :

```
    /**
     * Generic method, which based on a Root&lt;ENTITY&gt; returns an Expression which type is the same as the given 'value' type. 
     * @param metaclassFunction
     * @param value
     * @return
     */
    protected <X> Specification<ENTITY> genericEqualsSpecification(Function<Root<ENTITY>, Expression<X>> metaclassFunction, final X value) {
        return (root, query, builder) -> builder.equal(metaclassFunction.apply(root), value);
    }

    /**
     * @deprecated Just call the genericEqualsSpecification(root -> root.get(reference).get(valueField), value)
     */
    @Deprecated
    protected <OTHER, X> Specification<ENTITY> equalsSpecification(
            SingularAttribute<? super ENTITY, OTHER> reference, 
            SingularAttribute<? super OTHER, X> valueField, 
            X value) {
        return genericEqualsSpecification( root -> root.get(reference).get(valueField), value);
    }

    /**
     * @deprecated Just call the genericEqualsSpecification(root -> root.join(reference).get(valueField), value) 
     */
    @Deprecated
    protected <OTHER, X> Specification<ENTITY> equalsSetSpecification(SetAttribute<? super ENTITY, OTHER> reference,
        SingularAttribute<OTHER, X> idField,
        X value) {
        return genericEqualsSpecification( root -> root.join(reference).get(idField), value);
    }

```

With this, you can easily extend to build your query through multiple layers:
   genericEqualsSpecification( root -> root.join(reference1).join(reference2).get(idField), value);

And do the same with all the other query builder methods.

What do you think?

**Comment by Blackdread** [comment]
I think is good but there might be still an issue in it.
Functions like below (at end of the comment) do the logic for a given filter but only works for SingularAttribute and require lot of code to be able to have a PluralAttribute for first, then second then third or second and third, etc (all combination).

I will find a way to pass the builder expression via arguments to a buildReferringEntitySpecification without requiring to pass all builder expression of each if/else inside buildReferringEntitySpecification method.
And also would be good that the solution is within a single line like:

```specification = specification.and(QueryUtil.buildReferringEntitySpecification(criteria.getCompanyId(), MyObject_.field, MyObject2_.field, OtherObject_.company, Company_.id));```

Otherwise it will make sub-classes of QueryService with too much repeated code in each "createSpecification" method.

I did not check yet but with the "metaclassFunction" and value, it should possible to get rid of the 4 SingularAttribute below. I try later (maybe this week-end)

```
    public static <ENTITY, ENTITY2, ENTITY3, ENTITY4, X> Specification<ENTITY> buildReferringEntitySpecification(
        Filter<X> filter,
        SingularAttribute<? super ENTITY, ENTITY2> reference,
        SingularAttribute<? super ENTITY2, ENTITY3> reference2,
        SingularAttribute<? super ENTITY3, ENTITY4> reference3,
        SingularAttribute<ENTITY4, X> valueField) {
      ...
    }
```

**Comment by gzsombor** [comment]
I have some free time, and try to put together my idea and create a pull request in this evening. Stay tuned :wink:

**Comment by gzsombor** [comment]
The javadoc is not the best, there are tons of warning because of missing stuff, however it seem to be a compiling and working implementation, which can be extended.

**Comment by Blackdread** [comment]
The code looks good and should work, when I have time I will try it with an application (and join with more than 2/3 tables then filter on a field different than the fk of the join chain).
Maybe only need to put javadoc and should be good to merge as it does not break existing code, old methods are kept with @Deprecated annotation.
Can you add a method to overload the "buildSpecification" method by passing a RangeFilter so it will fix issue #7195 (it is solution 3 in fact which I did put)

**Comment by gzsombor** [comment]
I've modified the code, to have a "buildSpecification" methods with various Filter classes as parameters, so you don't have to remember, how it's actually named, and overloading works as expected.

**Comment by Blackdread** [comment]
I think can close this issue since #97 is merged. CriteriaUtil is an opinionated implementation, anyone can decide by himself.

**Comment by khodabandelu** [comment]
@Blackdread please give me example of this issue.
i dont know how to have ( joins of more than 1 entity) in my spescification and whats method and signature i should use.

**Comment by agallo73** [comment]
> I've modified the code, to have a "buildSpecification" methods with various Filter classes as parameters, so you don't have to remember, how it's actually named, and overloading works as expected.

hello can you pèlease share the code also with me? I did not realize how is possible to create the join list at runtime. Are you using the lambda function or what else?

**Comment by DanielFran** [comment]
@agallo73 You have some examples available here: https://github.com/jhipster/jhipster-sample-app-vuejs/blob/main/src/main/java/io/github/jhipster/sample/service/BankAccountQueryService.java#L49

This use [generic methods](https://github.com/jhipster/jhipster-bom/blob/main/jhipster-framework/src/main/java/tech/jhipster/service/QueryService.java) from jhipster-bom project
