### ISSUE TITLE
Why node_modules and other front-end files got generated for --skip-client flag?

### ISSUE THREAD

**Issue by yatendragoel** [jhipster/generator-jhipster#7585]
##### **Overview of the issue**

I created a new JHipster project with the following command:

    jhipster --skip-client

Since, I skipped client generation via `--skip-client`, why the newly created project contains the following files and folders which I think are related to frontend and not related to backend anywhere:

 - node_modules
 - package.json
 - .yo-rc.json
 - yarn.lock

**Comment by ruddell** [comment]
The purpose of installing a local copy of `generator-jhipster` is that if you upgrade your global version, the local version will still match what your project uses.  This protects you from using a newer entity generator on an older project. You can skip the installation of the local `generator-jhipster` by using `--skip-install` (note that your project will then always use the global `generator-jhipster`)

The `.yo-rc.json` file has the answers to your prompt and other details about your project that help with the other subgenerators such as `entity` or `import-jdl`.  This file is important to keep.

**Comment by yatendragoel** [comment]
@ruddell That makes sense.

1. Does that mean we should check-in `node_modules` in our source repository (`git` in our case) as well? I see that the generated `.gitignore` file excludes `node_modules` folder

2. It seems like `--skip-install` would not be a good idea then because inconsistency in *generator* versions can lead to more incompatible code. Am I right?

**Comment by yatendragoel** [comment]
Since now I understand that this was actually not a bug, but rather a feature, I am closing this issue.
