### ISSUE TITLE
Upgrade to Spring Boot 2.0.2.RELEASE and 1.5.13.RELEASE

### ISSUE THREAD

**Issue by henri-tremblay** [jhipster/generator-jhipster#7591]
##### **Overview of the issue**

Many CVE fixed

##### **Motivation for or Use Case**

You know... security and stuff again.

##### **Reproduce the error**

NA

##### **Related issues**

NA

##### **Suggest a Fix**

Upgrade the Spring boot version

##### **JHipster Version(s)**

4.14.3
5.0.0-beta-1

##### **JHipster configuration**

NA

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

NA

##### **Browsers and Operating System**

NA

**Comment by DanielFran** [comment]
@jdubois I implemented the changes for both branches, just waiting tests to confirm all is OK!
