### ISSUE TITLE
OAuth2: selecting elasticsearch/mongodb causes unit tests to fail

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7605]
##### **Overview of the issue**

When choosing elasticsearch as an option, `mvn test` fails.

##### **Motivation for or Use Case**

This didn't happen with JHipster 4.x.

##### **Reproduce the error**

Create a microservices app with the following `.yo-rc.json`, then run `./mvnw test`:

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer.store",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "store",
    "packageName": "com.okta.developer.store",
    "packageFolder": "com/okta/developer/store",
    "serverPort": "8082",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "80b1ded70f6c52da473e8a9b24ceeb5bed727e74",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

##### **Related issues**

I'm sure this is related to the fact that Elasticsearch is no longer embeddable, but we should provide a way to run tests w/o requiring an Elasticsearch instance to be running.

##### **Suggest a Fix**

Mock out Elasticsearch repositories so there's no call made.

##### **JHipster Version(s)**

I'm using the `master` branch, and I've seen this with 5.0 beta 1.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer.store",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "store",
    "packageName": "com.okta.developer.store",
    "packageFolder": "com/okta/developer/store",
    "serverPort": "8082",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true,
    "herokuDeployType": "git",
    "herokuAppName": "okta-store"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Product (product) {
  name String required,
  price Double required min(0),
  image ImageBlob
}
paginate Product with pagination
search Product with elasticsearch
microservice Product with store

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.1

node: v9.8.0

npm: 6.0.0

yeoman: 2.0.2

yarn: 1.6.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 5a3f1a3

**Comment by Tcharl** [comment]
Hi @mraible ,

Using the 5.0.0-beta.0 version, elastic search repositories  are mocked in integration tests (mocks are located in src/test/java/.../repository/search
It looks like it is the same for beta.1 (I'm currently migrating a project regenerating jdl and see no difference).

Regards

**Comment by jdubois** [comment]
Oh yes there is a big change here, as we can't run embedded Elasticsearch anymore (what a bad decision this is for us!!)

**Comment by pascalgrimaud** [comment]
In fact, this ticket has 2 issues:
- oauth2 + elasticsearch: fixed by https://github.com/jhipster/generator-jhipster/pull/7619
- oauth2 + mongodb

I solved one.
