### ISSUE TITLE
Expose /management/env again when Spring Boot 2.0.3 is released

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7606]
We need to migrate JHipster 5 to Spring Boot 2.0.2 because it corrects several CVEs.

This causes JHipster applications to fail starting because of https://github.com/spring-cloud/spring-cloud-commons/issues/367

-> the solution is to stop exposing the "/env" management endpoint. The application will start, but then we will have missing data in our "configuration" screen.

This is bad, but not as bad as having CVEs or a non-starting application :-)

I will link the commit removing the "/env" endpoint to this ticket, and this will need to reverted as soon as Spring Boot 2.0.3 is released, as the fix is already committed in the Spring Boot repo.

**Comment by jdubois** [comment]
Be careful there are 2 commits to rollback here

**Comment by DanielFran** [comment]
@jdubois, seems the fix has been included in Finchley-RC2, so upgrading to latest jhipster version should be OK?

**Comment by jdubois** [comment]
Oh let me test this!

**Comment by jdubois** [comment]
Indeed, thanks @DanielFran for pointing this out!

I'm fixing this ASAP

**Comment by pascalgrimaud** [comment]
@jdubois : we have this error in Travis builds for Gradle:

```
* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve io.github.jhipster:jhipster-framework:2.0.6.
  Required by:
      project :
   > Could not resolve io.github.jhipster:jhipster-framework:2.0.6.
      > Could not get resource 'https://jcenter.bintray.com/io/github/jhipster/jhipster-framework/2.0.6/jhipster-framework-2.0.6.pom'.
```

There is no `2.0.6` version here: https://jcenter.bintray.com/io/github/jhipster/jhipster-framework/
Is there something wrong ?

**Comment by jdubois** [comment]
Oh that's  me yesterday, I knew I broke the build... then 2.0.6 should be released and synced, it's on Maven Central - I don't why it's not on jcenter, I don't  know how the Gradle guys do it but they should be in sync with Maven Central

**Comment by pascalgrimaud** [comment]
It's correctly release here:
- https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.github.jhipster%22%20AND%20a%3A%22jhipster-dependencies%22

But no sync for jcenter. Strange! Maybe just wait

**Comment by jdubois** [comment]
As it's stuck since yesterday I'm contacting the JFrog support

**Comment by jdubois** [comment]
Oh I got an answer saying that we can't get support as we are not active customers :-(

**Comment by pascalgrimaud** [comment]
Another something strange:
- the link with 2.0.6
- the version inside: 2.0.5

The link: https://repo.maven.apache.org/maven2/io/github/jhipster/jhipster-framework/2.0.6/jhipster-framework-2.0.6.pom

If you look inside, there is: 
```
<parent>
<groupId>io.github.jhipster</groupId>
<artifactId>jhipster-dependencies</artifactId>
<version>2.0.5</version>
<relativePath>../jhipster-dependencies/pom.xml</relativePath>
</parent>
<artifactId>jhipster-framework</artifactId>
<packaging>jar</packaging>
```

**Comment by jdubois** [comment]
I have no idea how we got that wrong pom.xml -> see https://github.com/jhipster/jhipster/blob/2.0.6/jhipster-framework/pom.xml#L8 it's correct!! OK let's try 2.0.7

**Comment by jdubois** [comment]
Release 2.0.7 has been done 7 hours ago, and it's still not on Maven Central or JCenter - this all seems quite broken at the moment!

**Comment by pascalgrimaud** [comment]
finally out !
https://repo.maven.apache.org/maven2/io/github/jhipster/jhipster-framework/2.0.7/jhipster-framework-2.0.7.pom

**Comment by jdubois** [comment]
And 2.0.6 never made it to jcenter! WTF...

**Comment by pascalgrimaud** [comment]
yes, I don't understand:
https://jcenter.bintray.com/io/github/jhipster/jhipster-framework/

**Comment by jdubois** [comment]
It's just buggy... and as we can't open a support ticket we're stuck.
