### ISSUE TITLE
Cannot login when using Gateway + React + OAuth2

### ISSUE THREAD

**Issue by chrisdns** [jhipster/generator-jhipster#7609]
##### **Overview of the issue**

When trying to log in, the `authentication/GET_SESSION` call does not succeed.
The browser console shows the following message :
```
authentication/GET_SESSION caught at middleware with reason: "path.split is not a function".
TypeError: path.split is not a function
```

##### **Reproduce the error**

Generate a project with Gateway + React + OAuth2, launch keycloak and try to log in, it should not work

##### **Suggest a Fix**

It may have something to do with the last React header refactor.

##### **JHipster Version(s)**

Current master

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/alexandregc/repos/microservices/gateway
└── generator-jhipster@5.0.0-beta.1  -> /home/alexandregc/repos/generator-jhipster extraneous

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en",
      "microservicePath": "/home/alexandregc/repos/microservices/ms2"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.17.0

node: v8.11.1

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.6.0

Docker version 17.12.1-ce, build 7390fc6

docker-compose version 1.17.1, build unknown

##### **Browsers and Operating System**

Firefox, Ubuntu 18.04

**Comment by pascalgrimaud** [comment]
Closing this, as it seems resolved :)
