### ISSUE TITLE
Feature request: Rich text/WYSIWYG editor 

### ISSUE THREAD

**Issue by gomesp** [jhipster/generator-jhipster#7620]
##### **Overview of the issue**

Feature request: Could we please consider adding a new type of input field? Instead of a plain string, could we add a WYSIWYG input field (e.g. http://textangular.com/). 

I am not sure if this is still supported (the last commit is from 2016) and also need to find out a solution for react, but is it worth adding to the project core? Or is this something that belongs to the marketplace?

##### **Motivation for or Use Case**

Not every string field is a simple 1-liner text input field. :)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
There’s the TextBlob field type which uses a textarea in place of text input and allows longer values.  I’ve used a wysiwyg with that in one of my projects.  I’m not sure if TextBlob is implemented for react yet (on mobile so can’t easily look)

**Comment by jdubois** [comment]
Anyway we have nearly 50 opened tickets, we just don't have the bandwidth to do this at the moment

**Comment by gomesp** [comment]
Thanks for the feedback @ruddell and @jdubois. While I appreciate how busy you're, I believe this would be a great feature request for a first time OSS contributor if tagged like that. 

I am thinking of submitting more PRs to the project myself, and would love the chance to work around the edges to begin with, i.e. on issues like this one. 

I decided to submit a feature-request beforehand to gauge the interest from the core developers before spending any real effort on it.

**Comment by jdubois** [comment]
Oh sorry @gomesp - yes if you are ready to do the PR it's totally different, that doesn't take any bandwidth on our side. Unless we all fight on the rich text editor, which hopefully won't happen :-)

**Comment by sendilkumarn** [comment]
@gomesp go for it 👍

**Comment by jdubois** [comment]
And don't forget we need to implement both Angular and React, and that can be quite a huge job

**Comment by gomesp** [comment]
Thanks. I'll keep this issue open and post a few suggestions for both angular and react, and if the team likes them I'll implement them. 👍

**Comment by PierreBesson** [comment]
I personally would love to have this feature using either: 
- https://ckeditor.com/
- https://quilljs.com/
- https://www.froala.com/wysiwyg-editor
- https://alex-d.github.io/Trumbowyg

But ideally this would use a pre-made react/angular directive and so it might be hard to maintain. Ideally this could be a blueprint that replace our textarea with the WYSIWYG editor.

**Comment by gmarziou** [comment]
primeng's editor component uses Quill

**Comment by sendilkumarn** [comment]
yeah, also it is kinda important to check on the bundle sizes after adding this.

**Comment by jdubois** [comment]
Oh sorry but @sendilkumarn has a very good point here: initially, with AngularJS 1, I didn't want to have this, as this would make much bigger production builds. I'm not sure is this would be solved with tree shaking for Angular and React - I'm not the best person for this, unfortunately.

But if this can't be "tree shaked" when it's not used, then this costs much more than what we gain, and in that case I would be (unfortunately) quite strongly against this.

**Comment by gomesp** [comment]
@jdubois I'll take that into consideration when I start looking at it (probably over the weekend). So, what I am going with so far in terms of project direction is:

* Let's try QuillJS 
* If the users don't want to add any rich-text field, the library must not be packaged with the produced app

**Comment by jdubois** [comment]
Yes, perfect!

**Comment by jdubois** [comment]
I'm closing this as there has been no work for one month - anyway I'm not sure it's such a good fit for JHipster, as this will probably add a lot of weight to the default setup.
