### ISSUE TITLE
Small Change: Increase the definition of JDL snapshot png files

### ISSUE THREAD

**Issue by Tonterias** [jhipster/generator-jhipster#7621]
##### **Overview of the issue**

Increase the definition of JDL snapshot png files, because when the JDL is big and you open the png file you can not see anything in the entities and the image is useless. 

##### **Motivation for or Use Case**

Since the graph that is shown in the JDL-Studio can not be moved around (at least in Chrome) it is quite difficult so see the edges of the graph.

![jhipster-jdl 1](https://user-images.githubusercontent.com/11610877/39991573-4f73cf3e-5770-11e8-9514-4de1333076ad.png)

##### **Reproduce the error**

Not an error, but you can see the image pasted

##### **Related issues**

NA

##### **Suggest a Fix**

The easiest way to make it visible would be to increase the definition of the image. Being able to zoom in  a particular area of the image would be great too.

##### **JHipster Version(s)**

https://start.jhipster.tech/jdl-studio/#!/view/undefined

##### **JHipster configuration**

NA

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

NA

##### **Browsers and Operating System**

Versión 66.0.3359.139 (Build oficial) (64 bits)

- [ X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This is rendered by the browser, using https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL so I'm not sure we can do anything here, let me check

**Comment by jdubois** [comment]
Oh you need to zoom in: it generates the image using the size of the canvas in the browser.
So if you want a bigger image, zoom in :-)
