### ISSUE TITLE
yarn global upgrade generator-jhipster fails on node 10

### ISSUE THREAD

**Issue by henri-tremblay** [jhipster/generator-jhipster#7638]
##### **Overview of the issue**

When running the upgrade on from  4.14.3 to 4.14.4 it failed on the following error (with many deprecation messages)

```
  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/xxx/.node-gyp/10.1.0/include/node -I/Users/xxx/.node-gyp/10.1.0/src -I/Users/xxx/.node-gyp/10.1.0/deps/uv/include -I/Users/xxx/.node-gyp/10.1.0/deps/v8/include -I../../nan -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -fno-threadsafe-statics -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:1:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:832:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/xxx/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xxx/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:847:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/xxx/.node-gyp/10.1.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xxx/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:862:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/xxx/.node-gyp/10.1.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xxx/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:1471:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/xxx/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xxx/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxx/.config/yarn/global/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/Users/xxx/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/xxx/.config/yarn/global/node_modules/node-sass
gyp ERR! node -v v10.1.0
```

##### **Reproduce the error**

Launching the command with

node: v10.1.0
yeoman: 1.8.5
yarn: 1.6.0
 
shoud reproduce the issue.

##### **Related issues**

They seem to have the same issue in prettier/eslint-plugin-prettier#91

##### **JHipster Version(s)**

Migrating from 4.14.3 to 4.14.4

##### **Browsers and Operating System**

OSX 10.12.6. Node and yarn are installed with brew. Downgrading to node@8 fixes the problem.

**Comment by jdubois** [comment]
Yes can you check we already have a ticket on Node 10 (I'm closing this one as a duplicate).
As always we can only support LTS versions, the other releases are just too unstable.

**Comment by henri-tremblay** [comment]
Sorry, I failed to find the other issue. Note that if I'm correct, Node 10 will be LTS in October.

Then, since node 10 is now the default version of brew, you might want to document that node@8 should be used. I had to do the following after the node update:

```bash
brew install node@8
brew unlink node
brew link --overwrite --force node@8
```

**Comment by pascalgrimaud** [comment]
You're right @henri-tremblay : we should document it.
Can you do a PR for that? As you know all exact steps

@PierreBesson mentionned [this](https://github.com/jhipster/generator-jhipster/issues/7551#issuecomment-385738446) too:

> brew install node@8
brew link --force node@8
brew install yarn --without-node

**Comment by jdubois** [comment]
Even worse, I've spent some time trying to automate this in our [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/jhipster.rb), but I have no idea how to do it... So indeed that's really not good at the moment.
Best solution would be to support Node 10

**Comment by pascalgrimaud** [comment]
Yes it would be the best solution, to support Node10 too

**Comment by henri-tremblay** [comment]
@pascalgrimaud Yes. I've seen it. I'm not an expert. I'm not sure I need to unlink for instance. It's not harmful for sure though.

Then, there are 2 use-cases:
1- You install for the first time. In that case you do

```bash
brew install node@8
brew link --force node@8
brew install yarn --without-node
```

2- You are hit by a brew update that breaks everything. In that case you do (assuming I don't need to unlink

```bash
brew install node@8
brew unlink node
brew link --overwrite --force node@8
```

**Comment by henri-tremblay** [comment]
In order to document correctly, what is broken? yarn on node 10 or generator-jhipster on node 10?

**Comment by PierreBesson** [comment]
@henri-tremblay For me JHipster on node 10 works OK since I upgraded saas but yarn does have an issue that is fixed in their current master so it should arrive in v1.6.1.

@jdubois I have found the way to fix the JHipster homebrew formula, we have to change those lines :
```
  depends_on "node" => :recommended
  depends_on "yarn" => :recommended
```

As explained in https://docs.brew.sh/Formula-Cookbook : 

> :recommended generates an implicit without-foo option, meaning that the dependency is enabled by default and the user must pass --without-foo to disable this dependency.

This will let users do: `brew install jhipster --without-node --without-yarn`.
An alternative would be to use `:optional` instead of `:recommended` and this would have the reverse effect, install without node/yarn by default and you would need `brew install --with-node --with-yarn` to install the whole stack.

**Comment by henri-tremblay** [comment]
@PierreBesson I tried to find the yarn roadmap but they don't seem to have one. However, we can probably assume it should be out soon. So a documentation PR might not be that necessary.

**Comment by deepu105** [comment]
I guess we can see if we can support both node 8 and node 10

**Comment by jdubois** [comment]
I just tested the new Yarn 1.7.0 and Node 10.1.0 and everything works fine

**Comment by henri-tremblay** [comment]
I confirm. It works perfectly.
