### ISSUE TITLE
Feature request: Use Ant Design as React UI Library instead of reactstrap

### ISSUE THREAD

**Issue by tianlinzx** [jhipster/generator-jhipster#7639]
##### **Overview of the feature request**
Use Ant Design as React UI Library instead of reactstrap

Use Ant Design as React UI Library instead of reactstrap. Ant design have more components than reactstrap.
https://github.com/ant-design/ant-design 
##### **Motivation for or Use Case**
For the rich component and better look&feel , I suggest to use  Ant Design as React UI Library instead of reactstrap.

Ant Design is better designed and well documented and it has been stared for more than  28292 stars.

https://github.com/ant-design/ant-design
##### **Related issues or PR**
None.

No
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Send us a PR and we’ll consider it.

**Comment by jdubois** [comment]
I don't think you imagine the amount of work needed, probably more than 1 year... that's just not possible

**Comment by pascalgrimaud** [comment]
I think it can be a [module](https://www.jhipster.tech/modules/creating-a-module/) or a blueprint (you can have a look at [kotlin blueprint](https://github.com/jhipster/jhipster-kotlin))

**Comment by gmarziou** [comment]
It's well documented though their code contains comments in Chinese like [here](https://github.com/ant-design/ant-design/blob/master/components/modal/confirm.tsx#L21)

**Comment by jeremyprioux** [comment]
Here is a blueprint  Ant Design https://github.com/ChihoSin/generator-jhipster-ant-design
