### ISSUE TITLE
Success alerts not displaying in Firefox using production profile

### ISSUE THREAD

**Issue by contemmcm** [jhipster/generator-jhipster#7641]
##### **Overview of the issue**

When running jhipster app in production mode, success alert messages do not show up properly in Firefox. However, in Chrome everything looks fine. 

When running in dev mode, both browsers present the messages correctly.

###### Chrome

![captura de tela de 2018-05-16 08-40-38](https://user-images.githubusercontent.com/14226825/40115361-8d1e0cba-58e6-11e8-990e-c0afbc55db60.png)

###### Firefox

![captura de tela de 2018-05-16 08-40-47](https://user-images.githubusercontent.com/14226825/40115364-8f7d2464-58e6-11e8-9cd6-6160aeffb066.png)

##### **Motivation for or Use Case**

This happens in a newly created project and we cannot force users to use Chrome.

##### **Reproduce the error**

1. Generate a new project with jhipster generator
2. Add an entity
3. Build and run for production: `yarn install; yarn build; bash mvnw`
4. In Firefox, create, edit or update an entity through the administrative menu. The alert messages like `A MODEL is updated with identifier ID` do not show up in Firefox, but in Chrome it looks fine.

However, when running in dev mod (`bash mvnw & yarn start`), success alerts are shown correctly in both Firefox and Chrome.

##### **JHipster Version(s)**

4.14.4

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
##### **JHipster Version(s)**

```
myapp@0.0.0 /home/contemmcm/git/myapp
└── generator-jhipster@4.14.4 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.4",
    "baseName": "myapp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Label (label) {
  name String required
}

paginate Label with pagination
service Label with serviceImpl

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.7.4

node: v8.11.1

npm: 5.5.1

bower: 1.8.2

gulp:
[08:14:21] CLI version 2.0.1

yeoman: 2.0.1

yarn: 1.6.0

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.19.0, build 9e633ef

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

OS: Ubuntu 16.04 (64bits)
Browser: Firefox >= 45

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Is this related to #7615 ?

**Comment by contemmcm** [comment]
Surely the OS and dev/prod symptom is similar, but in #7615 the problem seems to occurs in both browsers (Firefox and Chrome), where in the present issue the problem is related to Firefox only. Besides, we are dealing with different components.

**Comment by jdubois** [comment]
I confirm the issue, even with JHipster 5 (using ng-bootstrap 2.0). This only happens with Firefox and in prod mode.

**Comment by deepu105** [comment]
Thats very strange

**Comment by jdubois** [comment]
My awesome trainees @agaspardcilia @chrisdns are on it :-)

**Comment by jdubois** [comment]
Closing as #7653 is merged (and I tested and I confirm it works!! Kudos to @agaspardcilia @chrisdns  )
