### ISSUE TITLE
Min validation with Angular 6 fails

### ISSUE THREAD

**Issue by FireWolf2007** [jhipster/generator-jhipster#7661]
##### **Overview of the issue**

1. validation require fill nullable field
2. Min validation require value more than specified in min value

##### **Reproduce the error**

Examle: https://github.com/FireWolf2007/hockey-match/

##### **JHipster Version(s)**

Current master version

##### **JHipster configuration**

hockey-match$ yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
hockey-match@0.0.0 /data/home_sasha_fast/hockey-match
└── generator-jhipster@5.0.0-beta.1  invalid

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "ru.wolfa.demo.hockey.match",
      "nativeLanguage": "ru"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "HockeyMatch",
    "packageName": "ru.wolfa.demo.hockey.match",
    "packageFolder": "ru/wolfa/demo/hockey/match",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "ru",
    "languages": [
      "ru"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Команда
 */
entity Team (team) {
  /**
   * Название команды
   */
  name String
}
/**
 * Игра в матче между 2 командами
 */
entity Game (game) {
  /**
   * Время начала
   */
  time ZonedDateTime,
  /**
   * Голы забытые командой 1
   */
  goalsTeam1 Integer min(0) max(1000),
  /**
   * Голы забытые командой 2
   */
  goalsTeam2 Integer min(0) max(1000),
  /**
   * Баллы начисленные команде 1
   */
  resultTeam1 Integer min(0) max(3),
  /**
   * Баллы начисленные команде 2
   */
  resultTeam2 Integer min(0) max(3)
}
/**
 * Турнир
 */
entity Tournament (tournament) {
  /**
   * Название турнира
   */
  name String
}
dto Team, Game, Tournament with mapstruct
paginate Team, Tournament with pagination
service Team, Game, Tournament with serviceImpl
paginate Game with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.7.4

node: v8.11.2

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.6.0

Docker version 17.03.2-ce, build f5ec1e2

docker-compose version 1.11.2, build dfed245

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>.jhipster/Game.json</summary>
<pre>
{
    "fields": [
        {
            "fieldName": "time",
            "javadoc": "Время начала",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "goalsTeam1",
            "javadoc": "Голы забытые командой 1",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min",
                "max"
            ],
            "fieldValidateRulesMin": 0,
            "fieldValidateRulesMax": 1000
        },
        {
            "fieldName": "goalsTeam2",
            "javadoc": "Голы забытые командой 2",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min",
                "max"
            ],
            "fieldValidateRulesMin": 0,
            "fieldValidateRulesMax": 1000
        },
        {
            "fieldName": "resultTeam1",
            "javadoc": "Баллы начисленные команде 1",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min",
                "max"
            ],
            "fieldValidateRulesMin": 0,
            "fieldValidateRulesMax": 3
        },
        {
            "fieldName": "resultTeam2",
            "javadoc": "Баллы начисленные команде 2",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min",
                "max"
            ],
            "fieldValidateRulesMin": 0,
            "fieldValidateRulesMax": 3
        }
    ],
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "tournament",
            "otherEntityName": "tournament",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "team1",
            "otherEntityName": "team",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "team2",
            "otherEntityName": "team",
            "otherEntityField": "name"
        }
    ],
    "changelogDate": "20180511035951",
    "javadoc": "Игра в матче между 2 командами",
    "entityTableName": "game",
    "dto": "mapstruct",
    "pagination": "infinite-scroll",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}
</pre>

<details>
<summary>.jhipster/Team.json</summary>
<pre>
{
    "fields": [
        {
            "fieldName": "name",
            "javadoc": "Название команды",
            "fieldType": "String"
        }
    ],
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "login"
        }
    ],
    "changelogDate": "20180511035950",
    "javadoc": "Команда",
    "entityTableName": "team",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}
</pre>

<details>
<summary>.jhipster/Tournament.json</summary>
<pre>
{
    "fields": [
        {
            "fieldName": "name",
            "javadoc": "Название турнира",
            "fieldType": "String"
        }
    ],
    "relationships": [],
    "changelogDate": "20180511204101",
    "javadoc": "Турнир",
    "entityTableName": "tournament",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}
</pre>

##### **Browsers and Operating System**

Firefox 60
Ubuntu 16.04

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Min/max Angular directive was merged recently in #7577 (not in beta 1), but they didn't allow null values so I opened a PR in ng-jhipster to fix this.
