### ISSUE TITLE
Add travis Test for OAuth2 gateway and microservices

### ISSUE THREAD

**Issue by farrault** [jhipster/generator-jhipster#7667]
##### **Overview of the feature request**

There is currently no automatic Travis test for the generation of OAuth2 gateway or microservices

##### **Motivation for or Use Case**

On https://github.com/jhipster/generator-jhipster/pull/7666, @mraible is making changes based on my propositions on the OAuth2 authenticationType but the unit test necessary to ensure that it compiles/runs are not currently launched by Travis.
( As an example, I think, that a missing dependency would be raised by Spring on OAuth2 Microservices with the current PR)

This Feature request only concerns generation and unit test execution of gateway or microservices separately.
It would be valuable to be able to do integration test with both components up, but it is a whole new story ....

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/pull/7666

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@farrault : thanks! In fact, it exists here https://travis-ci.org/hipster-labs/jhipster-travis-build/builds/381567326 but not in main generator.
It deserves a slot in main generator-jhipster as it's an important configuration.

Let me do this.

**Comment by PierreBesson** [comment]
> It would be valuable to be able to do integration test with both components up, but it is a whole new story ....
Oh yes this is badly needed. I'm planning on doing this once we have the JDL v2 as it would let us define several application and their entities in one shot. Then we simply generate a docker-compose configuration and run protractor tests on it.

**Comment by farrault** [comment]
@pascalgrimaud :
as said and discussed above with @PierreBesson  : testing gateway *and* microservice together would be very valuable but the purpose of this current issue was only to compile and run unit tests on gateway on one side (so without entity I'm afraid) ; and on microservices on another side.

This would at least ensure that the generation compile AND that the spring context boots correctly : which was my very first concerns when creating this issue.

( That being said, feel free to invest more time to test gateway and microservice together ;-) but that's a lot more time I guess )

**Comment by Tcharl** [comment]
I had this kind of stuff for protractor within one of my jenkinsfile:

`stage('E2e test') {
            steps {
                withEnv(['DISPLAY=:0']) {
                    sh '''
                        cd docker-compose && sh dev-compose.sh up
                        cd ../x.uaa && ./mvnw &
                        uaaPid=$!
                        until $(curl --output /dev/null --silent --head --fail http://localhost:9999/v2/api-docs); do
                            printf '.'
                            sleep 5
                        done
                        cd ../x.gw && ./mvnw &
                        gwPid=$!
                        cd ../x.us && ./mvnw &
                        usPid=$!
                        until $(curl --output /dev/null --silent --head --fail http://localhost:8080); do
                            printf '.'
                            sleep 5
                        done
                        cd ../x.gw && xvfb-run -a ./mvnw com.github.eirslett:frontend-maven-plugin:yarn -Dfrontend.yarn.arguments="run e2e"
                        kill $uaaPid
                        kill $gwPid
                        kill $usPid
                        cd ../docker-compose && sh dev-compose.sh down
                        docker volume prune -f
                    '''
                }
            }
        }
`

**Comment by mraible** [comment]
Related: https://github.com/jhipster/generator-jhipster/issues/7675
