### ISSUE TITLE
Capture logs during java unit tests

### ISSUE THREAD

**Issue by erikkemperman** [jhipster/generator-jhipster#7668]
##### **Overview of the feature request**

I would like to propose that, during (java) unit tests, we might capture the logging, for two reasons:
- explicitly assert the content being logged is as expected
- keep the terminal tidy during build

In the serverside library, we've been doing that for a while now, using [`LogbackRecorder`](https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/test/LogbackRecorder.java), and it seems to be working reasonably well.

##### **Motivation for or Use Case**

Too much stuff is written to my terminal during builds. Most of it is uninteresting (passing tests) but some of it looks scary even though it is harmless (expected errors). As a consequence, things that actually require my attention are easy too miss / hard to find.

I would be willing to start work on this -- but only if you agree it is worth a try, of course. What do you think?

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry I didn't answer yet on this ticket, but I don't understand what will be recorded or where... And I guess this is why you only got one thumb up.

Anyway, I'm closing this as you didn't have much feedback on this, so it's logical you won't work on it. But I guess it would be worth a clearer explanation, as I really don't get what you want to do.

**Comment by erikkemperman** [comment]
@jdubois Yeah, looks like I wasn't very clear, or maybe it just wasn't a popular idea.

For what it's worth though, I wanted to propose making the unit tests (of the generated app) lots less verbose, by only printing to the console if there are failing assertions.

This would also makes testing the generator itself lots less verbose, of course.

Currently, for example, there are exception traces which are OK (expected) but look frightening. Also it's hard to find where something is really going wrong, because of all the other uninteresting output.

By "recording" I mean to memory instead of to the console, so that we can assert the log contents and keep the console clean. We're doing that in jhipster/jhipster for a while already ([using this class](https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/test/LogbackRecorder.java)) and it seems to be working nicely.

Thoughts?

**Comment by pascalgrimaud** [comment]
I think we can put the log level to OFF for the tests

**Comment by erikkemperman** [comment]
True, but wouldn’t that end up hiding the interesting output as well (failing assertions)?

Also, what’s happening in the server lib is we actually assert the log content itself — although I guess some might find that overly pedantic.

**Comment by deepu105** [comment]
We can turn off Log for the actual source but not for the test classes as
well

Thanks & Regards,
Deepu

**Comment by erikkemperman** [comment]
We probably can, but not conveniently via package-names (test classes are in same package). So we'd have to address loggers with some kind of wildcard like `*Test`?
