### ISSUE TITLE
Compile on Heroku using Gradle results in no frontend

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#7674]
##### **Overview of the issue**
Apps using Gradle do not build the frontend when you choose "Compile on Heroku".  Compiling locally works as expected, Maven also works with either option

[Full Heroku Deploy logs](https://gist.github.com/ruddell/42e7afbcdd33ce1c5529399812aa49bd)

##### **Motivation for or Use Case**
Heroku responds as if the app built successfully (and the logs show it running), but it is inaccessible.  This can be confusing to new users.

##### **Reproduce the error**
Generate an app using Gradle (you can `--skip-install` since we it is building on Heroku)
Run `jhipster heroku` and choose to compile on Heroku

##### **Suggest a Fix**
Not sure, because it's related to Heroku's build environment pinging @jkutner 

##### **JHipster Version(s)**
v5 results in a blank white page
https://gradletestremote.herokuapp.com/
v4 results in a "Your request cannot be processed" page
https://gradleremotetest-v-4.herokuapp.com/

##### **JHipster configuration**
<details><summary>Config</summary>

```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "gradletest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "4f1a922cab86afeae8cc08948ee8ea1890ae2595",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "herokuDeployType": "git"
  }
}
```

</details>

##### **Environment and Tools**
<details><summary>Environment and Tools</summary>

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.17.0

node: v8.9.3

npm: 6.0.1

yeoman: 2.0.0

yarn: 1.3.2

Docker version 18.05.0-ce, build f150324

docker-compose version 1.21.2, build a133471
```

</details>

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jkutner** [comment]
@ruddell can you check what the command used to start the app is? (run `heroku ps` and you'll see it). Then post here? Thanks.

**Comment by jkutner** [comment]
@ruddell also, can you tell me what happens if you run `./gradlew stage` locally, and then run that same `java` command to start the app?

**Comment by ruddell** [comment]
java $JAVA_OPTS -Xmx256m -jar build/libs/*.war --spring.profiles.active=prod,heroku --server.port=$PORT

The same as on the remote happens.  Only the backend is compiled, the frontend does not build.

**Comment by ruddell** [comment]
If I add `-Pprod` so `./gradlew stage -Pprod` it builds the frontend

**Comment by atomfrede** [comment]
Adding `-Pprod` should be done nevertheless (in order to use the production webpack build). In dev mode it seems a propery `webpack` is required:

```groovy
processResources.dependsOn webpackBuildDev
webpackBuildDev.onlyIf { project.hasProperty('webpack') }
```
Not sure why that is and if maven has similar configuration.

**Comment by ruddell** [comment]
In dev you can use the `webpack` profile which compiles the TS for you at startup instead of having to run `yarn start` separately (you lose hot reload/compile though).  It doesn't use the prod webpack build though.

**Comment by jkutner** [comment]
@ruddell nevermind, i'm going to fix this by setting `GRADLE_TASK="stage -Pprod"`. However, now i'm running into:

```
remote:        :yarnSetup
remote:        /tmp/build_9e9656cc6de6750c7a9fef6675972ca0/.gradle/yarn/yarn-latest/bin/yarn -> /tmp/build_9e9656cc6de6750c7a9fef6675972ca0/.gradle/yarn/yarn-latest/lib/node_modules/yarn/bin/yarn.js

remote:        /tmp/build_9e9656cc6de6750c7a9fef6675972ca0/.gradle/yarn/yarn-latest/bin/yarnpkg -> /tmp/build_9e9656cc6de6750c7a9fef6675972ca0/.gradle/yarn/yarn-latest/lib/node_modules/yarn/bin/yarn.js

remote:        + yarn@1.7.0
remote:        added 1 package in 0.51s
remote:        :yarn_install FAILED
```

**Comment by jkutner** [comment]
Oh nevermind, that's because the app didn't have a `yarn.lock` because i never ran it locally. Seems to work.
