### ISSUE TITLE
Forbidden: Could not verify the provided CSRF token because your session was not found.

### ISSUE THREAD

**Issue by jimmyaug** [jhipster/generator-jhipster#7688]
##### **Overview of the issue**
Default app, not able to login using the default username and password (admin/admin). I get the following error at server side

o.z.p.spring.web.advice.AdviceTrait      : Forbidden: Could not verify the provided CSRF token because your session was not found.
2018-05-25 13:54:17.485  WARN 13772 --- [ XNIO-2 task-26] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: org.springframework.security.web.csrf.MissingCsrfTokenException: Could not verify the provided CSRF token because your session was not found.

##### **Motivation for or Use Case**
login feature does not work

##### **Reproduce the error**

1) generate the default app with options selected above.
2) build the app and start it - load the home page, click login
3) provide admin/admin as username and password. - Login fails

##### **JHipster Version(s)**
"4.14.4"

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
bookit@0.0.0 C:\Workspace_Jimmy\Idea_Workspace\jhipster\bookit
`-- generator-jhipster@4.14.4

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.reserve"
    },
    "jhipsterVersion": "4.14.4",
    "baseName": "bookit",
    "packageName": "com.reserve",
    "packageFolder": "com/reserve",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "enableHibernateCache": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.1.windows.1

node: v6.11.2

npm: 6.0.1

gulp:
[14:20:24] CLI version 2.0.1

yeoman: 2.0.2

yarn: 1.6.0

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

 Windows 10, problem on chrome.

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
That would be a very serious issue, I don't understand how this could have gone through all our tests!!! Let me test this ASAP

**Comment by jdubois** [comment]
@jimmyaug maybe this depends on your browser, on the way you start the application, or on how you access the application (directly on port 8080, through Webpack dev server on port 9060, or through BrowserSync on port 9000)???

Without this information, I'm running this with Maven (`./mvnw`), with Chrome on port 8080, which are the most obvious options.

**Comment by jdubois** [comment]
I'm sorry but I can't reproduce. Maybe also you have a specific browser extension? We already issues with people using ad blockers. Could you try with another, clean browser?

I'm closing as I can't reproduce, and will reopen if we have more information and can reproduce.
