### ISSUE TITLE
More user friendly Angular's datepicker for local dates

### ISSUE THREAD

**Issue by Falydoor** [jhipster/generator-jhipster#7699]
##### **Overview of the feature request**

When having an entity with a `LocalDate` field, the datepicker popup use a delta of 10 years based on the selected date. I'm using `5.0.0-beta.1` with Angular.

##### **Motivation for or Use Case**

Picking a date of birth for example is not very easy as you can only select a year with a range of 10 based on the selected date. You usually end up doing a manual input instead.

##### **Related issues or PR**

I don't think there is one.

I opened a ticket on [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap/issues/2412) to have the delta configurable.

I have two ideas to do this feature:
- Have a higher delta (100 years for example)
- Configure the `minDate` to be `100-01-01` (lowest value I was able to pick using the datepicker)

Let me know if you agree with this feature.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
yes, could you do it as a PR please?

**Comment by Falydoor** [comment]
Yes totally !

I created two branches:
- [With a delta of 100](https://github.com/jhipster/generator-jhipster/compare/master...Falydoor:datepicker-bigger-year-delta) (more code since it changes the entity page)
- [With a global min date](https://github.com/jhipster/generator-jhipster/compare/master...Falydoor:datepicker-custom-min-date)

Let me know which way makes more sense for you or if you know a better way !

**Comment by jdubois** [comment]
I would do a mix: I prefer the "global min date", but if you go to the middle ages it's really weird. I'm going to take your code and put a `moment().year() - 100` like you did for the "delta of 100".
And anyway, if people want to customize this, this will now be trivial to do.

**Comment by jdubois** [comment]
Fixed #8137
