### ISSUE TITLE
Feature Request - Enhance Istio / Kubernetes Support

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#7708]
##### **Overview of the feature request**

Istio Support MVP is in #7337. After that's implemented, look into additional changes around:

**Istio**
- [x] Update to Istio ~0.8~ 1.0 (Done #8321)
- [ ] Use Istio's Zipkin
  - [ ] Remove Zipkin Deployment
  - [ ] Configure Zipkin to point to Istio's Zipkin
  - [ ] Add Spring Cloud Sleuth Core Starter by default if using Istio
- [ ] Allow "*" wildcard hostname
- [ ] CORS configuration
- [x] Rate Limiting / Connection Pooling

**Istio mTLS**
- [ ] Use `curl` or local shell health check when generating for Istio (to support Istio Auth)
- [ ] Alternatively, put management port on a separate non-mTLS port (health check, and Prometheus)

**Kubernetes**
- [ ] Upgarde to Jib 1.0 (@PierreBesson)
- [ ] Add Prometheus scrape annotation to deployment YAML for metrics (@saturnism)
- [ ] Skaffold support
- [ ] (REMOVED) Spring Cloud Kubernetes
- [x] Better Helm support (@srinivasa-vasu) #9461

##### **Motivation for or Use Case**

To better support Istio in generated app/deployment.

##### **Related issues or PR**

#7337 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mrts** [comment]
Istio 1.0 is coming on July 18, maybe it's better to update to 1.0 instead of 0.8? See https://groups.google.com/forum/#!msg/istio-dev/tcDEwvBaTgw/jyziQbrICAAJ

**Comment by tianlinzx** [comment]
Istio 1.0 is released officially

**Comment by srinivasa-vasu** [comment]
Update to Istio 1.x #8321 @saturnism

**Comment by saturnism** [comment]
awesome! can't wait to try!!

**Comment by DanielFran** [comment]
@saturnism @srinivasa-vasu Any news on next evolution?

**Comment by srinivasa-vasu** [comment]
- Rate Limiting / Connection Pooling is already added, If I'm not wrong
- Initial Helm Support is added (#8630)

I'm waiting for #8987 to be merged to enhance helm support

**Comment by mraible** [comment]
@srinivasa-vasu The PR you were waiting for (#8987) has been merged. Can you please revisit this issue?

**Comment by pascalgrimaud** [comment]
@PierreBesson : this ticket has been opened for 1 year. What is the state of the different items ?
Should we keep this ticket opened ?

**Comment by pascalgrimaud** [comment]
As discussed with Pierre, I'm closing this
