### ISSUE TITLE
User entity filtering

### ISSUE THREAD

**Issue by Tarekajaj** [jhipster/generator-jhipster#7714]
##### **Overview of the feature request**
Create filtering queries for user entity in uaa server.
Just like [Entities filtering](https://www.jhipster.tech/entities-filtering/)
or at least document how developer can add it.

##### **Motivation for or Use Case**
Creating a filterable user list where one can filter users by searching name or email etc...

##### **Related issues or PR**
Unknown

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tarekajaj** [comment]
And since you suggest creating a new entity with one-to-one relation to User in order to add new fields and functionality it would also be helpful to show how one can query and filter Users based on those new fields.

**Comment by jdubois** [comment]
Yes that would be awesome, but there hasn't been any comment for 1 month and we have 50 opened tickets, so basically we don't have the bandwidth to do this.
PR is welcome from anybody who wants to do this, of course.
