### ISSUE TITLE
Support error boundaries introduced in react v16

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#7715]
##### **Overview of the feature request**

Support error boundaries introduced in react v16

##### **Motivation for or Use Case**

Starting v16, unhandled runtime errors will unmount whole react component tree. Error boundaries provides an elegant way to handle client side errors and display fallback UI.

https://reactjs.org/docs/error-boundaries.html

##### **Related issues or PR**

I don't see one

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
In addition to root level, I think we should also add page/module level error boundaries. Script failure in one module should still give end user a chance to use other non affected functionalties. For example, any script error in user-management sub-module can be scoped and users can continue using remaining admin functionality.

We can display standard error page in such scenarios. If possible, we should also create an endpoint to upload error stack trace so that it can be logged in server logs (may be separate log file). Overall, it would help to provide a centralized view of any un-handled errors (client / server) and will not go unnoticed.

**Comment by deepu105** [comment]
For now lets not get ahead of ourselves. I agree for root and module level
boundaries. Will you be willing to PR that?

**Comment by vishal423** [comment]
I will try doing this, however, I may be slow as I am new to react.

**Comment by deepu105** [comment]
You can use the snippet I provided and just add it per module and for root

Thanks & Regards,
Deepu
