### ISSUE TITLE
Angular : this._anchor is undefined error message when clicking

### ISSUE THREAD

**Issue by agaspardcilia** [jhipster/generator-jhipster#7716]
##### **Overview of the issue**

There is an error in the front-end console every time you click on the screen.
```
TypeError: this._anchor is undefined
Stack trace:
NgbDropdown.prototype._isEventFromToggle@webpack-internal:///./node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.js:227:68
NgbDropdown.prototype.closeFromClick@webpack-internal:///./node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.js:209:55
View_NavbarComponent_5/<@ng:///TmpAngAppModule/NavbarComponent.ngfactory.js:614:19
handleEvent@webpack-internal:///./node_modules/@angular/core/fesm5/core.js:11387:16
callWithDebugContext@webpack-internal:///./node_modules/@angular/core/fesm5/core.js:12484:22
debugHandleEvent@webpack-internal:///./node_modules/@angular/core/fesm5/core.js:12187:12
dispatchEvent@webpack-internal:///./node_modules/@angular/core/fesm5/core.js:8854:16
renderEventHandlerClosure/<@webpack-internal:///./node_modules/@angular/core/fesm5/core.js:9298:38
decoratePreventDefault/<@webpack-internal:///./node_modules/@angular/platform-browser/fesm5/platform-browser.js:1200:36
ZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:420:17
onInvokeTask@webpack-internal:///./node_modules/@angular/core/fesm5/core.js:4334:24
ZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:419:17
Zone.prototype.runTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:187:28
ZoneTask.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:495:24
invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:1539:9
globalZoneAwareCallback@webpack-internal:///./node_modules/zone.js/dist/zone.js:1576:21

```

##### **Motivation for or Use Case**

A huge error message in the console every time we click is pretty annoying.

##### **Reproduce the error**

+ Create a vanilla Angular project ( `jh` -> smash enter until it generates stuff).
+ Launch it
+ Click anywhere

##### **Related issues**

None that I can think of.

##### **Suggest a Fix**

No idea.

##### **JHipster Version(s)**

Current master.
##### **JHipster Version(s)**

```
tmp-ang@0.0.0 /home/alexandregc/repos/tmpAng
└── generator-jhipster@5.0.0-beta.1  -> /home/alexandregc/repos/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "tmpAng",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.17.0

node: v8.11.1

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.6.0

Docker version 17.12.1-ce, build 7390fc6

docker-compose version 1.17.1, build unknown

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entity.

##### **Browsers and Operating System**

FF 60 + Ubuntu 18.04

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Related to this ticket https://github.com/ng-bootstrap/ng-bootstrap/issues/2343
Not sure we can do something
