### ISSUE TITLE
Unable to delete user in User management

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#7721]
Jhipster Version: 5.0.0-beta.1

Here is the screenshot attaching related to the issue

![image](https://user-images.githubusercontent.com/11784253/40880238-a2d3b342-66ca-11e8-8bd2-92c7b1203a1b.png)

**Comment by pascalgrimaud** [comment]
Related to https://github.com/jhipster/generator-jhipster/pull/7406

**Comment by jdubois** [comment]
And please, please follow the guidelines... We spent a lot of time doing them, and they are here to help everyone

**Comment by deepu105** [comment]
This is already fixed

Thanks & Regards,
Deepu
