### ISSUE TITLE
Change the behavior of Angular entity resolver

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#7723]
##### **Overview of the feature request**

As of now, the resolver used in angular router cannot be strongly typed because it returns either a HTTPResponse or a new Entity.
Then, the update component and the detail component gets either the response.body or the element on their onInit() method.

I think we can improve it easily.

Instead of having this code:
```
@Injectable()
export class XDomainResolve implements Resolve<any> {
    constructor(private service: XService) {}

    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
        const id = route.params['id'] ? route.params['id'] : null;
        if (id) {
            return this.service.find(id);
        }
        return new X();
    }
}
```

We could have this:
```
@Injectable()
export class XDomainResolve implements Resolve<X> {
    constructor(private service: XService) {}

    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
        const id = route.params['id'] ? route.params['id'] : null;
        if (id) {
            return this.service.find(id).map((resp: HttpResponse<X>) => resp.body;
        }
        return new X();
    }
}
```

##### **Motivation for or Use Case**

Strongly type resolver, avoid dealing with either the response or the entity.

##### **Related issues or PR**

Will do one in a minute!

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@Tcharl since you are doing the PR anyway, i'm closing the ticket. Hope you dont mind. We need to do some ticket cleanup

**Comment by deepu105** [comment]
For minor improvements do a PR right away no need of ticket. Open issues only for major change proposals
