### ISSUE TITLE
Jhipster has jboss logging version conflicts

### ISSUE THREAD

**Issue by ganeshkrishnan1** [jhipster/generator-jhipster#7727]
Newly generated jhipster project.
Added support for hibernate search.
jhipster version 5.0.0-beta.1
Hibernate search compatible version: 5.9.2 final (NOT >= 5.10.x)

Bug: java.lang.methodnotfound error.

This is because of jboss-logging 3.3.2 final from spring boot is incompatible with jboss-logging 3.3.1 final which is required for hibernate search

Fix: Force jboss version to 3.3.1
eg gradle
compile("org.jboss.logging:jboss-logging:3.3.1.Final") {force=true}

**Comment by atomfrede** [comment]
Looks more like spring-boot or jboss problem (removing a method in a bugfix release).

**Comment by jdubois** [comment]
@ganeshkrishnan1 please follow our contribution guidelines, even if for this ticket we can work without them.

And yes this is an integration issue outside of the scope of JHipster - if your solution of forcing the lib works, then it's all good!
