### ISSUE TITLE
React: cannot compile for prod because of @types/react-router need ts 2.8

### ISSUE THREAD

**Issue by mkysoft** [jhipster/generator-jhipster#7729]
##### **Overview of the issue**

Cannot compile for prod with below command 
`yarn run webpack:prod`
Also ./mvnw -Pprod failed.
package.json devDependencies to @types/react-router-dom which has depency to @types/react-router with version *. 
yarn automaticly download @types/react-router v4.0.26 which need type script 2.8

##### **Motivation for or Use Case**

Working on React project.

##### **Reproduce the error**

Create sample project and try to release for prod.

##### **Suggest a Fix**

Remove @types/react-router-dom in pakacge.json

##### **JHipster Version(s)**

4.14.4
##### **JHipster configuration**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.10.1

node: v10.2.1

npm: 5.6.0

yeoman: 2.0.2

yarn: 1.6.0

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21
##### **Browsers and Operating System**
Mac OS 10.13.4

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
You use 4.14.4 with React which is deprecated.
A lot of work have been done in current master branch.
You should try, at least `v5.0.0-beta.1` or the `master` branch.

I'm closing this, as I confirm it works for current master.
