### ISSUE TITLE
Using jhipster server to create a project results in no applicationType in .yo-rc.json

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7731]
##### **Overview of the issue**

When creating a project with `jhipster server`, there is no `applicationType` key registered in `.yo-rc.json`. 

Projects like Ionic for JHipster rely on this key to determine if the app is a monolith or gateway. I could default to monolith if it's not found, but it seems like it should be there.

##### **Motivation for or Use Case**

https://github.com/oktadeveloper/generator-jhipster-ionic/issues/47

##### **Reproduce the error**

Create a project with `jhipster server`, then run the following command after it generates.

```
cat .yo-rc.json | grep applicationType
```

You will get no output.

##### **Suggest a Fix**

Add `applicationType: monolith` when `jhipster server` is used.

##### **JHipster Version(s)**

5.0.0-beta.1

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by manisi** [comment]
same error in JHipster version 4.14.4.

**Comment by jdubois** [comment]
I don't think `jhipster server` works at all, it's only meant to be composed by the main generator, but indeed the documentation says this should work - @deepu105 I guess you refactored this part, wdyt?

**Comment by pascalgrimaud** [comment]
It's just a missing option to add to `.yo-rc.json`
It shouldn't be hard to do

**Comment by deepu105** [comment]
The documentation is correct and this is the expected behaviour. And yes if
used seperately this option will not be updated. May be its a good idea to
update the docs and promote the skip client/server flags instead of sub gens
