### ISSUE TITLE
Issue combining elasticsearch with cassandra

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#7732]
##### **Overview of the issue**

Created Jhipster application with cassandra, manually edited .yo-rc file property searchEngine to elasticsearch and recreated the app. Unable to resolve the issue

##### **Motivation for or Use Case**

Wanted to create app with cassnadra and elasticsearch because both of them support distrubted node, fault tolarent. Was trying to create this combination. 

##### **Reproduce the error**
create application with cassandra database, then change yo-rc.json file, set "searchEngine": "elasticsearch", and regenerate using jhipster and rerun the app.
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "deapp.mvp"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "deapp",
    "packageName": "deapp.mvp",
    "packageFolder": "deapps/mvp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>

##### **JHipster Version(s)**
5.0.0-beta.1

##### **Environment and Tools**

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.7.4

node: v8.11.2

npm: 6.1.0

yeoman: 2.0.1

yarn: 1.7.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.18.0, build 8dd22a9

**Comment by jdubois** [comment]
It just can't work like that, there would a huge work to support this combination.

**Comment by pascalgrimaud** [comment]
I'm closing this ticket because there is no issue in JHipster.
We don't support Cassandra with Elasticsearch and this trick can't work.
