### ISSUE TITLE
Casandra-Migration docker fail to build with JHipster 5.0 on linux

### ISSUE THREAD

**Issue by groblochon** [jhipster/generator-jhipster#7740]
##### **Overview of the issue**

Casandra-Migration docker fail to build with JHipster 5.0 on linux :

`Step 3/7 : ADD cassandra/scripts/autoMigrate.sh /usr/local/bin/autoMigrate`
`ADD failed: stat /var/lib/docker/tmp/docker-builder151695797/cassandra/scripts/autoMigrate.sh: no such file or directory`

##### **Reproduce the error**

`docker-compose -f src/main/docker/cassandra.yml up -d`

##### **Related issues**

Script files must be in same directory than DockerFile.

##### **Suggest a Fix**

See diff file.

##### **JHipster Version(s)**

5.0.0-beta.1

##### **JHipster configuration**

See yo-rc.json

##### **Browsers and Operating System**

Ubuntu 18.04

- [x] Checking this box is mandatory (this is just to show you read everything)

[cassandraMigration.diff.txt](https://github.com/jhipster/generator-jhipster/files/2077191/cassandraMigration.diff.txt)
[yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/2077199/yo-rc.json.txt)

**Comment by ruddell** [comment]
Your `.yo-rc.json` file shows v5.0.0-beta.0 which is before this PR https://github.com/jhipster/generator-jhipster/pull/7488, that should fix the issue.
