### ISSUE TITLE
Using jhipster without mail server

### ISSUE THREAD

**Issue by agaspardcilia** [jhipster/generator-jhipster#7741]
##### **Overview of the feature request**

I'm implementing a way to reset password without a mail server.

##### **Motivation for or Use Case**

While discussing about what we should add to JHipster online, @jdubois thought it might be a good idea to find a way to make JH online fully usable even without a mail server to handle password reset. I came up with a solution that Julien liked.

I added a `jhipster.mail.enabled` to the configuration and depending on that value, the user management looks like this:

![](https://i.imgur.com/kD2DHtx.png)

And when you click on `Reset password` it shows:

![](https://imgur.com/GzcFOWn.png)

The generated link redirects you to our current password reset stuff that you would usually access from a password reset mail.

##### **Related issues or PR**

The implementation is almost done and I'll PR it soon. 

What do you guys think about it ?

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by agaspardcilia** [comment]
Actually, they're already done. I mean, the last thing to do is to fix an issue with link creation in Angular and to add some more tests.

**Comment by deepu105** [comment]
Great. Dont forget the React part

Thanks & Regards,
Deepu

**Comment by agaspardcilia** [comment]
The screeshots are from the React client.

**Comment by gmarziou** [comment]
I don't understand how the reset link is supposed to be communicated to end user?

**Comment by agaspardcilia** [comment]
The admin is supposed to send it himself to the user. It's just a way to make sure the admin can't know the real password unless he set it himself.

**Comment by jdubois** [comment]
Yes that's great. @agaspardcilia can you do a PR on jhipster/jhipster with the new Spring Boot configuration keys?

**Comment by deepu105** [comment]
@agaspardcilia please note there is bounty on this now

**Comment by agaspardcilia** [comment]
That's good to know. :smirk: I've got a lot of work these days but I might be able to take a look this week end.

**Comment by jdubois** [comment]
Closing as the PR is closed.
