### ISSUE TITLE
Not recompiling on change when using docker and docker-compose for a microservices architecture

### ISSUE THREAD

**Issue by iliasnaamane** [jhipster/generator-jhipster#7742]
##### **Overview of the issue**
I faced this problem when building docker images and generating docker-compose.yml for my microservices. Unfortunately, I cannot use docker as a development environment, since it is not automatically reload after code changes and it is a waste of time since it requires rebuilding images and lauching again.

##### **Related issues**
https://github.com/jhipster/generator-jhipster/issues/6126

##### **JHipster Version(s)**
4.14.1

##### **Browsers and Operating System**

OS: Linux stretch 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
what is the problem here, thats how it works. If you want live reload the use the development workflow and not docker. Run applications(except registry and console) using `./mvnw` or `./gradlew` and run `yarn start` for gateway

**Comment by iliasnaamane** [comment]
@deepu105 thanks for your quick response, but actually I want live reload with docker, since I am using ElasticSearch and it is not embedded based on @jdubois response on a previous issue https://github.com/jhipster/generator-jhipster/issues/7413 . Otherwise you can see that it is possible to use docker as a development tool with live reload on spirng http://endoflineblog.com/optimizing-development-with-docker

what do you think about that? It can be possible to PR this issue?  

Thanks

**Comment by deepu105** [comment]
If you know how to make it work, then please do a PR and we can consider it
based on how it fits our flow

Thanks & Regards,
Deepu

**Comment by ruddell** [comment]
You can launch the Elasticsearch docker container with `docker-compose -f src/main/docker/elasticsearch.yml up -d` and connect to it from the app running with `./mvwn` or `./gradlew`
