### ISSUE TITLE
Upgrade to JHipster Core v3

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7743]
This is mostly a question for @MathieuAA 

Now that JHipster Core v3 has been released, when do you plan to use it in generator-jhipster? Do you think there will be any issues?

I'd like to have JHipster 5 soon, do you think it is possible to migrate before, or is this too risky?

**Comment by MathieuAA** [comment]
Didn't I drop a PR for that?! I'm so, so sorry. I thought I did. I'll do it tonght.

**Comment by MathieuAA** [comment]
Ah @jdubois, I've just checked. I did drop a PR for that, it's in the JDL app fixing PR.

**Comment by jdubois** [comment]
Oops sorry @MathieuAA I just checked on the opened tickets!! So I'm closing this in favor of your PR
