### ISSUE TITLE
JWT token Invalid Signature | JWT secret should be base64

### ISSUE THREAD

**Issue by nemesiscodex** [jhipster/generator-jhipster#7744]
##### **Overview of the issue**

JWT token generated by jhipster has no valid signature for any other app besides the ones created by jhipster. (e.g. https://jwt.io/ debugger is not able to validate the signature)

##### **Motivation for or Use Case**
File `io.github.jhipster.sample.security.jwt.TokenProvider:63`
```java
return Jwts.builder()
            .setSubject(authentication.getName())
            .claim(AUTHORITIES_KEY, authorities)
            .signWith(SignatureAlgorithm.HS512, secretKey)
            .setExpiration(validity)
            .compact();
```
`secretKey` is a plain string, but the method `.signWith()` expects a base64-encoded key.
![image](https://user-images.githubusercontent.com/3976562/41117686-b6ae2e94-6a5b-11e8-93d6-5acaa2cdb3b1.png)

With this setup, everything will work for any jhipster application, but any other application with a different implementation will fail to validate the token.

##### **Reproduce the error**

1. Generate a jwt token (by authenticating with the gateway/auth server)
2. Try to validate the token with the https://jwt.io/ debugger

##### **Related issues**
- https://github.com/jhipster/generator-jhipster/issues/3322

##### **Suggest a Fix**
[TokenProvider.java:84](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs#L84)
Suggested fix:
```java
import java.nio.charset.StandardCharsets;
import java.util.Base64;
...
@Component
public class TokenProvider {
    ...
    private final Base64.Encoder encoder = Base64.getEncoder();
    ...
    @PostConstruct
    public void init() {
        ...
        this.secretKey =
            jHipsterProperties.getSecurity().getAuthentication().getJwt().getSecret();
        // Encode to base64
        this.secretKey = encoder.encodeToString(this.secretKey.getBytes(StandardCharsets.UTF_8));
        ...
    }
    ....
}
```

##### **JHipster Version(s)**
4.14.4

##### **JHipster configuration**
<details>
<summary>.yo-rc.json</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example"
    },
    "jhipsterVersion": "4.14.4",
    "baseName": "jhipster",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **Browsers and Operating System**
curl/postman

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
That's very surprising but it looks indeed correct! We need to check this.

**Comment by jdubois** [comment]
This is correct and I'm fixing this ASAP

**Comment by jdubois** [comment]
Thanks a lot @nemesiscodex - next time don't hesitate to do a PR, you did all the hard work and I don't deserve to be the author of the code!

**Comment by nemesiscodex** [comment]
Thanks @jdubois, I'm just glad to help. The work that you are doing is awesome!
