### ISSUE TITLE
Constraint Violation on Login Pattern when using Facebook login

### ISSUE THREAD

**Issue by damato3** [jhipster/generator-jhipster#7749]
##### **Overview of the issue**

Hello, i was working with the facebbok social login and found this issue. Basically i can't create a new User because the `login` patter validation fails, that's because the generated `login` using the Facebook user name and last name returns something like this `firstname_. lastname` (note the white space there). The Exception is:

```
2018-06-10 03:08:32.427 ERROR 53178 --- [  XNIO-2 task-7] c.m.myapp.web.rest.SocialController      : Exception creating social user: 

javax.validation.ConstraintViolationException: Validation failed for classes [com.mycompany.myapp.domain.User] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='must match "^[_'.@A-Za-z0-9-]*$"', propertyPath=login, rootBeanClass=class com.mycompany.myapp.domain.User, messageTemplate='{javax.validation.constraints.Pattern.message}'}
]
```
##### **Motivation for or Use Case**

I was testing with facebook login and i wasn't able to create the new User account because of the pattern error. So the pattern is `^[_'.@A-Za-z0-9-]*$` but the generated login was using a blank space (`firstname_. lastname`)

##### **Suggest a Fix**

A possible workaround would be to replace all white spaces in the string so we can be sure there is no white spaces in the generated `login`. 
```
private String getLoginDependingOnProviderId(UserProfile userProfile, String providerId) {
        switch (providerId) {
            case "twitter":
                // I didn't test a twitter account.
                return userProfile.getUsername().toLowerCase();
            default:
                // Using replaceAll() to remove any whitespace.
                return (userProfile.getFirstName().toLowerCase() + "_" + userProfile.getLastName().toLowerCase()).replaceAll(" ","");
        }
    }
```

##### **JHipster Version(s)**

JHipster Generator v4.14.4

##### **JHipster Version(s)**

```
jhipsterdemoui@0.0.0 /Users/damato/apps/jhipsterdemoui
└── generator-jhipster@4.14.4

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.4",
    "baseName": "jhipsterdemoui",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

git version 2.15.1 (Apple Git-101)

node: v10.1.0

npm: 6.1.0

bower: 1.8.0

gulp:
[03:01:41] CLI version 3.9.1
[03:01:41] Local version 3.9.1

yeoman: 1.8.5

yarn: 1.5.1

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.20.1, build 5d8c71b

##### **Browsers and Operating System**

MacOS High Sierra
version 10.13.4

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@damato3, unfortunately, the social login feature is removed in JHipster v5 and hence we will not be supporting this anymore. I suggest to use the fix you suggested for your app, and anyone facing the issue in 4.x will have this issue for reference.
