### ISSUE TITLE
Feign Client Annotation Issues

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#7756]
Opening this on behalf of @brunnels who can't open an issue for some reason, I can do the PR later if no one sees any issues.

##### **Overview of the issue**

OAuth2InterceptedFeignConfiguration and OAuth2UserClientFeignConfiguration classes should not be annotated with `@Configuration`

UserFeignClientInterceptor class should not be annotated with `@Component`

##### **Motivation for or Use Case**

Component scan will pickup these configurations and add to the global feign configuration.  The configuration should only apply to clients annotated with `@AuthorizedFeignClient` or `@AuthorizedUserFeignClient`.

UserFeignClientInterceptor is instantiated via `@Bean` annotation in OAuth2UserClientFeignConfiguration so annotating with `@Component` is not necessary and doing so will cause feign autoconfig to add it as an interceptor to all feign clients.

##### **Reproduce the error**

Create a basic `@FeignClient` annotated interface and you will find that it has Authorized headers added by the UserFeignClientInterceptor 

##### **Suggest a Fix**

Remove the annotations.  I have tested and microservice to microservice communication is still working properly after they have been removed.

##### **JHipster Version(s)**

Tested and confirmed in 5.0.0-beta.1.

Annotations are also present in my 4.14.1 projects.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Seems OK to me.

**Comment by jdubois** [comment]
Impressive work! Let's do this
