### ISSUE TITLE
when add @types/reactstrap, webpack compile failed

### ISSUE THREAD

**Issue by rainmanhhh** [jhipster/generator-jhipster#7757]
##### **Motivation for or Use Case**
when add @types/reactstrap, webpack compile failed

jhipster uses reactstrap but didn't include @types/reactstrap, but when i add it manually, webpack compile failed like below:

ERROR in E:/workspaces/instrument/instrumentManage/src/main/webapp/app/shared/layout/header/header.tsx
(173,29): Property 'nav' does not exist on type 'IntrinsicAttributes & UncontrolledProps & { children?: ReactNode; }'.

ERROR in E:/workspaces/instrument/instrumentManage/src/main/webapp/app/shared/layout/header/header.tsx
(178,29): Property 'style' does not exist on type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.

ERROR in E:/workspaces/instrument/instrumentManage/src/main/webapp/app/shared/layout/header/header.tsx
(191,35): Property 'to' does not exist on type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Thats due to an issue in the types. See discussions [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25329), [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26094) and [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25961)
