### ISSUE TITLE
JDL!! is printed when you start JHipster (master branch)

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7763]
> JDL!!! Welcome to the JHipster Generator v5.0.0-beta.1

![jhipster_010](https://user-images.githubusercontent.com/17892/41305691-e78ebd02-6e30-11e8-83aa-2225f4eca078.png)

**Comment by jdubois** [comment]
Thanks @mraible !! I'm fixing this

**Comment by jdubois** [comment]
BTW we should just print "Welcome to JHipster" now

**Comment by jdubois** [comment]
This is fixed, but I can't merge yet, jhipster/jhipster is stuck because Sonatype Nexus is time outing

**Comment by MathieuAA** [comment]
Pascal and his love for the JDL... it's truly a beautiful thing.Le 12 juin 2018 19:21, Julien Dubois <notifications@github.com> a écrit :This is fixed, but I can't merge yet, jhipster/jhipster is stuck because Sonatype Nexus is time outing

**Comment by PierreBesson** [comment]
«Proud to be the n°1 contributor of bugs» as Josh Long would say...

**Comment by pascalgrimaud** [comment]
Sorry for that... completely forgot to remove it, yesterday :-(
