### ISSUE TITLE
Make Cache Provider choosable on Gateways that has no service discovery

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#7767]
##### **Overview of the issue**

Currently Hazelcast is used as the mandatory cache on Gateways. However, if the Gateway doesn't perform rate limiting, there it doesn't seem necessary.

##### **Motivation for or Use Case**

Remove unneeded components.

##### **Suggest a Fix**

Use Hazelcast IFF Gateway and using Service Discovery. Otherwise, allow Cache provider selection.

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Agreed that Hazelcast on the gateway without service discovery will not work properly as the current config use eureka/consul to locate other instances and synchronize their caches.

And then you want to delegate gateway features to Istio. You might be better of disabling Zuul completely with env vars on your setup.

**Comment by saturnism** [comment]
if no service discovery, i recall i already removed zuul completely in generation.

**Comment by jdubois** [comment]
Without service discovery, Hazelcast and Inifispan won't be able to scale. Like Ehcache, which never scales in fact :-)
-> this 3 could only be options for people who do not want to scale their servers, which could be a choice

Then we now have Memcached support, and that would still work everywhere.

**Comment by jdubois** [comment]
I just tested it, and probably thanks to #7768 you can indeed use a gateway with no cache at all. So this is already done! Thanks @saturnism
