### ISSUE TITLE
JHipster Applications not scalable on OpenShift

### ISSUE THREAD

**Issue by hughwphamill** [jhipster/generator-jhipster#778]
When deploying application to OpenShift a 'do it yourself' cartridge is created, these cartridges are not scalable according to OpenShift [Documentation](https://developers.openshift.com/en/overview-platform-features.html#supported-cartridges), it might be worth looking at deploying a built war to a tomcat cartridge?

**Comment by renato-rjps** [comment]
Hi, could you help me with a question?
I'm trying to publish in openshit, and I wonder what kind of cartridge I have to create. Or if yo jhipster:openshift command will create for me? 
I have to create a DYV manually, make a clone and copy the files?
I read the documentation http://jhipster.github.io/openshift.html  but I didn't understand how to send files to OpenShift

**Comment by jdubois** [comment]
Yes it creates everything for you -> can you post this on stackoverflow ?
