### ISSUE TITLE
Run mvn in batch mode during ci

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#7785]
##### **Overview of the feature request**

During CI build, run mvn in batch mode to eliminate download progress logs

##### **Motivation for or Use Case**

Printing maven dependencies download progress logs is unnecessary and it is adding many unnecessary line number in build logs.

Following is really ugly to see every time and scrolling down (although many ci has scroll to end button), for eg,

```
Downloading: https://repo.maven.apache.org/maven2/io/github/jhipster/jhipster-dependencies/0.1.12/jhipster-dependencies-0.1.12.pom
Progress (1): 2.3/23 kB
Progress (1): 5.0/23 kB
Progress (1): 7.8/23 kB
Progress (1): 11/23 kB 
Progress (1): 13/23 kB
Progress (1): 16/23 kB
Progress (1): 19/23 kB
Progress (1): 21/23 kB
Progress (1): 23 kB   
```

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

##### **Suggested fix**

Adding an option to maven command `-B` which run maven in batch mode.
However, in addition to not displaying download progress, I am not sure what other impact to the build will be.

**Comment by mraible** [comment]
What’s the difference between -B and -q?

**Comment by pmverma** [comment]
Obviously,  `-q Quiet output - only show errors`. `-q` is better.

**Comment by pascalgrimaud** [comment]
I don't think download log is a problem -> as the dependencies should be in cache, you should have all these logs the 1st time or when there is a new dependency. But it seems the batch mode can avoid these logs, we can try, if there is no issue

About `quiet output`, you can have issue if the build is very long (more than 10min) and with no output, Travis can't stop the build. So I'm not in favor for that.

There are another discussion about reducing the logs during the build: https://github.com/jhipster/generator-jhipster/issues/7668

So, to resume:
- we need to test the `batch mode`
- maybe set the log to OFF only for tests

**Comment by pmverma** [comment]
>  as the dependencies should be in cache, you should have all these logs the 1st time or when there is a new dependency. 

I am running default generated Gitlab CI file, in my case, at every stage the deps is being downloaded.
It seems deps caching is not working with Gitlab CI config file.

**Comment by pmverma** [comment]
Here is my repo pipeline

[https://gitlab.com/pmverma/jh-ci/pipelines/23919870
](https://gitlab.com/pmverma/jh-ci/pipelines/23919870
)

All the jobs there are downloading deps

**Comment by pascalgrimaud** [comment]
@pmverma : thanks for linking a real project. It means these [lines](https://gitlab.com/pmverma/jh-ci/blob/master/.gitlab-ci.yml#L3-7) don't work -> it needs to be fixed

**Comment by pascalgrimaud** [comment]
Oh, you have only 1 build. Can you trigger another build and see if it used the cache ?

**Comment by pmverma** [comment]
Next build [https://gitlab.com/pmverma/jh-ci/pipelines/23921327](https://gitlab.com/pmverma/jh-ci/pipelines/23921327)
Same results.

Yes, I think gitlab cache settings need to be fixed as they might have changed something later with configuration format.

**Comment by pmverma** [comment]
@pascalgrimaud , the cache setting is correct.
The main problem is that we have not used `-Dmaven.repo.local=$MAVEN_USER_HOME` at every place.
Therefore, the deps of `./mvn` command run without it will never be cached and hence results in downloading again and again.

I will do a PR for Gitlab CI file.

**Comment by pascalgrimaud** [comment]
yes, go ahead plz :-)
