### ISSUE TITLE
Navbar menu Item Not translate  to selected lang 

### ISSUE THREAD

**Issue by manisi** [jhipster/generator-jhipster#7786]
##### **Overview of the issue**
when change lang to another from menu the menu item not set to selected lang and translated value

##### **JHipster Version(s)**

```
samplebeta-02@0.0.0 /Users/developer/Desktop/samplebeta02
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.2",
    "applicationType": "monolith",
    "baseName": "samplebeta02",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "memcached",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fa"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

git version 2.16.2

node: v8.11.2

npm: 5.6.0

yeoman: 2.0.2

yarn: 1.7.0

Docker version 17.05.0-ce, build 89658be

docker-compose version 1.13.0, build 1719ceb

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@manisi : I don't understand well the issue. The language is correctly selected for me, in the menu. Can you be more precise plz ?


![capture d ecran de 2018-06-22 08-18-02](https://user-images.githubusercontent.com/9156882/41760691-f3a5caba-75f4-11e8-8714-cf16b2b102f3.png)

**Comment by vishal423** [comment]
@pascalgrimaud , it's an issue with react codebase.

**Comment by agaspardcilia** [comment]
Indeed, and it also seems to be yet another issue with header needles. I'll take a look at it.

**Comment by manisi** [comment]
<img width="1404" alt="screen shot 2018-06-22 at 11 55 51" src="https://user-images.githubusercontent.com/3120328/41763584-d539696e-7613-11e8-9f83-c6a841953d69.png">
@pascalgrimaud 
Hi,
when change to farsi language the admin menu is still english lang menu item.
Thanks.

**Comment by pascalgrimaud** [comment]
yes, it is for React not Angular.
Thanks guys

**Comment by agaspardcilia** [comment]
After taking a closer look, header's translations in React seem to not be working at all. I'll try to fix that today.

**Comment by vishal423** [comment]
@agaspardcilia , can you check if PR #7815 fixes this on react?
