### ISSUE TITLE
React : Component unit test cases are excluded from Jest configuration

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#7787]
##### **Overview of the issue**

Component unit test cases are excluded from Jest configuration. This can be checked by looking under `jest.conf.js` file.

##### **Motivation for or Use Case**

Generated or newly added component unit test cases are not executed

##### **Suggest a Fix**
`jest.conf.js` -->
Current:
` testMatch: ['<rootDir>/src/test/javascript/spec/**/+(*.)+(spec.ts)'],`
Required:
`  testMatch: ['<rootDir>/src/test/javascript/spec/**/+(*.)+(spec.ts?(x))'],`

We also need to add enzyme configurations for enzyme functions (shallow, mount etc) to work:
`jest.conf.js` -->
`setupFiles: ['<rootDir>/src/test/javascript/enzyme-setup.ts']`

`enzyme-setup.ts` -->
```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

// React 16 Enzyme adapter
configure({ adapter: new Adapter() });
```
Above configurations enable execution of component test cases, however, few test cases fail due to usage of `require.context` in `translation.ts` as:
`en: mergeTranslations(require.context('../../i18n/en', false, /.json$/))`

As require.context is specific to webpack and Jest [discourage](https://github.com/facebook/create-react-app/issues/517) it's use, we should identify an appropriate way to resolve this issue to enable execution of component unit test cases.

##### **JHipster configuration**

Using JHipster version installed globally
Executing jhipster:info
Options: 
##### **JHipster Version(s)**

```
rgtw-4@0.0.0 /home/vishal/vishal/test/rgtw4
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "applicationType": "monolith",
    "baseName": "rgtw4",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "enableHibernateCache": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount (BankAccount) {
  name String required,
  balance BigDecimal required
}
entity Label (Label) {
  label String required minlength(3)
}
entity Operation (Operation) {
  date DateTime required,
  description String,
  amount BigDecimal required
}

relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)}
}
relationship ManyToOne {
  BankAccount{user(login)} to User
}
relationship ManyToMany {
  Operation{label(label)} to Label{operation}
}

paginate Operation with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.17.1

node: v8.9.1

npm: 5.5.1

yarn: 1.7.0

Docker version 18.03.1-ce, build 9ee9f40

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@vishal423 could you please PR, this. I guess this was missed during the migration to Jest
cc @wmarques

**Comment by deepu105** [comment]
I think yes, we should do it with `MergeJsonWebpackPlugin`. I originally used `require.context` when writing the i18n part and I wasnt aware that Jest was against it.

**Comment by deepu105** [comment]
@vishal423 will you be doing a PR? 
Also about the enzyme config, I remember I asked @wmarques about it and he said its not needed for Jest may be it was because of the missing tsx extension

**Comment by vishal423** [comment]
@deepu105, I will try and may take a day or two based on bandwidth.

**Comment by wmarques** [comment]
About `require.context`, I don't really know what's the correct solution for this. Could we manually require or import all the files and then merge them? Require seems handled by jest...

**Comment by vishal423** [comment]
I have changed require.context code to align with angular codebase. Basic code almost ready and should be able to raise merge in sometime.
