### ISSUE TITLE
Css differences between Dev And Prod

### ISSUE THREAD

**Issue by Belkacem** [jhipster/generator-jhipster#7789]
##### **Overview of the issue**

Style is different between dev and prod in parts of the app, example : 
dev: 
![image](https://user-images.githubusercontent.com/419224/41474372-1a891012-70bc-11e8-8e6e-0de42d639a7a.png)

prod: 
![image](https://user-images.githubusercontent.com/419224/41474379-1fb2e02c-70bc-11e8-9cee-4750bdacdbc3.png)

##### **Reproduce the error**

build the front end in dev mode or prod mode to see the difference

##### **JHipster Version(s)**

"jhipsterVersion": "5.0.0-beta.2"

##### **Browsers and Operating System**

Chrome, MacOs HighSierra 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes it's already been fixed in a previous ticket

**Comment by Belkacem** [comment]
Can you tell which ticket, and does it take care of the fileloader bug that makes assets that are in content folder unreachable from sass that is already in the content folder ?

**Comment by jdubois** [comment]
No sorry I'm on my phone... Have a look at the closed issue with no milestones, there should be very few of them, it will be there.
For the other bug I have no idea, you need to give me the ticket number.

**Comment by Belkacem** [comment]
Got it its #7776 
I'll create an issue for the second bug.
Thanks !
