### ISSUE TITLE
React shows registration link when using OAuth / OIDC for authentication

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7794]
##### **Overview of the issue**

"You don't have an account yet? Register a new account" is shown. This should be removed when OAuth/OIDC is used. Registration can be configured on the IdP and if turned on, it'll be available on Keycloak or Okta's login form.
##### **Motivation for or Use Case**

Because nothing happens when you click on the link.

##### **Suggest a Fix**

Remove the section in the template when OAuth is chosen as the authentication type.

##### **JHipster Version(s)**

```
gallery@0.0.0 /home/mraible/dev/okta-react-photo-gallery-example
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.2",
    "applicationType": "monolith",
    "baseName": "gallery",
    "packageName": "com.okta.developer",
    "packageFolder": "com/okta/developer",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "herokuDeployType": "git",
    "herokuAppName": "gallery-pwa"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Album (album) {
  title String required,
  description TextBlob,
  created Instant
}
entity Photo (photo) {
  title String required,
  description TextBlob,
  image ImageBlob required,
  takenOn Instant,
  uploadedOn Instant,
  open Boolean
}
entity Tag (tag) {
  name String required minlength(2)
}
relationship ManyToOne {
  Album{user(login)} to User,
  Photo{album(title)} to Album
}
relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.17.0

node: v8.10.0

npm: 6.1.0

yarn: 1.6.0

Docker version 18.05.0-ce, build f150324

docker-compose version 1.13.0, build 1719ceb

**Comment by deepu105** [comment]
closed via #7803
