### ISSUE TITLE
Gitlab CI artifact keeping period

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#7795]
##### **Overview of the issue**
Gitlab doc [https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html#defining-artifacts-in-gitlab-ci-yml](https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html#defining-artifacts-in-gitlab-ci-yml)

> If you don't define an expiry date, the artifacts will be kept forever.

If somebody is using self-hosted gitlab version, the ci job artifact is kept for 30 days by default.
However, for Gitlab.com hosted project they keep it forever. In that case it is better to define some expire days although they keep it forever.

##### **Motivation for or Use Case**

Old unnecessary artifact should be deleted after some period of time.

##### **Reproduce the error**

Better to see the downloadable artifact of success job at [https://gitlab.com/gitlab-org/gitlab-ce/pipelines?scope=all&page=2019](https://gitlab.com/gitlab-org/gitlab-ce/pipelines?scope=all&page=2019) (a yeal old)

##### **Related issues**

N/A

##### **Suggest a Fix**

set a default expire period when setting `artifacts` in a job, but need to change according to someone requirement.

eg,

```
pdf:
  script: xelatex mycv.tex
  artifacts:
    paths:
    - mycv.pdf
    expire_in: 1 week
```

##### **JHipster Version(s)**

v4.14.4

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Or should I keep it as it is because jhipster prefer defaults?

**Comment by pascalgrimaud** [comment]
I would suggest to let by default.
But we can add in comment `expire_in: 1 week` or 1 month, so the user knows what it does and can uncomment this if we want

**Comment by pascalgrimaud** [comment]
If you're ok with me, would you like to do this minor pull request?
Otherwise, we can discuss about it :)

**Comment by pmverma** [comment]
@pascalgrimaud I am also in favor of default, but add a comment. 
User may uncomment if necessary.

I will do a PR.

**Comment by pascalgrimaud** [comment]
Perfect, thank you !
