### ISSUE TITLE
Add ability to create multiple user roles from the app generator

### ISSUE THREAD

**Issue by gzsombor** [jhipster/generator-jhipster#780]
As configuring multiple roles is moderately tricky - the same value must be available on the javascript client, in the java server, and in the database as a record, it's fairly easy to forget, or spoil the change, so it would be nice if it can be autogenerated.

**Comment by jdubois** [comment]
I've been leaving this opened for too long, as I didn't make a decision:

- I don't want to have too many sub-generators, for all kind of things
- But I found this one to be quite useful

So after all this time, I have to choose: I am not going to merge this, as I'm not sure it will help that many people (it's quite easy to do it by hand, and I would argue it's easier than learning how to use a new sub-generator), and I don't want to have too many sub-generators (they become hard to maintain)
