### ISSUE TITLE
Show link to other entities with entity id == 0

### ISSUE THREAD

**Issue by FireWolf2007** [jhipster/generator-jhipster#7801]
##### **Overview of the issue**

I found the problem on my test project: entities with id == 0 is not shown.

Problem found at 
* entity-management-detail.component.html.ejs:90
* entity-management.component.html.ejs:133

Code: `<div *ngIf="<%= entityInstance + "." + relationshipFieldName + "Id" %>">`

##### **Reproduce the error**

Generate project with one relation and entities with id == 0

##### **Suggest a Fix**

I can't resolve how write condition. There is several options.
I write test in JS, but don't know what condition is correct, need advise.

Test in JS:

```
function test(a) {
    return a || a === 0 || a === false;
}

var c = 0;
for(c = -5;c<5;c++){
    if (test(c)) {
        console.log("IF"+c+" OK");
    } else {
        console.log("IF! BAD!!! "+c);
    }
}

c='';
if (test(c)) {
    console.log("IF '' BAD");
} else {
    console.log("OK ''");
}

c=null;
if (test(c)) {
    console.log("IF null BAD");
} else {
    console.log("OK null");
}

c=undefined;
if (test(c)) {
    console.log("IF undefined BAD");
} else {
    console.log("OK undefined");
}

c=true;
if (test(c)) {
    console.log("IF true OK");
} else {
    console.log("BAD true");
}

c=false;
if (test(c)) {
    console.log("IF false OK");
} else {
    console.log("BAD false");
}

c="test";
if (test(c)) {
    console.log("IF \"test\" OK");
} else {
    console.log("BAD \"test\"");
}

console.log("DONE");
```
In test:
* don't show: null, undefined, empty string
* show: all numbers, true, false, not empty string

So I think we must write something like this:
`<div *ngIf="<%= entityInstance + "." + relationshipFieldName + "Id" %> === 0 || <%= entityInstance + "." + relationshipFieldName + "Id" %> === false || <%= entityInstance + "." + relationshipFieldName + "Id" %>">`
It's will work but this is ugly. And need advice about correctness.

##### **JHipster Version(s)**

5.0.0-beta2, 4.14.4

##### **JHipster Version(s)**

```
route-service@0.0.0 /data/home_sasha_fast/work/transport-logistic/route-service
└── generator-jhipster@4.14.4 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "ru.wolfa.transport.route",
      "nativeLanguage": "ru"
    },
    "jhipsterVersion": "4.14.4",
    "baseName": "RouteService",
    "packageName": "ru.wolfa.transport.route",
    "packageFolder": "ru/wolfa/transport/route",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "ru",
    "languages": [
      "ru",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Route (route) {
  isReady Boolean,
  time Integer
}
entity RoutePoint (route_point)
entity RouteGraph (route_graph) {
  time Integer
}

relationship OneToMany {
  Route{routes} to
  RoutePoint{route required}
}
relationship ManyToOne {
  RouteGraph{pointFirst required} to RoutePoint,
  RouteGraph{pointSecond required} to RoutePoint
}

dto Route, RoutePoint, RouteGraph with mapstruct
paginate Route, RoutePoint, RouteGraph with pagination
service Route, RoutePoint, RouteGraph with serviceImpl
angularSuffix Route, RoutePoint, RouteGraph with routeService

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.7.4

node: v8.11.2

npm: 5.6.0

gulp:
[22:14:09] CLI version 3.9.1
[22:14:09] Local version 3.9.1

yeoman: 2.0.1

yarn: 1.6.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.2, build a133471

##### **Browsers and Operating System**
Ubuntu Linux, Firefox 60

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
IMO, entity with zero value in Id column is not a valid identifier.

**Comment by deepu105** [comment]
yes for numbers zero is equivalent of null

**Comment by deepu105** [comment]
@FireWolf2007 could you clarify why you need 0 as id in the first place?

**Comment by FireWolf2007** [comment]
@deepu105, It's not production. I'm used external file for loading initial data into DB via liquibase - they contains 0 as id.
I surprised that table has is empty cells (as null in external refs), but editor shows entity.
Technically I can't see problem to work with id 0 or less 0. I'm agree it's not common use 0 or negative values  for id.

**Comment by deepu105** [comment]
@FireWolf2007 in that case i would consider this as a non standard edge case and hence we wont change anything to support it. Ideally 0 should not be used as id
