### ISSUE TITLE
could not contact UAA to get public key

### ISSUE THREAD

**Issue by Icarus0xff** [jhipster/generator-jhipster#7814]
##### **Overview of the issue**

I generated a uaa service, a microservice named app0 and an api gateway with consul discovery type, but when i startup  app0 after start uaa server, I got a warn log`could not contact UAA to get public key` and when I try to login admin/admin via api gateway, it logged `java.lang.IllegalStateException: No instances available for uaa`, and in consul ui page, uaa service is health down. 
##### **Motivation for or Use Case**

I try to setup a microservice with uaa and api gateway.
##### **Reproduce the error**
Below is my tree path.
```
.
├── gateway
├── app0
└── uaa
```

##### **JHipster Version(s)**

4.14.4
Consul v1.1.0

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.cibfintech.rlap",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "4.14.4",
    "baseName": "app0",
    "packageName": "com.cibfintech.rlap",
    "packageFolder": "com/cibfintech/rlap",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "7d7203f4303958b276c8034b5be7001706c9680f",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

##### **Browsers and Operating System**

OSX
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
I believe you haven't started UAA server and that's reason behind errors you noticed.

**Comment by Icarus0xff** [comment]
@vishal423 I have started UAA before I start app0 and api gateway.

**Comment by Icarus0xff** [comment]
I found what's wrong in my enviroment.

- consul should not greater than 0.9.x
- service should run in a sequence uaa -> gateway -> app0

**Comment by pascalgrimaud** [comment]
In v4.14.4, you need to use consul:0.9.3
See https://github.com/jhipster/generator-jhipster/blob/v4.x_maintenance/generators/generator-constants.js#L44

In JHipster v5, we migrate to Consul 1.0.2
See https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-constants.js#L45

I'm closing this, as you found the issue with your Consul version.
