### ISSUE TITLE
Show console errors in overlay in browser window

### ISSUE THREAD

**Issue by digital-nomad17** [jhipster/generator-jhipster#7816]
##### **Overview of the feature request**

An overlay for the browser window. This overlay would display errors, warnings, and logs from the console. 

##### **Motivation for or Use Case**

During development it would be useful to beable to quickly glance at the browser window to see the output of the console. Especially with the fact browser-sync opens a new window with every start/restart of the build. 

[Asp.net javascript generator](https://github.com/aspnet/JavaScriptServices) had this feature when I used it awhile ago. I found it really useful in quickly debugging problems.

**Comment by deepu105** [comment]
Sorry but this is not something we can take up, we are already overwhelmed with features.

**Comment by digital-nomad17** [comment]
I made the mistake that this was a feature specific to another spa generator. 

It's a feature builtin to webpack - https://webpack.js.org/configuration/dev-server/#devserver-overlay for future reference.
