### ISSUE TITLE
execute ./gradlew bootWar -Pprod buildDocker report error

### ISSUE THREAD

**Issue by coolazrael** [jhipster/generator-jhipster#7818]
##### **Reproduce the error**
[5/5] Building fresh packages...
error /home/jhipster/app/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /home/jhipster/app/node_modules/pngquant-bin
Output:
??? The `/home/jhipster/app/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ??? pngquant pre-build test failed
  ??? compiling from source
  ??? pngquant pre-build test passed successfully
  ??? Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/jhipster/app/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':yarn_install'.
> Process 'command 'yarn'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 30s
5 actionable tasks: 4 executed, 1 up-to-date

##### **JHipster Version(s)**
V5.0.0

##### **JHipster configuration**
default config

**Comment by vishal423** [comment]
To fix this issue, you need to install 'libpng-dev' dependency on your system.

> Error: pngquant failed to build, make sure that libpng-dev is installed

**Comment by mraible** [comment]
I experienced this same issue on Linux. One you read the error and understand it, it makes sense. Closing because the error tells you what you need to do to fix it.
