### ISSUE TITLE
Missing closing quotes on generated build.gradle file.

### ISSUE THREAD

**Issue by DsosaV** [jhipster/generator-jhipster#7820]
##### **Overview of the issue**

The generated build.gradle file is missing a closing double quote for a single dependency. The dependency is: spring-retry.

##### **Suggest a Fix**

Add the closing double quotes [here](https://github.com/jhipster/generator-jhipster/blob/c39e6aa3f81a119d2ee24625b3063a0c4947a268/generators/server/templates/build.gradle.ejs#L334)

##### **JHipster Version(s)**

jhipster 5.0.0
![image](https://user-images.githubusercontent.com/3926475/41721948-3974edd4-7535-11e8-83f4-342efd7c732d.png)

**Comment by atomfrede** [comment]
Would you mind doing a pull request?

**Comment by DsosaV** [comment]
Will do in a moment.
