### ISSUE TITLE
elasticsearch node not available

### ISSUE THREAD

**Issue by alisedaghatbaf** [jhipster/generator-jhipster#7822]
##### **Overview of the issue**

I'm using jhipster (version 4.14.3) to generate a web app. The problem is that in production mode, the app cannot connect to the elastic search service which is running well on port 9200. Any help would be appreciated.

##### **Motivation for or Use Case**
users are faced with internal server error when trying to add any data record to the system.
##### **Reproduce the error**
1. build an executable war file:
`mvn -Pprod package`
2. run the war file:
`java -jar mywar.war`
3. login to the system and try to insert a record:
`exception details:
`org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are avail
able: [{#transport#-1}{localhost}{127.0.0.1:9300}]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(T
ransportClientNodesService.java:326)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNo
desService.java:223)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyCl
ient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:295)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)``

##### **JHipster Version(s)**
4.14.3
##### **JHipster configuration**
application-prod.yml:
`data:
    elasticsearch:
        cluster-name: elasticsearch
        cluster-nodes: localhost:9300`
elasticsearch.yml:
`cluster.name: elasticsearch
path.data: C:\Program Files\elasticsearch-6.2.4\data
path.logs: C:\Program Files\elasticsearch-6.2.4\logs
network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300`

**Comment by pascalgrimaud** [comment]
I just switch back to JHipster v4.14.3.
We generated an elasticsearch docker-compose file with `elasticsearch:2.4.6` that means a JHipster v4.14.4 only works with this version, not version 6.

Could you try JHipster v5.0.0 which has been released yesterday ?
It works with Elasticsearch 5.6.5, and maybe Elasticsearch 6.2.4.

**Comment by pascalgrimaud** [comment]
I'm closing this, as I think it's a problem with Elasticsearch version.
Don't hesitate to comment if you got the issue with JHipster v5 + Elasticsearch 5.6.5 / or give feedback for JHipster v5 + Elasticsearch v6.2.4

**Comment by ernsyn** [comment]
@pascalgrimaud, JHipster v5 now has issues with Elasticsearch even in dev mode. See https://github.com/jhipster/generator-jhipster/issues/7810.
