### ISSUE TITLE
Redundant / broken gateway sub-module/component code without serviceDiscovery

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#7827]
##### **Overview of the issue**
If you generate a gateway without service discovery, then, on server side it doesn't generate the GatewayResource.java. However, no such checks are added on frontend layer and thus it generate gateway page/component code (along with associated service, routes, reducer etc) which are redundant as they will never work without backend API

##### **Suggest a Fix**
This change got introduced by below commit on server side. Either we should revert this or apply similar checks on frontend layer.
https://github.com/jhipster/generator-jhipster/commit/f3d100c6d624ac58157a6c72ee4c949da563e574

##### **JHipster Version(s)**
5.0.0-beta.3

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.0.0-beta.3",
    "applicationType": "gateway",
    "baseName": "rgtw5",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "4a95621ba2e00b566a6b5625a4304126fdc687e7",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@vishal423 : Indeed, would you like to do a PR ?

**Comment by vishal423** [comment]
@pascalgrimaud, can you confirm the expectation as it used to work before

**Comment by pascalgrimaud** [comment]
Sorry I wasn't clear enough.

We should not revert the commit https://github.com/jhipster/generator-jhipster/commit/f3d100c6d624ac58157a6c72ee4c949da563e574 but do the same for the front part you mentionned when serviceDiscovery is set to false.
