### ISSUE TITLE
Feature Request : disable login registration form to externalize authentication

### ISSUE THREAD

**Issue by jgribonvald** [jhipster/generator-jhipster#783]
Having an option to avoid generation of all login/registration/activation account when all is managed externaly.

The authentication can be set with spring security, so no need in this case, but maybe having an entry point to go on authentication service.

**Comment by jdubois** [comment]
We will see what we can do when we refactor the security code.
But this won't be in v2, so it's out of scope at the moment.

**Comment by bluecitymoon** [comment]
how is going on with this?thanks
