### ISSUE TITLE
TextBlob fields validations stopped working in V5

### ISSUE THREAD

**Issue by Tonterias** [jhipster/generator-jhipster#7842]
##### **Overview of the issue**

Jhipster v5 does not like TextBlob fields validations:

~~~
entity Comment {
    creationDate Instant required
    commentText TextBlob minbytes(3) maxbytes(5000) required
    isOffensive Boolean
}


Hibernate JPA 2 Metamodel does not work with Bean Validation 2 for LOB fields, so LOB validation is disabled
WARNING! Cannot use validation in .jhipster/Comment.json for field {
"fieldName": "commentText",
"fieldType": "byte[]",
"fieldTypeBlobContent": "text",
"fieldValidateRules": [
"minbytes",
"maxbytes",
"required"
],
"fieldValidateRulesMinbytes": 3,
"fieldValidateRulesMaxbytes": 5000
}
~~~

This worked fine in version 4.13.

##### **Motivation for or Use Case**

As Gaël said, if it was working before, it should be a bug: https://stackoverflow.com/questions/50992210/how-to-create-a-field-validation-for-textblob-in-jhipster-v5-0-using-jdl

##### **Reproduce the error**

Try creating an Entity like this, please:

~~~
entity Comment {
    creationDate Instant required
    commentText TextBlob minbytes(3) maxbytes(5000) required
    isOffensive Boolean
}
~~~

##### **JHipster Version(s)**

v5 & v5.0.1 (it was working on v4.13)

##### **JHipster configuration**

D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\newstest501>jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**
v5.0.1
```
newstest-501@0.0.0 D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\newstest501
`-- generator-jhipster@5.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.web.newstest501"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "monolith",
    "baseName": "newstest501",
    "packageName": "com.web.newstest501",
    "packageFolder": "com/web/newstest501",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog (blog) {
  creationDate Instant required,
  title String minlength(2) maxlength(100) required,
  image ImageBlob
}
entity Post (post) {
  creationDate Instant required,
  publicationDate Instant,
  headline String minlength(2) maxlength(100) required,
  lead String minlength(2) maxlength(1000),
  bodytext TextBlob minbytes(3) maxbytes(50000) required,
  quote String minlength(2) maxlength(1000),
  conclusion String minlength(2) maxlength(2000),
  image ImageBlob
}
entity Comment (comment) {
  creationDate Instant required,
  commentText TextBlob minbytes(3) maxbytes(5000) required,
  isOffensive Boolean
}
entity Frontpageconfig (frontpageconfig) {
  creationDate Instant required,
  topNews1 Long,
  topNews2 Long,
  topNews3 Long,
  topNews4 Long,
  topNews5 Long,
  latestNews1 Long,
  latestNews2 Long,
  latestNews3 Long,
  latestNews4 Long,
  latestNews5 Long,
  breakingNews1 Long,
  recentPosts1 Long,
  recentPosts2 Long,
  recentPosts3 Long,
  recentPosts4 Long,
  featuredArticles1 Long,
  featuredArticles2 Long,
  featuredArticles3 Long,
  featuredArticles4 Long,
  featuredArticles5 Long,
  featuredArticles6 Long,
  featuredArticles7 Long,
  featuredArticles8 Long,
  featuredArticles9 Long,
  featuredArticles10 Long,
  popularNews1 Long,
  popularNews2 Long,
  popularNews3 Long,
  popularNews4 Long,
  popularNews5 Long,
  popularNews6 Long,
  popularNews7 Long,
  popularNews8 Long,
  weeklyNews1 Long,
  weeklyNews2 Long,
  weeklyNews3 Long,
  weeklyNews4 Long,
  newsFeeds1 Long,
  newsFeeds2 Long,
  newsFeeds3 Long,
  newsFeeds4 Long,
  newsFeeds5 Long,
  newsFeeds6 Long,
  usefulLinks1 Long,
  usefulLinks2 Long,
  usefulLinks3 Long,
  usefulLinks4 Long,
  usefulLinks5 Long,
  usefulLinks6 Long,
  recentVideos1 Long,
  recentVideos2 Long,
  recentVideos3 Long,
  recentVideos4 Long,
  recentVideos5 Long,
  recentVideos6 Long
}
entity Topic (topic) {
  topicName String minlength(2) maxlength(40) required
}
entity Tag (tag) {
  tagName String minlength(2) maxlength(40) required
}
entity Urllink (urllink) {
  linkText String required,
  linkURL String required
}
relationship OneToOne {
  Blog{user required} to User
}
relationship OneToMany {
  Blog{post} to Post{blog(title) required},
  Post{comment} to Comment{post(headline) required}
}
relationship ManyToMany {
  Topic{post(headline)} to Post{topic},
  Tag{post(headline)} to Post{tag}
}

paginate Blog, Post, Comment, Frontpageconfig, Topic, Tag, Urllink with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.16.2.windows.1

node: v8.11.1

npm: 5.6.0

yeoman: 2.0.2

yarn: 1.7.0

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

Congratulations, JHipster execution is complete!

D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\newstest501>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
    "name": "Post",
    "fields": [
        {
            "fieldName": "creationDate",
            "fieldType": "Instant",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "publicationDate",
            "fieldType": "Instant"
        },
        {
            "fieldName": "headline",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength",
                "maxlength",
                "required"
            ],
            "fieldValidateRulesMinlength": 2,
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "lead",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": 2,
            "fieldValidateRulesMaxlength": 1000
        },
        {
            "fieldName": "bodytext",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "minbytes",
                "maxbytes",
                "required"
            ],
            "fieldValidateRulesMinbytes": 3,
            "fieldValidateRulesMaxbytes": 50000
        },
        {
            "fieldName": "quote",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": 2,
            "fieldValidateRulesMaxlength": 1000
        },
        {
            "fieldName": "conclusion",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": 2,
            "fieldValidateRulesMaxlength": 2000
        },
        {
            "fieldName": "image",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "comment",
            "otherEntityName": "comment",
            "otherEntityRelationshipName": "post"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "blog",
            "otherEntityName": "blog",
            "otherEntityField": "title"
        },
        {
            "relationshipType": "many-to-many",
            "relationshipName": "tag",
            "otherEntityName": "tag",
            "ownerSide": false,
            "otherEntityRelationshipName": "post"
        },
        {
            "relationshipType": "many-to-many",
            "relationshipName": "topic",
            "otherEntityName": "topic",
            "ownerSide": false,
            "otherEntityRelationshipName": "post"
        }
    ],
    "changelogDate": "20180625092840",
    "entityTableName": "post",
    "dto": "no",
    "pagination": "pagination",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}

##### **Browsers and Operating System**

Before OS.
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tonterias** [comment]
Sorry, I hope that helps now. Thanks.

**Comment by dcaravana** [comment]
Not sure how relevant is to mention here (this may require a separate issue), but TextBlob rendering with React is wrong with v5 as it just renders an `input` of type `text` instead of a `textarea`.

**Comment by mraible** [comment]
I can confirm this is true.

**Comment by agaspardcilia** [comment]
@dcaravana @mraible I'll try to PR something about that today or tomorrow.

**Comment by deepu105** [comment]
@agaspardcilia please add the fix #no for autoclose next time
