### ISSUE TITLE
Add delete tests to Protractor tests

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7844]
##### **Overview of the feature request**

The current Protractor tests verify that add works, but they don't delete the records. This means that when you run the tests, test data is left around.

##### **Motivation for or Use Case**

Because I like to run e2e tests, but not have the test data lying around after.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/7778

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
it's a very good idea. We need this.

**Comment by mraible** [comment]
The only complicated thing I’ve seen is the add tests create relationships between entities, so deletes will need to happen in reverse order.
