### ISSUE TITLE
ERROR in MergeJsonWebpackPlugin: Error parsing the json file [./src/main/webapp/i18n/uz-lat/global.json]

### ISSUE THREAD

**Issue by xmeng1** [jhipster/generator-jhipster#7848]
##### **Overview of the issue**
get error when yarn run after generation 

ERROR in MergeJsonWebpackPlugin: Error parsing the json file [./src/main/webapp/i18n/uz-lat/global.json]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
If you find JHipster useful consider supporting our collective https://opencollective.com/generator-jhipster

##### **JHipster Version(s)**

jhipster -V
Using JHipster version installed locally in current project's node_modules
5.0.0

yarn -v
1.7.0

node -v
v8.11.3

npm -v
5.6.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "science.mengxin.java.jhipster",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0",
    "applicationType": "monolith",
    "baseName": "jhipsterXin",
    "packageName": "science.mengxin.java.jhipster",
    "packageFolder": "science/mengxin/java/jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "e8f00daf7899c656202f311c58c37cf86605be96",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly",
      "hy",
      "ca",
      "zh-cn",
      "zh-tw",
      "cs",
      "da",
      "nl",
      "et",
      "fa",
      "fr",
      "gl",
      "de",
      "el",
      "hi",
      "hu",
      "id",
      "it",
      "ja",
      "ko",
      "mr",
      "pl",
      "pt-br",
      "pt-pt",
      "ro",
      "ru",
      "sk",
      "sr",
      "es",
      "sv",
      "tr",
      "ta",
      "th",
      "ua",
      "uz-lat",
      "vi"
    ]
  }
}

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I think some special character in `src/main/webapp/i18n/uz-lat/global.json` might be causing issue. Can you remove any special chars in that file and try again? if it works let us know

**Comment by xmeng1** [comment]
I think I find the reason of the issue, there are two more commas in the JSON template
https://github.com/jhipster/generator-jhipster/blob/caa1ba98234063de0a007864b361835eaccd8f5e/generators/languages/templates/src/main/webapp/i18n/uz-lat/global.json.ejs#L96

and

https://github.com/jhipster/generator-jhipster/blob/caa1ba98234063de0a007864b361835eaccd8f5e/generators/languages/templates/src/main/webapp/i18n/uz-lat/global.json.ejs#L102

Remove them, build successfully. Do you think I need to make PR for it or just fix it with other PR?

**Comment by pascalgrimaud** [comment]
fixed by https://github.com/jhipster/generator-jhipster/pull/7863
