### ISSUE TITLE
SecurityConfiguration for production mode

### ISSUE THREAD

**Issue by jbaris** [jhipster/generator-jhipster#785]
I have generated an app with:
`$ yo jhipster`
then packaged with:
`$ mvn clean package -Pprod`
and then runned with:
`$ java -jar ./target/myapp-0.0.1-SNAPSHOT.war --spring.profiles.active=prod`
Then, when I go to http://localhost:8080/ on browser console I see the logs:
`GET http://localhost:8080/protected/authentication_check.gif 401 (Unauthorized)`
 `GET http://localhost:8080/views/main.html 401 (Unauthorized)` 
and the main page is partially rendered.
To solve this I had to change on SecurityConfiguration:

```
    public void configure(WebSecurity web) throws Exception {
    ...
    web.ignoring()
    ...
    .antMatchers("/dist/bower_components/**")
    .antMatchers("/dist/fonts/**")
    .antMatchers("/dist/images/**")
    .antMatchers("/dist/scripts/**")
    .antMatchers("/dist/styles/**")
    .antMatchers("/dist/views/**")
    .antMatchers("/dist/views/**")
    .antMatchers("/dist/i18n/**")
    .antMatchers("/dist/swagger-ui/**")
    .antMatchers("/dist/app/rest/register")
    .antMatchers("/dist/app/rest/activate")
    .antMatchers("/dist/console/**");
```

Is this ok?
Thanks,
Regards

**Comment by cobour** [comment]
Same problem here with unmodified generated app.
When using Maven's Prod-Profile, *every* file inside "views"-Folder leads to 401.
That's why only the Navigation-Bar and the Footer is rendered. After adding just
```
.antMatchers("/dist/views/**")
```
to SecurityConfiguration as stated above, everything works as expected.
What am I doing wrong?

**Comment by dalyc** [comment]
I'm seeing this too in production mode

**Comment by dalyc** [comment]
I noticed that if I had the port set in application-prod.yml but didn't include it in the url, I would get the above behaviour - that was with ssl and port 8443
