### ISSUE TITLE
Fail to update from 4.14.0 to 5.0.1 - ownerSide is missing in .jhipster/xxxxxxxxx.json for relationship

### ISSUE THREAD

**Issue by Blackdread** [jhipster/generator-jhipster#7852]
##### **Overview of the issue**

Fail to update from 4.14.0 to 5.0.1 - ownerSide is missing in .jhipster/MessageSeen.json for relationship

> Error: ERROR! ownerSide is missing in .jhipster/MessageSeen.json for relationship {
>     "relationshipType": "one-to-one",
>     "relationshipValidateRules": "required",
>     "javadoc": "Last time seen by user",
>     "relationshipName": "seenBy",
>     "otherEntityName": "user",
>     "otherEntityField": "login",
>     "otherEntityRelationshipName": "messageSeen"
> }

Another warning that happens just before but seems to default to a value:

> WARNING! otherEntityRelationshipName is missing in .jhipster/MessageSeen.json for relationship {
>     "relationshipType": "one-to-one",
>     "relationshipValidateRules": "required",
>     "javadoc": "Last time seen by user",
>     "relationshipName": "seenBy",
>     "otherEntityName": "user",
>     "otherEntityField": "login",
>     "otherEntityRelationshipName": "messageSeen"
> }, using messageSeen as fallback
> events.js:183
>       throw er; // Unhandled 'error' event

##### **Motivation for or Use Case**

Cannot update.
I can manually fix one file at a time by checking and adding the missing data in json but maybe there is an automatic solution

##### **Reproduce the error**

Generate from old version and try to upgrade

##### **Related issues**

None

##### **Suggest a Fix**

Owner side could be guessed?
Not sure how without the jdl being checked during upgrade

##### **JHipster Version(s)**

4.14.0 to 5.0.1

##### **JHipster configuration**

Default configuration of 4.14.0, did not modify

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

One of the json

> {
>     "fluentMethods": true,
>     "relationships": [
>         {
>             "relationshipType": "one-to-one",
>             "relationshipValidateRules": "required",
>             "javadoc": "Last time seen by user",
>             "relationshipName": "seenBy",
>             "otherEntityName": "user",
>             "otherEntityField": "login"
>         }
>     ],
>     "fields": [
>         {
>             "fieldName": "lastMessageTimeRead",
>             "fieldType": "Instant",
>             "fieldValidateRules": [
>                 "required"
>             ]
>         }
>     ],
>     "changelogDate": "20171209052327",
>     "entityTableName": "message_seen",
>     "dto": "mapstruct",
>     "pagination": "pagination",
>     "service": "serviceClass",
>     "jpaMetamodelFiltering": true
> }

##### **Browsers and Operating System**

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I couldn't reproduce this with the prompts or JDL so not sure how your entity JSON got in that format.  Tested generating with both v4.10.0 and v5 and the ownerSide field was always set

**Comment by Blackdread** [comment]
ok, no idea either.
I can manually correct the json when error happens

**Comment by MathieuAA** [comment]
A possible solution: if you generated your entities with the JDL and your JDL is up-to-date, let it overwrite your JSON files. If they weren't generate with the JDL, use the `export-jdl` subgen and try to do the same.

**Comment by Blackdread** [comment]
I used JDL, will do your solution.
Thx.
