### ISSUE TITLE
Online generator selecting angular

### ISSUE THREAD

**Issue by congruentsquare** [jhipster/generator-jhipster#7857]
##### **Overview of the issue**

Online jhipster-generator javascript framework selection not working. Is anyone having issues with generating a react jhipster app? 

##### **Reproduce the error**

Selecting 0auth 2.0 authentication causes angular to be selected.

**Comment by jdubois** [comment]
Thanks, I've spotted the issue, let me fix this

**Comment by PierreBesson** [comment]
This seems to be fixed and not posted in the right issue tracker. So I'm closing it;

**Comment by congruentsquare** [comment]
It's working now. If I run into another issue, I'll make sure I submit to the right github project. Thank you.
