### ISSUE TITLE
Error creating project 5.0.1

### ISSUE THREAD

**Issue by DennerLemos** [jhipster/generator-jhipster#7867]
I am facing a problem when generating a new project with version 5.0.1, in version 4.14.5 when generating a project I had the option to login with the social media, however in version 5.0.1 this option is not available, it was removed? or has the form of choice changed?

**Comment by jdubois** [comment]
Yes it was removed, that's not an error (next time, please write a better ticket title).
The first reason is that "Spring Social" isn't actively maintained anymore, so we had lots of problems with it.
With JHipster, it's replaced by OAuth2 authentication, typically with Keycloak.
With the new OpenID Connect support in Spring Security, I hope that in the future we could also directly have a Google OpenID Connect integration - that shouldn't be hard to do, but we just lack time to do everything.
