### ISSUE TITLE
Opening Login model Scrolls the page to bottom.

### ISSUE THREAD

**Issue by RohanHSBC** [jhipster/generator-jhipster#7873]
Hi Guys, just figured out a small glitch on UI side whenever you open the login model on the homepage which has scrollable content after the popup is opened the page automatically scrolls to the bottom.

![image](https://user-images.githubusercontent.com/17309736/41992036-03667282-7a65-11e8-8cfd-3599d7118e75.png)

Please find screenshot for reference.

**Comment by deepu105** [comment]
I also noticed this, but I have no idea why it happens. A workaround is to
call `window.scrollTo` on the componentWillUnmount step of the login
component

Thanks & Regards,
Deepu

**Comment by RohanHSBC** [comment]
Just figured out a workaround for this, the issue is caused when you set the focus on input after the modal has opened. The page scroll can be prevented by commenting the code that sets the focus in file.

**login.componect.ts** 

`
ngAfterViewInit() {
           //this.renderer.invokeElementMethod(this.elementRef.nativeElement.querySelector('#username'), 'focus', []);
    }
`

**Comment by agaspardcilia** [comment]
@PierreBesson Yeah, it's not working on firefox as you mentioned. I've found a simple css fix that works, but it messes a lot with what's behind the modal.
The fix is:
```
body.modal-open {
    position: fixed;
    overflow: hidden;
}
```
but I wouldn't recommend using it.

**Comment by deepu105** [comment]
Is there any other workaround for Mozilla?

Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
Well there should be a solution, as with the reactstrap's `autofocus` (eg. in [jhipster-sample-react](https://github.com/jhipster/jhipster-sample-app-react/blob/master/src/main/webapp/app/modules/login/login-modal.tsx#L47)) it seems to work fine. But the solution might be complex. Ultimately the property will be implemented in firefox I'm sure.

**Comment by ruddell** [comment]
FYI there are two related issues in the ng-bootstrap repository 
https://github.com/ng-bootstrap/ng-bootstrap/issues/938
https://github.com/ng-bootstrap/ng-bootstrap/issues/1776

**Comment by vishal423** [comment]
Did anyone tried last solution in #1776 to check if that solves issue seen here?

**Comment by deepu105** [comment]
@PierreBesson as @vishal423 suggested can you try this as well?
```
ngOnInit() {
    setTimeout(() => this.input.nativeElement.focus(), 0);
 }
```

**Comment by deepu105** [comment]
@PierreBesson I tried it and seems to work
```
    ngAfterViewInit() {
        setTimeout(() => this.renderer.invokeElementMethod(this.elementRef.nativeElement.querySelector('#username'), 'focus', []), 0);
    }
```

**Comment by PierreBesson** [comment]
Yes I just tried it this morning and it works well. I'm commiting it later.
