### ISSUE TITLE
Extract a "LiquibaseConfiguration" config bean from "DatabaseConfiguration"

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7875]
Currently in the `DatabaseConfiguration` configuration bean, we configure Liquibase. This is not very good:

- I think it's cleaner to have a more descriptive class name to configure Liquibase, like `LiquibaseConfiguration`
- It would also be easier for people who want to remove Liquibase (probably just delete the file), as I see this is something many people want to remove

That would also fix a bug I have in Cloud Foundry, and which is also linked with mixing the database configuration (which is done in another bean when running in Cloud Foundry, the `CloudDatabaseConfiguration`) and the Liquibase configuration. Which kind of prove the issue.

I'm going to refactor this soon, so if you are against this please comment!

**Comment by deepu105** [comment]
+1

Thanks & Regards,
Deepu
