### ISSUE TITLE
Changes in global.scss loaded before bootstrap.scss

### ISSUE THREAD

**Issue by jdordoigne** [jhipster/generator-jhipster#7886]
##### **Overview of the issue**

In jhispter 5, bootstrap rules have priority over styles in global.scss

##### **Motivation for or Use Case**

We have override bootstrap style in global.scss in our  jhipster 4 application. After migration in v5 all our style are broken.

##### **Reproduce the error**

For exemple add a button in home.component.html
<button class="btn btn-primary">Jhipster</button>

in global.scss add :

.btn {
    color:#28a745;
}

In v4 the text button is green, in v5 it's white. 

##### **JHipster Version(s)**

Seen in all jhipster 5 versions.

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "gateway",
    "baseName": "bug",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.15.2 (Apple Git-101.1)

node: v8.11.3

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.7.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 5a3f1a3

##### **Browsers and Operating System**

Not browser specific

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ndywicki** [comment]
Hello,

Ok I'm not crazy ! ;-)
Same issue also with our Jhipster migration v4 to v5.
Our corporate style sheet imported a the end of the global.scss but is loaded before the boostrap.

I've also tried an `yarn run webpack:build`

**Comment by vishal423** [comment]
@jdordoigne, If you want to override bootstrap styles, then, you should add those overrides to `bootstrap-variables.scss` which is loaded before bootstrap in global.scss and correctly override the defaults.

**Comment by vishal423** [comment]
I do see an issue as `bootstrap-variables.scss` filename should be `_bootstrap-variables.scss` as it's partial. I will look into that

**Comment by deepu105** [comment]
@jdordoigne, @vishal423 is right. You are doing it at the wrong place. This is documented on the webiste as well https://www.jhipster.tech/customizing-bootstrap-4/

@vishal423 yes the partial file is better with `_` in front but I think it works without as well. Please do PR if you like to change that. I'm closing this one as its not an issue

**Comment by deepu105** [comment]
@vishal423 seems like its my bad. I guess I introduced the issue. I just fixed it now partials should be correct

**Comment by vishal423** [comment]
With latest master, I am seeing below error for angular monolithic project. I just upgraded my node version to 8.11.3. Any clue?

> error An unexpected error occurred: "Reduce of empty array with no initial value".                                                           
> info If you think this is a bug, please open a bug report with the information provided in "/home/vishal/vishal/test/amono/yarn-error.log".  
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.                                                     
> yarn run v1.7.0                                                           
> $ yarn run cleanup && yarn run webpack:build:main                                             
> $ rimraf target/{aot,www}                                                                            
> /bin/sh: 1: rimraf: not found                                                                        
> error Command failed with exit code 127.                                                                    
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                         
> error Command failed with exit code 1.
