### ISSUE TITLE
Getting JHipster to work in AWS Elastic beanstalk

### ISSUE THREAD

**Issue by hooligan495** [jhipster/generator-jhipster#789]
I'm trying to get a Jhipster app working in elasticbeanstalk.  In production mode.

I'll fill this out with the steps I've been taking.

first some setup points:
I've used a combination of the eb CLI utility and the elasticbeanstalk web site too.  I haven't figured out how to script it all.

if you are using eb deploy you have to remember to commit your changes before deploying. 

If you are using an RDS instance your production yaml must have the database parameters set to something like this:

```
    databaseName: ${RDS_DB_NAME}
    serverName: ${RDS_HOSTNAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
```

**Comment by davykiala** [comment]
@hooligan495  did you succeed to deploy on AWS. if yes, could you explain how did you ? Thanks

**Comment by vw98075** [comment]
hooligan495 I am interested in this topic too. Deploying to AWS Beanstalk is more meaningful than Cloudfoundry to me. Please sharing your experience.

**Comment by wuethrich44** [comment]
@vw98075 This PR https://github.com/jhipster/generator-jhipster/pull/1686 will be merged soon. If you need any help I can answer your questions.

**Comment by rblazquez** [comment]
Im trying AWS deployer and get the following problem ...

"
Create S3 bucket
Bucket preveges created successful

Upload WAR to S3
War uploaded successful

Create database
Database created successful

Waiting for database (This may take several minutes)
Database available at jdbc:mysql://preveges.co5e9kgwtldd.eu-central-1.rds.amazonaws.com:3306/preveges

Create/Update application
✖ No Solution Stack named '64bit Amazon Linux 2015.03 v1.4.1 running Tomcat 8 Java 8' found.
"

**Comment by deepu105** [comment]
This issue is fixed wait for next release also read the issue threads its mentioned already

**Comment by ARAtIntBitTech** [comment]
Any tutorial on how to deploy the app on ElasticBeanStalk - AWS?

**Comment by deepu105** [comment]
Check the Aws sub generator
