### ISSUE TITLE
UAA support in React

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#7890]
I was fearing this would be the case. When doing react on UAA, it tries to do it the JWT way, what of course cannot work.

A few points here:

- [x] You cannot login over the UAA endpoint
- [ ] The react app handles JWT in local/session storage

I will do a PR to bring UAA support to react. While I will find further sub-issues, I'll note them down here.

**Comment by xetys** [comment]
OK that's a bit different: you can log in, but the axion interceptor sends access tokens if there are some left (you will see it if you work with both, ng and react apps on localhost)

And it totally ignores "remember me", which has a real implementation using OAuth2 refresh token grant in UAA.

so:

- [ ] Add Remember Me support

**Comment by xetys** [comment]
Because of the cookie handling, here's one more:

- [ ] UAA gateway needs proper CSRF handling to make write requests

**Comment by ruddell** [comment]
I fixed the gateway functionality when using UAA auth in #7939, fixing the localstorage issue mentioned in your second post in #7940

CSRF is handled by the cookie and it looks like it's working.

About refresh tokens- they are handled by the gateway when a token is near expiration in [RefreshTokenFilter.java](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/web/filter/RefreshTokenFilter.java.ejs).  Is that not working anymore?

**Comment by vishal423** [comment]
@ruddell , regarding CSRF handling, I believe, the pending item was related to passing `X-XSRF-TOKEN` header along with 'XSRF-TOKEN' cookie (angular HttpClient implicitly does this). Can you check if that's also done?

**Comment by xetys** [comment]
@ruddell no that's working fine
 btw thanks a lot for the help on this issue here! 

About the CSRF stiff, that was somehow strange when I tested it...it didn't work for the few first requests, but later it worked. I also couldn't reproduce it later then. I will try out your two PRs tonight, and if all these points are made, I'll close this issue.

**Comment by vishal423** [comment]
I believe my last PR should cover the remaining part. `X-XSRF-TOKEN` header is added by default by axios just like angular, so, no specific handling required.
