### ISSUE TITLE
Must remove the .yo-rc.json file if app is ever generated in the home directory

### ISSUE THREAD

**Issue by wilsonjl5** [jhipster/generator-jhipster#7896]
##### **Overview of the issue**

When creating a test application for jHipster 5 I accidentally generated the app in my home directory. After noticing my mistake, I removed the files and created a new directory for my application. When trying to generate it I ran into the following issue: the previously generated project's .yo-rc.json file is being used as the config for any and all jHipster projects regardless of where they exist.

##### **Motivation for or Use Case**

First-time users are likely to encounter this problem. 

##### **Reproduce the error**

Generate a new app in your home directory. Then try generating another application anywhere else. You will see something similar to the screenshot below.
<img width="839" alt="screen shot 2018-06-29 at 12 05 55 pm" src="https://user-images.githubusercontent.com/7031213/42102759-eb083096-7b94-11e8-923c-800a811c17e9.png">

##### **Related issues**

None, that I could find.

##### **Suggest a Fix**

A work-around: if you want to generate an app elsewhere on your computer, outside of your home directory, was to remove this hidden file (.yo-rc.json) **from the home directory** via command line.
`
rm .yo-rc.json
`

##### **JHipster Version(s)**

```
myapplication@0.0.0 /Users/leighawilson/Desktop/Ippon/Jhipster/myapplication
└── generator-jhipster@5.0.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "monolith",
    "baseName": "myapplication",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

git version 2.13.1

node: v8.9.0

npm: 5.5.1

yeoman: 2.0.3

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

macOS High Sierra Version 10.13.4

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Its a yeoman feature/limitation. So basically there is nothing that we can do here. You just need to be careful.

**Comment by deepu105** [comment]
To give some more info: yeoman has this feature so that you could generate stuff from any folder of your app. 

Also we print a message at the beginning to say where the app is being generated.

**Comment by pascalgrimaud** [comment]
Hi @wilsonjl5 from IpponUS :)

It happens to me several times and I hate it. 
What it could be done is to check if we are in home directory, then, displaying a very big warning.

**Comment by jdubois** [comment]
Yes I think we all hate this Yeoman "feature"!

**Comment by PierreBesson** [comment]
We could try to detect it and ask for confirmation (then it's hard to support windows, Linux and Mac OS). Also as once suggested to me by @jdubois we should create a `jhipster doctor` command to troubleshoot common problems like having a `yo-rc.json` in the home directory.
