### ISSUE TITLE
Token Exchange security vulnerability for API calls

### ISSUE THREAD

**Issue by muralihr** [jhipster/generator-jhipster#7899]
##### **Overview of the issue**

We have buillt a set of APIs which are specific to a user ; Let us say 
`/api/customerdata/**/**/11 `
Step 1 > if we send the token of the user 11 we get a proper response;

`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer token1' '//api/rental-trips/findOpenTripByMember/12'`

Now if we replace the token with the token of another user still getting the api response and also ;

`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer token2' '//api/rental-trips/findOpenTripByMember/12'`

##### **Motivation for or Use Case**
We are building a back end platform and we will make the system vulnerable and break the back end.

The APIs should insist that the token level authentication will not only allow the user to make a check - but should also warn some one is attempting to break the system.
##### **Reproduce the error**
 NA
##### **Related issues**

New vulnerability news reported exposed the firebase database and is a major news in the paper.
 https://adtmag.com/articles/2018/06/21/firebase-security.aspx
##### **Suggest a Fix**
 Generated token should be specific to a particular user and swap /exchange of the token should not be allowed.

##### **JHipster Version(s)**

 v4.14.0
##### **JHipster configuration**
+-- generator-jhipster@4.14.0 
`-- generator-jhipster-docker@2.4.0
  `-- generator-jhipster@4.14.0  deduped

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.7.4

node: v8.9.4

npm: 5.6.0

bower: 1.8.2

gulp:
[19:52:14] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.3.2

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.2, build a133471

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
NOt applicable;

##### **Browsers and Operating System**

Chrome oS
Ubuntu 14.06 
- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry but I'm not sure I get what you mean - are you using JWT authentication? In that case, if you take another user's token, then you are logged in as that user, I don't get where the issue is. And what's the link with Firebase?

**Comment by muralihr** [comment]
step 1 > 
I log in with the api/authenticate with username muralihr - i get a token say token1 and a user ID say 11
then i log in as user jdubois1 - i get a token say token 2 - and user Id say 12;
Now my API is having the userId as the input ;
so/ api/userId/11/data/x can be accessed by both 11 and 12 if they use a valid token irrespective of the userId;

**Comment by ruddell** [comment]
This is an issue with how you secured your endpoints, I'm guessing you only made sure the user requesting has the ROLE_USER which means any user can request any other user's endpoint.  

I see two options:
 - Instead of having the userId as a request parameter (which anyone can change), get the current user through [SecurityUtils.java](https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/java/io/github/jhipster/sample/security/SecurityUtils.java#L17-L34) and make your database queries based on that value.
 - Use Spring Security's `PreAuthorize` or `PostAuthorize` methods ([docs](https://docs.spring.io/spring-security/site/docs/3.0.x/reference/el-access.html)) to ensure only the user with the matching userId can make the request.

I don't see how this is an issue with the generator though.

**Comment by muralihr** [comment]
OK ~ Thanks ~ I had forgotten about PreAuthorize and PostAuth from spring and wanted Jhipster to generate the PreAuthorize and PostAuth  filters for all APIs ~  My suggestion was the design in jhipster to include PreAuthorize and PostAuth ; 
Thanks @ruddell

**Comment by muralihr** [comment]
Found one more way to do the job ~

http
		.authorizeRequests()
				.antMatchers("/user/{userId}/**").access("@webSecurity.checkUserId(authentication,#userId)")

**Comment by muralihr** [comment]
Additional http://www.baeldung.com/spring-security-method-security

@PostAuthorize("#username == authentication.principal.username")
public String getMyRoles2(String username) {
    //...
}
