### ISSUE TITLE
alertAsToast located Behind of the ElasticSearch panel

### ISSUE THREAD

**Issue by manisi** [jhipster/generator-jhipster#7902]
when set  alertAsToast :true  the messages of alert rise  back of search panel .
<img width="1374" alt="screen shot 2018-06-30 at 22 58 33" src="https://user-images.githubusercontent.com/3120328/42128209-46a04ff2-7cbb-11e8-8427-362504cf42bf.png">

##### **JHipster Version(s)**
jhipster 5.0.1

##### **JHipster configuration**

```
sample-5@0.0.0 /Users/developer/Desktop/sample5
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0",
    "applicationType": "monolith",
    "baseName": "sample5",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fa"
    ]
  }
}
</pre>
</details>

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I think some zIndex issue

**Comment by manisi** [comment]
@deepu105  Thanks, that was exactly

**Comment by sendilkumarn** [comment]
@manisi Will you be interested in doing a PR for this ?

**Comment by manisi** [comment]
@sendilkumarn  ok ,thanks.
