### ISSUE TITLE
Upgrade to Yeoman 3

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7909]
See https://github.com/yeoman/generator/releases/tag/v3.0.0

**Comment by deepu105** [comment]
From release notes it doesnt look like a major change for us. I'll try to
do this when I find time. I upgraded all dependencies today morning but
this want released then I guess

Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
@deepu105 @jdubois 
> For users of the Yeoman API: generator.run() now returns a promise as well as taking a callback (the callback will keep working for the foreseeable future as we need to maintains backward compatibility with older generators)

This is like christmas for me, as when we'll bump the version I'll finally be able to implement multi-application generation.

**Comment by deepu105** [comment]
@MathieuAA its done. I'm not sure what you meant by that this upgrade will help you, coz from what I understand they just return promise now, along with the callbacks they already have, so instead of passing callbacks as arguments now you can pass them as promise.then

**Comment by MathieuAA** [comment]
They had callbacks? Funny, didn't find suitable examples of that. I thought they added callbacks & promises in that version

**Comment by deepu105** [comment]
yup they had http://yeoman.io/generator/Generator.html#run
