### ISSUE TITLE
Sonar vulnerabilities: D

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#7911]
See https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application

Sonarcloud has probably changed some rules.
So currently, we got a `D` for vulnerabilites.

We need to fix that

**Comment by PierreBesson** [comment]
It seems that Sonar introduced a new role about entities returned directly from controllers : https://sonarcloud.io/organizations/default/rules?open=squid%3AS4684&rule_key=squid%3AS4684

This is a well know debate (I have seen this discussed many times on Twitter) and I'm sure @jdubois has an opinion on the subject. I personally would not say it is a vulnerability but some people have a strong view against it.

A simple way to fix it would be to force DTOs for all apps.

**Comment by cbornet** [comment]
The other one where we disable csrf looks like false positive to me: we also configure the session to be stateless. We should open an issue on sonar for that.

**Comment by jdubois** [comment]
I am strongly against having DTOs by default: for me they unnecessarily complicate the design, and usually hinder performance. This is against our goal of simplicity, and one of reasons why generators in the Java world (which typically use DTOs) have been less successful than those in alternative languages (which usually don't do DTOs).
Then, of course you need DTOs when your project grows or when your business logic becomes more complex, but I would keep this as optional and let the user decide what is best for him.
We should first remove the beta tag on DTOs: what we do isn't perfect but it's been out for so long it must be good enough for most people. 
Then for Sonar, I don't really like this but the easiest solution is indeed to generate an app with DTOs everywhere.

**Comment by cbornet** [comment]
> Then for Sonar, I don't really like this but the easiest solution is indeed to generate an app with DTOs everywhere.

Or exclude the rule if we don't agree with it.
We always validate our input with JSR303 `@Valid` so it's again a false positive for me...

**Comment by jdubois** [comment]
Yes agreed @cbornet - I guess you mean modifying the property in the pom.xml ? Let's do this, so we keep having Sonar on our sample app, which is nicer.

**Comment by PierreBesson** [comment]
+1 @cbornet and even if we changed the sample app, people would notice this on their own apps anyway.

**Comment by gmarziou** [comment]
What about excluding this rule in pom.xml only if DTO option is not enabled ?

**Comment by cbornet** [comment]
DTO is an entity option, not an app one

**Comment by gmarziou** [comment]
Right :) Though in JDL you can enable it on all entities using `*` as other entity options.

**Comment by jdubois** [comment]
Oh I just saw the CSRF error, and indeed that's a false positive.

I don't have any solution for this, unless we enable the check again. Maybe that could be useful for some people. Of course there should be a small performance hit, and that token could be misleading for some people (who will think it's doing something).

With those new issues I feel that Sonar is going too far, and that makes them send a lot of false positives. That's annoying for us as we rely on them.

**Comment by pascalgrimaud** [comment]
@jdubois : so what should we do for the CSRF error ? Should we add to ignore list the rule https://sonarcloud.io/coding_rules?open=squid%3AS4502&rule_key=squid%3AS4502 ?

**Comment by jdubois** [comment]
Yes @pascalgrimaud we should ignore it: for JWT tokens we are not subject to CSRF attack (we are vulnerable to XSS, not CSRF). As we have no session at all, that's not possible to have such an attack. I even tested it, to be totally sure, and my attack failed.

**Comment by pascalgrimaud** [comment]
Ok, I will do another PR tonight for this, so we can close this ticket
