### ISSUE TITLE
Remove moment.js

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#7932]
##### **Overview of the feature request**

Moment.js is quite large and I think we should try to get rid of it and provide a smaller alternative. I think day.js seems like a good alternative

##### **Motivation for or Use Case**

Our bundles are quite large and we should keep it as small as possible. With that we can save for angular around 20kb gzipped. (224kb with moment and 3 locales vs 210kb with dayjs). I also tried that for react, it works well for our react library, but sadly `availity-reactstrap-validation` depends on moment, so we can't get rid of it without finding an alternative validation library.

![screenshot_2018-07-05 webpack bundle analyzer](https://user-images.githubusercontent.com/203401/42346640-9f274a86-80a3-11e8-9c8e-8f8b78ebcbac.png)

![screenshot_2018-07-05 webpack bundle analyzer-after](https://user-images.githubusercontent.com/203401/42346651-abe19808-80a3-11e8-966b-c24208960d52.png)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
We should investigate potential replacements:

- [date-fns](https://date-fns.org/) (based on the native JS Date type)
- [jd-joda](https://github.com/js-joda/js-joda) (custom implementation of a date API in JS that map to java 8 date types)
- [dayjs](https://github.com/iamkun/dayjs) (same API as moment)

**Comment by atomfrede** [comment]
I would either go with date-fns or dayjs as jd-joda mimics the quite complex java api :) Personally I prefer dayjs as it replaces moment quite easily for many functions and can be extended via plugins.

**Comment by PierreBesson** [comment]
Oh and one thing I don't like about moment (or maybe it is a problem about js itself) is that the locale format is not the same as the java one ex "fr-FR" vs "fr_FR", currently composite locale i18n is broken on our backend i18n because of this.

**Comment by atomfrede** [comment]
Oh yes I know :)

**Comment by wmarques** [comment]
I often use `date-fns`, it does the job and doesn't need any webpack config to handle locales so that's a pretty good alternative IMO

**Comment by jdubois** [comment]
I think we all agree on replacing moment.js, but nobody has the time to work on this, and this is also going to be quite a burden for our users, as they will have a big migration cost.

That's why I think we should close this, and maybe talk about this again when we plan our next major release.
