### ISSUE TITLE
Bug in multiselect when using react and many-to-many relationship

### ISSUE THREAD

**Issue by clement26695** [jhipster/generator-jhipster#7943]
##### **Overview of the issue**

This bug concern the multi select in react. I created 2 entities, book and author, and a many-to-many relationship between these two entities. When I try to create a book, I can't select the authors I want to associate to this book. I think the error is coming from (not ?) parsing the option id in authorsUpdate (<%= relationshipFieldName %>Update) from string to number in the book-update.tsx (entity-update.tsx.ejs).  

##### **Motivation for or Use Case**

Same as the previous section.

##### **Reproduce the error**

1. Create a JHipster application with Jhipster v5.0.2 with the enclosed .yo-rc.json
2. Import the enclosed jdl file with the two entities
3. Create one or two basic authors
4. Try to create a book in relation to an author

##### **Related issues**

I don't think there was a similar issue reported before.
 
##### **Suggest a Fix**

I fixed my issue by changing the line 67 in my book-update.tsx file (on line 213 in entity-update.tsx.ejs) from : 
`const selected = Array.from(element.target.selectedOptions).map((e: any) => e.value, 10);`
to : 
`const selected = Array.from(element.target.selectedOptions).map((e: any) => parseInt(e.value, 10));`

##### **JHipster Version(s)**

Jhipster v5.0.2

##### **JHipster configuration**

**`jhipster info` :**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test-jh-5@0.0.0 /Users/clementdessoude/Documents/Personal/Dev/testJ5
└── generator-jhipster@5.0.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jhipster.test",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.2",
    "applicationType": "monolith",
    "baseName": "test-jh5",
    "packageName": "com.jhipster.test",
    "packageFolder": "com/jhipster/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Book (book) {
  title String,
  publication LocalDate
}
entity Author (author) {
  firstName String,
  lastName String
}
relationship ManyToMany {
  Book{authors} to Author{books}
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.16.2

node: v10.1.0

npm: 5.6.0

yeoman: 2.0.2

yarn: 1.6.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.0, build 5920eb0

Congratulations, JHipster execution is complete!
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

**Book entity :** 
{
    "name": "Book",
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String"
        },
        {
          "fieldName": "publication",
          "fieldType": "LocalDate"
        }
    ],
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "books",
            "relationshipName": "authors",
            "otherEntityName": "author",
            "otherEntityField": "id",
            "ownerSide": true
        }
    ],
    "changelogDate": "20180707224958",
    "entityTableName": "book",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}

**Author entity :** 
{
    "name": "Author",
    "fields": [
        {
            "fieldName": "firstName",
            "fieldType": "String"
        },
        {
            "fieldName": "lastName",
            "fieldType": "String"
        }
    ],
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "relationshipName": "books",
            "otherEntityName": "book",
            "ownerSide": false,
            "otherEntityRelationshipName": "authors"
        }
    ],
    "changelogDate": "20180707224959",
    "entityTableName": "author",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}

##### **Browsers and Operating System**

I'm on macOS High Sierra and found the bug in Google Chrome and Safari.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I thought @agaspardcilia or @chrisdns did something around this to fix an issue. Are these related?

**Comment by agaspardcilia** [comment]
It might be some side effect from my last fix. It shouldn't take long to fix.

**Comment by agaspardcilia** [comment]
You seem to have find a fix @clement26695. Would you mind making a PR for it?

**Comment by clement26695** [comment]
Yeah, sure ! I'll try to do that this afternoon or tomorrow.
