### ISSUE TITLE
Blueprint - Entity Generator Issues

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#7956]
##### **Overview of the issue**

Check out jhipster/jhipster-kotlin#36

##### **Reproduce the error**

Check out jhipster/jhipster-kotlin#36

##### **Suggest a Fix** || **Suggesting what could be the issue**

* Using this [method](https://github.com/jhipster/generator-jhipster/blob/05040a24a9b650ac82d33cf4f16091edfa8d3f21/generators/entity/index.js#L808)  inside blueprint is not binding the `this` object correctly.
* This makes https://github.com/jhipster/generator-jhipster/blob/05040a24a9b650ac82d33cf4f16091edfa8d3f21/generators/entity/index.js#L819 to not work properly.

I am not too sure but modifying these areas make it work.

##### **JHipster Version(s)**

The latest and greatest.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@sendilkumarn : recently, with Deepu, we fixed some issues with blueprint. It is released with generator-jhipster 5.1.0, so maybe the kotlin generator must upgrade from 5.0.2 to 5.1.0 ?

**Comment by deepu105** [comment]
@pascalgrimaud this was a different issue

**Comment by deepu105** [comment]
Well, some healthy competition is good for the project :P

Thanks & Regards,
Deepu
