### ISSUE TITLE
Is Node.js Backend on the Roadmap? :)

### ISSUE THREAD

**Issue by yatendragoel** [jhipster/generator-jhipster#7965]
##### **Overview of the feature request**
The way we have an option between React and Angular on the frontend side, Is Node.js backend as an alternative option for SpringBoot backend on the roadmap?

##### **Motivation for or Use Case**
React frontend goes hand-in-in with Node.js backend

**Comment by pascalgrimaud** [comment]
No, NodeJS as a backend, is not on our roadmap.
But have a look at https://www.jhipster.tech/modules/creating-a-blueprint/

Now, you can code a specific generator for the backend, similar to what is done with Kotlin (see https://github.com/jhipster/jhipster-kotlin)
Don't hesitate to tell us if you decide to start this blueprint. I'm pretty sure you can find people for contributing.

**Comment by jdubois** [comment]
Yes, we also have people who want a Java EE, PHP and .NET backend... We just can't do everything, but we welcome and will help people doing those projects.

**Comment by alexplacinta** [comment]
in case if is a chance for nodejs backend i highly recommend NestJS(https://github.com/nestjs/nest)

**Comment by dave0688** [comment]
I agree with @alexplacinta. NestJS is an awesome framework, growing extremely fast, and plus: Typescript 💃

**Comment by deepu105** [comment]
I wanted to do a NodeJS blueprint for the microservice backend for a while now but I don't have the bandwidth to do it alone. If anyone is interested in starting one I'll be happy to help

**Comment by amanganiello90** [comment]
@deepu105 I'm interested to start a nodeJS blueprint, so that we can extend the jhipster generation also for electron desktop app

**Comment by deepu105** [comment]
Awesome, let me create a repo and give you access to it.

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
@amanganiello90 here is the repo, you can do PRs to begin with. I'll later give you write access to it.

**Comment by amanganiello90** [comment]
@deepu105  thanks, I was already starting in a my repo :)

**Comment by deepu105** [comment]
@amanganiello90 you should have write access to that repo now
