### ISSUE TITLE
Swagger UI latest version support (3.17.3)

### ISSUE THREAD

**Issue by abhinav910** [jhipster/generator-jhipster#7966]
##### **Overview of the feature request**

Swagger UI very old version (2.2.10) is used which does not provide the support for Open API

##### **Motivation for or Use Case**

Open API support

**Comment by pascalgrimaud** [comment]
I don't remember well why we didn't upgrade but there was a reason.

Ping @cbornet as I'm pretty sure you know the answer :-)

**Comment by gmarziou** [comment]
Even if we updated swagger-ui to 3.17.3, you would not get openapi support because it's not supported by springfox.

**Comment by cbornet** [comment]
Indeed, Springfox doesn’t support OpenAPI yet. We didn’t migrate to the new UI at the time because there was no easy way to pass the auth token. It seems there are solutions now. But do we want to move to the new UI ? I’m not sure I prefer it over the current one :smile:

**Comment by deepu105** [comment]
Yes, we didn't migrate since the new version lacked some features which
were available in the old version.

Here is the PR where I attempted to upgrade
https://github.com/jhipster/generator-jhipster/pull/5645

But then we cant stay with the old version forever and would have to
upgrade at some point. If someone can revive the PR and fix the outstanding
items it would be great.

Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
I am against migrating to swagger UI 3. The UI is awful and does not bring any new features (that I know of). I would rather move to ReDoc to provide API documentation (but the interactive querying is not possible yet).

In the end, we have something that work really well for now. So I'm not so keen on changing things and risk making things worse.

**Comment by jdubois** [comment]
Following @PierreBesson advice, I'm closing the ticket

**Comment by abhinav910** [comment]
I guess @deepu105 already did some work for Swagger UI v3. The current UI does not provide the support for Open API json but v3 UI provides the support. I have checked both the version.

I thought jhispter always provide the support for latest version of components. My two cents.

**Comment by deepu105** [comment]
@abhinav910 as @cbornet highlighted even if we update the UI lib it still wouldn't work since spring fox doesn't support it yet. I think we can do the upgrade once spring fox supports openAPI. Personally, I don't have any issue with the new UI, but it does lack some features compared to the old one.

And we would never support something just coz its new, it needs to be justified as well, in most cases new is better but sadly in this case, new UI doesn't even have some features from the old one

**Comment by cbornet** [comment]
@abhinav910 Swagger UI is "just" the front-end part. The lib that generates the OpenAPI/Swagger spec is [Springfox](http://springfox.github.io/springfox/) and it currently doesn't generate OAIv3 specs (see https://github.com/springfox/springfox/issues/2124). As soon as springfox supports OAI, be sure that JHipster will do the upgrade. But for now there's no rush.
Also note that the "API first" option already work with OAIv3 specs.

**Comment by deepu105** [comment]
I guess its time to do this as we have started to get the deprecation warning during yarn install

warning swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.

**Comment by PierreBesson** [comment]
Personally, I still dislike Swagger UI v3. I would prefer to migrate to Redoc: https://github.com/Rebilly/ReDoc
Sadly it doesn't yet feature a "try it out" button.

**Comment by jdubois** [comment]
@PierreBesson Redoc indeed looks cool, I didn't know about it. @cbornet you're the boss here, what do you think is best?

**Comment by deepu105** [comment]
Try it out is the most important feature else we could even do static docs
instead of a living page, and I personally don't think the new UI is bad,
its just not as feature rich as the old one. So IMO migration would be the
best choice

**Comment by cbornet** [comment]
Yes, it's probably time to migrate. See https://github.com/swagger-api/swagger-ui/issues/2915#issuecomment-376245104 for how to pass the auth token to swagger-ui.

**Comment by PierreBesson** [comment]
OK let's do it. But we need to take the occasion to try to better integrate the swagger ui into the app (as an angular/react component). And we should make it optional to include it into the front-end assets.

**Comment by jdubois** [comment]
Yes totally agree! @PierreBesson are you willing to do it? Who is interested?

**Comment by jdubois** [comment]
I'm adding a [bug bounty](https://www.jhipster.tech/bug-bounties/) on this ticket as I think it's important, and there's a significant amount of work

**Comment by murdos** [comment]
Have you considered using the springfox-swagger-ui maven dependency?
It still uses Swagger UI 2.x, but it will follow Springfox lifecyle and ability to handle OpenAPI.
And it should ease our task by not maintaining our own Swagger UI, no?

**Comment by deepu105** [comment]
The reason we have our own is the different auth mechanism we support, you
have to provide JWT tokens and stuff to use the try it out feature, which
I'm not sure you can do with those plugins.

Thanks & Regards,
Deepu

**Comment by DanielFran** [comment]
@cbornet It seems that support for oas-3 is pratically done in https://github.com/springfox/springfox/tree/feature/2022/oas-3-support

**Comment by cbornet** [comment]
Yes. That's for the backend part and will be part of Springfox 3. This issue is about swagger UI for which we can already migrate.

**Comment by edceo** [comment]
If you add springfox-swagger-ui in only backend jhipster project, you will reach swaggerUI with http://localhost:8080/swagger-ui.html

**Comment by PierreBesson** [comment]
Maybe we could consider migrating to RapiDoc (https://mrin9.github.io/RapiDoc/) as I'm not a big fan of Swagger UI v3.

**Comment by jdubois** [comment]
I'm doubling the bug bounty here, as this is important and has been stuck for a long time

**Comment by DanielFran** [comment]
What about using this project: http://springdoc.org

Does it cover all our needs?

**Comment by cbornet** [comment]
Interesting. Seems more like a replacement to Springfox.

**Comment by PierreBesson** [comment]
At first glance SpringDoc looks like a much less advanced version of Springfox, I don't see how we could extend it to support the various auth schemes that we have. It also seems like it is based on the swagger-ui webjar.

**Comment by ecostanzi** [comment]
Indeed springfox has many more features. I think it's a little bit early to consider springdoc as a replacement. 

[Springfox upgrade to openAPI 3](https://github.com/springfox/springfox/issues/2022) seems to have been almost abandoned . However there's an [interesting comment](https://github.com/springfox/springfox/issues/2022#issuecomment-504898088) suggesting to use [SwaggerConverter](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java)  to convert v2 specs to openapi specs. It could be a workaround while waiting for springdoc to evolve.

**Comment by DanielFran** [comment]
I also consider it premature but it seems a good project that is starting and growing quickly.

**Comment by flostadler** [comment]
I'd like to tackle this issue, any heads up on where to start?

**Comment by cbornet** [comment]
Yes. Basically what's needed to be done is to update the swagger-ui version in package.json and replace the index.html with the one from the new swagger-ui. Then modify this index.html to include the passing of the auth tokens.

**Comment by cbornet** [comment]
See https://github.com/swagger-api/swagger-ui/issues/2915#issuecomment-376245104 on how to pass the token.

**Comment by cbornet** [comment]
Also some configs of the swagger-ui needs to be retreived from the Springfox endpoints. See the current index.html about that.

**Comment by flostadler** [comment]
Ok, thanks! I will give it a go

**Comment by DanielFran** [comment]
And seems like Springfox 3.0 might be out soon: https://github.com/springfox/springfox/issues/3070

**Comment by cbornet** [comment]
Dilip is asking for help. Don't hesitate to participate. Springfox is a very well-written lib. You learn a lot by contributing to it.

**Comment by Hawkurane** [comment]
Is anyone working on this? I would like to have a go at it :)
I have the UI displaying but am still working on passing the token to the swagger ui

**Comment by pascalgrimaud** [comment]
go, it was opened for too long

**Comment by Hawkurane** [comment]
@ecostanzi I've still submitted my branch as a PR so if you find anything interesting in my code we could try share point of views?

**Comment by ecostanzi** [comment]
@Hawkurane let's focus on one PR (#10567) so that the reviewers know where to look at. 

I'd keep PR #10567 (and close #10570) for the frontend part, since it already works for both frontends and fetches the list of specs from swagger resources. 

Let's discuss here: https://github.com/jhipster/generator-jhipster/pull/10567#discussion_r332115208 wether to customize springfox configuration in jhipster-framework (https://github.com/jhipster/jhipster/pull/425/) or by using a new template in the generator.  In the first case we'll have to keep both PRs open. WDYT?

**Comment by Hawkurane** [comment]
Sure, let's do that. I've closed my front part PR :)

**Comment by deepu105** [comment]
We really need this as GitHub is now always giving a moderate sev security vulnerability for Swagger UI

![image](https://user-images.githubusercontent.com/1107223/70925077-ee7b6180-202a-11ea-9e17-2e28249c4541.png)

**Comment by PierreBesson** [comment]
Which is complete bullshit :angry: as using swagger ui v2 does not constitute a security vulnerability.

**Comment by deepu105** [comment]
Indeed its bullshit, but its making our apps look bad and many would think
that the generated apps are not secure by default

**Comment by pascalgrimaud** [comment]
@ecostanzi : don't forget to claim the bounty, it's well deserved

**Comment by DanielFran** [comment]
@econstanzi PR https://github.com/jhipster/jhipster/pull/425 is stilo needed?

**Comment by pascalgrimaud** [comment]
As I don't need it during my test, I don't think so @DanielFran

**Comment by ecostanzi** [comment]
@DanielFran I think we can closed it, we postponed openapi security definitions for v7
