### ISSUE TITLE
React: saving failed when using relationship to Jhipster User

### ISSUE THREAD

**Issue by lutfi198** [jhipster/generator-jhipster#7967]
##### **Overview of the issue**

I am using example from https://github.com/mraible/jhipster5-demo. I used Postgresql for dev and pro. Project with entities are generated successfully.

When I create new Blog and saving, i got this error.

Exception in com.asdev.blog.web.rest.BlogResource.createBlog() with cause = 'java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.asdev.blog.domain.Blog.user -> com.asdev.blog.domain.User' and exception = 'org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.asdev.blog.domain.Blog.user -> com.asdev.blog.domain.User; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.asdev.blog.domain.Blog.user -> com.asdev.blog.domain.User'

##### **Motivation for or Use Case**

I used previous jhipster 4* and worked

##### **Reproduce the error**

Run the example then create new Blog 

##### **JHipster Version(s)**

```
blog@0.0.0 /Volumes/Data/*
└── generator-jhipster@5.1.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.asdev.indag.umkm"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "monolith",
    "baseName": "blog",
    "packageName": "com.asdev.indag.umkm",
    "packageFolder": "com/asdev/indag/umkm",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog (blog) {
  name String required minlength(3),
  handle String required minlength(2)
}
entity Entry (entry) {
  title String required,
  content TextBlob required,
  date Instant required
}
entity Tag (tag) {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User,
  Entry{blog(name)} to Blog
}
relationship ManyToMany {
  Entry{tag(name)} to Tag{entry}
}

paginate Entry, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.15.2 (Apple Git-101.1)

node: v10.6.0

npm: 6.1.0

yeoman: 2.0.2

yarn: 1.7.0

##### **Browsers and Operating System**

OSX 10.13.5, Safari, Chrome

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by lutfi198** [comment]
i tested with 5.0.1, works good too

**Comment by ruddell** [comment]
I tested with the v5.1.0 and master and couldn't reproduce.  In v5.1.0, there's a role restriction [on getting users from the api](https://github.com/jhipster/jhipster-sample-app/blob/a9b789f832b3bc508721605a66fb72e2e8edd01d/src/main/java/io/github/jhipster/sample/web/rest/UserResource.java#L145) that might be causing you issues (blog page loads the list of users), try removing that line.

**Comment by jdubois** [comment]
Please don't cross post: https://stackoverflow.com/q/51335228/150868 - time lost doing this means less time for us to answer, and it's annoying for other users.

**Comment by lutfi198** [comment]
i found the cause, there are differences between blog-update.tsx generated by 5.1.0 and 5.0.1. The difference that producing the error is

<AvInput id="blog-user" type="hidden" name="user.id" value={this.state.userId} />

5.1.0 did not generated above code. I added the code in 5.1.0 and works perfectly.

**Comment by lutfi198** [comment]
Sorry i click the wrong action button

**Comment by pascalgrimaud** [comment]
I don't understand.
In your config, you used Angular : `"clientFramework": "angularX"`
And in your last message, you mentionned `blog-update.tsx` which is related to React

**Comment by lutfi198** [comment]
that's the name of my directory. i edited my comment.

**Comment by deepu105** [comment]
cc @agaspardcilia @chrisdns
