### ISSUE TITLE
provide clear instructions for users behind corporate proxy

### ISSUE THREAD

**Issue by 62mkv** [jhipster/generator-jhipster#7977]
##### **Overview of the issue**

When trying to create JHipster application by running `jhipster`, the following WARNING occurs:

```WARNING! Failed to connect to "git://github.com"
1. Check your Internet connection.
2. If you are using an HTTP proxy, try this command: git config --global url."https://".insteadOf git://
```

I've already set this option, and the command `git ls-remote git://github.com/octocat/Spoon-Knife.git HEAD` is actually passing OK on my laptop, it just takes >75 seconds here and, probably, timeout value is less than that, thus failing the command. 

##### **Motivation for or Use Case**

I would expect to have more information here, like: how critical is this? will it somehow affect JHipster functionality later on ? what are the possible workarounds ? may be I could modify timeout value somewhere ? or set it as a option when running JHipster commands ?

##### **Reproduce the error**

1. Come into our office (just kidding; actually just setup some shitty corporate proxy with bad response time for https)
2. Set up necessary Git config (`http.proxy <proxyURL>; url."https://".insteadOf git://`)
3. Run `jhipster` in an empty folder 

##### **JHipster Version(s)**

5.1.0 

##### **JHipster configuration**

the default one, I guess

##### **Browsers and Operating System**

Windows 10 x64

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
The documentation is at https://www.jhipster.tech/configuring-a-corporate-proxy/

BTW I'm going to remove the Bower part in the documentation, that's obsolete.

If you are being a proxy, you'll probably have trouble with Maven and NPM, so a lot of stuff won't work, but that depends on what you doing in your company. Many companies have internal Maven/NPM mirrors, for example.

**Comment by 62mkv** [comment]
this documentation does not mention `git config url."https://"` part, by the way. also, proxy environment variables have to be specified as well, at least I could not find another way to get "webdriver-manager update" running. I understand that as JHipster is a mixed soup of all kind of tools, may be it's not exactly our concern here, but as users struggle with this when trying to use JHipster itself, I guess it would be great to give users more details and transparency. Link to the documentation about proxy configuration (displayed when aforementioned WARNING occurs) would also be great.

**Comment by 62mkv** [comment]
and I still don't understand - why and how is JHipster using "git://" connection to GitHub ? Is it for JHipster Marketplace ?

**Comment by pascalgrimaud** [comment]
When using JHipster, we check the git connection:
- https://github.com/jhipster/generator-jhipster/blob/master/generators/app/index.js#L175-L177
- https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base-private.js#L792-L803

It has been done because, with AngularJS, `bower` needed to pull some repositories in github. Now, with Angular and React, we don't need this, so I think it can be removed.

**Comment by jdubois** [comment]
No that must have also be for Bower, so it should be removed -> do you see my commit above? Could you do a PR to the documentation so it can be improved? We should also link to that page in the error message
