### ISSUE TITLE
Build failed: mvn clean test sonar:sonar due missing TESTS-results-sonar.xml

### ISSUE THREAD

**Issue by depzor** [jhipster/generator-jhipster#7978]
##### **Overview of the issue**

Build failure when running : 
mvn clean test sonar:sonar

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project licenses: Error during parsing of generic test execution report '<project- folder>/target/test-results/jest/TESTS-results-sonar.xml'. Look at the SonarQube documentation to know the expected XML format.: /<project-folder>/target/test-results/jest/TESTS-results-sonar.xml (No such file or directory) ##### **Motivation for or Use Case**

##### **JHipster Version(s)**
5.1.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "microservice",
    "baseName": "ab",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I already fixed this, in my PR: see https://github.com/jhipster/generator-jhipster/pull/7970/files#diff-46af807fe730aba11ead7c88e7e79a31L124

You need to remove this line, in your `pom.xml` as you use microservice and don't have the front part

**Comment by deepu105** [comment]
closing as there is another ticket to track that PR
