### ISSUE TITLE
 Infinite loading missing first page

### ISSUE THREAD

**Issue by mxxcx** [jhipster/generator-jhipster#7979]
##### **Overview of the issue**

Using infinite loading when you reach the end of the list and scroll back, the first page is missing, seems to be a react-hipster 0.5.4 error and it didn't happened it 0.5.3. The bellow gif should make it clearer.

https://gyazo.com/77511857f6509b190ad336eb8898b22e

##### **Motivation for or Use Case**

I don't think is the intended behavior, at least it wasn't like this in 5.0.2

##### **Suggest a Fix**

Problem seems to be here `entities: loadMoreDataWhenScrolled(state.entities, action.payload.data, links, ITEMS_PER_PAGE)` or the `link` header 

##### **JHipster Version(s)**

5.1.0

##### **JHipster configuration**

`{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.name.name",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "monolith",
    "baseName": "name",
    "packageName": "com.name.name",
    "packageFolder": "com/name/name",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "key",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}`

##### **Browsers and Operating System**

macOS/chrome

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
could you please follow our guideline :anger: 

cc @agaspardcilia

**Comment by mxxcx** [comment]
it doesn't happen with all entities, don't see what other info I can give, the gif should explain the issue.

**Comment by deepu105** [comment]
@mxxcx its easy for you to think that the given info is enough (it might be in this particular case) but often we end up wasting time due to a small piece of missing info and that's why we have issue submission guidelines and we expect you to respect them. We built the `jhipster info` command to make it easy for you to provide this. I don't think we are expecting anything unreasonable form the users here. So please respect our project guidelines and provide full info asked for regardless of what you think is needed or not.

**Comment by deepu105** [comment]
@mxxcx also there was some fixes around this area recently from @agaspardcilia so can you please test the current master branch and see if the issue still exists

**Comment by mxxcx** [comment]
From what I see, the issue is in the react-jhipster plugin `loadMoreDataWhenScrolled` function, which you can also see bellow:
https://gyazo.com/a9e45cc2563da12bc09e3cea30f0b393

After 3rd page if there is a 4th page `(links.first === links.last)` false,  it tests `if (incomingData.length === currentData.length)`.

Since current is 40 and incoming is 20 is goes into the `else` and test `if (incomingData.length === itemsPerPage) {` since that is `true` it just returns the new data in ` data = incomingData;` 

Why it would just return the new data if `incomingData.length === itemsPerPage`?

**Comment by agaspardcilia** [comment]
@deepu105 You must be mistaking me for @chrisdns, I never did anything on pagination.

**Comment by deepu105** [comment]
@mxxcx if you know the root cause can you submit a PR with the fix?

**Comment by deepu105** [comment]
Sorry @agaspardcilia, indeed it was @chrisdns

**Comment by mxxcx** [comment]
@deepu105 I can't understand why it was done like this, the naive fix may be to not test `if (incomingData.length === itemsPerPage) { data = incomingData; }` and just concatenate, current data/new data but I think there must be some reason.

**Comment by chrisdns** [comment]
I will fix that

**Comment by chrisdns** [comment]
@mxxcx would you mind testing out this pull request ? There are also some changes in react-jhipster lib

**Comment by mxxcx** [comment]
@chrisdns Why something as simple as this won't do it? 
https://gyazo.com/2590d6249ca8ec251b065eccf94b896b

**Comment by chrisdns** [comment]
@mxxcx check out the react-jhipster lib, i have created a pull request with your requested changes, but this would not work with the generator code as is with the delete/edit/create stuff, that's why i made some other changes on the generator to manage this. I was trying to do it all in loadMoreDataWhenScrolled but that was not the solution, now it should be good

**Comment by mxxcx** [comment]
@chrisdns looks good
