### ISSUE TITLE
Logout doesn't close the session on KeyCloack

### ISSUE THREAD

**Issue by cmoine** [jhipster/generator-jhipster#7980]
##### **Overview of the issue**

Logout doesn't close the session on KeyCloack. As a result, when we click on "Login" just after a "logout", 
Keycloack (probably other OAuth servers as well) re use the previously opened token.

##### **Motivation for or Use Case**

- security issues obviously
- We cannot logout/login to another user, which is quickly very annoying (I need to login to KeyCloack admin console to logout the user manually)

##### **Reproduce the error**

- Generate JHipster application with OAuth
- Login using admin/admin
- Logout
- Login again
=> No login/password is prompted, and admin is now logged in.

##### **Related issues**

None imho

##### **Suggest a Fix**

Could this help: http://www.baeldung.com/logout-spring-security-oauth
To be honest, I am not a security expert, so I would like to know the good practice to have here. I don't want to hardcode the logout API of keycloack, because it could be Google or Facebook OAuth maybe ?

##### **JHipster Version(s)**

```
jhipster-5@0.0.0 C:\tmp\jhipster5
`-- generator-jhipster@5.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "monolith",
    "baseName": "jhipster5",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.17.1.windows.2

node: v8.11.2

npm: 5.6.0

yeoman: 2.0.2

yarn: 1.6.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 7641a569

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**

- Windows 10 64bits
- Chrome 67

**Comment by pascalgrimaud** [comment]
Maybe duplicate of https://github.com/jhipster/generator-jhipster/issues/6941 ?

**Comment by cmoine** [comment]
Yes, correct, I guess you can close this ticket, sorry for this.
