### ISSUE TITLE
confusing wording in JHipsterConstants

### ISSUE THREAD

**Issue by 62mkv** [jhipster/generator-jhipster#7990]
##### **Overview of the issue**

The code for JHipsterConstants (as generated by monolithic application generator) contains these lines:

```
    // Spring profile used to disable swagger
    String SPRING_PROFILE_SWAGGER = "swagger";
    // Spring profile used to disable running liquibase
    String SPRING_PROFILE_NO_LIQUIBASE = "no-liquibase";
```
One would expect to either have `SPRING_PROFILE_SWAGGER` *enable* Swagger, or have it called `SPRING_PROFILE_NO_SWAGGER`

##### **Suggest a Fix**

depends on the actual implementation of this profile

##### **JHipster Version(s)**

5.1.0

##### **Browsers and Operating System**

Win 10 x64

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes indeed -> by default you have "swagger", and with "no-swagger" you remove it

**Comment by deepu105** [comment]
@62mkv would you like to do a PR to correct it?

**Comment by 62mkv** [comment]
I guess that @jdubois has different suggestion in mind. Judging by his comment

**Comment by 62mkv** [comment]
wth I have no idea I was closing this
