### ISSUE TITLE
Server side application generation should not include webapp and other files

### ISSUE THREAD

**Issue by abiton** [jhipster/generator-jhipster#7994]
##### **Overview of the issue**

I use `jhipster server` to generate a server side application, but get webapp and other pages, js files, which should not be here.

I use `jhipster import-jdl <some.jh> for the above project, the generator try to generate some page file and get a error:
```
npm ERR! path /<project_full_path>/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/<project_full_path>/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
```
##### **Motivation for or Use Case**

server-side app just for rest-api

##### **JHipster Version(s)**

5.1.0

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "<package_name>",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "monolith",
    "baseName": "< base_name >",
    "packageName": "<package_name>",
    "packageFolder": "< package_folder >",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "7efba186e608f080f3f48922bdac469a3df77d3a",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn"
    ]
  }
}
```

**Comment by ecostanzi** [comment]
Hi abiton! Did you try to use the skipClient for you jdl entities?
https://github.com/jhipster/generator-jhipster/issues/7327

**Comment by deepu105** [comment]
@abiton I suggest you use `jhipster --skip-client` rather than using `jhipster server` directly, since its for very advanced users who know how jhipster subs work. As @ecostanzi suggested in this case since you used `jhipster server` you need to pass `--skip-client` flag for other sub gens

**Comment by deepu105** [comment]
I think i'm gonna remove docs for direct usage of these subs as its better to use the flags
