### ISSUE TITLE
Add a defined name on unique constraint and OneToOne relationship on liquibase changelogs.

### ISSUE THREAD

**Issue by GuiF007** [jhipster/generator-jhipster#7995]
##### **Overview of the feature request**

All unique constraints should have a defined name in liquibase changelogs.

##### **Motivation for or Use Case**

I had the case I needed to remove a OneToOne between two relationship. So I created a change on liquibase and I was completely unable to remove this relationship when unit testing because H2 and Oracle give different default name. We fixed that giving a name to the unique constraint.

##### **Related issues or PR**
Related Issue : https://github.com/jhipster/generator-jhipster/issues/6416, https://github.com/jhipster/generator-jhipster/issues/6417
Related PR : https://github.com/jhipster/generator-jhipster/pull/6469 

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by GuiF007** [comment]
I can try to do a PR on this if you think it's necessary.

**Comment by jdubois** [comment]
That's a good idea indeed - but I'm not sure how you can have a unique name that you can reproduce (there can be several relationships for 2 entities, for example)

**Comment by deepu105** [comment]
The only way to reproduce would be to save it in the entity config json file

**Comment by GuiF007** [comment]
The idea is just to add `uniqueConstraintName="ux_*entityName*_*columnName*"` in the generated liquibase file. I don't understand why I need to save the name ?!

**Comment by jdubois** [comment]
Indeed, I might have said something stupid here.

**Comment by DanielFran** [comment]
@deepu105 @pascalgrimaud you can close this One 😜

**Comment by pascalgrimaud** [comment]
thx @DanielFran
