### ISSUE TITLE
App generation with --skip-server fails with "TypeError: Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by nagarajasr** [jhipster/generator-jhipster#8002]
##### **Overview of the issue**

i am trying to generate a jhipster app with "--skip-server" option (server was generated separately). but the generator fails with a TypeError as shown below:

```
D:\data\projects\xxxxxx\gw\client>jhipster app --skip-server --db xxxxxx --jhi-prefix zzz --npm --auth uaa
Using JHipster version installed globally
Executing jhipster:app
Options: skipServer: true, db: xxxxxx , jhiPrefix: zzz, npm: true, auth: uaa, skip-server: true, jhi-prefix: zzz

Welcome to JHipster v5.1.0

? What is the base name of your application? xxxxxx
? Which *Framework* would you like to use for the client? React
? Would you like to enable *SASS* support using the LibSass stylesheet preprocessor? No
? Would you like to enable internationalization support? No
? Besides JUnit and Jest, which testing frameworks would you like to use? Protractor
? Would you like to install other generators from the JHipster Marketplace? No
events.js:165
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at module.exports.getSharedConfigOptions (C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\client\index.js:382:94)
    at Object.<anonymous> (C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:406:18)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```
##### **Motivation for or Use Case**

i am unable to generate an app with --skip-server option

##### **Reproduce the error**

see above
##### **Related issues**

search did not reveal any similar issues

##### **JHipster Version(s)**

JHipster 5.1.0
##### **JHipster configuration**

.yo-rc.json was not generated due to above bug.

jhipster info
Using JHipster version installed globally
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
D:\data\projects\xxxxxxx\gw\client
`-- (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.16.1.windows.1

node: v9.8.0
npm: 5.6.0

yeoman: 2.0.4

yarn: 1.7.0

Docker version 18.01.0-ce, build 03596f51b1

docker-compose version 1.18.0, build 8dd22a9

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Windows 10. 
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by nagarajasr** [comment]
when i run ```yo jhipster:client --db xxxxxx --jhi-prefix zzz --npm --auth uaa```, i get an error saying ```ERROR! when using --auth uaa, a UAA basename must be provided with --uaa-base-name```
after adding the "--uaa-base-name" option, the app gets generated.
"jhipster app --help" does not indicate that uaa-base-name option must be specified
also, elsewhere i read that yo jhipster:server was meant to be used only by advanced users, is that the case with yo jhipster:client as well? if so the command jhipster app --skip-server must prompt the user for uaa-base-name option and also help text should be updated

**Comment by agaspardcilia** [comment]
This should fix your issue.

**Comment by deepu105** [comment]
@nagarajasr can you test the PR to see if its fixes the issue for you?

**Comment by nagarajasr** [comment]
the issue as reported is fixed (an error is reported if the uaa-base-name is not provided and the application is generated when it is). 

however, if the uaa-base-name is not specified, the error is reported late i.e., after all other questions are prompted. in contrast, if the db name was not specified, the error is reported immediately after the first question is prompted. i think it would be useful to have the error reported sooner. in my opinion, this is not a new issue (as it was introduced in the course of fixing this bug) but if you feel otherwise i can open another issue. thanks !
