### ISSUE TITLE
'Typical europaen' characters in login regex

### ISSUE THREAD

**Issue by co5dt** [jhipster/generator-jhipster#8004]
##### **Overview of the issue**

Login with Google is failing when Jhipster app is created with social login, in this case with Google. This happens when the Google user has 'typical europaen' characters in their name. For example, a person called Wilhelm Weiß will always fail, as jhipster will try to create a user with login _wilhelm_weiß_ .

##### **Motivation for or Use Case**

People with special characters in their first- or surname should be able to register using their Google account.

##### **Reproduce the error**

Create a Google account with where the surname contains any of the following characters:

> ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿıŒœŠšŸŽž

Then try to login. Or simply create any monolith with no 'special' configuration at all and try to create a user login containing any of the above characters.

##### **Suggest a Fix**
In generators/server/templates/src/main/java/package/config/Constants.java.ejs:
```

<     public static final String LOGIN_REGEX = "^[_.@A-Za-z0-9-]*$";
---
>     public static final String LOGIN_REGEX = "^[_'.@A-Za-z\u00c0-\u017e0-9-]*$";

```

##### **JHipster Version(s)**

4.14.1 but also present in 5.1.0

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.o33.sfm.googlecontacts",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "4.14.4",
    "baseName": "googleContactsForStarface",
    "packageName": "de.o33.sfm.googlecontacts",
    "packageFolder": "de/o33/sfm/googlecontacts",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "b3aee0a27b129742d2ea2b877105236dc22d4dbf",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de"
    ]
  }
}
```

##### **Browsers and Operating System**
Chrome, Debian

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by co5dt** [comment]
I'd love to push my changes and have read and followed the [guidlines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md), yet I currently receive:

```
remote: Permission to jhipster/generator-jhipster.git denied to co5dt.
fatal: unable to access 'https://github.com/jhipster/generator-jhipster.git/': The requested URL returned error: 403

```

My suggested change in generators/server/templates/src/main/java/package/config/Constants.java.ejs:

<     public static final String LOGIN_REGEX = "^[_.@A-Za-z0-9-]*$";
---
>     public static final String LOGIN_REGEX = "^[_'.@A-Za-z\u00c0-\u017e0-9-]*$";

Sorry, I my first attempt in submitting a fix. =)

And prob. important to mention: The regex is taken from here: http://www.port135.com/2017/01/31/how-to-allow-european-characters-in-text-fields-by-using-regular-expression/

**Comment by pascalgrimaud** [comment]
@co5dt : to contribute to JHipster
- first, fork the project -> https://github.com/jhipster/generator-jhipster/fork
- then clone on your local your fork: https://github.com/co5dt/generator-jhipster
- add remote upstream: `git remote add upstream https://github.com/jhipster/generator-jhipster`
- create a new branch in local, before doing some change
- once it's finished, push to your fork on github
- then, on github, you will be able to open a merge request

**Comment by atomfrede** [comment]
@pascalgrimaud , it's pull request, not merge request (we're not on gitlab :-D) 

But @co5dt follow what @pascalgrimaud wrote and you will be able to contribute. You can also have a look at our contribution guidelines: https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup

**Comment by co5dt** [comment]
Finally found the time to perform my first contrib. Hope everything is in line, more or less. Only problem seems that I have attached the original issue #8004 in the commit message, yet the pull requests # turned out to be #8045. 

However, I have seen that the social login has been removed in 5.x anyway, so I guess this will not be considered anyway. Too bad. Was really proud of my first contrib =)
