### ISSUE TITLE
ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./src

### ISSUE THREAD

**Issue by DjihadBengati** [jhipster/generator-jhipster#8007]
I am using the version 5.1.0 of JHipster and i get this error when I'm launching the 'yarn start' command.

##### **Overview of the issue**

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./src
Module not found: Error: Can't resolve './src' in 'C:\git\myapp'
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src
i ｢wdm｣: Failed to compile.

##### **Reproduce the error**

Just create a new app with the version that I mentioned and run the 'yarn start' command.

##### **JHipster Version(s)**

```
bestcoiner@0.0.0 C:\git\myapp
`-- generator-jhipster@5.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.bestcoiner.app",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "monolith",
    "baseName": "bestcoiner",
    "packageName": "com.bestcoiner.app",
    "packageFolder": "com/bestcoiner/app",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "ar-ly",
      "en"
    ]
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.12.0.windows.1

node: v8.11.3

npm: 5.6.0

yeoman: 1.8.5

yarn: 0.27.5

##### **Browsers and Operating System**

Windows 10 

Please advise ! :'(

**Comment by pascalgrimaud** [comment]
can you try to upgrade Yarn ?
yarn 0.27 is too old

**Comment by DjihadBengati** [comment]
Great thank you ! it works (*_*)
