### ISSUE TITLE
Error: MomentLocalesPlugin: Moment.js doesn't include a locale you specified: ua. Check the plugins `localesToKeep` option

### ISSUE THREAD

**Issue by javadev** [jhipster/generator-jhipster#8012]
##### **Overview of the issue**

I generated jhipster 5.1.0 + react application and can not build it on my pc.

```
\node_modules\webpack-cli\bin\cli.js:244
[ERROR]                                 throw err;
[ERROR]                                 ^
[ERROR]
[ERROR] Error: MomentLocalesPlugin: Moment.js doesnв??t include a locale you specified: ua. Check the pluginв??s `locale
sToKeep` option.
[ERROR] You can see the full list of locales that Moment.js includes in node_modules/moment/locale/
[ERROR]     at normalizeLocalesToKeep (C:\Users\user\Documents\project java\jobsviewer\node_modules\moment-local
es-webpack-plugin\index.js:67:15)
[ERROR]     at checkOptions (C:\Users\user\Documents\project java\jobsviewer\node_modules\moment-locales-webpack
-plugin\index.js:31:25)
[
```

##### **Motivation for or Use Case**

I think it happened because of my locale ua.

##### **Reproduce the error**

Generate jhipster 5.1.0 + react application. Setup locale ua. Try to build war file.

##### **Related issues**

https://github.com/moment/moment/issues/2979

##### **Suggest a Fix**

Add somme dependency to javascript modules.

##### **JHipster Version(s)**

5.1.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitCompany": "",
    "baseName": "jobsviewer",
    "packageName": "io.github.jhipster.application",
    "packageFolder": "io/github/jhipster/application",
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "enableSwaggerCodegen": false,
    "messageBroker": false,
    "buildTool": "maven",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "ru",
    "languages": [
      "ua",
      "ru"
    ],
    "clientFramework": "react",
    "jhiPrefix": "jhi"
  },
  "git-provider": "GitLab",
  "git-company": "javadev",
  "repository-name": "jobsviewer"
}

##### **Browsers and Operating System**

Windows 10 64 bit.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by javadev** [comment]
I solved this issue.

![screenshot_54](https://user-images.githubusercontent.com/348496/43063539-68c41dfe-8e5c-11e8-9fe3-0c7340831f93.png)

**Comment by PierreBesson** [comment]
@javadev Could you submit a PR to fix this, so that other Ukrainian users won't have the bug. Maybe we can patch this method: https://github.com/jhipster/generator-jhipster/blob/d237bd8a56521826482c0c28f3679bfaa4f7b169/generators/generator-base-private.js#L269

Or maybe the *UA* locale should be renamed *UK* ?

**Comment by javadev** [comment]
@PierreBesson I found this bug only for React not for Angular.

**Comment by pascalgrimaud** [comment]
I confirm the issue.

Currently, we don't have the issue with Angular because the dependency `moment-locales-webpack-plugin` is different between Angular and React

For Angular:
- moment-locales-webpack-plugin: 1.0.5

For React:
- moment-locales-webpack-plugin: 1.0.7

Downgrading the `moment-locales-webpack-plugin` dependency in React to use the version `1.0.5`  works.
