### ISSUE TITLE
OAuth and liquibase lead to referentialintegrity exception when upgrade

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#8018]
##### **Overview of the issue**

When running ./mvnw liquibase:diff on an oauth project lead to the generation of a constraint between users and authorities (the user_authorities file).

But, as the users do not exist in the database, this lead to a referentialintegrity exception at startup.

Before PRing, I wanted to know why there is a user.csv file while using oauth: aren't they automatically added while login from the OIDC server, also why do the user_authorities table is prepoulated.
Is there a reason?

##### **Motivation for or Use Case**

Avoiding referentialintegrityviolation

##### **Reproduce the error**

Generate an oidc project (in my case a microservice one), launch it (or run verify), run liquibase:diff -Pdev, then start the project.

##### **Related issues**

don't know if there is any

##### **Suggest a Fix**

remove user_authority.csv file when using oauth, and maybe users.csv.

##### **JHipster Version(s)**

5.0.1 at least

##### **JHipster configuration**
```

├── generator-jhipster@5.0.1 
├─┬ generator-jhipster-elasticsearch-reindexer@1.1.0
│ └── generator-jhipster@4.14.4 
├─┬ generator-jhipster-enterprise-pom@0.0.5
│ └── generator-jhipster@4.14.4 
└─┬ generator-jhipster-spring-cloud-stream@0.0.2
  └── generator-jhipster@4.14.4 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "xxx.marketplace",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.1",
    "baseName": "marketplace",
    "packageName": "xxx.marketplace",
    "packageFolder": "xxx/marketplace",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-elasticsearch-reindexer",
        "version": "1.1.0"
      },
      {
        "name": "generator-jhipster-enterprise-pom",
        "version": "0.0.5"
      },
      {
        "name": "generator-jhipster-spring-cloud-stream",
        "version": "0.0.2"
      }
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}

</pre>
</details>
##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.18.0

node: v8.11.3

npm: 5.6.0

yeoman: 1.8.5

yarn: 1.5.1

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 5a3f1a3

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**
Chrome, but is it important?



- [ ] Checking this box is mandatory (this is just to show you read everything)

<!-- Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate -->

**Comment by mraible** [comment]
The authorities table should be pre-populated because JHipster hard-codes the ROLE_ADMIN and ROLE_USER values in the UI code. If you’re saying the certain usernames to certain roles is also pre-populated, that’s probably not necessary for OAuth.

**Comment by Tcharl** [comment]
@mraible,

Yes, for the authority table it is sure that it should be persisted (for now), but I don't see the point on the actual user.csv nor the user_authorities.csv in the oauth context.
I just wanted to be sure that these rows aren't used anywhere
