### ISSUE TITLE
generator-jhipster have no option to generate angularjs app in framework section even for 4.14.4 version

### ISSUE THREAD

**Issue by yrojha4ever** [jhipster/generator-jhipster#8027]
##### **Overview of the issue**
Recently, generator-jhipster have no option to generate angularjs app in framework section even for 4.14.4 version. Website says AngularJS 1.X support is removed in JHipster 5, but I am using JHipster 4 still not able to generate AngularJS app, it was working before.

##### **Reproduce the error**
![image](https://user-images.githubusercontent.com/4167541/43259279-4cd033d0-90f5-11e8-9a99-ecd09197d008.png)

##### **JHipster Version(s)**
4.14.4

##### **JHipster configuration**
Shown in screenshot.

##### **Browsers and Operating System**
Mac Siera

**Comment by ruddell** [comment]
The OAuth2/OIDC auth type was never implemented for the AngularJS client, so the combination is not possible.
