### ISSUE TITLE
Button size while hovering in React is not consistent

### ISSUE THREAD

**Issue by Falydoor** [jhipster/generator-jhipster#8031]
##### **Overview of the issue**

When hovering a link entity's button (ex: "Create new entity", "View", "Edit", "Delete" and "Back"), the size of the button changes. If the button is not a link (ex: "Save"), the size doesn't change.

The size of the button changes because the text becomes **bold**.

##### **Motivation for or Use Case**

This behavior makes the buttons not consistent and the layout is affected by the size change. This is not happening with the Angular version.

##### **Reproduce the error**

Generate an app and an entity using React. Hover any buttons on the entity's page.

##### **Suggest a Fix**

An easy fix would be to remove the `font-weight` css rule in `app.css.ejs`:
```css
a:hover {
  color: #533f03;
  font-weight: bold; <--
}
```

An other fix would be to change link button to act like a normal button. Code will have to be added to make the button act like a link.

##### **JHipster Version(s)**

5.1.0

##### **JHipster Version(s)**

```
jhipster@0.0.0 /Users/theo/Documents/perso/jhipster-react-button-size
└── generator-jhipster@5.1.0  -> /Users/theo/Documents/perso/generator-jhipster-fork

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Car (car) {
  name String,
  creationDate ZonedDateTime
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.14.3 (Apple Git-98)

node: v8.11.3

npm: 6.1.0

yeoman: 2.0.5

yarn: 1.8.0

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

##### **Browsers and Operating System**

OSX 10.12.6, Chrome, Safari

- [x] Checking this box is mandatory (this is just to show you read everything)

I would be happy to do a PR if you guys agree with this issue (which is more a minor visual one I agree).

**Comment by pascalgrimaud** [comment]
I agree with you.
Angular and React applications should be consistent
