### ISSUE TITLE
Feature: conditional dev webpack builds on maven/gradle run

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#8033]
##### **Overview of the feature request**

This is an idea I got while tinkering with some stuff. Currently, we do a webpack build as soon as app is generated so that when you run `mvnw` or `gradlew` you get a working app. Though this is the way we have been doing it for a while it has some disadvantages
1. If the initial webpack build fails for some reason, you get a blank page when starting the server, and this results in many invalid tickets. In angular 1, we used to have an error page in this case but we dont have it anymore with Angular/React
2. With Yeoman 3 upgrade the process is more async and it splits our final instruction step logs
3. Not very reliable when your workflow involves clean runs

I propose the below alternative

During maven/gradle dev profile builds we can always trigger a webpack dev build conditionally depending on the presence of the `target|build/www` folder(and maybe even the main assets inside it)
This is pretty easy to do in Gradle and I'm sure shouldn't be difficult in maven as well (@jdubois @pascalgrimaud correct me if I'm wrong)

So this way the webpack build will be run when you run `mvnw|gradlew` for the first time and whenever you do a clean run making sure the app doesn't give a blank page

No changes to prod builds as it always runs the webpack build

##### **Motivation for or Use Case**

Better development experience

##### **Related issues or PR**

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
+1 to anything that helps solve the blank page issue.

**Comment by deepu105** [comment]
I can do the gradle part, but would appreciate help with Maven any volunteers @jhipster/developers ?

**Comment by pascalgrimaud** [comment]
I thought about this some months ago, but never had the time to investigate.
So +1

**Comment by atomfrede** [comment]
@deepu105 Great idea, because I had the exact same problem the last couple of days. Created a fresh project, yarn fails, need to do it manually. For first time users not great

**Comment by vishal423** [comment]
do you also plan to install UI dependencies (with --force) during clean install?

**Comment by jdubois** [comment]
With AngularJs 1 we used to have a nice error page that you did @deepu105 - it would be awesome to have something similar

**Comment by pascalgrimaud** [comment]
@deepu105 : what is your exact idea when the `target|build/www` is missing ?
- have a error page like AngularJS
- or trigger the webpack profile: install yarn/npm, launch webpack:dev build

**Comment by deepu105** [comment]
@jdubois @pascalgrimaud I'm not planning to have an error page, instead, I think we should trigger webpack build when the target|build/www doesn't have any assets. This way we ensure that when you run server you always have the frontend files to see the UI. Ofcourse this doesnt replace the need to run `yarn start` for development

Now for yarn/npm I think it shouldn't be forced so that the plugin does install only if the node_modules are not present, so this part will be as it is today.

**Comment by deepu105** [comment]
@pascalgrimaud If we go with the first solution then the actual handling is done on the client side and it means both Gradle and Maven can use it. I like the second one as well. Which do you prefer?

**Comment by pascalgrimaud** [comment]
I prefer the 2nd of course. Both needs to duplicate some code. For now, I don't see other solution. I need to think more, unless the 2nd solution is OK.

**Comment by deepu105** [comment]
For me its ok, can you start a PR with this, i'll add the Gradle part, unless @atomfrede wants to do it

**Comment by pascalgrimaud** [comment]
Ok, let's do it

**Comment by PierreBesson** [comment]
I'm also for the 2nd one, and it means that the webpack profile needs to duplicate the code from the dev profile as if we the activation clause in the webpack  profile is trigered it will completely replace the dev profile. So I suggest we rename webpack to webpack-dev.

**Comment by pascalgrimaud** [comment]
> With Yeoman 3 upgrade the process is more async and it splits our final instruction step logs

@deepu105 : about this, isn't it possible to store all instructions in a variable and display at the end of all process ?

**Comment by deepu105** [comment]
> With Yeoman 3 upgrade the process is more async and it splits our final instruction step logs
> 
> @deepu105 : about this, isn't it possible to store all instructions in a variable and display at the end of all process ?

@pascalgrimaud, unfortunately, the logs are from different sub gens and syncing them with yeoman would be very tricky. Anyway since this is merged its not a problem any more
