### ISSUE TITLE
Compile error in QueryService if inherit filtering entity from @MappedSuperclass. Need to place a lowerbound on `OTHER` type parameter in QueryService

### ISSUE THREAD

**Issue by soberich** [jhipster/generator-jhipster#8040]
##### **Overview of the issue**
Current QueryService implementation does not allow to use field from `@MappedSuperclass`, because the generated Static Metamodel uses inheritence and `QueryService` does not have lower bound for `OTHER` type parameter, thought has it for `ENTITY` type parameter.
##### **Motivation for or Use Case**

```java
@MappedSuperclass
class Base {
    @Id
    @GeneratedValue
    Long id; 
}

@Entity
class Child1 extends Base {
    
    @ManyToOne(optional = false, fetch = LAZY)
    private Child2 child2;
}

@Entity
class Child2 extends Base {
    @OneToMany(mappedBy = "child2", fetch = LAZY)
    private Set<Child1> child1s= new HashSet<>();
}
//#generated QueryService from 
    specification = specification.and(buildReferringEntitySpecification(criteria.getChild2Id(), Child1_.child1s, Child2_.id)); 
//COMPILE ERROR                                                                                                 ^        ^ compile error here, since the generated static metamodel inherited the type of SingularAttribute<Base, Long> and not SingularAttribute<Child2, Long>

@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(Child2_ .class)
public abstract class Child2_ extends Base_ {
	public static volatile SingularAttribute<Child2 , Child1> child2;
        .....
}

```
##### **Suggest a Fix**

replace `<.., OTHER> with <..., ? super OTHER>` 
in
`io.github.jhipster:jhipster-framework`  in `QueryService.java`

##### **JHipster Version(s)**
2.0.14

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by hosseinrasekhi** [comment]
i had a same problem how can i change jhipster-framework?

**Comment by gzsombor** [comment]
I see a pull request: https://github.com/jhipster/jhipster/pull/68 I think, this could fix your issue. Could you test it?

**Comment by soberich** [comment]
@hosseinrasekhi
Aaaa, I 've just embedded the `service` package from `jhipster-framework` artifact
It [the whole artifact] has near 50 classes, so, it is a tiny add. I rewrote parts, some just become look nicer, Like
```java
@Data
@Accessors(chain = true)
@FieldNameConstants(prefix = "")
public class Filter<FIELD_TYPE> implements Serializable {

    private static final long serialVersionUID = 1L;
    protected FIELD_TYPE equals;
    protected Boolean specified;
    protected List<FIELD_TYPE> in;

    @Override
    public String toString() {
        return getFilterName() + " ["
            + (getEquals() != null ? "equals=" + getEquals() + ", " : "")
            + (getIn() != null ? "in=" + getIn() + ", " : "")
            + (getSpecified() != null ? "specified=" + getSpecified() : "")
            + "]";
    }

    protected String getFilterName() {
        return this.getClass().getSimpleName();
    }
}

```
this is suitable since I am not writing a framework which these guys does. So I depend on Lombok.
But either way Spring inself has LOTS of Lombok, even rare stuff like `@UtilityClass`
some other pars I needed to rewrote 90% because I use it on Jax-Rs and will need to move even further to Wildfly later on.

**Comment by hosseinrasekhi** [comment]
@gzsombor i create MyQueryService and i still has error
The method buildReferringEntitySpecification(Filter<X>, SingularAttribute<? super Role,OTHER>, SingularAttribute<? super OTHER,X>) in the type MyQueryService<Role> is not applicable for the arguments (LongFilter, SetAttribute<Role,User>, SingularAttribute<EntityBase,Long>)

**Comment by hosseinrasekhi** [comment]
@soberich
i dont want to do a lot change and changing QueryService not working have u any idea
i want to use entityBase and filter by id
thanks

**Comment by soberich** [comment]
I don't call for "change a lot". I just say feel free to manually remove the reason of compiler error if you experience it. put a lowerbound everywhere you need if it compiler says you so. But from you method signature you are passing wrong arguments.. it is not about lowerbound anyway. Second parameter seems totally different `SingularAttribute<?,?>` is not `SetAttribute<?,?>`  with or without bounds anyway.

**Comment by hosseinrasekhi** [comment]
@soberich @gzsombor
thank you, changing all method signature to SingularAttribute<? super OTHER,X> or SetAttribute<? super OTHER,X> in QueryService fix compile error

**Comment by gzsombor** [comment]
@soberich : could you test the proposed solution, jhipster/jhipster#68? If I understand correctly, this is what you encountered too.

**Comment by deepu105** [comment]
is someone working on this? @gzsombor is this a bug?

**Comment by ruddell** [comment]
I'm closing this based on @gzsombor's [comment](https://github.com/jhipster/jhipster/pull/68#issuecomment-422515144) saying it's fixed.  Please re-open if it's still an issue
