### ISSUE TITLE
Sonar Analyze: 7 new bugs about CSS

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#8044]
Similar to this ticket: https://github.com/jhipster/generator-jhipster/issues/7911

See https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application

Currently, we have new 7 bugs about CSS:
https://sonarcloud.io/project/issues?id=io.github.jhipster.sample%3Ajhipster-sample-application&resolved=false&sinceLeakPeriod=true&types=BUG
- Unexpected unknow pseudo-class / media feature / property

**Comment by joewhite101** [comment]
Most of these (5 out of 7) are just missing the leading dash on the browser specific CSS entries in home.css. Sonar expects those leading dashes or thinks its an invalid tag.

The Unexpected unknown pseudo-class selector just needs to change to: `.point:last-child`

The entry for min-device-pixel-ratio requires a bit more research. That may be a browser specific css entry only in which case adding the prefix for the browsers should cover it.  May also be a sonar bug

I'll work to create a PR with a potential fix later today.  I think I have a local Sonar setup but if you have an easier way to validate let me know.

**Comment by pascalgrimaud** [comment]
I created the ticket to notice the issue. I'm not really a specialist in CSS, so go ahead :)

**Comment by deepu105** [comment]
@joewhite101 if your PR gets merged, dont forget to claim the 100$ bounty
