### ISSUE TITLE
Upgrade Spring-boot to 2.1.x

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#8047]
##### **Overview of the feature request**
With the launch of new spring-boot 2.1.0.M1 I would like that we create a branch to prepare the migration.

See: https://spring.io/blog/2018/07/30/spring-boot-2-1-m1

##### **Motivation for or Use Case**

Stay in line with Spring-boot releases

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
AFAIK, Spring Boot 2.1 won’t be released until Feb 2019, so it might be a bit early.

**Comment by DanielFran** [comment]
@mraible 

From Github milestones I see: https://github.com/spring-projects/spring-boot/milestones
- 2.1.0.M2: Aug 21
- 2.1.0.RC1: Sep 20

I was expecting that we could launch first Beta version based on 2.1.0.RC1 at least?

**Comment by deepu105** [comment]
I don't think we will do betas with RC releases unless there is a killer feature or something in it, so I agree with @mraible that its too soon and we have a lot on our plates already.
WDYT @jdubois

**Comment by deepu105** [comment]
closing this for now, we can start work once we are ready to upgrade

**Comment by DanielFran** [comment]
@jdubois Will you consider to start soon a branch to migration to spring-boot 2.1.x?

**Comment by jdubois** [comment]
Is that such a big change that we need a specific branch? If it's simple, a PR would be enough

**Comment by DanielFran** [comment]
Well, seems no such big impacts: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1.0-M1-Release-Notes

**Comment by DanielFran** [comment]
Considering spring-framework impacts we have: https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x

**Comment by DanielFran** [comment]
After that we could then think in migrating to micrometer...

**Comment by DanielFran** [comment]
@jdubois To proceed with the PR I created my own branch https://github.com/DanielFran/jhipster/tree/spring-boot-2.1.0

Already identified an issue with JCache: see https://github.com/jhipster/generator-jhipster/issues/7783

**Comment by sendilkumarn** [comment]
And we have to test `Cassandra` too

**Comment by DanielFran** [comment]
@sendikurmarn, it is in my todo list as soon as I have jhipster compiling...

**Comment by DanielFran** [comment]
And it is needed also to test couchbase...

**Comment by DanielFran** [comment]
@jdubois I created this PR https://github.com/jhipster/jhipster/pull/88, but we have some impacts in this project.

Can you please help how now I can proceed with those changes for generator without a branch?

Thanks

**Comment by jdubois** [comment]
Here is how I work:

- I do snapshots of jhipster/jhipster locally using `mvn install`
- I reference those snapshots in jhipster/generator-jhipster so my projects use it

And when I need to test "for real" I also deploy those snapshots to https://jhipster.jfrog.io/jhipster (but that's more complex, let's not do this right now). So if you can just test locally -> I'll then merge your PR in jhipster/jhipster and publish a new release on Maven Central, so then you'll be able to use it.

**Comment by tubbynl** [comment]
@DanielFran  migrating towards Micrometer is something that can already be initiated ahead? (using 2.0.x )

**Comment by jdubois** [comment]
@tubbynl no, work on Micrometer hasn't started yet. This would be huge, I don't expect it to be done soon - next time I have trainee, this could be is task for 6 months.

**Comment by tubbynl** [comment]
yes, i can imagine that it also impacts al lot, unfortunately i also don't have that kind of resources available
