### ISSUE TITLE
Documentation on Configuring Graphite Reporting is Outdated

### ISSUE THREAD

**Issue by cub-bsi** [jhipster/generator-jhipster#8052]
##### **Overview of the issue**
I was trying to set up Graphite reporting via the guide available here: https://www.jhipster.tech/monitoring/#metrics-exporters
I spent a while encountering `Reason: The elements [jhipster.metrics.graphite.enabled] were left unbound` errors until I realized that Graphite support has for now been removed as of #7100 and https://github.com/jhipster/jhipster/commit/0fec4209cc0cd831f2ca6443d0d12abaa8bd7d90

##### **Motivation for or Use Case**
I realize you might reintroduce Graphite integration in the future (which would be very nice), but for now the doc stands plain wrong.
What’s more, if you search the web for `jhipster metrics graphite`, there is no indication whatsoever that support has been removed; not even a mention any release notes of yours I think, at least I do not find anything if I search for `jhipster release notes graphite`.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I assign this ticket to you, @PierreBesson, as you're our expert on this part

**Comment by PierreBesson** [comment]
What ! I was not aware that we had removed support for graphite but after a quick look it seems that it is indeed the case (which is weird as we still include the graphite maven dependency). It seems this was done when trying to migrate to micrometer and then rolling back.
