### ISSUE TITLE
Update spring-boot to 2.0.4 and spring-cloud to Finchley.SR1

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#8067]
##### **Overview of the feature request**

Update current version of spring-boot and spring-cloud to lastest versions available

##### **Motivation for or Use Case**

see:
https://spring.io/blog/2018/07/30/spring-boot-2-0-4-available-now
https://spring.io/blog/2018/08/01/spring-cloud-finchley-sr1-is-available

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
@DanielFran , are you also considering migration of 4.14.x branch to spring boot 1.5.15?

**Comment by DanielFran** [comment]
Already done

**Comment by DanielFran** [comment]
See #8053

**Comment by vishal423** [comment]
@DanielFran , thanks
