### ISSUE TITLE
User entity should use a surrogate key rather than user name

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#807]
The current implementation of the User entity uses the user name as ID, this makes difficult to implement the "change my user name" feature and probably also the issue #750.

Using a surrogate key or generated ID would make it easier, although it would impact the audits.

It would also make easier adapting the authentication to use only email address, I wrote instructions on how to do it and did not implement the "change my email" feature for this reason.

**Comment by Rigobert** [comment]
Hi!
With the sub-generator (jhipster 2.3.x), when we create a relation between the user entity and another one, we still get the following error in the browser console:
Error: [$injector:unpr] Unknown provider: UserProvider <- User <- FooController
http://errors.angularjs.org/1.3.11/$injector/unpr?p0=UserProvider%20%3C-%20User%20%3C-%20FooController

**Comment by gmarziou** [comment]
I got this once too and I worked around it by inverting the ownership of the relation in the Foo entity rather than in User. I did not dig too much into this but I guess that User is a special entity as it is used for authentication.

**Comment by Rigobert** [comment]
gmarziou > Can I have more explanation ? Cause I put in the Foo entity (with the entity generator) the following code: 
```
   @ManyToOne
    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
```
But I received the same error :-(

**Comment by gmarziou** [comment]
So i probably got a different issue.
Your error seems to indicate that the FooController cannot get a User service to be injected to access the UserResource.
It's true that's there's no such service, no user.service.js file, so maybe you could try to add one.
Anyway, you should probably open a new issue rather than using this one which is closed and not related.

**Comment by gmarziou** [comment]
You're lucky, @jdubois committed [a fix](https://github.com/jhipster/generator-jhipster/commit/65d233549b5a3e855f61b2ece3aa4d5432f6dfca), you just have to wait for next release.

**Comment by jdubois** [comment]
yes, but I've commited this fix because I saw your issue, not because you are lucky :-)

**Comment by gmarziou** [comment]
:)
the new findAllForCurrentUser() is really a great feature for quite a common use case.
I'm wondering whether there should be a special case for ROLE_ADMIN when using entities CRUD views?

**Comment by jdubois** [comment]
That's what I started to do, but then it start to be specific to what you want to do.... Some people want to restrict stuff, other don't want, it all depends on the business case. So we can just propose some useful methods, like the findAllForCurrentUser but nothing more

**Comment by gmarziou** [comment]
Is it going to work also for OneToOne relations?
