### ISSUE TITLE
Configuration missing working with blueprint

### ISSUE THREAD

**Issue by hberndt** [jhipster/generator-jhipster#8070]
##### **Overview of the issue**

While developing on jhipster-kotlin generator I run into an error starting entity generator.
Error: ERROR! The entity cannot be generated as the application does not have a database configured!

The generator .yo-rc.json consists of two opjects, generator-jhipster-kotlin and generator-jhipster. Some configuration settings can only be found in the generator-jhipster-kotlin object.

If a copy the members for the database configurtion to the generator-jhipster object, I can start the entity generator.

This is the same with the package. It will not be used generating the classes.

##### **Motivation for or Use Case**

Developing the entity generator for jhipster-kotlin.

##### **Reproduce the error**

Starting an entity generator within a blueprint.
Entity generator constructor
```
module.exports = class extends EntityGenerator {
    constructor(args, opts) {
        super(args, Object.assign({ fromBlueprint: true }, opts)); // fromBlueprint variable is important

        const jhContext = this.jhipsterContext = this.options.jhipsterContext;

        if (!jhContext) {
            this.error(`This is a JHipster blueprint and should be used only like ${chalk.yellow('jhipster --blueprint generator-jhipster-sample-blueprint')}`);
        }

        this.configOptions = jhContext.configOptions || {};
        // This sets up options for this sub generator and is being reused from JHipster
        jhContext.setupEntityOptions(this, jhContext, this);
    }

```
##### **Suggest a Fix**

It may be an error on saving configuration options.

##### **JHipster Version(s)**
5.1.0

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
kotlintest@0.0.0 /Users/hberndt/Projects/kotlintest
└── generator-jhipster@5.1.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster-kotlin": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "microservice",
    "baseName": "kotlintest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true
  },
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "microservice",
    "baseName": "kotlintest",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "clientPackageManager": "yarn",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "blueprint": "generator-jhipster-kotlin",
    "skipClient": true,
    "skipUserManagement": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Person (person) {
  name String,
  givenname String
}
service Person with serviceClass
microservice Person with kotlintest

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.17.0

node: v10.6.0

npm: 5.6.0

yeoman: 2.0.3

yarn: 1.6.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 5a3f1a3

Congratulations, JHipster execution is complete!##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
this is already handled and works fine when I tested with the entity blueprint generated by the jhipster-blueprint generator. I need more details. Can you generate a new sample blueprint using [jhipster-blueprint generator](https://github.com/jhipster/generator-jhipster-blueprint) and reproduce the error?

**Comment by sendilkumarn** [comment]
Check out the comment here. `https://github.com/jhipster/jhipster-kotlin/pull/37#pullrequestreview-143421230` 

Currently the context object don't know whatever present inside the `generator-jhipster-<blueprint_name>`

**Comment by deepu105** [comment]
@sendilkumarn I already made sure to read config from blueprint as well see here https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L2525

and the same method is used to load the context https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L137

can you debug and see whats going on?

**Comment by jdubois** [comment]
As this has been labelled "waiting for information" for 12 days, I'm closing this, let's not keep incomplete bug reports for too long, they clutter the bug tracker.
