### ISSUE TITLE
Add ability to easily configure password policy for apps using JWT or Session

### ISSUE THREAD

**Issue by RothAndrew** [jhipster/generator-jhipster#8078]
##### **Overview of the feature request**

Currently there is no way to enforce a particular password policy. All the app does is check that the length of the password is allowed.

##### **Motivation for or Use Case**

Ability to easily enforce / change a password policy will be very beneficial for increasing security of a JHipster app, without forcing the developer to use a more complicated solution like OAuth.

##### **Related issues or PR**

I have searched and have not found anything relevant in this repo or StackOverflow.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
This will change from use case to usecase and we cant cover everything. Its quite easy ti customize your self

**Comment by RothAndrew** [comment]
1. Add a bean that checks app configuration for the existence of a password policy. I'm thinking `jhipster.security.password.policy`. The value is a regex that passwords much match to be valid.
1. If it can't find one, it does not enforce one.
1. Since it is practically impossible to translate a regex into meaningful instructions, just have the frontend say "The password you entered does not meet the required complexity requirements."

Result: It is trivial to enforce a password policy, and if the user does nothing, the functionality of the app stays exactly the same.

**Comment by RothAndrew** [comment]
I don't agree that it is easy to customize yourself. Not only do you have to make changes to the backend, you have to change your frontend in 3 places:

1. The registration page (In Angular: RegisterComponent)
1. The Change Password page (In Angular: PasswordComponent)
1. The Password Reset Finish page (In Angular: PasswordResetFinishComponent)

**Comment by PierreBesson** [comment]
I'm also not so keen to make the code more complex but I agree that adding a password policy should be easy to do.

Well, what could be done is isolate the password validation logic in a method which returns a boolean. Currently it would only contains the length check but it could be easily extended this way.

**Comment by RothAndrew** [comment]
Can we reopen this if we are in agreement on what can be done?

**Comment by jdubois** [comment]
I also thought @RothAndrew you wanted something much more complex than just a Regexp. It's trivial to do this currently, as you just add the Regexp to the code: for me this would add complexity to our current setup (as there would be a specific configuration key, etc), when it's just one line of code to change today, so for me this doesn't follow our [Policy 2](https://www.jhipster.tech/policies/).

Indeed, you are correct in saying it is a bit more complex as you need to change the front-end (and this also needs to be done for React, btw). But here the solution doesn't add much value, as we still can't tell people what the rules are. As you say, you can't translate a regexp into a meaningful text.
