### ISSUE TITLE
Add Fontawasome free regular icons 

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#8079]
##### **Overview of the feature request**

With the new fontawasome i do not have access to the free regular icons

##### **Motivation for or Use Case**

Sometime they are nicer 

It is easy to add by providing in the package.json:

    "@fortawesome/free-regular-svg-icons": "^5.1.0-8",

next to:

    "@fortawesome/free-solid-svg-icons": "^5.1.0-8",

and than they can be used like this in vendor.ts:

    import { faFilePowerpoint} from '@fortawesome/free-regular-svg-icons';
    library.add( faFilePowerpoint );

and like this in html:

    <fa-icon [icon]="['far', 'file-powerpoint']" [fixedWidth]="true"></fa-icon>

**Comment by deepu105** [comment]
We cant ship everything, if you need a specific icon you would have to add it. We will only include by default what we use in the generated app
