### ISSUE TITLE
Removal of isAuthenticated() method of AccountResource class

### ISSUE THREAD

**Issue by mhavrlent** [jhipster/generator-jhipster#8084]
##### **Overview of the issue**

JHipster generator is generating AccountResource class with the isAuthenticated() method that is not being used anywhere. There are only two tests in the AccountResourceIntTest class that are using this method. 
Following methods should be removed:
* isAuthenticated() method of AccountResource class
* testNonAuthenticatedUser() method of AccountResourceIntTest class
* testAuthenticatedUser() method of AccountResourceIntTest class

##### **Motivation for or Use Case**

I was looking at the usage of this method because our static source code analyzer reported the isAuthenticated() method is vulnerable to the XSS attack.

##### **Reproduce the error**

mkdir myapplication
cd myapplication
jhipster

##### **Related issues**

No similar issue found.

##### **Suggest a Fix**

I will provide a feature branch with the fix.

##### **JHipster Version(s)**

4.13.3

##### **JHipster Version(s)**

```
myapplication@0.0.0 /home/toor/git/myapplication
├── UNMET PEER DEPENDENCY @angular/common@6.0.0
├── UNMET PEER DEPENDENCY @angular/compiler@6.0.0
├── UNMET PEER DEPENDENCY @angular/core@6.0.0
├── UNMET PEER DEPENDENCY @angular/platform-browser@6.0.0
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@6.0.0
├── generator-jhipster@5.1.0 
├── UNMET PEER DEPENDENCY popper.js@^1.12.9
└── UNMET PEER DEPENDENCY rxjs@6.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "myapplication"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "monolith",
    "baseName": "myapplication",
    "packageName": "myapplication",
    "packageFolder": "myapplication",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v6.11.1

npm: 3.10.10

yarn: 1.9.2

Docker version 1.13.1, build bdb8293-unsupported

##### **Browsers and Operating System**

Fedora release 28 (Twenty Eight)

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mhavrlent** [comment]
Pull request: https://github.com/jhipster/generator-jhipster/pull/8085

**Comment by PierreBesson** [comment]
I just checked and the isAuthenticated method is used by UaaConfiguration : https://github.com/jhipster/generator-jhipster/blob/2c496ce113a068fd74c6fc385a46a7d603057fa9/generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs#L211

So it should be not be removed for `applicationType === 'uaa'`. Can you add an if condition in the template rather than removing the code entirely.

**Comment by PierreBesson** [comment]
[EDIT] Don't take this message into account. I was wrong, it seems you can safely remove the code.
> I just checked and the isAuthenticated method is used by UaaConfiguration : https://github.com/jhipster/generator-jhipster/blob/2c496ce113a068fd74c6fc385a46a7d603057fa9/generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs#L211
> 
> So it should be not be removed for `applicationType === 'uaa'`. Can you add an if condition in the template rather than removing the code entirely.

**Comment by jdubois** [comment]
We don't use it but expect that people will need it when coding their business logic.

**Comment by mhavrlent** [comment]
There is already a SecurityUtils.isAuthenticated() method which can be used for business logic, but this one has no api resource.

If we plan to keep the AccountResource.isAuthenticated() method, then we need some security expert to tell us if it's really vulnerable to XSS attack or not. This method was marked as Critical issue in the report of the Fortify Source Code Analyzer tool.

Here's the summary of that report:

#### Summary
The method isAuthenticated() in AccountResource.java sends unvalidated data to a web browser on line 99, which can result in the browser executing malicious code.Sending unvalidated data to a web browser can result in the browser executing malicious code.

#### Explanation
Cross-site scripting (XSS) vulnerabilities occur when:
1. Data enters a web application through an untrusted source. In the case of Reflected XSS, the untrusted source is typically a web request, while in the case of Persisted (also known as Stored) XSS it is typically a database or other back-end data store.

In this case the data enters at getRemoteUser() in AccountResource.java at line 99.

**Comment by jdubois** [comment]
That method is here to check if the user is authenticated or not, as the name suggests. I don't believe it can do any XSS attack. 
Fortify looks like a lot of marketing bullshit to me, if your company has money to spend, sponsoring the project would be a better use of it.

**Comment by jdubois** [comment]
Just had a look at the code, there is no way you can do an XSS attack here, so I'm closing this.

**Comment by cbornet** [comment]
I don't know Fortify but I guess that's a false positive because it doesn't see that `HttpServletRequest` is not the request body that should be validated but an object provided by the Spring framework.
