### ISSUE TITLE
Support for CockroachDB

### ISSUE THREAD

**Issue by Sebastiandg7** [jhipster/generator-jhipster#8088]
##### **Overview of the feature request**

Add support for CockroachDB

##### **Motivation for or Use Case**

CockroachDB is a NewSQL distributed cloud-based database which has very impressive core features (you can take a look here https://www.cockroachlabs.com). According to its documentation, although CockroachDB supports PostgreSQL syntax and drivers, it does not offer exact compatibility.

There are some SQL constraints that are not followed by the current jhipster SQL model generation. The idea is to add support for this great db (something similar to MariaDB. But instead of MySQL, PostgreSQL) so users can choose it at application generation and other sub-generators change its SQL/entity generation behaviour to be fully complaint with Cockroach constraints.

Apart from the above, the idea is to change the default database configuration to match the CockroachDB defaults, which will not be that much as it uses the same driver and dialect as PostgreSQL.

##### **Related issues or PR**

None.

- [x] Checking this box is mandatory (this is just to show you read everything)

I have started the development on this at https://github.com/Sebastiandg7/generator-jhipster/tree/cockroachdb-support

**Comment by jdubois** [comment]
Thanks @Sebastiandg7 - this has already been asked a couple of times, and I don't believe we should have this in the main generator.
We already added Couchbase support last year: it is a far more popular solution, and still we have close to 0 users. Same thing for Cassandra. Those are really niche markets compared to mainstream databases.

Adding a new database adds a huge maintenance burden to the team, and usually we need at least 1,000 users to get one contributor - so typically we would need to have several thousands of CockroachDB users to be able to maintain it correctly. I don't believe such a community can exist, so in the end this is going to be really bad for all other users, as this will make the whole generator more complex, and our releases more difficult.

Now there are 2 options for you: blueprints and modules. I think a blueprint who be better for CockroachDB - I haven't tested and I might be wrong, but have a look at https://github.com/jhipster/jhipster-kotlin which is our Kotlin port, I guess you could do the same thing to support CockroachDB.
