### ISSUE TITLE
Use @Qualifier by default on repositories

### ISSUE THREAD

**Issue by mathieu-chauvet** [jhipster/generator-jhipster#8090]
##### **Overview of the feature request**

Hi JHipster users and devs, 

I'm using jhipster 5.1.0

I'm following the side by side pattern introduced by @agoncal at the JHipster Conf last June.

Here is the slide I'm refering to : https://www.slideshare.net/agoncal/custom-and-generated-code-side-by-side-with-jhipster

Slide 17. 

I'm facing a problem when I extend a repository class. 

This class is injected via a constructor in a resource class and I get an error when I start the application : 

    Parameter 0 of constructor in com.home.books.web.rest.SNEntryResource required a single bean, but 2 were found:
    	- SNEntryRepositoryExtended: defined in null
    	- SNEntryRepository: defined in null

    Action:
    
    Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

    
I have solved the problem by using the @Qualifier annotation on the extended repository and changed the code in the generated resource class but it's not really "side by side compliant" as I'll have to do it every time I update the entity or jhipster.  

##### **Motivation for or Use Case**

This side by side pattern is really efficient and I guess it will be (or is already) used by a lot of jhipster users. It would be great to be able to use it out of the box.

##### **Related issues or PR**

None that I've found. 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This should work if you put `@Primary` on your own `SNEntryRepositoryExtended` bean, could you test this?

**Comment by jdubois** [comment]
I'm closing this as I'm pretty sure my comment is OK - @mathieu-chauvet don't hesitate to add more info, I'll re-open if needed
