### ISSUE TITLE
Unify angular and react state management

### ISSUE THREAD

**Issue by jbadeau** [jhipster/generator-jhipster#8091]
Redux is a framework agnostic state management library.

This request is to unify the angular and react state management code:

- reduce load on jhipster maintainers by removing the need to maintain multiple business logic code branches
- allow jhipster users to maintain business logic in one place but swap out different rendering technology
- could possibly simplify SPA build and test code
- with decorators, it might even be possible to unify component input and output
- testing which is a significant part of development might be unified as well. For example. Setting the app or component into a predefined state.

**Comment by jdubois** [comment]
This would be a huge refactoring, and we just don't have the necessary people to do this. Of course we also need to discuss if that's useful, but unless someone is a volunteer to lead that effort, let's close this as this just won't be done.
