### ISSUE TITLE
Heroku sub-generator doesn't allow you to deploy an app twice

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#8093]
##### **Overview of the issue**

When running `jhipster heroku` on a project, it deploys just fine. When you try to run it a second time, it fails and says the project already exists.

```
Creating Heroku application and setting up node environment
✖ { Error: Command failed: heroku create okta-gateway
Creating okta-gateway... !
 ▸    Name okta-gateway is already taken

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:538:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'heroku create okta-gateway' }
```

##### **Motivation for or Use Case**

It used to work in JHipster 4.x.

##### **Reproduce the error**

Create an app, deploy it to Heroku with `jhipster heroku`. Then change some things and try it again. I used [this tutorial](https://developer.okta.com/blog/2018/03/01/develop-microservices-jhipster-oauth), which leverages microservices. I'm not sure if it's specific to microservices.

##### **Suggest a Fix**

Detect if the app already exists. If it does, ask the user if they own it. If they say yes, try to deploy to that name.

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/mraible/dev/okta/okta-jhipster-microservices-oauth-example/gateway
└── generator-jhipster@5.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.okta.developer.gateway",
    "packageFolder": "com/okta/developer/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "herokuDeployType": "git"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.1

node: v9.8.0

npm: 6.3.0

yeoman: 2.0.5

yarn: 1.9.2

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 5a3f1a3

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I thought you were suppose to use the update commands second time

**Comment by jkutner** [comment]
I think this was caused by a change in error message when `heroku create` fails
