### ISSUE TITLE
Reserved keyword issue when generating frontend application

### ISSUE THREAD

**Issue by btrajkovski** [jhipster/generator-jhipster#8102]
##### **Overview of the issue**

I am running into following error when generating the frontend application. 
`Error: The name 'Profile' is a reserved keyword and can not be used as an entity table name.`This is very strange to me considering the fact that frontend only code does not generate database entities and should not check for reserved database keywords. 

This is the .jh file that I've used: https://pastebin.com/zDhLbSYx
Also I was able to generate the backend only code using the exactly same .jh file, only last line was changed to `skipClient *`

##### **Motivation for or Use Case**

Unable to generate frontend-only from .jh file

##### **Reproduce the error**

`jhipster import-jdl a.jh --skipServer` with this .jh file https://pastebin.com/zDhLbSYx
`jhipster import-jdl b.jh --skipClient` with this .jh file https://pastebin.com/HCgV9Wtv

##### **Suggest a Fix**

I would suggest to disable check for keywords when generating frontend only code 

##### **JHipster Version(s)**

5.1.0

##### **JHipster configuration**

sing JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
mrt@0.0.0 /Users/btrajkovski/development/projects/intertec/mr_t_frontend
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "monolith",
    "baseName": "mrt",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "databaseType": "sql",
    "devDatabaseType": "sql",
    "prodDatabaseType": "sql",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ],
    "skipServer": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity UProfile {
  isNewTenant Boolean,
  creditRating Integer
}
entity URole {
  name String
}
entity Property {
  size Integer,
  isRentable Boolean,
  rentableFrom Instant,
  latitude String,
  longitude String,
  orientation String,
  address String,
  city String,
  title String,
  rooms Integer
}
entity Amenity {
  name String
}
entity UFile {
  name String,
  path String
}
entity Message {
  content String,
  datetime Instant,
  isRead Boolean
}
entity Appointment {
  datetime Instant,
  status AppointmentStatus
}
entity Notification {
  content String,
  datetime Instant,
  isSeen Boolean
}
entity RequestToRent {
  status RentStatus
}
entity Shortlist {
  note String
}
entity Upload {
  datetime Instant
}
entity ProfilePropertyRole
entity MessageProfileAppointment

enum AppointmentStatus {
  APPROVED,
  REJECTED,
  IN_PROGRESS
}

enum RentStatus {
  DRAFT,
  APPROVED,
  PENDING,
  REJECTED
}

relationship OneToOne {
  UProfile{user} to User,
  UProfile{avatar} to UFile
}
relationship OneToMany {
  Appointment{property} to Property{appointment},
  UProfile{requestToRent} to RequestToRent{profile},
  Property{requestToRent} to RequestToRent{property},
  UProfile{shortlist} to Shortlist{profile},
  Property{shortlist} to Shortlist{property},
  UFile{upload} to Upload{file},
  Property{upload} to Upload{property},
  UProfile{profilePropertyRole} to ProfilePropertyRole{profile},
  Property{profilePropertyRole} to ProfilePropertyRole{property},
  URole{profilePropertyRole} to ProfilePropertyRole{role},
  UProfile{messageProfileAppointment} to MessageProfileAppointment{profile},
  Message{messageProfileAppointment} to MessageProfileAppointment{message},
  Appointment{messageProfileAppointment} to MessageProfileAppointment{appointment}
}
relationship ManyToOne {
  Property{owner} to UProfile,
  Property{tenant} to UProfile
}
relationship ManyToMany {
  Property{amenity} to Amenity{property},
  Appointment{profile} to UProfile{appointment},
  Notification{profile} to UProfile{notification}
}

paginate Property with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.13.1

node: v8.11.3

npm: 5.6.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 5a3f1a3

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Chrome v68, Mac OS X 10.13.5

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@btrajkovski there are reserved keywords for the front end as well, but yes table related checks can be skipped but then you won't be able to generate client and server code separately and expect them to work together without heavy changes

**Comment by btrajkovski** [comment]
@deepu105 I agree, but the thing is that backend generate went fine without problems. And also as far as I am aware jhipster uses `jhi_` prefix for that exact reason so that we can avoid reserved keywords in table names. All the endpoints and classes are generated correctly ex. `/role`, `/profile/` etc. And only frontend generate failed.
@gmarziou If `Profile` is reserved in Angular do you think it would be nice to have a separate list of reserved Angular/frontend keywords that will kick in when generating frontend code? Because right now I cannot have angular entities with these names `Roles`, `Profile`, `File` etc. which IMHO is pretty restrictive.

**Comment by jdubois** [comment]
@btrajkovski you totally understand the issue: we reserve those keywords, because we know we'll need those for the front-end.
It's clearly not a perfect solution: we didn't use the `jhi_` prefix because some people argued at that time that this would "tie" them to JHipster. So we only do this on the backend, "hidden" things, so that the end-used does not notice it. I'm not sure it's the best solution, but it's a compromise.
At the moment, I think the best solution would be to use that prefix everywhere - the code would be more coherent, and that would totally remove that kind of issue. Of course, a few Angular routes wouldn't look "perfect", but I'm not sure a lot of end-users notice that. And you can still easily refactor them if you want.

**Comment by jdubois** [comment]
No comment in the last 11 days: I'm not sure everybody agree on using our own "jhi-" prefix everywhere.

I also realize this could be a security risk: then it would be clear to everyone that the application is a JHipster application, which would help potential attackers. There are of course other ways to find that it's a JHipster application, but let's not help attackers too much.

Anyway, this would be a big refactoring that breaks a lot of applications, so unless there are a lot of people who are motivated, let's keep it that way. So you can't use "Profile", but there are plenty of other possibilities, like "MyProfile", so this isn't blocking. If you really want "Profile", you could also delete the current "Profile" module, and refactor a "MyProfile" module in it.

I think we should work again on our strategy here, when we plan JHipster 6. There should be a better way to work around "reserved keywords" than prefixing everything, as it's kind of ugly in the end.
