### ISSUE TITLE
Sorting icon is not updated

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#8105]
After a generation with Angular, in Administration > User Management, sorting on columns doesn't change the icon. It stays on:
![image](https://user-images.githubusercontent.com/766263/44231834-aaaaea80-a19f-11e8-9162-facf2092ae22.png), no matter the sorting direction.

An attempt of fix is here (but it is not sufficient, maybe a good start?): https://github.com/jhipster/ng-jhipster/pull/73

The bug appeared after the use of `angular-fontawesome` and/or `fontawesome-svg-core`.
It seems that the underlying svg is not "re-rendered" to display the correct icon.

**Comment by fresnault** [comment]
What is the current status of this issue ? 

@ctamisier Do you have work in progress ? On your side, you just have a problem of rerendered ?

For my part, I just pulled version 5.2.1 and even fa-icon classes are KO.

Step | classes
------------ | -------------
Initialization | ng-fa-icon
1st click on sort | ng-fa-icon fa-sort-up
2nd click on sort | ng-fa-icon fa-sort-up fa-sort-down
... | ng-fa-icon fa-sort-up fa-sort-down

I can look more closely at the problem if nobody has looked at it.

**Comment by jdubois** [comment]
I tried to do it a few days ago and miserably failed :-(
That's why I put the bounty on it!

**Comment by fresnault** [comment]
I didn't find a good solution to fix the rendering problem.

Angular-fontawesome renders icon when the change comes from angular binding value, not from classes.

I think there is a interesting response (and example) in this post  : 
https://github.com/FortAwesome/angular-fontawesome/issues/72#issuecomment-408473472
Maybe we can play with the ComponentFactoryResolver (but we need an extra dependency on @fortawesome lib).

Otherwise it is always possible to create a new component like this and show/hide fa-icon according to JhiSort value, but it's really worse than before
```
@Component({
    selector: 'jhi-sort-icon',
    template: `
        <fa-icon [icon]="'sort'"></fa-icon>
        <fa-icon [icon]="'sort-up'"></fa-icon>
        <fa-icon [icon]="'sort-down'"></fa-icon>
    `
})
```

**Comment by ctamisier** [comment]
That's good that we can have a solution..
But thinking about this issue more globally, it means that having an already rendered 'fa-icon' we are not able to "change it" dynamically by applying different CSS classes. The solution seems that we need to have a component and then re-render it through the Angular way to have this working.
Isn't it too restrictive ?
(Shouldn't we just remove the js+svg approach (fontawesome-svg-core) ?)

I'm just thinking about people that are already playing with CSS (and not having a dedicated component) to change these kind of icons and it might no longer work for them ?

**Comment by fresnault** [comment]
I totally agree with you. It was easier by only changing the class css.

I propose a solution that seems to work for sorting the pagination. For the rest, as you say, it's possible to change the icon directly with the angular [icon] directive.

So, it's like you want. There was probably a good reason to have migrated to fortawesome + svg...

**Comment by gvandooren** [comment]
Hi everybody,
To fix this issue, override the jhiSortBy directive and the jhiSortDirective.
I try many different fixes but only one is ok. The FaIconComponent implements OnChanges but the changes are never detected.

The fix consists to replace the svg path used to render the icon.

in the sort directive
`private resetClasses() {
        const allThIcons = this.element.querySelectorAll('fa-icon');
        // Use normal loop instead of forEach because IE does not support forEach on NodeList.
        for (let i = 0; i < allThIcons.length; i++) {

            const faIconElement = allThIcons[i];

            this.renderer.setElementAttribute(faIconElement.children[0], 'data-icon', 'sort');
            this.renderer.setElementAttribute(faIconElement.children[0], 'class', 'svg-inline--fa fa-w-10 fa-sort');
            this.renderer.setElementAttribute(faIconElement.children[0].children[0], 'd', this.sortIcon.icon[4]);
        }
    }`

in the sortby directive : 

`    private applyClass() {
        let iconName = 'sort';
        let icon = this.sortIcon;
        if (this.jhiSort.predicate === this.jhiAmadeusSortBy) {
            if (this.jhiSort.ascending) {
                icon = this.sortAscIcon;
                iconName = 'sort-up';
            } else {
                icon = this.sortDescIcon;
                iconName = 'sort-down';
            }
        }

        const childIcon = this.el.nativeElement.children[1];
        this.renderer.setElementAttribute(childIcon.children[0], 'data-icon', iconName);
        this.renderer.setElementAttribute(childIcon.children[0], 'class', 'svg-inline--fa fa-w-10 fa-' + iconName);
        this.renderer.setElementAttribute(childIcon.children[0].children[0], 'd', icon.icon[4]);
    }
`

**Comment by deepu105** [comment]
@gvandooren could you plz do a PR?

**Comment by deepu105** [comment]
so that you get the $100 bounty

**Comment by gvandooren** [comment]
@deepu105 i do that today :)

**Comment by lllllpylllll** [comment]
I had build ng-jhipster with the code changes from the pull.

It seems that the sorting icon does not response when i tested on Internet Explorer, however Chrome is working fine.

The Internet Explorer - Console is showing the below error
ERROR TypeError: Unable to get property '0' of undefined or null reference

**Comment by deepu105** [comment]
Which version of IE, we actually only support evergreen browsers

**Comment by lllllpylllll** [comment]
IE 11 (Internet Explorer 11)

**Comment by lllllpylllll** [comment]
Hi deepu105,

i regenerate and reinstall the ng-jhipster that was build locally and it is working fine now.

Thanks

**Comment by gvandooren** [comment]
@lllllpylllll Thanks for your return  :)

**Comment by scpoole709** [comment]
The <i> class has been replaced with an SVGElement which has a className as read-only. To change the appearance you need to change the attribute 'class'. I found that the class names that worked were svg-inline--fa-sort, svg-inline-fa-sort-up and svg-inline--fa-sort-down. Who writes code like this???
