### ISSUE TITLE
Users who did not get receive activation email can not log in

### ISSUE THREAD

**Issue by richard-fairthorne** [jhipster/generator-jhipster#8106]
##### **Overview of the issue**

When a user signs up, they are sent an activation email. If they do not receive it (for example if the mail server is down or it was filtered as spam), there is no way for that user to activate.

##### **Motivation for or Use Case**

When users sign up, they want to be able to login. If the activation email doesn't go through, there is no feature to resend it, and they cannot ever login.

When they try to log in they get the message: Failed to sign in! Please check your credentials and try again.

When they use "forgot my password" they get the message: Email address isn't registered! Please check and try again

When they try to re-register, they get the message: Login name already registered! Please choose another one.

When they choose a different username, they get the message: Email is already in use! Please choose another one.

##### **Reproduce the error**

1. Create a new jhipster project with no mail server setup.
2. Sign up.
3. Pretend you can't see the logs where the activation link is listed.
4. Try (to no avail) to log in, get another activation email, delete your account to re-sign up, or get access to the website my any means.

##### **Related issues**

I was not able to find a report of this issue.

##### **Suggest a Fix**

When a not activated user tries to sign in, provide a link to re-send the activation email.

##### **JHipster Version(s)**

v5.2.1

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
omnipresnet@0.0.0 /Users/admin/src/omnipresnet.com
└── generator-jhipster@5.2.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.omnipresnet",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "omnipresnet",
    "packageName": "com.omnipresnet",
    "packageFolder": "com/omnipresnet",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.17.0

node: v8.11.3

npm: 6.1.0

yeoman: 2.0.5

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880f

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Nothing generated but the defaults.

##### **Browsers and Operating System**

OSX - any browser -- I chose Angular when generating the projet.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
At the moment they need to way 2 or 3 days (I'm not sure) before being able to activate their account again, as their account will get purged. The other solution is to ask their administrator, who can activate the account manually.

We should just allow people to register again, if their email address hasn't been activated yet.
