### ISSUE TITLE
UAA- Access Control: allowing access for /auth/api/account, as no access control policy has been set up for service: auth

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#8107]
##### **Overview of the issue**

Unable to Login to the UAA from gateway

##### **Motivation for or Use Case**

Create UAA with one microservice and one gateway to test

##### **Reproduce the error**

```bash
mkdir auth

mkdir school-gate

cd auth/
```
use this `.yo-rc.json`

```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.school.auth"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "uaa",
    "baseName": "auth",
    "packageName": "com.school.auth",
    "packageFolder": "com/school/auth",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "8cce8f6d6d2fd6635ea43659525cada6362a09cb",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true
  }
}
```

```bash
cd school-gate/
```
use this `.yo-rc.json`

```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.school.gate"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "gateway",
    "baseName": "schoolGate",
    "packageName": "com.school.gate",
    "packageFolder": "com/school/gate",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "auth",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
Both applicatiions runs well, But login doesn't work and says as below screen shot

![image](https://user-images.githubusercontent.com/11784253/44294219-80495200-a2b1-11e8-901a-12c5ef57bdfb.png)

##### **JHipster Version(s)**
 jhipsterVersion:  "5.2.1"

##### 1. Auth

```
auth@0.0.0 /home/balu/balu/projects/jhipster/microservice-architecture/auth
`-- generator-jhipster@5.2.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.school.auth"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "uaa",
    "baseName": "auth",
    "packageName": "com.school.auth",
    "packageFolder": "com/school/auth",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.17.1

node: v8.11.3

npm: 6.3.0

yarn: 1.9.4

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880fe

##### 2. SchoolGate
```
school-gate@0.0.0 /home/balu/balu/projects/jhipster/microservice-architecture/school-gate
`-- generator-jhipster@5.2.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.school.gate"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "gateway",
    "baseName": "schoolGate",
    "packageName": "com.school.gate",
    "packageFolder": "com/school/gate",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "auth",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.17.1

node: v8.11.3

npm: 6.3.0

yarn: 1.9.4

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880fe

##### **Browsers and Operating System**
browser: Chrome,
OS: Linux 

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
The issue here is that your UAA is named `auth`, and the gateway routes for logging in start with `auth` as well.  Based on the logs, the request is being routed to the UAA instead of the gateway.  It would work if your UAA is not named `auth`, I guess we should prevent this from happening
