### ISSUE TITLE
Sonar can't find TESTS-results-sonar.xml

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#8111]
##### **Overview of the issue**
Following the [Code Quality docs](https://www.jhipster.tech/code-quality/), Sonar integration is failing:
`
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.1.1168:sonar (default-cli) on project sonartest: Error during parsing of generic test execution report '/private/tmp/jh/sonartest/target/test-results/jest/TESTS-results-sonar.xml'. Look at the SonarQube documentation to know the expected XML format.: /private/tmp/jh/sonartest/target/test-results/jest/TESTS-results-sonar.xml (No such file or directory) -> [Help 1]
`

##### **Reproduce the error**

```
# Generate a default project
jhipster

# Launch Sonar
docker-compose -f src/main/docker/sonar.yml up -d

# Run Sonar build command (from docs)
./mvnw clean test sonar:sonar
```
Error is displayed.

##### **Related issues**
https://github.com/jhipster/generator-jhipster/issues/7978 (looks like the same issue, but this affects monoliths)
https://github.com/jhipster/generator-jhipster/issues/7928

##### **Suggest a Fix**
Not sure

##### **JHipster Version(s)**
Master
v5.2.1
v5.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "sonartest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

<details>
<summary>Environment and Tools</summary>

<pre>

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.18.0

node: v8.11.4

npm: 5.6.0

yarn: 1.9.4

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880f
</pre>
</details>

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
The command from the docs (`./mvnw clean test sonar:sonar`) deletes the `target` folder beforehand.  Even without the `clean`, the only item in `target/test-results/` is `coverage` for Java files.

It looks like the frontend tests aren't running.  If I run `yarn run test` first, then run `./mvn test sonar:sonar` the file `TESTS-results-sonar.xml` is present and Sonar succeeds.

**Comment by geyuqiu** [comment]
may want to remove "clean" from doc / readmes?
