### ISSUE TITLE
jhipster upgrade deletes all ignored files

### ISSUE THREAD

**Issue by henri-tremblay** [jhipster/generator-jhipster#8117]
##### **Overview of the issue**

So I was migrating from a version to another. And my `.gitignore` is ignoring files like `/application.properties` which are not ignored by default by jhipster.

After migration, all these files were deleted.

##### **Motivation for or Use Case**

The ignore files should not be touched.

##### **JHipster Version(s)**

Was going from 4.14.4 to 4.14.5

##### **JHipster configuration**

It probably doesn't matter

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Doesn't matter

##### **Browsers and Operating System**

macOS 10.13.6

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Files that are cleaned up are configured [here](https://github.com/jhipster/generator-jhipster/blob/v5.2.1/generators/upgrade/index.js#L87).

Unfortunately this is just a list of files, and I'm not sure we have the tooling to read a `.gitignore` file and use it correctly to ignore those files....

Maybe the best solution would be to add in the documentation that this must be done on a separate project, that was freshly cloned for this purpose? And not use an existing project which has ignored files. WDYT, would that be good enough for you @henri-tremblay ?

**Comment by henri-tremblay** [comment]
I think we should keep `application.properties` as well. It is used to locally overload some Spring configuration.

From there, documenting about the deletion seems a good idea.

**Comment by gmarziou** [comment]
Could you explain why you use `application.properties`?
What does it bring that you cannot achieve with `src/*/resources` ?

**Comment by henri-tremblay** [comment]
Because it contains passwords and keys that I need to connect to third-parties when playing on local. However, I obviously don't want them to be checked-in.

**Comment by gmarziou** [comment]
I usually do this using env vars or through command line options which feel safer to me and come earlier in the [Spring Boot property source order.](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config).

I was unable to make it work with a gateway so I suspect it does not work with Spring Cloud Config Server.

Also your PR should probably include also `application.yml`

**Comment by jdubois** [comment]
@henri-tremblay I'm doing the same thing as you, but with a `.yml` file in same directory as my executable WAR file. That way I'm sure it's never mixed with the rest of the application, it's not even in the project!

**Comment by henri-tremblay** [comment]
But you never launch your application from your IDE? In dev? I even have integration tests using these. By default, I am faking the third-party server. But when needed, I really connect to it.

It could be an `application.yml` but the Spring Boot documentation wasn't mentioning that `application.yml` would work. But I must confess I never tried. We should ignore both if it does.

**Comment by jdubois** [comment]
@henri-tremblay in my IDE this is configured with the IntelliJ "run" screen. It even has auto-completion of those properties, so it's much easier than a file.

**Comment by henri-tremblay** [comment]
Interesting. Good to know. But then, if you want to reuse the same properties in Maven? (which I do when running integration tests)

**Comment by gmarziou** [comment]
Env variables work with maven too.

**Comment by henri-tremblay** [comment]
How do you pass them? But it seems redundant to have them twice (Maven and IDE).

I will propose an alternative: Can we imagine a section in .yo-rc.json to add some more ignored files? Something to add afterwards, not in the wizard questions

**Comment by vishal423** [comment]
Another solution would be to externalize such list to a file say '.jhipsterignore' and by default should be populated with current set from `_cleanUp` and generator should respect this. 
`const filesToKeep = ['.yo-rc.json', '.jhipster', 'node_modules', '.git', '.idea', '.mvn'] . `

This should allow end users to add more files, directories to list that they have added on top of project generated via Jhipster.

**Comment by jdubois** [comment]
@vishal423 it would be a bit like the `.gitignore`... So let's try to have just one file if possible.

I just found https://www.npmjs.com/package/parse-gitignore and this seems to do the job -> would everybody be fine (especially @henri-tremblay ) to use this to ignore files? I think that's a good solution

**Comment by vishal423** [comment]
@jdubois, yes, it should be like `.gitignore`, however, both are not same. You may require version control of few files like `.yo-rc.json`, `.jhipster` and not for few like `node_modules` `.mvn`. 

Since, cleanup is specific to Jhipster and not tied to source control, IMO, we should separate it.

**Comment by jdubois** [comment]
OK then, but this all sounds very complex.
If we now need to work with both .gitignore (as the upgrade process uses Git) and a new .jhipsterignore file, I'm afraid this is just too much work. Nobody works on the upgrade part, mainly because it's already too complex.

So I'd like to stick to the original idea: let's just document that you need to clone your project in a fresh directory. So there won't be any ignored files at all, and we only work with files stored in Git, which will of course work.

**Comment by henri-tremblay** [comment]
Document it is ok I guess but not pretty. I don't want it to become overly complicated for nothing either. Parsing the `.gitignore` seems a good idea if it's easy to do. Right now it feels that you just need to keep '.yo-rc.json', '.jhipster', '.mvn'` on top of the `.gitignore`. No?

**Comment by gmarziou** [comment]
There are several node modules for parsing .gitignore files, this could help.

**Comment by jdubois** [comment]
I'm doing the code with `.gitignore`. It's quite simple and will solve the issue of @henri-tremblay 

My only trouble is that this code is very hard to test, as it uses the release numbers - as long as there is no release, I can only simulate it working.... As it's pretty simple, I think it's good to go, so I'll commit my code directly, and this will need to be tested as soon as we do the next release. In case of trouble, I'll rollback and do a patch release.
