### ISSUE TITLE
string.match is not function

### ISSUE THREAD

**Issue by lzwill** [jhipster/generator-jhipster#8118]
##### **Overview of the issue**

I've used generator-jhipster to generate a front-end app with `--skip-server --auth=jwt --db=mssql` option and chose **React** as js framework, and **enable internationalization support**. Also I have another back-end service application(using `--skip-client` option) running there. 
I logged in, and when i try to modify the data(such as inactive an user or change email of user), it gives me an error **string.match is not a function**.
<img width="1422" alt="2018-08-20 2 25 37" src="https://user-images.githubusercontent.com/22948246/44324018-c0adf900-a486-11e8-99d4-b45a26426022.png">

##### **JHipster Version(s)**
v5.2.1

##### **JHipster Version(s)**

```
spm@0.0.0 /Users/lingzhiwei1/Documents/projects/spm/sps-web
└── generator-jhipster@5.2.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "spm",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "databaseType": "true",
    "devDatabaseType": "true",
    "prodDatabaseType": "true",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ],
    "skipServer": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.15.2 (Apple Git-101.1)

node: v8.11.1

npm: 6.1.0

yarn: 1.6.0

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880f

##### **Browsers and Operating System**
Mac OS 10.13.6, Chrome 68

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by lzwill** [comment]
If I don't **enable internationalization support**, this error won't appear, and all functions work correctly.

**Comment by postace** [comment]
This problem still exists in version 5.8.2

After one night investigation, I found that the problem comes from the server side.
That is, the server must send the corrected alert header for the client to displaying the toast.

Before ()
`.headers(HeaderUtil.createAlert( "A user is created with identifier " + newUser.getLogin(), newUser.getLogin()))`

After (fixed)
`.headers(HeaderUtil.createAlert( "userManagement.created", newUser.getLogin()))`
