### ISSUE TITLE
Update protractor to 5.4.0 to resolve 2 vulnerabilities

### ISSUE THREAD

**Issue by Fydon** [jhipster/generator-jhipster#8128]
##### **Overview of the issue**

NPM reports multiple vulnerabilities, where updating protractor to 5.4.0 will resolve 2 high vulnerabilities:

High            Denial of Service
Package         https-proxy-agent
Dependency of   protractor [dev]
Path            protractor > saucelabs > https-proxy-agent
More info       https://nodesecurity.io/advisories/593

High            Arbitrary File Write via Archive Extraction
Package         adm-zip
Dependency of   protractor [dev]
Path            protractor > webdriver-js-extender > selenium-webdriver > adm-zip
More info       https://nodesecurity.io/advisories/681

##### **Motivation for or Use Case**

Eliminate vulnerabilities

##### **Reproduce the error**

Create a new react or angular project and select Protractor.

##### **Related issues**

Didn't find one after searching

##### **Suggest a Fix**

Update [line 103 of Angular's package.json.ejs][1] and [line 129 of React's package.json.ejs][2].

##### **JHipster Version(s)**

```
XXX@0.0.0 XXX
`-- generator-jhipster@5.2.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "XXX",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "XXX",
    "packageName": "XXX",
    "packageFolder": "XXX",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1.windows.2

node: v8.11.4

npm: 6.4.0

yeoman: 2.0.5

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880fe

- [X] Checking this box is mandatory (this is just to show you read everything)

[1]: https://github.com/jhipster/generator-jhipster/blob/1a037d2735b2dcdd6c7bff2b7510fa4257e0451a/generators/client/templates/angular/package.json.ejs#L103
[2]: https://github.com/jhipster/generator-jhipster/blob/395f7ffcad1081c4f6faa2f9cf28affadb25700f/generators/client/templates/react/package.json.ejs#L129

**Comment by jdubois** [comment]
Could you do a PR for this?
