### ISSUE TITLE
Update browser-sync to 2.24.6 to resolve 5 vulnerabilities

### ISSUE THREAD

**Issue by Fydon** [jhipster/generator-jhipster#8129]
##### **Overview of the issue**

NPM reports multiple vulnerability, where updating browser-sync to 2.24.6 will resolve 5 low vulnerabilities:

Low             Regular Expression Denial of Service
Package         debug
Dependency of   browser-sync [dev]
Path            browser-sync > connect > debug
More info       https://nodesecurity.io/advisories/534

Low             Regular Expression Denial of Service
Package         debug
Dependency of   browser-sync [dev]
Path            browser-sync > connect > finalhandler > debug
More info       https://nodesecurity.io/advisories/534

Low             Regular Expression Denial of Service
Package         debug
Dependency of   browser-sync [dev]
Path            browser-sync > serve-index > debug
More info       https://nodesecurity.io/advisories/534

Low             Regular Expression Denial of Service
Package         debug
Dependency of   browser-sync [dev]
Path            browser-sync > localtunnel > debug
More info       https://nodesecurity.io/advisories/534

Low             Prototype Pollution
Package         lodash
Dependency of   browser-sync [dev]
Path            browser-sync > easy-extender > lodash
More info       https://nodesecurity.io/advisories/577

##### **Motivation for or Use Case**

Eliminate vulnerabilities

##### **Reproduce the error**

Create a new react or angular project

##### **Related issues**

Didn't find one after searching

##### **Suggest a Fix**

Update [line 70 of Angular's package.json.ejs][1] and [line 85 of React's package.json.ejs][2].

##### **JHipster Version(s)**

```
XXX@0.0.0 XXX
`-- generator-jhipster@5.2.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "XXX",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "XXX",
    "packageName": "XXX",
    "packageFolder": "XXX",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1.windows.2

node: v8.11.4

npm: 6.4.0

yeoman: 2.0.5

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880fe

- [X] Checking this box is mandatory (this is just to show you read everything)

[1]: https://github.com/jhipster/generator-jhipster/blob/1a037d2735b2dcdd6c7bff2b7510fa4257e0451a/generators/client/templates/angular/package.json.ejs#L70
[2]: https://github.com/jhipster/generator-jhipster/blob/395f7ffcad1081c4f6faa2f9cf28affadb25700f/generators/client/templates/react/package.json.ejs#L85

**Comment by jdubois** [comment]
Could you do a PR for this?

**Comment by Fydon** [comment]
@jdubois I plan to, but saw the commit message requirements listed an issue that it resolves, so am creating the issues first and then will create the pull requests to resolve.
