### ISSUE TITLE
Migrate from (Spring MVC REST + Tomcat/Jetty) to (Jersey + Undertow) ?

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#814]
Our current REST endpoints are coded with Spring MVC REST, and our default Web server is Tomcat (but we already use Undertow in the "fast" profile as it starts up 0.5 seconds faster).

Our tests show that the (Jersey + Undertow) combinaison is much, much faster:

| Title | SPRING MVC - Jetty | SPRING MVC - Undertow | JERSEY  - Jetty | JERSEY  - Undertow |
| --- | --- | --- | --- | --- |
| version | Jetty(9.2.4.v20141103) | n/a | Jetty(9.2.4.v20141103) | n/a |
| Document Length | 2124 bytes | 2124  bytes | 2114 bytes | 2114 bytes |
| Concurrency Level | 50 | 50 | 50 | 50 |
| Time taken for tests | 5.456 seconds | 5.768 seconds | 0.967 seconds | 0.581 seconds |
| Complete requests | 10000 | 10000 | 10000 | 10000 |
| Total transferred | 22972950 | 22894397 | 23333310 | 23019066 |
| HTML transferred | 21261240 | 21318588 | 21161140 | 21175938 |
| Requests per second | 1833.00 (mean) | 1733.84 (mean) | 10345.67 (mean) | 17198.80 (mean) |
| Time per request (mean) | 27.278 ms | 28.838 ms | 4.833 ms | 2.907 ms |
| Time per request (mean, across all concurrent requests) | 0.546 ms | 0.577 ms | 0.097 ms | 0.058 ms |
| Transfer rate | 4112.25 Kbytes/sec | 3876.49 Kbytes/sec | 23574.09 Kbytes/sec | 38662.13 Kbytes/sec |
| Connection Times (ms) | min  mean[+/-sd] median   max | min  mean[+/-sd] median   max | min  mean[+/-sd] median   max | min  mean[+/-sd] median   max |
| Connect | 0   11  29.7      9     531 | 0   11   7.8     10     557 | 0    0   0.1      0       2 | 0    0   0.1      0       2 |
| Processing | 1   15  22.4     13     531 | 2   17  38.2     14     567 | 1    5   2.7      4      39 | 0    3   1.1      3       9 |
| Waiting | 1   11  22.4      9     530 | 1   12  31.8     10     563 | 0    5   2.7      4      39 | 0    3   1.1      3       9 |
| Total | 3   27  37.6     24     549 | 8   28  39.8     25     590 | 1    5   2.7      4      39 | 0    3   1.1      3       9 |
| Percentage of the requests served within a certain time (ms) |  |  |  |  |
| 50% | 24 | 25 | 4 | 3 |
| 66% | 28 | 29 | 5 | 3 |
| 75% | 30 | 31 | 5 | 3 |
| 80% | 32 | 32 | 6 | 3 |
| 90% | 37 | 37 | 7 | 4 |
| 95% | 40 | 41 | 8 | 5 |
| 98% | 44 | 46 | 11 | 6 |
| 99% | 49 | 49 | 17 | 8 |
| 100% | 549 | 590 | 39 | 9 |

Migrating to Jersey/Undertow has the following consequences:
- We would migrate from the Spring MVC REST API to the JAX RS API. They are very similar, so this migration should be easy
- Dependency Injection would still work, using the Spring DI integration in Jersey
- We need to check if Spring AOP (like security and monitoring) will still be able to work: this looks possible but we need to validate this

**Comment by mpages** [comment]
i've put jersey as REST provider instead of Spring MVC Rest which is not compliant with JAX-RS spec
it need some tuning to provide the same feature thant Spring MVC Rest in JHipster (jackson mapper, jodatime, gzip) ....

i've done some jmeter test using from 1 to 200 thread on a service which have constant response time (no database access)
the diff between spring mvc and jersey is very light (mvc : 26782 req/s, jersey : 27854 req/s), the average time is 2ms diff over 400 000calls

but switching to jersey and JaxRS will provide easier switch to spring data rest or any fmk JaxRS + Hateoas

**Comment by schrepfler** [comment]
I thought Spring Data Rest is NOT JAX-RS? They do have Declarative Hyperlinking though even if it's not the same. I'm all for supporting Jersey as well.

**Comment by jdubois** [comment]
Yes, but we will stick with Spring MVC REST, as we are based on the Spring stack.

**Comment by mpages** [comment]
my bad .. @schrepfler spring data rest .. is not JAX-RS . only provide hyperlink info over repo :(

spring mvc rest is a very poor impl for rest service .. futhermore you have dev many things that is provide out of the box on rest impl : async service, gzip ...

**Comment by mpages** [comment]
spring boot 1.2.0 provide jersey profile

**Comment by nogece** [comment]
I did a similar test. undertow = 1.5*tomcat sounds realistic. undertow = 10*tomcat is nonsense.

**Comment by rchukka** [comment]
@jdubois Can you please share the test code that you used for initial tests? (jersey with undertow and jetty)

**Comment by jdubois** [comment]
@rchukka the original tests where done by @jmirc
