### ISSUE TITLE
jhipster kubernetes doesn't generate keycloak yaml

### ISSUE THREAD

**Issue by dkirrane** [jhipster/generator-jhipster#8143]
##### **Overview of the issue**

I generated an app with keycloak for oidc and postgres for db.
I then used the kubernetes subgenerator. It generates the yaml for the app & postgres but not keycloak

##### **Motivation for or Use Case**

Kubernetes integration

##### **Reproduce the error**

Run 
```
jhipster (selecting keycloak option)
jhipster kubernetes
# Result: no K8s yaml generated for keycloak
```

##### **JHipster Version(s)**

JHipster Docker Image tag: v5.2.1

##### **JHipster configuration**

jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
app@0.0.0 /home/jhipster/app
`-- generator-jhipster@5.2.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "app",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "appsFolders": [
      "app"
    ],
    "directoryPath": "../",
    "jwtSecretKey": "replaced-by-jhipster-info",
    "dockerRepositoryName": "mydocker.registry.mycompnay.com",
    "dockerPushCommand": "docker push",
    "kubernetesNamespace": "default",
    "kubernetesServiceType": "Ingress",
    "ingressDomain": "mycompnay.com",
    "monitoring": "no",
    "istio": "no",
    "istioRoute": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.17.1

node: v8.11.4

npm: 6.4.0

yeoman: 2.0.5

yarn: 1.9.4

##### **Browsers and Operating System**

Latest Chrome & Docker for Windows

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Could you follow the guidelines and post your config, so I can try to reproduce?

**Comment by dkirrane** [comment]
jhipster info updated

**Comment by st4rtx** [comment]
any body now fix this error or not?

**Comment by atomfrede** [comment]
I have a working example, but without using a helm chart, thats why I closed the PR as we wanted to go with a helm directly I think.

**Comment by st4rtx** [comment]
i want use jhipster and keycloac on kubernetes but generator dont use keycloac and app have error

**Comment by atomfrede** [comment]
@jhipster/developers As we have not yet made any progress using helm charts I could reactive my PR. If I remember correctly everything worked fine for monolith already.

**Comment by st4rtx** [comment]
in microservice  dont worked and jhipster kubernetes generator dont make keycloak.yml and ignore it !

**Comment by st4rtx** [comment]
any body now other Technic ?

**Comment by jdubois** [comment]
@st4rtx please don't spam everybody if you don't participate in solving the issue, this pollutes the thread and annoys the 780 people who are watching the repo

**Comment by st4rtx** [comment]
@dkirrane  ok i delete it but say me how can i find the solution ?

**Comment by atomfrede** [comment]
@st4rtx If you need specific help you can use stackoverflow or at least tell what your concrete problem is. My old PR contains everything to deploy a single keycloak instance in kubernetes and connects a jhipster application to it.

**Comment by st4rtx** [comment]
@atomfrede  i search at your PR but i dont find any things about keycloak ok kube

**Comment by pascalgrimaud** [comment]
@st4rtx : the PR is here https://github.com/jhipster/generator-jhipster/issues/8464

**Comment by saturnism** [comment]
ran into this issue w/ @mraible yesterday 😄

**Comment by mraible** [comment]
@saturnism Do you really care? If so, where's the PR?! 😉
