### ISSUE TITLE
[Protractor] Test that the entity can be displayed after creation

### ISSUE THREAD

**Issue by hdurix** [jhipster/generator-jhipster#8147]
##### **Overview of the feature request**

As explained in #8146, [no assert](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs#L143) is done for checking that the entity can be displayed after being created.

##### **Motivation for or Use Case**

This is important as we don't detect that an entity can not be displayed in client, an error could be at any of these parts:
- retrieve in the database
- JSON serialization
- Angular/React deserialization
- Angular/React display
- ...

An easy implementation is to check that the number of entities is incremented by 1 after creation (I proposed to do the same for delete: we check the entity list is decremented by 1 after delete).

Although checking the number of line could be not enough, because apparently, we don't switch to the next page after creating the 21st element in a page of 20 elements: a proper way could be to parse the pagination footer and assert that it has be incremented: (`Showing 1 - 20 of 20 items.` ==> `Showing 1 - 20 of 21 items.`)?

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm adding a $100 bounty on this.

**Comment by pascalgrimaud** [comment]
@hdurix : another solution would be to check the `alert` message, and we could try to close it. It will speed up a lot our protractor tests. Could it be possible ?

**Comment by hdurix** [comment]
Small update on the subject:
- Implementation has been done in https://github.com/jhipster/generator-jhipster/pull/8277 with checking that the entity list contains one more entity after creation
- We could not find a way to check the alert message: when the temporary alert is displayed, all the protractor test is freezing until the alert is closed (because it's waiting for Angular)
- Checking the list's length is enough as if the entity is displayed, it has been created
- For speeding up the tests in Travis, I created this PR https://github.com/jhipster/generator-jhipster/pull/8285
- For speeding up the tests outside of Travis, I have no idea expect ugly ones
