### ISSUE TITLE
Cache statistics are not sent by back-end in metrics (always none)

### ISSUE THREAD

**Issue by Blackdread** [jhipster/generator-jhipster#8148]
##### **Overview of the issue**

Since 5.0.0 of jhipster, cache statistics are not sent by back-end in metrics (always none).
For an application, we did upgrade from 4.14.1 to 5.0.1 (then later 5.2.1) and saw that cache statistics are always empty (see screenshot). 

Before upgrade, it was working without problem.

![no-cache-statistics-jhipster](https://user-images.githubusercontent.com/3595693/44502819-e1b05d00-a6c5-11e8-849f-31467065cb37.png)

I have created a fresh new app with some entities, it fails as well to send cache statistics.

##### **Motivation for or Use Case**

Get back statistics :)

##### **Reproduce the error**

Create a new app, import jdl with few entities, go to metrics page, cache  statistics will be empty

##### **Related issues**

none

##### **Suggest a Fix**

No idea

##### **JHipster Version(s)**

Since 5.0.0

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "c9a1a14c5fa7714b36354ef7c28a61128eb00f5f",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn",
      "fr"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Few entities with some basic relations

##### **Browsers and Operating System**

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Sorry, I knew about this and forgot to create the ticket -> thanks a lot @Blackdread !!
I have no idea what is causing that, maybe @henri-tremblay has an idea. I will investigate further when I have time.

**Comment by PierreBesson** [comment]
I remember @henri-tremblay contributed a jcache metrics registry first in JHipster then upstream to dropwizard metrics. We should just look at the metrics doc to see how to reactivate them.

**Comment by jdubois** [comment]
Indeed @PierreBesson I can confirm this is because the `JCacheGaugeSet` that was contributed by @henri-tremblay is not working anymore.
Its `getCacheBeans` cannot find any cached beans anymore, but I can see them using the JConsole, which is really strange. Maybe a classloader issue? As we got one recently in that part of the code.

**Comment by henri-tremblay** [comment]
Interesting (and annoying). I'll have a look.

**Comment by henri-tremblay** [comment]
The answer is: It's because of `@AutoConfigureAfter(value = MetricsConfiguration.class)` that was removed from `CacheConfiguration`. So now the gauge is registered before the caches are created. So no monitoring. It was removed by `https://github.com/jhipster/generator-jhipster/commit/843a671cf2e9febb20c1749fab7c2d522062ee1e`. Do you know why @jdubois ?

**Comment by jdubois** [comment]
I probably did this by mistake, not understanding why this was useful... However I already tried this without success, are you sure it works?
Be careful if you test on master, the build is currently broken.

**Comment by jdubois** [comment]
OK I will need to test again tomorrow! Thanks a lot

**Comment by Blackdread** [comment]
Strange I tried the annotation as well before posting this issue, did not work, will test again later.

**Comment by henri-tremblay** [comment]
Just debug and make sure CacheConfiguration is created before MetricsConfiguration.

**Comment by henri-tremblay** [comment]
Hum... You are right. I just got lucky. I'm currently passing a `CacheManager` to `MetricsConfiguration` constructor. I don't know if there's a better way.

**Comment by jdubois** [comment]
Oh thanks @henri-tremblay - the CacheManager trick is ugly but works very well, I'm doing that. Not the first time I do this kind of hack!

**Comment by henri-tremblay** [comment]
Note that you don't even need to assign it to a class attribute. Just to pass it to the constructor. And l would add a comment to prevent it to be removed by mistake later.

**Comment by jdubois** [comment]
Thanks @henri-tremblay ! Done in https://github.com/jhipster/generator-jhipster/commit/03a3dc0e657eaedf8adbb873fe5130909f85c910
