### ISSUE TITLE
Upgrade to Typescript 3 everywhere

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#8149]
##### **Overview of the feature request**

Upgrade to Typescript 3 in Angular(May have to wait until Angular updates to TS3) and React
Upgrade TS compilers, TSlint and related webpack plugins

- [ ] Angular
- [x] React

**Comment by wmarques** [comment]
@deepu105 I can start the work on this, I'll do a PR asap :) I have a free-day at ippon on the 31 so I'll finish this during no later than this day

**Comment by deepu105** [comment]
Done
