### ISSUE TITLE
Remove the SASS question and remove CSS option

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#8150]
Remove CSS option and provide SASS with CSS support as the default. 
This should be fine for new applications
For upgrading apps, generate SCSS and warn the user to choose between existing CSS or new SCSS files based on their preference

**Comment by wmarques** [comment]
@deepu105 When you say "upgrading apps" you mean the upgrade sub-gen ?

**Comment by deepu105** [comment]
@wmarques yes

**Comment by wmarques** [comment]
@deepu105 I don't understand the "generate SCSS and warn the user to choose", if SCSS is the default then we have to generate SCSS when we upgrade no ?
Or you meant ask the user to choose for each file?

**Comment by deepu105** [comment]
If Sass is used in the app then we just regenerate it normally no issues here.
If we remove CSS option completely, that means we cant generate that for apps that upgrade, in that case we will generate SCSS and warn user that there is no CSS generated and user can choose to keep the SCSS or keep old CSS files

**Comment by wmarques** [comment]
Ok ! Thanks for clarification :) I'm starting to work on this.
I never worked on the upgrade sub-gen so I might take some time...

**Comment by deepu105** [comment]
But lets not do this now, its a breaking change hence should be done for v6 thats why I added that label

**Comment by jdubois** [comment]
We really need to have this soon for JHipster 6, @wmarques do you have time to work on this, or do you need help?

**Comment by wmarques** [comment]
@jdubois I think this will be mostly cleaning so I should be fine, I just totally forgot about that.
I will provide a PR tomorrow
