### ISSUE TITLE
QueryService not working for ManyToMany relationships

### ISSUE THREAD

**Issue by stefantwog** [jhipster/generator-jhipster#8152]
##### **Overview of the issue**

So i created ManyToMany relationship between 2 entities and when i try to filter one entity by id of other entity in that ManyToMany relation  it returns me the whole list without filtration.

##### **JHipster Version(s)**

> {
>   "generator-jhipster": {
>     "promptValues": {
>       "packageName": "com.test"
>     },
>     "jhipsterVersion": "4.14.5",
>     "baseName": "test",
>     "packageName": "com.test",
>     "packageFolder": "com/test",
>     "serverPort": "8080",
>     "authenticationType": "jwt",
>     "cacheProvider": "ehcache",
>     "enableHibernateCache": true,
>     "websocket": false,
>     "databaseType": "sql",
>     "devDatabaseType": "h2Disk",
>     "prodDatabaseType": "mysql",
>     "searchEngine": false,
>     "messageBroker": false,
>     "serviceDiscoveryType": false,
>     "buildTool": "maven",
>     "enableSocialSignIn": false,
>     "enableSwaggerCodegen": false,
>     "jwtSecretKey": "af6a4740a877e210db7b0ebe238e23524d4edfdc",
>     "clientFramework": "angularX",
>     "useSass": true,
>     "clientPackageManager": "yarn",
>     "applicationType": "monolith",
>     "testFrameworks": [],
>     "jhiPrefix": "jhi",
>     "enableTranslation": false
>   }
> }

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

jdl studio file : 
```
entity Platform {
	name String
}


entity Tournament {
	name String,
   
}

relationship ManyToMany {
    Tournament{platforms(name)} to Platform{tournaments}
}


paginate Game with infinite-scroll
paginate * with pagination except Game


// Set service options to all except few
service all with serviceImpl

filter *
```

**Comment by jdubois** [comment]
Could you give an example of a query your created, so we can test?

**Comment by Blackdread** [comment]
could be related to #7195, depends on his query. Only the id has not yet been fixed in that issue

**Comment by deepu105** [comment]
no response for 23 days. @stefantwogI'm closing this. If you have more info for us to reproduce please update and ask to reopen. Also please follow our issue template properly please
