### ISSUE TITLE
Not possible to update JHipster to latest JHipster release 5.2.1

### ISSUE THREAD

**Issue by Tonterias** [jhipster/generator-jhipster#8154]
##### **Overview of the issue**

When using the command yarn global upgrade generator-jhipster it is not possible to upgrade the generator. After using it, if I use the command jhipster --version and I see always the old version 5.0.1

You closed this one: https://github.com/jhipster/generator-jhipster/issues/7232 which is almost the same, but with no solution. What can I do? Thanks

##### **Reproduce the error**

Trying to run command yarn global upgrade generator-jhipster

D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\upgrade>yarn global upgrade generator-jhipster
yarn global v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 243 new dependencies.
info Direct dependencies
└─ generator-jhipster@5.0.1
info All dependencies
├─ @mrmlnc/readdir-enhanced@2.2.1
├─ @nodelib/fs.stat@1.1.1
├─ ajv@5.5.2
├─ ansi-cyan@0.1.1
├─ ansi-red@0.1.1
├─ ansi@0.3.1
├─ are-we-there-yet@1.1.5
├─ argparse@1.0.10
├─ arr-flatten@1.1.0
├─ array-differ@1.0.0
├─ array-find-index@1.0.2
├─ array-slice@0.2.3
├─ asn1@0.2.4
├─ assign-symbols@1.0.0
├─ async@2.6.1
├─ asynckit@0.4.0
├─ atob@2.1.2
├─ aws-sign2@0.7.0
├─ aws4@1.8.0
├─ balanced-match@1.0.0
├─ base@0.11.2
├─ bcrypt-pbkdf@1.0.2
├─ binaryextensions@2.1.1
├─ brace-expansion@1.1.11
├─ braces@2.3.2
├─ buffer-alloc-unsafe@1.1.0
├─ buffer-alloc@1.2.0
├─ buffer-fill@1.0.0
├─ buffer-from@1.1.1
├─ builtin-modules@1.1.1
├─ cache-base@1.0.1
├─ call-me-maybe@1.0.1
├─ caseless@0.12.0
├─ chardet@0.4.2
├─ class-utils@0.3.6
├─ cli-table@0.3.1
├─ clone-buffer@1.0.0
├─ clone-stats@0.0.1
├─ clone@1.0.4
├─ cloneable-readable@1.1.2
├─ co@4.6.0
├─ collection-visit@1.0.0
├─ color-convert@1.9.2
├─ color-name@1.1.1
├─ colors@1.0.3
├─ combined-stream@1.0.6
├─ commander@2.15.1
├─ commondir@1.0.1
├─ concat-map@0.0.1
├─ concat-stream@1.6.2
├─ conf@1.4.0
├─ copy-descriptor@0.1.1
├─ core-util-is@1.0.2
├─ currently-unhandled@0.4.1
├─ cycle@1.0.3
├─ dargs@5.1.0
├─ dashdash@1.14.1
├─ dateformat@3.0.3
├─ debug@2.6.9
├─ decamelize-keys@1.1.0
├─ deep-extend@0.6.0
├─ delayed-stream@1.0.0
├─ delegates@1.0.0
├─ detect-conflict@1.0.1
├─ didyoumean@1.2.1
├─ diff@3.5.0
├─ drange@1.0.2
├─ ecc-jsbn@0.1.2
├─ editions@1.3.4
├─ ejs@2.6.1
├─ env-paths@1.0.0
├─ error@7.0.2
├─ esprima@4.0.1
├─ exit-hook@1.1.1
├─ expand-brackets@2.1.4
├─ extend@3.0.2
├─ extglob@2.0.4
├─ extsprintf@1.3.0
├─ eyes@0.1.8
├─ fast-deep-equal@1.1.0
├─ fast-glob@2.2.2
├─ fast-json-stable-stringify@2.0.0
├─ fill-range@4.0.0
├─ first-chunk-stream@2.0.0
├─ for-in@1.0.2
├─ forever-agent@0.6.1
├─ form-data@2.3.2
├─ fs.realpath@1.0.0
├─ gauge@1.2.7
├─ generator-jhipster@5.0.1
├─ get-value@2.0.6
├─ getpass@0.1.7
├─ gh-got@6.0.0
├─ github-username@4.1.0
├─ glob-parent@3.1.0
├─ glob-to-regexp@0.3.0
├─ glob@7.1.2
├─ gulp-filter@5.1.0
├─ har-schema@2.0.0
├─ har-validator@5.1.0
├─ has-ansi@2.0.0
├─ has-flag@3.0.0
├─ has-symbol-support-x@1.4.2
├─ has-to-string-tag-x@1.4.1
├─ has-unicode@2.0.1
├─ has-value@1.0.0
├─ has-values@1.0.0
├─ hosted-git-info@2.7.1
├─ http-signature@1.2.0
├─ iconv-lite@0.4.24
├─ inflight@1.0.6
├─ insight@0.10.1
├─ interpret@1.1.0
├─ is-accessor-descriptor@1.0.0
├─ is-arrayish@0.2.1
├─ is-builtin-module@1.0.0
├─ is-data-descriptor@1.0.0
├─ is-descriptor@1.0.2
├─ is-extglob@2.1.1
├─ is-glob@4.0.0
├─ is-obj@1.0.1
├─ is-object@1.0.1
├─ is-plain-object@2.0.4
├─ is-promise@2.1.0
├─ is-typedarray@1.0.0
├─ is-utf8@0.2.1
├─ is-windows@1.0.2
├─ isarray@1.0.0
├─ isbinaryfile@3.0.3
├─ isstream@0.1.2
├─ istextorbinary@2.2.1
├─ jhipster-core@3.0.2
├─ js-yaml@3.11.0
├─ json-parse-better-errors@1.0.2
├─ json-schema-traverse@0.3.1
├─ json-schema@0.2.3
├─ json-stringify-safe@5.0.1
├─ jsprim@1.4.1
├─ kind-of@3.2.2
├─ load-json-file@4.0.0
├─ locate-path@2.0.0
├─ lodash.difference@4.5.0
├─ lodash.pad@4.5.1
├─ lodash.padend@4.6.1
├─ lodash.padstart@4.6.1
├─ lodash.uniq@4.5.0
├─ log-symbols@2.2.0
├─ macos-release@1.1.0
├─ make-dir@1.3.0
├─ map-visit@1.0.0
├─ mem-fs-editor@4.0.3
├─ merge2@1.2.2
├─ micromatch@3.1.10
├─ mime-db@1.35.0
├─ mime-types@2.1.19
├─ minimist-options@3.0.2
├─ mixin-deep@1.3.1
├─ nanomatch@1.2.13
├─ nice-try@1.0.4
├─ oauth-sign@0.9.0
├─ object-copy@0.1.0
├─ os-shim@0.1.3
├─ p-cancelable@0.3.0
├─ p-limit@1.3.0
├─ p-locate@2.0.0
├─ p-timeout@1.2.1
├─ pascalcase@0.1.1
├─ path-dirname@1.0.2
├─ path-exists@3.0.0
├─ path-is-absolute@1.0.1
├─ path-parse@1.0.6
├─ performance-now@2.1.0
├─ pinkie@2.0.4
├─ pkg-up@2.0.0
├─ plugin-error@0.1.2
├─ pluralize@7.0.0
├─ posix-character-classes@0.1.1
├─ prettier@1.12.1
├─ pretty-bytes@4.0.2
├─ process-nextick-args@2.0.0
├─ psl@1.1.29
├─ punycode@1.4.1
├─ qs@6.5.2
├─ quick-lru@1.1.0
├─ randexp@0.4.9
├─ read-chunk@2.1.0
├─ read-pkg@3.0.0
├─ rechoir@0.6.2
├─ remove-trailing-separator@1.1.0
├─ repeat-element@1.1.3
├─ replace-ext@0.0.1
├─ resolve-url@0.2.1
├─ resolve@1.8.1
├─ restore-cursor@2.0.0
├─ ret@0.2.2
├─ rimraf@2.6.2
├─ rx@4.1.0
├─ rxjs@5.5.11
├─ safer-buffer@2.1.2
├─ scoped-regex@1.0.0
├─ set-value@2.0.0
├─ shebang-regex@1.0.0
├─ shelljs@0.8.2
├─ snapdragon-node@2.1.1
├─ snapdragon-util@3.0.1
├─ source-map-resolve@0.5.2
├─ source-map-url@0.4.0
├─ source-map@0.5.7
├─ spawn-sync@1.0.15
├─ spdx-correct@3.0.0
├─ spdx-exceptions@2.1.0
├─ split-string@3.1.0
├─ sprintf-js@1.0.3
├─ sshpk@1.14.2
├─ stack-trace@0.0.10
├─ static-extend@0.1.2
├─ streamfilter@1.0.7
├─ string_decoder@1.1.1
├─ string-template@0.2.1
├─ strip-bom-stream@2.0.0
├─ supports-color@5.5.0
├─ symbol-observable@1.0.1
├─ tabtab@2.2.2
├─ textextensions@2.2.0
├─ to-regex-range@2.1.1
├─ tslib@1.9.3
├─ tunnel-agent@0.6.0
├─ tweetnacl@0.14.5
├─ typedarray@0.0.6
├─ union-value@1.0.0
├─ unset-value@1.0.0
├─ untildify@3.0.3
├─ urix@0.1.0
├─ use@3.1.1
├─ util-deprecate@1.0.2
├─ validate-npm-package-license@3.0.4
├─ verror@1.10.0
├─ vinyl-file@2.0.0
├─ winston@2.4.2
├─ xtend@4.0.1
├─ yargs-parser@10.1.0
├─ yeoman-environment@2.1.1
└─ yeoman-generator@2.0.5
Done in 12.28s.

##### **JHipster Version(s)**

Currently I've the version 5.0.1 and it upgraded without problems from other versions below 5.0.1

##### **JHipster configuration**

D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\upgrade>jhipster info
Using JHipster version installed globally
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter
`-- (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

- where jhipster:
C:\Users\usuario\AppData\Local\Yarn\bin\jhipster
C:\Users\usuario\AppData\Local\Yarn\bin\jhipster.cmd

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.16.2.windows.1

node: v8.11.1

npm: 5.6.0

yeoman: 2.0.5

yarn: 1.7.0

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

Congratulations, JHipster execution is complete!

D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\upgrade>

##### **Browsers and Operating System**

Windows 10 Home

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
And how did you install JHipster? This could be an issue with Yarn but I doubt it - are you able to upgrade other packages?

**Comment by deepu105** [comment]
I'm really getting tired of all these npm/yarn compatibility issues. Yarn
is slowly diverging as well, may be it will be much easier for us and our
users if we just switch back to NPM and ditch Yarn altogether or atleast
make NPM default and yarn optional. The latest version of NPM is as fast as
Yarn if not faster and they are copying all Yarn features anyway

**Comment by jdubois** [comment]
Yes for me it's pretty clear now that we should remove Yarn.

**Comment by deepu105** [comment]
Lets make NPM the default option first and see how it goes so that existing
apps who upgrade don't have any issues. In the next major version we can
drop Yarn. Wdyt?

**Comment by jdubois** [comment]
Yes @deepu105 that could be a huge migration for some people, so we can't migrate like that. Changing the default, however, isn't a big deal, and nobody should complain. We'll drop Yarn in JHipster 6.0, probably, but not before.

**Comment by jdubois** [comment]
I'm closing this because it's an installation problem, either with NPM or Yarn (or maybe Chocolatey/Homebrew/etc - we provide so many options!). So you need to check your package manager, and how you installed the module.

**Comment by Tonterias** [comment]
I worked like Jon said,
-------------------------------------------------------------------------------------------------------------
Usually the fix to this issue is to uninstall from npm and yarn then reinstall with one or the other:

# Remove from both yarn and npm
yarn global remove generator-jhipster
npm uninstall -g generator-jhipster

# Install with just yarn
yarn global add generator-jhipster
--------------------------------------------------------------------------------------------------------
Thanks Jon

**Comment by soungsid** [comment]
Hi
it worked for me as Jon an Tonterias said. 

but When I was on **npm 5.6**    updgrade wasn't working. but when I upgrate to the  npm 6.4 I'am able now to upgrate Jhispter ton 5.2.1 version. I hope this information can help.
