### ISSUE TITLE
jhipster 5.2.1 upgrade project failure on the queston "? May JHipster anonymously report usage statistics to improve the tool over time"

### ISSUE THREAD

**Issue by carrotagileit** [jhipster/generator-jhipster#8156]
Upgrade to jhipster 5.2.1 fine global.

Hower then upgrades any project with jhipster upgrade always hung on the question. No matter press Y or N or just press Enter.

"? May JHipster anonymously report usage statistics to improve the tool over time"

I tried waiting for two hours, still on the hung there on the same question.

##### **Motivation for or Use Case**

`Done in 137.15s.
√ Updated generator-jhipster to version 5.2.1
     info Removing .cache-loader
     info Removing .classpath
     info Removing .editorconfig
     info Removing .factorypath
     info Removing .gitattributes
     info Removing .gitignore
     info Removing .prettierignore
     info Removing .prettierrc
     info Removing .project
     info Removing .settings
     info Removing .vscode
     info Removing angular.json
     info Removing logFile.2018-08-24.log
     info Removing mvnw
     info Removing mvnw.cmd
     info Removing node
     info Removing package.json
     info Removing pom.xml
     info Removing proxy.conf.json
     info Removing README.md
     info Removing src
     info Removing target
     info Removing tsconfig-aot.json
     info Removing tsconfig.json
     info Removing tslint.json
     info Removing webpack
     info Removing yarn-error.log
√ Cleaned up project directory
Regenerating application with JHipster 5.2.1...
C:\Users\wmsis\Documents\workspace-sts\crmA\node_modules\.bin
     info "C:\Users\wmsis\Documents\workspace-sts\crmA\node_modules\.bin/jhipster" --with-entities --force --skip-install
Using JHipster version installed globally
Running default command
Executing jhipster:app
Options: withEntities: true, force: true, skipInstall: true, with-entities: true, skip-install: true

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v5.2.1
Application files will be generated in folder: C:\Users\wmsis\Documents\workspace-sts\crmA
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

? May JHipster anonymously report usage statistics to improve the tool over time`

Jhipster version: 5.2.1

Windows 10 Pro

**Comment by jdubois** [comment]
Oh that's because the question is waiting for an answer, but as it's in a script you probably can't input the answer!

- Quick fix for you: install 5.2.1 manually, run it once and answer the question - then you will be good to go as it won't be asked again (unless you answer "no", then you are asked every 100th run).
- Please keep the ticket open, I will force this in the script (I'll probably do `--no-insight` so we'll lose all the stats, even if you answered "yes", but at least it won't block)

**Comment by jdubois** [comment]
In fact there was a mistake in the script, it was written `--skip-insight` instead of `--no-insight`! Fix coming very soon :-)

**Comment by carrotagileit** [comment]
@jdubois Thanks for you quick fix.

So how to make it work in my side? What's you mean   "install 5.2.1 manually" ?

**Comment by jdubois** [comment]
@carrotagileit you install it using `yarn global add generator-jhipster` (probably, we have tons of setup options), and run `jhipster` once in an empty folder. The first question will be about sending the stats, just say "Yes" or "No" (hopefully "Yes"!!), and then you won't get the question, so the upgrade script will work.

**Comment by carrotagileit** [comment]
By running: 

- yarn global add generator-jhipster 
- mkdir temp
- cd temp
- jhipster

the problem is gone. Thanks.

**Comment by piaofudeyu** [comment]
By running:

yarn global add generator-jhipster
mkdir temp
cd temp
jhipster


the problem stall~~~
