### ISSUE TITLE
Protractor test output is different between React and Angular

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#8164]
The outputs from Protractor are different. With Angular, it shows dots, while React shows test names.

React:

```
[17:27:35] I/direct - Using ChromeDriver directly...


  Account
    ✓ should fail to login with bad password
    ✓ should login with admin account (2709ms)

  Administration
    ✓ should load metrics
    ✓ should load health
    ✓ should load configuration
    ✓ should load audits
    ✓ should load logs
    User management
      ✓ should load user management (2077ms)


  8 passing (13s)
```

Angular:

```
[17:35:43] I/direct - Using ChromeDriver directly...
Started
...........


11 specs, 0 failures
Finished in 31.203 seconds
```

I like React's output, especially the timings that show slow tests. Not sure if that's on purpose, or [zsh-command-time](https://github.com/popstas/zsh-command-time) that I have installed.

**Comment by deepu105** [comment]
Thats coz of the framework used underneath. In Angular setup we use protractor with Jasmine and in React its Mocha + Chai.

Mocha has nice reporters out of the box. I once tried to get the same from Jasmine but it was no where near close to what mocha haf. May be things changed now and there is a better reporter for Jasmine now

**Comment by deepu105** [comment]
Also the timing comes from Mocha as well

**Comment by wmarques** [comment]
@deepu105 maybe we can use mocha + chai on Angular ?

**Comment by deepu105** [comment]
We could and that way we can move protractor test templates outside react/angular folder and reuse them for both. E2e should be same regardless of technology anyway and what works for React should work for angular as well.

**Comment by jdubois** [comment]
Oh that would be very impressive!

**Comment by wmarques** [comment]
I can work on this on Friday as the typescript 3 work seems blocked by Angular...

**Comment by wmarques** [comment]
@deepu105 I started to migrate from jasmine to mocha/chai on Angular. I'll provide a PR for this only and keep separate e2e tests. Then we can start "merging" the tests but we'll have some work to do to have same CSS selectors and same tests scenarios across the frameworks.

**Comment by wmarques** [comment]
This is fixed by https://github.com/jhipster/generator-jhipster/pull/8197 right?

**Comment by ruddell** [comment]
Yep, outputs now match.  Nice job
