### ISSUE TITLE
Current timestamp for the created_date not supported for the PostgreSQL

### ISSUE THREAD

**Issue by nadworny** [jhipster/generator-jhipster#8168]
##### **Overview of the issue**
Cloudfoundry deployment will fail for PostgreSQL due to the missing `now` type for the current date

##### **Motivation for or Use Case**
Using PostgreSQL

##### **Reproduce the error**
Generate basic project

##### **Suggest a Fix**
Add the following to the liquibase initial schema changelog:
`<property name="now" value="CURRENT_TIMESTAMP" dbms="postgresql"/>`

##### **JHipster Version(s)**
5.1

##### **JHipster configuration**
default

##### **Browsers and Operating System**

MacoS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry but I do this all the time, I'm sure this works...
Do you have a specific version of Postgresql? Or some specific configuration? Can you test with our Docker image (in `src/main/docker/postgresql.yml`) to check if you can reproduce?

**Comment by nadworny** [comment]
my fault, sorry :) I generated with mysql support...

**Comment by jdubois** [comment]
Ah, I was getting quite nervous about a new nasty bug :-)
