### ISSUE TITLE
Exception generating client code for entity in a react monolithic application

### ISSUE THREAD

**Issue by prasenjithaty** [jhipster/generator-jhipster#8175]
##### **Overview of the issue**

generator is unable to generate `entity-update.tsx` and fails with the following error
```
jhipster entity alumni                                                                               1 ↵  1892  01:17:07 
Using JHipster version installed locally in current project's node_modules
Executing jhipster:entity alumni
Options: 

Found the .jhipster/Alumni.json configuration file, entity can be automatically generated!


The entity alumni is being updated.

? Do you want to update the entity? This will replace the existing files for this entity, all your custom code will be overwritten Yes, re generate the entity
identical src/main/java/org/jecnaa/alumnus/domain/Alumni.java
identical src/main/java/org/jecnaa/alumnus/repository/AlumniRepository.java
identical src/main/java/org/jecnaa/alumnus/web/rest/AlumniResource.java
identical src/main/java/org/jecnaa/alumnus/service/AlumniService.java
identical src/main/java/org/jecnaa/alumnus/service/impl/AlumniServiceImpl.java
identical src/test/java/org/jecnaa/alumnus/web/rest/AlumniResourceIntTest.java
identical src/main/webapp/app/entities/alumni/alumni-delete-dialog.tsx
identical src/main/webapp/app/entities/alumni/alumni-detail.tsx
SyntaxError: '>' expected. (87:12)
  85 |     return (
  86 |       <div>
> 87 |       <Row className="justify-content-center">
     |            ^
  88 |         <Col md="8">
  89 |           <h2 id="jecnaaApp.alumni.home.createOrEditLabel">
  90 |             Create or edit a Alumni
    at e (/Users/hatyp/development/jecnaa/node_modules/prettier/parser-typescript.js:1:329)
    at Object.parse (/Users/hatyp/development/jecnaa/node_modules/prettier/parser-typescript.js:1:1844304)
    at Object.parse$2 [as parse] (/Users/hatyp/development/jecnaa/node_modules/prettier/index.js:7000:19)
    at coreFormat (/Users/hatyp/development/jecnaa/node_modules/prettier/index.js:10196:23)
    at format (/Users/hatyp/development/jecnaa/node_modules/prettier/index.js:10367:16)
    at formatWithCursor (/Users/hatyp/development/jecnaa/node_modules/prettier/index.js:10379:12)
    at /Users/hatyp/development/jecnaa/node_modules/prettier/index.js:31222:15
    at Object.format (/Users/hatyp/development/jecnaa/node_modules/prettier/index.js:31241:12)
    at prettier.resolveConfig.then (/Users/hatyp/development/jecnaa/node_modules/generator-jhipster/generators/generator-transforms.js:24:35)
    at <anonymous>

```

##### **Motivation for or Use Case**

Unable to generate the react client templates using `jhipster generator`

##### **Reproduce the error**

- generate a monolithic application with ReactJS as the client template engine
- copy the Alumni.json file inside `.jhipster` directory and run `jhipster entity alumni` to regenerate all the boilerplate files

##### **Related issues**

N/A

##### **Suggest a Fix**

The error is being thrown from this line. I can't figure out anything wrong there.
https://github.com/jhipster/generator-jhipster/blob/de5e7157f2960ad493dda11121f60d68e8b3b3c2/generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs#L238

##### **JHipster Version(s)**

```
jecnaa@0.0.0 /Users/hatyp/development/jecnaa
├── generator-jhipster@5.2.1
├─┬ generator-jhipster-docker@2.5.0
│ └── generator-jhipster@5.2.1  deduped
└─┬ generator-jhipster-nav-element@2.0.3
  └── generator-jhipster@5.2.0

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jecnaa.alumnus"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "jecnaa",
    "packageName": "org.jecnaa.alumnus",
    "packageFolder": "org/jecnaa/alumnus",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-nav-element",
        "version": "2.0.3"
      },
      {
        "name": "generator-jhipster-docker",
        "version": "2.5.0"
      }
    ],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>Alumni.json</summary>
<pre>
{
  "fluentMethods": true,
  "clientRootFolder": "",
  "relationships": [],
  "fields": [
    {
      "fieldName": "firstName",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "pattern"
      ],
      "fieldValidateRulesPattern": "(^[a-z ,.'-]+$)"
    },
    {
      "fieldName": "lastName",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "pattern"
      ],
      "fieldValidateRulesPattern": "(^[a-z ,.'-]+$)"
    },
    {
      "fieldName": "nickName",
      "fieldType": "String"
    },
    {
      "fieldName": "emailAddress",
      "fieldType": "String"
    },
    {
      "fieldName": "phoneNumber",
      "fieldType": "String",
      "fieldValidateRules": [
        "pattern"
      ],
      "fieldValidateRulesPattern": "(^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$)"
    },
    {
      "fieldName": "cellPhone",
      "fieldType": "String",
      "fieldValidateRules": [
        "pattern"
      ],
      "fieldValidateRulesPattern": "(^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$)"
    },
    {
      "fieldName": "department",
      "fieldType": "String",
      "fieldValidateRules": [
        "required"
      ]
    },
    {
      "fieldName": "yearOfPassing",
      "fieldType": "LocalDate",
      "fieldValidateRules": [
        "required"
      ]
    },
    {
      "fieldName": "dateOfBirth",
      "fieldType": "LocalDate",
      "fieldValidateRules": [
        "required"
      ]
    }
  ],
  "dto": "no",
  "searchEngine": false,
  "service": "serviceImpl",
  "entityTableName": "alumni",
  "jpaMetamodelFiltering": false,
  "pagination": "pagination"
}
</pre>
</details>
<details>
<summary>JDL entity definitions</summary>

<pre>
entity Alumni {
  firstName String required pattern(/(^[a-z ,.'-]+$)/),
  lastName String required pattern(/(^[a-z ,.'-]+$)/),
  nickName String,
  emailAddress String,
  phoneNumber String pattern(/(^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$)/),
  cellPhone String pattern(/(^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$)/),
  department String required,
  yearOfPassing LocalDate required,
  dateOfBirth LocalDate required
}
paginate Alumni with pagination
service Alumni with serviceImpl

</pre>
</details>

##### **Browsers and Operating System**

openjdk version "1.8.0_172"
OpenJDK Runtime Environment (Zulu 8.30.0.1-macosx) (build 1.8.0_172-b01)
OpenJDK 64-Bit Server VM (Zulu 8.30.0.1-macosx) (build 25.172-b01, mixed mode)

git version 2.14.3 (Apple Git-98)

node: v8.11.4

npm: 5.6.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880f

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I don't why, but it's the pattern on the `lastName` that causes the issue

**Comment by jdubois** [comment]
Oh I didn't test `lastName` but the other patterns work (I just did a diff to try to find the issue)

**Comment by deepu105** [comment]
ping @MathieuAA

**Comment by MathieuAA** [comment]
So weird: reproduced with both the JDL import & the questions/answers. With the latest generator version. I think I've found out why: it's because of the `'` in the regex

**Comment by MathieuAA** [comment]
I thought the generator does escape characters. There may be a fix to do

**Comment by MathieuAA** [comment]
Done for JCore, it must also be done for the entity generator, working on it

**Comment by jdubois** [comment]
Re-opening as PR as been rolled back
