### ISSUE TITLE
Builds failed for Gradle: missing jhipster-dependencies 2.0.18

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#8186]
There was a release of jhipster/jhipster v2.0.18 yesterday, 16 hours ago.
- it seems OK for Maven: https://mvnrepository.com/artifact/io.github.jhipster/jhipster-dependencies
- but KO for Gradle ; there is no 2.0.18 here https://jcenter.bintray.com/io/github/jhipster/jhipster-dependencies/

That's why all builds failed with Gradle.

@jdubois : I ping you as you are the only one who can fix it. Maybe just wait more than 24 hours ?

**Comment by jdubois** [comment]
Thanks @pascalgrimaud - yes I know about this, I was waiting a few hours to test again. We can't do much more anyway!

**Comment by pascalgrimaud** [comment]
Just to let you know, it's the same issue for `0.1.14` too

**Comment by jdubois** [comment]
Oh, and I see `0.1.14` never made it!! That's very bad from JCenter, as it means its sync system is just broken!!!
I'll release a `2.0.19`, that's the only way I know to force this.

**Comment by jdubois** [comment]
Looks like `2.0.19` is also not sync'ing to JCentral... They must have a bug, we can't do anything but wait, last time I contacted them for such an issue (for `0.1.14`) they told me that as I wasn't a customer I couldn't get support (which is fair, of course).

**Comment by jdubois** [comment]
I'm really not good at using Gradle, so please @atomfrede correct me if I'm wrong, but can't we use `mavenCentral()` to get the artifacts from Maven Central instead or Bintray? That would solve that issue, and would also be better for our stats (as I get the stats from Maven Central on our number of downloads)

**Comment by atomfrede** [comment]
Yes totally right. We should remove jcenter such that only one repository
is queried.

**Comment by pascalgrimaud** [comment]
@atomfrede @jdubois : I look an older version of JHipster randomly: 4.0.5, we had this config before:
https://github.com/jhipster/generator-jhipster/blob/v4.0.5/generators/server/templates/_build.gradle#L7

So I think it was removed, as discussed in this ticket: https://github.com/jhipster/generator-jhipster/issues/6252

> Every repository declaration slows down the build, because on missing or dynamic dependencies, Gradle has to look into each one of them in turn. I assume that may of these repos aren't actually necessary. For instance mavenCentral is fully contained in jcenter().

**Comment by atomfrede** [comment]
Exactly.

**Comment by jdubois** [comment]
OK I get it, then `For instance mavenCentral is fully contained in jcenter()` is not totally true, as we are getting those sync errors... And that's the second time, and we are quite blocked now.

So I'm for migrating back to Maven central

**Comment by jdubois** [comment]
At least I'm doing this now to fix the build....

**Comment by jdubois** [comment]
The sync process is getting better today, but it's still lacking the latest version.... I'm waiting for it to sync, and if it works I'll revert my commit and switch back to jcenter.
