### ISSUE TITLE
OWASP Dependency Checker for backend security

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#8191]
##### **Overview of the feature request**

Add OWASP dependency checker in Maven and Gradle builds

##### **Motivation for or Use Case**

This PR is inspired by the Devoox FR Talk [Sécurité des applications Web les bons réflexes à avoir (E. Lenoir)
](https://www.youtube.com/watch?v=UW2ZsbhbFDY)

Security is always underestimated, thanks to this talk I've discovered easy to setup tools. The aim of this PR is to have provided a security dependency checker for the generated projects.

I've made some tests and found CVEs on the sample projects.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Well I stay on my comments to #6329 :)

**Comment by jdubois** [comment]
Indeed @gmarziou you are right
Then, as I had quite a lot of trouble to set up those tools for one of my clients (and with a good configuration it works great!), maybe we should rather do a documentation page?

**Comment by danielpetisme** [comment]
@gmarziou sorry I should have search an existing issue before creating this one.

You've got more experience on that topic. So go for a doc.

Should we fix the current identified CVEs ?

**Comment by gmarziou** [comment]
> Should we fix the current identified CVEs ?

Yes

**Comment by jdubois** [comment]
OK then I'm closing this as there won't be anything coded here, just a new documentation page.

-> @danielpetisme if you want to do it, just duplicate a simple page and write the markdown, I know it's hard to test and integrate so if you have issues on those don't worry I will fix that. The most important thing is the content itself.

**Comment by danielpetisme** [comment]
Should I create a new page or could I continue this one https://www.jhipster.tech/security/

**Comment by jdubois** [comment]
@danielpetisme this is worth a specific page, it's quite big. And of course we can link it to the other pages
