### ISSUE TITLE
Microservices gateway fail to communicate with other services when enable https 

### ISSUE THREAD

**Issue by TonyLuo** [jhipster/generator-jhipster#8192]
##### **Overview of the issue**
there are 4 services(include gateway and jhipster-registry) in my microservices app:  jhipster-registry-4.0.0, gateway, order , core.
 Everything is fine when using http.
but the  gateway fail to communicate with other services when enable https for **gateway**, **order** and **core** service

##### **Related issues**

> 2018-08-31 11:32:50.214  INFO 53257 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
> 2018-08-31 11:33:01.510  INFO 53257 --- [ XNIO-2 task-11] c.z.gateway.security.jwt.TokenProvider   : Invalid JWT token.
> 2018-08-31 11:33:01.520 DEBUG 53257 --- [ XNIO-2 task-11] c.z.g.g.a.AccessControlFilter            : Access Control: allowing access for /core/api/authenticate, as it matches the following authorized microservice endpoint: /core/api
> 2018-08-31 11:33:02.559  WARN 53257 --- [ XNIO-2 task-11] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering
> 
> com.netflix.zuul.exception.ZuulException: 
> 	at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.findZuulException(SendErrorFilter.java:114)
> 	at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.run(SendErrorFilter.java:76)
> 	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117)
> 	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
> 	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157)
> 	at com.netflix.zuul.FilterProcessor.error(FilterProcessor.java:105)
> 	at com.netflix.zuul.ZuulRunner.error(ZuulRunner.java:112)
> 	at com.netflix.zuul.http.ZuulServlet.error(ZuulServlet.java:145)
> 	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:83)
> 	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:165)

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/tony/dev/microservice/gateway
└── generator-jhipster@5.2.1 

```
application.yml
```yml
server:
    port: 8443
    ssl:
        key-store: xxx.com.pfx
        key-store-password: xxxxxx
        keyStoreType: PKCS12
```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.zykj.gateway",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.zykj.gateway",
    "packageFolder": "com/zykj/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.15.1 (Apple Git-101)

node: v8.11.3

npm: 6.4.0

yeoman: 2.0.0

yarn: 1.7.0

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
(I edited your ticket to remove the keystore password!)

You don't give the full stacktrace, but I guess you have an SSL error? Are the other JVM trusting your certificate? That's a bit complex to set up manually (for that kind of thing, Istio will be so much better, see #7708 ) and I'm pretty sure that's your issue.

Unfortunately we can't set this automatically for you...

**Comment by TonyLuo** [comment]
I use nginx as  gateway load balancer and enable the https on nginx finally to achieve the same goal ...
 thanks so much for your reply
