### ISSUE TITLE
SwaggerBasePathRewritingFilter with http gzip compression 

### ISSUE THREAD

**Issue by ndywicki** [jhipster/generator-jhipster#8196]
Hello team,

With microservices applications and the **gateway** in Jhipster v5.2.1 (maybe older v5 also) when the server http compression is enabled (ex. with prod profil),  the response of an request after `Zull Filter` and `SwaggerBasePathRewritingFilter `the **Content-type** is '**gzip**' but the content is **decompressed**.

Note: spring-cloud-netflix-zuul alway send the Accept-Encoding to 'gzip' : [ProxyRequestHelper](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper.java#L151)

HTTP response from micro app directly : Content-type = content
![curl-app](https://user-images.githubusercontent.com/1721344/44912722-73a21080-ad2b-11e8-9e99-bfb839aa431a.JPG)

HTTP response from app through the gateway : Content-type != content

![curl-gateway-app](https://user-images.githubusercontent.com/1721344/44912723-73a21080-ad2b-11e8-9307-e1a2b05d8627.jpg)

Result browser or http client like Swagger UI failed to decode the content.

Browser:
![browser_failed_decode_contentjpg](https://user-images.githubusercontent.com/1721344/44911649-e7dab500-ad27-11e8-9e9b-8527b617c30c.JPG)

Swagger-UI:
![swagger_error](https://user-images.githubusercontent.com/1721344/44911651-e7dab500-ad27-11e8-9ec3-86d7fa157745.JPG)

(Error message isn't clear. Initially I  was thinking about an CORS issue)

With an gateway in v4 and spring-cloud-netflix-zuul 1.3.5 this issue isn't occure.

I'm not sure where is the root of this issue there is no messages exception.
Maybe in a recent change / fix or new issue in spring-cloud-netflix-zuul and gzip encoding (ex. https://github.com/spring-cloud/spring-cloud-netflix/issues/3122) or an EOF after reading the data stream GZIPInputStream in swagger filter.

However, I find that everything works perfectly if I deactivate the `SwaggerBasePathRewritingFilter` in the `GatewayConfiguration` :

![swagger_ok_with_filter_disabled](https://user-images.githubusercontent.com/1721344/44911648-e7421e80-ad27-11e8-9d95-87ab5c1ec92a.JPG)

![browser_gzipdisabled](https://user-images.githubusercontent.com/1721344/44912545-e363cb80-ad2a-11e8-8ec5-b468bc28e8ee.JPG)

But the HTTP header have also `Content-Encoding: gzip`. 
So I don't understand what's happen and why is working in this case... 

##### **Motivation for or Use Case**

Use Swagger UI and server compression enabled

##### **Reproduce the error**

1. Generate a `gateway` and `app` with default options.
2. Run the `app` with prod mode or enable server compression in dev configuration
3. Run the `gateway` (with dev or prod)
4. Open http://localhost:8080/app/v2/api-docs in browser

##### **Related issues**

This https://github.com/jhipster/generator-jhipster/pull/8025 but it's about Spring security not gzip content

##### **Suggest a Fix**

Maybe remove `SwaggerBasePathRewritingFilter`. Is alway useful ?
Force Swagger UI client to set the Accept-Encoding to 'gzip'

##### **JHipster Version(s)**

v5.2.1

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 C:\workspace\jhipster\version\v5.2.1\micro\gateway-gzip
`-- generator-jhipster@5.2.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "fr.myproject.myapp"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "fr.myproject.myapp",
    "packageFolder": "fr/myproject/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.9.3.windows.1

node: v8.11.4

npm: 5.7.1

yeoman: 1.8.5

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

- [x] Checking this box is mandatory (this is just to show you read everything)

yo-rc.json gateway and app1 :
[yo-rc.json.zip](https://github.com/jhipster/generator-jhipster/files/2340072/yo-rc.json.zip)

**Comment by jdubois** [comment]
Hey @ndywicki thanks for such a complete bug report! On a personal note: didn't we work together at the French central bank?

**Comment by ndywicki** [comment]
Correct ! you made a code review of our project with @agoncal ;)

**Comment by jdubois** [comment]
@ndywicki I'm sure your code was awesome :-)
(to be honest I don't remember!!)

**Comment by PierreBesson** [comment]
We can't remove the SwaggerBasePathRewritingFilter as it is required to have the correct base path in the swagger doc so calls on microservices endpoints using the try-it-out button won't fail.
> Force Swagger UI client to set the Accept-Encoding to 'gzip'

This is doable, but as we plan to migrate to swagger ui v3, we can do this later.
> An EOF after reading the data stream GZIPInputStream in swagger filter.

This might be what's happening, it's true that there were some breaking changes with Zuul during the Spring boot 1 -> Spring boot 2 migration.

**Comment by ndywicki** [comment]
@pascalgrimaud, Glad to see that we come to the same conclusion : remove the `SwaggerBasePathRewritingFilter` class ;-)

**Comment by PierreBesson** [comment]
But this filter is the magic that let's you have the right basePath for doing API call, I'm pretty sure that it can't work without it !

**Comment by pascalgrimaud** [comment]
@ndywicki : yes and I shouldn't loose so much time on this, if I saw your comment before, because we did the exact same analysis. It's my fault.

@PierreBesson : agree but it was 2 years ago, now I think some lib / class have been upgraded. You should give a try without it

**Comment by PierreBesson** [comment]
After having a quick look, it seems that the BasePathRewritingFilter doesn't correctly rezip the payload once edited. It looks like something that can be fixed.
