### ISSUE TITLE
Refactor de Repositories to use Optional

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#820]
Refactor like here:
https://github.com/spring-projects/spring-data-examples/blob/master/jpa/java8/src/main/java/example/springdata/jpa/java8/CustomerRepository.java
- this is only for the Java8 version, of course
- this could work for both MongoDB and JPA
- we need to check if this really improves the end result

cc @Fabszn

**Comment by cm325** [comment]
So, now that jhipster uses Java 8 by default, is it time to revisit this?
