### ISSUE TITLE
Count by criteria

### ISSUE THREAD

**Issue by Blackdread** [jhipster/generator-jhipster#8214]
##### **Overview of the feature request**

Be able to return only a count by criteria, very similar to "findByCriteria" in QueryService and  "getAllXXXXXX" in resource.

I have this feature in my apps for long time now but jHipster does not offer it by default which it could I think.
I looks like:
```
    /**
     * GET  /my-entities/count : count all the my-entities.
     *
     * @param criteria the criterias which the requested entities should match
     * @return the ResponseEntity with status 200 (OK) and the count in body
     */
    @GetMapping("/my-entities/count")
    @Timed
    public ResponseEntity<Long> countAllMyEntities(MyEntityCriteria criteria) {
        log.debug("REST request to count myEntities by criteria: {}", criteria);
        return ResponseEntity.ok(myEntityQueryService.countByCriteria(criteria));
    }
```

and

```
    /**
     * Return a count which matches the criteria from the database
     * @param criteria The object which holds all the filters, which the entities should match.
     * @return the count of matching entities.
     */
    @Transactional(readOnly = true)
    public long countByCriteria(MyEntityCriteria criteria) {
        log.debug("count by criteria : {}", criteria);
        final Specification<MyEntity> specification = createSpecification(criteria);
        return myEntityRepository.count(specification);
    }
```

##### **Motivation for or Use Case**

Enable count by default as a feature

##### **Related issues or PR**

None

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Blackdread** [comment]
Thank you, I will do a PR if the team think we can add this feature.
I can add at least one or two tests so code is not completely "unused".
Indeed it will work only when service and DTO are selected and criterias with filetring.

**Comment by jdubois** [comment]
Oh sorry, I understand it's different with service/DTO, as you do this by criteria, so it's fine if you don't have the same REST endpoints.
So that looks OK for me, but it's a complex part that I don't know extremely well - I would appreciate more comments from other people, just to be sure.

**Comment by gzsombor** [comment]
In which scenario do you need only the count of entities, but not the first page of entities in the UI layer? But this doesn't seems to difficult to implement.

**Comment by Blackdread** [comment]
I use it when I do not need to fetch all the data from DTOs.
Sometimes I can have some async data for display purposes, no sorting, etc so a count only will be faster than fetching a page of one element by criteria and then get the count from the header.
It is a point of view, either a count only is returned in the body or 0/1 entity dto is returned with some header for the "X-Total-Count"

**Comment by gzsombor** [comment]
I've claimed the bounty: https://opencollective.com/generator-jhipster/expenses/5116
