### ISSUE TITLE
MS SQL Server should not use tempdb when working with Docker Compose

### ISSUE THREAD

**Issue by duderoot** [jhipster/generator-jhipster#8215]
##### **Overview of the feature request**

When working with docker-compose and MS SQL then the default database in tempdb. MS SQL is cleaning this database on each restart i.e. data can get lost.

##### **Motivation for or Use Case**

 For the persistence of the data I use docker volumes. The problem is that  when I throw the container and restart  my data is also lost although I use volumes in order to persist the data.
It looks like MS SQL is cleaning the tempdb on restart.

##### **Related issues or PR**
@jdubois  motivated his choice in #7271. My sugestion is to use a similar aproach like we have in MySQL
`command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp`
As an example we can do something like:
`command: /bin/bash -c '/opt/mssql/bin/sqlservr & echo "wait 7 sec for DB to start "; sleep 7; /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -d tempdb -q "EXIT(CREATE DATABASE $$DATABASE)";  wait'`

This solution is persisting my data when I use docker volumes and I also recreate the container

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Ping @ruddell as he's the one who added the support.

**Comment by ruddell** [comment]
That looks good, would you like to PR?  I can't test MSSQL volumes on Mac as they are not supported ("Mounting a volume does not work on Docker for Mac" - [MSSQL on Docker Hub](https://hub.docker.com/r/microsoft/mssql-server-linux/))

Make sure you aren't using the Docker image in prod without a valid license, though you can use `MSSQL_PID=Express` for a free database up to 10GB ([MSSQL License page](https://www.microsoft.com/en-us/sql-server/sql-server-2017-pricing))  😉

**Comment by duderoot** [comment]
@ruddell  thank you for the hints 😃 . I crea a PR and the mssql.yml looks ok. In the docker-compose.yml the command layout is not well  formated ⚠️  thats why is for the moment WIP.
