### ISSUE TITLE
Enums should be used for declaring constants

### ISSUE THREAD

**Issue by yatendragoel** [jhipster/generator-jhipster#8224]
##### **Overview of the issue**
Instead of Class, Enums should be used for declaring constants. 

##### **Motivation for or Use Case**
The following and other similar ones should be changed

    public final class AuthoritiesConstants {

        public static final String ADMIN = "ROLE_ADMIN";

        public static final String USER = "ROLE_USER";

        public static final String ANONYMOUS = "ROLE_ANONYMOUS";

        private AuthoritiesConstants() {
        }
    }

to

    public enum AuthoritiesConstants {

        ADMIN("ROLE_ADMIN"),
        USER("ROLE_USER"),
        ANONYMOUS("ROLE_ANONYMOUS");

        private String role;

        private AuthoritiesConstants(String role) {
            this.role = role;
        }
    }

Not providing `jhipster info` as it is not needed to reproduce this bug.

**Comment by Blackdread** [comment]
No, cannot use in annotations

**Comment by jdubois** [comment]
I'm trusting @Blackdread here, so indeed let's keep it that way

**Comment by jdubois** [comment]
@yatendragoel you seem to have lots of good ideas here, I need to set up something for all breaking improvements we might do in JHipster 6. I do also have quite a lot of ideas!

**Comment by yatendragoel** [comment]
@jdubois I would love to contribute both in suggesting the ideas and implementing them

**Comment by jdubois** [comment]
Awesome @yatendragoel - for JHipster 6 I think we'll do a refactoring of the framework, so new ideas will be most welcomed. However, I don't know when we'll start, probably not in the next few months... I really need to find a space where we could store all those ideas, compare them, and then have a big discussion with everyone. Maybe a specific GitHub repo.

**Comment by yatendragoel** [comment]
@jdubois 
I am not sure what tool we use for project management for JHipster. If we use GitHub Issues to track features, we can simply create a JHipster6 tag and tag all the JHipster 6 specific ideas/feature-requests. Whatever it be, let me know and I can set it up.

**Comment by deepu105** [comment]
We can also create a temp repo and use its issues for that purpose so that
we don't have to worry about main repo issues exploding

**Comment by yatendragoel** [comment]
@deepu105 @jdubois Let's create a temp GitHub repo then for the issues. I would have created it myself if I had had access to the repo.

**Comment by jdubois** [comment]
OK, just to be sure I'm going to send this also to the core dev mailing list: I think we should create a project will all default options, and maybe also include the JHipster Framework in it, for easier refactoring. Then we do all the refactoring we want, and see how we can push them back to the main project.
If those are small issues we can put them in a minor release, otherwise it would be the next major release.

**Comment by jdubois** [comment]
For the record, the main is at https://groups.google.com/forum/?hl=en#!topic/jhipster-dev/Llsp6s30PZE

**Comment by cbornet** [comment]
I was wondering how to create issues for the Reactive option without crippling the main issue tracker. Maybe I can aldo create a repo for that ?
