### ISSUE TITLE
Change webpack to angular build when separating the front-end and the API server 

### ISSUE THREAD

**Issue by sunyuyangg555** [jhipster/generator-jhipster#8228]
##### **Overview of the feature request**

When separating the front-end and the API server, we want to use the stand angular layout with angular.json build.
##### **Motivation for or Use Case**

Using a angular.json simplify webpack build and it’s easier to find answers online when we encounter problems， webpack is a more advanced build that requires more of our team. We chose this option means we gave up the automatic generation of entities. So can you provide an initial project with a standard angular layout?
##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Please read existing issues. We tried to move to angular cli builds few times but wasn't successful so unless someone is willing to do the migration this won't be done
