### ISSUE TITLE
Strong typing in 2.0

### ISSUE THREAD

**Issue by thiagonuic** [jhipster/generator-jhipster#823]
Have anyone given some thoughts about adding strong typing to jhipster in 2.0?

Some possibilities could be typescript, gwt ou coffeescript... I think typescript would be less intrusive.

**Comment by seiter** [comment]
Love the idea of a TypeScript option, especially considering some of the talks at ng-conf last week. While TypeScript isn't required in Angular 2, seems it may ease transition to Angular 2 in the future. That said, I understand the prioritization challenge.

* [TypeScript and ES6](https://www.youtube.com/watch?v=U7NYTKgkZgo&list=PLOETEcp3DkCoNnlhE-7fovYvqwVPrRiY7&index=8)
* [TypeScript and Angular 2](https://www.youtube.com/watch?v=Xw93oketp18&index=19&list=PLOETEcp3DkCoNnlhE-7fovYvqwVPrRiY7)

**Comment by bradrich** [comment]
Has anything came out of this conversation? I am extremely impressed with JHipster, really want to use it, but with Angular 2 in Beta, I am uneasy about putting a lot of effort into a standard JavaScript approach. I thought about putting TypeScript into my JHipster project anyway, but the entity generator doesn't play nicely with it.

**Comment by gmarziou** [comment]
| the entity generator doesn't play nicely with it

What do you mean?
As far as I know, you could rename .js files into .ts files.
It could probably be done via a module.

**Comment by deepu105** [comment]
@gmarziou its high time we start angular 2.0 what say

**Comment by jdubois** [comment]
Yes this will only happen when we migrate to AngularJS 2.0
