### ISSUE TITLE
Test failure on AccountResourceIntTest -> testRegisterDuplicateEmail()

### ISSUE THREAD

**Issue by raulrotundo** [jhipster/generator-jhipster#8232]
##### **Overview of the issue**

After generating a UAA micro-services, and trying to building a docker images, this error has been displayed running all test scenario:

`AccountResourceIntTest.testRegisterDuplicateEmail:406 Range for response status value 201 expected:<CLIENT_ERROR> but was:<SUCCESSFUL>`

##### **Motivation for or Use Case**

Won't be able to generate a build because this test failure.

##### **Reproduce the error**

1. Create a folder uaa.
2. Run jhipster command following the attached yo-rc.json setup (Basically generate a UAA microservice with a MongoDB).
3. Run ./mvnw package -Pprod dockerfile:build
4. You will see the test error:

`[ERROR] Tests run: 29, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.02 s <<< FAILURE! - in com.companyname.appname.web.rest.AccountResourceIntTest
[ERROR] testRegisterDuplicateEmail(com.companyname.appname.web.rest.AccountResourceIntTest)  Time elapsed: 0.658 s  <<< FAILURE!
java.lang.AssertionError: Range for response status value 201 expected:<CLIENT_ERROR> but was:<SUCCESSFUL>
	at com.companyname.appname.web.rest.AccountResourceIntTest.testRegisterDuplicateEmail(AccountResourceIntTest.java:406)`

##### **Suggest a Fix**

/generator-jhipster/generators/server/templates/src/test/java/package/web/rest/AccountResourceIntTest.java.ejs 
Line: 796

```java
        // Active secondUser (Fix)
        testUser3.get().setActivated(true);
        userRepository.save(testUser3.get())<% if (reactive) { %>.block()<% } %>;

        // Register 4th (already activated) user
        <%_ if (!reactive) { _%>
        restMvc.perform(
            post("/api/register")
                .contentType(TestUtil.APPLICATION_JSON_UTF8)
                .content(TestUtil.convertObjectToJsonBytes(secondUser)))
            .andExpect(status().is4xxClientError());
        <%_ } else { _%>
        webTestClient.post().uri("/api/register")
            .contentType(TestUtil.APPLICATION_JSON_UTF8)
            .syncBody(TestUtil.convertObjectToJsonBytes(secondUser))
            .exchange()
            .expectStatus().is4xxClientError();
        <%_ } _%> 
```

##### **JHipster Version(s)**

5.3.1

##### **JHipster configuration**

jhipster info

```terminal
##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v8.11.3

npm: 6.2.0

yeoman: 2.0.2

yarn: 1.7.0

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.21.0, build 5920eb0

```
.yo-rc.json file:
```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.companyname.appname"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "com.companyname.appname",
    "packageFolder": "com/companyname/appname",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "secret",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "skipClient": true
  }
}
```

##### **Browsers and Operating System**

Chrome, Ubuntu 18.04.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This is probably because you use Hazelcast with Mongodb together.... An unusual combinaison, but not impossible!

**Comment by raulrotundo** [comment]
@jdubois I was thinking Hazelcast has been used as cache provider, why you mentioned that Hazelcast and MongoDB together is an unusual combination? Maybe Hazelcast is doing another things behind scene?

**Comment by jdubois** [comment]
It's distributed cache on top of MongoDB: some people would argue that MongoDB is like a distributed cache, or is as fast as as distributed cache, so you wouldn't need Hazelcast.

That's why it's "unusual", as most projects I see do not use a cache with a NoSQL database (same thing for Cassandra, for example).

But, from my personal experience, adding a cache on top of a NoSQL database can give you a very significant perf enhancement - that's data access 101: taking some data directly from RAM is much faster than doing a network round-trip. So personally I would do it, and that's also why I'm going to fix this, but I know quite a lot of people won't be OK with that statement.

Anyway, that's the beauty of JHipster: if we don't agree, we do a specific option, and then we have both solutions working depending on what we prefer.

**Comment by raulrotundo** [comment]
@jdubois good point!
