### ISSUE TITLE
Gradle + API First Dev Compile Issue

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#8235]
##### **Overview of the issue**
When you choose `gradle` and the other technology `API first development using OpenAPI-generator`, the app fails to compile:
```
* Where:
Build file '/private/tmp/jh/test24/build.gradle' line: 111

* What went wrong:
Could not compile build file '/private/tmp/jh/test24/build.gradle'.
> startup failed:
  build file '/private/tmp/jh/test24/build.gradle': 111: expecting ':', found ';' @ line 111, column 98.
     ialect.MySQL5InnoDBDialect&amp;hibernate
 ```

Reported by @werwuifi in the Gitter

##### **Motivation for or Use Case**
App should compile

##### **Reproduce the error**
 - Generate an app using the features mentioned in the overview
 - Run `./gradlew` and app fails to compile
##### **Suggest a Fix**
Not sure, the code causing issues is [this section in `build.gradle`](https://github.com/jhipster/generator-jhipster/blob/55a431aafd337c62494832d6fabb76bb09631f64/generators/server/templates/build.gradle.ejs#L159-L161).  This was added in the recent PR for Liquibae Gradle #8171 so pinging @atomfrede 

##### **JHipster Version(s)**
v5.3.0+, master
works in v5.2.1
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "monolith",
    "baseName": "gradlewapi",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Environment and Tools**

<details>
<summary>Environment and Tools</summary>

<pre>
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.18.0

node: v8.11.4

npm: 6.4.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f
</pre>
</details>

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Will look into it. But currently no idea why swagger should have influence
on liquibase or vice versa.
