### ISSUE TITLE
Documentation: Need to document removal of hibernate sequences, Activate Wiki?

### ISSUE THREAD

**Issue by jancel** [jhipster/generator-jhipster#824]
When upgrading from versions older than 1.8.0, I ran across an issue where the Hibernate Sequence table was removed.  I found reference to changing the GenerationType to GenerationType.TABLE to GenerationType.AUTO.  The main issue was that this wouldn't work anymore with Liquibase unless I updated my old change logs to add autoincrement=true.  

Another potential document issue is what to do if I can't re-run my migrations.  Would it be seamless then?  

In general, this issue should raise light that we have nowhere to easily contribute to nuances we experience, not saying I'd use it, but the repository is getting popular enough to warrant?

**Comment by brenthale** [comment]
What about opening up the 'wiki' feature of github?

I find it difficult to participate on Stackoverflow.  I just found that I wanted to add a question in a Comment (not an 'Answer') to a question I have but...(hanging my head in shame) I don't have enough reputation points to be able to make a comment.   That leads me to be a bad citizen and create an Answer that really isn't an Answer.

The github wiki would be a natural place for us to help one another as we learn this great tool you've put together.   Please open it up?

**Comment by jancel** [comment]
Wiki would definitely add contributors and contributions to value of
Jhioster. I think the community here is large enough too.

+1 for Wiki!

On Wednesday, April 1, 2015, Brent Hale <notifications@github.com> wrote:

> What about opening up the 'wiki' feature of github?
>
> I find it difficult to participate on Stackoverflow. I just found that I
> wanted to add a question in a Comment (not an 'Answer') to a question I
> have but...(hanging my head in shame) I don't have enough reputation points
> to be able to make a comment. That leads me to be a bad citizen and create
> an Answer that really isn't an Answer.
>
> The github wiki would be a natural place for us to help one another as we
> learn this great tool you've put together. Please open it up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/824#issuecomment-88652471>
> .
>


-- 
Jeff Ancel

(314) 703-8829 - Main

www.jeffancel.com

**Comment by brenthale** [comment]
Yup...I was a bad Stackoverflow citizen and they deleted my question as an answer.  This was the post in question:  http://stackoverflow.com/questions/27879373/in-jhipster-how-to-create-entity-with-relationship-with-user

The further question that still needs clarification was this:

I've been able to create the entity I need using the directions from stoffer above. However, how do you get the user_id to put into the object before you save it down?

I can think of two possible ways:

Stuff it in on the client side.
Stuff it in on the server side and somehow use Spring Security to get the current user_id.
but I don't know where to get the user_id from either side.

What is the best practice in this case?

---------------------

Would make a great Wiki entry :)

**Comment by jancel** [comment]
Simply put, never store or rely on passed user ids if you are expecting
that user to represent the action at hand. The way I do it, in the service
or web rest action, I use
userRepository.findByLogin(SecurityUtils.getCurrentLogin()). If I was doing
this often I would add a getCurrentUser in SecurityUtils, but I'm not so I
don't.

On Thursday, April 2, 2015, Brent Hale <notifications@github.com> wrote:

> Yup...I was a bad Stackoverflow citizen and they deleted my question as an
> answer. This was the post in question:
> http://stackoverflow.com/questions/27879373/in-jhipster-how-to-create-entity-with-relationship-with-user
>
> The further question that still needs clarification was this:
>
> I've been able to create the entity I need using the directions from
> stoffer above. However, how do you get the user_id to put into the object
> before you save it down?
>
> I can think of two possible ways:
>
> Stuff it in on the client side.
> Stuff it in on the server side and somehow use Spring Security to get the
> current user_id.
> but I don't know where to get the user_id from either side.
>
> What is the best practice in this case?
> ------------------------------
>
> Would make a great Wiki entry :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/824#issuecomment-88938856>
> .
>


-- 
Jeff Ancel

(314) 703-8829 - Main

www.jeffancel.com
