### ISSUE TITLE
Jest Configuration does not read env var from docker compose file

### ISSUE THREAD

**Issue by adpi2** [jhipster/generator-jhipster#8246]
##### **Overview of the issue**

Starting the app in a docker container does not work because it cannot connect to elasticsearch container.

##### **Motivation for or Use Case**

The environment variable SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES is ignored by Spring Data Jest Configuration.

##### **Reproduce the error**

./gradlew clean bootWar -Pprod buildDocker
docker-compose -f src/main/docker/app.yml up -d

##### **Suggest a Fix**

EDIT : replace SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES with SPRING_DATA_JEST_URI in src/main/docker/app.yml

##### **JHipster Version(s)**

5.3.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    ...
    "jhipsterVersion": "5.3.0",
    "applicationType": "monolith",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "clientPackageManager": "yarn",
    ...
  }
}

##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.11.0

node: v8.11.3

npm: 6.2.0

yeoman: 2.0.3

yarn: 1.9.4

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.8.0, build unknown

##### **Browsers and Operating System**

Debian Stretch

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
You have to use SPRING_DATA_JEST_URI with 5.3.0+.

Documented in https://www.jhipster.tech/using-elasticsearch/.

**Comment by pascalgrimaud** [comment]
Indeed, our code is wrong:
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/docker/app.yml.ejs#L89

Your suggestion seems good. 
@DineMartine : would you like to contribute and do a PR for the fix ?
