### ISSUE TITLE
Spring Data Jest - LocalDateTime mapping error

### ISSUE THREAD

**Issue by ndywicki** [jhipster/generator-jhipster#8249]
Hello,

With the new Spring Data Jest client for ES the default mapper can't serialize/deserialize entity with an ZoneLocaleDateTime attribut (issue in `DefaultJestResultsMapper` see full [stack.txt](https://github.com/jhipster/generator-jhipster/files/2361077/jhipster-jest-localdatetime-stack.txt)

Note: 
On our project we use ES advanced features like snapshot repository management, query on multi-type documents, scan&scroll, etc.
So after a cumbersome migration from ES v2.4.x to v5.5.x a new hard blow with this change for Spring Data Jest ;-)
I know this is not mandatory but migration is done :p

##### **Motivation for or Use Case**

Use ES with all type attributs entity

##### **Reproduce the error**

1. Generate v5.3.1 monolithic app with default options and search engine selected. 
2. Create entity with ZoneLocalDateTime field.
3. Run the app then create / search entity.

##### **Related issues**

N/A

##### **Suggest a Fix**

1. Restore the old `ElasticsearchConfiguration` and customize the entityMapper of the 
 `DefaultJestResultsMapper` to force Jackson instead of Gson :

```
@Bean
@Primary
public ElasticsearchOperations elasticsearchTemplate(final JestClient jestClient,
                                                     final ElasticsearchConverter elasticsearchConverter,
                                                     final SimpleElasticsearchMappingContext simpleElasticsearchMappingContext,
                                                     Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder) {
    return new JestElasticsearchTemplate(
        jestClient,
        elasticsearchConverter,
        new DefaultJestResultsMapper(simpleElasticsearchMappingContext, new CustomEntityMapper(jackson2ObjectMapperBuilder.createXmlMapper(false).build())));
}
```

Full code here : [ElasticsearchConfiguration.txt](https://github.com/jhipster/generator-jhipster/files/2361067/ElasticsearchConfiguration.txt)

2. Add ES annotation `@Field(type = FieldType.Date)`  on the attribut, exemple :
    
```
@Column( = "publication_date")
@Field(type = FieldType.Date)
private ZonedDateTime publicationDate;
```

Note: No need to add the Spring Boot parameter `jackson.serialization.write-dates-as-timestamps: false`

Thanks.

##### **JHipster Version(s)**

V5.3.1

##### **JHipster Version(s)**

```
jhipster@0.0.0 C:\workspace\jhipster\version\v5.3.1\mono\jest-app
`-- generator-jhipster@5.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Book {
  publicationDate ZonedDateTime
}
dto Book with mapstruct
paginate Book with pagination
service Book with serviceClass
search Book with elasticsearch

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.9.3.windows.1

node: v8.11.4

npm: 5.7.1

yeoman: 1.8.5

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Idem for Instant, but worse: the workaround does not seem to work

**Comment by ndywicki** [comment]
Strange I've add an Instant field and it's work. 

@Tcharl, what is your error ?


Book.json:
````
...
"fields": [
        {
            "fieldName": "publicationDate",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "chrono",
            "fieldType": "Instant"
        }
    ]
...
````

Book.java:
```
    @Column(name = "publication_date")
    private ZonedDateTime publicationDate;

    @Column(name = "chrono")
    private Instant chrono;
```

Note: Add `@Field(type = FieldType.Date)` is unnecessary the ES type mapping is a "date"
````
  "book": {
    "mappings": {
      "book": {
        "properties": {
          "chrono": {
            "type": "date"
          },
          "id": {
            "type": "long"
          },
          "publicationDate": {
            "type": "date"
          }
        }
      }
    }
  }
````

Sample:
```
"hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "book",
        "_type": "book",
        "_id": "2551",
        "_score": 1,
        "_source": {
          "id": 2551,
          "publicationDate": "2018-09-09T08:53:00Z",
          "chrono": "2018-09-09T08:53:00Z"
        }
      }
```

Note:
1. I've notice that the docker sub-generator is not updated with the new spring data jest uri env param :
`SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipster-elasticsearch:9300`
Should be :
`SPRING_DATA_JEST_URI=http://jhipster-elasticsearch:9200`
2. The default `elasticsearch.yml` docker compose cause high memory usage since 5.x, I add ES_JAVA_OPTS to limit :
```
    jhipster-elasticsearch:
        image: elasticsearch:5.6.5
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xms512m"
```

Thanks

**Comment by ndywicki** [comment]
@pascalgrimaud, done I've push 2 PR.
For mapping PR #8263 I've make an manual entity test with Instant, LocalDate and ZonedDateTime fields.

**Comment by ndywicki** [comment]
Ideally, one would have to re-switch the ressource integration tests to use the real repository search instead of the mock since Spring Data Jest include the embdded Elasticsearch server (internalNode)
