### ISSUE TITLE
Upgrade Liquibase to 3.6.2 to fix problem in Turkish Locale

### ISSUE THREAD

**Issue by sonersivri** [jhipster/generator-jhipster#8253]
##### **Overview of the issue**

liquibase not working well in Turkish Locale

##### **Motivation for or Use Case**

Liquibase 3.5.5 version sql generation code has toUpperCase() this fixed 3.6.2 version

##### **Reproduce the error**

if locale is tr_TR this occurs

##### **Related issues**

No related issue

##### **Suggest a Fix**

liquibase version 3.6.2 fix the problem

##### **JHipster Version(s)**

5.3.1

##### **JHipster configuration**

No need 

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No need 

##### **Browsers and Operating System**
Windows 10 Turkish

**Comment by gmarziou** [comment]
Looks like #753

**Comment by jdubois** [comment]
Yes, but I know that there are high chances we forget about it :-)
Also, those libraries are tested by Spring Boot, so upgrading them could cause other side-effects, and that means some testing for us.

@sonersivri :
- are you doing something specific, or do you think many other people are affected?
- I'm guessing you're the best person to test, can you do the Liquibase version upgrade on your pom.xml and tell us if that solves the issue for you?

**Comment by sonersivri** [comment]
@jdubois :
Turkish locale users affected this
I upgraded and tested it is ok for me after that I opened the issue 
I understand your hesitations about affecting other people for upgrading liquibase version. I solved my problem with changing new version of liquibase

**Comment by jdubois** [comment]
Thanks @sonersivri !
Just out of curiosity, do you know what causes this? Is this specific to Turkish locale?

Then yes we should do the upgrade in JHipster Core.

**Comment by sonersivri** [comment]
@jdubois yes specific to Turkish
latter i uppercase in Turkish is İ not I

**Comment by jdubois** [comment]
Oh that's a very interesting bug, then!

**Comment by sonersivri** [comment]
Yes, Generation tools developed any languages must use locale English avoid the uppercase or lowercase problems.

**Comment by deepu105** [comment]
IMO we will be updating to Spring boot 2.1 very soon (ping @DanielFran) and since this affects only a subset of users lets document it here, for now, is that ok with you @sonersivri in that case we can close this and wait for the upgrade mostly by next month

**Comment by jdubois** [comment]
Indeed, I didn't realize Spring Boot 2.1 was so close - let's not add more work, at the moment we have too many opened tickets (I've been working every evening this week, and now during the week-end...). This is a very important issue (and also a very interesting one), but it's going to be solved automatically very soon, so no need to worry.
