### ISSUE TITLE
currentpassword and currentpassword.placeholder properties do not exist in Turkish global.json.ejs file

### ISSUE THREAD

**Issue by sonersivri** [jhipster/generator-jhipster#8254]
##### **Overview of the issue**

Change Password currentpassword and currentpassword.placeholder do not exist in global.json.ejs file

##### **Motivation for or Use Case**

turkish language usage

##### **Reproduce the error**

using Turkish

##### **Related issues**

no issue

##### **Suggest a Fix**
adding currentpassword and currentpassword.placeholde properties to
https://github.com/jhipster/generator-jhipster/blob/master/generators/languages/templates/src/main/webapp/i18n/tr/global.json.ejs
file

##### **JHipster Version(s)**
5.3.1

**Comment by deepu105** [comment]
@sonersivri please make a PR when you are ready

**Comment by sonersivri** [comment]
> @sonersivri please make a PR when you are ready

@deepu105 I am not a contributer how can I make a PR
I follow the CONTRIBUTING.md

**Comment by jdubois** [comment]
@sonersivri you need to do a fork of the project, on your own GitHub account (click on the fork button on the top right). Then you'll be able to do a PR.

**Comment by deepu105** [comment]
via
