### ISSUE TITLE
Useless backend configuration

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#8267]
##### **Overview of the issue**

I just migrated a module to the latest and greatest JHipster and noticed this class:

https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/DateTimeFormatConfiguration.java.ejs

I tried to remove it, and tested fields with dates: everything looks working without it.

Is it always useful?

##### **Motivation for or Use Case**

Less code is better code

##### **Reproduce the error**

Delete this class and test forms: it's always working well ;-)

##### **Suggest a Fix**

Remove it?
##### **JHipster Version(s)**

5.3.1

##### **Browsers and Operating System**

MacOsx

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Apparently, it's used in audit resource filters (fromdate and todate) :-).
Any other way to specify filters or is it truly mandatory?

**Comment by cbornet** [comment]
Yes it's needed or else you have to annotate the parameters with `@DateTimeFormat` . See https://github.com/jhipster/generator-jhipster/pull/4433#issuecomment-258697743

**Comment by cbornet** [comment]
We should probably add some comments in the generated code about that
