### ISSUE TITLE
A minor issue with the key-alias in the SSL config and the keytool command

### ISSUE THREAD

**Issue by yatendragoel** [jhipster/generator-jhipster#8268]
##### **Overview of the issue**

For enabling HTTPS support, the `keytool` command in the generated comments in `application.yml`, `application-dev.yml` and `application-prod.yml` has a minor issue that the `key-alias` is Camel-case while it is always recorded in the generated certificate in the lowercase. Because of this mismatch, HTTPS doesn't work without giving any hint related to the error.

Even though it is a very minor issue, but a very easy one to slip by while development causing hours to debug.

    # ===================================================================
    # To enable SSL, generate a certificate using:
    # keytool -genkey -alias CalorieCounterBackend -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
    #
    # You can also use Let's Encrypt:
    # https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
    #
    # Then, modify the server.ssl properties so your "server" configuration looks like:
    #
    # server:
    #    port: 8443
    #    ssl:
    #        key-store: keystore.p12
    #        key-store-password: <your-password>
    #        key-store-type: PKCS12
    #        key-alias: CalorieCounterBackend
    # ===================================================================

##### **Suggest a Fix**

1. Making the `key-alias` lowercase wherever it is mentioned such as properties file, documentation etc.
2. Make an additional comment that the `key-alias` is always in lowercase in the generated certificate so make sure it is in lowercase in the config files as well

##### **JHipster Version(s)**

Using JHipster version installed globally
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
calorie-counter-backend@0.0.0 E:\workspace\sts_workspace\CalorieCounterBackend
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.3",
    "baseName": "CalorieCounterBackend",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) Client VM (build 25.172-b11, mixed mode, sharing)

git version 2.12.2.windows.2

node: v8.11.4

npm: 6.4.0

yarn: 1.3.2

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

- [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Let's put it in lower case everywhere -> @yatendragoel can you the PR?

**Comment by yatendragoel** [comment]
Yes, I will do the PR.

**Comment by ruddell** [comment]
This was fixed in https://github.com/jhipster/generator-jhipster/pull/7548 (v5 beta+), thank you for reporting this though.  Your issue was very clear. 👍

**Comment by yatendragoel** [comment]
@ruddell Thanks for fixing it super quickly in the previous issue and providing the link here!!
