### ISSUE TITLE
JHipster CLI tool unusable in Windows Cygwin environment due to input problems

### ISSUE THREAD

**Issue by Abdull** [jhipster/generator-jhipster#8270]
##### **Overview of the issue**
In a Cygwin environment, JHipster's CLI dialog's cursor operations (selecting an item by pressing up or down on the keyboard) don't work. Therefore, JHipster's CLI generator cannot be used in Cygwin environments.

A workaround is using Windows' Command Prompt (cmd.exe) for running jhipster-cli.

##### **Motivation for or Use Case**
Cygwin is a popular shell environment for Windows-based systems.

##### **Reproduce the error**
* Install Cygwin.
* Start Cygwin.
* Within Cygwin, install generator-jhipster.
* Start the generator with command `jhipster`.
* The dialog will ask `? Which *type* of application would you like to create? (Use arrow keys)`. Using the arrow keys moves a blinking "caret navigation" pipe text cursor (`|`) around the shell, but it does not move the `>` selection cursor.

##### **Related issues**
I haven't found a similar reported issue.

##### **Suggest a Fix**
No idea.

##### **JHipster Version(s)**
```
$ jhipster --version
Using JHipster version installed globally
5.3.1
```
I think this issue has existed for quite some time (all time?), as I noticed it two years+ ago.

##### **JHipster configuration**
As the generation cannot start due to this cursor input issue, no `.yo-rc.json` file is generated.

```
$ jhipster info
Using JHipster version installed globally
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

...

cat: no such file or directory: .yo-rc.json
```

##### **Environment and Tools**

```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding="UTF-8"

git version 2.17.0
node: v8.11.4
npm: 5.6.0
yeoman: 1.8.5
yarn: 1.10.0
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not generated.

##### **Browsers and Operating System**
* Windows 7
* Cygwin: 
```
$ uname -a
CYGWIN_NT-6.1 XXXXX 2.10.0(0.325/5/3) 2018-02-02 15:16 x86_64 Cygwin
```

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Consider upgrading to Windows 10 and use WSL for a real shell :)

**Comment by deepu105** [comment]
During my windows days, I stayed away from cygwin due to such compatibility
issues with nodeJs. I was using powershell, cmder and git bash.

Unfortunately there is nothing we can do here
