### ISSUE TITLE
Getting errors while generating client side project

### ISSUE THREAD

**Issue by redo99** [jhipster/generator-jhipster#8271]
##### **Overview of the issue**

I have tose 2 errors 
ERROR in /Users/Redo/Work/Workspace/celexio/CRM/cxocrm-web/src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts(6,14):
TS2420: Class 'AuthExpiredInterceptor' incorrectly implements interface 'HttpInterceptor'.
  Property 'intercept' is missing in type 'AuthExpiredInterceptor'.

ERROR in /Users/Redo/Work/Workspace/celexio/CRM/cxocrm-web/src/main/webapp/app/core/login/login.service.ts(11,37):
TS2304: Cannot find name 'AuthServerProvider'.

when executing the following command
npm start

in a client side project generated by the command below
jhipster --skip-server --db PostgreSQL --auth JWT

##### **Motivation for or Use Case**
create a client side project

##### **Reproduce the error**
run those commands
mkdir cxocrm-web
cd cxocrm-web
jhipster --skip-server --db PostgreSQL --auth JWT
? What is the base name of your application? cxocrmweb
? Which *Framework* would you like to use for the client? Angular 6
? Would you like to enable *SASS* stylesheet preprocessor? Yes
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install Arabic (Libya), French, Spanish
? Besides JUnit and Jest, which testing frameworks would you like to use? 
? Would you like to install other generators from the JHipster Marketplace? No
npm start 

##### **Suggest a Fix**
No suggestion

##### **JHipster Version(s)**
v5.3.0

##### **JHipster Version(s)**

```
cxocrmweb@0.0.0 /Users/Redo/Work/Workspace/celexio/CRM/cxocrm-web
└── generator-jhipster@5.3.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "monolith",
    "baseName": "cxocrmweb",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "authenticationType": "JWT",
    "cacheProvider": "no",
    "databaseType": "PostgreSQL",
    "devDatabaseType": "PostgreSQL",
    "prodDatabaseType": "PostgreSQL",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly",
      "fr",
      "es"
    ],
    "skipServer": true
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.13.1

node: v8.11.2

npm: 6.4.1

yeoman: 2.0.2

yarn: 1.9.4

##### **Browsers and Operating System**
macos
chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by chrisdns** [comment]
Try 
` jhipster --skip-server --db PostgreSQL --auth jwt` 
instead of 
` jhipster --skip-server --db PostgreSQL --auth JWT`

**Comment by redo99** [comment]
Thnx a lot. The problem is solved.
