### ISSUE TITLE
Jhipster Microservice application not serving APIs

### ISSUE THREAD

**Issue by tpulimoottil** [jhipster/generator-jhipster#8272]
##### **Overview of the issue**

Jhipster microservice application generated without service registry is not serving APIs. No errors are thrown in the console as well. When trying to access localhost:8081 it fails to connect.

##### **Motivation for or Use Case**

I just generated a microservice application with jhipster previous versions of jhipster and it always use serve APIs and this version doesn't seem to work in that manner.

##### **Reproduce the error**

I have provided the following options while generating jhipster application.
? Which *type* of application would you like to create? Microservice application
? What is the base name of your application? 4
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid 
port conflicts. 8081
? What is your default Java package name? com.mycompany.myapp
? Which service discovery server do you want to use? No service discovery
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? Which *production* database would you like to use? MySQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Do you want to use the Spring cache abstraction? Yes, with the Hazelcast implementation (distributed cache, for multiple node
s)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? Search engine using Elasticsearch
? Would you like to enable internationalization support? No
? Besides JUnit and Jest, which testing frameworks would you like to use? 
? Would you like to install other generators from the JHipster Marketplace? No

##### **Related issues**

I am not sure whether there was an issue. I was only able to find the following stackoverflow issue raised by an another user, which looked similar.
https://stackoverflow.com/questions/51615881/jhipster-5-microservice-not-starting-properly

##### **JHipster Version(s)**

It use to work fine in 4.14.4 version which i was using before.
This looks like a regression.

##### **JHipster Version(s)**

```
4@0.0.0 /path/to/project
└── generator-jhipster@5.3.1 U

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "microservice",
    "baseName": "4",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.16.0

node: v9.3.0

npm: 6.4.1

yeoman: 2.0.0

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

This was just a blank project created. No entities was created

##### **Browsers and Operating System**

Mac OS, Google Chrome 68

**Comment by gmarziou** [comment]
This is a breaking change of JHipster 5.0 that was introduced to support Istio.
When you generate a microservice without service discovery, a context path is configured in application*.yml, feel free to changeit.

**Comment by PierreBesson** [comment]
The context path was setup like that for a good reason. And it was part of a major release. If you think this is insuficiently documented, you can do a PR to the docs. There is a task to print the context path in the logs which is still in todo but I will try to do it tomorrow). I'm sorry that you lost time because of this, but the team doesn't have the time and resources to test  every option combination and upgrade paths.
