### ISSUE TITLE
Deprecation notice about yeoman when using CLI

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#8290]
##### **Overview of the issue**
Deprecation notices for when a user runs `yo jhipster` display all the time 
@deepu105 pinging you since you added these in https://github.com/jhipster/generator-jhipster/commit/1ef8cdec91deed509e38898948b21b5524fa5e79

##### **Motivation for or Use Case**
It's confusing, messages shouldn't be displayed when they don't apply

##### **Reproduce the error**
Run `jhipster` and answer the prompts, deprecation notices displayed constantly.  Also happens when running `jhipster` with an existing `.yo-rc.json`

New:
```
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? asdfasdfasdfa
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
? What is your default Java package name? com.mycompany.myapp
? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? Which *production* database would you like to use? MySQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Do you want to use the Spring cache abstraction? Yes, with the Ehcache implementation (local cache, for a single node)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? 
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
? Which *Framework* would you like to use for the client? Angular 6
? Would you like to enable *SASS* stylesheet preprocessor? Yes
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install 
? Besides JUnit and Jest, which testing frameworks would you like to use? 
? Would you like to install other generators from the JHipster Marketplace? No
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
```
Regenerating:
```
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...

WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
```

##### **Related issues**
Added in https://github.com/jhipster/generator-jhipster/commit/1ef8cdec91deed509e38898948b21b5524fa5e79

##### **Suggest a Fix**
Haven't looked into it

##### **JHipster Version(s)**
Master

##### **JHipster configuration**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "monolith",
    "baseName": "asdfasdfasdfa",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I guess it happens during composition and the flag is not passed properly.
I'll fix it

**Comment by deepu105** [comment]
@ruddell hope its alright now

**Comment by ruddell** [comment]
Looks good to me
