### ISSUE TITLE
Relationship to entity User raises Warning that doesn't apply

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#8293]
##### **Overview of the issue**
When adding a relationship from an entity to the User entity and selecting any available relationship option, the generator raises the following warning:

`WARNING! This entity has the DTO option, and it has a relationship with entity "user" that doesn't have the DTO option. This will result in an error.`

It shouldn't as User has DTO generated by using `dto * with mapstruct` and `service * with serviceImpl`

##### **Motivation for or Use Case**
As there is in fact a DTO configuration, the warning should no be shown.

##### **Reproduce the error**

Create a relationship between an entity and the `User` entity

##### **Suggest a Fix**
I'm not sure as the user entity has no json in the `.jhipster` directory. Maybe check directly the jdl file for the `dto * with mapstruct` configuration.

##### **JHipster Version(s)**

```
test@0.0.0 /Users/alejandro/IdeaProjects/test
└── generator-jhipster@5.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.tester.testering",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "monolith",
    "baseName": "test",
    "packageName": "com.tester.testering",
    "packageFolder": "com/tester/testering",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity TestEntity {
  avatar ImageBlob
}
dto TestEntity with mapstruct
service TestEntity with serviceImpl

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.16.2

node: v8.11.3

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
One solution is to not print the warning when the `otherEntityName` equals `'user'` [where this is printed in the entity generator](https://github.com/jhipster/generator-jhipster/blob/a97cb525545aedf50a05fa9aa070ab72e4596c0e/generators/entity/index.js#L687-L689)

**Comment by MathieuAA** [comment]
I'll have a look at it and fix it today, thanks for reporting!

**Comment by MathieuAA** [comment]
Awesome :)Le 12 sept. 2018 07:21, Pascal Grimaud <notifications@github.com> a écrit :@MathieuAA : there is already a PR to fix it

**Comment by amatosg** [comment]
it's waiting for approval :)

**Comment by jdubois** [comment]
I totally understand the use case, but I'm very surprised this works without doing anything! And I probably coded a big part of this... @amatosg did you test this? I just can't believe this works so easily
