### ISSUE TITLE
Missing classes when generating ApiGateway with No Service Discovery Option

### ISSUE THREAD

**Issue by michaelstievenart** [jhipster/generator-jhipster#8297]
When selecting 'No service discovery' for option 'Which service discovery server do you want to use?' there are missing classes needed for test classes that are generated.
Test Classes generated with errors:

1. CookieTokenExtractorTest is missing CookieTokenExtractor.java

2. OAuth2AuthenticationServiceTest  is missing:
 - OAuth2AuthenticationService
 - OAuth2TokenEndpointClient
 - RefreshTokenFilter
 - OAuth2CookieHelper
 - UaaTokenEndpointClient
 - CookieCollection

3. OAuth2CookieHelperTest is missing OAuth2CookieHelper

##### **JHipster Version(s)**

JHipster 5.3.1

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "gateway",
    "baseName": "ApiGateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>
##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.7.4

node: v8.11.4

npm: 5.6.0

yarn: 1.3.2

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**
Ubuntu 16.04

**Comment by jdubois** [comment]
Thanks! In fact, I'm surprised we have that option - having a gateway without a service discovery doesn't make much sense to me. Out of curiosity, why do you need this?

If there's no real use case, we might as well remove the option, that's why I need some feedback on why people need this.

**Comment by michaelstievenart** [comment]
On second thoughts, I originally thought this approach would be quicker but it isn't, as there are a number of key classes and dependencies that seemed to be tied to service discovery question option, especially the classes that setup authentication.

Why is it that a lot of the authentication classes are only generated as part of the service discovery selection. I thought this would be tied to the questions that ask about Authentication mechanism?

So to clarify your previous statement 'If there's no real use case, we might as well remove the option, that's why I need some feedback on why people need this.' - as it stands I wouldn't have a need for this as there is considerable effort necessary (in comparison to stripping out consul or eureka) in order to even create a simple microservice setup such as: gateway, uaa (Authentication server), standalone microservice.

**Comment by ruddell** [comment]
@jdubois Related Istio issue regarding gateways + no service discovery https://github.com/jhipster/generator-jhipster/issues/7337, I think that's why it is possible

**Comment by PierreBesson** [comment]
Yes this is a valid use case because of Istio. So it should be fixed and we should add a daily build to hipster-labs for it.
