### ISSUE TITLE
Launch prettier with npx, not npm

### ISSUE THREAD

**Issue by ecostanzi** [jhipster/generator-jhipster#8299]
##### **Overview of the issue**

According to the Get Started section of [prettier home page](https://prettier.io/), the command should be 

`npx prettier --write 'src/**/*.{ts,tsx,css,scss}`
not 
`npm prettier --write 'src/**/*.{ts,tsx,css,scss}`

##### **Motivation for or Use Case**
In the package.json:

```
  "scripts": {
    "precommit": "lint-staged",
    "prettier:format": "npm prettier --write 'src/**/*.{ts,tsx,css,scss}'",
    "lint": "tslint --project tsconfig.json -e 'node_modules/**'",
```
running `npm run prettier:format` does not trigger prettier.

##### **Reproduce the error**

- generate a workspace using npm as package manager
- run `npm run prettier:format` --> see the error
- run `npm prettier --write 'src/**/*.{ts,tsx,css,scss}'` --> see the error

##### **Suggest a Fix**

Change the command
`npx prettier --write \"src/**/*.{ts,tsx,css,scss}\""`

I had to use double quotes instead of single quotes, otherwise when launching `npm run prettier:format` file scan fails.

##### **JHipster Version(s)**

5.3.1

##### **JHipster configuration**
```
react-issuetracker@0.0.0 C:\Users\ecostanzi\dev\learn\jhipster\jhipster5-lab-react
`-- generator-jhipster@5.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "it.intesys.lab",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "monolith",
    "baseName": "react_issuetracker",
    "packageName": "it.intesys.lab",
    "packageFolder": "it/intesys/lab",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "it"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Project {
  key String minlength(3) maxlength(5) required,
  name String minlength(3) maxlength(20) required,
  description String maxlength(2048) required
}
entity Issue {
  title String minlength(3) maxlength(50) required,
  description TextBlob required,
  issueType IssueType required
}
entity Comment {
  message TextBlob maxbytes(2048) required
}
entity Tag {
  name String required maxlength(20)
}
entity Attachment {
  attachmentFile AnyBlob required
}
entity ProjectMember
entity ProjectRole {
  name String required
}

enum IssueType {
  BUG,
  FEATURE,
  TASK
}

relationship OneToMany {
  Project{issue} to Issue{project(key)},
  Issue{comment} to Comment{issue},
  Issue{attachment} to Attachment{issue},
  Project{required} to ProjectMember{project(key)},
  ProjectRole{required} to ProjectMember{projectRole(name)}
}
relationship ManyToOne {
  Comment{user(email)} to User,
  ProjectMember{user(email)} to User
}
relationship ManyToMany {
  Project{tag(name)} to Tag,
  Issue{tag(name)} to Tag
}

dto Project, Issue, Comment, Tag, Attachment, ProjectMember, ProjectRole with mapstruct
paginate Project, Comment with pagination
service Project, Issue, Comment, Tag, Attachment, ProjectMember, ProjectRole with serviceClass
filter Project, Issue, Comment, Tag, Attachment, ProjectMember, ProjectRole
paginate Issue with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

git version 2.12.2.windows.2

node: v8.11.3

npm: 5.6.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

##### **Browsers and Operating System**

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Why not simply "prettier" instead of "npx prettier" ? As you are inside a npm script it should work.

**Comment by ecostanzi** [comment]
@PierreBesson seems you're right, I removed the new variable and kept the double quotes

**Comment by cbornet** [comment]
Can be closed ?

**Comment by deepu105** [comment]
Also npx is to have temp installation, its not nice inside an npm script. I believe we generate the proper setup.
