### ISSUE TITLE
React: "Create a new user" dialog incorrectly prefills properties with data from a previously edited or detailed user

### ISSUE THREAD

**Issue by Abdull** [jhipster/generator-jhipster#8302]
##### **Overview of the issue**

In the React frontend, under *User Management*, when clicking *Create a new user*, the dialog incorrectly prepopulates user property fields with data from the previously edited or previously in-detail-shown user - making creation of a new user impossible.

A workaround is to go back again (which causes `UserManagementUpdate` to dispatch a `RESET` action on `componentWillUnmount()`), then clicking  *Create a new user* again.

##### **Motivation for or Use Case**

Creating a user should always work.

##### **Reproduce the error**

* Visit vanilla React-based JHipster frontend. Log in as `admin`. Click *Administration* -> *User Management*.
* Either *view* details of an existing user, then click *Back* ... or *edit* an existing user and click *Save*.
* Now being back in the User management interface, click *Create a new user*.
* The *Create or edit a user* dialog is shown and the route is `/admin/user-management/new`. But data is prefilled with data from the previous user, making creation of a new user impossible - as also the ID property is prepopulated - which isn't allowed for new users.

##### **Related issues**
No.

##### **Suggest a Fix**
The problem is that the user edit dialog and user creation dialog both use the `UserManagementUpdate` component. This component uses the Redux state `{user} : UserManagementState`. This state is also handled by  `UserManagementDetail`.

##### **JHipster Version(s)**
generator-jhipster@5.3.1. I don't know if this is a regression.

##### **JHipster configuration**
```
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "monolith",
    "baseName": "tagadata",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "xxx",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ]
  }
}
</pre>
</details>
```

##### **Browsers and Operating System**
Windows 7. Problem occurs at least in Chrome and Firefox, but problem is related to generated React codebase.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
would you be willing to make a PR? the solution would be to always fire a reset during create in the mount step

**Comment by deepu105** [comment]
submitted https://opencollective.com/generator-jhipster/expenses/5295 for this
