### ISSUE TITLE
Getting "Can't resolve" Error on creating UI for entities of microservice in the gateway

### ISSUE THREAD

**Issue by NasrinD** [jhipster/generator-jhipster#8319]
##### **Overview of the issue**
I am trying to generate the front-end for my microservice application. But when I try to create the UI for my entities (which I have already created in my microservice application), I get the following errors:

![image](https://user-images.githubusercontent.com/13658426/45521648-332ca300-b7bf-11e8-9d70-b2f1854b4cd5.png)

![image](https://user-images.githubusercontent.com/13658426/45521599-f8c30600-b7be-11e8-9f95-2381f2b35cbd.png)

##### **Motivation for or Use Case**
I'm not sure, if I am doing something wrong or if this is an issue. 
And I don't know, if there is any other way for producing the UI from the created microservice entities instead of creating them one by one using the `jhipster entity` command.

##### **Reproduce the error**
I do the following steps:
1. Creating a folder **tradingsystem-es** and three other folders there: **cash-desk-service**, **registry** & **store-gateway**.
2. In the **registry** folder: clone registry with: 
`git clone https://github.com/jhipster/jhipster-registry registry`
3. In the **cash-desk-service** folder create the microservice application using ".yo-rc.json" file and running:
`yo jhipster`
4. In the **cash-desk-service** folder create the entities using "cash-desk-jdl.jh" file and running:
`jhipster import-jdl C:\Users\nasrin\Desktop\cash-desk-jdl.jh`
5. In the **store-gateway** folder create the gateway application using ".yo-rc.json" file and running: 
`yo jhipster`
6. Trying to generate the UI in the gateway for each entity. For example for the Printer entity by running the following command in the **store-gateway** folder:
`jhipster entity Printer`
7. Answering these questions:
    - Do you want to generate this entity from an existing microservice? Yes
    - Enter the path to the microservice root directory: ../cash-desk-service
    - Do you want to update the entity? This will replace the existing files for this entity, all your custom code will be overwritten. Yes, re generate the entity
(all overwrite)
8. Then JHipster starts generating the entity. But after a while I get the errors.

##### **JHipster Version(s)**
I use JHipster v4.14.1.

##### **JHipster configuration**

This is the **.yo-rc.json** file for generating the **microservice**:
```{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jhipster.cashdeskservice",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "cashdesk",
    "packageName": "org.jhipster.cashdeskservice",
    "packageFolder": "org/jhipster/cashdeskservice",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "cd3b8863a83b8695e8ebdc2a5236ffcf06182cc5",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

This is the **.yo-rc.json** file for generating the **gateway**:
```{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jhipster.storegateway",
      "nativeLanguage": "en",
      "microservicePath": "../cash-desk-service"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "store",
    "packageName": "org.jhipster.storegateway",
    "packageFolder": "org/jhipster/storegateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "155b94af00d0bcc2639dc1d2d71442b229d28c67",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

This is the **jh** file for generating the entities in my microservice:
``` //-----------------------------------------
entity Store {
	name String required,
	address String
}
entity CashDesk
entity CashDeskApplication
entity CashDeskGUI
//-----------------------------------------
entity CashBox {
	model String required
}
entity CashBoxController
//-----------------------------------------
entity Printer  {
	model String required
}
entity PrinterController
//-----------------------------------------
entity BarCodeScanner {
	model String required
}
entity BarCodeScannerController
//-----------------------------------------
entity CardReader {
	model String required
}
entity CardReaderController
//-----------------------------------------
enum PaymentMode {
	CASH, CARD
}
entity Receipt {
	date Instant required,
	paymentMode PaymentMode required,
	runningTotal BigDecimal required
}
//Because we need to save the price 
entity ReceiptItem {
	productBarCode Long required,
	productSalesPrice BigDecimal required,
	productName String required
}
//-----------------------------------------
relationship OneToOne {
	Store{cashDesk} to CashDesk{store(name)},
	CashDesk{printer} to Printer{cashDesk},
	CashDesk{cashBox} to CashBox{cashDesk},
	CashDesk{cashDeskGui} to CashDeskGUI{cashDesk},
	CashDesk{barCodeScanner} to BarCodeScanner{cashDesk},
	CashDesk{cardReader} to CardReader{cashDesk},
	CashDesk{cashDeskApplication} to CashDeskApplication{cashDesk}
}
relationship OneToOne {
	Printer{controller} to PrinterController{printer},
	CardReader{controller} to CardReaderController{cardReader},
	BarCodeScanner{controller} to BarCodeScannerController{barCodeScanner},
	CashBox{controller} to CashBoxController{cashBox}
}
relationship OneToMany {
	Receipt{receiptItems} to ReceiptItem{receipt},
	CashBox{receipt} to Receipt{cashBox}
}
```
After using this file, the json files related to each entity will be created in the .jhipster folder of my microservice.

##### **Browsers and Operating System**

I am using Windows 7 and Firefox.

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
This happens because your entities have relations, so just generating the Printer is missing the CashDesk service ts file which is used in the update component.  You should set a `microservice` name in your JDL and import that, it will build successfully (`microservice * with cashdesk`).

[JDL Microservice Docs](https://www.jhipster.tech/jdl/#microserviceoptions)

**Comment by jdubois** [comment]
Closing as @ruddell has answered!
@NasrinD don't hesitate to comment if you still have errors, we'll re-open, of course.
