### ISSUE TITLE
Error while upgrading existing project form v5.0.0 to v5.3.1

### ISSUE THREAD

**Issue by pksharmapokhrel** [jhipster/generator-jhipster#8322]
##### **Overview of the issue**

After upgrading the existing project from jhipster version 5.0.0 to 5.3.1, project does not run due to problem caused in TokenProvider.java file
##### **Cause**

Error occurs due to length of the jwt security code provided in the updated application-dev.yml file which is of 240 bits and does not meet the requirement of HS512 algorithm which requires at least 512bits long key.

##### **How i solved**
Changed the secret key in the application-dev.yml file and .yo-rc.json to a valid BASE64 string of valid length.
##### **JHipster Version(s)**
5.3.1

##### **JHipster configuration**
Monolithic project, angular, mysql, scss for styling and hibernate 2nd level caching

##### **Browsers and Operating System**
Window 10. Using yarn package manager. Google Chrome.

- [✓] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
See the release note: https://www.jhipster.tech/2018/09/03/jhipster-release-5.3.0.html

> Upgrade to JJWT #8145. This will probably affect many JWT users, as the JWT key should now have a minimal length of 512 bits. If your key is smaller, JJWT won’t accept it, and your users won’t be able to log in. Please note that is for your own good: if your key is too short, this is a high security risk. Also, we now have a new “base64-secret” property, where you can store your token in Base64 encoding. This is also much better for security, and we expect this new property to be the only one supported in our next major release. More information on #8165.

**Comment by jdubois** [comment]
Yes, you need a bigger JWT key.

Sorry about that, I know this broke a lot of projects, and now I regret this choice. But it's very good for your project's security, so please understand this is also a way to protect you from attacks.

Also, we didn't have much choice, as this is forced by the new release of JJWT (and let's not keep an old version for something which is vital).
