### ISSUE TITLE
default docker config: gateway application crashes with error (not able to connect elasticsearch)

### ISSUE THREAD

**Issue by standors** [jhipster/generator-jhipster#8326]
##### **Overview of the issue**
in Jhipster 5.3.1 default docker configuration do not work
##### **Motivation for or Use Case**
generated simple config should work
##### **Reproduce the error**
generate new project
1. run Jhipster for microservice : application gateway
(maybe not only microservice problem)
**then start the application from generated  docker configuration in 
gateway/src/main/docker/app.yml**

docker-compose -f src/main/docker/app.yml up -d

gateway application crash with error (not able to connect elasticsearch)
from logs:
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userSearchRepository': Invocation of init method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.NumberKeyedRepository]: Constructor threw exception; nested exception is org.springframework.data.elasticsearch.ElasticsearchException: failed to execute action

....
io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://localhost:9200
...
Caused by: java.net.ConnectException: Connection refused (Connection refused)

but 
from browser http://localhost:9200   responds correctly !!!
##### **JHipster Version(s)**

jhipster 5.3.1

##### **JHipster configuration**

Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
report@0.0.0 /home/ond/prog/training/java/jhipster-demo/reporting-ond-api/gateway
└── generator-jhipster@5.3.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "wr.gw",
      "nativeLanguage": "sk"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "gateway",
    "baseName": "report",
    "packageName": "wr.gw",
    "packageFolder": "wr/gw",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": removed
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "sk",
    "languages": [
      "sk"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

The passed validation must be valid to be added to the field.
Errors: No value
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! 
Error while parsing entities to JDL

##### **Browsers and Operating System**
debian9  linux
firefox 

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@ruddell : would you like to do a PR, as you're the one who suggested the fix
