### ISSUE TITLE
Generate dropdown selection lists for non enum fields and/or support custom enums. 

### ISSUE THREAD

**Issue by Flying-Bison** [jhipster/generator-jhipster#8327]
##### **Overview of the feature request**

Enhance the JDL and generator to allow defining a set of acceptable values for an entity field in the JDL that will generate a dropdown list in the UI with the corresponding values. In addition it should add validation on the server side to ensure only those values are submitted. 

##### **Motivation for or Use Case**

- Entity fields often have a specific set of acceptable inputs that would be best presented to the user as a dropdown select list. Even though validation can be applied in the JDL using the regex feature, it does not provide a friendly user experience to determine which values can be accepted.

- Current Enum support only appears to allow standard enums where their name is stored as the database value. This limits the field value to follow the regex ([A-Z0-9_]). 

- Manually making the changes after the application is generated makes it difficult to manage the Entity layer with Jhipster if any changes need to be made to the entities. Runnng the import-jdl to update the model will require remaking the changes. 

##### **Suggest a Fix**
Update the JDL language to have an additional validation called values() that can accept a list of values. Update the generator to build the UI with these values as a dropdown list and add validation to only allow these values.

Example JDL Entity Definition  
```
entity Account{
	interestRate Double values(0.01,0.02, 0.05)
}
```

Alternative: Support custom enum classes with single types.
This would allow more advanced values to be saved in the database while still working with the current enum UI generation. 

Example JDL Enum change.
```
enum Double INTEREST_RATE {
	ONE_PERCENT(0.01), 
    TWO_PERCENT(0.02), 
    FIVE_PERCENT(0.05)
}
```
I built an extremely simple example in my github repo for code that works with hibernate's attribute converter to convert typed enums while interacting with the database. https://github.com/Flying-Bison/custom-enum-sample

##### **Related issues or PR**

Did not see the same request. However, I am fairly new to github so I may just be bad at searching. 

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
For the dropdown list, don't you think that  i18n option covers your needs?

**Comment by Flying-Bison** [comment]
I was hoping that we could define it from the JDL specifically. However, I am not overly familiar with i18n. I will need to review how i18n could provide this funcitonality or if you had an example that would help as well.

**Comment by Flying-Bison** [comment]
@gmarziou  I am sorry, I do not understand the first part of your response. How can I use i18n to provide a dropdown/select input field for the field of an entity that was defined in my JDL?

In my example above I have a field of type Double named interestRate on the Account entity. Instead of an open numeric input field for interestRate while creating an Account entity, I want to have a select list with 3 available options [0.01, 0.02, 0.05] for the user to select. 

Also, I did not originally consider the impact on multiple language support either. However, the current enum defined select lists do not appear to be translated in a test app I generated either. Furthermore, I believe multiple languages could be supported if you properly implement the select list to only translate the display of the options while leaving the values.

**Comment by gmarziou** [comment]
Well maybe I did not understand your point but with i18n, the text in the select are not the Enum values but their translated values.

An example with an enum Gender with 2 values F and M.

In `src\main\webapp\i18n\en\gender.json`, you can translate 

~~~json
        "Gender" : {
            "null": "",
            "F": "Female",
            "M": "Male"
        }
~~~

The HTML template then displayers the translated values using the `translate` pipe:

~~~html 
               <div class="form-group">
                    <label class="form-control-label" jhiTranslate="enumsApp.player.gender" for="field_gender">Gender</label>
                    <select class="form-control" name="gender" [(ngModel)]="player.gender" id="field_gender" >
                        <option value="F">{{'enumsApp.Gender.F' | translate}}</option>
                        <option value="M">{{'enumsApp.Gender.M' | translate}}</option>
                    </select>
                </div>
~~~

**Comment by deepu105** [comment]
We have too many open items at the moment to have new feature requests and this is a significant one and it's not very difficult for end users to do this themselves. That's why I'm closing this for now.

I don't think we will do the first part of your proposal, but for the enum part I think we can consider if you are willing to PR

**Comment by deepu105** [comment]
let me know if you willing to implement the enum solution, but please note in that case it also has to work with i18n

**Comment by deepu105** [comment]
1. It is conplex to maintain
2. Requires lot of changes to JDL and generator
3. Not a widely used requirement(if you have drop-downs, most likely you fetch its data using Rest and in that case you can model them as relationship, for remaining you have enums)
4. Not very hard to just add it to UI code directly by user

**Comment by deepu105** [comment]
But if you disagree, you are welcome to do a PR with your proposal and if we are convinced that it doesn't add maintenance burden and offers value to end user then we will consider it

**Comment by Flying-Bison** [comment]
Thank you for the feedback, I apologize for continuing this after it was closed. This helps me understand your point of view much better. I don't disagree with your explanation. I may take a look to familiarize myself with the JDL and Generator. However, I do not intend to add unnecessary complexity into your environment.
