### ISSUE TITLE
UAA server not starting just after creation by using JHipster

### ISSUE THREAD

**Issue by gthiabaud** [jhipster/generator-jhipster#8349]
##### **Overview of the issue**

Impossible to start uaa server immediatly just after creating it with JHipster v5.3.1

##### **Motivation for or Use Case**

It is a bug because the issue appear during the compilation phase when I start UAA server the first time after changing nothing.

##### **Reproduce the error**

With JHipster v5.3.1 create a uaa server.
Start it by using .mvnw

##### **Suggest a Fix**

In JacksonConfiguration replace 
import org.zalando.problem.**validation**.ConstraintViolationProblemModule;
by 
import org.zalando.problem.**violations**.ConstraintViolationProblemModule;

##### **JHipster Version(s)**
v5.3.1

##### **JHipster configuration**
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
uaa-2@0.0.0 K:\JHipster\uaa2
`-- generator-jhipster@5.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.gthiabaud.dirnav"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "uaa",
    "baseName": "uaa2",
    "packageName": "com.gthiabaud.dirnav",
    "packageFolder": "com/gthiabaud/dirnav",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.18.0.windows.1

node: v8.11.4

npm: 5.6.0

yeoman: 2.0.2

yarn: 1.5.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**
Windows 10

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm pretty sure this is a duplicate, but I couldn't find the original ticket.

Anyway, this is already fixed on `master`, thanks @gthiabaud !
