### ISSUE TITLE
The example code in the jdl-studio is broken

### ISSUE THREAD

**Issue by alexander-redmann-teaching** [jhipster/generator-jhipster#8360]
##### **Overview of the issue**

The example code in the jdl-studio is broken
https://start.jhipster.tech/jdl-studio/

##### **Reproduce the error**

Copy the code in an jh file and try to import via jhipster import-jdl. The import is aborted with:
The JDL is being parsed.
Error: Selecting DTOs without services is forbidden, for entities Employee, Job.
ERROR! Error while parsing applications and entities from the JDL Error: Selecting DTOs without services is forbidden, for entities Employee, Job.

##### **Suggest a Fix**

Remove  except Employee, Job on service all with _serviceImpl **except Employee, Job**_ or add it on 
dto * with mapstruct to _dto * with mapstruct  **except Employee, Job**_
It is nice to explain this feature with wildcards and excetions but it is very hard to understand for a rookie why the import doesn't work.

##### **JHipster Version(s)**

5.2.0 until 5.3.2

**Comment by jdubois** [comment]
Thanks @alexander-redmann-teaching - I know about this, I thought it was corrected!!

**Comment by PierreBesson** [comment]
Yes the example code is way too complex, I often see newcomers who struggle because they keep the dto and serviceImpl code at the end of the file.

**Comment by jdubois** [comment]
Yes we should definitely make it a lot more simple. No example of complex stuff at all.

**Comment by jdubois** [comment]
I just tested and had no problem at all, this is strange! @alexander-redmann-teaching can you share your JDL? Where did you get it exactly?

**Comment by deepu105** [comment]
I think the sample bis not updated yet, if you are trying it just enable service for all entity as well

**Comment by MathieuAA** [comment]
Gotta come up with a new example...

**Comment by jdubois** [comment]
I have modified the example with last release, it's OK now!
