### ISSUE TITLE
Display Name does not work for OneToMany mappigns in JDL

### ISSUE THREAD

**Issue by alexander-redmann-teaching** [jhipster/generator-jhipster#8361]
##### **Overview of the issue**

If i set a display name in JDL in OneToMany relationship in JDL the generated code does not display  the name but only the id. If you use the example JDL script and want to use the jobTitle and the lastName rather then the id I would expect to see this elements but only the id is present in the resulting code.

```
relationship OneToMany {
	Employee{job(jobTitle)} to Job,
	/**
	* A relationship
	*/
	Department{employee(lastName)} to
	/**
	* Another side of the same relationship
	*/
	Employee
}
```

All other relationships works as expected.

**Comment by ruddell** [comment]
Please fill out the issue template when opening new issues, it helps save us time when reproducing bugs.

In the case of your JDL, the select boxes are on the other side of the relationship than you expect, so set the select field up there as well:
 - the `job-update.component.ts` has the select box for Employees
 - the `employee-update.component.ts` has the select box for Departments

```
entity Job {
    jobTitle String
}
entity Employee{
    firstName String
    lastName String
}
entity Department{
	title String
}

relationship OneToMany {
	Employee{job(jobTitle)} to Job{employee(lastName)},
	Department{employee(lastName)} to Employee{Department(title)}
}
```

As I don't see a bug and this ticket is incomplete, I'm closing this.  Feel free to let me know if I missed something.
