### ISSUE TITLE
Enable unit testing of blueprints

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#8364]
##### **Overview of the feature request**

Allow writing unit tests with yeoman-test when developing blueprints, invoking the main JHipster subgenerator while loading the blueprint subgenerator using .withGenerators(...).

##### **Motivation for or Use Case**

Writing such test in blueprint module currently doesn't work:
```
describe('JHipster server generator with blueprint', () => {
    describe('generate server', () => {
        beforeEach((done) => {
            helpers.run('generator-jhipster/generators/server')
                .withOptions({blueprint: 'generator-jhipster-myblueprint'})
                .withGenerators(
                     [path.join(__dirname, '../generators/server') // <== blueprint generator
                ]) 
                .withPrompts({
                    /* ... */
                })
                .on('end', done);
        });
    });
});
```
You end up with an error:
```
The generator-jhipster-myblueprint blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-myblueprint.
```

##### **Related issues or PR**

None that I know. 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
@deepu105 bounty added :-)

**Comment by deepu105** [comment]
@murdos please dont forget to claim your bounty
