### ISSUE TITLE
React: Creating and editing users is tricky

### ISSUE THREAD

**Issue by Abdull** [jhipster/generator-jhipster#8367]
##### **Overview of the issue**

I noticed several problems with the user creation and editing dialog. One specific problem is already tracked in #8302. Here I want to list further problems. As these problems are quite interrelated, I'm creating a single issue.

**User creation incorrectly creates activated user even when the user is requested to be deactivated**
In the React frontend, under *User Management*, creating an deactivated user (`activated=false`, i.e., no checkmark set in the *Activated* input checkbox) will incorrectly create an activated user.

This is because the Redux `createUser(user)` action will call the REST endpoint `UserResource.createUser(UserDTO)`, which delegates to `UserService.createUser(UserDTO)`, which always sets that JPA `USER` entity's  `activated` field to `true`, irrespective of the provided `UserDTO`'s `activated` value.

**User editing sometimes shows an incorrect activated/deactivated value**
In the React frontend, under *User Management*, when editing an activated user, sometimes the _Activated_ checkmark is incorrectly not set. When clicking _Save_, the user will be updated to have `activated=false`. This is bad when quickly editing and saving a user, because one would expect unedited input fields to have the same value as before the editing process.

**Some input elements do not have validation features, and server-side validation is not handled within the creation/editing dialog, making user creation/editing frustrating**
Only the _Login_ and _Email_ input elements have validation markup. the _Language_ input element does not have validation markup. When creating a user, by default, some language (default language?) is shown as being selected from its drop down menu, but is actually not selected. Clicking on _Save_ without having explicitly selected a language causes the React frontend to go back to the user management overview, showing an interpretation of the server side-generated validation error (`Field translation-not-found[exampleapp.userDTO.langKey] does not meet min/max size requirements!`). Clicking *Create a new user* will then show an empty form again.
Also, in the creation/editing dialog, providing an already existing _Login_ or _Email_ and clicking _Save_ will bring the user back to the user management overview. It would be nice to keep the editing person within the dialog form as long as both client-side and server-side validations fail on save.

**dev sample users have non-validating email addresses**
the dev profile sample users are provided with email addresses (`system@localhost`, `admin@localhost`, and `user@localhost`) which do not validate in the user editing dialog - making it necessary to change the e-mail addresses to a validating one (e.g. `admin@localhost.example`) in order to edit that user.

##### **Motivation for or Use Case**
User creation and editing should be a consistent user experience.

##### **Reproduce the error**
While the other problems are self-explanatory to reproduce, here are the steps for reproducing _**User editing sometimes shows an incorrect activated/deactivated value**_:
* Start up backend with `mvn`.
* Start up frontend with `yarn start`.
* Visit http://localhost:8080/#/admin/user-management in a __new Chrome tab__ (complete React app reload seems to be required for reproducing this bug).
* Sign in as `admin`.
* Click _Edit_ for the `system` user.
* Expected behavior: _Activated_ checkbox should be checked.
* Actual behavior: _Activated_ checkbox actually is unchecked.

Chrome's Dev Console shows error messages:
* `Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in AvForm (created by UserManagementUpdate)`.
* When clicking the _Activated_ checkbox: `Uncaught TypeError: e.id.match is not a function` and `Uncaught TypeError: Cannot read property 'length' of undefined`.

##### **Related issues**
#8302.

##### **JHipster Version(s)**
generator-jhipster@5.3.1. I don't know if this is a regression.

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "monolith",
    "baseName": "exampleapp",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "xxx",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ]
  }
}
</pre>
</details>

##### **Browsers and Operating System**
Windows 7. Problems occur at least in Chrome.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
**User creation incorrectly creates activated user even when the user is requested to be deactivated**
In Angular, we disable this input when creating a new user, it should always be activated.  The new user is required to reset the password through an email for their first log in so it's the same as if they had to activate.

**User editing sometimes shows an incorrect activated/deactivated value**
I think this may be fixed by the issue you referenced (didn't test), as it should fetch the user on opening the update dialog.

**dev sample users have non-validating email addresses**
The React validation library we are using doesn't follow the email RFC exactly ([source](https://github.com/Availity/availity-reactstrap-validation/blob/49db051a8a8e0fc61b3ffe20d24b4e88678a46c0/__test__/AvValidator.email.spec.js#L19)), technically it should allow those emails.  Not sure what to do here.  ([Related issue](https://github.com/jhipster/generator-jhipster/issues/5810#issuecomment-303201305), [related StackOverflow](https://serverfault.com/q/721927))

**Comment by deepu105** [comment]
Would appreciate if you are willing to contribute fixes and improvements
here

**Comment by Abdull** [comment]
@ruddell, thank you for your comments.
> **User creation incorrectly creates activated user even when the user is requested to be deactivated**
> In Angular, we disable this input when creating a new user, it should always be activated. The new user is required to reset the password through an email for their first log in so it's the same as if they had to activate.

Allright. I think then it's good to have the _Activated_ input form disabled/greyed out and checked during user creation.

> **User editing sometimes shows an incorrect activated/deactivated value**
> I think this may be fixed by the issue you referenced (didn't test), as it should fetch the user on opening the update dialog.

I applied the changes of https://github.com/jhipster/generator-jhipster/pull/8338 to my code, but it does not improve the flaky checked/unchecked behavior.

**Comment by deepu105** [comment]
@Abdull does current master branch have same issues?

**Comment by deepu105** [comment]
@Abdull can you please update the issue with what is outstanding?

**Comment by jdubois** [comment]
As there has been no updates from a long time, and as it looks like there has been several fixes on the master branch, I'm closing this.
