### ISSUE TITLE
Extension of Domain Definition

### ISSUE THREAD

**Issue by SKoepsel** [jhipster/generator-jhipster#8370]
##### **Extension of Entity Generation Capabilities**

I propose that the JDL and related generators are extended to support the continous usage of jhipster and its tools in an agile development process and to support existing patterns in jHipster usage.
Therefore the following extensions to domain definitions are necessary:
- Optional replacement of the generated domain classes with"Generated" prefixed classes. Additionaly, "custom" classes inheriting from them are generated, if they do not already exist. This change is to support extension of existing entities without overriding custom changes. The pattern should be that generated code is only customised and extended in the derived classes. The generated classes containing the generated logic should be abstract, only the derived customizable classes should be used directly in the (generated) code. 
- Package options for jdl to define goal package. After domain objects are refactored after generation (like asserted in https://github.com/jhipster/jhipster-core/issues/123 says) changes through jhipster tools are impossible. 
Both concepts should be  used for services and related generated classes, too.

##### **Motivation for or Use Case**
At this moment, after initial setup and refactoring of generated code jhipster loses most of its possibilites. But as experience shows, editing of the model ist necessary long after its first generation.
The 2 given features would massivly increase the usability of jHipster in an agile Context.
Given tools, like entity editing could continue to be useful even after inital setup.
Furthermore, the jdl would continue to have its worth as a documentation tool, because its much easier to use it as the project develops
Common concepts such as modules and packages wouldn't break jHipster.
New users would have an easier way to discover best practices.

##### **Related issues or PR**
https://github.com/jhipster/jhipster-core/issues/123

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
why did you close it?

Thanks & Regards,
Deepu

**Comment by IlllIl** [comment]
Posted with the wrong account. Feel free to reopen or repost it if you feel that the content is appropriate.
