### ISSUE TITLE
import-jdl creating API classes on gateway; there shouldn't be any

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#8376]
##### **Overview of the issue**

I spent a good chunk of time today trying to re-create my [Develop a Microservices Architecture with OAuth 2.0 and JHipster](https://developer.okta.com/blog/2018/03/01/develop-microservices-jhipster-oauth) using `import-jdl` and the new support for creating multiple apps. 

It all seemed fine locally until I deployed to Heroku. That's when I discovered that my gateway wasn't saving data in the microservice apps, it was saving data in itself. 

I re-generated everything to confirm it, and it happens again. See screenshot below that shows the entities in the microservices have domain classes on the gateway.

I'm using [this JDL file](https://gist.github.com/mraible/3c97f60c6617e67fd87cd9895d54311c) to create my apps.

<img width="477" alt="screen shot 2018-09-20 at 7 49 58 pm" src="https://user-images.githubusercontent.com/17892/45855742-ccebd700-bd0e-11e8-86e0-aad760e161c7.png">

##### **Motivation for or Use Case**

It'd be cool to be able to create a microservices architecture with a single file.

##### **Reproduce the error**

Use `apps.jh` from [this gist](https://gist.github.com/mraible/3c97f60c6617e67fd87cd9895d54311c), run `jhipster import-jdl apps.jh`, and check the gateway's `domain` package to see if entities exist. They shouldn't.

##### **JHipster Version(s)**

This is the output I get when running `jhipster info` on my gateway.

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/mraible/dev/okta/okta-jhipster-microservices-oauth-example/gateway
└── generator-jhipster@5.3.4

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "gateway",
    "clientPackageManager": "npm",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.okta.developer.gateway",
    "packageFolder": "com/okta/developer/gateway",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [
      "protractor"
    ],
    "useSass": false,
    "websocket": false,
    "baseName": "gateway",
    "authenticationType": "oauth2",
    "jhipsterVersion": "5.3.4",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "skipUserManagement": true
  },
  "entities": [
    "Blog",
    "Post",
    "Tag",
    "Product"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

The passed validation must be valid to be added to the field.
Errors: No value
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR!
Error while parsing entities to JDL

    at Environment.error (/Users/mraible/dev/okta/okta-jhipster-microservices-oauth-example/gateway/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/Users/mraible/dev/okta/okta-jhipster-microservices-oauth-example/gateway/node_modules/generator-jhipster/generators/generator-base.js:2060:18)
    at module.exports.generateJDLFromEntities (/Users/mraible/dev/okta/okta-jhipster-microservices-oauth-example/gateway/node_modules/generator-jhipster/generators/generator-base-private.js:1000:18)
    at module.exports.displayEntities (/Users/mraible/dev/okta/okta-jhipster-microservices-oauth-example/gateway/node_modules/generator-jhipster/generators/info/index.js:57:34)
    at Object.<anonymous> (/Users/mraible/dev/okta/okta-jhipster-microservices-oauth-example/gateway/node_modules/yeoman-generator/lib/index.js:418:27)
    at /Users/mraible/dev/okta/okta-jhipster-microservices-oauth-example/gateway/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/mraible/dev/okta/okta-jhipster-microservices-oauth-example/gateway/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/mraible/dev/okta/okta-jhipster-microservices-oauth-example/gateway/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:810:20)
Execution time: 8 s.

**Comment by vishal423** [comment]
I also noted this recently, but, didn't dig further assuming some issue with my setup

**Comment by ruddell** [comment]
You need to set the microservice name ([docs](https://www.jhipster.tech/jdl/#microserviceoptions)).

    microservice Product with store
    microservice Blog, Post, Tag with blog

**Comment by mraible** [comment]
Thanks @ruddell! I'm closing this now.

**Comment by deepu105** [comment]
I'll let you all in on a little secret. It might be a bit old school but I find it very effective. When I work on some big revamp I follow the below to make sure things work the same as it used to and I'm not introducing any huge change.

1. I create an app or a microservice stack manually using the latest stable JH version and commit it to git.
2. I delete everything and recreate the apps using my new awesome cool feature :wink: 
3. I go through the git changelog to look for any change that I intended 

This also helps me to identify this kind of issues :)

**Comment by deepu105** [comment]
Btw @mraible WDYT of the new multi-app creation? any feedback? also did I tell you the old JDL studio is updated to work with JDL 3? https://www.jhipster.tech/jdl-studio/

**Comment by mraible** [comment]
@deepu105 I love the multi-app generation feature! It makes it pretty awesome to demo JHipster microservices. I should have used your suggestion with Git, it probably would've saved me some time. 

One issue I ran into that I sent to @jkutner is when I deploy everything to Heroku. My store microservice fails to communicate with its Elasticsearch instance:

```
2018-09-21T05:01:27.478390+00:00 app[web.1]: Caused by: org.apache.http.NoHttpResponseException: olive-9070097.us-east-1.bonsaisearch.net:443 failed to respond
2018-09-21T05:01:27.478392+00:00 app[web.1]: at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
2018-09-21T05:01:27.478394+00:00 app[web.1]: at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
2018-09-21T05:01:27.478395+00:00 app[web.1]: at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
```

I tried increasing the timeout for Jest in my `application-heroku.yml` file, but it doesn't help.

```yaml
spring:
    data:
        mongodb:
            uri: ${MONGODB_URI}?authMode=scram-sha1
        elasticsearch:
            properties:
                transport:
                    tcp:
                        connect_timeout: 120s
        jest:
            uri: ${BONSAI_URL}

```

It’s pretty strange really, Elasticsearch works fine for my blog app, but not for the store.

This isn't really a regression since in the past I've either 1) configured Elasticsearch to be embedded or 2) removed Elasticsearch when running on Heroku.

**Comment by deepu105** [comment]
Thanks for the feedback @mraible 
I also don't have an idea about the ES part, and I'm no ES expert anyway. I'm sure the smarter folks on our team will come up with a solution.

I imagine a day where we can do everything on JDL and just import it and then we can also coin the term   `development-as-code` (I'm looking at infra-as-code, devops-as-code and so on :wink: )
But seriously imagine a single file that defines my applications, entities, services, ci-cd setup, cloud deployment config etc. And you can share, recreate this with one command
Ping @MathieuAA

**Comment by MathieuAA** [comment]
@deepu105 this is on my mind ;)

**Comment by mraible** [comment]
@deepu105 Another thing that would be helpful is if the `.yo-rc.json` had the same order of keys if you're using `jhipster` vs `jhipster import-jdl`. Currently, they're very different, which makes it hard to compare the two. 

For example, here's my "store" microservice app generated with `jhipster` using 5.1.0:

```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer.store",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "microservice",
    "baseName": "store",
    "packageName": "com.okta.developer.store",
    "packageFolder": "com/okta/developer/store",
    "serverPort": "8082",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "4e6b5e9a3551e5d8548af5334c8953723d76fbfd",
    "enableTranslation": true,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipClient": true,
    "skipUserManagement": true,
    "herokuDeployType": "git"
  }
}
```

When using `jdl-import` and 5.3.4, properties are in a different order.

```json
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "clientPackageManager": "npm",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.okta.developer.store",
    "packageFolder": "com/okta/developer/store",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "serviceDiscoveryType": "eureka",
    "skipClient": true,
    "skipServer": false,
    "testFrameworks": [],
    "useSass": false,
    "websocket": false,
    "baseName": "store",
    "authenticationType": "oauth2",
    "serverPort": "8082",
    "jhipsterVersion": "5.3.4",
    "buildTool": "maven",
    "cacheProvider": "hazelcast",
    "clientFramework": "angularX",
    "skipUserManagement": true,
    "herokuAppName": "okta-store",
    "herokuDeployType": "git"
  },
  "entities": [
    "Product"
  ]
}
```

**Comment by deepu105** [comment]
@mraible I use the Sort JSON objects VSCode plugin and sort the jsons before comparing them. From JHCore it should be easy to write in a certain order but not sure if that's possible with Yeoman on generator. cc @MathieuAA

**Comment by MathieuAA** [comment]
I'm gonna sort them alphabetically.

**Comment by mraible** [comment]
@deepu105 It seems that https://www.jhipster.tech/jdl-studio/ is updated for the Full Stack JDL (see what I did there ;), but the [URL it recommends on JHipster Online](https://start.jhipster.tech/jdl-studio/) is not. Are there plans to keep them in sync, or remove one and redirect to the other?

**Comment by deepu105** [comment]
Ideally they should be in sync. I'm waiting for Julien to release JH online with the update

**Comment by deepu105** [comment]
And yes Full stack JDL sounds cool :)
