### ISSUE TITLE
Outdated entity definitions in sample apps

### ISSUE THREAD

**Issue by Abdull** [jhipster/generator-jhipster#8381]
##### **Overview of the issue**

I noticed that the entity definitions in (at least) the _jhipster-sample-app-react_ and _jhipster-sample-app_ are invalid/outdated with respect to the current (i.e., `generator-jhipster@5.3.4`) JDL grammar and semantics.

E.g., for _jhipster-sample-app-react_, the [entity definitions](https://github.com/jhipster/jhipster-sample-app-react/tree/v5.3.4/.jhipster) will make `jhipster info` generate the following JDL entity definition:

```
entity BankAccount {
  name String required,
  balance BigDecimal required
}
entity Label {
  label String required minlength(3)
}
entity Operation {
  date DateTime required,
  description String,
  amount BigDecimal required
}
relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)}
}
relationship ManyToOne {
  BankAccount{user(login)} to User
}
relationship ManyToMany {
  Operation{label(label)} to Label{operation}
}

dto BankAccount, Label, Operation with mapstruct
paginate Operation with infinite-scroll
```

These JDL entity definitions have the following issues:
* `DateTime` type is not (or no longer?) supported. [The JHipster documentation suggests to favor `Instant`](https://www.jhipster.tech/creating-an-entity/#field-types).
* Entities can use `dto`s only if they also use `service`.

These issues cause entity generation for another JHipster project with `jhipster import-jdl` (`generator-jhipster@5.3.4`) and using this JDL to fail.

##### **Motivation for or Use Case**
Having correct entity definitions for sample apps helps issue reporters to provide concise issue reproduction steps derived from these sample apps.

##### **Suggest a Fix**
Generate JHipster sample apps from a valid JDL, e.g.:
```
entity BankAccount {
  name String required,
  balance BigDecimal required
}
entity Label {
  label String required minlength(3)
}
entity Operation {
  date Instant required,
  description String,
  amount BigDecimal required
}
relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)}
}
relationship ManyToOne {
  BankAccount{user(login)} to User
}
relationship ManyToMany {
  Operation{label(label)} to Label{operation}
}

dto * with mapstruct
service * with serviceImpl

paginate Operation with infinite-scroll
```

##### **JHipster Version(s)**
generator-jhipster@5.3.4

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@Abdull would you like to PR a fix to the samples in the travis folder

**Comment by deepu105** [comment]
@jdubois @pascalgrimaud  what can we do here, should we just update the files in Travis and copy over?

**Comment by pascalgrimaud** [comment]
All samples in `test-integration` (`travis/` folder will be deleted soon) need to be update, same for all entities. Another suggestion is to generate a big jdl sample and use it in our CI

I already plan to do it the next month

**Comment by jdubois** [comment]
OK as per @pascalgrimaud comment I'm closing this. Indeed, this should all be replaced by JDL files, but that takes time to do.
