### ISSUE TITLE
Fix Export JDL

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#8391]
Some issues and improvements for `export-jdl` command

- [x] The export-jdl sub generator currently seems broken for normal applications, this is the store application from this JDL https://gist.github.com/deepu105/83145766158bf8923d20866de1221afa

```
$ jhipster export-jdl app.jdl -d
Using JHipster version installed locally in current project's node_modules
Debug logging is on
DEBUG!  cmd: export-jdl
DEBUG!  args: app.jdl, commands: Object, options: Object, _execs: Object, _allowUnknownOption: true, _args: Object, _name: export-jdl, _noHelp: false, parent: Object, _description: Create a JDL file from the existing entities, _argsDescription: undefined, _events: Object, _eventsCount: 1
DEBUG!  opts: argument: Object, desc: Create a JDL file from the existing entities
DEBUG!  Arguments found
DEBUG!  cmdArgs: app.jdl
Executing jhipster:export-jdl app.jdl
Options: d: true, from-cli: true
Parsing entities from .jhipster dir...
The passed validation must be valid to be added to the field.
Errors: No value
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! 
Error while parsing entities to JDL

    at Environment.error (/home/deepu/workspace/temp/iHomer/store/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/home/deepu/workspace/temp/iHomer/store/node_modules/generator-jhipster/generators/generator-base.js:2060:18)
    at module.exports.generateJDLFromEntities (/home/deepu/workspace/temp/iHomer/store/node_modules/generator-jhipster/generators/generator-base-private.js:1000:18)
    at module.exports.parseJson (/home/deepu/workspace/temp/iHomer/store/node_modules/generator-jhipster/generators/export-jdl/index.js:51:33)
    at Object.<anonymous> (/home/deepu/workspace/temp/iHomer/store/node_modules/yeoman-generator/lib/index.js:418:27)
    at /home/deepu/workspace/temp/iHomer/store/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/deepu/workspace/temp/iHomer/store/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/deepu/workspace/temp/iHomer/store/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:810:20)
```

- [x] it doesn't support exporting applications
- [x] it doesn't support exporting multiple applications from a root folder

**Comment by deepu105** [comment]
@MathieuAA do you think the second and third point is feasible

**Comment by MathieuAA** [comment]
Fixed the first one already, I'll create an issue for the two.

**Comment by MathieuAA** [comment]
Well, I'm reopening this. The culprit is [here](https://github.com/jhipster/generator-jhipster/blob/8739c7d88b6e23f04da4615d786a29f443e01858/generators/generator-base-private.js#L1076)

**Comment by MathieuAA** [comment]
@deepu105 I'm creating an exporting file in JCore to deal with this situation (and moving the logic from here to JCore, like the JDL importer). After that, I'll do a release to update the code here.

**Comment by deepu105** [comment]
Awesome thanks

Thanks & Regards,
Deepu

**Comment by Shaolans** [comment]
@MathieuAA Hello, I would like to contribute on this enhancement. Are you still working on it ?

**Comment by MathieuAA** [comment]
@Shaolans Hi, nop. I don't have much time to work on it.

**Comment by Shaolans** [comment]
Okay thanks ! Just so I know, is there already some base to work with ? like some utilities functions

**Comment by pascalgrimaud** [comment]
@Shaolans : you can have a look at this file https://github.com/jhipster/generator-jhipster/blob/master/generators/export-jdl/index.js

The export jdl works well for entities, inside a folder with existing JHipster app. It does not export the JHipster config.
And same for multi folder

**Comment by Shaolans** [comment]
Thanks ! I will check it out :+1:

**Comment by pascalgrimaud** [comment]
I'm adding a bounty on this as:
- it's opened for long time
- it looks like a lot of work
- it deserves this

**Comment by MathieuAA** [comment]
A PR has been merged on JCore about that. The credit goes to @Shaolans as I've taken his code as inspiration to implement it. He absolutely deserves the bounty.

**Comment by deepu105** [comment]
@MathieuAA shall we close this then?

**Comment by MathieuAA** [comment]
@deepu105 I'll be closing this tomorrow, when I'll drop the (hopefully) latest release of JCore before the merge.

**Comment by deepu105** [comment]
Sure thanks man. Awesome work

**Comment by Shaolans** [comment]
@MathieuAA You deserve as much as I do, if not more ! You did a great work by reviewing my PR and reimplement it better 👍

**Comment by deepu105** [comment]
I propose that both of you claim the bounty of $100  :) I'll be happy to
approve

Thanks & Regards,
Deepu

**Comment by Shaolans** [comment]
Bug bounty claimed https://opencollective.com/generator-jhipster/expenses/8966.
