### ISSUE TITLE
Feature Request: Add the ability to configure ACL

### ISSUE THREAD

**Issue by gomesp** [jhipster/generator-jhipster#840]
Thanks for this great project. I hope to contribute more to it in the near future. In the meantime, I'll make some feature requests (which I'd be willing to implement in the near future). Please let me know if it aligns with the project roadmap.

The 1st application that I'm trying to write based on JHipster requires ACL. 

Use case example:
- Organizations and Employees. The employees are associated with multiple organizations (e.g. they work for multiple orgs) and maintain their own details. 
- The organizations are allowed to view the employees details, but not to update them. 
- The organization details are maintained by yet another user, who "represents" the organization itself.

This can be achieved using ACE in Spring Security. I am not yet sure what would be the easiest way to add it to JHipster, but perhaps as a question in the entity generator (asking if this is going to require an ACL), combined with some administration interface to add/remove allowed SIDs for each ACE.

**Comment by jdubois** [comment]
Are you still working on this?
As far as I'm concerned it's too complex for us, and I've never seen ACL used anywhere (it's not even introduced in the SpringSource training, btw). So I'm closing this,  at least for the moment.

**Comment by gomesp** [comment]
I've started working on it, but I am far from finished. Work commitments diverted my attention. When I pick that up again I'll make a PR and you can reopen this issue.

Thanks

**Comment by jdubois** [comment]
OK -> we will refactor the security part after the v2.0 release, we'll see that at the moment

**Comment by diggers** [comment]
I'd be interested to know what is the suggested way to return entities that the user owns.

When establishing one to many relationships between entities, i.e: User -> Car a user_id column is added to the Car table, however the Principal is not exposing the User id to filter on. 

Should User implement a custom UserDetails that exposes the ID? or there is a better way?

**Comment by minu-jain** [comment]
Hi,

Can we  configure ACL to Jhipster now? 
Or its still in progress.

We are thinking of using Jhipster UAA. Can we easily integrate ACL with this. Any thoughts  are really appreciated.

Thanks,
Minu

**Comment by MathieuAA** [comment]
@minu-jain Hi, please don't comment on (very) old posts like this one, especially for a question. I suggest you ask your question on StackOverflow or on the Gitter.
