### ISSUE TITLE
[documentation] Add missing JDL field validation for unique constraint

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#8403]
##### **Overview of the issue**

Reviewing JDL documentation I discover that the [unique constraint implementation](https://github.com/jhipster/jhipster-core/commit/a4c7081b8f16b858bdfaa69d294f5774f6e27949) in jhipster-core project has never been documented in [JDL documentation](https://www.jhipster.tech//jdl/).

##### **Motivation for or Use Case**

A new feature since v.4.13.0  & v5.0.0.beta2 that seems not documented (https://github.com/jhipster/generator-jhipster/pull/6678 + https://github.com/jhipster/generator-jhipster/pull/6850 + https://github.com/jhipster/generator-jhipster/issues/6860):
https://github.com/jhipster/generator-jhipster/commit/f2e367315ec4128105c72df054079107d1be3279
https://github.com/jhipster/generator-jhipster/commit/baaa043c5564154d879a18e9cb1483745e38d56c

Note: The PR https://github.com/jhipster/jhipster.github.io/pull/520 has been merged in create entity documentation but I think it is missing the documentation in JDL part.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@MathieuAA I did not found any reference in https://github.com/jhipster/jhipster.github.io/blob/master/pages/jdl.md.
Do you want I PR to add the information?

**Comment by MathieuAA** [comment]
Is it finally in the generator?! I have a branch already for this... I'll find time to merge it and add the doc

**Comment by deepu105** [comment]
I'm not sure, will need to look at code. But I think it wad reverted at
some point due to issues

**Comment by MathieuAA** [comment]
Well, once it's in the generator and enabled, feel free to reach me so that I can do my part. Thanks :)

**Comment by DanielFran** [comment]
@deepu105 @MathieuAA Confirmed for the 2 pull request on generator side:
https://github.com/jhipster/generator-jhipster/commit/f2e367315ec4128105c72df054079107d1be3279
OK => https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs#L62-L65
+ https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs#L113-L116
KO => https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/prompts.js#L722-L725
(...)

https://github.com/jhipster/generator-jhipster/commit/baaa043c5564154d879a18e9cb1483745e38d56c
OK => https://github.com/jhipster/generator-jhipster/blob/master/travis/samples/.jhipster/Division.json#L23-L24
+ https://github.com/jhipster/generator-jhipster/blob/master/travis/samples/.jhipster/Division.json#L29-L32

So we need to take care of the missing changes in https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/prompts.js

**Comment by MathieuAA** [comment]
Roger that. Thanks for the heads up

**Comment by jdubois** [comment]
@DanielFran I'm reverting the commit right now

**Comment by DanielFran** [comment]
@MathieuAA I think that you can merge your changes and create the PR for the JDL documentation ;)

**Comment by jdubois** [comment]
@DanielFran sorry I can't revert the commit easily, there's a conflict, give me some time :-)

**Comment by DanielFran** [comment]
@MathieuAA You can proceed with the merge of unique validation in Core project since @jdubois already merge the missing prompts in the generator.
Do not forget to add the documentation in JDL part.
Thanks

**Comment by MathieuAA** [comment]
Okay!Le 3 oct. 2018 23:40, Daniel Franco <notifications@github.com> a écrit :@MathieuAA You can proceed with the merge of unique validation in Core project since @jdubois already merge the missing prompts in the generator.
Do not forget to add the documentation in JDL part.
Thanks

**Comment by DanielFran** [comment]
@MathieuAA Just to confirm with you if you already do the PR for to update of JDL documentation?
This issue is still open waiting for your confirmation....

**Comment by MathieuAA** [comment]
I don't have much time nowadays to do anything, but it's merged. I'll do the doc during the weekendLe 12 oct. 2018 18:04, Daniel Franco <notifications@github.com> a écrit :@MathieuAA Just to confirm with you if you already do the PR for to update of JDL documentation?
This issue is still open waiting for your confirmation....

**Comment by MathieuAA** [comment]
The PR has been submitted.

**Comment by DanielFran** [comment]
Closed with https://github.com/jhipster/jhipster.github.io/pull/641
