### ISSUE TITLE
Bug with clean+package in prod, without node_modules

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#8405]
##### **Overview of the issue**

Thanks to @hcapitaine for reporting to me this issue.

When the `node_modules/` is missing, you can't package the application with `prod` profile.
The error is:
```
14:57:32 in ~/tmp/01-toto on  master [!?] 
➜ mvn clean package -Pprod               
executing mvnw instead of mvn
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] 'profiles.profile[artifactory].repositories.repository.id' must be unique but found duplicate repository with id snapshots @ /home/pgrimaud/.m2/settings.xml
[WARNING] 
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.galerieslafayette.toto:jhipster >-----------------
[INFO] Building Jhipster 0.0.1-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ jhipster ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (default-resources) @ jhipster ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 15 resources
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ jhipster ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 15 resources
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ jhipster ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (pre-unit-tests) @ jhipster ---
[INFO] argLine set to -javaagent:/home/pgrimaud/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/home/pgrimaud/tmp/01-toto/target/test-results/coverage/jacoco/jacoco.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
[INFO] 
[INFO] --- git-commit-id-plugin:2.2.5:revision (default) @ jhipster ---
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.0.5.RELEASE:build-info (default) @ jhipster ---
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) @ jhipster ---
[INFO] Node v8.11.4 is already installed.
[INFO] NPM 6.4.1 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:npm (webpack build dev) @ jhipster ---
[INFO] npm not inheriting proxy config from Maven
[INFO] Running 'npm run webpack:build' in /home/pgrimaud/tmp/01-toto
[INFO] 
[INFO] > jhipster@0.0.0 webpack:build /home/pgrimaud/tmp/01-toto
[INFO] > npm run cleanup && npm run webpack:build:main
[INFO] 
[INFO] 
[INFO] > jhipster@0.0.0 cleanup /home/pgrimaud/tmp/01-toto
[INFO] > rimraf target/{aot,www}
[INFO] 
[ERROR] sh: 1: rimraf: not found
[ERROR] npm ERR! file sh
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno ENOENT
[ERROR] npm ERR! syscall spawn
[ERROR] npm ERR! jhipster@0.0.0 cleanup: `rimraf target/{aot,www}`
[ERROR] npm ERR! spawn ENOENT
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the jhipster@0.0.0 cleanup script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[WARNING] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/pgrimaud/.npm/_logs/2018-09-26T12_57_44_284Z-debug.log
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! jhipster@0.0.0 webpack:build: `npm run cleanup && npm run webpack:build:main`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the jhipster@0.0.0 webpack:build script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[WARNING] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/pgrimaud/.npm/_logs/2018-09-26T12_57_44_304Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.013 s
[INFO] Finished at: 2018-09-26T14:57:44+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (webpack build dev) on project jhipster: Failed to run task: 'npm run webpack:build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

##### **Motivation for or Use Case**

We should be able to package in prod, with or without the `node_modules` folder

##### **Reproduce the error**

1) generate a jhipster application with: `jhipster --skip-install` or clone an existing sample
2) launch `mvn clean package -Pprod`

##### **Related issues**

Related to this PR: https://github.com/jhipster/generator-jhipster/pull/8038 when we added `webpack` profile

##### **Suggest a Fix**

Try to add multiple condition for activating this profile:

https://github.com/jhipster/jhipster-sample-app/blob/master/pom.xml#L696-L699

##### **JHipster Version(s)**

Since 5.2.0

➜ jhipster info          
Using JHipster version installed globally
Executing jhipster:info
Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/01-toto
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.galerieslafayette.toto",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.4",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.galerieslafayette.toto",
    "packageFolder": "com/galerieslafayette/toto",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.19.0

node: v8.12.0

npm: 6.4.1

yeoman: 2.0.2

yarn: 1.9.4

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.21.2, build a133471

Congratulations, JHipster execution is complete!

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I think I saw similar error with Gradle when you don't have nodeJS
installed. The builds were suppose to do a local node/npm setup when global
is not found as well

**Comment by wmarques** [comment]
Should we run an `npm install` before building the front with maven ?

**Comment by jdubois** [comment]
@wmarques yes I guess so.
The issue is mostly when the project was created by someone else (so `npm install` did not run on your machine at project generation).
