### ISSUE TITLE
Integration with Vaadin

### ISSUE THREAD

**Issue by SheikhZayed** [jhipster/generator-jhipster#8410]
Integration with vaadin as Frontend

It would be great if jhipster can include vaadin in UI Layer along with React/Angular

It would be simple enough to use vaadin in the frontend because most of us who use jhipster are good java developers.
So,we can eliminate the need of knowing a JS framework,which inturn will make a single java dev handle both frontend and backend..

which would be really great!

**Comment by atomfrede** [comment]
I agree with you that a complete java stack (vaadin, thymeleaf or something else) would be quite cool, but I don't think we can handle that in the core. But we have now blueprints (https://www.jhipster.tech/modules/creating-a-blueprint/). The vue.js support for example will be a blueprint and I think vaading support would be a great candidate for a blueprint.

**Comment by SheikhZayed** [comment]
is there a blueprint for vaadin?

**Comment by SheikhZayed** [comment]
Sure ✌️
