### ISSUE TITLE
Enable Prometheus & add documentation for Prometheus

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#8423]
~~It seems like we have no documentation for Prometheus & Grafana, or at least I couldn't find them~~

~~Also it seems like there is no prometheus profile for Gradle and the maven profile isn't  documented as well~~

Enable prometheus back since its still ofeered during docker/kubernets config generation

**Comment by DanielFran** [comment]
@deepu105 this was removed since it was not working in a recent update...

**Comment by deepu105** [comment]
Then we need to remove the option everywhere since the docker/k8s sub generators still show the option

**Comment by deepu105** [comment]
@DanielFran btw in which release did we remove it?

**Comment by DanielFran** [comment]
@deepu105 removed in this PR https://github.com/jhipster/generator-jhipster/pull/8098

**Comment by deepu105** [comment]
@PierreBesson the issue for the above PR was Graphite relates right? why was Prometheus removed as well? If indeed it doesnt work we need to remove it everywhere

**Comment by saturnism** [comment]
was gonna look into prometheus w/ #7708. was wondering if the app still has a prometheus endpoint that can be scraped? thanks!

**Comment by atomfrede** [comment]
We should have prometheus, its just awesome imho.

**Comment by atomfrede** [comment]
I will add prometheus again. Should we make it configurable again or just expose the endpoint by default?

**Comment by deepu105** [comment]
We should at least make it usable out of the box with Kubernetes/Docker
when choosing the option

Thanks & Regards,
Deepu

**Comment by atomfrede** [comment]
Check will prepare a first version with prometheus enabled by default (imho it doesn't hurt) and we can add a property in `JhipsterProperties` afterwards.

**Comment by PierreBesson** [comment]
Prometheus was initially removed during the failed attempt at migrating to micrometer. Then, we still want to migrate to micrometer in the future which support prometheus out of the box with dimensional metrics which are more appropriate to the prometheus model). We have started the work on micrometer at Ippon with Clement the new intern, so the migration should be in progress in the coming weeks.

In the mean time, I agree with @atomfrede's approach of adding it by default (maybe in the lib itself so people who upgrade the lib can get it easily) but let's not add the property again.
