### ISSUE TITLE
Angular: the JHipster logo is missing in error page (style)

### ISSUE THREAD

**Issue by ndywicki** [jhipster/generator-jhipster#8424]
##### **Overview of the issue**

When an error occured (or access denied) the error html page not displaying the JHipster logo.

##### **Motivation for or Use Case**

Little issue but we can't see the beautiful JHipster logo in error pages ;-)

##### **Reproduce the error**

Generate an application with angular (mono or gateway app)
Navigate to http://localhost:9000/#/accessdenied

Result:

![acessdenied_logo_ko](https://user-images.githubusercontent.com/1721344/46289459-6f1a8300-c589-11e8-9c37-4e7b27d8d925.JPG)

Instead of:

![acessdenied_logo_ok](https://user-images.githubusercontent.com/1721344/46289955-ccfb9a80-c58a-11e8-9387-d9fde3c56c54.JPG)

##### **Related issues**

N/A

##### **Suggest a Fix**

In `error.component.html` logo span is present :
`<span class="hipster img-fluid rounded"></span>`
But style class `hipster` wasn't declared like `home.scss`.

Somes possibilities :
1. Create error.(s)css with `hipster` style class (copy of home) and declare it in `error.component.ts`
3. Declare home.(s)css style url in `error.component.ts`
```
@Component({
    selector: 'jhi-error',
    templateUrl: './error.component.html',
    styleUrls: ['../../home/home.scss']
})
```
3. Move home.(s)css `hipster` style class to the global style file

##### **JHipster Version(s)**

v5.3.4

##### **JHipster configuration**

λ jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 C:\workspace\jhipster\version\v5.3.4\micro\gateway-oauth2
`-- generator-jhipster@5.3.4

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "5.3.4",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.9.3.windows.1

node: v8.11.4

npm: 5.7.1

yeoman: 1.8.5

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

##### **Browsers and Operating System**

Win10 64Bits

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Oh yes it would look better... Then that's just a template, normally people will change it.

+1 from me, @ndywicki would you like to do the PR?

**Comment by ndywicki** [comment]
@jdubois yes I can push a PR. 
Just tell me if it's ok to point the `home.(s)css` style sheet (suggest #2) or move `.hipster` to global file (suggest #3) ?
I don't like style duplicates :)

**Comment by jdubois** [comment]
Oh I see, this is currently in the "home.css" page, so that would need to be duplicated to the error page... I also hate duplication, so that means moving the code to the "global.css" file.

Those things will change soon (we'll move fully to Sass, and we'll also change the logo), so don't worry too much. I think that in the long term those should be 2 different images, and that would solve the issue.

**Comment by ndywicki** [comment]
Yes, as you said, this page must be personalized. I leave in the state if changes on the style are coming.
I close the ticket.

Thanks.
