### ISSUE TITLE
No database option is not available when creating microservice application

### ISSUE THREAD

**Issue by alexander-redmann-teaching** [jhipster/generator-jhipster#8425]
##### **Overview of the issue**

On the jhipster homepage  it is described that a microservice application geenerated by jhipster could be created without an database, but this option does not exist when I want to create the service.

Here is one place where this option is mentioned at the last paragraph:
https://www.jhipster.tech/creating-microservices/

##### **Suggest a Fix**

Add option to not creating database or update documentation

##### **JHipster Version(s)**

v5.3.4

![jhipster-no-dataabse](https://user-images.githubusercontent.com/33935295/46293126-db4db480-c592-11e8-804b-71380cb6180a.png)

**Comment by jdubois** [comment]
That's because you used OAuth2, which requires a database. I agree this is not clear in the documentation, and besides it should be possible to use OAuth2 without a database (cc @mraible ).

**Comment by jdubois** [comment]
I'm only correcting the documentation at the moment, as we require a database for OAuth2 with our current implementation.

We will refactor all this when we migrate to Spring Security 5.1, which will be a huge change and cleanup on that part, and hopefully remove this constraint.

**Comment by murdos** [comment]
For the record: fixed with #9634 in JHipster 6
