### ISSUE TITLE
Generate a Cassandra version

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#843]
- Using Spring Data Cassandra
- Should be close to the MongoDB version

**Comment by jdubois** [comment]
I'm working on it here: https://github.com/jhipster/jhipster-cassandra-app

**Comment by jdubois** [comment]
We should also check Liquibase Cassandra: https://github.com/liquibase/liquibase-cassandra
@nvoxland is it usable?

**Comment by chbatey** [comment]
I was going to raise Cassandra support but you are all way ahead! Happy to you test this.

**Comment by nvoxland** [comment]
I've not really used cassandra enough to have any idea of how usable the extension is. It's completely community-contributed.  

I've been recently emailing with @sbonde who created https://github.com/sbonde/liquibase-ext but I haven't gotten a chance to look at the differences. His is probably worth looking at as well.

**Comment by jimbobwyatt** [comment]
I would be weary of any automagic schema migration tooling for Cassandra. Migrations there are almost always more complicated than you would ever want a tool to do for you IMO. Basic crud support and KISS should be more than enough than those selecting Cassandra over alternatives. My two cents.

**Comment by jdubois** [comment]
This is now merged in the main branch!
