### ISSUE TITLE
JHipster app resiliency

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#8431]
##### **Overview of the feature request**

This issue is an open discussion about JHipster app resiliency. Being resilient to a DB shutdown or a missing service is not free and implies an additional layer to either wait, use cached data or fallback to a default behavior.

I would be interested to find the balance between the benefits of resiliency and the technical complexity based on the JHipster community' feedbacks.

For the record, everything started here #8414 

##### **Related issues or PR**

Resiliency is of course a Top #1 priority in a cloud environnement (and partially covered with the circuit breaker pattern) but also for "classic" applications. 

Currently, if a dependent service (eg. Database) is not up and ready to receive  requests, the JHipster app stops and shutdown.

Chaos Engineering is hype these days and it's not only an Ops issue 😉 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
This feature was discussed for inclusion in Spring Boot back in 2015 !
https://github.com/spring-projects/spring-boot/issues/4779
This could be developed as part of the JHipster lib and enabled with properties.
So basically we could have those properties:
```
jhipster:
  datasource:
    retries:
      enabled: true
      initial-interval: 1000
      multiplier: 1.1
      max-interval: 2000
      max-attempts: 100
```

Or either we don't define any properties ourselves, we just use the ones provided by spring-cloud-config: see [RetryProperties.java](https://github.com/spring-cloud/spring-cloud-config/blob/v2.0.1.RELEASE/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/RetryProperties.java) (although I think our basic monolith currently don't have the dependency).

**Comment by pascalgrimaud** [comment]
It's an interesting subject but if we decide to add specific code for this, we'll go too far. 
I'm pretty sure some user won't want this, and prefer the application to stop and shutdown.

I think it will be better to add documentation, and let the user to add these code and/or properties.

**Comment by PierreBesson** [comment]
I'm also against pushing this as default, only as an option configurable with properties.

**Comment by jdubois** [comment]
Originally the database issue comes from the Spring philosophy from several years ago: do not start the container if everything is not working properly. Now things have changed a lot, of course, including on the Spring side. I'm not sure what is the current standard with Spring Boot, as it's supposed to be "cloud native", and hence support this use-case.

So, following our [Policy 1](https://www.jhipster.tech/policies/) I would like first to study how this is supposed to work today in Spring Boot.

Then, there is also another reason not to do those checks at startup: we would definitely load the application faster.

 Also, we would need the same "feature" with Cassandra, MongoDB, Couchbase, Kafka, Elasticsearch.... Not sure this is complex for each of them, but if you add them all I'm afraid this would be quite time-consuming to achieve, if that's not supported out-of-the-box by Spring Boot.

**Comment by deepu105** [comment]
My 2 cents. IMO the pattern makes more sense in a microservice architecture
than in a monolith. Of course, you can do it a monolith but in most cases,
you wouldn't want your app to start if the DB is down unless your
application is only doing some static content serve.
To me, I don't want to take additional burden of maintaining this in
JHipster. Of course if its a spring feature which we can just enable
disable that's a different story. To do this ourself would be overkill and
we have may more pressing concerns to manage than this. If you are really
interested then I would suggest to do it as a module so that people who
really want this can use it and others wouldn't mind.

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
OK I agree with @deepu105 here. I'd love to have something like this, but this more a work for Spring Boot, and we really can't implement this at the moment. We have nearly 50 opened tickets and we need to prioritize, and take what we are able to do. Here it's just too complex for our limited resources.
