### ISSUE TITLE
Adopt spring-cloud-kubernetes when native service discovery is used

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#8437]
##### **Overview of the feature request**

Currently JHipster registry uses Spring Cloud to discover and display application health. This doesn't work if no service discovery is used in a native Kubernetes deployment.

If no service discovery used, and deployed in Kubernetes, configure JHipster registry w/ Spring Cloud Kubernetes (which now works w/ Spring Boot 2).

##### **Motivation for or Use Case**

Able to use JHipster registry w/o Eureka/Consul.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
I think you mean JHipster registry and not JHipster Console.

**Comment by saturnism** [comment]
ah yes! updated.

**Comment by jdubois** [comment]
As of yesterday's meeting with @saturnism @PierreBesson this isn't a priority anymore, so I'm closing this
