### ISSUE TITLE
Websocket doesnt work

### ISSUE THREAD

**Issue by gzsombor** [jhipster/generator-jhipster#844]
I've tried to create a new application with athmosphere support, but it doesnt seems to be working. If I start with "mvn spring-boot:run", I have the following lines in the log :

`[WARN] org.atmosphere.util.IOUtils - META-INF/services/org.atmosphere.cpr.AtmosphereFramework not found in class loader
[WARN] org.atmosphere.cpr.DefaultAsyncSupportResolver - Found multiple containers, please specify which one to use: org.atmosphere.container.Tomcat7CometSupport, org.atmosphere.container.TomcatCometSupport,  until you do, Atmosphere will use:class org.atmosphere.container.Tomcat7CometSupport'

and later: 

'[ERROR] org.atmosphere.cpr.AsynchronousProcessor - Invalid request state. Websocket protocol not supported'

And in the browser this is logged: 
`atmosphere.js:1117 WebSocket connection to 'ws://localhost:8080/websocket/tracker?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.5-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json&X-atmo-protocol=true' failed: Error during WebSocket handshake: Unexpected response code: 501
atmosphere.js:3117 Websocket failed. Downgrading to Comet and resending`

It's not clear how this should work, if the comet downgrading is working or not, because I can't see anything in the 'Real-time user activities' screen

**Comment by jfarcand** [comment]
Filled SpringBoot issue, let's see what they have to say: https://github.com/spring-projects/spring-boot/issues/2341

**Comment by philwebb** [comment]
#2341 should be fixed when 1.2.2 is released. I've added a sample app but I'm not that familiar with Atmosphere so I may well be configuring it in a daft way. Hopefully the root issue is sorted and the sample will give you some way to proceed.

Let us know if we need to change anything else.
