### ISSUE TITLE
nativeLanguage & languages not taken into account if enableTranslation is false

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#8445]
##### **Overview of the issue**
`nativeLanguage` & `languages` `application.config` JDL parameter not taken into account if `enableTranslation` is set to `false`.

##### **Motivation for or Use Case**
I want to generate single application without i18n support but with another native language than English.

##### **Reproduce the error**

Create the following `jhipster-jdl.jh`:
```
application {
  config {
    applicationType monolith
    authenticationType jwt
    baseName cartest
    buildTool maven
    cacheProvider hazelcast
    clientPackageManager yarn
    devDatabaseType postgresql
    enableSwaggerCodegen false
    enableTranslation false
    languages [fr]
    nativeLanguage fr
    packageName com.mycompany.cartest
    prodDatabaseType postgresql
    testFrameworks [cucumber, gatling]
    useSass true
  }

  entities *
}

entity Car {
  model String maxlength(50),
  createdDate LocalDate
}

paginate * with pagination
```
Then execute
```bash
docker run -it --rm -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 jhipster/jhipster jhipster import-jdl ./jhipster-jdl.jh

docker-compose -f src/main/docker/postgresql.yml up &
yarn start &
./mvnw
```

Then accessing to http://localhost:9000 is displaying an English version of everything instead of a French one.

##### **JHipster Version(s)**
5.3.4

##### **Browsers and Operating System**

Ubuntu 16.04 LTS on Chromium browser

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry but if you don't select i18n, the only language you will get is English.

- If you have i18n, we have a full system to select the right language.
- If you don't have i18n, the language is directly hard-coded (which might be simpler to use). And we only hard-coded it in English.
