### ISSUE TITLE
@ManyToMany is using plural @JoinColumn name instead of singular

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#8447]
##### **Overview of the issue**
When using ManyToMany relationship, the generated `@Entity` is using plural for `@JoinColumn(name)` property.
I think the best practice is to use singular column name for such join table column.
Some examples of such best practice:
- https://www.baeldung.com/hibernate-many-to-many
- https://www.mkyong.com/hibernate/hibernate-many-to-many-relationship-example-annotation/
- https://vladmihalcea.com/the-best-way-to-map-a-many-to-many-association-with-extra-columns-when-using-jpa-and-hibernate/

##### **Motivation for or Use Case**
I want my many-to-many relationships to follow best practices, that is to say, to generate join table containing column using singular names.

##### **Reproduce the error**
Given the following `jhipster-jdl.jh`
```
entity Project {
  name String required maxlength(50)
}

entity City {
  name String required maxlength(50)
}

relationship ManyToMany {
  Project{city(name)} to City{project(name)}
}
```
the generated `Project.java` entity looks like
```java
    @ManyToMany
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    @JoinTable(name = "project_city",
               joinColumns = @JoinColumn(name = "projects_id", referencedColumnName = "id"),
               inverseJoinColumns = @JoinColumn(name = "cities_id", referencedColumnName = "id"))
    private Set<City> cities = new HashSet<>();
```
instead of
```java
    @ManyToMany
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    @JoinTable(name = "project_city",
               joinColumns = @JoinColumn(name = "project_id", referencedColumnName = "id"),
               inverseJoinColumns = @JoinColumn(name = "city_id", referencedColumnName = "id"))
    private Set<City> cities = new HashSet<>();
```

##### **Suggest a Fix**
Modify https://github.com/jhipster/generator-jhipster/blob/8739c7d88b6e23f04da4615d786a29f443e01858/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs#L271-L272
as well as https://github.com/jhipster/generator-jhipster/blob/af02fe82e6c0cf568a5f76d3098c343a3fd29ebf/generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs#L46-L51 and https://github.com/jhipster/generator-jhipster/blob/af02fe82e6c0cf568a5f76d3098c343a3fd29ebf/generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs#L160-L168

##### **JHipster Version(s)**
5.3.4

##### **JHipster Version(s)**

```
myproject@0.0.0 /dev/shm/test
└── generator-jhipster@5.3.4 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "clientPackageManager": "yarn",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "fr",
    "packageName": "com.mycompany.myproject",
    "packageFolder": "com/mycompany/myproject",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [
      "cucumber",
      "gatling"
    ],
    "useSass": true,
    "websocket": false,
    "authenticationType": "jwt",
    "baseName": "myproject",
    "buildTool": "maven",
    "cacheProvider": "hazelcast",
    "jhipsterVersion": "5.3.4",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "skipUserManagement": false
  },
  "entities": [
    "Project",
    "City"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Project {
  name String required maxlength(50)
}
entity City {
  name String required maxlength(50)
}
relationship ManyToMany {
  Project{city(name)} to City{project}
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.7.4

node: v8.10.0

npm: 6.2.0

yeoman: 2.0.1

yarn: 1.7.0

Docker version 17.05.0-ce, build 89658be

docker-compose version 1.14.0, build c7bdf9e

##### **Browsers and Operating System**
Ubuntu 16.04 LTS

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by GuiF007** [comment]
Already noticed that ! Don't know why it's like this...

**Comment by freynder** [comment]
Hello,
Is there any guidance on how to upgrade existing projects? When following jhipster upgrade instructions, initial liquibase changesets are updated rather than creating new changesets with renameColumn instructions and according changes to the FK constraints. Should this be done manually? 
Thank you
