### ISSUE TITLE
Implement HTML5 pushstate for Angular & React clients

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#8462]
##### **Overview of the feature request**

HTML pushstate has been a long discussion on the JHipster issues thread.
It should be nice to implements it, because it has many advantages for the end users.
May be motivating contribution with a bounty? I can pay from my pocket if necessary.

##### **Motivation for or Use Case**

- SEO and server side rendering

- Using anchors in pages

- Avoiding some tricky Identity provider hacks (tokens are usually returned on the form of anchors)

##### **Related issues or PR**

[list](https://github.com/jhipster/generator-jhipster/issues?utf8=%E2%9C%93&q=pushstate+)

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@Tcharl are you working on this?

**Comment by deepu105** [comment]
Oh ok, Just read your description. Of course we can put a bounty, not a big deal, but not sure if that will help, lets try anyway. @jdubois i'm adding a bounty on this
