### ISSUE TITLE
Incorrect version for Oracle ojdbc8 driver in parent pom

### ISSUE THREAD

**Issue by sazeez** [jhipster/generator-jhipster#8466]
##### **Overview of the issue**

The JHipster parent pom defines oracle JDBC GAV as com.oracle.jdbc:ojdbc8:jar:18.3, but maven.oracle.com published GAV is com.oracle.jdbc:ojdbc8:jar:18.3.0.0

Project fails to compile with error:
[ERROR] Failed to execute goal on project : Could not resolve dependencies for project : Could not find artifact com.oracle.jdbc:ojdbc8:jar:18.3 in maven.oracle.com (https://maven.oracle.com) -> [Help 1]

##### **Motivation for or Use Case**

Microservice generated using JHipster using oracle database as backend.

##### **Reproduce the error**
Overriding version in project pom.xml using below fixes the issue. 
        <dependency>
            <groupId>com.oracle.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>18.3.0.0</version>
        </dependency>

##### **Suggest a Fix**

Change  <oracle-jdbc.version> to 18.3.0.0 in https://github.com/jhipster/jhipster/blob/master/jhipster-dependencies/pom.xml

##### **JHipster Version(s)**
5.4.0

##### **JHipster Version(s)**

```
`-- generator-jhipster@5.4.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
    },
    "jhipsterVersion": "5.4.0",
    "serverPort": "8082",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true,
    "enableHibernateCache": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode, sharing)

git version 2.16.2.windows.1
node: v8.10.0
npm: 6.4.1
yeoman: 2.0.5
yarn: 1.9.4

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
None

##### **Browsers and Operating System**
Windows 10
-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Thanks a lot @sazeez for both the bug report and the fix!!! That's awesome :-)
It's a bit hard to test as we need an access to Oracle's Maven repo, but I think we already had this issue, so this is a bit disturbing...

**Comment by jdubois** [comment]
Closing as PR is merged.
