### ISSUE TITLE
/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk Blank Pages JHipster 5.4.1

### ISSUE THREAD

**Issue by rampantlion103** [jhipster/generator-jhipster#8467]
I tried the latest JHipster 5.4.1 with the latest Java 8, but I am getting a blank page at localhost:8080 at Safari, Chrome and Firefox. 

Here are the versions:

$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

$ jhipster --version
Using JHipster version installed globally
5.4.1

When further test in my mac terminal, the following starting results are:
$ curl localhost:8080
<!doctype html>
<html class="no-js" lang="es" dir="ltr">
<head>
    <base href="./" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>blog</title>
......

What is causing the blank page? Anything that I can do or configure in my maven?

**Comment by jdubois** [comment]
Yes you need to run `npm install && npm start`.

Please have a look at the documentation, it's fully explained.

I agree this is not user-friendly, but it's harder to solve than one may think - we just had a brain storming session yesterday about this with @wmarques and this should be much improved in the future.

**Comment by deepu105** [comment]
The maven build should have run npm install and build when you run the
bootrun task, unless you started the app some other way. Anyway you don't
provide us enough details

**Comment by jdubois** [comment]
Yes @deepu105 you are correct, but I'll also open a couple of new feature requests to improve the error pages (and I think we've been pretty clever with @wmarques , you'll see!)

**Comment by rampantlion103** [comment]
Team, I' really sorry for this delayed response because I took a vacation. First you are right that to use "npm start" and it works. In my case, I was following step by step instruction from the "Video Tutorial (16 minutes)" by @mraible. In 03:22 of the video tutorial, he suggested that the method to start the Jhipster is to use the IDE(Intellij) to start the blog app instead of the maven. This is steps to reproduce the blank page ...
Sorry again for the slow response.

**Comment by jdubois** [comment]
Thanks for your feedback! No problem, I know we need to improve this.

**Comment by deepu105** [comment]
I guess since we moved the initial webpack build step to maven/gradle, we
need to update the video to use maven/gradle or to ask to run npm start
