### ISSUE TITLE
How to make JHipster don't add id field as default?

### ISSUE THREAD

**Issue by nqthiep** [jhipster/generator-jhipster#8474]
Hi Everybody,

I would to generate an Entity has a field which is a key field.
I want to specify the name of this key field by myself, not use the "id" as default of JHipster.

Is there anyone know a solution,
please help me.

**Comment by deepu105** [comment]
It is not possible as ID is the primary key and we have no plans to support such feature. You would have to remove it manually if you don't like it. But honestly I don't see why you would want to do it

**Comment by nqthiep** [comment]
Yes, i known that the Jhipster doesnt support it. But i would like to know is there any other solution than manual.
I follow to design of our customer.

**Comment by ruddell** [comment]
You can write a blueprint ([docs](https://www.jhipster.tech/modules/creating-a-blueprint/)) and customize all of the templates.  The ID is used in a lot of places so there will be a lot of modifications

**Comment by nqthiep** [comment]
@ruddell Thaak you for your guide.
