### ISSUE TITLE
Validation's placeholders are not replaced in React with translation disabled

### ISSUE THREAD

**Issue by Falydoor** [jhipster/generator-jhipster#8476]
##### **Overview of the issue**

Validation's placeholders are not replaced with the corresponding value.

![image](https://user-images.githubusercontent.com/2212267/46568855-fa916c80-c919-11e8-8494-1b6beb154a17.png)

##### **Motivation for or Use Case**

The message should display the value to help the user.

##### **Reproduce the error**

Generate a React monolith with no translation.
Generate an entity with validation that requires a value (ex: min, max, pattern, etc).

##### **Suggest a Fix**

I believe it's because in the method `utils.replaceTranslation` the placeholders are never replaced by their values.

##### **JHipster Version(s)**

5.4.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.4.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Person {
  age Integer min(1)
}

</pre>
</details>

##### **Browsers and Operating System**

Chrome 69.0.3497.100 on Mac.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Wgil** [comment]
Hello! I'm going to give this a try
