### ISSUE TITLE
Angular - Switch to reactive forms?

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#8482]
##### **Overview of the feature request**

Reactive forms is a new paradigm brought by Angular 6.
It could be nice to upgrade update forms to highlight it, as the approach looks better than the actual form validation implemented by JHipster.

##### **Motivation for or Use Case**

Easier validation. I've already tested it for some of our forms and it looks easier to understand than ngModel + validation bindings.

##### **Related issues or PR**

Even @wmarques is OK for it!
https://github.com/jhipster/generator-jhipster/issues/7575

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
@Tcharl Indeed it's a good idea I also find it better for validation. That's quite a big work to do so maybe we can try to do that for JHipster v6 ?

**Comment by Tcharl** [comment]
It could be a good target for V6, as it would be very visible to the Angular users.
I'll try to implement it on a WIP branch when I'll finish the current contributions

**Comment by DanielFran** [comment]
@thainan10 Are you working in Reastive forms ? See https://github.com/jhipster/generator-jhipster/issues/7575
