### ISSUE TITLE
Converting Gradle build scripts from groovy to kotlin

### ISSUE THREAD

**Issue by rifatdover** [jhipster/generator-jhipster#8494]
##### **Overview of the feature request**

Gradle now supports kotlin as an alternative to groovy. 

##### **Motivation for or Use Case**

This helps a lot about tools inside ides like Idea. And also it is easier to implement custom tasks inside kotlin.

##### **Related issues or PR**

I can not find a related issue about this.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by rifatdover** [comment]
Here is migration guide:

https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/

**Comment by jdubois** [comment]
The boss on this part is @atomfrede (and maybe also @deepu105 ) but not me :-)
The main downside for me is that this would lock us with Intellij IDEA - I'm not a big fan of forcing people to use an IDE, even more if it's a paying one (I know there's a community edition, but if you want the full experience it's far too expensive for most of our users). And please note I'm huge Intellij IDEA user and fan :-)

**Comment by deepu105** [comment]
No, I don't see any reason to migrate. I like the way it is and hate doing something just becoz its hyped.

**Comment by rifatdover** [comment]
@jdubois @deepu105 It is not forcing you to use Idea it is just providing you to use kotlin in DSL not groovy. But you are the boss. :)

**Comment by rifatdover** [comment]
Maybe an alternative would be good? Or in Khipster?

**Comment by atomfrede** [comment]
I see it basically the same way as @deepu105 . There is currently no need to migrate to kotlin imho. What we should try (and I didn't had time for that) is a jhipster Gradle plugin as it makes maintaining our Gradle build easier both for us and the users by proving an opiniated way to build a jhipster project. So @rifatdover if you would like you can support us in writing that plugin.

**Comment by rifatdover** [comment]
@atomfrede Is there a related issue?

**Comment by rifatdover** [comment]
@atomfrede If you guide me about how it should be or what you have in your mind I will be pleased to help.

**Comment by atomfrede** [comment]
I will have a look tomorrow. We have closed the related issue as I didn't had the time last year. Maybe we can try to have something ready for Gradle 5 later this year.

**Comment by deepu105** [comment]
@rifatdover and if you decide to write that plugin, you can of course do that in Kotlin if you like :)

**Comment by atomfrede** [comment]
@rifatdover Here is the plugin with some discussion and one pr we can discard: https://github.com/hipster-labs/jhipster-gradle-plugin

So we should have multiple plugins in the end, starting with a `jhipster-base` plugin and multiple smaller plugins which configures more or less other plugins. We should keep in mind that some things need to be configured from within the project and can't be part of the plugin itself.

Maybe we can have a look at https://github.com/aalmiray/kordamp-gradle-plugins which seems very similar to what we need to build. Besides the base plugin (configuring boot & java plugins) I have something in mind like `jhipster-frontend`, `jhipster-liquibase`, `jhipster-sonar`, `jhipster-openapi` for example. Furthermore it would be cool to get rid of all `-P` switches as they make the tasks less discoverable. But lets not spam this issue anymore :) For more discussions lets use https://github.com/hipster-labs/jhipster-gradle-plugin
