### ISSUE TITLE
Datepicker not displayed on Safari & Firefox

### ISSUE THREAD

**Issue by gomesp** [jhipster/generator-jhipster#850]
Hi guys

The datepicker component only displays on date fields when I browse to the application using Chrome. Not working when I browse using Safari or Firefox on OS X (all browsers on their latest versions on Yosemite).

**Comment by barfoo4711** [comment]
http://stackoverflow.com/questions/28134960/how-to-add-datepicker-at-jhipster-ui shows how to add a datepicker to a jhipster project.
