### ISSUE TITLE
TextBlob is missing in JDL-Studio

### ISSUE THREAD

**Issue by alexander-redmann-teaching** [jhipster/generator-jhipster#8507]
Not a real bug, but an inconsistency. In the JDL-Studio is the **TextBlob** missing as an build in auto-complete value.

**Comment by PierreBesson** [comment]
Same as my previous comment on your other issue : https://github.com/jhipster/generator-jhipster/issues/8508#issuecomment-428174093

I'm sorry but a one liner is not a valid bug report or feature request.
---

This ticket has been closed as the **guidelines are not followed**.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md),
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

**Comment by deepu105** [comment]
Please use the JDL studio issue tracker
