### ISSUE TITLE
Warnings if reserved words are used in JDL-Studio and JHipster generator

### ISSUE THREAD

**Issue by alexander-redmann-teaching** [jhipster/generator-jhipster#8508]
##### **Overview of the feature request**

Some words are reserved for JHipster or Java itself (e.g. User for JHipster when used by JDL-Studio or class, new as packagename part in the generator).
If I write them in the JDL-Studio they should be marked as an error, to resolve the problems before the JDL is imported and decline the package name if generating the project

**Comment by PierreBesson** [comment]
Please follow the issue template and provide exemples on what feature exactly you are requesting and if you are able to contribute.

Also the JDL studio issue tracker is probably more appropriate for this: https://github.com/jhipster/jdl-studio/issues

---

This ticket has been closed as the **guidelines are not followed**.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md),
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

**Comment by deepu105** [comment]
Yes, please open an issue in the JDL studio issue tracker
