### ISSUE TITLE
Cloud Foundry sub-generator does not work: no suitable cloud connector found

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#8518]
##### **Overview of the issue**

I attempted to deploy a JHipster app (with PostgreSQL) to Cloud Foundry today and it fails with the following stack trace:

```
2018-10-09T12:37:42.10-0600 [APP/PROC/WEB/0] OUT Caused by: 
org.springframework.beans.BeanInstantiationException: Failed to instantiate 
[org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 
'servletEndpointRegistrar' threw exception; nested exception is 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with 
name 'auditEventsEndpoint' defined in class path resource 
[org/springframework/boot/actuate/autoconfigure/audit/AuditEventsEndpointAutoConfiguration.c
lass]: Unsatisfied dependency expressed through method 'auditEventsEndpoint' parameter 0; 
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error 
creating bean with name 'customAuditEventRepository' defined in file [/home/vcap/app/WEB-
INF/classes/com/okta/developer/repository/CustomAuditEventRepository.class]: Unsatisfied 
dependency expressed through constructor parameter 0; nested exception is 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'persistenceAuditEventRepository': Cannot create inner bean '(inner bean)#22ee2d0' of type 
[org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 
'entityManager'; nested exception is 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'(inner bean)#22ee2d0': Cannot resolve reference to bean 'entityManagerFactory' while 
setting constructor argument; nested exception is 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with 
name 'liquibase' defined in class path resource 
[com/okta/developer/config/LiquibaseConfiguration.class]: Unsatisfied dependency expressed 
through method 'liquibase' parameter 1; nested exception is 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'cloudDatabaseConfiguration' defined in file [/home/vcap/app/WEB-
INF/classes/com/okta/developer/config/CloudDatabaseConfiguration.class]: Initialization of 
bean failed; nested exception is org.springframework.cloud.CloudException: No suitable cloud 
connector found
```

##### **Motivation for or Use Case**

It used to work.

##### **Reproduce the error**

Create an app with the following JDL:

```
application {
  config {
    applicationType monolith,
    baseName HealthPoints
    packageName com.okta.developer,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    buildTool gradle,
    searchEngine elasticsearch,
    testFrameworks [protractor],
    clientFramework react,
    useSass true,
    enableTranslation true,
    nativeLanguage en,
    languages [en, es]
  }
  entities Points, BloodPressure, Weight, Preferences 
}

// JDL definition for application 'TwentyOnePoints' generated with command 'jhipster export-jdl'

entity BloodPressure {
  timestamp ZonedDateTime required,
  systolic Integer required,
  diastolic Integer required
}
entity Weight {
  timestamp ZonedDateTime required,
  weight Double required
}
entity Points {
  date LocalDate required,
  exercise Integer,
  meals Integer,
  alcohol Integer,
  notes String maxlength(140)
}
entity Preferences {
  weeklyGoal Integer required min(10) max(21),
  weightUnits Units required
}

enum Units {
  KG,
  LB  
}

relationship OneToOne {
  Preferences{user(login)} to User
}
relationship ManyToOne {
  BloodPressure{user(login)} to User,
  Weight{user(login)} to User,
  Points{user(login)} to User
}

paginate BloodPressure, Weight with infinite-scroll
paginate Points with pagination
```

Then update `src/main/resources/config/application-prod.yml` and find the following configuration for Spring Data Jest:

```yaml
data:
    jest:
        uri: http://localhost:9200
```

Replace it with the following, which will cause Elasticsearch to run in embedded mode.

```yaml
data:
    elasticsearch:
        properties:
            path:
                home: /tmp/elasticsearch
```

Then run `jhipster cloudfoundry`. I answered the questions as follows when prompted.

```
? Name to deploy as: health-points
? Which profile would you like to use? prod
? What is the name of your database service? elephantsql
? What is the name of your database plan? turtle
```

##### **JHipster Version(s)**

```
health-points@0.0.0 /Users/mraible/okta-react-native-spring-boot-example/jhipster-api
└── generator-jhipster@5.4.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "clientPackageManager": "npm",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "es"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.okta.developer",
    "packageFolder": "com/okta/developer",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [
      "protractor"
    ],
    "websocket": false,
    "applicationType": "monolith",
    "baseName": "HealthPoints",
    "authenticationType": "oauth2",
    "buildTool": "gradle",
    "clientFramework": "react",
    "useSass": true,
    "jhipsterVersion": "5.4.2",
    "skipUserManagement": true,
    "cacheProvider": "ehcache",
    "serverPort": "8080"
  },
  "entities": [
    "Points",
    "BloodPressure",
    "Weight",
    "Preferences"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BloodPressure {
  timestamp ZonedDateTime required,
  systolic Integer required,
  diastolic Integer required
}
entity Weight {
  timestamp ZonedDateTime required,
  weight Double required
}
entity Points {
  date LocalDate required,
  exercise Integer,
  meals Integer,
  alcohol Integer,
  notes String maxlength(140)
}
entity Preferences {
  weeklyGoal Integer required min(10) max(21),
  weightUnits Units required
}

enum Units {
  KG,
  LB
}

relationship OneToOne {
  Preferences{user(login)} to User
}
relationship ManyToOne {
  BloodPressure{user(login)} to User,
  Weight{user(login)} to User,
  Points{user(login)} to User
}

paginate BloodPressure, Weight with infinite-scroll
paginate Points with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (Zulu 8.31.0.1-macosx) (build 1.8.0_181-b02)
OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-macosx) (build 25.181-b02, mixed mode)

git version 2.17.1 (Apple Git-112)

node: v8.11.3

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.10.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
After seeing https://github.com/jhipster/generator-jhipster/issues/8169, I tried running `jhipster cloudfoundry` again. This time it succeeded, but it seems it can't connect to my database when I load the site.

<img width="1099" alt="screen shot 2018-10-09 at 1 41 37 pm" src="https://user-images.githubusercontent.com/17892/46694142-1cfce180-cbc9-11e8-84f5-63e558f491f8.png">

**Comment by mraible** [comment]
I was able to solve the problem by removing the properties added in [this commit](https://github.com/jhipster/generator-jhipster/commit/b1020ac3a37c7252405d0e116f59db630c01e4d5#diff-54384bc2a000247e59e6e16cb677fdb0).

```diff
diff --git a/jhipster-api/src/main/resources/config/application-prod.yml b/jhipster-api/src/main/resources/config/application-prod.yml
index 7a35894..49b5537 100644
--- a/jhipster-api/src/main/resources/config/application-prod.yml
+++ b/jhipster-api/src/main/resources/config/application-prod.yml
@@ -30,15 +30,12 @@ spring:
         url: jdbc:postgresql://localhost:5432/HealthPoints
         username: HealthPoints
         password:
-        hikari:
-            auto-commit: false
     jpa:
         database-platform: io.github.jhipster.domain.util.FixedPostgreSQL82Dialect
         database: POSTGRESQL
         show-sql: false
         properties:
             hibernate.id.new_generator_mappings: true
-            hibernate.connection.provider_disables_autocommit: true
             hibernate.cache.use_second_level_cache: true
             hibernate.cache.use_query_cache: false
             hibernate.generate_statistics: false
```

**Comment by jdubois** [comment]
I know this commit (as it's from me), and this gives a nice performance enhancement, normally without causing any issue anywhere. 
From the bug we had earlier it seems that just redeploying the apps make the database binding works -> now your app works, could you try again with the original configuration?
For both issues, that would be a bug on the Cloudfoundry side in my opinion.

**Comment by jdubois** [comment]
We could change them in the cloudfoundry sub-generator - if I remember well there is a specific cloudfoundry profile, so this property just needs to be set up there

**Comment by Tcharl** [comment]
I had exactly the same issue in PCF: sorry to not have filled the issue before.
MRaible, I fixed it by also reinserting the missing line
