### ISSUE TITLE
zipkin.sleuth.sampler.percentage wrong property

### ISSUE THREAD

**Issue by raulrotundo** [jhipster/generator-jhipster#8535]
##### **Overview of the issue**

It looks like spring.sleuth.sampler.percentage property is wrong, the correct one is spring.sleuth.sampler.probability.

Here is the source code that is being used and it is using probability not percentage.

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/SamplerProperties.java

##### **Motivation for or Use Case**

Zipkin does not trace any request.

##### **Reproduce the error**

Generate a micro-services and then open zipkin to monitor your request.

##### **Related issues**

I'm not sure if there is an issue releated with this issue but I found the issue was introduced in the following commit:

https://github.com/jhipster/generator-jhipster/commit/77b1f737487cc129b0e724930906968d90a4e19f#diff-54384bc2a000247e59e6e16cb677fdb0

##### **Suggest a Fix**

Change spring.sleuth.sampler.percentage by spring.sleuth.sampler.probability:1.0 to report 100% of traces.

##### **JHipster Version(s)**

5.4.1

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.sample",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.4.1",
    "applicationType": "microservice",
    "baseName": "sample",
    "packageName": "com.sample",
    "packageFolder": "com/sample",
    "serverPort": "8083",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "XXX",
    "enableTranslation": true,
    "languages": [
      "en",
      "es"
    ],
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
No entities generated.

##### **Browsers and Operating System**

Google Chrome - Version 69.0.3497.100 (Official Build) (64-bit)
Ubuntu 18.04

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
@raulrotundo Thank you so much, I wondered why it why was not working properly and indeed it's because they changed the property name !
