### ISSUE TITLE
v5.4.2 skip user management bug

### ISSUE THREAD

**Issue by spasco** [jhipster/generator-jhipster#8549]
##### **Overview of the issue**

Upon installing jhipster 5.4.2 (skipping user management):

jhipster --skip-user-management

I get the following error:

ERROR Failed to compile with 1 errors 22:02:12

This relative module was not found:

./user-management in ./src/main/webapp/app/shared/reducers/index.ts ✖ ｢wdm｣: 971 modules
ERROR in ./src/main/webapp/app/shared/reducers/index.ts Module not found: Error: Can't resolve './user-management' in '/Users/spasco/code/web/polarisnousers/src/main/webapp/app/shared/reducers' ℹ ｢wdm｣: Failed to compile.

##### **Motivation for or Use Case**

A JHipster 5.4.2 app does not start with "--skip-user-management" enabled.

##### **Reproduce the error**

1. Create a monolithic app with "jhipster --skip-user-management"
2. Select "No" to jhipster registry
3. (for auth) Select JWT auth
4. (for db) Select MongoDB
5. (for cache) Select "No" to spring cache
6. (for build) Select Maven
7. (for other technologies) Select API first development
8. (for web framework) Select React
9 (for SaSS) Select Yes
10. (for il8) Select No
11. (for testing) Select Cucumber and Gatling
12. (other generators) Select No
13. (after app is constructed) run .mvnw

The error will show after completing the above.

##### **Related issues**

No similar issue reported before

##### **JHipster Version(s)**

5.4.2

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
polaris@0.0.0 /Users/spasco/code/web/polarisnousers
└── generator-jhipster@5.4.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.techrisk.seceng"
    },
    "jhipsterVersion": "5.4.2",
    "applicationType": "monolith",
    "baseName": "polaris",
    "packageName": "com.techrisk.seceng",
    "packageFolder": "com/techrisk/seceng",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1 (Apple Git-112)

node: v8.12.0

npm: 6.4.1

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not applicable

##### **Browsers and Operating System**

MacOs

-   [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
I don't understand [this code](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/react/src/main/webapp/app/shared/reducers/index.ts.ejs#L29-L33) why importing a UserManagementState when skipUserManagement is true ?

**Comment by gmarziou** [comment]
Related to https://github.com/jhipster/jhipster-core/issues/268
