### ISSUE TITLE
Gatling with OAuth2 and Keycloak

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#8552]
##### **Overview of the issue**

Gatling tests don't work with OAuth2 and Keycloak

##### **Motivation for or Use Case**

Here the stacktrace:

```
================================================================================
2018-10-13 10:06:39                                          90s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=19397  KO=0     )
> First unauthenticated request                            (OK=100    KO=0     )
> Authentication                                           (OK=100    KO=0     )
> Authentication Redirect 1                                (OK=100    KO=0     )
> patternfly.css Redirect 1                                (OK=100    KO=0     )
> favicon.ico Redirect 1                                   (OK=100    KO=0     )
> patternfly-additions.css Redirect 1                      (OK=100    KO=0     )
> zocial.css Redirect 1                                    (OK=100    KO=0     )
> login.css Redirect 1                                     (OK=100    KO=0     )
> Authenticate                                             (OK=100    KO=0     )
> Authenticate Redirect 1                                  (OK=100    KO=0     )
> Authenticate Redirect 2                                  (OK=100    KO=0     )
> Authenticate Redirect 3                                  (OK=100    KO=0     )
> Authenticate Redirect 4                                  (OK=100    KO=0     )
> Authenticate Redirect 5                                  (OK=100    KO=0     )
> Authenticate Redirect 6                                  (OK=100    KO=0     )
> Authenticate Redirect 7                                  (OK=100    KO=0     )
> Authenticate Redirect 8                                  (OK=100    KO=0     )
> Authenticate Redirect 9                                  (OK=100    KO=0     )
> Authenticate Redirect 10                                 (OK=100    KO=0     )
> Authenticate Redirect 11                                 (OK=100    KO=0     )
> Authenticate Redirect 12                                 (OK=100    KO=0     )
> Authenticate Redirect 13                                 (OK=100    KO=0     )
> Authenticate Redirect 14                                 (OK=100    KO=0     )
> Authenticate Redirect 15                                 (OK=100    KO=0     )
```

##### **Reproduce the error**

I generated the project with JHipster Online:

```
git clone https://github.com/pascalgrimaud/jhipster-test-oauth2
cd jhipster-test-oauth2
npm install
docker-compose -f src/main/docker/keycloak.yml up -d
./mvnw
```

In another Terminal:

```
gatling -sf src/test/gatling/user-files/simulations
```

##### **JHipster Version(s)**

5.4.2 and current master

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/jhipster-test-oauth2
└── generator-jhipster@5.4.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitCompany": "",
    "baseName": "jhipster",
    "packageName": "io.github.jhipster.application",
    "packageFolder": "io/github/jhipster/application",
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "authenticationType": "oauth2",
    "uaaBaseName": "../uaa",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "enableSwaggerCodegen": false,
    "messageBroker": false,
    "buildTool": "maven",
    "useSass": false,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "enableTranslation": false,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientFramework": "angularX",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "5.4.2"
  },
  "git-provider": "GitHub",
  "git-company": "pascalgrimaud",
  "repository-name": "jhipster-test-oauth2"
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Toto {
  name String
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.19.1

node: v8.12.0

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.10.1

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.21.2, build a133471
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@jdubois : as discussed, it doesn't work. It's a part that we don't test with Travis or Azure.

**Comment by jdubois** [comment]
@pascalgrimaud I've added a bug bounty on this

**Comment by pascalgrimaud** [comment]
Thanks @jdubois 
Hope someone will find time to fix it.

**Comment by mraible** [comment]
It used to work. I remember writing it.

**Comment by mraible** [comment]
I tried with Gatling 2.3.1 and it just hangs for me. Not sure why:

```
/opt/tools/gatling/bin/gatling.sh -sf src/test/gatling/user-files/simulations
GATLING_HOME is set to /opt/tools/gatling
TotoGatlingTest is the only simulation, executing it.
Select simulation id (default is 'totogatlingtest'). Accepted characters are a-z, A-Z, 0-9, - and _
```

I ran this for 10 minutes and nothing happens.

**Comment by pascalgrimaud** [comment]
just press enter, then enter again

**Comment by mraible** [comment]
I was able to fix the authentication issue by add `.disableAutoReferer` to `httpConf`.

```
val httpConf = http
    .baseURL(baseURL)
    .inferHtmlResources()
    .acceptHeader("*/*")
    .acceptEncodingHeader("gzip, deflate")
    .acceptLanguageHeader("fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3")
    .connectionHeader("keep-alive")
    .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:33.0) Gecko/20100101 Firefox/33.0")
    .disableAutoReferer
```

Running the app in `prod` mode would likely solve the issue too since there's no redirect-to-referer in prod.

Now I'm setting an issue with CSRF token.

```
2018-10-13 12:22:05.240  WARN 65840 --- [ XNIO-2 task-55] o.z.problem.spring.common.AdviceTrait    : Forbidden: Invalid CSRF Token '0178ed30-a79a-47e3-9e6a-118a089bd216' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'.
2018-10-13 12:22:05.242  WARN 65840 --- [ XNIO-2 task-55] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by handler execution: org.springframework.security.web.csrf.InvalidCsrfTokenException: Invalid CSRF Token '0178ed30-a79a-47e3-9e6a-118a089bd216' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'.
2018-10-13 12:22:09.940  WARN 65840 --- [ XNIO-2 task-35] o.z.problem.spring.common.AdviceTrait    : Forbidden: Invalid CSRF Token '5b476e72-189d-4357-8f71-1f2cfc2cf115' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'.
2018-10-13 12:22:09.942  WARN 65840 --- [ XNIO-2 task-35] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by handler execution: org.springframework.security.web.csrf.InvalidCsrfTokenException: Invalid CSRF Token '5b476e72-189d-4357-8f71-1f2cfc2cf115' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'.
2018-10-13 12:22:11.139  WARN 65840 --- [ XNIO-2 task-44] o.z.problem.spring.common.AdviceTrait    : Forbidden: Invalid CSRF Token 'cd582f5d-01ac-4317-9b8d-5c7ec6b12892' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'.
2018-10-13 12:22:11.140  WARN 65840 --- [ XNIO-2 task-44] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by handler execution: org.springframework.security.web.csrf.InvalidCsrfTokenException: Invalid CSRF Token 'cd582f5d-01ac-4317-9b8d-5c7ec6b12892' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'.
```

**Comment by atomfrede** [comment]
It seems like the xsrf token is not updated after successfull login. At least when looking at the web console the xsrf cookie changes after login and I can see a set cookie response header. Looking further into it.

**Comment by pascalgrimaud** [comment]
@atomfrede : yes, we need to update the xsrf token from the 302 redirect
Thanks for helping to solve this issue. With Julien and Pierre, we need this :)

**Comment by atomfrede** [comment]
You say it the 302 redirect. We don't check for 302 when posting the keycloak formular (we check for 200) and the test doesn't fail :thinking:

**Comment by pascalgrimaud** [comment]
Reading the doc : https://gatling.io/docs/2.3/http/http_protocol/

I tried to play with `disableResponseChunksDiscarding` but didn't have enough time to test everything.

I tried to understand how Keycloak works too, it's new for me. I think the 200 is correct, but there are some 302 which are not catched. So the xsrf is not updated

**Comment by atomfrede** [comment]
Currently playing around with disabling auto redirects. Makes the tests more complicated but I currently see no other options as we can't make any checks on the auto followed redirects as it seems

**Comment by atomfrede** [comment]
Looks like I found a solution. Going to prepare a PR.
![screenshot-20181014140908-769x344](https://user-images.githubusercontent.com/203401/46916408-bf96d500-cfba-11e8-982c-2166f4bf15a8.png)

**Comment by atomfrede** [comment]
We should maybe somewhere document we currently only support gatling 2 and put the link there too as the gatling homepage already pushes gatling 3 (rc4) and I was not able to find a 2.x download there :)

**Comment by pascalgrimaud** [comment]
@atomfrede : oh yes, we need to update the documentation for that. Do you have time to do this ?
The link to download 2.x: https://github.com/PierreBesson/microservice-monitoring-tools-in-action-demo/blob/master/download-gatling.sh

**Comment by atomfrede** [comment]
@pascalgrimaud Yes will do this evening.
