### ISSUE TITLE
Keycloak files not copied for oauth2 microservices

### ISSUE THREAD

**Issue by rainerh** [jhipster/generator-jhipster#8553]
##### **Overview of the issue**

When creating a microservice with oauth2 option, the keycloak docker file and realms are not copied.

##### **Motivation for or Use Case**

When creating a microservice with oauth, I'd like to be able to run the entire service environment with docker-compose -f src/main/docker/app.yml

##### **Related issues**

n/a

##### **Suggest a Fix**

See [PR 8554](https://github.com/jhipster/generator-jhipster/pull/8554)

##### **JHipster Version(s)**

5.4.2 and master
 
##### **JHipster configuration**

```
jhipster@0.0.0 /home/rhermanns/code/jhipster/service
└── generator-jhipster@5.4.2 
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.service",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.4.2",
    "applicationType": "microservice",
    "baseName": "service",
    "packageName": "com.example.service",
    "packageFolder": "com/example/service",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva3VuLXRvLWNoYW5nZS1pbi1wcm9kdVN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true,
    "languages": [
      "en",
      "de"
    ],
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.19.1

node: v10.12.0

npm: 6.4.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

##### **Browsers and Operating System**

OSX

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Are you running your microservices without your gateway? I believe a Gateway is always required (especially to log in). That's why we stopped generating Keycloak files for microservice apps. We were doing it at one point but decided it wasn't necessary.

**Comment by rainerh** [comment]
Matt, I always run the app with a gateway,  that is the reason, why I personally add my gateway container to app.yml for all microservices.
If it is not required for the team, that‘s fine, but then there is a remaining bug in app.yml, where keycloak.yml is still added. See comment in linked PR

**Comment by pascalgrimaud** [comment]
Closing this one as https://github.com/jhipster/generator-jhipster/pull/8675 has been merged.
I think it's resolved
