### ISSUE TITLE
Replace blank page by loading/instruction

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#8564]
##### **Overview of the feature request**

When starting the backend with an IDE (like IntelliJ), there is a beautiful blank page. But there is no information for the user.
That's why we had a ton of tickets since we added the Angular support.

The goal is to display a message which explains what happened, similar to what we had with AngularJS 1, only if the front is not compiled.

##### **Related issues or PR**

A 1st PR was done here: https://github.com/jhipster/generator-jhipster/pull/8558

I opened this ticket, following https://github.com/jhipster/generator-jhipster/pull/8558#issuecomment-429621217 from @jdubois : I'll let you test the solution, add the bounty if you want and close this, if you validate the solution.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Bounty added!

**Comment by deepu105** [comment]
Its already merged and the solution is actually good. So I suggest we close this and you claim the bounty. @jdubois WDYT?

**Comment by jdubois** [comment]
Yes OK, I'll see it today anyway :-)

**Comment by jdubois** [comment]
Seen it and it's cool!!! @sabrinapayet don't forget to claim the bounty
