### ISSUE TITLE
Improve message when the backend is not started

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#8565]
##### **Overview of the feature request**

When the backend is not started, and you started only the front with `npm start`, try to log into the application.
You will see:

![backend-not-started](https://user-images.githubusercontent.com/9156882/46918590-0513cc00-cfd4-11e8-98bb-4af53b3d42d5.png)

The goal would be to replace this message, instead of this default.
This message should not change if the credentials are not correct, of course

##### **Related issues or PR**

Similar to this ticket https://github.com/jhipster/generator-jhipster/issues/8564

I opened this ticket, following #8558 (comment) from @jdubois : I'll let add the bounty if you want.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@fleboulch Are you still working in any PR related with this?

**Comment by fleboulch** [comment]
@DanielFran no I'm not working on it. You can implement it if you want :)

**Comment by wmarques** [comment]
I think this is closed we now have a nice pacman during loading 😄 
@pascalgrimaud is that ok to close this ?

**Comment by pascalgrimaud** [comment]
This enhancement will just help the develop who started the front with `npm start` and not the backend... 
It would be cool to have this, but not necessary. That's why I'm closing this.
Let's focus on Spring Boot 2.1, HTML5, Jar, etc.

@fleboulch : I know you worked on it and waited our feedback about the implementation. I'm really sorry we didn't have the time to analyze / answer to you, hope you understand.
