### ISSUE TITLE
/api/users is admin-only, which causes issues for update screens with relationships to User

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#8570]
##### **Overview of the issue**

The `/api/users` endpoint is admin-only. This means if you create an entity with a many-to-one relationship with `User`, the update screen will fail to load users if you're logged in as a non-admin.

```java
@GetMapping("/users")
@Timed
@Secured(AuthoritiesConstants.ADMIN)
public ResponseEntity<List<UserDTO>> getAllUsers(Pageable pageable) {
```

##### **Motivation for or Use Case**

This is [an issue](https://github.com/mraible/21-points/issues/44) in the v5 version of my 21-Points Health application. Note that my user's drop down is hidden for non-admin users. This is custom logic that I added.

![image](https://user-images.githubusercontent.com/17892/46929464-fd1c5200-cffc-11e8-967a-c886130ee3ff.png)

##### **Reproduce the error**

Create an entity with a one-to-many relationship with `User`, then try to add a new entity when not logged in as an admin.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/2274

##### **Suggest a Fix**

If non-admin users can't get users for the drop down, it should be hidden and the call shouldn't be made. That's better than showing a non-obvious error message.

##### **JHipster Version(s)**

```
21-points@5.0.1 /Users/mraible/dev/21-points
└── generator-jhipster@5.4.2 
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jhipster.health",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.4.2",
    "baseName": "TwentyOnePoints",
    "packageName": "org.jhipster.health",
    "packageFolder": "org/jhipster/health",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "herokuAppName": "health-by-points",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "herokuDeployType": "git"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BloodPressure {
  timestamp ZonedDateTime required,
  systolic Integer required,
  diastolic Integer required
}
entity Weight {
  timestamp ZonedDateTime required,
  weight Double required
}
entity Points {
  date LocalDate required,
  exercise Integer,
  meals Integer,
  alcohol Integer,
  notes String maxlength(140)
}
entity Preferences {
  weeklyGoal Integer required min(10) max(21),
  weightUnits Units required
}

enum Units {
  kg,
  lb
}

relationship OneToOne {
  Preferences{user(login)} to User
}
relationship ManyToOne {
  BloodPressure{user(login)} to User,
  Weight{user(login)} to User,
  Points{user(login)} to User
}

paginate BloodPressure, Weight with infinite-scroll
paginate Points with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (Zulu 8.31.0.1-macosx) (build 1.8.0_181-b02)
OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-macosx) (build 25.181-b02, mixed mode)

git version 2.17.1 (Apple Git-112)

node: v8.11.3

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.10.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

Congratulations, JHipster execution is complete!

**Comment by pascalgrimaud** [comment]
I confirm it. See the commit https://github.com/jhipster/generator-jhipster/commit/625869d48b7ba820633f32bf4715c364fe033bf8#diff-28249db051587f3329b064e738025f25

I'm closing it, as it is resolved in 5.4.2 version.
