### ISSUE TITLE
Java 11 LTS support?

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#8573]
##### **Overview of the feature request**
As JDK 8 will go [end of support on December 2020](https://www.oracle.com/technetwork/java/javase/eol-135779.html#java-commercial-offerings), the current LTS for JDK is now 11.

I saw that JHipster is planned to support every LTS but is currently not supporting 11 whereas it has been released on September 2018 (it's not that long ago though ;) ).

##### **Motivation for or Use Case**

Support every LTS JDK.

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by antarus** [comment]
it seems to me that jhipster will support jdk 11 when spring boot 2.1 will be released

**Comment by jdubois** [comment]
Yes but we first need to wait for Spring Boot to support Java 11... That will be with Spring Boot 2.1, and then we'll start the work (no worries - I'm closing this but it's on our roadmap, of course).

FYI I'm using Java 10 on https://start.jhipster.tech so there shouldn't be much issue.

BTW we need help for this, so if you're ready to contribute, don't hesitate to join us.

**Comment by rishabh9** [comment]
> Hi there;
> Am testing my generated app with Java 11 and it works without problems.
> just update pom like this :
> 
>     1. Java version : `<java.version>11</java.version>`
> 
>     2. Spring Boot version : `<spring-boot.version>2.1.2.RELEASE</spring-boot.version>`
> 
>     3. Add jaxb dependencies :
> 
> 
> ```
>         <dependency>
>             <groupId>org.glassfish.jaxb</groupId>
>             <artifactId>jaxb-runtime</artifactId>
>             <version>2.3.2</version>
>         </dependency>
> ```
> 
>     1. Comment or Remove **maven-enforcer-plugin requireJavaVersion** rule.
> 
>     2. mvn clean build
> 
> 
> **My Env :** Windows 10 64-bit, OpenJDK 11.0.1 64-bit, Apache Netbeans 10, Maven 3.5.2, Spring Boot 2.1.2.RELEASE

This doesn't work for me. Not sure what I am doing wrong. I have followed the exact same steps but I get the following error.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project user-service: Fatal error compiling: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException: javax.xml.bind.JAXBException -> [Help 1]
```

**Comment by jdubois** [comment]
This won't work well until we migrate to Spring Boot 2.1, so that will be for JHipster 6.
