### ISSUE TITLE
"npm update -g generator-jhipster" is not upgrading from 5.4.1 to 5.4.2

### ISSUE THREAD

**Issue by rampantlion103** [jhipster/generator-jhipster#8576]
Here is the actual results from my mac terminal, basing on the how to upgrade jhipster in the 5.4.2 release notes and instructions:

> $ jhipster --version
> Using JHipster version installed globally
> 5.4.1
> $ npm update -g generator-jhipster
> $ jhipster --version
> Using JHipster version installed globally
> 5.4.1

When I ran the jhipster, the warning says that I still have the older version.
 > JHipster update available: 5.4.2 (current: 5.4.1)
 > Run npm install -g generator-jhipster to update.

I tried the npm install also
> $ npm install -g generator-jhipster
> /usr/local/Cellar/node/10.11.0/bin/jhipster -> /usr/local/Cellar/node/10.11.0/lib/node_modules/generator-jhipster/cli/jhipster.js
> generator-jhipster@5.4.2
> updated 1 package in 18.366s
> $ jhipster --version
> Using JHipster version installed globally
> 5.4.1

**Comment by jdubois** [comment]
I'm guessing you are running JHipster inside an existing JHipster project - in that case it will use the local version, which is the one that was used to generate your project.

To upgrade it, you can do `npm install generator-jhipster` (no `-g` as it's not global) or use the `jhipster upgrade` sub-generator (but please read the documentation before, it's more complex).

This is done so you can have several projects with several JHipster versions. Also upgrading JHipster won't break your project, unless you specifically upgrade it.

**Comment by tibistibi** [comment]
with the upgrade guide it only gives an example for global.
i could only upgrade it like this:
npm install generator-jhipster@6.2.0
(from the dir of the project)
