### ISSUE TITLE
Traefik issues, redirect login error

### ISSUE THREAD

**Issue by antarus** [jhipster/generator-jhipster#8578]
##### **Overview of the issue**
Hello,

[ ] 1. when we generate a gateway with keycloack and traefik we access the url of the gateway by `http://localhost/GATEWAY_NAME/`
but when we click on authenticate, we are redirected to
`http://localhost/login`
that does not exist.
[ ] 2. By default, traefik dashboard and gateway ports are in conflict (8080)
it does not pose a problem when we use containers but in development, I use only the container traefik, the application being launched via ./mvnw. the application refusing to launch if traefik is started via the generated configuration.
[ ] 3. If you access a gateway API without being authenticated, you are also redirected to `localhost/login `

##### **Motivation for or Use Case**

Authentication should be functional by default with traefik.

##### **Reproduce the error**
use the jdl configuration and make
`jhipster import-jdl bug.jdl`
build the image
`./mvnw verify -Pprod dockerfile: build`

create a docker folder
go to the docker folder and do
`jhipster docker-compose`
select the `traefik` option

once generation is complete, edit the traefik.yml file and change the default port of the dashboard, which conflicts with the gateway application's default port
replace
`- 8080: 8080`
 by
`- 18080: 8080`
launch the necessary containers:
`docker-compose -f keycloak.yml -f traefik.yml -f consul.yml up`

return to the application folder, execute the command
`. /mvnw`

once the server has started go to the address:
`http://localhost/gateway/`

the application loads, then try to authenticate.
the application tries to redirect us to http://localhost/login`
`404 page not found`

##### **Suggest a Fix**

1. 
- I don't think it's great but it has the merit of working
add the name of the application in the login.services.ts
`location.href = '//' + location.hostname + port + '/GATEWAY_NAME/login';`
- We can also configure traefik to serve the gateway application without context. (/)
There may be consequences to doing that ...
2. change port by default expose in the configuration
3. the suggest for 1 seem to not resolve this problem.

##### **JHipster Version(s)**
5.4.2

##### **JHipster configuration**

<details><summary>jdl</summary>
application {
        config {
        baseName gateway
        applicationType gateway
        authenticationType oauth2
        serviceDiscoveryType consul
    }
}
</details>

##### **Browsers and Operating System**
linux, windows
firefox, chrome, IE

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@antarus could this be related to https://github.com/jhipster/generator-jhipster/issues/7036

**Comment by fw060** [comment]
We are trying to evaluate consul/traefik setup for microservice and seeing the same issue. After updating login.service.ts, I can login properly via keycloak and the redirects work fine. 

My guess is that traefik can not properly handle redirect. Either we need to configure traefik differently or there is a bug in traefik. I just don't know traefik enough. Maybe someone with good knowledge on traefik can help.

**Comment by fw060** [comment]
@DanielFran I was using traefik 1.7.2 and I just tested against 1.7.3. I still see the same problem. 

I was hoping the problem can be fix by going to traefix 1.7.x since there was a fix: https://github.com/containous/traefik/pull/3631. I am new to traefik, maybe this can be fixed by just updating traefik config?

**Comment by antarus** [comment]
it's not a problem with traefik.
I'm sure this is the  `login()` method in `login.service.ts` that does not work the same way as other services

**Comment by antarus** [comment]
i found a solution for point 1 and 3 i do a PR  later ;)

**Comment by antarus** [comment]
@deepu105 do I have to change the default port of the traefik dashboard in this PR or do I do another one?

**Comment by jdubois** [comment]
@antarus if you modify the default ports, please have a look (and update if necessary) this new page: https://www.jhipster.tech/common-ports/

**Comment by antarus** [comment]
@fw060 can you try my PR ?

**Comment by fw060** [comment]
@antarus I just tried your PR by modifying my generated project directly. The change works great with traefik (http://localhost/gateway/) AND without traefik when I expose the gateway directly (http://localhost:8081). 

Thanks a lot for the quick fix. Please let me know if my test is enough or you want me to rebuild jhipster generater from your branch.

**Comment by deepu105** [comment]
@antarus is this ticket still valid, I see there are some PRs merged which points to this, can we close this? next time please open separate issues or do everything in one PR so that we dont keep issues open for ever with partial fix

**Comment by antarus** [comment]
I asked if I had to do a PR or several...
All that remains is the documentation to be merged.
