### ISSUE TITLE
application shouldn't write log to file

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#8582]
##### **Overview of the issue**

The generated `application.yml` has `logging.file` property specified, which causes the log appender to write log to file.

This is not desired for container-based deployment nor appengine.

##### **Motivation for or Use Case**

The log shouldn't be written to file in many cases.

##### **Reproduce the error**

Generate a new monolith application and validate the generated `application.yml`

##### **Suggest a Fix**

Remove `logging.file` property, but add to profiles that actually need it.

##### **JHipster Version(s)**

5.4.2 from master

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
+1 I don't know where this comes from, but we shouldn't write stuff to disk, this should go to the console according to the 12 factors

**Comment by jdubois** [comment]
Oh I understand this is needed to show the logs in the JHipster Registry, maybe even in the JHipster Console - is that correct @PierreBesson @pascalgrimaud ?
I thought this was stored in some kind of in-memory buffer, if that's not the case this feature causes a big trouble, as indeed the log files shouldn't be written to disk.

**Comment by PierreBesson** [comment]
Indeed this was done for the registry (not the console) but I didn't know this was active on prod. Anyway I think we should remove the property because it's not really useful. I noticed the /log endpoint seems to  be  quite useless as it's only sending a small part of the log file and I have not really found a way to send the full log file (correct me if I'm wrong). Moreover we can't know where the user will want to store the logfile so the property should always ne overwritten.

Also by defaut Spring boot will write the logs to /tmp (so they are always written to disk even if the property is not set) it's just that the /log endpoint will not work when the property is not set.

**Comment by PierreBesson** [comment]
See the base Spring boot logback config : https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/base.xml
You see that a file appender is already configured for /tmp. So much for the "12 factors"...

**Comment by kaidohallik** [comment]
Question is what Spring boot logback config files to use. If requirement is not to write logs to disk then instead of base.xml for example this configuration can be used:
```
    <include resource="org/springframework/boot/logging/logback/defaults.xml" />
    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
```

**Comment by pascalgrimaud** [comment]
Closing this, as the PR is merged

**Comment by deepu105** [comment]
@pascalgrimaud @PierreBesson @jdubois this means the log train feature in registry/console will not work anymore. Can we remove those features then?

**Comment by jdubois** [comment]
Or we can add a documentation on those pages to explain how to set this up.
I'm not a big fan but this could be handy for some people, and the work is already done.

**Comment by deepu105** [comment]
Yes agree sometimes they are handy. Another option is to have this only
setup in dev profile, so if anyone wants it in prod they can copy it over
as well. WDYT?

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
@deepu105 : by removing the `logging.properties`, there is only 1 screen which is impacted. It's in the registry logfile component. But the instructions is already there:
https://github.com/jhipster/jhipster-registry/blob/master/src/main/webapp/app/admin/logfile/logfile.component.ts#L38-L49

**Comment by jdubois** [comment]
Thanks @pascalgrimaud - so it's already all OK! I'm just going to modify the text to say it's not configured by default

**Comment by saturnism** [comment]
+1 to @kaidohallik for updating the logback config to not to write to the file either.

i simply disabled the `logging.file` location that's causing trouble, but would like to make sure it's not writing file to `/tmp`
