### ISSUE TITLE
Microservices with uaa auth and ManyToOne relationship to User with services fail to compile.

### ISSUE THREAD

**Issue by jsm174** [jhipster/generator-jhipster#8590]
##### **Overview of the issue**

Similiar to #8550, microservices with uaa authentication and ManyToOne relationship to User with services fail to compile.

Given the following JDL:

```
application {
  config {
    baseName uaa,
    applicationType uaa,
    packageName com.optimoit.ia.uaa,
    authenticationType uaa,
    uaaBaseName "uaa",
    prodDatabaseType mssql,
    buildTool gradle
  }
}

application {
  config {
    baseName gateway,
    applicationType gateway,
    authenticationType uaa,
    uaaBaseName "uaa",
    packageName com.example.gateway,
    prodDatabaseType postgresql,
    clientFramework react,
    buildTool gradle
  }
  entities A, B, C, D
}

application {
  config {
    baseName microservice1,
    applicationType microservice,
    authenticationType uaa,
    uaaBaseName "uaa",
    packageName com.example.microservice1,
    prodDatabaseType postgresql,
    buildTool gradle
  }
  entities A, B
}

application {
  config {
    baseName microservice2,
    applicationType microservice,
    authenticationType uaa,
    uaaBaseName "uaa",
    packageName com.example.microservice2,
    prodDatabaseType postgresql,
    buildTool gradle
  }
  entities C, D
}

entity A {
    data String
}

entity B {
    data String
}

entity C {
    data String
}

entity D {
    data String
}

relationship ManyToOne {
    D{user(login)} to User
}

dto * with mapstruct
service * with serviceImpl

filter D

microservice A, B with microservice1
microservice C, D with microservice2
```

Results in:

```
./gradlew bootWar -Pprod jibDockerBuild

> Task :compileJava
/Users/jsm174/git/jhipster/jh-uaa-reactx-many2one/microservice2/src/main/java/com/example/microservice2/domain/D.java:32: error: cannot find symbol
    private User user;
            ^
  symbol:   class User
  location: class D
/Users/jsm174/git/jhipster/jh-uaa-reactx-many2one/microservice2/src/main/java/com/example/microservice2/domain/D.java:56: error: cannot find symbol
    public User getUser() {
           ^
  symbol:   class User
  location: class D
/Users/jsm174/git/jhipster/jh-uaa-reactx-many2one/microservice2/src/main/java/com/example/microservice2/domain/D.java:60: error: cannot find symbol
    public D user(User user) {
                  ^
  symbol:   class User
  location: class D
/Users/jsm174/git/jhipster/jh-uaa-reactx-many2one/microservice2/src/main/java/com/example/microservice2/domain/D.java:65: error: cannot find symbol
    public void setUser(User user) {
                        ^
  symbol:   class User
  location: class D
/Users/jsm174/git/jhipster/jh-uaa-reactx-many2one/microservice2/src/main/java/com/example/microservice2/service/mapper/DMapper.java:11: error: cannot find symbol
@Mapper(componentModel = "spring", uses = {UserMapper.class})
                                           ^
  symbol: class UserMapper
/Users/jsm174/git/jhipster/jh-uaa-reactx-many2one/microservice2/src/main/java/com/example/microservice2/service/mapper/DMapper.java:11: error: Couldn't retrieve @Mapper annotation
@Mapper(componentModel = "spring", uses = {UserMapper.class})
^
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.17.Final
6 errors
```

##### **JHipster Version(s)**

```
microservice-2@0.0.0 /Users/jsm174/git/jhipster/jh-uaa-reactx-many2one/microservice2
└── generator-jhipster@5.4.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.example.microservice2",
    "packageFolder": "com/example/microservice2",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "microservice2",
    "applicationType": "microservice",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "buildTool": "gradle",
    "jhipsterVersion": "5.4.2",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "hazelcast",
    "serverPort": "8081"
  },
  "entities": [
    "C",
    "D"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity C {
  data String
}
entity D {
  data String
}
relationship ManyToOne {
  D{user(login)} to User
}

dto C, D with mapstruct
service C, D with serviceImpl
microservice C, D with microservice2
filter D

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1 (Apple Git-112)

node: v8.12.0

npm: 6.4.1

yarn: 1.10.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I'm pretty sure relationships to the User in a microservice app is only currently supported for the OAuth2 auth type (correct me if I'm wrong)

**Comment by jsm174** [comment]
The code seems to indicate that but the documention at https://www.jhipster.tech/managing-relationships/ doesn’t mention any limitations on authentication type.

**Comment by deepu105** [comment]
Yes John is right. You can have relationship to user only on gateways
actually, not in microservices at all as they won't have any user domain
objects. I need to check the entity sub gen to confirm

**Comment by sahaliatarek** [comment]
Hi There,
I know this is closed, but just wondering how you can map users to microservices if User entity is just in gateway. what is the right approach to do so?
Thanks
