### ISSUE TITLE
Liquibase DiffChangeLog 

### ISSUE THREAD

**Issue by filiipake** [jhipster/generator-jhipster#8597]
##### **Overview of the issue**
Creating new project and changing from h2 to mysql database. After some changes in entities, I tried to run command `./gradlew liquibaseDiffChangelog -PrunList=diffLog` to generate new changelog, but the task generate wrong changelog.

##### **Suggest a Fix**

```
diffLog {
            driver 'com.mysql.jdbc.Driver'
            url 'jdbc:mysql://localhost:3306/database'
            username 'root'
            password ''
            changeLogFile project.ext.diffChangelogFile
            defaultSchemaName 'database'
            referenceUrl 'hibernate:spring:com.project.domain?dialect=org.hibernate.dialect.MySQL5InnoDBDialect&amp;hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&amp;hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy'
            referenceDefaultSchemaName 'gif'
            logLevel 'debug'
        }
```
I removed classpath from `diffLog`.  and in `dependencies` added:

```
//Liquibase RunTime
    liquibaseRuntime "mysql:mysql-connector-java"
    liquibaseRuntime "org.liquibase:liquibase-core"
    liquibaseRuntime "org.liquibase.ext:liquibase-hibernate5:${liquibase_hibernate5_version}"
    liquibaseRuntime('org.liquibase:liquibase-core:3.6.2')
    liquibaseRuntime('org.liquibase:liquibase-groovy-dsl:2.0.1')
    liquibaseRuntime('org.springframework.boot:spring-boot-starter-data-jpa')
    liquibaseRuntime sourceSets.main.output
```

Now is working!

##### **JHipster Version(s)**
`5.4.2`

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
> changing from h2 to mysql database

How? What do you mean?

**Comment by filiipake** [comment]
> How did you change from h2 to MySQL? If you did manually it's quite normal that the initial generated liquibase config doesn't work
Yeah, I changed manually, but only changing 
```
yeah

**Comment by filiipake** [comment]
> How did you change from h2 to MySQL? If you did manually it's quite normal that the initial generated liquibase config doesn't work

Yeah, I changed manually, but just changing `diffLog` to point to mysql doesnt work.

```
diffLog {
            driver 'com.mysql.jdbc.Driver'
            url 'jdbc:mysql://localhost:3306/database'
            username 'root'
            password ''
            changeLogFile project.ext.diffChangelogFile
            defaultSchemaName 'database'
            referenceUrl 'hibernate:spring:com.project.domain?dialect=org.hibernate.dialect.MySQL5InnoDBDialect&amp;hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&amp;hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy'
            referenceDefaultSchemaName 'gif'
            logLevel 'debug'
        }
```

and adding this on gradle
```
liquibaseRuntime "mysql:mysql-connector-java"
```

I had to add all this on gradle too to get working: 
```
liquibaseRuntime "org.liquibase:liquibase-core"
    liquibaseRuntime "org.liquibase.ext:liquibase-hibernate5:${liquibase_hibernate5_version}"
    liquibaseRuntime('org.liquibase:liquibase-core:3.6.2')
    liquibaseRuntime('org.liquibase:liquibase-groovy-dsl:2.0.1')
    liquibaseRuntime('org.springframework.boot:spring-boot-starter-data-jpa')
    liquibaseRuntime sourceSets.main.output
```

> And what do you mean by it generates a wrong change log?
The task liquibaseDiffChangelog was ignoring my entities and generating empty changelogs, and if database was filled, it generates a changelog to remove all tables of database. I thaught that was wrong config, but if doesnt, please close the issue.
