### ISSUE TITLE
CLI entity command adds to existing liquibase changelog files

### ISSUE THREAD

**Issue by tylerjohnhaden** [jhipster/generator-jhipster#8599]
##### **Overview of the feature request**

*Not sure if this would be considered a bug or feature request, but it's not technically broken.*
When I run the command line `jhipster entity ExistingEntity` on a previously generated entity, the updates to liquibase are added to the existing liquibase changelogs. The feature request would be to use new changelog files with `addColumn`, `dropColumn`, etc. so as not to upset the check sums.

##### **Motivation for or Use Case**

This becomes an issue when the changelog check sums are being stored on a database that you don't want to keep dropping check sum tables every time you push an entity update.

##### **Related issues or PR**

Non that I can find.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
There was several related issues, in particular #5954 with some unfinished work #6016 to implement incremental changelogs, just in case you'd like to contribute.

**Comment by deepu105** [comment]
closing this as the issue has been discussed many times and no point starting all over again, unless someone is willing to continue the work that was started
