### ISSUE TITLE
JDL application options

### ISSUE THREAD

**Issue by rubensa** [jhipster/generator-jhipster#8608]
##### **Overview of the issue**

At [JDL application options](https://www.jhipster.tech/jdl/#application_options) documentation page:

JDL option name | Default value | Possible values | Comment
----------------------|------------------|---------------------|---------------
serviceDiscoveryType | false | eureka, consul, no | 

The *Default value* seems to be wrong as the only accepted values are *eureka, consul, no*.

##### **Motivation for or Use Case**

Fix doc (and possibly implementation).

##### **Reproduce the error**

Using JHipster JDL for vscode (v. 1.3.1) shows error if using value false.

```json
application {
  config {
    serviceDiscoveryType false
  }
}
```

##### **Suggest a Fix**

The easy fix should be changing the value from false to no in Doc

Note:  But...  there seems to be some inconsistency for "don't use" value as some options use "no" and other options use "false".  Default "don't use" values should be revised in order to be consistent.

##### **JHipster Version(s)**

5.5.0

##### **JHipster configuration**

Using JHipster version installed globally
Executing jhipster:info
Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/media/data/rubensa/development/vscode/workspace/autotriaje/monolith
└── generator-jhipster@5.5.0

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v8.11.3

npm: 5.6.0

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.21.2, build a133471

##### **Browsers and Operating System**

Linux 4.15.0-36-generic Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
These inconsistencies are in the generator as well, the JDL reflects those. We should do something about it, definitely.

**Comment by MathieuAA** [comment]
cc @jhipster/developers

**Comment by colameo** [comment]
@rubensa about vscode I will create an issue for you in the [jhipster-ide](https://github.com/jhipster/jhipster-ide/issues) where the extension is maintained.

**Comment by colameo** [comment]
@MathieuAA what shall we do with this? The jdl importer can already handle both values. So I may allow both inputs as valid option values in the JH IDE as well? I want to finish the 1.5 release as I fixed a couple of annoying issues...

**Comment by MathieuAA** [comment]
Allowing both is the only choice right now. I'll work on removing inconsistencies in the generator later...

**Comment by deepu105** [comment]
I think supporting both internally and cleaning up docs to support only `false` would be the best solution.

**Comment by murdos** [comment]
`true`/`false` are fine for every option titled `enableXXX`, but for the following options that are expecting multiple values, wouldn't the value `none` be more accurate as a canonical value? `false` sounds a bit strange (but I'm not a native English speaker...)

Options | Possible values
------------ | -------------
searchEngine | elasticsearch, **false**
serviceDiscoveryType | eureka, consul, **no**
messageBroker | kafka, **false**
prodDatabaseType | mysql, mariadb, mssql, postgresql, oracle, **no**
databaseType | sql, mongodb, cassandra, couchbase, **no**
cacheProvider | ehcache, hazelcast, infinispan, **no**
... | ...

**Comment by deepu105** [comment]
An option would be to add a util method on jhipster-core like below and use that to compute the value for JDL and generator prompts, then update docs to just use `none`
```
const getNoneValue = value => ! ['none', 'NONE', 'no', 'NO', false].includes(value);
```

**Comment by colameo** [comment]
About option: `testFrameworks []` would something like `testFrameworks [none]` not be more consistent with the other options?

**Comment by colameo** [comment]
> About option: `testFrameworks []` would something like `testFrameworks [none]` not be more consistent with the other options?

...from a language design perspective this looks like another way to specify a "do not use" option

**Comment by colameo** [comment]
> An option would be to add a util method on jhipster-core like below and use that to compute the value for JDL and generator prompts, then update docs to just use `none`
> 
> ```
> const getNoneValue = value => ! ['none', 'NONE', 'no', 'NO', false].includes(value);
> ```

I would rather prefer one (clear) way to define an option value rather than different values... the implementation is not a problem (at least in the IDE). Of course it would make the logic for content assist and validation a bit more complex, but that's not main point here.

**Comment by deepu105** [comment]
@colameo I would also prefer that but we can't do that without a breaking version so this is an interim solution for backward compatibility

**Comment by deepu105** [comment]
for content assist and docs we should stick to preferably `none`

**Comment by deepu105** [comment]
for v6 lets standardize everything to use 'none', the enable*, disable* props will continue to use true/false

we will handle `no/false` as a fallback but will not document it

Options | Possible values
------------ | -------------
searchEngine | elasticsearch, **none**
serviceDiscoveryType | eureka, consul, **none**
messageBroker | kafka, **none**
prodDatabaseType | mysql, mariadb, mssql, postgresql, oracle, **none**
databaseType | sql, mongodb, cassandra, couchbase, **none**
cacheProvider | ehcache, hazelcast, infinispan, **none**
... | ...

**Comment by pascalgrimaud** [comment]
It has been opened for a while.
Does someone want to work on this for the v7 ? Otherwise, let's close this and focus on other features

**Comment by rubensa** [comment]
Looks like @MathieuAA and @murdos are looking at this.  See this related issue https://github.com/jhipster/jhipster-core/issues/283

**Comment by pascalgrimaud** [comment]
Only comments / discussion, there is no work on this (unless I'm wrong)
That's why I'm asking this.

**Comment by MathieuAA** [comment]
There's some work for this, but a refactor was needed to do it right. The refactor is done and ready to be merged. The next step is implementing this feature.

**Comment by PierreBesson** [comment]
@MathieuAA do you need a bounty for this feature?

**Comment by MathieuAA** [comment]
Nop, almost done! Thanks anyway

**Comment by MathieuAA** [comment]
Applications can now have options in their declaration (cc @colameo), I believe there's another issue about value standardization ('no', false, etc.) in JCore and referenced in the v7 roadmap.
What I propose is to open an issue about value standardization with the info from here and close this one

**Comment by colameo** [comment]
@MathieuAA I'm completely redesigning the option part in the JH IDE project and want to talk with you about this topic. As we already discussed last year, from my point of view we need also a workflow for language changes otherwise people will end up with inkongruent behaviour in the tooling which of course confuses. I will contact you by mail.

**Comment by MathieuAA** [comment]
@avdev4j Unless you have an objection, I'm gonna add this issue to the v7 project list.

**Comment by avdev4j** [comment]
It's made to be alive along the v7 is in progress :).

Feel free to add what you think is important

**Comment by MathieuAA** [comment]
@murdos any objection if I take it?

**Comment by murdos** [comment]
> 
> 
> @murdos any objection if I take it?

Not at all!

**Comment by MathieuAA** [comment]
There are some things we can do to improve the overall "option handling" experience:
  - fix option values according to their types (what this is issue is originally about)
  - use the affirmative form instead of a mix of the two (enableTranslation vs skipClient)

I'll create separate issues for the two points to detail everything. I plan to use them for JCode.

**Comment by DanielFran** [comment]
Reopening issue since @MathieuAA created a PR but it is yet done

**Comment by MathieuAA** [comment]
A non-breaking version can be done before breaking things, so I suggest not to keep it mandatory for v7.
Also, I fear I won't be able to make it due to the lack of time I'm facing :( so if anyone wants to tackle it, be my guest

**Comment by deepu105** [comment]
@MathieuAA this issue is not done right? Should we reopen it?

**Comment by MathieuAA** [comment]
The cleaning up of the values, according to their "type" isn't (no, false etc.). This is a huge refactoring :(
The improvement is though (the use ABC syntax). So yes, for me we can close this one.

**Comment by MathieuAA** [comment]
Sorry, forgot to write: another issue should be opened for the sole purpose of cleaning up falsy values. This issue is too bloated to read

**Comment by colameo** [comment]
...for that reason we made the [jhipster-base](https://github.com/jhipster/jhipster-base) project. In the jh ide all options (application, deployment etc) are maintained based on the models (json files) from that project. However, I know it costs effort to integrate those models in the core components but after that we will benefit of maintaining all options centrally - just my two cents.

**Comment by pascalgrimaud** [comment]
@colameo : what is the state of this project today? Is it used?

I'm asking because I added Vue.js support, removed uaa support, but I didn't do any change there. So maybe I should?

**Comment by colameo** [comment]
> @colameo : what is the state of this project today? Is it used?
> 
> I'm asking because I added Vue.js support, removed uaa support, but I didn't do any change there. So maybe I should?

the purpose of this project was to keep JDL options in sync for all dependent jhipster projects like JH IDE, generator etc.
This to avoid inconsistency in the tooling (which we had quite often). In other words, if we have options in JDL which are not in the jhipster-base json files users of the JH IDE will not be able to define them via content assist and a validation error will also prevent this. So it's quite important to keep those models up to date.

**Comment by colameo** [comment]
...and BTW even the documentation of all options can be maintained easily. Have a look to the linked MD files in the [README](https://github.com/jhipster/jhipster-base/blob/main/README.md). They are all generated automatically :-)

**Comment by pascalgrimaud** [comment]
@colameo : ok, then in this case, `jhipster-base` is out-dated:
- Vue.js is not a blueprint anymore
- UAA support will be deleted soon
- and some other stuff probably

**Comment by pascalgrimaud** [comment]
First PR to remove UAA here: https://github.com/jhipster/jhipster-base/pull/20

**Comment by pascalgrimaud** [comment]
> ...for that reason we made the jhipster-base project. In the jh ide all options (application, deployment etc) are maintained based on the models (json files) from that project. However, I know it costs effort to integrate those models in the core components but after that we will benefit of maintaining all options centrally - just my two cents.

I understand the reason of this project. Anyway, I still think it's better for the long life of JHipster to be in 1 single repository, as suggested several times by @PierreBesson 
We have too much parallel projects, and all of them are not enough maintained. Using a mono repository will help us a lot.

**Comment by mraible** [comment]
Closing because @pascalgrimaud's last comment (on Jan 24, 2021) seems to indicate this issue is resolved.
