### ISSUE TITLE
how to use import jdl and blueprint together

### ISSUE THREAD

**Issue by aman048** [jhipster/generator-jhipster#8610]
like:
jhipster --blueprint my-generators import-jdl test.jdl

**Comment by deepu105** [comment]
Its just about passing the blueprint value to sub generators. I'm not sure if it's already done, else I'll do it soon

**Comment by deepu105** [comment]
Actually, this also needs to be supported by jhipster-core in order to be complete

**Comment by brunnels** [comment]
this works as is if the blueprint is already defined in the .yo-rc.json like so:
`"blueprint": "generator-jhipster-mine"`
then you just call import-jdl like normal without the --blueprint parameter.

**Comment by MathieuAA** [comment]
Since the blueprint option is available in a JDL application, can this be closed?

**Comment by murdos** [comment]
@MathieuAA The blueprint option is indeed available, but I don't think it is used. 
I'll check it later: this ticket is on my TODO list. 
But I want to work first on another unrelated issue: make sure the upgrade subgenerator behaves as intended when a blueprint is involved.

**Comment by murdos** [comment]
Already works fine according to my tests.

**Comment by yelhouti** [comment]
Sorry guys, but I having the same issue:
The problem happens in the generated index.js: `This is a JHipster blueprint and should be used only like...` when trying to override `entity-client` specifically.
the `jhContext` is undefined.
Any idea on how to fix this please. Thanks

**Comment by murdos** [comment]
@yelhouti I can't help if you don't provide more information: JHipster version, extract of jdl and blueprint used, ... in order to reproduce the issue.

**Comment by yelhouti** [comment]
My bad:
.yo-rc
```
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.elhouti.jhipster.primeng",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.8.1",
        "applicationType": "monolith",
        "baseName": "jhipster",
        "packageName": "com.elhouti.jhipster.primeng",
        "packageFolder": "com/elhouti/jhipster/primeng",
        "serverPort": "8080",
        "authenticationType": "session",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "gradle",
        "enableSwaggerCodegen": false,
        "rememberMeKey": "bcb1139466575094fd1c1d5e6ed92729f45e85d751030361e84676761d6c0436190e23fafcd0a3c1d7085651121deae4f329",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [
            {
                "name": "generator-jhipster-primeng-blueprint",
                "version": "0.0.0"
            }
        ],
        "enableTranslation": true,
        "clientPackageManager": "npm",
        "nativeLanguage": "en",
        "languages": ["en", "fr"],
        "blueprint": "generator-jhipster-primeng-blueprint",
        "blueprintVersion": "0.0.0"
    },
    "generator-jhipster-primeng-blueprint": {
        "jhipsterVersion": "5.8.1",
        "applicationType": "monolith",
        "baseName": "jhipster",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "enableTranslation": true
    }
}

```

**Comment by WiteCastle** [comment]
Wait, so is there a blueprints option when configuring the application in the JDL? If so, is it just not in the docs? (https://www.jhipster.tech/jdl/applications). 

Or do we have to have a valid .yo-rc file and then import a JDL for this to work? If so, what should teams that use JDLs solely for application creation do?

**Comment by MathieuAA** [comment]
@WiteCastle Hello there. The `blueprints` option is yet to be implemented in the JDL.

**Comment by WiteCastle** [comment]
@MathieuAA Thanks for the response but quick question. Why is this issue closed? Are there plans to enable this feature as discussed earlier in the thread? Or are we waiting for a pull request? I can attempt to help with this (even with my beginner knowledge of yo generators).

**Comment by MathieuAA** [comment]
This is an old issue, don't worry.
Head to the JCore repo instead, you'll find what you need.

**Comment by deepu105** [comment]
And if you wanna work on it you are welcome to do so and would be much
appreciated :)

**Comment by 62mkv** [comment]
so, to summarize: a "blueprint" (singular) has been in JHipster JDL since v3.something

But for "blueprints" (plural) this is an open issue: https://github.com/jhipster/jhipster-core/issues/415

**Comment by MathieuAA** [comment]
I'll close the issue as this is implemented.
