### ISSUE TITLE
React Gateway with Gitlab ci-cd frontend-test job failure - jest snapshots 

### ISSUE THREAD

**Issue by jsm174** [jhipster/generator-jhipster#8612]
##### **Overview of the issue**

Not sure if this is an issue, but I didn't see anything in documentation that explained jest, snapshots, and ci-cd.

We are using the ci-cd generator to build a `.gitlab-ci.yml` configuration. Out of the box, with a fresh 5.5.0 gateway, the build will fail with the following:

```
      56 |     const component = wrapper();
      57 |     // the created snapshot must be committed to source control
    > 58 |     expect(component).toMatchSnapshot();
         |                       ^
      59 |     expect(component.find(LoadingBar).length).toEqual(1);
      60 |     const navbar = component.find(Navbar);
      61 |     expect(navbar.length).toEqual(1);

      at Object.<anonymous> (src/test/javascript/spec/app/shared/layout/header/header.spec.tsx:58:23)

  ??? Header ??? Renders a Header component in prod profile with LoadingBar, Navbar, Nav.

    expect(value).toMatchSnapshot()

    New snapshot was not written. The update flag must be explicitly passed to write a new snapshot.

    This is likely because this test is run in a continuous integration (CI) environment in which snapshots are not written by default.

```

I've seen some issues suggesting snapshots should be checked into the repository.

Anyway, I did some tests, and by adding a new `test-ci` command to `package.json`:

```
    "test": "npm run lint && jest --coverage --logHeapUsage -w=2 --config src/test/javascript/jest.conf.js",
    "test-ci": "npm test -- --updateSnapshot",
```

And then updating gitlab-ci.yml:

```
frontend-test:
    stage: test
    script:
        - ./gradlew npm_run_test-ci -PnodeInstall --no-daemon
    artifacts:
        reports:
            junit: build/test-results/jest/TESTS-*.xml
        paths:
            - build/test-results/
            - build/jacoco/
        expire_in: 1 day
```

I was able to get through the `frontend-test` job. 

If this seems like an appropriate fix, I would be willing to work on a PR.

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/jsm174/git/cicd/gateway
└── generator-jhipster@5.5.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.example.gateway",
    "packageFolder": "com/example/gateway",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "gateway",
    "applicationType": "gateway",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "clientFramework": "react",
    "buildTool": "gradle",
    "jhipsterVersion": "5.5.0",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "cacheProvider": "hazelcast",
    "serverPort": "8080",
    "useSass": true
  },
  "entities": [
    "A",
    "B",
    "C",
    "D"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity A {
  data String
}
entity B {
  data String
}
entity C {
  data String
}
entity D {
  data String
}
dto A, B, C, D with mapstruct
service A, B, C, D with serviceImpl
microservice A, B with microservice1
microservice C, D with microservice2
filter D

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1 (Apple Git-112)

node: v8.12.0

npm: 6.4.1

yarn: 1.10.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Not sure, but if you do `--updateSnapshot` in your ci environment the test will never fail (but not 100% sure how the snapshot test work), because if there is a failure the snapshots are updated and the test will be green, which is properly not what you want.

**Comment by jsm174** [comment]
@atomfrede Thanks. I totally agree. 

It would be great to have some clarity on best practices somewhere in the code/docs.

**Comment by deepu105** [comment]
The idea is that you need to run those tests atleast once locally and
commit the generated snapshots. If you want to run ci on a app as soon as
generated then it's tricky as having updateSnapshot enabled beats the
purpose. I guess the best solution is documentation. Unfortunately I don't
have much time now so if someone can write the docs I'll be greateful. I
can do the review

**Comment by atomfrede** [comment]
Let me check over the weekend
