### ISSUE TITLE
Activation link is not authorized after registration with UAA

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#8617]
##### **Overview of the issue**

Create a micro-service system with the following micro-service:

- [JHipster UAA](https://www.jhipster.tech/using-uaa/) for authentication and user management
- JHipster Application for business logic
- [JHipster Gateway](https://www.jhipster.tech/api-gateway/) for UI
- [JHipster Registry](https://www.jhipster.tech/jhipster-registry/) from monitoring and cofiguration

When there is a new registration for a new user, I receive the email invitation from the UAA with the activation link.

Clinking on the link, it appears the JHipster Gateway but the new user is not activated.
Checking with the development tool of Chrome, it is possible to see in the "Network" tab that the request failed with HTTP status code 401 Not Authorized

This problem is present with brand new micro-services just created with JHipster Generator without any modification

##### **Motivation for or Use Case**

Registration / Creation of new users can receive activation emails but they cannot be activated and access to the application

##### **Reproduce the error**

Simply create the following micro-services using JHipster Generator with the usage of [JHipster Registry](https://www.jhipster.tech/jhipster-registry/) for all of them:

- [JHipster UAA](https://www.jhipster.tech/using-uaa/) for authentication and user management
```
Welcome to JHipster v5.5.0
Application files will be generated in folder: /home/alex/Development/workspace/jhipster/test-uaa-550
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

? Which *type* of application would you like to create? JHipster UAA server (for microservice OAuth2 authentication)
? What is the base name of your application? TestUaa
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 9999
? What is your default Java package name? com.kekse.mystaff
? Which service discovery server do you want to use? JHipster Registry (uses Eureka, provides Spring Cloud Config support and monitoring dashboards)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? Which *production* database would you like to use? MySQL
? Which *development* database would you like to use? MySQL
? Do you want to use the Spring cache abstraction? Yes, with the Hazelcast implementation (distributed cache, for multiple nodes)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? Search engine using Elasticsearch
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install Farsi, French, Galician
? Besides JUnit and Jest, which testing frameworks would you like to use? Gatling
? Would you like to install other generators from the JHipster Marketplace? No
```

- JHipster Application for business logic

- [JHipster Gateway](https://www.jhipster.tech/api-gateway/) for UI
```
Welcome to JHipster v5.5.0
Application files will be generated in folder: /home/alex/Development/workspace/jhipster/test-gateway-550
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

? Which *type* of application would you like to create? Microservice gateway
? What is the base name of your application? TestGateway
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8080
? What is your default Java package name? com.kekse.mystaff
? Which service discovery server do you want to use? JHipster Registry (uses Eureka, provides Spring Cloud Config support and monitoring dashboards)
? Which *type* of authentication would you like to use? Authentication with JHipster UAA server (the server must be generated separately)
? What is the folder path of your UAA application? ../test-uaa-550
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? Which *production* database would you like to use? MySQL
? Which *development* database would you like to use? MySQL
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? Search engine using Elasticsearch
? Which *Framework* would you like to use for the client? Angular 6
? Would you like to enable *SASS* stylesheet preprocessor? Yes
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install French, Italian
? Besides JUnit and Jest, which testing frameworks would you like to use? Gatling, Protractor
? Would you like to install other generators from the JHipster Marketplace? No
```

Configure MySQL connection for all the micro-services in `application-dev.yml`.
Configure the UAA to be able to send emails. I used my Gmail account as tests.

Run all of them with `./mvnw`

Access to the default portal at `http://localhost:8080/#/` and try to register a new user from the homepage.
You should receive the email although the registration page says that there was an error and to retry it later (I think also in this phase there is a problem but I didn't figure it out properly).

Access the activation email and click on the link inside.
The user won't be activated and won't be able to login.

##### **Related issues**

I did not find anything related to this issue

##### **Suggest a Fix**

As mentioned earlier, in the development console of Chrome it says that the request to the UAA was unauthorized (it returns 401). I guess the issue is related to the security configuration of the UAA. Maybe in one of the following Java classes:

- UaaConfiguration
- UaaWebSecurityConfiguration

I am not sure 100% because I did not investigate it properly but I just made few tests to see if it was my problem or not.

##### **JHipster Version(s)**

JHipster v5.5.0

##### **JHipster configuration**

Above you can find my answers to create the UAA and the Gateway using JHipster Generator.
I hope those info are enough

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

I did not create any entity but I have tried only the registration mechanism

##### **Browsers and Operating System**

I used only Chrome

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
@alexsintoni Thanks for reporting.  In the future, please include your `.yo-rc.json` files instead of the prompt answers - they show the same info but we can generate the same project from the json file.

The issue is [a 401 redirects to home](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts.ejs#L53-L70) for UAA apps, and the activate route requests the account on enter (which always gives a 401 if not logged in).  Same issue as https://github.com/jhipster/generator-jhipster/issues/7773
