### ISSUE TITLE
Console Error from "jhipster-error" code

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#8619]
##### **Overview of the issue**
After loading the app and waiting 4 seconds, an error is logged to the console.  It's caused by [the new code in index.html](https://github.com/jhipster/generator-jhipster/blob/eddc134ba7aec85c5214d40892e3d5a4d5c0cec7/generators/client/templates/angular/src/main/webapp/index.html.ejs#L93-L101).  Affects both `dev` and `prod`

    Uncaught TypeError: Cannot read property 'style' of null
        at showError ((index):8)
        at t.invokeTask (0.5d276ac7348b4dad830c.chunk.js:1)
        at e.runTask (0.5d276ac7348b4dad830c.chunk.js:1)
        at e.invokeTask (0.5d276ac7348b4dad830c.chunk.js:1)
        at i.useG.invoke (0.5d276ac7348b4dad830c.chunk.js:1)
        at n.args.(:8080/anonymous function) (http://localhost:8080/app/0.5d276ac7348b4dad830c.chunk.js:1:941445)

##### **Motivation for or Use Case**
There shouldn't be a console error on a new app.

##### **Reproduce the error**
Generate and run an app, wait 4 seconds, then check the console.

##### **Suggest a Fix**
I'm not familiar with this section of the code, maybe add an `if` statement checking for the element before adding a style to it.

##### **JHipster Version(s)**
Master, v5.5.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "websockets",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

<details>
<summary>Environment and tools </summary>

<pre>
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.18.0

node: v8.11.4

npm: 6.4.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f
</pre>
</details>

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Fixed. Saw it yesterday but thought it had something to with my experiments regarding https://github.com/jhipster/generator-jhipster/issues/8498
