### ISSUE TITLE
liquibase can't access the classes so it deletes the entire db

### ISSUE THREAD

**Issue by rabiori** [jhipster/generator-jhipster#8622]
##### **Overview of the issue**

After making any JPA changes, running `./gradlew -Pprod liquibaseDiffChangelog -PrunList=diffLog    ` either creates an empty changeset, or deletes the entire db if there were any previous modifications.

##### **Motivation for or Use Case**

Because it it should create a new change to apply, and not delete all the previous changes.

##### **Reproduce the error**

1. create a new project with SQL and gradle.
2. add a new Entity in your domain with JPA.
3. run `./gradlew -Pprod liquibaseDiffChangelog -PrunList=diffLog`

##### **Suggest a Fix**

In `build.gradle` in the liquibase component, changing the classpath from `classpath 'src/main/resources/'` to `classpath 'build/classes/java/main'` fixed the issue.
In the generator should be fixed [here](https://github.com/jhipster/generator-jhipster/blob/c7867c2b6dd821fc31c5d88a80fb328d06febfc0/generators/server/templates/build.gradle.ejs#L194) and [here](https://github.com/jhipster/generator-jhipster/blob/c7867c2b6dd821fc31c5d88a80fb328d06febfc0/generators/server/templates/build.gradle.ejs#L205).

##### **JHipster Version(s)**

```
for-bug-report@0.0.0 /Users/orirabi/git-repos/dummy/forBugReport
└── generator-jhipster@5.5.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "forBugReport",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity NewEntity {
  newField String
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1 (Apple Git-112)

node: v8.12.0

npm: 6.4.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

##### **Browsers and Operating System**

Mac, Chrome

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Will look into it. Thx for the report.

**Comment by standors** [comment]
I had the same issue. This is only with Gradle plugin. From this reason I moved to Maven and it works.

**Comment by pascalgrimaud** [comment]
closing this, as the PR https://github.com/jhipster/generator-jhipster/pull/8637 has been merged
