### ISSUE TITLE
Release 5.5.0 'io.github.jhipster:jhipster-dependencies' version should be 2.0.27

### ISSUE THREAD

**Issue by unikzforce** [jhipster/generator-jhipster#8625]
##### **Overview of the issue**

upgraded the project and some errors appeared. apparently jhipster-dependencies library version has not been upgraded to latest ... so some errors Showed up for example In `DatabaseConfiguration`.

I also double checked this in generating a whole new project. the `jhipster-dependencies` version is still `2.0.22` over there. I upgraded to `2.0.27` and all errors has been resolved.

##### **Suggest a Fix**
in `gradle.properties` change `jhipster-dependencies` version to `2.0.27`

##### **JHipster Version(s)**
5.5.0

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "net.marjaa.educationalmanagement",
      "nativeLanguage": "fa"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "microservice",
    "baseName": "EducationalManagement",
    "packageName": "net.marjaa.educationalmanagement",
    "packageFolder": "net/marjaa/educationalmanagement",
    "serverPort": "8003",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "consul",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "-------",
    "enableTranslation": true,
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "nativeLanguage": "fa",
    "languages": [
      "fa",
      "en"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by unikzforce** [comment]
My other question is what happend to constructor injections fields. they are no longer final? i couldn't find any issue to read about it.

**Comment by ruddell** [comment]
@unikzforce The v5.5.0 release of the generator [uses `2.0.26`](https://github.com/jhipster/generator-jhipster/blob/v5.5.0/generators/server/templates/gradle.properties.ejs#L28), and the current master [uses `2.0.27`](https://github.com/jhipster/generator-jhipster/blob/c9d870931f087b7eb017e01dea0f30081c2b01d5/generators/server/templates/gradle.properties.ejs#L28).  I'm not sure how you generated old code, are you sure your global generator is using the latest v5.5.0?  Also how did you upgrade your app?

About your second comment, the `final` keyword was fixed in https://github.com/jhipster/generator-jhipster/pull/8601

**Comment by unikzforce** [comment]
`jhipster --version` shows me:
```
Using JHipster version installed globally
5.5.0
```
my last jhipster was 5.3.4 i guess.
`npm update -g generator-jhipster` didn't work for me and exited immediately without any error or output.
so i used `yarn global upgrade generator-jhipster` and it updated the global `generator-jhipster`. and after that i checked the global version. it was `5.5.0`.
then i went to my project directory and executed `jhipster upgrade`.

for me `final` was not fixed in `5.5.0` and some of my constructor injections missed the keyword.
also for me `jhipster-dependencies` was still `2.0.22`..

These problems were not specific to `update` ... they also appeared in creating a whole new applicationS:
![screenshot from 2018-10-22 17-05-36](https://user-images.githubusercontent.com/7010566/47295541-bf32b580-d61c-11e8-9690-8cdb55f05eb5.png)

gradle.properties:
![image](https://user-images.githubusercontent.com/7010566/47295588-dd001a80-d61c-11e8-9dbd-ccfb6bdc06bc.png)

And after creating an entity with cli:
![image](https://user-images.githubusercontent.com/7010566/47295699-2b151e00-d61d-11e8-9674-a15a13fd96d2.png)

`YesServiceImpl.java` has no final keyword behind `YesRepository` in line 27:
![image](https://user-images.githubusercontent.com/7010566/47295772-5b5cbc80-d61d-11e8-86cb-6e19412ac90e.png)

**Comment by unikzforce** [comment]
`jhipster --version` shows me `5.5.0`
at first i tried `npm update -g generator-jhipster` but it returned immediately without error or any output. so i tried with `yarn global upgrade generator-jhipster` . it did the job.

then i upgraded my project using `jhipster upgrade`.
at first i thought that maybe my upgrade process has been broken, so for making sure , i've just created a whole new application but these two problems ( jhipster-dependencies && missing final keyword ) were still there.

created a whole new application:

![screenshot from 2018-10-22 17-05-36](https://user-images.githubusercontent.com/7010566/47296378-ec806300-d61e-11e8-9540-aa4c404acb1e.png)

`gradle.properties`:

![image](https://user-images.githubusercontent.com/7010566/47296409-0752d780-d61f-11e8-9276-3afd8d6094b8.png)

and then i created a new Enitity using `jhipster entity Yes`:

![image](https://user-images.githubusercontent.com/7010566/47296463-2ea9a480-d61f-11e8-8ba2-0e2d270e7e49.png)

the final keyword is still missing in `YesServiceImpl.java`:

![image](https://user-images.githubusercontent.com/7010566/47296534-5b5dbc00-d61f-11e8-98a3-34ab912c8f73.png)

**Comment by ruddell** [comment]
The `final` keyword fix has not been released yet.

I still have no idea how you get old templates with the new version.  I'm guessing it's related to installing with both `npm` and `yarn`.  Try uninstalling with both and only installing with `npm install -g generator-jhipster`

**Comment by PierreBesson** [comment]
Looks like a config setup issue so I'm closing.
@unikzforce you can run `which jhipster` to know the path of the jhipster script that is actually running when using the jhipster command. Also to get the latest version what works all the time is using `npx jhipster` 😃 .

**Comment by unikzforce** [comment]
it problem was from yarn.. it was on 1.7.0 ... and after i'v upgraded yarn to 1.10.1 (using npm) and upgrading jhipster again using `yarn global upgrade generator-jhipster` the problem has been resolved.
sometimes yarn and npm creates such problems ..
