### ISSUE TITLE
Invalid session locks users out with HTTP 500.  Server log says UT000010: Session is invalid

### ISSUE THREAD

**Issue by fil512** [jhipster/generator-jhipster#8627]
##### **Overview of the issue**

Browser sends request to server with invalid Session.  Server returns HTTP ERROR 500 and logs the following stack trace on the server:

2018-10-21 18:26:33.901 ERROR 1 --- [  XNIO-2 task-7] io.undertow.request                      : UT005023: Exception handling request to /
wgrserver-app_1         |
wgrserver-app_1         | java.lang.IllegalStateException: UT000010: Session is invalid 9b_OLbDyElq33A8aN-7i2Fi8IxsqDaVGijPpGkVz
wgrserver-app_1         |       at io.undertow.server.session.InMemorySessionManager$SessionImpl.getAttribute(InMemorySessionManager.java:511)
wgrserver-app_1         |       at io.undertow.servlet.util.SavedRequest.tryRestoreRequest(SavedRequest.java:155)
wgrserver-app_1         |       at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:74)
wgrserver-app_1         |       at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
wgrserver-app_1         |       at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
wgrserver-app_1         |       at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
wgrserver-app_1         |       at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
wgrserver-app_1         |       at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
wgrserver-app_1         |       at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
wgrserver-app_1         |       at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
wgrserver-app_1         |       at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
wgrserver-app_1         |       at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
wgrserver-app_1         |       at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
wgrserver-app_1         |       at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
wgrserver-app_1         |       at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
wgrserver-app_1         |       at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
wgrserver-app_1         |       at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
wgrserver-app_1         |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
wgrserver-app_1         |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
wgrserver-app_1         |       at java.lang.Thread.run(Thread.java:748)

If it helps, here is my SecurityConfiguration.configure()

   @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .addFilterBefore(corsFilter, UsernamePasswordAuthenticationFilter.class)
            .exceptionHandling()
            .authenticationEntryPoint(problemSupport)
            .accessDeniedHandler(problemSupport)
        .and()
            .csrf()
            .disable()
            .headers()
            .frameOptions()
            .disable()
        .and()
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        .and()
            .authorizeRequests()
            .antMatchers("/api/register").permitAll()
            .antMatchers("/").permitAll()
            .antMatchers("/error").permitAll()
            .antMatchers("/api/activate").permitAll()
            .antMatchers("/api/authenticate").permitAll()
            .antMatchers("/api/rocket_chat_iframe").permitAll()
            .antMatchers("/api/rocket_chat_auth_get").permitAll()
            .antMatchers("/api/account/reset-password/init").permitAll()
            .antMatchers("/api/account/reset-password/finish").permitAll()
            .antMatchers("/api/**").authenticated()
            .antMatchers("/management/health").permitAll()
            .antMatchers("/management/info").permitAll()
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN)
            .antMatchers("/v2/api-docs/**").permitAll()
            .antMatchers("/swagger-resources/configuration/ui").permitAll()
            .antMatchers("/swagger-ui/index.html").hasAuthority(AuthoritiesConstants.ADMIN)
        .and()
            .apply(securityConfigurerAdapter());

    }

##### **Motivation for or Use Case**

The only workaround for the user is to log into the server in incognito mode.

##### **Reproduce the error**

Stay logged in longer than the session timeout configured for the server, then navigate to /.

##### **JHipster Version(s)**

5.1.0

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
wgr-server@0.0.0 C:\Users\Ken\git\wgr\wgr-server
`-- generator-jhipster@5.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.wargameroom"
    },
    "jhipsterVersion": "5.0.2",
    "applicationType": "monolith",
    "baseName": "wgrServer",
    "packageName": "com.wargameroom",
    "packageFolder": "com/wargameroom",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Boardgame (boardgame) {
  name String required,
  minPlayers Integer,
  maxPlayers Integer,
  clientFilename String
}
entity GamePlay (game_play) {
  name String required,
  rated Boolean required,
  started Instant required,
  turncount Integer required,
  ended Instant,
  lastMove Instant,
  scenario String,
  timeAllowed Integer,
  victoryReason String,
  clientVersion String
}
entity Player (player) {
  realName String,
  phoneNumber String
}
entity Seat (seat) {
  joinNumber Integer required,
  playerNumber Integer,
  side String,
  role String,
  won Boolean,
  score Integer
}
entity Move (move) {
  line String
}
entity CrashReport (crash_report) {
  datetime Instant required,
  message String,
  gameplayId Long,
  game String,
  gameplay String,
  version String,
  player String,
  stackTrace TextBlob
}
entity Ranking (ranking) {
  rating Integer,
  gamesPlayed Integer
}
entity ChatMessage (chat_message) {
  message String,
  datetime Instant required
}
entity StackTraceElement (stack_trace_element) {
  line String
}
relationship OneToOne {
  Player{user(login) required} to User
}
relationship ManyToOne {
  GamePlay{createdBy(login) required} to User,
  GamePlay{winner(login)} to User,
  GamePlay{turn(login)} to User,
  GamePlay{game(name) required} to Boardgame,
  Seat{playing(login) required} to User,
  Seat{gameplay required} to GamePlay,
  Move{playedBy(login) required} to User,
  Move{gameplay required} to GamePlay,
  Ranking{player(login) required} to User,
  Ranking{game(name) required} to Boardgame,
  ChatMessage{player(login) required} to User,
  StackTraceElement{crash required} to CrashReport
}

service Boardgame, GamePlay, Player, Seat, Move, CrashReport, Ranking, ChatMessage, StackTraceElement with serviceImpl
filter Seat, Move, Ranking
paginate ChatMessage with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.18.0.windows.1

node: v10.7.0

npm: 6.1.0

yarn: 1.10.1

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

see above

##### **Browsers and Operating System**

Chrome.  Server is Debian GNU/Linux 8.

**Comment by jdubois** [comment]
I don't get it, you're using JWT and have expressively a stateless mechanism (so no session), which is our default settings - how come you use a session? Did you modify some of the generated code? How does this happen? Like all the time at login, or after 10 minutes??

**Comment by fil512** [comment]
I see my mistake.  Thanks.

**Comment by fil512** [comment]
Perhaps I closed this prematurely.  The mistake I made is I call request.getSession().setAttribute(..) in one of my REST handlers.  I guess this is inadvertently creating a session that mostly works, until it doesn't.

JHipster should probably be more robust and recover from this better than it does now--e.g. by ignoring the session issue if sessions are disabled.

I plan to stop using sessions and send back the state I need in a cookie, but other folks may make the same mistake as I did...

**Comment by jdubois** [comment]
By default JHipster is stateless:

- we don't consider putting stuff in the session is a good idea. There's also a performance hit of having a stateful app, so we can't put that by default (as most people will code their app correctly, they shouldn't suffer from this)
- there is the option to have a stateful app, it's a question during generation,  so just select the option if you want it
- otherwise turning the stateless app into a stateful app is trivial, have a look at the "stateless" part in the security configuration -> I think this is what you need

I'm closing this at it's a user error, not a JHipster bug.

**Comment by deepu105** [comment]
And about JHipster being more robust in this case is objective, we
don't know and can't control what a user does with the code. ANd quite
frankly we don't want to control that. Once generated it's your code, you
do whatever you like with it.

Thanks & Regards,
Deepu
