### ISSUE TITLE
Add a "translation-not-found" class name

### ISSUE THREAD

**Issue by mxxcx** [jhipster/generator-jhipster#8633]
##### **Overview of the feature request**

On slower connections there is a visible flickering of translation-not-found placeholder text, as you can see it here https://gyazo.com/f3e0a76fb66d325e4456d7e66ce8a293 and https://gyazo.com/08867885279c270fa30619d515ef2a3c (React, jhipster 5.50, the latter being prod build)

Adding a class name would allow to hide it, or show the inner text of the Translate component and notify the dev by error notifications that a translation is not found. 

The new pacman loader doesn't fix it, the flickering is still there, same delay actually. 

##### **Motivation for or Use Case**

Looks unprofessional, and a lot of people browse on slower mobile connections. 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I already saw this, when working on Protractor tests with React, so I confirm this issue

**Comment by deepu105** [comment]
Yes, we need to fix it. Adding the class needs to be done in the
react-jhipster lib, anybody willing to PR? But it won't work for
placeholders. Another option is to pass empty string as message in prod
profile and keep the current message only in dev

**Comment by vishal423** [comment]
I believe same issue is also applicable for angular.

**Comment by pascalgrimaud** [comment]
@vishal423 : never saw it for Angular. Do you have a config + use case to reproduce it ?

**Comment by deepu105** [comment]
the best solution IMO is to keep the elements hidden by default, with or without a CSS class, and make them visible only when the translation is applied. This way you won't have the flickering and for valid cases of translation not found you still see the message. If anyone is willing to do this PR for react-jhipster lib plz feel free to do so, else I'll do it next week or whenever I find the time.

**Comment by deepu105** [comment]
sometimes they are valid as well, in this case it seems valid as the key is
wrong

Thanks & Regards,
Deepu
