### ISSUE TITLE
Maven filtering not performed on test yml config files

### ISSUE THREAD

**Issue by MSaguer** [jhipster/generator-jhipster#8636]
##### **Overview of the issue**

When running the tests on monolith application with maven, the test configuration files are not filtered by the maven-resources-plugin plugin and still contain unresolved variables.

##### **Motivation for or Use Case**

Test yml configuration file such as src/test/resources/config/application.yml contains variables that shall be resolved by maven filtering.

##### **Reproduce the error**

1. Generate the monolith application with maven build tool
2. Run the tests (mvn test)
3. Open target/test-classes/config/application.yml file

Check that info.project.version = #project.version# instead of 0.0.1-SNAPSHOT

##### **Related issues**

None

##### **Suggest a Fix**

Add the following configuration in pomx.ml in maven-resources-plugin plugin
````
                    <execution>
                        <id>test-resources</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>target/test-classes</outputDirectory>
                            <useDefaultDelimiters>false</useDefaultDelimiters>
                            <delimiters>
                                <delimiter>#</delimiter>
                            </delimiters>
                            <resources>
                                <resource>
                                    <directory>src/test/resources/</directory>
                                    <filtering>true</filtering>
                                    <includes>
                                        <include>config/*.yml</include>
                                    </includes>
                                </resource>
                                <resource>
                                    <directory>src/test/resources/</directory>
                                    <filtering>false</filtering>
                                    <excludes>
                                        <exclude>config/*.yml</exclude>
                                    </excludes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
````

##### **JHipster Version(s)**

generator-jhipster@5.5.0

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "appli",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

<details>
<summary>Operating System</summary>
<pre>
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.19.1.windows.1

node: v8.11.4

npm: 5.5.1

yeoman: 2.0.5

yarn: 1.9.4
</pre>
</details>

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
I'm wondering if those properties are really needed for the test run. Would it be possible to just remove them from `src/test/resources/application.yml` ?
Why do you need those properties in the test context ?

**Comment by MSaguer** [comment]
You are right. This variable is not really needed in test env.
I noticed the filtering problem when I was extracting port values from yml file to maven settings. The final aim is to be able to share the same virtual machine for many developers (corporate constraint).
That's why filtering the test configuration file is mandatory for me.

**Comment by jdubois** [comment]
Yes but there's a performance hit for everyone else

**Comment by PierreBesson** [comment]
OK so, I'm removing this property from the test's property file as it is unused and give a false impression that we do property substitution on test resources.
