### ISSUE TITLE
h2TCPServer config fails on server port >=10.000

### ISSUE THREAD

**Issue by Evertude** [jhipster/generator-jhipster#8639]
##### **Overview of the issue**
Generated code (of the gateway backend) in DatabaseConfiguration.java was changed in Version 5.5.0 to:

    public Object h2TCPServer() throws SQLException {
        String port = "1" + env.getProperty("server.port");
        log.debug("H2 database is available on port {}", port);
        return H2ConfigurationHelper.createServer(port);
    }

Because there are only 2^16 ports available (on Windows), the program crashes when it tries to open a port >100.000

##### **Motivation for or Use Case**

I use a Server Port >10.000

##### **Reproduce the error**

Use a Server Port >10.000 and run mvnw

##### **Suggest a Fix**

Don't add a leading 1 to the port if it already has 5 digits

##### **JHipster Version(s)**

5.5.0

##### **JHipster configuration**

<anything>
"serverPort": "10000",
<anything>

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Is there any specific reason that you use that port?

**Comment by jdubois** [comment]
It's my fault, I changed that default port as I don't think anybody uses it, and it clashed with the Kafka default port (real culprit is Kafka in fact).
I had no idea there was such a limit on Windows, anybody can confirm?

**Comment by pascalgrimaud** [comment]
@jdubois : it's not related to Windows. For example, if you choose server.port=18080, the port for h2 would be 118080, which is not possible, because of port range
