### ISSUE TITLE
User linking to UserExtra missing info in tutorial

### ISSUE THREAD

**Issue by defrummel** [jhipster/generator-jhipster#8648]
##### **Overview of the feature request**

Missing removal of user additions in the linking of User to UserExtra

Add some code to the https://www.jhipster.tech/tips/022_tip_registering_user_with_additional_information.html

    private boolean removeNonActivatedUser(User existingUser){
        if(existingUser.getActivated()) {
             return false;
        }
        userExtraRepository.findById(existingUser.getId()).ifPresent( ue -> {
            userExtraRepository.delete(ue);
        	userExtraRepository.flush();
        });
        userRepository.delete(existingUser);
        userRepository.flush();
        this.clearUserCaches(existingUser);
        return true;
    }

    public void deleteUser(String login) {
        userRepository.findOneByLogin(login).ifPresent(user -> {
            userExtraRepository.findById(user.getId()).ifPresent( ue -> {
	            userExtraRepository.delete(ue);
            });
            userRepository.delete(user);
            this.clearUserCaches(user);
            log.debug("Deleted User: {}", user);
        });
    }

    public void removeNotActivatedUsers() {
        userRepository
            .findAllByActivatedIsFalseAndCreatedDateBefore(Instant.now().minus(3, ChronoUnit.DAYS))
            .forEach(user -> {
                log.debug("Deleting not activated user {}", user.getLogin());
                userExtraRepository.findById(user.getId()).ifPresent( ue -> {
    	            userExtraRepository.delete(ue);
                });
                userRepository.delete(user);
                this.clearUserCaches(user);
            });
    }

##### **Motivation for or Use Case**

Everything worked fine, untill i moved to prod package. Then the tests were failing and from the stacktrace it is not clear where the problem is coming from. Something with a duplicate id.. But this comes from the one-to-one relationship that is not removed when you remove an unregistered user.

Also there are a lot of tests obviously failing, maybe a comment saying "Make sure you update your testcases accordingly since now the UserExtra entity is dependent on a present User in the DB" or something like that

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Tips are written by users.
We can't guarantee it will work fine. If it needed to be updated, don't hesitate to PR and update the tips.

**Comment by pascalgrimaud** [comment]
@Paul-Etienne : as you are the author of the tips, are you ok with these suggestions ?

@defrummel @Paul-Etienne : If some of you want to update the tips, it will be cool.
Otherwise, that means the tips is not working anymore, so it should be deleted.

**Comment by Paul-Etienne** [comment]
I am not currently using JHipster anymore so I have to admit this is all a bit distant to me right now.
I trust @defrummel with the changes he's referring to, so yes I am ok with any suggestion. I don't feel entitled to perform the update for now though, for the reason I have stated first. Feel free to update or delete the tip if it became outdated.

**Comment by pascalgrimaud** [comment]
thanks for your answer @Paul-Etienne !

**Comment by defrummel** [comment]
o man im just getting started with coding outside of my own git repo, not sure how to do pr and stuff :)

**Comment by deepu105** [comment]
@defrummel well you have to start somewhere, look at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-a-pull-request for example

**Comment by jdubois** [comment]
Yes there's ton of help and don't worry if you mess up, you can't break anything (we'll review & help before merging your changes)

**Comment by pascalgrimaud** [comment]
So as no one want to update the tips, I'm removing the link.
