### ISSUE TITLE
When caching is not enabled, PersistentTokens are not deleted from database by PersistentTokenRememberMeServices

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/generator-jhipster#8653]
jhipster-dependencies.version: 2.0.26
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

##### **Overview of the issue**

When cache is disabled, tokens are not deleted from database by `PersistentTokenRememberMeServices` because of the use of `delete()`. It's a JPA/Hibernate "problem", probably caused by the fact that we're not in transactions. Using `deleteById()` fixes the bug.

##### **Motivation for or Use Case**

Have tokens deleted from database even if cache is disabled.

##### **Reproduce the error**

Tick "Remember me"
Authenticate
   -> a token is stored
Logout
   -> the token should be deleted, but no delete statement is produced so it stays.

The same happens if you simulate a cookie theft by altering the token. The token should be deleted from the database but it remains as no delete statement is produced.
Same of expiration.

##### **Related issues**

Not found.

##### **Suggest a Fix**

In `PersistentTokenRememberMeServices`, replace all `persistentTokenRepository.delete` by `deleteById`, which works with and without cache.
I had doubts, but the explanation might be that we're not in a `@Transactional` block: the detached token has to be merged, then removed, which causes the problem (no delete statement).
With deleteById, the underlying repository does the findById then calls remove on the fetched instance and the delete statement is produced. It's clean from a JPA/Hibernate point of view.

##### **JHipster Version(s)**

I think it's a regression for logout as it used to be `@Transactional` before Spring Boot 2, but I'm not sure.

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitCompany": "",
    "baseName": "xxx",
    "packageName": "net.xxx",
    "packageFolder": "net/xxx",
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "authenticationType": "session",
    "uaaBaseName": "../uaa",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "enableSwaggerCodegen": false,
    "messageBroker": false,
    "buildTool": "maven",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "clientFramework": "angularX",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "5.5.0",
    "rememberMeKey": "xxx"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**

NA

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
OK this is "normal": there is no transaction (not possible on this bean, we can't add a proxy to it), so when we get the token it's done in a first transaction, then the object gets detached, and therefore it doesn't get deleted.

Indeed using "deleteById" will solve the issue, as we work with the ID and not with the detached object.

Let me do the fix, many thanks @pblanchardie for the issue & the analysis (as you found the solution)
