### ISSUE TITLE
PersistentAuditEvent lacks equals() and hashCode()

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/generator-jhipster#8655]
##### **Overview of the issue**

PersistentAuditEvent lacks `equals()` and `hashCode()`

##### **Motivation for or Use Case**

Mandatory

##### **Reproduce the error**

NA

##### **Related issues**

NA

##### **Suggest a Fix**

Generate equals and hashCode

##### **JHipster Version(s)**

JHipster 5.5.0

##### **JHipster configuration**

NA

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

NA

##### **Browsers and Operating System**

NA

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Would you like to create a PR?
