### ISSUE TITLE
Unable to connect to MongoDB Atlas

### ISSUE THREAD

**Issue by michael-pratt** [jhipster/generator-jhipster#8665]
##### **Overview of the issue**

Using JHipster 5, I am unable to connect to a MongoDB Atlas cluster (running version 4.0.3). This could be an issue with spring-data, but figured I'd start here.

Stack trace is:

##### **Motivation for or Use Case**

Cannot start application due to connection failure.

##### **Reproduce the error**

Start a free tier MongoDB atlas cluster. Here's the YAML I am using:

    spring:
        data:
            mongodb:
                uri: mongodb://<USER>:<PASSWORD>@XXXXX-shard-00-00-m4gfg.mongodb.net:27017,XXXXX-shard-00-01-m4gfg.mongodb.net:27017,XXXXX-shard-00-02-m4gfg.mongodb.net:27017/test?ssl=true&replicaSet=XXXXX-shard-0&authSource=admin&retryWrites=true
                database: MyDatabase

Error message is:

    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongobee' defined in class path resource [com/mike/config/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is com.mongodb.MongoQueryException: Query failed with error code 8000 and error message 'user is not allowed to do action [find] on [XXXXX.system.indexes]' on server XXXXX-shard-00-01-m4gfg.mongodb.net:27017

I have ensured the user I am connecting with has the `readWriteAnyDatabase@admin` roles in Atlas.

Possibly related to this issue mentioned on StackOverflow:

https://stackoverflow.com/questions/49958635/mongodb-atlas-user-is-not-allowed-to-do-action-find-on-system-indexes

##### **JHipster Version(s)**

5.5.0

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mike"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "pelotonduel",
    "packageName": "com.mike",
    "packageFolder": "com/mike",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "XXXXX",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

git version 2.17.1 (Apple Git-112)

node: v9.11.1

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

**Comment by ruddell** [comment]
Looks like a Mongobee issue https://github.com/mongobee/mongobee/pull/87, maybe [mongock](https://github.com/cloudyrock/mongock) (a fork of mongobee) is something to look into if mongobee is no longer maintained.

**Comment by michael-pratt** [comment]
Thanks. Looks like Mongock isn’t a simple drop in replacement. Is there a way in jhipster to disable migration functionality that mongobee provides?

**Comment by michael-pratt** [comment]
Answered my own question...removing the `@Bean` definition from `public Mongobee mongobee(...)` in _DatabaseConfiguration.java_ seems to do the trick. Haven't done any thorough testing, but the apps starts and I can create new users.

**Comment by michael-pratt** [comment]
Since Mongobee appears to have been abandoned, is there any interest in moving to Mongock? After a little tinkering I got it working, and would be happy to submit a PR.

**Comment by agherashyam2000** [comment]
After removing the @Bean definition from public Mongobee mongobee(...) in DatabaseConfiguration.java, the app starts and I can create new users. But after creating new user the activation link is not sent to users email and also I can not able to logged in !
Can you suggest any solution ?
