### ISSUE TITLE
keycloak being added to app.yml for microservices with oauth2 causes startup errors

### ISSUE THREAD

**Issue by rainerh** [jhipster/generator-jhipster#8674]
##### **Overview of the issue**

When creating a microservice with oauth2 option, keycloak.yml is added as include to app.yml, but no keyycloak.yml is available.

##### **Motivation for or Use Case**

Running into startup errors while starting the microservices with docker-compose -f src/main/docker/app.yml

##### **Reproduce the error**
Create a microservice with oauth2 and start with docker-compose -f src/main/docker/app.yml

##### **Related issues**

PR follows

##### **JHipster Version(s)**
5.4.x, 5.5.0 and master
 
##### **JHipster configuration**

```
jhipster@0.0.0 /home/rhermanns/code/jhipster/service
└── generator-jhipster@5.5.0 
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.service",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "microservice",
    "baseName": "service",
    "packageName": "com.example.service",
    "packageFolder": "com/example/service",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva3VuLXRvLWNoYW5nZS1pbi1wcm9kdVN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true,
    "languages": [
      "en",
      "de"
    ],
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@mraible can you please take a look?

**Comment by mraible** [comment]
I approve #8675 if it replaces #8554. IMO, there's no need for Keycloak files in microservices, only in monoliths and gateways.
