### ISSUE TITLE
Entity gets persisted in Elasticsearch even when an exception is thrown in database persist

### ISSUE THREAD

**Issue by ikramcheb** [jhipster/generator-jhipster#8676]
##### **Overview of the issue**
We have these two lines in functions of save accross all  generated services
      
        Foo result = fooRepository.save(foo);
	fooSearchRepository.save(result); 

But when an exception is thrown in the first save (DataIntegrityViolationException for instance), the database save is rolled back but  foo entity is saved in elasticsearch nevertheless.  which will cause inconsistency of  data between the database and elasticsearch

##### **Motivation for or Use Case**
 Inconsistency of  data between the database and elasticsearch

##### **JHipster Version(s)**
5.2.0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes that's normal, there is no transaction manager (it's not possible to have one with Elasticsearch).

The only solution would be to flush the Hibernate session after doing the save, but there's a performance hit for doing so.

**Comment by jdubois** [comment]
In fact this shouldn't happen with a "normal" JHipster application, this is because you added some logic, including probably a unique field somewhere, and you are not checking this field before saving.

- For a "good" application, you should check this before saving, and not rely on the database (and that will also solve the issue)
- Then I understand you can't test everything: in that case just do a `.flush()` before saving to Elasticsearch, so you have the exception earlier (of course there'll be a performance hit)

Not sure we should do it a the JHipster level: one solution would be to wrap the database code into a try...catch block and then do the Elasticsearch save: the code wouldn't be very nice-looking, but that should solve the error for everyone.

**Comment by gzsombor** [comment]
I don't understand, if there is an exception from the first repository save method - which deals with db - how could happen, that the entity is also saved to Elasticsearch? The exception must prevent this. Or have you added code to catch the exception? Or you talking about having a different RuntimeException thrown from a later code?
 In my experience, there is a different, data inconsistency problem in this code, which generally not noticed at start, and highly dependent on the actual data model: it's too easy to save entities into ES, which doesn't have assigned ID from the database - having a flush there could be a solution.
 The other solution is to delegate the ES saving into a transactional callback method, which only gets called when the transaction succeeded.

**Comment by deepu105** [comment]
@jdubois @gzsombor do you guys want to do anything for this or should we close it and document it so that users can handle it when customizing?

**Comment by jdubois** [comment]
We could improve it but this would bloat the templates, not sure this is good for everyone. 

We have too many opened issues and won't be able to work on it anyway, so let's close it.

**Comment by ikramcheb** [comment]
Thank you all for the response. 
First, @gzsombor The exception is thrown by the database repository save not from another code.
Second, @gzsombor  I dont catch that exception anywhere in the code.
Third, @jdubois  it will be exhausting to check all constraints before save, especially in large applications.
I think flushing the Hibernate solution is the most adequate in my case (since I can't  implement transactional callbacks at this advanced stage of application development)
It will be nice to handle this in Jhipster template though

**Comment by jdubois** [comment]
Thanks, totally makes sense. But still, I wouldn't recommend doing the flush by default, I don't think it's a good practice (for most people).

**Comment by gzsombor** [comment]
@ikramcheb : if you don't catch the exception, how the ElasticSearch repository gets called? That is after the db repository call, which is throwing the exception ...

**Comment by ikramcheb** [comment]
@gzsombor  I am equally confused by this. How the next line is executed while the previous one throws an exception.
This is the exact code I am using 
I have an entity "Snomed" with a unique field "code"
        Rest Controller 


     	@PostMapping("/snomeds")
		@Timed
		public ResponseEntity<Snomed> createSnomed(@Valid @RequestBody Snomed snomed) throws URISyntaxException {
			log.debug("REST request to save Snomed : {}", snomed);
			if (snomed.getId() != null) {
				throw new BadRequestAlertException("A new snomed cannot already have an ID", ENTITY_NAME, "idexists");
			}
			Snomed result = snomedService.save(snomed);
			return ResponseEntity.created(new URI("/api/snomeds/" + result.getId()))
					.headers(HeaderUtil.createEntityCreationAlert(ENTITY_NAME, result.getId().toString())).body(result);
		}

SnomedSERVICE 

     public Snomed save(Snomed snomed) {
		log.debug("Request to save Snomed : {}", snomed);
		Snomed result = snomedRepository.save(snomed);
		snomedSearchRepository.save(result);
		return result;
	}

I insert two snomeds with the same code. At the second attempt a DataIntegrityViolationException is thrown, nothing is added to the database but a new snomed is added in elasticsearch 

  	{
	  "took" : 1,
	  "timed_out" : false,
	  "_shards" : {
		"total" : 5,
		"successful" : 5,
		"skipped" : 0,
		"failed" : 0
	  },
	  "hits" : {
		"total" : 2,
		"max_score" : 5.008058,
		"hits" : [
		  {
			"_index" : "snomed",
			"_type" : "snomed",
			"_id" : "206",
			"_score" : 5.008058,
			"_source" : {
			  "id" : 206,
			  "code" : "test1",
			  "description" : "test1 description"
			}
		  },
		  {
			"_index" : "snomed",
			"_type" : "snomed",
			"_id" : "207",
			"_score" : 3.4590964,
			"_source" : {
			  "id" : 207,
			  "code" : "test1",
			  "description" : "duplicated"
			}
		  }
		]
	  }
	}

**Comment by gzsombor** [comment]
Very strange, indeed. Do you have any custom hibernate listener, which triggers saving the entity to ES (that's a common pattern, which I saw)?
 Other than, you need to debug it, you can add breakpoints to ES code as well, and check who calls it.
