### ISSUE TITLE
Update to new logo everywhere

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#8679]
Since we have new cool inclusive logos, let's use this ticket to switch over

TODO: For the team

- [x] Add random logo tied to a hash(app name or JWT key) to generated app client app
- [x] Change main logo & favicon for generated projects #8672
- [x] Show a logo slideshow in the main website
- [x] Change the main logo & favicon on the docs website
- [x] Change logo on all project Readme etc
- [x] Twitter marketing for the new logo

@jhipster/developers please add here if I missed an

**Comment by pascalgrimaud** [comment]
In readme:
> THIS IS STILL A WORK IN PROGRESS

So I think we should wait a little bit :-)

**Comment by atomfrede** [comment]
We could create bow ties for e.g. react and vue with slightly changed colors

**Comment by jdubois** [comment]
Please keep the color: the logo is just the bow tie, it's very simple, so if you change color people will not recognize it.

**Comment by deepu105** [comment]
@jdubois agree let's keep a single color bow tie as the main logo everywhere, for the avatar we can have any number of colors variations.
@jdubois also the hipster guy variation of the logo we recently had was apache 2 license as the guy who submitted the PR agreed to it on the ticket. And anyway, by submitting something to this repo, you agree to the license anyway. So I guess we can keep it

**Comment by deepu105** [comment]
@jdubois btw are the logo still WIP? can we announce it?

**Comment by jdubois** [comment]
Still in WIP, there are still a couple of issues with them, sorry.

**Comment by deepu105** [comment]
Oh ok, I didn't know that

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
For me this is all done (mostly thanks to @atomfrede - thanks!!) so I'm closing this
