### ISSUE TITLE
Upgrade Node.js version to 10.13.0 (LTS)

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#8682]
##### **Overview of the feature request**

Upgrade Node.js version to 10.13.0 (LTS)

##### **Motivation for or Use Case**
See https://nodesource.com/blog/what-s-new-to-lts-with-the-introduction-of-node-js-10-lts

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@pascalgrimaud Is this something you will take care?

**Comment by pascalgrimaud** [comment]
ok, self assigned
