### ISSUE TITLE
Upgrade jdk to 11

### ISSUE THREAD

**Issue by yudar1024** [jhipster/generator-jhipster#8689]
##### **Overview of the feature request**

provide jdk 11 support in jhipster

jdk8 life cycle support will be closed in 2019,  the next lts version 11 is released.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by antarus** [comment]
Jjhipster will support jdk 11 when spring boot 2.1 will be used in the generator (Work In Progress) ;)

**Comment by cbornet** [comment]
JDK11 will be supported once we migrate to Spring Boot 2.1. See #8681 for follow-up

**Comment by cbornet** [comment]
Actually #8683
