### ISSUE TITLE
Cleanups: Dockerfile and entrypoint.sh still created under 'src/main/docker'

### ISSUE THREAD

**Issue by rainerh** [jhipster/generator-jhipster#8690]
##### **Overview of the issue**

After generating an application, `src/main/docker/Dockerfile` and `src/main/docker/entrypoint.sh` are still created in the source tree. Since `jib` is now used to generate the docker images, both files are no longer required.

##### **Motivation for or Use Case**

Cleanups

##### **Suggest a Fix**

- remove `generators/server/templates/src/main/docker/Dockerfile.ejs`
- remove `generators/server/templates/src/main/docker/entrypoint.sh.ejs`

##### **JHipster Version(s)**

5.4.x, 5.5.0 and current master

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by antarus** [comment]
At work we still have some problem with Jib and the dockerfiles and and the entrypoint file allows us to still generate our images.
We work in offline mode.
It would be cool to keep them still some version: D

**Comment by ruddell** [comment]
It was decided in the `jib` integration PR to leave the Dockerfile for some time, see the bottom of https://github.com/jhipster/generator-jhipster/pull/8352#issuecomment-425633447

**Comment by deepu105** [comment]
yes we will remove it during next major version

**Comment by deepu105** [comment]
i'll keep your PR open with v6 tag
