### ISSUE TITLE
Yarn start command is working only few seconds 

### ISSUE THREAD

**Issue by QuentinFombaron** [jhipster/generator-jhipster#8692]
##### **Overview of the issue**

When I tried to run `yarn start` in my JHipster project, it works perfectly during the next 10 seconds, `http://localhost:9000` responds, the `watch` in IntelliJ works as well. But after about 10 seconds, nothing works at all. I have to kill `node` process to free 9060 port and to relaunch `yarn start` command.

I have tried to delete `yarn.lock` file, then to run `yarn install` cause I have updated yarn version with `brew upgrade`. But nothing is working, I also tried to clean the project with *Maven clean* and *Yarn cleanup*.

##### **JHipster Version(s)**

```
mes-courses@0.0.0 /Users/Quentin/Documents/Cours/Polytech_RICM5/S9/ECOM/ecom-mescourses
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "ecom.mescourses"
    },
    "jhipsterVersion": "5.3.4",
    "applicationType": "monolith",
    "baseName": "MesCourses",
    "packageName": "ecom.mescourses",
    "packageFolder": "ecom/mescourses",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.19.1

node: v11.0.0

npm: 6.4.1

yarn: 1.12.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

##### **Browsers and Operating System**

Mac OS Majove (10.14.1)

-   [**X**] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
In your .yo-rc.json, I see npm configured as package manager. Instead of
yarn, try using npm

**Comment by QuentinFombaron** [comment]
Thank you @vishal423 but no changes, I tried with `yarn` and `npm`. When I try to load my `localhost:9000` page (the maven `localhost:8080` works). I can see JHipster log message : 
```
2018-10-31 17:01:57.516 DEBUG 11145 --- [ XNIO-2 task-24] e.mescourses.aop.logging.LoggingAspect   : Enter: ecom.mescourses.repository.CustomAuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=2018-10-31T16:01:57.516Z, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2018-10-31 17:01:57.517 DEBUG 11145 --- [ XNIO-2 task-24] e.mescourses.aop.logging.LoggingAspect   : Exit: ecom.mescourses.repository.CustomAuditEventRepository.add() with result = null
2018-10-31 17:01:57.518  WARN 11145 --- [ XNIO-2 task-24] o.z.problem.spring.common.AdviceTrait    : Unauthorized: Full authentication is required to access this resource
```

**Comment by vishal423** [comment]
I have recently used v5.4.2 (yarn) and hadn't noted any issues. Can you try
with latest v5.5 to check? Also, please be more explicit on what's not
responding. What do you see on console (one running yarn start)

**Comment by atomfrede** [comment]
You are using node 11. We usually only support LTS versions. Can you please try node 8 (not sure if node 10 is working yet).

**Comment by atomfrede** [comment]
@QuentinFombaron  It looks like the same issue as here: https://stackoverflow.com/questions/53085942/jhipster-hot-reload-crashes-node

So please try with node 10 LTS (or 8 LTS). If you still have a problem we can reopen this issue.

**Comment by QuentinFombaron** [comment]
The problem was the Node version, I downgraded to v10.13.0 and it works ! Thank you very much @atomfrede !
