### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test 

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#8693]
##### **Overview of the issue**

After the latest java upgrade on at least debain and ubuntu maven surefire plugin stops working with this error:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project stand-bystand: There are test failures.
> [ERROR]
> [ERROR] Please refer to /home/tibi/git/char4/target/surefire-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
> [ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> [ERROR] Command was /bin/sh -c cd /home/tibi/git/char4 && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -javaagent:/home/tibi/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/home/tibi/git/char4/target/test-results/coverage/jacoco/jacoco.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m -jar /home/tibi/git/char4/target/surefire/surefirebooter6488219923373782248.jar /home/tibi/git/char4/target/surefire 2018-10-31T13-40-05_490-jvmRun1 surefire6687084744045484879tmp surefire_01044511474891119345tmp

##### **Motivation for or Use Case**

Surefire team is working on a fix but in the mean time there is a work around. We could implement it until the plugin is fixed

##### **Reproduce the error**

Create any form of jhipster project with maven and run tests.

##### **Related issues**
Surefire manifest jar classloading broken on latest Debian/Ubuntu Java8
https://issues.apache.org/jira/browse/SUREFIRE-1588?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16670286#comment-16670286

##### **Suggest a Fix**

added this line in to the pom.xml:

    <useSystemClassLoader>false</useSystemClassLoader>

like this:

        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>${maven-surefire-plugin.version}</version>
            <configuration>
                
                <runOrder>alphabetical</runOrder>
                <useSystemClassLoader>false</useSystemClassLoader>
            </configuration>
        </plugin>

Executing jhipster:info
Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
stand-bystand@0.0.0 /home/tibi/git/mvntest
└── generator-jhipster@5.5.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "nl.tibi.sbys",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "baseName": "standBystand",
    "packageName": "nl.tibi.sbys",
    "packageFolder": "nl/tibi/sbys",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "nl",
      "de"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v8.11.3

npm: 6.2.0

yarn: 1.9.4

##### **Browsers and Operating System**

Ubuntu

-   [ x Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Interesting, seen a discussion on twitter already about suddenly breaking builds.

**Comment by tibistibi** [comment]
I will keep an eye on it. Will make a PR. When is next jhipster scheduled? 

It is not sure yet if it will be ported to a 2.* version (used in jhipster now) or only to the new 3.* 

On November 1, 2018 12:25:21 PM CET, Frederik Hahne <notifications@github.com> wrote:
>The fix is already merged upstream, but not sure how fast the next
>release is baked. So @tibistibi do you want to make a PR?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/8693#issuecomment-435011706

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pascalgrimaud** [comment]
Thanks, the fix had been merged https://github.com/jhipster/generator-jhipster/pull/8714
We'll keep in mind to remove this additional line

For now, let's close this.

**Comment by tibistibi** [comment]
it seems the linux openjdk team has reverted the change:

>The problem seems to have been resolved upstream if you update the OpenJDK package. (For me, from 1.8.0_181-8u181-b13-1ubuntu0.18.10.1-b13 to 1.8.0_191-8u191-b12-0ubuntu0.18.10.1-b12.)

https://issues.apache.org/jira/browse/SUREFIRE-1588

so we can revert the change (tested it on my system) but we can also wait a bit to be sure everyone will have the new openjdk

in all cases it is fixed (even with strict setting in java) in the new surfiere plugin so we can also wait when jhipster is using version 3.0.0-M1 (now 2.22.0)

i think it is best to wait a bit there seems no real problem with the temp fix.

**Comment by ishaq8283** [comment]
not working for me

**Comment by ishaq8283** [comment]
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.21.0</version>
				<configuration>
					<forkCount>0</forkCount>
					<argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
					<suiteXmlFiles> <suiteXmlFile>src/test/resources/runner/testng.xml</suiteXmlFile> 
				</suiteXmlFiles>
				</configuration>
			</plugin>

**Comment by ajay443** [comment]
what is the correct fix for this error, any details?

**Comment by gmarziou** [comment]
@ajay443 

Please don't comment on an **old issue**.
If you think this issue still applies, please [create a new ticket](https://github.com/jhipster/generator-jhipster/issues/new) with proper details.
