### ISSUE TITLE
Remove tapable as a direct dependency if it isn't directly in use

### ISSUE THREAD

**Issue by Fydon** [jhipster/generator-jhipster#8699]
##### **Overview of the issue**

Development depencency tapable appears to be a dependency of other dependencies, but not directly in use. It is only present in Angular.

##### **Motivation for or Use Case**

Tapable is a dependency of fork-ts-checker-webpack-plugin, html-webpack-plugin, enhanced-resolve (from ts-loader) and webpack. Removing tapable as a direct dependency still resolves to version 1.0.0. Is there a reason to depend on it directly, as I can't see a reference to it? If not then I can create a pull request to no longer depend on it directly.

##### **Reproduce the error**

N/A

##### **Related issues**

None found

##### **Suggest a Fix**

Remove tapable from [Angular package.json.ejs][1].

##### **JHipster Version(s)**

```
prototype@0.0.0 
`-- generator-jhipster@5.5.0

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "example",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.17.1.windows.2

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

-   [X] Checking this box is mandatory (this is just to show you read everything)

[1]: https://github.com/jhipster/generator-jhipster/blob/0d91b01ae216fd109f9e10d44ecad3cd2b601313/generators/client/templates/angular/package.json.ejs#L123

**Comment by deepu105** [comment]
It was directly installed due to some conflict when adding the plugin, may be that issue no longer exists, but  it needs testing to make sure it doesnt break anything

**Comment by Fydon** [comment]
@deepu105 Okay. With my settings both a dev and prod build work without tapable, which is what I'd expect given that it still resolves to version 1.0.0:

	+-- fork-ts-checker-webpack-plugin@0.4.1
	| `-- tapable@1.0.0
	+-- html-webpack-plugin@3.2.0
	| `-- tapable@1.0.0  deduped
	+-- ts-loader@4.0.1
	| `-- enhanced-resolve@4.1.0
	|   `-- tapable@1.0.0  deduped
	`-- webpack@4.8.0
	  `-- tapable@1.0.0  deduped

Explicitly having a section to control a dependency of dependencies is a benefit in yarn, having recently started frontend development, although I've also chosen npm over yarn.

Would the tests that run on a pull request be sufficient to test that removing this isn't resulting in an issue again? Should I create a pull request to remove this or rather not?

**Comment by deepu105** [comment]
Ok then lets remove it. Can you do PR please
