### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#87]
- Add a mocking framework (Mockito?)
- Add more tests on the main generator (might be difficult on some very technical classes, like the Servlet filters)
- Generate tests with the entity and service sub-generators

**Comment by geyuqiu** [comment]
Entities do have some Integration Tests.
But no unit tests. 
How come you closed this ticket ? @jdubois

**Comment by pascalgrimaud** [comment]
@geyuqiu : this ticket was closed near 5 years ago... and was opened before the 1st release !

What did you expected by commenting this ticket ? We have both some integration and some unit tests. Feel free to improve them if you want.
See our coverage which is pretty good, IMO: https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application
