### ISSUE TITLE
JPA entities and extending classes

### ISSUE THREAD

**Issue by devedipoint** [jhipster/generator-jhipster#870]
I've noticed in entity generator there is not any possibility to extending classes.

Case 1: I need to all my entities extend BaseEntity related to TagEntity
Case 2: InvoiceEntity would extend AbsDocumentEntity because some fields would share with other documents, ie. OrderEntity.

I think extending and choosing JPA Strategy is very neccessery.

What do you think about it?

**Comment by kirit93** [comment]
Is there an easy way to extend hibernate envers to create an audit table for newly created entities?

**Comment by ShekharSahu** [comment]
@devedipoint were you able to implement it?
