### ISSUE TITLE
Should reflect-metadata be in devDependencies instead of dependencies?

### ISSUE THREAD

**Issue by Fydon** [jhipster/generator-jhipster#8702]
##### **Overview of the issue**

The [Angular 7 release documentation][2] speaks of reflect-metadata being incorrectly used in production. 

##### **Motivation for or Use Case**

I'm new to Angular and JHipster, so sorry if I'm misunderstanding the setup. It is currently only referenced in [Angular's webpack.dev.js.ejs][3] so I would expect no problems when moving reflect-metadata [from dependencies][4] to devDependencies.

##### **Reproduce the error**

N/A

##### **Related issues**

None found

##### **Suggest a Fix**

Move reflect-metadata to devDependencies.

##### **JHipster Version(s)**

```
prototype@0.0.0 
`-- generator-jhipster@5.5.0

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "example",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.17.1.windows.2

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

-   [X] Checking this box is mandatory (this is just to show you read everything)

[1]: https://github.com/jhipster/generator-jhipster/blob/0d91b01ae216fd109f9e10d44ecad3cd2b601313/generators/client/templates/angular/package.json.ejs#L118
[2]: https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c
[3]: https://github.com/jhipster/generator-jhipster/blob/9dd6895f625615660492efbe668cc7b2d0e153e9/generators/client/templates/angular/webpack/webpack.dev.js.ejs#L87
[4]: https://github.com/jhipster/generator-jhipster/blob/0d91b01ae216fd109f9e10d44ecad3cd2b601313/generators/client/templates/angular/package.json.ejs#L48

**Comment by vishal423** [comment]
+1, `reflect-metadata` that should be dev dependency.

**Comment by deepu105** [comment]
if its not used anywhere in the application, it can be moved. I think it might have been used for some lazy loading related things in past. @wmarques can you confirm?

**Comment by wmarques** [comment]
I don't remember adding this in order to setup lazy-loading, I think it is (or was ?) used by Angular to manage his DI. Maybe we can try to remove it and see if it works...

**Comment by jdubois** [comment]
I tested and it's working, thanks a lot @Fydon !
I'm doing the PR ASAP
