### ISSUE TITLE
Angular Material support

### ISSUE THREAD

**Issue by Harouun** [jhipster/generator-jhipster#8718]
Are there any plans to add Angular Material in Jhipster?

**Comment by pascalgrimaud** [comment]
It would be too much work, that's why we won't add Material support.
But don't hesitate to create :
- a module: https://www.jhipster.tech/modules/creating-a-module/
- or a blueprint: https://www.jhipster.tech/modules/creating-a-blueprint/

**Comment by Harouun** [comment]
Okey thanks @pascalgrimaud
