### ISSUE TITLE
Gradle does support use realm-based SSO so use a different URL for Oracle Maven

### ISSUE THREAD

**Issue by Fydon** [jhipster/generator-jhipster#8731]
##### **Overview of the issue**

As Gradle [doesn't support use realm-based SSO][1], a different URL is required to read from Oracle Maven.

##### **Motivation for or Use Case**

I want to receive Oracle dependencies from Oracle Maven using Gradle, but the current URL doesn't work.

##### **Reproduce the error**

N/A

##### **Related issues**

None found

##### **Suggest a Fix**

Add a link to [this repository][2], as it provides further details like encrypting credentials, and provide the following instead of [this line][3]:

    maven {
        url "https://www.oracle.com/content/secure/maven/content"

        credentials {
            username ''
            password ''
        }
    }

I haven't tried using the plugin to read maven setting for encrypted credentials.

##### **JHipster Version(s)**

```
prototype@0.0.0 
`-- generator-jhipster@5.5.0

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "example",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.17.1.windows.2

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

-   [X] Checking this box is mandatory (this is just to show you read everything)

[1]: https://discuss.gradle.org/t/support-for-maven-repositories-that-use-realm-based-sso/14456
[2]: https://github.com/robin-a-meade/example-gradle-oracle
[3]: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/build.gradle.ejs#L227

**Comment by jdubois** [comment]
Thanks @Fydon - could you do a PR on this? I don't use Oracle and it's hard to test, so help is really welcome on this one

**Comment by jdubois** [comment]
As nobody works on this, can we close this?
