### ISSUE TITLE
Update Apache Maven version to 3.6.0

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#8732]
##### **Overview of the feature request**

See https://lists.apache.org/thread.html/76da3ffda428e34d8253cb71bfcbb9409919c76311f59d3ad46cd302@%3Cannounce.maven.apache.org%3E

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Already done :-)
