### ISSUE TITLE
NPM Install -g jhipster-uml code ELIFECYCLE and deasync@0.1.9 install: `node ./build.js`

### ISSUE THREAD

**Issue by JustinZhaowilson** [jhipster/generator-jhipster#8740]
**Can't install jhipster-uml**

Error:

C:\jhipster\blog2>npm install -g jhipster-uml
C:\Users\James\AppData\Roaming\npm\jhipster-uml -> C:\Users\James\AppData\Roaming\npm\node_modules\jhipster-uml\jhipster-uml.js

> deasync@0.1.9 install C:\Users\James\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\deasync
> node ./build.js

C:\Users\James.DESKTOP-JFDRPUF\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Users\James\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "node C:\Users\James\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\James\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\deasync\node C:\Users\James\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.9 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\James.DESKTOP-JFDRPUF\AppData\Roaming\npm-cache\_logs\2018-11-03T12_24_23_972Z-debug.log

-----------------------------------------------------------------------------------------------------------
Jhipster Info
-------------
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
blog-2@0.0.0 C:\jhipster\blog2
`-- generator-jhipster@5.2.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.blog.learn",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "blog2",
    "packageName": "com.blog.learn",
    "packageFolder": "com/blog/learn",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * The BankAccount entity.
 * @author A true hipster
 */
entity BankAccount {
  /**
   * name
   */
  name String,
  amount Double
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.18.0.windows.1

node: v8.11.3

npm: 6.4.1

yeoman: 2.0.2

yarn: 1.7.0

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe
------------------------------------------------------------------------------------------------------------------
##### **Motivation for or Use Case**
Want to use UML Software to import UML into JDL files

##### **Suggest a Fix**
Could be to do with deasync@0.1.9, but have tried in the past to re-install this, but to no avail.

Using Chrome Version 70.0.3538.77 (Official Build) (64-bit) and Windows 10

**Comment by deepu105** [comment]
Please open the issue in JHipster UML repo and nit here

**Comment by MathieuAA** [comment]
This is not the repo for this, and to be honest: the JUML project needs maintenance.Le 3 nov. 2018 13:40, JustinZhaowilson <notifications@github.com> a écrit :Can't install jhipster-uml
Error:
C:\jhipster\blog2>npm install -g jhipster-uml
C:\Users\James\AppData\Roaming\npm\jhipster-uml -> C:\Users\James\AppData\Roaming\npm\node_modules\jhipster-uml\jhipster-uml.js

deasync@0.1.9 install C:\Users\James\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\deasync
node ./build.js

C:\Users\James.DESKTOP-JFDRPUF\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Users\James\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "node C:\Users\James\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
module.js:549
throw err;
^
Error: Cannot find module 'C:\Users\James\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\deasync\node C:\Users\James\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.9 install: node ./build.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\James.DESKTOP-JFDRPUF\AppData\Roaming\npm-cache_logs\2018-11-03T12_24_23_972Z-debug.log

Jhipster Info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator
JHipster Version(s)
blog-2@0.0.0 C:\jhipster\blog2
`-- generator-jhipster@5.2.1


JHipster configuration, a .yo-rc.json file generated in the root folder

.yo-rc.json file
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.blog.learn",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "blog2",
    "packageName": "com.blog.learn",
    "packageFolder": "com/blog/learn",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn"
    ]
  }
}


JDL for the Entity configuration(s) entityName.json files generated in the .jhipster directory

JDL entity definitions
/**
 * The BankAccount entity.
 * @author A true hipster
 */
entity BankAccount {
  /**
   * name
   */
  name String,
  amount Double
}



Environment and Tools
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
git version 2.18.0.windows.1
node: v8.11.3
npm: 6.4.1
yeoman: 2.0.2
yarn: 1.7.0
Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.22.0, build f46880fe
Motivation for or Use Case
Want to use UML Software to import UML into JDL files
Suggest a Fix
Could be to do with deasync@0.1.9, but have tried in the past to re-install this, but to no avail.
Using Chrome Version 70.0.3538.77 (Official Build) (64-bit) and Windows 10
