### ISSUE TITLE
Can't upgrade from 5.5.0 to 5.6.1

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#8758]
##### **Overview of the issue**

When I execute `jhipster upgrade`, the local version of `jhipster` does not seem to be updated (not in `package.json`, nor in `.yo-rc.json`).

##### **Motivation for or Use Case**

I want to upgrade my JHipster application from v5.5.0 to 5.6.1.

##### **Reproduce the error**
Create the following `jhipster-jdl.jh`:
```
application {
  config {
    applicationType monolith
    authenticationType oauth2
    baseName TestApp
    buildTool maven
    cacheProvider hazelcast
    clientPackageManager yarn
    devDatabaseType postgresql
    enableSwaggerCodegen false
    enableTranslation false
    languages [fr]
    nativeLanguage fr
    packageName fr.mycompany.testapp
    prodDatabaseType postgresql
    testFrameworks [cucumber, gatling]
    useSass true
  }

  entities *
}


entity SpecificUser {
  firstName String required maxlength(50),
  lastName String required maxlength(50),
  mail String maxlength(50),
  password String maxlength(50),
  type String maxlength(1),
  expirationDate LocalDate
}

entity Project {
  name String required maxlength(50),
  description String maxlength(500),
}

relationship ManyToOne {
  Project{creator(lastName)} to SpecificUser
}

paginate * with pagination
service * with serviceClass
```
Then `import-jdl` to create the project with v5.5.0 (and commit the first commit):
```bash
docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn jhipster/jhipster:v5.5.0 jhipster import-jdl ./jhipster-jdl.jh --force
git commit -m "First commit"
```
Now add the latest version of jhipster as a global npm package & launch the upgrade:
```bash
npm install -g generator-jhipster # also tried with yarn global add generator-jhipster without any success
jhipster upgrade
```
I notice during this step a strange behaviour, it doesn't seem to use the correct version of jhipster when re-generating the application here is the log:
```
✔ Updated generator-jhipster to version 5.6.1
     info Removing .editorconfig
     info Removing .gitattributes
     info Removing .gitignore
     info Removing .huskyrc
     info Removing .prettierignore
     info Removing .prettierrc
     info Removing README.md
     info Removing angular.json
     info Removing mvnw
     info Removing mvnw.cmd
     info Removing package.json
     info Removing pom.xml
     info Removing postcss.config.js
     info Removing proxy.conf.json
     info Removing src
     info Removing tsconfig-aot.json
     info Removing tsconfig.json
     info Removing tslint.json
     info Removing webpack
✔ Cleaned up project directory
Regenerating application with JHipster 5.6.1...
/dev/shm/test/node_modules/.bin
     info "/dev/shm/test/node_modules/.bin/jhipster" --with-entities --force --skip-install --no-insight
Using JHipster version installed globally
Running default command
Executing jhipster:app
Options: withEntities: true, force: true, skipInstall: true, insight: false, from-cli: true, with-entities: true, skip-install: true


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v5.5.0
Application files will be generated in folder: /dev/shm/test
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

 ______________________________________________________________________________

  JHipster update available: 5.6.1 (current: 5.5.0)
```
After all the upgrade, here is my git tree:
```bash
git log --graph --oneline --all
*   19105dc Merge branch 'jhipster_upgrade'
|\  
| * 9061485 Generated with JHipster 5.6.1
| * 8846bef Initial application generated by JHipster-5.5.0
* |   9452c83 Merge branch 'jhipster_upgrade'
|\ \  
| |/  
| * 14a5989 Generated with JHipster 5.5.0
* a7e355f First commit
```
Now, when I execute `jhipster --version` here is the output:
```
Using JHipster version installed locally in current project's node_modules
5.5.0
```
The `.yo-rc.json` does not seem to be updated also:
```bash
cat .yo-rc.json | grep jhipster
  "generator-jhipster": {
    "jhipsterVersion": "5.5.0",
```
At last, the `package.json` does not seem to be updated also:
```bash
cat package.json | grep generator
    "generator-jhipster": "5.5.0",
```
##### **JHipster Version(s)**

```
test-app@0.0.0 /dev/shm/test
└── generator-jhipster@5.5.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "clientPackageManager": "yarn",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "jhiPrefix": "jhi",
    "languages": [
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "fr",
    "packageName": "fr.mycompany.testapp",
    "packageFolder": "fr/mycompany/testapp",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [
      "cucumber",
      "gatling"
    ],
    "websocket": false,
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "TestApp",
    "buildTool": "maven",
    "cacheProvider": "hazelcast",
    "useSass": true,
    "jhipsterVersion": "5.5.0",
    "skipUserManagement": true,
    "clientFramework": "angularX",
    "serverPort": "8080"
  },
  "entities": [
    "SpecificUser",
    "Project"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity SpecificUser {
  firstName String required maxlength(50),
  lastName String required maxlength(50),
  mail String maxlength(50),
  password String maxlength(50),
  type String maxlength(1),
  expirationDate LocalDate
}
entity Project {
  name String required maxlength(50),
  description String maxlength(500)
}
relationship ManyToOne {
  Project{creator(lastName)} to SpecificUser
}

paginate SpecificUser, Project with pagination
service SpecificUser, Project with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.7.4

node: v8.10.0

npm: 6.2.0

yeoman: 2.0.1

yarn: 1.7.0

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.21.2, build a133471

##### **Browsers and Operating System**

I'm running Ubuntu 16.04 LTS.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by Evertude** [comment]
Have you tried a shell or system restart?

**Comment by anthony-o** [comment]
> Have you tried a shell or system restart?

I don't really see the link but in doubt I did a system restart and the following:
```bash
yarn global remove generator-jhipster
npm uninstall -g generator-jhipster
mkdir test2
cd test2
cp ../test/jhipster-jdl.jh ./
docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn jhipster/jhipster:v5.5.0 jhipster import-jdl ./jhipster-jdl.jh --force
git commit -m "First commit"
npm install -g generator-jhipster
jhipster upgrade
```
And got the exact same results.
But then I did the following:
```bash
yarn global remove generator-jhipster
npm uninstall -g generator-jhipster
mkdir test3
cd test3
cp ../test/jhipster-jdl.jh ./
docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn jhipster/jhipster:v5.5.0 jhipster import-jdl ./jhipster-jdl.jh --force
git commit -m "First commit"
docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn -v ~/.gitconfig:/home/jhipster/.gitconfig:ro jhipster/jhipster:v5.6.1 jhipster upgrade
```
And this time, the upgrade has correctly been taken into account!
All I can see are different versions for `git`, `node`, `npm`, `yeoman` and `yarn`:
```bash
docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn -v ~/.gitconfig:/home/jhipster/.gitconfig:ro jhipster/jhipster:v5.6.1 jhipster info
# [...]
##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.12.1

```

**Comment by pascalgrimaud** [comment]
JHipster upgrade is really hard to maintain.
Could you could try with the last release, it should work (I hope).

And reading your last comment, I think it is solved, as you mixte an install with NPM/Yarn.
That's why I'm closing this.
