### ISSUE TITLE
Can't use `postgresql` as `devDatabaseType` using JHipster 5.6.1

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#8760]
##### **Overview of the issue**

Can't use `postgresql` as `devDatabaseType` using JHipster 5.6.1.

##### **Motivation for or Use Case**

I was able to use such devDatabaseType in JHipster 5.5.0, I would like to have this also in this version.

##### **Reproduce the error**

Create the following `jhipster-jdl.jh`:
```
application {
  config {
    applicationType monolith
    authenticationType oauth2
    baseName TestApp
    buildTool maven
    cacheProvider hazelcast
    clientPackageManager yarn
    devDatabaseType postgresql
    enableSwaggerCodegen false
    enableTranslation false
    languages [fr]
    nativeLanguage fr
    packageName fr.mycompany.testapp
    prodDatabaseType postgresql
    testFrameworks [cucumber, gatling]
    useSass true
  }

  entities *
}
```
Then `import-jdl` to create the project with v5.6.1:
```bash
docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn jhipster/jhipster:v5.6.1 jhipster import-jdl ./jhipster-jdl.jh --force
```
Here is the output error:
```
Using JHipster version installed globally
Executing import-jdl ./jhipster-jdl.jh
Options: force: true, from-cli: true
The JDL is being parsed.
Error: Unknown value 'postgresql' for option 'devDatabaseType'.
ERROR! Error while parsing applications and entities from the JDL Error: Unknown value 'postgresql' for option 'devDatabaseType'.
```

##### **JHipster Version(s)**

```
/home/jhipster/app
`-- (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.12.1

##### **Browsers and Operating System**

I'm running Ubuntu 16.04 LTS.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I confirm the issue, using the same JDL we used at our workshop the last week:

```
➜ jhipster import-jdl workshop.jdl
Using JHipster version installed globally
Executing import-jdl workshop.jdl
Options: from-cli: true
The JDL is being parsed.
Error: Unknown value 'mongodb' for option 'devDatabaseType'.
ERROR! Error while parsing applications and entities from the JDL Error: Unknown value 'mongodb' for option 'devDatabaseType'.
```

**Comment by pascalgrimaud** [comment]
@MathieuAA : I'm looking the code in jhipster-core. If you can point me where to look, I can try to fix it during my travel, so we'll gain time

**Comment by pascalgrimaud** [comment]
I think it comes from this commit:
https://github.com/jhipster/jhipster-core/commit/f2b11b9199c8db683d09ca8c862a6217960ff386

**Comment by MathieuAA** [comment]
It's one introducing app validation. There's a file called application_validator, it needs be adjusted

**Comment by pascalgrimaud** [comment]
I think I got the fix.
Let me time to write full tests and PR to jhipster-core

**Comment by pascalgrimaud** [comment]
@jdubois : do you consider this bug as major ? If yes, I'm afraid we'll need another patch release soon (as soon as it's fixed)

**Comment by DanielFran** [comment]
@pascalgrimaud Probably adding in the list of devDatabase the prodDatabase list will fix it quickly: https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/application_options.js

**Comment by jdubois** [comment]
Yes but I won't be able to do a patch release until Thursday
Anyway I think @deepu105 will need this for his Devoxx talk

**Comment by pascalgrimaud** [comment]
@DanielFran : the problem comes from this function: https://github.com/jhipster/jhipster-core/blob/master/lib/exceptions/application_validator.js#L42-L54
When the option is databaseType, devDatabaseType or prodDatabaseType, it will fail because of this function: `checkForUnknownValue`

During lunch time, I'm implementing some checkDatabaseType, checkDevDatabaseType etc but didn't have time to finish the code.

**Comment by DanielFran** [comment]
@pascalgrimaud It fails probably because in devDatabaseType there is only [H2 options](https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/application_options.js#L64-L68) , so any other value fail because there are not available in the list.
But, I did not test it, this is only my assumption reading the code...

**Comment by deepu105** [comment]
Its not urgent for me

**Comment by MathieuAA** [comment]
@pascalgrimaud If you don't finish, don't worry: I'm having a look at it tonight

**Comment by MathieuAA** [comment]
If you need any pointer, don't hesitate :)

**Comment by MathieuAA** [comment]
I'm going to release JCore v3.6.1 (and drop a PR here) that includes this fix, and other DB validations.
