### ISSUE TITLE
Gateway -> Microservice connection doesn't work on dev port 9000

### ISSUE THREAD

**Issue by Evertude** [jhipster/generator-jhipster#8762]
##### **Overview of the issue**

When I create microservices with the latest versions of JHipster CLI, I experience the problem that I can't connect to those services with the dev port 9000 of my gateway although it works when I use the port that was specified for the gateway.

It still works with the service I created with versions 5.4.2 and earlier

The services are found through http://localhost:9000/#/admin/gateway and the swagger document can be accessed as usual, but http://localhost:9000/#/admin/docs doesn't find it

##### **Motivation for or Use Case**

I have a microservice architecture with a gateway and several microservices.

##### **Reproduce the error**

* Create a Gateway
* Create a Microservice with a spring-controller
* Run both mvnw and yarn start
* Window with port 9000 pops up
* Verify "Can't read swagger JSON from http://localhost:9000/test/v2/api-docs" in http://localhost:9000/#/admin/docs
* Change port to the one that was used for creation
* Verify that it works

##### **JHipster Version(s)**

I think it started with 5.6.0

##### **JHipster configuration**

	{
	  "generator-jhipster": {
		"promptValues": {
		  "packageName": "com.mycompany.myapp",
		  "nativeLanguage": "de"
		},
		"jhipsterVersion": "5.6.1",
		"applicationType": "gateway",
		"baseName": "TEST",
		"packageName": "com.mycompany.myapp",
		"packageFolder": "com/mycompany/myapp",
		"serverPort": "8080",
		"authenticationType": "jwt",
		"cacheProvider": "hazelcast",
		"enableHibernateCache": true,
		"websocket": false,
		"databaseType": "sql",
		"devDatabaseType": "h2Disk",
		"prodDatabaseType": "mysql",
		"searchEngine": false,
		"messageBroker": false,
		"serviceDiscoveryType": "eureka",
		"buildTool": "maven",
		"enableSwaggerCodegen": false,
		"jwtSecretKey": "MDI4NzNmZWJjN2Q3YWRmNTUxM2ZiYzk1OTJhMzU2M2JjYmEyYzcwMmVlY2MxYWRiOGY4Njk3YTZiN2M5YjJlZGM2ZmIwMmU1NGM0NjY2ZDBjMWRjZjllMGM4MWZkNjc2MzM1ZWI5MDM5OGY0NGEzMzBmYWQ5NDRkNjQ2NDdkMGU=",
		"clientFramework": "angularX",
		"useSass": true,
		"clientPackageManager": "npm",
		"testFrameworks": [
		  "gatling",
		  "cucumber",
		  "protractor"
		],
		"jhiPrefix": "jhi",
		"enableTranslation": true,
		"nativeLanguage": "de",
		"languages": [
		  "de",
		  "en",
		  "fr",
		  "it"
		]
	  }
	}

	{
	  "generator-jhipster": {
		"promptValues": {
		  "packageName": "com.mycompany.myapp",
		  "nativeLanguage": "de"
		},
		"jhipsterVersion": "5.6.1",
		"applicationType": "microservice",
		"baseName": "service",
		"packageName": "com.mycompany.myapp",
		"packageFolder": "com/mycompany/myapp",
		"serverPort": "8081",
		"authenticationType": "jwt",
		"cacheProvider": "no",
		"enableHibernateCache": false,
		"websocket": false,
		"databaseType": "no",
		"devDatabaseType": "no",
		"prodDatabaseType": "no",
		"searchEngine": false,
		"messageBroker": false,
		"serviceDiscoveryType": "eureka",
		"buildTool": "maven",
		"enableSwaggerCodegen": false,
		"jwtSecretKey": "YmQ0ZWFhOGYxOTM0OTdhZGNiMjA2MTMzZmJhMDg4MjgxZmFkNTlmZGFlZjRjMTdhNzk0YzVhNTM3ZTQ2NTJiY2M0NmNmZTFjNWU3M2JlNGNiNzJiNGZjMDJhOWY1N2M5NTQ1YjYwOGZlMmY2MjRlMzA4MzAxNjVjYjgwMjVhYzI=",
		"testFrameworks": [
		  "gatling",
		  "cucumber"
		],
		"jhiPrefix": "jhi",
		"enableTranslation": true,
		"clientPackageManager": "npm",
		"nativeLanguage": "de",
		"languages": [
		  "de",
		  "en",
		  "fr",
		  "it"
		],
		"skipClient": true,
		"skipUserManagement": true
	  }
	}

##### **Browsers and Operating System**

Working on Windows 10, tested with latest Firefox and Chrome

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
This seems like the normal behavior. Did you try port 9060 ? Have a look at the webpack proxy configuration for the specifics of what it does.

**Comment by Evertude** [comment]
I haven't changed any of the configuration that was generated by default so it doesn't seem normal to me if you have to change something or it won't work

**Comment by PierreBesson** [comment]
@evertude you are mistaken. Port 9000 is to serve static assets, a separate proxy for the API is set up on port 9060

**Comment by PierreBesson** [comment]
Anyway I will check your config tomorrow to see if there is an issue.

**Comment by Evertude** [comment]
I don't have enough knowledge on the topic, I can just tell you what I observe.

This is what I see when I run yarn start
![image](https://user-images.githubusercontent.com/7377709/48033535-f09e9b80-e15b-11e8-87cd-07c4a926c479.png)
It also opens a browser window on port 9000

**Comment by Evertude** [comment]
Okay, I found my problem and this could maybe be added to https://www.jhipster.tech/creating-a-spring-controller/:
I had to add the service to my dev webpack like the following:

    devServer: {
        contentBase: './target/www',
        proxy: [{
            context: [
	        '/service',
                /* jhipster-needle-add-entity-to-webpack - JHipster will add entity api paths here */
                ....

**Comment by deepu105** [comment]
@Evertude arent the controllers also under path `api` which is already on context?

**Comment by Evertude** [comment]
@deepu105 Yes they are, I used "jhipster spring-controller Foo" with a method bar for testing

	package com.mycompany.myapp.web.rest;

	import org.slf4j.Logger;
	import org.slf4j.LoggerFactory;
	import org.springframework.web.bind.annotation.PostMapping;
	import org.springframework.web.bind.annotation.RequestMapping;
	import org.springframework.web.bind.annotation.RestController;

	/**
	 * FooResource controller
	 */
	@RestController
	@RequestMapping("/api/foo")
	public class FooResource {

		private final Logger log = LoggerFactory.getLogger(FooResource.class);

		/**
		* POST bar
		*/
		@PostMapping("/bar")
		public String bar() {
			return "bar";
		}

	}

**Comment by ruddell** [comment]
@Evertude Can you submit a PR to [the docs](https://github.com/jhipster/jhipster.github.io/blob/master/pages/creating-a-spring-controller.md)?  

Normally this works because the developer generates an entity in the microservice, then imports that entity to the gateway, which adds the path to the gateway proxy config.  There's no way for JHipster to know about microservices when generating a gateway, so the paths aren't pre-filled.
