### ISSUE TITLE
Compilation error of Gateway project when I generated Full microservice stack using import-jdl 

### ISSUE THREAD

**Issue by yorkwu1977** [jhipster/generator-jhipster#8764]
##### **Overview of the issue**

I generated microservice stack using ‘jhipster import-jdl appstack.jdl’,  but the gateway project had compile error.

> error info:  The import org.hibernate.annotations cannot be resolved
```
import org.hibernate.annotations.Cache; 
import org.hibernate.annotations.CacheConcurrencyStrategy;
```

> error info: Id cannot be resolved to a type
```
    @Id
    private Long id;
```

> error info: Return type for the method is missing
``` 
    // jhipster-needle-entity-add-field - JHipster will add fields here, do not remove
    public  getId() {
        return id;
    }
```
>  error info: Syntax error, insert "... VariableDeclaratorId" to complete FormalParameterList
```
    public void setId( id) {
        this.id = id;
    }
```

##### **JHipster Version(s)**

5.6.0

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
application {
  config {
    baseName microservice1,
    applicationType microservice,
    authenticationType uaa,
    packageName com.company.appstack.microservice,
    serverPort 8081,
    uaaBaseName "uaa",
    databaseType sql,
    devDatabaseType h2Disk,
    prodDatabaseType mysql,
    serviceDiscoveryType eureka,
    buildTool maven
  }
  entities EntityA
}

application {
  config {
    baseName microservice2,
    applicationType microservice,
    authenticationType uaa,
    packageName com.company.appstack.microservice,
    serverPort 8081,
    uaaBaseName "uaa",
    databaseType sql,
    devDatabaseType h2Disk,
    prodDatabaseType mysql,
    serviceDiscoveryType eureka,
    buildTool maven
  }
  entities EntityB
}
application {
  config {
    baseName uaa,
    applicationType uaa,
    packageName com.company.appstack.uaa,
    serverPort 9999,
    authenticationType uaa,
    uaaBaseName "uaa",
    databaseType sql,
    devDatabaseType h2Disk,
    prodDatabaseType mysql,
    serviceDiscoveryType eureka,
    buildTool maven
  }
}

application {
  config {
    baseName gateway,
    applicationType gateway,
    authenticationType uaa,
    packageName com.company.appstack.gateway,
    serverPort 8080,
    uaaBaseName "uaa",
    databaseType no,
    serviceDiscoveryType eureka,
    buildTool maven
  }
  entities EntityA, EntityB
}

entity EntityA {
    data1 String
}

entity EntityB {
    data2 String
}

dto * with mapstruct
service * with serviceClass

```

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@yorkwu1977 you are missing `microservice EntityA with microservice1` and `microservice EntityB with microservice2` declarations. Not sure if that's the issue but in any case please try that and also try this JDL https://github.com/jhipster/jdl-samples/blob/master/microservice-ecommerce-store-4-apps.jdl

**Comment by yorkwu1977** [comment]
@deepu105  I add 'microservice EntityA with microservice1' and 'microservice EntityB with microservice2', 
 and now compile success!  thank your so much.
