### ISSUE TITLE
[Oracle] boolean fields generated as type bit in liquibase scripts

### ISSUE THREAD

**Issue by rubensa** [jhipster/generator-jhipster#8765]
##### **Overview of the issue**

For **Oracle** database, generated **liquibase** changelogs use **bit** type for **Boolean** fields.
The type should be the liquibase type **boolean**.

##### **Motivation for or Use Case**

For Oracle liquibase **boolean** type is generated as **number(1)** (**bit** is for SQL Server).  See https://dba-presents.com/index.php/liquibase/29-liquibase-3-3-x-data-types-mapping-table ).

JHipster generator should use liquibase types as much as possible to let liquibase do the type mapping.

##### **Reproduce the error**

Using **Model.jdl**:
```json
application {
  config {
    applicationType monolith
	authenticationType jwt
    baseName demo
	buildTool maven
	cacheProvider ehcache
	clientFramework angularX
	clientPackageManager npm
	databaseType sql
	devDatabaseType h2Disk
	enableHibernateCache true
	enableSwaggerCodegen false
	enableTranslation true
	jhiPrefix auto
	languages [en]
	messageBroker false
	nativeLanguage en
	packageName com.company.demo
	prodDatabaseType oracle
	searchEngine false
	serverPort 8080
	serviceDiscoveryType false
	skipServer false
	skipUserManagement false
	testFrameworks []
	useSass false
	websocket false
  }
  entities *
}

entity EntityOne {
    field1 Boolean
}
```

Run: ```jhipster import-jdl Model.jdl```

Generated **20181105110653_added_entity_EntityOne.xml**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd
                        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">

    <property name="now" value="now()" dbms="h2"/>

    <property name="now" value="sysdate" dbms="oracle"/>

    <property name="floatType" value="float4" dbms="postgresql, h2"/>
    <property name="floatType" value="float" dbms="mysql, oracle, mssql"/>

    <!--
        Added the entity EntityOne.
    -->
    <changeSet id="20181105110653-1" author="jhipster">
        <createTable tableName="entity_one">
            <column name="id" type="bigint" autoIncrement="${autoIncrement}">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="field_1" type="bit">
                <constraints nullable="true" />
            </column>

            <!-- jhipster-needle-liquibase-add-column - JHipster will add columns here, do not remove-->
        </createTable>
        
    </changeSet>
    <!-- jhipster-needle-liquibase-add-changeset - JHipster will add changesets here, do not remove-->
</databaseChangeLog>
```

##### **Suggest a Fix**

In file **20181105110653_added_entity_EntityOne.xml** change from:

```xml
<column name="field_1" type="bit">
```
to
```xml
<column name="field_1" type="boolean">
```

##### **JHipster Version(s)**

JHipster v5.6.0

##### **JHipster configuration**

Using JHipster version installed globally
Executing jhipster:info
Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
demo@0.0.0 /media/data/rubensa/development/vscode/workspace/prueba
└── generator-jhipster@5.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "auto",
    "languages": [
      "en"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.company.demo",
    "packageFolder": "com/company/demo",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "demo",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "serverPort": "8080",
    "skipUserManagement": false,
    "useSass": false,
    "jhipsterVersion": "5.6.0",
    "jwtSecretKey": ""
  },
  "entities": [
    "EntityOne"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity EntityOne {
  field1 Boolean
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)

git version 2.17.1

node: v8.11.3

npm: 5.6.0

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.21.2, build a133471

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

**EntityOne.json**
```json
{
    "name": "EntityOne",
    "fields": [
        {
            "fieldName": "field1",
            "fieldType": "Boolean"
        }
    ],
    "relationships": [],
    "changelogDate": "20181105110653",
    "entityTableName": "entity_one",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": [
        "demo"
    ]
}
```

##### **Browsers and Operating System**

Linux 4.15.0-38-generic Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Yes, agree. We should use liquibase types everywhere so that it works
across DBs

Thanks & Regards,
Deepu

**Comment by ruddell** [comment]
@rubensa Would you like to create a pull request?  The [change looks simple](https://github.com/jhipster/generator-jhipster/blob/f534a1b5b7e38f8ebe55f28d8ea3f158da295d24/generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs#L101-L105)

Related to https://github.com/jhipster/generator-jhipster/pull/4590#issue-95995136 from 2 years ago that I forgot to follow up on
