### ISSUE TITLE
Jhipster gateway entity generator assumes that id is of type number

### ISSUE THREAD

**Issue by Evertude** [jhipster/generator-jhipster#8766]
##### **Overview of the issue**

When using MongoDB in a micro service, the type of generated entities' ID field is string.
When consuming this entity in a gateway, the assumed type is always number
It is not possible to define the id field in the entity json because it will generate a second field.

##### **Motivation for or Use Case**

I use a microservice architecture with MongoDB

##### **Reproduce the error**

* Generate a microservice with MongoDB database
* Generate any entity
* Generate a gateway
* Call entity generator with option from existing micro service
* Verify that the generated id type in the gateway is number

##### **Suggest a Fix**

Either add the id field to the json definition or check database type when generating entities from existing micro services

##### **JHipster Version(s)**

5.6.1

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "de",
      "microservicePath": "../service"
    },
    "jhipsterVersion": "5.6.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZjQwYmViZTE3ZGJjZTY3YWUyYTc3YTQ3ZWFiZmVhZmVhZGRlOGIyZjkzYjg3NzVlMDZmOTVkMDk1MGZlNDJiNjUyZDVhMDlhNjI0ZDNlMzcwYmQ1ZDE4MmFhZjJmZWUwMzFkYWIxMzU4NWVlN2YzMDU4MjY1MWJjNjVhY2YxYTQ=",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en",
      "fr",
      "it"
    ]
  }
}
```
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "5.6.1",
    "applicationType": "microservice",
    "baseName": "service",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZjgwOWQ3YjJjY2I5NmJkODBlNGI0ZmZiYTQ3YmE4N2M2YWFhMGViNDQ0NTUyZGUyNmFjOGI2NGY4ODRiNjU4NmI0ZGFmNTM3YzM5ODU0M2QzMjAyNDhkYjIzNGE3ZmJiZThlZTFjYmQ1YjNjZDQ5NzViMjUzM2IwNzUwMTcyN2M=",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en",
      "fr",
      "it"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
```
{
    "fluentMethods": true,
    "clientRootFolder": "service",
    "relationships": [],
    "fields": [],
    "dto": "no",
    "searchEngine": false,
    "service": "no",
    "entityTableName": "my_entity",
    "jpaMetamodelFiltering": false,
    "pagination": "no",
    "microserviceName": "service"
}
```

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
We did a workshop with microservices last week, with JHipster 5.5.0 and I'm pretty sure it works.

What is the error ? Do you have some stacktrace or error in console of your browser ?

**Comment by Evertude** [comment]
You are right, it works because you assign a string to a number and its not checked but I think it's against the common sense that you get a string if you actually expect a number.
I also debugged it to check if it's not a hex value which would make more sense.

Design time
![image](https://user-images.githubusercontent.com/7377709/48084736-cbac3600-e1f8-11e8-8d2e-f3052a516e23.png)
Run time
![image](https://user-images.githubusercontent.com/7377709/48084816-f8f8e400-e1f8-11e8-88a6-ce1186e78f0c.png)

**Comment by pascalgrimaud** [comment]
I confirm the issue, although it is minor.

The real problem comes from the json file from the Microservice and used by the Gateway.
This json file doesn't contain the information to know the databaseType of the Microservice, so when generating the "id", it can't determine the correct type (String).

Here my gateway and the Invoice.json entity from a Microservice using MongoDB:
https://github.com/pascalgrimaud/jhi-store/blob/master/.jhipster/Invoice.json#L70

I think this JSON should contain the databaseType.

**Comment by pascalgrimaud** [comment]
@MathieuAA : here the ticket, I talk you about. What do you think about that ?

**Comment by MathieuAA** [comment]
That I won't like it ;)

**Comment by jdubois** [comment]
I understand this is annoying so I add a $100 bug bounty
