### ISSUE TITLE
Non-required boolean should be supported

### ISSUE THREAD

**Issue by einar-saukas** [jhipster/generator-jhipster#8777]
##### **Overview of the issue**

Generated front-end code cannot distinguish between "field Boolean" and "field Boolean required".

##### **Motivation for or Use Case**

Omitting the "required" keyword should make it possible to set this field to NULL. However this behavior works correctly for all datatypes except "Boolean".

The generated front-end code currently doesn't allow setting a non-required Boolean field to NULL. A non-required Boolean field is always initialized to FALSE, and there's no way to change it to NULL using the front-end.

This behavior is not consistent with all other datatypes, where non-required fields can be cleared (thus explicitly assigning them to NULL).

##### **Reproduce the error**

1. Generate an application using this JDL:

```
application {
	config {
		baseName sample
		packageName com.sample
		prodDatabaseType mysql
	}
	entities *
}

entity Candidate {
    paidKind Boolean required,
    taskPaid Boolean,
}
```

2. Run the generated application

3. Using the web interface, create a new Candidate. Both fields "paidKind" and "taskPaid" will be initialized to FALSE. Now there's no way to change "taskPaid" to NULL using the web interface.

4. Update the database manually:

`update CANDIDATE set TASK_PAID = null
`

5. Using the web interface, refresh the list of Candidates. Now field "paidKind" is FALSE and "taskPaid" is NULL, as expected.

6. Using the web interface, click to edit this instance. Click on "taskPaid" to enable it, again on "taskPaid" to disable it again, then save it. It will remain NULL.

7. Using the web interface, click to edit this instance. Click on "taskPaid" to enable it, then save it. It will become TRUE.

8. Using the web interface, click to edit this instance. Click on "taskPaid" to disable it, then save it. It will become FALSE. Now there's no way to change "taskPaid" to NULL using the web interface (except updating the database manually again).

##### **Related issues**

Apparently previous work on fixing required boolean in issue #5289 was responsible for breaking non-required boolean...

##### **Suggest a Fix**

I suggest modifying the front-end code to adopt the following behavior:

1. Required Boolean:

* Should be initialized to FALSE by default;
* The web interface component should only alternate between FALSE and TRUE (obviously), exactly like current behavior.

2. Non-required Boolean:

* Should be initialized to NULL by default;
* The web interface component should alternate between 3 states: FALSE, TRUE, NULL. I suggest a visual representation similar to this:

https://i.stack.imgur.com/hzPlz.png

##### **JHipster Version(s)**

```
sample@0.0.0 C:\stuff\jhipster\sample
`-- generator-jhipster@5.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.sample",
    "packageFolder": "com/sample",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "sample",
    "jhipsterVersion": "5.6.0",
    "buildTool": "maven",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "useSass": true,
    "jwtSecretKey": "..."
  },
  "entities": [
    "Candidate"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Candidate {
  paidKind Boolean required,
  taskPaid Boolean
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.11.0.windows.1

node: v10.13.0

npm: 6.4.1

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

File "Candidate.json":

```
{
    "name": "Candidate",
    "fields": [
        {
            "fieldName": "paidKind",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "taskPaid",
            "fieldType": "Boolean"
        }
    ],
    "relationships": [],
    "changelogDate": "20181108014633",
    "entityTableName": "candidate",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": [
        "sample"
    ]
}
```

##### **Browsers and Operating System**

Tested on Firefox 63.0.1 (64-bit) on Windows 7 Professional,

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by einar-saukas** [comment]
A simple good solution was proposed here (last alternative in this article):

https://css-tricks.com/indeterminate-checkboxes/

**Comment by pascalgrimaud** [comment]
@einar-saukas : I'm closing this ticket as there is a similar one https://github.com/jhipster/generator-jhipster/issues/8786
We can go on there, and discuss about it.
