### ISSUE TITLE
Optimizing the JSon output for comboboxes

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#8782]
##### **Overview of the feature request**

It would be great for performances to decrease the weight of the JSon sent from the server to fill a combobox.

##### **Motivation for or Use Case**

I wrote a blog post[2] about using the auto-complete component of PrimeNG but also on how to use JSonView[4] to optimise the JSon output for comboboxes. I talked about this idea with Julien, Pascal and Pierre who thought it was a good idea, so here is an explanation.

I’ve coded an example[1] so you can have a look if you want. It’s about a `Contact` having a `Language`. As you can imagine, when creating a contact, there is a language combobox so you can select a language. And because the language entity is quite complex (id, alpha2 code…), this is the JSon that is produced to populate the combobox.

```
{
  "id" : 19,
  "alpha3b" : "ben",
  "alpha2" : "bn",
  "name" : "Bengali",
  "flag32" : "",
  "flag128" : "",
  "activated" : false
}, {
  "id" : 39,
  "alpha3b" : "eng",
  "alpha2" : "en",
  "name" : "English",
  "flag32" : "GB-32.png",
  "flag128" : "GB-128.png",
  "activated" : true
}, {
  "id" : 46,
  "alpha3b" : "fre",
  "alpha2" : "fr",
  "name" : "French",
  "flag32" : "FR-32.png",
  "flag128" : "FR-128.png",
  "activated" : true
}, {
  ...
}
```

But what we really need for the combox, is the id and name :

```
{
  "id" : 19,
  "name" : "Bengali"
}, {
  "id" : 39,
  "name" : "English"
}, {
  "id" : 46,
  "name" : "French"
}, {
  ...
}
```

Of course, the entity/DTO could be even more complex with one to one relationships and so on. So the JSon can be very very verbose, but at the end of the day, we just need the id, or, id + some label for the combobox.

To optimize the JSon output, JHipster could use the `JSonView` annotation of Jackson. 

```
public class LanguageDTO implements Serializable {

    @JsonView(View.Minimal.class)
    private Long id;

    @NotNull
    @Size(max = 3)
    private String alpha3b;

    @NotNull
    @Size(max = 2)
    private String alpha2;

    @JsonView(View.Minimal.class)
    @NotNull
    private String name;

    private String flag32;

    private String flag128;

    private Boolean activated;
```

As you can see, the Id and name are annotated with `@JsonView(View.Minimal.class)` (`View` and `Minimal` are just arbitrary names, it could be `Format.Minimal`, `View.Id`... as we all know, naming is hard).

The REST endpoint would have two different methods: one to get all the languages with all the details (used for the main list, with url http://localhost:9000/api/languages) and one to get the minimal needed for the combobox (with url http://localhost:9000/api/languages/minimalview) :

```
    @GetMapping("/languages")
    @Timed
    public ResponseEntity<List<LanguageDTO>> getAllLanguages(LanguageCriteria criteria, Pageable pageable) {
        log.debug("REST request to get Languages by criteria: {}", criteria);
        Page<LanguageDTO> page = languageQueryService.findByCriteria(criteria, pageable);
        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(page, "/api/languages");
        return ResponseEntity.ok().headers(headers).body(page.getContent());
    }

    @GetMapping(value = "/languages/minimalview")
    @JsonView(View.Minimal.class)
    @Timed
    public ResponseEntity<List<LanguageDTO>> getAllLanguagesMinimalView(LanguageCriteria criteria, Pageable pageable) {
        log.debug("REST request to get Languages with Minimal View by criteria: {}", criteria);
       return getAllLanguages(criteria, pageable);
    }
```

Again, finding a good name for the URL is not easy as you could use:
* api/languages/minimalview
* api/languages?view=minimal
* api/languages?format=minimal
* use HTTP headers

On the TypeScript side we could have two different methods in the service:

```
query(req?: any): Observable<EntityArrayResponseType> {
   const options = createRequestOption(req);
   return this.http.get<ILanguage[]>(this.resourceUrl, { params: options, observe: 'response' });
}

queryMinimalView(req?: any): Observable<EntityArrayResponseType> {
   const options = createRequestOption(req);
   return this.http.get<ILanguage[]>(this.resourceUrl + '/minimalview', { params: options, observe: 'response' });
}
```

The way to automatically generate this code would be to look at the JDL. Below we only have a many to one relationship between `Contact` and `Language`:

```
relationship ManyToOne {
    Contact to Language
}
```

In this case, we only have a `JSonView` on the ID (by default, every id of every Entity/DTO should have a JSonView):

```
public class LanguageDTO implements Serializable {

    @JsonView(View.Minimal.class)
    private Long id;

    @NotNull
    private String name;

    @NotNull
    @Size(max = 3)
    private String alpha3b;
```

But most of the time having the ID is not enough in a combobox. The JDL allows us to use an attribute instead (here, name). 

```
relationship ManyToOne {
    Contact{language(name)} to Language
}
```

In this case, we would add a second JSonView to the name attribute.

```
public class LanguageDTO implements Serializable {

    @JsonView(View.Minimal.class)
    private Long id;

    @JsonView(View.Minimal.class)
    @NotNull
    private String name;

    @NotNull
    @Size(max = 3)
    private String alpha3b;
```

What do you think ?

[1] https://github.com/agoncal/agoncal-sample-jhipster/tree/master/jacksonviews
[2] https://antoniogoncalves.org/2018/11/08/jhipster-angular-primeng-and-autocomplete/
[3] https://grokonez.com/java-integration/integrate-spring-restapis-jsonview
[4] https://www.baeldung.com/jackson-json-view-annotation

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by antarus** [comment]
I love the idea, maybe we should optimize the jpa request that will return all the attributes of the entity before being truncated by jakson?

**Comment by amatosg** [comment]
could this be also filtered like `"minimal.equals" : "true"`? (or something like that)

**Comment by agoncal** [comment]
@amatosg what do you mean by that ? Something like  /api/languages?minimal.equals=true ?

I am not totally happy with the way we do it, but we use different paths (which is easier for the front-end team). So we usually have two views (we call them `Combo` and `List`, but as you know, naming is hard) therefore we have 3 paths:

* /api/languages
* /api/languages/viewcombo
* /api/languages/listcombo

**Comment by amatosg** [comment]
@agoncal yeah, just like that, would that avoid having multiple endpoints for each entity?

**Comment by batterista87** [comment]
I have the same problem, but I manage this on the Java side with different solutions, for example using the Projection, or using the Criteria API in custom repositories in order to select only some fields of an entire entity, or using different entity/DTO mappers.

The endpoit can be one, and the workflow is managed by a boolean parameter from front-end for example "isMenuLoading".

**Comment by agoncal** [comment]
@batterista87 any code you could share with us ?

**Comment by avdev4j** [comment]
Hi,
And what about [Partial Response](https://developers.google.com/drive/api/v3/performance)**?

Something like "/ api / languages ​​/ viewcombo" mean "viewCombo" is a  sub-resource of "languages", I don't think it's what is intended.

With Partial Response the API looks like "/api/languages?fields=id,value" and the HTTP returned code will be 206.
`[{
       "id": 1,
       "value": "English"
},{
       "id": 2,
       "value": "French"
}]`

I think it's a really cool feature and a real improvement, why not something that JHipster can handle...

** Another article to read:  [Partial Response in RESTful API Design](http://yaoganglian.com/2013/07/01/partial-response/)

**Comment by agoncal** [comment]
In a previous project we used partial responses. It was very powerful but we found it difficult to maintain in the long run (eg. you get rid or rename an attribute and the client API needs to be updated) and the users of the APIs found it verbose.

But all in all, I quite liked it.

**Comment by jdubois** [comment]
I think we all agree this is a good idea, but this has been stuck for more than 2 months and we have tons of issues -> I'm closing this as nobody works on it, but if anybody wants to do the PR it's most welcomed
