### ISSUE TITLE
Restrict Node.js LTS dependency on Chocolatey

### ISSUE THREAD

**Issue by SteffanUA** [jhipster/generator-jhipster#8798]
##### **Overview of the issue**

Chocolatey installs nodejs-lts (≥ 8.12.0) alongside jhipster as a dependency and with the release of node 10.13.0 LTS there is a major version change which will be downloaded instead of version 8.*

##### **Motivation for or Use Case**

Node version 10.13.0 is not compatible with some packages used in jhipster at the moment and this breaks when running applications

##### **Reproduce the error**
Install Jhipster with chocolatey 

`choco install jhipster` 

select [y] to install all dependencies when prompted. 
Generate a jhipster gateway with react frontend and run

`yarn install`

##### **Suggest a Fix**

Restrict Node LTS dependency to nodejs-lts (8.12.0) instead of nodejs-lts (≥ 8.12.0)  

##### **JHipster Version(s)**

5.6.0

##### **Browsers and Operating System**

Windows 10 pro

-   [+] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
> Node version 10.13.0 is not compatible with some packages used in jhipster at the moment and this breaks when running applications

Can you give more details about this ?
In the core team, few people use Windows 10, so maybe we miss something ?

**Comment by ruddell** [comment]
I think we need to change the version for nodejs here: https://chocolatey.org/packages/jhipster, it looks like @jdubois has done it in the past based on the comments there

**Comment by ruddell** [comment]
@SteffanUA Can you describe which packages fail in nodejs v10?  As that is the new LTS version, we should upgrade to that.  I didn't notice any issues on Mac, but I don't have a WIndows computer to test.

**Comment by gmarziou** [comment]
@SteffanUA I don't understand this issue.

Currently our pom.xml references node 10.13.0 and frontend-maven-plugin installs it and builds an angular or react monolith without any problem (I tested both on WIndows 10), it uses it independently from what is installed on developer's PC. 
So this works well without Chocolatey.

I also tested with npm start (so not using frontend-maven-plugin) and haven't seen an error with 10.13.O on Windows 10 Pro.

**Comment by jdubois** [comment]
Yes indeed I'm doing this, and update the Chocolatey package with each of our releases. As we are currently using Node 10 LTS (which is normal, we always support the LTS release), I also updated the Chocolatey script to use Node 10 LTS.

Then, this shouldn't cause any issue as we do support Node 10 LTS: if there is an error, this isn't a Chocolatey issue, it's a bug in our Node 10 LTS support.

At the moment there is no such error that I know of, and @SteffanUA you don't give that error -> in order to keep the bug tracker clean, I'm closing this, and if @SteffanUA you have some errors with Node 10 LTS, can you open an another ticket with full information on that error?

**Comment by pascalgrimaud** [comment]
@jdubois : shouldn't we upgrade this https://github.com/jhipster/chocolatey-package/blob/master/jhipster.nuspec#L26 ?

**Comment by jdubois** [comment]
@pascalgrimaud oh sorry, I thought I already did this!! Yes you are correct.

**Comment by pascalgrimaud** [comment]
It's my fault, I forgot this repo when upgrading to Node 10.13.0 LTS.
I'll add it to my personnal repo list when upgrading Node.
