### ISSUE TITLE
Proposed new keywords: "key" and "provided-key"

### ISSUE THREAD

**Issue by einar-saukas** [jhipster/generator-jhipster#8799]
##### **Overview of the feature request**

In JHipster JDL, IDs are defined implicitly. For instance, consider this JDL:

```
entity Language {
        name String required,
        nativeName String
}
```

In this case, an additional field will be automatically defined as "id Long required", and declared as PRIMARY KEY with AUTO_INCREMENT. The corresponding domain class in Java will have:

```
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;
```

Even if a field called "id" is explicitly declared in the JDL, it's ignored (producing a warning) and it's still automatically defined as "id Long required" anyway. For instance, this JDL below will produce exactly the same result (still using "Long" instead of "Integer"):

```
entity Language {
        id Integer required,
        name String required,
        nativeName String
}
```

I think this behavior described above is perfectly fine. I'm not suggesting any changes to it.

However I propose extending current behavior with 2 new (optional) keywords, as follows:

1. NEW KEYWORD "key"

Use keyword "key" to explicitly declare an entity id in JDL, to control its name and datatype. For instance:

```
entity Language {
        id Integer key,
        name String required,
        nativeName String
}
```

In this case, the generated code will be exactly the same, except using datatype "Integer" instead of "Long". The corresponding domain class in Java will be:

```
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Integer id;
```

Another example:

```
entity Language {
        numCode Integer key,
        name String required,
        nativeName String
}
```

In this case, the generated code will be exactly the same, except using field name "numCode" instead of "id". The corresponding domain class in Java will be:

```
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Integer numCode;
```

Notice that keyword "key" will only work for numeric datatypes, due to the auto generation strategy. In practice, it will greatly increase JHipster flexibility to match already existing databases, since users will be able to control column name and datatype of primary keys, without making any significant changes to JHipster or making it any harder to use.

2. NEW KEYWORD "provided-key"

Use keyword "provided-key" to explicitly declare an entity id in JDL, making it an explicit parameter to be provided by users (when using "create new entity" in the front-end interface), besides also controlling its name and datatype. For instance:

```
entity Language {
        id Integer provided-key,
        name String required,
        nativeName String
}
```

In this case, an additional field will be automatically defined as "id Integer required", and it will be declared as PRIMARY KEY but WITHOUT the AUTO_INCREMENT. The corresponding domain class in Java will have:

```
@Id
private Integer id;
```

In this case, the "create" (POST) operation will require this new id to be provided explicitly by users, along with all other fields.

Another example:

```
entity Language {
        isoCode String provided-key,
        name String required,
        nativeName String
}
```

In this case, the generated code will be exactly the same, except using field name "isoCode" instead of "id", with datatype String. The corresponding domain class in Java will be:

```
@Id
private String isoCode;
```

Notice that keyword "provided-key" will work for any datatypes, not just numeric, since it won't have automatic generation of keys (these values will be explicitly provided by users instead). Again this will greatly increase JHipster flexibility to match already existing databases, without making any significant changes to JHipster or making it any harder to use.

##### **Motivation for or Use Case**

Real life databases don't always have all primary keys declared as long auto-increment called "id" in every table.

A practical example is a table to store natural languages (i.e idioms). In this table, using the international standard ISO 639-1 codes (such as 'en' and 'fr') as PRIMARY KEY makes more sense than arbitrarily auto generated numbers. They are more meaninful, and the underlying database performance is exactly the same (if they are declared as CHAR(2) instead of INTEGER).

##### **Related issues or PR**

It seems nothing similar has been requested here yet.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@einar-saukas sorry, we have been having this request many times and we always decided against it as its a lot of work to implement & maintain for the small benefit it gives. So I'm sorry that we have to reject this request. We don't want to make JDL a JPA/Bean replacement. I understand your use case but the cost of maintenance is too high for this.
