### ISSUE TITLE
Proposed new keyword: "readonly"

### ISSUE THREAD

**Issue by einar-saukas** [jhipster/generator-jhipster#8800]
##### **Overview of the feature request**

At the end of JDL file, users could add something like:

`readonly *
`

Or

`readonly A, B, C
`

Or

`readonly * except D, E
`

Entities defined as read-only should work almost exactly like others, with just a few differences:

* Frontend should only provide list and "View" pages for these entities. It won't provide "Create new", "Edit" or "Delete" options.

* Backend should only generate "findOne" and "findAll" methods for these entities. It won't generate "save" (create/update) and "delete" methods.

* Database won't need AUTO_INCREMENT in table id for these entities (thus no need for @GeneratedValue in entity id declaration).

##### **Motivation for or Use Case**

* Sometimes an application must also reference some external data, such as additional tables imported periodically from a third-party system, or replicated online from another database, or simply managed by a different application. In this case, it's necessary to map these external tables because of relationships with other application tables referencing them, but the external tables must never be changed by the application.

* Sometimes applications need some kind of fixed "domain" information, stored in the database instead of hard-coded enums, that shouldn't be modified by the application. In this case, it can be useful to visualize this information inside the application (especially when editing entities referencing them), without ever modifying this information from the application itself.

##### **Related issues or PR**

It seems no similar features have been requested yet.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
This is actually a useful feature. @jdubois @MathieuAA WDYT?

**Comment by jdubois** [comment]
Yes this is useful.

**Comment by deepu105** [comment]
This can be a JDL only feature and for entity subgen may be we can add a
flag

Thanks & Regards,
Deepu

**Comment by DanielFran** [comment]
+1 for mee too

**Comment by Tcharl** [comment]
Really useful in my context, I would love to have it!

**Comment by pascalgrimaud** [comment]
@einar-saukas : as there are a lot of +1, do you want to contribute on this ?

**Comment by einar-saukas** [comment]
I'm sorry but I won't have time to work on it. :(

**Comment by pascalgrimaud** [comment]
It is an interesting feature but as no one want or have the time to work on this, let's close this.

**Comment by hdaniel93** [comment]
Hey guys, myself and a few others are thinking of taking on this feature. Having never worked on an open source project before, can anyone point me to in the codebase some examples we can use as a base? At its core its simply adding @Immutable to the JPA class and not generating certain stuff which seems simple enough

**Comment by hdaniel93** [comment]
@MathieuAA @pascalgrimaud @deepu105  I made this post https://github.com/jhipster/generator-jhipster/issues/9562 Dont suppose you have any advice?

**Comment by pascalgrimaud** [comment]
@hdaniel93 : I closed this ticket because it was opened for 4 months and no work has been done. But if you want to contribute and push this feature, you're welcome ! :)

**Comment by ddsultan** [comment]
Is this still open?

**Comment by pascalgrimaud** [comment]
@ddsultan : no it's closed. It's already avaiblable in the last releases
