### ISSUE TITLE
No ".war.original" generated from "gradlew -Pprod bootWar"

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#8811]
##### **Overview of the issue**
Gradle doesn't generate a .war.original.  The docs (https://www.jhipster.tech/production) say it should when running `./gradlew -Pprod bootWar`

Originally reported by @campbellmcneill in the Gitter

##### **Motivation for or Use Case**
This file is normally used when deploying to application servers

##### **Reproduce the error**
- Generate a gradle project
- `./gradlew -Pprod bootWar`

##### **Suggest a Fix**
Not sure, I don't use gradle

##### **JHipster Version(s)**
Affects all v5 versions (confirmed with master and v5.0.0)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.6.1",
    "applicationType": "monolith",
    "baseName": "gradle",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**
<details>
<summary>Environment and Tools</summary>

<pre>

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.18.0

node: v8.11.4

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

</pre>
</details>

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Looks like that behaviour has changed with the boot 2 Gradle plugin. But it
looks like it can be activated again. Will try it.

Am Di., 13. Nov. 2018, 00:10 hat Jon Ruddell <notifications@github.com>
geschrieben:

**Comment by atomfrede** [comment]
Adding 

```
    enabled = true
    classifier = 'original'
```

to the war task works, but the war is only generated when explicitly executing the war task. `bootWar` doesn't trigger the war task anymore. So two questions:

* How is maven behaving?
* I would just adapt the documentation and not enable add the above lines as comment to the gradle build file as we want to switch to jar files anyway  with jh6 if I remember correct

**Comment by campbellmcneill** [comment]
That worked for me fine to get the slim war from Gradle.

**Comment by atomfrede** [comment]
I will handle it don't worry
