### ISSUE TITLE
Duplicate CSS Selector

### ISSUE THREAD

**Issue by Fydon** [jhipster/generator-jhipster#8813]
##### **Overview of the issue**

`.app-loading .lds-pacman` exists twice in loading.css.ejs for both React ([1][3] and [2][4]) and Angular ([1][1] and [2][2]). These should be merged.

##### **Motivation for or Use Case**

It will be easier to read see what styles are being applied if there is only one instance of a selector.

Stylelint detected this. Prettier performs a few code changes, but Stylelint goes beyond those and [should be able to work along side Prettier][5]. Is there any reason that Stylelint isn't being used in this project?

##### **Reproduce the error**

N/A

##### **Related issues**

None found

##### **Suggest a Fix**

Merge both selectors into one.

##### **JHipster Version(s)**

```
prototype@0.0.0 
`-- generator-jhipster@5.5.0

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "example",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.17.1.windows.2

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

-   [X] Checking this box is mandatory (this is just to show you read everything)

[1]: https://github.com/jhipster/generator-jhipster/blob/749e192700281c07bccf41dac0f2801f7f140bbf/generators/client/templates/angular/src/main/webapp/content/css/loading.css.ejs#L105
[2]: https://github.com/jhipster/generator-jhipster/blob/749e192700281c07bccf41dac0f2801f7f140bbf/generators/client/templates/angular/src/main/webapp/content/css/loading.css.ejs#L150
[3]: https://github.com/jhipster/generator-jhipster/blob/095d8ade7759ed14604d8ef8d246f2306245d170/generators/client/templates/react/src/main/webapp/static/css/loading.css.ejs#L105
[4]: https://github.com/jhipster/generator-jhipster/blob/095d8ade7759ed14604d8ef8d246f2306245d170/generators/client/templates/react/src/main/webapp/static/css/loading.css.ejs#L150
[5]: https://github.com/prettier/stylelint-config-prettier

**Comment by pascalgrimaud** [comment]
@Fydon : would you like to contribute and PR the fix ?
