### ISSUE TITLE
Custom validators JSR-303 does not get injected for autowired fields in integration test

### ISSUE THREAD

**Issue by Blackdread** [jhipster/generator-jhipster#8818]
##### **Overview of the issue**

Autowired fields in custom validators are not injected in integration test

##### **Motivation for or Use Case**

Make tests work :)

##### **Reproduce the error**

Create a custom annotation for validation and a custom ConstraintValidator<A extends Annotation, T>, put Autowired service/etc in it, it will be null for integration test

##### **Related issues**

None

##### **Suggest a Fix**

See pull request #8819

##### **JHipster Version(s)**

5.0.1

##### **JHipster configuration**

Nothing special

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Any

##### **Browsers and Operating System**

W10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Closing as PR is merged
