### ISSUE TITLE
Entity: Getter for a boolean attribute prefixed by 'is' should not add prefix 'is'

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#8822]
##### **Overview of the issue**

Using the following JDL : 
```
entity A {
    isDeleted Boolean required
}
```

The generated Entity `A.java` has the following getter : 
```
public Boolean isIsDeleted() {
         return isDeleted;
 }
```

##### **Motivation for or Use Case**

Generated getter does not match usual practice in java, and generated getter by IDE.

##### **Suggest a Fix**

Detect `is` prefix in attribute, and then do not add a prefix to generated getter.

##### **JHipster Version(s)**

5.4.2

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

See above

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by cbornet** [comment]
We don't have a choice on how the getter should be named. If the attribute is `foo`, the getter shall be `getFoo` as per the Java bean contract.
Now we do have an issue which has been pointed out in another issue: the `is` getter shall only be used for the primitive `boolean` and not for the wrapper ̀Boolean`. I think this will be adressed by PR #8820 . 
So if `isDeleted` is `required` the getter shall be `boolean isIsDeleted` and if not required it shall be `Boolean getIsDeleted`.

**Comment by murdos** [comment]
@cbornet I'm perfectly aware of PR #8820 (you can see my comments on the PR). I discovered this issue while doing some tests for the PR.

Java Bean Specification indeed doesn't talk about this specific case, but it seems to be usual practice to not generate `isIsXXX` : 
- [lombok](https://projectlombok.org/features/GetterSetter) does not do it:
> For boolean fields that start with is immediately followed by a title-case letter, nothing is prefixed to generate the getter name. 
- IDE don't do it either (tested IntellIJ, but I guess Eclipse too)

**Comment by cbornet** [comment]
Indeed @murdos, you're right ! The field name doesn't really matter in JavaBean since it only uses the getters and setters.

**Comment by cbornet** [comment]
One thing to verify : does it work with Jackson as you would expect ?

**Comment by MathieuAA** [comment]
By the way, isXXX implies a function, method. Not necessarily a field. It's actually considered "clean code"

**Comment by jdubois** [comment]
Here we are bindly following the spec: if you call your field "isDeleted" then you will get a "isIsDeleted" method, and that's logical, and you shouldn't give a name with a verb in your variable in the first place.
That being said, indeed we could be smarter and detect this, and call it "isDeleted" as I don't think any tool has a look at the underlying variable name -> from what I read here, this is what other projects are doing, and that's indeed a good solution.

@cbornet I was also afraid of how Jackson would work as we use its Afterburner module, but I just tested and it worked without any issue.

So +1 one for adding a quick check and solve this - @murdos you are welcome to do the PR. Otherwise I don't think this is very important, so we might close it if there is a lack of interest.

**Comment by murdos** [comment]
Fine! Thanks for testing it @jdubois 
I'll work on it, I love making JHipster smarter ;-)

**Comment by pascalgrimaud** [comment]
@murdos : are you still working on this ? Or plan to do it ? Otherwise, as Julien said, we can close this.

**Comment by murdos** [comment]
Yes, I plan to work on it.

**Comment by pascalgrimaud** [comment]
Sorry again @murdos : could it be done before the release of v6 ?

**Comment by murdos** [comment]
Ok. I'm currently working on it. 
If it's bigger that what I thought (I was only thinking about server side originally), I'll given up and close the ticket.

**Comment by murdos** [comment]
So I made a first attempt at it: https://github.com/murdos/generator-jhipster/commit/5ced7eb9025ab13f43192e397f44dc01b68261ab but integration tests won't work:
```
[ERROR] getAllASByNameIsInShouldWork  Time elapsed: 0.144 s  <<< FAILURE!
java.lang.AssertionError:
JSON path "$.[*].isDeleted"
Expected: a collection containing <false>
     but:
        at com.mycompany.myapp.web.rest.AResourceIT.defaultAShouldBeFound(AResourceIT.java:266)
        at com.mycompany.myapp.web.rest.AResourceIT.getAllASByNameIsInShouldWork(AResourceIT.java:240)
```
Indeed it implies to consider the field without the prefix in the JSON DTO and thus on the client side. So it goes back to remove the prefix when interpreting the JDL, and I'm really not sure that's something we want to do. Users won't understand that we're modifying things on their back.

Thus I'm closing this request.
