### ISSUE TITLE
PostgreSQL with Docker-Compose: fails to start sometimes

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#8841]
##### **Overview of the issue**

If I generate a microservices stack with the following JDL, everything usually starts great the first time.

```
application {
  config {
    baseName gateway,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    searchEngine elasticsearch,
    serviceDiscoveryType eureka,
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    searchEngine elasticsearch,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    searchEngine elasticsearch,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

// will be created under 'docker-compose' folder
deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
  monitoring elk
  consoleOptions [zipkin]
}

// will be created under 'kubernetes' folder
deployment {
  deploymentType kubernetes
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
  monitoring elk
  consoleOptions [zipkin]
}
```

However, sometimes the blog app fails to start with the following error:

```
blog-app_1                    | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'(inner bean)#143900a6': Cannot resolve reference to bean 'entityManagerFactory' while 
setting constructor argument; nested exception is 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'liquibase' defined in class path resource 
[com/okta/developer/blog/config/LiquibaseConfiguration.class]: Invocation of init method 
failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed 
for change set 
config/liquibase/changelog/20181115123709_added_entity_Blog.xml::20181115123709-1::jhipster:
blog-app_1                    |      Reason: liquibase.exception.DatabaseException: ERROR: 
relation "blog" already exists [Failed SQL: CREATE TABLE public.blog (id BIGINT NOT NULL, 
name VARCHAR(255) NOT NULL, handle VARCHAR(255) NOT NULL, user_id VARCHAR(100), CONSTRAINT 
PK_BLOG PRIMARY KEY (id))]
```

##### **Motivation for or Use Case**

Starting the apps with `docker-compose up` should work every time.

##### **Reproduce the error**

Create an app with the JDL above, then run `docker-compose up` on it. After everything starts, stop the containers and try again.

This morning - I was able to reproduce this the 2nd time I restarted everything, but not the 3rd or 4th. Because of this, I decided not to enter this as a bug.

Then it happened again tonight, during my talk at Chicago JUG. I'm not sure why it happens, but it's happened enough times that it seems like a bug.

##### **Suggest a Fix**

A workaround: run `docker rmi` on the PostgreSQL image and run `docker-compose up` again.

##### **JHipster Version(s)**

5.7.0. This is not a regression AFAIK. I've seen it in previous versions, but I never reported it.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I'm not sure what you mean by migrations. All I'm going is generating the apos from the JDL, building the Docker containers, then running ”docker-compose up” in the docker-compose directly. I'm not modifying any code after generating everything.

**Comment by pascalgrimaud** [comment]
What do you mean by shutting down the container ?
Maybe you need to delete all containers ; stopping them wouldn't be enought

**Comment by deepu105** [comment]
@mraible @pascalgrimaud is right. It happens to me on MySQL as well, I think when we just shutdown the container the persistent volume is kept and reused on next run. I always do `docker kill <ID> && docker rm <ID>` or `docker-compose down && docker image prune --all`

**Comment by vishal423** [comment]
> Since I'm re-generating the same apps (many times for different talks/demos), maybe it has something to do with the way I'm shutting down the containers?

Every time you re-generate, Liquibase migrations would be generated with newer Id (timestamp based) and during application start, Liquibase will try to apply those against database as their Id would be different than those already present in the database (that's why you see table already exists error)

**Comment by PierreBesson** [comment]
Always best to do a full `docker-compose down && docker-compose up -d` as docker compose might pick up and reuse previously created containers. And if the database container actually contains the migration table from another jhipster app (maybe the same appname but it it was regenerated so the liquibase timestamps won't match), so I can see why it can have problems.

**Comment by pascalgrimaud** [comment]
As discussed, I'm pretty sure it's because there are still persistent volume with Docker.
Matt: don't hesitate to reopen if you still have an issue after deleting all containers.
