### ISSUE TITLE
When selecting the current date (for type instant), the web component should add a default time

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#8846]
##### **Overview of the feature request**

When you have a date of type `Instant`, the Angular update component uses a `type="datetime-local"`. When selecting the current day on the HTML component, only the date is set, not the time. So you have to add it manually otherwise the component does not allow you to save it.

It would be helpful to set the time (by default could be 00:00)

##### **Motivation for or Use Case**

Imagine you have the following JDL which represents an item status with a status date of type `Instant`:

```
entity ItemStatus{
    status String required,
    statusDate Instant required,
    additionalInformation String
}
```

The code generated in the `item-status-update.component.html` uses a 

```
<div class="d-flex">
    <input id="field_statusDate" type="datetime-local" class="form-control" name="statusDate" [(ngModel)]="statusDate"
    required/>
</div>
```

So when you create a new Item Status and you hit the current day button, only the date is set, not the time. Because the date in not valid, the Save button is not enabled, and you can't save the Item Status:

![instant1](https://user-images.githubusercontent.com/729277/48660103-82f84680-ea5c-11e8-9305-e154689cdafe.png)

You have to manually set a time for the Save button be enabled. The component should add 00:00 by default.

![instant2](https://user-images.githubusercontent.com/729277/48660112-9acfca80-ea5c-11e8-87ad-6063c35d5c31.png)

##### **Related issues or PR**

See #5006
See #6711

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
Ok some I have just done some tests and unfortunatelly it seems we can't handle event when a date is choose in the calendar. 
Calendar is related to navigator not the component itself, that's why on chrome or firefox the calendar has not the same rendering.

Both "change" and "input" events are fired when the field is totally filled (so date AND time). We can't use them to change time on the fly.

 But maybe I have a workaround : 
- we have to set a value (if input don't have one already)
- the default value is "today" at 00:00am
- when the user choose a new date in the calendar the time is already filled

In this case we break the "required" validation because the field is always filled.

**Comment by FernandaCG** [comment]
Hi, can I work on this??

**Comment by pascalgrimaud** [comment]
@FernandaCG : sure, you're welcome !

**Comment by avdev4j** [comment]
@FernandaCG 
Have you any idea how you will face with this issue?
It's not as easy as we can think. You are welcome to share any ideas you want, if you think we can improve this behaviour by using a component or a trick. Be careful we need to think also to react and vue implementation.

I already analyzed this issue and I didn't find any natural way to fix it. I'm glad to help you if you need ;)

**Comment by FernandaCG** [comment]
@avdev4j  

Hi, I have try to set a default time, I mean current day and time at 12:00 am. 

<img width="263" alt="Screen Shot 2019-12-05 at 3 38 20 PM" src="https://user-images.githubusercontent.com/28972973/70280283-530a0700-1775-11ea-9e6e-ab5897415a77.png">

My other option is to use just another component, or change the type of the input to date, and set time by default too.

**Comment by qmonmert** [comment]
@avdev4j @pascalgrimaud I have a PR #11043 I set datetime-local by default with the date: today 00:00

I think it's the simplest way

**Comment by qmonmert** [comment]
I claim my money :) https://opencollective.com/generator-jhipster/expenses/12701 

cc @jdubois & @pascalgrimaud
