### ISSUE TITLE
JHIPSTER: http://localhost:8080/#/admin/user-managment - translation-not-found[footer]

### ISSUE THREAD

**Issue by arthurdn** [jhipster/generator-jhipster#8849]
JHIPSTER: http://localhost:8080/#/admin/user-managment - translation-not-found[footer]
Probably, this could be easily fixed, but such unbelievably GREAT generator should generate
working apps. Maybe, this error is because of some my actions.
Googled a lot of time unsuccessfully.

1 step. Generation
2. jhipster import-jdl jhipster-jdl.jh --force
3. npm install
4. Run back, front

`entity Category {
}
entity Image {
    type ImageType
    path String
}
enum ImageType {
   MAIN
}
//relationship OneToOne {}
relationship ManyToMany {
    Category{images} to Image
	Category{parents} to Category{children}
}

service all with serviceImpl`

    ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'admin/user-managment'
    Error: Cannot match any routes. URL Segment: 'admin/user-managment'
But user-managment files are present in resources.

messages_ua.properties is present in project\src\main\resources\i18n also for my chrome locale
and all other - whole list from the generator.

    	Application 'x' is running! Access URLs:
    	Local: 		http://localhost:8080/
     	External: 	http://10.2.0.117:8080/
Front

    [HPM] Proxy created: [ '/api',
    '/management',
    '/swagger-resources',
    '/v2/api-docs',
    ......
    [Browsersync] Proxying: http://localhost:9060
Security

       @Override
    public void configure(HttpSecurity http) throws Exception {
        http
            .csrf()
            .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
        .and()
            .addFilterBefore(corsFilter, CsrfFilter.class)
            .exceptionHandling()
            .authenticationEntryPoint(problemSupport)
            .accessDeniedHandler(problemSupport)
        .and()
            .logout()
            .logoutUrl("/api/logout")
            .logoutSuccessHandler(ajaxLogoutSuccessHandler())
            .permitAll()
        .and()
            .headers()
            .frameOptions()
            .disable()
        .and()
            .authorizeRequests()
            .antMatchers("/api/**").authenticated()
            .antMatchers("/management/health").permitAll()
            .antMatchers("/management/info").permitAll()
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN);

    }
Also login redirects to

    http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth?client_id=web_app&redirect_uri=http://localhost:8080/login&response_type=code&scope=openid%20profile%20email&state=82ykgW

How to fix translation-not-found[footer]?

**Comment by ruddell** [comment]
Duplicate of https://github.com/jhipster/generator-jhipster/issues/8801

You are going to an invalid URL, the path should be http://localhost:8080/#/admin/user-management (`user-management` instead of `user-managment`)

**Comment by gmarziou** [comment]
@arthurdn  Please don't cross-post it's a waste fo time for peop;e trying to help you https://stackoverflow.com/questions/53356091/jhipster-http-localhost8080-admin-user-managment-translation-not-foundf

**Comment by arthurdn** [comment]
removed, it is also translation-not-found[footer] for this url http://localhost:8080/#/admin/user-management

**Comment by gmarziou** [comment]
OK but your post does not include required details for us to reproduce, please aâste output of `jhipster info`

**Comment by arthurdn** [comment]
here is the whole project [https://github.com/arthurdn/jhipster](url)

**Comment by ruddell** [comment]
@arthurdn It is the same issue as I linked above (404 is unhandled on the client).  You are using OAuth2 as the authentication type, so no user-management routes are generated in the Angular client (you manage it through Keycloak or Okta).

Make sure to read [the docs on using OAuth](https://www.jhipster.tech/security/#oauth2), that login redirect is expected

**Comment by gmarziou** [comment]
Cross posted once  again, https://stackoverflow.com/questions/53365876/jhipster-http-localhost8080-admin-user-managment-translation-not-foundf

**Comment by jdubois** [comment]
@arthurdn please don't spam us - if you continue I will fill an abuse request, we all do this for free here (I'm currently having a day off from work to take care of my sick kid!), so we can't accept inappropriate behavior like this.

**Comment by arthurdn** [comment]
thx, sorry, deleted
