### ISSUE TITLE
New Service sub-folder inside shared

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#8851]
##### **Overview of the feature request**

For Angular projects, create a sub-folder called `services` inside the existing `shared` one which follows the same structure of the sub-folder `model`.

At the moment, the command `jhipster import-jdl`, used to import micro-service configurations, creates inside the folder `shared/model` one sub-folder for each new imported micro-service containing the necessary models.
Everything else is created inside the folder `entities`. Many time, one component, of one specific entity, needs to call services of other entities in order to keep the relationships between them.

For this reason, it would be nice to have a similar approach also for the services necessary to query the different micro-services.

The result for Angular projects to have the following folder structure:

```
app/
   accounts/
   admin/
   blocks/
   entities/
      **microservice01**/
      **microservice02**/
      **...**/
      **microserviceN**/
      entity.module.ts
   home/
   layouts/
   shared/
      ...
      model/ (<-- I would suggest to rename it **models** for consistency)
         **microservice01**/
         **microservice02**/
         **...**/
         **microserviceN**/
   ...
      **services/** (<- the new foder containing the services)
         **microservice01**/
         **microservice02**/
         **...**/
         **microserviceN**/
   ...
```

##### **Motivation for or Use Case**

This proposed folder structure would keep consistency between the usage of the models to represent the entities and their services with the Angular components to manage them.
It would be also easier to find and import the services when it is needed to keep the foreign keys.

##### **Related issues or PR**

I did not find any similar suggestion.

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@alexsintoni I'm sorry moving around models was already complex enough for us and after careful consideration, we decided to not do the same for services. So you would have to move around common services yourself. The requirement to have common services is less priority than to have modular code for microservices and in most cases, you wouldn't share services. anyway I'm sorry but we won't be doing this as it involves too much maintenance for us, not to mention circular dependency issues in Angular
see https://github.com/jhipster/generator-jhipster/issues/6480 and https://github.com/jhipster/generator-jhipster/issues/6693
