### ISSUE TITLE
JHipster keycloak logout, then login automaticly

### ISSUE THREAD

**Issue by seyfullah** [jhipster/generator-jhipster#8858]
jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jh-gateway@0.0.0 c:\Next\next-all-repos\nextJHipster\jhGateway
`-- generator-jhipster@5.6.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.vodafone.next",
      "nativeLanguage": "tr"
    },
    "jhipsterVersion": "5.6.1",
    "applicationType": "gateway",
    "baseName": "jhGateway",
    "packageName": "com.vodafone.next",
    "packageFolder": "com/vodafone/next",
    "serverPort": "8202",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "tr",
    "languages": [
      "tr",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) Client VM (build 25.191-b12, mixed mode)

git version 2.17.0.windows.1

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.10.1

Docker version 18.09.0, build 4d60db4

docker-compose version 1.23.1, build b02f1306

Congratulations, JHipster execution is complete!

##### **Overview of the issue**

I login using user admin, then I logout, then I want to login with another user. But I login as admin automatically.

##### **Motivation for or Use Case**

I want to login as another user for testing

##### **Reproduce the error**

See above.

##### **Related issues**

No.

##### **Suggest a Fix**

I think it is because of angular services and used cookies.

##### **JHipster Version(s)**

5.6.1

##### **JHipster configuration**

see above.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

There is no entity.

##### **Browsers and Operating System**

I use windows 10, it is a problem with all browsers.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Duplicate: https://github.com/jhipster/generator-jhipster/issues/7980 https://github.com/jhipster/generator-jhipster/issues/6941 https://github.com/jhipster/generator-jhipster/issues/6555

There is a PR which is work in progress: https://github.com/jhipster/generator-jhipster/pull/8757
