### ISSUE TITLE
Managing constraint validation on entity

### ISSUE THREAD

**Issue by jgribonvald** [jhipster/generator-jhipster#886]
Is there a way to manage in the frontend side eorrs on constraint validation on entities attributes ?
like intercepting errors ?

**Comment by jgribonvald** [comment]
What do you think about valdr and valdr Bean Validation ?
https://github.com/netceteragroup/valdr + https://github.com/netceteragroup/valdr-bean-validation
With theses plugins/tools it seems that we can have an automated approach.

**Comment by jdubois** [comment]
yes, it looks good, but it has already been discussed several times here: we will not use a small project for something of this importance for JHipster. I'm not taking risks for something that affects all users.
We don't discourage people from using it, but we don't put it by default.

**Comment by jgribonvald** [comment]
Ok Thanks for the feedback
