### ISSUE TITLE
Generated java integration tests have incorrect suffix 'IntTest'

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#8868]
##### **Overview of the issue**

Maven plugin dedicated to integration tests ([maven-failsafe-plugin](https://maven.apache.org/surefire/maven-failsafe-plugin/index.html) includes by default tests with `IT` prefix/suffix, not `IntTest` prefix/suffix : 
https://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html

##### **Motivation for or Use Case**

Currently integration tests generated by JHipster are run during `test` phase by maven-surefire-plugin whereas they should not be run.

##### **Reproduce the error**

- Generates a new application from .yo-rc.json.
- Run mvn test
- Output will contains:
> [INFO] Running com.mycompany.myapp.web.rest.LogsResourceIntTest

##### **Related issues**

#498, #2663

##### **JHipster Version(s)**

5.7.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.7.0",
    "applicationType": "microservice",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "N2E3YmM1N2RiOTk3MmFiYWQ3ZGZmNGRjY2U4Mzk2ZWYwNTczMzEyZjdiYjNkYmU5NWY4YmQyZThhNzNmYWQwZjdjMTlhODg4MDJmOTE5ODBhNzY2OWViNWEwMDRlMzM5MTkyYTdjMzNmNDUzMzMwNDg4NDRjNWE5Njg1ZDAxOTc=",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Check the closed issues, there was a huge discussion about this already and
we decided to keep it this way

Thanks & Regards,
Deepu

**Comment by murdos** [comment]
Are you talking about #6131 ?
This is the first project I encounter that use this specific `IntTest` suffix, and for me it breaks Policy 1.

**Comment by deepu105** [comment]
We could do it for v6 as that was the plan in that ticket

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Yes for me the discussion on #6131 is still accurate, and I still haven't any Java developer separate unit tests and integration tests (and that's bad, and I know it, but that's the way people work).

Now we've always tried to provide "best practices" and push new and interesting stuff, so I'm totally in favor of changing this, I just have 2 issues with this:

- We need to check if all common IDEs support this correctly, as well as Sonar
- This is a major breaking change for everyone, so I wouldn't do it now but on our next major release

**Comment by Allsimon** [comment]
I'm looking into implementing this.
Do you have any pointer on how to migrate previously existing integration tests ?

**Comment by murdos** [comment]
Thanks @Allsimon !

I don't necessary agree with the separate source/resource folder. It's not standard. But I don't have the final word :)

Regarding separate coverage for UT/IT I don't understand why it's needed. On the contrary, we should make sure coverage is consolidated.

And for migrating existing IT, I'm not sure... maybe take a look to https://github.com/jhipster/generator-jhipster/blob/master/generators/app/index.js#L452 and cleanup.js to see if it can be used.

**Comment by Allsimon** [comment]
I checked cleanup.js but it seems to just delete the files.

If someone implemented custom logic in a previously existing `FooIntTest`, it would be a bad idea to just blindly delete it

**Comment by murdos** [comment]
I was not suggesting to remove previous test, just to use the same logic (verify jhipster version, and then renamed files and update class name of existing tests).

**Comment by pascalgrimaud** [comment]
it will be for v6, so we can do some breaking changes. No need to remove old files

**Comment by anthonyrichir** [comment]
Hello,
I was going through the discussions of v6 and got really interested in this topic, and I must give you some feedback on this because you're doing a great job with Jhipster but on this one, I think you might be doing a mistake.

I think that using the maven-failsafe-plugin for executing the current *IntTest classes is not a very good idea.

This plugin relies on the following 4 maven phases
- pre-integration-test
- integration-test
- post-integration-test
- verify

And those phases occur **after** the package phase.

If you do that, it means that you accept the fact that the application will be packaged, even with failing tests, slowing down the feedback loop.

Somehow, it also means that you need the packaged application to be able to run your tests and so far, it's never been the case.

Typically the integration tests generated by Jhipster are not exactly integration test in the sens that they do not need an environment to integrate with. They bootstrap an in-memory database in order to run.

**Comment by Allsimon** [comment]
Hello,

verify being after the package phase is really useful if you test with some others tools (https://github.com/palantir/docker-compose-rule in a multi module maven project for example).

Purely subjectively, I'd argue that the "slow" feedback loop is in fact "much faster".  I usually make a large part of the coverage with standard unit tests and fallback to Spring when we really need it. Instantiating a full Spring app is reaaaaally slow for unit tests. 

> Jhipster are not exactly integration test in the sens that they do not need an environment to integrate with

They literally launch a complete Cassandra container.

**Comment by pascalgrimaud** [comment]
The tests were renamed but I'm reopening this as there is 2 points mentionned by Julien, which are still WIP:
- We need to check if all common IDEs support this correctly
- as well as Sonar

See :
- Maven: https://github.com/jhipster/generator-jhipster/pull/9337
- Gradle: https://github.com/jhipster/generator-jhipster/pull/9328

**Comment by anthonyrichir** [comment]
@Allsimon, I wasn't aware that a Cassandra container is instantiated, I'm not working with it, so I apologize for my mistake. And therefore, I agree, it makes sens to run those tests in the integration-test phase.

However, when starting a container is not required, I still think those tests should remain in the classic test phase.

**Comment by atomfrede** [comment]
@pascalgrimaud For me sonar is working fine, we use testcontainers a lot at work for integration testing and have no problems with sonar. What do you mean exactly by IDE support? As I mentioned already somewhere I would also go with having testcontainers for spring integration tests (when e.g. selecting not h2 in mem).

**Comment by Allsimon** [comment]
@anthonyrichir see https://github.com/jhipster/generator-jhipster/blob/c3803e580d442796ff1d00c0fe0924bb77ff1f56/generators/server/templates/src/test/java/package/AbstractCassandraTest.java.ejs

It is a Cassandra container

I agree with @atomfrede it would be really nice to have testcontainers for IT instead if the prod database used is supposed to be something else than H2

**Comment by anthonyrichir** [comment]
@Allsimon ok, as I said, I'm not using Jhipster with Cassandra, and in such case, having those tests running with maven-failsafe-plugin can be discussed. However, you still don't need to package your app before executing those tests.

**Comment by atomfrede** [comment]
For gradle there is a new task of type test which does not require packaging the application.

**Comment by DanielFran** [comment]
Both #9337 (maven) and #9328 (gradle) have been merged, so I am closing this.
