### ISSUE TITLE
Store secrets in separate files

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#8876]
##### **Overview of the feature request**

Store secrets in separate files and add them to .gitignore when generating a new application.

##### **Motivation for or Use Case**

Secrets should not be commited to a source code management system.
Also the effort to create bug reports here will be lower because I don't have to remove the JWT token for example.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
About bug report:

The token should be changed when you use jhipster:info
https://github.com/jhipster/generator-jhipster/blob/master/generators/info/index.js#L47-L54

Do you see a bug with this ?

About secret :
The generated code is for development platform and all secret should be committed. 
In production, you should override all secret properties. If you use the default from git, you have a security issue.
That's how spring boot works.

**Comment by CodingSpiderFox** [comment]
OK thanks. I tried it and the token on jhipster info is the same for all my projects.

**Comment by deepu105** [comment]
Actually this is something I wanted to do when switching completely to JDL
so ya its on my roadmap

**Comment by CodingSpiderFox** [comment]
What is JDL in this context?

**Comment by deepu105** [comment]
I don't want to force everyone to use a service. I have some simple
solution in mind but its for v6 and hence too early to discuss now
