### ISSUE TITLE
CreateProcess error=206, The filename or extension is too long - Maven and Windows

### ISSUE THREAD

**Issue by lsadehaan** [jhipster/generator-jhipster#8878]
##### **Overview of the issue**
The goal spring-boot:run fails due to classpath being too large in a jhUAA project with too many dependencies selected on Windows (using Maven).

Seems to be the same issue as #4323 except for Maven. For Gradle it was fixed with #4324.

##### **Motivation for or Use Case**

Generated microservice jhUAA application cannot be run on Windows.

##### **Reproduce the error**

Generate a microservice UAA application on Windows with preferences of following .yo-rc.json file

##### **Related issues**

Seems like #4323 is the same issue just for gradle

##### **Suggest a Fix**

Perhaps it can be fixed in the same way as #4323 was fixed (see #4324)

##### **JHipster Version(s)**
5.7.0

##### **JHipster configuration**

jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhuaa@0.0.0 C:\_CODE_\gitlab\socialref\jhuaa
`-- generator-jhipster@5.7.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.socialreferee.rugby",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.7.0",
    "applicationType": "uaa",
    "baseName": "jhuaa",
    "packageName": "com.socialreferee.rugby",
    "packageFolder": "com/socialreferee/rugby",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.10.2.windows.1

node: v11.2.0

npm: 6.4.1

yarn: 1.12.3

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**

Chrome and Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by antonioortizpola** [comment]
Just change the launch configuration to avoid using the default shorten line

![image](https://user-images.githubusercontent.com/11655127/49041829-ecc6cd80-f18b-11e8-936c-ac270db2be40.png)

I no not know if this could be take as a JHipster error or not.

**Comment by pascalgrimaud** [comment]
It's a problem related to Windows.
So if you have a fix for Maven, you're welcome to PR. Otherwise, I'm not sure we can do something here.

**Comment by pascalgrimaud** [comment]
I'm closing this. But don't hesitate to PR if you find the solution.
