### ISSUE TITLE
Reimporting a JDL file is handled as a new project

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#8880]
##### **Overview of the issue**
When importing a JDL file, it doesn't ask for confirmation on conflict files where changes have been made and it simply overrides them. It also commits the changes with the message `Initial application generated by JHipster-5.7.0`

##### **Motivation for or Use Case**
When importing a JDL file, it should as for confirmations prior overriding changed files and it shouldn't automatically commit those changes.

##### **Reproduce the error**
Create a project and import a JDL. It shouls, at least, ask for confirmation when overriding the narbar file.

##### **Related issues**
none found

##### **Suggest a Fix**
implement the confirmation before overriding the files changed by the user and don't auto-commit the changes.

##### **JHipster Version(s)**

```
factur-app@0.0.0 /Users/alejandro/IdeaProjects/test_comment
└── generator-jhipster@5.7.0

```
##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.16.2

node: v8.11.3

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.09.0, build 4d60db4

docker-compose version 1.23.1, build b02f1306

INFO! Congratulations, JHipster execution is complete!

##### **JHipster Version(s)**
5.7.0

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Please use the --interactive flag for that behaviour

**Comment by amatosg** [comment]
this is counterintuitive, the previous behavior was to ask before overriding files. Now it behaves the other way around: it will override all your files unless you use a flag. I was using the import feature very often as I made changes to my jdl file and I was really surprised to realize that I wasn't asked to override my changes, it just did it **and** it committed those changes so all the work I did had to be made again.

I know I'm not in the position to demand anything, I just want to understand. So, could you please explain to me why was this change made? maybe I'm missing something?

**Comment by deepu105** [comment]
@amatosg sorry it was a surprise, and I understand the pain, let me see what can be done, the change was made to speed up multi-application import so that things are done in parallel, and when running in parallel you won't be able to interact with it. Maybe I can skip the behavior for cases where you are only generating entities. Can you confirm, did you generate app and entities or just entities?

**Comment by amatosg** [comment]
I was generating a monolithic app with entities. Whenever I make changes to the JDL file (new fields, change the values of other fields), I reimport it and it would ask to override some files. I then check which files are being affected and accept or reject the generation. 

IMO, the user should still be prompted to choose the action and leave a flag like `--unattended` for generating without asking the override as that was the original flow.

**Comment by ruddell** [comment]
In my opinion, the application shouldn't regenerate by default if it already exists in that directory, that's what is causing the issue.

It's fine if you use `--ignore-application` but it isn't clear to the end-user that they have to add a special flag to re-import an updated JDL file

**Comment by jbadeau** [comment]
Is there some way to disable auto git commit?

**Comment by ruddell** [comment]
@jbadeau `--skip-git`, to see all options, `jhipster app --help`

**Comment by jdubois** [comment]
I'm adding a bug bounty on this, as this is important for JHipster 6

**Comment by vishal423** [comment]
I suspect this issue is also causing the manual upgrade to auto commit

**Comment by deepu105** [comment]
@amatosg please claim the bounty. @mraible fyi

**Comment by vishal423** [comment]
@deepu105, do above change also fixes the auto commit behavior on manual upgrade?

**Comment by pascalgrimaud** [comment]
@deepu105 : the PR was opened by @Shaolans, not by @amatosg
It was @Shaolans who worked on this, and tried to find the fix

**Comment by deepu105** [comment]
Oh sorry @Shaolans, plz do claim the bounty

**Comment by deepu105** [comment]
@vishal423 no this only addresses the interactive behaviour. If there is an issue with commit it needs to be looked into

**Comment by Shaolans** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/8417
If someone who participated wants a share of the bounty I will be glad to do so.

**Comment by pascalgrimaud** [comment]
Don't share, @deepu105 you should claim one, as you worked on this too. We have money and should use it.

**Comment by steffanolesen** [comment]
> In my opinion, the application shouldn't regenerate by default if it already exists in that directory, that's what is causing the issue.
> 
> It's fine if you use `--ignore-application` but it isn't clear to the end-user that they have to add a special flag to re-import an updated JDL file.
> 
> JDL file showing this issue (import it, then import it again):
> 
> ```
> application {
>     entities *
> }
> 
> entity Foo {
>    name String
> }
> ```

With version 6.1.0 re-importing (using `--ignore-application`)  still always regenerates a new 20190621083439_added_entity_Foo.xml and updates master.xml
