### ISSUE TITLE
https://www.jhipster.tech/running-tests/  "Gherkin" link not workin

### ISSUE THREAD

**Issue by vidhya03** [jhipster/generator-jhipster#8897]
Go to [https://www.jhipster.tech/running-tests/#behaviour-driven-development-bdd](https://www.jhipster.tech/running-tests/#behaviour-driven-development-bdd)
the Gherkin link shows 404 
![image](https://user-images.githubusercontent.com/534679/49200650-b5dafc80-f3c3-11e8-9111-0fdeb80b2a69.png)

**Comment by pascalgrimaud** [comment]
There is no small contribution !
Your help is welcome :)

**Comment by atomfrede** [comment]
We all started with small contributions, every little thing counts 👍

**Comment by deepu105** [comment]
PR merged
