### ISSUE TITLE
Support more Graph Databases using spring-data-gremlin

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#8900]
##### **Overview of the feature request**

The goal is to support graph databases compatible with Apache Tinkerpop framework, like Neo4J or OrientDB.
One could use https://github.com/Microsoft/spring-data-gremlin or https://github.com/zifnab87/spring-data-gremlin in order to use a layer that implements Spring Data for those graph databases.

##### **Motivation for or Use Case**

Support more graph DB, OrientDB for my specific use case.

**Comment by deepu105** [comment]
@anthony-o there is not enough info here to go on? are you asking for support for more database or is it about migrating any existing stuff? I don't recall we using spring-data-gremlin anywhere and we don't have support for Neo4J as well.

**Comment by anthony-o** [comment]
@deepu105 indeed, I read the code here https://github.com/jhipster/jhipster-neo4j-app but didn't see that it has not been updated for 3 years :)

My real need would be to support graph databases like Neo4J or OrientDB inside JHipster.

By the way, I also saw that https://github.com/zifnab87/spring-data-gremlin has more features than https://github.com/Microsoft/spring-data-gremlin in term of Apache Tinkerpop Gremlin support as a Spring Data implementation.

**Comment by deepu105** [comment]
We are currently thinking of removing support for some databases that are not used a lot so we won't be adding any new database at the moment(It will add a lot of maintenance overhead for us). You can take a look at JHipster blueprints to build the support yourself as an extension. If your blueprint is well received and used we can think of bringing it into the core.

**Comment by jdubois** [comment]
Yes and we already tried Neo4J support several years ago and nobody wanted to work on it... All those databases have far too few users for us. Typically we have 1 contributor per 1,000 users, so in order to have something working we really need to have something that is widely used. I'm sorry, but that the (sad) way open source works.
