### ISSUE TITLE
Having a way of very quickly generating something

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#8917]
#### **Overview of the feature request**

The title says it all.
For me, there's no very good way of quickly generating an entity (or an application) like in Rails.
Something like`jhipster generate entity ENTITYNAME field1:String field2:Integer` or `jhipster generate application MySuperApplication monolith OPTION1:WHATEVER OPTION2:WHATEVER`.

#### **Motivation for or Use Case**

Q&As aren't a bad solution, but can be a pain to maintain and there's always the question of what can be generated from Q&As. DSL are good because this solution gives the user a sense of control and easiness (if done right) but both solution aren't quick enough. There's always something one's gotta do before generating something:
  - A user can spend quite some time generating something (an app or an entity) from the Q&As
  - And generating from a JDL file implies creating a file, writing something and executing the command

That's why I'm proposing (again, after a few years) this kind of feature.

#### **Related issues or PR**

None

-   [X] Checking this box is mandatory (this is just to show you read ever

**Comment by mraible** [comment]
Please provide more information on what you’re looking for. What commands would you like to see and what would they generate?

**Comment by MathieuAA** [comment]
Hi @mraible! As written, this is not a "I-want-this-feature-precisely" but more of a "this-kind-of-feature-would-be-nice-don't-you-think" open question. Maybe I wasn't clear enough, if that's the case, my apologies.

Everything here is open for debate, but to answer your questions: I'm proposing to introduce a way of generating **anything**:
  - Things we already generate like entities or apps
  - And maybe one day things we could generate things such as controllers, services (there are talks already of generating little things in the JDL by the way).

For instance, you have two ways of generating an entity right now:
  - jhipster import-jdl <YOUR_JDL> (this implies creating the file, writing something and executing a comand: 3 actions at least)
  - jhipster entity <YOUR_ENTITY> (this implies answering the questions: I lost count of how many actions there are during my internship 3/4 years ago to be honest)

Now, what I'm suggesting is implementing something close to what Rails does (or not, this is up for discussion). Something likejhipster generate entity ENTITYNAME field1:String field2:Integer or jhipster generate application MySuperApplication monolith OPTION1:WHATEVER OPTION2:WHATEVER.

As to why, if some subgens are to be deprecated in the future in favor of the JDL, we need a way of quickly generating things without relying on the JDL for everything. And I say this even though I'm the one maintaining the beast :)

_And there were talks of moving away from yeoman, one day, maybe._

By the way, I want everyone's opinion on this (@jhipster/developers).

**Comment by ruddell** [comment]
For a while, I've wanted to be able to run something like `jhipster oauth2` and get a monolith with `oauth2` (similar to [the Slack generator](https://github.com/jhipster/hipslacker)), but I never found the time to look into it.  The new application JDL made it simple enough for me.

Aside from more maintenance, what I don't like about the idea is it would be creating a third type of jhipster-specific commands.  From the perspective of a JHipster power-user, writing a simple JDL file takes about the same work as formatting a complex command to run (new users would probably have to look up the format for both).

**Comment by MathieuAA** [comment]
Hi @ruddell, agreed and disagreed. This feature is clearly not for someone who wants to generate complex things.

> what I don't like about the idea is it would be creating a third type of jhipster-specific commands.

Yep, so do I. But the first one (Q&As) are being used less and less (hooray).
The JDL is becoming more important every day (and will be very important in the near future). 
That's an issue for me (no, I'm not too crazy yet) because the JDL has some issues:
  - it may not be intuitive at first: reading the doc is a necessary step (to understand relationships one has to read the JDL relationship section and the general relationship section)
  - 3 actions to do something (create a file, write something, execute a command)
  - Anyone can mess up writing a **good** JDL file (well formatted, grouped relationships, entities not declared twice, etc.) <-- that's why the linter wil be released. Yet another tool.

However, these things have become possible thanks to the JDL:
  - default values are important: if someone is tired of always selecting the Q&As' default values everytime, these can be skipped by not mentioning them in the JDL (and it works depending on the app type you choose --which has a default value too) **<--that's why I'm proposing this**
  - JDL studio
  - JHipster IDE
  - etc.

Don't get me wrong: the JDL has a bright future ahead, but making it the default generating option is not something I look forward too as it has been created as an alternative to the Q&As.

I'd have agreed about the maintenance part if there were lots of things to do to implement something like this. I'll work on a separate GitHub project to do something like this next week for fun.

**Comment by deepu105** [comment]
@MathieuAA here are my thoughts.

I'm actually against this for below reasons. Hope it makes sense.

1. providing everything in the command line in more error prone and is not a nice user experience for our end users, please remember the majority of our end users and novice to medium devs and hence it would mean we have to maintain and support both this flavor, the current CLI prompts and JDL
2. Such a feature will only help core developers and people who are just randomly testing stuff, in a real-world use case you are never in a such a hurry and you always take time to craft your options/entities and in that case, JDL is the best fit there. So for me, the effort of supporting this is not justified as it only benefits a subset of people who really know the generator well
2. I was hoping to even deprecate the entity sub gen and move completely to JDL as that is the most intuitive and practical option so that we can focus on JDL and remove a lot of maintenance overhead coming from the current CLI prompts

Now I do agree that something like this would be nice to have in that case may I propose something that is less maintenance for us and will align with my JDL vision?

what if we can run JDL snippets directly in CLI without needing a file? say I can run
```
$ jhipster import-jdl "application { config { baseName foo, authenticationType oauth2 } }"
or
$ jhipster import-jdl "entity Foo { bar String, baar Integer }"
or
$ jhipster import-jdl \
"entity Foo { \
  bar String, \
  baar Integer\
}\
service Foo with serviceClass"

WDYT?


```

**Comment by MathieuAA** [comment]
@deepu105 sorry for the late response. Not really, you still need to correctly write your JDL content.

**Comment by deepu105** [comment]
But wouldn't it be the same case with CLI flags?

**Comment by MathieuAA** [comment]
Oh yes. There's no point in arguing that the doc must be read beforehand in any case. But using the JDL in the command line is like using a js code (what's the point if you have a file?)Again, this solution has been proposed to solve an issue. Just like the JDL has been created to solve an issue, or JUML.
