### ISSUE TITLE
Provide x-auth-token authentication method

### ISSUE THREAD

**Issue by julienboulay** [jhipster/generator-jhipster#892]
When no cache system is enabled on the server side, x-auth-token could provide a better stateless and simpler authentication method compared to OAuth2.
An example here : https://github.com/joshlong/boot-examples/tree/4b14c1634e7cfa0e5ab5313fe5a14121ef7c10f7/x-auth-security/src/main/java/demo/xauth

**Comment by jdubois** [comment]
This is merged!

**Comment by alchemistgo87** [comment]
Do we have refresh token option in x-auth-token authentication. If not, do we have to save username and password of the user in client's local storage or do we have to set the expiration time of token to be infinity.

**Comment by julienboulay** [comment]
Hi,
there's no refresh token option with x-auth-token. The user will need to signup another time when the token has expired. Refreshing the token could be done each time a new request is send to the server, extending the expiration limit.

**Comment by DarkmanMuMoo** [comment]
Hi i just wonder that is it more better to implement  some AbstractAuthenticationFilter for doing login process instead of let UserXAuthTokenController do this. ???
