### ISSUE TITLE
JDL comments in DTO's

### ISSUE THREAD

**Issue by co5dt** [jhipster/generator-jhipster#8924]
##### **Overview of the feature request**

Domain objects receive javadoc and swagger annotations derived from JDL comments by default, which is awesome, yet generated DTO's don't. 

##### **Motivation for or Use Case**

It is awesome that there's a single place to add all the relevant information about an API. 
Especially the swagger annotations are darn useful when working with external parties or different departments. Copy-pasting those from the domain objects to the DTO's seems wrong, once regenerating them and all the hard work is gone.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
@deepu105 you also need to be in the "beta" program

**Comment by deepu105** [comment]
oh ok
