### ISSUE TITLE
New CLI commands: rename-entity and remove-entity

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#8933]
##### **Overview of the feature request**

`rename-entity` would rename an existing entity and update all related entities
`remove-entity` would remove an existing entity only if no other entity is related 

##### **Motivation for or Use Case**

As a development platform, JHipster should handle the whole possible lifecycle of an entity: 
 - [x] create
 - [x] update
 - [ ] rename
 - [ ] remove

Because you don't always (never?) design your perfect model from beginning, you should have the ability to rename or remove an entity without having to do it manually (it's quite painful).
There's also a common trap: when you rename an entity in your JDL, a new entity is created, but the old one is still here.

##### **Related issues or PR**

#4372

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Why would you need rename if you have remove and add?

**Comment by murdos** [comment]
Because when I create a new entity for the new name there's now way to make the link with the entity with the former name, and thus all linked entities won't be updated?

```
entity Category {
    description String required,
}

entity Product {
    title String required,
}

relationship ManyToMany {
	Category{product(title)} to Product{category}
}
``` 

What if I want to rename `Product` to e.g. `Asset`?
`jhipster entity Asset` => new entity `Asset` created
`jhipster remove-entity Asset` => not possible, since `Category` still references `Product`

**Comment by pascalgrimaud** [comment]
Here my point of view.
JHipster is used for generating code, not for renaming or deleting. If the user did a mistake by choosing a wrong name for his entity, it's on his side, not on our side. JHipster should not be used to fix user's mistake.
For deleting use case, `git` is the best here.
For renaming, it will took less than 5min, with `find / replace`, if the user knows well his code.

**Comment by murdos** [comment]
Since that what I've done this week (renaming entities), I can tell that it's not that simple, and it took me way more than 5min.
Now either JHipster is just a tool to bootstrap your application, that you trash away after the application is generated, or it's a development platform that you use while you're developing your application. In the latter case, this requested feature case is very useful.

> If the user did a mistake by choosing a wrong name for his entity, it's on his side, not on our side. JHipster should not be used to fix user's mistake.

It's not about mistake. It's about keeping a common, rigorous language between developers and users (of the application). Defining an ubiquitous language can take time, and it can evolve during the project lifecycle.

> For deleting use case, `git` is the best here.

How can you do that when there's hundred of commits after the initial entities generation?

**Comment by pascalgrimaud** [comment]
Here a use case:
- the user creates an application with hundred entities + SQL
- then, some dev + custom modifications
- some deployment, so apply liquibase changes
- the user needs to rename an entity (with table). Do you think he will:
    - do it manually ? (personnaly, I will choose this, helping by git diff)
    - or use this new rename sub generator ? a minor bug in this, and the user will do the change manually (no time to wait the fix / a new release), or he will open a new ticket without details because he can't share his code (exactly like upgrade sub-generator)
- for both solutions, he'll need to check closely his code, manage liquibase diff, because the rename sub-gen can't handle it

@murdos : I'm not against, just reluctant to have this, because I think it will be hard to achieve (specially to test in our CI), then to maintain and it will probably result in a lot of issues.
But maybe I'm wrong, because I don't use JHipster as a platform, but only to bootstrap my application.

**Comment by deepu105** [comment]
Personally, I will also be against renaming entity with JH as it will bring
a lot of maintenance overhead for us, and the only way to do it properly
would be to use a lot of regex/needles etc which is not very scalable and
is too much work. An IDE can do the job much better IMO. For deletion
I'm half minded

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
I agree with the comments from @pascalgrimaud @deepu105 - this is going to be a headache, and will cause many bug reports because people will expect too much from this. There are many limitations on this, and the easier way to rollback a change is just to use Git properly.

I'm closing this because I don't think this should be done.

**Comment by cbornet** [comment]
I had worked on an entity remover some time ago : https://github.com/jhipster/generator-jhipster/pull/4403.
I gave up because there were problems on Windows (it was working fine on unix)
The principle should still work. I may give it a try again one day.

**Comment by cbornet** [comment]
The branch is still there for someone to work on it. The principle is to use git in the same way the upgrade gen works.

**Comment by Entrecampos** [comment]
@cbornet @murdos
 Is it possible to remove an entity ?
 I would love to do that not manually:-)

**Comment by deepu105** [comment]
Please use your IDE for that. We will not be doing this as it is too much
maintenance overhead for us for very little value.

**Comment by ari62** [comment]
A tutorial how to remove an entity across Java / Angular would be great, the IDE Safe Delete refactoring just warns you about unsafe occurrences.

**Comment by Ahrovan** [comment]
@murdos Update this issues please

**Comment by mshima** [comment]
@Ahrovan it’s not implemented.
It’s not planned.
If someone wants to contribute with an implementation we can happily review.
