### ISSUE TITLE
Remove Infinispan option

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#8937]
Infinispan distributed cache support has been added by @srinivasa-vasu and I propose to remove this option:

- Last month it was only used by 0,58% of applications
- It has quite a high maintenance cost as it's complex to test
- The vast majority of users use Hazelcast, which basically does the same

@srinivasa-vasu I know you coded this while working at Red Hat, but as you left the company I'm guessing you don't have much incentive to continue supporting it?

Would anybody be interesting in maintaining Infinispan support?

**Comment by srinivasa-vasu** [comment]
Julien,

I see the usage is minimal. But If it makes sense to make it available for
our users, I don't have any issues maintaining it.

Thanks,
-Srini

**Comment by jdubois** [comment]
Thanks @srinivasa-vasu : let's keep it as long as it doesn't cause any big issues, then we'll see if it's worth the effort or not.

**Comment by DanielFran** [comment]
@srinivasa-vasu if you can take a look in spring-boot 2.1 branch, the update to latest version needs some adjustments... Thanks

**Comment by srinivasa-vasu** [comment]
Hi,

I am on vacation. Will check that once I am back.

Thanks,
-Srini

**Comment by kdejaeger** [comment]
@srinivasa-vasu I check out the infinispan implementation yesterday. Can you verify if the hibernate cache L2 inits/overrides are working properly. I had the impression that the defined configuration was not taken into account by the infinispan framework and just the configs defined in the default infinispan-configs.xml were activated.

**Comment by DanielFran** [comment]
@srinivasa-vasu @kdejaeger Do not forget to look at the correct branch:
- https://github.com/jhipster/jhipster/commits/spring-boot_2.1.0
- https://github.com/jhipster/generator-jhipster/commits/spring-boot_2.1.0

**Comment by srinivasa-vasu** [comment]
@kdejaeger - I don't see any issues mate. Defined custom config is getting
reflected. Do you want to be more specific?

**Comment by kdejaeger** [comment]
My experience with this is much lower, so I trust you fully. For instance I didn't already understand why I believe 'replicated-query' is defined in cacheconfig when the infinispan xml file seemed to contain only 'query' or something. I was as if the key's to override did not match the config file. I thought it had to mach those key's, just as the onces defined in the DataType.class enum. I just had put some breakpoints in the infinispan code where it seemed as if the framework was still preferring the infinispan xml config. Based on some changes I made in the time-to-live java configuration. I'll check it out again when the spring boot 2.1.x generator is released. Thanks for looking into this.

**Comment by srinivasa-vasu** [comment]
@kdejaeger - Sure, let me know if you face any issues. To answer your
question, if you explicitly mention the infinispan xml config, then it will
override your configuration. If not, defined config will be taken into
consideration. For L2, 'entity' config is applicable for all the domain
objects. Few things are hibernate specific.

**Comment by DanielFran** [comment]
@srinivasa-vasu example in Travis: https://travis-ci.org/jhipster/generator-jhipster/jobs/470923637

**Comment by srinivasa-vasu** [comment]
@DanielFran - Is it intermittent? I ran the tests locally from the same
branch, don't see any problems. Do you want to restart the travis build
again? or have you tried already?

**Comment by DanielFran** [comment]
@srinivasa-vasu it happens always in Travis... You can check the historic.

**Comment by srinivasa-vasu** [comment]
@DanielFran - I do see a problem with microservices app. I am getting a
different exception, but not the one in the travis build. I've pushed a
changed to the 2.1 branch. Let's see if this fixes the issue. I'll check
other cases as well.

**Comment by srinivasa-vasu** [comment]
@DanielFran - infinispan-spring-boot-start - 2.1.1.Final has some issues
with micrometer and JCache based cache initialisation. travis build null
pointer exception is because of this. I've submitted a pull request to
infinispan to address that particular issue. Let's not use 2.1.1, instead
will use 2.0.0.Final till the request is being acted upon.
*<infinispan-spring-boot-starter-embedded.version>2.0.0.Final</infinispan-spring-boot-starter-embedded.version>*

**Comment by kdejaeger** [comment]
Why are there no expiration times defined in the hibernate l2 caches?
