### ISSUE TITLE
Remove Cassandra option

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#8939]
I am a **huge** Cassandra fan, and I'm the one who coded the Cassandra support in JHipster. In my opinion, this could has been a mean.io alternative for Java.

But today I'm proposing to remove the option:

- Last month it was only used by 0,48% of users
- It has a high maintenance cost in our templates
- It doesn't work with JDK 11 so this is already a blocker for our Spring Boot 2.1 branch: the issue is that we use an embedded Cassandra (using the awesome CassandraUnit lib from @jsevellec ) for our tests, and JDK 11 support is planned for Cassandra 4 (not released yet). The solution would be to migrate to TestContainers, like we do for Couchbase, but that's a lot of work.

At the moment I propose:

- To remove the option now as this is blocking our Spring Boot 2.1 branch. This is only removing the question is the generator, not the code.
- Try to find an official maintainer for this - I know @clun would be interested, please add comments if you are interested - who would do the TestContainers migration (and more if needed), so we add back the question once it's solved.

And if we don't find a solution, we'll remove the code in 6 months.

**Comment by atomfrede** [comment]
@jdubois Are we planning to move more towards testcontainers in general?

**Comment by jdubois** [comment]
@atomfrede I'd rather stay without them whenever possible, each time I do trainings or I go to companies, people have a very hard time with Docker ("normal" JHipster users don't have access to the same tools we hipsters use daily...).

But for things like Cassandra, there is no other choice, so it's the way to go. Unless you have another proposal?

**Comment by atomfrede** [comment]
@jdubois Good point with many companies not having docker in place. But we are already heavily promoting docker/docker-compose for local development. We have made very good experiences lately with testcontainers (even docker with win 10 works very well right now). But I guess you have more insights what going on at jhipster users :)

**Comment by PierreBesson** [comment]
It's really sad but the feedback from our users is that we cannot force them to use docker as it could be really painful to use depending on their setup (win7, not enough ram, etc). Also the default option must include a way to run without docker otherwise it could be a dealbreaker in people's adoption of JHipster. Also testcontainer cannot run in all CI environnements (you need docker installed and root access).
However I would really like to have the dev sql option to use testcontainer has it would enable testing on the real db.

**Comment by jdubois** [comment]
As we are stuck on the Spring Boot 2.1 branch with Cassandra, I will remove the option in that branch. Hopefully we'll find a better solution in the future.

**Comment by dhiresbudhiraja** [comment]
I think Cassandra is best NOSQL database i have ever used, is there anyway we could go on with cassandra?? then

**Comment by jdubois** [comment]
As I discussed yesterday with @clun he will take the lead on this ( @dhiresbudhiraja don't hesitate to join him!).

We're going to organise into smaller groups for each technology stack like Cassandra, Couchbase, VueJS etc. over the next few weeks, in order to solve those maintenance issues.

I'm closing this as this now under control.

**Comment by micobarac** [comment]
Please, do not remove Cassandra support in future versions. We are using it with several clients now and we have plans to use it in the future.

So, please, keep Cassandra support alive :).

**Comment by jdubois** [comment]
@micobarac don't worry it won't be removed, we have direct support from Datastax now :-)

**Comment by clun** [comment]
Still going and going strong, you expect some improvements
