### ISSUE TITLE
Tomcat Error on running 2 instances of JHipster

### ISSUE THREAD

**Issue by BenoPope** [jhipster/generator-jhipster#8940]
##### **Overview of the issue**

Previously I have created two projects in Jhipster and got them to run fine on my tomcat server. The issue comes into play when I try to run both projects at the same time on the same tomcat. I am presented with a java.lang.IllegalStateException whenever I try to access one of the sites.

##### **Motivation for or Use Case**

Ease of use. Previous non-jhipster projects work just fine in this manner.

##### **Reproduce the error**

Add two jhipster .war files into the webapps folder of tomcat. Observe the log output.

##### **Related issues**

5408 had this issue, however, as their issue ticket was not formatted correctly, their ticket was closed, and no solution was given.

##### **JHipster Version(s)**

v4.14.3

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.nibhi.mymindcheck"
    },
    "jhipsterVersion": "4.14.3",
    "baseName": "myMindCheck",
    "packageName": "org.nibhi.mymindcheck",
    "packageFolder": "org/nibhi/mymindcheck",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "enableHibernateCache": false
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.19.0.windows.1

node: v8.12.0

npm: 6.4.1

Docker version 18.09.0, build 4d60db4

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

Building and testing on Windows 10.
Deploying and testing on Scientific Linux 7.1 (Nitrogen)

**Comment by jdubois** [comment]
This should indeed work, then I wouldn't recommend this, as we're only keeping WAR deployment because of cloud providers like Google App Engine or Azure (if it was just for me I'd have dumped it a long time ago).

Could you post the whole StackTrace, maybe we'll see something interesting?

**Comment by BenoPope** [comment]
On another inspection there are quite a few errors thrown. I have uploaded the whole log file but the exceptions are as follows:

Line 760: java.lang.ClassNotFoundException
Line 1462: javax.management.InstanceAlreadyExistsException
Line 1530: org.apache.catalina.LifecycleException
Line 1620: java.lang.IllegalStateException
Line 1787: java.lang.ClassNotFoundException
Line 1969: java.lang.ClassNotFoundException

[catalina.out.txt](https://github.com/jhipster/generator-jhipster/files/2663800/catalina.out.txt)

**Comment by jdubois** [comment]
Doesn't look good :-(
Maybe you could try disabling JMX (it's one line in the Spring Boot config), as it might create the same management beans twice (hence your  javax.management.InstanceAlreadyExistsException exception)

**Comment by atomfrede** [comment]
@BenoPope Any specific reasong why you use jhipster 4? (But I guess will be the same with jhipster 5)

**Comment by BenoPope** [comment]
> Doesn't look good :-(
> Maybe you could try disabling JMX (it's one line in the Spring Boot config), as it might create the same management beans twice (hence your javax.management.InstanceAlreadyExistsException exception)

Tried this, sadly to no aid. Same errors.

**Comment by BenoPope** [comment]
Success. Added "jmx.default-domain: mymindcheck" to the 'spring' config within application-dev.yml and application-prod.yml.
