### ISSUE TITLE
jhipster registry error with monolith out of box - docker

### ISSUE THREAD

**Issue by jamalzkhan** [jhipster/generator-jhipster#8945]
##### **jhipster monolith doesn't work with docker jhipster registry**

Running jhipster locally on Mac using the monolith and jhipster registry options, when running the registry and monolith, the registry doesn't show an intance of the app running.

##### **Motivation for or Use Case**

Bug as this means that there is an error in the docker file composition in dev, hinders development and testing.

##### **Reproduce the error**

Running the monolith and jhipster registry, the registry using:

`docker-compose -f src/main/docker/jhipster-registry.yml up`

##### **Suggest a Fix**

Not sure, but I think it's because of the config of the registry on dev.

##### **JHipster Version(s)**

5.7.0

##### **JHipster Version(s)**

```
testapp@0.0.0 /Users/jkhan47/IdeaProjects/jhipster-regtest
└── generator-jhipster@5.7.0

```

##### JHipster configuration
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jamalzkhan.testapp"
    },
    "jhipsterVersion": "5.7.0",
    "applicationType": "monolith",
    "baseName": "trading",
    "packageName": "com.jamalzkhan.testapp",
    "packageFolder": "com/jamalzkhan/testapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "lalalalala",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": false
  }
}
```

##### **Environment and Tools**

git version 2.17.0

node: v11.4.0

npm: 6.4.1

yeoman: 2.0.2

yarn: 1.7.0

Docker version 18.09.0, build 4d60db4

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

Chrome, Macbook High Sierra

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
I just generated a sample registry enabled monolith and indeed the generated `application-dev.yml` file contains:

```
eureka:
    instance:
        prefer-ip-address: true
    client:
        enabled: false # By default, the JHipster Registry is not used in the "dev" profile
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
```

So this is not a bug, it is the behavior we decided to have for monolith. Of course you are free to change your configuration.

**Comment by jamalzkhan** [comment]
Thanks for the clarification @jdubois @PierreBesson
