### ISSUE TITLE
Support import in jdl file

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#8947]
##### **Overview of the feature request**

It is really easy to maintain a single jdl file for a small to medium size project. However, as the project grows, it would be better to separate the jdl files by their relevance and import all of them into one `main.jdl` 

##### **Motivation for or Use Case**

Keeping a few files rather than one large file is easy to view and maintain. Saves scrolling up and down through hundreds of lines.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I'm not sure exactly what you want. You can already import several JDL files at once with: `jhipster import-jdl first.jdl second.jdl`

**Comment by pmverma** [comment]
@ruddell Thanks. I have overlooked the docs. Just saw it.
