### ISSUE TITLE
Follow Dave Syer's advices to make Spring faster

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#8954]
This should be done on the `spring-boot_2.1.0` branch.

We should do a list of all the tips given by Dave Syer on https://spring.io/blog/2018/12/12/how-fast-is-spring and discuss them one-by-one, and then do small PRs to implement each of the ones we select.

**Comment by jdubois** [comment]
I did the 4 most obvious tricks we could do. For the other points it's more complicated:

- several of them include adding arguments to the JVM, and we don't have much control on how the end-user sets up is IDE. Maybe we could do this only for Maven/Gradle.
- we could manually configure all beans, but then it would be a pain for our end-users when they want to add or configure more features, as they would lose all the auto-configuration and will need to do this manually like us.

**Comment by PierreBesson** [comment]
@jdubois arguments to the JVM could be setup on the docker image as well. As for the exploded jar and running with `java -cp`, this is already what jib does 😃!

**Comment by jdubois** [comment]
Thanks @PierreBesson good idea, I'm doing this!

**Comment by jdubois** [comment]
BTW I won't use `-XX:TieredStopAtLevel=1` because this degrades performance later

**Comment by jdubois** [comment]
Closing this as the list is over!

**Comment by jdubois** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/6356
