### ISSUE TITLE
Generation of test data factories for stubs and testing from Swagger 

### ISSUE THREAD

**Issue by jdrew1303** [jhipster/generator-jhipster#896]
Using the parser from #895 to generate test data factories using [factory-girl](https://github.com/aexmachina/factory-girl) and [Faker.js](https://github.com/marak/Faker.js/) to allow for more concise unit testing of functions requiring models. If the models are wrapped in a [UMD](https://github.com/umdjs/umd), they can be reused for unit tests, stubs and UI/Visual regression tests.

**Comment by jdubois** [comment]
This looks complex to me, I would like to focus on #897 and then we can see if can do your other requests
