### ISSUE TITLE
Improve docker-compose for non-eureka microservices

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#8967]
##### **Overview of the feature request**

I talked with @saturnism during JHipster Conf in Paris about our microservice experience when working with kubernetes. In a nutshell, using K8s native service discovery, ingress etc, we can get rid of Zuul and Eureka. This is mainly interesting for K8s deployments but doesn't help so much for developer experience.

In other words, you can use Minikube for local development. But usually, this comes with certain limitations for the developer. Running like 10 java microservices inside a VM for Minikube will lack performance. When speaking for myself, my workflow is developing using docker-compose and use kubernetes in production. But our docker-compose isn't aware of that level of service discovery and ingress routing like k8s does, but there are approaches to achieve this.

So I am thinking of 2 changes for our docker-compose generator:

1. create a small project called "jhipster-proxy", which is an extension on nginx (or maybe traefik) in order to pass service names, so they are resolved similarly to what Zuul does automatically, or what our enhanced ingress generator does. In more details, if we have a "gateway", "fooservice" and "barservice", we should route the services over a reverse proxy, and all requests on '/' to the gateway and expose the proxy instead of the gateway to the host port (which usually is 8080). 

2. find a solution how to make the services being resolved with the same hostname like inside k8s or using service discovery. docker-compose already supports hostname resolution by the name of the services, but currently we generate names like "fooservice-app" instead of "fooservice". So we could just rename these names or use some option for docker-compose to make the default app names work.

I am currently working on a prototype at work to solve these 2 things and would love to PR them as soon as they start to work.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by xetys** [comment]
I was thinking about different constellations and found one critical one: UAA. The way how UAA works today is that the gateway stores the access token in an HTTP-only cookie, so you can just open the microservice routes without handling (or seeing) the actual access token.

The current Istio/Ingress approach would already break this. Same would happen for my idea with docker-compose (it would work with JWT, and possibly with OAuth2. @mraible could comment how exactly an access token is passed to a microservice: cookie or as header and if the client is doing that by it self, like with JWT)

However, I see two approaches here to make this working with UAA. First is, use the gateway for routing, but with manual routes (you can do this with zuul, and I'm sure spring-cloud-gateway will offer the same options). The second is, make every UAA microservice capable of maintaining the cookie logic by itself. But I don't like the second approach.


P.S.: the prototype for the jhipster proxy can be found here: https://github.com/xetys/jhipster-proxy

**Comment by PierreBesson** [comment]
@xetys Sorry I have just seen your post, actually I don't think we would need a specific proxy service for as docker-compose comes with it's own virtual network, so we could work simply with static Zuul routes. Also as we know all the apps names (and port!) through their .yo-rc.json we could generate those zuul routes in the docker subgen and set them up with environment variables. It's totally doable IMO.

> currently we generate names like "fooservice-app" instead of "fooservice"

Yes obviously we should rename it, this choice was completely arbitrary and I have never liked it.

However we will need to refactor the docker-compose subgen completely as for now it is simply composing the existing applications docker-compose files.

@jdubois I think we need to prioritize this. As less and less people will choose Eureka, we need to have a working docker-compose setup for them. The logic of defining static routes for the gateway can also be useful for other subgen like k8s.

**Comment by xetys** [comment]
Yeah. As of the case with uaa I would prefer to use static zuul routes.

I'm tomorrow back from vacation and will look forward to work on this

**Comment by pascalgrimaud** [comment]
@xetys : it is opened since 6 months. Do you plan to work on this ?

**Comment by PierreBesson** [comment]
As this is quite a complex feature, 
@xetys can you create an RFC linked to this issue as described in https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

This would allow you to lay out your ideas and maybe someone else who has more time can work on it, maybe @hawkurane or @shaolans.

**Comment by pascalgrimaud** [comment]
It's opened since 10 months now
I think no one is interested to work on this

I'm sorry but I'm closing this, because of lack of interest.
Hope you're ok @PierreBesson @xetys

**Comment by xetys** [comment]
Same as in #9027, these are connected

sry for the delay
