### ISSUE TITLE
Incorrect gradle liquibase task parameters

### ISSUE THREAD

**Issue by carloca68** [jhipster/generator-jhipster#8969]
##### **Overview of the issue**

The generated gradle build file has escape codes in place of question marks for the liquibase task setup. 

##### **Motivation for or Use Case**

Due to the escape chars liquibase ignores the naming strategy settings and generate wrong migrations with extra fields.
```

liquibase {
    activities {
        main {
            driver 'org.h2.Driver'
            url 'jdbc:h2:file:./target/h2db/db/test'
            username 'test'
            password ''
            changeLogFile 'src/main/resources/config/liquibase/master.xml'
            defaultSchemaName ''
            logLevel 'debug'
            classpath 'src/main/resources/'
        }
        diffLog {
            driver 'org.h2.Driver'
            url 'jdbc:h2:file:./target/h2db/db/test'
            username 'test'
            password ''
            changeLogFile project.ext.diffChangelogFile
            referenceUrl 'hibernate:spring:com.mycompany.myapp.domain?dialect=org.hibernate.dialect.H2Dialect&amp;hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&amp;hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy'
            defaultSchemaName ''
            logLevel 'debug'
            classpath "$buildDir/classes/java/main"
        }
    }

    runList = project.ext.runList
}

```
##### **Reproduce the error**

Just run the generator with the attached configuration.

##### **Related issues**

None I know.

##### **Suggest a Fix**

Escaped chars instead of question marks in:

 generator-jhipster/generators/server/templates/build.gradle.ejs

 line 206

##### **JHipster Version(s)**

5.7.1

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.7.1",
    "applicationType": "monolith",
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

Windows 10 with jdk 8

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
@carloca68 Would you mind doing a PR? Not sure if I got it correctly. In fact its the same string we use for maven (which also only forwards to liquibase, so maybe we have the same problem there too?)
