### ISSUE TITLE
Addition of scaffolding for UI testing

### ISSUE THREAD

**Issue by jdrew1303** [jhipster/generator-jhipster#897]
Addition of [Protractor](http://angular.github.io/protractor/), [Mocha](http://mochajs.org/), [Chai](http://chaijs.com/), [chai-as-promised](http://chaijs.com/plugins/chai-as-promised) and [cucumber.js](https://github.com/cucumber/cucumber-js) for acceptance testing and E2E regression tests.

Using the mocha, chai stack allows for much more expressive and descriptive code. Using the chai-as-promised plugin removes the need for unwrapping promises (which are the backbone of angular).

Cucumber allows for the enforcement of WIP limits and segregation of test suites (fast, slow, e2e, regression, acceptance, etc.) through @ tags. It also allows for non-technical stakeholders input at an earlier stage of the development process.

Protractor is the default UI testing framework for Angular applications since the deprecation of ng-scenario.

**Comment by jmirc** [comment]
Seems to be amazing improvement for JHipster. It was the last missing peace for the testing.

I will prefer having the tests under src/test/e2e.

**Comment by jdrew1303** [comment]
Then tests under src/test/e2e you will have! :) I should hopefully have this done by the end of the week.

Its a good start, but theres still a lot of knowledge and bits and pieces needed to make them useful, cost effective and easy to maintain. Ill add in some info about how to handle the code for ui tests (for the two cases; cucumber and jasmine/mocha) and some tips and tricks as a doc.

**Comment by jdubois** [comment]
@jdrew1303 have you been working on this? Can you give us an update?

**Comment by jdubois** [comment]
I'm closing this: it is a good idea, but no work has been done on it, and we will not start this in the v2 release as far as I'm concerned
