### ISSUE TITLE
Multiple war files causing gitlab ci / cd docker-push job to fail

### ISSUE THREAD

**Issue by jsm174** [jhipster/generator-jhipster#8972]
##### **Overview of the issue**

After rebuilding a JHipster 5.7.0 project to JHipster 5.7.2, our gitlab ci / cd pipelines started failing during the `docker-push` job.

After checking the archive of the `gradle-package` job, it seems like there are now two war files generated:

```
gateway-0.0.1-SNAPSHOT-original.war
gateway-0.0.1-SNAPSHOT.war 
```

in `/src/main/docker/Dockerfile`, the command:

```
ADD *.war app.war
```

Results in:

```
Step 10/10 : ADD *.war app.war
When using ADD with more than one source file, the destination must be a directory and end with a /
ERROR: Job failed: exit code 1
```

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/jsm174/example/gateway
└── generator-jhipster@5.7.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.example.gateway",
    "packageFolder": "com/example.gateway",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "gateway",
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "clientFramework": "react",
    "buildTool": "gradle",
    "jhipsterVersion": "5.7.2",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "hazelcast",
    "serverPort": "8080",
    "useSass": true,
    "otherModules": []
  },
  "entities": [
    "A",
    "B"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity A {
  data String
}
entity B {
  data String
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.2 (Apple Git-113)

node: v8.14.0

npm: 6.4.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes this rings a bell, we need to check how this works with Maven to have something similar.

**Comment by atomfrede** [comment]
Will have look.

**Comment by atomfrede** [comment]
@jsm174 As a workaround you might try `./gradlew package -X war` or `./gradlew bootWar -X war` to disable the separate war tasks which creates the `-original.war`.

**Comment by pascalgrimaud** [comment]
let's do it for our Dockerfile

**Comment by jsm174** [comment]
@atomfrede Thanks. This morning we temporarily added another step to the .gitlab-ci.yml to remove the original file prior to building the docker file:

```
  before_script:
        - docker info
        - cp build/libs/*.war src/main/docker
        - rm src/main/docker/*-original.war
```

**Comment by pascalgrimaud** [comment]
@atomfrede : can we
- remove the generation of original war for gradle by default
- add a profile to generate the original war for gradle, so users who want to use it with tomcat are happy

**Comment by atomfrede** [comment]
We don't need a profile for that (need to check), but just executing the
war task should be sufficient. So maybe just a matter of documentation.

**Comment by Tcharl** [comment]
I've implemented it pretty easily in the maven context:

Dockerfile:
```
ARG JAR_FILE
ADD ${JAR_FILE} app.war
```
Pom:
```
<artifactId>jib-maven-plugin</artifactId>
<configuration>
<environment>
                                <JAR_FILE>${project.build.finalName}.war</JAR_FILE>
                            </environment>
```

Do you want a PR based on this solution?
