### ISSUE TITLE
SPF/TXT records not properly set.

### ISSUE THREAD

**Issue by 123shan007** [jhipster/generator-jhipster#8980]
The SPF entries includes at least one CNAME which is known to cause problems on some mail servers.

Inlcude 14 allow rules from host _mailcust.gandi.net.
Allow all from the range 217.70.176.0/21
Allow all from the range 2001:4b98:c::/48
Allow all from the ip 217.70.186.186
Allow all from the ip 217.70.186.176
Allow all from the ip 217.70.184.158
Allow all from the ip 217.70.185.10
Allow all from the ip 217.70.186.165
Allow all from the ip 155.133.132.131
Allow all from the ip 2001:4b99:1:252::131
Allow all from the ip 155.133.138.131
Allow all from the ip 2001:4b98:dc5:252::131
Allow all from the ip 155.133.142.131
Allow all from the ip 2001:4b98:dc6:252::131
Neutral all IPs which do not match any previous rule
Neutral all IPs which do not match any previous rule

Allow means that the stated addresses are allowed to send emails.
Soft deny means that the stated addresses are not allowed to send emails.
Deny means that emails from the stated addresses must not be accepted.

[SPF.docx](https://github.com/jhipster/generator-jhipster/files/2705463/SPF.docx)

**Comment by gmarziou** [comment]
Looks suspicious to me, it's either an error or a malicious action from a newly created github user. 
Don't open the attachment.

**Comment by gmarziou** [comment]
Just commented out attachment.

**Comment by jdubois** [comment]
Thanks a lot, I will report the abuse and ban the user from our GitHub org.
