### ISSUE TITLE
Add JHipster Registry directly into generator-jhipster

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#8982]
##### **Overview of the feature request**

I was thinking why not move the Jhipster Registry directly inside the Jhipster Generator in the same way as it is for the Gateway, UAA and a micro-serevice?

When people launch the jhipster generator, it is possible to choose between the following options:
```
? Which *type* of application would you like to create? (Use arrow keys)
  Monolithic application (recommended for simple projects) 
  Microservice application 
  Microservice gateway 
❯ JHipster UAA server (for microservice OAuth2 authentication)
```

Why not add the option to generate a Jhipster Registry as well? Like:
```
? Which *type* of application would you like to create? (Use arrow keys)
  Monolithic application (recommended for simple projects) 
  Microservice application 
  Microservice gateway 
  JHipster UAA server (for microservice OAuth2 authentication)
❯ Create JHipster Registry
```

If the user chose `Create JHipster Registry` the next question would be to chose the authentication mechanism as it is for the `Microservice gateway` or the `Microservice application`:
```
? Which *type* of authentication would you like to use? (Use arrow keys)
  JWT authentication (stateless, with a token) 
  OAuth 2.0 / OIDC Authentication (stateful, works with Keycloak and Okta) 
❯ Authentication with JHipster UAA server (the server must be generated separately)
```
And in the same way ask:
```
? What is the folder path of your UAA application? (../uaa)
```

In this way, the users of JHipster framework would have the same user experience throughout all the JHipster components:
```
Microservice application 
Microservice gateway 
JHipster UAA
JHipster Registry
```

Moreover, all of those components would have the same authentication mechanism and the same registered users and their permissions to access the different components included the registry.

Another advantage, would be that the registry libraries would be updated with the same Spring Boot and Angular version as it is for the gateway.

##### **Motivation for or Use Case**

Fix authentication issue between UAA and JHipster Registry.
Use same user created for the application (via Gateway or UAA) also to access the Registry

##### **Related issues or PR**

Not found

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Because there is no value in doing that. For UAA there is some level of customisation possible but for registry it doesn't make sense and only adds complexity in maintanance

**Comment by deepu105** [comment]
Also for registry there is lot of custom pages and components which is not common for other apps

**Comment by alexsintoni** [comment]
Hi @deepu105,

thanks for the answers.
I didn't check the source code of the JHipster Generator but I thought that putting the Registry into it would be similar to the Gateway. 
Also the default Gateway has already the swagger API, the Management session and the profile settings page.
So I thought that with the Registry would be a similar thing.

From my point of view, the value would the following 2 points:
1) have same authentication mechanism and users registered for both Gateway and Registry. At the moment the Registry doesn't work well with the UAA and the swagger doesn't show the REST API of micro services. Also, it give access to different users than the one registered with the Gateway or the UAA.
2) have same libraries versions for all the components. At the moment the Registry has older versions of Angular and Spring Boot. Also the Gateway is moving from yarn to npm but the Registry is still using yarn.

For those 2 reasons I thought it would be easier to maintain all the components with the same style. But as I said, I didn't check the code.

Another way would be to totally separate the Registry with the rest of the components: remove the swagger API from it and use completely different users for the login. 

Anyway, thanks for the answers and happy Christmas period.

**Comment by PierreBesson** [comment]
@alexsintoni What you are suggesting is not really feasible. The registry has always be conceived as a standalone app and it needs to be packaged periodically as jar and docker image. I agree that it would be nice to have it updated on the latest version of front end libraries but ultimately it doesn't matter much.

**Comment by ruddell** [comment]
@alexsintoni You can use the JHipster Registry with a UAA microservice page, make sure the `uaa` profile is enabled on the registry and you should be able to use the Swagger and other admin pages.  You still have to use a user specific to the JHipster Registry, the queries to the microservice management endpoints uses the `internal` client to make requests.
