### ISSUE TITLE
Microservice API versioning

### ISSUE THREAD

**Issue by Evertude** [jhipster/generator-jhipster#8996]
##### **Overview of the feature request**

I would like to have a versioning system for my backend microservice apis.
The way I currently use it is that i add a version to the spring request mapping like:
@RequestMapping("/api/v1")
and I haven't found that feature in JHipster yet so it is always overridden.

Affected files would be
src/../rest/EntityResource.java
test/../rest/EntityResourceIntTest.java (the path)
most likely Entity.json for the front end

##### **Motivation for or Use Case**

Legacy applications

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
There is 3 ways of versioning:
1. In the URL (like in your example) usually from soap
2. Using mediatype, normally vendor mediatype
3. Using a specific header field (not very usefull)

My preferance is to use vendor mediatype in rest.
If you want I can provide an example...

**Comment by Evertude** [comment]
Does the generator support any of those ways so that my code won't get overridden?

**Comment by DanielFran** [comment]
No, actually versioning is not supported!

**Comment by jdubois** [comment]
Indeed, I know it's not a perfect answer, but we let people do what they want here, as not everybody agrees on which is the "best practice".

From what I see, most people think that putting the version in the URL (point 1 from @DanielFran ) isn't a good practice, then many big and well-known products use this method...

Anyway I'm closing this as this is the current answer ("we don't support this"), then I really hope that we can find a better solution in the future. We still need to work on this part.
