### ISSUE TITLE
:rocket: Add client side translation for 404 states

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#9002]
##### **Overview of the feature request**

It would be good to have a generic translation for `404` states on client side. Very useful for e.g. having a client side route which handles invalid routes.

##### **Motivation for or Use Case**

https://github.com/jhipster/jhipster-vuejs/pull/194

##### **Related issues or PR**

* None

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
There's an open PR with this https://github.com/jhipster/generator-jhipster/pull/8909

**Comment by atomfrede** [comment]
@ruddell Thx for the hint. So let's close this. #8909 proposes the same handling for non existing routes as we want to do in vue.
