### ISSUE TITLE
Duplicated line in LoggingConfiguration.java.ejs

### ISSUE THREAD

**Issue by bzah** [jhipster/generator-jhipster#9024]
##### **Overview of the feature request**
I noticed a duplicated line, which seems to be unnecessary, in the file LoggingConfiguration.java.ejs.
The request is to remove this line (which I could totally do in a PR).

The duplicated code is ` logstashEncoder.setCustomFields(customFields);` lines 132 and 139 of 
[LoggingConfiguration.java.ejs](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/LoggingConfiguration.java.ejs) file.
The commit introducing the duplication is : https://github.com/jhipster/generator-jhipster/commit/553b8170fbd0b0495f3231b2bda5043734458335

##### **Motivation for or Use Case**

Cleaner code.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Yes indeed this is mistake, please submit a PR ! Don't bother creating an issue next time. For such simple task, it is OK to PR directly the fix. Thank you for your time and for rigorously completing the issue template.

**Comment by bzah** [comment]
Ok ok.
PR is : https://github.com/jhipster/generator-jhipster/pull/9025

**Comment by DanielFran** [comment]
PR merged so closing issue
