### ISSUE TITLE
Webpack and webpack-dev-server configuration producing unlimited hot-update files

### ISSUE THREAD

**Issue by garajo** [jhipster/generator-jhipster#9029]
##### **Overview of the issue**

During development, unlimited `*.hot-update.*` files are being generated in `target/www`

![2019-01-08 10_03_38-greenshot](https://user-images.githubusercontent.com/2825366/50851343-69270180-1331-11e9-8702-1e10ad143b57.png)

##### **Motivation for or Use Case**

Changing files under constant development produces a huge number of these files.

##### **Reproduce the error**

Run the development environment. Make changes in your files. See `target/www` grows with unbounded generated hash-named files. 

##### **Related issues**

Not I could find

##### **Suggest a Fix**

Seems the issue has been discovered here, https://github.com/gaearon/react-hot-loader/issues/456

##### **JHipster Version(s)**

Used "generator-jhipster": "5.7.0". I don't know how long it's been like this.

##### **JHipster configuration**

N/A

##### **Browsers and Operating System**

Windows

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
This is how hot update works and these are created in a temp directory which gets deleted when you run clean. I'm not sure what you expect here
