### ISSUE TITLE
Create tutorials for end-users

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#9033]
This is for helping beginners using JHipster. I would like several simple step-by-step tutorials, using Google Cloud Shell, like https://github.com/jenkins-x/jx-tutorial

Those should work with the free tier of Google Cloud Shell, and last 10-30 minutes each.

More information on those tutorials: https://cloud.google.com/shell/docs/tutorials

**Comment by deepu105** [comment]
Good idea

Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
@jdubois I have initialized the jhipster-guides here https://github.com/PierreBesson/jhipster-guides
I have requested a transfer of ownership to you so you can move the project to the JHipster org.

**Comment by jdubois** [comment]
Oh @PierreBesson I just created https://github.com/jhipster/jhipster-tutorials this morning!!

OK, let't use yours, and I'll delete the "tutorials" repo.

**Comment by PierreBesson** [comment]
So now that the tutorial is initialised, our trainees can get to work and create the guides themselves.

**Comment by pascalgrimaud** [comment]
The work is already done here https://github.com/jhipster/jhipster-guides by:
- @Hawkurane
- @Shaolans
- @SoniaLahi

Congrats to you!
Of course, it can be improved, but let's close this ticket.
