### ISSUE TITLE
Build in Jenkins failing with or without root (npm VS docker)

### ISSUE THREAD

**Issue by pdelaby** [jhipster/generator-jhipster#9035]
##### **Overview of the issue**

I cannot find a way to build a Jhipster monolith in a classic Jenkins (not dockerized), using "build in docker containers" : 
* if I build using the `-u root` (by default in `docker.image('jhipster/jhipster:v5.7.2').inside('-u root -e MAVEN_OPTS="-Duser.home=./"') {`) arguments, the step `build docker` will fail because the `target` folder is created as root, and then Jenkins cannot create a subfolder `docker` to build the docker image

Jenkins log, the folder is root (on the host)
```
cp -R src/main/docker target/
cp: cannot create directory 'target/docker': Permission denied
```
* if I build without the `-u root` this first issue is fixed, but the build fail during `npm install` because its not root

Jenkins log, npm does not have the permission (on the container)
```
[INFO] Running 'npm install' in /var/lib/jenkins/workspace/jhipster
[ERROR] npm ERR! path /.npm
[ERROR] npm ERR! code EACCES
[ERROR] npm ERR! errno -13
[ERROR] npm ERR! syscall mkdir
[ERROR] npm ERR! Error: EACCES: permission denied, mkdir '/.npm'
[ERROR] npm ERR!  { [Error: EACCES: permission denied, mkdir '/.npm']
[ERROR] npm ERR!   stack: 'Error: EACCES: permission denied, mkdir \'/.npm\'',
[ERROR] npm ERR!   errno: -13,
[ERROR] npm ERR!   code: 'EACCES',
[ERROR] npm ERR!   syscall: 'mkdir',
[ERROR] npm ERR!   path: '/.npm' }
[ERROR] npm ERR! 
[ERROR] npm ERR! The operation was rejected by your operating system.
[ERROR] npm ERR! It is likely you do not have the permissions to access this file as the current user
```

This used to work without the `-u root` : with yarn, which I think  changed directory (cf jenkins log in older projects where the build succeded ) 
```
[ERROR] warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
[ERROR] warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-112".
```

##### **Motivation for or Use Case**

Build Jhipster in jenkins with docker 

##### **Reproduce the error**

You can see the code used for checking the bug at https://github.com/pdelaby/jhipster-test.

Just create a Jenkins pipeline with the generated Jenkinsfile. 

##### **JHipster Version(s)**

* Jenkins : Jenkins ver. 2.150.1
* Jhipster :  v5.7.2

```
jhipster@0.0.0 C:\projets\tests\jhipster-bug
`-- generator-jhipster@5.7.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.7.2",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.20.1.windows.1

node: v10.13.0

npm: 6.4.1

yarn: 1.9.4

Docker version 18.09.0, build 4d60db4

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

Jenkins runs on Ubuntu 16.04.5 LTS 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
If I understand well, your config are:
- classic Jenkins (not inside Docker)
- your build is inside Docker
- you want to create a Docker image

I think I already see this issue, and there are some discussions about that, in old tickets.
I'll try to have a look and find a fix.
Don't hesitate to comment this, if you have something to propose.

**Comment by pdelaby** [comment]
Yes, exactly. Thanks :-) 

The Jenkinsfile is generated using `jhipster ci-cd`, I just removed some steps to fasten the build for the bug demo. 

I found a temporary workaround by switching to yarn for the build : without the `-u root`, it seemed yarn does switch to a writable directory when facing the issue. 

```
[ERROR] warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
[ERROR] warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-112".
```
and the build suceeded. 

Here is the light Jenkinsfile ( I also modified the pom.xml : replacing npm by yarn and adding yarnVersion property)

```
#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

   // if jenkins is dockerized, you need to add -u root as first argument on "inside"
    docker.image('jhipster/jhipster:v5.7.2').inside('-e MAVEN_OPTS="-Duser.home=./"') {
        stage('check java') {
            sh "java -version"
        }

        stage('clean') {
            sh "chmod +x mvnw"
            sh "./mvnw clean"
        }

        stage('install tools') {
            sh "./mvnw com.github.eirslett:frontend-maven-plugin:install-node-and-yarn -DnodeVersion=v10.14.1 -DyarnVersion=v1.6.0"
        }

        stage('yarn install') {
            sh "./mvnw com.github.eirslett:frontend-maven-plugin:yarn"
        }

        stage('packaging') {
            sh "./mvnw verify -Pprod -DskipTests"
            archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
        }
    }

    def dockerImage
    stage('build docker') {
        sh "cp -R src/main/docker target/"
        sh "cp target/*.war target/docker/"
        dockerImage = docker.build('docker-login/jhipster', 'target/docker')
    }

}
```

Maybe there's a configuration for npm so that it coud reproduce the yarn behavior, I'm working on it.

**Comment by cbornet** [comment]
You can [remap a user](https://docs.docker.com/engine/security/userns-remap/) to the docker container's root. That's the cleanest and most secure way to do it, but a little advanced...

**Comment by PierreBesson** [comment]
You should be able to set the NPM cache to a different location with `npm config set cache --global /tmp/.npmcache/`.

Also, I'm not very happy that we set the user to root. And now that we have integrated jib, we should be using it to build the docker image without a docker daemon and directly push to a registry. So IMO our CI config is outdated.

**Comment by cbornet** [comment]
Previously we were using an openjdk8 image which only had a `root` user. I see that we are now using our own `jhipster` image that has a `jhipster` user. So it should be easy to build using this `jhipster` user.
