### ISSUE TITLE
Wrong RESTful resource naming

### ISSUE THREAD

**Issue by jorgelorente** [jhipster/generator-jhipster#9039]
All PUT methods don't follow the RESTful Resource Naming Best Practices

`
@PutMapping("/users")
public ResponseEntity<UserDTO> updateUser(@Valid @RequestBody UserDTO userDTO) {
...
`

It should be a PUT on the correct resource ID

**Comment by PierreBesson** [comment]
This ticket has been closed as the **guidelines are not followed**.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md),
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**If this is indeed a JHipster bug**, please open a new issue with proper details or update this issue with all details and request to reopen.
Issues opened without proper details will be closed without explanation.

**Comment by PierreBesson** [comment]
Please follow the issue template and guidelines when reporting bugs and we will reconsider reopening this issue.
