### ISSUE TITLE
Documentation about how to set up your own continuous integration server

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#904]
Setting up your own continuous integration server using Jenkins for a JHipster 2 application is harder than for a classic Spring MVC application because of all tools required to build and test the client code.

In fact, for those who can it's probably a good idea to think about hosted continuous integration like TravisCI as the JHipster team does.

I am currently going through this process and I would like to contribute some how-to documentation if you think it is useful and maybe some other users may have some tips to share.

It's harder because you have to manage 3 software stacks in your build process:
- Java/Maven for the server code and the build orchestration
- Javascript/NodeJS/Grunt/Bower for client code
- Ruby/Compass to pre-process CSS style sheets

Each stack comes with its own dependency management (artifacts, npm, gem) with potential conflicts to solve.

CSS pre-processing is optional though, but it could have been simpler by choosing LESS as it requires only NodeJS which is already a requirement of JHipster. Anyway, maybe in the future this dependecy on Ruby will go away by using [node-sass](https://github.com/sass/node-sass) which is based on [libsass](http://libsass.org/) a C/C++ implementation but that would mean more work users (especially on Windows) as no pre-compiled binary is available.

I have started by setting up Jenkins on a Linux CentOS server without display and have faced issue #416 due to headless server. I have installed Xvfb and Firefox but Karma is still failing the same even though I modified karma.conf.js. I can give details if someone would like to help.

Finally, I have setup Jenkins on a Windows 2008 server and got a sucessful build with prod profile.
I can document instructions.

I had to change 2 things in karma.conf.js:
- singleRun: true otherwise grunt test server stays alive after end of build and blocks next build.
- added karma-junit-reporter plugin so that Jenkins can present results of Karma tests but I need to dig further this 

This makes me think that there should be a different karma.conf.js for prod/CI and for dev, or maybe the test server on port 9001 should be configured as singleRun.

A minor thing, the Jenkins log console contains non printable characters probably used for color output:

```
    [4mRunning "ngtemplates:dist" (ngtemplates) task[24m
```

**Comment by gmarziou** [comment]
@telefunken I used your Dockerfile, I had an issue with dbus dependency when running the "apt-get upgrade" which seems similar with [this report](http://forum.siduction.org/index.php?topic=5194.0).
As a workaround I commented out this line and finally successfully built my image but unfortunately the Jenkins job fails with same error as I had on my physical server "Fatal error: Cannot read property 'x-ua-compatible' of null" known as issue #416 and due to headless server.
It failed the same on 2 different Docker environments: Linux CentOS and Windows/boot2docker, maybe it works for you because you are on OSX, I may give it a try.

**Comment by PeterEltgroth** [comment]
@gmarziou what version of node where you using?

I had the "Fatal error: Cannot read property 'x-ua-compatible' of null" issue on MacOS when using node 0.11.14, but reverted to 0.11.13 (per https://github.com/spoike/refluxjs/issues/90) and it went away.  I had also attempted to upgrade my version of karma (since https://github.com/karma-runner/karma/pull/1182 had been merged in); however, that did not work for me. I probably missed something as I'm fairly new to using node.

Here's the error I recieved with 0.11.14 when running './gradlew test':

ERROR [karma]: [TypeError: Cannot read property 'x-ua-compatible' of null]
TypeError: Cannot read property 'x-ua-compatible' of null
    at getXUACompatibleMetaElement (/Volumes/home/yw5927bj/c/janisch/node_modules/karma/lib/middleware/karma.js:40:19)
    at /Volumes/home/yw5927bj/c/janisch/node_modules/karma/lib/middleware/karma.js:145:45
    at /Volumes/home/yw5927bj/c/janisch/node_modules/karma/lib/middleware/common.js:57:35
    at fs.js:295:14
    at /Volumes/home/yw5927bj/c/janisch/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:104:5
    at Object.oncomplete (fs.js:93:15)

**Comment by gmarziou** [comment]
@PeterEltgroth many thanks, you found the root cause.

I was using NodeJS 0.11.14, I downgraded to 0.11.13 and now my build passes on my physical server or @telefunken Docker container

**Comment by gmarziou** [comment]
This explains also why it was working on my Windows server as the NodeJS installer uses the current stable version: 0.10.35.
I don't know why I initially selected 0.11 in Jenkins, I'll recommend to use 0.10 in the coming documentation.

**Comment by gmarziou** [comment]
Sorry, my second pull request about setting up CI got appended to my first one about client code doc.

**Comment by gmarziou** [comment]
For those who would like to review what I have documented before it gets merged, look at setup_ci_*.md files in https://github.com/jhipster/jhipster.github.io/tree/v2.0

**Comment by jdubois** [comment]
Great work @gmarziou !

Some comments:

- The end of the setting_up_ci_windows.md file is in French, you need to translate it to English
- For the Karma.js tests in the JUnit format -> shouldn't this be the default? I'd rather have this by default in the generator, and remove the documentation, what's your opinion?

**Comment by gmarziou** [comment]
- Sorry for the French part, it should be OK now.
- I agree with you about Karma tests, changing gruntfile.js and package.json should be safe but I'm not sure about the 'singleRun: true' in karma.conf.js, normally it should not be required as it is already set in Gruntfile.js. I can't remember clearly, I'll try again tomorrow and let you know. I'd also like to run clean builds in both dev and jenkins .

**Comment by jdubois** [comment]
@gmarziou OK, for the Karma tests it's cool if you can have a look at it, but anyway this is a great improvement over the existing documentation, can you submit a PR?

**Comment by gmarziou** [comment]
@jdubois just to clarify, you mean a PR for Karma test configuration as the PR for the doc is merged within the one about client code doc, right? I'll do it.

**Comment by jdubois** [comment]
Yes, if you can do both PR that's great, otherwise the documentation PR is already very good alone!

**Comment by jdubois** [comment]
Hi, can you send the PR about the documentation?

**Comment by gmarziou** [comment]
There's only one PR: https://github.com/jhipster/jhipster.github.io/pull/21 which includes several commits about CI and client code structure.
