### ISSUE TITLE
Multiple matching beans in tests when adding spring-boot-starter-data-rest as dependency

### ISSUE THREAD

**Issue by alexander-redmann-teaching** [jhipster/generator-jhipster#9042]
##### **Overview of the issue**

When i add the spring-boot-starter-data-rest dependency and i run the test and the test itself contains following autogenerated code:

@Autowired
private MappingJackson2HttpMessageConverter		jacksonMessageConverter;

or	

@Autowired
private FormattingConversionService				formattingConversionService;

With following error:
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.mycompany.myapp.web.rest.AuditResourceIntTest': Unsatisfied dependency expressed through field 'jacksonMessageConverter'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.http.converter.json.MappingJackson2HttpMessageConverter' available: expected single matching bean but found 4: mappingJackson2HttpMessageConverter,jacksonHttpMessageConverter,halJacksonHttpMessageConverter,alpsJsonHttpMessageConverter

##### **Motivation for or Use Case**

I need to add the spring-boot-starter-data-rest dependency for a projection on a database entity, but this will broke the tests

##### **Reproduce the error**

Create a project, with entities and add spring-boot-data-rest and the tests will be broken. For example AuditResourceIntTest

##### **Suggest a Fix**

Add Qualifier to the autogenerated lines to force bean selection
	
@Autowired
@Qualifier ("mappingJackson2HttpMessageConverter")
private MappingJackson2HttpMessageConverter		jacksonMessageConverter;
	
@Autowired
@Qualifier ("mvcConversionService")
private FormattingConversionService				formattingConversionService;

##### **JHipster Version(s)**

v5.4.2

an example in v5.7.2 show the same issue

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.xplace.timebutlertoaddison",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "5.4.2",
    "applicationType": "monolith",
    "baseName": "timebutlertoaddisonmapper",
    "packageName": "de.xplace.timebutlertoaddison",
    "packageFolder": "de/xplace/timebutlertoaddison",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en"
    ]
  }
}
</pre>
</details>

##### **Browsers and Operating System**

Ubuntu 12.04

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
This might be useful as a tip, but I don't see a jhipster issue here, as we don't support spring data test out of box.
