### ISSUE TITLE
Entity generation > one-to-one > Select through UI

### ISSUE THREAD

**Issue by MartinLichtblau** [jhipster/generator-jhipster#905]
It would be really nice and consistent when the one-to-one relation would have a UI to select one related entity element.
1. In commit 483cff5 you said such a thing isn't possible. But shouldn't it be just fine to show all elements of the related table, select one, and save the element.id as a foreign key in the newly created element of the other table?
2. I tried the REST create-method through the jhipster-API but couldn't create an element this way.

**Comment by timveil** [comment]
+1

**Comment by jdubois** [comment]
I'm closing this for lack of interest: I never use one-to-one relationships myself, and as nobody has contributed a patch after several months, this won't be done.
