### ISSUE TITLE
Reduntant this.queryCount and this.totalItems?

### ISSUE THREAD

**Issue by Tonterias** [jhipster/generator-jhipster#9057]
##### **Overview of the issue**

Are this.queryCount and this.totalItems just doing the same thing everywhere? Is not one of those variables just superflous / reduntant?

##### **Motivation for or Use Case**

This is not an error. Just asking if there a two things doing the same, because I can not see where there are used differently...

##### **Reproduce the error**

Not an error to reproduce

##### **Related issues**

no

##### **Suggest a Fix**

Delete one of them

##### **JHipster Version(s)**

Latest 5.7.2

##### **JHipster configuration**

Any

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

In every entity that paginates the result, you will find it

##### **Browsers and Operating System**

Any browser

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
`queryCount` is only used in the Angular client (React only uses `totalItems`), and the only times I see it set to a value are [entity-management](https://github.com/jhipster/generator-jhipster/blob/11db669ef5dc411db73f018df001a19cfe698f40/generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs#L101) and [user-management](https://github.com/jhipster/generator-jhipster/blob/11db669ef5dc411db73f018df001a19cfe698f40/generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs#L172), so I believe it's used as the same variable.

The PR should be simple so I think you can handle it @Tonterias.  If you need help just let us know.

Changes needed:
 - Replace `queryCount` with `totalItems` in the `jhi-item-count` directives
 - Remove `queryCount` variable where declared (use your IDE global search to help find these, or see below)

```
generators/entity-client/templates/angular/src/main/webapp/app/entities/infinite-scroll-template.ejs
26:    queryCount: any;

generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs
31:    queryCount: any;

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs
101:        this.queryCount = this.totalItems;

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
175:            <jhi-item-count [page]="page" [total]="queryCount" [itemsPerPage]="itemsPerPage"></jhi-item-count>
184:            <jhi-item-count [page]="page" [total]="queryCount" [maxSize]="5" [itemsPerPage]="itemsPerPage"></jhi-item-count>

generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.ts.ejs
38:    queryCount: number;
136:        this.queryCount = this.totalItems;

generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs
98:            <jhi-item-count [page]="page" [total]="queryCount" [itemsPerPage]="itemsPerPage"></jhi-item-count>

generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
48:    queryCount: any;
172:        this.queryCount = this.totalItems;
```

**Comment by DanielFran** [comment]
Closing since PR has been merged
