### ISSUE TITLE
Why server restart invalidate remember-me token ?

### ISSUE THREAD

**Issue by Avricot** [jhipster/generator-jhipster#906]
Once the server get rebooted, we get a CookieTheftException exception for connected users. 
I don't understand why, and I'm not sure if this should be the default behaviour. 
Any ideas about this ?

**Comment by jmirc** [comment]
Do you have any news on this issue?

**Comment by Avricot** [comment]
Can't reproduce it on my dev project, however I still get the issue on prod 

I don't understand why the token value would change :(

Btw, logs shouldn't trace the tokens in logs imo

    [DEBUG] com.petitetranche.security.CustomPersistentRememberMeServices - Remember-me cookie detected
    [INFO] com.petitetranche.security.CustomPersistentRememberMeServices - presentedToken=qQ5zoFGgSFURPXXXXXX== / tokenValue=AhwDM+C77QPJyAXXXXXX==
    [DEBUG] com.petitetranche.security.CustomPersistentRememberMeServices - Cancelling cookie
    [ERROR] org.springframework.boot.context.web.ErrorPageFilter - Forwarding to error page from request [/index.htmlnull] due to exception [Invalid remember-me token (Series/token) mismatch. Implies previous cookie theft attack.]
org.springframework.security.web.authentication.rememberme.CookieTheftException: Invalid remember-me token (Series/token) mismatch. Implies previous cookie theft attack.
	at com.petitetranche.security.CustomPersistentRememberMeServices.getPersistentToken(CustomPersistentRememberMeServices.java:175) ~[CustomPersistentRememberMeServices.class:na]
	at com.petitetranche.security.CustomPersistentRememberMeServices.processAutoLoginCookie(CustomPersistentRememberMeServices.java:86) ~[CustomPersistentRememberMeServices.class:na]

**Comment by jdubois** [comment]
@Avricot any news?

**Comment by jdubois** [comment]
No news, I'm closing this

**Comment by Avricot** [comment]
A quick update, we still have the error on prod, a solution might just be to revoke the cookie without any error, what do you think ?
