### ISSUE TITLE
ng-show items flash before loading

### ISSUE THREAD

**Issue by imduffy15** [jhipster/generator-jhipster#908]
ng-show items flash before loading if they aren't required. 

ng-cloak along with the necessary CSS should be used to hide them until it is known whether or not the element is needed.

```
[ng\:cloak], [ng-cloak], .ng-cloak {
    display: none !important;
}
```

**Comment by imduffy15** [comment]
Hi,

I tested this on the latest version today.
I can confirm the flickering still exists.

**Comment by andidev** [comment]
@jdubois  Was this issue resolved by itself or was somtheing coded?

It seems that the correct way to remove flickering of html elements that should not be visible according to the `ng-show` attribute is to add the `ng-cloak` class and the css class as mentioned by @imduffy15.

Is there a reason why this is not already done?

**Comment by andidev** [comment]
Sorry actually the css is injected by javascript. Howerver it works better if it is placed in header instead of at the bottom of the javascript.

But still the `<div ui-view="navbar" ></div>`  is missing the `ng-cloak`.

**Comment by jdubois** [comment]
@andidev no it hasn't been resolved -> I agree with you, ng-cloak should do the trick, but I haven't tested. The only reason why it's not done, is that nobody has done it yet! Could you send a PR on this?

**Comment by andidev** [comment]
Yes can do!

**Comment by andidev** [comment]
Hopefully this PR solves this issue for you @imduffy15 
If not maybe we need to move the ng-cloak css rule to be loaded before the vendor css rules.

Though there will allways be some minor flashing got from the font loading time.
