### ISSUE TITLE
Gatling 3 Support

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#9080]
Gatling 3 is already a few month old. We should support gatling 3 at least for jhipster 6. See https://gatling.io/docs/current/migration_guides/2.3-to-3.0/#to-3-0 for details

**Comment by jdubois** [comment]
I added a $100 bug bounty

**Comment by pmverma** [comment]
Is there any chance we can have gatling-maven-plugin back https://github.com/jhipster/generator-jhipster/issues/7042 since we are moving to gatling 3?

Not a mandatory thing but if issues with gatling 2.x are sovled in 3.x then it is good to have.

**Comment by atomfrede** [comment]
The Gatling maven plugin uses still the same classpath. I need to check if it works better but I don't think so. Therefore currently not in the scope of this ticket imho.
