### ISSUE TITLE
Improve JHipster generator-base API

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#9083]
##### **Overview of the feature request**

JHipster expose his API by the generator-base classe. IMHO this classe is really huge.  We could provide to JHipster a more user friendly API.

##### **Motivation for or Use Case**
The generator-base has nearly 3000 lignes of code. Most of those lignes are dealing with needle and the jhipsterUtils rewriteFile() function. 
I recently see that some of this functions does not work as expected because of wrong needle, bad filename or sometimes because the react case is not supported.

I think we could rework a large part of this file by define a needle API. This API will contain generic method to update files by using needles.

Exemple of a possible architecture : 

```
needle-base: {
    needle-client-base (generic method + webpack): [
          needle-client-angular,
          needle-client-react,
          needle-client-npm
    ],
    needle-server-base: [
        needle-server-maven,
        needle-server-gradle,
        needle-server-liquibase,
        needle-server-gradle,
        needle-server-cache
    ],
    needle-i18n
}
```
Those classes are all been taken from the same generator-base (it represent maybe the half of the generator-base classe).

The generator-base class will still expose the API and be the entrypoint. It's like a proxy to the whole API.

I assume this is a huge and risky work to do. But I'm sure it worth it.

The more we will simplify the needle code the more we could simplify the rest.

##### **Related issues or PR**
My first PR is here : https://github.com/jhipster/generator-jhipster/pull/9078
A WIP PR to show you how I imagine this : https://github.com/jhipster/generator-jhipster/pull/9082

/discuss

regards

PS: and good night ;)

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I'm ok to change the structure as long as there is no huge breaking changes for existing plugins. If you are willing to do that without causing big disruption you are welcome to PR

**Comment by avdev4j** [comment]
To avoid bugs as possible I still using the generator-base like a proxy 
`    addMavenRepository(id, url) {
        needleServerMaven.addRepository(id, url);
    }`

I keep the names.

**Comment by avdev4j** [comment]
Great @PierreBesson ! thank you.

**Comment by DanielFran** [comment]
@avdev4j https://github.com/jhipster/generator-jhipster/pull/9082 has been merged. Should we close this issue?

**Comment by pascalgrimaud** [comment]
let's close this (we can reopen later if needed)

**Comment by avdev4j** [comment]
Thanks guys for doing all this stuffs you did for me.

I would like to open another subject about this. We have the same issue with JSON writeFile API.

I think I can do the something like needle api. It's smaller (only 4 methods I think) but it's a lot of duplicated code that we can avoid easily.

What do you think about ?
