### ISSUE TITLE
[FEATURE] Add copy method in Filters and generated criterias

### ISSUE THREAD

**Issue by Blackdread** [jhipster/generator-jhipster#9084]
##### **Overview of the feature request**

Add copy method in Filters and generated criterias.

Two things  to do:
- add a method "copy()" -> optional but can be useful when using those classes with an abstraction of interfaces, proxy, adapter, etc
- add a copy constructor

Copy method implementation just call the copy constructor
```
public XXXX copy(){
    return XXXX(this);
}
```

The copy constructor then calls the copy method (for each fields) if copy method is defined (as it is optional in this feature request). Otherwise calls the copy constructor for each fields.

Once this feature is accepted, I will do the PR.
Need to decide if "copy()" method should be added.

You can check the reason for copy method below, the implementation use reflection but for jHipster it is not required as all classes are defined/known but all sub-classes must implement copy method of course.
The reflection is just for laziness as I did not want to implement copy method in all commands.
Copy method allow to copy without knowing the actual type of the copied class.
[Interface](https://github.com/Blackdread/canon-sdk-java/blob/master/camera-framework/src/main/java/org/blackdread/cameraframework/api/command/contract/CopyCommand.java)
[Implementation](https://github.com/Blackdread/canon-sdk-java/blob/master/camera-framework/src/main/java/org/blackdread/cameraframework/api/command/AbstractCanonCommand.java)

##### **Motivation for or Use Case**

Sometimes it is necessary to modify a filter/criteria but we do not want to modify the passed parameter, so to copy it is better, keep it "immutable" and result in no side effect when pass criteria/filter that may be modified

##### **Related issues or PR**

[PR java](https://github.com/jhipster/jhipster/pull/182)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Blackdread** [comment]
@jdubois Hi who could check if this can be merged? Then need to discuss on generator to create the copy method and constructor.


Also it would require to add an interface for all criterias
```
public interface Criteria {
    /**
     * @return a new criteria with copied filters
     */
    Criteria copy();
}
```
But should it be added in jhipster server code or in generator?

**Comment by DanielFran** [comment]
@jhipster/developers Can someone give opinion on this?

**Comment by Blackdread** [comment]
I did a pull #9363 , still fail but need to wait that dependency with jhipster is updated to match the merge of [jhipster #182](https://github.com/jhipster/jhipster/pull/182).

I think Criteria interface is necessary otherwise there is no way to just pass a criteria object and being to call copy method without cast or reflection.
The question is mainly, where shoulb that interface be, generator or jhipster then which package

**Comment by jdubois** [comment]
I'm totally trusting @Blackdread and @gzsombor here ( @gzsombor liked the idea on https://github.com/jhipster/jhipster/pull/182 ) as you are both the experts and big users of this.

For the interface: yes it should go to the "JHipster Framework", in fact we should put everything that doesn't need generation there.

**Comment by Blackdread** [comment]
All is merged so I close.
Thanks for adding the feature.
