### ISSUE TITLE
Wrong login URL when using OAuth2 and TLS

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#9086]
##### **Overview of the issue**

If I generate a JHipster application using the `authenticationType oauth2` application config and try to [develop using TLS](https://www.jhipster.tech/tls/), when I click on "Sign in", I'm redirected to a non existent page: http://localhost:8080/login

##### **Motivation for or Use Case**

Be able to develop and use TLS when using OAuth2 security.

##### **Reproduce the error**

```bash
cat >test.jdl <<EOF
application {
  config {
    applicationType monolith
    authenticationType oauth2
    baseName Test
    buildTool maven
    clientPackageManager yarn
    enableTranslation false
    languages [fr]
    nativeLanguage fr
    packageName com.mycompany.test
    prodDatabaseType postgresql
  }
  entities *
}
EOF
docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn -v "$HOME/.gitconfig:/home/jhipster/.gitconfig:ro" jhipster/jhipster:v5.7.2 jhipster import-jdl test.jdl --force
docker-compose -f src/main/docker/app.yml up keycloak &
./mvnw -Pdev,tls &
sleep 20
yarn start-tls
```
Then go to http://localhost:9000 & click on "Account" > "Sign in": it results in a 404 not found.

##### **Suggest a Fix**

I have tried to add `TLS_OPTION_ENABLED: options.tls` in `webpack.common.js` (inside the `new webpack.DefinePlugin({` part) and then add `
export const TLS_OPTION_ENABLED = process.env.TLS_OPTION_ENABLED;` in `app.constants.ts` and use it inside `login.service.ts`:
```javascript
        const protocol = TLS_OPTION_ENABLED ? 'https:' : '';
        location.href = protocol + '//' + location.hostname + port + location.pathname + 'login';
```
with an `import { TLS_OPTION_ENABLED } from 'app/app.constants';` but my variable is not taken into account, I don't know why...

##### **JHipster Version(s)**

```
test@0.0.0 /home/jhipster/app
`-- generator-jhipster@5.7.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "enableHibernateCache": true,
        "enableSwaggerCodegen": false,
        "enableTranslation": false,
        "jhiPrefix": "jhi",
        "languages": ["fr"],
        "messageBroker": false,
        "nativeLanguage": "fr",
        "packageName": "com.mycompany.test",
        "packageFolder": "com/mycompany/test",
        "prodDatabaseType": "postgresql",
        "searchEngine": false,
        "serviceDiscoveryType": false,
        "skipClient": false,
        "skipServer": false,
        "testFrameworks": [],
        "websocket": false,
        "applicationType": "monolith",
        "authenticationType": "oauth2",
        "baseName": "Test",
        "buildTool": "maven",
        "clientPackageManager": "yarn",
        "jhipsterVersion": "5.7.2",
        "skipUserManagement": true,
        "cacheProvider": "ehcache",
        "clientFramework": "angularX",
        "serverPort": "8080",
        "useSass": true,
        "otherModules": []
    },
    "entities": []
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1

node: v10.14.1

npm: 6.5.0

yeoman: 2.0.5

yarn: 1.12.3

##### **Browsers and Operating System**

Chromium and Firefox on Ubuntu 16.04 LTS.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by anthony-o** [comment]
For my fix to work, I also had to modify `module.exports = (options) => webpackMerge(commonConfig({ env: ENV }), {` in `webpack.dev.js` to `module.exports = (options) => webpackMerge(commonConfig(Object.assign(Object.assign({}, options), { env: ENV })), {` perhaps I should open another issue for this: in development, console `options` are not passed to `webpack.common.js`...

**Comment by vishal423** [comment]
can you check latest master branch code to see if commit https://github.com/jhipster/generator-jhipster/pull/9059 fixes your issue?

**Comment by anthony-o** [comment]
@vishal423 yes I can confirm that current `jhipster/jhipster:master` Docker image (`Digest: sha256:84b92aed77a521853db6f3f467019e76673cc1065e96bf5abf7ceaf3f1327b32`) generated me an application that correctly pointed me to the Keycloak I've launched with `docker-compose -f src/main/docker/app.yml up keycloak` when click on "Sign in".

Nevertheless, it is still unusable because now the Keycloak configuration is wrong, it sends a `400` error telling "**We're sorry... Invalid parameter: redirect_uri**".
The URL is http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth?client_id=web_app&redirect_uri=https://127.0.0.1:8080/login&response_type=code&scope=openid%20profile%20email&state=9bMyQk

**Comment by vishal423** [comment]
I did quick check and able to get it working with below changes:
1. In webpack.dev.js -- change target url to specify `localhost` instead of `127.0.0.1`
> target: `http${options.tls ? 's' : ''}://localhost:8080`,
2. Update web_app client in keycloak to add following redirect url:
> https://localhost:8080/*

**Comment by lmbai** [comment]
In the PR #9059  fixed a issue with the 8080 port when using the 9000 port for proxy. 
But I didn’t test the Https.  Maybe you can checkout the latest code to try

**Comment by anthony-o** [comment]
@lmbai, as said [previously](https://github.com/jhipster/generator-jhipster/issues/9086#issuecomment-455533978), I tested the #9059 modifications with TLS, and then I have a Keycloak error.
However, I didn't test [@vishal423 suggestion](https://github.com/jhipster/generator-jhipster/issues/9086#issuecomment-455645187) yet.

**Comment by lmbai** [comment]
@anthony-o ,  i think @vishal423 's suggestion should work. just test it

**Comment by anthony-o** [comment]
@vishal423 & @lmbai : no I'm sorry, I've tested to change `webpack.dev.js` from `http${options.tls ? 's' : ''}://127.0.0.1:8080` to `http${options.tls ? 's' : ''}://localhost:8080`, I still have a **`Invalid parameter: redirect_uri`** on page http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth?client_id=web_app&redirect_uri=https://localhost:8080/login&response_type=code&scope=openid%20profile%20email&state=wGSbl3 this time.
This is surely due to the Keycloak created in Docker which uses `src/main/docker/realm-config/jhipster-realm.json` which defines `"redirectUris": ["http://localhost:8080/*", "http://localhost:8100/*", "http://127.0.0.1:8761/*", "http://localhost:9000/*"],` and `"webOrigins": ["http://localhost:8080/*", "http://localhost:8100/*", "http://127.0.0.1:8761/*", "http://localhost:9000/*"],` (no https here).

**Comment by ruddell** [comment]
@anthony-o Read @vishal423's comment again, it says you need to add the https URL to your keycloak `redirectUris`.  You can update jhipster-realm.json and restart Keycloak

**Comment by anthony-o** [comment]
@ruddell , @lmbai & @vishal423 OK I added `"https://localhost:8080/*"` to `"redirectUris"` in `jhipster-realm.json` and this time this is working.

I tried to generate the application with latest `v5.8.1`, the problem still exists with generated sources, I think one should fix it by modifying https://github.com/jhipster/generator-jhipster/blob/master/generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs tu include the HTTPS option isn't it ?

**Comment by ruddell** [comment]
@anthony-o  Would you like to create a pull request to fix it?
