### ISSUE TITLE
Document `export-jdl` sub-generator

### ISSUE THREAD

**Issue by mark-monteiro** [jhipster/generator-jhipster#9089]
##### **Overview of the feature request**

The `export-jdl` sub-generator is very useful but I could not find any documentation on it anywhere. The only reason I was able to find out that it exists at all was via a google search that led to the original GitHub issue where it was requested as a feature: https://github.com/jhipster/jhipster-core/issues/64

My recommendation would be to add it as a new section to existing JDL documentation page here: https://www.jhipster.tech/jdl/

##### **Motivation for or Use Case**

This feature should be documented so that users know
* that the feature exists
* what the sub-generator does
* any options that can be specified when running it
* any limitations of the conversion

##### **Related issues or PR**

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Although it is documented in the CLI itself (`jhipster --help`), it could be mentioned in the JDL docs as well. Would you like to submit a PR to https://github.com/jhipster/jhipster.github.io ?

As for the cli options that can be passed to it, there is only the optional name of the export JDL file.

```
➜  ~ jhipster export-jdl --help
  Usage: export-jdl [options] [jdlFile]

  Create a JDL file from the existing entities

  Options:

    -h, --help  output usage information
Usage:
  yo jhipster:export-jdl [<jdlFile>] [options]

Arguments:
  jdlFile    Type: String  Required: false

Description:
    Creates JDL from the json entities
Example:
    jhipster export-jdl
    jhipster export-jdl jhipster.jh
```
