### ISSUE TITLE
[Vote] Which authentification mechanisms should we provide?

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#910]
We currently provide:
- "formed based" authentication with Spring Security, which we have extended so you can invalidate sessions, have a better cookie theft feature, etc...
- OAuth2 authentification, which requires us to have our own server side implementation in MongoDB (and soon in Cassandra)

Both options are good and are two different approaches.

Now we have 4 other options that are currently opened tickets:
- #684 Support Spring Social
- #813 Use Json Web Tokens
- #892 x-auth-token authentication method
- #903 use Angular Token

Obviously, we can't support all of them, so we need to choose. From my personal point of view, what we already have is good enough, and I don't know if those other mechanisms are good/secured/useful.

So I'm opening this ticket to start a discussion and a vote, and close the mechanisms that we will not support.

**Comment by sdoxsee** [comment]
I'm not too familiar with spring social but I know that jwt is growing in popularity and isn't just limited to the Java world. I think jwt would be great

+1 JWT

**Comment by sdoxsee** [comment]
..or at least don't close the poll yet. What is already in jhipster is fine for now. I wouldn't change much yet after only hearing from a few people on a poll that wasn't tweeted about. 
Jwt, oauth2 + openid connect is a powerful authentication/authorization combination with ietf standards and support from big players (jwt is authorization not authentication in itself but openid connect is authentication). I admit it isn't simple but I think it's worth it at the right time. 
If you do need to change direction right now, I wouldn't go far from what you currently have. 

I'm very interested in this topic and only saw this poll now!

**Comment by pvlastaridis** [comment]
OAUTH2 is here to stay and maybe a small Android App to connect to it and do some Basic CRUD operation? Anyone from Coursera MOOC Specialization could help.

**Comment by jmirc** [comment]
My goal is to do a refactor of the current generator to be able to add a new authentication support easily.
