### ISSUE TITLE
Use Faker.js to generate test data

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#9103]
Please note I have a fully working prototype on the PR below.

[Faker.js](https://github.com/marak/Faker.js/) is a JavaScript library to generate "fake" data. For example, it can generate sample first names.

Like we already do with the "user" and "authority" tables, the idea here is to generate rows of fake data for each generated entity:

- For each entity, there would be 20 rows of "fake" data, so people can better test/understand the generated code
- This data is generated in .csv files, so it can easily be edited with Excel (for example), in order to have better data (maybe even true business data)
- The generator is smart enough to recognize some column names, like "first_name", and will generate appropriate fake data for those
- It is limited to what can be inserted into databases: if you put advanced validation logic in your entity's fields, it will not work totally well. That means the data will be inserted (as it will work at the database level), but you will have validation errors when trying to save it from the Web UI, going through bean validation. I do not think this is a big problem, everybody understands this is fake data, and not perfect business data

I think this would help many people when starting their application for the first time, and then would still be a great help later, as being able to have some initial data in all tables is often a requirement.

**Comment by ruddell** [comment]
A common issue I see in Gitter is that people edit `users.csv`, which causes the liquibase checksum to fail on the next startup (because the data doesn't match).  You can reproduce this by starting an app, then adding a new user to `users.csv` and trying to start the app a second time.

**Comment by deepu105** [comment]
I assume this would add the data only for dev db. May be we should also have a cli flag to disable adding this data since someone might not want it

**Comment by jdubois** [comment]
Yes we should probably limit this for dev (we already have the flag for test, look at the end of the "initial" changelog).

Then people need to learn Liquibase, and thus this shouldn't be the default option.

**Comment by vishal423** [comment]
Can this be made optional via some flag like suggested by @deepu105 ?

**Comment by gmarziou** [comment]
@jdubois How would you handle required relationships ?

**Comment by jdubois** [comment]
@vishal423 @deepu105 yes there could be a flag for this.
@gmarziou I'm currently not handling them. My current idea is to link them using the IDs in order (so line 1 in table A is linked to line 1 in table B), as I'm always doing 20 lines per table. Then, it's a bit complex (also for many-to-many relationships), so I'm not sure if that's worth the effort.

**Comment by gmarziou** [comment]
Regarding the issue about liquibase checksums for users changing CSV contents, I wonder this would work: generate a changeset that first deletes all rows and then inserts them from CSV, and using the
 `runOnChange` attribute.
