### ISSUE TITLE
Can't use a different user with Liquibase

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#9106]
##### **Overview of the issue**

When trying to use a different user to apply liquibase modifications ([`spring.liquibase.user`](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-execute-liquibase-database-migrations-on-startup)), I've got an error which indicates that the generated application is not able to use such different user.

##### **Motivation for or Use Case**

One should be able to use the [standard Liquibase for Spring integration features](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html) (and specifically the ability to use different users when Liquibase apply its modifications and when the application is using the DB) on a JHipster generated application.

##### **Reproduce the error**
Generate the application:
```bash
cat >test.jdl <<EOF
application {
  config {
    applicationType monolith
    baseName Test
    buildTool maven
    clientPackageManager yarn
    devDatabaseType postgresql
    enableTranslation false
    languages [fr]
    nativeLanguage fr
    packageName com.mycompany.test
    prodDatabaseType postgresql
  }
  entities *
}

entity TestTable {
	fieldInt Integer
	fieldBigD BigDecimal
	fieldString String
}
EOF

docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn -v "$HOME/.gitconfig:/home/jhipster/.gitconfig:ro" jhipster/jhipster:v5.7.2 jhipster import-jdl test.jdl --force

cat >src/main/docker/postgresql.yml <<EOF
version: '2'
services:
    test-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/Test/postgresql/:/var/lib/postgresql/data/
        environment:
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
            - POSTGRES_USER=Test_owner
            - POSTGRES_PASSWORD=Test_owner
            - POSTGRES_DB=Test
        ports:
            - 5432:5432
EOF
cat >src/main/docker/init-db.sql <<EOF
CREATE SCHEMA Test;

ALTER SCHEMA Test OWNER TO Test_owner;
GRANT ALL PRIVILEGES ON SCHEMA Test TO Test_owner;

CREATE USER Test WITH PASSWORD 'Test';
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA Test TO Test;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA Test TO Test;
GRANT CONNECT ON DATABASE Test TO Test;
GRANT USAGE ON SCHEMA Test TO Test;

ALTER DATABASE Test SET search_path TO Test;
EOF

sed -i "/datasource:/,/password:/c\    datasource:\n\
        type: com.zaxxer.hikari.HikariDataSource\n\
        url: jdbc:postgresql://localhost:5432/Test\n\
        username: Test\n\
        password: Test" src/main/resources/config/application-dev.yml

cat >spring_config_add_liquibase_owner.txt <<EOF
        user: Test_owner
        password: Test_owner
EOF
sed -i "/liquibase:/r spring_config_add_liquibase_owner.txt" src/main/resources/config/application-dev.yml
```
Launch it:
```bash
docker-compose -f src/main/docker/postgresql.yml up &
./mvnw
```

Got this stacktrace:

    2019-01-21 10:28:16.259 DEBUG 30534 --- [  restartedMain] org.postgresql.Driver                    : Connection error: 

    org.postgresql.util.PSQLException: FATAL: password authentication failed for user "Test"
	    at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:514)
	    at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	    at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	    at org.postgresql.Driver.makeConnection(Driver.java:454)
	    at org.postgresql.Driver.connect(Driver.java:256)
	    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
	    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
	    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
	    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
	    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	    at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.afterPropertiesSet(AsyncSpringLiquibase.java:79)

which indicates that my generated application is using `Test` user and not `Test_owner` as asked in the modified `application-dev.yml`.

##### **Suggest a Fix**

This is due to the generated `LiquibaseConfiguration.java` which creates a new `io.github.jhipster.config.liquibase.AsyncSpringLiquibase` as `SpringLiquibase` bean, overwriting the behavior of [`org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration.LiquibaseConfiguration#createSpringLiquibase`](https://github.com/spring-projects/spring-boot/blob/v2.0.6.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java#L134): in `LiquibaseConfiguration.java` there is a simple `liquibase.setDataSource(dataSource)` whereas in the SpringBoot auto configuration, the `LiquibaseConfiguration.user` & `.url` and `.password` is taken into consideration when creating the `DataSource` in [`org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration.LiquibaseConfiguration#createNewDataSource`](https://github.com/spring-projects/spring-boot/blob/v2.0.6.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java#L156).

##### **JHipster Version(s)**

```
test@0.0.0 /home/jhipster/app
`-- generator-jhipster@5.7.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "databaseType": "sql",
        "devDatabaseType": "postgresql",
        "enableHibernateCache": true,
        "enableSwaggerCodegen": false,
        "enableTranslation": false,
        "jhiPrefix": "jhi",
        "languages": ["fr"],
        "messageBroker": false,
        "nativeLanguage": "fr",
        "packageName": "com.mycompany.test",
        "packageFolder": "com/mycompany/test",
        "prodDatabaseType": "postgresql",
        "searchEngine": false,
        "serviceDiscoveryType": false,
        "skipClient": false,
        "skipServer": false,
        "testFrameworks": [],
        "websocket": false,
        "applicationType": "monolith",
        "baseName": "Test",
        "buildTool": "maven",
        "clientPackageManager": "yarn",
        "jhipsterVersion": "5.7.2",
        "skipUserManagement": false,
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "clientFramework": "angularX",
        "serverPort": "8080",
        "useSass": true,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "otherModules": []
    },
    "entities": ["TestTable"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity TestTable {
  fieldInt Integer,
  fieldBigD BigDecimal,
  fieldString String
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1

node: v10.14.1

npm: 6.5.0

yeoman: 2.0.5

yarn: 1.12.3

##### **Browsers and Operating System**

Chromium & Firefox on Ubuntu 16.04 LTS

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by anthony-o** [comment]
I found the following workaround.

Create `src/main/java/<package>/config/DataSourceClosingAsyncSpringLiquibase.java`:

```java
package <package>.config;

import io.github.jhipster.config.liquibase.AsyncSpringLiquibase;
import liquibase.exception.LiquibaseException;
import org.springframework.beans.factory.DisposableBean;
import org.springframework.core.env.Environment;
import org.springframework.core.task.TaskExecutor;
import org.springframework.util.ReflectionUtils;

import java.lang.reflect.Method;

/**
 * Copy of org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase behavior for io.github.jhipster.config.liquibase.AsyncSpringLiquibase
 */
public class DataSourceClosingAsyncSpringLiquibase extends AsyncSpringLiquibase implements DisposableBean {

    private volatile boolean closeDataSourceOnceMigrated = true;


    public DataSourceClosingAsyncSpringLiquibase(TaskExecutor taskExecutor, Environment env) {
        super(taskExecutor, env);
    }


    public void setCloseDataSourceOnceMigrated(boolean closeDataSourceOnceMigrated) {
        this.closeDataSourceOnceMigrated = closeDataSourceOnceMigrated;
    }

    @Override
//    public void afterPropertiesSet() throws LiquibaseException {
    protected void initDb() throws LiquibaseException {
        super.initDb();
        if (this.closeDataSourceOnceMigrated) {
            closeDataSource();
        }
    }

    private void closeDataSource() {
        Class<?> dataSourceClass = getDataSource().getClass();
        Method closeMethod = ReflectionUtils.findMethod(dataSourceClass, "close");
        if (closeMethod != null) {
            ReflectionUtils.invokeMethod(closeMethod, getDataSource());
        }
    }

    @Override
    public void destroy() throws Exception {
        if (!this.closeDataSourceOnceMigrated) {
            closeDataSource();
        }
    }
}
```
And modify `src/main/java/<package>/config/LiquibaseConfiguration.java`:
```java
    @Bean
    public SpringLiquibase liquibase(@Qualifier("taskExecutor") TaskExecutor taskExecutor,
                                     DataSource dataSource, LiquibaseProperties liquibaseProperties, DataSourceProperties dataSourceProperties) {

        // Use liquibase.integration.spring.SpringLiquibase if you don't want Liquibase to start asynchronously
        SpringLiquibase liquibase;
        // Copy org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration.LiquibaseConfiguration.createSpringLiquibase behavior for DataSource
        if (liquibaseProperties.getUrl() != null || liquibaseProperties.getUser() != null) {
            liquibase = new DataSourceClosingAsyncSpringLiquibase(taskExecutor, env);
            // specific datasource
            String url = getProperty(liquibaseProperties::getUrl,
                dataSourceProperties::getUrl);
            String user = getProperty(liquibaseProperties::getUser,
                dataSourceProperties::getUsername);
            String password = getProperty(liquibaseProperties::getPassword,
                dataSourceProperties::getPassword);
            dataSource = DataSourceBuilder.create()
//                .driverClassName(dataSourceProperties.determineDriverClassName())
                .url(url)
                .username(user)
                .password(password)
                .build();
        } else {
            liquibase = new AsyncSpringLiquibase(taskExecutor, env);
        }
        liquibase.setDataSource(dataSource);
        liquibase.setChangeLog("classpath:config/liquibase/master.xml");
        liquibase.setContexts(liquibaseProperties.getContexts());
        liquibase.setDefaultSchema(liquibaseProperties.getDefaultSchema());
        liquibase.setDropFirst(liquibaseProperties.isDropFirst());
        liquibase.setChangeLogParameters(liquibaseProperties.getParameters());
        if (env.acceptsProfiles(JHipsterConstants.SPRING_PROFILE_NO_LIQUIBASE)) {
            liquibase.setShouldRun(false);
        } else {
            liquibase.setShouldRun(liquibaseProperties.isEnabled());
            log.debug("Configuring Liquibase");
        }
        return liquibase;
    }
```

**Comment by pascalgrimaud** [comment]
@anthony-o @DanielFran : it is opened since 5 months. How can we advance on this ?
Is it an improvement we can provide easily, without complex code or breaking stuff ?
If yes, who wants to do this ?
Otherwise, as there is very no comment, I'd like to close this:
- lack of interest
- our current configuration works out of the box, so I'm fine with this

**Comment by DanielFran** [comment]
@pascalgrimaud sorry, I forget it completly!
Will try to work on it next week...

**Comment by pascalgrimaud** [comment]
@DanielFran : don't be sorry, it's just a reminder. I'm trying to close old ticket :)
If you plan to work on this, it's ok, nothing urgent !

**Comment by amatosg** [comment]
> @anthony-o @DanielFran : it is opened since 5 months

7 months :speak_no_evil:

**Comment by DanielFran** [comment]
@amatosg thanks for the remind, I started working on it...

**Comment by DanielFran** [comment]
@anthony-o @amatosg Can you please make some tests and confirm it is ok please?
