### ISSUE TITLE
Embedded MongoDB uses old server version (3.2.2)

### ISSUE THREAD

**Issue by bilelbm** [jhipster/generator-jhipster#9108]
Hello,
im trying to create unit tests for mongodb but from the documentation jhipster uses 
de.flapdoodle.embed.mongo which is an embedded mongodb the issue is the server version that starts is 3.2.2 and my tests use features from version 3.6. 
de.flapdoodle.embed.mongo already deprecated version 3.2.2 but for some reason jhipster starts that old version.
Using JHipster 5.7.0

**Comment by DanielFran** [comment]
@bilelbm The version will now be managed in jhipster-bom.
This will be included in next v6 release.

Note: next time please fill correctly the issue.
