### ISSUE TITLE
Move client app to classpath:/public

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#9118]
##### **Overview of the feature request**

By default Spring-boot serves anything that is into `classpath:/public`
So I propose to build the client into `target/classes/public` instead of `target/www`.
With this we can remove our custom addition of static assets for IDEs in WebConfigurer.
So far I've tested with IDEA, maven, and `java -jar`. Not yet by deploying in an app server, not yet with gradle.
We have a lot of ways to run the app and it can be tricky. Do you see use-cases I'm missing ?

##### **Motivation for or Use Case**

* Policy 1, less custom code
* Our current implementation can have a bad effect if someone runs the prod war from a dir that has a `target/www` directory. In that case our detection will serve what is in this folder instead of what is in the war.
* This would be compatible with Webflux (our current is not : you can't do `setDocumentRoot` in Webflux)
* After that, we may be able to use Spring's built-in cache control instead of our custom cache filter.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
We use `target/classes/static` for the `index.html` of microservices, we should be consistent and use same location for both microservices and web apps (monoliths and gateways). I think that Spring Boot processes `static` and `public` the same way

**Comment by cbornet** [comment]
Yes static or public behave the same.

**Comment by gmarziou** [comment]
Maybe there is something to configure in Spring Boot devtools so that changes made by webpack in target/classes/public do not trigger a reload.

**Comment by cbornet** [comment]
Yes it's possible to prevent the reload : https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-restart-exclude

**Comment by cbornet** [comment]
For gradle Isee that we already copy `build/www` into `build/resources/main/static` for buildJar. So I guess we could generate directly into the latter and configure bootRun and bootWar accordingly. WDYT @atomfrede ?

**Comment by PierreBesson** [comment]
I totally agree with this change, it can be done for v6. `/public` has always be the correct place to put assets as recommended in the spring boot docs.

**Comment by atomfrede** [comment]
@cbornet Yes +1 lets remove more custom configuration and tasks.

**Comment by deepu105** [comment]
Please note we tried to do it once and then rolled back due to some issue.
I'm with phone now so can't dig up the issue

**Comment by jdubois** [comment]
Yes same comment as @deepu105 ! Be careful and test well

**Comment by cbornet** [comment]
@deepu105 @jdubois yes, that's what I feared. Do you have history on what were the issues ?

**Comment by deepu105** [comment]
I need to dig it up

**Comment by jdubois** [comment]
Also maybe some issue with the hot reload? I don't remember the issue, but we definitely had something that blocked us from doing this

**Comment by ruddell** [comment]
Here's the issue where we reverted the change to public https://github.com/jhipster/generator-jhipster/issues/8586

**Comment by cbornet** [comment]
Thanks @ruddell . I understand why we rolled back to fix it quickly but I think we should try to make that work on app servers. I'll give it a try.

**Comment by cbornet** [comment]
In v5.4.2, the maven-war-plugin hadn't been configured to use the resources from /public
I have it working fine when doing proper configuration.
One of the issues is that the app server will serve assets at the root of the WAR which are copied from `<warSourceDirectory>` which defaults to `src/main/webapp` (and that we currently set to target/www) and Spring will add assets from `classpath:/public` during its autoconf. If we set warSourceDirectory to `target/classes/public`, the resources are present twice in the jar.

So there are two solutions I see:
1/ change `warSourceDirectory` to `target/classes/public` and exclude `WEB-INF/classes/public` with `packagingExcludes`  --> SB autoconf will not be used, will not work when/if we do a jar
2/ or move the front-end code from `src/main/webapp` to another directory (src/main/www ?) so that its content is not copied into the war --> SB autoconf is used.

Personally I'd vote for 2/ since it's closer to Spring Boot defaults but I'm open for discussion.

**Comment by atomfrede** [comment]
We always do src/main/www when we used angular 1 without any transpiling necessary src/main/webapp was the right directory. So I would go with option 2

**Comment by PierreBesson** [comment]
Option 2 looks OK. Most importantly, the configuration need to be simple and respect the defaults for the standard jar mode. If it's a bit convoluted to create the war it's not a huge issue.

**Comment by pascalgrimaud** [comment]
I always saw `src/main/webapp/` in all of my projects, so migrate to `src/main/www/` looks a little bit strange for me, but I'm not against it.

> We always do src/main/www when we used angular 1 without any transpiling necessary src/main/webapp was the right directory. So I would go with option 2.

@atomfrede : I switch to v1 and v2, and I don't see this folder, we always used `src/main/webapp/` -> are you sure about that ?

I'd like to know what @deepu105 and @jdubois think about this change ?

**Comment by atomfrede** [comment]
@pascalgrimaud I think of the very early days, when we hat ng1 without using es6. In that case all files in `src/main/webapp` could go without any postprocessing into the war. With es6 or typescript this is not the case anymore. So at work when we have a java backend and vue frontend we use  `src/web` or `src/main/web`.

**Comment by cbornet** [comment]
The problem is that by default Spring will set  `src/main/webapp` as document root if it exists so the content of `src/main/webapp` is served when starting with maven or IDE.

**Comment by deepu105** [comment]
as I mentioned in the PR, I would prefer to keep `webapp` dir but if moving to `www` is the only good option then I'm fine with it

**Comment by Tcharl** [comment]
Couldn't be a 3)? src/main/webapp is the Maven standard: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
Even if it's a minor change, mosts of the Maven users could be disapointed (86% of the user base)

**Comment by cbornet** [comment]
But Spring Boot sets it as document root and that's not what we want. This is why we currently have custom code to change the document root to target/www.

**Comment by cbornet** [comment]
So what do we do ?
1/ keep code in src/main/webapp and:
  * configure maven-war-plugin to exclude its content from the war
  * change the document root to target/classes/public if it's detected
2/ move static source to src/main/www
3/ move static source to src/main/web

**Comment by pascalgrimaud** [comment]
I vote for keeping `src/main/webapp`, so for 1/, but I'm fine if we need to choose 2/ or 3/
