### ISSUE TITLE
Jhipster and kafka 2.x

### ISSUE THREAD

**Issue by warnonphilippe** [jhipster/generator-jhipster#9147]
##### **Overview of the feature request**

Jhipster 5.7 generates a kafka.yml file still referencing kafka 1.0.0. 
Is Kafka 2.x well supported (and already tested) by jhipster. If yes, is the move to kafka 2.x planned ?

##### **Motivation for or Use Case**

Kafka is a very important component in micro-services architecture. Kafka 2.0 was delivered in june 2018 but jhipster, while evolving great in general, didn't migrate kafka 2.0. It could be nice to use jhipster generated app with the latest version of kafka and its associated tools.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
In our `spring-boot_2.1.0` branch, we already use Kafka 2.0.
See https://github.com/jhipster/generator-jhipster/blob/spring-boot_2.1.0/generators/generator-constants.js#L35

But honestly, we have very few feedback about Kafka so not sure it works well.

**Comment by pascalgrimaud** [comment]
I'm closing this, as it is done in our `spring-boot_2.1.0` branch and it will be merged soon into `master`.
