### ISSUE TITLE
UAA with Gateway error in dev profile

### ISSUE THREAD

**Issue by diegobs2** [jhipster/generator-jhipster#9162]
##### **Overview of the issue**

When i tried to login with Gateway to UAA Service in localhost without dockers , using eclipse IDE,
i cant login and the error displayed is "No instances available for localhost".
I started the UAA localhost:9999 and Gateway localhost:8080 .
I tried to change this line of application.dev.yaml

security:
        client-authorization:
            access-token-uri: http://web_app:changeit@localhost:9999/oauth/token  
            #http://uaabaeldung/oauth/token

i just followed the example related on https://www.baeldung.com/jhipster-uaa-secured-micro-service.

Please help!

##### **JHipster Version(s)**

Jhipster 5.7.2

##### **JHipster configuration**

Gateway Config : 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.cosentino.gateway",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.7.2",
        "applicationType": "gateway",
        "baseName": "gatewayBaeldung",
        "packageName": "com.cosentino.gateway",
        "packageFolder": "com/cosentino/gateway",
        "serverPort": "8080",
        "authenticationType": "uaa",
        "uaaBaseName": "uaaBaeldung",
        "cacheProvider": "hazelcast",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": "eureka",
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "clientFramework": "angularX",
        "useSass": false,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en", "es"]
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.20.1.windows.1

node: v10.15.0

npm: 6.4.1

yarn: 1.13.0

UAA Config : 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.cosentino.uaa",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.7.2",
    "applicationType": "uaa",
    "baseName": "uaaBaeldung",
    "packageName": "com.cosentino.uaa",
    "packageFolder": "com/cosentino/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ],
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.20.1.windows.1

node: v10.15.0

npm: 6.4.1

yarn: 1.13.0

##### **Browsers and Operating System**

Windows 10
Google Chrome
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by lmbai** [comment]
@diegobs2  did you start the registry service ?

**Comment by lmbai** [comment]
based on you config `"serviceDiscoveryType": "eureka",`
you config the the `eureka` as service discovery , you need to start the Jhipster registry. 
you should not change the `access-token-uri: http://web_app:changeit@localhost:9999/oauth/token`.
they don't use the ip, they will use the service name registerred in the `eureka` side. 
if you are not familliar with this, you better run it in docker. (start up all the dependent service with the IDE will be a bit difficult)

**Comment by diegobs2** [comment]
I tried to start all structure with docker. Using docker-compose with this file.

version: '2'
services:

    jhipster-registry:
        image: jhipster/jhipster-registry
        volumes:
            - ./central-server-config:/central-config
        # When run with the "dev" Spring profile, the JHipster Registry will
        # read the config from the local filesystem (central-server-config directory)
        # When run with the "prod" Spring profile, it will read the configuration from a Git repository
        # See https://www.jhipster.tech/microservices-architecture/#registry_app_configuration
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev,swagger,uaa
            - SPRING_SECURITY_USER_PASSWORD=admin
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/
            #- SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
            #- SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
            #- SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
        ports:
            - 8761:8761
    
    uaa-app:
        image: uaa
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'SPRING_DATASOURCE_URL=jdbc:mariadb://uaa-mariadb:3306/uaa'
            - JHIPSTER_SLEEP=10
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
            - JHIPSTER_REGISTRY_PASSWORD=admin
    uaa-mariadb:
        image: 'mariadb:10.3.7'
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=uaa
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    
    gateway-app:
        image: gateway
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mariadb://gateway-mariadb:3306/gateway
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
            
    gateway-mariadb:
        image: mariadb:10.3.7
        # volumes:
        #     - ~/volumes/jhipster/gateway/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=gateway
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    
    
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
    kafka:
        extends:
            file: kafka.yml
            service: kafka

The result is registry and gateway up but my uaa service didnt appear in registry and docker log this output error when tried to up uaa.
java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:136)
at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
uaa-app_1            |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:91)
at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:118)
at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:153)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$43388bc8.locate(<generated>)
 at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94)
 at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:628)
at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:364)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
at com.cosentino.gateway.UaaApp.main(UaaApp.java:65)
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8761/config/uaa/prod/master": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
'

**Comment by pascalgrimaud** [comment]
You have different errors here.

I tested it this morning:
- broken in dev profile
- it works well in prod profile

**Comment by lmbai** [comment]
@diegobs2 
for the gateway, you configured the registry . but for the uaa, you missed the registry config.
can you add the following for the uaa-app?  i believe this is the reason why the uaa is not register in the registry. 
```
- EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
```
> the default config is `http://admin:${jhipster.registry.password}@localhost:8761/eureka/`, it won't work when runing in docker.

**Comment by lmbai** [comment]
@diegobs2 , for the docker-compose file, you can use `jhipster docker-compose` to generate a tempate
here i create a sample based on the v5.7.2 [issue9612-jh_v572](https://github.com/lmbai/jhipster-playground/tree/master/issues/issue9612/issue9612-jh_v572)

@pascalgrimaud i checked this and generate serveral projects based the jhipster `v5.7.2` and `v5.8.1`
>issue9162
---v572
---v581

- build the gateway in dev profile. 
- build the gateway in prod profile
- run the gateway in prod
- run the gateway in dev
- run the webpack proxy `yarn start`

it works well. here is the [sample ](https://github.com/lmbai/jhipster-playground/tree/master/issues/issue9612)

may i know more detail that `it break in dev profile`?

**Comment by pascalgrimaud** [comment]
@lmbai : it is probably related to https://github.com/jhipster/generator-jhipster/issues/9261

**Comment by lmbai** [comment]
@pascalgrimaud it is possible。
 During the test： run in dev profile, it start up smoothly. when i login, first 2 times, there is a Zuul exception, but the third time, it works.
It may related to to the 9261. I didn't read the detail. did the bug only related when use UAA ?

**Comment by lmbai** [comment]
> @pascalgrimaud it is possible。
> During the test： run in dev profile, it start up smoothly. when i login, first 2 times, there is a Zuul exception, but the third time, it works.
> It may related to to the 9261. I didn't read the detail. did the bug only related when use UAA ?

@pascalgrimaud  No, it is not related, the `lazy` logic was introduced recently. we havn't release it yet. it is not in v5.8.1 or v5.7.2. 

for this ticket, i don't think it is related.

**Comment by diegobs2** [comment]
Okey guys, thanks so much!

**Comment by pascalgrimaud** [comment]
With the last beta release 6.0.0-beta.0, UAA seems to work well.
We have protractor passed with dev and prod profile.
Don't hesitate to comment this ticket if you still got issue.

So I'm closing this, because it's resolved.
