### ISSUE TITLE
Small changes: create a generateListFromPage method in PaginationUtil class

### ISSUE THREAD

**Issue by Gigaxel** [jhipster/generator-jhipster#9209]
##### **Overview of the feature request**

Static method in PaginationUtil class for creating a Page from a List

##### **Motivation for or Use Case**

In almost every jhipster project I've worked on, I needed a utility method for creating a Page from a List, and I've talked to a couple of my colleagues, and they've come across that issue too. 
That's why I've decided to create that utility static method in the PaginationUtil class. The usage is pretty simple and doesn't need any explanation.

```
PaginationUtil.generatePageFromList(yourList, pageable); // returns Page
```

The implementation is also very simple:

```
public static <T> Page<T> generatePageFromList(List<T> list, Pageable pageable) {
  if (list == null) {
      throw new IllegalArgumentException("To create a Page, the list mustn't be null!");
  }

  int startOfPage = pageable.getPageNumber() * pageable.getPageSize();
  if (startOfPage > list.size()) {
      return new PageImpl<>(new ArrayList<>(), pageable, 0);
  }

  int endOfPage = startOfPage + pageable.getPageSize();
  endOfPage = (endOfPage > list.size()) ? list.size() : endOfPage;
  return new PageImpl<>(list.subList(startOfPage, endOfPage), pageable, list.size());
}
```

##### **Related issues or PR**

No

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Shouldn't we move this class to jhipster-framework ? Less generated code...

**Comment by Gigaxel** [comment]
> Shouldn't we move this class to jhipster-framework ? Less generated code...

I've forgot about the jhipster-framework. If you agree, then I will do it.

**Comment by Gigaxel** [comment]
@jdubois What would be the appropriate class or interface name for the file where this method would be located, since there is no PaginationUtil class or interface on the jhipster-framework repo?

**Comment by PierreBesson** [comment]
Basically the PaginationUtils class should be moved to JHipster framework and removed from the generated code.

**Comment by jdubois** [comment]
Yes it should go to the framework, it implements an RFC so there's little need to customize it.
I recently went to a French bank and in their internal GitHub they had 100+ copies of it...
