### ISSUE TITLE
Faster home page loading. 

### ISSUE THREAD

**Issue by Entrecampos** [jhipster/generator-jhipster#9219]
To access the same database in the same server with php is like 0 seconds to appear the home page and with Jhipster is 12 seconds.

You can check here php https://nms.blaucomm.co.uk -0 seconds
jHipster http://35.230.141.174:8080/nms/#/ - 12 seconds without no indication
(In chrome shows the loading icon, but in safari nothing)

Beter experience User Interface, 
Maybe with Lazy Loading?

**Comment by gmarziou** [comment]
First page loading can be faster for sure but you are comparing a simple static HTML page without any JS code with a Single Page  Application, it's like comparing apples with oranges.

Also your JHipster app has issues:

- many errors trying to load from localhost !
- your build is not optimized for production, your index.html refers to non minified bundles, make sure you deploy a prod build.

**Comment by atomfrede** [comment]
@Entrecampos :warning: Please change the default passwords too! Not sure if that is real data...

**Comment by deepu105** [comment]
Some of the data looks real, please change default passowrds or delete
those data

Thanks & Regards,
Deepu

**Comment by Entrecampos** [comment]
No they are not real data, so I din't change yet the default pwd, so you can test it better. Do you think if optimise my build for production would be faster?

**Comment by atomfrede** [comment]
The optimised production build is much much smaller. Now the bundle is 17(!) MB. And in the latest version we should have lazy loading for entities. If you are brave enough try the vue.js blueprint currently in beta.

**Comment by Entrecampos** [comment]
Thanks @atomfrede.
Until now I was just trying Jhipster for (generating the database and use the crud API, and some extra that I build) to implement an Ionic 3/Jhipster that is already installed in my android. And other person was doing the portal in php. Now there is an idea of doing only in jhipster the Portal. but when I saw so slow ... I was not sure if it was a good option. I am brave :-) What do you mean by trying vue.js ?

**Comment by sahbi-ktifa** [comment]
This is the one. Just follow up the guidelines there and you should have much better performances even using dev mode.

**Comment by Entrecampos** [comment]
Thanks a lot @sahbi-ktifa & @atomfrede. Vue seems great!

**Comment by gmarziou** [comment]
@Entrecampos if you're building an API backend in JHipster for an Ionic mobile app then the time to load the web app is not relevant at all because it will call /api and will not download the frontend part (HTML/CSS/JS)

**Comment by Entrecampos** [comment]
Thanks @gmarziou. Yes until now was not important. But now maybe they want me also to build the portal instead of php that other person was developing. And I am deciding between vue or Ionic PWA. Any suggestions?

**Comment by gmarziou** [comment]
As others said, prod build will be much faster whatever framework you use (Angular, React or Vue) and don't forget also that the browser caches everything on first load.

**Comment by gmarziou** [comment]
It depends on whether you want to keep the UI generated by JHipster or not, it could work for an administration portal and you could build an end user web app or mobile app from scratch just using the API exposed by JHipster.

**Comment by gmarziou** [comment]
As a side note, I saw "If the mail server is not yet instaled, you can see the link to change password in /opt/tomcat/logs/catalina.out", any reason why you deploy in Tomcat? This is so much harder than using the executable war/jar, stackoverflow is full of questions from users who use Tomcat for JHipster apps :)

**Comment by Entrecampos** [comment]
Great tip @gmarziou !!!
It has been a hard experience with tomcat.
I was trying also http://35.230.141.174:8070. (no Real Data on it !)
And I also have configure TLS.
I installed Nginx. And try to figure out how to do it.
All suggestions in this area are very welcome, because don't know much of this stuff :-)

**Comment by Entrecampos** [comment]
The client likes the UI generated by JHipster, that why they were thinking replacing the php

**Comment by gmarziou** [comment]
Well get rid of Tomcat and use a prod build as an executable war.

**Comment by Entrecampos** [comment]
Yes!!! Not Tomcat & Prod mode ! Quite good the speed :-) thanks @gmarziou !

**Comment by gmarziou** [comment]
Great! Did you decide also about which frontend framework?

**Comment by Entrecampos** [comment]
Like now is faster and the client still wants lot of changes I will stay for now with 'out of the box' jHipster/ angular :-)

But If I had to choose I would go for Ionic.
And works very well JHipster entity generator for ionic :-)
[https://github.com/oktadeveloper/ionic-jhipster-starter](https://github.com/oktadeveloper/ionic-jhipster-starter)
