### ISSUE TITLE
Unable to access API from other clients or Postman for the monolith app using Keycloack

### ISSUE THREAD

**Issue by jaydeep-punjani** [jhipster/generator-jhipster#9221]
##### **Overview of the issue**
Unable to access API from other clients or Postman for the monolith app using Keycloack
{
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "title": "Unauthorized",
    "status": 401,
    "detail": "Full authentication is required to access this resource",
    "path": "/api/movies",
    "message": "error.http.401"
}

##### **Motivation for or Use Case**

Accessing the API from a mobile app for a monolith generated using JHipster and using Keycloack for Security

##### **Reproduce the error**

1. Generate a monolith App using JHipster Generator and Select OAuth using Keycloak for security
2. Create some entities using JDL Import
3. Configure Keycloak with Postman callback URL for web_app in jhipster relm
4. Generate a Token from Postman
5. Access API of any entity

##### **Related issues**
NA

##### **Suggest a Fix**
NA

##### **JHipster Version(s)**
v5.8.1

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
samplewebapp@0.0.0 D:\git\samplewebapp
`-- generator-jhipster@5.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.harman.samplewebapp"
        },
        "jhipsterVersion": "5.8.1",
        "applicationType": "monolith",
        "baseName": "samplewebapp",
        "packageName": "com.harman.samplewebapp",
        "packageFolder": "com/harman/samplewebapp",
        "serverPort": "8080",
        "authenticationType": "oauth2",
        "cacheProvider": "no",
        "websocket": "spring-websocket",
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "clientFramework": "angularX",
        "useSass": false,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": false
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Movie {
  movieName String required,
  movieGenere Genere required,
  movieImage AnyBlob required,
  imdbURL String
}
entity Location {
  latitude BigDecimal required,
  longitude BigDecimal required
}
entity Theatre {
  theatreName String required
}
entity MovieShow {
  showTime ZonedDateTime required,
  totalCapacity Integer required,
  ticketPrice BigDecimal required
}
entity Booking

enum Genere {
  ACTION,
  ADVENTURE,
  COMEDY,
  DRAMA,
  HORROR,
  SCI_FI
}

relationship OneToOne {
  Theatre{theatreLocation required} to Location
}
relationship ManyToOne {
  MovieShow{movie required} to Movie,
  MovieShow{theatre required} to Theatre,
  Booking{show required} to MovieShow,
  Booking{booker required} to User
}

paginate Movie, Theatre, MovieShow, Booking with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.20.1.windows.1

node: v11.9.0

npm: 6.5.0

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
As per above.

##### **Browsers and Operating System**
Windows 10 Enterprise

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
When accessing the API using OAuth2 (Keycloak/Okta), by default you have to use cookies. Also when using cookies, XSRF protection is enabled.  This means you have to send an XSRF-Token with each PUT/POST request (extracted from cookie, added to header).

If you prefer to use an `Authorization` token header with OAuth2, you can enable that by adding a [ResourceServerConfiguration](https://github.com/oktadeveloper/generator-jhipster-ionic/blob/1337c12c0b75c3f8e8b486d34774dd5f815e8313/generators/app/templates/src/main/java/package/config/ResourceServerConfiguration.java).  This is used in the [JHipster Ionic](https://github.com/oktadeveloper/generator-jhipster-ionic) and [React Native](https://github.com/ruddell/ignite-jhipster) clients.

**Comment by jaydeep-punjani** [comment]
> When accessing the API using OAuth2 (Keycloak/Okta), by default you have to use cookies. Also when using cookies, XSRF protection is enabled. This means you have to send an XSRF-Token with each PUT/POST request (extracted from cookie, added to header).
> 
> If you prefer to use an `Authorization` token header with OAuth2, you can enable that by adding a [ResourceServerConfiguration](https://github.com/oktadeveloper/generator-jhipster-ionic/blob/1337c12c0b75c3f8e8b486d34774dd5f815e8313/generators/app/templates/src/main/java/package/config/ResourceServerConfiguration.java). This is used in the [JHipster Ionic](https://github.com/oktadeveloper/generator-jhipster-ionic) and [React Native](https://github.com/ruddell/ignite-jhipster) clients.

Thanks @ruddell that worked. Cheers!

**Comment by gabsone** [comment]
How to implement this in v7?

**Comment by mraible** [comment]
@gabsone You don't need to. JHipster's monolith and gateway apps are OAuth 2.0 resource servers by default!

https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs#L285

**Comment by gabsone** [comment]
Thanks for quick reply, but I'm passing a token generated from login process by keyclock and passed to gateway through the authorization header... And non working. The response code is always 401.

**Comment by mraible** [comment]
It's best not to comment on a closed issue. Can you please create a new one with the steps to reproduce the problem?

**Comment by Tcharl** [comment]
Reproduced:

- Use any monolithic oauth2 app
- Add postman redirect uri in keycloack (I'll add it in the conf in my next PR)
Use this postman configuration:
<img width="517" alt="Capture d’écran 2022-03-02 à 19 51 27" src="https://user-images.githubusercontent.com/792925/156428669-1792a3b1-ebcc-4f1c-b583-a89cf53fb5f6.png">
<img width="1260" alt="Capture d’écran 2022-03-02 à 19 52 37" src="https://user-images.githubusercontent.com/792925/156428784-54a33b84-1a1a-48ed-9777-91e15d47aeb0.png">

Which should work, but doesn't...

Any idea ? A TIPS to write on the documentation?

**Comment by DanielFran** [comment]
@mraible Do you know if this issue remains or if this can be closed?

**Comment by mraible** [comment]
@DanielFran It looks like it's still an issue. I didn't try with Keycloak, but I did with Auth0. Steps:

1. Create a new app with `jhipster jdl blog-oauth2`. Fix JDL for v8.
2. Register a new OIDC app on Auth0 and copy settings to `.auth0.env`. Run `source .auth0.env` to set the environment variables. 
3. Start the app with `./mvnw`
4. Create a new access token using the Auth0 CLI and my audience: `auth0 test token -a https://dev-06bzs1cu.us.auth0.com/api/v2/`.
5. Try to access the app using HTTPie: `http :8080/api/account Authorization:"Bearer $TOKEN"`

Error is:

```
WWW-Authenticate: Bearer error="invalid_token", error_description="Invalid token", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
```

I tried turning up the logging in `application-dev.yml` by adding `org.springframework.security: TRACE`. 

This shows that there's a problem communicating with the `/userinfo` endpoint. 

```
2023-06-20T14:46:12.688+02:00 DEBUG 54876 --- [  XNIO-1 task-5] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@5489fa676 pairs: {GET /userinfo HTTP/1.1: null}{Accept: application/json, application/*+json}{Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkRGbzcxemxOdV9vLTkxOFJIN0lIVyJ9.eyJodHRwczovL3d3dy5qaGlwc3Rlci50ZWNoL3JvbGVzIjpbIkV2ZXJ5b25lIiwiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJpc3MiOiJodHRwczovL2Rldi0wNmJ6czFjdS51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjFiY2JjNzZmNjRkNGEwMDcyYWY4YTFkIiwiYXVkIjoiaHR0cHM6Ly9kZXYtMDZienMxY3UudXMuYXV0aDAuY29tL2FwaS92Mi8iLCJpYXQiOjE2ODcyNjQ4MDYsImV4cCI6MTY4NzM1MTIwNiwiYXpwIjoieDJEUVJvaUtmYXB3QnVOSFU2WkVuc1JRRTFVMFhLZ1oifQ.bF251IgFelH93myy0-3g0V5_w_guoN6Y0Iu4kozDM7qhBItNXu2Pva_C4j4q_FaHKoPpBjKoVmfn0olas_E2WoxfKx5R5h8MwpXLcFnvn1EvpF0bBOVP52mYKh2ovzrP22ONaHTCfToyoAkTEZDx_Oj3xasrKFR2kZ8FZRsVbsVlmt9OWbEz4ZZclZmcsLqO6DT0B8a8IBmEGn4UEHewoWfPF2A6xZo-Lm451b2YkrMuHwMG-eOdKVZmJ6d5Q93Lzz8rsTu9WHErvXqq8bdaRvZr_X2j3Br9qIlLtmQQSkCwFUgfcR0iq0B-6FdzCp9Ron089IHJwh8VKOYpxi2jRA}{User-Agent: Java/19.0.2}{Host: dev-06bzs1cu.us.auth0.com}{Connection: keep-alive}
2023-06-20T14:46:12.905+02:00 DEBUG 54876 --- [  XNIO-1 task-5] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@1fb5629c29 pairs: {null: HTTP/1.1 401 Unauthorized}{Date: Tue, 20 Jun 2023 12:46:12 GMT}{Content-Type: application/json; charset=utf-8}{Content-Length: 66}{Connection: keep-alive}{CF-Ray: 7da41d016912363c-FRA}{CF-Cache-Status: DYNAMIC}{Access-Control-Allow-Origin: *}{Cache-Control: private, no-store, no-cache, must-revalidate, post-check=0, pre-check=0, no-transform}{ETag: W/"42-lCMfZcFsM/a2s4oTDhYyRwsfR18"}{Set-Cookie: did=s%3Av0%3A703040d0-0f68-11ee-9b1b-4b61edfea71d.dfPhV%2BjhZeHlaerasqs0XO0oVVWvi71ObaFoLZ40Rr0; Max-Age=31557600; Path=/; Expires=Wed, 19 Jun 2024 18:46:12 GMT; HttpOnly; Secure; SameSite=None}{Strict-Transport-Security: max-age=31536000}{Vary: Origin}{Access-Control-Allow-Credentials: false}{Access-Control-Expose-Headers: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset}{ot-baggage-auth0-request-id: 7da41d016912363c}{ot-tracer-sampled: true}{ot-tracer-spanid: 7517abdc483eab4b}{ot-tracer-traceid: 02413ee06618fa57}{Set-Cookie: did_compat=s%3Av0%3A703040d0-0f68-11ee-9b1b-4b61edfea71d.dfPhV%2BjhZeHlaerasqs0XO0oVVWvi71ObaFoLZ40Rr0; Max-Age=31557600; Path=/; Expires=Wed, 19 Jun 2024 18:46:12 GMT; HttpOnly; Secure}{traceparent: 00-000000000000000002413ee06618fa57-7517abdc483eab4b-01}{tracestate: auth0-request-id=7da41d016912363c,auth0=true}{X-Auth0-RequestId: c485c08507e615f226ef}{X-Content-Type-Options: nosniff}{X-RateLimit-Limit: 300}{X-RateLimit-Remaining: 299}{X-RateLimit-Reset: 1687265174}{Server: cloudflare}{alt-svc: h3=":443"; ma=86400}
2023-06-20T14:46:12.908+02:00 TRACE 54876 --- [  XNIO-1 task-5] o.s.s.oauth2.jwt.NimbusJwtDecoder        : Failed to process JWT

org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: "{"error":"unauthorized","error_description":"invalid credentials"}"
```

I checked, and the JWT value is the same between the HTTPie command and the console log.

**Comment by mraible** [comment]
I'm able to hit the `/userinfo` endpoint directly if I use a different audience for my access token.

```
auth0 test token -a https://dev-06bzs1cu.us.auth0.com/userinfo
TOKEN=...
http https://dev-06bzs1cu.us.auth0.com/userinfo Authorization:"Bearer $TOKEN"
```

However, this access token won't work for access the JHipster API:

```
WWW-Authenticate: Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: 
Encrypted JWT rejected: No JWE key selector is configured", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
```
