### ISSUE TITLE
Handling 'scope' in blueprint names

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#9223]
##### **Overview of the issue**
Hello !
You probably know that Jhipster blueprints have a normalized name: generator-jhipster-*
For some reason we sometimes need to add a scope to our packages and named them like this `@hipsterCompany/generator-jhipster-myRedPrint`.

It actually not possible because the blueprint name is normalized by JHipster.
The pros is that when you're generating a new project with blueprint the command is simplified:
`jhipster --blueprint myRedPrint`

If I test by adding a scope the result is not really the result expected : 
`jhipster --blueprint @hipsterCompany/myRedPrint` -> `generator-jhipster-@hipsterCompany/myRedPrint`  

¯\\_(ツ)_/¯

##### **Motivation for or Use Case**
Using [scope](https://docs.npmjs.com/misc/scope) in NPM package.

##### **Suggest a Fix**
generator-base-private.js l. 721
```
    normalizeBlueprintName(blueprint) {
        if(blueprint.startsWith('@')) {
            return blueprint;
        }
        if (blueprint && !blueprint.startsWith('generator-jhipster')) {
            return `generator-jhipster-${blueprint}`;
        }
        return blueprint;
    }
```

I added a dumb condition to skip normalize if start with `@`but I'm sure we can do something better.
For now I prefer to discuss about it with you and to know what do you think about it.

##### **JHipster Version(s)**
5.8.1

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Actually, as long as we are using Yeoman underneath we would have to stick to yeoman naming which doesn't support this as well AFAIK

**Comment by avdev4j** [comment]
After a little research I found this : 
[https://github.com/yeoman/generator-node/issues/272](https://github.com/yeoman/generator-node/issues/272)

It seems to be managed since the [v2.4.0](https://github.com/yeoman/generator-node/releases/tag/v2.4.0)

Unfortunately we are on 2.0.5 version

**Comment by arjunnayak** [comment]
We're running into the same issue with our company blueprint, and scoped packages are necessary when you want to use a private company npm registry + the public registry. Any chance we can upgrade yeoman to support this, as @avdev4j recommended?

**Comment by ruddell** [comment]
Yeoman has supported scoped generators [since this commit](https://github.com/yeoman/environment/commit/7342d0a5844ae1bd4d36338e847c4fd6dd8f90fd) a few years ago.

I tested with @avdev4j's change and the app successfully composed a scoped blueprint and generated the expected files.  The only difference is that you must pass the full package name:
```
jhipster --blueprint @jhipster/generator-jhipster-scoped-blueprint
```
