### ISSUE TITLE
Renaming of the default profiles

### ISSUE THREAD

**Issue by Brzhk** [jhipster/generator-jhipster#9249]
##### **Overview of the feature request**

I would really enjoy if the profiles could be renamed. For instance, the dev profile could be named "local". 
As of prod, i have not yet found a name that gets an unanimous approval here, but  i guess i could make a few suggestions soon.

##### **Motivation for or Use Case**

Very simply put, prod and dev are usual names of the environments you share with other developers, and if you are lucky, theses environments are iso. Therefore, the difference between theses dev and prod env are pretty much where you connect to a DB and with which credentials. 

And explaining this to developers new to JHipster is pretty difficult. 

##### **Related issues or PR**
N/A
-   [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
This is not inline with our policy 2 https://www.jhipster.tech/policies/
You can easily edit teh generated code to call the profiles as you see fit

**Comment by Brzhk** [comment]
I did not say this as an option. I suggested an hardcoded renaming. Therefore policy 2 does not apply.

**Comment by deepu105** [comment]
AFAIK `dev`, `test`, `sit`, `uat`, `prod` are the most commonly used profile names. If you can provide any stats to show otherwise we could consider otherwise I dont think we will change it

**Comment by PierreBesson** [comment]
>prod and dev are usual names of the environments you share with other developers

I personally disagree with this naming. What you are calling the "shared dev environment" is actually a staging environment. Indeed "dev" stands for development and we encourage people to do this activity locally on their development machines.

**Comment by Brzhk** [comment]
I personally agree to this too, but cant argue when someone tell me 'well,
local is local wether you call it that way or dev, therefore applies to
whatever naming-policy is in effect in [your] company.

I am not going to push it further as it can be fixed internally here. I was
just thinking it would be a simple suggestion to improve your naming policy
by being the less conflicting in any environment where it is studied for
adoption. (While i am sure there are more critical bugs for you to fix.)

**Comment by pascalgrimaud** [comment]
In JHipster, the profiles `dev` and `prod` mean:
- `dev`: optimized for development
- `prod`: optimized for production
That's all. It is not related at all to environment.

But I agree it can confuse people, when they want to start the application in real environment, like `int`, `uat`, etc. It's hard to satisfy all people, as it depends on how you deploy and customize the properties:
- uploading a specific application-xxx.yml ?
- override configuration using environment variables ?
- etc.
