### ISSUE TITLE
UML Class Diagram for JHipster

### ISSUE THREAD

**Issue by VikasJindal84** [jhipster/generator-jhipster#925]
Hi,

Currently , we are using command line to create entities in JHipster e.g.

yo jhipster:entity author

I want to contribute to your project by integrating it with Class diagram . User can create create a class diagram from that plugin ,then that plugin will invoke some JHipster's APIs to create entities corresponding to it .

I have some questions , can you please help me with these :

* How should that plugin invoke JHipster for creation of entities . One possibility is to generate a script of yo jhipster:entity author,yo jhipster:entity filed name String. 

Please share your suggestions on it .

Thanks

**Comment by gzsombor** [comment]
What kind of Class Diagram plugin do you use ? Is it an eclipse plugin ? Which one? 

JHipster has the ability to load json files, which describes the individual entities (when you generate a new entity, JHipster automatically saves in these format, so later, you can regenerate it). So your plugin could output a couple of json files, and execute the entity generator.

**Comment by devedipoint** [comment]
As @gzsombor said, "JHipster has the ability to load json files..." and with my proposed enhancement with extending entities it has also greatest ability with inheritance used in UML. Let's look at #919 - it's not merged with jhipster:master yet.

**Comment by gzsombor** [comment]
I think, there is one, bigger missing piece from jhipster, is to have multiple, named relations between entities. For example, currently if you have 'Project' and 'People' entities, you couldn't declare that Project have a 'leader', 'developers', 'testers', 'client' which all 'People', only that there is a 'persons' relation.

**Comment by VikasJindal84** [comment]
I have 2 options :

1) Create a new java-script plugin like https://www.npmjs.com/package/uml.js
,that will generate json file..
2) Use eclipse uml-designer

Please share your suggestions on above options .

**Comment by VikasJindal84** [comment]
There is one online tool http://cruise.eecs.uottawa.ca/umpleonline/ ,which generates json from Class Diagram , can we use it in JHipser ?

**Comment by MartinLichtblau** [comment]
It sounds really cool, but it won't be so easy. 
First thing which comes to my mind is that the creation order of the database tables is relevant. Which means that you need an algorithm to find out which table and relation you have to create first, second,,, and so on. And of course there will be many more big problems.

If you are looking for a tool with such capabilities you should take a look at [mysql workbench](http://www.mysql.com/products/workbench/design/).

**Comment by jdubois** [comment]
The best thing would be to support XMI (or something newer, if that exist!), so that you don't rely on an UML tool.
You could do a sub-generator (or something like that), in JavaScript, that reads XMI and then executes the JHipster commands.
As @MartinLichtblau says, one of the issues is the order in which tables need to be created, and I have no idea for that!

**Comment by VikasJindal84** [comment]
I think xml idea is good. I will take care of order of tables

**Comment by VikasJindal84** [comment]
Hi, I have seen that ,currently there is option to supply json file ,instead of giving commands :

https://github.com/jhipster/generator-jhipster/blob/master/entity/index.js#L14

but there is no documentation for it . How can i use that json file option instead of commands ?

**Comment by MartinLichtblau** [comment]
Here are some tools you could use to create the diagrams: [PonyOrm](http://ponyorm.com/), [SQL Developer Data Modeler](http://www.oracle.com/technetwork/developer-tools/datamodeler/overview/index.html), [Visual Paradigm](http://www.visual-paradigm.com/features/database-design/#erd). I for my part prefer to use [Lucidchart](https://www.lucidchart.com) for all kind of diagrams.

**Comment by VikasJindal84** [comment]
Now in jhipster , we can specify json file as input (available in mater branch )

.jhipster.Employee.json

{
    "relationships": [],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String",
            "fieldNameCapitalized": "Name",
            "fieldNameUnderscored": "name"
        },
        {
            "fieldId": 2,
            "fieldName": "age",
            "fieldType": "Integer",
            "fieldNameCapitalized": "Age",
            "fieldNameUnderscored": "age"
        },
        {
            "fieldId": 3,
            "fieldName": "joiningDate",
            "fieldType": "DateTime",
            "fieldNameCapitalized": "JoiningDate",
            "fieldNameUnderscored": "joining_date"
        }
    ],
    "fieldsContainOwnerManyToMany": false,
    "fieldsContainOneToMany": false,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": true,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": true,
    "changelogDate": "20150104201232"
} 


I can write script that can convert xml to json . I can try xml like this 

<root>
	<Entity name='Employee'>
		<Field name='name' type='String'/>
		<Field name='age' type='Integer'/>
		<Field name='joiningDate' type='DateTime'/>
	</Entity>
</root>

**Comment by leonardoavs** [comment]
As @gzsombor said, I think, there is one, bigger missing piece from jhipster, is to have multiple, named relations between entities. For example, currently if you have 'Project' and 'People' entities, you couldn't declare that Project have a 'leader', 'developers', 'testers', 'client' which all 'People', only that there is a 'persons' relation.

I think that this feature is very common, and it can be nice if it can be implemented in for a future release.

**Comment by jdubois** [comment]
I just merged the "multiple named relationships" from @gzsombor so this is one more step towards having the UML tooling ready.

**Comment by barais** [comment]
Hi, I just release a small entity json generator from genmymodel uml editor. 
https://github.com/barais/genmymodeljhipstergenerator
If it can be  useful to someone.
Regards
Olivier

**Comment by jdubois** [comment]
@barais looks like a great solution!!!

**Comment by barais** [comment]
I will try to write some docs ;).
Currently it generates a json entitty and a shell script to call the different commands
> yo jhipster:entity ...

**Comment by gabriel-a** [comment]
@barais Can you please explain how to use it? It seems a very good solution to work with.

**Comment by jdubois** [comment]
I have a new trainee at work (thanks @ippontech ) and he's going to work on the UML support at https://github.com/jhipster/jhipster-uml

Welcome @Mathieuaa !!

**Comment by jdubois** [comment]
I'm closing this as work will happen on https://github.com/jhipster/jhipster-uml
