### ISSUE TITLE
The same backend stack but different frontent options

### ISSUE THREAD

**Issue by mrzepinski** [jhipster/generator-jhipster#926]
Is there any chance to implement different frontent options for this architecture?
I would like to have an options to chose AngularJS or Metor or React + Flux for my frontent.
Any suggestions? Backend architecture is nice and simple and it could be reuseable.

DW: @jdubois @jmirc

**Comment by jmirc** [comment]
It could be great to support multiple front-end technology but I don't think this is feasible.
It is a lot of work to maintain multiple stacks and we are not front-end expert. 
We already have the same support problem for the back-end stacks; for example grunt (we support)/glup (community support), maven (we support)/graddle (community support).

However, we could create a new project for each front-end implementation. The main issue is how the sub-generators could support multiple front-end implementation.

**Comment by jdubois** [comment]
Yes it would be great but it's just not possible.

- We have some very specific code for AngularJS, concerning security, i18n, etc...
- We just can't support everything. And we choose to focus on AngularJS from the start, which I still find an excellent decision, so we won't change that
