### ISSUE TITLE
Forbidden: Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'

### ISSUE THREAD

**Issue by jaydeep-punjani** [jhipster/generator-jhipster#9268]
##### **Overview of the issue**
Getting Forbidden: Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN' on POST when using OAuth 2.0 with Okta.
Note : I'm using this with Google Actions dialogFlowWebook, which does a POST request to one of my endpoints on /api/dialogFlowWebook

##### **Motivation for or Use Case**
To be able to do POST actions on /api/** and use JHipster App as a Webhook Fulfillment from Google Actions.

##### **Reproduce the error**
1. Create a JHipster Monolith App.
2. Configure Okta
3. Deploy to Heroku
4. Create a Sample Google Action and create a webhook endpoint in the JHipster App
5. Initiate the Intent from GA

##### **Related issues**
https://github.com/jhipster/generator-jhipster/issues/9221
I have create the ResourceServerConfiguration as suggested and http.csrf().disable() is set, still getting this error.

##### **Suggest a Fix**
NA

##### **JHipster Version(s)**
v5.8.1

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
movieapp@0.0.0 D:\git\movieapp
`-- generator-jhipster@5.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.harman.movieapp"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "monolith",
    "baseName": "movieapp",
    "packageName": "com.harman.movieapp",
    "packageFolder": "com/harman/movieapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "herokuAppName": "injpunjani-movieapp",
    "herokuDeployType": "jar"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Movie {
  movieName String required,
  movieGenere Genere required,
  movieImage AnyBlob required,
  imdbURL String
}
entity Theatre {
  theatreName String required,
  latitude BigDecimal required,
  longitude BigDecimal required
}
entity MovieShow {
  showTime ZonedDateTime required,
  totalCapacity Integer required,
  ticketPrice BigDecimal required
}
entity Booking

enum Genere {
  Action,
  Adventure,
  Comedy,
  Drama,
  Horror,
  Sci_Fi
}

relationship ManyToOne {
  MovieShow{movie(movieName) required} to Movie,
  MovieShow{theatre(theatreName) required} to Theatre,
  Booking{show required} to MovieShow,
  Booking{booker(login) required} to User
}

paginate Movie, Theatre, MovieShow, Booking with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.20.1.windows.1

node: v11.9.0

npm: 6.5.0

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**
Windows 10 Enterprise

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
@jaydeep-punjani You can modify your security configuration to disable CSRF for Google's requests.  The config linked in your other issue checks for the Authorization header, I'm guessing you can either check for a Google-specific header or disable CSRF on your custom Google webhook endpoint.

As this isn't a bug or issue with JHipster, I'm closing this.  Please use StackOverflow or Gitter in the future if it isn't a bug in the generated code.

**Comment by jaydeep-punjani** [comment]
Thanks @ruddel, ignoringAntMatcher on the csrf, for Google API did the trick.

**Comment by geyuqiu** [comment]
@ruddell csrf-service.ts is created for Angular + jwt + monolith. But it is never used in code. Do you know more background information?

**Comment by ruddell** [comment]
@geyuqiu CSRF is enabled for Session, Oauth2, and UAA auth types, but not for JWT.  You could [change the code here](https://github.com/jhipster/generator-jhipster/blob/45dbcb4146cd3573c7e372f9eda57c4c06457ad5/generators/client/files-angular.js#L395) so it isn't added for JWT apps.
