### ISSUE TITLE
gulp/grunt server:dist is currently broken

### ISSUE THREAD

**Issue by amr** [jhipster/generator-jhipster#927]
Currently in master branch, `gulp server:dist` and `grunt server:dist` are broken.

Errors while accessing the homepage from a `grunt server:dist`:

![errors from grunt server:dist](https://cloud.githubusercontent.com/assets/35434/5595747/010abe98-9284-11e4-91cc-ee953e12c365.png)

And from a `gulp server:dist`:

![errors from gulp server:dist](https://cloud.githubusercontent.com/assets/35434/5595752/1eececce-9284-11e4-90ad-a61f20609b63.png)

I found this while I was testing a PR I'm working on for fixing live-reload in gulp, initially I thought it's something in my PR but then I realized it's an existing issue. I will probably work on this after I finish the gulp live-reload PR but I wanted to report it in case I don't get the chance.

Btw, it would be nice if someone could briefly describe what is the purpose of the `server:dist` task in our grunt/gulp build, personally I'm not really sure what is the value this is supposed to provide.

**Comment by jdubois** [comment]
1. I am not using Gulp.js, it was provided by the community and in fact I was thinking of removing it for our v2.0 version -> would you be interested in maintaining it "officially" ? Of course I would rather have Gulp.js work, but I don't have the time to support everything.
So if Gulp.js fails I am not too surprised.

2. I have no idea what the "server:dist" task is supposed to do! With Grunt, I just use "grunt server" for the livereload. What makes you think this task should do something?

**Comment by amr** [comment]
1. Yes, can do
2. Because it's defined in both Grunt and Gulp as a task and no other task depends on it, so it's meant to be executed externally. I think it initially existed in Grunt, and then whoever did the initial grunt -> gulp port carried it forward to Gulp

I believe the idea with `server:dist` is to serve the front-end assets that actually go to production (technically the result of the `build` task). This is different from `server` in that the latter serves the development versions.

**Comment by jmirc** [comment]
I think to be able to work with server:dist option, we should start the server with the production profile.

I never tried too

**Comment by jmirc** [comment]
If nobody used this option, we should remove it

**Comment by jdubois** [comment]
@amr 
1. I'll add you to the team, welcome on board!
2. Do you see any use for it? Can we remove it?

**Comment by amr** [comment]
Awesome, thanks!

I agree on removing it. We can always add it again later if needed, but at least then we would know the use case(s)

**Comment by jdubois** [comment]
@amr  I just added the "gulp.js" label so you can check the Gulp issues easily:
https://github.com/jhipster/generator-jhipster/labels/gulp.js

**Comment by amr** [comment]
That's pretty handy, thank you

**Comment by jdubois** [comment]
I suck at Grunt and can't make it work anyway... @amr did you suppress it from the gulp.js build? Can you have a look at the Grunt build too?

**Comment by amr** [comment]
I didn't do anything about it yet, was planning on removing it actually. If you think there is value in retaining it, I can try to fix it for both gulp and grunt.

**Comment by jdubois** [comment]
@amr no, please remove it (can you do it on both grunt and gulp.js?) -> it doesn't work and nobody uses it anyway

**Comment by amr** [comment]
PR Submitted
