### ISSUE TITLE
Feature request: support for SAP HANA

### ISSUE THREAD

**Issue by breglerj** [jhipster/generator-jhipster#9272]
* **Overview of the request**

I'd like to enhance JHipster to support SAP HANA as a database type when creating an application.

* **Motivation for or Use Case** 

Recently I've been adding support for SAP HANA to several open source projects like Hibernate, Spring, Liquibase, and others, and I'd like JHipster to support SAP HANA as a database as well.

* **Browsers and Operating System** 

n/a

* **Related issues** 

n/a

* **Suggest a Fix** 

If you accept the feature request, I can contribute the support for SAP HANA.

**Comment by jdubois** [comment]
The issue with something like SAP Hana is that we usually need about 1,000 users to get 1 contributor to the project, so I already know that:

- We won't have enough contributors to maintain the integration
- We won't have the licenses or hardware to test it and maintain it ourselves

It's sad, I have several customers who spend millions on SAP, including SAP Hana (I saw the invoices!!), but they aren't ready to help the project by doing some contribution or sponsoring, so in the end this won't work out for them.

The only way this could work is through a module (maybe a blueprint).

**Comment by breglerj** [comment]
@jdubois Thanks for the info. I'll look into creating a module or blueprint for now.

BTW, [SAP HANA express edition](https://developers.sap.com/topics/sap-hana-express.html) is a free version of SAP HANA available on-premise or in the cloud that you can use for development and testing purposes, so licensing and hardware shouldn't even be too much of an issue. I can see your point about the number of contributors, though.

**Comment by jdubois** [comment]
Thanks @breglerj - for the number of contributors it's of course not a criticism, in fact I'm very sad to see how few people and (most importantly) companies are interested to contribute to OSS projects. I don't get how it's possible that companies spend millions of $ on SAP Hana and won't be interested in supporting SAP Hana on JHipster, but that's the way it is.
