### ISSUE TITLE
Failing CI Azure build for react

### ISSUE THREAD

**Issue by pvliss** [jhipster/generator-jhipster#9282]
##### **Overview of the issue**
The `react-noi18n-es-ws-gradle-session` sample is failing at Azure Pipelines

So I spent a few hours today to find the cause of this problem as I feel uncomfortable submitting PRs and see builds failing :)

The problem seems to be caused by commit bda31032 (Migrate PaginationUtil and HeaderUtil to jhipster/jhipster-framework ). Reverting it seems to pass the CI again. The root cause I think is that the change does not take into account the disabled translation feature, hence its the only sample that fails.

You can see that the build is succesfull [here](https://dev.azure.com/pvlissidis/pvlissidis/_build/results?buildId=129) for the [fix-ci-branch](https://github.com/pvliss/generator-jhipster/tree/fix-ci-build)  at my fork where I have done the revert.

I do not want to submit a PR as this should be probably fixed instead of completely reverted.

##### **Motivation for or Use Case**
Fix the CI build

##### **Suggest a Fix**
Other than reverting the whole commit I think the following fixes should help:

1. The default application name of `HeaderUtils` was replaced by `<%= angularAppName %>` while the replacement `${spring.application.name:JHIPSTER}` is replaced by `<%= baseName %>`
2. The new [HeaderUtil](https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/web/util/HeaderUtil.java) class ignores case where translation is disabled.

##### **JHipster Version(s)**
Current master(6.x)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I'll have a look.
If your 2 fix are OK, I'll merge them. 
Thanks a lot !

**Comment by pvliss** [comment]
Thanks @pascalgrimaud .

I believe it will work but I would like to note that I am not sure/convinced that this is the best way to go. The reason is that I have added an extra config property `jhipster.clientApp.name` in `application.yml` which might give the false impression to end users that changing it will make things work while this is not the case as the value will be hard-coded at the client code.

**Comment by pascalgrimaud** [comment]
It works locally for me, so just merged the 2 PRs.
I saw an extra config property, agree with you, maybe it's not the best way to go, but at least, it will fix the CI, and not block other PRs.

**Comment by pvliss** [comment]
Thanks @pascalgrimaud
