### ISSUE TITLE
Helper to override specific files using blueprint

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#9284]
##### **Overview of the feature request**

The purpose of this changes is to make it easier for developers not very familiar with the source code to override templates without changing any other file.

This could be implemented by overriding the function `fetchFromInstalledJHipster`
in all subgenarors ex: `module.exports = class extends EntityClientGenerator {` and make it fetch locally in the blueprint and falling back to the default implementation if the files is not present the blueprint.
##### **Motivation for or Use Case**

This will reducing the bootsraping time trying to figure out how existing code works and how to make go through our own.
##### **Related issues or PR**
May people in Stackoverflow are asking how to this.

-   [X] Checking this box is mandatory (this is just to show you read everything)

EDIT: After checking the code a bit more I found out that, `fetchFromInstalledJHipster` would override the base path for all files, therefore, to be able to implemnt the feature code in `writeFilesToDisk` would need to change to check for files in the blueprint before using the default value.
I will follow the advice of @avdev4j and do the replacements manually for now.

Another approach to have this is to code something in the module that uses all angular files, check for replacements and keep only files present in blueprint to replace them.

**Comment by avdev4j** [comment]
I'm sure we can improve the developer experience when using blueprint but not sure the template overriding is not an issue.

You easily can call the JHipster writing step and then calling your own step which contains your own files. You can override or adding new files.

I think there is an exemple when you creating a client blueprint.

You can check this [repo](https://github.com/avdev4j/samSuffit) where I call the JHipster step and override with my own files: 

Index.js
```
    get writing() {
        const phaseFromJHipster = super._writing();
        const phaseFromSam = writeFiles();

        return Object.assign(phaseFromJHipster, phaseFromSam);
    }
```

files.js
```
const serverFiles = {
    serverResource: [
        {
            path: SERVER_MAIN_RES_DIR,
            templates: [{ file: 'banner.txt', method: 'copy', noEjs: true }]
        }
    ]
};

function writeFiles() {
    return {
        writeSamFiles() {
            this.writeFilesToDisk(serverFiles, this, false);
        }
    };
}
```

My banner.txt is loaded in memory and replace the JHipster one. When the generator dump the files, my banner is created.

hope it can help.

regards,

**Comment by deepu105** [comment]
Yes it shouldn't be an issue. You can easily override files or use your own
util methods in the current setup
