### ISSUE TITLE
Update npm packages

### ISSUE THREAD

**Issue by pvliss** [jhipster/generator-jhipster#9285]
##### **Overview of the feature request**

I have lately been dealing with various issues mainly related to ones blocking dev of the Kotlin blueprint and I have noticed that many of the npm dependencies(prod+dev) of both the main generator-jhipster as well as the `package.json` for the generated apps(only checked React not sure about angular) are lacking behind.

Not sure if this on purpose(if so please let me know and close this) or simply no one has the time to deal with that task but I would like to help in bringing these up to date, at least the ones with minor and patch releases, as major upgrades will need more consideration/careful inspection.

Also while inspecting #9282 I noticed that for React there are some [dependencies](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/react/package.json.ejs)() used that have been moved/deprecated in favor of new packages(e.g [react-addons-css-transition-group](https://www.npmjs.com/package/react-addons-css-transition-group) has been replaced by [react-transition-group](https://github.com/reactjs/react-transition-group) ) and should also be fixed accordingly.

I think though that it would be best to update these before the 6.x release rather than later and the more they stay stale the more difficult they are to update.

###### **Update Tasks**

- [x] Check and update npm dependencies of the [main generator](https://github.com/jhipster/generator-jhipster/blob/master/package.json).
**NOTE:** I have done some initial work for that at https://github.com/pvliss/generator-jhipster/commits/update-npm-dependencies
- [x] Check and update npm dependencies of the [generated Angular apps](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/package.json.ejs)
- [ ] Check and update npm dependencies of the [generated React apps](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/react/package.json.ejs)

##### **Motivation for or Use Case**

Get latest features and fixes/patches of used libraries

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pvliss** [comment]
@jhipster-developers As this has not been closed I assume you want me to continue with this? If not then please let me know. Thanks

**Comment by ruddell** [comment]
Please continue if you have time.  @DanielFran recently did some related work:
 - The Angular dependencies were upgraded (two weeks ago) here: https://github.com/jhipster/generator-jhipster/pull/9241
 - There was some work done to React but it required some code changes so it wasn't merged https://github.com/jhipster/generator-jhipster/pull/9243

**Comment by pvliss** [comment]
Thanks @ruddell . Will do so

**Comment by jdubois** [comment]
Yes thanks a lot @pvliss

**Comment by DanielFran** [comment]
@pvliss Closing since all PRs are merged

**Comment by pvliss** [comment]
Yes, thanks @DanielFran
