### ISSUE TITLE
Leverage Confluent Kafka docker images

### ISSUE THREAD

**Issue by framiere** [jhipster/generator-jhipster#9286]
As seen face-to-face today with @jdubois , @Dabz and I propose to leverage our Confluent expertise to provide better Kafka support in JHipster.

### Outdated kafka images

JHipster is relying on old kaka version by `wurstmeister`
https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-constants.js#L35

### Leverage Confluent images

We propose to use the confluent images instead, so they are always up to date.
https://hub.docker.com/r/confluentinc/cp-kafka

### Target

We propose to update both the `docker-compose` and `helm` charts with these images.

### Longer term target

Being able to provide full [KSQL](https://github.com/confluentinc/ksql), [Kafka Connect](https://kafka.apache.org/documentation/#connect) and [Schema Registry](https://github.com/confluentinc/schema-registry) support.

Let us know what you think.

**Comment by jdubois** [comment]
As we all agree, let's do this!

**Comment by pascalgrimaud** [comment]
I suppose we could use confluentinc/cp-zookeeper
https://hub.docker.com/r/confluentinc/cp-zookeeper too ?

**Comment by DanielFran** [comment]
Is this supposed to be done for v6?
Would love  to have this has soon...

**Comment by pascalgrimaud** [comment]
@framiere @Dabz : I supposed you didn't have time to start the work.

So I had a quick look yesterday, and what I already did:
- migrate to official images for kafka and zookeeper
- update configuration for spring boot
- migrate from Spring Cloud Stream to native Apache Kafka client (related to https://github.com/jhipster/generator-jhipster/issues/9287)
- implement a simple rest controller, with 2 services (1 for Producer and 1 for Consumer)

Will you be able to do a review once I propose the PR ?

**Comment by Dabz** [comment]
Sure, I will have a look to https://github.com/jhipster/generator-jhipster/pull/9567 today or tomorrow ;)
