### ISSUE TITLE
Run `npm test` once at CI

### ISSUE THREAD

**Issue by pvliss** [jhipster/generator-jhipster#9290]
##### **Overview of the feature request**

It seems that `npm test` should be executed when building/installing the generator from the master branch. 
More specifically something along the lines of the following script should be added to https://github.com/jhipster/generator-jhipster/blob/b802f7bb08dce8829efd79ece7b7c37c49abf47f/test-integration/scripts/10-install-jhipster.sh#L73:

```bash
    if [[ "$JHI_APP" == "" || "$JHI_APP" == "ngx-default" ]]; then
        npm test
    fi

```

Currently the `npm test` is run as a byproduct of https://github.com/jhipster/generator-jhipster/commit/c7fb5c6108487be127c4e8da4b05625e521bd06c but I believe this should not be the case. Neverthelless, running prettier after every `npm install` or 'npm link' is not very efficient for both local dev and CI build times. As suggested  by @deepu105 a commit hook would be the most appropriate way to avoid that problem and the CI will simply verify everything is in order

##### **Motivation for or Use Case**

Run the mocha tests once at the CI and decrease local + CI build times

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pvliss** [comment]
Hello @DanielFran. I believe the intention of @pascalgrimaud with #9304 was to make the CI build fail as he deliberately introduced some invalid formatting but the CI passed. This means that `npm test` was not executed or more precisely linting was not performed. Hence this issue still stands. I can create a PR if you wish to verify this

**Comment by pascalgrimaud** [comment]
@pvliss :

> he deliberately introduced some invalid formatting but the CI passed

no, in my PR, I fixed existing invalid format. Otherwise, the PR won't pass

> `npm test` was not executed or more precisely linting was not performed

I don't understand what you mean here. As `npm run lint` passed, `npm test` was correctly performed: https://travis-ci.org/jhipster/generator-jhipster/jobs/496245281

Can you be clearer plz ?

**Comment by pvliss** [comment]
Thanks for the clarification @pascalgrimaud.

I was under the impression that the last branch was executed and I was actually referring to that case, the one at 62 https://github.com/jhipster/generator-jhipster/blob/b802f7bb08dce8829efd79ece7b7c37c49abf47f/test-integration/scripts/10-install-jhipster.sh#L62   but I am obviously wrong.  Thanks for pointing out.

In which case will the last branch be executed? Is it for blueprints?

@DanielFran Please ignore my previous comment and sorry for the confusion
