### ISSUE TITLE
Swagger model schema and example empty with jhipster 5.8.1 generator.

### ISSUE THREAD

**Issue by Pranavism** [jhipster/generator-jhipster#9292]
##### **Overview of the issue**
Swagger UI and Json does not contain model details for app generated with 5.8.1 generator

##### **Motivation for or Use Case**

The exact same project generated with previos version works fine and full swagger details are shown.
I tried both upgrading an existing project and creating a new project with 5.8.1 ,in both cases swagger model is empty.
##### **Reproduce the error**
Generate a microservices app with 5.8.1 and navigate to swagger UI with gateway or just the json.

##### **JHipster Version(s)**
5.8.1

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Pranavism** [comment]
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.sb.organization"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "microservice",
    "baseName": "Organization",
    "packageName": "com.sb.organization",
    "packageFolder": "com/sb/organization",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "UAA",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true,
    "messageBroker": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Organization {
  orgNum String required,
  orgName String required,
  facilityFlag Boolean required,
  localeNum String maxlength(40),
  primaryUrl String,
  activeFlag Boolean required
}
entity OrgUser {
  login String maxlength(40) required,
  facilityFlag Boolean required,
  orgNum String required,
  defaultFctlFlag Boolean required,
  primaryOrgFlag Boolean required
}
entity RoleType {
  roleTypeNum String maxlength(40) required,
  roleTypeDescription String maxlength(100) required
}
entity Role {
  roleNum String maxlength(40) required,
  roleDescription String maxlength(100) required,
  isActive Boolean required,
  refRoleType String maxlength(40) required,
  orgNum String required
}
entity UserRole {
  login String maxlength(40) required,
  roleNum String maxlength(40) required,
  isActive Boolean required,
  orgNum String required
}
entity ContactType {
  contactTypeNum String maxlength(40) required,
  contactTypeDescription String maxlength(140)
}
entity AddressType {
  addressTypeNum String maxlength(40) required,
  addressTypeDescription String maxlength(140)
}
entity OrganizationAddress {
  addressLine1 String maxlength(40) required,
  addressLine2 String maxlength(40),
  addressLine3 String maxlength(40),
  addressLine4 String maxlength(40),
  addressLine5 String maxlength(40),
  addressLine6 String maxlength(40),
  city String maxlength(40),
  state String maxlength(40),
  country String maxlength(40) required,
  zip String maxlength(40),
  phoneNumber String maxlength(20),
  email String maxlength(40),
  faxNumber String maxlength(20)
}
entity OrganizationContact {
  firstName String maxlength(20) required,
  lastName String maxlength(20),
  phoneNumber String maxlength(20),
  email String maxlength(40),
  faxNumber String maxlength(20)
}
relationship OneToMany {
  Organization{orgUser} to OrgUser{userOrgNum(orgNum) required},
  Organization{orgRole} to Role{roleOrgNum(orgNum) required},
  Organization{orgAddress} to OrganizationAddress{addressOrgNum(orgNum) required},
  Organization{orgContact} to OrganizationContact{contactOrgNum(orgNum) required}
}
relationship ManyToOne {
  Organization{parentOrganization} to Organization,
  Role{roletype(roleTypeNum) required} to RoleType,
  UserRole{roletype} to RoleType,
  UserRole{orguser} to OrgUser,
  UserRole{role} to Role,
  OrganizationAddress{addressType(addressTypeNum) required} to AddressType,
  OrganizationContact{contactType(contactTypeNum) required} to ContactType
}

service Organization, OrgUser, RoleType, Role, UserRole, ContactType, AddressType, OrganizationAddress, OrganizationContact with serviceImpl
microservice Organization, OrgUser, RoleType, Role, UserRole, ContactType, AddressType, OrganizationAddress, OrganizationContact with Organization
clientRootFolder Organization, OrgUser, RoleType, Role, UserRole, ContactType, AddressType, OrganizationAddress, OrganizationContact with Organization

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.15.1 (Apple Git-101)

node: v10.13.0

npm: 6.8.0

yeoman: 2.0.5

yarn: 1.10.1

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

**Comment by Pranavism** [comment]
<img width="267" alt="screen shot 2019-02-18 at 10 21 25 pm" src="https://user-images.githubusercontent.com/41497523/52988088-eb442480-33cb-11e9-99ff-7d46f5aa3543.png">

**Comment by Pranavism** [comment]
Tried with what @deepu105 has here at https://medium.com/@deepu105/create-full-microservice-stack-using-jhipster-domain-language-under-30-minutes-ecc6e7fc3f77

Same issue swagger empty with no model schema

**Comment by Pranavism** [comment]
Did anyone face this issues and any resolution for the same?

**Comment by ruddell** [comment]
I can not reproduce.  I used your config to generate a microservice and I can see the model:
![screen shot 2019-02-20 at 9 59 41 am](https://user-images.githubusercontent.com/4294623/53113449-791c2e80-34f6-11e9-8f37-b64f80dd36f6.png)

**Comment by Pranavism** [comment]
Strange , I still don’t see the model.
But when I run in docker with Jdk11 environment sometimes upon restart I  see the model coming as expected.
