### ISSUE TITLE
集成Quartz，且任务持久化

### ISSUE THREAD

**Issue by heiheiyuan** [jhipster/generator-jhipster#9295]
##### **Overview of the feature request**

使用jhipster生成的项目集成Quartz时，实现任务持久化遇到问题，日志无错误信息，但是数据库中也没有任务被写入，普通Demo集成可正常持久化

##### **Motivation for or Use Case**

因为工作需要，自己能力有限，研究了好久都找不到原因，可不可以给个Demo？万分感谢

**Comment by jdubois** [comment]
Please, can you post your ticket in English so we can understand what you mean?

I'm closing this, so you can open another one in English.
