### ISSUE TITLE
Authentication reducer returns errors after logout (401 authentication 

### ISSUE THREAD

**Issue by orkidze** [jhipster/generator-jhipster#9297]
The application was using "api/' as a landing page and rendered content based on if user is authenticated. But after logout the state did not had time to update. 

Error example in browser console (After logging out):
GET https://www.*.com/api/* 401 (Unauthorized)
For basically every resourced I used

The key was to fix auto generated authentication reducer... and add following in **authentication.ts** :
`case REQUEST(ACTION_TYPES.LOGOUT):
      return {
        ...initialState,
        showModalLogin: true
      };`

I hope it helps somebody and I think it might need to be fixed in the JHipster generator.

**Comment by orkidze** [comment]
Btw, the code added was at the very beginning of the switch statement

**Comment by mraible** [comment]
Can you please [submit a pull request](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-a-pull-request) with this change?
