### ISSUE TITLE
Problem with karma tests and latest JHipster

### ISSUE THREAD

**Issue by amchess** [jhipster/generator-jhipster#9298]
I tried latest version ("5.8.1") with latest node and yarn.
I generated a microservice-gateway application with maven build tool.
I can start it with 
`./mvnw` 
and also do integration test with
`yarn e2e`.
The problem is karma tests with Jest because when I run
`npm test`
I have the following error message:

```
> ...
> npm run lint && jest --coverage --logHeapUsage -w=2 --config src/test/javascript/jest.conf.js


> ...
> tslint --project tsconfig.json -e 'node_modules/**'

No valid rules have been specified for JavaScript files
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In ...
  577 files checked.
  testMatch: .../src/test/javascript/spec/**\+(*.)+(spec.ts) - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 577 matches
  testRegex:  - 577 matches
Pattern:  - 0 matches
npm ERR! Test failed.  See above for more details.
..
```

.

The following is the `jhipster info` output:

##### **JHipster Version(s)**

```
espace@0.0.0 C:\git\ECAM\espacev4\espace-gateway
`-- generator-jhipster@5.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "fr.edu.ecam",
            "nativeLanguage": "fr"
        },
        "jhipsterVersion": "5.8.1",
        "applicationType": "gateway",
        "baseName": "espace",
        "packageName": "fr.edu.ecam",
        "packageFolder": "fr/edu/ecam",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "hazelcast",
        "enableHibernateCache": true,
        "websocket": "spring-websocket",
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "postgresql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": ["protractor"],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "fr",
        "languages": ["fr", "en"]
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.19.2.windows.1

node: v10.15.1

npm: 6.8.0

yeoman: 2.0.5

yarn: 1.13.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!
PS C:\git\ECAM\espacev4\espace-gateway>
```
Is this a bug or I'm wrong?

**Comment by gmarziou** [comment]
You should not use yarn at all as you selected npm

`"clientPackageManager": "npm"`

**Comment by gmarziou** [comment]
Seems to be solved on gitter by @tibistibi and @amchess 

> solved
> now all test passed
> It was not a Jhipster problem
> but Jest
> "resolutions": {
> "write-file-atomic": "4.2.1"
> }
> but it's a workaround
> 4.2.2 fails

**Comment by jdubois** [comment]
Closing as per the last comment this looks solved
