### ISSUE TITLE
Heroku: × [Error: stderr maxBuffer exceeded.]

### ISSUE THREAD

**Issue by MartinLichtblau** [jhipster/generator-jhipster#930]
I get the following error while running the command "yo jhipster:heroku", which crashes the deployment process. Probably it's a bug.
![yojhipsterherokuerror](https://cloud.githubusercontent.com/assets/4956334/5602047/0a95aa22-9333-11e4-80db-a9e5f2d9b8e4.PNG)

The solution is to set increase the maxBuffer size in the heroku/index.js as stated [here](http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process). I tried it out and it solved the problem. 
But the newly created app on heroku still crashes during the HerokuDatabaseConfiguration, because of #865 . 

Two questions: Is it normal that it crashes with the current generator? Could we use the [heroku maven plugin](https://devcenter.heroku.com/articles/deploying-java-applications-with-the-heroku-maven-plugin) to deploy on heroku? (which would make it easier to automaitcally deploy new builds from Travis-CI). A fully functional continious intergration & deployment option would be great!

**Comment by jdubois** [comment]
- "maxBuffer" : I had the same problem with the Gitlab repo we have at work, so this is quite common -> could do a PR or send your working configuration?
- It should not crash, but if you are on the free plan it is very slow, and it crashes the app after 60 seconds. So if you don't pay I'm not that surprised.
- I didn't know about this Maven plugin: I'd like to stick with the current method, as it's the same as the other sub-generators (as well as the other Yeoman generators). But this is indeed worth looking at, did you try it? Anyway, that's good to know.

I'm closing this as I don't think you have any blocking bug, am I correct?

**Comment by MartinLichtblau** [comment]
* Yes, done.
* But, it crashes before the 60sec margin on heroku. (See full log [here](https://gist.github.com/MartinLichtblau/5d4287bfb81a6412626f#file-heroku-start-error))
 * Openshift free acc works
 * CloudFoundry free acc (Pivotal) 
   * Generator crashes because of " * " in path. ```
"GetFileAttributesEx C:\Programming\jhiphero\target\*.war: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
× { [Error: Command failed: ] killed: false, code: 1, signal: null }
"```
     * The deployment process fails wiht error ```FAILED
Could not find service jhiphero to bind to jhiphero
× { [Error: Command failed: ] killed: false, code: 1, signal: null }```
* I have tried but I have no idea how I can create the database on heroku and bind the databaseurl during this process.
