### ISSUE TITLE
I18n Placehoder key makes object from field key 

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#9305]
##### **Overview of the issue**

For fields sometimes there is a placeholder text. The key is equal to the label key with placholder extension like this:
global.form.currentpassword = Current password
global.form.currentpassword.placeholder = Current password
 
This gives a problem global.form.currentpassword is now and an object (holding placeholder) and a value holding 'Current password'. In my i18n editor this is a problem and i also see the translation being:
![image](https://user-images.githubusercontent.com/1875634/53074300-a8c53980-34ea-11e9-8087-d0f7bae3402f.png)

If not everyone has it it has probably to do with my i18n editor making it a real object instead of dot notation.

##### **Suggest a Fix**

A solve would be to change the key like this:

global.form.currentpassword = Current password
global.form.currentpassword_placeholder = Current password

or

global.form.currentpassword.label = Current password
global.form.currentpassword.placeholder = Current password

If ok i can do a PR for this.

##### **JHipster Version(s)**

8.5.1

##### **JHipster configuration**

not important.

**Comment by wmarques** [comment]
I'm ok with the second solution

**Comment by wmarques** [comment]
@tibistibi for your information, here is a sample json file, that's why we don't see the problem, I think it's an issue with your i18n editor
```
"password": "Mot de passe",
"password.placeholder": "Votre mot de passe",
```

So it works today, but I find the second solution using `label` and `placeholder` much more clean, if you are willing to do a PR you are welcome

**Comment by tibistibi** [comment]
ok i will do it!

**Comment by tibistibi** [comment]
@wmarques yes it is the editor who can not work with the double meaning. 

as info:
i use the only one which is free and can work with json files:
https://github.com/jcbvm/i18n-editor

**Comment by pdelaby** [comment]
I was going to open a pull request to translate the french labels on this particular field ( `global.form.currentpassword` and `global.form.currentpassword.placeholder` are not translated in french) ( cf https://github.com/jhipster/generator-jhipster/blob/master/generators/languages/templates/src/main/webapp/i18n/en/global.json.ejs ) 
Shoud I wait for the labels changes to do it?

**Comment by wmarques** [comment]
@pdelaby No that's ok that's not a big change so you can already provide your PR :)

**Comment by tibistibi** [comment]
i will do it before monday

**Comment by tibistibi** [comment]
changed all from 
global.form.username -> global.form.username.label
global.form.currentpassword -> global.form.currentpassword.label
global.form.newpassword -> global.form.newpassword.label
global.form.confirmpassword -> global.form.confirmpassword.label
global.form.email -> global.form.email.label

i just pushed it to my own branch lets see what the test are doing

**Comment by tibistibi** [comment]
i noticed that the global.form.currentpassword is missing for these languages:

vi,sk,sr,sv,th,ua,ta

**Comment by wmarques** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/9445

**Comment by tibistibi** [comment]
thanks @wmarques
