### ISSUE TITLE
Adding new language - Uzbek (Cyrillic)

### ISSUE THREAD

**Issue by khasanboyshoraimov** [jhipster/generator-jhipster#9307]
##### **Overview of the feature request**

It would be great to add a new Uzbek language based on Cyrillic alphabet as well. 

##### **Motivation for or Use Case**

Firstly, thanks to all contributors of JHipster, and also to a guy who helped  to add Uzbek - latin language. But there is a high demand on Uzbek - cyrillic as well, as most of our state documentations are written in Cyrillic alphabet.

**Comment by pascalgrimaud** [comment]
New language is always welcome! So go ahead.
@khasanboyshoraimov : would you like to contribute for this ?

**Comment by khasanboyshoraimov** [comment]
@pascalgrimaud, Surely, I will.

**Comment by DanielFran** [comment]
@khasanboyshoraimov You can take example from this PR https://github.com/jhipster/generator-jhipster/pull/8317 and the respective documentation PR https://github.com/jhipster/jhipster.github.io/pull/623

**Comment by khasanboyshoraimov** [comment]
Dear @DanielFran thanks for your guide, I have uploaded all JSON files, however got confused in placing them to directories. Hope not to make that mistakes on my further PRs))

**Comment by pascalgrimaud** [comment]
@khasanboyshoraimov : it's better if you can do 1 PR with all files, so our builds can test the new language

**Comment by DanielFran** [comment]
@khasanboyshoraimov I closed #9309 in favor if #9310.

**Comment by khasanboyshoraimov** [comment]
@DanielFran, documentation PR is done. Thanks a lot.
