### ISSUE TITLE
outputDirectory is not a valid configuration for maven-surefire-plugin

### ISSUE THREAD

**Issue by jsone-studios** [jhipster/generator-jhipster#9317]
##### **Overview of the issue**

Inside the configuration of the maven-surefire-plugin the `outputDirectory` is set to following:

    <outputDirectory>${sonar.junit.reportsPath}</outputDirectory>

But the configuration `outputDirectory` is not present for the maven-surefire-plugin. Therefore the outputs of this plugin are not inside the `${sonar.junit.reportsPath}` directory instead they go into surefires default directory `${project.build.directory}/surefire-reports`.

##### **Suggest a Fix**

An alternative configuration `reportsDirectory` exists, which is exactly what is needed here.

Fix can be found in pr #9318
##### **JHipster Version(s)**

```
test@0.0.0 C:\Home\Development\jhipster\maven-test
`-- generator-jhipster@5.8.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "jsone_studios.test",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.1",
    "baseName": "Test",
    "packageName": "jsone_studios.test",
    "packageFolder": "jsone_studios/test",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "xxxx",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ],
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "skipCommitHook": true,
    "otherModules": [],
    "entitySuffix": "",
    "dtoSuffix": "DTO"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.14.2.windows.1

node: v8.11.3

npm: 5.4.2

yeoman: 2.0.0

yarn: 1.7.0

[x] Checking this box is mandatory (this is just to show you read everything)

**Comment by xmeng1** [comment]
👍
