### ISSUE TITLE
translateService.onLangChange.subscribe not working anymore

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#9319]
##### **Overview of the issue**

I create a component which has a subscription to `translateService.onLangChange.subscribe` and in the JHipster version 5.5.0 was working fine. Now that I update everything to version 5.8.1 is not working anymore.

In particular the following service:
```
import { Injectable } from '@angular/core';

import { BehaviorSubject, Observable, of } from 'rxjs';
import { TranslateService, LangChangeEvent } from '@ngx-translate/core';

@Injectable({ providedIn: 'root' })
export class TimeLocalizationService {
    private timeFormatBehaviorSubject: BehaviorSubject<number>;

    constructor(private translateService: TranslateService) {
        this.timeFormatBehaviorSubject = new BehaviorSubject<number>(this.getFormat(this.translateService.currentLang));

        this.translateService.onLangChange.subscribe((langChangeEvent: LangChangeEvent) => {
            console.log(langChangeEvent);
            this.timeFormatBehaviorSubject.next(this.getFormat(langChangeEvent.lang));
        });
    }

    getTimeFormat(): Observable<number> {
        return this.timeFormatBehaviorSubject.asObservable();
    }

    private getFormat(langKey: string): number {
        if (langKey) {
            switch (langKey) {
                case 'en':
                    return 12;
                case 'it':
                case 'fr':
                    return 24;
                default:
                    return 12;
            }
        } else {
            return 12;
        }
    }
}
```

##### **Motivation for or Use Case**

I add to my project the [ngx-material-timepicker](https://github.com/Agranom/ngx-material-timepicker) which is able to show the time in 12H or 24H.
Then I have created the above service that is listening to the change of language of the user and change the settings from 12H to 24H and vice-versa.
With JHipster 5.5.0 this service was working fine and now I migrated the same code to the last JHipster version 5.8.1 and it does not working anymore.
In particular I tried the following test:

```
this.translateService.onLangChange.subscribe((langChangeEvent: LangChangeEvent) => {
            console.log(langChangeEvent);
            this.timeFormatBehaviorSubject.next(this.getFormat(langChangeEvent.lang));
        });
```
And now I can't see any log in the console of Chrome.
Before I was able to see the changes and propagate the result of `this.getFormat(langChangeEvent.lang)` to my component in order to change the time settings.

##### **Related issues**

I didn't see any.

##### **Suggest a Fix**

Check what is changed in between JHipster v5.5.0 and v5.8.1 to  understand why it is not working anymore.

##### **JHipster Version(s)**

At the moment v5.8.1
When it was working v5.5.0

##### **JHipster configuration**

I don't think it is necessary here. I used exactly the same code from previous version 5.5.0 to 5.8.1 and it stopped working.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entity at the moment

##### **Browsers and Operating System**

Ubuntu 18.04
Chrome Version 72.0.3626.109 (Official Build) (64-bit)

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@alexsintoni : I'm not an Angular expert (@wmarques is :-p) so I can only show you ticket and pull requests, related to this subject :
- the original issue : https://github.com/jhipster/generator-jhipster/issues/9048
- 1st fix : https://github.com/jhipster/ng-jhipster/pull/87
- another fix : https://github.com/jhipster/ng-jhipster/pull/90

Maybe it can help you.

**Comment by wmarques** [comment]
@alexsintoni Did you correctly upgraded the `ng-jhipster` lib to the latest and added the `ngx-translate` lib in your `package.json`?

**Comment by alexsintoni** [comment]
Hi @pascalgrimaud and @wmarques 
thanks a million for your help.

What I did is:

1. create a JHipster gateway app with generator version 5.5.0
2. install dependency `ngx-material-timepicker` and add this component to a page
3. add the service `TimeLocalizationService` to the project to change the `format` input of `ngx-material-timepicker` when the user changed the language

In this project was working fine.
After I created a new JHipster gateway project with generator version 5.8.1 and add the wep page with the `ngx-material-timepicker` and the service `TimeLocalizationService`.

Unfortunately, with this version the following code wasn't working anymore:
```
this.translateService.onLangChange.subscribe((langChangeEvent: LangChangeEvent) => {
            console.log(langChangeEvent);
            this.timeFormatBehaviorSubject.next(this.getFormat(langChangeEvent.lang));
});
```

**Comment by wmarques** [comment]
@alexsintoni Ok I'll try to reproduce this, might be related to the recent changes we did in the `ng-jhipster` lib

**Comment by wmarques** [comment]
@alexsintoni Just tried the following:
* Generate a jhipster app from master branch
* Added a listener to the  `onLangChange` event in the `HomeComponent`
* Switching languages, the `onLangChange` event works

Do you have any errors in your terminal or in your JS Console ?

**Comment by vishal423** [comment]
do check code under `JhiLanguageHelper` as that contains similar code to your requirement and seems to work fine:

```
        this.translateService.onLangChange.subscribe((event: LangChangeEvent) => {
            this._language.next(this.translateService.currentLang);
            this.renderer.setAttribute(document.querySelector('html'), 'lang', this.translateService.currentLang);
            this.updateTitle();
        });
```

**Comment by alexsintoni** [comment]
@wmarques @vishal423 I apologise for the delay of my reply.

I don't get any error and any log in my console and I can't change the parameter for [ngx-material-timepicker](https://github.com/Agranom/ngx-material-timepicker) because 
```
this.translateService.onLangChange.subscribe((langChangeEvent: LangChangeEvent) => {
            console.log(langChangeEvent);
            this.timeFormatBehaviorSubject.next(this.getFormat(langChangeEvent.lang));
});
```
does not react at all.
I will check if I changed something involuntarily and let you know.

Anyway, really thank you for you help

**Comment by wmarques** [comment]
@alexsintoni Give me a reproduction case, or a repo that i can clone to reproduce this ;) 
When I listen to the `onLangChange` event in a freshly generated app, it works.

**Comment by wmarques** [comment]
Closing this as non reproductible

**Comment by iahmedgamal** [comment]
facing the same error now

**Comment by sebastientromp** [comment]
I'm also facing this error. I use `translateService.use(newLocale)` to change the language, and listen to changes with `translate.onLangChange.subscribe((info) => console.debug('loc changed in service', info));`.

The callback is never called.
