### ISSUE TITLE
Javascript bundle 'global' is always empty for angular production build

### ISSUE THREAD

**Issue by jsone-studios** [jhipster/generator-jhipster#9334]
##### **Overview of the issue**

The JavaScript bundle 'global' does only contain CSS as its entrypoint is `global.(css|scss)`.
In the production build all CSS is extracted into a separate CSS file because of the MiniCssExtractPlugin.
Therefore the final `global.[hash].bundle.js` will only contain the standard webpack import stuff but no code from us and so it is useless.

##### **Reproduce the error**

- clone [jhipster-sample-app](https://github.com/jhipster/jhipster-sample-app)
- `npm install`
- `npm run webpack:prod`
- Look into `target/www/app/global.[hash].bundle.js`

##### **Suggest a Fix**

Remove the global entrypoint of the webpack production configuration and import the `global.(css|scss)` in`app.main.ts`.

I can do the PR.

##### **JHipster Version(s)**

```
jhipster-sample-application@0.0.0 C:\Home\Development\OpenSource\jhipster-sample-app
`-- generator-jhipster@5.8.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "baseName": "jhipsterSampleApplication",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "maven",
    "searchEngine": false,
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "languages": [
      "en"
    ],
    "serverPort": 8080,
    "jhipsterVersion": "5.8.1",
    "enableSocialSignIn": false,
    "useSass": false,
    "jhiPrefix": "jhi",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "reactive": false,
    "otherModules": [],
    "entitySuffix": "",
    "dtoSuffix": "DTO"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount {
  name String required,
  balance BigDecimal required
}
entity Label {
  label String required minlength(3)
}
entity Operation {
  date DateTime required,
  description String,
  amount BigDecimal required
}
relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)}
}
relationship ManyToOne {
  BankAccount{user(login)} to User
}
relationship ManyToMany {
  Operation{label(label)} to Label{operation}
}

paginate Operation with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.14.2.windows.1

node: v10.15.1

npm: 6.4.1

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
@jsone-studios LGTM

**Comment by DanielFran** [comment]
Closing since #9334 has been closed
