### ISSUE TITLE
version 5.8.1 broken due to HTTP version missing in jHipsterProperties class

### ISSUE THREAD

**Issue by Pranavism** [jhipster/generator-jhipster#9345]
##### **Overview of the issue**

NOte: I upgraded from 5 to 5.8.1 version

1)jHipsterProperties.getHttp().getVersion()
getHttp().getVersion() is not found.
in WebConfigurer.java  , JHipsterProperties.Http.Version.V_2_0 
Version is not found and it  is not in HTTP()
compilation error.

##### **Motivation for or Use Case**

This was working till a few days back with new build it fails

##### **Reproduce the error**

generate any project with 5.8.1 and check for compilation error or do a build

##### **JHipster Version(s)**

5.8.1

##### **JHipster Version(s)**

```
uaa@0.0.0 /Users/pranavsingh/Desktop/test
└── generator-jhipster@5.8.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.sb.uaa"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "com.sb.uaa",
    "packageFolder": "com/sb/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.15.1 (Apple Git-101)

node: v10.13.0

npm: 6.8.0

yeoman: 2.0.5

yarn: 1.10.1

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Pranavism** [comment]
public static class Http {

        private final Cache cache = new Cache();

        public Cache getCache() {
            return cache;
        }

        public static class Cache {

            private int timeToLiveInDays = JHipsterDefaults.Http.Cache.timeToLiveInDays;

            public int getTimeToLiveInDays() {
                return timeToLiveInDays;
            }

            public void setTimeToLiveInDays(int timeToLiveInDays) {
                this.timeToLiveInDays = timeToLiveInDays;
            }
        }
    }


No getVersion() here , hence the issue

**Comment by Pranavism** [comment]
More failures with 5.8.1
--------------------------------
> Task :compileJava
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.17.Final
/Users/pranavsingh/Desktop/test/src/main/java/com/sb/uaa/config/LiquibaseConfiguration.java:14: error: cannot find symbol
import org.springframework.core.env.Profiles;
                                   ^
  symbol:   class Profiles
  location: package org.springframework.core.env
/Users/pranavsingh/Desktop/test/src/main/java/com/sb/uaa/aop/logging/LoggingAspect.java:14: error: cannot find symbol
import org.springframework.core.env.Profiles;
                                   ^
  symbol:   class Profiles
  location: package org.springframework.core.env
main/java/com/sb/uaa/config/CacheConfiguration.java:18: error: cannot find symbol
import org.springframework.core.env.Profiles;
                                   ^
  symbol:   class Profiles
  location: package org.springframework.core.env
src/main/java/com/sb/uaa/config/AsyncConfiguration.java:8: error: package org.springframework.boot.autoconfigure.task does not exist
import org.springframework.boot.autoconfigure.task.TaskExecutionProperties;
                                                  ^
src/main/java/com/sb/uaa/config/AsyncConfiguration.java:25: error: cannot find symbol
    private final TaskExecutionProperties taskExecutionProperties;
                  ^
  symbol:   class TaskExecutionProperties
  location: class AsyncConfiguration
/src/main/java/com/sb/uaa/config/AsyncConfiguration.java:27: error: cannot find symbol
    public AsyncConfiguration(TaskExecutionProperties taskExecutionProperties) {
                              ^
  symbol:   class TaskExecutionProperties
  location: class AsyncConfiguration
6 errors

**Comment by pmverma** [comment]
It seems there are problems with your local repository. Did you try by cleaning your local `~/.m2/repository` repository?

**Comment by Pranavism** [comment]
it is even failing on another machine.

**Comment by Pranavism** [comment]
This is HTTP class

public static class Http {

```
    private final Cache cache = new Cache();

    public Cache getCache() {
        return cache;
    }

    public static class Cache {

        private int timeToLiveInDays = JHipsterDefaults.Http.Cache.timeToLiveInDays;

        public int getTimeToLiveInDays() {
            return timeToLiveInDays;
        }

        public void setTimeToLiveInDays(int timeToLiveInDays) {
            this.timeToLiveInDays = timeToLiveInDays;
        }
    }
}
```

Note that there is no "Version" here.

**Comment by Pranavism** [comment]
<img width="944" alt="screen shot 2019-02-27 at 9 31 26 am" src="https://user-images.githubusercontent.com/41497523/53497597-87c49180-3a72-11e9-9829-ff9ccc431b6a.png">

**Comment by Pranavism** [comment]
@DanielFran  the change resulting in to this issue was made here 
https://github.com/jhipster/jhipster/commit/b0d1223766997ee462a5f3a7be910d00ccb07655#diff-d73b450e042bc33509018d66093cf7e1

@JulienGard

**Comment by cbornet** [comment]
JHipster 5.8.1 depends on version 2.1.1 of jhipster-framework so you shouldn't pull 3.0.0-SNAPSHOT. Did you modify things manually ?

**Comment by jdubois** [comment]
@Pranavism indeed, that change was commited 7 days ago and is not released yet, how come you are using it?

**Comment by DanielFran** [comment]
@Pranavism If you are using the master, you need to compile also the jhipster/jhipster project otherwise you will doenload a snapshot that has been created several weeks ago were the changes you invoke are not present.

**Comment by Pranavism** [comment]
@jdubois I did nothing out of normal!
I had a well working project (several components) then I upgraded it to 5.8.1 and still they were all working just as expected.
Later today I had to do a clean build and it started failing.
gradle properties has 3.0.0 Snapshot as version for jhipster dependency and since it does not have version related code it started failing.

I tried changing it to 2.1.1 and though the original issue was fixed there were other broken pieces everywher so reverted to 3.0.0 Snapshot.
For now I commented out the version related code , but not sure what should be done exactly to overcome this issue.

**Comment by Pranavism** [comment]
@DanielFran thanks for getting back, if you don't mind can you please help me understand what exactly is required to fix this issue.

**Comment by jdubois** [comment]
@Pranavism sorry, I can't believe we are having a snapshot release with Gradle on our latest release!! Let me check ASAP

**Comment by jdubois** [comment]
On our sample app, that I generate with every release, we do use a stable version, see: https://github.com/jhipster/jhipster-sample-app-gradle/blob/master/gradle.properties

@Pranavism maybe this is an issue with our upgrade sub-generator, how exactly did you do the upgrade?

**Comment by DanielFran** [comment]
@Pranavism If you use v.5.8.1 it should not target jhispter/jhipster version 3.0.0-SNAPSHOT.

If you are creating the project based on master that you compile locally, you need also to compile jhipster-bom version locally (jhipster/jhipster project).
If you do not do that, it will try to download an old snapshot that was created some week ago that is probably the origin of your problem.

**Comment by Pranavism** [comment]
@jdubois I used upgrade sub-generator.
probably it is not just the snapshot because when reverted to stable version it results into failure across other config classes. is it that the upgrade sub generator pulled the config classes as well from non stable version ?

**Comment by Pranavism** [comment]
@jdubois  oh !! the projects that I upgraded are using spring boot 2.1.3 and has java 11 related OR condition in gradle

**Comment by jdubois** [comment]
@Pranavism I have no idea why the upgrade sub-generator pulled a non-stable version. This just should not happen, and I have never heard of this before.

**Comment by Pranavism** [comment]
@jdubois  I guess this is why the newer builds were failing on k8s deployment.
Probably I should remove everything and re-install 5.8.1 and regenerate?

**Comment by jdubois** [comment]
@Pranavism yes that would definitely put you a stable release, but I don't really understand the issue

**Comment by jdubois** [comment]
I'm closing this as I understand you probably upgraded manually, and are going to regenerate the app using a stable build.

**Comment by Pranavism** [comment]
Alright , I have them working with refreshed version.

**Comment by al100** [comment]
I faced the same issue and remove jhipster framework 3.0.3 from my pom.xml and it fixed it

Hope it helps
