### ISSUE TITLE
Protractor: application with session as authenticationType

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#9349]
##### **Overview of the issue**

Protractor tests failed for an application with session as authenticationType, only with production profile :

```
  account
    ✓ should fail to login with bad password
    ✓ should login successfully with admin account (1719ms)
    ✓ should be able to update settings
    ✓ should fail to update password when using incorrect current password
    1) should be able to update password
    2) "after all" hook: ret for "should be able to update password"

```

##### **Reproduce the error**

- generate an application with session as authenticationType
- package in production profile
- run application
- run Protractor tests

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/45-session
└── generator-jhipster@5.8.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.20.1

node: v10.15.0

npm: 6.7.0

yeoman: 2.0.5

yarn: 1.13.0

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.21.2, build a133471

INFO! Congratulations, JHipster execution is complete!

**Comment by sendilkumarn** [comment]
I guess the protractor tests are kind of flaky at the moment. It is constantly failing for the Kotlin branch 😢

**Comment by sendilkumarn** [comment]
It will be really awesome if we can split the `FieldTestServiceClassEntity` entity into two or three different entities

**Comment by pascalgrimaud** [comment]
For this config, with prod profile, it always failed locally.
So there is a real issue.
