### ISSUE TITLE
liveness and readiness http probe fails for microservices other than Gateway when UAA is deployed

### ISSUE THREAD

**Issue by Pranavism** [jhipster/generator-jhipster#9357]
##### **Overview of the issue**

The kubernetes deployment for microservices fails for not gateway apps.
UAA based architecture is not working , is it not supported ?

Following is the container logs:

Profile(s): 	[prod]
External: 	http://10.8.2.13:8082/Organization
Local: 		http://localhost:8082/Organization

Application 'Organization' is running! Access URLs:

It seems the /Organization is the problem here.
 
**Error:**

[2019-03-02T03:43:28.056Z] "GET /organization/management/health HTTP/1.1" 503 UF 0 57 0 - "-" "kube-probe/1.11+" "6b2a0ac9-8f50-9f38-90c3-a0ae840ed9e8" "10.8.2.13:8081" "127.0.0.1:8081"

##### **Motivation for or Use Case**

Non Gateway applications i.e a microservice and UAA fails to get health check passed in K8s.

##### **Reproduce the error**

Generate a microservices app with UAA , a microservice and Gateway.
Deploy on K8 in prod profile.
The health check fails for UAA and microservices but works for Gateway.
##### **JHipster Version(s)**
5.8.1

##### **JHipster configuration**

{
  "generator-jhipster": {
    "deploymentType": "kubernetes",
    "gatewayType": "zuul",
    "monitoring": "no",
    "directoryPath": "../",
    "appsFolders": [
      "Organization",
      "Supplybyte",
      "UAA"
    ],
    "clusteredDbApps": [],
    "consoleOptions": [],
    "serviceDiscoveryType": false,
    "jwtSecretKey": "NmEyYTNhMWUyYWQxMmUwMzZjMDU1MDc1OTAyOGEwNWYxNjJmM2I5ZjA2NmNjMWZlYmVkYzQ0ODAzMzlmNTJkMzFiNGE3MjcyMzZiMjVkNjZhZTFkNGYzNWY0Mjk3NzEwMTI1YQ==",
    "dockerRepositoryName": "gcr.io/suppybytedemo",
    "dockerPushCommand": "docker push",
    "kubernetesNamespace": "supplybyte",
    "kubernetesServiceType": "Ingress",
    "ingressDomain": "35.193.135.141.nip.io",
    "istio": "autoInjection",
    "istioRoute": true
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

**Organization Microservice config:**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.sb.organization"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "microservice",
    "baseName": "Organization",
    "packageName": "com.sb.organization",
    "packageFolder": "com/sb/organization",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "UAA",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "OWRiYjMyYTY3MWIwOTczY2QwOTg0N2IwMTQ2OTMwNWViYjk2ZmU3MGZkNGRkYWQ2NjQ1YTQ3NDY5MjQ3Y2JlYjgwNzlhOTEzZTI0Y2M4NmM5MDc1ZDJiNDdhOGNiODQwNjVlNjJiZmI4ZGM3YjNiODlmNGE5MjQxZmNmOWFkZGY=",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true,
    "messageBroker": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  }
}
##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Pranavism** [comment]
@jdubois  is UAA based architecture supported for kubernetes ?
with jwt it does work but when UAA is used all services other than gateway fails health check .
We have large customization around UAA for security context , is there a way to make UAA work?
@deepu105

**Comment by jdubois** [comment]
I have no idea I didn't work on those parts, why do you ask me specifically?

**Comment by xetys** [comment]
hey, 

this is related to #9027 and #9176, and I have a plan for it...I hope I'll find time to work on this one

**Comment by pascalgrimaud** [comment]
It looks like the same ticket than https://github.com/jhipster/generator-jhipster/issues/9027
Let focus on this ticket, that's why I'm closing this one.

**Comment by Pranavism** [comment]
@xetys Thanks for the enhancement, got a question before we switch to istio. what does it take to incorporate this change?
Our microservices have matured and cannot upgrade to latest jhipster (to avoid any unforseen event). will updating generator to latest and then generating k8 manifests will be enough.
I tried to look at the files with code changes but wanted to make sure by seeking your expert advice.
