### ISSUE TITLE
Glyphicon assets fails to load in browser when generating a project using Compass

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#936]
The navbar has only square looking icons since glyphicons assets fails to load (when using latest 2.0 version).

This is what the browser console outputs:

```
Failed to load resource: the server responded with a status of 404 (Not Found)   http://localhost:8080/assets/bower_components/bootstrap-sass/vendor/assets/fonts/bootstrap/glyphicons-halflings-regular.woff

Failed to load resource: the server responded with a status of 404 (Not Found)   http://localhost:8080/assets/bower_components/bootstrap-sass/vendor/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
```

**Comment by jmirc** [comment]
Can you check if bower has loaded the libraries?

**Comment by sdoxsee** [comment]
Had this problem too with the latest code. I was able to get it working locally (haven't checked production) by changing the first line of main.scss to 

$icon-font-path: "../../bower_components/bootstrap-sass/vendor/assets/fonts/bootstrap/";

so it could find the font files. It's because the output "css" file is 2 directories in from the root (assets/styles/main.css) and the bower_components is directly under the webapp root.

**Comment by andidev** [comment]
They seem to exists in `src/main/webapp/bower_components/bootstrap-sass/vendor/assets/fonts/bootstrap/`.

I can confirm that changing the $icon-font-path as @sdoxsee mentions fixes the issue, but only when running the application with `grunt server` command. Then the correct path
```
http://localhost:9000/bower_components/bootstrap-sass/vendor/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
```
to the fonts is used.

But when running the application with `mvn spring-boot:run` then the incorrect path 
```
http://localhost:8080/assets/bower_components/bootstrap-sass/vendor/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
```
is used.

**Comment by MartinLichtblau** [comment]
Thanks!

**Comment by jdubois** [comment]
@andidev can you send us a PR with your code?

**Comment by mikizdr** [comment]
@sdoxsee is quiet right. It should change the line:

$icon-font-path: "../../bootstrap-sass/assets/fonts/bootstrap/";

with this one:

$icon-font-path: "../../bower_components/bootstrap-sass/assets/fonts/bootstrap/";


in main.scss or index.scss or what ever *.scss file is named.
