### ISSUE TITLE
Use the Prettier transform for all subgens

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#9367]
##### **Overview of the feature request**

Following this PR https://github.com/jhipster/generator-jhipster/pull/9281 from @Fydon, we have prettierisation of YAML files for the main generator. 

I'm proposing to add this transform to all our subgens and especially for the Kubernetes related subgens which use a lot of YAML. The v6 release is a good time to do this.

However there is something to be aware of : this will change the indentation style for lists. Currently with the Kubernetes subgen, our lists are indented like this :

```
spec:
  containers:
  - name: app
```
With prettier, it will be indented like this :
```
spec:
  containers:
    - name: app
```

##### **Motivation for or Use Case**

- Not having to think too much about formating of the templates
- Being able to catch invalid YAML in CI and suggest a fix

**Comment by cbornet** [comment]
In that case we should match the prettier style when generating the lube yaml.

**Comment by PierreBesson** [comment]
So apparently there was a vote on https://github.com/prettier/prettier/issues/4723 and the behavior cannot be configured for now. The indented version looks fine for me and I think it's good to enforce conventions automatically.
