### ISSUE TITLE
Sonar : externalize sonar config in .properties

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#9374]
##### **Overview of the feature request**
For the moment JHipster generate Sonar config in pom.xml or gradle properties. This mean we can use both wrappers for launch the sonar scan.
It useful but I think we can do better by adding a sonar-project.properties in project root folder and load it into pom (for example).
This could offer another way to launch sonar: [sonar scanner](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner).

Of course we keep the maven/gradle way too.

##### **Motivation for or Use Case**
If you generate a new project with `--skip-server` flag it don't come with a sonar config and you can't use sonar scanner.
This could fix it.

I've already started working on this but I have some troubles to how use or not maven properties in sonar properties. Of course we can't use them since with `--skip-server` we don't have maven at all.

I will open a WIP PR soon.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
If you have problems setting up the maven plugin to read the sonar.properties files I can help.
