### ISSUE TITLE
Overwrite files after confirmation rather than during

### ISSUE THREAD

**Issue by smulhall1337** [jhipster/generator-jhipster#9376]
##### **Overview of the feature request**

Jhipster will wait until after confirmation of all files that will be overwritten to perform its operations. This would allow a user to abort whatever operation they're doing in the event of a mistake (say an accidental overwriting of a file thats been heavily modified) and still preserve their files in the original state without having to do something like a git reset.

##### **Motivation for or Use Case**

Purely quality of life. I've been using jhipster with an ever evolving project and doing something like updating an entity can be a pretty cumbersome task due to all the files that I've crammed my business logic into. Still some files I would like to be overwritten, such as the entity model. However sometimes 'module' can look a lot like 'model' and sometimes I absent mindedly hit y-enter only to realize my error too late. Then at that point I'm stuck because I can abort but the file has already been blown away and now I have to call on git to fix the damage. But maybe I didn't commit what I was working on before I ran the entity sub-generator? That work is now gone, granted from my own short comings. 

All in all I feel that if a user aborts an operation such as that, I should be able to return to exactly the state I was in before I ran that command, much like a git merge that I can abort out of. 

##### **Related issues or PR**

I have not seen any issues relating to this.

I'd be happy to try my hand in this matter if I could get pointed in the right direction. Jhipster has been an invaluable tool for me in my work and I'd love to be counted as a contributor. 

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
- I'm not sure we have the power to do it directly, as this comes from Yeoman -> in that case you would need to modify Yeoman first, so that's not impossible but more complex
- Personally I never work on a file by file basis like this: I overwrite everything and work with Git to choose which file I want to update or not. Isn't Git better suited for this kind of job?

**Comment by smulhall1337** [comment]
Thats a fair point and it is what git is good at. I'd personally want to avoid any kind of merge if I can. The less comparing and merging files that I have to do, the sooner I can just get right back into what I was doing before.

**Comment by deepu105** [comment]
yeoman indeed commits updates only when user accepts it so I don't think there is any more room to rollback an invalid decision. So as Julien said using Git is the recommended approach
