### ISSUE TITLE
Add a css linter

### ISSUE THREAD

**Issue by fishonweb** [jhipster/generator-jhipster#9380]
##### **Overview of the feature request**
For the moment, Jhipster has no css linter and it's very easy to write CSS very badly. It can be useful to add a css linter and avoid bad css code and mistakes.

##### **Motivation for or Use Case**
A css linter help to point out with your css code. It does syntax checking as well as applying a set of rules to the code that looks for problematic patterns or inefficiency. It will stop you to write mistakes in your css. It enforce best practices and code style convention.

I suggest to use [stylelint](https://github.com/stylelint/stylelint)

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by wmarques** [comment]
I'm ok for it, since we use prettier, we should avoid conflicts between stylelint rules and prettier formatting

**Comment by fishonweb** [comment]
Thanks, we started to use it on our project. 
I totally aggree with you to avoid conflict between linter and prettier. For me both are complementary and prettier will use stylelint rules.

**Comment by pascalgrimaud** [comment]
@fishonweb : any advance on this ?

**Comment by pascalgrimaud** [comment]
If someone is motivated to work on this, just comment this ticket.
For now, let's close this, as it's opened for too long.
