### ISSUE TITLE
Angular - generator-jhipster - Couldn't follow symbolic link

### ISSUE THREAD

**Issue by vleboulanger** [jhipster/generator-jhipster#9382]
##### **Overview of the issue**

I upgrade my jhipster project from 5.7.2 to 5.8.2. Migration was a success, all works on my dev environment, but when I push on my gitlab server (ubuntu 18.04), compilation failed. I don't understand why...

I have a monolith project, with gradle, JWT, postgresql.

##### **Motivation for or Use Case**

I can not push upgrade project on my server..

##### **Reproduce the error**

`$ ./gradlew test -PnodeInstall --no-daemon
> Task :bootBuildInfo
> Task :compileJava
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.17.Final
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :nodeSetup UP-TO-DATE
> Task :npmSetup UP-TO-DATE
> Task :npmInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of output files for task ':npmInstall' property '$1' during up-to-date check.
> Could not list contents of '/home/gitlab-runner/builds/23dc74ac/0/Appli/appli/node_modules/generator-jhipster/node_modules/js-yaml/node_modules/.bin/esparse'. Couldn't follow symbolic link.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 8s
5 actionable tasks: 3 executed, 2 up-to-date
Uploading artifacts...
Runtime platform                                    arch=amd64 os=linux pid=37537 revision=8bb608ff version=11.7.0
WARNING: build/test-results/test/TEST-*.xml: no matching files 
ERROR: No files to upload                          
ERROR: Job failed: exit status 1`

##### **JHipster configuration**

 "generator-jhipster": {
        "promptValues": {
            "packageName": "fr.yoni.appli",
            "nativeLanguage": "fr"
        },
        "jhipsterVersion": "5.8.2",
        "applicationType": "monolith",
        "baseName": "yvidya",
        "packageName": "fr.yoni.appli",
        "packageFolder": "fr/yoni/appli",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "postgresql",
        "prodDatabaseType": "postgresql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "gradle",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "MY KEY=",
        "clientFramework": "angularX",
        "useSass": false,
        "clientPackageManager": "npm",
        "testFrameworks": ["gatling", "cucumber"],
        "jhiPrefix": "jhi",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "fr",
        "languages": ["fr", "en"],
        "entitySuffix": "",
        "dtoSuffix": "DTO"
    }

**Comment by atomfrede** [comment]
What runners are you using for gitlab ci? Can you check in your ci config to execute `npm install` directly instead via gradle?

**Comment by vleboulanger** [comment]
I am using gitlab runner

In my gitlab ci, you want I replace 

`./gradlew npm_install -PnodeInstall --no-daemon`

By 

`npm install`


?

Thanks

**Comment by wmarques** [comment]
@vleboulanger yes I think that what @atomfrede meant :)

**Comment by vleboulanger** [comment]
it does not work : 

`Successfully extracted cache
$ export GRADLE_USER_HOME=`pwd`/.gradle
$ npm_install
bash: line 70: npm_install: command not found
ERROR: Job failed: exit status 1`

If I connect on my server, and launch manually "npm install" on folder application, command run...

**Comment by atomfrede** [comment]
You may have to make sure to use a correct image in that case. E.g. a node/npm image as we have a jvm base image

**Comment by vleboulanger** [comment]
I try again

I put 'npm_install' instead of 'npm install' doh!!!

**Comment by vleboulanger** [comment]
Result is the same with 'npm install'

`> Task :npmInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of output files for task ':npmInstall' property '$1' during up-to-date check.
> Could not list contents of '/home/gitlab-runner/builds/23dc74ac/0/Appli/appli/node_modules/generator-jhipster/node_modules/js-yaml/node_modules/.bin/esparse'. Couldn't follow symbolic link.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 17s
5 actionable tasks: 5 executed
Uploading artifacts...
Runtime platform                                    arch=amd64 os=linux pid=33196 revision=8bb608ff version=11.7.0`

**Comment by atomfrede** [comment]
I think we didn't understand each other. You executed the task via gradle. What I asked for to make sure it is not a problem with npm or your runner to not use gradle to execute npm task, but use npm directly to execute the task. How is your runner setup? Is it a docker runner, a shell runner or something else? Which version of the runner and gitlab you are using?

**Comment by vleboulanger** [comment]
it is not a docker runner : 

gitlab-runner version : 

`Version:      11.7.0
Git revision: 8bb608ff
Git branch:   11-7-stable
GO version:   go1.8.7
Built:        2019-01-22T11:24:14+0000
OS/Arch:      linux/amd64
`

gitlab version : GitLab Community Edition 11.7.3

My server is Ubuntu 18.04.2

**Comment by vleboulanger** [comment]
complete trace : 

`
$ ./gradlew test -PnodeInstall --no-daemon
Downloading https://services.gradle.org/distributions/gradle-4.10.2-bin.zip
..........................................................................

Welcome to Gradle 4.10.2!

Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC6
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block

For more details see https://docs.gradle.org/4.10.2/release-notes.html

> Task :bootBuildInfo
> Task :compileJava
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.17.Final
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :nodeSetup

> Task :npmSetup
/home/gitlab-runner/builds/23dc74ac/0/Appli/Appli/.gradle/npm/npm-v6.4.1/bin/npm -> /home/gitlab-runner/builds/23dc74ac/0/Appli/Appli/.gradle/npm/npm-v6.4.1/lib/node_modules/npm/bin/npm-cli.js
/home/gitlab-runner/builds/23dc74ac/0/Appli/Appli/.gradle/npm/npm-v6.4.1/bin/npx -> /home/gitlab-runner/builds/23dc74ac/0/Appli/Appli/.gradle/npm/npm-v6.4.1/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.4.1
added 387 packages from 770 contributors in 19.422s

> Task :npmInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of output files for task ':npmInstall' property '$1' during up-to-date check.
> Could not list contents of '/home/gitlab-runner/builds/23dc74ac/0/Appli/Appli/node_modules/generator-jhipster/node_modules/js-yaml/node_modules/.bin/esparse'. Couldn't follow symbolic link.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 17s
5 actionable tasks: 5 executed
Uploading artifacts...
Runtime platform                                    arch=amd64 os=linux pid=33196 revision=8bb608ff version=11.7.0
WARNING: build/test-results/test/TEST-*.xml: no matching files 
ERROR: No files to upload                          
ERROR: Job failed: exit status 1
`

**Comment by atomfrede** [comment]
I would say it is a problem of your runner (so it is a shell runner, right?) Can you just the delete the node_modules folder in the build directory? All in all I would say it is not a jhipster issue.

**Comment by vleboulanger** [comment]
Ok I try, but with production version in jhipster 5.7.2, all it works

**Comment by vleboulanger** [comment]
I upgrade gitlab, gitlab-runer, create a new runner.. it does not work

I am giving up upgrade project

**Comment by atomfrede** [comment]
Did you remove the node_modules folder or was the runner empty? Sorry I can't help you more, but it works with gitlab.com, but I will try to have a look. But as it works on your local machine I suspect something with the gitlab runner, but I only use the hosted solution myself.

**Comment by atomfrede** [comment]
Can you check this issue? https://github.com/srs/gradle-node-plugin/issues/190 Maybe delete your .gradle folder on the runner? But as you said you tried a new runner not sure it would help.

**Comment by vleboulanger** [comment]
Yes I test with an empty runner

**Comment by atomfrede** [comment]
An it is a shell runner, right? Can you clone your repo and try to build it on the runner manually?

**Comment by vleboulanger** [comment]
Yes a shell runner
I create a new instance of runner => empty folder 

I build with dev profile, content of profile_dev.gradle in 5.8 : 

`
import org.gradle.internal.os.OperatingSystem

apply plugin: 'org.springframework.boot'
apply plugin: 'com.moowork.node'

dependencies {
    compile "org.springframework.boot:spring-boot-devtools"
}

def profiles = 'dev'
if (project.hasProperty('no-liquibase')) {
    profiles += ',no-liquibase'
}
if (project.hasProperty('tls')) {
    profiles += ',tls'
}

springBoot {
    buildInfo {
		properties {
			time = null
		}
	}
}

bootRun {
    args = []
}

task webpackBuildDev(type: NpmTask) {
    inputs.files(fileTree('src/main/webapp/'))

    def webpackDevFiles = fileTree('webpack//')
    webpackDevFiles.exclude('webpack.prod.js')
    inputs.files(webpackDevFiles)

    outputs.files(fileTree("build/www/"))

    dependsOn npmInstall

    args = ["run", "webpack:build"]
}

task copyIntoStatic (type: Copy) {
    from 'build/www/'
    into 'build/resources/main/static'
}

processResources {
    filesMatching('**/application.yml') {
        filter {
            it.replace('#project.version#', version)
        }
        filter {
            it.replace('#spring.profiles.active#', profiles)
        }
    }
}

processResources.dependsOn webpackBuildDev
copyIntoStatic.dependsOn processResources
bootJar.dependsOn copyIntoStatic
`

And content in 5.7.2 : 

`import org.gradle.internal.os.OperatingSystem

apply plugin: 'org.springframework.boot'
apply plugin: 'com.moowork.node'

dependencies {
    compile "org.springframework.boot:spring-boot-devtools"
}

def profiles = 'dev'
if (project.hasProperty('no-liquibase')) {
    profiles += ',no-liquibase'
}
if (project.hasProperty('tls')) {
    profiles += ',tls'
}

bootRun {
    args = []
}

task webpackBuildDev(type: NpmTask, dependsOn: 'npm_install') {
    inputs.dir("src/main/webapp/")
    inputs.files(fileTree('src/main/webapp/'))
    outputs.dir("build/www/")
    outputs.file("build/www/app/main.bundle.js")
    args = ["run", "webpack:build"]
}

task copyIntoStatic (type: Copy) {
    from 'build/www/'
    into 'build/resources/main/static'
}

processResources {
    filesMatching('**/application.yml') {
        filter {
            it.replace('#project.version#', version)
        }
        filter {
            it.replace('#spring.profiles.active#', profiles)
        }
    }
}

processResources.dependsOn webpackBuildDev
copyIntoStatic.dependsOn processResources
bootJar.dependsOn copyIntoStatic`

**Comment by atomfrede** [comment]
You could try replace the `webpackBuildDev` task with the one from 5.7

```groovy
task webpackBuildDev(type: NpmTask, dependsOn: 'npm_install') {
  inputs.dir("src/main/webapp/")
  inputs.files(fileTree('src/main/webapp/')) 
  outputs.dir("build/www/")
  outputs.file("build/www/app/main.bundle.js")
  args = ["run", "webpack:build"]
}
```

**Comment by vleboulanger** [comment]
it works with this issue
