### ISSUE TITLE
User ImageUrl not getting set when login via Google Identity Provider through Keycloak

### ISSUE THREAD

**Issue by rakeshkalra1983** [jhipster/generator-jhipster#9383]
##### **Overview of the issue**

When login to website using Google Identity Provider configured via Keycloak, not getting image of person.
I am able to login to website, and User's firstname and lastname is getting initialized fine, just that image is not getting setting.

If you think this is not Jhipster issue, can you please provide some hint or what could be wrong?

##### **Reproduce the error**

Configure Jhipster app with Keycloak and configure Google Identity provider on Keycloak. Jhipster supports a variable image_url on user object, but it is getting initialized null.

##### **JHipster Version(s)**

 5.7.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.test"
    },
    "jhipsterVersion": "5.7.0",
    "applicationType": "monolith",
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

MacOS, Chrome

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
This seems to be more of a Keycloak or IdP issue rather than a JHipster one. Maybe Keycloak provides a mapping you can do to convert from one property name to another?

**Comment by rakeshkalra1983** [comment]
Thanks Matt, for reverting back. Can you please help here, I am really stuck on this from long time, what to check where, what mapping to provide? I assumed this all to work as part of Jhipster setup, as we do get realm file which we use to setup keycloak with Jhipster.

**Comment by medimohammadise** [comment]
What is the result of this? Did you find any solution? I have the same issue.

**Comment by mraible** [comment]
@medimohammadise It's a low priority issue for me. I'd be happy to review/approve a pull request if someone has the time to test and fix.

**Comment by rakeshkalra1983** [comment]
@mraible @medimohammadise I didn't find any solution for this yet, I do see UserService.java have code to set imageUrl in User.java if coming from OIDC:

if (details.get("picture") != null) {
            user.setImageUrl((String) details.get("picture"));
        }

Its not coming from keycloak somehow. Even checked scope being used when calling google api which contains profile scope, which should get picture actually.

**Comment by mraible** [comment]
In that case, I think we should close this issue since it’s related to Keycloak, not JHipster.

**Comment by rakeshkalra1983** [comment]
Not sure though, I have limited knowledge in this context. Will be great if you can check.
Also could it be possible that jhipster-realm.json included with jhipster project, might have some scope of improvement to take care of this?

**Comment by pascalgrimaud** [comment]
@rakeshkalra1983 @medimohammadise : for me, it's not a JHipster bug. Our current option OIDC works well, as you can see in our CI builds.
It's more like a feature request, as you want to get picture from Google Identity Provider.

As Matt said, it's more related to Keycloak configuration with your identity provider, than something related to JHipster.

If you find some improvement which can be done to our configuration, your pull requests are welcome.
For now, as this ticket is opened since 2 months with very few comments, I don't think it is a "must have".
That's why I'm closing this ticket.
