### ISSUE TITLE
Gitlab-CI found error with generated .gitlab-ci.yml

### ISSUE THREAD

**Issue by xenogew** [jhipster/generator-jhipster#9391]
##### **Overview of the issue**

Pipeline just started, and then found `FATAL: file does not exist`. And don't have any clues about the `file` was referred.

##### **Motivation for or Use Case**

The file is fresh generated, and then I modified a bit on `chmod +x mvnw` for other error I found before on Google. But it's not related.

##### **Reproduce the error**

- Create project
- Run local server for first time
- Generate `.gitlab-ci.yml` and push to the repository
- Found error on log

##### **JHipster Version(s)**

5.8.2

##### **JHipster Version(s)**

```
my-project@0.0.0 C:\sandbox\my-project
`-- generator-jhipster@5.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.comp.proj",
            "nativeLanguage": "ja"
        },
        "jhipsterVersion": "5.8.2",
        "applicationType": "monolith",
        "baseName": "my-project",
        "packageName": "com.comp.proj",
        "packageFolder": "com/comp/proj,
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "postgresql",
        "prodDatabaseType": "postgresql",
        "searchEngine": "elasticsearch",
        "messageBroker": false,
        "serviceDiscoveryType": "eureka",
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "clientFramework": "angularX",
        "useSass": false,
        "clientPackageManager": "npm",
        "testFrameworks": ["gatling"],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "ja",
        "languages": ["ja", "en"]
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.21.0.windows.1

node: v11.10.1

npm: 6.9.0

##### **Browsers and Operating System**

Windows 10 (1809 update), Chrome, but the issue might not related.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
@xenogew Can you create a public sample repository on Gitlab with same error produced?

**Comment by xenogew** [comment]
@pmverma Sure, here [jHipster-Gitlab-CICD-failed](https://gitlab.com/w_nattasan/gitlabcibug)

**Comment by atomfrede** [comment]
Can you try the trick with making the wrappet executable? The fatal file not found doesn't fail the build. It tries to extract the cache which of course doesn't exist for a first build yet. But I will check later too.

**Comment by xenogew** [comment]
@atomfrede pardon, but I can't get your suggestion. Can you please describe more in specific command or method I need to do?

Does it related to JHipster cache I chose the choice, when first generated project?

**Comment by atomfrede** [comment]
No. I am talking about the gitlab ci cache. Give me a minute.

**Comment by pmverma** [comment]
I have forked and tested.
It is related to permission issue.
Have a detail look at log https://gitlab.com/pmverma/gitlabcibug/-/jobs/173964839

**Comment by atomfrede** [comment]
Exactly. The wrapper files are executable in our repository and I use gitlab ci a lot and it worked without any problems (for gradle). Has it something to do with using windows as client os (maybe it overwrites the executable flag?)

**Comment by pmverma** [comment]
@atomfrede As you can see there is no execute permission so I doubt even root can not run `./mvnw`.

**Comment by atomfrede** [comment]
You are right. Seen it too. Mh maybe something with the latest update of the ci runner infrastruture?

**Comment by atomfrede** [comment]
@xenogew Can you make the wrapper files executable via windows?

**Comment by atomfrede** [comment]
> Exactly. The wrapper files are executable in our repository and I use gitlab ci a lot and it worked without any problems (for gradle). Has it something to do with using windows as client os (maybe it overwrites the executable flag?)

Sorry I am wrong! the unix maven wrapper is not marked executable in our repository

**Comment by xenogew** [comment]
@atomfrede Apologize, but I don't get the meaning and the term of "make wrapper files executable", do you have any hint or link to let me understand?

**Comment by atomfrede** [comment]
Try `git update-index --chmod=+x mvnw` such that the file is marked as executable and commit & push to your git repository again.

**Comment by xenogew** [comment]
@atomfrede did it, but still same
[ci-cd after git update-index --chmod=+x mvnw](https://gitlab.com/w_nattasan/gitlabcibug/-/jobs/173970881)

**Comment by atomfrede** [comment]
Sorry, forgot to tell you to remove `chmod +x mvnw` from the `before_script` of your your gitlab ci config.

**Comment by atomfrede** [comment]
I see the build is running. Will check why the wrapper is not executable by default on another machine without my develop environment for jhipster.

**Comment by pascalgrimaud** [comment]
@atomfrede : it is not the 1st time we saw this issue. Maybe we can add some documentation at https://www.jhipster.tech/setting-up-ci/ ?

**Comment by atomfrede** [comment]
Yes will do it.

**Comment by atomfrede** [comment]
@pascalgrimaud should (or can) we make the generator call `git update-index --chmod=+x mvnw` at the end to make sure the wrapper is executable?

**Comment by pascalgrimaud** [comment]
I think it's a good idea, we can try
