### ISSUE TITLE
Add the main java application class to Sonarqube exclusions

### ISSUE THREAD

**Issue by RothAndrew** [jhipster/generator-jhipster#9408]
##### **Overview of the feature request**

Ignore the main java application class when evaluating test coverage in Sonarqube

##### **Motivation for or Use Case**

The main application class is typically ignored when evaluating code coverage due to it being very difficult or impossible to test.

##### **Related issues or PR**

PR incoming

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Closing this, after my comment: https://github.com/jhipster/generator-jhipster/pull/9409#issuecomment-485526982
But we can still discuss about it, if needed
