### ISSUE TITLE
Update jhipster-core version

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#9413]
Needed new version due to:
- #9368
- #8987 
- #9405

**Comment by DanielFran** [comment]
@MathieuAA I created this issue so we do not forget that is needed a new version due to those PRs.

**Comment by MathieuAA** [comment]
Okay, I'll release ASAP.

**Comment by MathieuAA** [comment]
Maybe not ASAP, this is a breaking change and I'd like to have something available for v4. Is there a "deadline" for v6?

**Comment by jdubois** [comment]
JHipster 6 beta release is getting close, is there anything I can do here? If it's just doing a release I can totally do it

**Comment by DanielFran** [comment]
https://github.com/jhipster/jhipster-core/pull/315 needs to be merged.

In fact @MathieuAA did not make a latest release including this this one because of https://github.com/jhipster/jhipster-core/pull/309 that has been merged and need SB 2.1.4 (see https://github.com/jhipster/generator-jhipster/pull/9341 for more details).

To resume, you can merge it and create the release since we are pretty closed to SB 2.1.4 in April 1.

**Comment by jdubois** [comment]
@DanielFran I just merged jhipster/jhipster-core#315 but I'm lost with #9341 - if that breaks everything, shouldn't we better rollback temporarily?

**Comment by DanielFran** [comment]
@jdubois If I understood correctly it was not possible yet to implement relations for couchbase (#9342).
So it should be OK to release it if we do not push the documentation....
For me it os OK for beta with it included, anyway the update to SB 2.1.4 is for next monday Apr-1 and we can confirm it is fixed.

**Comment by jdubois** [comment]
I can do a release today or in the next couple of days, @MathieuAA is that all good for you?

**Comment by MathieuAA** [comment]
Yep

**Comment by jdubois** [comment]
Thanks @MathieuAA - doing it right now!
