### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by codelano** [jhipster/generator-jhipster#9415]
`[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
You are running an incompatible version of Java. JHipster requires JDK 1.8`

I got this when trying to build new hipster project on Java 11. When do you plan to start supporting it?

**Comment by jdubois** [comment]
In the next release.
Here you need Java 8 to build but this runs on JDK 11 already.
