### ISSUE TITLE
I would like to add a description after name of choices of some modules.

### ISSUE THREAD

**Issue by xenogew** [jhipster/generator-jhipster#9419]
##### **Overview of the feature request**

At the step to choose TEST suite to be added into, I would like to ask if you can add more description after the name of each modules.

##### **Motivation for or Use Case**

When I first generate I want to do as simple as possible, but after I develop for a while, I recognize I need the choice the generator offered before, such as TEST suite which has Gatling, Cucumber, Protractor.

But it just write the name of each modules, so for the very newcomer of Javascript developer like me, I don't know what they is? What do it do? And then I know from the meanings later in [Create an App doc](https://www.jhipster.tech/creating-an-app/).

##### **Related issues or PR**

I has searched but not found, might be it's just a little optional feature.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Of course it will help. We have similar things for "other technologies" question.
@xenogew, Would it be okay for you to do a PR?

**Comment by xenogew** [comment]
@pmverma Do you mean I make a change as I want for the description stuff and create a PR to the repository?

**Comment by pmverma** [comment]
@xenogew If I am not wrong, you want to put a description like 

- Gatling (Performance tests - server side)
- Cucumber (Behaviour tests - server side)
- Protractor (Angular integration tests - client side)

Is that correct?
And sorry for confusing with "other technologies", actually just wanted to give you an example but you can see at many places in the generator code.

Yes, I meant the same as your regarding PR.

**Comment by pascalgrimaud** [comment]
Sure, it can be improved a little bit, but the prompt must be **short** for our users, that's why we can't add a full description of every technologies.

About other modules from marketplace, we can't put the full description: it would be really too long. You should go and read their documentation before choosing the option.

Let's close this for now, as I think all information are already in documentation: https://www.jhipster.tech/creating-an-app/
