### ISSUE TITLE
Change 'activeModal.dismiss' with 'activeModal.close' in deleting user

### ISSUE THREAD

**Issue by MooDySmiles** [jhipster/generator-jhipster#9421]
##### **Overview of the issue**
When accepting the deletion of a user, the modal closes rejecting the 'NgbModal.result' promise

##### **Motivation for or Use Case**
If I confirm operation in the modal popup, then I expect that the 'NgbModal.result' promise will be resolved

##### **Reproduce the error**
Generation of a project with Angular as client framework

##### **Suggest a Fix**
Change `this.activeModal.dismiss(true)` with `this.activeModal.close(true)` in `confirmDelete(login)` method

##### **JHipster Version(s)**
5.8.2

##### **JHipster configuration**
```
{
    "generator-jhipster": {
        "promptValues": {
            "nativeLanguage": "it"
        },
        "jhipsterVersion": "5.8.2",
        "applicationType": "monolith",
        "baseName": "user_management",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": "spring-websocket",
        "databaseType": "sql",
        "devDatabaseType": "postgresql",
        "prodDatabaseType": "postgresql",
        "searchEngine": "elasticsearch",
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "it",
        "languages": ["it", "cs", "en", "fr", "de", "sk", "sr", "es"]
    }
}
```

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
yes, it should be corrected. can you raise PR with changes or I can do when time permits

**Comment by MooDySmiles** [comment]
I've never done a PR before, but I can give it a try :wink:

**Comment by wmarques** [comment]
@MooDySmiles don't hesitate if you need help on your PR, you can read the Contributing guidelines here: https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md
