### ISSUE TITLE
Kubernetes Generator fail with ERROR! Copying template README-KUBERNETES.md.ejs

### ISSUE THREAD

**Issue by gaelgubian** [jhipster/generator-jhipster#9422]
##### **Overview of the issue**
Kubernetes Generator fail with this stack trace : 
```
⎈ Welcome to the JHipster Kubernetes Generator ⎈
Files will be generated in folder: kubernetes
√ Docker is installed

Found .yo-rc.json config file...

Checking Docker images in applications directories...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! Copying template README-KUBERNETES.md.ejs failed. [ReferenceError: node_modules\generator-jhipster\generators\kubernetes\templates\README-KUBERNETES.md.ejs:98
    96| <%_ } _%>
    97|
 >> 98| <%_ if (app.serviceDiscoveryType === 'eureka') { _%>
    99| ## JHipster registry
    100|
    101| The registry is deployed using a headless service in kubernetes, so the primary service has no IP address, and cannot get a node port. You can create a secondary service for any type, using:

i is not defined]
    at Environment.error (node_modules\yeoman-environment\lib\environment.js:157:40)
    at module.exports.error (node_modules\generator-jhipster\generators\generator-base.js:1488:18)
    at ejs.renderFile (node_modules\generator-jhipster\generators\utils.js:207:23)
    at tryHandleCache (node_modules\ejs\lib\ejs.js:254:14)
    at Object.exports.renderFile (node_modules\ejs\lib\ejs.js:482:10)
    at Object.renderContent (node_modules\generator-jhipster\generators\utils.js:203:9)
    at module.exports.template (node_modules\generator-jhipster\generators\generator-base-private.js:672:23)
    at module.exports.writeReadme (node_modules\generator-jhipster\generators\kubernetes\files.js:63:18)
    at Object.<anonymous> (node_modules\yeoman-generator\lib\index.js:418:27)
    at node_modules\run-async\index.js:25:25
Emitted 'error' event at:
    at Immediate.setImmediate (node_modules\yeoman-generator\lib\index.js:427:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
INFO! Deployment: child process exited with code 1
```
##### **Reproduce the error**
Create a new jdl file with kubernetes deployment.
ex : 
```
application {
    config {
        baseName myapp
        applicationType monolith
        prodDatabaseType postgresql
        nativeLanguage fr
        testFrameworks [protractor, cucumber, gatling]
        skipUserManagement false
    }

    entities * 
}


entity A {
    name String
}

paginate * with pagination

service * with serviceImpl

deployment {
  deploymentType kubernetes
  dockerRepositoryName "myrepo/"
  kubernetesServiceType LoadBalancer
  kubernetesNamespace mynamespace
  istio autoInjection
  istioRoute true
}

```
Run the generator : 
 jhipster import-jdl ./model/model.jdl

##### **Related issues**
none

##### **Suggest a Fix**
generator-jhipster\generators\kubernetes\templates\README-KUBERNETES.md.ejs:98
Replace
`<%_ if (app.serviceDiscoveryType === 'eureka') { _%>`
by
`<%_ if (serviceDiscoveryType === 'eureka') { _%>`

##### **JHipster Version(s)**

```
project@0.0.0 \src
`-- generator-jhipster@5.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "enableHibernateCache": true,
        "enableSwaggerCodegen": false,
        "enableTranslation": true,
        "jhiPrefix": "jhi",
        "languages": ["en", "fr"],
        "messageBroker": false,
        "nativeLanguage": "fr",
        "packageName": "com.mycompany.myapp",
        "packageFolder": "com/mycompany/myapp",
        "prodDatabaseType": "postgresql",
        "searchEngine": false,
        "serviceDiscoveryType": false,
        "skipClient": false,
        "skipServer": false,
        "testFrameworks": ["protractor", "cucumber", "gatling"],
        "websocket": false,
        "baseName": "",
        "applicationType": "monolith",
        "skipUserManagement": false,
        "jhipsterVersion": "5.8.2",
        "buildTool": "maven",
        "clientPackageManager": "npm",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "clientFramework": "angularX",
        "serverPort": "8080",
        "useSass": true,
        "jwtSecretKey": "",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": []
    },
    "entities": ["Project", "Document", "ProjectBranch", "DocumentBuild", "SourceReader", "DocumentProcessor", "DocumentWriter"]
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.5

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

**Comment by amatosg** [comment]
shouldn't it be disabled then? 🙄

**Comment by pascalgrimaud** [comment]
We don't have a full real CI for Kubernetes, but we can add `npm test` for that.

**Comment by PierreBesson** [comment]
The error in the template rendering doesn't apply to v6. However the kind of JDL that was provided is not supported at the moment and cause an error. When declaring apps and deployement at the same time, it only works with at least 2 applications and the appsFolder field.
