### ISSUE TITLE
[Kubernetes] Logging format

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#9428]
Kubernetes expects the application services to log output to stdout stream by default and provide documentation how should be then transfered the logs for observability.

Since we use elk for logging, to allow better integration we shoudl expose logs in json format.

My proposition would be for Production environment to wrote directly in stdout the logs in json format.

I can provide a PR with the necessary changes if needed.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@PierreBesson Do you think this is something usefull that should be integrated in jhipster?

**Comment by PierreBesson** [comment]
The logback-logstash-appender already report logs in JSON format and send the logs directly to logstash.

Of course you can retrieve logs in a different way for example by plugging into the kubernetes logging driver. I guess in this case having the logs as JSON is a possibility. We could ship with an optional configuration to do it.

Oh and I see that the logstash-logback-endoder now support JSON formatting for all use cases and not just for reporting to a socket (https://github.com/logstash/logstash-logback-encoder/blob/master/README.md#usage).
This is super useful as it will handle complex cases like multi-line logs.

**Comment by DanielFran** [comment]
@PierreBesson Yes, the changes I wanna to propose is only to change logback file with the necessary changes in the appender to a format like:
_{"@timestamp":"2019-03-13T11:50:23.706+00:00","@version":"1","message":"The following profiles are active: dev,swagger","logger_name":"i.r.e.s.e.MyApp","thread_name":"restartedMain","level":"INFO","environment":"dev","application":"myApp","nested":{"customRawMessage":"The following profiles are active: dev,swagger","id":"2f950494-4586-11e9-be70-00c0f03d5b7c"},"sequenceNumberField":1,"context":"default"}_

**Comment by PierreBesson** [comment]
No the problem with the logback file is that it is always enabled which some people might not want.
You need to add the conf to LoggingConfiguration (as java code) configurable with a property so the feature can be enabled/disabled with env variables... This way we can enable it for the Kubernetes subgen without impacting other people.

**Comment by DanielFran** [comment]
OK, will investigate, otherwise I have it working changing logback file.
But I like your new approach!
Will then do a PR when I have something to show.
Thanks

**Comment by PierreBesson** [comment]
Great looking forward to review it.

**Comment by DanielFran** [comment]
@PierreBesson PRs are ready for review.
