### ISSUE TITLE
bower_components included in JAR

### ISSUE THREAD

**Issue by imduffy15** [jhipster/generator-jhipster#943]
The bower_components directory is included in the final JAR. There is no need for this to be the case as far as I'm aware. All resources have been concatenated and minified up and placed into dist/ where they will be served from thus keeping these sources around a little pointless.

Leaving bower_components in the JAR results in a pretty overhead in terms of size.

**Comment by jdubois** [comment]
No, this is on purpose: the final war can also run in "dev" mode, for debugging it.
This can be discussed (this is a more of a compromise, I don't think this is such a great idea)  but this is not a mistake.

**Comment by imduffy15** [comment]
worth while having a production only JAR?

**Comment by jdubois** [comment]
Not sure.
Pro: it would be smaller
Con: you couldn't use the same file for dev/test/prod
And I want to keep the workflow as simple as possible, so it's easier to have a JAR that does everything
