### ISSUE TITLE
Empty jhiPrefix leaves an underscore

### ISSUE THREAD

**Issue by developpef** [jhipster/generator-jhipster#9430]
##### **Overview of the issue**

In .yo-rc.json, set jhiPrefix option to empty string "". Attributes in generated entities keep an "_" as prefix...

##### **Motivation for or Use Case**

Avoid jhi prefix generation.

##### **Reproduce the error**

See overview

##### **Suggest a Fix**

If empty jhi prefix is set, do not generate any prefix, even "_".

##### **JHipster Version(s)**

INFO! Using JHipster version installed locally in current project's node_modules

INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
t-back@0.0.0 
`-- generator-jhipster@5.8.1

```
##### **Environment and Tools**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.16.1.windows.1

node: v8.11.3

npm: 6.7.0

yeoman: 2.0.5

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Windows 7 pro

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
Hi @developpef 
I'm not sure it's a good idea since prefix has been added to prevent some problems about using reserved names in tables names.

It's the case for User (I think). If you remove the whole prefix your database will raise an error. "User" as table name is not allowed.

**Comment by murdos** [comment]
The problem is that JHipster considers a lot of word as reserved names. Even "label".
I think we should support empty prefix as an advanced usage, maybe with a warning, and let users assume if they have errors with the generated code.

**Comment by developpef** [comment]
Hi,
I agree with @murdos point. My case is that even "start", "to" (column names) and so on are considered reserved...
A simple warning would be OK for me.
