### ISSUE TITLE
mapstruct alternative for DTOs

### ISSUE THREAD

**Issue by developpef** [jhipster/generator-jhipster#9431]
##### **Overview of the issue**

MapStruct library is incompatible with Hibernate lazy loading (as discussed here https://github.com/mapstruct/mapstruct/issues/778). But DTO concept (and mappers) are a must have in complex applications. But in JDL, if "dto * with mapstruct" is commented, all Mappers and DTO are deleted from generated sources... 

##### **Motivation for or Use Case**

DTOs and Mappers are really useful for complex applications.

##### **Suggest a Fix**

It should exist a way to generate DTOs and Mappers without MapStruct (with alternative library or no library at all).

##### **JHipster Version(s)**

INFO! Using JHipster version installed locally in current project's node_modules

INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator
JHipster Version(s)

t-back@0.0.0 
`-- generator-jhipster@5.8.1

Environment and Tools

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.16.1.windows.1

node: v8.11.3

npm: 6.7.0

yeoman: 2.0.5

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Windows 7 pro

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
No time to read the linked ticket at the moment, but I can guarantee you MapStruct totally works with Hibernate and lazy loading. I'm doing this all the time and there's nothing specific in fact. You just load your relationships inside the transaction.

**Comment by developpef** [comment]
The problem is not that we cannot load lazy entities, the problem is that intentionally not loaded entities (the point of lazy loading) are loaded by the mappers...

**Comment by jdubois** [comment]
If you don't want the relationship then you shouldn't map it

**Comment by developpef** [comment]
I wan't it, but only when I decide to load it

**Comment by jdubois** [comment]
In that case you can't use a DTO, just use the entities directly within a transaction. 
BTW we disable the open session in view pattern as we believe it causes too many issues but you might like that option.

**Comment by PierreBesson** [comment]
I agree with Julien here, Lazy loading does work correctly with Mapstruct but obviously as soon as you map the values from the entity to the DTO they need to be loaded from Hibernate. For me this is a feature as it prevents the LazyInitializationException.

Also see this resource on open Session In view: https://vladmihalcea.com/the-open-session-in-view-anti-pattern/

**Comment by developpef** [comment]
You are fast in closing issues... Let me try to explain a last time the use case : 

Data model is complex, EntityA could be linked to thousands of EntityB. 
For performance issue, when we display a summary list of EntityA, I don't want to load thousands of EntityB for each EntityA... But when user enters EntityA's edit form, I have to load all its related EntityB.

I have an API like "/api/entitiesA?complete=true|false" to choose whether I need to load all the EntitiesB or not depending on where user is in website.

There is absolutely no relation with Hibernate open session or transaction...

FYI, I managed to do it with "manual" mappers that do check : 

`// check Hibernate.isInitialized to avoid triggering lazy loading if property has not been loaded explicitly
        if (Hibernate.isInitialized(entityA.getEntitiesB())) {
            entityADTO.setEntitiesB(entitiesBMapper.toDto(entityA.getEntitiesB()));
        }`

**Comment by atomfrede** [comment]
Sound resonable, but I also don't consider it as jhipster issue. I even would create custom special api endpoints to serve this purpose instead of doing something like `incomplete` or `embedd`.

**Comment by jdubois** [comment]
I'm sorry but your ticket said: "MapStruct library is incompatible with Hibernate lazy loading", and that's wrong, and this wouldn't be a JHipster bug.

For your use case I would do like @atomfrede indeed. Please note we have the concept of "VM" (View Model) for this.

**Comment by developpef** [comment]
My initial question was to ask if it would be possible for JHipster to use an alternative to MapStruct or no library at all (and generate raw DTOs and Mappers).

**Comment by jdubois** [comment]
Oh then no, we'll not move away from MapStruct. It works really well, except maybe for the annotation processor that needs to be configured in IDEs. And feedback on MapStruct is usually extremely positive. 
Also, moving away from it would be an enormous amount of work.

**Comment by deepu105** [comment]
Also please note that we won't be able to support every usecase out there
and there is only so much combination we can support. I suggest you
generate with DTO and rewrite the ones where you want lazy loading from
mapstruct to what you like. We are sorry that we have to reject the request.

**Comment by hdurix** [comment]
Your use case is classic. But I think it's really linked to your business: sometimes you want to have some attributes (lazy loaded relations or direct attributes -> BLOB, ...), and JHipster could not know what the user wants, so the generated code should be modify to answer better the business needs.

I'm not a mapstruct expert, but for me, you could have different ways to map each entity: something like `complete`, `withFooRelation`, `summary` depending on what you want in your API, by specifying `@Mapping` [annotation](https://github.com/jhipster/jhipster-sample-app-dto/blob/master/src/main/java/io/github/jhipster/sample/service/mapper/BankAccountMapper.java#L19) in the mapper and avoid Lazy loading.
