### ISSUE TITLE
please consider provide a mechanism to override jhispster dependencies 

### ISSUE THREAD

**Issue by yudar1024** [jhipster/generator-jhipster#9433]
##### **Motivation for or Use Case**

we use mongodb 4 and need use the ACID transaction. but jhipster 5.x still in spring boot 2.0.x. the mongodb related dependencies version is low can not support the transaction feature. we want upgrade some dependencies to make it available. but the modification of pom doesn't effect the dependencies of project. all these dependencies is in jhipster-dependency pom. it can not be override.  so the upgrade is be blocked.  and jhipster 6 seems still need long time to release.
can team consider provide a way to override the dependency version

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
It's not blocked, we just provide a bill of materials and you can override it the way you want.
In fact, it's made to be overriden.

**Comment by yudar1024** [comment]
> It's not blocked, we just provide a bill of materials and you can override it the way you want.
> In fact, it's made to be overriden.

how？ do you mean modify jhipster-dependency pom directly?  that's need every project memeber modify their local pom in maven local repository, or copy the jhipster-dependency pom dependencies element content to project pom?

**Comment by jdubois** [comment]
You modify your pom.xml directly, or do your own BOM which inherits from the one from JHipster... Our BOM inherits from the Spring Boot BOM so it's exactly the same way as with a normal Spring Boot app.

**Comment by pascalgrimaud** [comment]
We do the same as normal Spring Boot, so for me there is no bug here.
Let's close this.
