### ISSUE TITLE
incorrect webpack proxy config when using capital letters in the project name

### ISSUE THREAD

**Issue by amrnablus** [jhipster/generator-jhipster#9435]
##### **Overview of the issue**

Simply generate a new microservice project and name it something like demo**M**icroservice, when generating an entity from the microservice gateway the proxy will be named demo**m**icroservice

all the requests to the APIs from demoMicroservice will be 404
##### **Reproduce the error**

- Create a microservice application with a capital letter in the name
- generate any entity -demo-
- create a microservice gateway
- inside the gateway, run jhipster entity demo
- select "Do you want to generate this entity from an existing microservice?" => Y
- chose the demoMicroservice created earlier
- observe "webpack/webpack.dev.js", it will have a proxy entry named "demomicroservice" with a small m
- try to call the entity API, note that you'll get a 404 

##### **Suggest a Fix**

If someone can point me to the part of the code (or documentation, depending on how we decide to fix it) I would happily do.

##### **JHipster Version(s)**

5.8.2
##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by amrnablus** [comment]
P.S: sorry seems i forgot to mention i'm running linux mint 19, I think the issue won't happen on macOS or windows since the directory names are not case sensitive.

**Comment by ruddell** [comment]
Without your config, we can't reproduce the issue easily.  In the upcoming v6, the webpack dev proxy paths for microservices are no longer generated as we use HTML5-mode (no # in URL).

Also note that directory names don't have anything to do with the Zuul routes, it's based off the app's registration in your service discovery choice (default is JHipster Registry).

The Zuul routes should all be lower-cased as well (configured in application.yml linked below).  You can verify this is working correctly by checking http://localhost:8080/#/admin/gateway which will list the available routes.  

The places the microservice name can be found:
 - [`application.yml`](https://github.com/jhipster/jhipster-sample-app-microservice/blob/dbe28d29708f56ab63b3481526e39a97f955bc5d/src/main/resources/config/application.yml#L27) `eureka.instance.appname` config sets the Zuul proxy route
 - [`webpack/webpack.dev.js`](https://github.com/jhipster/jhipster-sample-app-gateway/blob/ea594b734e0d1319fa437eb47eba36048c3ed6fa/webpack/webpack.dev.js#L22) proxy (removed in v6)
 - Entity's [`service.ts`](https://github.com/jhipster/jhipster-sample-app-gateway/blob/ea594b734e0d1319fa437eb47eba36048c3ed6fa/src/main/webapp/app/entities/jhipsterSampleMicroservice/bank-account/bank-account.service.ts#L14) file (Angular)
 - Entity's [`reducer`](https://github.com/jhipster/jhipster-sample-app-react/blob/586d4c6f49e74525825c3c10ffbb1f2f5528bb43/src/main/webapp/app/entities/bank-account/bank-account.reducer.ts#L98) file (React, this sample is a monolith so doesn't have MS name)

**Comment by amrnablus** [comment]
@ruddell That's weird, i was sure i pasted my config! let me add it again as an attachment.

**Comment by amrnablus** [comment]
[jhipster_demo.zip](https://github.com/jhipster/generator-jhipster/files/2974496/jhipster_demo.zip)
Here's a fully working reproduction of the bug (i removed the node_modules tho). 

If you run the two apps, you will notice that the service url for the demo entity from the microservice gateway is "http://localhost:8080/jhipster**ms**/api/demos" while it should actually be "http://localhost:8080/jhipster**MS**/api/demos"
I traced the problem and it is a jhipster issue, if i change the config inside the generated webpack config everything works perfectly.

**Comment by ruddell** [comment]
One possible fix is to add a config value `spring.cloud.consul.discovery.service-name` equal to the lower-cased `baseName`.  Similar to [what we do for Eureka](https://github.com/jhipster/generator-jhipster/blob/8fbeb75951b0b1f573aa2d7e99918d07d3f10fed/generators/server/templates/src/main/resources/config/application.yml.ejs#L46-L47), but further down [in the same file](https://github.com/jhipster/generator-jhipster/blob/8fbeb75951b0b1f573aa2d7e99918d07d3f10fed/generators/server/templates/src/main/resources/config/application.yml.ejs#L172).

That should make the routes accessible on the lower-cased URL that is used everywhere else in the generated code.

**Comment by amrnablus** [comment]
Can't we just have the proper casing inside webpack/webpack.dev.js?

**Comment by PierreBesson** [comment]
Seriously the project name should not be in uppercase. Then it is our mistake of forgetting to force lowercase at some point. I'm personally against having uppercase in the default route names. So we should go with @ruddell's solution to do the same thing for consul as we do for Eureka.

@amrnablus Also please respect the guidelines and paste the .yo-rc.json file in your issue description. It has already cost time for @ruddell because he as not aware that you used Consul (an unusual non default option !). We are not paid to work on JHipster, support is done because of our good will. Thanks for understanding.

**Comment by amrnablus** [comment]
@PierreBesson I very much thank your contribution and I think jhipster is amazing, and I did provide a full working reproduction of the issue in my previous comment.
That said, what do you suggest as a replacement for the capital letters in a project name? If using "_" or "-" could fix the issue at the moment I can just switch to that assuming it doesn't cause other issues

**Comment by PierreBesson** [comment]
@amrnablus you should be able to apply the fix I did in my PR. Note that this must be done in all your apps. Thanks @rudell for the analysis !

I would say that uppercase chars are valid as jhipster app names. But I don't really like the possibility of having underscore or dashes in the app name. I'm going to check that we do validation against that.
