### ISSUE TITLE
Unnecessary old integration tests files are not being cleaned up

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#9440]
##### **Overview of the issue**

Upgrading an app from v5 to v6(master branch) does generate new integration tests files. Then old integration tests files should be deleted.

##### **Motivation for or Use Case**

When upgrading from v5 to v6, having two duplicate files for IT tests is unnecessary.

##### **Reproduce the error**

- Generated an app using 5.8.x
- Regenerate using current master branch
- You can see both old and new files for IT tests.

##### **Related issues**

#8868 #9174  

##### **Suggest a Fix**

Add old files in cleanup.js to remove during clean up process. Moreover, old files for entities are also required to be cleaned up.

##### **JHipster Version(s)**

```
filter@0.0.0 /Users/sierra/github/pmverma/filter
└── generator-jhipster@5.8.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "filter",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.17.2 (Apple Git-113)

node: v10.14.2

npm: 6.7.0

yeoman: 2.0.5

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
What if the user has modified manually some tests in these old integration tests?

**Comment by pmverma** [comment]
Normally JHipster regenerates them anyway during upgrade but do not delete them. So yes, we also need to consider that part. It would be nice if we have some data from users.

**Comment by pascalgrimaud** [comment]
I think it's not a good idea to delete old integration tests.
The users who upgrade to JHipster v6 need to take care about that, and it will probably be manually.
