### ISSUE TITLE
Login via OIDC takes you back to home page

### ISSUE THREAD

**Issue by caffeinecoders** [jhipster/generator-jhipster#9446]
##### **Overview of the issue**

I have created Jhipster app using v 5.7.2 and using Keycloak along with it. When any of page on app requires login, it takes you back to home page after login instead of being coming back on the same page.

##### **JHipster Version(s)**

v5.7.2

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.thinkscholar"
    },
    "jhipsterVersion": "5.7.2",
    "applicationType": "monolith",
    "baseName": "thinkscholar",
    "packageName": "com.thinkscholar",
    "packageFolder": "com/thinkscholar",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

MacOs, Chrome

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
I assume this is related to OIDC configuration, no ?

Does something like `http://myUrl/*` should work.

**Comment by vishal423** [comment]
Its an issue with client side code. I will soon patch fix

**Comment by avdev4j** [comment]
Does it related to "#" in the URL ? 
Because there is some work done about that recently

**Comment by rakeshkalra1983** [comment]
@vishal423 can you please update me with the correction, what needs to be fixed where?

**Comment by vishal423** [comment]
@rakeshkalra1983, `UserRouteAccessService` guard also checks the user identity (used in private routes to authorize access). If it can't find in-memory user identity, it stores the current url in session storage and redirect to OIDC for authentication. 

To fix current issue, post **successful** authentication, you need to retrieve the stored url from session storage and navigate to that. There is similar code available for other authentication types (JWT/UAA), however, that code lacks capability to handle query params. I may find sometime later today and/or tomorrow and will try to provide fix
