### ISSUE TITLE
Alerts not coming when setting alertAsToast as true

### ISSUE THREAD

**Issue by caffeinecoders** [jhipster/generator-jhipster#9447]
##### **Overview of the issue**

Alerts doesn't appear at all when setting alertAsToast in app.module.ts in v5.8.2

##### **Reproduce the error**

Download jhipster-sample-app, set alertAsToast value to true in app.module.ts. 
Start the application and update any entity, you will not see any success alert.

##### **JHipster Version(s)**

v5.8.2

##### **Browsers and Operating System**

MacOs chrome

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by JinnaBalu** [comment]
Can you provide the git repo or yo-rc.json file for reproducing the same error? Your steps are not according to the guideline.

**Comment by rakeshkalra1983** [comment]
Kindly use jhipster sample app only present here: https://github.com/jhipster/jhipster-sample-app and then turn set alertAsToast value to true in app.module.ts.

**Comment by pascalgrimaud** [comment]
I confirm the bug.
Setting `alertAsToast` to true, doesn't work.
