### ISSUE TITLE
Use JRE instead JDK image for docker.

### ISSUE THREAD

**Issue by soberich** [jhipster/generator-jhipster#9448]
Currently used tag is `openjdk:11.0.1-slim-stretch` which is JDK not JRE
All `...-slim-stretch` are JDKs and to get JRE it needs to be `...-jre-slim-stretch`
I won't follow you guidelines for this kind of tiny issues, so, just close it with "does not comply.." but at least you read this and you know about the issue, so, you can fix it. 
Yours respectfully.

**Comment by atomfrede** [comment]
I think thats a valid point in order to keep our images small. For running an application a jdk is not needed.

**Comment by wmarques** [comment]
@soberich Yes you are right, jdk is not necessary to run the server.
Are you willing to do a PR on this ?

**Comment by PierreBesson** [comment]
As of JDK11, I have heard that the concept of JRE doesn't really exists anymore in JDK. 

https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html
>In this release, the JRE or Server JRE is no longer offered. Only the JDK is offered. Users can use jlink to create smaller custom runtimes.

However it seems that the openjdk image has a JRE version:
- `openjdk:11.0.2-slim-stretch`: 474MB
- `openjdk:11.0.2-jre-slim-stretch`: 273MB

So I guess we can switch to the JRE version.
