### ISSUE TITLE
switching between two controller with in a single form

### ISSUE THREAD

**Issue by bipinkishore** [jhipster/generator-jhipster#945]
Hi,
I am new to the jhipster and I am really glad to work with this tool. But I had a requirement to store data into two different tables from single entry form. I can do this in angularjs app by using ng-controller with out using ngroute. But when I am using jhipster, I couldn't able to add ng-controller within the form(some fields) as it making disable the default controller of entity. Actually i had a plan to do this by adding two different entities say e1 & e2. And inserting the e2 form inside the e1 and based on need I need to switch between the controller. This requirement is similar to changing the controller based on its state. your help will be really appreciated. 
thanks

**Comment by jdubois** [comment]
For this kind of question, which is not a bug or a feature request, you should go to http://stackoverflow.com/questions/tagged/jhipster
