### ISSUE TITLE
Running mvnw with prod profile defaults to the dev,swagger profiles

### ISSUE THREAD

**Issue by gomesp** [jhipster/generator-jhipster#9457]
##### **Overview of the issue**

Using JHipster 5.8.2.

In order to determine if this could be just an user error, I have created a new monolith app using all the default answers. The chosen data sources were H2 and MySQL.

When I switch between the dev and prod profiles, the app will continue running in the dev,swagger profiles. 

I have initialised the app with the the following command: ```./mvnw -Pprod``` (as per https://www.jhipster.tech/profiles/).

Thanks for the help team.

##### **Motivation for or Use Case**

Profile switching is not working
##### **Reproduce the error**

* Create a new monolith app
* Only use the default answers (H2/MySQL as databases)
* Run ```./mvnw -Pprod```
* The log will output: 
```
----------------------------------------------------------
	Application 'profiletest' is running! Access URLs:
	Local: 		http://localhost:8080/
	External: 	http://192.168.1.24:8080/
	Profile(s): 	[swagger, dev]
----------------------------------------------------------
```

##### **JHipster Version(s)**

5.8.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "profiletest",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.8.2",
        "applicationType": "monolith",
        "baseName": "profiletest",
        "packageName": "profiletest",
        "packageFolder": "profiletest",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en"]
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.21.0

node: v11.10.1

npm: 6.7.0

yeoman: 2.0.5

yarn: 1.13.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities have been created.

##### **Browsers and Operating System**

macOS Mojave (10.14.3)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I can't reproduce with v5.8.2 on Mac.  Not sure what could cause it.
```
----------------------------------------------------------
	Application 'profiletest' is running! Access URLs:
	Local: 		http://localhost:8080/
	External: 	http://192.168.0.8:8080/
	Profile(s): 	[prod]
----------------------------------------------------------
```

**Comment by pmverma** [comment]
I have experienced this same error with one of my PR branch. I was not sure if I messed up something and I had to create a fresh new branch to work again properly.

**Comment by gomesp** [comment]
I removed all my development tools and reinstalled it from scratch. There was something buggered in my environment.
