### ISSUE TITLE
Using noI18n with a blueprint throw an exception

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#9459]
##### **Overview of the issue**
When we generate a new project with a blueprint and choose to not have i18n the generator throw an exception when generate files.

##### **Motivation for or Use Case**
Avoid the exception ;) and make possible to have both blueprint and noi18n.

##### **Reproduce the error**
Run `jhipster --blueprint myBlueprint` where myBlueprint is a known blueprint (previously linked with npm in dev mode). When the question `Would you like to enable internationalization support?` is asked choose "no".

When files are generates an exception is raised :
```Error: /Users/aviard/projects/jhipster-myBlueprint/generator-jhipster-myBlueprint/generators/languages/templates/src/main/webapp/i18n/en/home.json.ejs doesn't exist```

Of course JHipster is looking for i18n files in my blueprint instead of the main generator project.

We must load them from JHipster. 

##### **Related issues**
none

##### **Suggest a Fix**
In utils.js instead of use relative path to store the languages templates path use an abslolute one.

From
```
const LANGUAGES_MAIN_SRC_DIR = `../../languages/templates/${constants.CLIENT_MAIN_SRC_DIR}`;
```

To
```
const LANGUAGES_MAIN_SRC_DIR = `${__dirname}/languages/templates/${constants.CLIENT_MAIN_SRC_DIR}`;
```

Also remove `path.join(generator.sourceRoot(), filename)` when resolve the filename.

the whole called stack is:
generatorBase: copyTemplate() 
=> utils: copyWebResource() 
=> utils: replaceTranslation() or replacePlaceholders() or replaceTitle()
=> utils: geti18nJson()

##### **JHipster Version(s)**
5.8.2

##### **JHipster configuration**

> {
  "generator-jhipster-myBlueprint": {
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "debugVsCodeFolder",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZjdjZjdkMGRjZDVjMzNhYWNkYmRkNjZkMDFkYzUyYWJjNzU2MDYzMTEzMzA3YWJjYmQ4NTVlYWEyNTc3YmRhMGExZTE1N2I2Y2RlYmU3ZjBiNmM0Njc2ZmVlYTg1M2UzMTQ5ZjZiZjRjMmM2MjYwNTQxNjU4YzdiYmI3MWQ5NDk=",
    "useLogm": true,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "enableTranslation": false
  },
  "generator-jhipster": {
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "debugVsCodeFolder",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-myBlueprint",
        "version": "0.0.0"
      }
    ],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprint": "generator-jhipster-myBlueprint",
    "blueprintVersion": "0.0.0"
  }
}

##### **Browsers and Operating System**
Mac OS X

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@avdev4j : I don't understand well the issue.

For me, you shouldn't have this error `Error: /Users/aviard/projects/jhipster-myBlueprint/generator-jhipster-myBlueprint/generators/languages/templates/src/main/webapp/i18n/en/home.json.ejs doesn't exist` because no files from i18n folder should be copied, as you choose noi18n

And we don't have the issue in Vue.js blueprint

**Comment by avdev4j** [comment]
hi @pascalgrimaud 
it's not related to i18n template copying but placeholders replacement.

> generatorBase: copyTemplate()
=> utils: copyWebResource()
=> utils: replaceTranslation() or replacePlaceholders() or replaceTitle()
=> utils: geti18nJson()

We need to load the i18n json files to replace all keys by their values. It tried to load them from my blueprint folder instead of the main generator JHipster folder.

**Comment by pascalgrimaud** [comment]
Oh I see, maybe we don't have the issue with Vue.js because some methods are overrided:
https://github.com/jhipster/jhipster-vuejs/blob/master/generators/utils.js

**Comment by avdev4j** [comment]
I've seen this too. I've just tested with a new empty blueprint and I can't reproduce it. I need to find where it come from.
