### ISSUE TITLE
Shouldn't PersistentAuditEvent.auditEventDate be an Instant?

### ISSUE THREAD

**Issue by henri-tremblay** [jhipster/generator-jhipster#946]
Instead of a LocalDateTime.

Also, is there a reason with JodaTime is still used for Java 8?

**Comment by gzsombor** [comment]
Hibernate doesn't support it, yet : 
https://hibernate.atlassian.net/browse/HHH-8844

**Comment by henri-tremblay** [comment]
Sad, by reading the documentation, Jadira seemed to support it.

**Comment by jdubois** [comment]
Yes, and it would be annoying for us to have different types for Java 7 and Java 8

**Comment by henri-tremblay** [comment]
Note to myself: Never ask two questions in the same issue.

That's what I guessed for JodaTime. To have to support both. Just wanted to be sure.

What about the title? Shouldn't PersistentAuditEvent.auditEventDate be an Instant?
