### ISSUE TITLE
Strange behavior of service tests with angular: always passed but failed

### ISSUE THREAD

**Issue by clakech** [jhipster/generator-jhipster#9463]
##### **Overview of the issue**

When generating a project, angular services tests are green but this is fake news: whatever you expect in those tests, they stay green because this is a coding issue with RxJS stuff there

##### **Motivation for or Use Case**

Tests should not be OK when expectations are KO

##### **Reproduce the error**

git clone https://github.com/clakech/jhipster-fake-tests-sample
cd jhipster-fake-tests-sample
npm install
npm test

Sample failed tests are here: src/test/javascript/spec/app/core/user/user.service.spec.ts

The way existing tests manage async api call is not good. This is maybe because of the behavior of a new version of rxjs, not sure. (was working in v5, no more in v6)

##### **Suggest a Fix**

Here is a way to solve this: https://github.com/clakech/jhipster-fake-tests-sample/commit/c2d66ca977e9bc18bf2c1360ed74940fbc2955e9

This is a sampled test generated that is always ok:

```
it('should return User', () => {
                service.find('user').subscribe(received => {
                    expect(received.body.login).toEqual('user');
                });

                const req = httpMock.expectOne({ method: 'GET' });
                req.flush(new User(1, 'user'));
            });
```

This test is always OK even if it fails: see 'NOT USER'

```
it('should return User', () => {
                service.find('user').subscribe(received => {
                    expect(received.body.login).toEqual('NOT USER');
                });

                const req = httpMock.expectOne({ method: 'GET' });
                req.flush(new User(1, 'user'));
            });
```

This test is failing and it is normal to fail here: 

```
it('should return User OK', done => {
                service.find('user').subscribe({
                    next: received => {
                        expect(received.body.login).toEqual('NOT USER');
                    },
                    complete: () => done()
                });

                const req = httpMock.expectOne({ method: 'GET' });
                req.flush(new User(1, 'user'));
            });
```

This is how your tests may be generated to be OK for real reasons (not faked):
```
it('should return User OK', done => {
                service.find('user').subscribe({
                    next: received => {
                        expect(received.body.login).toEqual('user');
                    },
                    complete: () => done()
                });

                const req = httpMock.expectOne({ method: 'GET' });
                req.flush(new User(1, 'user'));
            });
```

##### **Browsers and Operating System**

```
jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster-fake-tests-sample@0.0.0 /Users/cyrillakech/Dev/jhipster-fake-tests-sample
└── generator-jhipster@5.8.2

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitCompany": "",
    "baseName": "jhipsterFakeTestsSample",
    "packageName": "io.github.jhipster.application",
    "packageFolder": "io/github/jhipster/application",
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "enableSwaggerCodegen": false,
    "messageBroker": false,
    "buildTool": "maven",
    "useSass": false,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "enableTranslation": false,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientFramework": "angularX",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "5.8.2",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "git-provider": "GitHub",
  "git-company": "clakech",
  "repository-name": "jhipster-fake-tests-sample"
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Sample {
  city String,
  stateProvince String
}

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)

git version 2.20.1

node: v10.15.3

npm: 6.9.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!
```
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
I have also seen this issue and wrapped my test function in `async()` function like below to solve this. However, I am not sure on why the current syntax doesn't work as it's following [angular documentation ](https://angular.io/guide/http#expecting-and-answering-requests) to test http client calls.

```
it('should return User', async(() => {
    service.find('user').subscribe(received => {
        expect(received.body.login).toEqual('NOT USER');
    });
    const req = httpMock.expectOne({ method: 'GET' });
    req.flush(new User(1, 'user'));
}));
```

**Comment by wmarques** [comment]
@vishal423 maybe because they're running with Karma and we use Jest

**Comment by ufwtlsb** [comment]
maybe because rxjs config useDeprecatedSynchronousErrorHandling is false,then expect throw use 
settimeout async called

**Comment by clakech** [comment]
Maybe yes. Good clue.

If yes, I would recommend to fix the code and not using this flag 😉

**Comment by vishal423** [comment]
I had quick look into `jest-preset-angular` service examples and they specify assertions in end https://github.com/thymikee/jest-preset-angular/blob/075498e9519f78607c0dbd69fce2b217d925b44e/example/src/app/service/hero.service.spec.ts#L80

We can try that to check if it works (also would be good to upgrade preset)

**Comment by wmarques** [comment]
@vishal423 yep let's try this. Do you want to do a PR on this ? I can work on it tomorrow if you want, we have our jhipster day at the office :)

**Comment by vishal423** [comment]
@wmarques, you can go ahead to try this out/upgrade
