### ISSUE TITLE
Not compile generated Monolithic application

### ISSUE THREAD

**Issue by rostendrixpoterentax** [jhipster/generator-jhipster#9465]
##### **Overview of the issue**

\src\main\java\*\*\web\rest\AuditResource.java

Error:(43, 98) java: incompatible types: org.springframework.web.util.UriComponentsBuilder cannot be converted to javax.servlet.http.HttpServletRequest

Error:(66, 98) java: incompatible types: org.springframework.web.util.UriComponentsBuilder cannot be converted to javax.servlet.http.HttpServletRequest

\src\main\java\*\*\web\rest\UserResource.java

Error:(150, 98) java: incompatible types: org.springframework.web.util.UriComponentsBuilder cannot be converted to javax.servlet.http.HttpServletRequest

##### **JHipster Version(s)**

v5.8.2

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "ru.flystaff",
      "nativeLanguage": "ru"
    },
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "flystaff",
    "packageName": "ru.flystaff",
    "packageFolder": "ru/flystaff",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "Mzk1YmJmOTU3NGRjMWU5YWVhMGExYmU4ZTlmZTkyNGI0OGExYzBmMGU0YjQwY2FkNDJlMmNkMGY4YzFkMTIzZDZjYTgyYmNlNDQwZjc0NjI2NGFlNTc1NzU1N2RmNGNjYWRkMWRlYzJiMDI4MTFlNDgyODVkMmEzYTBhNzBiMmI=",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "ru",
    "languages": ["ru", "en"]
  }
}

**Comment by cbornet** [comment]
I guess you're on master (you didn't mention it in the description). You need to clone and install the jhipster-dependencies locally.

**Comment by atomfrede** [comment]
Had the same problem yesterday but thought it was my local setup.

**Comment by atomfrede** [comment]
@cbornet thanks for the hint so maybe it was my local setup

**Comment by cbornet** [comment]
@jdubois would you have time to publish the dependencies snapshot ?

**Comment by rostendrixpoterentax** [comment]
> I guess you're on master (you didn't mention it in the description). You need to clone and install the jhipster-dependencies locally.

Yes. I cloned the JHipster project's master branch.

**Comment by jdubois** [comment]
@cbornet it's deployed!
I don't think this can be easily automated, as this must be signed with GPG - it's a trust issue, of course!
