### ISSUE TITLE
Jhipster uaa source code used more throw new Exception doubt

### ISSUE THREAD

**Issue by coderLinJ5945** [jhipster/generator-jhipster#9467]
##### **Overview of the issue**

uua source code when the interface returns, it is heavily used 'throw new Exception', but all I see in register is used 'return ResponseEntity' method. I have a question,why is it used in uaa 'throw new Exception'

##### **Motivation for or Use Case**

if (userDTO.getId() != null) {
            throw new BadRequestAlertException("A new user cannot already have an ID", "userManagement", "idexists");
            // Lowercase the user login before comparing with database
        } else if (userRepository.findOneByLogin(userDTO.getLogin().toLowerCase()).isPresent()) {
            throw new LoginAlreadyUsedException();
        } else if (userRepository.findOneByEmailIgnoreCase(userDTO.getEmail()).isPresent()) {
            throw new EmailAlreadyUsedException();
        } else {
            User newUser = userService.createUser(userDTO);
            mailService.sendCreationEmail(newUser);
            return ResponseEntity.created(new URI("/api/users/" + newUser.getLogin()))
                .headers(HeaderUtil.createAlert( "userManagement.created", newUser.getLogin()))
                .body(newUser);
        }

##### **Suggest a Fix**

 As far as I know, creating an exception takes a snapshot of the thread stack, which can be very time-consuming. I wonder why the uaa author wrote this?I really look forward to your time to answer the novice
The question of

##### **JHipster Version(s)**

5.7.0

**Comment by PierreBesson** [comment]
ping @xetys

**Comment by coderLinJ5945** [comment]
I found this author changed the way the 'return ResponseEntity' is used in the source code,but Jhipster generated uaa that had not been modified.
url:https://github.com/xetys/jhipster-uaa-setup/blob/master/uaa/src/main/java/com/mycompany/myapp/web/rest/UserResource.java

**Comment by PierreBesson** [comment]
@coderLin please paste your .yo-rc.json file in your issue description. As it stands it is not a valid issue and is at risk of automatic closing by the team. Thanks for understanding.

**Comment by coderLinJ5945** [comment]
I have the answer, I will close this question, thank you very much

**Comment by PierreBesson** [comment]
@xetys can you confirm that the code is fixed in the current master ?
