### ISSUE TITLE
Missing 8080 proxy for /protected

### ISSUE THREAD

**Issue by krmcbride** [jhipster/generator-jhipster#947]
Correct me if I'm wrong, but I think the following needs to be added to the Gruntfile proxies:

```js
{
    context: '/protected',
    host: 'localhost',
    port: 8080,
    https: false,
    changeOrigin: false
}
```

In development, without the proxy, requests for `authentication_check.gif` are not served by Spring, so never return a `401`.

**Comment by jdubois** [comment]
Which version are you using?

**Comment by jdubois** [comment]
- in v1 it's working
- in v2, which is our current focus, we don't have the "/protected" is not used anymore (it's still there, but it's an error, I'm going to remove it)
