### ISSUE TITLE
Rest endpoints for Jhipster server for tasks like creating apps, entities or importing jdl file

### ISSUE THREAD

**Issue by amalkurup** [jhipster/generator-jhipster#9480]
##### **Overview of the feature request**

Rest endpoints for jhispter server installed, so that we can trigger auto-generation of apps or entities from other applications

##### **Motivation for or Use Case**

Jhipster can be integrated with various internal applications

**Comment by PierreBesson** [comment]
@amalkurup Is this request concerning JHipster Online (https://github.com/jhipster/jhipster-online) ?
If it's the case then please it should have been opened on jhipster/jhipster-online. 

I think you mean that we should open the JHipster Online API publicly. This is actually planned so I'm closing this issue.

**Comment by amalkurup** [comment]
@PierreBesson it's not related to jhipster online. My case is, 

1. jhipster installed on an Ubuntu container

2. Instead of jhipster-cli, I need to expose the jhipster app/entity generation capability over rest API, so that external apps on some other docker container can access this rest API

**Comment by PierreBesson** [comment]
For running JHipster "as a service" we have already developed JHipster Online. It specifically exposes a REST API to generate apps and can return a zip file that you can download. Otherwise I don't understand what you want to do.

**Comment by amalkurup** [comment]
@PierreBesson Thanks for the pointer. 

One quick question - Does Jhipster-online provide all the capabilities of jhipster generator

**Comment by PierreBesson** [comment]
Not currently. It only supports app, entity and ci pipelines. However it is able to connect to github, gitlab and bitbucket.
