### ISSUE TITLE
Ability to run jhipster Docker image using another user than user 1000

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#9493]
##### **Overview of the feature request**
[Docker image 5.8.2](https://github.com/jhipster/generator-jhipster/blob/v5.8.2/Dockerfile) is creating a `jhipster` user with the default UID `1000` and defines this user by default when running the image.
I would want to be able to give an environment variable (or detect the target UID using the one of `/home/jhipster/app` when mounting the app volume) to change this UID.

##### **Motivation for or Use Case**
In order to launch reproducible scripts by my co-working team (when running `jhipster import-jdl` for example), I've created scripts that use the official `jhipster/jhipster:v5.2.8` Docker image.
The problem is that my current user UID is `1001` and not `1000`, so when launching `docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn jhipster/jhipster:v5.8.2 jhipster import-jdl ./my-app.jdl --force` for example, the running `jhipster` user with UID 1000 does not have the rights to create files in my application folder because it is created with my current user with UID 1001.

Today, I'm forced to do those kind of ugly scripts (which is long to boot by the way, due to the `chown` commands):
```bash
CURRENT_GID=`id -g`
CURRENT_UID=`id -u`
CHANGE_USER_CMD=""

if [[ "$CURRENT_GID" != 1000 ]]; then
    CHANGE_USER_CMD="$CHANGE_USER_CMD && sed -i s/:1000:/:$CURRENT_GID:/ /etc/group"
fi
if [[ "$CURRENT_UID" != 1000 ]]; then
    CHANGE_USER_CMD="$CHANGE_USER_CMD && sed -i s/1000:1000/$CURRENT_UID:$CURRENT_GID/ /etc/passwd"
fi
if [[ -n "$CHANGE_USER_CMD" ]]; then
    CHANGE_USER_CMD="$CHANGE_USER_CMD && chown -R jhipster:jhipster /usr/local/lib/node_modules /home/jhipster/{.bash*,generator-jhipster} && chown jhipster:jhipster /home/jhipster"
fi

docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn -u root jhipster/jhipster:$JHIPSTER_VERSION bash -c "set -x $CHANGE_USER_CMD && su -l jhipster -c 'cd app && $*'"
```

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by cbornet** [comment]
Have you tried to use [userns-remap](https://docs.docker.com/engine/security/userns-remap/)

**Comment by PierreBesson** [comment]
This userns-remap flag looks like a good solution. @anthony-o if you make it work for you. Could you contribute the solution to the docs ([jhipster/jhipster.github.io]( https://github.com/jhipster/jhipster.github.io))?

**Comment by anthony-o** [comment]
I can't because it is a setting that must be set for the whole `docker` daemon, I can't use this just as an argument to a specific `docker run`...
In order to avoid each time to do this, I build a specific Docker image like this: https://github.com/iorga-group/debattons/blob/master/scripts/docker-run-jhipster.sh
But I don't think it is a good practice, other Docker image like [MySQL one](https://hub.docker.com/_/mysql#running-as-an-arbitrary-user) for example allows the use of `--user` `docker run` argument to customize the running user UID...

**Comment by PierreBesson** [comment]
Just had a quick look at the code of the MySQL dockerfile and it seems their --user flag let's you switch the MySQL user and not the linux user. I could be mistaken as I went over it really quickly.

See https://github.com/docker-library/mysql/blob/a7a737f1eb44db467c85c8229df9d886dd63460e/8.0/docker-entrypoint.sh

**Comment by PierreBesson** [comment]
Taking a second look I'm really not sure about my previous statement. If you manage to make it work without breaking other use cases. A PR is welcome.

**Comment by anthony-o** [comment]
The idea would be I think, to create an image without jhipster user inside, and with the possibility that any user could use the installed nodejs & jhipster tools (without "chowning" the nodejs library if you will).
I'm not sure to have the time to look at it but if I have I will try to PR something...

**Comment by PierreBesson** [comment]
@anthony-o Do you plan to do a PR for this ? Otherwise I'm sorry but we will need to close the issue. I suggest you to either use JHipster directly or set up your own docker image for this.

**Comment by anthony-o** [comment]
@PierreBesson here it is

**Comment by pascalgrimaud** [comment]
@anthony-o : I commented your pull request. So it can't be merged like this:
- maybe it will resolve your own issue
- but it will broke too many use cases

The problem you described here looks like specific to your computer and your own Docker installation.

Our Docker image here is for very advanced users and is provided as example. As suggested by @PierreBesson, feel free to build your own Docker image. All our tags / releases are public, you can easily do it.

**Comment by anthony-o** [comment]
The fact that my user has not the UID 1000 is not at all specific to my computer!
Actually the current jhipster Docker image just can't work with another user that UID 1000, it's very problematic and not at all rare...
Anyway, I'll try to fix the image (and to fix the issue it will be necessarily big modifications to the current Dockerfile).
This issue I opened can affect for example people that try to create a CI/CD that would build a generated jhipster project on a server (often user is not UID 1000 in that case) and that don't want to install the tools required by jhipster to build directly on the server but want to run a jhipster image to build instead.

**Comment by pascalgrimaud** [comment]
The image `jhipster/jhipster` is used for our GitLab CI and Jenkinsfile.
The last time I tried, and it works very well.

The problem with your changes is it will break all these use cases :-(
I'm not against your proposal, if you can find a "good" solution without breaking our configurations.

**Comment by PierreBesson** [comment]
Let's close this issue and PR, as the proposed fix introduce too many breaking changes and the current image already works for most purposes.
Thank you @anthony-o for having given a shot at this !

**Comment by anthony-o** [comment]
> The problem with your changes is it will break all these use cases :-(

@pascalgrimaud I'm still having this issue, could you tell me exactly what are the use cases broken by my Docker image please so I can try to correct my PR?
