### ISSUE TITLE
Email : localized messages not found for Locale with country specified (zh-cn)

### ISSUE THREAD

**Issue by olivierdepriester** [jhipster/generator-jhipster#9494]
##### **Overview of the issue**
When emails are generated for a Locale when the country is specified, the messages are not translated in this locale.
It seems to be due to the "uppercasing" of the country attribute in the locale initialization :

```java
// user.getLangKey = zh-cn
Locale locale = Locale.forLanguageTag(user.getLangKey());
// locale.getLocale() = zh
// locale.getCountry() = CN 
```
##### **Motivation for or Use Case**

99% of my users are Chinese and 2% of them speak English :)

##### **Reproduce the error**

* Generate an app with English as default language and simplified Chinese as additional language
* Change the language of the "user" user account to simplified Chinese
* Reset "user" password
==> The email is in English 

##### **Related issues**
None found

##### **Suggest a Fix**

I finally fixed this simply by renaming my messages_zh_cn.properties to messages_zh_CN.properties.
Maybe the .properties could be generated directly like this.

##### **JHipster Version(s)**

5.8.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.demo.entity",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.8.2",
        "applicationType": "monolith",
        "baseName": "jhipTestIe11",
        "packageName": "com.demo.entity",
        "packageFolder": "com/demo/entity",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "no",
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Memory",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "clientFramework": "angularX",
        "useSass": false,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en", "zh-cn"],
        "enableHibernateCache": false,
        "entitySuffix": "",
        "dtoSuffix": "DTO"
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v10.15.3

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.12.3

Docker version 18.09.3, build 774a1f4

docker-compose version 1.22.0, build f46880fe

##### **Browsers and Operating System**

Ubuntu 18.04

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Thanks for the report, this is a really complex issue that I have already spent a lot of time on.
Please see this PR and discussion: https://github.com/jhipster/generator-jhipster/pull/6423

I don't remember all the details but this was related to the fact that the locale is of the form `zh-cn` in javascript (in the browser) and `zh_CN` in java. Currently the composed locales (eg. zh_CN are broken for emails).

If you are able to fix this in JHipster. You would have my eternal gratitude ! I'm still occasionally thinking about this bug :sweat: but I have no time or use case to invest my time in solving this.
We also would need to add some tests specifically for i18n emails to prevent regressions in the future.

**Comment by olivierdepriester** [comment]
I am still wondering how I missed #6423 :)

I have spent half a day on it but I think I have it. Here are the main points : 

- When creating message_*.properties, I change the created file name from xx-yy to xx_YY (if there is a-yy part of course). And this is done only for *.properties not for .json folder.  Thus : messages_zh_cn.properties.ejs ->messages_zh_CN.properties
- I fought with Uzbek languages that were a bit tricky because uz-cyr and uz-lat are not IETF-compliant. I have changed them to uz-Cyrl-uz and uz-Latn-uz and renamed the related json folders/entities
- I have changed the max size of User.langKey from 6 to 10 (uz-Cyrl-uz was too large)
- I have changed the LocaleId of UZ to uz-Cyrl and uz-Latn or it could not work as default app language (angular import in core.module.ts did not compile)
With this email and interface internationalization seem ok at least for monolithic app.

By the way UZ json folders are a bit messy : mix json.ejs and json files (ie : global.json.ejs with global.json). Not important for generation but messy :p

**Comment by PierreBesson** [comment]
Thanks a lot ! Those locales names are not standard at all. I can definitely provide a review later for your PR about the templates. It's probably some remnants of the our old templating code.

BTW I'm curious about the kind of project you work on. Could you contact me privately by twitter (pibesson) or email.

**Comment by olivierdepriester** [comment]
Aaargh !
I commit again : I forgot to remove a debug console,log

**Comment by PierreBesson** [comment]
Okay so I'm working on it and adding a test to validate that the app can send emails in all configured languages. And I'm finding new bugs everywhere.

The i18n inside java is definitely kind of crazy. From property file that normally only support ISO charsets to  the "id" locale silently converted to "in" (apparently "in" is a deprecated locale for indonesia, so why does it convert the new code to the old one !).

Here in `sun.util.localeLanguageTag.java` :
<img width="441" alt="Screenshot 2019-04-02 at 23 35 05" src="https://user-images.githubusercontent.com/513471/55437881-5b83bf80-55a0-11e9-9f15-f213b968cf74.png">

**Comment by jdubois** [comment]
This is definitely important & very complex: I'm adding a bug bounty on this

**Comment by olivierdepriester** [comment]
@PierreBesson You made a mistake : "in" is truly the deprecated but LanguageTag.parseLocale silently convert "in" into "id" so I guess it's ok
--> For Indonesian maybe it's just about changing "in" to "id" in the generator constants to solve the issue.

For those who want to fight with the topic, here is an XLSX file I made with what seems to be the reference
[LocaleISO.xlsx](https://github.com/jhipster/generator-jhipster/files/3038254/LocaleISO.xlsx)
Source :
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
referenced by :
https://www.w3.org/International/questions/qa-lang-2or3.en.html

**Comment by PierreBesson** [comment]
@olivierdepriester No it's worse than that, we correctly use the "id" locale but java converts it implicitly to "in" and try to load the messages_in.properties file.

**Comment by olivierdepriester** [comment]
I saw it after commenting. They have some code that translate "in" to "id" in a parseLanguage()method but the one used by forLanguageTag is parse(). I definitely love the guy who developed these classes

**Comment by olivierdepriester** [comment]
I have committed a change of the Indonesian locale from "id" to "in" (I have found comments from 15 years ago about this java issue so I guess it won't be solved right away). -> 997b5738ee8fbbc088ebd179a1b1ef147e494dc4

- The other light solution would have been to write a "if (langProp== 'id') { langJavaProp= 'in' } in the     installI18nServerFilesByLanguage method but I find this ugly.
- The heavy solution : split languages into client-languages and server-languages. I am not ready to 
start such a change ...

I also created a unit test about locales in a second commit to keep the change and not the test 763a136248521cd3dac0c7a0a1a72ec8f2e2c5f8

**Comment by PierreBesson** [comment]
Yes let's change "id" -> "in". It's the simplest.

**Comment by PierreBesson** [comment]
I found the OpenJDK bug (from 2006 !) labeled as `wontfix` for compatibility reason. This is infuriating 😡  https://bugs.openjdk.java.net/browse/JDK-6457127

**Comment by PierreBesson** [comment]
Note: I'm still on this issue and I am slowly making progress whenever I have the time.
