### ISSUE TITLE
Sonar support for JHipster 6

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#9495]
Our current Sonar analysis is pretty bad:

https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application

We have 3 different issues:

- [ ] Since we moved most of the unit tests to be integration tests, they are not covered anymore.
- [ ] The front-end tests are not analyzed anymore
- [ ] There is a new issue because of [this new rule](https://sonarcloud.io/organizations/default/rules?open=squid%3AS4684&rule_key=squid%3AS4684). It only exist (at the moment) on Sonar Cloud as we have the entreprise version there. This is indeed a potential bug, but it's the whole point of generating simple CRUDs, and I have seen many, many applications doing this as it's much easier to do it like that. And if you want to secure your code, doing stupidly a POJO will not make any difference -> for each situation, at some point you need to think about your code and secure it. So for me it's a false positive and I think we should exclude it. But indeed, there is a potential risk here that we do not document well enough - this is obvious for me, but as we have more and more junior people using JHipster, this won't be obvious for everyone.

**Comment by avdev4j** [comment]
All you need is here #9482 ;)

**Comment by jdubois** [comment]
Oh thanks @avdev4j -> closing this

**Comment by pascalgrimaud** [comment]
I'm reopening this, as our [sample](https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application) is still broken

**Comment by pascalgrimaud** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/9511
