### ISSUE TITLE
Upgrade to JUnit 5

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#9498]
##### **Overview of the feature request**

We should upgrade to JUnit 5 because it's the latest and greatest version of JUnit and JHipster is hip!

##### **Motivation for or Use Case**

Show Java developers the latest and greatest technologies.

##### How

For Maven, exclude `junit:junit` and include `junit-jupiter-engine`:

```xml
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

For Gradle:

```groovy
testImplementation ("org.springframework.boot:spring-boot-starter-test") {
    exclude module: "junit"
    exclude group: "com.vaadin.external.google", module: "android-json"
}
testImplementation "org.junit.jupiter:junit-jupiter-engine"
```

In .java files:

1. Replace `org.junit.Before` with `org.junit.jupiter.api.BeforeEach` (or `BeforeAll`, I'm not sure which)
2. Replace `org.junit.Test` with `org.junit.jupiter.api.Test`
3. Remove classes and imports no longer needed:
    1. `import org.junit.runner.RunWith;`
    2. `import org.springframework.test.context.junit4.SpringRunner;`
    3. `@RunWith(SpringRunner.class)`

I'm sure there's more, but this seems like the basics to get started.

**Comment by cbornet** [comment]
That would be great. I just hope all our test dependencies work with it. For instance I had issues on a project with the EmbeddedKafka. Testcontainers seems to have an extension.

**Comment by atomfrede** [comment]
We could also use the vintage engine first and migrate all tests step by step to junit 5

**Comment by PierreBesson** [comment]
I think it's better to do it in one go as users are going to be annoyed to have an app that is partially migrated between JUnit 4 and 5.

**Comment by atomfrede** [comment]
We should document how to run and use junit 4 tests, as e.g. spock currently still requires junit 4. Is someone working on this by the way already?

**Comment by mraible** [comment]
@atomfrede Is there a component that requires Spock in JHipster?

**Comment by atomfrede** [comment]
No there is not, so only a problem for users wanting to use it. So if no one is working on it yet I can do it.

**Comment by hdurix** [comment]
@atomfrede did you start to work on this? I'd be happy to do it, may I assign it to myself?

**Comment by atomfrede** [comment]
No nothing substantial. Just tried a sample app with junit 5 but nothing regarding the generator. So go ahead!

**Comment by hdurix** [comment]
Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/8820
