### ISSUE TITLE
Extending User with jpaDerivedIdentifier and Oauth2 id type mismatch

### ISSUE THREAD

**Issue by SUSTAPLE117** [jhipster/generator-jhipster#9499]
##### **Overview of the issue**
After generating the application using these settings, I firstly get this method in my SiteUserResource.java where in the following two lines, a String is tried to be assigned to a long and a long is being used in a String parameter.
 ```
   long userId = siteUser.getUser().getId();
   userRepository.findById(userId).ifPresent(siteUser::user); 
``` 
The complete method:
```
/**
     * POST  /site-users : Create a new siteUser.
     *
     * @param siteUser the siteUser to create
     * @return the ResponseEntity with status 201 (Created) and with body the new siteUser, or with status 400 (Bad Request) if the siteUser has already an ID
     * @throws URISyntaxException if the Location URI syntax is incorrect
     */
    @PostMapping("/site-users")
    public ResponseEntity<SiteUser> createSiteUser(@Valid @RequestBody SiteUser siteUser) throws URISyntaxException {
        log.debug("REST request to save SiteUser : {}", siteUser);
        if (siteUser.getId() != null) {
            throw new BadRequestAlertException("A new siteUser cannot already have an ID", ENTITY_NAME, "idexists");
        }
        if (Objects.isNull(siteUser.getUser())) {
            throw new BadRequestAlertException("Invalid association value provided", ENTITY_NAME, "null");
        }
        long userId = siteUser.getUser().getId();
        userRepository.findById(userId).ifPresent(siteUser::user);
        SiteUser result = siteUserRepository.save(siteUser);
        siteUserSearchRepository.save(result);
        return ResponseEntity.created(new URI("/api/site-users/" + result.getId()))
            .headers(HeaderUtil.createEntityCreationAlert(ENTITY_NAME, result.getId().toString()))
            .body(result);
    }
```
If I correct this method and then run the App I get an issue with liquibase because the id of User and SiteUser are of different types: 
```
liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20190324194135_added_entity_constraints_SiteUser.xml::20190324194135-2::jhipster:
     Reason: liquibase.exception.DatabaseException: ERROR: foreign key constraint "fk_site_user_user_id" cannot be implemented
  Detail: Key columns "id" and "id" are of incompatible types: bigint and character varying. [Failed SQL: ALTER TABLE public.site_user ADD CONSTRAINT fk_site_user_user_id FOREIGN KEY (id) REFERENCES public.jhi_user (id)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
	at liquibase.Liquibase.update(Liquibase.java:214)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:103)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:83)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
I know it is the oauth2 option that impacts this has it sets the User id to a String here:
https://github.com/jhipster/generator-jhipster/blob/917419bb2c86779834e6271fcbcbcec9087aef8f/generators/server/templates/src/main/java/package/domain/User.java.ejs#L116

##### **Motivation for or Use Case**

I would like to extend the User and use Oauth2 and OpenId Connect

##### **Reproduce the error**

Extending the User Entity with a jpaDerivedIdentifier and using Oauth2 

##### **Related Issues**

 Did not find one

##### **JHipster Version(s)**

```
 generator-jhipster@5.8.2
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "databaseType": "sql",
        "devDatabaseType": "postgresql",
        "enableHibernateCache": true,
        "enableSwaggerCodegen": false,
        "enableTranslation": true,
        "jhiPrefix": "jhi",
        "languages": ["en", "fr"],
        "messageBroker": false,
        "nativeLanguage": "en",
        "packageName": "com.mycompany.leprojet",
        "packageFolder": "com/mycompany/leprojet",
        "prodDatabaseType": "postgresql",
        "searchEngine": "elasticsearch",
        "serviceDiscoveryType": false,
        "skipClient": false,
        "skipServer": false,
        "testFrameworks": ["protractor"],
        "websocket": false,
        "baseName": "leProjet",
        "applicationType": "monolith",
        "authenticationType": "oauth2",
        "cacheProvider": "hazelcast",
        "buildTool": "gradle",
        "clientFramework": "angularX",
        "jhipsterVersion": "5.8.2",
        "skipUserManagement": true,
        "clientPackageManager": "npm",
        "serverPort": "8080",
        "useSass": true,
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": []
    },
    "entities": ["Store", "SiteUser", "Product"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
application {
  config {
    baseName leProjet
    applicationType monolith
    packageName com.mycompany.leprojet
    languages [en, fr]
    searchEngine elasticsearch
    serviceDiscoveryType no
    authenticationType oauth2
    prodDatabaseType postgresql
    devDatabaseType postgresql
    cacheProvider hazelcast
    buildTool gradle
    clientFramework angularX
    testFrameworks [protractor]
  }
  entities *
}

entity Store {
	name String required,
    description String required
}

entity SiteUser {

}

entity Product {
	name String required,
    description String required,
    price BigDecimal required,
    content Blob required,
    previewPicture ImageBlob,
    language Language required,
    audience String,
    subject String,
    environment String
}

enum Language {
	FRENCH,
    ENGLISH
}

relationship OneToOne {
	SiteUser{store} to Store
    SiteUser{user required} to User with jpaDerivedIdentifier
}

relationship OneToMany{
	Store{products} to Product{store}
}

relationship ManyToMany {
	SiteUser{purchasedItems} to Product{buyers}
}

deployment {
  deploymentType kubernetes
  dockerRepositoryName "******"
  serviceDiscoveryType no
  istio autoInjection
  istioRoute true
  kubernetesServiceType Ingress
  kubernetesNamespace leprojet
  ingressDomain "********"
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.21.0.windows.1

node: v10.15.1

npm: 6.4.1

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
@SUSTAPLE117 Thanks for reporting the issue. Actually I developed this part and am wondering that all the CI tests passed.
I will fix this soon.

**Comment by pmverma** [comment]
With OAuth2, id is `String` and JHipster currently support only `long` for its entities ids. And this will exactly results in type mismatch error as you have with liquibase error. 

In this case, the entity related to user should have `String` and `varchar2` as its datatype as oppose to `long` and `bigint`.

**Comment by SUSTAPLE117** [comment]
Thanks for your answer. I am using JDL, so I do not think there is a way to change the Id type of my entity extending User to Long, unless doing it manually?

**Comment by pascalgrimaud** [comment]
@pmverma : I'm adding a bounty on this as it was a lot of work to fix this ! Don't forget to claim it.
