### ISSUE TITLE
Use libsass instead of compass

### ISSUE THREAD

**Issue by azadorozhniy** [jhipster/generator-jhipster#950]
Hi! 
There is interesting idea to consider using libsass instead of compass it's like 5 times faster but if user has node env it's quite eas to switch. 

http://benfrain.com/lightning-fast-sass-compiling-with-libsass-node-sass-and-grunt-sass/

**Comment by jdubois** [comment]
It's a C/C++ lib, and we need to be cross platform, so unfortunately we can't use it.

**Comment by azadorozhniy** [comment]
It's basically nodejs library, that works across platforms. 
When you install libsass it complies across your platform.

**Comment by azadorozhniy** [comment]
http://foundation.zurb.com/forum/posts/11597-how-to-install-grunt-and-libsass-on-windows

**Comment by deepu105** [comment]
:+1:
