### ISSUE TITLE
Remove 'cc' profile from maven pom.xml

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#9500]
##### **Overview of the feature request**
As explained in https://github.com/jhipster/generator-jhipster/pull/9369#issuecomment-469292093, we can remove the cc profile from maven pom file

##### **Motivation for or Use Case**

There is no exact data available but it seems nobody is using that profile. Remove unnecessary code and keep clean the pom.xml.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
yes let's remove it, I don't think anybody uses it anyway

**Comment by PierreBesson** [comment]
Yes it also doesn't work for jdk11 as Scala doesn't support jdk11 yet.
