### ISSUE TITLE
Move maven dependency declarations from inside build tag to dependencies tag

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#9501]
##### **Overview of the feature request**

As per https://github.com/jhipster/generator-jhipster/pull/9369#issuecomment-469283608, it is suggested that dependency declaration should move from inside `<build/>` to `</dependencies>`

##### **Motivation for or Use Case**

This improvement will make pom.xml a little simpler and cleaner.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@pmverma : just to know, do you plan to work on this ?

**Comment by pmverma** [comment]
@pascalgrimaud I noted here so that this can be improved later. If there is none then I will work on this. I just need more time to take care of this.

**Comment by pascalgrimaud** [comment]
thanks, I assigned the ticket to you :)

**Comment by pmverma** [comment]
@pascalgrimaud after reading the documentation at 
https://maven.apache.org/pom.html#Plugins
```
The major difference in this case is that instead of applying as dependencies of the project, 
they now apply as dependencies of the plugin that they are under. 
```
So if we move deps declaration from build to under dependencies, those will be included during packaging unnecessarily.

I would like to close the issue. WDYT?

**Comment by pascalgrimaud** [comment]
Thanks for the analyze @pmverma
So yes, let's close this
