### ISSUE TITLE
Integrate Jhipster gateway with kubernetes or open shift service discovery instead of Jhipster registry

### ISSUE THREAD

**Issue by amalkurup** [jhipster/generator-jhipster#9515]
I am a novice to this awesome code generator framework called Jhipster

As I read through your docs, I see that Jhipster registry is a default and mandatory option for gateway angular application. 

Use case : If user want to opt for k8s discovery, instead of Jhipster registry, what all are the configuration changes needed

**Comment by pascalgrimaud** [comment]
There is already a ticket for that.
See https://github.com/jhipster/generator-jhipster/issues/9348

Don't hesitate to comment this ticket. 

I'm closing this, as duplicated
