### ISSUE TITLE
CSS fails to load at first time launch when using Compass

### ISSUE THREAD

**Issue by sgandon** [jhipster/generator-jhipster#952]
I have installed jhipster with the following parameters and install mongoDb on my Mac.
I have then run `mvn spring-boot:run`.
The appli is launching but the web page fails to load the main.css file at this url http://localhost:8080/styles/main.css
```
? (1/13) What is the base name of your application? testapp
? (2/13) What is your default Java package name? com.talend.testapp
? (3/13) Do you want to use Java 8? Yes (use Java 8)
? (4/13) Which *type* of authentication would you like to use? Token-Based Authentication (Oauth2)
? (5/13) Which *type* of database would you like to use? NoSQL (MongoDB)
? (6/13) Which *production* database would you like to use? MongoDB
? (7/13) Which *development* database would you like to use? MongoDB
? (8/13) Do you want to use Hibernate 2nd level cache? No (this not possible with the NoSQL option)
? (9/13) Do you want to use clustered HTTP sessions? Yes, with HazelCast
? (10/13) Do you want to use WebSockets? No
? (11/13) Would you like to use Maven or Gradle for building the backend? Maven (recommended)
? (12/13) Would you like to use Grunt or Gulp.js for building the frontend? Grunt (recommended)
? (13/13) Would you like to use the Compass CSS Authoring Framework? Yes
```

**Comment by sgandon** [comment]
you are absolutly right. 
I suggest to convert this to a feature request in order to improve the first time launch.
Thanks for your answer.

**Comment by jdubois** [comment]
Yes, it's "how it's supposed to work", but I agree it's not intuitive at all.

I'm not sure we can force "grunt compass" after build, if you have an idea...

**Comment by andidev** [comment]
Maybe possible with [Grunt Maven Plugin](https://github.com/allegro/grunt-maven-plugin)? Not sure if you can set which task to run though.

**Comment by andidev** [comment]
Another alternative is to execute the yeoman-maven-plugin which is executed in the prod profile. But this will make the startup really slow cause it does more than just grunt compass. I guess thats why the plugin is not added to the dev profile at the moment?

**Comment by jdubois** [comment]
@andidev yes I guess that's why we didn't do it at the first time.

I guess that if people want to use Compass, they should know they need to install Compass & run it -> maybe it's more of a documentation issue?
Of course I'd rather have everything automated, it would be cleaner.

**Comment by andidev** [comment]
Agree.

It seems that the there is a solution that is fast. Adding the following to the plugin execution to the dev profile seems to work.
```xml
<plugin>
    <groupId>pl.allegro</groupId>
    <artifactId>grunt-maven-plugin</artifactId>
    <version>1.5.0</version>
    <configuration>
        <gruntOptions>
            <gruntOption>compass:server</gruntOption>
        </gruntOptions>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>grunt</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

It's fast since it only executes the compass task.

Should I create a PR?

**Comment by jdubois** [comment]
OK, but as we already have the yeoman-maven-plugin I'd like to avoid having a second Maven plugin that run Grunt tasks... I don't know if that's do-able with yeoman-maven-plugin, thus

**Comment by andidev** [comment]
I agrre but unfortunately it is not possible to use the yeoman-maven-plugin for executing specific grunt tasks. Yeoman Maven Plugin runs
```
            npmInstall();
            bowerInstall();
            grunt();
```
in it's build goal

Maybe it is possible to replace the Yeoman Maven Plugin with the Grunt Maven Plugin? Should I look inte that?

**Comment by jdubois** [comment]
If the Grunt Maven Plugin can do the npm install and the bower install, but when I chose the Yeoman Maven Plugin, more than 1 year ago, it was the only one which could do it.

**Comment by andidev** [comment]
Seems that Grunt Maven Plugin can do the same today. It also seems that I was wrong and that the Yeoman Maven Plugin can execute a specific grunt task. Though it will also run `npm install `and `bower install` before running that task.  `npm install `and `bower install` is however not that time consuming if there are no changes in the `package.json` and `bower.json` files. This means totally 7 seconds extra. Though it might take more time if more scss files are added.

**Comment by andidev** [comment]
Another alternative is to run compass compile from the generator file index.js
Then it will only compile once when the app is generated.
