### ISSUE TITLE
The newly generated project has a GitHub insights security alert about bootstrap.

### ISSUE THREAD

**Issue by slgxmh** [jhipster/generator-jhipster#9520]
as this screenshot

![image](https://user-images.githubusercontent.com/13213238/55311556-d7451580-5495-11e9-9ae4-12e2c7152624.png)

And in my newly generated project, the version of bootstrap is 4.2.1.
![image](https://user-images.githubusercontent.com/13213238/55312639-95699e80-5498-11e9-9b82-849adb2d045f.png)

**Comment by wmarques** [comment]
@slgxmh Thanks for the report. Indeed we need to bump our `bootstrap` version. Are you willing to do a PR to fix this issue ?

**Comment by slgxmh** [comment]
> @slgxmh Thanks for the report. Indeed we need to bump our `bootstrap` version. Are you willing to do a PR to fix this issue ?
 
I checked /master/generators/client/templates/angular/package.json.ejs , the version of bootstrap is right (4.3.1).
My project is generated by JHipster Online, maybe this problem caused by web site using the previous version。

**Comment by wmarques** [comment]
@slgxmh oh yes probably, i think this will be fixed once v6 is released I think.

**Comment by pascalgrimaud** [comment]
Yes, just wait the next release.
Already fixed in master branch here: https://github.com/jhipster/generator-jhipster/commit/5197f7428047ec39687afe1c93aaa6632d6f03b1
