### ISSUE TITLE
Customize "Initial application generation by JHipster" commit message

### ISSUE THREAD

**Issue by firmsoil** [jhipster/generator-jhipster#9522]
##### **Overview of the issue**

Customize "Initial application generation by JHipster" commit message

##### **Motivation for or Use Case**

For corporate use the commit message should be customizable "Initial application creation..."

**Comment by vishal423** [comment]
I think you can generate with `--skip-git` to not initialize and commit into new git repository

**Comment by pascalgrimaud** [comment]
There are several possibilities here:
- use `--skip-git` as suggested by @vishal423 
- use `git commit --amend` to change the default message

There is no real value to include this in the main generator, as it would be an additional flag.
