### ISSUE TITLE
Decouple front-end from api gateway in microservice architecture

### ISSUE THREAD

**Issue by hfye** [jhipster/generator-jhipster#9527]
##### **Overview of the feature request**

The generated front-end code either in Angular or React is bundled with api gateway for microservice architecture. And web security is heavily relying on the Spring security. Ideally we can move out the front-end code and let it running on servers in the web tier, while api gateway is running in the application tier. Both application will be protected by oauth2 SSO servers.

##### **Motivation for or Use Case**
As it's microservice architecture, it's better to run front-end and gateway in separate box, which also helps improve security and reduce ops downtime.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
This is not something we can do at the moment as it will complicate the architecture and templates further. I'm sorry. If you prefer to do it this way you can use the `--skip-server` and `--skip-client` flags to generate UI and server separately and achieve that design. those flags are here for these kind of use cases.
