### ISSUE TITLE
Can't use OAuth2 in dev with start-tls

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#9529]
##### **Overview of the issue**

If I try to develop on a generated application with OAuth2 and use `npm run start-tls`, after having logged-in on the Keycloak, the browser redirects me to https://localhost:9000 instead of http://localhost:9000 so it fails with a "Secure Connection Failed" (in Firefox).

##### **Motivation for or Use Case**

I should be able to develop in TLS mode when developing an OAuth2 application generated with JHipster.

##### **Reproduce the error**

Download the current https://github.com/jhipster/jhipster-sample-app-oauth2 (tested on commit a22ff50d6cd9bdbf7e4f5ed96e4c565dd0743c1e), patch:
 - `/webpack/webpack.dev.js` to replace ``target: `http${options.tls ? 's' : ''}://127.0.0.1:8080`,`` with ``target: `http${options.tls ? 's' : ''}://localhost:8080`,``
 - `/src/main/docker/realm-config/jhipster-realm.json` to replace `"redirectUris": ["http://localhost:8080/*"` with `"redirectUris": ["http://localhost:8080/*", "https://localhost:8080/*"` and `"webOrigins": ["http://localhost:8080/*"` with `"webOrigins": ["http://localhost:8080/*", "https://localhost:8080/*"`
(I don't understand by the way that my PR https://github.com/jhipster/generator-jhipster/pull/9177 to fix #9086 that would normaly apply such patches did not patch this project...)

Then launch:
 - `docker-compose -f src/main/docker/keycloak.yml up`
 - `./mvnw -Pdev,tls`
 - `npm run start-tls`

Access to http://localhost:9000 login in the Keycloack instance, this will correctly sign in then redirect to the wrong address https://localhost:9000

##### **Related issues**

I think in a way #9086 is still not fixed

##### **Suggest a Fix**

It seems that the browser after that it is requested from https://localhost:8080 to redirect to http://localhost:9000 is doing a `307 Internal Redirect` (we can track it with Chrome, not Firefox) with a `Non-Authorotative-Reason: HSTS` as a reason.
I tried to add this patch in `SecurityConfiguration.java`
```java
        if (environment.acceptsProfiles("dev") && environment.acceptsProfiles("tls")) {
            // delete STS while in dev + tls thanks to https://github.com/spring-projects/spring-security/issues/4099
            http.headers().httpStrictTransportSecurity().disable();
        }
```
but then I have XSR problems while `POST`ing

##### **JHipster Version(s)**

5.7.2

##### **Browsers and Operating System**

Windows 10, Firefox & Chrome

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
Any specific reason to access with `http://localhost:9000` and not <code>http<b>s</b>://localhost:9000</code> ?

**Comment by anthony-o** [comment]
Simply because webpack proxy, when using `start-tls` is still set on `http://localhost:9000` but perhaps it can be the real fix indeed: to use HTTPS even with webpack proxy when using the TLS option...

**Comment by anthony-o** [comment]
I've managed to fix this using https for the webpack proxy when using `start-tls` with the following modifications to `webpack.dev.js`:
```js
    devServer: {
        /* [...] nothing changed except the following line at the end of devServer config: */,
        https: options.tls
    },
/* [...] nothing changed until BrowserSyncPlugin */
        new BrowserSyncPlugin({
            host: 'localhost',
            port: 9000,
            https: options.tls, // added this line
            proxy: {
                target: `http${options.tls ? 's' : ''}://localhost:9060` // modified this line
            },
/* [...] nothing changed after that */
```
Now someone should add this to `jhipster-generator` if everybody agry to use https://localhost:9000 while developing with TLS option, http://localhost:9000 otherwise?

**Comment by DanielFran** [comment]
@anthony-o Can you do a PR please?

**Comment by anthony-o** [comment]
@DanielFran so it is OK for jhipster team to use https://localhost:9000 when using TLS and http://localhost:9000 if not?

**Comment by pascalgrimaud** [comment]
@anthony-o : just tested your PR and I got some issue. I'm not sure it comes from your PR or not
- start the application with `mvn -Pdev,tls`, so I can go to `https://localhost:8080` and it works well
- start `npm run start-tls`, browser opened at https://localhost:9000/
- when I want to sign in, it goes to https://localhost:8443/oauth2/authorization/oidc

I don't think it's related to your changes, but does it work for you ?
