### ISSUE TITLE
Application fail to start - The elements [jhipster.clientapp.name] were left unbound.

### ISSUE THREAD

**Issue by Kerruba** [jhipster/generator-jhipster#9537]
##### **Overview of the issue**

I've created a blueprint and in this blueprint I want to extend the application.yml file to include spring.data.rest.base-path configuration. I've copied the application.yml file from the generator-jhipster repository and added a step to copy the new application.yml (and override the previous one). JHipster is able to pick the blueprint up and create all the necessary files, though when running the application with `./mnvw`, the application fails to start with this error message
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target [Bindable@84977b2 type = io.github.jhipster.config.JHipsterProperties, value = 'provided', annotations = array<Annotation>[@org.springframework.boot.context.properties.ConfigurationProperties(ignoreInvalidFields=false, ignoreUnknownFields=false, value=jhipster, prefix=jhipster)]] failed:

    Property: jhipster.clientapp.name
    Value: entandoTokenPluginApp
    Origin: class path resource [config/application.yml]:144:11
    Reason: The elements [jhipster.clientapp.name] were left unbound.

Action:

Update your application's configuration
```

##### **Motivation for or Use Case**

I wanted to extend the application.yml file with my custom properties inside, but copying the one provided from generator-jhipster repository is not working out of the box

##### **Reproduce the error**

The blueprint I'm using is currently in development and available @ https://github.com/Kerruba/myfirstblueprint/tree/spring-data-rest. 
I had to comment out the clientApp.name property for the application to work

I've included the blueprint the usual way:
```
// in the blueprint
npm link

// create a new folder
mkdir my-blueprint-test-app && cd my-blueprint-test-app

// link the blueprint
npm link generator-jhipster-entando

// create the app using the blueprint
jhipster --blueprint entando
```

##### **JHipster configuration**

INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
##### **JHipster Version(s)**

```
entando-token-plugin@0.0.0 /home/kerruba/Development/entando/dev-projects/test-blueprint-datarest
└─┬ generator-jhipster-entando@0.0.0 -> /home/kerruba/Development/entando/jhiptests/entandoBlueprint
  └── generator-jhipster@5.8.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "it"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "org.entando.plugin.token",
    "packageFolder": "org/entando/plugin/token",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "entandoTokenPlugin",
    "applicationType": "microservice",
    "buildTool": "maven",
    "authenticationType": "jwt",
    "jhipsterVersion": "6.0.0-beta.0",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "hazelcast",
    "serverPort": "8081",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-entando",
        "version": "0.0.0"
      }
    ],
    "blueprint": "generator-jhipster-entando",
    "blueprintVersion": "0.0.0"
  },
  "entities": [
    "Token"
  ],
  "generator-jhipster-entando": {
    "jhipsterVersion": "5.8.2",
    "applicationType": "microservice",
    "baseName": "entandoTokenPlugin",
    "packageName": "org.entando.plugin.token",
    "packageFolder": "org/entando/plugin/token",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Token {
  value String required unique minlength(16),
  type String required,
  registrationTime LocalDate required,
  associatedUsername String required
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1

node: v10.15.3

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

-   [ X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
The `application.yml` on this repository's master branch is for `generator-jhipster` v6, but your `generator-jhipster` is v5.  You can copy [the config from v5.8.2](https://github.com/jhipster/generator-jhipster/blob/v5.8.2/generators/server/templates/src/main/resources/config/application.yml.ejs) which doesn't have the `clientApp` config variable.

**Comment by Kerruba** [comment]
Ok thanks, there's a way of blocking of blocking the use of a blueprint if not compatible with the JHipster version you want to develop against?

**Comment by PierreBesson** [comment]
@Kerruba Not that I know of. But @avdev4j has a trick so that the blueprint uses the JHipster version that it sets as npm dependency in the blueprint package.json. Maybe he can share it here.

**Comment by avdev4j** [comment]
Hi @Kerruba 
To do this you should look at this PR https://github.com/jhipster/generator-jhipster-blueprint/pull/30

I plan to write a medium story to explain how to do that if the PR will not be accepted.

Does it fix your issue?
