### ISSUE TITLE
Using react-kotlin in jhipster

### ISSUE THREAD

**Issue by j209** [jhipster/generator-jhipster#9542]
Hi
What about using [react-kotlin](https://github.com/JetBrains/create-react-kotlin-app) instead of react in jhipster.
In this situation both backend and front end can develope in one language.Kotlin!

**Comment by pascalgrimaud** [comment]
You can use this blueprint https://github.com/jhipster/jhipster-kotlin to generate an application with:
- React for frontend
- Kotlin for backend

**Comment by unknowedNp** [comment]
Can use kotlin as fronted language ?
use kotlin and no js ?

**Comment by mraible** [comment]
@unknowedNp Nope.
