### ISSUE TITLE
Using resilience4j as a possible circuit breaker option beside Hystrix

### ISSUE THREAD

**Issue by Romeh** [jhipster/generator-jhipster#9543]
##### **Overview of the feature request**

Can we add a support to use resilience4j as a circuit breaker as an alternative to Hystrix as a Hystrix now is just on maintenance state  

##### **Motivation for or Use Case**

As Hsyrix is on maintencane state and Netflix guys are pushing people to look for other alternative like Resilience4j , it would be cool to add support to it 

I can help here if you would like as i am contributor in resilience4j as well.

**Comment by deepu105** [comment]
Sorry given the workload and options we have, I don't think we have the bandwidth to provide more options here.

**Comment by jdubois** [comment]
Yes, it should probably replace Hystrix at some point, but I'd rather wait 1 or 2 years to see where this is going.

**Comment by jdubois** [comment]
I think we should add this to our v7 roadmap at #10958

@Romeh would you still be interested in helping on this? Do you think this is a big change (I don't expect it is, but I have no experience in this migration)?

**Comment by atomfrede** [comment]
Maybe https://github.com/robwin can help here too.

**Comment by gmarziou** [comment]
Is it more than "just" using spring-cloud-starter-circuitbreaker-resilience4j and adjusting application properties?

**Comment by RobWin** [comment]
You can either use spring-cloud-circuitbreaker or our Spring Boot starter which adds much more features like support for Annotations, Spring Cloud Config support, Retry, RateLimiter, Bulkhead,...

**Comment by DanielFran** [comment]
@RobWin @Romeh Are you still willing to work on this feature?
