### ISSUE TITLE
Support in aws-containers deploy a Aurora serverless db

### ISSUE THREAD

**Issue by andreaschiona-tria** [jhipster/generator-jhipster#9546]
##### **Overview of the feature request**
Enable the deploy of an application with a serverless database

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Hi @andreaschiona-tria 
I don't know if it's already done or not, as I couldn't test AWS sub generator.

Did you try our current sub generator AWS ?
Did you read our documentation ? https://www.jhipster.tech/aws/
Would you like to contribute and propose improvement to our sub generator ?

**Comment by andreaschiona-tria** [comment]
Hi @pascalgrimaud ,

I tried the current sub generator AWS and there isn't this option. I can only create "standard" Aurora database.
I read the documentation yet, but I can't find any details about this option.

How can I contribute ? Where can I propose improvement?

Thanks,
Andrea

**Comment by PierreBesson** [comment]
Hi @andreaschiona-tri,

You are in the right place to propose an improvement 😄. However your feature request description is only one line and lacking the requested information. This is not in agreement with our guidelines. Please edit your issue to add more details and especially a "motivation" section and maybe a proposal of implementation. Then the feature request can be accepted by the team and you or someone else can start working on it and submit PRs.

For more info on how to contribute to the project, please refer to https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by pascalgrimaud** [comment]
It's very hard for the team to test and maintain the AWS sub generator.

It looks like you're the only one who asked this, do you plan to contribute to improve the AWS sub generator @andreaschiona-tria ?

**Comment by andreaschiona-tria** [comment]
Hi @pascalgrimaud at the moment I use gradle plugin to deploy to aws (via cloudformation) so I don't plan to work to aws sub generator.

Regards,
Andrea

**Comment by PierreBesson** [comment]
I guess most people who deploy to aws cannot really contribute their setup as it is heavily dependent on their own infrastructure.
However it would be cool to setup this gradle plugin you are talking about. Actually our Heroku and Google app Engine deployments are already setup using a maven/gradle plugin.

**Comment by pascalgrimaud** [comment]
Thanks for your answer @andreaschiona-tria
That's fine so, let's close this ticket as it won't be done for now.
