### ISSUE TITLE
Change the packaging to jar and configure a war profile

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#9547]
##### **Overview of the issue**

Needs update to documentation explaining that jar packaging is the default and how to use war profile when needed.

##### **Motivation for or Use Case**

See PR https://github.com/jhipster/generator-jhipster/pull/9034 for implementation but no information about documentation changes.

##### **JHipster Version(s)**

v.6.0.0-beta0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@PierreBesson : just to let you know, I'm starting this

**Comment by pascalgrimaud** [comment]
Closing this, as the PR to jhipster.github.io is done.
It will be merged for v6
